### ISSUE TITLE
only contributors to submit expenses

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#100]
now that we are improving the flow through which contributors are added to a collective. I think we should allow only contributors to submit expenses. As this scales, it will become increasingly difficult the manage the approval and doing this removes a layer of complexity. 

What was the logic behind allowing anyone to submit an expense?

**Comment by asood123** [comment]
A few reasons we did this:

1) We didn't have a login system in place. It's something we need to build for other reasons as well.
2) It's a heavy enough action that we are unlikely to see random expenses submitted. It's like Pull Requests on Github, anyone can submit it. The organizers can discuss, ignore, or close it if they don't want it.

Are we seeing examples of people submitting errant expenses that they shouldn't be?

**Comment by piamancini** [comment]
We haven't seen that yet. But:
1) It's an inefficient flow: an expense submitted I see it in the activity feed, contact the organizers to see if it's legit and then approve it. It's fine now because it's small but if if do our job right, it shouldn't be fine much longer. 
2) It's a problem for large organizations like wwcode who don't know their local chapters members and they want to avoid the pain of adding a step in the process of managing financials - which we are trying to remove friction from. They specifically said this was a security issue for them.
