### ISSUE TITLE
Account deletion and deletion policy

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#1002]
We often get requests from users wanting to remove their accounts. Since we are a public ledger of record, this can sometimes put us in odds with these requests. We need a clear policy that lays out scenarios and can be accessed by any user.

Here are general guidelines:
- If a user/collective/event hasn't touched any money or taken any other action (update, comment, etc), we can mark them as deleted. (note this can still create an issue later if that user tries to signup with that email address). Maybe a better solution is to create a "Remove identity" function. That can remove identifying info for a user and still leave that row intact. This reduces risk of that user row's deletion causing issues later (like in Activity Table or Events or Tiers etc).
- If there's funding involved, we can allow users to remove their name (but their email must remain?). 
- If there's funding involved, collectives shouldn't be deleted. Otherwise, there is risk of users abusing funds and then closing the collective. We can instead mark that collective as "Inactive" and thus show a different UI, while still maintaining its ledger.

We can also define a few different that need to be supported over time:
1. Active (visible, most common state)
2. Inactive (visible and no action allowed - useful for Collectives)
3. Hidden (Inactive and not visible)
4. Marked deletedAt in DB (not available outside DB)
5. Deleted (truly deleted, shouldn't be used in the ideal world; instead, we should keep the row and remove its contents)

Easiest path maybe to support Inactive (which is already in Collectives table) and Hidden for users. 

More thought needed on this issue.

**Comment by piamancini** [comment]
yes. closing in favor of it #1317
