### ISSUE TITLE
address is not showing up in individual invoices

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1007]
Address is added in postico but it's not showing up in the individual transaction invoices.
It shows up in the monthly one.

**Comment by asood123** [comment]
Do you have an example where it's broken? I see the address for my own subscriptions.

**Comment by piamancini** [comment]
emailed you one

**Comment by piamancini** [comment]
closed via https://github.com/opencollective/opencollective-website/pull/801
