### ISSUE TITLE
add an identifier to expenses.

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1008]
We need to make it easier to reference expenses, a) for users who want to reference them and b) for Alanna so she can make a note of payment processor fees when she pays manually via paypal (atm I search for txn ID to identify them)

**Comment by piamancini** [comment]
we are solving the immediate need with #1012 but this is still something we should do that will improve communication with users for de-bugging

**Comment by xdamman** [comment]
We now provide a unique URL per expense that includes its id: e.g. https://opencollective.com/webrussels/expenses/1309
