### ISSUE TITLE
Cannot complete application for the Asciidoctor project

### ISSUE THREAD

**Issue by mojavelinux** [opencollective/opencollective#1010]
I'm attempting to submit an application for the Asciidoctor project to accept funding through OpenCollective. However, I'm stuck at the repository selection screen. Although [asciidoctor/asciidoctor](https://github.com/asciidoctor/asciidoctor) has well over 100 stars, and I'm the owner of both the asciidoctor organization and the repository, the repository does not appear in the repository selection list.

What I can tell you is that the asciidoctor/asciidoctor repository has been migrated to the new team permission model, so it likely does not have the legacy owner scope that the OpenCollective code is looking for. In that case, I will need someone to push the application through manually.

Here's the account I'm attempting to hook the asciidoctor/asciidoctor repository to:

URL (project): https://asciidoctor.org
URL (OpenCollective): https://opencollective.com/asciidoctor
Logged in as: mojavelinux

If you need any other information from me, don't hesitate to ask. Thanks in advance!

**Comment by mojavelinux** [comment]
I don't understand what you mean by oauth-ing using the org. The org isn't an account on GitHub. My personal account owns the org. As far as I understand, that's the only type of ownership you can have on GitHub. I was not aware that an organization can sign in itself.

**Comment by asood123** [comment]
See for example the section in this oauth screen under "Organizational access". <img width="605" alt="screenshot 2018-04-17 17 02 35" src="https://user-images.githubusercontent.com/6106941/38896618-2aca72ce-4261-11e8-82f8-3039a6c78ced.png">

Can you please share what your oauth screen looks like?

**Comment by asood123** [comment]
You may need to revoke access at https://github.com/settings/applications.

**Comment by mojavelinux** [comment]
I understand what the problem was now. The Asciidoctor organization [has restricted access for third-party applications](https://help.github.com/articles/about-oauth-app-access-restrictions/). Therefore, it's necessary to explicitly Grant access on the oauth screen.

![grant-oauth](https://user-images.githubusercontent.com/79351/38901534-c343afa0-4259-11e8-8c16-74c7dfd475fe.png)

Once I did that, it worked. I have successfully submitted the application.

This is the key detail that was missing from the instructions. Perhaps you can consider adding a heads up about this.

**Comment by mojavelinux** [comment]
(the Revoke button indicates that I pressed Grant).

**Comment by piamancini** [comment]
this was solved

**Comment by mojavelinux** [comment]
Indeed it was. Thank you so much for the assistance!
