### ISSUE TITLE
Writing an update, draft makes content "undefined"

### ISSUE THREAD

**Issue by luceos** [opencollective/opencollective#1014]
URL: https://opencollective.com/tenancy/updates/new#
Logged in as: https://opencollective.com/luceos
Error message if any: none
Expected result: see the content i wrote.
Received result: `undefined` instead of content
Browser: 
![image](https://user-images.githubusercontent.com/504687/38888967-78fd3d8e-427d-11e8-9fd6-eb9e0fe4db5b.png)

![image](https://user-images.githubusercontent.com/504687/38888986-892a352c-427d-11e8-9e40-c74e2149f671.png)

Copied content over from a draft patreon post. Continued writing then pressed submit.

**Comment by piamancini** [comment]
thanks Daniel. We'll look at it on bug fix day on Friday. I'm assigning a priority.
