### ISSUE TITLE
Visualization error on Brussels together

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#1016]
Just reporting this on https://opencollective.com/brusselstogether#

![screen shot 2018-04-17 at 4 52 58 p m](https://user-images.githubusercontent.com/30665166/38900146-08039d3e-4260-11e8-88ef-b746b4f37ce3.png)

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by xdamman** [comment]
Looks good for me. What's your browser and language?
![](https://d.pr/free/i/6p5eR1+)
