### ISSUE TITLE
Calculate and populate Paypal fees

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#102]
Docker is using Paypal to receive money. Currently, we only calculate and populate fees automatically for Stripe transactions.

For collectives receiving money from Paypal, we need to:
1) calculate host fees, platform fees, and txn fees
2) Investigate how paypal handles transactions in different currency (meaning, currency other than the currency of the account). what information does it give us? 
3) Populate backend transaction table with fees and currency info

**Comment by piamancini** [comment]
@asood123 this we'll need to do...

**Comment by piamancini** [comment]
We are not allowing paypal donations any more.
