### ISSUE TITLE
Allow backers/sponsors to pledge to future collectives

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1020]
## Problem we are trying to solve:

Many sponsors would love to sponsor either specific projects that are not (yet) on the platform, or a category (e.g. all Machine Learning meetups in this region).

## Proposed solution:

We could introduce the concept of a pledge. Any backer could pledge any amount towards any combination of tags and of websites (e.g. a GitHub URL or a Meetup.com URL).

We could have a page `/pledges` that would list all the pledges as a way to invite people to create collectives to claim them.

## MVP

We could implement pledges the way we implement goals. We simply store them in the `collective.settings` column. It's not ideal because we would want to be able to query all pledges. So it's not the preferred way.

I think it would be better to have a `Pledges` table with `FromCollectiveId`, `tags`, `url`, `description`, `longDescription`, `createdAt`, `deletedAt`.

- `/:collectiveSlug/pledges/edit`
Edit the pledges. Would be great to also accept a `package.json` as input.

- `/pledges`
List all the pledges across the platform.

## Claiming a pledge

To claim a pledge, one has to create a collective that matches the tags or the URL (GitHub url, meetup url, ...). Pledges wouldn't be automatic. Instead, whenever there is a new collective that matches a pledge, we send an email to the owner of the pledge. And we can let the admins of the collective know that we have notified x pledges.

That way it's safe for any backer to make a pledge as it's just a way to be notified.
A second version could include the ability to actually put money down but that's much more complex to develop.

**Comment by piamancini** [comment]
I agree that the correct way of thinking about this is to have a pledges table and make them discoverable by anyone in the /discover page.

We could include a pledged tier too (this was suggested by a sponsor). example: a 500/m tier with sponsors logo on every page of their doc. 

Definitely pledges shouldn't be automatic. We can treat the claiming a pledge as an apply to a host. It's pending review and author of the pledge can hit accept/reject in an email

**Comment by piamancini** [comment]
we need an owner of this feature.
