### ISSUE TITLE
Login emails are not delivered

### ISSUE THREAD

**Issue by kamilmysliwiec** [opencollective/opencollective#1021]
URL: https://opencollective.com/signin
Logged in as: mail@kamilmysliwiec.com
Error message if any: -
Expected result: Login email is delivered (I can log in to my account)
Browser: Chrome

I received a 'Login email sent. Please follow the instructions in that email to proceed.' message, but email is never delivered. I have tried a few days ago without succeeding, today I did it once again and unfortunately, nothing changed (spam dir is empty as well).

**Comment by piamancini** [comment]
Hi Kamil, we are seeing the emails going out of our servers, so it looks like the are blocked by your email server. I just forwarded you one to unblock you now.

**Comment by piamancini** [comment]
I’m closing this issue since the emails are being sent so there’s little on our end we can do. Feel free to reopen if you need to.

**Comment by kamilmysliwiec** [comment]
Thanks @piamancini, I'll contact with them.

**Comment by piamancini** [comment]
Hi @JimBobSquarePants we've filed a ticket with mailgun. For some reason they are blocking our emails to outlook. I am very sorry about this. We'll send you a new token now manually

**Comment by greysonp** [comment]
I'm experiencing this issue with my Gmail account (greyson.parrelli@gmail.com). I've tried twice and waited ~30min and haven't seen anything (including spam).

**Comment by greysonp** [comment]
Just got 'em. Might have been backed up or something.
