### ISSUE TITLE
Update email doesn't show which collective it's from

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1024]
Unless they happen to name the collective in the text of the update, or you look at the email sender details and notice the subdomain address, there's no way to tell which collective an update is from when you receive it as an email. Could it say "Update from [Collective]" at the top maybe?

**Comment by piamancini** [comment]
yes, it's extra confusing because it has the open collective footer

**Comment by xdamman** [comment]
Fixed in https://github.com/opencollective/opencollective-api/pull/1244
