### ISSUE TITLE
don't include Approve button in Collective Pending email to collective creator

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1029]
approve is a host functionality not a creator's functionality

**Comment by xdamman** [comment]
We don't. Can you show me an example of that happening?
We only send that approve button to the admins of the host.

**Comment by piamancini** [comment]
@xdamman sure, the creator of this collective received this email
<img width="834" alt="screen shot 2018-05-07 at 3 08 12 pm" src="https://user-images.githubusercontent.com/3671070/39719909-a6ccb718-5208-11e8-95d0-3146015cea5b.png">

**Comment by piamancini** [comment]
This happened again @xdamman 

![screen shot 2018-08-13 at 2 03 05 pm](https://user-images.githubusercontent.com/3671070/44049291-b56e34ae-9f01-11e8-9750-196e46b3f8b6.png)

User approved it and got an error that is correct but was confusing for him since he was logged in: 
![screen shot 2018-08-13 at 2 04 21 pm](https://user-images.githubusercontent.com/3671070/44049312-c2b52cf8-9f01-11e8-9102-cadd8f03524b.png)

**Comment by piamancini** [comment]
We are actually including an approve button in all emails to admins. Just search on emailbcc for "New Collective Pending"
latest example: 
![screen shot 2018-08-13 at 2 05 24 pm](https://user-images.githubusercontent.com/3671070/44049466-33dee40a-9f02-11e8-9a9a-62ce2aa5a1dc.png)

**Comment by piamancini** [comment]
this popped up again @xdamman in slack. Let's fix it, it's confusing for people.
