### ISSUE TITLE
Add labels to post-donation flow

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#103]
In the post-donation flow, if all the fields are filled out, user can't tell what field is what. 
![screenshot 2016-05-31 13 14 20](https://cloud.githubusercontent.com/assets/6106941/15683697/9d91cfc0-2731-11e6-855a-19d1c1703599.png)

**Comment by piamancini** [comment]
and the upload should be the first option not the last for the profile image

**Comment by asood123** [comment]
Can we make upload the first option if we didn't find any image for them? Otherwise, we should show that first.

**Comment by carlosascari** [comment]
Can do, will do

**Comment by carlosascari** [comment]
@asood123 
I've sent a PR with the fixes here: https://github.com/OpenCollective/opencollective-website/pull/277

Basically icons are used instead of a text label to preserve vertical space and keep the ImagePicker and the inputs aligned, here is a preview

![now](https://my.mixtape.moe/fkojfq.png)

**Comment by asood123** [comment]
Looks nice, @carlosascari
