### ISSUE TITLE
Administration interface with Forest

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1031]
### Collectives

  - Display: id, type, slug, name, currency, created_at, is_active
  - Update, delete (No creation)
  - Segments
    - Collectives (type=COLLECTIVE)
    - Organizations (type=ORGANIZATION)
    - Users (type=USER)

### Expenses

  - Display: id, user, collective, category, amount, currency, status, created_at
  - Update, delete (No creation)
  - Links:
    - User
    - Collective

### Members

  - Display: id, role, member collective, collective, tier, created_at
  - Update, delete (No creation)

### Orders

  - Display: id, subscription, tier, total amount, currency, from collective, collective, created_at
  - Update, delete (No creation)

### Payment Methods

  - Display: id, collective, uuid, name, primary, type, service, created_at
  - Update, delete (No creation)
  - Links:
    - Collective
  - Associations:
    - Orders
    - Transactions

### Subscriptions

  - Display: id, order, amount, currency, created_at, is_active
  - Update, delete (No creation)
  - Links:
    - Order 
  - Actions:
    - Cancel subscription (deactivate)
    - Activate subscription

### Tiers

  - Display: id, type, name, collective, amount, currency, created_at
  - Update, delete (No creation)
  - Links:
    - Collective 

### Transactions

  - Display: id, uuid, type, amount, currency, host, from collective, collective, created_at
  - Update, delete (No creation)
  - Links:
    - Host
    - From Collective 
    - Collective 

### Users

  - Display: id, full name, email, collective, created_at
  - Update, delete (No creation)
  - Links:
    - Collective 

## Actions

  - [x] Cancel Subscription
  - [x] Activate Subscription
  - [x] Delete User
  - [x] Delete Collective
  - [x] Merge User

## Links

 - [ ] See User from Collective[type=USER]

**Comment by piamancini** [comment]
- When deleting a collective (making it as deletedAt) a string needs to be appended to the slug otherwise, that slug will be unavailable in the future. I usually do "_old"

**Comment by patcon** [comment]
Ref: https://www.forestadmin.com/compare/forest-for-nodejs/
