### ISSUE TITLE
Include upload of W8/W9 when submitting an expense

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1033]
Hosts in the US are required to have w9 (to issue 1099s) and w8-ben /ben-e for individuals/companies that invoice +$600 a year.

Right now the process is very manual, I email them and ask for it and we also include this in the wiki and FAQs.

It'd be nice to include a way for users to upload this in a secure way before submitting an expense.

**Comment by xdamman** [comment]
Can you give us a sense of how many W9 and W8-ben we are talking about here per year?
Maybe adding a custom expense policy field per host / collective could help mitigate this for now (a US host could add a word of explanation about this and request people to send that form by email)

**Comment by piamancini** [comment]
It's anyone who is receiving more than +600 a year.
Last year that was 42 (and we might have missed several of them, specially w8s)

**Comment by piamancini** [comment]
closing this in favor of #1200
