### ISSUE TITLE
Submit expense - no email received

### ISSUE THREAD

**Issue by Carodem** [opencollective/opencollective#1035]
Hello ! 

I tried several times to submit an expense on our collective (HuNeeds hosted by BrusselsTogether):
https://opencollective.com/huneeds#

I entered my email address to sin in but nothing happens : 
![capture d ecran 2018-04-30 a 09 46 11](https://user-images.githubusercontent.com/36923849/39418585-8816543a-4c5b-11e8-8351-06b259dd5d19.png)

Thank you !

**Comment by piamancini** [comment]
Hi @Carodem mailgun is blocking emails to hotmail again, I've already opened a support ticket with them. I just forwarded you a login token you can use for the moment.  You should be able to remain logged in for 30 days.

**Comment by piamancini** [comment]
Closing this, since mailgun solved it/
