### ISSUE TITLE
Remove incorrectly created organisation (not the collective)

### ISSUE THREAD

**Issue by luceos** [opencollective/opencollective#1037]
Thanks for all the hard work 🙏 

I mistakenly created an organisation thinking I was creating a collective.

If possible could someone delete https://opencollective.com/flarum-org

Sorry about that 😞

**Comment by piamancini** [comment]
Hi @luceos We'll delete it, worry not. We are using this case to test a new database internal dashboard,  we have. Do you mind waiting a day or two so we tinker with this?

**Comment by piamancini** [comment]
cc / @znarf

**Comment by znarf** [comment]
Deleted.
