### ISSUE TITLE
an organisation is listed as collective

### ISSUE THREAD

**Issue by luceos** [opencollective/opencollective#1041]
So by mistake I made an organisation instead of a collective. Now both show up under collectives:

![image](https://user-images.githubusercontent.com/504687/39444619-b63772d8-4cb8-11e8-8415-9930eaaa82c1.png)

`flarum-org` is the organisation: see https://opencollective.com/flarum-org
vs `flarum` which is the collective https://opencollective.com/flarum

**Comment by piamancini** [comment]
cc / @xdamman Maybe you can look into this when you add the 'create collective' to the menu. The org should appear under 'organizations?' It's adding to the general confusion.

**Comment by piamancini** [comment]
this is now fixed. profile makes the distinction between collectives and organizations.
