### ISSUE TITLE
Allow configuration of webhooks for collective mutations

### ISSUE THREAD

**Issue by luceos** [opencollective/opencollective#1043]
It would be helpful to have (initial) webhook functionality. This would allow pushing information whenever it happens about pledges, updates etc.

My use case is that I currently list all my backers on the website. This list is updated using a cron and cached for a limited time. It would be great to be able to cache the list permanently and rely on the webhook call to update for changes.

**Comment by xdamman** [comment]
Would love to see that. Would also be useful to have a Zapier.com integration.

**Comment by xdamman** [comment]
Related: https://github.com/opencollective/opencollective/issues/464

**Comment by Betree** [comment]
The progress for this issue is now being tracked by https://github.com/opencollective/opencollective/issues/1839. We're now working on it.
