### ISSUE TITLE
Missing "Pay" button

### ISSUE THREAD

**Issue by mroderick** [opencollective/opencollective#1046]
URL: https://opencollective.com/sinon
Logged in as: mroderick
Error message if any: 
Expected result: A "Pay" button, that would allow me to pay people
Browser: Safari

![2018-05-02 at 11 21](https://user-images.githubusercontent.com/20321/39520958-ceb8ce38-4e0c-11e8-9788-2977d846a1f9.png)

**Comment by piamancini** [comment]
Hi Morgan, you are the admin of the collective but the Sinon is hosted(fiscal sponsored) by Open Source Collective 501c6. Only the host pays for expenses, and we do it every Friday. 
More info: https://github.com/opencollective/opencollective/wiki#managing-funds
If you want to become the host of your collective (receive the funds for it in a bank account you own) you can become its host. Read more here https://github.com/opencollective/opencollective/wiki/Becoming-a-Host

**Comment by mroderick** [comment]
Thanks @piamancini.

Perhaps a text update to the UI would save future support cases :)

**Comment by piamancini** [comment]
Yep for sure, thanks for the feedback
