### ISSUE TITLE
Show company name in list of backers on Github

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#105]
We want to incentivize companies to give a monthly budget to their engineers to back open source projects. It would be good to give them credit for that.

@erickrico Can you come up with a design to show that information in the list of backers in the github integration?

![context](https://cloud.githubusercontent.com/assets/18429104/14970446/94216efa-108e-11e6-89a5-8548bcadc03f.png)
Source: https://github.com/OpenCollective/OpenCollective/issues/50#issuecomment-216388611

**Comment by erickrico** [comment]
we can try something like this:



### The Open Source Initiative
--
These awesome companies give their engineering team a monthly budget to **support open source projects** they use during their development, join the ini

![initiative](https://cloud.githubusercontent.com/assets/18429104/15723980/9b6f9e3c-280a-11e6-9952-7f17e85b76fb.png)

**Comment by xdamman** [comment]
Problem with that is there is no link between those companies and the backers. We should convey that Aseem is working for company X.

**Comment by erickrico** [comment]
### The Open Source Initiative
--
These awesome companies give their engineering team a monthly budget to **support open source projects** they use during their development, join the initiative

![initiative](https://cloud.githubusercontent.com/assets/18429104/15728166/799ac276-2820-11e6-9e27-015142f66fd5.png)
![btn](https://cloud.githubusercontent.com/assets/18429104/15728334/79c11c72-2821-11e6-85e6-e992f5c989ba.png)

**Comment by piamancini** [comment]
Nice!

**Comment by dasilvacontin** [comment]
> We want to incentivize companies to give a monthly budget to their engineers to back open source projects.

:O Cool idea.

Regarding the design, I'm not sure about those edge-to-edge lines... I've gotten used to them separating sections. e.g. sections in a README (h2, h3), on the right of an issue/PR: Labels, Milestone, Assignees, etc.

So if this layout / partial were to be put in a page that uses lines to separate sections at a higher level, I think it would feel a bit confusing. Lines should be used to separate the same kind of thing.

**Comment by xdamman** [comment]
Design is great! 👍 

I'm just worried about the fact that in most cases there will only be one or two faces for each company.
Can you do a design with a few faces without a company, and one or two companies with only one or two faces?

**Comment by dasilvacontin** [comment]
Also, I just realised that GH solves the lines thing using a lighter shade. (section one is #dddddd, list one is #eeeeee)
<img width="267" alt="screenshot 2016-06-03 00 06 33" src="https://cloud.githubusercontent.com/assets/1260830/15762619/221cec18-291f-11e6-9aec-9c0244c35ebb.png">

**Comment by erickrico** [comment]
### The Open Source Initiative
--
These awesome companies give their engineering team a monthly budget to **support open source projects** they use during their development, join the initiative

![faces](https://cloud.githubusercontent.com/assets/18429104/15764745/02f9cb02-28f3-11e6-9e36-6d847d86b3a7.png)

**Comment by piamancini** [comment]
It looks really good I think even with few backers per company

**Comment by nayafia** [comment]
I know these are just mockups but you may want to use a different term than "Open Source Initiative" to avoid confusion with https://opensource.org/ :)

**Comment by xdamman** [comment]
Yes we shouldn't use this copy. Suggestions welcome :-)
"Contributors"? "Our collective"?
Also the text should be more generic because that section also includes individual contributors that are not part of a company (or contributing outside of their company time).

**Comment by piamancini** [comment]
Leaving this open for the moment. We've discussed something similar with @nayafia. I don't want to let this go.
