### ISSUE TITLE
Aggregated monthly report for backers/sponsors

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1050]
The goal is to provide a consolidated view by email of all the collectives that a backer (sponsor) supports.
E.g. AirBnB is supporting 11 collectives. It's hard for them to go through all the updates of them all. An overall overview that they can easily use for their reporting internally would be very useful.

![](https://d.pr/free/i/sSWkbR+)

**Comment by piamancini** [comment]
Ideally we want to show sponsors aggregated data across their collectives like: 
- total donated across collectives that month, type of collective, collective's tags
- how much was spend in engineering, travel, etc?
- link to the updates of the collectives they sponsor

V2: 
Brought in from external sources:
- how many commits the OS repo had that month / closed issues? / new contributors
- how many events a meetup made / how many participants

**Comment by xdamman** [comment]
This implies a much larger rewrite of the monthly email than I thought.

## Right now:
- We only show the active monthly subscriptions. Moving forward, we would want to also show collectives to which we have made a one time donation last month. Correct?
- We only process Users and not organizations. That means that only the person who created the organization receives the email and it's mixed with their personal contributions (if any)

## Moving forward:
- We need to process users and organizations differently. The report for organizations should be sent to all admins
- We should include all donations made last month, even one time ones

## Technically:
1. Compute the stats for all collectives, store result in memory
2. Go through all distinct `FromCollectiveId` (User, Organization or Collective) that have made at least one transaction past month
3. Compute aggregate stats, generate email, send to admin(s) of `FromCollectiveId`

## Open questions:
Do we want to embrace the micro services architecture? Should we move this outside of the API to keep the API small and clean and free from generating HTML? That means that we won't be able to re-use the models. Maybe it's not too big of a deal?

**Comment by clarete** [comment]
I think its always a good idea to think about the modularity of system components. And although I do agree that factoring out some of our codebase to external services might help keeping the API concise and maybe even small, our main problem is probably in the sharing of data, not code.

If we're thinking about using the same database for these other systems, we're not really doing microservices, we're just doing a distributed monolith :smile: 

The easier way to start doing actual microservices is to identify pieces of the codebase that don't require any shared state with the rest of the application and can do their work with a small amount of information provided by the API during the scheduling of work. The notifications system is a good example of that. The entire work of sending notifications can be done without querying the database if the notifications microservice know which content an email should have and to which address it should be sent.

If we need to do a lot of database calls within the "microservice" in question, the value of transforming a piece of code in an actual microservice is smaller. But if we're still only reading from the database it's better than if we need to write to it. In that case we can always come up with a read replica for the database, this way separate services can't compromise the main db. The problem with this approach is that we introduce synchronization issues between the main db and the replica. And code depending on the replica would have to be written with the synchronization delay in mind.

These are the issues that I think people usually encounter when they start talking about microservices.

**Comment by xdamman** [comment]
Thank you both for your input.

This monthly report only needs read access to the database to compute the stats and could potentially have its own database to keep track of what emails have been sent and maybe manage unsubscriptions? (that's less clear as we would want to let the frontend edit those email preferences, but I like the idea of having all those notifications contained somewhere, any thoughts?)

The problem it solves is avoiding to bloat the code base of the API and therefore make it easier to test and update independently. *Most importantly, I think the main value is to make it easier for people to contribute*. Smaller loosely coupled services would make it easier for someone to fork the code, create or customize an existing report and send a pull request.

I like the idea of a separate npm module for Sequelize models.

I think if we start with notifications, it won't break the API or the frontend. So it seems like a safe place to start.

I don't know if the the frontend should only communicate with the API. It seems safer at least as a place to start.

And for cross service communication, I guess having a common hub makes sense.
I don't think it's needed right now for sending email notifications though.

**Comment by xdamman** [comment]
The other question is whether this separate service should have its own GitHub repo?
I'm torn on this question.

On one side I like the concept of mono repo (makes sure that everything works as a whole, you don't need to wait to update the API before updating the frontend for example).

On the other side, I like the architecture of node and loosely coupled node modules. Every module has its own repo and people can contribute to a particular module without having to download and worry about the dependencies.

Any thoughts on this?

**Comment by xdamman** [comment]
Coming together nicely

![](https://d.pr/free/i/ps11Df+)

**Comment by piamancini** [comment]
@xdamman looks great!

**Comment by clarete** [comment]
@xdamman 
> The other question is whether this separate service should have its own GitHub repo?
I'm torn on this question.
>
> On one side I like the concept of mono repo (makes sure that everything works as a whole, you don't need to wait to update the API before updating the frontend for example).
>
> On the other side, I like the architecture of node and loosely coupled node modules. Every module has its own repo and people can contribute to a particular module without having to download and worry about the dependencies.

I don't have any strong preferences here. I've been working one repo per project for a while, but I'd certainly be excited to try the single repo approach. I think the important question here is how to deploy these new services and how they'd talk to each other.

Although heroku seems to be more compatible with the one project per repository approach, it does seem to support the concept of workers (background services). https://devcenter.heroku.com/articles/background-jobs-queueing

Maybe we could create a worker based on whatever queue service we agree on and it'd still be easy to deploy under heroku. I'll check if heroku has any queue services available via addons.
