### ISSUE TITLE
Add goals with their description to the collective page

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1052]
Right now we only show the name of the goal on the budget line on the cover of the collective.
We should show the list of goals on the collective page somehow.

![](https://d.pr/free/i/j9c9Xf+)

@cuiki can you provide a mock up for this?

**Comment by cuiki** [comment]
Hi @xdamman,

While I was working on the homepage — the task to add burn-rate & gol title — I was struggling with finding a good way to show this information in a way that would be easily translated in the collective public page.

So to do that I decided to re-approach the collective page during the week in addition to the homepage, also to fix the problem we later saw about the awkward way the goals are displayed in the progress bar where they overlay on each other.

There is a bunch of comments that explain my thinking on all solutions proposed for this page. Once I'm done with the homepage I'll finish the rest of the content on the collective public page but you'll get a pretty good idea.

› https://invis.io/UQF0FK26S#/295204809_Collective_Page_-_Generic_-USER-
