### ISSUE TITLE
publishing modules to npm

### ISSUE THREAD

**Issue by boneskull** [OpenCollective/OpenCollective#106]
so I'm the type to "just do it" and beg for forgiveness later.  I went ahead and registered the user `opencollective` (*not* an org--you have to pay for those) on npmjs.com.  Basically squatting it to ensure someone else doesn't nab the name.

An issue is that you cannot exist as an "org" in npm without paying.  The purpose of paying would ostensibly be to have *private* packages on npm.  We don't need private packages, so it doesn't make much sense to pay.  On the flip side, it's lame to share a username and password amongst our members.

But, we should, at the very least, publish scoped packages when appropriate; for example, `opencollective-jobs` could be published as `@opencollective/jobs`.  Given this is a library, and has a CLI component others may find useful, it makes sense to publish this package (or a portion of it) at some point, scoped or not.  

At present time, if I want this package, I need to `npm install` via GitHub instead of the registry, because the package is not published.  I don't think this is a huge deal, but there are certainly implications if we wish to improve discoverability.

I'm not going to publish anything with this user until we've had a discussion around it, of course.

**Comment by asood123** [comment]
Thanks for registering the name. Agreed that we should register as an org for publishing scoped packages. $50/month is roughly what it would cost. Not unaffordable but not the best use of that money right now either. I'd recommend waiting till we raise some funding before registering.
