### ISSUE TITLE
Action buttons not working on individual expense page

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1060]
I can use the green buttons like "pay with paypal" and "record as paid" fine through the host dashboard, but when viewing an individual expense's page, the action buttons are greyed out (I mean for the same action for the same expense, so it's not invalid for a different reason).

**Comment by piamancini** [comment]
assuming this is not a problem anymore. @alannallama please comment for re-opening

**Comment by alannallama** [comment]
Yes this is fixed
