### ISSUE TITLE
Paypal balance broken

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1061]
In the host view on the expenses page, it says "available balance", a number, and a button under to refill the Paypal preapproval at the top right of the page. However, this number is not correct and does not update as expected.

**Comment by piamancini** [comment]
This is still an issue.

**Comment by alannallama** [comment]
@xdamman were you working on this? It's half fixed - now when you load the dashboard it shows the correct preapproval balance, it just doesn't update when you make a payment and you have to refresh to update.

**Comment by xdamman** [comment]
@Betree has been working on this

**Comment by Betree** [comment]
@alannallama Indeed I fixed the balance on the API side but we don't refresh this data on the frontend when we pay expenses. I've moved this part to a new issue: https://github.com/opencollective/opencollective/issues/1855
