### ISSUE TITLE
Expense comment is truncated

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1063]
It only shows the first few words of a comment on an expense. The whole comment should be viewable.

<img width="849" alt="screen shot 2018-05-12 at 11 14 17 am" src="https://user-images.githubusercontent.com/5498878/39950507-a5b76de8-55d5-11e8-88ae-50e33fa137e1.png">

**Comment by alannallama** [comment]
@xdamman @piamancini this is kind of urgent because I can't actually read the reply the submitter gave after I commented on their expense (see: https://opencollective.com/typeorm/expenses/1900). I did not get an email notification of their comment either.

**Comment by xdamman** [comment]
Also, you can hover the text and the full untrimmed version will show up
![](https://d.pr/free/i/CJpgOR+)

Not ideal, working on a fix, just wanted to share another workaround.
