### ISSUE TITLE
Sponsor listed but no transactions

### ISSUE THREAD

**Issue by luceos** [opencollective/opencollective#1064]
(history #981)

One of the fears I had was that both my sponsors would stop pledging. One of them actually did and hasn't renewed, which is - under circumstances - fine. The second one, according to records, is still active and pledging, but no transactions have been made so far to match those records. Even when both are still listed as sponsors.

https://opencollective.com/tenancy/members/organizations.json

*inactive sponsor*
```json
        "tier": "Silver Sponsor",
        "isActive": false,
        "totalAmountDonated": 250,
        "currency": "USD",
        "lastTransactionAt": "2018-03-20 19:35",
        "lastTransactionAmount": 250,
```
*active sponsor*
```json
        "tier": "Bronze Sponsor",
        "isActive": false,
        "totalAmountDonated": 300,
        "currency": "USD",
        "lastTransactionAt": "2018-04-03 18:58",
        "lastTransactionAmount": 100,
```

Collective page: https://opencollective.com/tenancy#contributors

![image](https://user-images.githubusercontent.com/504687/39685936-29350db0-51c6-11e8-8e05-21c759a598b5.png)

Transactions: https://opencollective.com/tenancy/transactions#

Last transaction by any org/sponsor:

![image](https://user-images.githubusercontent.com/504687/39685963-409bd538-51c6-11e8-81b6-64fab3851d63.png)

**Comment by luceos** [comment]
The `isActive` flag on Health Care Logistics (HCL) recently changed to false as well. They are/were still listed as sponsor though. They reached out to me again today and are willing to continue backing 😄 .

**Comment by piamancini** [comment]
@luceos maybe there credit card failed or needs to be updated? We try three payments before we cancel a subscription. That's probably why it the flag was isActive is TRUE while we attempted payment. The subscription needs to be re done.

**Comment by luceos** [comment]
Okay, makes sense. But still doesn't explain why these are still listed as sponsor.

**Comment by piamancini** [comment]
because they made contributions in the past, so they are your sponsors.

**Comment by luceos** [comment]
They are lifetime sponsors? Not current sponsors?

Interesting, confusing 😊 

So.. then this can be closed right?

**Comment by piamancini** [comment]
yes, once they gave you funding they continue to show up.  
We think we should always show those who have contributed to a collective, but in the future we'll have an inactive sponsors or previous sponsors category but we haven't prioritized it yet. 
closing this issue for now then!
