### ISSUE TITLE
improve admin approval flow 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1068]
Admin receives an email with a new expense and hits approve and is directed to a url (https://opencollective.com/opensource/expenses/3561/approve) that only loads a word 'done'. 

We should probably send them to their collective or their collective /expenses so they can see the expense approved or even a place to check out new collectives! to make this flow more meaningful. 

<img width="913" alt="screen shot 2018-05-08 at 1 50 10 pm" src="https://user-images.githubusercontent.com/3671070/39773846-35f13f04-52c7-11e8-85db-cd4cd01832ae.png">

**Comment by FadySamirSadek** [comment]
will grab this one up

**Comment by HipsterBrown** [comment]
@FadySamirSadek Awesome! Let us know if you need any help setting up the api and frontend.

**Comment by FadySamirSadek** [comment]
installing graphicsmagic manually using macports solved the issue
