### ISSUE TITLE
Enable host admins to reject expenses

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1069]
Sometimes a collective admin / core contributor approves an expense which isn't valid according to the host's policies, for example not including a valid invoice or receipt. However, the host admin can't reject or delete the invalid expense. 

I'm not sure what the ideal flow would be, but perhaps a reject option that kicks it back to the collective admin / core contributor to approve or reject again, with a note of explanation from the host admin?

**Comment by alannallama** [comment]
Another example where it would be good to be able to delete and expense: this person has put a note saying actually nevermind they don't want to submit [this expense](https://opencollective.com/code-settings-sync/expenses/3087).

**Comment by xdamman** [comment]
This is the current logic for rejecting an expense:

```js

    const canReject = LoggedInUser
      && LoggedInUser.canApproveExpense(expense)
      && (
        expense.status === 'PENDING'
        || (expense.status === 'APPROVED' && (Date.now() - (new Date(expense.updatedAt).getTime())) < 60 * 1000 * 15) // we can reject an expense for up to 10mn after approving it
      );
```

For some reason, we didn't want to allow people to reject an expense that has been approved unless it was a mistake (hence the 10mn window). Maybe @piamancini remembers why we decided to do that?

So you'd like to be able to reject an expense no matter its current state?
Is it enough to allow just the host to do that?

This would be the new logic:

```js
const canReject = LoggedInUser
      && LoggedInUser.canApproveExpense(expense)
      && (
        expense.status === 'PENDING'
        ||
        (
          expense.status === 'APPROVED'
          &&
          (
            ((Date.now() - (new Date(expense.updatedAt).getTime())) < 60 * 1000 * 15) // admin of collective can reject the expense for up to 10mn after approving it
            ||
            LoggedInUser.canEditCollective(collective.host)
          )
        )
      );
```

**Comment by piamancini** [comment]
I can't remember why we set that window, we should remove the bar then.

**Comment by alannallama** [comment]
I have been getting around this by editing the listing slightly, which un-approves it, and then not re-approving it. It's OK as a workaround. I think ideally, though, the host would be able to reject it and give a reason (like "no receipt") so the submitter and core contributor could be notified.
