### ISSUE TITLE
small tweak to collectives list on host dashboard

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1070]
This is a tiny tweak that would make admin for large hosts with lots of collectives less frustrating.

On the host dashboard there's a dropdown list with all the host's collectives. If you select one halfway down the list and load that page, then click the list again, it jumps back up to the top instead of staying at the point you've selected.

In the below example, the desired behavior would be for the list to start at "phalcon" (the last one selected), but instead it's jumping all the way to the top of the alphabet again. This makes going through the list a chore because you have to keep scrolling to find your place again.

<img width="476" alt="screen shot 2018-05-09 at 2 28 53 pm" src="https://user-images.githubusercontent.com/5498878/39792608-8d0dea16-5395-11e8-9c25-98a964da557c.png">

**Comment by piamancini** [comment]
this dashboard has a lot of room for improvement.
Also. we are the only ones with so many collectives.

**Comment by clarete** [comment]
I think my changes to the host expenses page may have addressed this issue. Let me know what can be better there.

**Comment by clarete** [comment]
Reopening it since the changes to the dashboard were reverted.
