### ISSUE TITLE
activity updates in expense comments

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1071]
Now that we have comments on expenses, it would be great if activity status updates appeared there as well. For example: "expense submitted by [name]", "expense approved by [core contributor name]", "file xyz uploaded", "expense edited by [name]", "expense paid". Having these notes with the dates on them would be very useful for record keeping and figuring out any confusion or mistakes.

**Comment by xdamman** [comment]
I like that.

I wonder what would be the best way to implement that and also implement "reactions" (👍 🎉❤️...) and multiple levels of approval (e.g. approved by Xavier and Alanna).

One way I can think about it is to have a special type of comment "activity" or "reaction".
The flip side of it would be to abstract everything as an "activity" of type "comment", "approval", "reaction".

I probably like the latter better but it conflicts with our current `Activity` table. That said, this really needs to be updated.

Other things to consider: entities. We should be able to mention someone in a comment.

I'd be curious to know how is Github handling this behind the scene.

**Comment by alannallama** [comment]
We still need this

**Comment by mixmix** [comment]
Alanna re-opened this because I was asking her how I figure out who approved an expense for someone to go to a conference on my OC group. 

e.g. I'm looking at this expense : https://opencollective.com/secure-scuttlebutt-consortium/expenses/6503 and can't see very much info at all

![image](https://user-images.githubusercontent.com/2665886/52251066-d6917680-295f-11e9-9f4a-994172074086.png)
[ DOM edited to hide user name + email ]

**Comment by alannallama** [comment]
Bumping this, because it keeps coming up....

**Comment by alanna** [comment]
This should be included in the new expense flow design @raulgrafico

**Comment by Betree** [comment]
Implemented in https://github.com/opencollective/opencollective-frontend/pull/3893, will be resolved with the new expense flow release

**Comment by Betree** [comment]
Implemented in the new expense flow

**Comment by mixmix** [comment]
Hooray! <3
