### ISSUE TITLE
Unable to pay 100% of collective balance due to fees

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1073]
Maintainers sometimes invoice for 100% of the funds in a collective (especially for small ones), but that doesn't leave enough funds to cover the host fee. Currently we have to manually request the submitter revise their expense down. It's a messy and error prone process.

For example: a collective has $240 in its balance and the maintainer invoices for $240. If the admin clicks pay, the system will error saying there's not enough to also cover $12 in fees. So we contact the submitter and say please change the amount you're invoicing to $228 instead. 

The system obviously knows the fees because it throws an error when you try to process the payment - can it give the error to the submitter in the first place?

**Comment by piamancini** [comment]
the system has no way of knowing if they'll receive another donation next month or the next day.

**Comment by alannallama** [comment]
Can the system just pay the amount minus the fees? So if someone invoices for $240 they get $228 and the collective is debited $240? Instead of debiting $252 (amount including fees). I think people are used to this model, for example if their AirBnB is rented for $100 they know they aren't going to get that amount, but instead will get that minus the fees. Will it mess up all the accounting if the invoiced amount doesn't equal the debited amount, or can the fees be accounted for?

**Comment by piamancini** [comment]
Not really, because the fees amount that the system gives is an estimate we make based on previous fees, we don't know exactly how much the fees will be before the payment goes through. We could deduct the estimated fees but then the actual fees would be different so that needs to be managed. Not sure it's worth the trouble now. 

Maybe it's just a matter of letting them know the amount needs to be adjusted but we can still use the existing expense. As long as expense amount = or > than amount  paid should be ok.

**Comment by alannallama** [comment]
This problem keeps coming up. It's frustrating and slows payments down as users have to re-do them after the whole issue is explained.

What about a warning message if a user is trying to submit an expense for the entire current balance? 

_This Collective's current balance is not enough to pay this expense plus the required fees. If you would like to withdraw the full balance, please revise your expense amount to $[balance minus estimated fees]. You may submit this expense as it is, but it will not be paid until your Collective balance goes up by $x in that case._

This feels like a hacky solution though, requiring that users actually read error messages and think about math.

I still don't understand why the system can't deal with this at the time of the transaction being approved for payment. When I hit "pay with paypal", can't the system subtract the actual fees charged from the total amount of the expense, and pay that to the user, so the correct amount debited to the Collective balance (what user gets + fees) is the amount of the expense exactly?

@piamancini I probably haven't fully understood what you said above about this.

**Comment by alannallama** [comment]
I am re-opening this because it keeps coming up. Collectives need to zero their balance in order to deactivate or switch hosts, and between the rounding the system does and no way to accurately tell exact fees the API will charge, we keep running into a situation where a Collective will try to invoice out their whole balance but be left with a few cents in the Collective that prevents them from moving forward.

**Comment by znarf** [comment]
What is the action plan?

**Comment by alannallama** [comment]
@znarf

It's tricky because we can't disallow Collectives from expensing more that is payable with their balance, because we encourage Collectives to submit expenses before they have income.

Right now I just edit expense totals down to allow for fees, but I think this might cause future problems with accounting because then the invoice amount doesn't match the paid amount. Also, because the system does rounding I often end up leaving some cents in the account, which doesn't help the Collective that wants to move hosts or shut down and causes a big headache. When the system estimates expenses for the host admin trying to pay it, it also rounds.

Maybe the system could pop up with a message if [expense total] = [Collective balance], saying "Warning: if you are trying to submit an expense for 100% of the Collective balance, make the amount $xx.xx to allow for $xx.xx in fees". But this assumes the system can accurately guess the actual fees... are they knowable exactly in advance?

In terms of a workaround, I can live with editing the expense amounts myself to cover fees if I have some way to zero out the leftover cents. Or, if we could remove rounding so I can calculate it exactly when changing the amount.

**Comment by alannallama** [comment]
This is somewhat ameliorated by the 'zero balance' feature, but I think we should keep it open until we confirm that it will be resolved by the new expenses flow.

**Comment by alanna** [comment]
This will be fixed in the new expense flow

**Comment by Betree** [comment]
Just a quick note to mention that this hasn't been addressed in the new expense flow. If I remember correctly, the feedback was that the checkbox introduced too much complexity in the form.

Let's keep this issue open until we find a proper way to address it.

**Comment by alanna** [comment]
@Betree that was not my understanding. The checkbox was in the final designs I approved. Can we please bring it back? It's a really important feature in terms of support volume and user satisfaction, because it's super frustrating not to have it.

**Comment by Betree** [comment]
@alanna ping @piamancini @opencollective/design - I'm not the decision owner on this

**Comment by piamancini** [comment]
@alanna we decided to take it out in the process because it was confusing and complex to implement. We know it's a request and we can build it for future iterations if it is still a problem.

**Comment by alanna** [comment]
We really need this! Not being able to expense for 100% of the balance is still causing so many problems. Can we please build this feature? It was originally in the new expense flow project but was removed. I don't agree with that decision.

**Comment by alanna** [comment]
I still think we should find a way to do this if possible.

**Comment by alanna** [comment]
Two and a half years later and I still think we need this

**Comment by alanna** [comment]
This issue is still regularly raised by users ([example](https://opencollective.freshdesk.com/a/tickets/25024)) and causes pain and frustration. I've been advocating it for 3 years now... can we possibly prioritise it as a long-standing papercut? We need a "pay 100% of balance" option on expenses.

**Comment by Betree** [comment]
I agree that this would help in many situations. It's might not be trivial though.

A possible solution on the engineering side is to store a flag in the expense to record who will pay the fee (`feePayer`=`COLLECTIVE`|`PAYEE`). Then, when paying the expense, we would ideally pass a parameter to payment providers to tell them where the fee should be deducted.
- For PayPal payouts, it seems that there is [no solution](https://www.paypal-community.com/t5/REST-APIs/PayPal-payout-fee/td-p/1722298) for this yet
- For Transferwise, it seems [quite easy](https://api-docs.transferwise.com/#quotes-create) as you can either specify the source amount or the target amount 

(ping @kewitz in case you're aware of other possibilities or limitations)

So, as an MVP, we can limit the "pay 100% balance" feature to Transferwise. That's not perfect, but at least we would have something to offer on the support side. If that works for the team, we still need a quick design to decide where/how we're going to display that in the interface.

**Comment by alanna** [comment]
This is so incredibly annoying. Is there any way to make Wise calculate a fees-inclusive amount based on the total to pay?

<img width="321" alt="Screen Shot 2021-10-05 at 12 12 45 PM" src="https://user-images.githubusercontent.com/5498878/135936735-1a36c766-253f-4ada-a128-881b8135949c.png">

**Comment by alanna** [comment]
This is such a waste of time every time it happens
![Screen Shot 2021-10-15 at 10 46 52 AM](https://user-images.githubusercontent.com/5498878/137400180-17c84db9-3ef6-4fd9-aec8-71181eb74fbf.png)

**Comment by abitrolly** [comment]
@Betree can it be reticketed into a separate `Payment Processor Fee Tracker? I haven't found any database diagram in documentation, and also I am not a JS developer, so getting to the first PR will take a long route, and this issue doesn't looks like a place to add too much internal code details.

**Comment by BenJam** [comment]
plan

- [ ] build an MVP (even if it's just in the database) as a starter for UX development etc.

**Comment by Betree** [comment]
Update on the project: testing was difficult, but I ended up with a functioning MVP in https://github.com/opencollective/opencollective-api/pull/6898. I still need to push my latest changes, clean up the code then start thinking about a simple MVP UI to expose the feature in the frontend.

**Comment by znarf** [comment]
After completing Transferwise, would be great to look into having the same behavior for PayPal. Related: https://github.com/opencollective/opencollective/issues/4953

**Comment by piamancini** [comment]
- [ ] Week 2 goal: Have MVP on Prod

**Comment by BenJam** [comment]
update: found we need to reflect payment processor fees

- [ ] new MVP that incorporates payment processor fees recorded in the ledger

**Comment by Claudio060320** [comment]
> This is so incredibly annoying. Is there any way to make Wise calculate a fees-inclusive amount based on the total to pay?
> 
> <img alt="Screen Shot 2021-10-05 at 12 12 45 PM" width="321" src="https://user-images.githubusercontent.com/5498878/135936735-1a36c766-253f-4ada-a128-881b8135949c.png">

**Comment by abitrolly** [comment]
@Claudio060320 as far as I can see resolving this is a current focus https://github.com/opencollective/opencollective-api/pull/6932

**Comment by piamancini** [comment]
Status: deployed. Live for Wise

**Comment by Memo-Es** [comment]
@alanna Some comments and questions about the current state of the project:

* @Betree is implementing a solution to charge the fees to the payee when paying an expense of 100% of the Collective's budget. We think this covers the main problem presented on this issue.
* On the user interface side, I was exploring to include the original idea as an option inside the expense submission process. But after going through the design process and some discussion with the team, we realize that perhaps it makes more sense to have this feature under the Collective's settings, embedded in the options to close the collective and change host.

**Question:** Are there other cases apart from closing a collective or changing hosts that we should be aware of?

**Comment by alanna** [comment]
After seeing how it's been implemented, I think it's actually OK to only show this option to host admins, because it's really a payment processing problem. 

If the user has submitted an expense for 100% of the balance, and the Collective admin has approved it, then it's obvious that both of them want the expense paid and the balance zeroed - we already inform them that payment processor fees may apply. So I actually don't think any action is needed from either of those roles.

> have this feature under the Collective's settings, embedded in the options to close the collective and change host

There are commonly a lot more situations for zeroing balance than only closing or changing hosts. People often want to pay out the max possible, even if they wish to keep their Collective as it is. So I don't think we should put this option in the zero balance or host settings areas. I think that will make it way too complex and bring up all kinds of issues about how to connect the expense approval and payment process to that action.

That said, in the future we should separately take on reviewing the UX flows for changing hosts and closing a Collective, as right now it's pretty disjointed and not intuitive for those who don't understand all the steps. But that's out of scope here.

So, for now, for this iteration, here are the options I could see...

1. Leave it as is, where it's a checkbox in the expense payment modal only seen by host admins (and just focus on implementing that for all payment methods).
2. Change from a checkbox to more like a function of how the payment process itself works: when expense amount = balance always have payee cover the fees automatically; OR when a payment fails because of fees pop up an option to the host admin saying 'This transaction failed because of insufficient balance to cover fees. Have payee cover the fees and continue?' and the host admin can click ok or cancel.

Personally I think we should go with option 1 for MVP, use it for a month or two, get feedback from host admins, and then decide if we want to iterate it or leave it.

**Comment by Claudio060320** [comment]
https://github.com/opencollective/opencollective/issues/5040

**Comment by Betree** [comment]
Demo of the latest progress: https://www.loom.com/share/f5f3e55bbbd44adaab086c63afeaa11d

**Comment by piamancini** [comment]
- [ ] merge refund fix
- [ ] close issue and open a review / improvements issue

**Comment by alanna** [comment]
@Betree this feature doesn't appear to be on for OCNZ host. Can it be activated?

**Comment by Betree** [comment]
@alanna There's no host-specific feature flag. The two conditions for the checkbox to appear are:
- The balance must match exactly the expense amount
- The payout method must be a `BANK_ACCOUNT`

If you think these conditions are respected, could you share the expense URL to investigate?

**Comment by alanna** [comment]
Turns out the expense was for $1,910.74 and the balance was $1,910.76 so it failed due to fees despite not being 100% of the balance. I paid it manually because it couldn't wait.

**Comment by Betree** [comment]
MVP's ready, feel free to open followup / feedback issues for the next steps!
