### ISSUE TITLE
add a link to /subscriptions on the menu bar of profiles

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1074]
There is no obvious path to /subscriptions from a user's profile
<img width="1266" alt="screen shot 2018-05-09 at 12 30 54 pm" src="https://user-images.githubusercontent.com/3671070/39827100-e1979462-5384-11e8-849c-21651f5799e2.png">

**Comment by FadySamirSadek** [comment]
@piamancini  This should be closed as the design in the screenshot has been changed and the subscriptions page can be accessed from the drop-down menu beside the user avatar

**Comment by piamancini** [comment]
thanks @FadySamirSadek
