### ISSUE TITLE
Payment Method for orders from one Collective to another

### ISSUE THREAD

**Issue by clarete** [opencollective/opencollective#1079]
Collectives that have positive balance should be able to contribute to other collectives.

* This payment method is only available for collective admins
* The collective has to be under the same host (Will support transactions between collectives between multiple hosts as soon as the [PR for new multi-currency fields](https://github.com/opencollective/opencollective-api/pull/1228) lands)

/cc  @piamancini @xdamman

**Comment by piamancini** [comment]
closing this it's being done my @marcogbarcellos in collective to collective contributions
