### ISSUE TITLE
Remove old donations/expenses code

### ISSUE THREAD

**Issue by sedubois** [OpenCollective/OpenCollective#108]
- [ ] remove old subscription-related code e.g `Transaction`/`transactions.js` columns `interval`, `stripeSubscriptionId`
- [ ] remove old expense-related code e.g `Transaction`/`transactions.js` columns `payoutMethod`, `paidby`, `reimbursedAt`
- [ ] remove old donation-related code
- [ ] remove properties from before fees migration
- [ ] remove `#postmigration` code

**Comment by asood123** [comment]
Here is a partial list of changes for cleanup.
