### ISSUE TITLE
Allow site admins to add funds to organizations

### ISSUE THREAD

**Issue by clarete** [opencollective/opencollective#1080]
There are some organizations that have a budget and want to spend it monthly in different projects. We currently create the transactions for their (also manually created) subscriptions. To automate this process we're thinking about implementing the following features:

 * The site admins should be able to add funds to an organization.
 * The organization should be able to see their balance
 * The organization should be able to manage subscriptions via their `/${organization}/subscriptions` page.

Changes:
 API: https://github.com/opencollective/opencollective-api/pull/1303
 Frontend: https://github.com/opencollective/frontend/pull/454

**Comment by clarete** [comment]
### How to use it:

1. Add funds to org (only site admins can do this)
    * go to the host expenses page of the host that received the funds in their bank account
    * select the organization and use the add funds form to select the amount and add the funds.

2. Place order with new payment method (Only organization admins can do this)
   * Go to any collective's donate page
   * Select the organization in the "Contribute as" field
   * The first credit card available should be something like "Organization - prepaid balance exp ..."

### The implementation that is coming looks like:

  * [X] during step 1, on the backend side adding funds to orgs doesn't create any transactions. Instead, it creates a new payment method for that host. And the `customerId`  of the newly created payment method contains the `slug` of the organization.

 * [X] during step 2, the GraphQL query for `Collective.paymentMethods` was changed. When the `collective.type` is `ORGANIZATION`, it returns all the payment methods with `pm.CollectiveId === org.id` plus the ones that have their `customerId` equal their slug (`pm.customerId ===  org.slug`).

 * [X] The `OrderForm` component needs to allow the credit card combo to list other types of payment methods.

  * [ ] The `OrderForm` component needs to query the balance of the org payment method and setup the order in a way that the machinery for gift cards (opencollective.prepaid) can create the transactions.

/cc @xdamman

**Comment by clarete** [comment]
I changed the implementation strategy a little bit and updated the previous comment accordingly.

**Comment by clarete** [comment]
## What didn't work

The host expenses page header looks like this with the above changes:

![10801](https://user-images.githubusercontent.com/1459190/40729602-baa22170-63fa-11e8-98e9-c70582ec6db2.jpg)

The problem with that is that we end up loading all the collectives & all the organizations when we load that page. We can select which query to be executed if we change how the components are arranged but that'd take some refactoring.

## New suggestions

@xdamman  suggested to get rid of the above option and add a button to the organization page. The question I have about that is: how do we pick the host that should be registered for that operation? Should I list all the collectives that the logged in user is an admin of and check if they're hosting a collective? I didn't find a way of doing that in a simple graphql query.

What do you think about adding the button to add funds to orgs in the Hosts profile page? That way the host will already be selected and I can just paginate the results of the list of organizations in a lil modal that appears after clicking the button to add funds. It'd look like this:

![1080 suggestion](https://user-images.githubusercontent.com/1459190/40730298-524f47ea-63fc-11e8-9c15-4e4c5866ecd4.jpg)

And the modal with the add funds form would look like this:

![1080 suggestion 1](https://user-images.githubusercontent.com/1459190/40730621-17ec7e6e-63fd-11e8-9f2e-e161ab667e40.jpg)

Let me know what you think @xdamman.

**Comment by piamancini** [comment]
This feature should only be visible to hosts admins and only for organizations that are hosts, since it's the host that needs to validate it actually has the funds form that organization.  That was the logic of it being in the host dashboard. 

With the option above, we'll have host functionalities in two different places, the dashboard and the organization itself + we need to hide it for organizations that are not hosts. 

Ideally you want to have one place where hosts admins have to go to, to manage everything related to administering the host.  And that's the only place the system validates the user has host management credentials.

**Comment by xdamman** [comment]
Thanks for writing this up. That’s very useful to provide feedback before you get into implementing. 

The problem with adding that option on the host page is that you will have again to populate the entire list of all organizations (500+). That’s very painful to go through.

Whereas a user is only an admin of 1-5 max hosts.

The way you can select all hosts is by selecting all stripe accounts linked to the user collective or to one of the organization collectives that the user is an admin of.

That’s why I think that in the short term, it’s better to implement it this way.
If you have more time, the real proper way to do it would be to have a backer management interface for the host (in the same way that we have /host/collectives/expenses, we should have /host/backers). There we should be able to export the list in csv, filter them by name and add funds to any of them or create a new backer.
But that’s a lot more work.

**Comment by xdamman** [comment]
@Pia yes it will only be visible to host admins. But that doesn’t mean that it has to be in the host dashboard (which doesn’t really exist today, we only have an expense management view).
See my comment above, I agree that ideally we should consolidate all that within one dashboard but that’s why beyond the scope of this. And given that it’s a feature that is not used much (and mainly by our own host), it’s fine to use a shortcut here.

**Comment by piamancini** [comment]
What happens if we need to add funds to an organization for say the 501c6 and open collective host? This might happen if an organization wants to back both open source projects and tech meetups?

**Comment by xdamman** [comment]
Per my comment above, we will have to select all the hosts the user is an admin of (and show a drop down to select the host to use).

**Comment by clarete** [comment]
### The above feature is implemented in the frontend, here's what it looks like:

1. If you're a host admin. When you navigate to an organization page, you'll see the following new button on the menu bar:

![addfbt](https://user-images.githubusercontent.com/1459190/40995593-6fcb32fe-68cd-11e8-956f-ffcc0f6944d7.jpg)

2. And clicking that button opens the following form:

![addfundsform](https://user-images.githubusercontent.com/1459190/40996178-30b2deda-68cf-11e8-99ba-a6bb0ac92896.jpg)

The *SOURCE* combo is filled in with the hosts that the logged in user is admin of.

### What's missing on the backend

I modeled this feature on top of the Gift Card. Everything from creating the payment method with the balance all the way to placing the order is pretty similar between the gift card and the add fund to orgs feature. However, the execution of the order might be a little different for those two payment methods.

#### How placing an order with a Gift Card currently works
Upon receiving the order from the order form, the gift card flow goes like:
  0. Create a new payment method of type "collective"
  1. Create transaction with the total amount of the gift card from the host to the user, so the user can pay the collective
  3. Archive the payment method so nobody can claim that same gift card
  4. Create the transaction between user and collective receiving the donation.

#### How placing an order with a pre-paid card from an organization should work

  0. Create transaction between the host & the organization documenting moving the money from the host to the organization (maybe this could be done during the `add funds` operation instead of in the process of placing an order)
  1. Create transaction between organization and collective receiving the donation
  2. The balance of the payment method would be `PM.initialBalance` - `sum(transactions.amount) where PM.id = <PMID>`

**Comment by clarete** [comment]
I got some PRs for implementing the above feature:

 * https://github.com/opencollective/opencollective-api/pull/1303
 * https://github.com/opencollective/frontend/pull/454

I just pushed them to staging.

@piamancini here's how I've been testing this feature:

 1. Log in as a site admin
 2. Go to an organization page (I've been using algolia's)
 3. Click the "Add funds" button and fill in the form***
 4. Log in with a core contributor from the organization you added the funds to
 5. Go to another collective's donate page
 6. Choose your organization in the combo "Contribute as"
 7. Choose the algolia card in the credit card combo & finish the order

Other things that I tested:
 1. Monthly subscription (after following the above steps marking the order as monthly) I tweaked the charge dates in the subscriptions table and charged the prepaid card successfully with our cronjob script.
 2. Tried to place an order after using all the balance available in the card. It didn't go through with the right error message.

***There's currently no confirmation message after successfully adding funds to an organization.

Please ping me if you need any help testing this.

**Comment by piamancini** [comment]
- change source for host (it's confusing since the source is actually airbnb, the organization that provided de funds)

- remove host/platform fee since we are taking them at the moment of the transaction. 

cc/ @xdamman

**Comment by piamancini** [comment]
I'm seeing two credit cards <img width="719" alt="screen shot 2018-06-14 at 10 47 27 am" src="https://user-images.githubusercontent.com/3671070/41419586-64d6fc80-6fc0-11e8-97fb-8e236090c341.png">

**Comment by clarete** [comment]
One thing that's missing is where to show the organization balance. Would it fit in the organization page?  I can add it close to the `add funds` button (but keep the balance public?). @xdamman do you have any suggestions?

**Comment by clarete** [comment]
> I'm seeing two credit cards 

Just for the sake of documenting. I added some credit to airbnb on staging as well. Every time funds are added, a new credit card will appear in the combo. I can just edit the existing one if you prefer but I think we get to save the dates if we keep it like that.

**Comment by xdamman** [comment]
"remove host/platform fee since we are taking them at the moment of the transaction."

I would keep them and prepopulate with the default host fees.
It's important to record the total amount added and total amount available after fees.

For showing the balance, it should be like the Open Collective Card for a collective. We should show it in the dropdown menu where you select the card (e.g. $4,400 left). The balance is not at the organization level but at the prepaid card level. Because a prepaid card is restricted to a host.

**Comment by xdamman** [comment]
The problem with creating a new card every time is that the card will run out at some point and subscriptions will fail. So I'd only keep one prepaid card per organization per host.

**Comment by clarete** [comment]
> The problem with creating a new card every time is that the card will run out at some point and subscriptions will fail. So I'd only keep one prepaid card per organization per host.

Isn't it a feature to be notified that the card is empty so there can be another deal between the organization and the host?

**Comment by clarete** [comment]
> I would keep them and prepopulate with the default host fees.
It's important to record the total amount added and total amount available after fees.

Sounds good! I'll keep them and make sure that the host fee that appears by default is read from the host selected in the combo.

> For showing the balance, it should be like the Open Collective Card for a collective. We should show it in the dropdown menu where you select the card (e.g. $4,400 left). The balance is not at the organization level but at the prepaid card level. Because a prepaid card is restricted to a host.

Alright! <o/ Thanks for the instructions!

**Comment by xdamman** [comment]
Interesting thought. It could indeed be seen as a feature or as a bug for the same price. I guess ideally we could top up an existing card or create a new one.

But if we had to pick one, I'd be on the side of having only one card to avoid confusion. Also you don't want to end up with a bunch of cards with a few dollars on each.

In all cases, they will be notified that the card is getting empty and can choose to top it up or not and to unsubscribe from existing subscriptions.

**Comment by clarete** [comment]
> (...)
> In all cases, they will be notified that the card is getting empty and can choose to top it up or not and to unsubscribe from existing subscriptions.

That makes sense! I'll keep just one card per organization/host then and make sure the subscription script can handle that case.

**Comment by clarete** [comment]
>> I would keep them and prepopulate with the default host fees.
It's important to record the total amount added and total amount available after fees.
> Sounds good! I'll keep them and make sure that the host fee that appears by default is read from the host selected in the combo.

Sorry to come back to this, but I think there's another detail here. The host fee is stored in two places as far so far:
 1. Collectives table
    1.1 Host row (Default host fee)
    1.2 Collective row (Overrides host fee from the Host row)
 2. Transactions table
    2.1 Transaction row (uses either the fee in the collective row or in the host row)

If the `add funds to org` form allow to change the host fee (or the platform fee) we'll have to store that information in the payment method. I just want to confirm if that's the wanted feature.

### Alternative

If you just want to display the fees, I suggest not showing the fields but keeping the fees in the lil `detail` section as well as in the balance displayed in the credit card combo box.

**Comment by xdamman** [comment]
Oh. Now I get it. And I get what Pia was trying to say above. She's right. We don't care about host fees at all. This is acting as a credit card so the host fees are already being taken care of at the time of the transaction when using that prepaid card.

**Comment by clarete** [comment]
Alright! I'll keep the fees in the details section but won't show them as form fields! Thanks for the response!

**Comment by xdamman** [comment]
No you can remove both host fees and platform fees. They are irrelevant here.
We are just creating a prepaid card for the full amount received. When they will use it to make a payment, it's at that time that the host and platform fees will apply.

**Comment by clarete** [comment]
Alright!

**Comment by clarete** [comment]
What's on the list:

 * [ ] hiding all the fees on the add funds form
 * [ ] avoid creating duplicated cards from the same host to the same organization. Instead, just add to the `initialBalance` field of the existing payment method.
 * [ ] Add a confirmation after the funds were added to an organization

**Comment by clarete** [comment]
Here's what I did to address the last point in the above comment (show confirmation after adding funds)

![fundsaddedalert](https://user-images.githubusercontent.com/1459190/41430806-0ff38c6e-6fdf-11e8-97aa-a1d52a38db5e.jpg)

**Comment by clarete** [comment]
Alright. I addressed all the points raised above. I'll proceed pushing this to prod. Things that might be worth noting:

 1. Only site admins will see the `add funds` button in the organization profiles for now.

 2. There's currently no place for the host admin to visualize the balance of a prepaid card of an organization.

 3. There's no specific way to know how much in platform fees the host owes Open Collective for a given period time. The paypal payment method has the same issue. Maybe it's worth working on a report that unify this information.

I can create separate tickets for the above points if you guys think they make sense.

/cc @xdamman @piamancini

**Comment by xdamman** [comment]
Awesome!

1. You mean host admins?
2. That's correct but that's ok for now
3. In theory, the host shouldn't have to pay any platform fees when using "Add Funds". It's only different for the Open Source Collective because we are doing all the work ourselves. So we will know how much we should charge the host in this case.

**Comment by clarete** [comment]
1. Right now it's only available for site admins. As soon as you guys say the word, I can change that!

2. Thanks for the confirmation!

3. Thanks for the explanation, that's something I didn't understand before. I thought platform fees would be added to each transaction made with the prepaid card. If that's not the case I'll need to remove one small line of code that adds our 5% there.

**Comment by xdamman** [comment]
1. What do you mean by "site admins", never heard that before.
There are host admins and collective admins and organization admins.
2.
3. Mmmm... I see. We are discovering more complexity as we go. Because if we add our platform fees as usual to transactions, since the money is already on the host, we actually didn't receive the money and therefore we would have to record that somewhere and process it at some point. Thanks for uncovering this problem!

I see two ways to solve this:
- We remove our platform fees and we manually charge the host for those fees and record them as any other one time invoice (which means that the actual transactions won't have any platform fees attached to them -- I'm ok with that)
- We need to find a way to actually move the platform fee from the bank account of the host to our bank account. But since platform fees are so small per transaction, it's not worth it to pay $0.30 + 2.9% for those transactions. So we should bundle them. That looks complicated to do at this stage. Don't you think?

**Comment by clarete** [comment]
1. I've been calling open collective staff the site admins.  So the feature is pushed to prod but nobody else can see/use it. Not sure if that's the best name for that role. Please let me know if there's a better name!

3. I kinda like the second idea because it could be useful for paypal as well. To simplify things, we can create a monthly report that filters out all the transactions of a given payment method of each collective hosted by a host and send them an invoice with a consolidated bill. And after battle testing that script a little bit we could even automate the charging. If that's too  complex for now, removing the 5% on the transactions of the `prepaid` credit card is pretty trivial. Just have to replace a lil calculation with `0`.

**Comment by xdamman** [comment]
Let’s call them “platform admins” to be consistent with platform fees for example. 

The problem with 2 is that the ledger should always reflect where the money is physically. In the future double ledger, we shouldn’t record the entry for those platform fees before we actually process them (or we could record them as pending). But since right now those fees are on the same row, we can’t really say that just the platform fee is pending. That’s why we are a bit stuck.

Now if we ignore those platform fees, we have another issue which is that the collective will receive more money than they should. And they may have spent it before we get to invoice for those fees. Aaaaaah! Those things are complicated!

**Comment by clarete** [comment]
Alright! Platform admins from now one!

Yeah, this is definitely tricky. And having the double entry ledger extended to encompass payment methods would indeed be useful right now. But your reasoning certainly made me understand the problem a little better and come up with the following questions/scenarios:

How does it work for current users like Airbnb, Trivago, etc? Do we charge the fees upfront? If that's the case, how would we represent it in our current system?

  a) Would it be OK to keep charging per transaction since the money would already be in our account?

  b) Should the operation "Add funds to organization" be changed to create a transaction from the host to opencollective-company with the fee and then discount the fee from the balance in the card? In that case, the payment method wouldn't charge the fee per transaction.

If we don't charge them upfront, do you think we can maybe not charge the fee per transaction and create one transaction from the host to opencollective-company every month with the sum of all the fees of all the transactions of that payment method for that host?

**Comment by xdamman** [comment]
We just chatted on the phone about this.
This is the conclusion we reached:

- When a host adds fund to an organization, the interface should show a message saying: "Please put aside `${hostFeesPercent}`% (`${hostFeesPercent} * totalAmount}`) for your host fees and 5% (`${totalAmount * 0.05}`) for platform fees."
- The prepaid card should be of the full amount before fees. At every transaction, we apply the classic host and platform fees (so there is no difference between using a credit card or a prepaid card). That way the organization sees that they have a $10k prepaid card, and when they give $100 to a collective they see in the transaction the host fee and platform fee.

**Comment by clarete** [comment]
OK, here's how the form will look like with the above changes.

![add-funds-to-org-notice](https://user-images.githubusercontent.com/1459190/41483276-7eb08bc6-70a6-11e8-8de3-32168c344cb8.jpg)

**Comment by clarete** [comment]
It's all on prod now. Only for site admins though. I'd suggest opening a new ticket to open it to all the hosts whenever we're comfortable with it. <o/
