### ISSUE TITLE
show sponsors as 'Inactive' on the front end when they stop contributing

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1082]
Inactive sponsors have the same status as active sponsors on the collective's front end. 

This is confusing and we are giving sponsors who haven't contributed for years, same real state and same category as active ones. 

This could be done by: 
- marking the card as Inactive
- moving them to an 'Previous Sponsors' area below current ones. 

Issues to be discussed: 
How long do we show a one time sponsor as active? 
If a sponsor makes a long one time donation, are they active for that month? For a year?
If they make a 12000 contribution is that a 1000 per month tier so they show active for the year?

cc / @cuiki @xdamman

**Comment by yyx990803** [comment]
With the current behavior, if a company was platinum sponsor for even just one month, they will be taking the top spot forever... I think that's particularly problematic when we are using logo placement on our website as an incentive for people to sponsor. Would love to see this rectified. Personally, I prefer moving inactive sponsors to a separate "Previous Sponsors" section.

Regarding active time for one-time sponsors - I think it makes sense to match that to the closest per month tier. e.g. if a company donates $12,000 and there is a 1000$/month tier they'd be matched for 12 months in that tier.

**Comment by xdamman** [comment]
There was a bug, found a fix. We will only return active members of the given tier moving forward.

For one time donations, the better way to handle them is to give them a prepaid card for the amount of the donation and they can use that card to join the tier they want and pay monthly off that card. Something that @clarete is working on.
