### ISSUE TITLE
"Pay with Donation" wording and behavior

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1083]
<img width="602" alt="screen shot 2018-05-11 at 3 03 36 pm" src="https://user-images.githubusercontent.com/3671070/39942197-c1b8feca-552c-11e8-947c-7fe90d60ea23.png">
Maybe we cab change it to 
'In kind contribution' 
or
'Contribute'

also the in kind donation is seen as an expense (the email sent is the expense email and reads 'expense paid') this is confusing

**Comment by piamancini** [comment]
another issue is that when trying to make a donation through the expense flow, the system checks available balance and prevents the execution. see:
<img width="954" alt="screen shot 2018-05-11 at 3 08 39 pm" src="https://user-images.githubusercontent.com/3671070/39942387-561b1bfc-552d-11e8-866f-f53a8c268e75.png">
We should remove the check for available balance when selecting 'donation' from the drop down menu

**Comment by clarete** [comment]
Thanks a lot for the screenshot. I thought I got this on the API side when you mentioned it. I'll take a look at this soon! <o/

**Comment by alannallama** [comment]
Another example of the system not allowing the donation due to insufficient balance, which doesn't make sense:

<img width="599" alt="screen shot 2018-05-26 at 10 08 16 am" src="https://user-images.githubusercontent.com/5498878/40568145-fab6f794-60cc-11e8-8219-ccebb9462e6a.png">

**Comment by alannallama** [comment]
I suggest the button should say "donate"

**Comment by alannallama** [comment]
@clarete - I have come across several of these where the balance being low keeps the host from processing the donation. Is there any update on this issue? Thanks!
