### ISSUE TITLE
Unable to save expense policy

### ISSUE THREAD

**Issue by jhoguet** [opencollective/opencollective#1089]
URL: https://opencollective.com/burlington-code/edit#expenses
Logged in as: jon-hoguet
Error message if any: `Uncaught (in promise) TypeError: t.tags.split is not a function`
Expected result: saved
Browser: Chrome 66.0.3359.139

When trying to save, we get the following error. 

![image](https://user-images.githubusercontent.com/1234146/40139492-03fd08e0-591e-11e8-9384-3babaaae3850.png)

**Comment by piamancini** [comment]
this is fixed. thanks!
