### ISSUE TITLE
Switch WWCode's stripe account

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#109]
- [x] 1. cancel existing subscriptions on Stripe [@asood123]
- [x] 2. mark those subscriptions in our database as 'inactive' [@asood123]
- [x] 3. disconnect stripe account for WWCode host in the database [@asood123]

Between step 3 and 4: no WWCode collective will be able to receive donations. So, they should happen together.

- [x] 4. Reconnect with new account [@piamancini]

**Comment by piamancini** [comment]
I'll coordinate with WWCode

**Comment by piamancini** [comment]
done.
