### ISSUE TITLE
Move GraphQL queries in the frontend to .graphql files

### ISSUE THREAD

**Issue by clarete** [opencollective/opencollective#1091]
Hi all,

I was just wondering if it's worth thinking about moving our GraphQL queries to separate files and import them using a *webpack plugin. This would probably help unclutter the component files. As a side effect, I think it'd also get rid of some repeated queries.

Definitely super low priority and actually more of a question to see what you guys think.

[*] https://www.apollographql.com/docs/react/recipes/webpack.html

Cheers

**Comment by znarf** [comment]
Also doable through Babel:
https://github.com/detrohutt/babel-plugin-inline-import-graphql-ast

**Comment by znarf** [comment]
@clarete Sounds like a great idea and straightforward to implement.

**Comment by clarete** [comment]
Nice! I wonder if that would increase the modularity and reuse of the queries. Not sure if we'd need fragments working properly in our setup for that too. I have a lot to learn about these things!
