### ISSUE TITLE
order search results

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1094]
order results by either total amount contributed or number of collectives backed when searching for organizations.

E.g. https://opencollective.com/search?q=facebook
![](https://d.pr/free/i/3QRgf2+)

I understand that we don't have that data for collectives, so the best might be to generate a rank / score based on (total amount raised, total amount donated, total number of backers, total numbers of collectives backed).

I don't have a strong opinion on the exact formula but here is a suggestion.

```
if type === 'COLLECTIVE'
  score = number of backers * total amount raised;
if type === 'ORGANIZATION' or type === 'USER'
  score = numbers of collectives backed * total amount donated
```

Reason I'm multiplying here is to make sure that we reward people with larger number of backers or collective backed (addition would make that number insignificant compared to amount of money)

Also, can we ignore (i.e. don't show) collectives that don't have a name?

**Comment by piamancini** [comment]
@HipsterBrown do we still need this open?

**Comment by HipsterBrown** [comment]
Yes, to keep track of the feature.
