### ISSUE TITLE
How to create a collective for projects not using github?

### ISSUE THREAD

**Issue by laf0rge** [opencollective/opencollective#1097]
At the Osmocom project (https://osmocom.org/) we have a strong belief in self-hosting our own infrastructure, including e-mail, lists, gerrit, gitolite, cgit, etc. 

We do have literally more than a hundred git repositories (see https://git.osmocom.org), but we don't host them on github.  Hence we don't have (nor want) "a github repository with 100 stars", as indicated on https://opencollective.com/opensource/apply

In all of the matierials I've read about opencollective before, there was no mention of github being a *requirement* to use opencollective.  The "Terms" only refer to an optional connection to github.

**Comment by laf0rge** [comment]
To be more precise: The "Terms" don't contain any mention of github.  It's only the privacy policy, which mentions github "We will share your name and avatar with Github if you participate in a collective that is also working on a software project through Github." - but that cannot be used to construe some kind of requirement for it.

**Comment by piamancini** [comment]
Hi @laf0rge thank you for this reminder, that we should add an alternative pathway for OSS that don't host in github on that link. 
Please go ahead and create your collective here opencollective.com/apply (choose something other than open source, we'll edit the settings manually on our end)

**Comment by piamancini** [comment]
closing since it answers the issue question, re-open or create another one if there are pending issues.
