### ISSUE TITLE
Typo on Open Source Collective page: "right" -> "write"

### ISSUE THREAD

**Issue by sloria** [opencollective/opencollective#1099]
URL: https://opencollective.com/opensource#about
Logged in as: sloria
Expected result: "You need to have at least two core contributors (people with write access to your repository)"

<img width="716" alt="open source collective - open collective 2018-05-23 19-32-33" src="https://user-images.githubusercontent.com/2379650/40456571-15197486-5ec0-11e8-8a91-c43541f8886d.png">

**Comment by xdamman** [comment]
Thanks! Fixed.
