### ISSUE TITLE
Create two-tiered approval for expenses

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#11]
Allow for Collective organizer/core contributor to approve expenses as well as the host. 
Eventually we could allow for collectives to choose between joint approval (host & organizer) or either/or approval.

**Comment by joeycrose** [comment]
For WWCode at this moment - we either need host + organizer at the transaction level or, maybe better, the ability for an individual to make an account and be approved by the director as an approved expenser... Happy to chat through this with you if it makes more sense.

**Comment by piamancini** [comment]
this is actually solved by V2
