### ISSUE TITLE
/donate keeps the pre-set amount even if you modify it in the box

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1102]
Typed 5 in the box, still being charged 10

<img width="998" alt="screen shot 2018-05-24 at 11 50 16 am" src="https://user-images.githubusercontent.com/3671070/40496892-e1010234-5f48-11e8-9610-9d6d380675b6.png">
<img width="895" alt="screen shot 2018-05-24 at 11 52 22 am" src="https://user-images.githubusercontent.com/3671070/40496945-f9ddda98-5f48-11e8-8ec1-63281825d3ef.png">

cc @xdamman

**Comment by xdamman** [comment]
That's because we make sure that the custom amount is never lower than the minimum suggested.
I'm adding an error message to make this more clear.
