### ISSUE TITLE
donations from my profile to a collective are showing up as amount raised

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1103]
I made two donations today from my profile with my credit card and they are showing up as amounts raised instead of amount donated. I checked the DB and I show up as backer not fundraiser. 

<img width="1273" alt="screen shot 2018-05-24 at 2 19 26 pm" src="https://user-images.githubusercontent.com/3671070/40503904-9189c79e-5f5d-11e8-8e0a-5673773fbc4e.png">

**Comment by xdamman** [comment]
I see two donations of $10. They increased your total amount donated from $680 to $700.

But they shouldn't have counted in the total amount raised. Looking into it.
