### ISSUE TITLE
Changing payment methods doesn't save credit card number

### ISSUE THREAD

**Issue by clarete** [opencollective/opencollective#1104]
Two users complained that they were not able to make donations. They both edited their payment method prior to trying to donate.

When I tried it myself on staging, although I was able to add the new credit card, it didn't really appear in the order form. I did notice that the last four digits of the card were not being saved. I wonder if that's related to it.

**Comment by piamancini** [comment]
The error they get is: 
<img width="1006" alt="screen shot 2018-05-24 at 2 28 34 pm" src="https://user-images.githubusercontent.com/3671070/40504262-cb8fd68a-5f5e-11e8-8794-917537310722.png">

Also, when we looked for their user and customer number in the host's stripe dashboard it wasn't showing up. The customer number and collective slug (opencollective.com/undefined) were showing up in the open collective inc. stripe dashboard.

I successfully (except for[ this bug](https://github.com/opencollective/opencollective/issues/1103) that might be unrelated) made two contributions. So it seems to be related to adding payment methods.

**Comment by znarf** [comment]
I have tested all workflows on staging and it works as expected.

- New subscription with a new credit card
- Changing credit card information for the subscription
- Deleting credit card from my account
- New subscription with a new credit card

One weird thing is that it's not possible to use one of my credit cards when I want to make a new subscription, I'm always asked to add a new one.

![screen shot 2018-05-25 at 09 27 45](https://user-images.githubusercontent.com/806/40531869-e98e158a-5ffd-11e8-9f07-0520f55a70f3.png)

**Comment by piamancini** [comment]
ok let's close until we see it again
