### ISSUE TITLE
Where can I find my sharing link for a project?

### ISSUE THREAD

**Issue by marktani** [opencollective/opencollective#1109]
I recently backed a project and received this referal link https://opencollective.com/graphql-shield?referral=16570.

I found it in the email, where can I find it on the homepage?
I can't find it on https://opencollective.com/graphql-shield.

**Comment by marktani** [comment]
Still can't find it :)

**Comment by piamancini** [comment]
Hi @marktani is this the link you are looking for? https://opencollective.com/_marktani

**Comment by marktani** [comment]
No, reading the email I get that notifies me of a donation, it sounds like there is a referral system:

![image](https://user-images.githubusercontent.com/1780597/45696210-5bbbf080-bb63-11e8-85c4-126d288edde5.png)

It says the total amount I help to raise will be shown in my profile.

This email is the only place I am aware of where this referral system is mentioned - maybe it is not yet in place? In this case I am ok with closing this issue 🙂

**Comment by piamancini** [comment]
Oh I see,  we should be clearer about this referral feature. If you go to your profile you'll see that you have amount donated and amount raised (see screenshot)
![screen shot 2018-09-18 at 10 58 55 am](https://user-images.githubusercontent.com/3671070/45696553-e126ad00-bb31-11e8-8f85-3476f0f2c777.png)
That is the only place we use the referral at the moment. We haven't really built much of a feature around it.

**Comment by marktani** [comment]
Got it! Thanks for helping me out, and for this project! 😄
