### ISSUE TITLE
Pull the list of contributors along with their organizations

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#111]
Goal: implement this: https://github.com/OpenCollective/OpenCollective/issues/105
![initiative](https://cloud.githubusercontent.com/assets/18429104/15728166/799ac276-2820-11e6-9e27-015142f66fd5.png)

Given the limitations of the Github api, I think it's best to pull the git repo and use tools such as `git-summary` or build a custom script to go through the git log. Note that we cannot do that on heroku because they don't provide a filesystem afaik. But that's ok, we can put that on a digital ocean box.

e.g.: 

    contributors('https://github.com/mochajs/mocha').then(contributors => {
     expect(contributors).to.be.deep.equal([{
          username: 'rauchg',
          name: 'Guillermo Rauch',
          website: 'http://...', 
          avatar: 'http://...', 
          company: { name: 'zeit', logo: '', url: '' }
          firstContributionAt: '2014-01-02', 
          lastContributionAt: '2015-12-14',
          totalContributions: 28
        }, {
          username: 'tj',
          name: 'TJ Holowaychuk',
          company: { name: 'Apex', logo: '', url: '' }
          totalContributions: 750,
          ...
        }, ...
      ]);
    });

**Comment by piamancini** [comment]
we fetch this info daily.
