### ISSUE TITLE
Emails should not display empty fields

### ISSUE THREAD

**Issue by sloria** [opencollective/opencollective#1113]
Transactional emails currently display empty fields.

<img width="500" alt="anonymous joined marshmallow as backer - sloria1 gmail com - gmail 2018-05-30 08-39-17" src="https://user-images.githubusercontent.com/2379650/40720513-ff1a9668-63e4-11e8-922a-5be700bfb27c.png">

I would expect "Frequency" and "Public message" to be hidden. Alternatively, "Frequency" could show "once". In any case, blank fields should not be shown.

More examples:

<img width="387" alt="your expense to marshmallow for 50 has been approved - sloria1 gmail com - gmail 2018-05-30 08-41-37" src="https://user-images.githubusercontent.com/2379650/40720601-4c500fc6-63e5-11e8-930c-e0834d30a47f.png">

<img width="533" alt="steven loria added you as a admin to marshmallow collective on open collective - sloria1 gmail com - gmail 2018-05-30 08-43-04" src="https://user-images.githubusercontent.com/2379650/40720667-80eecfd8-63e5-11e8-8fdf-70256515de18.png">

**Comment by sloria** [comment]
This appears to still be an issue. It's not a high priority, but I think it should still get fixed.

**Comment by piamancini** [comment]
This issue was also referenced by @luceos here https://github.com/opencollective/opencollective/issues/1795

**Comment by flickz** [comment]
Closed in [#1871](https://github.com/opencollective/opencollective-api/pull/1871)
