### ISSUE TITLE
Discuss superficially merging host org and host collective into one page

### ISSUE THREAD

**Issue by patcon** [opencollective/opencollective#1116]
I've been making plans to start demo'ing OpenCollective to some nonprofits, and the fact that a host has two pages (the org page for collective applications and the collective page for handling finances) seems a bit confusing to explain.

Might there be room for a discussion around treating the host collective as a special case (perhaps configurable in the host org settings) so that it gets hidden from the "member collectives" section, and its elements get merged into the host org page?

**Comment by piamancini** [comment]
cc / @xdamman

**Comment by xdamman** [comment]
Thanks for starting this conversation. 

I agree. The host should be able to also act as a collective on its own (and why not also allowing a user to have its own collective?). And the commission for the host should show up in its ledger in full transparency.

The good news is that hosts, organizations, users are already collectives in the architecture of the system. So it's fairly easy to make that happen. What's not easy is to reflect the commission for the host into the ledger. But that's something that @clarete is working on with the full double entry ledger (right now the commission is a different column in the `Transactions` table. It should be a row.)

As a first step, we could add a setting when editing an organization that is host to turn on "Run as a collective" to accept donations.
