### ISSUE TITLE
Unable to input payment details and become a backer

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1119]
I tried to set up a new donation as a backer, but the payment details area is blank and there's apparently no way to input credit card details. I have tried this in Firefox and Chrome, and on multiple collectives and it's the same.

This is what I see:
<img width="1156" alt="screen shot 2018-06-01 at 8 32 37 pm" src="https://user-images.githubusercontent.com/5498878/40830848-8b3d9094-65db-11e8-9b56-8b225f0794db.png">

If I click 'place order' I get:
<img width="1113" alt="screen shot 2018-06-01 at 8 30 18 pm" src="https://user-images.githubusercontent.com/5498878/40830873-98fb537e-65db-11e8-8d9c-f1789307280e.png">

**Comment by alannallama** [comment]
OK looks like it's only affecting me when I am logged in to Open Collective. I logged out and the credit card input field appeared.

**Comment by znarf** [comment]
Fixed in: https://github.com/opencollective/frontend/pull/475
