### ISSUE TITLE
Inject section in GH profile to see which collectives the person is backing

### ISSUE THREAD

**Issue by dasilvacontin** [opencollective/opencollective#112]
Maybe there, before the contrib chart.

<img width="789" alt="screenshot 2016-06-03 00 10 35" src="https://cloud.githubusercontent.com/assets/1260830/15762723/abb33874-291f-11e6-8aa9-a5cf4ddabf7f.png">

**Comment by piamancini** [comment]
cc/ @nayafia

**Comment by piamancini** [comment]
closing this as it's a github side issue.
