### ISSUE TITLE
Duplicated subscriptions

### ISSUE THREAD

**Issue by clarete** [opencollective/opencollective#1121]
Some users reported that their subscriptions got charged twice. I pulled the CSV files we get in from our daily report from the last two days and found 38 double charges.

Most of the occurrences I looked through so far have have duplicated subscriptions. Here are some examples:
 * https://opencollective.com/olavihaapala/subscriptions
 * https://opencollective.com/bmqb/subscriptions
 * https://opencollective.com/jackyalcine/subscriptions
 * https://opencollective.com/anthonydreaming/subscriptions

**Comment by clarete** [comment]
For reference, here's what I used to find the duplicates:

```python
import csv
from collections import defaultdict

F1 = csv.reader(open('2018-6-1.csv', 'rb'))
F2 = csv.reader(open('2018-6-2.csv', 'rb'))

P1 = ['..'.join(x[3:5]) for x in F1]
P2 = ['..'.join(x[3:5]) for x in F2]

CT = defaultdict(int)
for i in P1: CT[i] += 1
for i in P2: CT[i] += 1

DP = [k for k, v in CT.items() if v > 1]

print len(DP), 'dups:', ', '.join(DP)

```

**Comment by piamancini** [comment]
@clarete do we know if we accidentally created the manual subscriptions yesterday? One of the reports was from someone who had been charged the right amount until now. I guess one of them might be older dupes created by users in the order form

**Comment by piamancini** [comment]
Also can you please export a complete list with subscriptions and emails so I can refund and email explaining? Thanks!

**Comment by xdamman** [comment]
So we looked at the number of orders that were created within the same minute using this query:

```sql
with res as (
  SELECT 
    substring(cast(DATE_TRUNC('minute', o."createdAt") as text) from 1 for 16) as minute,
    count(*) as count, "FromCollectiveId", "CollectiveId", "totalAmount", max(o."currency") as currency,
    o.description,
    MAX(s."isActive"::INT) as "activeSubscription"
  FROM "Orders" o
  LEFT JOIN "Subscriptions" s ON o."SubscriptionId"=s.id
  WHERE (s."isActive" IS TRUE OR s.id IS NULL) AND o."deletedAt" IS NULL AND o."processedAt" IS NOT NULL AND o."PaymentMethodId" IS NOT NULL
  GROUP BY "FromCollectiveId", "CollectiveId", "totalAmount", "minute", o."description"
  ORDER BY count DESC
)
SELECT fc.slug, fc.type, r.*
FROM res r
LEFT JOIN "Collectives" fc ON fc.id=r."FromCollectiveId"
WHERE count > 1 ORDER BY r.count DESC
```

I've added this query in the wiki in case it can be useful in the future: https://github.com/opencollective/opencollective/wiki/Queries-for-ops

That returned 12 rows:
![](https://d.pr/free/i/8q10B9+)

Only 2 have active subscriptions. The one you already refunded and then https://opencollective.com/bilibilihuangyifan that we should contact and ask for details.

**Comment by piamancini** [comment]
![image2](https://user-images.githubusercontent.com/3671070/44113758-21461f36-9fd7-11e8-9272-23987e4ca1e4.png)
![image1 3](https://user-images.githubusercontent.com/3671070/44113768-2e90265a-9fd7-11e8-8805-11d0d6b3ebf5.png)
