### ISSUE TITLE
New HomePage

### ISSUE THREAD

**Issue by HipsterBrown** [opencollective/opencollective#1123]
This is a tracking issue for implementing the new home page design. 

[Invision link (small screen)](https://projects.invisionapp.com/share/UQF0FK26S#/screens/297103712)
[Invision link (medium screen)](https://invis.io/UQF0FK26S#/298239834_Homepage_-_M_-large_Tablets-)

Steps:

- [X] rebuild `TopBar` component with `styled-components`, using new design
- [X] rebuild `TopBarProfileMenu` component with `styled-components`, new design
- [X] rebuild `Footer` component with `styled-components`, new design
- [X] create "Latest Transactions" list with above-the-fold copy
- [X] create "Active Collectives" section
  - [X] create `CollectiveCard` component to display budget goals, stats
- [x] create "Create an open collective" section
- [x] create "Become a sponsor" section
- [X] create "Become a backer" section
- [x] create "Create an OC chapter" section
- [X] create "Today" stats sections
- [X] create newsletter subscribe form

### Preview:

**TopBar**:
<img width="337" alt="screen shot 2018-06-05 at 11 13 48 am" src="https://user-images.githubusercontent.com/3051193/40985246-b77668ec-68b1-11e8-9178-c4e68895d062.png">

<img width="1050" alt="screen shot 2018-06-05 at 11 13 35 am" src="https://user-images.githubusercontent.com/3051193/40985264-c0f6a918-68b1-11e8-905e-0089ffcf5ad7.png">

<img width="344" alt="screen shot 2018-06-06 at 1 06 51 pm" src="https://user-images.githubusercontent.com/3051193/41056614-c67dd0b4-6992-11e8-887a-942ef954f7eb.png">

**Hero Section:**
<img width="335" alt="screen shot 2018-06-07 at 3 36 00 pm" src="https://user-images.githubusercontent.com/3051193/41122256-f687d1c0-6a68-11e8-9159-c026f3e9e4c8.png">

<img width="1039" alt="screen shot 2018-06-07 at 3 36 20 pm" src="https://user-images.githubusercontent.com/3051193/41122268-fc9b8b74-6a68-11e8-8c9e-f5687279785e.png">

**Active Collectives Section:**

![oc-homepage-small-active-collectives](https://user-images.githubusercontent.com/3051193/41424878-3f4a4b4a-6fcd-11e8-99f3-56243c86c2a2.png)

![oc-homepage-large-active-collecitves](https://user-images.githubusercontent.com/3051193/41424886-42c5993c-6fcd-11e8-8c13-bb6be9b28d4c.png)

<img width="1073" alt="screen shot 2018-06-18 at 5 29 37 pm" src="https://user-images.githubusercontent.com/3051193/41563310-47e3a8d4-731d-11e8-8885-de4801415e04.png">

**Become a sponsor:**

<img width="380" alt="screen shot 2018-06-20 at 5 36 34 pm" src="https://user-images.githubusercontent.com/3051193/41686014-88fd439a-74b0-11e8-8ee4-4c183bf57096.png">

<img width="1328" alt="screen shot 2018-06-20 at 4 47 04 pm" src="https://user-images.githubusercontent.com/3051193/41685978-64f5b8ce-74b0-11e8-89cc-652e89c08a02.png">

**Become a backer:**

<img width="376" alt="screen shot 2018-06-25 at 6 47 23 pm" src="https://user-images.githubusercontent.com/3051193/41933115-f443d4a8-7950-11e8-91c0-4e1c1c4d52aa.png">

<img width="1098" alt="screen shot 2018-06-25 at 6 46 49 pm" src="https://user-images.githubusercontent.com/3051193/41933104-ed62e3f4-7950-11e8-920f-a71a872d0c21.png">

**Today we are:**

<img width="387" alt="screen shot 2018-06-27 at 3 14 47 pm" src="https://user-images.githubusercontent.com/3051193/42001595-71713d12-7a32-11e8-9a5e-7eeb85a0c6cf.png">

<img width="1130" alt="screen shot 2018-06-27 at 3 14 58 pm" src="https://user-images.githubusercontent.com/3051193/42001605-78d45698-7a32-11e8-992a-8b8722768251.png">

**Newsletter Form:**

<img width="358" alt="screen shot 2018-06-29 at 12 22 22 pm" src="https://user-images.githubusercontent.com/3051193/42107086-1e29b5f8-7ba4-11e8-8681-07e4ff6a1d0b.png">

<img width="1071" alt="screen shot 2018-06-29 at 12 20 48 pm" src="https://user-images.githubusercontent.com/3051193/42107092-22526238-7ba4-11e8-81bd-c8699f8eff3a.png">

**Footer:**
<img width="338" alt="screen shot 2018-06-05 at 11 14 14 am" src="https://user-images.githubusercontent.com/3051193/40985286-ce9b7148-68b1-11e8-8e88-093ddeb08bcc.png">

<img width="1047" alt="screen shot 2018-06-05 at 11 14 37 am" src="https://user-images.githubusercontent.com/3051193/40985292-d25a15f0-68b1-11e8-8f2e-4d84ad937080.png">

**Comment by piamancini** [comment]
- [ ] The transactions list shows donations to the host, should show donations to the collectives
- [ ] The logo on the nav bar (top left) seems the wrong design, where 'open collective' should be gray, not black. 
- [ ] the search on the top nav bar cut the word at 'Collect' extend so it reads 'collective'
- [ ] On the call to actions, there's a large white space next to the Create a Collective and Create a Chapter  CTA. Is this intentional?

**Comment by xdamman** [comment]
![](https://d.pr/free/i/SRtgzm+)

**Comment by xdamman** [comment]
![](https://d.pr/free/i/rAGlze+)

**Comment by piamancini** [comment]
We should add total fund raised here: 
<img width="1073" alt="screen shot 2018-07-04 at 11 12 09 am" src="https://user-images.githubusercontent.com/3671070/42268199-3457e874-7f7b-11e8-9508-5dad4336f468.png">

**Comment by piamancini** [comment]
new copy: https://docs.google.com/document/d/1ytCaijYNNil5vRwl0fDD8_gmYhUiYyH9xJnIt-9Uedc/edit#

**Comment by piamancini** [comment]
- [ ] Become a Backer Section: don't pull collective users that images is empty.
- [ ] Contribute & Chapter sections replace OC for Open Collective 
- [ ] Try to make cards height consistent
- [ ] search is cutting Open Collective in crhome
- [ ] see if we can add a total amount raised (@xdamman can you help find out where to pull this from?)

**Comment by piamancini** [comment]
@HipsterBrown still seeing the most active spending first (I forced refresh so it's not looking like a cache issue)

**Comment by HipsterBrown** [comment]
@piamancini I swear I did that locally, looks like I didn't save it. I'm pushing up that fix now.

**Comment by piamancini** [comment]
new copy for illustrations https://docs.google.com/document/d/1fg09p4SLHamHt89aFmBjU_wMdnFjGh2-GpzYZb5QC3Q/edit?usp=sharing

**Comment by xdamman** [comment]
- [ ] Footer feels off. Can we avoid having two rows?
- [ ] Numbers don't match what we currently have on the homepage (number of collectives and number of backers)

**Comment by xdamman** [comment]
- [ ] Update query to get top sponsors. See how we did it before to avoid returning hosts that add funds and our own investors https://github.com/opencollective/opencollective-api/blob/613895778d0803b63510d4a726b30aec3a911ddc/server/lib/queries.js#L377
- [ ] Dots below the carousel need to be bigger and more spaced out from the illustration (add top margin)

**Comment by cuiki** [comment]
More feedback:

1. The reason the footer looks weird in staging is because the footer (and the top bar with the nav + search) weren’t meant to be 100% width but a max width of 1280 px. Although the actual design does have it in 4 columns the grid system has a max width… https://tafka.d.pr/6GgYe1

2. We need to show 5 collective cards at the desktop view: https://tafka.d.pr/uwVGU2

3. I haven't seen the buttons' states applied. I'm assuming that they are not implemented yet. tI've already shared this with @HipsterBrown, still he buttons states & styles can be found here: https://invis.io/UDMY05M9MH6#/278359734_Buttons_-_States_-_Styles
![button-states-styles](https://user-images.githubusercontent.com/981188/42691895-6fb7a9d6-866f-11e8-810e-a32a0c264af9.png)

4. The width of the descriptions of the **'Join the Movement'** is too long: https://tafka.d.pr/qHlfEn.
