### ISSUE TITLE
Paypal(missing) appears after I add my paypal account

### ISSUE THREAD

**Issue by FadySamirSadek** [opencollective/opencollective#1124]
<img width="537" alt="screen shot 2018-06-07 at 11 15 09 pm" src="https://user-images.githubusercontent.com/7483806/41126771-e9eefaac-6aa8-11e8-8b92-bb337a388146.png">

**Comment by HipsterBrown** [comment]
@FadySamirSadek It is possibly due to certain permissions for your account related to the collective. Can you include more details, like a link to the expense and collective?

**Comment by FadySamirSadek** [comment]
https://opencollective.com/webpack
https://opencollective.com/webpack/expenses/3943

**Comment by HipsterBrown** [comment]
I'm am looking into this issue today @FadySamirSadek

**Comment by FadySamirSadek** [comment]
@HipsterBrown thanks

**Comment by HipsterBrown** [comment]
@FadySamirSadek You may have received a Login email that connects to the staging site. Sorry for the confusion, just debugging the issue.

**Comment by FadySamirSadek** [comment]
@HipsterBrown has this fix been published? because I am still seeing Paypal(missing)

**Comment by HipsterBrown** [comment]
@FadySamirSadek I'm testing it on staging now. Should be deployed to production by the end of the day at the latest.

**Comment by HipsterBrown** [comment]
@FadySamirSadek Can you check now?

**Comment by FadySamirSadek** [comment]
@HipsterBrown still the same, should I resubmit my expenses or do something to see the changes propagate?

**Comment by HipsterBrown** [comment]
@FadySamirSadek No, it should just work with the existing expense. Let me make sure the change was actually deployed.

**Comment by HipsterBrown** [comment]
@FadySamirSadek Ok it's actually deployed now. Check again, please?

**Comment by FadySamirSadek** [comment]
@HipsterBrown It is working now, Thank you so much for fixing it so fast 👍
