### ISSUE TITLE
Changing the URL should set up a redirect

### ISSUE THREAD

**Issue by arekkas** [opencollective/opencollective#1128]
I renamed my collective from `https://opencollective.com/ory-hydra` to `https://opencollective.com/ory-oss`. At first, both URLs worked but after a while the `ory-hydra` URL just showed a GraphQL Error (not even a 404):

![image](https://user-images.githubusercontent.com/3372410/41300981-55640130-6e67-11e8-9230-36d326cb444f.png)

Instead this should be handled similar to how GitHub handles this. If you rename the URL it should set up a 302 redirect to the new URL. IMO it should also disallow others to claim the old URL as to avoid scams.

**Comment by piamancini** [comment]
hmmm https://opencollective.com/ory-hydra works for me and https://opencollective.com/ory-oss doesn't...

**Comment by arekkas** [comment]
Yeah, I renamed it back because I didn't want to update all of the URLs everywhere!

**Comment by piamancini** [comment]
gotcha. I can change it for you now while we look into what's going on

**Comment by piamancini** [comment]
ory-oss then?

**Comment by arekkas** [comment]
Thanks, can you set up a redirect directly as well? Without redirect, I fear that:

1. People will browse to the old URL from some outdated link in the 10+ READMEs our projects have.
2. People will use the URL from browser's history and land at the broken site.

What I really want to do is actually have a company profile (we already have one [here](https://opencollective.com/ory)) were you can sponsor our efforts as we have 5+ open source projects and I don't want to set up a profile for each one. Is that possible?

**Comment by arekkas** [comment]
So ideally, I'd like to have `https://opencollective.com/ory` which links to our [GitHub organization](http://github.com/ory/) and explains our vision & what we do. There you can become a sponsor and help us out with all our projects (e.g. https://github.com/ory/hydra , https://github.com/ory/ladon , https://github.com/ory/editor, ...)

**Comment by piamancini** [comment]
got it. That's not complicated for us to do, we can just transform your current collective and link it to the githubOrg. The only issue is the redirect, which I'm not sure we can do. So you might need to go in and change the links. 
@xdamman what do you think about this?

**Comment by arekkas** [comment]
Ok, that sounds reasonable. Just to confirm:

I'll update the company profile from [`https://opencollective.com/ory`](https://opencollective.com/ory) to e.g. `https://opencollective.com/ory-gmbh` (gmbh = ltd in germany) and `https://opencollective.com/ory-hydra` to `https://opencollective.com/ory`, right? Then I would update the links and description accordingly.

After that, only the redirects would need to be set.

Thank you for the immediate response and help, by the way!

**Comment by piamancini** [comment]
Correct and I'll manually link the github settings to go to the org instead of the hydra repo. 

Please note that I don't have an answer on the redirects yet. I don't think we do them, so you might need to go in and change links manually. If this is a blocker, wait for @xdamman to confirm before you make the changes.

**Comment by arekkas** [comment]
Ok, sounds good, let's do that! I'll rename the profiles now.

**Comment by arekkas** [comment]
Ok, I renamed `https://opencollective.com/ory` to `https://opencollective.com/ory-company` and `https://opencollective.com/ory-hydra` to `https://opencollective.com/ory`!

**Comment by arekkas** [comment]
Awesome, thanks for the heads up!

**Comment by arekkas** [comment]
@piamancini I'd just like to reconfirm this. You said

> This doesn't have any effect at them moment since we stopped showing every repo contributor on the collective's pages, because it was too heavy.

Does that imply that this part

```
This project exists thanks to all the people who contribute. [[Contribute](CONTRIBUTING.md)].
<a href="graphs/contributors"><img src="https://opencollective.com/ory/contributors.svg?width=890&button=false" /></a>
```

in my project's readme does no longer work? Also, how will the display of this image change once the collective's URL is the organization and not a specific repository?

Thank you again for the quick & helpful responses.

**Comment by piamancini** [comment]
I was referring to the code contributors being displayed on your collective. 
Readme should work. Is it not working?

**Comment by arekkas** [comment]
Ah I see - no it is working which is why I was a bit confused :)

**Comment by piamancini** [comment]
great.
closing this then. best
