### ISSUE TITLE
Back Your Stack

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1129]
We're working on a small side project name "Back Your Stack". The goal is to analyze the projects that are used by organizations or individuals, then give recommendations of collectives to support.

The first version will be relying a lot on data fetched from GitHub, will detect `npm` packages based on the content of `package.json` dependency files, then match the Open Collectives behind these packages. Future versions should be able to handle data from other package managers such as `Composer` (PHP) or `Gems` (Ruby).

Like others Open Collective projects, the app itself is written in Javascript using the `Node`, `React`, and `Next.js`. It's obviously Open Source: https://github.com/opencollective/backyourstack

The first public version should be released this month already!

A first (embarrassing) development snapshot is already live: https://backyourstack.now.sh/

# Features

## Home Page

 - Introduction text
 - 4 possibilities:
   -  [x] Connect with Github
       - [x] If connected, display User Organizations and Profile
   -  [ ] Search (users and organizations)
   -  [ ] Browse suggested organizations (Airbnb, Facebook, etc ...)
   - [ ] Drag'n'drop/Upload dependency file (such as package.json)

## Profile Page

 -  [x] Name and profile data of the Organization / User
 - Badge/ranking (how many backed projects, how much $)
 - Organize content in 3 sections
   - Recommendations
     -  [x] Open Collective projects
     - Featured projects to pledge (not on Open Collective yet)
   - Dependencies
     -  [x] Summary of all dependencies with their repos
   - Repositories
     -  [x] Recap of all the repositories analysed
     - Ability to unselect / reselect repositories (to ignore some)

## Intelligence

  - Match Github Organizations with their OpenCollective profile
     -> Highlight when organizations are already backing collectives

## Pledge

 - Ability for authenticated users to pledge, in behalf of themselves or their organizations.

## oAuth

 - [x] on signout, delete token (easier to debug when retriggering the Github Authentication)

## Session persistence

  - Session is currently wiped on deploy (use Memcache on Heroku?)

## Caching persistence

  - LRU server side is currently wiped on deploy (use Memcache on Heroku?)
  - LRU client side is currently wiped on page refresh (use a backend proxy instead?)

**Comment by piamancini** [comment]
design is being currently discussed in this issue https://github.com/opencollective/backyourstack/issues/2
