### ISSUE TITLE
collective reports are not going out

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1130]
Host reports and user reports are going out, but the last collective reports I can see are from December. 
This tells us two things: 
a) we need to put some alerts in place for when some of our core processes fail
b) no one reads the collective reports.

**Comment by piamancini** [comment]
another collective just ask for them. Please solve this. 
Is there any way to generate manually?

**Comment by phated** [comment]
I noticed this too ☹️

**Comment by xdamman** [comment]
Fixed in https://github.com/opencollective/opencollective-api/pull/1342
