### ISSUE TITLE
host can't add funds 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1131]
<img width="838" alt="screen shot 2018-06-14 at 10 22 10 am" src="https://user-images.githubusercontent.com/3671070/41418045-ee679490-6fbc-11e8-9943-7e43421c8d1a.png">
URL http://opencollective.com/talkwellington-host/collectives/expenses

**Comment by clarete** [comment]
I can look into it!

**Comment by clarete** [comment]
I just pushed a fix to prod. Please re-open this ticket if that doesn't work for you!
