### ISSUE TITLE
individual invoices are serving the old 404 (travolta)

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1133]
https://opencollective.com/evance_net/transactions/# 
See for example first transaction https://opencollective.com/evance_net/transactions/67beb3c3-859b-4be1-90d9-6a1d9a358376/invoice.pdf

This doesn't seem to be happening for other users.

**Comment by piamancini** [comment]
update @xdamman one of your invoices is also giving the same 404 
https://opencollective.com/xdamman/transactions/# click on the download PDF 
in the 'Monthly donation to Co-Labs' donation It serves this: https://opencollective.com/xdamman/transactions/null/invoice.pdf

**Comment by xdamman** [comment]
It's probably related to the underscore in their username, since the only thing that really matters here is the UUID of the transaction, you can download it directly here: https://opencollective.com/evancenet/transactions/67beb3c3-859b-4be1-90d9-6a1d9a358376/invoice.pdf

**Comment by znarf** [comment]
@Betree is about to fix that I think

**Comment by Betree** [comment]
Yes that will be fixed with the invoice update
