### ISSUE TITLE
sign-in css looks broken

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1135]
<img width="996" alt="screen shot 2018-06-20 at 11 59 53 am" src="https://user-images.githubusercontent.com/3671070/41670174-8d878e86-7481-11e8-9134-e50937c462c2.png">
<img width="842" alt="screen shot 2018-06-20 at 12 00 59 pm" src="https://user-images.githubusercontent.com/3671070/41670229-bb5e4822-7481-11e8-91aa-c82ff7c35756.png">

**Comment by HipsterBrown** [comment]
This has been fixed before, I believe this is a caching issue that will be resolved as soon as the cloudflare cache is refreshed.
