### ISSUE TITLE
Allow multiple hosts to receive PayPal donations

### ISSUE THREAD

**Issue by clarete** [opencollective/opencollective#1140]
Our current implementation of PayPal is unfortunately not prepared to receive payments for more than one host.

We initially tried to use the Braintree OAuth (Renamed from Auth) solution to provide that functionality. The idea was that a host manager would connect their PayPal account via OAuth and allow Open Collective to create transactions on behalf of their merchant account. Sadly, Braintree didn't want to give us a production account (not sure why exactly but @piamancini or @xdamman might have more data).

The sad thing is that Braintree did a great job simplifying how PayPal works and we can't really leverage that. PayPal also has a Marketplace product that would allow us charging people on behalf of the host but this product also requires Open Collective to apply and receive authorization from PayPal to use it on production, so we might not be able to leverage that without getting production access :( :( :(

Maybe we could allow the host managers to do the required configuration on the PayPal side using their merchant account and then give them a way to upload their PayPal keys. This suggestion is indeed inferior to any OAuth based solutions, but I wonder if that'd be safe enough for our use case.

**Comment by xdamman** [comment]
For now, we could just add the PayPal API credentials as a connected account instead of them being part of the env environment. To make it more secure, we could encrypt them using a key in the env environment. 
What do you think? I think it's fine for that process to be cumbersome for the host. It's something that needs to be done only once anyway.

**Comment by znarf** [comment]
This is still relevant.
