### ISSUE TITLE
Payout email being changed incorrectly on expense

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1143]
I've gotten a few reports from users that an incorrect email is being applied expenses when they submit it. 

I raised #1132 to enable people to edit the email after submitting, but this seems like a bug where it saves a completely different email than they put in.

Examples: 

https://opencollective.com/boostnoteio/expenses/3773
https://opencollective.com/boostnoteio/expenses/3772
https://opencollective.com/boostnoteio/expenses/3771
https://opencollective.com/boostnoteio/expenses/3770
https://opencollective.com/boostnoteio/expenses/4032
https://opencollective.com/boostnoteio/expenses/4033

https://opencollective.com/boulder-react-meetup/expenses/3424

**Comment by HipsterBrown** [comment]
@alannallama Sorry about the late response to this. The platform does not currently support filing expenses on behalf of other users, i.e. by using different a PayPal email per expense. When an expense is created, the API will update the logged in user's PayPal email if it doesn't match the PayPal email of the expense. When the expense is paid, the API uses the PayPal email of the user that created the expense. The way for BoostNote to manage expenses for multiple users is to have actual accounts for each of those users. 

Currently, Open Collective doesn't have a way for users to manage their PayPal email through their profile settings but it is something we will be exploring.

**Comment by alannallama** [comment]
Thanks @HipsterBrown — I have informed the user.
