### ISSUE TITLE
Transactions linked to the wrong user

### ISSUE THREAD

**Issue by clarete** [opencollective/opencollective#1144]
### Intro

We've seen this bug happen twice so far. Users perform donations that never appear in their profile. And then after some digging we find out that the transactions were associated with the wrong users.

### Background

Someone had a yearly subscription to consciousness hacking sf they created last year. The person was charged this year and wanted to cancel since it's being a while since they interacted with the collective.

When we tried to cancel, we had problems finding the transactions for that donation. They were not associated with the user whose credit card was charged.

The transactions were actually associated with one of the admins of the consciousness hacking sf collective. The admins profile was associated with the Order, the subscription, the transactions and their email was associated with the stripe user. Although the credit card didn't really belong to her.

### Important database rows

* User that originated the donation: ID: 5318, CollectiveID: 1490
* SubscriptionID: 2360 (created 2017-06-07 21:32:39.)
* OrderID: 3139

**Comment by piamancini** [comment]
We should cancel the subscription of the user who is trying to cancel before the 7/1

**Comment by clarete** [comment]
> We should cancel the subscription of the user who is trying to cancel before the 7/1

Done with the following statement:

```sql
update "Subscriptions" set "isActive" = false, "deactivatedAt" = now() where id = 2360;
```

**Comment by piamancini** [comment]
Ok. We also need to refund, to that credit card. We can't do it from the /transactions because it's not showing up. Please ping when we allocate this to the correct user so we can make the appropriate refund

**Comment by clarete** [comment]
@piamancini I think it was already refunded on the stripe side but I'll double check!!

**Comment by clarete** [comment]
Here's the query that I started working on to try to find other occurrences. It's going to be a lil more complicated because we've used that field for other values (like the user's name):

```sql
select
	"data"::json->'charge'->'metadata'->'customerEmail' as "memail",
	"data"::json->'charge'->'source'->'name' as "sname"
from "Transactions"
where
	"deletedAt" is null and
	"data"::json->'charge'->'metadata'->>'customerEmail' != "data"::json->'charge'->'source'->>'name';
```

I'll filter out things that don't look like email addresses and see how that goes.

**Comment by clarete** [comment]
Here's the SQL used for moving the transaction to the right user:

```sql
update "Orders" set "CreatedByUserId" = 5318, "FromCollectiveId" = 1490 where id = 3139;
update "Transactions" set "FromCollectiveId" = 1490 where id = 85938;
update "Transactions" set "CollectiveId" = 1490 where id = 85936;
```

I'll proceed with the refund after I run the above queries

**Comment by clarete** [comment]
Refund executed!
