### ISSUE TITLE
Expense Flow → Provide reason when expense is rejected

### ISSUE THREAD

**Issue by Kilheure** [opencollective/opencollective#1148]
URL: https://opencollective.com/uk

When a host or collective admin reject expense, a reason for rejection must be mandatory. 
I had to reject 2 expenses lately as the recipient name was not correct. In addition, I can not contact the collective admin as there is no contact detail available... 

Collective will resubmit expense but doesn't know what to correct. It will be rejected again...
Not sure how to close the loop here

Please advice. 
Thanks
Dimitri

**Comment by alannallama** [comment]
We still need this

**Comment by piamancini** [comment]
this needs to be open until we ship expense flow redesign

**Comment by alanna** [comment]
@Memo-Es I thought this was in scope for the Expense flow project, but I just rejected an expense and it didn't ask me for a reason. Can we get this included somehow?

**Comment by Memo-Es** [comment]
Yes! we have the design for that, I will check it out and raise it up with the dev team 

cc @Betree

**Comment by Betree** [comment]
Why not using the comment system for that?

**Comment by alanna** [comment]
It can function like a comment. The only thing needed is a modal that pops up when you click 'reject' with a box saying "Give rejection reason (optional)" and a button below that saying "Reject" again. This makes it much more likely a reason will be given, and also gives people a chance to confirm if they almost rejected by accident.

**Comment by Memo-Es** [comment]
@alanna @Betree 

![Reject-expense-reason](https://user-images.githubusercontent.com/49539954/90198309-f1d01400-dd96-11ea-9a40-5dd46d76ee89.png)


It will be published as a comment
What do you guys think?

**Comment by alanna** [comment]
The design looks good. But make it optional, not required, to put a comment
here. Also, remove the text in the box because we can't assume the host
admin wants to encourage the person to resubmit (sometimes it's spam). Just
leave it blank.

**Comment by Memo-Es** [comment]
The 'Cancel' button is not enough to make it optional?

**Comment by alanna** [comment]
No, because the action is "reject expense" not "post comment" so cancel
means "don't reject the expense" not "reject the expense but don't put a
comment".

**Comment by Betree** [comment]
Are we good to implement the design shared in https://github.com/opencollective/opencollective/issues/1148#issuecomment-673776575?

**Comment by alanna** [comment]
Is this done?

**Comment by Betree** [comment]
No yet. I asked https://github.com/opencollective/opencollective/issues/1148#issuecomment-675329004 to know if the latest design was ready to be implemented.

**Comment by alanna** [comment]
Oh sorry, I wasn't clear if my feedback above had been incorporated. If so, then yes, this looks good. Just remove the placeholder text and make the comment optional.

**Comment by Betree** [comment]
This issue requires https://github.com/opencollective/opencollective/issues/4081, there's currently no notification when an expense is rejected.

**Comment by iamronen** [comment]
marking this as closed as part of work done in #6677
