### ISSUE TITLE
Monthly report email flagged for phishing

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1151]
I'm not sure why it was flagged, but I grabbed screenshots before clicking "I trust this email".

<img width="664" alt="screen shot 2018-07-02 at 4 31 54 pm" src="https://user-images.githubusercontent.com/5498878/42145439-a36e7f3c-7e15-11e8-91ad-945be6d69b22.png">

<img width="631" alt="screen shot 2018-07-02 at 4 32 12 pm" src="https://user-images.githubusercontent.com/5498878/42145441-a64585b6-7e15-11e8-9e75-abf61f5f62d1.png">

**Comment by alannallama** [comment]
I got a bunch of other monthly report emails at the same time and they were not flagged.

**Comment by xdamman** [comment]
can you share where the "learn more" links to?

**Comment by alannallama** [comment]
Ah sorry I clicked "trust this message" and the warning disappeared.
