### ISSUE TITLE
invoices are serving a 'unexpected error'

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1159]
<img width="790" alt="screen shot 2018-07-07 at 7 44 03 am" src="https://user-images.githubusercontent.com/3671070/42407297-bbb59380-81b9-11e8-97f4-dcd3911beddc.png">

**Comment by znarf** [comment]
It's failing in `TransactionDetails.js` because `transaction.host` is `null`.

**Comment by piamancini** [comment]
It’s also failing for other users like Facebook. @xdamman can this be related to the fix you did yesterday?

**Comment by xdamman** [comment]
Yes it's related to this: https://github.com/opencollective/opencollective/issues/1154
I'm pushing a fix to be able to see the list of transactions. The invoice PDF is still being generated by the old website repo. So will need a separate fix for that.
