### ISSUE TITLE
/partidodigital ledger issues

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1161]
Last transaction recorded was in March 2018. Are they still using it?

Also, a bunch of transactions, orders, expenses are in USD while others are in UYU and the host is in UYU. This is making the ledger health check script fail. Is it normal that they have transactions in multiple currencies?

You can list all those transactions with the following query:
```sql
SELECT * FROM "Transactions" WHERE "CollectiveId" = 8647
```

**Comment by piamancini** [comment]
They were using it, not sure the state now. March 2018 is not so long ago. Why do you ask?
This collective used to receive donations in paypal, the combination of currencies is probably legacy from that.

**Comment by piamancini** [comment]
we can close this. What's the actionable item?
