### ISSUE TITLE
css fixes in tier page

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1166]
From user: 
1. when editing tiers if there are quite a few different amounts you can't see the amounts you are trying to edit:

![can t_see_values](https://user-images.githubusercontent.com/3671070/42682521-1a188326-868b-11e8-8bdb-f04b55269572.png)

2. Similarly, when contributing it looks a bit wrong if there are more than 3 options to choose from (and the higher amounts are seemingly impossible to see/ select :-/ )  I seem to remember these various amounts previously being listed horizontally as opposed to vertically and when that was the case I don't think this was an issue:

![higher_values_hidden](https://user-images.githubusercontent.com/3671070/42682525-1c0cd9f2-868b-11e8-83b2-c7cbe1437ccc.png)

**Comment by xdamman** [comment]
For the first issue, what about we limit to 5 different options max?

**Comment by piamancini** [comment]
this is fixed.
