### ISSUE TITLE
Improvement → The system could automatically create invoices

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1167]
A lot of Open Collective users are not familiar with sending invoices, and many of them don't know how to create one to expense for their time from Collectives. We spend time getting them to include invoices or correct issues with them. One recently complained to me about it, saying "Patreon doesn't require an invoice". I thought how Patreon _does_ actually require one—they just create it for the user automatically when a payout it made, because they have all the required info in the system already.

This made me realise, Open Collective could gather the info beforehand (name, address, and paypal email) and just have a simple form for charging for work done (which Collective, what was done, how much $). There would still be an option to upload a receipt or user-created invoice if they need to, but for many many users this would be much simpler for them, and better for us as well because we'd get all the info required for the invoice automatically.

## Notes
* This could be part of a pro-version

**Comment by alannallama** [comment]
Note: the option to 'pay 100% of the balance' is there so the system can automatically set it to the correct amount minus fees, as discussed in #1073

**Comment by cuiki** [comment]
Hi @alannallama , thanks so much for putting this together. I'll review and post questions and comments. As @xdamman said, I have a few issues to tackle first but this will get some design love in the coming weeks!

**Comment by alannallama** [comment]
The other thing this design would fix is the issue where the tax bot tells people they have to submit their tax form, even if they are claiming reimbursement and not invoicing for time (when they don't actually need to do the tax form).

**Comment by xdamman** [comment]
I’m confused by that comment. For legal reasons we need to have the invoice/receipt. There is no way around that.

But I agree that we should record once and for all the bank details of the user for the payout.
Also adding a way to generate an invoice automatically would be very useful. And there too we could record most of the details of the user once and for all.

**Comment by piamancini** [comment]
+1 to generating invoices automatically

**Comment by alannallama** [comment]
@xdamman - yes we need invoices. But the idea here is to collect all the information we need for them once (name, address, etc), and then automatically generate them when users submit expenses (with the amounts and dates). But the user would never have to see this invoice, and would not have to repeatedly submit the same information. The user feedback above is because this user was put off by uploading a PDF with their personal info over and over, but they were fine giving us that info at least once because they've been paid before. This does not apply in the case of receipt reimbursements, since we still need the receipt, but it doesn't have the person's private info on it normally.

**Comment by piamancini** [comment]
Don't let this stale. This should be part of a pro version we offer to individuals (things to include, automatically email and create an expense, etc)

**Comment by alannallama** [comment]
Good suggestion from #2035 - make an option for a repeating invoice.

**Comment by piamancini** [comment]
This needs to be kept open until release.

**Comment by Betree** [comment]
This is done
