### ISSUE TITLE
Auto generate monthly invoice for hosts with platform fees

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1172]
For accounting purposes, the host needs to report the platform fees that they had to pay.
We should automatically generate a PDF on a monthly basis.

**Comment by znarf** [comment]
@xdamman because you have the most knowledge on this issue, can you add some basic specifications and where to look at?

**Comment by xdamman** [comment]
There is already a monthly email going to hosts so I'd just attach that invoice as a PDF with just the platform fees for the month.

See https://github.com/opencollective/opencollective-api/blob/master/cron/monthly/host-report.js
And this is where we already attach the PDF of all expenses for the month: https://github.com/opencollective/opencollective-api/blob/master/reports/host-report.js#L291

So we just need to generate another PDF probably the same way that we generate the invoice for donations. @Betree can give more details on how that's done.

**Comment by alanna** [comment]
this is done
