### ISSUE TITLE
airbnb is not showing up as a gold sponsor in the tier cards in the right bar

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1175]
<img width="344" alt="screen shot 2018-07-18 at 9 12 25 am" src="https://user-images.githubusercontent.com/3671070/42894617-97f6ea46-8ab7-11e8-95da-de55f1f9c415.png">

but here 

![image from ios](https://user-images.githubusercontent.com/3671070/42894660-b08e6390-8ab7-11e8-8b1a-4454601afe1b.png)

They are asking for this to be fixed this week because they have internal reporting.

**Comment by xdamman** [comment]
A better way to fix this would be to allow admins to edit the tier that a given backer belongs to.

**Comment by piamancini** [comment]
closing this issue since it has been fixed. 
Tiers need to be refactored to scale and function properly, but that should be a separate issue.
