### ISSUE TITLE
Show top spenders on homepage based on burn rate, not latest expenses

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1176]
Instead of showing the latest collectives that have spent money which lead to random and poor results: 
![](https://d.pr/free/i/miHfdR+)

we should show the collectives that spend the most money per month (aka burn rate)
![](https://d.pr/free/i/wDV2Fn+)

Also, it's weird to show "Top spenders" and not showing any information about how much they are spending.
So I'd suggest to show the burn rate instead of the number of sponsors in the card (and show the total number of backers which includes individuals and organizations).

**Comment by xdamman** [comment]
I have a PR ready for this but I first need to wait for this one to be merged before I can submit it https://github.com/opencollective/opencollective-api/pull/1371 /cc @HipsterBrown

**Comment by piamancini** [comment]
works for me. Let's get this merged today because homepage announcement is going in the newsletter.

**Comment by xdamman** [comment]
Mmmm... technically burn rate is supposed to be the difference between the money in and out
See: https://en.wikipedia.org/wiki/Burn_rate

The term became popular with startups that would anyway not have any revenue. So burn rate in their case meant the money spent per month. I guess it's not really true for collectives since they are getting some money.

How should we label this then?
Is it acceptable to use this term? Is there another one that would be a better fit? Any ideas?

**Comment by xdamman** [comment]
Alright, we will go with "monthly spending"

**Comment by piamancini** [comment]
I'm still seeing active spenders and a lot of wwcode ones.
