### ISSUE TITLE
Expense approved email rounds the amount up

### ISSUE THREAD

**Issue by luceos** [opencollective/opencollective#1177]
URL: https://opencollective.com/tenancy/expenses/4338
Logged in as: luceos

New expense mail lists correct amount:

![image](https://user-images.githubusercontent.com/504687/42907674-d481edc2-8ade-11e8-91d5-5a917daacbdd.png)

Approval email does not:

![image](https://user-images.githubusercontent.com/504687/42907695-e791cf5e-8ade-11e8-8c7d-17c892501e81.png)

**Comment by xdamman** [comment]
Opportunity for first PR? :-)
https://github.com/opencollective/opencollective-api/blob/master/templates/emails/collective.expense.approved.hbs

See: https://github.com/opencollective/opencollective-api/blob/master/templates/emails/collective.expense.created.hbs#L6

**Comment by luceos** [comment]
@xdamman i'll jump onto that opportunity 😁
