### ISSUE TITLE
subscription page fails for airbnb and coinbase

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1178]
Added funds today to both organizations and made the contributions. 
Everything else seems to work ok but their subscription  page serves and unexpected error 
This is specially important for airbnb since they might want to modify some of their subscription amounts for the coming months. 

<img width="958" alt="screen shot 2018-07-19 at 12 58 02 pm" src="https://user-images.githubusercontent.com/3671070/42938821-de400e78-8b53-11e8-9bcf-f53b230fdf2b.png">
<img width="1263" alt="screen shot 2018-07-19 at 12 58 40 pm" src="https://user-images.githubusercontent.com/3671070/42938823-dfb68886-8b53-11e8-85ad-3fffd351352c.png">

**Comment by xdamman** [comment]
were you logged in? as whom?

**Comment by piamancini** [comment]
logged in as myself (I am an admin of both collectives)

**Comment by lencioni** [comment]
I see this as well, and am logged in as the Airbnb admin user. It seems to first render the page and then a moment after the user info in the top right loads it changes to this page with the error message.

**Comment by xdamman** [comment]
Yes, we have a fix coming. But CircleCI was down for a while today so we couldn't deploy it. It's back up now so waiting for the tests to pass then it will be deployed. Thanks for your patience!

**Comment by xdamman** [comment]
It's deployed now. Sorry about the delay!
