### ISSUE TITLE
Adding a member without email succeeds with error

### ISSUE THREAD

**Issue by luceos** [opencollective/opencollective#1179]
Whenever you add a member, but do not add an email address you receive an error when saving. I guess it's from the xhr. 

However, the member does get added and listed. Editing the members' mail address is now no longer possible without removing her first.

It would make sense for the member to not get added or to be able to edit the mail address in case it's blank.

***

URL: https://opencollective.com/tenancy/edit#
Logged in as: luceos
Error message if any: can't remember
Expected result: disallow member adding or allow editing email later on

**Comment by xdamman** [comment]
Thanks for reporting. Fix coming.
