### ISSUE TITLE
Allow for assigning of sponsors from off platform and/or old events

### ISSUE THREAD

**Issue by bmann** [opencollective/opencollective#1183]
I have entered an old event for the purposes of collecting expenses. I'd like to indicate that certain organizations have sponsored, and they have already paid.

Is there a way, other than listing the sponsorships as free and asking them to register, that I in the backend can indicate that a sponsor has taken one of those slots?

**Comment by piamancini** [comment]
Sponsors are computed based on their financial contributions. A workaround is to include their logos using markdown on the event's or collective's descriptions.

**Comment by bmann** [comment]
@piamancini thanks for the update!

That still doesn't work for in-kind sponsors and other kinds of common occurrences. It also means that their logos don't appear in various embeds and badges.

No problem if this isn't in scope / isn't a feature that is of interest right now -- I wanted to capture the use case and indicate it was something I would find valuable. Cheers!

**Comment by piamancini** [comment]
Thanks @bmann Closing this for now then.
