### ISSUE TITLE
New homepage

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#119]
We would love to have a new homepage to showcase the latest collectives / activities on the platform.

We should proceed step by step to make sure that every week we deploy improvements.

We could start by showcasing the latest and most popular collectives, the latest backers and sponsors.

We would also love to show a graph of the total amount raised per month throughout all collectives.

**Comment by erickrico** [comment]
awesome, working on it (:

**Comment by erickrico** [comment]
@xdamman quick question at this point in oc people who come to the homepage should be encourage to create a collective or explore and support current collectives? i know both are importan but which one should be the main focus

**Comment by xdamman** [comment]
Definitely explore and support current collectives

But I think it would be good to have a section about open source collectives in which we should have a link to the github flow.

And then a section with all the other types of collectives.

**Comment by xdamman** [comment]
We should also change the tagline to "Start collecting money for your community"

And add somewhere the definition of what an open collective is:

```
Open Collective | ˈōpən kəˈlektiv |
An unincorporated association that operates in full transparency
· transparent: anyone can follow the money
· open: anyone is welcome to join and contribute
· fluid: leaders can change over time
```

**Comment by erickrico** [comment]
Just to get it going, this is the first draft, please let me know any feedback, still gotta figure out how to add other key points in the home page.

## home
![home](https://cloud.githubusercontent.com/assets/18429104/16026976/ff9ecb94-3197-11e6-9f32-d2a69a69fcc6.png)


## home notes
![home-notes](https://cloud.githubusercontent.com/assets/18429104/16026978/0babe714-3198-11e6-9739-8a9a84fa8711.png)


## video idea

i think we can explain quicker what a opencollective is with a video, this in order to introduce the collectives earlier and dont spend that space explaining the main idea and how it works.

**Comment by erickrico** [comment]
![collective-home](https://cloud.githubusercontent.com/assets/18429104/16101018/2b11ce8e-3328-11e6-9424-eeee627743f0.png)

**Comment by xdamman** [comment]
I really like the stats and the list of collectives. But I'm not a fan of the way the thumbnail of each collective comes up. The background is off. What do you think?

I wouldn't use a dropdown for now. I'd just have one such section for open source and one for meetups. 

For the hero, We can't really use that background image. Also it should convey a group or community. 

I like better the 3 vignettes instead of the two columns. 
The 3 steps should be:
- create a collective
- collect money from backers/sponsors/members
- submit expenses, be transparent

**Comment by xdamman** [comment]
The thumbnails for a collective is a hard one to get right. See on the profile page: 
https://opencollective.com/xdamman
https://opencollective.com/digitalocean
It doesn't look great with the collectives that we have. Not sure what would be the best. What do you think?

**Comment by erickrico** [comment]
![home](https://cloud.githubusercontent.com/assets/18429104/16211611/362bfd9c-3708-11e6-9a4f-e29c04dd788d.png)

**Comment by xdamman** [comment]
Those thumbnails for collectives are great. @carlosascari can you implement those components so that it will also reflect on the profile page? You can also already start implementing the homepage. 

Now we just need to find something for the hero.

**Comment by erickrico** [comment]
![home](https://cloud.githubusercontent.com/assets/18429104/16249518/0124bc40-37dc-11e6-8efe-f4f872bd8bf6.png)

**Comment by xdamman** [comment]
Ship it

**Comment by erickrico** [comment]
minor visual upgrades and text corrections 
![home](https://cloud.githubusercontent.com/assets/18429104/16278949/72355c8a-387e-11e6-8734-96160b18f963.png)

**Comment by erickrico** [comment]
@xdamman for the stats, what are the real numbers? im trying to figure out if this is the best way to display the information or if showing the real data will play against us at this moment

**Comment by xdamman** [comment]
We should never fear to display the real data. I can create an endpoint for this.

**Comment by xdamman** [comment]
Here is the PR https://github.com/OpenCollective/opencollective-api/pull/469

**Comment by asood123** [comment]
Launched!
