### ISSUE TITLE
Redesign Expense Details page

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1191]
E.g. https://opencollective.com/webpack/expenses/4394

- The attachment should be much bigger (we shouldn't have to open it in a new window to be able to read it)
- We should show the history of that user (previous expenses from same user, total expensed)
- We should be able to go to next/previous expense in same collective (or if coming from the host dashboard, to the next/previous expense of the current selection, e.g. all approved expenses ready to be paid across all hosted collectives)

**Comment by piamancini** [comment]
closing this in favor of https://github.com/opencollective/opencollective/issues/1326
