### ISSUE TITLE
is it possible to self-host opencollective?

### ISSUE THREAD

**Issue by ghost** [opencollective/opencollective#1192]
Sorry if this is not the right place... please feel free to redirect ;-)

I would like to self-host opencollective because the project I'm involved in does not qualify to apply. Where could I read about that?

Thanks in advance for your help!

**Comment by xdamman** [comment]
Yes it is.
More info here: https://github.com/opencollective/opencollective/wiki/Becoming-a-Host

**Comment by dachary** [comment]
@xdamman Sorry for being imprecise about [the meaning of self-host](https://99robots.com/the-difference-between-hosted-and-self-hosted-website-platforms/). I meant running the opencollective codebase on an infrastructure that has no ties with https://opencollective.com at all. Something similar to a package on https://yunohost.org/ or https://debian.org maybe? Or a Docker image that I could run to get started with my own opencollective instance?

Thanks for your quick reply :-)

**Comment by xdamman** [comment]
Ah gotcha, well, it's technically possible but to be honest we haven't put the time and effort to document this process. Maybe you can help?

@marcogbarcellos just recently went through the process of installing open collective on his machine.

**Comment by dachary** [comment]
> Maybe you can help?

I would love to. From experience going from **this works for me** to **this works for you** is a big undertaking. But you have to start somewhere and I'm game :-) Where do you advise me to begin?

**Comment by xdamman** [comment]
> From experience going from this works for me to this works for you is a big undertaking. 

Absolutely.

This would be a place to start: 
https://github.com/opencollective/opencollective-api

**Comment by dachary** [comment]
<pre>
$ openstack --quiet server create --image 'Debian 9' --flavor 's1-2' --key-name loic --wait opencollective
$ ssh debian@54.37.79.16 # opencollective
$ sudo apt-get update
$ sudo apt-get install -y emacs25-nox tmux git curl
$ curl -fsSL get.docker.com | bash
$ sudo usermod -aG docker debian
$ mkdir -p ~/src/github.com/opencollective
$ cd ~/src/github.com/opencollective
$ git clone https://github.com/opencollective/opencollective-api
$ git clone https://github.com/opencollective/frontend
$ sudo curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
$ sudo chmod +x /usr/local/bin/docker-compose
$ cd opencollective-api/
$ docker-compose -f docker/docker-compose.yml up --build
</pre>

It stops after a while with the following error:
<pre>
postgres_1  | LOG:  autovacuum launcher started
postgres_1  | FATAL:  role "root" does not exist
test_1      | postgres:5432 - accepting connections
test_1      | Run application command: npm run test
postgres_1  | FATAL:  role "root" does not exist
api_1       | postgres:5432 - accepting connections
api_1       | Run application command: npm run docker:dev
api_1       | 
api_1       | > opencollective-api@2.0.189 predocker:dev /usr/src/api
api_1       | > npm install && npm run db:setup && babel-node ./scripts/db_restore.js opencollective_dvl
api_1       | 
test_1      | 
test_1      | > opencollective-api@2.0.189 pretest /usr/src/api
test_1      | > npm run hint
test_1      | 
test_1      | 
test_1      | > opencollective-api@2.0.189 hint /usr/src/api
test_1      | > eslint '**/*.js' --quiet
test_1      | 
test_1      | sh: 1: eslint: not found
test_1      | npm ERR! file sh
test_1      | npm ERR! code ELIFECYCLE
test_1      | npm ERR! errno ENOENT
test_1      | npm ERR! syscall spawn
test_1      | npm ERR! opencollective-api@2.0.189 hint: `eslint '**/*.js' --quiet`
test_1      | npm ERR! spawn ENOENT
test_1      | npm ERR! 
test_1      | npm ERR! Failed at the opencollective-api@2.0.189 hint script.
test_1      | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
test_1      | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
test_1      | 
test_1      | npm ERR! A complete log of this run can be found in:
test_1      | npm ERR!     /root/.npm/_logs/2018-07-27T20_52_53_382Z-debug.log
test_1      | npm ERR! code ELIFECYCLE
test_1      | npm ERR! errno 1
test_1      | npm ERR! opencollective-api@2.0.189 pretest: `npm run hint`
test_1      | npm ERR! Exit status 1
test_1      | npm ERR! 
test_1      | npm ERR! Failed at the opencollective-api@2.0.189 pretest script.
test_1      | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
test_1      | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
test_1      | 
test_1      | npm ERR! A complete log of this run can be found in:
test_1      | npm ERR!     /root/.npm/_logs/2018-07-27T20_52_53_448Z-debug.log
docker_test_1 exited with code 1
</pre>

Any idea how to fix this?

**Comment by dachary** [comment]
Hum, it did not stop but hang for about five minutes. It keeps going afterward, non fatal error it seems.

**Comment by dachary** [comment]
It completed with
<pre>
...
frontend_1  | added 2333 packages from 1418 contributors and audited 48564 packages in 304.043s
frontend_1  | found 14 vulnerabilities (2 low, 8 moderate, 4 high)
frontend_1  |   run `npm audit fix` to fix them, or `npm audit` for details
frontend_1  | 
frontend_1  | > opencollective-frontend@2.2.0 dev /usr/src/frontend
frontend_1  | > babel-node src/server
frontend_1  | 
frontend_1  | info: loading languages ["en","es","fr","ja"] {"0":"en","1":"es","2":"fr","3":"ja","meta":[]}
frontend_1  | > Using external babel configuration
frontend_1  | > Location: "/usr/src/frontend/.babelrc"
frontend_1  |  DONE  Compiled successfully in 3452ms8:57:52 PM
frontend_1  | 
frontend_1  | info: Ready on http://localhost:3000 in docker environment
</pre>
And when loading localhost:13000 it displayed the following
![err](https://user-images.githubusercontent.com/433594/43346426-5b9f516e-91f1-11e8-974a-ef8e8820cec2.png)
and the logs show
<pre>
frontend_1  | > Building page: /home
frontend_1  |  DONE  Compiled successfully in 11850ms8:59:54 PM
frontend_1  | 
frontend_1  |  WAIT  Compiling...8:59:57 PM
frontend_1  | 
frontend_1  |  DONE  Compiled successfully in 938ms8:59:58 PM
frontend_1  | 
api_1       | >>> slow request 1223ms home query: query home {
api_1       |   transactions(limit: 30)
api_1       | >>> variables:  {}
api_1       | POST /graphql?api_key=dvl-1510egmf4a23d80342403fb599qd 200 1299.196 ms - 28650
frontend_1  | { TypeError: Cannot read property 'collectives' of undefined
frontend_1  |     at HomePage.render (src/pages/home.js:153:0)
frontend_1  |     at processChild (/usr/src/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2204:18)
frontend_1  |     at resolve (/usr/src/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2061:5)
frontend_1  |     at ReactDOMServerRenderer.render (/usr/src/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2380:22)
frontend_1  |     at ReactDOMServerRenderer.read (/usr/src/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2354:19)
frontend_1  |     at renderToString (/usr/src/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2726:25)
frontend_1  |     at renderPage (/usr/src/frontend/node_modules/next/dist/server/render.js:275:26)
frontend_1  |     at Function.getInitialProps (/usr/src/frontend/node_modules/next/dist/server/document.js:67:25)
frontend_1  |     at Function._callee$ (src/pages/_document.js:11:0)
frontend_1  |     at tryCatch (/usr/src/frontend/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
frontend_1  |     at Generator.invoke [as _invoke] (/usr/src/frontend/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:296:22)
frontend_1  |     at Generator.prototype.(anonymous function) [as next] (/usr/src/frontend/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
frontend_1  |     at step (/usr/src/frontend/src/.next/server/bundles/pages/_document.js:139:213)
frontend_1  |     at _next (/usr/src/frontend/src/.next/server/bundles/pages/_document.js:139:409)
frontend_1  |     at /usr/src/frontend/src/.next/server/bundles/pages/_document.js:139:477
frontend_1  |     at new Promise (/usr/src/frontend/node_modules/core-js/modules/es6.promise.js:177:7) sourceMapsApplied: true }
frontend_1  | info: GET / 500 16820ms
frontend_1  | info: GET /static/fonts/montserrat/montserrat-light-webfont.woff2 200 6ms
frontend_1  | info: GET /static/fonts/inter-ui/Inter-UI-Regular.woff2 200 38ms
frontend_1  | info: GET /static/fonts/montserrat/lato-regular.ttf 200 37ms
frontend_1  | info: GET /src/pages/home.js.map 404 111ms
frontend_1  | info: GET /usr/src/frontend/src/.next/server/bundles/pages/_document.js.map 404 115ms
frontend_1  | info: GET /src/pages/_document.js.map 404 118ms
frontend_1  | info: GET /usr/src/frontend/src/.next/server/bundles/pages/_document.js.map 404 5ms
frontend_1  | info: GET /favicon.ico 200 5ms
</pre>
Any idea how to fix this?

**Comment by xdamman** [comment]
there is a message in the readme of https://github.com/opencollective/opencollective-api that says that currently the homepage is broken with that setup because of missing data in the seed database.
Try to load http://localhost:13000/apex for example.

For the root error above, no idea how to fix it. I didn't create the docker setup. @clarete did. Maybe @znarf can help here.

**Comment by znarf** [comment]
@xdamman The message in the Readme is not valid anymore because the homepage is now powered by the 'frontend' codebase not the legacy 'website'. 

However, the  homepage is effectively currently broken "out of the box", due to missing entries in the database (chapters collective). This is the problem @dachary is currently facing.

**Comment by xdamman** [comment]
Thanks for the update. Any idea about the other issue above where it hang in the docker setup for 5mn?

**Comment by znarf** [comment]
The home is now fixed. I will close the issue.

To answer the question: "is it possible to self-host  opencollective?" yes, but it's not as simple as what we want it to be.
