### ISSUE TITLE
Bring wiki pages on the website

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1194]
There are a few pages on the wiki that would be good to bring to the website as markdown files (exactly like we did for https://backyourstack.com/faq)

/becoming-a-host
https://github.com/opencollective/opencollective/wiki/Becoming-an-Open-Collective-Host

/faq
(I'd convert the existing FAQ to markdown)

/about
(same)

@cuiki can you design such generic page with the new style? Just text with title, subtitles, sub subtitles, paragraphs, links, bullet points.

Other pages that I'm missing?

**Comment by cuiki** [comment]
On the list now. Also, I found this and thought that maybe it would work for something like this.

www.gitbook.com

**Comment by cuiki** [comment]
Here is the design for the generic pages for the OC website. The link to the InVision mock is the styles template and in the included screenshots I show how these styles are applied to the **About** page.

**InVision** — https://invis.io/UDMY05M9MH6#/311677420_Generic_-_Desktop

**— Styles**
![generic desktop](https://user-images.githubusercontent.com/981188/43436267-437dc2a0-9449-11e8-82b1-64f74e92a68a.png)


**— About Page**
![about desktop](https://user-images.githubusercontent.com/981188/43436273-4bc384ae-9449-11e8-8b18-60f7a5a69807.png)
