### ISSUE TITLE
Clarify software license?

### ISSUE THREAD

**Issue by downeym** [opencollective/opencollective#1195]
Sorry to not follow the standard template but this is more of a question/request.

Is it possible to clarify the licensing of the software? In `TOS.md` I see a reference to the MIT license, but the same document also describes Terms of Service that would not be relevant if I were copying and/or modifying the software for my own use. 

I presume `TOS.md` is really more of an internally-used by the software to display said terms within the website itself, as part of the service offered by the software's deployer, and not really related to use of the software ... but then again the language doesn't really match up with the terms at https://opencollective.com/tos either. Any clarification available there?

Any chance to move the software license bit to the traditional `LICENSE.md` or equivalent, e.g. provided at https://help.github.com/articles/licensing-a-repository/ ... and perhaps move the TOS file somewhere more out-of-the-way or otherwise explain that it doesn't apply to use of the software itself?

Thanks for your consideration! 😄

**Comment by znarf** [comment]
The `TOS.md` is useless and should be removed.

Our code is usually MIT licensed but this repo is not about code, for that reason we have not defined a license for it.
