### ISSUE TITLE
Fix link in new backer email for collective of type event

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1198]
When a new person joins a collective as a backer, the "new backer" notification email is sent to the admins.

The link to the collective is wrong as it doesn't include the path of the collective but just the slug of the event (without the parent collective slug + /events/).

**Comment by znarf** [comment]
@xdamman is that still valid?

**Comment by Betree** [comment]
@xdamman could you provide more info? From what I see in `templates/emails/collective.member.created.hbs` the "new backer" email already use `collectivePath`:

https://github.com/opencollective/opencollective-api/blob/61791ecfb7892322578e1d4ab6abdb84a5cc7f9c/templates/emails/collective.member.created.hbs#L15

![image](https://user-images.githubusercontent.com/1556356/62293829-ba334a00-b469-11e9-8025-dfcc0fa4b8dc.png)

**Comment by xdamman** [comment]
Then maybe it has been fixed since then. It’s a year old issue.
