### ISSUE TITLE
Need a small (?) icon

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1203]
Would love to add some help points throughout the interface.

For that purpose, I need a (?) round icon in PNG/SVG one dark and one light version (for light and dark background).

Thanks!

**Comment by cuiki** [comment]
Hi @xdamman , I included these in one of the iterations I did for the collective page. You can find them here: https://invis.io/UDMY05M9MH6#/312528212_collective_Page_-_Default

I left a comment of the mockups so you can extract them. Just adapted the one for dark bg's.

**Comment by xdamman** [comment]
Perfect.
What's the font face? (It doesn't say in Invision)

**Comment by cuiki** [comment]
Download SVG's here: https://tafka.d.pr/qdAjoJ

**Comment by xdamman** [comment]
Do you already ave somewhere a view of the hover state?
Not sure what color I should use for the background of the bubble.
That's what I have atm: ![](https://d.pr/free/i/qLPscR+)

**Comment by cuiki** [comment]
Yeah. In the same InVision project there are two tooltip designs but this is the simplest one:
https://invis.io/9MNCHLIEYWD

I can do one for a dark background though this should work. You can see them in context in the mockup.

**Comment by xdamman** [comment]
When I click on the code view, this is what I see: ![](
https://d.pr/free/i/jBA0jn+)

**Comment by cuiki** [comment]
I have no idea why you see that. The only thing I can think of is that maybe you're looking into these mocks without being signed into InVision. You have access to the prototype named "OC — Web Platform". There shouldn't be any issues.

https://tafka.d.pr/vHC3gj

`.base {
	height: 119px;
	width: 200px;
	border: 1px solid rgba(18,19,20,0.12);
	border-radius: 8px;
	background-color: #FFFFFF;
	box-shadow: 0 8px 16px 0 rgba(12,16,20,0.12);
}`

That's the css for the tooltip container.

**Comment by cuiki** [comment]
@xdamman , did you finally got this info and asset correctly? Can we close this issue?

**Comment by znarf** [comment]
Closed because of low activity. @xdamman
