### ISSUE TITLE
Link to report issue broken in the footer

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1204]
For some really weird reason, the link to report an issue in the footer is 
https://github.com/opencollective/opencollectives/issues instead of 
https://github.com/opencollective/opencollective/issues (notice the plural collective**s**) even though it is written properly in the code: https://github.com/opencollective/frontend/blob/master/src/components/Footer.js#L64

**Comment by znarf** [comment]
Fixed in https://github.com/opencollective/frontend/pull/642
