### ISSUE TITLE
Inconsistency between `Collective.HostCollectiveId` and `Members.host`

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1207]
12 collectives have a different `Collective.HostCollectiveId` than the one referenced in the `Members` table under the role `HOST`.

```sql
SELECT
  max(c.slug) as collective,
  max(hc.slug) as host, max(hc.currency) as "host.currency",
  max(h2c.slug) as "members.host", max(h2c.currency) as "members.host.currency",
  max(c."updatedAt") as "collective.updatedAt",
  max(m."createdAt") as "members.createdAt",
  min(t."createdAt") as "firstTransaction",
  max(t."createdAt") as "lastTransaction"
FROM "Collectives" c
LEFT JOIN "Members" m ON c.id = m."CollectiveId" AND m.role='HOST'
LEFT JOIN "Collectives" hc on hc.id = c."HostCollectiveId"
LEFT JOIN "Collectives" h2c on h2c.id = m."MemberCollectiveId"
LEFT JOIN "Transactions" t ON t."CollectiveId" = c.id
WHERE m."MemberCollectiveId" != c."HostCollectiveId"
  AND c."HostCollectiveId" IS NOT NULL
  AND c.type='COLLECTIVE'
  AND c."deletedAt" IS NULL
  AND c."isActive" IS TRUE
GROUP by c.id
ORDER BY collective ASC
```

![](https://d.pr/free/i/YsaA8c+)

This is probably due to manually changing the host of a collective and forgetting to do it in either the `Collective` table or the `Members` table.

The effective host being used right now is the host define in `Collective.HostCollectiveId` (`host` column above). The `HOST` member is what is being used when computing the monthly report to hosts.
That means that all the reports for the host listed above (in either column) need to be recomputed starting from the date of the first transaction for each of those collectives. Quite painful.

Anyway, for each of those collectives, we now need to confirm what is the host that they should be using.
@piamancini can you help complete the following table:

collective (slug) | collective.host (slug) | Member.HOST (slug) | Confirmed Host (slug)
-------------- | --------- | --------------- | ----------------
co-built | fka | opencollective-host | ?
jointhecosmos | foundation | opencollective-host | ?
mongoose | opensourcecollective | opencollective-host | ?
opencollective-oss | opensourcecollective | foundation | ?
opencoop | opencooplca | opencoop | ?
operationcodepdx | operationcode | opencollective-host | ?
react-native-firebase | invertase | opensourcecollective | ?
standardmeta | standardmeta-org | opencollective-host | ?
tenancy | europe | opensourcecollective | ?
torontojs | torontojs-host | meetups | ?
userfrosting | userfrosting-project | opensourcecollective | ?
weco | finance6 | weco | ?

**Comment by xdamman** [comment]
This query will
- delete all the existing rows in the `Members` table for the `HOST` role that don't match the `Collective.HostCollectiveId`
- insert new rows in the `Members` table to match the `Collective.HostCollectiveId`

```sql
BEGIN;
with "collectives" as (SELECT
  max(c.id) as "CollectiveId", max(c."HostCollectiveId") as "HostCollectiveId",
  max(m."MemberCollectiveId") as "MemberCollectiveId", max(m.role) as role
FROM "Collectives" c
LEFT JOIN "Members" m ON c.id = m."CollectiveId" AND m.role='HOST'
LEFT JOIN "Collectives" hc on hc.id = c."HostCollectiveId"
LEFT JOIN "Collectives" h2c on h2c.id = m."MemberCollectiveId"
WHERE m."MemberCollectiveId" != c."HostCollectiveId"
  AND c."HostCollectiveId" IS NOT NULL
  AND c.type='COLLECTIVE'
  AND c."deletedAt" IS NULL
  AND c."isActive" IS TRUE
GROUP by c.id), "updatedMembers" as (
UPDATE "Members" SET "deletedAt" = '2018-08-05' WHERE role='HOST' AND "CollectiveId" IN (SELECT "CollectiveId" FROM "collectives")
)
INSERT INTO "Members" ("CollectiveId", "MemberCollectiveId", "CreatedByUserId", "role", "createdAt")
SELECT "CollectiveId", "HostCollectiveId", 2 as "CreatedByUserId", 'HOST' as "role", '2018-08-05' as "createdAt" FROM "collectives";
COMMIT;
```

This will fix the problem above assuming the `Collective.HostCollectiveId` is the source of truth (still needs to be confirmed)

**Comment by piamancini** [comment]
Looking now. In the future is probably useful to have a role defined in only one place in the ledger.

**Comment by piamancini** [comment]
collective (slug) | collective.host (slug) | Member.HOST (slug) | Confirmed Host (slug)
-------------- | --------- | --------------- | ----------------
co-built | fka | opencollective-host | fka
jointhecosmos | foundation | opencollective-host | foundation
mongoose | opensourcecollective | opencollective-host | opensourcecollective
opencollective-oss | opensourcecollective | foundation | opensourcecollective
opencoop | opencooplca | opencoop | opencooplca
operationcodepdx | operationcode | opencollective-host | operationcode
react-native-firebase | invertase | opensourcecollective | invertase
standardmeta | standardmeta-org | opencollective-host | standardmeta-org
tenancy | europe | opensourcecollective | europe
torontojs | torontojs-host | meetups | torontojs-host
userfrosting | userfrosting-project | opensourcecollective | userfrosting-projec
weco | finance6 | weco | finance6 (weco is the collective)
