### ISSUE TITLE
Wrong profile ?

### ISSUE THREAD

**Issue by Carodem** [opencollective/opencollective#1208]
Hello ! 

I am having troubles sining up to my profile on Brussels Together. When I enter my email address to receive a link to connect and click on it, i appear under "anonymous497".
Here is the URL that appears when i click on the link received by email : https://opencollective.com/huneeds

Here is the URL of the "anonymous497" profile : https://opencollective.com/anonymous497#

+ i am administrator of 2 pages : HuNeeds and 400Toits but through this anonymous 497 profile, i only appear on 400Toits

![capture_d ecran_2018-08-06_a_11_51_10](https://user-images.githubusercontent.com/36923849/43710148-1cf86d44-996f-11e8-9c7c-749a2fea8837.png)

Thank you !

**Comment by piamancini** [comment]
Hi @Carodem You are an admin of huneeds with this profile https://opencollective.com/caroline-de-montjoye# that you created with your hotmail email address.

**Comment by Carodem** [comment]
Hi,

Thank you for your email.

I tried to log in with my email address but it says this address does not exist…
+ when i click on your link below, i arrive on my profile but that still says anonymous 497….

[cid:AE4FC1BC-1342-4223-ACBD-BAA629CCBCE2@lan]


Thanks !


Caroline

Le 7 août 2018 à 20:38, Pia Mancini <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi @Carodem<https://github.com/Carodem> You are an admin of huneeds with this profile https://opencollective.com/caroline-de-montjoye# that you created with your hotmail email address.

**Comment by piamancini** [comment]
Hi @Carodem hmm can you try logging out? 
The address I see for the profile is carolinedemontjoye{at}hotmail.com Is there a typo?

**Comment by Carodem** [comment]
Hello,

Sorry for not answering earlier !
Everything works perfectly now, thank you !

Just one last detail : I do not know how to delete an account (the « anonymous » one), and i see it is still shown as administrator of the 400Toits page : https://opencollective.com/400-toits-daken#team


[cid:92D5175D-0C86-4BEF-8010-265576B3CF77@home]



Thanks !!


Caroline de Montjoye

Le 13 août 2018 à 18:38, Pia Mancini <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi @Carodem<https://github.com/Carodem> hmm can you try logging out?
The address I see for the profile is carolinedemontjoye{at}hotmail.com<http://hotmail.com> Is there a typo?

**Comment by piamancini** [comment]
fixed.
