### ISSUE TITLE
Why users make donations with the wrong profile?

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1210]
We constantly have users making a donation with their personal  profile instead of their organizational one. I think part of the reason is that when you click on a tier to donate you land with an anchor direcly in the payment method section of the order: 

<img width="1276" alt="screen shot 2018-08-06 at 1 21 18 pm" src="https://user-images.githubusercontent.com/3671070/43731266-f4ef4130-997b-11e8-9f75-1233f4440d3f.png">

The anchor should be at the top of the page instead so the first think you see is the personal details 

<img width="1277" alt="screen shot 2018-08-06 at 1 23 21 pm" src="https://user-images.githubusercontent.com/3671070/43731277-fbe9110a-997b-11e8-9005-2681981116e9.png">

**Comment by piamancini** [comment]
@znarf This is happening again, at least in events. 
Click on Become a Sponsor here https://opencollective.com/sustainoss/events/sustainuk-2018-442ev
The anchor is at the bottom of the page instead of the 'contribute as'

**Comment by piamancini** [comment]
re-opening issue

**Comment by znarf** [comment]
@piamancini ok, let me know if there is any other cases to cover.
