### ISSUE TITLE
Add stroke to profile header text

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1213]
Currently the white text does not work with light backgrounds. If it were white text with a black stroke, it should work on any background.

<img width="739" alt="screen shot 2018-08-07 at 11 30 22 am" src="https://user-images.githubusercontent.com/5498878/43745935-709f0900-9a35-11e8-8871-ed1fb4798eaa.png">

**Comment by xdamman** [comment]
This can be done with
```css
text-shadow: 1px 0 0 #000, 0 -1px 0 #000, 0 1px 0 #000, -1px 0 0 #000;
```

@cuiki what do you think?

**Comment by xdamman** [comment]
This is the way it would look with a 3px spread shadow:
![](https://d.pr/free/i/cpgxYv+)

And without a spread:
![](https://d.pr/free/i/aDo6dW+)

**Comment by alannallama** [comment]
Looks good! That's much better.
