### ISSUE TITLE
CHSF has a null host fee % in their backers transactions

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1216]
<img width="1233" alt="screen shot 2018-08-07 at 11 01 06 am" src="https://user-images.githubusercontent.com/3671070/43784123-5fbe3614-9a31-11e8-98d7-baa689189093.png">

**Comment by xdamman** [comment]
Fixed.

Btw, is it normal that they are still hosted by opencollective-host?
Weren't they supposed to move to the foundation?

**Comment by piamancini** [comment]
PS: can I close this?
