### ISSUE TITLE
include how to cancel a subscription in the faq

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1219]

**Comment by xdamman** [comment]
I've started moving the FAQ to our wiki to make it easier to edit it.
https://github.com/opencollective/opencollective/wiki/FAQ

The goal is to move those pages on the new frontend.

**Comment by xdamman** [comment]
I've also started breaking down the FAQ per target audience. 
Here is the one dedicated for backers (individuals and organizations): https://github.com/opencollective/opencollective/wiki/FAQ-for-backers

**Comment by piamancini** [comment]
ok - closing this then.
