### ISSUE TITLE
Show contributors on the collective page of open source projects

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#122]
![mobile](https://cloud.githubusercontent.com/assets/18429104/15032010/efd1b094-1222-11e6-9091-07ecd9adceec.png)
![mobile-taped](https://cloud.githubusercontent.com/assets/18429104/15032014/f45e71a6-1222-11e6-8616-6726b7ce6219.png)
![mobile-tapped-2](https://cloud.githubusercontent.com/assets/18429104/15032018/f771e0b2-1222-11e6-8422-0ef0c7e4cb41.png)

**Comment by xdamman** [comment]
The data is the `group.data`. Something that @boneskull did.

**Comment by carlosascari** [comment]
@xdamman I have a `pending-collecitve` a scaffold with a component that displayes the contributor list
https://github.com/OpenCollective/opencollective-website/blob/pending-collective/frontend/src/components/public_group/ContributorList.js

We could merge the branch (I'll just remove a line that force the pending-collecitve to render)

**Comment by xdamman** [comment]
We should separate this from the concept of pending collective because we don't want to be blocked by the implementation of pending commitments etc. before showing the list of contributors.

**Comment by carlosascari** [comment]
It is separate, it is its own component, I am just saying that it has already been built, and its inside the `pending-collecitve` branch. The pending-collective view will NOT render until `group.settings.pending` is true, so I think its safe to merge it and just reuse the already existing component, instead of extracting it for this issue.

https://github.com/OpenCollective/opencollective-website/pull/286

**Comment by carlosascari** [comment]
@boneskull How can I see the `group.data` mentioned above? Could you show me the code?

**Comment by boneskull** [comment]
`group.data` is just a JSON-type db field. `scripts/update-contributions.js` puts data there. What are you needing to know, exactly?

**Comment by carlosascari** [comment]
@boneskull @xdamman 
I need the list of contributors for the open source project. The items in the list should include:
`name`, `avatar`, `commits`, `additions` & `deletions`

Here is an example with mocked data that is fed to the `ContributorList` component
https://github.com/OpenCollective/opencollective-website/pull/289/files#diff-922bbe5781cbfbe31e15ca1525fdea6fR135

**Comment by boneskull** [comment]
So we want to show *lines of code added* and *lines of code removed* on the site?  I'd suggest that data is less meaningful than even "number of commits", but just my 2 cents.

**Comment by carlosascari** [comment]
@boneskull You are right, the reason I'm asking for this is to display it when a user hovers over a contributor item, heres the design:
https://github.com/OpenCollective/OpenCollective/issues/33#issuecomment-217232132

**Comment by xdamman** [comment]
I agree that it doesn't make much sense to show those numbers. Just the number of "contributions" should be displayed. And ideally also the start and end date of those contributions.
