### ISSUE TITLE
Send email W9 bot to host

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1220]
As reported by @piamancini  https://github.com/opencollective/opencollective/issues/1200#issuecomment-411886066, we shouldn't receive the W9 on behalf of other USD based hosts.

A quick fix for this is to customize the comment to use the email of the host.

Now that I've added templating to it (see https://github.com/opencollective/opencollective-api/pull/1403), it should be fairly trivial.
We can add in the settings of the host `settings.w9.email` and ask people to send to that email address.

If there is no email set, we shouldn't run the W9 bot.

(a better version could send an email to the admins of the host to let them know that this expense is about to make that user pass the threshold for W9 and that they should ask the submitter for such form, while also letting them know that if they want we can automatically add a comment in such situations if they send us the email address where they would want to receive this)

**Comment by piamancini** [comment]
I think it's a nice feature to offer other hosts, super useful. Yes, we need to ask them and an email address to send. We don't have so many, it's an easy mailchimp campaign too if you want me to set that up.

**Comment by marcogbarcellos** [comment]
Can we have a list with all of our hosts and their respective emails(perhaps the same email for all of them?) ?

**Comment by znarf** [comment]
@marcogbarcellos Was that taken care of?

**Comment by marcogbarcellos** [comment]
I still need the hosts' emails so I can update their `settings.w9.email` and do the change. I can try figuring out their email through some queries and update the list here to have an Ok from pia and xavier. Other than the list, it doesn't seem complicate so i'll mark it with a `Bug fix friday` label as it may be a good pick to me!

**Comment by alanna** [comment]
This will be made obsolete by the new tax form system. We will be shutting down tax bot. No other host uses it as far as I know.
