### ISSUE TITLE
Expense Flow → Clarify privacy of attachments when creating expense (EPIC #1326)

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1222]
The system does not make it clear that attachments will not be visible publicly, causing users to be concerned about privacy (since their names and addresses are on invoices). [example](https://github.com/opencollective/opencollective/issues/1221).

**Comment by alannallama** [comment]
We still need this

**Comment by alanna** [comment]
We get support requests for this a lot. People think their personal info on attachments will be public. This stops people from submitting expenses because they don't understand that it's private.

**Comment by piamancini** [comment]
this needs to be open until we release expense flow.

**Comment by Betree** [comment]
I think this is resolved by the new expense flow?
