### ISSUE TITLE
Approvals dashboard fields and sorting

### ISSUE THREAD

**Issue by KishenG** [opencollective/opencollective#1224]
Currently, dashboard entries are sorted by original transaction date. If a transaction is uploaded at a later date, there is a risk that it might get missed in approvals, as it will go far down the queue.

Suggest that transactions should sort by upload date, then transaction date of necessary.

**Comment by xdamman** [comment]
Good idea.

As a work around for now you can filter expenses that are approved and ready to be paid (or by pending expenses, though it should be the responsibility of the host to do the first approval)
