### ISSUE TITLE
Timezone error in event  

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1225]
URL: https://opencollective.com/techforgoodnz
From user:
> I have an upcoming event promoted with Tech for Good New Zealand. The event is Monday 27th August at 6pm. 
> 
> The opencollective desktop is showing correctly. 
> The mobile site is showing 1 day later - Tuesday 28th at 6pm
> And when you go to purchase a ticket, it is Tuesday 28th at 5pm. 
> 
> There seems to be some error in time zones etc which is now confusing our ticket sales and we are getting enquiries.  I have attached 3 screenshots. 

![screen shot 2018-08-12 at 11 29 01 pm](https://user-images.githubusercontent.com/3671070/44044703-779b6c44-9ef4-11e8-9f71-677a39ea0146.png)
![img_0507](https://user-images.githubusercontent.com/3671070/44044708-7907d392-9ef4-11e8-927d-d756f00b66f6.PNG)
![img_0506](https://user-images.githubusercontent.com/3671070/44044718-7c625b0c-9ef4-11e8-80f6-11609c842133.PNG)

**Comment by znarf** [comment]
Looks like we can do better on timezone handling. I nailed this problem and fixed it:
https://github.com/opencollective/frontend/commit/21edda0f033e81812a7d40bd2f7b8a761e89fcd3
