### ISSUE TITLE
put link to ToS below the 'Connect Github' button in Github Flow 

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#123]
Many repos don't get to the ToS because they are at the end of the flow. We should add them below the button so everyone sees them. add: Please read or Terms of Service [here](https://docs.google.com/document/d/1-hajYd7coL05z2LTCOKXTYzXqNp40kPuw0z66kEIY5Y/pub)

**Comment by carlosascari** [comment]
Fix is live https://opencollective.com/opensource/apply
