### ISSUE TITLE
Images not resized in email to backers

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1230]
I'm not sure if this is an open collective thing, or if it depends on how the person composes the email. But if possible, emails should have a template or something that prevents this.

<img width="1073" alt="screen shot 2018-08-16 at 11 00 23 am" src="https://user-images.githubusercontent.com/5498878/44177855-ced8de00-a143-11e8-9038-80c0c53545fb.png">

**Comment by alannallama** [comment]
Another example today:

<img width="1077" alt="screen shot 2018-08-21 at 6 00 30 pm" src="https://user-images.githubusercontent.com/5498878/44383246-2d4ef380-a56c-11e8-82cf-fd2dc0a8eb37.png">

**Comment by xdamman** [comment]
Fixed in https://github.com/opencollective/opencollective-api/pull/1414
