### ISSUE TITLE
Monthly meetup creation issue: "Slug is already taken"

### ISSUE THREAD

**Issue by jancborchardt** [opencollective/opencollective#1231]
I just created an event at https://opencollective.com/opensourcediversity/events/open-source-diversity-berlin-monthly-meetup-19378ev

Now I wanted to add more of the monthly events. I choose to base it on the other event as template, but then when saving I get the error:
```
The slug open-source-diversity-berlin-monthly-meetup is already taken. Please use another name for your event.
```

I would assume that since the other url has this `-19378ev` appended, the new event would just get another random string appended to prevent the collisions. I also see no way to manually change the "slug" (which is a very technical term too, maybe better "link"?), without changing the name of the event itself.

**Comment by maddhruv** [comment]
@Betree @znarf this is happening even if the collective doesn't have an event with the name already

```
Collective A
    No Event
Collective A -> Create new Event (name: "Event One")
    It will throw an error that the `event-slug`  is already taken, which is meaningfully not taken
	Even if it generates a url for the event as in format - `{collective}/events/{event_name}` which is dependent and specific to that of the collective
```

The events (event names) should be collective specifics if they are collective scoped

**Comment by znarf** [comment]
Should be solved with https://github.com/opencollective/opencollective-api/pull/2704

**Comment by jancborchardt** [comment]
Thanks a lot @znarf! We don’t have regular meetups at the moment anymore, but will check when we do :)
