### ISSUE TITLE
threadless is not showing up in the list of organization to add funds 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1234]
this is annonying since I need to manually change the contributions from OSC to threadless every time I add funds to them

**Comment by xdamman** [comment]
On https://opencollective.com/opensourcecollective/dashboard?

You mean add funds **from** them?

**Comment by piamancini** [comment]
no no when I add funds to a collective, threadless never shows up as an organization in the list

**Comment by xdamman** [comment]
Fixed in https://github.com/opencollective/opencollective/issues/1242
