### ISSUE TITLE
Need Help: svg is not update to date

### ISSUE THREAD

**Issue by clarkdo** [opencollective/opencollective#1235]
URL: https://opencollective.com/nuxtjs/contributors.svg
Expected result: Contributors and their avatars can be same as [GitHub](ttps://github.com/nuxt/nuxt.js/graphs/contributors)
Browser: Chrome 70

So is there any way to sync contributors list or avatars from GitHub in OpenCollective ?

**Comment by znarf** [comment]
@clarkdo it should be up to date now. However, we're still looking at the root issue.

**Comment by znarf** [comment]
@clarkdo Sorry, mistaken your issue with another one. Will look at it.

**Comment by znarf** [comment]
Related: https://github.com/opencollective/opencollective/issues/1295

@clarkdo is it better now?

**Comment by clarkdo** [comment]
@znarf Thank you for the reply 😄 , but it seemed still displaying the old svg.

**Comment by znarf** [comment]
Fixed.

**Comment by clarkdo** [comment]
@znarf It works, thank you so much.
