### ISSUE TITLE
OC monthly report issues

### ISSUE THREAD

**Issue by Kilheure** [opencollective/opencollective#1239]
As a host (OC UK), I notice some issues with the monthly report that ensure the rec between the collectives fundings and expenses

**1) Some funding/income have negative hostfee, platform fee**
Other don't, so I don't understand the logic here. 
example ID: 59194; 65288. Income of 200 GBP but former has positive fee, later negative. 
**2) missing transactions**
For collective Agreelist, sum of monthly report (up to July 2018 included) indicates 9 expenses for a gross amount of 692.47GBP, although bank account statement recognises 16 expenses for a gross amount of 1110 GBP. The latter matches the collective webpage

I just did the rec for 1 collective. Other might be impacted too. 

Required improvement : 
**1) Ability to download a date range of OC transaction**
Host account do not end up in the same date (ie from Jan to Dec), so we should be able to download report for the data range on which the account must be submitted. 
Also, currently we only receive monthly report, having a yearly one that matches accounting can be very useful

**2) having a flag Income/ expense to identify the side of the transaction.**
It will simplify the rec by filtering on it, instead of positive or negative amount

**3) format field createdAt as date (DD/MM/YYYY)**
This field can't be used for filtering or anything as the format is useless. Either create a new field for the valid date format, or change this one so filter can apply. 
Another field might be required for the time of the transaction. Standard date field is really needed here

Thanks in advance for looking at improving the report
I really require the above change, so to simplify the accounting
[201808 OC Report Rec.xlsx](https://github.com/opencollective/opencollective/files/2306955/201808.OC.Report.Rec.xlsx)

**Comment by xdamman** [comment]
- [ ] Positive host / platform fees -> negative: done!
- Missing transactions: they are in the DB. Need to double check export.

TODO
- [ ] `createdAt` should be in the format `YYYY-MM-DD`
- [ ] add `DEBIT` or `CREDIT` column
- [ ] download transactions CSV at the host level for any date range

**Comment by Kilheure** [comment]
Not sure why this one is closed as in latest report, there are still missing transaction from 'a Man's world'. 
Furthermore, there is no ability to a date range of OC transaction on OC UI for host
