### ISSUE TITLE
add data in Stripe

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#124]
add OC 'slug' in the data that shows on the stripe dashboard

**Comment by piamancini** [comment]
I put it as high priority since it's blocking wwcode

**Comment by asood123** [comment]
As far as I can tell (https://stripe.com/docs/api#metadata), `description` is not supported for `Subscriptions` on Stripe (which we use for recurring payments). `description` is only supported for `Charges`, which we use for one-time payments. 

For `Subscriptions`, we can use metadata. I added `description` to metadata. 

We already had `description` for `Charges`. I updated it to `OC: [group.slug]`.

I can't get any of these to show up on the dashboard. You have to drill down to see this info. If wwcode knows how to do this, I'm happy to tweak.

https://github.com/OpenCollective/opencollective-api/pull/441
