### ISSUE TITLE
Link to ticket section jumps to location section

### ISSUE THREAD

**Issue by jdorfman** [opencollective/opencollective#1240]
URL: https://opencollective.com/sustainoss/events/sustainuk-2018-442ev#tickets
Logged in as (username or profile URL): https://opencollective.com/jdorfman
Error message if any: n/a
Expected result: To show the [ticket section](https://cl.ly/2h2p2k2y291V) not the Location section
Browser: Chrome

Screencast: https://cl.ly/2p04360o3a0t

**Comment by piamancini** [comment]
cc / @znarf

**Comment by znarf** [comment]
Thank you for the Screencast.

I'm unfortunately not able to reproduce the jump from tickets to location section. Can someone else test the flow?

**Comment by piamancini** [comment]
it's working for me too now @jdorfman

**Comment by jdorfman** [comment]
I tried it in Firefox Nightly and it seems to work. Must be isolated to me. Thanks for checking it out.
