### ISSUE TITLE
Better default background cover image for organizations / hosts

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1241]
Small version for the cards when we show them on https://opencollective.com/hosts but also large version when we click on one of them, e.g. https://opencollective.com/uk

![](https://d.pr/free/i/MmZU8D+)

**Comment by cuiki** [comment]
Hmm I guess the light one wouldn't work unless you can implement font color changing for dark vs light default bgs.

Maybe this can help:
- https://css-tricks.com/reverse-text-color-mix-blend-mode/
- http://thesassway.com/intermediate/dynamically-change-text-color-based-on-its-background-with-sass

**Comment by xdamman** [comment]
Can't do that. Out of scope for now. A good one to grab for external contributors.
