### ISSUE TITLE
AddFunds: Auto complete for selecting the source of money

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1242]
The form that a host can use to add funds to a collective asks you to provide the source of the money or create one (context: the host can receive money on behalf of a collective directly on their bank account, in which case they have to manually allocate those funds to the balance of the right collective).

Right now, the dropdown menu is populated by fetching all the members across all collectives hosted by the host. That list is massive for the open source collective and makes the interface almost unusable. 

![](https://d.pr/free/i/GP7G7D+)

It would be a much better UX to have an auto complete field to automatically search for a previously used sources https://github.com/opencollective/frontend/blob/master/src/components/AddFundsSourcePicker.js

It looks like Downshift by @kentcdodds would be a good candidate for doing this. See this example with Apollo: https://codesandbox.io/s/m5zrvqj85p

Related to #1234

**Comment by xdamman** [comment]
As a quick mitigation, we could only show the list of previous sources of money.
This query returns this:
```sql
SELECT c.slug
FROM "Collectives" c INNER JOIN "Transactions" t ON t."FromCollectiveId" = c.id
WHERE t."PaymentMethodId" = :HostPaymentMethodId
  AND t.type='CREDIT'
  AND t."deletedAt" IS NULL
GROUP BY c.slug
```

**Comment by piamancini** [comment]
What happens with new organizations that we are using as source for the first time?

**Comment by xdamman** [comment]
same as today: you'll have to select "other" and then specify its name / url / email to create one on the fly.

**Comment by xdamman** [comment]
This would be the dropdown with this query for the open source collective:

![](https://d.pr/free/i/Ft9by5+)

**Comment by piamancini** [comment]
@xdamman why is threadless not showing up?

**Comment by xdamman** [comment]
It is showing up but as a user. Not sure why it was created that way. You may want to convert it.
