### ISSUE TITLE
Self serve flows bugs list

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1243]
- [x] When connecting a stripe account, should update the currency of the new hosted collective as well
- [ ] Show stripe connected account when editing organization or user
- [x] After connecting stripe to a newly created organization, make sure we refresh the page
- [x] Title case menu in edit collective

**Comment by piamancini** [comment]
Adding a bug here https://github.com/opencollective/opencollective/issues/1296

**Comment by znarf** [comment]
@xdamman Is "Show stripe connected account when editing organization or user" still a todo?

If so, can you create a separate issue explaining what needs to be done so we can close this one?

**Comment by piamancini** [comment]
This has been done. Closing issue.
