### ISSUE TITLE
adding funds to an organization fails

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1245]
when I go to opencollective.com/trivago and hit add funds I get this error
<img width="1280" alt="screen shot 2018-08-28 at 11 07 00 am" src="https://user-images.githubusercontent.com/3671070/44734931-13a43380-aab9-11e8-89e9-855916ca63a9.png">

**Comment by piamancini** [comment]
adding a high priority because I want to be able to start this subscription before the end of the month

**Comment by marcogbarcellos** [comment]
@piamancini and @xdamman here, PR is open.
