### ISSUE TITLE
feedback collective to collective donations

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1247]
- the dropdown menu has a combination of organizations, collectives and personal a user's personal profile. It would be very helpful to clearly identify what is what. My case is out of the norm clearly, but a better display for everyone can help.  

<img width="449" alt="screen shot 2018-08-28 at 2 17 57 pm" src="https://user-images.githubusercontent.com/3671070/44743772-67227b80-aad1-11e8-8ec1-28e6b5a2245f.png">

- when contributing as a profile other than the personal one, it's confusing that your personal credit cards are showing up in the payment method dropdown menu: 

<img width="930" alt="screen shot 2018-08-28 at 2 35 59 pm" src="https://user-images.githubusercontent.com/3671070/44743825-87ead100-aad1-11e8-915c-1ef1a626c5e1.png">

- in the case of the Open Collective Host (the default host we use for new collectives): it's unclear what the 100k are? If it's the balance of the host, it's not correct since the money belongs to several collectives. It should always be the budget of the collective.  
Same for the other credit cards, not sure what they are: 
<img width="846" alt="screen shot 2018-08-28 at 2 04 48 pm" src="https://user-images.githubusercontent.com/3671070/44743945-d9935b80-aad1-11e8-8240-acd59b1831a4.png">

**Comment by cuiki** [comment]
This gets solved by the new contribution flow:

<img width="615" alt="screen shot 2018-11-21 at 7 12 28 am" src="https://user-images.githubusercontent.com/981188/48843494-d4564d80-ed5c-11e8-9f12-53cc9148e8f9.png">

Should we close this or add a quick fix to it based on the solution provided?
