### ISSUE TITLE
self - serve flow grapql error

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1250]
two users reported this morning that they can't create a collective: 
One is un GBP and the other one in AUD
![image from ios 1](https://user-images.githubusercontent.com/3671070/44791997-f16dec80-ab70-11e8-968f-75ffaf0de9e5.png)

![image 3](https://user-images.githubusercontent.com/3671070/44792408-dea7e780-ab71-11e8-9b21-e98d24240361.png)

**Comment by piamancini** [comment]
It seems like it's not related to currency, another collective reported it, in USD
![error](https://user-images.githubusercontent.com/3671070/44792308-9983b580-ab71-11e8-8a7b-2596921900e7.jpg)

**Comment by xdamman** [comment]
It looks like the API wasn't deployed with the new graphql method.
I've just redeployed it and it should work properly now.
Can you ask them to try again?
It works on staging: ![](https://d.pr/free/i/5JQ8vF+)
btw, something tells me I'm gonna love this collective :-)

**Comment by piamancini** [comment]
closing since issue is solved.
