### ISSUE TITLE
contributors.svg not work

### ISSUE THREAD

**Issue by ShanaMaid** [opencollective/opencollective#1254]
How to create a contributors.svg of my rep?
eg:
https://opencollective.com/yoshino/contributors.svg
![](https://opencollective.com/yoshino/contributors.svg)
it not work

but backers and sponsor svg work 
eg:
![](https://opencollective.com/yoshino/backers/badge.svg)
![](https://opencollective.com/yoshino/sponsors/badge.svg)

**Comment by znarf** [comment]
Similar to: https://github.com/opencollective/opencollective-api/issues/1164

Seems that the script refreshing the contributors daily is not executed. However, when triggered manually it works. And we also know that the daily cronjob is properly triggered.

Maybe something is interrupting the execution of the daily cronjob before the update-contributions is  itself executed.

**Comment by ShanaMaid** [comment]
Thanks，it works now.
