### ISSUE TITLE
bug for sending e-mails

### ISSUE THREAD

**Issue by Leadang** [opencollective/opencollective#1260]
Hello! 

There is a bug for sending e-mails in the events page. A friend of mine tried to send several e-mails through her event, but it failed ->>

www.opencollective.com/paris 
URL: https://opencollective.com/mae-trips-/events/wei-2018-18757ev

[capture d ecran 2018-09-01 a 16 47 49](https://user-images.githubusercontent.com/38157592/44956831-4f306a80-aeca-11e8-836e-76f1f6aa0ad6.png)

Thank you!

**Comment by znarf** [comment]
The functionality is used on a daily basis by collectives and it's working.

Without more details, we can't take care of this issue. Please reopen if this happen again or if you have more information.
