### ISSUE TITLE
Event order form doesn't record number of tickets

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1261]
If the number of tickets is selected on the event page and isn't changed in the `createOrder` page, the order sent to the server is always for one ticket.

**Comment by looisjl** [comment]
Hello, I don't know if that's the same issue but hello I've created tickets for an event https://opencollective.com/make-it-sound/events/repair-cafe-100-audio-make-it-sound-18-11-16878ev#tickets > I defined "5" as booking limit but it does seem to appear anywhere or have any effect.. can you help me? Cheers Thanks

**Comment by xdamman** [comment]
That's a different issue. I'll create a new one.
