### ISSUE TITLE
Question: eligible OS projects not showing up

### ISSUE THREAD

**Issue by manekinekko** [opencollective/opencollective#1263]
Hi, I'm trying to create an Open Collective for an open source project which has +100 stars, but it's not showing in the eligible repositories.

**The project URL**: https://github.com/angular-klingon/klingon
**Logged in as (username or profile URL)**: https://opencollective.com/wassimchegham
**Error message if any**: The project is not listed
**Expected result**: The project should be eligible

**Comment by piamancini** [comment]
hi @manekinekko it might be because it's under an org. Do you own the organization?

**Comment by manekinekko** [comment]
Yes, I'm the owner. Does F2A extra security affect this?

**Comment by piamancini** [comment]
no it shouldn't. Maybe you gave access as a user and not as an org. try revoking the rights and then when you connect again, make sure you are doing as the org. LMK if you still can't and I'll send you an alternative link for a manual set up

**Comment by manekinekko** [comment]
Oh! that worked. I revoked the rights and tried again. Thanks, @piamancini for your help 👍 

Closing this issue.

**Comment by piamancini** [comment]
yay! welcome to Open Collective. <3
