### ISSUE TITLE
create an open collective payment method for host

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1264]
Marco, the following host : /wpsyd-host (ID 8708) is an old one and they are now reactivating, they need an open collective payment method. Can you please add one? 
Thanks!

**Comment by marcogbarcellos** [comment]
hey guys, sorry but I completely missed this issue. what's the status on it @piamancini ?

**Comment by piamancini** [comment]
We still need to add an open collective payment method to this collective.

**Comment by piamancini** [comment]
closing then. Thanks
