### ISSUE TITLE
measure % of monthly donations come from paypal

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1266]
We want to measure what % of the backer support is through paypal vs credit cards. 
This is another up for grabs issue for the team

**Comment by Betree** [comment]
@piamancini Do we want that information to be available via the GraphQL API, or should we just provide a SQL query that can be used to get the info whenever we want?

**Comment by piamancini** [comment]
this is no longer relevant as it's part of the weekly and platform reports. closing.
