### ISSUE TITLE
Github flow: disable "create" button after first click

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#127]
Someone just created two collectives within a couple of seconds of each other.

**Comment by carlosascari** [comment]
Related Issues
https://github.com/OpenCollective/OpenCollective/issues/140
https://github.com/OpenCollective/OpenCollective/issues/137

PR
https://github.com/OpenCollective/opencollective-website/pull/302

**Comment by asood123** [comment]
Fixed.
