### ISSUE TITLE
Create new payment Method: Virtual Cards

### ISSUE THREAD

**Issue by marcogbarcellos** [opencollective/opencollective#1272]
This payment method will be basically a proxy to an actual Payment Method in a sense that whenever some Collective/Host/User creates it, it's going to specify the source of the virtual card(`SourcePaymentMethodId`).

## User story 

1. **Organization X** wants to create a `U$2000` **virtual card**.
2. **Organization X** chooses one of its payment method to be the `SourcePaymentMethodId` of the Virtual card, which means that every time someone uses the Virtual Card is going to act basically like a proxy to the **Organization X** `SourcePaymentMethod` and it will also, of course, decrease or end the Virtual Card Balance. 
3. When **Organization X** creates the Virtual Card, the Payment method `CollectiveId` will be, at first, the `CollectiveId` of the **Organization X**. A link called **claimURL** will be generated and The **Organization X** can send this link to an email to claim it.
4. Once the user who receives the email click on the claimURL. 
    - He's going to be redirected to a page on the open collective website 
    - The page can have something like `Congratulations, Organization X has given you a U$2000 virtual card to spend on opencollective, sign up(or sign in) with your email to claim it!`
5. After that, the user will be able to see the payment method on its Payment method list.

## Best solution for this problem (ideal)

The best solution is the one stated above on the User story.

One thing that is not perfect technically is: the virtual card will work as just a proxy, so whenever there is an order to be processed it's going to use its `SourcePaymentMethod` to process that order and then it will update the transactions created on the ledger to replace the `SourcePaymentMethodId` with the virtual `PaymentMethodId` which may be dangerous in some cases(for example, the system creates the transactions and between the time it's created the transactions and the virtual card is trying to update the transactions something wrong happen with the instance of the app or something like that. In this case we wouldn't have the transactions updated and it can be a problem because we'll never know that transaction happened "because" of a credit card).

### PS regarding other solution

During a whiteboard session, it was discussed if instead of creating a new Payment Method(virtual cards) we should keep reusing the Prepaid Card method. Here are some things we found on why using prepaid cards may not be ideal at the moment:

- When we add funds to an Organization creating a prepaid card, we don't record this action as a transaction on the ledger.
  - It'd be ideal to record this action as a ledger transaction but it would require a lot of efforts regarding migrating the funds that were already added to make sure the ledger is consistent
  - The transactions only show up on the ledger when there is a payment from the organization to a collective.
- This would not work correctly to create prepaid cards without having anyone "assigned" to it.

## Metrics 

// TO DO: Open for discussion

#### Creating a virtual card

The virtual card payment method fields: 
  - claimUrl - The Url that's going to be generated for someone to "claim" the virtual card, 
  - initialBalance - The initial amount that can be spend,
  - CollectiveId - The Collective that will be allowed to use the virtual card,
  - SourcePaymentMethodId - The actual payment method that's going to be used everytime the virtual card generates a transaction,
  - expiryDate - the date the virtual will be no longer valid

We will have a new mutation `createVirtualPaymentMethod(CollectiveId[, PaymentMethodId], initialBalance, expiryDate)` that will be responsible for creating the virtual payment methods as stated above.

#### Claiming a virtual card
  
we need another mutation `claimPaymentMethod(CollectiveId, virtualCardUUID)` that will basically update the Virtual Card `CollectiveId` to have the CollectiveId field as stated in the parameter.

#### API Calls
  - We need an API call to create Virtual Cards
  - We need an API call to claim the Virtual Cards
  - We need an API call to get the list of all transactions made by the SourcePaymentMethodId

### Whiteboard Pictures

![img_0842](https://user-images.githubusercontent.com/8717041/45269117-44d81880-b456-11e8-9402-be24bbd07b3b.jpg)

## Documentation 

// TO DO: Waiting on Frontend/Design implementation

**Comment by xdamman** [comment]
For v1:
The created virtual cards should be assigned to the organization that created it but anyone that provides the UUID of such card should be able to use it (right now a payment method can only be used by admins of the organization or members within the `monthlyLimitPerMember`)

5. On the frontend, it will be like today with the Gift Card link. The user will have to enter the UUID (or better a short version of it like we do for `matchingFund`). Or this UUID could be passed as a query param in the URL and we could store it in `localStorage` like we do for `matchingFund`.
That would basically add the virtual card with its current balance as payment method to the list of payment methods available to make the order.

6. Whenever a virtual card is used for the first time, it is being assigned to the `fromCollective` of the order. That way, it will automatically show up in the list of payment methods if its balance is > 0 and if it's not expired.

Notes:
- We need an API call to get the list of all transactions made by the `SourcePaymentMethodId`
- We need an API call to generate Virtual Card which would return a unique link that can be sent by email and that will automatically keep the "gift card code" in the `localStorage` (like we do for `matchingFund`).

**Comment by xdamman** [comment]
TODO:
- [ ] Create a new API key and associated token for the admin of organization X (@znarf)
- [ ] New mutation `createVirtualPaymentMethod(CollectiveId: Int!, initialBalance: Int!, expiryDate: String)` (@marcogbarcellos)
- [ ] Update mutation `createOrder()` to work with a UUID of a VirtualPaymentMethod (@marcogbarcellos)
- [ ] Update page opencollective.com/redeem?uuid=xxxx-xxxx-xxxx-xxxx (@xdamman)
- [ ] Update design for showing a `Transaction` small (for collective page) / wide (for transactions page) (@cuiki)
- [ ] Implement updated design for showing a `Transaction` (@xdamman)

**Comment by marcogbarcellos** [comment]
## Final Implementation details

Adding a new type of payment methods: virtual cards.

It's important to be consistent as much as possible throughout our code base and API.
To that goal, here is a first proposal for the create a new virtual card api endpoint:

```sh
curl "https://api.opencollective.com/v1/payment-methods" \
  -H "Content-Type: application/json"\
  -H "Authorization: Bearer ${token}" \
  -H "Client-Id: ${clientId}"

```

POST Parameters:

- `CollectiveId`: id of the User or Organization
- `type`: "virtualcard" (This is optional as it defaults to `virtualcard`)
- `amount`: amount in cents
- `currency`: currency of the payment method to be created

Example:

Create a U$100 virtual card for CollectiveId 13223:

```sh
curl "https://api.opencollective.com/v1/payment-methods" \
  -H "Content-Type: application/json"\
  -H "Authorization: Bearer ${token}" \
  -H "Client-Id: ${clientId}"\
  --data '{"amount": 10000, "currency": "USD", "CollectiveId": "XXXXXX"}'
```

This returns a JSON:

```json
{
  "id": 912838,
  "CollectiveId": 327865,
  "code": "c7194e16fb07",
  "balance": 10000,
  "expiryDate": "2014-09-08T08:02:17-05:00",
  "currency": "USD",
  "redeemUrl": "https://opencollective.com/redeem?code=c7194e16fb07"
}
```

## Technical How To

1) Become an admin of the Collective you want
```sql
INSERT INTO public."Members"(
	 "CreatedByUserId", "CollectiveId", role, "MemberCollectiveId")
	VALUES (YOUR_USER_ID, COLLECTIVE_ID, 'ADMIN',  YOUR_USER_COLLECTIVE_ID);
```
2)  export API_KEY=XXXXXXXXX (IF you're using actual staging go to Heroku settings to get the correct key)
3) curl "http://0.0.0.0:3060/users/signin?api_key=${API_KEY}" -H "Content-Type: application/json" -X POST -d '{"user":{"email":"marco@opencollective.com"}}'
4) export LOGIN_TOKEN=XXXXXXXXXX
5) curl "http://0.0.0.0:3060/users/update-token?api_key=${API_KEY}" -H "Authorization: Bearer ${LOGIN_TOKEN}" -X POST
6) export ACCESS_TOKEN=XXXXXXXXX
7) curl "http://0.0.0.0:3060/applications/create?api_key=${API_KEY}" -H "Content-Type: application/json" -H "Authorization: Bearer ${ACCESS_TOKEN}" -X POST -d '{ "name":"My Open Collective App", "description":"This is my Open Collective App", "callbackUrl":"http://0.0.0.0:3000/callback" }'
8) export CLIENT_ID=XXXXXXXXXX
9) curl -H "Content-Type: application/json" -H "Authorization: Bearer ${LOGIN_TOKEN}" -H "Client-Id: ${CLIENT_ID}" -X POST --data '{"CollectiveId": 1863, "amount": 10000, "currency": "USD"}' http://localhost:3060/v1/payment-methods
