### ISSUE TITLE
Browsing from one collective to another doesn't refresh the balance/budget bar

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1274]
To reproduce:
Go to https://opencollective.com/webrussels
Then click on the logo of the last transaction to get to https://opencollective.com/fearlesscitiesbrussels

![](https://d.pr/free/i/XMtacX+)

After refreshing the page:
![](https://d.pr/free/i/L4FZNj+)

**Comment by znarf** [comment]
@xdamman Similar issue was https://github.com/opencollective/frontend/pull/407

There was a `this.collective` that was never updated when navigating.

**Comment by xdamman** [comment]
@znarf thanks, that was it!
