### ISSUE TITLE
Style Buttons according to Figma Design standards

### ISSUE THREAD

**Issue by marcogbarcellos** [opencollective/opencollective#1277]
Style the buttons according to what is stated on Figma.

![screen shot 2018-09-07 at 10 21 15 am](https://user-images.githubusercontent.com/8717041/45224738-b7939900-b288-11e8-94d6-7f5d00cdd0bd.png)

**Comment by cuiki** [comment]
I've updated the buttons in the design system.

They now include more states (Selected, Async) and the sizes were adjusted to all be multiples by 8 px (1X) in height.

<img width="689" alt="screen shot 2018-11-21 at 7 06 40 am" src="https://user-images.githubusercontent.com/981188/48843263-2b0f5780-ed5c-11e8-9f4b-c89dc93873dd.png">
