### ISSUE TITLE
Contributor Images still *sometimes* Not Found

### ISSUE THREAD

**Issue by monkeywithacupcake** [opencollective/opencollective#1278]
Similar to: https://github.com/opencollective/opencollective-api/issues/1164
and Similar to: https://github.com/opencollective/opencollective-api/issues/1254

I'm getting lots of questions about not founds when I setup repos, and I don't have a good answer. Can someone help me explain it? 

Here's a recent failure

URL: https://opencollective.com/opensourcediversity/contributors.svg
Logged in as (username or profile URL):NA
Error message if any: Not found
Expected result: image
Browser:Chrome

**Comment by HipsterBrown** [comment]
@monkeywithacupcake It appears the https://opencollective.com/opensourcediversity/backers.svg and https://opencollective.com/opensourcediversity/sponsors.svg works. 

Where do we document the `contributors.svg` endpoint? That endpoint should only work for GitHub projects, I believe.

**Comment by monkeywithacupcake** [comment]
If I am only updating projects that are on Github, this should always work, right?

**Comment by piamancini** [comment]
I can add the repo in the settings - this is because opensourcediversity was created manually

**Comment by piamancini** [comment]
done
