### ISSUE TITLE
W9 bot failed to post comment when it was required

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1279]
https://opencollective.com/vuejs/expenses/4426

This person has expensed over $600, but the bot did not make a comment. He has not submitted his tax form (according to the email box archives and the dropbox folder). I post about it manually to him for now, but is the bot working as expected?

**Comment by marcogbarcellos** [comment]
I tested all steps everything locally(even with the same user) and this with this issue https://github.com/opencollective/opencollective/issues/1273 closed and already in production, I believe the next time this user creates an expense the bot comment should show up. I will keep this issue open so we can monitor this, I'd appreciate if you can help me keep tracking of this as well @alannallama . thanks for the heads up...

**Comment by znarf** [comment]
@marcogbarcellos Close?

**Comment by marcogbarcellos** [comment]
Sure, If the issue come up again we can always reopen or create a new one...
