### ISSUE TITLE
update picture not working

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#128]
from github.com/nem035 (algorithmvisualizer collective)
I've been trying to update my picture on your page but the application breaks every time. 

Here's the screenshot of the error:

<img width="1195" alt="screen shot 2016-06-10 at 1 18 57 pm" src="https://cloud.githubusercontent.com/assets/3671070/15973175/f47ecadc-2f0f-11e6-9aff-0d44364fd60e.png">

**Comment by nem035** [comment]
Seems like [this line](https://github.com/OpenCollective/opencollective-website/blob/a45f891fc0a81bae1585e0b6b007460a328208c0/frontend/src/components/ImageUpload.js#L42) is causing the problem

**Comment by ScottFreeCode** [comment]
Would changing `value.match(/.../)` to `/.../.test(value)` fix this? Or do we want to instead first check that `value` is a String? (`/.../.test(<anything that is not a String but can be converted to one>)` will convert the thing to a string before calling `test`, so in some uses it could be dangerous -- e.g. `/Object/.test(someVariable)` will return true for both `someVariable = "This string talks about Objects!"` and `someVariable = {}`.)

**Comment by ScottFreeCode** [comment]
To answer my own question with a better question, I guess what matters is why something that isn't a string is being passed to this function; simply skipping that check for non-string objects could lead to silent failures.
