### ISSUE TITLE
Collective Receiving money

### ISSUE THREAD

**Issue by nadineCnP** [opencollective/opencollective#1283]
URL: www.opencollective.com
Logged in as (username or profile URL): nadinekhouzam
Error message if any:
Expected result: I would like for my collective to be able to receive money (directly on the account) from people paying for our service. This should directly be identified as belonging to my collective and should send a confirmation email saying that the amount was well received on [the collective name] account.
I do not have preferences for the payment to be made by transfer or on opencollective platform, as long as it is available for credit as well as debit cards.

Thanks!!
Browser: all

**Comment by piamancini** [comment]
Hi @nadineCnP Sorry we missed this! 
The way of doing this is connecting a stripe account to your collective. 
Go to opencollective.com/create and create your collective, choose yourself as the host and connect a stripe account. That's it! best
