### ISSUE TITLE
Support invoices from vendors

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1284]
## User story:

Sometimes user file directly an invoice from a vendor to their collective.
This happened to me when I needed to file the invoice to pay the VAT for the Open Collective Europe host (e.g. https://opencollective.com/europe-collective/expenses/3012 and https://opencollective.com/europe-collective/expenses/4809). I paid those expenses directly from the bank account of the host and marked those as paid. 

## Problem

When we file invoices that are directly paid by the host, we are currently recording the CREDIT transaction from the perspective of the person who filed the expense instead of the organization that emitted the invoice. As a result, I now see in the list of my transactions that I received money from the Open Source Europe collective: 

![](https://d.pr/free/i/SGpm9R+)

## Ideal solution

When filing an expense, we should specify if it's an expense that needs to be reimbursed or if it is an invoice that needs to be paid out. In that case, the user should specify the vendor.

**Comment by alanna** [comment]
I think this case is a subset of "submit expense on behalf of someone else" which will be included in the expenses redesign soon. That way the submitter can specify the vendor as the payee and the payment can be made directly from the host. This is great for us to enable as it cuts down on redundant payments that then need to be reimbursed.

**Comment by alanna** [comment]
Dup of #3323
