### ISSUE TITLE
Add banner to apply to create a collective for an open source project to the /opensource super collective

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#129]
@carlosascari can you add this banner that you did for the homepage to the `PublicGroup.js` container but only if `group.slug === 'opensource'` ?
I'd put it just below the list of members (which in the case of the open source collective represents all the open source projects that we have)

![](http://cl.ly/0E2Y2y231Z0m/Screen%20Shot%202016-06-10%20at%202.04.27%20PM.png)

P.S: Btw, this looks great! 👍

**Comment by carlosascari** [comment]
@xdamman 
Currently, below the list of members is the whyjoin section, if I place the banner under the list of members it will look weird next to the whyjoin section.

We could hide the whyjoin section when `group.slug == '/opensource'`, what do you think?

![Preview](https://my.mixtape.moe/hoftja.png)

**Comment by xdamman** [comment]
Ah yes indeed, that doesn't look good. Yes let's remove it. @piamancini we should then use the main description of the collective to talk about the matching fund.

**Comment by piamancini** [comment]
that's ok
