### ISSUE TITLE
API call to create a new virtual card

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1293]
It's important to be consistent as much as possible throughout our code base and API.
To that goal, here is a first proposal for the create a new virtual card api endpoint:

```sh
curl "https://api.opencollective.com/v1/paymentMethods/create" \
  -H "Authorization: Bearer ${token}"

```

POST Parameters:
- `ClientId`: id of the application (aka api key)
- `CollectiveId`: id of the User or Organization
- `type`: "virtual" (default)
- `amount`: amount in cents

Example:

Create a $100 virtual card for CollectiveId 13223:

```sh
curl "https://api.opencollective.com/v1/paymentMethods/create" \
  -H "Authorization: Bearer ${token}" \
  --data "ClientId=xxxxxxxxx&CollectiveId=13223&amount=10000"
```

This returns a JSON:

```json
{
  "code": "c7194e16fb07",
  "emitterSlug": "myorganization",
  "balance": 10000,
  "currency": "USD",
  "redeemUrl": "https://opencollective.com/redeem?code=c7194e16fb07"
}
```

where `emitterSlug` is the slug of the `CollectiveId` used to create the card.

**Comment by znarf** [comment]
- Please keep the `Client-Id` in the headers, it's the same level as the `Authorization`
- `create` is duplicate with `POST` and can be removed
- `CollectiveId` could be in the URL

**Comment by xdamman** [comment]
If we want to have `CollectiveId` in the URL, then we need to have the previous path be `collectives`.

To be consistent with `/connected-accounts` https://github.com/opencollective/opencollective-api/blob/master/server/routes.js#L113, let's use `/payment-methods`

Based on this feedback, what about:

```
curl "api.opencollective.com/v1/collectives/:collectiveSlug/paymentMethods" \
  --header "Authorization: Bearer ${token}" \
  --header "Client-Id: ${ClientId}" \
  --data "amount=10000&expiryDate=YYYY-MM-DD"
```

**Comment by marcogbarcellos** [comment]
Looks good, I personally think if we want to have a public and consistent API we should try to follow the REST Standard as much as possible, in the end it's supposed to be a standard for this reason. 

In this case I think it's "more" Rest compliant if we just use spinal-case like this: `https://api.opencollective.com/v1/payment-methods` and leave the other properties(including `CollectiveId`) in the request payload.

It is recommended to use spinal-case (which is highlighted by [RFC3986](https://tools.ietf.org/html/rfc3986)), this case is used by Google, PayPal and other big companies.

**Comment by marcogbarcellos** [comment]
## Final Implementation details

Adding a new type of payment methods: virtual cards.

It's important to be consistent as much as possible throughout our code base and API.
To that goal, here is a first proposal for the create a new virtual card api endpoint:

```sh
curl "https://api.opencollective.com/v1/payment-methods" \
  -H "Content-Type: application/json"\
  -H "Authorization: Bearer ${token}" \
  -H "Client-Id: ${clientId}"

```

POST Parameters:

- `CollectiveId`: id of the User or Organization
- `type`: "virtualcard" (This is optional as it defaults to `virtualcard`)
- `amount`: amount in cents
- `currency`: currency of the payment method to be created

Example:

Create a U$100 virtual card for CollectiveId 13223:

```sh
curl "https://api.opencollective.com/v1/payment-methods" \
  -H "Content-Type: application/json"\
  -H "Authorization: Bearer ${token}" \
  -H "Client-Id: ${clientId}"\
  --data '{"amount": 10000, "currency": "USD", "CollectiveId": "XXXXXX"}'
```

This returns a JSON:

```json
{
  "id": 912838,
  "CollectiveId": 327865,
  "code": "c7194e16fb07",
  "balance": 10000,
  "expiryDate": "2014-09-08T08:02:17-05:00",
  "currency": "USD",
  "redeemUrl": "https://opencollective.com/redeem?code=c7194e16fb07"
}
```

## Technical How To

1) Become an admin of the Collective you want
```sql
INSERT INTO public."Members"(
	 "CreatedByUserId", "CollectiveId", role, "MemberCollectiveId")
	VALUES (YOUR_USER_ID, COLLECTIVE_ID, 'ADMIN',  YOUR_USER_COLLECTIVE_ID);
```
2)  export API_KEY=XXXXXXXXX (IF you're using actual staging go to Heroku settings to get the correct key)
3) curl "http://0.0.0.0:3060/users/signin?api_key=${API_KEY}" -H "Content-Type: application/json" -X POST -d '{"user":{"email":"marco@opencollective.com"}}'
4) export LOGIN_TOKEN=XXXXXXXXXX
5) curl "http://0.0.0.0:3060/users/update-token?api_key=${API_KEY}" -H "Authorization: Bearer ${LOGIN_TOKEN}" -X POST
6) export ACCESS_TOKEN=XXXXXXXXX
7) curl "http://0.0.0.0:3060/applications/create?api_key=${API_KEY}" -H "Content-Type: application/json" -H "Authorization: Bearer ${ACCESS_TOKEN}" -X POST -d '{ "name":"My Open Collective App", "description":"This is my Open Collective App", "callbackUrl":"http://0.0.0.0:3000/callback" }'
8) export CLIENT_ID=XXXXXXXXXX
9) curl -H "Content-Type: application/json" -H "Authorization: Bearer ${LOGIN_TOKEN}" -H "Client-Id: ${CLIENT_ID}" -X POST --data '{"CollectiveId": 1863, "amount": 10000, "currency": "USD"}' http://localhost:3060/v1/payment-methods
