### ISSUE TITLE
Deactivate legacy 'website'

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1294]
We're still using some elements from a legacy code base that we want to retire. Repository: https://github.com/opencollective/opencollective-website

The elements that are still loaded from it:

- [x] https://opencollective.com/learn-more
- [x] https://opencollective.com/discover
- [x] https://opencollective.com/opensource/apply
- [x] https://opencollective.com/public/*
- [x] https://opencollective.com/babel/banner.md (looks broken)
- [x] /invoice.pdf /invoice.html (please confirm that it is still being used)

**Comment by Betree** [comment]
Once `learn-more` and `discover` page will be migrated, one should remove the `TemporaryFixMenuLink` component created in https://github.com/opencollective/opencollective-frontend/pull/933 to use a regular `MenuLink` instead.

See this TODO: https://github.com/opencollective/opencollective-frontend/blob/561f679c821f3bc48ac0d617e26ade70a44caabc/src/components/Footer.js#L85

**Comment by znarf** [comment]
That's done!

**Comment by Betree** [comment]
Woot :champagne:
