### ISSUE TITLE
Different avatar in contributors and backers view

### ISSUE THREAD

**Issue by FredyC** [opencollective/opencollective#1295]
I am wondering where does OC take avatars shown within contributors? It has used an old photo of me which I am no longer using and would love to figure where it's still used. Correct avatar is used for me as the backer. It's the same one I am using in GitHub and the same one in OC profile.

URL: https://github.com/lingui/js-lingui#contributors
Logged in as (username or profile URL): https://opencollective.com/fredyc

![image](https://user-images.githubusercontent.com/1096340/45427849-3bda8780-b6a0-11e8-9dec-4e8f4db09523.png)

**Comment by piamancini** [comment]
hi @FredyC thank you, quick question was that your twitter avatar before? it might be a cache issue. When did you update your OC profile?

**Comment by FredyC** [comment]
@piamancini No, my twitter profile has this new avatar also and it's there for more than 1 year for sure. I went through all the services that might be somehow related, but I wasn't able to find the old one anywhere.

**Comment by znarf** [comment]
hey @FredyC, spent some time investigating this.

We're fetching  and processing the images through a service named "Cloudinary" and looks like there was an infinite cache policy there. I flushed the cache but at this time, we're still hitting a CDN cache on their side :-/

Link: https://res.cloudinary.com/opencollective/image/fetch/c_thumb,g_face,h_128,r_max,w_128,bo_3px_solid_white/c_thumb,h_128,r_max,w_128,bo_2px_solid_rgb:66C71A/e_trim/f_auto/https%3A%2F%2Favatars.githubusercontent.com%2FFredyC%3Fs%3D96 (seems that it's up to date when fetching with Chrome, but not from or Firefox or from our infrastructure).

Once solved on Cloudinary side, there is still another cache on our side, and I'm also currently reviewing our policy there.

Keeping the ticket open and we will see how that evolve in the next hours.

**Comment by znarf** [comment]
Fixed.

**Comment by FredyC** [comment]
@znarf Awesome, thank you. So if you understand correctly, it was just cached in Cloudinary so I don't need to worry I forgot to replace it somewhere?

**Comment by znarf** [comment]
Yes, it was cached on multiple layers with the source being a staled cache on Cloudinary. It was basically your avatar from 2 years ago. From now, we will cache for a maximum of 7 days.
