### ISSUE TITLE
collectives through github flow break notification/currency/tiers when they apply to a new host 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1296]
https://opencollective.com/mmmmm-mobile came in through github but they want to be hosted by Europe. 

So they during the flow they applied to Europe as a result: 

- the host ID in collective table and member was OC Europe 
- the collective received an of pending approval from 501c6 with broken css (see image below)
- the collective received an email of approval from 501c6 even if isActive remained FALSE.  
- the collective currency was USD (instead of taking the one from the host)
- the tiers didn't show up when approved
<img width="532" alt="screen shot 2018-09-12 at 10 46 02 am" src="https://user-images.githubusercontent.com/3671070/45432982-29008c80-b679-11e8-9322-d49e15296c81.png">

**Comment by znarf** [comment]
@piamancini @xdamman was that fixed?

**Comment by piamancini** [comment]
the host currency issue is not fixed or at least is also reported here https://github.com/opencollective/opencollective/issues/1382
https://github.com/opencollective/opencollective/issues/1408 althouh @xdamman pushed a fix here https://github.com/opencollective/opencollective/issues/1415

The other issues I haven't seen them again, this was an edge case. But I don't know if they are fixed.

**Comment by znarf** [comment]
@piamancini Looks like we had a lot of changes in these areas since that issue was reported. 

Closing. If something happen again, please report again with fresh data.
