### ISSUE TITLE
remove (edit) from the main title in host/apply flow

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1297]
collective core contributor applies to create a new collective under a host using the host organization /apply. Before it creates a collective there's an _(edit)_ in the main title that shouldn't be there. It looks out of place. 

<img width="1263" alt="screen shot 2018-09-12 at 12 40 32 pm" src="https://user-images.githubusercontent.com/3671070/45440182-9fa58600-b689-11e8-8e5c-4fbd059a61d8.png">

**Comment by Betree** [comment]
Looks like this was fixed 

![selection_999 090](https://user-images.githubusercontent.com/1556356/52734272-09bdb080-2fc5-11e9-85ea-bd43f330fb83.png)
