### ISSUE TITLE
Record everything that goes on in the system

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#13]
We have an `Activity` model that's meant to record every action in the system. It started as a way to show an activity feed on a group page. Then it evolved into recording events to show in slack. It's incomplete in both cases.

We need to record everything that happens in the system - every action, every bit of data that comes in. `Activity` should be modified to cover all the cases. 

One way to do this would be to create a middleware that intercepts all routes and records everything. This would clean up scattered `Activity` entries everywhere and put them in one place for easy maintenance. Open to other ideas like Kafka?

**Comment by sedubois** [comment]
I should add that Redux naturally enables to store a trail of all its states, probably as well as all its actions. Would take much work though to bring Redux to the backend and store each and every state within it both on frontend and backend. But worth keeping in mind as a general design principle.

**Comment by piamancini** [comment]
@asood123 Can i close this?
