### ISSUE TITLE
Collective / host Self serve flow issues

### ISSUE THREAD

**Issue by Kilheure** [opencollective/opencollective#1302]
URL: https://opencollective.com/uk#about
Logged in as (username or profile URL): none
Error message if any: none
Expected result: reduced number of collectives
![screen shot 2018-09-13 at 12 07 49](https://user-images.githubusercontent.com/31570464/45484986-ebb9fe80-b74d-11e8-8bb9-4973640f8e92.png)

Browser: chrome / IE / Safari

Number of issues with self serve flow: 
1) Collectives that are created without host approval. 
Example: a-minimum-viable-platform-for-better-media; Dundee block chain
1.1) it leads to duplicate collectives
Example: Kings Lynn appears twice as a collective
1.2) Collective with invalid page, webpage doesn't load up on any browser
https://opencollective.com/a-minimum-viable-platform-for-better-media-cpbfs-agm-2018-17634ev
1.3) Most Newest collectives have no backer, no description, etc. (see attached imaged)

**Comment by xdamman** [comment]
Fixed in https://github.com/opencollective/opencollective-frontend/pull/995
