### ISSUE TITLE
Activate tax form bot on expense submission instead of approval

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1305]
Currently, the tax form bot makes a comment when an expense is approved that will put a user over the $600 limit. However, the person needs time to fill out their form and we only pay expenses once a week, so if the core contributor approves the expense right before payment time, we can't pay until the following week (assuming the user submits their tax form in that time). This creates a delay.

I suggest the tax bot posts upon submission of the expense instead of waiting for approval. 

If the message could be made obvious when the users clicks "submit" on their expense (kind of like an error message, but it still lets them submit the expense), and it also posted a comment too (so I can see it while processing payments and an email is generated to the user), that would be ideal.

**Comment by alannallama** [comment]
To add some context, we get emails every week from people who have submitted their tax form but missed the pay run that week and are wondering what the delay is.

**Comment by alannallama** [comment]
We still need this

**Comment by alanna** [comment]
This will be moot with the new tax form process.
