### ISSUE TITLE
Add a rest endpoint to the api to get the transactions of a given payment method

### ISSUE THREAD

**Issue by marcogbarcellos** [opencollective/opencollective#1307]
## User story 

Backer wants to know all the transactions he's done over the last couple months|weeks|days with his credit card.

## Best solution for this problem

Create a REST Endpoint `GET /v1/payment-methods/:id/transactions` that will also allow URLs using `start` and `end` through the format `YYY-MM-DD` that will look for transactions with the fields `createdAt` that match the result. If only `start` is defined we'll have all transactions that were created after the specified date, If only `end is defined` all transactions before the date, and if both are defined we will have the transactions between those dates.

**Comment by piamancini** [comment]
@marcogbarcellos USER is not a role one the platform ---> https://github.com/opencollective/opencollective/wiki/Open-Collective-Roles

**Comment by marcogbarcellos** [comment]
I have found 2 importants things to discuss so I can have the final requirement/ implementation: 

1. We have credit and debit transaction and i'll be returning all transactions but i was wondering if we need to actually return all or only their DEBIT or CREDIT transactions. 

2. I think we need to actually have 2 endpoints:
    - `GET /v1/payment-methods/:paymentMethodId/transactions` where this will return all transactions if the CollectiveId of the logged in user is the same as in the payment method, otherwise the user won't have permissions to see other people's payment methods.
    - `GET /v1/payment-methods/:PaymentMethodId/collectives/:CollectiveId/transactions` where this will return all transactions if the logged in user is an `ADMIN` of collective found through the param `CollectiveId` , otherwise the user won't have permissions to see other people's payment methods.
    - If we don't want to keep both endpoints, I believe the second endpoint is more important.

**Comment by znarf** [comment]
@marcogbarcellos Nice that you have written the documentation. Let's figure a place to host it permanently. What about some markdown documents in the API project?

**Comment by xdamman** [comment]
Can be added here: https://github.com/opencollective/opencollective/tree/master/docs/api
This is what is published on https://developer.opencollective.com

I wouldn't do the second api call as the first call is already good enough. Less surface area to maintain.

**Comment by znarf** [comment]
@xdamman @marcogbarcellos +1 for "Less surface area to maintain." and +1 for the developer docs. Just need to check how to generate and deploy.

Thinking about the future of our architecture, if we all agree that the `opencollective-api` is our GraphQL API and that it's our only core API, I think we should move all REST endpoints asap out of the `opencollective-api` repository, so that we don't have to maintain them there.

We can create quickly a project like `opencollective-rest'  using GraphQL to expose REST endpoints. We would deploy that on now and expose that on something like https://rest.opencollective.com/.

**Comment by marcogbarcellos** [comment]
I will update the docs link right now as well, but I'm also posting the last Docs here so this issue is also up to date: 


This PR contains 2 new REST endpoints:

## GET /v1/collectives/:collectiveSlug/transactions

This query requires the collective **slug** of. It also allows the following query parameters:
    - type - If Transaction is `DEBIT` or `CREDIT`
    - limit - the number of records to be returned
    - offset - the number that determines offset of the query
    - dateFrom - the start date(format `YYYY-MM-DD`) to be considered when returning the data
    - dateTo - the end date(format `YYYY-MM-DD`) to be considered when returning the data
    - includeVirtualCards - a boolean that, if true, will include the transactions generated by all virtual cards issued by the specified collective

Example: 
Open Collective(a collective that has slug **opencollective-company**) wants to see his last 3 CREDIT transactions, including the transaction from the virtual cards Open collective has issued:

```sh
curl "http://localhost:3060/v1/collectives/opencollective-company/transactions?limit=3&type=CREDIT&includeVirtualCards=true" \
  -H "Content-Type: application/json"\
  -H "Client-Id: ${clientId}"
```

This returns the following json JSON:

```json
{
   "result":[
      {
         "id":9047,
         "uuid":null,
         "type":"CREDIT",
         "amount":500,
         "currency":"USD",
         "hostCurrency":"USD",
         "hostCurrencyFxRate":1,
         "hostFeeInHostCurrency":-25,
         "platformFeeInHostCurrency":-25,
         "paymentProcessorFeeInHostCurrency":-45,
         "netAmountInCollectiveCurrency":405,
         "createdAt":"Sun Apr 30 2017 22:33:49 GMT-0400 (Eastern Daylight Time)",
         "updatedAt":"Thu Mar 08 2018 15:24:33 GMT-0500 (Eastern Standard Time)",
         "host":{
            "id":8686,
            "slug":"opencollectiveinc"
         },
         "createdByUser":{
            "id":3605,
            "email":null
         },
         "fromCollective":{
            "id":4505,
            "slug":"christinabowen"
         },
         "collective":{
            "id":1,
            "slug":"opencollective-company"
         },
         "paymentMethod":{
            "id":2198
         }
      },
      {
         "id":7698,
         "uuid":null,
         "type":"CREDIT",
         "amount":500,
         "currency":"USD",
         "hostCurrency":"USD",
         "hostCurrencyFxRate":1,
         "hostFeeInHostCurrency":-25,
         "platformFeeInHostCurrency":-25,
         "paymentProcessorFeeInHostCurrency":-45,
         "netAmountInCollectiveCurrency":405,
         "createdAt":"Fri Mar 31 2017 22:25:57 GMT-0400 (Eastern Daylight Time)",
         "updatedAt":"Thu Mar 08 2018 15:23:18 GMT-0500 (Eastern Standard Time)",
         "host":{
            "id":8686,
            "slug":"opencollectiveinc"
         },
         "createdByUser":{
            "id":3605,
            "email":null
         },
         "fromCollective":{
            "id":4505,
            "slug":"christinabowen"
         },
         "collective":{
            "id":1,
            "slug":"opencollective-company"
         },
         "paymentMethod":{
            "id":2198
         }
      },
      {
         "id":7322,
         "uuid":null,
         "type":"CREDIT",
         "amount":500,
         "currency":"USD",
         "hostCurrency":"USD",
         "hostCurrencyFxRate":1,
         "hostFeeInHostCurrency":-25,
         "platformFeeInHostCurrency":-25,
         "paymentProcessorFeeInHostCurrency":-45,
         "netAmountInCollectiveCurrency":405,
         "createdAt":"Mon Mar 20 2017 20:20:24 GMT-0400 (Eastern Daylight Time)",
         "updatedAt":"Thu Mar 08 2018 15:24:47 GMT-0500 (Eastern Standard Time)",
         "host":{
            "id":8686,
            "slug":"opencollectiveinc"
         },
         "createdByUser":{
            "id":3605,
            "email":null
         },
         "fromCollective":{
            "id":4505,
            "slug":"christinabowen"
         },
         "collective":{
            "id":1,
            "slug":"opencollective-company"
         },
         "paymentMethod":{
            "id":2198
         }
      }
   ]
}
```

## Test in production

Open Collective(collective slug **opencollectiveinc**) has already generated some $50 virtual cards so we can check whether all transactions are all right. Here are a few examples: 

- Including Virtual Card transactions(transactions that used a virtual card that was issued by the collective: http://opencollective.com/v1/collectives/opencollectiveinc/transactions?api_key=YOUR_API_KEY&includeVirtualCards=true

- NOT Including Virtual Cards: http://opencollective.com/v1/collectives/opencollectiveinc/transactions?api_key=YOUR_API_KEY

- Using `limit=20`, `type=DEBIT` and `offset=5`: http://opencollective.com/v1/collectives/opencollectiveinc/transactions?api_key=YOUR_API_KEY&includeVirtualCards=true&limit=20&type=DEBIT&offset=5
