### ISSUE TITLE
[object Object] on Add Funds page

### ISSUE THREAD

**Issue by elijahv** [opencollective/opencollective#1309]
**Describe the bug**
When adding funds to a Collective under the "Source" dropdown the odd option "[object Object]" is displayed. 

What does it mean? It seems like a bug. :-)

**To Reproduce**
1. Go to https://opencollective.com/HOST/dashboard
2. Click on the Collectives dropdown
3. Scroll down to any Collective
4. Click "Add Funds"
5. See error

**Expected behavior**

**Screenshots**
<img width="967" alt="netsquared__a_program_of_techsoup_-_open_collective" src="https://user-images.githubusercontent.com/3868907/45648357-35238a00-ba7d-11e8-8bb5-8fd47a11cf9f.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 10.13.5
 - Browser Chrome
 - Version 69.0.3497.92 (Official Build) (64-bit)

**Additional context**

**Comment by piamancini** [comment]
thank you @elijahv - @HipsterBrown is actually working on it already.
