### ISSUE TITLE
Can't remove update from collective

### ISSUE THREAD

**Issue by dahacouk** [opencollective/opencollective#1310]
**Describe the bug**
I can't remove an update from my collective

https://opencollective.com/noplasticapp#updates

The update is just stuck there. There is not even an edit or delete button.

What happen is I created an update with a video link. It did not work and generated a GraphQL error. So I tried to delete the update by removing all text and title. This left a ghost update that cannot be edited or removed.

**Please can you remove the update?**

**To Reproduce**
1. Create an update.
2. Remove the text and title.
3. See if it creates a ghost update that cannot be removed or edited.

**Expected behavior**
1. I would really like to be able to edit any update.
2. I would like to be able to remove any update.

**Screenshots**
<img width="615" alt="noplasticapp_-_open_collective" src="https://user-images.githubusercontent.com/201752/45670008-91d48280-bb19-11e8-8111-200b2a4849f7.png">

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Safari]
 - Version [11.1.2]

**Comment by piamancini** [comment]
removing the bug tag since there was never a delete button there. 
@znarf can you confirm you manually delete this update?

**Comment by znarf** [comment]
@piamancini yes, done

**Comment by piamancini** [comment]
ok closing this then, since it's solved for @dahacouk and opening a new one specifically for adding the delete option.
