### ISSUE TITLE
Broken certificates

### ISSUE THREAD

**Issue by BonfaceKilz** [opencollective/opencollective#1315]
**Description**
When you navigate to the domain https://opencollective.com, the certificate is correct and the padlock icon on the navigation bar is green as expected. However, when you navigate to https://opencollective.com/webpack, the site becomes insecure.

**To Reproduce**
1. Go to https://opencollective.com
2. Click on 'Discover'
3. Scroll to 'Webpack' and click it

**Expected behavior**
Correct certificates should be given on all pages.

**Screenshots**
**Desktop**
![nonhttps](https://user-images.githubusercontent.com/11820306/45781356-657b4c00-bc68-11e8-999c-e1e05d660284.png)

 - OS: Arch Linux
 - Browser: Firefox
 - Version: 61.0.2-1

**Comment by BonfaceKilz** [comment]
It's fixed. Thanks!

**Comment by znarf** [comment]
Yes, the the slack logo on this page was not loaded from https. We fixed that issue.

However, we still need to change the way we link to external images to prevent that happening in the future.
