### ISSUE TITLE
Virtual Cards release

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1321]
Related to https://github.com/opencollective/opencollective/issues/1272

- [x] don't pass the values in query params, just pass the id of the virtual card and fetch the data from the frontend
- [x] Show the transactions made with the virtual card on the profile page of the owner of the source payment method
- [x] Show the payment method details along with the transaction (to show the owner of the source payment method)

**Comment by znarf** [comment]
Enhancement

- [ ] Enhancement: Marketing Landing Page
- [ ] Enhancement: Client side balidation of the code

General

- [ ] Change link in email for the version with code, nor hardcoded parameters

Backend

- [ ] createPaymentMethod should not accept queries without a paymentMethodId

Unauthenticated experience

- [ ] No email explaining the account creation.
- [ ] Check content of user.card.claimed email
- [ ] "select €100 card from New Order" check that it's appearing like that

Authenticated experience

- [ ] Should we send an email or not. Check the email content.
- [ ] "Hello again, anonymous!" Hello again is not appropriate.

Redeemed page

- [X] Make sure it's only accessible for owner.
- [ ] Make sure invalid codes are handled.

Payment

- [ ] Rename Credit Card -> Payment Method
- [ ] Replace "anonymous - virtualcard €100 card from New Order" -> "anonymous - €100 Gift Card from New Order - exp 01/2019"
- [ ] Use different emoji that Credit Card to differenciate
- [ ] Remove "Use a Gift Card"

Consistent wording:

- [ ] Redeem
- [ ] Redeemed
- [ ] Gift Card
- [ ] Virtual Card (should never appear)
- [ ] Claim (should never appear)
- [ ] Claimed (should never appear)

**Comment by Betree** [comment]
Enhancement

- [ ] [Future VirtualCards implementation: possible risk of double spending? #1412](https://github.com/opencollective/opencollective/issues/1412)

Bug fix

- [ ] Zombie gift cards: if user ends up with a balance < `$0.50` on its VirtualCard, he won't be able to use them (minimum amount for a transaction is `$0.50`). We should keep this minimum amount to avoid having too much micro-transactions, but should not allow to spend `$9.99` for a `$10` gift card.

**Comment by znarf** [comment]
Closing this giant issue. Following up in smaller ones.
