### ISSUE TITLE
Contribution flow: Matching fund

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1323]
As we are redesigning the create order flow, let's make sure we don't forget about those things:

- [ ] matching fund

---

Edit by @Betree 
~~- [ ] make sure we communicate fee structure at the time of checkout~~ => https://github.com/opencollective/opencollective/issues/1506

**Comment by cuiki** [comment]
How does the matching fund work here? Can you give an example?

**Comment by Betree** [comment]
@cuiki There's an example for that on https://opencollective.com/opencollectiveparis/donate/ in the "Matching fund" section. 

![image](https://user-images.githubusercontent.com/1556356/51698466-913d8280-200a-11e9-91d5-6fbb4c66a3bf.png)

So basically we have:
- Matching amount
- Custom message (in French here)
- Generic description (Open Collective has setup...)

**Comment by Betree** [comment]
As per https://github.com/opencollective/opencollective/issues/2237 we're getting rid of the Matching fund feature for now so this issue will not be implemented.
