### ISSUE TITLE
Expense reports with multiple receipts (batch reports)

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#1324]
## User story 
As an event organiser, I want to submit expenses en masse for categories of expense. 

## Best solution for this problem
Submit expense > Upload _multiple_ receipts, provide a _total_ cost and category along with payment instructions as before. Extra points for uploading in the background with a tracker to provide fedback when the upload is complete and the expense can be submitted (obvs. I would be filling in the other information when this happened).

## MVP
The same form, with multi select (and the necessary writes to store/db and multiple file attachments on approval screen)

## Metrics 
Number of batch requests made over singular requests with the same category by the same person within the same 24 hour period. 

## Documentation 
Additional guidance re. _total_ figures to be provided when >1 file is being uploaded should be enough.

**Comment by xdamman** [comment]
Thanks Ben for creating this feature request.

This is typically the type of things that we would love to open an API for and have the community build better tools to submit expenses.

If there is any taker, we would prioritize opening up this part of the API.
