### ISSUE TITLE
Sponsors section on HP

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1325]
## User story 
As a sponsor, I can find all the sponsor features that Open Collective offers (matching funds, virtual card, pre-paid card) so that I can use them. 

## Best solution for this problem
The ideal solution is a self-serve pathway for a sponsor to use any of these features. The sponsor section of the HP would have a Create flow for all these features. 

## MVP

The MVP is a sponsor page (linked from HP) that lists the services with a 'reach out to us' to set it up email. 

Draft copy: 
Become a Sponsor on Open Collective:

Features for sponsors.

- Virtual Cards: Give the gift of giving!  Give your users or your employees a gift card they can use to make donations to collectives. (Maybe link here to triplebyte/redeem?)

- Matching Fund: Incentivize others to give by matching their donation. 

- Pre-paid card: When using a credit card is not convenient, send a bulk payment to your host and create a pre-paid card for your organization for that amount you can use to start (and modify) subscriptions. 

- Analyze your open source stack and support them - BackYourStack

## Metrics 

Measure the number of organizations using the features. 

## Documentation 
_The goal of the documentation should be to make it easier for others to do this_

**Comment by piamancini** [comment]
cc / @xdamman let's iterate on the content until @cuiki wraps up pledges for Nick and maybe we can squeeze this in before he starts the user flow (design for this should be fairly straight forward)

**Comment by cuiki** [comment]
Hi, I can start on this tomorrow. Few questions though.

So there will be a sponsor page dedicated to explain (and 'create' start a flow for each) these 4 features. Can you explain what is the process of what happens after a user clicks on each of the buttons that begin the 'create' flow? I assume that we need to account for orgs that are already in OC and those who have not created an account yet.

Also, just to confirm, a sponsor can still be either a person or an organization, or just organizations. If it's both, then we'd need to update the copy of the homepage that says it is comanies supporting other companies.

Also, I didn't understood this sentence:
> The MVP is a sponsor page (linked from HP) that lists the services with a 'reach out to us' to set it up email.

**Comment by xdamman** [comment]
@cuiki for now, let's just focus on releasing a static marketing page to explain those features with a contact us button or to a google form ([coinbase style](https://listing.coinbase.com) - ah ah ah)

Yes, this is really meant for organizations. Not sure if it's better to call them sponsors or organizations in this case.

To iterate on the content, let's use this google doc:
https://docs.google.com/document/d/1xzJ2AiC-5dHZ_UZ0qPyw2L3O5vlZ-vp6ckCr3xy-9cA/edit?usp=sharing

**Comment by piamancini** [comment]
Made some additional changes to the copy I think it's good to get a start on design when @cuiki finishes pledges

**Comment by cuiki** [comment]
**Hi everyone, here is the first stab at this page:**
https://www.figma.com/file/OUhDavcHuoC0qFt7azSPU7/platform-%E2%80%94-03-become-a-sponsor?node-id=0%3A1

I left some comments on it. Please post your responses to wrap this page up. @HipsterBrown let me know if theres questions when you get to this.

**Comment by xdamman** [comment]
Done but broken. There is a misalignment of the text on mobile. It’s badly centered. Can you fix it or find a way to get the person who wrote the responsive version to directly contribute to the code?

**Comment by znarf** [comment]
@xdamman screenshot?

**Comment by cuiki** [comment]
Here's one @znarf : https://tafka.d.pr/YoZf4c

As you can see the text is misaligned relative to the vertical margins. The images are well positioned in my view, just the text is misaligned. The new updated image is in the FIGMA file.
