### ISSUE TITLE
Remove old/unused branches from the API

### ISSUE THREAD

**Issue by marcogbarcellos** [opencollective/opencollective#1332]
We should clean up the api so that all branches that are outdated/old/unused must be removed

**Comment by znarf** [comment]
Should be simple, let's do it now.

**Comment by marcogbarcellos** [comment]
Do we have a branch that cannot be removed? Perhaps @xdamman has an exception.
If not, We can have the rule of removing all branches with exception to the ones with Open PRs. a good thing to add to this feature is looking for a good bot that does that for us( remove branches after their corresponding PRs are merged)

**Comment by xdamman** [comment]
Not that I can think of. Yeah would be a good idea to have a bot to make sure there is no branch on the origin unless there is an open PR.
