### ISSUE TITLE
UI not working properly when a payment method fails

### ISSUE THREAD

**Issue by marcogbarcellos** [opencollective/opencollective#1334]
**Describe the bug**
When I tried to donate with a payment method that didn't have funds to my order, the UI didn't let me easily retry with a different payment method, I needed to refresh the page.

**To Reproduce**
1. Go to  any collective and try to donate
2. Select the amount and Payment method
3. click in donate
4. You will see an error if your payment method does not have enough funds
5. the payment method options disappear and if I want to retry I will need to refresh the page.

**Expected behavior**
I would expect that the payment method option need to be available so if my payment method fail i can try with a different one at once.

**Screenshots**
![screen shot 2018-10-02 at 11 24 58 am](https://user-images.githubusercontent.com/8717041/46358943-2076f280-c636-11e8-832f-dee8a54993ca.png)

Then i get the error(which is expected) but the payment methods options disappear:

![screen shot 2018-10-02 at 11 25 28 am](https://user-images.githubusercontent.com/8717041/46358951-24a31000-c636-11e8-8637-d7d0d46568d4.png)

**Desktop (please complete the following information):**
 - OS: macos Mojave
 - Browser Chrome
 - Version 69

**Comment by znarf** [comment]
@marcogbarcellos can you try to edit the title to fit in one line max?

**Comment by znarf** [comment]
@marcogbarcellos this is flagged as a priority, is that still the case?

**Comment by marcogbarcellos** [comment]
this is solved with the pr https://github.com/opencollective/opencollective-frontend/pull/909
