### ISSUE TITLE
Crash when removing a payment method while adding one

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1335]
**Steps**

1. Make sure to have at least one Payment Method in your profile
2. Go to http://opencollective.com/<profile> then Edit, then go to Payment Methods section
3. Click "add another payment method"
4. Now "remove" an existing payment method

**Result**: App is crashing

![screen shot 2018-10-03 at 14 12 29](https://user-images.githubusercontent.com/806/46409607-7cb14380-c716-11e8-84c8-14219e5cca26.png)

![screen shot 2018-10-03 at 14 12 45](https://user-images.githubusercontent.com/806/46409591-715e1800-c716-11e8-94d8-49a23d8b4519.png)

**Expected**: No crash

**Comment by Betree** [comment]
Fixed by https://github.com/opencollective/opencollective-frontend/pull/1046
