### ISSUE TITLE
UX improvements in Payment Method editing

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1336]
General

 - [x] There should be no "Save" button.
 - [x] Only a button to submit a new Payment Method
 - [x] And a button to remove an existing Payment Method (no extra Save)

Success when adding a Payment Method:

 -  [x] Feedback message when succeeding <sup>(1)<sup>
 -  [x] Input form should disappear  when succeeding  <sup>(1)<sup>
  - [x] Payment Method should be immediately available in the list

 Payment Method list:

 - [x] The list should be more beautifully presented
 - [x] It should works when accessing directly from the URL. ie: https://opencollective.com/znarf/edit#paymentMethods (currently the list is empty)
 - [x] Virtual cards should be listed

(1) Screenshot after adding a Payment Method

![screen shot 2018-10-03 at 14 17 58](https://user-images.githubusercontent.com/806/46409857-43c59e80-c717-11e8-9b44-0bf7232e17f8.png)

**Comment by Betree** [comment]
Re-opening this as some of the points will be implemented in https://github.com/opencollective/opencollective-frontend/pull/1372

**Comment by Betree** [comment]
Resolved by opencollective/opencollective-frontend#1372
