### ISSUE TITLE
A user should be able to enter the "Meetup" URL without errors

### ISSUE THREAD

**Issue by m2mathew** [opencollective/opencollective#1341]
# NOTE:

This is currently preventing me from creating a collective. Might be happening to others, too.

### Describe the bug

When I am on the `/create` route, the page crashes if I paste in the URL from our meetup site. If I begin typing into the "Meetup URL" field, the cursor moves to the second `<input>` after one key stroke.

### To Reproduce

1. Go to `https://opencollective.com/create`
2. Select "Meetup"
3. Click on the first field and type (or paste something)
4. You will see the cursor jump down to the second input

### Expected behavior

The form should let me type appropriate data into the fields.

### Screenshots

You can see from the video that the focus of the input is moving after a single key event (or maybe paste event). When I get to the full name 

![open-collective--input-error](https://user-images.githubusercontent.com/11624407/46498663-b734e200-c7e3-11e8-8b28-bcedde62dd39.gif)

Error from console pictured below

![image](https://user-images.githubusercontent.com/11624407/46498646-aab08980-c7e3-11e8-9089-27d7c4009606.png)

### Desktop

 - OS: macOS Mojave
 - Browser: Chrome 69.0, Safari 12.0

Thanks, team!

**Comment by znarf** [comment]
@m2mathew, thank you for the detailed bug report!

I hot fixed it. Please confirm that it works for you now.
