### ISSUE TITLE
A user receives an error message for a "too-long" value after submitting the Create form

### ISSUE THREAD

**Issue by m2mathew** [opencollective/opencollective#1342]
# NOTE:

This is currently preventing me from creating a collective. Might be happening to others, too.

### To Reproduce

1. Go to `/create` route's form
2. Fill out completely
3. Put > 255 characters in the "Short Description" field
4. Error pops up **after** the user clicks the submit button.

### Expected behavior

Any error that occurs after a user hits submit should not remove the entire form from the page. At that point the user is told to take care of an error, but has not actionable elements on the page.

### Screenshots

This error should pop up _before_ the user loses all of the content from the "Create" form.

![image](https://user-images.githubusercontent.com/11624407/46498362-d4b57c00-c7e2-11e8-8fdb-eeecd8e46b75.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome 69.0, Safari 12.0

This happened as I was also experiencing #1341

**Comment by maddhruv** [comment]
@znarf can be closed
with this merge - https://github.com/opencollective/opencollective-frontend/pull/2662
