### ISSUE TITLE
Add GitHub urls to organisations

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#1343]
## User story 
Organisations with a GitHub account should be able to add their URL as a personal user can.

## Best solution for this problem
Add GitHub url to database, UI and API for orgs as well as individuals.

**Comment by piamancini** [comment]
@znarf This is what we talked today. The mvp of this would be adding a field under the organization's website to record their github org. We can add it to the settings in the db (I guess?). This might come in handy in the future for backyourstack.

**Comment by Betree** [comment]
Would like to work on this one :slightly_smiling_face: 

In my opinion, it would be nice to have this information provided for **users** too. As of today, they can only set their Twitter handle and a custom website.

**Comment by znarf** [comment]
That does make sense. For each case, we have to see if we want the input at registration time, or only when editing the profile. @piamancini what do you think?

**Comment by piamancini** [comment]
I think for organizations it makes sense to add it on sign up as well as editing since it will increase the likelihood of the doing it and most organizations have them. Users that are not open source maintainers might be confused by this field on sign up so I would only do it in editing profile.

**Comment by BenJam** [comment]
@znarf I noticed that GitHub isn't a field on the new accoutn signup screen for new users: 

i.e. https://opencollective.com/octobox/order/220 

![screencapture-opencollective-octobox-order-220-2018-11-16-15_47_26](https://user-images.githubusercontent.com/158833/48631673-f5aee680-e9b6-11e8-8425-740b934b0776.png)

**Comment by znarf** [comment]
@BenJam Maybe the comment from @piamancini (October 12th) might explain that?

**Comment by piamancini** [comment]
@BenJam do you need it for users?
