### ISSUE TITLE
Change sender and preview text for collective update emails

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1344]
Currently the update emails say they come from "Hello". This adds to the problem of it not being clear which collective a message is from, and looks a bit odd in today's polished email marketing environment. I suggest changing it to "Update from [Collective Name]".

Also, the first few words that show in the preview are always "view online [collective name] logo", which isn't very engaging or helpful. I've seen lots of other emails that begin with a brand image that don't show that kind of text, so there must be a way to start the preview with the actual text content? Or, if not, can we add something generic to show there like "Message for backers of the [collective name] Collective"?

<img width="1015" alt="screen shot 2018-10-06 at 10 33 08 am" src="https://user-images.githubusercontent.com/5498878/46561280-78be3500-c953-11e8-9a6c-cb7d68c8ef71.png">

**Comment by xdamman** [comment]
good point, fixing this
