### ISSUE TITLE
Email Address missing when Exporting CSV on events

### ISSUE THREAD

**Issue by jdorfman** [opencollective/opencollective#1345]
**Describe the bug**
When exporting the CSV of people who bought tickets for [our event](https://opencollective.com/sustainoss/events/sustainuk-2018-442ev), the email addresses are not included.

**To Reproduce**
1. Go to https://opencollective.com/sustainoss/events/sustainuk-2018-442ev#tickets
2. Click on `EXPORT CSV`
3. Open CSV (something like `201810-08-sustainoss-sustainuk-2018-442ev.csv`)
4. See missing values (see 2nd screenshot)

**Expected behavior**
The email addresses should show up to import into MailChimp or whatever

**Screenshots**
![image 2018-10-08 at 2 36 04 pm](https://user-images.githubusercontent.com/398230/46634940-86b4b700-cb07-11e8-858d-3cb85e438bcc.png)
![image 2018-10-08 at 2 24 11 pm](https://user-images.githubusercontent.com/398230/46634966-97fdc380-cb07-11e8-8de6-f8b1c80699be.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 69.x

**Smartphone (please complete the following information):**
- n/a

**Comment by znarf** [comment]
Taking over.
