### ISSUE TITLE
Top Bar thinner on search page

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1356]
**Describe the bug**
Top Bar is thinner on search than everywhere else

**To Reproduce**

1. Go to 'Home Page'
2. Do a search in the Top Bar. 
3. You're navigated to the search page.

**Current Behavior**
The Top Bar is suddenly thinner that on the Home Page.

**Expected behavior**
The Top Bar should be exactly the same.

**Screenshots**

Expected

![screen shot 2018-10-11 at 10 42 57](https://user-images.githubusercontent.com/806/46791995-966c0f80-cd42-11e8-9b77-42ed578eeabe.png)

Actual

![screen shot 2018-10-11 at 10 43 08](https://user-images.githubusercontent.com/806/46791954-818f7c00-cd42-11e8-9ced-2acbb3dcf64b.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome, Firefox, Safari
 - Version: Latests

**Comment by HipsterBrown** [comment]
This is probably because the search input is not rendered on the search page. We should probably set a min-height on the TopBar to avoid that issue.
