### ISSUE TITLE
Cryptocurrency Implementation

### ISSUE THREAD

**Issue by marcogbarcellos** [opencollective/opencollective#1358]
### Main story

**Zcash foundation**(an organization) wants to donates **zcash**(cryptocurrency) to **collectives**
Potentially a grant would go to Open Collective Company to develop compatibility.

### Other stories correlated

We may actually have different scenarios regarding cryptocurrencies :

1. A contributor donates an amount in **cryptocurrency** to a Collective that has a **cryptocurrency**(same *coin* as the donation) **Wallet**.
2. A contributor donates an amount in **cryptocurrency** to a Collective that doesn't have cryptocurrency. 
3. A contributor donates an amount in **fiat** to a Collective that only has a **cryptocurrency**(same *coin* as the donation) **Wallet**. 
4. A collective has a host (fiat) and wants to add a crypto wallet to it's collective. 

## Best solution for this problem

All organization, hosts, collectives, contributors and etc will have **Wallets**  that will have a specific **currency**, either fiat or crypto. following this concept, a **Collective** may have a **USD**, a **CAD**, a **BTC**, a **ZCASH** and so on Wallet. 

Given that, we could have the following *high level* implementations to the different scenarios:

1. A contributor donates an amount in **cryptocurrency** to a Collective that has a **cryptocurrency**(same *coin* as the donation) **Wallet**.
    - The collective will have an *exposed* cryptocurrency **address**(which doesn't necessarily means that address belongs to the Collective, it may be related to the collective but belonging to the platform, the same we have in cryptocurrencies exchanges) which contributors can send money to.
    - The contributor will send the amount of crypto to the address specified in the Collective page.
    - This address will belong to the OpenCollective platform,, then a fee would be charged and the remaining amount will go to the address of the **Wallet Provider**(Each wallet will have a wallet provider which is quite similar to the **host** concept we have today)
    - The Wallet Provider will transfer the money to the Collective according to their agreement.

2. A contributor donates an amount in **cryptocurrency** to a Collective that doesn't have cryptocurrency:
    - // To do 

3. A contributor donates an amount in **fiat** to a Collective that only has a **cryptocurrency**(same *coin* as the donation) **Wallet**.
    - // To do

**Comment by piamancini** [comment]
@marcogbarcellos making some updates on your core issue. Thanks for starting this!

**Comment by piamancini** [comment]
The lowest hanging fruit would be for a collective to have a wallet with a single coin as a host
Collective X gets created via the self serf flow, when setting up a host the option is enabled to add a wallet and chose a coin. 
This will automatically set up budget/contribution in that coin denomination. 
When expenses are filed, user converts the expense amount (if in fiat) to the collective's coin.

V2: might be multiple coins or fiat + coin. 
Challenge here is figuring out  the budget. Is it a consolidated budget? 
Or do we have several budgets in parallel? (this seems easier and it's what you see in any wallet today)
Challenge is being able to submit expenses agains one of the denominations.  User who submit expense can choose if they prefer to get paid in crypto (and which) or fiat. 
Collective admin can approve / reject request for this currency.

**Comment by piamancini** [comment]
> Zcash foundation(an organization) wants to donates zcash(cryptocurrency) to collectives
> Potentially a grant would go to Open Collective Company to develop compatibility.

ZCash poses an additional challenge because of their shielded addresses.

**Comment by acityinohio** [comment]
Thanks for adding me to the thread @piamancini! Agree that the lowest hanging fruit option is the best way to start, as things start to get quite complicated when dealing with conversion and multiple coins.

On the ZEC side, it does present more challenges due to shielded addresses, although it also preserves donators' privacy which (depending on the project) can be a very welcome addition. The concept of "view keys" in Sapling would still allow projects to show balances which would be another welcome addition.

If we can arrange for the Zcash Foundation to support this I'd very much encourage prioritizing ZEC and BTC support first (along with those nice Sapling ZEC features like fast shielded addresses and view keys), then other arbitrary cryptocurrencies later.

If it helps @marcogbarcellos here's a guide about upgrading to Sapling on the ZEC side: https://zcash.readthedocs.io/en/latest/rtd_pages/nu_dev_guide.html#sapling

**Comment by aparcar** [comment]
:(
