### ISSUE TITLE
Move dns to another digital ocean box

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#136]
Off of xdamman's personal box and onto an OC box. Add credentials to vault for any of us to log in.

**Comment by xdamman** [comment]
Login: ops@opencollective.com
Password: in 1password

You should add your ssh key to be able to access the box.

I've already updated Cloudflare. All done.
In case there is any issue, `/etc/init.d/nginx restart` is your friend.

**Comment by asood123** [comment]
Should we be sharing the password publicly?
