### ISSUE TITLE
"How it works" and "Discover" links in footer don't work

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1361]
**Describe the bug**
`How it works` and `Discover` links in footer don't work. They are however functional when clicked from top navbar (which still use regular `<a href=".../>`, not router `Link` components)

**To Reproduce**

![Preview](https://user-images.githubusercontent.com/1556356/46908218-0a174380-cf20-11e8-9f65-b13fd5b7c4e6.png)

------

Linked to #1294

**Comment by znarf** [comment]
They should be turned to normal links. Because they are handled from another codebase (legacy).

We still need to integrate these 2 pages in the regular frontend codebase.
