### ISSUE TITLE
Is PayPal supported?

### ISSUE THREAD

**Issue by paladox** [opencollective/opencollective#1362]
Hi, im wondering is PayPal supported? Since 
https://github.com/opencollective/opencollective/wiki/Paypal shows "No Longer in Use" .

**Comment by Betree** [comment]
Hi @paladox sorry for replying so late on this one we just missed it :disappointed: PayPal is supported for one-time donation to collectives hosted by the [opensource collective](https://opencollective.com/opensource). We're currently updating our documentation system to have more coherency and ensure we're up to date.

**Comment by theAkito** [comment]
Will this be available for recurring donations, as well?
