### ISSUE TITLE
Backer reported as sponsor in a Readme

### ISSUE THREAD

**Issue by MichaelMure** [opencollective/opencollective#1368]
Github readme: https://github.com/MichaelMure/git-bug
Collective page: https://opencollective.com/git-bug

**Describe the bug**
The backer "TLDR Newsletter" is correctly reported as a baker on the Collective page. However, it's listed as a sponsor in the readme integration.

Likely related, no backers at all are listed on the readme, despite the collective having 2.

Happen on all device I had access to, even after a cache clear.

**Comment by znarf** [comment]
This is happening because there is for historical reasons conflicting definitions of "Backers" and "Sponsors".

1) Tiers based: in your case $5+ -> "backer" $100+ -> "sponsor"
2) Type based: Supporting individual -> Backer, Supporting organization -> Sponsor

In your Readme, this is the second definition that is currently used.

What I think is needed here: the ability for you to setup your Readme with the first definition.

**Comment by MichaelMure** [comment]
Am I right to understand it's not possible currently?

**Comment by znarf** [comment]
@MichaelMure You're understanding right! However, I think this is an important problem that should be prioritized, and it doesn't seem to be too difficult to build. So stay tuned.

**Comment by kroitor** [comment]
@znarf any updates on this issue? We seem to be affected too, though, with a slightly different result – we have backers listen in sponsors. It would be great to see it fixed. Also, can we possibly fix this by reorganizing our tiers to some "standard" or "new" way that would be handled by opencollective properly without an error? Or it won't make a difference?

**Comment by znarf** [comment]
@kroitor No update but this is something that is still on top of our TODO.

**Comment by znarf** [comment]
@kroitor followed up here: https://github.com/ccxt/ccxt/pull/4507

**Comment by znarf** [comment]
@MichaelMure followed up here: https://github.com/MichaelMure/git-bug/pull/92

**Comment by MichaelMure** [comment]
@znarf It's better: for my project, "SIT" correctly appears as a backer. Although, shouldn't "TLDR Newsletter" be removed as it dropped out of being a backer ? Last payment was 3 months ago.

**Comment by znarf** [comment]
@MichaelMure Ok, I'll check.

**Comment by znarf** [comment]
We're taking care of that in https://github.com/opencollective/opencollective/issues/2116

**Comment by kroitor** [comment]
@znarf thank you!
