### ISSUE TITLE
github flow errors 

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#137]
cc / @asood123 @carlosascari from user mehdy dara: 

I have a Github organization (https://github.com/FountainJS) with a main entry repo (https://github.com/FountainJS/generator-fountain-webapp).

I try to add this project to OpenCollective by following the button "Apply Now" in https://opencollective.com/opensource.
Everything works well until the last step 3/3.
Yesterday I submit by "Create" button but the server respond with error 500.
Today the server respond with error 400
```{
    "error": {
        "code": 400,
        "type": "validation_failed",
        "message": "Unique Constraint Error.",
        "fields": [
            "GroupId",
            "UserId",
            "role"
        ]
    }
}
Maybe the error 500 save Fountain in your DB and now we can't finish submitting.

PS: I am seeing 8 separate groups created under the same name.

**Comment by zckrs** [comment]
>PS: I am seeing 8 separate groups created under the same name.

Sorry I tried many times.

**Comment by piamancini** [comment]
No worries! It's on our end if it's letting you do it. :)

**Comment by carlosascari** [comment]
Related Issue 
https://github.com/OpenCollective/OpenCollective/issues/140

PR
https://github.com/OpenCollective/opencollective-website/pull/302

**Comment by asood123** [comment]
Fixed: https://github.com/OpenCollective/opencollective-api/pull/462
