### ISSUE TITLE
New → Marketing page for /fiscal-sponsorship

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1370]
A lot of organizations are already experiencing the pain of fiscal sponsorship.
We have developed a great software to stream line that process. But we aren't communicating about it!

So we would love to create a marketing page to present Open Collective as a platform for managing fiscal sponsorship.

The target audience of that page are non profit organizations that are interested in fiscal sponsorship.
Many have likely already experienced the pain of keeping track of expenses and budgets for all the different projects that they are fiscally sponsoring.

The call to action is to contact us (and set up a call) 

One illustration that I like is showing this
![](https://d.pr/free/i/7ulTOG+)

to highlight the fact that there is one common legal entity that takes care of all the overhead for everyone (and the open collective platform that enables all collectives to have their own independent budget)

Copy:
https://docs.google.com/document/d/1rmqcoe3Z_KNxAheV3DnNlW5ctNKEFJZq62A4hRuxBac/edit?usp=sharing

**Comment by cuiki** [comment]
Hi everyone, update:

I decided to scrap the illustration I was working on cuz it wasn't working so I tried a header based on the graphic that Xavier Damman suggested in the issue's description. I didn't go further to implement all the graphics so you can:

a) Comment on the information architecture.
b) Help me figure out the best way to choose how to illustrate this page with so many features listed.

![become a fiscal sponsor](https://user-images.githubusercontent.com/981188/49018109-27127980-f150-11e8-9b22-1264ceb84509.png)

**Comment by cuiki** [comment]
FIGMA link: https://www.figma.com/file/eqgZAUzzaTGcW2T2oilV20/04.-Platform-Become-a-fiscal-host?node-id=0%3A1

**Comment by piamancini** [comment]
what's the status of this? It seems like we dropped it

**Comment by cuiki** [comment]
Picking up:

Latest update on the heading area. Front-end contractor is working on implementing the update.

![update](https://user-images.githubusercontent.com/981188/55452222-e6aa8880-5593-11e9-80db-68bd85435598.png)

**Comment by cuiki** [comment]
@piamancini, @xdamman, @alannallama we need the copy-write to describe the role of the fiscal host in the hero section (main header block).

**Comment by alannallama** [comment]
@cuiki I'm keen to work with you on this. What's the easiest way for me to edit the existing text or give you changes?

**Comment by alannallama** [comment]
@cuiki @znarf I have updated the text and committed the changes.

I also suggest these small changes (which I haven't made because I didn't want to break anything):

* Link the case studies to the relevant case study articles: [Women Who Code](https://medium.com/open-collective/women-who-code-powering-up-an-international-network-with-local-crowdfunding-78ccf5d3c725), [Operation Code](https://medium.com/open-collective/open-source-is-the-next-mission-for-these-soldiers-8648496eef65), and [Brussels Together](https://medium.com/open-collective/turning-our-city-into-an-open-collective-93d107f0f86a).
* At the bottom, instead of 'contact us' how about 'find out more' which links to the [fiscal hosting docs](https://docs.opencollective.com/help/hosts).

**Comment by alannallama** [comment]
Is this live now?

**Comment by alannallama** [comment]
@znarf @cuiki where has this got to? I would really like it to go live now.

**Comment by cuiki** [comment]
It looks like it is live already: https://opencollective.com/become-a-fiscal-host

**Comment by alannallama** [comment]
Oh cool! It looks good!

Can the small changes I suggested [here](https://github.com/opencollective/opencollective/issues/1370#issuecomment-483487794) be made?

**Comment by alannallama** [comment]
A user has pointed out that the contact link at the bottom is broken as well. 

@Betree or @znarf can you please make the small changes described in this thread? I want to start using this page publicly but these fixes need to go in first.

**Comment by Betree** [comment]
@alannallama On it

**Comment by znarf** [comment]
Closing!
