### ISSUE TITLE
Show latest updates across all collectives

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1371]
It would be good to have a page to list all the latest updates across the platform but also within a host / collection of collectives (e.g. https://opencollective.com/opensource, https://opencollective.com/brusselstogether)

This will also incentivize people to post updates has it will give their collective more visibility.

This could be a section like "Next events" that we have today on the page of a collective.

**Comment by jeans** [comment]
I agree, this is kind of missing. As a logged-in user you click on the OC logo, go to home and then you're asked to join the movement - just like any other anonymous, first time visitor. 

1. a simple activity-stream that only displays latest updates from the collectives you're backing, maybe with filters for transactions, updates, events in a second step
2. the same activity-stream on every collective page, but with updates from this collective only, obviously
