### ISSUE TITLE
View Details broken in personal transactions

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1372]
**Describe the bug**

An unexpected error is occurring when clicking the "View Details" link in personal transactions.

**To Reproduce**

1. Authenticate
2. Go to your personal transactions
3. Click "View Details" 

**Happening**

`An unexpected error has occurred.`

**Expected**

No error

**Screenshots**

![screen shot 2018-10-22 at 14 59 16](https://user-images.githubusercontent.com/806/47293822-8dfdb980-d60b-11e8-890c-f4ec8ccc65ff.png)

![screen shot 2018-10-22 at 15 01 35](https://user-images.githubusercontent.com/806/47293826-90f8aa00-d60b-11e8-9dca-13f1533bcf0b.png)

**Comment by xdamman** [comment]
Not sure why this didn't get closed automatically 10 days ago. Closing now.
