### ISSUE TITLE
CSS is broken in montlhy consolidated invoice 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1374]
**Describe the bug**
Css is broken 

**To Reproduce**
Download a monthly invoice in from the Open Source Collective 

**Expected behavior**
A decent looking invoice with no css issues - specially title and broken logo in the footer
![screen shot 2018-10-22 at 12 42 17 pm](https://user-images.githubusercontent.com/3671070/47305722-63eecc00-d5f8-11e8-9d0e-abc3a0516bf2.png)

**Comment by HipsterBrown** [comment]
@piamancini Can you include a link to that invoice to view in the browser?
