### ISSUE TITLE
Paypal payment does not go through

### ISSUE THREAD

**Issue by johnpeterm** [opencollective/opencollective#1376]
**Describe the bug**
When I make payment through Paypal, the payment does not go through and it gives the following error
![image](https://user-images.githubusercontent.com/20897821/47504189-5e5be500-d889-11e8-908a-eb6e34f4dc3f.png)

**To Reproduce**
Go to this link and make payment through paypal https://opencollective.com/pressbooks/donate

**Expected behavior**
Payment does not go through and gives error

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcogbarcellos** [comment]
Hi @johnpeterm , I really appreciate you taking the time to report this issue. I couldn't reproduce the problem locally, would you mind about giving us some more details. For example: Did the problem occur when you clicked in the paypal button or you were able to see the paypal login popup, and then you logged in and authorized the payment and the error showed up? I would really appreciate more informations.

Once more thanks!

**Comment by johnpeterm** [comment]
Steps
1.open the link https://opencollective.com/pressbooks/donate
2.login or if you are already logged in, it will show the pressbook detailed page
3.Select or enter the price
4.Choose paypal as payment method and click
5.Paypal pop up opens and enter card details and click pay
6.Returns back to opencollective dashboard with the message
"An error occured 😳. The order didn't go through. Please try again in a few.: Error: GraphQL error: Bad Request"

**Comment by marcogbarcellos** [comment]
Hey @johnpeterm , Thanks once more. so I tried reproducing locally your problem and wasn't able to. Then I just tried using my own paypal in Production and was able to make the payment:
I've donated 10USD to mongoose. You can see the donation listed here: https://opencollective.com/mongoose/transactions

![screen shot 2018-10-26 at 6 56 49 am](https://user-images.githubusercontent.com/8717041/47562416-58e3b680-d8ec-11e8-81cc-b1251f86ae5d.png)

At this point I believe that the problem may be something related to either paypal or the credit you tried to use on paypal. I would recommend you at least to give a try with another card or payment method inside paypal or even use the credit card option in our own platform as well. 
In the meantime I think this error message is not even close to be "user friendly" and we're going to try to improve it.

I'm really sorry about your issue but I hope everything will work out on your new try. let us know and thanks once again 👍
