### ISSUE TITLE
Should return http code 404 for nonexistent pages

### ISSUE THREAD

**Issue by limonte** [opencollective/opencollective#1377]
**Describe the bug**

It's essential to use http codes properly, especially 404 :) 

Some background: I'm planning to add automated checks for nonexistent OpenCollective pages for https://github.com/feross/thanks

Right now, it's impossible because every page, even nonexistent, returns 200.

**To Reproduce**

```sh
 curl -sI https://opencollective.com/blah-blah-blah
```

**Actual behavior**

`HTTP/2 200`

**Expected behavior**

`HTTP/2 404`

**Screenshots**

![image](https://user-images.githubusercontent.com/6059356/47549654-62c5e380-d905-11e8-856a-affef38e9772.png)

**Comment by znarf** [comment]
Also reported as https://github.com/opencollective/opencollective/issues/1369

I haven't found an easy fix for that yet (using Next.js).

An alternative is to use our GraphQL API for that, https://medium.com/open-collective/open-collective-graphql-api-preview-3b42ed1d55ff

**Comment by znarf** [comment]
Closing, let's track that in https://github.com/opencollective/opencollective/issues/1369
