### ISSUE TITLE
Users unable to edit expenses

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1378]
I have received multiple reports from users when I ask them to update an expense (to correct an invoice for example) that they can't see the 'edit' option. They've confirmed they are logged in and are the users who created the expense. I show them a screenshot of where the link should be, and they say they can't see it at all.

**Comment by marcogbarcellos** [comment]
Hi @alannallama , can you give me some more details. I'd like to know at least the status(Pending, Approved, etc) of the expenses you're talking about. I remember that once you asked me to change the payment method of an expense but as it was approved I couldn't do much at that point. I believe you can only edit an expense when it's **pending**.

In my opinion we could change the whole workflow but if someone changes an expense that was already approved the status of that expense should change to **pending** again. let me know if you have any thoughts.

**Comment by alannallama** [comment]
@marcogbarcellos what should we do in [this circumstance happening now](https://opencollective.com/vuejs/expenses/5437)? They need to change the type to paypal and input their address. Do I have to get them to email me their paypal email (because they might want to write it privately) and then edit it myself? It's a real problem if the users can't fix errors themselves.

**Comment by piamancini** [comment]
I think anyone should be able to edit their own expense and the status should go back to 'pending' and needs to be re-approved by either an admin of the host (if it was approved previously and the amount didn't change, I think this is ok to do) or a core contributor of the collective.  
(I thought this was the current behavior).

**Comment by marcogbarcellos** [comment]
Thanks for the input @alannallama , imo this is an important discussion: define how the expense workflow will be(including editions on expenses that were already approved). having @piamancini and @xdamman involved in this discussion seems interesting.

For the VUE case , the user is question has already his paypal email on file(I have just checked in production) so to solve this problem quickly I can just edit the payment method to paypal and it should be alright for this expense. However, if the user hadn't the paypal you'd need to ask him in private, so we should also think on this use case.

Do you want me to edit this expense to change the payment method to paypal @alannallama ? As soon as you approve, i'll do that.

**Comment by marcogbarcellos** [comment]
@alannallama through what I understood from the issue, It was kinda clear the user was ok about changing the payment method to paypal and that's what I did. Let me know if it's ok now or you want me to change something more. I've also created an issue detailing how the expense workflow should be so we can fix this edition problem.

Thanks.

**Comment by alannallama** [comment]
OK that one is now paid, thanks @marcogbarcellos 

@piamancini yes, if you edit an expense it goes back to pending, and I think that's the right behavior.

If this is complex, let's add it to the overall expense flow redesign work. If it's an easy change to extend permissions for editing to the user who created an expense, it would be great if it could be changed sooner, because this comes up all the time.

**Comment by marcogbarcellos** [comment]
Cool, I'm closing this issue as we'll follow up with the #1384 to solve this expense workflow. thanks @alannallama
