### ISSUE TITLE
Wrong currency recorded when refunding a transaction in GBP

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1380]
I had to refund the last transactions on https://opencollective.com/norwichsharingcity/transactions which a collective hosted on Open Collective UK in GBP.

The refunds worked all good (we double checked in the Stripe account) but the transactions had the USD currency in our database. It's probably because it used the currency of the `FromCollectiveId` of the donor which is by default USD.

FYI I had to run this query to fix the transactions:

```sql
UPDATE "public"."Transactions" SET "currency"='GBP' WHERE "id"=126592 OR "id"=126591 OR "id"=126590 OR "id"=126589 OR "id"=126588 OR "id"=126587 OR "id"=126586 OR "id"=126585 OR "id"=126584 OR "id"=126583
```

**Comment by znarf** [comment]
@xdamman what's the update on this?

**Comment by xdamman** [comment]
I have no idea. I just reported the issue.

**Comment by znarf** [comment]
It's stale.
