### ISSUE TITLE
Onboarding new core contributors

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1388]
- [x] email address 
- [x] add to google groups
- [x] add to slack team & howdy 
- [x] add to standups / working days calendar
- [ ] announce in newsletter
- [ ] set up peer programming sessions during the first week(s)
- [ ] invite to figma 

cc / @znarf 
@xdamman can you please generate benjamin@opencollective.com? thanks!

**Comment by znarf** [comment]
Let's maybe have this list out of an issue? Projects might be a good way to do that.

**Comment by piamancini** [comment]
done https://github.com/opencollective/opencollective/projects/5
