### ISSUE TITLE
Pledge flow improvements

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1389]
It's quite deceiving that we let people fill out the form just to realize that they cannot go any further without logging in (and lose all the info they already entered in the process).
![](https://d.pr/free/i/HJIE23+)
Can we either force the user the log in first or (better) ask for the email as part of the form and only record the pledge after email confirmation?

Also would be good to suggest to make a pledge from the 404 page (e.g. search for "wikipedia" or "make a pledge to "wikipedia")

**Comment by HipsterBrown** [comment]
> Can we either force the user the log in first or (better) ask for the email as part of the form and only record the pledge after email confirmation?

I remember blocking the form if the person is not logged in at one point while developing. Not sure what happened to that change but I can add it fairly quickly. 

> Also would be good to suggest to make a pledge from the 404 page

We currently have the suggestion to search by the collective slug in the 404 page, which will have the pledge call-to-action button.
