### ISSUE TITLE
backers are seeing the refund button on their profile 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1390]
backer made a donation with the wrong profile and hit the refund button so he could made the donation again with the right profile.  It's unclear  for the user is the refund went through or not. From the data base it seems like it didn't. 
Users shouldn't see a refund button until there's an agreement on how and if users we'll issue refunds.

**Comment by xdamman** [comment]
FYI, right now only the ROOT users can refund a transaction but we had decided that we should allow the author of a transaction to refund themselves within 24h and that we should also allow the admins of the host to do it anytime. But we haven't implemented any of those scenarios.
I'd argue that we should also allow the admins of the collective to do it (maybe with a time limit of 1 month?)
The more we enable trusted parties to do admin tasks, the less support for us.

See: https://github.com/OpenCollective/opencollective-api/blob/c7e493123169a5f4f7601edb676f6e7c45291642/server/graphql/v1/mutations/orders.js#L571-L575

In the meantime, I'll fix the frontend to reflect that only root users should be able to refund transactions.
