### ISSUE TITLE
Capitalisation of titles not honoured by email reports...

### ISSUE THREAD

**Issue by dahacouk** [opencollective/opencollective#1391]
**Describe the bug**
Capitalisation of titles not honoured by email reports.

**To Reproduce**
Check any report emails coming from a collective.

**Expected behavior**
I'd expect capitalisation of titles to be honoured by email reports.

**Screenshots**
I'd expect the each word of "World Peace Now" to be capitalised.
<img width="632" alt="inbox__115_messages__5_unread_" src="https://user-images.githubusercontent.com/201752/47857684-310bbb80-dde2-11e8-9b00-b137b7393506.png">

**Desktop (please complete the following information):**
 - Any

**Smartphone (please complete the following information):**
 - Any

**Additional context**
None.

**Comment by Betree** [comment]
Template (`opencollective-api/templates/emails/collective.monthlyreport.hbs`) uses `capitalize` which, [according to the docs](https://github.com/helpers/handlebars-helpers#capitalize) capitalize only the first letter and downcase the rest.

We could switch to [`capitalizeAll`](https://github.com/helpers/handlebars-helpers#capitalizeall) which would produce the desired result, but it seems we should keep the original format here and not change the existing case.

**Comment by znarf** [comment]
@xdamman We suggest to drop `capitalize`? Ok?

Alternative is to use `capitalizeAll` but we think it's better on the long term to not touch capitalization and use the name as it's stored.

**Comment by znarf** [comment]
@xdamman Any opinion?

**Comment by znarf** [comment]
@xdamman taking it for tomorrow then!

**Comment by dahacouk** [comment]
Agree with @znarf "use the name as it's stored". So does that mean World Peace Now is stored as "World Peace Now" or "World peace now"? Because I thought it was stored as "World Peace Now". I mean I never write it as "World peace now". Thanks for your work on this.
