### ISSUE TITLE
Approved expenses but not paid

### ISSUE THREAD

**Issue by Carodem** [opencollective/opencollective#1393]
Hello ! 

On HuNeeds page (https://opencollective.com/huneeds#team).
Some of my expenses were paid but others only approved (older expenses than the paid ones). 
3 approved expenses are still pending for payment (3 x 22,95€ for June, July and August).
![capture d ecran 2018-11-01 a 16 49 27](https://user-images.githubusercontent.com/36923849/47863370-640c7a00-ddf7-11e8-90ed-ab61430d69cc.png)
![capture d ecran 2018-11-01 a 16 49 34](https://user-images.githubusercontent.com/36923849/47863376-68389780-ddf7-11e8-868b-7303111fd724.png)

Thank you !

**Comment by znarf** [comment]
Hi @Carodem, thank you for contacting us. Was that processed since you reported the issue? Please contact support@opencollective.com if that's not the case.

**Comment by Carodem** [comment]
Hello, not it wasn't processed yet... Thanks !
