### ISSUE TITLE
Error when completing a pledge and funding from a collective

### ISSUE THREAD

**Issue by sloria** [opencollective/opencollective#1394]
**Describe the bug**

**To Reproduce**
1. Click on "Complete My Pledge"
2. Change "Contribute as" to a collective
3. Click "donate"

**Expected behavior**

**Screenshots**

<img width="400" alt="image" src="https://user-images.githubusercontent.com/2379650/47891755-f37f5080-de2a-11e8-9b73-84c7197b9902.png">

----

<img width="400" alt="image" src="https://user-images.githubusercontent.com/2379650/47891770-03973000-de2b-11e8-9897-c317d165a3a6.png">

------

<img width="500" alt="image" src="https://user-images.githubusercontent.com/2379650/47891650-8b306f00-de2a-11e8-917e-f37e5d316031.png">

**Desktop (please complete the following information):**
 - OS: macOS 
 - Browser: Firefox 63.0 
 - Version: 10.14 (18A391)

**Additional context**

Using the normal "Contribute" flow from a collective page works as expected. I only see the above error when completing a pledge.

**Comment by HipsterBrown** [comment]
Thanks for creating an issue @sloria. I'll look into this today.

**Comment by HipsterBrown** [comment]
@sloria Can you provide a link to the pledge completion form so I can get the id of order in the database?

**Comment by sloria** [comment]
@HipsterBrown sure thing. https://opencollective.com/pledges/16923

**Comment by HipsterBrown** [comment]
@sloria I just tried it on our staging area and was able to complete the pledge. Can you share a full screenshot of the pledge form in your view? 

I think it may have been a race condition between updating the pre-commit collective with a host and the completing of the pledge.

**Comment by sloria** [comment]
@HipsterBrown I'm not able to reproduce the issue since I already went through the normal contribution flow on pre-commit's collective.

I didn't change anything else on the form except for the two fields in my screenshots above ("Contribute As" and "Credit Card").

**Comment by HipsterBrown** [comment]
While working with @piamancini, we figured out the issue. I'm working on a patch now.

**Comment by HipsterBrown** [comment]
@sloria The fix has been deployed to production. Thanks again for creating this report. 👍

**Comment by sloria** [comment]
@HipsterBrown Thanks for the quick resolution!
