### ISSUE TITLE
Super slow query to get balance of logged in user's payment methods

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1395]
This is incredibly slow: 
https://github.com/OpenCollective/opencollective-api/blob/c7e493123169a5f4f7601edb676f6e7c45291642/server/graphql/v1/CollectiveInterface.js#L1189

- [ ] add an index `PaymentMethodId_deletedAt` to the `Transactions` table.
- [ ] Refactor to execute this in parallel and not in series (`Promise.all`) or, better, use a `loader`

**Comment by xdamman** [comment]
Also, it's weird that you compute the balance for cards that you may never return:
https://github.com/OpenCollective/opencollective-api/blob/c7e493123169a5f4f7601edb676f6e7c45291642/server/graphql/v1/CollectiveInterface.js#L1197
(I'd make sure you don't compute the balance for more than `args.limit` cards)

**Comment by znarf** [comment]
@xdamman @marcogbarcellos can you share a sample SQL query to see what we're talking about?

**Comment by xdamman** [comment]
```sql
  psql -------------------- <query> --------------------
  psql  Executed (default): SELECT "amountInHostCurrency", "paymentProcessorFeeInHostCurrency", "platformFeeInHostCurrency", "hostFeeInHostCurrency" FROM "Transactions" AS "Transaction" WHERE (("Transaction"."deletedAt" > '2018-11-07 10:04:56.901 +00:00' OR "Transaction"."deletedAt" IS NULL) AND ("Transaction"."type" = 'DEBIT' AND "Transaction"."PaymentMethodId" = 8472));
-------------------- </query executionTime="1022"> --------------------
 +0ms
  psql
  psql -------------------- <query> --------------------
  psql  Executed (default): SELECT "amountInHostCurrency", "paymentProcessorFeeInHostCurrency", "platformFeeInHostCurrency", "hostFeeInHostCurrency" FROM "Transactions" AS "Transaction" WHERE (("Transaction"."deletedAt" > '2018-11-07 10:04:57.241 +00:00' OR "Transaction"."deletedAt" IS NULL) AND ("Transaction"."type" = 'DEBIT' AND "Transaction"."PaymentMethodId" = 14228));
-------------------- </query executionTime="1021"> --------------------
 +0ms
  psql
  psql -------------------- <query> --------------------
  psql  Executed (default): SELECT "amountInHostCurrency", "paymentProcessorFeeInHostCurrency", "platformFeeInHostCurrency", "hostFeeInHostCurrency" FROM "Transactions" AS "Transaction" WHERE (("Transaction"."deletedAt" > '2018-11-07 10:04:56.902 +00:00' OR "Transaction"."deletedAt" IS NULL) AND ("Transaction"."type" = 'DEBIT' AND "Transaction"."PaymentMethodId" = 12091));
-------------------- </query executionTime="1022"> --------------------
```

**Comment by xdamman** [comment]
Each of those queries takes more than one second on my computer and it's repeated for every single collective that I'm an admin of. It makes it impossible for me to be logged in locally.

**Comment by znarf** [comment]
@xdamman Look like they are executing fast ~100ms. Are you sure you're not misinterpreting the output in the console?

**Comment by xdamman** [comment]
see above, each of those queries take more than 1000ms because it's doing a full table scan on the `Transactions` table because there is no index on `PaymentMethodId`
