### ISSUE TITLE
Super slow queries

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1396]
You can run the backend with `DEBUG=psql npm run dev` to see all the queries with their execution time in ms. Queries shouldn't take more than 1s. You may want to see if we shouldn't add some indexes or loaders.

This is just to load the page `http://localhost:3000/uk`
(might also be related to my current logged in user: xdamman)

  psql -------------------- <query> --------------------
  ```sql
SELECT COALESCE(SUM("amount"), 0) AS "total" 
FROM "Transactions" AS "Transaction" 
WHERE (("Transaction"."deletedAt" > '2018-11-02 21:38:37.682 +00:00' OR "Transaction"."deletedAt" IS NULL)
  AND ("Transaction"."amount" > 0 
  AND "Transaction"."createdAt" < '2018-11-02 21:38:37.677 +00:00'
  AND "Transaction"."CollectiveId" = 302))
LIMIT 1;
```
-------------------- </query executionTime="3208"> --------------------
 

  psql -------------------- <query> --------------------
  psql  Executed (default): 
```sql
SELECT "CollectiveId", COALESCE(SUM("netAmountInCollectiveCurrency"), 0) AS "balance" 
FROM "Transactions" AS "Transaction" 
WHERE (("Transaction"."deletedAt" > '2018-11-02 21:38:37.694 +00:00' OR "Transaction"."deletedAt" IS NULL) 
  AND "Transaction"."CollectiveId" IN (302)) 
GROUP BY "CollectiveId";
```
-------------------- </query executionTime="3196"> --------------------
 

  psql -------------------- <query> --------------------
  psql  Executed (default): 
```sql
SELECT "Transaction"."CollectiveId", COUNT(DISTINCT("FromCollectiveId")) AS "count", "fromCollective"."type" 
FROM "Transactions" AS "Transaction" 
INNER JOIN "Collectives" AS "fromCollective" ON "Transaction"."FromCollectiveId" = "fromCollective"."id" 
  AND ("fromCollective"."deletedAt" > '2018-11-02 21:38:37.695 +00:00' OR "fromCollective"."deletedAt" IS NULL) 
WHERE (("Transaction"."deletedAt" > '2018-11-02 21:38:37.695 +00:00' OR "Transaction"."deletedAt" IS NULL) 
  AND ("Transaction"."CollectiveId" IN (302)
  AND "Transaction"."type" = 'CREDIT')) 
GROUP BY "fromCollective"."type", "CollectiveId";
```
-------------------- </query executionTime="3202"> --------------------

**Comment by marcogbarcellos** [comment]
Some suggestions(not necessarily all of them together and respectively) on how we can approach this issue:

- Create effective indexes on the related table
- Improve/simplify query
- Look for caching solution through either sequelize or directly on the project itself
- Create views on the database
- Identify the slowest queries(not only for one user but in general) and run jobs to store straight results.

**Comment by znarf** [comment]
@xdamman I tested all 3 queries and they all execute in ~100ms.
