### ISSUE TITLE
White collective logos don't show up in thumbnail view

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1400]
See https://opencollective.com/wwcode#members

Most of these collectives have a while logo because on their collective page the background is colored. But in the thumbnail view, it just looks like a bunch of blanks. I suggest the thumbnail background takes the same color/image as the collective header background.

**Comment by znarf** [comment]
I think these should have a default (colored) background. That should solve the issue.

**Comment by Betree** [comment]
Looks like we fixed that 

![image](https://user-images.githubusercontent.com/1556356/51685248-35650080-1fee-11e9-8414-833469a65dd0.png)
