### ISSUE TITLE
Paypal platform fees

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1401]
Unlike Stripe, Paypal doesn't allow us to automatically take our 5% platform fee.
So we have to manually bill the host for the platform fees. 

Right now, Paypal has been hard coded for the open source collective.

Here is a query to monitor the total amount of platform fees that we should bill the open source collective:

```sql
SELECT 
  substring(cast(DATE_TRUNC('month', t."createdAt") as text) from 1 for 7) as month,
  max(hc.slug) as "host",
  max(pm.service) as "payment method",
  max(t.currency) as currency,
  count(t.id) as "number of donations",
  sum(t.amount) / 100 as "total amount",
  -sum("platformFeeInHostCurrency") / 100 as "platformFees"
FROM "Transactions" t
LEFT JOIN "PaymentMethods" pm ON t."PaymentMethodId" = pm.id
LEFT JOIN "Collectives" hc ON t."HostCollectiveId" = hc.id
WHERE pm.service = 'paypal'
  AND t."deletedAt" IS NULL
  AND t.type = 'CREDIT'
  AND t."OrderId" IS NOT NULL
GROUP BY month, t."HostCollectiveId"
ORDER BY month DESC
```

Total: $817 from June 2018 till October 2018 included.
@piamancini can you pay that? 
You can use this link: https://opencollective.com/opencollective-company/pay/817/Platform%20fees%20for%20Paypal%20donations%20June-October%202018

![](https://d.pr/free/i/cz2JoA+)

Ideally we would love to automate this process.
But we would also love enable all hosts to accept donations with PayPal.

**Comment by piamancini** [comment]
The correct process to pay is for open collective to submit an invoice to the open source collective in opencollective.com/opensource 
This payment is not a donation.

**Comment by znarf** [comment]
This is taken care of.
