### ISSUE TITLE
"donate/pay our collective" button with custom redirect

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1402]
When I talked to @andrew and @benjam from the [Octobox collective](https://opencollective.com/octobox) at [Sustain](https://opencollective.com/sustainoss), they expressed the need to be able to redirect people from [their website](https://octobox.io) to their open collective to pay and then being redirected back with a way to know if their payment went through.

That's actually something that we had back in the days but nobody really used it:
https://github.com/OpenCollective/OpenCollective/wiki/API#redirect-people-to-your-website-after-a-donation (it's broken today).

Would something like that old implementation work for you @benjam @andrew? Please let us know what would work and if we know it's going to be used, we will prioritize this.

**Comment by andrew** [comment]
@xdamman that sounds perfect 👌

**Comment by andrew** [comment]
@xdamman following those docs, I get a 404 when redirecting users to a payment page on OC: https://opencollective.com/octobox/donate/100/month/individual?redirect=https://octobox.io/callback Am I missing a step?

**Comment by Betree** [comment]
Hi @andrew, sorry about that. We're currently preparing the ground for the new contribution flow and we've accidentally deprecated this URL scheme. 

You should be able to make it work by using this URL instead:
> https://opencollective.com/octobox/donate?amount=100&interval=month&description=individual&redirect=https://octobox.io/callback

Please tell me if you need any additional help.

**Comment by andrew** [comment]
@Betree thanks!
