### ISSUE TITLE
Credit Card Payments not working in Staging environment

### ISSUE THREAD

**Issue by marcogbarcellos** [opencollective/opencollective#1407]
**Describe the bug**

Not able to use credit cards In the **staging** environment.

**To Reproduce**
1. Go to https://staging.opencollective.com
2. Go to a collective
3. Try to pay with a credit card
4. See error:
![screen shot 2018-11-06 at 8 54 53 pm](https://user-images.githubusercontent.com/8717041/48105671-66f7d800-e206-11e8-9cdb-cf5c6836ec50.png)

**Expected behavior**
The payment should work, according to [stripe testing docs](https://stripe.com/docs/testing), if we use `customerId=null` and `token=tok_visa` so we could check if the `process.env.NODE_ENV=='staging'` and then return those values.

**Comment by znarf** [comment]
@marcogbarcellos I don't see that in stripe documentation, in which section is it?

Sounds like a mismatch between Stripe's live API Key (or IDs created with it) and Stripe's test API Key.

**Comment by marcogbarcellos** [comment]
@znarf the tokens and cards list are in the link:
![screen shot 2018-11-07 at 8 46 04 am](https://user-images.githubusercontent.com/8717041/48134985-a572ae80-e269-11e8-8900-37a12f8ad27c.png)

And regarding the customerId I didn't find it on their docs but figure out trying by myself if we set it to null on our end, stripe will "understand". I think the Stripe API Key is already correct for the Staging environment but it's something I(or someone who works on this one) can look as well.

**Comment by znarf** [comment]
@marcogbarcellos before doing anything complicated, you need to nail the real issue. My point: if it's working locally (it does), it should works on staging too, nothing to change.

You need to investigate the customer id ( in your example `cus_CvEP...`). Where does it come from? Why is it a live customer id?

**Comment by marcogbarcellos** [comment]
Yeah @znarf , i've spent some time trying to figure that out and still wasn't able to get that. I've tried looking for the stripe env Vars , setting the staging ones locally to see if I could reproduce the problem. as it took me more time than I thought i hope i'll finish it next bug fix fridays. will keep you on the loop, thanks.

**Comment by znarf** [comment]
I don't think that's worth working on it.

If you want to test payments, then add cards in the staging environment.
