### ISSUE TITLE
Update card details doesn't work

### ISSUE THREAD

**Issue by GazCloud** [opencollective/opencollective#1409]
When updating card details on an existing contribution, once all details are entered, the "save" button does not light up. In order to update my details, I had to cancel my subscription and re-affiliate with the page in question.

**Comment by znarf** [comment]
@GazCloud Thank you for reporting that. Can you try again?

If this doesn't work can you make a video of it? Alternatively, provide a precise description of every step with screenshots?

**Comment by GazCloud** [comment]
Hi François,

I tried this several times on the last attempt, but just once today - it worked first time. No idea what the issue was last time around...

Thanks,
Gareth

________________________________
