### ISSUE TITLE
Collectives without hosts should not be able to add paying tickets to events

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1411]
**Describe the bug**
Collectives without financial host can add paying tickets to their events. If someone tries to order them, an error will be shown as API expect the collective to have an host.

![Error preview](https://user-images.githubusercontent.com/1556356/48128282-440d0880-e286-11e8-82eb-b219176837ff.png)

**To Reproduce**
1. Go to a collective page without host with an admin account
2. Create an event with a paying ticket
3. Try to order the ticket

**Expected behavior**
1. Frontend should not display the `Amount` field if to admin if collective has no host
![Amount field](https://user-images.githubusercontent.com/1556356/48128398-a7973600-e286-11e8-8c23-25f61323a866.png)

2. Frontend should not display the existing tickets with `amount` > 0 if collective has no host. This is to deal with collectives creating an event then being removed from their financial host.

**Comment by bolariin** [comment]
I think this might have been resolved by https://github.com/opencollective/opencollective-frontend/pull/3307

**Comment by Betree** [comment]
@bolariin indeed, in any case the proper solution is to hide them - not to prevent their creation (because collectives can loose their hosts). Thanks for the heads up!
