### ISSUE TITLE
Predicting Churning Backers

### ISSUE THREAD

**Issue by cborodescu** [opencollective/opencollective#1414]
## User story 
_As a Collective, I can see predictions about backers that are most likely to churn so that I can proactively reach out & incentivize them to continue supporting us._

## Best solution for this problem
_In the "View All Transactions" section, for each backer see a label such as: loyal, neutral, churning._

## MVP
_Simply send an e-mail notification to the Collective owner/admin (every week or so) with potential churning users._

## Metrics 
_Increasing retention/decreasing churn per Collective._

**Comment by piamancini** [comment]
For context, Ciprien's project predicts user churn, drop points, etc. He'd like to see if there's a use there for his project (which is a collective: opencollective.com/morphl)

**Comment by cborodescu** [comment]
Thanks @piamancini, that's correct. We're open-source (https://github.com/morphl-ai) and we'd be happy to work on this use-case. The number one thing is actually getting the data ... 

About that, I understand that some of it might be sensitive, so anonymizing it beforehand would be useful. Again, can help with that.

We can start a conversation by simply describing the data you currently have: what kind of data are you currently recording per user?
