### ISSUE TITLE
collectives are not taking the currency of the host 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1415]
**Describe the bug**

collectiveId=21190 was set to USD when the host (id=21188) was in AUD
collectiveId=21738 was set to USD when the host (id=21739) was in EUR

I manually changed both. 

**Expected behavior**
For the collective to automatically take the currency of the host (this used to happen)

**Additional Context**
Run this query 
```
SELECT
  count(*) as count, max(hc.slug) as "host", max(hc.id) as "HostCollectiveId",
  max(hc.currency) as "host.currency",
  max(c.slug) as "collective", max(c.currency) as "collective.currency",
  max(t.currency) as "transaction.currency",
  max(t."hostCurrency") as "transaction.hostCurrency",
  upper(t.data -> 'balanceTransaction' ->> 'currency') as "stripe.currency",
  min(t."createdAt") as "firstTransactionAt",
  max(t."createdAt") as "lastTransactionAt"
FROM "Transactions" t
LEFT JOIN "Collectives" hc ON hc.id=t."HostCollectiveId"
LEFT JOIN "Collectives" c ON c.id=t."CollectiveId"
WHERE t."hostCurrency" != hc.currency
  AND t."deletedAt" IS NULL
GROUP BY t."HostCollectiveId", t."CollectiveId", "stripe.currency"
ORDER BY count DESC
```
And only 5 collectives are mismatched with the host which we already knew about (and some are on purpose). So we should check the code in the self-serve flow to avoid this happening again.

**Comment by znarf** [comment]
@xdamman can you have a look?
