### ISSUE TITLE
New presentation page with partner platforms to raise money for your collective

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1420]
It would be great to have a page somewhere with the list of ways one collective can bring money in (and link to it from one of the automated onboarding emails, the FAQ, other?)

I'm thinking of CodeFund (@coderberry), Carbonads (@sayzlim), Threadless, Eventbrite, etc.

For each, we should have a logo, picture (e.g. of webpack t-shirt), and links to some of the transactions to different collectives made by those platforms.

As a step 2, it would be great to keep track of those partners and follow how much money each is bringing across all collectives.

@piamancini other partners we should include here?
@alannallama can you start a copy for this?
@cuiki can you come up with a design (following the same template as other marketing pages you've made recently)

**Comment by sayzlim** [comment]
Let me know if you need anything from us.

**Comment by alannallama** [comment]
@xdamman Sorry I'm not totally clear about what you mean. Are you talking about income sources through Open Collective such as...

* Small recurring donations
* Large one-off sponsorship
* Event tickets
* Gift cards
* Reward tiers (ex: selling t-shirts, VIP support hours)

... or is it something else? I don't know what 'partner platforms' are.

Are you thinking about something in the wiki, or a blog post, or...?

**Comment by xdamman** [comment]
I’m more talking about platforms that collectives can use to make more money for their collectives. Basically services like the ones mentioned above that make it easy to get the earnings to your collective. So it’s not about special tiers. It’s more about what other platforms you can use out there that can help you make money for your collective.
