### ISSUE TITLE
showBtn has no effect

### ISSUE THREAD

**Issue by astorije** [opencollective/opencollective#1425]
It looks like the `showBtn` param of the backer snippet has no effect:

- https://opencollective.com/thelounge/tiers/backer.svg?avatarHeight=36&showBtn=false
- https://opencollective.com/thelounge/tiers/backer.svg?avatarHeight=36&showBtn=0
- https://opencollective.com/thelounge/tiers/backer.svg?avatarHeight=36&showBtn=
- ...

Am I missing something obvious?

**Comment by HipsterBrown** [comment]
@astorije It looks like we should update our documentation for that. The query parameter is actually `button`. So https://opencollective.com/thelounge/tiers/backer.svg?avatarHeight=36&button=false will hide the button. 

Thanks for creating an issue.

**Comment by HipsterBrown** [comment]
@znarf On the `/:collectiveSlug/edit#export` page:

<img width="870" alt="screen shot 2018-11-12 at 5 03 14 pm" src="https://user-images.githubusercontent.com/3051193/48377839-db19fc00-e69c-11e8-9b77-03e4955639b6.png">
