### ISSUE TITLE
Use Cases in page footer doesn't give use cases

### ISSUE THREAD

**Issue by RalphCorderoy** [opencollective/opencollective#1426]
The site's footer has a _Use Cases_ link to https://opencollective.com/opensource in the _PLATFORM_ column, but it doesn't give use cases on that page.

**Comment by znarf** [comment]
@piamancini Looks like we need a proper _Use Cases_ page. And maybe in the meantime remove from the footer the current link as it's confusing. What do you think?

**Comment by piamancini** [comment]
yep.
