### ISSUE TITLE
Don't know where to leave issues for opencollective.com

### ISSUE THREAD

**Issue by mixmix** [opencollective/opencollective#1427]
**Problem** - when something is confusing about the website interface, I want to leave constructive feedback. When I go to https://github.com/opencollective/ there are many repos that could be the right one:
- https://github.com/opencollective/opencollective
- https://github.com/opencollective/opencollective-frontend
- https://github.com/opencollective/opencollective-website

My response is to give up and leave an issue on twitter. (@alannallama convinced me not to and pointed me at this repo)

**Solution** ideas:
- make a form somewhere
- put a link on the website which says "feedback" instead of issue?
- make the github link go straight to the correct repo
- change github.com/opencollective view by:
  - pinning different repos which are most relevant
  - change the descriptions of the repos to indicate which are demo repos and which are the main ones ... or be a little more descriptive

<3

**Comment by piamancini** [comment]
Thanks Mix! It's great feedback. 
Did you have any particular issue you need help with?

**Comment by mixmix** [comment]
oh good point, i forgot the initial issue ... here it is: https://github.com/opencollective/opencollective/issues/1428

**Comment by znarf** [comment]
![screen shot 2018-11-12 at 21 29 32](https://user-images.githubusercontent.com/806/48373446-21ce1d00-e6c2-11e8-95b3-af222d76a31d.png)

Small improvement, updated the description of the repository.

**Comment by mixmix** [comment]
nice one @znarf 

Can you also mark the opencollective-frontend differently? Is that in use, is it a prototype/ experimental beta, has it been deprecated?

**Comment by znarf** [comment]
@mixmix opencollective-frontend is definitely in use, it's containing all our website/web app.

**Comment by znarf** [comment]
Yes, the team is more comfortable using a central repository for issues. So this is where things are happening!

We still have a few issues in dedicated repos but we don’t advise to use them.

**Comment by znarf** [comment]
All issues from API and Frontend were move to the main repo. It's now clearer.

**Comment by znarf** [comment]
I think this is fixed now.
