### ISSUE TITLE
Automate direct deposits

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1429]
Patreon, Medium and other platforms offer direct deposit via bank transfer as a payment option. Many Open Collective users would like to receive direct bank deposits rather than Paypal. I think Open Collective should offer this option. Currently we do bank transfers manually and it's too time consuming and difficult. I think we can set this up via Stripe.

Related to #1424

**Comment by alannallama** [comment]
@xdamman I think this would help with your issues around doing bank transfers. If someone is giving us their bank details for a manual wire transfer anyway, it would be as easy for them and a lot easier for us to have them input those details into our system and then automate the payment via Stripe.

**Comment by xdamman** [comment]
Absolutely, if it's automated it's a totally different story.

@znarf can Stripe automate SEPA transfers with IBAN numbers? How complex would be such integration? That would be a killer addition for European transactions.

**Comment by IzzySoft** [comment]
Amongst "privacy proponents", Stripe is almost as "evil" as PayPal. Opening a Stripe account is out of question for many. So it would be much preferred if that would not be a requirement for donation receivers.

**Comment by znarf** [comment]
How could we streamline direct deposits? Can we use Transferwise API for that? https://api-docs.transferwise.com/

**Comment by IzzySoft** [comment]
I don't know what is needed to implement that or what APIs are available for it (not my area of expertise), sorry.

As others already stated, I was hoping I had only to add an IBAN to my account data to retrieve the donations I received – either manually triggered from within the account (fine with me), whenever a certain threshold is reached, or in a certain interval (monthly/quarterly/yearly). I'd fully understand if there'd be a "minimum amount" for each transaction (5, 10 or even 20 EUR would certainly be acceptable – with the exception of account closure, where just "the remains" would be transferred).

**Comment by alannallama** [comment]
@znarf 

Here's Patreon's payout options using Paypal and Payoneer: https://support.patreon.com/hc/en-us/articles/203913489-What-are-my-options-to-receive-payout-

Medium uses Stripe: https://help.medium.com/hc/en-us/articles/360003928833-Setting-up-payments-with-Stripe

**Comment by IzzySoft** [comment]
@alannallama for the privacy proponents, Paypal and Stripe are no options (and if I were happy with them, I'd not spoken up here but would simply stay with Liberapay, as they use the two). I didn't yet dig into Payoneer, though – but again that would require another 3rd party account, if I understood that correctly (payout to Payoneer account or Payoneer credit card).

**Comment by alannallama** [comment]
Yes, there are a few different kinds of users with different priorities. Some only care about the convenience of direct deposits, while others have ethical and privacy concerns with third party services. I hope we can offer options to meet all the needs.

**Comment by alanna** [comment]
More and more expense submitters are asking for transfer via Transferwise or ACH. It's a commonly requested feature and will be essential if we want hosts to be more scalable.

**Comment by IzzySoft** [comment]
I guess the stale bot will come by this some more times, unfortunately…

**Comment by IzzySoft** [comment]
I was a prophet it seems. See you in April then, stale bot…

**Comment by kewitz** [comment]
@alanna I've been going through Stripe and TransferWiser docs and I think there's room for some improvements:

**Payout from Stripe**
Assumptions: The user submitting the expense has a TransferWise account with a mirror account that matches the host's currency.
1. We create a custom account through Stripe connect for the user in the host's Stripe.
2. We use the API to create manual payouts for that account.

**Payout from TransferWise**
Assumptions: The host has a TransferWise business account. The user submitting the expense has an account in a [country covered by TransferWise](https://transferwise.com/us/business/pricing-and-coverage).
1. The host is responsible for keeping the balance of the TransferWise account.
  - The host can configure Stripe to automatically send fund to the Transferwise account.
  - We can create tools for creating payouts from Stripe to TransferWise on demand.
2. The user sets up its account information when submitting the expense, this information can promptly be validated using TransferWise's API.
3. On approval, we can use TransferWise API to automatically pay that account.

I'm just not fully aware of the legal aspects of such transactions and how feasible are my assumptions.

**Comment by piamancini** [comment]
> Payout from Stripe

What's interesting here is that GitHub is using this same mechanism to pay groups in their Github Sponsors Program. So many of them will have a double interest in setting this up. 
@devonzuegel can you please confirm if this is just for the organizations program or it's also for individual maintainers? 

Also that we are already set up with stripe to receive payments and we use connected accounts. 

> Payout from TransferWise

What I like about this is that it's more widespread. We use it regularly and users have experience creating TW accounts. They offer the option of creating local bank details in 
USD / GBP / EUR / AUD / NZD / PLN (poland)

This covers a wide range of hosts for which payments will simply be a local bak transfer. This is a massive improvement. 

> The host is responsible for keeping the balance of the TransferWise account.

You can also get TW to fetch money from your bank or you make the transfer in the moment with a code to match the transaction. It's fairly straight forward. 

> The host can configure Stripe to automatically send fund to the Transferwise account.

This is useful, but we need to look at the fine print. I don't think TW will let you keep the funds there for +30days. It's likely a clearing account. 

> We can create tools for creating payouts from Stripe to TransferWise on demand.

Each host can set this up from their TW account. 

> On approval, we can use TransferWise API to automatically pay that account.

This would be the killer feature :)

**Comment by kewitz** [comment]
> This is useful, but we need to look at the fine print. I don't think TW will let you keep the funds there for +30days. It's likely a clearing account.

They do, with borderless accounts.

The fundamental difference is: are we pushing for hosts or users to have a TW account?

**Comment by IzzySoft** [comment]
> The fundamental difference is: are we pushing for hosts or users to have a TW account?

If it's possible to deal with that host-based (and users only need the bank account they usually already have), that would be much preferred by us tin-foils (I didn't yet look up TW – but I definitely wouldn't create a PayPal or Stripe account, for example). Users who want this could then chose an instance supporting it, without having to open their own 3rd party account – only to store their "bank connection" (e.g. Name + IBAN for SEPA, in Europe) in their account settings on their instance. I'd like that!

**Comment by kewitz** [comment]
It seems that Stripe is able to collect ACH debit from accounts in the US.
This is also compatible with Stripe Connect, which means we could collect through the platform and credit the host.
The flow is a bit different from credit cards, it is totally async and takes some days to validate.
More info here: https://stripe.com/docs/ach

**Comment by IzzySoft** [comment]
@kewitz Seeing https://docs.opencollective.com/help/fiscal-hosts/payouts/payouts-with-transferwise it looks like the admin(s) of an OC instance take care for the "TW stuff" – and all the "recipient" has to do is to provide account details (e.g. IBAN/BIC). Do I understand that correctly? So I could set up an account with an instance supporting that (how to find out which does?), setup payment via IBAN/SEPA, and receive donations that way without the need to register myself with Paypal/Stripe/TW/whatever? To me that sounds great even if I had to trigger each payment manually (and it might be delayed a few days in case the instance had not yet "covered" their balance) – just want to make sure I understood correctly :smiley:

**Comment by kewitz** [comment]
Hey @IzzySoft,
I'm a bit out of context here and I don't know if you're a Host or a user trying to get reimbursed, so I'll try to explain what the feature is capable right now.

Right now TransferWise is working only for payouts, this means that you're able to get reimbursed directly to your bank account (without needing to have a TransferWise account) for all expenses and invoices you submit to a host connected to TransferWise.

_Example:_
Today you can submit an expense to Webpack collective requesting a wire transfer to your IBAN account because its host Open Source Collective 501(c)(6) is connected to TransferWise.

**Comment by IzzySoft** [comment]
Sorry for not giving the background: a *potential* "user trying to get reimbursed". I'm a "creator" (content & software, all CC/FOSS); with Liberapay requiring Paypal or Stripe (which I refuse), my "donation service" is dead to me. Watching OC for quite a while, waiting for one of the alternatives (Bitcoin, SEPA) to become available. So this sounds promising – but I need to submit an "expense"? Just asking for a "payout" of accumulated donations would not work? What formalities would such an expense need to meet (i.e. can "simple receivers" like me set it up themselves, or must it be eg. a bill received, travel ticket, etc)? Must I give a reason why I want my funds? :wink: Just wondering and trying to grasp the idea. Thanks!

**Comment by znarf** [comment]
It's the Open Collective model, you don't withdraw money, you submit invoices or receipts as expenses. That way, you have a transparent budget and people can look at how you used that money. 

If you want money for yourself, you can just submit an invoice for consulting services or similar.

**Comment by IzzySoft** [comment]
Perfect, got it – thanks! Then it's time for me to watch out for a matching instance :smiley:

**Comment by znarf** [comment]
This is solved by the Bank Transfer / Transferwise feature.
