### ISSUE TITLE
host dashboard missing paypal connect button

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1431]
**Describe the bug**
host https://opencollective.com/arron-kennedy should be able to connect payapl from the host dashboard: https://opencollective.com/arron-kennedy/dashboard but there's no paypal button. 

**Expected behavior**
be able to connect paypal from a button on the navbar to the right. 

**Screenshots**
this host's dashbaord: 
![no paypal](https://user-images.githubusercontent.com/3671070/48421945-8c677300-e72b-11e8-9bb1-9b5f1f97ef54.PNG)

A normal dashboard: 
<img width="1260" alt="screen shot 2018-11-13 at 10 05 27 am" src="https://user-images.githubusercontent.com/3671070/48421993-ae60f580-e72b-11e8-8bca-06b5e381a262.png">

Error user sees when trying to pay an expense: 
<img width="892" alt="screen shot 2018-11-13 at 10 06 11 am" src="https://user-images.githubusercontent.com/3671070/48422043-c9336a00-e72b-11e8-9b4b-6d910a7cae0f.png">

This makes sense since there's no paypal connected for that user in the connected accounts table. 

I think it's related to the this host being a user and not an organization.

**Comment by znarf** [comment]
I don't get where the functionality to connect Paypal is supposed to be. Screenshot of a situation where it's working?

**Comment by piamancini** [comment]
The image above that says normal dashboard is what we expect to see. 
Log in to any host opencollective.com/foundation /opensourcecollective /europe (you need to be an admin of the host) and you'll see a connect payapl

<img width="1274" alt="screen shot 2018-11-13 at 8 58 18 pm" src="https://user-images.githubusercontent.com/3671070/48454881-142e9b00-e787-11e8-86d2-c490a4b5c418.png">

**Comment by znarf** [comment]
@piamancini All right
