### ISSUE TITLE
Update API async functions to remove babel transform

### ISSUE THREAD

**Issue by HipsterBrown** [opencollective/opencollective#1432]
While [upgrading to Babel 7](https://github.com/opencollective/opencollective-api/pull/1509), it was discovered that there are several places in the `opencollective-api` repo that assume the Bluebird Promise methods are available on the return value from `async` functions. So the `@babel/plugin-transform-async-to-generator` package is required to polyfill those Bluebird methods until those functions are updated to use the native `async / await` API.

Those functions can be found by removing the transform plugin and running the test suite locally. More smoke testing will probably be needed to make sure all code paths are covered.

**Comment by Betree** [comment]
An example of a CI run demonstrating this issue:
- https://github.com/opencollective/opencollective-api/pull/5161/checks?check_run_id=1747628214
- https://github.com/opencollective/opencollective-api/pull/5161/checks?check_run_id=1747628106

The most frequent error is `.tap is not a function`
