### ISSUE TITLE
Making one-time pledges doesn't work

### ISSUE THREAD

**Issue by onyxmaster** [opencollective/opencollective#1433]
**Describe the bug**
When selecting "One-Time" frequency for pledges, the form fails to submit.

**To Reproduce**
1. Search for a non-existent project
2. Click on 'Make a pledge'
3. Fill out the form, specifying "One-Time" frequency
4. Submit form
5. See error 'Error: GraphQL error: Validation error'

**Comment by onyxmaster** [comment]
@piamancini No, I logged with `xm@drive.net` and tried both company account (https://opencollective.com/drivenet-inc) and my personal one (https://opencollective.com/onyxmast3r).

**Comment by piamancini** [comment]
ok thanks. we'll look into it.

**Comment by HipsterBrown** [comment]
@onyxmaster The fix for this has been deployed this morning. Please let me know if you're still encountering an issue.
