### ISSUE TITLE
Goals overlap

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1434]
**Describe the bug**
Goal is unreadable 

**To Reproduce**
Go to: 
- https://opencollective.com/falcon
- https://opencollective.com/manyverse
- https://opencollective.com/classicpress

**Expected behavior**
No overlap in the available budget

**Screenshots**
![screen shot 2018-11-13 at 2 38 31 pm](https://user-images.githubusercontent.com/3671070/48438468-07438480-e752-11e8-9fa1-447858ef29ca.png)

**Desktop (please complete the following information):**
  iOS
chrome

**Additional context**

**Comment by Betree** [comment]
Has a fix been discussed yet? I remember encountering it and setting different goals to bypass the bug.

As a very simple fix, I think a logarithmic scale instead of a linear one could fix most of the situations we encounter.

That and alternating between having the marker on top then bottom.

**Comment by piamancini** [comment]
Reported by collective admin 
![image 5](https://user-images.githubusercontent.com/3671070/50310896-698a5600-0471-11e9-9347-a0b4de420595.png)

**Comment by Betree** [comment]
Fixed by https://github.com/opencollective/opencollective-frontend/pull/1214

**Comment by znarf** [comment]
@Betree have a look at https://opencollective.com/opensource

![screen shot 2019-01-03 at 00 17 13](https://user-images.githubusercontent.com/806/50617333-f5c65f80-0eec-11e9-85f3-32994539d886.png)

**Comment by Betree** [comment]
Re-opening this to track the edge cases we may find

**Comment by gusaus** [comment]
https://opencollective.com/devshop might be an edge case, but it's a good example of how multiple goals close together overlap and obstruct each other. 

![OpenDevShop - Open Collective 2019-04-16 17-14-33](https://user-images.githubusercontent.com/113996/56252088-1b760f80-606b-11e9-8e99-17ebdfab6da9.png)

**Comment by Betree** [comment]
@gusaus This one really looks bad :disappointed: It's hard to see what could be done to improve it beside using a scale that is non linear at all.

The best option in my opinion would be to give the collective the ability to set how this is displayed (linear, logarithmic, equally-spaced...etc) - that's pretty easy to implement.

However with the new collective page that's coming we're not going to spend time on this right now, it's possible that we drop the feature as it looks today entirely.

**Comment by gusaus** [comment]
We should thank @jonpugh for creating such a fine example of functionality that needs to be improved 😄 

@Betree What about the option of providing/displaying goals similar to Patreon? https://support.patreon.com/hc/en-us/articles/203913409-What-are-goals-

The feature itself is most likely something that many collectives use and value. Are you considering dropping the feature entirely?

**Comment by Betree** [comment]
@gusaus Not the feature itself but the way it is displayed. Design team is still actively working on it so I can't exactly say how it's going to look, but they confirmed me that this progress bar is going away with the new collective page :slightly_smiling_face:

**Comment by piamancini** [comment]
this is deprecated by the new collective page
