### ISSUE TITLE
Migrate all UNSAFE_componentWillReceiveProps

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1438]
`componentWillReceiveProps` is deprecated and should not be used anymore. Most of the ones we do in the code can easily be migrated with `componentDidUpdate`.

See https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

- [x] ./src/apps/expenses/components/CreateExpenseForm.js
- [x] ./src/apps/expenses/components/TransactionsWithData.js
- [x] ./src/components/CreateCollectiveForm.js
- [x] ./src/components/EditEventForm.js
- [x] ./src/components/EditCollectiveForm.js
- [x] ./src/components/InputField.js
- [ ] ./src/components/InputTypeCreditCard.js
- [ ] ./src/components/InputTypeLocation.js
- [ ] ./src/components/MatchingFundWithData.js
- [ ] ~~./src/components/OrderForm.js~~ (not needed, components will be deleted)
- [ ] ./src/components/PaymentMethodChooser.js
- [ ] ./src/components/Subscriptions.js
- [ ] ./src/components/UpdatesWithData.js
- [ ] ./src/pages/banner-iframe.js

**Comment by eloyekunle** [comment]
I'll like to work on this.
