### ISSUE TITLE
Taglines on /discover appears to persist despite editing 

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#1440]
**Describe the bug**
The tagline on  for octobox was edited, but the entry on /discover appears to use the old one.

**To Reproduce**
Haven't attempted to reproduce as this would involve creating a new collective. 

**Expected behaviour**
The tagline should be editable/reflect the current tagline.

**Screenshots**

<img width="339" alt="screenshot 2018-11-14 at 13 25 08" src="https://user-images.githubusercontent.com/158833/48485564-1dfce080-e811-11e8-9c96-77bf3f94ca05.png">

this tagline was edited a while back to due to our wanting to disassociate from the rhetoric around the Brexit vote in the UK 😅

**Comment by znarf** [comment]
@BenJam do you know when you did edit the tagline? Long time ago?

**Comment by znarf** [comment]
We released yesterday a new version of the discover page which is actually fixing this problem!

![screen shot 2018-11-28 at 12 12 58](https://user-images.githubusercontent.com/806/49148190-fb85bf80-f306-11e8-9691-37320349a3ce.png)
