### ISSUE TITLE
Implement a `Pay me a beer on OpenCollective` button for individuals 🍻

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1441]
## User story 
As a developer, I often end up on Gist or Github to use small scripts or projects that would be too small to create a Collective. However for some of them I'd like to say thanks by tipping the author but unless they have a custom `Donate with Paypal` button (which is really rare) or Bitcoin address I can't.

## Best solution for this problem
A possible way to make that possible would be to allow donations for individuals who would set a checkbox to "Accept donations" on their OC profile (and who select a proper host).

Science fiction glasses ON :sunglasses:

We could then create a browser extension that would add a `Pay me a beer on OpenCollective` button on every user Github profile - either redirecting to the actual OC profile or creating a new pledge for this user if not registered yet.

## MVP
1. We should be able to set a `acceptingDonations` flag for some users
2. If flag is set, users should have an `Export` entry in their `Edit profile` (like for collectives) with snippets to add a `Pay me a beer on OpenCollective` button in HTML / Markdown documents.
3. When clicked, this button should redirect to https://opencollective.com/${user_slug}/donate with the same interface we get when donating to a regular collective.

## Metrics 
Before any implementation this idea should be validated by:
- Contacting developers or content creators who use other donation methods, to know if this could interest them
- Ask to developers who share code under free licenses and who are not taking donations today if they would use this system
- Estimate how many people that could represent

MVP should be tested with a few selected users, ideally well-known developers or content producers.

During the MVP we could evaluate the feature by:
- Measuring the count and total donations to individuals who activated the feature
- Measuring the median and average donations to individuals
- Getting feedback from the persons who activated it

**Comment by nemchik** [comment]
I like this idea but I see it's been closed without any additional comments or information. Has this been implemented? Or has this discussion been supersceded by another issue that can be seen here on GitHub?

**Comment by Betree** [comment]
Hi @nemchik, I closed this issue because it seemed too far away from the current Open Collective mission.

Though there are some individuals using OC for receiving donations (eg. https://opencollective.com/sindresorhus) this is still a very rare use case, most of the projects on the platform are about communities.

So except if there's a strong demand from users, I don't think that we'll plan to work on it anytime soon.

**Comment by nemchik** [comment]
I see. Indeed I agree what drew me to OC was the idea that the project I've put on the platform is growing from a one man show into a community and I want the monetary aspect of that to be transparent and accessible. The adjusted title makes more sense as this idea is about donating to an individual where OC currently focuses on the ability to donate to a project.

Thanks for the clarification!
