### ISSUE TITLE
Creating "sub-host" collectives for BrusselsTogether

### ISSUE THREAD

**Issue by jfdh** [opencollective/opencollective#1442]
## User story 
Hello OC team.
With BrusselsTogether, I'd like to allow one of the collective we host, to host itself other collectives. Basically I want to build a mini virtual cooperative. The main host (BrusselsTogether) will keep its prerogatives in terms of payement management, etc. 

This system would allow one collective to collect memberships for its activity from other collectives that it hosts (BrusselsTogether will remain the main host - legal entity for all these collectives). Is it doable?

## Documentation 
Here are the url I'd like to transform into a mini virtual cooperative:

BrusselsTogether (the main host - nothing changes)
https://opencollective.com/brusselstogetherasbl

Make it sound (currently hosted by BrusselsTogether) would become a "sub-host" of collectives
https://opencollective.com/make-it-sound

La Jacqueline (currently hosted by BrusselsTogether) would become a "member collective" of Make it Sound
https://opencollective.com/lajacqueline

Thank you in advance for your help guys!

Cheers

JF

**Comment by xdamman** [comment]
I made lajacqueline a sub collective of make-it-sound, itself a sub collective of BrusselsTogether.

**Comment by patcon** [comment]
Best place to see example of this: https://opencollective.com/make-it-sound#members

**Comment by alannallama** [comment]
@jfdh - Can you simply create another Collective under the BrusselsTogether host? Why does the new Collective need to be a child of another Collective instead of a sibling?

> This system would allow one collective to collect memberships for its activity from other collectives that it hosts

I don't quite understand this part.

I have been thinking about improving how tags work to enable a really flexible groupings of Collectives, regardless of host. So you'd be able to add a tag like #BrusselsprojectX and go to a URL that shows you a page of all Collectives with that tag, to demonstrate who is part of a movement or network. Would this meet your need, or is it more complex that simply grouping these Collectives together?

**Comment by patcon** [comment]
Can't speak for @jfdh, but I see this ability as a pointer that team OpenCollective is open to arbitrarily nested collectives in the future. The delegated hierarchy and implied trust relations are what's interesting.

So for example, Code for American is now looking at Open Collective for it's brigade network. (I hope that Code for Canada might as well, in the future.) I hope that nest collectives like this might one day support a flow where:

1. Code for America is a host. New brigades apply to be subcollectives.
2. Local city brigades are subcollectives. They have budgets and spends.
3. Local city brigades also have their own communities, that run individual open projects.
4. Projects can apply to be subcollectives of brigade subcollectives.
5. When a project member wants to file an expense, it gets approved by project lead, and then the request goes up to the brigade leads, and then the request goes up to the final gate of the Code for America admin. So there's delegated trust, and each person received the request knowing that some person they've trusted has ok'd it

I hope this is helpful! Tags sound exciting and useful, but I hope they don't replace this trajectory of functionality in the future...!
