### ISSUE TITLE
"Request Money" not available

### ISSUE THREAD

**Issue by friedger** [opencollective/opencollective#1447]
I was looking for the request money feature described in the "how it works" but couldn't find anything.

I was looking at https://opencollective.com/blockchain-garage-brussels

**Comment by piamancini** [comment]
Hi @friedger that feature is disabled now. We should remove it from the how it works! Thanks for the reminder. 
As a workaround for now, you can create a tier with that amount from https://opencollective.com/blockchain-garage-brussels/edit#tiers or you can send them or https://opencollective.com/blockchain-garage-brussels/donate
