### ISSUE TITLE
Apply an open-source project using gitlab.com

### ISSUE THREAD

**Issue by der-On** [opencollective/opencollective#1448]
## User story 
As an open-source maintainer, I want to be able to connect to gitlab.com so that I can apply my open-source project hosted on gitlab.com

## Best solution for this problem
The page https://opencollective.com/opensource/apply offers another button that is labeled "connect gitlab". Pressing it will require a gitlab.com private access token, then connects to my gitlab account and lists all repositories from my gitlab.com account with 100+ stars. Everything else then continues in the same way as applying an open-source project using github.com would.

## MVP
An MVP should be able to actually list all 100+ starred projects on my gitlab.com account.

## Metrics 
The number of open-source projects on gitlab.com compared to those on github can be used as a metric. We also have the numbers of users of the [#MoveToGitlab](https://twitter.com/hashtag/MoveToGitLab?src=hash) initiative telling us how many people already made the switch to gitlab. Basically without supporting gitlab.com we are yet again discriminating people who have decided against github.com for reasons.

## Documentation 
Documentation about integrating Gitlab into other software can be found here: https://gitlab.com/help/api/README.md

**Comment by HipsterBrown** [comment]
Labelling this as a complex feature, mostly because we still need to bring over the open source onboarding flow from the `opencollective-website` repo to the `opencollective-frontend` repo. Once that initial flow is brought over, it _should_ drop the complexity for this feature.

**Comment by znarf** [comment]
@der-On In the meantime, if you need to be unblocked, feel free to contact support.

**Comment by der-On** [comment]
@znarf Thank you. As I'm planning on releasing OS on gitlab instead of github I'm glad to here that support will be able to help me with that.

**Comment by YourPsychiatrist** [comment]
Are there no further plans for including GitLab as a source for the verification of reliability?

**Comment by znarf** [comment]
It's not planned but the Open Source Collective is happy to review manual applications of Open Source projects hosted on GitLab. It's just that the process is not automated.

**Comment by Betree** [comment]
@YourPsychiatrist for more info about how to apply manually: https://docs.opencollective.com/help/collectives/osc-verification#manual-verification

**Comment by alanna** [comment]
Gitlab stars are specifically mentioned as valid evidence in our acceptance criteria: https://www.oscollective.org/#criteria

It's just a manual validation process instead of automatic.
