### ISSUE TITLE
French translations improvements

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1450]
- [ ] **Replace all `On` by `Nous` when talking about OpenCollective**

Example:
> ~~On est en train de traiter votre donation à {collective}~~
> Nous sommes en train de traiter votre don à {collective}

- [ ] **Properly change sentences that misuse `Impératif` and `Infinitif`. The following rule should apply:**

> L'infinitif exprime un ordre général et impersonnel. L'impératif exprime un ordre plus personnel et plus proche du lecteur, de ce fait il est plus prescriptif et crée un lien d'obligation entre l'énonciateur et l'exécutant potentiel.
S'il s'agit par exemple de consignes qui doivent impérativement être exécutées dans le déroulement d'un processus employez l'impératif. S'il s'agit de consignes générales adressées à un public non ciblé employez l'infinitif.

- [x] **Replace all `Donation` by `Don`** => https://github.com/opencollective/opencollective-frontend/pull/1066

`Donation` in French is about giving goods, not money.

**Comment by xdamman** [comment]
As another improvement to the way we manage those locales, we should use a tool like https://crowdin.com that has been highly recommended to me.

**Comment by Betree** [comment]
@xdamman And they provide [free licenses for open-source](https://crowdin.com/page/open-source-project-setup-request), we should definitely give it a try.

**Comment by xdamman** [comment]
Ah I didn't even realize that, super cool. Yeah let's definitely do that. It will make it much easier. @znarf was also complaining about the way we handle translations. This will make it much better.
