### ISSUE TITLE
Rate limit api call to test if an email is present

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1455]
What about limiting this at the api level at 20 or 30 calls per hour?

Notes:
- we check if the email is a valid email before making the api call: https://github.com/opencollective/opencollective-frontend/blob/master/src/lib/api.js#L84-L89
- once email is valid, we make a request every 500ms if there has been a keystroke
https://github.com/opencollective/opencollective-frontend/blob/7327f64e61132fab27eaadf5ba0f08e8a7c498c8/src/components/SignInForm.js#L264
- even without key strokes, when email is valid and has changed we make a request every 500ms https://github.com/opencollective/opencollective-frontend/blob/7327f64e61132fab27eaadf5ba0f08e8a7c498c8/src/components/SignInForm.js#L124-L136

**Comment by znarf** [comment]
If we want to rate limit, then we need to get rid of these "every 500 ms" requests.

**Comment by znarf** [comment]
Right. What would be the basis of the limitation, on IP address? We can implement that silently to measure real world numbers and based on that decide what the right threshold should be.

**Comment by xdamman** [comment]
Yeah I think IP address is the easiest and best way.

**Comment by Betree** [comment]
This was done in https://github.com/opencollective/opencollective-api/pull/3102
