### ISSUE TITLE
Memory usage of the frontend application through the roof

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1456]
Since last Tuesday November 13th the memory usage of the frontend is through the roof. What happened?
![](https://d.pr/free/i/VL7R4j+)

What has been deployed on that day?

**Comment by xdamman** [comment]
It’s something in there: https://github.com/opencollective/opencollective-frontend/compare/5632e259...5498e32d

Let's maybe revert @HipsterBrown's PR opencollective/frontend#1018  that got deployed and see if memory usage is better? Otherwise it's one of the greenkeeper updates but it will take more time to identify.

**Comment by znarf** [comment]
![screenshot_2018-11-20 oc-prod-frontend metrics heroku](https://user-images.githubusercontent.com/806/48769910-25166980-ecbd-11e8-9e54-9380c6e6a7fb.png)
