### ISSUE TITLE
PDF Invoice generator service

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1459]
Right now we are generating PDFs for two types of invoices:
- per transaction invoice:
Generated by the old website code base: https://github.com/opencollective/opencollective-website/blob/master/server/src/routes.js#L136
- aggregated monthly invoices per host:
Generated by the new frontend code base: 
https://github.com/opencollective/opencollective-frontend/blob/master/src/server/routes.js#L92

And also to generate name tags for events:
https://github.com/opencollective/opencollective-frontend/blob/master/src/server/routes.js#L125

We should move all this to its own repo, in the same way that we did for https://github.com/opencollective/opencollective-images

It will be easier to test and maintain.

To make this even more modular, we could simplify such service to only expect a template name and a JSON body with all the data expected by the template (a bit like the email templates that we have on API that should also eventually be moved to its own micro service).

That way the PDF generator service is independent of any database access.

E.g. this invoice: https://opencollective.com/xdamman/transactions/3b0c5aba-61ac-4462-9c3e-483421683f00/invoice.pdf could be generated by calling `https://pdf.opencollective.com/:template?data={}`, so in this case: `https://pdf.opencollective.com/invoice?data=${encodeURIComponent(JSON.stringify(data))}` where `data` is:
```
{
  "collective": {
    "slug": "parcel",
    "name": "Parcel"
  },
  "billTo" {
    "slug": "xdamman",
    "name": "Xavier Damman",
    "address": "xxxxxxxxx"
  },
  "date": "2018-11-02",
  "reference": ""
  "details": [
    {
      "date": "2018-11-02",
      "description": "monthly donation to Parcel (backer)",
      "amount": {
        "value": 200
        "currency": "USD"
      }
    }
  ],
  "totalAmount": {
    "value": 200,
    "currency": "USD"    
  },
  "host": {
    "slug": "opensourcecollective",
    "name": "Open Source Collective 501c6 (Non Profit)",
    "address": "340 S Lemon Ave #3717\nWalnut CA 91789\nUSA"
  }
}
```

**Comment by znarf** [comment]
This was partially implemented in https://github.com/opencollective/opencollective-invoices

Closing for now.
