### ISSUE TITLE
Can't "oauth as the organisation"

### ISSUE THREAD

**Issue by fabiosantoscode** [opencollective/opencollective#1461]
**Describe the bug**
I can't register as my organisation terser-js

**To Reproduce**
1. Log in to my account
2. Add the organisation to my orgs
3. Create an open source collective
4. Don't see my project with more than 1000 stars

**Expected behavior**
I expected to be able to create an open collective for github.com/terser-js/terser

**Screenshots**
![screenshot from 2018-11-20 21-12-54](https://user-images.githubusercontent.com/1611595/48803179-240b2980-ed09-11e8-9c51-6fee6ef9878a.png)

**Desktop (please complete the following information):**
 - ElementaryOS
 - Firefox
 - Version 63

**Additional context**
I'm new here

**Comment by fabiosantoscode** [comment]
Note: I've followed every suggestion in https://github.com/opencollective/opencollective/issues/773

**Comment by piamancini** [comment]
Hi @fabiosantoscode! Sorry we missed this until now. 
Can you try revoking access, and when you re-do it, make sure you click on authorizing as an organization? You'll see it when you scroll down. It looks like you've auth your personal github. Let me know how it goes.
