### ISSUE TITLE
Members Migration to follow up on 1535

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1470]
We're merging https://github.com/opencollective/opencollective-api/pull/1535 but a migration still need to be done on the Members table to close the topic.

**Comment by Betree** [comment]
Migration can probably be done with the following query but it would delete members that are not concerned by the previous migration. It seems however that their membership is not valid. This needs to be confirmed.

```sql
/* Delete fundraiser members when no order has them as referral */

DELETE FROM "Members"
WHERE id in (
	SELECT *
	FROM "Members" m
	INNER JOIN "Collectives" c ON m."MemberCollectiveId" = c.id
	LEFT JOIN "Orders" o ON m."MemberCollectiveId" = o."ReferralCollectiveId"
	WHERE o.id IS NULL
	AND c.type = 'ORGANIZATION'
	AND m.role = 'FUNDRAISER';
)
```

**Comment by znarf** [comment]
@xdamman we need your feedback on this one.

**Comment by znarf** [comment]
@xdamman still waiting on your feedback on this one.

**Comment by Betree** [comment]
To put fresh data on this one, the idea is to delete all members with role=`FUNDRAISER` if there's no order made with them in `ReferralCollectiveId`.

Here are the members that will be deleted:

| role       | member           | collective                     | 
|------------|------------------|--------------------------------| 
| FUNDRAISER | hutson           | mochajs                        | 
| FUNDRAISER | hutson           | chaijs                         | 
| FUNDRAISER | aaron1           | impactfellowship               | 
| FUNDRAISER | amp              | webpack                        | 
| FUNDRAISER | amp              | preact                         | 
| FUNDRAISER | amp              | babel                          | 
| FUNDRAISER | elinalin         | acgn-stock                     | 
| FUNDRAISER | simonkjellberg   | webpack                        | 
| FUNDRAISER | simonkjellberg   | babel                          | 
| FUNDRAISER | jim              | beaker                         | 
| FUNDRAISER | chrisdarroch     | skatejs                        | 
| FUNDRAISER | gilbarbara       | babel                          | 
| FUNDRAISER | s4cha            | freshos                        | 
| FUNDRAISER | ricky            | democracyearth                 | 
| FUNDRAISER | ricky            | gatsby                         | 
| FUNDRAISER | iamstarkov       | webpack                        | 
| FUNDRAISER | iamstarkov       | babel                          | 
| FUNDRAISER | iamstarkov       | jss                            | 
| FUNDRAISER | maxscheideman    | streetmix                      | 
| FUNDRAISER | andrewrota       | babel                          | 
| FUNDRAISER | josediazseng     | webpack                        | 
| FUNDRAISER | josediazseng     | babel                          | 
| FUNDRAISER | josediazseng     | parcel                         | 
| FUNDRAISER | ron              | webpack                        | 
| FUNDRAISER | outsideris       | nodemon                        | 
| FUNDRAISER | frostmatthew     | operationcode-collective       | 
| FUNDRAISER | frostmatthew     | operationcodeboston            | 
| FUNDRAISER | pwang            | beaker                         | 
| FUNDRAISER | ross             | beaker                         | 
| FUNDRAISER | scott-walkinshaw | trellis                        | 
| FUNDRAISER | cam-gerlach      | spyder                         | 
| FUNDRAISER | jeborsel         | openrecognition                | 
| FUNDRAISER | jaysoifer        | vuejs                          | 
| FUNDRAISER | morgan-herlocker | turf                           | 
| FUNDRAISER | dylan-shine      | vapor                          | 
| FUNDRAISER | mziehlke         | parcel                         | 
| FUNDRAISER | benoit-martin    | lajacqueline                   | 
| FUNDRAISER | almusamim        | nuxtjs                         | 
| FUNDRAISER | joelcomeaux      | fabio                          | 
| FUNDRAISER | ganzorig         | erxes                          | 
| FUNDRAISER | munkhbold-dembel | erxes                          | 
| FUNDRAISER | jacobtomlinson   | opsdroid                       | 
| FUNDRAISER | syke             | gulpjs                         | 
| FUNDRAISER | syke             | babel                          | 
| FUNDRAISER | malloc007        | babel                          | 
| FUNDRAISER | ryan-helmoski    | cyclejs                        | 
| FUNDRAISER | anonymous71      | socialcoop                     | 
| FUNDRAISER | stichris         | befrank                        | 
| FUNDRAISER | duotai           | babel                          | 
| FUNDRAISER | marswong         | koajs                          | 
| FUNDRAISER | millehorde       | nest                           | 
| FUNDRAISER | darkpixel        | dokku                          | 
| FUNDRAISER | darkpixel        | strider                        | 
| FUNDRAISER | sorayama         | poi                            | 
| FUNDRAISER | philpl           | webpack                        | 
| FUNDRAISER | philpl           | preact                         | 
| FUNDRAISER | ryan-jones       | jsbin                          | 
| FUNDRAISER | epadovani        | aurelia                        | 
| FUNDRAISER | epadovani        | aurelia                        | 
| FUNDRAISER | cdiaz            | nest                           | 
| FUNDRAISER | lislis           | internetffswag                 | 
| FUNDRAISER | lislis           | internetffswag                 | 
| FUNDRAISER | eduardo-jordano  | generator-jhipster             | 
| FUNDRAISER | matt-mirus       | sage                           | 
| FUNDRAISER | codepilotai      | chaijs                         | 
| FUNDRAISER | codepilotai      | webpack                        | 
| FUNDRAISER | codepilotai      | babel                          | 
| FUNDRAISER | codepilotai      | socketio                       | 
| FUNDRAISER | codepilotai      | vuejs                          | 
| FUNDRAISER | anonymous181     | babel                          | 
| FUNDRAISER | marco-carbone    | hots-nyc                       | 
| FUNDRAISER | billie-goodman   | internetffswag                 | 
| FUNDRAISER | benjamin-ward    | biojulia                       | 
| FUNDRAISER | tin-ching-yuen   | babel                          | 
| FUNDRAISER | natario1         | cameraview                     | 
| FUNDRAISER | thread           | the-london-django-meetup-group | 
| FUNDRAISER | thread2          | the-london-django-meetup-group |

**Comment by piamancini** [comment]
The fundraiser idea never flew - I am ok with adding it to the kill list. 
@Betree Is this impacting gift cards? I remember it was showing as 'fundraiser' at the beginning.

**Comment by Betree** [comment]
@piamancini This is indeed linked to gift cards, you remember correctly: the amounts donated through gift cards were recorded as "fundraising".

The change proposed here should remove `FUNDRAISER` members from this time when their amount fundraised is now "0" (it's mostly triplebyte as they were the ones using this feature intensively at the time).

I have a better understanding now of the gift cards system than what I had at the time and I think this is a safe change (I'll double check). So if there's no blocker for anyone I'll probably follow up on this one next week.

**Comment by piamancini** [comment]
SGTM

**Comment by xdamman** [comment]
Sounds good!

**Comment by Betree** [comment]
Done

<details>

|                  |            |                                             | 
|------------------|------------|---------------------------------------------| 
| juin-20 17:29:30 | SQL / User | DELETE FROM public."Members" WHERE id=10829 | 
| juin-20 17:29:30 | SQL / User | DELETE FROM public."Members" WHERE id=10878 | 
| juin-20 17:29:30 | SQL / User | DELETE FROM public."Members" WHERE id=10831 | 
| juin-20 17:29:30 | SQL / User | DELETE FROM public."Members" WHERE id=10830 | 
| juin-20 17:29:29 | SQL / User | DELETE FROM public."Members" WHERE id=11092 | 
| juin-20 17:29:30 | SQL / User | DELETE FROM public."Members" WHERE id=10880 | 
| juin-20 17:29:30 | SQL / User | DELETE FROM public."Members" WHERE id=10879 | 
| juin-20 17:29:29 | SQL / User | DELETE FROM public."Members" WHERE id=11158 | 
| juin-20 17:29:29 | SQL / User | DELETE FROM public."Members" WHERE id=11156 | 
| juin-20 17:29:29 | SQL / User | DELETE FROM public."Members" WHERE id=11154 | 
| juin-20 17:29:29 | SQL / User | DELETE FROM public."Members" WHERE id=11255 | 
| juin-20 17:29:29 | SQL / User | DELETE FROM public."Members" WHERE id=11228 | 
| juin-20 17:29:29 | SQL / User | DELETE FROM public."Members" WHERE id=11164 | 
| juin-20 17:29:29 | SQL / User | DELETE FROM public."Members" WHERE id=11341 | 
| juin-20 17:29:29 | SQL / User | DELETE FROM public."Members" WHERE id=11336 | 
| juin-20 17:29:29 | SQL / User | DELETE FROM public."Members" WHERE id=11287 | 
| juin-20 17:29:28 | SQL / User | DELETE FROM public."Members" WHERE id=11354 | 
| juin-20 17:29:28 | SQL / User | DELETE FROM public."Members" WHERE id=11350 | 
| juin-20 17:29:29 | SQL / User | DELETE FROM public."Members" WHERE id=11342 | 
| juin-20 17:29:28 | SQL / User | DELETE FROM public."Members" WHERE id=11599 | 
| juin-20 17:29:28 | SQL / User | DELETE FROM public."Members" WHERE id=11502 | 
| juin-20 17:29:28 | SQL / User | DELETE FROM public."Members" WHERE id=11449 | 
| juin-20 17:29:28 | SQL / User | DELETE FROM public."Members" WHERE id=11709 | 
| juin-20 17:29:28 | SQL / User | DELETE FROM public."Members" WHERE id=11638 | 
| juin-20 17:29:28 | SQL / User | DELETE FROM public."Members" WHERE id=11785 | 
| juin-20 17:29:28 | SQL / User | DELETE FROM public."Members" WHERE id=11783 | 
| juin-20 17:29:28 | SQL / User | DELETE FROM public."Members" WHERE id=11714 | 
| juin-20 17:29:27 | SQL / User | DELETE FROM public."Members" WHERE id=11965 | 
| juin-20 17:29:28 | SQL / User | DELETE FROM public."Members" WHERE id=11795 | 
| juin-20 17:29:28 | SQL / User | DELETE FROM public."Members" WHERE id=11790 | 
| juin-20 17:29:27 | SQL / User | DELETE FROM public."Members" WHERE id=12067 | 
| juin-20 17:29:27 | SQL / User | DELETE FROM public."Members" WHERE id=12021 | 
| juin-20 17:29:27 | SQL / User | DELETE FROM public."Members" WHERE id=12000 | 
| juin-20 17:29:27 | SQL / User | DELETE FROM public."Members" WHERE id=12131 | 
| juin-20 17:29:27 | SQL / User | DELETE FROM public."Members" WHERE id=12129 | 
| juin-20 17:29:27 | SQL / User | DELETE FROM public."Members" WHERE id=12086 | 
| juin-20 17:29:27 | SQL / User | DELETE FROM public."Members" WHERE id=12198 | 
| juin-20 17:29:27 | SQL / User | DELETE FROM public."Members" WHERE id=12197 | 
| juin-20 17:29:27 | SQL / User | DELETE FROM public."Members" WHERE id=12149 | 
| juin-20 17:29:26 | SQL / User | DELETE FROM public."Members" WHERE id=12341 | 
| juin-20 17:29:26 | SQL / User | DELETE FROM public."Members" WHERE id=12316 | 
| juin-20 17:29:26 | SQL / User | DELETE FROM public."Members" WHERE id=12314 | 
| juin-20 17:29:27 | SQL / User | DELETE FROM public."Members" WHERE id=12215 | 
| juin-20 17:29:26 | SQL / User | DELETE FROM public."Members" WHERE id=12500 | 
| juin-20 17:29:26 | SQL / User | DELETE FROM public."Members" WHERE id=12437 | 
| juin-20 17:29:26 | SQL / User | DELETE FROM public."Members" WHERE id=12377 | 
| juin-20 17:29:26 | SQL / User | DELETE FROM public."Members" WHERE id=12509 | 
| juin-20 17:29:26 | SQL / User | DELETE FROM public."Members" WHERE id=12507 | 
| juin-20 17:29:26 | SQL / User | DELETE FROM public."Members" WHERE id=12502 | 
| juin-20 17:29:26 | SQL / User | DELETE FROM public."Members" WHERE id=12513 | 
| juin-20 17:29:26 | SQL / User | DELETE FROM public."Members" WHERE id=12511 | 
| juin-20 17:29:25 | SQL / User | DELETE FROM public."Members" WHERE id=12761 | 
| juin-20 17:29:25 | SQL / User | DELETE FROM public."Members" WHERE id=12698 | 
| juin-20 17:29:25 | SQL / User | DELETE FROM public."Members" WHERE id=12569 | 
| juin-20 17:29:25 | SQL / User | DELETE FROM public."Members" WHERE id=12515 | 
| juin-20 17:29:25 | SQL / User | DELETE FROM public."Members" WHERE id=12776 | 
| juin-20 17:29:25 | SQL / User | DELETE FROM public."Members" WHERE id=12774 | 
| juin-20 17:29:25 | SQL / User | DELETE FROM public."Members" WHERE id=12766 | 
| juin-20 17:29:25 | SQL / User | DELETE FROM public."Members" WHERE id=12861 | 
| juin-20 17:29:25 | SQL / User | DELETE FROM public."Members" WHERE id=12808 | 
| juin-20 17:29:24 | SQL / User | DELETE FROM public."Members" WHERE id=12901 | 
| juin-20 17:29:25 | SQL / User | DELETE FROM public."Members" WHERE id=12898 | 
| juin-20 17:29:25 | SQL / User | DELETE FROM public."Members" WHERE id=12865 | 
| juin-20 17:29:24 | SQL / User | DELETE FROM public."Members" WHERE id=13159 | 
| juin-20 17:29:24 | SQL / User | DELETE FROM public."Members" WHERE id=13146 | 
| juin-20 17:29:24 | SQL / User | DELETE FROM public."Members" WHERE id=13072 | 
| juin-20 17:29:24 | SQL / User | DELETE FROM public."Members" WHERE id=13197 | 
| juin-20 17:29:24 | SQL / User | DELETE FROM public."Members" WHERE id=13186 | 
| juin-20 17:29:24 | SQL / User | DELETE FROM public."Members" WHERE id=13181 | 
| juin-20 17:29:24 | SQL / User | DELETE FROM public."Members" WHERE id=13330 | 
| juin-20 17:29:24 | SQL / User | DELETE FROM public."Members" WHERE id=13237 | 
| juin-20 17:29:24 | SQL / User | DELETE FROM public."Members" WHERE id=13236 | 
| juin-20 17:29:23 | SQL / User | DELETE FROM public."Members" WHERE id=13358 | 
| juin-20 17:29:24 | SQL / User | DELETE FROM public."Members" WHERE id=13357 | 
| juin-20 17:29:24 | SQL / User | DELETE FROM public."Members" WHERE id=13356 | 
| juin-20 17:29:23 | SQL / User | DELETE FROM public."Members" WHERE id=13390 | 
| juin-20 17:29:23 | SQL / User | DELETE FROM public."Members" WHERE id=13387 | 
| juin-20 17:29:23 | SQL / User | DELETE FROM public."Members" WHERE id=13362 | 
| juin-20 17:29:23 | SQL / User | DELETE FROM public."Members" WHERE id=23418 | 
| juin-20 17:29:23 | SQL / User | DELETE FROM public."Members" WHERE id=16208 | 
| juin-20 17:29:23 | SQL / User | DELETE FROM public."Members" WHERE id=16205 | 
| juin-20 17:29:23 | SQL / User | DELETE FROM public."Members" WHERE id=23466 | 
| juin-20 17:29:23 | SQL / User | DELETE FROM public."Members" WHERE id=23460 | 
| juin-20 17:29:23 | SQL / User | DELETE FROM public."Members" WHERE id=23451 | 
| juin-20 17:29:22 | SQL / User | DELETE FROM public."Members" WHERE id=23604 | 
| juin-20 17:29:22 | SQL / User | DELETE FROM public."Members" WHERE id=23553 | 
| juin-20 17:29:23 | SQL / User | DELETE FROM public."Members" WHERE id=23548 | 
| juin-20 17:29:22 | SQL / User | DELETE FROM public."Members" WHERE id=23683 | 
| juin-20 17:29:22 | SQL / User | DELETE FROM public."Members" WHERE id=23624 | 
| juin-20 17:29:22 | SQL / User | DELETE FROM public."Members" WHERE id=23622 | 
| juin-20 17:29:22 | SQL / User | DELETE FROM public."Members" WHERE id=23817 | 
| juin-20 17:29:22 | SQL / User | DELETE FROM public."Members" WHERE id=23771 | 
| juin-20 17:29:22 | SQL / User | DELETE FROM public."Members" WHERE id=23710 | 
| juin-20 17:29:21 | SQL / User | DELETE FROM public."Members" WHERE id=23871 | 
| juin-20 17:29:22 | SQL / User | DELETE FROM public."Members" WHERE id=23824 | 
| juin-20 17:29:22 | SQL / User | DELETE FROM public."Members" WHERE id=23822 | 
| juin-20 17:29:22 | SQL / User | DELETE FROM public."Members" WHERE id=23820 | 
| juin-20 17:29:21 | SQL / User | DELETE FROM public."Members" WHERE id=23883 | 
| juin-20 17:29:21 | SQL / User | DELETE FROM public."Members" WHERE id=23873 | 
| juin-20 17:29:21 | SQL / User | DELETE FROM public."Members" WHERE id=23906 | 
| juin-20 17:29:21 | SQL / User | DELETE FROM public."Members" WHERE id=23904 | 


</details>
