### ISSUE TITLE
Unability to remove Host after collective creation

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1471]
**Describe the bug**
Collective admin created a collective via de github flow, collective host looks ok, isActive=TRUE and hostID 11004.  https://opencollective.com/amethyst
Collective admin wants to revoke that host, since they want to use their own. Clicks on remove host and nothing happens. Console is not saying anything. (See screenshot)
Furthermore, the legend in the dashboard says the collective is waiting approval, when this is not the case. 

<img width="1264" alt="screen shot 2018-11-26 at 7 14 37 pm" src="https://user-images.githubusercontent.com/3671070/49045535-12fe6480-f1b0-11e8-8024-11909030748d.png">

I am manually removing the host to see if user can use their own host. 

When I went to remove the host, the member row in the members table was deleted, but the collective still had a hostCollectiveId and was Active

**Comment by oncletom** [comment]
When you write "removed the host manually", as an OpenCollective admin of some sort?

I ran in the same problem while trying to see what were the other Hosts but I'm stuck in between two states (Pending Approval by OpenCollective and the inability to take a peek at another Host).

**Comment by piamancini** [comment]
@oncletom yep, as a platform admin. What's your collective?

**Comment by oncletom** [comment]
It is https://opencollective.com/nodebook 🙂 Thanks for your help.

**Comment by piamancini** [comment]
hmmm you don't have a host, what do you see when you go to https://opencollective.com/nodebook/edit/host

**Comment by oncletom** [comment]
Ah, now I see this:

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/138627/50563536-f9f05280-0d1d-11e9-9783-5e856e6d98d6.png">

Prior to now, it was like I was still on the OpenCollective host.

**Comment by piamancini** [comment]
@oncletom good to know, thank you for taking the time to report it. 

@xdamman @znarf I think the issue is that it's not removing the parent collective ID and so it's not letting users see new host options because they are stuck on a pending state.

**Comment by piamancini** [comment]
@oncletom we just approved you for open collective europe.  Thanks again!

**Comment by oncletom** [comment]
Amazing thanks!

PS: sorry for the annoyance, I cancelled my application to peek into the OpenCollective Paris before realising it was not part of OpenCollective/OpenCollective Europe.

**Comment by piamancini** [comment]
no problem! you are all set.

**Comment by znarf** [comment]
This was fixed.
