### ISSUE TITLE
Prettier update and enforcement

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1472]
somehow my editor keeps on creating prettier changes which is quite annoying and noisy in PRs.
E.g. https://github.com/opencollective/opencollective-frontend/pull/1098/commits/037718be9ea691722b07e1f0546d00b2d04cbecb

Can we update frontend and api with the prettier rules (max col width: 120) and make sure we enforce this in all PR?

Also, let's keep in mind that we cannot expect external contributors to change their editor, so let's make sure that we take that into account.

**Comment by znarf** [comment]
Looks like this changes might be due to an update in Prettier. We should used a fixed version of Prettier in the future.

We used to have quite big PRs in the pipeline in the last days and this is why we were waiting for the big change.

**Comment by xdamman** [comment]
Ok cool, the sooner the better obviously.

**Comment by znarf** [comment]
Done.

https://github.com/opencollective/opencollective-api/pull/1541
https://github.com/opencollective/opencollective-frontend/pull/1025
