### ISSUE TITLE
Some collective details are not updated when switching from user menu

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1474]
**Describe the bug**
When switching collectives from the user menu some details are not updated properly. This does not happen when switching collectives by clicking on other links (like from cards).

**To Reproduce**
1. Login
2. Go to a collective page
3. Open your user menu, select another collective

**Expected behavior**
All info should be updated.

**Screenshots**
![Steps](https://user-images.githubusercontent.com/1556356/49074592-40d9bc80-f235-11e8-8953-18f6a386830f.png)
![Preview](https://user-images.githubusercontent.com/1556356/49074308-ba24df80-f234-11e8-9087-17472cc884fb.png)

**Desktop (please complete the following information):**
 - Ubuntu
 - Firefox

**Additional context**
Tested on staging / prod

**Comment by znarf** [comment]
I fixed something like that long time ago. It was some properties that were copied on instantiation and never updated in the component.

**Comment by Betree** [comment]
@znarf The reason may be similar here. I think we should set a high priority on this, we're not sure about the consequences it may have, maybe a user could en up doing an action on another collective than what he intended.

**Comment by Betree** [comment]
I have not be able to reproduce this in local, staging nor production. I may have encountered a local cache issue here.
