### ISSUE TITLE
Replace withLoggedInUser -> withUser 

### ISSUE THREAD

**Issue by HipsterBrown** [opencollective/opencollective#1484]
With the introduction of UserContext (https://github.com/opencollective/opencollective-frontend/pull/1061), we no longer need to pass the `LoggedInUser` object around to child components from each page or parent component. Any page using the repeated `Header`, `Body`, `Footer` components, could make use of the `Page` component instead, see `src/pages/discover.js` or `src/pages/search.js` as an example.

- Number of pages using `withLoggedInUser`: 30
- Number of components referencing LoggedInUser: 51
  - number of component using LoggedInUser: 35

TODO:

- [ ] update usage of `withLoggedInUser` to `withUser` if the page needs that object
- [ ] remove redundant `withData` usage around pages and components
- [ ] wrap components the depend on `LoggedInUser` in `withUser` helper

**Comment by znarf** [comment]
A $300 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $300 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md).

Check list for completion:

- [ ] No components should rely directly on `withLoggedInUser` anymore
- [ ] Components should all use `withUser` instead
- [ ] No broken functionality
- [ ] All tests are passing

**Comment by leonardohof** [comment]
@znarf I'd like to work on this issue.

**Comment by znarf** [comment]
@leonardohof You're assigned! The initial time limit is 1 week, it can be extended if necessary.
