### ISSUE TITLE
Setup new approach for developing React components

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1485]
## User story 

In our current development approach, there is no way to develop React components independently. Our current process is to code them as part of the whole feature, integrated in the main App.

We would like to introduce a new approach as pioneered by projects like [Storybook](https://github.com/storybooks/storybook).

## Best solution for this problem

We're currently considering two solutions and need to decide on one:
- https://github.com/storybooks/storybook
- https://github.com/styleguidist/react-styleguidist

### Storybook

Pros
 - _tbc_

Cons
 - _tbc_

### React Styleguidist

Pros
 - _tbc_

Cons
 - _tbc_

## Implementation

We will start using this approach for new components as a first step.

**Comment by HipsterBrown** [comment]
We are currently trying out React-Styleguidist for our component development and documentation.

It allows for auto-generation of a Props table and annotation with JSDoc. We can also create interactive examples in Markdown. 👍 

https://github.com/opencollective/opencollective-frontend/pull/1119

**Comment by Betree** [comment]
@znarf maybe we can close this? I think we're pretty happy with styleguidist.
