### ISSUE TITLE
fix insecure img src

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#149]
![pasted image at 2016_06_24 12_15 pm](https://cloud.githubusercontent.com/assets/3671070/16347147/051939c2-3a00-11e6-8044-0afcf2089deb.png)

**Comment by carlosascari** [comment]
Changing the urls to protocol-less urls should do the trick
http://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by xdamman** [comment]
We already do.
The problem is that the avatar of the members are often loaded from HTTP servers. We should proxy them. We can use cloudinary for that. I'll submit a PR in a few.
