### ISSUE TITLE
ContributePayment Component

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1490]
![screen shot 2018-11-29 at 09 44 53](https://user-images.githubusercontent.com/806/49209697-75778080-f3bb-11e8-91f0-3504e801511d.png)

It needs to support:
- existing Credit Cards (passed as prop)
- existing Gift Cards (passed as prop)
- _Collective to Collective_ (passed as prop)
- new Credit Card
- Paypal

Note:
- "new Credit Card" is the Stripe widget
- ability to NOT save Credit Card is a new feature
  - it should not be possible if it's subscription
  - it should be disableable if backend support is not ready
- as of today, PayPal needs to generate its own button, we need to figure best way to do that
 - no sub-component identified

[Check Source on Figma](https://www.figma.com/file/e71tBo0Sr8J7R5n6iMkqI42d/09.-Platform-%2F-Collectives?node-id=253%3A219)

**Comment by HipsterBrown** [comment]
> Collective to Collective (passed as prop)

After looking through the Figma designs, I don't see an example for this case. @cuiki

**Comment by Betree** [comment]
Done with https://github.com/opencollective/opencollective-frontend/pull/1223
