### ISSUE TITLE
Gift Cards contributions not appearing in Backing / Backers

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1493]
**Describe the bug**

According to:
https://opencollective.com/znarf/subscriptions
https://opencollective.com/znarf/transactions

I donated to:
https://opencollective.com/unified
https://opencollective.com/babel
https://opencollective.com/manyverse
https://opencollective.com/symfony
https://opencollective.com/webpack

All these were made trough a Gift Card owned by:
https://opencollective.com/opencollectiveinc

However, when going to https://opencollective.com/opencollectiveinc, I don't see in the Backing area:
- babel
- manyverse
- webpack

Double checking, I can see the transactions in: https://opencollective.com/opencollectiveinc/transactions Browsing this list, I can also see that the problem is shared with other members of the team.

Finally, note that the reverse is true, I don't see 'opencollectiveinc' in the Backers section of:
https://opencollective.com/manyverse

**Comment by znarf** [comment]
Linked with https://github.com/opencollective/opencollective/issues/1470 ?

**Comment by Betree** [comment]
I don't think so, the only thing that #1470 could induce is showing TripleByte (they are the only organization concerned by this) as fundraiser of collectives for which one of its gift cards was used.

**Comment by Betree** [comment]
First clues :
- Not able to reproduce for new subscriptions, to this seems to affect mainly existing subscriptions that were using virtual cards from updates
- It actually works for unified, OpenCollective is properly mentioned, only the total count is not right
![selection_839](https://user-images.githubusercontent.com/1556356/49371193-ee961100-f6f6-11e8-9742-7f22b138167c.png)

**Comment by Betree** [comment]
So the migration I had created for the new column `UsingVirtualCardFromCollectiveId` did not add all the `Member`s that it should have. Though new subscriptions are ok, the ones made before this update doesn't have a proper member attached for the virtual card provider.

The following query returns all the pairs of missing `Backer Organization` <> `Collective`

```sql
SELECT c.slug as "TransactionUsingVirtualCardFromCollective", ct.slug as "TransactionCollective" FROM "Transactions" t
LEFT JOIN "Members" m ON m."MemberCollectiveId" = t."UsingVirtualCardFromCollectiveId" AND m."CollectiveId" = t."CollectiveId"
INNER JOIN "Collectives" c on c.id = t."UsingVirtualCardFromCollectiveId"
INNER JOIN "Collectives" cu on cu.id = t."FromCollectiveId"
INNER JOIN "Collectives" ct on ct.id = t."CollectiveId"
WHERE t."UsingVirtualCardFromCollectiveId" IS NOT null
and t.type = 'CREDIT'
AND m.id IS NULL
GROUP BY c.slug , ct.slug;
```

And here is the result:

| TransactionUsingVirtualCardFromCollective | TransactionCollective             | 
|-------------------------------------------|-----------------------------------| 
| opencollectiveinc                         | babel                             | 
| opencollectiveinc                         | chaijs                            | 
| opencollectiveinc                         | cypressio                         | 
| opencollectiveinc                         | manyverse                         | 
| opencollectiveinc                         | mochajs                           | 
| opencollectiveinc                         | mongoose                          | 
| opencollectiveinc                         | preact                            | 
| opencollectiveinc                         | secure-scuttlebutt-consortium     | 
| opencollectiveinc                         | sinon                             | 
| opencollectiveinc                         | spyder                            | 
| opencollectiveinc                         | styled-components                 | 
| opencollectiveinc                         | webpack                           | 
| rollbar                                   | vuejs                             | 
| triplebyte                                | android-password-store            | 
| triplebyte                                | asciidoctor                       | 
| triplebyte                                | avogadro                          | 
| triplebyte                                | camerakit-android                 | 
| triplebyte                                | cameraview                        | 
| triplebyte                                | chsf                              | 
| triplebyte                                | coconut                           | 
| triplebyte                                | crypto-ui                         | 
| triplebyte                                | developing-ios-10-apps-with-swift | 
| triplebyte                                | emotion                           | 
| triplebyte                                | expo-cli                          | 
| triplebyte                                | gorm                              | 
| triplebyte                                | gulpjs                            | 
| triplebyte                                | haxe                              | 
| triplebyte                                | heapclub                          | 
| triplebyte                                | jbot                              | 
| triplebyte                                | librenms                          | 
| triplebyte                                | nest                              | 
| triplebyte                                | parcel                            | 
| triplebyte                                | rubytogether                      | 
| triplebyte                                | shields                           | 
| triplebyte                                | streamlink                        | 
| triplebyte                                | turf                              | 
| triplebyte                                | wwcodebeijing                     | 
| triplebyte                                | wwcodekyiv                        | 
| triplebyte                                | wwcodepune                        | 

I will prepare a migration to create members of all these.
