### ISSUE TITLE
Getting "Unknown Error" trying to load expense pages

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1495]
This is happening intermittently, when I try to load an expense URL. It's affecting about half the ones I try to load.

<img width="686" alt="screen shot 2018-11-30 at 6 30 38 pm" src="https://user-images.githubusercontent.com/5498878/49270462-6c2b0880-f4ce-11e8-89d9-1fcefccc7fb2.png">

Error:
* https://opencollective.com/ngrx/expenses/5888
* https://opencollective.com/qubes-os/expenses/5857
* https://opencollective.com/dim/expenses/5856
* https://opencollective.com/bevry/expenses/5842

No error:
* https://opencollective.com/fast-xml-parser/expenses/5863
* https://opencollective.com/redux-devtools-extension/expenses/5878
* https://opencollective.com/qubes-os/expenses/5867

**Comment by znarf** [comment]
Looks duplicate with https://github.com/opencollective/opencollective/issues/1494
