### ISSUE TITLE
Allow adding fees on top

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#15]
Currently, when you donate $100, stripe charges you $100 and fees come out of that. Depending on how much host takes, end collective gets around ~$87.

We want to let users pay more fees on top of their donation. User clicks on `Donate $100`. Dialog shows: 

$100
`+` $13 fees
`=` $113
Confirm

Implementation proposal
1. Backend: Add a boolean field on the collective `feesOnTop`
2. Frontend: Create a new dialog that shows the final amount with fees
- If flipped (initially only for the French movement with a French host, so no currency issues), we show the dialog above. 
- When they click confirm, we pass $113 to Stripe and show the Stripe dialog. Two dialogs aren't ideal but it would be the easiest way to do it. Otherwise, we'd need to rebuild a credit card donation form.

Open questions
- Should we do one dialog or two?
- Find out exactly how much stripe will charge for a european credit card. We can also assume a flat 3% rate and eat the difference of 20 cents or so.

**Comment by piamancini** [comment]
Stripe fees:
1.4% + 0.25E for european cards
2.9% + 0.25E non european cards

P.
piamancini.com
t: @piamancini
s: piamancini
OpenCollective <https://opencollective.com>

**Comment by asood123** [comment]
We won't know which card it is because this needs to be shown before the card is entered. We can pick the smaller one and eat the difference initially?

**Comment by piamancini** [comment]
ahhh
donation range let's say is 5-20EURO son it's
EC: 0.32 - 0.53
NonEC: 0.39 - 0.83
Let's say in 500 7.57E and 14.75

I think it's ok to do it at the beginning but we should stay on top of it
because in large donations the difference is double.


P.
piamancini.com
t: @piamancini
s: piamancini
OpenCollective <https://opencollective.com>

**Comment by xdamman** [comment]
PayPal is using 
`feesPayer = 'SENDER'` or `feesPayer='RECEIVER'`

I would suggest using the same terminology but instead of `SENDER` and `RECEIVER`, we could use `HOST`, `BACKER`, `COLLECTIVE`.

For the frontend, and as an MVP, I would simply change the description in the Stripe modal to say "$20 + $3 fees"

![](http://cl.ly/3P283Z2K340A/Screen%20Shot%202016-04-15%20at%2011.38.10%20PM.png)

**Comment by asood123** [comment]
I implemented a simple version of this: https://github.com/OpenCollective/website/commit/639cd15aff84852e5db43b73023b533c4b8e0cac. It runs into some issues. 

I laid out two methods and their consequences in this spreadsheet: https://docs.google.com/spreadsheets/d/1EthmgOrYGQwZ78YTz3Yma7KHbpQeUuTD2BRcBNPGFXY/edit#gid=0. The commit above is Method 1 in the spreadsheet. 

Method 2 is definitely better to implement - it has a huge overhead for every donation, especially smaller ones.

**Comment by asood123** [comment]
My biggest concern is not implementation - it's the perception. It sucks if we are adding 20% or 30% in fees. One option is not to include host fees, especially for organizations like Women Who Code. Added a few variations at the bottom of the spreadsheet to show what that would look like.

**Comment by xdamman** [comment]
I talked to @cuiki this morning about this. He should come back today with a first draft design.
The idea is the following:

You click on "Donate $20 / month" then you have a new screen (a modal on desktop) that acts as the receipt like in the restaurant. It would basically show the breakdown. E.g: 

    Your donation: $20
    WWCode Austin: $16.1
    WWCode HQ: $2
    OpenCollective fees: $1

    Credit card processing fees: $0.90

    Total: $20.90

    [Pay by Credit Card ] [ Pay With PayPal ]

For #NuitDebout, it would look something like: 

    Your donation: €10 / month
    #NuitDebout global: <--- €2.50 --->
    #NuitDebout / media commission: <--- €2 --->
    #NuitDebout / infrastructure: <--- €2  ---> 
    #NuitDebout / security: <--- €2 --->
    OpenCollective foundation: <--- €1 --->

    Credit card processing fees: €0.50

    Total: €10.50

    [Pay by Credit Card ] [ Pay With PayPal ]

**Comment by erickrico** [comment]
hey, this is the first approach to the donation "recipe
![fixed-amounts-comission-optional-on](https://cloud.githubusercontent.com/assets/18429104/14658338/9c99fb28-0658-11e6-8471-3c486d4170ba.png)
![fixed-amounts-comission-optional-off](https://cloud.githubusercontent.com/assets/18429104/14658337/9c97c646-0658-11e6-847a-0f23997e64ad.png)
![fixed-amounts](https://cloud.githubusercontent.com/assets/18429104/14658340/9c9cb778-0658-11e6-9f1f-72907a6754b3.png)
![slidebars](https://cloud.githubusercontent.com/assets/18429104/14658339/9c9cb480-0658-11e6-8462-27acca03ee8e.png)



", i still have to work on the wording of the modal, feel free to give any kind of feedback 😬

**Comment by xdamman** [comment]
I really like it. 
Few comments:
- Stripe shouldn't be an option (and we should label it "credit card processing fee")
- not sure what are the boxes on the left. In that scenario people won't have the option to edit it. So we should also remove the input type text on the right. 
- I love the sliders!
- I'd do a version with stripe and OC fees at the bottom and then have a line with "Total" (for the case when fees are added on top and not part of the donation)

**Comment by erickrico** [comment]
im on it

**Comment by erickrico** [comment]
![v-set-amounts-10plus](https://cloud.githubusercontent.com/assets/18429104/14681859/8a62d7aa-06e8-11e6-9af8-dc562affef66.png)
![v-oc-optional-on](https://cloud.githubusercontent.com/assets/18429104/14681863/8a633eac-06e8-11e6-918d-df6f26145598.png)
![v-oc-optional](https://cloud.githubusercontent.com/assets/18429104/14681861/8a63156c-06e8-11e6-8f4e-4750b9737c18.png)
![v-set-amounts](https://cloud.githubusercontent.com/assets/18429104/14681860/8a62cd1e-06e8-11e6-88fa-a426a0f44f4f.png)
![v-sliders](https://cloud.githubusercontent.com/assets/18429104/14681862/8a63186e-06e8-11e6-83db-380e054ec0ec.png)

**Comment by xdamman** [comment]
This is great! 👍 

Just also do a version with $100 per month and with two buttons at the bottom:
[ Pay by Credit Card ] [ Pay with PayPal ]

And ship it! :-)

**Comment by carlosascari** [comment]
@xdamman Could you tell me which, if there is an endpoint or something that exists that will tell me the fee amount, comission and the collectives where the donation will be distributed?

**Comment by xdamman** [comment]
We are still discussing that with @asood123. For now you can hard code it. 

    const userEditable = true; // show slider if true
    const connectedCollectives = [{slug, name, mission, percentage}, {}, {}];
    const processingFees = 0.30 + 0.029 * amount;
    const feesOnTop = true; // add the processing fees + OC fees on top of amount, otherwise, subtract those fees from amount

where `percentage` would be the percentage from the initial amount that should be attributed to that collective. The balance should go to the current collective.

**Comment by carlosascari** [comment]
Got it. 

I also wanted to ask why you want two buttons saying: Pay with Paypal and Pay with Creditcard.
Wont the user be redirected to the paypal site and still have to choose between credit card and their paypal email?

**Comment by erickrico** [comment]
![desktop](https://cloud.githubusercontent.com/assets/18429104/14683207/1f1818aa-06ef-11e6-9b00-7f1abfa90e77.png)

**Comment by xdamman** [comment]
It depends if the host has set up their paypal account in such a way that they can also accept credit card payments. It's not the default. Regardless, I think it's good to have those two options.
I'd just put Credit Card first, then PayPal.

Also, can you add the disclaimer text below those buttons:
*By clicking above, you are pledging to give Women Who Code 501(c)((3) USD $1.00 per month for WWCode Austin. You can cancel anytime.*

**Comment by erickrico** [comment]
since that exact text is displayed one step before on the flow, i think it will be redundant, should we still add it?

**Comment by erickrico** [comment]
![screen shot 2016-04-20 at 12 03 01 pm](https://cloud.githubusercontent.com/assets/18429104/14683328/d8493f70-06ef-11e6-9470-32659ac3a270.png)

**Comment by xdamman** [comment]
We should remove that text from that step, it should only be just without clicking on Pay by credit card or Pay with Paypal.

**Comment by carlosascari** [comment]
@xdamman The `Credit Card Processing Fee` can only be displayed AFTER choosing either paypal or creditcard, which by design as of now, it is not possible. @erickrico is working on a redesign to allow you to select the type (paypal or creditcard) before you donate. 

What do you think?

**Comment by xdamman** [comment]
Mmmm... good catch. You are right. Then maybe better to find a way to select the payment method and depending on that showing the payment processing fees. 
And by default, it should be Credit Card (and note that for most collectives there will only be one payment method)

**Comment by erickrico** [comment]
![toggle](https://cloud.githubusercontent.com/assets/18429104/14684065/ad7c1cfa-06f3-11e6-9b22-5e0b816cceb1.png)

**Comment by xdamman** [comment]
Maybe add the processing fee just below the donation method? So that there is a direct link between the method you choose and the cost associated to it.

**Comment by xdamman** [comment]
Any update on this?
I think that donation method should be at the bottom. It feels weird in terms of hierarchy of information to have it separated from the donate button. The bottom should be about the actual payment, including the method and related processing fees.

**Comment by erickrico** [comment]
ok, Ascari is already working on it, let me make a new version, with more contextual information

**Comment by erickrico** [comment]
hey, what do you think of this approach, all editable fees go to the top, we create a "sub-total" they pick the donation method, and afterwards you get the total amount the donation, either if we add the credit card processing fee on top of the actual donation or as a part of it 
![slack_for_ios_upload_1024](https://cloud.githubusercontent.com/assets/18429104/14751193/5367a6d4-088e-11e6-88f0-20738f0ac74c.jpg)

**Comment by xdamman** [comment]
Love it!

**Comment by asood123** [comment]
this was done a while back.
