### ISSUE TITLE
Expense dashboard filtering breaks after payment

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1500]
When I am paying out expenses from the [dashboard](https://opencollective.com/opensourcecollective/collectives/expenses) and I click 'pay with paypal', once the payment goes through, the filtering by status (pending, approved, paid), resets. It still shows that it's filtered by 'approved' but all the pending and paid ones jump back into the list. If I select a different filter and then go back to approved, it works, until another payment goes through and resets again.

As you can see here, 'approved' is selected but a pending expense is displayed.
<img width="539" alt="screen shot 2018-12-01 at 4 17 26 pm" src="https://user-images.githubusercontent.com/5498878/49323763-21b89300-f585-11e8-9232-5f48ca741990.png">

**Comment by alannallama** [comment]
Hey @znarf is there any update on this? Thanks!

**Comment by alannallama** [comment]
Just following up on this bug again. It makes processing expenses a lot harder. @znarf have you had a chance to look into it?

**Comment by Betree** [comment]
@alannallama I'll be working on this issue today

**Comment by Betree** [comment]
I haven't solved it yet, but here is what I found:

- After `PayExpenseBtn` succeed, `ExpenseWithData` is re-rendered fully (why?). 

- The `options` callback in `addExpensesData` is called without the `props.data.variables.status` filter that we would like to have: it is stored in Apollo's cache and is not passed in this callback.

- It looks like a bug in Apollo's: there's no reason to re-trigger the `options` callback here.

**Comment by alannallama** [comment]
I love the new "ready to pay" filter @xdamman made. But unfortunately, it's still breaking after each time I make a payment :(

<img width="525" alt="screen shot 2019-03-01 at 5 43 42 pm" src="https://user-images.githubusercontent.com/5498878/53616903-b21c7780-3c49-11e9-9eac-d203fe46a1d9.png">

**Comment by xdamman** [comment]
I know :-(
I looked into it in #1770 but there is no easy solution. It's a deep bug. @Betree is going to look into it more. Hopefully there is a way out.

**Comment by alannallama** [comment]
The filters were sticking for a little while (yay) but then it broke again (boo). No idea what changed... I was uxing the same browser on the same day, and first it worked for a few payments, then it broke again.
