### ISSUE TITLE
"cannot read property info of null" error

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1501]
This has come up several times. I click "pay with paypal" and this error comes up, and the expense doesn't show as paid and the pay button remains. However, if I reload the page, it shows that it actually went through and has been paid. Most recently happened on [this expense](https://opencollective.com/sustainoss/expenses/5742).

<img width="374" alt="screen shot 2018-12-01 at 4 36 15 pm" src="https://user-images.githubusercontent.com/5498878/49323874-b6bc8b80-f587-11e8-8fd4-2801293ae1a5.png">

**Comment by alannallama** [comment]
This is still happening, FYI

**Comment by znarf** [comment]
@alannallama @xdamman What is the status on this?

**Comment by xdamman** [comment]
This is a duplicate of #1516 
It's fixed in https://github.com/opencollective/opencollective-api/pull/1576
