### ISSUE TITLE
Not possible to unsubscribe from "Thank you for your * donation to *" emails

### ISSUE THREAD

**Issue by jancborchardt** [opencollective/opencollective#1502]
**Describe the bug**
Every month you get these nice mails thanking you for your donations. While they are cool, after some time they get a bit annoying and people know that they donate regularly. ;) But there seems to be no "unsubscribe" link. I can "manage your subscriptions here" but I don’t want to stop donating.

**To Reproduce**
1. Donate to a collective
2. Wait a month
3. Get a "thank you" email
4. Wait another month
5. Get another "thank you" email

**Expected behavior**
I expected a link to "Unsubscribe" in the footer of the mail.

**Screenshots**
Mails every month:
![open collective thank you mail](https://user-images.githubusercontent.com/925062/49340729-4f184600-f644-11e8-9ee8-431ba1e18efb.png)

**Desktop (please complete the following information):**
Not really relevant, but:
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 63

**Comment by znarf** [comment]
We should:
- add an unsubscribe link in the footer of these emails, it should be automatically available from `data.unsubscribeUrl`
- check `active` status from the `Notifications` before sending the email

**Comment by piamancini** [comment]
Is this stale or solved? I think emails have an unsubscribe @xdamman can you confirm please?

**Comment by znarf** [comment]
Maybe @flickz can you look into that?

**Comment by flickz** [comment]
Sure, I will.
