### ISSUE TITLE
Email reminder for pending orders

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1508]
User story:

I make a donation and I chose "wire transfer". I receive the instructions by email to make the wire manually to the host.

Two things can happen from here:
1- I make the wire but the host doesn't record it
2- I forget to make the wire

To solve this, it would be good to send an email reminder to the host after a few days (3-5?) to either confirm with one click that they have received the money or to send a reminder to the donor with the instructions (and maybe with a button to cancel the order).

After the second reminder, we should give the option to the host to cancel or delete the order.

**Comment by alanna** [comment]
@znarf requested this and a few other issues related to pending orders be broken down into clearly seperate issues. So this one is about a notification email to the host of pending orders. I'm taking out the part about a way to delete/cancel a pending order and raising a new issue for that.

Some more clarity about the desired notifications:

1. When a pending order is created, trigger a "new pending financial contribution" email to the host admin.

> Subject: New pending financial contribution of [amount] to [Collective]

> [Collective] has a pending financial contribution of [amount] from [payer]. They have been sent bank wire transfer instructions to transmit the funds to [host].

> [Button linking to the pending order]

2. 4 days later, send another email to follow up

> Subject: Pending financial contribution confirmation: [amount] for [Collective]

> Has [amount] arrived in the bank account of [host] from [payer] for [collective]?

> [Button to mark as paid] or [view details - link to pending order]

**Comment by leonardohof** [comment]
Hi @znarf! Can I work on this issue?

**Comment by znarf** [comment]
@leonardohof it's for you

**Comment by znarf** [comment]
As a follow up, would be great to also warn the donator following the initial specs from @xdamman . But let's make sure we're more precise in the way we're handling the PENDING/MANUAL status before.

**Comment by znarf** [comment]
🏆 This issue was completed by @leonardohof 

To claim the bounty please, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new  Please make sure to mention the ticket number in the invoice and in the expense title.
