### ISSUE TITLE
Expose a route for tier banners

### ISSUE THREAD

**Issue by phated** [OpenCollective/OpenCollective#151]
Currently, I have to embed a ton of links into my README to show the supporters of my project.  However, it would be really nice if the OpenCollective website generated a banner image of the backers and served it from a URL like `/:slug/:tier/banner.png` (or `.svg`) so I could embed a single image into the README and link it to my collective.

**Comment by piamancini** [comment]
@xdamman can you help us out with this?

**Comment by xdamman** [comment]
It's a great idea. I'll do that. I think it's great for easy inclusion at the bottom of a blog post or in an email newsletter. However, note that the problem with this solution is that you won't be able to make the image link to the website of each respective sponsor.

**Comment by phated** [comment]
I'm fine with that. My goal is to direct everyone to the collective and they can navigate backers from there. More people reaching the collective hopefully equals more backers.

**Comment by ScottFreeCode** [comment]
Is there any way to get SVG to scale/wrap to fit the width of the screen/window/tab/whatever the way individual pictures could in HTML?

On the other hand, using a banner-style approach could open the door to word-cloud-like collages of backer images... And maybe to other formats. A link to the collective as a whole could be nicely differentiated from links to the individual backers that way.

**Comment by xdamman** [comment]
You asked, you get https://github.com/OpenCollective/opencollective-website/pull/320

**Comment by xdamman** [comment]
It's now live, e.g. https://opencollective.com/gulpjs/backers.svg
![](https://opencollective.com/gulpjs/backers.svg)

Or https://opencollective.com/yeoman/backers.png?margin=10&width=300
![](https://opencollective.com/yeoman/backers.png?margin=10&width=300)

Or https://opencollective.com/mochajs/sponsors.svg
![](https://opencollective.com/mochajs/sponsors.svg)

**Comment by phated** [comment]
@xdamman you are amazing! thanks!

**Comment by xdamman** [comment]
I forgot, you can also add a parameter `avatarHeight`
e.g. https://opencollective.com/gulpjs/backers.svg?avatarHeight=128
![](https://opencollective.com/gulpjs/backers.png?avatarHeight=128)

https://opencollective.com/yeoman/backers.svg?avatarHeight=32
![](https://opencollective.com/yeoman/backers.svg?avatarHeight=32)

**Comment by akkie** [comment]
What is the preferred way to embed the SVG images into the README?

**Comment by xdamman** [comment]
@akkie github doesn't like svg with internal links. Have a look here to add your backers and sponsors automatically in your readme.  https://github.com/OpenCollective/OpenCollective/wiki/Github-banner

**Comment by piamancini** [comment]
Hi @akkie the link that @xdamman is pointing you to it's the PR you've merged already.
