### ISSUE TITLE
CORS removed at some point

### ISSUE THREAD

**Issue by phated** [opencollective/opencollective#1510]
**Describe the bug**
CORS was added in https://github.com/opencollective/opencollective/issues/342 but it was removed at some point.  This is breaking gulp's backers display on our website.

**To Reproduce**
1. Go to https://gulpjs.com
2. Open your browser console
3. See the CORS error

**Expected behavior**
The APIs to have CORS.

**Comment by phated** [comment]
Scratch that, it was a configuration problem on my end. Sorry.

**Comment by Betree** [comment]
@phated Well I've seen this recently and wanted to open an issue too. I think all the `json` endpoints are indeed not properly adding CORS headers.

The `https://opencollective.com/api/groups/{collective}/backers` endpoint however works. We should either update the Export documentation to mention this endpoint or fix CORS for the JSON ones.

@xdamman any clues about this?

**Comment by phated** [comment]
Cool. My issue seemed to be happening because cloudflare was sniping my connection. Which happens when I'm using a VPN.

**Comment by dodgepong** [comment]
We're hitting this issue, too, CORS doesn't seem to be available on JSON files made available by the API. We're trying to fetch our collective member JSON for our backer display and getting `No 'Access-Control-Allow-Origin header is present on the requested resource`. This is for files such as https://opencollective.com/{collective}/members/all.json

**Comment by znarf** [comment]
@dodgepong CORS are not available yet on this set of endpoints.

https://github.com/opencollective/opencollective-frontend/blob/master/src/server/routes.js

A potential solution is to add CORS for all the JSON routes here: https://github.com/expressjs/cors PR welcome :-)

**Comment by dodgepong** [comment]
Upon further reflection, I suppose it's maybe not _intended_ for this endpoint to be used as a component in a backer display, and more for just exporting as JSON? The endpoint that @Betree mentioned above should work for our purposes instead, I think. If that's the case, it would be nice to be more documented in the collective settings, I suppose.

**Comment by znarf** [comment]
As discussed here for example https://github.com/gulpjs/gulpjs.github.io/pull/103, we introduced a new REST endpoint with CORS enabled.

@dodgepong would be great to also use that endpoint for OBSProject, see this issue https://github.com/opencollective/opencollective/issues/2037
