### ISSUE TITLE
Gift cards admin: list gift cards

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1512]
- Show existing gift cards as a paginated list
- Show basic information about gift cards
  - If it's claimed
  - Who claimed it (account, or the email it was sent to)
  - Balance
  - Amount
  - Date of creation
  - Expiry date
  - If not redeemed yet, the redeem link
  - (optional) gift card description AKA custom message

To go in the way of https://github.com/opencollective/opencollective/issues/1451, the new component should take care of maintaining its own isolated state.

**Comment by Betree** [comment]
@cuiki  @znarf @xdamman A first sketch for the admin dashboard 

https://app.moqups.com/Cuiki/JSZNg8YwFr/edit/page/a23fa75ed

![Admin dashboard](https://user-images.githubusercontent.com/1556356/49502976-96861880-f876-11e8-88ec-035715b90781.png)

**Comment by Betree** [comment]
@znarf Good point, here is the version with `View details`:

![01 _dashboard 1](https://user-images.githubusercontent.com/1556356/49505709-a143ac00-f87c-11e8-974a-67ef442efc8b.png)

**Comment by xdamman** [comment]
A few questions:
- Where does the "create gift card" button lead to?
- What's the empty state?
- What are all those different icons? Are they supposed to be avatars?

I'd love to see a header to this with an explanation of what a gift card is ("Give your team members a gift card so that they can support the communities that they care about + screenshot of a donation to show that the name of the person and the name of the organization are both showing up") and directly the form to create one (amount, interval). Then below, this list of gift cards already created like this is fine.

**Comment by xdamman** [comment]
"View Details" only makes sense if there is more than one information to show.
What is "Custom message"? What's the use case for such message?

Either you have like before directly the link to redeem that people can copy paste, or you have a "view redeem link" that shows the entire URL (not just the code) with a "copy to clipboard" link (like on github when cloning a repo)

**Comment by xdamman** [comment]
Maybe @cuiki can take a quick stab at this with Moqups to directly include the create gift card form on this page at the top (this will be the number one user intent by going to this page) and adding a word of explanation and mini FAQ (and showing a preview of how donations mades with such gift cards are displayed).

We need to explain that the payment method will only be charged when a user uses the gift card, not when the gift card is created. Showing a FAQ in context would be useful.

**Comment by Betree** [comment]
@xdamman 

- The button leads to this view: https://github.com/opencollective/opencollective/issues/1513#issuecomment-444427874

- Haven't specified this yet, what about a message like:
> No gift cards yet! [Create your first gift card(s)](https://opencollective.com/org/edit/giftcards/new)

- The icons are a quick indication of if the gift card is claimed or not. I've used [this](https://styled-icons.js.org/?s=giftcard) and [this](https://styled-icons.js.org/?s=accesstime)

- Regarding the header with explanation of what a gift card is with a screenshot, it totally makes sense if no gift card has been created yet, we should definitely do that. I'm not so convinced that it will be useful if some gift cards have already been created.

- Not so convinced too about having the form on the same page, I have in mind that some organizations will end up with hundreds if not thousands of gift cards so we should keep the list page as clear and concise as possible.

- The custom message would allow organizations to attach a small message when sending the gift cards that will be shown in the mail. The use case is for companies to provide a more personalized / contextualized info about this gift card, we could imagine things like `Merry Christmas folks, please use that to support the projects we all use and love at Company000!`

**Comment by xdamman** [comment]
For 100 visits to this page, 90 will have zero gift cards created, 7 will have less than 10, 3 will have more than 50. 
That’s why I’d love to have the form ready to be used right there above the fold on that page. That’s the number one action we want to optimize for. Viewing the list of past gift cards is useful but secondary to that.

**Comment by znarf** [comment]
@xdamman any user interface with that pattern you've seen recently?

**Comment by Betree** [comment]
I had forgot an important information on the mockup that is the expiry date. I've added it to the details.
