### ISSUE TITLE
Paid expense not showing up in paypal

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1516]
A user got in touch saying [this expense](https://opencollective.com/redux-devtools-extension/expenses/5878) was notified as paid, but the funds didn't arrive in his paypal. I searched through the paypal activity log, but I'm unable to find a record of the transaction. The expense does not tell me if it was paid through the API (in which case it could be a bug) or manually (in which case it could be human error)—can someone look at the database and get more information?

**Comment by alannallama** [comment]
Another report from a different user - same problem with [this expense](https://opencollective.com/qubes-os/expenses/5857).

**Comment by alannallama** [comment]
Looks like this also affected this whole series of payments for [SFGlobalShapers](https://opencollective.com/sfglobalshapers/expenses).

<img width="713" alt="screen shot 2018-12-07 at 11 48 30 am" src="https://user-images.githubusercontent.com/5498878/49616550-17c7e180-fa16-11e8-9f0c-643b64ffa50d.png">

**Comment by xdamman** [comment]
19 expenses are marked as PAID but don't have a transaction in the ledger:

```sql
SELECT * FROM "Expenses" e
LEFT JOIN "Transactions" t ON t."ExpenseId" = e.id 
WHERE e.status = 'PAID'
  AND t.id IS NULL
  AND e."deletedAt" IS NULL
```

First one was created on October 30th and updated November 30th.
Then all following ones have been created after November 13th and updated in December.

So it looks like something that we did recently on the backend broke this.

**Comment by alannallama** [comment]
@xdamman can you please check the transactions I put through today? I am wondering if it's related to #1501 which I saw many times when I did payments just now.
