### ISSUE TITLE
Get companies to offer their developers gift cards to support open source

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1520]
When you give $50 to someone to treat themselves, it makes them happy.
But if you give them $50 to give to someone else, it makes them happier.

As companies are deciding what to give for the holidays, we could try to convince them to give the "gift of giving" to their developers: "let them support the open source projects that helped them the most this year".

It would be good to have a landing page for this (e.g. on https://opencollective.com/holidays).

Copy (proposal):

### Offer your developers 👩🏾‍💻👨🏼‍💻  a gift card to donate to the open source projects that they love ❤️

Your developers have done amazing things this year. They couldn't have done as much without the support of the open source community. That's where they learn, that's where they can reuse tools, libraries, modules so that they don't have to reinvent the wheel and they can focus on making it work for your particular needs.

Form:

Gift card amount: (default: $50)
Number of cards: 

Company name:
Company website:

Your name:
Your email:

[Submit]

**Comment by xdamman** [comment]
What would be the best way to advertise this landing page to CTOs?

**Comment by piamancini** [comment]
we can hire someone from upwork to build us a a list of CTOs emails - that's the spammy way - or we need to use social media & get our friends to share it too. The HOTS NYC is a cto meetup on open collective we can reach out to them

**Comment by xdamman** [comment]
Best would be to have have developers ask their own CTO. It will be much more effective.
The question becomes: how do we reach out to developers and ask them to do that?

I can send an email to Hots NYC, good idea. I'm also reaching out to City-O, which is the Slack of CTOs in Paris.

**Comment by cuiki** [comment]
— Gift card page: https://www.figma.com/file/BNTNXjACDbJw2nonAcRx2U/12.-Platform-Gift-cards-Copy?node-id=0%3A1351

**Comment by xdamman** [comment]
# FAQ

- **What happens if the gift cards are not used?**
You are only charged when the gift cards are used. If you give away a $50 gift card to 10 of your employees and only 8 used it, you will only be charged $400.

- **Do I get an invoice?**
Yes, you will receive a proper consolidated monthly invoice from the [Open Source Collective 501c6](https://opencollective.com/opensourcecollective).

- **Is there an expiry date?**
By default gift cards expire after 3 months but you can define your own expiry date. If they are not used by then, they become inactive. You will never be charged if they haven't been used.

- **I received a gift card, do I need to spend it all in one go?**
No, you can use your gift card to give any amount to any collective as long as you have enough balance on the card

- **Who will show up as a backer? My company or my employee?**
Both! The person to whom you gave the gift card is the one picking the collectives they want to support. But their donation will show that they used a gift card gifted by your company and your company will also show up as a sponsor of the collective. See for example [Triplebyte](https://opencollective.com/triplebyte) that is showing up as a sponsor of [Electron](https://opencollective.com/electron).

**Comment by cuiki** [comment]
Figma files is updated with this text.

https://www.figma.com/file/BNTNXjACDbJw2nonAcRx2U/02.-Holiday-gift-card?node-id=0%3A1351

**Comment by xdamman** [comment]
For the slug I’d suggest /giftcards

**Comment by xdamman** [comment]
Or maybe better /opensource/giftcards

**Comment by znarf** [comment]
Implemented.
