### ISSUE TITLE
Enable logging through DEBUG var for all scripts and cron jobs at once

### ISSUE THREAD

**Issue by marcogbarcellos** [opencollective/opencollective#1525]
When we run any scripts (opencollective-api/scripts or opencollective-api/cron) it never hurts to show all their logs in their execution. 

We could think on a unique param/approach(through the environment variable `DEBUG`) so we can enable watching all logs from scripts/crons at once.

**Comment by znarf** [comment]
Related: https://github.com/opencollective/opencollective-api/pull/1555
