### ISSUE TITLE
Spending is $0 for Active collectives on Homepage

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1528]
![](https://d.pr/free/i/8R0BCd+)

**Comment by znarf** [comment]
@xdamman Can we create have individual bugs?

**Comment by marcogbarcellos** [comment]
After, spending a long time without being able to reproduce locally I think this may be either a caching problem or a misconfiguration

Just like locally, staging is properly working:
![screen shot 2018-12-21 at 12 01 48 pm](https://user-images.githubusercontent.com/8717041/50346074-58485480-0518-11e9-9342-8aa18dde9ac3.png)

I'm looking into the configuration part to see if it may be that.

**Comment by znarf** [comment]
@marcogbarcellos have you tracked what is the API response in production?

If you suspect caching, can you try with memcache activated locally?

**Comment by marcogbarcellos** [comment]
1) I have checked the query straight in the prod database and the values look correct but the frontend is still getting 0
2) I have checked in prod api and the graphql endpoint is called in the homepage as well
3) Thanks, I'll try with memcache locally now.
4) If it's not cache and the code is exactly the same, I'd say it may be a configuration problem which I'll check after eliminating my suspicions on the cache side.

**Comment by znarf** [comment]
@marcogbarcellos What's the output of the GraphQL endpoint?

**Comment by marcogbarcellos** [comment]
closed by https://github.com/opencollective/opencollective-api/pull/1626

**Comment by znarf** [comment]
Was that deployed?
