### ISSUE TITLE
Change featured sponsors on homepage

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1529]
We shouldn't feature those sponsors, they are a poor representation of the companies we have on Open Collective. We should only take into account amount donated that include `platformFee` or consider manually selecting them (or pick randomly among manually selected ones)

![](https://d.pr/free/i/X7zpSE+)

**Comment by xdamman** [comment]
Re-opening this. 6 months after we still have the same sponsors featured and they are not a good representation.

**Comment by znarf** [comment]
@xdamman you didn't reopen, reopening :-)

**Comment by xdamman** [comment]
Ah I thought commenting would automatically reopen it ¯\_(ツ)_/¯
