### ISSUE TITLE
Design a better subscription page

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#153]
It needs some serious design love. Data is all there.

**Comment by erickrico** [comment]
can you give me a link so i can take a look

**Comment by asood123** [comment]
Here's my subscription page on opencollective: 

![image](https://cloud.githubusercontent.com/assets/6106941/16597325/4d63a1e4-42c6-11e6-901e-8377c77574ef.png)

Here's one with transactions expanded:
![image](https://cloud.githubusercontent.com/assets/6106941/16597351/667a54ca-42c6-11e6-933c-df2f9de153f6.png)

The format for showing transactions is same as what we show on the details page linked from the public pages, like opencollective.com/mochajs/donations and opencollective.com/mochajs/expenses. Ideally, we could use the same component in all three places. Those two pages also need some design love.

**Comment by erickrico** [comment]
## my subscriptions browser
![subscriptions-desktop](https://cloud.githubusercontent.com/assets/18429104/16603098/0f7f639a-42df-11e6-8886-ca5c22fa5dd8.png)
![subscription expanded desktop](https://cloud.githubusercontent.com/assets/18429104/16603099/0f809aa8-42df-11e6-86c8-7e3e0ef3634f.png)

## my subscriptions mobile
![subscription mobile](https://cloud.githubusercontent.com/assets/18429104/16603119/5002b9ee-42df-11e6-9e52-216b03a595ab.png)
![subscription expanded mob](https://cloud.githubusercontent.com/assets/18429104/16603122/5388d33c-42df-11e6-93fe-c5e0b9bc3725.png)

**Comment by asood123** [comment]
General layout looks clean. I wonder if we can format the transactions differently. All of them will say the same "Recurring Subscription". Any ideas? 

One layout for transactions needs to include fees: like $1 donation. $0.33 stripe fees, $0.05 platform fees, $0.05 host fees. That's less relevant on this page but would be useful for the full transactions page connected to a collective.
