### ISSUE TITLE
Fix paypal preapproval key balance

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1531]
Balance is off
![](https://d.pr/free/i/CpphMc+)

We should refresh the balance based on the value returned by the Paypal API

**Comment by alannallama** [comment]
This is not fixed. The balance now shows $0 all the time. This is generating support requests because new host admins are very confused by it.

**Comment by znarf** [comment]
@xdamman What's the status on this?

**Comment by Betree** [comment]
@znarf Should be fixed by https://github.com/opencollective/opencollective-api/pull/1804

However we calculate the balance from our own data, we don't refresh it from PayPal's API. It should be good to close this issue but we may keep an eye on it to ensure the balance we show don't go out-of-sync.

**Comment by znarf** [comment]
@Betree can we close?

**Comment by Betree** [comment]
Yes, we'll open another one in case we see synchronization issues
