### ISSUE TITLE
Wrong link to Event page

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1535]
As originally reported on https://github.com/opencollective/opencollective/issues/1532

https://opencollective.com/slack#backer

Clicking on "Sustain" leads to an Unknown error page because it is linking to the slug of the event without including the slug of the parent collective + `/events/`, ie. it's linking to https://opencollective.com/sustainuk-2018-442ev instead of https://opencollective.com/sustainoss/events/sustainuk-2018-442ev
It should use `collective.path` instead of `collective.slug`.

![](https://d.pr/free/i/XMevqe+)

**Comment by xdamman** [comment]
This bug was introduced by this commit from @HipsterBrown https://github.com/OpenCollective/opencollective-frontend/commit/f8a8d071054f9b7f1fcd323a36838402dc880966

@HipsterBrown can you take this on?

**Comment by marcogbarcellos** [comment]
@xdamman the problem isn't between Nick's commit and the way it was before, both would throw errors because the `type` of the Collective is `EVENT` and the correct path would be `/${parent_collective_slug}/events/${collective_slug}`.

I'll create a PR to fix it...
