### ISSUE TITLE
Wrong avatar alignment in Team section

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1536]
It used to be that the avatar would be left aligned with the name of the person on the right of it.
What changed?

![](https://d.pr/free/i/0JS6kb+)

**Comment by cuiki** [comment]
Hi guys, so the last iteration that Design did presents the core-contributors in a component very similar to the sponsor card. See here: https://tafka.d.pr/OypZa7

However, if that is not doable right now, then the way it used to be is like Xavier says: https://tafka.d.pr/JeKrfK.
