### ISSUE TITLE
Don't show goals if no goals and no balance

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1538]
The page of a collective freshly created doesn't look great with no goals and no balance

![](https://d.pr/free/i/H77vX4+)

**Comment by qatarstreets** [comment]
Can I know what do you want !!

Sent from Mail for Windows 10

From: Xavier Damman
Sent: Thursday, December 13, 2018 7:10 PM
To: opencollective/opencollective
Cc: Subscribed
Subject: [opencollective/opencollective] Don't show goals if no goals and nobalance (#1538)

The page of a collective freshly created doesn't look great with no goals and no balance
