### ISSUE TITLE
Paid expense with method 'other' is not accounting for the host fee

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1539]
Added a host fee in an expense marked with payment method 'other'
The fee shows up in the front end but it's not accounted for in the transaction
![screen shot 2018-12-13 at 1 25 51 pm](https://user-images.githubusercontent.com/3671070/49959185-db472a80-feda-11e8-9fef-76d14cf37bbf.png)

**Comment by piamancini** [comment]
the same happened with Symfony. Host fee wasn't computed and it's showing up in the collective's budget preventing them from connecting their host. I am manually fixing it.

**Comment by xdamman** [comment]
There is definitely an issue on how it's being displayed on the frontend but the transactions for `ExpenseId` 6094 look good but I'm not sure if you have manually updated it (please update the `updatedAt` if you ever manually edit a record).

Also what's the Symfony `ExpenseId`?

**Comment by piamancini** [comment]
> I am manually fixing it.

Yes,I fixed both manually since I needed to unblock the users. 

Symfony expense id 5868 Also manually fixed. None of them were accounting for host fees.

**Comment by xdamman** [comment]
Ok cool. I found the bug. Fees are recorded properly but the total amount only takes the payment processor fee into account when manually reimbursing an expense. I’ll provide a PR by this weekend.
