### ISSUE TITLE
Design a logged-in top bar for publicpage

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#154]
Will shortly look like this: 
![image](https://cloud.githubusercontent.com/assets/6106941/16530465/3e6d7ce2-3f96-11e6-8592-ea62101d0a21.png)

Ideally, it should have your face, name/email and a dropdown for "My subscriptions", "App", and "logout".

**Comment by erickrico** [comment]
hey @asood123 here is the nav bar, i dont undesrstand the "app" section, i can just add it, but i would like to understand what it does first

### Default
![screen shot 2016-07-05 at 10 54 31 am](https://cloud.githubusercontent.com/assets/18429104/16590978/659b74f2-429f-11e6-8858-12d48d632160.png)

### Loged in
![screen shot 2016-07-05 at 10 54 42 am](https://cloud.githubusercontent.com/assets/18429104/16591011/9664a81a-429f-11e6-9c10-a3701aac83ec.png)

### Loged in (drop down)
![screen shot 2016-07-05 at 10 54 51 am](https://cloud.githubusercontent.com/assets/18429104/16591023/a64e43f8-429f-11e6-9f05-3a267ee45b36.png)


### Loged in scrolled
![screen shot 2016-07-05 at 10 55 16 am](https://cloud.githubusercontent.com/assets/18429104/16591029/ae6a7d7c-429f-11e6-8b7e-2d749a77f96f.png)

**Comment by asood123** [comment]
Looks good. "App" is supposed to take you to app.opencollective.com, which is used by hosts and members to approve expenses. We'll eventually support that functionality on the website but for now we need to link to it somewhere.

**Comment by asood123** [comment]
Also, this bar will be on top of all public pages too

**Comment by asood123** [comment]
I plugged LoginTopBar component into a couple of places. Need help plugging it into homepage, profile page and public group. One option is to extract out the right most section with shows `login` or the dropdown menu. 

Ideally, would like to use `LoginTopBar` everywhere and remove `PublicTopBarV2` and `PublicTopBar` and corresponding files from the codebase.

**Comment by asood123** [comment]
This is fully implemented now. Closing.
