### ISSUE TITLE
Support login on website

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#155]
Without a login, we are blocked on doing a bunch of things like faster payments (since payment method is stored), collective to collective donations, approving expenses on website, etc.

I have a basic login running on Website. Tricky part is how to get the users to create an account. 

**Option 1:** Create an account before you can donate (that's how Patreon does it). It's the easiest but I think it sucks for users.

**Option 2:** Let them donate without a login and send an email to verify account
- User makes a donation
- We send them an email thanking them (with a link to subscriptions - no token) and another email with a verification link
- When they click on the link, we ask them to create an password

**Option 3:** Extend the current token system used for Subscriptions to the whole frontend
- Anytime you try to access a restricted part of the site, we ask for your email. 
- We send you a link with a token. 
- On click, we remove the token from the url and store it in the localStorage and voila!
- I don't know if users will feel that this is as secure as a login

Open to other ideas? @xdamman @sedubois @piamancini

**Comment by xdamman** [comment]
I'd definitely go for option 3. But I'd make it clear that you are logged in with an easy option to logout. 

That's the slack model with their "magic link"

**Comment by piamancini** [comment]
agree on making sure they know they are logged in.
with that seems the best ux

**Comment by asood123** [comment]
#3 is the best user experience. Let me figure out how to make it happen piecemeal, so we aren't blocked on this.

**Comment by asood123** [comment]
Fully implemented with: https://github.com/OpenCollective/opencollective-website/pull/357
