### ISSUE TITLE
Add VAT when submitting expense

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1552]
- [ ] add a VAT (int) column to represent the amount in cents of VAT to the `Expenses` table
- [ ] add VAT input field when creating/editing an expense (need to make clear that `amount` is the total amount including VAT)
- [ ] Include total VAT for all expenses in the monthly report for hosts
- [ ] Enable VAT for submitting expenses for all hosts where currency is `EUR`

**Comment by piamancini** [comment]
is this still relevant?

**Comment by xdamman** [comment]
Still relevant but only applies to European collectives that are part of the host (and not independent unincorporated partnerships). So I wouldn’t prioritize it now but we should just keep this in mind.

**Comment by Betree** [comment]
Closing in favor of a more generic issue: https://github.com/opencollective/opencollective/issues/4532#issuecomment-899302701
