### ISSUE TITLE
VAT for tiers

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1553]
- [x] Add a way to record the VAT percentage on a per tier basis (could be a new column or a `settings` JSON column like in the `Collectives` table)
- [ ] If `collective.currency` === 'EUR', add VAT percent input field when creating/editing a tier (with default values per preset, e.g. donation: 0%, service: 21%)

**Comment by Betree** [comment]
@xdamman With what we discussed in Berlin, do we agree that this issue is now deprecated in favor of having the tiers VAT based on the tier type in host's settings?
