### ISSUE TITLE
Collective Deactivation by host admin

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1556]
## User story 
As a host admin, I can deactivate a collective, so that we can comply with user requests to shut their collective down.

## Best solution for this problem
When a collective is deactivated, it needs to be flagged as such in the database, the donate buttons disabled, and some kind of visual design that lets users know they are looking at an inactive collective. I'm not sure if this option should be available only to host admins, or also to core contributors to deactivate their own collectives.

## MVP
A link visible to host admins that deactivates the collective, similar to the "add funds" option we have now. 

## Metrics 
Requests to shut down collectives are actioned more quickly and users are satisfied with the experience.

## Documentation 
Add explanation of what deactivation means to the help docs.

**Comment by alannallama** [comment]
Related to #1317 (user-facing feature as opposed to admin)

**Comment by lsmith77** [comment]
it might also be a useful feature for collectives in case they have some governance issues to sort out and do not want to collect donations for a period as a result.

**Comment by znarf** [comment]
That was done!
