### ISSUE TITLE
VAT for create order 

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1557]
Requires https://github.com/opencollective/opencollective/issues/1553

- [x] If there is a VAT specified for the tier being ordered, we need to add the VAT to the amount at check out (design needed)
- [ ] If the order is made on behalf of an organization, we need to ask: "Do you have a VAT number?" (design needed)
- [x] Record the country of the organization
- [ ] if the country is outside of the EU, there is no VAT
- [ ] else if the country of the organization is different than the country of the host, and if the organization has a VAT number, then the VAT added should be zero
- [ ] Add VAT to the invoice generated (if zero, still need to show zero)

**Comment by Betree** [comment]
Organizations with a VAT number should not pay any VAT - at least that's the ways it works in France. Is it like so in other European countries?

**Comment by xdamman** [comment]
It’s the same rule across Europe. They have to pay it if the vendor is in the same country but they get it back from the state. 
If the vendor is in another country, they don’t have to pay it if they can show a valid VAT number. The reason for this is because if they had to pay it they would have to ask to get it back but the French state shouldn’t reimburse the VAT that has been paid to another state.

**Comment by Betree** [comment]
![selection_999 043](https://user-images.githubusercontent.com/1556356/51737574-3a2cc180-208d-11e9-8c99-5227ca52f1de.png)

**Comment by Betree** [comment]
Here is an example of the upcoming data structure in host `settings`. It supports for custom tax names (to avoid being limited to EU VAT) and values depending on tier type.

```json
{
  "TaxesIdentificationNumber": "______________",
  "TiersTaxes": {
    "service": {
      "name": "VAT - Services",
      "value": 0.1,
    },
    "product": {
      "name": "VAT - Products",
      "value": 0.2,
    }
  }
}
```
