### ISSUE TITLE
Review automatic yearly report

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1559]
We automatically send a yearly report to backers and hosts.
We should review them to make sure they are still working properly.

**Comment by xdamman** [comment]
This is the text version of my 2018 report (to review copy):

---

Hi Xavier Damman!

2018 is already ending 🎉. That was fast!

In those troubled times of social unrest and climate change, we believe more than ever in the strength of our communities.
Whereas big institutions that surround us are increasingly unable to make our voice heard, our communities make our contributions matter.
They give us an opportunity to connect and to learn from each other.
They give us the opportunity to make meaningful contributions. They give us meaning.

But we need to nurture them. They need us. They need us to contribute with our time and our skills, to attend their events, to promote them in our social networks and to support them financially.
If we all do that, we will be surrounded by thriving communities that will give everyone of us the opportunity to do meaningful contributions in the world 🌍

In 2018 you have contributed a total of €4,950, $64 and £6 across 18 collectives:

BrusselsTogether ASBL
  €3,200 to BrusselsTogether Media https://opencollective.com/brusselstogether-media
  €400 to WeBrussels https://opencollective.com/webrussels
  €110 to BrusselsTogether https://opencollective.com/brusselstogether
  €80 to Fearless Cities Brussels https://opencollective.com/fearlesscitiesbrussels
  €60 to listes citoyennes https://opencollective.com/listescitoyennes
  €60 to CodeNPlay https://opencollective.com/codenplay
  €60 to Co-Labs https://opencollective.com/co-labs
  €50 to HuNeeds  https://opencollective.com/huneeds
  €20 to CIN https://opencollective.com/civicinnovationnetwork
  €16 to Mastodon.brussels https://opencollective.com/mastodonbrussels

Open Collective Europe ASBL
  €700 to The New Citizen Europe https://opencollective.com/thenewcitizen-europe
  €80 to En Marche.be https://opencollective.com/enmarchebe
  €50 to TealWiki https://opencollective.com/tealwiki
  €40 to lab.davan.ac https://opencollective.com/labdavanac

Open Collective UK
  £6 to Norwich Sharing City https://opencollective.com/norwichsharingcity

Open Source Collective 501c6 (Non Profit)
  $40 to Cypress.io https://opencollective.com/cypressio
  $24 to Parcel https://opencollective.com/parcel

Diem25
  €24 to DiEM25 Spontaneous Collective (DSC) Brussels https://opencollective.com/dscbrussels

\>\>\> Tweet those stats <<<
https://twitter.com/intent/tweet?text=%F0%9F%8E%81%20In%202018%2C%20I%20have%20contributed%20a%20total%20of%20%E2%82%AC4%2C950%2C%20%2464%20and%20%C2%A36%20across%2018%20collectives&url=https://opencollective.com/xdamman

Thank you for the contributions that you made this year. Thank you for playing your part in building this future 🙏.


Don't forget:
- You can manage your subscriptions here: https://opencollective.com/xdamman/subscriptions
- You can discover other great collectives to support here: https://opencollective.com/discover
- We are an open collective ourselves and our code is under MIT license. We welcome contributions of any kind! 😊 https://github.com/opencollective/opencollective


- For the Open Collective Community
@PiaMancini and @xdamman



                          - Open Collective -
                    We can do great things together

       Made with ❤️ in Berlin, Brussels, Guadalajara, NYC and Paris


For questions or feedback just reply to this email.
You can also follow us on https://twitter.com/OpenCollect or come chat with us on our public Slack channel https://slack.opencollective.com.

**Comment by alannallama** [comment]
Looks good @xdamman ! Some small changes:

Both times you said 'those' it should be 'these'.

Whereas big institutions that surround us are increasingly unable to make our voice heard
-> While it seems increasingly difficult to get big institutions to listen to our voices

But we need to nurture them
-> But we need to nurture our communities

to do meaningful contributions in the world
-> to meaningfully contribute to the world

**Comment by piamancini** [comment]
looks good! Do you want to maybe add spectrum ? seems like a good opportunity.
