### ISSUE TITLE
Discover page → Unbalanced margins in discover page

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1560]
The margins between collective cards seem off and unbalanced on https://opencollective.com/discover (left and right margins are massive compared to top bottom margins). What do you think @cuiki ?

![](https://d.pr/free/i/37zN7f+)

Overall, the first impression when looking at that page is that it's visually a downgrade compared to the previous version: http://opencollective-prod-website.herokuapp.com/discover

Can we improve that @HipsterBrown ?

**Comment by Mayekita** [comment]
I made a new mockup with some minor changes to the page so we can even have a filter for the pledged collectives, wich is the same issue that we have here #1387.
I think both issues can solve here:
https://www.figma.com/proto/D9ToLTukHKrcoHq3vNKB9Mea/05.-Discover?node-id=1%3A2&viewport=245%2C133%2C0.26711&scaling=min-zoom
