### ISSUE TITLE
Gift cards Admin: host restrictions selector

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1561]
Replace the `Limit to opensource collectives` checkbox by a `Restrictions` field displayed as a multi-select with the following options :
- Any host
- Open Source Collective 501c6
- BrusselsTogether ASBL
- Open Collective Paris

**Comment by maddhruv** [comment]
Hey @Betree what would be the API side solution for this? Replacing the switch button for `limitedToOpenSourceCollectives` which is a boolean check with `restrictions` which would be an Array of strings require a change in the table schema as well and the logic check to find `openSourceHost`

**Comment by Betree** [comment]
Hey @maddhruv we already have the API recipe for this. We only need a way to pick the hosts for Frontend, I already plan to work on this issue as a way to demo the component specified in https://github.com/opencollective/opencollective/issues/2429.

**Comment by Betree** [comment]
Done in https://github.com/opencollective/opencollective-frontend/pull/2814
