### ISSUE TITLE
'Gift cards' marketing page.

### ISSUE THREAD

**Issue by cuiki** [opencollective/opencollective#1563]
## WHAT
Marketing page targeted to organization admins to promote the use of gift cards.

## REQUIREMENTS
- Communicate the benefits (features) for organizations of using gift cards to support collectives.
- Include examples or case studies of organizations that are already using them to validate their value.

**Comment by piamancini** [comment]
@cuiki Copy https://docs.google.com/document/d/1Ux_gwLhTrZIyd-LlRTGSa5Z-11vOJltbLqSri9Ni0q8/edit?usp=sharing

**Comment by cuiki** [comment]
Figma file: https://www.figma.com/file/0VHMcyjPv7mEr4q68hBTu6qA/12.-Gift-cards?node-id=102%3A1770

Still need copy for Slack, insert two screens and create the header graphic.
