### ISSUE TITLE
Add a link to FAQ in gift cards admin

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1564]
Add a mini FAQ at the bottom or as a sidebar to make it clear that you will only be charged when gift cards are used. See the FAQ on https://opencollective.com/gift-of-giving

**Comment by jeffin143** [comment]
@Betree Where should it be added ? Can you point the location

**Comment by Betree** [comment]
It's hard to see exactly where this should go, we don't have  proper design for it. I'd be in favor of adding a simple link to the docs so that we don't duplicate the FAQ's content: https://docs.opencollective.com/help/backers-and-sponsors/gift-cards#faq

So for clearer specs: 
- On https://staging.opencollective.com/{ORGANIZATION_SLUG}/edit/gift-cards-create
- Add a link to the position shown on the screenshot bellow with the following message:

> [Learn more about Gift Cards](https://staging.opencollective.com/opencollectiveinc/edit/gift-cards-create)

![image](https://user-images.githubusercontent.com/1556356/67701516-5d83f480-f9b0-11e9-95d1-52f2bfa3f28f.png)

**Comment by Betree** [comment]
File is https://github.com/opencollective/opencollective-frontend/blob/820c3dbf5e3eb898b612a26fa8eb7453f6133964/components/EditCollectiveForm.js#L835, though that'd be cleaner to move all that to `CreateVirtualCardsForm` (not requested for this issue).
