### ISSUE TITLE
"Sign In" in contribution flow

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1566]
For existing - but signed out - users, the first step of the contribution flow is to Sign In.

![screen shot 2018-12-20 at 10 27 31](https://user-images.githubusercontent.com/806/50276295-e6054080-0441-11e9-85a3-4042f188f8e8.png)

![screen shot 2018-12-20 at 10 30 40](https://user-images.githubusercontent.com/806/50276508-69269680-0442-11e9-858a-965f5ac61e14.png)

Now, that we have done the ground work.
- the Sign In component https://github.com/opencollective/opencollective/issues/1486
- the skeleton for the Contribute page: https://github.com/opencollective/opencollective/issues/1491

Requirements:
- Users should be able to enter their email
- On success, redirected to the confirmation screen.
- The email should be sent and received
- After using the link from the email, the user should be at Step 1, with the ContributeAs component.

[Figma Source](https://www.figma.com/file/e71tBo0Sr8J7R5n6iMkqI42d/09.-Collectives?node-id=203%3A0)

**Comment by Betree** [comment]
This part is already working
