### ISSUE TITLE
Allow contributors to add other contributors

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#157]
We need to allow for core contributors to add other core contributors. 
@xdamman suggested that we can use the existing donation flow module. 
@erickrico can we get started on some mockups?

**Comment by piamancini** [comment]
@asood123 is this issue contemplated on #244 ? If so we can close it

**Comment by asood123** [comment]
This one is a subset of other one, closing: https://github.com/OpenCollective/OpenCollective/issues/244
