### ISSUE TITLE
Contribute flow submission

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1571]
It's the final step of the contribute flow. Once the user has selected a payment method, he can submit.

Requirements:
- communicate with API
- in case of failure, display errors
- in case of success, redirect to the confirmation page (part of this issue).

![screen shot 2018-12-20 at 12 29 52](https://user-images.githubusercontent.com/806/50282415-fc67c800-0452-11e9-99f1-b273b060b6c9.png)

**Comment by Betree** [comment]
Added backend tag cause we must not forget to add the "Contribute Anonymously" feature
