### ISSUE TITLE
Users have trouble finding the cancel subscription option

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1581]
## User story 
As a financial contributor, I want to be able to cancel a subscription myself.

## Best solution for this problem
Currently the cancel subscription option is behind the three dots menu, but many users cannot find it. Can this menu be more obvious, or can the functions be revealed as buttons instead of hidden in the menu?

## MVP
"Cancel" button next to each subscription.

## Referenced Issues
#1930 
Support requests to cancel subscriptions.

## Documentation 
Ideally revealing the options should reduce the need for help documentation, but adding it explicitly to the docs could help users who search for that.

**Comment by znarf** [comment]
They can also have problems finding the subscriptions page itself. Because, only the one connected to their individual is easy to reach (from the menu). Subscriptions pages for Organizations are more difficult to access.

**Comment by cuiki** [comment]
Agreed. On it.

**Comment by Betree** [comment]
Also the current wording is incorrect in the popup menu, we say `Cancel contribution` instead of `Cancel subscription`:

![image](https://user-images.githubusercontent.com/1556356/55880383-e1a39580-5ba0-11e9-89f5-3046d04f6962.png)

**Comment by alanna** [comment]
This is important because it's still a very common support request that we get.

**Comment by Betree** [comment]
@lindatalu this is still an issue

**Comment by piamancini** [comment]
@Memo-Es where is the design for this? I can't find it in figma.

**Comment by Memo-Es** [comment]
### Design update
Consolidated design for this is [here](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=3572%3A0) Ready for implementation

@piamancini cc @Betree

**Comment by piamancini** [comment]
Thank you @Memo-Es 
@sbinlondon is owner of this project.
