### ISSUE TITLE
lower fees for donors that do not need invoices

### ISSUE THREAD

**Issue by lsmith77** [opencollective/opencollective#1583]
## User story 
_As donor, I can donoate with lower fees if I do not require an invoice so that more of my donation reaches the collective_

## Best solution for this problem
When donating, give donors the option to state of they need an invoice or not.

## MVP
_Provide a default host that issues no invoices but has non profit status and allows transfering funds to other default hosts with no fees. That way a collective can create a sub-collective using this host._

## Metrics 
_How much more money reaches collectives due to lower fees_

## Documentation 
_The goal of the documentation should be to make it easier for others to do this_

**Comment by znarf** [comment]
I don't see how fees are related to having an invoice (or not).

@piamancini @xdamman what do you think?

**Comment by xdamman** [comment]
Yes that’s what we have in mind with the idea of having multiple hosts per collective so that companies can give to a fiscal host so that they can have an invoice (which is a requirement for them) and individuals can give directly to a personal bank account in which case there is no host fee.

**Comment by znarf** [comment]
We're changing our fee structure and I don't think we're not gonna do this.
