### ISSUE TITLE
Invalid collective links in monthly report

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1584]
In monthly report there are two broken links:
- `{Collective} needs x more per month` --> Collective link broken
- `Open Collective Page`

They both don't include the website address, instead of `https://opencollective.com/collectiveslug`, we have `https://collectiveslug`

**Comment by znarf** [comment]
@marcogbarcellos @Betree how is that related to https://github.com/opencollective/opencollective/issues/1503 ?

**Comment by Betree** [comment]
Actually my sister showed that bug to me with the last monthly report she received 1st December, I wasn't aware of #1503 so this has most probably been fixed. I'll check on 1st of January just to be sure.
