### ISSUE TITLE
Prevent duplicate expenses from being submitted

### ISSUE THREAD

**Issue by sloria** [opencollective/opencollective#1586]
**Describe the bug**
The "Submit Expense" button will submit multiple expenses if a user inadvertently clicks it multiple times in quick succession.

**To Reproduce**
1. Go to the new expense page on any collective
2. Fill out the expense form
3. Click the "Submit Expense" button multiple time quickly

**Expected behavior**
The "Submit Expense" button is disabled after the first click, so only one expense is submitted.

**Screenshots**
Duplicate expenses were submitted:

![image](https://user-images.githubusercontent.com/2379650/50522016-cfd92f00-0a96-11e9-9e6c-50c4ae0258d0.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.2 (Mojave)
 - Browser: Firefox 64.0
 - Version 64.0

**Comment by Betree** [comment]
The way we handle this in new forms it to have a disabled / loading state on the button and prevent submit if this state is true.

**Comment by flickz** [comment]
@Betree Can you provide ref link on how this was handled in the new form?

**Comment by Betree** [comment]
@flickz Sure! For example this form has a `submitting` state and we disable the button if it's `true`: https://github.com/opencollective/opencollective-frontend/blob/4b18298f215ebfad9090775601013ecda70a7c71/src/components/CreateVirtualCardsForm.js#L218-L219
