### ISSUE TITLE
make it possible for donors to move their donations to a sub-collective

### ISSUE THREAD

**Issue by lsmith77** [opencollective/opencollective#1587]
## User story 
_As a donor, I can move money I donated to a collective to a sub-collective so that I can support a specific sub-collective with previously donated money to the collective (as long as both collectives are on the same host)_

Some more context:
As a collective you might have specific causes for which you want to do a donation drive. Lets say you need to collect $1000 to be able to fund a hackathon. So you create a sub-collective and ask people to either donate directly to this sub-collective. But existing donors can also move their donations from the main collective (to which they might donate monthly or yearly) to the sub-collective to show their support for the cause. This way the donors can basically fund the cause explictly reducing the need for governance to decide what happens with the money on the main collective that wasn’t collected for a specific cause.

## Best solution for this problem
_A donor can go to each collective to which they donated and see how much money they donated which has not yet been moved to a sub-collective. They can then select an active sub-collective and the amount of money that is still left in the collective that they donated and have not yet moved._

## MVP
_The MVP would be to have some way for the collective admins to track when they move money at the request of a donor and donors being able to see what is “left”._

## Metrics 
_Collectives actively using sub-collectives as a means to fund specific causes._

## Documentation 
_The goal of the documentation should be to make it easier for others to do this_

**Comment by Betree** [comment]
Hello @lsmith77 thanks for opening this!

This should already be possible, just go to the donate page of the collective you want to send the money to, then in "Contribute As" select the collective sending the money and you should be good to go - as long as the collectives are hosted by the same host you can move the funds instantaneously.

I'll close this for now but feel free to re-open if this doesn't solve your problem.

**Comment by lsmith77** [comment]
this covers the ability to move funds as an admin of a collective. it does not cover the full user story which is about “donors” reallocating the money *they* donated to a collective. and it does not even cover the MVP which is about tracking how much money an admin has moved on the behalf of a donor and showing the amounts to the donor.

so none of the things I requested above are currently possible.
I was aware that admins can move funds to other collectives on the same host for free before opening the ticket.

**Comment by Betree** [comment]
@lsmith77 Regarding the fact that users can also donate directly to the sub-collectives I'm not sure that we want to support the use case for users to re-allocate their donations.

It seems to me that once the money has been donated to a collective then it's the responsibility of the collective to decide where it should be allocated, I wouldn't like to have users re-allocating my collective's budget - even if it's to give it to sub collectives.

In this situation the right thing to do in my opinion would be for donors to contact the collective to ask them to re-allocate the money. We can think of tools to do that properly in the future but right now I don't think that we have enough demand to justify the development of such feature as it is not an easy change.

Please tell me if I'm missing something important here.

**Comment by lsmith77** [comment]
I see this as an important component in making sure funds are allocated in a way that is inline with donors, while also ensuring a constant stream of donations via "subscriptions".

Essentially what I propose is a 2 step donation process:
1) a re-occurring donation to a collective
2) an allocation of those funds to a specific cause within the collective

Note I am specifically talking about one time causes, like the organization of a specific event etc, not perpetual sub-collectives. Anyone that does not allocate their funds, essentially gives their trust to the collective. This in turn encourages, but does not require, regular engagement by donors to allocate the funds.

The alternative would either be:
1) no sub-collectives and just reoccurring donations to one main collective: which means there is no integrated feedback process for donors to communicate the causes of the collective they find more important
2) discourage reoccuring donations in favor of asking people to make one time donations to specific causes: risk of loosing donors because they might forget to donate or they currently do not have a specific cause they want to allocate to

**Comment by lsmith77** [comment]
BTW as for your suggestion about asking the collective to do this manually .. this is essentially what I am suggesting with the MVP, but then it would be nice to easily have some transparency for both the collective maintainers and the donors about how many funds can still be allocated by a specific donor.

**Comment by Betree** [comment]
Thanks for the details!

So we still need design for it but I think that https://github.com/opencollective/opencollective/issues/1784 could help us on this one by allowing the collective to display publicly something like `Moving funds to ____ collective at the request of @_____` on the transaction.

Also the new design for collectives pages will normally include a "Contact" button to directly send a message to the collective.

Could that work as an MVP?

**Comment by lsmith77** [comment]
I think these would be hopeful steps in that direction, but in that case as a collective I would still need to manage a spreadsheet to keep an overview.

**Comment by alanna** [comment]
I think this is solved by Projects

**Comment by alanna** [comment]
This is achieved by Projects now
