### ISSUE TITLE
Can not list all contributers

### ISSUE THREAD

**Issue by wsdjeg** [opencollective/opencollective#1588]
I use this tool more than half a year, and thanks for your work, but I found the feature has been changed. I just add https://opencollective.com/spacevim/contributors.svg?width=890&button=false to my readme, but it only list 30 contributers, how can I list all contributers?

**Comment by znarf** [comment]
You're right, a fix is on its way.

https://github.com/opencollective/opencollective-api/pull/1631

**Comment by wsdjeg** [comment]
Thanks for your hotfix.

________________________________
wsdjeg@outlook.com
