### ISSUE TITLE
Backers vs Contributors vs Sponsors

### ISSUE THREAD

**Issue by techtonik** [opencollective/opencollective#1589]
**Describe the bug**

This is current `vis` project backers. 3 people. Live:
![](https://opencollective.com/vis/backers.svg)
https://opencollective.com/vis/backers.svg

Screenshot:
![image](https://user-images.githubusercontent.com/515889/50547624-69970c80-0c4e-11e9-99b8-6abd4e433706.png)

But there are 5 people and 1 organization who donated at https://opencollective.com/vis#contributors

![image](https://user-images.githubusercontent.com/515889/50547625-7c114600-0c4e-11e9-8e06-18bcae1d51de.png)

Why? I want badge to list everybody who donated, but there are only 3 people. Web site doesn't explain much, but in the end I found explanation in https://github.com/opencollective/opencollective/wiki/Difference-between-Backers-and-Contributors which kind of say that contributors don't give money, but all 5 people donated, not 3. And the web site the link - https://opencollective.com/vis#contributors - is called "Contributors", nothing about backers at all. Something wrong with terminology there. It would be better to clarify the roles somehow on the website.

**Comment by znarf** [comment]
@techtonik you're absolutely right. There is even some cases of conflicting terminologies, which is an important issue that needs to be taken care of.

**Comment by techtonik** [comment]
Why not to get `backers` right for the start? Calling `contributors` only those who contributed financially is unfair, and in the end the role of backer is very important - is to get people back secured while everybody can contribute on the frontline.

**Comment by znarf** [comment]
This is being tackled in:
- https://github.com/opencollective/opencollective/issues/2116
- https://github.com/opencollective/opencollective/issues/1969

Feel free to jump on these issues to make sure we're properly addressing your points.

**Comment by znarf** [comment]
Closing. If you want us to check some specific numbers, you can contact support. http://opencollective.com/support
