### ISSUE TITLE
Add link to individual expense page from all transactions view

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1590]
Problem: currently when you go to a collective > budget > view all transactions, there is no way to get from that list to the page of one of the expenses. There are links to the user and the host, but not to the expense page itself.

<img width="1118" alt="screen shot 2019-01-01 at 1 58 27 pm" src="https://user-images.githubusercontent.com/5498878/50569588-8c9bfa80-0dcd-11e9-91a5-69a211c2cf0c.png">

## User story 
As a user, I want to be able to look at a collective's expenses and click from there to the expense page to see more details or add a comment.

## Best solution for this problem
Make the expense title a clickable link to the individual expense's page.

## Metrics 
Quicker and easier to find and interact with the expense you are looking for.

**Comment by alanna** [comment]
It would be great to have this and it's such a tiny change that I think we should keep it in the backlog. @znarf possibly a good bounty?

**Comment by Betree** [comment]
# Specs

## API

- Create a new data loader in `server/graphql/loaders.js` to load expenses by ids
- In `TransactionExpenseType`, add an `expense` field that resolves to an `ExpenseType`. Use the dataloader to load the expenses.

## Frontend

- In `lib/graphql/queries.js` -> `transactionFields` fetch the attached `expense.id` when appropriate
- On the transactions page (`/{collective_slug}/transactions`), if the transaction is an expense, add a link to it

---

Please follow our [code guidelines](https://docs.opencollective.com/help/developers/best-practices-and-code-guidelines), especially:

* The strings must be internationalized. See [/help/developers/translations](https://docs.opencollective.com/help/developers/translations)
* Whenever it's possible we must use `styled-components` to write styles. See [OC Styleguide](https://opencollective-styleguide.now.sh/)
* We're getting rid of `Bootstrap`. Please don't use it for new developments.
* When adding new dependencies, we use [fixed versions](https://docs.npmjs.com/about-semantic-versioning).
* Icons must be imported from the [styled-icons](http://styled-icons.js.org/) library.
* Tests written with Cypress must follow our [good practices](https://docs.opencollective.com/help/developers/testing-with-cypress) conventions.

**Comment by Betree** [comment]
A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged.

:warning: This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

:arrow_right: [More info](https://github.com/opencollective/opencollective-frontend/edit/master/BOUNTY.md)

**Comment by iamuchejude** [comment]
Hello! I am currently at OSCA Lagos even and am working on fixing this issue.

**Comment by iamuchejude** [comment]
Hello! I am still working on this issue.

**Comment by sudo-kaizen** [comment]
@iamuchejude still working on this issue?

**Comment by Betree** [comment]
@iamuchejude We can't hold the bounty assigned to you for too long. If you have a pull request ready please ping us, otherwise we'll have to assign someone else in the next few days.

**Comment by EslamHiko** [comment]
Hello, Can I work on this issue?

**Comment by znarf** [comment]
@EslamHiko yes, our pleasure!

**Comment by EslamHiko** [comment]
@znarf I submitted 2 pull requests to solve this issue. Waiting for your review.... Thanks.

**Comment by znarf** [comment]
🏆 This issue was completed by @EslamHiko

To claim the bounty, you can either:

    Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
    Or ask for an Open Collective gift card of the same value (to donate to other collectives)
