### ISSUE TITLE
Host dashboard doesn't load

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1591]
https://opencollective.com/brusselstogetherasbl/dashboard doesn't load (it shows a white page without anything in the console.log)

I couldn't reproduce locally.
I tried to run the frontend in dev or production environment against the staging or production api.

I put the priority tag because it is preventing a host from doing their job.

**Comment by znarf** [comment]
@xdamman Loading in production when testing with my own account.

**Comment by znarf** [comment]
@xdamman after a quick investigation, we can reproduce when Signed Out.

According to the code, this is the expected behavior:

```
{LoggedInUser && (
   <HostDashboard hostCollectiveSlug={this.props.hostCollectiveSlug} LoggedInUser={LoggedInUser} />
)}
```

This was introduced in:
https://github.com/opencollective/opencollective-frontend/commit/8a647f20947a71b7a61743c81edf30bc0a424386#diff-d2e9d5def68db721abc0640a8892caed

**Comment by xdamman** [comment]
Trying logged out was the key. Thanks for the insight.
Fix is straight forward. Pushing a PR for it right now.
