### ISSUE TITLE
Show gift cards with monthly limitations even if balance is 0

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1599]
As a user, I want to be able to see my gift cards to check their balances and subscriptions.

This could be an option in the user menu, or under subscriptions or profile.

**Comment by Betree** [comment]
@alannallama  You can normally see your gift cards by going to your profile > Edit > Payment Methods. The page shows the balances of the gift cards.

**Comment by alannallama** [comment]
This is what I see on that screen:

<img width="703" alt="screen shot 2019-01-05 at 10 46 49 am" src="https://user-images.githubusercontent.com/5498878/50717100-f5df7e80-10e9-11e9-9568-23a4abc28710.png">

**Comment by Betree** [comment]
So the issue here is that we're not showing gift cards with a $0 balance. While this behaviour is what we normally want, it should not hide the ones with a monthly limit.

**Comment by alannallama** [comment]
@Betree My giftcard should not have a $0 balance, as I've just cancelled a 30 Euro subscription to a collective that was failing every month.

**Comment by alannallama** [comment]
I have just cancelled all my subscriptions, but I still can't see my giftcard in the payment methods section. I would have expected that if I cancel the subscriptions to value would become available again on the card.

**Comment by Betree** [comment]
But the payment for the first subscription ($50) has already been made, so the balance for this month is $0. It will be $50 again on 01/02/2019

**Comment by alannallama** [comment]
I see. In that case the problem would be that it's a $0 balance card. Makes sense!
