### ISSUE TITLE
Dashboard not showing connected Paypal account

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1602]
Paypal is connected and I am able to pay expenses and refill the pre-approval balance as normal, but the dashboard is displaying 'connect paypal'.

<img width="820" alt="screen shot 2019-01-05 at 11 24 47 am" src="https://user-images.githubusercontent.com/5498878/50714194-a5155900-10dc-11e9-8369-baab708b3b1e.png">

**Comment by znarf** [comment]
@Betree should that be fixed by https://github.com/opencollective/opencollective-frontend/pull/1253?

**Comment by Betree** [comment]
@znarf Most probably. @alannallama can you confirm if this works now?

**Comment by alannallama** [comment]
Yes it's fixed now, thanks!
