### ISSUE TITLE
payout via virtual credit cards

### ISSUE THREAD

**Issue by lsmith77** [opencollective/opencollective#1603]
## User story 
_As a collective, I can to do payout via virtual credit cards so that recipients have more flexibility in using the funds_

This is especially useful for people from countries that limit the use of local credit cards for international purchases or where people do not even have access to a bank account at all.

## Best solution for this problem
_Ability to generate a virtual credit card using something like https://stripe.com/issuing that can be given to a recipient instead of a usual payout_

## MVP
_A semi-manual process where some things need to be done manually on stripe.com_

## Metrics 
_How often is this used as a payout option?_

## Documentation 
_The goal of the documentation should be to make it easier for others to do this_

**Comment by znarf** [comment]
It's a legit feature request.

I thought we already add that issue opened. But I was not able to find it.

**Comment by znarf** [comment]
Found it! Duplicate with: https://github.com/opencollective/opencollective/issues/1657
