### ISSUE TITLE
When switching from "Sign In" to "Join for free!", we should keep the email entered in input

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1605]
When switching from "Sign In" to "Join for free!" in Contribution Flow, we should preserve the email entered in input. 

This takes place in https://github.com/opencollective/opencollective-frontend/blob/22d91bc3d68adbc72c4697ebecd5d7fb26a0ff5c/src/pages/createOrderNewFlow.js#L666-L687

**Comment by Betree** [comment]
@flickz That could work :slightly_smiling_face:

**Comment by flickz** [comment]
How can I reproduce the issue to be sure would fixed it?
