### ISSUE TITLE
Allow exporting supporter data in useful format

### ISSUE THREAD

**Issue by elamadej** [OpenCollective/OpenCollective#161]
As a collective manager, I want to be able to export my supporters' email addresses in a .csv file so I can add them to my CRM/Mailchimp, etc.

For now, as a user I don't care that it's not automated  (i.e. I need to email someone at OC about the export and someone runs it manually). 

However, it's important that the data is already in a useful format, and First Name and Last Name get separated - most CRMs, and email management systems need data in that form.

Might be good to also include total contribution, so:

1. First Name (or Company Name)
2. Last Name (or Company Name)
3. Email Address
4. Currency
5. Lifetime contribution

**Comment by piamancini** [comment]
Hi @elamadej, thank you for reporting this. Totally agree. 
We are looking into it. We won't get to it this week unfortunately, but we'll keep it in planning for the next one.
