### ISSUE TITLE
Prepaid refunds not included in balance calculation

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1610]
Refunded $5500 worth of transactions made with Coinbase prepaid, but balance is still -5500. Also it seems the refunds doesn't appear on transactions.

**Comment by piamancini** [comment]
sorry the screenshot are txns from 9 months ago when we refunded the ones done with credit card. 
So effectively there are no refund transactions generated in the data base. 
I will try doing it from a collective/transaction instead of from the sponsor
