### ISSUE TITLE
Correction to expense help link

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1611]
When you submit a new expense, there is help text that appears below the host-defined expenses policy that says "You must upload a valid receipt or invoice. We should be able to see clearly on the picture (or PDF) the total amount paid, the date, the items purchased and the legal address.Need help?"

Two changes:

* 'need help?' links to the wrong URL. It should be https://opencollective.com/faq/expenses
* Add a space between the last sentence and 'need help?'

<img width="822" alt="screen shot 2019-01-08 at 1 11 27 pm" src="https://user-images.githubusercontent.com/5498878/50800951-86ff6100-1347-11e9-91cc-d7a8eacebf3b.png">

**Comment by znarf** [comment]
@alannallama You can correct the link here:
https://github.com/opencollective/opencollective-frontend/blob/bb85d9f6278c5ccf53a52e553be9b37509f8ffc0/src/apps/expenses/components/CreateExpenseForm.js#L333

While you're at it, you can add a line with just `&nbsp;` before the `<a>` to fix the spacing.

**Comment by alannallama** [comment]
Thanks @znarf - I submitted a [pull request](https://github.com/opencollective/opencollective-frontend/pull/1268).
