### ISSUE TITLE
Contribute Details: don't automatically select a default value

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1617]
While having a defaultValue is important when params are given in URL (`/donate?amount=420`) we should not automatically select an amount if not provided initially: 

![image](https://user-images.githubusercontent.com/1556356/50896954-f4c09100-140a-11e9-9d0e-1d8cc64862a6.png)

**Comment by HipsterBrown** [comment]
@Betree Why should we not select an amount initially? It limits the amount of actions required by the contributor, which would make the process faster.

**Comment by HipsterBrown** [comment]
> When making a donation you'll almost always want to set a custom amount so I'm not sure we would reduce the number of required actions by providing a default.

Is there data behind that assumption? We still have default suggested values for one-off donations, so why not select something initially? 

References for selected defaults:

- http://bradfrost.com/blog/post/designing-an-effective-donate-form/
- https://www.wsj.com/articles/the-art-of-suggested-donation-amounts-1481511960
- https://topnonprofits.com/examples/donation-page-examples-best-practices/

**Comment by Betree** [comment]
No, it's just an assumption. Let's have this conversation with @cuiki

**Comment by znarf** [comment]
I'm personally good with a default value. The initial problem I reported that even if it seemed that a default value was selected, it was requiring the user to select it again before going to next step.

![screen shot 2019-01-09 at 17 48 41](https://user-images.githubusercontent.com/806/50914432-d2dd0380-1436-11e9-9859-51925e61da73.png)

**Comment by Betree** [comment]
@znarf  For this we have two ways we can fix it:
1. Dispatch an onChange event with default value in componentDidMount
2. Provide the default value from parent

I've used first technique for PaymentMethod select if an example is needed.

**Comment by HipsterBrown** [comment]
I like option 2 since we're passing down that initial value from the parent already.

**Comment by Betree** [comment]
@znarf Then just be careful with the fact that we don't want to have all steps pre-filled by default. In other words the default value should be set in state when the ContributeDetails component first appears. Otherwise contributor could go directly to the Payment section, skipping the ContributeDetails component.

**Comment by cuiki** [comment]
Hi, sorry for being late on this. I went to have breakfast.

So the thinking (and decision) behind not setting a default value is from the psychological standpoint. Human tend to employ the minimum effort to perform a task. So by preselecting an option we risk having donations of that preselected amount and we can reduce the probability of having donations of different amounts (usually larger).

In this case, since it is donations (money) I thought that preselecting was not worth it and the perceived friction os forcing the user to make a choice is better than risking losing donations (and our OC fee) from larger donation amounts.

Of course this is always open to discussion. :)

**Comment by cuiki** [comment]
A similar (not exaclty the same) famous example is of a stat somewhere in Europe (can't remember) where the % of people registered as organ donors was critically low.

When looking into it, they realized that a form (probably the drivers license) had a checkbox that read 'Mark to become an organ donor'. Most people left it as is. So they redesigned the form and changed the label of the checkbox to 'Mark to opt out of being an organ donor'. Most people left it as is, again, but now the % of people registered as organ donors enormously increased.
