### ISSUE TITLE
ContributeDetails: wrong "Next contribution" date

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1619]
![screen shot 2019-01-09 at 18 24 57](https://user-images.githubusercontent.com/806/50916646-e8086100-143b-11e9-87e7-37bdea8e3e4e.png)

"Next contribution" date doesn't seems to calculate what we expect when adding 1 month or 1 year to a date. 

Today, on Jan 9, 2019:

- yearly -> Jan 4, 2020 (Jan 9, 2020 expected)
- monthly-> Feb 6, 2019 (Feb 6, 2019 expected)

But even if that was right, it should exactly match how "Next Contribution" is handled in Open Collective API and to my knowledge it's not working exactly like that. 

**Update**

What we want:
 - monthly: First of next month
 - yearly: First of same month next year

**Comment by HipsterBrown** [comment]
As discussed in slack, the subscriptions are charged on the 1st of the month and there is also a bug in our logic for formatting the date provided by moment. 

The following will provide the correct date for "Next contribution"
```js
interval = 'month'; // can be month or year
moment().add(1, interval).date(1).format('MMM D, YYYY');
```
