### ISSUE TITLE
#bug Unable to cancel subscription

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#162]
Trying to unsubscribe to MochaJS, I got this error: `unsupported BodyInit type`

![](https://cl.ly/110t2d342r23/Screen%20Shot%202016-07-08%20at%205.48.22%20PM.png)

**Comment by asood123** [comment]
That's a frontend error with `fetch`. I cancelled one subscription without any issues a minute ago. Can you do a complete reload and try cancelling one more time?

**Comment by asood123** [comment]
It could potentially be a problem with polyfill in Safari? Here's some info on a potential fix: https://github.com/facebook/react-native/issues/6025

**Comment by xdamman** [comment]
You are right, it works in Chrome but not in Safari. That's an issue.
