### ISSUE TITLE
sub-collective management

### ISSUE THREAD

**Issue by lsmith77** [opencollective/opencollective#1620]
## User story 
_As project, I can to manage several sub-collectives so that I can have collectives for specific currencies and more importantly different causes_

## Best solution for this problem
_UI to create sub-collectives based on an existing collective. This sub-collective would re-use all settings and allow to selectively override individual settings and all sub-collectives should be linked to the main collective._

## MVP
_Ability to create a sub-collective from an existing collective re-using all settings and automatically linked to the main collective._

## Metrics 
_Number of sub-collectives created._

## Documentation 
_The goal of the documentation should be to make it easier for others to do this_

**Comment by alanna** [comment]
This is achieved by Projects now
