### ISSUE TITLE
ContributeDetails: review how Frequency is handled 

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1624]
For Tiers:
- if interval=monthly, force "monthly"
- if interval=yearly, force "yearly"
- if no interval, force "one time"

For free donation:
- default to "one time"
- ability to switch to "monthly" or "yearly"

Pending input from @cuiki on desigh of forced frequencies.

**Comment by HipsterBrown** [comment]
@cuiki We're missing some designs around this for collectives with tiers of a limited quantity and a fixed amount + interval.

Example: https://opencollective.com/madpy/order/3443
<img width="1156" alt="screen shot 2019-01-11 at 4 06 39 pm" src="https://user-images.githubusercontent.com/3051193/51059749-40b23800-15bb-11e9-964c-d4cba0e53513.png">
