### ISSUE TITLE
Postinstall scripts are harmful

### ISSUE THREAD

**Issue by arcanis** [opencollective/opencollective#1625]
## User story 

As mentioned in the title, while handy, postinstall scripts are quite harmful (I explain more below) and adding them to a package should in my opinion be the answer to a clear technical need rather than an organizational one - especially if there are better alternatives.

## Why are postinstall scripts harmful?

There are two main reasons:

- Since packages have different dependency trees from a project to another, postinstall artifacts cannot be cached system-wide. Since the package manager doesn't know whether the postinstall script will generate artifacts or not, the mere presence of a postinstall script will cause the package to be deoptimized and copied into each project - losing some of the benefits provided by Plug'n'Play and similar install strategies.

- The postinstall script will need to run when the package dependency tree is modified. While it should be relatively fast, it still has a slight cost that adds up - especially if a high number of packages are using OpenCollective, since multiple processes will be spawned, which will each require a new Node process to boot. And Node isn't particularly fast.

In consequence, in a world where OpenCollective becomes the norm, the developer experience would be significantly worsened for the end users. Note that some of those problems aren't as visible because neither Yarn nor npm have the infrastructure to take advantage of build artifacts, but I'm working to fix that and it will become much more visible - with the result that we might have to recommend users to disable install scripts.

## Best solution for this problem

Good question - I'm not familiar with OpenCollective yet so I fully expect to have some things to learn about it before being able to make a formal proposal. The only thing I can say for sure is that, right now, the postinstall scripts goes against the users best interest in significant ways.

On the top of my head, this problem would be better solved at the package manager level - for example if the package manager was printing the package list obtained from OpenCollective, or something similar. It probably wouldn't be as pretty as the current output, but I'm sure we can come up with something that would satisfy everyone 🙂

**Comment by feross** [comment]
Just wanted to note that I replied in the `yarn` repo indicating that I would adopt a feature that allowed me to avoid the de-optimization you mentioned here. 

https://github.com/yarnpkg/yarn/issues/6971#issuecomment-524498883

**Comment by znarf** [comment]
Closing. To be clear, not because we don't care, but because we're moving forward!

The new issue to track our progress is:
https://github.com/opencollective/opencollective/issues/2391
