### ISSUE TITLE
New → Pricing Page

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1635]
People expect to have a /pricing page so that they can quickly have an overview of how much it costs.
It's not normal that people have to dig into the FAQ to find that out as reported by Jeremie on Twitter: https://twitter.com/skynebula/status/1085566010709676032

Can we create such a page to make it clear that it's free to use Open Collective, you only pay 5% when you raise money through the platform, and you have to pay host fees that depend on the host.

Something along those lines:

feature | price
------- | -----
Create an Open Collective | free
Publish expenses | free
Create events | free
Post updates | free
Allocate money | free (your fiscal host may charge a fee)
Collect money online | 5% platform fee + payment processor fee (see [Stripe](https://stripe.com/pricing) pricing in your region)
Host money | depends on your host

As always with a quick contextual FAQ:
- What is a host?
A host is an individual or a legal entity that holds the money on behalf of your collective.

- Do I need a fiscal host?
You always need one but you can be your own host. It's a matter of trust for the community and funding needs. If you don't need much money and if most of it is coming from individuals, it's probably ok to host your collective yourself. If backers are companies, they will require an invoice. That's why you'd need a real legal entity to be your host. That's why we have created [The Open Source Collective 501c6](https://opencollective.com/opensource) which is a non profit in the US to host open source communities around the world. This makes it super easy for companies to support the open source projects that they rely on.

- How much are hosts usually charging?
It highly depends. We have hosts like [Open Collective Paris](https://opencollective.com/paris) that don't charge any fee. [BrusselsTogether](https://opencollective.com/BrusselsTogetherASBL) just ask collectives to pay €10/month. [The Open Source Collective 501c6](https://opencollective.com/opensource) charges 5%. Other hosts offer much more than just fiscal sponsorship, they also take care of a common brand and activities, as such [Women Who Code](https://opencollective.com/wwcode) charges 10% and [Operation Code](https://opencollective.com/operationcode) charges 30%.

- What payment methods are accepting?
...

- What about manual bank transfers?
The host can receive money outside of Open Collective, for example via bank transfers. In that case the host can allocate that money to your collective for free or for a fee. In any case, Open Collective doesn't charge any fee for this since it's a manual process.

**Comment by alannallama** [comment]
Great idea @xdamman. I'm working on a draft of the content [here](https://docs.google.com/document/d/1yopQcu_UtS6r_fG-f3N5SxdAohYhHqtQQdxuAZbzKt8/edit?usp=sharing). 

@cuiki I will just focus on the text - I'd love your expertise with the design. The concepts get a little complicated so it would be great to find a visual way to present them clearly.

**Comment by znarf** [comment]
Design: https://www.figma.com/file/qEmmtsi5UNVUVhVj3YuaJg/05.-Pricing
