### ISSUE TITLE
User can define billing address

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1639]
## User story 
As a user, I want to be able to add and edit the billing address that appears on receipts from open collective, for my records and taxes

## Best solution for this problem
An editable field in user settings for billing address

## Metrics 
Fewer requests for us to do this manually

## Documentation 
Add note about how to edit billing address in FAQ

**Comment by xdamman** [comment]
We can reuse `Collective.address` that is being served by GraphQL as `collective.location.address`.
That's also what we use to generate the invoice: https://github.com/opencollective/opencollective-invoices/blob/master/src/pages/invoice.js#L108

We need to add this `address` field in the edit collective form: https://github.com/opencollective/opencollective-frontend/blob/master/src/components/EditCollectiveForm.js#L283

**Comment by flickz** [comment]
@xdamman The input label should be `Address` or `Billing Address`?

**Comment by znarf** [comment]
At first it's `Address`.

We expect that later people will ask for a `Billing Address` being different from `Address` but we're not gonna do that for now.

**Comment by Betree** [comment]
Re-opening this, I still need to add this on the invoices

**Comment by Betree** [comment]
This is done and deployed, just set your address in edit profile and it will appear on the invoice.

![image](https://user-images.githubusercontent.com/1556356/53797078-be4c5180-3f35-11e9-8984-f9ae7fb9af9a.png)

**Comment by alannallama** [comment]
@Betree I can't find the option to add an address in my profile. Is it in production now?

**Comment by Betree** [comment]
@alannallama It was but we had to do rollback because of a new bug introduced in the contribution flow (https://github.com/opencollective/opencollective/issues/1788).

We'll re-deploy this as soon as possible, sorry for the inconvenience.
