### ISSUE TITLE
Bugs when changing event template

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1640]
I went to a Collective, events, create event, and used the template dropdown to select a template. Then I selected a different template, and all the other boxes in the form disappeared. Then I tried to put it back to the first option (no template) and the whole screen went blank and it said "UNKNOWN ERROR". This was in Firefox.

I tried the same in Chrome, and the same thing happened where the boxes disappeared when I changed the template, but it didn't show "UNKNOWN ERROR".

**Comment by maddhruv** [comment]
It is not happening for me
at `{collective}/events/new`
@alanna can you confirm again

**Comment by znarf** [comment]
We don't support templates anymore.
