### ISSUE TITLE
Login error when trying to approve new collectives

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1642]
I get a notification of a new collective application and click "approve" in the email. Sometimes it works, and sometimes I get this error about not being logged in. But I am logged in (see my photo in upper right).

<img width="831" alt="screen shot 2019-01-18 at 5 49 50 pm" src="https://user-images.githubusercontent.com/5498878/51366313-c39e3a00-1b49-11e9-8b66-d38e84f854f8.png">

If I refresh the page, it logs me out and I have to log in again using the email process. Then I try approving the collective and it might work or this whole thing repeats again.

What it looks like to me is that the page begins loading before whatever part determines the logged in state, because as the page loads I can see the not logged in view (it says 'log in' in the upper right) before my photo and username appears in the corner. But the Collective approval process loads faster.

**Comment by znarf** [comment]
@alannallama Let's try to fix the issue. I'm prioritizing that.

**Comment by znarf** [comment]
@alannallama Is it still the same? To help me troubleshoot, can you try:

While being already authenticated:
- hacking he URL and skipping the /signin part, just go to `/{host}/collectives/{id}/approve`

While being not authenticated:
- trying one of the latest approval email (<24 hours)

**Comment by alannallama** [comment]
If it's easier, can we just remove the authentication from the approve button, and instead use the straight URL and rely on the user being logged in already?

**Comment by Betree** [comment]
@alannallama What's the URL of the host? I just found a bug that may be related

**Comment by alannallama** [comment]
@Betree these have all been for the Open Source Collective I think.

**Comment by znarf** [comment]
@alannallama We expect that to be better now.

1) If the link is invalid and you're already authenticated, it's ignored
2) If the link is invalid and you're not already authenticated, you get a login form to sign in

Can we close it?

**Comment by alannallama** [comment]
Yes, it's working now. Thanks!

--
Alanna Irving
hello@alanna.space
https://alanna.space
