### ISSUE TITLE
Contribution flow: UI gets mad when there are too many tier presets

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1646]
![Preview](https://user-images.githubusercontent.com/1556356/51405813-a5d7d180-1b57-11e9-8f2c-ab9bcd488c5a.png)

**Comment by Betree** [comment]
Linked to https://github.com/opencollective/opencollective/issues/1690

**Comment by Betree** [comment]
@znarf Just found out that the number of presets is actually limited to 5, I used an old collective data for this test. So this should be fixed by https://github.com/opencollective/opencollective/issues/1690

**Comment by znarf** [comment]
@Betree where is the imitation enforced?

**Comment by Betree** [comment]
https://github.com/opencollective/opencollective-frontend/blob/0de9675cae9a04f375246ce6f63ac04e0ea5eeac/src/components/InputFieldPresets.js#L51
