### ISSUE TITLE
ContributionFlow: don't zoom in when giving focus to input on mobile

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1649]
It's not a great experience that when we give focus to an input field, we lost the full screen view. It is zooming a bit, not by much. Ideally we should keep the zoom level the same.

![](https://d.pr/free/i/LdOQZ5+)

![](https://d.pr/free/i/BifulO+)

**Comment by znarf** [comment]
A $50 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

**Comment by DeolaJ** [comment]
My name is Adeola (OSCA Lagos). I have picked this isue

**Comment by DeolaJ** [comment]
Please how do I navigate to the page?

**Comment by znarf** [comment]
@DeolaJ for example https://staging.opencollective.com/babel/donate (make sure you're not already authenticated)

**Comment by DeolaJ** [comment]
Thank you

**Comment by znarf** [comment]
This issue is now open to everyone.

**Comment by znarf** [comment]
@JohnTitor Looks better!

This needs to be confirmed by @xdamman, the original reporter.

Can you please check? https://opencollective-frontend-wkcvlwgpfk.now.sh/babel/donate

**Comment by znarf** [comment]
:trophy: This issue is now completed by @JohnTitor 

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
