### ISSUE TITLE
NEW submit expense 

### ISSUE THREAD

**Issue by erickrico** [OpenCollective/OpenCollective#165]
Upgrading the summit expense section >>https://opencollective.com/yeoman/expenses/new

**Comment by erickrico** [comment]
## New view
![summit expense](https://cloud.githubusercontent.com/assets/18429104/16814386/3cd8fb40-48fb-11e6-80f1-9b501fa6715a.png)

- rearranged the information order
- removed the "notes" input (can be added again no problem, i just think any "note" can be added on the description box)

**Comment by xdamman** [comment]
Can you make a responsive version?
Also a version with the state after the image receipt or PDF is uploaded?

**Comment by erickrico** [comment]
sure, already on it (:

**Comment by erickrico** [comment]
## Responsive
![responsive](https://cloud.githubusercontent.com/assets/18429104/16816317/0598548e-4903-11e6-8d55-ea17a7d48efe.png)

## Responsive  with info
![responsive filled](https://cloud.githubusercontent.com/assets/18429104/16816433/7732dbb4-4903-11e6-9f05-b28dc495808c.png)

**Comment by xdamman** [comment]
Cool!
Ship it! :)

Can you also do the list of expenses? 
Eg https://OpenCollective.com/RailsGirlsAtl/expenses

**Comment by asood123** [comment]
Can you also add a logged-in version? With login on the website, we don't need to ask for information we already have like email. We should show who we believe it is. 

`Name: Tara Mill` 
`Not Tara Mill? Logout`

Email/paypalemail shouldn't be included on the logged-in form.

**Comment by erickrico** [comment]
i think it would work best if we pre fill the inputs with the information we already have, instead of removing them.
as for the name part, i can add the log out part contextually to it no problem @asood123

**Comment by asood123** [comment]
Ok let's make those fields not editable, otherwise we'll end up updating
users account with new info (and some fields like email shouldn't be
changeable anyway)
