### ISSUE TITLE
New Collective approval email for Meetups does not specify host

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1651]
I'm getting new collective requests for "Meetups" that don't say what host the request is for. It's not possible to approve them without knowing the host, as they all have different policies. See this list of emails below—they all specify the host name except for "meetups".

<img width="838" alt="screen shot 2019-01-18 at 9 33 22 am" src="https://user-images.githubusercontent.com/5498878/51506795-f3538780-1e52-11e9-8982-be04e0949732.png">

In the body of the email, one of the items listed should be "host".

<img width="560" alt="screen shot 2019-01-22 at 2 36 14 pm" src="https://user-images.githubusercontent.com/5498878/51506834-21d16280-1e53-11e9-9a75-62d5466b11ff.png">

**Comment by alannallama** [comment]
@piamancini said meetups should go in the c3 host, but how do I know if I click "approve" that's where they will go?

**Comment by xdamman** [comment]
This is the logic:

https://github.com/opencollective/opencollective-api/blob/master/server/graphql/v1/mutations/collectives.js#L47-L70

We didn't have anything for US.
So for now I'll automatically assign them to the Open Collective Inc Host by default as it's the safest place. The host will still have to approve the request.

If it's a tech meetup, I'd argue that they should be hosted on the Open Source Collective 501c6. Something to discuss with @piamancini and the board. Maybe we need to make the distinction between a tech meetup and an open source meetup. TBD.

If they can fall into the requirements of the C3, we should get in touch with them and ask them to change the host when they edit their collective. They should also approve the terms of service of the 501c3 in that case.
