### ISSUE TITLE
Option to send only positive text in monthly tweets.

### ISSUE THREAD

**Issue by dahacouk** [opencollective/opencollective#1653]
## User story 
_As a Collective on Open Collective, I can choose to post only positive news in my automatic **Monthly stats** tweets so that people looking at my Twitter feed don't see loads of "nothing happened this month" tweets._

## Best solution for this problem
_Have a switch preference in the Connected Accounts section such as https://opencollective.com/noplasticapp/edit/connected-accounts that would enable only positive text in a tweet. And if there was no positive text at all then don't send the tweet. So, for example the "positive" preference would remove all the "nothing happened" text from the tweet._

<img width="580" alt="noplasticapp___noplasticapp____twitter" src="https://user-images.githubusercontent.com/201752/51596055-64994600-1ef8-11e9-9963-3f2a2a594f2a.png">

**Comment by xdamman** [comment]
I agree. Not sure we want to add yet another option. But we could definitely skip the line "No new backer has joined" and "we spent €0".
