### ISSUE TITLE
Users should be able to edit their country

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1654]
With the upcoming [VAT](https://github.com/opencollective/opencollective/issues/1557) feature, we will apply some rules based on user's country. As of today, this information cannot be changed.

## Expected

We should add a field in `Edit Collective` to change the country.

**Comment by xdamman** [comment]
We need to add this field in the edit collective form: https://github.com/opencollective/opencollective-frontend/blob/master/src/components/EditCollectiveForm.js#L283

We need to add country in the `CollectiveInputType`: https://github.com/opencollective/opencollective-api/blob/master/server/graphql/v1/inputTypes.js#L102

And the `Collective` model: https://github.com/opencollective/opencollective-api/blob/master/server/models/Collective.js#L105

Which means we also need a migration file like this one: https://github.com/opencollective/opencollective-api/blob/master/migrations/20180221200011-add-transaction-status.js

**Comment by flickz** [comment]
Best to save the country's [ISO 3166-1 alpha codes](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) right? And use it as an object key when displaying country to the user (maybe) 

```js
  const countries = {
      US: 'United States of America',
     ......
  }
 const country = countries[countryISO]
```

**Comment by Betree** [comment]
@flickz I agree that this is the best solution for this, it is a standard and will allow us to plug things like https://github.com/michaelwittig/node-i18n-iso-countries so we don't have to translate country names by ourselves :+1:

**Comment by flickz** [comment]
Great, working on it!
