### ISSUE TITLE
enable PayPal for all fiscal hosts

### ISSUE THREAD

**Issue by lsmith77** [opencollective/opencollective#1655]
## User story 
_As a fiscal host, I can offer paypal to collectives so that their donors have more flexibility in how to donate (especially those without credit cards)._

## Best solution for this problem
_Paypal is no longer hardcoded to just one fiscal host_

https://github.com/opencollective/opencollective-api/blob/master/server/paymentProviders/paypal/payment.js#L21

## MVP
_A pattern to at least hardcode additional fiscal hosts_

## Metrics 
_What metrics will be used to measure impact?_

## Documentation 
_The goal of the documentation should be to make it easier for others to do this_

**Comment by znarf** [comment]
This was talked within the Open Collective team and is likely to be prioritized.

**Comment by alannallama** [comment]
I think we still need this. Maybe related to #1141 in terms of improve the whole Paypal experience.

**Comment by znarf** [comment]
Duplicate with: https://github.com/opencollective/opencollective/issues/1140

**Comment by znarf** [comment]
It's now potentially available for all Hosts, they need to be in touch with support@opencollective.com to activate it.

**Comment by alanna** [comment]
I'm planning to send an update to all fiscal hosts in the near future with
some info about platform updates. I'll include a mention about turning on
Paypal.

**Comment by Betree** [comment]
Would be great to add this info and some lines about how it works for fiscal hosts in [the documentation](https://docs.opencollective.com/help/fiscal-hosts/fiscal-hosts)

**Comment by znarf** [comment]
@alanna Once they contact support, it's up to the admin team to decide if we activate it or not. One tricky aspect is that the host will be collecting platform fees or platform contributions (aka: "fees on top") on behalf of Open Collective and will need to wire them back on a monthly or quarterly basis.

**Comment by alanna** [comment]
> Would be great to add this info and some lines about how it works for fiscal hosts in [the documentation](https://docs.opencollective.com/help/fiscal-hosts/fiscal-hosts)

Paging @contraexemplo

**Comment by alanna** [comment]
> Once they contact support, it's up to the admin team to decide if we activate it or not. One tricky aspect is that the host will be collecting platform fees or platform contributions (aka: "fees on top") on behalf of Open Collective and will need to wire them back on a monthly or quarterly basis.

@znarf that sounds complicated. How do you think it will work? Will we send them a request to pay via Paypal each month or something?

**Comment by znarf** [comment]
Closing, we're now expanding to more hosts. They need to contact  support@opencollective.com.
