### ISSUE TITLE
Missing refund function for PayPal

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1656]
Multiple payment providers are missing refund function, which forces us to create the refund transactions manually.

- [x] Prepaid
- [x] Collective to collective (https://github.com/opencollective/opencollective/issues/1935)
- [x] Virtual cards
- [x] Manual (https://github.com/opencollective/opencollective/issues/1936)
- [x] PayPal

**Comment by piamancini** [comment]
This is going to the hackathon - we should do it

**Comment by znarf** [comment]
@piamancini the 2 linked issues are in the list.

**Comment by piamancini** [comment]
Did we do this?

**Comment by znarf** [comment]
@piamancini "Manual" was done. "Collective to Collective" is pending.

**Comment by Betree** [comment]
With PayPal recurring being released soon, we can expect much more contributions with PayPal. We'll probably have to prioritize this issue soon after the release.

**Comment by znarf** [comment]
@Betree Yes, I also think it's an important one.
