### ISSUE TITLE
Stripe virtual cards

### ISSUE THREAD

**Issue by themightychris** [opencollective/opencollective#1657]
Stripe is finally getting into the virtual API-driven cards game: https://stripe.com/issuing

Since OpenCollective already uses stripe, does this make the prospect more feasible now of enabling collectives to issue cards to organizers to charge expenses directly to their balance?

**Comment by themightychris** [comment]
See opencollective/opencollective#1038

**Comment by RCheesley** [comment]
Was there any progress on this? At the moment it is a very convoluted process that I have to go through using my corporate credit card and getting reimbursed. Happy to be a beta tester if you need one!

**Comment by BenJam** [comment]
closing this as we have virtual cards from privacy, which aren't without their issues but appear to work. #4276
