### ISSUE TITLE
API: Update to GraphQL 14

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1658]
We have a policy to try to use the latest version of our dependencies in all repositories.

In the API, we're currently using the GraphQL version 0.13  and the upgrade to version 14 has breaking changes.

- Branch with GraphQL 14:
  https://github.com/opencollective/opencollective-api/tree/package/update-graphql
- Sample failure on CI:
  https://circleci.com/gh/opencollective/opencollective-api/9315

We want to:
  * upgrade the package
  * make sure tests are passing
  * make sure the API stay compatible with current version

Here are the things we know that needs to be looked at:

- [ ] fix a breaking change sending all dates from the database as timestamp instead of current (non standard) format `Tue Mar 01 2016 01:00:00 GMT+0100 (Central European Standard Time)`

**Comment by znarf** [comment]
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](https://github.com/opencollective/opencollective-api/blob/master/BOUNTY.md).

**Comment by vickywane** [comment]
Hello , 
I would love to attempt solving this .

**Comment by znarf** [comment]
@vickywane Looks like @robertlyson already started it. Let's wait for his answer.

@robertlyson What's your progress on this? Normally, if you want to be part of the bounty program, you need to ask to be assigned to the issue. We want to avoid multiple people working on the same thing at the same time.

**Comment by robertlyson** [comment]
@znarf that make sense, next time will do that :+1:.
I was looking into fixing unit tests and date formatting issues, but couldn't make any progress in the last two days so I guess @vickywane feel free to grab it :)
@vickywane you can also check my PR(https://github.com/opencollective/opencollective-api/pull/1763). There was one fix made to BDD tests.

**Comment by vickywane** [comment]
Do you mind sharing the approaches you've tried in solving this issue so I can pick up from where you stopped @robertlyson

**Comment by robertlyson** [comment]
@vickywane I tried to change graphql type definition for `createdAt` and `updatedAt`([here](https://github.com/opencollective/opencollective-api/blob/package/update-graphql/server/graphql/v1/TransactionInterface.js#L53-L54)) so it formats timestamps at it used to. Was thinking about using resolver for `GraphQLString` but couldn't figure it out. 
Hope that helps.

**Comment by vickywane** [comment]
Alright thanks..  
Since you started it first I'll give you the " emotional " credit 😂.

**Comment by robertlyson** [comment]
@vickywane how it's going? Keen to see how it was resolved :)

**Comment by vickywane** [comment]
@robertlyson .. Am still working on this..  Spent some days trying to make some fixes but they weren't working as expected..  I tried about three different approaches.  

I don't know if @znarf agreeses to this..  But I guess you can have the bounty if you fix it before me

**Comment by znarf** [comment]
@vickywane @robertlyson if you're cool with it, no objection.

**Comment by kevgathuku** [comment]
Hi @znarf I would love to work on this.
vickywane @robertlyson are you still working on it?

**Comment by robertlyson** [comment]
@kevgathuku I stopped working on this. If @vickywane and @znarf are ok with it, feel free to grab it. Thanks.

**Comment by znarf** [comment]
@kevgathuku you can have a look!

**Comment by vickywane** [comment]
@kevgathuku i stopped also . Feel free to work it out

**Comment by eloyekunle** [comment]
I'll also love to look into this.

**Comment by kevgathuku** [comment]
Go ahead @eloyekunle
I've dropped the ball here and taken too long to make a breakthrough

**Comment by znarf** [comment]
Huge achievement, this is now our last pending package update in the API.

Hope someone will fix this :-)

**Comment by znarf** [comment]
Thank you @eloyekunle! It's merged and deployed.

To claim the bounty, you can:

a) submit an invoice to https://opencollective.com/engineering
b) or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Comment by znarf** [comment]
Fyi, our test coverage was not enough to prevent breaks, we had to follow up in many PRs:

- https://github.com/opencollective/opencollective-frontend/pull/1892
- https://github.com/opencollective/opencollective-frontend/pull/1891
- https://github.com/opencollective/opencollective-frontend/pull/1889
- https://github.com/opencollective/opencollective-frontend/pull/1878
- https://github.com/opencollective/opencollective-api/pull/2062
- https://github.com/opencollective/opencollective-images/pull/69
- https://github.com/opencollective/opencollective-rest/pull/19

**Comment by eloyekunle** [comment]
Oh, that's interesting. Hopefully there'll be few breaks left.
