### ISSUE TITLE
Formatting issues in collective update emails

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1659]
<img width="629" alt="screen shot 2018-06-28 at 3 00 17 pm" src="https://user-images.githubusercontent.com/5498878/42010757-508ae8c0-7ae4-11e8-8963-d1b43f09bb1a.png">

- [x] 1. If a collective does not have a logo, it should just have [collective name] but it has [collective name logo] in text instead.

- [ ] 2. Make it clear to users how to format in these messages—in the example above they are trying to use markdown but it's not rendering.

**Comment by znarf** [comment]
1. was taken care of
