### ISSUE TITLE
[Project] OAuth support

### ISSUE THREAD

**Issue by erlend-sh** [opencollective/opencollective#1660]
Are there any plans for OpenCollective to run its own OAuth server? OAuth makes integrations with other apps a lot easier and more flexible.

We're working on a [Patreon integration for Discourse](https://meta.discourse.org/t/discourse-patreon-login/44366), and would love to do something similar with OpenCollective.

**Comment by ArtemSBulgakov** [comment]
Any plans on this issue?

**Comment by ffMathy** [comment]
Any news?

**Comment by ariv797** [comment]
Is oAuth still being considered??

**Comment by znarf** [comment]
@ariv797 It's still considered. However we operate on tight resources and could not make it happen so far.

**Comment by ariv797** [comment]
Hope it happens soon! 👍

**Comment by BenJam** [comment]
FYI looking to scope this from an engineering perspective next week only. We'll need to deliver this in a big project in a future sprint.

**Comment by piamancini** [comment]
Week 2
- [ ] list design requirements & communicate to design

**Comment by piamancini** [comment]
- [ ] discuss - kickoff with design team 
- [ ] create an issue for the backend model and kickoff discussion with team

**Comment by piamancini** [comment]
- [ ] add details to technical issues

**Comment by znarf** [comment]
- [ ] https://github.com/opencollective/opencollective/issues/5344
- [ ] https://github.com/opencollective/opencollective/issues/5345
- [ ] https://github.com/opencollective/opencollective/issues/5346
- [ ] https://github.com/opencollective/opencollective/issues/5356
- [ ] https://github.com/opencollective/opencollective/issues/5357

**Comment by BenJam** [comment]
Goal 

- [ ] close the API/model implementation
- [ ] iterate and improve tests
- [ ] start working on frontend (auth, token management etc)
- [ ] design application token management interface (work with eng)

**Comment by znarf** [comment]
Goal

- [ ] implement List / Revoke tokens API
- [ ] implement List / Revoke tokens interface
- [ ] Keep current Sign In / Sign Up for now

**Comment by BenJam** [comment]
- [ ] wrap up plan for future sprint(s) in issue
- [ ] contact orgs interested in implementing (metagov, cobudget) validate with them

**Comment by znarf** [comment]
Future work

- [ ] Integrate with latest Sign In and Sign Up
- [ ] Basic Activity logging
- [ ] Scope handling (what can the app do, which collective it can interact with)
- [ ] Ability for developers to create and manage apps ("Developers" section in the settings)
- [ ] Migrate "Personal Tokens" to the new "Developers" section of the settings

**Comment by znarf** [comment]
Q2 Sprint 2:

- [ ] Integrate with latest Sign In and Sign Up @SudharakaP @znarf https://github.com/opencollective/opencollective/issues/5346
- [ ] List applications created by an account (developers) @znarf @Betree 
- [ ] Ability for developers to create Apps @SudharakaP @znarf  https://github.com/opencollective/opencollective/issues/5345 
- [ ] Migrate "Personal Tokens" to the new "Developers" section of the settings (Migrate old /applications and rebrand to "Personal Tokens") -> Create Issue. @Betree @znarf 
- [ ] Scope management -> Create Issue @znarf @Betree
  - [ ] move from everything by default to nothing 
    - [ ] "profile" scope (who is the user, what is their Open Collective account)
    - [ ] "email" scope (what the address of the user)
    - [ ] "payoutMethods" "paymentMethods"
    - [ ] "incognito" which scope?
    - [ ] "legalName" "address" "taxId"  as "contributorsInfos" ?
    - [ ] "expenses": comments, attachments, createExpense, editExpense, payExpense
    - [ ] "contributions"
    - [ ] "transactions"
  - [ ] granularity at the Collective level should not be part of it (but it's important for power users, multiple host/collective admins)
 - [ ] Basic Activity logging
   - [ ] Store ApplicationId in the `Activity` table
   - [ ] Read from `req.remoteUser` or `req.clientApp`
 - [ ] Create an activity and send an email when connecting the app

**Comment by piamancini** [comment]
- [ ] Integrate with latest Sign In and Sign Up @SudharakaP @znarf https://github.com/opencollective/opencollective/issues/5346
- [ ] Kick-off ability to manage apps (https://github.com/opencollective/opencollective/issues/5345)
- [ ] Kick-off scope (permissions)

**Comment by piamancini** [comment]
- [ ]  Integrate with latest Sign In and Sign Up @SudharakaP @znarf https://github.com/opencollective/opencollective/issues/5346
- [ ] App Management Review and merge
- [ ] Work on scoping

**Comment by znarf** [comment]
We'll keep the same tasks for this week (Q2 Sprint 2 Week 4).

**Comment by znarf** [comment]
Q2 Sprint 2 Week 6:

- [ ] Merge, Deploy
- [ ] Document
- [ ] Create follow up issues
