### ISSUE TITLE
Navigation button without HTML <a> tag

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1666]
On Collective page (such as https://opencollective.com/apex) the "Submit Expense" is a simple link to http://opencollective/apex/expenses/new but doesn't have a proper HTML <a> tag.

![Capture d’écran 2019-07-08 à 14 32 27](https://user-images.githubusercontent.com/806/60810422-62b4fd80-a18d-11e9-8a21-ddf102ff8ac3.png)

The button is currently located in this file:
https://github.com/opencollective/opencollective-frontend/blob/master/src/components/MenuBar.js#L330

**Comment by Shorpee** [comment]
is this issue still open? i'll like to work on this if it is!

**Comment by znarf** [comment]
@Shorpee it is! Should not be complicated.

**Comment by Shorpee** [comment]
Great! will get right on it!

**Comment by znarf** [comment]
A $50 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

**Comment by Sokan93** [comment]
I'm Ayodeji Sokan from the OSCA event. I'd like to work on this!

**Comment by Akumzy** [comment]
I'm working on this #OSCAPH

**Comment by alabobriggs** [comment]
Am from osca ph and will like to work on this

**Comment by znarf** [comment]
Thank you @Sokan93  ! It's merged.

To claim the bounty, you can:

a) submit an invoice to https://opencollective.com/engineering
b) or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Comment by znarf** [comment]
@Sokan93 this was broken, I had to revert, see https://github.com/opencollective/opencollective/issues/2231

It should look like that:

![Capture d’écran 2019-07-12 à 09 57 24](https://user-images.githubusercontent.com/806/61112248-b4120500-a48b-11e9-9c97-0b819fa382b8.png)

**Comment by Sokan93** [comment]
Okay thanks,  seems the issue has been closed

**Comment by znarf** [comment]
@Sokan93 well, I only reverted to what it was before. The original issue (this one) is now re-opened.

**Comment by Sokan93** [comment]
Okay, so I'd just have to correct it as the former.

**Comment by znarf** [comment]
It should just look like the screenshot when scrolling.

**Comment by Sokan93** [comment]
Hello @znarf 
This is the page - https://opencollective.com/drupal-diversity-and-inclusion-speaker-initiative
It looks the screenshot when scrolling.
Or is there something else missing?
Thanks

**Comment by znarf** [comment]
We reverted your change. So it’s working like before. And like before, there is no <a>, so we’re back at the the start.

**Comment by Sokan93** [comment]
Okay, I'll work on that, what would possibly have caused the buttons overlapping(what broke earlier)?

**Comment by josiaholatunde** [comment]
I'm from Osca Lagos and would be working on this

**Comment by znarf** [comment]
Closing because it will be invalid with the release of Collective Page v2.
