### ISSUE TITLE
Review Collective onboarding policy (Readme)

### ISSUE THREAD

**Issue by XhmikosR** [opencollective/opencollective#1667]
When the bot opened a PR on BootstrapCDN, I noticed a couple of things that seemed weird.

1. your are using HTML in the template for README.md. While that is fine, you should try using Markdown
2. `target="_blank"` is useless because it's being stripped by GitHub
3. the bot added the logos 2x
4. the template added the CONTRIBUTING.md paragraph even though the repo does not have such file and led to 404s

You can see my patch which switched to pure Markdown and cleaned things up [here](https://github.com/MaxCDN/bootstrapcdn/commit/89270bbedde2e52274fe79e21190dc0319d6505d).

**Comment by Betree** [comment]
We're not creating these PRs anymore.
