### ISSUE TITLE
Ban console.log in frontend

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1669]
On Node.js side, we already switched all console.log to logger (winston).

In pages and components we still have a few left. If not logger/winston, we should replace them by a lightweight wrapper that is silent by default in production.

Finally, to enforce that rule in the future, we should remove the eslint exception currently in place.

**Comment by Betree** [comment]
Would be great to get rid of all these warnings. We can use https://babeljs.io/docs/en/babel-plugin-transform-remove-console to only keep `console.error` in production.

**Comment by znarf** [comment]
My approach would be to introduce a small `logger` wrapper to activate/deactivate on demand. With sensible defaults, enabled in dev, disabled in production.

**Comment by Betree** [comment]
This is good too. What I like about using a babel-plugin is that it entirely strips the `console.log` from the code (lighter) and there's no big refactor to do, it's only 5 lines to add in the `.babelconfig`

**Comment by Betree** [comment]
Now that we're using Sentry, it would be great if the `logger.error` that will replace the `console.error` could push the error to Sentry. See https://www.npmjs.com/package/@sentry/browser

**Comment by code4cake** [comment]
hey as this issue been taken and may I take it ? Thanks

**Comment by Betree** [comment]
Resolved in https://github.com/opencollective/opencollective-frontend/pull/7670
