### ISSUE TITLE
new page /:slug/:tier

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#167]
E.g. `/mochajs/backers`

This should show the list of all backers with a search box on top to quickly find a given user by name.
It should be responsive.

Bonus point: `/:slug/:tier.:format(json|csv)`

(should return the same data in son or cvs format)

**Comment by asood123** [comment]
Problem we are trying to address: a meetup wants to "checkin" paid members at their next monthly meeting. Right now, it's painful for them to scroll on the phone. 

This is the simplest solution we could think of. Feel free to propose other (easier) things to build.

**Comment by xdamman** [comment]
That meetup is ConsciousnessHackingSF: https://opencollective.com/chsf
They have 100+ members.

**Comment by asood123** [comment]
note that this still needs an api endpoint.
