### ISSUE TITLE
Contribution Flow: new step to pick tier

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1671]
On a collective page, when clicking/taping on "contribute", users are directed to the hash "#contribute" and are expected to look on the right (desktop) at the tiers section.

I did found this behavior confusing and would like to propose a "Contribute" page displaying the Tiers (+ one time donation) and only that.

![screen shot 2019-01-24 at 16 17 56](https://user-images.githubusercontent.com/806/51687837-a35ff680-1ff3-11e9-9935-b0dc011a6d1d.png)

**Comment by flickz** [comment]
@znarf A separate page with path `/:slug/contribute`? Or on the main section of the collective page rather the current right side?

**Comment by znarf** [comment]
@flickz this is a new separate page/component, part of the "Contribution Flow".
