### ISSUE TITLE
markdown styling encourages code which is in-accessibile

### ISSUE THREAD

**Issue by mixmix** [opencollective/opencollective#1672]
There's an org info area where you can post markdown.

I made all my headings h2's like `## What does this fund?` but the styling came out kinda like subheadings.

I tried changing this to an h1 header `# What does this fund?` and I get the sort of bit sections I was expecting. The problem is that for someone navigating with a screen-reader, you're messing up the semantics of the page area. e.g. "What does this fund" is a sub-section of the major page section: "Secure Scuttlebutt Consortium"

This is simultaneously not a major thing, and a thing which send signals about an open source project to people who know about accessibility, or people who have accessibility needs

**Comment by znarf** [comment]
How should that be solved?

**Comment by mixmix** [comment]
Make both h1 the biggest, and h2 big, and also give it decent margin.

**Comment by mixmix** [comment]
A perfect solution would be to have the main page header an h1, then mess
with the markdown rendering so that the biggest heading a person can
generate with that is an h2.

**Comment by Betree** [comment]
With the new collective page, markdown is not used anymore for collective's long descriptions. We instead use a WYSIWYG editor that doesn't create titles above H2. Legacy descriptions have all been migrated in https://github.com/opencollective/opencollective/issues/3207 and existing titles have normally been updated.

**Comment by mixmix** [comment]
<3
