### ISSUE TITLE
Use new SignIn component everywhere

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1676]
Now that we have the [SignIn](https://github.com/opencollective/opencollective/issues/1486)  and the `SignInOrJoinFree` components ready, we should migrate all SignIn and SignUp forms to them.

- [ ] SignInForm.js
  - [x] Sign in page
  - [ ] src/apps/expenses/components/CreateExpenseForm.js
  - [ ] src/components/CreateCollective.js
  - [ ] src/components/CreateOrganization.js
  - [ ] src/components/EditCollective.js
  - [ ] src/pages/completePledge.js
  - [ ] src/pages/createHost.js

- [ ] SignInUp

  - [ ] `src/components/InterestedForm.js`

**Comment by flickz** [comment]
@Betree Can I take this on?

**Comment by Betree** [comment]
Hi @flickz thanks for offering! I'm not totally finished preparing the ground for this one and I'm already working on parts of it.

I can recommend going through these issues: https://github.com/opencollective/opencollective/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+label%3A%22complexity+%E2%80%BA+simple%22

**Comment by flickz** [comment]
Good, Thanks!

**Comment by Betree** [comment]
Update: Base component for this issues are ready.

**Comment by znarf** [comment]
Closing as duplicate of https://github.com/opencollective/opencollective/issues/2119
