### ISSUE TITLE
Internal Email Overload

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1677]
Currently the whole Open Collective team is CC'd in a LOT of system emails, causing massive overload and important messages getting lost. I think this was a quick and dirty solution a long time ago that has now got out of hand, and we should fix it.

For example, when a new Collective applies, I see 11 copied emails! Several times each to me, @piamancini and @xdamman and several other people. Why can I see the emails to other people? Because it's also copying info@ or something?

Here is [my list of over 40 filters](https://drive.google.com/file/d/1MUCtr-1A1D0cD28oaX3rPrd16im4YJ2d/view?usp=sharing), which I use to mark all these irrelevant emails as read. As a workaround, I suggest every team member import these and add/delete filters as needed to regain control of your inbox.

I also recommend one more: to filter requests to approve new Collectives (subject "would love to be hosted by" will catch them) - I don't filter these because I need them.

I need to get all emails intentionally sent to support@opencollective and info@opencollective, but if those addresses are copied on tons of auto emails they become hard to use.

Team, what emails do you actually need to do your job? Everything else we should turn off.

**Comment by Betree** [comment]
Thanks for the list @alannallama! Most of the emails I receive today are indeed not necessary.

I like to receive the support emails. Even if I'm not the one usually responding to them, it's helpful to see where users are struggling and to catch bugs that may not have been reported on Github.

Most notifications (`_____ became a backer`, `Welcome to Open Collective`...) are not useful to me. It's good that we have them, for example if we need to debug an email sent with wrong data, but I'd rather have this on a separate email like `_notifications-backup@opencollective.com` that I would connect to only if I need to investigate a specific issue.

**Comment by alannallama** [comment]
Another type of email we get but shouldn't: new collective applications for hosts we don't manage.

**Comment by alannallama** [comment]
@piamancini @xdamman @znarf can you please answer the question about what automated or support emails you actually do want to get?

**Comment by znarf** [comment]
@znarf I would personally like to receive zero automated emails. I'm fine receiving @ops, info@, @support for the time being.

**Comment by alannallama** [comment]
@xdamman says he wants to get the weekly reports, and applications to hosts, but not other automated emails

**Comment by alannallama** [comment]
OK we have figured out how to unsubscribe from the bcc-email list, so that should help. If you are still getting a lot of unwanted emails after you unsubscribe that, let us know what kind they are.
