### ISSUE TITLE
Logo + sticker for Open Source Collective

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#168]
We want to develop the Open Source Collective https://opencollective.com/opensource

People should be able to become a backer of it and we should acknowledge their support.

We need a logo for it and a sticker that we can send to the supporters.

**Comment by piamancini** [comment]
@erickrico hi! we want to revisit this. You had some designs here https://github.com/OpenCollective/OpenCollective/issues/21 Can you send a couple of options?

**Comment by piamancini** [comment]
@erickrico we'd like to do a couple of things for the stickers. 

1 - Can you do a couple of versions with: 
'I back  <MochaJS LOGO> on OpenCollective'
'I am a backer of <logo> on OpenCollective'...
I support... 

2 - For the open source collective, can you create a logo in the same vibe you did for free ride to vote? Thanks!
