### ISSUE TITLE
Contribution flow: Implement the summary step

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1681]
# Design

:art: https://www.figma.com/file/e71tBo0Sr8J7R5n6iMkqI42d/09.-Collectives?node-id=989%3A10

![selection_999 054](https://user-images.githubusercontent.com/1556356/51893245-a1f04e80-23a4-11e9-9d7f-a2e3fedb50b2.png)

# Specs

- [x] Should display fees breakdown
- [x] Should display VAT if any (not implemented yet)
- [ ] Should have a field to leave a public message
- [ ] Public message should be added to the default tweet message in order success page
- [x] Should display the FAQ on the right
- [x] Last button should be renamed "Make contribution"
- [x] Ensure we replace the proper button when using PayPal

**Comment by znarf** [comment]
If we decide to move forward with the tipping model, can we wait for the summary.

I'm afraid in that the summary with that design is not positively exposed, and I expect a drop in contributions.

**Comment by Betree** [comment]
@znarf I share your feeling about the information not being positively presented, but at the same time we need this to move forward with [VAT](https://github.com/opencollective/opencollective/issues/1557).

I can eventually skip it if the host hasn't configured VAT, so it only shows when there's tax to breakdown.

**Comment by znarf** [comment]
@Betree let's make sure we have a team agreement on that before implementing.

**Comment by Betree** [comment]
Done with https://github.com/opencollective/opencollective-frontend/pull/1339
