### ISSUE TITLE
Sign In: Invalid email when using browser suggestion

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1685]
**Describe the bug**

In the Sign In form, when using the browser suggestions to fill the email input, the form can't be submitted because the form is invalid.

**To Reproduce**

1. Go to https://staging.opencollective.com/signin
2. Use browser suggestion to fill the email input

**Screenshots**

![signin](https://user-images.githubusercontent.com/806/51975037-97f04d80-2481-11e9-813a-cb709f89430c.gif)

**Environment:**
 - OS: Mac OS
 - Browser: Firefox 65

**More details**

 When debugging with the following code:

```
<StyledInput
  error={!!state.error}
  fontSize="Paragraph"
  id="email"
  name="email"
  onChange={({ target }) => {
    console.log('StyledInput', 'onChange', target.value, target.validationMessage);
    onEmailChange(target.value);
    setState({ error: target.validationMessage, showError: false });
  }}
```

What I get as output on:

- Chrome (Mac OS): `StyledInput onChange znarfor@gmail.com`
- Firefox (Mac OS): `StyledInput onChange znarfor@gmail.com Please enter an email address.`

So, `target.validationMessage` is not being reset. Is that an edge case because we're not using it properly or an obvious bug on Firefox side?

**Comment by znarf** [comment]
Not affected on Safari 12 or Chrome 71 (Mac OS).

So, looks like it's a Mac OS + Firefox only issue at the moment.

**Comment by flickz** [comment]
How are the suggestions on fixing it?

Apparently works on Chrome 70.0.3538.67 and Firefox 61 on Ubuntu.

**Comment by znarf** [comment]
@flickz I have no idea what the problem is, and was not able to find anyone reporting it elsewhere.

It needs more investigation.

**Comment by Betree** [comment]
@znarf My Firefox was updated to 65.0 and now I'm affected by this too (OS is still Ubuntu 18.04). Do you have a link to the bugzilla's issue so I can report this information?
