### ISSUE TITLE
Sign In: Navigation should work when moving to Create Account

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1686]
**Describe the bug**

When navigating from Sign In to Create Account, the back button is not going back to Sign In.

**To Reproduce**
1. Go to http://staging.opencollective.com/
2. Click on 'Sign In'
3. Click on 'Join Free'
4. Use the browser back button

**Actual:**

Navigated to the Home Page.

**Expected behavior**

Navigated to Sign In form.

**Comment by znarf** [comment]
@flickz I expect that we need to have dedicated route for the "Create Account" form, such as `https://opencollective.com/create-account`.

After that, it's a matter of plugging this route and using next.js `pushRoute` when navigating from  'Sign In' to 'Create Account'.

**Comment by Betree** [comment]
One thing to note here to implement that correctly is that the `SignInOrJoinFree` component (in charge of switching between the two forms) is used in the `/signin` page as well as on the order page `/apex/donate`.

So we need to be clever on how we handle the route change, probably by letting the parent handling this change.

**Comment by flickz** [comment]
Since this will involve setting up a new page (`createAccount`), what will be the best way to persist `email`  input value from the `SignIn` page to `CreateAccount`? In the current, we passed it as prop. Thinking about passing it as a query string, `https://opencollective.com/create-account?email=foo@g.com`. Any better way?

**Comment by Betree** [comment]
We use frontend routing, so the state is persisted as long as the page stays the same. That's what we do in the contribution flow (createOrderNewFlow): routes change, but the page stays the same so we don't loose state.

I personally prefer this approach over query string params.
