### ISSUE TITLE
Design Bug → Contribution Flow: Can't see white logos

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1689]
**Describe the bug**
The new contribution flow has a white background which makes white logos not distinguishable. 

**To Reproduce**
See https://opencollective.com/validatorjs/donate

**Expected behavior**
We should have a darker backgroundor play with css `mix-blend-mode` so logos are always visible.

**Comment by Betree** [comment]
In design, logos have a slightly colored background that could improve things on this issue:

![selection_999 076](https://user-images.githubusercontent.com/1556356/52344755-da82ce80-2a1b-11e9-9b0c-028be4ccc007.png)

**Comment by cuiki** [comment]
Hi @Betree , indeed they have a background color. But that is assuming that the image file of the logo is like that from origin. This is the same issue that we inherited from earlier versions of OC where we accept JPG and transparent PNG's and place them in different colored backgrounds.

I don't know if css `mix-blend-mode` works on all browsers but if it does, Maye can come up with design rules for these cases.

**Comment by Betree** [comment]
`mix-blend-mode` is supported by most browsers, except Edge:

![image](https://user-images.githubusercontent.com/1556356/53208611-bc31eb00-3637-11e9-9183-43d0539ca74b.png)

**Comment by cuiki** [comment]
Nice to know. I feel I should've known this. I'm losing my game! 🥴

**Comment by Betree** [comment]
A resolution for this has been given in https://github.com/opencollective/opencollective/issues/2310#issuecomment-525711716:

> Latest (and final) resolution is to specify that **all** logos on Open Collective will always be displayed on a white background. It is the responsibility of the admins to upload something that looks nice.
