### ISSUE TITLE
Contribution flow: Responsiveness issue on Contribute As

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1693]
# Description

When the personal account description is too long, the whole text goes under the picture.

![screenshot_20190130-234045_firefox](https://user-images.githubusercontent.com/1556356/52018216-ea655480-24e9-11e9-8cc3-5feea88a65c1.jpg)

# Expected behavior

The text should stay at the right of the picture, going to the next line if necessary.

**Comment by gutofoletto** [comment]
Hello! I can take a look at this issue :D

**Comment by Betree** [comment]
Hi @gutofoletto, thanks for offering! I'm currently making a lot of changes on `createOrderNewFlow` but it should not conflict with the changes required by this issue as they should all take place in the `ContributeAs` component.

Feel free to go for it, ask me if you need anything :slightly_smiling_face:

**Comment by Betree** [comment]
Fixed by https://github.com/opencollective/opencollective-frontend/pull/1414. Thanks!
