### ISSUE TITLE
Add an option to say why when cancelling subscription

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1697]
It would be useful to know why backers/sponsors cancel subscriptions. These are people who have already jumped all the hurdles to find and support a Collective, so if they are stopping they might have important feedback for us.

Our messaging when they cancel has a sad face, but sometimes they are actually just changing payment method or subscription amount, so it's not sad (just saw one today where the person emailed the collective to let them know they were doubling their backing, not cancelling). 

I imagine a modal or something like this:

_Why are you cancelling your subscription today?_

* No longer want to back the Collective
* Changing payment method or amount
* Other (write-in)

_Care to give us feedback to help us improve?_
(text box)

## Parent issues
#1581

## Referenced Issues
#1930

**Comment by cuiki** [comment]
Hi @alannallama, I want to make sure I get this.

As a backer of collectives I can change the amount of my contribution or update the payment method without having to explicitly cancel the subscription. The system does that automatically and moves them to the 'Cancelled Subscriptions' list below the active ones when I confirm an update.

Cancelling a subscription is an explicit choice (see: https://tafka.d.pr/Jd1B80). Asking the user to provide feedback on why they cancelled a subscription makes sense then but not when making a change.

So, that said, what I understand that you're asking for is a way to:

a) Ask people to tell us why the are cancelling (if that is their explicit choice).
b) Direct people to the right action (update payment method or changing amount) if they clicked on cancel by mistake and it wasn't what they really wanted to do

I think that in the case of updating the amount it might be worth to also ask (with optional response) the user why the change. It can provide valuable feedback to the collective.

Does this make sense to you?

**Comment by alannallama** [comment]
I didn't know that about changing subscriptions being an option. In the
help docs it says you have to cancel and make a new subscription to change
the amount or payment method. Can you please update the docs with the
correct info? In the backers and sponsors section. (Sorry I'm traveling and
can't do it myself right now).

For now, I think we should just ask for a reason from the backer when they
cancel, and it should be optional. I don't think we need to ask when they
are only updating a subscription.

Ideally the collective core contributors and us at open collective should
receive these notifications because we both need the feedback.

**Comment by Mayekita** [comment]
@cuiki I've made this flow, I also add a message at the end maybe it has "copy" issues but feedback would be appreciated.
https://www.figma.com/proto/ZnhzRJkD6tqTR62JGVCqvEo3/GitHub-Issues?node-id=2%3A473&viewport=630%2C579%2C0.286676&scaling=min-zoom

**Comment by alanna** [comment]
I think this is important because it's a feedback loop between backers and Collectives.

**Comment by piamancini** [comment]
this hasn't been solved and it's a candidate to the hackathon.

**Comment by znarf** [comment]
The design is not found, can you share it again @cuiki ?

This will not done in the hackathon but is a good bounty candidate.

**Comment by Memo-Es** [comment]
The final design for this was shared when implementing the page to manage contributions, but the feedback path was not implemented.

<img width="719" alt="Screen Shot on 2021-02-10 at 20-58-48" src="https://user-images.githubusercontent.com/49539954/107598339-0e80c380-6be3-11eb-96ec-eb65cd11c585.png">

Design file in [Figma →](https://www.figma.com/file/HN3d7HwVAGjodZWrT2JR5Isx/OC.com-02-Accounts-and-Profiles?node-id=150%3A10817)

cc @Betree

**Comment by Betree** [comment]
This was implemented in https://github.com/opencollective/opencollective-frontend/pull/7736 + https://github.com/opencollective/opencollective-api/pull/7459
