### ISSUE TITLE
Sign In: Ignore white spaces in email field

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1701]
**Describe the bug**
When entering an email with spaces before or after, we consider the email to be invalid.

While this is a very minor issue, it could bother a user copy/pasting from a password manager.

**To Reproduce**
1. Go to `/signin`
2. In the email field, enter a valid email with space(s) before/after
3. Try to click on Sign In, the field is disabled

**Expected behavior**
Sign In button should not be disabled, we want to trim spaces before and after the email address.

**Comment by gutofoletto** [comment]
@Betree Hello there. Can I submit a PR for this issue? :)

**Comment by Betree** [comment]
Hi @gutofoletto, sure :slightly_smiling_face: Don't hesitate to ask me directly on this issue if you have any question.

**Comment by gutofoletto** [comment]
@Betree Hello! Just opened https://github.com/opencollective/opencollective-frontend/pull/1378. Sorry it took so long, had put this task on hold fot a bit after I requested it. 

Hope it helps :D

**Comment by Betree** [comment]
Fixed by https://github.com/opencollective/opencollective-frontend/pull/1378. Thanks!
