### ISSUE TITLE
Support ticket system

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1709]
Myself and @piamancini have been answering most of the support emails, but we need a better system. With multiple people it's hard to see who has answered what and make sure nothing falls through the cracks. We also don't have a great system for escalating issues to @znarf and @xdamman if we need engineering help with an issue.

I looked into ticketing systems and it seems like [Zendesk](https://zendesk.com) is the most popular. But [Freshdesk](https://freshdesk.com) has a free tier that would meet all our needs (I think), and seems to be as good as Zendesk.

Does anyone have thoughts about a support ticketing system? We have pretty low volume and only 2-3 people answering tickets.

**Comment by alannallama** [comment]
@piamancini suggests we look at https://nolt.io/ as well

**Comment by piamancini** [comment]
closing this -- the project is done and up and running.
