### ISSUE TITLE
Very slow load times on Firefox

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1710]
I thought Open Collective was just a super slow site, because every page takes 30 seconds or more to load any page and would make my computer fan go crazy. This has been going on for ages, and I was always using Firefox. But then I tried it on Chrome for the first time today and it loaded straight away. I think there's something going wrong with how Firefox loads Open Collective.

**Comment by Betree** [comment]
There are things that we must be able to do to reduce the bundle size and thus make the site load faster. The homepage for example is 8mb,  which is huge.

Below is a report made using [Dareboost](http://dareboost.com/) - a useful site to detect optimization issues and markup errors, that could help us troubleshoot this issue.

[Dareboost_report_d_5c593a6de96790490a1e27a5.pdf](https://github.com/opencollective/opencollective/files/2831164/Dareboost_report_d_5c593a6de96790490a1e27a5.1.pdf)

**Comment by znarf** [comment]
I get different numbers from Pingdom.
https://my.pingdom.com/reports/rbc/1981202

The bundle size is not that bad but it does take some time to be evaluated by the browser.

We should quietly investigate, back the "every page takes 30 seconds or more to load any page" statement with precise numbers, and see if there is anything special to investigate.

**Comment by kewitz** [comment]
I also couldn't reproduce that:
![image](https://user-images.githubusercontent.com/2119706/52341775-cd61e180-2a13-11e9-84bc-bf29372e41cc.png)

Even tho the page is close to 8mb, there's GZip and Caching which means you actually don't transfer everything.
