### ISSUE TITLE
Allow users to edit their email address

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1711]
In the `/:username/edit` page we should allow users to edit their email.

Because they will need to confirm that they own that new email address, we should send a confirmation token by email before making that change.

**Comment by Betree** [comment]
## Constraints

- We shouln't change the email address before the new one is confirmed
- We must ensure users owns the requested addresses

## Specs

- Add a `emailWaitingForValidation`:string column to `Users`
- Add a `emailConfirmationToken`:string column to `Users`

## Flow

1. Users go to `/:username/edit`

2. Users change email and click save

3. We set `emailWaitingForValidation` to user's provided email address and `emailConfirmationToken` to a random string

4. Users see a special warning on their profile similar to what we show for archived collectives

*Example from Twitter*

![2019-04-01_20:02:16](https://user-images.githubusercontent.com/1556356/55349112-c48c0a00-54b0-11e9-8ecf-a8b3698854a5.png)

5. Users click on the link

6. If token is valid, `email` takes the new values while `emailWaitingForValidation` and `emailConfirmationToken` are set to `null`

**Comment by xdamman** [comment]
Another proposal to kill two birds with one stone:
allow multiple rows in the `Users` table to link to the same `CollectiveId`.
Just add a `confirmedAt` column.

**Comment by Betree** [comment]
@xdamman I think having multiple rows for the same `User` is dangerous, we link to it with `CreatedByUserId` in multiple places and failing to update one of these references can have negative side-effects.

I also don't like the idea of creating another user as a concept: it's still the same user, we only change the email.

**Comment by xdamman** [comment]
Ideally the table Users should be merged with ConnectedAccounts. That’s really what it is. It’s just that the service is “email”. So I wouldn’t be blocked by the fact that (And you are right) we shouldn’t have two users for a same user.

I don’t see any issue with CreatedByUserId. It’s keeping track of who using what account to authenticate created a given row.

**Comment by Betree** [comment]
Three examples of regressions that duplicating users would introduce:

- In https://github.com/opencollective/opencollective-api/blob/636516adf7c36a9bed9f85d967c987798555b2d6/server/controllers/applications.js#L40 we check for the application creator to be the same as user. If users update their email, it will invalidate all that application tokens they have created.

- In https://github.com/opencollective/opencollective-api/blob/636516adf7c36a9bed9f85d967c987798555b2d6/server/controllers/services/email.js#L235 we use `Member.CreatedByUserId` to check the email to notify. If not updated properly, we will send emails to the old address.

- In https://github.com/opencollective/opencollective-api/blob/636516adf7c36a9bed9f85d967c987798555b2d6/server/models/Comment.js#L171-L172 we check `Comment.CreatedByUserId` to see if user can edit it.

It would also make it way more complicate to check all the logs (orders created, comments posted...etc) for a given user.

**Comment by xdamman** [comment]
Ok you win ;-)

But it was tempting to also allow users to have more than one email. And maybe refactor Users to ConnectedAccounts. ¯\_(ツ)_/¯

**Comment by Betree** [comment]
I understand that need and would love to be able to have multiple emails linked to my opencollective account as well, I recently had the case where I got invited as a core contributor to https://opencollective.com/engineering with another email address than the one for my account and had to change it myself manually.

**Comment by alannallama** [comment]
@Betree This feature isn't working for me. When I go to the update emails section in my profile, the box is greyed out and I can't type in a new email. If I click the 'change email' button (even though the box still has my original email address) I get an error saying "invalid email".

**Comment by alannallama** [comment]
Sorry @Betree actually it is working. I think this is more of a UX bug. I didn't understand you have to click "change email" then click into the box, then click the button again. I think it would be much more intuitive if you could just update the email in the text box, and if it detects a change the "update email" button would activate. Then when you click it, it would send the confirmation.

**Comment by Betree** [comment]
@alannallama Good feedback, will do
