### ISSUE TITLE
Collective Update Content Missing from Email

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1713]
The Update looks like this online:

<img width="1110" alt="screen shot 2019-02-06 at 1 23 05 pm" src="https://user-images.githubusercontent.com/5498878/52313191-6263db00-2a12-11e9-9f17-a9822c10300a.png">

But here's what I see in email:

<img width="1012" alt="screen shot 2019-02-06 at 1 23 15 pm" src="https://user-images.githubusercontent.com/5498878/52313197-70b1f700-2a12-11e9-940c-bb56c247a964.png">

I noticed this because it's still pulling through the preview text, but not displaying that text when you open it.

<img width="1022" alt="screen shot 2019-02-06 at 1 24 26 pm" src="https://user-images.githubusercontent.com/5498878/52313224-8aebd500-2a12-11e9-92f5-2cfdd898ce49.png">

I've just got another one that had the same problem, for the Tania Collective.

**Comment by alannallama** [comment]
I got another blank update email from Webform - that's making me wonder if it's actually an issue with this specific Collective??

What I see in email:

<img width="952" alt="Screen Shot 2019-04-09 at 4 45 36 PM" src="https://user-images.githubusercontent.com/5498878/55773956-31258b00-5ae7-11e9-836c-8a6fe5729f1f.png">

What I see on the Collective page:

<img width="1002" alt="Screen Shot 2019-04-09 at 4 46 46 PM" src="https://user-images.githubusercontent.com/5498878/55773967-397dc600-5ae7-11e9-9029-9627594c40ba.png">

@xdamman are you still looking into this one?

**Comment by alannallama** [comment]
Another Collective is having this issue. 

Here's what the update looks like on their page:
![Screen Shot 2019-04-26 at 11 23 25 AM](https://user-images.githubusercontent.com/5498878/56774224-d5ad0a00-6815-11e9-98fc-d532a3c7782b.png)

And here's what it looks like in my email:
![Screen Shot 2019-04-26 at 11 23 37 AM](https://user-images.githubusercontent.com/5498878/56774236-de9ddb80-6815-11e9-8b02-5f6a3f90512c.png)

@Betree are you aware of this issue? it's been going on for a while.

**Comment by alannallama** [comment]
The Collective above sent out two updates recently, and they are both coming up blank in the email.

**Comment by piamancini** [comment]
@xdamman was working on this today
