### ISSUE TITLE
Remove Open Collective Host as an option for new Collectives to apply to

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1714]
Please remove Open Collective Host as an option to apply to when creating a new Collective. We are no longer accepting Collectives to it, but people still apply and we have no good way to change their host over once they do (see #1708).

**Comment by znarf** [comment]
@alannallama Trying to reproduce. Can you add a screenshot? Is that in this list? https://opencollective.com/hosts

**Comment by alannallama** [comment]
@znarf  It used to come up when going through the process from opencollective.com/create, then 'apply to existing host', then you'd see Open Collective Host as an option. But I just tried it again and it's not coming up. Maybe something was changed? In that case, this is solved.

**Comment by znarf** [comment]
I guess someone closed it for new applications.
