### ISSUE TITLE
Remove recompose library

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1717]
Recompose library was introduced to easily add state to functional components. It has been deprecated with the new react hooks and it brings unnecessary complexity to the code.

React hooks are now live, so components can be migrated either to regular components or to hooks.

We want to migrate the following files:

- [ ] `/src/components/ContributeAs.js`
- [ ] `/src/components/ContributeDetails.js`
- [ ] `/src/components/CreateProfile.js`
- [ ] `/src/components/StyledInputGroup.js`
- [ ] `/src/components/StyledRadioList.js`
- [ ] `/src/components/StyledTooltip.js`
- [ ] `/src/lib/withFallbackImage.js`
- [ ] `/src/pages/createPledge.js`
- [ ] `/src/pages/discover.js`

**Comment by flickz** [comment]
Closed this in [#1383](https://github.com/opencollective/opencollective-frontend/pull/1383)

**Comment by Betree** [comment]
Amazing job @flickz, thank you!!

**Comment by znarf** [comment]
@flickz @Betree Seems that recompose was not removed, who can take care of that?

**Comment by flickz** [comment]
I will

**Comment by flickz** [comment]
Closed in [#1487](https://github.com/opencollective/opencollective-frontend/pull/1487)
