### ISSUE TITLE
Anonymous backers getting revealed

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1722]
In the previous contribution flow, there was a 'donate anonymously' option. But even if checked, users could later be associated with those activities through other things connecting to that email address. We recently had a user report that they added people as team members to their Collective who had previously donated anonymously, but this revealed them in the team section as connected to those contributions.

User feedback:

> Contributors who wish to remain anonymous should have their contributions show up without attribution. It shouldn’t create a user whose name is anonymous. It shouldn’t bind all their contributions together. And it shouldn’t be possible to find those contributions by adding their email address.

There does not appear to be an anonymous option in the new Contribution flow, which is probably better because it doesn't promise anonymity without ensuring it. But we still have a responsibility to people who donated and checked the anonymous box previously.

When users inquire, we tell them to create a pseudonymous separate account if they don't want a donation associated with their identity. Is this the best approach going forward?

**Comment by alannallama** [comment]
I think this is a security/privacy issue we need to fix.

**Comment by znarf** [comment]
@alannallama do you see that as a feature request or a bug?

if it's a bug, can you create an issue explaining the steps to reproduce, the current behavior and the expected behavior.

if it's a feature request, can you create an issue with the basic specification for it?

**Comment by alannallama** [comment]
@znarf it's a UX bug. Current behaviour is that people who thought they were donating anonymously are having their donations associated to their public profiles. To fix it, we'd need to make sure donations made with the promise of anonymity stay anonymous.

**Comment by znarf** [comment]
@alannallama if it's a bug, please create a new issue with steps to reproduce (1. 2. 3. ...), current behavior (a precise, easily verifiable, point that is wrong) and expected behavior. We just just need a simple case to look at and make sure we're looking at the same thing.

**Comment by znarf** [comment]
Fixed by the new Incognito feature.
