### ISSUE TITLE
Host fees should be automatically added

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1723]
## User story 
As a host admin, I want host fees processed automatically, so they can be always recorded transparently and error free, and I can easily see accurate finances for my host organisation.

Currently, we manually add the funds when the monthly host report email appears. They get added to a Collective we have to manually set up to receive them.

## Best solution for this problem
User-configurable host fees, whether a % of transactions or set amount fee, which are automatically added to the host org itself, or to a Collective the host admin specifies.

## MVP
Maybe a bot that reads the monthly host report emails and adds the fees? Not sure.

## Metrics 
Hosts effectively use their budgets to further their work supporting Collectives.

## Documentation 
Add a section to the Fiscal Hosts section of the docs about how host fees are handled.

**Comment by alannallama** [comment]
Thought of another reason this is important. Right now, the easiest default thing is to not record your host fees anywhere. This is bad for transparency. If a host does not want to manage their own finances transparently on the platform, they shouldn't be forced to, but the default should be that when you set up a host, a Collective for that host is created and the host fees automatically go there. This should be an option for opt-out during setup.

**Comment by Upperholme** [comment]
The advice I received when we set up our host was to create a collective and then create a new host organisation for that collective, which aligns with your comment @alannallama . 
The docs at https://docs.opencollective.com/help/hosts/create-a-fiscal-host don't currently follow this guidance for some reason.

Given that, in our perception at least, transparency is a key feature of the OC platform, it follows that host fees should also be visible. Given the importance of transparency I would suggest that the implementation of this functionality should be prioritised.

**Comment by alannallama** [comment]
Thanks for your thoughts @Upperholme - I agree.

@znarf @Betree - could the scope and priority of this please be assessed?

**Comment by piamancini** [comment]
@alannallama we should update the docs too.

**Comment by znarf** [comment]
@alannallama question:

> They get added to a Collective we have to manually set up to receive them.

Where is that currently done?

**Comment by alannallama** [comment]
@znarf it depends on the host. We have /opensource set up for OSC and /foundation for OCF. These were created manually. Each month I get the host report and manually add the host fee amount to those Collectives. Some Hosts don't set up a Collective to receive fees (for example we don't have one for c-corp host) so those fees just... disappear and aren't tracked anywhere.

**Comment by alanna** [comment]
In light of our strategic decision to focus on being a product for diverse hosts, I would put this issue forward for potential prioritisation.

This is also very relevant for the new business model discussion @xdamman is leading. To make our proposed new model work, we need to enable hosts to set up and collect fees from their Collectives in the way that works best for them (free, monthly per Collective, % revenue, etc). To make it a good experience, this should happen automatically once they set it up.

Having thought about it more:

### MVP

* Host admin can specify default Collective as a setting in edit > advanced
* Host fees are automatically added monthly to that Collective

### Best solution

* Hosts are Collectives themselves, meaning there would be no need to have a seperate Collective to track its budget
* Host fees are automatically added to this Collective's budget as they come in

**Comment by piamancini** [comment]
I second that this has now higher priority.

**Comment by alanna** [comment]
Bumping this up - is this a requirement for deploying the new pricing model?

**Comment by znarf** [comment]
It's activated for Hosts with the "budget management" feature.

**Comment by alanna** [comment]
Is it really? I thought we were still manually adding host fees each month?

**Comment by alanna** [comment]
@Memo-Es I think this should be in scope for the host dashboard project. Along with #3161 it will really smooth the experience of managing host fees.

**Comment by Memo-Es** [comment]
@alanna I think this is addressed in the 'Fiscal Host Settings' tab in the new admin panel, Is this accurate?

<img width="1408" alt="Annotation on 2020-08-11 at 09-18-54" src="https://user-images.githubusercontent.com/49539954/89909035-3ea7c500-dbb4-11ea-8051-d8b44510fe8d.png">

I'm also thinking to add a widget element with this info to the dashboard

Let me know what you think :)

**Comment by znarf** [comment]
> Is it really? I thought we were still manually adding host fees each month?

@alanna yes, I confirm it's a feature for Hosts with "Budget" activated. Seems that they were added 2 times for July in some places (opensource)

**Comment by alanna** [comment]
Ah, ok  @znarf - Me and @alinamanko were not aware of this and added the fees manually for OSC and OCF as usual. Thanks for fixing it.

We should inform host admins with integrated budgets about this. Can you give me a list of emails of host admins with integrated budgets, and I'll send them a message about host fees being automatically added from now on?

@contraexemplo can you please add this info about automated fees to the documentation about integrated host budgets when you get to that?

@znarf - maybe this feature can be considered complete then? We still have a lot of hosts on the legacy design of a seperate budget Collective and therefore no automatic host fees, but if all new hosts will have integrated budgets with this functionality, and old hosts can transition when they want, then we don't really need to do anything else for automated host fees, right?

**Comment by znarf** [comment]
@alanna  Yeah, we can close! Sharing with you the list of admins privately.
