### ISSUE TITLE
Contribution flow: refresh LoggedInUser at the end

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1724]
Reported by a user:
> The gift card balance remaining is not updating correctly.  It should read $0.  The error message is correct.  The balance in the payment method is incorrect.  

![image](https://user-images.githubusercontent.com/5498878/52542995-65900a00-2e0a-11e9-804b-cfc86415188a.png)

**Comment by Betree** [comment]
This is part of a larger issue which is that logged in user is not refreshed properly. For example if I make an order with a new credit card then go back to the flow, the card won't appear before I refresh the page.

**Comment by znarf** [comment]
I guess we should reload the `loggedInUser` data at the end of the Contribution Flow.

**Comment by Betree** [comment]
@znarf That's a way to do it, or we could load user's payment methods in the query, at the start of the contribution flow. We often have problems like this related to logged in user being cached. I like the idea of loading the data only when we really need it.

**Comment by alannallama** [comment]
OK, should I just tell the user to ignore it and that we're working on it?

**Comment by Betree** [comment]
Yes, it's an annoying bug but we're ensuring the balance is correct on the server side so there's no risk of spending an amount if there's no balance

**Comment by flickz** [comment]
@Betree & @znarf So what is the final proposed solution for this?

**Comment by znarf** [comment]
You can follow @Betree's advice and fix it by making sure to fetch `paymentMethods` at the beginning of the contribution flow.

**Comment by Betree** [comment]
@flickz If you go with this solution (adding `LoggedInUser` in graphql query) you'll need to remove `withUser` decorator to avoid conflicting props.

**Comment by flickz** [comment]
@Betree Can you take this up instead, looks like every fix is breaking something for me?

**Comment by Betree** [comment]
@flickz even just doing `refreshLoggedInUser`?

**Comment by flickz** [comment]
@Betree  Yeah I have this in `componentDidUpdate` method but it's seems to be hanging my chrome tab when "Next step ->" button is clicked.  I feel it's firing multiple times at once.

```js
if (this.props.step === 'payment') {
      await this.props.refetchLoggedInUser();
    }
```

**Comment by Betree** [comment]
Yep, that's not the good place to add it :wink: 

> componentDidUpdate => refetchLoggedInUser() => update component with refreshed user => componentDidUpdate => refetchLoggedInUser() => update component with refreshed user => componentDidUpdate (...)

You want to do the `refetchLoggedInUser` when the order is completed, and only if it succeed.

**Comment by flickz** [comment]
> Edit: This  is incorrect, graphql query would add the data in `props.data` so there's no risk of conflict

@Betree 
I noticed something, when you reload the page the value of `props.data.LoggedInUser` is `null`, 

![screenshot (1)](https://user-images.githubusercontent.com/15707013/55992227-f9b00d80-5ca3-11e9-8624-8a76806a5efe.png)

Checking the API, the value of `req.remoteUser` is `undefined` here too
https://github.com/opencollective/opencollective-api/blob/master/server/graphql/v1/queries.js#L100

**Comment by flickz** [comment]
> You want to do the refetchLoggedInUser when the order is completed, and only if it succeed.

Basically within here https://github.com/opencollective/opencollective-frontend/blob/master/src/pages/createOrder.js#L354?

**Comment by Betree** [comment]
> I noticed something, when you reload the page the value of props.data.LoggedInUser is null,

I can't reproduce on local/staging. Are you sure it's not linked to a change you made?

**Comment by flickz** [comment]
Yeah it is, If you add `LoggedInUser` query to `createOrder` page without removing `withUser`

**Comment by Betree** [comment]
You don't need this if you go with `refetchLoggedInUser()`

**Comment by flickz** [comment]
> Edit: This arrow_up is incorrect, graphql query would add the data in props.data so there's no risk of conflict.

Yeah I know, more of an FYI for this.

**Comment by flickz** [comment]
@Betree Added this `this.props.refetchLoggedInUser();` in `submitOrder` method, as the code below. 

```js
try {
      const res = await this.props.createOrder(order);
      const orderCreated = res.data.createOrder;
      this.setState({ submitting: false, submitted: true, error: null });
      await this.props.refetchLoggedInUser();
      if (this.props.redirect && isURL(this.props.redirect)) {
        const transactionId = get(orderCreated, 'transactions[0].id', null);
        const status = orderCreated.status;
        const redirectTo = `${this.props.redirect}?transactionid=${transactionId}&status=${status}`;
        window.location.href = redirectTo;
      } else {
        this.pushStepRoute('success', { OrderId: orderCreated.id });
      }
    } catch (e) {
      this.setState({ submitting: false, error: e.message });
    }
```
but it is taking forever to refetchLoggedInUser. 

![Screenshot from 2019-04-12 11-19-27](https://user-images.githubusercontent.com/15707013/56031017-36b4e800-5d16-11e9-894b-ed5ad8ede70a.png)

**Comment by Betree** [comment]
@flickz Please open a pull request, the issue is not the good place to review code
