### ISSUE TITLE
Order success: bad tags alignment with long tags

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1725]
We should `text-align: center` the tags to avoid the following issue:

![selection_999 080](https://user-images.githubusercontent.com/1556356/52558261-21910b00-2df2-11e9-8619-e270e869c61b.png)

**Comment by znarf** [comment]
In the end, what's the value of tags here?

**Comment by Betree** [comment]
To easily find related collectives. With the example of the C# community, still small on OC but growing, we can make the assumption that users will be tempted to click on a "csharp" tag to find other collectives they know and would be likely to support.
