### ISSUE TITLE
Pledged Collective claim fails

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1726]
**Describe the bug**
Two different collective admins reported that they got an error when trying to claim their collectives. 

From owner of ESLint: 

> I tried claiming the opencollective.com/eslint page today, but I was told the validation was unsuccessful. I'm not sure what the problem is as I'm an owner of the github.com/eslint and I granted access to the ESLint org when approved the OC app integration.

Screenshot: 
![img_1648](https://user-images.githubusercontent.com/3671070/52591430-ebfc1a00-2e11-11e9-880b-0cb626c00674.jpg)

From Ryan from Cyph: 
> 
> To give a little more context: I was a little confused by the UX, so the order in which I did things in went like this:
> 
> 1. Create personal account (***@linux.com) and start browsing collectives
> 
> 2. Search for Cyph, see that it doesn't exist but donations can be queued up / "pledged" anyway, click the pledge button
> 
> 3. After seeing the pledge UI, I thought it'd make more sense to just proactively create the collective, so I fired up incognito and registered it with a new *** @cyph.com  account
> 
> 4. After seeing a message that there was an approval process and my collective wouldn't go live right away, I just went ahead and finished the pledge process from the original tab, at which point the bad state originally described was produced
> 
> I don't remember exactly what the errors were, but I think for *** @cyph.com it just said unauthorized, and for ***@linux.com it first appeared to work but then after a loading screen it gave me a 503 error or something to that effect.
> 
> Hope that helps.

**Comment by flickz** [comment]
I believe the error shows up because of this incorrect condition https://github.com/opencollective/opencollective-frontend/blob/master/src/pages/claimCollective.js#L155
`this.state.org` is not defined in the state and the condition should be `(!token || !this.state.repo || this.state.membership.length === 0)`.

`503` is a timeout error, the request took longer than 25 secs. Sever network issue most likely. 
what do you think @znarf @Betree ?

**Comment by znarf** [comment]
@flickz the `this.isAdmin()` test is first and we should check why this one is not returning `true`.

**Comment by znarf** [comment]
For repository (ie : `cyph/cyph`), behavior looks correct, we're checking the `permissions.admin` after retrieving the `repo `with the user GitHub token.

For organizations (ie: `eslint`), behavior also looks correct, we're checking memberships with the user GitHub token.

https://octokit.github.io/rest.js/#api-Orgs-listMemberships
https://developer.github.com/v3/orgs/members/#list-your-organization-memberships

We'll only be able to troubleshot that with additional input from the users.

**Comment by piamancini** [comment]
ok should we close then until we hit another issue?

**Comment by znarf** [comment]
We had one new report today. We need to add additional logging to troubleshot that.
