### ISSUE TITLE
Contribution flow: mobile stepsProgress

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1727]
# Specs

- Implement in `StepsProgress` component
- Render on mobile only
- Because this component will be rendered server-side (SSR), we must render both mobile and desktop views and use CSS for conditional rendering.
- A nice optimization can be made client-side thanks to the `withViewport` helper to avoid rendering the view that will not be displayed when `viewport` is not `UNKNOWN`

# Design

![selection_999 082](https://user-images.githubusercontent.com/1556356/52623455-9cb6f780-2eac-11e9-98a6-87e0c52b5fc9.png)

https://www.figma.com/file/JZxZiavpekMXjSL5dFB66BS6/02.-Molecules?node-id=397%3A0 For the individual elements and states

https://www.figma.com/file/9Iq3vBOmZ2EuOacXEYD5yK/03.-Organisms?node-id=377%3A19 for the organism (actual component we’ll use)

**Comment by znarf** [comment]
A $500 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $500 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

**Comment by EugeneHlushko** [comment]
Hi @znarf 
Want to pick this up.

**Comment by rakhi2104** [comment]
I want to take this up.

**Comment by EugeneHlushko** [comment]
@Betree @znarf can you confirm this is still valid and i can pick it up? Maybe assign at me so its transparent :)

**Comment by znarf** [comment]
@EugeneHlushko you are assigned

**Comment by EugeneHlushko** [comment]
Hi @znarf 
Thank you, had time to start working on it, requested early feedback to get up-to-date TODO list to complete the PR.

**Comment by leonardohof** [comment]
@znarf Can assign this one to me?

**Comment by Betree** [comment]
@leonardohof Yes, a work was started in https://github.com/opencollective/opencollective-frontend/pull/2827 but went to stale. Feel free to re-use the code from this PR if you find anything interesting.

**Comment by leonardohof** [comment]
> @leonardohof Yes, a work was started in [opencollective/opencollective-frontend#2827](https://github.com/opencollective/opencollective-frontend/pull/2827) but went to stale. Feel free to re-use the code from this PR if you find anything interesting.

Ok, Thanks.

**Comment by Betree** [comment]
:trophy: This issue is now completed by @leonardohof :tada: 

To claim the **$500** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
