### ISSUE TITLE
Contribution Flow: add support for events

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1728]
We still use the old contribution flow to order event's tickets. The logic is not very different, but we'll need a way to pick the number of tickets (most certainly in step `Details`) to implement it with the new contribution flow.

**Comment by flickz** [comment]
@Betree Can you elaborate more on this?

**Comment by Betree** [comment]
@flickz Sure, first description wasn't detailed enough. I've just updated it.

Basically it's the last feature we need to move away from `createOrderLegacy` before we can totally disable it. If you check the routes in `pages.js` we still have:

```
pages.add('orderEventTier', '/:collectiveSlug/events/:eventSlug/order/:TierId', 'createOrderLegacy');
```

This is use to book tickets for events. I think that the only thing we're missing here is a way to select the number of tickets that we want to order.

Some events may also have a free ticket with an optional amount, we need to make sure it works.
