### ISSUE TITLE
Make links in comments clickable

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1732]
When pasting a link in a comment, it should be clickable even if the user didn't explicitly turned it into a link. That's the way Github and most commenting systems work.

**Example**
On https://opencollective.com/opencollective/expenses/6710 :

![image](https://user-images.githubusercontent.com/1556356/52720638-462ee380-2fa8-11e9-9929-836bbea939aa.png)

**Comment by maddhruv** [comment]
I have a proposed solution for this, if you are okay with the solution, I can go ahead with a PR.

#### Solution

```
- A component doing parsing[1] of the text content (viz. RichText)
- [1] Parsing - check the string (viz. content) (description, comment, or any passed text) to match for urls inside that
- forEach (url) => content.replace(url, `<a href={url}>{url}</a>`)
- render (<p>{content}</p>)
```

#### Usage

```js
<RichText>{content}</RichText>
```
instead of simply doing this

```js
<p>{content}</p>
```

#### Implementation

```js
// RichText Component

```

What do you say @Betree @znarf

**Comment by Betree** [comment]
Your example above wouldn't work, because content would be considered as a string and rendered as such. For it to work like you've described you'd need to use:
```jsx
<p dangerouslySetInnerHTML={{ __html: content }}
```

I'd rather use `react-markdown` with a limited set of options to achieve that, because escaping at this point is tricky.  For example with the component above a malicious user could inject code by encoding the following (based on regex):

```html
My test message http://a-valid-url.com/"></a><script>alert('XSS')</script><a href="___
```

**Comment by maddhruv** [comment]
the final html rendering i would do with the `dangerouslySetInnerHTML`

**Comment by maddhruv** [comment]
@Betree which way of doing it would you suggest me to do?
`react-markdown` vs the one I suggested

**Comment by Betree** [comment]
> @Betree which way of doing it would you suggest me to do?
> `react-markdown` vs the one I suggested?
> and also do you want to open the link in a new tab or the same tab?
> 
> `react-markdown` options -> `linkTarget`

I'd say in a new tab. Unless you can demonstrate that your solution is 100% safe from XSS injections (the example you provided above is not) we should prefer using `react-markdown`.

If you go with this solution please limit the allowed types to links only, we're about the revamp the expenses flow and we don't want people to start writing markdown in their expenses descriptions, otherwise we'll need to migrate them later.

**Comment by maddhruv** [comment]
@Betree `react-markdown` is not able to parse it, 'cause the return string in comment i.e. `comment.html` is in the format `"<p>something</p>"` which it doesn't recognizes.
Please have a look at this - https://codesandbox.io/s/proud-snow-v3pm4?fontsize=14

I am not sure, if we can trim out the `<p>` and `</p>` tags from the `comment.html` returned property. Does commenting creation always adds this?

**Comment by Betree** [comment]
Ah then we need to fix this at the `HTMLEditor` level. I didn't know that the comment form was using this component. `https://www.npmjs.com/package/quill-auto-links` maybe?

**Comment by maddhruv** [comment]
This can be done for the future comments/descriptions to be added, but what about the current ones - the ones already there?
How would we do the formatting there?

**Comment by maddhruv** [comment]
This is a very vulnerable approach
`const commentText = comment.html.replace('<p>', '').replace('</p>', '')`

but still after doing this, if I add the prop for `allowedTypes` as
`allowedTypes={["p", "link"]}`
it doesn't render anything, no clue why. 😕

**Comment by Betree** [comment]
@maddhruv We'll be able to convert the ones already there with a migration in the API. It will be much safer to use a regex there cause we can preview the results before making the change.

`.replace('<p>', '').replace('</p>', '')` won't help because a lot of comments contain way more HTML than that, some of them have images, titles, links...etc

**Comment by maddhruv** [comment]
@Betree Let's split this task into two
- [ ] migrate the currently saved comments
- [ ] use https://www.npmjs.com/package/quill-auto-links in the editor itself to format in future comments

**Comment by Betree** [comment]
Let's not do this one at the moment. We'll consider it while revamping the expense flow.
