### ISSUE TITLE
'Unknown Error' when trying to access OC EU host dashboard

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1735]
**Describe the bug**
I'm trying to go to https://opencollective.com/europe/collectives/expenses
It looks like it's loading, but then says "unknown error" and I can't access the dashboard.

**To Reproduce**
1. go to https://opencollective.com/europe/collectives/expenses
2. see error

**Expected behavior**
Supposed to load the dashboard so I can pay expenses as admin.

**Screenshots**
<img width="1280" alt="screen shot 2019-02-15 at 5 42 32 pm" src="https://user-images.githubusercontent.com/5498878/52834936-1a972f00-3149-11e9-9f43-3dbc93e34216.png">

**Desktop (please complete the following information):**
MacOS, Chrome browser, both up to date

**Additional context**
I can access all the other host dashboards, and https://opencollective.com/europe loads fine for me.

**Comment by znarf** [comment]
That was fixed manually by @xdamman.

After a Collective deletion, there were some orphan events in the database.
