### ISSUE TITLE
Backer not showing up in API 

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#1736]
**Describe the bug**
Backers are not appearing in the API response despite having a valid transaction. Are we using an incorrect endpoint to get _all_ backers?

**To Reproduce**
Donate to Octobox, https://opencollective.com/brackett-development
Check the API endpoint for the project (https://opencollective.com/octobox/members.json)

**Expected behavior**
The backer appears in the API response. The backer appears on the collective page. 

**Additional context**
We are using the API to complete a synchronous transaction with a user (PR and code at https://github.com/octobox/octobox/pull/1563) and periodically checking the API for new transactions and to expire accounts that have cancelled their repeating donation (code at https://github.com/octobox/octobox/pull/1547/files).

**Comment by znarf** [comment]
@BenJam When loading https://opencollective.com/octobox/members.json I see 79 items and `brackett-development` at position 75.

Do you have another example?

**Comment by BenJam** [comment]
Weird, I was quite sure it wasn’t there previously. Is there a delay between the two at all?

**Comment by znarf** [comment]
@BenJam I checked and this can be explained by a CDN cache, the data being stale up to 100 minutes. We're gonna check and see if we can review this policy.

In the meantime, if you need to bypass this, you can add an extra random parameter to the URL, ie: https://opencollective.com/octobox/members.json?ts=1550441707

**Comment by BenJam** [comment]
Awesome thanks for confirming. I though maybe I was taking crazy pills. Which is standard for coaching problems :)
