### ISSUE TITLE
URL requirements

### ISSUE THREAD

**Issue by 7i4** [opencollective/opencollective#1737]
**Describe the bug**
The issue is about website https://sizzy.co

It crash into permanent reloading with sefl.location.href like the following one:
https://sizzy.co/?url=https%3A%2F%2Fhttps%3A%2F%2Fhttps%3A%2F%2Fhttps%3A%2F%2Fhttps%3A%2F%2Fhttps%3A%2F%2Fhttps%3A%2F%2Fhttps%3A%2F%2Fhttps%3A%2F%2Fhttps%3A%2F%2Fhttps%3A%2F%2Fhttps%3A%2F%2Fhttps%3A%2F%2Fhttps%3A%2F%2Fhttps%3A%2F%2Fhttps%3A%2F%2Fhttps%3A%2F%2F%20dfdfdf

**To Reproduce**
1. Go to the main page
2. Focus on `<input type="text" placeholder="Enter an URL" class="kgPzEf">`
3. Type Space symbol and a couple of other symbols for example " abc" (without quotes)
4. Hit Enter button or click ![image](https://user-images.githubusercontent.com/8938682/52902446-ecd1e900-3221-11e9-95a2-a7946ca28d3d.png)

5. Enjoy the performance 

**Expected behavior**
Alert message with URL requirements

**Screenshots**
![ezgif-2-f30f6a2ea569](https://user-images.githubusercontent.com/8938682/52902417-864ccb00-3221-11e9-9d42-6c68337039a6.gif)

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra 10.13.6 (17G5019)
 - Browsers: both Google Chrome 72.0.3626.96 and Safari 12.0.3

**Comment by znarf** [comment]
Sorry, here is Open Collective here, not Sizzy. Please fill an issue on https://github.com/kitze/sizzy
