### ISSUE TITLE
Allow usual username/mail + password login

### ISSUE THREAD

**Issue by rugk** [opencollective/opencollective#1738]
## User story 
As a user of OpenCollective, I want to login with "usual" passwords, because this "passwordless login" is insecure and cumbersome.

I've explained this in detail [e.g. here](https://discourse.mozilla.org/t/allow-usual-mail-password-login/18192), but the general reason is: With a proper password manager, it is harder to login with a mail sent each time, then two clicks to autofill username+password.

Regarding security, the current passwordless login is obviously "only" slightly worse than a "password reset" mechanism, because you, at least notice if someone broke into your account (and changed passwords etc.)  when resetting passwords.

## Best solution for this problem

Let users set a password after clicking the verification link first. It allows them to upgrade their security (for such a service really needed!) and a "sane" login for users with password-managers.

## Metrics 

Usage of that feature?

**Comment by Betree** [comment]
While it surely decrease the security for users using a password manager, password less authentication actually increase security for a large number of users that either use the same password everywhere, or a very weak one.
Passwordless authentication is actually safer than using a password + a password reset mechanism.

I'd rather think about two factors authentication, or a secret code that you use for sensitive actions (but not to login) which will not decrease our current level of security.

**Comment by rugk** [comment]
> Passwordless authentication is actually safer than using a password + a password reset mechanism.

It's not. Passwordless auth (via mail!) is less safe than password reset. Please back your claim by facts.

> two factors authentication

Good idea, but that's a different issue. Opened a different issue for that: https://github.com/opencollective/opencollective/issues/1746

Also the 2FA is about three possible factors you can use (["something you know/have/are"](https://en.wikipedia.org/wiki/Multi-factor_authentication#Authentication_factors)) and email and any other 2FA factor (except of biometrics) that is currently used by websites is all "something you know". So it's not a different way of authentication.

---

Maybe I should repeat it: My main concern is **not** security. My main concern is **usability**. Username/password auth is way more convenient for users using password managers than any way of 1) entering your mail 2) logging in to your mail account 3) clicking a link there - instead of just two clicks directly on the site. And password managers are the only way to do it securly, you should not discourage them.

**Comment by Betree** [comment]
> It's not. Passwordless auth (via mail!) is less safe than password reset.

A password reset feature brings the same risks than having a passwordless authentication: in both cases if the mailbox is compromised then attacker will have access to your account.

By adding the ability to login with a password, you add new weaknesses for all users that don't have a sane password policy (weak or too common passwords, using the same password everywhere, storing passwords in browser's password manager...). 

- [In Linkedin data breach](https://blog.preempt.com/weak-password), 35% of passwords were present in dictionaries.
- Numbers change from one source to another, but some of them argue that there's about 40-80% of people use the same password everywhere ([1](https://www.cyclonis.com/report-83-percent-users-surveyed-use-same-password-multiple-sites/), [2](https://securityboulevard.com/2018/05/59-of-people-use-the-same-password-everywhere-poll-finds/), [3](https://nakedsecurity.sophos.com/2013/04/23/users-same-password-most-websites/)).

Unfortunately we can't force our users to use a password manager. You can spend time ensuring users choose strong passwords (length, entropy...etc) but you can't force them to use a different password than the one they use on all other websites.

This is why I argue that passwordless is actually more secure: same risks, less failure points. I'd love to hear the opposite arguments.

---

Regarding usability your point makes sense and if other users are frustrated by the existing system then we should definitely work on it.

I encourage all users sharing @rugk's concerns to vote up on this issue so we can decide how we should prioritize it.

**Comment by rugk** [comment]
> A password reset feature brings the same risks than having a passwordless authentication: in both cases if the mailbox is compromised then attacker will have access to your account.

Difference is, as I stated already:
>  you at least notice if someone broke into your account (and changed passwords etc.) when resetting passwords.

You cannot notice an account breach if you have a single-login (essentially like OAuth via your mail provider). ([And yes, that happens](https://www.forbes.com/sites/kateoflahertyuk/2018/09/29/facebook-data-breach-what-to-do-next/). Then OAuth is flawed, this here, too.)

> for all users that don't have a sane password policy

Users anyway have to protect their mailbox via passwords. Possibly some users use a better password there, but I doubt it hardly differs. If it all, because (*your* argument here):
> * Numbers change from one source to another, but some of them argue that there's about 40-80% of people use the same password everywhere ([1](https://www.cyclonis.com/report-83-percent-users-surveyed-use-same-password-multiple-sites/), [2](https://securityboulevard.com/2018/05/59-of-people-use-the-same-password-everywhere-poll-finds/), [3](https://nakedsecurity.sophos.com/2013/04/23/users-same-password-most-websites/)).

If that is the case (which I don't doubt), "paswordless login" via mail does not help, because also your mail account is protected by a password.

> Unfortunately we can't force our users to use a password manager.

But you can at least not discourage them by making usage a pitty with "passwordless" logins.
And as always said, if you want, make it optional, but let me set a password.

>

**Comment by rugk** [comment]
ssh

**Comment by davebrny** [comment]
im finding this quite awkward as well.  

when im logging into the site im doing it on my desktop computer, but im hardly ever logged into my email there. i only really use the email app on my phone but thats not much use because i will be clicking the link in the email which will open it in my phones browser.  
if i want to log into my email service on my desktop computer then i have to get out my phone to use the 2 factor app. 

its all a lot of bother for something that could be autofilled by a password manager. the solution the rugk stated above sounds like it would keep everyone covered

**Comment by alanna** [comment]
I agree with this - we get a number of support requests from people who have lost access to their email for whatever reason. It's way more secure to let someone log in with a username and password and update their own email, then taking it on trust that someone messaging you from their new email is actually the same person and changing their account that way.

**Comment by rugk** [comment]
sssh

**Comment by znarf** [comment]
This is a project that we want to do in on the mid-term. It's currently difficult to prioritize but it will be done.

**Comment by rugk** [comment]
shh #badbot :no_bell::robot::no_bell:

**Comment by piamancini** [comment]
Adding here from someone else who wants to support the issue and emailed: 

" I lack a GitHub account to participate, so this E-mail is a way for me to
say "me too" if nothing else, to express the importance of this to me
and to others, and to offer my personal take. I believe either a
conventional 2FA option and/or OpenID login would be a nice improvement
to OC. Personally I'd lean more toward the OpenID as an option (maybe
not a requirement, so that the normal E-mail login method can still be
used) as it means that OC isn't responsible for handling passwords.
I've wanted to set up an OpenID auth server for myself but I'd like to
see more adoption of it. I think it's a pretty cool, established
standard, unless someone else has already made something good enough to
justify switching from OpenID."

**Comment by crankycyclops** [comment]
As a random user, I just want to chime in and say that I was considering donating to a project on a recurring basis until I discovered this "passwordless" login via email. I won't trust my credit card details to such a system, and so, unfortunately, I won't be able to contribute :(

**Comment by Betree** [comment]
Some documentation pages that were added recently:
- About the [security of our passwordless login system](https://docs.opencollective.com/help/product/log-in-system#about-security)
- About [our security in general](https://docs.opencollective.com/help/product/security) (which describes that we don't store any credit card number)

**Let's keep this issue about describing the implementation of a password login.** If there are more concerns about the security of the passwordless approach feel free to open another issue to discuss it specificly (or to contact `security@opencollective.com` if it's something sensitive).

**Comment by FezVrasta** [comment]
If allowing password login is not an option you could at least make the emails arrive quicker. It usually takes 15 seconds for an email to arrive, that's so annoying.

**Comment by FezVrasta** [comment]
Don't close this issue. This is an automatic message by [Fresh](https://github.com/c-hive/fresh) - a bot against stale bots.

**Comment by alanna** [comment]
Hahah I love the Fresh bot.

**Comment by kaylarep** [comment]
another [request ](https://opencollective.slack.com/archives/C0HSLRNVC/p1648087866167829)for this:
>can I request a normal password based login instead of the email link?

>The point about accessibility definitely stands though, especially as password managers are getting more popular

**Comment by shannondwray** [comment]
The current password less access doesn’t work on ipads. This is because on an iPad when you click the link via the gmail app it opens an in between safari browser, you get logged in here rather than directly on the web browser. I haven’t been able to figure out a way to login on my web browser

**Comment by lucaszischka** [comment]
Hello, I would like to give my quick opinion on this: I understand that passwordless login is more secure than password login + password reset. However I think there Is a pretty easy solution: Default to passwordless login, but give a choice to use a password instead - but only if the user has 2FA activated. Because then password login (+ 2FA) is way more secure).

Another reason why I would suggest login with a password is the already mentioned password manager issues without password. But I don't mean that I can't save my email to a password manager without a password, I also can not add 2FA to without an account. So currently I have neither a strong password, nor 2FA.

**Comment by xenago** [comment]
This system is really bad for accessibility and is causing a variety of issues. I am struggling to understand why a proper password-based login system is not possible to implement. Users on devices other than a desktop PC, or persons with accessibility needs are left out in the cold.

**Comment by Betree** [comment]
It is possible to implement and there's an overall consensus in the core team that this is something we want to support. 

Historically, it has been difficult to prioritize mostly because there is a gazillion of things the team needs to work on, and this one (though already proposed and discussed for prioritization, like [here](https://github.com/opencollective/opencollective/issues/5330)) never made it to the top yet.

The lack of password-based authentication is clearly a pain point for many users, including members of the core/support team. I would like to see it prioritized for the next sprint and will promote the idea during the next round of prioritization.

**Comment by xenago** [comment]
That is fantastic news, I know many people will be happy to hear it is being prioritized.

**Comment by Betree** [comment]
To be clear: me promoting the idea among the core team doesn't mean it is being prioritized yet. Prioritization is done collectively; multiple persons need to be convinced that this is more important than the other items on the list for it to happen. I'm pretty hopeful that this is the case (especially with our recent engineering capacity increase), but we can't promise anything at this stage.

**Comment by pbrkr** [comment]
This issue needs to be at the top of the priority list. I consider this to currently be a major security flaw in OpenCollective as well as an accessibility issue.

* A "password reset" is similar to logging in using just an email address, yes. But password resets should be rare events and should trigger security notifications. If your account on some website is compromised via a password reset process, there's at least some chance of noticing this if a security notification is issued. However if passwordless email login is the normal process there's no way to notice this. So a password reset process with notification has a lower risk level than passwordless login.
* The above issue is mostly mitigated by enabling proper 2FA, but the 2FA login supported by OpenCollective is not required or on by default for new accounts. If the issue with password logins is that "most users default behaviour is bad" then you need to realise most users will not by default reach into the account settings and enable 2FA.
* **I would argue OpenCollective does not currently implement 2FA.** Passwordless login is a "thing you have" factor for most people as their mobile phone which contains their authenticator app is logged in to their email accounts (I fall into this category). Therefore an authenticator app and a passwordless login via email are not a two distinct factors. A second factor should be something different - with password + authenticator app you have "thing you know" + "thing you have".
* Email does not have strong guarantees about time-to-delivery. Not all systems are set up for immediate email processing and some folks turn off email polling when they're using low bandwidth or high cost internet connections.
* This is an accessibility issue. Users with ADHD may want to avoid checking emails as that is a point of huge temptation for distraction. I have email notifications turned off to reduce distraction and do not want to go digging into my inbox as part of a login process.
* Most operating systems and email clients only support one default browser which handles all links. This makes it a pain to maintain multiple browsers or profiles (e.g. one for work and one for personal use). Sending passwordless login links via email exacerbates this issue as the link ends up opening in a different browser profile to the one I was trying to log in from.

**Comment by BenJam** [comment]
- [ ] kick off conversation this week

**Comment by FezVrasta** [comment]
While we are here, maybe Passkeys would be more in line with the original idea of a password-less OpenCollective?

**Comment by znarf** [comment]
The feature is now available for everyone to use from the "Security" section of you personal settings.

There is still some follow up work and we will be tracking this from the new issue. https://github.com/opencollective/opencollective/issues/6337

**Comment by alanna** [comment]
Is this ready for a fire announce?
