### ISSUE TITLE
Transaction data requirement

### ISSUE THREAD

**Issue by yiikou** [opencollective/opencollective#1739]
Thanks again for the well-maintained document! I am a researcher who interested in the impact of the monetary incentive on OSS and the opencollective is a great dataset which deserves further study. My target is to provide useful insights for the backers, projects and the platform.

Following is the script I found in https://github.com/opencollective/opencollective-api/pull/1723/commits/f47c42eeed467f50295c7feb3857c7ab77544b06, which is used to export transaction data. Since I want to analyze the full transaction dump, I modified the startDate placeholder to '2015-11-01' and the endDate placeholder to '2019-02-01'. (btw, is the earliest creation date of projects on opencollective is "2015-11-01"?)

Since the rejected expense information is also important and valuable, how should I query about rejected expense information?

Query script

    SELECT 
    t."createdAt" , c.slug as "collective slug", t.type as "transaction type", t.amount::float / 100, 
    t.currency, fc.slug as "from slug", fc.type as "from type", t.description, e.category as "expense category", 
    h.slug as "host slug", t."hostCurrency", t."hostCurrencyFxRate", 
    pm.service as "payment processor", pm.type as "payment method type",
    t."paymentProcessorFeeInHostCurrency"::float / 100 as "paymentProcessorFeeInHostCurrency", 
    t."hostFeeInHostCurrency"::float / 100 as "hostFeeInHostCurrency", 
    t."platformFeeInHostCurrency"::float / 100 as "platformFeeInHostCurrency"
    FROM "Transactions" t
    LEFT JOIN "Collectives" fc ON fc.id=t."FromCollectiveId"
    LEFT JOIN "Collectives" c ON c.id=t."CollectiveId"
    LEFT JOIN "Collectives" h ON h.id=t."HostCollectiveId"
    LEFT JOIN "PaymentMethods" pm ON pm.id=t."PaymentMethodId"
    LEFT JOIN "Expenses" e ON e.id=t."ExpenseId"
    WHERE t."createdAt" >= "2015-11-01" AND t."createdAt" < "2019-02-01"
      AND t."deletedAt" IS NULL
    ORDER BY t.id ASC
      `
 

Thank you in advance!

**Comment by xdamman** [comment]
Yeah we can’t export expenses like that because the receipts / invoices may contain sensitive information. Also note that this won’t pull up rejected expenses. This will only get the ones linked to a transaction, therefore the PAID ones.

**Comment by yiikou** [comment]
> Yeah we can’t export expenses like that because the receipts / invoices may contain sensitive information. Also note that this won’t pull up rejected expenses. This will only get the ones linked to a transaction, therefore the PAID ones.

Thanks for the explanation. I have already removed the `e*` in the main content. Btw how to query the rejected expense information? Should I raise a new request for this requirement?

**Comment by xdamman** [comment]
It's ok I've adapted the query. Everything is in https://drive.opencollective.com

Have fun with the data and please share what you found! :-)

**Comment by yiikou** [comment]
Great! Thanks for your help!!!!! Definitely, I will share the result and hope that will help this community as well!
