### ISSUE TITLE
Unable to change the cover picture of a host organization

### ISSUE THREAD

**Issue by jfdh** [opencollective/opencollective#1740]
**Describe the bug**
Unable to change the cover picture of the host organization https://opencollective.com/brusselstogetherasbl

**To Reproduce**
1. Go to https://opencollective.com/brusselstogetherasbl/edit
2. Click on Images
4. See error : the new picture is displayed in the icon but won't appear on the main page

**Expected behavior**
I expected that after pressing "save", the cover picture would change

**Screenshots**
![capture](https://user-images.githubusercontent.com/30813303/52917012-8793fb80-32e6-11e9-9c0f-6b62cd04500b.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 72.0.3626.109 (Official Build) (64-bit)

Thank you for your help!

**Comment by znarf** [comment]
There was some hardcoded blue color in the settings.
