### ISSUE TITLE
links on homepage footer are not working

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1743]
**Describe the bug**
links on footer just hang the page, nothing happens.

**To Reproduce**
1. Go to opencollective.com
2. Click on Docs&Help link on footer

**Expected behavior**
successfully being directed to the address on the link. 

**Additional context**
A user reported same behaviour when clicking on an invoice PDF, might be related?

**Comment by Betree** [comment]
On it

**Comment by Betree** [comment]
This actually affects all footer's external link. Fix is on its way
