### ISSUE TITLE
Add 2FA two factor authentication for login

### ISSUE THREAD

**Issue by rugk** [opencollective/opencollective#1746]
## User story 
As a user of a platform realted to money stuff, I really want to secure my account with two factors, i.e. 2FA = two factor authentication.

## Best solution for this problem
_What does the ideal solution look like?_

These methods should be offered
* TOTP (Google Authenticator, FreeOTP, Authy, AndOTP etc.)
* FIDO U2F/WebAuthn (hardware dongle)

SMS is not really required IMHO. It's just not cheap and not really secure.

## MVP
_What will be built as an MVP? (Please refer to our [wiki](https://github.com/opencollective/opencollective/wiki/Feature-Spec-Template) for what's acceptable as an MVP.)_

maybe start with one auth provider only, TOTP is likely one of the easy ones. FIDO U2F/WebAuthn may be added later.

## Metrics 
_What metrics will be used to measure impact?_

usage

## Documentation 

I saw https://github.com/opencollective/opencollective/issues/459, but it is unclear to me what that issue is about and it seems to be about a very specific thing, which (may) include 2FA...

**Comment by Betree** [comment]
Thanks for creating this! It's a strong +1 for me, TOTP is a great way to easily secure an account.

I also agree that SMS is not a good solution.

While designing this, we should also think about a policy for users that are unable to get their 2FA code to retrieve their account, like asking for a proof of identity.

**Comment by skade** [comment]
The lack of this was pointed out in one of our campaigns as a reason against using Open Collective as a donor. https://www.reddit.com/r/rust/comments/c8951c/status_of_rustanalyzer_achievements_and_open/

**Comment by znarf** [comment]
@skade Looks like that this person is more asking for login + password first https://github.com/opencollective/opencollective/issues/1738 Which is absolutely legit. I definitely see that coming in the near future.

**Comment by sbinlondon** [comment]
2FA for login is being tested by the team at the moment. We are also building 2FA for payouts by hosts.

Our current plan is that if a host chooses to enable 2FA for payouts, then every user who is an admin will need to enable 2FA on their account to be able to do the payouts.

At this time I believe that is the only place we plan to roll out 2FA, not for every single user, though we'll keep this under consideration.

**Comment by sbinlondon** [comment]
2FA for login has been released! You can find it in your profile settings menu. Please open another issue for any bugs/further work you believe we should do on this 🙏

**Comment by stephenyeargin** [comment]
@sbinlondon Didn't want to clutter up the repository with another issue, but making a note that the docs still refer to this feature as "available soon". Tested it today and everything is :sparkles:.

https://github.com/opencollective/documentation/blob/v2/product/log-in-system.md#L21

**Comment by Betree** [comment]
Good catch, thank you @stephenyeargin. I'm opening https://github.com/opencollective/documentation/pull/95 to update that
