### ISSUE TITLE
Lots of promise warnings in tests

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#175]
Seeing a bunch of Promise warnings where they aren't returned from the same handler. Mostly part of authentication flow. You are probably the best person to take a look at this @sedubois.

**Comment by sedubois** [comment]
I don't see the warnings you mention in CircleCi: https://circleci.com/gh/OpenCollective/opencollective-api/2314

And when running locally, I see multiple `(node:7331) Warning: a promise was created in a handler but was not returned from it`, but without stack traces, even though `NODE_ENV` is `development`. Adding `Promise.config({warnings:true,longStackTraces:true})` (see [doc](http://bluebirdjs.com/docs/api/promise.config.html)) doesn't help. Don't know what I'm missing.

**Comment by asood123** [comment]
Strange. I wonder if upgrading node took they away. I still see them locally on `npm run test`
