### ISSUE TITLE
Open Collective bounties experimentation

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1751]
This is the result of the Bounties workshop. Feel free to comment, share thoughts or questions!

# Open Collective bounties

- For the first iteration, we will rely on Github labels (no third party tools)
- We need a bounty policy (BOUNTY_POLICY.md), advertised in README.md
- Users should be able to add bounties on issues (sponsors)
- Good candidates issues:
  - Technical debt
  - Packages updates
  - Not a priority
  - If it's a feature, it needs to have proper specifications, design and owner
  - If it's a bug, it needs to be confirmed/reproduced
- Amount should be disconnected from time, but internally we should still evaluate how long it would take us
- We should talk about and evaluate new bounties during the weekly meeting
- Each bounty should have an owner in the team

## Bounty policy

- QA guidelines
  - Tests needs to pass
  - Localisation (FormattedMessage)
  - Must be accepted by the team
- Bounty amount is linked to complexity (complex issues should ideally be split in smaller issues)
  - Simple --> $100
  - Medium --> $300
  - Complex --> $1000
- Should have a link to a list with all unassigned issues that have a bounty 
- Issue may be unassigned in case of inactivity (time span to be defined)

## Workflow

1. Tag issues ourselves, add a comment with explanations and link to BOUNTY.md
2. Wait for people to pick the issue by commenting
3. Assign the issue
4. Open PR
5. QA, review loop
6. PR gets merged
7. Add expense on Open Collective
8. Get paid!

## Communication

We should communicate on new bounties to incentive people to participate.

- Tweet
- Slack
- Newsletter
- Blog post

## How do we measure impact

- Main metric: repeated contributors (engagement)
- Number of closed issues

**Comment by piamancini** [comment]
@Betree can we close this? we've implemented the bounty.md already. Not sure if we have outstanding issues here we want to do

**Comment by Betree** [comment]
Agree, this is solved by https://github.com/opencollective/opencollective-frontend/pull/1453
