### ISSUE TITLE
wrong paypal address shows connected in the host dashboard

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1752]
**Describe the bug**
the open source collective dashboard shows the foundation's paypal connected. 
I refreshed the connection to ensure we connected the c6 but the c3 is still showing. 

Also dates is wrong 

<img width="1272" alt="screen shot 2019-02-20 at 11 49 55 am" src="https://user-images.githubusercontent.com/3671070/53091435-d8d00500-3509-11e9-994f-42fd8ebe2419.png">

**Comment by xdamman** [comment]
Fixed in the production database.
That was because we linked the wrong paypal account in the past and when we fetch the list of payment methods we were ordering them by the oldest first.
I just removed it from the db for now which fixes it. PR coming for long term solution.
