### ISSUE TITLE
Allow tiers to have both a monthly and a yearly interval simultaneously

### ISSUE THREAD

**Issue by dodgepong** [opencollective/opencollective#1754]
## User story 
_As collective, I can set up my tiers such that contributors can choose to give on a monthly or yearly bases to a tier so that contributors can choose what works best for them._

## Best solution for this problem
Monthly pledge intervals make sense when the amounts are small or the donors are individuals or small companies, but larger companies tend to prefer making pledges on a yearly basis since it ends up working better when budgeting. It would be nice if we could set up tiers such that they can be met via monthly gifts or yearly gifts. For example, suppose we had a tier at $12,000 per year. A company might not be able to give $12,000 in a lump sum, but they could give $1000 a month. Not to mention, it's easier to make 12 $1000 payments with a credit card instead of one $12,000 payment.

While it's true that backers could rescind their monthly payments before a year is up, potentially giving less than a full-year donor had given, they would also be giving up any benefits they would be getting for giving at that tier.

The only other question is whether monthly pledges should exactly equal 1/12th of a yearly pledge, or if there should be some sort of price bump for people who give monthly to get that tier. There is value in having finds given for a whole year as opposed to monthly due to the ability to plan and budget better. It may just be best to let the collective define the default and suggested amounts for each, so they can decide which model works best.

## MVP
When setting tiers, collectives can select "monthly and yearly" in the "Interval" drop-down, and set the respective default/suggested amounts for each.

**Comment by znarf** [comment]
Alternative, all monthly tiers can be subscribed yearly upfront. No one can complain about that right?

**Comment by alanna** [comment]
I still think we should make this possible. We can achieve a similar result by having a sponsor send up a year's worth of donations and crediting their Organization profile so they can then set up monthly donations at a specific tier level. But this is currently a manual, messy process, and if they are willing to pay by credit card if they will show up at the correct tier, then we should let them.

**Comment by Betree** [comment]
Implemented in https://github.com/opencollective/opencollective/issues/4089 as a "Flexible interval" option in edit tiers.

![image](https://user-images.githubusercontent.com/1556356/226664572-6d6e0e32-7f44-49be-b1ec-19aac8e89f60.png)
