### ISSUE TITLE
Add GitHub Contributors for Techqueria.org

### ISSUE THREAD

**Issue by fvcproductions** [opencollective/opencollective#1755]
Similar to #282

> On other projects I saw a list of Github contributors listed on the bottom too. Can we add that to [opencollective.com/opensourcedesign](https://opencollective.com/opensourcedesign) as well? We have the organization [@opensourcedesign](https://github.com/opensourcedesign), and our most active repos are /organization, /opensourcedesign.github.io, /jobs and /events

Would it be possible to do this as well for https://github.com/techqueria? 

We are hoping to add our GitHub contributors to various READMEs. 

Thank you! 💛

**Comment by piamancini** [comment]
hi @fvcproductions! Thank you for reaching out. 
I added the url to your collective but we are not surfacing the GitHub contributors anymore at the moment. We are working on a new collective page and we'll likely bring this back.

I noticed too that your collective still doesn't have a host organization if you would like to be fiscal sponsored by the Open Source Collective then you'll need at least a repo of 100 stars. If you have a bank account you can use, then you just need to go to your collective /edit and select fiscal host and create your own host organization. You just need to have a stripe account.

more help here: https://docs.opencollective.com/help/

**Comment by fvcproductions** [comment]
Ah okay, thanks for all the help - much appreciated!
