### ISSUE TITLE
Multiline in expenses private instructions

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1757]
As an user filling expenses on Open Collective, I sometimes have a lot of information to put in expense's private instructions. For example if I expect to get the money on my bank account, I will have to add my IBAN number, my BIC number, a label (...):

![image](https://user-images.githubusercontent.com/1556356/53231317-ef509a80-3688-11e9-8e94-f0f31452a5fe.png)

Having rich text here is not a requirement but we should at least support multiline.

If possible, we should avoid modifications to the API for this.

**Comment by flickz** [comment]
Just to be clear, the goal is to transform this (current)
![screenshot from 2019-03-04 15-32-20](https://user-images.githubusercontent.com/15707013/53739859-18e0a180-3e93-11e9-93b0-f1e27bc1873a.png)

into a rich text editor as shown above?

**Comment by Betree** [comment]
@flickz Not for the first iteration, for now it's just a matter to properly display the multiline values. If you enter a multiline string in this field today, it will be displayed on a single line after you submit it.

**Comment by flickz** [comment]
What’s your suggestion on how you think that could be handled properly?

**Comment by Betree** [comment]
I haven't investigated on the root cause yet, but either:

- This is just a css `white-space: pre;` to set on the container div
- New lines are stripped from value (in frontend or api) and it needs to be removed
