### ISSUE TITLE
remove in kind donations feature

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1758]
We did this feature (see issues #245 #1030 for context), but it's not properly executed. We don't account for this transactions properly and it shows like a credit / debit line in the host transactions when that transaction never happened. 

It's not a used feature and it a potential issue, we should just hide it / remove it until we do this properly.

**Comment by alanna** [comment]
I'm adding priority to this because I just actually paid a "donation" expense today and I don't know what that means or how to undo it. We need to disallow users from selecting this option until we fix it.

**Comment by znarf** [comment]
Mentioned in https://github.com/opencollective/opencollective/issues/1895
