### ISSUE TITLE
Improvement → Error page

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1764]
# Motivation

Our current error page is very basic, we just show "Error" or "Request Error":

![image](https://user-images.githubusercontent.com/1556356/53479948-77b0b000-3a7a-11e9-85a5-4e338d74ae33.png)

This induce a certain number of issues:
- User has no clue about why this happened
- User has no clue about how to solve it
- User has no clue about what he or she should do next
- User can feel responsible of the error
- It doesn't look professional - the error looks "uncatched"

# Proposal

### Change the message to de-dramatize
> Ooops, an unexpected error seems to have occurred.

### Add actions

  - **`Reload the page`**
  - **`Contact support`**
  - **`Open an issue on Github`**
We can prefill the issue with the error message, see https://help.github.com/en/articles/about-automation-for-issues-and-pull-requests-with-query-parameters

### Add an emoji or a small illustration to make it looks less "raw"

*To be specified*

# Inspiration

- Github

![image](https://user-images.githubusercontent.com/1556356/53481059-b7789700-3a7c-11e9-9372-820ebd5e0c24.png)

- Hootsuite

![image](https://user-images.githubusercontent.com/1556356/53481093-c3fcef80-3a7c-11e9-9659-43dbafd94165.png)

- Twingly

![image](https://user-images.githubusercontent.com/1556356/53481128-d8d98300-3a7c-11e9-8247-3c6703a8b0cd.png)

**Comment by xdamman** [comment]
A good illustration like that or a gif might be nice. 

We used to have Travolta for our 404: https://github.com/opencollective/opencollective-website/blob/master/frontend/src/public/images/404.gif

Maybe the community can suggest some cool ideas! :-)

**Comment by znarf** [comment]
Let's try to not have a 4.94MB gif this time :-D

**Comment by cuiki** [comment]
This is very nice issue description. Thank you!

Should we account in this issue for 404 (non-existent URL) and server maintenance screens in addition to the error (500's) screen as well?

**Comment by Betree** [comment]
@cuiki We could, but the 404 looks less problematic to me - the error is clear and there's a call to action:

![image](https://user-images.githubusercontent.com/1556356/53490920-35e13300-3a95-11e9-80c4-22a40cc09bc9.png)

**Comment by Betree** [comment]
Here is a first skeleton I came up with:

![image](https://user-images.githubusercontent.com/1556356/53549373-50b6b480-3b34-11e9-88f6-dee963706cb0.png)

![image](https://user-images.githubusercontent.com/1556356/53549408-61ffc100-3b34-11e9-90de-4291288c49e5.png)

---

- I think it needs some more explanations, a `Why did this happen` section
- Should we display this "Error details" in non-dev environment?

**Comment by piamancini** [comment]
in the previous frontend we used to have this: https://media.giphy.com/media/3nZRJP0BBMP28/giphy.gif <3

**Comment by Betree** [comment]
The new version introduced in https://github.com/opencollective/opencollective-frontend/pull/1467 seems good enough to me. Let's follow up in future issues if we think we should still improve it.
