### ISSUE TITLE
Host dashboard new filter: ready to pay

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1767]
The open source collective has a lot of approved expenses in collectives that don't have enough funds. 
It would be great to have a new filter "ready to pay" to only show expenses that are approved and that are "ready to pay" because there are enough funds in their collective.

**Comment by alannallama** [comment]
This filter is not working. There are expenses ready to pay (if I look at "approved"), but if I look at "ready to pay" it says "no expenses".

**Comment by alannallama** [comment]
@xdamman @Betree any chance we can get this working? I'm really looking forward to using it.
