### ISSUE TITLE
Improve workflow for automatic/manual verification of new OSC Collectives

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1768]
As the host admin of the Open Source Collective, I get an email whenever a new Collective applies to join. There are a couple issues.

* It's not clear if the user has come through the workflow where the system verifies that they are a legit core contributor of the Collective they are representing, or if they have gone through the create Collective flow without verification. This is important because we risk allowing an unverified user to claim a Collective they don't have a right to claim.
* The email doesn't show if the Collective was already automatically approved, or if I need to manually approve them from the email link - the email includes a big "approve" button so it looks like action needs to be taken. But checking some of them, it seems they are actually already approved. I don't want to receive these emails if there's no action required. But if a Collective needs manual approval, I need to be notified.

**Comment by alannallama** [comment]
@znarf @Betree - is there a workaround that would let me see Collective applications to Open Source Collective that have *not* already been automatically approved? Because right now, it's not feasible for me to check each email notification manually (the vast majority are already auto-approved), which means that no one gets back to Collectives that have not been automatically approved to manually verify the Collective or suggest a different host.

**Comment by Betree** [comment]
I don't see any, but creating a very simple page that list all pending applications with "Approve" / "Decline" buttons should take no time. @alannallama would that work for you?

**Comment by alannallama** [comment]
Yes, that would be great. So it would only show the ones that aren't
automatically approved, right?

--
Alanna Irving
hello@alanna.space
https://alanna.space

**Comment by Betree** [comment]
@alannallama Yes, it will only show the ones that are not approved yet.

I've made a first version but I saw that we don't have a `rejectCollective` function yet. Do you often reject collective's application? If you do, what's the process? What information do you need to make the decision?

Current state:
![image](https://user-images.githubusercontent.com/1556356/56582299-38fd2900-65d7-11e9-809a-414b9f08e399.png)

**Comment by alannallama** [comment]
@Betree we don't reject Collectives currently. We just only accept them if they meet the host criteria, and otherwise take no action. I think for this MVP version we can leave that as-is.

In the future, it might be worth building a reject function, especially if we can add a message explaining why the Collective was not accepted, and what they can do now (e.g. apply to another host and how to do that). Currently I fulfil this function by writing the applicant an email. It's OK for the time being as the volume is not high.

**Comment by Betree** [comment]
Thanks for the details, I'll ship it this week
