### ISSUE TITLE
Support for paid events

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#177]
From [Impact.tech's collective](https://opencollective.com/impacttech):

> The issue we are faced with at the moment is we want to have our ticket sales flow through Open Collective, but tickets are registered on other sites (meetup, eventbrite). What happens is we need to allow people to register a ticket for free and then try to convince them to go to our Open Collective and pay for the ticket or become a member. Once people have the registered ticket they think they are done (no matter how many times/places we tell them they are not) and very few go on to pay for the ticket on Open Collective.
> Do you have any plans to allow for both the registration for an event and the payment happen on Open Collective? It would greatly help us and I would imagine other groups. Also, do let us know if you have some tips to improve this process in the meantime.

**Comment by xdamman** [comment]
This is a tentative to outline the MVP for supporting events.
There are quite a few moving pieces.

# Routes

- `/:collective/events`
- `/:collective/events/YYYY-MM-DD-:eventSlug`
- `/:collective/events/YYYY-MM-DD-:eventSlug/register`
- `/:collective/events/YYYY-MM-DD-:eventSlug/participants`

## Event page

e.g. `/impacttech/events/2016-07-22-meetup`

This page should show the info of the event and make it easy to register and pay.

**event.name**
event.startDate - event.endDate, event.locationName, event.locationCity
event.description

List of tickets available:
- Early bird (30% off) : $10 (expired) [register]
- Regular ticket: $15 [register]
- Members: free [login/become a member]

List of confirmed participants:
- avatar, name, bio

## Register page

In the first version, the [register] button from the event page can directly open the Stripe modal, then it would redirect to the component to enter the name, description and avatar of the participant (unless we recognize the email address)

\[+ Add to Calendar] 
(nice to have)

# DB schema

## Events table


id | GroupId | slug | name | description | locationName   | locationCity | locationUrl | startDate | endDate 
---|---------|------|------|-------------|----------------|--------------|-------------|-----------|---------
1  | 1 | meetup | 3rd meetup | all about the impact of CRISPR-CAS9 | Galvanize | SF | http://... | 2016-08-01 19:00:00 | 2016-08-01 22:30:00
2 | 1 | conference | 
3 | 1 | festival |
4 | 1 | other | 

- We could also add a `longDescription`

## Tiers table

id | slug | name | description | amount | presets | interval | range | EventId | GroupId | createdAt | expiresAt |
---|------|------|-------------|--------|---------|----------|-------|---------|---------|-----------|-----------|
1  | earlybird | Early bird | 30% off | $10 | -| one-time |[10,10]| 1       | 1       | 2016-07-10 18:00:00 | 2016-07-20 19:00:00
2  | ticket | Regular Ticket | - | $15 | - | one-time | [15,15] | 1 | 1 | 2016-07-10 18:00:00 | 2016-08-01 19:00:00
2  | member | Members Ticket | - | $0 | - | one-time | [15,15] | 1 | 1 | 2016-07-10 18:00:00 | 2016-08-01 19:00:00
3  | silversponsorevent | Silver Sponsor | Your logo on our slides | $250 | - | one-time |
4  | silversponsoryearly| Silver Sponsor for the year | Your logo at all of our meetups for a year | $2,500 | - | one-time | [2500,2500] | NULL | 1 | 2016-07-10 18:00:00 | NULL
5  | backer | Backer | Become a backer | - | [2,5,10,20] | monthly | [2,20000] | NULL | 1 | 2016-07-10 18:00:00 | -
6  | member | Member | Become a member | $10 | - | monthly | [10,10] | NULL | 1 | 2016-07-10 18:00:00 | -

Notes: 
- `slug` should only be unique for a same (GroupId, EventId).
- there is two times `member` as a slug: 
  - once to become a member of the collective (GroupId = 1, EventId = null)
  - once to define the price to register to the event for the members (GroupId = 1, EventId = 1)
  
Questions:
- How can a sponsor register for free or at a discounted price?
We should consider sponsors as backers as well. We can do that using the `range` (which is used to defined the tier of a user based on the total amount of money donated).
In the future we could define a number of "free tickets" or discount per tier, but that's a lot more complexity.

**Comment by asood123** [comment]
Looks good to me. Like the thorough backend and frontend design.

**Comment by erickrico** [comment]
Event page sketch v.1

### Header
i plan to do something very similar to our current one, but change the CTA btn to a drop down so they can pick a tier, pay and get the tickets faster

### Guests
All confirmed guests to the event follows user through the page this can be scrolled

### Event topics
All thing related to the event, schedule, speakers

### Location
Map and pictures of the venue

### Get ticket
explains more in depth what each "tier" represents, 1 time ticket, requiring ticket, etc 

### Opencollective
Explains what oc is and invites users to go to the discover page 

### sketch 
![slack_for_ios_upload_1024](https://cloud.githubusercontent.com/assets/18429104/17489232/adcb5ed0-5d62-11e6-8583-a1c01d6c5b48.jpg)

**Comment by erickrico** [comment]
![event](https://cloud.githubusercontent.com/assets/18429104/17537472/8045dc14-5e62-11e6-84a5-5fd3c36942af.png)

**Comment by xdamman** [comment]
Looking great! Can you do the responsive version?

Also for sake of simplicity, for the first version we will list all the tiers in one list (so not a two step process for silver/gold sponsors for example).

How will it work for a member only tier? 
Should we add a "login or become a member" button somewhere? How do you envision that?

Also, can you design the step after the Stripe modal? We can probably reuse the current component for after you become a member?

**Comment by xdamman** [comment]
@erickrico can you add the new design you did here?

**Comment by xdamman** [comment]
I've started the frontend for this on https://github.com/OpenCollective/frontend using [create-react-app](https://github.com/facebookincubator/create-react-app ).
@asood123 is taking care of the backend using [GraphQL](http://graphql.org)

**Comment by erickrico** [comment]
![event page guest](https://cloud.githubusercontent.com/assets/18429104/21703154/a05abaa0-d375-11e6-83e6-ce4320021aae.png)
![event page guest phone](https://cloud.githubusercontent.com/assets/18429104/21703156/a06ade26-d375-11e6-8907-5b45f6c16cbd.png)
![iphone 7](https://cloud.githubusercontent.com/assets/18429104/21703155/a069a4c0-d375-11e6-8d05-17c642f55c18.png)

**Comment by piamancini** [comment]
events is deployed.

**Comment by Nadine21** [comment]
Hi, 
This is a great feature - Thank you!
Adding to it, is it possible to:
- easy: change the communication from donation to payment - since thisis a payment for a ticket
- time consuming: collect extra information about the people: for example in an education event for children - name of the child, age, ...
- more time consuming: customize the confirmation message  (to be done when creating the event)

**Comment by alannallama** [comment]
@Betree @cuiki will the new tiers design have the option to Collect extra information as @Nadine21 described above? We get this request a lot from Collectives that want to, for example, give a tshirt or sticker for giving to a certain tier, then need to collect the contributor's postal address. See #1798

**Comment by Betree** [comment]
@alannallama Collecting extra info is a larger issue that goes in https://github.com/opencollective/opencollective/projects/6, the new tier page will not change how we handle things here. We should create an issue if that's something that we want to implement.

@Nadine21 I agree that our wording about tickets should always be "Payment", "Donation". Can you specify where you saw "Donation" instead of "Payment" so we can change it?

@Nadine21 Regarding the custom confirmation message, can you tell us more about which one you want to change? You can already change the message displayed when ordering a ticket by changing the ticket's description (see below), is that what you're looking for?

![Preview](https://user-images.githubusercontent.com/1556356/54291886-8edcbb00-45ad-11e9-9cfb-02c4cc228fa5.png)
