### ISSUE TITLE
Host dashboard: keep current filter after paying out an expense

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1770]
When we filter expenses by approved or ready, after we mark an expense as paid (or pay one with paypal), the list of expenses is being refreshed but the current filter is lost (despite still being active in the interface).

This is very annoying for @piamancini and @alannallama who have to go through a lot of expenses for the open source collective.

I took a look at it but I couldn't find an obvious fix. 

Interestingly enough, rejecting an expense doesn't cause the same behavior. So it's something about marking an expense as paid. The difference is that we have to refetch the balance of the collective. So maybe it's linked to that.

**Comment by Betree** [comment]
@xdamman I think this is a duplicate of https://github.com/opencollective/opencollective/issues/1500. I added what I found on the issue.

**Comment by xdamman** [comment]
Ah ok cool, closing this one then.
