### ISSUE TITLE
"Refill Balance" button does not work

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1775]
When I click "refill balance" to refresh the Paypal preapproval key, it says "processing" for a second, then nothing happens.

**Comment by piamancini** [comment]
this has been fixed already. Outstanding issue is the balance which is a separate issue.

**Comment by alannallama** [comment]
The refill balance button is not working again. Same behavior.

**Comment by alannallama** [comment]
OK now it's suddenly working again... no idea why.

**Comment by znarf** [comment]
@alannallama Still working?

**Comment by alannallama** [comment]
Yes still working. I'll close this now and reopen if it happens again. Thanks!
