### ISSUE TITLE
Frontend: Build failure with Next.js 8

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1776]
When upgrading to Next.js 8, the build is regularly failing in our CI environment.

```
> next build dist

Creating an optimized production build ...

> Using external babel configuration
> Location: "/home/circleci/project/.babelrc"
internal/child_process.js:372
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:372:11)
    at spawn (child_process.js:559:9)
    at Object.fork (child_process.js:113:10)
    at fork (/home/circleci/project/node_modules/next/node_modules/worker-farm/lib/fork.js:12:35)
    at Farm.startChild (/home/circleci/project/node_modules/next/node_modules/worker-farm/lib/farm.js:106:16)
    at Farm.processQueue (/home/circleci/project/node_modules/next/node_modules/worker-farm/lib/farm.js:279:10)
    at Farm.<anonymous> (/home/circleci/project/node_modules/next/node_modules/worker-farm/lib/farm.js:97:21)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
```

Sample failure in CI: https://circleci.com/gh/opencollective/opencollective-frontend/8756

Issue in our frontend repository: https://github.com/opencollective/opencollective-frontend/pull/1442

Issue in next.js repository: https://github.com/zeit/next.js/issues/6353

We need a reliable fix that address the root cause of this issue, so we can upgrade to Next.js 8.

**Comment by znarf** [comment]
A $300 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $300 when the Pull Request is reviewed, accepted and merged. [More info](https://github.com/opencollective/opencollective-frontend/blob/master/BOUNTY.md).

**Comment by znarf** [comment]
Looks like this was fixed upstream. @ijjk do you want to claim the bounty?

**Comment by ijjk** [comment]
@znarf I think it would be good to transfer the bounty to another issue so someone else has a chance to get it.

**Comment by timneutkens** [comment]
@znarf Hey 👋 The Next.js team at ZEIT (which @ijjk is part of) would like to donate the bounty to https://opencollective.com/wwcode if that's possible.

**Comment by znarf** [comment]
@ijjk @timneutkens Thank you! We'll think about the best way to do that and will notify here when it's done.

**Comment by timneutkens** [comment]
@znarf Thanks! 💯

**Comment by znarf** [comment]
@ijjk @timneutkens To proceed, we would like to give you a Gift Card. You will be free to give the whole amount to https://opencollective.com/wwcode, and you will be credited for that. For Zeit to be credited (see sample screenshot), the person donating will need to be an admin (Core Contributor) of the Zeit organization on https://opencollective.com/zeit.

![image (2)](https://user-images.githubusercontent.com/806/54812903-8f9bde00-4c8c-11e9-88a0-378f71e9a93d.png)

**Comment by timneutkens** [comment]
@znarf Sounds good to me! Is it already applied to the account or do you need details for sending the gift card? In that case you can find me on https://twitter.com/timneutkens / https://spectrum.chat/users/timneutkens

**Comment by znarf** [comment]
@timneutkens Great, I will PM you.
