### ISSUE TITLE
Update API to json2csv version 4

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1777]
We have a policy to try to use the latest version of our dependencies in all repositories.

In the API, we're currently using the version 3 of json2csv and the upgrade to version 4 has breaking changes.

- Greenkeeper PR:
  https://github.com/opencollective/opencollective-api/pull/1713
- Latest branch from Greenkeeper (rebased):
  https://github.com/opencollective/opencollective-api/tree/greenkeeper/json2csv-4.3.5
- Sample failure in CI:
  https://circleci.com/gh/opencollective/opencollective-api/9310

We want to:
- upgrade the package
- adapt the code everywhere it's used
- add a few tests to cover that for the future

**Comment by znarf** [comment]
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](https://github.com/opencollective/opencollective-frontend/blob/master/BOUNTY.md).

**Comment by eloyekunle** [comment]
I will like to work on this issue.

**Comment by znarf** [comment]
@leonardohof Are you progressing on this issue. Is it ok for @eloyekunle to take over?

**Comment by leonardohof** [comment]
Ok. I had some issues with prettier in my local environment.

**Comment by znarf** [comment]
The bounty was successfully claimed by @eloyekunle. Good job!

https://opencollective.com/engineering/expenses/7132
