### ISSUE TITLE
add an editable billing field for organizations in their profile

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1780]
## User story 
As as sponsor I want to add a billing address to my profile so that I can have a proper invoice. See link below

https://twitter.com/asp_net/status/1102545977653776384

## Best solution for this problem
Include a Billing Address editable field in the profile

**Comment by Betree** [comment]
I'll look at it along with #1766

**Comment by znarf** [comment]
@Betree @piamancini isn't that fixed in https://github.com/opencollective/opencollective-frontend/pull/1344 and a duplicate of https://github.com/opencollective/opencollective/issues/1639 ?

**Comment by Betree** [comment]
Definitely, closing in favor of https://github.com/opencollective/opencollective/issues/1639.

I'll review opencollective/opencollective-frontend#1344 so we can merge it

**Comment by Betree** [comment]
@piamancini Done & deployed, see https://github.com/opencollective/opencollective/issues/1639#issuecomment-469617745
