### ISSUE TITLE
Better engage and recognize contributors

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1781]
*Disclaimer: This issue takes a lot of inspiration from the amazing job that @gatsbyjs is doing to engage and motivate its community.*

## Why

People who contribute to the code, to the design, to the translations or to the documentation are amazing. They add diversity to the way we build Open Collective and help us to improve ourselves by sharing their experiences and good practices.

We want to better recognize these people, to reward them when appropriate and to make contributing to Open Collective a pleasant experience so they'll be willing to contribute again.

## What do we want to reward

All types of contributions should be rewarded. For us, it mostly includes:
- Submitting code (features, bug fixes...etc)
- Reporting security issues
- Issues triage
- Documentation
- Design
- Translations

### 1. Invite all contributors to a Contributor team

![image](https://user-images.githubusercontent.com/1556356/53751813-6d911600-3ead-11e9-9d8c-d37b078892ee.png)

The idea is to have a common group for all people that made at least one contribution to the project in the past. Inviting people will be a public recognition of our gratitude and a way to stay in touch.

Github Teams seems the good place to do that, especially since it offers a "Discussion" page where we can start conversations or notify all past contributors about the latest news and bounties of Open Collective.

We will be able to assign people in this group to specific issues or pull requests and they will be allowed to edit labels on issues to help us with triage.

Finally, they will have the privilege to commit directly on Open Collective's repositories (except staging and master branches) which will be way more practical than having to maintain and sync a separate fork.

**Process**

- Contribution to the project gets accepted/merged
- Core contributors invite the person to the Contributors team and add a comment like this one:

> On the behalf of the Open Collective community, I want to say thank you for being here and for contributing to the project. Open Collective is built by awesome people like you.
> 
> We would like to say "thanks" by inviting you to the Open Collective organization on Github. You'll be able to label issues, review pull requests and commit directly on our repository.
> 
> If you have any questions about that, come and join us on [Slack](https://opencollective.slack.com).
> 
> Thanks again!

- On a regular basis (1/week?) we publish updates and new bounties to the team's discussion page (contributors will be notified by email).

### 2. Swags

*This part is still a draft and ideas or experiences are more than welcome here.*

The idea would be to have a store of swags (tshirts, hats, Open Collective gift cards...etc) where people can order Open Collective goodies and to provide discount and free items to contributors, based on their number of contributions.

As a reference, Gatsby is doing this: [Holy buckets! Get your Gatsby swag here!](https://store.gatsbyjs.org/)
After one contribution, they allow you to order a simple item (socks, tshirts...) for free.
After five contributions, you can get a hoodie for free.

### 3. Mentions on social networks

Making a public mention on Twitter of the work done by new contributors have three positive effects:

1. Contributor feels publicly recognized, it's good for the ego and for their professional reputation
2. It shows that people contribute and may motivate others to do the same
3. It is an opportunity to communicate about new features more often

**Comment by piamancini** [comment]
I like this. We could also invite those in Team to help us prioritize our roadmap using a simple voting tool

**Comment by alannallama** [comment]
This is a great idea. We can also make it transparent by running expenses like swag through the Collective along with payments for Bounties, etc.

**Comment by Betree** [comment]
Just added a new section: `3. Mentions on social networks`

**Comment by piamancini** [comment]
@beetree can I help here?

**Comment by Betree** [comment]
@piamancini The experiment with (1) is going well, we progressively add contributors to Github teams so it's easier for them to participate and we have a way to reach them all if needed. We don't post bounties on the discussion page yet but they usually get picked up pretty quickly so there's not a strong need for it.

I tried to use the discussion page to thanks contributors two months ago: https://github.com/orgs/opencollective/teams/translators. I think it's a good thing to do and I'm preparing another one for this month to keep track of the progress. Maybe something similar for developers/bounties would be nice to do? Kinda like a "Bounty hunters monthly leaderboard"?

For (2. Swags) it progressively slept at the bottom of my TODO and I didn't take the time to look at it yet. I'm still willing to look at that, but if anyone has suggestions, wants to take the lead or pair on this I'm open to it.

For (3. Thanks on social networks) I didn't think about it for the last contributions, I'll try to see for future issues and PRs if there are interesting situations for this.

**Comment by piamancini** [comment]
Great! 
We can take the swag out of your plate. Let us know what you have in mind and we can work something out. @alanna

**Comment by Betree** [comment]
The only part of this issue that hasn't been explored yet is the "swag store" and it deserves an issue on its own. I think @xdamman was interested to lead this topic recently?

I'm closing this one for now, I may open more specific ones in the future.

**Comment by znarf** [comment]
As a follow up, we can discuss the "Open Collective ladder" idea in our upcoming retreat.

**Comment by Betree** [comment]
@znarf Great idea
