### ISSUE TITLE
donations from a collective (with a credit card) can't be cancelled

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1782]
User made a donation from a collective to a collective in a different host using a credit card as the collective's payment method. 
See: https://opencollective.com/up-we-rise/transactions

The issue is that https://opencollective.com/up-we-rise/subscriptions is not available for collectives and so the user had no way of cancelling the donation.

We need to add a way for a collective (not USER or ORG) to manage subscriptions. 

@xdamman this is related to the 10EURO donation to Brussels Together that you need to keep reimbursing monthly.

**Comment by znarf** [comment]
This issue is not clear enough. Can that be rewritten using two user stories? Story one: what happened. Story two: what needs to be allowed.

**Comment by znarf** [comment]
Collective to Collective backed by Credit Card is now disabled. Closing.
