### ISSUE TITLE
Alphabetize the 'add funds' sources list

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1785]
## User story 
As a host admin, I want to easily add funds to a Collective and select the correct source.

## Best solution for this problem

There are other improvements that would also be nice for the add funds flow, including the ability to edit a source, get to the add funds screen from a link on the Collective page (not only the host dashboard), and having the default platform fee set to 5% (like the default host fee is already) - but displaying the source list better is a good start.

## MVP

Display the sources list in alphabetical order:

<img width="748" alt="screen shot 2019-03-05 at 4 14 32 pm" src="https://user-images.githubusercontent.com/5498878/53778654-595b2080-3f62-11e9-8cef-463facc8e4ab.png">

**Comment by alannallama** [comment]
@znarf this might be a super easy issue for a new person to pick up.

**Comment by Betree** [comment]
This will be solved by https://github.com/opencollective/opencollective-frontend/pull/2265
