### ISSUE TITLE
Contribution Flow: Review "Other" color in ContributionDetails

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1786]
In ContributionDetails, when picking "Other", it's not clear that it's active because it doesn't have a strong different color compared to when it's inactive (except a lightweight border).

![screen shot 2019-03-05 at 14 30 50](https://user-images.githubusercontent.com/806/53808757-57d62c00-3f53-11e9-9189-1cb74cce490d.png)

**Comment by znarf** [comment]
Do you have any input on that @raulgrafico @cuiki ?

**Comment by cuiki** [comment]
Hi @znarf , yes.

I had done a quick state change witch the intensity of color hues in the labels of the buttons. I made a quick video for you to see: https://tafka.d.pr/572pts

The Figma link to this particular screen is:
https://www.figma.com/file/PozXUSiYMNIkLcwKD38two/OC.COM-07-Collectives-Copy?node-id=355%3A1426

**Comment by znarf** [comment]
A $50 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

**Comment by alabobriggs** [comment]
Am from osca ph and I'll like to work on this

**Comment by josiaholatunde** [comment]
Hi, how do i locate this page ?

**Comment by josiaholatunde** [comment]
I'm Olatunde from Osca Lagos

**Comment by znarf** [comment]
@josiaholatunde this is the "Contribution Flow" https://github.com/opencollective/opencollective-api/pull/2392

**Comment by sudo-kaizen** [comment]
> Hi @znarf , yes.
> 
> I had done a quick state change witch the intensity of color hues in the labels of the buttons in addition to the outline border of the text-field. I made a quick video for you to see: https://tafka.d.pr/572pts
> 
> The Figma link to this particular screen is:
> https://www.figma.com/file/PozXUSiYMNIkLcwKD38two/OC.COM-07-Collectives-Copy?node-id=355%3A1426

Hello! 😟 I am unable to access this document

**Comment by znarf** [comment]
@cuiki Can you check the Figma link, looks it was renamed, can you share the updated one? Also, looks like Figma is not public, can you review the permissions?

**Comment by cuiki** [comment]
Hi. Yes, all files should be public. We created a few new ones to unpack complex flows (i.e. the flow to contribute is now in a separate file) and I just opened them up.

This is the file: https://www.figma.com/file/M4OD1AM4nN8kzEhnO3zILo/OC.COM-05-Collectives-%E2%86%92-Contribute?node-id=355%3A1426

I'll reconnect the example prototype that is shown up in the comments but the file is now accesible.

**Comment by javierbyte** [comment]
@znarf I can work on this, please let me know if it has not been assigned.

**Comment by someofthethings** [comment]
Seems very simple but javierbyte should work on this in preference as he was assigned before me

**Comment by javierbyte** [comment]
@znarf amazing thanks, working on it

**Comment by jzabala** [comment]
Hi @javierbyte are you still working on this issue? Anything we can help with?

**Comment by znarf** [comment]
Minimizing comments for clarity. Updating the Bounty to $100.

**Comment by millord** [comment]
I would like to solve this issue...

**Comment by znarf** [comment]
@millord you're welcome, have a try. Time limit is 1 week, so we can free the bounty for someone else in case you have trouble completing it.

**Comment by znarf** [comment]
@millord haven't heard from you after 1 week, unassigning.

**Comment by millord** [comment]
morning,

Sorry, had many technical issues.

**Comment by JoyLubega** [comment]
Hey @znarf  I am going to give it a try

**Comment by Betree** [comment]
:trophy: This issue is now completed by @JoyLubega  

To claim the **$100** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
