### ISSUE TITLE
host reports were not send for February. 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1787]
**Describe the bug**
The hosts didn't receive the monthly report again this month. Last time the issue was #1730.
 
**To Reproduce**
check the emails sent for the host reports February 2019

**Expected behavior**
receive the report on the 1st of the following month

**Comment by znarf** [comment]
@xdamman what do we need to do to make sure it's sent next month?

**Comment by znarf** [comment]
ping @xdamman (there is a priority label on that issue)

**Comment by xdamman** [comment]
I ran it manually so priority label should be dropped. It ran smoothly so not sure why it didn’t work first time. Let’s keep an eye on it for next first of the month.

**Comment by piamancini** [comment]
It's the second month in a row it happened, so there seems to be an underlying issue. It's a pain for WWCode who complained about this twice already.

**Comment by znarf** [comment]
Didn't happen last months.
