### ISSUE TITLE
Contribution Flow: Error when next step is clicked

### ISSUE THREAD

**Issue by flickz** [opencollective/opencollective#1788]
**Describe the bug**
A graphQL error occurs when trying to contribute to an organization 
```
[GraphQL error]: Message: Abstract type CollectiveInterface must resolve to an Object type at runtime for field Mutation.createCollective with value "[object SequelizeInstance:Collective]", received "null". Either the CollectiveInterface type should provide a "resolveType" function or each possible types should provide an "isTypeOf" function., Location: [object Object], Path: createCollective
```

**To Reproduce**
1. Go to ''https://opencollective.com/asyncapi"
2. Click on Contribute button.
3. Select an organization profile to contribute as.
4. Click next step

**Expected behavior**
Should take you to the next step

**Screenshots**
![screenshot from 2019-03-05 21-10-25](https://user-images.githubusercontent.com/15707013/53834420-342ed800-3f8b-11e9-8143-86035e73e59f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version 75

**Comment by znarf** [comment]
Introduced in https://github.com/opencollective/opencollective-frontend/compare/9961e2a9...7e2d686c

**Comment by flickz** [comment]
Closing this in[ #1496](https://github.com/opencollective/opencollective-frontend/pull/1496)
