### ISSUE TITLE
Make 'amount type' setting an option for all tiers

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1789]
## Update after clarification

The "membership" tier type is missing the "amount type" option, which lets users select fixed or flexible on the other tier types. There doesn't seem to be a reason to restrict this, as users can select fixed if they want a set membership amount anyway, and it's confusing for those who don't realise how it works.

---

## User story 
As a user, I want to be able to customize my donation amount in the contribution flow.

I just tried to give to a Collective, and clicked 'become a backer'. There's no option to change it to a different amount than the pre-set $2.

<img width="888" alt="screen shot 2019-03-06 at 11 29 38 am" src="https://user-images.githubusercontent.com/5498878/53842135-87dd0800-4003-11e9-8777-a32257dd2648.png">

Clicking "Or make a one time donation" is how I can actually set up a custom recurring donation amount, the opposite of what the text implies.

## Best solution for this problem

Allow users to always customize the recurring donation amount, regardless of what they clicked to enter the contribution flow.

## MVP

Change "Or make a one time donation" link to a box that looks the same as the other tiers, called "custom donation", so users know that's where to go if they want something different from the pre-set tiers.

## Metrics 

More user contributions because people can customize the amount and easily find what they want on the page.

## Documentation 

Add a section to "tiers" documentation saying that all Collectives come with a "customizable tier" as default.

**Comment by znarf** [comment]
@alannallama I think this is a misconfiguration in the tier. This is not the behavior for other collectives.

**Comment by alannallama** [comment]
Is allowing contributors to adjust a custom amount a user-defined setting when creating a tier? I'm trying to understand how this happened.

**Comment by alannallama** [comment]
@znarf I got into the Collective's tiers to check it out. Apparently the first tier is missing the "amount type" option where you can set it to allow flexible amounts. Why would this be? The tier below has this setting.

<img width="678" alt="screen shot 2019-03-06 at 10 27 51 pm" src="https://user-images.githubusercontent.com/5498878/53870515-40846500-405f-11e9-8e32-fe7d2e8b1b3e.png">

**Comment by znarf** [comment]
@alannallama  Reading the code in https://github.com/opencollective/opencollective-frontend/blob/master/src/components/EditTiers.js, I see:

```
'_amountType',
 when: tier => ['DONATION', 'TIER'].indexOf(tier.type) !== -1,
```

Which means `amountType` can only be picked if the type is `TIER` (generic tier) OR `DONATION` (gift).

**Comment by alannallama** [comment]
I suggest we make the amount type option available for all tier types. If users want it to be fixed, they can select 'fixed amount'. Collectives use tiers in so many different ways, I don't think we can assume that just because it's a "membership" tier that they don't want to have the choice.

**Comment by znarf** [comment]
Sounds good, I don't know the rationale behind the current behavior, let's check @xdamman opinion on that.

**Comment by znarf** [comment]
@alannallama Can we maybe follow up in a separated issue now that we better understand what the problem is?

**Comment by alannallama** [comment]
@znarf I edited this issue to reflect a better understanding of the situation.

**Comment by jeffin143** [comment]
@znarf are we still on this issue , does it require handling :)

**Comment by znarf** [comment]
@jeffin143 I'm not sure about this one. Maybe you can propose a PR and we'll ask for feedback there.
