### ISSUE TITLE
Account Deletion

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1793]
Specification
==========

One of the most asked feature on support. It will not be available for accounts with transactions, this one will be proposed  the "[deactivation](https://github.com/opencollective/opencollective/issues/1317)" feature.

Frontend side
-------------

Add a form to delete a collective (User or Organization)

- This should be an additional form in the "Advanced" section of `EditCollectiveForm`
- This should be using a new separated component: ie: `DeleteCollective` or together with the archive form `ArchiveOrDeleteCollectiveForm`
- The Component should use the following layout:

```
Delete this Organization|Collective|Account
-------------------------------------------

This will delete this organization|collective|individual account
and delete all related data such as: memberships, payment methods etc ...

 --------------------------------------------------------
| Delete this organization|collective|individual account |
 --------------------------------------------------------
```

- There needs to be a confirmation screen (before the action: are you sure you want to do that?)
- On success, a confirmation page is displayed. If it's a user account, the user should be logged out (delete the token).
- If deletion is not available for the account (check the property returned by the API), the interface should be disabled and it should be explained why.
- Every string in the UI should be localize.

API side
--------

1. Add a GraphQL mutation to delete an account (named a collective in the model)

When deleting an account, behind the scenes (synchronous today / async later):
- check that the authenticated user is an admin
- check that the account is available for deletion
- delete (soft delete)
  - payment methods
  - tiers
  - memberships (soft delete)
  - connected accounts (soft delete)
- if a user, delete
 - non-paid expenses
 - user entry in the the user table
- finally delete the account/collective itself (soft delete)

2. Add a GraphQL property to know if a collective is deletable.

This should check if there is any recorded transaction (Order, Transaction, Paid Expenses), and return false if that's the case.

**Comment by flickz** [comment]
Closed in [#1819](https://github.com/opencollective/opencollective-api/pull/1819) and [#1574](https://github.com/opencollective/opencollective-frontend/pull/1574).
