### ISSUE TITLE
Frequency in collective.member.created.hbs email template seems to hold no value

### ISSUE THREAD

**Issue by luceos** [opencollective/opencollective#1795]
**Describe the bug**

When a new backer joins which donates periodically, the email send to the open collective members shows that the frequency is empty:

![image](https://user-images.githubusercontent.com/504687/53965524-af120300-40f1-11e9-8bec-c581e4570821.png)

Frequency: empty
Title of order: "Monthly donation"

This confused me a lot in the past.

---

Other information doesn't seem relevant.

**Comment by piamancini** [comment]
good catch @luceos - we'll look into this.

**Comment by znarf** [comment]
I think there might be a duplicate issue filled. That is simple and should be prioritized.

**Comment by znarf** [comment]
I found the duplicate: https://github.com/opencollective/opencollective/issues/1113

**Comment by piamancini** [comment]
closing then in favor of #1113
