### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#18]
In a collective, people have different roles and different titles.
For example, you could have `core contributors`, `organizers`, `volunteers`, `contributors`, `staff`, etc.

Per @asood123's point, we should make sure we that don't create too much complexity with this. So I think it will be good to have only 3-4 different "master roles", but then people can name them how they want and subdivide them in different "tiers". 

For example, in an open source project there are core maintainers then a bunch of contributors who contribute at very different levels (some doing one pull request a year, others once a month, others once a week). Likewise, there are different backers. Some giving $1, others giving $500. We should design for that.

This could be achieved by adding a `title` column in the `UserGroups` table (which should eventually be renamed to `UserCollectives`)

E.g.:
- **ADMIN**: People who are the main organizers / leaders. They can pre-approve expenses, edit the page of the collective. Title could be "Core contributors", "Staff", "Organizers", "Founders", "Maintainers".
- **MEMBER**: People who contribute more casually to the collective. They could have a role (e.g. "Community manager", "Advisor"). They could be called "Contributor", "Member", "Staff member", "Team member", "Volunteer".
- **BACKER**: People / companies who contribute money, "supporters", "sponsors", "gold sponsors", ...
- **FOLLOWER**: Someone who just wants to follow the progress of a collective but doesn't contribute to it 

We should keep the organization of a collective as flat as possible but we also need to design for providing people different levels of contribution for which they should be acknowledged accordingly.

Here could be a way to schematize this:

| id | UserId | CollectiveId | role | title | about | createdAt | deletedAt |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 1 | 1 | 2 | ADMIN | Core Contributor | Reviewing pull requests | 2016-04-05 | NULL |
| 2 | 2 | 2 | MEMBER | Contributor | Javascript developer | 2016-4-06 | NULL |
| 3 | 3 | 2 | BACKER | Sponsor | Best place to work in SF | 2016-4-06 | NULL |

Note that the `about` column solves this issues as well: https://github.com/OpenCollective/OpenCollective/issues/9 (one-liner/bio for backers)

**Comment by piamancini** [comment]
We had a chat w @xdamman about this offline and we came up with this three categories/names 
- Contributors: people who do work 
- Backers: people who give money 
- Friends: people who are happy with staying on the loop, still haven't decided to commit. (this is a free category)

We played with the idea (for the foundation) to give members voting power based on if they work, if they back and if they bring others to the platform. A liquid democracy mechanism can be put in place, where new members are by default delegating on the person who brought them to the platform. So, even if they still don't have voting rights, they can through their weight behind the person they trust. **It's not something to do now**, but in order to do this in the future, we should start tracking now somehow how people bring other people to the collectives.

**Comment by piamancini** [comment]
Hosts should automatically be contributors.

**Comment by dahacouk** [comment]
Hello @xdamman and @piamancini, I think I've found some issues around roles so I'm posting them here. If you want me to post in another issue then feel free to direct me to do so.

Each human being should only need one login to OpenCollective. So, no matter what role I have it can all be contained in one login/profile.

AFAIK so far where this breaks is for the host role. And there are a number of reasons why sharing login details is bad for traceability if you have multiple people authorising payments. So the host role should be added to a human login/profile and not need a separate login itself.

I really like the user model used by DigitalOcean or GitHub where a user creates a team or organisation and then invites other users into them and assigns permissions. I reckon this is how OpenCollective should work too.

Yeah?

**Comment by xdamman** [comment]
@dahacouk totally agree. I'm currently working on refactoring a bunch of that stuff. I'll keep that in mind. Thanks for your input.

**Comment by dahacouk** [comment]
Ah @xdamman great stuff! If you have a model/plan document that you are working from I'd gladly take a look at it and comment. Cheers!

**Comment by patcon** [comment]
Would be rad if OC could play nice with the all-contributors spec :)
https://github.com/edgi-govdata-archiving/web-monitoring-db#contributors

**Comment by piamancini** [comment]
V2 has admins (core contributors) and contributors. A host can have several admins. 
Organizations have members and can make contributions as organizations. 
Closing this. @dahacouk if you find v2 is not solving your issue. Feel free to create a new one accordingly.
