### ISSUE TITLE
Thank you Tweets not going out

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1800]
Core contributors of opencollective.com/solidus report that they have connected their Twitter, but thank you Tweets are not going out.

> We connected our Twitter account but we are not seeing tweet being published, although we activated all the possible options. Let me attach a screenshot of the current configuration that we did on 3/4/19 so we expected our last donation ($250 from https://opencollective.com/modded-euros, happened on 3/5/19) to be published on Twitter.

<img width="843" alt="Schermata 2019-03-07 alle 09 37 43" src="https://user-images.githubusercontent.com/5498878/54057732-a0922b80-4258-11e9-8d7e-30e64a7a2cd1.png">

**Comment by znarf** [comment]
I've checked everything and could not fined anything obvious. I added some extra debugging in production, next time there is a new backer in this collective, we can check the data.

**Comment by alannallama** [comment]
I requested the user to test again

--
Alanna Irving
hello@alanna.space
https://alanna.space

**Comment by znarf** [comment]
@alannallama All they need is a new backer.

**Comment by kennyadsl** [comment]
Thanks! I'll let you know here next time there is a new backer.

**Comment by kennyadsl** [comment]
Hey there, we just had a new backer (5/9/2019) and no tweet has been sent. Here's a screenshot of our current configuration:

<img width="860" alt="Schermata 2019-05-09 alle 14 23 16" src="https://user-images.githubusercontent.com/167946/57453194-0d7c6e80-7266-11e9-8f21-3e61c201c4da.png">

Monthly stats and updates tweets work well instead.

Hope it helps to debug!

**Comment by znarf** [comment]
Cool. According to the logs, things went almost as expected:

```
{ newBacker: 
    { active: true, 
      tweet: 
       '{backerTwitterHandle} thank you so much for supporting #Solidus and its community.❤️Your {amount} donation help us keep growing!\n\n👁‍🗨Visit solidus.io or watch Solidus on GitHub to stay up to date.' }, 
   monthlyStats: 
    { active: true, 
      lastTweetId: '1123550562740514818', 
      lastTweetSentAt: '2019-05-01T11:31:43.000Z' }, 
   updatePublished: { active: true } } 
```

```
@_KarmaCreative thank you so much for supporting #Solidus and its community.❤️Your $750 donation help us keep growing! 
```

It seems, this was rejected by the Twitter API, not sure why yet.

**Comment by znarf** [comment]
@kennyadsl The tweet wen out actually: https://twitter.com/SolidusIO/status/1126460472583184384

Is there anything wrong with it?

**Comment by kennyadsl** [comment]
Sorry. The tweet starts with @ so we didn't see it in the timeline. 🤦‍♂

We'll change the content of the tweet, thanks and sorry again.
