### ISSUE TITLE
BackYouStack should be BackYourStack on the FAQ

### ISSUE THREAD

**Issue by thunderrabbit** [opencollective/opencollective#1803]
**Describe the bug**
BackYouStack should be BackYourStack on the FAQ

**To Reproduce**
1. Go to https://opencollective.com/opensourcecollective#faq
2. Scroll down to 'What Services do you offer?'
3. See BackYouStack
4. Squint eyes and think "not sure if misspelled or if stack is a verb"

**Expected behavior**
See BackYourStack

**Comment by znarf** [comment]
@thunderrabbit Thank you! Easy to miss that R. It's fixed now.
