### ISSUE TITLE
Refreshing the Onboarding Emails

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1804]
When new Collectives sign up, they get a series of emails from @piamancini to help them get started. These haven't been changed in a while and they could be better.

**[Here are the current onboarding messages](https://docs.google.com/document/d/1XXvEgMTth2oGynpRFK41fFjA2KkQnvhRKj7cR50acyw/edit?usp=sharing)**

In addition to welcoming new people and letting them know they can ask for help, the CTAs are:

* Get your first backers (read the ['10 steps' article](https://medium.com/open-collective/ten-steps-to-successful-open-source-crowdfunding-fa2b43e82687))
* Put a donate button widget on your website
* Submit an expense (even if you don't have money yet)
* Connect your Twitter to automatically thank backers
* Post an update to your backers

How could these be better? What are the top actions that actually help new Collectives get going? What do some Collectives not know that could really help them?

**Comment by piamancini** [comment]
@alannallama left a bunch of comments in the doc!

**Comment by xdamman** [comment]
Are we keeping emojis and the current look / template?
E.g.

![](https://d.pr/free/i/rbX2jk+)

**Comment by xdamman** [comment]
![](https://d.pr/free/i/OM20zZ+)

**Comment by alannallama** [comment]
@xdamman I like the emoji, personally, but ultimately it's not that important either way. If it's easier for you to leave the template the same, let's leave it for now.

Question: Should these come from @piamancini 's email as they have been, or from support@ or info@? It's more personal and friendly coming from Pia, but I think we need to process replies in the normal support queue or else it will bottleneck in Pia's inbox.

**Comment by alannallama** [comment]
@xdamman I did a round of small text edits in response to your comments, so please use the newest content.
