### ISSUE TITLE
Move /faq to the website repo (and match style)

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#181]
Move the current FAQ
https://github.com/OpenCollective/website-static/blob/master/views/faq.hbs

to a new page on the website repo (under /faq route)
And add it as a link to the top bar (instead of How It Works and Discover that I will remove now because they return 404)

**Comment by xdamman** [comment]
Fix for the top bar links: https://github.com/OpenCollective/opencollective-website/pull/358

**Comment by carlosascari** [comment]
PR merged, closing.
