### ISSUE TITLE
VAT billing details

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1812]
There are a few UX issues.

It's not clear what to do here and why we can't continue:

![](https://d.pr/free/i/v50sJq+)

I'd suggest to add a placeholder to select the country: "please select your country" or automatically populate the country based on the IP address.

I'd also remove the VAT amount next to the country in the dropdown. It will incentivize people to lie on the country.

I'd also add on the right hand sidebar the current "Billing address details" with a link for people to edit it in their organization / user profile `/edit`.

**Comment by Betree** [comment]
I agree that this is not clear enough.

I already looked at the option to populate the country from IP address and found nothing satisfying. The resolution of the address has to be done server side (the data for it is pretty heavy) and it's not straightforward to provide an unified experience between frontend routing and pre-rendered.

I'm in for the placeholder, it's a good improvement.

**Comment by xdamman** [comment]
you can use https://wtfismyip.com/json

**Comment by Betree** [comment]
I was not comfortable with using a third party API for privacy reasons but if you think that's acceptable it would be really easy to use one.

**Comment by xdamman** [comment]
It seems fine to me. What’s the privacy risk that you are worrying about
here?

**Comment by Betree** [comment]
As the request will be client side they'll have the user IP, browser, that kind of stuff. It's not private information but we're normally supposed to mention it in the privacy policy to conform to RGPD.

It's like a like button.
