### ISSUE TITLE
Disabling Recaptcha

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1818]
With the release of the new contribution flow, we're not actively using Recaptcha anymore.

We're only using it passively, adding meta data in our database. When reviewing this data (as seen in the #abuse channel), we see that it's poor and not usable by itself in production, only potentially as part of a more complex score system.

There are some downsides having Recaptcha:
- it's loading a library from Google, that is potentially spying users
- if it's blocked, it needs to be white-listed by the user
- it's adding an ugly icon, with links to Recaptcha privacy policy

For these reasons, I would like to disable Recaptcha until further notice and put it first behind a feature flag.

**Comment by Betree** [comment]
I agree with this, a feature flag to quickly enable it in case of attacks would be great but let's not bother our users (especially on mobile) with this ugly icon.

**Comment by xdamman** [comment]
Somewhat related: I'm so tired of helping google identify pedestrian paths, front windows of shops, cars, traffic lights. We should train a global open source algorithm, not a privately owned one.

**Comment by xdamman** [comment]
Talking of which... 😒

![](https://d.pr/free/i/swhTSw+)
