### ISSUE TITLE
Error while deploying on API staging with local modifications

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1820]
```
+ npm version patch
npm ERR! Git working directory not clean.
npm ERR! M README.md

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fhodierne/.npm/_logs/2019-03-18T08_59_19_872Z-debug.log
```

This is preventing a new version to be created, and potentially impact the next production deploy.

**Comment by Betree** [comment]
I'm not used to this command but reading at the docs it seems like the expected behaviour:

From: https://docs.npmjs.com/cli/version

> If run in a git repo, it will also create a version commit and tag. This behavior is controlled by git-tag-version (see below), and can be disabled on the command line by running npm --no-git-tag-version version. It will fail if the working directory is not clean, unless the -f or --force flag is set.

What is the proposal to improve the current behaviour?

**Comment by znarf** [comment]
As it's part of the `deploy.sh`, we need to make it work.

Maybe add a `git stash`before and `git stash pop`after?

**Comment by Betree** [comment]
If the goal is just to ignore local modifications then a `-f` would work

**Comment by znarf** [comment]
Sounds good.
