### ISSUE TITLE
Archive Collective: check balance before archiving

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1823]
###  Rationale

We don't want to allow administrators to archive their collective if they have a balance.

##### Frontend

Disable the archive button if the collective have a balance.  Add a sentence to explain why. Explain that the simplest way is to give the balance to another collective.
 
##### API

Test the balance before archiving. Throw an error if the balance is > 0.

**Comment by flickz** [comment]
Closed in [#1824](https://github.com/opencollective/opencollective-api/pull/1824) and [#1583](https://github.com/opencollective/opencollective-frontend/pull/1583).
