### ISSUE TITLE
Archive Collective: don't delete tiers

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1824]
## Rationale

When archiving a collective, we want users to be able to undo. And when undoing, we want the collective tiers to be as before.

### API

Don't delete tiers when archiving.

### Frontend

Make sure users can't donate to tiers when a collective is archived.

**Comment by piamancini** [comment]
Is a collective is marked as isActive=FALSE the tiers don't show up. You'll need to double check the code is setting it back to =TRUE brings back all tiers in that collective (I would guess yes) or the default ones.

**Comment by flickz** [comment]
> Don't delete tiers when archiving.

@znarf Currently we are soft deleting, we can restore soft deleted tiers by fetching them with ```{ paranoid: false }```  and setting the value of `deletedAt` to `null` .  Does this mean we shouldn't soft delete anymore?

**Comment by znarf** [comment]
From now, we should not delete tiers, and not soft delete either. We don't touch them.

But we do make sure to not display them on the frontend if the collective is archived. That should already be the case according to @piamancini.

**Comment by flickz** [comment]
Closed in [#1812](https://github.com/opencollective/opencollective-api/pull/1812).
