### ISSUE TITLE
Archive Collective: unarchive

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1826]
## User Story

When archiving a collective by mistake, users should be able to undo and unarchive the collective.

### Frontend

When editing an archived collective, there should be a button to unarchive it. It should have a similar behavior of archiving collective, but doing the opposite.

### API

Create an `unarchiveCollective` mutation (better name welcome).

**Comment by piamancini** [comment]
yes - 100%

**Comment by flickz** [comment]
Closed in [#1554](https://github.com/opencollective/opencollective-frontend/pull/1554) and [#1805](https://github.com/opencollective/opencollective-api/pull/1805).
