### ISSUE TITLE
Contribution Flow: Migrate "Complete your pledge"

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1829]
We still use the `OrderForm` on the "Complete your pledge page". As we are removing this in favor of the new contribution flow, we should move it as well then kill `OrderForm` and all its unique dependencies.

The page itself has nothing special except a "Complete your pledge" title at the top so most of the difficulty here will be to setup proper routes.

A way to handle this could be to extract all the logic to a `ContributionFlow` component that would be re-used on both pages. This component would be agnostic to routing and all the logic for fetching data and redirecting would be taken care of by the parent page.

![image](https://user-images.githubusercontent.com/1556356/54589783-ea340080-4a26-11e9-9b6a-0883f08f8210.png)

**Comment by pietgeursen** [comment]
Hey @Betree 

> that would be re-used on both pages.

What are the two pages you're referring to?

**Comment by Betree** [comment]
@pietgeursen `createOrder` and `completePledge`. It's just a proposal, so feel free to come up with any better solution you may think of :slightly_smiling_face: 

Ping me if you want to jump on a call to have a quick demo of the feature to better understand the context.

**Comment by pietgeursen** [comment]
@Betree 

> Ping me if you want to jump on a call to have a quick demo of the feature to better understand the context.

Yeah, I'm going to need help with this. I've spent an hour trying to dig through the code but I need an intro. I think you're on holiday today. Will have to be Friday or Monday your time.

**Comment by Betree** [comment]
@pietgeursen Let's find a spot on Slack :slightly_smiling_face:

**Comment by Betree** [comment]
![image](https://user-images.githubusercontent.com/1556356/58790927-9bdbda00-85f1-11e9-9875-866ce04c927b.png)

**Comment by Betree** [comment]
A good (hacky) way to test that while developing: make an order, go in the database to set the status to `PENDING`, then go to `/pledges/:id` (id=orderId).

**Comment by Betree** [comment]
@cuiki I just checked https://www.figma.com/file/M4OD1AM4nN8kzEhnO3zILo/OC.COM-05-%2F-Collectives-%E2%86%92-Contribute?node-id=0%3A8447 and did not find a design for "Complete your pledge". Would be great if we can have something here, this is the only blocker left to get rid of the old contribution flow. I can provide details if you don't remember what this is about.

**Comment by cuiki** [comment]
First, sorry for not seeing this before. Secondly, I'm on it today.
