### ISSUE TITLE
Modify CollectiveCard to show a smaller version of the card

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#183]
CollectiveCard works fine for most cases like HP or showing 2-3 collectives. 

For supercollective (with say 50 collectives), it's too much scrolling. Also, need a compact version of the card. @erickrico - can you design one for @carlosascari to implement?

**Comment by asood123** [comment]
Built supercollective using the current CollectiveCard: 
https://github.com/OpenCollective/opencollective-api/pull/502
https://github.com/OpenCollective/opencollective-website/pull/364

**Comment by carlosascari** [comment]
@asood123 I believe this issue was solved with following PR: https://github.com/OpenCollective/opencollective-website/pull/345

Can you confirm?
