### ISSUE TITLE
Link to organization subscriptions in user menu

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1831]
I am an admin of an organization and I am logged in to my profile, I click on my profile, click on subscriptions on the dropdown menu, and it takes me to piamancini/subscriptions I have no way of accessing any or my organization's subscriptions from there (or even knowing where they are). 

I then go to one of the organizations I manage, ie /airbnb and there's no link to subscriptions there, only to transactions. Dropdown menu subscriptions link still takes me to my personal profile.

It's no wonder we have so many questions in support about how to cancel subscriptions. It is not evident that they need to be airbnb/subscriptions. What's an easy way of improving this?

**Comment by znarf** [comment]
I recently discussed that with @Betree and I think this can be integrated in a redesigned profile menu.

**Comment by Betree** [comment]
Yes. As a backer of multiple collectives, I should not have to scroll to find my profile links:

![image](https://user-images.githubusercontent.com/1556356/54652237-77726600-4ab6-11e9-8530-d198a07fb7a6.png)

**Comment by piamancini** [comment]
ok. evident (or at least some!) access to subscriptions for sponsors is needed.

**Comment by znarf** [comment]
This was fixed alternatively.

- clearer user menu
- subscriptions link in organization's navigation

**Comment by Betree** [comment]
I forgot to link to the issue, this was indeed resolved by https://github.com/opencollective/opencollective-frontend/pull/1665 by adding a link in collective's menu bar:

![image](https://user-images.githubusercontent.com/1556356/56063107-af479300-5d6e-11e9-84d1-39d432f83986.png)
