### ISSUE TITLE
Remove gift cards form on static page

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1834]
On https://opencollective.com/gift-cards we show a form to "set up gift cards". It actually just sends us an email with the form values.

As we now have gift cards admin (#1512 + #1513), we want users to create the cards themselves.

**Proposal**

Replace the form by a button:

> Register now to create gift cards

![image](https://user-images.githubusercontent.com/1556356/54669230-292e8880-4af1-11e9-808f-9f74ac582fc1.png)

**Comment by znarf** [comment]
What if the user is already authenticated?

**Comment by Betree** [comment]
Good point. I'm not familiar with how static pages work so I'm not sure what are the easy options here.

I'd either show all collectives user is admin of with a button `Create gift cards for {collective}` or if it's too complicate then nothing at all.

**Comment by Betree** [comment]
Done in https://github.com/opencollective/opencollective-frontend/pull/1581
