### ISSUE TITLE
Sanitize the way we handle collective's locations

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1835]
The way we handle locations is confusing. Moreover, we don't fill the `countryISO` when creating an event which is an issue to properly apply taxes (that are based on the country).

A documentation page [has been created](https://docs.opencollective.com/help/developers/collectives-locations) to explain how we handle locations and to reflect the following changes.

- [x] Accept `countryISO` in `LocationInputType`
- [x] Export `countryISO` in `LocationType`
- [x] Deprecate `countryISO` in `CollectiveInterface`
- [x] Ensure we properly send the `countryISO` when creating an event
- [x] Try to migrate DB entries that stores the country in `address`

**Comment by xdamman** [comment]
This is great.

Ideally, we should have a separate `Addresses` table.
This would also give us more flexibility on having a delivery address, billing address, etc.
