### ISSUE TITLE
Icon arrows look wrong

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1837]
The arrow in the middle is a donation, they should all be green

![Capture d’écran 2019-03-20 à 11 26 13](https://user-images.githubusercontent.com/3671070/54686116-ed92bf00-4aee-11e9-9704-94aed054922f.png)

These are all expenses, they should all be red 

![Capture d’écran 2019-03-20 à 11 25 22](https://user-images.githubusercontent.com/3671070/54686154-03a07f80-4aef-11e9-83ba-cfe694fae524.png)

**Comment by znarf** [comment]
I can't reproduce.  http://opencollective.com/material-ui http://opencollective.com/material-ui/transactions

**Comment by znarf** [comment]
Likely duplicate with: https://github.com/opencollective/opencollective/issues/1392

**Comment by znarf** [comment]
Closing as duplicate with https://github.com/opencollective/opencollective/issues/1392
