### ISSUE TITLE
Webhooks - Custom URLs and Zapier

### ISSUE THREAD

**Issue by eloyekunle** [opencollective/opencollective#1839]
## User story 
As a collective owner, I can configure notification webhooks to custom URLs or Zapier so that I can process events as they occur.

## MVP

1. Add a new `Webhooks` option to the `Edit Collective` page, which is linked to a new `EditWebhooks` component.
2. The `EditWebhooks` component will display a list of all webhooks currently configured for custom URLs and a button to add a new Webhook.
3. The `Add Webhook` button will open a form asking for a custom URL and a selection input for all events to send to the URL. An information section below the form will provide some help and also link to a documentation page for Webhooks.
4. The `EditWebhooks` component will have a button to "Configure Zapier Integration" which will open Zapier in a new tab.
5. Zapier integration requires `Subscribe` and `Unsubscribe` endpoints. We'll extend the API with these endpoints. The `Subscribe` endpoint accepts:

    - Target URL (Unique, generated by Zapier)
    - Event
6. We need to define the best authentication method for Zapier, which can be via Basic Authentication, Session Auth, API Keys etc.

Ref: opencollective/opencollective#328

**Comment by znarf** [comment]
What events do we want to support in this first version?

How should the data be modeled? I suggest to align on our GraphQL v2 objects.

Authentication? We have a support for API Keys in our model (created per user), that should be reused and adapted.

**Comment by xdamman** [comment]
As a start, I'd focus on those events in the following priority (based on usefulness for integrating with other services)
- new transaction (DEBIT/CREDIT)
- new backer
- new order
- new expense
- status update on order (PENDING -> PAID) or on expense (PENDING -> APPROVED/REJECTED -> PAID)

**Comment by Betree** [comment]
I'd add "new update" (news) if it's not too complicated.

As a core-contributor, I'd like my updates to be posted on social networks, chat channels...etc

![image](https://user-images.githubusercontent.com/1556356/54749321-7afc0f00-4bd4-11e9-8002-1cea65d457d0.png)

**Comment by znarf** [comment]
@eloyekunle do you have everything you need to start?

**Comment by eloyekunle** [comment]
@znarf 
Yes I do. I have started working on the feature.

**Comment by ghuntley** [comment]
Rad. Can't wait for this to ship.

**Comment by eloyekunle** [comment]
In order to start configuring the Zapier triggers, the [API pull request](https://github.com/opencollective/opencollective-api/pull/1854) needs to be reviewed and merged first.

**Comment by Betree** [comment]
Most of this issue is now implemented, the rest (The EditWebhooks component will have a button to "Configure Zapier Integration" which will open Zapier in a new tab.) is being tracked in https://github.com/opencollective/opencollective/projects/20

**Comment by ghuntley** [comment]
omg omg omg
