### ISSUE TITLE
Redirect /about

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1840]
Google still references /about so we should write a redirect to go to https://docs.opencollective.com/help/about

**Comment by znarf** [comment]
That should be implemented in the Cloudflare Workers:
https://github.com/opencollective/opencollective-workers/blob/master/main.js

We don't have that redirect pattern yet, good to introduce.

**Comment by znarf** [comment]
Done.

https://github.com/opencollective/opencollective-workers/commit/460e48bd4f0d9c23563708169708992751e4b684
