### ISSUE TITLE
Check Connected Accounts (Twitter, GitHub)

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1845]
## Connecting

- [X] It's currently impossible to connect a Twitter account
- [X] It's currently impossible to connect a GitHub account

## Reconnecting

- [X] It's currently impossible to reconnect a Twitter account
- [X] It's currently impossible to reconnect a GitHub account
- [x] When reconnecting Twitter, the connection date doesn't change
- [x] When reconnecting GitHub, the connection date doesn't change

## Parameters

- [x] For individual Users, there is an unusable "Settings" links to manage a Twitter account

![Screenshot 2019-10-04 at 17 40 54](https://user-images.githubusercontent.com/806/66220933-419d7380-e6ce-11e9-94a1-824f370aa504.png)

## Disconnecting

- [x] It's currently impossible to disconnect a Twitter account
- [x] It's currently impossible to disconnect a GitHub account

## Permissions

- [ ] Check GitHub permissions https://github.com/opencollective/opencollective/issues/1034

### Edits
- Accepted `For individual Users, there is an unusable "Settings" links to manage a Twitter account` with https://github.com/opencollective/opencollective-frontend/pull/2753
- Accepted `When reconnecting Twitter, the connection date doesn't change` and `When reconnecting GitHub, the connection date doesn't change` with https://github.com/opencollective/opencollective-frontend/pull/2737 
- Accepted `It's currently impossible to disconnect a Twitter account` and `It's currently impossible to disconnect a GitHub account` with https://github.com/opencollective/opencollective-frontend/pull/2738

**Comment by thadguidry** [comment]
I also need to disconnect my personal Twitter (accidentally added) from our Org page.  https://opencollective.com/openrefine/edit/connected-accounts

**Comment by piamancini** [comment]
@thadguidry, connecting your org one should disconnect your personal one. Do you have one? Otherwise we should disconnect you manually. let us know please

**Comment by thadguidry** [comment]
@piamancini This is resolved for me now. The Org page has its own Twitter connected.  And My Profile page has my personal Twitter connected.

**Comment by maddhruv** [comment]
Closing!
As discussion for the `GitHub Permissions` still continues at https://github.com/opencollective/opencollective/issues/1034
