### ISSUE TITLE
adding contributors to the collective page is not showing them on the front page

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1846]
**Describe the bug**
Collective admin adds contributors to their collective, they get the notification but they don't show up on the interface. 

**To Reproduce**
look at the added members on these collectives vs those that are showing up. 

https://opencollective.com/wwcodeindianapolis
https://opencollective.com/wwcodestlouis
https://opencollective.com/wwcodebogota

**Expected behavior**
Being able to show a collective's contributors without giving them admin rights

**Comment by xdamman** [comment]
Test Member User is a "Contributor" and is showing up here: https://opencollective.com/testcollective#team

And I see one core contributor and two simple contributors showing up on the first url of wwcode:
![](https://d.pr/free/i/85cK7r+)

So I'm not sure what the issue here.

**Comment by piamancini** [comment]
hmmm this was not the case last week. I'll find out more

**Comment by piamancini** [comment]
From wwcode: "Yes they are showing up now, thanks Pia. They weren't originally showing. "
So closing this since it solved itself out.
