### ISSUE TITLE
Tabs in Gift Card admin are non functional

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1847]
**Describe the bug**

When clicking on "Redeemed" or "Pending", nothing is happening.

**Screenshots**

![Screen Shot 2019-03-22 at 16 55 04](https://user-images.githubusercontent.com/806/54835921-6d718280-4cc3-11e9-9c05-463002bf024a.png)

**Comment by Betree** [comment]
Works as expected on local/staging. May be an issue specific to `opencollectiveinc`

![Peek 25-03-2019 16-20](https://user-images.githubusercontent.com/1556356/54931784-f8e45100-4f19-11e9-8546-c3bbcb65d962.gif)

**Comment by znarf** [comment]
Will check

**Comment by Betree** [comment]
Current status: I tried to reproduce on Ubuntu 18.04 for `opencollectiveinc` with both Firefox 66.0.1 and Chromium 73.0.3683.75, using both François and Pia's accounts and wan't able to reproduce it.

**Comment by znarf** [comment]
Can't reproduce anymore. Closing.
