### ISSUE TITLE
Make it easier to contact Collectives

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1849]
## Context
We get quite a few emails to support@opencollective.com from confused people trying to contact a specific Collective. They are sometimes developers with a technical question about a FOSS project, or a potential sponsor, etc. It's not clear enough how to get in touch with a Collective's core contributors.

## User story 
As a user, sponsor, contributor, or interested developer, I want to be able to directly contact the core contributors of a Collective from their page.

## Best solution for this problem
A contact button or form on every Collective page that connects to info@collectivename.opencollective.com, which goes to the Collective's core contributors. 

## Metrics 
Fewer support requests meant for Collectives coming to Open Collective Support

## Documentation 
Add a section to the Collectives > Communication section in the docs about how people can contact you from your page.

**Comment by alannallama** [comment]
Adding to this: we also get confused people trying to reach admins of other hosts. Whatever solution we create for contacting Collectives directly should also be implemented for contacting hosts. Even as an Open Collective team member, I often find it difficult to know who to contact for specific host issues.

**Comment by alanna** [comment]
I am bumping this again because I still don't think the contact button in the new Collective page is obvious enough. Instead of hiding among the other menu items, it should be a big button in a highlight color. This is one of the top reasons people contact support and a big unnecessary wall between Collectives and potential sponsors.

![Screen Shot 2019-07-03 at 2 24 24 PM](https://user-images.githubusercontent.com/5498878/60558877-d4acd180-9d9e-11e9-9dca-a1fdb220d98f.png)

@Betree @cuiki please address this before finishing the new Collective page.

**Comment by Betree** [comment]
I've also reported multiple times that having `Contact` in the NavBar was confusing because it's not a nav link, it's an external link. I actually miss clicked it multiple times trying to scroll the page so my intuition is that users will be confused.

@xdamman also gave a feedback I agreed on, with the `Share` button not being necessary on this page (so we could just replace it by Contact).

I'm all for this but the decision is up to @opencollective/design, waiting for their reply.

**Comment by cuiki** [comment]
Hi guys, I would not do it as a CTA like in Alanna's example. Contacting the Collective is not the main action we want people to do and this will send that message.

We do agree on moving the **Contact** link to the right hand side in the same style as the **Get Updates** and **Share** buttons. The action will be to try and move the **Share** button to the area below the collective name and move the **Contact** link into a button on the right side.

@raulgrafico is on this.

**Comment by xdamman** [comment]
if contact is (for now) a mailto link to an email address, why not putting it visually along side the website url of the collective?

**Comment by alanna** [comment]
This is fixed in NCP
