### ISSUE TITLE
Need a title "Related collectives" + css fix

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#185]
![](https://cl.ly/3e1X3c3h1x3P/Screen%20Shot%202016-07-22%20at%204.53.45%20PM.png)

Also, it's not centered on iPhone 6S plus.

**Comment by asood123** [comment]
title fix: https://github.com/OpenCollective/opencollective-website/pull/362

**Comment by asood123** [comment]
@carlosascari can you fix the centering pls?
