### ISSUE TITLE
Q2 - Priorities

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1850]
# Q2 Priorities Proposal

### Open Collective Pro (top/tier)

Open Collective Pro is a tier designed for individual users of the platform who want a better experience (Octobox model). During our last retreat we discussed how we can start fleshing this out. The tier would be $7 per month and it would give individuals access to enhanced features. These are the first two.

Invoices on the fly
Invoices via email 
Open Collective Core badge

### Supporting Collectives’ Outreach / Visibility

Growing the long(ish) tail: 
actions directed at supporting their ability to outreach (webhooks/zapier) 
visibility (GitHub badges/scaling collective bot)
Fundraising (Maintainer.io collaboration

### Growing / Supporting Open Collective’s core contributor ecosystem
_this are ongoing tasks - I am adding them here to make sure we prioritise them_

Manage and support Bounty Program (François)
Create a mini pod in Brussels (Xavier)

### Redesign of Collective Page

It lost some purpose along the way. (ie. it needs to show better why they need funding)
adding communication feature 
(stretch goal: groundwork for job board)

### Experimental / collaborations (not driven by us) - Not a HP but if there’s pull we should ensure they can build for OC
Tythe
Bbidali.com

**Comment by piamancini** [comment]
Also look here https://github.com/opencollective/opencollective/issues/1851

**Comment by alanna** [comment]
Superseded by current strategic focus as agreed at team sprint
