### ISSUE TITLE
Sponsor logos not clearly visible

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1853]
**Describe the bug**
Due to transparency and background colors, sponsor logo's are hard to read on some pages.

<img width="918" alt="Screen Shot 2019-03-25 at 2 33 05 PM" src="https://user-images.githubusercontent.com/5498878/54889759-1827b200-4f0b-11e9-9502-1729e234ea7a.png">

**Expected behavior**
Transparency should be reduced for all Collectives, so they look more like Webpack's page:

<img width="865" alt="Screen Shot 2019-03-25 at 2 35 03 PM" src="https://user-images.githubusercontent.com/5498878/54889787-3f7e7f00-4f0b-11e9-863e-9e77801d342e.png">

**Comment by znarf** [comment]
@xdamman I think you touched that recently, what do you think?

**Comment by Betree** [comment]
As a simple fix, the following css applied on images:

```css
filter: drop-shadow(-1px 0px 0px grey);
```

Would turn...

![staging opencollective com_opensource (1)](https://user-images.githubusercontent.com/1556356/54937724-3c908800-4f25-11e9-9e56-415b0fd30e6f.png)

Into...

![staging opencollective com_opensource](https://user-images.githubusercontent.com/1556356/54937727-3d291e80-4f25-11e9-806c-3300e6d3455d.png)

**Comment by xdamman** [comment]
Yes I touched this a month ago because the previous white was also causing issues, see #1748 
Not sure what is the best way to handle this to make it work for all.
In the meantime, I like @Betree's quick fix.

**Comment by alannallama** [comment]
The logos are still looking pretty bad and hard to read. This seems small but it's actually super important to sponsors that their logos show up well.

@cuiki do you have any advice?

More examples:

<img width="770" alt="Screen Shot 2019-04-16 at 2 55 17 PM" src="https://user-images.githubusercontent.com/5498878/56178882-f5933f80-6057-11e9-8dea-602d638f8546.png">

<img width="763" alt="Screen Shot 2019-04-16 at 2 55 28 PM" src="https://user-images.githubusercontent.com/5498878/56178884-f88e3000-6057-11e9-952c-a4c3f53a16cb.png">

**Comment by cuiki** [comment]
Hi @alannallama, this won't get properly fixed until the users replace their logos (or fix them ourselves) with squared versions on a solid background. The new designs pushes for this pattern.

However, during the demo call on Friday we mentioned that @xdamman, @znarf or @Betree would try to bring the background cover into the bg of these new squared containers to avoid this issue while users progressively update their own logos.

**Comment by znarf** [comment]
@cuiki What about today?

**Comment by cuiki** [comment]
You mean taking a stab at this today?

**Comment by alannallama** [comment]
@cuiki OK I understand. If there's anything we can do as a quick fix now, I think we should. And I hope this issue can be properly fixed in the new Collective page design. In terms of issues that the people who bring the most money care about, this is high on the list. I'd like to see how sponsors are featured be revamped in the new design. They are always super concerned about it and contact support frequently.

**Comment by yellowwoods12** [comment]
@alanna @znarf @cuiki @Betree I think a possible solution to the right opacity of an image could be if we check the RGB values of the container component or the background cover and accordingly set the opacity.
Tell me if this could be one approach?

**Comment by Betree** [comment]
@yellowwoods12 It would work, that's a good approach. However it adds some complexity that we probably want to avoid right now because we're totally re-designing this page (see https://github.com/opencollective/opencollective/issues/1951).

**Comment by alanna** [comment]
Fixed in NCP
