### ISSUE TITLE
Redesign Modal Component 

### ISSUE THREAD

**Issue by flickz** [opencollective/opencollective#1854]
Currently we have a `Modal` component mostly used for action confirmation, we'll like to redesign the modal component. Below is the current modal:

![Screenshot from 2019-03-11 14-50-08](https://user-images.githubusercontent.com/15707013/54899460-2dcbb600-4ed0-11e9-960d-795b530b1bfb.png)

A redesign should look like below:
![Screenshot from 2019-03-25 07-38-01](https://user-images.githubusercontent.com/15707013/54899777-3d97ca00-4ed1-11e9-9e25-789e1011a266.png)

Design - https://www.figma.com/file/9Iq3vBOmZ2EuOacXEYD5yK/DS07-%2F-UI-%2F-Atoms-%2F-Organisms?node-id=574%3A9

### Todo:
- Edit [`Modal.js`](https://github.com/opencollective/opencollective-frontend/blob/master/src/components/Modal.js) to meet the new design, make sure it works in isolation and changes doesn't break existing component using it.
- Add it to Styleguide

**Comment by znarf** [comment]
@flickz what is the status?

**Comment by flickz** [comment]
Incomplete, requires few modifications and test. I'll do that this week.
