### ISSUE TITLE
Unexpected error when creating a collective

### ISSUE THREAD

**Issue by v-sing** [opencollective/opencollective#1856]
# Describe the bug
*A clear and concise description of what the bug is.*

# To Reproduce

# Screenshots
*If applicable, add screenshots to help explain your problem.*

# Device
- OS: Win32
- Browser: `5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36`

# Context

:warning: PLEASE REMOVE ANY PERSONAL INFORMATION BELOW :warning:

**URL**: https://opencollective.com/create

**Stacktrace**:
```

```

**Comment by Betree** [comment]
Hello @v-sing, thanks for opening an issue. Can you edit it to provide more information like steps to reproduce?

**Comment by Betree** [comment]
Missing details and steps to reproduce. Will re-open if more data is provided
