### ISSUE TITLE
Which Open Source projects should be on Open Collective?

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1864]
A lot of Open Source projects provide tons of value, but have not yet set up a way for backers and sponsors to give financially. What projects do you use, or know of, that aren't on here but should be?

I reach out to project maintainers about their financial support situation, to see if Open Collective might help. While it's not for everyone, in some cases I can answer questions and provide support and they find it's a good fit. But it's hard to know about all the awesome projects out there, so I want ideas from you!

**Comment by Betree** [comment]
All the projects hosted by [SPI](http://www.spi-inc.org/projects/) which is a fiscal host taking donations for many great open-source projects. Would be awesome for SPI to become a host on Open Collective and to have all these join OC:

  - Postgres
  - Archlinux
  - Debian
  - LibreOffice
  - FFMPEG

**Comment by Betree** [comment]
Also I would love to support the job done by the Elixir language community. The quality of the libraries and documentations available for this language is incredibly high and it's used by companies for this reason, so it would be a good opportunity to reach new sponsors.

For information we already have a quite popular Elixir library called "Nerves Project" and another library called "Witchcraft" on Open Collective.

Others projects I'd love to be able support:

- [The language itself](https://github.com/elixir-lang/elixir)
- [Phoenix (web framework)](https://phoenixframework.org/)
- [Ecto](https://github.com/elixir-ecto/ecto)
- [Poison](https://github.com/devinus/poison)
- [Guardian](https://github.com/ueberauth/guardian)
- [ComeOnIn](https://github.com/riverrun/comeonin)
- [Jason](https://github.com/michalmuskala/jason)

**Comment by alannallama** [comment]
I reached out to SPI - we'll see what happens!

**Comment by gusaus** [comment]
OpenProducer collective is actively trying to onboard projects in verticals such as music and community/public media. 

Projects:
* LibreTime
  * https://libretime.org/
  * https://github.com/LibreTime/libretime
* MIXXX
  * https://www.mixxx.org/
  * https://github.com/mixxxdj/mixxx
* Audacity
  * https://www.audacityteam.org/
  * https://github.com/audacity/audacity
* Rivendell
  * https://www.paravelsystems.com/rivendell
  * https://github.com/ElvishArtisan/rivendell
* Open Broadcaster Software (OBS)
  * https://obsproject.com/
  * https://github.com/obsproject
  * https://opencollective.com/obsproject
* Azuracast
  * https://www.azuracast.com/
  * https://github.com/AzuraCast
  * https://opencollective.com/azuracast

While some are already on Open Collective, many don't have the capacity to actively work on sustaining their project. Improved outreach tools and functionality will certainly help https://github.com/opencollective/opencollective/issues/1869, but ideally we'd be able to onboard more people and organizations who are already doing outreach, fundraising, marketing, training, project management in a specific community or vertical. 

The [collaboration between Open Collective and @RichardLitt](https://www.burntfen.com/2019-03-18/improving-open-source-with-documentation-and-funding-maintainer-mountaineer-and-open-collective) is a big step in the right direction. Possibly we can extend this by providing guides and documentation for onboarding verticals and forming community based teams. https://github.com/opencollective/documentation/issues/2#issuecomment-415519216

**Comment by alannallama** [comment]
@Betree - yes please post on https://elixirforum.com. Give me the link and I'll come along and comment too if that's helpful. I will reach out directly to Nerves Project and Witchcraft to get their thoughts about more Elixir Collectives forming. Do you think it would be good if I contacted those other projects directly too?

@gusaus - great ideas! Is it OK if I go ahead and reach out to those projects directly, or do you already have active conversations going on with them? I agree we need to provide better tools (we're working on it) but I think it could still be good to get them on board now. It's free and easy to get them set up, and then they can activate their Collectives when the time is right.

**Comment by gusaus** [comment]
> Is it OK if I go ahead and reach out to those projects directly, or do you already have active conversations going on with them?

The only project on the list I've been actively trying to [onboard is LibreTime](https://discourse.libretime.org/t/opencollective-to-help-sustain-the-project-and-community/84). We also have some folks representing projects and organizations in the #communitymedia channel on https://opencollective.slack.com/

I think active onboarding from Open Collective team leads within vertical channels could really help!

**Comment by alannallama** [comment]
@gusaus I reached out to LibreTime, Mixxx, and Audacity, just offering to have a conversation. We'll see what happens.

**Comment by Betree** [comment]
@alannallama Here is an extract of all the pledges collectives on the platform:

| Project                    | Website                                      | Number of pledges | Amount |
|----------------------------|----------------------------------------------|-------------------|--------|
| [sandstorm](https://opencollective.com/sandstorm)                  | https://sandstorm.online/                    |      3            | $600   |
| [moment](https://opencollective.com/moment)                     | https://github.com/moment                    |      2            | $110   |
| [cloudpickle](https://opencollective.com/cloudpickle)                | https://github.com/cloudpipe/cloudpickle     |      1            | $100   |
| [cyph-old](https://opencollective.com/cyph-old)                | https://github.com/cyph/cyph                 |      1            | $100   |
| [exercism](https://opencollective.com/exercism)                   | https://github.com/exercism                  |      1            | $100   |
| [openmv](https://opencollective.com/openmv)                     | https://github.com/openmv/openmv             |      1            | $100   |
| [breeze](https://opencollective.com/breeze)                     | https://github.com/Breeze                    |      1            | $50    |
| [axios](https://opencollective.com/axios)                      | https://github.com/axios                     |      1            | $50    |
| [prettier](https://opencollective.com/prettier)                   | https://github.com/prettier                  |      1            | $50    |
| [razerdp](https://opencollective.com/razerdp)                    | https://github.com/razerdp/BasePopup         |      1            | $50    |
| [gimp](https://opencollective.com/gimp)                       | https://github.com/GNOME/gimp                |      2            | $30    |
| [linux](https://opencollective.com/linux)                      | https://github.com/torvalds/linux            |      1            | $30    |
| [anki](https://opencollective.com/anki)                       | https://github.com/dae/anki                  |      1            | $25    |
| [openstreetmap](https://opencollective.com/openstreetmap)              | https://github.com/openstreetmap             |      1            | $25    |
| [scikit-learn](https://opencollective.com/scikit-learn )              | https://github.com/scikit-learn              |      1            | $25    |
| [zsh](https://opencollective.com/zsh)                        | https://github.com/robbyrussell/oh-my-zsh    |      2            | $22    |
| [lodash](https://opencollective.com/lodash)                     | https://github.com/lodash                    |      2            | $15    |
| [cppinsights](https://opencollective.com/pateron)                    | https://github.com/andreasfertig/cppinsights |      2            | $10    |
| [janrywang/redux-callbag](https://opencollective.com/janrywang/redux-callbag)    | https://github.com/janryWang/redux-callbag   |      2            | $10    |
| [bluebird](https://opencollective.com/bluebird)                   | https://github.com/petkaantonov/bluebird     |      1            | $10    |
| [octobercms](https://opencollective.com/octobercms)                 | https://github.com/octobercms/october        |      1            | $10    |
| [vlc](https://opencollective.com/vlc)                        | https://github.com/videolan/vlc              |      1            | $10    |
| [elixir](https://opencollective.com/elixir)                     | https://github.com/elixir-lang/elixir        |      1            | $5     |
| [express](https://opencollective.com/express)                    | https://github.com/expressjs                 |      1            | $5     |
| [flameshot](https://opencollective.com/flameshot)                  | https://github.com/lupoDharkael/flameshot    |      1            | $5     |
| [jasminebdd](https://opencollective.com/jasminebdd)                 | https://github.com/jasmine/jasmine           |      1            | $5     |
| [libreoffice](https://opencollective.com/libreoffice)                | https://github.com/LibreOffice/core          |      1            | $5     |
| [peek](https://opencollective.com/peek)                       | https://github.com/phw/peek                  |      1            | $5     |

**Comment by Betree** [comment]
Also open-source projects that are free when self-hosted but that offer a commercial service where they host an instance for you.

Would be interesting to see if they're open to combine the two models like Octobox does: a commercial service where the money goes to the company AND donations where the money goes to the community (for example to have bounties).

I can think of:
- https://nextcloud.com/
- https://zulipchat.com
- https://mattermost.com/
- https://matrix.org
- https://matomo.org/
- https://www.discourse.org/
- https://gitlab.com/gitlab-org/gitlab-ce/

**Comment by alannallama** [comment]
@gusaus - FYI I had a detailed back and forth with someone on the Audacity core team. They aren't going to join Open Collective right now but they will keep it in mind for the future.

@Betree thank you! I will follow those up.

**Comment by gusaus** [comment]
@alannallama Thanks for reaching out. As mentioned in https://github.com/opencollective/opencollective/issues/1864#issuecomment-477392802, even projects not signed up could benefit from other projects, groups, or orgs who are. For instance, integrating Audacity or a creating a tutorial on "How to Record Radio Shows with Audacity" could be source material for complimentary projects like https://opencollective.com/obsproject or https://opencollective.com/azuracast

**Comment by gusaus** [comment]
There are also large CMS projects and communities like Wordpress and Drupal on Open Collective. 

https://opencollective.com/search?q=wordpress
https://make.wordpress.org/community/2019/03/01/using-open-collective-to-manage-money-for-do_action-charity-hackathons-and-intro-to-os-workshops/

https://opencollective.com/search?q=drupal
https://www.jrockowitz.com/blog/drupal-is-frustrating
https://events.drupal.org/seattle2019/bofs/open-collective

Within these are hundreds of projects, meetups, organizations, and individuals that could use Open Collective to sustain their own projects and potentially Open Collective. 

For these, it's probably best to team up with groups, initiatives and individuals already embedded in these communites.

**Comment by gusaus** [comment]
The following projects and communites provide tools that Open Collective and many other projects could use (if not already) for outreach, sustaining, and documentation. 

* CiviCRM
  * https://github.com/civicrm
  * https://civicrm.org/
  * https://civicrm.org/make-it-happen
* Read the Docs / Write the Docs
  * https://github.com/rtfd
  * https://readthedocs.org/
  * http://www.writethedocs.org/
* GitBook
  * https://github.com/GitbookIO
  * https://www.gitbook.com/

**Comment by xfischer** [comment]
Hi ! I'm the co owner of https://github.com/GeoJSON-Net.
We need funds to take time to get things up to date.

**Comment by gusaus** [comment]
> I reached out to LibreTime, Mixxx, and Audacity, just offering to have a conversation. We'll see what happens.

@alannallama Here's some additional ideas and discussions on the LibreTime side - 
https://github.com/LibreTime/libretime/issues/795#issuecomment-480952129
https://discourse.libretime.org/t/opencollective-to-help-sustain-the-project-and-community/84/23?u=gusaus

**Comment by gusaus** [comment]
If we're looking to expand our outreach to organizations and services that support open source project, there's a pretty great list here:

https://github.com/velikanov/opensource-candies

Thanks @SlvrEagle23 for sharing that resource!

**Comment by gusaus** [comment]
> The following projects and communites provide tools that Open Collective and many other projects could use (if not already) for outreach, sustaining, and documentation.
> 
> * CiviCRM
>   
>   * https://github.com/civicrm
>   * https://civicrm.org/
>   * https://civicrm.org/make-it-happen

Along with being a great case study for sustaining OSS, [this post via CiviCRM](https://civicrm.org/blog/michaelmcandrew/paths-to-sustainability) provides a some pretty good reasons why CiviCRM would be a great addition to the Open Collective platform and community.   

> Open Collectives make it easy to collect money, issue invoices, administer expenses, and so on. They can also help with the legal side of things: local chapters can act as hosts for collectives. For example Open Collective UK is a community interest company that could support a UK based collective. 
> 
> Granted, CiviCRM does a great job on many of the workflows mentioned above: collecting money, organising events and so on. The good news is that both systems are open source and there is lots of potential for collaboration, though that's a topic for another post.

**Comment by BenJam** [comment]
is there any reason that *all* open source projects can't be on open collective? As in, there could be an OC page for everything with the 'make a pledge' action topmost for collectives without an owner?

**Comment by piamancini** [comment]
@benjam no reason, and the feature to pledge to a collective is built. The original intent was to use it for that.

**Comment by gusaus** [comment]
That sounds super useful - so you're talking about making this more prominent? https://opencollective.com/pledges/new

Are there examples of a 'pledged collective'? 

Also...is there any way to pledge for Open Source projects/orgs not on Github or with less than 100 stars?

Seems like getting around those requirements would allow orgs and individuals to back projects within large CMS communities like Drupal and WordPress https://github.com/opencollective/opencollective/issues/1864#issuecomment-479364335

**Comment by Betree** [comment]
@gusaus https://github.com/opencollective/opencollective/issues/1864#issuecomment-477509992 has a list of pledged collectives (though it's not up to date).

**Comment by alanna** [comment]
We have followed up on the suggestions here. Thanks everyone!
