### ISSUE TITLE
Edits not being reflected for Collectives

### ISSUE THREAD

**Issue by jaskirat2000** [opencollective/opencollective#1870]
**Describe the bug**
When we tries to make some edits in the collective, it does not get reflected immediately or sometimes don't get reflected. I was trying to add budget goals in the collective and when I clicked on "Save" button it showed me that it got saved but on the main collective page the changes did not get reflected.

**To Reproduce**
1. Go to ' Add goals and add a budget goal'
2. Click on 'save button'
3. Return to  'main collective page '

**Expected behavior**
Changes did not get reflected.

**Desktop (please complete the following information):**
 - OS: [ Windows ]
 - Browser [ chrome]
 - Version [ 22.0]

**Comment by Betree** [comment]
This issue has been seen in different forms many times in the past when editing tiers, description...

It has been a source of frustration for many users, we should prioritize it.

**Comment by Betree** [comment]
@znarf Any idea on the best way to tackle this one? Should we ping Cloudflare's workers API to ask for the cache to be invalidated when we make an edit?

**Comment by znarf** [comment]
@Betree that's not related to workers, but yes, invalidating the cache could do the trick.

**Comment by znarf** [comment]
https://api.cloudflare.com/#zone-purge-files-by-url

We just need to have a Cloudflare config set in the environment, and then do a single HTTP post.

**Comment by Betree** [comment]
So the cloudflare cache is part of the issue and solving it will ensure we always get the data when we refresh the page.

However to really solve this issue we also need to refresh the Appollo's cache when creating updates, goals...etc.
