### ISSUE TITLE
Unable to Zero Collective

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1871]
Related to #1073 

Collectives need to zero their balance in order to change Hosts or shut down and deactivate. The system rounds amounts in some places, making this impossible. We often end up with a Collective having a few cents left and getting stuck. There should be an option to pay/transfer 100% of the balance, or the system should stop rounding and show them the actual exact total.

**Comment by Betree** [comment]
Linked to #1524 

@znarf Do you think we should re-allow float numbers in amount input to avoid these two issues? As the step payment is after the step details in the contribution flow, the only alternatives I can imagine is to show, on step payment, a confirm like:

> The balance left on this payment method is very low, we need to round your donation to `$1.42` for it to be valid. Do you agree?
>
> [ Yes, pay $1.42 ] ............ [ No, I'll use another payment method ]
>

**Comment by znarf** [comment]
This is not easy. Good reason to allow again float amounts.

**Comment by alannallama** [comment]
Collectives really don't care about the very small amount that is left in the balance, so maybe we could just delete it? Can there just be an option when trying to transfer or expense out all the money to select "full balance" or "zero your balance" and then the system can do the math behind the scenes? Like, they can put in $50 and if there's another 36 cents, that can just be deleted. Or how about this option for host admins only, so if we know they want it zeroed we can just delete the balance with a click?

**Comment by Betree** [comment]
@alannallama Whatever we do it has to be clear to the user where the difference go. We cannot delete amounts.

But yes, either:

1. We offer the user to empty the payment method's balance (see https://github.com/opencollective/opencollective/issues/1871#issuecomment-476876943)

2. Or we allow float amounts for all orders.

I prefer (1) because it will only impact the users that need it and because we probably don't want to end up with people making multiple $0.01 donations.

**Comment by znarf** [comment]
@Betree even if we implement 1) I think it will still be confusing for users to not be able to put the precise amount at the "Contribute Details" step. So, I would still do 2)

And if we do 2), do we still need 1)? Potentially yes, it's also useful when I initially set I want to give $10 and then there is not enough funds: "Do you want to give the full balance $8.99" instead?

So, let's do both?

**Comment by alannallama** [comment]
@znarf this is already fixed with the new feature, right?

**Comment by znarf** [comment]
@alannallama yes.

Maybe we also want to follow up and reopen the discussion on donating float amounts.
