### ISSUE TITLE
GraphQL fails to reconciliate cache

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1872]
Multiple times when accessing an URL directly, we got an "Unexpected Error" page with to error message in logs. This probably mean that `data` or `data.Collective` is null.

Note that the data initially loads (SSR works) but errors pop as soon as page gets rehydrated. 

**Steps to reproduce**

Try to access one of the following page directly:
- `/{collective}/transactions`
- `/{collective}/edit`

![opencollective-frontend-ylmjhsdtns now sh_betree_transactions](https://user-images.githubusercontent.com/1556356/55068829-ff420c80-5082-11e9-85c8-0ed2469adf86.png)

**Comment by Betree** [comment]
Maybe related to https://github.com/apollographql/react-apollo/issues/2114

**Comment by Betree** [comment]
Putting `priority` back on this issue as a user faced it today (https://github.com/opencollective/opencollective/issues/1891)

I followed the investigation since last time but https://github.com/apollographql/react-apollo/issues/2114 is still the privileged candidate.

The bug translate to Apollo removing the `data` from collective `props` at some point. As this has been seen on different pages recently it is possible that we face a regression from Apollo library.

It's hard to investigate because the bug happens randomly.

**Comment by Betree** [comment]
The following video from @davojta clearly demonstrate the issue: page loads the error pop after page re-hydratation: https://www.dropbox.com/s/krcb6kuomf1sqm2/Screen%20Recording%202019-04-03%20at%2011.12.16%20AM.mov?dl=0

**Comment by znarf** [comment]
@Betree should we downgrade apollo to an older version?

**Comment by Betree** [comment]
@znarf I'll try locally to see if it helps

**Comment by Betree** [comment]
Nay also be related to https://github.com/apollographql/react-apollo/issues/1314

**Comment by Betree** [comment]
Tried:
- Setting an id on `location`
- Changing the fetchPolicy to `network-only` and `no-cache`

**Comment by Betree** [comment]
Removing `priority` as a fix has just been deployed. However I'll keep this open to track down the issue in Apollo, that's a serious bug that shouldn't be ignored.

**Comment by mac-s-g** [comment]
@Betree has the fix been released?

**Comment by Betree** [comment]
It has, I deployed https://github.com/opencollective/opencollective-frontend/pull/1625 on 5th April at 9AM. @mac-s-g what was the URL when you faced this issue?

**Comment by Betree** [comment]
My experience tracking this issue in various places so far is that Apollo randomly strips the data when one of the field in sub-queries or mutations are missing an `id` field.

**Comment by Betree** [comment]
Haven't this this issue in a while, looks like Apollo updates  + enforcing `id` field did the job. If it ever happen again in the future we should be able to solve it case by case.
