### ISSUE TITLE
API: Upgrade `sequelize` to latest version

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1873]
We have a policy to try to use the latest version of our dependencies in all repositories.

In the API, we're currently using Sequelize version 4 and the upgrade to version 5 has breaking changes.

- Current Branch with Sequelize 5:
   https://github.com/opencollective/opencollective-api/tree/greenkeeper/sequelize-5.1.0
- PR with Sequelize 5:
   https://github.com/opencollective/opencollective-api/pull/1788
- Sample failure on CI:
   https://circleci.com/gh/opencollective/opencollective-api/10675

We want to:

- [x] upgrade the package `sequelize` >= 5.2.1
- [x] upgrade the companion `sequelize-cli` >= 5.4.0
- [x] make sure tests are passing
  
Here are the things we already did or needs to be looked at:

- [x] fork `sequelize-temporal` and switch to our fork (`sequelize-historical`)
        https://github.com/opencollective/opencollective-api/commit/f3cfee64d13f33aca11daf0057a065a5fb556641
- [x] remove operatorsAliases config
        https://github.com/opencollective/opencollective-api/commit/924a2eafc1f105f6d5e351e8b15563541d1c84c3
- [x] use the imported `Op` from `sequelize`instead of the other way
        https://github.com/opencollective/opencollective-api/commit/48e466ed581c1ba8223ea70015501d579930eb1b

A lot of tests are breaking and it's not yet clear why.

**Comment by eloyekunle** [comment]
I'd like to work on this.

**Comment by eloyekunle** [comment]
@znarf 

On this line: https://github.com/opencollective/opencollective-api/blob/156a8e62be62b80a64c3231978791176ed44504a/server/models/Transaction.js#L408, `hostCurrencyFxRate` is going to be a FLOAT, which means the multiplication of `netAmountInCollectiveCurrency` and `hostCurrencyFxRate` will return `amountInHostCurrency` as a FLOAT.

However, the column data type is an INTEGER. Should we perform a `Math.round` operation in this case, or modify the `amountInHostCurrency` column dataType to store FLOATs?

**Comment by eloyekunle** [comment]
@znarf Fixed, tests pass now.
