### ISSUE TITLE
Document how to make an anonymous donation

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1874]
Related to #1841 

Right now, we only explain how to make an anonymous donation to new users.

![](https://d.pr/free/i/1rZIXC+)

We should also display this contextual FAQ in the contribution flow when the user already has one or multiple profiles.

**Looking to make an anonymous contribution?**
Please log out and create a new account with another email address and don't provide any personal information.

![](https://d.pr/free/i/1mi6GC+)

**Comment by alannallama** [comment]
It's already in the docs here: https://docs.opencollective.com/help/product/user-profile#using-open-collective-anonymously
