### ISSUE TITLE
Allow for anonymous/pseudonymous donations

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1875]
Related to #1841 

In the contribution flow, we get to select the identity we want to use when we make a donation.
![](https://d.pr/free/i/1mi6GC+)

We should be able to create not only an organization but also another profile. This would allow for anonymous/pseudonymous donations.

Given our architecture, I don't think that it's that complicated.
Instead of creating an organization from that interface, we can create a new Collective of type `USER`.

**Comment by alannallama** [comment]
We already encourage users to sign up with a pseudonym if they don't want to donate under their own name publicly. But we don't currently have a way for them to choose to sometimes be anon and sometimes use their name, or to link two profiles if they have an alt for anonymity. This comes up occasionally in support requests, so if we had a cleaner way to enable this, that would be great. I like @xdamman 's suggestion to just allow alt profiles that will come up in the 'contribute as' list.

**Comment by xdamman** [comment]
Deployed to production!
