### ISSUE TITLE
Open Collective Bot onboarding: configuration

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1876]
When the Open Collective Bot is installed on a given repository, it should create a PR to help users configure the bot.

The PR should add a default `.github/opencollective.yml` and prompts to edit it, adding the Open Collective slug or URL. The `.github/opencollective.yml` should contain all the possible options, commented by default, with default values explained.

Linked to this change, I would argue that most features needs to be opt-in, so users clearly configure what they want and don't want.

**Comment by vickywane** [comment]
Hello,  
I would love to work on this...

**Comment by znarf** [comment]
@vickywane Feel free to have a first look. I marked the complexity as _only_ medium, but it might require a lot of knowledge (or research to get that knowledge), such as Typescript, Probot, Git, GitHub App API. Also, the developer setup is not properly explained in the Open Collective Bot repository, so this also a challenge. Now that I think about it, I'll create a bounty for that.

**Comment by vickywane** [comment]
Yes,  I just realized that.  I forked the opencollective bot in a bid to see how it was setup and I discovered it wasn't fully documented. Also resources on building Github Apps are quite scarce.  I'll however give it a shot and possibly leave it for someone more exposed to  building Github Apps to take it up.

**Comment by znarf** [comment]
@vickywane I created this one for the developer experience: https://github.com/opencollective/opencollective/issues/1879

**Comment by vickywane** [comment]
@znarf am happy you did.  I get discouraged when trying to work on things that provide little developer experience to new collaborators.  

Seems the task there is to test it out basically

**Comment by vickywane** [comment]
Does this need to have .ts support?  

Considering the original bot was written in ts

**Comment by maticzav** [comment]
Hey @vickywane, did you by chance make any progress with this? If @znarf agrees, we should stick to TS because the benefits outweigh the learning curve significantly.

@znarf I didn't notice the initial state of the issue, could you elaborate briefly on the state of bounties and complexity?

**Comment by vickywane** [comment]
@maticzav I was working on this locally.  Am yet to create a PR hence you can go ahead in taking it up.

**Comment by twisstosin** [comment]
Is anyone still working on this? I'd like to pick it up.

**Comment by piamancini** [comment]
hi @twisstosin!  @znarf is away until next week and he is managing the bounties. He'll get back to you as soon as he can. I have no information on the state of this bounty. Thank you!

**Comment by twisstosin** [comment]
ping @znarf , just so you know I've started working on this issue.

**Comment by znarf** [comment]
@twisstosin It's a complicated one. Normally, we prefer new contributors to first solve a simple issue or do a simple contribution before moving on complex ones. See: https://docs.opencollective.com/help/developers/bounties If you already started, please share a draft PR as soon as possible and engage with us on Slack if you have questions.

**Comment by twisstosin** [comment]
Okay great, I'll create the draft PR now.

**Comment by znarf** [comment]
Would be great to guess the Open Collective slug or URL by pinging the Open Collective API. 

I just made available a GraphQL query for that.

```
{
  collective(githubHandle: "babel") {
    name
    slug
    description
  }
}
```

Or:

```
query collective($githubHandle: String) {
  collective(githubHandle: $githubHandle) {
    name
    slug
    description
  }
}
```

**Comment by znarf** [comment]
To make the bounty workflow better, we decided to introduced deadlines. In this case, for a moderately complex feature, we're expecting completion in 1 week

Also, for this specific bounty, because we want to have the feature shipped, if not done by May 31th, we will remove the bounty and work on it internally.

**Comment by znarf** [comment]
That was done.
