### ISSUE TITLE
Open Collective Bot onboarding: postinstall

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1877]
When the Open Collective Bot is installed on a given repository, if applicable (basically, if it's an npm package), it should create a PR to help users configure the `postinstall` script.

The PR should modify the `package.json` and add the following:

```
scripts {
"postinstall": "opencollective-postinstall"
}
```

```
dependencies {
"opencollective-postinstall": "^1.0.0"
}
```

If missing:

```
"collective": {
  "type": "opencollective",
  "url": "https://opencollective.com/<slug>"
}
```

Note: it's possible we don't know the Open Collective slug / URL yet, so maybe we should only issue the PR once the `.gitub/opencollective.yml` is added to the repository. Otherwise, we would have to prompt the user to edit the slug / URL, making the process more difficult.

**Comment by vickywane** [comment]
Hello.  
Can I try this out ?

**Comment by maticzav** [comment]
We could presume that the slug of the collective is the same as the name of the repository; however, that might be an overgeneralization. Perhaps checking whether any collective matches the repository name could be sufficient.

Besides that, it is crucial for updating the `package.json` file that we maintain its structure which is a challenging task by itself. `renovate` does a great job of persisting the structure through changes but the code is quite complex. We should also consider what happens with `package-lock.json`/`yarn.lock` file once we add the dependency.

I believe having a simple QA system to help users with an onboarding flow could help us encourage more users to try the bot out; however, we should discuss the capabilities of the bot.

Briefly summing up the tasks:
1. `package.json` structure perseverance,
2. `yarn.lock`/`package-lock.json` syncing,
3. on boarding QA.

**Comment by huan** [comment]
It seems that we had already implemented this feature?

Because I got a PR https://github.com/Chatie/wechaty/pull/1759 exactly match we described.

Or was that sent from our team member?

**Comment by znarf** [comment]
@huan was made by a Jessie, she's human :-)

**Comment by znarf** [comment]
Removing the bounty, we will try to achieve that differently.

**Comment by znarf** [comment]
We will not do that.
