### ISSUE TITLE
Banner for collectives with pending approval

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1878]
When creating a new collective, the collective is not necessarily immediately activated, it needs to be approved first.

While it's in this state, a banner on top of the collective should explain the status, similar to what we're doing with _archived collectives_.

## API

To enable that, we want to introduce a new flag/date on the API side to know more precisely the current status of the collective: `approvedAt`.

- `approvedAt` will be set the the current date when the collective is approved by the host or automatically approved (GitHub flow)
- `approvedAt` will be set to `NULL`when the collective change the host or is archived
- if not already, the host should be removed when the collective is archived  (member table, `hostCollectiveId` column) 
- the `approvedAt`column needs to be exposed as `isApproved` in GraphQL (similar to `isArchived`)

## Frontend

- If the collective is not archived (`isArchived=false`) and not approved (`isApproved=false`) a banner should be displayed on top of the collective page. This happens in the `Collective` component and should be similar to what is done when the collective is archived.
- The banner should not be displayed when the `collectiveCreated` banner is
- The `collectiveCreated` banner should have a different message regarding if the collective is approved or not. See: https://github.com/opencollective/opencollective/issues/2100

## Link to impacted files

- approvedAt will be set to the current date when the collective
  - is approved by the host: https://github.com/opencollective/opencollective-api/blob/master/server/graphql/v1/mutations/collectives.js#L440
  - automatically approved (GitHub flow): https://github.com/opencollective/opencollective-api/blob/master/server/graphql/v1/mutations/collectives.js#L176

- approvedAt will be set to NULL when
  - the collective change the host: https://github.com/opencollective/opencollective-api/blob/master/server/models/Collective.js#L1502
  - or is archived: https://github.com/opencollective/opencollective-api/blob/master/server/graphql/v1/mutations/collectives.js#L614

**Comment by znarf** [comment]
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md).

**Comment by Shorpee** [comment]
I'll like to work on this.

**Comment by yellowwoods12** [comment]
Hey @Shorpee, are you working on this or should I start working on it?

**Comment by znarf** [comment]
@yellowwoods12 In our bounty program, we prefer if contributors stick to 1 issue at a time. Let's finish https://github.com/opencollective/opencollective-frontend/pull/1960 first?

**Comment by yellowwoods12** [comment]
@znarf Sure. It's almost done.

**Comment by yellowwoods12** [comment]
Hi @znarf, can I start working on this issue if the last one is done?

**Comment by znarf** [comment]
Sure, let's set a time limit of one week to start.

**Comment by znarf** [comment]
@yellowwoods12 sorry, the time limit is exhausted, I can't lock this bounty longer for you.

This bounty is available to participants of the OSCA (Open Source Africa) event.

**Comment by Shedy151** [comment]
i am shedy from osca PH I will be working on this...

**Comment by EslamHiko** [comment]
@znarf can I give this issue a shot?
