### ISSUE TITLE
Open Collective Bot: developer environment

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1879]
We now have a new project in the Open Collective galaxy, the Open Collective Bot! 

https://github.com/opencollective/opencollective-bot

The documentation for developers willing to work on the bot is non existing and it's actually more tricky to test than anything else we're doing, because it's _webhook_ based and needs to be exposed to the internet. We need to provide steps to:

- git clone and yarn install (easy)
- configure the API URL (should default to staging and provide example for local API)
- how to expose local environment to the internet (ie: https://ngrok.com/)
- create a new GitHub App for development
- copy and use credentials from the GitHub App locally
- install the GitHub App on a test repository
- inspect incoming messages
- see it working!

**Comment by vickywane** [comment]
Great.  I'll do this now

**Comment by maticzav** [comment]
@vickywane could you give a brief update on the state of this issue.

**Comment by vickywane** [comment]
There is an active PR for this.  @znarf referenced it above.  
Have you gone through?

**Comment by znarf** [comment]
Removing the bounty.

Basics are covered in https://github.com/opencollective/opencollective-bot/pull/102.

We still need to make the test coverage 100%.
