### ISSUE TITLE
Use webpack

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#188]
Anything that increases our iteration speed is worth trying. Faster we learn, more likely we are to succeed. 

From what I can hear, webpack can speed up our development significantly. @mxstbr has offered to help us configure it.

**Comment by sedubois** [comment]
Just to mention it:
- besides doing realtime stuff, Meteor is supposed to handle all the config: 
https://www.meteor.com/tutorials/react/creating-an-app
- Facebook just created a zero-conf React tool: https://facebook.github.io/react/blog/2016/07/22/create-apps-with-no-configuration.html

The `create-react-app` can be "ejected", then serving as a config boilerplate generator. (I think demeteorizer might do something along those lines for meteor).

**Comment by mxstbr** [comment]
I'm actually part of the `create-react-app` core team, but that won't work for our our purposes since we'd need to eject anyway for our SSR stuff.

I like Meteor, but have never worked with it! Would that fix what we're trying to do here?

**Comment by sedubois** [comment]
I think going toward meteor should be part of a bigger intention to have real-time capabilities etc. Probably makes more sense if the software moves beyond prototype.

**Comment by asood123** [comment]
List of things before we can merge webpack (keep adding to it as we discover issues):

- [ ] CSS on desktop is showing mobile views (ex: instead of side by side donations and expenses columns, they are one below another, same with different donation boxes - should be side by side)
- [ ] Path issue. Do we need to modify everyone's path? Is there a better solution?
- [ ] Testing: Few linting errors need to be cleaned up
- [ ] Update instructions on wiki
- [ ] Test production setup. Is there a way to do it without pushing to staging?

**Comment by jhnns** [comment]
Now that we're on open collective, you should definitely do that 😉 (we can also give you support)

**Comment by asood123** [comment]
@jhnns we would love to. @datapimp got us close with https://github.com/OpenCollective/opencollective-website/pull/446. We still have a few issues to work through before merging.

**Comment by jhnns** [comment]
If you have any questions, just tag me and I'll try to give you support :)

**Comment by piamancini** [comment]
already using webpack
