### ISSUE TITLE
API: Replace `knox` library

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1880]
In the API project, we're using a library named [knox](https://github.com/Automattic/knox) to connect to S3. 

Unfortunately, this library is not maintained anymore and we need to use something else instead.

`knox` is only used in the [images](https://github.com/opencollective/opencollective-api/blob/master/server/controllers/images.js) controller, that should be a straightforward modification.

**Comment by vickywane** [comment]
I found this https://github.com/andersfugmann/aws-s3 

Would you like to go through it to see if it matches your expectations of a replacement?  

It's quite newly built and hasn't been used largely

**Comment by znarf** [comment]
@vickywane It's a library for the ocaml language, not JavaScript. For us, the default choice would be https://github.com/aws/aws-sdk-js but we're open to other libraries if they're lighter, widely used and properly maintained.

**Comment by vickywane** [comment]
Am sorry that slipped my notice

**Comment by vickywane** [comment]
I found this also;  
https://github.com/transloadit/uppy 
Can you have a look to see if it matches your requirements?

**Comment by znarf** [comment]
@vickywane we just want to upload to s3 on the server side, we don't need any browser side functionality.

**Comment by vickywane** [comment]
Alright . 
I would work with the official aws-sdk.  
I initially tried avoiding it due to the documentation and other unavailable configuration

**Comment by vickywane** [comment]
Made a PR already #1846

**Comment by brymut** [comment]
Hi @znarf @vickywane, is there any update on this issue? If it hasn't been worked out, I would like to have a go at it while I wait for my pull request to get reviewed.

**Comment by vickywane** [comment]
Hello @brymut  , i think #1939 has fixed it . You can however wait for @znarf 's confirmation

**Comment by znarf** [comment]
@brymut @JohnTitor had a try recently, but feel free to have a look. You can have a look at the failing PR first https://github.com/opencollective/opencollective-api/pull/1939

**Comment by brymut** [comment]
I had a look already at the PR, was just unsure if I should check this out & have a go or not since @JohnTitor closed their pull request. I'll have a look over the weekend and hopefully, @JohnTitor is able to confirm soon.

**Comment by brymut** [comment]
Hi @znarf, I've had some luck over at https://github.com/opencollective/opencollective-api/pull/2012. Could I please get some feedback on this when you can?

**Comment by znarf** [comment]
Thank you @brymut ! It's merged.

Thank you for working on this, your claim is already approved:
https://opencollective.com/engineering/expenses/8176
