### ISSUE TITLE
Empty collective balance

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1884]
Before archiving or deleting collectives, we are asking for an empty balance. It's however more difficult that it sounds to achieve that. Why?

- restrictions in donation amount
  - minimum amount
  - only round values accepted
- restrictions related to the host
  - can only donate to collectives with the same host

### Proposal

Add a form/button in the "Advanced" selection of "Edit collective". 

#### 1st version

Link to the Donation Flow with.
- Target Collective: the collective linked to the host
- Contribute As: the collective you want to empty
- Value: the exact remaining balance
- Payment Method: the collective balance (preselected)

#### Later version

Ability to donate to a collective of choice.

#### Alternative

A functionality in the admin interface to do the same thing.

**Comment by alannallama** [comment]
@znarf this is already done right?

**Comment by znarf** [comment]
@alannallama Yeah, this is done and active for a selection of hosts (open source, paris, brussels, europe and wwcode).
