### ISSUE TITLE
Missing opensource tag for some collectives

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1886]
## Problem

Some of the collectives from the [opensourcecollective](https://opencollective.com/opensourcecollective) are missing an `open source` tag.

The following query:
```sql
select count(id) from "Collectives" 
where "HostCollectiveId" = 11004
and not 'open source' = ANY(tags)
```

Returns 106 entries.

## Fix proposal

- [x] In https://github.com/opencollective/opencollective-api/blob/master/server/graphql/v1/mutations/collectives.js#L267 we use `opensource` instead of `open source`, we should change that
- [x] Ensure we are not using `opensource` in other places
- [ ] Migrate the `open source` tags to all collectives with host `11004` that don't have it

**Comment by piamancini** [comment]
yes please let's make sure they match. 
Let's add the 'open source' tag to all the collectives without it. The super collective relies on the 'open source' tag to bundle collectives under it.  We've already made the mistake in the past of adding 'opensource' (without the space)

**Comment by xdamman** [comment]
For the record, here is a postgres query to append the `open source` tag:
```sql
UPDATE "Collectives" SET tags = array_append(tags, 'open source')
WHERE "HostCollectiveId" = 11004
  AND NOT 'open source' = ANY(tags)
```

**Comment by Betree** [comment]
All done :heavy_check_mark:
