### ISSUE TITLE
Approve Expense email functionality broken/unexpected 

### ISSUE THREAD

**Issue by mixmix** [opencollective/opencollective#1888]
**Describe the bug**
I got an email with an expense for a collective I admin. There was a sweet "Approve" button.

I thought "oh sweet, a magic link, I won't have to sign in for this" so clicked "Approve"

And I got a page which (after some loading spinner) said "Approving expense" but then supiciously didn't progress from this. I opened the console and saw an error

![image](https://user-images.githubusercontent.com/2665886/55362715-55a5c400-5537-11e9-8df8-6b1d11fa1f29.png)

**What I would expect**

either :
- an error I can read as a user
- a prompt to log in
- my approval just works as I thought it would (because of a magic link, i.e. a token in the email link)

**Feeling**
ahh fuck, I hate signing in, I guess I'll just skip this and never bother opening those expense emails again because they're more work than I want to deal with
(harsh, but that's honestly how lazy / admin averse I am)

**To Reproduce**
see above 

**Desktop (please complete the following information):**
 - OS: kubuntu 16.04
 - Browser: firefox
 - Version: 66.0.2 (64-bit)

**Smartphone (please complete the following information):**

**Comment by znarf** [comment]
@mixmix we decided to move away from magic links in notification emails, the idea being that we should not send authentication tokens when they are not clearly expected. For instance, users could forward the email to other people in the team, giving their token. It was a nice convenience, but we moved the balance toward security.

This should have been a prompt to Sign In.

**Comment by piamancini** [comment]
Hi Mix, yep, the error is telling you to log in because your token expired. This is related to a recent deploy. The approval should work magically as expected in the future. Sorry about it! cc @znarf (token related)

**Comment by znarf** [comment]
@piamancini Have you seen my reply?

**Comment by piamancini** [comment]
I hadn't sorry! For some reason your reply wasn't synced in my Octobox (cc @benjam)
Sorry @mixmix for the confusion.

**Comment by mixmix** [comment]
Thanks all. Yeah logins and magic-links are one of the things I problems I don't have to deal with in Scuttlebutt. Maybe one of these days we'll get a Scuttlebutt extension which will enable easy sign on lots of places .... till then.... hope my browser remains signed in

**Comment by flickz** [comment]
Closed in [#1642](https://github.com/opencollective/opencollective-frontend/pull/1642)
