### ISSUE TITLE
Amount in Contribution flow url not working with floats

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1889]
https://opencollective.com/lajacqueline/pay/302.5
turns into https://opencollective.com/lajacqueline/pay/details?description=302.5
instead of https://opencollective.com/lajacqueline/pay/details?amount=302.5

**Comment by Betree** [comment]
@xdamman The URL pattern is looking for an integer

```
'/:collectiveSlug/:verb(donate|pay|contribute|order|events)/:amount(\\d+)?/:interval(month|monthly|year|yearly)?/:description?'
```

So https://opencollective.com/lajacqueline/pay/details?amount=302 works as expected. As we don't support float amounts in contribution flow, should we support this case?

**Comment by xdamman** [comment]
We should.
Especially now with VAT, the total amount of an invoice will have decimals.

**Comment by Betree** [comment]
Yes but VAT is calculated by us, collectives are not supposed to include it in their pricing.

As a temporary fix, the following URL should work:
https://opencollective.com/lajacqueline/pay?totalAmount=30250

**Comment by xdamman** [comment]
Regardless we cannot make the assumption that collectives will not want to ask for an amount with decimals.

**Comment by Betree** [comment]
That's fair, we should indeed support it. The only problem that I see is that if I remember correctly we wanted to support legacy URLs like:
1. https://opencollective.com/lajacqueline/pay/custom-description
2. https://opencollective.com/lajacqueline/pay/monthly/custom-description
3. https://opencollective.com/lajacqueline/pay/42/monthly/custom-description

The 1. and 2. are not going to play nice with having float amounts in the URL.

Maybe we can update our documentation to incentive collectives to use the format https://opencollective.com/lajacqueline/pay?totalAmount=30250 (that is already supported instead)?

**Comment by xdamman** [comment]
Well, the amount is always going to be `[0-9]+(\.[0-9])?`, so you can’t really confuse that with any description.

**Comment by xdamman** [comment]
From a user experience stand point, avoiding query parameters is much much better.
`/pay/500.50` is much much better than `/pay?totalAmount=50050`
The latter requires much more things to remember (is that totalAmount or amount or total_amount?)

**Comment by Betree** [comment]
:arrow_double_up: https://github.com/opencollective/opencollective/issues/1889#issuecomment-478936161 sound like a simple fix for this issue

**Comment by znarf** [comment]
I just tested the Amount in URL feature. It's currently buggy and should be more properly tested.

Also, in this feature, I don't think `amount` should be fixed. It should be more like a single preset, selected by default.

Donators should be absolutely free to edit the amount and the frequency.

**Comment by xdamman** [comment]
> Also, in this feature, I don't think amount should be fixed. It should be more like a single preset, selected by default.

That makes sense for `/donate/:amount`. Less so for `/pay/:amount` where you'd expect to force the user to pay that given amount. That's another good example of how we can start differentiating those different aliases to better match users' expectations (and give them more control over how they want to ask for money).

**Comment by Betree** [comment]
We need to communicate properly with collectives if we decide to do this change. For example Octobox uses: https://opencollective.com/octobox/donate?amount=10&interval=month&description=individual&redirect=https://octobox.io/opencollective to handle orders.

One problem is that we have a complex behaviour that is undocumented and relies on legacy hacks that we must support. For example being able to pass an `amount` **or** a `totalAmount` is something that we did to be retro-compatible without really knowing who use it and how. There's a good change that this is the reason for the bug in amount.

Writing proper specs and documentation for this could save us some time in the future.

**Comment by sbinlondon** [comment]
This has been fixed in the new contribution flow right? Should we close it?

**Comment by Betree** [comment]
While we do support float for amounts in URL parameters when passed as query variables, the URL https://opencollective.com/lajacqueline/pay/302.5 is not working yet (we need to update the regex of the page for that). Let's keep this issue open until we do the change.

**Comment by Betree** [comment]
We've decided to deprecate the route parameters in favor of query parameters: https://github.com/opencollective/opencollective/issues/5716.
