### ISSUE TITLE
Call for Collaboration of Open Collective with DONUT project

### ISSUE THREAD

**Issue by jaskirat2000** [opencollective/opencollective#1893]
Thanks a lot @Betree for recommending me to write an issue for this.

It would be indeed to partner Open Collective with DONUT.

## **Description of DONUT**
[Codeuino](http://www.codeuino.org) is a volunteer-driven non-profit open source Social networking organisation that provides various robust frameworks solutions which could span the entire world through building all kinds of social environments, discussion portals and collaboration platforms, giving prospectus to various other organisations, users and outreachers to use social media in a custom way.

[DONUT](https://github.com/codeuino/Social-Platform-Donut) is a major project of [Codeuino](http://www.codeuino.org) that builds social networking Kit for various organisations to build up social environment for their organisation to showcase their productivity and services for their community along with the collaboration platform to interact with one another. This project stands similar to "[Facebook](https://facebook.com)", "[Twitter](https://twitter.com)" like social medias.
This project has been built in Nodejs, mongo and ejs but shifting codebase to Vuejs now. 
Individual users and organisations can use this platform in their custom way with various color themes and integrations.

More can be seen here https://github.com/codeuino/Social-Platform-Donut

## **Collaboration with Open Collective**

Many of us handle various social handles like Facebook, Twitter, etc. Since we have seen that Facebook has a feature which help raise the funds for anything ( It is Social media).
So DONUT platform being another open Source Social Networking platform ( Different from Facebook and other social handles) comes up with many multi-integration system. We see Open Collective as a strong platform for raising funds by giving good and efficient User friendly setup at user end and we would love to integrate Open collective on our platform so that people should not find it difficult to raise funds for their projects wherever needed or leads existing ones.

Here Collaborating means that we would be developing modules ( If approved by community ) that will be integrated with the DONUT platform and then Users/communities can make their own collectives whiach are needed or raise up for existing one. Functionality will remain same for the collectives but there will be bit change of UI on DONUT platform in order to meet color scheme ,etc.

Since this project will be used by users/communities worldwide so this will help open collective to reach to more **projects/people/backers** since there will be many enthusiasts available on this platform.
So partnering will help in to work in collaboration and outreach more.

## **DONUT is not Facebook**

We can't exactly say about that DONUT is facebook. Because it has been made by taking into consideration of of-course social handles but it consists of different UI and functionality. It comes with various integrated system. The all the social medias I have seen just contain majorly as writing post, sharing and following.
But DONUT contains and help various Open source enthusiasts to raise up their projects on research under various open source experts and communities available there and use it to raise up their productivity by showcasing project. We have tag mechanism which not only restricted to "tag someone" but this helps to redirect projects.
Assume that "X" user signs up on the DONUT platform. Once the "X" user has defined all the details about himself, then he would be asked to select some tags from the tags cloud which describes him the best and here, "X" user chooses "Designer", "Nodejs" and "Html". this tells us from the description of the tags in the tags cloud that this "X" user is a "Designer" and knows languages like "Nodejs" and "Html".On pursuing further these tags get stored for him.

Now assume other user "Y", suppose "Y" user is already logged into this platform. "Y" user writes a post as project/article/blog or any other thing related to feeds on it, before he publishes, he would be asked to choose some tags from the "Tags Cloud". Suppose the "Y" user choose "Nodejs" tag from it. **Here, we see that user "X" and "Y" has "Nodejs" common in them.** So on publishing the post by user "Y", the particular project would be redirected to the "X"(because they both contain common tags), According to the tags description user "X"would be able to review the thing.

So there are many other tools too, analytical report generator, automatic posting of things to various handles ( by just setting up things once), appropriate dashboards for communities as well as individual users with management tools.

**We still have proposed many module development project in this year Google Summer of Code so hope to add more features. Check out Idea page here https://developer.jboss.org/wiki/GSoC2019Ideas#jive_content_id_Category_Codeuino**

## **Expectations from Open Collective on Collaboration**

There is no demand of users or people using open collective or developers or maintainers. Once we are done with it (If approved), you can simply outreach if wants or whatever tweet you would like. We need nothing from Open Collective to things happen but if Open collective can help in backing up a project that would be appreciable. Since we required to put funds for many things like hosting, even giving some bounties to developers as a reward, etc. **But again not a compulsion.** Here is our collective we just made 
**https://opencollective.com/donut**

**Required: Opinion of major (Core) members of Open Collective @znarf @piamancini @alannallama @xdamman @Betree @opencollective/core 
Actually why I wanted to add their opinion for making it move is that since that gonna be a big project and it will be like building so many back up modules and we will keep on reaching to some backers, tweeting about it on social and talk about it in general events and without the official approval we can't use the name of Open collective like this "We are collaborating with Open Collective or partnering with Open Collective or something like that " if that's fine then I think we are good to go. This we have suffered in past so don't wanted to make cluster of things. 

So final call to this action.**

We are partner with WOMEN WHO CODE Delhi and had received sponsorship from Digital Ocean in past. Looking forward to collaborate with Open Collective too.

**Comment by Betree** [comment]
Thanks for opening the issue @jaskirat2000, we'll review it as soon as possible

**Comment by jaskirat2000** [comment]
Looking forward to it

**Comment by jaskirat2000** [comment]
Hi @xdamman and @piamancini . I opened this issue few times back. So can you just give me a final call in "Yes" or "No" for if Open Collective can collaborate with DONut? If yes then I would love to discuss few more things further.

**Comment by Betree** [comment]
Hello @jaskirat2000 :wave: 

First of all thanks for thinking about Open Collective while you plan to integrate more services into Donut. Your proposal have been discussed and reviewed by the core team, here is our official reply:

- We can't back Donut because right now we're focused on backing the libraries we use to build Open Collective. If it was only for us, we would back all the projects on the platform - all of them are amazing :wink:!

- We'd be happy to provide documentation and guidance for open collective integration into Donut but it's hard for us to say more right now because the specific features that you want to add are still unclear.

- Saying that we are collaborating or partnering is not appropriate in this context, but feel free to say that you plan to integrate Open Collective features and to re-use our logos if needed.

I'm closing this issue, feel free to re-open it if you think this answer is incomplete or if there are some other things that you want to discuss.

**Comment by jaskirat2000** [comment]
Hi @Betree Thanks for it. I am reopening this issue because wanted to add few things.
1. Backing up this project is usually I mean with few bucks not by sponsoring $10000 etc because this can help us to give it a start for seeking donation and that too with adjoining Open Collective in DONUT.

2. Regarding features. It is not likely that we are building a new collective taking into consideration about Open Collective. No. We are just integrating Open Collective with DONUt with every same features just adding few UI like it should be displayed in appropriate windows or fit in some pages, etc. We have yet to decide more things how we can do that.

3. I stated as the words "Collaboration or partnership" because it would not be our new collective, it would just be integration and user will be redirecting from our DONUt to the Open collective which would help collectives to reach more backers for projects, also open new collectives for other newly developed projects. 
Moreover we would be giving people to raise funds for events, hackathons and other meetups related so for that it would be used OC itself.
So that's why I prefer word collaboration or partnering.

I hope this make sense. So looking forward to the team response.

**Comment by Betree** [comment]
1- We understand that but still we currently don't have any plan to officially back collectives that are not a library that we use for Open Collective.

3- We clearly understand that too but the words "partnering" and "collaborating" are not appropriate in this situation.

**Comment by jaskirat2000** [comment]
Okay thanks, no worries

**Comment by Betree** [comment]
I'm sorry that we cannot give you a more positive answer at the moment. I wish you the best for Donut!
