### ISSUE TITLE
Users expect that removing a payment method will cancel its subscriptions

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1894]
We get support requests from people who have removed their payment method (credit card), and then are surprised when the subscription continues to be charged to that card. They expected removing the payment method means the system will no longer charge anything to that card.

I am struggling to think of a case where someone would remove a credit card intentionally, and *not* want the associated subscriptions cancelled. Maybe they should just be cancelled automatically, or with a warning saying "Removing this payment method will cancel associated subscriptions".

**Comment by Betree** [comment]
Good catch, that's definitely a bug. We should display the warning and cancel the subscriptions.

**Comment by znarf** [comment]
Aren't we prevented of deleting a payment method with subscriptions attached?

**Comment by Betree** [comment]
@znarf It's a mistake I made when refactoring the payment methods edit page, the check did exist in previous version but I forgot to migrate it on the new version. Will fix that ASAP.

**Comment by Betree** [comment]
Actually my last comment is inaccurate: the way I implemented it was to only show the "Remove" button when there's no subscription:

![image](https://user-images.githubusercontent.com/1556356/55646404-65ddcd80-57db-11e9-81f7-2f60e1106ef2.png)

So I'm surprised that user was able to remove the payment method.

**Comment by Betree** [comment]
@alannallama Regarding my previous comment, can you point me to some examples where users had this issue so I can look at the data and understand what went wrong?

**Comment by alannallama** [comment]
@Betree here's one: https://opencollective.freshdesk.com/a/tickets/238

**Comment by Betree** [comment]
So I'm still not sure why users were able to click the "Remove" button on a payment method with subscriptions but for sure we need to enforce this validation on API.

Two solutions:

1. We block it and show an error message "Please cancel or update your subscriptions first" with a link to the subscriptions page to make it easier

2. We cancel all the subscriptions.

I personally prefer the first approach.

**Comment by alannallama** [comment]
If there are subscriptions attached to the card they are removing, the
options should be 1) add a new payment method, 2) change subscriptions to
another existing payment method, 3) cancel the subscriptions. I guess we
could make them manually go set that up first and just block them from
removing a card with active subscriptions, because this is a rare use case
and that's probably easier. But the ideal case would be a nice experience
where the system gave them the options they want right there.

--
Alanna Irving
hello@alanna.space
https://alanna.space
