### ISSUE TITLE
Infinite looping GraphQL request to fetch updates

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1896]
**Describe the bug**

In some circumstances, there is a GraphQL error in the 'Updates' section of the collective page. When inspecting the request, there is an infinite loo trying to fetch the resource.

**To Reproduce**

1. Go to https://opencollective.com/blogmarks

**Current Behavior

- Notice the **GraphQL error** message in the update section.
- Open the Browser network tab, notice the looping requests

**Expected behavior**

- No error
- No looping request

**Screenshots**

![Screen Shot 2019-04-03 at 16 26 15](https://user-images.githubusercontent.com/806/55486804-39844e80-562d-11e9-9db3-b4505b6622d3.png)

![Screen Shot 2019-04-03 at 16 26 36](https://user-images.githubusercontent.com/806/55486832-4608a700-562d-11e9-94f4-0212b39e6115.png)

**Comment by flickz** [comment]
@znarf I'm unable to reproduce this locally

**Comment by znarf** [comment]
Ok. I'll have a look.

**Comment by znarf** [comment]
Not reproducible anymore.
