### ISSUE TITLE
Allow multiple attachments in one expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1897]
## User story 
As a contributor, I want to upload a batch of multiple receipts in one expense, because creating a seperate expense for each one is tedious.

## Best solution for this problem
Allow multiple attachments on a single expense, with space for the amount and description per each, with a "apply to all" option if they are all the same.

## MVP
Maybe a way to duplicate an expense so all you'd need to do is upload another attachment? Seems just as hard to build as allowing multiple attachments and would be less useful.

## Metrics 
More small expenses submitted because it's easier to batch them. 

## Documentation 
Ideally the UI would make it obvious that you can add another file.

**Comment by alannallama** [comment]
@piamancini is there a reason related to accounting that we can't have multiple receipts for one expense?

**Comment by Betree** [comment]
Implemented in the new expense flow
