### ISSUE TITLE
Make sure the PDF receipt reads Invoice for Tier of type "service"

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1899]
It's important for Europe that the PDF receipt shows "Invoice" and not "Donation Receipt" when the tier is of type "service"

**Comment by znarf** [comment]
What about @alannallama's feedback?

If I remember, she said "invoice" is when a payment is required, and "receipt" after the payment was processed.

**Comment by alannallama** [comment]
If it needs to say 'invoice' for Europe, just go with this. Technically, documentation of payment already made is a receipt, but I don't think it will confuse or cause problems to say 'invoice'.

**Comment by Betree** [comment]
As an invoice can contains both donations and orders for services, the way I'm going to implement it is to only show "Donation receipt" if there are only `DONATION` tiers.
