### ISSUE TITLE
let OSS backers know they show up in github

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#19]
After making a donation through the platform, redirect/show somehow that they show up in the github repo.

**Comment by boneskull** [comment]
automate sending of PR to update `README.md`?

**Comment by asood123** [comment]
@boneskull: @xdamman came up with a clever solution so we don't have to push a new PR everytime. We originally submit a PR to show up to 30 backers. For empty slots, we show a 1px image. As they fill up, we serve the new backers automatically.

**Comment by xdamman** [comment]
The only issue is caching. It takes a couple of minutes to show up. So we can't really redirect the backer straight away. 

But we should add in the thank you note a message that says that they will show up on the github page.

**Comment by piamancini** [comment]
@xdamman are you following up on this?

**Comment by piamancini** [comment]
This is low priority now and a new issue for the action needs to be filed when we revisit.
