### ISSUE TITLE
Scary warning on host report email

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1900]
The host report this month triggered a warning in gmail:

<img width="1002" alt="Screen Shot 2019-04-04 at 2 37 16 PM" src="https://user-images.githubusercontent.com/5498878/55523808-41a0c480-56e7-11e9-91e0-22769fdd2a51.png">

If we can figure out why this is happening and fix it, we should, as it's pretty offputting.

**Comment by znarf** [comment]
Using Gmail and haven't got this warning.

**Comment by xdamman** [comment]
same

**Comment by znarf** [comment]
Closing. I don't see actionable here. Let's keep our eyes open and report it if this happens again.
