### ISSUE TITLE
Missing job for 3* tests on CI

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1901]
In https://github.com/opencollective/opencollective-frontend/pull/1574 and https://github.com/opencollective/opencollective-frontend/pull/1593 a few tests were added, all starting with `3`.

Unfortunately we don't have a job configured to run on CI so these tests never went through CircleCI.

I tried to add one, but 32- breaks (see https://dashboard.cypress.io/#/projects/yt5kwm/runs/6445/failures/d99686fe-5a80-4c19-88fa-7b3dfcddc109)

We need to:
- [ ] Fix 32-
- [ ] Add the job to .cicleci/config.yml

In the mean time I'll add a job to still run my `33-` test on CI (see https://github.com/opencollective/opencollective-frontend/pull/1620/commits/f83b6a2f273c5faf39befee6a6a5d7842ead14ec)

**Comment by znarf** [comment]
Let's rename the job and put it in the `0*`, `1*` or `2*` namespace.

**Comment by Betree** [comment]
Yep for the `33-user.changeEmail` it actually makes sense to put it in 08 next to signIn.
