### ISSUE TITLE
Image upload for updates not working in Safari

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1908]
User report: I clicked on the image button, selected the image that I wanted to add from my filesystem and was brought back to the compose window.  Unfortunately, nothing had been added.  I tried it several times with the same outcome.  This was in Safari (Version 11.1.2 for Mac).

I tested this myself in Chrome and image upload is working.

**Comment by znarf** [comment]
Just tested in Safari 12.1 and it was working.

Can someone try in Safari 11.1.2? Looks like a version that is not supported anymore https://en.wikipedia.org/wiki/Safari_version_history

**Comment by alanna** [comment]
This has not come up again
