### ISSUE TITLE
"New expense" email is showing the PayPal address even for manual payouts

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1912]
In the "New expense" email, the PayPal address is displayed even if the payout method is set to "Other".

This is a privacy issue, users asking for manual payouts doesn't expect their PayPal addresses to be shared with the collective admins.

It also creates some confusion: from seeing this email as a collective admin, I am tempted to think that user asked to be paid via PayPal.

![image](https://user-images.githubusercontent.com/1556356/55687397-cfd9ac80-596c-11e9-9f8f-789a7313c5f3.png)

## Expected behaviour

In the "New expense" email, PayPal email address must only be displayed when the user asks to be paid using PayPal.

**Comment by znarf** [comment]
Also, PayPal address is not stored on an expense basis, which can lead to further confusion.

**Comment by Betree** [comment]
So maybe we should totally strip the PayPal email, regardless of the expense's payout method. I don't see any benefit to show this in the email.

**Comment by piamancini** [comment]
@betree, let's think about this. 

The user needs to see what email they are using becasue when they add a new email it overrides the existing one recorded as their paypal email. 

And from a host admin perspective if they don't see the paypal email in the field it's hard to troubleshoot (they would need access to a view in the data base of that email)
