### ISSUE TITLE
Currency mismatch between budget balance and contribution options

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1913]
This Collective's currency is £ but their balance and budget are showing in $.

<img width="1164" alt="Screen Shot 2019-04-08 at 4 56 08 PM" src="https://user-images.githubusercontent.com/5498878/55699524-4931d780-5a1f-11e9-8b48-539e4f7e8041.png">

**Comment by Betree** [comment]
@alannallama I've manually changed the currency for P6 Community to GBP, so this should be fixed for P6 community. 

Will follow up with the root cause in https://github.com/opencollective/opencollective/issues/1914 + https://github.com/opencollective/opencollective/issues/1865
