### ISSUE TITLE
Add a button to quickly open emails inbox on login

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1915]
## User story 
When sending a confirmation email (for example to login) we can make the life of users easier by providing a button to directly open the email on their email provider's website.

## Best solution for this problem

Create a new `<OpenEmailProviderButton />` component that takes an email address and an optional email title filter.

If email provider is supported, add an `ExternalLink` wrapping a `StyledButton` with the text `Open Inbox`.

Ideally the link should filter the messages to directly show the email that we want.

For example to get login email in Gmail you can link directly to:
https://mail.google.com/mail/u/2/#advanced-search/subject=Open+Collective%3A+Login&subset=all&within=1d

![image](https://user-images.githubusercontent.com/1556356/55722289-1d562800-5a06-11e9-9e2f-94cc39cf93bd.png)

## MVP

Add the button on the login confirmation page with support for the 2 most used providers on the platform:
- GMail (~50%)
- Hotmail (~5%)

<details>
<summary>See statistics about providers</summary>

Query:
```sql


SELECT
  split_part(email,'@', 2) AS domain,
  COUNT(*) as count,
  COUNT(*) / 32000.0 * 100 as percentage
FROM
  "Users"
where
	email is not NULL
GROUP BY
  domain
ORDER BY
  COUNT(*) DESC
```

10 first results:

| domain           | count | percentage              | 
|------------------|-------|-------------------------| 
| gmail.com        | 15788 | 49.33750000000000000000 | 
| hotmail.com      | 1502  | 4.69375000000000000000  | 
| yahoo.com        | 458   | 1.43125000000000000000  | 
| outlook.com      | 407   | 1.27187500000000000000  | 
| qq.com           | 374   | 1.16875000000000000000  | 
| womenwhocode.com | 283   | 0.88437500000000000000  | 
| mygeoweb.info    | 226   | 0.70625000000000000000  | 
| protonmail.com   | 222   | 0.69375000000000000000  | 
| me.com           | 157   | 0.49062500000000000000  | 
| icloud.com       | 150   | 0.46875000000000000000  | 

</details>

## Inspiration

- Example with https://changelly.com

![image](https://user-images.githubusercontent.com/1556356/64424514-9b982280-d0a9-11e9-961d-db48242ad3a1.png)

---

**General guidelines**
- The strings must be internationalized. See [/help/developers/translations](https://docs.opencollective.com/help/developers/translations)
- Whenever it's possible we must use `styled-components` to write styles. See [OC Styleguide](https://opencollective-styleguide.now.sh/)
- Icons must be imported from the [styled-icons](http://styled-icons.js.org/) library.
- Tests written with Cypress must follow our [good practices](https://docs.opencollective.com/help/developers/testing-with-cypress) conventions.

**Comment by Betree** [comment]
No objection has been given for this feature, I don't see any danger in implementing it and it's contained and simple enough to make it a candidate for "Good first issue" to give to new contributors.

**Comment by JoyLubega** [comment]
Hey @znarf I want to give this a try

**Comment by Betree** [comment]
Hi @JoyLubega, welcome! Feel free to give it a try. Please note that there's no bounty attached to this issue.

**Comment by JoyLubega** [comment]
Hey @Betree about the Email filter, I think I have to integrate Gmail API and outlook. I beg to be advised. thanks

**Comment by Betree** [comment]
You should be able to filter by generating a URL similar to https://mail.google.com/mail/u/2/#advanced-search/subject=Open+Collective%3A+Login&amp;subset=all&amp;within=1d

Keep it as simple as you can, we shouldn't have to integrate the providers APIs. If filtering is not possible/easy to add easily then don't bother with it, a link to the inbox will be enough :slightly_smiling:

**Comment by JoyLubega** [comment]
Hey, @Betree  I am trying to push my work and It says I don't have permissions. Do I need to fork, I had just cloned.

**Comment by Betree** [comment]
Hi @JoyLubega, for your first contribution you need to fork the repository and make the PR from your fork. When your first contribution gets merged, you join the `Contributors` group and you'll be able to push directly to this repository.

**Comment by Betree** [comment]
This issue has been resolved by @JoyLubega. You've been invited to https://github.com/orgs/opencollective/teams/contributors - you can now commit directly on Open Collective's repositories (except master branches). Be welcome and let us know if there's anything we can do to help you get onboard! :tada:

**Comment by Betree** [comment]
@JoyLubega We want to introduce a monthly tweet to thank Open Collective's contributors publicly.

It's opt-in, so I need to know first if you're ok to be mentioned publicly. If you do, what's your Twitter handle?

Thanks!

**Comment by JoyLubega** [comment]
Yes am okay with that

**Comment by Betree** [comment]
@JoyLubega Cool :-) What' your Twitter handle?

**Comment by JoyLubega** [comment]
@NamuliJoy
