### ISSUE TITLE
Host admin can add funds to organizations

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1919]
## User story 
As a host admin, I want to manually add funds to an Organization, so that I can process [bulk transfers](https://docs.opencollective.com/help/backers-and-sponsors/bulk-transfers).

## Best solution for this problem
An 'add funds' option on the Organization page that only host admins can see.

I'm not sure where in the process the platform and host fees should come into it. With the current 'add funds' feature for adding to Collectives, you can put in the host and platform fee % manually. But if those fees will be charges automatically when the Org allocates them to Collectives, then we don't want to double charge them.

**Comment by piamancini** [comment]
This feature is hardcoded for my user atm (I cant' remember how we ended up here). Ideally any host admin can do this.

**Comment by alanna** [comment]
We still need this but we should solve #2311 first.

**Comment by Betree** [comment]
I'm wondering what could happen if someone malicious plays with that, especially because **any user can become a host admin** (aka we cannot trust host admins). 

Implementing this issue means that any user will be able to create a prepaid payment method for any organization out there without their consent. Do we want that? Can this be abused?

We should also be careful with what that means when we'll implement #2441: with this issue implemented, any self-hosted collective will be able to lie on its available balance so this information will not be trustable for sensitive operations anymore.

@piamancini @znarf @alanna @flickz  Can we think of other scenarios that may be considered as vulnerabilities?

**Comment by flickz** [comment]
> Implementing this issue means that any user will be able to create a prepaid payment method for any organization out there without their consent.

I didn't exactly think about the consequence like this when I opened a PR for this issue, now that I think about it, it is actually scary.  Can we have an implementation where the host admin can do this but a notification email will be sent to the root user for confirmation, the fund will never be added until the root user confirms it?

> Any self-hosted collective will be able to lie on its available balance so this information will not be trustable for sensitive operations anymore.

Can we or do we have any means of confirming the authenticity of self hosted collective balance?

**Comment by alanna** [comment]
Yeah you're right @Betree I don't think we can go ahead with this in such a simple way. Maybe something like, host admin can add funds to organization but that organization can only contribute those funds to Collectives under that host? I think it's too complicated, though.

For now let's just stick with root users can add funds to Organizations. If we get demand in the future from other host admins about this feature in the future, we can tackle it. Really, the system should have some way of tracking a balance for a host and then the host can allocate those funds to Organizations or anyone in the system, but that's a whole other idea.

**Comment by Betree** [comment]
> For now let's just stick with root users can add funds to Organizations. 

It may be safer to do that until we're ready to properly tackle it, we should keep this issue open so that host admins can +1 if they're interested in it.

**Comment by Betree** [comment]
> host admin can add funds to organization but that organization can only contribute those funds to Collectives under that host?

That's already the case, prepaid are limited to the host they are created by

**Comment by alanna** [comment]
This is done
