### ISSUE TITLE
Make archiving available for individual accounts (USER)

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1920]
When we worked on the archive feature, we decided to not make it available for individual accounts.

I don't see reasons today to not allow that.

**Comment by flickz** [comment]
@znarf What activities should be prevented from archived user account?

**Comment by znarf** [comment]
@flickz same as other types of accounts

**Comment by piamancini** [comment]
we'd have to check the userId in the expense table (expense table uses userId not collectiveId) and remove the email from the userID table.

**Comment by flickz** [comment]
@piamancini I'm not clear on this

**Comment by znarf** [comment]
Not clear for me either.

**Comment by piamancini** [comment]
Sorry: 
When you archive a USER collective you need to ensure there are no expenses filed for that user. The expense table doesn't use the collectiveID of the user, it uses the UserID of that user. 

So you'll need to check that the userID of that collectiveId doesn't pending expenses in the expense table. (you should check for paid expenses, but once the expense is PAID we generate transactions in the transaction table with the user CollectiveId) 
Pending expenses are only registered in the expense table.

The second thing that needs to be done is invalidate the email of the user in the user Table. If you just mark it as deletedAt, the system won't let the user create a new profile with that email address in the future.

**Comment by znarf** [comment]
@piamancini Are you talking about deleting or archiving? 

Archiving is for accounts that we can't delete, especially the one with orders and expenses.

**Comment by piamancini** [comment]
deleting. A user with a filed expense - pending - won't have any transactions yet. I'm assuming we are ok with deleting a pending expense?

**Comment by znarf** [comment]
This issue is about archiving not deleting. 

But we can still double check the behavior for deleting.

**Comment by alannallama** [comment]
I find the help text for these features really confusing. I am trying to add the new features in the advanced section to the docs but I can't explain them. Seems related to this to I'm posting it here @znarf 

Here's what I see:

<img width="841" alt="Screen Shot 2019-04-15 at 1 33 46 PM" src="https://user-images.githubusercontent.com/5498878/56102779-45ec9d80-5f83-11e9-87db-284abafbeb6c.png">

As an individual user, it doesn't make any sense to me that my account has a balance on it and can't be archived. Where do I see this balance? How do I get rid of it?

Also it doesn't make sense to tell users below that they can't delete but can archive their account, but then not allow them to archive it.

**Comment by znarf** [comment]
@alannallama I don't understand the non-empty balance, I'll check.

You're right for the other sentence. The second part should be optional, based on availability.
