### ISSUE TITLE
event calendar editing is funky

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1922]
@xdamman Wordpress Foundation announced they'll be scaling up their Open Collective use to create events for their community. Net Squared just announced it too. 

Can you please look into fixes  we have pending? 
(search old issues)
the admins not being translated to the events 
the thank you email being hard coded and not editable by event users. 

Also, the calendar is looking weird see screenshot.

Tagging this issue bug fix Friday - Does using that tag work for you? Seems easy since you'll be doing Fridays with the team. 

<img width="720" alt="Screen Shot 2019-04-10 at 9 40 07 AM" src="https://user-images.githubusercontent.com/3671070/55883618-a8553080-5b74-11e9-968e-0d5f7d72bce1.png">

**Comment by Betree** [comment]
Fixed by https://github.com/opencollective/opencollective-frontend/pull/1649/

**Comment by piamancini** [comment]
I think @Betree made a PR to fix the calendar issue. 
There's another issue too with the way time is displayed 
![Screen Shot 2019-04-11 at 11 52 32 AM](https://user-images.githubusercontent.com/3671070/55971924-6a2d3f00-5c50-11e9-8123-15383803cf51.png)
