### ISSUE TITLE
Clicking on French and then on English redirects to French

### ISSUE THREAD

**Issue by niccokunzmann** [opencollective/opencollective#1924]
**Describe the bug**

The link https://opencollective.com/cryptpad/contribute?language=en&set=1 redirects to https://opencollective.com/cryptpad/contribute?language=fr&set=1 for me.

**To Reproduce**
1. Go to https://opencollective.com/
2. Click on [French](https://opencollective.com/cryptpad/contribute?language=fr&set=1) in the Footer
3. The page opens in French, I can see "Connectez-vous en utilisant votre adresse email :"
4. Click on [English](https://opencollective.com/cryptpad/contribute?language=en&set=1) in the Footer
4. I see the page still opens in French "Connectez-vous en utilisant votre adresse email :"

**Expected behavior**

I would like to see the page open in English

**Screenshots**

![Screen Shot 2019-04-11 at 07 56 32](https://user-images.githubusercontent.com/564768/55933969-69d07c00-5c2f-11e9-96a2-811823b804c0.png)
![Screen Shot 2019-04-11 at 07 56 24](https://user-images.githubusercontent.com/564768/55933972-6b9a3f80-5c2f-11e9-8006-479925973c21.png)

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser FireFox Quantum Extended Support Release
 - Version 60.4.0esr (64-bit)

**Additional context**

Just visiting the Front page for the first time.

**Comment by znarf** [comment]
Effectively. I'll check what's wrong.
