### ISSUE TITLE
Translation Contribution Path not found

### ISSUE THREAD

**Issue by niccokunzmann** [opencollective/opencollective#1925]
**Describe the bug**

I would like to know how to contribute translations.

**To Reproduce**

- The footer shows text but no place where I can help translate 
  ![Screen Shot 2019-04-11 at 08 03 13](https://user-images.githubusercontent.com/564768/55934269-55d94a00-5c30-11e9-9c81-25d5dc8d9bb6.png)
- https://docs.opencollective.com/help/ only shows code contributions at the bottom but does not mention translation

**Expected behavior**

I would like to have links in these places to the translation platform:
- https://docs.opencollective.com/help/ at the bottom, listed as an equal way how to contribute
- The percentage signs should be links to the translation platform ![Screen Shot 2019-04-11 at 08 03 13](https://user-images.githubusercontent.com/564768/55934269-55d94a00-5c30-11e9-9c81-25d5dc8d9bb6.png) 

**Additional context**

I would like to contribute translations but I do not know how.

**Comment by znarf** [comment]
Good point, maybe the percentages should be linked to the translation interface.

https://crowdin.com/project/opencollective

**Comment by Betree** [comment]
Hello @nicobarretoOC! This is reflected in this page for the documentation https://docs.opencollective.com/help/about/contributing

I just pushed https://github.com/opencollective/opencollective-frontend/pull/1658 which adds the following tooltip:

![Peek 11-04-2019 16-20](https://user-images.githubusercontent.com/1556356/55965501-01a58880-5c77-11e9-8f55-4f6dad5f0fb9.gif)

I think it will solves the issue but I like @znarf's idea to add links on percentages too.

**Comment by Betree** [comment]
I also reflected the change you suggested on https://docs.opencollective.com/help/

Thanks!
