### ISSUE TITLE
GraphQL error on this page

### ISSUE THREAD

**Issue by shtefcs** [opencollective/opencollective#1926]
**Screenshots**
![](https://i.imgur.com/pg1e2Ti.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [latest]

On this page https://opencollective.com/stumptownsyndicate#about

**Comment by znarf** [comment]
Thank you for reporting that, I can confirm the issue, we're looking at it.

**Comment by flickz** [comment]
@znarf Have not been able to reproduce this locally

**Comment by znarf** [comment]
@flickz Have you looked in production?

**Comment by flickz** [comment]
@znarf  Not really but have tried to compare the same query locally, I think we might need to investigate the "Stumptown Syndicate" collective data in production database especially data fetched with`allCollectives` query

**Comment by znarf** [comment]
I see: ```{"errors":[{"message":"Cannot destructure property `dataValues` of 'undefined' or 'null'.","locations":[{"line":2,"column":3}],"path":["allCollectives"],"level":"debug"}],"data":{"allCollectives":null}}```

We should check if there is actually any collectives linked to this host.

**Comment by heyakyra** [comment]
Same error here: https://opencollective.com/resist#about

actually...same error on many pages: https://www.google.com/search?q=site%3Aopencollective.com+"graphql+error"

**Comment by flickz** [comment]
Oh Thank you @heyakyra we'll fix this asap.

**Comment by flickz** [comment]
@znarf The problem is here https://github.com/opencollective/opencollective-api/blob/master/server/lib/queries.js#L353-L363, we need to inspect the production database to find out while the `COUNT` SQL query is failing for this collective hosts.
