### ISSUE TITLE
Collective Page → Define visual language for the Hero image and Contributor's header (EPIC #1928) (EPIC#1999)

### ISSUE THREAD

**Issue by lindatalu** [opencollective/opencollective#1927]
## Best solution for this problem
We've working on ideas to come up with a subtle but clear visual language for Open Collective that strengthens the concept of unity and collaboration.

This issue is to track the progress of these explorations.

## Referenced Issues
#1928 
#1999

**Comment by cuiki** [comment]
References:

![become-a-sponsor](https://user-images.githubusercontent.com/981188/56003313-b184f100-5c8b-11e9-824e-fb6bf6357bd3.png)

![join-the-movement](https://user-images.githubusercontent.com/981188/56003347-d4170a00-5c8b-11e9-9698-61f769c49539.png)

![collective-page](https://user-images.githubusercontent.com/981188/56003379-f6108c80-5c8b-11e9-9408-009555a5f58b.png)
