### ISSUE TITLE
Personal Profile → Manage subscriptions re-design (EPIC #1930)

### ISSUE THREAD

**Issue by lindatalu** [opencollective/opencollective#1931]
## User story 
_As an individual, I can comprehensively find all of my subscriptions (donations and memberships) so that I can update the subscription amount/frequency, payment method or cancel them._

## Best solution for this problem
_In the same way we're redesigning the collective page we should take a stab at the subscriptions page as a part of a larger section revamp (#1930). There a number of small problems with this entire experience that calls for a rework._

## Ideas

- A way to bring back/reboot previously cancelled subscriptions? Somehow showing the history of my cancelled subscriptions with an option to restart it (_if available, i.e. maybe subscription was cancelled because the collective no longer exists_) might create a small opportunity to get back some of the cancelled subscriptions.

## Referenced Issues
#1930 
#1697

**Comment by cuiki** [comment]
#1930

**Comment by znarf** [comment]
@lindatalu @cuiki Please review the content of this issue.
