### ISSUE TITLE
Negative Paypal pre-approval balance

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1932]
**Describe the bug**
This shouldn't happen, right?

<img width="468" alt="Screen Shot 2019-04-12 at 6 20 42 PM" src="https://user-images.githubusercontent.com/5498878/56016304-e78ba900-5d4f-11e9-9c2d-7ff0a4af0995.png">

I refilled the balance and it appears to be working normally.

**Comment by alannallama** [comment]
After refilling, I paid a bunch of expenses and then noticed the balance went negative again.

<img width="451" alt="Screen Shot 2019-04-12 at 6 25 30 PM" src="https://user-images.githubusercontent.com/5498878/56016468-726ca380-5d50-11e9-83c0-442e5e4bdba8.png">

**Comment by Betree** [comment]
Definitely not, I'll investigate this in priority at the beginning of next week to understand why the info we display is not synchronized with PayPal here.

I assume this happened with the Open Source collective?

**Comment by alannallama** [comment]
Yes it was the open source collective. Thanks!

--
Alanna Irving
hello@alanna.space
https://alanna.space

**Comment by Betree** [comment]
Fixed by https://github.com/opencollective/opencollective-api/pull/1896
