### ISSUE TITLE
Invoices are not downloadable

### ISSUE THREAD

**Issue by DominikAngerer** [opencollective/opencollective#1933]
**Describe the bug**
Invoices are not downloadable. Invoice button in interface is not available - links from mails into timeouts and others result in 404.

**To Reproduce**
1. Try to download an invoice.

**Expected behavior**

Being able to download an invoice as PDF or/and have the button

**Desktop (please complete the following information):**
 - OS: MacOS / Windows 10
 - Browser chrome, safari, ff, IE11
 - Version : current (except IE)

**Additional context**

**Comment by Betree** [comment]
Hi @DominikAngerer is it solved? Did you get this error from the transactions page (`/:collective/transactions`)?
