### ISSUE TITLE
Design Ops → Create documentation that guides the community to understand and collaborate to the design efforts.

### ISSUE THREAD

**Issue by lindatalu** [opencollective/opencollective#1934]
This issue is to track the progress of the framework we'll follow as the Open Collective Design collective to approach design tasks, communicate with the OC team (and externals) and collaborate with the community of designers.

The first draft is here: http://bit.ly/OC_design_doc

@Memo-Es lets get this cleaned up so we can publish it in the collective page.

@alannallama we're aiming to have this eventually included in the Help Docs of open collective just as we have today for developers: https://tafka.d.pr/Krr5Fn so let me know what you need specifically to be able to include this. Any guidelines and what not.

**Comment by znarf** [comment]
@lindatalu @cuiki Please review the content of this issue.

**Comment by alannallama** [comment]
@lindatalu That's great! You are most welcome to include stuff in the main docs. We can give Design its own section, with sub-chapters underneath. I'll make you an author on the gitbook - can I have your email to add you please? I'm sure the Design chapter will be the best looking one in the docs 😁

**Comment by lindatalu** [comment]
@alannallama Thank you good idea to have our own section the docs will be updated by @Memo-Es. You should grant the access to him. maybe the way you will work on those documents is a conversation to have on slack.

**Comment by Memo-Es** [comment]
Hi @alannallama yes, I'd be a pleasure to collaborate with you, please show me the next steps to follow to put this baby online
