### ISSUE TITLE
Can't refund a collective to collective transaction

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1935]
I was trying to refund a transaction made by the up-we-rise collective: https://opencollective.com/up-we-rise/transactions to /brusselstogether

From the api logs on production:
```
 2019-04-15T20:45:04.507427+00:00 app[web.1]: error: GraphQL v1 error: paymentMethod.refundTransaction is not a function
```

Can we fix that?

**Comment by Betree** [comment]
There's a issue for that: https://github.com/opencollective/opencollective/issues/1656

The refund method for this payment method has never been implemented.

**Comment by znarf** [comment]
As a quick win, maybe they can be simply deleted instead of processing the refund like Stripe / Credit Cards.

**Comment by xdamman** [comment]
We should keep collective to collective donations. 

If it's on the same host, deleting these would do the job but I'd argue it's as easy to create the reverse transaction no? So that we have a trace which is always preferable.
