### ISSUE TITLE
Can't refund a manual donation

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1936]
I was trying to refund the initial manual donation that was made to https://opencollective.com/up-we-rise but same issue. There is a "refund" button but clicking on it doesn't do anything. 
Here is the log on api production:
```
2019-04-15T21:09:58.377020+00:00 app[web.1]: error: GraphQL v1 error: paymentMethod.refundTransaction is not a function
```

This is related to #1935 
But in the case of refunding a manual donation, it's important to make sure that the host has manually refunded the transaction. So it's a bit more complicated to implement and it also requires some changes on the frontend to confirm that step before proceeding.

**Comment by Betree** [comment]
There's a issue for that: https://github.com/opencollective/opencollective/issues/1656

The refund method for this payment method has never been implemented.

**Comment by znarf** [comment]
Maybe they can be simply deleted instead of processing the refund like Stripe / Credit Cards.

**Comment by xdamman** [comment]
While I think that we should offer a "refund" function so that it is recorded, we could also offer a "delete" button for those manual donation. This might be easier to implement (it doesn't serve the same purpose but this could mitigate the need for a proper refund)

If it's easy to implement, my preference would be to record the reverse transaction for traceability.
