### ISSUE TITLE
Unexpected error when ___________

### ISSUE THREAD

**Issue by ZhugeYijun** [opencollective/opencollective#1937]
# Describe the bug

I got an unexpected error on https://opencollective.com/create while I was trying to __________

# To Reproduce

1. Go to ________
2. Click on ________
3. Scroll down to ________

# Device
- OS: Win32
- Browser: `5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36`

# Technical details

```

```

**Comment by Betree** [comment]
Hello @ZhugeYijun, thanks for opening this issue. Can you provide more details about how this happened and steps to reproduce?
