### ISSUE TITLE
Improve error message when repo has less than 100 stars

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1939]
**Describe the bug**
If a user is trying to create a new open source Collective, but they connect a repo with less than the required 100 stars, they get an error message that says "No Repository found", which is misleading.

**To Reproduce**
1. Go through the create Collective process from https://opencollective.com/opensource/apply
2. Try to connect a repo with less than 100 stars

**Expected behavior**
The error message should give helpful information, like "The repo you're trying to connect has less than 100 stars. For more info, see [the requirements of the Open Source Collective](https://opencollective.com/opensourcecollective#faq), or contact support@opencollective.com."

**Comment by znarf** [comment]
@alannallama the proposed message doesn't work because we're not connecting a Repo but an Account. The error is that we can not find any repo (with >= 100 stars) linked to the account.

**Comment by alannallama** [comment]
Ok. Just saying that in the message would be fine.
