### ISSUE TITLE
Update email empty

### ISSUE THREAD

**Issue by wooorm** [opencollective/opencollective#1943]
**Describe the bug**

Yesterday we at [unified](https://opencollective.com/unified) created a small update. The email sent out was empty though, see the attached screenshots!

**To Reproduce**

(I’m not going to try and dig into what exactly the cause is, because I don’t want to bug our backers with empty emails 😬)

1. Have one person create an update (specifically, for us it was just an unordered list)
2. Receive an empty email

**Env**
* Device: Mail.app on iPhone XS on iOS 12.2 and Mail.app on macOS on Mojave 10.14.4

**Screenshots**

![3MQ5ofbV jpg-large](https://user-images.githubusercontent.com/944406/56303379-0fa64e00-613c-11e9-83c1-6ba09af2230c.jpeg)

![q9UIadof jpg-large](https://user-images.githubusercontent.com/944406/56303367-09b06d00-613c-11e9-97cc-f49a814e51b5.jpeg)

**Comment by znarf** [comment]
I'm a backer and got it in my Inbox, effectively looking empty. Looking at the source, I see:

![Screen Shot 2019-04-17 at 21 38 18](https://user-images.githubusercontent.com/806/56315914-4dfe3600-6159-11e9-94a5-7621025084d3.png)

We'll investigate promptly.

**Comment by znarf** [comment]
@xdamman can you have a look tomorrow?

**Comment by xdamman** [comment]
Thank you @znarf for your screenshot, it really helped speeding up debugging!
PR coming.
