### ISSUE TITLE
Payment Issues From USA

### ISSUE THREAD

**Issue by fuzzyTew** [opencollective/opencollective#1945]
I just wanted to report that my bank informed me that, because the money was being sent to Belgium, they will decline every payment I initiate with you unless I call them in advance to notify them I will be sending money to Belgium.

It would be great if you guys accepted some other payment method than a credit card, such as cryptocurrency or Paypal.  This would be much more convenient for situations like this.

**Comment by fuzzyTew** [comment]
(note: the project I was trying to back was https://opencollective.com/manyverse/contribute )

**Comment by znarf** [comment]
@fuzzyTew Sad from your bank to be so drastic.

But I agree, this is why allowing a diversity of payment methods is important.

**Comment by Betree** [comment]
See these related issue about better support for PayPal:
- https://github.com/opencollective/opencollective/issues/1141
- https://github.com/opencollective/opencollective/issues/1655

Definitely something we need to work on. Closing this one to follow up in related issues
