### ISSUE TITLE
Collectives showing in wrong section of host page

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1946]
**Describe the bug**
On the Open Source Collective host page, 3 Collectives are showing at the bottom as "part of our organization", when in fact they are just normal Collectives.

**To Reproduce**
Go to https://opencollective.com/opensourcecollective

**Expected behavior**
These three Collectives should show with all the others.

**Screenshots**
<img width="1108" alt="Screen Shot 2019-04-18 at 1 40 14 PM" src="https://user-images.githubusercontent.com/5498878/56331241-9d874500-61df-11e9-83f6-0766723670b1.png">

**Comment by piamancini** [comment]
fixed -
