### ISSUE TITLE
Can't log into staging

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1947]
I've previously signed in with alanna@opencollective.com but now it's throwing this error.

<img width="618" alt="Screen Shot 2019-04-18 at 5 33 24 PM" src="https://user-images.githubusercontent.com/5498878/56338911-28783780-6200-11e9-92f0-0b830519ad74.png">

**Comment by alannallama** [comment]
I asked for a new sign in link as suggested but the same thing happened.

**Comment by Betree** [comment]
Hello Alanna I'm currently using staging to fix a bug, this will be resolved today

**Comment by znarf** [comment]
Works for me now. Let's not have open issues for temporary staging issues. But we should definitely work on this error message.
