### ISSUE TITLE
bring back terms of fiscal sponsorship to the github flow

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1948]
Terms of [Fiscal Sponsorship](https://docs.google.com/document/u/1/d/e/2PACX-1vQbiyK2Fe0jLdh4vb9BfHY4bJ1LCo4Qvy0jg9P29ZkiC8y_vKJ_1fNgIbV0p6UdvbcT8Ql1gVto8bf9/pub)  need to be added again on the github flow 

<img width="404" alt="Screen Shot 2019-04-18 at 7 13 21 AM" src="https://user-images.githubusercontent.com/3671070/56367392-0227ad00-61aa-11e9-9b57-2b0bf3aee1f5.png">

**Comment by znarf** [comment]
I guess we need to add a new static page with the "Fiscal Sponsorship TOS" content.

Can you provide the new copy for the message under the button? And tell which term should be linked?

**Comment by znarf** [comment]
For reference:

![Screen Shot 2019-04-18 at 18 14 30](https://user-images.githubusercontent.com/806/56375460-df2ae680-6205-11e9-9f7d-31f81d009a85.png)
