### ISSUE TITLE
Error on host dashboard: Int cannot represent non-integer value

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1949]
**Describe the bug**
This error is coming up when I try to load the Open Source Collective dashboard.

![Screen Shot 2019-04-19 at 4 20 07 PM](https://user-images.githubusercontent.com/5498878/56405204-553f5400-62bf-11e9-952a-9055f5285949.png)

**To Reproduce**
Go to https://opencollective.com/opensourcecollective/collectives/expenses

**Additional context**
I can load other host dashboards. The error arose after only paying a few expenses through the OSC host dashboard. Possibly related to changes @Betree made recently? This is blocking expenses going out today.

**Comment by alannallama** [comment]
Now I tried to pay OC Foundation expenses and the same thing happened. Paid a few successfully, then started getting errors, now can't load the dashboard at all.

![Screen Shot 2019-04-19 at 4 28 45 PM](https://user-images.githubusercontent.com/5498878/56405444-5a50d300-62c0-11e9-83cb-853dcb5fce91.png)

![Screen Shot 2019-04-19 at 4 29 05 PM](https://user-images.githubusercontent.com/5498878/56405448-5fae1d80-62c0-11e9-85c2-7b06c8d8c213.png)

**Comment by Betree** [comment]
I most certainly introduced this in https://github.com/opencollective/opencollective-api/pull/1908, I didn't tried paying floating amounts and it seems to be the root cause here. On it.

**Comment by Betree** [comment]
This is now fixed in production, sorry for the inconvenience @alannallama
