### ISSUE TITLE
New profile page

### ISSUE THREAD

**Issue by erickrico** [OpenCollective/OpenCollective#195]
i have 2 versions with small changes , mainly the order of the information
we tell how much they are giving monthly and the tier that conveys, also added the "apply for sponsorship" section, since this are companies that can benefit of the exposure i think a video or image of the company will work fine, in the current example i use one video from digital ocean
![profile-page-v2](https://cloud.githubusercontent.com/assets/18429104/17120613/05ac4f36-5293-11e6-8e95-39df94e6b30e.png)
![profile page](https://cloud.githubusercontent.com/assets/18429104/17120614/05d35a7c-5293-11e6-8a5a-fa23611f6f89.png)

@xdamman @piamancini @asood123 what do you think?

**Comment by piamancini** [comment]
I think the 'apply' button can be bigger, under the cards instead of in the supporting area. 
Definitely prefer the first version where the cards are on top.

**Comment by xdamman** [comment]
Not sure what that video or image would be. Can we explore another direction?
Also, I find it very heavy to have this blue frame around the collective card. I'd rather have something lighter/simpler. Maybe reusing what we already have on the collective page:
![](https://cl.ly/3P2L282b061k/Screen%20Shot%202016-07-26%20at%202.01.23%20PM.png)

**Comment by erickrico** [comment]
![profile-2](https://cloud.githubusercontent.com/assets/18429104/17312300/4e0ebe6a-5817-11e6-8429-62ecfa673aef.png)

**Comment by xdamman** [comment]
This is great!

**Comment by carlosascari** [comment]
Merged
