### ISSUE TITLE
Our host page reports an incorrect number of collectives hosted

### ISSUE THREAD

**Issue by Upperholme** [opencollective/opencollective#1952]
Over the last 12 hours or so two collectives have applied to be hosted by our host: https://opencollective.com/platform6-coop

Neither have as yet been approved - we'll discuss the applicationsand approve ro otherwise in the next couple of days.

However our host page reports that "We are Hosting 2 collectives". In fact atthis point we are hosting 1 collective (this being the one that we set up when we created the host), and have two applications pending. I wouldexpect the page to report "We are hosting 1 collective" until such time as one or both of the pending applications are approved.

At that point iI would expect the reported number to change, such that it accurately reflected the humber of collectives hosted.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari 12.02, Firefox 66.03

![Screenshot 2019-04-19 at 09 44 54](https://user-images.githubusercontent.com/5860951/56416275-47baa780-6288-11e9-8ecd-f9608343ed99.png)
![Screenshot 2019-04-19 at 09 44 35](https://user-images.githubusercontent.com/5860951/56416293-4f7a4c00-6288-11e9-8ffa-56a5777cb8b5.png)

**Comment by Betree** [comment]
Thanks for opening this issue @Upperholme, good catch.

**Comment by piamancini** [comment]
The create collective flow is not taking into account when a collective is approved and it's not taking the correct host % fee. 
See for example id21431 it's FALSE but it still shows up + the fee % was 5 (I changed it to 2% to reflect the correct host fee as you can see above)

**Comment by znarf** [comment]
Fixed in https://github.com/opencollective/opencollective/issues/1990
