### ISSUE TITLE
Mismatch in host fee %age across host settings and email notifications

### ISSUE THREAD

**Issue by Upperholme** [opencollective/opencollective#1953]
Our host (https://opencollective.com/platform6-coop) is curently configured with a 2% host fee, and this is displayed on our host page.

However, we have just received email notifications as a result of two new collectives applying to be hosted by us, and those emails state that we will "receive a commission of 5% on all their donations".

The email notification should reflect the percentage figure set in our host config.

screenshot of email:
![Screenshot 2019-04-19 at 09 54 34](https://user-images.githubusercontent.com/5860951/56416643-653c4100-6289-11e9-93cd-a85c42bb7eac.png)

**Comment by piamancini** [comment]
Yes it should. We'll fix it.

**Comment by piamancini** [comment]
@xdamman can you take it on please?
