### ISSUE TITLE
Add "team" section to fiscal host page

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1955]
## User story 
As a user, expense submitter, community member interested in transparency/accountability, or Collective core contributor, I want to easily see who admins a given host. 

## Best solution for this problem
Add a "team" section to host pages, similar to the team section on Collective pages, which displays the admin users.

## Metrics 
Easier to contact host admins, fewer support requests trying to get in touch.

**Comment by gusaus** [comment]
Many (most?) hosts create a supercollective to collect/distribute funds, display the team, contributors/sponsors, transactions, etc. Is there a way to merge that functionality into the host page?

Supercollective - https://opencollective.com/wwcode
Host - https://opencollective.com/wwcodeinc

Supercollective - https://opencollective.com/opensource
Host - https://opencollective.com/opensourcecollective

Supercollective - https://opencollective.com/foundation-collective
Host - https://opencollective.com/foundation

**Comment by alannallama** [comment]
@gusaus yeah there are a lot of improvements to be made with how Hosts are represented as Collectives. #1723 is a related issue. Basically, host pages should have all the functionality of Collective pages, and fees should automatically be added to them. Right now we have to manually create supercollective pages to fill the functions the Host page should.

**Comment by Betree** [comment]
@raulgrafico Let's make sure we take this into account for the new profiles.

**Comment by znarf** [comment]
@alanna @Betree is that solved by the new collective page?

![Screenshot 2019-09-16 at 20 42 21](https://user-images.githubusercontent.com/806/64984192-8d74ae00-d8c2-11e9-8fc7-cbd93308d19f.png)

**Comment by Betree** [comment]
@znarf Yes 🚀
