### ISSUE TITLE
Unexpected error when ___________

### ISSUE THREAD

**Issue by MonkeyWeiW** [opencollective/opencollective#1959]
# Describe the bug

I got an unexpected error on https://opencollective.com/code-settings-sync/order/tier/3848-? while I was trying to __________

# To Reproduce

1. Go to ________
2. Click on ________
3. Scroll down to ________

# Device
- OS: Win32
- Browser: `5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36`

# Technical details

```

```

**Comment by Betree** [comment]
Hello @MonkeyWeiW, thanks for reporting this issue. Can you provide more details, maybe steps to reproduce?
