### ISSUE TITLE
Use case: hire a community member

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1960]
I have two immediate use cases for the tier based goal feature introduced in the latest designs.

One is for [Extinction Rebellion Belgium](https://opencollective.com/xr-belgium) that would love to offer people a way to “adopt a rebel”. 
The other one is for [ParcelJS](https://opencollective.com/parcel) who would love to allow companies to hire developers in their community to work on Parcel.

The ideal user experience would be something along those lines:
When a user goes on the collective page of the collective, they should be able to see the different ways they can contribute financially starting with the easiest ways:
1. Make a one time donation (easy, no brainer, just a straight one time donation)
2. Become a backer (make a recurring donation, support our actions in the long run without anything in particular in return, you just trust us with your money)
3. Hire a rebel / developer / ... (contribute a monthly recurring amount to participate in the budget required to hire part time or full time a human resource for the community)

The number 3 could even be generalized to also acquire material resources for the community (e.g. help us raise $1000 to buy a projector).

## MVP
In all those examples, the only thing we need for a MVP is to attach the concept of goal to a tier and show the list of tiers as a grid on the collective page.

## Sending updates to backers of a given tier

Send updates that are specific to the tier. The goal is to allow the person hired by the community to give regular updates to the people who hired her/him. Those updates could also be listed publicly except the last one which should only show the title (the idea is that the latest update should only be available to the paying backers, but the archived ones can be public).

## Dedicated page for a given tier

When hiring a community member, people want to be able to see the face of that person along with a word of explanation, bio, etc. 

That’s why it would be good to be able to have a dedicated page to show all the details about a given tier. That would require adding a column `longDescription` that is markdown compatible. 

This will also make it easier for people to share a specific URL that goes straight to the right tier.

**Comment by alannallama** [comment]
Can you expand a bit more how this will work @xdamman? Will it be like "Pay $x for a retainer of y hours per month"? Or more like bounties for one-off projects done by a specific person?

For the "adopt a rebel" option, is the reason it can't work with current tiers because they want to adopt a *specific* rebel that the payer chooses? As opposed to just generally "If you give $x/month that covers costs for one rebel".

> That’s why it would be good to be able to have a dedicated page to show all the details about a given tier....This will also make it easier for people to share a specific URL that goes straight to the right tier.

I agree about this. When you click on a tier option, it seems like you should be taken to a page where you see all the details about that tier, and then proceed with contributing.

**Comment by xdamman** [comment]
It will be about contributing a monthly amount towards a bucket that will be used to hire a specific person (or a generic person, it’s up to the collective to name that person or not). It’s up to each collective / person to define what the backers will receive in return. The default is that it’s a donation. People give money and don’t get to decide what the person will be working on. They just trust the person to be working on things that need to be done for the community. In most cases, those people will be paid by more than one backer.

To give a very concrete example, here is a google doc with the descriptions of a few rebels available “for hire” for the Extinction Rebellion Belgium chapter and their role:
https://docs.google.com/document/d/1PAGJ2fkE14Vvhu9Gz137emCD2OEBDN0ZGHxeycrvteI

This gives you an idea of why the current tiers don’t perfectly fit the use case (yet).
Each person should have their own dedicated tier, with their own dedicated page. So that each individual is incentivized to share that particular URL to get their friends and followers to support them.

One thing that came up in the discussions is that people wonder “why should I receive money and not this other person in the community?” (kind of the imposter syndrome). One thing we discussed to mitigate that is to give a commission to the collective. While it would be great to be able to somehow define that in the tier, I think we can take care of that manually for now.

## Specifications

A `Tier` should have a `goal` (amount in cents) and `interval` (that’s already the case). We should also add a `longDescription` and `image` which will be a url to an image.

We need a new page with the lists of tiers (`/:collectiveSlug/[contribute|tiers]`) (my understanding is that @flickz was already working on that and is almost done, would be just good to also add a default tier box for a “custom donation”) and a dedicated page per tier (`/:collectiveSlug/contribute/:tierSlug-:id`, e.g. `/parcel/contribute/hire-Devon-12` — the idea of using a slug based on the title of the tier is for SEO purposes. We could the `:id` to ensure uniqueness).

On the list of tiers and on the tier page we need to be able to see the progress bar towards the goal. So that means we need to be able to get back from the api the current balance of a tier.

When editing tiers, we should be able to edit the goal attached to it and the image.
As a first version, we could either expect the user to provide the url of an image, or skip the image attribute altogether and just rely on markdown for the `longDescription`.

If we can release that quickly, that will already be tremendously useful.

The next step would be to allow to send updates to a specific tier, which I think we already do with the email address `backers@:collectiveSlug.opencollective.com`.

I’d love to keep this feature simple for now so that we can experiment with some collectives, get feedback and get a better view of what they would love to see next before we think about packaging this neatly for everyone.

**Comment by Betree** [comment]
All the changes required by these specs are the same we need for the tier page (https://www.figma.com/file/e71tBo0Sr8J7R5n6iMkqI42d/OC.COM-07-%2F-Collectives?node-id=2587%3A39809). I'm going to split them into smaller issues.

**Comment by Betree** [comment]
Moved specs to #1982 (#1979 #1980 #1981) + #1983 

@xdamman Feel free to close this issue if eveything's covered

**Comment by Betree** [comment]
Resolved with https://github.com/opencollective/opencollective/issues/1982
