### ISSUE TITLE
Host's stripe account is connected but not showing in UI or DB

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1961]
Host  https://opencollective.com/plus-ninety-5-pte-ltd/ has a stripe account successfully connected in stripe dashboard but there is no payment method service=stripe connected to that id in the data base.
Search PaymentMethods table for collectiveid=38432 only the opencollective method is showing up.

**Comment by xdamman** [comment]
When you connect a Stripe account, it adds a `ConnectedAccount`, not a payment method.
You can only receive money when you connect a stripe account. To send money you need a payment method which is a credit card or prepaid card / gift card.

**Comment by piamancini** [comment]
The issue remains that the user doesn't have a stripe service payment menthod in the data base

**Comment by xdamman** [comment]
>  (I said payment method because that's the name of the table in the data base)
No, the table is `ConnectedAccounts` (stripe, twitter, github). There is also a table `PaymentMethods` but that's for payment methods (stripe tokens for credit cards, paypal, prepaid, ...).

I see the Stripe Connected Account so it worked. Might be related to #1964 let me deploy it.

**Comment by piamancini** [comment]
Ok - asked user to see if it shows up now.

**Comment by piamancini** [comment]
closing this - it's fixed on the user's end
