### ISSUE TITLE
New pledge doesn't appear after submitting

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1962]
When pledging a collective that already have existing pledges, the new pledge doesn't appear on the page after submitting the form.

This may be linked to the changes made in https://github.com/opencollective/opencollective-frontend/pull/1600 as I didn't try the flow on a collective that already had pledges when testing it.

The proper way to handle this would be to either use `update` option (best solution, see https://www.apollographql.com/docs/angular/features/cache-updates#after-mutations) or, if not possible, to do a `refetchQuery`.

![Peek 25-04-2019 15-45](https://user-images.githubusercontent.com/1556356/56740437-3c2c1c80-6771-11e9-834d-fa8ddb701b17.gif)

**Comment by brymut** [comment]
Hi @Betree , I'd be more than happy to have a look at this if no one else is on it.

**Comment by Betree** [comment]
Hi @brymut, thanks for joining in. Feel free to do so, you can ping me here or on Slack if you need assistance.

**Comment by brymut** [comment]
Hi @Betree , I managed to get started on the pull request for this issue, my apologies for the delay, an unfortunate mixture of family commitments and trouble getting my dev environment going using Docker. (Do you know anyone who's got Docker going for their dev environment?) Otherwise, I've had some luck and here we go.

**Comment by brymut** [comment]
To start with, I managed to handle the problem by adding the update option as you had mentioned earlier to handle changes to the cache after the mutation. And I think everything should be up to spec at that end. However, I ran into a new issue where once I click 'submit' the new pledge shows up, but the site breaks like this :  

![Alt Text](https://raw.githubusercontent.com/brymut/github-gifs/master/ezgif.com-video-to-gif.gif)

**Comment by brymut** [comment]
With further code exploration and investigation, with why the data.Collective prop was undefined I came across this issue that seems to very similar if not the same thing we see here. #1872 
 
So after trying out the fix that was done for that issue by adding that prop to the state instead, the application works like a charm again. So I was wondering if it was okay to add a new commit to the pull request for this issue containing the same fix and reference the original issue until it is solved?

**Comment by Betree** [comment]
Hi @brymut, no problem for the delay!

We don't use the docker env in the core team, but I may personally be tempted to do so if it works well.

https://github.com/opencollective/opencollective/issues/1872 is really a pain, I hope that it is not the case. Let's continue this conversation directly on the pull request, I'll test with you to see if that's the one responsible for this error.
