### ISSUE TITLE
Can't add members to a collective if their email is already in the db

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1965]
When trying to add someone by their email address, if they are already in the database, there is a "Validation error" being returned in the interface.

**Comment by flickz** [comment]
@xdamman Not been able to reproduce this issue perhaps more details will be helpful.

**Comment by znarf** [comment]
@xdamman @flickz Just tested on staging and it's effectively working.

**Comment by znarf** [comment]
@xdamman Do you have steps to reproduce or we can close?

**Comment by xdamman** [comment]
Couldn’t reproduce. Closing.
