### ISSUE TITLE
Event end times not displayed

### ISSUE THREAD

**Issue by over9001** [opencollective/opencollective#1966]
On event pages, the start time of an event is displayed, but the end time is omitted, hidden, not displayed, missing. 

![screenshots-for-opencollective-bug](https://user-images.githubusercontent.com/6494531/56835495-6568ad80-6842-11e9-8957-dcdb29b6b526.png)

Anyone can see this on any event page, in any browser: https://opencollective.com/opensource/events/london-meetup , https://opencollective.com/veganbrussels/events/oscar-event , https://opencollective.com/open-toronto-school/events/livestream-saturday-40271ev (Why does that last one have a crazy suffix?)

The expected behaviour is for end times to be displayed correctly. 

(Additional context: This is the first real thing I have tried to do using OpenCollective. First day bug hunt? Maybe a challenge for onboarding non-technical people...)

Please help me find where this bug is hiding so I/we can fix it. :) Thanks!

**Comment by over9001** [comment]
Bug research update:
It looks like the server is sending the start time twice to the frontend?
This is what the page looks like on cold-cache reload in the moment before it cleans itself up to look like the screenshot above in the original bug report.

![opencollectivechromescreenshot](https://user-images.githubusercontent.com/6494531/56836349-fb9dd300-6844-11e9-94a6-7ba7af5dc042.png)

React chrome devtools shows the frontend has the start time value twice, and the end time value is MIA.

**Comment by over9001** [comment]
I think I found where the change should be made: https://github.com/opencollective/opencollective-frontend/blob/839bba062436f20414ce8a3a8724e040353b9b81/src/components/CollectiveCover.js#L59

Any guidance welcome!

**Comment by over9001** [comment]
Running the dev server on my local machine, it looks like a simple enough fix:

            {props.collective.startsAt && (
              <React.Fragment>
                <FormattedDate
                  value={props.collective.startsAt}
                  timeZone={props.collective.timezone}
                  weekday="short"
                  day="numeric"
                  month="long"
                />
                , &nbsp;
                <FormattedTime value={props.collective.startsAt} timeZone={props.collective.timezone} />
                &nbsp; - &nbsp;
              </React.Fragment>
            )}
            {props.collective.endsAt && (
              <React.Fragment>
                <FormattedDate
                  value={props.collective.endsAt}
                  timeZone={props.collective.timezone}
                  weekday="short"
                  day="numeric"
                  month="long"
                />
                , &nbsp;
                <FormattedTime value={props.collective.endsAt} timeZone={props.collective.timezone} />
                &nbsp; - &nbsp;
              </React.Fragment>
            )}
            {get(props.collective, 'location.name')}

**Comment by over9001** [comment]
I have made a pull request: https://github.com/opencollective/opencollective-frontend/pull/1709

Please advise! :) Thanks!

**Comment by over9001** [comment]
"All checks have passed"! :)

Looking forward to seeing this get merged soon! Thanks!

**Comment by Betree** [comment]
Resolved by https://github.com/opencollective/opencollective-frontend/pull/1709

Thanks for contributing on this one @over9001! We'll deploy it today or in the next few days. 

I've invited you to the https://github.com/orgs/opencollective/teams/developers group, next time you'll be able to commit directly on the main repository :slightly_smiling_face:
