### ISSUE TITLE
Host getting notification of expenses to Collective they did not approve

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1967]
**Describe the bug**
Collective A applied to be hosted by Host X, but they were not approved. Then someone submitted an expense to Collective A, and the admin of Host X got an email notification. This caused them to be concerned activity was happening in their host that was not approved. It seems pending Collectives of a host are being treated as if they are approved in this case.

**To Reproduce**
1. Apply to a Host as a Collective
2. Do not approve the application
3. Submit an expense to the un-hosted Collective
4. Host admin gets a notification

**Expected behavior**
Host admins should not get any notification of expenses in Collectives they have not approved.

**Comment by piamancini** [comment]
Hi @xdamman can you look into this on Friday?
