### ISSUE TITLE
Cannot build frontend Docker image on Windows

### ISSUE THREAD

**Issue by JohnTitor** [opencollective/opencollective#1968]
**Describe the bug**

I tried to build docker image on frontend but couldn't.

<details><summary>The log</summary>

```
> Copying lang
cp: cannot stat './src'$'\r''/lang': No such file or directory
: not founduild_server.sh: 9: ./scripts/build_server.sh:
> Copying templates
cp: cannot stat './src'$'\r''/templates': No such file or directory
: not founduild_server.sh: 12: ./scripts/build_server.sh:
> Copying static
cp: cannot stat './src'$'\r''/static/fonts': No such file or directory
cp: cannot stat './src'$'\r''/static/icons': No such file or directory
cp: cannot stat './src'$'\r''/static/images': No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencollective-frontend@2.2.0 build:server: `./scripts/build_server.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencollective-frontend@2.2.0 build:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

</details>

I think this place causes error.

https://github.com/opencollective/opencollective-frontend/blob/e2cf5db78dad59d2ba0a96b2d25dec96125078b7/scripts/build_server.sh#L1-L2

When I remove these and add `SRC` and `DIST` as `ENV` in `dockerfile`, the build is success.

**To Reproduce**

1. `git clone https://github.com/opencollective/opencollective-frontend.git`
2. `cd opencollective-frontend`
3. `docker build -t foo .`

**Expected behavior**

The build is success.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1803

**Comment by znarf** [comment]
That's strange, we're actively using the docker setup in our development deployments, without problems so far.

**Comment by JohnTitor** [comment]
@znarf Hmm, I'm not sure. If so, I guess the reason is I'm using Docker on Windows.

**Comment by znarf** [comment]
@JohnTitor can you share the error in the bug description?

**Comment by JohnTitor** [comment]
@znarf Sure, I'll post later.

**Comment by znarf** [comment]
This is stale. Feel free to reopen if you have more information.
