### ISSUE TITLE
Contribution Flow: Can't go back due to CC validation

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1970]
**Describe the bug**

When trying to contribute with an account without a stored credit card, after reaching Payment Details step, I'm prevented to go back because of a bogus credit card validation.

**To Reproduce**

As a Signed In user, without a Credit Card stored on your account.

1. Go to 'https://opencollective.com/veganbrussels/contribute'
2. Click on 'Next step'
3. Click on 'Next step' again
4. Click on 'Previous step'

**Current behavior**

Credit Card validation error.

**Expected behavior**

I'm on Step 2 and can edit my donation amount.

**Screenshots**

![Contribution-Error](https://user-images.githubusercontent.com/806/56886488-67fc1a80-6a6f-11e9-8f85-d467f58cf1a0.gif)

**Comment by Betree** [comment]
@flickz Be careful while fixing this - we need to have the following flow covered:

1. User complete all the steps until payment
2. User go back to Step 2 and sets an invalid amount
3. User click on previous
4. User jumps to Step 3 by clicking on the (3) bubble

If we don't do any validation, users may be able to submit an order with an invalid amount.

We have two options to cover this:
- Validate step when we click on "Previous" (what we do today)
- Update `lastVisitedStep` to forbid user to go to Step 3 directly if Step 2 is edited
