### ISSUE TITLE
Contribution Flow: error message is in french

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1971]
**Describe the bug**

While I actively set the interface to English, Credit Card related error messages are displayed to me in French (likely because it's my browser's default language).

**To Reproduce**

As a Signed In user, without a Credit Card stored on your account, with a browser language set to french and the Open Collective website set to English.

1. Go to 'https://opencollective.com/veganbrussels/contribute'
2. Click on 'Next step'
3. Click on 'Next step' again
4. Click on 'Next step' again

**Current behavior**

Credit Card error in French.

**Expected behavior**

Credit Card error in English.

**Screenshots**

![Screen Shot 2019-04-29 at 11 14 43](https://user-images.githubusercontent.com/806/56886769-06887b80-6a70-11e9-9204-b09dd465b165.png)

**Comment by Betree** [comment]
This is because Stripe auto-detects the language if not provided. To fix it we have to provide the locale manually. See https://github.com/stripe/react-stripe-elements#props-shape-1

**Comment by znarf** [comment]
Let's do that.

**Comment by flickz** [comment]
@Betree  How is this suppose to work exactly? The docs doesn't really provide more information about the `locale` option. Do we just set `locale` to `en`?

**Comment by znarf** [comment]
@flickz It needs to match the current active locale.

So, if strings are currently in english, it should be effectively `en`. But if I french is activated, it should be `fr`, etc ...

**Comment by znarf** [comment]
locale is mentioned in this page. https://stripe.com/docs/stripe-js/reference

One way to test might be to to set the Open Collective interface to French, and test that Stripe errors are appearing in French.
