### ISSUE TITLE
Link to Slack in contributing.md not working.

### ISSUE THREAD

**Issue by brymut** [opencollective/opencollective#1972]
Hi, new to open collective and would like to learn how I can start contributing.

I headed over to the contributing guide page and noticed that the link to slack (at the bottom) isn't working. I'm not sure if that [slack.opencollective.com](slack.opencollective.com) was a custom third level domain that redirects to your slack page or if there was a mistake instead of it being [opencollective.slack.com](opencollective.slack.com) . 

I'd be more than happy to change that for you if that is the case.

**Comment by brymut** [comment]
Absolutely my bad, even the link you used in your comment isn't working for me. Strange, so switched to my phone and the link is working. So probably something to do with my browser/computer's connection? My apologies. 

![Reproduction](https://im5.ezgif.com/tmp/ezgif-5-693c849c91ce.gif)

**Comment by znarf** [comment]
@brymut If it happens to to you, it might happen to others, let us know if you understand better the cause.

**Comment by brymut** [comment]
Alright, I'll have a look and re-open if I spot something.

**Comment by brymut** [comment]
okay, link works when I disconnect from the VPN I use (NordVPN). No clue why 🤷‍♂️
