### ISSUE TITLE
Evaluating Greenkeeper

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1974]
We're quite happy with Greenkeeper to help us update our packages. It had a few glitches but that is happening to everyone, we know that :-)

However, because we have many dependencies, the workflow could be better and it's taking more time as it should to edit and validate the pull requests.

- When there is a merge conflict in `package.json`, we have to edit it by hand, in the GitHub interface or locally
- When there is a merge conflict in `package-lock.json`, we have to edit it locally, resolve the conflict with `npm install`
- Sometime, we want to `rebase` the branch against master
- When there is a new version of a package, on top of a non-merged update, we need to manually create a new PR from the most recent branch, this is time consuming.

Would be great to see how `renovatebot` or `dependabot` would help on this different points.

**Comment by Betree** [comment]
I'm not very familiar with `renovatebot` but I've used `dependabot` for some time. Here is how it addresses the issues you've listed:

> When there is a merge conflict in package.json, we have to edit it by hand, in the GitHub interface or locally
>
> When there is a merge conflict in package-lock.json, we have to edit it locally, resolve the conflict with npm install

Dependabot has a `@dependabot recreate` command that recreates a fresh PR, which usually solves the conflicts in package.json and package-lock.json.

Also Dependabot automatically rebase its PRs when it detects a conflict in these files, so most of the time there's nothing to do.

> Sometime, we want to rebase the branch against master

Dependabot has a `@dependabot rebase` command that does that

> When there is a new version of a package, on top of a non-merged update, we need to manually create a new PR from the most recent branch, this is time consuming.

Dependabot automatically close the PR, delete the branch and create a new one when an unmerged package is updated. 

Example: https://github.com/opencollective/opencollective-invoices/pull/31#issuecomment-485396220

**Comment by znarf** [comment]
@Betree thank you for the input. How do you trigger commands?

**Comment by Betree** [comment]
By mentioning the bot in a comment, like on this one: https://github.com/opencollective/opencollective-invoices/pull/34#issuecomment-487871858

**Comment by znarf** [comment]
We're using dependabot now.
