### ISSUE TITLE
Tier page: goal progress

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1979]
Require https://github.com/opencollective/opencollective/issues/1978

## Frontend

- [ ] Show a progress bar on the tier page (see [Figma](https://www.figma.com/file/e71tBo0Sr8J7R5n6iMkqI42d/OC.COM-07-%2F-Collectives?node-id=2587%3A39809))

![image](https://user-images.githubusercontent.com/1556356/56952839-7dd71180-6b3b-11e9-9ee9-6511369f2ef6.png)

**Comment by xdamman** [comment]
Don’t forget to handle both cases of absolute goals and recurring goals.
E.g.
- $522 / $1,000 raised
- $1,020/month / $2,000/month raised
