### ISSUE TITLE
Discover page

### ISSUE THREAD

**Issue by erickrico** [OpenCollective/OpenCollective#198]
Section to explore all the collectives

**Comment by erickrico** [comment]
For the sort options i was thinking something among
-new
-trendy/popular
-featured

and i would like to add other kind of filter for opesource or meetups but i dont know if we can tell what each collective topic is

as for the scroll, i think right now a infinite scroll will work just fine, but as more collectives join we might have to change this behaviour 

![discover](https://cloud.githubusercontent.com/assets/18429104/17186816/5d50d8aa-53fc-11e6-8b42-271d6780c2e7.png)

**Comment by erickrico** [comment]
awesome, let me add that

**Comment by erickrico** [comment]
![discover](https://cloud.githubusercontent.com/assets/18429104/17195837/f1fc6176-5425-11e6-9944-08d9384a3f9c.png)

**Comment by piamancini** [comment]
love it.

**Comment by xdamman** [comment]
I wonder if we could make the tags more visible (not hidden by a dropdown). That way people can see that there are collectives around many different topics directly.
