### ISSUE TITLE
Tier page: Add long description to tiers

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1981]
# Specs

## API

- [x] Add `longDescription` field for tiers (text, default=null)
- [x] Allow editing `longDescription` in `editTiers` mutation

## Frontend

- [x] On the new collective page, add the ability to edit the `longDescription` inline with a rich text editor
- [x] On the new collective page, show the long description on the tier (see [Figma](https://www.figma.com/file/e71tBo0Sr8J7R5n6iMkqI42d/OC.COM-07-%2F-Collectives?node-id=2587%3A39809))

**Comment by xdamman** [comment]
Last point: I’d say show the `tier.image`, it’s not really the `backgroundImage` which should fallback to the `collective.backgroundImage`

**Comment by Betree** [comment]
@xdamman My bad that was a typo, the issue for tier's image is https://github.com/opencollective/opencollective/issues/1980#issuecomment-487913455
