### ISSUE TITLE
Under review email when registering from GitHub

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1984]
**Describe the bug**

When using the GitHub flow, looks like the review is automated and the collective is active by default. However, it was reported that admins get an email saying the collective is under review, which is confusing.

**Expected behavior**

Currently unknown.

**Comment by znarf** [comment]
What do you think should be the right behavior @alannallama ?

**Comment by piamancini** [comment]
There should be two emails, one that says under review and another one following up that says it has been approved.

**Comment by alannallama** [comment]
If they are automatically approved, why would there be two emails? They would both some at the same time.

Automatically approved > gets email that their Collective is approved and active

Under review > Collective is not active and they should get an email saying they are under review and pending, then if they are approved, they get notified of that.

But the second case should not be occurring in the automated github flow.
