### ISSUE TITLE
Surface organizations in search

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1986]
It's impossible for someone to discover a sponsor profile unless they know the exact url - we should surface them in search

**Comment by piamancini** [comment]
@znarf can we spec this out and add a bounty?

**Comment by znarf** [comment]
@piamancini we don't have the notion of "sponsor profile" in our systems, are you speaking about "organizations" ?

**Comment by piamancini** [comment]
yes -- sorry

**Comment by znarf** [comment]
@piamancini seems it's actually supported in search.

![Capture d’écran 2019-05-20 à 16 14 31](https://user-images.githubusercontent.com/806/58028138-64adf900-7b1a-11e9-909a-b292675a6456.png)
![Capture d’écran 2019-05-20 à 16 14 41](https://user-images.githubusercontent.com/806/58028139-65468f80-7b1a-11e9-8114-141cc877bd72.png)

**Comment by piamancini** [comment]
closing because Magic!
