### ISSUE TITLE
Unsubscribe links should lead to frontend, not API

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1987]
I clicked unsubscribe in the monthly report for a test collective I set up, and this page loaded:

<img width="991" alt="Screen Shot 2019-05-02 at 3 07 20 PM" src="https://user-images.githubusercontent.com/5498878/57054972-1ca27000-6cec-11e9-858a-986e47d65b89.png">

Does this mean I was unsubscribed?

**Comment by piamancini** [comment]
LOL yes, but the message could at least have some css

**Comment by znarf** [comment]
Unsubscribe link should lead to the website (frontend) not the API.

The frontend should trigger an API request and display a success/failure message.

**Comment by yellowwoods12** [comment]
@alanna  Can you assign this to me?

**Comment by znarf** [comment]
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](https://github.com/opencollective/opencollective/blob/master/BOUNTY.md).

**Comment by znarf** [comment]
@yellowwoods12 Feel free to work on it.

**Comment by znarf** [comment]
@yellowwoods12 Any progress? I forgot, once assigned, there is a time limit on bounties, in this case 7 days. This might be extended.

**Comment by EslamHiko** [comment]
@znarf Hello, can I work on this issue?

**Comment by EslamHiko** [comment]
@znarf I created this PR https://github.com/opencollective/opencollective-frontend/pull/1959 this is the frontend part so what do you think?
