### ISSUE TITLE
Bring back disclaimer below donate button

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#199]
It used to say "By clicking above, you are agreeing to give $100/month to Open Collective for Rails Girls Atlanta...". The exact message already exists in Tiers.js - we must have lost it in one of the refactors. Let's bring it back.

**Comment by asood123** [comment]
@carlosascari, @xdamman can one of you please pick this up in next day or so? Just had another user submit payment and then cancel subscription.

**Comment by carlosascari** [comment]
I'll work on this issue today
