### ISSUE TITLE
Wrong label: "We are hosting X collectives"

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1990]
**Describe the bug**

On https://opencollective.com/stumptownsyndicate on the bottom of the page there is this string: "We are hosting 5 collectives". But something is wrong, there is no collective below.

![Screen Shot 2019-05-02 at 15 40 32](https://user-images.githubusercontent.com/806/57079446-a3f1e280-6cf0-11e9-9e45-61ace53f11ab.png)

**Comment by piamancini** [comment]
This is happening because the member table has 5 rows where this collective has the role=HOST

Those collectives are status=FALSE and therefore are not showing up. 

We shouldn't show that a host is hosting a collective until that collective is Active - but this pulling the information as expected.

**Comment by znarf** [comment]
Instead of `status=FALSE` you mean `isActive=false`? Or where are you exposing `status`?

**Comment by piamancini** [comment]
my mistake, it's isActive=FALSE

**Comment by znarf** [comment]
Deployed.
