### ISSUE TITLE
include terms of fiscal sponsorship when a collective applies directly to c6 host

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1991]
opencollective.com/opensourcecollective/apply should include the terms of fiscal sponsorship. I'm happy to do it if I get pointed to the right place in the code.

**Comment by znarf** [comment]
This is happening here:
https://github.com/opencollective/opencollective-frontend/blob/105056575700c6ea46cb4fe4ea1aa39a76f32cd6/src/components/CreateCollectiveForm.js

There is something already existing to support TOS for hosts , we just have to edit the host settings and add a "tos" entry to enable that.

Maybe you want to tweak that and rename it "terms of fiscal sponsorship" instead of TOS. Do you want to edit the copy?

> I agree with the terms of service of the host ({HOST}) that will collect money on behalf of our collective

**Comment by znarf** [comment]
The edit form should also be updated  to reflect the name.

![Screen Shot 2019-05-06 at 11 49 14](https://user-images.githubusercontent.com/806/57218216-0ef33000-6ff5-11e9-9827-f6f8f55e4105.png)

**Comment by piamancini** [comment]
yep sure. I need to be on a branch to edit that file. what should I do?
<img width="901" alt="Screen Shot 2019-05-07 at 10 52 02 AM" src="https://user-images.githubusercontent.com/3671070/57309480-2e05c680-70b6-11e9-90bc-a6d321038da6.png">

**Comment by znarf** [comment]
@piamancini just give me the new copy for the following sentence and I will take care of it.

> I agree with the terms of service of the host ({HOST}) that will collect money on behalf of our collective

**Comment by piamancini** [comment]
I agree with the terms of fiscal sponsorship of the ({HOST}) that will ....

**Comment by znarf** [comment]
Will do.

**Comment by piamancini** [comment]
can I close this?

**Comment by znarf** [comment]
It was done in https://github.com/opencollective/opencollective-frontend/pull/1747/files

Was not deployed yet.

**Comment by znarf** [comment]
Yes, it's working.

@piamancini please be aware that we're not displaying the checkbox for TOS/TOFS when switching hosts or applying manually.
