### ISSUE TITLE
Collective creator can still edit when removed from members

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1992]
core contributor creates a collective and later decides to move on and remove themselves as a core contributor from that collective 

They remove themselves via the Members tab in editing the collective. This successfully marks the member row as deleted at however, since the collective row in the collectives table still has the userID in the createdBy column, the user is still able to edit the collective. 

the user id needs to be removed from the column in the collective table for the user to lose admin rights on that collective.

**Comment by znarf** [comment]
We should not rely on `createdBy` for permissions. We should stop doing that and before enforcing the new policy, we should generate a report to see who would be affected by the change.

**Comment by piamancini** [comment]
agreed.

**Comment by znarf** [comment]
```sql
SELECT "Collectives"."id", "Collectives"."slug", "Users"."id", "Users"."email"
FROM "Collectives", "Users"
WHERE "Collectives"."type" != 'USER'
AND "Collectives"."CreatedByUserId" = "Users"."id"
AND NOT EXISTS (
  SELECT * FROM "Members"
  WHERE "CollectiveId" = "Collectives"."id" AND "MemberCollectiveId" = "Users"."CollectiveId"
  AND "role" = 'ADMIN'
)
AND NOT EXISTS (
  SELECT * FROM "Members"
  WHERE "CollectiveId" = "Collectives"."HostCollectiveId" AND "MemberCollectiveId" = "Users"."CollectiveId"
  AND "role" = 'ADMIN'
)
```

218 rows
