### ISSUE TITLE
Erroneous pending orders

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1994]
<img width="501" alt="Screen Shot 2019-05-03 at 4 38 27 PM" src="https://user-images.githubusercontent.com/5498878/57119955-049d2000-6dc2-11e9-8b44-00c8ce3042b8.png">

Noticed this on the host dashboard. What does it mean to mark and incoming donation as paid? And how can a donation be pending like this?

**Comment by Betree** [comment]
This can normally happen when people submit "Manual donations" (see screenshot below). However I just checked and this option should not appear for open source collective - at least it doesn't for Octobox.

@xdamman Any idea?

![image](https://user-images.githubusercontent.com/1556356/57124060-82423b00-6d84-11e9-97fb-16191fccc687.png)

**Comment by znarf** [comment]
@Betree so, this is something else.

We need to investigate. Maybe an application error in the middle of the transaction.

**Comment by alanna** [comment]
This is still happening...

![Screen Shot 2019-05-29 at 4 42 14 PM](https://user-images.githubusercontent.com/5498878/58529964-ee537a00-8230-11e9-8b97-efe7b1273f80.png)

**Comment by znarf** [comment]
In that case, I read "a month ago", "5 month ago".

**Comment by xdamman** [comment]
I confirm that this option is only for Open Collective Brussels and Open Collective Paris and Open Collective Europe.

So this shouldn’t happen. Maybe indeed an error while processing the transaction? Because it starts with the status “PENDING” but then it should directly go to “PAID” or “ERROR”.

**Comment by alanna** [comment]
@znarf - this issue is for dealing with all the weird old pending orders that don't make sense. 

Easiest way to see them is to go to the OSC host dashboard and filter orders by pending. Unless they were created in the last couple days since you turned the feature on (which I don't think any have been yet), they are mysterious and shouldn't exist.

**Comment by znarf** [comment]
So far, we found 4 cases for PENDING orders:
- the regular one, for manual bank transfers -> this is expected
- for updated subscriptions, orders were updated to PENDING until next payment -> we don't do that anymore
- for totalAmount=0 "free" tier/membership, payments were never processed and the order not validated -> this is being fixed
- crashes in the middle of payment processing -> this needs to be fixed and orders should be properly marked as ERROR

**Comment by alanna** [comment]
@znarf what you describe here seems good to me. I am not aware of any other cases but I also don't feel like I know enough to say for sure. For me the only important outcome is we can easily see the ones that are for manual bank transfers.

**Comment by znarf** [comment]
- Manual Payments are now expiring after 2 months, as of today there is 72 entries not expired on the platform and 44 for the Open Source Collective. This is the one that should appear in the dashboard.
- Pending errors with Credit Cards are either errors (app crash) or 3d secure validation that was not fulfilled, they will be marked as error after 1 day

https://github.com/opencollective/opencollective-api/pull/2655
