### ISSUE TITLE
"no payment source available" paypal error

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1995]
Getting this error when trying to pay [this expense](https://opencollective.com/gitea/expenses/7874):

<img width="521" alt="Screen Shot 2019-05-03 at 4 41 28 PM" src="https://user-images.githubusercontent.com/5498878/57120032-85f4b280-6dc2-11e9-9a8c-e1a10116861b.png">

**Comment by alannallama** [comment]
Same thing happening for [this expense](https://opencollective.com/rocketmod/expenses/7844), but all the others are going through fine.

**Comment by Betree** [comment]
This is coming from PayPal. Strange that it happens only for some expenses, maybe user's account must have a default payment method configured too?

The following help page may help, if it doesn't then it would be good to check with the users:

> You will get this error when the preferred method of payment has not been set. Or when the card you added hasn't been confirmed.
> 
> The solution: Link a bank account, or add a credit card or debit card
> 
> 1. Log into your PayPal account.
> 
> 2. Click "Money" at the top right portion
> 
> 3. Scroll down and under Bank, or under Credit and Debit Cards link your payment method.
> 
> How to confirm your card
> 
> 1. Log into your PayPal account.
> 
> 2. Click "Money"
> 
> 3. Click "Update" beside your card
> 
> 4. Click" Enter PayPal Code"
> 
> 5. Enter the 4-digit PayPal Code and click "Confirm Card"

**Comment by alannallama** [comment]
OK, I asked those two users to check their paypal accounts. Weird that it's happening for two people at once. Maybe paypal changed a policy?

**Comment by alannallama** [comment]
One user added their bank account in Paypal and then I was able to put the payment through. Another (Rocketmod) said they checked their account and nothing seemed wrong so they didn't do anything, so I tried again and one payment went through. But then the same error came back for the next payment I tried on that Collective. Now there are still a bunch of outstanding expenses I can't pay.

**Comment by alannallama** [comment]
@Betree after googling the error I saw something about how it can appear if you have less than $100 in your paypal account (meaning open source collective's paypal account as the payer). Could this be causing the problem? I logged into our paypal manually and it's showing a balance of only $21, but I thought it was configured to automatically add more funds from our bank account as needed?

**Comment by Betree** [comment]
@alannallama I'm not familiar with how we have this setup with the bank account. 

@xdamman @piamancini any input regarding [Alanna's comment](https://github.com/opencollective/opencollective/issues/1995#issuecomment-489494328)?

**Comment by xdamman** [comment]
My understanding is that it should refill automatically since it’s connected to the bank account. But I haven’t logged into this account in a while. Pia might know better.

**Comment by alannallama** [comment]
This error has disappeared so I'll close the issue. No idea what was going on but the expenses went through this time.

**Comment by alannallama** [comment]
This issue is happening again on [this expense](https://opencollective.com/rocketmod/expenses/7837). The user has checked their paypal and can't see any issues, and we've paid this user multiple times before via paypal.

**Comment by alanna** [comment]
It's happening for [this one](https://opencollective.com/engineering/expenses/8176) too now.

**Comment by Betree** [comment]
This is happening again https://opencollective.slack.com/archives/GDTJY7S48/p1581627301000700
