### ISSUE TITLE
Evaluate the need for a community managed docs team

### ISSUE THREAD

**Issue by gusaus** [opencollective/opencollective#1997]
Based on conversations and observations, it seems like the Open Collective team could use some help producing documentation, FAQs, guidebooks and other materials needed to better support the product and the community.

Problem is it’s currently not clear which Open Collective team members are responsible for docs; if there’s a specific need (I.e. project manager, maintainer/docs lead, writer, etc.); or if there’s a process to onboard and sustain community members interested in contributing. 

Having no experience (skills or interest) managing a docs team myself, it would be great if others more well versed in this area could chime in.

**Comment by alannallama** [comment]
@gusaus sorry no one picked this up when you originally posted it. Obviously we haven't had as much capacity as we've liked for documentation, although we've made some big improvements this year with the new docs. We've been accepted to Google Season of Docs, so I think we'll continue to see steps forward. Currently, I think it makes sense for us to collaborate with a few key contributors, as opposed to trying to go really wide.

**Comment by gusaus** [comment]
@alannallama The docs refactoring you headed up https://github.com/opencollective/opencollective/issues/1612 + new community members joining for [Seaon of Docs](https://docs.opencollective.com/help/projects/season-of-docs-2019) + the [bounty program](https://docs.opencollective.com/help/developers/bounties#open-collective-bounty-program) provides a much better foundation for organizing and sustaining a community docs team. 

Goals and structure of some other communities could again serve as inspiration - 
https://make.wordpress.org/docs/
https://www.drupal.org/about/strategic-initiatives/documentation

This, of course, could be a really good task to pilot https://github.com/opencollective/opencollective/issues/1996

**Comment by Saichethan** [comment]
Can I take this issue @alannallama

**Comment by alannallama** [comment]
I don't think anything needs to be done on this issue, so I'm going to close it. We'll reevaluate toward the end of the year after our Season of Docs experience.
