### ISSUE TITLE
Refunds are not taken into account when using API

### ISSUE THREAD

**Issue by ilyavolodin** [opencollective/opencollective#1998]
**Describe the bug**
When calling backers API (https://opencollective.com/api/groups/<client>/backers) backers information does not account for refunds. Total amount donated per client includes all of the money that were donated, even if part of them was refunded. Also, there's no indication that a company/person is no longer a sponsor, if they canceled their monthly donations.

**To Reproduce**
1. Refund one month worth of donations for a given sponsor
2. Navigate to https://opencollective.com/api/groups/<client>/backers and verify that for that sponsor, `totalDonations` includes full amount, not counting the refunded portion. 
3. Verify that `lastDonation` field still shows the date of the refunded monthly donation.
4. Verify that `role` and `tier` fields do not have any indications that this sponsor is no longer have any monthly donations scheduled.

**Expected behavior**
`totalDonations` should be calculated taking account refunded amounts. There should be some indication that specific backer is no longer a recurring sponsor when they cancel their monthly donations.

**Comment by znarf** [comment]
@ilyavolodin I guess it's for ESLint. I'm currently looking at a another problem Nicholas is having with this API endpoint. The endpoint itself is old, not convenient and should not be used anymore. I will propose an alternative that should solve your problems. Currently working on that.

**Comment by ilyavolodin** [comment]
Yes, it's for ESLint. And Nicholas did mention the other problem as well. So I guess this can be closed since you are working on alternative solution to the problem.

**Comment by znarf** [comment]
I submitted a Pull Request: https://github.com/eslint/eslint.github.io/pull/564
