### ISSUE TITLE
Design Monthly Email template

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#200]
We need a design of a monthly email template that shows: 
- Name of the Collective 
- Budget Available 
- New Donation 
- New backers/Sponsors
- Expenses 
- Fees 
- Did you know? / changelog section 

@erickrico I'm assigning this to you. :)

**Comment by erickrico** [comment]
hey let me know if this works 
![monthly mailing](https://cloud.githubusercontent.com/assets/18429104/17745865/35df3a46-6473-11e6-958e-32724e224086.png)

**Comment by piamancini** [comment]
this is done.
