### ISSUE TITLE
New collectives on hosts with 0% host fee fall back to 5% host fee

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2000]
It looks like lately the collectives created on OC Paris and OC Brussels that have a zero % host fee were getting the 5% host fee.

- [ ] Fix the bug to avoid new collectives having the same issue
- [x] Update manually the host fee in the db
- [ ] Figure out how much in fees they had to pay and refund those collectives

**Comment by xdamman** [comment]
This was the query that was run on May 4th 2019: 
```sql
UPDATE "Collectives"
SET "hostFeePercent" = 0
WHERE "HostCollectiveId"=11284 OR "HostCollectiveId"=9802
```

(For OC Paris and OC Brussels hosts)

**Comment by xdamman** [comment]
Total host fees that should be reimbursed: 
- OC Paris (id 11284): €24 
- OC Brussels (id 9802): €216
- Techsoup (id 16485): $2 to [one event](https://opencollective.com/net2van-meetup/events/google-analytics-101-master-class-for-nonprofits-taught-by-a-marketing-veteran-16534ev)
- Platform6coop (id 28201): <£1 (they changed their host fee to 2%, some collectives had the 5% rate)
- WWCode: $0
- OperationCode (id 9803): $0.90
- DotNetFoundation (id 9800): $30 to [/net-core-summer-event-netherlands](https://opencollective.com/net-core-summer-event-netherlands)
- userfrosting-project (id 12212): $14 to [/userfrosting](https://opencollective.com/userfrosting)

Breakdown for OC Brussels:
![](https://d.pr/free/i/pcqlJj+)

**Comment by piamancini** [comment]
@xdamman - I thought I already fixed platfoorm coops one. Did it revert back?
