### ISSUE TITLE
Collectives not appearing on host page

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#2001]
**Describe the bug**
[This host](https://opencollective.com/stumptownsyndicate) says it has 6 Collectives, but none are appearing on the page.

![Screen Shot 2019-05-05 at 2 36 57 PM](https://user-images.githubusercontent.com/5498878/57187504-f8d96700-6f43-11e9-984d-2046f7d9bc02.png)

**Comment by znarf** [comment]
This is already being taken care of in https://github.com/opencollective/opencollective/issues/1990. Duplicate.
