### ISSUE TITLE
Donations as a spam vector

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2002]
This escort site has started backing Collectives as a way to show up as spam on their pages: https://opencollective.com/escort-girl

Short term, we need to shut this down and ban them from backing more Collectives.

Longer term, do we need an option for Collectives to reject/ban specific subscriptions? Or some other defense for this?

Honestly, I'm surprised spammers will spend real money to do this, but I guess you can never underestimate them. I wonder how other platforms who show supporters on pages deal with this?

**Comment by znarf** [comment]
@alannallama On the platform side, what we need is to define a policy that we can use to disable this kind of organization. Maybe, we also need to update our terms of service to include this policy.

- Collectives should also be able to refuse donations based on their own rules.
- Hosts should also be able to refuse donations based on their own rules.

**Comment by alanna** [comment]
This has come up a couple times in the last few days ([here](https://github.com/opencollective/opencollective/issues/2113) and [here](https://opencollective.freshdesk.com/a/tickets/414)) so I think we need to solve it.

**Comment by Betree** [comment]
I think that https://github.com/opencollective/opencollective/issues/2097 would be a great way to solve this. Maybe we can tackle https://github.com/opencollective/opencollective/issues/2006 at the same time: we could, when admins click on User card > Remove member, add a confirmation like this:

> Are you sure you want to remove _____ from the members of MyCollective?
> ------------------------------------------------------------------------
> This will remove the collective from the widgets and everywhere
> they appear as a backer of your collective.
>
> :ballot_box_with_check: Also refund their orders
>
> [Cancel]             [Confirm]

**Comment by alanna** [comment]
Another example: https://opencollective.com/bluehost-vs-squarespace

**Comment by ghuntley** [comment]
Another example: https://github.com/reactiveui/rfcs/issues/27

**Comment by Andarist** [comment]
I've encountered the same problem - people trying to boost their SEO, put backlinks or whatever. And that being their only motivation for donations.

**Comment by Andarist** [comment]
BUMP for stale bot

**Comment by ghuntley** [comment]
Bump

**Comment by sbinlondon** [comment]
@ghuntley @Andarist If you have any further ideas/comments on this issue please let us know, I'm writing a moderation proposal this week and will be including this issue in it.

**Comment by Andarist** [comment]
As I've mentioned somewhere on Twitter - would be great to have like a dedicated warning/information (copy-pastable) about a collective admin having a right to moderate the list as they see fit to exclude such SEO-boosting donors from being displayed automatically. If they still want to donate - I'm OK with that, but I'd like to be clear upfront that I don't want to host their "ads". Something like this should be displayed (opt-in? or maybe even better - as opt-out) before donations are made.

Having a manual control over which sponsors are displayed would be very much appreciated, it's a waste of time to bother your team with requests to hide some. Having an option to refund somebody would probably be a good idea as well.

**Comment by znarf** [comment]
Closing the issue because:
- Collective Admins now have a "Rejected Categories" setting to prevent some kind of accounts to contribute
- Collective Admins can reject contributions from their collective page

This is live and is definitely helping There will be likely some follow up, but let's track this in more precise issues.
