### ISSUE TITLE
Ability for admins to cancel/reject financial contributions 

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2006]
## User story 
As a Collective or Host admin, I want to be able to refuse/cancel financial contributions (subscriptions) so that I can have a say in who my project accepts money from and who shows up on my page as a contributor, and to combat backer spam.

## Best solution for this problem
A screen showing all active recurring contributions to a Collective, with an option to cancel each, and an option to block future contributions from that account.

Related to #1993 to also allow Collective admins to give refunds, which should probably be part of the cancel flow (option to refund past contributions as well as block future ones).

Ideally also a way to refund and block one-time donators as well.

## Context

#2002 - Someone is using becoming a backer as a spam vector to get listed on Collective pages.

Some Collectives (and hosts) have legal or moral restrictions on who they can accept funding from.

**Comment by Betree** [comment]
Only blocker to implement this is https://github.com/opencollective/opencollective/issues/1656. We don't have the proper refund functions for collective to collective and manual donations. We should add them before implementing this, otherwise users will get an error whenever they try to refund such transactions.

**Comment by piamancini** [comment]
@xdamman maybe you are considering this in the context of the new create collective with recording expenses option?

**Comment by Betree** [comment]
@flickz yes, it also requires https://github.com/opencollective/opencollective/issues/1993 on which I added a bunch of items that must be solved in order to make it feasible

**Comment by boneskull** [comment]
Is there a workaround for this in the meantime?  On our project's website (not its OC page), we could manually suppress the display of logos.

Otherwise, if we have this problem, how should we approach it?

**Comment by josegonzalez** [comment]
The Dokku organization would also be willing to co-sponsor development of this feature. I think it's important to us as an OSS org to ensure that any money we receive comes from people and organizations that don't run afoul of our own moral prerogatives. Getting paid for writing code is great, but not at the expense of some elses human rights.

I'll bring this up in the slack group as well to see what would be appropriate :)

**Comment by boneskull** [comment]
Mocha will be removing ~19 sponsors from our site listing, likely in the next couple days (unclear how many of these actually appeared, but the number is nonzero).  Hopefully this won't cause too many problems, but we really don't need to be linking to spammers.

**Comment by Betree** [comment]
Pasting here a solution that was recently discussed: 

Have a `Reject contribution` button on the transactions page that will refund the contributions and open a modal for you to confirm if you want to:
- [ ] Remove the member from your collective
- [ ] Prevent them from contributing again in the future
- (Optional) Add a small message to explain why you're rejecting their contribution

**Comment by sbinlondon** [comment]
This is on the 'host dashboard' project board. Is this being addressed in the current host dashboard revamp or should I reassign this to the moderation project? @piamancini @Betree ?

**Comment by Betree** [comment]
@sbinlondon let's confirm with @Memo-Es, but I don't think there's anything in design for this yet. It's actually linked to both projects.

**Comment by sbinlondon** [comment]
@josegonzalez We are looking at moderation as a whole right now - if you're in our Slack we have a #moderation channel or you can comment on this [issue](https://github.com/opencollective/opencollective/issues/2741). It sounds like you might have some thoughts on moderation in general and I'd love to get your feedback on what we can do beyond just cancel/reject contributions.

**Comment by sbinlondon** [comment]
Please refer to our updated issue for Collective admins going forward: opencollective/opencollective#3463

**Comment by MR10833768** [comment]
There is nothing that can hold you back once you decide to start making financial corrections in the field of work problems.
