### ISSUE TITLE
Enforce minimum amount in Contribution Flow

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2008]
Now that we have a minimum amount in tiers, we need to display it and enforce it in the interface.

**Comment by znarf** [comment]
Let's discuss the behavior of `getOrderMinAmount`. cc @Betree

**Comment by znarf** [comment]
@cuiki We need to make clear in the interface there is a minimum amount for some (most) tiers. 

- This needs to be displayed/explained on the Contribution Details step
- There needs to be a clear explanation why the "Next Step" is disabled

![Screenshot 2019-05-21 at 11 24 45](https://user-images.githubusercontent.com/806/58084435-29afd200-7bbb-11e9-8967-4435477fb5e9.png)

**Comment by alanna** [comment]
This seems related to #2030 - if they want to give a smaller amount, they should be allowed to, but it should be clear they will no longer be contributing to that specific tier.

**Comment by cuiki** [comment]
This changes things a bit from @znarf 's request.

So if the user wants to change the amount to something lower than the minimum, should we allow them to do so by suggesting other tiers that might be a better match? Rather than just notifying of the minimum amount?

**Comment by znarf** [comment]
@cuiki The swap tier aspect will make that way more complicated. Let's stick to the original request for now. But still, the error message or the notification could say: "Want to give less than {minimumAmount}? Look at [LINK]other tiers[/LINK] or make a [LINK]free donation[/LINK]."

**Comment by raulgrafico** [comment]
@Betree hi Ben, here is the link to the Figma file:
https://www.figma.com/file/GF1gQ7fWNfaOAFNwuLeAUl/OC.com-Hot-Fixes?node-id=1520%3A218

**Comment by Betree** [comment]
![image](https://user-images.githubusercontent.com/1556356/79448139-2dbdbd00-7fe1-11ea-8d7e-00547ae816c3.png)

**Comment by snitin315** [comment]
@Betree can I work on this?

**Comment by Betree** [comment]
@snitin315 Sure! Let us know if you need anything

**Comment by snitin315** [comment]
@Betree When I tried minAmout = `{minAmount}` its displaying `10000` instead of `100`. I think it's `100.00` but without `.` ?

![Screenshot at 2020-06-01 17-05-20](https://user-images.githubusercontent.com/46647141/83405590-6fd47e00-a42a-11ea-861a-c8ea74b54064.png)

**Comment by snitin315** [comment]
Got it I need to format the currency using formatCurrency Util.
![Screenshot at 2020-06-01 17-23-14](https://user-images.githubusercontent.com/46647141/83406612-aad7b100-a42c-11ea-9956-82d7582059f7.png)

**Comment by Betree** [comment]
> When I tried minAmout : {minAmount} its displaying 10000 instead of 100. I think it's 100.00 but without . ?

@snitin315 it's because the amount is in cents (integer). 

> Got it I need to format the currency using formatCurrency Util.
minAmount: {formatCurrency(minAmount, currency)}

You can use it, but I'd recommend to rather use `FormattedMoneyAmount` as it also supports displaying an interval.
