### ISSUE TITLE
Expense transactions not featuring original invoice

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2009]
**Describe the bug**

When browsing, DEBIT transactions of a Collective, when clicking on Download (pdf), I get an invoice automatically generated by Open Collective, not the original one. 

**To Reproduce**

1. Go to https://opencollective.com/engineering/transactions
2. Click on 'debits'
3. Click on 'view details'
4. Click on 'Download (pdf)'

**Current behavior**

Downloading an Open Collective generated invoice.

**Expected behavior**

Not sure. The original invoice?

**Screenshots**

![Screen Shot 2019-05-09 at 09 23 58](https://user-images.githubusercontent.com/806/57434901-4b649d00-723c-11e9-81b3-4680abca0698.png)

**Comment by Betree** [comment]
This behaviour is indeed confusing and I don't see the need to have generated invoices here, we should definitively surface the invoice submitted by the person who submitted the expense if there's one.
