### ISSUE TITLE
Proposal: link /contribute to /tiers

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2011]
Right now /contribute is an alias for /donate
but now that we have a (great!) new /tiers page ([example](http://opencollective.com/babel/tiers)), I think it would make more sense to have /contribute to point there.

So to be clear, we would still have /donate and /tiers and /contribute would point to /tiers.

Any objection?

**Comment by znarf** [comment]
I think both /donate and /contribute should be alias to /tiers.

Meaning, we need a new URLs for the previous behavior of /contribute and /donate. We could introduce a new dedicated URL such as /donate/one-time /contribute/one-time

**Comment by xdamman** [comment]
`/donate` to me should open a big customizable dollar amount right front and center with the option to make it recurring. If people come to donate, we shouldn't distract them with a "menu of different options" that will paralyze them ("what should I pick?"). They come to donate without any expectation of return (that's the definition of a donation). So let's keep that interface minimal and straight to the point. The best interface is the one that gets out of the way to let the user achieve their initial intent as quickly as possible and with fewer questions as possible.

For one-time I'd keep the current aliases which I love and I keep telling people about: `/donate/:amount `and `/donate/:amount/month`. That said, I have no objection for adding a `/donate/one-time` but I'm just questioning the utility of it. It's also hard to memorize it (one word? two words? dash? underscore?).

`/contribute` is an obvious one for `/tiers` because it's about showing all the ways you can contribute.

**Comment by znarf** [comment]
Why do we have assumptions that there is a difference between /contribute, /donate and /pay when it's today exactly the same? Is there already a difference in the way we use these URLs?

Based on the discussion in https://github.com/opencollective/opencollective/issues/1969 do we have new definitions for these terms?

**Comment by xdamman** [comment]
Today there is no difference between those 3 URLs. The primary reason being that it was "good enough" at the time. Now that we have a page `/tiers` I think we can start differentiating them to better match end users' expectations.

The #1969 conversation is still ongoing but what's already clear is that we want to double down on the concept of "contribute" (and "contributions"). This really reflects what an open collective is all about. It's about being open to contributions (by opposition of a triangle, a classic privately owned company that is top down).

**Comment by znarf** [comment]
No rush, but we should take a decision on that for the release of the Tier page.

**Comment by xdamman** [comment]
For now, I’d make /contribute an alias for /tiers

For /donate, let’s keep it the way it is for now. We can always revisit that later. 
I don’t want to add an extra step. If I send a link to someone to /donate, I want them to donate as simply as possible, without worrying about the different tiers. But I see your point and I could be convinced otherwise. Maybe that would be easier to make that switch once the /tiers page will have by default a first tier which is “make a custom donation” (right now it’s just a small link at the bottom)

**Comment by Betree** [comment]
One problem is that some collectives seems to have linked the current `/contribute` (see extract from the logs below). We should acknowledge that it's going to be an unexpected behaviour for these users, though one could argue that it's not a major issue because people reaching the link still end up on a page that pushes them to contribute. 

![image](https://user-images.githubusercontent.com/1556356/58572812-b2261680-823c-11e9-9550-0bb38dfc7f19.png)


Also if we define the new route as `/contribute`, then we should be consistent and have the tier url as `/contribute/:tierSlug-:tierId` too, or said with code:

```es6
pages.add('tiers', '/:collectiveSlug/(tiers|contribute)');
pages.add('tier', '/:collectiveSlug/(tiers|contribute)/:tierSlug?-:tierId(\\d+)');
```

Enters the `orderCollective` route (see below). The `tiers` route has some ambiguity with it, but it will work if we put it first (though order is not a great way to prioritize routes).

```es6
pages.add(
  'orderCollective',
  '/:collectiveSlug/:verb(donate|pay|contribute|order|events)/:amount(\\d+)?/:interval(month|monthly|year|yearly)?/:description?',
  'createOrder',
);
```

---

I personally don't like having multiple URLs for the same page. It's [bad for SEO](https://moz.com/learn/seo/duplicate-content) (it would be better if we used `rel="cannonical"` but we don't) and it makes the routes less predictable.

While I agree with the fact that `/contribute` is a better name than `/tiers`, I think that the risk of breaking existing URLs + the SEO penalty should be considered if we make this change.

**Comment by xdamman** [comment]
Thanks for this info.

> one could argue that it's not a major issue because people reaching the link still end up on a page that pushes them to contribute.

Exactly, I'm not worried about that.
It's a minor change for them. But that's why I want to keep `/donate` the way it is so that there is still a way to get to the old behavior

> I personally don't like having multiple URLs for the same page. It's bad for SEO (it would be better if we used rel="cannonical" but we don't) and it makes the routes less predictable.

That's right. Maybe we can ditch the `/tiers`? We never communicated about it. I think `/contribute` makes more sense.

All in all, I don't see any major risk to move forward with this small change.

**Comment by Betree** [comment]
We get a good number of requests for `/tiers`, we should not take the assumption that it is not used:

![image](https://user-images.githubusercontent.com/1556356/58577178-39c45300-8246-11e9-9d8c-6f3aced4dfc7.png)

**Comment by Betree** [comment]
Breaking a URL that users use is not an acceptable solution. So we can't ditch /tiers for now.

We defined previously that SEO was important for this page, so the way to go with this change is to create the new routes and to set the canonical meta properly.
