### ISSUE TITLE
Unexpected error when ___________

### ISSUE THREAD

**Issue by WET9** [opencollective/opencollective#2012]
# Describe the bug

I got an unexpected error on https://opencollective.com/ethereum-revolutions1/events/tier/9156-?amount=10000000000&eventSlug=bigcrypto001-42070ev while I was trying to __________

# To Reproduce

1. Go to ________
2. Click on ________
3. Scroll down to ________

# Device
- OS: Linux x86_64
- Browser: `5.0 (X11; CrOS x86_64 11647.154.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.114 Safari/537.36`

# Technical details

```

```

**Comment by Betree** [comment]
Hello, thanks for opening this issue. Can you provide more details about how this happened and steps to reproduce?

**Comment by WET9** [comment]
May im know the issue ist not conections

**Comment by Betree** [comment]
@wet9 I'm sorry that you faced this bug. I'm not sure how this happened, but we need more details to reproduce and fix the issue.

In the mean time, the following URL will work if you need to place an order for this event: https://opencollective.com/ethereum-revolutions1/events/bigcrypto001-42070ev/order/9156

**Comment by WET9** [comment]
Close all

Pada Jum, 10 Mei 2019 01:16 Benjamin Piouffle <notifications@github.com>
menulis:

**Comment by WET9** [comment]
Close all issue

Pada Jum, 10 Mei 2019 01:16 Benjamin Piouffle <notifications@github.com>
menulis:
