### ISSUE TITLE
Move applications page to /applications

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2013]
# Problems

- Currently the page to edit user's API keys lives on `https://opencollective.com/:user/applications`. With the upcoming Zapier integration, it would be useful to have a direct link to this page that users can click on from Zapier.

- We're not making it clear that API keys are created per user (not per collective). If I go to https://opencollective.com/babel/applications, I'll be able to create API keys but they will not appear because they will be created for the logged in user, not for `babel`. Same goes for any collective profile, it isn't a security issue (we have good checks on the API side) but to the user it may look like one.

# Proposal

Move the page to `https://opencollective.com/applications`, fetch API keys from `LoggedInUser`.

**Comment by znarf** [comment]
Looks like there are indeed some mistakes in the Applications model.

I agree with the change, it's great to have a page that can be easily linked.
