### ISSUE TITLE
Webhooks: Add warning about private infos

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2016]
Require https://github.com/opencollective/opencollective-frontend/pull/1624

# Problem

With the upcoming webhooks release, users are going to post Open Collective data on third party services. That data might include personal information.

For example the following JSON is an activity for new expense as posted by the webhook. You may notice that it includes user's `email`, `paypalEmail` and the URL to the invoice.

```json
{
  "createdAt": "2019-05-09T16:42:56.724Z",
  "id": 71280,
  "type": "collective.expense.created",
  "UserId": 9476,
  "CollectiveId": 10885,
  "data": {
    "host": {
      "id": 9802,
      "type": "ORGANIZATION",
      "name": "BrusselsTogether ASBL",
      "image": "https://cl.ly/0Q3N193Z1e3u/BrusselsTogetherLogo.png",
      "slug": "brusselstogetherasbl",
      "twitterHandle": "brutogether",
      "githubHandle": null,
      "publicUrl": "http://localhost:3000/brusselstogetherasbl",
      "mission": "We are on a mission to make Brussels a great city to live and work",
      "isSupercollective": false
    },
    "collective": {
      "id": 10885,
      "type": "COLLECTIVE",
      "name": "Open Potatoes",
      "image": "https://opencollective-staging.s3-us-west-1.amazonaws.com/72fcb400-6810-11e9-a86d-e7e9045f1519.png",
      "slug": "open-potatoes",
      "twitterHandle": "open-potatoes",
      "githubHandle": "open-potatoes",
      "publicUrl": "http://localhost:3000/open-potatoes",
      "mission": null,
      "isSupercollective": false
    },
    "user": {
      "id": 9476,
      "firstName": null,
      "lastName": null,
      "email": "wowhello@opencollective.com",
      "paypalEmail": "piouffon-facilitator@gmail.com"
    },
    "fromCollective": {
      "id": 10884,
      "type": "USER",
      "name": "Zappa",
      "image": "https://opencollective-staging.s3-us-west-1.amazonaws.com/40cf57a0-2fbf-11e9-85ef-e1ba4406e770.jpg",
      "slug": "test43wow",
      "twitterHandle": null,
      "githubHandle": "Betree",
      "publicUrl": "http://localhost:3000/test43wow",
      "mission": null,
      "isSupercollective": false
    },
    "expense": {
      "type": "DEBIT",
      "id": 2479,
      "UserId": 9476,
      "CollectiveId": 10885,
      "currency": "EUR",
      "amount": 4200,
      "description": "Test",
      "attachment": "https://d.pr/free/i/OlQVIb+",
      "category": "Communications",
      "payoutMethod": "paypal",
      "vat": null,
      "privateMessage": null,
      "lastEditedById": 9476,
      "status": "PENDING",
      "incurredAt": "2019-05-09T16:42:56.665Z",
      "createdAt": "2019-05-09T16:42:56.666Z",
      "updatedAt": "2019-05-09T16:42:56.666Z"
    }
  },
  "TransactionId": null
}
```

# Solution

Add a `MessageBox` with `type="warning"` on the "Edit webhooks" page with a message like:

> Activities posted on webhooks may include sensitive users data such as users emails (when an expense is created). Only add webhooks for services you personally trust and always ensure that unnecessary data is properly hidden.

**Comment by eloyekunle** [comment]
For users configuring Zaps (via Zapier), won't these private information also be sent to the Zapier webhook URLs?

**Comment by Betree** [comment]
@eloyekunle Yes they will. We'll have to surface this information on the app's triggers too

**Comment by znarf** [comment]
Can you confirm we're only including sensitive information (email) if the Webhook creator has the right to see them?

**Comment by Betree** [comment]
@znarf I added a task in my To Do to review all of them before merging to be sure. As proposed by @eloyekunle, we'll also need to have a filtering layer on `publishToWebhook` to whitelist what's published.

**Comment by znarf** [comment]
Cool, the permissions should be aligned with what we have in GraphQL.

**Comment by Betree** [comment]
We now sanitize the data to only include safe items
