### ISSUE TITLE
Reimplement Collective to Collective contributions across fiscal hosts

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2017]
## User story 
As a Core Contributor, I want to use the balance of my Collective as the payment method for contributions to other Collectives, regardless of fiscal host. See #1196 and #2003 

This is a very common request from users, and current workarounds are a tedious manual process for everyone involved.

## Best solution for this problem
Core contributors can financially contribute to any Collective on the platform using their Collective balance, which would show up in the list of payment options in the contribution flow.

## MVP
The current workaround is:

* Recipient Collective submits expense to contributing Collective, putting their fiscal host's paypal as the payment address
* Contributing Collective admin approves expense
* Host of contributing Collective pays expense out
* Host of recipient Collective manually add those funds to the recipient Collective balance

In addition to the obvious tediousness and complexity of this process, it's also unclear what documentation should be submitted with the expense. Does the individual collective admin create an invoice with their own name? Does the recipient host have to create the invoice?

I do not recommend a quick MVP solution here, as that's what we tried last time and it didn't work.

## Metrics 

* Fewer support requests to coordinate Collective to Collective contributions.
* More giving between Collectives.

## Notes

Giving up and downsteam was relatively highly rated in importance on the recent [core contributor survey](https://medium.com/open-collective/what-core-contributors-want-4e7327ac9180).

I believe the previous implementation of this relied on charging credit cards on file to move funds between organizations, and this didn't work very well.

Ideas:

* The system should know the Paypal addresses of the hosts involved - can we trigger a payment similar to how we pay out expenses?
* The system could automatically create and submit the expense using info it already knows for these transactions, and just put it into the regular expense flow for fiscal hosts (not fully automated, but way better than the current situation).
* Maybe inter-host transactions could be batched (once a month?) similar to how a central bank works. So if Collective A in Host X gives $100 to Collective B in Host Y, and then later Collective C in Host Y gives $150 to Collective D in Host X, at the end of the month, Host Y owes Host X $50 to settle up, and an expense could be created in the system automatically to trigger that.
* Or all Collective to Collective contributions be paid to Open Collective Inc and we could use that as a clearing house, which we could batch and settle on a regular basis between Inc and all the Hosts.

**Comment by alannallama** [comment]
Related question: How does this currently work for Bulk Transfer from Organizations? We credit funds to the Organization in the system, but Organizations don't have fiscal hosts. Where is that money? How can they spend it across all Collectives in different hosts without running into the same problems as cross-host Collective-to-Collective contributions?

**Comment by Betree** [comment]
> Related question: How does this currently work for Bulk Transfer for Organizations? We credit funds to the Organization in the system, but Organizations don't have fiscal hosts. Where is that money? How can they spend it across all Collectives in different hosts without running into the same problems as cross-host Collective-to-Collective contributions?

To do that organizations use a special `Prepaid` payment method that we create for them. It has an initial balance that we use to compute the real balance by subtracting the amount of the DEBIT transactions created from it.

It's different from the collective balance because the collective balance is basically a sum of all the CREDIT transactions minus the DEBIT transactions, it doesn't have an `initialBalance`.

I currently don't see why we could not do the same thing that we do for prepaid to solve this issue, that is to simply create a transaction from collective A to collective B, using the collective as the payment method. But they may be blockers that I don't see that prevent us from implementing like this so I'll let @xdamman and @znarf correct me if this is not right.

**Comment by alanna** [comment]
@kewitz @znarf - wouldn't this be much easier to achieve now that we have bank transfer payments? 

To accomplish this manually, now you could make a contribution to the payee Collective and select bank transfer payment type, which triggers a notification with the host's bank info, then file an expense under the payer Collective and put that host bank info for the payout method, and put the reference# as a note.

So could we automate the above process and therefor enable cross-host payments between Collectives?

**Comment by kewitz** [comment]
@alanna I think we should get back to think about this.
TransferWise can automate sending money to a bank account, but the host would still need to manage the required funds.
Also, if we want to enable funds to be transferred between two hosts, it would require both hosts to be connected to TransferWise.
A similar approach should be possible using PayPal Payouts, once I finish implementing it.

**Comment by alanna** [comment]
> the host would still need to manage the required funds

That's what creating the pending order to the payee Collective is for - right now the host manually confirms funds received to the bank account so the Collective is credited. But if we were handling it through Transferwise, we already know the funds were paid, so it could just be automatically created and marked as paid instantly.

I'm not sure both hosts would need to be connected to Transferwise, only the payee Collective's host. Because we know the funds were sent from the payer host (because they used Transferwise on Open Collective), we can assume the money will arrive and therefore confirm the credit to the destination Collective immediately. It doesn't matter if the recipient host has Transferwise. They just need a bank account to receive the funds, and they don't need to do anything manually when they arrive.

**Comment by alanna** [comment]
Another thing this could enable: With #3161 we could allow hosts to pay for their Open Collective plans using their own budget balance.

**Comment by znarf** [comment]
@alanna I created a project for that. https://github.com/opencollective/opencollective/issues/3190 I'm willing to work on it on the short-term to mid-term.

**Comment by kewitz** [comment]
> I'm not sure both hosts would need to be connected to Transferwise, only the payer Collective's host. Because we know the funds were sent from the payer host (because they used Transferwise on Open Collective), we can assume the money will arrive and therefore confirm the credit to the destination Collective immediately. It doesn't matter if the recipient host has Transferwise. They just need a bank account to receive the funds, and they don't need to do anything manually when they arrive.

I think this is doable and could work well enough. Although there are some caveats:
TransferWise will confirm the payment once the money leaves TW. The transaction can still bounce-back after being marked as PAID, in that case, our systems will revert those transactions and mark the expense as ERROR.
Also, trusting the sending part would mean that only a set of collectives could donate to other collectives and not the other way around.

**Comment by alanna** [comment]
Could it be possible to move forward with [my suggestion](https://github.com/opencollective/opencollective/issues/2017#issuecomment-637855825) of how to implement this pretty easily using bank transfers?

**Comment by alanna** [comment]
Part of this is being worked on in #3190 already.

**Comment by RichardLitt** [comment]
@alanna Is there any further movement on this? I've also run into this issue.

**Comment by alanna** [comment]
@znarf @kewitz what do you think about the feature [described here](https://github.com/opencollective/opencollective/issues/2017#issuecomment-637855825) and the chances of moving this forward?

**Comment by alanna** [comment]
@Betree @znarf I recently did an expense from an OSC Collective with the Payee as OC Nigeria, via bank transfer. It seems like it worked automatically and added the funds to OC Nigeria?? If so, that means that Collective to Collective transfers across hosts via bank transfer is already activated?? If so, can we clarify how this works and add it to the docs, and we also should let the whole admin team know because this will make life a lot easier.

**Comment by znarf** [comment]
> It seems like it worked automatically and added the funds to OC Nigeria??

If the Payee is financially active (Collective or Host+Budget), it's visible in their transactions and added to the balance. That's the usual behavior.

> If so, that means that Collective to Collective transfers across hosts via bank transfer is already activated??

No, nothing special happened here I'm afraid.

The original issue is about making **financial contributions** across Hosts and having the money move automatically.

**Comment by alanna** [comment]
OK so Collective to Collective *expenses* across hosts work, but not *contributions* @znarf ?

**Comment by znarf** [comment]
@alanna I'm confused. In your case, it was from a Collective (hosted by OSC) to an Organization (Nigeria Host). It worked but there is nothing new here, you were just able to pay an expense to an Organization/Host.

Collective to Collective expenses across hosts are currently not supported.

However, if I try to follow your reasoning, the previous example demonstrates that this could not be complicated to support. Given that the Host has a bank account configured and we force the Payout Method to be the bank account of the Host. Maybe @Betree can give additional input.

**Comment by alanna** [comment]
I was thinking of the host's budget (Nigeria) as like a "Collective". I was surprised when the funds were automatically added to Nigeria's budget (in another currency no less!) because I had assumed we'd need to manually add the funds because it was across different hosts. But maybe I don't get how it works.

I do think, however, that if it worked in this case, there's no reason we can't do the same thing for Collective to Collective contributions or expenses across hosts if it's paid by bank transfer.

**Comment by znarf** [comment]
Closing in favor of https://github.com/opencollective/opencollective/issues/3190

**Comment by BenJam** [comment]
> Closing in favor of #3190

actually closing
