### ISSUE TITLE
Overwritten Intl.locale value

### ISSUE THREAD

**Issue by flickz** [opencollective/opencollective#2019]
The issue is when you set OC interface to a new language, the value of `intl.locale` remains as `en` meanwhile the interface texts change.

During my investigation, I log the value of `intl.locale` within [`WithIntl.js`](https://github.com/opencollective/opencollective-frontend/blob/master/src/lib/withIntl.js#L55), I realized the `locale` changes on the server but gets overwrite back to `en` on the browser.

**Comment by Betree** [comment]
I think this has been solved by https://github.com/opencollective/opencollective-frontend/pull/2049, I now see the correct value in `marketingPage` when I log `intl.locale`.
