### ISSUE TITLE
Load translated marketing pages

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2020]
Now that [Crowdin](https://crowdin.com/project/opencollective) allows static pages to be translated easily, we should provide a better way to load them.

Currently all the static pages are imported in `pages/marketingPage.js` and a `if (...) else if (...)` is taking care of serving the right one. To provide a generic way to handle this, we could have a const object to define the pages:

```es6
import howItWorksPageScript from '!file-loader?publicPath=/_next/static/js/&outputPath=static/js/&name=[name]-[hash].[ext]!../static/how-it-works-page/javascripts/scripts.js'; // eslint-disable-line
import howItWorksPageStyle from '!css-loader!../static/how-it-works-page/stylesheets/styles.css';

const PAGES = {
  'how-it-works': {
    basePage: '../static/how-it-works-page/index.html',
    css: howItWorksPageStyle,
    js: howItWorksPageScript,
    className: 'mkt-page-how-it-works'
  },
  ...
}
```

We should then be able to load the file dynamically based on `intl.locale`.

# Specs

- [ ] Move languages support definition from `components/Footer.js` to `constants/locales.js`

- [ ] If locale is not `en` and is a supported locale, try to load localized file, replacing `.html` by `.${locale}.html`.
Example: `'../static/how-it-works-page/index.fr.html'`

- [ ] If it fails, load the default `basePage`

**Comment by Betree** [comment]
A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged.

:warning: This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

:arrow_right: [More info](https://github.com/opencollective/opencollective-frontend/edit/master/BOUNTY.md)

**Comment by burinious** [comment]
I will like to work on this issue

**Comment by Betree** [comment]
@burinious This issue is medium complexity and it might be difficult to solve for relatively new contributors. Let us suggest tackling a couple of simple complexity issues first. But if you really want it, sure, you can have a look and try. The time limit for it is one week.

**Comment by burinious** [comment]
@Betree Please help I can't find the ```locale.js``` under the specified directory

**Comment by leonardohof** [comment]
@Betree I want to try this one too.

**Comment by yellowwoods12** [comment]
@Betree Should I give this a shot?

**Comment by Betree** [comment]
Hello @yellowwoods12, @leonardohof is already working on this one

**Comment by Betree** [comment]
:trophy: This issue is now completed by @leonardohof (great job!) 

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

---

For more info about the bounty process and how to format your invoice, please read https://docs.opencollective.com/help/developers/bounties

If you have any feedback on how we could improve the bounty process or how to better onboard new developers please [share it with us](https://slack.opencollective.com/), we're always eager to improve :slightly_smiling_face:
