### ISSUE TITLE
GraphQL Error on /subscriptions (possible flicker)

### ISSUE THREAD

**Issue by ElijahLynn** [opencollective/opencollective#2022]
**Describe the bug**
GraphQL Error (string)

**To Reproduce**
1. Visit /subscriptions for first time

**Expected behavior**
no error

**Screenshots**
![image](https://user-images.githubusercontent.com/1504756/57545043-f6915700-730d-11e9-933b-a87058f29876.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Chrome latest-stable

**Additional context**
Could not reproduce

**Comment by znarf** [comment]
Thank you for submitting this. I unfortunately can't reproduce at the moment.

I tried on Firefox / macOS:

- navigating to /subscriptions with a normal account
- force refreshed the /subscriptions page with a normal account
- navigating to /subscriptions with an empty account
- force refreshed the /subscriptions page with the empty account

**Comment by ElijahLynn** [comment]
K, these types of issues are the worst to debug (not reproducible), but as long as others aren't reporting it then it seems super low priority and I suggest closing this. And it is helpful in case it crops up again with other users.
