### ISSUE TITLE
Minor issue: when a new collective applies to be hosted by our host organisation two email notifications get sent

### ISSUE THREAD

**Issue by Upperholme** [opencollective/opencollective#2023]
When a new collective applies to be hosted by our host organisation two email notifications get sent.
They appear to be identical and sent at the same time.

**Comment by piamancini** [comment]
This is across the board for hosts - we should put it in the fix list -- @znarf maybe for Olu?

**Comment by znarf** [comment]
I also experienced it but could not find anything wrong in our systems yet.
