### ISSUE TITLE
Fixed header wrapping bug

### ISSUE THREAD

**Issue by sloria** [opencollective/opencollective#2025]
**Describe the bug**

The fixed header on collective pages overflows incorrectly.

**To Reproduce**

1. Go to https://opencollective.com/marshmallow.
2. Scroll down.

**Expected behavior**

Header displays in a single row

**Screenshots**

![opencollectiveheaderissue](https://user-images.githubusercontent.com/2379650/57586535-2c2c7080-74c5-11e9-9539-d8c47e1d18ea.gif)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Firefox
 - Version: 66.0.4

**Comment by Betree** [comment]
Hello @sloria,

Thanks for reporting this issue.

As the collective admin you have more links in there and there's not enough place to display them all in one row. The backers of your collective should not encounter this bug, though we acknowledge that this NavBar doesn't have a great responsiveness. 

We are currently revamping the collective page and the re-design will address this issue. I'm not sure that we will fix it for the current version but if anyone has something simple to suggest we could work on it.

**Comment by maddhruv** [comment]
@Betree with v2 (NCP) I don't see this happening.
@sloria can you reverify

**Comment by sloria** [comment]
It still wraps

![image](https://user-images.githubusercontent.com/2379650/66055090-00a53380-e503-11e9-964d-8f49439222c1.png)

but I'm unsure if this is expected?

**Comment by Betree** [comment]
Yep, this was a bug on the old collective page but it's part of the design for the new collective page to display the collective logo and name above the links :slightly_smiling_face: 

![Peek 02-10-2019 17-27](https://user-images.githubusercontent.com/1556356/66057987-e3d82280-e539-11e9-9480-399fadfaee61.gif)
