### ISSUE TITLE
Enable Collective admins and host admins to reject or unapprove expense after approval

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2027]
## User story 
As a Collective admin, I want to be able to reject or unapprove an approved expense that has not been paid out, because sometimes an expense is approved by mistake.

As a host admin, I want to unapprove an expense if it is lacking valid documentation. Currently expense submitters cannot edit an approved expense, so we constantly have to make small edits to fake it back to unapproved status so they can make changes.

## Best solution for this problem
Reject button should continue to be available to Collective admins even after the expense has been approved. 'Approve' button should turn into 'unapprove' instead of disappearing, so they can decide whether to fully reject it or just send it back to unapproved status. Unapprove button should be available to host admins.

**Comment by alanna** [comment]
This still comes up constantly. @raulgrafico will this be fixed in the expense improvements project?

One thought.... why not allow expense submitters to edit the expense any time, and just make it go back to unapproved status if they do? Why disallow them from editing approved expenses at all?

**Comment by raulgrafico** [comment]
@alanna reject an approved expense is already on our scope for the new Expense Flow. 
Re the edit at anytime feature, we only need to create a real flow to make sure we don't have logic gaps, because that is a delicate subject, maybe we can start working on those requirements on our weekly call.

**Comment by alanna** [comment]
This issue specifies the ability to `unapprove` expenses. That's the part I want to make sure is in the design.

Regarding changes to approved expenses, it would work the same as when an admin makes a change now - it would go back to unapproved status.

**Comment by flickz** [comment]
Closed in https://github.com/opencollective/opencollective-frontend/pull/2783 &  https://github.com/opencollective/opencollective-api/pull/2695
