### ISSUE TITLE
Allow financial contributors to change tier options mid-flow

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2030]
## User story 
As a financial contributor, I want to be able to customize my donation (amount and frequency) regardless of which tier I originally selected, so I can give how I want to give to the project without restrictions.

We get support requests where users are frustrated because they don't understand why they are unable to change the amount and frequency options for their contribution. Currently we have to advise them to go back out and select the "one time donation" option instead of a tier, and it's a bad experience right at the most critical moment of someone committing to give.

## Best solution for this problem
If a contributor selects a tier option that's recurring, for example, but then changes their mind and wants to make it one-time, the system should allow it, and just not count them as contributing to that specific tier. It should not block them from proceeding, but just change the title of the contribution flow to something general instead of that tier.

We should make it a lot more clear to Collective admins how to set tiers up to restrict or not restrict how people give to them. Especially with the upcoming conflation of tiers and goals in the Collective page, admins need to decide if they want a tier to be strict (e.g. can only use it if you give $10/mo recurring) or permissive (can give any amount or frequency, but specifically to that goal/tier). I think core contributors are unintentionally blocking contributions they would like to accept.

**Comment by znarf** [comment]
@alanna I think this was implemented in https://github.com/opencollective/opencollective/issues/2110 Closing.
