### ISSUE TITLE
API: create expense programmatically 

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2035]
I’d love to build a quick script to automatically submit my monthly invoice to a collective.
I could also imagine people who would love to build similar scripts to automatically create an expense when they receive an email. 

For that, I just need to be able to call the `createExpense` mutation using my API key.
Expenses created that way would always be in `PENDING` status and should be approved using the interface (or email notification to the admins of the collective).

The `attachment` Is a tricky one. While we could in theory ask people to simply send us a URL to the file, there is the risk that the file won’t be there anymore when we will compute the monthly or yearly reports for the host. So we should require people to submit the actual file and we should store it on our AWS bucket. Not sure how file uploads is handled with GraphQL.

E.g. 

```graphql
mutation createExpense($expense: ExpenseType!) {
  createExpense(expense: $expense) {
    amount
    currency
    description
    category
    incurredAt
    payoutMethod
    paypalEmail
    privateMessage
    attachment
  }
}
```

**Comment by victorb** [comment]
Our use case (Open Services / Open-Registry) is to submit expense reports for each received invoice from infrastructure providers.

We would want the invoices to be automatically accepted in the collective (but obviously not the fiscal host).

I would hope we could create invoices that are not tied to a specific user of the Collective, as they could come and go. Instead, we'd like to have a Collective API key the invoice application could act via, to not be tied to a user. But could probably work around this, as I don't think Collectives can have API tokens right now, just users.

**Comment by alannallama** [comment]
@xdamman - Instead of doing this through the API, which many users will not find accessible, we should just add a "repeating invoice" option to the new expense flow described in #1167 - I'd much rather fix the expense flow properly than append more partial fixes to the situation. Repeating invoices is a really good suggestion I hadn't thought of.

@victorb I'm not sure I understand exactly what you're describing, but we need to tie expenses to users to fulfil accounting and tax obligations. However, perhaps the feature to forward a receipt by email to create an expense (#1862) would help in your use case?

**Comment by victorb** [comment]
@alannallama yeah, expenses tied to users are fine.

Would love to avoid introducing emails into the system, and use API endpoints where possible. Makes development, operations and debugging so much easier compared to dealing with emails.

Repeating invoice won't work for us either, as our costs might be different for each month, and want it to work automatically. Unless we could change the "repeating invoice" options via API, that could work too.

**Comment by xdamman** [comment]
@alannallama it’s not or it’s and. We need to offer more ways for people to file expenses and by offering an api we can enable other developers to build more integrations. That doesn’t mean we shouldn’t also offer a better interface and a better flow to manage expenses on the website.

**Comment by victorb** [comment]
AFAIK, this is still missing. https://github.com/opencollective/opencollective/issues/2725 seems to be touching "Automatic invoices" but not in the same sense as mentioned here (via API endpoints, not UI).

Could be that this issue (#2035) gets solved once the new UI work begins, and endpoints gets created to support the UI work?

**Comment by Betree** [comment]
Pasting the comment I made [here](https://github.com/opencollective/opencollective/issues/1862#issuecomment-576185849) cause is also applies here:

These kind of "integration" issues should, in my opinion, be implemented through Zapier.

Having a more powerful integration with Zapier that allows interactions with Open Collective's API would solve this in a very simple way, while allowing tons of other integrations for free. No need to create custom resolvers, email forwarding addresses...etc all we need to implement this is **the ability to create expenses through Zapier**. Then users just add a "Mail" trigger on Zapier (or webhook, or Dropbox, or whatever works for them to retrieve the invoice) and use an action to create an expense with the attachment.

No need to add any code to configure a new provider.

However if we want to integrate more our API in Zapier we'll need to revamp the project, as what was made for #328 is not sustainable and we're already facing limitations.

**Comment by victorb** [comment]
@Betree I'm pretty sure having a integration with Zapier would first require a normal API endpoint that Zapier can use. And what I have the need of, is just this API endpoint, without having anything to do with Zapier.

**Comment by Betree** [comment]
@victorb Sure, the API endpoint is actually planned with #1326 and should be publicly available in less than 2 months. My point was about the simplicity to create different kind of integrations that Zapier allows.

**Comment by victorb** [comment]
@Betree I was looking at #1326 which lead to #2394 and took a look to find which issue I should subscribe to, so I know when the API endpoint for generating an invoice is done. However, I cannot find any references there about generating invoices via API (in fact, the word "API" is never even mentioned in that issue-thread), could you please point me in the right way?

**Comment by Betree** [comment]
Hi @victorb, this is the right issue to track this change, I'll post an update when the endpoint is ready for public use. Hopefully it shouldn't be too long, we just need a couple of weeks to adapt  the host dashboard and various part of the website for the new concepts introduced with the latest expenses improvements, like the ability to attach multiple attachments.

**Comment by Betree** [comment]
@victorb Our GraphQL V2 API now exposes a `createExpense` mutation that should be safe for you to use. Let me know if you have any feedback!

**Comment by Betree** [comment]
@victorb there may be a breaking refactor before the public release: https://github.com/opencollective/opencollective/issues/3039.

Please let me know if you're actively using this endpoint and need us to soft deprecate.

**Comment by victorb** [comment]
Thanks a lot for letting me know! I couldn't quickly find the GraphQL API docs, so never got too far and didn't have time to dig further into it yet.

So go crazy with breaking changes, at least from my pov :+1:

**Comment by Betree** [comment]
@victorb The GraphQL API described in https://medium.com/open-collective/open-collective-graphql-api-preview-3b42ed1d55ff is normally self-documented, any good client like AltairGraphQL, GraphQL Playground or GraphiQL should show you the docs:

![image](https://user-images.githubusercontent.com/1556356/78765732-afca3800-7988-11ea-999b-5cda440fb19a.png)

**Comment by Betree** [comment]
The `createExpense` mutation is now implemented on our public GraphQL API and should be ready for public use.
