### ISSUE TITLE
Remove deprecated clean-tag package

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2038]
Looks like the package will not be maintained in the future, see:
https://github.com/styled-system/extras/commit/dff7bba235256163ba44942f1c34ded312e39ee2#diff-4bc3019a96ad421bce27a874b0fe80a1

And the last release is breaking, see:
https://github.com/opencollective/opencollective-frontend/pull/1774

What can we use as alternative?

**Comment by znarf** [comment]
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md).

**Comment by yellowwoods12** [comment]
@znarf I am not sure if  I got this issue right. What is the issue in removing that package?

**Comment by znarf** [comment]
@yellowwoods12 Sorry, I don't have much more information now. The person willing to take this issue needs to study what this package is doing and how to do the same thing without it.

**Comment by Shedy151** [comment]
I'm Shadrach from  osca PH i will be working on this...

**Comment by znarf** [comment]
Closed in https://github.com/opencollective/opencollective-frontend/pull/2323
