### ISSUE TITLE
Write a script to populate PaymentMethodId field on `Donations`

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#204]
With the last change, we now store `PaymentMethodId` in `Donation` model. Need a quick script to go back and populate this. 

Note: this isn't required. Mostly for good housekeeping.

**Comment by asood123** [comment]
Along these lines, we need to mark all old `Donation` entries with `isProcessed` as `true` and `processedAt` timestamp as `not null`. Again needed for good housekeeping.

**Comment by piamancini** [comment]
@asood123 do you still need this opened?

**Comment by asood123** [comment]
done.
