### ISSUE TITLE
Can't add funds manually on behalf of existing user

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2042]
**Describe the bug**
As a host admin, I am trying to manually add funds to a Collective that were donated outside the platform, but I'm getting an error because I'm trying to input the email of the admin of the donating organization and she already has an Open Collective user account. 

**Expected behavior**
It seems like the system is expecting her to be able to log in and do this herself, but core contributors don't have access to this feature, only host admins, and host admins need to have the power to add funds manually on behalf of anyone regardless of if they already have an account. It should just associate this manual contribution with her profile automatically.

**Screenshots**
![Screen Shot 2019-05-17 at 5 52 29 PM](https://user-images.githubusercontent.com/5498878/57906088-e01a6b00-78cc-11e9-8b5a-be1ef17ab23f.png)

**Additional context**
This particular situation is a consequence of Collective to Collective transfers being disabled, as we're trying to work around that by using paypal and manually adding funds.

Open Collective UK also recently ran into the same problem.

**Comment by alannallama** [comment]
@piamancini is there a better way to do this? it's a mess.

**Comment by znarf** [comment]
@alannallama can you edit the issue and provide the steps to reproduce (1. 2. 3. ...)

**Comment by alannallama** [comment]
1. Go to add funds
2. Under source, select 'other' to create new
3. Use an email address of an existing registered user
4. See error, can't create source

**Comment by alanna** [comment]
@znarf @Betree I am running into problems with this constantly. Can this please be fixed with priority? If the user already exists, the donation should be attributed to their existing profile, not blocked.

**Comment by piamancini** [comment]
@alanna the way to fix this is to enable you to search all collectives/users/organizations in the source of funds. IT used to be like that, but there was never a search and so finding someone was virtually impossible. 
So @xdamman fixed it by showing only the organizations that already sponsor.  

@xdamman should be able to fix this on Friday, @betree has already too much on plate.  @xdamman can you look at this tomorrow?

**Comment by flickz** [comment]
@znarf Not sure how to fix this without defeating the original purpose for which the check was added, according to the comment in the code:
```js
// Form changes in frontend when trying to create an order with an
// existing email, asking user to login. So if user given in `order.user`
// already exists, that could mean two things:
    // 1. Email is registered under another account as Paypal address.
    // 2. We got a bad payload trying to impersonate another user.
```

**Comment by znarf** [comment]
I would simplify this by moving this `addFund` functionality in a dedicated GraphQL mutation. This is too complicated to have that in the `createOrder` one. It will be an opportunity to remove code from `createOrder` and make it simpler.

After that, in this new mutation, given that the acting user is root/superadmin, we should allow them to do the operation, even if the email is existing.
