### ISSUE TITLE
Logo image broken in update email

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2045]
Update from [this Collective](https://opencollective.com/fisk-vanderbilt-masters-to-phd-bridge-program) is showing a broken logo image.

![Screen Shot 2019-05-18 at 10 56 27 PM](https://user-images.githubusercontent.com/5498878/57968564-5c41ab00-79c0-11e9-8201-79f6815948f2.png)

**Comment by znarf** [comment]
Effectively. Looks like they don't have a logo, should the Open Collective logo be displayed instead (like on the collective page) or should it just be ignored?

**Comment by piamancini** [comment]
Ignored is better to avoid confusion.

**Comment by alanna** [comment]
I think it should just display the Collective's name in text, which also links to the Collective.
