### ISSUE TITLE
Add agreeing to terms to application flow for Open Collective Foundation

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2046]
We need to include agreeing to the terms of fiscal sponsorship to Open Collective Foundation, same as we do for Open Source Collective (e.g. #1991). 

[Here is the document to link to](https://docs.google.com/document/u/2/d/e/2PACX-1vQ_fs7IOojAHaMBKYtaJetlTXJZLnJ7flIWkwxUSQtTkWUMtwFYC2ssb-ooBnT-Ldl6wbVhNQiCkSms/pub).

**Comment by znarf** [comment]
Seems already there in the database.

**Comment by alannallama** [comment]
@znarf I just tested this, and it does not require you to tick a box to agree to the terms. My understanding from @piamancini is we need to get them to tick the box. The terms are linked from the host page but it doesn't ask you to agree to them explicitly.

**Comment by znarf** [comment]
@alanna the ticket was about ensuring it's the same as https://github.com/opencollective/opencollective/issues/1991 In this issue I warned: "please be aware that we're not displaying the checkbox for TOS/TOFS when switching hosts or applying manually."

If this the problem you're talking about, can you create an issue for a feature request and close this one?

**Comment by alanna** [comment]
https://github.com/opencollective/opencollective/issues/2060
