### ISSUE TITLE
Design for webhook administration

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2049]
@cuiki can you provide design input on this administration interface for https://github.com/opencollective/opencollective-frontend/pull/1624 ?

**Empty screen**

![Capture d’écran 2019-05-20 à 12 31 19](https://user-images.githubusercontent.com/806/58027139-4515d100-7b18-11e9-9b92-460fba837324.png)

**Adding a webhook**

![Capture d’écran 2019-05-20 à 16 02 07](https://user-images.githubusercontent.com/806/58027328-aa69c200-7b18-11e9-9076-0172aab69506.png)

**One entry**

![Capture d’écran 2019-05-20 à 12 31 09](https://user-images.githubusercontent.com/806/58027174-5a8afb00-7b18-11e9-9927-ce1b8f5d3db6.png)

**Multiple entries**

![Capture d’écran 2019-05-20 à 16 01 18](https://user-images.githubusercontent.com/806/58027278-902fe400-7b18-11e9-88a3-b8189a2dfbb3.png)

**Comment by cuiki** [comment]
Hi @znarf,  I made a clickable prototype for you guys to get a sense of how it behaves.

Prototype: https://www.figma.com/proto/GF1gQ7fWNfaOAFNwuLeAUl/OC.COM-99-Quick-Fixes?node-id=421%3A610&viewport=-1299%2C230%2C0.5&scaling=min-zoom

Figma FIle: https://www.figma.com/file/GF1gQ7fWNfaOAFNwuLeAUl/OC.COM-99-Quick-Fixes?node-id=420%3A1322

_Note: I'm not entirely sure on where is it that this lives but the page where I placed it is a generic wrapper for the mockup._

**Comment by znarf** [comment]
@cuiki sorry for the delay. I have 2 simple feedback on Figma before this can be integrated

**Comment by znarf** [comment]
![Capture d’écran 2019-06-20 à 15 54 02](https://user-images.githubusercontent.com/806/59854703-b1802c00-9373-11e9-9507-ac5a311ebd6e.png)

**Comment by znarf** [comment]
Implementation can already start without the feedback from the design team.

Just bear in mind that compared to the design:
- you should have the "Edit Collective" navigation on the left
- the title "Webhooks" can stay "Edit Webhooks" and smaller
- You have some flexibility in how you handle the "Save" part (you can look at the "Payment Method" section to get inspiration from)

**Comment by rdinicut** [comment]
@znarf I would like to start on this

**Comment by znarf** [comment]
@rdinicut We're partnering with OSCA this week-end (Open Source Africa) and this bounty will be part of a selection made for the event. If not completed there, you will be able to assign you next week.

**Comment by rdinicut** [comment]
@znarf Awesome. I was wondering what osca is :). Hope all goes well!

**Comment by mikkidollar** [comment]
Hi i am from OSCAFRICA i would like to work on this

**Comment by znarf** [comment]
@mikkidollar it's a big one, maybe try to pair with someone else at the event :-)

**Comment by NotJohs** [comment]
@znarf can I look into this issue?

**Comment by rdinicut** [comment]
@znarf still up for grabs?

**Comment by znarf** [comment]
@NotJohs started last week-end and is still on it

**Comment by NotJohs** [comment]
@znarf finished on Friday but was battle within git :(
over the weekend had to create my own repo, fork it and practice rebase, merge --squash, etc to really understand it.
anyways I made my pr

**Comment by Betree** [comment]
:trophy: This issue is now completed in https://github.com/opencollective/opencollective-frontend/pull/2164 

@NotJohs To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

---

For more info about the bounty process and how to format your invoice, please read https://docs.opencollective.com/help/developers/bounties

**Comment by NotJohs** [comment]
@Betree Thank you.
