### ISSUE TITLE
Improve experience of changing tiers

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2052]
## User story 
As a financial contributor, I want to be able to change tiers without cancelling and re-doing my recurring contribution.

Today we had a user want to upgrade from $10/mo contribution to becoming a gold sponsor of that Collective. This is a really positive thing that we want to encourage, but the UX involves the contributor and the Collective admins getting a sad "sorry to see you go!" email, and the user felt he had to get in touch to explain he was actually increasing support not cancelling it.

Right now your options for a recurring donation are "update payment method" "update amount" or "cancel subscription". None of those addresses the "change tier" experience. 

## Best solution for this problem
I suggest we either add that as its own option, or change "update amount" to "change tier or amount" or something like that, and then let them select from the Collective's tier options or put in a custom amount.

Like this:
![Screen Shot 2019-05-21 at 9 38 45 AM](https://user-images.githubusercontent.com/5498878/58053762-9079bf00-7bac-11e9-9054-220acf28cbd8.png)

**Comment by znarf** [comment]
I think this was addressed in the new Recurring Contributions interface.
