### ISSUE TITLE
Add agreeing to terms in onboarding flow of Open Collective Foundation host

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2060]
*MVP*

We need to require explicitly agreeing to the terms of fiscal sponsorship to the onboarding flow of Open Collective Foundation (same as we already do for Open Source Collective).

[Here is the terms document to link to](https://docs.google.com/document/u/2/d/e/2PACX-1vQ_fs7IOojAHaMBKYtaJetlTXJZLnJ7flIWkwxUSQtTkWUMtwFYC2ssb-ooBnT-Ldl6wbVhNQiCkSms/pub).

*Ideal*

There should be an option for host to require new Collectives to explicitly tick a box to agree to their terms. We already have a setting to link to the terms document, but it should be a toggle like "require Collectives to tick a box explicitly agreeing to these terms when they apply".

**Comment by znarf** [comment]
@alanna I don't see what's specific to Open Collective Foundation host. It's a generic feature request.

**Comment by alanna** [comment]
If we can build the generic feature quickly and easily, great. If that can't be prioritised right now, we need to just turn it on for the Open Collective Foundation.

@piamancini can you please advise about how we should go about this and why the priority of it should be? My understand was we need to implement this right now so all new Collectives coming into c3 host agree to it.

**Comment by znarf** [comment]
Closing in favor of https://github.com/opencollective/opencollective/issues/2072
