### ISSUE TITLE
Differentiate Fiscal Hosts and sponsor Organizations

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2062]
We currently send an onboarding email to new organizations, which was designed for sponsors. I've just realized that new host orgs also get this email, but the content for each needs to be different. 

Here's the current message, which should go to sponsors:

![Screen Shot 2019-05-24 at 10 24 07 AM](https://user-images.githubusercontent.com/5498878/58290499-147eb180-7e0e-11e9-9ecc-1c00b60b391e.png)

---

We need a seperate email for new host orgs.

Suggested text:

> Congratulations on setting up a Fiscal Host!

> The [host dashboard](https://docs.opencollective.com/help/hosts/host-dashboard) is your hub to see all activity, manage Collectives, and pay out expenses. You'll also get email notifications when there are new Collectives or expenses waiting for your approval.

> See our [docs about fiscal hosts](https://docs.opencollective.com/help/hosts) for more details. You might want to check out the sections on [host settings](https://docs.opencollective.com/help/hosts/fiscal-host-settings) and [payouts](https://docs.opencollective.com/help/hosts/payouts).

> Please let us know if you have any questions.

> [Go to your host dashboard]

---

If the organization email is triggered immediately for all new orgs, but some later become hosts, I suggest we put a delay of 24-72 hours on the sponsor one, as they don't need to receive it immediately, and then only send it if that org has not turned into a host. The host email should go out immediately as at that point we know for sure which type they are.

**Comment by znarf** [comment]
I think we need to differentiate more clearly fiscal hosts from organizations. The current definition is really weak: "A fiscal host is an Organization with a connected Stripe account".

**Comment by alanna** [comment]
I wonder if fiscal hosts should be more of a Collective that can contain other Collectives, rather than an organization, because they actually need a transparent budget too, for their host fees income and expenses (see #1723).

**Comment by piamancini** [comment]
There's an argument for a host should be a collective with a stripe account. We should accommodate for hosts who don't want to raise funds themselves (properly handling the look of a collective with no tiers)

**Comment by alanna** [comment]
This issue keeps coming up. It's confusing for design and everyone to have to specify the differences for every change between host orgs and sponsor orgs. They should be seperate things.

**Comment by Betree** [comment]
According to the feedback on #2316, maybe we should introduce two new collective types:
- `HOST`
- `FISCAL_SPONSOR`

**Comment by alanna** [comment]
To stay aligned with the work @xdamman is doing in #2366 I think if there are two types they would be `FISCAL_HOST` and `FUND_HOLDER`. I don't think we should introduce the term `fiscal sponsor` anywhere as it will be confusing (unless we're making the choice to transition all references to `fiscal host` to that, which is a different discussion).

I would argue, however, that the simplest change now that would have the greatest benefit would be to create a type for the existing reality of our system, which would be `FISCAL_HOST`, which is differentiated from `ORGANIZATION`. I would consider all questions about further differentiating self-hosted Collectives and hosts with multiple Collectives under them to be a different topic.

**Comment by znarf** [comment]
We use isHostAccount=TRUE because moving away from User/Organization is to complicated.

**Comment by znarf** [comment]
This is done. Hosts are Users or Organizations that opted in for the Hosts features
- in database: isHostAccount=TRUE
- in GraphQL this can be queried as isHost()
