### ISSUE TITLE
Automatically approved Collectives triggering a "pending" notification in error

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2063]
**Describe the bug**
Collectives automatically approved in the open source GitHub flow also triggering a "pending" notification that confuses users.

The example is [Nox](https://opencollective.com/python-nox), the core contributor of which sent this message:

> I didn't receive a message about confirming the approval was done. I did get one that said my collective was "live" but that was basically immediately, whereas I got the email saying it was pending approval a little later.

It seems like the "live" notification is correct, but the "pending" one is in error, because the Collective was already approved automatically.

**To Reproduce**
Not able to reproduce because I have to connect a GitHub repo of 100+ stars to test it.

**Expected behavior**
Collectives which are automatically immediately approved should not trigger a "pending" email, only the notification that the Collective is live.

**Comment by znarf** [comment]
I think this is already opened as an issue.

**Comment by znarf** [comment]
This is it: https://github.com/opencollective/opencollective/issues/1984
