### ISSUE TITLE
Avatar image not showing up

### ISSUE THREAD

**Issue by kasbah** [opencollective/opencollective#2065]
**Describe the bug**
Avatar image for my collective is not showing up on header and main page though it appears to be there in settings. 

If you go to console you can see an error 500 in requesting resource: 
https://images.opencollective.com/proxy/images?src=https%3A%2F%2Fopencollective-production.s3-us-west-1.amazonaws.com%2F65c1bc20-e37e-11e8-bdd6-c7e0e2e838bb.png&height=640 

**To Reproduce**
1. Go to https://opencollective.com/kitspace
4. See default avatar

**Expected behavior**
See custom avatar.

**Screenshots**

![image](https://user-images.githubusercontent.com/206854/58336224-e1024e00-7e32-11e9-89ec-02695c9180e5.png)

**Comment by znarf** [comment]
We had some trouble this week with our images service, especially yesterday.

This is working as expected now, but we'll be performing some work next week to make it more stable.
