### ISSUE TITLE
Deleting a collective with expenses crashes the host dashboard

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2067]
A collective/event, `xr-hackney-july-uprising-42829ev`, was recently deleted with an `APPROVED` expense (id=8149). Deleting collectives is only blocked if an expense has been paid.

As a consequence, the host dashboard is crashing as it expect all expenses to have a `collective` attached. The crash occurs on this line: https://github.com/opencollective/opencollective-frontend/blob/d0721a8c15a4f03075ead849747ddd188abe163a/src/apps/expenses/components/Expense.js#L312

To ensure that no other expenses is affected:

```sql
SELECT * FROM "Expenses" e
INNER JOIN "Collectives" c ON c.id = e."CollectiveId"
WHERE c."deletedAt" IS NOT NULL
AND e."deletedAt" IS NULL
```

---

Slack report: https://opencollective.slack.com/archives/C6JTTA4SK/p1558886890003500
Freshdesk ticket: https://opencollective.freshdesk.com/a/tickets/534

**Comment by alanna** [comment]
Another outcome was that the funds in the event's balance just disappeared - were not paid out or replaced in the Collective's balance. The user contacted support [here](https://opencollective.freshdesk.com/a/tickets/526).

**Comment by znarf** [comment]
As a first quick action, we need to remove the the ability to delete events. Until done properly.
