### ISSUE TITLE
Turn off email notifications for automatically approved Collectives

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2068]
## User story 
As a host admin, I want to only get emails for Collective applications I need to action, so I don't lose important ones in a sea of unnecessary emails.

## Best solution for this problem
Do not trigger a "[Collective] would love to join Open Source Collective" email notification for open source Collectives automatically approved via the GitHub stars verification flow. 

That way, I will know that if I get an email, I need to actually look at it and do something because the Collective is pending. Right now, I have to filter all those emails because otherwise I'm overwhelmed with notifications I do not need to action. I want to be able to remove the filter.

## MVP
Maybe send another different notification if a Collective has been pending for more than 1 hour? That's probably no more minimal than the other idea, though.

## Metrics 
Fewer Collectives stuck in pending unnoticed for a long period of time. Fewer support requests from users wondering the status of their application.

**Comment by flickz** [comment]
> Do not trigger a "[Collective] would love to join Open Source Collective" email notification for open source Collectives automatically approved via the GitHub stars verification flow.

Looks like this issue requires more than this?

> Maybe send another different notification if a Collective has been pending for more than 1 hour?

@znarf Can you help make a spec for this?

**Comment by znarf** [comment]
> Maybe send another different notification if a Collective has been pending for more than 1 hour?

We will not do that.

I think we're good with https://github.com/opencollective/opencollective-api/pull/2037

**Comment by flickz** [comment]
I think we're good here then.

**Comment by znarf** [comment]
@flickz we should disable the COLLECTIVE_APPLY notification for collectives automatically activated in the "GitHub flow"

**Comment by flickz** [comment]
I'm on it
