### ISSUE TITLE
Some Open Source Collectives are not being automatically approved even with 100+ stars

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2069]
**Describe the bug**
[This Collective](https://opencollective.com/taskbook) applied to Open Source Collective. [Their repo](https://github.com/klaussinani/taskbook) has over 100 stars (over 6000 actually). But it got stuck in 'pending' instead of being automatically approved.

**To Reproduce**
This is only happening occasionally so I don't know how to reproduce. Is it possible to look at the system logs for this Collective's application and see what happened?

**Expected behavior**
Collectives with over 100 GitHub stars should be automatically approved to join the Open Source Collective.

**Comment by alanna** [comment]
Here's another example: [Single-Spa](https://opencollective.com/single-spa), which has [2400 stars on their repo](https://github.com/CanopyTax/single-spa), was stuck in the manual pending queue.

**Comment by znarf** [comment]
If they use the GitHub flow, it should works automatically. If they apply manually, then it's the manual process.

**Comment by alanna** [comment]
Ah ok, so you think they failed to go through the GitHub process and ended up in the manual one? How would that happen? If they didn't identify as an open source project in the flow?

This wouldn't be such a bad problem if #2068 wasn't an issue, but currently Collectives who don't go through the automatic flow for Open Source Collective are very likely to get lost.

**Comment by znarf** [comment]
Good news, https://github.com/opencollective/opencollective/issues/2068 is almost fixed.

**Comment by alanna** [comment]
This will become more manageable with #2068 - so I will close this issue.
