### ISSUE TITLE
Host admin unable to access refund button

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2070]
**Describe the bug**
Conrad, admin of the Operation Code fiscal host, does not see a refund button when looking at a contribution.

It's supposed to look like this:

![unnamed](https://user-images.githubusercontent.com/5498878/58441904-2d52d400-813a-11e9-9ade-17ad2483ec3b.png)

But he sees this:

<img width="1127" alt="Screen Shot 2019-05-27 at 3 03 30 PM" src="https://user-images.githubusercontent.com/5498878/58441909-3c398680-813a-11e9-8b0b-6240aa669b65.png">

**Expected behavior**
Host admins should be able to refund contributions to Collectives in their host.

**Comment by znarf** [comment]
Because ```canRefund={LoggedInUser && LoggedInUser.isRoot()}``` in `Transaction.js`.

`isRoot` in reality means the authenticated user is an admin of [opencollective](https://opencollective.com/opencollective).

We need to change this condition and also check (`OR`) if the authenticated user is an admin of the host. While doing that, we also need to double check similar permissions in the API.

**Comment by piamancini** [comment]
yes, we need to make this available to other host admins. right now is only done for us.

**Comment by alanna** [comment]
@znarf - The admin from Operation Code is still unable to see the refund button. This issue indicates he should be able to see it now, right?

**Comment by znarf** [comment]
@alanna Let's follow up in #support. To troubleshoot, I need the account of the user trying to refund.

**Comment by znarf** [comment]
@alanna might have found the problem

@flickz please check the comments on https://github.com/opencollective/opencollective-frontend/pull/1864 and fix that.

**Comment by znarf** [comment]
@alanna can you confirm it's working now?

**Comment by alanna** [comment]
User confirmed this is fixed for them

**Comment by alanna** [comment]
Another host admin is unable to see the refund button. This time it's [Ludovic](https://opencollective.com/ldubost) from [XWiki SAS](https://opencollective.com/xwikisas).

**Comment by znarf** [comment]
I tested and this should work. Let's continue in the support channel.
