### ISSUE TITLE
Add details option on "orders" view

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2071]
## User story 
As an admin, I want to be able to see details of an order/transaction regardless of how I got to it, so I can take actions such as refund.

## Best solution for this problem
Right now if you click on an order on the host dashboard, it takes you to an 'order' page, like this: https://opencollective.com/companion/orders/45947

If you find the same order via going to the Collective page and clicking "all transactions" (ex: https://opencollective.com/companion/transactions), you cannot click on it to go to its own page, but you can click "view details". From there you can see the breakdown of fees and also refund.

This is confusing and seems strange to have it treated different in different views. It makes it harder for host admins to access the functions and info they need.

## MVP
Add a "view details" option to orders that appear on the dashboard, which displays the same options and "view details" on a transaction.

**Comment by flickz** [comment]
@alanna What exact information will be shown in details?

**Comment by alanna** [comment]
The same info you can see if you click "view details" from the transactions view.

![Screen Shot 2019-11-29 at 2 47 01 PM](https://user-images.githubusercontent.com/5498878/69838158-31ada480-12b7-11ea-83ae-1b6244f0eceb.png)

**Comment by flickz** [comment]
@alanna I have a PR for this now but it is only displaying "CREDIT" transaction details, I feel it makes sense to display only that because it's an order not expense, is that okay?

<img width="642" alt="Screenshot 2019-12-02 at 9 54 55 AM" src="https://user-images.githubusercontent.com/15707013/69945432-cd265b80-14e9-11ea-88d9-4983ee600f19.png">

**Comment by alanna** [comment]
Yes that looks good.
