### ISSUE TITLE
Turn on bank transfer contributions for Open Source Collective & other hosts?

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2075]
## User story 
As a financial contributor, I want to easily set up payments to Collectives via bank transfer, so I can send larger amounts and not have to use a credit card.

As a host admin, I want to have help from the system making manual payments easier and less error prone, so we can provide better service.

As a Collective, I want to enable all possible ways for people to give money, so I can increase the budget.

## Best solution for this problem
Right now the 'bank transfer' option is a selectable payment type for Open Collective EU and a few other hosts. We could turn that on for more hosts, including Open Source Collective. This provides a semi-automated solution, when the financial contributor sets up the transaction and is sent the bank transfer info automatically by email. When the funds arrive, the host admin marks it as paid and the Collective is automatically credited.

## Discussion
I'm worried that if we enable bank transfer as an option for Open Source Collective, people will start trying to use it for lots of tiny payments or recurring monthly payments, and it will end up taking a lot of time to manually match all the transactions. Currently we only accept manual payments for large, infrequent amounts.

I'm also not clear on what kind of fees we would be paying for accepting a lot of wire transfers. I suspect this was only turned on in Europe because bank transfers are much easier, cheaper, and more common there than in the US.

@xdamman explained to me:

> When people select “wire transfer” as payment method, it records a pending donation and it sends them an email with the instructions to make the wire to the host with a special communication that we can use to track the Order ID. Then once the hosts confirms that the payment has been received, they just need to “mark it as paid” in their dashboard and that’s it.
Otherwise it’s a pain to create a profile for the donor when adding funds.

Xavier can you comment on this idea?

**Comment by xdamman** [comment]
I think it's a great idea.
I'd just turn it on for payments of more than $10k to start (or $5k?) 

The only thing is that we should make it clear that this option is there but only available for one time payments of a certain amount (same for paypal btw, otherwise people wonder: "why is this option not always there?" So better to always show it but greyed out with a small explanation: "This payment method is only available for one time payments of minimum $10k")

**Comment by alanna** [comment]
OK, so a good first step could be to turn on bank transfers for Open Source Collective for one-off contributions only, for transactions over $x ($2000 seems like a good threshold to me).

What would be involved in doing this? @znarf since the code already exists for OCEU, is it easy to turn on for OSC, with those criteria in place?

**Comment by xdamman** [comment]
The only thing that will need to be added is:
- the concept of threshold 
- a bit of design to know how to display when the condition / threshold is not met (would be good to show it even for recurring contributions but with a message that says: "wire transfers are only available for one time donations of over $2,000")

**Comment by piamancini** [comment]
This can potentially be handled by Stripe @alanna (albeit only for the US) - Let's discuss.

**Comment by alanna** [comment]
Bank transfer payment option has been turned on for OSC
