### ISSUE TITLE
Can't make a one time donation with decimals

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2079]
Step to reproduce:
Go to opencollective.com/europe-collective/donate
Pick a profile, then enter "143.20". You can play with the plus/minus controls. 
Select "Wire transfer", then click on "contribute"
500 error

Error in the API logs:

```
2019-05-31T09:31:28.881161+00:00 app[web.1]: error: GraphQL v1 error: Variable "$order" got invalid value {"paymentMethod":{"type":"manual"},"totalAmount":14319.999999999998,"taxAmount":0,"quantity":1,"currency":"EUR","interval":null,"fromCollective":{"id":37416,"type":"COLLECTIVE","name":"G4G"},"collective":{"id":868},"description":""};
Expected type Int at value.totalAmount; Int cannot represent non-integer value: 14319.999999999998
```

The process is still very broken, I just want to be able to do /:collective/donate/:amount/:description

It's still not working for amounts with decimals

**Comment by znarf** [comment]
The issue is first about opencollective.com/europe-collective/donate then /:collective/donate/:amount/:description. It's confusing.

**Comment by xdamman** [comment]
It’s the same issue. Basically no matter the collective there is no way to make a donation with decimals. 
This should work whether you specify the amount in the interface or in the url.

**Comment by flickz** [comment]
@xdamman This is a JavaScript issue we forgot (or didn't realize) to handle properly, in JavaScript the result of `143.20 * 100` equals ` 14319.999999999998`, this should have been rounded up to `14320` as expected by the API. Have opened [#1874](https://github.com/opencollective/opencollective-frontend/pull/1874) to fix it.
