### ISSUE TITLE
Make it easier to contact host admins

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2080]
## User story 
As a fellow host admin, I need to contact other host admins about transfers of funds.

As a prospective Collective, I need to follow up on fiscal hosting applications.

As a sponsor, I need to know who to contact regarding agreements and transfers of funds.

This is kind of related to #1955 and #1849 but neither specifically solves contacting host admins.

Even by searching in Forest it's still really hard to track down host admin emails as a superadmin. Much less regular users who need to get in touch.

## Best solution for this problem
A "contact fiscal host" button on every fiscal host page, which takes you to a message form.

## MVP
Make the info@[slug].opencollective.com format work for hosts like it does for Collectives, and automatically display that address on every host page.

**Comment by Betree** [comment]
@raulgrafico Let's make sure we take this into account for the new profiles.
