### ISSUE TITLE
Simplify events

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2081]
We currently have an events feature that was implemented by kind of treating an event as a mini-Collective. We have had issues with it, like:

* Events have their own seperate budget, and expenses submitted to it weren't showing up in the regular host dashboard workflow to be paid.
* Deleting an event with transactions is like deleting a Collective, and it messed up the ledger when it happened (which is why we only allow archiving of Collectives with transactions).

It was suggested that we just get rid of events, but I don't want that to happen because it's a useful feature, and a revenue stream for Collectives and the platform.

I think we can re-implement events much more simply: instead of being like a whole Collective, an event can just be a grouping of tiers. 

* Click 'create event' on your Collective page
* Put in the name, description, date & time, location
* Upload image for header (optional)
* Create tickets
  * Name
  * Description
  * Price (can be $0)
  * Available quantity (can be unlimited)

Each ticket option creates a tier. These tiers do not show up on the main page, only that specific event page. The event page displays the info you put in, plus the tiers associated with that event. When the event date has passed, those tiers deactivate.

**Add:** a "message participants" button on the event page, which loads a similar form to creating an Update, and sends the message only to people who have backed those event ticket tiers when you publish it.

**Remove:** templates, intervals and ticket types. You cannot have a recurring contribution to an event tier, only one-time. It's much better to have a smaller set of options properly implemented than a larger set partially implemented (as these were). 

Differences to current implementation:

* Events will not have a seperate budget from the rest of the Collective - expenses for an event will be submitted to the main Collective budget.
* Events can be deleted, but the underlying transactions remain because they are contributions to a given tier, while the event is just a way to group those tiers on a page.
* No repeating events - create a new one each time (this is MVP!).

**Comment by alanna** [comment]
Another issue caused by events being treated as Collectives: #2083 - it counts them wrongly in the  total number of Collectives in a host.

**Comment by alanna** [comment]
Some metrics to back up the argument to keep events:

We have had about **300 events** bring in **$23,500** through the platform via **1210 tickets** sold.

Usage of events is trending steadily up:
<img width="358" alt="Screen Shot 2019-06-05 at 2 02 36 PM" src="https://user-images.githubusercontent.com/5498878/58925501-d6817600-879b-11e9-8f31-12354a3fb5c8.png">

We are getting increasing requests via support to interface with payments from Eventbrite and other external event platforms. Open Collective can't compete as a fully-featured events tool, but if we improve how events work, I think more people will use our tool to keep everything in one place unless they need advanced functionality.

**Comment by xdamman** [comment]
I agree that events need some love.
But a set of tiers as you say, already exists and it’s called a « collective ». 
I’d rather keep the number of concepts as small as possible to reduce the complexity of the system.

The bugs you mentioned are bugs and should be solved. Changing the way it works won’t make things simpler, and will introduce new problems.

So the only difference I see is the problem of keeping a separate ledger for the event.
Can you explain more why is that an issue?
There is already a big banner at the top after the event is passed to invite the admins to move any remaining balance to the parent collective.
From my personal experience, it has been quite useful to know how much « profit » does an event generate and how much it has cost. It would also be quite noisy to see all the individual transactions for each ticket sale. Also, if the collective uses EventBrite, they receive the total amount of the proceeds and they record them once. Which is quite clean.

After interviewing Eli from NetSquared that is a big user of events, he loved the idea of templates but he would love to have some templates at the host level that any hosted collective could re-use.

So the few changes that I think could help here:
- When filing an expense, suggest to attach it to an event if one is on going or still has a positive balance (it’s not clear today that you should file those expenses directly in the event)
- simplify tiers for events, as you say it makes no sense to have recurring contributions there
- Fix the bugs you mentioned
- Allow to remove an event and move the balance if any to the parent collective (which has already been implemented, it’s just a front end option to add)

**Comment by alanna** [comment]
I think that making events a whole other Collective is way more complex. If someone wants a whole seperate Collective, let them create a seperate Collective. Don't frankenstein it into the way existing Collectives work. We made a call recently that goals should not have seperate budgets, specifically because of the complexity it introduces (for example, not knowing which budget to submit an expense against, which you mention people already being confused about for events), and I think the same logic applies to events.

Yes, it's super useful to have budget tracking for individual projects, which is kind of what you're trying to achieve by giving events a seperate budget. If we want to make the possible, let's design and implement it fully, giving Collectives the ability to add tags or categories to expenses and tools for reporting on those within the larger budget. Why should events be treated specially, when this functionality is useful for all kinds of contexts? In my experience of financial admin, it's *way* better to have tracking codes within one larger budget than to try to achieve the same functionality using multiple seperate accounts.

But I don't see project tracking and budget sub-division as a priority right now, given all the things we need to do, so this proposal was about simplifying how events work so we can keep them at all.

**Comment by alanna** [comment]
Discussed in meeting.

@piamancini : events have been frustrating but we should find a way to keep them

@znarf : it would be better to integrate with an external events platform

@Betree : it might lead us to make good improvements to tiers like collecting extra info

Decision: events isn't the priority right now (new collective page and expense flow is more important), maybe Alanna and @pietgeursen can work on it after taxes.

**Comment by xdamman** [comment]
+1 on @znarf’s idea of better integrating with 3rd party event systems.

Independently of that I think it’s a good idea to add tags to tiers and to expenses and something to keep in mind as we are redesigning those components.

**Comment by Dumzicoders** [comment]
I am from OSCA PH

**Comment by znarf** [comment]
@Dumzicoders There is no bounty on this issue. It's not solvable.

**Comment by alanna** [comment]
Another reason events shouldn't be seperate Collectives: we can't manually add funds to them as a host admin. Instead they should be treated as tiers, and host admins should be able to manually add funds to a tier.

**Comment by xdamman** [comment]
Using tier goals for https://opencollective.com/Xr-Belgium, we now have the opposite problem. We actually want to file expenses and link them to that tier and we want to know how much is left of that money we raised. This would have been much easier if a tier was actually a sub collective like an event is. Also given that this fundraising tier was initiated by the Food Working Group, I’d have loved to delegate the approval process to the locomotive (leader) of that working group. Here again we would have gotten that for free if a tier was a collective. 

And you can easily transpose all those arguments to the concept of event. Which is a tier with a date and location. 

[“A complex system that works is invariably found to have evolved from a simple system that worked”](https://twitter.com/xdamman/status/808073136231084032?s=21). That’s why I’m a big believer in fractals. We should simplify everything by considering everything as a collective. That’s how we can get to essence of what we do. But it takes time to get there. “You reach perfection once there is nothing left you can remove”. If we truly do that, then of course we should also make sure that you can add funds to an event in the same way that you can add fund to any collective that you host (so your point is very valid, I just wanted to offer another perspective on how to solve it by reducing complexity)

**Comment by Betree** [comment]
> Another reason events shouldn't be seperate Collectives: we can't manually add funds to them as a host admin. Instead they should be treated as tiers, and host admins should be able to manually add funds to a tier.

That sounds like something that should be possible. Why can't we?

Overall, I strongly agree with https://github.com/opencollective/opencollective/issues/2081#issuecomment-499459235. There are many bugs that we need to solve with events, but I don't think that revamping their underlying structure is an easy solution to solve them, and it will probably introduce new challenges. Event's issues do not come so much from the way it's designed, but from the fact that we don't invest in that feature - we barely maintain it to make sure it keeps working.

Treating events as collectives gives us many features for free: the collective page, a clear budget, transactions list, updates, etc. Revamping that means that we will lose most of the intelligence that has already been built to support important things; It means re-implementing a new page to show the event time/timezone, location, to adapt all the template emails, to re-implement the permissions for events, to re-implement all the tests. That's a massive complexity, and the gain/cost doesn't seem positive to me.

Finally, and I think this is important for this discussion, the "PROJECT" collective types have been built with the same basis as events (same notion of "parent collective", with permissions being checked on the parent). So we're now capitalizing on this design pattern: any change to projects is usually available to events for free. Example: I've made the updates feature available for projects 2 weeks ago, now [enabling that for events](#4122) is a one-line change.

So, two years after and with the way our model currently look, I now think that the balance clearly tends toward improving the existing system rather than revamping it.

**Comment by alanna** [comment]
This issue is super out of date but still has some useful comments. I no longer think my original idea is the right one. I think we should take a giant step back and realise that the functionality of Projects and Events is overlapping, and we should properly understand their functions and design a more elegant approach. Related: #4075 #4074
