### ISSUE TITLE
[API] Return internal error

### ISSUE THREAD

**Issue by Johann-S** [opencollective/opencollective#2082]
**Describe the bug**

Hi, when we call your API it returns a `500` error code

**To Reproduce**
1. Go to https://opencollective.com/bootstrap/members/all.json?TierId=7192
2. See error

**Expected behavior**

Return our sponsors

**Desktop :**
 - OS: Win 10
 - Browsers: All

**Comment by znarf** [comment]
@Johann-S sorry for that, fix coming.

Curious, where are you using this endpoint? I would love to help you migrate to our new GraphQL API.

**Comment by Johann-S** [comment]
Hi @znarf,

It's a draft PR here: https://github.com/twbs/bootstrap/pull/28744 we work on a thanks page

**Comment by znarf** [comment]
@Johann-S Cool.

The issue is fixed and deployed, that was due to an internal GraphQL update which was more strict with parameters. https://github.com/opencollective/opencollective-rest/pull/19/files

**Comment by Johann-S** [comment]
Great ! thanks
