### ISSUE TITLE
In host report email, events are counted in the totalCollectives

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2083]
In the host-report email, events are counted in the `totalCollectives`. This is confusing, hosts are not expecting events to be counted as collectives.

See: https://github.com/opencollective/opencollective-api/blob/d6b5255ab3b6fd2384e231b1100ddff1538f6c89/reports/host-report.js#L235

Can be reproduced with https://opencollective.com/ryan-petroff hosting 1 collective with several events https://opencollective.com/opentorontoschool

**Comment by piamancini** [comment]
@xdamman can you put this on your list for Friday?
