### ISSUE TITLE
Network error when adding funds manually

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2085]
**Describe the bug**
Unable to add funds to Collective manually due to: "Network error: Response not successful: Received status code 500"

**To Reproduce**
1. Go to Foundation host dashboard
2. Select Drupal Ashville
3. Click add funds
4. Put in $441.75 from Eventbrite
5. Click 'add funds"

**Screenshots**

![Screen Shot 2019-06-04 at 10 35 39 AM](https://user-images.githubusercontent.com/5498878/58839155-f2f6b300-86b4-11e9-8a92-0856b0c6a3c2.png)

**Comment by znarf** [comment]
```GraphQL v1 error: Variable "$order" got invalid value { totalAmount: 44175, description: "ticket sales", hostFeePercent: 5, platformFeePercent: 5, collective: { id: 19540 }, fromCollective: { id: "10881" }, paymentMethod: { uuid: "3df4cc6d-8598-4edf-8b7f-61adb61cf463" } }; Expected type Int at value.fromCollective.id; Int cannot represent non-integer value: "10881"```

**Comment by znarf** [comment]
Should be fixed by https://github.com/opencollective/opencollective-frontend/pull/1891

**Comment by alanna** [comment]
This has been fixed
