### ISSUE TITLE
Github oauth is broken

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#209]
It errors out with redirect-uri-mismatch. 

On github, we have registered `https://api.opencollective.com/connected-accounts/github/callback`. 

In our requests, we are sending `https://prod-opencollective-api.herokuapp.com/connected-accounts/github/callback`.

The `herokuapp` url is coming from `API_URL` in heroku settings. Changing that to `api.opencollective.com` triggers a cloudflare alert breaking the flow altogether:

`You've requested a page on a website (api.opencollective.com) that is on the CloudFlare network. Unfortunately, it is resolving to an IP address that is creating a conflict within CloudFlare's system.`

**Comment by asood123** [comment]
I'm also curious why this happened now and how long the mismatch has existed?

**Comment by piamancini** [comment]
I haven't received any complaints but also, I haven't seen new OS from the integration in a while.

**Comment by sedubois** [comment]
This might be it: https://github.com/OpenCollective/opencollective-api/pull/533

**Comment by asood123** [comment]
fixed with that revert.
