### ISSUE TITLE
non active collectives shouldn't show up in the host dashboard

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2091]
when a collective applies to a host, we create a row on the member table and we add the host as the collective's hostId but we don't activate them (isActive=FALSE)

The problem is that we still show these collectives in the host dashboard (dropdown menu). We shouldn't surface collectives on the dashboard until they are approved by the host.

**Comment by znarf** [comment]
Linked to: https://github.com/opencollective/opencollective/issues/1878 The API might help.

**Comment by piamancini** [comment]
I think this was fixed by @xdamman. Xavier please confirm?

**Comment by xdamman** [comment]
Yes it’s fixed
