### ISSUE TITLE
Fix propTypes in the frontend codebase

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2095]
In the frontend codebase we rely on PropTypes to check parameters passed to React components.

We have an eslint rule setup to warn us when we're missing PropTypes. However, there is still plenty of warnings. For this bounty to be solved, they all need to be fixed (only the `react/prop-types` of course). Check `npm run lint`. 

Also, when running `e2e` test, there is is still some PropTypes warnings (generated by the runtime, not eslint). They also need to be fixed. To confirm that, you can just check the output of `e2e` tests at CircleCI.

This bounty has a simple complexity and is beginner friendly.

- [x] fix all `react/prop-types` eslint warnings when running `npm run lint`
- [x] fix all "Failed prop type" warnings surfaced when running `npm run test:e2e`

**Comment by leonardohof** [comment]
@znarf Can I assign to myself this issue?

**Comment by znarf** [comment]
@leonardohof Sounds good. Looks like you already accomplished the first part!

**Comment by leonardohof** [comment]
> @leonardohof Sounds good. Looks like you already accomplished the first part!

I'm having problems to fix the **withFallbackImage.js** file.
Could you give me some help?

I tried to change to this:
`import React from 'react';
import PropTypes from 'prop-types';
import { defaultImage } from '../constants/collectives';
import { getDomain, imagePreview } from './utils';

function withFallbackImage(ChildComponent) {
  return class extends React.Component {
    static displayName = `withFallbackImage(${ChildComponent.displayName})`;
    static propTypes = {
      src: PropTypes.string,
      type: PropTypes.string,
      radius: PropTypes.number,
      height: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
      website: PropTypes.string,
      name: PropTypes.string,
    };

    constructor(props) {
      super(props);
    }

    render() {
      const { radius, height, website, name } = this.props;
      let { type = 'USER', src } = this.props;

      if (name === 'anonymous') {
        type = name.toUpperCase();
      }

      const fallback = defaultImage[type];

      if (!src && website && type === 'ORGANIZATION') {
        src = `https://logo.clearbit.com/${getDomain(website)}`;
      }

      let image;
      if (!src) {
        image = fallback;
      } else {
        image = imagePreview(src, fallback, {
          width: radius,
          height,
        });
      }

      if (image && image !== fallback) {
        if (process.browser) {
          const img = new Image();
          img.src = image;
          img.addEventListener('error', () => {
            src = fallback;
          });
        }
      }

      const childProps = {
        ...this.props,
        src: image,
        height,
        radius,
        type,
        name,
      };

      return <ChildComponent {...childProps} />;
    }
  };
}

export default withFallbackImage;
`

**Comment by znarf** [comment]
Thank you @leonardohof ! It's merged.

To claim the bounty, you can:

a) submit an invoice to https://opencollective.com/engineering
b) or ask for an Open Collective gift card of the same value (to donate to other collectives)
