### ISSUE TITLE
Empty Balance button is not showing up

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2096]
Reported by TechSoup Admin

Hi! I’m trying to shut down a collective using the guide at 

https://github.com/opencollective/documentation/blob/master/collectives/zero-collective-balance.md

However, I’m not seeing the “Empty Balance’ button” on my Collective.

https://opencollective.com/net2van-meetup

<img width="1130" alt="NetSquared_Vancouver__Net2van__-_Open_Collective" src="https://user-images.githubusercontent.com/3671070/58959459-7394dc80-87a5-11e9-9379-496020cc22cd.png">

**Comment by znarf** [comment]
@piamancini The host doesn't have an "host collective" setup.

**Comment by piamancini** [comment]
Oh I see.  So how can I link a host collective to a host?

**Comment by znarf** [comment]
We had an hostCollective entry in their settings. ie: `hostCollective":{"id": 40817},`

I can do it.

**Comment by piamancini** [comment]
why is the button not showing up with the option of vacating funds to another collective under the same host?
They way it could work is: 
Button shows up / surface the list of collectives under the same host + an option to create a collective for the host is there's not one already surfaced.

**Comment by znarf** [comment]
Why not, we "just" need to build it.

But if they want, they can already donate to this collective using the contribution flow.

**Comment by piamancini** [comment]
I note a shade of sarcasm there :D

**Comment by elijahv** [comment]
Hi friends, I've now created the "host" collective at https://opencollective.com/netsquared-administrative-collective/

Can you now set things up so that I can use the "Empty Balance" feature. 

I'm failing in my attempts at transfering funds to another collective because currency conversions make this a very hard project.

@piamancini  can you help here?

**Comment by znarf** [comment]
@elijahv done

**Comment by elijahv** [comment]
Thanks! We're making progress. When I click the button I'm getting a "Invalid currency. Expected USD." error. 
<img width="852" alt="Screenshot_2019-06-27__7_15_AM" src="https://user-images.githubusercontent.com/3868907/60273696-85046c80-98ab-11e9-88be-e2b979ef48e1.png">

URL: https://opencollective.com/techforgoodnz/edit/advanced

**Comment by znarf** [comment]
With the release of https://github.com/opencollective/opencollective-frontend/pull/2614 we will better understand when the "Empty Balance" will not be there. Closing.
