### ISSUE TITLE
Error when pledging collective

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2098]
**Describe the bug**
An error about payment method shows up when creating a new pledge. A second click on the submit button **does** create the pledge.

**To Reproduce**
1. Go to http://staging.opencollective.com/pledges/new
2. Fill the form with valid values
3. Click on `Make pledge`
4. See error:

![image](https://user-images.githubusercontent.com/1556356/58977613-60483800-87ca-11e9-8ad6-808412047ec3.png)

**Comment by Betree** [comment]
Just merged https://github.com/opencollective/opencollective-frontend/pull/1877 so we don't have conflicting code when fixing this. https://github.com/opencollective/opencollective-frontend/pull/1877 is not the cause of this issue as it appears with and without it.

**Comment by flickz** [comment]
Close in [#2118](https://github.com/opencollective/opencollective-api/pull/2118)
