### ISSUE TITLE
intermittent 503 errors when paying expenses

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2099]
**Describe the bug**
``` {"response":"<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>503 Service Temporarily Unavailable</title>\n</head><body>\n<h1>Service Temporarily Unavailable</h1>\n<p>The server is temporarily unable to service your\nrequest due to maintenance downtime or capacity\nproblems. Please try again later.</p>\n</body></html>\n","httpStatusCode":503}```

**To Reproduce**
Hard to reproduce because it's intermittent. When I try to pay the same expense again, it went through, but then the same error happened on another one, repeat.

**Comment by znarf** [comment]
@alanna next time it occurs, would be great if you could note the exact time (to the second precision)
