### ISSUE TITLE
Stickers for backers

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#21]
Backers of a collective should receive a sticker with the logo of the collective and the date of when they started supporting the collective.

Let's brainstorm a few ideas here.

**Comment by piamancini** [comment]
we need to build an instance in our flow where we ask for the address. 
We shouldn't store that information in our db.

**Comment by erickrico** [comment]
Hey, this are the sponsor stickers as well as a few variations of brand ones, ill attach the original an a couple imgs, feel free to post feedback 😬 
![screen shot 2016-04-12 at 4 28 46 pm](https://cloud.githubusercontent.com/assets/18429104/14476145/a7545514-00cb-11e6-97ce-22cc541ee670.png)
![screen shot 2016-04-12 at 4 27 31 pm](https://cloud.githubusercontent.com/assets/18429104/14476143/a75182c6-00cb-11e6-9b28-f4f31a105bbe.png)
![screen shot 2016-04-12 at 4 27 12 pm](https://cloud.githubusercontent.com/assets/18429104/14476144/a751c722-00cb-11e6-81d8-d60af22586c0.png)

**Comment by boneskull** [comment]
:+1: for the angled stickers.  the third sticker (yeoman) looks too much like
![image](https://cloud.githubusercontent.com/assets/924465/14477634/0ff301cc-00c4-11e6-8adb-1f53cbca7e3e.png)

**Comment by piamancini** [comment]
Closing this since we have a design already and we are not pursuing this for the moment.
