### ISSUE TITLE
parentCollectiveId preventing host to be removed

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2101]
In the GitHub flow, we're setting the `parentCollectiveId` of all collectives to `83`. This is later preventing hosts to be removed.

**To Reproduce**

1. Go to http://opencollective.com/opensource/apply
2. Create a new collective
3. Edit the newly created collective
4. Go to the Fiscal Host section
4. Remove the host

**Current behavior**

The host doesn't appear to be removed.

**Expected behavior**

The host should be removed.

**Resolution**

- [ ] Seems `parentCollectiveId` is not useful here, so we should stop setting that.
- [ ] We should fix all impacted entries in the database
  - [ ] parentCollectiveId=83 (open source)
  - [ ] parentCollectiveId=858 (meetups)

**Feedback**

- [ ] before proceeding, check first with @xdamman, because he might know the original intent

**Comment by xdamman** [comment]
It’s on purpose.
It’s to make sure that all open source collectives are listed on https://opencollective.com/opensource (which is the Parent Collective).

That shouldn’t prevent collectives from changing host. In fact, that’s exactly the point of this `ParentCollectiveId`, making sure that we can gather different collectives that may be on different hosts in one place.

**Comment by piamancini** [comment]
Parent collectiveID is used to group the collectives under an umbrella organization - in this case the open source collective collective: opencollective.com/opensource Since this is now duplicating opencollective.com/opensourcecollective and we now group using tags, I think it's safe to remove it. 

@alanna if this is done, we should swap the slugs so the collective can ben opencollective.com/opensourcecollective (now the host) and the host can be opencollective.com/opensource (now the collective)

**Comment by znarf** [comment]
@xdamman How confusing is that. Surfacing a Collective on a host when it's not hosted there. Let's stop that.

**Comment by xdamman** [comment]
It’s not surfacing a collective on a host, but on another collective that acts as a “super collective”.
Another recent example: https://opencollective.com/drupal-collectives
https://opencollective.com/meetups is another good example. Clearly most meetups won’t share the same host. But you want a place to gather all meetup collectives in one place.

I agree that tags could fulfill the same purpose. The only problem is that anyone can change tags. It may or may not a big problem.

In all cases, we need to keep the concept of `ParentCollectiveId` for events (and potentially in the future “working groups” or “projects”).

**Comment by znarf** [comment]
## Notes

(This will be edited).

- https://opencollective.com/meetups is featuring a link to apply but when I click on it https://opencollective.com/meetups/apply I get "This host is not open to applications"

**Comment by piamancini** [comment]
@znarf - removed the reference

**Comment by znarf** [comment]
@piamancini what did you do exactly?

**Comment by piamancini** [comment]
@znarf just deleted the link in the collective's description. The host shouldn't be showing up as on option to apply to in the flow since it doesn't have an "apply":true in the settings.

**Comment by znarf** [comment]
@piamancini there is so many things mentioned in this issue, it's difficult to follow if you're not explicit. I think you're talking about https://opencollective.com/meetups Ok then.
