### ISSUE TITLE
New collective page admin: pick primary color

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2104]
With the new collective page admins are able to set the primary color of the collective :taco: :taco: :taco:

There no design yet for it, so here's a proposal to start the discussion:

- **On the Hero, show a pencil icon if user is admin**

![image](https://user-images.githubusercontent.com/1556356/59039376-081a4000-8875-11e9-9906-ae93754db878.png)

- **When users click on it, open a modal with**
  - Hero background image upload form (_will be part of another issue_)
  - Color picker

For the color picker, **let's not use something fancy**: the native color picker (`<input type="color"/>`) is well supported by browsers, no need to include heavy libraries that will never match the level of accessibility that this one has. You can try it on https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/color (the results vary depending on the browser/OS).

Ideally, we should update the color in real time so that collectives can preview before saving.

![EditColor](https://user-images.githubusercontent.com/1556356/59040688-7eb83d00-8877-11e9-9e97-3c083608ec8b.png)

<details>
<summary>Styleguidist snippet</summary>

```jsx
import Modal, { ModalBody, ModalHeader, ModalFooter } from 'components/StyledModal';
import StyledButton from 'components/StyledButton';

initialState = { show: false };

<React.Fragment>
  {state.show ? (
    <Modal show onClose={() => setState({ show: false })}>
      <ModalHeader>Customize your collective appearance<span style={{width: 25}}/></ModalHeader>
      <ModalBody>
        <div>
        <p style={{fontWeight: 'bold'}}>Pick the primary color for your collective</p>
        <input type="color"/> #A85679
        </div>
        <div>
        <p  style={{fontWeight: 'bold'}}>Upload an image</p>
<div>        <img src="https://opencollective-staging.s3-us-west-1.amazonaws.com/759400b0-6810-11e9-a86d-e7e9045f1519.jpg" style={{height: 60}}/></div>
        <input type="file"/>
        </div>
      </ModalBody>
      <ModalFooter>
        <StyledButton mx={20}>Cancel</StyledButton>
        <StyledButton buttonStyle="primary">Apply</StyledButton>
      </ModalFooter>
    </Modal>
  ) : (
    <StyledButton buttonSize="large" buttonStyle="primary" onClick={() => setState({ show: true })}>
      Show modal
    </StyledButton>
  )}
</React.Fragment>;
```

</details>

**Comment by xdamman** [comment]
I love that.

Given it's a setting that will be changed only once, I'm not sure we want to use real estate from the collective page, otherwise it will always be in your face. So maybe put it in the /edit page?

**Comment by Betree** [comment]
By having it directly on the collective page you can preview the result in real-time before saving (rather than save, navigate to the collective page, return to the edit page if it doesn't look nice...etc). That's what Twitter does and I really like the UX of it:

![Peek 07-06-2019 10-57](https://user-images.githubusercontent.com/1556356/59093006-30f11280-8913-11e9-914a-92bc68bc1b8d.gif)


I'd personally love if we were able to edit 100% of the content on this page without never leaving it.

**Comment by xdamman** [comment]
alright, I'm sold :-)

**Comment by Betree** [comment]
https://github.com/opencollective/opencollective-frontend/pull/2104 adds support for theming by setting the primary color in `settings.collectivePage.primaryColor`. So the implemented color picker described in this issue should update the color in settings.

**Comment by Betree** [comment]
Resolved in https://github.com/opencollective/opencollective-frontend/pull/2421
