### ISSUE TITLE
Expenses flow: allow for custom internal reference

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2106]
CodeNPlay received more than €300k in subsidies.
They have to follow strict rules in terms of reporting, using some weird codes provided by the government.

It would be extremely useful for them to be able to add a custom reference when filing an expense and show that reference in the monthly PDF report with all the invoices/expenses and in the CSV file.

**Comment by Betree** [comment]
Is this reference a private info?

**Comment by xdamman** [comment]
That's a very good question. I see no reason why it shouldn't be public. But at the same time given it's an internal custom reference, it's not that useful for the public.

**Comment by Betree** [comment]
Would that be ugly or too hacky to put this reference in the expense title?

**Comment by xdamman** [comment]
Yeah too ugly. Also need to be able to filter by it in the spreadsheet being sent to the host / collective.

**Comment by piamancini** [comment]
This will be tackled in the expense redesign process.

**Comment by Betree** [comment]
@xdamman Can the tags introduced in the new expense flow solve this issue if we show them in the report and in the CSV?

**Comment by Betree** [comment]
I believe the tag system now addresses this issue by providing a way to attach any string to an expense. Closing, feel free to re-open if you feel that it's not the case.
