### ISSUE TITLE
unknown status of my new collective

### ISSUE THREAD

**Issue by mixmix** [opencollective/opencollective#2108]
**Describe the bug**
I just made a new collective and I saw this : 
![image](https://user-images.githubusercontent.com/2665886/59137454-10d95600-89dc-11e9-8b00-a81cc34f96c8.png)

fair enough, it's being approved, I'll come back tomorrow. To be clear the text to me reads as **"your account has not yet been approved"**

Leave tab, open, refresh it the next day ... same thing.

Oh wait, the url is : https://opencollective.com/patchbay?status=collectiveCreated

looks like the state of my account displayed on the page has nothing to do with the state of my account? or does it?

Try visiting : https://opencollective.com/patchbay ... yep, no banner.

This is disquieting ... if I wasn't a programmer I'd just think I was being ignored and my account was not approved... forever?

**Comment by znarf** [comment]
Related: https://github.com/opencollective/opencollective/issues/1878 https://github.com/opencollective/opencollective/issues/2100

**Comment by mixmix** [comment]
closed as this was a duplicate
