### ISSUE TITLE
User should be taken to the expense's page after submitting

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2109]
Initially, a user contacted support saying they could't find their unapproved expense after submitting. They thought it was hidden until approval. Later they realised it was just hidden in the list of expenses and they didn't see it.

~~1. Expenses submitters should always be able to see their own expense, regardless of status~~
2. After submitting an expense, take submitter to that expense's page (with a banner acknowledging that it was submitted) instead of the 'submitted' message page we have now

[Support ticket with details here](https://opencollective.freshdesk.com/a/tickets/653).

**Comment by alanna** [comment]
The user came back and said:

> After discussing this with a colleague, it seems that the expense might have been visible from the beginning but the expense list was not ordered by most recent first so I could not find it at first glance.

I still feel 2. above is relevant, so I'm updating this issue to reflect that.

**Comment by znarf** [comment]
I should be ordered by most recent, but relative to the expense date (user submitted), not the submission date (automated).

**Comment by Betree** [comment]
When you submit an expense, you currently see a page like this:

![image](https://user-images.githubusercontent.com/1556356/62297898-49446000-b472-11e9-8667-7da0edcce000.png)

Instead we want users to be redirected to the expense URL (`/{collective_slug}/expenses/{expense_id}`).

# Specs

- [ ] Redirect users with `Router.pushRoute` when the expense is created sucessfully. Add a special query param to notify the page that the expense has just been created, like `?createSuccess`
- [ ] In https://github.com/opencollective/opencollective-frontend/blob/7a19d5e85e765c3f333fadc7888b6fc2ad84c501/pages/expense.js#L97
  - [ ] Show the message currently in https://github.com/opencollective/opencollective-frontend/blob/8ff7e6140d849e095ff9403de4bd1052cb531712/pages/createExpense.js#L98 on the page (`Your expense has been submitted with success...`).
- [ ] Show the `<ExpenseNeedsTaxFormMessage id={expenseCreated.id} />`. You can test that part by submitting expenses > $5000 to /newopensourcecollective

---

Please follow our [code guidelines](https://docs.opencollective.com/help/developers/best-practices-and-code-guidelines), especially:

* The strings must be internationalized. See [/help/developers/translations](https://docs.opencollective.com/help/developers/translations)
* Whenever it's possible we must use `styled-components` to write styles. See [OC Styleguide](https://opencollective-styleguide.now.sh/)
* We're getting rid of `Bootstrap`. Please don't use it for new developments.
* When adding new dependencies, we use [fixed versions](https://docs.npmjs.com/about-semantic-versioning).
* Icons must be imported from the [styled-icons](http://styled-icons.js.org/) library.
* Tests written with Cypress must follow our [good practices](https://docs.opencollective.com/help/developers/testing-with-cypress) conventions.

**Comment by Betree** [comment]
A **$50** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged.

:warning: This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

:arrow_right: [More info](https://github.com/opencollective/opencollective-frontend/edit/master/BOUNTY.md)

**Comment by kleva-j** [comment]
Working on this

**Comment by kleva-j** [comment]
I have not been able to work on this because I had to setup a new machine for this project. I will now begin work on this issue.

**Comment by sudo-kaizen** [comment]
@kleva-j Are you still working on this? @Betree, if @kleva-j isn't still working on this issue, I would like to be assigned to it

**Comment by Betree** [comment]
@kleva-j We can't hold the bounty assigned to you for too long. If you have a pull request ready please ping us, otherwise we'll have to assign someone else in the next few days.

**Comment by sudo-kaizen** [comment]
@Betree I cant seem to find any example for how the `expenseCreated` object can be passed from the `Submit Expense` page to the page for the created expense using `Router.pushRoute`
Any form of help will be appreciated.
Thanks!

**Comment by Betree** [comment]
Hello @sudo-kaizen you don't need to pass the `expenseCreated`, the expense page is responsible for fetching its own data. The expense id that you need for the tax form thing is actually available from the route, in `pages/expense.js` > `props.ExpenseId`.

**Comment by Betree** [comment]
Increased the bounty amount to **$100** because of the complexity.

**Comment by sudo-kaizen** [comment]
Noted!

**Comment by sudo-kaizen** [comment]
> Hello @sudo-kaizen you don't need to pass the `expenseCreated`, the expense page is responsible for fetching its own data. The expense id that you need for the tax form thing is actually available from the route, in `pages/expense.js` > `props.ExpenseId`.

Of course! I was addressing Spec#2, where the `expenseCreated` object is necessary for the message currently in https://github.com/opencollective/opencollective-frontend/blob/8ff7e6140d849e095ff9403de4bd1052cb531712/pages/createExpense.js#L98 to be displayed on the page that the user has been redirected to.

**Comment by Betree** [comment]
@sudo-kaizen You should be able to retrieve the required host name from `data.Collective.host.name`. You need to have the same check tho, `data.Collective.host` can be null.

**Comment by sudo-kaizen** [comment]
Sure! I can do that!
I'll keep you posted!
Thanks 😊

**Comment by Betree** [comment]
:trophy: This issue has been resolved by @sudo-kaizen 

To claim the $100 bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
