### ISSUE TITLE
monthly email is going to inactive collectives

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#211]
Some emails went out anyway to members of groups who had been set to inactive (public set to FALSE) before. ISPCW for example. We should account for this.

**Comment by asood123** [comment]
Is this email automated @xdamman? If so, we should fix this before end of the month.

**Comment by xdamman** [comment]
We need to run it manually. 

It's doing a `Group.findAll(query)` via Sequelize, so as long as the group has a `deletedAt` value, it won't be processed. We shouldn't use the `public` flag for deactivating a collective.

**Comment by asood123** [comment]
'DeletedAt' isn't the right flag to use. In interest of transparency,
everything should remain public and we should have another state on the
group. Like in ISPWCA's case, I'd still rather leave that publicly
available and disable expense submission and donation on it.
