### ISSUE TITLE
Backers cannot contribute recurring donations

### ISSUE THREAD

**Issue by klmansel** [opencollective/opencollective#2110]
**Describe the bug**
On specific collectives, the _Become a backer_  or _contribute_ options do not allow recurring contributions. The `Frequency` box is greyed out/disabled. When choosing _Or make a one time donation_, contributors have the option to choose a monthly or yearly donation. 

**To Reproduce**
1. Go to https://opencollective.com/wwcodegreenville
2. As a logged in user, click on either button: _contribute_ or _Become a backer_
3. Contribute As - select your user name/profile
4. Click Next Step
5. Attempt to change the frequency of the donation (button will be disabled)

**Expected behavior**
This is confusing behavior and seems it should be the opposite: Choosing _contribute_ or _Become a backer_ should allow contributors to choose a frequency for their donation. _Or make a one time donation_ should disable the frequency drop down.

**Screenshots**
Video of issue (could not screenshot disabled dropdown due to mouse disappearing in screenshot):

![open_collective_backer_issue](https://user-images.githubusercontent.com/18410214/59148216-dc619c00-89d3-11e9-9047-929f14440e4e.gif)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.5
 - Browser: Chrome 
 - Version 74.0.3729.169

**Additional context**
As far as I can tell, this is an issue on some, but not all collectives. The link provided is an example of one.

**Comment by alanna** [comment]
Related to #1789 ?

**Comment by klmansel** [comment]
Yes! I didn’t see that one when searching. This is directly related.

**Comment by znarf** [comment]
The "Make a one time donation" link is gonna be updated soon.

**Comment by znarf** [comment]
A simple fix would be to have the `Frequency`editable, triggering a modal warning:

> If you're changing the frequency, we will not contribute to this specific the tier "Gold Sponsor".

- If "Confirm", redirect to the "custom financial contribution".
- If "Cancel", nothing

**Comment by znarf** [comment]
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

**Comment by mikkidollar** [comment]
Hi am micheal from OSCAFRICA , i want to work on this issue

**Comment by alabobriggs** [comment]
Is this issue assigned already. I want to work on it

**Comment by viva-jasper** [comment]
Hello, I'm Jasper from OSCA, i've opted in to work on this issue...Thanks

**Comment by viva-jasper** [comment]
@znarf , I'm currently working on this issue , but i'm a bit confused about what you mean by 'redirect to the "custom financial contribution"'....Kindly explain, so that i can proceed with making my PR

Thanks

**Comment by NotJohs** [comment]
Are you still on this issue? @viva-jasper

**Comment by znarf** [comment]
@viva-jasper sorry for late answer. If you're:

1) contributing to https://opencollective.com/babel/contribute/bronze-sponsors-356/checkout/details
2) change the frequency
3) confirm in the modal
4) you should be "redirected" to https://opencollective.com/babel/donate/details (the amount should ideally stay the same). This should not be a hard redirect, this should be done smoothly by changing the state and/or pushing a new route.

**Comment by znarf** [comment]
This bounty is now opened to everyone.

**Comment by znarf** [comment]
🏆 This issue was completed by @sudo-kaizen  

To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
