### ISSUE TITLE
Track Tiers history

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2114]
On a few tables, we're tracking the whole history of modifications (Collective, Expense, Order, Subscription).

We need to activate that for Tiers, it will would be really useful for troubleshooting.

**Comment by znarf** [comment]
A $50 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

**Comment by mikkidollar** [comment]
I am michael from OSCPH and i want to work on this issue

**Comment by Sokan93** [comment]
Hello @znarf Can I please get a hint on how to go about this?

**Comment by znarf** [comment]
Look at the models https://github.com/opencollective/opencollective-api/tree/master/server/models

And try to understand why have history enabled on `Collective` and not on `Tiers`.

**Comment by Sokan93** [comment]
I came across this - https://www.npmjs.com/package/sequelize-historical
Please do you think it might help me gain some understanding of the stated above

**Comment by znarf** [comment]
Yes, this is the package we're currently using.

**Comment by znarf** [comment]
This bounty is now opened for everyone.

**Comment by znarf** [comment]
🏆 This issue was completed by @NotJohs 

To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
