### ISSUE TITLE
"Make a one time donation" is misleading

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2115]
It should be more: "Make a free donation (one time or recurring)"

**Comment by znarf** [comment]
What should be the proper copy @piamancini @alanna?

**Comment by piamancini** [comment]
I need better context here.

**Comment by znarf** [comment]
@piamancini 

![Capture d’écran 2019-06-12 à 12 06 02](https://user-images.githubusercontent.com/806/59342668-7db95c80-8d0a-11e9-949e-1ea3e89690bd.png)
![Capture d’écran 2019-06-12 à 12 05 50](https://user-images.githubusercontent.com/806/59342669-7db95c80-8d0a-11e9-9a4d-ddab0bd0fbe6.png)

**Comment by xdamman** [comment]
“Or just make a donation”?

Basically the idea is that you just want to make a donation without any reward and independently of any predefined tier.

**Comment by piamancini** [comment]
This is solved in the new collective page, I don't understand the question.

**Comment by znarf** [comment]
If you don't understand the question, how do you know it's solved?

I don't think the "Make a one time donation" link on this page https://opencollective.com/graphql-shield/tiers will be fixed by the new collective page.

**Comment by piamancini** [comment]
Because if the question is that making a one time donation is not clear, then it will be, because it'll be a different card at the same level of the others. It is not a free tier, it has a cost. There's no such thing as a free donation, hence my confusion.

**Comment by znarf** [comment]
I tried to nail the problem as a single sentence, on a single page with a screenshot and a link to the page.

Today we have a link that is **not on the collective page**, the link say "Make a one time donation". You can see it there: https://opencollective.com/graphql-shield/tiers But it's wrong, because you are actually allowed to edit it as recurring (monthly / yearly), so users are confused. See: https://github.com/opencollective/opencollective/issues/2110

The fix is simple: change the copy. I propose  now "Make a donation (one time or recurring)"

Ok with that? Or do you have a better copy?

**Comment by piamancini** [comment]
ahhh you see, when it's al in the framing of the problem! I would say, make a custom donation

**Comment by alanna** [comment]
Make a custom *financial contribution*. I hope we're sticking to the clarified terminology for everything in the new Collective page.

**Comment by znarf** [comment]
Fixed in https://github.com/opencollective/opencollective-frontend/pull/1932

**Comment by znarf** [comment]
Just spotted that. ![Capture d’écran 2019-06-13 à 17 34 20](https://user-images.githubusercontent.com/806/59446320-8e003300-8e01-11e9-86e3-893676aef474.png)
