### ISSUE TITLE
Add a `formattedAmount` field for Zapier payloads

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2117]
Add a `amountStr` (string) field in the payloads sent to Zapier (ex: `$42.50`) to use instead of `amount` that uses cents which requires formatting before being used.

Zapier provides tools to format a value, but it requires a "pro" account. By doing this change we'll enable all collectives to easily use amounts from notifications in their integrations.

Must be update on API and in https://github.com/opencollective/opencollective-zapier/blob/master/src/samples.js

Notifications to update:
- [x] Created expense amount
- [x] Member created > Order > Amount

**Comment by znarf** [comment]
It's a good feature request for the GraphQL API v2 too. This is for this kind of use case that I decided to have the `Amount` object, instead of a `String` or `Integer`.

**Comment by jeffin143** [comment]
@Betree , sorry but I had a glance at the opencollective-zapier repo API folder, and could understand where to handle this

Could you point me the location , so that I can handle this :)

Thanks

**Comment by josesimoes** [comment]
This inaccuracy and the fact that we can't fix it without a Pro account is causing us some unrest in our project... Each contribution is announced as it was 100x greater and we have to intervine to state the correct amount.
Please have this fixed ASAP.

**Comment by znarf** [comment]
@josesimoes Unfortunately, we can't tell you for sure when this will be addressed. In the meantime, maybe can you turn this integration off if this is causing problems in your project.

**Comment by Betree** [comment]
@josesimoes This enhancement has been deployed in the latest version of the Zapier app (1.1.0)

**Comment by josesimoes** [comment]
Thanks @Betree !
Anything I need to change on zappier? Or it will just work?

**Comment by Betree** [comment]
@josesimoes You need to edit the Zap to use the new app version:

![image](https://user-images.githubusercontent.com/1556356/71734534-7a272780-2e4c-11ea-8ea0-3c87d1626d2b.png)

Zapier will probably ask you to login again, you can find your API key on https://opencollective.com/applications

Then in your action you need to switch from using the `member.order.amount` field to one of the new fields (ie. `member.order.formattedAmount`)
