### ISSUE TITLE
Migrate to new Sign In form 

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2119]
## Background

This year, as part of our "Contribution Flow", we moved to new "Sign In" components. These one: 

- https://github.com/opencollective/opencollective-frontend/blob/master/src/components/SignIn.js
- https://github.com/opencollective/opencollective-frontend/blob/master/src/components/SignInOrJoinFree.js

## Problem

While we migrated the key areas where we're using the "Sign In" form, we still need to migrate a few places which are using the old ones:

- https://github.com/opencollective/opencollective-frontend/blob/master/src/components/SignInUp.js
- https://github.com/opencollective/opencollective-frontend/blob/master/src/components/SignInForm.js

## Solution

Fix all places where the old form is still being used. For implementation, see for example how it is handled in the `createOrder` page. ie: https://opencollective.com/babel/donate

### SignInForm

- [ ] CreateExpenseForm ie: https://opencollective.com/babel/expenses/new (check non authenticated)
- [ ] CreateCollective ie: https://opencollective.com/create (check non authenticated)
- [ ] CreateOrganization ie: https://opencollective.com/organizations/new (check non authenticated)
- [ ] EditCollective ie: https://opencollective.com/babel/edit (check authenticated)
- [ ] complePledge ie: https://opencollective.com/pledges/38124 (check non authenticated)
- [ ] ~~CreateHost ie: https://opencollective.com/:collectiveSlug/connect/stripe~~ (currently checking this one, maybe it should be killed, not fixed)

### SignInUp

- ~~InterestedForm~~ (this one should be killed, not fixed).

## Before opening the PR

- [ ] remove SignInForm.js
- [ ] remove SignInUp.js
- [ ] remove all helpers/components that were used in SignInForm.js/SignInUp.js  that are not used anymore

## Final note

In all cases, the new Sign In Form needs to be properly centered and the design needs to look cleaner not worse than before. You're free and welcome to fix small details around it.

**Comment by znarf** [comment]
A $300 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $300 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md).

**Comment by znarf** [comment]
I forgot about an existing previous issue: https://github.com/opencollective/opencollective/issues/1676

**Comment by tsriram** [comment]
Hey @znarf, I'd like to give this a shot. Can I get this assigned to me?

**Comment by tsriram** [comment]
Ah, I started with this the other day just to see @yellowwoods12 is almost done with this now. Wish GitHub notifies me when an issue is assigned to someone :)

**Comment by tsriram** [comment]
Oops, how did I unassign @yellowwoods12. I don't even have access to do that!

**Comment by znarf** [comment]
@tsriram Don't worry, maybe a GitHub bug. Fixed.

**Comment by znarf** [comment]
Thank you @yellowwoods12  ! It's merged.

An expense was already submitted to claim the bounty:
https://opencollective.com/engineering/expenses/8628
