### ISSUE TITLE
set donators to "expire" after 90 days

### ISSUE THREAD

**Issue by boneskull** [OpenCollective/OpenCollective#212]
If a backer or sponsor has not donated within the last 90 days, remove them from the list.  

For example, Yahoo! still shows in the list of Mocha sponsors (it's unclear to me if they donated in the last 90 days though; can @OpenCollective/core answer when the last donation date was?).

**Comment by asood123** [comment]
API: https://github.com/OpenCollective/opencollective-api/pull/542
Website: https://github.com/OpenCollective/opencollective-website/pull/403

**Comment by asood123** [comment]
Requires https://github.com/OpenCollective/opencollective-api/pull/542 to be merged first.

**Comment by asood123** [comment]
fixed. Github might take a bit to refresh.
