### ISSUE TITLE
Couldn't find any repositories (with >= 100 stars) linked to the account

### ISSUE THREAD

**Issue by t-k-** [opencollective/opencollective#2125]
**Describe the bug**
I have a open source project with 200 stars now, when I create an opencollective project, it says 

> We couldn't find any repositories (with >= 100 stars) linked to the account

**To Reproduce**
Login as approach0 (my account), go to https://opencollective.com/pricing and click create opencollective, choose opensource project and then click "get started".

**Expected behavior**
Can proceed.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Chrome
 - Version: 22

**Comment by t-k-** [comment]
Sorry, I just find that I have linked a wrong Github account in my profile page. I am closing the issue...

**Comment by t-k-** [comment]
I have to re-open this issue, it still says 

> We couldn't find any repositories (with >= 100 stars) linked to the account

I want to link to my project under GitHub organization `approach0` which satisfies the star requirement and I am the current owner of that organization, but it seems you only check the projects under my personal Github account (`t-k-`), I want to ask if there is any way to create an opencollective project for a project under organization account (it is actually a personal project)?

**Comment by piamancini** [comment]
@t-k- you need to revoke permits and re auth this time checking to authenticate as an 'organization' - there's a checkbox scrolling down. lmk how it goes.

**Comment by t-k-** [comment]
@piamancini Thank you so much, I have successfully created the opencollective under your instructions. I am closing this issue again. There is one minor thing though, under my [opencollective page](https://opencollective.com/approach0), it has a title style "GraphQL error", I do not know why it is there, maybe I should open another issue?
