### ISSUE TITLE
Custom fields for Tiers

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2128]
## User story 

As a collective admin, I want to be able to collect custom information from individual or organizations contributing financially through a tier.

It's relevant for example for the Back My Entire Stack project, where we want to collect the URL of a JSON file that summaries dependencies. https://github.com/opencollective/backyourstack/issues/168

### API side

A) Exposing the settings

- Add a new `settings` (JSON) column to Tiers that will contain additional data
- Expose `settings` through GraphQL

A) Collecting custom fields

- The `createOrder` mutation should be able to receive custom fields. It should store them in the `data` column of the `Orders` table

### Frontend side

- When `settings.customFields` is set, display additional fields at the `contributeDetails` step of the contribution flow
- It should validate `required` fields
- When submitting the order, it should pass the custom fields to the GraphQL mutation
- It should be able to receive default values for custom fields in the URL, ie: `https://opencollective.com/backyourstack/contribute/sponsors-5798/checkout?data[jsonUrl]=http://example.com/deps.json`

### Data Structure

```
{"customFields: [
  "name": "jsonUrl",
  "label": "URL of the JSON dependency file",
  "type": "url",
  "required": true,
]}
```

## Out of scope ##

- The administration interface for that

**Comment by Betree** [comment]
May be worth looking at JSON schema, it's not so far from the specification proposed here and being a standard there are plenty of libs that are capable of building forms automatically based on it (ex https://github.com/mozilla-services/react-jsonschema-form)

**Comment by znarf** [comment]
In this context, I would implement something simplistic that matches our Input components. But, we can get inspiration for the JSON structure.

**Comment by alanna** [comment]
Related: #1798 and #2105

**Comment by Betree** [comment]
I agree that we don't need to include additional libraries and too much complexity for now. Just following JSON schema's structure doesn't add more complexity and opens the door for #1798 and #2105 to be implemented with reverse compatibility in the future.
