### ISSUE TITLE
Sort pending orders chronologically

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2132]
## User story 
As a host admin, I want to be able to find the pending orders that I need to mark as paid. Currently they are in a seemingly random order.

They are located on the host dashboard > orders > pending filter.

## Best solution for this problem
Best case would be options for sorting by amount or date.

## MVP
Sort the pending orders chronologically by date created.

![Screen Shot 2019-06-19 at 1 01 19 PM](https://user-images.githubusercontent.com/5498878/59729379-5b878780-9292-11e9-8f71-6beda738ee23.png)

**Comment by Betree** [comment]
Fixed by https://github.com/opencollective/opencollective-api/pull/2357 (not yet deployed)
