### ISSUE TITLE
A way to delete/cancel/reject pending orders

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2133]
## User story 
As a host admin, I want to be able to cancel pending orders if the payer does not follow through with the bank transfer, or if they made a mistake.

## Best solution for this problem
A "cancel" button next to the "mark as paid" button, accessible to the host admin and the original order creator. When pressed, it first asks to confirm and then if you do, deletes the pending order. Maybe it should also send a notification confirming the cancellation to the host admin, order creator, and Collective admin.

![Screen Shot 2019-06-19 at 1 03 46 PM](https://user-images.githubusercontent.com/5498878/59729468-cd5fd100-9292-11e9-962b-f2483ea27650.png)

## MVP
Cancel button only accessible to host admin, no email notification.

**Comment by znarf** [comment]
We have to be clear about the wording and what status we give to these `orders` after that.

The `CANCELLED`and `REJECTED` statuses are already taken for other cases, so we need something different.

**Comment by alanna** [comment]
How about "expired"? It doesn't matter too much what word we use for the status. I think in the UI it should say 'cancel' because that's the action the admin is taking.

**Comment by flickz** [comment]
Closed in https://github.com/opencollective/opencollective-api/pull/2737 & https://github.com/opencollective/opencollective-frontend/pull/2820
