### ISSUE TITLE
Fix SEO and social media meta data

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2137]
Right now, this is how sharing an open collective link such as https://opencollective.com/babel looks like on Facebook / Messenger / WhatsApp: 

![](https://d.pr/free/i/20NlJc+)

Facebook scraper:
https://developers.facebook.com/tools/debug/sharing/?q=opencollective.com%2Fbabel

Twitter card tool:
https://cards-dev.twitter.com/validator

How should it look?
Title: `collective.name` - Open Collective
Description: `collective.description`
Image: `collective.image`
twitter:creator: `collective.twitterHandle`
twitter:site: @opencollect

To make sure that it works, please use the Facebook Scraper (see above) with the URL of the automatically deployed branch, e.g. https://opencollective-frontend-vwfxtupsdr.now.sh/babel
![](https://d.pr/free/i/A1dWi7+)

**Comment by xdamman** [comment]
@znarf Can we add a bounty for this?

**Comment by znarf** [comment]
@znarf we'll include that in the OSCA bounty effort.

**Comment by znarf** [comment]
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the OSCA (Open Source Africa) events. if not completed there, it will be later open to everyone

**Comment by znarf** [comment]
Looks like Facebook works now. Following up for Twitter in https://github.com/opencollective/opencollective/issues/2206
