### ISSUE TITLE
Notifications when subscription cancelled

### ISSUE THREAD

**Issue by edsilv** [opencollective/opencollective#2139]
This is more of a feature request.

We base membership of our steering group on OC sponsorship. If we lose a sponsor it would be great to be notified (an email) so that we can act on it as opposed to needing to review our statements. Otherwise as we get more sponsors it'll get progressively more difficult to spot.

Many thanks!

**Comment by alanna** [comment]
Collective admins do get notified when someone cancels a subscription. The email looks like this, with the Core Contributors CC'd.

![Screen Shot 2019-06-21 at 1 03 50 PM](https://user-images.githubusercontent.com/5498878/59890463-18115280-9425-11e9-8644-2b78d37f4f68.png)

**Comment by edsilv** [comment]
Thanks @alanna, we must have missed it!
