### ISSUE TITLE
Collective page: v1 → v2 migration

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2140]
The goal of this issue is to describe the migration process to the new collective page. It's just a proposal and all periods are chosen arbitrarily so feel free to suggest edits!

# Timeframe

I'd like to have the first releasable version of the new collective page at the end of next week (28th June) (right now the main blocker is that the "budget" section doesn't exist).

Though it will be usable, we don't want to break anything for collectives so we should deploy it progressively. Here is the schedule I'm proposing:

- **1st July**
  - Start communicating to some collectives (on Slack & with good friends) about the `/v2` URL so they can preview their page. Get a list of collectives willing to join the `Beta` program.
  - Implement the setup to redirect collectives in the Beta program to the new collective page properly (may take one or two days to be done properly). Once the setup is ready, start onboarding collectives on the new page.
- **15th July**
  - Based on the feedback and improvements made during the 15 days
    - All good → Make `v2` the default, with possible fallback on v1 based on a simple setting
    - Not ready →
        - Add a checkbox on `/edit` so users can activate v2 themselves
        - Keep improving the page
  - Communicate about the new collective page on the newsletter
- **5th August**
  - If new collective page is not the default, now is a good time to do it (@znarf's will be back from holidays to save us if everything goes wrong)
- **Two months after the new collective page is live**
  - If there's no blocker, kill the old one :hocho: 

# Technically  

*TODO*

**Comment by xdamman** [comment]
What's the plan for the "conversations" section?

**Comment by Betree** [comment]
@xdamman This one has a pretty high cost and is currently not planned for the initial release (see https://github.com/opencollective/opencollective/projects/18). The goal is to work on it once the base page with all required sections is done, so (in theory)  during this summer.

**Comment by yellowwoods12** [comment]
@Betree What about the documentation? Do we have to update it as well according to the new release?

**Comment by Betree** [comment]
@yellowwoods12 I have nothing planned for documentation yet but we should probably update it as soon as the new collective page becomes the default. Do you have some documentation pages in mind?

**Comment by yellowwoods12** [comment]
@Betree Yes. We can add some documentation pages informing about the design and features of the new release; what were the challenges and issues with the old design; how we overcame them in the new one; what are the deprecated components in the old one that what alternatives are we using for it.
My whole idea is to properly document every feature related to the new release for future use as well as for new contributors. This documentation should be such that both developers and Open Collective contributors can benefit from that.

**Comment by yellowwoods12** [comment]
> @Betree Yes. We can add some documentation pages informing about the design and features of the new release; what were the challenges and issues with the old design; how we overcame them in the new one; what are the deprecated components in the old one and what alternatives are we using for it.
> My whole idea is to properly document every feature related to the new release for future use as well as for new contributors. This documentation should be such that both developers and Open Collective contributors can benefit from that.

@Betree  Should I create an issue for the same so that it can be discussed further?

**Comment by Betree** [comment]
> Yes. We can add some documentation pages informing about the design and features of the new release; what were the challenges and issues with the old design; how we overcame them in the new one; what are the deprecated components in the old one and what alternatives are we using for it.
> My whole idea is to properly document every feature related to the new release for future use as well as for new contributors. This documentation should be such that both developers and Open Collective contributors can benefit from that.

There are some good points in there @yellowwoods12. Some of what you suggested would be more relevant to put in a blog post but I could see a FAQ with questions like `What happened the collective bar?` as we won't have a replacement for the feature it provides right now. 

> @Betree Should I create an issue for the same so that it can be discussed further?

Let's start with that, we'll try to reference in the issue all the important changes that users are going to face and the questions that they may have.

Thanks!

**Comment by yellowwoods12** [comment]
Issue created for discussing about documenation : opencollective/opencollective/#2148

**Comment by Betree** [comment]
In the end I took the decision to limit the "beta program" idea because the way to implement it correctly added too much complexity. Some internal collectives such as https://opencollective.com/general-intellect have been activated with the "partial" beta though.

**Final resolution:** https://github.com/opencollective/opencollective-frontend/pull/2400 added the option to enable the new collective page site-wise. We'll take this approach to migrate everything at once, with the option to rollback easily if anything goes wrong.
