### ISSUE TITLE
Expense not showing in 'ready to pay' when it should be

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2144]
**Describe the bug**
[This expense](https://opencollective.com/pizzaql/expenses/8403) did not show up under "ready to pay" even though it was ready to pay. The user had to contact support or I would never had seen it.

**Expected behavior**
The expense should have appeared in the list under the "ready to pay" filter.

**Screenshots**

The expense is payable:

![Screen Shot 2019-06-21 at 3 23 31 PM](https://user-images.githubusercontent.com/5498878/59895449-c07ce200-9438-11e9-8de3-4248dafb07e9.png)

But nothing is showing up here:
![Screen Shot 2019-06-21 at 3 23 47 PM](https://user-images.githubusercontent.com/5498878/59895455-c7a3f000-9438-11e9-801d-bd90a97083c6.png)

**Comment by znarf** [comment]
@alanna in this expense, you say that you had to reduce the total slightly to cover paypal fees.

Do you think the problem could be related to that?

Now that it's paid, it's difficult to troubleshoot.

**Comment by alanna** [comment]
I don't think it's due to the paypal fees situation, because we often have expenses where there isn't enough to cover fees come up in 'ready to pay'. I don't think the system checks that until you press 'Pay' and if there's not enough to cover fees it throws an error.

**Comment by alanna** [comment]
Here's another example. This one has not been paid yet because we're waiting on an updated invoice.

https://opencollective.com/volteuropa/expenses/8082

I think in both cases the amount of the expense was the full balance of the Collective so maybe that's a clue?

@znarf can you have a look at this please? If expenses don't show as ready to pay they will be missed.

**Comment by alanna** [comment]
[Here's another example](https://opencollective.com/intellij-rainbow-brackets/expenses/9101) that wasn't showing up in ready to pay so I didn't know about it until the user contacted support upset by the delay.

This is a big problem because it's going to cause expenses to be missed. Can it please be investigated?

**Comment by znarf** [comment]
@alanna Sure. If you want us to investigate, please don't pay the expense so that we can have a look at the live data. We'll act quickly so you can pay the expense after ~24 hours.
