### ISSUE TITLE
Upgrade react-apollo package to latest version

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2145]
We have a policy to try to use the latest version of our dependencies in all repositories.

In the Frontend, we're currently using `react-apollo` version `2.5.2` and the upgrade to version `2.5.3` (and later) has breaking changes.

- PR with `react-apollo` `2.5.5`:
  https://github.com/opencollective/opencollective-frontend/pull/1776
- Sample failure on CI:
  https://circleci.com/gh/opencollective/opencollective-frontend/26447

We want to:

- upgrade the package react-apollo >= 2.5.5
- make sure tests are passing

Likely related: https://github.com/apollographql/react-apollo/issues/2900

**Comment by Shorpee** [comment]
I'll work on this.

**Comment by znarf** [comment]
Thank you @Shorpee ! It's merged.

To claim the bounty, you can:

a) submit an invoice to https://opencollective.com/engineering
b) or ask for an Open Collective gift card of the same value (to donate to other collectives)
