### ISSUE TITLE
NULL amountType for some tiers

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2147]
# Problem

The following query:

```sql
SELECT id, amount, "type", "interval", "amountType", presets FROM "Tiers"
WHERE "amountType" IS NULL
```

Returns:

| id    | amount  | type       | interval | amountType | presets | 
|-------|---------|------------|----------|------------|---------| 
| 9 494 | 800 000 | DONATION   | [NULL]   | [NULL]     | [NULL]  | 
| 9 663 | 100 000 | MEMBERSHIP | year     | [NULL]     | [NULL]  | 
| 9 664 | 80 000  | MEMBERSHIP | year     | [NULL]     | [NULL]  | 
| 9 677 | 100     | TIER       | [NULL]   | [NULL]     | [NULL]  | 
| 9 678 | 100     | TIER       | [NULL]   | [NULL]     | [NULL]  | 
| 9 679 | 300     | TIER       | month    | [NULL]     | [NULL]  | 
| 9 708 | 35 000  | TICKET     | [NULL]   | [NULL]     | [NULL]  | 
| 9 717 | 1 000   | TIER       | [NULL]   | [NULL]     | [NULL]  | 
| 9 833 | 1 000   | TICKET     | [NULL]   | [NULL]     | [NULL]  | 

# Fix

It seems to me that `amountType` should never be null (@znarf please edit the following if I'm missing something) so:

- [ ] See why these tiers were allowed to be created without `amountType`
- [ ] Migrate invalid tiers to a valid `amountType`
- [ ] Set `allowNull=false` on `amountType`
- [ ] Add a `defaultValue` on `amountType`

**Comment by flickz** [comment]
Initially when `amountType` was added to the Tier column the value was set along in the [migration file](https://github.com/opencollective/opencollective-api/blob/master/migrations/20190509094659-add-amountType-column-to-tiers.js#L14-L27) for each tiers, at that point, no `amountType` was supposed to be `NULL`. But we didn't disallow NULL in the model nor set defaultValue. 

After the [tier validation PR](https://github.com/opencollective/opencollective-api/pull/2060), I noticed, at times the kind of tier data sent from the frontend was incomplete, like `amountType` missing, this was the motivation for this PR [##issuecomment-498325140](https://github.com/opencollective/opencollective-frontend/pull/1880#issuecomment-498325140), it sets the default value for `amountType` in the frontend. 

I think tiers without `amountType` were created before this PR [#1880](https://github.com/opencollective/opencollective-frontend/pull/1880) was merged.

Have opened [#2194](https://github.com/opencollective/opencollective-api/pull/2194) to fix this, disallow NULL and set default value to FIXED as you've stated.
