### ISSUE TITLE
Documentation for the new collective page

### ISSUE THREAD

**Issue by yellowwoods12** [opencollective/opencollective#2148]
This issue is created to discuss the structure and features of the new documentation that we will create and maintain with the new release. Kindly address all the points that come up in your mind that will help us in making a great documentation.

**Comment by Betree** [comment]
Here's a first draft of the "breaking" changes I see coming. I'll edit this comment to add new ones if I can think of any.

- Goals

With the new collective page we removed the goal progress bar. While we acknowledged this and provided the feedback to design, we don't know if or when we will add a similar feature.

**Comment by alanna** [comment]
Info about customising Collective pages has been added here:
https://docs.opencollective.com/help/collectives/customize-collective

Still working on documentation for Tiers and Goals.

**Comment by alanna** [comment]
Only thing left is to add the part about creating individual tier pages to the Tiers & Goals page. @Betree or @piamancini to action once we have screenshots.

**Comment by piamancini** [comment]
closing this issue as documentation has been created and added to docs.
