### ISSUE TITLE
Can’t remove or add host

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2149]
When logged in as an admin of a collective, it doesn’t let me remove the host or create one because of what seems to be an erroneous permission check. 
Reported by https://opencollective.com/reseautransition-be

![0267F1BE-7858-4B21-A1D6-6C2DC4D04322](https://user-images.githubusercontent.com/74358/59952336-17f07180-947c-11e9-9877-00e158508132.png)
![A3078398-1D95-49FB-BE8F-23607D2B231A](https://user-images.githubusercontent.com/74358/59952337-17f07180-947c-11e9-899f-01231e0e82bc.png)

**Comment by znarf** [comment]
@xdamman This is a support request. We need additional information like the authenticated user trying to perform the change.

How can they remove one if they can't add one? 

In the database, there is no ADMIN for this collective.

**Comment by xdamman** [comment]
Because I manually removed the host.

Ah that was it, not sure how come that user was a MEMBER and not an ADMIN of the collective.
Weird.
Anyhow. Thanks for looking into this!
