### ISSUE TITLE
How to integrate OpenCollective sponsors and backers list into a Docusaurus website?

### ISSUE THREAD

**Issue by hsluoyz** [opencollective/opencollective#2150]
I want my sponsors and backers to be automatically listed in my project's website, which is in [Docusaurus](https://docusaurus.io/), like how jest did it: https://jestjs.io/ . Is there a way to do so? Better if the list can also be in GitHub README.

**Comment by alanna** [comment]
Please see the documentation here: https://docs.opencollective.com/help/collectives/data-export

You can use these widgets on your website and README.
