### ISSUE TITLE
Recurring financial contributions with Paypal

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2151]
## User story 
As a financial contributor, I want to set up recurring contributions to a Collective with Paypal as the payment source, so that I can pay using my preferred method.

## Best solution for this problem
Here's the feedback we got from a user:

> I do not want to let you store my card in your system. Paypal is PCI compliant and only paypal should have my debit card info. I want to use my PayPal Credit Account for this Business expense, (not my personal debit card). I want to use Paypal. I want Open Collective to protect my financial information by using the Paypal API properly. I am an eCommerce developer.
I am not going to put my banking info into a form on your website... BUT I totally would "check out with paypal" using 1 click and hand over the money. Maybe you could examine that. Not having [this](https://www.paypal.com/us/webapps/mpp/pro-recurring-payments ) set up in your system is baffling to me. I set this feature up all the time for clients. It works with IPN. Takes a few min to a few days... depending on your skill set.

**Comment by znarf** [comment]
Original issue: https://github.com/opencollective/opencollective/issues/1141

**Comment by Betree** [comment]
Sounds like a duplicate of https://github.com/opencollective/opencollective/issues/1141, @alanna can we close it?
