### ISSUE TITLE
GraphQL error when trying to view order

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2152]
**Describe the bug**
Unable to view order details due to "GraphQL" error.

**To Reproduce**

1. Go to host dashboard
2. Click on an order under 'latest orders'
3. See error

**Expected behavior**
It should show the details page of that order.

**Screenshots**
![Screen Shot 2019-06-25 at 9 12 25 AM](https://user-images.githubusercontent.com/5498878/60052747-2fed1d00-972a-11e9-9aeb-11288220e60c.png)

**Comment by znarf** [comment]
@alanna Thank you for reporting. This is again related to our latest GraphQL upgrade.

This is easy to fix.
