### ISSUE TITLE
Unable to apply to host with the right Collective when you have multiple unhosted Collectives

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2154]
## User story 

Imagine you admin two Collectives without a fiscal host, A and B. When you view a host page the button says "Apply with Collective A" and there is no way to select Collective B. Even if you go to Collective B > edit Collective > fiscal host and try to add a host that way, it will still default to Collective A.

## Best solution for this problem

There should be a way to select the Collective you'd like to apply with. Maybe the button should just say "Apply to Host Your Collective" and if you have multiple it will pop up with a box asking you to select one. 

Bonus point: if you arrive to that point from the "edit fiscal host" page, it should default to the Collective you were editing.

**Comment by znarf** [comment]
Adjusting the complexity and adding a bounty.

- We should adapt or duplicate our modal to allow selection of the Collective through it (an HTML select is fine).
- This should be covered by at least one e2e test.
