### ISSUE TITLE
Not getting receipt/invoice for funds added manually

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2155]
**Describe the bug**
Whenever someone gives a financial contribution, they should be emailed a receipt/invoice. Someone contacted support to say their sponsor hadn't gotten theirs, so I tested it using my own email and the receipt wasn't sent to me. However, I can see and download the receipt by going to /transactions.

**To Reproduce**
1. Go to host dashboard
2. Select a Collective
3. Go to 'add funds'
4. Create a new source, using your own email
5. Add funds
6. Do not get an email receipt

**Expected behavior**
Whether a contribution is made via any source, credit card or manual, the payer needs to be emailed their receipt.

**Comment by flickz** [comment]
@alanna Following your steps to reproduce, I got an email with receipt link.

<img width="471" alt="Screenshot 2019-10-06 at 9 38 39 AM" src="https://user-images.githubusercontent.com/15707013/66266580-d6af8200-e81e-11e9-9a13-de75445f8345.png">

Or maybe it is adding fund from the host collective page? 🤔 

<img width="467" alt="Screenshot 2019-10-06 at 9 53 00 AM" src="https://user-images.githubusercontent.com/15707013/66266615-432a8100-e81f-11e9-8005-aba60f50ded0.png">

**Comment by alanna** [comment]
Yes, it appears to be working now.
