### ISSUE TITLE
Confirmation message before Removing host

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2156]
## User story 

As a Collective admin, I want to avoid accidentally removing the host of my collective.

![Capture d’écran 2019-07-05 à 16 26 20](https://user-images.githubusercontent.com/806/60728872-a7e4ef80-9f41-11e9-8b0c-e4688544aef9.png)

## Best solution for this problem

An "Are you sure you want to [action]? Yes/No" modal. 

Similar to what we have already for "Delete Collective" / "Archive Collective".

![Capture d’écran 2019-07-05 à 16 24 43](https://user-images.githubusercontent.com/806/60728772-6bb18f00-9f41-11e9-8b9f-7f112d13db9b.png)

**Comment by znarf** [comment]
A $50 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

**Comment by alabobriggs** [comment]
I'll like to work on this

**Comment by alabobriggs** [comment]
Working on this issue requires having a fiscal host already. I tried adding a fiscal host but got error when prompted to connect to stripe. Is there a way to bypass the stripe connection request on staging api and create a fiscal host or is there another way to get a fiscal host?

below is the screenshot of the error when connecting to stripe.

![Screenshot (10)](https://user-images.githubusercontent.com/38571291/60980235-00463380-a32c-11e9-9e3d-7a084aafde95.png)

**Comment by JaybeeClassical** [comment]
I'm going through this and would like to work on this 
From osca Lagos

**Comment by znarf** [comment]
It's a bit complicated to do for external contributors, we will do that internally.

**Comment by JaybeeClassical** [comment]
So what do you suggest i do to this issue?


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by znarf** [comment]
@JaybeeClassical unless you already have a working solution, it's best to stop looking at it and let someone from our team take care of it.

**Comment by sudo-kaizen** [comment]
@znarf I think it will be a good thing if the organisation adds a particular label to issues that will be resolved by the opencollective team

**Comment by znarf** [comment]
@sudo-kaizen as soon as we know it will be resolved by someone from the Open Collective, we're assigning it to this person. Until that, it's open.

**Comment by flickz** [comment]
Closed in https://github.com/opencollective/opencollective-frontend/pull/2356
