### ISSUE TITLE
Event Times are wrong

### ISSUE THREAD

**Issue by mixmix** [opencollective/opencollective#2159]
check this event out : https://opencollective.com/secure-scuttlebutt-consortium/events/js-getter-setter-abstractions-with-andre-staltz-12314ev

Andre is hosting this webinar, he lives in Finland, and the event is at 9am there.

Mix lives in New Zealand and he's about to get on the call at the time the event is listed on this page - **9AM**

---

solution: 

here's the code I use for this problem in scuttlebutt/patchbay (which is an electron / chrome env)

```js
var spacetime = require('spacetime')

function Time (date) { // e.g. date = new Date(2019, 05, 26)
  const t = spacetime(date)
  return h('div.time', [
    t.format('nice'),
    h('div.zone', { title: 'timezone' }, [
      getTimezone() || '??',
      h('span', ['(UTC ', getTimezoneOffset(), ')'])
    ])
  ])
}

function getTimezoneOffset () {
  const offset = new Date().getTimezoneOffset() / -60
  return offset > 0 ? `+${offset}` : offset
}
getTimezone () {
  try {
    return Intl.DateTimeFormat().resolvedOptions().timeZone
  } catch (e) {
    return undefined
  }
}
```

the vibe of this is "have a stab at the local time" AND also tell people what we think we've guessed the timezone to be ... and tell people if we don't know for sure! I don't know about the 

see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat for support of that API

**Comment by znarf** [comment]
I think it's important to first always display the timezone.

Then we calculate local time, and if it's different, we can add the time in the user timezone.

**Comment by mixmix** [comment]
recommend you / a designer draws a scamp (mock up on an envelope) so the person fixing this know what you mean - timezones are curly!

**Comment by alanna** [comment]
Just to add a bit of feedback, I'm not able to use Open Collective events for OSC's maintainer support calls because the time zones are too unclear. We have people in 8 different time zones and I can't figure out if I should be specifying the time in my own time zone or what the users will see, and it's too confusing.

**Comment by znarf** [comment]
🏆 This issue was completed by @Rexben001  as part as our first Hackathon.

I retroactively added a $200 bounty on it. To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Comment by mixmix** [comment]
awesome work @Rexben001 !

---

@znarf it'd be great for bug reporters to get some thanks / acknowledgement. I took 5-10 mins out of my time to try and clearly outline this problem. I don't need money, I hope to benefit from this, but a high-five, and a cute emoji would co a long way e.g.

> Great catch, thanks @mixmix :egg: :pineapple: :boom: 

Emoji's are a really light-weight way convey playfulness and feelings without having to write heaps. This makes me feel good about contributing, because I feel like I've been seen, which makes me more likely to do the same in the future :heart:

**Comment by znarf** [comment]
@mixmix  thank you, you're absolutely right, we never thank enough the bug reporters. 🍍❤️

Fyi, we're still working on it as I realized we should let events creators set/edit the timezone https://github.com/opencollective/opencollective/issues/2512

**Comment by mixmix** [comment]
# :tropical_fish: :heart:

**Comment by znarf** [comment]
Closing it, we will track the rest in the follow up issue.
