### ISSUE TITLE
Page to confirm unsubscription from mailing list

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#216]
We need a page to confirm that you've unsubscribed from a mailing list.
We would also need the same page with a different message and a different API call to confirm that an email has been approved for submission to the mailing list.

Right now, the link in the email (to unsubscribe or to approve) goes to `https://opencollective.com/api/services/email/approve?messageId=:messageId&approver=:approverEmail`
and
`https://opencollective.com/api/services/email/unsubscribe/:email/:slug/:type/:token`

We should have a very simple page that loads fast with just the OpenCollective logo and footer and the confirmation message at https://opencollective.com/services/email/[approve|unsubscribe] that would call the corresponding API route with the parameters.

**Comment by carlosascari** [comment]
@xdamman Where is the unsubscribe endpoint located?

I cannot find the `../services/email/unsubscribe/:email/:slug/:type/:token` route

**Comment by xdamman** [comment]
@erickrico can you upload your design here?

**Comment by erickrico** [comment]
![cancelled](https://cloud.githubusercontent.com/assets/18429104/18453627/d0fc2eb6-7905-11e6-83f4-c5496fe3f49e.png)
![succesful](https://cloud.githubusercontent.com/assets/18429104/18453628/d0fc7e16-7905-11e6-8ca9-b673c5951d27.png)

**Comment by carlosascari** [comment]
Merged
