### ISSUE TITLE
Admin unable to refund transaction

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2162]
I'm pretty sure this is different from #2070 so I'm raising it separately

**Describe the bug**

When the admin of the host [CSS](https://opencollective.com/css) tries to refund the [$50,000 transaction here](https://opencollective.com/dat/transactions) by clicking the refund button, they see this error in the console:

> GraphQL error: paymentMethod.refundTransaction is not a function

When I try to refund it, it appears as if it's working, but then the transaction is still there, not refunded.

**Comment by znarf** [comment]
Duplicate with https://github.com/opencollective/opencollective/issues/1936 ?

**Comment by alanna** [comment]
Oh. I didn't realise refunds didn't work for manually added funds. Can this specific transaction be refunded on the backend please? The user attributed it to the wrong source and needs to re-do it.
