### ISSUE TITLE
Fiscal host applications were re-enabled erroneously

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2164]
**Describe the bug**
[CSS](https://opencollective.com/css) previously had applications from new Collectives disabled. Recently it has become enabled again for an unknown reason. It needs to be disabled and it should not be re-enabled unless they request it.

**Comment by znarf** [comment]
@alanna looking at the Collective history it was never disabled. Do we have a trace of the exchange where we said we did?

**Comment by alanna** [comment]
@znarf no but the admin says it was, and previously they weren't getting Collective applications, whereas recently they have. I am not sure of the details. @piamancini do you remember?

**Comment by alanna** [comment]
I'm closing this because we'll have a toggle setting soon and this won't matter.
