### ISSUE TITLE
Fiscal Host admin can enable or disable applications from new Collectives

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2165]
## User story 
As a fiscal host admin, I want to be able to turn on or off applications from new Collectives, so I can align with the policy or status of my organization.

## Best solution for this problem
During host creation, the system should ask if you want the host to be open to new Collectives (other than the one you are creating it for) to apply. And this setting should also be available in host settings.

## MVP
A toggle in edit > advanced for "Enable applications from new Collectives" that switches on or off.

The default setting is currently OFF but I think the default should be ON if we are not going to have them set it explicitly during setup.

**Comment by alanna** [comment]
@xdamman can you please do this one on Friday? It's a blocker for new hosts trying to activate.

**Comment by alanna** [comment]
@xdamman are you going to do this one?

**Comment by xdamman** [comment]
If no one can take this one I can put it on my plate for Friday.

It's also a fairly simple one. Maybe worth adding a small bounty as a good first issue @znarf ?

**Comment by alanna** [comment]
@xdamman when will this be done?

**Comment by Betree** [comment]
> Maybe worth adding a small bounty as a good first issue

Bounties are there to address backlog issues without expectations about delivery date. I'd say it's usually not compatible with `priority` or `important` issues.

**Comment by znarf** [comment]
@flickz can you have a look? The GraphQL property is `canApply`. In the database it's `collective.settings.apply`.

**Comment by flickz** [comment]
Closed in https://github.com/opencollective/opencollective-frontend/pull/2300
