### ISSUE TITLE
Unable to generate API key 

### ISSUE THREAD

**Issue by yellowwoods12** [opencollective/opencollective#2166]
**Describe the bug**
Unable to generate API key on pressing pressing the new API key button. The keys showed up after I refreshed the page and then cannot be deleted.

**To Reproduce**
1. Go to 'https://opencollective.com/applications'
2. Click on 'New API key' button
3. See error

**Expected behavior**
 The API key should show up on pressing the 'New API key' button rather than on refreshing the page. Also the key should be deleted on pressing the 'delete' button.

**Screenshots**
Before refreshing:
![Screenshot_2019-06-27 Applications - Open Collective](https://user-images.githubusercontent.com/31931348/60257494-2feb4980-98f1-11e9-9765-718d456fea36.png)

After refreshing:
![Screenshot_2019-06-27 Applications - Open Collective(1)](https://user-images.githubusercontent.com/31931348/60257502-35489400-98f1-11e9-8995-ccb60b4ee931.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Browser : firefox

**Comment by Betree** [comment]
Good catch @yellowwoods12, thanks for reporting that. I actually changed the behaviour on this page recently so this is probably linked to a change that I made.

**Comment by znarf** [comment]
I fixed the deletion issue. PR open.

**Comment by Betree** [comment]
@znarf Then we have two fixes for this one :) https://github.com/opencollective/opencollective-frontend/pull/2035 + https://github.com/opencollective/opencollective-api/pull/2174 fix the type issue on ID and the updaters

**Comment by Betree** [comment]
opencollective/opencollective-api#2174 and opencollective/opencollective-api#2173 are the same, closing opencollective/opencollective-api#2174
