### ISSUE TITLE
Add confirmation for "Empty Balance"

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2167]
Collective Admin wanted to close the collective, hit "Empty Balance" but wasn't expecting it to happen without a warning. 

![Capture d’écran 2019-07-05 à 16 33 13](https://user-images.githubusercontent.com/806/60729288-a36d0680-9f42-11e9-99fe-9b7b04bcd0f5.png)

We should add a warning similar to "Archive Collective" and "Delete Collective".

![Capture d’écran 2019-07-05 à 16 24 43](https://user-images.githubusercontent.com/806/60729189-6739a600-9f42-11e9-9c46-135accd454bf.png)

**Comment by alanna** [comment]
Dup of #2156

**Comment by znarf** [comment]
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

**Comment by bigpreshy** [comment]
I am Precious Luke from #oscaph.
I am working on this issue

**Comment by NotJohs** [comment]
@znarf is this issue assigned?

**Comment by znarf** [comment]
@NotJohs if @bigpreshy is not working on it, feel free to look at it

**Comment by NotJohs** [comment]
@znarf thanks a lot.

**Comment by znarf** [comment]
Thank you @NotJohs ! It's merged.

To claim the bounty, you can:

a) submit an invoice to https://opencollective.com/engineering
b) or ask for an Open Collective gift card of the same value (to donate to other collectives)
