### ISSUE TITLE
Error when trying to pay expense: "the pre-approval key can't be used before the start date or after the end date"

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2171]
As reported in [this ticket](https://opencollective.freshdesk.com/a/tickets/805) on Freshdesk and [this Slack message](https://opencollective.slack.com/archives/C6JTTA4SK/p1561644869061200). I have tried paying a few expenses myself and have not encountered an error.

**Describe the bug**
This error is coming up from Paypal when the host admin tries to pay an expense.

<img width="792" alt="pperror" src="https://user-images.githubusercontent.com/5498878/60312380-39d38200-99af-11e9-9c57-9c892276ccbc.png">

**Comment by Betree** [comment]
Response sent to user:

> This is because the PayPal pre-approval code has expired on 21 June (they expire after one year). You should be able to solve this by clicking on `Refill balance` and reconnecting PayPal.

![image](https://user-images.githubusercontent.com/1556356/60330392-a0967280-9992-11e9-8ca2-01e20eab9b93.png)

Closing this.

@alanna is there a place in the docs where I should add this? https://docs.opencollective.com/help/hosts/payouts?

**Comment by Betree** [comment]
Added better error message in https://github.com/opencollective/opencollective-api/pull/2180
