### ISSUE TITLE
Can't transfer funds from event to Collective or Collective to host due to currency mismatch

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2172]
**Describe the bug**
They are trying to transfer the balance from [this event](https://opencollective.com/net2van-meetup/events/google-analytics-101-master-class-for-nonprofits-taught-by-a-marketing-veteran-16534ev) to their Collective, and empty the balance of [this Collective](https://opencollective.com/techforgoodnz), but are encountering errors related to currencies.

Both issues are being encountered by the admin of the [TechSoup](https://opencollective.com/techsoup) fiscal host.

**Screenshots**

<img width="679" alt="techsoup1" src="https://user-images.githubusercontent.com/5498878/60312748-91262200-99b0-11e9-8ab6-7c5f15de0db7.png">

<img width="852" alt="techsoup2" src="https://user-images.githubusercontent.com/5498878/60312752-94211280-99b0-11e9-951a-2dcf234c09e6.png">

[Support ticket](https://opencollective.freshdesk.com/a/tickets/805)

**Comment by znarf** [comment]
This is not something we can support, so we'll help this person in the support channel.

We should disable these buttons if there is a currency mismatch, and explain why.

**Comment by xdamman** [comment]
Turns out the problem is that the currency of the event was USD instead of CAD. 
I'm creating another issue to make sure that when we create a new event, it takes the current of the parent collective, not of the host collective.

**Comment by xdamman** [comment]
I've manually fixed this issue in the database for the two events impacted. I've also created a pull request to make sure this doesn't happen in the future, see https://github.com/opencollective/opencollective/issues/2197
