### ISSUE TITLE
Expense submitted with no paypal address

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2173]
**Describe the bug**
[This expense](https://opencollective.com/nanoframework/expenses/8590) was submitted and approved with no Paypal address, which shouldn't be possible.

**To Reproduce**
I was not able to reproduce. When I try it won't let me submit without a Paypal address.

**Expected behavior**
Should throw an error and not let the expense through.

**Screenshots**
![Screen Shot 2019-06-28 at 3 20 11 PM](https://user-images.githubusercontent.com/5498878/60314953-b585fc80-99b8-11e9-87ed-54d2811c7f27.png)

**Comment by piamancini** [comment]
@alanna hmm we had this issue in the past. @xdamman fixed it I think. Do you need their email address to unblock you now?

**Comment by xdamman** [comment]
Not exactly sure why this happened. The problem is that right now we are recording the paypal address at the user level, not at the expense level. So if it changes, it changes for all expenses.

We should save it as a payout method connected to a (User) Collective and link the payout method to the expense. But that's a big refactoring (that I would consider doing in the redesign of the expense flow).

**Comment by znarf** [comment]
What if we record it directly in the `Expense` table?

**Comment by xdamman** [comment]
That would be a good first solution. 
```js
Expense.payoutMethod = {
  service: 'paypal', // or IBAN
  userid: 'paypal@email.com' // or IBAN number
}
```

Longer term, would be better to have a dedicated table (or re-use the `paymentMethods` table with a flag to know if this payment method can only send or receive money)

**Comment by znarf** [comment]
The initial diagnostic is wrong, the paypal email was properly submitted, it's just not appearing. Investigation in progress.

**Comment by znarf** [comment]
While troubleshooting this Collective last week, I forgot to add the `HOST` entry in the `Members` table. One of the effects was to make the `paypalEmail` invisible.
