### ISSUE TITLE
Core contributors unable to apply to host

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2178]
**Describe the bug**
Somehow [doorkeeper-gem](https://opencollective.com/doorkeeper-gem) got unlinked from its host (OSC), and now the core contributors ([Nikita](https://opencollective.com/nikita-bulai) and [Felipe](https://opencollective.com/felipe-philipp)) aren't able to re-apply. When they go to OSC's page, they don't see "Apply with your Collective, Doorkeeper-gem", only the option to create a new Collective. If they go via edit Collective > fiscal host, the same thing happens.

**Screenshots**
<img width="1429" alt="Open Source Collective 501c6 (Non Profit) - Open Collective 2019-06-28 09-46-33" src="https://user-images.githubusercontent.com/5498878/60390107-ceaabc80-9b22-11e9-8155-6720f0c70daa.png">

**Comment by xdamman** [comment]
I fixed it manually for them in the database.

We should revisit the process to apply to a host. It’s a bit hacky today. It works for the most common default case, but it quickly breaks down when you deviate from it (e.g. if you have more than one collective that doesn’t have a host, when there are already transactions in the collective, etc.)

**Comment by xdamman** [comment]
I’ll close this for now, this should be part of another issue to revamp the application process.
