### ISSUE TITLE
Event with blank name should not be allowed

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2179]
**Describe the bug**
If you try to create an event with no name, it will error and not let you do it. But if you create an event with a name, it will let you edit it, delete the name, and save. This creates a situation where you cannot edit the event again or delete it because there is no name string to click on.

See example here: https://opencollective.com/testcollective#events

**To Reproduce**
1. create event with a name
2. edit the event
3. delete the name
4. click save

**Expected behavior**
When trying to save it should error and say your event must have a name

**Screenshots**
<img width="648" alt="Screen Shot 2019-06-30 at 10 48 32 AM" src="https://user-images.githubusercontent.com/5498878/60390173-b9cf2880-9b24-11e9-9e2c-f46102918db2.png">

**Comment by znarf** [comment]
A $50 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

**Comment by alabobriggs** [comment]
I'll be working on this

**Comment by AsaoluElijah** [comment]
Hi @znarf , I'll love to know if this issue is assigned :octocat:

**Comment by znarf** [comment]
@AsaoluElijah if @alabobriggs is not on it, feel free to take it

**Comment by alabobriggs** [comment]
I am on it right now @znarf

**Comment by alabobriggs** [comment]
I've been able to find the bug but it is in API not front-end. I think the label should be updated @znarf

**Comment by znarf** [comment]
@alabobriggs you might be right, adding the api label

**Comment by sudo-kaizen** [comment]
@alabobriggs still working on this? I experienced this bug while solving another issue

**Comment by znarf** [comment]
This issue is now open for everyone.

**Comment by Betree** [comment]
:trophy: This issue is now completed by @Rexben001  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
