### ISSUE TITLE
Settings page for the collective

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#218]
When logged in as a core contributor ('MEMBER' for the backend), we should have access to a settings page for the collective (e.g. `/mochajs/settings`).

On that page we should be able to:
- [ ] Connect Twitter account
- [ ] Connect Meetup account
- [ ] Connect Github account
- [ ] Edit "thank you for your donation" email template 
- [ ] Edit "I'm now a proud backer" tweet template
- [ ] Edit "Thanks to our sponsors" monthly tweet template

**Comment by erickrico** [comment]
i added some setting i think should be editable from this view

### General
![general](https://cloud.githubusercontent.com/assets/18429104/17947187/449bd60e-6a11-11e6-9135-bf8e17543716.png)

### Social integration
![social empty](https://cloud.githubusercontent.com/assets/18429104/17947200/538ad4a8-6a11-11e6-9b9b-e4e0351907a4.png)
![social filled](https://cloud.githubusercontent.com/assets/18429104/17947204/57185924-6a11-11e6-9bdb-76b8df7d60d9.png)

### Mailing
![mailing](https://cloud.githubusercontent.com/assets/18429104/17947218/6963a016-6a11-11e6-9870-20510a036830.png)

### banking
![banking](https://cloud.githubusercontent.com/assets/18429104/17947234/79e2f07c-6a11-11e6-8dde-98750c179bc3.png)

please let me know if this settings are in the app or they should stay here

**Comment by piamancini** [comment]
I think we should move as much as we can to the front end, and away from
the app.

**Comment by xdamman** [comment]
Yes agreed. This is great Erick! Great job!
Ship it! :-)

**Comment by piamancini** [comment]
this is now obsolete because of V2
