### ISSUE TITLE
Events form does not let you correct errors

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2180]
**Describe the bug**
If you create an event but fail to fill in a required field, the system will throw an error when you click save. However, if you fix the problem, it will not let you save again. The only way to proceed is to reload the page, losing all the data you put into the form.

**To Reproduce**
1. Create event
2. Don't fill in a required field (event name, tier name) or try to use a duplicate slug
3. See error
4. fix problem
5. unable to click save

**Expected behavior**
If you fix the problem, the save button should become active again.

**Screenshots**
<img width="407" alt="Screen Shot 2019-06-30 at 10 43 59 AM" src="https://user-images.githubusercontent.com/5498878/60390200-68736900-9b25-11e9-8d88-2b178785f859.png">
<img width="564" alt="Screen Shot 2019-06-30 at 10 43 23 AM" src="https://user-images.githubusercontent.com/5498878/60390201-690bff80-9b25-11e9-9677-8f50e4032844.png">
<img width="251" alt="Screen Shot 2019-06-30 at 10 42 46 AM" src="https://user-images.githubusercontent.com/5498878/60390202-690bff80-9b25-11e9-8f01-33b89afb8031.png">

**Comment by znarf** [comment]
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

**Comment by gbless17** [comment]
I would like to take up this issue Am from OSCAFRICA

**Comment by saranshkataria** [comment]
@znarf when does this open to everyone?

**Comment by Betree** [comment]
@saranshkataria It is now open for everyone :wink:

**Comment by sudo-kaizen** [comment]
> A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)
> 
> This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

Hello @ Beetree, the More info link does not work. Could there be other places where this happens? I think the working link to that part of the repo has changed

**Comment by sudo-kaizen** [comment]
Now that this is opened to everyone, must someone still apply to be assigned to it before his/her PR can be considered?

I will like to be assigned to it ASAP

**Comment by Betree** [comment]
@sudo-kaizen The correct link is https://docs.opencollective.com/help/developers/bounties

**Comment by Betree** [comment]
:trophy: This issue is now completed by @sudo-kaizen 

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
