### ISSUE TITLE
Unable to approve Collective due to permissions error

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2181]
**Describe the bug**
When trying to approve [this Collective](https://opencollective.com/open-austin) in Open Collective Foundation (via clicking approve in the email), it says "Error: You need to be logged in as an admin of the host of this collective to approve it". But I am the admin and logged in. I can access "edit organization" for the host.

**Screenshots**
<img width="1272" alt="Screen Shot 2019-06-30 at 8 22 45 PM" src="https://user-images.githubusercontent.com/5498878/60394227-27a34080-9b75-11e9-904c-c3a97aee85e6.png">

**Comment by znarf** [comment]
@alanna The Collective moved to another host: https://opencollective.com/openaustin

**Comment by alanna** [comment]
OK. In that case the error message is misleading. Maybe we should add the host name to the approval screen to make it clearer which host it's referring to?

**Comment by alanna** [comment]
Closing this. I'll raise a new issue for the small change to make it clearer what host is being referred to.
