### ISSUE TITLE
Monthly report recent sponsor activity: collectives are not grouped correctly

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2185]
In the monthly collective report, one of the line for the `Recent sponsor activity on Open Collective` is confusing:

> Creative Tim - Theme Affiliations gave $8,387.94 to Material-UI, $6,347.52 to Material-UI

Both `Material-UI` are pointing to https://opencollective.com/material-ui, it seems that should be grouped and the amounts summed.

![image](https://user-images.githubusercontent.com/1556356/60434286-17d43c80-9c07-11e9-9a5d-3f285983ed7c.png)

**Comment by piamancini** [comment]
hmm I wonder why there are two I think we missed one and did it both in one month. @alanna want to dig this up?

**Comment by alanna** [comment]
Yep Pia remember I said I have a calendar reminder to add the Create Tim
funds and I thought I already did it last month, but you also did it
because you remembered we don't get notifications for it.

Right now we can't refund manually added funds so I don't know how to fix
this.

**Comment by piamancini** [comment]
@alanna, I'm only seeing this now for some reason... Let's discuss.

**Comment by Betree** [comment]
Platform reports have been removed in https://github.com/opencollective/opencollective-api/pull/7482
