### ISSUE TITLE
Submitted an expense 11 days ago but still not get paid.

### ISSUE THREAD

**Issue by t-k-** [opencollective/opencollective#2186]
**Describe the bug**
Submitted an expense 11 days ago but still not get paid.

**To Reproduce**
As the core member, I submit an expense 11 days ago

It should have enough balance for what I've requested for, but no new transaction has been issued.

Here is my collective:
https://opencollective.com/approach0

**Comment by znarf** [comment]
Please contact support http://opencollective.com/support
