### ISSUE TITLE
Forum is going down

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2187]
forum will be down today: 
we need to 

- [x] remove link from footer
- [x] update the DNS records and remove the CNAME pointing to their servers (@znarf)
- [x] look into the automated emails to see where it's mentioned and remove it (@piamancini)
- [ ] remove it from documentation (@alanna)

**Comment by znarf** [comment]
There is no link in the footer from quite some time right?

**Comment by piamancini** [comment]
you are right. 
(side note @alanna there is a link to /opensource there for when we make the slug swap)
