### ISSUE TITLE
Indicate the fiscal host when approving a new Collective

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2188]
## User story 
As a fiscal host admin, when I am approving a Collective, I would like the screen to display the host name, so I can understand what's happening if it fails.

## Best solution for this problem
When a new Collective applies to a host, the admin gets an email. If they click "approve" they are sent to a page where it says "approving" then either "done" or an error if it fails. Recently it failed and I couldn't understand why. It turned out that the Collective had changed fiscal hosts after applying, but I could not see that host name. (See #1927) Let's add the host name somewhere on the approval screen you see after clicking the email link.

**Comment by znarf** [comment]
A $50 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

**Comment by osumgbachiamaka** [comment]
I am from open source meetup ph will like to solve this issue #bounty
