### ISSUE TITLE
Self-serve flow to create a new collective

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#219]
Let's build a simple self-serve flow to create a new collective. Initially, let's assume that only we will be using this internally. So, a hidden url.

Here's the form we currently use: https://opencollective.typeform.com/to/MT1gcO

What info do we absolutely need?
- Core contributors' info: email, name
- Collective: name, slug, mission, description, website_url, logo

Info we can add afterwards
- add hero image (easy to do with an edit button on top)
- add main collective image

Backend tasks
- create user accounts for all core contributors and the main user
- create collective with provided info
- add users to collective as `MEMBERS`
- Support showing the collective without any tiers and transactions when there is no host. Add dummy sections in place until enabled.

Tasks we are specifically punting:
- any money related setup: no host is being added (this may require some backend tweaks), no tiers are being added, etc.

@piamancini @xdamman Anything you want to add/modify in this?

**Comment by piamancini** [comment]
Add afterwards
[ ] why join 
[ ] add video
[ ] currency?

Backend tasks
[ ] there's a host demo account, we can use that as the default host as well. 
[ ] turn ispublic to TRUE

Questions 
Any automation for tags, settings?

**Comment by asood123** [comment]
api: https://github.com/OpenCollective/opencollective-api/pull/574
website: https://github.com/OpenCollective/opencollective-website/pull/418

supports all the things we talked about above. No automation for tags or settings right now.

**Comment by asood123** [comment]
Open bugs:
- [ ] image uploads give random errors
