### ISSUE TITLE
Spinning logo looks buggy when image is not loaded

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2191]
**Describe the bug**
I had this bug a few times on mobile and desktop. It's especially visible when using a slow connection. Normally the logo is rotating while the page is loading:

![Peek 02-07-2019 16-21](https://user-images.githubusercontent.com/1556356/60520302-71ab3400-9ce5-11e9-9e11-70a2257229f7.gif)

But if the image is not loaded yet the alt text produce a very strange looking results.

![Peek 02-07-2019 16-16](https://user-images.githubusercontent.com/1556356/60520026-f47fbf00-9ce4-11e9-9779-d0d693643271.gif)

![Peek 02-07-2019 15-54](https://user-images.githubusercontent.com/1556356/60520027-f5185580-9ce4-11e9-844c-53da34786a6b.gif)

**To Reproduce**
1. Throttle your connection
2. Go to https://opencollective.com
3. Hard refresh (CTRL+F5)

**Expected behavior**
The easy step would be to set `alt=""` on the logo, that way we don't who anything while loading the image.

But I know @opencollective/design had some concerns about this feature so it would be great to have their opinion on this.

**Comment by znarf** [comment]
Classic :-/

**Comment by raulgrafico** [comment]
While using Safari, the browser sometimes only loads the top of the website, so the logo remains spinning forever until you scroll the site all the way down to load all the content.
