### ISSUE TITLE
Sign-in link can be used multiple times over a long time period and on different devices

### ISSUE THREAD

**Issue by udoprog** [opencollective/opencollective#2192]
**Describe the bug**
Sign-in links ~don't expire~ has a long expiration, can be used multiple times and could employ stronger security practices.

**To Reproduce**
1. Go to https://opencollective.com/ and click "Sign In"
2. Sign in using your email through the provided link.
3. Sign in again:
   * Open another incognito tab and use the same link to sign in again.
   * Open the link on a different device and use the same link to sign in again.
   * Open the link in an incognito browser over a VPN.
   * Wait 24 hours and use the same link to sign in again in another incognito tab (tested a couple of months back, the longest I've waited this time around is 6 hours).

**Expected behavior**
After logging in the first time the link should no longer be valid.

**Additional context**
Anyone who has access to the link in the email can seemingly use it to sign in to another account.

Since the closest convention that this login method matches is email-based password resets, it would be worthwhile making sure similar security best practices are in effect.

Stackoverflow: https://security.stackexchange.com/questions/1918/can-anyone-provide-references-for-implementing-web-application-self-password-res
Linked article: https://www.troyhunt.com/everything-you-ever-wanted-to-know/ (warning: **nsfw** picture in the article)

Some of the relevant suggestions are:
- [ ] **Require a CAPTCHA**
- [ ] **Include a time limit** - the link should only be usable once, and should immediately expire as soon as it is used.
  * Partly solved in #2206 (15 minute time limit)
- [ ] **Include explanatory text in the email** - in particular, include a cancellation link which the user can click which provides feedback if a login attempt has been successful (in which case the link was followed by someone else).
- [ ] **Monitor cancellations** - I'm assuming this doesn't happen since there is no cancellation button.

It would also be good if you could allow users to enable 2FA as a preventative measure.

Related: #1746, #1738

**Comment by znarf** [comment]
In the current implementation, the expiration for login links is exactly 24 hours. There is effectively no other invalidation mechanism at the moment.

**Comment by piamancini** [comment]
hi @udoprog Thank you for opening this issue! I followed the conversation on reddit. As @znarf mentioned, time limit is now 24h. This is something we've been wanting to upgrade for a while now, thanks for pushing us to re think about it. We'll have a chat about potential (and feasible) next steps for us and update this issue.

**Comment by znarf** [comment]
As a follow up, we should spec an upgrade of the authentication token, to make them one-time and cancellable. We can use our volatile storage for that.

**Comment by eric-s-raymond** [comment]
Been having this conversation by email with Alanna Irving, but it seems like a good idea to have it on the record here.

That change to 15 minutes screwed over everyone using greylisting for anti-spam.

You should never, ever pull that timeout below twice the SMTP minimum retry interval in RFC5231, which turns out to be 30 minutes.  Actually you should find out what the retry interval on your mailer is (it could be larger) and double that, then add a bit of buffer (say 15 minutes) for human lag.

The reason: You want there always to be time for one full retry before the token times out, otherwise greylisting receivers who return a "temporarily unavailable" first time to throw off spammers will always lose.

**Comment by znarf** [comment]
This was set to 75 minutes in https://github.com/opencollective/opencollective-api/pull/2291

**Comment by sbinlondon** [comment]
@znarf do you want to assign this issue to me or is it ok to just reference it in my PR?

**Comment by znarf** [comment]
@sbinlondon you are assigned now.

**Comment by sbinlondon** [comment]
Can this one be closed now if everything has been merged? @Betree @znarf

**Comment by Betree** [comment]
@sbinlondon The new invalidation mechanism is in place, but we haven't enforced the actual invalidation yet to ensure that we're not missing any edge-cases. We'll be monitoring the logs to iterate on this shortly.

**Comment by znarf** [comment]
@Betree I activated it in production last week. Not proud of the 4 different attempts it took me, but here we are. https://github.com/opencollective/opencollective-api/pull/2838 https://github.com/opencollective/opencollective-api/pull/2862 https://github.com/opencollective/opencollective-api/pull/2863 https://github.com/opencollective/opencollective-api/pull/2867 On top of my first refactor https://github.com/opencollective/opencollective-api/pull/2822

**Comment by sbinlondon** [comment]
Is there anything else I can help with?

**Comment by znarf** [comment]
Closing. We now have a sensible time limit and the links can be used only once.

We're also adding the originating IP address in the Sign In email for troubleshooting.
