### ISSUE TITLE
Add info when approving or rejecting expenses from email

### ISSUE THREAD

**Issue by mixmix** [opencollective/opencollective#2193]
I got an email saying there was an expense, I clicked the **Approve** button.
Site opened and I waited for .... 20-30 seconds while nothing at all showed up. Site appeared dead.

Then the page loaded and almost immediately jumped to this :

![image](https://user-images.githubusercontent.com/2665886/60552499-32332500-9d83-11e9-8ea6-1eda97622711.png)

I would just like to see the details of what expense I successfully approved. This is useful in case I clicked approve on multiple of them.
Not a big change, just a link "back to expense" or a summary of the expense or anything.

This is really important, especially in the context of such confusingly long load times.

**Comment by alanna** [comment]
Sort of related to #2188 - all approval screens should have basic info about what you're approving.

**Comment by Betree** [comment]
@mixmix We've had other reports of crazy load times from New Zealand. If you get more data about this at some point we'd love to have it so we can better understand what's the problem.

Regarding this specific issue I totally agree that we should display info about the expense that has been approved here. I also agree with @alanna's comment above:

> all approval screens should have basic info about what you're approving.

I'll try to see if we can create a simple pattern on the approval page so contributors can add details easily.

In the mean time, I'll try to see if we can have the full expense displayed here or at least the most important info (submitter, title, amount...etc).

**Comment by mixmix** [comment]
Yeah a simple improvement of basic info sounds perfect.

I'll try to snapshot asset and api load times if I hit a slow load in
future. Past couple of weeks we're noticeably better. Mysterious

**Comment by mixmix** [comment]
hey @Betree I just approved an expense and saw the solution to this issue in action!
my heart sang for the clarity I experienced in the process.

THANK YOU :heart: :heart: :heart:

**Comment by Betree** [comment]
Thanks for the feedback @mixmix! Really happy to hear that :smiley:
