### ISSUE TITLE
Enable VAT on a per collective basis

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2196]
Whether or not a collective falls into the VAT regulation depends on its status.

By default, a collective is an unincorporated partnership for which the host is just holding money on their behalf. In that case, it is the responsibility of the collective to register their own VAT number if needed to be.

Some hosts may offer collectives to be part of their entity. This could be necessary for examples to be able to receive some subsidies. In that case, they should use the VAT number of the host. It also means much more legal liability for the host so the terms and conditions should be different (at the discretion of the host). E.g. [CodeNPlay](https://opencollective.com/codenplay) hosted on Open Collective Brussels.

Given that the default should be that the VAT shoudn't apply for unincorporated partnership, I'd recommend to only apply the VAT if `collective.settings.vat` is set to `host` (i.e. use the VAT number of the host), or any given value (i.e. use this specific VAT number that belongs to this collective). If `collective.settings.vat` is `undefined` or `null` or `false`, then don't apply VAT.

**Comment by Betree** [comment]
The problem that I see is that we don't have any UI for collectives to manually enable VAT on their collectives/events. If we don't add the matching fields in the collective `/edit`, I'm afraid we'll end up disabling VAT in multiple places where it's actually required.

@xdamman So it the following todo correct?

- Add a `VAT` section in collective/event settings
  - Select { `No subject to VAT`, `Use host VAT`, `Use my own VAT number` => input }
- Change behaviour in frontend and API to apply VAT...
  - Only if `settings.vat` is set

**Comment by xdamman** [comment]
That’s correct. Not sure we need it for events though. They should just fall back to their parent collective’s VAT rule.

**Comment by alanna** [comment]
We do need this on a per-event and per-tier basis if we're going to apply it more generally than VAT. In the US, online purchases from another state don't trigger local sales tax but a local person buying a local event ticket does. We've got a Collective now figuring out how to set up sales tax for their event and they will need it to apply only to ticket tiers in that event, and not to their normal Collective sponsorship tiers.

**Comment by Betree** [comment]
@alanna In the case of VAT we do it per tier type (PRODUCT => taxed, DONATION => not taxed). But anyway this issue is specific to VAT, whatever tax we may want to implement for the US would have its own separate implementation. 

I would have loved to keep the initial "customizable taxes" feature that I worked on but it should have been better specified from the start and the need was not important enough to justify investing more time on it.

Please open a new issue for everything related to this US tax and tag me on it, I'll try to see how complex it would be.
