### ISSUE TITLE
New events should have the currency of the parent collective, not the host's

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2197]
This is the cause of #2172

**Comment by xdamman** [comment]
Only two events were impacted by this issue:
https://opencollective.com/net2van-meetup/events/google-analytics-101-master-class-for-nonprofits-taught-by-a-marketing-veteran-16534ev
https://opencollective.com/net2van-meetup/events/changemakers-summer-potluck-cmpotluck-16534ev

They were in USD despite their parent collective being in CAD.

To solve this I've temporarily changed their parent collective to be another collective on the same host but that is USD
https://opencollective.com/netsquared-administrative-collective

I was then able to move the remaining balance of these two events to that new parent collective.

Finally I made a donation of the equivalent amount in CAD to the original parent collective https://opencollective.com/net2van-meetup
(I've also restored the original parent collective for those 2 events)

**Comment by elijahv** [comment]
Thanks @xdamman I'm struggling with a related problem as I try to archive https://opencollective.com/techforgoodnz/

I want to Empty the Collective balance (which is in NZ) currency and send to "NetSquared Administrative Collective" (USD). But I get the error "Invalid currency. Expected USD."

<img width="965" alt="Screenshot_2019-07-03__4_48_PM" src="https://user-images.githubusercontent.com/3868907/60631073-68d46400-9db2-11e9-86c8-f1575d60e8ff.png">

**Comment by xdamman** [comment]
This is related but a different situation. 
I've manually emptied the balance of that collective so you should be good now.

Do you foresee to face this situation a lot?

**Comment by elijahv** [comment]
Thanks! I anticipate running into a similar situation at least twice a year as chapters of my network come and go..
