### ISSUE TITLE
Archive past events

### ISSUE THREAD

**Issue by elijahv** [opencollective/opencollective#2199]
## User story 
_As <administrator>, I can <archive or "hide" past events> so that <I have a clean collective page and don't confuse my members.>_

## Best solution for this problem
Ability to "archive" old events so that only Core Contributors can see the events. 
Archiving would only be possible for events that are:

* past
* has balance at zero (ie. balance transferred to main collective)

## MVP
_What will be built as an MVP? (Please refer to our [wiki](https://github.com/opencollective/opencollective/wiki/Feature-Spec-Template) for what's acceptable as an MVP.)_

## Metrics 
_What metrics will be used to measure impact?_

## Documentation 
_The goal of the documentation should be to make it easier for others to do this_

**Comment by shannondwray** [comment]
Duplication: https://github.com/opencollective/opencollective/issues/6495
