### ISSUE TITLE
Display event year

### ISSUE THREAD

**Issue by elijahv** [opencollective/opencollective#2200]
## User story 
_As <user>, I can see WHEN an event is/was scheduled so that I can identify if an event is past or upcoming.

## Best solution for this problem
Add event YEAR to event pages.

<img width="1131" alt="Screenshot_2019-07-03__4_54_PM" src="https://user-images.githubusercontent.com/3868907/60631418-2f045d00-9db4-11e9-9037-bbac91926260.png">

<img width="808" alt="Screenshot_2019-07-03__5_02_PM" src="https://user-images.githubusercontent.com/3868907/60631485-738ff880-9db4-11e9-9764-5cabe34cb39e.png">

## MVP
_What will be built as an MVP? (Please refer to our [wiki](https://github.com/opencollective/opencollective/wiki/Feature-Spec-Template) for what's acceptable as an MVP.)_

## Metrics 
_What metrics will be used to measure impact?_

## Documentation 
_The goal of the documentation should be to make it easier for others to do this_

**Comment by Betree** [comment]
# Specs

- [ ] Show year on event's cover for `endsAt` (https://github.com/opencollective/opencollective-frontend/blob/6cc7d93415ce92cff9877f48307179383c1b0af8/components/CollectiveCover.js#L139)

- [ ] Hide `tickets` button on the event's cover if the event is passed already 

- [ ] In `EventsWithData`, show the year of the event (https://github.com/opencollective/opencollective-frontend/blob/7a19d5e85e765c3f333fadc7888b6fc2ad84c501/components/EventsWithData.js#L66)

**Comment by Betree** [comment]
A **$50** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged.

:warning: This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

:arrow_right: [More info](https://github.com/opencollective/opencollective-frontend/edit/master/BOUNTY.md)

**Comment by Rexben001** [comment]
Working on this from OSCA Lagos

**Comment by Rexben001** [comment]
https://github.com/opencollective/opencollective-frontend/pull/2282

**Comment by Betree** [comment]
:trophy: This issue is now completed. 

@Rexben001 To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
