### ISSUE TITLE
Unexpected error when visiting "Recurring financial contributions"

### ISSUE THREAD

**Issue by sloria** [opencollective/opencollective#2201]
# Describe the bug

I got an unexpected error on https://opencollective.com/sloria/subscriptions while I was trying to view my subscriptions.

# To Reproduce

1. Go to https://opencollective.com/<username>/subscriptions

# Device
- OS: macOS Mojave
- Browser: Firefox 67.0

**Comment by znarf** [comment]
@sloria thank you for reporting. there is something specific to your account that is triggering the error, we're looking into it.

**Comment by sloria** [comment]
OK, no rush on this on my end. Let me know if I can help diagnose.

**Comment by znarf** [comment]
Seems a collective you pledged to was deleted (pytest). This is an unexpected case. If that's right, I can delete the pledge.

They joined the platform with a different account: http://opencollective.com/pytest

**Comment by sloria** [comment]
Yes, go ahead and delete the pledge.

**Comment by znarf** [comment]
Done!
