### ISSUE TITLE
Change button link on "new expense approved" email from "view all expenses" to "view expense" to see that specific one

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2203]
## User story 
As an expense submitter, Collective Admin, or Host Admin, I want to be able to go from the "expense approved" email to that expense's page directly, instead of all Collective expenses.

## Best solution for this problem

Change the button link to point to that expense URL.

## How to do it

Edit the template file.

https://github.com/opencollective/opencollective-api/blob/master/templates/emails/collective.expense.approved.hbs

**Comment by znarf** [comment]
A $50 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

**Comment by alabobriggs** [comment]
I'll be working on this

**Comment by Akumzy** [comment]
I'll like to work on this

**Comment by alabobriggs** [comment]
The file specified for this issue does not contain a 'view all expenses' button. The link to the file is 'https://github.com/opencollective/opencollective-api/blob/master/templates/emails/collective.expense.approved.hbs'

**Comment by znarf** [comment]
@alabobriggs The author of the issue should be talking about the "View Latest Expenses" link.

**Comment by alabobriggs** [comment]
Alright thank you.

**Comment by znarf** [comment]
While doing it, would be great to tackle https://github.com/opencollective/opencollective/issues/2209 at the same time.

**Comment by Gbahdeyboh** [comment]
I'm from OSCA and i'm working on this issue

**Comment by Gbahdeyboh** [comment]
https://github.com/opencollective/opencollective-api/pull/2363

**Comment by Betree** [comment]
@alanna There's already a link to the expense in the email template you mentioned:

![image](https://user-images.githubusercontent.com/1556356/62446105-29f34e80-b762-11e9-92e7-9e4d8334c8c1.png)

I think the one you're thinking about is `collective.expense.approved.for.host.hbs` (this one doesn't have any link to the expense):

![image](https://user-images.githubusercontent.com/1556356/62446285-a128e280-b762-11e9-8562-166b738917e7.png)

**Comment by NotJohs** [comment]
@znarf I have reviewed this issue and so far I understand that the email template 
https://github.com/opencollective/opencollective-api/blob/master/templates/emails/collective.expense.approved.hbs
at line 5 provides a link to the expense.
so my question is,  is this enhancement needed?

**Comment by Betree** [comment]
@NotJohs As per [my comment](https://github.com/opencollective/opencollective/issues/2203#issuecomment-518118058) above the correct template is `collective.expense.approved.for.host.hbs`

**Comment by NotJohs** [comment]
@Betree understood.

**Comment by znarf** [comment]
🏆 This issue was completed by @NotJohs

To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
