### ISSUE TITLE
Implement Twitter Card on Collective Page

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2206]
Similar to Facebook (see https://github.com/opencollective/opencollective/issues/2137), when sharing on Twitter we want links to Open Collective to appear in the best possible way.

To do that, we might want to use Twitter Cards:
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started.html

How should it look?

- Title: `collective.name` - Open Collective
- Description: `collective.description`
- Image: `collective.image`
- twitter:creator: `collective.twitterHandle`
- twitter:site: @opencollect

To make sure that it works, please use the Twitter Card Validator (https://cards-dev.twitter.com/validator) with the URL of the automatically deployed branch, e.g. https://opencollective-frontend-vwfxtupsdr.now.sh/babel
![](https://d.pr/free/i/A1dWi7+)

**Comment by znarf** [comment]
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

**Comment by mykeels** [comment]
I'm interested in working on this

**Comment by NotJohs** [comment]
I am taking up this issue.

**Comment by doncitymail** [comment]
This issue is mine

**Comment by NotJohs** [comment]
@znarf can this issue be closed?

**Comment by znarf** [comment]
Thank you @NotJohs  ! It's merged.

To claim the bounty, you can:

a) submit an invoice to https://opencollective.com/engineering
b) or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Comment by NotJohs** [comment]
@znarf submitted an invoice.
