### ISSUE TITLE
Support AliPay and WeChat payments system

### ISSUE THREAD

**Issue by XVilka** [opencollective/opencollective#2207]
They are very popular in China and the neighborhood ring. And apparently Stripe supports both of them:

- AliPay https://stripe.com/docs/sources/alipay
- WeChat https://stripe.com/docs/sources/wechat-pay

With China's middle class and IT community growing it might give you a significant increase in transactions.

**Comment by piamancini** [comment]
yes, we've looked into it in the past. Thanks for brining it up again.

**Comment by znarf** [comment]
Related: https://github.com/opencollective/opencollective/issues/919

**Comment by ai** [comment]
Just recently got an email from Chinese users, that they want to donate, but don’t have Paypal account and WeChat will be the best option.

Chinese market is very big. We definetly should support it.

**Comment by nicolo-ribaudo** [comment]
A person just opened a discussion in Babel's repository (https://github.com/babel/babel/discussions/13318) asking us if we can accept donations via Alipay, since it would make it way easier for developers from China to sponsor us.

I know that this is probably a big thing to implement, but I'm :+1:ing this feature request!

**Comment by BenJam** [comment]
🙌 https://github.com/opencollective/opencollective/issues/4200

**Comment by ai** [comment]
@BenJam crypto donations is not so useful for Chinese users as payment in WeChat

**Comment by BenJam** [comment]
I'm going to close this out in favour of #4200 which is in a weird state as @piamancini and I need to work through compliance issues post development.
