### ISSUE TITLE
Sort not working on Discover

### ISSUE THREAD

**Issue by maddhruv** [opencollective/opencollective#2208]
**Describe the bug**

**To Reproduce**
1. Go to 'https://opencollective.com/discover?show=all&sort=true&offset=0'
2. Click on 'Most Popular/Newest'
3. Scroll down to 'Collectives'
4. See error - The collectives are not sorted

**Expected behavior**
The collectives should be sorted as per the filter, Most Popular or Newest

**Screenshots**
<img width="1246" alt="Screenshot 2019-07-07 at 20 40 05" src="https://user-images.githubusercontent.com/18121502/60770326-79a91080-a0f7-11e9-93ab-af870fb064a8.png">
<img width="1246" alt="Screenshot 2019-07-07 at 20 39 55" src="https://user-images.githubusercontent.com/18121502/60770328-7f065b00-a0f7-11e9-9420-cd136adf1ac3.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 75

**Smartphone (please complete the following information):**

**Additional context**

**Comment by znarf** [comment]
Was that broken in https://github.com/opencollective/opencollective-frontend/pull/1999 while fixing https://github.com/opencollective/opencollective/issues/1387?

**Comment by Betree** [comment]
@maddhruv Thanks for reporting this! This issue will be solved by https://github.com/opencollective/opencollective-frontend/pull/2188 when deployed
