### ISSUE TITLE
Change buttons in "expense paid" email to link to that expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2209]
## User story 
As an expense submitter or host admin, I want to be able to jump from the notification email of a paid expense directly to that expense to see details or make a comment.

## Best solution for this problem
Change the buttons from "Submit Another Expenses" and "View All Expenses" to just one "View Expense" which takes you to that page.

<img width="950" alt="Screen Shot 2019-07-08 at 12 09 42 PM" src="https://user-images.githubusercontent.com/5498878/60775659-7bb3b380-a179-11e9-8ad7-1e762b0397b4.png">

**Comment by Betree** [comment]
Isn't `Mic for voice recording` already linking to the expense itself?

**Comment by alanna** [comment]
Yes it is! Wow I didn't even notice that. I guess this is more design feedback than a feature request then.
