### ISSUE TITLE
List expenses on user profile page

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2210]
## User story 
As a code or service contributor, I want to show off my contributions to Collectives that I have been paid for.

As an admin, I want to see all the expenses paid to a specific user so I can track down issues or documentation easily.

Currently we show contributions, admin roles and events on the user profile page, but not a history of expenses submitted.

This will also become more important as we build up value-added services as something Open Colletive is facilitating. The profile page as a CV where someone can show off the work they have done for Collectives.

## Best solution for this problem
List of expenses the person has submitted. Could be a card design like contributions and admin roles are now, or use the same design as how we show expenses on a Collective page. It should clearly show the name of the expense, amount, date, and what Collective it was for, and link to the individual expense page.

**Comment by piamancini** [comment]
yes, this is something we've discussed in Brussels for the expense flow from the use case of a collective admin who wants to see the same info. cc @raulgrafico is this in the spec doc already?

**Comment by piamancini** [comment]
Adding bounty candidate here @Betree. Since we already show the donations made in a user's profile, it seems that surfacing the expenses as well should be doable.

**Comment by Betree** [comment]
@piamancini With the upcoming v2 we're going to kill the exising users profiles, do we want to invest on adding this to the current profiles?

**Comment by piamancini** [comment]
ah of course. Are we adding this feature to v2 though?

**Comment by Betree** [comment]
@raulgrafico Can you confirm?

**Comment by znarf** [comment]
Looks like this was implemented.

![Screenshot 2019-09-16 at 21 05 35](https://user-images.githubusercontent.com/806/64985711-cbbf9c80-d8c5-11e9-9ef1-b7d43166a521.png)

Should we close?

**Comment by Betree** [comment]
Yes, we need to iterate on that one but the base feature is implemented

**Comment by alanna** [comment]
Unfortunately what we built doesn't meet the whole need. We show *transactions* on the new profile page, which are completed payments. We still have a need to show all expenses related to a user, regardless of status (pending, approved, etc).

**Comment by Betree** [comment]
https://github.com/opencollective/opencollective-frontend/pull/2596 will show the 10 latest expenses for user, but to solve this issue completely we'll need to apply that to the transactions page. Should be done with https://github.com/opencollective/opencollective/issues/2434.
