### ISSUE TITLE
NCP: Improve the look of "Top contributors" when there are few

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2212]
For collectives that have no organizations (or almost none) as contributors, the "top contributors" section is weird.

I'd make it optional to add it.

I'd also consider having top individuals on the left and top organizations on the right. People first.

See https://opencollective.com/xr-belgium/v2
![](https://d.pr/free/i/B1IrUz+)

**Comment by Betree** [comment]
Also on http://opencollective.com/captainfact_io/v2 that has literally 0 orgs the section looks empty:

![image](https://user-images.githubusercontent.com/1556356/60827708-14b1f100-a1b1-11e9-8c73-d9d9285a1415.png)

Here's the solution I've been considering to try to always display the 4 columns:

- If no org is donating, show 20 individuals instead (4 columns).
- If less than 5 orgs are donating, show 15 individuals instead (1 column for orgs, 3 for individuals).

Same thing the other way around (though that happens more rarely) if no individuals or few, complete the empty space by showing more orgs.

---

> I'd also consider having top individuals on the left and top organizations on the right. People first.

@raulgrafico do you prefer to have these kind of design feedback here or on Figma?

**Comment by Betree** [comment]
Also ideas to consider:
- Don't show `Individuals` or `Organizations` labels when there's only one of the two categories
- Display contributors in row (instead of columns) when they're less than 20

**Comment by piamancini** [comment]
@betree I think they'll look at figma more than github. Also for #2212

**Comment by raulgrafico** [comment]
@Betree I think it is a lot easier to find feedback on Github than Figma, let's keep using Github. I'm going to make the updates on Figma and create scenarios with different combinations.

**Comment by Betree** [comment]
@raulgrafico No need to work on this one, https://github.com/opencollective/opencollective-frontend/pull/2122 already solves the issue.

**Comment by Betree** [comment]
Also improved in https://github.com/opencollective/opencollective-frontend/pull/2129
