### ISSUE TITLE
Add total amount contributed to list of contributors

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2214]
We should be able to see what is the total amount contributed by each contributor (like we do today on the collective page)

![](https://d.pr/free/i/oy6OgS+)

**Comment by Betree** [comment]
It's not fully implemented yet, but the final design will include the amount donated each month: 

![image](https://user-images.githubusercontent.com/1556356/60828656-40ce7180-a1b3-11e9-971d-fcc44bb5628b.png)

Adding new information on these cards requires an update on design: we already reached the limit with the existing mockups:

![image](https://user-images.githubusercontent.com/1556356/60828802-b20e2480-a1b3-11e9-8871-74b1d500ed40.png)

Ping @raulgrafico

**Comment by Betree** [comment]
This has been tackled as part of the pre-release blockers
