### ISSUE TITLE
Missing link to view all expenses

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2215]
It would be good to add the latest expenses on the collective page.

At the very least we should add a link to view all expenses but ideally we could add a link at the top of the transactions saying: 

> ☝️ There are 3 expenses pending approval and 2 expenses approved that still need to be paid by the host

![](https://d.pr/free/i/ypwZ7i+)

**Comment by Betree** [comment]
Latest expenses should be displayed, if they're not then it's a bug.

+1 for a link to view all the expenses

**Comment by xdamman** [comment]
Ah could be, but it's not clear that they are expenses and not transactions.
So we should be explicit about it (i.e. "Expense by Tiny Brains") and add the status of the expense with a link to it.

**Comment by Betree** [comment]
I still have some tweaks to do to make it look like the design, I find the fact that the left circles serves either to show an avatar or to display an icon confusing, but I think that's personal taste. Anyway the icon should help, as well as the status of the expense (`Pending approval`):

![image](https://user-images.githubusercontent.com/1556356/60832078-58a9f380-a1bb-11e9-9cb5-072a3d27f85f.png)


I'll add the link on the title as well, I forgot this one.

**Comment by xdamman** [comment]
Yes, that’s indeed confusing to reuse the same spot and shape for two different concepts.
It’s also weird to have the avatar as part of a tag. It’s too small, it’s two different concepts that are not linked together. I’d keep the tag simple (actually it’s the expense category).

@raulgrafico can you take a look and come up with a solution?

Basically, an expense is a pending transaction. I’d just be very explicit and say “Expense by...”

**Comment by Betree** [comment]
There is also a comment on Figma for this avatar issue: https://www.figma.com/file/e71tBo0Sr8J7R5n6iMkqI42d/OC.COM-07-%2F-Collectives?node-id=3880%3A538

**Comment by Betree** [comment]
Resolved in https://github.com/opencollective/opencollective-frontend/pull/2604
