### ISSUE TITLE
Add explanation about estimated budget

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2216]
The balance not the estimated budget should be in bold
Would also be good to add a (i) icon that people can hover to get a short explanation about how the estimated yearly budget is computed.

![](https://d.pr/free/i/XbjyNE+)

**Comment by Betree** [comment]
I asked for a copy to add in the tooltip displayed when hovering `Estimed annual budget` on Figma but received no answer (https://www.figma.com/file/e71tBo0Sr8J7R5n6iMkqI42d/OC.COM-07-%2F-Collectives?node-id=3880%3A538).

I can propose the following one:

> This is the projection of the annual budget based on previous donations and existing recurring donations.

**Comment by piamancini** [comment]
This is super confusing for people in general. We should also specify how we calculate it.  Is it calendar year? Is it 12 months projections? What happens with one time donations?

**Comment by alanna** [comment]
@Betree sorry I didn't see your request about copy. Can you please tag me on future copy requests?

> Projected annual budget based on previous recurring financial contributions.

@piamancini is bringing up a good point that this number causes some problems currently. One example was Babel got a one-time big grant and it really skewed their annual budget numbers, making it look like they had a lot more money than they actually would once that one-time grant ran out. This will be the case for any large on-time contribution - it will skew the numbers.

An idea to give a more realistic budget view:

* Show 'total financial contributions so far' - all time total
* Separately, show "total recurring contributions"

**Comment by xdamman** [comment]
I agree that we should simplify and bring some clarity here.

What about changing this to “Yearly Budget (Total financial contributions in the past 12 months)”?

**Comment by piamancini** [comment]
+1 @xdamman

**Comment by DeolaJ** [comment]
My name is Adeola (from OSCA Lagos). I have picked this issue

**Comment by DeolaJ** [comment]
Please how can I navigate to this page?

**Comment by Betree** [comment]
Hello @DeolaJ, this issue is not part of the OSCA event. Please check https://github.com/opencollective/opencollective/issues?q=is%3Aopen+is%3Aissue+label%3Aosca

**Comment by DeolaJ** [comment]
All right. Thank you
