### ISSUE TITLE
New collective page UX: adapt other pages that use the old cover

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2217]
# Problem

A lot of pages use the `CollectiveCover` component, which is the bloc displayed at the top of the legacy collective page. Navigating to such pages from the new collective page induces a confusing experience because the visual identity is very different:

![Peek 08-07-2019 19-46](https://user-images.githubusercontent.com/1556356/60831151-28f9ec00-a1b9-11e9-8d9a-237c49675350.gif)

The red part is the one to replace:

![image](https://user-images.githubusercontent.com/1556356/60831444-e8e73900-a1b9-11e9-95f4-c13f47380696.png)

# Where 

List of all the places where the old collective cover is used:

:arrow_down: = low priority / don't care
:arrow_up:  = high priority

- Create collective :arrow_down: 
- Create event :arrow_down:
- Create organization :arrow_down:
- Edit collective :arrow_up: 
- Edit event :arrow_down:
- Event :arrow_down:
- Host page :arrow_down:
- User page :arrow_down:
- Expenses list :arrow_up: (must also have "New expense" button)
- Create expense :arrow_down: (reached when we click "Submit expense")
- Create event :arrow_down:
- Transactions :arrow_up: (reached from the new collective page "All transactions")
- Update :arrow_up: (reached from the new collective page "Updates")
- Updates list :arrow_up: (reached from the new collective page "Updates")

# How to solve it

Most of these pages fetch data from the collective so we'll be able to know from the collective's settings if it uses the new version of the collective page and adapt the cover based on that.

We don't need something shiny (the less the better) but just something that stays in the mood of the new collective page.

**Requirements**

- Must have a way to go back to the collective page
- We need to find a way to display a button or a link to submit a new expense (in pink in the screenshot above) for the `/expenses` page (see http://opencollective.com/babel/expenses)

**Comment by raulgrafico** [comment]
Hi Ben, I added a new artboard to display the solution for this. Let me know if something is still missing.

**Comment by Betree** [comment]
Perfect, thanks @raulgrafico :ok_hand:

**Comment by Betree** [comment]
Resolved by https://github.com/opencollective/opencollective-frontend/pull/2254

To enable it, we need to set `settings.collectivePage.useV2` to `true`.
