### ISSUE TITLE
Add tags to expenses

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2218]
The collective [Agora](https://opencollective.com/agora) would love to be able to add tags to expenses so that they can keep track of how much they spend on e.g. facebook ads, a specific action/campaign, etc.

MVP could be using the same tagging input we have for collectives and add a `tags` column in the `Expenses` table.

Ideally, we should have a `Tags` table so that we can autocomplete and avoid having multiple tags spelled differently. Tags should be at the collective level. Maybe we should also consider global tags so that there is some convergence across collectives. I don’t have a strong opinion on this.

**Comment by alanna** [comment]
This would be great for budget tracking and reporting.

**Comment by piamancini** [comment]
I think this should be tackled in the new expense flow -I don't think it's worth spending time fixing something in the old one.

**Comment by piamancini** [comment]
closing this as it's incorporated in the design of expense flow
