### ISSUE TITLE
Hide horizontal scrollbar

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2224]
On desktop, can we make the scroll bar hidden by default and only visible on hover?
macOS is also hiding by default the scroll bar and only shows it when you are actually scrolling.

See https://opencollective.com/babel/v2
![](https://d.pr/free/i/QQ9kxs+)

**Comment by Betree** [comment]
These sticking scrollbars annoy me as well. Here's an experiment to show them when hovering the cards, would that work for you?

![Peek 09-07-2019 16-59](https://user-images.githubusercontent.com/1556356/60899565-f9a3b780-a26a-11e9-82ea-18ab76764aa9.gif)

**Comment by xdamman** [comment]
Sooooooo much better! ❤️❤️❤️😃
