### ISSUE TITLE
Add redirect from old OSC URL to new one

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2226]
We just changed OSC's URL to https://opencollective.com/opensource - but there are references to the old link in the wild, so we need a redirect from https://opencollective.com/opensourcecollective 

I hope we can do this quickly so people don't end up at a 404 until we find all the references and fix them.

Re: #2182

**Comment by alanna** [comment]
@znarf I added `priority` because I think this should happen ASAP

**Comment by znarf** [comment]
Done

https://github.com/opencollective/opencollective-workers/commit/550984209bb7b87e1f44ce6e6d199423c2e19b65

**Comment by alanna** [comment]
Thank you! <3
