### ISSUE TITLE
Add confirmation for "remove core contributor"

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2227]
Similar to #2167 and #2156 

We should confirm before proceeding when the user clicks "remove core contributor" in the edit core contributors screen.

**Comment by Betree** [comment]
# Specs

- Implement the feature specified above using a javascript `confirm`. 
- The message should be internationalized using `intl.formatMessage`. 
- If user clicks `no`, don't remove the contributor from the list
- The message should say:

> Do you really want to remove {Name} ({email}) from the core contributors of the collective?

---

Please follow our [code guidelines](https://docs.opencollective.com/help/developers/best-practices-and-code-guidelines), especially:

* The strings must be internationalized. See [/help/developers/translations](https://docs.opencollective.com/help/developers/translations)
* Whenever it's possible we must use `styled-components` to write styles. See [OC Styleguide](https://opencollective-styleguide.now.sh/)
* We're getting rid of `Bootstrap`. Please don't use it for new developments.
* When adding new dependencies, we use [fixed versions](https://docs.npmjs.com/about-semantic-versioning).
* Icons must be imported from the [styled-icons](http://styled-icons.js.org/) library.
* Tests written with Cypress must follow our [good practices](https://docs.opencollective.com/help/developers/testing-with-cypress) conventions.

**Comment by Betree** [comment]
A **$50** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged.

:warning: This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

:arrow_right: [More info](https://github.com/opencollective/opencollective-frontend/edit/master/BOUNTY.md)

**Comment by sudo-kaizen** [comment]
I choose to work on this

**Comment by Betree** [comment]
@sudo-kaizen it's all yours :)

**Comment by sudo-kaizen** [comment]
Okay. Thanks. How can I replicate this bug?

**Comment by Betree** [comment]
1. Create a collective
2. Go to the edit members page (`/{your_collective}/edit/members`)
3. Add members
4. Try to remove them with `remove Core Contributor`

**Comment by chidimo** [comment]
I raised a PR on this issue today at OSCA lagos.
Kindly take a look
https://github.com/opencollective/opencollective-frontend

**Comment by sudo-kaizen** [comment]
I've fixed this issue, but I'm having issues with merging. I'm still working on it

**Comment by Betree** [comment]
Resolved by @sudo-kaizen in https://github.com/opencollective/opencollective-frontend/pull/2285

:trophy: This issue is now completed. 

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

---

For more info about the bounty process and how to format your invoice, please read https://docs.opencollective.com/help/developers/bounties

**Comment by sudo-kaizen** [comment]
Awesome! Thanks!
