### ISSUE TITLE
Broken styles for "Submit Expense" button

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2231]
Most probably broken by https://github.com/opencollective/opencollective-frontend/pull/2123 (rebased in https://github.com/opencollective/opencollective-frontend/pull/2136)

Example: https://opencollective.com/drupal-diversity-and-inclusion-speaker-initiative

![image](https://user-images.githubusercontent.com/1556356/61071310-0d891e00-a411-11e9-8df4-4d0e3942b460.png)

**Comment by znarf** [comment]
Not sure how that was before, we can easily roll back.
