### ISSUE TITLE
Improve search with multiple tag selection

### ISSUE THREAD

**Issue by hestenet** [opencollective/opencollective#2232]
## User story 
As someone searching for collectives, I'd like to easily see what tags exist, and search a matrix of multiple tags together.

## Best solution for this problem
There are a few potential solutions - someone more well versed may want to chime in:

1. The opencollectives.com/search page could provide a tag cloud, and allow you to click-to-select/multi-select tags
2. The search bar on opencollectives.com/search (and the other places it appears) could allow some boolean logic - e.g: tag:drupal AND tag:training -- or even better, could allow auto completion of tags as you type. 

- In both cases, those search parameters should be added as url parameters so one can link directly to a filtered search. 

## MVP
Not knowing the structure for how tags and search are currently implemented, I'm unsure whether boolean syntax or a tag cloud would be an easier first pass to implement. 

## Metrics 
Fewer duplicate collectives? Better organization of 'chapter' collectives within larger projects? 

## Documentation 
The /search page itself should likely have in-place documentation of how to use this feature, and a real world scenario of why you would want to. "E.G: Are you looking to sponsor talent development in X open source project? Try a search for tag:<project> and tag:training!"

**Comment by alanna** [comment]
I really think we should invest in improving and using the tag system more. It comes up all the time as a way to group and find Collectives, hosts, expenses, etc.

**Comment by gusaus** [comment]
@hestenet This comment is an attempt to convey a similar Drupal need https://github.com/opencollective/opencollective/issues/2053#issuecomment-494623817 (obviously could be better described by a skilled technical PM!). https://github.com/opencollective/opencollective/issues/2230 & https://github.com/opencollective/opencollective/issues/2141#issuecomment-508313693 are related and should probably be considered _must have_ since the [first step of Drupal.org integration](https://www.drupal.org/project/drupalorg/issues/2138397#comment-13120773) will be more of an evaluation of the Open Collective platform. 

Definitely think there's an opportunity to combine resources and collaborate.

**Comment by gusaus** [comment]
Referencing https://github.com/opencollective/opencollective/issues/1745#issuecomment-474872514 as I 'think' what @hestenet is proposing would be a step towards providing a more granular search and discovery.

> I think improving the search and discovery would make it easier for foundations, nonprofits and other organizations to commit funding and resources.
> 
> * support campaigns that align with their mission or target vertical
> * support open source projects and communities they benefit from
> * provide training or mentorship
> * sponsor a meetup, hackathon, or working group that aligns with their mission or target vertical
> 
> Ideally supporters could filter their search on things like -
> 
> * Geographic area - projects or groups in my area
> * Category or vertical - Tech, Education, Nonprofit/NGO, Media/Publishing, Music, Community/Civic Participation, Social Impact, etc.
> * Project/collective type - Open source project, Meetup, Cooperative, etc.
> * Host type - nonprofit, for profit, etc.
> * Projects looking for talent - possibly filter on skill needs or demographics
> * Funding level - fully funded, projects with no funds, matching offers, etc.
> * Matching offers
> 
> https://www.donorschoose.org/donors/search.html provides some good inspiration for search and discovery

**Comment by kaylarep** [comment]
@SudharakaP sorry to reopen, is there a way to add the 'view more' option add the end of the suggested tag list?

![image](https://user-images.githubusercontent.com/64920686/174916134-f5737aaf-932b-43c3-b6aa-1ba4d4da1fa6.png)

**Comment by SudharakaP** [comment]
> @SudharakaP sorry to reopen, is there a way to add the 'view more' option add the end of the suggested tag list?
> 
> ![image](https://user-images.githubusercontent.com/64920686/174916134-f5737aaf-932b-43c3-b6aa-1ba4d4da1fa6.png)

This is encompassed by the new design and we'll iterate on this in the future. There's already and issue for this; https://github.com/opencollective/opencollective/issues/5622

**Comment by SudharakaP** [comment]
> 

I've created a new issue for this at, https://github.com/opencollective/opencollective/issues/5793 and suggested this on our Roadmap as well; https://github.com/opencollective/opencollective/discussions/5741#discussioncomment-3264149
