### ISSUE TITLE
Disable "donation" payment method

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2234]
There are expenses in the system like [this one](https://opencollective.com/volteuropa/expenses/8082) where they selected "donation" payment method. This is not documented or specified anywhere. My understanding was it was partially implemented but never really worked. We should not allow people to choose this option if it's not actually available. I don't know what to do with expenses like this.

@piamancini can you comment?

**Comment by znarf** [comment]
@alanna @piamancini what is the difference with? https://github.com/opencollective/opencollective/issues/1758

**Comment by piamancini** [comment]
same issue. Is a dupe. Mine could be titled better - 'in kind' was how we called the feature internally/
