### ISSUE TITLE
Images service does not support Gravatar

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2236]
With the migration of all images to the dedicated service we lost something useful: having images fetched from gravatar (see https://github.com/opencollective/opencollective-api/blob/f423207c3069bc599d5571f59cff8f3be670c8e3/server/models/Collective.js#L751). 

Would be great to have that back, @znarf would it be an easy change? All that's needed to generate a Gravatar image is the email address.

![image](https://user-images.githubusercontent.com/1556356/61128901-74f7aa00-a4b3-11e9-8aa6-e5f3dab23e61.png)

**Comment by znarf** [comment]
Why is it appearing on top?

Gravatar handling is currently API side. The `image` column is populated with gravatar when necessary.

**Comment by Betree** [comment]
My bad that's a localhost issue then
