### ISSUE TITLE
Proposal: Kill matching funds

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2237]
# Acknowledging
- That maintaining code for a feature always takes time (eg. tests need to be updated, bugs...)
- That unmaintained features can contain security issues, or be a vector for privilege escalation
- That the bigger/more complex the code base, the harder it is for newcomers to get on board

# And regarding the fact that...

- Matching funds has been dead since we deployed the new contribution flow (~6 months now)
- No one complained about it or asked for this particular feature (to my knowledge)
- Gift cards somehow fills the same needs of companies giving next to individuals
- It may not be too hard to re-implement with fresh code if needed in the future
- The feature hasn't been a success overall (see data below)

### Data: all matching funds currently on Open Collective (active + inactive)

<details>

```sql
SELECT c.slug AS from_collective, pm.name, pm."expiryDate", FORMAT('$%s', COALESCE(SUM(t.amount), 0) / 100) AS total_matched
FROM "PaymentMethods" pm
INNER JOIN "Collectives" c ON c.id = pm."CollectiveId"
LEFT JOIN "Transactions" t ON t."PaymentMethodId" = pm.id
WHERE matching IS NOT NULL
GROUP BY c.id, pm.id
```

</details>

| from_collective   | name                                     | expiryDate          | total_matched | 
|-------------------|------------------------------------------|---------------------|---------------| 
| xdamman           | Matching Fund #BrusselsTogether          | 2018-01-02 01:00:00 | $11           | 
| xdamman           | Matching Fund Open Collective            | 2018-01-01 01:00:00 | $132          | 
| opencollectiveinc | Matching Fund for Open Collective Paris  | [NULL]              | $0            | 
| opencollectiveinc | Matching Fund for Open Collective UK     | [NULL]              | $0            | 
| opencollectiveinc | Matching Fund for Open Collective Europe | [NULL]              | $0            | 
| notationcapital   | 7212                                     | 2018-03-10 01:00:00 | $102          | 

# I propose that

We kill the matching fund feature entirely:
- [ ] Remove all references left in the frontend (homepage/marketing included)
- [ ] We remove all the code for it from the API
- [ ] Re-enable https://github.com/opencollective/opencollective-api/blob/7509c2ea9cd80b4d4f769e8af1758337f78dd1cd/cron/daily/check_ledger_health.js#L189?

---

Resolve https://github.com/opencollective/opencollective/issues/1323

**Comment by xdamman** [comment]
Ok for me. We can always revive that flame once we have a concrete demand from a large donor.

**Comment by piamancini** [comment]
+1

**Comment by Betree** [comment]
Thanks for the quick feedback, this is now in my TODO.
