### ISSUE TITLE
Add an inter-page loader

### ISSUE THREAD

**Issue by maddhruv** [opencollective/opencollective#2242]
## User story 
When migrating from one page to another, it takes time to load the assets (obviously), but while doing the transition, we don't show any loader, if the user is on a Fast/Slow 3G he will not be able to see any transition happen after the anchor (`a`) is being clicked
Bad experience for users on slow network - feels like nothing is happening when clicking something

## Best solution for this problem
- Add a loader
- Prefetch required modules

## MVP
Improve user experience

## Metrics 
TTI for next page

## Documentation 
_The goal of the documentation should be to make it easier for others to do this_

**Comment by znarf** [comment]
We do have a loader, we use `nprogress`:
https://github.com/opencollective/opencollective-frontend/blob/master/src/pages/_app.js

It's a progress line on top of the screen, similar to the one at GitHub.

**Comment by maddhruv** [comment]
but it is not showing up properly
or say there is no proper indication that I clicked any navigation/anchor

**Comment by znarf** [comment]
Then it’s a bug. What’s your environment? From which page to which page?

**Comment by maddhruv** [comment]
I tried from / to /babel

**Comment by znarf** [comment]
Are you sure you're not seeing the blue progress bar on top?

![Screenshot 2019-07-14 at 14 03 39](https://user-images.githubusercontent.com/806/61183319-4ce98180-a640-11e9-98e1-397298c6a0b5.png)

What's your environment? Operating System? Browser?

**Comment by maddhruv** [comment]
Mac OS, Google Chrome
i will hard reload

**Comment by maddhruv** [comment]
yeah it is there
but mostly visible or noticeable when
the background is dark enough

**Comment by maddhruv** [comment]
we can also put a whole screen (content-level or component-level)
circular loader, that this content is being loaded
and unmounting those components

it feels like the past is gone
and something will be coming up here
in its place
