### ISSUE TITLE
Rename Organization, Collective and Profile Slugs

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#2247]
**Describe the bug**
I created an OpenCollective profile, organization and a collective. All of which are given below. I believe I tried creating and recreating them and thus the url slug has 1's and 2's at the end could you please rename these urls so that the 1 and 2 are removed? 

Profile: https://opencollective.com/sudharaka-palamakumbura1
Organization: https://opencollective.com/python-sinhala-education-society1
Collective: https://opencollective.com/python-sinhala-education-society2

Also one of the organization profiles I created before was not deleted completely; https://opencollective.com/python-sinhala-education-society

Related to issue: #529

**Comment by piamancini** [comment]
geez @SudharakaP sorry that this was your experience! Also sorry that we missed this issue until now. In the future, please feel free to email support@opencollective.com if your issue gets lost :) 

Your profile is fixed and now you have opencollective.com/python-sinhala-education-society-host for your organization and opencollective.com/python-sinhala-education-society-collective for the collective. I added the roles for clarity. 

please let me know if this works, you can edit the url as well.

**Comment by SudharakaP** [comment]
@piamancini : No worries 😄 Thanks much for solving the problem. Yes, I'll email directly if I have any further problems. 👍
