### ISSUE TITLE
Problems editing date input in the contributor settings

### ISSUE THREAD

**Issue by mojoaxel** [opencollective/opencollective#2249]
In the setting "Edit Core Contributors" there are problems editing the "Since" date:
* [ ] The date is not locally formatted ;-)
* [ ] Its hard to edit the date manually e.g. "10/26/2017" the date alsways gets changed one day back e.g. "10/25/2017". So if I want the date "10/26/2017" to be saved I have to input "10/27/2017" for it to work out.
* [ ] On the last entry the date-picker is covered:
![image](https://user-images.githubusercontent.com/600565/61188206-0580e680-a67c-11e9-988d-35650a612293.png)

**Comment by alanna** [comment]
Dup of #2161

**Comment by mojoaxel** [comment]
Closing as dublicate of #2161. Sorry folks!
