### ISSUE TITLE
Off By One error in markdown-embedded backer list

### ISSUE THREAD

**Issue by josegonzalez** [OpenCollective/OpenCollective#225]
Dokku has [10 backers](https://opencollective.com/dokku#backer) but only [9 show up](https://github.com/dokku/dokku#backers) in the readme, and the "Become a Backer" button links to the 10th person's webpage.

**Comment by piamancini** [comment]
Hi @josegonzalez it seems to be an issue from the github cache: https://github.com/OpenCollective/opencollective-api/issues/535

**Comment by josegonzalez** [comment]
Good catch. Will close as the issue was resolved on our end and it seems to be a dupe of the aforementioned issue.
