### ISSUE TITLE
Improve main website image pulled through to social media

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2250]
I posted a link to the main Open Collective homepage to Facebook today, and it pulled through a very odd image (apparently a screenshot of github issues??) - this should be changed to our logo or one of the cool illustrations on our front page.

<img width="527" alt="Screen Shot 2019-07-15 at 9 33 13 PM" src="https://user-images.githubusercontent.com/5498878/61207027-2c0c5380-a748-11e9-9b1d-21ceb1075d1a.png">

**Comment by znarf** [comment]
Effectively, this is picking one image from the home page because none is defined.

https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fopencollective.com%2F

This is being worked on by a contributor and was about to be fixed. But the PR was closed, I don't know why. https://github.com/opencollective/opencollective-frontend/pull/2149

**Comment by NotJohs** [comment]
@znarf @alanna am looking into this

**Comment by znarf** [comment]
Fixed https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fopencollective.com%2F

![Capture d’écran 2019-07-15 à 16 48 26](https://user-images.githubusercontent.com/806/61225217-6b26ae80-a720-11e9-9156-582ab508ff57.png)

I'm not sure about the image though.

**Comment by znarf** [comment]
@xdamman @alanna should we have a different image than that?

**Comment by NotJohs** [comment]
@znarf 
the recommended standards for images are:

**Comment by alanna** [comment]
I like this image from the homepage a lot better:

![Screen Shot 2019-07-16 at 1 02 12 PM (2)](https://user-images.githubusercontent.com/5498878/61258486-18093600-a7ca-11e9-99fd-80d15f65bde2.png)

But the logo image is already a big improvement!

**Comment by Betree** [comment]
[Updated](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fopencollective.com)

![image](https://user-images.githubusercontent.com/1556356/62353635-5bbea800-b50b-11e9-9517-c9080c512a59.png)

**Comment by alanna** [comment]
Nice!
