### ISSUE TITLE
Minor typo within welcome E-mail template

### ISSUE THREAD

**Issue by jamesgeorge007** [opencollective/opencollective#2252]
Recently I signed up on open collective for one of our projects - [Mevn-CLI](http://github.com/madlabsinc/mevn-cli)
> [mevn.madhacks.co](mevn.madhacks.co)

I just noticed a minor typo on the welcome E-mail that came out thereafter.
![Screenshot from 2019-07-17 17-46-41](https://user-images.githubusercontent.com/25279263/61375105-a7424680-a8bb-11e9-806d-d72694d8ec96.png)

Towards the end of the `Get & manage funds` section the word `approved` is misspelled as evident from above.

**Comment by znarf** [comment]
Thank you for reporting. Are you fancy creating a PR for it?

https://github.com/opencollective/opencollective-api/blob/f807ce3757e8e5adde8c7579499589728a8a906a/templates/emails/github.signup.hbs

**Comment by jamesgeorge007** [comment]
Sure :+1:

**Comment by jamesgeorge007** [comment]
@znarf Check out [#2273](https://github.com/opencollective/opencollective-api/pull/2273)

**Comment by jamesgeorge007** [comment]
@znarf Would love to know your thoughts on [Mevn-CLI](http://github.com/madlabsinc/mevn-cli)

**Comment by znarf** [comment]
@jamesgeorge007 I'm not practicing Mongo or Vue, so I don't have a lot of thoughts on it. Unfortunately!

**Comment by jamesgeorge007** [comment]
@znarf Well, you could show off your support and love by leaving a :star: :smile:

**Comment by jamesgeorge007** [comment]
@znarf Well, you could show off your support and love by leaving a :star: :smile:
