### ISSUE TITLE
Discover page: "most popular" should sort by total pledged

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2254]
On the discover page, the `Most popular` filter for pledged collectives has unpredictable ordering.

When choosing this filter, the API should order by total amount pledged desc. An alternative would be to order by total number of pledgers (it require frontend code as well).

The fix must be implemented in the API, in the `allCollectives` query https://github.com/opencollective/opencollective-api/blob/963887f4f7e679e10452124fc3809f58c2f2e5b4/server/graphql/v1/queries.js#L856

![image](https://user-images.githubusercontent.com/1556356/61391151-5d0d9500-a8bc-11e9-883e-b4925843cedd.png)

**Comment by jeffin143** [comment]
@Betree this is done , we should close the issue 🚀

**Comment by Betree** [comment]
Solved in https://github.com/opencollective/opencollective-api/pull/2841
