### ISSUE TITLE
Terms of fiscal sponsorship missing from host page

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2256]
**Describe the bug**
There used to be a link to the host terms of fiscal sponsorship near the top of the page, but it's disappeared.

![Screen Shot 2019-07-19 at 2 15 17 PM](https://user-images.githubusercontent.com/5498878/61504539-d974b500-aa2f-11e9-83c7-faeadf710c98.png)

**Comment by Betree** [comment]
@alanna The link has not disappeared from the code (https://github.com/opencollective/opencollective-frontend/blob/7a19d5e85e765c3f333fadc7888b6fc2ad84c501/components/ApplyToHostBtn.js#L47), however it seems that there's no `tos` link in OSC's settings. Can you provide the link where this should go so I can add it to the config?

**Comment by alanna** [comment]
OK this is a bug then. The terms of fiscal sponsorship have been set for OSC for a very long time, and have not changed. Can you please investigate how and when it got deleted? This is pretty concerning because we require new Collectives to agree to these terms and we don't know how long they haven't been linked. What happens when they get to the screen where they have to tick the box to agree to them? Is it linked there?

I just tried to test this, but I can't actually get the system to let me apply to OSC. I have an unhosted Collective (test collective) but when I go to the OSC host page, it says "Apply to create a collective" instead of "Apply with your Collective, test collective". I tried creating a brand new Collective to test it, but I got stuck in an endless loop: Apply to create collective > create it > get to host selection screen > choose OSC > see again the button that says "apply to create collective".

After all that I went ahead and re-added the terms URL in the OSC host settings.

**Comment by Betree** [comment]
Seems that it was removed from the settings on `2019-07-18 05:55:05`

> What happens when they get to the screen where they have to tick the box to agree to them? Is it linked there?

Yes

![image](https://user-images.githubusercontent.com/1556356/61856488-892fa400-aec2-11e9-8c2c-18c8bf78de22.png)

> OK this is a bug then.

I don't exclude the possibility of a bug in the edit collective form, but I'll need steps to reproduce if we want to tackle that. I just tried locally and the field seems to react normally.

Another possibility is that someone mistakenly removed it.

**Comment by alanna** [comment]
OK I guess this will be a mystery for now. If it happens again, we need to track down what's causing it, as this could put OSC in a questionable legal position if the terms are not linked.

I raised #2281 to deal with the other problem.

**Comment by alanna** [comment]
The same thing happened to Open Collective Foundation!

I was editing the org description and I noticed the terms link box was empty. It was definitely linked before and somehow disappeared. I'm 100% sure I didn't delete it and I seriously doubt anyone else has been editing that org. 

I know this is really hard to troubleshoot but I really think there's a glitch going on.

**Comment by Betree** [comment]
I did some more investigation and finally found the root cause. Pushing a fix right now. 

I'm also adding this to #2253 because it is directly linked to the way edit collective is implemented.
