### ISSUE TITLE
PayPal payout API

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2258]
As suggested by @dodgepong

We're currently using [Paypal Adaptive Payments](https://developer.paypal.com/docs/classic/adaptive-payments/integration-guide/APIntro). It was, at the time of implementation, what worked best for us:
- One application
- Multiple senders (hosts)
- Multiple recipients

It has however some limitations:
- Fees are high: around 2.5% + $0.30
- Host needs to re-generate a pre-approval every $2,000
- Cannot pay more than $2,000 from the host dashboard

---

PayPal introduced a [Payout API](https://developer.paypal.com/docs/api/payments.payouts-batch/v1/) that provides the following benefits over adaptive payments:
- Payout limit is $20,000 USD
- For payouts made through the API, it’s just $0.25 USD per U.S. transaction.
- For international payments, the fee is 2% of the payment amount to each recipient (up to a maximum of $20)

It seems that just migrating to this API without batching would already greatly improve the amount of fees paid to PayPal. But with this API it's also possible to batch multiple payouts in one request, then you only pay $0.25 fees for the total.

Batching is **not** part of this issue as we should before run queries to see how much money would really be saved. This issue is about investigating the possibility of migrating from adaptive to payout only.

## Specs

*Still need some investigation before writing proper specs*

**Comment by piamancini** [comment]
This is great.

**Comment by alanna** [comment]
This would be amazing!!

**Comment by Betree** [comment]
From looking at the data, I found out that the actual fees applied by PayPal for paid expenses are currently closer to **3.5% + $0.30**. The following table summarizes the fees on all times and on the last 6 months for expenses payed via PayPal. 

Estimating fees is not easy because there's a big difference between domestic (US) payouts and international (see pricing above). The presented table below shows a range between international-only (max fees) and US-only (min fees). **The actual fees should be somewhere between the two.**

The TLDR ; of this is: **Using the Payout API would save between $1000 and $11800 per month to payees**.

That in my view would justify to prioritize this project, especially for OSC which is the most impacted by this.

| Period        | Count | Total paid  | Current Fees | Min Estimated Payout API fees | Max Estimated Payout API fees | 
|---------------|-------|-------------|--------------|-------------------------------|-------------------------------| 
| All time      | 4511  | $977 798,00 | $34 040,00   | $902,20                       | $19 555,96                    | 
| Last 6 months | 1331  | $298 289,00 | $12 077,00   | $266,20                       | $5 965,78                     |

**Comment by alanna** [comment]
> Using the Payout API would save between $1000 and $11800 per month to payees. That in my view would justify the prioritization of this project, especially for OSC which is the most impacted by this.

I completely agree. This would be extremely welcome. Do we have any developers around us who could take this on, or does it have to be a core team member? OSC could contribute toward the budget for sure.

**Comment by Betree** [comment]
@alanna My personal opinion is that because this project is complex and we want the implementation to be the cleanest possible, we should handle it internally. But @znarf has a better view on this than I do.

**Comment by znarf** [comment]
The core team should do the specifications. After that, I think any good developer can do it.

What I like about this project is that it's not necessarily a rewrite of what we have but something that can run in the background.

The expenses could be "Marked for Payout" by Host Admins and after that a background job would do the magic behind the scenes. If there is any problem with the new system, we could always fallback to the previous implementation or manual payments.

**Comment by Betree** [comment]
@kewitz since the base is now implemented, maybe we can close this one and follow up in https://github.com/opencollective/opencollective/issues/3131?

**Comment by kewitz** [comment]
Agreed, the base API is already implemented and merged.
