### ISSUE TITLE
Docs down

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2259]
Instead of directing to the Open Collective gitbook, docs.opencollective.com is redirecting to https://docs.opencollective.brussels, breaking all help links.

@xdamman @znarf @Betree - did you change anything related to this?

**Comment by znarf** [comment]
Related to the creation Open Collective Brussels docs at Gitbook. Deleted that.

**Comment by xdamman** [comment]
Huh oh sorry my fault. I’m the one who created that.  But I had no idea it would break the existing docs. That’s weird. I’ll investigate. Would be good to have docs for hosts as well.
