### ISSUE TITLE
Unsubscribe is broken

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#226]
It should also be removed from Login emails. If someone hits it by mistake, they can end up in a frustrating state.

**Comment by xdamman** [comment]
The unsubscribe link is only present for

    'group.monthlyreport'
    'group.transaction.created'
    'email.approve'
    'email.message'

See https://github.com/OpenCollective/opencollective-api/blob/master/server/lib/email.js#L86

**Comment by asood123** [comment]
sent you a login email with unsubscribe in it.

**Comment by asood123** [comment]
Not reproducible. reopen if happens again.
