### ISSUE TITLE
UI elements for new tax form notifications

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2260]
## Help text 

On hover over "Tax form required" label:

> We can't pay until we receive your tax info. Check your inbox for an email from HelloWorks with a link to the form you need to submit. Need help? Contact support@opencollective.com

If possible, it would be great if clicking that label took you to https://docs.opencollective.com/help/expenses/tax-information

## Banner

Currently, after submitting an expense you are redirected to this page:

![Screen Shot 2019-07-22 at 1 43 35 PM](https://user-images.githubusercontent.com/5498878/61601356-15568700-ac89-11e9-98c2-21e52cce579a.png)

If the expense has pushed you over the $600 limit, it should display a banner similar to this one (which appears after creating a Collective):

![Screen Shot 2019-07-22 at 2 01 57 PM](https://user-images.githubusercontent.com/5498878/61601412-4e8ef700-ac89-11e9-9d3a-f81ebecd2e11.png)

Banner text:

> **We need your tax information before we can pay you.** 
> You will receive an email from HelloWorks saying Open Collective is requesting you fill out a form. This is required by the IRS (US tax agency) for everyone who invoices $600 or more per year. If you have not received the email within 24 hours, or you have any questions, please contact support@opencollective.com. For more info, see our [help docs about taxes](https://docs.opencollective.com/help/expenses/tax-information).

The banner should show when:

* They cross the $600 threshold (not counting receipt reimbursement expenses going forward)
* The expense is first submitted (not on approval, as it is with tax bot)
* We do not already have a received tax form in the system for them

**Comment by Betree** [comment]
A message above `Your expense has bee submitted with...` would make more sense to me because the collective notification bar is a place where we normally display notifications about the collective you're viewing (ex: created, archived...etc) not about the logged in user. The goal being to ensure that the user doesn't miss this message, we have helpers in the design system that could help (for example the warning class): https://styleguide.opencollective.com/#!/MessageBox

Not a blocker for me thought.

**Comment by piamancini** [comment]
who's implementing this? @piet?

**Comment by pietgeursen** [comment]
> who's implementing this? @piet?

Yep! :wave:

**Comment by pietgeursen** [comment]
@alanna what do you think about mentioning that the email might take up to 24h to be sent? Try and work it in or leave it out?

**Comment by alanna** [comment]
@pietgeursen the 24 thing is mentioned in the banner text. Are you saying we should also add it to the hover text?

**Comment by alanna** [comment]
@Betree - I agree that the ideal location of the banner would be above "Your expense has been submitted". If it's easy to put it there, great. @pietgeursen and I were just planning to use as much existing styling and code as possible, so we were planning to piggyback off the existing banner design. If it's a simple change, let's go for it. 

But if it's not, I think redesigning the expense submitted page should be part of the new expense redesign and we should do it properly and include this in the design. That page has a lot of problems. @raulgrafico

**Comment by pietgeursen** [comment]
@alanna yeah I was meaning the hover text. Buuut, the banner text is very clear so on reflection I think it's good enough. The hover text is pretty long as is.

**Comment by alanna** [comment]
@pietgeursen feel free to make edits/improvements as you're seeing it in the UI context. I wasn't sure how long to make things.

**Comment by pietgeursen** [comment]
@alanna see the pics in the description of the [PR here](https://github.com/opencollective/opencollective-frontend/pull/1987). What do you think?

**Comment by alanna** [comment]
@pietgeursen  it looks really good! The only small changes I would suggest are:

* Yeah the hover text seems too long. Let's delete the words "with a link to the form you need to submit" and keep the rest the same.

* I find the light yellow on lighter yellow text of the banner really hard to read. Can you change the color to something higher contrast?

* In the banner, are the words "see our help docs about taxes" a link? They are meant to be, but the styling doesn't make it apparent that it's clickable.

**Comment by pietgeursen** [comment]
@alanna 

> In the banner, are the words "see our help docs about taxes" a link? They are meant to be, but the styling doesn't make it apparent that it's clickable.

Good spotting, I think I missed that. Will fix.

> I find the light yellow on lighter yellow text of the banner really hard to read. Can you change the color to something higher contrast?

I'm trying to re-use existing components so that the styling is consistent through the site. I'd like to keep using this component: https://styleguide.opencollective.com/#!/MessageBox . What about using blue or red?

> Yeah the hover text seems too long. Let's delete the words "with a link to the form you need to submit" and keep the rest the same.

:+1:

**Comment by Betree** [comment]
> I'm trying to re-use existing components so that the styling is consistent through the site. I'd like to keep using this component: https://styleguide.opencollective.com/#!/MessageBox . What about using blue or red?

This is the right thing to do, the goal of the design system is to have consistent design/colors across the site. If the warning colors I to light (I think they are too) then we should update them.

Actually I just looked at https://www.figma.com/file/1jyGC3MjtqI7uUsGf1447P/DS-03-%2F-Colors?node-id=1234%3A1201 and it seems that it has already been updated, @pietgeursen feel free to edit https://github.com/opencollective/opencollective-frontend/blob/7a19d5e85e765c3f333fadc7888b6fc2ad84c501/lib/constants/theme.js#L69 to reflect these changes in your PR:

```es6
  yellow: {
    900: '#703C00',
    800: '#945400',
    700: '#B86E00',
    600: '#DB8B00',
    500: '#FFAA00',
    400: '#FFC94D',
    300: '#FFEB85',
    200: '#FFF5C2',
    100: '#FFFAE0',
  },
```

**Comment by Betree** [comment]
@pietgeursen and also

```es6
    warning: {
      backgroundColor: colors.yellow[100],
      borderColor: colors.yellow[500],
      color: colors.yellow[500],
    },
```

**Comment by pietgeursen** [comment]
@Betree I don't have access to that figma file I guess. I've created an account with figma using my open collective email address but still no love.

**Comment by Betree** [comment]
@pietgeursen I asked the design team to add you on Figma. But you can just rebase on master, I've already updated the design there (I needed that too).

**Comment by pietgeursen** [comment]
> But you can just rebase on master

Ok, I did that and removed the custom styling for the colors that I had added.

**Comment by alanna** [comment]
I'm pretty sure this has already been done.
