### ISSUE TITLE
Unexpected error when ___________

### ISSUE THREAD

**Issue by dangtan973** [opencollective/opencollective#2269]
# Describe the bug

I got an unexpected error on https://opencollective.com/babel/contribute/backers-355/checkout? while I was trying to __________

# To Reproduce

1. Go to ________
2. Click on ________
3. Scroll down to ________

# Device
- OS: Linux aarch64
- Browser: `5.0 (Linux; Android 5.1; CPH1605) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.143 Mobile Safari/537.36`

# Technical details

```

```

**Comment by Betree** [comment]
@dangtan973 can you provide more details about the error, like steps to reproduce?
