### ISSUE TITLE
Transaction Data Mismatch

### ISSUE THREAD

**Issue by maddhruv** [opencollective/opencollective#2270]
**Describe the bug**
The Latest Transactions data doesn't match in the two pages
- https://opencollective.com/bundlephobia/v2 - version 2 (new design)
- https://opencollective.com/bundlephobia - version 1 (older design)

<img width="954" alt="Screenshot 2019-07-24 at 14 31 58" src="https://user-images.githubusercontent.com/18121502/61780265-da3a8c00-ae1f-11e9-949d-b32173068aa4.png">
--- VS ---
<img width="1187" alt="Screenshot 2019-07-24 at 14 31 45" src="https://user-images.githubusercontent.com/18121502/61780280-e0306d00-ae1f-11e9-967f-ff302fc8b681.png">

**Comment by Betree** [comment]
Good catch, that's because we show the amount after Stripe/OC fees in one case and not the other. I'll update that so design match.

**Comment by sudo-kaizen** [comment]
@Beetree Are you going to create an issue for this or you have it assigned to yourself already? Is this really a frontend related issue?

**Comment by Betree** [comment]
@sudo-kaizen It is, I'm on it already.
