### ISSUE TITLE
Need to attribute an Organization's contributions to a Collective

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2273]
The contributions from this Organization:
https://opencollective.com/access1

Need to be attributed to this Collective:
https://opencollective.com/access

This happened because of the inability to do Collective to Collective transfers between hosts (#2017). Instead, we did a manual transfer from host to host and then added the funds manually to the Collectives. But this doesn't work for cohesive reporting of the budgets.

How do we fix this in this specific case, and also enable correct attribution in the future?

**Comment by Betree** [comment]
One way to do that could be to change the `FromCollectiveId` of all orders and transactions from `access1` to `access`. @xdamman is that a safe thing to do?

**Comment by xdamman** [comment]
Yes. But you’d need to also do that for the corresponding transactions. And the proper way to do this is to mark them as deleted and create new ones.

**Comment by alanna** [comment]
Please let me know when this has been done so I can inform the user.

**Comment by Betree** [comment]
@alanna This is at the top of my todo list. Just need your confirmation on this: do we agree that [access](https://opencollective.com/access)'s balance will be impacted by this change in the following way: all their contributions (6165+5865+3695+3530 = $19255) will be subtracted from the collective balance ($72,796.05 to this day)?

**Comment by alanna** [comment]
Yes that is correct @Betree - sorry I should have been more specific.

This was an unsuccessful attempt at a workaround to do a Collective to Collective transfer across hosts. Next time I think a better process would be for the Collective admin to make a contribution with the Collective balance as the source, and select "bank transfer" as the payment method. Then when I confirm the pending order, it would automatically debit from the Collective and show in their ledger. Is that right? If that will work, then I can improve this a lot next time.

**Comment by Betree** [comment]
@alanna Done! Sorry about the delay to get there. Please tell me if I forgot anything:

- https://opencollective.com/access1 is now empty
- Transactions are now associated with https://opencollective.com/access:

![image](https://user-images.githubusercontent.com/1556356/62133056-7829cd00-b2de-11e9-849f-1f0a2d217f28.png)

- Balance for access is now `€53,541.05`

- The memberships has been updated too so `access` correctly appears as a contributor:

![image](https://user-images.githubusercontent.com/1556356/62133324-dfe01800-b2de-11e9-84f2-36bc72df46e6.png)

**Comment by alanna** [comment]
Thank you!!
