### ISSUE TITLE
widgets are broken

### ISSUE THREAD

**Issue by mojoaxel** [opencollective/opencollective#2275]
**Describe the bug**
The opencollective widget are not shown anymore.

**To Reproduce**
1. Go to https://opencollective.com/widgets
2. open dev console 
3. See error `Uncaught ReferenceError: require is not defined at button.js:3`

**Comment by Betree** [comment]
Fixed by https://github.com/opencollective/opencollective-frontend/pull/2249 and deployed

Thanks for the report @mojoaxel!

**Comment by mojoaxel** [comment]
this fix results in #2278
