### ISSUE TITLE
Unable to pay expenses through paypal or refill balance

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2277]
I paid some of expenses today and it was working fine at first. I refilled the paypal balance a couple times. Then, I started getting this error on every expense I tried to pay:

> PayPal error: The date range between the start date and the end date is too wide (error id: 579038)

Also, I can't refill the balance anymore. I thought I might need to reset the token, but when I click "refill balance" nothing happens.

This is affecting all hosts. It started with OSC but the same thing is happening in Foundation, C-corp, everywhere apparently.

**Comment by Betree** [comment]
We didn't change this recently so my first guess is that PayPal reduced the max validity period of the pre-approval. Investigating that in priority.

**Comment by Betree** [comment]
From the logs I can confirm that we're sending the same period as usua (1 year)

> "startingDate":"2019-07-26T06:04:52.373Z","endingDate":"2020-07-26T06:04:52.366Z"

Whatever change they made hasn't been reflected to their "sandbox" API, all my local test are still working. We'll have to go for a blind fix that will need to be tested once it's live. I'm going to reduce the validity period to 6 months.

**Comment by Betree** [comment]
As per https://opencollective.slack.com/archives/G46PNRCGP/p1564127222003700 this issue seems fixed, @alanna can you confirm?

**Comment by alanna** [comment]
I was able to pay an expense through the API so apparently this is fixed now.

**Comment by alanna** [comment]
Seems to be working normally now so I'm closing this.
