### ISSUE TITLE
Security error on chrome for images fetched fom Cloudfront

### ISSUE THREAD

**Issue by mojoaxel** [opencollective/opencollective#2278]
**Describe the bug**
The page https://opencollective.com/widgets shows a security warning in Chrome.
The "backers and sponsors" widget can not be displayed in Firefox

### Chrome 75.0.3770.142 (Offizieller Build) (64-Bit) (Ubuntu Linux)
![image](https://user-images.githubusercontent.com/600565/61951290-e4d85b00-afb0-11e9-9abd-22a245ff50da.png)

### Firefox 68.0.1 (64-bit) (Ubuntu Linux)
![image](https://user-images.githubusercontent.com/600565/61951265-c83c2300-afb0-11e9-8f3e-c0301ad6303a.png)

**Comment by Betree** [comment]
Seems like the cloudfront domain is red flagged, we still use it for some old user pictures. It doesn't seems related to widgets themselves.

Note: Works for me on Firefox without warning (this is why I missed it)

![image](https://user-images.githubusercontent.com/1556356/61951737-30d7cf80-afb2-11e9-8f43-1eb67e4b4229.png)

**Comment by mojoaxel** [comment]
I'm sure everything worked well last week or so.

**Comment by Betree** [comment]
Thanks again for this new report @mojoaxel, this is fixed now. Turns out we were displaying a screenshot instead of the real widget and the image provider used for it got blacklisted by browsers.
