### ISSUE TITLE
When are new translation updated?

### ISSUE THREAD

**Issue by IoTopenTech** [opencollective/opencollective#2279]
Hi, we are testing Open Collective for our non profit organization.

I have translated several strings to spanish in crowdin, but they are not automatically updated in the frontend.
For example:
![imagen](https://user-images.githubusercontent.com/52624907/62011236-d8e9c600-b175-11e9-90ba-4bbb308661a8.png)
![imagen](https://user-images.githubusercontent.com/52624907/62011243-11899f80-b176-11e9-9a9f-e59757d6e14c.png)

Please, could you tell me when these translations are updated?

Kind regards from Madrid.

**Comment by Betree** [comment]
Hello @IoTopenTech, thanks for contributing on that!

We usually merge the translations once per week. Next batch should be delivered today or tomorrow :slightly_smiling_face:
