### ISSUE TITLE
Reduce text in contribute section of Collective page

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2280]
We've been running into issues deciding what labels and text should be on things in the contribute section of the new Collective page. I think this is because we are using too much redundant text, and too much text defined by us instead of users.

There are many different kinds of Collectives who will want to use different terminology. We can enable them by using their tier names as the action buttons, and removing extraneous labels with text defined by us.

Here's my suggestion:

![](https://user-images.githubusercontent.com/5498878/61196184-eab47d80-a720-11e9-836b-7f371b0b92a6.png)

**Comment by Betree** [comment]
As mentioned in the original thread having the tier title on the button may not play nicely with https://github.com/opencollective/opencollective/issues/543

I like the idea of simplifying this tho.

**Comment by piamancini** [comment]
> As mentioned in the original thread having the tier title on the button may not play nicely with #543

Agreed. 

I also agree with removing the top Contribute (since we have it already below) and the blue tags for simplicity. 

I don't like the idea of putting the title on the button since it's not a call to action

**Comment by alanna** [comment]
I see the downside to the title being on the button. The problem we were running into is then every button says `contribute` repetitively. But if you think that redundancy is OK and we really want to emphasise that contribute action, then that's fine. 

Some Collectives have different actions in mind for certain tiers, like "join" "donate" "buy" etc, and we had a whole conversation about if a Collective should be able to customise its CTA word. I didn't think that was a great idea because of the added complexity - this idea came because I thought, well we are having them customise the tier name so why not put that on the button?

But anyway, after typing all that I think the best solution is to just stick with `contribute` on the button since we're doubling down on that CTA. If users really want other CTA words we'll hear about it after deployment.

**Comment by Betree** [comment]
@alanna A contributor already took care of that, it's now possible customize the button (though I just noticed it's not working properly, I'll push a fix for it today). 

![image](https://user-images.githubusercontent.com/1556356/62109097-e1dcb380-b2ab-11e9-863c-ecf6dd477b2f.png)
