### ISSUE TITLE
Unable to apply to Open Source Collective manually

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2281]
**Describe the bug**
Can't apply with existing or new Collective to Open Source Collective host without going through the GitHub verification flow.

**To Reproduce**
A. With exisiting unhosted Collective:
1. Go to opencollective.com/opensource
2. Button says "apply to create Collective" instead of "Apply with [Collective name]"
3. No way to apply with your Collective

B. Create New Collective:
1. Go to opencollective.com/create
2. Select 'other' Collective type
3. When you get to host page, choose "apply to existing host" 
4. Select OSC
5. Button says "apply to create Collective" instead of "Apply with [Collective name]"
6. You are in a loop

C. Create new Collective from OSC host page
1. Go to opencollective.com/opensource
2. Click button "apply to create Collective" 
3. Immediately sent to Github verification flow with no other option
4. Give up

**Expected behavior**
We need a way for Collectives to apply to OSC who want to be verified by other means. Previously, if you had an existing unhosted Collective you could apply with it to OSC as a host.

**Comment by Betree** [comment]
@alanna I just created https://github.com/opencollective/opencollective/issues/2282 that I think should solve this. We'll be able to use the new component once the design team delivers the design for it (even if it looks bad on the old collective page) to ensure we solve this asap.

**Comment by piamancini** [comment]
@alanna, existing collectives should also be able to apply from /edit and Fiscal Host tab

**Comment by alanna** [comment]
@piamancini they can't. Try it yourself. If you go to edit > fiscal host > try to add OSC, it will make you create a new Collective or go through the Github flow.

**Comment by piamancini** [comment]
yes, I get that it's not the case now. I meant that we should also modify that path.

**Comment by Betree** [comment]
If we change the button to `Apply with [Collective name]`if you already have a collective without host, would that be a good (temporary) fix?

**Comment by alanna** [comment]
@Betree that would help in a lot of cases. It doesn't fix #2154 (a relatively rare situation), but what you described would at least get us back to how it worked before.

**Comment by alanna** [comment]
Is there any update on this? We need to use the manual application functionality quite often. I just tried to test it with Test Collective (which has no host) and it's not allowing me to apply with that. Only saying "Apply to Create a Collective". 

I know this will be fixed properly in the new design but we need a quick fix now.

**Comment by Betree** [comment]
@alanna This has been fixed by https://github.com/opencollective/opencollective-frontend/pull/2320. I tried to reproduce and there's indeed an issue: you need to refresh the page before the button shows `Apply to host your collective ...`. I believe this is not only for the open source collective, I'll create a separate issue now.

![image](https://user-images.githubusercontent.com/1556356/63250122-2d5efd80-c26b-11e9-9250-68b4ec88baed.png)
