### ISSUE TITLE
Charge on Stripe not reflected in Transaction Table

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2285]
collectiveId=5793 (managed by userId=5162) has two separate $600 payments in stripe, one for 2/7 and one for 5/7, however as you can see in their profile /transactions only one payment it shown. 

There is no transaction for that order in the transaction table for the 2/7, you only see the one on 5/7. 

All previous transactions are on the 2nd of each month 2/6, 2/5 all the way to 2/2/18 so one hypothesis is that we failed to notice the charge on the 2nd and tried a second attempt on the 5th. But the charge on the 2nd had gone through successfully. I refunded the charge in stripe. 

I have stripe charge id's info if needed.

**Comment by znarf** [comment]
It's now well understood that these are connection errors with the Stripe API. 

The script from @Betree is great to figure if we missed one of these errors.

We're tackling that in https://github.com/opencollective/opencollective/issues/2584

A first implementation of Stripe retries is here https://github.com/opencollective/opencollective-api/pull/2842

I think we can close this issue.

**Comment by piamancini** [comment]
Yep. Closing.
