### ISSUE TITLE
Unexpected error when ___________

### ISSUE THREAD

**Issue by quangcaodinhluan** [opencollective/opencollective#2287]
# Describe the bug

I got an unexpected error on https://opencollective.com/pixijs/contribute/backer-10287/checkout? while I was trying to __________

# To Reproduce

1. Go to ________
2. Click on ________
3. Scroll down to ________

# Device
- OS: Win32
- Browser: `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36`

# Technical details

```

```

**Comment by Betree** [comment]
Hello, thanks for opening this issue. 

Could you provide more details about how this happened and/or steps to reproduce?
