### ISSUE TITLE
Remove collective goals (once NCP is deployed)

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2288]
As per [this answer](https://opencollective.slack.com/archives/C0YFZ3MHP/p1555499071007800) from design, goals will be removed entirely once we migrate everything to the new collective page.

We'll need to remove:

- API
  - From emails (monthly report)
  - From edit collective endpoints

- Frontend
  - Edit goals
  - CollectiveStatsCard
  - CollectiveCover

**Comment by Betree** [comment]
Assigning @cuiki as he's the decision maker on this one.

**Comment by piamancini** [comment]
are we assuming that only tiers have goals, as oppose to general collective goals @cuiki ?

**Comment by Betree** [comment]
Resolved in https://github.com/opencollective/opencollective-frontend/pull/2584

**Comment by Betree** [comment]
This seemed to have a big (negative) impact for one of the collective, see https://opencollective.slack.com/archives/C0HSLRNVC/p1569537147082000
