### ISSUE TITLE
prevent collectives for having 0 admin

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2289]
Right now, you can remove all admins from a collective. We should prevent this from happening. 
Last admin needs to add a new one (that needs to validate the email) before removing themselves.

**Comment by alanna** [comment]
Another example of how this can happen came through support today.

User wanted to delete his account and his Collective. He deleted his account. But then lost access to delete his Collective, which was left with 0 admins.

We should not allow someone to delete their account if they are the only admin of a Collective.

**Comment by znarf** [comment]
This is a regular and pretty frustrating issues for our users.

@flickz can you have a look?

**Comment by flickz** [comment]
Alright I'm on it

**Comment by flickz** [comment]
> Right now, you can remove all admins from a collective. We should prevent this from happening.

I've been thinking about the best logic for this because of the way `editMembers`  method is currently written, can we establish a ground rule that says:

"As an admin, you can't remove yourself from a collective, you have to inform another admin member of the collective to remove you. Or add a new admin member that can do that for you" 

This would prevent a collective at any point in time from having 0 admin.

**Comment by znarf** [comment]
@flickz Sounds like a sensible option.

**Comment by alanna** [comment]
Sounds good @flickz - once you confirm how it will work let me know and I can write some help text for you to use when someone needs to be informed why they can't delete themselves.

**Comment by flickz** [comment]
@alanna can you write the help text now?

**Comment by alanna** [comment]
@flickz can you confirm how it will work? Will it not ever allow you to remove yourself as an admin, even if there are other admins, or will this only come up if they are the last admin left? When will they see the text?

**Comment by alanna** [comment]
Also, what will the behaviour be when someone is trying to delete their own account but they are the only admin of a Collective or Organization?

**Comment by flickz** [comment]
> Will it not ever allow you to remove yourself as an admin, even if there are other admins

Yes this is happens. 

> Also, what will the behaviour be when someone is trying to delete their own account but they are the only admin of a Collective or Organization?

Currently this only prevents you from removing yourself as an admin. I'm thinking about making the 
account deletion a separate PR, @znarf What do you think?

**Comment by znarf** [comment]
> When will they see the text?

@flickz Can you answer this question from @alanna ? Maybe share a screenshot with the error message.

> I'm thinking about making the account deletion a separate PR, 

@flickz Yes, let's do it separated.

**Comment by flickz** [comment]
> When will they see the text?

@alanna The error message is shown when the user click save in the edit collective page, like the screenshot below:

<img width="817" alt="Screenshot 2019-08-13 at 1 24 28 PM" src="https://user-images.githubusercontent.com/15707013/62941698-94ddfe80-bdce-11e9-92e9-3acc1dd1c7de.png">

For the account deletion, this is shown in the advanced section of the edit collective page after the Delete button from the modal confirmation is clicked.

<img width="868" alt="Screenshot 2019-08-13 at 12 53 31 PM" src="https://user-images.githubusercontent.com/15707013/62941782-c787f700-bdce-11e9-8c9e-407bfebe1e85.png">

**Comment by alanna** [comment]
OK. So I am understanding that no one can ever remove themselves as an admin, even if there are other admins. If that's right, here's some text for the error messages.

Core Contributors screen:
> You cannot remove yourself as a Collective admin. If you are the only admin, please add a new one and ask them to remove you.

Delete account screen:
> Unable to delete your account because you are the only admin of [Collective]. Please archive or delete that Collective, or add another admin.

**Comment by Betree** [comment]
Re-opening as there is a path that https://github.com/opencollective/opencollective-api/pull/2386 doesn't cover: if users change their roles from `Collective Admin` to `Core Contributor`, they will still loose the access to their collective. We only prevent the remove, not the edit.

See https://opencollective.slack.com/archives/C0HSLRNVC/p1566257208170100

**Comment by znarf** [comment]
@flickz can you take care of that?

**Comment by flickz** [comment]
Sure

**Comment by znarf** [comment]
Merged and deployed.

**Comment by hugonun** [comment]
Hello, I have an issue that seems to be related to this. I've created an user account and changed the username, but received the following message: "There must always be at least one collective admin". The settings got changed tho.

But now I wanted to change profile picture and that doesn't seem to work, I get that message everytime.

**Comment by znarf** [comment]
@hugonun we'll look into it, what's your collective or user account?

**Comment by hugonun** [comment]
@znarf Thanks, here is my account: https://opencollective.com/hugonun

**Comment by znarf** [comment]
@hugonun Thank you for the report, should be fixed.
