### ISSUE TITLE
Expenses with comments

### ISSUE THREAD

**Issue by erickrico** [opencollective/opencollective#229]
im trying to change the way the full expense history looks and works, make it easier to scan and understand the overall status of the collectives money
![expenses-new](https://cloud.githubusercontent.com/assets/18429104/18238872/9cc6bd46-7306-11e6-94f0-3dee7cefb754.png)
![expenses-comment](https://cloud.githubusercontent.com/assets/18429104/18238876/a0082076-7306-11e6-83e0-b3666282aaa5.png)

**Comment by asood123** [comment]
👍  for clean new design. One thing to add is `Notes` somewhere. It's an optional field with unlimited text length. In reality, probably less than 255 chars most of the time.

**Comment by Shakyamuni177te** [comment]
This is really starting to look useful now. :)

**Comment by xdamman** [comment]
Can you do a mobile version of this?

**Comment by Shakyamuni177te** [comment]
Almost definitely.

**Comment by erickrico** [comment]
### With a note
![screenshot 2016-09-12 16 04 27](https://cloud.githubusercontent.com/assets/18429104/18453716/37d2cb86-7906-11e6-9015-59bbccf1d57b.png)

### mobile
![screenshot 2016-09-12 16 17 14](https://cloud.githubusercontent.com/assets/18429104/18453732/4848bdf4-7906-11e6-83a3-057502dbf8eb.png)

### mobile comment
![screenshot 2016-09-12 16 17 27](https://cloud.githubusercontent.com/assets/18429104/18453743/54b2da98-7906-11e6-812f-924abfd73bdf.png)

**Comment by xdamman** [comment]
Thanks @erickrico. It looks great. Can you just add the thumbnail of the receipt?

Also, I wonder if the note shouldn't be just the first comment of the author (Instagram style). What do you think?

**Comment by erickrico** [comment]
😅  it actually makes a lot of sense to display the note in that way, making the change and adding the thumbnail

**Comment by erickrico** [comment]
![screenshot 2016-09-12 17 20 22](https://cloud.githubusercontent.com/assets/18429104/18455114/a783368a-790d-11e6-9ac9-fa7af55f4f5b.png)

**Comment by xdamman** [comment]
Ship it! :)

**Comment by piamancini** [comment]
this never shipped, but we'll leave it opened as it is useful for #478
