### ISSUE TITLE
Collective Page→ Feedback Discover Collective Cards

### ISSUE THREAD

**Issue by lindatalu** [opencollective/opencollective#2291]
## User story 

The purpose of the issue is to receive feedback for the navigation in the cards

## Link
https://tafka.d.pr/NundxW

**Comment by piamancini** [comment]
I like this behaviour better than the hover. Are we planning this for both mobile and desktop?
@Betree what do you think with regards to implementation complexity?

**Comment by Betree** [comment]
> @Betree what do you think with regards to implementation complexity?

Should be alright. I'd be careful with keeping the mask with the bubbles for the banner image, it can be quite expensive for performances to have too much of these on the page. The previous version of the cards was more optimized in this regard.

@lindatalu 
- How do we choose the profiles to show in `Last Activity by`?
- What triggers the effect to show the description?

**Comment by piamancini** [comment]
>  it can be quite expensive for performances to have too much of these on the page

good catch
