### ISSUE TITLE
Migrate to StyledSelect on Discover page

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2292]
The `/discover` page still uses `DeprecatedStyledSelect`. We want to migrate that to our new `StyledSelect` component, that is basically just an instance of [react-select](https://react-select.com) with our custom styles.

The labels must stay internationalized, you can either do that using:
- The `getOptionLabel` prop
- Or by pre-generating the options with the correct label

---

Please follow our [code guidelines](https://docs.opencollective.com/help/developers/best-practices-and-code-guidelines), especially:

* The strings must be internationalized. See [/help/developers/translations](https://docs.opencollective.com/help/developers/translations)
* Whenever it's possible we must use `styled-components` to write styles. See [OC Styleguide](https://opencollective-styleguide.now.sh/)
* We're getting rid of `Bootstrap`. Please don't use it for new developments.
* When adding new dependencies, we use [fixed versions](https://docs.npmjs.com/about-semantic-versioning).
* Icons must be imported from the [styled-icons](http://styled-icons.js.org/) library.
* Tests written with Cypress must follow our [good practices](https://docs.opencollective.com/help/developers/testing-with-cypress) conventions.

**Comment by Betree** [comment]
A **$50** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged.

:warning: This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

:arrow_right: [More info](https://github.com/opencollective/opencollective-frontend/edit/master/BOUNTY.md)

**Comment by Nelson-Chinedu** [comment]
from osca event and will like to work on this issue

**Comment by Nelson-Chinedu** [comment]
Hey @Betree Good day... have fixed the issue on the discover page but it seems am having some conflict regarding the pacakage-lock.json file. i actually installed the dependencies just to run it locally on my pc, after that trying to raise a PR after the test ran successfully i noticed there are some conflicts in the package-lock.json. will like to know what to do before proceeding below is the first image gotten
![Capture2](https://user-images.githubusercontent.com/26670804/62655071-1f79b600-b916-11e9-957a-c7808700140c.JPG)
below also is the image showing the conflict
![Capture1](https://user-images.githubusercontent.com/26670804/62655123-37513a00-b916-11e9-8e03-2bedc1e913e2.JPG)

**Comment by Betree** [comment]
You don't need to commit your changes to pzckagle-lock.json, so you can simply ignore your local changes

**Comment by Nelson-Chinedu** [comment]
Oh ok... thanks

**Comment by znarf** [comment]
Unassigning @Nelson-Chinedu because the allowed time is over (feel free to follow up on your PR though).

This issue is now open for everyone.

**Comment by JohnnyAir** [comment]
I will like to work on this issue.

**Comment by JohnnyAir** [comment]
here is my pull request for this issue [https://github.com/opencollective/opencollective-frontend/pull/2574](url)

**Comment by JohnnyAir** [comment]
This is my pull request for this issue: [Migrate to styled select](https://github.com/opencollective/opencollective-frontend/pull/2574)

**Comment by Betree** [comment]
:trophy: This issue is now completed by @JohnnyAir. 

To claim the $50 bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
