### ISSUE TITLE
Migrate to StyledSelect on Edit Webhooks page

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2293]
The `{collective_slug}/edit/webhooks` page still uses `DeprecatedStyledSelect`. We want to migrate that to our new `StyledSelect` component, that is basically just an instance of [react-select](https://react-select.com) with our custom styles.

---

Please follow our [code guidelines](https://docs.opencollective.com/help/developers/best-practices-and-code-guidelines), especially:

* The strings must be internationalized. See [/help/developers/translations](https://docs.opencollective.com/help/developers/translations)
* Whenever it's possible we must use `styled-components` to write styles. See [OC Styleguide](https://opencollective-styleguide.now.sh/)
* We're getting rid of `Bootstrap`. Please don't use it for new developments.
* When adding new dependencies, we use [fixed versions](https://docs.npmjs.com/about-semantic-versioning).
* Icons must be imported from the [styled-icons](http://styled-icons.js.org/) library.
* Tests written with Cypress must follow our [good practices](https://docs.opencollective.com/help/developers/testing-with-cypress) conventions.

**Comment by Betree** [comment]
A **$50** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged.

:warning: This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

:arrow_right: [More info](https://github.com/opencollective/opencollective-frontend/edit/master/BOUNTY.md)

**Comment by nonsodaniel** [comment]
From Osca event

**Comment by nonsodaniel** [comment]
My Apologies for the late response. I've actually completed the task but, kindly direct me on how to test it

**Comment by znarf** [comment]
@nonsodaniel do you have a Pull Request open to share what you have done?

**Comment by nonsodaniel** [comment]
I'd do so now

**Comment by znarf** [comment]
Unassigning @nonsodaniel because of lack of activity.

This issue and bounty is now open to everyone.

**Comment by nonsodaniel** [comment]
Hi, I had issues with my PC.. But I'm ready to do it now

**Comment by nonsodaniel** [comment]
@znarf I'm taking this already

**Comment by nonsodaniel** [comment]
Hi @znarf, I've resolved the issue and I'd like you to check it

**Comment by znarf** [comment]
@nonsodaniel what is the PR?

**Comment by nonsodaniel** [comment]
I've fixed it

**Comment by nonsodaniel** [comment]
> @nonsodaniel what is the PR?

Fixed #2363

**Comment by znarf** [comment]
@nonsodaniel seems the link is wrong, can you check?

**Comment by nonsodaniel** [comment]
> @nonsodaniel seems the link is wrong, can you check?

@znarf  which link?

**Comment by znarf** [comment]
@nonsodaniel “fixed #2363” in your comment above

**Comment by Betree** [comment]
:trophy: This issue is now completed by @nonsodaniel in https://github.com/opencollective/opencollective-frontend/pull/2549 

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
