### ISSUE TITLE
Migrate to StyledSelect on PaymentMethodSelect

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2294]
The `PaymentMethodSelect` component still uses `DeprecatedStyledSelect`. We want to migrate that to our new `StyledSelect` component, that is basically just an instance of [react-select](https://react-select.com) with our custom styles.

You can use the `getOptionLabel` prop to generate the labels (see react-select docs).

To test this, you can either:
- Go on `{collective_slug}/gift-cards-create`
- Or start styleguidist with `npm run styleguide` and navigate to `PaymentMethodSelect`

---

Please follow our [code guidelines](https://docs.opencollective.com/help/developers/best-practices-and-code-guidelines), especially:

* The strings must be internationalized. See [/help/developers/translations](https://docs.opencollective.com/help/developers/translations)
* Whenever it's possible we must use `styled-components` to write styles. See [OC Styleguide](https://opencollective-styleguide.now.sh/)
* We're getting rid of `Bootstrap`. Please don't use it for new developments.
* When adding new dependencies, we use [fixed versions](https://docs.npmjs.com/about-semantic-versioning).
* Icons must be imported from the [styled-icons](http://styled-icons.js.org/) library.
* Tests written with Cypress must follow our [good practices](https://docs.opencollective.com/help/developers/testing-with-cypress) conventions.

**Comment by Betree** [comment]
A **$50** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged.

:warning: This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

:arrow_right: [More info](https://github.com/opencollective/opencollective-frontend/edit/master/BOUNTY.md)

**Comment by JohnnyAir** [comment]
John From Osca

**Comment by Betree** [comment]
:trophy: This issue is now completed by @JohnnyAir 

To claim the bounty, you can either:
- Submit a $50 invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

---

For more info about the bounty process and how to format your invoice, please read https://docs.opencollective.com/help/developers/bounties
