### ISSUE TITLE
Don't create multiple accounts for the same user via alternate emails

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2296]
I recently invited someone as an admin of an Organization and a Collective, but I used an alternate email for them and therefore the system created a new account. Instead, when the user gets the email notification, they should click "accept invitation" and log into the Open Collective account they want the role associated with, regardless of email used.

**Comment by Betree** [comment]
I missed this while writing #2571. Closing in favor of the second, lmk if there's anything missing in the specs
