### ISSUE TITLE
Add Fund doesn't create a `Donation`

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#230]
In `App`, Add Fund directly creates a `Transaction`. This is problematic as we are removing `Transaction.description`, so we have nothing to show. 
1. Add Fund needs to create a `Donation` on the backend with the `title` set to the current `description` and `PaymentMethod=null`
2. `lib/donation` needs logic to process a `Donation` without `PaymentMethod`. It only needs to create a `Transaction` and mark `isProcessed` and `processedAt` timestamps.

Backend already sends back `Donation.title` as `description` when fetching a `Transaction`.

@sedubois, fyi.

**Comment by asood123** [comment]
Once this works, this PR should pass as well: https://github.com/OpenCollective/opencollective-app/pull/193

**Comment by piamancini** [comment]
add funds already works
