### ISSUE TITLE
Paypal error: "based in a country that isn't enabled to receive payments"

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2300]
**Describe the bug**
When I try to pay this expense, I get this Paypal error. The user says his account should not be restricted. Do we know what causes this? The error implies it's his country but he says it should work.

> PayPal error: The email account Receiver not in receive money enabled country is based in a country that isn't enabled to receive payments (error id: 539041)

https://opencollective.com/phalcon/expenses/9255

**Comment by Betree** [comment]
As per https://www.paypal-community.com/t5/About-Payments/Can-t-Recieve-money-Error-539041/td-p/1145656, the user should try to see if `USD` is properly listed on https://www.paypal.com/myaccount/money/balances/summary. He can add it if it's not the case:

![image](https://user-images.githubusercontent.com/1556356/62410329-7add3880-b5e4-11e9-8fab-3a66354f8e8a.png)

If it doesn't solve the problem, we'll need to have his PayPal country (from the address) and the nationality to investigate deeper. He can find them on https://www.paypal.com/myaccount/settings/:

![image](https://user-images.githubusercontent.com/1556356/62410386-0eaf0480-b5e5-11e9-9688-b59b2622272c.png)

**Comment by alanna** [comment]
Thanks! I'll tell the user.
