### ISSUE TITLE
Unexpected error when changing profile

### ISSUE THREAD

**Issue by curnow1278** [opencollective/opencollective#2301]
# Describe the bug

I got an unexpected error on https://opencollective.com/eric-curnow/edit while I was trying to __________

# To Reproduce

1. Go to ________
2. Click on ________
3. Scroll down to ________

# Device
- OS: Win32
- Browser: `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36`

# Technical details

```

```

**Comment by znarf** [comment]
Closing. Feel free to re-open if you have more details.
