### ISSUE TITLE
Frontend: "Core contributor" vs "Member" labeling is confusing

### ISSUE THREAD

**Issue by aptalca** [opencollective/opencollective#2303]
On the Open Collective frontend, while viewing a collective's page in v1, team members are marked as either "Core Contributor" or "Contributor". On v2, the contributor list contains "Core Contributors", "Financial Contributors" and "Members", of which only Core Contributors and Financial Contributors are filterable.

Can this marking/labeling be improved? In reality, the only difference between "Core Contributor" and "Contributor" in v1 and "Core Contributor" and "Member" in v2 is that Core Contributors have admin rights on Open Collective so they can approve expense requests. There is no real world difference between core vs non-core contributor.

For [linuxserver](https://opencollective.com/linuxserver), all members are team members and are equal, except 3 of them are elected to positions where they are tasked with approving expense requests (a committee if you will). 

Currently (in both v1 and v2 frontends) it looks like the 3 admins are the core members of the team whereas the others are merely code contributors, which lessens their positions and involvement. Perhaps admins should be marked as "Admin" and other team members are marked as "Team Member" so it is clearer.

Thanks

**Comment by Betree** [comment]
Hi @aptalca, thanks for reporting this and for taking the time to share your use case with LinuxServer. 

The use of `Member` on the new collective page is definitely a mistake, our terminology clearly say that they should be called `Contributor`. This will be fixed during the week.

> Perhaps admins should be marked as "Admin" and other team members are marked as "Team Member" so it is clearer.

I'll let @alanna review and eventually reply to that part as she's working actively on the terminology.

One last thing I can recommend: you can use the `Description` field to better explain what each contributor is doing for the collective. It will be displayed in the `Contributors` section of the new collective page.

![image](https://user-images.githubusercontent.com/1556356/62492013-c141bb80-b7cd-11e9-8678-1faf3f4030c8.png)

**Comment by Betree** [comment]
Also related: you can see our current terminology definitions on https://docs.opencollective.com/help/about/glossary#collectives. It currently defines that:


* _**Core Contributors:**_  These are all the individuals that take part in running a collective.
* _**Collective Admins:**_ These individuals are core-contributors that have been given full-edition capabilities over the collective’s settings, make contributions to other collectives, approve and dismiss expenses, and receive messages sent to the collective. \(info@collectivename.opencollective.com\)
* They are often community organizers or maintainers of open source projects.
* Core Contributors want to make their communities sustainable financially, so receiving financial contributions from organizations and individuals is first on their priority list. They use tools like [tiers](../collectives/tiers.md), [goals](../collectives/goals.md), and [social media sharing](../collectives/integrations.md#twitter-integration). They are interested in managing and growing their communities by creating [events](../collectives/events.md) and [sending updates](../collectives/communication.md).

**Comment by aptalca** [comment]
thanks @Betree 

Just looked through the gloassary you linked and now I'm more confused.

Glossary lists:
1) Core Contributor
2) Collective Admin

The team editing page in the frontend is titled "Edit Core Contributors", and lets me select one of these two options for each member:
1) Admin
2) Contributor

But the frontend (v1) lists only the admins as "Core Contributor" whereas the others are simply "Contributor". Shouldn't they be listed as either "Collective Admin" or "Core Contributor" as the glossary states?

Not to mentions users who donate are labeled "Financial Contributor"

**Comment by Betree** [comment]
> Shouldn't they be listed as either "Collective Admin" or "Core Contributor" as the glossary states?

They definitely should. The terminology update is quite fresh and there are still some places that needs to be updated. I'll fix it for both the current and the new collective pages.

**Comment by alanna** [comment]
Sorry for the confusion @aptalca - we're in the middle of cleaning up terminology across the app. As @Betree explained, members shouldn't be a thing. There's only Core Contributors, some of whom may also have admin status. Feel free to point out any other places you find where this is incorrect in the UI.

I'm going to work on updating the glossary.

**Comment by aptalca** [comment]
No worries, just wanted to point it out. I'll go through both v1 and v2 and let you know if I notice other discrepancies.

Thanks
