### ISSUE TITLE
Unexpected error when ___________

### ISSUE THREAD

**Issue by az89629900089** [opencollective/opencollective#2305]
# Describe the bug

I got an unexpected error on https://opencollective.com/hyper-star-samsung-next-decentralization-grant/donate? while I was trying to __________

# To Reproduce

1. Go to ________
2. Click on ________
3. Scroll down to ________

# Device
- OS: Linux armv8l
- Browser: `5.0 (Linux; Android 9; X19) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.143 Mobile Safari/537.36`

# Technical details

```

```

**Comment by flickz** [comment]
@az89629900089 Please provide more information on the error.

**Comment by znarf** [comment]
Closing. Feel free to re-open if you have more details.
