### ISSUE TITLE
Error in Tax Form tests

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2306]
**Describe the bug**

When executing CI, the Tax Form tests are generating an error.

See for example: https://circleci.com/gh/opencollective/opencollective-api/17389 

```
    sendHelloWorksUsTaxForm
      ✓ updates the documents status to requested when the client request succeeds
Cannot find module 'pg-native'
error: Failed to initialize tax form {"dataValues":{"_salt":"$2b$10$D.AyFHhEgb7kvAFmrByf6O","refresh_token":"$2b$10$QnF7M2otFrrTdqEEmOHAeu","createdAt":"2019-08-06T06:10:29.429Z","updatedAt":"2019-08-06T06:10:29.478Z","newsletterOptIn":false,"id":
```

**Comment by pietgeursen** [comment]
This is really strange. I never saw anything like this when I was developing.

There is this issue: https://github.com/sequelize/sequelize/issues/3781 that _might_ be the problem. Has the pg module or something pg related been updated recently?

**Comment by znarf** [comment]
The first CI run highlighting the error is https://circleci.com/gh/opencollective/opencollective-api/17348 triggered after https://github.com/opencollective/opencollective-api/pull/2351

@Betree any idea?

**Comment by Betree** [comment]
Found it, I introduced this by logging the user object -- logging sequelize models is usually a bad idea. Pushing a fix now.
