### ISSUE TITLE
Modules option for next/dynamic has been deprecated

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2308]
When running `npm run build:next`, we can see the following warning in the output.

```
The modules option for next/dynamic has been deprecated.
See here for more info https://err.sh/zeit/next.js/next-dynamic-modules
```

This is currently used in https://github.com/opencollective/opencollective-frontend/blob/master/components/collective-page/SectionAbout.js

We should move away from this pattern.

**Comment by Betree** [comment]
I already had this one in my TODO
