### ISSUE TITLE
Generate a receipt for recurring donations

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#231]
Sponsors often want a receipt for each recurring donation. I doubt each backer wants that. So, let's add a receipt for any monthly donation of $100 or more.

@piamancini fyi

**Comment by piamancini** [comment]
good idea

**Comment by piamancini** [comment]
Guys, sponsors are again asking for this receipt. I'll generate it manually, but it will keep happening monthly. It'll be great to automate this.

**Comment by asood123** [comment]
Should be happening now for anything over $10.

**Comment by piamancini** [comment]
$10 included?

**Comment by asood123** [comment]
Hmm looking at the code, it's still set to $50 or above for a receipt. I thought @xdamman changed it to $10. Do you want to change it to $10?

**Comment by piamancini** [comment]
yes please, or Nik Graf's invoices will still need to be generated manually.

**Comment by asood123** [comment]
https://github.com/OpenCollective/opencollective-api/pull/683
