### ISSUE TITLE
White logos are not visible on the new collective page

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2310]
Similar to #1689 

This issue has already been reported in https://github.com/opencollective/opencollective/issues/2225#issuecomment-511247060 and on Figma but it's critical that we find a proper solution before the realease of the new collective page.

@raulgrafico do you have a plan/ideas for this?

**Examples**
- https://opencollective.com/triplebyte/v2
- https://opencollective.com/gulpjs/v2

![image](https://user-images.githubusercontent.com/1556356/62634280-e94c2e80-b935-11e9-92cb-0a32a1f287bf.png)

![image](https://user-images.githubusercontent.com/1556356/62633844-1d731f80-b935-11e9-9a43-8fdaeddfea1a.png)

**Comment by cuiki** [comment]
I superficially brainstormed an idea to fix this with @raulgrafico yesterday. I'll drak up a sketch and show it to show later today.

**Comment by yellowwoods12** [comment]
@Betree one way to solve this issue can be to check for the RGB values of the logo and if it turns out to be more of white then either adjust the background color accordingly or can shift the logo over a darker background.

**Comment by Betree** [comment]
@yellowwoods12 That could work but it is costly to implement so we need a clear decision from @opencollective/design before we go for it :slightly_smiling_face: 

Most platforms (eg. facebook) don't bother with that, they clearly specify that avatars will be displayed on a white background and that it's your responsibility to upload something that looks nice. It's way simpler but we need to make it super-clear on the interface to upload an image.

**Comment by piamancini** [comment]
@raulgrafico @cuiki what's the decision here?

**Comment by raulgrafico** [comment]
Our original idea was to set all to a Blue (or Black, this is right now the default color for our Hero image, but I prefer to use blue as the default color  ) default color, to encourage users to select the color accent and customize it.

I left @Betree a note on Figma to make it easier for him to find the appearance of it.

![01](https://user-images.githubusercontent.com/1252676/63296534-ebe34800-c294-11e9-9828-b249b334aead.png)

**Comment by raulgrafico** [comment]
Playing a little with the CSS I made this demo on how Gulp page would look, using these criteria for the Hero Image, same color for Hero image and logo container.

![Unknown](https://user-images.githubusercontent.com/1252676/63297139-4fba4080-c296-11e9-8d7d-84326d631a79.png)

**Comment by Betree** [comment]
@raulgrafico So the idea is that the color you pick as Primary Color for your collective will be used as the logo's background?

**Comment by piamancini** [comment]
That makes sense to me.

**Comment by Betree** [comment]
I just realized that there's an important issue with this approach: in all other places of the website (contribution flow, contributors list, members cards...etc) and in the emails, we show the logos on a white background. If we do what's proposed here, people will start uploading white logos that will look great on the new collective page but will be barely visible in all other places.

If we're not ready to tackle this issue in a systematic way yet, I'd suggest we do the following

> Most platforms (eg. facebook) don't bother with that, they clearly specify that avatars will be displayed on a white background and that it's your responsibility to upload something that looks nice. It's way simpler but we need to make it super-clear on the interface to upload an image.

**Comment by piamancini** [comment]
good catch. 
Agh this is hard because the current background is not white so we'll break a lot of logos. 
I would be ok with the approach going forward, what's the best way of let current users know? 
For sure adding a note on this when we release, but is there any way we can query to know which ones are transparent / white? I'm guessing no, but worth trying.

**Comment by Betree** [comment]
> what's the best way of let current users know?

That's where I love inline editing, if we follow the design proposed by @raulgrafico for the edit we shouldn't even have to add a message because collectives admins will be able to see how their logo look like on a white background before changing it:

![image](https://user-images.githubusercontent.com/1556356/63415934-ca9e6b00-c3fe-11e9-97c4-2b1d1c06e2cb.png)

Our support communication for collectives if they encounter problems with that in the future should then be:
> All logos are always displayed on a white background. If you have a white/transparent logo, please edit the image to set a background manually with the color of your choice.

**Comment by Betree** [comment]
To notify current users, I guess we should add a message about it in the newsletter that will come with the new collective page release. It would be hard to query that indeed, but we can build up a list manually with the ones we already know and contact them manually. If you'd like to do this, **please edit this comment to add yours** (I'll come back there to do it as well): 

- triplebyte
- gulpjs

**Comment by znarf** [comment]
@Betree what's the latest resolution on that?

**Comment by Betree** [comment]
@znarf Latest (and final) resolution is to specify that **all** logos on Open Collective will always be displayed on a white background. It is the responsibility of the admins to upload something that looks nice.

**Comment by znarf** [comment]
Thank you! A good issue is a closed issue.
