### ISSUE TITLE
Fiscal hosts should be able to send updates

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2314]
## User story 
As a fiscal host admin, I want to be able to send updates to all core contributors in my host, plus anyone else who wants to subscribe to updates. This would be used for announcements, changes to fiscal hosting terms, etc.

## Best solution for this problem
Same update feature we have for Collectives enabled for hosts, including showing updates on the host page in addition to emailing them. Core contributors of Collectives in that host should be automatically subscribed when they join the host.

**Comment by xdamman** [comment]
+1

Open Collective UK would love to send an email to all the collectives they are hosting. 
It’s very important for them (and other hosts) to be able to develop their community.

I like the idea of automatically following the host when you are accepted to be hosted.
But this requires a some other changes (that would all be great to see btw)
- Capacity to follow a collective (receive their updates without having to become a backer)
- Allow organizations to have the “Updates” section

In the meantime, in the same way that we can publish an update only for backers, it would be good to be able to create an update visible only to hosted collectives. This will offer an easy way to reach out to all hosted collectives. It would also be good to allow for comments below an update.

**Comment by alanna** [comment]
Would it be difficult to turn on updates for hosts since we already have that feature built for Collectives? Maybe it could be a bounty? Would be good to hear from the devs about scope for this.

**Comment by Betree** [comment]
The engineering work for this is pretty simple and could be a bounty.

What we miss is to properly surface the information of "who will receive this update". In the case of hosts, we need to make it clear that they're sending it to the admins of the Collectives they're hosting (and not to their contributors, as it is today for Collectives).

**Comment by alanna** [comment]
> the information of "who will receive this update".

For MVP I think we can just address that in docs, then in the future we could add more options for recipients or allowing people to subscribe who aren't Collective admins. We can keep it simple at first.

**Comment by Betree** [comment]
We should at least update the wording for `Private update` because it doesn't make much sense to talk about contributors there. The option should be for the update to only be visible to the collective admins.

If we want a simple MVP, we can also hide this option for host updates.

![image](https://user-images.githubusercontent.com/1556356/80951087-72c25b80-8df7-11ea-85e0-ecdaa06b5000.png)

**Comment by alanna** [comment]
@znarf should this issue be part of #3161 ? If the Host's Collective is folded into the Host page, they will lose the ability to do Collective updates right now, unless we enable it.

**Comment by znarf** [comment]
@Betree could you setup a bounty for this one?

**Comment by Betree** [comment]
Specs below, where I've disabled private updates for hosts as it introduces some complexity in `canSeeUpdates` to check if the user is allowed to see the update.

Note that thanks to https://github.com/opencollective/opencollective-frontend/pull/3567, organizations are already able to send updates so the main task here is to make sure we send the update to the right users and to make things clearer in the frontend.

# Specs

## API

- [ ] When publishing an update, if the collective publishing it is a host, also send the update to all core contributors of collectives hosted by this host.

## Frontend

- [ ] Allow users to enable "Updates" in the `/edit` if they have `isHost === true` 
- [ ] Hide the "Private update" checkbox when sending the update as a host
- [ ] On the "Preview update" screen, when sending the update as a host, change the message to `Your update will be sent to x financial contributors and y collective admins`

![image](https://user-images.githubusercontent.com/1556356/83730671-b18f3f80-a649-11ea-968c-10e7c6af93c0.png)


---

Please follow our [code guidelines](https://docs.opencollective.com/help/developers/best-practices-and-code-guidelines), especially:

* The strings must be internationalized. See [/help/developers/translations](https://docs.opencollective.com/help/developers/translations)
* Whenever it's possible we must use `styled-components` to write styles. See [OC Styleguide](https://opencollective-styleguide.now.sh/)
* We're getting rid of `Bootstrap`. Please don't use it for new developments.
* Tests written with Cypress must follow our [good practices](https://docs.opencollective.com/help/developers/testing-with-cypress) conventions.

**Comment by snitin315** [comment]
@Betree is this a bounty ?

**Comment by Betree** [comment]
@snitin315 it is now :slightly_smiling_face:

**Comment by snitin315** [comment]
taking this up.

**Comment by Betree** [comment]
I've updated the specs to make target audience (collective admins or financial contributors) configurable.

**Comment by snitin315** [comment]
>  Add a select to choose who this update will be sent to:

@Betree where should I add the selection?  with the publish button or in place of the private update checkbox?

**Comment by Betree** [comment]
@snitin315 It makes sense to show it with the publish button like you did

**Comment by Betree** [comment]
:trophy: This issue has been completed by @snitin315 (opencollective/opencollective-frontend#4547 + https://github.com/opencollective/opencollective-api/pull/4119). 

To claim the **$500** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
