### ISSUE TITLE
Should host have their own collective types?

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2316]
I'm wondering why hosts doesn't have their own collective type (like `USER`, `ORGANIZATION`...etc). It sounds like it would make it easier to recognize them (today we check in the `Members` table to see if the collective hosts other collectives).

Hosts also have very specific features and most of the time we don't care if a host is an organization or a user. Or do we?

@piamancini @xdamman @znarf do you have some background about that?

**Comment by znarf** [comment]
The problem is that today hosts are `USER` or `ORGANIZATION`. Whatever we do, an existing `USER` accounting should keep the "user" behavior.

I agree with you, the platform would be much clearer if "hosts" had their own type `HOST`.

**Comment by alanna** [comment]
This would certainly help with #2062 - we need to send different onboarding emails to hosts and sponsor orgs, they have different features, the designers need to think differently about them. So if making them different types in the database would help with all that, I support the idea.

**Comment by alanna** [comment]
I just raised #2326 about terminology in edit settings needing to be different for Fiscal Hosts, Organizations, and Collectives, which is related.

**Comment by znarf** [comment]
We'll be using User/Organization with `isHostAccount=TRUE` for now.

**Comment by Betree** [comment]
> We'll be using User/Organization with `isHostAccount=TRUE` for now.

Solves the lack of having an easy way to recognize hosts for me. Closing.
