### ISSUE TITLE
Private comments on expenses

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2317]
## User story 
As an expense submitter or host admin I want to be able to discuss private details on expense comment threads without them being publicly visible. Expenses often entail confidential info like addresses, phone numbers, bank info, emails, etc. Right now there's no good way to communicate about these things on an expense. It's important for records to keep all info about expense transactions in one place instead of splitting out into email threads, etc.

## Best solution for this problem
I could see a few options:

* Make all expense comments private - not as good for transparency but the majority of expense comments aren't super critical for the whole world to see, and sharing private info on the internet is worse in many ways.
* Have an option for "private comment" that you can tick so the comment will only be visible to Collective admins, host admins, and the submitter.

**Comment by Betree** [comment]
I think we dropped this idea in favor of private notes.

The main argument was that a conversation thread mixing both private and public comments would create strange conversations for users not allowed to see them and that there was a risk of leaking private data by having someone quoting a private comment in a public one.

@piamancini if you can confirm

**Comment by piamancini** [comment]
confirmed.
