### ISSUE TITLE
Design and copy for "Back My Stack" banner

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2318]
We're introducing a new feature on BackYourStack to let users subscribe to a monthly plan.

The MVP of this feature will be available for users uploading their dependency files themselves.

This is the current version in development.

![Screenshot_2019-08-12 BackYourStack Discover the Open Source projects you are using and need financial support ](https://user-images.githubusercontent.com/806/62852895-0f355280-bceb-11e9-8bd6-dc01319da989.png)

**Title**: NEW: Automatically Back Your Stack every month

**Text**: With our monthly plan available from Open Collective, commit a fixed amount every month and the money will be automatically dispatched to your dependencies!

**CTA**: Back My Stack

- [ ] Check copy @piamancini @alanna 
- [ ] Give design input @raulgrafico @Memo-Es @cuiki

**Comment by piamancini** [comment]
> With our monthly plan available from Open Collective, commit a fixed amount every month and the money will be automatically dispatched to your dependencies!

Set up a monthly subscription and we will automatically distribute the funds among your dependencies on Open Collective!

**Comment by piamancini** [comment]
Where are we explaining that we will update as new dependencies come in?

**Comment by znarf** [comment]
Here: https://github.com/opencollective/opencollective/issues/2319

**Comment by piamancini** [comment]
got it (sorry forgot we did that one already)

**Comment by piamancini** [comment]
@znarf are you ok closing this? 
@lindatalu the issues we asked closing are the ones only for design and created by you. Not issues from engineering.
