### ISSUE TITLE
Design and copy for BackYourStack Monthly Plan presentation

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2319]
We're introducing a new feature on BackYourStack to let users subscribe to a monthly plan.

The MVP of this feature will be available for users uploading their dependency files themselves. Once they click on the "BackMyStack" CTA, they get the following presentation screen to present them the feature.

This is the current version in development.

![Screenshot_2019-08-12 BackYourStack Discover the Open Source projects you are using and need financial support (1)](https://user-images.githubusercontent.com/806/62853472-c54d6c00-bcec-11e9-88d4-b1aa5866de1a.png)

> **Brilliant!**

> You're about to subscribe to the BackYourStack monthly plan on Open Collective.

> Each month, you will be charged once by BackYourStack through Open Collective. The money will then be dispatched equally between all detected dependencies.

> If new dependencies are joining Open Collective, they will be detected and taking care of in the next monthly dispatch.

> Example: you decide to give $200 within the monthly plan.

> Estimation, final value may be slightly different depending of payment processor fees.

> Sounds good?

> **Continue on Open Collective**

- [ ] Check copy @piamancini @alanna
- [ ] Give design input @raulgrafico @Memo-Es @cuiki

**Comment by alanna** [comment]
Should this be through Open Collective or Open Source Collective? Which entity will be receiving the funds and providing receipts? If it's OSC, is the service limited to Collectives hosted by OSC?

What happens if they have a dependency that does not have a Collective already? Will it create a pledge? I think this is an amazing channel for onboarding new Collectives.

What happens if they already separately have set up a recurring financial contribution to a Collective on their list? Will that be cancelled? Or will they just have a double contribution now?

Can use real numbers for them instead of an example? Allow them to enter the amount they want to pay on this screen and automatically update the amount given to each dependency, so they can adjust it when they see the real numbers. Let's make the default high! How about $100 x number of dependencies detected.

For the list of dependencies, let's use the Collective name instead of the slug.

Copy changes below:

> **You're about to Back Your Stack!**

> You'll make a single monthly payment and we'll distribute the funds to your detected dependencies below. If new dependencies join in the future, they will be detected and addedthe following month.

> Monthly payment: [  $900  ] (box editable by user)

> * *May vary slightly depending on payment processor fees.*

> **[ Back My Stack ]**

**Comment by znarf** [comment]
> Should this be through Open Collective or Open Source Collective? Which entity will be receiving the funds and providing receipts? If it's OSC, is the service limited to Collectives hosted by OSC?

This is done through the Open Source Collective and will be limited to collectives on the Open Source Collective.

@flickz let's double check the behavior if we try to dispatch money to collectives on a different host.

> What happens if they have a dependency that does not have a Collective already? Will it create a pledge? I think this is an amazing channel for onboarding new Collectives.

This is considered but not part of the present feature set.

> What happens if they already separately have set up a recurring financial contribution to a Collective on their list? Will that be cancelled? Or will they just have a double contribution now?

We might be able to detect that. But for now we're not trying and this will create a second contribution.

> Can use real numbers for them instead of an example? Allow them to enter the amount they want to pay on this screen and automatically update the amount given to each dependency, so they can adjust it when they see the real numbers. Let's make the default high! How about $100 x number of dependencies detected.

The idea is to have a fixed monthly plan and divide, so we will not do something like $100 / dependency. We're considering letting them adjusting the weight of each dependency. We can imagine they will be able to set the full amount and adjust the results live. This is not part of the present MVP but this is doable/scheduled in future iterations.

**Comment by alanna** [comment]
Yes I understand about making it one monthly total. What I meant was, let's let them input that total on this screen so they can see the numbers update dynamically. The $100/Collective suggestion was just about the default total to start with in the box, which they can edit. If we anchor that high, people may decide to make their total high.

**Comment by alanna** [comment]
If this is restricted to Open Source Collective, then we should refer to OSC in all instances, not Open Collective. Myrewrite of the text removes this issue in this particular instance by taking out references to both.

However, we will need to incorporate an explanation about the restriction to OSC somewhere, because people might search a dependency an see a Collective in OC EU for example for an open source project, then not understand why it's not included.

**Comment by flickz** [comment]
> let's double check the behavior if we try to dispatch money to collectives on a different host.

Noted.

**Comment by piamancini** [comment]
Edits to @alanna's copy: 

Congratulations, you're about to Back Your Stack!

You'll make a single monthly payment and we'll distribute the funds to your detected dependencies below. If new dependencies join in the future, they will be detected and added the following month. Your subscription will not change, we'll distribute it amongst more dependencies You can always update the amount _(where?)_

Monthly payment: [ $900 ] (box editable by user)

May vary slightly depending on payment processor fees.
[ Back My Stack ]

**Comment by znarf** [comment]
This issue was about copy, not changing the behavior (ie: box editable by user). Please create a feature request issue if you want to make that happen. I will not change this part of the copy for now, feel free to propose something that doesn't impact the behavior in the meantime.

Also, the "Continue on Open Collective" is important because we want to hint the users that they're about to leave the "BackYourStack" site. The "Back My Stack" proposed copy is failing at that point.

<img width="641" alt="Capture d’écran 2019-08-23 à 14 34 12" src="https://user-images.githubusercontent.com/806/63592944-1abe2e80-c5b3-11e9-9bb8-1a198461fbd8.png">

**Comment by piamancini** [comment]
copy can remain the same. No need to change it, even if box is not editable. You can go ahead and update it. I'll create a new issue for the box behaviour.

**Comment by piamancini** [comment]
"The "Back My Stack" proposed copy is failing at that point." Ok then update the button to Back your Stack and add a small caption that they will be moved to another website? This is how it's normally handled imho

**Comment by piamancini** [comment]
idem @znarf - not sure if you want this closed. I think we haven't released yet so should stay open.
