### ISSUE TITLE
Design and copy for BackYourStack Monthly Plan confirmation

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2320]
We're introducing a new feature on BackYourStack to let users subscribe to a monthly plan.

The MVP of this feature will be available for users uploading their dependency files themselves. To do that, we're redirecting them to Open Collective and allow them to subscribe to the monthly plan there. Once done, we're redirecting them to BackYourStack an they get a confirmation page explaining what happened and what's next.

This is the current version in development.

(Insert screenshot here)

> Woot woot! 🎉

> Your first payment was successfully dispatched, you just backed he following collectives:

> What's next? Your subscription being now active, you will be charged next month and the money will be automatically dispatched to your dependencies. You don't have to do anything. 🤞

- [ ] Check copy @piamancini @alanna
- [ ] Give design input @raulgrafico @Memo-Es @cuiki

**Comment by alanna** [comment]
Copy changes:

> Woot woot! 🎉 Your first payment was successfully dispatched. 

> You're contributing to the following Collectives:

> That's it! You will be charged each month and the funds will be automatically distributed to your dependencies.

It says "was successfully dispatched" so they should be able to immediately see their contribution on the Collective's page, right? If it's not immediate we should change the text.

How will this interact with our monthly billing cycle - will they be charged on the day and again on the 1st of the month? If so (and we're not going to fix #1215 before this launches) we will need to include big bold text here explaining that, or we're definitely going to get irate support requests about being double charged if they set this up late in the month.

**Comment by znarf** [comment]
> It says "was successfully dispatched" so they should be able to immediately see their contribution on the Collective's page, right? If it's not immediate we should change the text.

Yes, exactly like that.

> It's done through a monthly subscription on BackYourStack, so it's exactly the same. We should effectively write that straight on this screen.

**Comment by alanna** [comment]
OK let's change it to:

> That's it! You will be charged for the first time today, then on the 1st of each month from now on. The funds will be automatically distributed to your dependencies.

> * *Note: Since the next charge will be on the 1st of the month, you may be charged twice in a short period if you set this up near the end of the month.*

> Thank you for Backing Your Stack!

**Comment by piamancini** [comment]
good catch.

**Comment by znarf** [comment]
Latest screenshot (will try to do another with some content in the table). 

<img width="683" alt="Capture d’écran 2019-08-23 à 16 15 26" src="https://user-images.githubusercontent.com/806/63599167-5102aa80-c5c1-11e9-9232-533570345b69.png">

**Comment by alanna** [comment]
Looks good!
