### ISSUE TITLE
Update docs.opencollective.com/help urls

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2321]
In order to be able to have multiple books in gitbook with their own url, we have to move the subdomain docs.opencollective.com from the account level to the book level in GitBook.

That way we can have docs.opencollective.brussels, .paris, etc.

A side effect is that instead of having docs.opencollective.com/help we will have docs.opencollective.com (which arguably looks nicer but may break some URLs).

**Comment by alanna** [comment]
Are Paris, Brussels, etc requesting a way to create their own gitbooks on the domain? Or is this for the future?

**Comment by xdamman** [comment]
Turns out that we can keep them as they are. 
I don’t know if they fixed something on their side but right now docs.opencollective.com works as before (with the /help) and docs.opencollective.brussels works as well. 

Yes Open Collective Brussels asked for a place to document how collectives can “hire” people in Belgium, how they should address invoices, etc.

Extinction Rebellion also needs a place to document how Local Finance Working Groups can get started.

I’ll close the issue for now.

**Comment by alanna** [comment]
OK. I think it would be cool to have a seperate gitbook for a host guide too.
