### ISSUE TITLE
Host admin can un-pay an expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2324]
## User story 
As a host admin, I want to be able to un-pay expenses previously marked as paid, because sometimes payments fail unexpectedly after the fact, and we need to be able to reflect that in the system.

## Best solution for this problem
A `mark as unpaid` button on paid expenses accessible to host admins. Clicking it would reverse all the associated ledger transactions (fees, debits) and push the expense back to 'approved' status.

**Comment by yellowwoods12** [comment]
For this problem we can directly link it with paypal and if there is some error in processing the payment then it can automatically be marked as unpaid. What say?

**Comment by alanna** [comment]
The main time this is needed is actually for non-paypal transactions we manually mark as paid. That's because paypal transactions through the API happen instantly and will fail and not be marked as paid if there is a problem. But bank transfers and echecks and other methods take a few days to clear, so the expense is marked as paid but later needs to be reversed.

**Comment by yellowwoods12** [comment]
> The main time this is needed is actually for non-paypal transactions we manually mark as paid. That's because paypal transactions through the API happen instantly and will fail and not be marked as paid if there is a problem. But bank transfers and echecks and other methods take a few days to clear, so the expense is marked as paid but later needs to be reversed.

This reminds me of the scenario that happened with me. With paypal too even when the transaction was unsuccessful, the status on the website showed "paid".I was not clear whether it's a bug or not.

**Comment by flickz** [comment]
@alanna How do we deal with user's email notification in this case? They've been notified before that their expense was paid, updating the status of the expense back to "Approved" will trigger another notification about expense approval. This is going to confuse them.

**Comment by alanna** [comment]
In these cases we are almost always in touch with the suer directly because there's been an issue with the payment. For an MVP, I think not sending any notifications when unpaid is fine. When it's paid again, it should send a payment notification as normal.

**Comment by flickz** [comment]
Closed in https://github.com/opencollective/opencollective-frontend/pull/2724 & https://github.com/opencollective/opencollective-api/pull/2652

**Comment by alanna** [comment]
@flickz is this deployed in production? I don't see an unpay option.

**Comment by znarf** [comment]
@alanna we haven't deployed since monday, we'll try to do that tomorrow
