### ISSUE TITLE
We need different terminology for sponsor organization settings

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2326]
I just had a sponsor get super confused because the terminology in the organization settings is not correct for their context. We need to differentiate terms used on sponsor orgs from terms used in Fiscal Host orgs and from Collectives.

For sponsor orgs, "core contributors" should be "team members". "Collective admin" should be "Organization admin". I think these should be the same for Fiscal Hosts (team members and organization admin).

**Comment by znarf** [comment]
@alanna there is a difference between copy changes and filtering some settings.

Can you focus this issue on the copy and create a new one for the settings that should be filtered?

**Comment by alanna** [comment]
OK lets make this one about terminology. I have opened #2380 about settings.

**Comment by piamancini** [comment]
@alanna I think we can close this.

**Comment by alanna** [comment]
closing in favor of #2316
