### ISSUE TITLE
Give people a way to avoid Github verification when creating a new Collective

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2328]
## User story 
As a Collective creator of an open source related Collective, I want to be able to set up a new Collective without being forced to join Open Source Collective or verify using the 100 Github stars requirement, so that I can create a self-hosted Collective or apply to a different host.

## Best solution for this problem
When going through the create Collective process, if they select "open source" as their type, instead of automatically sending them to verify using Github stars, give them the option to do that or continue without Github verification. They should be able to choose to host themselves, have no host, or apply to a different host than OSC.

## MVP
Our current workaround for this is to tell them to choose 'other' instead of 'open source'. But they have no way to know this unless they contact support. Maybe add some help text on the tags screen if they select 'open source' saying "If you don't have 100 Github stars, choose 'other' instead".

**Comment by piamancini** [comment]
> Maybe add some help text on the tags screen if they select 'open source' saying "If you don't have 100 Github stars, choose 'other' instead".

Maybe the Open Source one should say 'via Github' and the other Open Source?

**Comment by sbinlondon** [comment]
I believe this is now being solved in opencollective/opencollective#2874 with the new Create Collective Flow

We offer 'request manual verificaiton' instead of verifying by stars

Will close this issue once it's merged

**Comment by alanna** [comment]
This is fixed in the new flow
