### ISSUE TITLE
#design Follow and volunteer

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#233]
We want to have new levels of engagement:

1- Follow:
This collective is interesting to me, I don't want to commit to become a backer or to volunteer yet but I want to keep an eye on it

2- Volunteer/Contribute:
I don't have money but I'd love to contribute / volunteer (or I have money but I'd also be happy to contribute time). Should be able to give a time commitment (e.g. between 1-5 hours per month) and a list of skills. That will also help build up the profile of that person.

3- As a core contributor, post requests for volunteers
E.g. we need a new maintainer, a designer, someone to record videos, someone to help checkin people at the door, etc. (also with time commitment bracket)

**Comment by piamancini** [comment]
Just had a chat with a group in Greece interested in collectives with these
levels of contributors as well.

**Comment by erickrico** [comment]
hey this is what i have came up with so far, i think we can use the categories we already have from expenses to let users recognise what they can do to contribute faster, 
Each card consist of:
- category tag
- Tittle (50 characters)
- Details of the request (130 characters)
- Cta

![screenshot 2016-09-13 16 16 00](https://cloud.githubusercontent.com/assets/18429104/18491899/4a63c02a-79ce-11e6-9a7e-776d866ea5be.png)

**Comment by xdamman** [comment]
I really like this idea of cards and the idea of suggesting a contribution. I think it's very important because the collective may not think of something that I could contribute that could be useful. 

Now I wonder how we could convey who did contribute what and show where there is already a lot of contributors and where there is less. Thoughts?

**Comment by erickrico** [comment]
i think this version can work to acknowledge the contributor
![screen shot 2016-09-19 at 2 25 09 am](https://cloud.githubusercontent.com/assets/18429104/18625006/3e9cf7f6-7e11-11e6-96fa-67097887c233.png)

and for the visibility im working on a activity feed, but is more of a global feature of the collective, let me know what you think of it 
![screen shot 2016-09-19 at 2 33 45 am](https://cloud.githubusercontent.com/assets/18429104/18625044/88566850-7e11-11e6-8668-08329a9decbb.png)

**Comment by xdamman** [comment]
I really like that from the top of the very first page, people can directly see what a collective is all about. 

It's a detail that we can change later but the order of tabs should be different. It should be in the order of the questions that people would have about a collective:
- Who are we?
- Our values
- Join us (or "our suppporters"?)
- Next events
- Contribute

(There is no need for transparency as this is a value and something that people can see)

It's really good work Erick!

**Comment by piamancini** [comment]
leaving this open as it might be useful for #502

**Comment by piamancini** [comment]
@cuiki do you need/want this open still?

**Comment by cuiki** [comment]
Yes. I can put it in queue, unless it is something we will not do, in which case I would close it. But if it is something that makes sense I'll leave it open and just move it to the queue (low priority) list.

**Comment by piamancini** [comment]
I don't think we'll be doing this anytime soon. @xdamman ?

**Comment by piamancini** [comment]
closing for like of activity. Re open when it becomes a priority
