### ISSUE TITLE
Account creation form distorted when arriving via opensource/apply > join

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2334]
**Describe the bug**
Sign in form looks squashed and is pretty unusable.

**To Reproduce**
1. While signed out, go to https://opencollective.com/opensource/apply
2. When it asks you sign in, click 'join free'
3. See broken formatting

Oddly this does not seem to happen when starting from https://opencollective.com/create and following the same steps.

Originally reported by a user and I was able to reproduce. Both of us are using Chrome on Mac.

**Screenshots**

<img width="1545" alt="Screen Shot 2019-08-15 at 3 57 11 PM" src="https://user-images.githubusercontent.com/5498878/63137684-69a41b00-c02b-11e9-93c8-c4310110d329.png">

![Screen Shot 2019-08-16 at 1 38 57 PM](https://user-images.githubusercontent.com/5498878/63137687-6d37a200-c02b-11e9-857c-883f0a868b8b.png)

**Comment by znarf** [comment]
Doesn't look Chrome specific, same on Firefox.

@flickz can you have a look?

**Comment by flickz** [comment]
Okay

**Comment by flickz** [comment]
This is really tricky, as it is not reproducible locally but it also affect staging.

**Comment by znarf** [comment]
Can you try locally with a production build? `NODE_ENV=production npm run build` then `NODE_ENV=production npm run start`

**Comment by flickz** [comment]
Okay I can confirm this is happening as a result of dependencies change or something related. Initially I was not getting this locally till I ran `npm install` I've not been able to identify which exact dependency is causing this, I'm still looking into it.

**Comment by flickz** [comment]
@znarf This is happening from bumping `@rebass/grid` from `v 6.0.0` to `v 6.1.0`.

**Comment by znarf** [comment]
@flickz "update to Styled System v5" is the only change and that matters. @Betree already fixed a regression last week related to that.

**Comment by znarf** [comment]
Looks like the project will be renamed to https://github.com/rebassjs/rebass/tree/master/packages/reflexbox, but that's unrelated.

**Comment by flickz** [comment]
> update to Styled System v5

Our current version of styled system is `5.1.0`

**Comment by znarf** [comment]
@flickz I'm talking about  "update to Styled System v5" from https://github.com/rebassjs/grid/blob/master/CHANGELOG.md

Whatever what we use, they ship their own version. In the update to 6.1.0, they updated to styled-system 5, before it was version 4. This is likely the breaking change.

**Comment by flickz** [comment]
Can we go back to the previous version of `@rebass/grid` `v6.0.0` as a temporary fix?

**Comment by znarf** [comment]
I don't think so, @Betree already adapted a component to the new version and I guess the changes are not retro-compatible. https://github.com/opencollective/opencollective-frontend/pull/2343

**Comment by znarf** [comment]
@Betree can you have a look?

**Comment by Betree** [comment]
I believe this is because `minWidth` wasn't doing anything for `Flex` in previous version of `styled-components`. It is now a valid prop and so the following line was breaking the page when the SignIn is combined with a FAQ:

https://github.com/opencollective/opencollective-frontend/blob/4750abbb68e0850fc7e4d38dbdbfe527d1c924f3/pages/openSourceApply.js#L223
