### ISSUE TITLE
Paypal Email visible to non-admins

### ISSUE THREAD

**Issue by connyduck** [opencollective/opencollective#2335]
**Describe the bug**
I can see the Paypal email in the expenses of a Collective I am no admin of.

**Expected behavior**
Only Collective Admins should be able to see PayPal emails.

**Screenshots**
Why am I seeing this, I am no admin of this Collective
![Screenshot 2019-08-16 at 21 25 22](https://user-images.githubusercontent.com/10157047/63193112-ed322c00-c06c-11e9-909a-fa32e206826a.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Firefox

**Additional context**
@stom79 donated to my project, and I to his. Other than that there are no connections between the two accounts, and there is no reason to leak the email address of any of us. I also noticed that I can see the email of users who submitted expenses to my collective on other collectives.

**Comment by znarf** [comment]
I inspected the behavior and it's working as intended in the code base.

If someone is a member of a collective that you're administrating, you have access to their personal informations like their email and their paypal email. This permission is granted everywhere and is not specific to a specific collective. 

I understand the way it's surprising you but it's not a security hole, but more something that needs to be better explained or reconsidered in a new iteration.

**Comment by znarf** [comment]
Closing. Feel free to follow up in a new issue if needed.
