### ISSUE TITLE
Enable deletion of rejected expenses by Host and Collective admins

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2337]
If someone submits an expense to a Collective, even if it's rejected there is no way to fully delete or hide that from the Collective's public page. This is not good when someone uses expenses as a method for spam ([example](https://opencollective.com/pixijs/expenses/9638)).

Should we allow Collective admins to fully delete rejected expenses if they wish? Because it's for rejected expenses only I don't see a huge issue for transparency. But if there are concerns about it, we should at least allow Host admins to delete expenses if requested.

**Comment by znarf** [comment]
I'm fine allowing deletion of rejected expenses. Can we create an issue for that?

**Comment by piamancini** [comment]
+1

**Comment by alanna** [comment]
I've updated this issue to be able the specific rejection solution.

**Comment by sudo-kaizen** [comment]
Can I hop on this? I think I've worked on this part of the codebase before

**Comment by znarf** [comment]
@sudo-kaizen sounds good

**Comment by flickz** [comment]
@alanna Do you think we should have a rejected tab too, to make deleting easier?

<img width="558" alt="Screenshot 2019-11-19 at 10 42 24 AM" src="https://user-images.githubusercontent.com/15707013/69135351-491baf00-0ab9-11ea-9e2a-5b349ea08506.png">

**Comment by alanna** [comment]
@flickz it sounds useful to have a rejected tab, but I don't think it would be used for deletion much. I think the likely users are Collective admins who don't access the host dashboard.
