### ISSUE TITLE
Create collective: dead image/link

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2338]
**Describe the bug**
On https://opencollective.com/create, there's a dead image pointing to `https://images.opencollective.com//logo.png`. Also the link wrapping the image has its `href` set to `/undefined`.

**To Reproduce**
1. Go to https://opencollective.com/create
2. Check the image/link in the cover

**Expected behavior**
- Should display the default collective logo
- There should be no link on the image

**Screenshots**
![image](https://user-images.githubusercontent.com/1556356/63249922-c6414900-c26a-11e9-9f81-f83b21f9dd4b.png)

---

@znarf Could this be linked to recent changes in avatar's API?

**Comment by znarf** [comment]
This will be fixed in https://github.com/opencollective/opencollective-frontend/pull/2086
