### ISSUE TITLE
Apply to host button require a refresh to work properly

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2339]
Following on https://github.com/opencollective/opencollective/issues/2281#issuecomment-522371266

The `Apply to host your collective ...` button require a full page refresh before it shows the collective. I'd rather prioritize https://github.com/opencollective/opencollective/issues/2282 but we need to acknowledge it.

**To reproduce**
1. Create a collective https://staging.opencollective.com/create
2. Click on `Apply to an existing host`
3. Click on `Open source collective`
4. The button displays `Apply to create a collective` instead of showing the newly created one

**Comment by NotJohs** [comment]
@Betree can't reproduce this.

**Comment by Betree** [comment]
Ah I didn't think about it when making the change but I'm pretty sure https://github.com/opencollective/opencollective-frontend/pull/2647 fixed that (because the Apply button looks for pending collectives in `LoggedInUser`). Thanks for testing @NotJohs :+1:
