### ISSUE TITLE
Add date field in Submit Expense

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#234]
We should be able to specify the date of the expense (default: today)
in `/:slug/expenses/new`

**Comment by xdamman** [comment]
Also, it would be good to refresh the list of expenses after submitting so that the newest added expense shows up there.

**Comment by xdamman** [comment]
I would also add a different field "Notes (private)" as an opportunity to justify the expense in a private way (there is already a "notes" column in the Expense model)

**Comment by asood123** [comment]
Dates field disappeared in the redesign. It exists on the backend. Let's
bring it back.

Re: notes. The current field ismeant to be a public field. Another issue
open to make it visible externally (there may be old data in it
pre-migration). We can another field for private notes.

**Comment by xdamman** [comment]
Not sure there is a need to have two different descriptions (description and notes) if they are both public. I'd love to limit the number of input fields to make the process of submitting easier/faster.

**Comment by xdamman** [comment]
Also, when selecting the reimbursement method "Other (please provide instructions)", there is no place to provide instructions. We could also use the private notes for that.

For public comments, we should use comments that will be introduced in the new design (Instagram style where the caption was actually the first comment of the author)
