### ISSUE TITLE
Stripe SCA: offline validation flow

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2346]
From September, we need to support Strong Customer Authentication as it's becoming mandatory to follow European regulation.

- The first part is to implement credit card validation using systems like 3d secure in our contribution flow for new and existing cards. #2340
- The second part is to implement Stripe's "Setup Intents API" while adding new Credit Cards to the account. https://github.com/opencollective/opencollective/issues/2341

The final part is the ability to catch errors in our daily subscription processing scripts. What need to be done?

- [x] in the subscription processing script, catch errors related to SCA and send an email to users explaining the situation and linking to a confirmation page.
- [x] create a landing page enabling users to confirm an order / payment method. Ie: https://opencollective.com/order/{orderId}/confirm
- [x] the page should be using the `confirmOrder` GraphQL mutation and display the Stripe validation actions as necessary (`stripe.handleCardAction`). If success, the failed payment should immediately be processed using the "Payment Intents API".

That's all!

**Comment by znarf** [comment]
![Screenshot 2019-08-21 at 12 47 18](https://user-images.githubusercontent.com/806/63425907-e5c6a600-c411-11e9-9be4-29046890865c.png)

**Comment by znarf** [comment]
@piamancini @alanna This is the current copy for users who will receive SCA (Strong Customer Authentication) notifications. When they click on the link, the will see the following (as implemented in https://github.com/opencollective/opencollective-frontend/pull/2395):

![Peek 22-08-2019 09-42](https://user-images.githubusercontent.com/1556356/63496518-5e853b00-c4c2-11e9-87e9-9331516e203a.gif)

If you have a copy change please let me know.

**Comment by piamancini** [comment]
Email: 

- To comply with new regulations in the EU we are required to confirm ...
- Please confirm your credit card now to continue with this payment.

**Comment by alanna** [comment]
Looks good to me
