### ISSUE TITLE
Unexpected error when ___________

### ISSUE THREAD

**Issue by memilmert** [opencollective/opencollective#2347]
# Describe the bug

I got an unexpected error on https://opencollective.com/pixijs/donate? while I was trying to __________

# To Reproduce

1. Go to ________
2. Click on ________
3. Scroll down to ________

# Device
- OS: Linux armv7l
- Browser: `5.0 (Linux; Android 7.0; SPYbox-S11-CI-Turbo) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.111 Safari/537.36`

# Technical details

```

```

**Comment by znarf** [comment]
@memilmert  thank you for reporting. Can you please give us additional details so we can have a look?
