### ISSUE TITLE
Stats on homepage show wrong numbers

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2349]
**Describe the bug**
There's a section on the homepage showing how many hosts and Collectives we have, but the numbers are wrong.

![Screen Shot 2019-08-20 at 11 06 02 AM](https://user-images.githubusercontent.com/5498878/63305417-d294d700-c33a-11e9-91fa-428462cef10f.png)

**Expected behavior**
I'm not sure what the right numbers are, but the discover page lists over 2000 Collectives and we had 78 active hosts as of July.

**Comment by znarf** [comment]
We can look at it but let's not spend too much time because the homepage is gonna be redesigned soon.

**Comment by xdamman** [comment]
The reason is because we count the number of active collectives on the homepage, whereas we let you discover all the collectives on the discover page.

So I'd propose to simply specify that as a quick solution:

![](https://d.pr/free/i/RkETp3+)
