### ISSUE TITLE
Implement settings page

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#235]
Priority: twitter integration
e.g. https://opencollective.com/opensource/connect/twitter 

See also the design made by @erickrico  https://github.com/OpenCollective/OpenCollective/issues/218#issuecomment-242203492

**Comment by piamancini** [comment]
made obsolete by v2

**Comment by piamancini** [comment]
actually no, this hasn't been solved yet.

**Comment by cuiki** [comment]
Hi @piamancini, do we need design for this? I'm currently organizing all tasks for design work.

**Comment by piamancini** [comment]
I don't think we can tackle this in the short term @cuiki :(

**Comment by cuiki** [comment]
Ok, I'll leave it in queue.

**Comment by piamancini** [comment]
we already have a twitter integration. It seems no one is working on this so I'm closing
