### ISSUE TITLE
manually added funds not showing up

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2350]
**Describe the bug**
I manually added funds to [this Collective](https://opencollective.com/ievobio) but the contribution is not appearing on their page. I got the email notification saying thank you for the contribution, so I know it went through. The balance is showing correctly on the host dashboard.

![Screen Shot 2019-08-20 at 3 56 20 PM](https://user-images.githubusercontent.com/5498878/63316466-17346880-c363-11e9-99ce-56094d14232b.png)

**Comment by piamancini** [comment]
I'm seeing it both in the collective and the sponsor page - What am I missing? 
Sometimes you need to hard refresh to clear the cache and see the changes. My trick is to append a string like ?124 to the url to force it. 

<img width="888" alt="Screen Shot 2019-08-20 at 9 36 26 AM" src="https://user-images.githubusercontent.com/3671070/63327192-07e6f800-c32e-11e9-9460-0b11948307ce.png">
<img width="801" alt="Screen Shot 2019-08-20 at 9 36 32 AM" src="https://user-images.githubusercontent.com/3671070/63327193-07e6f800-c32e-11e9-8aaf-cf2700fc8315.png">

**Comment by alanna** [comment]
OK I am seeing it now. I guess it was just delayed. This could cause anxiety for users so if we can fix that I think it would be good.

**Comment by znarf** [comment]
Closing in favor of https://github.com/opencollective/opencollective/issues/2354
