### ISSUE TITLE
Sort expenses based on added date.

### ISSUE THREAD

**Issue by flickz** [opencollective/opencollective#2351]
Originally from [#2307](https://github.com/opencollective/opencollective/issues/2307), currently we sort expenses based on the user input date
<img width="859" alt="Screenshot 2019-08-07 at 12 58 03 PM" src="https://user-images.githubusercontent.com/15707013/63327651-7de76100-c326-11e9-9ee8-5c92c906d7b3.png">

We should be able sort expenses based on the actual date the user created it.

**Comment by anshumanv** [comment]
Seems like a simple fix, exploring 👍

**Comment by flickz** [comment]
Closed in https://github.com/opencollective/opencollective/issues/2351
