### ISSUE TITLE
Unable to complete free ticket order

### ISSUE THREAD

**Issue by seand7565** [opencollective/opencollective#2352]
**Describe the bug**
We've created an event with a $0.00 ticket for sponsors & organizers. However, I am unable to complete any order with the free ticket. I am able to get to the payment page, where it says "This is a free ticket, you can submit your order directly." however there is no "submit" or "proceed" button. There is a "Make Contribution" button, but it is grayed out.

Our event is here -> https://opencollective.com/solidus/events/solidusconf-2019-21928ev

**To Reproduce**
1. Create an event with a $0.00 ticket
2. Attempt to purchase the ticket and proceed to the payments page

**Expected behavior**
You should be able to check out with a free ticket - ideally with a "Complete Order" button rather than a "Make Contribution" button

**Screenshots**
![image](https://user-images.githubusercontent.com/5720486/63382482-6d53dc80-c360-11e9-8764-2f1407b9c2fd.png)

**Comment by piamancini** [comment]
I can reproduce. 
@Betree do you think this is related to the change you made in the input fields?

**Comment by Betree** [comment]
@piamancini I don't think so, but it may be related to the recent refactor I made (https://github.com/opencollective/opencollective-frontend/pull/2281). I'll check that in priority today.
