### ISSUE TITLE
Refunds not updating everywhere they should

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2354]
A $1000 donation was made in error to [this Collective](https://opencollective.com/techqueria). I refunded it when they contacted support. 

However, the balance of the Collective is still showing those funds. It should be at $0. 

Also, the contributor of the funds ([this org](https://opencollective.com/techqueriaorg)) is still showing as having contributed $1000. 

Refunds should totally reverse all of these immediately.

![Screen Shot 2019-08-21 at 3 00 49 PM](https://user-images.githubusercontent.com/5498878/63399425-95a50f00-c424-11e9-9bcd-2ec0c9ce0ab4.png)

**Comment by znarf** [comment]
It's a CDN side caching issue.

**Comment by piamancini** [comment]
Yes, I am seeing the balance in 0 https://opencollective.com/techqueria

**Comment by piamancini** [comment]
Cache is strong @alanna whenever you make changes like this (or editing, host, etc) append ?124 to the collective's URL to reload a fresh page. You'll see the changes then

**Comment by znarf** [comment]
We should flush the cache when triggering such event.
