### ISSUE TITLE
Unexpected error when ___________

### ISSUE THREAD

**Issue by d923** [opencollective/opencollective#2356]
# Describe the bug

I got an unexpected error on https://opencollective.com/pixijs/donate? while I was trying to __________

# To Reproduce

1. Go to ________
2. Click on ________
3. Scroll down to ________

# Device
- OS: Linux armv7l
- Browser: `5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.111 Safari/537.36`

# Technical details

```

```

**Comment by znarf** [comment]
@d923 thank you for reporting. Can you please give us additional details so we can have a look?

**Comment by d923** [comment]
.github/ISSUE_TEMPLATE/feature_request.md

**Comment by znarf** [comment]
@d923 That's not helping :-)
