### ISSUE TITLE
approvedAt not always set on approved collectives

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2359]
This was tentatively fixed by https://github.com/opencollective/opencollective-api/pull/2416 but we're still getting such entries. 

Right now, we have to run the following query to solve that.

```
UPDATE "Collectives" c
SET "approvedAt" = '2019-08-21'
WHERE c."isActive" IS TRUE
AND c."type" = 'COLLECTIVE'
AND c."HostCollectiveId" IS NOT NULL
AND c."approvedAt" IS NULL
```

**Comment by piamancini** [comment]
do you need help here reaching out to host admins?

**Comment by znarf** [comment]
@piamancini no, there is no need to contact host admins. we just need to make sure this stops happening.
