### ISSUE TITLE
Contribution flow error when tier doesn't exist

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2362]
**Describe the bug**
When users start the contribution flow from an URL that references a tier that doesn't exist (that can happen, for example, if admins remove the tier but someone end up on the URL because it has already been shared outside) we don't show any error message and silently fail instead.

**To Reproduce**
1. Go to https://staging.opencollective.com/babel/contribute/sponsors-999999/checkout
2. Click on `Next step`
3. See error

**Expected behavior**
If the tier doesn't exist, there should be a clear error message displayed instead of the contribution flow with two fallback actions:

```
Oups! This tier doesn't exist or has been removed by the collective admins.

<link route="tiers">View all the other ways to contribute</link>
```

- [ ] This must be implemented in https://github.com/opencollective/opencollective-frontend/blob/80be17d5ed84855588bebce64b36f1d53760c2b9/pages/createOrder.js.
- [ ] Must have a cypress test that opens the URL and ensure the error message is there in `test/cypress/integration/13-contributionFlow.contribute.test.js`

---

Please follow our [code guidelines](https://docs.opencollective.com/help/developers/best-practices-and-code-guidelines), especially:

* The strings must be internationalized. See [/help/developers/translations](https://docs.opencollective.com/help/developers/translations)
* Whenever it's possible we must use `styled-components` to write styles. See [OC Styleguide](https://opencollective-styleguide.now.sh/)
* We're getting rid of `Bootstrap`. Please don't use it for new developments.
* When adding new dependencies, we use [fixed versions](https://docs.npmjs.com/about-semantic-versioning).
* Tests written with Cypress must follow our [good practices](https://docs.opencollective.com/help/developers/testing-with-cypress) conventions.

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by sudo-kaizen** [comment]
Hello @Betree I request to be assigned this issue. Thanks

**Comment by Betree** [comment]
:trophy: This issue is now completed by @JohnTitor 

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
