### ISSUE TITLE
ship a default version of `.env`

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#237]
It's quite annoying to require any developer to have a `.env` file.
The API should ship with a default one (`.env.default`?). We should only require a custom `.env` file when we need to test mailgun, s3, twitter oauth, etc.

**Comment by asood123** [comment]
https://github.com/OpenCollective/opencollective-api/blob/master/default.env

**Comment by gabriellupu** [comment]
I personally subscribe to the idea that mixing `/.env` with `/config/*.json` sets of configurations is too much overhead. The set of configuration provided in this repository should be ideally enough to allow potential contributors to spin-up the system without any other dependencies / external "private" configs.

**Comment by asood123** [comment]
Agree with the goal. Anyone should be able to spin up the system. We are likely missing a variable or two

**Comment by asood123** [comment]
We already do this. The issues that you hit were more related to babel-node and switching from `require` to `import`, which messed up the order of environmental variables.
