### ISSUE TITLE
Staging server signup emails not arriving

### ISSUE THREAD

**Issue by Beanow** [opencollective/opencollective#2376]
As part of #2375 / #2235 the staging servers are suggested for testing vulnerabilities.

Creating (personal) accounts from https://staging.opencollective.com/create-account
I did not receive any emails to complete account creation with (I've checked spam).

Tested using two providers: gmail.com and soverin.net

Please verify they are sent and not being bounced.
(Related #1695)

**Comment by znarf** [comment]
@Beanow Can you try again?

**Comment by Beanow** [comment]
I received a signup email now :+1:
