### ISSUE TITLE
Make an embeddable widget 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#238]
Users are asking for a widget for their websites. They'd like a donate button, essentially the boxes.  
What we have right now, doesn't work like that.  

The options they have are 
- https://opencollective.com/ubie/widget (css needs improvement, the ones that appear as backers are the host and the core contributors, there's no donate button)
- The banner https://opencollective.com/ubie/banner.md (become a sponsor button that takes you to the public page, not specific donation button) See for example: apex.run/links
- specific urls: https://opencollective.com/ubie/donate/100 

This issue has been references before here: 
- https://github.com/OpenCollective/OpenCollective/issues/96

These are the websites of the collectives that want them: theplanetforusa.org and http://basicincome-europe.org/ubie/

**Comment by simonmichael** [comment]
I'd like this for http://hledger.org too. Examples there: the bountysource widget (indicates that the project uses bountysource, how many bounties are open and their total amount, and links to the bountysource project page where there's a recurring donation button), the gratipay widget (indicates gratipay usage and weekly donation amount, links to the gratipay project page etc.).

**Comment by simonmichael** [comment]
(I've replaced the gratipay widget with a more compact one, but you get the idea)

**Comment by xdamman** [comment]
@simonmichael you can use the badges that we have to show the number of backers/sponsors https://github.com/OpenCollective/OpenCollective/wiki/Github-banner

What specific other metric would you like to show? Annual budget maybe?

**Comment by simonmichael** [comment]
Thanks @xdamman. Yes annual budget would be good. Also some open collective-specific branding, eg the name/logo.

**Comment by simonmichael** [comment]
I have added these at http://hledger.org. Some notes re https://github.com/OpenCollective/OpenCollective/wiki/Github-banner:
- In step 1, there shouldn't be a colon before `yourcollective`
- the "How does it work" paragraph referring to steps 1-3 but adjacent to step 4, plus unfamiliar markdown markup, confused me for a minute
- I had to look up again which was which of backers and sponsors, and I suspect it won't be the last time
- Both show 0 (as do my README widgets), but I'm a backer. Is the collective owner not counted ?
- your 404 page is awesome

**Comment by simonmichael** [comment]
- In step 4, the #backers and #sponsors link targets are ineffective (as is #supporters, even though the Contribute button appears to use it)

**Comment by piamancini** [comment]
opencollective.com/widgets
