### ISSUE TITLE
Different settings in sponsor orgs vs host orgs

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2380]
Sponsor orgs don't need an expenses policy section. This should be "sponsorship policy" or not be there at all.

In advanced, there shouldn't be a setting for "host fee" or for enabling applications from Collectives.

There should be no associated terms of service.

Related to #2326 about terminology differences in the settings section.

**Comment by piamancini** [comment]
Where are you seeing it?

**Comment by piamancini** [comment]
nm, I see it.

**Comment by znarf** [comment]
I think this can tracked under https://github.com/opencollective/opencollective/issues/2665
