### ISSUE TITLE
Expenses page GraphQL Error (RequiredLegalDocuments)

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2383]
**Describe the bug**

https://opencollective.com/general-intellect/expenses shows a graphql error with the following logs:

```
[GraphQL error]: Message: Cannot read property 'getRequiredLegalDocuments' of null, Location: [object Object], Path: allExpenses,0,userTaxFormRequiredBeforePayment backend.js:1:11466
graphql error>>> GraphQL error: Cannot read property 'getRequiredLegalDocuments' of null
```

Reason is that we assume that host exists in https://github.com/opencollective/opencollective-api/blob/6ce710a8872f3ff78cc45ab8c0345789e6b0f332/server/lib/tax-forms.js#L38

**To Reproduce**
1. Go to https://opencollective.com/general-intellect/expenses
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/1556356/63929836-6e68c600-ca52-11e9-84c9-fa3925c60195.png)

**Comment by alanna** [comment]
Is this what's preventing the info banner from showing when someone hits the $600 threshold? I just tried to trigger that on staging to get a screenshot and got a GraphQL error and no banner.

![Screen Shot 2019-08-30 at 2 42 42 PM](https://user-images.githubusercontent.com/5498878/63989417-5ff2db00-cb34-11e9-92b6-2c9549a0efe5.png)

**Comment by Betree** [comment]
@alanna That may be. In the issue reported here it happens because the collective doesn't have a host. If the collective you've used doesn't have one either, then it's the same issue.

**Comment by alanna** [comment]
Hmmm it appears that https://staging.opencollective.com/newopensourcecollective does not have a host. So that could be it.

@Betree can you please confirm:
* Is the tax form banner being displayed as expected when users submit an expense to a Collective in Open Source Collective that puts them over the threshold?
* How can I get a screenshot of the banner for the docs?

If the banner isn't working for OSC Collectives I take it we'll need a seperate issue for that?

**Comment by Betree** [comment]
> Is the tax form banner being displayed as expected when users submit an expense to a Collective in Open Source Collective that puts them over the threshold?

I believe so, it works on staging and the `RequiredLegalDocuments` exists on prod so it should work.

> How can I get a screenshot of the banner for the docs?

To test the tax form feature I go to https://staging.opencollective.com/babel and submit a $5000 expense. Here is a screenshot of the page where the message appears:

![image](https://user-images.githubusercontent.com/1556356/64095365-e8ed5a80-cd5e-11e9-9ea7-acef81aceb9a.png)


> If the banner isn't working for OSC Collectives I take it we'll need a seperate issue for that?

Yes that would indeed be a separate issue, this one will be closed today by https://github.com/opencollective/opencollective-api/pull/2492
