### ISSUE TITLE
Small tweaks to the invoice/receipt selector on expenses

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2385]
Requesting two small improvements to the receipt/invoice selector on submit new expense.

![Screen Shot 2019-08-30 at 2 54 55 PM](https://user-images.githubusercontent.com/5498878/63989981-684c1580-cb36-11e9-9b4c-2530b004f185.png)

1. Add a ? help icon, and on hover show:

> Select 'receipt' to get paid back for a purchase already made. Select 'invoice' if you are charging for your time, getting paid in advance, or do not have a receipt.

2. Make the default selection blank, so the user has to proactively choose. If they don't choose the form can't be submitted. I am concerned that people will just leave it on the default option and that will mess up our tax requirement tracking.

**Comment by piamancini** [comment]
2. is a good point.

**Comment by anshumanv** [comment]
On it! 😄

**Comment by piamancini** [comment]
@anshumanv this bounty has not been tagged with a reward yet. Please hold off until we do. (cc @znarf)

**Comment by anshumanv** [comment]
Hey @piamancini it's alright either way, sent a fix here - https://github.com/opencollective/opencollective-frontend/pull/2587 doing some minor tweaks now as per the feedback. :)

**Comment by znarf** [comment]
@piamancini it's cool, we're in touch with @anshumanv. And more generally, it should not be a problem if contributors work on issues without bounties right?

**Comment by piamancini** [comment]
Oki! It was confusing because it has the bounty candidate label, I was trying to avoid someone working on it thinking there's a reward when that wasn't set. 

Thanks @anshumanv and sorry for the confusion!

**Comment by znarf** [comment]
🏆 This issue was completed by @anshumanv  

I retroactively added a $100 bounty on it. To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
