### ISSUE TITLE
Paypal donation flow bugs

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#239]
**Needs immediate attention**
- [x] `isActive` isn't being set in `subscription` in `paypalcallback`
- [x] Promise bug: `const subscriptionId = transaction.getSubscription().id` returns null because `getSubscriptions() is a promise`.
- [ ] Cancel flow doesn't work on Paypal (https://github.com/OpenCollective/OpenCollective/issues/240)

**Needs to be investigated**
- [ ] Where is the money from paypal going? Check host and see how paypal is linked to the host. And where do we take our cut?

**Longer term**
- [ ] Need to rewrite the flow with `Donation` -> `Transaction`, instead of other way around.

**Comment by asood123** [comment]
Immediate fixes: https://github.com/OpenCollective/opencollective-api/pull/596

**Comment by piamancini** [comment]
closing this as we are not supporting paypal donations anymore.
