### ISSUE TITLE
Host admins can set terminology on payment receipts

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2390]
<img width="859" alt="Screen Shot 2019-09-03 at 11 25 41 AM" src="https://user-images.githubusercontent.com/5498878/64135576-eada1b00-ce3d-11e9-8399-d3d081b04636.png">

Users report that the invoices saying "donation receipt" causes problems for them in terms of claiming financial contributions as legitimate business expenses and tax reporting. Not all financial contributions are donations - some are in exchange for services, marketing opportunities, etc. Donations implies giving to charity. I suggest we change the language to "payment receipt" to be more general and cover a broader set of use cases.

**Comment by alanna** [comment]
@xdamman is there a reason it says "donation receipt" now? Do some people need it to say that for their own tax reasons?

**Comment by znarf** [comment]
@alanna @xdamman  fyi, this is the code https://github.com/opencollective/opencollective-invoices/blob/c6afcba88a9e70bb285d48bcc6664bc3afde5878/src/pages/invoice.js#L242 cc @Betree

**Comment by xdamman** [comment]
Yes. My understanding is that in the US a 501cx can emit invoices or donation receipts interchangeably. 
Not in Europe. An invoice is specifically for a service or a product and is subject to VAT (which can be zero in some circumstances). You can also deduct that from your profit. A donation receipt is for donations and should appear in your books after profit and taxes (ie. you give a donation with your after tax money).

**Comment by alanna** [comment]
OK in that case I would like to go ahead with this change. Can this be actioned please @znarf ? Normally I'd say make it a bounty but we have a user waiting to be able to download invoices that will be valid in his country.

**Comment by Betree** [comment]
Let's not break things for Europe. We can check the country of the person being invoiced, if it's EU then keep the existing behavior, otherwise always show "Payment receipt". Would that work @xdamman @alanna?

**Comment by alanna** [comment]
This user is in Bulgaria. Not sure if that counts as Europe. I would much rather keep this simple and make it the same for everyone. @Betree who exactly would it break for if it said "payment receipt"?

**Comment by znarf** [comment]
@alanna Bulgaria is in the EU https://en.wikipedia.org/wiki/Member_state_of_the_European_Union

**Comment by Betree** [comment]
I was a misuse of language, I was indeed talking about the European Union so Bulgaria is concerned.

From @xdamman's comment above, my understanding is that some users need to have `Donation receipt` marked there for their accountability. If we just show `Payment receipt` for everyone I'm afraid we may break things for them.

> Not in Europe. An invoice is specifically for a service or a product and is subject to VAT (which can be zero in some circumstances). You can also deduct that from your profit. A donation receipt is for donations and should appear in your books after profit and taxes (ie. you give a donation with your after tax money).

**Comment by alanna** [comment]
We've had another user request for this same issue. "Donation" is causing issues where people need to justify use of funds for business purposes, grants etc.

**Comment by alanna** [comment]
@xdamman I still don't understand why using the phrase "payment receipt" would break this for Europe. If someone wants to account for a contribution as donation, can't they just do so, and use the fact that they gave money to a nonprofit for no exchange of goods or services to back up their claim if their country's tax agency requires it? Does the regulation say it *must* have the specific word "donation" on the receipt? 

I feel that using more neutral language will allow users to account for the payments in the best way for their own contexts. It's not fair to give priority to people who want "donation" over those who can't have it say "donation".

**Comment by xdamman** [comment]
Well of course people will have issues because they would want to deduct a donation as a business expense. Totally understandable. Who doesn’t want to pay less taxes?

Not speaking for the US where it’s much simpler in that regard, but in continental Europe, either you make a donation in which case it comes from your budget after taxes and there is no expectation of service directly back to you. Or you pay for a product/service in which case we need to add VAT if the collective is part of the host (only a few under OC Brussels fall into that category) or the collective needs to register for its own VAT if it’s considered as an unincorporated partnership (which is the default for the OC Europe host) and it is a regular economic activity of the collective.

We could put “payment receipt” on the pdf but the line item would still be “donation to...”. 
So not sure it’s helping here.

**Comment by edsilv** [comment]
Having "donation" on the receipts is a deal breaker for our US sponsor:

> Is it possible to have a receipt that does not refer to this as a donation?  I will need new receipts for every month I have contributed. 

> The problem with the receipts you are sending is that I cannot use my allocated grant funds to pay for this membership when my receipt defines it as a "donation"

**Comment by xdamman** [comment]
I was only talking for Europe. Should I understand that you are hosted on a European host with backers in the US?

Memberships are also VAT free in any association. 
So we could say payment receipt and line item could be “membership”. That works for me. But I can’t speak for how such receipt can be considered on the side of the company paying for it. This would have to be checked with a professional accountant in their country and it would be at their discretion.

**Comment by edsilv** [comment]
We are UK-based, but hosted by https://opencollective.com/opensource

**Comment by alanna** [comment]
I think we should make our receipts as generic as possible, because of the huge variety of regulations in different countries and for different contexts. 

It should be up to each contributor to account for the expenses properly for their own accounting, whether they are claiming it as a business expense or a donation, etc. Our receipt language should not try to determine that.

The language we use is "financial contribution" for exactly the reason that every Collective is different and other words carry too much baggage (such as donation, membership, etc).

So a decision needs to be made here. I volunteer as decision-maker and will gather information from accountants and users, etc.

@xdamman - does this have to be a global setting, or is it something that would be pretty easy to set at the host level?

**Comment by Betree** [comment]
@alanna If needed, there are three different ways we could make this customizable:
1. Automatically adapt sentence based on host's country
2. Automatically adapt sentence based on user/org's country
3. Add a field in settings so that host can customize the title for their invoices

1. and 2. would be really easy to implement (we already have countries setup) but require some specs to ensure we apply the correct wording.

**Comment by alanna** [comment]
I've requested advice from our accountant and I'll report back soon.

**Comment by alanna** [comment]
I got a reply from the accountant, and based on what they said here is my proposal:

1. Change the global settings to the most neutral possible language and just say "payment receipt" and "payment to [Collective]".
2. Add a completely free text field to host settings that allows fiscal host admins to define some text that appears on payment receipts in addition. 

Instead of trying to guess what different countries need, we leave this up to each fiscal host. For example, Open Collective Foundation could add "Donations to Open Collective Foundation 501(c)(3) are tax deductible in the United States - EIN ##-#####" and Open Collective Europe could add the language for their local regulations.

I will reach out to a couple fiscal host admins and ask fo feedback about this directly.

FYI here is how I explained my argument for neutral language to the accountant:

> If their country's tax agency asks them to justify how they are accounting for the payment, they can do so based on facts, like "we received XYZ business value" or "it's a donation as the entity is a nonprofit and we received no goods or services in return". I don't think it's up to us to try to serve all the conflicting and diverse needs and we should leave it to them.

**Comment by alanna** [comment]
Are there any objections to the proposal I explained above? If not, I'm going to recommend we proceed with it.

**Comment by Betree** [comment]
@alanna No objection, but I wonder: isn't the language specific to the invoiced organization rather than the host? How will we proceed if an european organization ask for specific language on an invoice they have from OSC?

**Comment by alanna** [comment]
A comment from a host admin:

> Strongly in favor of removing “donation” since that has a strict legal definition with the expectation of being claimable when submitting taxes. I use “contribution” as a helpful synonym for my community-based (but not legal charitable) project asks.

@Betree hosts can provide customised documentation for anyone on request. For example I'm creating an invoice for a contributor mentioned in this thread with specific language needed for their grant requirements. I'm doing this outside the system as a seperate document. That's why I want the system generated documents to have the most generic possible language, because every financial contributor has different needs and we can't serve them all.

**Comment by Betree** [comment]
Turns out we already have a `host.settings.invoiceTitle` field to customize invoices titles. It wasn't working, I re-activated it in https://github.com/opencollective/opencollective-invoices/pull/184 + https://github.com/opencollective/opencollective-api/pull/2960

All we'll need next will be a field to edit it in the frontend.

**Comment by alanna** [comment]
After discussing this at the last team meeting, we decided to create a simple feature so fiscal host admins can set the receipt language for their host.

Here are the specs:

* In host settings, add a section called "invoices & receipts"

(We will actually need this section soon for settings required in the new expense flow ([details here](https://github.com/opencollective/opencollective/issues/2394#issuecomment-557374499)).)

* Under that, have a section called "receipt settings" with these boxes
  * Title - default: *Payment Receipt*
  * Description - default: *Financial contribution to [Collective]

These correspond to the text circled here:
<img width="859" alt="64135576-eada1b00-ce3d-11e9-8399-d3d081b04636" src="https://user-images.githubusercontent.com/5498878/69770710-edef6800-11ee-11ea-9007-37dd7d0cda50.png">

@Betree would that be easy to implement? If we only have a field for the title and it's too much to add one for the description, I think we can hard-code the default language above and just let the title part be editable.

Question: can this settings section be made to only show up for hosts, not Collectives or Organizations?

**Comment by Betree** [comment]
To complete these specs, the field to edit for the invoice title is `settings.invoiceTitle`.

> would that be easy to implement? If we only have a field for the title and it's too much to add one for the description, I think we can hard-code the default language above and just let the title part be editable.

The title is a no brainer, we already have everything we need in the code to do it.

The description however has different implications, it's the string that gets generated when someones make an order. It is based on the tier, for example for tickets it's `Registration for {event.name}`. It can also be `Monthly donation to babel`. So for this one we have two options:
1. Either change the strings we generate per default to replace `Donation to ____` by `Financial contribution to ____`. We can eventually migrate all the past orders to use this new wording.
2. Or hard-code the language above in the invoice. Problem is that we loose the context if it's a ticket or a recurring contribution.

![image](https://user-images.githubusercontent.com/1556356/69792454-f633ad00-11c6-11ea-99ab-dfd30b55597a.png)


> Question: can this settings section be made to only show up for hosts, not Collectives or Organizations?

Yes

**Comment by alanna** [comment]
OK great. Let's go forward with the setting for the title.

For the description, it's problematic for it to say "donation" in many cases, and the generic terminology we've agreed on is "financial contribution". But I see what you mean about not losing the tier context.

So let's use "financial contribution to" as the default, and only vary it for events or to pull the custom language from the tier if the Collective has set it.

**Comment by Betree** [comment]
@alanna It's deployed
