### ISSUE TITLE
BackYourStack Homepage Copy Changes

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2395]
> We currently detect dependencies from JavaScript (NPM), PHP (Composer), .NET (Nuget), Go (dep) and Ruby (Gem). Want to see something else? See how to contribute.

Ruby (Gem) (...) To add new languages, please see how to contribute.

> You have two different options to perform an analysis of your code to know which Open Source Projects you are going to contribute to.

Use one of the two options below to scan your organization's code and find out which of your dependencies are seeking funding. You can now support them!

> Use your github link

Public Repositories

> Just copy and paste the URL of the repository that you want to scan and set a contribution.

add your organization's slug and we'll scan all public repositories under it. 

> Upload your own file

_option 1:_ Private repositories or repositories not on Github. 
_option 2:_ Upload a dependency file. 

> If you want to analyze non-public repositories, sign in with your GitHub account or simply upload dependency files. At the moment, we do support composer.json, *.csproj, packages.config, Gopkg.lock and Gemfile.lock.

(...) or simply upload your dependency file. At the moment we support (...)

> The uploaded files will not be shared with anyone and will be deleted when your session expire. 

The uploaded files will not be shared and we will store them only with your explicit consent.

**Comment by znarf** [comment]
- "Public Repositories" is misleading -> "Use a GitHub profile" ?
- Option 2 -> "Upload dependency files" ?

**Comment by piamancini** [comment]
> "Use a GitHub profile" 
ok - you don't think it'll make user think they must login? I guess having the url immediately afterwards makes it clear. 

> "Upload dependency files"
Ah, I always thought it was one file.
