### ISSUE TITLE
Archived Collectives should not appear in search results

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2397]
This Collective is archived but still turning up in search results: https://opencollective.com/symfony-diversity-speaker-mentoring

I assume that means others are too. They should not be appearing in search.

**Comment by znarf** [comment]
Our search index is managed on Algolia. The script used to populate the index is https://github.com/opencollective/opencollective-api/blob/master/cron/daily/populate_search_index.js

**Comment by znarf** [comment]
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

**Comment by EugeneHlushko** [comment]
Hi @znarf 
Had time to kick in

**Comment by znarf** [comment]
Thank you @EugeneHlushko ! It's merged.

To claim the bounty, you can:

a) submit an invoice to https://opencollective.com/engineering
b) or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Comment by EugeneHlushko** [comment]
Hi, Thanks man! Very overwhelmed to finish the other one :(
