### ISSUE TITLE
Unexpected error when I try to view our open collective page

### ISSUE THREAD

**Issue by MaryOJob** [opencollective/opencollective#2399]
# Describe the bug

<img width="1276" alt="Screen Shot 2019-09-05 at 2 25 21 AM" src="https://user-images.githubusercontent.com/25005583/64304652-8ecdde80-cf84-11e9-9340-b9e1720f9d02.png">

I got an unexpected error on https://opencollective.com/do_action-ijebu while I was trying to view our collective page here - https://opencollective.com/do_action-ijebu

# To Reproduce

1. Go to https://opencollective.com/do_action-ijebu
2. See error

# Device
- OS: MacIntel
- Browser: `5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36`

# Technical details

```

```

**Comment by znarf** [comment]
@MaryOJob the origin of the problem was that an update was created with an account you have now deleted. I attached your new account to the update. It should work now.

**Comment by MaryOJob** [comment]
Thanks @znarf for the assist. I appreciate.
