### ISSUE TITLE
Fixes on new public page 

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#24]
- [x] login / logout is not working [https://cldup.com/eV_5SaBaZM.png](url) & [https://cldup.com/r7xipqu0N9.png](url) 
- [x] the tier name is pulled from the 'name' and not the 'title'
- [x] force min/max height for tier 'button'
- [x] make "we are on a mission to" bigger 
- [x] add "..." to the beginning of the mission statement & remove final "."
- [x] do we still need short description & long description now that we have mission statement? seems redundant. 
- [x] when a user changes twitter avatar the avatar in public page keeps loading see https://cldup.com/HvFHyzJu7Y.png
- [x] force heights in donation boxes see: https://cldup.com/hv21KSO0oi.png
- [x] a "see all donations" button seems to be missing. Maybe all buttons in this area should be the same size? https://cldup.com/GxUKGYPmhy.png
- [x] currency in presets amount is Euro currency in other is USD https://cldup.com/8CSE9CEoQd.png
- [x] fix centered text & bullet points https://cldup.com/JOCzBk8S_2.png
- [x] the images that are pulled from the db are not forced to fit the designated space in the public page so some of them look cut off in. See for example: https://opencollective.com/perthindymedia#why-join

**Comment by PeterDCarter** [comment]
On it.

**Comment by piamancini** [comment]
Feedback I collected: 
It looks like an open collective landing not the page from a collective. 
The collective’s logo should be visible from the beginning.
The cards are great 
Expenses/Activity feed is great
It's be nice if the 'Be a part of it' Button would scroll down to donation instead of jumping straight to it.
The "mission to" doesn't work at that size, you start reading the phrase and since it's hard to see it's a page from a collective, the phrase makes no sense.

**Comment by cuiki** [comment]
Hi Pia, can you expand on this:
› _It looks like an open collective landing not the page from a collective. _ (Is it the whole page or the hero header makes it look like that?)
› _The "mission to" doesn't work at that size, you start reading the phrase and since it's hard to see it's a page from a collective, the phrase makes no sense._ (You mean the text size or is it mainly a problem linked to the issue I list above?)

**Comment by piamancini** [comment]
@cuiki 
the hero header only. The first thing you see is a phrase that it's hard to understand that it is a mission statement from a collective. The phrase above that mentions the collective and 'is in a mission to..' is too small. That plus the logo of OpenCollective top left makes it look like an OC page. 
I think the fix is twofold, a) making the link to the collective and the 'is in a mission to' way bigger so you see it in relation to the actual mission statement and b) placing the collective's logo on the hero header.

**Comment by carlosascari** [comment]
I will take:
- force heights in donation boxes section...
-  a "see all donations" button seems to be missing. 
- force min/max height for tier 'button'
- make "we are on a mission to" bigger
- add "..." to the beginning of the mission statement & remove final "."
-  the 'Be a part of it' Button would scroll down to donation instead of jumping straight to it.

**Comment by piamancini** [comment]
@carlosascari @cuiki I've been adding some more issues. Please refer to the original issue in the thread. Let us know which ones you are taking on please and tick them off. thanks!

**Comment by carlosascari** [comment]
@piamancini I've made a PR with the first issue I mention about the donation box height. As for the second issue, the see all donations button appears after there are 3 or more contributions, see:

https://github.com/OpenCollective/website/blob/master/frontend/src/components/public_group/PublicGroupDonations.js#L11 and Line 35

**Comment by cuiki** [comment]
I can't tick them off because I am not a collaborator.

**Comment by piamancini** [comment]
@carlosascari great. Now what I'd like to prioritize is a) the heroheader that I think @cuiki is working on b) making sure the image container for the #whyjoin forces images to fit or we need to make it bigger. See how most of the image are, they don't fit that space and c) the text centered.

**Comment by piamancini** [comment]
hmm dunno how to fix that. I'll ask @asood123

P.
piamancini.com
t: @piamancini
s: piamancini
OpenCollective <https://opencollective.com>

**Comment by cuiki** [comment]
Thank you. Let us know.

**Comment by cuiki** [comment]
@piamancini can you expand a bit on the priorities you said to @carlosascari ? Point A is clear but I'm not sure what you mean with point B. Maybe could add a few screenshots as examples? In point C do you mean the long description?

**Comment by piamancini** [comment]
sure
b) 
this image looked better in previous design https://cldup.com/-ehBBNNa52.png
this image is cut in the middle: https://opencollective.com/perthindymedia#why-join
this image is getting the borders cut off https://opencollective.com/yeoman#why-join
Idem: https://opencollective.com/angular-fullstack#why-join
I think that the code is not forcing the images to fit the container, instead is just cropping the size of the container. 
c) Yes, the #whoweare see for example how these descriptions look in a large viewport: 
https://opencollective.com/wwcodesf#who-we-are
https://opencollective.com/railsgirlsatl#who-we-are

**Comment by cuiki** [comment]
Thanks @piamancini . We got it. :)

**Comment by piamancini** [comment]
rockstar

**Comment by carlosascari** [comment]
@piamancini from the priorities you asked B & C are done. I will continue on the issues I took, let me know if you have other priorities in mind.

**Comment by piamancini** [comment]
@carlosascari great, I'll gave a look with @asood123 today and push the changes. I'll circle back to you once I see them.

**Comment by piamancini** [comment]
@carlosascari The forcing a height of the buttons is creating this issue: https://cldup.com/ODFPtUdcql.png pulled from https://opencollective.com/sf-data-science/

**Comment by carlosascari** [comment]
@piamancini done: https://github.com/OpenCollective/website/pull/150
