### ISSUE TITLE
Unable to sign in via email

### ISSUE THREAD

**Issue by staltz** [opencollective/opencollective#2401]
**Describe the bug**

I keep waiting for the magic link to arrive, but it doesn't, not even to my spam folder. I am sure it has worked in the past. This is rather critical issue in my opinion, because I can't send newsletters/updates neither invoices like this.

**To Reproduce**
1. Go to OpenCollective.com
2. Click on Sign In
3. Input my email address `andre@staltz.com`
4. I don't receive any email from OpenCollective, not even in the spam folder

**Expected behavior**

My email inbox should show the email from OpenCollective with a magic link, at latest in a few hours.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 18.04.2
 - Browser: either Firefox 68 or Chrome 76

**Comment by Betree** [comment]
Hi @staltz, I just checked and your provider rejects our emails:

![image](https://user-images.githubusercontent.com/1556356/64326297-03773c00-cfca-11e9-8375-d17181f9aa50.png)

Can you check if Open Collective emails are not blacklisted on your side? Are you using a third party email provider or are you self hosting?

**Comment by znarf** [comment]
Similar to https://github.com/opencollective/opencollective/issues/2302

**Comment by staltz** [comment]
@Betree I use fastmail.com and I'm able to receive other OpenCollective emails such the "hiring" email just sent some hours ago:

![Screenshot from 2019-09-05 11-50-57](https://user-images.githubusercontent.com/90512/64326914-79cc6c00-cfd3-11e9-8963-55a8d0e3c70d.png)

If OpenCollective had a password login, I'd use that instead. I'll contact Fastmail now, too.

**Comment by znarf** [comment]
It's on Mailgun side, somehow you're in a list of people who marked Open Collective emails are spam (don't know how that happened) and the email is not sent for that reason. The newsletter is sent through another provider.

**Comment by znarf** [comment]
Removed you from that list, it should be better now.

**Comment by staltz** [comment]
Thanks for the info.

I managed to fix this (or maybe it was you guys who also did an action in the past few minutes), by adjusting my email provider's spam settings to be more loose, and I'm now logged in.

Thanks for the very quick reaction!
