### ISSUE TITLE
NCP: Hero background bug on IE11

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2404]
**Root cause**
CSS masks are not supported on IE11.

**Expected behavior**
Background should be white and no image should be displayed if CSS masks are not supported.

**Preview**
Test ID: TES1009631001567667576236858
Operating System: Windows 10
Browser: IE 11
Resolution: 1024x768

![](https://s3.amazonaws.com/issues-screenshots/Q0YJrb8x8fyP6has0MWyCizBoBRsbgHaIxaxa6Zk1567672894.png)

**Comment by piamancini** [comment]
@Betree that arrow man... you ok? 🤣

**Comment by Betree** [comment]
@piamancini Hahaha I was hopping that nobody would see it :smile: I swear I'm not drunk-coding! I was using https://www.lambdatest.com/ which is great for cross-browser testing but their UX to edit the screenshot can definitely be improved :wink:

**Comment by Betree** [comment]
The website is mostly not functional on IE11, and we don't want to invest in fixing it at the moment.
