### ISSUE TITLE
Language switcher: "Niederländisch" should be  "Nederlands"

### ISSUE THREAD

**Issue by TheDutchCoder** [opencollective/opencollective#2407]
**Describe the bug**
The language switcher in the footer of the front-end shows "Niederländisch" to switch to Dutch, but that's the German word. It should be "Nederlands".

**To Reproduce**
1. Go to the footer
2. Confirm "Niederländisch" is shown

**Expected behavior**
It should display "Nederlands"

**Screenshots**
![image](https://user-images.githubusercontent.com/1668207/64369894-3f6ec900-cfeb-11e9-9050-3dee80350718.png)

**Comment by znarf** [comment]
@TheDutchCoder absolutely sorry about that, will be fixed promptly

**Comment by TheDutchCoder** [comment]
No worries, it's a detail and it struck me as funny :)

**Comment by znarf** [comment]
Thank you, fixed!
