### ISSUE TITLE
Development deployment configuration on remote server

### ISSUE THREAD

**Issue by bkmgit** [opencollective/opencollective#2409]
**Describe the bug**
When deploying on a Remote server using Fedora 30, the default configuration in  opencollective-frontend/env.js with PORT: 3000 and WEBSITE_URL: 'http://localhost:3000', does not work well

**To Reproduce**
1. Setup a fresh virtual machine with Fedora 30 with at least 2 Gb RAM
2. sudo dnf install -y git npm
3. git clone https://github.com/opencollective/opencollective-frontend
4. cd opencollective-frontend
5. npm install
6. firewall-cmd --permanent --add-service=http
7. firewall-cmd --zone=public --add-port=3000/tcp --permanent
8. firewall-cmd --reload
9. npm run dev

**Expected behavior**
Would expect to view website

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Browsers: Web, Firefox
 - Versions: 3.3.24, Quantum 69.0

**Additional context**
Would be good to update README or indicate alternate configuration for testing on remote servers. For example indicate possibility of using npm run dev -- -p <your port here> as indicated at https://nextjs.org/docs

**Comment by znarf** [comment]
I don't see how changing `WEBSITE_URL` would fix the situation, it's barely used in the codebase. I also don't see why `0.0.0.0` or `localhost`, if you're on a remote server, you should use the public IP address right? 

Does the production build works better? 'NODE_ENV=production npm run build` then 'NODE_ENV=production npm run start`

**Comment by bkmgit** [comment]
Thanks for pointer on public IP. Will check production settings.

**Comment by znarf** [comment]
Closing as I don't see any immediate actionable.
