### ISSUE TITLE
fix counter on widget

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#241]
The comma is in the wrong place.

<img width="1261" alt="screen shot 2016-09-16 at 10 02 44 am" src="https://cloud.githubusercontent.com/assets/3671070/18594432/dedc90ba-7bf4-11e6-917a-8e5ae1d5a008.png">

They have $595 see https://opencollective.com/hoodie

**Comment by asood123** [comment]
fixed.
