### ISSUE TITLE
Unpredictable behavior when hosts change their Stripe account

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2411]
In https://github.com/opencollective/opencollective-api/blob/c279192f2f592d05316657ae985df5bfa7651591/server/models/Collective.js#L2089, we retrieve host's Stripe account by returning the first `ConnectedAccount` available.

This creates an issue where when changing your Stripe account, as the old one is not marked as deleted, where the actual account that will be used cannot be predicted.

Marking this issue as important cause the implications of using an old Stripe account can be pretty bad.

# Proposed fix

- Add a `order` clause for `createdAt`on `getHostStripeAccount` to ensure we always get the latest account
- (optional) When you change host stripe's account, mark the old one as deleted

**Comment by jeffin143** [comment]
@Betree if you don't mind , can I take up this issue ?

**Comment by Betree** [comment]
Resolve by @jeffin143 in https://github.com/opencollective/opencollective-api/pull/2706 :rocket:
