### ISSUE TITLE
Project: Homepage redesign

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2417]
![Wireframe Home page open collective B](https://user-images.githubusercontent.com/74358/64712853-3df64280-d4bc-11e9-93aa-cc83ebd444f6.png)

## Feedback so far

- Work on About + open source sections, maybe make it less prominent?
- Need a link to documentation, to blog, to our github repo (maybe use the icons now within About section for that)
- Need for a /transparency page
- Add another call to action to create a collective after “They are using Open Collective” 
Make it visually a different section after that.
- Spend money in the header instead of disburse (more correct but less common in international English)

I will close comments by the end of this week and share a new wireframe for review.

**Comment by alanna** [comment]
Please let me know when you're ready for copy feedback

**Comment by xdamman** [comment]
You can already make copy suggestions in [this google doc](https://docs.google.com/document/d/1FkiGvMVuamExwC7WXg_PcohLtVDdHcHktEV2N7qEQM8).

**Comment by piamancini** [comment]
Also feedback: 
- include the numbers in the transparency page not at the bottom. I think there's a general feeling that they are nos very accurate.

**Comment by Memo-Es** [comment]
### Latest illustration update

These are the drafts applied to the current homepage to solve the conceptual links to the messaging and interface design. The illustrations that are approved will be taken to production.
@xdamman @piamancini 

The main illustration (Make your community sustainable) is still on the conceptualization. Bellow inside the table it's shown the progress around this concept ↓

![Homepage-illustrations](https://user-images.githubusercontent.com/49539954/68702369-53382d80-054e-11ea-9c65-42232922a812.jpg)

Concept | Option 1 | Option 2 | Option 3
-- | -- | -- | --
Make your community sustainable | ![Community](https://user-images.githubusercontent.com/49539954/68702633-c6da3a80-054e-11ea-84db-049ebcb1c09e.JPG)  | ![gif2](https://user-images.githubusercontent.com/49539954/68704125-6d273f80-0551-11ea-8d46-ca9cbb3d85ba.gif)  |  
Collect money | ![Collect money 3](https://user-images.githubusercontent.com/49539954/68702628-c6da3a80-054e-11ea-9006-38f9357748bc.JPG)   | ![g1](https://user-images.githubusercontent.com/49539954/68704383-d60eb780-0551-11ea-9537-13521d7ac553.gif)  |  ![Collect_money_2](https://user-images.githubusercontent.com/49539954/68702632-c6da3a80-054e-11ea-96b3-db01950f2cc3.JPG)
Spend money | ![Spend money](https://user-images.githubusercontent.com/49539954/68702638-c772d100-054e-11ea-926c-4de5306f5b19.JPG)  |   |  
Manage money | ![Manage money](https://user-images.githubusercontent.com/49539954/68702635-c772d100-054e-11ea-80d9-6e8d7787fbe9.JPG)  |   |  
Open Collective for fiscal sponsors |   |   |  
They are using Open Collective (Discovery) |   | ![Discovery](https://user-images.githubusercontent.com/49539954/68702631-c6da3a80-054e-11ea-9128-823ad8198728.JPG)  |  
We are open source (Open source & open data) |  |   |  

*Note: It is sufficient if we only have one option for each concept if it's solid enough, the other options can be used in other parts of the platform.

**Comment by alanna** [comment]
Looking good! Please let me know when the time is right to do copy edits and the best way to do them.

**Comment by xdamman** [comment]
Make your community sustainable: I like both options. I like the animation. I'd just have colors that pop more. Make it feel more like (citizen) spring than autumn.

I like the option 2 for collect money because it's about collecting money *together*.

For spending money I don't understand the image. It feels like someone alone on his computer. That doesn't convey a sense of community. It is also about spending money *together*.

For manage money, I'd love to see more than one area so that the person arranges the stars between different places (collectives / circles / working groups). Here again, conveying a sense of *together* would be good.

Discovery: looks great, I'd just here again show multiple collectives, 2 or 3 of those "stains" with stars.

**Comment by piamancini** [comment]
> Make your community sustainable: I like both options. I like the animation. I'd just have colors that pop more. Make it feel more like (citizen) spring than autumn

@xdamman yes totally, these are black and white pen and paper examples to see if they fit. color scheme will be bright. You can see some color examples [here](https://paper.dropbox.com/doc/OC-Design-OpenCollective.com-New-Illustrations--Aohu6jEMiyI7avq7xZtQfePGAg-oDgnu9iv1wv1iUMtoRTuq#:uid=924607847867734416272869&h2=Color-usage-proposal)

> I like the option 2 for collect money because it's about collecting money together. 

+1

**Comment by alanna** [comment]
Where is the 2 minute animated explainer video going to fit in on the front page?

https://www.youtube.com/watch?v=IBU5fSILAe8

**Comment by Memo-Es** [comment]
### Illustrations update

Concept | Option 1 | Option 2 | Option 3
-- | -- | -- | --
Make your community sustainable | **Main illustration in WIP**  |   |  
Collect money | ![Collect money 3](https://user-images.githubusercontent.com/49539954/68702628-c6da3a80-054e-11ea-9006-38f9357748bc.JPG)   | ![g1](https://user-images.githubusercontent.com/49539954/68704383-d60eb780-0551-11ea-9537-13521d7ac553.gif) ✅Green light for production (considering the color usage proposal)  |  ![Collect_money_2](https://user-images.githubusercontent.com/49539954/68702632-c6da3a80-054e-11ea-96b3-db01950f2cc3.JPG)
Spend money | ![Spend money](https://user-images.githubusercontent.com/49539954/68702638-c772d100-054e-11ea-926c-4de5306f5b19.JPG)  | ![Spend-money](https://user-images.githubusercontent.com/49539954/69195772-3ec9d700-0af2-11ea-966f-736895abccde.png)  |  
Manage money | ![Manage money](https://user-images.githubusercontent.com/49539954/68702635-c772d100-054e-11ea-80d9-6e8d7787fbe9.JPG)  |   |  
Open Collective for fiscal sponsors | **Conceptualization in progress**  |   |  
They are using Open Collective (Discovery) | ![Discovery](https://user-images.githubusercontent.com/49539954/68702631-c6da3a80-054e-11ea-9128-823ad8198728.JPG) ✅Green light for production (considering the color usage proposal and adding 1 or more stains with stars)  |   |  
We are open source (Open source & open data) |![os2](https://user-images.githubusercontent.com/49539954/69195833-6a4cc180-0af2-11ea-9e9b-a95725b879dd.png)  | ![os](https://user-images.githubusercontent.com/49539954/69195843-720c6600-0af2-11ea-8abb-e4165fdb743f.jpg)  |  

> To manage money, I'd love to see more than one area so that the person arranges the stars between different places (collectives/circles/working groups). Here again, conveying a sense of together would be good.

- We are thinking of a sort of composition using these three concepts that convey the sense of community more compellingly. We are basing this approach on the "Collect money" illustration. 

<img width="1415" alt="What-can-you-do-on-open-collective" src="https://user-images.githubusercontent.com/49539954/69196958-987fd080-0af5-11ea-9080-823b462d1253.png">

> Where is the 2 minute animated explainer video going to fit in on the front page?

@alanna 

- This video has excellent messaging. We would like to have input from @xdamman and @piamancini if it makes sense to update it with the new illustrations now. If we do this, it would require an illustration/animation side-project... 
I vote for updating the explainer video and launch the home without it while it's ready.

**Comment by Betree** [comment]
This is really cool!

Just a short feedback about the `We are open source` illustration: I think the option (2) is better because the first one assumes that you know the "official" open source logo, while the second one makes it clear what the values of open-source are without knowledge pre-requisites.

**Comment by xdamman** [comment]
The illustration for spending money is still confusing to me.
I don't think it should have a computer.

People spend money on things and on people, to shops, etc. 
I'd make it more "real" rather than "online".

For the video, what about having a link in the cover below or above the "create collective": 
"▶️ watch the explainer video" ?

**Comment by Memo-Es** [comment]
### Update
**Note:** Color usage is not final*

![Homepage](https://user-images.githubusercontent.com/49539954/69667275-4c7fdf00-1053-11ea-9fb4-a1241319f36d.jpg)

Concept | Illustration | Concept | Illustration | 
-- | -- | -- | -- | 
**Make your community sustainable** | ![collectivestars](https://user-images.githubusercontent.com/49539954/69669246-1ba1a900-1057-11ea-8f0f-cd88c6f7f271.png) | **Collect money** | ![collect copy](https://user-images.githubusercontent.com/49539954/69672870-9a4e1480-105e-11ea-8922-b2e2c9d26d9c.png)
**Spend money** | ![spend copy](https://user-images.githubusercontent.com/49539954/69670694-13973880-105a-11ea-85c2-02cb57888ce6.png) | **Manage money** | ![manage copy](https://user-images.githubusercontent.com/49539954/69671044-e008de00-105a-11ea-910d-eb72b195065d.png)
**They are using Open Collective (Discovery)** | ![Discovery](https://user-images.githubusercontent.com/49539954/69671220-35dd8600-105b-11ea-9c02-637ed1e8855c.png) | **OC for fiscal sponsors** |  ![starpatternhands](https://user-images.githubusercontent.com/49539954/69671260-45f56580-105b-11ea-8478-9e7fea71a024.png)
**We are open source** | ![os](https://user-images.githubusercontent.com/49539954/69671310-61f90700-105b-11ea-8f13-b328f707b1a7.jpg) | **Join us** | ![Community](https://user-images.githubusercontent.com/49539954/69671334-6e7d5f80-105b-11ea-92ec-4459ca7aa8fc.png)

**Comment by piamancini** [comment]
This is looking great! 
The font, lines, etc of the homepage should be more in sync with the feel of the illus. (I am assuming there hasn't been any figma design done yet)

**Comment by xdamman** [comment]
Great to see the progress.
The first illustration looks amazing.

For the rest I think there are too many illustrations. We are overdoing it. Less is more.
I'd remove the one for "They are using Open Collective" and the one for "Fiscal Hosts"

The illustration for managing money comes across as I'm keeping all that money for me.
I'd love to see that more about moving the stars between different "buckets" and also with more than one person because we are managing money together.

The colors for the join us don't work. It should blend better with the design (or vice versa)

**Comment by Memo-Es** [comment]
I agree that we could remove "They are using Open Collective" (Even though it was partially approved) 

> Discovery: looks great, I'd just here again show multiple collectives, 2 or 3 of those "stains" with stars.

Anyway, we could use it elsewhere on the platform...

As for the colors, these are preliminary versions as I noted in the last comment. 
The final design version will come after Karim is done with the "Create collective flow", we are prioritizing it for now.

**Comment by piamancini** [comment]
> I'd love to see that more about moving the stars between different "buckets" and also with more than one person because we are managing money together.

@Memo-Es the one with the stars un the different jugs can work for this. I liked that one

**Comment by Memo-Es** [comment]
### Update
**Note:** These illustrations are preliminary, cropping and color usage will likely change during final production*

@xdamman @alanna @piamancini 

![Homepage](https://user-images.githubusercontent.com/49539954/70657647-d027f700-1c21-11ea-9cbe-571c54da61e5.jpg)

**Comment by nonsodaniel** [comment]
@znarf I would like to work on this issue

**Comment by alanna** [comment]
@Memo-Es what's the best way for me to suggest detailed changes to the text? Not changing the design at all just phrasing.

**Comment by Betree** [comment]
@Memo-Es where is the `Subscribe` button - where do I click to submit my email?

![image](https://user-images.githubusercontent.com/1556356/71883616-15fbb080-3137-11ea-9b32-7e7163a55373.png)

**Comment by piamancini** [comment]
As per @xdamman: The "Learn more" links under collect, disburse and manage should not be there. 
@flickz we can remove them.

**Comment by xdamman** [comment]
@alanna @Memo-Es see this google doc for editing the copy: https://docs.google.com/document/d/1i1eP5PLfM2Tshp6Oiqnpt8lXAazJ-twFj8iQQg2SYWI/edit?usp=sharing

@flickz a few comments on the latest version that you've implemented and that I could see on https://opencollective-frontend-miltkcgtrf.now.sh/v2 
- there is a css issue with safari for the background of the boxes for the carousel:
![](https://d.pr/free/i/hDOZiQ+)
- the spacing/padding is off for the "learn more" section: ![](https://d.pr/free/i/yXznp5+) (need more space below the description of the section, need more space between each column and the icons. Maybe @Memo-Es can provide more accurate values for those things
- in the mobile view, the main title "make your community sustainable" should be centered
- any chance we could swipe the carousel on mobile with the content following my finger (expected behavior on mobile)

**Comment by znarf** [comment]
>  "make your community sustainable" should be centered

@xdamman If I check the design, it's not, so it's a design issue. @Memo-Es can you check?

**Comment by alanna** [comment]
I've edited the [google doc with the copy here](https://docs.google.com/document/d/1i1eP5PLfM2Tshp6Oiqnpt8lXAazJ-twFj8iQQg2SYWI/edit#heading=h.2wctg5rx4t4h). It would be great to see these changes incorporated into the designs so we can see how it will look.

One thing missing from this page: [the explainer video](https://www.youtube.com/watch?v=IBU5fSILAe8)! I think it should go below the hero section, above "What can you do on Open Collective?". It's a great video and people have come to expect one.

**Comment by piamancini** [comment]
@Memo-Es can you add latest approved design and copy here?

**Comment by Memo-Es** [comment]
### Latest design update
@piamancini @xdamman 
![fixed](https://user-images.githubusercontent.com/49539954/72291027-194ddb00-3614-11ea-8c2e-f5971ba27f06.jpg)


- **[Features section prototype:](https://www.figma.com/proto/bOkmWlsYxP9qA15z85lzgHQ2/OC.COM-01-Homepage?node-id=1485%3A958&viewport=409%2C923%2C0.3412298262119293&scaling=min-zoom)**
- **[Google doc with the copy](https://docs.google.com/document/d/1i1eP5PLfM2Tshp6Oiqnpt8lXAazJ-twFj8iQQg2SYWI/edit#heading=h.2wctg5rx4t4h)**

**Comment by alanna** [comment]
Looks great!

Just a few copy changes....
* Watch explanatory video > Watch: 2 min explainer video
* Discover more **C**ollectives, Create a **C**ollective  (capital C)
* Not only does our platform help you be transparent > Transparency is key to our product *and* our company
* Subscribe **to** our newsletter

**Comment by Betree** [comment]
@Memo-Es What's the behavior when clicking on "Watch video", does it opens a modal?

**Comment by Memo-Es** [comment]
@Betree Yes, a modal window with the video

**Comment by Betree** [comment]
@Memo-Es can you provide a design for the different states of this button? It currently does not react to hover/active...etc Or should we update the existing `dark` styles? (see https://styleguide.opencollective.com/#!/StyledButton/7)

![Peek 23-01-2020 14-58](https://user-images.githubusercontent.com/1556356/72990617-c54fad00-3df0-11ea-8d65-cafa9fab9ecc.gif)

**Comment by BenJam** [comment]
Very excited to see this https://github.com/opencollective/opencollective/issues/2417#issuecomment-573865363 and I love the new art style 💃

**Comment by Memo-Es** [comment]
This version is live here https://opencollective.com/
So I hereby proceed to close this issue 🎉

There is a new small project called "Homepage polish" for other small fixes.

**Comment by Betree** [comment]
:tada:
