### ISSUE TITLE
New collective page: edit default sections

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2418]
If there is no tier, we shouldn't show the default "donate tier".

compare https://opencollective.com/xr-ist with https://opencollective.com/xr-ist/v2

(ideally, we should be able to customize the default "donate tier" in /edit tiers, but for now, it feels like not showing when there is no tiers defined could be a quick fix)

Reason it's important: some collectives might not be ready yet to receive donations.

**Comment by xdamman** [comment]
> I don't see it live in Chrome/Firefox, but I've seen this when taking screenshots (because of the way browsers take screenshot). Is that appearing live on your mobile?

Oh interesting. Indeed. That’s funny.

**Comment by Betree** [comment]
Opened a new issue about editing sections https://github.com/opencollective/opencollective/issues/2424
