### ISSUE TITLE
Show Individuals' Contributions instead of Organization

### ISSUE THREAD

**Issue by writingpoli** [opencollective/opencollective#2421]
When I added donations we'd received before we joined Open Collective, the platform forced me to include an "organization" along with the name of the contributor. So, I wrote "via facebook fundraiser" for one and then "n/a" for the rest (assuming we'd have this chat and sort it out later). But the site only shows the "organizations" that contributed rather than the individuals. Can we make that field not required?

I want to show the individuals who donated. Can we make that optional?

Inputting offline contributions you receive an error requiring an organization input.
![image](https://user-images.githubusercontent.com/3883763/64911413-2cdd4980-d6e7-11e9-8a5b-7602717d1d1f.png)

Then you end up with

![image](https://user-images.githubusercontent.com/3883763/64911439-59916100-d6e7-11e9-8cf1-a4507d378a77.png)
 
What am I missing?

**Comment by piamancini** [comment]
@znarf fyi: I fixed this from the database level but we need to tackle the underlying issue.

**Comment by znarf** [comment]
If it's fixed, then let's close. To fix the underlying issue, let's create a separate bug or enhancement issue.
