### ISSUE TITLE
Add a GitHub Sponsor button to this repository

### ISSUE THREAD

**Issue by XVilka** [opencollective/opencollective#2423]
I wonder why you didn't enable it yet :)

- https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository (it even has OpenCollective integration after all)
- apply for GitHub matching sponsorship https://github.com/sponsors

**Comment by znarf** [comment]
@XVilka GitHub matching sponsorship is unfortunately only available when fundraising directly with GitHub.

**Comment by gusaus** [comment]
Wouldn't it make sense to link out to whatever collective is associated with the OSS project? https://github.com/opencollective/opencollective

I think that would be a great way to encourage financial incentives such as  bounties https://github.com/opencollective/opencollective/issues/2420

**Comment by znarf** [comment]
Done!

**Comment by gusaus** [comment]
Seems like the GitHub Sponsor button should link to a collective that references bounties and campaigns https://github.com/opencollective/opencollective/issues/2420 focusing on sustaining the project. 

Is https://opencollective.com/opencollective the collective associated with the OSS project? https://github.com/opencollective/opencollective

**Comment by znarf** [comment]
@gusaus yes, the decision from the team is to lead donations to this collective
