### ISSUE TITLE
New collective page: edit sections

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2424]
## User story 
As a collective admin, I can re-order / remove / add sections from my collective page.

## Best solution for this problem
The base feature is already implemented. Today collective admins need to contact us, then we set a value in `settings.collectivePage.sections`. It's an array that should contain all the sections that we want to display for the collective, in the order that we want to display them. For section names, check https://github.com/opencollective/opencollective-frontend/blob/7a19d5e85e765c3f333fadc7888b6fc2ad84c501/components/collective-page/_constants.js#L19

Ex:

```es6
settings = {
  "collectivePage": {
    "sections": ["about", "updates"]
  }
}
```

==> **What we need now is a way to edit them, with a proper UI/UX.**.

## Design 

https://www.figma.com/file/GF1gQ7fWNfaOAFNwuLeAUl/%5BOC.com%5D-Hotfix-Fixes?node-id=1038%3A454

![image](https://user-images.githubusercontent.com/1556356/76774847-c07df880-67a4-11ea-93c3-759af3ccd363.png)

## Metrics 
How many collectives change their default sections.

## Documentation 
We should add animated GIFs demonstrating how to edit sections when this is done.

**Comment by Betree** [comment]
@lindatalu I'm re-opening, we need an input from design on this issue but it's also an engineering task and we'll loose track of it if we close it.

**Comment by raulgrafico** [comment]
Link to the Figma file:
https://www.figma.com/file/GF1gQ7fWNfaOAFNwuLeAUl/OC.com-Hotfix-Fixes?node-id=1038%3A454
