### ISSUE TITLE
Update contribute page with NCP's design

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2425]
:art: Design: https://www.figma.com/file/e71tBo0Sr8J7R5n6iMkqI42d/OC.COM-04-%2F-Collectives-%E2%86%92-Create%2C-Edit?node-id=3272%3A0

The tier page was initially implemented to show all the tiers available for a given collective.

Ex: https://opencollective.com/babel/contribute/
![Screenshot_2019-09-16 Tiers - Open Collective](https://user-images.githubusercontent.com/1556356/64939685-1dced680-d862-11e9-9957-453347ce8da7.png)

The new collective page normally has a link to it (`View all the ways to contribute`) but the difference in design is disturbing so we're going to remove it for now.

This issue describes the steps to re-enable this button:

1. [x] Update contribute page with latest contribute cards design
2. [x] Add events
3. [x] Re-enable the button on the collective page

**Comment by piamancini** [comment]
@cuiki @raulgrafico Can we get a design update on this page with the new cards for Ben to implement? thanks!

**Comment by Betree** [comment]
Done in https://github.com/opencollective/opencollective-frontend/pull/2561
