### ISSUE TITLE
Contribution flow: fetch payment methods dynamically

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2427]
The contribution flow currently relates on the `LoggedInUser` provided by `withUser` to get the payment methods. This is a problem because:
1. The payment method query is called every time a user opens the website, and it's quite heavy (see #1395)
2. The payment methods displayed are sometime outdated, for example users sometimes need to refresh the page after they redeem a gift card (ex: https://opencollective.freshdesk.com/a/tickets/1671)

## Solution

In `pages/createOrder.js`, fetch user's payment methods and use them instead of what's provided by `withUser`.

**Comment by sbinlondon** [comment]
I believe this has been solved by my PR for the payments step - payment methods are dynamically fetched according to the profile you select. Ok to move this to done @Betree?

**Comment by Betree** [comment]
@sbinlondon yep! As said in the PR, I think we should do the fetch in the background at the beginning of the flow to make the flow faster and avoid displaying a loading spinner to users. I'll create an issues for that now.
