### ISSUE TITLE
New component to pick or create a collective, user, or organization

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2429]
## Problem

When adding funds, submitting an expense, or adding someone as a contributor to a collective, we need to be able to either find an existing profile or create one.

Right now, people need to create one based on email address but they often get confused with which email to use and we end up with duplicate accounts left and right.

## Solution

A new component `CollectivePickerComponent` to pick the right collective as the source (or "on behalf of").

## Scope

This could already be implemented in the current "Add Funds" interface and "add a member" in the edit collective page.

But this will also be used in the new create collective flow (more specifically in the empty collective page state) and in the upcoming new expense flow.

## Specs

```js
<CollectivePicker 
  types={["USER", "COLLECTIVE", "ORGANIZATION"]} 
  create={true}  // allow the user to create a collective inline?
  onChange={(collective) => {}} // returns the collective created ({id, type, slug, name})
  />
```

## Wireframes

![](https://d.pr/free/i/c2QwES+)

## Design

This is a very classic component that should be reusable in many different places. I'd keep it as simple as possible. We already have a nice design for the autocomplete form with suggestions.

![](https://d.pr/free/i/rug0fk+)

So we just need a proper way to prompt the user to create a missing profile and design the way the minimal form and button will look like.

![](https://d.pr/free/i/h3LYnD+)

**Comment by Betree** [comment]
The proposed specifications are great. A first MVP without the create action would already help in a lot of places (and this can easily be added later).

**Comment by alanna** [comment]
Looks great. This is popping up all over. We need it for the new expense flow and the Collective onboarding flow as well.

**Comment by piamancini** [comment]
Do we need design here or we can start an MVP without them?

**Comment by Betree** [comment]
I can easily start an MVP without design by re-using the component that Xavier mentioned above: 
![image](https://user-images.githubusercontent.com/1556356/65137467-adfb5000-da09-11e9-8b2e-47e7e5f9ab87.png)
 
The part that will really need design is the "Create collective" aspect of it.

**Comment by Betree** [comment]
To add a bit to the specs above, I think we should follow the pattern implemented by [react-select](https://react-select.com/) (the library that we use for selects) and have two components instead of one to better make the difference between "search a collective" and "pick a collective from this already-fetched list". So:
- CollectivePicker: dumb component, takes a list of collectives and filters it
- CollectivePickerAsync: Based on CollectivePicker, but load data asynchronously based on search

Also react-select implements multi-select, so I'd also add that this new component should support it and let us pick multiple collectives if the option is enabled (`allowMulti={true}`):
![Peek 18-09-2019 11-52](https://user-images.githubusercontent.com/1556356/65138286-0717b380-da0b-11e9-81d8-b897910505c4.gif)

**Comment by xdamman** [comment]
Sounds good. Do you have everything you need to get started on this? (so that we can start prioritizing this)

@cuiki can you make sure we have a design for the form that should appears beneath this to create a new collective (of type USER, COLLECTIVE or ORGANIZATION). 
It's probably very close to the one we already have in the contribution flow. No need for anything fancy here. 

![](https://d.pr/free/i/fI0e8F+)
(I'd just remove Github and Twitter to keep it as short as possible)

**Comment by Betree** [comment]
> Do you have everything you need to get started on this? (so that we can start prioritizing this)

I do and it should be really quick to implement, I'll prioritize it as soon as the release of the NCP is done :-)

**Comment by piamancini** [comment]
Design proposal: https://www.figma.com/file/GF1gQ7fWNfaOAFNwuLeAUl/OC.COM-XX3-%2F-Priority-Tasks?node-id=747%3A69

**Comment by raulgrafico** [comment]
Hi @xdamman @Betree @piamancini Please take a look at this. :)

![01](https://user-images.githubusercontent.com/1252676/65977780-287b9500-e438-11e9-910b-5b2ced662a69.png)
![02](https://user-images.githubusercontent.com/1252676/65977782-287b9500-e438-11e9-93d9-7bc5327f1802.png)
![03](https://user-images.githubusercontent.com/1252676/65977783-29142b80-e438-11e9-92e8-3c9f1d90fc88.png)
![04](https://user-images.githubusercontent.com/1252676/65977785-29142b80-e438-11e9-8e29-684c1930e68d.png)
![05](https://user-images.githubusercontent.com/1252676/65977786-29142b80-e438-11e9-928c-233f167d52f9.png)
![06](https://user-images.githubusercontent.com/1252676/65977787-29142b80-e438-11e9-9899-cbda39677024.png)
![07](https://user-images.githubusercontent.com/1252676/65977788-29142b80-e438-11e9-8129-09e68ff8208b.png)
![08](https://user-images.githubusercontent.com/1252676/65977789-29142b80-e438-11e9-9a5d-5a1e7e4d25e1.png)
![09](https://user-images.githubusercontent.com/1252676/65977790-29142b80-e438-11e9-9a8c-029b85f693b9.png)

**Comment by xdamman** [comment]
This is great!
I’d just also show the slug for organizations and maybe consider showing it in a new line in case the organization name (or user name) is too long.

**Comment by raulgrafico** [comment]
@xdamman Will we be displaying the slug for collectives also? Or this applies to organizations and users?

**Comment by Betree** [comment]
@raulgrafico It's for everyone, what I described above can be applied to any type of profiles: I could create a collective with the name `Webpack`, the system wouldn't stop me. Only the slug is unique.

**Comment by raulgrafico** [comment]
Thanks @Betree !

This is the new draft.

![01](https://user-images.githubusercontent.com/1252676/65984888-55cf3f80-e446-11e9-8e40-71d2d37676e8.png)
![02](https://user-images.githubusercontent.com/1252676/65984889-5667d600-e446-11e9-9763-e2fabcf41380.png)
![03](https://user-images.githubusercontent.com/1252676/65984891-5667d600-e446-11e9-82bd-5f530aaaae19.png)
![04](https://user-images.githubusercontent.com/1252676/65984892-5667d600-e446-11e9-9b69-37c59d30fe0c.png)
![05](https://user-images.githubusercontent.com/1252676/65984893-5667d600-e446-11e9-8bb5-07e10534aefc.png)
![06](https://user-images.githubusercontent.com/1252676/65984894-5667d600-e446-11e9-8002-38d8ee0f39d2.png)
![07](https://user-images.githubusercontent.com/1252676/65984896-5667d600-e446-11e9-90e8-3de6232c2b00.png)
![08](https://user-images.githubusercontent.com/1252676/65984897-5667d600-e446-11e9-99be-eb49ded70bdd.png)
![09](https://user-images.githubusercontent.com/1252676/65984898-57006c80-e446-11e9-90b1-c747dfa564f4.png)

**Comment by alanna** [comment]
Looks nice! 

Some thoughts:

I think the "create new" option should always be there, even if there are many closely matching strings, because sometimes people create similarly named new profiles. What if someone is looking at view #2 but they want to create a new one?

In different contexts, different types of profiles are allowed. I think it would be great if expenses could be created in the name of Collectives, or if Organizations could be the admin of a Collective, but it's not the case right now. Will the design allow for the correct logic and only show profiles of the types allowed for that action? 

* Add a Collective or Organization Admin (individual users only)
* Add funds manually (individuals and organizations only)
* Submit expense (individual users only)

Re #4: It doesn't make sense to have the "by joining you agree to the terms of service" text on this screen because often it will not be that person creating their own account, but someone else inviting them. We need to send the actual person an invitation and when they accept, they need to agree to the terms.

**Comment by xdamman** [comment]
Great feedback @alanna !

> What if someone is looking at view #2 but they want to create a new one?

Yes we should always show the option to create a new entity.

> In different contexts, different types of profiles are allowed.

Yes. This should be parameters when we instantiate the component (see original issue above)

@raulgrafico maybe you can add some design to show the case where there is only one button to create a user, or two buttons to create a user or an organization?

And yes good point on the terms of service. Ideally we should record a date (also for legal reasons) when the TOS have been approved. This will also solve the problem of creating a user on behalf of someone else and having the TOS approved at a different time (and keeping track whether the TOS have been approved)

**Comment by xdamman** [comment]
Also, shouldn't we reuse the existing default icon for a new collective instead of introducing this new symbol? What do you think @raulgrafico @cuiki ? (same for organization and user)

**Comment by raulgrafico** [comment]
@xdamman can you point me where to find that old symbol for collectives and organizations? I just asked Cuiki about it, and this is the default icon we've been using for new collectives, is not new from my understanding.

**Comment by raulgrafico** [comment]
> Yes. This should be parameters when we instantiate the component (see original issue above)
> 
> @raulgrafico maybe you can add some design to show the case where there is only one button to create a user, or two buttons to create a user or an organization?
> 
We made that version on the first draft, the idea was that based on the kind of "already created profile type" if there was a collective with that name, the user will be able to choose a user or an organization with that name, and at the same time they are still able to create a new collective profile using the small +NEW button. 

![05-01](https://user-images.githubusercontent.com/1252676/66054158-304f3e00-e4f9-11e9-86cb-bfd0f0e9e7a7.png)

**Comment by raulgrafico** [comment]
This is number 4 updated @alanna @xdamman.

![04](https://user-images.githubusercontent.com/1252676/66054488-ad7ab300-e4f9-11e9-9d02-38b49338a4af.png)

**Comment by alanna** [comment]
Looks good. Should we make it clear in the design that this will trigger an invitation to be sent to them? As long as they don't encounter this component when creating their own user account, it should always be the case. This will be completely seperate from the create new user interface we have now for new people signing themselves up, right?

**Comment by xdamman** [comment]
@raulgrafico those are the default icons we are currently using for new collectives and new organizations

![](https://d.pr/free/i/Z2PIsP+)

I'm fine to change those (though I have to say that I really like the default one for collectives, but I'm not a fan of the one for organizations), but we need to be consistent throughout

**Comment by raulgrafico** [comment]
Hi @alanna thanks, that sounds good, can you guys please help me with the copy for that message?

@xdamman we have some concepts right now on our design system, the only pending item we have right now is the fiscal host avatar image, but that is on our scope. Look at this, I think is looking nice:

![Screen Shot 2019-10-03 at 9 53 37 AM](https://user-images.githubusercontent.com/1252676/66138307-03b42880-e5c4-11e9-8887-dee28ed672b4.png)

**Comment by alanna** [comment]
@raulgrafico I think it would be enough to change the button from "create user" to "invite". This will make it obvious that a notification will be sent and the other person will be asked to accept the invitation. I think most users are familiar with this process from other apps.

**Comment by Betree** [comment]
Where are we with the feedback round? @xdamman is it ready for implementation?

**Comment by xdamman** [comment]
Ready for implementation.

The only thing as we discussed last call is to keep “Create user” and not “send invitation” because when you add funds or submit an expense on behalf of a user, you don’t want to wait for the user to accept the invitation to be able to record it.

However, we should record somewhere that the user hasn’t confirmed their account and hasn’t accepted the terms of service (TOS) to distinguish with the classic sign up flow.

Should we add a “confirmedAt” in the `Users` table or in the `Collectives` table?

**Comment by piamancini** [comment]
@xdamman are you ok with the icons of organization, collective and user to be implemented like that?

**Comment by Betree** [comment]
@raulgrafico Can we create a pattern to show in the UI which fields are required and which ones are not, so that users don't miss out the required fields? This would be helpful here and for all future forms.

"The best error message is the one that never shows up" :-)

**Comment by Betree** [comment]
Done in https://github.com/opencollective/opencollective-frontend/pull/2649 + https://github.com/opencollective/opencollective-frontend/pull/2859
