### ISSUE TITLE
Participation in Outreachy as an Organization 

### ISSUE THREAD

**Issue by yellowwoods12** [opencollective/opencollective#2430]
## Purpose
This issue is created to discuss whether or not Open Collective should participate in Outreachy as an organization.
Outreachy (previously the Free and Open Source Software Outreach Program for Women) is a program that organizes three-month paid internships with free and open-source software projects for people who are typically underrepresented in those projects. It is organized twice every year with a lot of Open Source organizations providing their projects for welcoming new contributors. 
It is a great initiative for Open Collective for welcoming new contributors in the community, spreading awareness about FOSS and at the same time supporting minorities from all around the globe.
Kindly present your views regarding this whether or not this step should be taken.
The last date of application for organizations is September 24, 2019 for the December to March round.

**Comment by yellowwoods12** [comment]
@piamancini @alanna  @znarf

**Comment by contraexemplo** [comment]
I'm an Outreachy helper so I may be able to help you if you wish to join us this round or on a future one!

**Comment by alanna** [comment]
This is a great idea! I will look into it.

**Comment by alanna** [comment]
It says

> FOSS communities need to have secured funding for at least one intern ($6,500).

Does this mean we need to come up with the funding ourselves? I think it does mean that.

**Comment by yellowwoods12** [comment]
> It says
> 
> > FOSS communities need to have secured funding for at least one intern ($6,500).
> 
> Does this mean we need to come up with the funding ourselves? I think it does mean that.

Yes we need funding for atleast one intern. They say that for a FOSS organization to be a part of Outreachy you need atleast $6500 of self-generated funding to be an 'includer' in the program.

**Comment by contraexemplo** [comment]
Yes, that's exactly right, Open Collective needs to fund at least one intern. There are also ways to help communities to have more than one intern, but that's not guaranteed.

**Comment by alanna** [comment]
OK, unfortunately I don't think we're going to be able to fund or prioritise participation in this program right now. However, we are considering diversity to be a big priority for hiring. We are also prioritising supporting initiatives like Open Source Community Africa and other ways of supporting more diverse contributors to be involved. In the future I hope we have more capacity for doing something like Outreachy.

**Comment by znarf** [comment]
Closing
