### ISSUE TITLE
New collective page: New Standalone Tier Page Access

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2431]
Right now - we generate a link to go to a standalone tier page if 
a) the short description is >140 characters or 
b) a long description has been added to the tier page. 

This is not at all obvious. We need to either find an easy way to enable a standalone page for a given tier (maybe when creating the tier?) or we just automatically generate it for each tier and we make something like the top section (with the background) clickable.

**Comment by Betree** [comment]
Agree, that'd be great if we can sort it before the release tomorrow.

Today we have a tier page for all tiers on the website, so the condition you mention (> 140 chars or long description) is only about whether we should display `Read more` or not.

Could we solve this by having a checkbox in `/edit/tiers` like this? 
`[ ] Enable the standalone page for this tier work`

**Comment by piamancini** [comment]
I think it's good enough, we'll add it to the docs and update the picture we have in the editing tiers documentation

**Comment by piamancini** [comment]
removing the V2 label and assigning it to you @Betree. It's not a blocker if we can't fit it in
