### ISSUE TITLE
ContributorCard: Edit public message from the grid

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2433]
The new contributor card implemented in https://github.com/opencollective/opencollective-frontend/pull/2576 is supposed to become the default. We still need a little re-factoring to make the best use of it and allow contributors to edit their messages directly from the contributor grid.

# Specs

## API

- [x] Mark the current `editMembership` endpoint as deprecated with `deprecationReason`
- [x] Create a new `editPublicMessage` endpoint based on `editMembership` and change the parameters (please set the `description` fields to the following):
  - `FromCollectiveId`: the collective id of the collective posting the message
  - `CollectiveId`: the collective id of the collective where the message is posted
  - `message`: the actual message
- [x] When changing public message, change it for **all** memberships matching `MemberCollectiveId=FromCollectiveId` and `CollectiveId=CollectiveId` couple. That way we'll ensure that we have the same public message everywhere even if the collective has multiple memberships to the collective (one as backer, one as admin..etc).
- [x] Add a `collectiveId` to the GraphQL `ContributorType` next to `collectiveSlug` https://github.com/opencollective/opencollective-api/blob/88ff9e6ac3badcf3e9a07dbef4fe2531febcdbc0/server/graphql/v1/types.js#L442. The ID should normally be prefilled, so resolving to the following should work: `return contributor.isIncognito ? null : contributor.id;`

## Frontend

- [x] Add a mutation to `ContributorCard` so users can edit their own messages directly from the grid using the new `editPublicMessage` endpoint. You **must** re-use the UX from `OrderSuccessContributorCardWithData` but it's up to you to decide if you want to write new code or use the existing one. 

Be careful! The `ContributorCard` is rendered multiple times in the grid, especially when scrolling. We need to keep decent performances for it, ideally cards where the user is not an admin should not see any performance impact. 

**Bonus**
- [ ] Use the `ContributorCard` on the order success page and delete `components/OrderSuccessContributorCardWithData.js`

**Comment by jzabala** [comment]
Hi, after updating the message if the user refresh the page she can see the old one because of the cache in `getContributorsForCollective`. Should I invalidate de cache for that collective after update?

**Comment by Betree** [comment]
@jzabala Ah I didn't see that coming, makes sense! We have an issue related to this: https://github.com/opencollective/opencollective/issues/2494

Tell me when you need it and I'll make the necessary change.

**Comment by jzabala** [comment]
> @jzabala Ah I didn't see that coming, makes sense! We have an issue related to this: #2494
> 
> Tell me when you need it and I'll make the necessary change.

@Betree yeah jejeje. I left a comment in the issue #2494

**Comment by znarf** [comment]
🏆 This issue was completed by @jzabala 

I retroactively added a $500 bounty on it. To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
