### ISSUE TITLE
Become a contributor page lists Default amount as Minimum amount

### ISSUE THREAD

**Issue by HeroicKatora** [opencollective/opencollective#2436]
**Describe the bug**

The contributor tiers shown in the page `ORG/contribute` list the default amounts as minimum amounts. For example, if the tier is configured with a default suggested amount is `$5` but starts at `$2`, the text will read:

> Starts at
> 
>  5 $ USD / month

**To Reproduce**

The `Babel` organization has tiers setup this way. Steps to reproduce the behavior:
1. Go to 'https://opencollective.com/Babel/contribute'
2. Note that the `Backers` tier says (this is the bug)
  > Starts at: 5 $ USD / month
3. Click on 'Become a backer'
4. Go to Details
5. Note that you can select `Amount (USD): $2`

**Expected behavior**
The text of the tier should specify:

> Starts at
> 
>  2 $ USD / month

**Desktop:**
 - OS: Linux
 - Browser: Firefox
 - Version: 69

**Additional context**

Haven't conclusively debugged this but have some possible leads: The graphql query of the contribution page is missing the attribute `tier.amountType` but that is later used to decide which amount to show in `components/contribute-cards/ContributeTier.js`.

https://github.com/opencollective/opencollective-frontend/blob/8af9a1ab259d14301fab609fe6476b43528b78e4/pages/contribute.js#L172-L227

https://github.com/opencollective/opencollective-frontend/blob/707aaca77b4d8825a1a228bb3a13e85062f376df/components/contribute-cards/ContributeTier.js#L36

**Comment by Betree** [comment]
Thanks @HeroicKatora! Solving bugs is way too easy which such a great report :wink: 

Your analysis was good, the query was missing the `amountType`. I'm pushing a fix right now.
