### ISSUE TITLE
Collective yearly budget: add a GraphQL loader

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2437]
Fetching `yearlyBudget` for multiple collectives has a huge cost because of N+1. We must:

1. Add a loader for the field
2. Revert https://github.com/opencollective/opencollective-frontend/pull/2606

**Comment by znarf** [comment]
Should we also cache it on API side somehow?

**Comment by Betree** [comment]
Let's `ANALYZE` the SQL query that will serve the yearly budgets for the loader. If the complexity is above ~500 for 1500 collectives (number of collectives OSC is a contributor to) then we should indeed add a cache to the specs.

**Comment by znarf** [comment]
Fixed in: https://github.com/opencollective/opencollective-api/pull/8319

Should we close @Betree ?

**Comment by Betree** [comment]
Good for me; I don't think updating the frontend (as suggested in the issue) is really that important.
