### ISSUE TITLE
NCP: add E2E tests for collectives

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2442]
The new collective page doesn't have a good test coverage yet. We want to solve that by adding new cypress tests. We've added the paths that we want to cover in https://github.com/opencollective/opencollective-frontend/blob/master/test/cypress/integration/04-collective_v2.test.js.

To implement the missing tests, you need to:
1. Setup your local environment & check the best practices: https://github.com/opencollective/opencollective-frontend/blob/master/docs/e2e.md
2. Open `test/cypress/integration/04-collective_v2.test.js`, for each test with a `// TODO`:
    - Remove the `.skip` (`it.skip('...')` --> `it('...')`)
    - Implement the test (make sure it passes)
    - If you're not sure about what should be tested for a given test, please ask directly on this issue
3. Commit the result, CI will run your tests to make sure they pass.

**Comment by NotJohs** [comment]
@Betree can I be assigned this task

**Comment by NotJohs** [comment]
@Betree can I get avatar and cover image

**Comment by Betree** [comment]
@NotJohs Sorry, I don't understand what you need exactly?

**Comment by Betree** [comment]
As a helper for the file upload feature, feel free to install & use https://www.npmjs.com/package/cypress-file-upload

**Comment by NotJohs** [comment]
@Betree `'can change avatar' `and `'can change cover background-image'`
both need images to be uploaded and my question is: 
should I use any image or would one be provided to me?

**Comment by Betree** [comment]
Feel free to use any image :slightly_smiling_face:

**Comment by NotJohs** [comment]
Alright

**Comment by NotJohs** [comment]
@Betree having a little issue with the `cy.login` command
After creating a hosted collective, I log in with `cy.login` command which worked and redirected to ``/<randomslug>/v2``.
The problem is after redirection I logged off the `testuser`

**Comment by Betree** [comment]
@NotJohs Can you share the code with me?

**Comment by NotJohs** [comment]
Currently in the hospital. Will do when i get back home.

**Comment by Betree** [comment]
I hope everything's fine for you @NotJohs, let me know if I can help (there's no problem if you need additional time to complete this)

**Comment by NotJohs** [comment]
@Betree Thanks a lot. Currently working on this.

**Comment by znarf** [comment]
🏆 This issue was completed by @NotJohs

To claim the bounty please, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new

**Comment by NotJohs** [comment]
@znarf can we close this issue?
