### ISSUE TITLE
New Collective Page Feedback

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2445]
This issue is where we will be collecting feedback from the team and community about the newly redesigned Collective page.

**Comment by dodgepong** [comment]
French and Spanish localization use a `5` instead of a `$` when listing contribution amounts in the "Top financial contributors" section.

**Comment by gusaus** [comment]
Seems like a lot of collectives will be surprised many of their tiers link to a stand-alone page.
The pages look a bit incomplete and need a bit of improvement to the text formatting right out of the box -
https://opencollective.com/babel#section-contribute
https://opencollective.com/babel/contribute/gold-sponsors-1906
https://opencollective.com/babel/contribute/base-support-sponsor-3790

Guess this is the ‘Force standalone page’ setting on /edit/tiers?

> The standalone tier page, represented by the “Read more” link, will be enabled automatically if you write a short description longer than 100 characters or if you’ve already set a long description. You can use this switch to force the display of the page.

**Comment by gusaus** [comment]
There doesn't seem to be an obvious way to edit existing tiers from the collective page. 
![OpenProducer - Open Collective 2019-09-23 13-25-20](https://user-images.githubusercontent.com/113996/65459847-98b96380-de05-11e9-8e00-41cf19706a79.png)

**Comment by gusaus** [comment]
Where is the text under certain contributors coming from? Is there a way to edit or hide? For example https://opencollective.com/libretime#section-contributors

![LibreTime - Open Collective 2019-09-23 15-23-31](https://user-images.githubusercontent.com/113996/65467369-1ab18880-de16-11e9-977e-ee6e44bae2bf.png)

**Comment by alanna** [comment]
I can't see a 'manage contributions' button on host organization pages. How do host orgs get to their recurring contributions page?

**Comment by Betree** [comment]
> French and Spanish localization use a `5` instead of a `$` when listing contribution amounts in the "Top financial contributors" section.

@dodgepong We indeed had a bug with localization which is fixed now. Thanks for reporting!

> Guess this is the ‘Force standalone page’ setting on /edit/tiers?

@gusaus Yes, but standalone page is also enabled when the tier's description is too long. I'll prioritize the enhancements for it, I agree that it needs to be improved.

> There doesn't seem to be an obvious way to edit existing tiers from the collective page.

Edit/sort tiers is a feature yet to come, final result should look like this:

![image](https://user-images.githubusercontent.com/1556356/65491110-b55da600-deae-11e9-9b7a-88882109d12e.png)

> Where is the text under certain contributors coming from? Is there a way to edit or hide? For example https://opencollective.com/libretime#section-contributors

This is the public message set after a successful contribution. We'll add the ability to edit your own public message directly from the contributors grid soon. Currently, there's no way for collective admins to hide a specific public message but we'll probably solve the problems induced (spam mostly) with https://github.com/opencollective/opencollective/issues/2097

![image](https://user-images.githubusercontent.com/1556356/65491254-fd7cc880-deae-11e9-9191-1d2aa6051e0a.png)

> I can't see a 'manage contributions' button on host organization pages. How do host orgs get to their recurring contributions page?

@alanna The CTAs defined for hosts in [design](https://www.figma.com/file/e71tBo0Sr8J7R5n6iMkqI42d/OC.COM-04-%2F-Collectives-%E2%86%92-Create%2C-Edit?node-id=4324%3A0) were `Dashboard` and `Apply` only. I personally didn't know about this use case, I'll add a third button to cover this.

**Comment by nemchik** [comment]
Just to reiterate my point from #2228 I feel like the v2 interface is a great improvement and does an awesome job with making `Become a contributor` a call-to-action.

Thanks for the hard work on v2!

**Comment by AlinaWithAFace** [comment]
Hi! I'd like to add custom images/icons to the financial tiers, is there a way to do so?

**Comment by Betree** [comment]
Hi @AlinaWithAFace, it's not possible yet but that's something we want to support. You should follow https://github.com/opencollective/opencollective/issues/2121 to get updates about this specific feature.

**Comment by znarf** [comment]
Let's close!
