### ISSUE TITLE
Get rid of "moment" dependency in Frontend

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2446]
# Why

The `moment` dependency is quite heavy: more than `65kb` Gzipped according to [Bundlephobia](https://bundlephobia.com/result?p=moment@2.24.0). The use we have for it is very simple, so we could easily replace it by helpers or other existing dependencies.

We also want to get rid of `moment-timezone`, which is ~35kb GZip (and that requires moment anyway).

**Goal: Make the bundle smaller.**

# How

See specs in https://github.com/opencollective/opencollective/issues/2446#issuecomment-693372258

<details>
<summary>Legacy specs</summary>

We have around 15 files using `moment` right now, with 3 use cases:

1. To format dates, like in https://github.com/opencollective/opencollective-frontend/blob/7a5b25e5138acbfe447521080f43357967f0e4b6/src/apps/expenses/components/InvoiceDownloadLink.js#L48

    Can usually be replaced by `FormattedDate` or `.toLocaleDateString(...)` (to display it) or by various helpers, such as this one (to send data to the API): https://github.com/opencollective/opencollective-frontend/blob/2921e4a7a133cc0ee5cffba7d88a042b02b27fa6/lib/utils.js#L407

2. To show a relative datetime (ex: `12 days ago`0) with the `Moment` component. 

    Another library that we use, `react-intl`, provides this functionality through the `FormattedRelativeTime` component: https://github.com/formatjs/react-intl/blob/master/docs/Components.md#formattedrelativetime

3. To add or remove an interval, like in https://github.com/opencollective/opencollective-frontend/blob/fb832dc517f3f9acf877787a9f87d497eb435a6a/components/expenses/TransactionsExportPopoverAndButton.js#L79

    Should be replaceable by https://github.com/opencollective/opencollective-frontend/blob/6c8d3b1f3a2411667b9a2b9258380306177956d3/lib/date-utils.js#L9 (though the function can be completed or modified to better fit the needs). 

</details>

**Comment by EvanBurchard** [comment]
@Betree are you talking about getting rid of moment-timezone and/or react-add-to-calendar too?

**Comment by Betree** [comment]
@EvanBurchard I missed the fact that these two libraries were depending on `moment`. It brings too much complexity to this issue so I'm tempted to close it. If you already started working on it please let me know, we can re-open.

**Comment by Betree** [comment]
Re-opening this issue, we don't use `react-add-to-calendar` anymore so the migration should be simpler. Also from https://momentjs.com/docs/#/-project-status/:

> Recently, Chrome Dev Tools started showing recommendations for replacing Moment for the size alone. We generally support this move.
> **We now generally consider Moment to be a legacy project in maintenance mode. It is not dead, but it is indeed done.**

Also see:

<ul>
<li><a href="https://dockyard.com/blog/2020/02/14/you-probably-don-t-need-moment-js-anymore"><em>You Probably Don't Need Moment.js Anymore</em></a></li>
<li><a href="https://github.com/you-dont-need/You-Dont-Need-Momentjs/blob/master/README.md"><em>You don't (may not) need Moment.js</em></a></li>
<li><a href="https://inventi.studio/en/blog/why-you-shouldnt-use-moment-js"><em>Why you shouldn't use Moment.js...</em></a></li>
<li><a href="https://blog.logrocket.com/4-alternatives-to-moment-js-for-internationalizing-dates/"><em>4 alternatives to moment.js for internationalizing dates</em></a></li>
</ul>

There's no rush (and arguably no need) to migrate the API, but migrating the frontend could bring improvements on bundle size.

**Comment by sbinlondon** [comment]
Maybe one for a bounty candidate, since it seems very 'chore-y'? Or would we want to do it ourselves?

**Comment by darkmtr** [comment]
@Betree can this be a bounty? i'd like to work on it.

**Comment by Betree** [comment]
Some specs to complete the issue:

- Guessing timezone should be done with `Intl.DateTimeFormat().resolvedOptions().timeZone` (there should be a fallback on a default timezone for old browsers).
- Using [day.js](https://github.com/iamkun/dayjs) for dates computations (add, subtract, etc) would be a good because it's only 2kb
- As much as possible, try to rely on the `FormattedDate` component for displaying dates
- Do **not** use day.js internationalization capacities. The [`FormattedTime`/`FormattedRelativeTime`](https://formatjs.io/docs/react-intl/components#formattedrelativetime) components already support that.
- No need to do anything about `Cypress.moment` (it's only a dev dependency)

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

@darkmtr Has the priority on this (first to comment). If you're ok with the amount, feel free to assign yourself.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by snitin315** [comment]
@darkmtr are you still working on it? If not I would like to take up this.

**Comment by darkmtr** [comment]
@snitin315 i already did the initial work and it's almost done i believe. I don't have the time currently to work on it. If you want to, take a look at the pr and continue it.

**Comment by snitin315** [comment]
Sure 👍🏻

**Comment by Betree** [comment]
:trophy: This issue has been completed by @snitin315 

To claim the **$200** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
