### ISSUE TITLE
Error when creating Organization

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2448]
**Describe the bug**
Getting "unexpected error" after creating a new organization, but the organization is actually created. It should take you to that organization's page.

**To Reproduce**
1. Go to user menu
2. Click + in Organization section
3. Fill out form and submit
4. See "unexpected error"
5. New Organization is listed in your menu and is working fine

**Comment by maddhruv** [comment]
yeah,
I first got a success message
but on the organization page
i got this error

https://opencollective.com/test40?CollectiveId=61872&status=collectiveCreated

<img width="1428" alt="Screenshot 2019-09-24 at 10 33 56" src="https://user-images.githubusercontent.com/18121502/65482476-dcb87100-deb6-11e9-8dce-b37a0066a6a7.png">

**Comment by NotJohs** [comment]
@znarf tried recreating this issue but everything worked fine.

**Comment by znarf** [comment]
I tested and haven't got the error. But:

![Screenshot 2019-10-03 at 10 07 41](https://user-images.githubusercontent.com/806/66109815-c6509a80-e5c5-11e9-9b12-280008a29ece.png)

- The page says "Collective created with success" it should be "Organization created with success"
- The organization is not editable,  it should be editable

This is what you should see:

![Screenshot 2019-10-03 at 10 09 20](https://user-images.githubusercontent.com/806/66109893-e97b4a00-e5c5-11e9-859e-908526152b26.png)

**Comment by Betree** [comment]
Crash fixed in https://github.com/opencollective/opencollective-frontend/pull/2709
Message fixed in https://github.com/opencollective/opencollective-frontend/pull/2643
Missing Edit button fixed in https://github.com/opencollective/opencollective-frontend/pull/2647
