### ISSUE TITLE
NCP: add E2E tests for users

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2450]
The new collective page doesn't have a good test coverage yet. We want to solve that by adding new cypress tests. We've added the paths that we want to cover in https://github.com/opencollective/opencollective-frontend/blob/master/test/cypress/integration/05-user_v2.test.js.

To implement the missing tests, you need to:
1. Setup your local environment & check the best practices: https://github.com/opencollective/opencollective-frontend/blob/master/docs/e2e.md
2. Open `05-user_v2.test.js`, for each test with a `// TODO`:
    - Remove the `.skip` (`it.skip('...')` --> `it('...')`)
    - Implement the test (make sure it passes)
    - If you're not sure about what should be tested for a given test, please ask directly on this issue
3. Commit the result, CI will run your tests to make sure they pass.

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged.

:warning: Because we want the cypress issues to be addressed by different contributors, this bounty cannot be assigned to the same person who will tackle https://github.com/opencollective/opencollective/issues/2442, https://github.com/opencollective/opencollective/issues/2451 or https://github.com/opencollective/opencollective/issues/2452

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by sudo-kaizen** [comment]
@Betree, does one need to have the cypress tool installed to do this?

**Comment by Betree** [comment]
@sudo-kaizen Yes, this tool is part of our dev dependencies so it should automatically run on your machine if your do:
- `npm install`
- `npm run cypress:open`

**Comment by sudo-kaizen** [comment]
Thanks!

**Comment by Betree** [comment]
@sudo-kaizen do you want to be assigned?

**Comment by sudo-kaizen** [comment]
😊 Thanks. Not yet

**Comment by maddhruv** [comment]
hey @Betree I would love to pick this up
But I just have one doubt
do you just want to focus on the test suites already defined there
or wanna add more?

**Comment by Betree** [comment]
Hey @maddhruv, we should focus on the ones already defined in `05-user_v2.test.js`. This issue is about implementing all the tests in this file that have a `// TODO`.

**Comment by maddhruv** [comment]
Okay
I would pick this up

**Comment by Betree** [comment]
:trophy: This issue is now completed by @maddhruv  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

---

For more info about the bounty process and how to format your invoice, please read https://docs.opencollective.com/help/developers/bounties

If you have any feedback on how we could improve the bounty process or how to better onboard new developers please [share it with us](https://slack.opencollective.com/), we're always eager to improve :slightly_smiling_face:
