### ISSUE TITLE
NCP: add E2E tests for organizations

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2451]
The new collective page doesn't have a good test coverage yet. We want to solve that by adding new cypress tests. We've added the paths that we want to cover in https://github.com/opencollective/opencollective-frontend/blob/master/test/cypress/integration/04-organization_v2.test.js.

To implement the missing tests, you need to:
1. Setup your local environment & check the best practices: https://github.com/opencollective/opencollective-frontend/blob/master/docs/e2e.md
2. Open `04-organization_v2.test.js`, for each test with a `// TODO`:
    - Remove the `.skip` (`it.skip('...')` --> `it('...')`)
    - Implement the test (make sure it passes)
    - If you're not sure about what should be tested for a given test, please ask directly on this issue
3. Commit the result, CI will run your tests to make sure they pass.

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$50** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged.

:warning: Because we want the cypress issues to be addressed by different contributors, this bounty cannot be assigned to the same person who will tackle https://github.com/opencollective/opencollective/issues/2442, https://github.com/opencollective/opencollective/issues/2450 or https://github.com/opencollective/opencollective/issues/2452

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by jzabala** [comment]
Hi @Betree, I can try this one :D.

**Comment by Betree** [comment]
@jzabala all yours!

**Comment by jzabala** [comment]
Thanks @Betree

**Comment by someofthethings** [comment]
I thought according to the new bounty guidelines here: https://blog.opencollective.com/scaling-up-our-bounty-program/ the minimum is now $100?

**Comment by JoyLubega** [comment]
Hey @Betree  what exactly should be tested according to this issue

**Comment by znarf** [comment]
@jzabala are you still on it or can someone else have a look?

**Comment by jzabala** [comment]
> @jzabala are you still on it or can someone else have a look?

@znarf I was a little busy with https://github.com/opencollective/opencollective/issues/2433 and after that I was going to work on this one. But if you prefer you can reassign it. No problem :D

**Comment by JoyLubega** [comment]
@znarf I want to give it a try

**Comment by jzabala** [comment]
I assigned it to you @JoyLubega. Anything you need just let us know 🙂

**Comment by Betree** [comment]
:trophy: This issue is now completed by @JoyLubega. 

To claim the $50 bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
