### ISSUE TITLE
NCP: add E2E tests for hosts

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2452]
The new collective page doesn't have a good test coverage yet. We want to solve that by adding new cypress tests. We've added the paths that we want to cover in https://github.com/opencollective/opencollective-frontend/blob/master/test/cypress/integration/06-host_v2.test.js.

To implement the missing tests, you need to:
1. Setup your local environment & check the best practices: https://github.com/opencollective/opencollective-frontend/blob/master/docs/e2e.md
2. Open `06-host_v2.test.js`, for each test with a `// TODO`:
    - Remove the `.skip` (`it.skip('...')` --> `it('...')`)
    - Implement the test (make sure it passes)
    - If you're not sure about what should be tested for a given test, please ask directly on this issue
3. Commit the result, CI will run your tests to make sure they pass.

**Comment by sbinlondon** [comment]
@betree @znarf I'd be interested in taking on this issue :blush:

**Comment by Betree** [comment]
:trophy: This issue is now completed by @sbinlondon!

To claim the **$50** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
