### ISSUE TITLE
ERROR: value too long for type character varying(255)

### ISSUE THREAD

**Issue by novdddd** [opencollective/opencollective#2454]
**Describe the bug**
Whenever I try to edit the description of a tier and click **Save** I get the following error in red font:

```
! value too long for type character varying(255)
```

**To Reproduce**
1. Try editing the description of a tier
2. Click **Save**

**Screenshots**
![50](https://user-images.githubusercontent.com/24556287/65543266-80d30400-df19-11e9-8a85-975b1ae47bd5.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest - Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by Betree** [comment]
Hi @novdddd, thank you for reporting this issue. Tier's description is limited to 255 characters. If you want to add more details, you can force the creation of a tier page:

![image](https://user-images.githubusercontent.com/1556356/65544132-e7085880-df12-11e9-93af-c0e285fec527.png)

Then from the tier card click on "Read more":

![image](https://user-images.githubusercontent.com/1556356/65546393-bb3ba180-df17-11e9-8ba9-d2c1b1e5d630.png)

Click on `Add a rich description` and you'll be able to put all the content that you want from there:

![image](https://user-images.githubusercontent.com/1556356/65546449-d73f4300-df17-11e9-9428-f8ebe1a34f35.png)

---

We acknowledge that this error message is unclear. Let's improve this:
- Add a validation in https://github.com/opencollective/opencollective-api/blob/b89c3f3a12c733edc6660afeb254b9e134326cdf/server/models/Tier.js#L57 (will improve the error message)
- Add a `maxLength` on the field, so we won't be able to type more than the field can accept anymore
- Add a description below the short description to incentive to use the tier page for longer descriptions

**Comment by Betree** [comment]
# Specs

## API

- Add a `len` validation in with value `[0, 255]` in https://github.com/opencollective/opencollective-api/blob/b89c3f3a12c733edc6660afeb254b9e134326cdf/server/models/Tier.js#L57 (will improve the error message)

## Frontend

- Add a `maxLength` on the `description` field, so we won't be able to type more than the field can accept anymore
- Add a description below the `description` field to incentive to use the tier page for longer descriptions:

    > Limited to 255 characters. If you need more space, please use the standalone tier page - you'll be able to add as much content as you need from there.

---

Please follow our [code guidelines](https://docs.opencollective.com/help/developers/best-practices-and-code-guidelines), especially:

* The strings must be internationalized. See [/help/developers/translations](https://docs.opencollective.com/help/developers/translations)
* Whenever it's possible we must use `styled-components` to write styles. See [OC Styleguide](https://opencollective-styleguide.now.sh/)
* We're getting rid of `Bootstrap`. Please don't use it for new developments.
* Tests written with Cypress must follow our [good practices](https://docs.opencollective.com/help/developers/testing-with-cypress) conventions.

**Comment by novdddd** [comment]
Hello @Betree, I tried deleting the content of the tier's description and moving it to the rich description section, but I get the same error. I practically can not edit any of the tier's details, for example the title can not be updated, clicking **Save** gives me the same error as described above:

![SharedScreenshot](https://user-images.githubusercontent.com/24556287/65547644-8e40bc00-df22-11e9-91e2-580582e2ad22.jpg)

**Comment by novdddd** [comment]
@Betree This is what I piratically see when I try to edit the details of a tier:

![a1](https://user-images.githubusercontent.com/24556287/65548058-5d14bb80-df23-11e9-87c3-45dadc1ec745.png)

I can not update anything. Thank lot for your help!!

**Comment by Betree** [comment]
That's bad, thanks for the additional details! We're going to prioritize this

**Comment by novdddd** [comment]
@Betree Thank you a lot! Also, I can not delete the created tiers, in order to make new ones, the error appears at the bottom of the screen, next to the save button, each time I click it.

![2](https://user-images.githubusercontent.com/24556287/65550055-71f34e00-df27-11e9-92ba-958555964771.jpg)

**Comment by Betree** [comment]
@novdddd can you try again?

**Comment by novdddd** [comment]
@Betree Works perfectly! Thank you so much for your fast response!!! ♥

**Comment by Betree** [comment]
Great, thanks to you for all the details @novdddd
