### ISSUE TITLE
Discover page: use new collective cards

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2455]
The discover page still uses the old collective cards. These cards don't match our policy regarding logos that must be:
- Squares
- Displayed on a white background

![image](https://user-images.githubusercontent.com/1556356/65669586-1f5b8400-e044-11e9-8f45-31c96a9e102d.png)

Best solution would be to replace them with a design similar to what has been defined for the new profile pages:

![image](https://user-images.githubusercontent.com/1556356/65669669-487c1480-e044-11e9-83fa-e7fbd8b7ba42.png)

**Comment by misocho** [comment]
Hi, I'm new here. I'd like to be assigned this issue.

**Comment by Betree** [comment]
Hi @misocho, thanks for proposing! There's a tiny bit of refactoring to do before this issue, I'll ping you once it's ready.

**Comment by JoyLubega** [comment]
hey, @Betree  I have created another component that has items from both cards. I wanted to ask you before i raise a PR. Not sure if the design is okay.
<img width="1440" alt="Screen Shot 2019-12-22 at 9 34 53 PM" src="https://user-images.githubusercontent.com/29824008/71325808-399de480-2503-11ea-8284-80f84711b49d.png">

**Comment by Betree** [comment]
Hi @JoyLubega, looks good!

We'd need to rename `Backers` to `Financial contributors` (that's our default terminology now).

I'd also keep both designs consitant by displaying the info on two lines like on the contribution cards:

![image](https://user-images.githubusercontent.com/1556356/71417891-23f5ff80-2668-11ea-95c3-68ec654ed212.png)

**Comment by JoyLubega** [comment]
Okay, thanks. Let me move forward with that.
