### ISSUE TITLE
Issue invoice when creating a pending order

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2456]
Most companies require an invoice before paying. 
Right now we only generate an invoice after the payment is made.

We should issue an invoice when making a manual donation (by wire transfer) and attach it to the email confirmation that contains the instructions to make the payment.

It would be great to also add those instructions in the actual PDF invoice.

**Comment by zaunders** [comment]
Yes, if we would use our collective to invoice for things like talks or consulting services where we want to retain some of the income in the collective, it would be very useful to be able to send invoices in a way that clients are used to. 

Being able to create an invoice send it and have clients pay by bank transfer or something like that would require less understanding and garner more trust for most clients in our collective.

**Comment by alanna** [comment]
This would be a very helpful thing to have. Right now we hard-code the payment instructions for bank transfer payment type, and have to manually turn it on for hosts. 

In an ideal world, this would be a setting hosts could turn on themselves, and when they did so they could input the payment instructions that will go in the email and also appear on the automatically generated invoice. We would just need to make sure we have all the other info needed to generate a payable invoice (legal entity name, address, tax number if required) but I don't think it's complicated.

We're implementing system generated payable invoices for expenses soon (part of the new expense flow) and it will be a very similar process for generating invoices on behalf of hosts.

**Comment by Betree** [comment]
@jfdh needs that for OC Europe.

**Comment by alanna** [comment]
I think this is the same as #4497 which has more detail

**Comment by Betree** [comment]
Indeed, closing in favor of https://github.com/opencollective/opencollective/issues/4497
