### ISSUE TITLE
Rich text editor: clickable/editable area doesn't take the full size

### ISSUE THREAD

**Issue by maddhruv** [opencollective/opencollective#2457]
**Describe the bug**
On the add/edit description text field, click doesn't work on the whole `ql-container` but just on the `ql-editor` which is just one line of the whole container.

**To Reproduce**
1. Go to 'https://opencollective.com/{username}'
2. Click on 'Add a description' or Edit description 'Icon' in front of your description
3. Try to click at any place in the editor container
4. You won't be able to click anywhere but at a certain area

**Expected behavior**
The user should be able to click and edit by clicking at any place in the container

**Screenshots**
<img width="757" alt="Screenshot 2019-09-27 at 19 52 30" src="https://user-images.githubusercontent.com/18121502/65776829-7fdfe380-e160-11e9-98a4-fe77fda518e2.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 77

**Additional context**
### Solution
- either make the container editable (❌) or change the size of the editor to that of the container (🤜)

**Comment by Betree** [comment]
Good catch! Note that this is also true for all the places where we show this editor (tier page, comment, updates...etc). Related to https://github.com/zenoamaro/react-quill/issues/426

**Comment by maddhruv** [comment]
I have a fix for that

**Comment by maddhruv** [comment]
Please assign me
