### ISSUE TITLE
Pricing page: layout problem wth FAQ

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2460]
When expending the details of the FAQ section in the pricing page (https://opencollective.com/pricing), the height doesn't expand with it which conflicts with the footer:

![Peek 27-09-2019 18-23](https://user-images.githubusercontent.com/1556356/65785128-f9250980-e153-11e9-9b04-01d673e0e619.gif)

**Comment by EslamHiko** [comment]
@flickz I have a Jquery solution for this issue

**Comment by Betree** [comment]
@EslamHiko would it be more complex to go for a CSS solution? The code above is pretty cryptic

**Comment by EslamHiko** [comment]
@Betree one solution would be to give the footer `position: relative` property but the accordion will be hidden when we collapse a few tabs, maybe a better solution is to show only one tab at a time

**Comment by flickz** [comment]
I think the idea of one tab at a time sounds cool but that doesn't really eliminate the issue. A long text tab will show the issue.

**Comment by EslamHiko** [comment]
@flickz `position: relative` will hide the text so it'll look better.
btw the last tab doesn't work with me.

**Comment by Betree** [comment]
So the main problem here is that we have `height: 2700px;` on the pricing page. That will never work on mobile, I'm surprised that the review of the page didn't catch this.

Whatever the fix, we must get rid of this fixed height.
