### ISSUE TITLE
'create an update' button on updates page

### ISSUE THREAD

**Issue by maddhruv** [opencollective/opencollective#2462]
**Describe the bug**

The `Create an Update` link (button) on the `{collective}/updates` page seems to be a normal text not like a button (actionable)

This ⬇️ 

<img width="545" alt="Screenshot 2019-09-28 at 17 54 52" src="https://user-images.githubusercontent.com/18121502/65816462-841c0780-e219-11e9-95b3-39359bc74e01.png">

---

This should be the button from `{collective}/v2#section-updates` page
Which is ⬇️ 
<img width="1294" alt="Screenshot 2019-09-28 at 17 59 44" src="https://user-images.githubusercontent.com/18121502/65816498-fdb3f580-e219-11e9-8221-cda86e5e22cd.png">

**Expected behavior**
Have the same StyledButton at both the places

**Comment by znarf** [comment]
Sounds like a look idea to add the button on the top right of the Updates page.

**Comment by dinolinjob** [comment]
Can I work on this?
If yes, where is the page exactly located?
