### ISSUE TITLE
date picker hides behind scroller for "contributor since"

### ISSUE THREAD

**Issue by maddhruv** [opencollective/opencollective#2463]
**Describe the bug**
When opening the Date Picker the height of the wrapping container doesn't adjust as per. And hence it hides behind the wrapper - where the user had to scroll to get the date picker on screen :confounded: :confounded:
This should not be the behaviour.
Can be seen here as well
<img src="https://user-images.githubusercontent.com/1556356/61625026-1338fc00-ac7a-11e9-90fa-3455b499cd27.gif" />
at 	https://github.com/opencollective/opencollective-frontend/pull/2229

**To Reproduce**
1. Go to '{collective}/edit/members`
2. Click on 'add Core Contributor'
3. Scroll down to 'Contributor SInce'
4. Click on the input

**Screenshots**
<img width="871" alt="Screenshot 2019-09-28 at 18 25 31" src="https://user-images.githubusercontent.com/18121502/65816838-61402200-e21e-11e9-999b-257de4e99a92.png">

**Comment by znarf** [comment]
Sounds similar to https://github.com/opencollective/opencollective/issues/2161

@Betree because you fixed the similar issue, can you have a look?

**Comment by Betree** [comment]
@maddhruv I believe this issue is not solved yet

**Comment by maddhruv** [comment]
@Betree I don't know how I closed this issue 🤔 😕 Maybe on the github mobile something bad happened. Sorry for that

**Comment by jeffin143** [comment]
For me, It work smooth, Am i missing something 

![Screenshot from 2019-10-18 21-54-35](https://user-images.githubusercontent.com/21286134/67111200-12205800-f1f2-11e9-9952-8623d1945fd4.png)

**Comment by Betree** [comment]
Solved by https://github.com/opencollective/opencollective-frontend/pull/6332
