### ISSUE TITLE
event creation failure still creates a template

### ISSUE THREAD

**Issue by maddhruv** [opencollective/opencollective#2464]
**Describe the bug**
I don't know if this actually is a bug or what.
But I can't digest the behaviour as such so can be a question as well

When creating an event if the event creation fails (especially if the error is - `The slug * is already taken. Please use another slug for your event.`, it stills creates a template for the same event name. 😕 😕 Why?

**Comment by maddhruv** [comment]
After inspecting a little more
I just found out that
The issue is not in template generation
but the event creation
The event is created even if it throws this error
`The slug * is already taken. Please use another slug for your event.`

Which should not happen

**Comment by NotJohs** [comment]
@maddhruv can I get more context on this issue?

**Comment by znarf** [comment]
We don't support templates anymore.
