### ISSUE TITLE
buying more tickets than available

### ISSUE THREAD

**Issue by maddhruv** [opencollective/opencollective#2465]
**Describe the bug**
##### Collective Events
Why am I being able to buy/get tickets more than the quantity available(left out) 😕 ❓ 

**To Reproduce**
1. Go to '{collective}/events/{event_name}'
2. Click on 'Get Tickets' for any ticket
3. Try to increase the number of tickets to more than the left out amount

**Expected behavior**
One should not be able to buy tickets more than the number of tickets left out
and the other suggestion I would put along with this - *there should be a maximum amount/number of tickets one can buy* - this would to some extent reduce *misuse* and increase the *user availability* for the tickets (such that a single person would not buy all the tickets and sell them in the black  - 🃏 - for a higher price 😉 

**Screenshots**
<img width="457" alt="Screenshot 2019-09-28 at 19 25 20" src="https://user-images.githubusercontent.com/18121502/65817597-f5ae8280-e226-11e9-8f3f-1749e7426180.png">
🆙 able to add 59 tickets even when only 55 are available

**Comment by znarf** [comment]
@maddhruv just some feedback on reporting bugs. You don't need to ask questions like "Why am I seeing this thing that is not right ???". It's a bug, there will be no answer to that question. You can just describe it using a neutral tone "I see this thing that doesn't seem right" or "This thing is not right". Also, let's try to not fall in emoji overload in such issues.

**Comment by znarf** [comment]
I just tested and I noticed it is controlled a bit later in the process.

![Screenshot 2019-10-09 at 14 11 14](https://user-images.githubusercontent.com/806/66480318-b1c94200-ea9e-11e9-92d8-d58e08fe1d3c.png)
