### ISSUE TITLE
Double *and* in Creating a Collective docs

### ISSUE THREAD

**Issue by jzabala** [opencollective/opencollective#2466]
**Describe the bug**
There are 2 *and*'s in _Creating a Collective_ documentation.

**To Reproduce**
1. Go to https://docs.opencollective.com/help/collectives/create-collective

**Expected behavior**
There should be only 1 *and*

**Screenshots**
![Screen Shot 2019-09-28 at 7 43 59 PM](https://user-images.githubusercontent.com/1315054/65833499-1fa38b80-e29f-11e9-8bba-e44006c52eaf.png)

**Comment by maddhruv** [comment]
Good Catch 👋 
I have raised a PR for the fix
Thanks

**Comment by maddhruv** [comment]
@znarf this can be closed

@jzabala Fixed
Thanks for the issue
