### ISSUE TITLE
Expenses and Orders page: unclear 404 error message

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2469]
Example: https://opencollective.com/cucumber/expenses/10360

We need a better error message for when expenses doesn't exist. Currently we show "Unknown error", we need to have a `MessageBox` with:

> This expense doesn't exists or has been deleted.

![image](https://user-images.githubusercontent.com/1556356/65863561-9e1c2e00-e370-11e9-8309-3fea32eba53f.png)

**Comment by znarf** [comment]
It's a 404, it's happening because I just deleted the Expense and triggered the error when refreshing.

**Comment by Betree** [comment]
Alright, would be nice to have an explicit error message for this one, I'll edit the issue

**Comment by Betree** [comment]
Note: same issue with order page

**Comment by Betree** [comment]
Added to hackathon as it's similar to https://github.com/opencollective/opencollective/issues/2272 and https://github.com/opencollective/opencollective/issues/1369
