### ISSUE TITLE
NCP: Improve behavior for Hero image crop/resize

### ISSUE THREAD

**Issue by lsmith77** [opencollective/opencollective#2471]
**Describe the bug**
I am having problems adjusting the zoom level to zoom out. Also uploading a new image seems to start a wrong zoom level initially. I assume the issues are related so creating a single ticket.

**To Reproduce**
1. Go to https://opencollective.com/symfony-diversity
2. Click on Edit cover
3. Try to zoom out (it does not)
4. Click on Remove
5. Upload a new image
6. Click save
7. No image shown (but it was uploaded and is referenced in the source but with a wrong transform to make it invisible)

**Expected behavior**
Ability to zoom out and ability to upload a new image (with a sensible default zoom level)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 18.04, iPad OS 13.1.1
 - Browser Firefox/Chrome/Safari
 - Version Latest

**Additional context**
see also https://opencollective.slack.com/archives/C0HSLRNVC/p1569563773086100

**Comment by anshumanv** [comment]
I'm not facing any of the above issues, works flawlessly for me.

OS: MacOS Mojave
Browser: Chrome 77

**Comment by Betree** [comment]
@anshumanv Can you try with this image?

https://opencollective-production.s3-us-west-1.amazonaws.com/d7d0c490-1106-11e9-88dc-33f6e9e72bfc.jpeg

**Comment by anshumanv** [comment]
Yes, works for me.

I did have to bring it in the visible area initially, but whenever I reloaded the page it seemed to fit well.

![image](https://user-images.githubusercontent.com/21009455/66134351-d4c6a280-e615-11e9-91f8-8eb2a1100b57.png)

**Comment by Betree** [comment]
@anshumanv Alright, thanks for testing :pray: Like @lsmith77 I'm using Ubuntu, that may be related. I'll try to see if I can reproduce based on that.

@lsmith77 could you also share your screen resolution please?

**Comment by lsmith77** [comment]
ok I tried once more. this time with my iPad. there I got it to work. but its quite a "choppy" experience to try and resize it to the right size.

I then went back to my Ubuntu laptop and there I could also get it to work but the experience is even more cumbersome trying to use a touchpad.

So I think in summary, I might have given up on my laptop because the experience was so choppy that I thought its not working at all. Also the fact that the image was moved somewhere into the lower corner didn't help either (maybe there should be a "center and set to default resolution" button for this case?).

**Comment by Betree** [comment]
> maybe there should be a "center and set to default resolution" button for this case

+1 to have alignment buttons. I'll see how we could implement this without surcharging the interface.

In the mean time, a good actionable for this issue would be:
- [ ] Make sure added images are aligned to the top-right corner and best fitted when uploaded
- [ ] When (de-)zooming, make sure that the center of the image stays at the same position
