### ISSUE TITLE
Unable to see what Collective an event is associated with

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2474]
I am trying to figure out which Collective created [this event](https://opencollective.com/collective/events/open-energy-data-hackdays-26090ev) but I can't tell from the info on the page or the URL. I think the design should make this clear.

**Comment by Betree** [comment]
It's not super visible because the link looks like a text, but the info is there:

![image](https://user-images.githubusercontent.com/1556356/65944087-3da0f580-e431-11e9-9b99-cca62bf5ce7d.png)

The collective is: https://opencollective.com/dat-alets-ch

**Comment by alanna** [comment]
Oh I see. In that case, I think it would be good to add text like "Hosted by: [Collective]" to make that more clear.

**Comment by alanna** [comment]
Maybe not 'hosted' because that's a word that means something else on our platform. Created by would probably be fine.

**Comment by Betree** [comment]
Yep, that's an easy change.
