### ISSUE TITLE
NCP: Improve accessibility on the new collective page

### ISSUE THREAD

**Issue by flickz** [opencollective/opencollective#2475]
I did an accessibility audit of the new collective page for mobile and desktop, the scores were pretty low.

#### Desktop

<img width="1440" alt="Screenshot 2019-10-01 at 8 16 23 AM" src="https://user-images.githubusercontent.com/15707013/65953834-ae014400-e43c-11e9-9c84-45a1be7698d2.png">

#### Mobile

<img width="1435" alt="Screenshot 2019-10-01 at 8 13 07 AM" src="https://user-images.githubusercontent.com/15707013/65953865-c2454100-e43c-11e9-9e6e-36536e5d40a1.png">

We should care more about accessibility.

#### Tool
https://web.dev/measure 

##### Buttons
- Add `aria-label` `prop` to [`StyledButton`](https://github.com/opencollective/opencollective-frontend/blob/master/components/StyledButton.js#L16) just like the way other props within the component were added (Don't forget propTypes and description of the prop).

- In [Hero.js](https://github.com/opencollective/opencollective-frontend/blob/master/components/collective-page/hero/Hero.js#L124-L145), add `aria-label` prop to the following `StyledRoundButton` component
                     - `aria-label = "Twitter link"`
                     - `aria-label = "Github link"`
                     -`aria-label = "Website link"` 

##### Img tag
- Add `alt` attribute to `img` element in [`TopBar.js`](https://github.com/opencollective/opencollective-frontend/blob/master/components/TopBar.js#L79). I.e `alt="Open collective"`

##### input tag
- In [`SearchInput`](https://github.com/opencollective/opencollective-frontend/blob/master/components/SearchForm.js#L45) component add the `aria-label` attribute. I.e `aria-label = "Open collective search input"`

---- Will be adding this soon ---

**Comment by Betree** [comment]
Good initiative, I'm not giving enough attention to accessibility. Can you share a link or the name for the tool that you've used in your screenshots?

**Comment by maddhruv** [comment]
> Can you share a link or the name for the tool that you've used in your screenshots?

These are lighthouse audits
available in the `chrome devtools` as well (under `Audits` section) or you can measure it on https://web.dev/measure

**Comment by jeffin143** [comment]
@flickz , Was trying to handle this, but eslint fails when adding aria-label as a prop ? What should I do ?

**Comment by flickz** [comment]
@jeffin143 Which of the components did you add the prop to?

**Comment by jeffin143** [comment]
> @jeffin143 Which of the components did you add the prop to?

Just here 

https://github.com/opencollective/opencollective-frontend/blob/0f9951486db8b6495dc8c39ddbc3d43abc76b231/components/StyledButton.js#L104

**Comment by znarf** [comment]
> Will be adding this soon

@flickz It's impossible to solve this issue if the desired outcome is not clear.

**Comment by flickz** [comment]
It is tricky but I'll take care of it.

**Comment by Betree** [comment]
Can we clearly spec out the expectations for this issue? Is it about reaching a score, implementing specific attributes?

A work was started in https://github.com/opencollective/opencollective/issues/2652 but it's hard to move forward with it at the moment.
