### ISSUE TITLE
FE: Footer is not sticking to bottom

### ISSUE THREAD

**Issue by anshumanv** [opencollective/opencollective#2477]
**Describe the bug**
Footer is not sticking to the bottom when the main content height is less.

**To Reproduce**
See https://staging.opencollective.com/tootallnate/transactions

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/21009455/65973474-03fbd900-e489-11e9-9ad1-7f7e1b07de46.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 77

**Additional context**

A question, what are we importing footer in every page? Not checked but if it's in every page then can't we import it once in the page wrapper and it'll make it's way on all pages?

**Comment by anshumanv** [comment]
cc @Betree @znarf wdyt? ✨

**Comment by Betree** [comment]
> A question, what are we importing footer in every page? Not checked but if it's in every page then can't we import it once in the page wrapper and it'll make it's way on all pages?

We use to import it in every page but we now use the `Page` component for new pages that adds it automatically: https://github.com/opencollective/opencollective-frontend/blob/8a3903d8de5328632f30f3107b83d7ff40de847d/components/Page.js

I wouldn't want to have too complex styles to have the border at the bottom, to me the correct fix here would be to have a `min-height` on the transactions page.

@opencollective/design / @raulgrafico do you have an opinion on this one?

**Comment by anshumanv** [comment]
> We use to import it in every page but we now use the Page component for new pages that adds it automatically: https://github.com/opencollective/opencollective-frontend/blob/8a3903d8de5328632f30f3107b83d7ff40de847d/components/Page.js

Ah this is great!
Maybe I saw older code before.

> I wouldn't want to have too complex styles to have the border at the bottom, to me the correct fix here would be to have a min-height on the transactions page.

Just adding `min-height` doesn't seem to work, trying a fix and sending a PR, we can iterate from there. 😄
