### ISSUE TITLE
opencollective.dev domain

### ISSUE THREAD

**Issue by maddhruv** [opencollective/opencollective#2479]
> opencollective.dev

The `.dev` domains are already out in the public.
Most of the giants are already available on `.dev` domains sharing their awesome resources, projects, documentation, and whatnot. mdn.dev, nodejs.dev, women.dev, github.dev to name a few.

### What resources/website we want to share?

We can share our documentation through that domain as well or sharing stories about our collectives and other entities.

### Is it available?
YES

### How?
https://get.dev is the place google is sharing these domains via various partners.

**Comment by maddhruv** [comment]
@znarf @piamancini :point_up:

**Comment by piamancini** [comment]
Thanks for the heads -up @maddhruv we purchased it already. 
Closing issue.
