### ISSUE TITLE
Gift cards: better surface expiry date

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2480]
Following up on this thread: https://opencollective.slack.com/archives/C0RMV6F8C/p1569949743159400

We had multiple cases of people that couldn't find their gift cards because they were expired and they didn't know the reason. We should make that clearer.

A few ideas have been suggested in this thread:

1. [x] Make sure that it's not possible to redeem an expired gift card and that the error message is clear (should already be the case).

2. [x] Add the expiry date on the gift card displayed on the redeem page

![image](https://user-images.githubusercontent.com/1556356/66029185-1ca6d600-e4ff-11e9-99f5-26d2417a771f.png)

3. [ ] Continue to show expired gift cards up to one month after their expiry date in the contribution flow, but make them disabled in the list and add a `Expired` tag.

---

Because (3) is more complex, we should tackle (1) and (2) in priority and eventually follow up with (3) in a separate issue.

**Comment by piamancini** [comment]
@znarf can we tackle this in the redeem page changes you are doing?

**Comment by znarf** [comment]
@piamancini Nothing I'm taking care of. Maybe for Ben as part of https://github.com/opencollective/opencollective/issues/2536

**Comment by Betree** [comment]
Thanks for the heads up, I'll take care of that as part of https://github.com/opencollective/opencollective-frontend/pull/2929

**Comment by piamancini** [comment]
thanks ben!

**Comment by Betree** [comment]
Still two boxes to check. First improvement made in https://github.com/opencollective/opencollective-frontend/pull/2929

**Comment by Betree** [comment]
Closing, will follow up with the last item in https://github.com/opencollective/opencollective/issues/2673
