### ISSUE TITLE
Expense-related email not received

### ISSUE THREAD

**Issue by staltz** [opencollective/opencollective#2481]
This is basically the same as https://github.com/opencollective/opencollective/issues/2302 and https://github.com/opencollective/opencollective/issues/2401 but this time when I submitted an expense I didn't get the email to approve/reject that expense. Also, I haven't received emails from OpenCollective in the past week or so (e.g. have not received the monthly report emails).

**Comment by znarf** [comment]
<img width="1260" alt="Capture d’écran 2019-10-02 à 10 58 31" src="https://user-images.githubusercontent.com/806/66031416-a5c00c00-e503-11e9-828b-9e2d0df3ca74.png">

Same issue, still no idea why you end up on this list of "Complaints".

**Comment by znarf** [comment]
Removed you from this list. I contacted Mailgun about it and asked for explanation.
