### ISSUE TITLE
NCP: The section highlited in NavBar is not the correct one

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2482]
When navigating to "Updates", "Budget" appears as active in the menu.

**To Reproduce**

1. Go to 'https://opencollective.com/manyverse'
2. Click on 'Updates'

**Current behavior**

"Budget" is highlighted

**Expected behavior**

"Updates" should be highlighted

**Screenshots**

<img width="1227" alt="Capture d’écran 2019-10-02 à 11 55 41" src="https://user-images.githubusercontent.com/806/66035670-defc7a00-e50b-11e9-9cc3-475a7c8587a1.png">

**Environment:**

 - OS: Mac OS
 - Browser: Firefox
 - Version 69.0.1

**Comment by Betree** [comment]
I can't reproduce on Firefox/Linux. Could you share your screen resolution?

![image](https://user-images.githubusercontent.com/1556356/66036583-e1f86a00-e50d-11e9-92d2-506f5b7dfe0c.png)

**Comment by znarf** [comment]
I have a big monitor and use custom/random size windows. Also, it's high resolution so difficult to share the number of pixels. This is happening with a big height, the Budget section needs to be visible.

<img width="975" alt="Capture d’écran 2019-10-02 à 12 17 37" src="https://user-images.githubusercontent.com/806/66037029-01dc5d80-e50f-11e9-9982-7ee0df468348.png">

**Comment by Betree** [comment]
> I have a big monitor and use custom/random size windows. Also, it's high resolution so difficult to share the number of pixels. This is happening with a big height, the Budget section needs to be visible.

Makes sense, the function takes the latest section that has been scrolled on more than 500px. I didn't try on monitors higher than `1080px` before, but I can reproduce by simulating a `1920x1600` resolution.

We need to change the formula.
