### ISSUE TITLE
Should we bring back global collective goals?

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2483]
In the previous version of the collective page, we used to display global goals based on balance or yearly budget. We've deprecated this feature on the new collective page (#2288) to favor tier goals instead (#1979, https://github.com/opencollective/opencollective-frontend/pull/1888). We haven't killed the feature and the data associated yet, but it is now hidden in the edit interface.

As outlined in [this Slack thread](https://opencollective.slack.com/archives/C0HSLRNVC/p1569537147082000) initiated by @themightychris, the tiers goals may be not be adapted for certain use cases that global collective goals used to cover. Quoting:

>The recurring-support focused progress bar was a major unique drawing point for us as we try to shift our MOs from one-off funding to sustainable funding. Just mentioning goals in the about section pales in comparison as a means to shift focus

> Our approach here is rallying our established local communities to getting our core programming covered entirely by recurring contributions, through individual donations and leveraging our long tail of institutional relationships to build a wall off institutional sponsors. Setting sep goals at e.g. the $100 and $250 and $1000/mo level has negative value for us, we want to get to $10k/yr and then to $100k/yr and we want to push sponsors up to the highest tier we can get each up to. We want to seed each sponsor level with one we have close relationships with so future sponsors will be cued to pick higher levels by what tiers their peers are in

---

@opencollective/design feel free to add details about the motivation for deprecating the global collective goals.

**Expected outcome for this issue:**
- Specify how global goals should be re-implemented in the new collective page
- Or decide that we should kill the feature entirely

Example: https://opencollective.com/webpack/legacy
![image](https://user-images.githubusercontent.com/1556356/66041354-f6426400-e519-11e9-91e3-62f427442d56.png)

**Comment by Betree** [comment]
If we want to move on with bringing back the collective goals, it could take the form of a new `Goals` section in the new collective page only displayed when collectives set goals in `/edit/goals`, with an optional checkbox to display it or not.

- The fastest way to re-implement it would be to just re-use the previous code that we had in the cover for this new section (imported dynamically so that we don't make the bundle heavier for other collectives). That'd be a really easy change, but we must be aware of #1434 - this component doesn't always look nice!

- A more complex way that we can go for if there's demand for it would be to adapt a new design for these goals. Food for tough, this is how Tipeee (a French donation platform for YouTube creators) displays the global goals for projects:

![Peek 02-10-2019 14-04](https://user-images.githubusercontent.com/1556356/66042739-9ea5f780-e51d-11e9-9163-fbbc899053b2.gif)

**Comment by Memo-Es** [comment]
Thank you, @Betree, for creating the issue. Also, thank you @themightychris to bring this up.

We think that what @themightychris is trying to do can be achieved very neatly with the current capabilities of the Collective Page.
![Frame 2](https://user-images.githubusercontent.com/49539954/66070732-83d08480-e517-11e9-9398-25bc3c0a5411.png)

So, in this case, you set up a different card for each yearly goal and set a specific amount for contribution, (you can use the card header images to differentiate them better). However, we need to add some changes to the tier creation process for this:

This tier creation process will imply that the first thing you set is if this new tier is whether financial or other and under "other" you will have "product, event, goal, etc."

<img width="1151" alt="Schermata 2019-10-02 alle 13 09 48" src="https://user-images.githubusercontent.com/49539954/66071226-6354fa00-e518-11e9-9325-cf7732a92dd2.png">

What's also missing here is a field to set the header image of the card between the default ones or an upload option.

**Comment by themightychris** [comment]
Thanks @Memo-Es  -- IMHO, tier-level goals will be a counterproductive approach to our real goals. 

We want to get to ~$10k a year of sustainable income for the org in order to deliver a given set of programming. I really don't care how many of those are $100/mo, $250/mo, or higher contributions. I want to focus our community and promotion around the overall goal and what it gets us. I want people to be able to drop in custom contributions to help us towards our goal.

**Comment by Memo-Es** [comment]
Ok, I thought of that solution based on this part of the [slack thread](https://opencollective.slack.com/archives/C0HSLRNVC/p1569537147082000)

> I want to set a goal of $10k annual funding to cover our weekly event costs, and then a $90k yearly goal after that, and drive all the orgs in our city that like to posture as supporting our work to sign up for $100/mo, $250/mo, and higher tiers based on how high up they want their logo to be

It sounds to me that you want your sponsors to showcase themselves depend on their tier, but if that doesn't matter to you you can maintain only one yearly goal for dev production and another yearly goal to track only the budget for events.
And use the "Other contributions" to publish your events, sell merch, or set other particular goals.

It could look like this...

![Frame 2 1](https://user-images.githubusercontent.com/49539954/66087227-5b0eb600-e53c-11e9-928c-b86228a56e62.png)

I hope it looks more like what you want @themightychris. 
I think is important that particular cases like yours help us communicate better the capabilities of the tools we design, thank you very much.

**Comment by piamancini** [comment]
@themightychris How about just having one tier only? 
An open tier, with one goal to Sustain the community. In that way, you can have a standalone page if you want to share that tier that has the budget, you can add a video, it has a progression bar, etc.

**Comment by alanna** [comment]
Maybe a flexible option to fit with the current design is combining @piamancini 's solution above of using a tier goal, and also having a "featured tier" option, so Collectives can have one tier which fills the full width of the contribution section and reveals details like the goal, video thumbnail, etc. That way if a Collective is doing a big campaign they can really highlight it. This could fit with the existing page logic and design.

**Comment by themightychris** [comment]
These suggestions are certainly feasible workarounds, and I could certainly be wrong about this, but my experience tells me these workarounds will all be substantially less effective for our use case as the previous structure would have been

Our use case might differ from where most of the platform usage is right now, but I believe it's a substantial area for growth. The new design maybe does make more sense for efforts that our fundraising against an open system e.g. webpack raising money from the whole wide world. Maybe it makes sense to split up goals, let everyone pick which goal they want to contribute to, contribute whatever amount they want, and just rank all contributors evenly by total contribution

[The group I'm designing for](https://www.meetup.com/Code-for-Philly/) (and our [85 peers in the US alone](https://brigade.codeforamerica.org/) who I'm trying to design for also) fundraises against a **closed system**. Our audience is people in Philadelphia interested in helping put software to more effective public use. We're more successful when we're fundraising against a big goal, and when we offer our prospective funders a menu of contribution levels that they can self sort into based on which tier they're trying to position themselves into before our community. It's not going to be effective having them pick their own arbitrary contributions. What's effective is when they see their peer's logos tiered at 2-3 levels. I think it would also be a bad experience for our sponsors if folks coming after them could just +$1 to elbow to the front of the stack. There's some community solidarity to sharing a tier.

**Comment by Betree** [comment]
@themightychris I've started an experiment in https://github.com/opencollective/opencollective-frontend/pull/2775 to bundle the goals progress bar (that we had before) as a section of the new collective page. There's some design enhancements to do, but I think that we can make it work. Could you look at https://opencollective-frontend-gmoyxfkyea.now.sh/webpack/v2 to provide some feedback about how you feel about this solution?

**Comment by themightychris** [comment]
@Betree this looks great! The placement within the new design is perfect and the responsiveness works well enough (seems identical to what it did before). This launching as-is would solve for most of my needs.

**Comment by Betree** [comment]
Great to hear! I'll add the option in the collective settings to enable it (this will be opt-in) and I'll do some polish to make it look better for a release in the coming week.

**Comment by themightychris** [comment]
@Betree I can't wait to fire it up, thanks! Happy to take it for the first spin before it's ready for wide release if you can feature flag `code-for-philly`

**Comment by Memo-Es** [comment]
@Betree Please tell me if you need anything from design

**Comment by piamancini** [comment]
@Betree Thank you for taking this! I am looking at https://opencollective-frontend-gmoyxfkyea.now.sh/webpack/v2 and two suggestions: 

- background is super big, I would make the black space smaller. At least in my screen size. 

<img width="1280" alt="Screen Shot 2019-10-08 at 9 48 11 AM" src="https://user-images.githubusercontent.com/3671070/66376850-c7f8d480-e9b0-11e9-9d42-2cc334523d27.png">


- @Memo-Es can we do a quick enhancement / experiment to make it more in sync with the current design? Please don't go overboard here, just maybe changing the background color to white, the text to the black / grey we use and the blue/greens to the ones currently on NCP? Again, just a quick try, we don't have design resources to put here at the moment given the other priorities.

**Comment by Betree** [comment]
@themightychris final version will look mostly like this:

![image](https://user-images.githubusercontent.com/1556356/66572329-0a690f80-eb71-11e9-99db-1b1035b5b609.png)

**Comment by Memo-Es** [comment]
Great @Betree this looks good 👍🏽

**Comment by Betree** [comment]
Will be deployed in the next few days. I'll update on the issue when it's live.

**Comment by Betree** [comment]
Deployed!
