### ISSUE TITLE
link to the main collective from a subcollective

### ISSUE THREAD

**Issue by lsmith77** [opencollective/opencollective#2485]
## User story 
As a user viewing a collective with its sub-collectives I want to have links between the main and the sub-collective in both directions, so that I don't get lost.

## Best solution for this problem
Sub-collectives have a link back to the main collective and potentially even to the other sub-collectives, so that users can easily move around to see the different causes within our initiative they can support.

## MVP
A link from the sub-collective to the main collective.

**Comment by Betree** [comment]
That's legit, we'll need an input from @opencollective/design before implementation.

Also @znarf I think that you had concerns about using the `ParentCollectiveId` for that, let me know if you want to chat about a better technical solution before we move forward with this issue.

**Comment by Betree** [comment]
Note: this will be easier now that https://github.com/opencollective/opencollective/issues/2633 is done, it won't require any API changes. The only thing we need to move forward is a design proposal acknowledging that a subcollective can have multiple parents.

**Comment by alanna** [comment]
I want to bump this. The sub-Collective should definitely show the parent Collective somehow.

**Comment by Betree** [comment]
Would something like this work? What would be the correct terminology: `Parent collective`, `Main collective`?

![image](https://user-images.githubusercontent.com/1556356/72968949-d4b90100-3dc4-11ea-8e76-f856cfe29221.png)

**Comment by Betree** [comment]
Related question: can a sub-collective have multiple parents?

**Comment by alanna** [comment]
Yes that design looks good to me @Betree 

I don't know about multiple parents.

**Comment by Betree** [comment]
Ok, we'll have to decide at some point (especially before #1620). Technically it's already possible, we just need to think about whether this is something we want or not.

**Comment by raulgrafico** [comment]
Link to the Figma file @Betree:
https://www.figma.com/file/GF1gQ7fWNfaOAFNwuLeAUl/OC.com-Hot-Fixes?node-id=1081%3A12923

**Comment by Betree** [comment]
![image](https://user-images.githubusercontent.com/1556356/78659361-b8106d80-78cb-11ea-92f0-eb64b8b81517.png)
