### ISSUE TITLE
Show Collective's host on expense page

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2487]
## User story 
As a fiscal host admin, I need to verify which host an expense is connected to, in order to make sure payments are being made correctly. This info used to appear on the header under the Collective name on individual expense pages because it was in the Collective header everywhere. With the new design, it's missing. We don't need it to appear everywhere, but it should appear somewhere on individual expense pages and on the expenses page for that Collective.

## MVP
"Host: [host name]" appears under Collective name in header on individual expense pages and the expense page for a Collective. If there's a better place for it that's fine - anywhere is OK on the page as long as it's visible.

![Screen Shot 2019-10-03 at 3 49 41 PM](https://user-images.githubusercontent.com/5498878/66095999-ff086800-e5f5-11e9-8d2a-803b848f9f98.png)

![Screen Shot 2019-10-03 at 3 50 00 PM](https://user-images.githubusercontent.com/5498878/66096000-ffa0fe80-e5f5-11e9-8673-3a3aa29cf5d5.png)

**Comment by Betree** [comment]
Let's have a feedback from @opencollective/design first, I don't want to change the NavBar without their consent because what we'll do here will become a pattern for many other pages.

**Comment by piamancini** [comment]
@alanna We should add this to the specs of the expense flow if we want it to be done

**Comment by alanna** [comment]
@Memo-Es can you make sure this gets in the new design?

**Comment by Betree** [comment]
Implemented in the new expense flow
