### ISSUE TITLE
non-descriptive error on add funds form

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2488]
This error came up when I was trying to manually add funds, but it doesn't explain what the problem is so it's not useful. I think it wanted either an Organization name or website. This was a contribution from an individual so I don't have these things.

<img width="606" alt="Screen Shot 2019-10-03 at 4 23 54 PM" src="https://user-images.githubusercontent.com/5498878/66097329-7a6c1880-e5fa-11e9-9611-7d49b451a743.png">

**Comment by flickz** [comment]
Closed in https://github.com/opencollective/opencollective-api/pull/2750
