### ISSUE TITLE
Turn on Paypal payment method for one-time contributions for Open Collective Foundation host

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2489]
## User story 
As a financial contributor, I want the option to pay via Paypal to Collectives hosted by Open Collective Foundation.

## Best solution for this problem
Make Paypal a payment option for all hosts, recurring and one time.

## MVP
Turn on Paypal for one-time contributions for Foundation, like we have for OSC.

## Note
People are sending money direct to Foundation's paypal address, which is creating unnecessary manual work for the host admins.

**Comment by alanna** [comment]
Can this please be done soon?

**Comment by piamancini** [comment]
yes, @znarf do you think this can be a medium complexity task?

**Comment by znarf** [comment]
@piamancini This needs to be handled by the core team. Maybe this is doable without much code. We can prioritize that.

**Comment by znarf** [comment]
I looked at it and it's more complicated than what I thought, not something we can do on the side. Removing the priority.

Quickly created some branches with todos:
- https://github.com/opencollective/opencollective-api/tree/feat/paypal-payment
- https://github.com/opencollective/opencollective-frontend/tree/feat/paypal-payment
