### ISSUE TITLE
Bug in how Gift Cards info is displayed in Transaction Details

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2491]
**Describe the bug**
In the list of transactions, the information about the Gift Card is not displaying correctly. 

**To Reproduce**
Go to https://opencollective.com/material-ui/transactions and scroll down until you find: 

<img width="1037" alt="Screen Shot 2019-10-03 at 11 45 24 AM" src="https://user-images.githubusercontent.com/3671070/66116855-be97f280-e5d3-11e9-88b4-e0ea6a74c01e.png">

**Expected behavior**

For it to read with a Gift Card from Triplebyte

**Comment by flickz** [comment]
@piamancini I think I have a fix for this but I'm not sure how to create and use a gift card locally, in order test.
