### ISSUE TITLE
Expense titles should be linkified

### ISSUE THREAD

**Issue by anshumanv** [opencollective/opencollective#2493]
I think it makes sense to linkify the title of the expense to the actual expense page for quick access, or else we need to go to all expenses and then to the page.

![image](https://user-images.githubusercontent.com/21009455/66127635-c8d4e380-e609-11e9-94ca-be9f43c07676.png)

cc @Betree @znarf

**Comment by anshumanv** [comment]
> I agree. Just run into this issue myself and it's pretty annoying.

Great! Will fix this. 👍

**Comment by Betree** [comment]
Thanks for reporting and fixing this issue @anshumanv you did great :+1:
