### ISSUE TITLE
Refresh contributors caches when there are new contributions

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2494]
At least one user was recently surprised to not see their name in the contributors section just after contributing (see https://opencollective.freshdesk.com/a/tickets/1931). The reason is that we cache contributors so that we don't run the query more than once per hour.

My proposal would be:

- [x] Have only one cache per collective. Today cache key is based on limit/contributor type. We should cache all contributors and do the filtering in Javascript rather than SQL.
- [ ] When order success in `createOrder`, refresh the cache for contributors of the collective.

**Comment by jzabala** [comment]
To move the filtering to js will certainly make every request a little bit slower. Not crazy slow but slower. If all we want to do is to remove every cache related to a specific collective how about if we improve the `del` method in cache to receive a string or a regex? This way with a regex like `collective_contributors_42*` we can remove all cache entries related to that collective.

**Comment by Betree** [comment]
> To move the filtering to js will certainly make every request a little bit slower.

That's true, but we also want to paginate this endpoint in the future to add progressive loading to the contributors grid. Filtering in JS would help for that.

The strategy of caching per request signature (`collective_contributors_${collectiveId}_${limit}`) may also have an important RAM consumption and could be an easy DDOS vector: if you flood this endpoint by incrementing `limit` at each iteration the you're gonna see memory issues pretty quickly.

These two reasons make me prefer the JS filtering solution.

@znarf we need to iterate on this issue to unblock @jzabala for https://github.com/opencollective/opencollective/issues/2433. What's your advice/opinion for the next steps?

**Comment by jzabala** [comment]
@Betree you are right. I didn't consider those points. But I still think this implementation is problematic.

To do the filtering we would need to load all the data in memory the first time and do the filtering in js from there. It just take a couple of collectives with a lot of data for us to have a RAM problem.

Since we are moving to progressive loading maybe a cache is not necessary any more. Or we could cache the initial 20 or 50 since is going to be the most intensive search every time a user visits a Collective page.

**Comment by jzabala** [comment]
> @znarf we need to iterate on this issue to unblock @jzabala for #2433. What's your advice/opinion for the next steps?

For issue #2433 I can just use the current cache api and remove the collective's cache. Not need to rush.

**Comment by Betree** [comment]
> To do the filtering we would need to load all the data in memory the first time and do the filtering in js from there. It just take a couple of collectives with a lot of data for us to have a RAM problem.

Not really, all contributors for Webpack (one of the largest collectives that we have, ~1500 contributors) is somewhere around 600kb so that's not too bad. We can afford doing that for all collectives.

> Since we are moving to progressive loading maybe a cache is not necessary any more. Or we could cache the initial 20 or 50 since is going to be the most intensive search every time a user visits a Collective page.

The contributors SQL query is really expensive. Because it needs to compute the total amount contributed for each contributor to sort them, pagination is not gonna help much. Though there are other solutions, having the filtering in JS has the advantage of being really simple to implement.

In terms of performance, slicing is really cheap. Filtering can be more expensive, but optimizing that doesn't seems too complex too.

> For issue #2433 I can just use the current cache api and remove the collective's cache. Not need to rush.

@jzabala because of the limit there are currently multiple caches, but you could indeed delete the "main one", used by the collective page with the params `(roles: [BACKER], limit: 150)`.

**Comment by jzabala** [comment]
> Not really, all contributors for Webpack (one of the largest collectives that we have, ~1500 contributors) is somewhere around 600kb so that's not too bad. We can afford doing that for all collectives.

yeah, it is not that bad.

> The contributors SQL query is really expensive. Because it needs to compute the total amount contributed for each contributor to sort them, pagination is not gonna help much. Though there are other solutions, having the filtering in JS has the advantage of being really simple to implement.

> In terms of performance, slicing is really cheap. Filtering can be more expensive, but optimizing that doesn't seems too complex too.

Cool. Let's go for it then :D.

> because of the limit there are currently multiple caches, but you could indeed delete the "main one", used by the collective page with the params (roles: [BACKER], limit: 150)

I am close to summit the PR so, I am removing the main cache as you proposed. I left a comment there so that we can check it after this one is finished.

**Comment by Betree** [comment]
@jzabala perfect, I'll follow up on that quickly after your PR.

**Comment by znarf** [comment]
@Betree What's the status of this issue?

**Comment by Betree** [comment]
Only the last bit is missing (`When order success in createOrder, refresh the cache for contributors of the collective.`). Tho we should probably refresh cache in `editMembers`

**Comment by bolariin** [comment]
I think this issue might be resolved because I noticed that `invalidateContributorsCache` was called in `Collective.js` in both [addUserwithRole](https://github.com/opencollective/opencollective-api/blob/32fab8e14166a0158234caae0b4200c05f22ddbb/server/models/Collective.js#L1396) and [editMembers](https://github.com/opencollective/opencollective-api/blob/32fab8e14166a0158234caae0b4200c05f22ddbb/server/models/Collective.js#L1839).

**Comment by Betree** [comment]
@bolariin we only do it for admins and members. Financial contributors (`roles.BACKER`) and event's attendees (`roles.ATTENDEE`) currently don't trigger a refresh. 

I would say that no matter the role, we should always refresh the cache when adding a member to a collective. So either we update that part of the code, or we factorize everything in a Sequelize `afterCreate` [hook](https://devdocs.io/sequelize/manual/hooks) in `server/models/Member.js`.

Maybe just one exception to that: no need to refresh the cache if the role is `FOLLOWER` (it will prepare a safe ground for https://github.com/opencollective/opencollective/issues/1445).

**Comment by bolariin** [comment]
@Betree thanks for explaining things
