### ISSUE TITLE
Event: ticket is not respecting parameters set when created

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2495]
**Describe the bug**

This is the ticket I created and saved: 

<img width="660" alt="Screen Shot 2019-10-03 at 4 24 16 PM" src="https://user-images.githubusercontent.com/3671070/66135934-f8302400-e5fa-11e9-8535-4f79a6b10f6e.png">

Note the default and minimum amounts, the CTA for the button and the frequency. 

However, this is what i'm seeing in the ticket 
<img width="474" alt="Screen Shot 2019-10-03 at 4 24 27 PM" src="https://user-images.githubusercontent.com/3671070/66136025-1564f280-e5fb-11e9-8528-306a4a7075bd.png">

The CTA button is set to a default: Donate, the frequency is flexible (I had set it to one time) and the minimum and default amounts are not respected. 

**To Reproduce**
1. Go to a collective
2. Create an event
3. Create a ticket inside the event with flexible amount. 
4. See screenshots

Also, this is how the page looks when I click on Get Tickets in the sustain collective
https://opencollective.com/sustainoss/events/sustain-2020-summit-442ev
<img width="771" alt="Screen Shot 2019-10-03 at 4 46 26 PM" src="https://user-images.githubusercontent.com/3671070/66137441-62e25f00-e5fd-11e9-98c8-c4a42aa24e2e.png">

EDIT: removed reference to console errors

**Comment by piamancini** [comment]
In tinckering with it some more I realized that when the event is created as separate collective: https://opencollective.com/sustainoss/events/sustain-2020-summit-442ev#tickets The ticket shows up correctly. 

<img width="1217" alt="Screen Shot 2019-10-03 at 4 42 18 PM" src="https://user-images.githubusercontent.com/3671070/66137064-cf109300-e5fc-11e9-82ed-306b3a268ce0.png">
However, I can no longer edit it even if I am an admin:

**Comment by znarf** [comment]
If it's not a ticket, it should not appear as a ticket.

This whole thing is buggy and should be migrated to the new Contribution Flow.

**Comment by contraexemplo** [comment]
I was testing this feature today and noticed that the **Available quantity** field counter does this:
![Peek 2019-11-22 18-35](https://user-images.githubusercontent.com/29989176/69462334-76858880-0d57-11ea-9f1c-799dcbf07f74.gif)
If an user adds those quantities by accident the platform tells them there's something wrong, so it's something small that doesn't warrant an issue of its own. But it's a mistake that can be reproduced so easily (by scrolling down the page) I thought it would be a good idea to report it here.

**Comment by znarf** [comment]
We don't feature/support this widget anymore since we moved to the new collective page.
