### ISSUE TITLE
contributions cards getting switched

### ISSUE THREAD

**Issue by maddhruv** [opencollective/opencollective#2497]
**Describe the bug**
The cards (Open Collective Design and Open Collective Engineering) at https://opencollective.com/opencollectiveinc switch the title after a split of second on page render. Even the link is also getting switched weirdly.

Note: You won't see this behaviour if you navigate to some link on this page and come back (`window.history.back()`)

**To Reproduce**
1. Go to 'https://opencollective.com/opencollectiveinc'
2. Check the Contributions section
3. Check the `Design` and `Engineering` cards
4. See the switching behaviour

**Comment by Betree** [comment]
Good catch, there's seems to be a difference in contributions sorting between SSR and client.

![Peek 04-10-2019 11-39](https://user-images.githubusercontent.com/1556356/66198015-d33fbd80-e69b-11e9-9017-68ad30701fab.gif)

**Comment by maddhruv** [comment]
But for you, it is switching different cards, and different for me
