### ISSUE TITLE
Text color is not working in WYSIWYG editor in standalone tiers

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2498]
**To Reproduce**

1. Go to a standalone tier and use the rich editor.
1. Select a color other than black for the text
1. Save.

**Current Behavior**

Color is reverted to default (black)

**Comment by Betree** [comment]
@piamancini The editor that we've selected with the design team as the best candidate so far to replace the one we have is https://yabwe.github.io/medium-editor/ (you can try a live demo from the website).

It has a great UX experience, but no support for changing text color (though it would possible to achieve with some more development).

Would you say that text color picking is a required/important feature?

**Comment by someofthethings** [comment]
I've seen this before with Angular. It seems to be part of some underlying HTML behavior.

**Comment by Betree** [comment]
@piamancini The new editor implemented in https://github.com/opencollective/opencollective-frontend/pull/2782 (PR includes a preview GIF) doesn't support it.

**Comment by Betree** [comment]
Latest editor doesn't support colors anymore. I personally think it's a good design decision, but feel free to open another issue we you think we should implement it.
