### ISSUE TITLE
GiftCard: Show actual contributor name in new backer email

### ISSUE THREAD

**Issue by flickz** [opencollective/opencollective#2499]
#### Description

While working on #2491 I noticed the email sent to collective admin about new backer shows name of gift card issuer rather than the person who donated to the collective with it.

<img width="511" alt="Screenshot 2019-10-03 at 3 48 38 PM" src="https://user-images.githubusercontent.com/15707013/66209598-97aeee80-e6af-11e9-8a5e-42d450f76e29.png">

#### Email screenshot

<img width="666" alt="Screenshot 2019-10-04 at 1 42 55 PM" src="https://user-images.githubusercontent.com/15707013/66209693-d8a70300-e6af-11e9-8a78-6454f30671b3.png">

**Comment by piamancini** [comment]
good catch

**Comment by flickz** [comment]
@piamancini So I investigated this and found out two emails were sent (gift card user and issuer), the gift card issuer was added as a backer too. is this the expected behaviour?

**Comment by znarf** [comment]
Yes, it is not the ideal behavior but this is known and expected.

**Comment by flickz** [comment]
Okay, I can close this issue then.
