### ISSUE TITLE
User submitted tax form but the system thinks they haven't

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2501]
Please see the comments in this expense: https://opencollective.com/gosublime/expenses/10024

The user submitted the tax form via HelloWorks, but the system has not recorded it. In Forest the legal document shows as "requested" not "received". They can't resubmit it because HelloWorks says they already did it when they try again.

**Comment by znarf** [comment]
@alanna I answered to that on Slack long time ago when it was mentioned.

**Comment by alanna** [comment]
OK @znarf what was the answer? I can't find that message.

**Comment by znarf** [comment]
@alanna According to https://github.com/opencollective/opencollective/issues/2540, looks like you found the message.

Closing this issue then, we will track in the other issue.
