### ISSUE TITLE
Better rich text editor

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2508]
If tackled, this issue will resolve https://github.com/opencollective/opencollective/issues/2498
Also related to https://github.com/opencollective/opencollective/issues/1805

---

We're not happy with our current `HTMLEditor`, based on `react-quill`.

Here are some drawbacks that we have with it:
- The content is not formatted like the final result (WYSIWYG). That's a real blocker.
- There's a glitch with some tooltips that gets hidden
- No nested lists (https://github.com/quilljs/quill/issues/979)
- The interface is too complex overall

I've done some testing and picked two possible libraries to replace `react-quill`:
- https://github.com/yabwe/medium-editor: favorite of the design team. Great UX, but requires a plugin to support lists. No "good" react wrapper.
- https://trix-editor.org/: Backed by Basecamp. Maintained. Feels a bit "old UI", but it woks. Poor responsiveness.

I'll try to have a replacement component this week. If anyone has suggestions or experience with one of this two libraries, feel free to comment on the issue :point_down:

**Comment by someofthethings** [comment]
This seems a complex issue. Is it covered by your bounty program?

**Comment by Betree** [comment]
@someofthethings It's not, bounty issues have the `bounty` label attached.

**Comment by someofthethings** [comment]
I won't be paying attention to this one then

**Comment by Betree** [comment]
After testing implementations for both libraries, I made the final choice to use https://github.com/basecamp/trix for the following reasons:
- Trix provides all the features that we need out of the box
- Trix has FAR less open issues and seems overly more maintainer
- Basecamp (the company behind Trix) has a strong reputation in the dev world
- `medium-editor` required the addition of at least 3 plugins to do what we wanted
- Among the plugins required by `medium-editor`, some where very dirty and included crazy amount of third-parties (including JQuery)  

---

Demo:

![Peek 08-10-2019 17-32](https://user-images.githubusercontent.com/1556356/66410033-b97edd00-e9f1-11e9-9032-a95aad724a07.gif)

Also added support for nested lists:

![image](https://user-images.githubusercontent.com/1556356/66408782-df0ae700-e9ef-11e9-9b67-09ea23bdc688.png)
