### ISSUE TITLE
Logos and header images are wrong in contribution list cards

### ISSUE THREAD

**Issue by kof** [opencollective/opencollective#2509]
**Describe the bug**
I see in a users contributions list cards 2 projects, JSS and styled-components and they have somehow exchanged the logo and header image. JSS card has styled-components logo and header image and vise-versa, see the screenshot

**To Reproduce**
1. Go to https://opencollective.com/thomas-gorny

**Screenshots**
<img width="1335" alt="Screenshot 2019-10-08 at 11 18 14" src="https://user-images.githubusercontent.com/52824/66383486-612de800-e9bd-11e9-9791-8d2330b21d91.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome 
 - Version 77.0.3865.90

**Comment by znarf** [comment]
We'll investigate. It's gonna be a bit difficult without steps to reproduce.

**Comment by kof** [comment]
it looks correct already, there are no steps just the link, closing, since it's not reproducibel any more
