### ISSUE TITLE
Ability to set event timezone

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2512]
## User story 

When creating an event, I can't set or edit the event timezone. The property exists in the API/database and is actively used. The timezone is currently guessed from the user environment and not editable.

## Best solution for this problem

Add a timezone picker in the create and edit forms. Default to the the user timezone or collective timezone.

**Comment by piamancini** [comment]
yes!  100% also referenced https://github.com/opencollective/opencollective/issues/2159

**Comment by znarf** [comment]
@piamancini We're actually working on https://github.com/opencollective/opencollective/issues/2159. This is when testing the fix that I realized timezone was not editable.

**Comment by leonardohof** [comment]
@znarf Can I work on this?

**Comment by znarf** [comment]
@leonardohof sure

**Comment by someofthethings** [comment]
Timekeeping certainly seems a _general catalyst_ for syncronisation of mutual renumerations...

**Comment by leonardohof** [comment]
@znarf Hi! What is missing to close the issue? Is missing something from my side?

**Comment by znarf** [comment]
🏆 This issue was completed by @leonardohof  as part as our first Hackathon.

To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
