### ISSUE TITLE
Project renamed, unable to get contributors!

### ISSUE THREAD

**Issue by viest** [opencollective/opencollective#2515]
### My collective:

https://opencollective.com/php-ext-xlswriter

### Github project:

https://github.com/viest/php-ext-xlswriter

### All contributors url:

https://opencollective.com/php-ext-xlswriter/members/all.json

The contributors I get are only myself, there are no other members, which is very strange.

**Comment by flickz** [comment]
@viest Can you provide more information regarding this issue?

**Comment by viest** [comment]
I created a group after modifying the git repository name.

Old git repository name: https://github.com/viest/php-ext-excel-export

**Comment by znarf** [comment]
@viest members returned by the API are only the contributors on Open Collective, ie: core contributors, financial contributors. So this looks correct.

**Comment by viest** [comment]
@znarf  How can I get a list of commit contributors that I didn't find in the documentation?

Https://github.com/viest/php-ext-xlswriter/graphs/contributors

**Comment by znarf** [comment]
@viest Use the GitHub API?
