### ISSUE TITLE
Deleted events show up in Contributions

### ISSUE THREAD

**Issue by maddhruv** [opencollective/opencollective#2516]
**Describe the bug**
Events which are deleted/don't exist show up in the contributions section for a collective.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://opencollective.com/maddhruv
2. Click on any `event` card in the contributions section
3. The page says - `Ooops, an unexpected error seems to have occurred  🤕` which is because the event actually doesn't exist anymore - as I deleted the collective which was hosting the event.

**Expected behaviour**
The archived/deleted events should not show up here

**Screenshots**
<img width="924" alt="Screenshot 2019-10-10 at 19 52 18" src="https://user-images.githubusercontent.com/18121502/66577748-85ddb780-eb97-11e9-919f-0d9f3d22c294.png">

**Comment by Betree** [comment]
Crash is now prevented, and the policy for events deletion has been reviewed:
- Preventing Deletion of Collective with Events opencollective/opencollective#2577
