### ISSUE TITLE
contributors.svg doesn't work

### ISSUE THREAD

**Issue by panjf2000** [opencollective/opencollective#2517]
Hi,
I am reporting that the contributors.svg of my GitHub repositories doesn't work, returning "Not found".

https://opencollective.com/ants/contributors.svg

https://opencollective.com/gnet/contributors.svg

**Comment by someofthethings** [comment]
Have you tried with opencollective.fun.max.important? There seems to be various limits that vary between integer, double and float.

**Comment by panjf2000** [comment]
@someofthethings 
Sorry I don't quite get it when you said "tried with opencollective.fun.max.important", how should I try it?

**Comment by Betree** [comment]
Sorry @panjf200, `someofthethings` seems to be trolling. We'll look at your issue as soon as possible

**Comment by panjf2000** [comment]
Any update?

**Comment by panjf2000** [comment]
@Betree 
Is anyone working on this issue?

**Comment by znarf** [comment]
@panjf2000 It can take some time to be populated. We need to revamp that script so it performs better. https://github.com/opencollective/opencollective-api/tree/master/cron/daily

**Comment by sobolevn** [comment]
Just an update, that my collective contributors graph has not updated in (almost) a week.
Here are the links:
- README: https://github.com/wemake-services/wemake-python-styleguide#contributing (showing 53)
- Contributors: https://github.com/wemake-services/wemake-python-styleguide/graphs/contributors (showing 61)
- OpenCollective page: https://opencollective.com/wemake-python-styleguide

Any help is appreciated.
