### ISSUE TITLE
Do not show expenses requiring tax form in 'ready to pay'

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2521]
## User story 
As a host admin, I want 'ready to pay' to show only expenses that are actually able to be paid now, so I can easily see if I've completed all the transactions needed.

## Best solution for this problem
Hide expenses pending tax forms from the 'ready to pay' dashboard filter.

![Screen Shot 2019-10-14 at 10 55 18 AM](https://user-images.githubusercontent.com/5498878/66723057-2fab9580-ee71-11e9-8b9e-cc047af43036.png)

**Comment by jeffin143** [comment]
@alanna  How to land up on this page , I mean when I try to view the expenses, options are there as : 

` Approved | engineering | edit | close `

There isn't a filter button on expenses page 

How to bring the option for tax form required , or the filter page
Could you please point me to the location where the segregations is done :)

**Comment by alanna** [comment]
It's a filter on the fiscal host dashboard

**Comment by aunnop739** [comment]
#2521

**Comment by Betree** [comment]
Hi @jeffin143, I believe that we don't have clear instructions in the docs about how to test and dev for this part right now. We need to write them (I'll follow up with that) but in the mean time I'd recommend you to not work on this issue so you don't loose time searching for things that are not properly documented :-)

@znarf do we have a page in docs about `Testing features` where we could provide such instructions?

**Comment by jeffin143** [comment]
> Hi @jeffin143, I believe that we don't have clear instructions in the docs about how to test and dev for this part right now. We need to write them (I'll follow up with that) but in the mean time I'd recommend you to not work on this issue so you don't loose time searching for things that are not properly documented :-)

Thanks @Betree :)

**Comment by flickz** [comment]
@znarf The issue is closed or are we reopening?

**Comment by znarf** [comment]
It's closed, was just assigning you for internal statistics purpose.

**Comment by flickz** [comment]
Okay.
