### ISSUE TITLE
Need to manually add funds to event

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2525]
## User story 
As a fiscal host admin, I need to be able to attribute sponsorship funds received outside the platform to a specific event. The current manually add funds interface only allows you to select Collectives. ([Support ticket example](https://opencollective.freshdesk.com/a/tickets/2284)). Often sponsors are sponsoring a specific event not the hosting Collective.

## Best solution for this problem
"Add funds" button visible to host admins on event pages, similar to the button we have for Organization pages now.

It doesn't seem like a good idea to clutter the already cluttered Collectives dropdown on the host dashboard with events. Really events should not be seperate Collectives, but treated as tiers or some other approach that fixes all these issues with having them as standalone Collectives. (See #2081).

**Comment by xdamman** [comment]
I discussed this with @Betree. We could use the newly developed Collective Picker in the « Add Funds » form and allow for the selection of collectives of type « EVENT ».

**Comment by Betree** [comment]
I can confirm that this will be resolved when we deploy the new collective picker for host dashboard (hopefully before the end of the week):

![Peek 16-10-2019 17-23](https://user-images.githubusercontent.com/1556356/66933671-b57a3d00-f039-11e9-8104-9954347513e8.gif)

**Comment by alanna** [comment]
Great!

**Comment by bodhi1970** [comment]
I am not a fiscal host but admin for a collective and I want to add funds from the main account to an event. We had surplus from an event last year that I transfered to the main account but now I can't find a way to add that to the new Event.

**Comment by znarf** [comment]
@bodhi1970 Normally you should be able to "Contribute" (like when doing a credit card contribution) to the new Event using the other account balance. Do you see this option?
