### ISSUE TITLE
GraphQL error when updating bank transfer details

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2526]
I tried to use the new 'add wire transfer details' feature, and saw there was already info in there for Open Source Collective. I made some small edits and clicked "save" but got the error `GraphQL error: Parent collective with id 17403 not found`.

![Screen Shot 2019-10-16 at 11 14 38 AM](https://user-images.githubusercontent.com/5498878/66873989-5b13b900-f006-11e9-9b9c-7263968ee88f.png)

**Comment by alanna** [comment]
Same thing when I tried to update the details for Foundation: `GraphQL error: Parent collective with id 17403 not found`

**Comment by znarf** [comment]
@xdamman @alanna Is that solved?

**Comment by alanna** [comment]
Yes it appears to be fixed now.
