### ISSUE TITLE
Don't require to connect a Stripe account to become a host

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2528]
Since we just introduced the ability for a host to accept donations manually by bank transfer (see https://github.com/opencollective/opencollective-frontend/pull/2757), having a stripe account shouldn't be a requirement to be a host on open collective anymore.

The way we compute `Collective.isHost` is correct: https://github.com/opencollective/opencollective-api/blob/02fcfff24bdd17f3cedb839c04bdd0c2a7ad89bb/server/models/Collective.js#L2054

However, when we select a host for a collective, the interface requires us to connect a Stripe account:
![](https://d.pr/free/i/vlKnGw+)

Instead, that section should read:
**Payment Methods**
Add at least one payment method to start collecting money on that host on behalf of your collective
[ add a payment method ]

This should link to the new updated edit payment methods of the user or organization that is acting as a host.

**Comment by znarf** [comment]
This is being fixed.

**Comment by piamancini** [comment]
@znarf we can close this one was we make this change.
