### ISSUE TITLE
Onclick Menu icon in mobile view redirects to footer instead of menu bar elements

### ISSUE THREAD

**Issue by dinolinjob** [opencollective/opencollective#2529]
**Describe the bug**
On clicking the menu icon in mobile view, it redirects to footer.

**To Reproduce**
1. Go [https://opencollective.com/](https://opencollective.com/) in mobile view.
2. Click on 'Menu Icon  ☰'
3.  It gets redirected to [#footer](https://opencollective.com/#footer)

**Comment by dinolinjob** [comment]
@Betree Can I work on this?

**Comment by Betree** [comment]
@dinolinjob This isn't a bug so to speak, we never implemented a real mobile navigation for this menu. Let's not rush on that without a proper design because it could look strange with the mobile menu that we have on the collective page (see https://opencollective.com/babel/ on mobile).

**Comment by dinolinjob** [comment]
okay..cool @Betree

**Comment by Betree** [comment]
Will be resolved by https://github.com/opencollective/opencollective/issues/3009

**Comment by Betree** [comment]
Resolved by https://github.com/opencollective/opencollective-frontend/pull/4812
