### ISSUE TITLE
Adapt the general website Header items based on current page (menu/navbar)

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2530]
Following up on https://github.com/opencollective/opencollective/issues/2228#issue-466280440 and considering https://github.com/opencollective/opencollective/issues/2529

We show a lot of options in the top menu bar / navbar, which turns out in two problems:

1. Display issues on medium screen sizes:

![image](https://user-images.githubusercontent.com/1556356/66995480-5ff06f80-f0cf-11e9-91b4-e37703a1e122.png)

2. Options are sometimes unrelated to the current page and can distract users. For example on https://opencollective.com/babel/donate/ pricing has noting to do here and can actually turn users out of the contribution flow.

![image](https://user-images.githubusercontent.com/1556356/66995574-8a422d00-f0cf-11e9-88a4-8e0f36d31d1d.png)

## Proposed solution

- Always display `Discover` and `Docs & Help`
- `How it works` and `Pricing` pages are targeted toward (future) collective admins, not financial contributors. They should only appear on:
  - Homepage
  - `/create`
  - `/how-it-works`
  - `/pricing`

**Technical details**
`Header` and `Page` components should accept a `menuItems` flag map that will be passed in the pages listed above:
```es6
{
    howItWorks: true,
    pricing: true
}
```

This map should be merged on the default:
```es6
{
    discover: true,
    docs: true,
    howItWorks: false,
    pricing: false
}
```

**Comment by jeffin143** [comment]
@Betree why map , and why not props
```
class TopBar extends React.Component {
  static propTypes = {
    className: PropTypes.string,
    loadingLoggedInUser: PropTypes.bool,
    showSearch: PropTypes.bool,
    Discover : PropTypes.bool
     Somethingelse : PropTpes.bool
    .
  };

  static defaultProps = {
    className: '',
    showSearch: true,
     Discover : true
     Other option : true
     And then : true
  };

```

And then just add

```
{ discover && (
             <NavLinkContainer>
                <Link route="discover" passHref>
                  <NavLink>
                    <FormattedMessage id="menu.discover" defaultMessage="Discover" />
                  </NavLink>
                </Link>
              </NavLinkContainer>
```


This way I don't have to handle the map, merge them or append the values , I guess this could be simple unless you have something in your mind ( which I guess is there ) :)

**Comment by Betree** [comment]
@jeffin143 Having the fields in props (without using a map) works just as well. I prefer the first approach because it doesn't require any update to `Page` if we add a new field to `menuItems` (we'll just pass down the map, not the individual items) and we don't duplicate prop types.

So my rational is to avoid repetition.

But that's a personal preference, so a different solution wouldn't be a blocker :-)

**Comment by jeffin143** [comment]
> I prefer the first approach because it doesn't require any update to `Page` if we add a new field to Header's `menuItems` (we'll just pass down the map, not the individual items) and we don't duplicate prop types.

Sorry I didnt't uderstand what do you mean by `page`, is it homePage ?

The menu is in header right ?

**Comment by Betree** [comment]
@jeffin143 I meant the `Page` component (https://github.com/opencollective/opencollective-frontend/blob/8a3903d8de5328632f30f3107b83d7ff40de847d/components/Page.js#L16) that most pages use to wrap all the layout (rather than using `Header` directly)

**Comment by jeffin143** [comment]
@Betree anything left to handle here ?

**Comment by Betree** [comment]
@jeffin143 All good!

Solved in https://github.com/opencollective/opencollective-frontend/pull/2870
