### ISSUE TITLE
Tax form emails not being sent

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2537]
We've had an uptick in reports of users not getting the email from HelloWorks. Normally we ask users to search their spam, etc, but recently there have been a few expenses where I can't see the email going out in the HelloWorks dashboard, so I suspect something is going wrong. There hasn't been an email sent from HelloWorks since Oct 8, and 10 days would be an unusually long gap.

Here are expenses where the user reports no tax email received:

* https://opencollective.com/redux-saga/expenses/10859
* https://opencollective.com/preact/expenses/10749

These should be showing up as outgoing on the HelloWorks dashboard, but they aren't. If the user simply missed the email it would show as 'pending'. These both should have gone out in the last week.

![Screen Shot 2019-10-18 at 10 41 18 AM](https://user-images.githubusercontent.com/5498878/67049958-e9697580-f193-11e9-9edd-72a5bbe4d02e.png)

**Comment by znarf** [comment]
Seems there is an issue in the daily cronjob execution, not the tax form script itself.
