### ISSUE TITLE
Paid expenses reverted to pending

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2539]
Core contributor reports that a bunch of previously paid expenses on his Collective had reverted to pending status.

Can these be checked please to make sure all previously paid expenses are marked as paid? We should make sure this isn't affecting any other Collectives. Did these changes trigger notifications?

https://opencollective.com/bower/expenses

https://opencollective.freshdesk.com/a/tickets/2377

**Comment by Betree** [comment]
From what I see in the history the first one was never marked  as paid

![image](https://user-images.githubusercontent.com/1556356/67060982-1f403700-f15f-11e9-8310-4f9fde9a9d2d.png)

**Comment by alanna** [comment]
The user said

> I've received money at least for $2250 withdrawal.

I will check with Alina to see if she might have forgot to mark as paid.

**Comment by alanna** [comment]
I have confirmed this was in fact paid via Paypal on 10/03/2019 - I can see it in the paypal log. However, I don't see an "expense paid" email notification going out, so that makes me think it was not actually ever marked as paid. Still doesn't explain why it's pending now.

![Screen Shot 2019-10-18 at 4 09 27 PM](https://user-images.githubusercontent.com/5498878/67063022-ade5a000-f1c1-11e9-856b-6c57b67016be.png)

@Betree can you look at the other transactions that are now pending? Were they previously approved or paid?

**Comment by znarf** [comment]
**According to the database entries**, all expenses "Rails-assets.org hosting (compute & file store)" from `6891` to `6898` were never approved or paid, their status never changed from pending.

**Comment by znarf** [comment]
For the https://opencollective.com/bower/expenses/10376 one, I think the most likely is a human error when paying the expense, clicking "Unapprove" instead of "Record as paid"

**Comment by flickz** [comment]
> I think the most likely is a human error when paying the expense, clicking "Unapprove" instead of "Record as paid"

I'm going to add a confirmation modal to prevent this from occurring next time.

**Comment by znarf** [comment]
@flickz It's just a theory at this stage. But good idea any way.

**Comment by alanna** [comment]
Ah! That could have been it. I will ask Alina.

**Comment by alanna** [comment]
@Betree says

> "Mark as unpaid" and "Unapprove" buttons were deployed on last Thursday (October 17th). Update for these expenses were older than that.

**Comment by znarf** [comment]
@alanna the modification was effectively done by Alina on October 3d, so I agree that it's not coming from the "Unapprove" button (which was not there).

From the data I have, the expense was edited by Alina to change the payout method from "paypal" to "other". At this time, it went from "Approved" to "Pending".

It was never edited again until we start caring about this issue. Let me know if you see some follow up needed.

**Comment by alanna** [comment]
OK, let's consider this closed. I've informed the user.
