### ISSUE TITLE
Use of localStorage crashes Chrome when cookies aren't whitelisted

### ISSUE THREAD

**Issue by Krinkle** [opencollective/opencollective#2542]
**Describe the bug**

When I open <https://opencollective.com/eslint>, I very briefly see the page. It then flashes to white with the browser tab spinning forever. If I leave it like this for too long, I have to force quite the browser tab via Chrome's "Task Manager".

I suspect this is due to an **infinite loop** where part of the code handling the problem itself tries to use localStorage. I see in the bottom-left corner that it tries it is accessing `sentry.io` many times in row. 

**To Reproduce**
1. Use the current stable version of Chrome .
2. Open Settings > Advanced > Site settings > Untick "Allow sites to save and read cookie data". 
3. Open <https://opencollective.com/eslint>
4. Observe the above problem.

**Expected behavior**

For users to be able to at least browse pages on <https://opencollective.com> without demanding that information about them or from your website is permanently stored on their computer. I'm well aware that many features may require cookies, that's no problem. I have a separate browser profile with limited expiry and no such restriction in which I browse such websites. I would like however to be able to at least navigate and peruse websites like <https://opencollective.com> in my main browser. If I have to whitelist this website in order to sign in or may payments, or do so through my other browser profile, that would be totally fine.

**Screenshots**

| <img width="691" alt="1" src="https://user-images.githubusercontent.com/156867/67149818-c7611780-f2a7-11e9-9337-a7ba545702ac.png"> | <img width="1244" alt="2" src="https://user-images.githubusercontent.com/156867/67149819-c7611780-f2a7-11e9-816a-006481cd7699.png">
|--|--
| <img width="925" alt="3" src="https://user-images.githubusercontent.com/156867/67149820-c7f9ae00-f2a7-11e9-9781-de66379c22f8.png"> | <img width="717" alt="4" src="https://user-images.githubusercontent.com/156867/67149821-c7f9ae00-f2a7-11e9-87b6-4082c446cca7.png">

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version: 77

**Additional context**

I believe this is related to https://github.com/opencollective/opencollective-frontend/pull/2642 which attempted to fix a similar issue, but didn't quite get it. It's pretty rare in modern browsers for `localStorage` to be null (even in search engines, cookie-restriction modes, or private browsing modes). Rather, the object tends to exist but throw on access.

**Comment by richport** [comment]
you need to give chrome permission to work ,or your running It while in
roaming..
also u could clear ur storage..try the chromium projects..it's alot bettrr
