### ISSUE TITLE
Adding funds manually to an event triggers a ticket registration

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2545]
As per #2525 we can now manually add funds to an event, which is mainly used for sponsorship coming in via invoice and bank transfer. I did it for the first time today and realised it's erroneously treating that contribution as a ticket sale, which doesn't make sense for sponsorship. This triggers a confusing email notification (below) and will mess up the attendee list for the event for the organisers.

![Screen Shot 2019-10-21 at 10 28 54 AM](https://user-images.githubusercontent.com/5498878/67166646-bde1c780-f3ed-11e9-82d2-928777ef1436.png)

**Comment by znarf** [comment]
Duplicate with https://github.com/opencollective/opencollective/issues/2891 and fixed.
