### ISSUE TITLE
Tax form not triggered for user when it should have been

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2546]
**Describe the bug**
The tax form notification is supposed to be triggered when a user crosses $600 in invoices. But [this user](https://opencollective.com/isiahmeadows1) has submitted $1000 in invoice expenses and did not get asked to fill out the tax form. Looking in Forest, it seems our system has not identified it as 'required' in this case (no entry for legal document).

**Expected behavior**
"Tax form required" should have triggered when he submitted the second $500 expense.

**Comment by znarf** [comment]
@alanna What's the difference with this issue which is being fixed https://github.com/opencollective/opencollective/issues/2537? Can it be the same?

**Comment by alanna** [comment]
@znarf you only specified 4 affected users for the delayed notifications in that other issue, and this user is not one of them.

**Comment by alanna** [comment]
@znarf - any update about whether this was part of the other issue with the delayed emails, or a seperate thing?

**Comment by znarf** [comment]
@alanna one of the expenses is classified as receipt, not invoice. This is the reason.

**Comment by alanna** [comment]
Thanks @znarf

**Comment by alanna** [comment]
Ah, in that case can you please update them both to invoice type, since that's the correct classification? I have no way to do that myself.

**Comment by alanna** [comment]
@znarf can you please update the expense to invoice type and make sure the tax form gets triggered for this user?

**Comment by znarf** [comment]
Done.
