### ISSUE TITLE
Improve the way update's summaries are generated

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2547]
We have several issues in the way updates summaries are generated ([here](https://github.com/opencollective/opencollective-api/blob/88ff9e6ac3badcf3e9a07dbef4fe2531febcdbc0/server/graphql/v1/types.js#L877)):
- If the update doesn't start with `<p>`, we return an empty string. This is going to be a problem when we'll introduce the new rich text editor because it uses a `<div>` to wrap the content.
- We only take the first paragraph, which can be a very short string
- Content is sanitized in the resolver, thus the function has a cost at each request

## Proposed change

- Add a `summary` column to the DB
- In the migration, generate all summaries for existing updates
- In the model, when saving `html` content, generate the summary
- Use `sanitize-html` to remove everything we don't want (`<br/>`, `<p/>`...)

**Comment by bolariin** [comment]
How should summaries be generated for the updates? Should it be similar to what was done in https://github.com/opencollective/opencollective-api/blob/88ff9e6ac3badcf3e9a07dbef4fe2531febcdbc0/server/graphql/v1/types.js#L848-L851

**Comment by Betree** [comment]
We're moving out of markdown for these descriptions. 

I'd say we should mimic what was done for conversation, using the `generateSummaryForHTML` helper: https://github.com/opencollective/opencollective-api/blob/1d509a0a3e63ce239f1887166ebf049b110bea4d/server/models/Conversation.js#L45
