### ISSUE TITLE
Add modal confirmation for Unapprove button.

### ISSUE THREAD

**Issue by flickz** [opencollective/opencollective#2548]
In the host dashboard, we recently added an [Unapprove](https://github.com/opencollective/opencollective-frontend/pull/2783) button for expense. 

There are several buttons for expense within the dashboard, it's easy to use the wrong button unconsciously, like what could have happened in https://github.com/opencollective/opencollective/issues/2539#issuecomment-544446419. Having a confirmation modal could have prevented that.

**Comment by znarf** [comment]
Would be great to take the opportunity to refactor the modal, we have already too many copy/paste for that in the codebase.
