### ISSUE TITLE
Should we have a dedicated image for Organization's logos in widgets?

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2550]
## Description

Topic was brought up in https://opencollective.freshdesk.com/a/tickets/2417

Some users/orgs like [Triplebyte](https://opencollective.com/triplebyte/) have a legacy **rectangular** avatar. Today someone who wanted to do the same did not understand why they were limited to a **square** avatar.

---
![image](https://user-images.githubusercontent.com/1556356/67314358-d395e080-f504-11e9-86f4-b73dd3fd1ef2.png)
---

The reason is that we enforced stricter rules for the avatar with the release of the new collective page:
- Must be square
- Will always be shown on a white background

## Proposal

We should try to address this disparity. I see two possible solutions:

1. Enforce that logos will be squares in widgets too, in that case we should contact the organizations not matching the criteria to ask them if they can upload a new logo. **Some organizations may not like this option** and will probably not make the update.

2. In `/edit/images` for organizations add a field to set a different image for widgets that will only be used there and doesn't set any constraint for the image ratio.

**Comment by github-xiaogang** [comment]
I uploaded a new logo few minutes ago, but it seems not update, is this a bug?

NEW LOGO should be:
![image](https://user-images.githubusercontent.com/4679072/67316243-aa904280-f53a-11e9-818d-29c1a5aba273.png)

LOGO link in repo (I got from the README raw text mode):
https://opencollective.com/kingfisher/sponsor/1/avatar.svg

it seems always refer to the old one, is it has a cache?

**Comment by piamancini** [comment]
@github-xiaogang yes, the cache from github is quite heavy. It might take a while longer.

**Comment by github-xiaogang** [comment]
@piamancini I mean that the image in https://opencollective.com/kingfisher/sponsor/1/avatar.svg is still the old one, this should be your site's cache problem, not github

**Comment by Betree** [comment]
@github-xiaogang The cache is now refreshed for this image https://opencollective.com/kingfisher/sponsor/1/avatar.svg. As mentioned in private message, please send following support requests to `support@opencollective.com` - this issue is about discussing the possibility of having a specific image dedicated to the sponsor widget.

**Comment by Betree** [comment]
Related request today in https://opencollective.freshdesk.com/a/tickets/3111 to have a dedicated image for link preview when sharing on Twitter, Facebook...etc (opengraph)

**Comment by Betree** [comment]
Closing in favor of https://github.com/opencollective/opencollective/issues/2660
