### ISSUE TITLE
"New backer" email sent repeatadly for same contributor on the 1st of each month

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2551]
**Describe the bug**
ESLint admins receive the same `New backer` email for Triplebyte on the 1st of every month.

It's unclear right now what happens, but this could be related to the fact that a lot of people contributed to ESLint via one of the numerous gift cards  that TripleByte emitted.

**To Reproduce**
*Needs steps*

**Expected behavior**
Should only send the "New Backer" when creating the membership.

**Screenshots**
![image](https://user-images.githubusercontent.com/1556356/67396351-b5cd8780-f5a7-11e9-96e9-49b2345221f5.png)

**Additional context**
https://opencollective.freshdesk.com/a/tickets/2419

**Comment by znarf** [comment]
We want to kill this email (gift card issuer as backer) to avoid various problems. It's a bit tricky though.

**Comment by znarf** [comment]
PR: https://github.com/opencollective/opencollective-api/pull/2790
Follow Up issue: https://github.com/opencollective/opencollective/issues/1482
