### ISSUE TITLE
HostDashboard: Improve E2E tests

### ISSUE THREAD

**Issue by flickz** [opencollective/opencollective#2553]
The host dashboard currently lacks a good e2e test coverage compare to other important pages within the code base, we're constantly adding new features and enhancements but no e2e tests. The following functionalities need test:

Test file - https://github.com/opencollective/opencollective-frontend/blob/master/test/cypress/integration/29-host.dashboard.js

- Approve and reject expense
<img width="394" alt="Screenshot 2019-10-23 at 9 28 39 PM" src="https://user-images.githubusercontent.com/15707013/67431426-29898780-f5dc-11e9-838a-09a0bf10aaec.png">

-  Mark expense unpaid
<img width="372" alt="Screenshot 2019-10-23 at 9 31 23 PM" src="https://user-images.githubusercontent.com/15707013/67431611-8edd7880-f5dc-11e9-9c30-978a5d5aab32.png">

- Record expense as paid
<img width="401" alt="Screenshot 2019-10-23 at 9 39 50 PM" src="https://user-images.githubusercontent.com/15707013/67432201-bda81e80-f5dd-11e9-8147-a3c95ea52b8e.png">

- Navigate to pending application tab and approve an application
<img width="446" alt="Screenshot 2019-10-23 at 9 41 35 PM" src="https://user-images.githubusercontent.com/15707013/67432318-f9db7f00-f5dd-11e9-80a2-b55c426c6f73.png">

**Comment by Betree** [comment]
+1 for this one, good initiative.

Would indeed be a great bounty candidate but we need to write some documentation about testing the host dashboard first. It's currently difficult to give instructions to contributors about how the should test this dashboard (should the create a new host? hack a membership in their local DB?).

**Comment by sbinlondon** [comment]
This one looks interesting. Once you've figured out some of the documentation I'd be up for doing it to get more experience with E2E testing. However, I'm aware that I've already done a bounty involving Cypress and I think you mentioned you wanted to spread those around a bit to different contributors. Just let me know what you think 😊

**Comment by Betree** [comment]
> However, I'm aware that I've already done a bounty involving Cypress and I think you mentioned you wanted to spread those around a bit to different contributors. 

We wanted to spread the bounties to get different perspectives and see what we could improve. Thanks to the great feedback everyone provided on the PRs and on #2531 I think that we now have a better understanding of what we need to improve so I'd be comfortable assigning new Cypress issues to recurring contributors :slightly_smiling_face:

**Comment by sbinlondon** [comment]
Cool 😎 Would you like me to have a go at it, or wait for more info/docs as mentioned in your first comment @Betree?

**Comment by Betree** [comment]
@sbinlondon If you're interested in it feel free to start! Don't hesitate to ask questions (on Slack #engeenirring  or here) for everything that seems unclear so that we have a better feeling of what we need to document in the process.

**Comment by sbinlondon** [comment]
Same comment as my other issue: moved house, not had internet/time to work on things but more settled in and will be able to work on it this week 😊

**Comment by sbinlondon** [comment]
Progress:

- [ ] Approve/reject expense
- [ ] Mark expense unpaid
- [x] Record expense as unpaid 
- [x] Navigate to pending and approve application

**Comment by Betree** [comment]
Resolved by @sbinlondon  in https://github.com/opencollective/opencollective-frontend/pull/2977

**Comment by znarf** [comment]
🏆 This issue was completed by @sbinlondon

To thank you for the quality work, I retroactively added a $200 bounty on it. To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
