### ISSUE TITLE
Transfer funds from event to collective broken

### ISSUE THREAD

**Issue by sebsheep** [opencollective/opencollective#2555]
**Describe the bug**
When I'm clicking on the "Transférer 84.55€ à Elm France" button, nothing happens.

![image](https://user-images.githubusercontent.com/6839698/67474015-06022380-f654-11e9-9a9a-3c5667a8e104.png)

(I'm logged in as "Sébastien Besnier", administrator of Elm France, the url is https://opencollective.com/elm-france/events/hackathon-elm-france-50136ev).

**Expected behavior**
Huuuuuum the money is transfered to the collective?

**Desktop (please complete the following information):**
 - OS: Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
 - Browser: Firefox 69.0.3 & Chromium 73.0.3683.75

**Comment by znarf** [comment]
The issue is not specific to this event and can be reproduced.

I just tested looking for an error or something, but looks like the button doesn't even try to do anything. Need to look at the code.

**Comment by znarf** [comment]
After investigation, I found this was broken in https://github.com/opencollective/opencollective-frontend/pull/2094 cc @Betree @NotJohs

**Comment by sebsheep** [comment]
It still does not work...

**Comment by znarf** [comment]
@sebsheep it's not deployed yet

**Comment by sebsheep** [comment]
Thanks François. Do you know when it will be? Is it possible to be pinged
when it is deployed?

**Comment by znarf** [comment]
@sebsheep Try again? If it's still not there, will have to wait for the cache to be flushed.

**Comment by sebsheep** [comment]
It worked! Thanks :)
