### ISSUE TITLE
Make Cypress tests environment-agnostic

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2556]
Following up on https://github.com/opencollective/opencollective/issues/2531

From the feedback provided on https://github.com/opencollective/opencollective/issues/2531, it seems that the best way to simplify the experience and onboarding for Cypress tests would be to ensure that tests are environment agnostic (meaning that they can work locally or on staging indifferently).

Concretely, we should use `cy.createCollective` as much as possible and provide helpers to easily create data rather than using pre-existing collectives.

Let's use this issue to list all places and patterns that we need to update to get there:

**Patterns**
- Need to be able to easily create a large number of transactions
- Need to be able to easily create a large number of memberships
- *Todo*

**Tests**
*Todo*

**Comment by jzabala** [comment]
This may sound crazy but how about if from cypress we setup a postgres client? I have created tests for the api and frontend and in my opinion apis tests are way easier because in the backend I can access the database directly. For example if I need to test an order success in the api I don't have to figure out how stripe works or any of that, I just put the data that I want, in the table that I want, test that the query returns what I want and clean up after that.

**Comment by Betree** [comment]
> This may sound crazy but how about if from cypress we setup a postgres client? I have created tests for the api and frontend and in my opinion apis tests are way easier because in the backend I can access the database directly. For example if I need to test an order success in the api I don't have to figure out how stripe works or any of that, I just put the data that I want, in the table that I want, test that the query returns what I want and clean up after that.

@jzabala that's a brilliant idea, it would simplify this issue by an order of magnitude if we can create entries in the databases directly from cypress commands. @znarf what do you think?

**Comment by znarf** [comment]
What do you have in mind? Raw SQL? Or using our model? As I see it, the 2 are coming with important drawbacks.

**Comment by jzabala** [comment]
> What do you have in mind? Raw SQL? Or using our model? As I see it, the 2 are coming with important drawbacks.

How about create a data layer package with all our models. That way we can consume them by the backend and frontend?

**Comment by Betree** [comment]
> How about create a data layer package with all our models. That way we can consume them by the backend and frontend?

That's a clean option, leveraging an advantage of using JS on the full stack. Doing the change and keeping the model in sync with all projects has however a cost/complexity.

For a first iteration. I would see us use raw SQL, with minimal queries to cover the basics, something like:

```es6
Cypress.commands("createMember", ({ MemberCollective, CollectiveId, role}) => {
    API.runQuery(`
        INSERT INTO "Members" VALUES (...)
    `, { ... })
})
```

**Comment by Betree** [comment]
One downside I didn't think about: I'm not sure we're willing to let anyone run SQL queries in the staging DB, which compromises the environment-agnostic aspect.

**Comment by jzabala** [comment]
> One downside I didn't think about: I'm not sure we're willing to let anyone run SQL queries in the staging DB, which compromises the environment-agnostic aspect.

How will this be possible? I mean, staging keys are private and e2e tests are suppose to be run locally or by the CI.

**Comment by jzabala** [comment]
> > How about create a data layer package with all our models. That way we can consume them by the backend and frontend?
> 
> That's a clean option, leveraging an advantage of using JS on the full stack. Doing the change and keeping the model in sync with all projects has however a cost/complexity.
> 
> For a first iteration. I would see us use raw SQL, with minimal queries to cover the basics, something like:
> 
> ```js
> Cypress.commands("createMember", ({ MemberCollective, CollectiveId, role}) => {
>     API.runQuery(`
>         INSERT INTO "Members" VALUES (...)
>     `, { ... })
> })
> ```

Yeah, you are right, there is a cost on keeping both projects up today. But we already have a script that update the frontend schema when we change the backend. Can we do the same for the models?

**Comment by Betree** [comment]
> How will this be possible? I mean, staging keys are private and e2e tests are suppose to be run locally or by the CI.

The main goal of this issue is precisely to discuss how we could make Cypress tests run efficiently on staging, so that contributors don't need to clone the API to run them :slightly_smiling_face:

**Comment by jzabala** [comment]
> > How will this be possible? I mean, staging keys are private and e2e tests are suppose to be run locally or by the CI.
> 
> The main goal of this issue is precisely to discuss how we could make Cypress tests run efficiently on staging, so that contributors don't need to clone the API to run them 🙂

yeah, but we are looking at this solution because currently is not that easy for people to setup the api locally to run the tests. How about if instead enabling people to run tests on stating we could provide an easier setup for the api. **Download Docker, clone api project, run this command** and you are setup, you can run your e2e tests locally.

Or how about we create another instance of the api only focused on tests, this one wouldn't even need the frontend?

I think the easier we make it to write tests the more we'll do it.

**Comment by Betree** [comment]
@jzabala That's a different issue, let's follow up on that topic in separate issues

**Comment by jzabala** [comment]
> @jzabala That's a different issue, let's follow up on that topic in separate issues

Yeah, you are right. I got caught up in the moment 😁.

**Comment by Betree** [comment]
Seems difficult to achieve. Will eventually revisit in the future.
