### ISSUE TITLE
Use CollectivePickerAsync on AddFundsSourcePicker

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2558]
We want to use the new `CollectivePickerAsync` component with the `creatable` option for `AddFundsSourcePicker`.

@xdamman @piamancini my notes from last time are incomplete, so I wanted to confirm with you the specs for this component before implementing:

- Should be able to search for any `ORGANIZATION` or `USER`
- Should allow to create `USER` or `ORGANIZATION` inline if it doesn't exist yet
- ~~"Source" should be the first field in the form~~
- ~~Should display the balance of the source~~

I also have this but I'm not sure if these are requirements for MVP or part of a future improvement:
- Should be able to select event as the source ==> **Edit: For future improvement**

**Comment by piamancini** [comment]
> Should be able to search for any ORGANIZATION or USER 

Yes

> Should allow to create USER or ORGANIZATION inline if it doesn't exist yet

Yes

> "Source" should be the first field in the form

No, it should be amount. 

> Should display the balance of the source

What do you mean by this? If the source doesn't exist there shouldn't be a balance. Also we are adding money on behalf of a source, we don't add the money first to the organization and then to the collective. So balance doesn't seem relevant. 

> Should be able to select event as the source

I'm not sure about this use case. It doesn't seem very urgent. By @xdamman and @alanna have been working with collectives more.

**Comment by Betree** [comment]
> What do you mean by this? If the source doesn't exist there shouldn't be a balance. Also we are adding money on behalf of a source, we don't add the money first to the organization and then to the collective. So balance doesn't seem relevant.

I think this was related to the intent to add funds from another Collective or Event.

**Comment by piamancini** [comment]
oh I see.
That case is likely to be handled as a regular collective to collective donation.
If we show it when we display organizations, it'll be confusing as there is no expectations for the funds to be there on the first place so the information is irrelevant. Maybe consider it displaying it only in the cases you mention above?

**Comment by piamancini** [comment]
ok cool

**Comment by Betree** [comment]
I've started working on this, but because of #1919 it seems to me that we can't really show **all organizations/users** as source to host admins, only to root users. Am I missing something?

**Comment by alanna** [comment]
Host admins can only add funds to Collectives under their host right? So even if we give them the ability to attribute those funds as coming from any organization, is there a risk? Unlike the broader case in #1919 this feature is limited to adding funds only in their host.

They are responsible for all funds in all Collectives in their host, regardless of source, so it seems likely someone would be able to use this maliciously. 

Maybe I am missing something?

**Comment by Betree** [comment]
@alanna Sorry I got confused with https://github.com/opencollective/opencollective/issues/1919 but you're right that it's not the same thing (adding funds to an organization VS adding funds to collectives).

So this should be safe indeed. I'll iterate on https://github.com/opencollective/opencollective-frontend/pull/2921
