### ISSUE TITLE
Focus collective page on showing ledger and money-related items

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#256]
![2016-10-10 15 26 20](https://cloud.githubusercontent.com/assets/6106941/19250274/911664ca-8f07-11e6-87bd-a33352a73f07.jpg)

**Comment by asood123** [comment]
Opencollective is about transparency. We are freeing your ledger (like Github freed your code).  So, your transactions (aka ledger) is taking front and center role. 

Some general notes:
- Top hero remains the same, except that annual budget is replaced with faces of contributors
- All other fields like description, longDescription, whyJoin, etc are consolidated into a single .md file

Expenses:
- In the ledger section, expenses can be these states: pending, rejected, approved, paid. Need to show all of those.
- The "+" next to "pending transaction" is a way to add a new expense. Would be even cooler to leave a hanging row to submit a new expense
- Also, need a placeholder for that section when you have no expenses. Maybe the hanging row can be it?

Donations:
- Top three green buttons ("become a backer", "become a sponsor", etc) are the new donation flow. By default, a collective will just start with a single button "Donate" that will open up a generic field (like square cash) with a prefilled amount and one-time duration.
- When a collective adds tiers (like "backers"), other buttons will show up and "Donate" will change to "Other".
- Types of donations: general one-time, recurring, paying for an expense, and in-kind. For donations which are paying for an expense, we need to show small text to let you know that. 
- For recurring donations, we can use a small text area underneath to show that it's recurring.

Also, note that there is no need to show fees anywhere. We want to switch to adding fees on top.

**Comment by erickrico** [comment]
still in progress, gotta figure out how to filter between status, please tell me if im going to far of the concept you want to convey, i just feel the list is to straight forward and we can play a little bit with the information we got. 
![working](https://cloud.githubusercontent.com/assets/18429104/19459963/d78c5622-949c-11e6-9981-afd1adb674d1.png)

**Comment by asood123** [comment]
- Like the photos of people at the top.
- Would rather not hide pending expenses behind a click (we want people to approve and cover them)
- I'm not sure a timeline like that will work in our current UI. Takes up too much space. We need to be able to show at least 10 or so things before you click "more". We are imagining something closer to a bank statement than a timeline.

**Comment by erickrico** [comment]
![progress](https://cloud.githubusercontent.com/assets/18429104/19500813/3b0c50de-9566-11e6-9318-2f476b16b26d.png)

**Comment by asood123** [comment]
Looking better @erickrico. 

- The left side is likely going to be much longer than right side. Would that look weird in the UI? 
- What about showing donations?
- Where do "Become a backer" or "Become a sponsor" take you? We were originally putting the full donation flow above the ledger...

**Comment by erickrico** [comment]
![new collective](https://cloud.githubusercontent.com/assets/18429104/19664213/0c42438c-9a05-11e6-900d-349d71de5c4e.png)

**Comment by asood123** [comment]
@erickrico Starting to look a lot better. How will we show comments and notes for expenses? Might need to make them a bit bigger?

**Comment by erickrico** [comment]
![ledger](https://cloud.githubusercontent.com/assets/18429104/19749310/bb5d53c6-9bad-11e6-8270-271baf3d9e9c.png)
![screen shot 2016-10-26 at 6 53 37 pm](https://cloud.githubusercontent.com/assets/18429104/19749311/bb6f5940-9bad-11e6-8a77-225651a5d3fe.png)

**Comment by erickrico** [comment]
detail view with ledger at the right, you can scroll down to see other expenses or use the ledger to navigate  ![screen shot 2016-10-28 at 2 01 17 pm](https://cloud.githubusercontent.com/assets/18429104/19818810/1babd418-9d17-11e6-865e-e4621e13457f.png)

**Comment by erickrico** [comment]
![2](https://cloud.githubusercontent.com/assets/18429104/20123034/ed779b80-a5e1-11e6-93e0-0ac290377790.png)
![1](https://cloud.githubusercontent.com/assets/18429104/20123033/ed751022-a5e1-11e6-857a-826567d22e90.png)

**Comment by xdamman** [comment]
Looking good!

I'd add a big button below the funds available "donate" or "become a backer" that would link to the detailed sections about becoming a backer or sponsor.
Most crowdfunding sites use the top right column to show the status and the call to action to join the campaign.

Also I feel like showing the last 3 or 5 transactions should be enough with a button to view more. 

I'm not a fan of the plus or minus need the avatar. It should be near the amount.

**Comment by asood123** [comment]
@erickrico you are right, donate section next to transactions feels cluttered. But, empty space when there are no pending expenses doesn't feel right either. One way to deal with this is to show only 4-5 transactions and put a placeholder for "Submit expense". Similar to the placeholder that we show when there are no transactions.

**Comment by asood123** [comment]
Posting a few images from slack:

![image](https://cloud.githubusercontent.com/assets/6106941/20731178/3e9915ae-b657-11e6-943e-65eac72ef64c.png)

![image](https://cloud.githubusercontent.com/assets/6106941/20731188/49431b9e-b657-11e6-8f89-ec747bcb7cc9.png)

![image](https://cloud.githubusercontent.com/assets/6106941/20731194/4de51f26-b657-11e6-85f8-75acbaa5255d.png)

![image](https://cloud.githubusercontent.com/assets/6106941/20731199/52abd6c6-b657-11e6-9131-69bde8823fee.png)

**Comment by asood123** [comment]
bulk of this is live, closing
