### ISSUE TITLE
Precision Not current on View Expense Page

### ISSUE THREAD

**Issue by jeffin143** [opencollective/opencollective#2560]
**Describe the bug**

While testing [PR](https://github.com/opencollective/opencollective-api/pull/2392 ), I noticed that the amount is rounded in view all expense page, Which I guess is not correct , Since the amount is not rounded in mail and on budget page 

**To Reproduce**
1. Go to Expense Page
2. Click on any Expense

**Expected behavior**

The amount should display exactly as it is 

**Screenshots**

**Rounded Amount**

![Screenshot from 2019-10-25 22-28-56](https://user-images.githubusercontent.com/21286134/67591062-262c0280-f77a-11e9-994b-bb2b0109a81c.png)

**Not Rounded**

![Screenshot from 2019-10-25 21-58-25](https://user-images.githubusercontent.com/21286134/67591065-26c49900-f77a-11e9-9f02-c07b9f548ccc.png)

**Rounded Amount**

![Screenshot from 2019-10-25 21-58-17](https://user-images.githubusercontent.com/21286134/67591066-26c49900-f77a-11e9-8bd4-e5b7688dddca.png)

I guess we should be consistent everywhere.

**Comment by znarf** [comment]
@alanna @piamancini should we prefer rounded or not rounded? I think not rounded (with  decimals) is better. Better display more characters than confuse users.

**Comment by piamancini** [comment]
agree @znarf

**Comment by jeffin143** [comment]
Closing this for #2579
