### ISSUE TITLE
Might not be able to receive emails

### ISSUE THREAD

**Issue by staltz** [opencollective/opencollective#2566]
I might or might not have a bug with emails. I just want to check if #2401 is still happening to my email account `andre@staltz.com` or not, before the next month comes in and I miss update emails.

**Comment by znarf** [comment]
After https://github.com/opencollective/opencollective/issues/2481 I removed you from the "unsubscribe" list and shared with you by email the feedback from our email provider.

I can confirm that as of now you have not been added again on this "unsubscribe" list.

**Comment by staltz** [comment]
Okay, thanks! I'll let you know if anything goes wrong.
