### ISSUE TITLE
Event budget transfer button won't work

### ISSUE THREAD

**Issue by looisjl** [opencollective/opencollective#2568]
**Describe the bug**
When I click on the budget transfer button from this page https://opencollective.com/make-it-sound/events/mise-en-place-audiotheque-la-serre-16878ev nothing happens (and no budget is transferred). 

**To Reproduce**
1. Go to https://opencollective.com/make-it-sound/events/mise-en-place-audiotheque-la-serre-16878ev 
2. Click on "transférer 2.256€ à Make it Sound" 

**Expected behavior**
Nothing happens and budget is not transfered. 

**Screenshots**
not necessary 

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Chrome
 - Version 77

Thanks for your help (quite urgent..) 

regards

Loois

**Comment by znarf** [comment]
Thank you for reporting it. We're on it https://github.com/opencollective/opencollective/issues/2555, the fix will be released today.

Closing as duplicate.

**Comment by looisjl** [comment]
wow, great!! 

many thanks for your fast reply

**Comment by znarf** [comment]
@looisjl It should be deployed now.
