### ISSUE TITLE
Host dashboard: improve consistency for buttons

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2570]
Related to https://github.com/opencollective/opencollective/issues/2567

---

Buttons on the host dashboard use different styles. We can improve consistency by using `StyledButton` for all of them and capitalized labels (ex: `Mark as paid`).

We'll need to add a new `buttonStyle` type called `danger` for the `Reject` operation. Button's design is available on https://www.figma.com/file/N4Xbl652BhzOutXmzhcrLGch/DS-06-%2F-Atoms?node-id=1928%3A7979

---

![image](https://user-images.githubusercontent.com/1556356/67697009-26114a00-f9a8-11e9-855b-80a79f7866e4.png)

**Comment by Betree** [comment]
Update: design's team has added the `Danger` state in the design system (https://www.figma.com/file/N4Xbl652BhzOutXmzhcrLGch/DS-06-%2F-Atoms?node-id=1928%3A7979). This issue now ready for implementation.

![image](https://user-images.githubusercontent.com/1556356/67700140-b1d9a500-f9ad-11e9-8b8d-1290e3540052.png)

**Comment by JoyLubega** [comment]
Hey, @Betree I would like to try this one, Do I just self assign?

**Comment by JoyLubega** [comment]
Let me just give it a try

**Comment by JoyLubega** [comment]
After doing some good homework on the host dashboard, I want to pick this again

**Comment by Betree** [comment]
Issue completed by @JoyLubega :tada:
