### ISSUE TITLE
Update design pattern for forms lists (edit goals/members)

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2572]
The edit pattern for `Edit goals` and `Edit members` doesn't have a good positioning for the Add/Remove/Save buttons. We want to edit both forms with a common pattern to edit the lists. 

**This issue is currently waiting for a feedback from design to know how to move forward with it.**

Below is how it looks like today (calls to action in green):

![image](https://user-images.githubusercontent.com/1556356/67753193-a2516f00-fa34-11e9-84cb-77a74fcf86d9.png)

**Comment by raulgrafico** [comment]
Hi @Betree , here is the link to the Figma file: 
https://www.figma.com/file/GF1gQ7fWNfaOAFNwuLeAUl/OC.com-Hot-Fixes?node-id=1038%3A454

**Comment by Betree** [comment]
Todo:

- Update `Ad goal` size and use `secondary` style

![image](https://user-images.githubusercontent.com/1556356/80352310-fc13e400-8873-11ea-93bd-d845bd120884.png)

- Update the pattern for `Remove`

![image](https://user-images.githubusercontent.com/1556356/80352360-10f07780-8874-11ea-97bc-e1c4e39c25d2.png)

- Update the form input styles

![image](https://user-images.githubusercontent.com/1556356/80352440-3087a000-8874-11ea-9c74-b104f3c671ee.png)

- **Do not** update the save button to what's in the design, as it is using the old button styles. Instead keep the existing ones.

**Comment by SudharakaP** [comment]
I'll do this issue if no one is already working on this. :smile:
