### ISSUE TITLE
Content for fancy terms of service screen

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2575]
@xdamman has suggested a fancy more inviting version of the terms of service screen. Personally I do not agree with this as I don't think it's MVP or necessary given our priorities right now, but if it's going ahead it will start to show up all over the place and we need to make sure the content is right.

I strongly disagree with this version from the mockups:

![](https://user-images.githubusercontent.com/1556356/67751904-4259c900-fa32-11e9-8c52-199295e36c01.png)

There is no such thing as perfect inclusion. Including some people (eg, abusive people) excludes others by making the space unsafe. Many projects have valid criteria for who they will and will not accept money from. A climate group should not be forced to accept involvement and money from an oil company. A diversity group should not be forced to include misogynists.  

Not every group is sustainable. That's reality. Many are not yet but are coming to Open Collective because they *aspire* to be. We still support them even if ultimately they fall short of true sustainability. Open Collective Inc itself is not actually sustainable right now - I wouldn't be able to click yes on these terms for our own group.

If we want to make a friendly version of the ToS screen, to help people understand what they are agreeing to in human language, great! But it should be a simplified version of what's actually in the legal terms and privacy policy, not some made up content. I did this for the ToS for OSC and Foundation, with friendly 'help text' to decode the legal language. Accessibility is an important aspect of transparency so it's important people can actually understand what they agree to.

If this change is going ahead, I can take the time to create a similar 'friendly' version of the ToS and privacy policy, but again I don't think this is our priority right now. For the MVP of the various flows we are working on, we should just have a standard tickbox to accept the existing terms and move on.

**Comment by piamancini** [comment]
I think it'd be ok if we wanted to simply state that these are our values, but forcing the check marks is very weird. 

The values are so broad and subjective that clicking doesn't really mean anything. We also have no way of agreeing what a violation of these terms would be, let alone enforce them. It looks like an attempt to signal virtue without any real meaning or consequence. Those values are properly ushered in this community with actions. 

Again, I'd be happy to support a statement of values but not a ToS type of action.

**Comment by xdamman** [comment]
This lacks context. I agree with Alanna that inclusive doesn't mean that you should accept everyone. However it does mean that you don't discriminate people as long as they follow the values of your collective. So it's a matter of properly defining those terms.

That said, and in the spirit of moving things forward, we will simplify this for now to simply approve the terms of service and we will create a separate project for this.

I'd love to see a way where in the process of creating a collective, the user gets presented the values of the network that they are joining. E.g. if you want to create an XR collective, you must agree with [their principles](https://extinctionrebellion.gitbook.io/docs/principles-and-values). By extension, Open Collective is the genesis circle and should also have a set of values.

**Comment by piamancini** [comment]
@alanna if this is not the case anymore, let's close this issue. @xdamman if you need to please open a separate one for a new feature.

**Comment by alanna** [comment]
We decided not to prioritise this right now and will stick with a standard ToS tickbox for now. If we want a more human friendly terms of service experience i the future, a new issue will be opened.
