### ISSUE TITLE
Prevent collectives to be deleted when they have events attached.

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2577]
## User story 

Before deleting a collective, we should make sure there is no event attached to it.

## Best solution for this problem

On collective deletion, we should check if there is any non-delete event attached to it. If there is one, we should deny the collective deletion.

## Note

The ability to delete events is not there yet but there is an open PR https://github.com/opencollective/opencollective-frontend/pull/2803 for it.

**Comment by znarf** [comment]
@jeffin143 thank you for the API PR. If I'm not mistaken, this needs also to be handled on the Frontend side. Similar to other cases, the Delete button should be disabled and it should be explained why.

**Comment by jeffin143** [comment]
> @jeffin143 thank you for the API PR. If I'm not mistaken, this needs also to be handled on the Frontend side. Similar to other cases, the Delete button should be disabled and it should be explained why.

The delete button will be `disabled` if the error persist, so since I am throwing an error it would be disabled, we just need to add the condition for event, I guess we need not write special handling for it except for explicitly mentioning the reason in print.

**Comment by znarf** [comment]
🏆 This issue was completed by @jeffin143 

To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
