### ISSUE TITLE
Refactor or remove specific precision handling

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2579]
Following up on:
https://github.com/opencollective/opencollective-frontend/pull/2890/files

We need to either:
- move this specific precision handling in the `AmountCurrency` component
- remove it altogether

**Comment by Betree** [comment]
My personal opinion would be to **not** truncate decimals when there's none (`$10,00`) if `precision` has been passed as a parameter. Main argument for that is alignment: if you conditionally truncate the number, it may be mis-aligned with the others when used in a vertical display.

|  Quantity |  Amount | Notes |
|:---------:|-------:|-------|
| 4         | $5.47   |       |
| 2         | $91.12  |       |
| 7         |   $10   |  <-- Not aligned with the rest     |
| 1         | $1.30    |       |
| 3         | $7.99   |       |

**Comment by jeffin143** [comment]
@znarf , is it ok to go with @Betree suggestion, so should we need more discussion on it ?
if that's the case i will handle this :)

**Comment by znarf** [comment]
@jeffin143 Yes we're good to go.

Precisely, let's make sure the rounding has a precision of 2 decimals everywhere.

**Comment by jeffin143** [comment]
@znarf Let's close this

**Comment by znarf** [comment]
🏆 This issue was completed by @jeffin143 

To claim the bounty please, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new  Please make sure to mention the ticket number in the invoice and in the expense title.
