### ISSUE TITLE
send a backers receipt email after each recurring donation

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#258]
we need to send backers an email acknowledging each donation.

**Comment by tgamblin** [comment]
@piamancini: any timeframe on this one?  Most folks getting reimbursed by their employer are going to need a receipt showing zero balance as proof they paid.

**Comment by tgamblin** [comment]
FWIW, I can submit a CC statement in the meantime.

**Comment by piamancini** [comment]
@xdamman : can you help with this?

**Comment by xdamman** [comment]
Should be fixed. We are now sending a link to the PDF receipt in the thank you email that is sent after each transaction.

**Comment by tgamblin** [comment]
@xdamman: would this have happened for my sustain ticket or for the donation I made to Sustain on OpenCollective?  The Sustain confirmation didn't have an attachment, and I can't find a thank you email for the sustain donation.

**Comment by xdamman** [comment]
Ah no I pushed that change after. So it's only for new donations. Let me look in the DB and I'll send it to you manually.

**Comment by piamancini** [comment]
this has been fixed.
