### ISSUE TITLE
Last question on the FAQ section of the pricing page doesn't work

### ISSUE THREAD

**Issue by madebycollins** [opencollective/opencollective#2582]
**Describe the bug**
The accordion for the last question under the FAQ on the pricing page is not set up correctly. It doesn't work,

**To Reproduce**
1. Go to [https://opencollective.com/pricing](https://opencollective.com/pricing)
2. Scroll down to the 'Frequently Asked Questions' section.
3. Click the last question ('What are some examples of fiscal hosts? ')
4. See error, in that it does not expand.

**Expected behavior**
You would expect the accordion to expand in the same way as the previous ones, but it doesn't. It should either be fixed or removed. I imagine fixed.

**Comment by flickz** [comment]
This is not a bug, that section has no answer looking through the [code](https://github.com/opencollective/opencollective-frontend/blob/master/static/pricing-page/index.html#L658-L662) . I'm not sure why we have it that way.

@piamancini  Are we leaving this section out on purpose?

**Comment by znarf** [comment]
@flickz Let's remove it for now.
