### ISSUE TITLE
HostDashboard: Add loading state for expense refetch

### ISSUE THREAD

**Issue by flickz** [opencollective/opencollective#2583]
Following up  @Betree's [comment](https://github.com/opencollective/opencollective-frontend/pull/2896#pullrequestreview-307977537) to include a non blocking loading state for expense refetch.

**Comment by Betree** [comment]
We will rather focus on the dashboard revamp.

**Comment by Betree** [comment]
Not needed anymore since this view has been replaced on the new dashboard
