### ISSUE TITLE
Expenses being raised under the user instead of the Collective

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2589]
A user submitted an expense to the [Scuttlebutt Maintenance](https://opencollective.com/powersource/expenses/11347) Collective. You can see it displayed in the budget section.

![Screen Shot 2019-11-04 at 10 46 35 AM](https://user-images.githubusercontent.com/5498878/68092484-86e0db00-fef0-11e9-9ed5-13e1dd95f4c9.png)

However, the expense appears to be under the user (powersource) instead of the Collective: https://opencollective.com/powersource/expenses/11347

The expense is showing 'insufficient balance' even though there is enough money in the Collective.

![Screen Shot 2019-11-04 at 10 46 09 AM](https://user-images.githubusercontent.com/5498878/68092487-9102d980-fef0-11e9-872b-88115ab8c3b7.png)

**Comment by alanna** [comment]
Reported by @mixmix

**Comment by znarf** [comment]
It's interesting. The conditions are a bit tricky to reproduce.

This link or this page should not exist in the first place: https://opencollective.com/powersource/expenses/11347. Or at least, if you start with this page, it breaks the behavior later.

This is the correct URL, clicking on it should (I hope) unblock the users:
https://opencollective.com/scuttlebutt-maintenance/expenses/11347

We have yet to figure how the users fall in this path and how we can prevent that.

**Comment by alanna** [comment]
Oh that's strange. Thanks for the alternate link. @mixmix I paid this expense so that's unblocked. We'll try to find out how this happened.

**Comment by alanna** [comment]
We're seeing more examples of this and something if definitely going wrong here.

These two expenses:
* https://opencollective.com/sean-denny/expenses/11380
* https://opencollective.com/sean-denny/expenses/11389

Were raised under the [Solidus](https://opencollective.com/solidus) Collective, and you can see them in the budget section:

<img width="835" alt="Screen Shot 2019-11-08 at 12 30 44 PM" src="https://user-images.githubusercontent.com/5498878/68436702-9bd8a980-0223-11ea-88a8-30dd497c6a6c.png">

However if you look at the URLs you can see they are under the user not the Collective.

**Comment by znarf** [comment]
@alanna same issue, to unblock, you should replace the user slug with the collective slug in the expense URL

**Comment by znarf** [comment]
@Betree In the Budget section, the expenses should be under the collective URL, not the user URL.
