### ISSUE TITLE
Transaction pdf shows wrong month

### ISSUE THREAD

**Issue by naduvko** [opencollective/opencollective#2591]
**Describe the bug**
When downloading transaction invoice, pdf file shows date with next month
Fore example transaction made on 11/4 is with date 12/4

**Screenshots**

![image](https://user-images.githubusercontent.com/615788/68106935-d7a20500-feeb-11e9-9452-c593f44f5646.png)

**Comment by znarf** [comment]
@naduvko Thank you for reporting this!

This is handled in the following code: https://github.com/opencollective/opencollective-invoices/blob/master/src/pages/invoice.js#L447

The second parameter should be a `monthIndex` and not a `month`, we should basically substract 1. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

This is a terrible API in Javascript and developers usually fall in this trap.

**Comment by jeffin143** [comment]
@Betree , we can close this too :)
