### ISSUE TITLE
Widget count issues

### ISSUE THREAD

**Issue by nemchik** [opencollective/opencollective#2593]
**Describe the bug**
The widget (`<script src="https://opencollective.com/SLUG/banner.js"></script>`) seems to be incorrectly counting all organizations that have donated to a collective as a sponsor, but not showing the organization under sponsors or backers.

**To Reproduce**
1. Use the widget code from https://opencollective.com/SLUG/edit/export (in my case I'm testing for `https://opencollective.com/linuxserver` at https://lsio.nemplex.com/donate )
2. Put the code in an HTML page (any plain old HTML works fine)
3. The page displays the widget as described above (incorrectly)

**Expected behavior**
The widget should either:
- Display Organizations and Individuals separately OR
- Display tiers separately (probably not just backers and sponsors)

**Screenshots**
![image](https://user-images.githubusercontent.com/725456/68153950-1d6ec580-ff0c-11e9-9a00-0fe2c08cc587.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 78

**Smartphone (please complete the following information):**
 - Device: Moto z3
 - OS: Android 9
 - Browser Google Chrome
 - Version 78

**Comment by znarf** [comment]
@nemchik Thank you for the report!

Seems the widget is displaying Organizations and Individuals separately, which looks like a correct behavior if I compare to the collective page.

![Screenshot 2019-11-12 at 12 59 28](https://user-images.githubusercontent.com/806/68670108-62b67700-054c-11ea-9b8e-65bf189beb66.png)

- The organizations count looks good
- The individuals count doesn't seem to match. It's just because only the top 15 individuals are displayed. There is no total count given in the collective page to compare, but I'm assuming the "36" figure is correct in the end.
- The terms "Become a sponsor" and "Become a backer" are confusing and needs to be updated. They could be replaced by "Contribute as an Organization" or "Contribute as an Individual" to use updated terminologies. Or just "Contribute" as a shorter version.

**Comment by nemchik** [comment]
Re: counts
I agree the numbers look correct. The count isn't really the issue (sorry for the misleading title, feel free to edit).

Re: terminology
I would agree "contribute as ..." Or just "contribute" makes sense.

The issue I was trying to point out can be seen in the screenshot and demo link above; organizations are counted correctly but not shown, and are listed next to the become a sponsor section.

**Comment by nemchik** [comment]
This does not seem to be resolved. The widget is currently displaying an organization that seemed to make an ad-hoc contribution as a sponsor here:
![image](https://user-images.githubusercontent.com/725456/74158502-cd289300-4bdf-11ea-8471-fabd57bf6a77.png)
The amount contributed is not the amount designated for the sponsor tier.

I'm pointing this out to reference https://opencollective.com/linuxserver
My organization on OpenCollective https://opencollective.com/dockstarter is one of the 2 counted in the screenshot, but not displayed in the widget anywhere. DockSTARTer is a backer of LinuxServer and is setup for recurring contributions. Salesforce https://opencollective.com/salesforce is showing as a sponsor but has not donated in the sponsor tier OR the backer tier (from what I can tell - it looks to have been a one time contribution). We both show up in the SVG for organizations https://opencollective.com/linuxserver/organizations.svg?width=600 which is good.

So as I understand the first screenshot:
- A count of all organizations regardless of tier is shown (2)
- Large cards for organizations that have contributed without using a predefined tier are then shown as if they were sponsors (and for LSIO only one is shown at the moment, Salesforce)
- A count of all individuals regardless of tier is shown (91)
- Avatars for all individuals regardless of tier are shown.

This seems very confusing. I may be incorrect about the exact way (tier) that Salesforce donated to LSIO (I don't have access to see that), but there are a few scenarios that don't really clear anything up:
- Salesforce somehow donated at the sponsor tier for an amount different than the tier describes
- Salesforce donated at the backer tier and is displayed as a sponsor (but DockSTARTer is not)
- Something else that maybe I'm not understanding.

I don't really care about the specifics about my collective being displayed, but the inconsistencies and confusion about what is actually being displayed would apply to anyone using the widget.

**Comment by znarf** [comment]
Most of the confusion is about the wording which is not appropriate. This was explained in:
https://github.com/opencollective/opencollective/issues/2593#issuecomment-552865967

> The terms "Become a sponsor" and "Become a backer" are confusing and needs to be updated. They could be replaced by "Contribute as an Organization" or "Contribute as an Individual" to use updated terminologies. Or just "Contribute" as a shorter version.

These are NOT "tiers" which are displayed but "types" (individual and organization). Changing the copy should fix that confusion.

Also, DockSTARTer is not an "Organization" but a "Collective", this is why it's not appearing together with Organizations in some places. It's a problem that we're surfacing "Organizations" and "Individuals" and missing "Collectives". It's why we've taken small steps to feature Collectives together with Organizations in some places (t's definitely not helping clarification but it's better than nothing). It's why you're seeing DockSTARTer featured next to Salesforce in https://opencollective.com/linuxserver and why you're seeing it in the image at https://opencollective.com/linuxserver/organizations.svg.

- I will update the copy
- I will add Collectives together with Organizations in the banner at https://opencollective.com//linuxserver/banner.html 

PR pending: https://github.com/opencollective/opencollective-frontend/pull/3522

**Comment by nemchik** [comment]
Thank you for all of that explanation, it clarifies A LOT!

**Comment by znarf** [comment]
<img width="569" alt="Capture d’écran 2020-02-13 à 17 17 55" src="https://user-images.githubusercontent.com/806/74454859-cbcbc480-4e84-11ea-84d1-873616a682f7.png">

@nemchik Changes are live! Let me know if it works for you and if we can close this issue.

**Comment by nemchik** [comment]
Sorry I did not see your reply sooner. I can confirm that this is working as expected now! Thanks!
