### ISSUE TITLE
Buttons overlapping menu on host page in admin view

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2599]
Because of the large number of buttons visible to host admins when looking at the host page, they overlap the menu bar.

![Screen Shot 2019-11-05 at 1 30 42 PM](https://user-images.githubusercontent.com/5498878/68169356-a2bbae00-ffd0-11e9-9d3e-8f3dfc4b9cfe.png)

**Comment by znarf** [comment]
@alanna Normally, "Contact" should not be there if you're an admin of the Host. Do you still see it? This was supposed to be fixed in https://github.com/opencollective/opencollective-frontend/pull/2897 from @flickz 

After that, maybe we could also remove the "Apply" button for Host admins.

**Comment by alanna** [comment]
The contact button is gone, which helps a lot. I think it's OK now, although it still looks cluttered. 

We need the 'apply' button because sometimes fiscal host admins want to add a Collective to their own host. How else would they do that?

**Comment by znarf** [comment]
> We need the 'apply' button because sometimes fiscal host admins want to add a Collective to their own host. How else would they do that?

Ok, make sense.

**Comment by alanna** [comment]
Closing as the worst of the problem is gone now. But this issue with cluttered buttons and some options being hidden (#2606) should be looked at by design at some point @Memo-Es @cuiki
