### ISSUE TITLE
Dead link in Google results for API docs

### ISSUE THREAD

**Issue by wooorm** [opencollective/opencollective#2600]
**Describe the bug**

I was hoping to see if there was a nice API to search OC, and...

**To Reproduce**

1. Google “OpenCollective API”
2. Click on the first result (`https://docs.opencollective.com/help/developers/api`)
3. Get a [404 not found](https://docs.opencollective.com/help/developers/api)

**Expected behavior**

A redirect to a new place

**Additional context**

For the XY problem: If anyone has tips on how to search for the most active companies that sponsor through OC, I was hacking on sort of the inverse of back your stack: a dashboard for maintainers to see who is recently interacting with their orgs, where they work, etc.

**Comment by znarf** [comment]
The documentation team is currently working on a refactor. They should have an idea. cc @alanna @contraexemplo 

For the API, I would recommend exploring our GraphQL API from here:
https://medium.com/open-collective/open-collective-graphql-api-preview-3b42ed1d55ff The post is 1 year old but everything there should still be valid. Ping me on slack if you need anything specific.

About "Reverse BackYourStack", someone close to us is working on something in that spirit, see: https://github.com/RichardLitt/jabbar

**Comment by wooorm** [comment]
Sweet, thanks! Yeah I was talking to Richard about it as well, it aligns a bit with jabbar!

**Comment by contraexemplo** [comment]
That URL has in fact changed! It should take some time until Google updates that, I believe? I'm adding that to the redirect list over here https://github.com/opencollective/documentation/blob/v2/.gitbook.yaml

**Comment by contraexemplo** [comment]
So it looks like my redirects aren't working but I can't figure out why. Here's the docs talking about that on GitBook: https://docs.gitbook.com/integrations/github/content-configuration GitBook uses a versioning system that is not Git to manage content, so it doesn't really keep track that well on folders that were renamed, files moved, etc.

**Comment by contraexemplo** [comment]
@znarf and I were able to solve this after chatting over Slack: https://github.com/opencollective/documentation/commit/d18797281b648a92092f3a816feccba9984cb405 I had to drop the `help` prefix and add a `./`to every single redirect. It seems to be working just fine now! Can you confirm that, @wooorm?

**Comment by wooorm** [comment]
This works great, thanks @contraexemplo and @znarf!
