### ISSUE TITLE
Update Bot to @hapi/joi 16

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2602]
We have a policy to try to use the latest version of our dependencies in all repositories.

In the [Bot](https://github.com/opencollective/opencollective-bot), we're currently using the version 15 of @hapi/joi and the upgrade to version 16 has breaking changes.

We want to:

 - upgrade the package: `@hapi/joi` and `@types/hapi__joi` to v16
 - make sure the tests are passing

**Comment by CanerSezgin** [comment]
Hi @znarf, I am interested in this one, this will be the first time for me, I hope it will go well.
I've already sorted out the first issue after upgrading version of the packages.

**Comment by znarf** [comment]
@CanerSezgin Please have a try! Time limit is 1 week, so we can give it to someone else if it's not completed or progressing by then.

**Comment by CanerSezgin** [comment]
@znarf PR opened, I directly selected opencollective-bot master branch, I hope it is correct. 
Also, couldn't find any way to attach that pr with this issue. This is why I am writing from here.
https://github.com/opencollective/opencollective-bot/pull/229

**Comment by znarf** [comment]
@CanerSezgin To attach, the best is simply to add a link to the issue in the PR description, GitHub detects that.

**Comment by znarf** [comment]
🏆 This issue was completed by @CanerSezgin 

To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
