### ISSUE TITLE
Ability to run Open Collective Bot in a "serverful" prod environment

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2603]
As seen in https://github.com/opencollective/opencollective-bot/pull/184 there are currently issues upgrading to the latest `now` runtime and the feature we're relying on is already labeled as legacy, see: https://zeit.co/docs/runtimes#advanced-usage/advanced-node-js-usage/legacy-serverful-behavior.

For this reasons, we would like to be prepared to run in a "serverful" environment like Heroku.

We need to:
 - implement `npm run build` to compile typescript
 - implement `npm run start` using the built app

Important point, instead of the custom bootstrap currently in `index.ts`, it should make use of a more regular `probot` setup like `probot run ./index.js` (CLI) or `Probot.run(app)` (API) https://probot.github.io/docs/development/#alternate-way-of-running-a-probot-app This will be easier to maintain in the future.

Bonus point, upgrade to latest probot version, see: https://github.com/opencollective/opencollective-bot/pull/182

**Comment by NotJohs** [comment]
I would look into this issue

**Comment by znarf** [comment]
@NotJohs As you're already looking at another medium issue, and you have another medium issue that still needs to be merged, let's focus on these ones and keep the bounty for someone else for now.

**Comment by gmarcos87** [comment]
I can try to look this issue.
The idea is to keep doing deploy to now but that you can use the same code in Heroku?

**Comment by znarf** [comment]
@gmarcos87 ideally yes

**Comment by gmarcos87** [comment]
The probot update is now ready and the bot runs in both Now and Heroku.
I'm experimenting a bit with the Probot setup change. I think I found some bugs, as soon as I have more promising results I will tell you.

**Comment by gmarcos87** [comment]
This issue can now be closed, the change was applied in https://github.com/opencollective/opencollective-bot/pull/250

**Comment by znarf** [comment]
🏆 This issue was completed by @gmarcos87 

To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
