### ISSUE TITLE
Add "funding" to package.json while onboarding with Open Collective Bot

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2604]
NPM recently introduced the new `funding` property for `package.json`. See, https://blog.opencollective.com/beyond-post-install/ and https://blog.npmjs.org/post/188841555980/updates-to-community-docs-more

We're already creating the `FUNDING.yml` for GitHub, we would like now to add "funding" to  `package.json` if it exists. This should be a separate PR and action.

Implementation:
- create a new action such as `addPackageJsonFunding` similar to `createFunding`
- make sure it's adding the `funding` property to the `package.json` if it exists
- make sure the formatting of the `package.json` is not messed up, the Git diff should normally never bee more than 4 or 5 lines
- make sure 100% coverage stay so

**Comment by CanerSezgin** [comment]
I can take a look at this as well. Could you please assign this to me ?

**Comment by znarf** [comment]
Have a try and please take care of point 3 carefully, we don't want to mess up the indentation.

**Comment by CanerSezgin** [comment]
@znarf Tests are also done, JFYI

**Comment by znarf** [comment]
🏆 This issue was completed by @CanerSezgin 

To claim the bounty please, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new  Please make sure to mention the ticket number in the invoice and in the expense title.
