### ISSUE TITLE
Add type filter to search results

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2605]
It would be very useful if you could sort by `Collective` `Organization` `Fiscal host` and `Individual` in search results. Currently they are all mixed together and it's very hard to find things.

Example: https://opencollective.com/search?q=open

**Comment by znarf** [comment]
A $200 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the Open Source Festival event. If not completed there, it will be later open to everyone.

**Comment by codemutatio** [comment]
hello @znarf i would liike to work on this issue could you assign it to me

**Comment by znarf** [comment]
@codemutatio You're assigned!

**Comment by znarf** [comment]
@codemutatio Any progress? We'll have to unassign you if there is no significant activity within the next days.

**Comment by joshikeno** [comment]
@codemutatio any update?

**Comment by Betree** [comment]
If no progress, I think we should close the bounty to rather focus on https://github.com/opencollective/opencollective/issues/2970 (we can later implement it there).

**Comment by raulgrafico** [comment]
Link to the Figma file: https://www.figma.com/file/GF1gQ7fWNfaOAFNwuLeAUl/OC.com-Hot-Fixes?node-id=1523%3A1

**Comment by Betree** [comment]
Note that the `Individual` filter won't be there on the final implementation because this search doesn't allow to search for users (and I don't think that should be the case).

![image](https://user-images.githubusercontent.com/1556356/79478620-ebf63c00-800b-11ea-9677-98a745a63047.png)

**Comment by alanna** [comment]
Should this become a bounty again?

**Comment by Betree** [comment]
@alanna From the latest discussions, the goal for search was to rather move with https://github.com/opencollective/opencollective/issues/2970 and to move away from Algolia to use our own system. But we have no clear ETA for this project, so I'm not against adding a small bounty.

**Comment by jeffin143** [comment]
@Betree Is this a bounty ? since bounty tag was removed

**Comment by Betree** [comment]
@jeffin143 It currently isn't, for the reasons mentioned above.

However, I'm now thinking that 90% of the work required here will be preserved when we move to the new system: the frontend will stay the same, the mutation params also. Only the call to the `search` function itself will be affected, and that's a small change.

So I'm not against adding a small bounty on this one.

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

(this issue is currently assigned to @jeffin143)

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by snitin315** [comment]
Hi @jeffin143, Are you still working on this. If not I would love to give it a shot!

**Comment by jeffin143** [comment]
Yes @snitin315 , I am working on it

**Comment by snitin315** [comment]
@jeffin143 Any update on this?

**Comment by jeffin143** [comment]
Dropping it of , you can claim it

**Comment by Betree** [comment]
:trophy: This issue has been completed by @snitin315  

To claim the **$200** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
