### ISSUE TITLE
Fix "Relation {Table} does not exist" errors in CI

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2607]
In CircleCI environment, when performing `npm run test` in the API project, we see the following errors in the logs.

```
Unhandled rejection SequelizeDatabaseError: relation "Transactions" does not exist
Unhandled rejection SequelizeDatabaseError: relation "Transactions" does not exist
Unhandled rejection SequelizeDatabaseError: relation "Collectives" does not exist
Unhandled rejection SequelizeDatabaseError: relation "Collectives" does not exist
Unhandled rejection SequelizeDatabaseError: relation "Collectives" does not exist
Unhandled rejection SequelizeDatabaseError: relation "Collectives" does not exist
Unhandled rejection SequelizeDatabaseError: relation "Collectives" does not exist
Unhandled rejection SequelizeDatabaseError: relation "Collectives" does not exist
Unhandled rejection SequelizeDatabaseError: relation "Collectives" does not exist
```

While it's not impacting the results of the test, it's noisy and can be source of confusion for newcomers.

We need to find why we have this errors and fix the root cause. To be clear, we're not looking for a quick fix to hide them!

**Comment by znarf** [comment]
🏆 This issue was completed by @EslamHiko 

To claim the bounty please, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new Please make sure to mention the ticket number in the invoice and in the expense title.

**Comment by znarf** [comment]
@EslamHiko, it seems it still happening, see the output of https://circleci.com/gh/opencollective/opencollective-api/21960. Could you have a look?

**Comment by EslamHiko** [comment]
@znarf It's working fine on my machine, I'll check it out and find an alternative solution.

**Comment by EslamHiko** [comment]
@znarf I tried many things here : https://github.com/opencollective/opencollective-api/compare/wip-2607 but none of them worked on CircleCI although It's working fine on my machine, I think it has something to do with Postgres container, CircleCI uses `circleci/postgres:9.6.8-alpine-postgis-ram` Image but I use `mdillon/postgis:9.6` maybe that's the reason of that strange conflict.

**Comment by znarf** [comment]
@EslamHiko can we try with different Postgres versions?

**Comment by EslamHiko** [comment]
@znarf I tried `mdillon/postgis:latest` and the errors appeared again.

**Comment by EslamHiko** [comment]
@znarf I know it's strange but I tried `mdillon/postgis:latest`,`mdillon/postgis:10`,`mdillon/postgis:9.6` and the first time after a fresh container it shows the errors but the second time it doesn't show any errors.

**Comment by znarf** [comment]
The bounty is reopened, anyone definitively fixing the issue will be rewarded.

**Comment by CanerSezgin** [comment]
I had thought these errors because of **dataloader-sequelize** update issue.
Because after I have updated loaders file, I don't get these error messages anymore. JFYI
https://github.com/opencollective/opencollective-api/pull/2900

**Comment by EslamHiko** [comment]
@CanerSezgin the errors may not appear on your machine but it'll still appear on CI 
check your last PR CI `npm run test` results: https://circleci.com/gh/opencollective/opencollective-api/22058?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by gmarcos87** [comment]
I figured out a way to reproduce the error outside the CI environment:
**Delete the test database and run it again**
```
dropdb opencollective_test  
createdb opencollective_test
psql -d opencollective_test -c 'GRANT ALL PRIVILEGES ON DATABASE opencollective_test TO opencollective'
psql -d opencollective_test -c 'CREATE EXTENSION postgis'
```
The error occurs during the first execution, in the next executions it will no longer be seen.
