### ISSUE TITLE
BackYourStack backing banner

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2609]
We would like a new banner to show up for organizations "Backing Their Stack".

It will replace the following banner, with the same size:

![Screenshot_2019-11-08 BackYourStack Discover the Open Source projects you are using and need financial support ](https://user-images.githubusercontent.com/806/68477020-9df33600-022c-11ea-9c02-34ce6bd44839.png)

But with a content and a visual style that could be mostly inspired by the design of the "BackYourStack" badge. Reference: https://www.figma.com/file/oNb9TlYCPcKABl4brBACDI/BYS.COM-XX1-%2F-Lab?node-id=881%3A0

The goal? The "BackYourStack" badge will ultimately point to this page which will feature the banner.

**Comment by znarf** [comment]
@piamancini I agree.

The positioning and size could be the same as current banner. The overall style should be dark to match the badge style. It should feature a big title then a text.

> ### {NameOfCompany} is backing their stack!

> Backing 234 dependencies with a $1000 monthly budget. $5000 donated so far.

> Optional Button {Back Your Stack too}

The optional could lead to a landing page to help others people Back Their Stack.

**Comment by raulgrafico** [comment]
Let me know if you like it @znarf .

![Banner-BYS](https://user-images.githubusercontent.com/1252676/68698697-1d437b00-0547-11ea-9304-172093f96939.png)

**Comment by znarf** [comment]
@raulgrafico I like it!

@piamancini It's to put on the BackYourStack profile of the company. Good to go?

**Comment by piamancini** [comment]
yep, great! good to go

**Comment by flickz** [comment]
<img width="465" alt="Screenshot 2019-11-14 at 7 42 59 AM" src="https://user-images.githubusercontent.com/15707013/68832961-8e537180-06b2-11ea-994a-64dc84c2757c.png">

@raulgrafico The other banner has a mobile version, can we also get that for this?

**Comment by raulgrafico** [comment]
Sure.

Good to go @piamancini ?

![Banner - Mobile](https://user-images.githubusercontent.com/1252676/68884201-46474580-06d8-11ea-82c0-7ec698fec224.png)

**Comment by flickz** [comment]
Closed in https://github.com/opencollective/backyourstack/pull/268 & https://github.com/opencollective/backyourstack/pull/265
