### ISSUE TITLE
Prevent anyone to submit expenses

### ISSUE THREAD

**Issue by coffynp** [OpenCollective/OpenCollective#261]
I really don't think it's a good idea to allow anyone to submit expense claims like this. If we start getting random claims from people we don't know or who are not active with us: a) it takes time we don't have to answer them; b) it puts us at risk from disappointed people complaining, regardless of how fair the decision not to pay might be. c) How would OC know what is spam since they don't have access to our email lis
Does this have to be on our page as far as OC is concerned, or can it be taken off? 
Or do zee only allow emails from Contributors to submit expenses?

**Comment by Shakyamuni177te** [comment]
I think it should be possible to block certain people who persistently put in nuisance expenses claims, or conversely, to allow collectives to setup whitelists, and automatically block all expenses claims from non-whitelisted sources...

**Comment by coffynp** [comment]
Whitelisting e.g. based on Contributors (not sure what else Contributors is used) and maintainable by the Host/Treasurer seems a good design

**Comment by Shakyamuni177te** [comment]
I would highly caution against this sort of consolidation of powers being the default option if the repo is based on a mission statement concerning democracy and accountability. Which I understand the need to allow filtration or even blocking in extreme cases, it should not become a habit and at the slippery slope end of things, could end up invalidating the entire mission.

**Comment by coffynp** [comment]
You raise a good point making me think we might have different types of Open Collectives across the world.  Maybe the 'category' you select when setting up an OC (Movement, organization, ...) can be used to distinguish these and tailor this (and other) options.  For the OC I am talking (UBIE and BIEN), we do not want everryone to submit expenses, only leaders in the UBIE/BIEN network.
