### ISSUE TITLE
Implement BackYourStack badges

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2610]
We would like to feature badges for the new BackYourStack monthly-plan. See the design: https://www.figma.com/file/oNb9TlYCPcKABl4brBACDI/BYS.COM-XX1-%2F-Lab?node-id=881%3A0

They should be implemented in SVG first and served from the following URL: http://backyourstack.com/{profile}/badge

The number of dependencies backed can be fetched dynamically from the data stored, the same one used to generate `backing.json`.

Finally, the badge needs to check with the OpenCollective API that the subscription is active. This can be implemented in several manners:
- Check that {profile} is having a match in the github of subscribers of the "Monthly Plan"
- Save the `orderId` when backing, and check that the `orderId` is `ACTIVE`

If the subscription is not active, the badge should display this information.
 
Bonus point: there should be a page, ie: http://backyourstack.com/{profile}/badge/setup explaining how to integrate the badges on your website.

**Comment by flickz** [comment]
Closed in https://github.com/opencollective/backyourstack/pull/264
