### ISSUE TITLE
Support global .github repository in Bot

### ISSUE THREAD

**Issue by glennawatson** [opencollective/opencollective#2611]
Hi there,

Thanks for making this fantastic tool, definitely much appreciated.

So one feature that github added recently was a global .github repository which would allow templates for your entire organization https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/

One thing that would be great since our OpenCollective has a github organisation with 8 different active projects is to have only one 'opencollective.yml' file using that repository.

Maybe it'd be possible to look up to see if that file exists in that `.github` repository and use that if one doesn't exist in the current repository?

**Comment by znarf** [comment]
Open Collective bot is discontinued.
