### ISSUE TITLE
Bot should notify maintainers when a backer creates an issue

### ISSUE THREAD

**Issue by maticzav** [opencollective/opencollective#2614]
I believe it would be beneficial if we added a `notify` option to the configuration which would modify the behaviour of the app in such a manner that would notify maintainers once someone who is backing the project submits an issue or a PR.

**Comment by gmarcos87** [comment]
Perhaps an email could be sent for each item labelled as "priority". 
But the address to which it is sent should not be in the repository settings (for privacy). I think that as a collective you should be able to configure the maintenance address in the frontend of opencollective.

**Comment by znarf** [comment]
Open Collective bot is discontinued.
