### ISSUE TITLE
Ability to select analyzed repositories

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2618]
### Story

When browsing a profile (organization or user), I want to be able to select/unselect analyzed repositories.

Currently, all repositories are analyzed and this should stay the default, all checked by default.

### Scenario

1. Go on https://backyourstack.com/
2. Go to an organization or user profile, ie: https://backyourstack.com/airbnb
3. Go to "Analyzed Repositories"
4. All repositories are checked by default. I'm able to uncheck/recheck them.
5. When switching back to "Projects requiring funding" or "Detected Dependencies", I can immediately see the result

### Future Work

If it's their profile or organization, users will be able to save these settings.

**Comment by flickz** [comment]
Closed in https://github.com/opencollective/backyourstack/pull/263

**Comment by znarf** [comment]
@flickz After having selected repositories, then immediately pressing "Back My Stack", repositories selection is not used.

**Comment by znarf** [comment]
@flickz when there is no dependency to donate to, there is this screen, this should not be possible

![Screenshot 2019-11-18 at 11 09 44](https://user-images.githubusercontent.com/806/69043797-047a1000-09f4-11ea-82c5-7e2a52d35b8c.png)

**Comment by znarf** [comment]
@flickz what about the second issue here?

**Comment by flickz** [comment]
I'll see to it.
