### ISSUE TITLE
[bug] [sponsors] Missing data causing CollectiveCards to render with bugs.

### ISSUE THREAD

**Issue by spentay** [OpenCollective/OpenCollective#262]
I was taking a look at the site earlier and noticed that the sponsor cards (CollectiveCards) are rendering wrongly.
The most obvious issue is the Annual budget rendering NaN & the missing mission statements - my guess is that sponsor shouldn't have an annual budget? and so the price formatting is doing calculations on `undefined`.
<img width="1092" alt="screen shot 2016-10-27 at 20 23 08" src="https://cloud.githubusercontent.com/assets/4335450/19762296/29ba1afc-9c85-11e6-90fd-a09859ff7cce.png">

I've taken a quick look and it looks like there's something a miss with [CollectiveCard.js](https://github.com/OpenCollective/opencollective-website/blob/57450d64f0ff0cd19587981e3282ff745540da93/frontend/src/components/CollectiveCard.js).
As mentioned - I'm thinking sponsors wouldn't have an annual budget, perhaps  `isSponsor` here is false for some reason and so the wrong logic is applied...

    if (isSponsor) {
      className = 'sponsor';
      stats = this.mapSponsorsCardProps();
    } else if (isCollectiveOnProfile) {
      stats = this.mapCollectiveCardOnProfileProps();
    } else {
      stats = this.mapCollectiveCardProps();
    }

I've not had the time to really get the project set up and dig in to this but it feels as though the sponsor card should be its own component, or at least it's content should be?
I'd be happy to take a look at this when I have a bit more time and open a PR :)

**Comment by asood123** [comment]
Thanks for reporting, @spentay. Do you have a url where you are seeing this issue?

**Comment by asood123** [comment]
Fix: https://github.com/OpenCollective/opencollective-website/pull/524. Going live shortly.

**Comment by spentay** [comment]
Awesome stuff :) Glad I could help there!
Sorry I didn't get back in time to answer your question though!
