### ISSUE TITLE
Handle permissions for BackYourStack subscribers

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2622]
We're currently relax on who can "Back Their Stack" from a given profile.

However, we should implement a simple permission system to prevent someone to edit the BackYourStack profile of someone else once the subscription is setup.

- [ ] By default don't allow to update a saved profile
- [ ] Allow update for a user profile if the connected GitHub account match the profile
- [ ] Allow update for any profile if the connected GitHub account match the stored GitHub account
- [ ] Allow update for an organization profile if the connected GitHub account is member of the organization

As part of this effort, we should save in `dependencies.json`:
- the connected GitHub account when the transaction was triggered (if any)
- ~~the order object from Open Collective~~ Moved to https://github.com/opencollective/opencollective/issues/2624
  - including basic properties such as `id`, `amount`, `fromCollective`~~

**Comment by flickz** [comment]
> the order object from Open Collective

Why do we want to  do this? Also is it going to be the new order created for dispatch?  or previous orders to collective dependency?

**Comment by znarf** [comment]
The `order` for the monthly subscription to BackYourStack, it will later be useful to check the status of it. But that's not exactly connected to permissions at this point so I can create a new ticket for it.
