### ISSUE TITLE
Save the `order` matching a BackYourStack profile

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2624]
We would like to keep track of the order id matching a given BackYourStack profile. We need to store at least the `{"order": {"id": 567}}` in the `dependencies.json` file.

It would be better, and we should anticipate that, to store the a more complex `order` object there, containing information such as `fromCollective` and 'totalAmount`

**Comment by flickz** [comment]
> We need to store at least the {"order": {"id": 567}} in the dependencies.json file.

I believe we're no longer using `dependencies.json` for this right? What is the structure of `order.json` and how should this fit in? 

I expect this to be saved after the user is redirected back to backyourstack from opencollective i.e `monthly-confirmation` page.

**Comment by znarf** [comment]
It should be `order.json` and we'll simply store the id `{"id": 567}` for the the first version.

**Comment by znarf** [comment]
@flickz Looking back at that, the stored data is not as specified. 
https://github.com/opencollective/opencollective/issues/2624#issuecomment-554887456

It's then incompatible with the work I have been doing in:
https://github.com/opencollective/backyourstack/blob/master/src/lib/data.js

```
  let order = await getProfileOrder(id);
  if (order) {
    order = await fetchOrder(order.id);
  }
```

Also as discussed yesterday, we should ensure that`triggeredBy` is optional.

**Comment by flickz** [comment]
This was the confusion.

https://github.com/opencollective/opencollective/issues/2624#issue-521478905

**Comment by znarf** [comment]
@flickz how are you gonna handle the permissions if you don't store `triggeredBy` anymore?

**Comment by flickz** [comment]
Yes, I removed it based on our conversation on permission PR yesterday, because authentication is not required to backyourstack and dispatch.

**Comment by znarf** [comment]
This is not answering my question. How do we implement the GitHub based permissions that we're discussing in the permission issue/PR ?

**Comment by flickz** [comment]
We're going to do it like, authentication won't be required to save but will be required for update on profile. The condition follows like.

```js
if (metadata && profileOrder && profileOrder.triggeredBy !== loggedInUsername) {

      if (!loggedInUsername || !accessToken) {
        return res.status(401).send('You have to sign in to edit profile');
      }

      if (profile.type === 'User' && loggedInUsername !== profile.login) {
        return res
          .status(401)
          .send('You can only edit profile connected to your GitHub account.');
      }

      if (profile.type === 'Organization') {
        const membership = await fetchOrgMembership(
          profile.login,
          loggedInUsername,
          accessToken,
        );
        if (
          !membership ||
          membership.state !== 'active' ||
          membership.role !== 'admin'
        ) {
          return res
            .status(401)
            .send(
              'You have to be an active admin of the organization update organization profile.',
            );
        }
      }
    }

```


PS: I'll add the `triggeredBy` property back and but only if the value is present (seperate PR)

**Comment by znarf** [comment]
@flickz that can work. `metadata` is a really misleading variable name, you should consider renaming it.
