### ISSUE TITLE
Add reject button to Collective application email notification

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2626]
Now that host admins can reject pending Collectives on the host dashboard (#2092), let's add a `reject` button to the email as well.

<img width="492" alt="Screen Shot 2019-11-13 at 10 22 45 AM" src="https://user-images.githubusercontent.com/5498878/68712059-cbaaf700-05ff-11ea-9e2c-3757c70378d7.png">

**Comment by sbinlondon** [comment]
I'd be interested in this once I've sorted my other issues (unless anyone else is keen to jump on it in the meantime). Has it been spec'd or does it need more planning first?

**Comment by Betree** [comment]
We've chosen a different path: in https://github.com/opencollective/opencollective-api/pull/3059 direct actions have been removed in favor of redirecting to the applications page. From there admins can approve or reject applications.

## Email

![image](https://user-images.githubusercontent.com/1556356/71003052-c0f0ef80-20e0-11ea-8e38-2920e853dffb.png)

## Dashboard

![image](https://user-images.githubusercontent.com/1556356/71007622-9b1b1900-20e7-11ea-95e5-a12e11a7add8.png)
