### ISSUE TITLE
Not clear Collectives box on host dashboard is a search box not a dropdown list

### ISSUE THREAD

**Issue by writingpoli** [opencollective/opencollective#2628]
I can't find the San Antonio Review collective on my host dashboard. The drop-down is empty.

Just want to add funds manually again.

![image](https://user-images.githubusercontent.com/3883763/68788378-e33aad80-0608-11ea-9794-681084182533.png)

Where am I screwing up?

**Comment by alanna** [comment]
@writingpoli we've recently changed that box from a dropdown list to a search box. If you type in the name of the Collective, does it appear?

@Betree - this is confusing because the little down arrow really makes it seem like a dropdown, but if you try to click that nothing appears. We should change the visual indicator from a down arrow to a search icon. I have made this mistake myself.

**Comment by writingpoli** [comment]
@alanna Ah, yes, @piamancini noted that in Slack. Totally confused me for a few days, though. Weird for it to be a completely empty box with any sort of drop-down functionality. For instance, I would click on it and an empty box would lower but it gave no indication I should try typing in it to find my collective.

**Comment by alanna** [comment]
I'm going to reopen this issue because while @writingpoli 's question was answered, the underlying design problem that caused the confusion is still there. I think we can easily improve this.

**Comment by alanna** [comment]
Here's my suggestion based on the user feedback shared here:

* Change dropdown arrow icon to search symbol
* Add help text in the box that says "search by Collective name" or just "start typing..."

**Comment by writingpoli** [comment]
![1113192143](https://user-images.githubusercontent.com/3883763/68825262-1f98f880-065f-11ea-96b5-fc4e007685e3.jpg)

**Comment by Betree** [comment]
> Here's my suggestion based on the user feedback shared here:
> 
>     * Change dropdown arrow icon to search symbol
> 
>     * Add help text in the box that says "search by Collective name" or just "start typing..."

Good suggestions, I'll also add preloading to ensure that hosts with a few collectives (< 25) always see them in the list without the need to search.

**Comment by writingpoli** [comment]
Thank you for the big "Add Funds" button! 
![image](https://user-images.githubusercontent.com/3883763/68828455-5bd25600-066b-11ea-8256-398584704797.png)

**Comment by Betree** [comment]
@alanna @writingpoli thank you for the valuable feedback, I made some improvements based on what was suggested here in https://github.com/opencollective/opencollective-frontend/pull/2978
