### ISSUE TITLE
Officially support subcollectives

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2633]
## User story 
Some collectives/groups have the need for a notion of "subcollective", that could be defined as a child collective **that may or may not share the same host**. This is useful, for example, when you need to collect money in different currencies, upon different chapters but for the same entity.

One example of that exists today as an MVP for https://opencollective.com/symfony-diversity, and all feedback about this experiment were positive to this day.

@xdamman just announced that another collective would need something similar. It's generally better to avoid "niche" features, only used by few users because they are usually less maintained. So great to see that others want to join!

However what we did for Synfony Diversity is not a sustainable approach because it adds too much complexity, confusion and potentials security issues in our data model. We've used the field `ParentCollectiveId`, which is normally used by events. Problem is that we expect events to have the same host than the collective they're depending on, which is not true for subcollectives.

![image](https://user-images.githubusercontent.com/1556356/68864800-01c8a380-06f2-11ea-8526-fc6b4c566a48.png)

## Best solution for this problem

I see four potential solutions:

(2) **We create a new `CollectiveRelationships` table to represent all the relationships between collectives. Main advantage: it's extensible and we would be able to represent all kinds of relationsips with it (parent, recommended, friends...etc).** Medium complexity.

My personal preference goes to (2) because it's a nice separation of concern, it's extensible, performant and the complexity is not too high. Its flexibility allows us to solve https://github.com/opencollective/opencollective/issues/2485 and https://github.com/opencollective/opencollective/issues/2141 too.

<details>
<summary>Other proposed solutions</summary>

(1) We add a new column (like `DependsOnCollectiveId`) for this specific use case (easy).
(3) We use the `Members` table. A new role must be added. Easy, but looks hacky to me.
(4) We decide that collective's children (including events) can have a different host id than the parent and decide to officially support this feature through `ParentCollectiveId` (complexity to be estimated).

</details>

## MVP

We should keep these changes backend-only for the MVP, but in the future it would be nice for users to be able to make the changes themselves.

## Metrics 

- How many Collectives have subcollectives
- Average number of subcollectives when there are some

## Documentation 

We should add a section in the documentation to tell users to contact support if they want to use child collectives.

## Related issues

https://github.com/opencollective/opencollective/issues/2485
https://github.com/opencollective/opencollective/issues/2141

**Comment by alanna** [comment]
Another data point to support this is a feature users want: this also came up in my recent conversation with the admin of Drupal Diversity and I think they would use it if it were available. They currently have multiple Collectives and it's caused some confusion about the relationship between them.

I'm not sure "subcollectives" is the right concept though, because the relationship is not necessarily hierarchical. How about simply "Connected Collectives"? 

To me it's as simple as connected Collectives showing up in a section called "Connected Collectives" on the Collective pages. If Collective A is connected to Collective B, then A shows up on B and B shows up on A.

I don't think it should matter at all which host any of the Collectives are in. In fact many times this will be needed specifically because they are in different hosts (eg. a group with a US branch and an EU branch). We should clearly define this feature as *not* connecting budgets or anything like that, to keep it simple. Moving money between the Collectives if they have different hosts should be enabled by #2017 as a seperate project.

**Comment by Betree** [comment]
> To me it's as simple as connected Collectives showing up in a section called "Connected Collectives" on the Collective pages. If Collective A is connected to Collective B, then A shows up on B and B shows up on A.

This sounds like a good and simple option for the MVP. We'll eventually be able to extend that to make it possible to create a hierarchy easily if we go with option (2).

It will also make it very easy to implement a recommendation system, so that Collectives can recommend some other Collectives to support. We need this for the (not implemented yet) `Other Collectives to support` section in the new collective page, and for https://github.com/opencollective/opencollective/issues/2565 for example.

I really think the solution (2) is the good way to go. Because it's a fairly simple and non-breaking change, I'll iterate soon if that's not a blocker for anyone.

**Comment by Betree** [comment]
Also @lsmith77 I forgot to mention you but may want to jump in the discussion :slightly_smiling_face:

**Comment by lsmith77** [comment]
We basically have two needs for sub-collectives:
1) different currencies
2) specific causes (like collecting money for speaker training, collecting money for conference scholarships). this way we want to offer donors more control over how their donations may be used.

I would add that in our case we really do want one collective to be considered the parent and others as the sub-collectives (especially for the cause specific collectives).

**Comment by Betree** [comment]
Thanks for the feedback @lsmith77!

Let's have a `type` column on `CollectivesRelationship` as an enum with the following values to represent that:
- `CONNECTED`
- `RECOMMEND`
- `PARENTING`

That will also create a safe ground to implement https://github.com/opencollective/opencollective/issues/2141 (`These Collectives are part of our Organization`, like on https://opencollective.com/fbopensource).

**Comment by gusaus** [comment]
Would the following be examples of what this functionality would support? 

- Working group or service collective
  - Group together projects/collectives the working group is contributing towards
  - The subcollectives for the most part would be hand-picked; not owned or hosted by the parent collective
- Community or meetup collective
  - Group together local meetup groups or chapters
  - Chapters may or may not have the same host as the parent collective

**Comment by alanna** [comment]
@lsmith77 for number 2, would the new dedicated tier pages and goals accomplish that or does it need a whole seperate Collective?

**Comment by lsmith77** [comment]
no it doesn’t need to be a separate collective as long as there is some tracking that makes it easy to know how much was donated for what cause. not sure if tier pages would provide this. but if there would be a virtual ledger it would be fine. 

another option I think I once raised as an approach would be that people could donated to a general pool but that when donating they could say if they trust the collective to allocate as they wish or if they want to be asked for each cause and then they can allocate the funds they donated to a specific cause.

**Comment by Betree** [comment]
> Group together projects/collectives the working group is contributing towards

Good point! I've added `CONTRIBUTING_TO` to the enum to represent that use case.

Also added `USING`, so that we can represent dependencies between projects with the same system.

**Comment by gusaus** [comment]
@Betree Glad I was able to make sense 😄 

I'll follow-up with some collectives that should be a good test case.

If the second use case is valid, a collective/subcollective trial for chapters/meetup groups for Open Collective and Sustain could be a good internal test.

**Comment by lsmith77** [comment]
just wanted to reference this stale ticket I originally created for this topic  https://github.com/opencollective/opencollective/issues/1620

this is another one that is clearly beyond on an MVP
https://github.com/opencollective/opencollective/issues/1587

**Comment by Betree** [comment]
When I wrote the specs two months ago I excluded the `Members` table option with the following message:

> (3) We use the Members table. A new role must be added. Easy, but looks hacky to me.

I now think that it's not a crazy solution, especially because we've added the `MemberInvitation` feature that we'll need if we want to build some UI around this (#1620) because you need both parties to accept the link before creating it: parents and children.

So I'm going to go with this solution by adding two new roles to the `Members` table:
- `SUBCOLLECTIVE` - intentionally not using the words Parent/Children to avoid creating confusion with event's `ParentCollective`. Sub-collectives should be displayed on the parent as they are today and eventually on the children's pages in the future - but referred as sub-collectives.
- `CONNECTED` - connected collectives should be displayed on both collectives in `More ways to contribute` with the tag `CONNECTED COLLECTIVE`.

**Comment by xdamman** [comment]
Not sure to understand the difference between SUBCOLLECTIVE and CONNECTED.

A good example is https://opencollective.com/XR-Belgium where you can see two types of child collectives: 
- a child by location, eg: XR Antwerp (on another host): https://opencollective.com/XR-Antwerp
- a child by topic, eg: XR Legal (on the same host but doesn’t have to): https://opencollective.com/XR-Belgium-legal

Now there should probably be a way to surface that connection the other way (from the child to the parent). 

I’m not a fan of the name “sub” because it implies a subordination and all those movements are actively trying to mitigate for power and avoid hierarchies. Parent/child seems better in that regard, or even connected. The difference between the two for me seems to be the creation process. XR Antwerp starter independently with other people. XR Belgium Legal is a “brain child” of the main XR Belgium collective and therefore starts with as default values, the same settings than the parent (like an event).

I know it’s only for the code base so feel free to use what you want but just wanted to make sure you have the proper context.

**Comment by Betree** [comment]
> Not sure to understand the difference between SUBCOLLECTIVE and CONNECTED.

For now I've only implemented `SUBCOLLECTIVE`. `CONNECTED` intended to describe the relation from https://github.com/opencollective/opencollective/issues/2633#issuecomment-554108548. The main difference between the two would be the wording: subcollective would be referred to as `Parent collective` / `Member collective` while `CONNECTED` would be referred to as `Connected` or `Linked`.

> I’m not a fan of the name “sub” because it implies a subordination and all those movements are actively trying to mitigate for power and avoid hierarchies. Parent/child seems better in that regard, or even connected.

Naming has been discussed in https://github.com/opencollective/opencollective-api/pull/3153. In the interface it's actually called `Member collective` because - as mentioned in https://github.com/opencollective/opencollective/issues/2633#issuecomment-572107583 - using children/parent could lead in a  confusion with the event system's `ParentCollectiveId`. Using parent/children in the interface would be fine tho.
