### ISSUE TITLE
Create gift cards form: simplify/clarify form

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2634]
The gift cards form has grown a bit too much lately and feels pretty complex:

![image](https://user-images.githubusercontent.com/1556356/68871408-aa7c0080-06fc-11ea-8b27-fa5dbbfd5239.png)

We can simplify that with two simple steps.

## 1. Collapse limitations by default

`Limit to the following hosts` and `Limit to the following collectives` can be collapsed by default. Let's use a `<detail>` HTML for that, with the `Limitations` label as a summary. This label must have the same font weight/size than other labels.

![image](https://user-images.githubusercontent.com/1556356/68870393-1bbab400-06fb-11ea-9759-62e1f68ab50a.png)

## 2. Show optional fields

We should display the `Optional` text under optional field's labels. Color must be `black.600`, fontWeight `normal`, react-intl key is `forms.optional`.

All optional fields must appear below required fields (but still above the "Send by email/I'll send the codes myself" toggle).

Optional fields are:
- Batch name
- Limit to the following hosts
- Limit to the following collectives

![image](https://user-images.githubusercontent.com/1556356/68870842-d34fc600-06fb-11ea-9f00-14464072f763.png)

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by jeffin143** [comment]
@Betree Looks easy , Can i take up this ?

**Comment by Betree** [comment]
@jeffin143 sure :+1:

**Comment by Betree** [comment]
:trophy: This issue is now completed by @jeffin143  

To claim the $200 bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
