### ISSUE TITLE
Retain budget data for archived Collectives

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2637]
It seems that when a Collective is archived, the only sections that remain are Updates, Contributors, and About. Why don't we show the budget history? I think it's important for transparency. I suggest we retain the budget section when a Collective is archived, and just disable the ability to add to or change it.

Example: https://opencollective.com/gatsby - I wanted to see how big their budget was, what expenses they had, etc, but all that data is gone.

**Comment by icaroharry** [comment]
Hi 👋 
I'm interested in contribute to the project. Can I work on that?

**Comment by znarf** [comment]
@alanna No reason to hide it. I imagine why it's hidden technically but we should definitely display it.

@icaroharry Feel free if you want.

**Comment by Betree** [comment]
Fixed in https://github.com/opencollective/opencollective-frontend/pull/3095
@icaroharry also proposed a fix in https://github.com/opencollective/opencollective-frontend/pull/3098
