### ISSUE TITLE
wrong message when trying to approve already approved expense

### ISSUE THREAD

**Issue by mixmix** [opencollective/opencollective#2638]
found an old expense email. Clicked `Approve`

GOT THIS. herp

![image](https://user-images.githubusercontent.com/2665886/68909345-de196200-07b2-11ea-83b6-e006f8994d4a.png)

**Comment by mixmix** [comment]
that text reads: 
> You can't reject an expense that is already paid

**Comment by mixmix** [comment]
1. I wasn't rejecting the expense
2. don't show me Red Warning when everything is fine

I recommend you just say "Sucess!"
Even if my approval was useless, approval should be idempotent - N approvals is the same as one. 

By showing an error here you're bumming me out. I like approving expenses because it feels like I'm helping, but this made me feel stupid and useless

**Comment by znarf** [comment]
Looks like this happening in https://github.com/opencollective/opencollective-api/blob/master/server/graphql/v1/mutations/expenses.js. This was not touched recently, last major update in https://github.com/opencollective/opencollective-api/pull/1102 Looks like the approve and reject  error messages are inverted.

That should be easy to fix, thank you for the report!

We will unfortunately not move forward with your improvement proposal now.
- in the way it's designed, "approving an approved expense" is not the same as "approving a paid expense", it's a change of status. Reading the code I don't think it would have failed if you would have tried "approving an approved expense", which is **kind of** idempotent
- we could make that clearer/better on the Frontend/UI part, but we're currently tackling a revamp of the "Expenses Flow" and this kind of improvements should be part of this effort

**Comment by mixmix** [comment]
cool, thanks for the context !

Looking forward to the new expense flow. Good luck!

**Comment by znarf** [comment]
@mixmix for the fun, there was even a test to make sure that it was wrong, https://github.com/opencollective/opencollective-api/pull/2893/files#diff-e6094d627461a9d299c2995259e60f7b
