### ISSUE TITLE
ERROR probot: pluginFunction is not a function

### ISSUE THREAD

**Issue by CanerSezgin** [opencollective/opencollective#2645]
**Describe the bug**
After installing new packages, I got started getting this error when I run server. It was working before updating node_modulus folder. 

**To Reproduce**
1. clone repo
2. npm install
3. npm run dev

**Expected behavior**
INFO probot: Open Collective Bot up!
INFO probot: Forwarding https://smee.io/xxxxxxxxx to http://localhost:3000/
INFO probot: Connected https://smee.io/xxxxxxxxx

**Screenshots**
![Screenshot from 2019-11-19 00-56-38](https://user-images.githubusercontent.com/38403291/69097731-375deb80-0a68-11ea-8436-8543ec5d7e29.png)

**Comment by znarf** [comment]
I had the problem yesterday, it's pretty simple.

You should use `yarn install` and not `npm install` in this project.
