### ISSUE TITLE
Back Your Stack hero text unreadable

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2646]
This is how the Back Your Stack front page looks to me:

<img width="1207" alt="Screen Shot 2019-11-19 at 3 48 52 PM" src="https://user-images.githubusercontent.com/5498878/69112017-1cc95800-0ae4-11ea-83cb-94789c19333a.png">

Using Chrome 78.0.3904.97 on Mac.

**Comment by alanna** [comment]
Same issue on a subsequent page:

<img width="661" alt="Screen Shot 2019-11-19 at 3 53 18 PM" src="https://user-images.githubusercontent.com/5498878/69112282-bd1f7c80-0ae4-11ea-95ac-ede32299e3d3.png">

**Comment by znarf** [comment]
@alanna Alyssa faced that too. I don't remember what it was. Can you try disabling your extensions one by one?

**Comment by alanna** [comment]
Huh... strangely now I can't reproduce this again, either in my normal browser with extensions or in another browser with no extensions.

**Comment by alanna** [comment]
This issue is affecting @awright and blocking her from showing it to potential customers. I think it needs to be fixed with priority. If the background can't easily be fixed, please just make it white for now until we can fix it properly.

**Comment by piamancini** [comment]
I can't reproduce anywhere either.

**Comment by Betree** [comment]
Tried on Ubuntu 19.10 with Opera, Chrome, Brave and Firefox (all of them up-to-date). Wasn't able to reproduce.

**Comment by znarf** [comment]
I will have a call with @awright to look at that tomorrow. Fortunately, she told me she was not exactly blocked by this issue!

**Comment by znarf** [comment]
No one can reproduce anymore. Closing until it's reported again.
