### ISSUE TITLE
Pricing page has a view issue when expanding multiple FAQs

### ISSUE THREAD

**Issue by GriffGreen** [opencollective/opencollective#2649]
<img width="1407" alt="Screen Shot 2019-11-20 at 10 11 51 PM" src="https://user-images.githubusercontent.com/14945613/69250901-17066c00-0be3-11ea-95a5-f46709d59732.png">

**Comment by znarf** [comment]
Thank you for the report. I think it's duplicate with https://github.com/opencollective/opencollective/issues/2460
