### ISSUE TITLE
Collective page performance

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#265]
We got this email from Tobias Koppers of Webpack:

---
Heyho

The webpack collective is working great so far. Thanks for providing this service.

I'm writting to you because I think you site has a serious performance problem. At least for the webpack collective.

![](https://cl.ly/1Y0g2u3k2q3e/pasted1.png)

I can hardly use the site on desktop and it crashes often on mobile.

Even with everything cached it's really slow: ![](https://cl.ly/1O1v3I3f1X02/pasted3.png)

Here are some issues that I discovered and should really be adressed:

* The main bundle is 350kb and takes 3s! to execute (including a forced reflow of 1.5s). Do you really need all this JS on every page? Consider splitting it and only load the JS you need on the current page. Load stuff on demand. Remove unneeded stuff.
* Take a look at your dehydrated initial state. It contains functions: "function Connect(props, context) {" This can't be correct.
* Check if react reuses the server-side rendering.
* I think you tried to proxy the images to include them in a smaller size. Great idea, but it doesn't seem to work for all images  https://opencollective.com/proxy/images/?src=https%3A%2F%2Fres.cloudinary.com%2Fopencollective%2Fimage%2Fupload%2Fv1476472821%2Ficon-big_x6ot1e.png&height=320 still returns the 1200x1200 image for webpack.
pasted3
* This causes may requests.
  * Consider rendering a single image on server and use this. Hint: <map>-tag.
  * At least request smaller images. Currently they are 480x480. 48x48 may be better suited for the small image...
* Note that you may not notice this problems with a fast connection and fast computer. Try throttling in devtools...

I really hope you could concentrate on performance improvements. That's really important. You (and we) probably lose donors because of this.

Greeting

---

**Comment by asood123** [comment]
Adding my response here for completeness:
---

We hear you on all those issues and are working on fixing them. We are new to React, Redux, etc, so figuring this out as we grow.

A few of the things you mentioned like image loading issues - we are going to get those fixed in next few days. 

Moving to Webpack is top of our list. In fact, we are helping [fund](https://medium.com/open-collective/asking-for-a-new-feature-on-an-open-source-project-3305deba1356) Server-side Rendering support in React-boilerplate, so we can switch to it asap.

**Comment by xdamman** [comment]
We reduced the size of the avatars: https://github.com/OpenCollective/opencollective-website/pull/550
And we now generate the mosaic of contributors from the server which reduces the number of network calls from a few hundreds to just one: https://github.com/OpenCollective/opencollective-website/pull/552

All in all, we reduced the load time of the webpack collective page by 3x (24s to 8s) and the total data transferred by 5x (from 32.2MB to 5.8MB).
