### ISSUE TITLE
How should we handle spammers?

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2650]
Opening this issue to discuss our options regarding spammers, following a request from WWC in https://opencollective.freshdesk.com/a/tickets/3052, https://opencollective.freshdesk.com/a/tickets/3053 and https://opencollective.freshdesk.com/a/tickets/3054 to block someone submitting expenses to their collectives.

---

We have two paths that we need to be able to solve:

1. Users submit expenses that are clearly SPAM. 
  Example: https://opencollective.com/bubis-makaronas. 
    - What should be our policy to ban these users? How should we proceed?
    - Possible option: introduce a `limited` mode for users, blocking all community actions (submit expenses, contact...etc) and showing a banner at the top `Your account has been limited. Please contact support if you think this is a mistake.`

2. Users submit expenses that it's unclear if they're SPAM or not. Definitely not enough to ban the users, but WWC are asking if they can block them. Example: https://opencollective.com/sarah-harder
    - We could re-use the system implemented in https://github.com/opencollective/opencollective-api/pull/2808, but it completely blocks the feature for the user (and not only for this collective).
    - Like on Github, add a feature to block users from a collective

**Comment by sbinlondon** [comment]
_1. Users submit expenses that are clearly SPAM._

I agree with the idea of limited mode for spammers. Whatever we do, we should show a banner to a user letting them know that we've taken action (whether it's limiting or fully blocking the account) just in case it's a false positive.

_2. Users submit expenses that it's unclear if they're SPAM or not._

Community moderation is really important no matter what the reason, so I think having a Github-style feature to block users from a collective is a great idea. It can be used for spammers, harassers, etc.

Maybe we can give communities the option to set a minimum bar to clear before you are able to do certain things? i.e. you have to set a profile photo before being able to claim an expense. This would maybe make it a little harder for spammers to do this stuff?

**Comment by alanna** [comment]
Related: #2002 #2006

**Comment by Betree** [comment]
Another example of expenses as a SPAM vector: https://opencollective.com/lord-justine#section-transactions

We need an option to flag a user as "banned" to prevent them from doing any further action on the website.

**Comment by Betree** [comment]
Followed up with the limited account idea in https://github.com/opencollective/opencollective/issues/2695

We still need to define a procedure for banning users permanently.

**Comment by alanna** [comment]
Example of a slightly different flavor of spam, where they are hoping we'll just pay without looking too closely, as opposed to posting for linkspam or pageviews: https://opencollective.com/madrid-retreat-1ev/expenses/12316

**Comment by Betree** [comment]
@alanna I've seen a bunch of these lately (and removed some).

**Comment by Betree** [comment]
This discussion has now been turned into a project: https://github.com/opencollective/opencollective/issues/2741
