### ISSUE TITLE
Ready to pay expenses not showing up on dashboard

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2653]
Users are getting in touch about expenses they expected to be paid and it turns out that  they are not being shown on "ready to pay" in the host dashboard so we are missing them.

Examples:

* https://opencollective.com/network-time-foundation/expenses/9228
* https://opencollective.com/hyper-star-samsung-next-decentralization-grant/expenses/11522

The first one has already been paid. The second one I am holding off on so this can be looked into, but by the time we're alerted to these the user is already unhappy at the delay and has contacted us, so we end up having to pay them right away.

**Comment by alanna** [comment]
I feel like I have seen this come up multiple times when the expense amount = 100% of the Collective balance (as is the case for both these examples) and I strongly suspect that's related.

**Comment by znarf** [comment]
Reported in the past as https://github.com/opencollective/opencollective/issues/2144 But it was closed without being fixed.

**Comment by alanna** [comment]
This change seems to have created a bug: now expenses with insufficient balance are showing in "ready to pay".

**Comment by znarf** [comment]
This is already taken care of in https://github.com/opencollective/opencollective-frontend/pull/3074. Will be part of next deploy.
