### ISSUE TITLE
Include IP address in sign in emails

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2654]
## User story 
@piamancini got an sign in email a few months ago that she did not requested ([see the conversation here](https://opencollective.slack.com/archives/C0RMV6F8C/p1570451028191600)). We were not able to investigate much because we don't log the IP address of users who try to sign in.

## Best solution for this problem
We need to be able to retrieve some information about who requested a sign in token, at least the IP address.

## MVP
Add a small grayed message in the email like this:
> This sign in email email was requested by `00.00.00.00`. If you did not request this email, please inform support@opencollective.com.

**Comment by znarf** [comment]
@Betree can you link to the conversation with pia?

@Betree is it really best practice? should we consider some anonymized version instead? what are others doing?

**Comment by Betree** [comment]
> @Betree can you link to the conversation with pia?

My bad, just edited the issue with the link.

> @Betree is it really best practice? should we consider some anonymized version instead? what are others doing?

I wouldn't do anonymized: if someone tries to break into your account I don't think that sharing their IP address is a violation of privacy.

When trying to login on sites like Scaleway (hosting provider) or Steam or Humble Bundle (games) you get an email with the IP address disclosed:

![image](https://user-images.githubusercontent.com/1556356/69856309-a5d35280-128d-11ea-8551-dc94d85208c9.png)


![image](https://user-images.githubusercontent.com/1556356/69856191-5e4cc680-128d-11ea-8056-a203f66973fe.png)

![image](https://user-images.githubusercontent.com/1556356/69856255-84726680-128d-11ea-89cb-35faccc0593d.png)

**Comment by znarf** [comment]
@Betree good examples, let's do it then

**Comment by jeffin143** [comment]
@znarf let's close this since this is done :)

**Comment by CanerSezgin** [comment]
I just realized that there are two email in this message, I think this is a mistake right ? I had directly copied from @Betree 's message to the code. 
_This sign in **email email** was requested by 00.00.00.00. If you did not request this email, please inform support@opencollective.com._

**Comment by Betree** [comment]
@CanerSezgin good catch! Do you want to open a PR for it?
