### ISSUE TITLE
Improve the docs about how to link to backer's custom website?

### ISSUE THREAD

**Issue by mrdulin** [opencollective/opencollective#2655]
Now, I am using the backer avatar link below:

```
<a href="https://opencollective.com/slideshowp2#backers" target="_blank"><img src="https://opencollective.com/slideshowp2/backers.svg?width=890"></a>
```
This link will not link to backer's custom website. How could I do that?

I read the docs: https://docs.opencollective.com/

But didn't find the docs about how to link to backer's custom website by the backer's avatar.

Github Repo: https://github.com/mrdulin/blog
opencollective: https://opencollective.com/slideshowp2

Thanks.

**Comment by znarf** [comment]
@mrdulin It should link to their website if they have one set in their Open Collective profile. This is not the case for the 2 featured backers.

**Comment by znarf** [comment]
Closing. Feel free to reopen if that didn't solve your problem.
