### ISSUE TITLE
Update changelog nextjs custom server to nextjs serverless route for Now 2.0

### ISSUE THREAD

**Issue by flickz** [opencollective/opencollective#2656]
Following up the creation of [changelog]( https://github.com/opencollective/opencollective-changelog) from https://github.com/opencollective/opencollective/issues/1674, 

Changelog uses custom nextjs server which is no longer supported for `Now 2.0` deployment. In order to deploy to Now 2.0, we need to update to nextjs custom serverless route.

https://zeit.co/guides/custom-next-js-server-to-routes/

**Comment by flickz** [comment]
Deployed https://opencollective-changelog.now.sh/

**Comment by znarf** [comment]
Doesn't seem to work.
