### ISSUE TITLE
Excessive amount of requests when opening the expenses page of a collective.

### ISSUE THREAD

**Issue by jzabala** [opencollective/opencollective#2658]
**Describe the bug**
When you open the expenses page of a collective, too many requests are fired to the GraphQL api.

**To Reproduce**
1. Go to https://opencollective.com/webpack
2. Open the DevTools and go to the network tab.
2. Click on **View all expenses**
![Screen Shot 2019-11-26 at 7 22 26 AM](https://user-images.githubusercontent.com/1315054/69626085-4ae7f400-101e-11ea-84f2-a966cf91bde5.png)
3. See all the requests that are fired.

**Expected behavior**
Should fire only one request.

**Screenshots**
![Nov-25-2019 21-00-25](https://user-images.githubusercontent.com/1315054/69626006-21c76380-101e-11ea-9ad3-e2e726b15091.gif)

**Comment by Betree** [comment]
Duplicate of https://github.com/opencollective/opencollective/issues/2519.

It's ugly, but we don't want to fix it since we'll be revamping the expenses feature entirely very soon.

**Comment by jzabala** [comment]
> Duplicate of #2519.
> 
> It's ugly, but we don't want to fix it since we'll be revamping the expenses feature entirely very soon.

Alright. Closing this one 🙂
