### ISSUE TITLE
Rename "Manual Payments" orders from PENDING to MANUAL

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2659]
Today, in the DB, we mark Manual Payments pending confirmation as `PENDING` but this is causing confusion because the `PENDING` state is shared for multiple things. 

This was originally outlined here: https://github.com/opencollective/opencollective/issues/1994#issuecomment-503435051

To clarify the behavior, Manual Payments should be internally renamed as `MANUAL` or `UNCONFIRMED` or `PENDING_CONFIRMATION`.

The change will impact the whole feature, from the _initial order submission_, to the _host dashboard_. This needs to be tackled cautiously.

**Comment by znarf** [comment]
We still should do that.

**Comment by franciscotv** [comment]
hello, is the complexity of this task, *medium or simple*?, **both**? is there somewhere documented what the categories of ***complexity*** means in terms either on time to spend on the task ___or___ the know-how needed for completing that task?.
Please let me know your thoughts.
Regards.

**Comment by znarf** [comment]
It's a medium. Multiple changes over API and Frontend. Might take 1 or 2 days for someone with past experience with our codebase.

**Comment by znarf** [comment]
Was implemented in https://github.com/opencollective/opencollective-api/pull/4431
