### ISSUE TITLE
Does WeChat extension repo really belongs to the Open Collective?

### ISSUE THREAD

**Issue by XVilka** [opencollective/opencollective#2661]
I noticed the https://github.com/opencollective/WeChatExtension-ForMac repository, which doesn't really look relevant to this organization's account. Apologies if I am wrong.

And it is even out of sync with the original repository: https://github.com/MustangYM/WeChatExtension-ForMac

**Comment by znarf** [comment]
No, the repository was just forked on our organization to let them setup their Open Collective.

**Comment by XVilka** [comment]
Hmm, but it is not a requirement, right? Because we (radareorg) succesfully set our Open Collective without the fork.

**Comment by znarf** [comment]
No, it's just done sometimes by someone in the team to help Collectives setup their Readmes etc ...

**Comment by XVilka** [comment]
@znarf I see. In my opinion, it is better to separate then from this organization account. Otherwise it will quickly become a mess. It already did in fact. Or if you have a bot, it can remove the fork after PR was sent - the PR itself is stored in the target repository, so it will be kept even if the fork was removed.

**Comment by znarf** [comment]
I agree it's not looking good. It's a bit of a problem to clean now that we have around 1000 repositories like that.

**Comment by XVilka** [comment]
You can list only forks in the GitHub and remove them in a batch:
https://github.com/opencollective?utf8=%E2%9C%93&q=&type=fork&language=
