### ISSUE TITLE
Updated Pricing Implementation

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2662]
## Rationale

Open Collective is strategically focusing on a platform for Hosts (including Self Hosted Collectives). Hosts are the customers of Open Collective. As part of this effort, an updated pricing plan is being discussed and implemented.

Today, some Hosts are currently using the platform for free because because they're not using the donation feature and more relying on "Add Funds" and "Manual Transfers". Having customers using the platform for free is not sustainable and the idea is to start making Hosts pay a monthly fee based:
- on the amount of data managed on the platform through "Add Funds" and "Manual Transfers"
- the total number of collectives hosted

As part of this effort, we'll want to implement some restrictions on the platform. Hosts will need to subscribe to a plan:
- to host multiple collectives
- to access to the "Host Dashboard"
- to add more than 1000$ to the platform using "Add Funds"
- to activate "Manual Transfers"

**Note**: Some upcoming new features will only be available to paying customers. All existing Hosts will be able to enjoy the same features they're using today for free for at least one year.

## Implementation

- Start clearly differentiating Hosts in the model (API, Frontend?)
- Add a column to the model containing the plan Hosts are currently using (API)
- Update plan in the DB when customers subscribe to the Tier (API)
- Check restriction before hosting new collectives (API, Frontend)
- Check restriction when "Adding funds" (API, Frontend)
- Check restriction when activating "Manual Transfers" (API, Frontend)

**Comment by kewitz** [comment]
TODOs:
- [ ] Add blockers/validations to DeactivateAsHostCollective.
- [ ] Hook to assign a plan when subscribing to an OpenCollective tier plan.
- [ ] Hook to un-assign plan when unsubscribing from an OpenCollective tier plan.
- [ ] "Host" section in the Collective settings displaying the current plan and limits.
- [ ] Add usage info to the Collective Plan resolver.
- [ ] Add frontend information about the plan limits and current usage.

**Comment by znarf** [comment]
New Todos:

- [ ] Make sure "Downgrade" and "Upgrade" are used for the Button when that make sense
- [ ] Prevent downgrading based on the current usage

**Comment by kewitz** [comment]
@znarf I implemented Downgrade and Upgrade based on the tier price.
The prevention of downgrade based on usage will require us to include plan limits in the tier meta-data.

**Comment by znarf** [comment]
@kewitz let’s do it ?

**Comment by kewitz** [comment]
On it.

**Comment by kewitz** [comment]
Pending from QA:
- [ ] Validate current plan limits when assigning collectives to own host.
- [ ] Disable "Receiving Money" on Payment Methods when plan.manualPayments is false.

**Comment by znarf** [comment]
New round of feedback after review with @piamancini:

- [ ] Add free plan in the pricing table
- [ ] Re-introduce "single host plan"
- [ ] Add "Network Plan" / Contact Us as 6th plan (optional, but it will look better if we have 2 lines)
- [ ] Move plans on a layout of 2 rows, three columns on regular screen (maybe stop using <table>)
- [ ] Border or Background for current plan instead of grey (selected, not disabled)
- [ ] Remove "Host Dashboard" from pricing as it's available for everyone. We can keep the flags for the future.
- [ ] Edit Organization/User: separate host features in the menu, on the bottom after a line break
- [ ] Host Settings: add tool-tips in "usage" section to explain what are "Added Funds" and "Manual Payments"
- [ ] "Use my own host" should be able to apply to an host without Stripe connected
- [ ] When over limit, "Add Funds" should be greyed out in Host Dashboard with a message explaining why
- [ ] "Apply" button should be visible for Host reaching limit (it's hidden now). It should be disabled with a message explaining why.

**Comment by kewitz** [comment]
@znarf what should we do with the button on the `Free` plan?

**Comment by znarf** [comment]
@kewitz not much choice, no button for now I think

**Comment by piamancini** [comment]
Manual Payments Tooltip: _Your contributors create a pending donation and receive email instructions with your bank details. You can reconcile the donation when you receive it_

Updating docs to use until pricing page is done: https://docs.opencollective.com/help/about/pricing

**Comment by kewitz** [comment]
Sice Network will be a "Contact Us" button, can I soft-delete the Network tier in production?

**Comment by piamancini** [comment]
@kewitz what would the path to contact us be?

**Comment by kewitz** [comment]
@piamancini `mailto:support` as of now, super MVP but my current problem is consistency.
I think we should either have _Network_ as a tier that has a price and can be self-subscribed or it shouldn't be directly accessible from the collective page (hence soft-deleting it).

**Comment by znarf** [comment]
Please delete @kewitz

**Comment by piamancini** [comment]
agreed.

**Comment by piamancini** [comment]
had a good chat with a host just now (netsquared). Their feedback is that pricing looks good and fair. Only thing for them is that sometimes a collective leader leaves and they spend a long time recruiting a new one. (Their collectives are meetups in cities). All that time, they feel like it's unfair to count the collective in the host collective count, they'd like a way to 'deactivate' collectives that are not being used and as soon as they are alive again, they are more that happy to pay for them.

**Comment by Betree** [comment]
@piamancini Maybe archiving is the solution? We could omit the archived collectives from the count. They can then re-activate the collectives when they want, only drawback is that they'll need to empty the collective balance before archiving.

**Comment by znarf** [comment]
Completed!
