### ISSUE TITLE
GraphQL V2: "Account" object type is confusing

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2663]
In [graphql v2](https://github.com/opencollective/opencollective-api/blob/366ae80b95df5a3d3a4b7ac224629282b8c166d5/server/graphql/v2/interface/Account.js#L267) I find that using the word `Account` for grouping collectives/users/events...etc is confusing. In most systems I've encountered an account is what you use to login somewhere and that contain your personal info, you expect it to have an email (the equivalent of our Users table).

Example: On Facebook, you refer to your "Account" then you create "Pages" and "Groups".

### Proposal

I suggest using `Profile` which matches the wording that we've used in places like the contribution flow where we refer to them as "Contribution profiles".

---

Ping @znarf @jzabala

**Comment by Betree** [comment]
I stumbled upon this again today. I really think we should address this as we're going to increasingly use V2 in our code, would be better if we can avoid naming all variables `account`.

@znarf any opinion on this one?

**Comment by Betree** [comment]
Note: renaming schemas objects can be done cleanly and without breaking anything by using [schema transforms](https://www.apollographql.com/docs/graphql-tools/schema-transforms/).

**Comment by znarf** [comment]
I'm fine with Account (I picked it carefully back then) but I'm good with the change to Profile. Do we have other potential alternatives for a better name?

**Comment by Betree** [comment]
Account does describe what it is, it's not a wrong name and I can get used to it. I just think there's a risk of creating confusion for newcomers because "Account" if often used to describe a way of login in (what we internally call `Users`).

> Do we have other potential alternatives for a better name?

I can only think of `Indentity`, which could also be confusing.

**Comment by znarf** [comment]
For Organization, I think `account` is ok. Ie: https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-organizations#organizations-and-enterprise-accounts

The most disturbing is Events, definitely not an `account` but neither a `profile`.

**Comment by Betree** [comment]
> The most disturbing is Events, definitely not an account but neither a profile.

Good point. It's actually hard to think of a term that will better describe something so generic.

The fact that Github does use this terminology tends to demonstrate that my point above about confusion doesn't stand. I'm convinced, let's keep account!
