### ISSUE TITLE
Images are not loading in your How it works page

### ISSUE THREAD

**Issue by sbhol2008** [opencollective/opencollective#2666]
Hi,
Images are not loading in your How it works page.
URL: https://opencollective.com/how-it-works
Browser: Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)
Screenshot: https://i.imgur.com/EoSrvNy.gifv
Thanks!

**Comment by znarf** [comment]
Thank you for the report!

**Comment by znarf** [comment]
It's a regression coming from an update of `file-loader`, we'll rollback while investigating. https://github.com/opencollective/opencollective-frontend/pull/3076

**Comment by gmarcos87** [comment]
Hi @znarf, if you want to keep the latest version of image-loaders add ``` esModule: false``` at https://github.com/opencollective/opencollective-frontend/blob/4d8e7edd033a9e205cb672179c2519aa88be790f/next.config.js#L80

**Comment by znarf** [comment]
@gmarcos87 Done that. https://github.com/opencollective/opencollective-frontend/pull/3083
