### ISSUE TITLE
Organization avatar display bugs

### ISSUE THREAD

**Issue by Olegt0rr** [opencollective/opencollective#2668]
## Description
Something went wrong with your organizations avatar generation service.

## Organization PNG 
<img src="https://i.ibb.co/gWTKHCz/Screenshot-2019-11-30-at-11-16-16.png" alt="Screenshot-2019-11-30-at-11-16-16" border="0">
`https://opencollective.com/aiogram/orgranization/0/avatar.png`

## Organization SVG 
<img src="https://i.ibb.co/YLKndPC/Screenshot-2019-11-30-at-11-15-50.png" alt="Screenshot-2019-11-30-at-11-15-50" border="0">
`https://opencollective.com/aiogram/orgranization/0/avatar.svg`

## Expectations
Square picture 64x64 without empty spaces
<img src="https://i.ibb.co/DkV5xKv/Screenshot-2019-11-30-at-11-29-52.png" alt="Screenshot-2019-11-30-at-11-29-52" border="0">

**Comment by Betree** [comment]
Hi @Olegt0rr, thanks for reporting this issue. Can you provide the raw image that you tried to upload?

If it has spaces on the sides I'm afraid there's not much we can do at the moment, we don't have a cropper in place for the avatar.

**Comment by Betree** [comment]
Ah my bad, I understand now that there's an unnecessary padding even with properly squared logo https://opencollective.com/aiogram/organization/0/avatar

**Comment by znarf** [comment]
@Olegt0rr In your report, the screenshots for SVG and PNG are inverted.

I'm not sure why the SVG is wrong. I think it's best to use the PNG version from now.

The behavior I see in the screenshot for the PNG is the normal one. I'm not sure about the rationale for this size but it's what everyone is using for years. See for example https://github.com/babel/babel

**Comment by Olegt0rr** [comment]
@znarf 
Your example is wrong. I'll be happy if my organization avatars will be similar size :)

 Any of output format should be FULL filled with my square picture.
Just because it's a SQARE and more than 64x64 in original size.

Your outputs:
PNG - 162x64 
SVG - 64x64 with 16x16 avatar within it

Please check the original avatar size on org page: https://opencollective.com/truemafia

**Comment by Olegt0rr** [comment]
Still actual

**Comment by evelynhathaway** [comment]
Since you mentioned it only happened with SVGs, I figured it would be an easy fix! And I think it was.

If anyone in this thread is interested, the PR is available here: https://github.com/opencollective/opencollective-images/pull/400
