### ISSUE TITLE
Links to organization site are not working

### ISSUE THREAD

**Issue by Olegt0rr** [opencollective/opencollective#2669]
# Descriptions
Something went wrong when I use `organization` and `organizations` in your service links.
Some examples use different ways and I've checked it out:

## `organization`
Link is wrong
`https://opencollective.com/aiogram/organization/0/website`

Image is OK (but have a bad size #2668)
`https://opencollective.com/aiogram/organization/0/avatar`

## `organizations`
Link is OK
`https://opencollective.com/aiogram/organizations/0/website`

Image is OK (but have a bad size #2668)
`https://opencollective.com/aiogram/organizations/0/avatar`

**Comment by znarf** [comment]
Looks like the link is correct now. Maybe some temporary cache issue?

**Comment by Olegt0rr** [comment]
Not it works fine
