### ISSUE TITLE
set background style default to no-blur 

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#267]
add a setting that allows to switch that from backend.

**Comment by asood123** [comment]
Based on a couple of quick queries, we have 45 collectives (of ~300) with a backgroundImage. Should we add blur to all of them? Or flip it and handle it case by case once they say something?

Here's the query:
```
select 
	slug,
	"backgroundImage",
	settings::json->'style' as style
from "Groups"
where "backgroundImage" is not null
```

**Comment by asood123** [comment]
https://github.com/OpenCollective/opencollective-api/pull/680
https://github.com/OpenCollective/opencollective-website/pull/556

Also need to add blur to settings of those collectives that want it (can do that now, no need to wait to merge).

**Comment by piamancini** [comment]
Whatever is simpler for you now and it does not imply a lot of front end changes when we pass the functionality to the users. If we force it now, we need to add later the 'remove blur' functionality for users. If we don't force it, when someone can't do it themselves, we can manually to it from the backend (this are going to be very few). We haven't added blur ourselves for quite some time.

**Comment by asood123** [comment]
Ok then merging those two PRs should do the trick.
