### ISSUE TITLE
Unable to contribute as Collective due to insufficient funds, but there are enough funds

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2670]
I am trying to contribute from the [Open Collective Collective](https://opencollective.com/opencollective) to the [Open Collective Documentation Collective](https://opencollective.com/documentation) (same host, Open Collective Inc), based on our recent decision to allocate some budget for ongoing documentation work. There is over $60k in the Collective balance, but it's saying there are insufficient funds for a $1200 payment.

<img width="699" alt="Screen Shot 2019-12-02 at 1 00 13 PM" src="https://user-images.githubusercontent.com/5498878/69922786-256a5700-1504-11ea-996d-617fcadaff4c.png">
<img width="1221" alt="Screen Shot 2019-12-02 at 12 59 31 PM" src="https://user-images.githubusercontent.com/5498878/69922792-2ac7a180-1504-11ea-9764-4d0593be6171.png">

**Comment by znarf** [comment]
@alanna This is not what I see.

1. Picking: Open Collective (Collective)

<img width="953" alt="Capture d’écran 2019-12-10 à 14 41 37" src="https://user-images.githubusercontent.com/806/70534381-444b9780-1b5b-11ea-8788-e1488ea02736.png">

2. I see  
<img width="742" alt="Capture d’écran 2019-12-10 à 14 41 06" src="https://user-images.githubusercontent.com/806/70534429-588f9480-1b5b-11ea-896a-c38f9931e436.png">

**Comment by znarf** [comment]
Removing priority as it's investigated.

**Comment by znarf** [comment]
Will proceed with the changes.

**Comment by znarf** [comment]
Taken care of.
