### ISSUE TITLE
Budget section missing from Collective page

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2671]
There was a support request related to https://opencollective.com/DragonetMC so I went to look at their expenses and budget, but the whole section seems to be missing from their page. In the host dashboard I can see they have multiple past expenses.

**Comment by znarf** [comment]
@Betree do you have an idea?

**Comment by Betree** [comment]
Will be resolved in https://github.com/opencollective/opencollective-frontend/pull/3095

In the mean time you can check the transactions on https://opencollective.com/DragonetMC/transactions
