### ISSUE TITLE
Wrong donation amount value display

### ISSUE THREAD

**Issue by zicmama** [opencollective/opencollective#2674]
**Describe the bug**
https://opencollective.com/fred-renault is contributing for 20€
but is related to 5€ on contributors page:https://opencollective.com/monnaie-libre

**Comment by znarf** [comment]
There is effectively something wrong. fred-renault used to be a  5€ donator but is a 20€ since january last year.

**Comment by znarf** [comment]
@Betree maybe can you have alook?

**Comment by Betree** [comment]
Hi @zicmama, thanks for reporting this issue. It should be fixed now:

![image](https://user-images.githubusercontent.com/1556356/70057819-1952c800-15de-11ea-8fc7-0cf68049fb13.png)
