### ISSUE TITLE
Re-organize API's tests

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2675]
Today API's tests are all in the same folder, eventually grouped by name prefixes (eg. `graphql.xxx.test.js`). 

This is hard to navigate and doesn't provide a clear pattern about what kind of tests we expect.

## Proposal

- Rename all `{testName}.js` to `{testName.test.js}`
- Re-organize the entire `test` directory like this:

```
test
├─ mocks
├─ support
├─ cron
├─ server
│   ├── models
│   │   ├── Comment.test.js
│   ├── graphql
│   │   ├── v1
│   │   ├── v2
│   │   └── common

**Comment by Betree** [comment]
No blocker has been mentioned here so I'll iterate with the proposed solution this week.

**Comment by znarf** [comment]
As a result, could be interesting to parallelize tests in CI, so we can execute even faster.
