### ISSUE TITLE
Review 10mn policy for expenses

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2677]
In Expenses, there is a 10 min policy:

- // admin of collective can reject the expense for up to 10mn after approving it
- // we can approve an expense for up to 10mn after rejecting it

See:
https://github.com/opencollective/opencollective-frontend/blame/cfa9224074bc25fc569a99313102a2446624994a/src/apps/expenses/components/Expense.js#L121

Should we reconsider this?

**Comment by alanna** [comment]
What is the purpose of this 10 min policy? And how does it work in practice?

**Comment by znarf** [comment]
> What is the purpose of this 10 min policy?

I have no idea. It was implemented more than 2 years ago.

> And how does it work in practice?

If I understand well:
- it prevents a collective admin to change their mind and reject an expense 10 minutes after it was approved
- it prevents a collective admin to change their mind and approve an expense 10 minutes after it was rejected

**Comment by alanna** [comment]
I'm not aware of anyone using this and I haven't used it myself. I think we should allow unapprove and unreject at any time by admins anyway.

**Comment by znarf** [comment]
@alanna Was also surprised to see that, and surprised no one had complained ever? We we'll remove this behavior.

**Comment by piamancini** [comment]
I think we can safely remove.

**Comment by znarf** [comment]
This should be done.

**Comment by Betree** [comment]
The new expense page doesn't implement this behavior, I think we can safely close.

**Comment by znarf** [comment]
@Betree We need to delete the old components.

**Comment by Betree** [comment]
The behavior has been deprecated in the new flow and old components are removed
