### ISSUE TITLE
Toggle "new related collectives" in thank-you email to donors

### ISSUE THREAD

**Issue by heyakyra** [opencollective/opencollective#2681]
## User story 
As collective, I can either want to be found by similarity to other projects and be discoverable among many projects, or be standalone and independent so that we can establish our own identity. The section of "New related collectives" in the thank you email diminishes the second possibility and comes off as unprofessional for many nonprofit organizations.

## Best solution for this problem
Have an option to enable or disable the "new related collectives" section of the thank you email which would also control whether your collective appears in that section for others.

**Comment by znarf** [comment]
@heyakyra Thank you for pointing on that.

I personally think this "New related collectives" is not great and should be removed.
