### ISSUE TITLE
Credit card expiration handling part 1: update payment page

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#2683]
Relates #2672

## User story 
_As user, I can access a simple page via an email link so that I can input my new credit card details and it will update all the subscriptions attached to the old one_

## Best solution for this problem
- A plain page based on the "redeem"/"redeemed" pages for gift cards
- Using the credit card form found on the "contribute" page
- The page will tell me once it's updated the subscription

## MVP
Two-state page:

- [x] state 1: a credit card form
- [x] state 2: confirmation that subscription has been updated

Updating multiple subscriptions will occur in part 2 after we've written the new GraphQL mutation.

## Stretch
- [x] show the user which subscriptions will be updated
- [ ] rainbows and unicorns 😜🌈 🦄 

## Metrics 
 _tbd_

## Documentation 
 _tbd_

## Details
- get payment method id from LoggedInUser info
- URL slug to be something like `opencollective.com/paymentmethod/:id/update`

**Comment by sbinlondon** [comment]
@Betree @znarf

**Comment by znarf** [comment]
Completed!
