### ISSUE TITLE
Collective goals not showing

### ISSUE THREAD

**Issue by ivaylokenov** [opencollective/opencollective#2688]
**Describe the bug**
My collective goals are not showing on the main page, even though I have turned it on in settings. Link to the collective: https://opencollective.com/mytestedaspnet

**To Reproduce**
1. Go to https://opencollective.com/mytestedaspnet

**Expected behavior**
Goals showing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest

**Comment by Betree** [comment]
Hi @ivaylokenov, thanks for reporting this issue. The root cause has been identified and a fix should be deployed today.
