### ISSUE TITLE
Expenses duplicated on host dashboard

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2689]
After clicking "load more" sometimes the host dashboard shows the same expense duplicated multiple times. This is super problematic and- it just caused me to make a big overpayment to a user because I added up the total of all expenses shown and sent the funds, only to later realise some of them were duplicated.

Here's an example of how it looks:

![Screen Shot 2019-12-06 at 12 34 24 PM](https://user-images.githubusercontent.com/5498878/70283290-7be9d500-1825-11ea-91ca-95f3166fb8f7.png)

**Comment by flickz** [comment]
I'm sorry for this experience, while I couldn't reproduce the issue locally but I was able to figure out what could be wrong in relation with https://github.com/opencollective/opencollective/issues/2690 and I opened a fix.
