### ISSUE TITLE
Issue with top bar overflow on mobile

### ISSUE THREAD

**Issue by sedubois** [opencollective/opencollective#269]
E.g when viewing opencollective.com/preact on iOS 10 Safari, the top bar entries "SUPPORT US" and "BUDGET" overflow outside of the black backround and become invisible because their color is white. Scrolled over a color button in picture below to make visible.

![img_0046](https://cloud.githubusercontent.com/assets/4217871/20649228/ecef42b8-b4c2-11e6-8424-3d50e5790f07.PNG)

**Comment by xdamman** [comment]
Yes. Not sure how we can fix that.
I guess the best would be to be able to swipe left and right but not sure how to implement. 
We could also have a hamburger menu. All those details take time :(
