### ISSUE TITLE
Expense comments showing in reverse order

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2691]
[These comments](https://opencollective.com/json-schema/expenses/11938) are reversed, with the newest one first and the first one last. They should be in chronological order from the top.

![Screen Shot 2019-12-06 at 3 03 14 PM](https://user-images.githubusercontent.com/5498878/70289427-9e85e900-1839-11ea-8835-0e46f342d0d1.png)

**Comment by alanna** [comment]
Same problem here: https://opencollective.com/cloudflarecollective/expenses/11824

**Comment by icaroharry** [comment]
@Betree would this be a good second contribution? 😅 I can work on it this weekend

**Comment by Betree** [comment]
@icaroharry if you have a clear path to fix it feel free to do. Otherwise we may handle it internally, it's a problematic issue that we want to prioritize

**Comment by znarf** [comment]
That seems a regression from https://github.com/opencollective/opencollective-frontend/pull/3006

We should order by `createdAt` in API v2 `expense.comments` resolver.
