### ISSUE TITLE
Contributor monthly report showing double amount

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2692]
We have had multiple users get in touch saying their monthly contributor report is showing they paid twice what they actually contributed, which is making them think they were double charged. The Open Collective transactions on the website show the correct amount so it seems to be an issue with the report email.

[Example ticket](https://opencollective.freshdesk.com/a/tickets/3194)

![Screen Shot 2019-12-06 at 3 42 07 PM](https://user-images.githubusercontent.com/5498878/70291087-fb37d280-183e-11ea-82b0-3d88e8f2518a.png)

**Comment by znarf** [comment]
I smell that in some circumstances we also fetch the previous contribution (october) or the following one (december) and then are double counting.

**Comment by znarf** [comment]
We're counting an order marked as ERROR, we should not do that. Current behavior is coming from a modification that was not properly tested. https://github.com/opencollective/opencollective-api/commit/33dfb89b69197adb00721ece1b688277a0b21326

**Comment by znarf** [comment]
Removing priority because a fix is ready and it just needs to be shipped before January 1st for the next report.
