### ISSUE TITLE
ARCHITECTURE.md contains ambiguous phrasing

### ISSUE THREAD

**Issue by PeterDCarter** [OpenCollective/OpenCollective#27]
Is "A host is the financial host of the collective, it will receive the money of a group for a donation." intended to read as, "A host is the financial host of the collective; it will receive the money from the group as a donation." or perhaps: "A host is the financial host of the collective; it will receive donations made by the group."?

**Comment by asood123** [comment]
fixed.

**Comment by PeterDCarter** [comment]
Hhhhm. Now it kinda looks like the funds go into the host's personal bank account, rather than an Open Collective account. I assume that's not right. Will raise a new issue :).
