### ISSUE TITLE
tito.io integration

### ISSUE THREAD

**Issue by maxogden** [OpenCollective/OpenCollective#270]
Hi! For http://donutjs.club/ we use http://tito.io/ for ticketing. They have some nice features like exportable attendee lists, a check-in web app for checking people in at the door, and payment integrations with our bank account using Stripe.

Since OpenCollective is also based on Stripe I was wondering if it's possible to use Tito as a 'front-end' to the same Stripe account used by OpenCollective, so that we can have Tito ticket sales as well as donations/backers through OC end up in the same account.

**Comment by asood123** [comment]
Sadly not. While we could hook up our stripe account to it, if transactions go straight to our stripe account, we won't be able to tell which collective they belong to. When they pass through our frontend, we can easily keep track of it, credit the collective, etc.

We want to allow collectives to do ticketing on Open Collective. Maybe a holiday hack project for one of us. Stay tuned and thanks for filing.
