### ISSUE TITLE
How should we deal with fees for bank transfer payments?

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2702]
When a user selects "bank transfer" payment option, we mark the pending order as paid when the funds arrive. Sometimes, the actual funds we receive are less than the amount of the pending order because of bank fees. For example, we got one today where the pending order was $500 and the amount received was $480.

We are about to release the bank transfer payment option to more hosts, so we need to decide what to do about fees. 

### My suggestion:
Add a fees box like we have with expenses, to adjust the amount credited to the Collective down to the real amount after fees. Similar to how we handle payment processor fees for Stripe payments. So in the example above, you'd put in $20 and the order would reflect $500  from the contributor (so they get recognised for the full amount) and $480 credit to the Collective. Then it can be up to each host whether they cover bank fees as part of their service or whether they put the fees in the box and subtract them from the total credit.

**Comment by Betree** [comment]
The suggestion looks good to me because the transaction will describe exactly what happens: contributor paid $500, $20 went to fees. That's what we want for transparency.

I'd suggest opening a modal when confirming an order, that will be also good for preventing misclicks:

```
+---------------------------------------------------------+
|                                                         |
| Confirm order #4253                                     |
+---------------------------------------------------------+
|                                                         |
| +------+                                                |
| |      | Financial contribution to Webpack  +500.00USD  |
| |      |                                                |
| |      | Username | 12/18/2019 | View details           |
| +------+                                                |
|                                                         |
|                                                         |
| If fees were charged by the payment provider,           |
| please set them here:                                   |
|                                                         |
| +---------------+                                       |
| |$|        0,00 |                                       |
| +---------------+                                       |
|                                                         |
|                          +--------+     +-----------+   |
|                          | Cancel |     |  Confirm  |   |
|                          +--------+     +-----------+   |
+---------------------------------------------------------+


```

**Comment by raulgrafico** [comment]
Link to the Figma file:
https://www.figma.com/file/GF1gQ7fWNfaOAFNwuLeAUl/OC.com-Hot-Fixes?node-id=1104%3A312

**Comment by SudharakaP** [comment]
This seems to be a duplicate of https://github.com/opencollective/opencollective/issues/4069 and if no objections I am closing this.
