### ISSUE TITLE
Overlapping when there are multiple goals at the same amount

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2703]
If a Collective sets up multiple goals with the same amount, they overlap.

<img width="1227" alt="Screen Shot 2019-12-09 at 8 04 21 PM" src="https://user-images.githubusercontent.com/5498878/70415058-a905e400-1ac0-11ea-9b4b-a6c798d8b4c2.png">

**Comment by allenlai18** [comment]
@alanna   I am in /edit/goals .    i can not reproduce the problem

**Comment by Betree** [comment]
The bug has to be observed on the collective page after editing the goals. It's the same as the old #1434.

@allenlai18 if it works for you could you share a screenshot so that we can compare the results?
