### ISSUE TITLE
'Find out more' link is broken.

### ISSUE THREAD

**Issue by azilber** [opencollective/opencollective#2707]
**Describe the bug**
Link: https://docs.opencollective.com/help/hosts
Does not work:
"Page not found
Sorry, but the page you were looking for could not be found."

**To Reproduce**
1. Go to 'https://opencollective.com/become-a-fiscal-host'
2. Click on 'Find out more'
3. See error

**Expected behavior**
Docs

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by azilber** [comment]
<img width="954" alt="Screenshot 2019-12-11 at 10 33 09 AM" src="https://user-images.githubusercontent.com/691270/70586438-05bce800-1c02-11ea-8b5d-6e9873f58535.png">
<img width="890" alt="Screenshot 2019-12-11 at 10 36 35 AM" src="https://user-images.githubusercontent.com/691270/70586453-13726d80-1c02-11ea-8df4-813a58d86d3e.png">

**Comment by znarf** [comment]
@contraexemplo can you have a look?

**Comment by contraexemplo** [comment]
Fixed on the docs side as well (https://github.com/opencollective/documentation/commit/387ca1d8f3ed567e1c765204d596e3df2777a1f4).
