### ISSUE TITLE
Monthly export of emails and stats for newsletter

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2711]
@alanna needs a monthly export of email addresses to import into mailchimp for the newsletter.

This is the query

```sql
-- Export email for newsletter
SELECT "createdAt", "firstName", "lastName", email
FROM "Users"
WHERE "newsletterOptIn" IS TRUE
  AND "createdAt" >= '2019-11-01'
  AND "deletedAt" IS NULL
```

I've been doing this manually but I'm not always available when this has to be done and it has been problematic in the past. Can anyone take it over? (and hopefully at some point find a way to automate this?)

Another thing that needs to be done is the export of the monthly stats. 
This can be done by running 
`npm run export:csv` (with the proper `PG_DATABASE` env variable)

Also make sure to adapt the `OC_GOOGLE_DRIVE` env variable properly if needed:
```
const GoogleDrivePath = process.env.OC_GOOGLE_DRIVE || `${process.env.HOME}/Google\ Drive/Open\ Collective`;`
```

This will populate the monthly stats and put them in the public drive (https://drive.opencollective.com).

**Comment by Betree** [comment]
I'll take care of the one for 2020-01, I'll close this if I don't encounter any issue.

**Comment by znarf** [comment]
Can we write that documentation somewhere out of this issue?

**Comment by Betree** [comment]
I've updated https://docs.opencollective.com/help/internal/newsletter with these information

**Comment by znarf** [comment]
Closing then.
