### ISSUE TITLE
Organization did not appear in search when adding funds

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2712]
I just added $3600 to [Decoupled Days](https://opencollective.com/decoupled-days) on behalf of Drupal Association. When I went to "add funds" I typed "Drupal" in the box but Drupal Association did not appear, so I clicked "create new organization". Then I ended up with https://opencollective.com/drupal-association1 which tipped me off that it's a duplicate profile. Sure enough, https://opencollective.com/drupal-association already exists. 

1. Please merge drupal-association1 into the drupal-association profile.
2. Even now when I go back to add funds and try to find either organization they are not coming up. As long as existing orgs don't appear in the search we'll continue having duplicates created.

![Screen Shot 2019-12-12 at 2 00 21 PM](https://user-images.githubusercontent.com/5498878/70673617-02039100-1ce8-11ea-9f5f-7fe39d38c199.png)

**Comment by piamancini** [comment]
@Betree I'll take care of changing the transactions - you can take the underlying issue.

**Comment by piamancini** [comment]
done
