### ISSUE TITLE
Monthly platform and collective report: review who'll be notified

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2714]
Currently:
- Platform reports are sent to all admins of https://opencollective.com/opencollective
- Collective reports are sent to all the admins of the collective

We want to review these policies, because users should not be given more permissions than they need just to get an additional notification.

@alanna suggested that we should send the reports to all **core contributors**, that way adding users as `MEMBER` will be enough for them to be notified.

**Comment by alanna** [comment]
I think it's good we don't seen non-admin core contributors all the notifications about expenses, etc, but monthly reports seem like a good one to send to all core contributors. They can unsubscribe if they don't want it, right?

**Comment by Betree** [comment]
Yes it seems that the collective monthly report has an unsubscribe link properly set

**Comment by Betree** [comment]
Going with the specs proposed above:
- Platform reports: `report.platform.hbs` + `report.platform.weekly.hbs`
- Collective report: `collective.monthlyreport.hbs`

These emails should be sent to all core contributors of the Collective, so all members with role=`ADMIN` or role=`MEMBER`.

**Comment by Betree** [comment]
The root cause for this issue (accountants being added as admin of our collectives) will be rather solved by https://github.com/opencollective/opencollective/issues/3112
