### ISSUE TITLE
Event time in SSR is wrongly translated to user timezone

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2717]
Check 
https://staging.opencollective.com/blogmarks/events/blogmarks-christmas-23741ev

Displayed:
<img width="454" alt="Capture d’écran 2019-12-12 à 15 26 28" src="https://user-images.githubusercontent.com/806/70720359-f3bb7200-1cf3-11ea-9f6d-d96b4af342a9.png">

Expected:
<img width="419" alt="Capture d’écran 2019-12-12 à 15 26 34" src="https://user-images.githubusercontent.com/806/70720351-f027eb00-1cf3-11ea-93d0-aa0d258f7d02.png">

**Comment by znarf** [comment]
Likely linked to https://github.com/opencollective/opencollective/issues/2841

**Comment by Betree** [comment]
Maybe an easy fix would be to force the re-render of this component in `componentDidMount`?

**Comment by znarf** [comment]
It's re-rendering here. The wrong time is just quickly flashing.
