### ISSUE TITLE
"GraphQL error" shows up on all Expenses pages

### ISSUE THREAD

**Issue by audreyr** [opencollective/opencollective#2718]
**Describe the bug**
"GraphQL error" shows up on all Expenses pages.

**To Reproduce**
1. Go to a collective like https://opencollective.com/streetlives/expenses
2. See error.

**Expected behavior**
Seeing expenses rather than a blank error page.

**Screenshots**

**Desktop**
 - OS: [e.g. iOS] macOS Mojave
 - Browser [e.g. chrome, safari] Chrome Version 78.0.3904.108 (Official Build) (64-bit)
 - Version [e.g. 22] 10.14.6

<img width="1332" alt="Screen Shot 2019-12-12 at 10 56 38" src="https://user-images.githubusercontent.com/74739/70740475-1b97df00-1cce-11ea-9943-819bf034cc9e.png">

**Smartphone (please complete the following information):**

**Additional context**
I only checked pages under https://opencollective.com/foundation.

**Comment by Betree** [comment]
Hi @audreyr, thanks for reporting this bug.

Is this still happening on your side? I tried to reproduce but the page works on my machine:

![image](https://user-images.githubusercontent.com/1556356/70745367-e6b67700-1d23-11ea-9c2f-1f54f9e2f043.png)

**Comment by znarf** [comment]
Closing. Feel free to reopen if this happens again in the future.
