### ISSUE TITLE
nivo Website Dark mode does not show some components examples due to lack of contrasting colors 

### ISSUE THREAD

**Issue by sanatp** [opencollective/opencollective#2719]
**Describe the bug**
nivo Website Dark mode does not show some components examples due to lack of contrasting colors 

**To Reproduce**
1. Go to main webpage
2. Click on https://nivo.rocks/sankey
2. Click on light → dark mode

**Expected behavior**
visualization should be visible

**Screenshots**
![Screen Shot 2019-12-12 at 4 23 15 PM](https://user-images.githubusercontent.com/862612/70750127-c8d51c00-1cfb-11ea-942a-b6d443765220.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6
 - Browser safari
 - Version 12.1

**Additional context**
N/A

**Comment by znarf** [comment]
Sorry, it's Open Collective there. Maybe you want to check https://github.com/plouc/nivo
