### ISSUE TITLE
💬️ Conversation feature: 1st feedback round

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2722]
The conversations feature is going to be released soon. This first release is just a start, but we want to get some feedback as early as possible to make sure that this feature is useful to users. 

This issue is where we will be collecting feedback from the team and community to iterate as quickly as possible. It will be live for the next 3 months. Ideas in this thread that we can't implement in this time frame will then be extracted to their own issues.

**Comment by Betree** [comment]
Some early feedback from the initial pre-release:

- Text looks too small. Design used a `13px` font-size (which is not standard according to the design system). I think we should increase to `14px`.

- The edit button for the title doesn't look great. I've used the default one because the action was not designed in Figma, but I think we should move it to the left-side buttons that haven't been implemented yet

![image](https://user-images.githubusercontent.com/1556356/70814076-081e6e00-1dcb-11ea-9a5e-58258373e4ef.png)

**Comment by piamancini** [comment]
When editing a comment, trying to add a picture, hit save picture wasn't saved

**Comment by Betree** [comment]
Image upload is broken indeed, need to investigate. It's normally supported.

**Comment by piamancini** [comment]
view thread online in this email is linked to https://opencollective.com/ not the thread. 
<img width="949" alt="Screen Shot 2019-12-13 at 5 40 06 PM" src="https://user-images.githubusercontent.com/3671070/70816405-b9270780-1dcf-11ea-9191-7b75eb883a4e.png">

**Comment by piamancini** [comment]
Now  this email notification, effectively takes me to the thread, but I can't see François comment 
<img width="1077" alt="Screen Shot 2019-12-13 at 5 44 41 PM" src="https://user-images.githubusercontent.com/3671070/70816693-571ad200-1dd0-11ea-9650-79cebdc63526.png">
<img width="1288" alt="Screen Shot 2019-12-13 at 5 44 34 PM" src="https://user-images.githubusercontent.com/3671070/70816708-5d10b300-1dd0-11ea-85c5-2ecfb79ef8cb.png">

**Comment by znarf** [comment]
- My comment was a single image so it was effectively empty because of the image upload issue
- When deleting a comment, I was redirected to the Collective page, that was weird.
- When editing a comment, the Update / Cancel button are **HUGE**

**Comment by znarf** [comment]
@piamancini you're admin, you should have that right

**Comment by piamancini** [comment]
really? I'm not comfortable with that. I think admins should be able to delete comments but not edit them.

**Comment by Betree** [comment]
What we agreed during last Friday's call was that admins shouldn't be able to edit comments because we don't have an history for now, but I didn't have the time to do it yet

**Comment by znarf** [comment]
Editing the title, the buttons are also HUGE

<img width="707" alt="Capture d’écran 2019-12-13 à 18 07 18" src="https://user-images.githubusercontent.com/806/70818380-d362e480-1dd3-11ea-8ba2-334d4a49fad9.png">

**Comment by piamancini** [comment]
strikethrough in editing is not saving!

**Comment by Betree** [comment]
> When deleting a comment, I was redirected to the Collective page, that was weird.

@znarf Was it the root comment (conversation body)? Deleting a comment normally don't redirect, but deleting the conversation does.

**Comment by piamancini** [comment]
I shouldn't be receiving an email notification of my own comment

**Comment by znarf** [comment]
> Was it the root comment?

@Betree No, was a comment in a conversation.

**Comment by znarf** [comment]
The "comment count" (here `1 1 4`) is globally inaccurate. Not sure it's supposed to include the root conversation or not.

<img width="294" alt="Capture d’écran 2019-12-13 à 21 18 15" src="https://user-images.githubusercontent.com/806/70829514-424d3700-1dee-11ea-910a-1d43bcbbb0e5.png">

**Comment by alanna** [comment]
* I got an email notification about my own comment 
* I expected to show up in the "following" section as soon as commented, but I had to refresh the page manually

**Comment by Betree** [comment]
- On mobile, we show just the icons without labels which is not a good practice for accessibility: icons interpretation may differ based on culture and personal experience. It's better to not use icons alone. See https://ux.stackexchange.com/a/1803 for the data behind this claim.
![image](https://user-images.githubusercontent.com/1556356/71083359-1ede0f80-2193-11ea-977a-b54f953f4ae5.png)

- The `Edit` + `Delete` buttons take a lot of place
![image](https://user-images.githubusercontent.com/1556356/71083018-6021ef80-2192-11ea-8016-1a43b4e083f5.png)

We plan to add at least four new actions on top of it: Reply, Report (#2694), Hide (#2740) and Share. Having 6 buttons in there is not manageable and will never work on mobile. I'd advocate to mimic what Github is doing and have a dropdown menu:

![image](https://user-images.githubusercontent.com/1556356/71083820-34a00480-2194-11ea-9339-4901eea5ff78.png)

**Comment by Betree** [comment]
> I think it was that François accidentally posted an empty comment? We shouldn't send notifications for empty comments.

@piamancini that was because of the missing image bug. We normally don't allow empty messages at all.

**Comment by alanna** [comment]
Admins should be able to add/remove tags to any Conversation in their Collective. Just tried to help organise some tags and realised I didn't have permissions.

**Comment by Betree** [comment]
@alanna it's still not possible to edit the tags of an existing conversation, will be tackled in https://github.com/opencollective/opencollective/issues/2812. We'll make sure that collective admins can edit them.

**Comment by staltz** [comment]
Quick question: can Conversations be limited to collective contributors only? If not, could that be a potential next feature? I'd like to use it gather feedback from the collective's community, but not from outside.

**Comment by Betree** [comment]
@staltz it's not possible at the moment, but that could be a good feature indeed. 

To better understand your use case:
- Would the conversations be publicly visible (and only contributors can comment) or should they be hidden unless you're a contributor?
- Do you see it as a global setting (all conversations for a collective are private) or as a per-conversation setting (some conversations are public, other are private).

Thanks!

**Comment by staltz** [comment]
Thanks for the quick reply! To answer your two questions: I'd prefer all conversations to be publicly visible, but as a global setting, only contributors can comment. Maybe also a global setting to make the conversations only visible to contributors too, that sounds easy to build.

**Comment by znarf** [comment]
I like the idea of limiting posts to contributors while keeping discussions public (as an option). Generally, I don't like much when we make data private because it's in our DNA to have most things public. Of course, this can still be considered if there is strong demand for it.

**Comment by Betree** [comment]
All the feedback in this issues have been acknowledged - either by design or engineering - and the feedback round is now over. Thanks to everyone who participated here, all this feedback was super helpful for us!  

If you feel strongly about specific items that have not been addressed here, feel free to open dedicated issues to discuss them more in depth.
