### ISSUE TITLE
Contributors missing in tier

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2723]
See https://opencollective.com/xr-belgium/contribute/after-party-12957

![](https://d.pr/free/i/9dd3zB+)

Expected result: I (Xavier) should show up as a contributor (€20) but also other people.

It looks like one of the issues comes from the fact that it doesn't create a new row in `Members` if the contributor is already a member of the collective.
I've updated manually the row with id 65319 (in the `Members` table) but it still doesn't show up (maybe caching?)

**Comment by znarf** [comment]
The row with id `65319` is not you but "Leen". It's now correctly appearing.

Effectively, because of internal caching, it's possible that manual edits to the database are not appearing immediately.

**Comment by xdamman** [comment]
It's not only caching, there is also another issue as I don't show up despite my donation (I manually fixed it for Leen's), and also the total raised sor far €156 doesn't match with the only 3 contributors that show up so far (€60)

![](https://d.pr/free/i/Dvz0DE+)

**Comment by Betree** [comment]
> It looks like one of the issues comes from the fact that it doesn't create a new row in Members if the contributor is already a member of the collective.

That's probably the root cause, I've recently spotted a similar issue.

The amount difference seems to be related to that as well, it's missing your contribution and the ones from 3 other contributors.

**Comment by znarf** [comment]
@xdamman I never implied the problem was due to caching. I was just explaining why manual edits to edit the database were not appearing.
