### ISSUE TITLE
Rich text editor > Add link: buttons sizes are wrong

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2724]
Related to #2722 

This is because of the customization for toolbar's buttons. We need to make sure this only applies to the buttons actually in the toolbar, not to the add link popup.

![image](https://user-images.githubusercontent.com/1556356/70813185-60ed0700-1dc9-11ea-8990-1041eb0199ae.png)

**Comment by JoyLubega** [comment]
Hey @Betree I am going to this is a try

**Comment by Betree** [comment]
Hi @JoyLubega, feel free to do so. This is quite important for the public release of conversations, so I'll probably handle it myself if you don't have the time to to solve it before the end of the week.

**Comment by Betree** [comment]
Issue completed by @JoyLubega. Thanks!
