### ISSUE TITLE
Add comments to standalone tier pages

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2727]
I think we should add comments/discussions to standalone tier pages. As we already have this functionality built it seems like it could be straightforward. 

Contributors to that tier could be automatically subscribed as followers, so Collectives could use comments as a way to update everyone on progress of a tier. For example, when they raise the funds successfully and fulfil the goal.

Here's an example: https://opencollective.com/colour-science/contribute/cie-015-2018-12242/

The user wants a way to update it to show they spent the money on what they promised they would, but there's no way to do that now.

**Comment by xdamman** [comment]
I like that idea. To push it a bit further, people should be able to post an expense on such tier page. 
So we need to think of expenses as just another type of comment that can be approved/rejected/paid.

**Comment by alanna** [comment]
This is solved by Project Updates.
