### ISSUE TITLE
Expense not yet paid out

### ISSUE THREAD

**Issue by staltz** [opencollective/opencollective#2729]
**Describe the bug**

Hi! Not sure if this is the right place to report this, but [this expense](https://opencollective.com/manyverse/expenses/12116) on the Manyverse OpenCollective has not yet been paid out, although it has been some weeks already, and the invoice date has passed too. I do this every month, but this month the payment hasn't been sent yet.

**Comment by znarf** [comment]
@staltz I already forwarded internally but the best channel for that is support@opencollective.com

**Comment by znarf** [comment]
Closing as conversation has moved to the other channel.
