### ISSUE TITLE
User and Organization should be able to set their currency

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2730]
Follow up from https://github.com/opencollective/opencollective/issues/1408

## User story 

As a user or organization I would like my statistics to be displayed in the currency of my choice.

## Best solution for this problem

Let user and organization set their currency from the settings, the property is already existing in the API.

- This should absolutely NOT be available for past and current hosts (User or Organization).
- This should absolutely NOT be available to Collectives or Events.

## Implementation

- Add a setting in "Edit Collective", hide or disable it in the mentioned cases
- Check the API and make sure currency can be edited, ignore or throw an exception in the special cases

## Notes

- ~This feature is dependent on the flagging of Hosts in the database.~ Done with the `isHostAccount` property.
- We should come up with a list of supported currencies on the platform, this will first be hardcoded in the Frontend code base. See this link: https://github.com/opencollective/opencollective-api/blob/master/server/graphql/v2/enum/Currency.js#L178

**Comment by znarf** [comment]
A $200 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the Open Source Festival event. If not completed there, it will be later open to everyone.

**Comment by joshikeno** [comment]
@znarf 
> 
> * This should absolutely NOT be available for past and current hosts (User or Organization).
> * This should absolutely NOT be available to Collectives or Events.
> 

I don't really understand the above statements. 
Should I enable this feature based on the flag `isHostAccount `?

**Comment by joshikeno** [comment]
Basic Implementation;
* An `currency` can be chosen from a list of `hardcoded currency options`. 
* `Value (currency type)` would sent to the `API`, If action is rejected display an message like: `User or Organization can't set currency`.

**Comment by znarf** [comment]
@joshikeno yes, this should only be available to `User` and `Organization` with `isHostAccount=false`

**Comment by joshikeno** [comment]
@znarf can I get a bit more information about
>
> * ~This feature is dependent on the flagging of Hosts in the database.~ Done with the `isHostAccount` property.
>

**Comment by znarf** [comment]
@joshikeno You should use that property `isHostAccount`. But maybe you have a more precise question?

**Comment by znarf** [comment]
🏆 This issue was completed by @joshikeno 

To claim the bounty please, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new  Please make sure to mention the ticket number in the invoice and in the expense title.
