### ISSUE TITLE
Missing email when exporting participants as CSV (SSR)

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2735]
When landing on an Event page directly, emails are missing from the export.

**To Reproduce**

1. Go to an Event you're administrating
2. Reload the page to be sure it's a server side rendered version
2. Click on Export CSV

**Current behavior**

Emails are missing

**Expected behavior**

Emails are present

**Explanation**

With our authentication model, emails are not loaded in the SSR data, the data needs to be refreshed with the user token so the emails are available.

**Alternative**

Generate the CSV from the REST API service, and make sure to pass the authentication token.

**Comment by Betree** [comment]
Seems that we duplicated this issue in https://github.com/opencollective/opencollective/issues/3260, it was later solved in https://github.com/opencollective/opencollective-frontend/pull/4522 by making sure we wait for the refetch before displaying the Export button.
