### ISSUE TITLE
Misplaced public message popup on order success page

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2736]
**Describe the bug**
After the contribution flow, on order success page, the popup to leave a public message is not where it should be. The bug doesn't seems to appear after a page refresh, so that might be linked to client-side rendering.

![image](https://user-images.githubusercontent.com/1556356/71014200-d6224a00-20f1-11ea-998e-b8413d0bd07c.png)

**To Reproduce**
1. Go to `/collective/donate`
2. Complete the contribution flow
3. See error

**Expected behavior**
SSR and client-side should render the same UI. See screenshot above.

**Comment by allenlai18** [comment]
@Betree   what would be the best way to reproduce this. without actually making a real donation? lol

**Comment by allenlai18** [comment]
i am on staging and I can not reproduce this bug
![Screen Shot 2019-12-17 at 8 39 29 AM](https://user-images.githubusercontent.com/7275313/71015644-d1857380-20a8-11ea-9a5b-65c0b6ff8e07.png)

**Comment by Betree** [comment]
Should ideally be resolved with https://github.com/opencollective/opencollective/issues/2745

**Comment by znarf** [comment]
@kewitz have you tested that it works before closing?

**Comment by kewitz** [comment]
@znarf yes. I reviewed, tested and merged. I will deploy soon.

**Comment by znarf** [comment]
@kewitz Thank you, great to know!
