### ISSUE TITLE
Contribution FAQ doesn't appear on mobile

### ISSUE THREAD

**Issue by gallexi** [opencollective/opencollective#2744]
**Describe the bug**
The FAQs that appear in the contribution flow on desktop don't appear on mobile. This is especially confusing because the explanation text for the Incognito option says "Keep my contribution private (see FAQ for more info)", but there's no FAQ to be found.

**To Reproduce**
1. Initiate a contribution on desktop
2. Note that an FAQ appears (Screenshot 1, below)
3. Initiate a contribution on mobile, or use desktop browser devtools to request the mobile version of the page
4. Note that no FAQ appears (Screenshot 2, below)

**Expected behavior**
If the Incognito option references an FAQ, I expect to see or be linked to an FAQ. At the very least, I want to know who will see what personal information of mine if I contribute as Incognito.

**Screenshots**
Screenshot 1:
![Screenshot showing desktop view with FAQ](https://user-images.githubusercontent.com/17116584/71065822-00025d80-2140-11ea-8e86-1880738b99bd.png)

Screenshot 2:
![Screenshot showing mobile view with no FAQ](https://user-images.githubusercontent.com/17116584/71065738-d2b5af80-213f-11ea-8a80-e21176bd685c.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version 79.0.3945.79

**Smartphone (please complete the following information):**
 - Device: iPhone Xs
 - OS: 13
 - Browser: Safari
 - Version: 13

**Additional context**
Looks like perhaps a followup to https://github.com/opencollective/opencollective/issues/1628

**Comment by Betree** [comment]
Unfortunately the [design](https://www.figma.com/file/M4OD1AM4nN8kzEhnO3zILo/OC.COM-05-%2F-Collectives-%E2%86%92-Contribute?node-id=1912%3A42588) didn't include the FAQs in the mobile version, we'll need their input to move forward with this.

**Comment by raulgrafico** [comment]
We have am FAQ mobile design, you can find it here: https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=1733%3A7390

**Comment by Betree** [comment]
@raulgrafico this issue is for the contribution flow, not the expense flow. Should we apply to same pattern of displaying the FAQs below the call to actions?

**Comment by raulgrafico** [comment]
@Betree yes, right now that's how we are displaying the FAQ here: https://www.figma.com/file/M4OD1AM4nN8kzEhnO3zILo/OC.com-Web-05-Collectives-%E2%86%92-Contribute?node-id=355%3A3608

Let me know if this works fine.

**Comment by Betree** [comment]
With the latest contribution flow revamp the FAQ is now displayed on mobile. Thanks for making us aware of this issue @gallexi!
