### ISSUE TITLE
Improve tooltips positioning

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2745]
# Problem

In multiple cases, our tooltips positioning is not working great. We are mainly facing three issues:
- Tooltip is positioned out of screen - see first screencast
- Tooltip is not reacting to windows events (scroll, resize...etc) - see second screencast
- Tooltip is not initializing correctly - see #2736 

We have mainly two components that we need to fix: `StyledTooltip` and `EditPublicMessagePopupContainer`. The second provides its own code for positioning, while the first one relies on `react-tooltip` (that obviously is not doing its job properly).

![Peek 18-12-2019 11-20](https://user-images.githubusercontent.com/1556356/71077801-6ad78700-2188-11ea-849c-f77ce579034a.gif)

![Peek 18-12-2019 11-13](https://user-images.githubusercontent.com/1556356/71077325-7fffe600-2187-11ea-874b-e58888d7e1e4.gif)

# Proposal

[PopperJS](https://popper.js.org/) is a small library (6kb) whose role is solely to position poppers. popper.js is not a tooltip library, it's a positioning engine to be used to build features such as (but not restricted to) tooltips. It's popular (13k+ stars) and maintained.

We should ideally use it though its React implementation, https://github.com/popperjs/react-popper.

- [x] Remove the custom positionning logic in `EditPublicMessagePopup` by using `react-
popper`
- [x] Get rid of `react-tooltip` in `StyledTooltip`, use `react-popper` for positioning (maybe take the code from https://github.com/opencollective/opencollective-frontend/blob/f7c8da49023345248976ca7265c155f7a66be9ae/components/EditPublicMessagePopup.js#L36 to render the arrow?)
- [x] Two components are still using `react-tooltip` directly, migrate them to `StyledTooltip` and uninstall `react-tooltip` from frontend

**Comment by FezVrasta** [comment]
Popper 2 is approaching its stable release. If you'd like to contribute, it's on, d'uh, OpenCollective 😄

Here's the alpha 2 changelog:
https://opencollective.com/popperjs/updates/popper-2-alpha-2-is-out

**Comment by Betree** [comment]
Hello @FezVrasta! Thanks for the info, I missed the fact that a new major was about to be released - thanks for jumping in :slightly_smiling_face: Also glad to see that you joined Open Collective, feel free to join us on [Slack](https://slack.opencollective.com/) if you need help with anything.

The company gives us a budget to contribute to the project that we use, I'll be happy to contribute to Popper as soon as we start using it :wink:

**Comment by Betree** [comment]
`react-popper` has been introduced in the codebase in https://github.com/opencollective/opencollective-frontend/pull/3857 and should now be the default to build new tooltips (side note: it's delightful to work with!).

A work has been started to migrate `EditPublicMessagePopup`: https://github.com/opencollective/opencollective-frontend/pull/3859. After that we'll still need to migrate `StyledTooltip`.

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$150** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $150 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by jeffin143** [comment]
Here we have to migrate StyledTooltip? 
I think so rest you have done ??

**Comment by Betree** [comment]
@jeffin143 As per the issue description, only the first item (Remove the custom positionning logic in EditPublicMessagePopup by using react- popper) has been done. We need to:
- Migrate StyledTooltip
- Update `StyledUpdate` that still uses `react-tooltip`

**Comment by nonsodaniel** [comment]
Hi @Betree, can I work on this issue?

**Comment by jeffin143** [comment]
@nonsodaniel I have almost completed , there is a pr

**Comment by Betree** [comment]
:trophy: This issue has been completed by @jeffin143  

To claim the **$150** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
