### ISSUE TITLE
Weird checkout behaviour triggered fraud detector

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2747]
New user trying to set up a new donation with a valid credit card: 

> I have successfully used this card on other websites today and we even called the bank and they claim that they're not seeing the failing charge attempts come through. When I go through initially, it gives me a "card declined" error. If I click "Make contribution" again, I'm able to see the actual Stripe token (a bug, I assume)

_You cannot use a Stripe token more than once: (token ID sent to us)_

When I looked in Stripe, there were 9 costumers created for this same email address in the same day: 

<img width="860" alt="Screen Shot 2019-12-18 at 4 14 10 PM" src="https://user-images.githubusercontent.com/3671070/71098130-7be8be00-21b1-11ea-9758-0a1137d08838.png">

Collective ID: 79089

These are the orders that errored out: 
59440
59439
59438
59437
59431
59423
59422
59421
59401
59399
59396

**Comment by znarf** [comment]
Ok, "card declined" error make sense. We should reset the token and ask a new one in this case, so we don't resubmit the same token.

**Comment by znarf** [comment]
Created a simpler issue.
