### ISSUE TITLE
Notify platform admins when a suspicious value is set for URLs

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2750]
## User story 
As platform admins, we need to be notified whenever someone links to suspicious external websites.

While investigating on #2738, I found out that the main common trait between spammers is that they are trying to create as many links as possible to their websites.

Finding some keywords in user-submitted contents should trigger a notification on Slack:
- keto
- porn
- pills

## Best solution for this problem
Ideally we should trigger the notification for links submitted in any type of content:
- Long descriptions
- Comments
- Updates
- Profile info

## MVP
Whenever someone creates a collective or edit it:
- [x] Create a `getSuspiciousKeywords(content: string): string[]` function in `server/lib/spam.ts`
- [x] Check collective `website`, `name`, `description` and `longDescription` with this function
- [x] If at least one suspicious keyword is detected, trigger a notification in Slack `spam-reports` channel (id: `GRX4WNP9C`) like this:
> Field {fieldName} for <collectiveName|collectiveUrl> was set to a suspicious value: 
> `fieldValue`

## Metrics 
- How many notifications get triggered

**Comment by CanerSezgin** [comment]
@Betree I wanna take this. 

2 quick questions. 
1) I couldn't find this file on master. `server/lib/spam.ts` Should I create or should I use another branch (if you have already got started in another branch) ? 

2) I couldn't get the idea behind why we are returning array with this function. `getSuspiciousKeywords(content: string): string[]`
I thought something like this. 

```
// Suggestion: We should call this *DoesIncludeSuspiciousKeywords* and it will return boolean
function getSuspiciousKeywords(content: string): string[] {
    const suspiciousKeywords = [
        'keto',
        'porn',
        'pills'
    ]

    return suspiciousKeywords.some(keyword => content.includes(keyword))
}
```

**Comment by Betree** [comment]
1. `server/lib/spam.ts` doesn't exist yet, you should create it
2. Your proposal would work. The idea of returning an array with all the suspicious keywords was to be able to display them in the slack notifications mentioned above:

> Field {fieldName} for <collectiveName|collectiveUrl> was set to a suspicious value:
fieldValue

**Comment by Betree** [comment]
Resolved by https://github.com/opencollective/opencollective-api/pull/3119
