### ISSUE TITLE
Group duplicates members in widget

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2754]
There may be multiple `Member` rows per MemberCollective/Collective, each row describes one aspect of the membership. For example if a user is a financial contributor to Tier1, Tier2 but also an admin of the collective, we'll need three rows to describe the situation.

What describes a membership is the pair of "MemberCollectiveId", "CollectiveId", "TierId", "role".

Widget for contributions is not taking that into account. See https://staging.opencollective.com/betree/widget.html:

![image](https://user-images.githubusercontent.com/1556356/71158896-ff9fba80-2244-11ea-88ae-99be040cab2a.png)

This issue was reinforced by https://github.com/opencollective/opencollective/issues/2723, but there have always had been duplicate members to describe the various roles (also some unwanted duplicates, see https://github.com/opencollective/opencollective/issues/2753).

**Expected behavior**
- [ ] There should be only one card per collective
- [ ] Roles (the one in green in the screenshot) should be grouped. ie: `Admin, backer, sponsor`

**Comment by znarf** [comment]
A $200 bounty was attached to this issue. Anyone submiting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md).

**Comment by leonardohof** [comment]
@znarf Can I work on this issue?

**Comment by leonardohof** [comment]
@Betree A card by collective means it?
![image](https://user-images.githubusercontent.com/294406/72306490-022fdd00-3656-11ea-9445-bdce1c3391ea.png)

**Comment by Betree** [comment]
@leonardohof absolutely

**Comment by Betree** [comment]
:trophy: This issue is now completed by @leonardohof  

To claim the $200 bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
