### ISSUE TITLE
Show core contributor description

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2755]
I added descriptions for all the core contributors of OSC, but they don't show on the person's card in the contributors section. We should show the description under their name.

<img width="817" alt="Screen Shot 2019-12-20 at 9 53 47 AM" src="https://user-images.githubusercontent.com/5498878/71208826-cdf32600-230e-11ea-8593-f4d664c1ebd5.png">
<img width="865" alt="Screen Shot 2019-12-20 at 9 52 48 AM" src="https://user-images.githubusercontent.com/5498878/71208828-cdf32600-230e-11ea-8d7c-257e3f6a45b0.png">

**Comment by Betree** [comment]
The initial version used to display the description, but the height with the role + amount contributed + the description + the public message was too high so we decided to sacrifice this one.

Just adding it back now would break the design, so we need to either come up with something clever or ask @opencollective/design to propose a different approach.

**Comment by alanna** [comment]
If we're not going to display it then we should probably hide the field in settings because it implies it will be displayed and encourages people to use it.

**Comment by Betree** [comment]
My proposal would be to reduce the number of lines in the contributors grid to **two**, and to add the description under the role.

![image](https://user-images.githubusercontent.com/1556356/71209462-f0078c80-22ab-11ea-8dbc-8ed829f8f3c7.png)

**Comment by Betree** [comment]
> If we're not going to display it then we should probably hide the field in settings because it implies it will be displayed and encourages people to use it.

The initial intent was to bring it back but we never iterated on this design. This issue is a good reminder that we should, I personally think that it's great to be able to have a custom description of the person's role rather than generic "Admin"/"Contributor".

**Comment by kewitz** [comment]
Can’t we consider the _description_ and _public message_ as being mutually exclusive?
I see a reason for displaying the _public message_ for financial contributors, but it doesn’t seem that important for core contributors.
My suggestion would be displaying the _description_ and falling back to _public message_ using the existing space and format.

**Comment by Betree** [comment]
> Can’t we consider the _description_ and _public message_ as being mutually exclusive?
> I see a reason for displaying the _public message_ for financial contributors, but it doesn’t seem that important for core contributors.
> My suggestion would be displaying the _description_ and falling back to _public message_ using the existing space and format.

That's a really good point. This fix should work for most scenarios and it's a really simple change.

I'd suggest doing it the other way around tho: using _public message_ and fallback to _description_, otherwise we may end up with a strange UX - "why can't I see my public message after pressing save"?

**Comment by kewitz** [comment]
Hi @alanna, can you confirm this solves your issue?
https://opencollective.com/opensource#section-contributors

**Comment by alanna** [comment]
Yes looks great!
