### ISSUE TITLE
Record as paid not working for Paypal expenses

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2759]
[User reports](https://opencollective.slack.com/archives/C6JTTA4SK/p1576898392000700):

> I see there is now a "record as paid" button even when the payment method is set to paypal! thanks! however, it's not working, it still errors out and says no payment method was found. i can do the workaround of editing the method to "other" but it would be nice if "record as paid" worked too.

Seems like a bug with #1976

**Comment by znarf** [comment]
Great if you can have a look @Betree .
