### ISSUE TITLE
Webpack is breaking Open Collective :D – too many contributors in the mosaic

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#276]
Any ideas on the best way to fix this? 
![c1wxt1ywqaapugp jpg-large](https://cloud.githubusercontent.com/assets/3671070/21695569/44244890-d33f-11e6-9176-e807cffa4e3f.jpg)

Original tweet by @changelog
https://twitter.com/changelog/status/816725278802280448

**Comment by xdamman** [comment]
We used to have one `<img>` tag per contributor but that was way too slow to load and it was also slowing down scrolling.

So we moved to generating one single SVG on the backend with all the avatars in base64. It works fine in Chrome but Safari seems to have some issues when the number of avatars is very large.

What's the best way to solve this?

**Comment by markadrake** [comment]
Can you setup some middleware to take a custom url such as `https://opencollective.com/webpack/contributors.svg` and return the server-composed SVG file. Wikipedia says base64 could add [about 37% more weight to the file](https://en.wikipedia.org/wiki/Base64).

**Comment by boneskull** [comment]
Alternatively you could convert to a diff img format?

**Comment by xdamman** [comment]
@markadrake that's what we do: 
- https://opencollective.com/webpack/backers.svg?width=900
- https://opencollective.com/webpack/contributors.svg?width=900

But the SVG is made of sub images that are base64 encoded so that the browser doesn't have to do 600+ requests to get the individual avatars.

**Comment by xdamman** [comment]
@boneskull we also offer a png version:
- https://opencollective.com/webpack/contributors.png?width=900

But then we lose the ability to link each avatar to their website/profile.

**Comment by boneskull** [comment]
@xdamman image map!

**Comment by boneskull** [comment]
([`<map>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/map) for those unfamiliar with this bit of antiquity)

**Comment by boneskull** [comment]
Or instead of the SVG, you could put up a big warning which insists the user upgrade to a modern browser.  *zing*

**Comment by mattijsbliek** [comment]
@xdamman I would say a JPG version is actually preferred. If I load the [MochaJS page](https://opencollective.com/mochajs) for example, the total weight is a whopping 8.8MB. The contributors SVG is responsible for over 80% (7.3MB) of the total page weight. By changing the format to JPG at 70% quality, the image becomes 0.7MB, saving everybody lots of data.

I say losing the links and transparency but decreasing the page weight by that much is definitely worth the trade-off. Since the avatar dimensions are fixed, you can always put absolutely positioned anchor tags on top of the image.

Let me know if I can help out in any way.

**Comment by markadrake** [comment]
@xdamman I left part of my question out sorry. In the SVG spec you can include a file reference to an actual image no? Like so: 

```
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" 
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="5cm" height="4cm" version="1.1"
     xmlns="http://www.w3.org/2000/svg" xmlns:xlink= "http://www.w3.org/1999/xlink">
	<image xlink:href="https://opencollective.com/webpack/contributors.png?width=900" x="0" y="0" height="900px" width="900px"/>
</svg>
```

Could you not also still include blank shapes to act as hover spots? This would take minimal effort, if it works for you.

Image maps are in the HTML 5 spec so they shouldn't go away anytime soon.

Using a `canvas` element is another possibility.

**Comment by piamancini** [comment]
fixed.
