### ISSUE TITLE
[#COMMIXTURE] ff HAPPY INSPRING

### ISSUE THREAD

**Issue by RythmosAdvisory** [opencollective/opencollective#2763]
https://www.researchgate.net/lab/Commixture-Labs-Marzio-Veneman

Recently, I have an interest in Collaborative Intelligence (**Social Impact:** _P2P Blockchain connected to AI in conjunction with the ELITE SILO's_).

For this purpose, I am a member of a (open) European observatory.

 

/snip/

A new tender call: Is anyone interested to participate in a joint tender?

Tender call just published at https://lnkd.in/dZ43fuU

(specifications at https://lnkd.in/dEh9xd7):

Financing of Artificial Intelligence and Blockchain Technologies in Europe

Setting-up a Running Investment Support Program.

Mainly there should be realized studies, analyses, a project map, workshops and an MOOC related to AI and blockchain in Europe.

/snip/

-- 
~~~~~~~~~~~~~~>>>
 
https://www.linkedin.com/in/rythmosadvisory/
https://www.linkedin.com/feed/hashtag/commixture
https://www.csiac.org/members/rythmomachy
https://www.hdiac.org/members/rythmomachy
https://community.culturalheritage.org/people/maci-marzio-veneman1
 
https://www.join.me/RythmosAdvisory
 
 
 
 
~ Power to the Commons ~
 
[Colleborative Intelligence: Binairy Code -> Subject.
Returns 1 if the data is from a real living system, and 0 if it's not.
The use of learning algorithms is expressly not allowed, for the obvious
reason, they would not yield an explanation of why they work.]

**Comment by Betree** [comment]
The purpose of this issue is unclear. Please use one of the templates for bug reports or feature requests: https://github.com/opencollective/opencollective/issues/new/choose

For any other inquiry feel free to join on https://opencollective.slack.com/
