### ISSUE TITLE
我发现了一个错误，原谅我英文不太好

### ISSUE THREAD

**Issue by solyn** [opencollective/opencollective#2768]
**Describe the bug**

**To Reproduce**
1. 引用粘页眉插件。bootstrap-table-sticky-header
2. 同时使用了bootstrap-table-filter-control
3. 当bootstrap-table-filter-control  设定了select时候，往下拖动的时候里面是没有数据的，null
4. 如果发现了回我邮件就好。solyn@foxmail.com
原因是：
复制的表头，select里面没有数据

**Comment by solyn** [comment]
hi，a bug，in china

**Comment by Betree** [comment]
Hi @solyn, sorry but we can only support issues written in English. Could you translate it please?

**Comment by solyn** [comment]
no Closed

**Comment by solyn** [comment]
The problem has not been solved。
I'm now overriding it by listening to the browser scroll bar.

**Comment by solyn** [comment]
Reference the paste header plug-in. "bootstrap-table-sticky-header"

"Bootstrap table filter control" is also used

When the bootstrap table filter control is set to select, there is no data in it when dragging down. Null

If only I found a reply to my email. solyn@foxmail.com

As a result of:

There is no data in the copied header and select

**Comment by solyn** [comment]
Hi


I'm now overriding it by listening to the browser scroll bar.


Reference the paste header plug-in. "bootstrap-table-sticky-header"


"Bootstrap table filter control" is also used


When the bootstrap table filter control is set to select, there is no data in it when dragging down. Null


If only I found a reply to my email. solyn@foxmail.com


As a result of:


There is no data in the copied header and select



I'm now overriding it by listening to the browser scroll bar





Solyn

























Phone: 17600445600

Telephone: 17600445600

Email address: solyn@foxmail.com

Address: Room 101, Building 44, Dongfuli, Jiayuan, Qingxi Mountain, Four Seasons, Beijing

Website: 未鉴定艺术


&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Benjamin Piouffle"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月2日(星期四) 下午5:26
收件人:&nbsp;"opencollective/opencollective"<opencollective@noreply.github.com&gt;;
抄送:&nbsp;"solyn"<solyn@foxmail.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [opencollective/opencollective] 我发现了一个错误，原谅我英文不太好 (#2768)




Closed #2768.

**Comment by Betree** [comment]
@solyn Sorry but this is Open Collective, not bootstrap-table-sticky-header.
