### ISSUE TITLE
setup an apply link for OTF

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#277]
We need to setup a page for OTF to direct their projects to signup for Open Collective. Now that we support /apply for hosts, let's use that to setup an apply link for them. I believe we already have a collective setup for them. @piamancini can point you in the right direction.

Note, this is blocking them from moving forward.

**Comment by piamancini** [comment]
We have two collectives, one OTF as an organization and the other to act as the freedom of the internet supercollective: opencollective.com/opentechfund & https://opencollective.com/internetfreedom
Let me know how can I help unblock

**Comment by xdamman** [comment]
I'm confused by this. Which one should people apply to? I'd guess OpenTechFund?

**Comment by asood123** [comment]
My understanding is that they have a legit use case to want both eventually.

Let's start with OpenTechFund, so they can share that in their proposal step.

**Comment by piamancini** [comment]
I think it has to be to Internet Freedom, that is the grant they have.  People apply to the internet freedom grant not to become part of OTF.  OTF if for their organisation, not for the grantees and I think it's for later in the future.

**Comment by asood123** [comment]
I thought OTF proposals are more than just Internet Freedom. Let's ask them.

**Comment by xdamman** [comment]
I've activated both :-)
- https://opencollective.com/opentechfund/apply
- https://opencollective.com/internetfreedom/apply

**Comment by piamancini** [comment]
shoudln't we remove the options? it should just be one button to submit a collective for a OTF project

**Comment by xdamman** [comment]
What options are you talking about?

**Comment by piamancini** [comment]
for context, this is a link that OTF will use internally to send their projects to Open Collective. They don't support parent associations or meetups. only open technology projects. It will be confusing for them to see it as is, imo.

**Comment by xdamman** [comment]
I see. But I thought that they didn't want to be the host. So this should be a different form altogether. It's more for asking for sponsorship no?

**Comment by asood123** [comment]
this is done and sent to otf.
