### ISSUE TITLE
Several 404 pages on REST API docs

### ISSUE THREAD

**Issue by lawik** [opencollective/opencollective#2771]
**Describe the bug**
Looking into the APIs for Open Collective led me to https://docs.opencollective.com/help/contributing/development/api

Clicking through for Collectives and the ones below gave 404s.

I'm aware of the new GraphQL API but I imagine the broken links are undesirable.

**To Reproduce**
1. Go to https://docs.opencollective.com/help/contributing/development/api
2. Click on 'Collectives' in the list.
3. See 404 page :)

**Expected behavior**
I'd expect to find the docs :)

**Comment by znarf** [comment]
@contraexemplo can you have a look?

**Comment by contraexemplo** [comment]
It's just a matter of broken paths. I'm on it!

**Comment by contraexemplo** [comment]
Fixed it  — all links on the REST API section are now pointing to the right paths.
