### ISSUE TITLE
Fragile E2E test: 34-expenses.comment.test.js

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2772]
```
Running:  34-expenses.comment.test.js

  1) Expense Comments loads more comments:
     CypressError: Timed out retrying: Not enough elements found. Found '23', expected '25'.
```

Sample CI run: https://github.com/opencollective/opencollective-frontend/pull/3241/checks?check_run_id=374461613

**Comment by Betree** [comment]
Probably related to https://github.com/opencollective/opencollective-frontend/pull/3246. I'll investigate tomorrow
