### ISSUE TITLE
Expense: Show "Mark as unpaid" button regardless of the payout method

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2773]
According to #2324 host admins should have the ability to unpay expenses, but the button is not showing up for most expenses. 

I can only see it for Collectives where I am an admin of the Collective. As host admin, I should be able to see the button for all Collectives under my host.

Collective where I am the admin:
![Screen Shot 2020-01-06 at 10 10 39 AM](https://user-images.githubusercontent.com/5498878/71786124-0f086b80-306d-11ea-9c13-22cccc64c84b.png)

Collective where I am not the admin (but I am host admin):
![Screen Shot 2020-01-06 at 10 11 00 AM](https://user-images.githubusercontent.com/5498878/71786111-eb452580-306c-11ea-809b-79bfec27b5fb.png)

**Comment by alanna** [comment]
Question: should "mark as unpaid" be available for all paid expenses, or has it only been implemented for manual payment type (not Paypal API transactions)?

**Comment by znarf** [comment]
```
    const canMarkExpenseAsUnpaid =
      LoggedInUser &&
      LoggedInUser.canPayExpense(expense) &&
      expense.status === 'PAID' &&
      expense.payoutMethod === 'other';
```

Just looked at it and it's only available for manual payment type.

**Comment by alanna** [comment]
We need this paypal expense to be marked as unpaid as the funds were returned: https://opencollective.com/keepassxc/expenses/12164

Can someone please do that?

@znarf it would be very helpful to have the mark as unpaid button appear to fiscal host admins for all expenses, manual or paypal.

**Comment by alanna** [comment]
We have now re-paid https://opencollective.com/keepassxc/expenses/12164 so we don't need it marked as unpaid anymore.

However it would be useful to have this button available for all expenses regardless of payment type.

**Comment by Betree** [comment]
Resolved by https://github.com/opencollective/opencollective-frontend/pull/4383 + https://github.com/opencollective/opencollective-api/pull/4020
