### ISSUE TITLE
Unable to approve Nigeria Collective in Nigeria Host

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2774]
Related to #2748 

The [Nigeria Host](https://opencollective.com/nigeria) and [Collective](https://opencollective.com/nigeria-collective) have been created. We had to do it specially because this host does not have Stripe.

The Nigeria Collective is currently pending approval by the host. But Samson did not get an email notification to approve it, nor does it show up under pending Collectives on the dashboard. How do we activate this Collective under the host?

![Screen Shot 2020-01-06 at 11 16 01 AM](https://user-images.githubusercontent.com/5498878/71786905-fcdefb00-3075-11ea-90be-13731232e408.png)
![Screen Shot 2020-01-06 at 11 15 05 AM](https://user-images.githubusercontent.com/5498878/71786906-fcdefb00-3075-11ea-81c6-69c0e32d9f3a.png)

**Comment by znarf** [comment]
Not sure what was special and what were the actions taken to arrive in this state.

The `approvedAt` field was no set, I've now set it manually.
