### ISSUE TITLE
Tax form not sent to user roxblnfk

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2776]
This expense should have triggered the tax form email: https://opencollective.com/yiisoft/expenses/12734

But the user says he didn't get it. I also can't see a record of it being sent in HelloWorks. Meanwhile many other tax forms have been sent successfully so the system appears to be functioning for other users.

**Comment by znarf** [comment]
Seems this expense was filled on the last day of 2019 and the tax form system is not able to send tax forms for 2019 anymore, only counting expenses for 2020.

**Comment by znarf** [comment]
Took care of that.
