### ISSUE TITLE
Clicking "Next" on Discover doesn't scroll you up to the top of the content

### ISSUE THREAD

**Issue by lencioni** [opencollective/opencollective#2781]
**Describe the bug**
Clicking "next" on the discover page leaves you hanging at the bottom of the page instead of scrolling you up to the top of the next page of content.

I think this is similar to https://github.com/opencollective/opencollective/issues/1647

**To Reproduce**
1. Go to https://opencollective.com/discover
2. Scroll to the bottom of the page
3. Click on "Next" button
4. See that you are still at the bottom of the page, even though the new content has loaded

**Expected behavior**
I expected to be returned to the top of the page.

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: chrome
 - Version: 79.0.3945.88

**Comment by Betree** [comment]
@lencioni thanks for reporting this! It will be fixed by our next deployment (probably today or tomorrow).
