### ISSUE TITLE
Reset Stripe token when resubmitting order

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2782]
Following up from https://github.com/opencollective/opencollective/issues/2747

When contributing with a new credit card, if the order is failing, we should reset the token so it's not reused if the user submit the form again with the same credit card.

That way we can avoid the error "You cannot use a Stripe token more than once".

I'm not able to find steps to reproduce the issue using Test Credit Cards from Stripe https://stripe.com/docs/testing.

Testing with `4000 0000 0000 0002` and making sure that the stripe token is refreshed before re-submitting should do the job.

**Comment by BassT** [comment]
@znarf I think I could fix this issue. Could I be assigned?

**Comment by znarf** [comment]
🏆 This issue was completed by @CanerSezgin 

To claim the bounty please, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new  Please make sure to mention the ticket number in the invoice and in the expense title.

Note: because the complexity was simpler than expected, I'll kindly ask you to jump in if there is small follow up on it.
