### ISSUE TITLE
Add link to refill paypal balance to error message

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2784]
### Problem
If you run out of the $2000 paypal preapproval and you try to pay an expense, you get an error saying "insufficient funds in your paypal preapproval". To fix it, you need to go to your host dashboard and click "refill paypal balance" and go through that process. 

Right now it's easy to get blocked if you're not sure what that error means. There should be a link in that error message so host admins who get stuck here know what to do. Often hosts are looking at an individual expense page when paying, and are not on the dashboard, so it's unclear that they need to go to the dashboard.

### Best Solution
Add a link saying "refill balance now" that connects directly to the same page you reach when you click "refill balance" on the dashboard.

### MVP 
Add a link saying "refill paypal balance from your host dashboard" that links to the host dashboard, where they can click the "refill balance" button.

**Comment by Betree** [comment]
Would be a nice UX improvement.

**Comment by JoyLubega** [comment]
Hey @Betree I am taking a look at this again. But I can't seem to connect to Paypal. Do I need to create my dev account in Paypal and use that? Thanks

**Comment by Betree** [comment]
@JoyLubega the connection needs to happen from the host dashboard (ie. `/my-host/dashboard`). You can create sandbox paypal accounts from https://developer.paypal.com/developer/accounts/
