### ISSUE TITLE
Remove direct actions from frontend

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2786]
Since https://github.com/opencollective/opencollective-api/pull/3059, for security reasons, we're not generating direct action links anymore. ie: approve collective, approve expense, reject expense.

Out of clarity, support for these should be removed from the Frontend codebase.

**Comment by Betree** [comment]
I initially wanted to give the links a grace period of one month. We're almost there, so I'm fine with removing the pages now.

**Comment by Betree** [comment]
If we want to be safe, we can also edit the approve pages to redirect to the dashboard/expense views rather than removing them.

**Comment by znarf** [comment]
No rush, I just wanted to have that tracked.
