### ISSUE TITLE
Configuration via mocha.opts is DEPRECATED

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2787]
When running `npm run test` in API.

```
DeprecationWarning: Configuration via mocha.opts is DEPRECATED and will be removed from a future version of Mocha. Use RC files or package.json instead.
```

Let's move that to `package.json` if possible, we don't want yet another configuration file at the root of our project. If the `RC` file is in the `test` folder then it's fine.

**Comment by kewitz** [comment]
https://github.com/mochajs/mocha/pull/4069

**Comment by znarf** [comment]
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md).

**Comment by znarf** [comment]
🏆 This issue was completed by @CanerSezgin 

To claim the bounty please, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new  Please make sure to mention the ticket number in the invoice and in the expense title.
