### ISSUE TITLE
Move Event balance to parent

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2792]
In the previous Event page, we were supporting the ability to move the Event balance to the parent. This functionality is now gone since we moved to the new Event page (based on the new collective page).

Today, it can still be reachable by adding "/legacy" to the event URL. That way we can unblock users contacting us.

We would like to make this feature accessible again.

Old code: https://github.com/opencollective/opencollective-frontend/blob/master/components/Event.js#L166

**Comment by znarf** [comment]
A $200 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the Open Source Festival event. If not completed there, it will be later open to everyone.

**Comment by jeffin143** [comment]
Hi @znarf , It has been long time I haven't be in touch with the codebase, Can you point me to the file where I have to implement the feature. 

Thanks

**Comment by bolariin** [comment]
I took a look at this yesterday, I think the implementation would go here https://github.com/opencollective/opencollective-frontend/blob/master/components/collective-page/CollectiveNotificationBar.js

You might also want to take a look at https://github.com/opencollective/opencollective-frontend/blob/master/pages/new-collective-page.js

**Comment by Je-ni** [comment]
Hi @znarf , I would like to work on this feature. 

I have the front-end setup, and have tried creating an event to view the legacy 'moving event balance to parent' feature, but can't seem to see it. 

Could you give me some pointers?

**Comment by znarf** [comment]
@Je-ni What is the event address you're looking at? Can you try adding `/event` at the end?

Also, make sure the Event has a positive balance (register a paying ticket) and that the event is over (the end date is in the past). These are conditions for the feature to be visible.

**Comment by joshikeno** [comment]
@Je-ni Please indicate if you are from `OSCA`

**Comment by Je-ni** [comment]
I am from OSCA

**Comment by znarf** [comment]
@Je-ni any progress on that?

**Comment by Je-ni** [comment]
No @znarf. I'm a lot confused with the codebase.

**Comment by znarf** [comment]
🏆 This issue was completed by @joshikeno 

To claim the bounty please, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new  Please make sure to mention the ticket number in the invoice and in the expense title.
