### ISSUE TITLE
Remove "Name Tags" feature

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2793]
Pros:
- It's currently broken. If we don't remove it, we need to spend time fixing it.
  - See: https://opencollective.com/sustainoss/events/sustain-2020-5874aeeb/nametags.pdf
- No one complained that it was broken.
- It's already considered as debt, and we wanted to remove it from the frontend codebase anyway
  - It's relying on heavy and outdated dependency (phantomjs) that we would like to remove from our tree
  - We have plans centralizing PDF generation in a separated service: https://github.com/opencollective/opencollective/issues/2055
- This can be re-implemented as a feature of the PDF service if there is demand for it.

Cons:
- Some people might be sentimentally attached to the feature

**Comment by piamancini** [comment]
ok -

**Comment by xdamman** [comment]
Ok. But we really need to think about how we can extract the Event feature from the core of open collective. It should be its own app. Let’s put that as a topic for the Brussels retreat. This will fit nicely in the discussion for opencollective.org.

**Comment by piamancini** [comment]
@xdamman that's a separate issue from this one. Open one specifically for that as a project if you think you want to work on that. Thanks!
