### ISSUE TITLE
Attempting to change URL Slug on account setting retuns "Validation error"

### ISSUE THREAD

**Issue by MrControl** [opencollective/opencollective#2796]
All attempts made to change my URL slug has caused the message "Validation error" when I click save.  Is anyone else having problems like this?
![Error message](https://user-images.githubusercontent.com/27393212/72195318-b2e07700-33df-11ea-8794-a4bd5e53aff4.png)

**Comment by znarf** [comment]
@MrControl No, it's not common, can you give a link to your collective?

**Comment by znarf** [comment]
Duplicate with https://github.com/opencollective/opencollective/issues/3325
