### ISSUE TITLE
Admins can download past reports

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2798]
## User story 
As the admin of a Collective, Host, or Organization, I want to be able to download past reports so I can access records and provide information as needed. 

This comes up for all kinds of reasons, like providing info to accountants for taxes, creating budget reports, filling out grant applications, etc.

Currently reports are emailed out monthly, but there is often the need to look up past info and it's very hard to track down. Plus if I need a report from before I was the admin I don't have it in my email archive.

## Best solution for this problem
A section where admins can see and download past reports (monthly and annual). They could have the same info that we put in the emails, just in a downloadable format, with past months and years available.

**Comment by BenJam** [comment]
going to close this on the basis that you can filter by month in the new reports dashboard: 

![Screenshot 2022-08-15 at 10 58 47](https://user-images.githubusercontent.com/158833/184655559-518a1f76-34c9-4b9b-81f8-4d43dce828bb.png)

Reopen if we think it's still important.
