### ISSUE TITLE
Replace Google/Apple maps by OpenStreetMaps

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2799]
To deal with event's locations, we currently use:
1. Google maps to suggest the addresses
2. Google maps to display the map
3. Apple maps for the link to the full map

Both of these services are proprietary and raise privacy concerns (that we successfully avoid on the rest of the website by not using any tracker).

## Best solution for this problem

Thankfully Open Street Map is a very strong alternative to these services and can provide anything we need with a simple integration while respecting our user's privacy. 

## MVP

The transition can be done incrementally: 
1. For addresses, one can use https://osmnames.org/api/ or https://openaddresses.io 
2. A simple `iframe` (see "export > html" on OSM) will replace the map
3. Replacing the Apple link is the easiest

## Related

This [tweet](https://twitter.com/satarsalasratas/status/1213932799209738248?s=20).

**Comment by znarf** [comment]
@Betree thank you for creating the issues! Feel free to add the bounty on it.

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by joshikeno** [comment]
@Betree I would like to work on this issue.

**Comment by joshikeno** [comment]
- [ ] For addresses, one can use `https://osmnames.org/api/` or `https://openaddresses.io`
- [x] A simple iframe (see `export > html` on OSM) will replace the map
- [x] Replacing the Apple link is the easiest

<img width="1296" alt="Screenshot 2020-01-13 at 18 27 57" src="https://user-images.githubusercontent.com/29008971/72278351-1ebb1d80-3634-11ea-9d9f-548c4247ab98.png">

**Comment by Betree** [comment]
@joshikeno looks good! Can we add a pin on the address, like the one we had on Google maps?

![image](https://user-images.githubusercontent.com/1556356/72280048-ba01c200-3637-11ea-99df-afb62d9e714d.png)

**Comment by joshikeno** [comment]
@Betree position marker doesn't show up within the iframe.

**Comment by joshikeno** [comment]
`InputTypeLocation`  makes use of [`react-geosuggest`](https://github.com/ubilabs/react-geosuggest) for addresses.

I haven't seen a good implementation using either `https://osmnames.org/api/` or `https://openaddresses.io`

**Comment by Betree** [comment]
> @Betree position marker doesn't show up within the iframe.
> It works perfectly on the Full Map.

Check https://gis.stackexchange.com/a/180723

> `InputTypeLocation` makes use of [`react-geosuggest`](https://github.com/ubilabs/react-geosuggest) for addresses.
> 
> I haven't seen a good implementation using either `https://osmnames.org/api/` or `https://openaddresses.io`

Feel free to build your own component. `StyledSelect` or `react-select`'s async (https://react-select.com/async) can help you to do this.

**Comment by Betree** [comment]
I just contacted https://www.maptiler.com to ask clarification about their usage limits and to know if we qualify for a free plan. Let's wait for their answer before finishing the implementation.

**Comment by Betree** [comment]
Update from Maptiler:

> Hello Benjamin,                                                           thank you for reaching out to us.                                                           If you scroll down on the pricing page, you'll find there a table where is explained how geocoding requests are counted.                                                           It is 1 geocoding request = 1 request. So with the  Flex plan, you have 500k geocoding requests/month included for  $20/month. Each additional 1k requests are charged $0.05.                                                           You are qualified for the Free plan only in case  your solution is completely no-revenue generating (including ads, etc.).                                                                                             Have a nice day!

So we're gonna skip the geocoding part for now because our usage (probably ~500 requests/month) doesn't justify paying $20/m. Also this is not the part where privacy is the most impacted, only the event organizer use that part of the code (while maps are displayed for everyone).

**Comment by Betree** [comment]
:trophy: $200 bounty completed by @joshikeno 

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Comment by Betree** [comment]
Though the last part (geosuggest) wasn't implemented because Maptiler's API didn't fit, a custom address component was created in https://github.com/opencollective/opencollective-frontend/pull/3356. To anyone revisiting this issue: feel free to use this work to replace `react-geosuggest`.
