### ISSUE TITLE
Conversation: save draft in local storage

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2800]
There is nothing worse than spending half an hour writing something, then being distracted and opening another tab, then coming back and realizing that the browser reloaded the page (especially on mobile where memory usage is limited) and the text is gone.

This could be easily solved by saving regularly the current draft in local storage.

Whenever I come back to the new conversation page, the last text I wrote should be there (with the collective slug being part of the cache key). When posting the conversation (or reply), the local storage is cleared.

**Comment by znarf** [comment]
A $200 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the Open Source Festival event. If not completed there, it will be later open to everyone.

**Comment by Betree** [comment]
See https://github.com/opencollective/opencollective/issues/2922 for the specs to implement the `FormPersister` library to allow that.

**Comment by Ebugo** [comment]
Hi @znarf I'd love to work on this issue. Could you assign it to me

**Comment by znarf** [comment]
@Ebugo you're assigned!

**Comment by Ebugo** [comment]
Alright, thanks. Would get to work asap.

**Comment by Ebugo** [comment]
Hi, I've been having loads of issues replicating the conversations environment on my windows OS. I had to install Ubuntu, and would need some time to set up. Thanks.

**Comment by znarf** [comment]
@Ebugo what were the problems with windows?

**Comment by Ebugo** [comment]
Failed to compile
./components/collective-page/images/HeroBackgroundMask.svg 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <svg width="1368" height="472" viewBox="0 0 1368 472" fill="none" 
|   xmlns="http://www.w3.org/2000/svg">
|   <path opacity="0.2" d="M31.9856 0.000437154C220.409 253.606 823.256 428.277 990.082 456.764C1103.27 476.092 1311.06 468.232 1368 446.069C1368 384.621 1368 1.13814 1368 1.13814C980.28 0.761682 370.991 0.00024623 31.9856 0.000437154Z" fill="#000000"/>

This is what I've been seeing..It's not just with the conversations even

**Comment by Ebugo** [comment]
@znarf Do you think this can be solved fast enough?

**Comment by znarf** [comment]
@Ebugo No idea. We're not actively looking at it. Feel free to create an issue with steps to reproduce.

**Comment by Ebugo** [comment]
Alright

**Comment by znarf** [comment]
@leonardohof I'm absolutely sorry for the confusion, yesterday I forgot to assign @bolariin who already had a PR for this issue: https://github.com/opencollective/opencollective-frontend/pull/3733

If you could review his PR and give your opinion on how it could be made better, I can give you $100 as a compensation for your work. Again, really sorry about that.

**Comment by leonardohof** [comment]
> @leonardohof I'm absolutely sorry for the confusion, yesterday I forgot to assign @bolariin who already had a PR for this issue: [opencollective/opencollective-frontend#3733](https://github.com/opencollective/opencollective-frontend/pull/3733)
> 
> If you could review his PR and give your opinion on how it could be made better, I can give you $100 as a compensation for your work. Again, really sorry about that.

Ok, no problem. I added some suggestions.

**Comment by Betree** [comment]
:trophy: This issue has been completed by @bolariin 

To claim the **$200** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

@leonardohof can also claim a $100 bounty for the work he did on this.

Thank you both!
