### ISSUE TITLE
Multiple expense's attachments: prepare the data model (batches)

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2803]
## User story 
As part of the [expense flow re-design project](https://github.com/opencollective/opencollective/issues/2394), users will be able to add multiple attachments to a single expense. Each attachment has its own amount, date and title. The sum of the attachments **must** match the amount of the expense.

![image](https://user-images.githubusercontent.com/1556356/72246384-db8c8a80-35f2-11ea-9b59-abe3565ac443.png)

## Best solution for this problem
Two solutions have been suggested to solve this issue. @kewitz's proposal is the favorite for its simplicity and the clear migration path that it offers (no breaking changes in frontend).

- [x] Create an `ExpenseAttachments` table
- [x] Migrate the `Expense.attachment` column to this new table
- [x] Update the code creating an expense to use this new field
- [x] Deprecate the [`expense > attachment`](https://github.com/opencollective/opencollective-api/blob/c8beb9551f03cfef27d3479feb9b6ad8a341e207/server/graphql/v1/types.js#L749) resolver and make it return the first attachment's URL only
- [x] Introduce a new resolver: `Expense > attachments` that returns all the attachments (full object, including the amount/date...etc)
- [x] Make sure the `createExpense` and `editExpense` endpoints accept both usages
- [ ] Make sure deleting an expense deletes the attachments

## Alternative solution

<details>

- Create an `ExpenseBatches` table
- Create batches for all existing expenses
- Update create expense's code to also create batches
- Update resolvers to fetch batches rather than expenses

</details>

**Comment by kewitz** [comment]
Moreover, I think a method for getting the total expense based on attachments might also be desirable.
