### ISSUE TITLE
CSS issue in the contribution flow (new org)

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2804]
![](https://d.pr/free/i/SktfJa+)
I guess the title "A New Organization" should not be in a column but on top no?

**Comment by Betree** [comment]
> I guess the title "A New Organization" should not be in a column but on top no?

That's for the signup. As per design:

![image](https://user-images.githubusercontent.com/1556356/72275493-558e3500-362e-11ea-8e65-6443658ca5ac.png)
