### ISSUE TITLE
CollectivePage: Don't show 'hibernating' if organization has subcollectives

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2805]
We shouldn't show "Fridays for Future seems to be hibernating in a cave in the North Pole ❄️☃️!" 
![](https://d.pr/free/i/jlEgAa+)

More generally, we shouldn't show empty sections. There shouldn't be "Contributions" nor "Transactions" in the menu and on the page if there is nothing to show. Those should only show if you are logged in as an admin (both for organizations and collectives)

**Comment by Betree** [comment]
`These Collectives are part of our Organization` is part of `Contributions`, so it's normal to have it there. Sections handling will be handled in https://github.com/opencollective/opencollective/issues/2807, let's keep this one about the `Hibernating` thing.

**Comment by xdamman** [comment]
I'd not show this message in all cases if you are not logged in as an admin. It's quite a negative message to show publicly. 
If you are logged in, I'd rather say something such as "Connect a fiscal host and define different tiers to enable financial contributions" (with a link to the fiscal host section in the collective settings)
