### ISSUE TITLE
GraphQL query to fetch collective's features

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2807]
## Motivations

- **NavBar**: We [recently improved](https://github.com/opencollective/opencollective-frontend/pull/3307) the sections displayed for each collective. But the current conditions are not perfect: for example we want to keep showing the `Contribute` section for collectives without hosts if they have an event or subcollectives. **But** we don't want to fetch tons of data in all pages that have a `CollectiveNavbar` to achieve that. How convenient would it be if we could directly fetch these info about which feature to display without having to deal with all this complex logic and additional data in the frontend?

- **Optional features (Transferwise, PayPal payout...etc)**: in multiple pages we need a way to easily check if a feature is supported. For example in the create expense flow, we need to know if the host supports Transferwise as a payout option. Having a consistent way to check that could improve clarity.

### API

On `CollectiveInterface`, create a new `features` field that returns a `CollectiveFeatures` object.

Each key is a feature name, and the value is an enum with the following values:

```ts
enum FEATURE_STATUS {
  /** 'The feature is enabled and is actively used */
  ACTIVE = 'ACTIVE',
  /** The feature is enabled, but there is no data for it */
  AVAILABLE = 'AVAILABLE',
  /** The feature is disabled, but can be enabled by an admin */
  DISABLED = 'DISABLED',
  /** The feature is disabled and cannot be activated for this account */
  UNSUPPORTED = 'UNSUPPORTED',
}
```

The returned object would look like this:

```json
{
  "collective": {
    "features": {
      "CONTACT": "ENABLED",
      "RECEIVE_EXPENSES": "ENABLED",
      "CONTRIBUTE": "ENABLED",
      "CONTRIBUTE_PAYPAL": "ENABLED",
      "UPDATES": "DISABLED",
      "SHOW_TRANSACTIONS": "DISABLED"
    }
  }
}
```

In the example above:
- `UPDATES` would be marked as `DISABLED` if there's no update.
- `SHOW_TRANSACTIONS` would be marked as `DISABLED` if there's no transactions.

Most of the code should be inspired by what's [in navbar today](https://github.com/opencollective/opencollective-frontend/blob/7fa8b7d480df8b8ace6e0253bafdeae7f742550e/components/CollectiveNavbar.js#L259), with the following adjustments:
- Still enable `Contribute` if the collective has an event or a subcollective
- Don't enable `Transactions` for users/orgs with no transaction for non-admins 

Also see [existing features enum](https://github.com/opencollective/opencollective-api/blob/027cb3683985615127a6e289b6958c0c5e660365/server/constants/feature.ts), we should use it as a basis to defined a corresponding GraphQL enum type.

### Frontend

Create a reusable `CollectiveNavbarFeatures` fragment that fetches all the fields from `features` required to display the collective navbar properly and use it where necessary.

**Comment by sbinlondon** [comment]
API features endpoint has been merged 🎉👯‍♂️
