### ISSUE TITLE
Update styled-components to version 5.0.0

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2809]
We have a policy to try to use the latest version of our dependencies in all repositories.

In the Frontend, we're currently using the version 5.0.0-beta.8 of `styled-components` and the upgrade to version 5.0.0 is breaking E2E tests.

Check failing PR: https://github.com/opencollective/opencollective-frontend/pull/3335

We want to:
- [x] upgrade the package
- [x] make sure the test are passing

**Comment by znarf** [comment]
This was merged but there is a blocker, see https://github.com/opencollective/opencollective-frontend/pull/3344#pullrequestreview-355750705 and https://github.com/opencollective/opencollective/issues/2898

**Comment by Shulammite-Aso** [comment]
hello Znarf, I would love to work on this issue, can it be assigned to me?

**Comment by znarf** [comment]
@Shulammite-Aso This is still assigned to someone else.

**Comment by JoyLubega** [comment]
@znarf I think this should be closed too

**Comment by znarf** [comment]
🏆 This issue was completed by @JoyLubega 

To claim the bounty please, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new  Please make sure to mention the ticket number in the invoice and in the expense title.
