### ISSUE TITLE
Unexpected error when ___________

### ISSUE THREAD

**Issue by phongbuigk** [opencollective/opencollective#2810]
# Describe the bug

I got an unexpected error on https://opencollective.com/git-quick-stats/donate? while I was trying to __________

# To Reproduce

1. Go to ________
2. Click on ________
3. Scroll down to ________

# Device
- OS: Win32
- Browser: `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36`

# Technical details

```

```

**Comment by Betree** [comment]
Hi, thanks for opening this issue. Unfortunately we need more details about how this happened and how to reproduce to be able to take care of it. Please let us know if you have any other information.
