### ISSUE TITLE
Edit conversations tags

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2812]
## User story 
As a collective admin or as the creator of the conversation, I can edit the tags for it after it's created.

## Best solution for this problem
Add a edit button on the top right of the tags, on the conversation page. Best would be to use the `InlineEditField` so that we keep the styles consistent. When clicked, replace the tags list by a `StyledInputTags` with `Save` / `Cancel` buttons. 

![image](https://user-images.githubusercontent.com/1556356/72326598-bdd12b00-36af-11ea-9888-f7721183dc76.png)

## Expected tests

- Add an E2E test in https://github.com/opencollective/opencollective-frontend/blob/1557dc8329d3e7ab606ed433593de4fed7cda5a8/test/cypress/integration/17-conversations.test.js#L41 that changes the tags and ensure new tags are properly added.

## Testing the feature

Docs about testing conversations: https://docs.opencollective.com/help/contributing/development/testing-features/conversations

---

Require https://github.com/opencollective/opencollective-api/pull/3201

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by joshikeno** [comment]
@Betree working on this.

**Comment by Betree** [comment]
@joshikeno I'm deploying https://github.com/opencollective/opencollective-api/pull/3201 to staging now so that you'll have the API ready

**Comment by joshikeno** [comment]
@Betree It would be nice if `testuser` -> `testCollective` has most features enabled by default.
What do you think?

**Comment by Betree** [comment]
@joshikeno which features?

**Comment by joshikeno** [comment]
I was wondering why the conversation section wasn't enabled by default and thought there was a special reason until I referenced the documentation.

**Comment by Betree** [comment]
Yep, conversations are enabled per default for new collectives

**Comment by Betree** [comment]
:trophy: This issue is now completed by @joshikeno in https://github.com/opencollective/opencollective-frontend/pull/3345

To claim the **$200** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

---

For more info about the bounty process and how to format your invoice, please read https://docs.opencollective.com/help/developers/bounties

If you have any feedback on how we could improve the bounty process or how to better onboard new developers please [share it with us](https://slack.opencollective.com/), we're always eager to improve :slightly_smiling_face:
