### ISSUE TITLE
Turn on the tax form system for other hosts

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2815]
The tax form system is currently only active for OSC host. However, we actually have the same need for OC Inc host (currently having to do a bunch of manual work to chase tax forms for 2019) so it would be great if we could use the automated tax form system for 2020. 

What would be required to activate this feature for hosts besides OSC, starting with OC Inc host (and ideally Foundation too)? 

I suggest we first just consider other US based hosts that need exactly the same form and criteria as the form for OSC, and not totally different requirements in other countries, for now.

**Comment by alanna** [comment]
As an aside, I think this is an other strong contender for a paid feature for upgraded host plans. It's a huge value add for fiscal hosts who are heavy users of the platform - @piamancini

**Comment by alanna** [comment]
@piamancini with scaling up the Foundation, I think we're really going to need to turn on the tax form system for that host.

@znarf do you have a sense of how big a project that would be? It's one of those things that seems hard up front, but actually saves so much pain once a year, so if it's possible we should do it.

**Comment by znarf** [comment]
We activated it for Foundation.
