### ISSUE TITLE
Cypress tests: get rid of all "force: true"

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2816]
In our cypress tests, we have a lot of `cy.get('...').click({ force: true })`. While sometimes desirable, we should avoid it as much as possible because it doesn't test the following cases:

- Ensure the element can be scrolled to.
- **Ensure the element is not hidden.**
- **Ensure the element is not disabled.**
- Ensure the element is not detached.
- Ensure the element is not readonly.
- Ensure the element is not animating.
- **Ensure the element is not covered.**

## Best solution for this problem

For most tests on the collective page, `{ force: true }` can be avoided by calling `disableSmoothScroll` at the beginning of the test (see function description for more details about this issue). We should actually add it as a command in https://github.com/opencollective/opencollective-frontend/blob/19735cce1c713ef26014f072e9d75120a78c1b2f/test/cypress/support/commands.js so that it can be called with `cy.disableSmoothScroll()`.

For all other cases, we should either:
- Remove the `{ force: true }`
- Add a comment next to it to explain why it's necessary (there must be a good reason)

---

Tests written with Cypress must follow our [good practices](https://docs.opencollective.com/help/developers/testing-with-cypress) conventions.

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by danielsum** [comment]
Hi, I got a similar issue on another project, best strategy is to apply a wait until : https://www.npmjs.com/package/cypress-wait-until so you can wrap everything in a Promise and apply a timeout error.

**Comment by Betree** [comment]
Hi @danielsum, thanks for the info. `cypress-wait-until` is definitely interesting, we'll keep an eye on it in the future. In this specific case @brymut was able to solve all the occurrences in https://github.com/opencollective/opencollective-frontend/pull/3383 without this package.

For us part of the issue is related to https://github.com/cypress-io/cypress/issues/3200.

**Comment by znarf** [comment]
🏆 This issue was completed by @brymut 

To claim the bounty please, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new  Please make sure to mention the ticket number in the invoice and in the expense title.

**Comment by znarf** [comment]
The PR was reverted and so the issue is open again.

**Comment by znarf** [comment]
@brymut fyi ![Screenshot 2020-03-02 at 20 49 43](https://user-images.githubusercontent.com/806/75711907-6e7aa480-5cc7-11ea-96f2-53ca935d2f99.png)
