### ISSUE TITLE
Zeit deployments previews unresponsive API

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2818]
**Describe the bug**
Pre-deploys generated by Zeit are randomly stuck and the API calls timeout. Pages usually show a loading spinner then an `The Open Collective Server is momentarily unreachable` error. I personally rely a lot on them for testing contributor's PRs and often have to re-deploy manually.

**To Reproduce**
Example: https://opencollective-frontend-adlzxrjqdz.now.sh/babel

1. Open a PR on frontend
2. Randomly, the pages that make API calls timeouts

**Screenshots**
![image](https://user-images.githubusercontent.com/1556356/72448362-2820c300-37b7-11ea-8b0f-0f28865bfc16.png)

**Additional context**
Logs when the request fails:

> error: middlewareError {"meta":{"error":{"errno":"EAI_AGAIN","code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"api-staging-direct.opencollective.com"},"level":"error","message":"uncaughtException: getaddrinfo EAI_AGAIN api-staging-direct.opencollective.com\nError: getaddrinfo EAI_AGAIN api-staging-direct.opencollective.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)","stack":"Error: getaddrinfo EAI_AGAIN api-staging-direct.opencollective.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)","exception":true,"date":"Wed Jan 15 2020 15:49:21 GMT+0000 (Coordinated Universal Time)","process":{"pid":27,"uid":0,"gid":0,"cwd":"/usr/src/frontend","execPath":"/usr/local/bin/node","version":"v12.13.1","argv":["/usr/local/bin/node","/usr/src/frontend/dist/server"],"memoryUsage":{"rss":127574016,"heapTotal":77574144,"heapUsed":70501384,"external":1681014}},"os":{"loadavg":[2.6708984375,2.8857421875,2.46533203125],"uptime":3425273},"trace":[{"column":26,"file":"dns.js","function":"GetAddrInfoReqWrap.onlookup [as oncomplete]","line":60,"method":"onlookup [as oncomplete]","native":false}],"req":{"url":"/api/graphql","headers":{"host":"opencollective-frontend-adlzxrjqdz.now.sh","x-forwarded-host":"opencollective-frontend-adlzxrjqdz.now.sh","x-real-ip":"82.227.105.40","x-forwarded-for":"82.227.105.40","x-forwarded-proto":"https","x-now-id":"7rxdd-1579103283331-711174082f52","x-zeit-co-forwarded-for":"82.227.105.40","content-length":"2287","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0","accept":"*/*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","content-type":"application/json","authorization":"","origin":"https://opencollective-frontend-adlzxrjqdz.now.sh","dnt":"1","referer":"https://opencollective-frontend-adlzxrjqdz.now.sh/","x-now-trace":"zrh1,bru1,sfo1"},"method":"POST","httpVersion":"1.1","originalUrl":"/api/graphql","query":{}}}}

**Comment by Betree** [comment]
At first view it looks like a DNS issue on Zeit's side. May be worth escalating the issue.

**Comment by Betree** [comment]
I'm opening a ticket about this issue with Zeit now.

**Comment by znarf** [comment]
The easy answer for them will be to say that their API v1 is about to be deprecated and that we should not be using it.

**Comment by paulogdm** [comment]
@znarf Negative. There are a few layers of this problem that I've clarified on the ticket request:
- When using Now 1.0, it can take a while for the server to warm up if you are not using a fixed scaling configuration.
- EAI_AGAIN is a Docker related error and we can't fix it at the platform level. We do recommend that you try other Dockerfiles to see if it improves.

Now 1.0 will be deprecated this year and we do recommend our users that they move away from the platform if they need a serverful offering. The future for us is to provide the best workflow and experience for frontend developers through static and serverless deployments.

**Comment by znarf** [comment]
@paulogdm Sorry, I deleted my earlier comment because I thought it was not appropriate here. 

Thank you for helping and providing your input again, much appreciated! We don't plan to go serverless yet and so Now 1.0 is unfortunately still the best platform for our case!

**Comment by Betree** [comment]
Does not happen anymore since we migrated to Now V2 :rocket:
