### ISSUE TITLE
Shouldn't be able to submit expenses on archived collectives

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2819]
When looking at the pages for an archived collective, it's still possible to submit expenses:
- The [collective page](https://staging.opencollective.com/up-we-rise) has a button for it
- The expense(s) pages have a button for it
- The [form](https://staging.opencollective.com/up-we-rise/expenses/new) to submit expenses is still active

![image](https://user-images.githubusercontent.com/1556356/72454345-f57bc800-37c0-11ea-9f6e-4891d69ac08e.png)

**To Reproduce**
Example: https://staging.opencollective.com/up-we-rise

Steps to reproduce the behavior: use the collective above, or...
1. Create a collective
2. Go to Settings > Advanced > Archive
3. See collective page
4. See expense page(s)

**Expected behavior**
- Archived collectives should never have a `Submit expense` button
- The form should be replaced by a message like this one:
![image](https://user-images.githubusercontent.com/1556356/72454707-a5513580-37c1-11ea-8a7d-a688778d3a8b.png)

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by daud1** [comment]
I would like to have a go at this.

**Comment by Betree** [comment]
@daud1 All right, initial time limit is 1 week. This can later be extended if there is demonstrable progress. Good luck!

**Comment by Betree** [comment]
:trophy: This issue has been completed by @daud1 

To claim the **$200** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

---

@daud1 We also added you to https://github.com/orgs/opencollective/teams/contributors/members. **Congrats!** :tada: You can now push directly to most Open Collective repos (only the `master` branches are protected).

---

For more info about the bounty process and how to format your invoice, please read https://docs.opencollective.com/help/developers/bounties

If you have any feedback on how we could improve the bounty process or how to better onboard new developers please [share it with us](https://slack.opencollective.com/), we're always eager to improve :slightly_smiling_face:
