### ISSUE TITLE
How to add Github contributors to a collective?

### ISSUE THREAD

**Issue by jancborchardt** [OpenCollective/OpenCollective#282]
On other projects I saw a list of Github contributors listed on the bottom too. Can we add that to https://opencollective.com/opensourcedesign as well? We have the organization https://github.com/opensourcedesign, and our most active repos are /organization, /opensourcedesign.github.io, /jobs and /events

**Comment by piamancini** [comment]
Hi @jancborchardt Yes, I can add them manually. We can either add an entire organization or just one repo. I guess in this case we'll add https://github.com/opensourcedesign?

**Comment by jancborchardt** [comment]
@piamancini yes, it would be perfect if you can add the entire organization @opensourcedesign! :) Thanks

**Comment by piamancini** [comment]
done! we fetch them once a day, you should be able to see them tomorrow.

**Comment by jancborchardt** [comment]
Aaaawesome, looks very cool now! Thanks a lot :)

![capture du 2017-01-17 00-58-37](https://cloud.githubusercontent.com/assets/925062/22002930/2073668c-dc50-11e6-85c7-5a8fb7618840.png)

**Comment by piamancini** [comment]
<3
