### ISSUE TITLE
Low quality avatar picture 

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#2820]
**Describe the bug**
I'm not sure if the image is just low quality or if it is being stretched.
The image seems to look good when it is used as 64x64, but in the Hero avatar, there's a noticeable drop in quality which suggests the image might be stretched.

**Screenshots**
You'll need to open these images and zoom to 100%.
![image](https://user-images.githubusercontent.com/2119706/72464623-69fc3a00-37b4-11ea-9c3c-babdd049c049.png)
![image](https://user-images.githubusercontent.com/2119706/72464640-754f6580-37b4-11ea-8a87-10cd0bc0e796.png)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Chrome
 - Version: 79

**Smartphone (please complete the following information):**
 - Device: Nokia 8.1
 - OS: Android
 - Browser: Chrome
 - Version: latest

**Comment by znarf** [comment]
@Betree what do you think?

**Comment by kewitz** [comment]
Fixed here: https://github.com/opencollective/opencollective-frontend/pull/3365.
