### ISSUE TITLE
Allow hosts to charge different fees per Collective

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2821]
## User story 
As a host admin, I want to specify different fees for different Collectives in my host, so that I can manage both internal projects (who I don't want to charge a fee to) and offer fiscal hosting services externally (which I do want to charge for).

## Best solution for this problem
Probably would need a "Collectives" tab on the host dashboard that lists some settings hosts define per Collective, one of which is the host fee.

## MVP
If it's possible for us to set this up by request that would be great, even if we don't develop a user-facing feature right now.

**Comment by xdamman** [comment]
I also want to be able to specify a plan rather than a fee. 
Eg. Open Collective Brussels is asking €10/month to each collective. Right now they have just created a tier and they manually ask collectives to subscribe to it. It would be very useful if this could be part of the built-in experience.

**Comment by Betree** [comment]
https://github.com/opencollective/opencollective/issues/3355 will solve this issue. We'll follow up on https://github.com/opencollective/opencollective/issues/2821#issuecomment-584154676 with https://github.com/opencollective/opencollective/issues/3362.
