### ISSUE TITLE
Expense tags

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2823]
## User story 
As part of https://github.com/opencollective/opencollective/issues/2394, we want users to be able to add multiple tags when they submit an expense, and not just a single category.

![image](https://user-images.githubusercontent.com/1556356/72521700-37a61780-385c-11ea-9604-1c32022e27d9.png)

## Best solution for this problem
Full ability to add and remove tags on expenses.

## MVP
The full feature will be implemented with the new expense flow. This issue is only about implementing the changes in the API while being reverse-compatible with the existing frontend.

- [x] Create a new column on `Expenses` named `tags`, an array of strings
- [x] Move all the expense's `category` to this new field and delete the column
- [x] Adapt the existing graphql `category` field to return the first tag and deprecate it
- [x] Create a new `tags` fields for expenses on Expense's graphql type
- [x] Make sure the `createExpense` and `editExpense` endpoints are compatible with both usages

Some validations for tags were implemented with conversations. We should extract them in a lib to use the same between the two models: https://github.com/opencollective/opencollective-api/blob/5ff5e291d2dc833a90859b1f3790bef6fa84242d/server/models/Conversation.js#L61

**Comment by CanerSezgin** [comment]
@Betree for creating new column and moving values from one column (category) to new one, I have created a migration file and wrote the SQL script inside and run migrate comment on shell. 
Db updated as expected but I couldn't make sure whether this is the correct way or not. I mean I couldn't see any docs etc for DB related developments and also don't know whether you have an ORM that can generate these migration files automatically.

**Comment by Betree** [comment]
@CanerSezgin we use sequelize, migrations are in the API's `migrations` folder if you want to look at it. 

However we prefer to handle developments for the new expense flow internally (you can recognize them as they're part of the `Expense flow` project), I should have self-assigned this issue. Thanks for jumping in, feel free to look at the other issues to find something more suited

**Comment by CanerSezgin** [comment]
Oh sorry about that, I should have asked before starting you are right. 
At least let me write it down what I've done up to now, it's not a big deal but maybe you may want to use it. 

**migrations/20200121195818-expense-tags.js**
```
'use strict';

const table = 'Expenses';
module.exports = {
  up: async (queryInterface, Sequelize) => {
    // Create Tags Column: string[]
    await queryInterface.addColumn(table, 'tags', {
      type: Sequelize.ARRAY(Sequelize.STRING),
      allowNull: true,
    });
    // Put Category Values into Tags Array
    await queryInterface.sequelize.query(
      `UPDATE "${table}" main SET tags= tags || (SELECT category FROM "${table}" WHERE id = main.ID);`,
    );
    // Remove Category Column
    await queryInterface.removeColumn(table, 'category');
  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.dropTable('users');
    */
  },
};
```

**Comment by Betree** [comment]
An alternative to this proposal is to store the expense's tags at the conversation level. Because expenses are embed in conversations and conversations already have tags, it could make sense to use it.
