### ISSUE TITLE
Make event title on expenses page a link to the event

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2824]
The event title on the expenses page is plain text. It should be a link to the event page. The same goes for the transactions page.

![Screen Shot 2020-01-17 at 4 04 35 PM](https://user-images.githubusercontent.com/5498878/72581167-4adfe280-3943-11ea-8676-ecd2295264b3.png)

**Comment by Betree** [comment]
@znarf shouldn't we display the new navbar on this page?

**Comment by znarf** [comment]
@Betree definitely

**Comment by Betree** [comment]
Closing in favor of the new https://github.com/opencollective/opencollective/issues/2826
