### ISSUE TITLE
Use the new collective navbar on event's expense page

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2826]
We want to migrate the `CollectiveCover` on event's expense page (`/:eventSlug/espenses`) to the new `CollectiveNavbar`.

![image](https://user-images.githubusercontent.com/1556356/72603471-5cac9000-3919-11ea-946b-c03554ab234b.png)

**Comment by bolariin** [comment]
@Betree For this issue should all expense related pages be updated to the new navbar such as `:eventSlug/expenses/new` and `:eventSlug/expenses/:ExpensesId`

**Comment by Betree** [comment]
@bolariin absolutely, thanks for catching that I missed the fact that these pages were using it too.
