### ISSUE TITLE
Reduce max image size in updates when shown on collective page

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2827]
See https://opencollective.com/testcollective#section-updates
![](https://d.pr/free/i/At7ebX+)

**Comment by znarf** [comment]
There is no updates on the linked collective.

**Comment by Betree** [comment]
I don't see that as a bug, it's big but the image is not overflowing it's container. Some collectives may actually want to have an image that takes the full width (ie. a team picture, a banner, etc).

We also have an issue for resizing the images uploaded in rich texts like this one (#2044) but here the behavior is the expected one: we use the real size of the image.

What could help would be the ability to resize them inline, but that's something we should rather do in the new rich text editor (which is not yet available for updates #2839).

**Comment by Betree** [comment]
Created a test update on https://staging.opencollective.com/atomex to demo the issue.

Something we can do to improve the situation is to add a `max-height` on summary's images. 
Example with `max-height: 250px;`:

**Before**
![Screenshot_2020-04-29 atomex - Open Collective(1)](https://user-images.githubusercontent.com/1556356/80577406-20ec9080-8a07-11ea-8642-969f1142c72e.png)

**After**
![Screenshot_2020-04-29 atomex - Open Collective](https://user-images.githubusercontent.com/1556356/80577324-f8fd2d00-8a06-11ea-9bca-fbe354143a31.png)

--- 

We should also add more space below the title.

**Comment by snitin315** [comment]
I will work on this one.

**Comment by snitin315** [comment]
@Betree can you point me to the corresponding file? I'm still exploring the codebase.

**Comment by SudharakaP** [comment]
@snitin315 : I think what you are looking for is; 

https://github.com/opencollective/opencollective-frontend/blob/fc552adc5a7bbae15507ade801ed6b7711cfcc12/components/StyledUpdate.js#L293-L297

Hope that helps. :smile:

**Comment by Betree** [comment]
Fixed by https://github.com/opencollective/opencollective/issues/2547
