### ISSUE TITLE
Wrong metadata for update page

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2828]
Related to #2817 

Sharing an update on social media doesn't show the right title / description for the page. 
It should use the title of the update and the first sentences of the text.

See https://opencollective.com/rebelsmanager/updates/january-update
Facebook url parser: https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fopencollective.com%2Frebelsmanager%2Fupdates%2Fjanuary-update
![](https://d.pr/free/i/iOytYV+)

Ideally, we could use the first image of the update as the thumbnail image.

**Comment by Betree** [comment]
Will be partially resolved by https://github.com/opencollective/opencollective/issues/4013. Next step to complete this issue is to set the `description` with `stripHTML(update.sumary)`.
