### ISSUE TITLE
Link collective name to website

### ISSUE THREAD

**Issue by jancborchardt** [OpenCollective/OpenCollective#283]
On other projects (like Qubes OS) I also saw the »This is the Qubes OS open collective.« sentence on the top with the collective name being linked to the website. How can we link that on https://opencollective.com/opensourcedesign to http://opensourcedesign.net ?

**Comment by piamancini** [comment]
done. Sorry that you can't do this yourselves yet, we'll do a better job in the future!

**Comment by jancborchardt** [comment]
Good stuff, thanks! Also to not lead people away from your platform, the link should be `target="_blank"` to open in a new tab since it’s external. cc @asood123

**Comment by asood123** [comment]
thanks @jancborchardt. Fixed: https://github.com/OpenCollective/opencollective-website/pull/620
