### ISSUE TITLE
Collective's "Edit" menu categories

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2832]
The menu on `/{collective}/edit` is getting big and https://github.com/opencollective/opencollective-frontend/pull/3222 is going to introduce a new section for host settings, separated from the rest. I think it would add clarity to group the entries in categories. That may also help if we want to simplify the mobile version.
 
## Best solution for this problem

Add categories to separate entries (`Profile` & `Financial` in the example below).

![image](https://user-images.githubusercontent.com/1556356/72627321-91860a80-394c-11ea-992f-5535ecefcf4a.png)

This menu should consider what was defined for host's settings by @alanna in https://github.com/opencollective/opencollective/issues/2665. My proposal is to group entries in 4 categories: `Profile`, `Financial`, `Features` and `Advanced` (I haven't included all settings page in this example).

> .
> └── Settings
>     ├── Profile
>     │   ├── Info
>     │   ├── Images
>     │   ├── Connected accounts
>     │   └── Core contributors
>     ├── Financial
>     │   ├── Host
>     │   ├── Payment methods
>     │   ├── Payout methods
>     │   ├── Gift cards
>     │   ├── Tiers
>     │   ├── Expense policy
>     │   └── Invoices & receipts
>     ├── Features
>     │   ├── Goals
>     │   └── Conversations
>     └── Advanced
>         ├── Export
>         ├── Webhooks
>         └── Archive or delete

**Comment by Memo-Es** [comment]
Closing this issue in favor of #3395
