### ISSUE TITLE
Unable to add Collective to host

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2837]
I created this Collective: https://opencollective.com/scuttlebutt-grantwriting

I want to add it to this host: https://opencollective.com/protozoa

I am an admin of both.

There seems to be no way to do it. There's no "apply" button visible to me on the Protozoa page. How do I add the Collective to the host?

**Comment by znarf** [comment]
1) https://opencollective.com/scuttlebutt-grantwriting -> Edit
2) Host
3) "Use my own host"
4) Organization -> Protozoa

**Comment by Betree** [comment]
The org has `settings.apply` to `true`, so this seems related to the host plan: https://github.com/opencollective/opencollective-api/blob/a6531bab4dac2833ebf3f894fa539b17b87f66fb/server/models/Collective.js#L914

**Comment by znarf** [comment]
@Betree I was assuming `settings.apply` was not set, will have a look.

**Comment by alanna** [comment]
@znarf  those steps worked but I never would have figured that out on my own. I was clicking "use existing host" and getting stuck.

When I try to add it to Protozoa, I get the error "Host is already hosting the maximum amount of collectives its plan allows" but there's no option to edit my plan? This needs to link to where I can do that or I'm stuck.

**Comment by znarf** [comment]
@alanna Thank you for the feedback, we're gonna improve.

- apply button will be visible all time whatever the limits
- but will be disabled if host is over limit
- better error management in the collective "Host" panel

Otherwise, Protoza is currently in the "Legacy Single Host Plan + unlimited Added Funds" and effectively needs an upgrade to to host more than 1 collective.

**Comment by znarf** [comment]
<img width="1098" alt="Capture d’écran 2020-01-22 à 12 54 03" src="https://user-images.githubusercontent.com/806/72892234-500fa980-3d16-11ea-87b1-d72906985917.png">
