### ISSUE TITLE
Rich text editor: add support for text alignment

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2838]
The only place where we're not using the `RichTextEditor` yet is the **Updates** feature. Though the change would be fairly easy, we'd lost a feature on the way: the ability to align text. 

![image](https://user-images.githubusercontent.com/1556356/72886715-9959fc00-3d0a-11ea-83ba-1c13fbb47b37.png)

This feature is [used today](https://user-images.githubusercontent.com/1556356/72886762-b1ca1680-3d0a-11ea-928e-bf23155b2c57.png), so we don't want to break it. Unfortunately, Trix has no native support for this (see https://github.com/basecamp/trix/issues/289) but it can still be achieved.

**Steps**
- Implement feature on Trix editor in the most standard way possible. Right now using `class` seems to be the most appropriate.
- Allow required fields on API's sanitizer. If using class, we must only allow the classes dedicated to alignment

**Comment by SudharakaP** [comment]
@Betree : Just wondering; maybe this was discussed before; why don't we go for [Quill](https://quilljs.com/) instead of [Trix](https://trix-editor.org/)? Felt like Quill has more features such as the justification out of box. 🤔

**Comment by Betree** [comment]
@SudharakaP The rational for using Trix was documented in https://github.com/opencollective/opencollective/issues/2508 + https://github.com/opencollective/opencollective-frontend/pull/2782. Unfortunately neither of these editors are perfect, so even if Trix works pretty well for 90% of what we do we still need some work for the last 10%.

We're still open to switch to another library in the future if we find something that is simpler or works better.

**Comment by SudharakaP** [comment]
> @SudharakaP The rational for using Trix was documented in #2508 + [opencollective/opencollective-frontend#2782](https://github.com/opencollective/opencollective-frontend/pull/2782). Unfortunately neither of these editors are perfect, so even if Trix works pretty well for 90% of what we do we still need some work for the last 10%.
> 
> We're still open to switch to another library in the future if we find something that is simpler or works better.

Thanks for the links and information. Now I get a clearer picture. 🤔

**Comment by Betree** [comment]
Just noticed that the feature doesn't work today in react-quill, there's no classes for the `.ql-align-right` in our emails and since we sanitize the content, they're already removed from all the content! So this is not a blocker for https://github.com/opencollective/opencollective/issues/2839, I'll remove the buttons from the frontend until we're ready to tackle this issue.
