### ISSUE TITLE
Move updates to the new `RichTextEditor`

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2839]
Related to https://github.com/opencollective/opencollective/issues/1805

**Updates** is the last feature that still uses the `MarkdownEditor` (through `HTMLEditor`). We want to migrate it to the new editor, so that we have only one to maintain.

Paths that need to be migrated to `RichTextEditor`:
- `/{collective}/updates/new`
- `/{collective}/updates/:updateSlug` (the "edit" mode)

We must also rename `test/cypress/integration/28-update.create.test.js` to `test/cypress/integration/28-updates.test.js` and edit tests to use latest editor.

**Comment by Betree** [comment]
The only element needed for this issue is to allow people to add H1 and H2 tags. Unlike other contents, we want to allow top-level titles for updates.

**Comment by awright** [comment]
the update feature is great but has frustrating formatting tooling, particularly with carriage returns. one needs to have no space between paragraphs in order for the preview and sent email to have spacing. see visual description here: https://docs.google.com/drawings/d/16LZTUxOpxzv2MCIUIvs7Hj48r5LRdjFJJfOCMDv_EaQ/edit?usp=sharing
