### ISSUE TITLE
Getting Open Source Design collective added to the Open Source Collective

### ISSUE THREAD

**Issue by jancborchardt** [OpenCollective/OpenCollective#284]
Is it possible to get our [Open Source Design collective](https://opencollective.com/opensourcedesign) added to the list at https://opencollective.com/opensource ? Because we consider ourselves a project in the open source space of course. :)

**Comment by piamancini** [comment]
done. also see #282

**Comment by jancborchardt** [comment]
:tada: yeah, assumed that it has something to do with the registration flow through Github. Thanks!
