### ISSUE TITLE
React Intl: timeZone is not supported.

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2841]
In Frontend, when using a `FormattedDate` or `FormattedTime` component with the `timeZone` prop, we get the following warning.

```
[React Intl] Error formatting date.
RangeError: timeZone is not supported.
    at InitializeDateTimeFormat (/Users/fhodierne/Dev/opencollective/frontend/node_modules/intl/lib/core.js:3216:33)
...
```

We would like to avoid having this error and have a graceful fallback. Note that this issue is only affecting server side rendering, client side works fine.

In [HeroEventDetails.js](https://github.com/opencollective/opencollective-frontend/blob/master/components/collective-page/hero/HeroEventDetails.js), we have a mitigation in place and we would now like to have a general solution.

I'm suggesting to create new components wrapping `FormattedDate` and `FormattedTime` and only passing the `timeZone` when rendering on the server side.

**Comment by znarf** [comment]
@Betree Do you agree? Good for a bounty?

**Comment by Betree** [comment]
@znarf I would be ok with that solution. I think this may also be solvable by adding the right `Intl` polyfills.

**Comment by znarf** [comment]
@Betree that would be more elegant indeed, let's dig into it.

**Comment by Betree** [comment]
Worth trying: https://github.com/yeutech-lab/react-intl-polyfill
I don't know if this the best way to polyfill, but it may be good for quick testing.

**Comment by znarf** [comment]
@Betree at first glance, doesn't seems like a good fit, we're more looking for something to polyfill node and adding extra features.

**Comment by znarf** [comment]
In the end, looks like the error is in the server side polyfill, this can be solved by revamping the Intl setup, as explored in https://github.com/opencollective/opencollective-frontend/pull/3412

**Comment by znarf** [comment]
Fixed in https://github.com/opencollective/opencollective-frontend/pull/3993
