### ISSUE TITLE
Add more options for Hosts to charge Collectives their Host Fee

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2843]
With the new paid host plans going into effect, I think it's time we add more options for the fees Hosts can charge their Collectives. I just upgraded my own Host to the small plan and immediately wanted the choice to pass on the fees to the Collectives, but our current system does not make this easy. 

I think the options should be:
1. A % of all incoming funds (the option we have now)
2. A monthly set fee (e.g. $10/month)
3. No fee

I thought about setting up monthly contributions from each Collective to the host for "admin fee" as a hack, but there's no way to contribute directly to a host so it's not possible. With the new payment structure, it's especially unfair to force hosts to create a Collective to receive fees as they will have to pay for it.

We either need to transform hosts into an entity that can have its own budget, or give hosts a default Collective for free to send the Collective fees to. See #1723 and #1985.

Also see #2821 for the ability to charge different fees to different Collectives.

**Comment by alanna** [comment]
A couple more ideas:

* Charge a Collective a one-time fee
* An option to simply pass on whatever fees the host is paying Open Collective to their Collectives automatically

**Comment by flaki** [comment]
There's also the added issue of monthly fees to hosted orgs who are only intermittently active - when they are not active, a base fee feels like a needless charge, and when they _are_ active and generating work for their host, a baseline fee would not be fair either.

We are working around this currently by charging a fix per-transaction fee (1 EUR) that covers or at least contributes to the variable cost of the activity (basically forwarding the cost we pay to our accountant to account for these costs), but we would like to charge our active collectives a "support contribution" that helps us cover the underlying foundation's fixed costs. The way we figured this could work is we have created a separate collective for the foundation (so we have both a host  AND a collective for the underlying foundation), and we just present our budget and running costs openly in this collective. This also allows our hosted collectives to contribute on a "pay-what-you-can-spare" basis for all the non-accounting-related services they are using (e.g. our hosted Matrix installation for chat, or our Zoom subscription for video that all these collectives have access to).

One drawback of this approach is that managing the foundation's collective adds an extra collective to our host and managing its budget quickly puts us past the limits of free collectives, so even as a host just starting out and few active collectives we are forced to paying the monthly fee. While we are glad to be supporting development (as we see it going really well), this might be an issue and a barrier of entry for other bottom-up bootstrapped hosts like us.

**Comment by alanna** [comment]
@flaki - Thanks for the feedback. I totally agree. We are aware of the problems with making hosts also create a Collective for their own budget. We are planning to integrate Collective budget features into host pages soon so this won't be needed.

**Comment by alanna** [comment]
Closing in favor of #3362 because the rest is done with the new pricing model
