### ISSUE TITLE
Tax form not sent to user submitting expense to an event

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2844]
I'm not sure if submitting the expense to an event is the cause, but user martin-abrahams should have got the tax form for [this expense](https://opencollective.com/sustain-2020-5874aeeb/expenses/13295). Our system shows "tax form required" but looking at HelloWorks it seems it was not sent out, and the user reports he has not got it.

1) Can this be triggered somehow so the user's payment is not blocked?
2) We need to figure out why it wasn't sent and make sure it's not affecting more users.

**Comment by znarf** [comment]
@alanna the invoice is exactly at 600$ which is the tax form threshold, I think we have a mismatch in how we're checking it.

Should we ask for a tax form if the total is reaching exactly $600 or only when it's over $600?

**Comment by znarf** [comment]
It was sent 4 hours ago. 

![Screenshot 2020-01-23 at 09 50 49](https://user-images.githubusercontent.com/806/72969394-ab4ca500-3dc5-11ea-838f-822b2f988d70.png)
