### ISSUE TITLE
Unable to delete a past event

### ISSUE THREAD

**Issue by IoTopenTech** [opencollective/opencollective#2846]
How coul I delete a past event?

**Comment by IoTopenTech** [comment]
Dear znarf,

I cannot find the Delete button
![imagen](https://user-images.githubusercontent.com/52624907/72989055-cf23e100-3ded-11ea-90d0-ca2675eec137.png)

**Comment by znarf** [comment]
What's the URL of your event? It likely it's unfortunately not deletable.

**Comment by IoTopenTech** [comment]
https://opencollective.com/iot-open-tech/events/reunion-de-comunidades-ttn-40908ev

**Comment by znarf** [comment]
Sorry, it's not possible at this stage to delete an event with attached expenses or transactions.

In the future, we would like to allow you to "Archive" it instead but we have to work on the feature.

**Comment by znarf** [comment]
This is now possible.
