### ISSUE TITLE
Review permissions for Payout Methods

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2848]
As part of revamping the expense flow and in the spirit of _"Never give more access to users than what they need"_, I'm wondering if **collective admins** really need to know the details about the payout methods used for expenses (ie. the Paypal email address, bank account...etc). 

Sounds to me that this information is only relevant for **hosts admins** and should be limited to them. Is this assumption correct?

Ping: @piamancini @alanna @xdamman @alinamanko

**Comment by alanna** [comment]
You are correct. Only host admins need detailed payout info.

**Comment by Betree** [comment]
Thanks for the feedback, this has been taken into account in the new expense flow.
