### ISSUE TITLE
The parameters from the post-donation redirect doesn't return an UUID primary key for orderId and transactionId

### ISSUE THREAD

**Issue by danielsum** [opencollective/opencollective#2849]
**Describe the bug**
I try to implement the post-donation redirect link and retrieve the transactions detail after but when I have the redirect back link, it doesn't seems to send me an UUID primary key value like in the GraphQl Api but an integer. 

Here is what I have for exemple as parameters : 

?orderId=63122&transactionid=327551&status=PAID

**To Reproduce**
1. Generate a link like : https://opencollective.com/community/donate/20?redirect=http://localhost:3000/callback
2. Validate or make a pending request
4. In the url you will have something like : http://localhost:3000/callback?orderId=63124&transactionid=null&status=PENDING or http://localhost:3000/callback?orderId=63122&transactionid=327551&status=PAID

**Expected behavior**
Expected something like : http://localhost:3000/callback?transactionid=117fe88f-3fc7-4634-b78c-05b0fd0cf7d8 to find the detail of the transaction through GraphQL instead of an integer

**Comment by Betree** [comment]
Hi @danielsum, thank you for reporting this. We indeed switched to `uuid` for API V2 (the one you're using) while the V1 was using integer values.

@znarf What do you think is the best way to solve this, should we pass an `orderUuid` to the redirect URL? Or accept old-style ids for order's endpoints on Graphql V2?

**Comment by danielsum** [comment]
Hi @Betree , I think for the moment the easier will be to return the orderUuid, transactionUuid in the redirect link so it gives the flexibility to people to use the new uuid (v2) or the old one (v1). Because I would like to link to the url page of the order and the link still only compatible with the integer id (I think ?) ex: https://opencollective.com/wwcodenyc/orders/13202.

Little typo noticed, the parameter transactionid should be in camelcase like orderId so transaction**Id**
