### ISSUE TITLE
Image broken in  expense notification email

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2850]
![Screen Shot 2020-01-27 at 9 48 28 AM](https://user-images.githubusercontent.com/5498878/73141559-4c02d380-40ea-11ea-8f2b-51a3e4cc8ca2.png)

This expense came through for OSC but the image is broken. I assume it's meant to be the Collective logo?

**Comment by Betree** [comment]
It should be the attachment there. May have been broken in https://github.com/opencollective/opencollective-api/pull/3190

**Comment by alanna** [comment]
This is still happening. Can it be a bounty?

**Comment by Betree** [comment]
Sorry, this one had slipped my attention but should be fixed as a priority
