### ISSUE TITLE
$250 missing from Collective balance

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2854]
![Screen Shot 2020-01-28 at 10 15 02 AM](https://user-images.githubusercontent.com/5498878/73214464-1ed02700-41b7-11ea-8c81-90d0680c4db1.png)

$50,000 contribution - $2500 host fee - $2500 platform fee + $2500 + $2500 *should* add up to $50,000 balance, but it's showing $49,750 - why?

**Comment by Betree** [comment]
$50,000.00 -$2,500.00 (-5% host fee) -$2,500.00 (-5% Open Collective fee) = **$45,000**
$2,500.00 -$125.00 (-5% host fee) = **$2375**
$2,500.00 -$125.00 (-5% host fee) = **$2375**

Total: $49,750.00 USD

I think you missed the host fees on the two financial contributions from OSC and inc that sums up to $250. I'll be happy to remove them if there are not supposed to be there, just let me know.

**Comment by alanna** [comment]
Ah, that explains it. Yes please remove them! Thanks @Betree

**Comment by Betree** [comment]
Should be fixed now:

![image](https://user-images.githubusercontent.com/1556356/73222183-e7378f80-4162-11ea-8bdd-397e2e5604c9.png)
