### ISSUE TITLE
Base URL slug for new org on name not twitter handle

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2856]
I helped a user set up opencollective.com/coopdevinst today. Their organization goes by the name "CDI" and that's what they put in the "name" field. But the system apparently pulled the URL slug from their twitter handle, which was unexpected.

### MVP

Base slug on name

### Best solution

Allow users to preview and edit the slug during org creation, just like we do when creating a new. It should generate a slug from the name, show it to them, and let them edit it if they want.

**Comment by Betree** [comment]
Not sure about adding a new field in the new collective form because we may not want to make it as simple as possible, but definitely agree with the MVP.

**Comment by alob-mtc** [comment]
@Betree is it possible I take up this issue.

**Comment by Betree** [comment]
@alob-mtc it's better to work on one thing at a time (I see you already picked https://github.com/opencollective/opencollective/issues/3450). But if you feel like taking both at the same time, go ahead :-)

**Comment by alob-mtc** [comment]
As soon as i'm done with  #3450 i'll pick this up

**Comment by FluxZA** [comment]
I found this issue on your main page for "good first-issues". I would be happy to work on it if @alob-mtc is still working on #3450 .

**Comment by alob-mtc** [comment]
@fluxZa you are free to pick it up if that's fine by @Betree

**Comment by FluxZA** [comment]
Hi. I am currently working on this, and while reading through the documentation I discovered what the 'bounty candidate' tag meant. Is there any scope for a bounty to be assigned? I will finish working on the issue regardless, but I figured I would ask as I could use the money.

**Comment by alanna** [comment]
@znarf

**Comment by znarf** [comment]
For a bounty to be added, one engineer need to be confident enough about the issue that they're willing to review and engage until completion. You can always ask, but I'm personally not in such position at this point. If someone else from the team is, they will show up.

If you're still willing to contribute (for fun, for free), we'll review your PR and make our best to help until completion. 

Exceptionally, we may thank you with a "retro-active" bounty, but this should not be asked, this has to come from us.

**Comment by FluxZA** [comment]
@znarf  Thanks for the info, I am happy to continue working on the issue. Is there anything I need to do to add reviewers to my pull request?

**Comment by Betree** [comment]
With @FluxZA work in https://github.com/opencollective/opencollective-api/pull/6439, the name is now prioritized over the Twitter handle when generating a default slug.

Combined with the fact that https://opencollective.com/organizations/new now has an input for the organization slug, we can considered this issue resolved.
