### ISSUE TITLE
typo on the website

### ISSUE THREAD

**Issue by adong** [opencollective/opencollective#2857]
**Describe the bug**

It's often embarrassing to see that translations of localizations are poorly worded. In this case, just plain wrong.

**To Reproduce**
1. Go to https://opencollective.com/
2. Scroll down to the bottom 
3. See error in the screenshot section

**Expected behavior**

Please change `简化字` to `中文` or `简体中文` 

简化字 is a direct translation from word to word for `Simplified Chinese characters`

While `中文` and `简体中文` are the rhetoric words that used on a daily basis. 

**Screenshots**
![image](https://user-images.githubusercontent.com/15989893/73497446-acef0d80-436f-11ea-82b6-73a5fb511cb0.png)

**Desktop (please complete the following information):**
N/A
**Smartphone (please complete the following information):**
N/A
**Additional context**
N/A

**Comment by znarf** [comment]
@adong thank you for reporting! not sure how that string landed here. do you want to submit a PR for that? the file is https://github.com/opencollective/opencollective-frontend/blob/master/lib/constants/locales.js

**Comment by adong** [comment]
@znarf Here's a PR for it. https://github.com/opencollective/opencollective-frontend/pull/3457 Thank you!
