### ISSUE TITLE
Issue when trying to change the host fee

### ISSUE THREAD

**Issue by jfdh** [opencollective/opencollective#2860]
**Describe the bug**
Not possible to change the host fee

**To Reproduce**
1. Go to 'https://opencollective.com/brussels/edit/advanced'

**Expected behavior**
I wish to setup a 3% fee for the host

**Screenshots**
![Screenshot 2020-02-03 at 08 54 01](https://user-images.githubusercontent.com/30813303/73638500-d0b19c80-466a-11ea-934a-ae6b84245592.png)

**Desktop (please complete the following information):**
I tried on several different browsers

**Smartphone (please complete the following information):**
Same

Thank you for your help

**Comment by znarf** [comment]
Thank you for the report @jfdh, we'll look into it.

**Comment by jfdh** [comment]
Any update on this one? I would love to launch our new financial model starting 15 February. Many thanks and good day :)

**Comment by znarf** [comment]
@jfdh It's a priority, looking at it this week for sure.

**Comment by znarf** [comment]
I know it will sounds weird, but this is linked to this collective having an invalid "slug": https://opencollective.com/perma@transforma

Would be great to contact them and ask if we can change their slug to `permatransforma` or `perma-transforma`.

In the meantime, I'm gonna take care of updating the host fee.

**Comment by znarf** [comment]
Done.

**Comment by jfdh** [comment]
Is there a place where these 3% percents go automatically on oc or should I add these manually each month in the collective I choose to manage the finance of the host?
