### ISSUE TITLE
Include date in receipt PDF file

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2861]
## User Story 

As a sponsor, I want to avoid the admin hassle of managing my open collective receipts. 

They'd like to 

a) avoid logging in each time so receive PDF via email

and 

b) better track/find files (the uuid is problematic). They suggest a timestamp name. 

## MVP

Sending a monthly consolidated PDF in the monthly report seems like an easy improvement at the moment. 

Not sure what can we done for the file names.

**Comment by freyfogle** [comment]
Thanks for opening an issue about this.

Just to clarify, the file name could include the uuid, please just also include name (so I dont have to open the file to figure out what it is) and date stamp. For example:
opencollective-20200203-uuid.pdf

**Comment by piamancini** [comment]
> please just also include name

This makes sense.

**Comment by Betree** [comment]
Extracted the proposal for receipts in email in https://github.com/opencollective/opencollective/issues/2867. 

Adding the date in the filename is a good idea. Let's keep this issue about this topic.

**Comment by znarf** [comment]
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the Open Source Festival event. If not completed there, it will be later open to everyone.

**Comment by Devvyky** [comment]
@piamancini can you assign the issue to me

**Comment by Devvyky** [comment]
@piamancini I'd like to work on this issue. Can you assign the issue to me

**Comment by znarf** [comment]
@Devvyky you're assigned!

**Comment by Devvyky** [comment]
thanks @znarf 
I'd like to confirm that the repository for generating the receipt PDF file is this https://github.com/opencollective/opencollective-invoices

**Comment by olawanlejoel** [comment]
@piamancini I'd like to work on this issue. Can you assign the issue to me

**Comment by znarf** [comment]
Yes, happening there:
https://github.com/opencollective/opencollective-invoices/blob/master/src/server/controllers/transactions.js#L136
https://github.com/opencollective/opencollective-invoices/blob/master/src/server/controllers/transactions.js#L82

But also here:
https://github.com/opencollective/opencollective-api/blob/master/server/graphql/v1/queries.js#L353

**Comment by Devvyky** [comment]
Okay, thanks so much for the information @znarf

**Comment by znarf** [comment]
@Devvyky Any progress? Fyi, we'll have to unassign you if there is no significant activity within the next days.

**Comment by Devvyky** [comment]
There's progress @znarf I'd be done soon, I plead

**Comment by Devvyky** [comment]
@znarf there's progress. i should be done soon

**Comment by Devvyky** [comment]
@znarf most API calls are returning null value. 
![Screenshot from 2020-03-01 11-59-26](https://user-images.githubusercontent.com/25306314/75624848-96c7ad80-5bb8-11ea-914d-ea26b57b1528.png)

i created a custom date in the code on line 79 and 80
![Screenshot from 2020-03-01 05-33-54](https://user-images.githubusercontent.com/25306314/75624867-d9898580-5bb8-11ea-8657-db2828c0defa.png)

and it returned the date stamp in the filename of the receipt pdf file
![Screenshot from 2020-03-01 11-48-25](https://user-images.githubusercontent.com/25306314/75624897-19506d00-5bb9-11ea-87a4-0aea535c2188.png)

most of the API calls are returning Null Value.
I'm really sorry I'm a bit slow at fixing this @znarf i have exams, I plead.

**Comment by freyfogle** [comment]
please use an 8 digit date stamp (ie YYYYMMDD like 20200301 or 2020-03-01), it makes it much easier to write software to do something with the file

**Comment by Devvyky** [comment]
okay @freyfogle . Thanks, i would do just that.

**Comment by sdas13** [comment]
can I take up the issue? :)

**Comment by jeffin143** [comment]
> can I take up the issue? :)

Yes @sdas13 , you can have a go at it , since we didn't see any progress , and hence assigning you

**Comment by znarf** [comment]
Unassigning @Devvyky and hiding some comments to reduce noise.

**Comment by Betree** [comment]
:trophy: This issue has been completed by @leonardohof  

To claim the **$100** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
