### ISSUE TITLE
Allow root users to download receipts from profile page

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2862]
As an admin of an organization I can download the PDF file from an invoice from the main organization's page and the transactions page. Also note that while logged in as an admin I can also download the consolidated receipt. 

<img width="1332" alt="Screen Shot 2020-02-03 at 12 56 30 PM" src="https://user-images.githubusercontent.com/3671070/73651487-d320f000-4684-11ea-81ce-7e631c465770.png">

<img width="1268" alt="Screen Shot 2020-02-03 at 12 57 01 PM" src="https://user-images.githubusercontent.com/3671070/73651496-d6b47700-4684-11ea-9fc3-f710e1a09ad1.png">

If I am not an admin I can't download receipt from the organization's profile, but I can download it from the transaction list. In this case, I don't have access to the consolidated pdf file. 

<img width="1314" alt="Screen Shot 2020-02-03 at 1 01 08 PM" src="https://user-images.githubusercontent.com/3671070/73651710-4b87b100-4685-11ea-997f-8242d3a0c10c.png">

<img width="1343" alt="Screen Shot 2020-02-03 at 12 59 49 PM" src="https://user-images.githubusercontent.com/3671070/73651667-2bf08880-4685-11ea-8704-7500e5af53c4.png">

I don't understand the rationale for 

a) allowing the behaviour on the transactions page but not on the profile page. 

b) allowing one kind of behaviour (downloading individual pdfs while not an admin) but not the other one (consolidated pdfs)

We should make this coherent. My proposal would be: 

- prevent users from downloading PDF invoices in all instances from organizations they don't manage. 

- make it easier for sponsors to manage their invoices by sending them via email (see #2861)

**Comment by alanna** [comment]
I agree with what Pia is suggesting. Just a note to say, please retain access to everything for platform admins. We often need to download invoices and transactions to assist users with support.

**Comment by Betree** [comment]
@piamancini I believe the confusion comes from the fact that you have a root account, so you can theoretically see and download invoices for everyone.

> Prevent users from downloading PDF invoices in all instances from organizations they don't manage.

With a regular account (not root), there's no button to download invoices on both profile and transactions page.

So the only thing that I see left on this issue is to add the button to download invoices for root users on the profile pages.

**Comment by piamancini** [comment]
ah, got it. 

> So the only thing that I see left on this issue is to add the button to download invoices for root users on the profile pages.

Then it's not necessary. Root admins can download from txn page @Betree - My concern was public facing.

**Comment by piamancini** [comment]
Closing the issue as the only actionable is not needed.

**Comment by Betree** [comment]
Still agree that we should be consistent, the button for root users will be added in https://github.com/opencollective/opencollective-frontend/pull/3465
