### ISSUE TITLE
Emails: Add support for DMARK

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2865]
From https://postmaster.google.com, it seems that we could improve our domain's reputation by supporting [DMARK](https://www.mailgun.com/blog/domain-reputation-and-dmarc/). I'm not familiar with it, so we'll have to investigate on what's required to achieve this.

![image](https://user-images.githubusercontent.com/1556356/73660900-6532f380-4699-11ea-975a-269017895763.png)

**Comment by znarf** [comment]
That was done in https://github.com/opencollective/opencollective/issues/3106
