### ISSUE TITLE
Open Collective Roadmap February - April 2020

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2868]
Overview
====== 
The goal of this roadmap is to provide clarity for the core team and our community about our priorities for the next 3 months. While these are the projects we'll be working on, life happens and iterations might take place. 

Below the roadmap projects, we list additional projects we'd like to carry out this quarter but are not top priorities. Below that, a list of projects we want to tackle in May-July period. These don't have owners yet but we want to provide a 6month visibility so you know (what can be coming up). Please take this as an opportunity to signal preference, suggestions, etc.

Top level priority for the team is: 

Being [sustainable](https://drive.google.com/drive/u/1/folders/1OwRpuIehFQxRnJIRAksQ1Jd2xXZrhz5L) in the next 12 months while supporting [our mission](https://app.gitbook.com/@opencollective/s/help/) and our community in a way aligned with our [values](https://app.gitbook.com/@opencollective/s/help/the-open-collective-way). 

Roadmap Priorities are aligned with this goal and our prioritization framework. 

Prioritization Framework (updated)
--------------

We are a small team and hence we need to work hard to be focused and aligned. When we decide which project / feature to prioritize we judge them against the following questions: 

- **Does this serve our mission? (We are on a mission to help collaborative groups collect and spend money transparently)**
- **Will this make us financially sustainable within a year?**
- Will this bring us more Collectives, hosts and financial contributors?
- Is it feasible to build and maintain with our team and runway?
- Can this make us move faster?
- Does this increase quality and not technical debt?
- Is this already solved elsewhere or is it our unique contribution?
- Can we measure the success of  this?

Create Collective Flow Implementation 
============
Aligning the create collective flow with the [new business model for Fiscal Hosts.](https://blog.opencollective.com/new-host-plans/). We want to make it easier for collectives to find the right path for them. 

**Project Issue**: #2366 (design) & #2872 (implementation)
**Status**: Designed - Awaiting implementation
Owner: @piamancini 
Technical Owners: @znarf @sbinlondon 
Soft Delivery Date: March 31, 2020
**Metrics**: 
* More self-hosted  Collectives created
* Increase per-Collective revenue

Expense Flow Redesign
==============
**Issue**: #2394 
**Owner**: @alanna (and @piamancini)
**Technical Owner**: @Betree 
Status: Implementation
Soft Launch Date: 
Full MVP soft delivery date: End of Februrary   
**Metrics**:
- More expenses filed
- Less support requests
- Less host admin time spent
- Way fewer issues with invoices (fewer expense comments)
- Use of the new features (ex batch expenses)

Transferwise
===========
Host admins only option to automatically sync payouts via open collective is using paypal. We want to upgrade their experience enabling them to also use transferwise. This will also enable contributors to submit expenses in their own currency and support hosts management of multi-currency payments. This feature will be available to [hosts on a plan](https://opencollective.com/pricing). 

**Project Issues**:  https://github.com/opencollective/opencollective/issues/2836
**Owner**: @kewitz 
**Soft Delivery Date**: TBC
**Metrics**
- The number of hosts connecting to TransferWise.
- The number of expenses being paid with TransferWise.
- The volume of money being paid with TransferWise.
- Qualitative/Subjective: overall time spent by Hosts on paying out expenses.

Host Dashboard Re-design
============
The goal is to improve the host admins experience on open collective to manage their funds on the platform. 
**Owner**: @piamancini 
**Design Owner**: @Memo-Es 
**Project Issue**: TBD

Github Sponsors Collaboration
=============
We are helping collectives receive funds as an organization from Github users / orgs. Alpha integration is manual but we will work on an automated way of crediting those donations. 
**Owner**: @piamancini 
**Technical Owner**: @znarf 

Secondary Priorities on current Roadmap: 
--------------------------------

- Update subscriptions management page: @piamancini and @Memo-Es 
- Re-design content of on-boarding emails and look into steps to help hosts upgrade: @piamancini 
- Credit card failure alert (letting backers know when their subscription is about to expire @sbinlondon 
- SEPA Payments (in & out via Stripe) @kewitz 
- Event Issues and revamp @sbinlondon 
- Moderation project @Betree #2741 

May - July Roadmap Ideas (emphasis on ideas) 
--------------------------
- Email Templates for Hosts (allowing hosts to edit the automated emails they send to their community)
- Email redesign (updating the look & content across platform's emails)
- Email service (solution for collectives to have a collective email address they can use)
- Upgrade PayPal payouts API (this will save fees for the collectives)
- New Expense Flow iteration and testing
- 2FA
- Expenses in local currency
- PayPal for every host

**Comment by alanna** [comment]
Looks good!

A few questions....

1. If possible I'd like to have input on the specs for the host dashboard project before I go on leave. Should we have a call about it? Not to get super detailed but just make sure the important stuff is covered and understood.

2. Can we add Bitcoin payments to the secondary priorities? If the OpenNode trial goes well we may want to integrate it into the checkout process. (I think it will follow a similar pattern to processing payments for Github Sponsors so it might piggyback on that work).

3. Should we assume that Back Your Stack dev will need to be funded by OSC and we'll need to hire an outside developer? Or is OC Inc planning to continue contributing some capacity?

**Comment by piamancini** [comment]
> If possible I'd like to have input on the specs for the host dashboard project before I go on leave. Should we have a call about it? Not to get super detailed but just make sure the important stuff is covered and understood.

Yes, let's schedule a call before you go on leave. 

> Can we add Bitcoin payments to the secondary priorities? If the OpenNode trial goes well we may want to integrate it into the checkout process. (I think it will follow a similar pattern to processing payments for Github Sponsors so it might piggyback on that work)

We can, but with you on leave for the whole roadmap and Github Sponsors still in manual mode, it's unlikely I'll be able to manage it. Depends on the volume. 

> Should we assume that Back Your Stack dev will need to be funded by OSC and we'll need to hire an outside developer? Or is OC Inc planning to continue contributing some capacity?

Yes. OC's commitment is to do maintenance 1 day a month and stay involved to answer questions and review stuff as needed. There's no plan for the team to do any additional development.

**Comment by Wodann** [comment]
@znarf As a collective, we want to extend our Open Collective services to Github users, through the Github Sponsors program for organizations. Currently, our fiscal host would manually have to input all Github Sponsors stripe transactions into Open Collective manually, which would be too much work for them.

I've checked existing issues and projects to see if there has been progress on the "Github Sponsors Collaboration" task, but couldn't find any information. What's the status of this?

Depending on (time) complexity of the task, I might be able to help out if this brings automated integration of Github Sponsors to all collectives/fiscal hosts :)

**Comment by alanna** [comment]
> bring automated integration of Github Sponsors to all collectives/fiscal hosts

That's definitely the outcome we'd like to see @Wodann! But we haven't had the dev capacity yet. 

We are still manually crediting Github Sponsors funds to Collectives ourselves. I would love to automate it, and to make that available to all hosts. I think to achieve that, we'll need work on both the Open Collective and Github sides. We have a good relationship with Github but they have other priorities also, so progress can be slow sometimes.

I'm under the impression that this project would be significantly complex, and have been thinking we'll need to seek funding for the dev capacity we'll need. It would be really helpful to get approximate scoping and a better understanding of what would be needed from @znarf . Open Source Collective wants to invest in this project but we don't have a fully fledged plan yet.

Thank you for offering to help! I am interested to hear what @znarf thinks about it.

**Comment by Wodann** [comment]
Thank you for your detailed response. I'll wait and see if I can contribute :)

**Comment by znarf** [comment]
@Wodann @alanna It's impossible to move this project forward without better data exports from GitHub. As of today, we don't get any useful information about who contributed on GitHub sponsors and this is blocking the work on automation.

As soon as we get the email or GitHub handle of the donators, we can start integrating the data in a better way on Open Collective.

@Wodann Not sure what kind of export you're able to generate on your side, feel free to contact me on our Slack for details.

**Comment by piamancini** [comment]
Q1 Review & Priorities Call 
===================

Check-in - what worked / what didn’t
---------------------------------

François: 
++ Good quarter / great retreat in January retreats / on track to execute what we wanted / Focused
-- Personally: messy since COVID-19 / lost track of things in bounty programme / Adapt to pandemic

Ben: 
++ Expense flow went well, a bit off schedule but iterating based on feedback. 
++ keep the boat floating despite the coronavirus. We were able to adapt. We were able to react quickly
++ Improving design / engineering process 
++ Leo / Kate: more power
-- Better scoped some features (ie submit expense as collectives)
-- Still unclear where OC Community is going. We’ll have to meet them somewhere. 

Kate:
++ Able to deliver the CCF project on time - Feels really good. 
++ Team - how cohesive we feel a lot of the time. Even if it’s remote - I feel I’m more integrated with this time. 
-- Personally: survival mode. Deliver and learn codebase. Want to be more of a well - rounded OC dev. 

Leo:
++ How everyone worked normal / Shipped things / Work well together 
-- Defined better MVPs for projects. Otherwise they increase in size. Lots of unknowns. Reevaluating MVPs. 
-- lower productivity during pandemic. Affected the roadmap. 

Memo: 
++ Team can adapt to new situations. We are resilient. Ability to react. Quick response. 
++ Improving productivity in calls. Better use of online time. Engineering / Design biweekly calls. Design System updates.  
-- Latency of QA process. We don’t preview changes and see them late in the process. Trade-off between host dashboard and expense flow. 

Cuiki
++ Engineering + Design relationship has improved. 
-- Still need to work on catching issues before. Tighten up decision-making framework and how to handle feedback process. 

Pia: 
++ We are on track to ship on time. 
++ We reacted well to covid - proud of that
++ Saw an opportunity and reacted quickly - took action
++ Feedback loops and iteration processes have been good (especially compared to what it was)

-- Still late with deliveries, things that we could have shipped before
-- Metrics - still not tracking and sharing things properly

Learnings: 

Incremental parts a clear path to ship one bit at a time.  
ship in phases, 
better design MVPs, 
build in iterative parts. 
Keep (also maybe Improve) project ownership template. 

Projects Review
===========
Create Collective Flow Implementation
-----------------------
Project owner: @piamancini 
Technical Owner: @sbinlondon 
Design owner: @Memo-Es 
🚀🚀Shipped. Live in opencollective.com/create 

Expense Flow Redesign & Implementation
------------------------------
Project Owner: @alanna @piamancini 
Technical Owner: @Betree 
Design Owner: @raulgrafico 
🚀🚀Shipping today (5/12) - Live in opencollective.com/engineering/expenses/new 

**Review & Learnings:** 
- Improvement: We could have launched earlier. Replacing bits and pieces before. 
- Goals to release: making sure we didn’t break anything. We had to fix the Christmas Tree before. 
Christmas tree fix was late to be delivered. Tags redesign was shipped before and it was less important. Design was seeing the tip of the iceberg only - they didn’t realise the impact the change would have had. 
- -- We are not assigning priorities to issues for design.  We need to improve how we communicate critical issues / importance to design.  Feedback loop translated into more quality.
- ++ Adding features that align with our values. Values are included in the design.  

Transferwise
-------------
Project & Technical owner:  @kewitz 
🚀🚀 MVP: shipped. Team is happy. 

**Review & Learnings**
- Unknowns: Transferwise limitations: ie GBP->GBP
- Follow-on issues: more features to add in the host dashboard. 
- Enforce limitations in expense-side. Display the fees beforehand. 
- Final Shipping when we ship expense flow. 
- Some potentially harmful unexpected bugs after deploy. 

Host Dashboard Re-design
--------------------------
Project owner: @piamancini 
Design Owner: @Memo-Es 
Status: Wireframes: shipped, UI design: in process. 

**Review & Learnings** 
Starting Design - late with delivery but good process. 
++ Involving people in reviews early
++ Well scoped
@cuiki: taking over design of the dashboard. Break it up in small pieces and deliver in parts. 
Q2 Timeframe: 
Shell / general logic of dashboard: 2 weeks prod ready.  

Github Sponsors Collaboration
-----------------------------
Owner: @piamancini
Technical Owner: @znarf
**Review & learnings** 
Happening in a manual way. Github is slow in growing this program. Bugs. 
@alanna is going to take over. Include it in the homepage? 
Data export: still no info about the person who donated. 

Secondary Priorities on  Roadmap:
------------------------------------
🚀🚀[DONE] Update subscriptions management page: @piamancini and @Memo-Es
🚀🚀[DONE] Re-design content of on-boarding emails and look into steps to help hosts upgrade: @piamancini
🚀🚀[DONE] Credit card failure alert (letting backers know when their subscription is about to expire @sbinlondon
SEPA Payments (in & out via Stripe) @kewitz
Event Issues and revamp @sbinlondon
🚀[DONE] Revamped events settings 
🚀🚀[DONE] Tiers & Tickets separated. 
🚀🚀[DONE] Hosts out of sync fixes
🚀🚀[DONE] Moderation project @Betree #2741
