### ISSUE TITLE
Moving a Collective to a host with a different currency

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2869]
Recently we had a bunch of issues when Flarum moved from a USD host to a EUR host. We have the same situation coming up soon with Social.coop moving from c-corp host (US) to Platform6 (UK). We are the ones forcing them to move, because we're shutting down c-corp host, so we need to find a solution for them.

**Comment by alanna** [comment]
@znarf - any further thoughts about this?

**Comment by znarf** [comment]
@alanna Not at this point, it's complicated.

**Comment by znarf** [comment]
Removing "priority" and adding "important" instead.

**Comment by znarf** [comment]
With the Ledger refactor from this year, we're now confident doing this. People still need to contact support so we can check their account before.

**Comment by alanna** [comment]
Good to know! @shannondwray can you add to docs please?
