### ISSUE TITLE
1099 for US based contractors: deadline Jan 31

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#287]
[Payable](https://payable.com) has a great website with all the info on the regulations around it https://payable.com/taxes

> 1099 forms should be sent to recipients who are an individual or a partnership that you paid $600 or more during the tax year in the course of your trade or business. (use box 7)
Rents paid for office space or machinery hire if greater than $600 (use box 1). 
Fees paid to attorneys, even if they are a corporation (use box 14)
you paid $10 or more in royalties. (use box 2 )
If you have contracted foreign individuals to work for you and they are not US tax payers, and are not based in US then you don't need to send them a 1099.

Todo:
- [x] Query to find out to whom we paid more than $600 in 2016
- [x] Identify who is US based
- [x] Collect EIN or SSN for each
- [x] Send them and IRS 1099 form

**Comment by xdamman** [comment]
I've added the query to the Wiki for Hosts: https://github.com/OpenCollective/OpenCollective/wiki/Queries-for-hosts#us-taxes-1099

Our accountant Sherrill is contacting them to get their W9, then will issue the 1099 to them and the IRS by end of month.

**Comment by piamancini** [comment]
[This](http://answers.teespring.com/customer/en/portal/articles/1856182-prepare-for-tax-season-form-1099-s-faqs) is a good reference to have, we could add something like it to our FAQs
