### ISSUE TITLE
Github deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2870]
Github deprecated authentication via URL query parameters. The [way we configure Octokit](https://github.com/opencollective/opencollective-api/blob/5226f030ee137d06482e2b3de163ae017dc0abf5/server/lib/github.js#L52) does use these query parameters.

This [issue](https://github.com/octokit/rest.js/issues/1588) provides explanations and instructions to migrate. Basically we need to convert the code to the following and update env variables for staging and prod: 

```js
octokitParams.auth = {
  userAgent: 'xxxxxxxx',
  auth: 'xxxxxxxxxxxxxxxxxxxxxx'
}
```

Email received from Github:

> Hello there!
> 
> On February 4th, 2020 at 01:38 (UTC) your application (OpenCollective) used its `client_id` and `client_secret` (with the User-Agent octokit.js/_______) as part of a set of query parameters to access an endpoint through the GitHub API:
> 
> https://api.github.com/organizations/_______/repos
> 
> Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated.
> 
> Depending on your API usage, we'll be sending you this email reminder at most once every 3 days.
> Just one URL that was accessed with a User-Agent combination will be listed in the email reminder, not all.
> 
> Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.
> 
> Thanks,
> The GitHub Team

**Comment by znarf** [comment]
Should have been taken care of in https://github.com/opencollective/opencollective-api/pull/3424
