### ISSUE TITLE
Implement 'Create a Collective' page

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#2873]
Part of #2872 

<img width="899" alt="Screenshot 2020-02-05 at 16 34 38" src="https://user-images.githubusercontent.com/37520401/73859227-fe007500-4839-11ea-840d-cfa13472bd85.png">

As seen [in the Figma design](https://www.figma.com/file/e71tBo0Sr8J7R5n6iMkqI42d/OC.COM-04-%2F-Collectives-%E2%86%92-Create%2C-Edit?node-id=7762%3A42619), we want an intial page where users select which kind of collective they're starting.

## Questions

* What do we show with the 'see examples' for each? @piamancini @znarf 
* There doesn't seem to be anything specific in the designs for the creating a 'climate initiative' collective? Which design should I use for that - just the normal non-Github one? @piamancini @Memo-Es

**Comment by xdamman** [comment]
Re: climate. Yes just the normal form. The only difference is that it should automatically add the tag "climate" to the collective when creating it.

@Memo-Es can we have another illustration for the climate? It's hard to see the link with Saturn and other stars and then buildings made of concrete. Something like the planet burning, or the same image than on the homepage but where the universe is replaced by our planet 
![](https://opencollective.com/static/images/makecommunity-section-illustration.png)

**Comment by piamancini** [comment]
@xdamman images are  just placeholders. 
They are not final. Delfina and Memo are working on them still.

**Comment by sbinlondon** [comment]
@piamancini @znarf What 'categories' should be used? Same as the existing ones (i.e. 'opensource', 'association', and 'climate') or some new labels (i.e. 'community' for the middle one).

**Comment by znarf** [comment]
@sbinlondon The middle one is without category.

**Comment by sbinlondon** [comment]
Update/still to do:

-  error handling
-  tablet responsiveness (mobile is done)
