### ISSUE TITLE
Implement open source/Github collective signup

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#2874]
Part of #2872

<img width="1020" alt="Screenshot 2020-02-05 at 17 22 58" src="https://user-images.githubusercontent.com/37520401/73860812-66e8ec80-483c-11ea-8995-252cc4264fa1.png">
<img width="1015" alt="Screenshot 2020-02-05 at 17 23 06" src="https://user-images.githubusercontent.com/37520401/73860814-681a1980-483c-11ea-8cf8-f95b2885a399.png">

Implement signup flow for collectives connected to open sources projects. This will require dealing with Github OAuth.

## Questions

* For the 'Request manual verification' button, what page does this go to or what does it do? @piamancini @Memo-Es

**Comment by piamancini** [comment]
@sbinlondon it should go to the create collective flow for non open source projects with the tag 'open source' and the open source collective as the suggested host

**Comment by sbinlondon** [comment]
Update:

* As discussed in the call last week, I'm making a new Github component that breaks the form out of the 'pick a repo' bit and redirects instead to the new Create Collective Flow form

**Comment by sbinlondon** [comment]
Mostly addressed in opencollective/opencollective-frontend#3530 and opencollective/opencollective-frontend#3605

Outstanding issues collected in #2945
