### ISSUE TITLE
Move charging subscriptions to 1st of every month

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#288]
Instead of keeping subscriptions on the day they are initiated, it would be better to charge everyone on 1st of the month. That way, a collective has a budget to start the month with and anyone else who joins is additional funding on top.

Currently:
- Alice donates $5/month on Jan 12
- We charge her $5 on Jan 12
- We charge her $5 on Feb 12 (and every 12th of the month until she cancels)

Proposal:
- Alice donates $5/month on Jan 12.
- We charge her $5 on Jan 12 (same as now)
- We charge her $5 on Feb 1st (and every 1st of the month until she cancels)

Note: one option is to do a pro-rated charge for current month. That's too complicated and I think we should stick to the simpler proposal above. As a comparison, [Patreon does exactly this](https://patreon.zendesk.com/hc/en-us/articles/208404313-Why-was-I-charged-immediately-Will-You-Charge-Me-Again-).

As a first step, we would only do this for new subscriptions. Leave old ones alone for now - we can run a script later and move them in the future.

**Comment by asood123** [comment]
Based on feedback from Stripe, here's how we'd have to do this:

> - Alice donates $5/month on Jan 12.
- [ ] We charge her a one-time $5 invoice on Jan 12
- [ ] We setup a subscription for her for Feb 1st and a `trial_end` date of Feb 1st. (so that subscription kicks in on Feb 1)
- [ ] Update messaging on website to let them know that next period charge will be on 1st.
- [ ] Update messaging in confirmation email to let them know about charges on 1st
- [ ] Add an FAQ to explain that this helps the collective get money in the beginning of the month and can plan head.

**Comment by xdamman** [comment]
This is really cool.

I'm just worried about the disincentive to commit to a monthly subscription in the last week of a month. It feels like paying a lot for a few days. I didn't know that this was what Patreon was doing. Maybe because it's a donation, it's not a big deal. Worth a try.

**Comment by xdamman** [comment]
Can you explain how you handle annual subscriptions in this scenario? They also wait for the 1st of the month?

Also for your example with the trial_end, did you mean that you create the subscription directly but offer a trial till end of the month?

**Comment by xdamman** [comment]
Just saw in the code that you wait for Jan 1 to process yearly donations. That further accentuates the issue if we donate in December. I'd rather treat yearly donations as one-time donations and process them directly.

**Comment by asood123** [comment]
Where did you see Jan 1? Annual donations are setup for 1st of the same
month in next year.

Have always advocated that annual donations make less sense on our platform
than one time donations. That's now a UI issue. This setup would be fine
for CHSF $100/year, for example.

**Comment by xdamman** [comment]
Gotcha, I misunderstood the code for the yearly donations. Thanks for the clarification.

The debate about one-time donations/yearly donations is another debate. CHSF makes a great use of it and I could also see BrusselsTogether offering such yearly membership in the near future.

Great job on this PR, can't wait to see this live.
