### ISSUE TITLE
Implement Accept Financial Contributions step 1: Myself

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#2881]
Part of #2872 

<img width="973" alt="Screenshot 2020-02-05 at 18 01 42" src="https://user-images.githubusercontent.com/37520401/73864366-cc8ba780-4841-11ea-9aaf-15a530a21c30.png">
<img width="977" alt="Screenshot 2020-02-05 at 18 01 50" src="https://user-images.githubusercontent.com/37520401/73864360-cbf31100-4841-11ea-802e-6933e631f19b.png">
<img width="991" alt="Screenshot 2020-02-05 at 18 02 03" src="https://user-images.githubusercontent.com/37520401/73864356-cac1e400-4841-11ea-8f90-f7905025aa0b.png">

Offer a Collective to accept financial contributions directly to the owner via Stripe or by adding a bank accout for bank transfers.

**Comment by sbinlondon** [comment]
<img width="1037" alt="Screenshot 2020-03-02 at 13 04 07" src="https://user-images.githubusercontent.com/37520401/75678967-a9a8b380-5c86-11ea-87c9-44bd94adbd78.png">
<img width="969" alt="Screenshot 2020-03-02 at 13 05 41" src="https://user-images.githubusercontent.com/37520401/75678969-aa414a00-5c86-11ea-9151-bb5367122a55.png">
<img width="960" alt="Screenshot 2020-03-02 at 13 05 54" src="https://user-images.githubusercontent.com/37520401/75678970-aa414a00-5c86-11ea-87b5-ed6985d9526c.png">

Outstanding questions:

- [ ] The 'Congratulations' page seems to be missing from the Production ready folder @Memo-Es, is there a final design for this?
- [ ] Final images still pending?

**Comment by Memo-Es** [comment]
@sbinlondon 

I'm working today on the Congratulations page, you will have by tomorrow and the create organization step plus the illustrations that are ready.

The illustrator is off until next week so the illustrations of the onboarding modal and start accepting financial contributions are going to be ready until the end of next week.

**Comment by sbinlondon** [comment]
Leaving this issue open because there is currently a bug regarding the success page opencollective/opencollective#3134
