### ISSUE TITLE
Fragile E2E test: Organization Profile, Has no filters

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2887]
```
 Running:  04-organization_v2.test.js                                                     (8 of 16)
  New organization profile
    Transactions section
      1) Has no filters (because organizations don't have expenses)

  1) New organization profile Transactions section Has no filters (because organizations don't have expenses):
     CypressError: Timed out retrying: cy.click() failed because this element is detached from the DOM.

<a data-cy="section-transactions" href="#section-transactions" class="CollectiveNavbar__MenuLink-sc-5qpl2s-1 dhLreL">Transac...</a>

Cypress requires elements be attached in the DOM to interact with them.

The previous command that ran was:

  > cy.get()
This DOM element likely became detached somewhere between the previous and current command.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element

You typically need to re-query for the element or add 'guards' which delay Cypress from running new commands.

https://on.cypress.io/element-has-detached-from-dom
```

Sample run: https://github.com/opencollective/opencollective-frontend/pull/3479/checks?check_run_id=429478867

**Comment by znarf** [comment]
Maybe related with https://github.com/opencollective/opencollective-frontend/pull/3383

@brymut what do you think?

**Comment by znarf** [comment]
Reverted the problematic PR.

**Comment by brymut** [comment]
Apologies, I haven't had a chance to look at this. Having a look today

**Comment by brymut** [comment]
Hi @znarf,
 I can't seem to recreate this but based on the recommendation [ here in the cypress docs](https://docs.cypress.io/guides/references/error-messages.html#cy-failed-because-the-element-you-are-chaining-off-of-has-become-detached-or-removed-from-the-dom) I think adding an extra assertion before the click to 'guard' against potential re-rendering in the middle of the test should address this.

**Comment by znarf** [comment]
@brymut uhm, how should that look?

**Comment by brymut** [comment]
@znarf I was initially thinking along the lines of 

`cy.getByDataCy('section-transactions').should('exist')`
      `.then(() => {`
          `cy.getByDataCy('section-transactions').click();`
        `});`    

initially but that doesn't look like it would help. I think it should be to figure out why that re-render 
 in the middle of the test happens?

@Betree , any ideas?
