### ISSUE TITLE
Homepage: update image for social media sharing

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2894]
We've got an awesome new homepage but when you share it on social media it's still pulling through the old images. I think it's pulling the wrong text as well. I think we should share the main illustration along with "Make your community sustainable. Collect and spend money transparently."

**Comment by Betree** [comment]
## Current state

![Screenshot_2020-02-18 Programme de débug du partage - Facebook for Developers](https://user-images.githubusercontent.com/1556356/74727066-de594b80-5240-11ea-8771-281019bd7da4.png)

## New image

Image resolution for the share should be: `1200x630`. If we want the main page image in there, we will have to crop it like that (you can download & use the this version):

![makecommunity-section-illustration](https://user-images.githubusercontent.com/1556356/74727244-2bd5b880-5241-11ea-9e0f-d157c193f7cc.png)

## New description

As per @alanna's description above:
> Make your community sustainable. Collect and spend money transparently.

Ideally we want the strings to be internationalized (translations for them already exist).

**Comment by piamancini** [comment]
How do we change it?

**Comment by Betree** [comment]
It needs to happen in the code. I can do it if there's an agreement on the image above, but it's also a good first issue for any contributor that wants to participate.

**Comment by piamancini** [comment]
I think it's too important brand-wise and would love to have it done. The top image is a good choice.

**Comment by Betree** [comment]
@piamancini should this be the new default image, aka the one that will appear on shares by default (no matter if the page shared is the homepage or the pricing page)?

**Comment by olawanlejoel** [comment]
Seems this has still not been fixed yet

**Comment by znarf** [comment]
@olawanlejoel There is a PR open https://github.com/opencollective/opencollective-frontend/pull/3563
