### ISSUE TITLE
Fix smooth-scroll on the collective and event page

### ISSUE THREAD

**Issue by JoyLubega** [opencollective/opencollective#2898]
**Describe the bug**
Smooth scrolling is not active on the collective and event page 

 https://opencollective-frontend-itruzqydxe.now.sh/backyourstack

**Expected behavior**
Scrolling should be smooth from one tab to another

**Comment by znarf** [comment]
I quickly attempted to fix it https://github.com/opencollective/opencollective-frontend/pull/3499 but this didn't work (see comments) so we'll need to think of another approach.

**Comment by JoyLubega** [comment]
@Betree  @znarf  how is class added on the this html tag, i think that logic can help me add style to the html tag

![Screen Shot 2020-02-11 at 3 08 56 PM](https://user-images.githubusercontent.com/29824008/74235726-b87ff400-4ce0-11ea-8f28-075fbea79267.png)

**Comment by Betree** [comment]
@JoyLubega it's added by the global css import in https://github.com/opencollective/opencollective-frontend/blob/eda9b0c2eeb1e87874764f851bf32d3a9b1f916a/pages/_app.js#L26

Not the way to go for this fix.
