### ISSUE TITLE
update "your collective is on its way" email

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#290]
Now collectives are live by default (except tiers). We need to update the text of the email. We currently say: 

_Thanks for signing up your GitHub repository: hledger. We are reviewing new requests as fast as we can.
While you wait, check out other open source collectives and see how they are spending the money they have raised.
Stay tuned for updates._

**Suggestion**: 

Your collective is now live (link to collective) and under review. While you wait for approval to start receiving donations, here's a quick guide to make the most out of it.

1. Make your collective your own. Login and hover over elements to edit them.

2. Add backers/sponsors to Github/Website. We'll make a PR to your README to add backers & sponsors. Instructions to add your backers to a website here (link).

3. Start tracking expenses. Submit expenses so others can see your costs. It helps to raise money.

4. Spread the word: if you have a twitter account, you can connect it to your collective and automatically thank your backers. See here how to do it. (link)

Find us on slack.opencollective.com or support@opencollective.com

**Comment by asood123** [comment]
@piamancini what are the links that you share in #2 and #4 above.

**Comment by asood123** [comment]
Found link for #4. Here's PR in progress: https://github.com/OpenCollective/opencollective-api/pull/741

**Comment by piamancini** [comment]
@asood123 link for #2 is https://github.com/OpenCollective/OpenCollective/wiki/Website-banner
