### ISSUE TITLE
Fix textures

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#2902]
Some of the textures look misplaced and low quality on mobile
<img width="484" alt="Screen Shot on 2020-02-10 at 09-56-09" src="https://user-images.githubusercontent.com/49539954/74169598-2a791000-4bf1-11ea-9d89-2a34de0c878b.png">

**Comment by Betree** [comment]
Closing in favor of https://github.com/opencollective/opencollective/issues/3321 as this section is going to change
