### ISSUE TITLE
Homepage: "learn more" links should open a new tab / Redirect links under "Who is using Open Collective?"

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#2903]
I think the "Learn more..." links should open a new tab
<img width="743" alt="Screen Shot on 2020-02-10 at 10-59-41" src="https://user-images.githubusercontent.com/49539954/74171693-90b36200-4bf4-11ea-8fe9-a4e11f0b1c2b.png">

These links need to be updated, links are in the [homepage copy document](https://docs.google.com/document/d/1i1eP5PLfM2Tshp6Oiqnpt8lXAazJ-twFj8iQQg2SYWI/edit?usp=sharing)
<img width="1372" alt="Screen Shot on 2020-02-10 at 11-02-11" src="https://user-images.githubusercontent.com/49539954/74171848-d3753a00-4bf4-11ea-8256-48699477d0b5.png">

**Comment by AdetunjiTejumade** [comment]
Can i work on this?

**Comment by znarf** [comment]
@AdetunjiTejumade you can try, but there is no bounty on it!

**Comment by KarenEfereyan** [comment]
Can I try to solve this as my first open source contribution?
