### ISSUE TITLE
Gift card contribution fails (stripe PaymentIntent error)

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2909]
**Describe the bug**
_Opening an issue to track the bug reported in https://opencollective.freshdesk.com/a/tickets/4230 and https://opencollective.freshdesk.com/a/tickets/4345._

Some users who try to contribute with Triplebyte's gift cards see this message:

![image](https://user-images.githubusercontent.com/1556356/74414968-bfbf1300-4e42-11ea-94ff-e472747292ef.png)

Unfortunately we didn't collect enough data to clearly identify the error yet, https://github.com/opencollective/opencollective-api/pull/3354 should help with that.

In the mean time, this is what we know:
- Only happens with Triplebyte's gift cards
- Triplebyte changed the CC used for its gift cards a month ago
- Only happens with collectives hosted by [WWC](https://opencollective.com/wwcodeinc):
  - https://opencollective.com/wwcodesf
  - https://opencollective.com/wwcode
  - https://opencollective.com/wwcodeboston
- First failed order for Triplebyte Gift cards <> WWC was on `2020-01-27 23:25:18`. The one before was successfully paid on `2020-01-25 21:16:41`. So it broke somewhere between the 25 and 27 of January. Nothing new was deployed on this period.

**Comment by znarf** [comment]
Also landed a potential fix there: https://github.com/opencollective/opencollective-api/pull/3362

Not sure if it's better, I investigated a bit and we're seeing the error in the daily subscriptions, don't know if it's new.

**Comment by Betree** [comment]
opencollective/opencollective-api#3362 was deployed on 13th February but we had new occurrences since. For example on 15th: https://my.papertrailapp.com/groups/1997763/events?focus=1165563924424749060&selected=1165563924424749060

It seems that we miss the PM info for the host, but I'm not sure why logger didn't properly log the object:

![image](https://user-images.githubusercontent.com/1556356/74638547-64f02900-516c-11ea-9605-1e5d8fc0fdad.png)

**Comment by znarf** [comment]
Yes, it's what I saw in the daily subscriptions, it's related but it's not our Gift Card issue right?

Looks like `logger` doesn't stringify objects, we should use console.log or stringify manually.

**Comment by Betree** [comment]
opencollective/opencollective-api#3362 seems have improved the situation as there's no order with status=ERROR matching this error since _2020-02-12 17:55:02_ for Triplebyte's gift cards :tada: I'll contact the users to ask them to try again.

The entries that we've see in the logs since then are **not** gift cards and all have in common that the orders previously had the `requires_source_action` status, which [according to the docs](https://stripe.com/docs/payments/intents) means: 
> If the setup requires additional actions, such as authenticating with 3D Secure , the SetupIntent has a status of requires_action. 

My current assumption for it is that if people don't confirm their 3D secure or ignore it then the next attempts will consider that there is no payment method attached to this PaymentIntent.

Anyway it's a different issue and the one initially reported here seems to be resolved, I'll re-open if necessary.

**Comment by znarf** [comment]
Interesting, we need to double check our behavior when adding a payment method and being challenged by 3d secure.

**Comment by Betree** [comment]
Got a confirmation from the two users who reported this that they were able to contribute this time :tada:
