### ISSUE TITLE
Host Settings and Plans: Changes and Updates

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2912]
We need to update some aspects of the paid plan feature and the Host settings. 

- [ ] Move Bank Transfers to another place in the settings
- [x] Activate Bank Transfers by default up $1000
- [ ] Remove Activate / Deactivate as Host from Advanced to new fiscal hosting setting
- [x] update in the CF: grey out bank transfer after $1000 / Same for PayPal 
- [ ] Move Stripe outside of connected accounts 
- [x] Manual Payments should be Bank Transfers and have the same limitation as added funds 

what are we telling users when they try to apply to host with max capacity? 
Copy: This host has reached a plan limit. They must upgrade to a new plan to accept new collectives.

**Comment by alanna** [comment]
Might want to add these detail to the main host settings update issue: #2665

**Comment by znarf** [comment]
The unchecked items are tracked in  https://github.com/opencollective/opencollective/issues/2665
