### ISSUE TITLE
Enable "Updates" for organizations

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2914]
In the same way that we can have "Conversations" on the profile of an organization, it would be great if we could also have "Updates". 

As a side note, it would be great if the profile of an organization could act as an open collective (which it already does behind the scene). This would remove the need to create a default root collective for the host (e.g. https://opencollective.com/foundation-collective, https://opencollective.com/allforclimate-collective, https://opencollective.com/uk-collective, https://opencollective.com/opencollectiveparis, ...)

**Comment by piamancini** [comment]
Yes, this is something we need to do better.

**Comment by alanna** [comment]
Related: #2314
