### ISSUE TITLE
Card auto fill broken on Chrome iOS

### ISSUE THREAD

**Issue by chmac** [opencollective/opencollective#2915]
**Describe the bug**

**To Reproduce**
1. Go to https://opencollective.com/generous-community
2. Click on pay
3. Scroll down to card details 

Pressing your card information doesn’t result in entering data into the form, there’s no response.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS 13.3.11
 - Browser Chrome
 - Version 80.0.398795

**Additional context**

You need cards saved in chrome to see this feature

**Comment by znarf** [comment]
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the Open Source Festival event. If not completed there, it will be later open to everyone.

**Comment by znarf** [comment]
It's now open to everyone.

**Comment by leonardohof** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to https://opencollective.com/generous-community
> 2. Click on pay
> 3. Scroll down to card details
> 
> Pressing your card information doesn’t result in entering data into the form, there’s no response.
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Smartphone (please complete the following information):**
> 
> * Device: iPhone XS
> * OS: iOS 13.3.11
> * Browser Chrome
> * Version 80.0.398795
> 
> **Additional context**
> 
> You need cards saved in chrome to see this feature

@chmac Could you add a screenshot?

**Comment by chmac** [comment]
@leonardohof Unfortunately I don't have credit cards in chrome on my iPhone. It was a friend trying to support our campaign at an event who told me about it, without any other cards on hand, there was no way for them to support the campaign. I'm asking if they can forward a screenshot, but I guess it's the absence of something happening rather than the presence of a problem, so it might be hard to get a screenshot which captures this essence. It's hard to take a picture of something that doesn't exist, etc...

**Comment by brymut** [comment]
Hi @znarf @chmac , looks like this isn't straightforward to reproduce. I tried with a card I had saved to the page mentioned ( https://opencollective.com/generous-community ) with my phone on:
 - Device: iPhone 8 (not same phone as mentioned)
 - OS: iOS 13.3.1
 - Browser Chrome
 - Version 80.0.3987.95
which in my opinion is quite similar to the device browser described and the autofill worked successfully as shown in the screengrab below. 
![gifofiphone8try](https://github.com/brymut/github-gifs/blob/master/opencollective:issues:2915/autocomplete-1.gif?raw=true)

**Comment by chmac** [comment]
@brymut Thanks for investigating this so thoroughly. I'm gonna close this issue now on the basis that it was probably a one off, or at least hard to reproduce, issue. Impressed with the depth of investigation and feedback here. Thanks. ❤️
