### ISSUE TITLE
Re-design comment actions

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2916]
# Problem

For comment actions (Edit, Remove...etc) we currently use buttons. This creates some problems:

- On mobile, we show just the icons without labels which is not a good practice for accessibility: icons interpretation may differ based on culture and personal experience. It's better to not use icons alone. See https://ux.stackexchange.com/a/1803 for the data behind this claim.
![image](https://user-images.githubusercontent.com/1556356/71083359-1ede0f80-2193-11ea-977a-b54f953f4ae5.png)

- This pattern take a lot of place and **we plan to add at least four new actions on top of it**: Reply, Report (#2694), Hide (#2740) and Share. Having 6 buttons in there is not manageable and will never work on mobile. 
![image](https://user-images.githubusercontent.com/1556356/71083018-6021ef80-2192-11ea-8016-1a43b4e083f5.png)

# Suggestions

Mimic what Github, Discourse, Facebook and actually most platforms with threaded conversations are doing and have a dropdown menu:

![image](https://user-images.githubusercontent.com/1556356/71083820-34a00480-2194-11ea-9339-4901eea5ff78.png)

![image](https://user-images.githubusercontent.com/1556356/74658141-f1611280-5191-11ea-91ce-875c929e19c6.png)

![image](https://user-images.githubusercontent.com/1556356/74658219-16558580-5192-11ea-8178-404b57d4a7a9.png)

**Comment by raulgrafico** [comment]
Link to the Figma file @Betree : 
https://www.figma.com/file/GF1gQ7fWNfaOAFNwuLeAUl/OC.com-Hot-Fixes?node-id=1088%3A63

**Comment by Betree** [comment]
Fantastic, thanks @raulgrafico! 

## Design

From [Figma](https://www.figma.com/file/GF1gQ7fWNfaOAFNwuLeAUl/%5BOC.com%5D-Hot-Fixes?node-id=1088%3A63):

**Button**

![image](https://user-images.githubusercontent.com/1556356/77642591-32510180-6f5e-11ea-994d-120cc90c9135.png)

**Popup**

![image](https://user-images.githubusercontent.com/1556356/77642609-3aa93c80-6f5e-11ea-85a4-84604b0ed984.png)

## Implementation

Ideally we should go with a pure CSS solution.

If the positioning of the menu is a problem we should, according to https://github.com/opencollective/opencollective/issues/2745, use https://github.com/popperjs/react-popper.

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by snitin315** [comment]
@Betree can I take this up?

**Comment by Betree** [comment]
Hi @snitin315, I'm sorry but this bounty came out of a proposal from @flickz so we'd like to keep it for him in a first time. If not completed during the given time frame, we'll open to everyone.

**Comment by Betree** [comment]
:trophy: This issue has been completed by @flickz  

To claim the **$200** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
