### ISSUE TITLE
Documentation: images replaced by random ones from other pages

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2917]
**Describe the bug**
@contraexemplo and I have noticed a bug on Gitbook that swipe images on pages with random images from other pages. We've both spent time fixing them last week, only to notice new broken ones this morning.

Example: In https://github.com/opencollective/documentation/commit/483ac7ee4d0fe6c8d6801558166015b075e38729#diff-89537b8726a92a41faa90b620f9fd5ec I fixed the images for conversations, core contributors, subcollectives, tax and moderation pages. After saving the result looked ok. Then now images are broken.

Another strange example: in https://github.com/opencollective/documentation/commit/afc29baa908aefcb99949705c1917fde5533607a the image for `fiscal-hosts/local-tax.md` got replaced by `.gitbook/assets/image (20).png` but if you browse the repository at this point the image doesn't exist: https://github.com/opencollective/documentation/tree/afc29baa908aefcb99949705c1917fde5533607a/.gitbook/assets

**Comment by piamancini** [comment]
agh this is annoying. Still no word from gitbook?

**Comment by Betree** [comment]
@contraexemplo contacted them but I don't think they replied yet

**Comment by contraexemplo** [comment]
@Betree no word yet? 😞

**Comment by Betree** [comment]
@contraexemplo I misunderstood your previous comment and thought you were sending them an email. Sorry about that! I'll contact them now.

**Comment by contraexemplo** [comment]
@Betree Oh, that's ok! No worries.

**Comment by Betree** [comment]
Got a reply from them today:

> Hi Benjamin,
> 
> Sorry for the late reply.
> I fix for the export process was shipped last week.
> Could you try again and let me know how it goes?
> 
> Kind regards,
> 
> Johan
> Lead Developer

So it should be fixed now. Let's remain vigilant and re-open if this happens again.

**Comment by contraexemplo** [comment]
Fantastic. Thank you, @Betree!
