### ISSUE TITLE
Wrong regex for linkify on conversations

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2918]
When writing "(e.g. https://opencollective.com/fridaysforfuture-eu-socialmedia)", the closing parenthesis should not be included in the link.

![](https://d.pr/free/i/3jp4wI+)

See https://opencollective.com/fridays-for-future-europe/conversations/more-explicit-collective-name-04qjob68

**Comment by Betree** [comment]
Having parenthesis in the URL is not wrong (for example https://opencollective.com/file-(1)-valid.js is valid) but it's indeed a bad experience to have in included when it's a closing parenthesis and it's very common to do that. Here's Github behavior:

- Include in URL by default: https://opencollective.com/name-(1)
- Don't include if inside of a parenthesis: (ie. https://opencollective.com/name-(1))

So we need the regex to be aware of whether it's inside parenthesis or not.

**Comment by znarf** [comment]
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the Open Source Festival event. If not completed there, it will be later open to everyone.

**Comment by prondubuisi** [comment]
Hello @znarf do I need to claim this bug before I can work on it,?

**Comment by znarf** [comment]
@prondubuisi I assigned you!

**Comment by prondubuisi** [comment]
@znarf Please can I get a link to the file where this regex resides? also how can I experience this bug first hand? I already have the frontend for opencollective set up
![Osca](https://user-images.githubusercontent.com/22311928/75027925-a734a580-549f-11ea-8adc-e0174d710321.png)

**Comment by znarf** [comment]
Sign In, Create a collective, Then post a message in the conversations.

The regex? Not sure, I'll share it once I find it.

**Comment by joshikeno** [comment]
@prondubuisi 

To experience the bug follow referenced instructions.
> Having parenthesis in the URL is not wrong (for example https://opencollective.com/file-(1)-valid.js is valid) but it's indeed a bad experience to have in included when it's a closing parenthesis and it's very common to do that. Here's Github behavior:
> 
> * Include in URL by default: https://opencollective.com/name-(1)
> * Don't include if inside of a parenthesis: (ie. https://opencollective.com/name-(1))
> 
> So we need the regex to be aware of whether it's inside parenthesis or not.

Checkout this file: 
https://github.com/opencollective/opencollective-frontend/blob/a8d865ade358129f4290269b56a46718a9a42afc/components/RichTextEditor.js#L267

**Comment by prondubuisi** [comment]
Hello @znarf @joshikeno  This is what I have done so far 
![First Collect](https://user-images.githubusercontent.com/22311928/75129054-8c447a00-56c7-11ea-970b-2b5b1e28821a.png)

Select Open Source Project, and try a URL with parenthesis
![Collect 2](https://user-images.githubusercontent.com/22311928/75129086-b007c000-56c7-11ea-9282-f60dd33c0bbd.png)

I think this is the expected error that I should work on, ensuring that parenthesis in urls are seen as valid one they don't exist inside another parenthesis right? 
![Collective 3](https://user-images.githubusercontent.com/22311928/75129131-e3e2e580-56c7-11ea-9008-2472a8398960.png)

I have made changes to the regex here https://github.com/opencollective/opencollective-frontend/blob/a8d865ade358129f4290269b56a46718a9a42afc/components/RichTextEditor.js#L267

and my changes don't seem to affect the page or the error message, I hope the bug I just replicated is that mentioned in this issue? Also is there anything I need to do to make changes reflect?

**Comment by Betree** [comment]
@prondubuisi the paths you're testing are not supposed to be affected by this issue. The affected component is the `RichTextEditor`, to try it you need to go to the **conversations** page. After creating a collective, go to `/{collectiveSlug}/conversations/new`, the component that needs a fix is the main text field for the conversation body.

**Comment by znarf** [comment]
@prondubuisi any progress?

**Comment by prondubuisi** [comment]
Hello @znarf not really I am still trying to figure out what part of the function to apply. The fix. I am a little slow because I am having exams. I should be able to send in A PR by weekend. Thanks

**Comment by bolariin** [comment]
I was wondering if I could resolve this issue

**Comment by Betree** [comment]
Hi @bolariin sure, thanks for joining in! I suspect that the complexity for this one may be higher than what we estimated, feel free to post updates and seek help if you need

**Comment by Betree** [comment]
Upgrading the bounty to $200 because the task ended up being more complex than expected

**Comment by Betree** [comment]
:trophy: This issue has been completed by @bolariin  

To claim the **$200** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
