### ISSUE TITLE
Style update for the Open Collective platform UI

### ISSUE THREAD

**Issue by cuiki** [opencollective/opencollective#2920]
## Problem
Now that some nice features have been rolled out such as the new Collective page, Conversations and the new Homepage with the awesome illustrations by Delfina, the need for an update to the UI's system is starting to show. Since these new features were implemented some important questions and on-the-fly solutions were made which makes it difficult to consistently grow the platform.

For example, in the conversations page and the 'submit expense' page we have an issue on the placement and logic of the CTA's (https://tafka.d.pr/wY0TyH and https://tafka.d.pr/WrNLIS).

On another front, the way the collective's page navigation behaves when the page is scrolled gets users confused on the navigation hierarchy and relationship between the collective and Open Collective, specially when they are landing on a collective's page directly (https://tafka.d.pr/OYTDnT).

In short, there a bunch of smaller issues that seem super contextual but are in fact something more global that will continue to impact the platform's design.

## Purpose
To revamp Open Collective's User Interface style and layout (**based on the current structures**) to a cohesively branded and comprehensive style that now expands to modularized page templates that we can reuse.

I started an experimental project to update some of the button colors in our design system based on a color palette extracted from Delfina's illustrations. Color changes aren't that apparent at first but they play better with the extracted color palette. I also added a few styles to account for different levels of users (i.e. regular users vs collective admins with inline editing capabilities). You can see it here: https://www.figma.com/file/N4Xbl652BhzOutXmzhcrLGch/DS-06-Atoms?node-id=1621%3A4356

There are some other ideas I'd like to discuss like the use of a dark-colored primary toolbar when viewing a collective page, like in here https://tafka.d.pr/cRoUQq, to make obvious the separation of context between a Collective's nav and OC. So I'd like to open up the conversation for everyone and see what you guys think of this and if there are other UI issues you'd like to tackle.

## Owner
@cuiki 

*Note: Project owner responsibilities include coordinating all the different people that need to contribute to the project, defining specs and goals, communicating project progress, being the point person for decisions, QA, documentation, and a plan for ongoing maintenance. If the project owner can't continue, they need to hand the role over to another person explicitly.*

## Prioritization

- Does this serve our mission?
Yes, a comprehensive and branded UI style should directly increase the number of new collectives being created and the general participation that we want from users in the different contexts of the Open Collective platform.

- Will this help to make us financially sustainable within a year?
Yes. Part of this project's goals is to create page templates for our platform. A good example is to figure out the CTA's placements in the conversations view.

- Is it feasible to build and maintain with our team and runway?
From a design perspective yes. I'm planning to tackle this project asynchronously from the production track. (expense flow, create collective flow, etc.). I'd like to have @Betree work with me a bit on defining the engineering approach and what things to consider in order to help the front-end team implement this in a progressive but consistent manner.

- Can this make us move faster?

- Does this increase quality and not technical debt?

- Will this bring us more Collective and financial contributors?

- Is this already solved elsewhere or is it our unique contribution?

## Roadmap & Timeframe
(Key milestones or phases and estimated delivery dates, including specs, design, feature development, feedback, marketing/comms, and documentation)

## Success metrics
(What we will judge outcomes of the project by)

**Comment by Betree** [comment]
Hi @cuiki, I think you forgot to add a description for this one, it has the default template

**Comment by Betree** [comment]
I like the fact that you're trying to address these small issues in a systemic way, I agree with your conclusion that they are correlated. 

From the engineering's perspective the complexity is ok. The good thing about the design system that was introduced in the code is that doing these kind of changes platform-wise is now very easy. To [update the button colors](https://github.com/opencollective/opencollective-frontend/pull/3481) for example there's in theory only one file to change.

Now regarding the feedback on the changes proposed:

**New buttons**
The new buttons are great, they definitely look more "modern" than the current ones.

**New navbar color**
I agree that a distinction between OC's navbar and collective navbar would be a good enhancement, using colors to achieve that seems reasonable. 

Yet I'm still not convinced by using black for the navbar: most of our pages are overall very white and this big black box at the top catches all my attention. We want this navbar to be as discrete as possible so that users with rather focus on the collective info.

**Comment by cuiki** [comment]
> Yet I'm still not convinced by using black for the navbar: most of our pages are overall very white and this big black box at the top catches all my attention. We want this navbar to be as discrete as possible so that users with rather focus on the collective info.

Yeah, this is something I've battled with in the last few days. Since part of the approach is to experiment with this I'll be presenting a few alternatives on DemoFridays so the team can weigh in and collectively select a proposal.

**Comment by piamancini** [comment]
@cuiki Thank you for taking this on. I agree we need to be coherent and it makes sense to approach this systemically, specially as we move the page to a more synced look and feel with the homepage as anchor. 

I also agree that the black navbar is difficult. @Memo-Es  proposed a black and white empty collective page (before there's any transaction or update, etc) and we decided to move away from it towards more color accents and less black heavy.

**Comment by Memo-Es** [comment]
All of the issues presented here have been addressed in the new Collective page design update 

CC @Betree
