### ISSUE TITLE
ExpenseFlow: PayoutMethod's "complentary info" field behavior

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2924]
In the new expense flow, there is a `Complementary info` field in the **`2.  Payee & payout information`** step. I'm trying to figure out the exact behavior for this field:
1. **Is it linked to the expense?**
  In this case the information will not be saved for future expenses.

2. **Or is it linked to the payout method?**
  In this case the information will be saved for future expenses. It also means that editing the info for this payout method on expense **A** will also edit it for expense **B** if A and B share the same payout method.

@Memo-Es suggested a third option: that the info is linked to a pair of [collective+payout method]:

> I believe we are connecting that info to the Collective you are submitting your expense to, which means that if you submit an expense on a different Collective you'll need to fill those fields again.

Because this last option has a higher technical cost (with it we won't be able to store the info in the expense nor in the payout method) I'd like to discuss the specifics before starting the implementation.

**Questions for @piamancini @alanna @opencollective/design**

- Which one of the options above (if any) is correct?
- Can you provide some examples for the data that we expect users to put in there?

---

![image](https://user-images.githubusercontent.com/1556356/74855803-7179aa80-5341-11ea-9387-ac6d42008c90.png)

**Comment by alanna** [comment]
This field was not in the original spec so I'm having trouble understanding what it's for. 

Is this where users will put extra info they need to show on their invoices, such as a VAT number? Is this the field we need for privates notes that go along with a particular expense? Or is this notes about the payout method, such as company name?

Regardless, the phrase "complementary info" does not make sense in English and this will be confusing to users. We should be clear about what this field is for and name it accordingly.

**Comment by piamancini** [comment]
@alanna Is a field we need for privates notes that go along with a particular expense - For example when Ben adds monthly salary and includes xx days off for reference. 

@Betree I would title it:  'Additional Information (optional)' it is linked to the expense itself - it shouldn't be saved for the future.

**Comment by Betree** [comment]
> Is a field we need for privates notes that go along with a particular expense - For example when Ben adds monthly salary and includes xx days off for reference.

@piamancini then I don't understand what's the difference with the **`Add notes (Optional)`** field on the summary step:

![image](https://user-images.githubusercontent.com/1556356/74937331-1e106680-53ec-11ea-8443-d677ebb799bd.png)

**Comment by Betree** [comment]
Decision from the meeting:

**The goal for this field is to put information that you want to see on the invoice.** So:

- Rename field to `Additional invoice information`
- Field will not be displayed if you pick the "Receipt" expense type
- Field will not be saved for future expenses
- Use the following placeholder:
> Tax ID, VAT number...etc This information will be printed on your invoice.
- Switch the fields to make it clear that the info is linked to your profile, not to the payout method
![image](https://user-images.githubusercontent.com/1556356/74946446-9a5d7680-53f9-11ea-9021-9767c340d1dd.png)
