### ISSUE TITLE
Received emails meant for the fiscal host

### ISSUE THREAD

**Issue by chmac** [opencollective/opencollective#2925]
URL: https://opencollective.com/generous-community
Logged in as (username or profile URL): @chmac
Error message if any: 
Expected result: 
Browser:

I got this email:

<img width="586" alt="Screenshot 2020-02-19 at 18 25 09" src="https://user-images.githubusercontent.com/690997/74858388-87896a00-5345-11ea-97cb-ccdec0178cab.png">

But this is meant to go to the fiscal host to confirm that the payment has been received by the bank. I received the same email 6 times for 6 donations. I'm pretty sure all the donations were made around the same time Saturday night, we were hosting an event. But all the emails showed up today at 6:12 CET (Berlin).

**Comment by znarf** [comment]
I merged and deployed a fix yesterday night. https://github.com/opencollective/opencollective-api/pull/3383 Should be fixed!
