### ISSUE TITLE
Some names showing as "null" in HelloWorks

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2926]
This is for the tax form system. In HelloWorks, most of the time it correctly shows the user's name on the list of sent forms. However, once in a while it shows "null" instead. This makes it hard to track down tax forms if there's an issue. The names are showing up correctly on the actual forms, just not in the list of sent files on the HelloWorks dashboard.

I originally thought this was a HelloWorks issue and they looked into it:

> After extensive investigation from our engineering team, the null null value is what is being passed into the create instance API call on your side. This is something that cannot be adjusted on our end and our team recommends that you check with your team to see how those values are being captured and passed through. 

Here's how it looks on the dashboard:

<img width="999" alt="Screen Shot 2020-02-20 at 11 10 24 AM" src="https://user-images.githubusercontent.com/5498878/74881189-c2d17a80-53d1-11ea-83a8-ee0f8195e88e.png">

**Comment by znarf** [comment]
It's relying on deprecated columns that are `null` for the most recent accounts. Should be an easy fix.
