### ISSUE TITLE
Create expense flow: clarify what info will be shared with collective/host admins

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2927]
## User story 
- As a user submitting an expense on Open Collective, I want to know exactly what info of my personal profile will be shared with the third-parties I'm interacting with.
- As a GDPR regulator, I need to make sure that the platform is properly informing the users when their data is shared with third parties.

When you submit an expense to the collective, the following information from your profile are shared:
- Email: accessible to the collective and host admins
- Address: accessible to the collective and host admins
- Payout method (paypal email): accessible to collective and host admins (may change with https://github.com/opencollective/opencollective/issues/2848)

## Best solution for this problem

1. In the dismissable info box at the top we already talk about personal info in there so it's just a matter of completing the sentence
2. In the FAQ it's just a matter of completing the `Is my private data made public?` entry 

![image](https://user-images.githubusercontent.com/1556356/74922182-25754700-53cf-11ea-94a1-4172cbef0390.png)

**Messages proposals**

1. For the blue info message (bold=changes)

> Request payment from ${collective} for work you’ve done or to be reimbursed for purchases. Expenses will be processed for payment once approved by a Collective admin. Only the amount and description are public in the Collective’s transparent budget— attachments, **payout** details, **emails and addresses are only shared with the admins**.

2. For the FAQ: `Is my private data made public?` (bold=changes)

> No. Only the expense amount and description are public. Attachments, payment info, **emails and addresses** are only visible to you and the admins.

---

Assigning @piamancini as the decision maker on this one

**Comment by piamancini** [comment]
Go ahead with the changes. Thank you Ben. Good catch

**Comment by Betree** [comment]
Alright thanks!
