### ISSUE TITLE
Move away from @rebass/grid

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2929]
The `@rebass/grid` package that we're using has been discontinued and has not been updated for the last 6 months (see https://github.com/rebassjs/grid).

Repo maintainer(s) recommend to switch to https://rebassjs.org/reflexbox.

**I see two ways to move forward with this issue:**

- Re-implement the components internally. This would be very fast, `@rebass/grid` relies on `styled-system` so in the end [the full lib is around 39 lines of code](https://github.com/rebassjs/grid/blob/master/src/index.js).

- Or we move to https://rebassjs.org/reflexbox. I have two concerns with this option:
   1. `styled-components` is not a first class citizen of the library, it's main target is `emotion`. All our imports would have to look like this `import { Box } from 'rebass/styled-components'`.

   2. The library adds a ton of primitives like `Link`, `Button`, `Heading`... Because we already rely on our own implementation for all these, we would have to either prevent their usage (bad experience for contributors) or migrate our code to them (important cost, small benefit).

I therefore tend to prefer the first option, but I want to open the space for us to discuss that and other potential alternatives.

---

To @opencollective/core-developers:
- What's your favorite option?
- Do you see any other alternatives that would be worth trying?

**Comment by kewitz** [comment]
Interesting, I think the ideal would keep up with `reflexbox`.
I think we can use just the `reflexbox` package without having the other ton of primitives:
```js
import { Flex, Box } from 'reflexbox/styled-components'
```
I'm just not sure how Theming will play with all this.
More info about the package here: https://github.com/rebassjs/rebass/tree/master/packages/reflexbox

**Comment by Betree** [comment]
@kewitz Ah yes, good catch! That eliminates one of the two concerns.

Still I wonder what would be the advantage of:

```jsx
import { Flex, Box } from 'reflexbox/styled-components'
```

Versus

```jsx
import { Flex, Box } from './FlexBox'
```

With the second, you can easily look at the code to understand what happen, no need for external docs. These component are so simple, I don't see the value of externalizing them.

**Comment by kewitz** [comment]
Yep, I agree.

**Comment by sbinlondon** [comment]
+1 for a code heist, then we can even minimise the number of components we have - i.e. you told me `Container` was just `Box` with some add ons. So we could just make our new `Box` fit every use case we need, right?

**Comment by kewitz** [comment]
I'm sorry, I didn't mean to heist! 😅
Make sure to include `rebass/grid` license in the header of our `./FlexBox.ts`!

**Comment by Betree** [comment]
> +1 for a code heist, then we can even minimise the number of components we have - i.e. you told me `Container` was just `Box` with some add ons. So we could just make our new `Box` fit every use case we need, right?

We could but I think having a separation has some benefits, though we should document it properly.

`Box` should be as simple as possible and **only about layout** (size, space, margins...etc).
`Container` is also about **styling**: box-shadows, border colors, background...etc

While it's true that using only `Container` could work, it would also have a performance impact.
