### ISSUE TITLE
Request money

### ISSUE THREAD

**Issue by erickrico** [opencollective/opencollective#293]
Hey i changed the wording since  request money seems cold, improved a bit on the creation and share of the "campaign link", and added a creation button from the owner view

## Owner View

![screen shot 2017-01-17 at 5 30 48 pm](https://cloud.githubusercontent.com/assets/18429104/22072771/0511b262-dd69-11e6-8456-c8d9cd3365b4.png)

![screen shot 2017-01-18 at 10 42 03 am](https://cloud.githubusercontent.com/assets/18429104/22073374/ca0e1a1e-dd6a-11e6-883f-0e3b03fd0ed8.png)

**Comment by erickrico** [comment]
@xdamman

**Comment by asood123** [comment]
@erickrico I like the design of the second one. 

On the first one, it would be better to show this link for everyone. I might be helping a collective (and not be an admin of that collective) and want to generate this link, for example.

Any other ideas on how to show this prominently on the main page?

**Comment by piamancini** [comment]
this was done. but now disappeared. Adding it to #502 and #478
