### ISSUE TITLE
Tiers: properly support float amounts

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2934]
Tiers with float amounts are not properly supported. There are a bunch of small steps that we need to take to unlock that:

- [ ] When editing a tier (`/{slug}/edit/tiers`), the `Amount` fields **already supports** float amounts. We should do the same for the following fields:
  - [ ] Minimum amount
  - [ ] Default amount
  - [ ] Suggested amounts
- [ ] Make sure that these changes work with the contribution flow
- [ ] On the tier cards, don't round amounts if they have some decimals:

![image](https://user-images.githubusercontent.com/1556356/75426050-1c8ef300-5944-11ea-8ac3-caafc1867e01.png)

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

---

Please follow our [code guidelines](https://docs.opencollective.com/help/developers/best-practices-and-code-guidelines), especially:

* The strings must be internationalized. See [/help/developers/translations](https://docs.opencollective.com/help/developers/translations)
* Whenever it's possible we must use `styled-components` to write styles. See [OC Styleguide](https://opencollective-styleguide.now.sh/)
* We're getting rid of `Bootstrap`. Please don't use it for new developments.
* Tests written with Cypress must follow our [good practices](https://docs.opencollective.com/help/developers/testing-with-cypress) conventions.

**Comment by brymut** [comment]
Hi @joshikeno, noticed that you're recently assigned on #2730 , would you mind if I had a go at this?

**Comment by joshikeno** [comment]
@brymut totally, have a go.

**Comment by Betree** [comment]
:trophy: This issue has been completed by @brymut. Congrats, it was a very good work :tada:  

To claim the **$200** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
