### ISSUE TITLE
Naming GraphQL inputs

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2935]
I would like to introduce the following rules for naming inputs:

- All inputs should finish by the suffix `Input`
- Inputs to create and update a given object should simply be named like the object: `CollectiveInput`.
- If they need to be more specific, they should be suffixed with `CreateInput` or `UpdateInput`. ie: `ExpenseCreateInput`, `ExpenseUpdateInput`
- Inputs to reference an object should have a consistent naming: `CollectiveReferenceInput` or `CollectiveFetchInput` (to be defined)
- Inputs to sort a collection should be suffixed by `OrderInput`, ie: `ChronologicalOrderInput`

Feedback welcome: @Betree, @kewitz, @sbinlondon

**Comment by Betree** [comment]
Agree with the full proposal, especially `{Object}ReferenceInput`. We're probably going to have a bunch of them to transition smoothly between API V1 and V2 so a proper way to differentiate is required.

**Comment by znarf** [comment]
As a transition strategy, I'm proposing a simple breaking change in the API, followed by an immediate Frontend deployment.

**Comment by kewitz** [comment]
I'm all-in for consistency.

**Comment by sbinlondon** [comment]
Just to add another +1 to the chorus, consistency is always a good thing.
