### ISSUE TITLE
Create Collective Form: finish and polish

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#2937]
### Category Picker

- [x] Final "examples" links (`discover=[category]`
- [x] fixed fonts

### Generic Form (Community / Climate)

- [x] Fix gap between Title (Create a Collective) and Top Bar
- [x] Remove mentions to Guinea Pigs. Sorry @sbinlondon! (Agora)
- [ ] 'create collective' loading button feedback
- [x] description should be max 160 characters
- [x] fixed fonts

### "Open Source Flow": Welcome

- [x] Fix "Request manual verification" button
- [x] "Terms of fiscal sponsorship" should not link to /tos. But [this link](https://docs.google.com/document/u/1/d/e/2PACX-1vQbiyK2Fe0jLdh4vb9BfHY4bJ1LCo4Qvy0jg9P29ZkiC8y_vKJ_1fNgIbV0p6UdvbcT8Ql1gVto8bf9/pub) (bonus point if it is read dynamically).
- [x] fixed fonts

### "Open Source Flow": Manual Verification Form

- [x] It should apply to the "Open Source Collective" (Should be same behavior as /opensource/apply/v2)
- [x] "Terms of fiscal sponsorship" checkbox if it was not already checked

### "Open Source Flow": Pick a repository

- [x] "Click here" should link to the manual verification flow

### "Open Source Flow": GitHub form

- [ ] No feedback about the picked Repository/Organization (@Memo-Es and design)
- [ ] Pre-fill name with Repository/Organization name
- [x] Bug preventing the form to be submitted (`"host" is read-only`) -> Host should not be set anymore anyway, remove `this.props.host = { slug: 'opensource' };`

### "Apply Flow"

- [ ] No mention of the collective on the page. Should we have the Nav Bar as before?  (@Memo-Es and design)
- [ ] Back button is not working. Remove?
- [x] "Please accept the terms of fiscal sponsorship" error (there was no checkbox and it's not defined for the host anyway).

### GraphQL mutation

- [x] `automateApprovalWithGithub` is missing

### Collective Page (after redirect)

- [ ] Success banner confirming creation and explaining the state. With / without host.

### General

- [x] color of Back link

**Comment by Betree** [comment]
- I get a loading spinner when I open https://staging.opencollective.com/create/v2. Showing the page with disabled buttons during SSR would be nice.
- `See examples` links are missing an `href`
- On general flow, back button seems far away (also shouldn't it be black?)
![image](https://user-images.githubusercontent.com/1556356/75537284-056d0580-5a17-11ea-9f08-3e0a94640795.png)
- 30 characters for the short description seems too short to me. Below is a visualization about the number of collectives VS description length. Based on that data, I'd recommend setting the max length to **160**.
![image](https://user-images.githubusercontent.com/1556356/75538666-436b2900-5a19-11ea-9022-3572b3a4df1e.png)
- When I click on `Create collective`, I have to feedback that my clicked actually worked. We should set `loading=true` on the button when we submit the request.

The general UX is great, so much better that the current one!

**Comment by sbinlondon** [comment]
Re: examples links, are we just linking to one Collective that is the same `category`? Or what?

**Comment by znarf** [comment]
> Re: examples links, are we just linking to one Collective that is the same `category`? Or what?

I would like to discover, ie: https://opencollective.com/discover?show=community This will be likely later edited but it's a good start.

**Comment by Memo-Es** [comment]
> No feedback about the picked Repository/Organization (@Memo-Es and design)

As shown in the design, when you choose a repository it displays the two radio buttons of the choice of creating the Collective for the repository or the organization.
(The first option is selected by default)
<img width="1251" alt="Screen Shot on 2020-02-28 at 17-35-23" src="https://user-images.githubusercontent.com/49539954/75595125-bf349800-5a50-11ea-827e-c7c638e0594b.png">

>  No mention of the collective on the page. Should we have the Nav Bar as before? (@Memo-Es and design) 

I don’t understand, there shouldn’t be a reference of the Collective BEFORE creating it… Am I understanding this right? 

AFTER you create your Collective, I was thinking of using the pattern designed for conversations, in this case, a breadcrumb.
<img width="1177" alt="Screen Shot on 2020-02-28 at 17-41-52" src="https://user-images.githubusercontent.com/49539954/75595398-d9bb4100-5a51-11ea-922f-c220f87648fa.png">

@sbinlondon

**Comment by Memo-Es** [comment]
About the fields in the form... @sbinlondon 

<img width="491" alt="Screen Shot on 2020-02-28 at 17-58-10" src="https://user-images.githubusercontent.com/49539954/75595960-12f4b080-5a54-11ea-87ce-06d9b3b32616.png">

**Comment by znarf** [comment]
>> No feedback about the picked Repository/Organization (@Memo-Es and design)

> As shown in the design, when you choose a repository it displays the two radio buttons of the choice of creating the Collective for the repository or the organization.

I was talking about the Form, when I wrote there was no feedback that the user actually picked an Organization or Repository, just a blank form. Now that we decided to have the Collective name pre-filled with the GitHub Name, it's slightly better.

>> No mention of the collective on the page. Should we have the Nav Bar as before? (@Memo-Es and design)

> I don’t understand, there shouldn’t be a reference of the Collective BEFORE creating it… Am I understanding this right?

Was talking about the Host sorry. I think we have an agreement on adding the NavBar in this case.

**Comment by Betree** [comment]
> AFTER you create your Collective, I was thinking of using the pattern designed for conversations, in this case, a breadcrumb.

It's still unclear to me when we should display this breadcrumb. My latest understanding was that this was part of the experiments to improve the NavBar that was not ready for implementation yet.

Let's solve it elsewhere before working on it for this PR, I'm adding that to the design<>engineering call.

**Comment by znarf** [comment]
@Betree agree with you, should not be a topic for the current work being done.

**Comment by sbinlondon** [comment]
Mostly addressed in opencollective/opencollective-frontend#3605

Outstanding issues collected in opencollective/opencollective#2945
