### ISSUE TITLE
Update expiring cards cron and add reminder

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#2940]
The way we built the 'your credit card is expiring' cron, we were going to email on the first of the month that the card was due to expire.

However, this can get noisy with lots of other emails sent at that time. We need to pick a new time, and potentially also add a reminder email later in the month.

I propose the 7th and 21st. So about 1/4 and 3/4 of the way through the month. That way it won’t clash with beginning of the month emails, and also will remind them with enough time before the end of the month.

Thoughts? @znarf @kewitz @Betree

**Comment by kewitz** [comment]
I like that, sounds like good UX.
Also, I'm not completely sure, but I think expiration dates are inclusive, which means that we should be sending emails to credit cards expiring in the current month.

**Comment by znarf** [comment]
> but I think expiration dates are inclusive, which means that we should be sending emails to credit cards expiring in the current month.

This is what we do.

**Comment by Betree** [comment]
Sounds good

**Comment by sbinlondon** [comment]
@znarf keep this issue open until we have the cron running in production, not triggering it manually?

**Comment by znarf** [comment]
@sbinlondon yeah, let's trigger manually one last time on Monday then activate it.

**Comment by sbinlondon** [comment]
Emails sent manually last night. Will send reminders on the 21st and see how many people have updated.

**Comment by sbinlondon** [comment]
This was activated a while ago 🙈
