### ISSUE TITLE
Latest host report is missing attachments

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2943]
**Describe the bug**
The attachments are missing in the latest host report. This is something I needed to investigate but didn't find the time to before the 1st of the month and the batch of email is already sent.

We may want to re-generate the reports once the fix is deployed.

**Comment by znarf** [comment]
@Betree when was that originally reported?

**Comment by Betree** [comment]
Nowhere that I'm aware of, this was the first item on my to-do list for this week and when I realized we passed the first of the month during the weekend I started by looking at what was sent.

In the emails we sent this weekend all expenses have a blank space below instead of the expected file preview.
