### ISSUE TITLE
PDF Download is missing

### ISSUE THREAD

**Issue by mstenta** [opencollective/opencollective#2947]
In the email that is sent to contributors, it says "You can download a PDF receipt for your contribution on your transactions page".

As of this month, the page that this links to is different, and there is no obvious place to download a PDF.

Has the page moved? Or has the ability to download a PDF been removed?

**Comment by mstenta** [comment]
Oops I didn't realize I was logged out. Logged in an saw the new PDF link.

Sorry for the spam - hopefully someone else finds this useful.

**Comment by Betree** [comment]
Hi @mstenta :wave: Just to let you know that we also plan to embed the receipts directly in the emails in the future (see #2867) to simplify the user experience around this.

**Comment by mstenta** [comment]
That would be greatly appreciated, thanks!
