### ISSUE TITLE
Unable to add Open Source project

### ISSUE THREAD

**Issue by soulgalore** [opencollective/opencollective#2948]
**Describe the bug**
Clicking on "Get started" button for an Open Source project generates a JSON parse error for my user.

**To Reproduce**
1. Login to Open Collective
2. Click on 'Create a collective.'
3. Click on  'Open Source project'
4. Click on 'Get started'
5. I get the error in the screenshot. `SyntaxError: JSON Parse error: Unrecognized token '<'` Looking at the console log I can see I get: `Failed to load resource: the server responded with status of 503 ()` from https://opencollective.com/api/github-repositories?...

**Screenshots**
<img width="657" alt="Screenshot 2020-03-02 at 20 49 57" src="https://user-images.githubusercontent.com/540757/75711988-8baf7300-5cc7-11ea-9ba7-a48481ca96af.png">

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser Safari
 - Version 13.0.5

**Comment by znarf** [comment]
Sorry for the issue, is this still happening?

Can you look at the network request and share more details? Great if you can share the time, so we can look at matching logs.

If you're blocked, you can bypass it and the "manual-verification" process as specified in https://docs.opencollective.com/help/collectives/osc-verification#manual-verification
