### ISSUE TITLE
Validation error message if Tier description is too long

### ISSUE THREAD

**Issue by brymut** [opencollective/opencollective#2953]
While a Collective Admin is editing the description of a Tier, passes the character limit and tries to save their changes, the validation error message is not very helpful with being specific as to why they are not able to proceed with saving or what they can do to resolve the error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Collective page, click on the gear icon and switch to the Tiers section.
2. Add a new Tier by completing the form for a new tier or edit existing Tier.
3. Add more words/characters to the description input part of the form and surpass 510 characters. 
4. Scroll down to 'Save' button and click it.
5. See error message ''value too long for type character varying(510)" (not descriptive & unable to proceed with saving changes)

**Expected behaviour**
A clear and concise description of why the error has occurred and are unable to proceed/ how to resolve the problem causing the error.

**Screenshots**
![Screenshot of error message](https://github.com/brymut/github-gifs/blob/master/opencollective:opencollective:issues:2953/description-too-long-error-reproduction.gif?raw=true)

**Desktop (please complete the following information):**
 - OS: macOS Catalina version 10.15.3
 - Browser:  Chrome
 - Version: 80

**Additional context**
The problem can be even more inconvenient if there are multiple Tiers, one or more descriptions that are too long and the error doesn't point out the specific Tier description causing the issue.
 
For example, if you don't fill in the Goal amount a validation error message is shown that helps the Collective Admin address the issue.
![Screenshot of error message](https://github.com/brymut/github-gifs/blob/master/opencollective:opencollective:issues:2953/Validation-error-message-Amount-required.jpg?raw=true)

**Comment by brymut** [comment]
ran into this bug while working on https://github.com/opencollective/opencollective-frontend/pull/3613

**Comment by znarf** [comment]
@brymut Thank you for the report. I can't see the screenshot right now.

**Comment by Betree** [comment]
Users are being confused by this error: https://opencollective.slack.com/archives/C6JTTA4SK/p1598556826018400

We could improve the error message by adding a custom `validate` in https://github.com/opencollective/opencollective-api/blob/ada16642e5a90e5598e79e50d4e3c3e60b3b8a89/server/models/Tier.js#L79. I'll do that now.

This form however deserves a good revamp, I hope we'll find the time to do it in the mid term as a lot of users use this flow.
