### ISSUE TITLE
Unique token column for ConnectedAccounts

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#2957]
Since queries to TransferWise are secured by IP, the easier way for a malicious actor with access to a valid token would be to just create a new Host and connect with the stolen token.
This way the attacker would be able to generate requests using that token from our IP.

To make sure that isn't possible, update the model and write a migration to make sure ConnectedAccount.token is unique.

**Comment by Betree** [comment]
A unique index on `[service, token]` would do the job (tho I don't think there's a strong risk of collision between tokens).

I checked earlier and we have ~200 entries with duplicates, all of them are Twitter and 1 is meetup.
- The meetup duplicate can safely be deleted.
- For all the Twitter entries, we could keep only the most recent one if there are duplicates. We should also add a check on https://github.com/opencollective/opencollective-api/blob/c5fc8dbb17751b5723be7f75fae20fe815a5c9b8/server/controllers/connectedAccounts.js#L116, that's probably the source of the duplicates

**Comment by kewitz** [comment]
@Betree we have a problem. There are a few Twitter accounts being used across different collectives.
I think we should talk to users before killing this feature.

**Comment by kewitz** [comment]
There's also a stripe account being shared between two collectives.
```sql
SELECT * FROM "ConnectedAccounts" WHERE id NOT IN (
	SELECT DISTINCT ON (token, service, username) id FROM "ConnectedAccounts" ORDER BY token, service, username, id desc
);
```

**Comment by znarf** [comment]
I'm almost done, main strategy is:

- Ignore deleted ConnectedAccounts and Collectives
- Delete duplicates that are not Collective or User=isHost or Organization=isHost (there is no point connecting Twitter out of these cases)
- Delete duplicates that don't have Tweets configured or are explicitly turned off
- Deletion of the least used/useful (no transaction, no tweet going out)

Also, we've now restricted Twitter connection to Collectives and Hosts.

**Comment by znarf** [comment]
Remaining is the possibility for someone to connect the same Twitter account (+ token) on their hosting Organization and their Collective. We should be ready to handle that.

**Comment by kewitz** [comment]
This is being validated in the ConnectAccount mutation and it occurs depending on the service being connected.
