### ISSUE TITLE
Enforce delay between Accepting expense and being able to automatically pay for it

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#2958]
## User story 
As a Host admin, I want to wait for 24hrs before I'm able to pay for an expense so if someone hacks my account I'm able to notice it before the attacker is able to generate and pay expenses.

## Best solution for this problem
When paying for expense automatically consider the value and the time since it was accepted.
If the value is above a threshold, throw if the expense was accepted less than 24 hours ago by the same user who's paying.
This should work for both PayPal and TransferWise

## MVP
Update `payExpense` mutation logic to check when the expense was accepted.
If the value is above 1K USD and it was accepted by the same user who's paying it less than 24 hours ago, throw an error.

**Comment by kewitz** [comment]
@Betree bringing this back for discussion.

**Comment by Betree** [comment]
As mentioned in https://github.com/opencollective/opencollective-api/pull/3613, I think that showing an error message if hosts try to pay expenses in the 24h following their approval is a bad user experience that can create a lot of frustration and wasted time.

If we want to go with such solution, I suggest to rather put this delay between the moment hosts click on "Pay" and the moment the payment is actually sent. Example:

- Host admin click on pay (01/01 @ 10h00), expense is marked as "validating"
- A notification is sent to the host admin that a payment is about to go out
- The host can still click on `Cancel payment` for the next 24h
- If not canceled before 02/01 @ 10h00, the payment will go out at this time

Now implementing this has a certain cost, so we should properly discuss it and eventually consider other security measures that will have a bigger impact first like https://github.com/opencollective/opencollective/issues/1746.

**Comment by kewitz** [comment]
Solved by https://github.com/opencollective/opencollective-api/pull/4713.
