### ISSUE TITLE
GraphQL schema for Events

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#296]
```graphql
  getEvent(collectiveSlug: "opencollective", eventSlug: "jan-meetup") {
    id,
    name,
    description,
    location, // location name, e.g. "Balanced.nyc"
    address, // location address string, e.g. "547 Broadway"
    lat, // float
    lng, // float
    backgroundImage, // string
    tiers {
      id,
      name,
      description,
      amount,
      currency,
      quantity // total number of tickets, not to be confused with total available (maybe we should use maxQuantity to make this clearer?)
    },
    collective {
      id,
      slug,
      name,
      mission,
      backgroundImage,
      logo
    },
    responses {
      quantity,
      status,
      description, // per event short bio, falls back to user.description
      user {
        name, // firstName + lastName
        avatar,
        description // or bio
      },
      tier {
        name
      }
    }
  }
```

**Comment by asood123** [comment]
1. Why do we need lat & lon if we have an address? Aren't they going to be conflicting?
2. `tier.quantity` is currently meant to track total quantity in that tier. Ex: An organizer specifies no more than 20 cheap tickets, so `quantity = 20` for that tier permanently. `maxQuantity` is better. I'll add that and `availableQuantity`, which will be a real-time query on `response` table.
3. I'll add `response.description` as well. 
4. Keeping `user.description` for now

**Comment by xdamman** [comment]
1. So that we don't always have to resolve the address into coordinates (which are needed to show the google maps)
1. Sgtm
1. Ok
1. Ok. Sure it's there? I think it was returning an error.
1. Ok.

**Comment by asood123** [comment]
#4 was in the model only, now in schema as well.

Lat, longs are a little more complicated and it would be a single Geometry field in Postgres. How will we resolve the address first time to get the lat/long? Given that it'll always happen on user's machine, is it worth storing? Will be another field to update and keep in sync with address.

**Comment by xdamman** [comment]
We could simply store it as two separate floats.
You don't want to resolve the address string to coordinates at every page load. They only change every few hundred years at best.

**Comment by asood123** [comment]
Ok I'll add it. Lots of articles online advocating not storing it as floats. So, we can do a point. Shouldn't matter from frontend's pov, we can split it into two points in the schema if that's the issue.
