### ISSUE TITLE
Github Banner not working

### ISSUE THREAD

**Issue by wdanilo** [opencollective/opencollective#2960]
**Describe the bug**
Hi! I registered to opencollective few days ago and I'm trying to generate github banner for my organization. However, after entering `https://opencollective.com/enso-language/contributors.svg?width=890` I do not see anything. Could I ask you for a help please?

**Comment by znarf** [comment]
Looking at it.

**Comment by wdanilo** [comment]
@znarf have you discovered something? :)

**Comment by znarf** [comment]
Yes, our job fetching contributors from GitHub was broken. But it's now fixed!

**Comment by wdanilo** [comment]
@znarf thank you, thank you, thank you!
