### ISSUE TITLE
Might not be receiving emails

### ISSUE THREAD

**Issue by staltz** [opencollective/opencollective#2961]
Follow up of issue https://github.com/opencollective/opencollective/issues/2566, I *think* I am not getting emails for the open collective [Manyverse](https://opencollective.com/manyverse). For instance, I just submitted an expense and did not receive an email within 1 hour. Also published an update but did not receive an email for that either.

**Comment by znarf** [comment]
Sorry, same issue as last times, because of a spam report originating from your address.

I tried to whitelist your address in our email provider without success. I contacted them about that.

You should receive the emails now but I'm afraid it will happen again.

**Comment by staltz** [comment]
I suppose I'm not the only one to ever experience this in opencollective? As an option, could consider changing email providers.

**Comment by znarf** [comment]
I know it's difficult to imagine, but you're the only one to report that :-/

Just looked again at this Complaints list and it's really short, ~20 emails in there.

**Comment by znarf** [comment]
Closing.

I'll keep an eye on it in Mailgun and will follow up with them if/when this happen again.
