### ISSUE TITLE
Support Metrics Report February 2020

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#2964]
### Support Metrics Report February 2020

This report looks at the trends around support to help us better understand areas we need to improve and highlight key topics for the month. 

**Tickets received** 
![Capture](https://user-images.githubusercontent.com/57156267/76044291-cb73a480-5fbe-11ea-8333-8c356ca08f94.PNG)

The number of tickets received has increased by 34% from 173 in January to 232 in February. If we take into account the tickets falling under the recruitment tag and blank tickets received, the increase remains roughly of the same proportions - 29% - with 132 tickets raised in February compared to 102 in January.

![Capture](https://user-images.githubusercontent.com/57156267/76044369-01188d80-5fbf-11ea-920a-060a6e9afcec.PNG)

**Trends and Recommendations**

After removing irrelevant tickets, we had 132 that required support attention. It is worth noting the following:

- The largest number of tickets received this month falls under the Expense category, with 21 tickets recorded in February (more than double than the 10 raised in January). Some of the questions were from users trying to understand the process around expenses, however, there were also some issues this month with PayPal payments. Some of the payments processed in early February were cancelled with refunds arriving closer towards the end of the month. Some [questions from users](https://opencollective.freshdesk.com/a/tickets/4579) drove us to investigate what has happened and to fix all similar issues (there were about 7 similar incidents) and the process has been established around ensuring PayPal balance is at around $25k to avoid similar issues going forward. It is worth noticing the team is currently working on the TransferWise integrations and the beta version is available for use for Engineering. Will be interesting to see the implications going forward

- We had a few questions arising around changes in payment methods and some users wanted to move from credit card payments to bank transfers. It triggered us to note that the document section on the topic was out of date, and thanks to the help from Anna [this section in our documents has been updated](https://docs.opencollective.com/help/financial-contributors/payments)

- It is worth noticing that we now starting to receive requests for Bitcoin payments, and the proposition we offered to users seem to attract a few requests. The volume is very low at the moment but it will be interesting to see the trend moving forward. You can learn more about the process [here](https://drive.google.com/open?id=1X5Myr0-eKyk_INzVBR9CirF2gnIyZw7II7ygZ0DUFjY)

- There is still a relatively high number of tickets classified under “tax” category, but those have dropped to 9 from 12 in January. This is mostly driven by questions from users submitting expenses for the first time where it triggers them to fill a new tax form for the year

- We received a number of notifications from Collective Admins about spam expenses arriving. All those were referred to the team review

**Comment by Betree** [comment]
This is very insightful, thanks @alinamanko! 

I hope the changes we are making on expenses with transferwise and the new flow will help decrease the support requests for them.

We also have new tools to fight against spammers that are making us more efficient at it. We still need to collect more data but at least we are able to respond and remove SPAM content quickly.
