### ISSUE TITLE
Merge search and discover pages

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2970]
## User story 
As an Open Collective user looking for a collective, I have two options:
- Use the search bar at the top, which redirects to the **search page**
- Use the **discover page**, that also has its own search bar

The reason for this distinction is unclear to me, one single endpoint with good filters to find collectives would be enough.

## Best solution for this problem
Because the **discover page** has a better design, I'd suggest using it by default for the search and to get rid of the existing search page. To make a smooth transition, we should apply the following changes:

- Update the behavior for the search bar on discover page to not only search by tag, but also in other fields (use the `search` GraphQL endpoint for that).

- Message when no collectives (optional)

Currently if there's no result in the discover query, we display this:

> No collective matches the current search.

The search page had [a clever call to action](https://opencollective.com/search?q=no-tag-like-this) to create a pledge in this situation, I think we should add it to the discover page too.

## Documentation 
Should update https://docs.opencollective.com/help/financial-contributors/financial-contributors#how-can-i-find-collectives-to-support

---

_Related: #2830, #2605, #2232, #2969_

**Comment by xdamman** [comment]
Good idea.

Also right now the discover page shows filters for “open source collectives”, “pledged collectives” and “Other”. Can we add one for “climate emergency”?

When clicking on “pledged collectives”, it would be good to have a word of explanation with a link to create a new pledged collective.

When no result I’d show a message followed by a section: “Discover new collectives”

**Comment by Betree** [comment]
> Can we add one for “climate emergency”?

That makes sense given that we add a special tag for them in the new create collective flow. Did we decided on the exact tag yet, is it `#climate`?

**Comment by sbinlondon** [comment]
This sounds like a great idea, simplifying it into one page 😊

**Comment by gusaus** [comment]
This sounds like a great first step. Curious if any of the suggestions for improving search and discovery mentioned in https://github.com/opencollective/opencollective/issues/2232 could be implemented next.

**Comment by Betree** [comment]
@gusaus we should involve design for this, but that could be a good addition indeed.

**Comment by raulgrafico** [comment]
This new flow to discover and search would be a good entry point for users that are already logged in; this new entry point can probably include relevant information for the user, based on their browse habits or updates around expenses, conversations, etc.

Inside this new entry point, we can have the search bar as our main top element.

The new discovery page will recommend collectives, tiers, conversations, etc. based on the user browse habits.

For future releases, I think saving searches, following tags, will be great features to improve the experience to find collectives to contribute.

Agree with @gusaus on that search using multiple tags.

**Comment by kaylarep** [comment]
Agree that merging the search bars makes the most sense for user functionality.

Have raised a github issue here for ideas for better search filters: https://github.com/opencollective/opencollective/issues/3892
(more suggestions are welcome!)

**Comment by patcon** [comment]
Just a note that **including "tags" in search** on https://opencollective.com/search?isHost=true

For a fiscal host, this helps them try to **catch the regions and themes** under which we'd hope to be found. Right now, we have to cram everything into the description, which is a bit awkward ("A Canadian worker co-operative based out of Toronto Canada, and incorporated under the Ontario Co-operative Act")

**Comment by Betree** [comment]
Got a [user feedback](https://opencollective.freshdesk.com/a/tickets/52486) that confirms the need for this to be tackled:

> I believed that the Pytest project was on Open Collective, so I came to your site, went to the Discover page and entered that name. It said nothing was found.
> 
> Eventually on their github site I followed a link and found that they are on Open Collective, and have been for a while. But still the search finds nothing.
> 
> This is very confusing.

**Comment by SudharakaP** [comment]
The [original spec](https://github.com/opencollective/opencollective/issues/2970#issue-577767126) in this thread seems a bit outdated therefore I am proposing the following. 

- [ ] Update the discover page search bar to use the `/search` endpoint (https://github.com/opencollective/opencollective-api/blob/533521783a17371eb37d07bcf7a596ba866c617a/server/graphql/v1/queries.js#L904).

- [ ] Remove pledged collective search capabilities from the discovery page. 
  - [ ] Removes showing pledged collectives
  - [ ] Removes the `Pledged collective filter

- [ ] Migrate the basic collective filters from the search page to the discovery page

![image](https://user-images.githubusercontent.com/12435965/157772393-8d707b58-6e50-49f2-921e-5bcd93dec225.png)

- [ ] Remove the search page (https://opencollective.com/search)

- [ ] Either remove the search bar or re-direct it to the discover page (to be confirmed with @opencollective/design).
- [ ] 
Let me know if I've missed anything here. 🙂

**Comment by Betree** [comment]
@SudharakaP We can go one way or another, but I think it is way simpler to rather remove the discover page and update the search page because this last one already uses the correct query, uses the right route, has the filters implemented, and pretty much everything we want (except a nice looking design). The sort by option is not supported by search yet, so we'll have to (temporarily) remove it from the discover page anyway. Going with this approach, the specs become as simple as:

- [ ] Redirect the discover page to the `/search` endpoint

**Comment by SudharakaP** [comment]
> @SudharakaP We can go one way or another, but I think it is way simpler to rather remove the discover page and update the search page because this last one already uses the correct query, uses the right route, has the filters implemented, and pretty much everything we want (except a nice looking design). The sort by option is not supported by search yet, so we'll have to (temporarily) remove it from the discover page anyway. Going with this approach, the specs become as simple as:
> 
>     * [ ]  Redirect the discover page to the `/search` endpoint

Makes sense. I think along with this, we'll update the design for this page as well to be proposed at today's meeting.

**Comment by SudharakaP** [comment]
So I am updating this some specific plans to implement next week; 

- [ ] Redirect the discover page to the `/search` endpoint. 
- [ ] Replace the search bar in the nav bar with the new magnify icon and redirect that to the search page. 
- [ ] Modify the search page according to the new design (we will tackle modifying the design of collective cards in a separate issue; https://github.com/opencollective/opencollective/issues/5316). 
  - [ ] Search bar redesign
  - [ ] Align the filters property

Figma Design: https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab?node-id=14313%3A186353 

![image](https://user-images.githubusercontent.com/12435965/157933781-34cc1141-5aca-4e98-b5b3-b001447e300b.png)
