### ISSUE TITLE
Make custom contribution (donation) opt-out

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2973]
# User story 
As a collective admin, I want to be able to disable the **Custom contribution** path to force contributors to belong to one of the tiers that I've defined.

![image](https://user-images.githubusercontent.com/1556356/76236406-e9464100-622c-11ea-96ba-b15bb888e626.png)

# Specs

## Frontend

- [x] On `collective/edit/tiers` add a checkbox at the top of the page
  - Label: Enable custom contributions
  - Description: This adds a default tier on your collective that doesn't enforce any minimum amount or interval. This is the fastest way for people to donate to your Collective!
  - Default value: true
  - When saving with an unchecked state, `collective.settings.disableCustomContributions` will be set to `true`.
- [x] On the collective page (ie. https://opencollective.com/babel) don't show custom contribution if `disableCustomContributions` is true
- [x] On the contribute page (ie. https://opencollective.com/babel/contribute) don't show custom contribution if `disableCustomContributions` is true
- [x] In the contribution flow (ie. https://opencollective.com/babel/donate) show a message instead of the normal flow if `disableCustomContributions` is true and there's no tier:

> {collective} requires you to select a tier to contribute. Check all the available tiers on [the contribute page](https://opencollective.com/{collective}/contribute).

## API

- [ ] In `createOrder`, throw an error if `disableCustomContributions` is true and there's no tier.

**Comment by Betree** [comment]
@znarf about the API changes (_In `createOrder`, throw an error if `disableCustomContributions` is true and there's no tier._) can this conflict with what we're doing with the Github sponsors integration?

**Comment by piamancini** [comment]
@Betree we should make this also available for events.

**Comment by Betree** [comment]
@piamancini true, arguably disabling donations should event be the default for events.

Anyway the checkbox should also be available for them as we're currently migrating events to the same settings page than collectives: https://github.com/opencollective/opencollective/issues/2932

**Comment by piamancini** [comment]
Someone else just requested the default tier to be removed as well.

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

---

Please follow our [code guidelines](https://docs.opencollective.com/help/developers/best-practices-and-code-guidelines), especially:

* The strings must be internationalized. See [/help/developers/translations](https://docs.opencollective.com/help/developers/translations)
* Whenever it's possible we must use `styled-components` to write styles. See [OC Styleguide](https://opencollective-styleguide.now.sh/)
* We're getting rid of `Bootstrap`. Please don't use it for new developments.
* When adding new dependencies, we use [fixed versions](https://docs.npmjs.com/about-semantic-versioning).
* Icons must be imported from the [styled-icons](http://styled-icons.js.org/) library.
* Tests written with Cypress must follow our [good practices](https://docs.opencollective.com/help/developers/testing-with-cypress) conventions.

**Comment by leonardohof** [comment]
Hey @jeffin143! Are you still working on this? Or, Can I take it? @Betree

**Comment by jeffin143** [comment]
> Hey @jeffin143! Are you still working on this? Or, Can I take it? @Betree

Hi @leonardohof , hope you are doing fine :) , can I have a go at this for 1 more day. I will leave the bounty by tomorrow same time and inform you

Thanks

**Comment by jeffin143** [comment]
@leonardohof , You can Go ahead and work on this issues, I have just started the work, You can push to the existing branch.

**Comment by leonardohof** [comment]
> @leonardohof , You can Go ahead and work on this issues, I have just started the work, You can push to the existing branch. It's your wish, don't feel obliged :)

If you're with working in progress, you can continue...

**Comment by davejon1337** [comment]
@jeffin143 can I work on this if it's okay with you?

**Comment by Betree** [comment]
Hi @jeffin143, are you currently working on it?

**Comment by jeffin143** [comment]
I will complete I today, this got of my list
Thanks for the heads up

**Comment by vickywane** [comment]
Hi, @Betree . 

Is any one currently working on this? 

I would like to give a try at contributing to the OpenCollective since my last PR.

**Comment by Betree** [comment]
@jeffin143 we still need an API PR to complete the issue (see the specs at the top of this thread)
