### ISSUE TITLE
Remove react-hook-form dependency

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2976]
We're moving away from `react-hook-form` to instead go with `Formik` (see https://github.com/opencollective/opencollective/blob/master/rfcs/009-move-away-from-react-hook-form.md).

We have 3 legacy forms that we want to migrate:
- [ ] `CreateConversationForm`: either use `Formik` or just react state (it's just 2 fields)
- [ ] `CommentForm`: either use `Formik` or just react state (it's just 1 field)
- [ ] `CreateCollectiveMiniForm`: use `Formik`

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

---

Please follow our [code guidelines](https://docs.opencollective.com/help/developers/best-practices-and-code-guidelines), especially:

* The strings must be internationalized. See [/help/developers/translations](https://docs.opencollective.com/help/developers/translations)
* Whenever it's possible we must use `styled-components` to write styles. See [OC Styleguide](https://opencollective-styleguide.now.sh/)
* We're getting rid of `Bootstrap`. Please don't use it for new developments.
* When adding new dependencies, we use [fixed versions](https://docs.npmjs.com/about-semantic-versioning).
* Icons must be imported from the [styled-icons](http://styled-icons.js.org/) library.
* Tests written with Cypress must follow our [good practices](https://docs.opencollective.com/help/developers/testing-with-cypress) conventions.

**Comment by jeffin143** [comment]
Hi @brymut , I see you have self assigned yourself, If you haven't started working on this, Can I take up the issue :), Don't be obliged, totally your call

**Comment by brymut** [comment]
Hi @jeffin143, sorry but I have started on it.

**Comment by jeffin143** [comment]
@brymut , no issues :) good luck

**Comment by brymut** [comment]
Hi @jeffin143, I find that unfair, I have been working on this.

**Comment by znarf** [comment]
@brymut @jeffin143 I think there is a misunderstanding, we (Open Collective Core Developers) manage this bounty program and it's of course at our discretion to unassign issues.

@brymut can you please share your work in progress for this issue? we'll unfortunately not be able to keep you assigned without significant progress.

**Comment by brymut** [comment]
Sure @znarf , I'll create one right away, it's just that I had been trying to learn how to work with React Hooks, I admint however, that I should've pushed some work either way.

**Comment by jeffin143** [comment]
> @brymut @jeffin143 I think there is a misunderstanding, we (Open Collective Core Developers) manage this bounty program and it's of course at our discretion to unassign people from issues.
> 
Sorry about that , won't repeat it 

> Hi @jeffin143, I find that unfair, I have been working on this.

Sorry @brymut , I was unaware of it , I just assumed you were caught up with something. It was mistake on my part , I should have probably asked you:)

**Comment by Betree** [comment]
:trophy: This issue has been completed by @brymut  

To claim the **$200** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
