### ISSUE TITLE
Collective picker: apply latest design

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2977]
:art:  See [latest design on figma](https://www.figma.com/file/9Iq3vBOmZ2EuOacXEYD5yK/%5BDS%5D-05-UI-Organisms?node-id=0%3A1716)

## Remove custom icons, use ( + ) icons and use new labels

**Today**
![image](https://user-images.githubusercontent.com/1556356/76427703-eeca9500-63ac-11ea-97ce-c5b438f02519.png)

**Expected**
![image](https://user-images.githubusercontent.com/1556356/76427911-3d782f00-63ad-11ea-99a7-18ef9717c84d.png)

## Add lines next to type labels

**Today**
![image](https://user-images.githubusercontent.com/1556356/76428163-9778f480-63ad-11ea-9bb1-a8a573b33bc5.png)

**Expected**
![image](https://user-images.githubusercontent.com/1556356/76428208-a790d400-63ad-11ea-8fb4-a9b2045bd2cc.png)

## Update font-sizes

*See design on Figma*

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by flickz** [comment]
@Betree Taking this on

**Comment by Betree** [comment]
:trophy: This issue has been completed by @flickz  

To claim the **$200** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
