### ISSUE TITLE
Design system update: Mid March 2020

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#2979]
### This update includes:

- **[Typography](https://www.figma.com/file/jxJfC29te8i1C8qMReth95/%5BDS%5D-01-Typography?node-id=9%3A10)**: 
  - Style sheets for devs and style sheets for design use
  - Use categorization: Display fonts, Heading fonts, Paragraph fonts, Caption fonts, Label fonts.
  - Improvements and adjustments in naming and organization 
<img width="848" alt="Screen Shot on 2020-03-13 at 01-00-55" src="https://user-images.githubusercontent.com/49539954/76597473-2a0cb700-64c6-11ea-9e30-7a4c76219707.png">

- **[Buttons](https://www.figma.com/file/N4Xbl652BhzOutXmzhcrLGch/%5BDS%5D-03-UI-Atoms?node-id=14%3A1)**
  - Style and gradient primary
  - Style and gradient secondary
  - Style and gradient standard dark
  -  Style and gradient standard light
  - Style and gradient red simple 

<img width="1010" alt="Screen Shot 2020-03-13 at 01 06 33" src="https://user-images.githubusercontent.com/49539954/76597790-ea929a80-64c6-11ea-9be0-06ee672b3640.png">

🟢 These updates are ready to be implemented platform-wide.
@opencollective/core-developers @Betree

**Comment by Betree** [comment]
This was done with https://github.com/opencollective/opencollective-frontend/pull/3481 + https://github.com/opencollective/opencollective-frontend/pull/3804 + https://github.com/opencollective/opencollective-frontend/pull/3805
