### ISSUE TITLE
modify the thank you email for subscriptions

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#298]
Perkins-Coie suggests we make the following addition to the thank you email to comply with US regulations: 

You can follow our future activities and how we will be spending the money on our open collective page (link) 

> Your subscription is ongoing and the contribution of $XX per month will be billed to the payment method you provided each month on a recurring basis until you cancel your subscription. If you would like to cancel your subscription, please click here. If you choose to cancel your subscription, you must do so at least [insert number] days before your next scheduled subscription renewal date to avoid being charged for the next month. For more information about Company’s subscription terms and cancellation policy, please see [insert URL to TOS].

Warmly, etc

**Comment by piamancini** [comment]
@asood123 what makes sense to you to add as # of days?

**Comment by asood123** [comment]
1 day before is fine for now.

**Comment by piamancini** [comment]
this should be revised from the c6
