### ISSUE TITLE
Relax X-Frame-Options on button page

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2981]
Reported in https://opencollective.freshdesk.com/a/tickets/5137

> <script src="https://opencollective.com/webpack/donate/button.js"></script>
> 
> I am facing the following error while access this script,
> 
> Load denied by X-Frame-Options: “SAMEORIGIN” from “https://opencollective.com/webpack/donate/button?color=white”, site does not permit cross-origin framing from “http://localhost/php/opencollective.html”
> 

We need to set `Access-Control-Allow-Origin` header to `*` on this page.

**Comment by davejon1337** [comment]
@Betree 
`
  server.use(helmet({ frameguard: false }));
`
Doing this in `/server/index.js` will fix this issue but will disable frameguard throughout the app.
Is this an acceptable solution? 
If not, can you point where exactly `Access-Control-Allow-Origin : *` is to be set. I can't seem to figure out where this route is `https://opencollective.com/webpack/donate/button?color=white`

**Comment by Betree** [comment]
Hi @davejon1337, thanks for looking into it. 

We can't change the CORS headers for the whole app, it needs to be done for this endpoint only. Thankfully this endpoint has a special express route so it should be fairly easy, just adding the header above in https://github.com/opencollective/opencollective-frontend/blob/8930cc562d738170d5cba0d0698a4265e347ca9f/server/routes.js#L115 should do the job (it needs to be tested to make sure).

**Comment by davejon1337** [comment]
@Betree 
I did try adding the header in `/:collective/:verb/button.js`. It still results in the same error.
I think the problem isn't with that route but with this `/webpack/donate/button?color=white`.

**Comment by Betree** [comment]
My bad, the header that we need to set is not `Access-Control-Allow-Origin`, it's `X-Frame-Options`.

**Comment by Betree** [comment]
Should be fixed in the next release, hopefully today
