### ISSUE TITLE
Changelog auto-update

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2984]
## User story 
https://changelog.opencollective.com is not updated often. As a consequence we can't really rely on it to track our progress, which defeat it's intended purpose.

## Best solution for this problem
We don't want to loose time doing that manually in the future, so we should create a job that does it at least once per day. Github actions has something for that: https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

```yaml
on:
  schedule:
    - cron: '0 * * * *'
```

## Metrics 
- Changelog is up to date
- Time saved not doing it manually

**Comment by SudharakaP** [comment]
@Betree : Hey, I can take this issue if no one is working on it. Can you please assign it to me? :smile:

**Comment by Betree** [comment]
Hi @SudharakaP :wave: 

This issue may not be the easiest to tackle if you're not part of the core team, but if you're comfortable with Zeit / Github actions your help here would be appreciated!

The repository is this one: https://github.com/opencollective/opencollective-changelog

We are deploying this service with Zeit Now. I suppose that the job could use [deploy hooks](https://zeit.co/docs/v2/more/deploy-hooks) to achieve what we want, but we're open to other proposals if you have a better idea on how to solve this!

**Comment by Betree** [comment]
Actually it seems that we have auto-deploys enabled for this repo, so a job that updates the changelog, builds and push the result should work

**Comment by SudharakaP** [comment]
> Actually it seems that we have auto-deploys enabled for this repo, so a job that updates the changelog, builds and push the result should work

Exactly my thoughts. I have a script which I am testing right now; will create a pull request today. :smile:

**Comment by SudharakaP** [comment]
@Betree : Done. Let me know if everything looks okay. Since it's my first few contributions I am not sure if I am doing everything according to your guidelines. :smile:
