### ISSUE TITLE
Make open collective free for COVID-19 related initiatives / hosts?

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2985]
A lot of citizens are coming together in solidarity with the people directly impacted by this pandemic; people at the front line (nurses, doctors, ...) and people losing their income.
Not everyone has the luxury to be able to work from home and we all need to come together to organize locally and support our communities.

Why not offering Open Collective for free for the next 3 months to all non profits that want to become a fiscal host for all those citizen initiatives? (No subscription fee, no platform fee).

The cost is virtually zero and this will give the opportunity to a lot of non profits around the world to learn and experience Open Collective.

**Other platforms offering their service for free:**
Discourse is offering 3 months free for schools that are closing down: https://twitter.com/discourse/status/1239661198317989889?s=21

Slack is offering free upgrades to communities working on COVID-19: https://twitter.com/stewart/status/1239688337029390336?s=21

**Some of the collectives for the coronavirus:**
- FOSS Responders https://opencollective.com/foss-responders
- Portland Coronavirus Mutual Aid Fund: https://opencollective.com/portland-corona-virus-mutual-aid-fund
- Zubian mutual aid fund https://opencollective.com/zubian-mutual-aid-fund

**Comment by kewitz** [comment]
I like it and I think it is only fair to do it, I just don't know the price implement it systematically.
We're currently manually implementing what you suggested by donating back to FOSS Responders all the fees we collected, this should happen weekly [ref](https://opencollective.com/foss-responders/conversations/open-collective-fees-04qjro68).

**Comment by xdamman** [comment]
What about we ask people to reach out to support and we could manually set a flag in the `collective.settings` (such as `collective.settings.platformFees = 0`). If applied to the host, all hosted collective inherit this value.

**Comment by Betree** [comment]
I'd rather use `data` if we want to implement such solution. `settings` is editable, which means users would be able to remove the fees for their collective by themselves.

**Comment by piamancini** [comment]
I think we should donate the fees back and not tweak it programmatically. Also, there should be some level of review so potentially an application process. 
How are discourse and slack doing it @xdamman?

**Comment by xdamman** [comment]
Not sure how they are doing it. It looks like you have to ask them, which is fine.

We can reimburse the fees for now but I’d definitely investigate how easy it would be to remove them programmatically as there is a big psychological difference between seeing that 5% went out to the platform when you made a donation and 0. Also most people won’t notice that the fees have been later reimbursed.

@kewitz @Betree how hard do you think it would be to implement that? (Sure we could use the `data` field). 

The new host http://opencollective.com/the-social-change-agency in the UK is ready to roll out to enable local communities there to have their own COVID19 mutual aid fund. But this 5% platform fee is definitely in the way. Let’s drop it for this use case during the lockdown (up to 3 months I’d say).

**Comment by piamancini** [comment]
>  Also most people won’t notice that the fees have been later reimbursed.

This fee is our sustainability, so if we are going to drop it, which I thing is the right thing to do, as we are doing with the FOSS responders, I think it's fair that people are aware we are. We are not sustainable yet, so giving away our revenue is a bog thing. I think people will notice less if there are no fees taken directly. 

> Not sure how they are doing it
So what's your proposal? Anyone with the tag Covid-19? I think we should have some review process here. What could that be?

> https://opencollective.com/the-social-change-agency
They have a test collective?

**Comment by xdamman** [comment]
Yes people should be aware that the platform fees are dropped momentarily. 
It's just much better for all parties to not charge them in the first place. But we can start that way.

For the review process, I'd just recommend that we whitelist some hosts starting with the one above and also use the tag #covid19. For other hosts, they need to reach out to us and justify their activity. Because everything is transparent, it's fairly easy for us to avoid abuse. So I'd be tempted to trust by default.

Thank you for participating in this global effort 🙏
