### ISSUE TITLE
Account number wrong?

### ISSUE THREAD

**Issue by wmhilton** [opencollective/opencollective#2988]
On [this page](https://docs.opencollective.com/help/collectives/github-sponsored-organizations) (e.g. https://github.com/opencollective/documentation/blob/v2/collectives/github-sponsored-organizations.md) it gives the account number as `4864122233` but when I entered that into Stripe, Stripe gave an error that that number was blocked because previous payouts did not go through. A quick google showed me OC has a different account number [here](https://www.oscollective.org/contact) `4866342233` and I tried that and that _did_ go through. Is the number listed on the page maybe a typo?

**Comment by znarf** [comment]
@piamancini can you check?

**Comment by sobolevn** [comment]
I confirm. The same worked for me.

**Comment by piamancini** [comment]
Yes, we are working with Stripe to solve this issue. The account number is correct. We will keep you updated. Thank you

**Comment by wmhilton** [comment]
Hmm. So... if `4864122233` is the _wrong_ account number, I guess I won't activate that GitHub Sponsor page yet. It'd be kind of awkward to send money to the wrong bank account.

Is `4866342233` at least still a current account of OC or does that page need to be updated instead?

**Comment by piamancini** [comment]
@wmhilton there is an error in github's documentation. The correct account is this one: 4866342233.  Please use that one. We will update the documentation soon. 

The funds will never go the wrong bank account, the issue you were seeing was the platform working as expected, blocking the wrong account number.

**Comment by znarf** [comment]
Fixed in https://github.com/opencollective/documentation/pull/61

**Comment by matchai** [comment]
The new account number worked for me.
I think this issue is ready to be closed. 👍
