### ISSUE TITLE
Learn more page 

### ISSUE THREAD

**Issue by erickrico** [OpenCollective/OpenCollective#299]
Create a page that explains with more detail how open collective works.

Based on this doc >> https://www.dropbox.com/s/jzzzhgfwz3otpnx/OpenCollective-ProductDemo.pdf?dl=0

**Comment by erickrico** [comment]
Hey, posting updates, i know you told me to not overthink the page, but i think this is doable within our time constraint, if this goes far off of what you envision we can just roll back to the keynote.

i still need to add the open source section and the final cta

![learn more](https://cloud.githubusercontent.com/assets/18429104/22491410/d6c714da-e7e8-11e6-8120-14dcfabc784a.png)

We are planning on adding a couple simple animations to display some functionalities such as:

- Submit expense flow (a video capture of the flow)
- Add tiers (make it clear that you can create more than 2)

**Comment by xdamman** [comment]
Looks great. Ship it. Get it out there first then worry about animations.

**Comment by erickrico** [comment]
@asood123 
![learn more](https://cloud.githubusercontent.com/assets/18429104/22600957/75e6cf5e-ea02-11e6-8a02-2a63555a44a4.png)

**Comment by asood123** [comment]
Already a huge improvement. @carlosascari mind adding this to the branch and then we can merge?

**Comment by carlosascari** [comment]
@asood123 looks good. On it

**Comment by carlosascari** [comment]
@asood123 Backgrounds added to `learn-more` branch, please review & merge

**Comment by asood123** [comment]
Merged. Thanks for knocking it out quickly.
