### ISSUE TITLE
Why do we have to CTAs that do the same in Conversations?

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2990]
@raulgrafico Can you look at this as part of your hot fixes? 
What's the difference between them? 

We have two call to actions to start a conversation. I checked and it looks the same in the collective admin view as in the logged out view

<img width="1297" alt="Screen Shot 2020-03-17 at 1 22 29 PM" src="https://user-images.githubusercontent.com/3671070/76877691-8e2ad480-6852-11ea-84c7-3c737046829c.png">

also cc @Betree FYI

**Comment by Memo-Es** [comment]
This issue is solved with the redesign of the Collective page CTA modules. 
For this release, I think it's already being addressed by @sbinlondon

**Comment by sbinlondon** [comment]
I only did that fix in the Contributions section. It was actually the Conversations design that I originally copied, hence the multiple CTAs. I definitely think we should reconsider the redundant CTAs in the other sections as well.

**Comment by Betree** [comment]
Should be resolved by https://github.com/opencollective/opencollective/issues/3220
