### ISSUE TITLE
Replace react-apollo with @apollo/client

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#2994]
## User story 
Since react-apollo is being deprecated ([ref](https://github.com/apollographql/react-apollo#react-apollo)), we should make sure we move to @apollo/client ASAP.
I'm not completely sure how this will affect our codebase but it seems pretty straight-forward in some cases.

## MVP
- [ ] Replace all graphQL hooks with @apollo/react-hooks. 
    - Search for `import { useQuery } from 'react-apollo';` and `import { useMutation } from 'react-apollo';`
- [ ] Replace all graphql high-order-components implementation with @apollo/react-hoc
    - Search for `import { graphql } from 'react-apollo';`
- [ ] Use ApolloProvider from `@apollo/react-components`

**Comment by kewitz** [comment]
@Betree I would like your opinion on this.
@znarf what do you think about this for a bounty?

**Comment by davejon1337** [comment]
can i take this?

**Comment by Betree** [comment]
Seems like the right thing to do.

**Comment by kewitz** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by kewitz** [comment]
🏆 This issue was completed by @davejon1337 

To claim the bounty, you can either:

Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
Or ask for an Open Collective gift card of the same value (to donate to other collectives)
