### ISSUE TITLE
Implement Sentry on the API

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2997]
## User story 
As core developers, rich error reports are tremendously helpful to be notified then easily reproduce and fix issues. We've used Sentry for this purpose on the Frontend and it already caught a bunch of problems that would have been difficult to know about or debug otherwise.

API errors reporting is currently not great, we have good logs but no notifications and incomplete data (ie. we usually don't see which user was impacted by an error in the logs). 

Our current plan with Sentry is enough for us to add a second project (we have been on an average of 2000/100000 events per month for the last 3 months) so we would like to have the API covered.

## Best solution for this problem
Implementation should be simpler for the API because there's no SSR/browser logic to handle. See the following docs for references about Sentry implementation: https://docs.sentry.io/platforms/node/

Ideally, we should cover all crashes:
- GraphQL V1
- GraphQL V2
- Webhooks
- Legacy REST endpoints
- Application crashes

Errors should include:
- User info (id, email, ip)
- Endpoint URL
- Request headers
- Request body (params)

We should also [tag API's releases on Sentry](https://docs.sentry.io/workflow/releases/?platform=javascript).

## MVP
As an MVP we should cover at least GraphQL V1 and V2. We need to make sure that the source maps are made available, we saw with Frontend that it can produce a lot of duplicated issues when they're not.

## Metrics 
- Number of errors detected before being reported by users
- Time saved when investigating

**Comment by cdvx** [comment]
I would like to have a go at this

**Comment by Betree** [comment]
Hi @cdvx, thanks for proposing! Obviously we can't share our Sentry token, but you can create a test app on https://sentry.io/ and add a new `SENTRY_DSN` env variable to make it easy to configure.

**Comment by cdvx** [comment]
Hi @Betree, thanks for the info. I had actually created one, will proceed with it since it is in line with your suggestion.
