### ISSUE TITLE
Updates: clarify the audience target before publishing

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2998]
I've just published a new important update for the allforclimate-uk collective.
https://opencollective.com/allforclimate-uk/updates/we-are-expending-our-expense-policy-to-help-you-organise-online

There are only two backers but 52 contributors (people who have submitted expenses and benefited from the collective).

When I published the update, only the 2 backers got a notification.
All contributors should receive it (and have the option to unsubscribe for future updates with one click)

**Comment by xdamman** [comment]
Looks like all contributors received it (at least one got back to me, can this be confirmed?) but when publishing it says on the interface that only the 2 backers would receive it.

**Comment by bolariin** [comment]
It looks like the notification emails are sent to contributors as well but it looks message before you publish the update only mentions backers.
https://github.com/opencollective/opencollective-frontend/blob/2f5380cccdca01407546f6c5ad23ca11f4392f6f/components/PublishUpdateBtnWithData.js#L53

What would the preferred message be? Should it include both the number of backers and contributors or just number of contributors?

**Comment by xdamman** [comment]
The total numbers of contributors that will receive the email notification

**Comment by xdamman** [comment]
Any update on this?
It's both a frontend and backend issue because it turns out that there is no way to get the total numbers of contributors of a collective via the graphql api (you need to iterate through all `collective.contributors`). And `collective.stats.collectives.all` only returns the sub collectives (collective that have the current collective as a parent).

**Comment by alanna** [comment]
I basically don't use the Updates feature (for host updates) because I can't get a clear picture of who exactly will receive it, so fixing this would be great.

**Comment by Betree** [comment]
Looking at the code for `publishUpdate`, it seems to rely on `collective.getUsers` which fetch all members regardless of their roles. So we should indeed update the wording in the frontend and variable names in the API to stop referring to them as "Financial contributors", and update the corresponding numbers (`This update will be sent to x contributors`) accordingly.

**Comment by Betree** [comment]
This should go with #4064. We need to display a breakdown like:

> Your update will be sent to:
> - 𝑥 direct members
> - the admins of 𝑥 member organizations
> - the admins of 𝑥 hosted collectives

The numbers for "direct members" and "member organizations" should consider all roles (ADMIN, BACKER, CONTRIBUTOR, etc).
