### ISSUE TITLE
Pledges: add Cypress tests

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2999]
We have a feature called "Pledges" where people can pledge to make a contribution to a project/group that is not yet on Open Collective. You can try this feature on https://staging.opencollective.com/pledges/new.

We're not giving it a lot of attention at the moment and we don't have a lot of tests to cover it, so it's difficult for us to know if any change we make can break it. We want to improve this situation by adding a new test file in `test/cypress/integration/36-pledges.test.js` that should follow this structure:

```es6
describe('Pledges', () => {
  describe('Create', () => {
    it('Needs to be logged in', () => {
      // Shows a link to sign in if unauthenticated
    });

    it('Create the pledge', () => {
    });

    it('Joins an existing pledge with another user', () => {
      // Collective page
      // Shows total amount pledged
      // Shows the list of people who pledged
      // Shows the Github URL
    });
  });
});

```

The path to test claiming a collective is not covered by this issue because it probably requires updates to the API to allow bypassing the Github verification. But if you feel inspired, that would be a nice bonus!

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

---

Please follow our [code guidelines](https://docs.opencollective.com/help/developers/best-practices-and-code-guidelines), especially:

* Tests written with Cypress must follow our [good practices](https://docs.opencollective.com/help/developers/testing-with-cypress) conventions.

**Comment by samcaspus** [comment]
Hi @Betree I would like to give it a shot can i be assigned to it.

**Comment by snitin315** [comment]
Can I work on this isuue?

**Comment by yellowwoods12** [comment]
Hi @Betree, I have worked with cypress before and updated tests for Open Collective too. I am confident that I can do it. It will be great if you could assign it to me.

**Comment by Betree** [comment]
@snitin315 @yellowwoods12 sorry @samcaspus was the first one to request the assignment.

Initial time limit to complete this issue is 1 week (this can later be extended if there is demonstrable progress). 

If @samcaspus doesn't complete the bounty in time I'll post a new message to know if you're still interested to work on this.

**Comment by Betree** [comment]
:trophy: This issue has been completed by @samcaspus  

To claim the **$200** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

---

@samcaspus We also added you to https://github.com/orgs/opencollective/teams/contributors/members. **Congrats!** :tada: You can now push directly to most Open Collective repos (only the `master` branches are protected).
