### ISSUE TITLE
Support a column for hostFeePercent

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#30]
Currently, we give 5% to the host for any donation. We need to customize this. Some hosts (like the self-hosted ones) want 0%. Some like WWCode want 10%.

This needs to be done soon to make fees for april easier.

**Comment by xdamman** [comment]
Yep. Just make sure we are consistent with the way we name those columns. It should be `hostFeePercent` (or `hostCommission`?)

**Comment by asood123** [comment]
PR at: https://github.com/OpenCollective/api/pull/282

- [ ] Need to manually populate this column in database after we push to production (@piamancini)

It should be an number between 0 and 100. 5% host fee will be represented with `5`.
