### ISSUE TITLE
Add a slash / when asking for URL of the collective in the create collective flow

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#3000]
![](https://d.pr/free/i/WRQQmG+)

Should be 

![](https://d.pr/free/i/skYNi2+)

Also would be good to auto-suggest based on the name of the collective entered, e.g. in this case: `covid-solidarity`

![](https://d.pr/free/i/8cope8+)

**Comment by cuiki** [comment]
Hi guys, so there is one case where we already designed auto-suggested URLs for collectives, so we should take that lead.

It is in the first version of the **Create Collective** flow that was done about a year ago.
→ https://www.figma.com/file/e71tBo0Sr8J7R5n6iMkqI42d/OC.com-Web-04-Collectives-%E2%86%92-Create?node-id=1019%3A1142

Preview:
![url-auto-suggestion](https://user-images.githubusercontent.com/981188/77435303-c6c53380-6da7-11ea-8029-a564bddc2a9e.png)

However, I'll bring it up in a meeting I'm having with OC Design in a few mins to make sure that we are still ok with that solution or if we are going to update it in some way.
