### ISSUE TITLE
the contributors.svg does not work

### ISSUE THREAD

**Issue by MHuiG** [opencollective/opencollective#3002]
**Describe the bug**
I do not know why this svg does not work:

https://opencollective.com/minivaline/contributors.svg?width=890

**To Reproduce**
1. Go to https://opencollective.com/minivaline/contributors.svg?width=890
2. See error

**Expected behavior**
to show the svg

**Screenshots**
![image](https://user-images.githubusercontent.com/38281581/77288513-f8d88600-6d12-11ea-8c56-a59cc019775c.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome
 - Version 22

**Additional context**
NA

**Comment by znarf** [comment]
Fixed!

**Comment by MHuiG** [comment]
@znarf Thank you!
