### ISSUE TITLE
Open Collective Financial numbers are not up to date

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#3004]
The spreadsheets on the public [drive.opencollective.com](https://drive.opencollective.com) / [Open Data /](https://drive.google.com/drive/folders/1OwRpuIehFQxRnJIRAksQ1Jd2xXZrhz5L) only show the financial data of the company till the end of 2019. 

Can they be updated with numbers from January and February 2020?

There are two files:
- [Open Collective Finances](https://docs.google.com/spreadsheets/d/1uNDoafJyI50o128tjV2HjJGrf8l4bGOorJdSL8qgPyk)
- [Open Collective Numbers](https://docs.google.com/spreadsheets/d/1XG1VGYodr5xxrZWdfr5q5gf3EhN4zpU_7Oa6Z5XI288)

**Comment by znarf** [comment]
Maybe for @piamancini ? Or what is the procedure ?

**Comment by xdamman** [comment]
Any update on this?

January, February and March numbers are not there.
