### ISSUE TITLE
Manipulation error - Need to remove a donation made manually to the wrong collective

### ISSUE THREAD

**Issue by jfdh** [opencollective/opencollective#3008]
**Describe the bug**
I manually added funds to the wrong collective. I can't use the refund option because we do not have a "host collective" on Open Collective Brussels

Could you please just remove this transaction? Thank you in advance.

https://opencollective.com/brusselstogether/orders/68498

Thank you for your help.

JF

**Comment by znarf** [comment]
Done. Let's do that through support next time, GitHub is not the best place for such request!
