### ISSUE TITLE
Primary navigation: Update to latest design

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3009]
:art:  See [latest design on figma](https://www.figma.com/file/9Iq3vBOmZ2EuOacXEYD5yK/DS-05-UI-Organisms?node-id=4%3A0)

## Primary navigation update

<img width="1606" alt="Screen Shot on 2020-03-23 at 22-36-39" src="https://user-images.githubusercontent.com/49539954/77388824-ce102100-6d56-11ea-9623-88e3853cb941.png">

@Betree

**Comment by Betree** [comment]
@Memo-Es thank you, this is looking really good!

Shouldn't there be a cog icon on desktop next to the collective name, similar to what we have today and in the mobile design?

![image](https://user-images.githubusercontent.com/1556356/77411601-f3d01100-6dbc-11ea-839e-5e38d008648b.png)

**Comment by Memo-Es** [comment]
Yes! sorry we forgot to display that... It is visible while hovering

<img width="1031" alt="Screen Shot on 2020-03-24 at 07-48-09" src="https://user-images.githubusercontent.com/49539954/77432702-0c7ffd00-6da4-11ea-8de8-eda308ab716d.png">

**Comment by Betree** [comment]
@Memo-Es Ok I get it now, displayed by default on touch devices (smartphones) but on hover for desktop. Good for me!

**Comment by Betree** [comment]
Extracted the part about updating user menu in https://github.com/opencollective/opencollective/issues/3037 to make the implementation easier

**Comment by SudharakaP** [comment]
Since I am already working on #3037, if that's okay with you guys I'd like to give it a try for this whole issue. :smiley: 

If that's okay, apart from #3037 what other parts are left to do? I suppose the counter in-front of `Manage Contributions` and the small primary nav? Am I missing anything. :smile:

**Comment by Betree** [comment]
@SudharakaP Thanks for joining this one :muscle: Let's solve #3037 first and make a separate for this one. Apart from this first issue, what's left todo is:
- Change search bar and menu links position
- Adapt responsiveness
- Update search bar styles

**Comment by SudharakaP** [comment]
@Betree : Wonderful; thanks for the info. Please feel free to assign those issues to me when you make them. :smile:

**Comment by Betree** [comment]
This issue is actually ready to be tackled, we should iterate as it's a very simple change

**Comment by SudharakaP** [comment]
@Betree : Sorry, I thought those are done in separate issues just like, #3037. Will work on it.

**Comment by Betree** [comment]
@SudharakaP no worry, my comment wasn't targeting you :wink: If you have the time to work on it your contribution would be welcome! What's left to do for this issue is what was described in https://github.com/opencollective/opencollective/issues/3009#issuecomment-618848190

**Comment by SudharakaP** [comment]
@Betree : Thanks. :+1: I'll work on it this week. :smile:

**Comment by SudharakaP** [comment]
@Betree : Done, let me know if you see any issues. :smile: Btw, when following Figma designs do we exactly follow the fonts sizes and stuff or is it based on the overall look and feel. I mean like the amounts do they have to match exactly? :smile:

**Comment by Betree** [comment]
@SudharakaP We try to stick to the design as much as possible. Texts should always match the fontWeight/fontSize/lineHeight from Figma. 

For cards sizes / spacing between items however we allow some differences, especially because we have to deal with responsiveness and have something that looks good on all screen sizes.

**Comment by SudharakaP** [comment]
@Betree : Thanks you for the information. Think I've matched them closely. Let me know if you see anything else to be added.

**Comment by SudharakaP** [comment]
@Betree : Please let me know when design has done the update for the mobile menu. Thanks.

**Comment by Memo-Es** [comment]
### Design update
---

Iteration to place menu buttons at the corner

<img width="527" alt="Screen Shot on 2020-08-05 at 12-42-02" src="https://user-images.githubusercontent.com/49539954/89445811-403b3e00-d719-11ea-8977-ada46ecdb6a1.png">


:art:  See [latest design on figma](https://www.figma.com/file/9Iq3vBOmZ2EuOacXEYD5yK/DS-05-UI-Organisms?node-id=4%3A0)

@Betree

**Comment by SudharakaP** [comment]
@Betree : Done; let me know if you see any issues with the mobile menu. 😄
