### ISSUE TITLE
Transactions page: filters overlap mobile menu 

### ISSUE THREAD

**Issue by snitin315** [opencollective/opencollective#3010]
**Describe the bug**

**To Reproduce**
1. Go to `/user/transactions`
2. Switch to mobile view
3. click on `dropdown icon`

**Expected behavior**

The dropdown should not be behind the tabbed navigation.

**Screenshots**

![Screenshot from 2020-03-26 07-58-44](https://user-images.githubusercontent.com/46647141/77604086-ad52f180-6f37-11ea-8d76-61b0a4e93956.png)

![Screenshot from 2020-03-26 07-58-52](https://user-images.githubusercontent.com/46647141/77604092-af1cb500-6f37-11ea-9cf9-15184817c4d8.png)

**Smartphone (please complete the following information):**
 - Device: All

**Additional context**

I will work on this issue.

**Comment by Betree** [comment]
Thanks for documenting this issue @snitin315

**Comment by MlkMahmud** [comment]
Hi @snitin315,  are you working on this already?

**Comment by snitin315** [comment]
You can work on this ig you want to.

**Comment by MlkMahmud** [comment]
Hello @Betree can I work on this?

**Comment by snitin315** [comment]
Yes you can

**Comment by Betree** [comment]
@MlkMahmud you're assigned! Let me know if you need more info.
