### ISSUE TITLE
Reorganize Host Settings

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3012]
This is related to: https://github.com/opencollective/opencollective/issues/2665

We're trying to separate Host Settings from other settings. This is valid when editing any Organization or User.

This work is mostly about moving settings that are already existing.

**User or Organizations (that ARE NOT yet hosts) should now see:**

```
...
Webhooks
Advanced

Fiscal Hosting
 - Activate (moved from advanced)
```

**User or Organizations (that ARE hosts) should see:**

```
...
Webhooks
Advanced

Fiscal Hosting
  - Enable Applications (moved from advanced)
  - Host fee (moved from advanced)
  - Terms of Fiscal Sponsorship (moved from info, was named Terms of service)
  - Deactivate (moved from advanced)
Host Plan
  - Same as existing
Expenses & Payouts
  - Expense Policy (same as existing)
Invoices & Receipts
  - Same as Existing
Receiving Money
 - Connect Stripe (moved from Connected Accounts)
 - Bank Transfers (moved from Payment Methods)
   - BONUS: Users should be able to delete Bank Transfers settings
Sending Money
 - PayPal: for now, just explain that PayPal is activated by default
 - Transferwise (moved from Connected Accounts)
```

**Comment by znarf** [comment]
A $500 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $500 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md).

**Comment by snitin315** [comment]
Can I work om this issue?

**Comment by znarf** [comment]
@snitin315 Have you already contributed to our code base? As medium complexity, it's normally reserved to Past Contributors (at least 1 completed issue).

**Comment by jeffin143** [comment]
@znarf , Could I be considered as second preference for the bounty to be assigned.

**Comment by snitin315** [comment]
@jeffin143 , you can go ahead with this one , meantime I will solve some issues to get myself familiarized with he codebase.

**Comment by znarf** [comment]
Good luck @jeffin143 ! Let's set 1 week from now to see significant progress. Don't hesitate to break it in multiple PRs.

**Comment by znarf** [comment]
🏆 This issue was completed by @jeffin143 

To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

NOTE: I would still appreciate if you could tackle my last minute feedback from: https://github.com/opencollective/opencollective-frontend/pull/3794#issuecomment-608336796 It's difficult to understand the components in this state.

**Comment by jeffin143** [comment]
>NOTE: I would still appreciate if you could tackle my last minute feedback from: opencollective/opencollective-frontend#3794 (comment) It's difficult to understand the components in this state.

I will definitely handle this :)
