### ISSUE TITLE
notNull Violation: Tier.name cannot be null, Validation error: In undefined's tier, "Amount" is required

### ISSUE THREAD

**Issue by KorbiZac** [opencollective/opencollective#3016]
**Describe the bug**
I got this issue when i pressed save but it was saved when i realoded the page
![grafik](https://user-images.githubusercontent.com/62755796/77764853-9f879400-703d-11ea-8b4a-5797acf155fc.png)

**To Reproduce**
1. Go to 'edit profil'
2. Click on 'save'
3. Scroll down to 'bottom'

**Comment by Betree** [comment]
Hi @KorbiZac, we've fixed it in https://github.com/opencollective/opencollective/issues/3014. The deploy is on its way.

**Comment by Betree** [comment]
Fix deployed, sorry for the issue and thanks for reporting it :pray:
