### ISSUE TITLE
Show the amount and interval on Tier buttons

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#302]
Currently, we say "Become a backer" or "Become a sponsor" on green buttons. This leads to confusion sometimes as users aren't always sure if they are committing to monthly.

It's better to show the amount (and whether it's monthly) on the button like opencollective.com/brusselstogether. 

This will reduce inadvertent subscription signups (and then cancellations).

Is there an easy way to flip all the tiers to show this instead?

**Comment by piamancini** [comment]
obsolete because of v2
