### ISSUE TITLE
opencollective.com is blocked in Ukraine

### ISSUE THREAD

**Issue by misuzu** [opencollective/opencollective#3026]
**Describe the bug**
`opencollective.com` is using the same IP address as `vipnetgame.com` which is [blocked in Ukraine](https://nkrzi.gov.ua/index.php?r=site/index&pg=99&id=1870&language=uk).

```
~ > host opencollective.com
opencollective.com has address 104.26.12.145
opencollective.com has address 104.26.13.145
opencollective.com has IPv6 address 2606:4700:20::681a:c91
opencollective.com has IPv6 address 2606:4700:20::681a:d91
opencollective.com mail is handled by 5 alt1.aspmx.l.google.com.
opencollective.com mail is handled by 10 alt3.aspmx.l.google.com.
opencollective.com mail is handled by 10 alt4.aspmx.l.google.com.
opencollective.com mail is handled by 1 aspmx.l.google.com.
opencollective.com mail is handled by 5 alt2.aspmx.l.google.com.
~ > host vipnetgame.com
vipnetgame.com has address 104.26.13.145
vipnetgame.com has address 104.26.12.145
vipnetgame.com has IPv6 address 2606:4700:20::681a:c91
vipnetgame.com has IPv6 address 2606:4700:20::681a:d91
vipnetgame.com mail is handled by 10 ntgmail.net
```

**Comment by znarf** [comment]
This is a Cloudflare IP address, this means many many websites are being blocked because of this rule. Is this really how websites are being blocked in Ukraine?

**Comment by misuzu** [comment]
> This is a Cloudflare IP address, this means many many websites are being blocked because of this rule. Is this really how websites are being blocked in Ukraine?

Some ISP's are blocking by IP, unfortunately.

**Comment by znarf** [comment]
Would be great to setup some alternatives addresses, like an .onion address.

**Comment by znarf** [comment]
@misuzu What's your ISP by the way?

**Comment by misuzu** [comment]
> @misuzu What's your ISP by the way?

Triolan. It's in top 5 by subscribers count.

**Comment by znarf** [comment]
@misuzu What's the update on this?

**Comment by misuzu** [comment]
> @misuzu What's the update on this?

Nothing has changed so far.

**Comment by misuzu** [comment]
It's probably even worse now. Seems like Volia started blocking those addresses too.
https://atlas.ripe.net/measurements/25209794/#!probes

**Comment by nop1984** [comment]
I confirm such problem exists and now getting in touch with our UA providers to get unblocking.

**Comment by nop1984** [comment]
Have emailed to ISP next, will try to track how it goes:

> блокування сайту https://opencollective.com/ дуже ймовірно є безпідставним. OpenCollective є краудфаундінговою платформою для Open Source проектів, а також надає послуги фіскального хостингу. Зокрема через нього фінансуються такі відомі проекти як PhalconPHP, Babel, WebPack, Material-UI, Vue, Bower.
> Сайт відкривається з мобільного інтернету ВодаФон, тим паче заблокований у кількох провайдерів України https://github.com/opencollective/opencollective/issues/3026
> Цим сайтом планую користуватися і я. У зв'язку з чим прошу його розблокувати. Це потенціно корисний і унікальний сервіс, особливо для Україноського ІТ в умовах ізоляції через санкції OFAC від таких сервісів як Stripe та PayPal.

**Comment by misuzu** [comment]
`vipnetgame.com` changed it's IP addresses and `opencollective.com` is working again!
