### ISSUE TITLE
Edit Form Validation broken 

### ISSUE THREAD

**Issue by jeffin143** [opencollective/opencollective#3027]
**Describe the bug**
Edit settings  in organisation give validation error when you try to save address or TOS 

**To Reproduce**
1. Go to any ORG
2. Click on INFO
3. Scroll down to address or TOS and edit it

**Expected behavior**
No error and should save normally 

**Screenshots**
<img width="1428" alt="Screenshot 2020-03-31 at 1 30 57 AM" src="https://user-images.githubusercontent.com/21286134/77956462-8b6abd80-72ef-11ea-9eea-4a763c5dcc80.png">

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser : chrome
 - Version : irrelevant  

**Additional context**
Found while testing for the comment -  https://github.com/opencollective/opencollective-frontend/pull/3794#pullrequestreview-384003388

Possible duplicate of #2953 , But Something different in case of ORG

**Comment by znarf** [comment]
Can you try to update the API? This has been fixed.

**Comment by jeffin143** [comment]
> Can you try to update the API? This has been fixed.

Thanks, will just do it and close it if resolved

**Comment by jeffin143** [comment]
Work smooth :)
