### ISSUE TITLE
New fields in Export Members.csv

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#303]
Currently, we only give totalDonations. Also need to add, how many times that person has donated.

Or maybe a better split is by individual donation (and subscription) and summing all transactions for that user under 'totalDonations'.

Feedback from @mfc

**Comment by louh** [comment]
Hey! I had a similar request. What would be really useful for me right now is a field that tells me if a user is a monthly donor, or a one-time donor. For monthly donors, what is their monthly amount?

**Comment by piamancini** [comment]
We still need to work on this.

**Comment by piamancini** [comment]
new export CSV has active members and frequency.
