### ISSUE TITLE
Expense Test: wrong assertion

### ISSUE THREAD

**Issue by snitin315** [opencollective/opencollective#3032]
**Describe the bug**

There is a wrong assertion in [`Expenses.test.js#L83](https://github.com/opencollective/opencollective-frontend/blob/59e04ed9dedb72b27a047e0a8e21e547fc27e0d8/components/expenses/__tests__/Expenses.test.js#L83)

~~it should be `length` not `length`~~  it should be `length` not **`lenght`.**

### [Bug found here](https://github.com/opencollective/opencollective-frontend/pull/3736#discussion_r394918821) 

**To Reproduce**
1. Go to [`Expenses.test.js#L83](https://github.com/opencollective/opencollective-frontend/blob/59e04ed9dedb72b27a047e0a8e21e547fc27e0d8/components/expenses/__tests__/Expenses.test.js#L83)

2. See error

**Expected behavior**

it should not be `lenght`.

**Additional context**

I will take a look into it.

**Comment by Betree** [comment]
> it should be length not length.

=> it should be length not lenght.

Good catch. We probably need to do `toEqual(0);` also.
