### ISSUE TITLE
Design for 'Create Organization on the Fly' instance

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3033]
🎨 See latest design on [figma](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=2375%3A2)

There are a couple of places in the platform, generally inside a flow (e.g., Add funds, start accepting financial contributions) where you are prompted to create an organization 'on the fly.'

See #2713 and https://github.com/opencollective/opencollective-frontend/pull/3247

In the current create collective flow redesign its needed when selecting your organization as funds holder. So we are revamping that instance platform-wide.

Status: Design ready for implementation

@Betree  @alanna

**Comment by Memo-Es** [comment]
Finished design already on [implementation](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=2375%3A2)

I think @sbinlondon it's going to implement this during the 'Start accepting financial contributions flow' @Betree

**Comment by Betree** [comment]
@sbinlondon can you estimate the complexity and add the corresponding label? I think you can re-use most of the things you did for CCF, for example the component to add admins?

![image](https://user-images.githubusercontent.com/1556356/78878792-3fd4b400-7a53-11ea-8dd1-42627814310f.png)

**Comment by Memo-Es** [comment]
Closing this because it's being implemented here #3468
