### ISSUE TITLE
Unable to edit a Collective's info if no tiers are attached to it

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3034]
**Describe the bug**

Collectives created with the new Create Collective Flow are created without any default tiers (unlike the old create flow).

However, if you go and try to edit that Collective's information on the settings page, you run into an error about tiers.

<img width="998" alt="Screenshot 2020-04-01 at 19 04 36" src="https://user-images.githubusercontent.com/37520401/78171138-f03b2a80-744b-11ea-9bb9-b8e4475ea414.png">

It appears that if a Collective does not have tiers, you are unable to edit it.

**To Reproduce**
1. Go to opencollective.com/create (or staging)
2. Create a collective using the new create flow
3. Go to the settings and try to add a website, for example
4. Click save
5. See error about tiers

**Expected behavior**
I expect to be able to edit the Collective info without having to worry about tiers

**Screenshots**
See above

**Additional context**
 Spoke to @kewitz and it's suggested we do one of two things:

1. Add some default tiers to the create flow
2. Add a check in the editCollective mutation to check if there are tiers or not

**Comment by znarf** [comment]
@sbinlondon @kewitz We need to 2) because we need to take care of the Collectives that were created in the meantime. It's curious that no one complained about the issue though. Wasn't that solved in https://github.com/opencollective/opencollective-api/pull/3598 ?

We should also do 1) and replicate the behavior that was there before.

**Comment by kewitz** [comment]
@znarf I don't think opencollective/opencollective-api#3598 hast anything to do with this.
This is a new edge-case that was discovered because the new create collective mutation doesn't create default tiers.
I'm adding this new edge-case just to be sure.

**Comment by znarf** [comment]
Update: Tiers creation was not changed in the CCF, It's handled here https://github.com/opencollective/opencollective-api/blob/master/server/models/Collective.js#L1657

**Comment by znarf** [comment]
@kewitz Might still be related, the regression being the same. https://github.com/opencollective/opencollective-frontend/pull/3630/files#diff-a24a56b7f34652e27e424c18037c2e33R78

**Comment by kewitz** [comment]
@znarf found it:
https://github.com/opencollective/opencollective-frontend/pull/3630/files#diff-a24a56b7f34652e27e424c18037c2e33R78-R79

**Comment by jeffin143** [comment]
Happen with create

<img width="1636" alt="Screenshot 2020-04-02 at 9 45 23 AM" src="https://user-images.githubusercontent.com/21286134/78210105-b3604980-74c6-11ea-9cc5-d99ffd589d89.png">
Event flow also
