### ISSUE TITLE
JupyterLab: inactive tabs are not correctly inverted in dark mode.

### ISSUE THREAD

**Issue by kamenevdn** [opencollective/opencollective#3035]
**Describe the bug**
If several tabs are open in JupyterLab, inactive tabs are not properly inverted with dark dynamic filter.

**Screenshots**
Appearance:
![chrome_IXsMvs0sin](https://user-images.githubusercontent.com/54708166/78230013-72bdfb80-74d9-11ea-96c7-9d64b47a7663.png)
Settings:
![GVMZYMH5b1](https://user-images.githubusercontent.com/54708166/78230196-b0bb1f80-74d9-11ea-8ec3-ae8a164c18a8.png)
![wMa9JWLsLY](https://user-images.githubusercontent.com/54708166/78230208-b6186a00-74d9-11ea-955c-70f5d06a9a52.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Version: 80.0.3987.149

**Comment by davejon1337** [comment]
Wrong repository.
