### ISSUE TITLE
Update design for user menu

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3037]
Part of https://github.com/opencollective/opencollective/issues/3009
:art:  See [latest design on figma](https://www.figma.com/file/9Iq3vBOmZ2EuOacXEYD5yK/DS-05-UI-Organisms?node-id=4%3A0)

This issue is about updating the design for the user menu that appears when you click on your profile picture. Some more details:
- The cog settings icon appears on hover on desktop, but is always displayed on mobile
- The collective/organizatiopns list must have a max-height and be scrollable
- You don't have to implement the count (`14`) next to `Manage contributions` (we'll create a new issue for that), but feel free to give it a try if you feel inspired!

Some components that may help you:
- `StyledRoundButton`
- `StyledHr`
- `Avatar`
- `components/Text`
- `@rebass/grid`

<img width="1031" alt="Screen Shot on 2020-03-24 at 07-48-09" src="https://user-images.githubusercontent.com/49539954/77432702-0c7ffd00-6da4-11ea-8de8-eda308ab716d.png">

<img width="1606" alt="Screen Shot on 2020-03-23 at 22-36-39" src="https://user-images.githubusercontent.com/49539954/77388824-ce102100-6d56-11ea-9623-88e3853cb941.png">

**Comment by SudharakaP** [comment]
@Betree : I would like to give it a try at this one. Feel free to assign it to me if nobody else is working on it. :smile:

**Comment by Betree** [comment]
Sure @SudharakaP, let me know if you need anything

**Comment by SudharakaP** [comment]
> Sure @SudharakaP, let me know if you need anything

Thanks much. I am sure I'll have a bunch of questions. I have done a preliminary PR. I am not sure all the guidelines you guys follow or if I have done exactly as expected. Take a look and if there's anything I need to improve feel free to let me know. :smile:
