### ISSUE TITLE
Rename ExpenseAttachments to ExpenseItems

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3039]
With https://github.com/opencollective/opencollective/issues/3022#issuecomment-608317258 we're introducing a new `ExpenseAttachedFiles` table to store additional file that don't have an amount/description/date/... attached to an expense.

To avoid the confusion between `ExpenseAttachedFiles` and `ExpenseAttachments`, I'd like to rename the second to `ExpenseItem`. This includes:
- [ ] Renaming the table
- [ ] Renaming the model
- [ ] Renaming the GraphQL endpoint
- [ ] Renaming the frontend components

I'd like to move forward with this before we make the feature public, so please share your feedback as soon as possible if you have any.

**Comment by znarf** [comment]
Good for me.

1. Will there be breaking changes for frontend if not migrated?
2. Does it impacts old features?
3. Does this mean we have to deploy API and frontend at the same time?

**Comment by Betree** [comment]
> Will there be breaking changes for frontend if not migrated?

We can avoid breaking changes for V1 by deprecating the existing graphql fields (`attachments`) rather than removing them because in V1 attachments are just an array of strings.

For V2 however the change in type name will be breaking.

> Does it impacts old features?

Yes, the old expense flow and host dashboard are already using the `attachments` fields. 

> Does this mean we have to deploy API and frontend at the same time?

Yes, we'll have to
