### ISSUE TITLE
History page for all your donations

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#304]
Currently, we have /subscriptions that shows you all subscriptions (and transactions for each of those subscriptions).

It means that people can't get invoices for one-time donations. We need a /history page that can show you all your transactions with a link to the invoice. 

@erickrico can you share a quick design for it? Here's what subscriptions looks like right now:

![image](https://cloud.githubusercontent.com/assets/6106941/22399933/f9a0bdf0-e575-11e6-814e-b058bfb286c3.png)

![image](https://cloud.githubusercontent.com/assets/6106941/22399939/11b3c892-e576-11e6-8668-b882221dd653.png)

**Comment by piamancini** [comment]
@asood123 is this fixed?
