### ISSUE TITLE
Rename "Sub-collectives" to "Connected collectives"

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3040]
The notion introduced in https://github.com/opencollective/opencollective/issues/2633 has created a lot of confusion among users, who have a hard time understanding how that relates to fiscal hosts.

We took the decision to rename them to "Related collectives". We need to update:
- [x] All Members entries that have the `SUBCOLLECTIVE` type
- [x] Places in the code where we use this variable name
- [x] Update the query in https://docs.opencollective.com/help/internal/queries/subcollective-queries#create-a-subcollective

**Comment by SudharakaP** [comment]
@Betree : I can take this issue. Just to clarify a could you explain a bit about what you mean by "Members entries"? :smile:

**Comment by SudharakaP** [comment]
@Betree : Done. Let me know if you see any issues or further alterations needs to be done. :smile:

**Comment by Betree** [comment]
"Members entries" refers to all the entries for the `Members` table in the database. We need to create a migration to update their type.

**Comment by Betree** [comment]
@piamancini I just noticed that we have a lot of occurrences in the code for `relatedCollectives`, we use this term in all places where we suggest similar collectives to support. 

I think the other proposal, `ConnectedCollectives`, would prevent any confusion because it's a term that doesn't exist yet in our codebase.

**Comment by SudharakaP** [comment]
@Betree : I've done the migration as well let me know if you see any issues. :smile:

**Comment by Betree** [comment]
Got the feedback from @piamancini, she's ok to use "ConnectedCollectives"

**Comment by SudharakaP** [comment]
@Betree : I've renamed everything to `connected collective`. Let me know if there's anything further to be done.
