### ISSUE TITLE
How to add Github contributors to a collective?

### ISSUE THREAD

**Issue by akkefa** [opencollective/opencollective#3041]
On other projects, I saw a list of Github contributors listed on the bottom too.

Can we add that to https://opencollective.com/urduhack as well?
We have the organization https://github.com/urduhack.

**Comment by akkefa** [comment]
FYI : https://github.com/OpenCollective/OpenCollective/issues/282

**Comment by znarf** [comment]
I'm curious, can you link to the other projects having that?

The issue you shared is 3 years old and as far as I know we're not doing that anymore.

**Comment by znarf** [comment]
@akkefa Could you answer? We'll close the issue if no further activity.

**Comment by akkefa** [comment]
@znarf you can close this issue.
