### ISSUE TITLE
New expense flow: form not expanded after reloading

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3045]
**Describe the bug**
When you pick an expense type and reload the page, the type is still selected but the form is not expended.

**To Reproduce**
1. Go to https://staging.opencollective.com/engineering/expenses/new/v2
2. Click on Invoice
3. Reload the page
4. Form is not there, you need to make a change to the type to see it appear

**Expected behavior**
Form should be there after reloading the page

**Screenshots**
![image](https://user-images.githubusercontent.com/1556356/78893328-78808780-7a6b-11ea-94d7-7967870d1644.png)

**Comment by SudharakaP** [comment]
@Betree : I would like to work on this issue if that's fine. Please feel free to assign it to me. :smile:

**Comment by SudharakaP** [comment]
I wonder if this has to do with [Zeit caching](https://zeit.co/docs/v2/network/caching). If we try to recreate this on local, the radio button is not selected upon page refresh; but on staging it seem to be selected. :thinking: :thinking: 

![Peek 2020-04-18 11-38](https://user-images.githubusercontent.com/12435965/79661952-4c4ec000-8169-11ea-84df-0ffb30523aaa.gif)

**Comment by Betree** [comment]
I was able to reproduce on both Firefox & Chrome. It happens when you select one of the two options before the logged in user is loaded (in other words, when there's still a spinner on the top right button).

Network throttling is helpful to reproduce this issue:
![image](https://user-images.githubusercontent.com/1556356/79758500-c58f1400-831d-11ea-9a67-07234f0247e8.png)

**Comment by SudharakaP** [comment]
@Betree : Thanks; managed to recreate the issue using the network throttle. I think this can be solved in different ways. My thinking is before the user loads not showing the expense form (put the placeholder until the user loads); as probably we don't want to show the expense form anyways if the user didn't load. I've done a pull request with this minor change. Let me know if you have a better idea or any changes needs to be done. :thinking:

**Comment by Betree** [comment]
@SudharakaP makes sense, that's a good & simple way to fix this!

**Comment by Betree** [comment]
@SudharakaP Thank you for solving this one!

We added you to https://github.com/orgs/opencollective/teams/contributors/members. **Congrats!** :tada: You can now push directly to most Open Collective repos (only the `master` branches are protected).

**Comment by SudharakaP** [comment]
@Betree : You are welcome; and thanks for adding me. :smile:
