### ISSUE TITLE
Expense redesign layout enhancements

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3046]
**Context:**
We are undertaking a series of exercises platform-wide to ensure consistency, better UX practices, and a more complete design knowledge-base to make new and old issues easier to tackle.
One of the most important aspects of this process is to institutionalize the layouts we use across the platform since it is the foundation blocks upon which we design pretty much everything.

While doing this layout exercise for expenses lead by @cuiki , based on the current redesign, we realized that some improvements were necessary to move forward with some apparently simple issues like the pay button positioning for hosts.

These improvements are based on the following premise:
**Information and actions have to be in the correct context within the layout; if that's covered, then the next criteria is consistency.**

| Enhancement  | Thinking |
| ------------- | ------------- |
| <img width="1868" alt="Annotation on 2020-04-09 at 08-05-09" src="https://user-images.githubusercontent.com/49539954/78898103-de075080-7a38-11ea-8179-3c22fd8ea858.png">  | There should be a clear difference between the info you interact with and the supporting info that helps you during the submission. 
|  <img width="661" alt="Screen Shot on 2020-04-09 at 08-15-27" src="https://user-images.githubusercontent.com/49539954/78898974-515d9200-7a3a-11ea-947d-895ceced674f.png">  | We are also using a container to improve readability and help the user contextualize the edition space faster 
| <img width="1868" alt="Annotation on 2020-04-09 at 07-56-53" src="https://user-images.githubusercontent.com/49539954/78897420-c24f7a80-7a37-11ea-8129-b8da52f956dc.png"> | Tags are tied to the expense title, inside the edition space |
| <img width="1868" alt="Annotation on 2020-04-09 at 08-43-25" src="https://user-images.githubusercontent.com/49539954/78901697-56244500-7a3e-11ea-89ec-83bc213ddb77.png"> | We are alligning currency info to improve the page order and structure |
| <img width="1868" alt="Annotation on 2020-04-09 at 08-17-38" src="https://user-images.githubusercontent.com/49539954/78899292-c6c96280-7a3a-11ea-9c4d-7f3b58fb3601.png"> | We changed the add element button to an already existing "add" button used in other parts of the platform like the user menu dropdown |

I confirmed with @Betree the technical viability of these enhancements and they won't delay the release date more than a day.

**Comment by Betree** [comment]
I personally like these changes, I think they create a better information hierarchy.

The only thing that could cause issues is the tags input that is still using the old design in our codebase, but I think @kewitz was about to start looking at it?

The rest of the redesign should indeed take less than a day.

**Comment by cuiki** [comment]
Nice! I'm wrapping up some other design details particularly for the expense summary view and the expense management (approve, reject, etc.) later today.

**Comment by Memo-Es** [comment]
### Update - Expense Summary

| Enhancement  | Thinking |
| ------------- | ------------- |
| <img width="1408" alt="Annotation on 2020-04-13 at 21-31-45" src="https://user-images.githubusercontent.com/49539954/79179935-5d48ab80-7dce-11ea-8b4f-2428597c1fb8.png">  | In the expense summary we made a clear division between what is the info the user has just filled and the payee info, making clear the information that's private

@Betree

**Comment by kewitz** [comment]
Yes @Betree, I'll update the tags picker this week!

**Comment by Betree** [comment]
All done
