### ISSUE TITLE
Remove timestamp from schema.graphql

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3047]
## Problem

In `schema.graphql` and `schemaV2.graphql`, a timestamp is autogenerated at the top as a comment:

```gql
# timestamp: Tue Apr 07 2020 17:48:50 GMT+0200 (GMT+02:00)
```

This creates a lot of unnecessary conflicts where the schemas are perfectly mergeable but this line is not, which means more developer time spent on solving these conflicts, rebasing & waiting for CI to pass again.

## Proposal

Either remove the timestamp line, or replace it with a fixed value in the scripts that generate the file.

**Comment by kewitz** [comment]
I think we can remove, there's always git blame and log if we want to fetch that information.

**Comment by sbinlondon** [comment]
Yes please, this is a headache every time 🙏

**Comment by znarf** [comment]
I was looking a bit at `graphql-cli` and `get-schema` is gonna be deprecated in the next version.

I also looked at https://github.com/prisma-labs/get-graphql-schema which is simple but doesn't read information from our `.graphqlconfig`.

**Comment by Betree** [comment]
@znarf Is the `.graphqlconfig` used by other scripts than the ones to export schema?

**Comment by znarf** [comment]
@Betree not at the moment

**Comment by Betree** [comment]
https://github.com/prisma-labs/get-graphql-schema looks pretty good to me then.

Just to mention it because it's kind of related, I recently discovered https://github.com/kamilkisiela/graphql-inspector - a CI job to enforce good GraphQL practices (like deprecating fields before removing them). It works by comparing old schema and new schema. There's also an helper to find fields usage in the application (useful to know if they're safe to delete).
