### ISSUE TITLE
Deprecate app.opencollective.com

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#305]
Remaining tasks
- [x] Support add funds from website (relatively easy, but need to update backend to create donation as well. Right now, super old code only creates a transaction)
- [x] Support fetching preapproval key and getting a new preapproval from Paypal
- [ ] Show payout method on website and allow editing it
- [x] Connect stripe (lower priority)
- [ ] Show a dashboard where a HOST can see all their collectives and outstanding tasks like approving expenses

Note: connecting PayPal from website is same thing is getting a new preapproval key

**Comment by piamancini** [comment]
Dashboard still needed.
