### ISSUE TITLE
Download invoices button text not aligned

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3052]
Maybe related to https://github.com/opencollective/opencollective-frontend/pull/3804

![image](https://user-images.githubusercontent.com/1556356/78982242-0323be00-7b22-11ea-868b-dd5f77c82a8f.png)

**Comment by snitin315** [comment]
Can I take this up?

**Comment by Betree** [comment]
@snitin315 sure! You can access this page by going to your personal profile > Transactions section. 

We need to remove the  `height` on the component (that prop is automatically set by `buttonSize`. If the button is too big we may consider using `buttonSize="tiny"`.

Let me know if you need more info.

**Comment by snitin315** [comment]
@Betree Thanks for the info.

**Comment by Betree** [comment]
@snitin315 I have another fix to send for the same part of the code, if you haven't started working on it let me know. The fix is just to remove the height

**Comment by snitin315** [comment]
You can send the fix. I haven't started yet.
