### ISSUE TITLE
Post comments on updates

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3053]
## User story 
As a contributor, I can comment on collective updates.

This feature has been discussed many times, but we never created an issue for it. 

## Best solution for this problem
- There should be a button in emails like "React to this update"
- Ideally the design for the page should match what we have with conversations and the new expense flow. 

## MVP
The MVP for this is to re-use the `Thread` and `CommentForm` components for updates on the existing page. We already have an `UpdateId` column for comments, so it should be fairly easy on the API side. 

## Metrics 
- Number of comments on updates
- Number of updates created (this change may incentive collectives to use the feature)

**Comment by xdamman** [comment]
Would be great to also have simple reactions so that people can click react with a predefined emoji (👍🎉❤️👋🙌) with just one click from the email notification.

**Comment by Betree** [comment]
@xdamman => https://github.com/opencollective/opencollective/issues/3059

**Comment by alanna** [comment]
Can we use the expense comment system for this? And if it's straightforward to do that, maybe it could be a bounty?

**Comment by Betree** [comment]
> Can we use the expense comment system for this?

We can, the specs for the MVP above are about re-using the existing comment system.

> maybe it could be a bounty?

I'm not comfortable with putting a bounty on this one, I'm afraid it would require too much feedback

**Comment by SudharakaP** [comment]
@Betree : Can take this up if you have no objection? 😄

**Comment by Betree** [comment]
@SudharakaP Sure!

**Comment by SudharakaP** [comment]
@Betree : I have submitted both of the PRs and they are ready to be reviewed. Thanks. 😄

**Comment by Betree** [comment]
After merging the implementation of this feature, we should create an issue about adding a checkbox to make it optional (default: true):
> [ ] Enable comments for this update

**Comment by SudharakaP** [comment]
@Betree : Should we close this issue as I think the functionality has been added or is there anything more to be done here? 😃

**Comment by Betree** [comment]
@SudharakaP Definitely, thanks for your work on this!
