### ISSUE TITLE
Expense redesign - Pay button set placement

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3054]
**Addressing:** #2936 

As stated in #3046 we needed to define a basic set of layouts to deal with the new expense redesign in order to ensure consistency and good UX practices, one of the most important issues that make this work necessary was the decision around the pay button set of the old expense pay design, a.k.a. 'The Christmas tree'.

In the expense layout enhancement issue #2936 we established as the top criteria the importance of having the info contextualized to ease the cognitive weight inherent in dealing with expenses.

The following screen explains the design approach to the pay button placement decision:

| Enhancement  | Thinking |
| ------------- | ------------- |
| <img width="1408" alt="Annotation on 2020-04-13 at 21-49-55" src="https://user-images.githubusercontent.com/49539954/79180911-be717e80-7dd0-11ea-9fdf-72c5b563b5a7.png"> | Now the separation of data and information that the user needs to understand and interact with (Cognitive load) is divided clearly with the new layout design. There is the space where the info of the expense is contained, and after you read it admins have the option to interact with the expense by changing its status or paying it. 
| | Plus, the other actions you can perform are in different contexts because they have to do with different types of actions and mental processes.

@Betree @piamancini @cuiki

**Comment by Memo-Es** [comment]
**Addressing the different cases stated in #2936 **

| Pending  | Approved | Rejected |
| ------------- | ------------- | ------------- |
| ![Pending](https://user-images.githubusercontent.com/49539954/79823386-49b2bd00-8359-11ea-9b07-0dad7706fac5.png) | ![Approved](https://user-images.githubusercontent.com/49539954/79823380-47506300-8359-11ea-8f9e-c2f08d1a2c70.png) | ![Rejected](https://user-images.githubusercontent.com/49539954/79823389-4a4b5380-8359-11ea-9cad-3863705ed447.png) 

| Error  | Paid | Processing |
| ------------- | ------------- | ------------- |
|![Error](https://user-images.githubusercontent.com/49539954/79823382-48819000-8359-11ea-942f-00fa7b0360ad.png) | ![Paid](https://user-images.githubusercontent.com/49539954/79823385-491a2680-8359-11ea-8276-a69fdd8b99e5.png) | ![Processing](https://user-images.githubusercontent.com/49539954/79823387-49b2bd00-8359-11ea-9350-00580d5dbd8c.png) 

🎨[Link to the figma file](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=2445%3A358)

**Comment by Betree** [comment]
@Memo-Es perfect! Is there a production-ready file for the behavior of the `Pay` button?

**Comment by Memo-Es** [comment]
**Update**

We are using 3 different Pay buttons depending on the payout method of the expense 

<img width="213" alt="Screen Shot on 2020-04-21 at 12-29-53" src="https://user-images.githubusercontent.com/49539954/79895598-c29f2c80-83cc-11ea-91e5-bd6d452db0cd.png">
