### ISSUE TITLE
Updates of the host should be sent to all admins of the hosted collectives

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#3058]
As a host I want an easy way to reach out to all the hosted collectives.

Now that organisations can have Updates (#2914), this would be the perfect way to do that. We just need to make sure that new updates are by default sent to all the admins of the hosted collectives (they can of course opt out).

**Comment by xdamman** [comment]
Related: #2314

**Comment by znarf** [comment]
We will track that in https://github.com/opencollective/opencollective/issues/2314
