### ISSUE TITLE
Participation in Google Season of Docs 2020

### ISSUE THREAD

**Issue by jaskirat2000** [opencollective/opencollective#3065]
Hi Team!
Open Collective was a part of **Google Season of Docs 2019** program where **me (@jaskirat2000)**  and **Alanna (@alanna )** was the organization administrators and successfully completed under it; revamping Open Collective documentation by **@contraexemplo (Google Season of Docs aspirant under Open Collective)**

FYI, **[Google Season of Docs](https://developers.google.com/season-of-docs)** is a global program which encourages technical writers to gain exposure to documentations of real-world open-source project scenarios either by building a new documentation set, or redesigning the existing docs or improving and documenting the open-source community's contribution procedures and onboarding experience to transmute their technical skills to greater levels.

So hereby I am pledging the participation of Open Collective community again in the Google Season of Docs 2020. Organization Application has already started and is accepted until May 4, 2020.
We would be needing two administrators again this year internally to lead this up, I am happy to make it move forward again this year.
Please let me know if you are still interested because we would be asked to draft the application, set up an idea page and call for volunteers.
cc @znarf @alanna @piamancini @Betree

**Comment by contraexemplo** [comment]
As I mentioned in private conversations, I'd be open to mentor another technical writer. Maybe someone with more expertise in development that could help the Engineering team to revamp their documentation as I'm more focused on maintenance tasks (keeping things up to date on an end-user level)?

**Comment by Betree** [comment]
One topic that could be interesting to tackle is the documentation for our public GraphQL API V2. We're investing a lot on it at the moment (*all* new endpoints are created there), yet we don't have a public documentation page for it.

GraphQL is kind of self-documented (when you use a client like GraphiQL) but it still nice to offer a traditional documentation website where you can expand on the different concepts with a nice presentation, like https://developer.github.com/v4/. Ideally, I'd say that this documentation should be 100% auto-generated from the code. We would indeed need someone with development expertise to handle that.

Now @alanna is not there at the moment to handle this, which means that we need someone else to take her role if we want to start this project.

@znarf you were also one of the mentor last year, is that something you'd like to take on this year?

**Comment by jaskirat2000** [comment]
Last year though @znarf agreed to be a mentor but I think due to time shortage he actually withdrew from it. So it was just me  and @alanna who mentored the project

**Comment by contraexemplo** [comment]
@jaskirat2000 Could you expand a bit on how was the process to apply as an organization last year? I know Google provides an extensive documentation on this but I'd like to get a more practical perspective from your experience.

**Comment by jaskirat2000** [comment]
@contraexemplo the process commences with two organization administrators who gonna be the liaison and take care of the things within the organization, They both set up the **organization GSoD Ideas page** and write down all the terms for the project and working with the org.
Org Admins are required to [fill out this form](https://bit.ly/gsod-org-app) which is probably of 5 pages and is required to answer the basic questions asked regarding experiences and planning for GSoD participation.
after the deadline, the Google reviews the things internally and selects organizations and the chosen organisations are displayed on their website accordingly.

**Comment by contraexemplo** [comment]
I see. Since I work closely with Outreachy, I believe administrating a community (or organization in this case) takes quite a bit of time. Which periods are most active for organization admins, and how much time did it take to fulfill admin duties from start to finish on a monthly basis?

**Comment by jaskirat2000** [comment]
You can check here for duties and responsibilities of admins
https://developers.google.com/season-of-docs/docs/admin-guide

**Comment by Betree** [comment]
I've discussed with the team today about this issue. Despite the fact that we loved participating in GSOD last year, no one in the team currently has the bandwidth to lead this project for this year.

@jaskirat2000 thank you for taking the time to share all this info with us and for proposing your help. We'll be happy to revisit this topic next year!

**Comment by jaskirat2000** [comment]
Its sad to hear, but still looking forward to next year turn.
