### ISSUE TITLE
reduce the barrier of donating

### ISSUE THREAD

**Issue by Clausinho** [opencollective/opencollective#3067]
## User story 
I was wondering if there was a way for Open Collective to allow people
to donate without registering traditionally but alternatively over their payment processor.
Similar to shops allowing to buy stuff without making an account first
by using paypal or amazon pay.

Furthermore it would be interesting, if this could also handle
recurring donations by using the payment providers functions

The advantage I see is that some users might not want to register or
remember another password and thus would be dissuaded from donating.

## Best solution for this problem
use the payment providers api

## MVP
have someone be able to donate without registering

## Metrics 
amount of people donating without registering
amount of people registering after donating without registering

## Documentation 
I don't get this

PS: the contribution guidelines link to the wiki
 the wiki seems deprecated. 
[wiki](https://github.com/opencollective/opencollective/wiki/Feature-Spec-Template) for what's acceptable as an MVP.)_
 PPS: I sent this to Alina Manko via email already

**Comment by gbrian** [comment]
Hi,
👏 for the project.

Sadly I aborted becoming a backer for GrapesJS project at last step because only Credit Card is aollowed. 
Please add Paypal, consider charging a fee if this helps starting with but worth paying a fee that registering a credit card.

**Comment by znarf** [comment]
It's on our radar and we will be tracking that here: https://github.com/opencollective/opencollective/issues/3164
