### ISSUE TITLE
How to link to the correct Github repository?

### ISSUE THREAD

**Issue by huihut** [opencollective/opencollective#3068]
**URL:** https://opencollective.com/interview

**Logged in as (username or profile URL):** [huihut](https://opencollective.com/huihut)

**Expected result:**

I want to link <https://opencollective.com/interview> to personal repository <https://github.com/huihut/interview>,

so that I can see the contributors at <https://opencollective.com/interview/contributors.svg>

**Error message if any:**

But it links to other organization <https://github.com/interview>, and contributors show the contributors of <https://github.com/interview>.

```
<img src="https://opencollective.com/interview/contributors.svg" />
```

<img src="https://opencollective.com/interview/contributors.svg" />

How to link <https://github.com/huihut/interview>?

**Comment by znarf** [comment]
I checked and everything is pointing to https://github.com/huihut/interview

**Comment by huihut** [comment]
Sorry, it's okay now.
