### ISSUE TITLE
Title of "Pending Invitations" seems off design

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3070]
Size, alignment and padding/margin doesn't seem to be right.

<img width="841" alt="Capture d’écran 2020-04-18 à 15 15 15" src="https://user-images.githubusercontent.com/806/79638769-829b3800-8187-11ea-86fe-07af5c8b9bb9.png">

**Comment by Betree** [comment]
I suppose it's because we removed the default `text-align: center` on H1. Setting the prop should fix the issue.

**Comment by znarf** [comment]
I think we should also review size and margin/padding.

**Comment by Betree** [comment]
The size is standard H1 from the design system, I'm happy to revisit that if it doesn't looks good. How should it look like?

**Comment by znarf** [comment]
Seems like the H1 size is almost always customized when we're using it.

On desktop, I would divide padding by 2. And `fontSize={['H5', 'H3']}` or `fontSize={['H4', 'H2']}`.

<img width="943" alt="Capture d’écran 2020-04-20 à 14 21 35" src="https://user-images.githubusercontent.com/806/79751200-7d1e2900-8312-11ea-8730-f5b794025d81.png">

**Comment by Betree** [comment]
`fontSize={['H4', 'H2']}` looks good to me.

The padding itself is pretty standard, it's a bit smaller for mobile but we do have `py={[5, 6]}` in a lot of places, especially the action/confirm pages which served as the template for this one.

I think there is a broader issue of having a common layout for all the quick action/confirm pages.

**Comment by Betree** [comment]
@raulgrafico our [pending member invitations page](http://opencollective.com/member-invitations) currently looks like this:

![image](https://user-images.githubusercontent.com/1556356/79752121-100b9300-8314-11ea-9740-170808d55204.png)

Could you provide some recommendations & eventually a design regarding the font-size, padding and alignments? We use a similar layout on some confirmation pages, so a good default would be helpful.

**Comment by SudharakaP** [comment]
Would you guys mind if I do this issue when the design task is completed? :smiley:

**Comment by Betree** [comment]
@SudharakaP Let's wait for design's feedback, we don't know yet when they'll have the bandwidth to work on this.

**Comment by SudharakaP** [comment]
> @SudharakaP Let's wait for design's feedback, we don't know yet when they'll have the bandwidth to work on this.

Sure thing. :smile:
