### ISSUE TITLE
Cannot submit expense ("This account cannot be used for payouts"?)

### ISSUE THREAD

**Issue by quimgil** [opencollective/opencollective#3073]
I submit the data for an expense as usual, then click submit button, then the submit button is greyed out and nothing happens. No error message in UI, the data is still visible in the form. Looking at the project activity, the data hasn't been submitted.

URL: https://opencollective.com/confederacio/expenses/new
Logged in as (username or profile URL): icaria36
Error message if any: not in the UI, but the browser inspector says "Error: "GraphQL error: This account cannot be used for payouts""
Expected result: Expense is submitted after clicking the submit button.
Browser: Mozilla Firefox for Ubuntu 75.0 (64-bit)

![image](https://user-images.githubusercontent.com/1899541/79698376-ca55b880-8288-11ea-84e6-c226ab537548.png)

**Comment by znarf** [comment]
@quimgil We'll look into it as a priority. What is your user account?

**Comment by Betree** [comment]
I I'm not mistaken, I think you're trying to submit expenses from a user profile that is also the host of the collective (https://opencollective.com/icaria36). I'll re-enable this now.

**Comment by quimgil** [comment]
Yes, I'm a member of a collective and I want to contribute to its expenses. I took the fiscal host responsibility because... there wasn't anyone else. :) We know financially it doesn't make much sense (we are paying some % for transactions that go from my account to my account) but we prefer to have the full transparency of our accounts in one place.

Thank you for your very quick response and thank you so much for this service!

**Comment by Betree** [comment]
@quimgil We're deploying the fix now, I'll let y ou know when it's ready

**Comment by Betree** [comment]
@quimgil fix deployed, let us know if you face any other issue.

**Comment by quimgil** [comment]
It works: https://opencollective.com/confederacio/expenses/16254

Thank you very much!
