### ISSUE TITLE
Make Update information more clearly expandable

### ISSUE THREAD

**Issue by blackforestboi** [opencollective/opencollective#3076]
**Describe the bug**
The box describing an update in the collective profile does not make clear that there is more information beyond the first line. 
To see "more", only the title is clickable which is not really apparent, and it also took me a bit, knowing that there is more information. Not knowing that I probably wouldn't even think about that those boxes can be opened. 

**To Reproduce**
1. Go to https://opencollective.com/worldbrain#section-updates
2. click on box, doesn't open
3. click on title, opens more information

**Expected behavior**
To fix this, make the entire box clickable, and add a little piece "show more" at the end of the line, indicating that this first line is not everything. 
Not fixing this makes the update box kind-of defeat its purpose because many people simply won't know the entire update. 

**Screenshots**

<img width="1232" alt="Screenshot 2020-04-20 at 17 22 58" src="https://user-images.githubusercontent.com/7870039/79768978-d0e93c00-832b-11ea-9495-fe42d80d0744.png">

**Comment by Betree** [comment]
@blackforestboi thanks for the detailed issue!

A "Read more" link would indeed be helpful. We _can't_ make the entire box clickable because there's another link in there (the avatar) but we should indeed make the description clickable too.

Related: #2547

**Comment by SudharakaP** [comment]
@Betree : What would be the idea solution here? How about making the description clickable and add a readme link on the right hand corner?

**Comment by Betree** [comment]
I just realized that making the description clickable is a bit tricky, because the description can contain links and nesting links is not valid HTML. In other words, we could end up with this:

```html
<a href="/collective/update/4242">
  <p>
     <!-- Nesting links like that is not valid HTML --> 
     I am the user-submitted summary and I contain a <a href="https://...">link</a>
  </p>
</a
```

The `Read more` is less risky, but I'm afraid it may not be visible enough. Let's involve @opencollective/design on this one.

**Comment by Betree** [comment]
Let's start with a `[Read more]` to improve the situation here. We'll follow up in another issue if it doesn't solve the issue.

**Comment by SudharakaP** [comment]
@Betree : Do you have any preference on where this [Read more] link should appear? Maybe next to title? :thinking:

**Comment by Betree** [comment]
I'd say at the end of the truncated content, similar to what we can see on Facebook & other social networks

![image](https://user-images.githubusercontent.com/1556356/88769935-5d05cd80-d17d-11ea-8a40-910c7561f86e.png)

**Comment by SudharakaP** [comment]
@Betree : Done. :+1:

**Comment by Betree** [comment]
The read more link will be part of the next update
