### ISSUE TITLE
Repair this!

### ISSUE THREAD

**Issue by Gahmous** [opencollective/opencollective#3077]
Hi, can you repair this? in  https://stellarium-web.org/
See this:
![image](https://user-images.githubusercontent.com/62570888/79805670-e92a7c80-8366-11ea-8a2e-9f8d714e152a.png)

**Comment by Clausinho** [comment]
how does this fit this project in any way?
you should point your issue to this project: https://github.com/Stellarium/stellarium-web-engine/issues

**Comment by Betree** [comment]
Wrong repo indeed, closing
