### ISSUE TITLE
Polish accept-financial-contributions, Host section

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3083]
1) Review the yearly budget formatting (no decimal and separator between 1000)

<img width="935" alt="Capture d’écran 2020-04-23 à 14 54 19" src="https://user-images.githubusercontent.com/806/80102057-8e657080-8572-11ea-883e-4e4bbada2d35.png">

2) Review the layout when only one host is rendered

<img width="766" alt="Capture d’écran 2020-04-23 à 14 54 58" src="https://user-images.githubusercontent.com/806/80101970-6d048480-8572-11ea-811f-2f315a0e99b3.png">

3) Review the layout when 3 hosts are rendered

<img width="715" alt="Capture d’écran 2020-04-23 à 14 55 34" src="https://user-images.githubusercontent.com/806/80102079-97eed880-8572-11ea-8ad4-389dc36991ad.png">

4) Is there an agreement on `description` vs `longDescription` for the modal? I still think `longDescription` is carrying information that is pretty useful.

**Comment by sbinlondon** [comment]
I thought `longDescription` was better and fills up more space, therefore making it look better, but I think @piamancini or @Betree had some issues with it if I recall?

**Comment by Betree** [comment]
I don't remember, technically it's ok to use `longDescription` if there enough place for it.

**Comment by sbinlondon** [comment]
Have addressed 1-3 in an upcoming PR, and 4 is what we're discussing on Slack. I've merged the PR to add `longDescription` to the API, now just need to merge @Betree's PR to filter non-hosts and we can see how it looks with some production hosts and decide if it needs any further work.

**Comment by Betree** [comment]
I haven't continued with https://github.com/opencollective/opencollective-api/pull/3804. I assume it's still needed to complete this?
