### ISSUE TITLE
FAQ layout issue on Safari

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3084]
**Describe the bug**
On Safari, the FAQ's layout is broken. This seems even more visible on mobile, it may be a responsiveness issue. 

**To Reproduce**
1. Go to https://opencollective.com/engineering/expenses/new/v2
2. If necessary, resize your browser
3. See layout issue

**Expected behavior**
Behavior should match what we have in other browsers. See https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC.com%5D-Production-Ready-%E2%9C%85?node-id=1054%3A23147

![image](https://user-images.githubusercontent.com/1556356/80115477-10f72b80-8585-11ea-9067-bf4e8f8bd2f9.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/1556356/80115581-371ccb80-8585-11ea-9dcf-597e29b03ab5.png)

![image](https://user-images.githubusercontent.com/1556356/80115539-266c5580-8585-11ea-9696-b3ecb8525c89.png)

**Comment by kewitz** [comment]
Related to https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers
