### ISSUE TITLE
generateSummaryForHTML missing trailing dots when link tag is truncated

### ISSUE THREAD

**Issue by bolariin** [opencollective/opencollective#3086]
**Describe the bug**
The `generateSummaryForHTML` helper function is used to generate a summary for conversations on the collective page. When `generateSummaryForHTML` is used on the content, it adds a three trailing dots to the end of the summary indicating if part of the original content was left out of the summary. It looks like there's a bug when the truncated text happens to be a link tag (this probably happens for other tags accepted by `sanitizeHTML`) .

**To Reproduce**
1. Go to any collective page
2. Click on `Conversations`
3. Click on `Create Conversation`
4. Add a title and paste the text below, you will have to replace the links in the text.

```
This week we had a choice of all sorts of news, but as we cut the show together as a group [Danny](https://twitter.com/DannyCrichton) pushed all the funding rounds up. So, when [Alex](https://twitter.com/Alex) and [Natasha](https://twitter.com/nmasc_) jumped into the show we had a bunch of good news to cover. We’re avoiding COVID-19 news,
```
You can view the example at https://staging.opencollective.com/engineering/conversations

**Expected behavior**
I expected the summary to end with trailing dots to indicate more text to read.

**Screenshots**
* Actual
![without trailing dots](https://user-images.githubusercontent.com/24629960/80263138-9e0db380-865d-11ea-97ad-1b62cba3e4be.png)

* Expected to be similar to this with trailing dots at the end
![with trailing dots](https://user-images.githubusercontent.com/24629960/80263140-9ea64a00-865d-11ea-880b-07a7676ad0be.png)

**Comment by Betree** [comment]
Good catch @bolariin, thanks for the detailed issue

**Comment by SudharakaP** [comment]
I'll give it try at this one if it's not being worked on. :smile:

**Comment by SudharakaP** [comment]
Done. This seems to happen because we do the second sanitization pass as the last step, overriding the truncation step and removing the `...`. I've corrected it. :smile:
