### ISSUE TITLE
hostFeePercent=0 stored as NULL in the database

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3097]
We are not properly saving `hostFeePercent=0`.

It's functional but that can lead to problems now and in the future.

Not sure if the issue is API or Frontend.

Update: in the settings, it's empty instead of zero.

<img width="931" alt="Capture d’écran 2020-04-29 à 14 56 25" src="https://user-images.githubusercontent.com/806/80598476-b436bd80-8a29-11ea-8e55-5dd3c19769d7.png">

- [x] Fix the bug
- [x] Migrate bogus data

**Comment by znarf** [comment]
Can you have a look @kewitz ?

**Comment by kewitz** [comment]
@znarf, sure. How should we migrate this? Is it safe to assume every null as being zero?
