### ISSUE TITLE
HeroAvatar: never save images from images service

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3099]
**Describe the bug**
In https://github.com/opencollective/opencollective-frontend/blob/00688a2801eedf22d8d45c88199f5a3cf56ec72e/components/collective-page/hero/HeroAvatar.js#L215, the component happens to sometimes save the URL from the image service (`https://images.opencollective.com/...`). 

**Expected behavior**
We should never save images from the image service, the URL that goes there **must** be a raw URL (`collective.image`).

**Comment by SudharakaP** [comment]
Also maybe on a slightly related note; I see that the function `upload(file)` has been marked deprecated; but the comment `moved to `lib/file-upload.js` seems not correct. I cannot find such file. :thinking: 

https://github.com/opencollective/opencollective-frontend/blob/bfc6a07cea4a22fc23b07555bd9e97de3c970100/lib/api.js#L44-L49

**Comment by SudharakaP** [comment]
I just did a pull request removing the `imageUrl` from getting saved. I am wondering it's simple as removing part of the condition right? :thinking: Is there anything else you can think that needs to be done here?

**Comment by Betree** [comment]
@SudharakaP Nope that should do it :slightly_smiling_face:
