### ISSUE TITLE
Activate as host fails

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#3100]
**Describe the bug**
When hitting Activate as host in an organization profile, you see a weird GraphQL validation error - `URL is not valid` 

In this case is organization (id: 101524). I went in manually and activated the host flag in the data base to unblock user and it worked normally. 

**To Reproduce**
1. Go to an organization's setting
2. Click on 'Fiscal Host' tab, then Activate as Host
3. Is Host flag is still set as FALSE in DB

**Expected behavior**
Activate as host being TRUE in the DB 
Seeing the host menu in the side bar. 

**Screenshots**

<img width="486" alt="Screen Shot 2020-04-29 at 4 55 39 PM" src="https://user-images.githubusercontent.com/3671070/80621725-fcfd6f00-8a47-11ea-84ce-897301fd66c8.png">

<img width="1078" alt="Screen Shot 2020-04-29 at 4 54 46 PM" src="https://user-images.githubusercontent.com/3671070/80621729-fe2e9c00-8a47-11ea-80ba-cf768f421972.png">

**Comment by Betree** [comment]
Seems related to my changes on the collective image, I can look at it tomorrow

**Comment by znarf** [comment]
@piamancini At which time did that happen?

Seems Ben pushed a fix https://github.com/opencollective/opencollective-api/pull/3797 for that at 17:22 CEST / 15:22 UTC. That is one hour before you reported this issue.

I don't see anything in the logs after 15:03 UTC, so I consider this being fixed.
