### ISSUE TITLE
Proposal for Roadmap Q2 - May & June

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#3104]
This is the list of top priorities for Q2 -

Top priorities 
------------

Kate: 
Recurring contributions management 
Host dashboard 
Simplifying and air-proofing txns recording (DA LEDGER)

Memo: 
Host Dashboard 
Implement Metrics 
Improve contribution experience (discovery / flow)

Ben: 
Contribution Flow: (allow custom donations to OC / Fees on top)
Sign in on CF - friction point 
Host dashboard 
Enhancements on CP - (like custom images on tiers / sort tiers)

François
Subscription revamp 
Fees on top
2FA
Ledger / host collective / collective to collective txn - Make platform simpler for users. 

Leo: 
Fees on top 
Deprecate Host Plans 
Metrics dashboard 
CF (one time donations without having to log in)

Cuiki: 
Host Dashboard
Behavioral analytics (Metrics)
Killing concept of host collective.
CF iteration
CP: match to new components
Kill pledges (create an issue for this) (Ben)

Pia: 
Fees on top
Contribution Flow Upgrade
Host dashboard (will reduce support/optimize team time)
Upgrade PayPal Payout
2FA 

I think there's a consensus that we need to build Fees on Top rather quickly because we have a window of opportunity to test it out.  I'll start a project for it. 

For the rest of the priorities, let's have a quick discussion below - add things that we could have missed, etc. 

Note: we are one month late in the Qs because we started at the retreat in Feb. So think of deliverables we can review in two months - This can be good practice to better define MVPS. We'll do a two month quarter to get back on normal schedule.

**Comment by sbinlondon** [comment]
I know only Leo mentioned it in his priorities but I also thought the metrics dashboard was important and while it's not _urgent_, the need for it is never going to go away so we might as well roll up our sleeves and do it. I'm not sure what we have set up at the moment but perhaps this could be a good 2-month project for he and I to work on? We can do a spike, decide what is most important for us to track, get a dashboard set up in i.e. Grafana or something, and then going forward whenever we do a project like Host Dashboard or Create Collective Flow, the project owner would be responsible for creating metrics on the dashboard to go with it.
