### ISSUE TITLE
Message sent through contact form triggering gmail phishing warning

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3106]
This is how an email sent through the contact form on a Collective page appears. Can we do anything to not trigger these warnings?

<img width="535" alt="Screen Shot 2020-05-04 at 10 52 23 AM" src="https://user-images.githubusercontent.com/5498878/80927990-a308fa80-8df5-11ea-8d64-1448245b9f6f.png">

**Comment by Betree** [comment]
I assume the problem comes from the fact that numerous SPAM emails are sent through our contact form. People report them in GMail, which then flags other messages coming from the contact form as SPAM.

The options that I see to get out of this situation:
- Try to detect SPAM and filter the messages sent through the contact form (complex).
- Drop the contact form, allow the collectives to customize their contact action (#2263) and let users decide how they want to be contacted (simple)

**Comment by znarf** [comment]
We're ready to remove the "softfail" of our SPF configuration. That should improve our reputation.

If that's not enough, we will need to look at Mailgun reputation, have a dedicated IP address or move to another provider.

**Comment by piamancini** [comment]
- [ ] go through the DMARC reports and make sense of them

**Comment by znarf** [comment]
Q2 Sprint 2 Week 5:

- [ ] check DMARC report automation status
- [ ] remove "softfail" from our SPF configuration
- [ ] activate dedicated IP address on Mailgun (if that still makes sense)

**Comment by BenJam** [comment]
@znarf is there any update missing here?

**Comment by Betree** [comment]
We haven't activated the dedicated IP yet. It's not an easy one to monitor, but according to [Google's Postmaster tools](https://postmaster.google.com/u/1/dashboards#do=opencollective.com&st=domainReputation&dr=120), we may want to iterate on this: our domain reputation is currently High (1) while our IP reputation sometimes falls into Medium (2).

![image](https://user-images.githubusercontent.com/1556356/192220192-259b705f-887a-4f90-875d-cb5ed30c33ce.png)

![image](https://user-images.githubusercontent.com/1556356/192220373-cf286668-613f-4010-9434-ecd3ee0b7c6f.png)

**Comment by Betree** [comment]
Dedicated IP has been enabled by @znarf, I will monitor the IP reputation in the next few days/week.

**Comment by Betree** [comment]
So far so good

![image](https://user-images.githubusercontent.com/1556356/193042693-9f056491-48a7-473e-be85-8ff8917d90a0.png)

**Comment by Betree** [comment]
Except for Mailchimp newsletters that are apparently having a negative impact on our email reputation (the yellow bar in the screenshot) the new IPs reputation seems to do the job. I'm closing this for now, feel free to re-open if you get more cases like that in the future.

![image](https://user-images.githubusercontent.com/1556356/208984809-10c83ffb-b0af-4389-9d33-d8b6bc3741e0.png)
