### ISSUE TITLE
API Question: How to get all pending expenses for collective?

### ISSUE THREAD

**Issue by fishcharlie** [opencollective/opencollective#3108]
Is there an example or way to get all pending expenses for a collective? I'm looking through the GraphQL documentation and can't find anything for this. All I can find is `expensePolicy` or `expensesTags`. Can someone provide an example for how to get all pending expenses for a collective?

Just for a bit more context, the goal is gonna be to build a system where every so often (likely every hour) we query the API for all recent pending expenses and for each new pending expense, we will create a PR on a GitHub repository with the details of the expense. Then users will be able to vote on the expense by using the GitHub approve/request changes PR review feature. Once the bot detects that an expense meets certain criteria in terms of votes for the given type, amount, etc. It will use the Open Collective API to approve the transaction, pay it, and merge the PR. I have been able to find documentation for approving and paying a transaction (it looks like), but not on how to retrieve a list of pending transactions.

**Comment by Betree** [comment]
@fishcharlie thanks for sharing your use case, that's an amazing feature idea!

The `expenses` endpoint is not available yet on our public API, but it's a priority that should be addressed this week or next week. I'll update you on this issue once it's ready.

**Comment by Betree** [comment]
@fishcharlie the endpoint is now available through the root `expenses` query (implemented in https://github.com/opencollective/opencollective-api/pull/3839). Feel free to ask questions here or [on Slack](https://opencollective.slack.com/archives/C4TC3AYDT) if you need more details!

**Comment by Betree** [comment]
@fishcharlie We got a big traffic on this endpoint and had to block some of the IPs. If you were somehow blocked, please let us know on https://slack.opencollective.com/

**Comment by fishcharlie** [comment]
@Betree I haven't gotten a chance to look at this further yet. Hopefully will in the future. Thanks tho!
