### ISSUE TITLE
Remove font-size aliases

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3109]
Most of our text components support aliases for the `fontSize`, defined in [lib/theme/text-sizes.js](https://github.com/opencollective/opencollective-frontend/blob/4d48f6fada12c3473fb95a046559b9dec68af539/lib/theme/text-sizes.js). For example, you can write the following:

```jsx
<Span fontSize="Paragraph"/> // Will be `font-size: 14px`
```

I personally liked this, but since the introduction of this feature a lot of different text styles were progressively added to [Figma - Typography](https://www.figma.com/file/jxJfC29te8i1C8qMReth95/%5BDS%5D-01-Typography) to the point that we now have more than 30 of them.

The main advantage of this aliasing practice is normally consistency: you make sure that all your paragraphs always have the same size (design system) and if you ever want to change it it's a one-line edit in the config.

I now think that we should stop supporting this, for the following reasons:
- For new contributors, it's unclear where these aliases come from and what their values are.
- The way we currently set this prop is not consistent (some with aliases and some with `px`)
- We'd need to add many more aliases if we want to cover all the font-sizes used in designs.
- Having aliases when there are more than 10 font-sizes is not useful because you can't expect people to remember them all.

**Suggested alternative**: always explicitly write the font size: (/keep it simple)
```jsx
<Span fontSize="14px"/>
```

**Comment by sbinlondon** [comment]
I agree with all this, especially point 1 and the bit about stuff being added to Figma. Even recently I had a design for Accept Financial Contributions that said the font was some alias name, with the px size in parentheses, and it did not match what we had in `theme.js` which is confusing at best and frustrating at worst. I agree that if we are able to go, "Figma says line height of x px and font size of x px" and then we explicitly set that, it will be much easier.
