### ISSUE TITLE
Broken links on documentation for manual reporting

### ISSUE THREAD

**Issue by whoabuddy** [opencollective/opencollective#3111]
**Describe the bug**

The two links on the [Manual Reporting](https://docs.opencollective.com/help/contributing/development/manual-reporting) page are broken. The current links from [manual-reporting.md](https://github.com/opencollective/documentation/blob/v2/contributing/development/manual-reporting.md):

- https://github.com/OpenCollective/opencollective-api/blob/master/templates/emails/group.monthlyreport.hbs
- https://github.com/OpenCollective/opencollective-api/blob/master/cron/monthly/email-report.js#L30

It looks like the correct links should be:

- https://github.com/opencollective/opencollective-api/blob/master/templates/emails/collective.monthlyreport.hbs
- https://github.com/opencollective/opencollective-api/blob/master/cron/monthly/collective-report.js

**To Reproduce**

1. Go to https://docs.opencollective.com/help/contributing/development/manual-reporting
2. Click on either link
3. Enjoy GitHub 404

**Expected behavior**

I expected the links to take me to fancy email templates and javascript code.

**Desktop (please complete the following information):**
 - OS: Linux Mint 19
 - Browser Vivaldi
 - Version 3.0.1874.33

**Additional context**

Originally [filed the issue here](https://github.com/opencollective/documentation/issues/72) before realizing this was the correct spot.

Random idea: you should add an issue template to the old repo that tells people to come here instead, similar to the issue that is currently there.

**Comment by znarf** [comment]
Seems this documentation is out-dated and was originally meant for Open Collective core developers. It needs to be completely revamped or deleted. 

For your use case, I recommend to use the GraphQL API or CSV export.

**Comment by vickywane** [comment]
@znarf if it is decided internally to keep that documentation, i made a fix for those broken links. 

I also dont mind spending some more time to work on the repository.

**Comment by sbinlondon** [comment]
@znarf should we revamp or delete? Happy to do it.
