### ISSUE TITLE
Contact backer

### ISSUE THREAD

**Issue by leena4c** [opencollective/opencollective#3114]
A backer donated more than he indicated in his donation. Maybe he made a mistake making the wire transfer, maybe while putting his contribution on OC. In any case, I would like to reach out to him and ask him, but I don't know how. How can I get in touch with a backer? 

Thank you!! 

URL: 
Logged in as (username or profile URL):
Error message if any:
Expected result: 
Browser:

**Comment by znarf** [comment]
@leena4c Can you engage with support -> support@opencollective.com ?

**Comment by Betree** [comment]
For anyone stumbling on this question:

You can export the emails of your contributors through `Settings > Export > Export CSV`.
