### ISSUE TITLE
PayPal error: "Cannot read property 'error' of undefined"

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3119]
PayPal response payload is not what is expected:

```
{
  "responseEnvelope": {
    "timestamp": "2020-05-07T16:19:39.277-07:00",
    "ack": "Success",
    "correlationId": "43644d05d666",
    "build": "apapiserv-0.0.1_20200423071356971"
  },
  "paymentExecStatus": "ERROR",
  "payErrorList": {
    "payError": [
      {
        "receiver": {
          "amount": "1100.00",
          "email": "XXX@gmail.com",
          "primary": "false",
          "paymentType": "SERVICE"
        },
        "error": {
          "errorId": "579045",
          "domain": "PLATFORM",
          "severity": "Error",
          "category": "Application",
          "message": "The amount exceeded the individual transaction limit of user 1100.00",
          "parameter": [
          ]
        }
      }
    ]
  },
  "httpStatusCode": 200
}
```

https://github.com/opencollective/opencollective-api/blob/master/server/lib/transactions.js#L97

Let's check if it's isolated or if they changed their API.

**Comment by znarf** [comment]
As of today, no new occurrence of the error in the logs. Searched for `"Cannot read property 'error' of undefined"``` in PaperTrail.

**Comment by znarf** [comment]
<img width="933" alt="Capture d’écran 2020-05-20 à 20 19 13" src="https://user-images.githubusercontent.com/806/82482472-31100100-9ad7-11ea-875b-4c91e5bfbda4.png">

**Comment by daegontaven** [comment]
I'm having this issue when trying to pay with paypal. What do I do?

**Comment by znarf** [comment]
@daegontaven Sorry, missed your message. Using Open Collective? Try again and contact support if that doesn't work.

**Comment by znarf** [comment]
One occurrence in the last 7 days:

<img width="932" alt="Screenshot 2020-06-26 at 10 26 08" src="https://user-images.githubusercontent.com/806/85836856-8f479800-b797-11ea-8da2-6120b46d4a4d.png">
