### ISSUE TITLE
Monthly email for backers

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#312]
We should send a monthly email to the backers with a summary of all of their contributions during the month.

- [x] List of active subscriptions (@xdamman)
- [x] Show new related collectives (@xdamman)
- [ ] List of one-time donations during the month
- [ ] Show latest pending expenses per collective (if any)
- [ ] Redesign email template (@erickrico)
- [ ] Show summary of latest issues / PR for open source collectives
- [ ] Add a link to the PDF receipt per host (pending aggregation of all donations per host per month)

**Comment by xdamman** [comment]
@erickrico can you help redesign this email template?
This is the way it currently looks: 

![](https://cl.ly/303g3w0M0F43/Screen%20Shot%202017-02-12%20at%2011.45.02%20PM.png)
![](https://cl.ly/3G3v1E0d1N1O/Screen%20Shot%202017-02-12%20at%2011.52.53%20PM.png)

**Comment by cuiki** [comment]
Hi Xavier, is this with the same content you show in these screenshots?

**Comment by xdamman** [comment]
For now yes, but later we would want to add more info (see the checkboxes above).

But we may also consider just showing a button to go to a special page for a monthly update online (because you may not want to have the digest for each collective you support in a single email if you support more than one)

**Comment by cuiki** [comment]
Hi! Ok, you can view the design for the email template here: https://zpl.io/Z1UCUbe

I left notes on the design to explain my thinking.

**Comment by xdamman** [comment]
This looks great. Can you make a version for mobile?
It's good to start with the smaller screens in mind.

Also I think that we want to provide the full list of collectives that you are backing. But for each collective, we may want to add (in the future, not now) the option to get to the full report online. The call for action for this should be something along the lines of 
- "12 new issues, 5 new PR, 40 new comments this month. [View their activity report]"
- "4 events, 120 participants this month [View their activity report]"

Note that we don't have the time to implement this yet so you don't have to take this into account just yet. It's more to give you an idea of where this going.

**Comment by cuiki** [comment]
Ok, understood. Here are the updated screens. I made some small edits to the one I had sent before. Here you go:

› Dekstop: https://zpl.io/22ExWh
› Mobile: https://zpl.io/Z2fOpdB

**Comment by piamancini** [comment]
can you invite pia@opencollective.com to the project so I can see it? thanks

**Comment by cuiki** [comment]
Done!

**Comment by xdamman** [comment]
This is great! I just wonder if we shouldn't put the logo of the collective at the top instead of the bottom in the small screen view.

Also, can one of you turn this into email compatible HTML?
Do you have experience in this? It's not that straightforward and we are limited in what we can do (especially the responsiveness can be quite tricky).

**Comment by xdamman** [comment]
can we add the URL of the collective somewhere?

E.g. As a user, I'd want to check the website of consciousness hacking to get the latest updates rather than going to their collective page (or the GitHub page of Webpack to see the latest*). Maybe we can add a link to the website on the left hand side and use the collective card to link to their collective page? Should we add a visual clue for that like "visit their collective page"?

* eventually we would want to aggregate the latest activities of a collective on their collective page but in the meantime, let's just link to their website.

**Comment by cuiki** [comment]
Hey, so to answer your questions:

1. I think that putting the Collective's card in the bottom is best because the assumption is that the user at least has an idea of which collectives he/she is a member of. Putting it at the top would be leading with info that I don't think we want them to primarily consume first. We are having the Collective's name first so I think that is enough.

2. Yes, we can create the HTML for it.

3. So for the URL, I thought of this: http://d.pr/i/iiQe. It is a small text below the Collective's name that links to both the oficial website (if it exists) and the Collective's page as well. This is now clear to any user. They can still go to the Collective's page  by clicking on the card.

**Comment by xdamman** [comment]
1. Ok
2. Awesome, then go! :)
3. Looks good to me. I would just show the domain instead of website but that's a detail we can tweak later (e.g. GitHub.com/webpack, meetup.com/RailsGirlsAtl)

**Comment by cuiki** [comment]
Yeah I thought of that too, but in the example for Consciousness Hacking SF, the website they have has this URL:

› https://www.meetup.com/Consciousness-Hacking-San-Francisco/

Which is super large, and since we can't control them, then I opted for labeling it "Website".
