### ISSUE TITLE
Tax form: threshold amount should be in RequiredLegalDocument, not hardcoded

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3121]
Amount for checking if a tax form is required is currently hardcoded: https://github.com/opencollective/opencollective-api/blob/6e0a683ff7e3c4d98c81abdf728c04a7894ab5dc/server/graphql/v1/types.js#L913.

It's unclear when reading at the code what this value is and where it comes from, and it defeats the purpose of `RequiredLegalDocument` which was ideally supposed to be compatible with other document types in the future.

### Proposal

Add a `thresholdAmount` column to `RequiredLegalDocument` and read the value from there.

**Comment by znarf** [comment]
I'm likely gonna touch that this week when integrating for Foundation.

**Comment by Betree** [comment]
@znarf cool, feel free to implement a different solution if you see a better fit. I'm not attached to this one, was just surprised to see this `600e2` in the middle of the code :slightly_smiling_face:

**Comment by flickz** [comment]
Since I'm currently working on related [issue](https://github.com/opencollective/opencollective/issues/3123) I'm thinking I can follow up the [PR](https://github.com/opencollective/opencollective-api/pull/4022) with this issue.

@Betree @znarf

**Comment by Betree** [comment]
https://github.com/opencollective/opencollective/issues/4645 actually surfaces more complex conditions than just checking the amount:
| Invoice payments per calendar year | Tax form Required? |
| ----------- | ----------- |
| $600 or more by any method besides Paypal  | Yes  |
| $600-$100,000 via Paypal   | No   |
| $100,000 or more via Paypal | Yes |

For this reason, I no longer see this issue as an interesting solution. We should however make sure that all constants like that are centralized and can easily be edited.
