### ISSUE TITLE
Improve user menu on mobile

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3122]
Follow up on https://github.com/opencollective/opencollective/issues/3037
:art:  See [latest design on figma](https://www.figma.com/file/9Iq3vBOmZ2EuOacXEYD5yK/DS-05-UI-Organisms?node-id=4%3A0)

The design for mobile hasn't been fully implemented, we need to make the following changes:
- [ ] Add the user account footer
- [ ] Make the tooltip menu full size (height and width)

![image](https://user-images.githubusercontent.com/1556356/81574893-aaf10d80-93a6-11ea-8732-16668d9bf353.png)

**Comment by axiiomatic** [comment]
can i try this one?

**Comment by Betree** [comment]
Hi @axiiomatic, sure! Let me know if you need anything

**Comment by Betree** [comment]
@darkmtr any progress on that one?
