### ISSUE TITLE
userTaxFormRequiredBeforePayment should use a GraphQL loader

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3123]
The places where we check if W9 tax form is required for users, in `expense.userTaxFormRequiredBeforePayment` (GQLV1) and `expense.requiredLegalDocuments` (API V2) are not using GraphQL loaders.

It's not a big deal yet because the places where we show this on lists (mainly, the host dashboard) make a single query for each expense (see https://github.com/opencollective/opencollective/issues/2519). But as we're going to revamp the host dashboard and eventually add the tags on list expenses list, it would be great to improve that.

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by flickz** [comment]
@Betree Taking on this

**Comment by Betree** [comment]
Bumped the complexity to `medium` and adapted the bounty

**Comment by Betree** [comment]
Note: with expense process actions coming to the expenses list, we'll need to add the fields on the `expenses` page query once we have the proper loaders to back them

**Comment by Betree** [comment]
:trophy: This issue has been completed by @flickz  

To claim the **$500** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
