### ISSUE TITLE
New expense flow: add more E2E tests

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3125]
The new expense flow is still lacking some Cypress tests. We need to cover:
- `test/cypress/integration/03-expenses.page.test.js`
  - [ ] List expenses
  - [ ] Can filter by tag
- `test/cypress/integration/27-expenses.test.js`
  - [ ] Some actions (approve, unapprove, reject, pay)
  - [ ] Delete an expense
- `test/cypress/integration/34-expenses.comment.test.js`
  - [ ] create, edit and delete comments

**Comment by jeffin143** [comment]
@Betree , saw your improvements on test , I will try to adapt same if I wrote any more E2e :) 

Let's close this since it is done

**Comment by Betree** [comment]
@jeffin143 Indeed! Your approach on these tests was good, but I didn't initially realize the underlying complexity that was needed, for example the fact that collective needed to have a positive balance to pay expenses. It was easier to use an existing collective to achieve that. I also found that we had this `cy.createExpense` helper already in the code, pretty convenient!
