### ISSUE TITLE
Feedback for new expense flow

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3128]
This issue is here to gather feedback and impressions around the new expense flow.
 
# Changelog

A small highlight of the new features:

### Automatic invoice generation

<details>
<br/>

> No need to generate a PDF to get reimbursed anymore! Just pick the `Invoice` type, and we'll generate one for you :receipt: 

![image](https://user-images.githubusercontent.com/1556356/79250670-4dd56b00-7e7f-11ea-96b6-b2d8da763cd7.png)

</details>

### Submit multiple receipts

<details>
<br/>

> No need to create multiple expenses or to merge receipts in PDFs anymore: you can now submit a single expense for multiple related items :shopping: 

![image](https://user-images.githubusercontent.com/1556356/79251416-65612380-7e80-11ea-82d3-ac24112cd2b8.png)

</details>

### Submit an expense as an organization

<details>
<br/>

> You can now submit an expense in the name of your organization. We currently working on making this feature work for collectives too!

![image](https://user-images.githubusercontent.com/1556356/79251700-c983e780-7e80-11ea-9996-4a95bcff06bd.png)

</details>

### Associate multiple payout methods

<details>
<br/>

> You can now associate multiple payout methods to your profile.

![image](https://user-images.githubusercontent.com/1556356/79252371-c9d0b280-7e81-11ea-82e2-e307a31ec5df.png)

</details>

### Expense activity feed

<details>
<br/>

> Along with the comments, see when expenses get approved, rejected, edited and paid.

![image](https://user-images.githubusercontent.com/1556356/79252690-51b6bc80-7e82-11ea-9d35-72fcf887e331.png)

</details>

# Try it :arrow_down: 

Just visit the existing expenses page. Feel free to use our test collective if needed:
- https://opencollective.com/open-potatoes/expenses/new

# Give feedback

Below are some questions to guide your feedback - you don't need to answer them all, feel free to answer with whatever format is easier for you:
- What is your general impression?
- Did you understand all the terms and actions that were presented to you?
- Did you encounter any glitches/bugs?
- Are there things that you especially like?
- Do you see things that could be improved?

_If you had experience with the previous flow:_
- Was it faster or slower to complete?
- Is there anything that you did with the previous flow that you're not able to do anymore?

### Related issues
#1073 

<br/>

**Comment by Memo-Es** [comment]
### Transparency enhancements

In a user research call with The Social Change Agency, we talked about some key enhancements in the payout information part:

**1.Disclaimer about payment processor fees**
- Adding a disclaimer in the dropdown where you choose your payout method telling you that payment processor fees may apply
<img width="1934" alt="Annotation on 2020-05-13 at 09-00-57" src="https://user-images.githubusercontent.com/49539954/81823049-7e013f80-94f9-11ea-8f9e-52b18665fabc.png">

**2. When you choose your payout method, display who will be adebited the fees**
<img width="1674" alt="Annotation on 2020-05-13 at 09-02-16" src="https://user-images.githubusercontent.com/49539954/81822993-6aee6f80-94f9-11ea-8300-a1fcd50c18bc.png">

**3. Make sure we display the right method the host used to pay the expense**
- Even if its the same experience for the submitter we should display the final payout method used by the host.
<img width="1574" alt="Annotation on 2020-05-13 at 09-05-46" src="https://user-images.githubusercontent.com/49539954/81823605-17c8ec80-94fa-11ea-9423-0ac5ebb1c3bc.png">

@piamancini @Betree @kewitz

**Comment by Memo-Es** [comment]
### GDPR issue

-Some users are submitting expenses with personal information in the expense title. The suggestion is to add a small caption indicating the user to be careful to share sensitive information in that field.

<img width="2744" alt="Annotation on 2020-05-13 at 23-40-14" src="https://user-images.githubusercontent.com/49539954/81893385-36b79500-9573-11ea-8a0c-2057fc0aaba6.png">

**Comment by charlie-watkinson** [comment]
### Data Privacy

Feedback from a Covid Community Support group with Social Change Agency that are using OC for expenses. As the receipt goes straight to public view, there are no preventions in place to review the content of any public information and as such personal information is being published. 

Also, the general flow is unclear what to put in the title field in general. Suggestion to add a header before the title field with subtext. 

But would also be good to hear if there would ever be a sign off stage so that receipts weren't public until they are authorised, meaning we can capture any that contain personal info.

<img width="423" alt="Screenshot 2020-05-18 at 11 58 23" src="https://user-images.githubusercontent.com/65552589/82344965-9804bb80-99ec-11ea-9632-f33cd96397a5.png">

**Comment by Betree** [comment]
Thanks to everyone who provided feedback! We're now iterating on a more recent version of the contribution flow, and tracking everything in separate issues.
