### ISSUE TITLE
Open Collective Roadmap: May - June  (short Q2)

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#3129]
Q2 Theme: Simplicity of our value proposition
===============================

This (short) Quarter is all about shedding complexity: in our offer, in our codebase, in our UI.

Offer: 
Covid has given us an opportunity to position ourselves in a new vertical that has similar requirements than the Open Source one. Crisis Responders. I mean similar in the sense that they need a turn-key solution that includes a platform to fundraise and disburse funds paired with a fiscal host that can act as the custodian of the funds. We’ve struggled to replicate this outside of the FOSS ecosystem, but now we are seeing it again. 

To make sure we support as many groups as possible in this vertical, we’ve waived our fees until June, we are hiring someone to manage the Open Collective Foundation (501c3 that’s doing the fiscal hosting in the US) and relaunched it with a focus on COVID. From the new collectives in march 175 are COVID related initiatives.

The growth driven by COVID-19 Relief groups is an opportunity for us to focus our efforts on growing a new segment of collectives with a **First Party Host** (this is a host we own, as opposed to a third party host, a legal entity that uses Open Collective Platform). This is important for us, because we are providing a complete solution ourselves: Tax deductible fiscal sponsorship as a service paired with a transparent open finances platform. 

Projects
========

Host Dashboard Design
-----------------------
Project Issue: https://github.com/opencollective/opencollective/issues/2896
Project owner: @piamancini
Design Owner: @Memo-Es
Status: Wireframes: shipped, UI design: in process.
Goal: Design in components that can be implemented in phases. 

Host Dashboard Implementation
-------------------------------
Project owner: @piamancini   
Technical owner: @Betree 
Implementation Specs Issue: **needed** 
Component Deliverables: 
- Expense List 
- Pay
- Filtering for Host Dashboard

Design Proposal for Contribution Flow Iteration
----------------------------
Goal is to lower the barriers for donors to give: 
User related Issues: https://github.com/opencollective/opencollective/issues/3067 and https://github.com/opencollective/opencollective/issues/2228
Project owner: @piamancini 
Design owner: @Memo-Es 
Project Issue: #3164 

PayPal Payout API Upgrade 
------------------------
We're currently using [Paypal Adaptive Payments](https://developer.paypal.com/docs/classic/adaptive-payments/integration-guide/APIntro)
PayPal introduced a Payout API that provides the following benefits over adaptive payments:
Payout limit is $20,000 USD
For payouts made through the API, it’s just $0.25 USD per U.S. transaction.
For international payments, the fee is 2% of the payment amount to each recipient (up to a maximum of $20)
Project Owner @kewitz 
Project Issue: https://github.com/opencollective/opencollective/issues/3131
Related Issues: https://github.com/opencollective/opencollective/issues/2274 and https://github.com/opencollective/opencollective/issues/2258

Collective Page Enhancements 
--------------------------
Improving and simplifying Collective Page
Project Owner: @Betree 
Project Issue: https://github.com/opencollective/opencollective/issues/3136

Subscriptions Management Revamp 
---------------------------------
Simplifying how donors manage their subscriptions
Project Owner: @sbinlondon 
Project Issue: #3137
Figma Designs: [here](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC.com%5D-Production-Ready-%E2%9C%85?node-id=3572%3A0)

2FA
---------
Project Owner: @znarf 
Project Issue: **needed**
[Related Issues](https://github.com/opencollective/opencollective/issues?q=is%3Aissue+2FA) 

API Metrics 
------------
Project Owner: @znarf 
Project Issue: **needed**

Fees on Top
--------------

Project Issue: https://github.com/opencollective/opencollective/issues/3105
Since we are waiving our fees for COVID collectives we are setting up a path for donors to give platform fees on top of their donation. 
Project Owner: @piamancini 
Technical Owner @sbinlondon 
Status: MVP merged

Secondary Priorities on Roadmap:
----------------------------
Stretch Goal: Update old static pages from new design (Design owner @Memo-Es, Project owner  @piamancini ) #3176 
Small Improvements (@znarf): 
- Killing host Collectives 
- Collective to collective across hosts (spec)
- Pledges issue (Ben)

Biz Dev Deliverables
-----------------------
(Biz Dev) Update OCF Board / Compliance (@piamancini)
(Biz Dev) Update Ford / Sloane Proposal (@piamancini)
(Biz Dev) Sign OSC Agreement with John Hopkins (Alyssa)
(Biz Dev) Push Github Sponsors (@alanna)
(Biz Dev) Grow the COVID-19 groups for OCF (Kayla)

**Comment by kewitz** [comment]
Updated the issue with PayPal Payout project issue.

**Comment by piamancini** [comment]
Updated Figma Design for Managing Subscriptions cc @sbinlondon

**Comment by sbinlondon** [comment]
Updated with subscriptions issue
