### ISSUE TITLE
Should we kill pledges?

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3135]
# Acknowledging
- That maintaining code for a feature always takes time (eg. tests need to be updated, bugs...)
- That unmaintained features can contain security issues, or be a vector for privilege escalation
- That the bigger/more complex the code base, the harder it is for newcomers to get on board

# Data

- Currently pledged collectives: 65
- Total amount currently pledged: $6,283
- Collectives claimed: 9 (`techx,ui-avatars,hyperapp,we-cropper,exercism,octobercms,sentinel,prettier,thetorproject`)
- Amount donated through honored pledges: _not enough data to know_

# Pros

- The number of project claimed is relatively low
- Pledges are a nice communication tool, but you can arguably achieve the same effect by contacting the projects directly and ask them to register on Open Collective.
- It's not a flow that we're testing often, we may miss regressions (tho we added some tests recently to make it stronger)
- It adds some complexity in the code, it's hard to differentiate between pledges and pending orders

# Cons

- Two big projects have come out of pledges: Tor and Prettier
- It's a good argument for a project to register to know that there already are contributors ready
- It works

**Comment by Betree** [comment]
My personal opinion is that we don't have enough data to make an informed decision. The total amount donated through honored pledges in particular is a very important piece that we don't have today.

My recommendation would be to add the metrics required to track this feature's success properly and revisit this discussion in 6 months.

**Comment by Betree** [comment]
Two interesting ideas were suggested today:
1. We can simplify pledges by removing all the logic of "Pending orders" for them (just collect the emails of pledgers).
2. On a similar idea, we can remove all the logic to claim a collective and instead ask people to contact support if they want to do so. This also makes sense because the path to claim collectives is actually the less tested.

**Comment by alanna** [comment]
We recently had a support ticket about this. The maintainer claimed the Collective, and then was confused/upset that the promised money wasn't there. I had to explain to them that we never collected any credit card numbers, and we just notified anyone who pledged to complete their payment but can't force them.

I agree with @Betree that we could really simplify the feature without losing much in terms of how it functions as a marketing tool.

Note: We may be working toward a lot more $ coming via pledges through Back Your Stack. I'm not sure what the flow will be for dependencies that show up on BYS which don't have a Collective set up, but I imagine inviting those users to pledge to the projects would be a good option.

**Comment by Betree** [comment]
From the feedback received and recent evolution, I conclude that we don't want to kill the feature now. We've already removed the buttons to claim the collective (replaced by a "contact support" CTA) - that will hopefully reduce the support work and simplify things.

I'll create another issue now to remove all the code related to claiming the collective. 

Thank you!
