### ISSUE TITLE
[PROJECT] Subscriptions management revamp

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3137]
## Purpose
The purpose of this project is to revamp the management of subscriptions, to make it easier and more clear for users to do things like cancel (see opencollective/opencollective#1581)

## Owner
Tech: @sbinlondon 
Design: @Memo-Es 

Figma link: https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC.com%5D-Production-Ready-%E2%9C%85?node-id=3572%3A0

## Prioritization

- Does this serve our mission?

- Will this help to make us financially sustainable within a year?

Would probably contribute towards this. Though it will make it easier for users to cancel their subscriptions, it might also make it easier for them to change it in ways that would contribute positively, like increasing their subscription or updating it if a payment method is going to run out soon.

- Is it feasible to build and maintain with our team and runway?

Yes - if the project stays in scope, we can finish and deliver it in this short quarter.

- Can this make us move faster?

Yes, it would probably decrease the number of support tickets 

- Does this increase quality and not technical debt?

Yes, hopefully

- Will this bring us more Collective and financial contributors?

Probably, if it's easier to find the subscriptions page and easily manage them once you've started

- Is this already solved elsewhere or is it our unique contribution?

not relevant

## Roadmap & Timeframe
(Key milestones or phases and estimated delivery dates, including specs, design, feature development, feedback, marketing/comms, and documentation)
Design: ready as of **May 13**
Development: Week beginning May 11 til mid June?
Feedback: continuous but final round mid June
Deadline/release: end of June

## Success metrics
* fewer support tickets regarding subscriptions (cancellations, where to find them, etc)
* anything else @piamancini ?

**Comment by sbinlondon** [comment]
@Memo-Es some design q's, mostly just confirming my assumptions from the design

Is this a new banner component or a revamp of the existing one (below)?

![Screenshot 2020-05-13 at 19 31 59](https://user-images.githubusercontent.com/37520401/81850849-7325c980-9550-11ea-9c83-61974152f40a.png)

This looks like I'll need to add a 'Subscriptions' section to a user's collective profile page?

![Screenshot 2020-05-13 at 19 33 06](https://user-images.githubusercontent.com/37520401/81851038-c26bfa00-9550-11ea-9f82-59ddfe0a833d.png)

And it seems as though I'll need to make a few pop-up components?

![Screenshot 2020-05-13 at 19 36 33](https://user-images.githubusercontent.com/37520401/81851291-2098dd00-9551-11ea-87ea-d1039bf03ec6.png)

**Comment by Memo-Es** [comment]
> Is this a new banner component or a revamp of the existing one (below)?

It is an existing banner like the one we use when a user submits an expense.

> This looks like I'll need to add a 'Subscriptions' section to a user's collective profile page?

Yes

> And it seems as though I'll need to make a few pop-up components?

Correct

@sbinlondon

**Comment by sbinlondon** [comment]
Meeting with @znarf 

* MVP all the pop-ups - there are a lot, figure out which are the priority (i.e. why are you cancelling and giving feedback can be after MVP)
* will the 'Subscriptions' section on the collective page be public? Everything on OC is public by default so it makes sense that it would be
* right now when you update a subscription (changing the amount), this cancels the old subscription and creates a new one. So this would clog up the 'cancelled subscriptions' filter. It is out of scope for us to fix now but we should be aware this is the behaviour.
* the Subscriptions page should stay in addition to this new section, and we should update it with the new components to make it look better and in line with new designs
* for a user Collective page, only the user can edit the subs; for an org or a Collective, all the admins are able to edit the subscription
* the 'default' is what people viewing a Collective profile will see, where as user who are able to edit the subscription will see the 'active' subscription card (that says 'manage subscription')
* we will need to write a GraphQL v2 mutation for updating a recurring financial contribution: changing the amount, the payment method, the frequency, the tier
* what is the pop-up? is it a modal? how does it appear on the page? does it replace the content in the card? does it appear over the whole page as a modal? @Memo-Es

**Comment by sbinlondon** [comment]
Answers to questions/concerns and still needed:



> Questions/concerns:
> 
>     * what is the pop-up? is it a modal? how does it appear on the page? does it replace the content in the card? does it appear over the whole page as a modal? there's nothing in the design that shows us how these components fit together yet @Memo-Es

From what I understand, replaces content in the card, but it will be good to still have a design on Figma depicting this

>     * we also need to see a design for when there is an error - will the notification bar turn red? do we show the error elsewhere? @Memo-Es

Design has said they'll add this in the Figma

>     * it's not clear in the design - when we add a new payment method, do we go back to the list of payment methods and have to select the new payment method from the list, or do we just automatically use the payment method when we add it? @Memo-Es

Decided that it makes the most sense and it most secure to add the new payment method and the go back to the list of payment methods, including this new one, for the user to choose it

>     * the postcode and cvc is missing from the 'add new payment method' pop up @Memo-Es

This will be added to the design in Figma

>     * why is 'changing payment method or amount' under the cancellation reasons? if they select this do we then do another pop up screen to tell them that they can actually do that in this same flow? @Memo-Es

We have decided that this will not be included in the MVP

**Comment by Memo-Es** [comment]
**Update payment method**

![Screen Capture on 2020-05-18 at 14-17-29](https://user-images.githubusercontent.com/49539954/82251523-f5c4d500-9912-11ea-8b4e-e17f52e53697.gif)

@sbinlondon

**Comment by Memo-Es** [comment]
**Update payment method**

![Screen Capture on 2020-05-18 at 14-25-05](https://user-images.githubusercontent.com/49539954/82251872-a0d58e80-9913-11ea-85d6-c2dce082cb52.gif)

@sbinlondon

**Comment by Memo-Es** [comment]
**Update contribution tier**

![Screen Capture on 2020-05-18 at 14-31-28](https://user-images.githubusercontent.com/49539954/82252417-910a7a00-9914-11ea-8197-ef5c80a65e60.gif)

@sbinlondon

**Comment by Memo-Es** [comment]
**Cancel contribution**

![Screen Capture on 2020-05-18 at 14-19-01](https://user-images.githubusercontent.com/49539954/82252489-b4cdc000-9914-11ea-89e1-c45aa465f603.gif)

@sbinlondon

**Comment by sbinlondon** [comment]
Thanks for these @Memo-Es! 🙌

**Comment by sbinlondon** [comment]
@Memo-Es Could I get a view of what happens when we click 'Activate subscription' on a cancelled subscription? Does it just execute immediately or will there be dialogs like with cancelling?

<img width="339" alt="Screenshot 2020-05-19 at 17 36 58" src="https://user-images.githubusercontent.com/37520401/82353496-71984d80-99f7-11ea-8056-58a9f497a4c3.png">

**Comment by Memo-Es** [comment]
I think it would be its something like this:

<img width="308" alt="Screen Shot on 2020-05-19 at 23-00-35" src="https://user-images.githubusercontent.com/49539954/82403527-abcc1400-9a24-11ea-903c-f1f2e8d1d3cb.png">

**Comment by Memo-Es** [comment]
**Error message**


![Screen Capture on 2020-05-20 at 09-01-59](https://user-images.githubusercontent.com/49539954/82459124-288adc80-9a7d-11ea-9a42-464610377201.gif)

@sbinlondon

**Comment by sbinlondon** [comment]
Everything is merged and released onto staging, will release onto prod tomorrow and then remove the feature flag if that goes well 🎉 👯

**Comment by sbinlondon** [comment]
Feature flag removed, released on prod/staging, and removed reactivation of contributions until we can deal with fees on top. I will make a separate issue for this.
