### ISSUE TITLE
Subscriptions management: create subs card component

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3138]
<img width="865" alt="Screenshot 2020-05-20 at 14 22 28" src="https://user-images.githubusercontent.com/37520401/82451031-5c79f800-9aa5-11ea-93cc-f74a25733c57.png">

Includes 5 states:

- [x] default
- [x] active
- [ ] ~hover~
- [ ] ~prepaid~
- [x] inactive

**Comment by vickywane** [comment]
Hi, i would like to try build this. 

Can you give some more information?

**Comment by sbinlondon** [comment]
@vickywane My apologies for the confusion, I forgot to add the `team` label. This is part of a project that will be completed internally.

**Comment by vickywane** [comment]
Alright.

**Comment by sbinlondon** [comment]
UPDATE: work needs to be done re: hover card (it's a bit jumpy on the transition now) and also need to add the prepaid card state

**Comment by vickywane** [comment]
Hi @sbinlondon, i noticed znarf took off the `team` label. 

I am currently trying to find your last work on this. 

I found this ;
https://github.com/opencollective/opencollective-frontend/pull/4226.

**Comment by znarf** [comment]
@vickywane Sorry if I removed the "team" label, it's not an official tag that we committed to use and haven't read the discussion. With that context, it doesn't mean anything that I removed it, @sbinlondon is still assigned and actively working on it.

**Comment by sbinlondon** [comment]
Update:

Hover state was removed after team discussion.
