### ISSUE TITLE
CloudFlare blocking requests

### ISSUE THREAD

**Issue by zachleat** [opencollective/opencollective#3139]
Are there new docs that replace this? https://docs.opencollective.com/help/contributing/development/api/members

CloudFlare is blocking requests, which is fine in the browser but not great from my node scripts 😅

**Comment by znarf** [comment]
1) Yes, this should be marked as deprecated. It's working but if you're using it, we may ask you to upgrade at some point in the future. Use our [GraphQL API v2](https://medium.com/open-collective/open-collective-graphql-api-preview-3b42ed1d55ff) instead. I can point to integrations we did with [eslint](https://github.com/eslint/website/blob/master/_tools/fetch-sponsors.js), [babel](https://github.com/babel/website/blob/master/scripts/download-sponsors.js) and others.

We haven't launched GraphQL API v2 officially yet but it's 100% supported and we'll update the documentation soon.

2) Sorry, it's temporary, we have some problems today. We have absolutely no plan to stay "Under Attack" in the future.

**Comment by zachleat** [comment]
No worries at all—appreciate y’all ❤️ Thanks for the link
