### ISSUE TITLE
Expense notification should include submitter name

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3142]
This email notification should also include the name of who submitted it.

<img width="937" alt="Screen Shot 2020-05-14 at 3 18 56 PM" src="https://user-images.githubusercontent.com/5498878/81888908-6cea2880-95f6-11ea-8af3-2de0c8ee346b.png">

**Comment by jamesgeorge007** [comment]
I would love to give it a shot 🙌

**Comment by snitin315** [comment]
@jamesgeorge007 can I take this up If you aren't working on this?
