### ISSUE TITLE
Widgets not displaying all contributors and backers

### ISSUE THREAD

**Issue by sloria** [opencollective/opencollective#3143]
**Describe the bug**

The Contributors and Backers widgets are not displaying all the relevant people.

**To Reproduce**

Go to https://github.com/marshmallow-code/marshmallow#contributors

**Expected behavior**

All code contributors and backers are displyed.

**Screenshots**

Only 6 contributors and 1 backer shows.

![Image 2020-05-14 at 11 01 42 AM](https://user-images.githubusercontent.com/2379650/81950750-5e8a1580-95d2-11ea-8613-729b3aef49d6.png)

**Comment by znarf** [comment]
We have some issues right now, including our image service. This should get better soon.

**Comment by sloria** [comment]
Sounds good. No urgency on my end--just noticed it while poking around.
