### ISSUE TITLE
Expense payout via Bank account does not show up in expense email

### ISSUE THREAD

**Issue by josegonzalez** [opencollective/opencollective#3144]
**Describe the bug**

I just received a bank payout (well, I think I did, still waiting on it to drop in the bank account) for the Dokku collective. The email notification has blank payout information.

**To Reproduce**
1. Setup an expense that is paid to a bank account
2. Check the email (that gets sent out once it gets approved)
3. Email is missing payout method

**Expected behavior**

Payout method shows up :)

**Screenshots**

<img width="511" alt="Screen Shot 2020-05-14 at 7 05 25 PM" src="https://user-images.githubusercontent.com/65675/81994452-e9403400-9615-11ea-8ae8-db0600f5ba87.png">

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.15.5
 - Browser: Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context**

The bank payout functionality is new, so this is likely a small oversight.

**Comment by piamancini** [comment]
cc @kewitz
