### ISSUE TITLE
Expense update says approved but actually rejected

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3146]
https://opencollective.com/osc/expenses/18122

This expense was rejected, and now shows as rejected status. But in the comments it says "expense approved".

<img width="776" alt="Screen Shot 2020-05-16 at 1 17 15 PM" src="https://user-images.githubusercontent.com/5498878/82106826-9d0d0500-9777-11ea-8d25-74326fd55b2a.png">

<img width="820" alt="Screen Shot 2020-05-16 at 1 17 25 PM" src="https://user-images.githubusercontent.com/5498878/82106830-a007f580-9777-11ea-9c57-7307e42c4137.png">

**Comment by znarf** [comment]
Was fixed in https://github.com/opencollective/opencollective-api/pull/3908
