### ISSUE TITLE
Allow non-admins to make Events

### ISSUE THREAD

**Issue by mixmix** [opencollective/opencollective#3147]
## User story 

As an admin I can white-list another OC user so that they can make OC Events, without having to worry they about giving them full admin privileges

**My use case**:  _I want to use OC Events to allow people to post up event proposals. If 10 people attend or buy tickets, we will sponsor the event and ensure the host is well paid. So I want a wide range of people to be able to post... but I don't want a wide range of people to be able to approve expenses_

## Best solution for this problem

Having a list of users who are allowed to author + admin Events.

## MVP

Having a toggle which turns off the safety on our OC so that anyone who contributes to a collective or is and admin can author Events.
Also as an admin I can still delete Events which I don't like

## Metrics 

- Admins aren't giving people they don't know that well admin permissions just to save time.
- Admins aren't stressed by having to manually post all events on behalf of others

## Documentation 
_The goal of the documentation should be to make it easier for others to do this_

**Comment by mixmix** [comment]
hmm I see I can add someone as a "core contributor"
I can't see if they have permissions to make events ... but that could be sweet

**Comment by Betree** [comment]
@mixmix Core contributors can indeed create events, that's the only special permission that they have. I actually wanted [to deprecate that behavior](https://github.com/opencollective/opencollective/issues/3113), but we may keep it if it solves your issue.

**Comment by mixmix** [comment]
yeah the language / labels about core contributors + admins is pretty confusing atm

**Comment by znarf** [comment]
Can we close this?

We don't have an issue yet to track the "Core Contributors" language but this is something that's still really bothering me.

**Comment by Betree** [comment]
> We don't have an issue yet to track the "Core Contributors" language but this is something that's still really bothering me.

Same here
