### ISSUE TITLE
Monthly recurring revenue is inaccurate (probably)

### ISSUE THREAD

**Issue by sloria** [opencollective/opencollective#3158]
**Describe the bug**

The displayed "Monthly recurring" for marshmallow appears to be inaccurate.

**To Reproduce**

Go to https://opencollective.com/marshmallow#section-budget and hover "Estimated Annual Budget".

It only shows $15.00

![Image 2020-05-18 at 10 03 34 AM](https://user-images.githubusercontent.com/2379650/82222170-e895ef00-98ee-11ea-968e-2326354faba8.png)

**Expected behavior**

Based on last month's revenue, it should be ~$145.

**Additional behavior**

It's _possible_ that nearly all marshmallow's backers have stopped contributing, but seems less likely than a bug in the implementation of https://github.com/opencollective/opencollective-frontend/pull/4119.

**Comment by Betree** [comment]
Hi @sloria, thanks for the report. There's indeed something wrong, I've opened https://github.com/opencollective/opencollective-api/pull/3939 to try and fix that.

**Comment by Betree** [comment]
@sloria fix deployed. The amount displayed for monthly recurring on https://opencollective.com/marshmallow#section-budget is now $175. I checked manually and the number seems to match the recurring subscriptions for the collective.

**Comment by sloria** [comment]
Thanks for fixing that @Betree .

Does the calculation subtract fees and deductions?

From the [OP](https://github.com/opencollective/opencollective/issues/1585):

> The current amount of recurring donations (after fees/deductions) is easy to find for collective owners.

**Comment by Betree** [comment]
@sloria It does not. I've opened another issue to fix that: https://github.com/opencollective/opencollective/issues/3226
