### ISSUE TITLE
Donating with Credit Card should be unavailable for Hosts without Stripe

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3159]
**Describe the bug**

Donating with Credit Card should be unavailable for Hosts without Stripe

**To Reproduce**

1. Create a new Fiscal Host with just Bank Account connected
2. Host a new collective on this Host
3. Try to contribute with a Credit Card

**Screenshots**

<img width="867" alt="Capture d’écran 2020-05-18 à 17 43 41" src="https://user-images.githubusercontent.com/806/82232745-4cd8a300-992f-11ea-9059-ec26ec759588.png">

NOTE: the HostCollectiveId=null in the screenshot is irrelevant, don't pay attention to it

**Comment by sbinlondon** [comment]
As per Slack comments, I'm working on this.

Will add a new field to host accounts (`server/graphql/v2/object/Host.js`) called `supportedPaymentMethods` that will return a simple array like `supportedPaymentMethods: ['CREDIT_CARD', 'BANK_TRANSFER', 'PAYPAL']`

**Comment by sbinlondon** [comment]
Starting to address in opencollective/opencollective-api#4343

**Comment by sbinlondon** [comment]
Merged and will be implemented in new Contribution Flow
