### ISSUE TITLE
[PROJECT] Contribution flow update

### ISSUE THREAD

**Issue by cuiki** [opencollective/opencollective#3164]
## Purpose
We want to double down on contributions as a way to make the organization sustainable, so the design of the right flow is key so people have a better experience contributing to Open Collective as an initiative and to any of the Collectives in the platform.

## Owner
@piamancini and @Memo-Es 
Tech: @sbinlondon @Betree 

*Note: Project owner responsibilities include coordinating all the different people that need to contribute to the project, defining specs and goals, communicating project progress, being the point person for decisions, QA, documentation, and a plan for ongoing maintenance. If the project owner can't continue, they need to hand the role over to another person explicitly.*

## Prioritization

- Does this serve our mission?
Yes, it creates a better way for us to be sustainable in the long therm. Plus it aligns to our community-driven strategy revenue.

- Will this help to make us financially sustainable within a year?
Yes, we aim to rise the amount of contributions made in the platform thus more revenue flowing in for the organization.

- Is it feasible to build and maintain with our team and runway?
Yes, we can split our goals and launch in a cadency of small releases.

- Can this make us move faster?
It would make us reach our financial goals sooner.

- Does this increase quality and not technical debt?
TBD

- Will this bring us more Collective and financial contributors?
It will bring us more financial contribution as an immediate consequence, and, we can start communicating our new contributing features and attract more Collectives to raise money on the platform.

- Is this already solved elsewhere or is it our unique contribution?
There are other donation softwares like gofundme and patreon. We should focus our use case to raise money for Collectives.

## Phases & Timeframe
* Current contribution experience analysis and project cover
* User testing
* Prioritization and release roadmap
* First design proposal and mockups
* First MVP launch
* Iteration and second design proposal

## Success metrics
* Amount of new contributions 
* Less support tickets related to contributions

---
## Current flow
| Individual/Organization  | Contribute as  | Contribution  | Payment details  | Summary  | Success  |
|---|---|---|---|---|---|
| ![Empty](https://user-images.githubusercontent.com/49539954/83593601-c1603400-a522-11ea-9501-3da2cfb63676.png)  | ![Personal profile](https://user-images.githubusercontent.com/49539954/83593647-db017b80-a522-11ea-9018-b4516a08fea9.png) | ![Empty](https://user-images.githubusercontent.com/49539954/83593699-01271b80-a523-11ea-857f-a2ce01a8af75.png) | ![Default](https://user-images.githubusercontent.com/49539954/83593722-100dce00-a523-11ea-90fa-5e4de363b214.png) | ![Summary](https://user-images.githubusercontent.com/49539954/83593746-2025ad80-a523-11ea-8545-720d82fd852c.png)  | ![Public Message](https://user-images.githubusercontent.com/49539954/83593771-2ddb3300-a523-11ea-8d80-5d1579d5fd87.png) |

## Releases proposals (TBD)
* Require no log in to contribute (Minding the implications)
* Design a better contribution flow including sign up (Less friction)
* Include button in homepage to contribute directly to Open Collective movement (Open Collective inc)
* Improve sharing capabilities of Collectives and Collective tiers

[Production Figma link](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC.com%5D-Production-Ready-%E2%9C%85?node-id=4558%3A10469)

**Comment by Memo-Es** [comment]
### Update - 1st proposal for the new contribution flow
---

| **1. Contribution**  | **2. Contribute as**  | **3. Payment info**  |
|---|---|---|
| <img width="1280" alt="Desktop" src="https://user-images.githubusercontent.com/49539954/83590619-c8d00f00-a51b-11ea-80ca-e0a4ede45d7f.png">  | <img width="1280" alt="Desktop" src="https://user-images.githubusercontent.com/49539954/83590626-cc639600-a51b-11ea-9d4a-302fcc2a9470.png">  | <img width="1280" alt="Desktop" src="https://user-images.githubusercontent.com/49539954/83590634-cf5e8680-a51b-11ea-93a5-d5515ab6ca58.png">  |


|**Primary updates**   |   |
|---|---|
| - We shortened the process from 4 steps to 3 steps: Contribution, Contribute as, and Payment info (See below)  | <img width="630" alt="Screen Shot on 2020-06-02 at 21-47-40" src="https://user-images.githubusercontent.com/49539954/83590163-bacdbe80-a51a-11ea-9111-398b5312178c.png">  |
| - We suggest to include an indicator of the security of the transaction in the platform  | <img width="346" alt="Screen Shot on 2020-06-02 at 21-49-33" src="https://user-images.githubusercontent.com/49539954/83590268-fd8f9680-a51a-11ea-8e9a-3365b9b7a1a2.png">  |
| - We introduced the "Guest contribution" so users don't need to register to contribute. Anyway, they can Log in if they already have an account  | <img width="701" alt="Screen Shot on 2020-06-02 at 21-50-45" src="https://user-images.githubusercontent.com/49539954/83590449-5fe89700-a51b-11ea-952b-d3241acf79d7.png">  |

---
**Whats next:**
* Log in screen 
* Success page

**Comment by piamancini** [comment]
I think this works and it seems like a manageable change. 
@Betree you ok with the gift cards checkmark and redeem there? 
@znarf What should we say in the Security Indicator? I guess we need to link to to a page in the docs, but we need copy for it.

**Comment by Betree** [comment]
It's a very good idea to add the ability to use the gift card from the flow. I however don't understand why not displaying that as another payment method option in the list, similar to what we do for credit cards. 

Gift cards are just another payment method option, and you don't want people to set their credit card details if they're using a gift card.

![image](https://user-images.githubusercontent.com/1556356/83740958-db4f6300-a657-11ea-844c-7f1ecef32be1.png)

**Comment by Betree** [comment]
Adding a small note here to mention that it would be great to take this as an opportunity to refactor a bit the code of the contribution flow. There are two things that we should ideally address (or at least not reproduce in the new code):
- `components/contribution-flow/index.js` is too big, there's too much logic in there. We should better split components.
- There's a lot of logic related to managing state and validating inputs. This is something `formik` could help with, so we should try to see if there's a way to progressively adopt it in there.

**Comment by Memo-Es** [comment]
## Update - Contribution flow - Different cases
---

### 1. Guest Contribution
| **1. Contribution -  Empty**  | **2. Contribute - Filled**  | **3. Contribute as - Empty**  | **4. Contribute as - Filled**  | **5. Payment info**  | **6. Contribution details and success**  |
|---|---|---|---|---|---|
| ![Guest contribution 1](https://user-images.githubusercontent.com/49539954/84726040-98439880-af51-11ea-81a8-afd81130532f.png)  | ![Guest contribution 2](https://user-images.githubusercontent.com/49539954/84726043-9974c580-af51-11ea-9077-7319c5949819.png)  | ![Guest contribution 3](https://user-images.githubusercontent.com/49539954/84726046-9aa5f280-af51-11ea-8d36-2a6805ccb724.png)  | ![Guest contribution 4](https://user-images.githubusercontent.com/49539954/84726049-9aa5f280-af51-11ea-93f4-41cacf5fb8e2.png) | ![Guest contribution 5](https://user-images.githubusercontent.com/49539954/84726050-9b3e8900-af51-11ea-96f0-4d1b1a4dd95c.png) | ![Guest contribution 6](https://user-images.githubusercontent.com/49539954/84726051-9b3e8900-af51-11ea-97eb-8fcacc13dda7.png)

---

### 2. Guest Contribution of more than $5k
| **1. Contribution -  Empty**  | **2. Contribute - Filled**  | **3. Contribute as - Empty**  | **4. Contribute as - Filled**  | **5. Payment info**  | **6. Contribution details and success**  |
|---|---|---|---|---|---|
| ![Guest contribution 1](https://user-images.githubusercontent.com/49539954/84726040-98439880-af51-11ea-81a8-afd81130532f.png)  | ![Contribute as guest w address 2](https://user-images.githubusercontent.com/49539954/84727933-c2975500-af55-11ea-8f85-e586ea4ce846.png)  | ![Contribute as guest w address 3](https://user-images.githubusercontent.com/49539954/84727935-c3c88200-af55-11ea-8c51-8e0ce5492a33.png)  | ![Contribute as guest w address 4](https://user-images.githubusercontent.com/49539954/84727937-c4611880-af55-11ea-872a-d58333e0cfe4.png) | ![Contribute as guest w address 5](https://user-images.githubusercontent.com/49539954/84727939-c4f9af00-af55-11ea-8c9b-34a9662244ef.png) | ![Contribute as guest w address 6](https://user-images.githubusercontent.com/49539954/84727940-c5924580-af55-11ea-8295-074a31fe864e.png)

---

### 3. Recurring Contribution
| **1. Contribution -  Empty**  | **2. Contribute - Filled**  | **3. Contribute as - Empty**  | **4. Contribute as - Filled**  | **5. Payment info**  | **6. Redirect screen**  | **7. Contribution details and success**  |
|---|---|---|---|---|---|---|
| ![Recurring contribution 1](https://user-images.githubusercontent.com/49539954/84728223-6254e300-af56-11ea-841d-44ef14120200.png)  | ![Recurring contribution 2](https://user-images.githubusercontent.com/49539954/84728227-641ea680-af56-11ea-925c-a54f8494928e.png)  | ![Recurring contribution 3](https://user-images.githubusercontent.com/49539954/84728228-64b73d00-af56-11ea-9da2-ca13e8151c58.png)  | ![Recurring contribution 4](https://user-images.githubusercontent.com/49539954/84728230-654fd380-af56-11ea-8bc8-25bac6973e77.png) | ![Recurring contribution 5](https://user-images.githubusercontent.com/49539954/84728231-65e86a00-af56-11ea-8ee2-e50ea70de585.png) | ![Recurring contribution 6](https://user-images.githubusercontent.com/49539954/84728233-66810080-af56-11ea-8d32-76a718fed65f.png) | ![Recurring contribution 7](https://user-images.githubusercontent.com/49539954/84728235-66810080-af56-11ea-8d3c-f1bf7c4d2abd.png)

---

### 4. User contribution
| **1. Contribution -  Empty**  | **2. Contribution - Filled**  | **3. Contribute as**  | **4. Payment details**  | **5. Contribution details and success**  |
|---|---|---|---|---|
| ![User contribution 1](https://user-images.githubusercontent.com/49539954/84728964-2c186300-af58-11ea-8234-be0ae06197b8.png)  | ![User contribution 2](https://user-images.githubusercontent.com/49539954/84728967-2e7abd00-af58-11ea-8b6a-e38eae407378.png)  | ![User contribution 3](https://user-images.githubusercontent.com/49539954/84728970-2f135380-af58-11ea-87a4-76861ae25449.png)  | ![User contribution 4](https://user-images.githubusercontent.com/49539954/84728971-2fabea00-af58-11ea-8ad5-2c9bbecaf5fb.png) | ![User contribution 5](https://user-images.githubusercontent.com/49539954/84728973-2fabea00-af58-11ea-9527-4af5813ebf86.png)

**Comment by piamancini** [comment]
Thanks Memo!  I'll update this issue with the comments from accounting. 

I am not a fan of the OC logo with the little prize tails. We don't have it anywhere else and it's a regression to the old look and feel. Let's use stars, or anything else from the new illustrations please. 

The copy currently on the flow for fees on top I think it's better than the proposed version here. 

In the +$5000 version we need to explain why we are asking for their address - please put a placeholder like: 'For donations over $5000 we are required to keep an address for our filings'

Same styling comment for the success page, that blue background feels like a regression. Please use the current styles. 

I really like the flow updates and how we only display info if they needed after first steps are done.

**Comment by piamancini** [comment]
@Memo-Es I can confirm: 

A) Donations under $250 don't need a tax deductible receipt so we can avoid validating their email (we send them a tax deductible receipt via email)

B) Donations between $250 - $5000 must have a validated email address for us to send them a receipt. 

C) Donations above $5000 (accumulated) require both validated email address and physical address for 990 filing.

**Comment by alanna** [comment]
Will guest contributors be signed up for updates from the Collective they supported? If not, can we have a tickbox in the process where they can opt in to that? I see the option to subscribe to the platform newsletter, and that's good as-is, but Collective updates are another thing.

Just checking, they have to create a profile to do a recurring contribution, right? Because otherwise how can they manage it on an ongoing basis?

**Comment by piamancini** [comment]
> Just checking, they have to create a profile to do a recurring contribution, right? Because otherwise how can they manage it on an ongoing basis?

correct

**Comment by sbinlondon** [comment]
For devs working on this (@Betree) I have made a flow chart to help think about states (logged in vs guest, contributing over $5000 vs under $5000, recurring vs one-time contribution) and how that effects what is displayed. I know we have mock-ups but for me this helps me to visualise and organise in my head how the components will look at change based on these conditions. I hope it's also helpful, especially since we'll be handing over and working on it in tandem.

![contributionflowchart](https://user-images.githubusercontent.com/37520401/87680124-f0e69b00-c774-11ea-934f-d0a9d978fba9.png)

**Comment by Betree** [comment]
Shipped :rocket:
