### ISSUE TITLE
[GitBook] Redirect rules don't work anymore

### ISSUE THREAD

**Issue by contraexemplo** [opencollective/opencollective#3165]
## Issue
On May 18th, François reported that a redirect rule for the path `https://docs.opencollective.com/help/about` wasn't working anymore. At first, it seemed like GitBook renamed a few files without warning us, and a simple change to `.gitbook.yaml` would solve this problem (see [this commit](https://github.com/opencollective/documentation/commit/426c61571fdc595d475776e848107428fc83a955#diff-89bd89c35cb6d9eb022b1a677273b55a)), as it did many times before. However, upon further investigation, we have to additional problems:

- The redirect rule now adds a *second* `help` to the URL; instead of sending the user to `https://docs.opencollective.com/help/about/introduction`, it sends the user to `https://docs.opencollective.com/help/help/about/introduction`.
- Instead of redirecting someone to `docs.opencollective.com/help`, the integration tool on GitHub sends them to `https://docs.opencollective.com/help/help/help`.

After investigating this issue for almost two days, I have reasons to believe that GitBook's GitHub integration is currently broken, and their deployment process isn't reading [content configuration files](https://docs.gitbook.com/integrations/github/content-configuration) correctly. Since I was able to reproduce the same bug in other GitBook spaces, I also believe this is a server-side issue that cannot be fixed by ourselves. That's why I'm opening this issue.

## Next steps
I'll email GitBook about this issue, though the process to do that has become quite... slow. But beyond that, I'm not sure how to proceed (besides adding this to the reasons why issue #2595 is still relevant). Do you have any other suggestions? Please let me know.

## Task list
- [x] Contact GitBook
- [x] Report reply

**Comment by contraexemplo** [comment]
**Update:** This bug is still around, and I was finally able to submit a bug report today after someone from their team contacted me.

**Comment by contraexemplo** [comment]
**Update:** Bug is still around. Issue escalated to their development team, according to the team member taking care of my case.

**Comment by alanna** [comment]
@znarf is there any way to temporarily add a hack to redirect this URL until the bug is fixed? Github has shared the old one a few places and they're concerned that it's 404 now.

old URL: https://docs.opencollective.com/help/collectives/github-sponsored-organizations
new URL: https://docs.opencollective.com/help/collectives/github-sponsors

**Comment by contraexemplo** [comment]
**Update:** The saga continues—I received an email telling me it should be solved by now, but my daily tests return the same results. When exploring our GitBook settings, the Advanced settings panel indicated a custom domain isn't being used, but general organization settings state otherwise (as reported by Ben). This was reported to the GitBook team today.

**Comment by contraexemplo** [comment]
**Update:** The bug is still around. I found a workaround for the case @alanna mentioned above: editing the slug directly on GitBook and removing any redirect rules related to this particular URL. The side effect is that any mention of `https://docs.opencollective.com/help/collectives/github-sponsored-organizations` will give anyone a 404 with no remedy currently available (so all mentions to this particular page need to be modified), but `https://docs.opencollective.com/help/collectives/github-sponsors` is working perfectly fine.

I still haven't heard back from GitBook about the issues reported in my last comment.

**Comment by contraexemplo** [comment]
It's been more than a week since our last contact, and I haven't heard from them since. The issue, I'm afraid, is still around.

**Comment by contraexemplo** [comment]
GitBook has addressed the redirect problem with a fix, and all of our redirect rules are working again!

**Comment by Betree** [comment]
Fantastic, thanks for handling this one @contraexemplo!
