### ISSUE TITLE
Improvements to the 'download receipts' tool on profile page

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3168]
If I go to my profile and click 'transactions' I see a tool to download my receipts. There are a couple issues with it. 

![Screen Shot 2020-05-26 at 3 12 05 PM](https://user-images.githubusercontent.com/5498878/82856981-bd9d4200-9f63-11ea-8b4e-96963a118667.png)

1) It's called "download receipts" but when you click on it, it says "download invoices". An invoice is what I submit to be paid for my time. A receipt is the proof that I have paid money. It should be consistent and say "receipts".
2) If there are no receipts to show for the current month, it looks very odd. It should just say "none" instead of putting nothing there.

**Comment by vinuch** [comment]
Hi @alanna I’d like to have a go at this if it’s okay
