### ISSUE TITLE
oc's mails are getting sent to spam & marked as scam

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#317]
There seems to be some certification thing that we haven't done. 
<img width="854" alt="screen shot 2017-02-27 at 3 36 20 pm" src="https://cloud.githubusercontent.com/assets/3671070/23379232/2ac34204-fd04-11e6-82c3-ad330d163008.png">

**Comment by xdamman** [comment]
Weird. First time I see this. Has anyone else reported this?

We did the DKIM verification in the domain in our DNS records. From Cloudflare dashboard:
![](https://cl.ly/0I1p1y1D0C32/Screen%20Shot%202017-02-28%20at%2011.32.58%20AM.png)
not sure what else we can do.

Here are some stats from mailgun: (outgoing last 30 days, bounced, complaints, incoming)
![](https://cl.ly/0g3g2v311W1C/Screen%20Shot%202017-02-28%20at%2011.30.19%20AM.png)

The number of emails that we send out dropped on the 24th of February. @asood123 did you deploy something then to stop using mailgun to send server errors?
![](https://cl.ly/152E3b1G1P2C/Screen%20Shot%202017-02-28%20at%2011.30.53%20AM.png)

**Comment by asood123** [comment]
Lots of emails from us go to spam for me too

**Comment by asood123** [comment]
Reduction in emails due to .well-known rule in nginx.

**Comment by piamancini** [comment]
Ricky's emails from us where going to spam as well...

**Comment by xdamman** [comment]
I did add an option to sign each email individually. Let's see if that helps: https://github.com/OpenCollective/opencollective-api/pull/814
