### ISSUE TITLE
Admin can see Updates section when Updates is disabled

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3177]
Settings

<img width="1236" alt="Screenshot 2020-05-29 at 12 05 37" src="https://user-images.githubusercontent.com/806/83248056-c4ff5e00-a1a4-11ea-8603-935abd33078e.png">

Outcome (as Admin of the Collective)

<img width="1255" alt="Screenshot 2020-05-29 at 12 05 51" src="https://user-images.githubusercontent.com/806/83248067-c7fa4e80-a1a4-11ea-95d7-897fb827c6eb.png">

**Comment by sbinlondon** [comment]
@Betree You mentioned an ideal solution to this would be:

> In components/edit-collective/sections/Updates.js, change the logic of the checkbox to act as an opt-out if the collective.type is a collective (preferred solution)

Is this still the case? Happy to pick it up if so.

**Comment by Betree** [comment]
Proposal for merging the settings discussed in https://github.com/opencollective/opencollective/issues/3698 & https://github.com/opencollective/opencollective/issues/3396. Solving these issues should resolve this one too.

**Comment by sbinlondon** [comment]
Closing this issue since we're working on it in the Collective Navigation v2 project. Refer to these issues from now on https://github.com/opencollective/opencollective/issues/3744 https://github.com/opencollective/opencollective/issues/3755
