### ISSUE TITLE
Expense flow: opt-out for "Save this info for future payouts" not working

### ISSUE THREAD

**Issue by flaki** [opencollective/opencollective#3179]
**Describe the bug**
In the new expense flow when in the **Payout method** I select **New custom payout method**, then uncheck the checkbox for **Save this info for future payouts** the opt-out is not honored and Open Collective still seems to save the payout method which clutters up this dropdown.

Relatedly, UX-wise, all saved options are recalled as "Other" so selecting the appropriate one even when they are legitimately useful is a hassle. These would work *much* better if the options contained the custom text itself (ideally, shortened with an ellipsis with the hover tooltip showing a full or longer content snippet). These options are already listed under the **Other** group so this would be appropriate.

**To Reproduce**
1. Go to a [collective page](https://opencollective.com/rusttallinn/)
2. Click on 'Submit Expense'
3. Select the 'Invoice' expense type
4. Fill out the required expense information
5. In the 'Payout method' dropdown, choose 'New custom payout method'
6. Uncheck the 'Save this info for future payouts' checkbox
7. Submit the expense
6. Verify by repeating 1-5. that a new 'Other' option appears in the dropdown nevertheless

**Expected behavior**
The opt-out should prevent saving the custom payout settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/2089432/83304660-e7769300-a207-11ea-8e0c-eff789daf0ed.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox Nightly
 - Version: 78.0a1 (2020-05-24) (64-bit)

**Comment by Betree** [comment]
Thanks for the report @flaki the fix is on its way, the payout methods you previously marked as unsaved should disappear from your list after the update. 

I'm also going to implement your suggestion to show a resume of the payout method's content with an ellipsis in the select.
