### ISSUE TITLE
Collective's host is showing up in various places while not approved yet

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3183]
**Describe the bug**
While a collective is pending for approval, we show the host in various places:
- Transactions list
![image](https://user-images.githubusercontent.com/1556356/83521558-b20bc700-a4df-11ea-8b7f-97d0cbe198ec.png)
- Expense(s) page
![image](https://user-images.githubusercontent.com/1556356/83521983-4bd37400-a4e0-11ea-9aa3-288d393f4664.png)

And probably in some other places where we display the host.

**To Reproduce**
1. Go to '/create`
2. Create a collective
3. Submit an application to the host
4. Visit pages mentioned above like `/expenses`

**Expected behavior**
By default, the host should never be displayed before the collective is approved.

**Proposed fix**
- In `collective.host` resolvers (v1 + v2), don't return the host if not approved yet
- Add a `pendingApplication` endpoint to fetch the collective's pending host

**Comment by sbinlondon** [comment]
Also on the expense reimbursement form

<img width="825" alt="Screenshot 2020-10-08 at 17 02 50 1" src="https://user-images.githubusercontent.com/37520401/95484257-266fde80-0988-11eb-8150-295514d951a7.png">

**Comment by sbinlondon** [comment]
I tried proposed fix 1 by returning `null` for the host resolver if `collective.isApproved()` is `false` but I don't think this is a viable option.

For example: my collective's application is pending with HackerGarageMX (pic 1) but if we just don't return the host from the resolver, the frontend doesn't know I have an application in (pic 2)
<img width="1182" alt="Screenshot 2020-10-08 at 17 14 12" src="https://user-images.githubusercontent.com/37520401/95485597-e3166f80-0989-11eb-88fc-09d536681693.png">
<img width="1185" alt="Screenshot 2020-10-08 at 17 13 33" src="https://user-images.githubusercontent.com/37520401/95485595-e1e54280-0989-11eb-955c-a60a742afc7a.png">

Also if we don't return a host, we would be able to submit any expenses until it's approved, although maybe this would be a desired behaviour.
<img width="1266" alt="Screenshot 2020-10-08 at 17 12 32" src="https://user-images.githubusercontent.com/37520401/95485812-253fb100-098a-11eb-88cc-4dbbef9fd021.png">

I think we could do a 3rd solution, which is to just read `collective.isApproved()` on the frontend and if so, add a "pending" tag after the host name.

<img width="1233" alt="Screenshot 2020-10-08 at 17 49 41" src="https://user-images.githubusercontent.com/37520401/95489360-b6b12200-098e-11eb-84c1-5a98e43b6f7e.png">
<img width="758" alt="Screenshot 2020-10-08 at 17 48 22" src="https://user-images.githubusercontent.com/37520401/95489365-b749b880-098e-11eb-804b-b99d90ce13c3.png">

**Comment by Betree** [comment]
> I tried proposed fix 1 by returning null for the host resolver if collective.isApproved() is false but I don't think this is a viable option.
> 
> For example: my collective's application is pending with HackerGarageMX (pic 1) but if we just don't return the host from the resolver, the frontend doesn't know I have an application in (pic 2)

That's why the [specs](https://github.com/opencollective/opencollective/issues/3183#issue-629180849) propose:
- In collective.host resolvers (v1 + v2), don't return the host if not approved yet
- **Add a pendingApplication endpoint to fetch the collective's pending host**

> I think we could do a 3rd solution, which is to just read collective.isApproved() on the frontend and if so, add a "pending" tag after the host name.

Checking `isApproved` on the frontend side is ok, it's arguably less reliable because we'll need to do that check everywhere `host` is used. Also conceptually, you don't have a host until you've been approved.

But it may be simpler to implement, so I have no strong preference. Choose what you think is best :slightly_smiling_face:

**Comment by sbinlondon** [comment]
Right, I see, options 1 & 2 were meant to go together! Ok I will think about it.
