### ISSUE TITLE
Transferwise payment screen showing erroneous fee text

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3187]
When you go through the process of paying an expense via Transferwise, you see a screen instructing you to add fees. But there is no way to add the fees, and it's not clear what such fees would be for.

<img width="366" alt="Screen Shot 2020-06-02 at 9 54 36 PM" src="https://user-images.githubusercontent.com/5498878/83575251-37948300-a583-11ea-9eb6-3b6136925fc3.png">

If there is a need to be able to add fees, it should appear here. However, I don't think there is a need so actually everything about fees should just be removed from this screen.

**Comment by Betree** [comment]
To add some context on this, we still need to implement the "estimated fees" for this screen, which should look like the screenshot below. I however agree with what's reported here, we shouldn't say `Please add the corresponding fees...` when an "Automatic" payout method is selected.

![image](https://user-images.githubusercontent.com/1556356/83604378-5a6c6a80-a576-11ea-987c-bf25501d359e.png)

**Comment by Betree** [comment]
Will be resolved by https://github.com/opencollective/opencollective-frontend/pull/4328

Estimated fees will be implemented with https://github.com/opencollective/opencollective/issues/3089
