### ISSUE TITLE
Cell merging of tables

### ISSUE THREAD

**Issue by likeSomeOne** [opencollective/opencollective#3188]
There are horizontal merged cells in the document, but no vertical merged cells are found. There are already horizontal merged cells. Why there are no vertical merged cells? This should be improved. Thank you

**Comment by Betree** [comment]
Hi @likeSomeOne, could you explain which document you're talking about?

**Comment by znarf** [comment]
It doesn't seem to be related to Open Collective. Closing.

If I'm wrong, feel free to reopen and add screenshots to illustrate the problem!
