### ISSUE TITLE
Spacing issue at the bottom of the page(last section)

### ISSUE THREAD

**Issue by SimranArora123** [opencollective/opencollective#3189]
At the bottom of the page ,as we reduce the size of the screen the gap between the last section i.e"Was this page helpful" becomes less.

To Reproduce:
1. Go to "https://docs.opencollective.com/help/"
2. Scroll down to the bottom of the page
3. See error

Expected behavior
There should a some space below the text "Was this page helpful(with the icons)"

Screenshots:

![Screenshot (179)](https://user-images.githubusercontent.com/52946773/83620044-62460200-a5aa-11ea-8016-f89732d2f504.png)

**Comment by Betree** [comment]
Hi @SimranArora123, thanks for proposing your help. Unfortunately we use https://www.gitbook.com to host our docs, and they're not open-source anymore so we can only transfer the issue to them. I'm doing that now!

**Comment by Betree** [comment]
Issue fixed by Gitbook
