### ISSUE TITLE
Sidebar should automatically shift toward left, when we open a new page

### ISSUE THREAD

**Issue by SimranArora123** [opencollective/opencollective#3192]
Describe the bug:
(when we open the site in small screen )
In Sidebar when we want to go to a specific page it opens it in the background(at the back of the sidebar). 

1. Go to site
2. Click on sidebar menu.
3. And choose any section .

Expected behavior:
As in sidebar menu when we open a specific page it opens in the backgroud (behind the sidebar).
So in place of this the sidebar should automatically be shifted towards left .

Screenshot:
![pic](https://user-images.githubusercontent.com/52946773/83664107-2ed59880-a5e7-11ea-84cb-58f3e3b3b84f.jpeg)

**Comment by Betree** [comment]
Also reported to Gitbook. I'm closing both issues as there's nothing more we can do on our side to address them.

**Comment by Betree** [comment]
Issue fixed by Gitbook
