### ISSUE TITLE
Display bank account details in receive money settings

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3193]
Currently if you look at the place the bank account details are stored for a host to receive contributions, it just shows a button to edit the details without displaying them. It would be better to show the host admin the saved details so they could tell if they needed to be edited. 

<img width="896" alt="Screen Shot 2020-06-04 at 9 27 15 AM" src="https://user-images.githubusercontent.com/5498878/83691269-029d3480-a646-11ea-8ebd-f66b8a4e6fc4.png">

**Comment by znarf** [comment]
As we're trying to lower the numbers of `important` issues opened, removing the label as it didn't seem the most important of the list.

**Comment by BenJam** [comment]
Added the papercut label becuse this is view template stuff.

**Comment by alanna** [comment]
If we're not able to build this requested improvement, can we at least put *some* indication of whether a bank account has been set up or not? Right now a user looking at this has no way to know if the bank account details have been saves and are active, and it makes it difficult to support people having issues with it.

<img width="812" alt="Screen Shot 2021-09-10 at 10 40 12 AM" src="https://user-images.githubusercontent.com/5498878/132771920-b169d4ff-524f-49ab-8a89-34fbf1930a78.png">

**Comment by SudharakaP** [comment]
Just going through this issue, I noticed that the page has changed over time and we now have a `Remove Bank Details` button as well. I would suggest that we rename the `Edit Bank Details` button to `View/Edit Bank Details` so that it will be clear to the user that they could either view the bank account details by clicking on this button or edit it. 

@alanna : Does that make it clearer? 🤔

**Comment by alanna** [comment]
I *just* was thinking about this because today I went to that screen and
thought, again, "it would be much better if the bank details were displayed
here". So no, changing the name of the button doesn't help. It's obvious
that to edit the bank details you can probably see them too. The request in
this issue is to simply display the bank details as already set on this
screen, without needing to click that button. Literally just take the
"preview" box from the edit screen and display it on the 'receive money'
page.

**Comment by SudharakaP** [comment]
@alanna : Just before I deploy this want to make sure this is what we need; 

![bank-account-details](https://user-images.githubusercontent.com/12435965/157753574-b1ff9347-295b-4d02-8384-8ee0f5751e2f.gif)

**Comment by alanna** [comment]
As long as it includes the full details (bank account number etc, everything you'd see if you went to edit it) then yes this is great.
