### ISSUE TITLE
Hiring page: Video is not responsive

### ISSUE THREAD

**Issue by SimranArora123** [opencollective/opencollective#3194]
Describe the bug:
As we open the site in small screen the video below the text "Watch this 2 minute explainer video about what we do and why we are passionate about it." is not completely visible.

To Reproduce:
1. Go to 'https://opencollective.com/hiring'
2. Scroll down'

Expected behavior:
As we open the site on small screen the video section should be responsive i.e the size should become small , so as to insure that it is completely visible by the users in small screen. 

Screenshots:
![WhatsApp Image 2020-06-03 at 22 08 20](https://user-images.githubusercontent.com/52946773/83719437-b3123500-a654-11ea-812f-f2aed8a74d6c.jpeg)

**Comment by snitin315** [comment]
Taking this up :raised_hands:
