### ISSUE TITLE
Unable to edit expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3195]
I'm trying to edit this expense: https://opencollective.com/hots-nyc/expenses/18601

Every time I click 'edit' I get `Ooops, an unexpected error seems to have occurred  🤕`

I need to change the payment type from bank transfer to custom/manual, but I can't load the edit screen.

**Comment by alanna** [comment]
I think this might be due to connecting Transferwise payment type and changing the expense to that type, then disconnecting Transferwise and then trying to edit the expense. @kewitz this is probably an edge case but I have a feeling that's the reason.

**Comment by Betree** [comment]
@kewitz Sentry cached this issue if you need more logs: https://sentry.io/organizations/open-collective/issues/1708609363

It seems that we're getting a null value for `transferwise.availableCurrencies` somehow.

**Comment by kewitz** [comment]
@alanna that's exactly right, the frontend is assuming the host is connected to TransferWise since it has an expense created with it. It's an edge-case I'll fix ASAP.

@Betree yes, any property for `transferwise` will return null if the host is not connected to TransferWise.

**Comment by alanna** [comment]
Sorry @kewitz I need to reopen this. I was able to edit the expense to 'other' payment type and save it. But it's still showing the buttons for a Transferwise expense. I need to be able to click `mark as paid` because we are paying this one manually, but there's no button for that. So I don't think this is completely fixed.

![Screen Shot 2020-06-05 at 11 23 59 AM](https://user-images.githubusercontent.com/5498878/83819904-3c8e3980-a71f-11ea-9181-764353541acc.png)

**Comment by Betree** [comment]
@alanna the mark as paid button should be in the modal that appears after you click on the "Pay" button. What do you see in that modal?

**Comment by kewitz** [comment]
@alanna after updating the payout method in the expense and approving it again, you should be able to click in the _Pay_ button and see this screen:

![image](https://user-images.githubusercontent.com/2119706/83890482-351c5f80-a722-11ea-824f-e4fc0b9be255.png)

Can you confirm this is the case?

**Comment by alanna** [comment]
This is what I see

<img width="750" alt="Screen Shot 2020-06-06 at 10 27 25 AM" src="https://user-images.githubusercontent.com/5498878/83927210-5a6fa300-a7e0-11ea-9d6a-4d5a15f6260e.png">

**Comment by Betree** [comment]
@alanna if you hover the pay button, does it tells you why it's disabled?

**Comment by alanna** [comment]
@Betree it says "insufficient balance" which refers to Transferwise, but this is no longer a Transferwise payment.

**Comment by Betree** [comment]
@alanna I digged a bit and it looks like a rounding issue: the expense amount is `$2402` but the collective balance is `$2401.60`. I acknowledge that we're displaying a misleading rounded amount there:

![image](https://user-images.githubusercontent.com/1556356/84055866-b50e2800-a9b5-11ea-956f-ad6beae71346.png)

I'm opening a PR to fix this right now. let me know if you need me to update the expense amount as well.

**Comment by alanna** [comment]
@Betree the purpose of this expense is to zero the balance, so it needs to be for the full amount that's in there (this is why I'm always going on about that "100% of the balance" option for expenses!).

Can you please make sure it's for the right about, and manually mark it as paid? We've been waiting on this to be able to shut down the Collective.

 @kewitz if you can help with this sooner that would be great, because otherwise we'll need to wait another full day because of time zones between me and Ben.

**Comment by alanna** [comment]
Oh I realised I could edit the expense myself and now it's working to pay it! Great. I'll take it from here.

FYI, a design issue: I would never have clicked a button that says "Pay" if you hadn't been assuring me it was right, because I would be afraid to pay the money twice (once manually and once through the dashboard). I would think that would trigger an automatic payment, when what I was looking for is "mark as paid".

**Comment by Betree** [comment]
> I would never have clicked a button that says "Pay" if you hadn't been assuring me it was right, because I would be afraid to pay the money twice (once manually and once through the dashboard)

That's good feedback, I've transferred it to design. If you have an idea of a better label for this button feel free to suggest, I'll be happy to make the change.
