### ISSUE TITLE
Privacy policy: Text is not responsive

### ISSUE THREAD

**Issue by SimranArora123** [opencollective/opencollective#3196]
Describe the bug:
Text is not responsive in small screen(screen resolution of 720 x 1480 pixels)

To Reproduce:
1. Go to 'https://opencollective.com/privacypolicy'
2. Scroll down

Expected behavior:
When we open the site in small screen the text should be responsive such that it is clearly visible to the users.

Screenshots:
![WhatsApp Image 2020-06-04 at 14 40 45](https://user-images.githubusercontent.com/52946773/83739031-aef51000-a672-11ea-981d-c34ae1e655eb.jpeg)

**Comment by SimranArora123** [comment]
@Betree i want to work on this, but facing some problem in identifying the files .
Could you please help me?

**Comment by Betree** [comment]
@SimranArora123  The content of the page is stored as markdown in [components/static-pages/privacypolicy.md](https://github.com/opencollective/opencollective-frontend/blob/8930cc562d738170d5cba0d0698a4265e347ca9f/components/static-pages/privacypolicy.md). 

This file is rendered by [pages/staticPage.js](https://github.com/opencollective/opencollective-frontend/blob/00688a2801eedf22d8d45c88199f5a3cf56ec72e/pages/staticPage.js), where the styles are defined.
