### ISSUE TITLE
graphql-cli breaking change from 3.0.14 to 4.0.0

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3198]
The `graphql-cli` package was just upgraded from 3.0.14 to 4.0.0.

Since we pull it via `npx` we were automatically upgraded to the latest version, which no longer works with our particular command and config file.

In the short term we've pinned the npx like this:

`npx graphql-cli@3.0.14 get-schema -p opencollective_v2 -e dev && prettier lib/graphql/schemaV2.graphql --write`

Here is the [info on 4.0.0](https://github.com/Urigo/graphql-cli/releases/tag/v4.0.0), which mentions deprecating the `get-schema` command in favour of something called `introspect`

@znarf mentioned that he thought they were deprecating the ability to create a schema entirely but from what I understand, we can still do that, we just need to update our `.graphqlconfig` file to YAML or something.

**Comment by znarf** [comment]
From what I understand, JSON should be fine but the file needs to be renamed.

https://github.com/Urigo/graphql-cli/blob/master/docs/MIGRATION.md
https://graphql-config.com/usage

Not sure yet the difference between `get-schema` and `introspect`.

**Comment by znarf** [comment]
Fixed in https://github.com/opencollective/opencollective-frontend/pull/4787
