### ISSUE TITLE
Unable to remove attachment from expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3201]
Regarding this expense: https://opencollective.com/hots-nyc/expenses/18601

It was originally raised as a receipt type, with an attachment. Then it was edited to become an invoice type. Now on the edit screen, there are no attachments displayed. But the old receipt attachment is still there when the expense summary is displayed. There appears to be no way to remove it.

@kewitz I think this is another edge case for you.

**Comment by Betree** [comment]
I'll look at this one

**Comment by znarf** [comment]
Seems this was fixed, cc @Betree
