### ISSUE TITLE
How it works: Spacing issue between the buttons

### ISSUE THREAD

**Issue by SimranArora123** [opencollective/opencollective#3202]
Describe the bug:
When we open the site in small screen ,the spacing between the two buttons(i.e Discover Collectives and Lear More). is less.

To Reproduce:
1. Go to 'https://opencollective.com/how-it-works'
2. Scroll down 
3. See error

Expected behavior:
There should be some spacing between the buttons.(some padding should be added to make it look nicer).

Screenshots:
![Screenshot (181)](https://user-images.githubusercontent.com/52946773/83844340-6d24a200-a724-11ea-912d-c7b6c1d63e26.png)

**Comment by InkFaust** [comment]
Hello @znarf ,

Please, check on the connected pull request I've opened for this issue.
This is my first attempt to contribute, and I'd like to continue my contribution further.
