### ISSUE TITLE
Might not be receiving emails

### ISSUE THREAD

**Issue by staltz** [opencollective/opencollective#3206]
Same as #2961. I think I didn't receive emails this month for the collectives I'm admin in, specially [Manyverse](https://opencollective.com/manyverse).

**Comment by znarf** [comment]
Following up once again with Mailgun. Will keep you updated.

**Comment by znarf** [comment]
I was able to see that you (or some other tool on your behalf) reported that message as spam and it's blocking all future attempts. It's indeed looking like spam.

<img width="662" alt="Screenshot 2020-06-05 at 11 55 49" src="https://user-images.githubusercontent.com/806/83863475-ab6d9180-a723-11ea-81e1-91695b0c56e7.png">

@Betree do you have any input on this? Seems related to https://github.com/opencollective/opencollective/issues/2840

**Comment by staltz** [comment]
@znarf If I have a malware somewhere, let me know more details, I can ask my email provider to investigate this (it's a paid service, not free like Gmail).

**Comment by Betree** [comment]
Our email forwarding service is still live so that may be the reason, do we know if this was sent through a hello@manyverse.opencollective.com email?

**Comment by znarf** [comment]
@staltz it's not a malware, it's a spam reaching your inbox and flagged from there. Would be interesting to know what's your email provider.

@Betree It certainly was, I don't see what else that could be. What can we do?

**Comment by Betree** [comment]
@znarf I'm going to iterate on the plan to deprecate it. In the meantime, we can also set the `settings.features.forwardEmails` flag to `false` for manyverse to avoid similar cases.

**Comment by staltz** [comment]
> Would be interesting to know what's your email provider.

fastmail.com

**Comment by Betree** [comment]
There's a [work in progress](https://github.com/opencollective/opencollective-api/pull/4000) to make email forwarding opt-in for all collectives. I've actively disabled it for `manyverse` last Friday to make sure that you will not be impacted again.

**Comment by znarf** [comment]
Ok, just removed the address from the complaints list on Mailgun. Mailgun said that the whitelist option was not protecting the email from being on the complaints list.
