### ISSUE TITLE
Migrate collective's long descriptions to HTML

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3207]
A long time ago, `Collectives` used to rely on markdown for their long descriptions. We've changed our practices in the new collective page to rely on an editor that generated `HTML` directly. The transition was done by creating a `ReverseCompatibleHTMLEditor` component that automatically converted your markdown to `HTML` when trying to edit it.

We still have a lot of collectives in the DB using the old markdown format. We would like to migrate them, and remove the transitional code.

### API

- [ ] Create a migration that takes all collectives with a markdown description (`LENGTH(longDescription) > 0 AND longDescription NOT LIKE '<%'`) and convert them to HTML using `Showdown.Converter().makeHtml`

### Frontend

- [ ] Remove `ReverseCompatibleHTMLEditor` and related code, rely on `RichTextEditor` directly

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by snitin315** [comment]
@Betree Can I take this up?

**Comment by Betree** [comment]
@snitin315 sure! It's a bounty, so we're adding a two weeks time limit (extensible if there's demonstrable progress). Good luck :slightly_smiling_face:

**Comment by Betree** [comment]
:trophy: This issue has been completed by @snitin315  

To claim the **$200** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Comment by snitin315** [comment]
@Betree invoice submitted :+1:
