### ISSUE TITLE
All Cards are not visible in small screen

### ISSUE THREAD

**Issue by SimranArora123** [opencollective/opencollective#3208]
Describe the bug:
when we open the site in small screen the first two cards below the text "Apply to a fiscal host" are not visible.

To Reproduce
1. Go to 'https://opencollective.com/pricing?tab=singleCollectiveWithoutAccount'
2. Scroll down to '....'
3. See error

Expected behavior:
As we open the site on small screen the first two cards i.e "Open source Collective" and "Women who code" are not completely visible.

Screenshots:
![Screenshot (182)](https://user-images.githubusercontent.com/52946773/83862433-90a91600-a73f-11ea-987b-c4840c3738f5.png)

**Comment by twisstosin** [comment]
taking this one up

**Comment by twisstosin** [comment]
@Betree I have a pr for this.
