### ISSUE TITLE
Design system update: Early June 2020

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3209]
##  **[Transactions component](https://www.figma.com/file/9Iq3vBOmZ2EuOacXEYD5yK/DS-05-Projects-UI-Kit?node-id=1859%3A23898)**: 
  
- All variations for financial contributions
<img width="1970" alt="Screen Shot on 2020-06-05 at 07-32-40" src="https://user-images.githubusercontent.com/49539954/83876796-017c0e00-a6ff-11ea-8f17-2d022e12c1d1.png">

  - All variations for expenses
<img width="1907" alt="Screen Shot on 2020-06-05 at 07-32-54" src="https://user-images.githubusercontent.com/49539954/83876789-fe811d80-a6fe-11ea-91f7-2773d72918fb.png">

🟢 These updates are ready to be implemented platform-wide.
@opencollective/core-developers @Betree

**Comment by Memo-Es** [comment]
We just updated the components to include the new behavior for accessibility to the buttons and the small fix related to the expense type tag @Betree

**Comment by Betree** [comment]
Thank you @Memo-Es, that's perfect!
