### ISSUE TITLE
Organization avatars not updating site-wide after being changed.

### ISSUE THREAD

**Issue by LogoiLab** [opencollective/opencollective#3210]
**Describe the bug**
Organization avatars on contributions pages and badges not updating.

**To Reproduce**
1. Contribute to a project as an organization.
2. Update organization profile with new avatar.
3. Go to contributions page of previously contributed to project.
4. See that avatar is still the old avatar.

**Expected behavior**
The avatar should be updated site-wide to the new avatar.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 78

**Comment by znarf** [comment]
We're normally adding a hash in the images URL to make sure that it's updated side wide.

Ie: https://images.opencollective.com/znarf/e534a60/avatar/256.png

I just checked and it's true that we don't use this versioned URLs for displaying contributors (ie: on https://opencollective.com/excalidraw), that should be looked at.
