### ISSUE TITLE
Fix how Updates & Conversations sections appear when there's no content

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3211]
*All these screenshots are the logged out view, so this is not a case of it displaying the onboarding encouragement to new admins to start using these sections.*

1. The 'create conversation' button shows up twice and it's redundant.

<img width="1262" alt="Screen Shot 2020-06-06 at 8 40 29 PM" src="https://user-images.githubusercontent.com/5498878/83960143-6be8a600-a8d9-11ea-83bc-089b49d258a4.png">

2. This weird "north pole" message appears and takes up huge amounts of space on the page. This shouldn't exist: if there are updates, display them. If not, do not display this section at all.

<img width="1000" alt="Screen Shot 2020-06-06 at 8 38 28 PM" src="https://user-images.githubusercontent.com/5498878/83960154-8cb0fb80-a8d9-11ea-876e-fd45f8e9e438.png">

3. Even if you turn off updates completely in settings, the above issue still occurs. If updates are switched off, there should be nothing about updates displayed.

**Comment by Betree** [comment]
We have some design (almost) ready for the empty states of these sections: https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP?node-id=1506%3A1116&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#28945760

I'll create an issue for that as soon as the illustrations get added to the final design.

> This weird "north pole" message appears and takes up huge amounts of space on the page. This shouldn't exist: if there are updates, display them. If not, do not display this section at all.

To be confirmed with design, but I think the goal of this message was to avoid displaying an empty page if the org doesn't have any contribution yet. It's true that it doesn't make much sense when the other sections are filled up.

**Comment by Betree** [comment]
Issue about updating empty states to the latest design: https://github.com/opencollective/opencollective/issues/3220

@alanna The message about north pole is not from the updates sections, but from the contributions sections. I think we should have a specific issue for this one if we want to change it.

**Comment by alanna** [comment]
OK thanks for clarifying @Betree - I will raise another issue for that.

**Comment by alanna** [comment]
closing in favor of #3220
