### ISSUE TITLE
Change default section order for fiscal host pages

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3212]
## User story 
As a fiscal host, I want to explain my activities to visitors to my page without confusing them, so I can provide hosting services to Collectives and support them. 

The functions of a host are very different to a Collective, but right now we force them to use the same layout. This really emphasises soliciting donations, which isn't the focus of most fiscal hosts, and de-emphasises the reasons people are on this page (to find out what the host does, apply to join, and see its hosted Collectives).

This has become even more relevant with the upcoming change to put budgets, updates, and other functions into host pages, making them more busy and crowded.

## Best solution for this problem
The best solution would be allowing admins of all kinds of profiles to reorder the sections as they want.

## MVP
Change the default order of host page buttons and sections to:

0a. [If non-admin] Contact, Apply, and Submit Expense buttons up top (already the case, but may need a rethink because that's a lot of buttons. Maybe 'Submit Expense' should go with Budget further down, so we don't confuse people trying to submit expenses to Collectives in that host).

0b. [If admin] Manage Contributions, Dashboard, Submit expense buttons.
1. About
2. Hosted Collectives (OK to show the whole "contributions" section, which also includes Collectives the org has contributed to, but the default filter should be hosted Collectives).
3. Updates (if any - otherwise hide section)
4. Events (if any - otherwise hide section)
5. Conversations (if any - otherwise hide section)
6. Budget (and maybe Submit Expense button)
7. Become a Contributor + Top Contributors
8. Core Contributors

**Comment by piamancini** [comment]
@betree is shipping a feature that allows for users to reorganize sections from the settings. That should solve it if it's also shipped for orgs

**Comment by Betree** [comment]
The feature that will be shipped with https://github.com/opencollective/opencollective-frontend/pull/4322 is only for collectives, but we should be able to iterate on it easily if it helps with this issue.

![Peek 03-06-2020 17-15](https://user-images.githubusercontent.com/1556356/83654829-eeadf000-a5bd-11ea-8613-d1ce3ff95ab1.gif)

**Comment by alanna** [comment]
Yes that would be perfect for hosts, too! Great.

**Comment by znarf** [comment]
Will be solved by https://github.com/opencollective/opencollective/issues/3257
