### ISSUE TITLE
Show expense submitter name in email notification

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3215]
Now that we have the ability to set the payee to an organization, you sometimes can't tell who the expense submitter was by the email notification. It should list "submitter" and their name below "payee".

<img width="858" alt="Screen Shot 2020-06-08 at 9 29 36 PM" src="https://user-images.githubusercontent.com/5498878/84014969-44740500-a9cf-11ea-88f5-e01d136f7054.png">

**Comment by snitin315** [comment]
Duplicate of #3142

**Comment by alanna** [comment]
Oh yeah I forgot I already raised an issue for this
