### ISSUE TITLE
Add transaction details on expense page

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3224]
Initially suggested by @kewitz 

We should display transactions information on the new expense page (once it's paid).

The best place to do that would be the activity, so maybe we should attach the public transaction information directly to the activity.

I suggest displaying something similar to what we have on the collective page:
> Transaction details
> $55.00 - $0.97 (-1.76% payment processor fee)

It should display:
- Total amount
- Host fees (if any)
- Payment processor fees  (if any)

---

![image](https://user-images.githubusercontent.com/1556356/84140427-e50b0900-aa51-11ea-9dd1-2f421ad3618a.png)

**Comment by alanna** [comment]
Good idea!

(By the way, the 'expense paid' action should also include the person who paid it - that's missing from your screenshot).

**Comment by Betree** [comment]
> (By the way, the 'expense paid' action should also include the person who paid it - that's missing from your screenshot).

@kewitz To achieve that :arrow_up: we would need to store the person who triggered the payment (aka. the one who marked it as processing) in the `COLLECTIVE_EXPENSE_PAID` activity. Do you see any issue if we decide to do that?

**Comment by kewitz** [comment]
@Betree Is it OK to use the `lastUpdatedBy` id?

**Comment by Betree** [comment]
@kewitz given that the expense cannot be edited while it's processing, it seems like a safe thing to do

**Comment by alanna** [comment]
+1 to this... it's not critical but it would be good for transparency

**Comment by kewitz** [comment]
Already implemented:
<img width="795" alt="Screen Shot 2021-01-19 at 18 07 04" src="https://user-images.githubusercontent.com/2119706/105093239-2b612580-5a81-11eb-95a1-99fe9e059fa6.png">

**Comment by Betree** [comment]
@kewitz I don't think it was, from the screenshot you shared where is the fees breakdown?

**Comment by kewitz** [comment]
I'm so sorry @Betree, I saw the image and assumed it was missing the author. :man_facepalming:

**Comment by Betree** [comment]
> I'm so sorry @Betree, I saw the image and assumed it was missing the author. man_facepalming

I see ^^ I didn't even notice that it was missing an avatar in my screenshot :smile:

**Comment by Betree** [comment]
I still think we need this, it would have helped today for the use case presented in https://github.com/opencollective/opencollective/issues/4691.

To propose some specs:
- [ ] On `server/graphql/v2/object/Activity.ts`, expose a new `transaction` field (based on `activity.TransactionId`)
- [ ] In expense's `ThreadActivity`, whenever a `COLLECTIVE_EXPENSE_PAID` activity is detected, show the details from `activity.transaction`
- [ ] Details should look more or less like this (do not show a fee if it's $0):
> Total paid: $50
> Payment processor fees: $0.42
> Host fee: $0.13

**Comment by Betree** [comment]
As a pre-requisite for this, we need to associate the `TransactionId` to `collective.expense.paid` activities. It's currently missing.

**Comment by Betree** [comment]
I would love to see this issue prioritized, it seems like a very important piece of information that is not properly surfaced. The current flow of going to the transactions list while you're already on the expense page feels like it's hidden.
