### ISSUE TITLE
Pricing: Contact button is not responsive 

### ISSUE THREAD

**Issue by SimranArora123** [opencollective/opencollective#3225]
Describe the bug:
When we open the site in small screen, and open the require page the button is not responsive (Contact Us).

To Reproduce:
1. Go to 'https://opencollective.com/pricing?tab=organization'
2. Scroll Down
3. Go to the last column of pricing table.

Expected behavior:
As the size of screen becomes small the text inside the button (i.e Contact Us) should be responsive, so as to insure that it completely fits the button.

Screenshots:
![pic](https://user-images.githubusercontent.com/52946773/84180526-460ffc80-aaa5-11ea-8b2f-4992af3f785b.jpeg)

**Comment by Betree** [comment]
Good catch, thanks for reporting this @SimranArora123. We're probably using a fixed width while we should be using a minWidth

**Comment by AARYAN-MAHENDRA** [comment]
I would like to work on this issue.Is it alright?

**Comment by Betree** [comment]
@AARYAN-MAHENDRA sure, than you for joining :+1:

**Comment by AARYAN-MAHENDRA** [comment]
Thanks.

**Comment by AARYAN-MAHENDRA** [comment]
Actually I am pretty much new to github so i would like to know why all the checks of my PR haven't passed. Is something wrong with the code or something else.I will be grateful if anyone will please enlighten me on this topic.

**Comment by SudharakaP** [comment]
@AARYAN-MAHENDRA : As far as I am aware, the e2e tests only run on branches belonging to the parent repo, not on forks. Your pull request commits are on your fork and thats the reason I think those tests are pending. So don't worry, there's nothing wrong with the code. Once you've been given access to create branches on this repo, you'll be able to get around this problem. 🙃

**Comment by Betree** [comment]
@SudharakaP is correct. For your first PR, the team will push your branch on the main repo once it's ready to run the E2E tests.

**Comment by AARYAN-MAHENDRA** [comment]
Thank You.
So my PR can now be merged successfully.Right?

**Comment by AARYAN-MAHENDRA** [comment]
Thanks.

**Comment by AARYAN-MAHENDRA** [comment]
@Betree I have linked the pull request.

**Comment by Betree** [comment]
Resolved by https://github.com/opencollective/opencollective-frontend/pull/4586
