### ISSUE TITLE
Approved Collective still showing "Collective pending approval" banner

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3228]
I approved [this Collective](https://opencollective.com/hots-nyc) to join OCF host. It's showing up in the OCF host dashboard. But when you go to the Collective page, you still see the pending banner.

![Screen Shot 2020-06-11 at 3 29 14 PM](https://user-images.githubusercontent.com/5498878/84341883-52f13500-abf8-11ea-9777-3ad60aa4e7c5.png)

**Comment by Betree** [comment]
I don't see the banner, I assume you faced a caching issue.

We could solve that by calling `purgeCacheForPage` when approving or rejecting collectives.

**Comment by alanna** [comment]
It seems to have cleared now, so I guess it was caching. I don't know how
it works but if it could update more quickly it would be a better
experience.
