### ISSUE TITLE
Invert order of pending Collectives

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3229]
I just had a situation where I was trying to approve a new Collective in the 'pending' tab in the host dashboard, but I couldn't find it. Then I realised it was hiding all the way at the bottom. We should invert the order so newest applications are at the top.

**Comment by Betree** [comment]
I just tested and collectives are currently sorted by creation date from newest to oldest. 

We currently can't sort by application date because we don't store that information.

**Comment by alanna** [comment]
Ah. This was an older Collective moving to a new host, so that explains why
it was at the bottom.

I'm a bit concerned that we don't store the date a Collective joined a
host, which may be different from its creation date. We need that because
legally that's the date they officially enter the terms of fiscal
sponsorship agreement. Our legal language is set up to refer to that date
(called the Effective Date) and we will need to be able to know it if
there's ever a legal issue.

So do we just not store the application date, or do we also not store the
approval date? We don't need to display it, just to let hosts access it if
they need it somehow.

**Comment by znarf** [comment]
We store the approval date.
