### ISSUE TITLE
Problem connecting PayPal after Stripe

### ISSUE THREAD

**Issue by aaronpk** [opencollective/opencollective#323]
From the settings page, (https://opencollective.com/___/settings) I first connected my Stripe account. This worked fine, and I was redirected back to the settings page after connecting.

I then clicked the Paypal button, and was taken to Paypal and approved that. When I was redirected back to opencollective.com, the settings screen did not acknowledge that I had connected my Paypal. I checked the URL, and noticed that it was like the following:

```
https://opencollective.com/***/settings?stripeStatus=success/?paypalApprovalStatus=success&preapprovalKey=PA-***
```

Notice that the `stripeStatus=success` was left in there from the Stripe redirect. It appears the callback URL did not strip out the Stripe parameters, so the site didn't get the Paypal `preapprovalKey` due to the double `?`

**Comment by piamancini** [comment]
Thanks @aaronpk. 
looping in @asood123.
