### ISSUE TITLE
Error visiting Collective Page after disabling items on Collective Page.

### ISSUE THREAD

**Issue by digitalextremist** [opencollective/opencollective#3232]
After disabling sections of `Collective Page`, going to the Collective Page itself shows this error:

![image](https://user-images.githubusercontent.com/21095/84389623-2e22a080-abab-11ea-84a7-61143d739049.png)

**To Reproduce**

0. Uncheck items on `Collective Page` in _Settings_
0. Click `Save`
0. Click `Visit Collective Page` next to `Save`.
0. See error above, and must reload to see page.

**Expected behavior**
After disabling sections on the `Collective Page`, visiting the Collective Page ought to be immediate without error, and with/without the sections selected in _Settings_.

**Desktop (please complete the following information):**
 - Mint Linux
 - Google Chrome 
 - 83.0.4103.97

**Comment by Betree** [comment]
@digitalextremist sorry about this issue, I'm looking at that now

**Comment by Betree** [comment]
@digitalextremist could you share your collective address?

**Comment by digitalextremist** [comment]
@Betree it occurred on `/upforce`, `/takeover`, `/abstractive`, and `/proactive`

**Comment by Betree** [comment]
The fix is on its way
