### ISSUE TITLE
Include events in search results

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3233]
## User story 
As an event attendee or organizer, I want to be able to find my event page using the Open Collective search. Currently only Collectives and Organizations appear.

## Best solution for this problem
Fully featured search for everything on the platform, with filters to find exactly what you're looking for, including events.

## MVP
Just include events to show up in the current search design.

**Comment by znarf** [comment]
That could be done when moving Search out of Algolia.

**Comment by Betree** [comment]
Done in https://github.com/opencollective/opencollective-api/pull/4883.
