### ISSUE TITLE
Kill Zapier app

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3236]
# Acknowledging
- That maintaining code for a feature always takes time (eg. tests need to be updated, bugs...)
- That unmaintained features can contain security issues, or be a vector for privilege escalation
- That the bigger/more complex the code base, the harder it is for newcomers to get on board

# Data

- Time since feature has been deployed: 1 year
- Number of integrations: 12

# Reasons to kill

- Very few users
- Not a good test coverage
- There are alternatives: we're still supporting "regular" webhooks, so with a custom service (or a pro Zappier account) you can still have the same feature
- It's hard to extend/update/maintain, because the implementation was not properly specified from the start: we are using a custom integration where adding a new endpoint requires a lot of work, while we should have worked with standard REST Webhooks from the start
- The APP is still in "Beta", it's not listed publicly on Zapier and it requires a fair amount of work if we want to tackle that (and also, more users)
- Zapier is a proprietary solution. We should focus on standards (RSS, webhooks).

# Reasons not to kill

- Some users may be attached to it

# Migration strategy

- [x] Remove ad on the webhooks page
- [x] Send notice to users that we'll deprecate Zapier app in the next few months
- [ ] Remove the webhooks
- [ ] Remove the app from Zapier
- [x] Archive the app repo

If we decide to go with this change, we need to properly inform the users and to give them a delay to transition out before we remove the feature.

**Comment by Betree** [comment]
The following query returns 19 entries:

```sql
SELECT c.slug, n.*
FROM "Notifications" n  
INNER JOIN "Collectives" c ON n."CollectiveId" = c.id
WHERE "webhookUrl" LIKE 'https://hooks.zapier.com/hooks/%'
```

Since using Webhooks requires a pro zapier account, removing the app now would break the feature for these integrations. Having RSS feeds for expenses, members, etc. (https://github.com/opencollective/opencollective/issues/3504) could provide a better way to migrate these.

**Comment by patcon** [comment]
Old docs, in case anyone is curious before it goes away (or wants to adopt it 🤷 ): https://docs.opencollective.com/help/v/master/collectives/integrations

**Comment by Betree** [comment]
> @betree if this is killed let's tell @shannondwray for updating docs. 

I've updated all the docs already. I'm still waiting to move to the next steps as some people may still depend on the Zapper integration.

**Comment by Betree** [comment]
@BenJam That'd be really helpful!

**Comment by BenJam** [comment]
Okay I'm contacting each collective with the following:

> Hi
>
> I'm writing to let you know that as of Friday 11th June we will no longer trigger events in the Zapier platform. 
>
> We launched our Zapier support in June 2019 and since then we have seen a small number of collectives configure the integration, including your own. 
>
> As a small team it's essential that we prioritise our time and resources to deliver the most value we can as a platform for our Hosts and their Collectives. Supporting features that aren't used is not an efective use of our time and as such we will deprecate features when we feel that the cost of maintianing them outweighs the benefit of doing so. 
>
> If you are actively using Zapier to automate parts of your process then we recommend you get in touch with us at support@opencollective.com and we will help you work through and changes you may need to make.
>
> Thank you 
>
> Ben
> Head of Product, Open Collective. 

I'll send them to each of the collectives with a webhook configured now.

**Comment by Betree** [comment]
I've removed all hooks from our systems, will proceed with removing the app in the next few days

**Comment by BenJam** [comment]
just logged in and it looks like all the zaps on the ops account are off. If there's another account I'm sure @Betree will pick this up when he returns form his holiday.

**Comment by Betree** [comment]
Yes, it's all done. We needed to wait a bit because Zapier forces you to deprecate your app ~2 weeks before it can be deleted entirely. I just removed the app, so Zapier is now gone for good.

**Comment by Ashleyburgos** [comment]
Approved
