### ISSUE TITLE
placeholder not replaced in bank transfer email

### ISSUE THREAD

**Issue by lsmith77** [opencollective/opencollective#3237]
**Describe the bug**
I created a bank transfer on the symfony-diversity collective and received an email which didn’t list the collective name but instead a `{{collective}}` plceholder
**To Reproduce**
1. Go to https://opencollective.com/symfony-diversity
2. Create a one time donation using bank transfer
3. Open email

**Expected behavior**
Name of collective in the bank transfer instructions. 

**Screenshots**

![04128A01-C4BB-498E-B9BF-0256B5620EB1](https://user-images.githubusercontent.com/300279/84575599-7f4eb200-adae-11ea-8373-18209cc702ad.jpeg)
**Smartphone (please complete the following information):**
 - Device: iPhone8
 - OS: iOS13.5.1
 - Browser safari
 - Version 

**Additional context**

**Comment by Betree** [comment]
Hi @lsmith77, the template for the instructions of your host (OC Europe) was using two brackets for the variable (`{{collective}}`) instead of one, which is why it wasn't replaced. I've edited the template manually and the collective name should now be properly replaced in the instructions.
