### ISSUE TITLE
Improve the process of applying to a fiscal host

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3238]
## User story 
I just got this feedback from a user:
> We were having a look at open collective and just sort clicking around and I accidentally clicked on 'apply' for fiscal sponsorship. I thought the next screen would be a list of things we would have to put into our application, but it just went straight to 'application sent'.

As an admin of a Collective applying o a fiscal host, I want the process to be clear, and to have the chance to communicate what my Collective is about to the host.

As a host admin, I want to help potential Collectives understand my host's acceptance criteria, and get sufficient info from them to evaluate their application.

## Solution for this problem
A customizable application form that host admins can set up, which is the screen you go to after clicking "apply". You put in some info and then click 'submit' when you're ready.

The MVP would be a single text box with customizable text above it explaining what the host needs you to answer. More complex would be the option to add multiple text boxes or other functions like tick boxes.

The data entered on this form would be included in the 'new pending Collective' email that host admins get, and would be viewable via the 'pending Collectives' tab on the host dashboard.

**Comment by alanna** [comment]
@piamancini would this be in scope for the host dashboard project, or should it be considered separately?

**Comment by Betree** [comment]
Related: https://github.com/opencollective/opencollective/issues/2282
