### ISSUE TITLE
Confusing button text for already-reimbursed expenses

### ISSUE THREAD

**Issue by aaronpk** [opencollective/opencollective#324]
I submitted an expense and marked it "already reimbursed." I then approved the expense. Now I am looking at this in the list of expenses:

![screenshot 2017-03-13 11 37 54](https://cloud.githubusercontent.com/assets/113001/23870113/9788aa08-07e2-11e7-9722-5783a75ffc98.png)

1) there is no indication that the expense was marked as "already reimbursed"

2) The button says "Pay", which is misleading. As it's already been reimbursed, the action that will happen if I click that is the funds will be deducted from my available balance. I wanted to be sure that clicking the button will not actually send a PayPal payment.

Perhaps a more appropriate text for the button would be "Mark as Paid".

**Comment by piamancini** [comment]
this is good feedback. We'll add it to #478
