### ISSUE TITLE
Can't post an update when copy pasting from a google doc

### ISSUE THREAD

**Issue by leena4c** [opencollective/opencollective#3240]
When copy pasting from a google doc, I have this error

![Screen Shot 2020-06-15 at 12 44 27 PM](https://user-images.githubusercontent.com/64890919/84648963-07939b00-af06-11ea-9ca9-1b084b78bc60.png)

**Comment by leena4c** [comment]
I just tried using just the formatting tools and it fails again so it doesn't seem linked to google docs (I copied paste first without formatting, clicked on preview and it worked, then went back, applied formatting with the toolbar and now it fails again)

Here is the text:
https://docs.google.com/document/d/1j36cYsYdQTPM5RgcLxJDH-_D6U4Wk0NAD7ZqUbkPHvE/edit#

**Comment by znarf** [comment]
Sorry, I found the issue, you can try again now.

**Comment by leena4c** [comment]
Thanks, I can publish now. The lay-out doesn't get fully published though, the colors I added (e.g. in the subtitles) to improve reading experience, are not published.

**Comment by znarf** [comment]
Ok, I'm not sure what we're supporting in term of formatting.

**Comment by znarf** [comment]
Closing because the original error was addressed.
