### ISSUE TITLE
Long Host/Collective title overlapping background

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3242]
![Screen Shot 2020-06-16 at 10 05 28 AM](https://user-images.githubusercontent.com/5498878/84710764-f6f02d00-afb8-11ea-81e7-89cc6b043490.png)

It should either wrap or we should character limit the names.

Note, it looks like this org is using its legal name, as they are probably required to do, but it's super long. This is why I suggested separating 'legal entity name' and host name on #2665

**Comment by alanna** [comment]
Here's another example

![Screen Shot 2020-06-16 at 11 33 22 AM](https://user-images.githubusercontent.com/5498878/84715674-450b2d80-afc5-11ea-82bc-1fad0598b138.png)

**Comment by alanna** [comment]
Another example https://opencollective.com/hrmi

<img width="915" alt="Screen Shot 2020-09-03 at 2 44 23 PM" src="https://user-images.githubusercontent.com/5498878/92065583-18acc380-edf4-11ea-9689-5f682fb87329.png">

@Betree is there any quick fix for this? This Collective is going to start a big fundraising campaign soon, and it doesn't look good.

The same problem is also affecting their host https://opencollective.com/motu

**Comment by Betree** [comment]
Either we wrap the text (it will go on a new line) or we truncate it and display the full name on hover. I personally prefer the first option.

**Comment by alanna** [comment]
Wrapping is fine. Even if it doesn't look perfect it will be a lot better
than it looks now.

**Comment by Betree** [comment]
Let's experiment with `max-width: 45%` on the title:

![Screenshot_2020-09-03 gomymobiBSB Free Online Site Shop Builder - Open Collective](https://user-images.githubusercontent.com/1556356/92096094-ca3cfc00-edd6-11ea-9d39-675a20e8bf28.png)

![Screenshot_2020-09-03 Motu Economic and Public Policy Research Trust - Open Collective](https://user-images.githubusercontent.com/1556356/92096100-cad59280-edd6-11ea-921e-db53e5f73216.png)

![Screenshot_2020-09-03 Human Rights Measurement Initiative Asia expansion - Open Collective](https://user-images.githubusercontent.com/1556356/92096104-cc06bf80-edd6-11ea-91f0-c1283d56f083.png)

**Comment by alanna** [comment]
Looks good to me!

**Comment by alanna** [comment]
<img width="1244" alt="Screen Shot 2020-09-08 at 10 46 58 AM" src="https://user-images.githubusercontent.com/5498878/92430124-06fa6000-f1e8-11ea-9db9-5155a564e337.png">

Looks like the wrapping isn't respecting word breaks. It should keep the whole word together if there isn't a space.

**Comment by Betree** [comment]
I guess it varies across browsers/OS, below is what I get. Pushing a potential fix that should unify that.

![Peek 2020-09-08 08-11](https://user-images.githubusercontent.com/1556356/92439335-ee1f8980-f1aa-11ea-9cef-3c6f53cc3185.gif)
