### ISSUE TITLE
Clarification of Connected Collectives

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3243]
Right now we are using too many confusing terms in reference to connected Collectives, aka member Collectives, and we're not communicating how they work to users.

This is how they appear:
![Screen Shot 2020-06-16 at 10 15 59 AM](https://user-images.githubusercontent.com/5498878/84711470-8f3ae180-afba-11ea-8a5d-9eaa46e8a067.png)

1. Are they called "Connected Collectives" or "Member Collectives"? I prefer "Connected Collectives" because it's more generic and people will be using this in different ways where 'member' might not fit.
2. Is the relationship hierarchical or reciprocal? i.e. are the two Collectives in the image above 'child' Collectives of the main one, or are they all connected as peers? I thought we were going to make them peers but we're displaying them in a hierarchy. If they are peers, they should show up on each other's pages, not only the child ones showing on the parent.
3. The "View Collective" button should have a capital 'C' on Collective.
4. This whole feature needs to be added to the docs.
5. I don't think "other ways to contribute" is a good section title. It should be called "Connected Collectives" or whatever term we decide to consistently use.

**Comment by Betree** [comment]
The decision was to rename everything to `Connected collectives` (see https://github.com/opencollective/opencollective/issues/3040). There should not be any occurrence of "Member Collective" anymore, I'm going to open a PR to fix that.

> Is the relationship hierarchical or reciprocal?

It's hierarchical indeed. They however do show up on both pages, see https://github.com/opencollective/opencollective/issues/2485

> This whole feature needs to be added to the docs.

It's already in the docs: https://docs.opencollective.com/help/collectives/connectedcollectives

> I don't think "other ways to contribute" is a good section title. It should be called "Connected Collectives" or whatever term we decide to consistently use.

This section also displays events, which is why it's called "other ways to contribute"

**Comment by alanna** [comment]
Thanks @Betree for some reason it wasn't coming up when I searched docs!

**Comment by Betree** [comment]
@alanna I've removed all occurrences left for `Member Collective`, feel free to close if you think everything has been addressed will be addressed in another issue.

**Comment by alanna** [comment]
Thanks @Betree 

My personal opinion is that sections should be modular and not combined, i.e. both Connected Collectives and Events should be their own section so admins can turn them on and off and reorder them as they see fit - we had another recent issue where a user wanted Events to show in the top nav bar, for example. 

But I think that's a seperate issue so I'll close this.
