### ISSUE TITLE
Fiscal host admin unable to add Collective to their own host

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3244]
Fiscal host admins often need to add new Collectives to their own host. But it seems like the "apply" button is not displayed to them on the host page where they are the admin, even if it is visible to other people. 

I suspect this is because we can't fit so many buttons there (I'll raise another issue about that), but we need to make an easy to understand way for fiscal hosts to add Collectives to their host, because we're getting support requests because new hosts can't figure it out.

![Screen Shot 2020-06-16 at 10 26 25 AM](https://user-images.githubusercontent.com/5498878/84712079-d9709280-afbb-11ea-9a8b-953c4bcad80e.png)

**Comment by znarf** [comment]
We don't have enough space and I had to remove this from the navigation in this particular situation.

If they want to apply to their own fiscal host, they can follow the "Accept Financial Contributions" flow or just edit the "Host" in the Collective settings.

**Comment by alanna** [comment]
@alinamanko - FYI see above if a host admin can't figure out how to add a Collective the admin to their host.

@contraexemplo can you please add this info to the docs for host admins?

**Comment by alanna** [comment]
I'm still not able to add Collectives to my own host. When I go via the Collective's host settings, I get this error:
![Screen Shot 2020-08-20 at 11 23 14 AM](https://user-images.githubusercontent.com/5498878/90699552-b58d3e00-e2d7-11ea-97d8-a4d66d84d296.png)

Should this be a seperate issue @znarf ?

**Comment by znarf** [comment]
@znarf Yes, it's a different issue, would be great to have the context and know which Collective it's about.
