### ISSUE TITLE
Need design pattern for when we have too many action buttons

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3245]
I have noticed this coming up in various places. We try to display all actions as buttons but it gets too crowded, e.g. on a fiscal host page like this:

![Screen Shot 2020-06-16 at 10 26 25 AM](https://user-images.githubusercontent.com/5498878/84712196-176db680-afbc-11ea-9418-7f20b7231acc.png)

This also came up with expenses and will be coming up on the host dashboard too.

We need input from the designers. I suggest something like: 1 main action button for the most common one, with an "actions" dropdown next to it to access anything else.

**Comment by Memo-Es** [comment]
This is being implemented in the new Collective page update.
It has a dedicated issue: #3640

**Comment by alanna** [comment]
This is done
