### ISSUE TITLE
Search not finding a Collective that exists

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3247]
[This Collective](https://opencollective.com/replikativ) has been created, but when I put its name into search, nothing appears.

![Screen Shot 2020-06-16 at 12 20 17 PM](https://user-images.githubusercontent.com/5498878/84718083-ded5d900-afcb-11ea-99c4-93aa29a2d45c.png)

**Comment by Betree** [comment]
It now appears in the search, so it looks like a delay before Algolia (the service that we use for the search) indexes it. I just checked and this index is currently refreshed on a daily basis. Maybe a first improvement would be to reduce this interval, let's say to 10 minutes? We must also make sure that this won't break our current plan limits.

**Comment by znarf** [comment]
@Betree I think we were considering dropping Algolia for Postgres? For example, anticipating that we stopped updating our Algolia package.

**Comment by Betree** [comment]
@znarf indeed and it would solve this issue. However we still need to study the performance impact before making the switch.

**Comment by znarf** [comment]
@Betree search GraphQL queries (with Algolia) are currently one of the slowests. It's also one of the least used one. If this can answer in less than ~2 seconds, we're good.

**Comment by Betree** [comment]
This should be fixed now that search is moved to SQL

**Comment by Betree** [comment]
This delay before showing collectives in search has been re-introduced to fight against spam (we are now waiting 48h before surfacing them). If that's something we want to support, we should clearly specify the use case to spec how we want to resolve it.

**Comment by znarf** [comment]
This can be adjusted or reverted, let see how this work out.
