### ISSUE TITLE
Fiscal Host admins should not be listed as Collective admins

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3248]
We just had a support request where the user was confused because she looked at the host page and saw it said she was labeled a "Collective admin" and therefore thought she was not a Host admin, which she is.

<img width="385" alt="Screen Shot 2020-06-16 at 4 13 46 PM" src="https://user-images.githubusercontent.com/5498878/84731310-9549b600-afec-11ea-9c2f-9f364d05b4b0.png">

I suggest we change that label to just be "admin" - if it's a host page it means host admin, if it's a Collective page it's a Collective admin.

**Comment by znarf** [comment]
And if it's an Organization ? And we should also consider funds.

**Comment by Betree** [comment]
@znarf I like this idea of using just `Admin` because it's generic, works the same way for Organizations, events...etc The way I renamed in https://github.com/opencollective/opencollective-frontend/pull/4432 is global, it will change all occurrences of "Collective admin" to "Admin"

**Comment by znarf** [comment]
@Betree Great, much simpler.
