### ISSUE TITLE
expenses small bugs

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#325]
When selecting "Other" in the payout method when submitting an expense, people usually use that field to send details about how to be reimbursed/paid. 
Can we show that in the list of expenses when logged in as the host?

Another bug: note the "undefined" as the submitter of the expense.

Also would be good to open a the link to the original attachment in a new tab/window.

![](https://cl.ly/2c092o40023y/Screen%20Shot%202017-03-14%20at%202.37.16%20PM.png)

**Comment by asood123** [comment]
yes, we can do that

**Comment by asood123** [comment]
- [ ] Only offer two types of payout methods. Paypal and Manual
- [ ] When manual payout method, show pay even without linking paypal
- [ ] when manual payout method, change 'pay' button to say something else
- [ ] make notes and attachment private for an expense and transaction
- [ ] show notes on expenses if user has permission to edit collective
- [ ] show notes and attachment in Transaction even after expense is paid
- [ ] show payout method on expenses on website
- [ ] some users show up as undefined, fetch user

**Comment by piamancini** [comment]
moving this to #478
