### ISSUE TITLE
Pledged collective caching issue

### ISSUE THREAD

**Issue by bkardell** [opencollective/opencollective#3252]
**Describe the bug**
Using the pledged collectives (like https://opencollective.com/css-selector-list-for-pseudo-in-chrome), pledging doesn't seem to update the page after complete, even refreshing afterward.  Adding a cache busting querystring seems to resolve this and show that your pledge has been counted.

**To Reproduce**
1. Go to https://opencollective.com/css-selector-list-for-pseudo-in-chrome
2. Click on pledge
3. Scroll down to choose amount
4. Submit
4. Your pledge is not visible

**Expected behavior**
Your just made pledge would be visible 

Expect this is just caching and probably applies to any os or browser.  I was using chromium on ubuntu, another person mac (unsure the browser) - we had the same experience.

**Comment by Betree** [comment]
Thank you for the report @bkardell, looks like we're not refreshing the cloudflare cache when a new pledge is submitted.

**Comment by Betree** [comment]
The fix for this issue will be deployed between now and early next week

**Comment by bkardell** [comment]
Thanks @Betree !
