### ISSUE TITLE
Expenses: filter by "Ready to pay"

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3253]
_Require #3204_

## User story 
On the host dashboard, there's a special filter for expenses to show only the ones that are ready to pay - which means the ones:
- That are approved
- With enough funds in collective balance
- If tax form is required for this host/user, it must have been provided

This filter was implemented as a frontend hack. As we're planning to show the new expenses list on the host dashboard, we must make sure that this feature is preserved and implemented in the most optimized way because host admins use it a lot.

## Best solution for this problem
The filtering **must** happen on the API side. However, in the frontend, we probably want to keep displaying the `Ready to pay` filter as just another status:

![image](https://user-images.githubusercontent.com/1556356/84881562-55d3a600-b08e-11ea-887e-33bb6d1e9bf9.png)

### API

- [ ] On `ExpensesQuery`, implement a boolean filter named `isReadyToPay` - default to `false`

### Frontend

- [ ] On `ExpenseStatusFilter` manually add en entry for the `Ready to pay` filter
- [ ] Set the flag in the GraphQL query if the `Ready to pay` filter is selected

**Comment by alanna** [comment]
The tax form is also a factor here. For hosts with the tax form activated, it must be received (if required for that user) in order for an expense to be ready to pay.

**Comment by Betree** [comment]
@alanna good catch! I've added that to the specs

**Comment by darkmtr** [comment]
@Betree can i take this up?

**Comment by Betree** [comment]
@darkmtr this issue has some inner complexity that will require syncing with other contributions, so we prefer to tackle it internally.
