### ISSUE TITLE
Bring the new expenses list to the host dashboard

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3254]
Require https://github.com/opencollective/opencollective/issues/3203

We want to bring the new expenses list to the existing the host dashboard, but we need to make sure that we don't loose any important feature in the process and there's a couple of things that we need to address for that - for example, we need to [re-implement the ready to pay filter](https://github.com/opencollective/opencollective/issues/3253) on GraphQL V2 and to see who we can integrate the whole feature of refilling the PayPal balance, the add funds...etc

In the spirit of continuous delivery, we can follow this plan:

1. Add a special tab in the dashboard that contains the new expenses list with its filters. We'll be able to iterate on the feature there.
![image](https://user-images.githubusercontent.com/1556356/84883414-c67bc200-b090-11ea-9474-af5b77cd7e71.png)

2. Once we think the feature is ready, make this new tab the default one and rename the other to `Expenses (legacy)`.

3. Finally deprecate the old tab once we're sure that we covered everything

This issue is about tackling the first step: bring the new expenses list to the host dashboard.

**Comment by piamancini** [comment]
SGTM

**Comment by Betree** [comment]
Resolved by https://github.com/opencollective/opencollective-frontend/pull/4527
