### ISSUE TITLE
Turn on 'edit sections' feature for fiscal hosts

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3257]
I want #2424 for fiscal host profiles please!

**Comment by alanna** [comment]
@Betree any chance for this happening soon? I'm blocked from sharing the OCNZ page because it just shows that huge "hibernating at the north pole" section, and I can't turn it off.

**Comment by Betree** [comment]
@alanna this message will disappear as soon as you have one contribution (one collective hosted, or a financial contribution). If that's blocking you right now I can manually edit the sections for the host to make sure it doesn't appear.

I haven't investigated the complexity of this issue yet. I can try to look at it this week, to do it if it's simple or at least add specs.

**Comment by alanna** [comment]
@Betree I have had a contribution and the dead space section is still showing: https://opencollective.com/ocnz

**Comment by Betree** [comment]
@alanna sorry, I meant an outgoing contribution. This section will show up when you have at least one membership.

It's a different issue, but maybe we can remove it entirely when there's no contribution.

**Comment by alanna** [comment]
@Betree if you could remove it that would be great! It's blocking me from sharing the link and inviting Collectives to join.

**Comment by Betree** [comment]
@alanna Done

I haven't had the time to tackle this issue last week but I've put in in my list for this week's priorities

**Comment by znarf** [comment]
I can't see the hibernating thing.

<img width="926" alt="Capture d’écran 2020-06-29 à 19 45 20" src="https://user-images.githubusercontent.com/806/86042010-d6a78000-ba46-11ea-87de-95f22b5a6527.png">

**Comment by Betree** [comment]
@znarf I've disabled the `Contributions` section

**Comment by alanna** [comment]
Thank you! It looks so good now.
