### ISSUE TITLE
Surface more information on expense submitters

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3258]
## User story 
> As a collective/host admin, I need to have accurate information to help me determine if an expense was submitted by legit users to make sure that they're who they pretend to be.

## Proposal
On the expense page, the expenses list, and the "new expense" email, we could surface some of the following items:

- If the user is new 
- If the collective is new
- Whether the payout method is new
- If the expense amount is extraordinarily high for the user and/or collective (inc. if this is the first expense for the Collective)
- If the reimbursement is missing a receipt
- If the user is likely to be operating multiple accounts (see #5200 or #5183)
- Their recent history, ie:
  - `4 expenses paid to this account` if it's an existing contributor
  - `/!\ First expense` / `/!\ New contributor` otherwise
- Whether their accounts are verified with any third-party platforms (i.e. 'blue check')
    - Github account
    - Twitter account

**Comment by Betree** [comment]
Another idea:

Show a special warning if using a new payout method (ie `/!\ New payout method`). That way if someone get hacked and someone submit an expense on their behalf with a different bank account/paypal, the collective/host admins will have a chance to see that there's something wrong.

**Comment by Betree** [comment]
A quick improvement for this: it is possible to copy the name and image for a profile, but not the `slug` (it's unique). So surfacing this when the authenticity of the profile matters can be a good practice to adopt. @Memo-Es wdyt?

![Peek 2021-04-23 10-29](https://user-images.githubusercontent.com/1556356/115843378-0fbe4000-a41f-11eb-98c1-51a6863ca538.gif)

**Comment by Betree** [comment]
According to the proposal made in https://github.com/opencollective/opencollective/issues/4491, we could surface an icon next to the contributor's name, showing a tooltip on hover:
- If another expense was paid in the past:
> :information_source: 
> Total expense payouts this calendar year ($YYYY):
> Invoices: $x; Receipts $y; Grants $z

- Otherwise
> :warning: 
> This is the first expense submitted by this contributor

**Comment by Betree** [comment]
The first part of https://github.com/opencollective/opencollective/issues/3258#issuecomment-886430408 is now implemented:
![image](https://user-images.githubusercontent.com/1556356/154430915-b7338272-7799-481c-8635-802ba82993af.png)

I suggest that, when all values are `0` like in the screenshot below, we instead display a warning icon and change the text to:
> This is their first expense for {collectiveName}

**Comment by Betree** [comment]
Other risks factors:
- Amount (are they emptying the full balance)?
- No attachment

**Comment by poohlaga** [comment]
Number of payment methods attached to the user. The number of successful vs. unsuccessful payments due to payment method. (Wise or PayPal may be a better indicator of fraud reports outside of our platform).

**Comment by Betree** [comment]
I like how Github displays a lot of information in a tooltip when you hover over the name, some of which is clearly meant to determine whether the commenter is "trustable". Using a tooltip saves space in the layout, and allows for dynamic fetching (which is great to not affect the initial load time of the page).

It's also a very simple pattern to re-use in different places without needing a design update.

Might not be the best UX for mobile, but still looks like an interesting solution to me.

![image](https://user-images.githubusercontent.com/1556356/186162846-d422731e-d509-43f0-9c3c-0554932b5670.png)

**Comment by BenJam** [comment]
some great ideas in here @betree thanks for gathering them in one place. I'm gonna edit the OP so that they're all listed as ideas that we can prioritise.

**Comment by alinamanko** [comment]
This is such an important conversation to have - thank you @Betree! I would add the following warning signs we encountered:

 - expense submitted and approved by the same user
 - a sense of urgency applied to the collective admin to get the expense paid out (that was specifically evident for a targeted collective under OCF when it came to claims for financial aid)
 - expenses submitted to the same collective by different people but with very similar descriptions and email formats, specifically when also lacking proper valid receipts

**Comment by poohlaga** [comment]
On the expense, it would be good to see an alert or a different status assigned to the expense if there are unresolved disputes or reviews in Stripe against the collective.

For any expense over a certain threshold, I'd want the user to be verified (https://stripe.com/identity).
