### ISSUE TITLE
Show a link to recent expenses

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#326]
Currently, if there aren't more than 3 pending expenses, we don't show a link to /collective/expenses. Add a link to the bottom to always take you to recent expenses

**Comment by asood123** [comment]
And would be even cooler if this page doesn't have any expenses that we give you suggestions on what you can file...

**Comment by xdamman** [comment]
I'd argue that we should always show the 3 latest expenses irrespective of their status (no reason to limit this to the pending ones).

i.e. the 2 last one could be pending, and the 3rd one is approved and paid, or if there are no pending expenses, just show the 3 latest approved/paid expenses.

**Comment by asood123** [comment]
That's a good idea

**Comment by asood123** [comment]
encapsulated here: https://github.com/OpenCollective/OpenCollective/issues/336
