### ISSUE TITLE
Events attendees export sometimes missing emails

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3260]
**Describe the bug**
The admin of [this Collective](https://opencollective.com/nenanhcc) reports:

> When I run the spreadsheet for attendees, sometimes it runs with the emails and sometimes it leaves them out. If I refresh my browser it seems to fix itself and then runs the the email version. Though the reliability makes me nervous as I am never sure if it is going to work or not. Is it me or a glitch?

**To reproduce**
I just tested using [this past event I'm admin of](https://opencollective.com/collective/events/open-source-speed-dating-fosdem-2020-96f78c6c#section-participants), and just as she said, the emails are missing. I clicked `EXPORT CSV` in the participants section, under "4 People Going". I refreshed and downloaded again, and the emails are still missing.

**Comment by Betree** [comment]
The data is fetched in https://github.com/opencollective/opencollective-frontend/blob/46b71c02810e5d5d58f298e1a81502e7462d7192/components/collective-page/graphql/queries.js#L206 and displayed in `components/collective-page/sections/SponsorsAndParticipants.js`.

From what I see we don't refresh the data when the user logs in, so changes are that today:
- Export will *never* work when you visit the page directly (ie. by copy pasting the address)
- Export will usually work when you reach the page via frontend navigation (ie. you click on a link on Open Collective)

We need to:
- Make sure we refresh the data when users login
- Make sure we don't display the `Export CSV` link until the data is refetched

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by darkmtr** [comment]
@Betree can i take this up?

**Comment by Betree** [comment]
@darkmtr sure!

**Comment by Betree** [comment]
:trophy: This issue has been completed by @darkmtr 

To claim the **$200** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
