### ISSUE TITLE
Include EVENTS in top nav bar

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3261]
## User story 
As an admin, I want to highlight that my Collective hosts events and encourage people to go.
As an event attendee, I want to easily jump to events on the Collective page.

## Best solution for this problem
Make `Events` a section that shows up next to `contribute` `budget` etc in the nav bar.

**Comment by Betree** [comment]
Events are currently part of the `Contribute` section. they're not a section of their own. Also we show connected collectives next to them (which is why the subtitle is `More ways to contribute`). So it's a tricky change.

**Comment by Betree** [comment]
Also there are now a lot of sections in this navbar. When there are two many we have to activate the horizontal scroll, and that's not a great experience (see the example on medium screen below). I'd rather push for simplification.

![image](https://user-images.githubusercontent.com/1556356/85266378-1208e400-b474-11ea-98b0-dca7699ba973.png)

**Comment by alanna** [comment]
The user who prompted this request specifically mentioned that people seeking to attend events are confused by it being classed as a type of contribution. It makes sense in terms of our platform, and maybe even to the Collective admin whose using events to raise money, but to the end user it doesn't make sense. She said people email her confused, asking how they attend events instead of "becoming a contributor". For Collectives which are highly focused on events, it's not a good design as is.

I definitely agree about the problem of too many things in the nav bar, but I think that's a seperate issue to solve from this one. I raised #3245 to discuss that. We are going to keep running into that because we're going to keep building new tools for Collectives.

'More ways to contribute' is a confusing place for connected Collectives to live, and trying to make everything fit inside this contributions section isn't working very well. With the new feature to reorder and turn on and off sections, I think it makes sense for events to be its own thing. If all the parts were more modular it would allow admins to better customize their pages and serve their particular communities. 

Sorry to expand the scope of this request but I think it's uncovering a weakness in the current design.

**Comment by alanna** [comment]
Closing in favor of #3245 and #3283 - but I really think we should address those two soon!
