### ISSUE TITLE
Make past events clearer

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3262]
## User story 
User writes:
> Is there a way to remove past events? or to move them to a different area? Or make the 'past event' writing more prominent. It is not very clear which are current and which are past. 

How it looks now:
![Screen Shot 2020-06-19 at 2 41 58 PM](https://user-images.githubusercontent.com/5498878/85091399-69703f80-b23b-11ea-9c42-20e05d66686f.png)

Only the first event above is active and the rest are past. But they all pretty much look the same except for the tiny text label.

## Best solution for this problem
Spatially or visually seperate current and past events.

**Comment by alanna** [comment]
related #2199

**Comment by SudharakaP** [comment]
@opencollective/design : Do we have an update for this or any new design ideas to make this visually more identifiable? 😄

**Comment by BenJam** [comment]
My proposal for this would simply be to hide past events below a button a la hosted collectives on https://opencollective.com/opensource:

![Screenshot 2022-01-04 at 09 36 17](https://user-images.githubusercontent.com/158833/148039799-dda04ebc-6124-4586-81f5-559b48945b7f.png)

@SudharakaP feel free to propose something as a starter when you hit an issue like this 👍

**Comment by SudharakaP** [comment]
As a quick and simple fix my thinking is change the color contrast between past and present events. I've proposed a PR for this above. Here are some screenshots; 

![image](https://user-images.githubusercontent.com/12435965/148132144-349f022a-3862-459d-9d6d-1955d3313c0d.png)

![image](https://user-images.githubusercontent.com/12435965/148132384-1dfb2ec0-f37f-4db0-9eac-ace73385aec4.png)

**Comment by Betree** [comment]
> As a quick and simple fix my thinking is change the color contrast between past and present events. I've [proposed a PR for this](https://github.com/opencollective/opencollective-frontend/pull/7303). Here are some screenshots;
> 
> ![image](https://user-images.githubusercontent.com/12435965/148132144-349f022a-3862-459d-9d6d-1955d3313c0d.png)
> 
> ![image](https://user-images.githubusercontent.com/12435965/148132384-1dfb2ec0-f37f-4db0-9eac-ace73385aec4.png)

That works for me, but let's ask for some feedback from @opencollective/design

**Comment by Memo-Es** [comment]
## Design update

We are proposing an update for the events section, on the public profile page and on its standalone page:

| Image reference | Description |
|-----------------------|-----------------|
|   ![Events](https://user-images.githubusercontent.com/49539954/148880680-cea719f5-b42c-480a-af13-d7175a634bef.png)   |  Past events grayed out, divider between upcoming events and past events  |
|   ![Standalone page](https://user-images.githubusercontent.com/49539954/148880684-2920ca57-4d94-48a4-8d6e-01ae071bb411.png)   |  Two different sections for upcoming events and past events, past events grayed out   |
|                       |                 |

### Important
The full update should include these issues as well, although not necessary to move forward with this issue
 - [ ] https://github.com/opencollective/opencollective/issues/5112
 - [ ] https://github.com/opencollective/opencollective/issues/4346

@SudharakaP @Betree

**Comment by SudharakaP** [comment]
The more exhaustive design update, we shall address in a new issue; https://github.com/opencollective/opencollective/issues/5121. This paper cut issue is linked to PR; https://github.com/opencollective/opencollective-frontend/pull/7303 which changes the color contrasts as a simple fix.
