### ISSUE TITLE
Scam expense

### ISSUE THREAD

**Issue by vjeux** [opencollective/opencollective#3268]
Someone requested a $1k dollar expense for one of the open source projects I maintain. This is probably a scam to get paid if the owner accidentally accept.

https://opencollective.com/excalidraw/expenses/20710

**Comment by znarf** [comment]
@vjeux it's unfortunately becoming common,. Collective admins needs to be extra cautious when reviewing incoming expenses.

We're not sure yet how to address that at the platform level. Let us know if you have ideas.

**Comment by Betree** [comment]
@vjeux We're not sure yet but some ideas have been curated in https://github.com/opencollective/opencollective/issues/2741, some feedback on what would be the most useful for you would help.

In the meantime feel free to forward the scam expenses that you receive to `support@opencollective.com`, we review all reports and ban scammers/spammers regularly.

**Comment by vjeux** [comment]
cc @petehunt who was in this business for a few years. He may have good ideas

**Comment by Betree** [comment]
https://opencollective.com/excalidraw/expenses/20710 has now been deleted, and its submitter banned. Thank you @vjeux

**Comment by vjeux** [comment]
Merci!
