### ISSUE TITLE
OC Leaderboard Question

### ISSUE THREAD

**Issue by awright** [opencollective/opencollective#3269]
**Describe the bug**
On the OC monthly newsletter, the Top Financial Contributors does not include a handful of large donations made to the [UPLIFT](https://opencollective.com/foss-responders/events/virtual-funding-event-q2-2020-4edd1e3a)! FOSS Responders Event. They include: 

- Sloan Foundation: [$50K](https://opencollective.com/sloan-foundation)
- Indeed [$11K](https://opencollective.com/indeed)
- DigitalOcean: [$10K](https://opencollective.com/digitalocean)
- Linux Fund: [$10K](https://opencollective.com/linuxfund)
- Sentry: [$10K](https://opencollective.com/sentry)

Additionally, neither FOSS Responders (collective) or the UPLIFT! (event) are on the "Top New Collectives" list even though we raised $115K. This does not seem right. 

**Expected behavior**
I would expect to see some of these orgs on the leaderboard and the $115 in donations acknowledged in the "top new collectives" list. 

.

**Comment by alanna** [comment]
@Betree can you look at the script and see why this might be happening?

**Comment by piamancini** [comment]
the script looks at May only - have these contributions been in may?

**Comment by awright** [comment]
Yes.

   - Sloan Foundation was (credited) on 05-20
   - Google Open Source: 05-20
   - Sentry.io 05-20
   - GitHub 05-12
   - Indeed 05-07 (their 10K commitment came on the 7th. the 1K add-on came
   in 06.02)

Linux Fund was on 04-28

**Comment by Betree** [comment]
I haven't found the time to investigate this yet but it's in my Todo. I suppose we need to fix that before the next newsletter, so I'll try to do it before the end of the month. Please let me know if you need this to be tackled sooner.

**Comment by Betree** [comment]
I just pushed a fix in https://github.com/opencollective/opencollective-api/pull/4249. There were two issues with these queries:
1. We were accounting for deleted transactions
2. Transactions without platform fees were ignored, probably to skip added funds. This is why the transactions to FOSS Responders haven't been included in the previous leaderboard

**Comment by awright** [comment]
awesome. thanks!
