### ISSUE TITLE
Terminology for Funds should not refer to Collectives

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3270]
<img width="767" alt="Screen Shot 2020-06-23 at 10 10 16 AM" src="https://user-images.githubusercontent.com/5498878/85340234-da646f80-b539-11ea-945a-8462049e7cc1.png">

I just accepted this invitation to join a Fund, but the text all references "Collective". It should say "Fund". I have a feeling this will come up for a lot of things related to Funds.

**Comment by znarf** [comment]
Funds is not a finished project. We're on it.

**Comment by piamancini** [comment]
<3 <3

**Comment by Betree** [comment]
That was resolved in https://github.com/opencollective/opencollective-frontend/pull/4802, then iterated on in https://github.com/opencollective/opencollective-frontend/pull/8503
