### ISSUE TITLE
UI should indicate that expense comments are private

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3276]
Thanks to #3216, expense comments are now private. But the interface does not do a good job of communicating that to the user. 

I was about to respond to a comment with some confidential payment info, and then I thought "Oh I better make sure that new private comments feature has been fully released... how can I know if this will be private?" And I realised I could not tell.

I'm not sure the best way to achieve this so I hope @Memo-Es and the designers can help.

**Comment by Betree** [comment]
Would be great if we could make the message below (displayed when users are not allowed to see the comments) prettier at the same time. Maybe we could have a similar box in two versions:

**Authorized**
:unlock: These comments are private, only the admins and the expense submitter can see them.

**Not authorized**
:lock: Comments for this expense are private. You must be signed in as an admin or the expense submitter to view them.

---

![image](https://user-images.githubusercontent.com/1556356/85856884-135e4780-b7b9-11ea-9067-339980a85688.png)

**Comment by Memo-Es** [comment]
This is the design for the privacy pop ups for expense comments: https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=5265%3A0

@Betree
