### ISSUE TITLE
Expense went through without required info

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3277]
Regarding this expense: https://opencollective.com/getferdi/expenses/16643

It has no payout method selected, and no payee address. But somehow it's been submitted and approved. How is this possible?

Expenses should not be allowed to be submitted or approved without the required details.

**Comment by alanna** [comment]
Screenshot in case the user edits it.
<img width="724" alt="Screen Shot 2020-06-26 at 11 26 06 AM" src="https://user-images.githubusercontent.com/5498878/85805226-d6d22200-b79f-11ea-8cbf-4563f090e98a.png">

**Comment by Betree** [comment]
This expense was submitted before the release of the new flow (2020-04-24).

**Comment by Betree** [comment]
The attached invoice has an address. I'm not sure about the payout method, the person probably selected "Other" at the time
