### ISSUE TITLE
Access 'create new organization' process when submitting an expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3278]
## User story 
As an expense submitter, I want to be able to create a new organization profile from the "Who is being paid for this expense?" interface on the submit expense form, so that I can select the correct payee and input the organizations address and payout preferences.

## Best solution for this problem
Be able to click "create new" in the "Who is being paid for this expense?" search/selection box when submitting an expense. It could be the same or similar as the "create new" model that pops up when you're adding new core contributors to a Collective.

## MVP
We already kind of have a workaround, because you can exit the expense process, create a new Organization, and then try again to submit the expense and be able to select the new Organization profile you made. But this is complicated for users.

*Note: this is part of the full implementation of "pay on behalf" which was originally part of the new expense flow spec but didn't make it in V1. The complexity comes from the need to generate an invitation process to the org admin if the person creating the profile is not actually the one behind the org.*

**Comment by Betree** [comment]
It was disabled on purpose, because we saw a risk if making it too easy that people would confuse this field and set `Heroku` there (rather than their personal profiles) if their bill was for some hosting on heroku. We also need a way for the organization admins to confirm the expense before it goes through.

I'll let @piamancini add more details if needed.

**Comment by znarf** [comment]
Doubling down on that, I'm super suspicious allowing everyone on the platform to create Organizations for others. That's creating more problems than it's solving. Unless we're doing it extremely right.

**Comment by alanna** [comment]
I agree that there are potential risks and issues if we let people create Organizations for others.

However, many Collective admins really want to submit expenses on behalf of vendors instead of asking those vendors to do it themselves, e.g. they have received an invoice from their lawyer, who is very busy, and they just want to upload it and have it be paid. 

The thing is, with no other option they submit the expense under their own profile. But we can't allow people to be submitting things and then asking they be paid out to third parties, as this is a risk for money laundering, and also messes up our tax stuff because the income looks like it's going to the wrong person.

So we have these options:
1. Allow people to create Orgs for others - pro: convenient to submit on behalf of vendor, income going to correct profile, payout and address details saved to associated payee. con: not good to have people representing orgs they aren't actually part of.
2. Do not allow people to create Orgs for others - pro: don't have random people representing companies they don't have permission to represent, con: people will raise expenses under their personal profile and it will be messy because we can't pay direct to the third party and the income looks like it's going to the wrong person.
3. Create some kind of invitation process similar to creating a new individual profile, where the actual person from the org gets the invitation, and they can input or confirm their payout details, etc, but much of the work has already been done for them to submit the expense. pro: maybe best of both worlds, con: more complex to implement.

**Comment by alanna** [comment]
Here is another example of this: https://opencollective.com/wa-state-3d-visor-mask-hub/expenses/21182

It comes up constantly. Users really want a way to submit invoices on behalf of vendors.

**Comment by piamancini** [comment]
The right way to do it is 3. Like any other vendor process. An invitation link from the collective admin to the lawyer to submit an expense. This quarter we are working on lowering the bar to do this. Similar to the guest checkout process vendors will add all details and we'll create the org for them at the end of the process.

**Comment by piamancini** [comment]
What we are building for Request grant could also be used to request payments. Almost like a pending order in reverse. We accept it, make the payment and $$ gets withdrawn

**Comment by Memo-Es** [comment]
Proposal for a new design to allow Collective admins to request an expense to vendors or community members @alanna
[→ Figma prototype ](https://www.figma.com/proto/KinuveYf4WUlRIXzMTnmIsmO/OC.com-Lab?node-id=7940%3A661&viewport=460%2C131%2C0.12921291589736938&scaling=min-zoom)

| 1. Collective admin  |  2. Collective admin |  3. Collective admin |  4. Collective admin |  5. Vendor | 6. Vendor   | 7. Vendor  | 8. Vendor  |
|---|---|---|---|---|---|---|---|
| ![1](https://user-images.githubusercontent.com/49539954/88508744-270df100-cfa5-11ea-8292-8fbaa2c29db4.png) | ![2](https://user-images.githubusercontent.com/49539954/88508742-270df100-cfa5-11ea-9bd0-ed00e893b7d7.png)| ![3](https://user-images.githubusercontent.com/49539954/88508740-270df100-cfa5-11ea-8e5c-98843e3134bd.png) | ![4](https://user-images.githubusercontent.com/49539954/88508739-26755a80-cfa5-11ea-8170-f8ff42f564e8.png)  | ![5](https://user-images.githubusercontent.com/49539954/88508730-22e1d380-cfa5-11ea-886a-2651b1b0154d.png)|![Screen Shot on 2020-07-27 at 01-00-40](https://user-images.githubusercontent.com/49539954/88509266-4c4f2f00-cfa6-11ea-8d6d-227e88f10b28.png)  | ![6](https://user-images.githubusercontent.com/49539954/88508737-25dcc400-cfa5-11ea-939d-3cea90263e7c.png)| ![7](https://user-images.githubusercontent.com/49539954/88508732-24ab9700-cfa5-11ea-8df4-d51ca875f381.png)

**Comment by alanna** [comment]
@Memo-Es this is a good start!

How does the user get to this flow? Will this be a third option next to "Reimbursement" and "Invoice"? I think it could be, but smaller and not as emphasised. We need to think of some very clear language so people understand when to click this option. "Create expense on behalf of someone else"? "Invite someone to submit an expense"? If we're also using this flow for grants and stuff, maybe just call it "Request" and then follow up with help text so people know if they're in the right place.

I think all the fields should be optional here, including uploading receipts, etc. This feature will likely be used for a wide variety of cases and we should allow the initiator to fill out whatever info they have and leave whatever they need to leave blank for the expense submitter. But all the mandatory fields need to be required for the final submitter.

It needs to be a lot clearer that you're submitting on behalf of someone else. The very first field in this type of expense should be the profile selector/creator that we already have implemented in other places in the app. People should be able to select an existing person or org profile, or create a new one that triggers an invitation to the new profile owner. Then they can fill in some or none of the expense info, add a note, and invite that profile owner to do the rest.

When the user clicks through to create their profile, they should be asked to confirm or enter all the details (profile name, change contact email, etc) - it should look like the normal profile creation form. And they should also have the option to sign into their existing Open Collective account in case they already have one.

Once they submit that, it should take them directly to the expense where they can confirm all those details and add any missing info.

So the flow for the invited submitter is: notification > email > click button > create or sign into profile > complete partly filled out expense > submit.

**Comment by Memo-Es** [comment]
### Design update
---

@alanna @piamancini @kewitz 
[→ Figma prototype ](https://www.figma.com/proto/KinuveYf4WUlRIXzMTnmIsmO/OC.com-Lab?node-id=8170%3A0&viewport=2227%2C732%2C0.39049237966537476&scaling=min-zoom)

| 1. Collective admin  |  2. Collective admin |  3. Collective admin |  4. Collective admin |  5. Collective admin | 6. Collective admin   | 7. Vendor  | 8. Vendor  | 9. Vendor  | 10. Vendor  | 11. Vendor  | 12. Vendor  |
|---|---|---|---|---|---|---|---|---|---|---|---|
| ![Invoice](https://user-images.githubusercontent.com/49539954/91928893-cb6d0c80-eca2-11ea-9940-e00a86aadaa3.png) | ![Invoice guest 1](https://user-images.githubusercontent.com/49539954/91928920-da53bf00-eca2-11ea-8241-fdced7bfd465.png)| ![Invoice guest 2](https://user-images.githubusercontent.com/49539954/91928939-e93a7180-eca2-11ea-975d-59b5abce4326.png) | ![Invoice guest 3](https://user-images.githubusercontent.com/49539954/91928958-f8b9ba80-eca2-11ea-8db4-48e40fd94d44.png)  | ![Invoice guest 4](https://user-images.githubusercontent.com/49539954/91928990-0ff8a800-eca3-11ea-94ea-1cc6e34b9e0c.png) | ![Invoice guest 5](https://user-images.githubusercontent.com/49539954/91929026-24d53b80-eca3-11ea-8f52-85b14c437ea2.png) | ![Invoice guest 6](https://user-images.githubusercontent.com/49539954/91929083-3d455600-eca3-11ea-81a9-d2beff42b8d9.png) | ![Invoice guest 7](https://user-images.githubusercontent.com/49539954/91929115-50582600-eca3-11ea-9766-b11e1f150064.png) | ![Invoice guest 8](https://user-images.githubusercontent.com/49539954/91929272-a927be80-eca3-11ea-8997-79b2af4f1802.png) | ![Invoice guest 9](https://user-images.githubusercontent.com/49539954/91929307-b9d83480-eca3-11ea-8414-88e05bf7fcbd.png) | ![Invoice guest 10](https://user-images.githubusercontent.com/49539954/91929325-c3619c80-eca3-11ea-867a-ce503bad0b69.png) | ![Invoice guest 11](https://user-images.githubusercontent.com/49539954/91929342-ce1c3180-eca3-11ea-9894-d95da4da2044.png) | ![Invoice guest 12](https://user-images.githubusercontent.com/49539954/91929371-dc6a4d80-eca3-11ea-9cc6-eae9a05729cd.png)

**If the user chooses to submit the expense using an organizational profile the form changes in step 9 with [this](https://d.pr/i/U3QVQ4) version**

**Comment by piamancini** [comment]
Hi @Memo-Es ! Great Some feedback: 

Image [number 3](https://user-images.githubusercontent.com/49539954/91928939-e93a7180-eca2-11ea-975d-59b5abce4326.png) Replace the question in the dropdown for: What's their name? 

On image [number 5](https://user-images.githubusercontent.com/49539954/91929026-24d53b80-eca3-11ea-8f52-85b14c437ea2.png) We should remove the blue box that prompts them to create an account, if they are an admin they have an account already. Idem for [Image 6](https://user-images.githubusercontent.com/49539954/91929026-24d53b80-eca3-11ea-8f52-85b14c437ea2.png)

On the email the [vendor receives](https://user-images.githubusercontent.com/49539954/91929083-3d455600-eca3-11ea-81a9-d2beff42b8d9.png) it'd be good to tell them they can edit these details before submitting. Otherwise they might think they need to contact the admin to change them. 

What happens after image 12?

**Comment by piamancini** [comment]
also cc @kewitz you should assign to the issue so you get updates. 
best !

**Comment by Memo-Es** [comment]
> Hi @Memo-Es ! Great progress! Some feedback:
> 
> Image [number 3](https://user-images.githubusercontent.com/49539954/91928939-e93a7180-eca2-11ea-975d-59b5abce4326.png) Replace the question in the dropdown for: What's their name?
> 
> On image [number 5](https://user-images.githubusercontent.com/49539954/91929026-24d53b80-eca3-11ea-8f52-85b14c437ea2.png) We should remove the blue box that prompts them to create an account, if they are an admin they have an account already. Idem for [Image 6](https://user-images.githubusercontent.com/49539954/91929026-24d53b80-eca3-11ea-8f52-85b14c437ea2.png)
> 
> On the email the [vendor receives](https://user-images.githubusercontent.com/49539954/91929083-3d455600-eca3-11ea-81a9-d2beff42b8d9.png) it'd be good to tell them they can edit these details before submitting. Otherwise they might think they need to contact the admin to change them.
> 
> What happens after image 12?

Fixed in [same comment](https://github.com/opencollective/opencollective/issues/3278#issuecomment-685273138) 
@piamancini

**Comment by alanna** [comment]
This is looking great! It's going to be a very helpful feature. I especially like how you handled account creation in the process.

> 3. Collective admin

I think the tickbox for `organization profile` will be confusing and people won't use it correctly. That's the language of how we understand our platform, not how the user thinks. I suggest there are three boxes, `name` `organization/company (optional)` and `email`. If they leave `organization` blank it's likely an individual profile. If they fill it in, it's likely an organization profile, and we should ideally create an individual profile for the person who is admin of the org profile that receives this expense payment. 

However, it should be up to the person invited to actually set the profile type when they accept the invite, and our system should do a good job guiding them on this. For example, lots of times someone I do work for just knows my name, but actually I need to invoice through my company, and I need a good path to follow to do that here.

> 4. Collective admin
I think the `add note` field should come at the end, after you put in the expense details. Otherwise people might think they have to put that info here, and often they wont feel the need to write a note after putting in the details and seeing how it will work.

> 6. Collective admin
This screen is missing the person who you are sending the invite to. I like how that's displayed on the previous screen at the bottom where the payee goes. Why remove it? This summary screen is about checking that all info is correct, and one of the main things is the name and email of the person you are inviting.

> 9. Vendor
Again I don't think the `organization` tickbox is a good solution. This form should have individual name and email required, and organization details as optional fields. If they don't enter the org name, it just creates and submits using an individual profile. If they do put in the org details, it should create an org *and* individual profile, with the individual as the admin of the org, and the expense submitted with the org profile as payee.

> 12. Vendor
I think we can do better when it comes to the whole email verification thing. Here's how I think it should work (I apoligise if this is how you already designed it - it didn't seem that way from the screenshots): 

On this screen the message about email verification appears, but it still lets you submit the expense. However, the expense is in a new kind of pending state (I think you're calling this "unpublished" - that makes sense from our perspective but from the user's perspective it would be better to call it "pending email verification" or "unverified" or something more informative than "unpublished"). The notification doesn't go to the Collective admin and the expense can't be approved yet. BUT it *does* allow the submitter to finish submitting the expense on this screen. Then later they can go to their email and click the verification link and they are finished. Otherwise on then screen 12 you're left if a weird hanging state and not sure if all the data you input will be saved or if you have to keep this tab open or what. This flow should come to a resolution, with a message to check your email to complete the last step.

**Comment by Memo-Es** [comment]
### Design update
---

Proposal for users to choose between their personal account and an organization account more easily

| Unauthenticated user - Personal  |  Unauthenticated user - Organization | 
|---|---|
| ![Unauthenticated - Personal](https://user-images.githubusercontent.com/49539954/96886947-afd3e600-1449-11eb-96e9-0ade4dff7056.png) | ![Unauthenticated - Organization](https://user-images.githubusercontent.com/49539954/96886930-acd8f580-1449-11eb-9121-dfbab291fb45.png) 

| Authenticated user - Personal  |  Authenticated user - Organization | Authenticated user - Collective picker dropdown
|---|---|---|
|  | New organization  | 
| ![Authenticated - Personal](https://user-images.githubusercontent.com/49539954/96891671-8073a800-144e-11eb-8503-788bb27296c4.png) |  ![Authenticated - Organization - New](https://user-images.githubusercontent.com/49539954/96891664-7f427b00-144e-11eb-96e8-9418c7686336.png) | ![Choose User](https://user-images.githubusercontent.com/49539954/96891673-81a4d500-144e-11eb-9de5-afa4f1df8a75.png) 
|  | Existing organization  | 
|  | ![Authenticated - Organization - Existing](https://user-images.githubusercontent.com/49539954/96891648-7c478a80-144e-11eb-9ea0-58c6ed8a43a2.png)  |


@alanna @piamancini @kewitz

**Comment by Memo-Es** [comment]
This is being implemented right @kewitz?
Can we mark this one as 'Closed'?

**Comment by kewitz** [comment]
@Memo-Es kinda, it is currently only available for invoices in selected collectives since it is implemented with the Submit on Behalf feature.

**Comment by kewitz** [comment]
This is now enabled by default.
