### ISSUE TITLE
the contributors.svg shows "Not Found"

### ISSUE THREAD

**Issue by jqhph** [opencollective/opencollective#3282]
I don't know why my contributor.svg shows "Not Found", what can I do to make it work?

https://opencollective.com/dcat-admin/contributors.svg?width=890&button=false

**Comment by znarf** [comment]
I just released [contributors.svg](https://github.com/opencollective/contributors-svg) as a separate Open Source repository. Anyone is welcome to participate.

I also deployed a new version which should normally fix this old issue.

Feel free to open issues and PRs in the new repository!
