### ISSUE TITLE
Decouple Events and Connected Collectives from "more ways to contribute"

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3283]
## User story 
As a Collective admin, I want control over the sections of my page, so I can present a clear message to my community.
As a page visitor, I want to be able to find what I'm looking for and understand the sections.

People don't natively consider events and Collectives as "ways" to contribute, and I think it's awkward conceptually and practically to have it all in one section.

## Best solution for this problem
Get rid of the "more ways to contribute" section and break it into its component parts - Events, Connected Collectives - so these can appear in the top nav bar and be turned on and off and reordered as needed.

Related: #3243 #3261 

This will require solving the problem of having too many items in the nav bar. I think it should show the top X items, then have a "more" dropdown or something like that. Also we could implement #3245 to leave more space by eliminating multiple action buttons.

## Metrics 
If users are reordering and activating these sections intentionally. If visitors are clicking these sections in the nav bar. Fewer support requests.

**Comment by Betree** [comment]
Resolved with the deployment of the new navbar, you can now disable events and connected collectives from your collective's settings. 

![image](https://user-images.githubusercontent.com/1556356/103912528-b6e4c900-5107-11eb-861d-6f8de82e31cc.png)
