### ISSUE TITLE
Add tests for the search expense feature

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3284]
We [recently introduced](https://github.com/opencollective/opencollective/issues/3214) a search feature for expenses. The underlying SQL query is quite complex, so we'd like to protect ourselves from future regressions by adding some testing on the API. The test should make sure that it:

- searches in expense description
- searches in expense tags
- searches in payee's name & slug

**Comment by SudharakaP** [comment]
@Betree : I'll take this no one is already on it. :smile:

**Comment by Betree** [comment]
Thanks @SudharakaP! I don't know how familiar you are with this test suite, but the way I personally like to run these tests is with `npm run test -- --watch path/to/my/test` (which will re-run them on each save). You can also add `-g` (aka grep) to filter by test name.

**Comment by SudharakaP** [comment]
> Thanks @SudharakaP! I don't know how familiar you are with this test suite, but the way I personally like to run these tests is with `npm run test -- --watch path/to/my/test` (which will re-run them on each save). You can also add `-g` (aka grep) to filter by test name.

@Betree : Thanks much; that is indeed helpful. :+1: I've created a pull request. Take a look and let me know if it needs any further adjustments. :smile:
