### ISSUE TITLE
Design system update: Late June 2020

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3286]
##  👉🏼 **[Expense component](https://www.figma.com/file/9Iq3vBOmZ2EuOacXEYD5yK/DS-05-UI-Kit?node-id=1859%3A23898)**: 
  
- Consolidated version of Expense visualization, both reimbursements and invoices in inline editing or with a modal

![Annotation on 2020-06-29 at 22-34-23](https://user-images.githubusercontent.com/49539954/86080785-4e7ea600-ba59-11ea-92fb-a8dd4fc93d02.png)

![Screen Shot on 2020-06-29 at 22-31-58](https://user-images.githubusercontent.com/49539954/86080856-7837cd00-ba59-11ea-8972-601e4de7277f.png)

![Screen Shot on 2020-06-29 at 22-32-27](https://user-images.githubusercontent.com/49539954/86080861-7e2dae00-ba59-11ea-9bc2-22c36651c264.png)

🟢 These updates are ready to be implemented platform-wide.
@opencollective/core-developers @Betree

**Comment by Betree** [comment]
Thanks @Memo-Es!
