### ISSUE TITLE
Feedback for new expenses list

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3288]
# Description

This issue is here to gather feedback and impressions around the new expenses list, especially from host admins that discover it from the host dashboard. Please note that this is an ongoing project, some parts are still missing and important changes are already planned.

# Preview

![image](https://user-images.githubusercontent.com/1556356/86107988-e2d12300-bac2-11ea-8e4e-21ef6fd849ad.png)

# Give feedback

Below are some questions to guide your feedback - you don't need to answer them all, feel free to answer with whatever format is easier for you:
- What is your general impression?
- Did you understand all the terms and actions that were presented to you?
- Did you encounter any glitches/bugs?
- Are there things that you especially like?
- Do you see things that could be improved?

_If you had experience with the previous flow:_
- Is this new flow faster for you?
- Is there anything that you did with the previous flow that you're not able to do anymore?

**Comment by alinamanko** [comment]
I am loving the new expense flow - making the process a lot quicker, especially with the integration of TransferWise payments. A few things I would like to note:

- In some instances where users are prompted by the collective admins to provide any additional information, people reply to the email notification rather in the expense thread. This means that these responses are going on Open Collective support rather than the collective admins and we need to make sure these are then forwarded to the relevant person. Any way we could prompt the responses to go through to the expense claim instead?
- When an expense is submitted as an expense, the generated form is impossible to be opened without it downloading first. This is a little bit of a pain point as previously these would open up in a new tab on the browser (which is still the case with any attachments the user includes)
- In the said form sometimes the user information is showing as incomplete - lack of full name, address etc. I know this has more to do with controls around the setup of an account initially. Just wanted to ensure I flag it here again but I think this is already being addressed

**Comment by alanna** [comment]
The buttons being greyed out when you're not hovering over them made me think the buttons were deactivated and that was stressful and confusing.

**Comment by piamancini** [comment]
yes - we made a fix they'll light up when you hover over any part of the expense row

**Comment by piamancini** [comment]
"When an expense is submitted as an expense, the generated form is impossible to be opened without it downloading first"
@betree is this the case?

**Comment by Betree** [comment]
> yes - we made a fix they'll light up when you hover over any part of the expense row

This update was deployed more that 24h ago so Alanna may have tested the latest version that light up when you hover over any part of the expense row. @alanna can you confirm?

> When an expense is submitted as an expense, the generated form is impossible to be opened without it downloading first @Betree is this the case?

Yes, the only way to download the generated invoice at the moment is through the download button. It's good to know that it's slowing down @alinamanko in her process, I think the "preview modal" that @Memo-Es recently presented can improve that.

![image](https://user-images.githubusercontent.com/1556356/86471972-a7db2380-bd3e-11ea-9a79-af2404d05760.png)

**Comment by kaylarep** [comment]
It looks great! Really clean and smooth, works fast too. I think everything is clear and understandable.

Some ideas/things I noticed (I'm new, so please forgive/disregard if these are irrelevant)
It would be nice to have:
-option to export filtered results lists into a report
-option to show specific category/tags: like to click on this "food & bev" tag, especially if these were used more often
![food bevtag](https://user-images.githubusercontent.com/64920686/86495885-f03f1500-bd2f-11ea-9844-eca2c972824b.JPG)

-'Sort by' options (high to low, newest to oldest, receipt #)
-view all results/50/100 (this type of option)
-"Pre-Approval Balance" is missing
-someone asked about if its possible to see a "post-paid expenses balance" as well-so they can have a better understanding of what they're budget would be if they paid off all the submitted expenses-he said it would give his group a more accurate understanding of their budget.

**Comment by leena4c** [comment]
Looks nice but for me it means a lot of extra 'clicks'. I need to open every expense to see what action is required and get the extra info I need before I can act e.g. name of the collective, the balance.

Info I like to get in one view to manage the expense efficiently: name - description - typical OC transaction number - picture of receipt/invoice - payment method and extra info (e.g. for a wire transfer) - collective name - balance of collective

Info that would be great to rearrange/filter the list: all the items now (great!) + the collectives if possible. Would be very useful to just filter on a specific collective there as well, as a host.

Small question: in the 'status' I miss 'ready to pay', one I use a lot in the old version. Has that changed to 'scheduled for payment'?

**Comment by Betree** [comment]
@kaylarep @leena4c thank you for the feedback :pray: 

> someone asked about if its possible to see a "post-paid expenses balance" as well-so they can have a better understanding of what they're budget would be if they paid off all the submitted expenses-he said it would give his group a more accurate understanding of their budget.

We have created an issue for this one: https://github.com/opencollective/opencollective/issues/3230

> Looks nice but for me it means a lot of extra 'clicks'. I need to open every expense to see what action is required and get the extra info I need before I can act e.g. name of the collective, the balance.

You're absolutely right, at the moment this list is missing some critical information. The currently designed view for admins should solve most of it (see screenshot below).

@Memo-Es we're not displaying the collective name in there (`from ____` is supposed to be the payee). Let's see what can be done.

![image](https://user-images.githubusercontent.com/1556356/86574613-6208a000-bf76-11ea-934c-887b3d9b91d4.png)

> Small question: in the 'status' I miss 'ready to pay', one I use a lot in the old version. Has that changed to 'scheduled for payment'?

@leena4c `Scheduled for payment` is a new status for expenses paid via transferwise (where there is a delay before the actual payment). The "Ready to Pay" filter will be there soon (https://github.com/opencollective/opencollective/issues/3253), we just need to work a bit on it to make it faster before adding it to this page.

**Comment by flaki** [comment]
I agree with the people commenting on the hover issues. I think avoiding heavy reliance on the hover property is especially commendable these days when touch devices are gaining prevalence (e.g. people using the dashboard on an iPad pro).

**Comment by Betree** [comment]
> I think avoiding heavy reliance on the hover property is especially commendable these days when touch devices are gaining prevalence (e.g. people using the dashboard on an iPad pro).

To add a note on this, the hover effect is disabled on touchscreens (all buttons are displayed with full opacity by default).

**Comment by Betree** [comment]
A new version of the list has been deployed for the host dashboard. It features:

- Rich information (payout method, collective balance...etc)
- A new layout optimized for host admins
- A modal to preview receipts
- Tax form status (for Open Source Collective only)

![Peek 09-07-2020 15-36](https://user-images.githubusercontent.com/1556356/87046841-f46ca600-c1f9-11ea-924e-dfb127c1508d.gif)

**Comment by Betree** [comment]
The "Ready to pay" filter for expenses is now deployed. We encourage everyone in this thread to use the new expenses tab in their daily process as we'll transition to making it the default.

**Comment by Betree** [comment]
Still waiting for more feedback :slightly_smiling_face: 

An important one that we haven't addressed yet is:
- "Pre-Approval Balance" is missing

**Comment by alanna** [comment]
Pre-approval balance is now a bit more complicated because we have both Paypal and Transferwise balances to handle.

**Comment by Betree** [comment]
All feedback in this issue have been taken into account to improve the new expenses list, which is now the default view on the host dashboard. We'll keep the old one in the `Expenses (legacy)` tab a bit longer in case there's anything we forgot.

Feel free to open new issues if you are missing some features or if you see things that could be improved.

Thank you everyone!
