### ISSUE TITLE
Make expenses great again

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#329]
We have lots of states for expenses - all of which can use design help.

Some background on how the system works:
- Expense is filed by anyone, status = `PENDING`
- A Core Contributor or Host can approve or reject. Status updates to `APPROVED` or `REJECTED`.
- A Host can pay. Expense status updates to `PAID`. We also create a transaction in the Collective's Ledger that updates the balance of the collective.

We have three different viewers for an expense:

1. Public/anyone
- All the basic info visible for an expense: title, amount, category (travel, food, etc), status (pending, approved, paid), submittedBy (name only), date of expense, payoutMethod (as in how to reimburse - paypal or manual. note: this is missing from the screenshot.)

![screenshot 2017-03-22 10 46 56](https://cloud.githubusercontent.com/assets/6106941/24203723/e37ad358-0eec-11e7-825a-d9b1783cd987.png)

ex: https://www.opencollective.com/opencollective and https://opencollective.com/opencollective/expenses

2. Core Contributor/Member
- All the info that's public
- SubmittedBy is now name and email
- Payout Method is editable, can be changed from paypal to manual and vice versa (missing from screenshot)
- Notes field (private field to share things like here's my bank info to send the wire to) (missing from screenshot)
- Attachment (receipt that's attached to the expense)
- Actions: Approve or Reject

What it looks like today: 
![screenshot 2017-03-22 10 49 09](https://cloud.githubusercontent.com/assets/6106941/24203849/328017ce-0eed-11e7-9c36-85df1c19a17e.png)

3. Host
- All the info for Core Contributor
- If payoutmethod is 'paypal', we need to show the paypal email.
- Actions: Pay

What it looks like today:
![screenshot 2017-03-22 10 50 50](https://cloud.githubusercontent.com/assets/6106941/24203951/6faef07a-0eed-11e7-9a2c-9defac050f80.png)

Other things needed: 
- disable states of buttons with ability to show a message. For example, there isn't enough money in the collective, a green 'pay' button doesn't make sense. Instead, we should disable the button and put a message saying, you need more money in the collective. (Currently, we let you hit it and then show the error).

Note that we are going to need to do something similar for Transactions. Currently, we show the following for a transaction:

![screenshot 2017-03-22 10 42 35](https://cloud.githubusercontent.com/assets/6106941/24203487/458c604e-0eec-11e7-9054-357b55892e02.png)

ex: https://opencollective.com/opencollective/transactions
When a transaction is an expense, we want to show some of the original expense information in it, like notes and the original receipt, so likely have a "+" button to expand it.

**Comment by cuiki** [comment]
Hi guys, here's the screens for the expenses widget. It shows:

- Expense pending (Public - hidden receipt)
- Expense pending (Core Contributor / Member)
- Expense pending (Host)
- Expense pending (Host - no funds available)

![expenses-widget](https://cloud.githubusercontent.com/assets/981188/24368577/2c66fe30-12de-11e7-83f3-37be235c5621.png)

Let me know your feedback. I'll work now on the mobile version (300px width).

**Comment by piamancini** [comment]
que lindas @cuiki !

**Comment by cuiki** [comment]
Gracias @piamancini !

Guys, here is the updated versions with the mobile views. I had also forgot the small feature of changing the payout method in the Core Contributor/Member version.

Let me know if you have any feedback. :D

![expenses-widget-updated](https://cloud.githubusercontent.com/assets/981188/24369641/e1cff7ec-12e1-11e7-90e5-57d2bd346054.jpg)

**Comment by asood123** [comment]
Very nice @cuiki!! More comments once I get a chance to dig in.

**Comment by cuiki** [comment]
Hi again. Here is the view for transactions. I took the liberty of working a bit on that page. Regardless of if you implement it now or no, it shows how to display the details of an expense. It was a simple solution using the same component for now. Let me know your thoughts.

Zeplin link: https://zpl.io/2soJvo

![widgets - transactions](https://cloud.githubusercontent.com/assets/981188/24419655/1f7183f6-13ad-11e7-934d-e8d15979b420.jpg)

**Comment by asood123** [comment]
i like that a lot @cuiki. i'm going to implement once i get back to coding.

**Comment by asood123** [comment]
@cuiki - Let's add fees while this is still fresh in your mind.

On expenses: we need to show paypal fees in cases where Payout Method is Paypal. It's usually 2.9% + $0.30. Maybe by the pay button? If it's a $40 expense, we could show the final amount - $41.56.

On transactions: we have a few fees to show.
- Expenses: paypal fees (payment processor fees) 
- Donations: stripe fees (payment processor fees), host fees and platform fees. 

For transactions, fees can be in the detailed view.

**Comment by cuiki** [comment]
Hey @asood123, are the fees visible for all versions of the expense or just for Contributors and Hosts?

**Comment by asood123** [comment]
All versions

**Comment by cuiki** [comment]
Also @asood123, can you give me example amounts for donations? Just like you did for PayPal.

› Donations: Stripe fees **(?)** + Host fee **(?)** + Platform fee **(?)** = **$??**

**Comment by cuiki** [comment]
Hi guys, so here are the changes applied from the feedback:

1. **Expenses** - All I did was move the amount below the _Payout Method_ info. I think it was the simplest and best solution for now.

![widgets - expenses](https://cloud.githubusercontent.com/assets/981188/24683382/5946cc96-1964-11e7-8cd3-1c53ac7f3272.jpg)


2. For transactions I added the fees and I made a Donation detail view. The amounts are not realistic in the example since I don't know the fees for donations. Once I get them I'll update the mock to reflect this.

![widgets - transactions donations](https://cloud.githubusercontent.com/assets/981188/24683401/7c76ae16-1964-11e7-8f95-0ec2f14ee986.jpg)
![widgets - transactions expenses](https://cloud.githubusercontent.com/assets/981188/24683402/7c79cefc-1964-11e7-87d1-e8b46e0f34d0.jpg)

Zeplin links remain. 🌮

**Comment by asood123** [comment]
@cuiki For a $10 donation: 
- Stripe fee: 2.9% + $0.30, so $0.59
- platform fee: 5%, $0.50
- host fee: 5%, $0.50

Net for collective: $10.00 - $0.59 - $0.50 - $0.50 = $8.41.

I think in most cases, it's better to show the absolute fee and maybe we can show the percentage on overlay?

**Comment by cuiki** [comment]
Yeah, but that only works on desktop. There are no tooltips in mobile, and we'd have to rely on something like iPhone's 3D-touch. That's why I opted for showing it there. Err, wait you mean overlay like in a modal?

**Comment by asood123** [comment]
Good point, re: mobile. Let's show it for now. More info is better than less.

**Comment by cuiki** [comment]
Cool. Instances are now updated in Zeplin.

- Transactions (**Expenses**) › https://zpl.io/1nn4Aq
- Transactions (**Donations**) › https://zpl.io/1nn50P

**Comment by xdamman** [comment]
@cuiki can you help me design the view of all expenses across all the collectives that a host is hosting?

![](https://cl.ly/3c2H3o0V051M/Screen%20Shot%202017-10-23%20at%203.55.54%20PM.png)

**Comment by cuiki** [comment]
Hey, take a look in Zeplin: https://zpl.io/Vxmor9W

**Comment by piamancini** [comment]
closing this. design has been updated
