### ISSUE TITLE
Add bank payout method form not clear which address it wants

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3293]
Is this screen asking for my organization's address, which is already filled out on the left but could potentially be different to the address associated with my bank account, or my bank's address? We should make this clear to the user.

<img width="667" alt="Screen Shot 2020-07-01 at 10 47 52 AM" src="https://user-images.githubusercontent.com/5498878/86185285-14f98800-bb8a-11ea-9e57-539694e174e6.png">

(I already raised a separate issue about how the fields are greyed out).

**Comment by znarf** [comment]
@kewitz @alanna Can we consider that solved?

**Comment by alanna** [comment]
I think it was solved on another issue by adding a tooltip. If @kewitz has completed that with the help text I supplied, this can be closed.
