### ISSUE TITLE
Expense submitted without adddress

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3294]
https://opencollective.com/wa-state-3d-visor-mask-hub/expenses/21182

<img width="800" alt="Screen Shot 2020-07-01 at 11 12 08 AM" src="https://user-images.githubusercontent.com/5498878/86185970-d6fd6380-bb8b-11ea-95bc-0f0aca083981.png">

Expenses should not be allowed to be submitted without the payee's address details filled out.

**Comment by Betree** [comment]
It's because it's a receipt, addresses are only required for invoices.

**Comment by alanna** [comment]
Ah I see. The user was confused and actually was trying to submit an invoice.
