### ISSUE TITLE
Not asking for reason when rejecting expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3295]
I am 99% sure we built this feature in the new expense flow, but I just rejected [an expense](https://opencollective.com/wa-state-3d-visor-mask-hub/expenses/21182) and it didn't pop up asking me to input a reason. Shouldn't it show me a modal where I can put in why the expense was rejected?

**Comment by Betree** [comment]
The modal is for rejecting collective applications, we didn't build that for the expense flow because you can already provide a reason through comments

**Comment by alanna** [comment]
Ah ok, I was mistaken.
