### ISSUE TITLE
ZipBooks as an alternative to Xero 

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#3296]
Below are some initial notes from the review of ZipBooks while clearing out any outstanding transactions for OSC and OCF:

- There seems to be an automatic suggestion of item category based on previously recorded similar transactions. It is up to the user to confirm the classification 
- The transactions category is showing all the listings from all the bank accounts linked to the user profile- so both OSC and OCF. To see the transactions related to specific accounts go to Manage Banks and select the relevant bank account to work on each host separately 
- The balance of unallocated transactions showing is representing all the open bank accounts. So in an instance where there a number of unreconciled transactions for each of the accounts, the user will see the accumulated amount to allocate showing
- When trying to classify incoming funds, it is a bit tricky to add details about the collective. There is an option to add tags, but this is only available on the $35 p/m plan. This means that if we want to look through a history of transactions with specific description to see which collective they should be attributed to, it is not really available
- You can edit transactions and add additional documents which may be useful to compensate for the lack of functionality above perhaps.

**Comment by alinamanko** [comment]
@alanna for the question you had around the attribution of a payment to an invoice - when the payment occurred, you can go to the invoice and select the option of Add Payment to mark it as paid

**Comment by alanna** [comment]
Xero started working again so we're moving back.
