### ISSUE TITLE
Contribution policy set by Host admin

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3297]
## User story 

As a Host admin, I want to communicate what kind of financial contributions we accept and any terms and conditions that apply.

User feedback:

> Mocha does not want to accept donations (nor display the logo) from certain sketchy classes of sites.  We were thinking of drafting a policy, but it doesn’t seem like something we can do unilaterally, and I’m not sure what this would imply.  I am unsure how to proceed. We have taken to maintaining a blocklist of contributors which we do not want to display on mochajs.org--as a “band-aid”.  But we should take other measures to address this. for example, I suppose we’d want to draft a policy like, “Mocha reserves the right to display logos and links on mochajs.org at its discretion.  A donation does not guarantee a logo or link will appear on mochajs.org.” people may want refunds… and that’s fine, we don’t want their money.

## Best solution for this problem

A setting similar to the expense policy, which is basically a text box in settings and that text is displayed in the contribution flow.

Needs #2006 to enforce it.

## Specs

In the Host Settings of an Organization, in the "Expenses & Payouts" section (1)
1. Rename "Expenses & Payouts" to "Policies"
2. Add "Contribution Policy" textarea similar to "Expenses Policy". It's already existing for Collective policies, see (2)
3. On the API side, ensure it's saved in the `contributionPolicy` of the Collective table
4. Make sure the contribution policy is displayed in the FAQ like the one from Collectives (3)

## Test

1. Create an Organization
2. Activate as Fiscal Host
3. Set a Contribution Policy in settings
3. Create a Collective
4. Pick the Organization you just created before as Fiscal Host
5. Do a Financial Contribution to the Collective

The Contribution policy should appear in the FAQ on the right (3)

## Screenshots

(1) Screenshot of the current "Expenses & Payouts" section for Fiscal Hosts

<img width="1249" alt="Screenshot 2021-01-21 at 14 24 46" src="https://user-images.githubusercontent.com/806/105357666-6dab7380-5bf5-11eb-8de0-9d181e39acdf.png">

(2) Screenshot of the existing Collective Contribution policy

<img width="1282" alt="Screenshot 2021-01-21 at 14 32 31" src="https://user-images.githubusercontent.com/806/105357755-8fa4f600-5bf5-11eb-8c27-fba24d2e046c.png">

(3)  Screenshot of the Contribution policy in the FAQ
<img width="1033" alt="Screenshot 2021-01-21 at 14 39 20" src="https://user-images.githubusercontent.com/806/105358515-8cf6d080-5bf6-11eb-9c66-dfd5010508a1.png">

**Comment by alanna** [comment]
Does #3596 solve this? or is that one only for Collective admins? We also need this at the host level.

**Comment by Betree** [comment]
> Does #3596 solve this? or is that one only for Collective admins? We also need this at the host level.

It partially does, the setting cannot yet be edited at the host level.

**Comment by alanna** [comment]
Editing this issue to focus on the Host level as the Collective level is already done.

**Comment by znarf** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by znarf** [comment]
@snitin315 Sorry, according to our [rules](https://docs.opencollective.com/help/contributing/development/bounties), only 2 bounties assigned at the same time for you.

**Comment by snitin315** [comment]
Oh! I see. Although I believe others are almost complete I will wait for them to be closed. Removed my assignment 👍🏻

**Comment by segfult** [comment]
@znarf can i take this one up?

**Comment by znarf** [comment]
@segfult Is it your first one? Sure! Have a try. I'm putting a 1 week limit on it.

**Comment by segfult** [comment]
> @segfult Is it your first one? Sure! Have a try. I'm putting a 1 week limit on it.

my third one i believe.

**Comment by znarf** [comment]
🏆 This issue was completed by @segfult 

To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Comment by segfult** [comment]
> trophy This issue was completed by @segfult
> 
> To claim the bounty, you can either:
> 
>     * Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
> 
>     * Or ask for an Open Collective gift card of the same value (to donate to other collectives)

Thank you @znarf. I have submitted the expense at https://opencollective.com/engineering/expenses/32586
