### ISSUE TITLE
`contributors.svg` seems to miss some contributions

### ISSUE THREAD

**Issue by dubzzz** [opencollective/opencollective#3298]
**Describe the bug**

The svg showing the Contributors for the repository dubzzz/fast-check does not seem to be synchronized with the current state of the project. 

**To Reproduce**
1. Open https://opencollective.com/fast-check/contributors.svg?width=890&button=false
2. You see 22 contributors while it should be 29 as on GitHub

**Expected behavior**

The contributors should be the same as the ones reported by GitHub for this project, see Contributors to dubzzz/fast-check at https://github.com/dubzzz/fast-check/graphs/contributors

**Comment by znarf** [comment]
I just checked and see 22 contributors:

<img width="866" alt="Capture d’écran 2020-07-01 à 09 31 03" src="https://user-images.githubusercontent.com/806/86215991-a282ab00-bb7d-11ea-88b6-b01cada96642.png">

**Comment by dubzzz** [comment]
And the count on GitHub:
![image](https://user-images.githubusercontent.com/5300235/86221839-b7fbd300-bb85-11ea-9390-ef3abcddc9c2.png)

**Comment by dubzzz** [comment]
@znarf Actually We should see 29 contributors not 22. GitHub reports that the repo as 29 contributors, contributors.svg only shows 22 of them

**Comment by dubzzz** [comment]
It seems that the problem came back

**Comment by znarf** [comment]
I just released [contributors.svg](https://github.com/opencollective/contributors-svg) as a separate Open Source repository. Anyone is welcome to participate.

I also deployed a new version which should normally fix this old issue.

Feel free to open issues and PRs in the new repository!
