### ISSUE TITLE
Add address fields in add fund's collective picker

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3299]
## User story 
> When I create a new organization for adding funds to a collective I am normally on their site looking up a logo or their website. It's a great opportunity to add an address as well which we know we'll need next year to file our taxes.

## Best solution for this problem
In the collective picker used for `AddFunds`, add two optional fields: `country` and `address` in the create form `CreateCollectiveMiniForm`.

**Comment by Betree** [comment]
@JoyLubega are you still working on this?

**Comment by JoyLubega** [comment]
Yeah, I am working on it. let me try to move faster

**Comment by JoyLubega** [comment]
@Betree I am trying to find the exact form as described above. Is this the form?
![Screenshot 2020-08-12 at 14 36 06](https://user-images.githubusercontent.com/29824008/90010897-58770400-dca9-11ea-8e65-5153f4aefcbd.png)

**Comment by Betree** [comment]
@JoyLubega the form is mentioned in the issue description, it's `CreateCollectiveMiniForm`. We want to display the address only when it's used in `AddFundsSourcePicker`. This component is a bit tricky to test, you need to go to the host dashboard, pick a collective and click on `Add Funds`. 

If you're not comfortable with that part of the code, I recommend looking at the [other open issues](https://github.com/opencollective/opencollective/issues/3380) that may be more accessible. Feel free to ask if you're not sure what to work on :slightly_smiling_face:

**Comment by JoyLubega** [comment]
Let me give it a try. I will let you know by tommorrow

**Comment by JoyLubega** [comment]
@Betree I think it might take me more time than I expected. I am unassigning myself

**Comment by Betree** [comment]
That was done in https://github.com/opencollective/opencollective-frontend/pull/4963
