### ISSUE TITLE
events feedback and usability

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#330]
The 'events' issue is huge, so I'm starting a new one for this.  3 issues came up from using events yesterday.

- [ ] We want to have a 'sponsor' tier but nit give them tickets in exchange, just a donation. The problem is that we want to link to only one site (tickets one) to optimize. Ideally we can have the $500 Sponsor ticket but changing 'ticket' for 'support' (or similar) + remove the ticket numbers. 

- [ ] Modify twitter flow so it also automatically thanks sponsors/backers from the events page. 

- [ ] Organizations/Sponsors should be seen as sponsors and not attendees. 

- [ ] Can't past credit card details, 1password enters the details but system doesn't recognize.

**Comment by jdorfman** [comment]
@piamancini also a "Tweet this" call to action so people can share that they just purchased tickets and will be attending X event. =D

**Comment by piamancini** [comment]
Also general feedback, we came and went a lot with tickets, changing prices, descriptions and tiers. If we hadn't had access to the DB, it would have been a pain.  I think this feature is not really ready for release outside of our team until we can give users control over it.

**Comment by piamancini** [comment]
When someone purchases two tickets they show up twice on the attending list. We should give them the option to add someone else.  @xdamman could we use what we have on /create to do it?

**Comment by xdamman** [comment]
Mmmm... that's probably because they bought two tickets separately. If they buy them in one go but with the quantity set to 2, they should only show up once.
