### ISSUE TITLE
Expense notification email has wrong amount

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3301]
[This expense](https://opencollective.com/ocnz/expenses/21339) has the correct amount:

<img width="793" alt="Screen Shot 2020-07-02 at 10 28 54 AM" src="https://user-images.githubusercontent.com/5498878/86297266-f4dfcc80-bc4e-11ea-9730-5e9e1d093a13.png">

But the amount was different in the email:

<img width="871" alt="Screen Shot 2020-07-02 at 10 29 20 AM" src="https://user-images.githubusercontent.com/5498878/86297346-2ce70f80-bc4f-11ea-999d-413368c6a8d3.png">

**Comment by Betree** [comment]
From the activity log, it looks like the expense was updated. Maybe the user updated the amount? I'll check tomorrow to confirm

**Comment by alanna** [comment]
Ah that would explain it. I nearly had a heart attack when I saw the expense for twice as much as I thought it was going to be... lol

**Comment by Betree** [comment]
I can confirm that the expense was initially created with an amount of `$2927.45` then a few minutes later updated to `$1548`. It would be great for admins to be able to see exactly what was updated in the activity log, under the `Expense updated`. I'll create an issue dedicated to this.
