### ISSUE TITLE
Allow platform admins to remove themselves as admins

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3303]
## User story 
As a platform admin (Open Collective core team member) I often have to create or edit various profiles (Collectives, Hosts, Organizations, Events) while doing support, etc, but then I need to remove myself as admin and let the customer take over. We don't allow people to remove themselves as admins (so that profiles don't become orphaned), but platform admins should be able to do this.

## Best solution for this problem
Remove the restriction on removing yourself as an admin from platform admins only.

**Comment by Betree** [comment]
I actually was slowed down by this behavior too in the past. Could we make it so that you can't remove yourself if you're the last admin, but you can still do it if there are other admins? @znarf what to you think?

**Comment by znarf** [comment]
@Betree I don't see a problem with that. We can always troubleshoot through support if they make a mistake.

**Comment by piamancini** [comment]
I don't think we should let people remove themselves if there's no one left. We need to ask them to archive the collective

**Comment by Betree** [comment]
> I don't think we should let people remove themselves if there's no one left.

That's the point, only let them remove themselves if they're not the last admin

**Comment by alanna** [comment]
I'd like to bump this, whether just for platform admins or for everyone as long as their not the last admin. 

As first part hosts are growing, we're creating off-platform application processes and we don't have a way to enable only invited Collectives to join a host (see #3548) so a workaround is the host admin (who is also a platform admin in the case of first part hosts) can create Collectives based on applications through an external form while the "allow applications" setting is toggled off for that host, but it's blocked by this issue.
