### ISSUE TITLE
OCF host unable to pay with TransferWise even though it's connected

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3308]
Transferwise is activated for Foundation:
![Screen Shot 2020-07-03 at 2 08 01 PM](https://user-images.githubusercontent.com/5498878/86424410-9d1c9080-bd36-11ea-9750-a389f1fb74f7.png)

But on an expense you're unable to select bank transfer as the payout option:
![Screen Shot 2020-07-03 at 2 08 59 PM](https://user-images.githubusercontent.com/5498878/86424447-b7ef0500-bd36-11ea-95d8-33ce7666e563.png)

**Comment by kewitz** [comment]
Hey @alanna, I wasn't able to reproduce this on production.
Can you confirm that this was an expense being submitted to the host itself? (through https://opencollective.com/foundation/expenses/new)

![Screenshot from 2020-07-06 14 11 16](https://user-images.githubusercontent.com/2119706/86620397-a4d87100-bf92-11ea-87c1-6c5549093623.png)

**Comment by Betree** [comment]
May have been solved in https://github.com/opencollective/opencollective/issues/3302 with https://github.com/opencollective/opencollective-api/pull/4159 + https://github.com/opencollective/opencollective-frontend/pull/4573

**Comment by alanna** [comment]
this is working now thanks
