### ISSUE TITLE
Cache issues when editing the slug of a profile

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3314]
**Describe the bug**
When editing the slug of a profile, there are two issues:
1. We're not redirected to the new `/edit` URL
2. The user menu still shows the old URL

**To Reproduce**
1. Go to /my-collective/edit
2. Edit the slug

**Expected behavior**
- Current page URL should be updated (use `Router.replaceRoute`)
- User menu should be updated (by using `refetchLoggedInUser`)

**Comment by znarf** [comment]
The feature looks pretty broken because of this issue. I think it's important.

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by brymut** [comment]
I'd like to take a try at this

**Comment by brymut** [comment]
Looking at this, would it be appropriate to update the route here before the settimeout with a if statement to check if the `collective.slug` at this point is the same as the current route? If not update the route and `refetchLoggedInUser`
https://github.com/opencollective/opencollective-frontend/blob/9ea25474b61b5ddb678762cb60efbdb7f367ba88/components/edit-collective/index.js#L72

**Comment by Betree** [comment]
@brymut sounds like a good way to do it 👍

**Comment by Betree** [comment]
:trophy: This issue has been completed by @brymut  

To claim the **$100** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
