### ISSUE TITLE
Recurring contributions: multiple popup conflicts

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3315]
**Describe the bug**
Because they have the same inputs `name`, the popups in edit recurring contributions conflict with each others.

**To Reproduce**
1. Go to /subscriptions
2. Edit multiple contributions at the same time

**Expected behavior**
States should be independent.

**Screenshots**
![Peek 06-07-2020 13-58](https://user-images.githubusercontent.com/1556356/86591016-039ceb00-bf91-11ea-8f20-caa9e8fb1143.gif)

**Comment by Betree** [comment]
@sbinlondon the fix should be really simple on this one, would be great if we can look at it this week

**Comment by sbinlondon** [comment]
Is this still an issue? Can pick it up if so.

**Comment by Betree** [comment]
It is, but that's something a contributor can do if you don't have the bandwidth right now

**Comment by sbinlondon** [comment]
Have fixed the conflicting menus but now there's a small bug with set tiers not sending the right option in the GraphQL mutation so looking into that.
