### ISSUE TITLE
Erroneous recurring contributions are not showing up

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3318]
**Describe the bug**
Because of the filters on order type (the [ones from original PR](https://github.com/opencollective/opencollective-frontend/blob/1df827ed20b6f33b7398029385792b69a710f6ee/components/recurring-contributions/RecurringContributionsContainer.js#L35) and the one introduced in https://github.com/opencollective/opencollective-frontend/pull/4593/files) we're not showing recurring contributions that have the `ERROR` status. It's quite important, because people are looking for them to update their payment method and re-activate the contribution.

**To Reproduce**
1. Go to /profile/recurring-contributions
2. In the DB, mark one of the orders there as status=`ERROR`

**Expected behavior**
The contribution should show up, ideally with a red `ERROR` tag to quickly identify it. Be aware that `ERROR` orders are not necessarily recurring, so you'll need to make sure there's a subscription attached.

**Comment by sbinlondon** [comment]
I hadn't realise this was something we wanted to display. I definitely remember discussing at some point that we only wanted to show ACTIVE or CANCELLED, at least while I was building it a few weeks ago. But thanks for doing this!
