### ISSUE TITLE
Multiple pledges to a pledged collective creates duplicate backers

### ISSUE THREAD

**Issue by fred-wang** [opencollective/opencollective#3319]
If someone donates twice to a pledged collective then they are counted as two backers.

**To Reproduce**
1. Go to a pledged collective at https://opencollective.com/discover?show=pledged
2. Make a "one time" plegde
3. Make another "one time" plegde
4. The interface will display your two pledges and count you twice as a "backer" (see screenshot)

**Expected behavior**
There are two behaviors expected:
* First the person could either mean to replace the amount of their one-time plege or more money. The plegde interface should clearly inform the user about what's going to happen.
* The interface should merge one-time pledges into a single one and report only one backer for them.

**Screenshots**
![multiple-donations](https://user-images.githubusercontent.com/567455/86884054-4971c480-c0f3-11ea-9483-137be284b774.png)

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Additional context**
I found this while testing the interface.

**Comment by Betree** [comment]
I vote in favor of replacing the existing pledge. In the API, when creating a pledge, we should check if another one exists for this user and if that's the case we should update it.

**Comment by Betree** [comment]
[We are removing pledges](https://github.com/opencollective/opencollective/issues/6590). We were not happy with how it worked and the usage was not significant enough to justify the maintenance costs. If you'd like to contribute to the discussion about a possible revival of pledges, you can do so at https://github.com/opencollective/opencollective/discussions/6027.
