### ISSUE TITLE
query selector error when refreshing paypal key

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#332]
Just to make sure we know that it still happening and might affect other hosts.

**Comment by asood123** [comment]
What's the error?

**Comment by piamancini** [comment]
It still adds a string =#?9... (can't remember exactly) to the URL after refreshing and gives an error. To fix it I just delete that string from the URL and refresh. We saw it many times together. It's just a reminder that it still going on and might happen to other hosts.
