### ISSUE TITLE
Allow users to modify or withdraw a one-time pledge to a pledged collective

### ISSUE THREAD

**Issue by fred-wang** [opencollective/opencollective#3320]
## User story 
If one pledges one-time to an open collective and then later decides to change the amount or withdraw it, it's not possible until they actually receive the email for actual payment. Worse, someone could try to pledge twice with the hope they could modify the amount, leading to bug #3319 

## Best solution for this problem
Add a https://opencollective.com/name/one-time-pledges preference interface listing current one-time pleges and allowing to modify them.

## MVP
Clicking Pledge a second time would re-use the existing amount and allow to modifying it.

## Metrics 
N/A

## Documentation 
N/A

**Comment by Betree** [comment]
[We are removing pledges](https://github.com/opencollective/opencollective/issues/6590). We were not happy with how it worked and the usage was not significant enough to justify the maintenance costs. If you'd like to contribute to the discussion about a possible revival of pledges, you can do so at https://github.com/opencollective/opencollective/discussions/6027.
