### ISSUE TITLE
Can’t submit an invoice sent by a vendor

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#3323]
When submitting an invoice, the field “Who is being paid for this expense” only shows me, the different organizations I’m part of, but it doesn’t let me create a new organization for the invoice that I received.

We got a €40 invoice from the lawyer and we cannot add it for them in the collective (and it’s very cumbersome to ask them to do it themselves). I should be able to submit the expense on their behalf.

**Comment by alanna** [comment]
We can't pay to third parties without their involvement. I have suggested many times we create a feature for this (called "submit on behalf" for lack of a better name), which should allow the submitter to fill out all the info and just send the actual payee an invitation link to confirm.

See #3278

**Comment by xdamman** [comment]
We should be able to. 
Look, here I have to submit an invoice from Deliveroo and Open Collective thinks that I'm the one that will receive the money. That's not ok.

Any accounting software would let you add a vendor without their consent.

That said, I agree that it would be a good idea to require an email address when adding a vendor that could confirm the creation of an open collective account. But this shouldn't block the ability for a collective to record a vendor.

<img width="766" alt="Screen Shot 2020-07-13 at 11 44 06 AM" src="https://user-images.githubusercontent.com/74358/87290505-5aa93f80-c4fe-11ea-9c09-92c25c062165.png">

**Comment by piamancini** [comment]
> Any accounting software would let you add a vendor without their consent.

This is not true - we constantly add any of our hosts as vendors to multiple companies / foundations and we always need to validate email. I don't think this is even legal under GDPR regulations. 

This is a feature we also want to see done - but we need to do it properly.

**Comment by alanna** [comment]
@xdamman the workaround for now is you can create an organization profile for the vendor yourself and select it when you submit the expense under "pay to". You can either add someone from there as the admin and remove yourself, or just manage that profile for them. Then at least our records show the income going to the correct payee, and if we have to get a tax form or whatever we will contact you as the admin of that profile and if you can't represent the vendor to fill out the tax form or whatever, then you'd need to get them involved. But you can see there are obvious drawbacks to having random people managing profile for companies they don't actually represent.

**Comment by alanna** [comment]
This will be solved by the `invite expense` feature which is being built.

**Comment by kewitz** [comment]
Since it refactors multiple crucial components in the expense flow, I shipped this under a feature flag enabled on a collective basis for testing.
@xdamman, I enabled it for Brussels Together, let me know if you want to test this in any other collective.

**Comment by kewitz** [comment]
Implemented and enabled by default.
