### ISSUE TITLE
Better validation errors for settings

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3325]
Currently if you try to change your URL slug to one that's already taken, you just get this:

<img width="470" alt="Screen Shot 2020-07-11 at 1 10 28 PM" src="https://user-images.githubusercontent.com/5498878/87213276-ecd30b80-c377-11ea-916f-28e9e97d611e.png">

Which is not very informative, as there are heaps of fields on that page that could be causing the issue.

1. Error should appear at the part of the page with the problem, plus a message next to the save button
2. The error should state what the actual problem is and how to fix it

**Comment by Betree** [comment]
It seems that we now have a clearer error message for this one

![image](https://user-images.githubusercontent.com/1556356/163988146-fbef0622-a4f5-4327-846f-8ff1089c99f5.png)
