### ISSUE TITLE
No sign-up email received

### ISSUE THREAD

**Issue by colemickens** [opencollective/opencollective#3327]
**Describe the bug**

It's probably been 10 minutes. I'm using my standard Gmail address. The email is not in my Spam either.

**To Reproduce**
1. Try to sign up.

**Expected behavior**

You get a "finish" or confirm registration email.

**Comment by znarf** [comment]
Please contact [support](support@opencollective.com) with your email address.

**Comment by colemickens** [comment]
It's entirely possible. Email sent to support. Thanks!

**Comment by colemickens** [comment]
Well, this was my mistake entirely.
