### ISSUE TITLE
Revamp the leaderboard

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3329]
We have been publishing a leaderboard in our monthly newsletter for a while now, and I think the time has come to either revamp that process, or scrap it.

I want to know if having a leaderboard is a priority. If it's not a priority, let's stop publishing it in the newsletter.

If we want a leaderboard, we should make something that automatically updates on a webpage and helps fulfil transparency and marketing goals, and most of all, make sure the data is accurate (it's not right now). Then we can base the newsletter stats off that.

* Accurate data for the categories
  * Top financial contributors
  * Top new Collectives by $ and number of contributors
  * Other ideas? Separate out events?
* Handle different currencies (1000 MXN is not more than 999 USD)

I think @Betree identified some other ways the current script is inaccurate.

**Comment by Betree** [comment]
The script that does the monthly data export is also exporting some other information, like the transactions. Moving that to a webpage would not really simplify things for engineering, the real simplification for us would be to have the data automatically exported to Drive, without developer intervention.

**Comment by alanna** [comment]
True. Ok so true MVP would be a manual script with accurate data. MVP+ would be that script running automatically and uploading to drive. The real best feature would be an awesome public visual leaderboard. I'm ok with any of those three, but we can't continue publishing inaccurate data. @Betree can you comment about the inaccuracies you discovered?

**Comment by Betree** [comment]
@alanna I just pushed a fix and described the underlying issue for the inaccurate data in https://github.com/opencollective/opencollective/issues/3269#issuecomment-661697680. I've also created https://github.com/opencollective/opencollective/issues/3352 to automatize the script, we'll eventually be able to add a bounty on it.

**Comment by Betree** [comment]
Is there any actionable left for this issue?
