### ISSUE TITLE
Embeddable Donate Button

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#333]
In the same way that people can add a PayPal button on their site, we should make it easy for people to add a donate button.

Can you come up with some designs?

Related to: 
https://github.com/OpenCollective/OpenCollective/issues/96
https://github.com/OpenCollective/OpenCollective/issues/238

**Comment by gusaus** [comment]
There are couple widget examples in this related issue - 
https://github.com/OpenCollective/opencollective-api/issues/769#issuecomment-281803583
https://github.com/OpenCollective/opencollective-api/issues/769#issuecomment-288586713

**Comment by xdamman** [comment]
@cuiki popping this back up

**Comment by cuiki** [comment]
Hi @xdamman, here are a few concepts. Two of them bring the OC logo , another is just written in text. let me know your feedback.

Zeplin link: https://zpl.io/ZzwlLf

![symbols - donate embeddable button](https://cloud.githubusercontent.com/assets/981188/24668881/e890dcde-192d-11e7-816e-9f99b8256105.jpg)

**Comment by xdamman** [comment]
I like the two top left. I'd maybe say "donate to our open collective" rather than "with". 
Can you do the different states (hover, pressed)?

**Comment by cuiki** [comment]
Sure thing. File updated in Zeplin. 👍
