### ISSUE TITLE
[Project] Ability for Fiscal Hosts to "un-host" Collectives 

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3330]
## User story 
As a fiscal host admin, I want to be able to unhost Collectives under my host, even if the Collective admin is not available or responsive.

## Best solution for this problem
Give fiscal host admins access to unhost a Collective, similar to the root action we have currently

## Specs
See https://github.com/opencollective/opencollective/issues/3330#issuecomment-779706601

**Comment by Betree** [comment]
In our current model being a fiscal host does not give you full admin permissions on the collective, it only gives you the admin permissions on their finances (expenses, orders). I see a risk of host admin deleting a collective by mistake or after they get into an argument, and it seems to me that this permission is too broad for their role.

As the action to "Un-host" a collective is already planned, wouldn't that solve it?

**Comment by alanna** [comment]
Yes an un-host option would help in this case. That probably makes more sense.

So if a Collective admin is MIA and a host has to stop hosting it, the host admin can submit, approve, and pay an expense to zero the balance, and then un-host? If so that would be ok.

Does the host admin also have access to the 'zero balance' button on their Collective? If not, we won't be able to complete the above due to the lack of a '100% balance' option on expenses. There's likely to be a small amount left in the balance due to variable fees, preventing un-hosting.

**Comment by Betree** [comment]
> Does the host admin also have access to the 'zero balance' button on their Collective?

Not at the moment, we can look toward enabling that in the new dashboard.

**Comment by alanna** [comment]
Bump! We've had a couple hosts shut down recently and admins are stuck and can't deactivate when they can't unhost their Collectives. In these cases, the Collectives were inactive and their admins nonresponsive. 

A Host really needs this ability because they need to be in control of the Collectives they allow. For example, if the NZ charity host finds out a Collective was supporting non-charitable activities, we'd have to boot them out immediately or risk losing the whole entity's charity status. 

Above we talked about access to "zero balance" since a Collective needs to be at zero to change host. But we have a workaround where the host admin can submit and pay an expense to achieve this, so the most important thing we need is an "unhost" option for after the Collective is at zero balance.

I suggest we make the "unhost" action a button or option on the Collective card on the Hosted Collectives tab of the Host Dashboard.

![Screen Shot 2021-02-15 at 11 17 01 AM](https://user-images.githubusercontent.com/5498878/107890751-6d499280-6f7f-11eb-989e-316771d19f34.png)

**Comment by Betree** [comment]
We have a design for that in https://www.figma.com/file/5pclePpILM2ja3aYsHuex7/%5BOC.com%5D-03-Admin-Panels-%2F-%E2%97%89?node-id=9%3A37827:

![image](https://user-images.githubusercontent.com/1556356/108043100-f248b080-7040-11eb-995a-db3bb3ec9b81.png)

![image](https://user-images.githubusercontent.com/1556356/108043119-faa0eb80-7040-11eb-9d1a-816bfe7670e6.png)

**Comment by Betree** [comment]
# Specs

## API

- [ ] In `server/graphql/v2/mutation/HostApplicationMutations.ts`, create a `removeHost` mutation:
  - [ ] Args: `account`, `message` (optional)
  - [ ] Can only be used by host admins or collective admins
  - [ ] Calls `changeHost` with `newHostCollectiveId` = null
  - [ ] If `changeHost` succeed, send an email. Include the custom message if there's one
 
## Frontend

- [ ] Implement the design proposal from https://github.com/opencollective/opencollective/issues/3330#issuecomment-779701300
- [ ] Use the `removeHost` mutation previously created
- [ ] Add E2E test in `test/cypress/integration/29-host.dashboard.test.js`

**Comment by alanna** [comment]
It's for legal/compliance reasons, practical reasons, and customer service reasons. A Collective being live on a Host means the host is legally liable for their activities and money will flow into their bank account for that project and they can't stop it. This is not a tenable situation for a Host as a legal entity. If a Collective violates their policies, what can they do? Also we are often trying to help people change Hosts or close down their Collective and the users are confused or nonresponsive so we can't help them.

**Comment by alanna** [comment]
Bump. This came up again today in support. A Host admin is trying to shut down their Host but they are stuck because there's an abandoned Collective that they are not admin of. This prevents a Host from being archived or deactivated, and the Host admin can't do anything about it.

**Comment by alanna** [comment]
This issue is becoming critical, especially in light of #4928 

A Host right now needs to remove a Collective for violating their ethics policies, but there is currently *no way* for them to do it. I really think this is a key compliance/legal/policy risk and it's not fair to our Hosts to force them to keep Collectives hosted that they want to remove.

**Comment by BenJam** [comment]
+1 ing as we manually unhost another collective today after a request...

**Comment by petervaldaz** [comment]
Hi
🪴🪴❤️🪴🪴

**Comment by Betree** [comment]
I feel a lot of tension around this feature. I'll be pushing a quick hack to add it to the root dashboard so that the rest of the support team can take action when it needs to be done.

**Comment by Betree** [comment]
- [ ] @opencollective/design we need a link towards the latest design for this, the one previously shared doesn't work anymore
- [ ] @hdiniz to synchronize with @opencollective/design this week to make sure they integrate the latest constraints

**Questions for Support/Ops**
- @alanna do we want to keep the root action? Will we need to keep the ability for support to unhost accounts for anyone? Our current assumption is that it won't be needed anymore.

# Specs

## API

- [ ] Review the current `removeHost(null)` call (unhost) to make sure all related data is being taking care of
  - [ ] Recurring contributions should be cancelled (same as `archiveCollective`)
- [ ] In `server/graphql/v2/mutation/HostApplicationMutations.ts`, update `removeHost` mutation to allow any host admin to unhost an account under their fiscal host.
- [ ] Implement a new `customMessage` argument on the mutation
- [ ] Implement a new activity
- [ ] Implement an email notification for collective admins
- [ ] Add tests for this new mutation in `test/server/graphql/v2/mutation/HostApplicationMutations.test.ts`
  - [ ] Needs to be authenticated
  - [ ] Needs to be host admin or collective admin
  - [ ] Collective must have an empty balance
  - [ ] Returns an error if collective has no host
  - [ ] Sends an email with the custom message
 
## Frontend

- [ ] Implement the design proposal
- [ ] Make sure there's a clear path to empty the balance
- [ ] Use the `removeHost` mutation previously created
- [ ] Add E2E test in `test/cypress/integration/29-host.dashboard.test.js`

**Comment by alanna** [comment]
Yes I think we should keep the root action.

**Comment by Memo-Es** [comment]
@alanna, to zero out the Collective, where does the host send the money to?

**Comment by alanna** [comment]
I don't think zeroing needs to be in scope of this issue. Hosts can already zero as needed by processing an expense.

**Comment by Memo-Es** [comment]
### Design update

| Freeze Collective | Un-host Collective
|------------|---------------
| ![Hosted Collectives](https://user-images.githubusercontent.com/49539954/191166787-ed2ba43b-32ba-442d-9682-58cdbc4b4bbe.png) | ![Hosted Collectives](https://user-images.githubusercontent.com/49539954/191166787-ed2ba43b-32ba-442d-9682-58cdbc4b4bbe.png)
| ![Freeze Collective](https://user-images.githubusercontent.com/49539954/191166508-d64d8083-1710-4c3b-9735-65b12c7b1335.png) | ![Action needed](https://user-images.githubusercontent.com/49539954/191166570-4ddb634e-cad6-42f6-b557-eb290a652667.png)
|      | ![Empty](https://user-images.githubusercontent.com/49539954/191166994-cc36d025-6366-49b6-936a-29c97d7baeb2.png)
| ![Hosted Collectives-1](https://user-images.githubusercontent.com/49539954/191166847-ff18b131-02bf-48d3-aba3-153905edf0b5.png) |  
| ![Collective Page](https://user-images.githubusercontent.com/49539954/191166907-77b57fec-8d95-48c1-a879-4ca440d16d57.png)

@alanna can you help me review it and write a better copy?

cc @hdiniz

**Comment by znarf** [comment]
> I don't think zeroing needs to be in scope of this issue. Hosts can already zero as needed by processing an expense.

I think this would streamline the experience by a lot, instead of having to surface the warning about the balance, expect the host to switch context, create an expense, figure the right recipient, approve it, pay it, then come back to the un-host button.

What do we gain by not doing it?

**Comment by Memo-Es** [comment]
@znarf, what's the most common case to zero out a Collective's balance with an expense? Who is this _right recipient_?

**Comment by znarf** [comment]
> @znarf, what's the most common case to zero out a Collective's balance with an expense? Who is this right recipient?

I'm not sure? Switching Host? Archiving the Collective? The balance can go the the Host as recipient or an admin of the Collective.

**Comment by Memo-Es** [comment]
A couple of questions:

 - What's the case for the host to keep the Collective's money?
 - It sounds like hosts will use the invite expense feature. Does it make sense to add an option to set "Collective admins" as a recipient and let the Collective admin team choose what admin gets the money? (I see a risk of going back and forth with admins to decide who ends up receiving the $)
 - Do we have an option to send the funds to another Collective with a different host? (What if the original admins want to transfer the funds to another Collective instead of putting them into any of the admins' accounts?)

These questions also tell me this project needs an extra round of design definition to set the right expectation in terms of the timeline. This current design iteration should be discussed and get some team approval before moving forward.

cc @alanna @znarf @hdiniz

**Comment by alanna** [comment]
I do not think zeroing should be in scope of this feature because the scenarios are too diverse to design for. It completely depends on the legal terms of the Host and the specific situation of the Collective. See the termination sections of the terms of fiscal hosting for various hosts to see examples. 

It's not the case that Hosts will always be moving the funds to their own budgets. They might be moving funds to another Collective or an outside payee via an expense. It can actually cause a lot of problems to move the balance to the Host without careful consideration. If the Host wants to move the balance to its own budget, they can do so easily via an Expense already.

If we want to give Hosts access to the 'zero balance' function that Collective admins have in their settings currently, which sends the money to the host, that is a good idea, but should be a separate issue and separate button in the interface. If a Host admin tries to unhost a Collective and gets an error saying "balance must be at zero to unhost" then that's a good thing, because it tells the admin exactly what they need to do and they can pause and consider the best way to achieve that.

@Memo-Es the answers to your questions depend on the legal terms of the specific Host.

This project does *not* need another round of design, and all these questions are overcomplicating it. All needed features are already in place for the Host admin or Collective admin to zero a balance. We just need Host admins to have access to an 'unhost' button, which only works when the balance is zero.

**Comment by alanna** [comment]
OK, copy feedback:

I think you can remove the repeated word 'Collective' from the little menu and just say contact, freeze, unhost.

For the modal popup

> Are you sure you want to un-host [Collective name]? 

(include the name so they are sure they have selected the right one)

> [Fiscal host name] will no longer be the Fiscal Host for this Collective.

Only show the warning about needing zero balance if it does not have zero balance and grey the button (as it has in the design already)

> The Collective's balance must be zero to un-host, including its Events or Projects. There is a remaining balance of [$x]. You can pay out these funds by processing expenses.

**Comment by alanna** [comment]
> remaining balance of [$x]

This number should include Events, Projects, and the parent balances together.

**Comment by znarf** [comment]
For consistency in project management, would be great to create a project board for the project. See https://github.com/opencollective/opencollective/projects/77 and https://github.com/opencollective/opencollective/projects/78 for example with other projects.

**Comment by alanna** [comment]
@shannondwray for docs

**Comment by Betree** [comment]
Re-opening as it's not yet released publicly. We want to make sure https://github.com/opencollective/opencollective/issues/5993 is properly done before doing so.

**Comment by BenJam** [comment]
- reviewing related PRs re cancelling recurring contributions and virtual cards

**Comment by hdiniz** [comment]
Enabling the unhost action in production with this PR: https://github.com/opencollective/opencollective-frontend/pull/8260
When the collective still has balance, we direct the host admin to this [doc](https://docs.opencollective.com/help/expenses-and-getting-paid/submitting-expenses) to submit an expense and clear the balance

We are also updating the unhost email notification copy to indicate that non transferable recurring contributions and virtual card will be canceled: https://github.com/opencollective/opencollective-api/pull/8031

**Comment by alanna** [comment]
Reposting from slack: the user who is unhosting a Collective is the host admin, who does not have access to a Collective’s “zero balance” button. This is why the instructions specify processing an expense to empty the balance, so the link should be to docs about submitting a normal expense, not using the zero balance button.

**Comment by hdiniz** [comment]
@alanna thanks! we updated the link to the [expenses docs.](https://docs.opencollective.com/help/expenses-and-getting-paid/submitting-expenses)

@shannondwray we are enabling this feature in production, do you need support with the documentation?

**Comment by BenJam** [comment]
I tried to use the feature but it's not clear how I do so. I couldn't find it from opensource's hosted collectives as indicated. In general it would be good to post the demo here once we're 'done' and ready to release.

Could someone drop that here and we'll get documentation and release done?

**Comment by hdiniz** [comment]
Hi @BenJam, I recorded a loom for this one: [Un-hosting Collectives Demo](https://www.loom.com/share/6e9fb5d618ef4229a797cb8eb5601253)

**Comment by shannondwray** [comment]
- Docs issue - #6136 
- Release Issue - #6135

**Comment by Betree** [comment]
Closing as it's released & documented
