### ISSUE TITLE
Rename 'platformFees' on the API & make everything consistent

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3331]
We should discuss what we want to call 'platform fees'/'fees on top' moving forward, and then do some work to make this consistent across the API and frontend.

![Screenshot 2020-07-14 at 17 01 23](https://user-images.githubusercontent.com/37520401/87448407-b73a5680-c5f3-11ea-8463-63b1670ad296.png)

[Discussion here](https://github.com/opencollective/opencollective-api/pull/4207#discussion_r453708446)

**Comment by sbinlondon** [comment]
Adding this to the contribution flow project since it relates to fees on top involved in that

**Comment by sbinlondon** [comment]
@znarf @kewitz To continue discussion here, Iike Leo's suggestion of `platformContributionAmount`. It make it clear it's a 1) contribution from the user and 2) relates to supporting the platform, us, not the Collective. But maybe you still don't like the use of 'platform' here Francois? What do you think?

**Comment by znarf** [comment]
My problem was more with `fee`. `platformContributionAmount` could work for me.

**Comment by sbinlondon** [comment]
Do we still need to do work on this?

For example in the API, there's `platformFee` on the `Transaction` interface, do we also want to deprecate that field and update it to `platformContributionAmount`?

**Comment by znarf** [comment]
No, there is nothing wrong with `platformFee` if it's the classic platform fee. The problem was calling a voluntary contribution a "fee".

I addressed that in https://github.com/opencollective/opencollective-api/pull/4310

**Comment by sbinlondon** [comment]
In that case I'll close this issue
