### ISSUE TITLE
Invoice's bills keep uploading forever

### ISSUE THREAD

**Issue by fabianmendes** [opencollective/opencollective#3332]
I'm adding an invoice and can't upload the billing. It keeps uploading forever.

**Comment by znarf** [comment]
We're not aware of any problem in this area. Could you share:

- The environment (Operating System, Browser Version)
- A screenshot
- Look at the browser console and tell us if you see any error?

**Comment by fabianmendes** [comment]
Sorry, I've forgotten to add all that!

Env: Google CHROME Version 80.0.3987.132 (Build oficial) (64 bits). Linux

Screenshots:
![Captura de pantalla de 2020-07-24 11-20-50](https://user-images.githubusercontent.com/31230743/88410040-d1b6c180-cda3-11ea-9406-6d7957f624d3.png)Versión 80.0.3987.132 (Build oficial) (64 bits)
(I've tried again, but it still happening)
![Captura de pantalla de 2020-07-24 11-50-47](https://user-images.githubusercontent.com/31230743/88410153-f9a62500-cda3-11ea-8c3b-0c823c0e9be5.png)

**Comment by fabianmendes** [comment]
Hello. This still happening.
![Screenshot-20200801014311-1385x873](https://user-images.githubusercontent.com/31230743/89095126-b1d16000-d398-11ea-9d5f-c3a7c899168b.png)

**Comment by znarf** [comment]
@fabianmendes Sorry. There is no known problem with this component and we need to understand what is specific to your case. I have a few questions:

1)What are the characteristics of the file you're trying to upload? Type? Size?

2) Can you test with another file? For example a small image?

3) Can you try with Chrome extensions disabled? Can you try with Firefox?

**Comment by fabianmendes** [comment]
Hi, thank you for your reply! I've just tried from a smartphone and it upload as it should. I think it seems to be the Chrome PC versión (which is unupdated), anyways, I'll try uploading an imagen file and Share with you whci type of files I was getting the issue (they were PDF files, not big MB).

**Comment by fabianmendes** [comment]
Ok, @znarf I could upload them via mobile but from my PC. The images uploaded but not any PDF file from my PC.

**Comment by Betree** [comment]
Given the logs shared in the screenshot, it comes from this line: https://github.com/opencollective/opencollective-frontend/blob/5a5635c2410f94c5c9298890acbd9fc28a5224d3/lib/api.js#L88. Another problem here is that we're not displaying the error.

I'll try to look at it this week.

**Comment by znarf** [comment]
@fabianmendes 3) Have you tried with Chrome extensions disabled (incognito mode)? Can you try with Firefox?

**Comment by fabianmendes** [comment]
> @fabianmendes 3) Have you tried with Chrome extensions disabled (incognito mode)? Can you try with Firefox?

Yes, or course I did. No, I can't for now sorry! Anyways, I'll ask to a friend to try it for me.

**Comment by Betree** [comment]
We've pushed numerous enhancements on file upload, including better error handling that I think should prevent this issue. Feel free to re-open if it ever happens again.
