### ISSUE TITLE
Contribution flow revamp: create new/update components

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3333]
Working from the Contribution Flow components page, check that we either:

* Have the component already as it appears
* Create a new component to match the look
* Can just make it inline (i.e. buttons and headers, don't need a special component)

### Step 1 contribution
- [x] Contribution header (guest/connected account)
- [x] Stepped progress
- [x] 'We protect your transaction' box
- [x] FAQs
- [x] New contribution button set
- [x] "Support OC"/fees on top widget
- [x] "Support OC" drop-down menu
- [x] Contribution details component (amount button set + frequency button set + support OC widget)

### Step 2 profiles/guest info
- [x] Contribution profiles
- [ ] ~Contribution profile selector~
- [x] "Contribute as a guest" widget (form)

### Step 3 payment
- [x] Payment method selector

### Success page
- [x] CTA cluster + CTAs ('Join OC', 'Read our stories', 'Subscribe')
- [x] Contribution success widget (Styled contribution card)
- [x] Comment box
- [x] Share buttons

**Comment by Betree** [comment]
Seems all done
