### ISSUE TITLE
Contribution flow revamp: upgrade to GraphQL v2

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3335]
Details TBA but queries/mutations are:

- [x] ~CollectiveDataQuery~ AccountQuery
- [x] ~CollectiveWithTierDataQuery~ AccountWithTierQuery
- [ ] SubmitOrderFragment
- [x] addCreateOrderMutation
- [ ] addConfirmOrderMutation

**Comment by sbinlondon** [comment]
@Betree do the remaining two GraphQL todos make sense in the context of the new contribution flow or do we not need them? (Names just copied from the old flow)

**Comment by Betree** [comment]
@sbinlondon `SubmitOrderFragment` would be nice to make sure `createOrder` and success page retrieve the same data. I've added a note for that in https://github.com/opencollective/opencollective/projects.

`addConfirmOrderMutation` will be required to implement 3D secure properly, but an issue for the endpoint itself is not required, we should rather have an issue for the feature as a whole. I'll do that now so you can close this one if you want.
