### ISSUE TITLE
Contribution flow revamp: step 1 contribution details

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3336]
For step 1, all 5 states (guest contribution > $250, guest contribution < $250, guest contribution > $5000, recurring contribution, and user contribution) are the same *except* that when logged in rather than being a guest, the *contribution flow header* will display differently.

### Screenshot of step 1
![Screenshot 2020-07-15 at 12 43 28](https://user-images.githubusercontent.com/37520401/87541248-dc34d500-c698-11ea-8bd2-61ea752b2571.png)

### Screenshot of guest header/connected header
![Screenshot 2020-07-15 at 12 43 36](https://user-images.githubusercontent.com/37520401/87541272-e656d380-c698-11ea-87f5-59959cd0f669.png)
![Screenshot 2020-07-15 at 12 43 52](https://user-images.githubusercontent.com/37520401/87541276-e6ef6a00-c698-11ea-8204-b7e3efec2568.png)

### To do
- [x] Lay out skeleton of the new contribution flow page
- [x] check which components need to be built/updated
- [x] Contribution header (guest/logged in)
- [x] 'We protect your transaction' box
- [x] FAQ text
- [x] Contribution details box (amount button set, freq button set, fees on top box)
- [x] Buttons (previous goes to Collective page, next goes to Step 2)

### Questions

* The 'connected account' header says 'You have contributed $x so far!' What if the person has not yet contributed to the Collective? Would the header then look the same as the guest header? @Memo-Es

**Comment by Memo-Es** [comment]
I think the 'You have contributed $x so far!' counter should start as of the first contribution, so before if you're a registered user but have not contributed yet to a given Collective you are in fact 'Joining' the rest of the contributors @sbinlondon

**Comment by Memo-Es** [comment]
Adding these behaviors for the 'Other amount' selection:

* Selecting 'other' amount
![ezgif com-optimize](https://user-images.githubusercontent.com/49539954/87632514-2cdf1900-c6ff-11ea-9bdf-6cc7a9369a4e.gif)

* Selecting 'invalid' amount
![ezgif com-optimize (1)](https://user-images.githubusercontent.com/49539954/87633080-564c7480-c700-11ea-97f9-82aad747bd26.gif)


Design is in the [production file](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=4620%3A1788)

**Comment by sbinlondon** [comment]
@Memo-Es @piamancini Do we have the full FAQ text for this flow?

**Comment by Betree** [comment]
I imported some of them from the current flow, but the `Is my contribution secure` one is still Lorem Ipsum. We should first write the proper documentation page/section on https://docs.opencollective.com then resume it there.

To defend this claim on the docs page, we can say that:
- Connection is protected by HTTPs
- We have a security bounty policy and pay rewards
- We are working on a security audit (should be updated once it's done)
- We use Stripe (which itself use state of the art policies) and don't store any credit card info by ourselves. We should link to https://stripe.com/docs/security/stripe (that page is actually a good example, we should take some inspiration from it).

## Current FAQ:
![image](https://user-images.githubusercontent.com/1556356/88939216-8d855e80-d286-11ea-90b9-3c1a4c2184d1.png)

**Comment by Betree** [comment]
Done in https://github.com/opencollective/opencollective-frontend/pull/4707
