### ISSUE TITLE
Contribution flow revamp: step 2 user details

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3337]
There are 4 states:

## Guest contribution > $250, guest contribution < $250

Optional name, required email, and optional newsletter

![Screenshot 2020-07-15 at 15 21 40](https://user-images.githubusercontent.com/37520401/87556757-eeba0900-c6ae-11ea-9034-29a5b3b664a3.png)
![Screenshot 2020-07-15 at 16 03 53](https://user-images.githubusercontent.com/37520401/87561609-d4832980-c6b4-11ea-81df-039b0104cded.png)

## Guest contribution > $5000

All form fields required 

![Screenshot 2020-07-15 at 15 22 16](https://user-images.githubusercontent.com/37520401/87556800-fda0bb80-c6ae-11ea-834b-507d741c615e.png)
![Screenshot 2020-07-15 at 16 05 22](https://user-images.githubusercontent.com/37520401/87561760-03999b00-c6b5-11ea-8e51-f997f8aef267.png)

## Recurring contribution if logged out - sign up prompt

Name and email both required this time, then you choose whether to contribute named or incognito, and then a login link is sent and we are broken out of the flow. Question - after the third 'thank you' screen, do we redirect somewhere? Do we stay on that page and expect the user to close it or navigate away? @Memo-Es @znarf?

![Screenshot 2020-07-15 at 15 22 35](https://user-images.githubusercontent.com/37520401/87556866-14471280-c6af-11ea-9fac-0fee5b4310e0.png)
![Screenshot 2020-07-15 at 16 06 06](https://user-images.githubusercontent.com/37520401/87561831-1d3ae280-c6b5-11ea-9974-6171a4c376c9.png)
![Screenshot 2020-07-15 at 16 07 03](https://user-images.githubusercontent.com/37520401/87561925-43f91900-c6b5-11ea-8c11-bb89b84e0c9c.png)

## User contribution logged in (single or recurring)

Single step - choose your profile or create a new org, just like the current profile selector

![Screenshot 2020-07-15 at 15 23 25](https://user-images.githubusercontent.com/37520401/87556906-26c14c00-c6af-11ea-8031-4451673e3a3c.png)

**Comment by Memo-Es** [comment]
> Question - after the third 'thank you' screen, do we redirect somewhere? Do we stay on that page and expect the user to close it or navigate away?

* Why third thank you screen? Where are the other two?
* I thought to send the confirmation email when you're seeing the screen with the illustration. When the users go to their email and click on the link it should redirect them directly to the next step (Choose your payment details) 

@sbinlondon

**Comment by sbinlondon** [comment]
>     * I thought to send the confirmation email when you're seeing the screen with the illustration. When the users go to their email and click on the link it should redirect them directly to the next step (Choose your payment details)

Yep that's how I understood it - so just to confirm, after this flow:


When we reach the thank you screen, the user then must leave our site, open their email, and click the link which brings them back to the payment step.

What I'm asking is what happens to the tab they have open with the 'thank you' screen? Do we just expect them to close it? It doesn't do anything else?

**Comment by Memo-Es** [comment]
Yeah. I don't know if it's possible to redirect them to the next screen using that same tab or it could be like the zoom screen when you connect to a meeting and you have to close that tab later.

**Comment by sbinlondon** [comment]
Have made an empty component and laid out some of the conditional logic for the different states (guest vs logged in, etc)

**Comment by alanna** [comment]
Let's be careful with how we use language here. It's 'financial contribution' not 'donation' and 'updates' not 'newsletter'. Phrases like 'donation receipt' have very specific meanings in some countries (e.g. tax deductibility) and we should not apply them globally. We need to use as neutral language as we can, such as just referring to 'receipt'. 

It's also not clear to me who "we" is on many of these screens. Fiscal host, or platform? If it's fiscal host, then the regulations about things like the threshold for amounts over which we need to have a physical address will vary per country. Also saying "we" is a bit confusing when it comes to privacy stuff and which entity is actually holding this data.

**Comment by sbinlondon** [comment]
Some changes have been made

* sign up for ${COLLECTIVE} newsletter removed from guest flow
* we don't have the 'profile chooser' for guest flow anymore

Largely these steps are done though

### still todo:

- [ ] for guest recurring contribution, finish writing the email functionality...
- [ ] ....and make the interim screen

![Screenshot 2020-08-14 at 12 06 21](https://user-images.githubusercontent.com/37520401/90243330-9f3e3880-de26-11ea-9868-3a4e4da5e6bc.png)

**Comment by Betree** [comment]
Just a note that guests contributions will be disabled for the initial release as the API is not yet ready for that.

**Comment by sbinlondon** [comment]
I think it would be good to make separate issues for the logged out stuff then so we can go ahead and track/'close' these issues for the intial release
