### ISSUE TITLE
Contribution flow revamp: step 3 payment

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3338]
Effectively the same for all 5 states, except that if the user is logged in, we'll see a list of their account's payment methods

![Screenshot 2020-07-15 at 16 20 14](https://user-images.githubusercontent.com/37520401/87563451-2331c300-c6b7-11ea-9134-848964e1ba55.png)

There is already a GraphQL v2 mutation for adding a payment method ✅

### Questions

This step raises an engineering design question for me. If the user starts as a guest and then has to sign up for an account to make a recurring contribution, we ask them to open their email to continue the contribution flow. When they click it, they'll be taken to this payment step.

To me that implies that we'll have to include all the info about the contribution (collective we're contributing to, amount, fees on top amount if relevant, frequency, etc) in the URL as query strings, and derive all our different states for the contribution flow component from this. Does that sound like an effective solution to you? 👍 @znarf and would especially love @Betree's opinion since we're working on this together

**Comment by sbinlondon** [comment]
Have made an empty component and laid out some of the conditional logic for the different states (guest vs logged in, etc)

**Comment by Betree** [comment]
> To me that implies that we'll have to include all the info about the contribution (collective we're contributing to, amount, fees on top amount if relevant, frequency, etc) in the URL as query strings, and derive all our different states for the contribution flow component from this. Does that sound like an effective solution to you? 

@sbinlondon It does. In fact the current contribution flow already supports that (ie. https://opencollective.com/babel/donate?totalAmount=250000&interval=month). We should try as much as possible to re-use the existing code because it has all these features and because it handles many cases that are not described in the current design, like VAT, events tickets (where you have a notion of quantity/limit), etc.

**Comment by sbinlondon** [comment]
First pass is done.

We should think about if we wanted to still add the inline gift card redeem - I think it could be useful but I am aware we are trying to roll this out with just features from the current contribution flow as MVP.

**Comment by Betree** [comment]
We should close this one and spec an issue for the inline gift card redeem, it's a complex issue that can safely be implemented separately.
