### ISSUE TITLE
Contribution flow revamp: step 4 success/CTAs

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3339]
For this final step we have two 'halves' of the page: success/thank you for the contribution with info about it, and some calls to action. There are 

## Guest contribution (all amounts)

There are all 3 CTAs: join Open Collective, 'read our stories', and subscribe to newsletter. The success/thank you panel shows info about the donation in a styled card.

![Screenshot 2020-07-15 at 17 19 00](https://user-images.githubusercontent.com/37520401/87570250-3b5a1000-c6c0-11ea-9e26-199ff0748d53.png)

## User contribution (logged in, whether they contributed as user or incognito)

Only two CTAs for recurring contributions: 'read our stories' and subscribe to newsletter. Only 1 CTA ('read our stories') for one-time contributions.

### Recurring contribution
Shows info about the contribution, contributed to date, and 'contribution since'
![Screenshot 2020-07-15 at 17 31 43](https://user-images.githubusercontent.com/37520401/87570876-2a5dce80-c6c1-11ea-9d47-e7f04ae819a3.png)

### One-time contribution
Shows info about the contribution and contributed to date
![Screenshot 2020-07-15 at 17 33 10](https://user-images.githubusercontent.com/37520401/87571022-58dba980-c6c1-11ea-96a7-7824f305e953.png)

## Questions

The normal logged in, one-time contribution mockup shows only one CTA ('read our stories'), whereas the recurring contribution mockup shows two CTAs ('read our stories', 'subscribe to our newsletter'). When would we show/not show the subscribe CTA @Memo-Es @znarf? Do we only show 'subscribe to our newsletter' to the newly signed up accounts from the recurring contribution route, since they didn't have a chance to sign up for the OC newsletter during our traditional signup? (see below)

Recurring contribution route
![Screenshot 2020-07-15 at 18 54 08](https://user-images.githubusercontent.com/37520401/87578669-aa3d6600-c6cc-11ea-8c1e-1ce6ae9be398.png)

Open Collective signup
![Screenshot 2020-07-15 at 18 54 35](https://user-images.githubusercontent.com/37520401/87578675-ab6e9300-c6cc-11ea-9750-30b98f3c320d.png)

**Comment by Memo-Es** [comment]
@sbinlondon I think that we should show the subscription CTA only with non-registered users and new users that came out from the recurring contribution flow for the first time

**Comment by sbinlondon** [comment]
Knocked a good chunk of the UI out for this - just waiting on the actual data from the contribution to be hooked up to it.

Additionally @piamancini what's the link for the 'Read Our Stories' CTA?

**Comment by sbinlondon** [comment]
Still to do:

- [ ] comment box for logged in users
- [ ] add email form to 'Subscribe' CTA
- [ ] feed successful order info into the card on the page

**Comment by sbinlondon** [comment]
Closing issue in favour of [this issue for final edits](https://github.com/opencollective/opencollective/issues/3436)
