### ISSUE TITLE
admin can turn off events

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3342]
Related to #3283 

## User story 
As an admin I want to disable events using the `page sections` settings, e.g. make events appear on this list (even if separating it from `contributions` is another issue, it could appear as a subheading under contributions until we fix that).

<img width="756" alt="Screen Shot 2020-07-16 at 11 45 55 AM" src="https://user-images.githubusercontent.com/5498878/87610609-ee2a7c80-c759-11ea-8426-0b1ac0be9c5c.png">

*This is requested by a host admin user whose Collectives are meetups but they need them to post the events on meetup.com instead and need to disable them on Open Collective to avoid confusion.*

**Comment by alanna** [comment]
This is done now, right @Betree ? In the new profile page settings.

**Comment by Betree** [comment]
> This is done now, right @Betree ? In the new profile page settings.

It is indeed, events can now be turned off form the settings: 
![image](https://user-images.githubusercontent.com/1556356/105042941-2a21ff80-5a65-11eb-9f49-aabd2ec4e47c.png)
