### ISSUE TITLE
Regression in Tax Form notice

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3343]
Seems we introduced a regression in https://github.com/opencollective/opencollective-api/pull/4022

> There is a regression in this PR, it seems we're now looking in the floating year (1 year before the current date) instead of looking in the fiscal year (in 2020).

We got a user complaining on support, https://opencollective.com/fody/expenses/21912

**Update**: the query seems flawed and needs to be fixed

**Comment by flickz** [comment]
> it seems we're now looking in the floating year (1 year before the current date) instead of looking in the fiscal year (in 2020).

Considering the current query and to better understand what is expected:
`  AND all_expenses."incurredAt" BETWEEN date_trunc('year', all_expenses."incurredAt") AND (date_trunc('year', all_expenses."incurredAt") + interval '1 year')` 

If an expense was incurred  `July 11, 2020`, the query search for all expenses between `Jan 1st, 2020` - `Jan 1st 2021` similar to what we have in the [model](https://github.com/opencollective/opencollective-api/blob/master/server/models/Collective.js#L2825).

Is this not how it should work 🤔 ? 

cc @Betree

**Comment by znarf** [comment]
@flickz what you describe is right, it's what it should do. However the behavior of the query is different and it's not working that way.

That looks suspicious to me:

`AND all_expenses."incurredAt" BETWEEN date_trunc('year', all_expenses."incurredAt") AND (date_trunc('year', all_expenses."incurredAt") + interval '1 year')`

**Comment by alanna** [comment]
In case it's helpful: 
* the $600 threshold needs to be counted based on calendar year, so it resets on Dec 31.
* we need a new tax form as soon as they hit the $600 threshold after Jan 1.

**Comment by Betree** [comment]
For context: https://opencollective.freshdesk.com/a/tickets/8231
