### ISSUE TITLE
contributors.svg didn't refresh once a day automatically

### ISSUE THREAD

**Issue by panjf2000** [opencollective/opencollective#3354]
Hi,
I am reporting that the contributors.svg hasn't been updated for more than a month.

https://opencollective.com/ants/contributors.svg shows 11 contributors while https://github.com/panjf2000/ants/graphs/contributors shows 12.

https://opencollective.com/gnet/contributors.svg shows 7 contributors while https://github.com/panjf2000/gnet/graphs/contributors shows 11.

**Comment by panjf2000** [comment]
Besides, the sequence of contributors in SVG doesn't match that in the Github contributors graph.

**Comment by znarf** [comment]
I just released [contributors.svg](https://github.com/opencollective/contributors-svg) as a separate Open Source repository. Anyone is welcome to participate.

I also deployed a new version which should normally fix this old issue.

Feel free to open issues and PRs in the new repository!
