### ISSUE TITLE
Host dashboard > Hosted collectives section

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3355]
:art: Design: [Figma](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC.com%5D-Production-Ready-%E2%9C%85?node-id=4741%3A8057)

# MVP

This MVP will include:
- [ ] Display the collectives list
- [ ] Set a custom fee per collective
- [ ] Sort by creation date
- [ ] Filter by fee structure
- [ ] Search bar

# Preview

![image](https://user-images.githubusercontent.com/1556356/88202858-be8fde80-cc49-11ea-9e4a-be3f5aa196df.png)

**Comment by alanna** [comment]
Related: #2821
