### ISSUE TITLE
Numbers in transactions details don't make sense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3358]
This is a transaction for OCNZ:

<img width="1122" alt="Screen Shot 2020-07-23 at 9 08 57 PM" src="https://user-images.githubusercontent.com/5498878/88270120-43055e80-cd29-11ea-8742-232fd7998061.png">

Is there another number that's supposed to come before `+`? If not why is it there?

Shouldn't it say *US* $2,055.42?

It was actually US $2,000.

> = -NZ$3,167.56 (net amount for Open Collective Inc)
Doesn't make sense to me... why is this there?

**Comment by znarf** [comment]
@kewitz is this part of your current work?

**Comment by kewitz** [comment]
@znarf I'll review this in the redesign.
