### ISSUE TITLE
Country name appearing in wrong language on receipt

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3359]
I downloaded a receipt and the country name is not in English?

<img width="854" alt="Screen Shot 2020-07-23 at 9 55 07 PM" src="https://user-images.githubusercontent.com/5498878/88274277-8c58ac80-cd2f-11ea-9097-dc34f9f01302.png">

I believe this info is pulled from the address field in settings, which says "United States" in English.

<img width="937" alt="Screen Shot 2020-07-23 at 9 57 12 PM" src="https://user-images.githubusercontent.com/5498878/88274284-8f539d00-cd2f-11ea-9956-5dd177fddad6.png">

**Comment by Betree** [comment]
Good catch, we introduced a bug with the latest countries internationalization update. Fixing that now
