### ISSUE TITLE
Download receipts doesn't work for hosts with merged budgets

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3360]
This button doesn't do anything on the transactions page of hosts whose budgets have been merged to their host page (Foundation and OCNZ), but it seems to be working for non-merged hosts (Open Collective Inc).

<img width="1235" alt="Screen Shot 2020-07-23 at 10 00 46 PM" src="https://user-images.githubusercontent.com/5498878/88274776-5a941580-cd30-11ea-9ecb-cde5a4289497.png">

**Comment by znarf** [comment]
I'm not sure what is the expectation in this case (except that it's not broken!).

This feature seems to be designed for USER and ORGANIZATION to download their financial contributions receipts (and only that).

I could remove the link for Hosts while we work on something better (this feature is not really solid).

**Comment by znarf** [comment]
https://github.com/opencollective/opencollective-api/pull/4287 to fix the crash.

**Comment by alanna** [comment]
@znarf as a fiscal host admin, I would like to be able to download contribution receipts too. I thought that's what the feature was for. 

Perhaps the needs are better solved another way? 

The times when I want to do this are a) seeing what my receipts look like after adjusting the settings for them like adding extra text (maybe a better preview feature on that settings page would be better), and b) providing support to my Collectives and their contributors who have any problems with receipts.

But neither of those seems super important right now so I think just hiding this link for any users who shouldn't access it would be a good step. It's confusing to have something there that doesn't do anything when you click it.
