### ISSUE TITLE
Bank transfer instructions showing markup

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3368]
The preview of the bank instructions is supposed to take the markup and render it as formatted text, but the preview is showing some of the markup, so the host admin can't really see what it will look like for users very well.

<img width="1206" alt="Screen Shot 2020-07-28 at 4 47 37 PM" src="https://user-images.githubusercontent.com/5498878/88620451-33539480-d0f2-11ea-9ab9-0ac07d9ecc11.png">

This markup is also implying that some HTML is accepted in this box. It only references the variables, so it would be good for the help text here to specify what markup is allowed.

**Comment by znarf** [comment]
Markup is now discouraged. You can check the latest default instructions template, it's now in plaintext.

We should consider stripping all markup from past entries and start actively stripping it if people try to add some.

**Comment by alanna** [comment]
I just manually fixed the instructions for the hosts I manage. It was messy... some just have a text box and others have you fill out a set form. Does it depend on the country?

**Comment by Betree** [comment]
Resolved with https://github.com/opencollective/opencollective/issues/4002
