### ISSUE TITLE
[PROJECT] Collective page navigation redesign

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3369]
## Purpose
Navigation between sections of the Collective page has become more complex with time and now it has some awkward behaviors related to the different sections and features available for admins and users. Resulting in an under-utilization of the platform features.

🗒 Full specs of this project [here](https://docs.google.com/document/d/1TCAi1iPCP36g3GdkwSyM8bQkyBkUF30pSrdJ4QbyZCU/edit?usp=sharing)

## Owner
@Memo-Es 

*Note: Project owner responsibilities include coordinating all the different people that need to contribute to the project, defining specs and goals, communicating project progress, being the point person for decisions, QA, documentation, and a plan for ongoing maintenance. If the project owner can't continue, they need to hand the role over to another person explicitly.*

## Prioritization

- Does this serve our mission?
Yes. It's necessary for users to understand the platform and its features, and develop a natural use through the familiarity of all the capabilities we offer.

- Will this help to make us financially sustainable within a year?
Yes. With a better navigation of the different profiles, we foster a better adoption for new users and a better general experience for existing users, resulting in better use of the money-related features that keep financial resources flowing inside the platform.

- Is it feasible to build and maintain with our team and runway?
Yes, many of these features are already built, we just need to design a better organization for them.

- Can this make us move faster?
Probably yes, less confusion means less attention needed in support tickets and conversations with users in slack, allowing us to focus our energy and resources on moving forward.

- Will this bring us more Collective and financial contributors?
Yes, first because part of this project is to redesign the sharing capabilities of tiers and events, and also because with a better experience is more likely that people recommend the use of Open Collective to their peers.

- Is this already solved elsewhere or is it our unique contribution?
Lots of platforms have these types of issues, using recognizable web patterns is a must for this project.

## Roadmap & Timeframe
* Research: 20 - 24 July
* Design specs and task unpacking: 27 - 31 July
* First wireframes and mockups: 3 - 7 August
* Second round of feedback: 10 - 14 August
* Design of new components and user reach-out: 17 - 21 August
* Production files by: End of August (approx)

## Success metrics
* Support tickets related with subsections and navigation
* Perception of the simplicity from users
* Better adoption of new users

---
**Related issues**
#3261 #3283 #3262 #3245 #2665 

@piamancini @alanna

**Comment by Memo-Es** [comment]
### Design update
---

![Desktop](https://user-images.githubusercontent.com/49539954/95155416-b845d480-0759-11eb-8866-f2314fecec35.png)

See the [design file](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=6564%3A416) in figma 🎨

**Comment by sbinlondon** [comment]
Need some clarifications @znarf @Betree @Memo-Es @piamancini :

This is our current logic for Collective page sections:

```
// Define default sections based on collective type
const DEFAULT_SECTIONS = {
  [CollectiveType.ORGANIZATION]: [
    Sections.CONTRIBUTE,
    Sections.CONTRIBUTIONS,
    Sections.CONTRIBUTORS,
    Sections.UPDATES,
    Sections.CONVERSATIONS,
    Sections.TRANSACTIONS,
    Sections.BUDGET,
    Sections.EVENTS,
    Sections.RECURRING_CONTRIBUTIONS,
    Sections.CONNECT,
    Sections.ABOUT,
  ],
  [CollectiveType.USER]: [
    Sections.CONTRIBUTIONS,
    Sections.TRANSACTIONS,
    Sections.RECURRING_CONTRIBUTIONS,
    Sections.ABOUT,
  ],
  [CollectiveType.COLLECTIVE]: [
    Sections.GOALS,
    Sections.CONTRIBUTE,
    Sections.UPDATES,
    Sections.CONVERSATIONS,
    Sections.BUDGET,
    Sections.EVENTS,
    Sections.CONTRIBUTORS,
    Sections.RECURRING_CONTRIBUTIONS,
    Sections.CONNECT,
    Sections.ABOUT,
  ],
  [CollectiveType.FUND]: [
    Sections.CONTRIBUTE,
    Sections.UPDATES,
    Sections.PROJECTS,
    Sections.BUDGET,
    Sections.CONTRIBUTIONS,
    Sections.CONTRIBUTORS,
    Sections.ABOUT,
  ],
  [CollectiveType.EVENT]: [
    Sections.ABOUT,
    Sections.TICKETS,
    Sections.CONTRIBUTE,
    Sections.PARTICIPANTS,
    Sections.LOCATION,
    Sections.BUDGET,
  ],
  [CollectiveType.PROJECT]: [Sections.ABOUT, Sections.CONTRIBUTE, Sections.BUDGET],
};
```

This project has defined 5 sections to cut down on the clutter: **Budget**, **Contribute**, **Connect**, **About**, and **Events**.

I assume this pertains to `CollectiveType.ORGANIZATION` and `CollectiveType.COLLECTIVE`, while the `CollectiveType.USER` page stays the same. So the new defaults would be:

```
// Define default sections based on collective type
const DEFAULT_SECTIONS = {
  [CollectiveType.ORGANIZATION]: [
    Sections.CONTRIBUTE, (including CONTRIBUTIONS and RECURRING CONTRIBUTIONS)
    Sections.BUDGET, (for orgs just TRANSACTIONS, CONTRIBUTORS aka team)
    Sections.CONNECT, (including UPDATES and CONVERSATIONS)
    Sections.ABOUT,
    // no events section?
  ],
  [CollectiveType.USER]: [
    Sections.CONTRIBUTIONS, (now including RECURRING CONTRIBUTIONS)
    Sections.TRANSACTIONS,
    Sections.ABOUT,
  ],
  [CollectiveType.COLLECTIVE]: [
    Sections.CONTRIBUTE, (including CONTRIBUTIONS and RECURRING CONTRIBUTIONS)
    Sections.EVENTS,
    Sections.BUDGET, (now including GOALS, TRANSACTIONS, EXPENSES, top financial CONTRIBUTORS, and CONTRIBUTORS aka 'Manyverse is all of us')
    Sections.CONNECT, (including UPDATES and CONVERSATIONS)
    Sections.ABOUT,
  ],
  [CollectiveType.EVENT]: [
    Sections.ABOUT, (including LOCATION)
    Sections.CONTRIBUTE, (including TICKETS and CONTRIBUTORS aka PARTICIPANTS)
    Sections.BUDGET,
  ],
  [CollectiveType.PROJECT]: [Sections.ABOUT, Sections.CONTRIBUTE, Sections.BUDGET],
};
```

Does that look correct?

What about `CollectiveType.FUNDS`?

```
  [CollectiveType.FUND]: [
    Sections.CONTRIBUTE,
    Sections.UPDATES,
    Sections.PROJECTS,
    Sections.BUDGET,
    Sections.CONTRIBUTIONS,
    Sections.CONTRIBUTORS,
    Sections.ABOUT,
  ]
```

We can move around every section into the new framework except `PROJECTS` - what is that and will it remain an extra special kind of section for `FUNDS`?

**Comment by sbinlondon** [comment]
UPDATE: please see the [table](https://docs.google.com/spreadsheets/d/15ppKaZJCXBjvY7-AjjCj3w5D-4ebLQdEowynJksgDXE/edit?usp=sharing) instead

**Comment by Betree** [comment]
Project is now live for everyone. We'll continue to iterate in the upcoming weeks to fix small regressions & to clean the code.
Progress can be tracked on https://github.com/opencollective/opencollective/projects/42
