### ISSUE TITLE
twitter is linked twice on profiles

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#337]
See for example: 
<img width="515" alt="screen shot 2017-04-11 at 5 21 30 pm" src="https://cloud.githubusercontent.com/assets/3671070/24929173/78a08ba0-1edb-11e7-8920-80460fc70490.png">

**Comment by xdamman** [comment]
Ah, that's because if there is no website we fall back to using their twitter url. I've just added JS foundation website in the DB and it fixed it for them (but it's still a bug to be fixed).

**Comment by piamancini** [comment]
I had just figured the same out with another profile.  Cool will close it then.
