### ISSUE TITLE
Request For Grant

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3374]
## User story 

As a project leader, I want to apply for Grant for my project.

I want to be able to be paid in cash (like an Invoice or Reimbursement). But it should be also possible to credit the money to my "Collective" (or "Event", etc ...) so I can use the Open Collective platform to disperse the money.

## Best solution for this problem

Adding a "Request for Grant" entry to "Submit Expense".

## MVP

Duplicate "Submit Invoice" and adapt it to "Request for Grant".

## Metrics 

Number of Grants requested.

## Documentation 

_TBD_

# Screenshots

![Screenshot_2020-07-30 Open Collective Foundation 501(c)(3) - New expense - Open Collective](https://user-images.githubusercontent.com/806/88911062-97df3280-d25d-11ea-9f5e-fa6a170e17c4.png)

![Screenshot_2020-07-30 Open Collective Foundation 501(c)(3) - New expense - Open Collective(1)](https://user-images.githubusercontent.com/806/88911103-a299c780-d25d-11ea-9227-97bbb78f178d.png)

**Comment by jeffin143** [comment]
Seems naive , do you want to handle it internally , or is it open , I can have a go if that's ok

**Comment by znarf** [comment]
@jeffin143 at this stage, I think we will handle internally, the specifications are not clear enough for other contributors.

**Comment by alanna** [comment]
Can we name this "request funding" instead? I think it will be used more broadly than just grants.

Ideally we should enable admins to set up a custom question. They will want certain info from requestors and it will be different for each. For MVP I think one text field with one user-definable text description is enough. Potentially we could adapt the "expense policy" feature to allow admins to set text shown to requestors (e.g. "In the descriptor field, please answer blah blah".

I really want the option to have the payee be Collective, Fund, Event etc for all expenses, not just this new kind! Why limit it? However, won't this require us to solve Collective to Collective transfers across hosts? Maybe we can release an MVP that only works for profiles in the same host first.

Will users be able to access the create Collective flow from this flow? I imagine many requestors will be new to the OC platform, so they'd need to create a personal profile, plus a payee Collective where the money will go. What will the UX be for that full flow?

If I'm understanding this correctly, I think payee Collectives created for funding requests should become connected Collectives, right? And show up on the parent Collective's page?

I assume after submitting, it goes to the parent Collective admin for approval. If they approve, what happens? Is the money automatically transferred? 

How will this intersect with tax form stuff? If it's just moving funds within the same host, then no tax issues will arise, and all tax stuff can be handled when people submit expenses to the resulting Collective.

**Comment by awright** [comment]
I am not sure if this is been discussed/considered -- but I wonder if there is ever a need to have multiple sign-offs. For example, we as admins can approve payment for a monies provided by XX org, but it would also be valuable to have a representative from XX org to review and agree. In the ethos of transparency, it would be like a verification/validation process representing consensus. 

Perhaps not needed for an MVP but is this a feature you have seen needed and/or considered? OOC.

**Comment by Betree** [comment]
@awright would https://github.com/opencollective/opencollective/issues/3081 match this need?

**Comment by awright** [comment]
@Betree ohh yes! definitely.

**Comment by flaki** [comment]
This is a really interesting proposition as it lines up precisely with one of the contribution processes we were drafting up. In this, basically contribution opportunities are to be listed as GitHub issues and an associated grant amount (can think of it as a "bounty" as well). Once the issue has been taken by a potential contributor they are requested to file an expense which would be approved and paid once the contribution is delivered.
Contribution locks can also "time out" that is, if the contribution is not received by a certain deadline and someone else shows up to deliver it, the expense would be rejected.

I think one of the trickiest questions in these setups is delineating what are the requirements for getting paid. While intuitively a "grant" sounds like to me as funds received early on into development, and "expenses" are filed in post for previous work, clearly explaining the rules are important in both cases.

Also just having an explicit separation for these grants vs expenses would allow for things like "what is the current amount of pending grants? how much money have we disbursed as grants?", instead of having these intermingled with *actual* expenses.

**Comment by alanna** [comment]
Great points @flaki ! @znarf could you see this being used for our bounties?

**Comment by znarf** [comment]
> Ideally we should enable admins to set up a custom question.

In the MVP, I'm considering a generic text field so it doesn't need a specific setup.

> I really want the option to have the payee be Collective, Fund, Event etc for all expenses, not just this new kind! Why limit it?

Agree. If it works for this case then It should work for others. But that might be complicated to implement. Cross Hosts transactions are another subject.

> Will users be able to access the create Collective flow from this flow?

No. This should be solved separately.

> If I'm understanding this correctly, I think payee Collectives created for funding requests should become connected Collectives, right? And show up on the parent Collective's page?

This is not considered at this point. "Connected Collectives" is not a core feature and we should try to avoid it. In the end, I would better see this featured in the 'Contributing' section.

> I assume after submitting, it goes to the parent Collective admin for approval. If they approve, what happens? Is the money automatically transferred?

It's like an Expense, Approval by an admin then payment by the Host Admin.

> How will this intersect with tax form stuff?

I assume it's working like Expenses, in the first place they will not be counted for tax form purposes because theses are not 'INVOICE'.

**Comment by Memo-Es** [comment]
### Design proposal

| Choose payee  | Payee info (Empty)  | Payee info (Filled)  | Grant application form (Empty)  |  Grant application form (Filled) | Expense summary  |
|---|---|---|---|---|---|
| ![Grant 1](https://user-images.githubusercontent.com/49539954/92677736-15c93b80-f2ea-11ea-9726-e6bceb9f3ccf.png)  | ![Grant 2](https://user-images.githubusercontent.com/49539954/92677741-182b9580-f2ea-11ea-8757-c3f42fdf725a.png)  | ![Grant 3](https://user-images.githubusercontent.com/49539954/92677746-19f55900-f2ea-11ea-82d2-a6f6b3eb9b2b.png)  |  ![Grant 4](https://user-images.githubusercontent.com/49539954/92677743-18c42c00-f2ea-11ea-8a29-134f86f90283.png) | ![Grant 5](https://user-images.githubusercontent.com/49539954/92677744-195cc280-f2ea-11ea-8022-e9a7ec06e21c.png) | ![Grant 6](https://user-images.githubusercontent.com/49539954/92677749-1a8def80-f2ea-11ea-992f-fc9043789bc5.png)  |

@znarf @piamancini

**Comment by kewitz** [comment]
Implemented following the design proposal. This feature is currently enabled only for funds.
