### ISSUE TITLE
Pay expense to a Collective budget (in the same host)

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3376]
I mentioned this in #3374 but I think it needs its own issue.

## User story 
As an expense submitter, I want to be able to select a Collective under the same host as the payee for an expense (or the host budget if it has an integrated budget).

This is effectively the same thing as going to a Collective and going through the contribution flow and selecting another Collective balance as the payment source - it moves money between Collectives without any money actually moving in bank accounts.

The reason we should enable this via expenses in addition to contributions is for transparency and good accounting practice. If one Collective does work for another, they should be able to submit an expense to reflect that accurately.

Moving money they way should not trigger the tax form because no money is being paid out. It's still sitting in the same host bank account, just credited to a different Collective budget.

Probably at first we should only allow people to select payee Collectives that they are admin of. 

The expense should go through the same approval process as any other expense.

Ideally this would work across hosts but that's way more complicated so I'm not suggesting it.

**Comment by alanna** [comment]
Note this would also apply to host budgets, as Hosts and their Collectives sometimes do work for each other too.

**Comment by alanna** [comment]
This is done, right?

**Comment by alanna** [comment]
@znarf this is done right?

**Comment by znarf** [comment]
@alanna Can you try it? Does it work for you?

**Comment by alanna** [comment]
This one worked so I guess it's good to go https://opencollective.com/opensource/expenses/30480
