### ISSUE TITLE
"Pay" button is stuck on "loading" after error

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#338]
![](https://cl.ly/1F173R341c3N/Screen%20Shot%202017-04-12%20at%208.54.11%20AM.png)

Also, what does the error "%email% account is restricted"?
(would be good to keep somewhere a list of errors and their explanation btw)

**Comment by xdamman** [comment]
Also, as an improvement, it would be better to show the error in the context of the action (so just below or above the "pay" button).

**Comment by piamancini** [comment]
I believe that  means there's an issue with the paypal account.

**Comment by asood123** [comment]
Yep, Paypal doesn't recognize the account or it's been restricted in some
form.
