### ISSUE TITLE
Tilde used instead of the almost equal to symbol

### ISSUE THREAD

**Issue by aaaxx** [opencollective/opencollective#3380]
In the Budget section, the Estimated annual budget amount is prefixed with a tilde, but should really use the symbol for almost equal to (≈ U+2248).

[It think this is the relevant line][budget-line], in `opencollective-frontend/components/collective-page/sections/Budget.js`

[budget-line]: https://github.com/opencollective/opencollective-frontend/blob/7238ba1e190617e13c9d25348632435f2314ed09/components/collective-page/sections/Budget.js#L174

![Screenshot of the Estimated annual budget issue](https://user-images.githubusercontent.com/6186480/89129082-a433eb80-d4fa-11ea-985a-c2f9c4506728.png)

***

Similarly, tilde is mentioned in ` opencollective-frontend/styleguide/examples/contribution-flow/StepBreakdown.md`:

> Paypal fee cannot be guessed in advance, so we prepend a ~ to the amount to show the user that we're not sure about this one.

There's also [this block of code][pmFeeInfo] that prepends a tilde to some fee, which I think relates to that, in `opencollective-frontend/components/contribution-flow/StepBreakdown.js`

[pmFeeInfo]: https://github.com/opencollective/opencollective-frontend/blob/master/components/contribution-flow/StepBreakdown.js#L80-L99

**Comment by Betree** [comment]
Hi @aaaxx, thanks for this insightful report. 

@Memo-Es what to you think?

**Comment by Memo-Es** [comment]
I've done a little bit of research, and I think we use it for its meaning of 'approx', which is accurate in the context of a Collective's balance displayed on the Collective page.

Anyway, I'm open to reviewing it if we found a more reliable reference :)
 
@Betree

**Comment by Betree** [comment]
@Memo-Es Indeed, according to https://en.wikipedia.org/wiki/Tilde#Approximation:

> Before a number the tilde can mean 'approximately; '\~42' means 'approximately 42'.[17] When used with currency symbols that precede the number (national conventions differ), the tilde precedes the symbol, thus for example '~$10' means 'about ten dollars'.[18]
> 
> The symbols ≈ (almost equal to) and ≅ (approximately equal to) are among the other symbols used to express approximation. 

So I don't think it's wrong to use `~` instead of `≈`. @aaaxx do you have any other references on why we should use one or another?

**Comment by aaaxx** [comment]
Sorry, I didn't mean for this to cause so much wasted time. I always assumed people used tilde simply because it's available on the keyboard, like they use the letter "x" or asterisk instead of the multiplication symbol.

I did some searching on Math Stack Exchange and found this question on [the meaning of various equality symbols][math-stack]. It seems that tilde, unlike "≈", has quite a few possible meanings, such as asymptotic to, equivalent to, having the same order of magnitude and showing distribution of some sort. They also mention [ISO 80000-2], which says it's used for proportionality and equivalence relations (p. 14).

[math-stack]: https://math.stackexchange.com/questions/1269958/the-meaning-of-various-equality-symbols
[ISO 80000-2]: https://people.engr.ncsu.edu/jwilson/files/mathsigns.pdf

**Comment by Betree** [comment]
@aaaxx We discussed this with the design team and though `≈` may be more accurate technically, we don't yet have proof that users may be confused by `~` and so we're not willing to make this change right now. We'll be happy to revisit if we get the feedback that this symbol has a different meaning for certain locales, or if it's globally misunderstood.

> Sorry, I didn't mean for this to cause so much wasted time.

Thank you for opening this issue! Improving the wording, icons and symbols that we use is important for accessibility and these discussions are always welcome. Feel free to contribute again!
