### ISSUE TITLE
Send hosts invoice for platform fees

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3381]
## User story 
User reports:

> I'm currently trying to reconcile the accounting of financial contributions made via credit card to our various hosted projects, and I can't see any UI or method to get a complete invoice for all Open Collective platform fees that were incurred in a month (or per any given transaction, for what it's worth). Yes, I can see the amounts both in open collective and Stripe but I need an *invoice* from Open Collective for all these deductions. Stripe provides one for the Stripe fees, but I don't see anything like this in OC.

In addition, the current way we handle host plan subscription documentation is pretty bad. We just send an email saying "Host plan subscription renewal" but there is no invoice attached or link to download it.

## Best solution for this problem
An invoice showing the total platform fees charged each month to a host, i.e. the 5% on Stripe transactions, plus any charges for a paid host plan. This could go out with the monthly host reports (i.e. as another attachment to that email) or could replace the "Host plan subscription renewal" emails we currently send.

Ideally there would also be a section in the host dashboard to see payments to the platform, and download past invoices, but that could be a future iteration. For now, emailing the invoice is enough.

## MVP
We already show host fees charged in the monthly report, but it's just a number, not a valid invoice. I don't think there's an MVP way to do this feature, because we're either sending a proper invoice or we're not.

**Comment by Kilheure** [comment]
I would also add a range section to download report (ie for a month a year, between 2 dates) and keep a copy of the invoice on its collectives page (in host dashboard?)

**Comment by flaki** [comment]
RE: @alanna in the [original Slack thread](https://opencollective.slack.com/archives/CJ2ERRZQ8/p1595755490132100?thread_ts=1595573318.130700&cid=CJ2ERRZQ8):
> I believe platform fees are taken out before the funds ever reach the host. Therefore its not money we charge in the same way paying for paid host plans is (which we do provide a tax invoice for).

Yes this is true, but from an accounting standpoint ACME Corp. is paying a full $100 as a contribution (sponsorship) to a collective and thus expects the host to provide an invoice for a $100 contribution. On the host's side, the host *needs* to reconcile the incurred transaction costs because it will ever see only ~$90 of those costs arrive on its account. Some of these fees are accounted for as being Stripe fees and Stripe does, in fact, provide such an invoice, but Open Collective does not.

![image](https://user-images.githubusercontent.com/2089432/89176472-4a7f0000-d592-11ea-9d7e-4ed0eb227c25.png)

**Comment by flaki** [comment]
This is still very much an impediment in our day-to-days and would love to see this resolved please.

**Comment by znarf** [comment]
@piamancini What do you think about it?

**Comment by alanna** [comment]
@znarf is this already done with the new way we're charging platform fees?

**Comment by znarf** [comment]
I'm not clear on what is really expected and what should be the specs for this.

Regarding the situation for Hosts in 2021 with our latest pricing (OCF as example):

- Platform Fees (through Added Funds)
    - are added to the Host Budget in one transaction (1)
    - are given back in the settlement Expense (2)
- Platform Tips
  - Paid with Stripe are automatically taken and not mentioned in the invoice
  - Paid with other Payment Methods
    - are added to the Host Budget in one transaction (1)
    - are given back in the settlement Expense (2)
- Revenue Share on Host Fees
  - Paid with Stripe are automatically taken and not mentioned in the invoice
  - Paid with other Payment Methods
    - are given back in the settlement Expense (2)

(1) Platform Tips and Fees added to the budget

<img width="1199" alt="Screenshot 2021-01-21 at 13 09 21" src="https://user-images.githubusercontent.com/806/105349713-67fc6080-5bea-11eb-9765-1829eeaf6df2.png">

(2) Settlement Invoice

<img width="725" alt="Screenshot 2021-01-21 at 13 12 50" src="https://user-images.githubusercontent.com/806/105349775-7c405d80-5bea-11eb-8de7-908096ddf134.png">

**Comment by alanna** [comment]
I can help with specs @znarf - things have changed a lot since this issue was raised so we should rethink requirements. We are trying to achieve a few things here.

**Accounting**: host entities need documentation, i.e. and invoice where the numbers match credits and debits in their bank account, for their tax reporting.

**Transparency**: Everyone (Host Admins, their Collective Admins, Financial Contributors, etc) should be able to clearly see the flows of money from the initial contribution to the host fees to the platform fees.

**Payments**: Both Hosts and Open Collective Inc need to accurately and reliably collect the money they are owed for fees.

Ideally we would achieve this in a single monthly expense to charge fees/tips owed, which can also serve as the downloadable invoice needed for documentation and fulfil the need for transparency.

So it could look like:

## Monthly Platform Fees - December 2020
| Invoice items       |            |   
| ------------- |:-------------:|
|    Platform tips collected - via stripe   |   $100 |
|    Platform tips paid - via stripe   |     -$100 |
|    Platform tips owing   | $500 |
|    Platform fees collected - via stripe   |   $200 |
|    Platform tips paid - via stripe   |     -$200 |
|   Platform fees owing (15% [or 50% for OCF] of $X host fees) | $2500 |
|   Payment processor fee reimbursement for platform tips transactions | -$50 |
|   **TOTAL** |  $2,920

**Comment by alanna** [comment]
This is solved with the new host budget monthly settlement expenses
