### ISSUE TITLE
Rounding 0.1$ to 0$ in collective front page

### ISSUE THREAD

**Issue by jilleJr** [opencollective/opencollective#3384]
**Describe the bug**
Frontpage of my collective is rounding a donation from 0.1$ to 0$.
It's nice that it's rounding but here's it just looks like someone cheated the system and gave 0$.

**To Reproduce**
1. Go to https://opencollective.com/newtonsoftjson-for-unity
2. Scroll down to 'Top financial contributors'
3. See 0$ donation

**Expected behavior**
Either...
- show amount in cents when <1; displaying "10¢" _(this would be the best IMO)_

- round to nearest 0.1 when between 0.1≤x<1, round to nearest 0.01 when between x<0.1; displaying "0.1$"

- _-or-_ display "<1$"

**Screenshots**
![top financial contributors example of 0$ donation](https://user-images.githubusercontent.com/2477952/89220336-ae74e900-d5d1-11ea-9274-8d7e02630cda.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - OS: Android
 - Browser Chrome
 - Version 84.0.4147.89

**Additional context**
Not big issue. Just think it's unfair for the donor to have their donation rounded down to 0

**Comment by Betree** [comment]
@jilleJr thank you for reporting this issue. While displaying the amount in cents (ie. `10¢`) looks good, it [won't work for all currencies](https://en.wikipedia.org/wiki/Cent_(currency)). The two other suggested options should work fine.

They should be implemented in the `FormattedMoneyAmount` component, but behind a special flag (ie. `roundToZero={false}`) because in some context (like showing the minimum amount for a tier) it's still ok to round to 0.

**Comment by jilleJr** [comment]
Ah Yea sad it doesn't translate well to EUR.
I don't know if it would be too spagetti or wrong dependency but it would be nice if it used the lower currency form if available. Like the value of 0.1 would be shown as:
- `10 ¢` in USD
- `0.1 €` in EUR
- etc..

**Comment by znarf** [comment]
I just checked and we actually don't want to support donations of less than $1 or 1 euro. These transactions are problematic because the payment processor fees can be more than the donation itself.

I think we should make sure Tiers can not set a minimum amount of less than $1 or 1 euro.

**Comment by Betree** [comment]
> I just checked and we actually don't want to support donations of less than $1 or 1 euro. These transactions are problematic because the payment processor fees can be more than the donation itself.

It's true but since some currencies can have a stronger value than the dollar (like "Kuwaiti dinar" for example - 1 dinar ~= 3$) it's valid to have amounts smaller than `1` in there. I've opened a separate issue to iterate on this: https://github.com/opencollective/opencollective/issues/3793
