### ISSUE TITLE
Transactions Page redesign follow-up

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#3385]
The Transactions page redesign was shipped yesterday and the old issues were closed.
This is a follow up with improvements and missing tasks.

- [x] Add server-side rendering.
- [ ] Refactor Transaction export endpoints from V1 to V2 and remove leaking ids to the front-end.
- [x] Restore the "Refund Button".
- [x] Review conditionals for accessing the "Download Receipts" button.
- [x] Resolve Transactions access and permissions in the back-end.
- [x] Fix comments count bug: https://sentry.io/organizations/open-collective/issues/1822712057/?project=1736806&referrer=slack
- [x] Update the collective page Budget section to use the V2 endpoint and the new TransactionDetail component.

**Comment by Betree** [comment]
Since we need to review them. it would be great to have the permissions checks for refund and download receipts server-side as proposed in https://github.com/opencollective/opencollective-frontend/pull/4719#discussion_r464322934.

**Comment by kewitz** [comment]
@Betree I think these permissions are actually related to the collective and not transactions.
Perhaps we should refactor the permission check for the collectives in another PR? WDYT?

**Comment by Betree** [comment]
While most of the checks are indeed done on the collective(s), I think they still belong conceptually to `Transactions`. Also because there still are some checks on transactions that can impact the result:

```es6
canRefundTransaction(transaction, user) {
  return !transaction.RefundTransactionId || user.isAdmin(transaction.collective.host.id);
}

canDownloadReceipt(transaction, user) {
  if (transaction.UsingVirtualCardFromCollectiveId) {
    return user.isAdmin(transaction.UsingVirtualCardFromCollectiveId);
  } else {
    return user.isAdmin(transaction.FromCollectiveId);
  }
}
```

**Comment by kewitz** [comment]
Refactor Transaction export endpoints from V1 to V2 and remove leaking ids to the front-end is more complex than first thought since it interacts with outside services that still rely on the UUID.
