### ISSUE TITLE
Redesign /donate and make it embeddable

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#339]
We would love to have an overlay after we click on the new donate button (https://github.com/OpenCollective/OpenCollective/issues/333) that people can put on their site.

The goal would be to offer a similar experience than the Stripe overlay that we currently use ourselves (after you click on "donate").

For that we would need to redesign the current /donate page (e.g. https://opencollective.com/webpack/donate) and then show it as part of an overlay in an iframe.

@cuiki can you come up with a design for it?

**Comment by cuiki** [comment]
Hi @xdamman,

Sorry for the delay. Here is the design for the embeddable donation modal. I used webpack's example with the donate button on their site. Let me know your thoughts.

› Zeplin link: https://zpl.io/1VvQXe

![embbedable-donation-modal](https://cloud.githubusercontent.com/assets/981188/25290273/f9815074-2692-11e7-99e2-fbbf06b467e9.png)

**Comment by xdamman** [comment]
Love this! Great job! @gusaus will love it too :)

Can you do a version that would not have options to change the amount / frequency and with a custom description? E.g. https://opencollective.com/webpack/pay/500/gold%20sponsorship

**Comment by piamancini** [comment]
nice!!

**Comment by gusaus** [comment]
Looks amazing! 

https://donorbox.org/ might provide examples of additional features that would be nice to have. @hollomancer will have a better idea of how it works on the admin side.  

If we need additional help, we can create a custom embed for https://opencollective.com/opensource/donate/ to fund the work!

**Comment by xdamman** [comment]
Our goal is not to creep it with ton of features. We want to keep it dead simple. At least for now. Done is better than perfect.

**Comment by cuiki** [comment]
Hey! Updated version in Zeplin: https://zpl.io/1VvQXe

**Comment by piamancini** [comment]
Hi @cuiki it looks great and it's sooooo requested  by our users, they'll be stocked. Any chance we can make force a height on both boxes?

**Comment by xdamman** [comment]
@cuiki great! Can you also do the next screen with credit card form and the one with the form to sign up a new user (first name, last name, avatar, one-liner).

@piamancini what do you mean by that?

**Comment by cuiki** [comment]
I think Pia means that both modals are different height, and she says that if they can be the same height. That means that the second one should be taller...

**Comment by xdamman** [comment]
I like the design here for the credit card form https://hackernoon.com/accept-payments-on-your-site-with-nextjs-stripe-and-micro-371de95b22d5

**Comment by cuiki** [comment]
Very cool form!

**Comment by piamancini** [comment]
no longer relevant.

**Comment by heyakyra** [comment]
> no longer relevant.

It is still not possible to create embeddable forms for donations, recurring subscription payments (memberships), etc. 

I guess there's #3003 now but it seems this was closed prematurely
