### ISSUE TITLE
Improve settings for all users (Admin panel update)

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3395]
## User story 
_As a Collective, user, or fiscal host, I want to have all of my settings and management features in one place so that is easier for me to understand all the things I can do inside Open Collective_

## Best solution for this problem
_Evolving the settings page to an admin panel for all types of users. In the case of fiscal hosts, they will have inside their admin panel all of the functionalities originally conceived for the former fiscal host dashboard (see #2896)_

## MVP
_Migrate current settings to this new structure, we might want to start with fiscal hosts since the dashboard and host features are currently developed_

![Collections](https://user-images.githubusercontent.com/49539954/89478692-4f8cac80-d756-11ea-8c96-3a8eb7cb21ad.png)

## Metrics 
_Less support tickets, can't think of another metric right now_

### Fiscal hosts
See #2665 

---

###  Help us sort Collectives' settings! 

We would like to simplify the options users have available, Collectives' panel sidebar has too many elements now and we want to nest some of them in categories _See example below_

Current state | Proposal
-- | --
![Large (Desktop)](https://user-images.githubusercontent.com/49539954/89481508-81554180-d75d-11ea-961c-1efdde5a58fa.png)  |  ![Large (Desktop)-1](https://user-images.githubusercontent.com/49539954/89481515-84503200-d75d-11ea-8749-560179a128a2.png)

Feel free to copy the next [🗒board](https://docs.google.com/drawings/d/1HQRmI9OIRV0SjlQJHlAroF4e5meqcP4bl02RobJE-nU/copy) and take a stab at this if you have another proposal for organizing these elements.

The final sorting/nesting decision will impact how fiscal host settings would look as well.

@opencollective/community @alanna @znarf @kewitz @sbinlondon @Betree @piamancini

**Comment by Betree** [comment]
@Memo-Es Should the navbar be displayed on this settings page?

**Comment by Memo-Es** [comment]
@Betree No, you go back to the Collective page clicking the 'Exit Admin Panel' button

![Annotation on 2020-12-03 at 10-49-29](https://user-images.githubusercontent.com/49539954/101060785-651fb080-3555-11eb-84b8-b5a3780db750.png)

**Comment by Betree** [comment]
That makes sense, thank you!

**Comment by Memo-Es** [comment]
Closing this issue since it's addressed in #3880
