### ISSUE TITLE
Ticking "enable" should override profile sections settings and vice versa

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3396]
I clicked "enable" in the "Updates" section of settings, but then could not see the option to post an Update on my page. Then I realised Updates were set to "disabled" in the "profile page" area of settings, where you can reorder, enable, and disable various sections. Enabling or disabling Conversations or Updates in either settings area should override the other setting, and the most recent decision should be in effect. This is a UX bug IMO.

**Comment by alanna** [comment]
@Betree @znarf this is still happening. 

I'm wondering why do we even need the seperate settings for conversations and updates when they can already be turned on and off under profile page? Better to add the FAQ and screenshots in the settings to the docs and just put a ? tooltip link to there from the profile page settings in the app.

But regardless, at least the two places to enable or disable conversations and updates should be synced.

**Comment by Betree** [comment]
> I'm wondering why do we even need the seperate settings for conversations and updates

The rational at the time was that you may want to use the conversations feature without showing the section on your collective page.

That being said, we should thrive for simplicity and the current behavior is really confusing.

**Comment by alanna** [comment]
> you may want to use the conversations feature without showing the section on your collective page

I... what? How would this work? Hahah sorry I'm confused. 

Personally I think we should simplify and remove the conversations and updates settings sections and just have them turn on and off in the profile page section. In the future if those features have settings of their own, we can reintroduce their own sections.

**Comment by Betree** [comment]
> I... what? How would this work? Hahah sorry I'm confused.

Like my collective may want to use the Updates feature to send newsletter without showing them on my collective page. For example if my updates are usually things limited in time or if I want the collective page to be simpler to not distract potential contributors. In such a case you go to `opencollective.com/collective/updates` to publish your updates, and everything works normally except the updates are not displayed on the collective page.

> Personally I think we should simplify and remove the conversations and updates settings sections and just have them turn on and off in the profile page section. In the future if those features have settings of their own, we can reintroduce their own sections.

Yep, I agree with that - "I'm up with unifying the settings" :slightly_smiling_face:

**Comment by Betree** [comment]
Wondering how this is going to play with the new `CONNECT` section , that's going to group updates and conversations in the same place. We need to be able to disable conversations without breaking updates and vice versa.

**Comment by sbinlondon** [comment]
This was a source of confusion for me writing the code @alanna so I agree it needs to be one or the other.

@Betree I was originally going to say that we should go for the `settings.collectivePage.sections[{section: "updates", isEnabled: true }, ...]` option but the more I think about it the more I dislike this. As you mentioned in clarifying features vs sections, CONNECT is a section, but UPDATES and CONVERSATIONS are features. 

So why wouldn't we keep relying on `settings.features.conversations` or `settings.features.updates` to see if they are enabled or not? We can use `settings.collectivePage.sections[{section: "connect", isEnabled: true }, ...]` for main sections like CONNECT, and if that's been 'hidden' via the edit collective page Profile Page Sections menu, then it won't matter whether the features within it like CONVERSATIONS and UPDATES are enabled or not. We won't show CONNECT, we won't try to fetch data for its features.

The problem I'm worried about though is that we currently have 2 - and with features incoming 3 - ways of deciding if CONVERSATIONS and UPDATES are turned on or not so if we decide to go with one option everywhere, will some collectives using the legacy ways get the wrong enabled/disabled/etc?

**Comment by sbinlondon** [comment]
Closing this since it is planned to be fixed as part of the Collective Navigation v2 project. Please put anything else related to this problem in this issue: https://github.com/opencollective/opencollective/issues/3755
