### ISSUE TITLE
Discover page: "most popular" should sort by number of contributors

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3397]
**Describe the bug**
On the [discover page](https://opencollective.com/discover), the order of the collectives when sorting by "Most popular" (default) is tricked by two things:
- The currency (a collective with 1000CZK will appear before one with $500)
- The added funds (self-hosted collectives can set a custom balance)

**Expected behavior**
Popularity should sort by number of contributors, because it's more difficult to fake this number.

**Screenshots**
![image](https://user-images.githubusercontent.com/1556356/89511280-fc583f80-d7d1-11ea-8f7b-61e6f7f51178.png)

**Comment by znarf** [comment]
Good stuff!
