### ISSUE TITLE
Join Slack is Broken

### ISSUE THREAD

**Issue by gersh** [opencollective/opencollective#3398]
**Describe the bug**
I'm unable to join Slack at https://slack.opencollective.com/.

**To Reproduce**
1. Go to https://slack.opencollective.com/
2. Enter an email
3. Hit the button to signup
4. I get "token revoked"

**Expected behavior**
Registration

**Desktop (please complete the following information):**
OS X, Chrome

**Comment by znarf** [comment]
@gersh Thank you for the report.

**Comment by znarf** [comment]
Just moved from Slackin to Slack's native invitation system. See: https://github.com/rauchg/slackin/issues/416
