### ISSUE TITLE
Support Metrics Report July 2020

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#3399]
### Support Metrics Report July 2020

This report looks at the trends around support to help us better understand areas we need to improve and highlight key topics for the month. 

**Tickets received** 

![Capture](https://user-images.githubusercontent.com/57156267/89748577-fd61d780-db17-11ea-8fa3-56bb052d37a1.JPG)

The number of tickets received has increased by nearly 10% from 365 in June to 401 in July . By removing blank tickets, the increase is only around the 8% mark with 298 tickets raised in July compared to 276 in June. 

**Trends and Recommendations**

![Capture2](https://user-images.githubusercontent.com/57156267/89748618-2a15ef00-db18-11ea-84b8-ae8f22be804e.JPG)

After removing irrelevant tickets, we had 298 that required support attention. It is worth noting the following areas:

**Expenses**

This category continues being the major one when it comes to support tickets received, with July numbers peaking at 89 tickets (nearly 30%).

As indicated in the previous month, there is still a large portion of tickets received are users' feedback and comments on changes in expense status (approved/paid) with some follow-ups which are referred to the collective directly and not dealt by us. 

Some other things to note. During July OSC bank account was compromised and we set up a new account. This resulted in some delays in payments due to the process and the linking of the account to PayPal and TransferWise. On a few occasions, payments were delayed. When this happened we ensured to notify the users and keep them informed of the delays. No major negative impact for us, but these changes did result in quite a significant increase in workload for the team. 

**Onboarding related questions**

The number of onboarding related questions seems to be dropping down which seems to be in line with enquiries of COVID related projects starting. We still get questions around the way our platform works but compared to the past few months there is a significant drop. It looks like we are getting back to the same level of enquiries as we were receiving pre-COVID, very much in line with our January-February figures. 

**Payments methods**

The major reason for the increase this month from a handful of tickets on a normal basis to 19 this month was a bug in early July where a number of contributions failed and the users were not able to update their card details. The issue was resolved and we expect to go down to single digits with our ticket numbers in the following months. 

**Grants**

There is positive traction of grants being received by the collectives under Open Collective Foundation 501(c)(3) umbrella and this is in line with previous months. There is an increase of new support grants being received by the collectives and this is a very positive sign. The tickets received here are mostly requests from the funds for us to confirm the recipient details to allow for the disbursement of funds. 

**Other things to note**

We are currently working on trying to improve the monitoring of donations received through bank transfers and checks, and looking into implementing a better process. This is mostly relevant for OCF where, at the moment, there is a lot of manual processing required to account for funds coming in.

We also work on a more transparent EOM process to ensure all revenue and expenses for the fiscal hosts is accounted for correctly. We will report back once the process has been fully established as we are still working through some technical issues with the setup of bank accounts for our operational costs. 

With the new dashboard going live, we are also curious to see the impacts on August trends and will report back on any significant feedback coming through. Stay tuned :)

**Comment by alanna** [comment]
Thank you @alinamanko !!

**Comment by Betree** [comment]
Thanks @alinamanko :+1:
