### ISSUE TITLE
Feature: Allow supercollectives to approve/deny collectives to join

### ISSUE THREAD

**Issue by hollomancer** [opencollective/opencollective#340]
_As a supercollective, I want to be able to approve or deny collectives that want to associate with me from the admin frontend._

**Comment by piamancini** [comment]
This makes sense. For the moment, collectives created with you as a host need to be activated manually. So there is a filter - albeit extremely suboptimal - that involves you and support checking that you are ok to approve it. 
We'd need to think how this would work in the flow. cc / @asood123

**Comment by piamancini** [comment]
this is now on an email. It happens at a host level. It only has an approve button but you have the contact of the person that submitted the application. closing.
