### ISSUE TITLE
Improve image optimization script

### ISSUE THREAD

**Issue by flickz** [opencollective/opencollective#3402]
### Current Behaviour: 
As a developer, I want to optimize a new image file in the `public/static/images` directory, I have to update the script file directly in order to set the right directory and filename. 

### Expected Behaviour
- Ability to set the file path or directory from the command-line either as a single image file or multiple files.

**Comment by Betree** [comment]
Agree, it would be nice to be able to do this:

```bash
# ./scripts/optimize-png.js [SOURCE_FILES] [OUT_DIR] 
./scripts/optimize-png.js public/static/images/home/original/joinus*.png public/static/images/home
```
