### ISSUE TITLE
Collective not appearing in search

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3404]
I searched `juneteenth` looking for the [Juneteenth Conference Collective](https://opencollective.com/juneteenth-conference) but it did not appear despite it existing.

<img width="1132" alt="Screen Shot 2020-08-12 at 2 54 05 PM" src="https://user-images.githubusercontent.com/5498878/89970218-709c5280-dcac-11ea-94d4-897f7e0cef8d.png">

**Comment by Betree** [comment]
@piamancini Indeed, search is only Collectives and Organizations at the moment but it's only a one line change in https://github.com/opencollective/opencollective-api/blob/a4c9bbffa2f0d18ecceca7c1d031df2fafba17f1/cron/daily/51-populate-search-index.js#L39 if we want to include Funds

**Comment by alanna** [comment]
I think we should include Funds. We already give Funds a lot of options about what data they want public, so I don't think we have to try to hide them.
