### ISSUE TITLE
Set up a new Fiscal Host without having to create a Collective

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3408]
## User story 
As the admin of a new Fiscal Host, I want a clear path to create and activate my host without needing to set up a Collective. Our current [process for onboarding as a host](https://docs.opencollective.com/help/fiscal-hosts/create-a-fiscal-host) requires a Collective to be created. Now that we have integrated host budgets, we need to enable a path for new hosts without a Collective to start with.

## Best solution for this problem
A fully thought through and designed 'create a host' flow.

## MVP
Create an Organization and then click a button to turn it into a host?

I'm pretty sure this isbeing considered in the host dashboard project @Memo-Es but I just want to be sure. Our current process is pretty broken for cases where a) there are no Collectives for the host yet, and b) where the host admin and first Collective admin are not the same person or from the same organization. In case of b) we have to get one or the other to set up both the Host and Collective and then add the other as admin to the right profile and get themselves removed, and it's messy.

**Comment by znarf** [comment]
It's more a documentation problem, creating a Collective is not required to create a Fiscal Host.

Any regular User or regular Organization account is enough.

**Comment by alanna** [comment]
@contraexemplo - can you update the host creation documentation to correct this?

**Comment by alanna** [comment]
I updated [the docs to show how to create a host](https://docs.opencollective.com/help/fiscal-hosts/create-a-fiscal-host) without a Collective, but it's really messy so I'm going to raise a seperate issue about improving the flow.
