### ISSUE TITLE
Feature: Allow supercollectives to set the handling fee percentage they take from the collective

### ISSUE THREAD

**Issue by hollomancer** [opencollective/opencollective#341]
As a supercollective, I would like to manually set the amount I charge in handling fees to my collectives.

Other notes:
- Probably good to make this as transparent as possible to the collective in the UX
- Possible future goal to make it clear when a collective joins a supercollective, what the handling percentage will be
- Possible future goal to set fees individually for each collective, instead of globally

**Comment by piamancini** [comment]
All of this makes sense as well @hollomancer. Thank you for brining it up. 
Atm we can do all of that, it just needs to be done manually. 
I wonder what other hosts think?

**Comment by hollomancer** [comment]
Yeah, I'm curious what some of the other hosts think too. I don't see it as a blocker, but it will become more valuable as a supercollective scales (re. number of collectives).

**Comment by gusaus** [comment]
It would be ideal for a supercollective to have this type of control if possible. Less overhead for the OpenCollective team too!

**Comment by piamancini** [comment]
Closing this in favor of an accurate definition of roles and also to fit it in the scope of self-serve flow https://github.com/opencollective/opencollective/issues/1066
