### ISSUE TITLE
Unable to pay via Transferwise even though funds are available

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3410]
I am trying to pay [this expense](https://opencollective.com/ocnz/expenses/23053).

I have the funds available in my Transferwise NZD balance:
![Screen Shot 2020-08-18 at 10 35 50 AM](https://user-images.githubusercontent.com/5498878/90450845-b343ac00-e13e-11ea-93d4-a18fa20b66f0.png)

But when I go to pay, it gives me this error:
![Screen Shot 2020-08-18 at 10 36 01 AM](https://user-images.githubusercontent.com/5498878/90450864-bccd1400-e13e-11ea-9803-fc6d5a131fc4.png)

Is this due to fees? If so, we need to make some improvements to this experience:
1. When the host is looking at the total for the expense, it should show the expected transferwise fees so they know how much they'll need in their transferwise balance. I specifically sent $1150 to transferwise to cover this expense, but now it's telling me it's not enough?
2. The error message should clearly state that the insufficient balance is due to fees, and show how much those fees are.

If it is due to fees, can you please tell me how much they are so I can send that amount over? It seems crazy to do a bank transfer for like $1 or whatever it's going to be, but I'm trying to do a full transferwise payment so I can ensure it's set up and working for this host.

@kewitz can you confirm?

**Comment by kewitz** [comment]
@alanna that's exactly right.
We're not fetching and displaying the fees at payment time, we do that only when already executing the payment.
This was discussed before with @Betree, although I'm not sure we converted to an issue:
The main idea would be displaying the fees at confirmation but a quick-win would be returning the fee value with the error.

Since these fees are kinda hard to predict, I'll include the amount in the error message ASAP so you can have that.
Another way to calculate these fees would be by checking the TransferWise website.

**Comment by alanna** [comment]
I added more funds and the payment went through. Having the fees in the error is a good start.

How about when an expense is approved for a Transferwise payment, if there are not enough funds in the balance to cover the amount + fees, an email goes to the host admin letting them know? Ideally the admin needs to know the balance is short ahead of going to pay the expense, because transferring funds to the TW balance takes time.

**Comment by kewitz** [comment]
The updated error message got merged already, it will specify how much you need and how much you’re paying for fees.

The problem with validating when cresting the expense is that the transaction often involves another currency. This means that the fees and rates involved might change from the time the expense was created and the time it was actually paid.
That’s why I think the right way to go is to add fees to the confirmation screen. The account balance will also be available in the new host dashboard, which may help out projecting your TW budget.

**Comment by Betree** [comment]
> We're not fetching and displaying the fees at payment time, we do that only when already executing the payment.
> This was discussed before with @Betree, although I'm not sure we converted to an issue:

It's still planned in https://github.com/opencollective/opencollective/issues/3089

**Comment by znarf** [comment]
Closing because I think the issue was addressed.
