### ISSUE TITLE
Inconstistencies on GQLV2 types

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3413]
I'm being slowed down by two inconsistencies in the GraphQL V2 API types.

<details>

# Order frequency VS Tier interval

We have two enums to represent the same concept: 
- [TierInterval](https://github.com/opencollective/opencollective-api/blob/066dbc71ac12d2ca4a90e33d2ef09c6ed6d87013/server/graphql/v2/enum/TierInterval.js)
- [OrderFrequency](https://github.com/opencollective/opencollective-api/blob/26f3db89fade9a1b5f2b0f5393450c9e73097d30/server/graphql/v2/enum/OrderFrequency.js)

In the frontend, it results in unnecessary complexity:

```es6
order = {
  frequency: getGQLV2FrequencyFromInterval(tier.interval),
}
```

Another [example](https://github.com/opencollective/opencollective-frontend/blob/f80caaf53b977fcab1d500b4606895c43c0a1b09/components/recurring-contributions/UpdateOrderPopUp.js#L125) in the existing code.

Having its values uppercase, `OrderFrequency` better follows the rules of GQLV2 API. On the other hand, it requires updating multiple places in the frontend if we want backward compatibility (ie. `FormattedMoneyAmount`, `i18nInterval`, etc.).

:arrow_right: **Should we remove `TierInterval` in favour of `OrderFrequency`?**

</details>

# PaymentMethod type

We recently introduced a [`PaymentMethodType` enum](https://github.com/opencollective/opencollective-api/blob/17766bb3b0a7507f2031ae75f89360b89bb38dab/server/graphql/v2/enum/PaymentMethodType.js) to use instead of the traditional `service`/`type` couple, but the [`PaymentMethod` object](https://github.com/opencollective/opencollective-api/blob/66ef527e77350e8d90f4f98ffceb4da55ca80b6e/server/graphql/v2/object/PaymentMethod.js#L11) is still using this legacy `service`/`type` pair.

:arrow_right:  **Should we deprecate `service`/`type` in favour of `PaymentMethodType` and use it for all new developments?**

**Comment by znarf** [comment]
> Should we remove TierInterval in favour of OrderFrequency?

I think so, but then it might be wrong to name it `OrderFrequency` so we could refactor it as `Frequency`.

> Should we deprecate service/type in favour of PaymentMethodType?

Yes, I gave feedback about that in https://github.com/opencollective/opencollective-api/pull/4021#pullrequestreview-427318562

We can keep `type` and `service` if they help the migration but I personally think they should be marked as deprecated.

I feel strongly about the simpler enum design (`PaymentMethodType`) even if it complicates a bit for now. It's still time to tweak this if we think it's not a good design.

**Comment by Betree** [comment]
@znarf thanks for the feedback!

> I think so, but then it might be wrong to name it OrderFrequency so we could refactor it as Frequency.

I agree, tho I would probably name it `ContributionFrequency` as these values are only meant to define frequencies for recurring contributions.

> I feel strongly about the simpler enum design (PaymentMethodType) even if it complicates a bit for now. It's still time to tweak this if we think it's not a good design.

I'll go with that then :+1:

**Comment by Betree** [comment]
I also suggest renaming `PaymentMethodDataInput` in https://github.com/opencollective/opencollective-api/blob/90374b46f6013b1c029d69cce067de4f09ebe27d/server/graphql/v2/input/PaymentMethodDataInput.js to `CreditCardDataInput` as it's only used for credit cards.

**Comment by znarf** [comment]
@Betree I agree. Then also `PaymentMethodCreateInput` to `CreditCardCreateInput` or `PaymentMethodCreditCardCreateInput`. Also `addStripeCreditCard` to `addCreditCard`?

**Comment by Betree** [comment]
I've hidden the part about _Order frequency VS Tier interval_ because having two different enums now makes sense: tier can have the `flexible` interval type, that lets users pick whatever interval they want. But we don't want this `flexible` value to be there when looking at `order.frequency`, because it makes no sense there.

As part of the Braintree work, we've noticed that the `service`/`type` approach for payment methods was more flexible. So we'll rather be tackling the changes in https://github.com/opencollective/opencollective/issues/4040. Other types have already been renamed.
