### ISSUE TITLE
Reading "email" on Organization in GraphQL is inaccurate

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3415]
**Describe the bug**

As a Collective admin, I would like to be able to see the email of Admins of Organizations contributing to my Collective.

**Problems**

- `email` is buggy or inaccurate on Organization as it's only exporting the email of the CreatedByUserId.

**Solution**
- `email` field should not exists on Organization as it's only exporting the email of the CreatedByUserId.
- `getListOfAccessibleMembers` should give me  access to the the admins of Organizations contributing to my Collective

**Comment by znarf** [comment]
Sample GraphQL:

```graphql
query collective {
  collective(slug: "bower") {
    name
    backers: members(role: BACKER, limit: 1000) {
      limit
      totalCount
      nodes {
        account {
          slug
          type
          ... on Individual {
            email
          }
          ... on Organization {
            admins: members(role: ADMIN) {
              nodes {
                account {
                  ... on Individual {
                    email
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by piamancini** [comment]
This is very problematic for some projects using open collective, specially https://opencollective.com/meet-coop/
Because they are selling subscriptions using open collective. 

Is there a path through which we can solve this? 

Alternatively, how can they access this information?

**Comment by znarf** [comment]
The only easy thing I see for now, they can always contact support and we do an export for them.

**Comment by piamancini** [comment]
That is not a realistic solution. 
Maybe @kewitz can do a query in metabase like we did for our accountants so they don't need to ping us every time.

**Comment by RCheesley** [comment]
+1 on this.

This is *really* problematic for events selling tickets through an Open Collective - we need to have the email address in the results in order to add the ticket purchasers to our event platform!

Link to Slack conversation: https://opencollective.slack.com/archives/C4TC3AYDT/p1601032266004500

**Comment by Betree** [comment]
If we're ready to allow that, `allowContextPermission` + `setContextPermission` called at the right place should solve the immediate issue.

Another option: we could add an `emails` field on `Member` that returns a list of all emails (with only one entry if it's an Individual).

Some related things to consider for the future:
- We would need to make sure the SPAM issue is solved before enabling that, but https://github.com/opencollective/opencollective/issues/2840 could also help. 
- Also https://github.com/opencollective/opencollective/issues/2263, so organizations could define their primary contact email.

**Comment by Betree** [comment]
Can we also use this issue to track the fact that organization emails are missing from CSV export? It sounds like a similar problem of defining what an organization's email(s) should be.

**Comment by znarf** [comment]
@Betree yes, I think it's what is exposed as the "problem" in the issue.

**Comment by kaylarep** [comment]
+1 on this. We had another request from an initiative who would like to be able to contact their financial contributors directly in order to send out customized 'Thank you' emails.
