### ISSUE TITLE
Show events in menu

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3416]
## User story 
As a collective admin/event organizer, I should see my events listed in the menu to easily find them.

![image](https://user-images.githubusercontent.com/1556356/90758097-c8574100-e2de-11ea-98bc-f0debc125c1c.png)

## MVP

Add a new `My Events` section in the user menu.

**Comment by znarf** [comment]
It would overload the menu I'm afraid.

**Comment by Betree** [comment]
@znarf We could display it only if you actually have events in there, and filter out the expired ones. The div is scrollable, so it shouldn't be a huge pain (compared to having to search for your event by navigating).

**Comment by znarf** [comment]
@Betree It's a good idea to display only the active Events.

**Comment by alanna** [comment]
> It would overload the menu I'm afraid.

I think this is another case where we as team members are edge cases. Most people only have one or two things in their menu. It could be interesting to look at the stats for that - I think the menu can very comfortably handle 10 items, and I'd be shocked if more than a tiny percentage of our users have 10 or more right now, so adding events should be fine. I have 50+ items in my own menu and it's actually still totally usable and good.
