### ISSUE TITLE
Wrong behavior after changing slug

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3418]
## Problem
I changed the slug of [this Collective](https://opencollective.com/di-research-grants).

After clicking `save` I got a permissions error, because now the old slug doesn't exist and I'm not an admin of that non-existent Collective.

I refreshed and got a 404, because the URL was still set to the old non-existent one.

## Expected behavior
After changing the URL slug and clicking `save` it should send you to `https://opencollective.com/NEW-slug/edit` instead of `https://opencollective.com/OLD-slug/edit`.

If someone does land on a restricted page (e.g. /edit) of a non-existent URL slug, it should give a 404 not a permissions error.

**Comment by Betree** [comment]
Duplicate of https://github.com/opencollective/opencollective/issues/3314, the fix is about to be merged

**Comment by Betree** [comment]
Fixed with https://github.com/opencollective/opencollective-frontend/pull/4875
