### ISSUE TITLE
Can't add TestCollective to Fiscal Host

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3419]
I'm trying to add TestCollective to a host so I can test stuff, but I get this error no matter which host I try.
<img width="1242" alt="Screen Shot 2020-08-21 at 2 26 03 PM" src="https://user-images.githubusercontent.com/5498878/90845540-5c4a0b00-e3ba-11ea-8822-b0c0c9eaf565.png">

I tried this with a different Collective and it worked fine, so I think it's just an issue with TestCollective, but whatever it is, the error should probably show something more useful and we should make sure it's not a situation users could get into.

**Comment by znarf** [comment]
Not reproducing today (with same collective but different User and different Host).

**Comment by znarf** [comment]
Closing this as stale.
