### ISSUE TITLE
Feature: CORS or JSONP for sponsor.json & backer.json

### ISSUE THREAD

**Issue by Saturate** [OpenCollective/OpenCollective#342]
It would be really useful for projects to have the ability to show off whos supporting the project.

This could be done in a very elegant way, with access to the following files:

https://opencollective.com/gulpjs/sponsor.json
https://opencollective.com/gulpjs/backer.json

Allowing JSONP or even better CORS for these two resources, would allow projects to use the data and display backers and supporters.

It could be needed to solve this issue:

https://github.com/gulpjs/gulpjs.github.io/issues/51

**Comment by phated** [comment]
👍  on enabling CORS. @xdamman would it be quick to enable it?

**Comment by Saturate** [comment]
Maybe CORS could be defined on project level, and project admins could set the project site. So for `https://opencollective.com/gulpjs/*.json` the CORS setting could be `Access-Control-Allow-Origin: http://gulpjs.com`

This would make it a bit harder to implement I guess, but also make it a bit more strict if that's what we are aiming for.

**Comment by xdamman** [comment]
I don't see any reason not to allow any domain to access those endpoints. I made a PR (see above). I'll let you know when it's live.

**Comment by phated** [comment]
Awesome. Thanks @xdamman and @asood123!

**Comment by Saturate** [comment]
Awesomely fast, thanks ya' all!

**Comment by xdamman** [comment]
It's now deployed:

    curl -I https://opencollective.com/gulpjs/backers.json

```
HTTP/1.1 200 OK
Date: Wed, 19 Apr 2017 20:42:13 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 7147
X-Powered-By: Express
Access-Control-Allow-Origin: *
```
