### ISSUE TITLE
Magic log in link has no expiry.

### ISSUE THREAD

**Issue by yase01** [opencollective/opencollective#3421]
URL: 
Logged in as (username or profile URL): Admin (request a magic link log in)
Error message if any:
Expected result: Old magic log in link is still valid
Browser: Firefox, Chrome

Steps to reproduce:

1) request a magic log in link
2) Log out
3) Request again a magic log in link
4) Log out again
5) Access/used the old magic log in link to Log in again

Impact:

Old magic log in link still valid.

Attach here is the my old magic link :

[REDACTED]

Have a great day.

**Comment by znarf** [comment]
I double checked and this should not be possible, a Sign In link is only valid once and can't be reused.
