### ISSUE TITLE
Event page should say 'event' not 'collective'

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3423]
It should say 'support this *event*.'
<img width="656" alt="Screen Shot 2020-08-23 at 9 55 35 AM" src="https://user-images.githubusercontent.com/5498878/90966473-d9928e80-e526-11ea-943f-d65f9c5089ff.png">

**Comment by Betree** [comment]
This is a generic string used for all account types (Event, Collective, Project). We can add conditions to make sure it displays the proper type, but the simplest for internationalization would be to have. 

> Make a custom one time or recurring contribution to support this initiative.

Would that work?

**Comment by alanna** [comment]
Just delete "to support this initiative" and make it say "Make a custom one
time or recurring contribution."
