### ISSUE TITLE
Contribution flow: can't add custom amount on free tickets

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3426]
**Describe the bug**
On the contribution flow, when trying to add a custom amount on a free ticket, the payment step is not displayed so your contribution fails ("No payment method provided").

**Expected behavior**
Payment step should be displayed.

**Comment by znarf** [comment]
As stated in https://github.com/opencollective/opencollective/issues/3424#issuecomment-678961194 I think this is a non-issue because in this case the amount should not have been editable. Root issue should be solved by https://github.com/opencollective/opencollective-frontend/pull/4902

**Comment by Betree** [comment]
I just tried and everything works fine in the latest version of the flow:
- With a **fixed** free tier, you cannot set an amount an the payment step doesn't appear
- With a **flexible** free tier, it only appears if you enter an amount, and it works if you submit without one
