### ISSUE TITLE
Events: can't edit core contributors

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3427]
**Describe the bug**
In the events settings, there's no menu entry to `Core Contributors` so people can't add admins for them.

**Expected behavior**

Either:
- We don't want people to edit the core contributors at the event level, we should then display a link to the collective settings.
- Or it's ok, and then we should just enable the section.

**Comment by Betree** [comment]
@znarf What's your opinion about the `Expected behavior`?

**Comment by znarf** [comment]
Out of simplicity, it was decided to say that Admins of an Event are the Admins of the parent Collective.

If we expose additional Admins for a given Event, it's becoming complicated to understand who has admin capacities.

Otherwise, I don't have strong opinions, I just want something that is clear to understand.

**Comment by Betree** [comment]
So maybe we should go with the second option, displaying the `Core contributors` tab in the event settings with a simple message and a link to edit the parent collective members. @alanna WDYT would have been the best option in the context of what you reported in https://github.com/opencollective/opencollective/issues/3424?

**Comment by alanna** [comment]
I think it's OK to keep it simple, and just make admins of the Collective the admins for its events. We can probably solve this with a design/UI fix as @Betree is suggesting. We just need to make sure that if someone is in their event settings looking to add an admin, it clear what they need to do, and that making someone an admin applied to the whole Collective and all its events.

**Comment by Betree** [comment]
There's also a behavior inconsistency that we'll need to solve (eventually in another issue), I haven't tried yet but because `Core Contributors` (`MEMBERS`) have the permission to create event I think that we're exposed to this issue:
- As a Core Contributor (not ADMIN), create an event
- You're now an admin of the created event
- There's no way to remove you from the admins of the event

Should we:
- Not let core contributors create events (sounds logical to me, but some users rely on it)
- Not have the event creator added as an admin (there will be some side effects I'm afraid)
- Let you edit the admins in this situation
