### ISSUE TITLE
Avatar does not show in donation card

### ISSUE THREAD

**Issue by jjavierdguezas** [opencollective/opencollective#3428]
**Describe the bug**
Yesterday I created a new account and set up an avatar. Then I made a donation.
I can see my avatar everywhere except on the donation card. I thought it was a cache problem, but 24 hours later I can't see the avatar yet. I even set the avatar again and nothing happens. At this time a default "JZ" avatar is displayed, however the avatar of other contributors does appear.

**Expected behavior**
The avatar should appear everywhere

**Screenshots**
This is my profile (https://opencollective.com/jjavierdguezas) and you can see the avatar
![image](https://user-images.githubusercontent.com/13673443/91036593-e89d3d80-e607-11ea-9ca7-714100f5cb32.png)

Now in the page of my contribution (https://opencollective.com/responsively) a "JZ" avatar appears instead
![image](https://user-images.githubusercontent.com/13673443/91036659-08346600-e608-11ea-91f3-dd5ff3378916.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome & firefox
 - Version: 83.0.4103.116 (Official Build) (64-bit) & 79.0 (64-bit)

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: Android X
 - Browser chrome
 - Version: 84.0.4147.125

**Comment by znarf** [comment]
Thank you for the report. Seems a duplicate of https://github.com/opencollective/opencollective/issues/3210

**Comment by jjavierdguezas** [comment]
It is working now, thanks @znarf 
![image](https://user-images.githubusercontent.com/13673443/91189283-8d944500-e6f2-11ea-95f8-b0e490bb4d8b.png)

Closing this issue
