### ISSUE TITLE
Profile links don't map to correct avatars (on Webpack repo)

### ISSUE THREAD

**Issue by yeskunall** [OpenCollective/OpenCollective#343]
Hey, you wonderful people! :wave:

At the request of @bebraw, I'm opening this issue here, as we both believe you guys are the right people to come to for this sort of thing. To expand on the issue, the links to the indiviudal backers under the [backers](https://github.com/webpack/webpack#backers) section on the `webpack` repo do not seem to be working properly. It looks like every link after the first backer is offset by 1 (as far as I can tell)

Any idea why this might be happening? Thanks in advance!

**Comment by asood123** [comment]
It's a GitHub cache issue. The links get updated right away but github image caching takes a littl while. If you wait a bit, it'll fix itself. And if you know of a way to fix it, we are all ears :).
