### ISSUE TITLE
Contribution flow: logged out path

### ISSUE THREAD

**Issue by JelF** [opencollective/opencollective#3434]
## User story 
_I wish to donate minor amount of money without registration_

## Best solution for this problem
_Allow donations without registration_

## MVP
_Add a tab at https://opencollective.com/browserslist/donate for anonymouse donations_

## Metrics 
_Amount of money donated this way and possible decrease of amount donated with registration_

**Comment by Betree** [comment]
Hi @JelF, the ability to contribute without signing in is planned in https://github.com/opencollective/opencollective/issues/3164 but we didn't have a dedicated issue to track it, so let's use this one.

**Comment by Betree** [comment]
This was done in the latest contribution flow update. There are some limitations, since we still ask you to register for recurring contributions (an update for this is already planned)
