### ISSUE TITLE
Contribution flow revamp: Success page enhancements

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3436]
See https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC.com%5D-Production-Ready-%E2%9C%85?node-id=4489%3A3180

- [ ] Implement bank transfer view

![image](https://user-images.githubusercontent.com/1556356/91442598-62386400-e872-11ea-810b-c9418d7aeef5.png)

**Comment by sbinlondon** [comment]
Also to do:

* Functionality to edit message again from the comment box
* Error displaying for any data errors

**Comment by Betree** [comment]
There's also an issue with long names here, I suggest looking at the `truncateOverflow` prop

![image](https://user-images.githubusercontent.com/1556356/91547513-5311ee80-e924-11ea-9884-64067765b191.png)

**Comment by Betree** [comment]
`Discover more Collectives like ...`  should be a link
