### ISSUE TITLE
Improve host onboarding flow

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3437]
I just updated the [docs page about creating a host](https://docs.opencollective.com/help/fiscal-hosts/create-a-fiscal-host), and it's very messy and unintuitive. There are like five different ways to create a host and none of them are straightforward.

The settings update and host dashboard project @Memo-Es is working on will help a lot, but I think he should also look at the host onboarding flow experience itself from a design perspective.

Myself and @piamancini have experienced that onboarding a new host usually needs our direct involvement and we have to hold their hand. This indicates the process could be improved a lot.

**Comment by alanna** [comment]
@Memo-Es do you have another issue for this?

**Comment by Memo-Es** [comment]
Closing this issue in favor of #3758
