### ISSUE TITLE
Redesign the page to edit tiers

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3438]
The tiers page has a lot of issues. To name some of them:
- Error messages are unclear (https://github.com/opencollective/opencollective/issues/2953)
- Related to the previous, there are no frontend validations. So if something's wrong, it's up to users to find the error source.
- The form is pretty complex, with more than 10 fields. The UI doesn't tell you which ones are required or not.
- It's using a legacy design, with libraries that are deprecated in our codebase (#3223)

![image](https://user-images.githubusercontent.com/1556356/91531103-85175680-e90c-11ea-9805-b6b506184970.png)

## Best solution for this problem
We need a redesign of this page, that we'll implement as a new one using latest best practices:
- Formik
- GraphQL V2
- https://github.com/opencollective/opencollective/issues/1451

**Figma file:**
- [Tier cards design](https://www.figma.com/file/9Iq3vBOmZ2EuOacXEYD5yK/DS-03-Global-Components?node-id=6253%3A84) 
- [Page to edit tiers](https://www.figma.com/file/eBwSvsJztTIIxoivPzz9pV/OC.com-03-Admin-Panels-%E2%9D%8F?node-id=2252%3A58137)

## Documentation 
We'll need to update https://docs.opencollective.com/help/collectives/tiers-goals#tiers

**Comment by Memo-Es** [comment]
### Design update
---

Proposal to add a custom tier through the settings page

| 1. Add new tier CTA  | 2. New custom tier form  |
|---|---|
| ![Large (Desktop)](https://user-images.githubusercontent.com/49539954/97377651-23c92080-1886-11eb-8671-811088a8b88a.png)   | ![Large (Desktop)-1](https://user-images.githubusercontent.com/49539954/97377645-20359980-1886-11eb-83d5-4cfdcef51012.png)  |

@Betree

**Comment by alanna** [comment]
Visually this is a big improvement @Memo-Es - looking good!

Some notes...

* I don't like how the 'custom contributions' thing is handled. It's way too complicated, and we shouldn't need all that text to explain how it works. Just make the default and only tier when someone creates a new Collective the custom contribution tier, fully editable, and allow Collectives to treat it like any other tier, including deleting it. Then we won't have to explain it or visually make it different or anything. Right now "enable custom contributions" as designed makes it look like you tick that box to then enable the admin to create custom tiers, but that's not what it means.
* We can have the action be simply `add tier` instead of `add new custom tier` - all tiers are customizable by the admin.
* What is the purpose of the pre-set tier types? Donation, membership, etc? If they select one of those, they can change all the settings anyway, right? I don't see the need for that. Just let admins create whatever tiers and call them whatever they want and change their settings to be what they need, including recurring or one-off, limited numbers, specific amounts, or to have local tax apply.
* Change `force standalone page` to just `standalone page` - forcing sounds violent. Also add a link from here to the docs page about it, because it's not too clear what it means to users who haven't seen one. If someone is trying to set up a mini-crowdfunding campaign and would like a standalone page, I'm not sure they'll realise this is how to do it.
* Suggested amounts for flexible tiers are missing? Or is it just this example only shows a fixed amount?
*The default name should be something we will be happy for them to use if they don't change it. `New Generic Tier` is not a good choice for this. The word "generic" has negative connotations in English. I suggest the default name for a generic tier is `Contribution`. 
* We should have default button text instead of a blank box, so they can leave it if they don't want to customise. It should be `Contribute`.

**Comment by Betree** [comment]
> What is the purpose of the pre-set tier types? Donation, membership, etc?

Those are really important for us to categorize the contribution type, especially for taxes (VAT, GST) that will apply only on certain types (tickets, products, services but not donations).

**Comment by Betree** [comment]
> I don't like how the 'custom contributions' thing is handled. It's way too complicated, and we shouldn't need all that text to explain how it works. Just make the default and only tier when someone creates a new Collective the custom contribution tier, fully editable, and allow Collectives to treat it like any other tier, including deleting it. Then we won't have to explain it or visually make it different or anything. Right now "enable custom contributions" as designed makes it look like you tick that box to then enable the admin to create custom tiers, but that's not what it means.

I agree with this, it's the main reason why I specified https://github.com/opencollective/opencollective/issues/3055 that was intended to achieve that. I closed it because the complexity/benefit balance didn't seem right, but on the long term "Custom contribution" being treated as just another tier should really simplify things when it comes to customizing your ways to contribute. I'll re-open it, though **I think we should treat it as a separate project** because of the complexity.

---

@Memo-Es From the design, I don't see how to edit a tier?

**Comment by Memo-Es** [comment]
### Design update
---

| Contribution tiers tab  | Create/Edit tier modal  | Edit tier mockup  |
|---|---|---|
| ![Large (Desktop)](https://user-images.githubusercontent.com/49539954/100423129-2075b000-3051-11eb-9f74-877ef7c90052.png)  | ![Generic](https://user-images.githubusercontent.com/49539954/100423141-253a6400-3051-11eb-8f94-968e922e5974.png)  |  ![Large (Desktop)-1](https://user-images.githubusercontent.com/49539954/100423127-1eabec80-3051-11eb-91ca-1a1916448f51.png) |

New update considering the latest feedback [here](https://github.com/opencollective/opencollective/issues/3438#issuecomment-717650877) and [here](https://github.com/opencollective/opencollective/issues/3438#issuecomment-734138270)

**Comment by Betree** [comment]
@Memo-Es the modal should be triggered when you click on a tier from this edit page right?

I love this modal proposal, the fact that it uses a modal allows for inline edition from other places. At some point we had a design of the collective page that included a pencil (edit) and a remove icon next to "Move":

![image](https://user-images.githubusercontent.com/1556356/100423876-0954b380-308d-11eb-936f-770e7b8d6f5c.png)

With that issue implemented, we should be able to add that easily!

**Comment by Betree** [comment]
@Memo-Es Some interesting feedback around standalone tier pages here: https://github.com/opencollective/opencollective/issues/3774

**Comment by Betree** [comment]
@Memo-Es We should add something to enable/disable "flexible contributions" and "cypto contributions" somewhere on the page

**Comment by alanna** [comment]
Could reordering tiers be part of this? Users request it

**Comment by Betree** [comment]
@alanna Re-ordering tiers already exist, you can drag & drop them from the collective page

![image](https://user-images.githubusercontent.com/1556356/151768522-f87be0c2-2757-494e-b0c2-a3516f0caeed.png)

**Comment by alanna** [comment]
Ah sorry I missed that

**Comment by Betree** [comment]
An interesting feature on Github sponsors: you can have drafts for tiers that are only displayed once published

![image](https://user-images.githubusercontent.com/1556356/163129334-31c7194e-0571-4399-86bf-2d06cbb2ad1e.png)

**Comment by BenJam** [comment]
May also need to consider #5418

**Comment by BenJam** [comment]
While I'm here I just wanted to point out that the case for investing some time in tiers is there in terms of usage: https://opencollective-metabase.herokuapp.com/dashboard/116-tiers

![Screenshot 2022-07-06 at 11 21 40](https://user-images.githubusercontent.com/158833/177529221-f683837f-ad3a-4efa-a465-e088252af22c.png)

**Comment by BenJam** [comment]
seems to me like there's a good level of understanding what the challenges are here and what the proposal for development looks like. @Memo-Es how do you feel _today_ about the design from back in 2020, looks to me like it could drop right in...

**Comment by BenJam** [comment]
reviewed design from two years ago and @aminakazi already updated. Designs are pretty much ready. 

- @Betree and @SudharakaP to discuss working on the skeleton

**Comment by aminakazi** [comment]
**Week 2 Update:**
Designed and updated the form according to the new requirements.

**Week 3 Tasks**

- [ ] Hand over production-ready files to the dev team (@aminakazi)
- [ ] Dev team to set up the base for breaking up the design into bounties.

**Comment by BenJam** [comment]
- [ ] @Betree and @SudharakaP to talk through building the framework for bounties to build onto.

**Comment by BenJam** [comment]
update tomrrow

**Comment by Betree** [comment]
We haven't started working on this project yet. We'll try to have it for the week.

**Comment by aminakazi** [comment]
The updated production-ready file can be [found here ](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=13426%3A217743).

**Comment by Betree** [comment]
# Current status
:arrow_right: Testing in dev environments (local, staging) & iterating.
Slack channel created on https://opencollective.slack.com/archives/C044GNQ7WBX.

We have the tiers list working:
![image](https://user-images.githubusercontent.com/1556356/193209527-0250e88a-2ee3-4070-8306-8a1618a98cf8.png)

@hdiniz added the ability to create a new tier, with proper validations and instant preview:
![Peek 2022-09-30 09-03](https://user-images.githubusercontent.com/1556356/193210795-cb0bdca7-73b8-40df-9f9e-8bf81c0c7d75.gif)

This form also supports editing:
![Peek 2022-09-30 09-06](https://user-images.githubusercontent.com/1556356/193211400-3e004b90-46f9-4d93-a288-d5fe798f12de.gif)

# Next steps
We have documented some issues we need to iterate on in this [Slack thread](https://opencollective.slack.com/archives/C044GNQ7WBX/p1664521259527539). We're also looking into https://github.com/opencollective/opencollective/issues/5947.

Once we're happy with the resolution of this feedback, I think we'll be able to roll it out for a larger audience. I suggest doing so in 3 phases:
1. Enable the `Tiers (New!)` admin section for the core team & trusted partners. Collect feedback for at least two weeks.
2. If we're confident enough that it's non-breaking, hide the old `Tiers` menu entry and make the new one the default. This release should be synced with @opencollective/documentation to make sure we update our docs at the same time.
3. After a few weeks, remove the legacy tier page

**Comment by BenJam** [comment]
prepare for next steps

- docs
- release and feedback issues

**Comment by Betree** [comment]
Let's make sure we close the following issue when we release this:
- https://github.com/opencollective/opencollective/issues/3263
- https://github.com/opencollective/opencollective/issues/3531
