### ISSUE TITLE
Correct Updates info for Hosts

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3442]
This is how the Updates settings page looks, but it's geared toward Collectives. For hosts it needs to have different info.

<img width="837" alt="Screen Shot 2020-08-30 at 4 30 15 PM" src="https://user-images.githubusercontent.com/5498878/91651230-3caf9280-eade-11ea-9e52-542456572482.png">

Suggested content:

> Updates are a way to keep your community posted on your progress. They are sent by email to admins of your Collectives and to your team members and contributors. Once enabled, a new "Updates" section will be added to your profile page and a dedicated page will be created on https://opencollective.com/foundation/updates.

FAQ's

> Who can see updates?
> Updates can be public or private. Public updates can be seen by anyone who visits your Host page. Private updates can only be seen by [who??]. Whenever you post a new update, you can define whether it should be public or private.

*If someone contributes directly to a host budget, do they get access to private updates? Team members of Collectives hosted by this host org should be able to see its private updates, right?*

> Who gets a notification when there is a new update?
> All contributors to the Host itself and the team members of Collectives it hosts will receive a notification by default. They can easily unsubscribe with one click.

> Who can post an update?
> Only the administrators of this Host can post updates.

> What should we use updates for?
Updates are great to keep your community up to date. They should preferably be low volume (such as once a month, or for only important changes to policies and big news).

**Comment by Betree** [comment]
I've updated https://docs.opencollective.com/help/collectives/communication with the latest info about host updates.

Hosts can select if they want to send their updates to their financial contributors or to their collectives when publishing them.

> If someone contributes directly to a host budget, do they get access to private updates? Team members of Collectives hosted by this host org should be able to see its private updates, right?

Private updates are not supported for hosts yet (because we need a different set of permissions if it's published as "send to Collective admins").

**Comment by alanna** [comment]
OK, great! I don't think hosts really need private updates. It just needs to be clear to them who will receive notifications, and I think it is now.

**Comment by alanna** [comment]
@Betree is this done?

**Comment by Betree** [comment]
It hasn't, I delayed because this page is meant to be removed (in favor of the "Profile page" settings) but I'll fix it now since it's still there
