### ISSUE TITLE
Content Spoofing

### ISSUE THREAD

**Issue by supr3mo** [opencollective/opencollective#3444]
**Describe the bug**
Content spoofing, also referred to as content injection, “arbitrary text injection” or virtual defacement, is an attack targeting a user made possible by an injection vulnerability in a web application. When an application does not properly handle user-supplied data, an attacker can supply content to a web application, typically via a parameter value, that is reflected back to the user.

**To Reproduce**
Just browse this link: https://opencollective.com/signin/sent?email=**CONTENT%20SPOOFING**
(you can also edit the content by changing the content on email parameter.

**Screenshots**
![cs](https://user-images.githubusercontent.com/52335698/91718889-dd797d00-ebc6-11ea-8b79-f039588eb54c.png)

**Comment by Betree** [comment]
Hi @supr3mo, thanks for taking the time to report this issue.

While you can indeed inject content via this parameter, it's also properly sanitized so there's no proof of a possible XSS injection. As a result, we don't consider this one to be a security issue.

As per https://github.com/opencollective/opencollective/blob/master/SECURITY.md, security reports must be sent to security@opencollective.com. Public reports like this one are not eligible for bounties. A clear explanation of the possible implications is also required.
