### ISSUE TITLE
New Expenses dashboard experience - issues to look at

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#3445]
**Review of things to be addressed on the new expenses dashboard**

The following are some of the things noticed - majority of them are rather small but can impact the user experience. Others, do require more immediate attention. 

1.  The filter option for payout options does not always work. On occasions, an error message is received. An investigation into the source of the problem shows the following

![Capture](https://user-images.githubusercontent.com/57156267/91772637-6204e380-ec39-11ea-81d8-6a20e7b369d9.JPG)

2. The balance in Transfer Wise is not doing the conversion to cents correctly. So if the balance available is $95.556.01, what is showing on the dashboard is $955.56. 

3. When an expense is processed for payment, the status changes to Paid, however it is not automatically cleared out of the view and user has to refresh the page in order for it not to be showing. This is happening when the status of the expense is filtered to be showing Ready to Pay expenses only

4. Attachments are showing as "receipts" regardless of what their actual status is and this should be either changed to "attachment" for general reference or indicate the right type of document. 

![image](https://user-images.githubusercontent.com/57156267/91772997-06872580-ec3a-11ea-819e-b530d9142983.png)

5. Previously there was an option for the user name to show when hovering over their avatar. This was really useful to check the match around the personal details between the expense they submit and the attached documents. This is not available now, and in order to check it, the user needs to access the information elsewhere, adding one more step to the review process.

6. On some occasions when processing a bank transfer, the payment wouldn't update straight away. The good thing is that when trying to click on the ay button user gets notified that expense has already been paid. But status does not change and it is quite confusing (it will update once the page was refreshed).

**Comment by Betree** [comment]
> The filter option for payout options does not always work. On occasions, an error message is received. An investigation into the source of the problem shows the following

This one was a network error. I've made some changes to improve the error messages and make sure the page doens't crash.

> When an expense is processed for payment, the status changes to Paid, however it is not automatically cleared out of the view and user has to refresh the page in order for it not to be showing. This is happening when the status of the expense is filtered to be showing Ready to Pay expenses only

That was initially implemented this way so that you can quickly go back to the expense if there's something wrong or if you need to check something afterward. I've made the change for them to disappear after processing.

All the other items have been fixed, mostly in https://github.com/opencollective/opencollective-frontend/pull/4986

**Comment by alinamanko** [comment]
Fantastic - thank you so much @Betree!

**Comment by Betree** [comment]
Fixes have been deployed

**Comment by Hmawn** [comment]
#4335

**Comment by Hmawn** [comment]
#3445
