### ISSUE TITLE
Can't pick payout method (CSS issue)

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#3447]
e.g. https://opencollective.com/bienfaiteurs/expenses/new

I've also heard other people complaining about that for https://opencollective.com/allforclimate-uk

<img width="864" alt="Screen Shot 2020-09-01 at 11 25 00 AM" src="https://user-images.githubusercontent.com/74358/91832544-d5145700-ec45-11ea-8ce5-9f1cc90d3f86.png">

**Comment by Betree** [comment]
@xdamman This issue should have been fixed yesterday (https://github.com/opencollective/opencollective-frontend/pull/4980). Is the screenshot newer than that? I can't reproduce in production

**Comment by Betree** [comment]
Closing as I believe this was fixed at the time of report. Feel free to re-open with more details if that's not the case.
