### ISSUE TITLE
Feature: Allow collectives to distribute funds to other collectives directly from their account

### ISSUE THREAD

**Issue by gusaus** [opencollective/opencollective#345]
I believe this can be done manually, but I'm not sure a collective or supercollective can sponsor or contribute to another collective directly from their page. A few example scenarios:

- Supercollective allocating funds to other collectives (for example [Open Source Collective](https://opencollective.com/opensource) allocating funds to [Maintainer Mountaineer](https://opencollective.com/maintainer), [OpenProducer](https://opencollective.com/openproducer) and other collectives to spend time on the OpenCollective project and community).
- Collective allocating funds to a supercollective (for example a collective allocating funds to [Open Source Collective](https://opencollective.com/opensource) that would go towards work on OpenCollective project and community).
- Collective allocating funds to another collective (for example [OpenProducer](https://opencollective.com/openproducer) allocating funds to [Maintainer Mountaineer](https://opencollective.com/maintainer) for services).

Ideally the collective allocating funds would appear as sponsor or contributor on receiving collectives page.

Is it possible to do any of this automatically?

**Comment by ghuntley** [comment]
* A successful open-source project is typically built upon the shoulders of other lesser known projects aka dependencies. These dependencies typically are more specialized (less eyeballs, less potential for financial support) whilst the projects that use them are generalized (more eyeballs, more potential for financial support).

**Comment by gusaus** [comment]
> A successful open-source project is typically built upon the shoulders of other lesser known projects aka dependencies. These dependencies typically are more specialized (less eyeballs, less potential for financial support) whilst the projects that use them are generalized (more eyeballs, more potential for financial support).

If you think of all the collectives on https://opencollective.com/opensource as 'dependencies', it looks like more than 1/2 have zero budget. 
![open source collective is on open collective 2017-04-20 17-02-17](https://cloud.githubusercontent.com/assets/113996/25257195/20bb6f9c-25eb-11e7-8ab5-901f2b0e5c6c.png)

Frame it differently and the [GoFundMe-like service for open source projects](https://venturebeat.com/2017/04/05/open-collective-is-a-gofundme-like-service-for-open-source-projects/) looks quite impressive:
![open source collective is on open collective 2017-04-20 16-57-35](https://cloud.githubusercontent.com/assets/113996/25257092/776ac2f8-25ea-11e7-9e8e-a4de051b68f0.png)

The latter should be a pretty easy, obvious sell for supporters of open source. If we take a more pro-active approach in directing resources (fundraising, marketing, events, social networking) to the Open Source Collective, it will enable more people to contribute to the OpenCollective project and community. That in turn should open up more options for directing resources to collectives in need.

**Comment by ghuntley** [comment]
Interesting @gusaus, in my case I want to support the projects that support me and have complete control of to specify a particular amount of money should be donated to a dependency that I nominate on behalf of the project.

**Comment by gusaus** [comment]
@ghuntley It's possible, but I believe the we still have to ask @piamancini to allocate funds. Not sure what needs to be done to automate the process.

**Comment by gusaus** [comment]
As mentioned in previous comments, I think directing and allocating funds through [Open Source Collective](https://opencollective.com/opensource) would enable more collectives and/or individuals to contribute to the OpenCollective project and community.

@piamancini touched on a potential approach in Slack when I asked if this was possible.

> we can do that yes, from the open source collective
> 
> An mvp would be, once we have the different tiers feature launched (like we do now for events tickets for example) [opencollective.com/sustainoss/events/2017](https://opencollective.com/sustainoss/events/2017) We can create different tiers for the different projects and the contributors that put them up can work on them as funding gets in
> 
> It's a way of also letting the community decide which of those features/projects gets done (by putting money in them) instead of centralizing the decision-making and/or using of a tool like co-budget for example

It would be great if we could further define how that would work.

**Comment by RichardLitt** [comment]
I'm a bit unclear on the process. [Maintainer Mountaineer](https://opencollective.com/maintainer) has a collective profile; but I don't think anyone knows how to interface with it or give it money to let us do our job for the payer's collectives. 

> Ideally the collective allocating funds would appear as sponsor or contributor on receiving collectives page.

This sounds good to me.

**Comment by gusaus** [comment]
I think #348 is related to some of the scenarios listed. 

What are the next steps?

**Comment by gusaus** [comment]
Regarding the idea of directing and [allocating funds through Open Source Collective](https://github.com/opencollective/opencollective/issues/345#issuecomment-300020372)...

With the events feature now live (https://opencollective.com/opensource#events), we should be able to create virtual or in-person sprints and events that support the OpenCollective project and community.

Seems like the only thing we need are some guidelines for those interested in coordinating or contributing to these types of events. 

Is this correct @piamancini @xdamman ?

**Comment by gusaus** [comment]
The following was @xdamman's response regarding a process for directing and allocating funds through [Open Source Collective](https://opencollective.com/opensource).

> We don't and sadly don't have the time for this at the moment. But feel free to experiment or see if others are interested

Per the 'thumbs up' in this issue and subsequent comments and discussions, there's definitely interest. It's not clear how a group could create events/sprints on behalf of OpenCollective or Open Source Collective without @piamancini @alannallama or someone else on the OpenCollective team managing. Possibly we appoint someone on our end to become 'core contributor' and work with the OpenCollective team?

**Comment by gusaus** [comment]
@xdamman Is https://github.com/opencollective/opencollective/wiki/Architecture#transactions related to the desired functionality described in this issue https://github.com/opencollective/opencollective/issues/345#issue-223180925? If so, will the collective allocating funds appear as sponsor or contributor on receiving collectives page?

**Comment by ghuntley** [comment]
@gusaus if `reactiveui` sponsors `xunit` (downstream dependency of ours) then I would expect `reactiveui` to show up on `xunits` collective as a backer.

**Comment by ghuntley** [comment]
Some updates @gusaus 

![image](https://user-images.githubusercontent.com/127353/31330446-3ca3a438-ad2a-11e7-9f78-f477af6a288d.png)

The user interface in v2 is opens up this as a possibility. Right now I have to create an "organization" - can you please add the ability to select an existing collective. ATM I'd love to donate a couple dollars a month as the collective "reactiveui" to https://opencollective.com/octobox/ and have reactiveui appear as a backer. Funds would come from the collective.

**Comment by piamancini** [comment]
v2 is set up for donations between collectives, we need to implement. but it's on the roadmap.
