### ISSUE TITLE
"Undefined" expenses in User Report

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3450]
Un-tagged expenses are appearing as "undefined" expenses in the monthly user report.

<img width="643" alt="Screenshot 2020-09-02 at 08 30 11" src="https://user-images.githubusercontent.com/806/91939777-b5893700-ecf6-11ea-85ad-2871b71197c4.png">

We should write "unclassified expenses" instead of "undefined".

**Comment by alob-mtc** [comment]
@znarf is it possible I take this up.

**Comment by znarf** [comment]
@alob-mtc It's a good one, feel free to take it.

**Comment by alob-mtc** [comment]
Alright, thank you @znarf

**Comment by Betree** [comment]
I think we should entirely remove the `in ...` part. We now have multiple tags per expenses, but the code only looks at the first one which is inaccurate. We can eventually implement a breakdown in another format later if we think it adds value.

**Comment by alob-mtc** [comment]
> I think we should entirely remove the `in ...` part. We now have multiple tags per expenses, but the code only looks at the first one which is inaccurate. We can eventually implement a breakdown in another format later if we think it adds value.

Make sense 👍
