### ISSUE TITLE
Redirect to the relevant page after accepting invitation

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3453]
## User story 
As a newly invited admin of a Fund/Collective/Organization, after I click `accept` I should be redirected to the page I just accepted the invitation from. 

Currently you click accept and then just stay stuck here:
<img width="502" alt="Screen Shot 2020-09-03 at 10 54 56 AM" src="https://user-images.githubusercontent.com/5498878/92045213-1aff2580-edd4-11ea-9ab9-20f0542d1e83.png">

**Comment by Betree** [comment]
There can be multiple invitations on this page, we should do it only if there's only one invitation as it could otherwise stop you while you're trying to confirm the others. Also, the collective name in there is a link so it's easy to move to the collective page.

**Comment by alanna** [comment]
OK, makes sense. I didn't realise it could be more than one on that page.
