### ISSUE TITLE
Automatically add http:// to the start of URLs for links in text editor

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3455]
## Problem
Just had a support request where a user got blocked because they thought the URL link feature of our text editor was broken. It turned out they were just putting in `example.com` instead of `http://example.com`. The box just turns red with no message about how to fix it, which is not helpful.

![url](https://user-images.githubusercontent.com/5498878/92167606-8f969a80-ee8e-11ea-85c1-b7da0050ec8d.png)

## MVP
Make an error message show that says "you need to add http:// or https:// to the start of the URL"

## Best solution
If a user puts in a valid URL that's just missing the http:// part, automatically add it for them and successfully input the link. This is how many other tools work and users expect it these days.

**Comment by Jeanluis019** [comment]
Is anyone working on this? I'd like to take it.

CC: @alanna @JoyLubega

**Comment by Betree** [comment]
@Jeanluis019 feel free to take it :slightly_smiling_face:

**Comment by sky0707-qq** [comment]
Hi ,may I know what is it about can anyone contact me to gave me a brief
idea

**Comment by alanna** [comment]
Is this done @Betree ?

**Comment by Betree** [comment]
> Is this done @Betree ?

There's a work in progress but it's not merged yet: https://github.com/opencollective/opencollective-frontend/pull/5533

**Comment by Jeanluis019** [comment]
Hi @Betree, what about the bounty? I see this is a bounty candidate

**Comment by Betree** [comment]
@Jeanluis019 Bounty candidates are issues we are considering for the bounty program, but a bounty is only active when there is ` bounty` tag along with a defined amount. We also post a message on issues that are concerned by bounties to make things explicit. To learn more: https://docs.opencollective.com/help/contributing/development/bounties

**Comment by Jeanluis019** [comment]
@Betree Got it. Thanks for taking the time to explain :D
