### ISSUE TITLE
Redirect to 404 after changing URL slug in profile

### ISSUE THREAD

**Issue by qw-in** [opencollective/opencollective#3457]
**Describe the bug**

When changing URL slug in profile edit (at `/<slug>/edit`), after saving a 404 page is displayed

**To Reproduce**
1. Go to `/<slug>/edit`
2. Change the `URL slug` field
3. Click save
4. See 404

**Expected behavior**
Correctly redirect to the new page at `/<new slug>/edit`

**Comment by qw-in** [comment]
Looks like [this](https://github.com/opencollective/opencollective-frontend/blob/9d8ff5ddd9b3c0a6dc76c7a489398d57e321f041/components/edit-collective/index.js#L73-L85) is likely the code in question

**Comment by znarf** [comment]
Interesting, this was supposedly fixed in https://github.com/opencollective/opencollective-frontend/pull/4875

**Comment by qw-in** [comment]
@znarf happened to me this morning, not sure if because it's a personal account that could change anything?

**Comment by qw-in** [comment]
https://github.com/opencollective/opencollective-frontend/pull/4875 introduced it as the following:
```js
if (Router.router.query.slug !== collective.slug) {
  Router.replaceRoute('editCollective', { slug: collective.slug });
```
Then later [here](https://github.com/opencollective/opencollective-frontend/commit/831928e789612b3f93524ddaead56d2da0c5c11c) was changed to:
```js
if ((eventSlug || slug) !== collective.slug) {
   Router.replaceRoute('editCollective', { ...Router.router.query });
```

Looks like the `collective.slug` is no longer being used in `replaceRoute`

---

Of minor note`(eventSlug || slug)` will have issues with falsy slugs (`'false'` for example)

**Comment by Betree** [comment]
@qw-in thanks for investigating this one, and good catch for the `(eventSlug || slug)`.
