### ISSUE TITLE
Don't automatically capitalize tier titles

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3459]
If you create a tier with a custom title, it overrides your capitalization choices and capitalizes every word. This is not the correct convention in English (it should be title case if anything), but anyway we should allow the user to make the choice themselves, and retain their capitalization in the displayed text string.

E.g. this user did not capitalize anything but the first word, but the whole tier title is capitalized.

![capitalized](https://user-images.githubusercontent.com/5498878/92361433-79b10000-f142-11ea-963e-b1a6244a42d3.png)

**Comment by Betree** [comment]
One problem is that all default tiers, "backer" and "sponsor", have been created lowercase since the beginning. It will not look good if we just disable capitalization. I think your other suggestion, using title case, should work better.
