### ISSUE TITLE
How to add a background to a collective

### ISSUE THREAD

**Issue by jancborchardt** [opencollective/opencollective#346]
I saw collectives with some cool background images and we’d like to have that for [Open Source Design](http://opensourcedesign.net) as well:
https://opencollective.com/opensourcedesign
I can’t seem to find an option to upload an image, so I suppose I need to ask you @piamancini @asood123? Otherwise let me know what I missed. :)

The image we’d like to use is the group picture we use on our Twitter too: https://cloud.jancborchardt.net/s/opensourcedesign-group – maybe we need to have the blur applied, since there’s a lot going on in that picture.

cc @simonv3

**Comment by piamancini** [comment]
hi @jancborchardt You can send the link to us and we'll update it. Can you blur it? I think we have an option to do it in the backend if not. I can check.

**Comment by jancborchardt** [comment]
Hey @piamancini, here’s the link to the blurred image: https://raw.githubusercontent.com/opensourcedesign/opensourcedesign.github.io/2ff99c063474e7f8b412dae1a8dbeacb6119e5fb/images/2017-fosdem-picture-compressed-blur30px.jpg – thanks! :)

**Comment by piamancini** [comment]
hi @jancborchardt updated!
