### ISSUE TITLE
[PROJECT] New contribution moderation and spam Q3/Q4 2020

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3461]
:rotating_light: :rotating_light: :rotating_light: **We want community feedback on this! Please read.** :rotating_light: :rotating_light: :rotating_light:

This is our main issues for discussion of the moderation project as a whole. If you have ideas for what you'd like to see relating to moderation on Open Collective, and it isn't mentioned in the issues linked in the **Roadmap & Timeframe** section, please comment here. For discussing specific goals/things we are implementing, please comment on those issues.

We also have the channel **#moderation-spam** on our [Slack](https://slack.opencollective.com/) for general discussion and urgent queries.

## Purpose

Moderation is an important part of any community or platform. At the beginning, many projects set out a code of conduct or community guidelines and moderation is dealt with in a manual fashion. But as platforms grow and attract a larger user base and the attention of a wider audience, it’s important to ensure that problems are dealt with as they arise and eventually anticipated and dealt with beforehand.

Open Collective is at particular risk as both a financial platform and as a platform based on transparency, making it a likely target for scammers, spammers, and those looking to take advantage. The Collectives we serve entrust us with both their money and their brands, and our success as a company depends on building and maintaining a reputation for safety, integrity, trustworthiness, and thoroughness.

Open Collective has had many ideas around moderation and implemented a few features (see opencollective/opencollective#2741), but largely moderation is still manual, is causing frustration for Collective admins, and has drawn attention to the platform negatively. It’s important to listen to this criticism and feedback; identify what we can do to improve the situation immediately and over the next few months; and realise that this will be an ongoing effort.

We need a plan that comprises:

* short term solutions (‘quick wins’) that will alleviate the worst behaviours as soon as possible
* medium-term solutions that will take a little more work but are also important to implement sooner rather than later
* and long-term solutions and thinking about how we want to shape the platform as a whole as we move forward. 

We want to work to keep our users’ trust, make it stronger, and grow through our reputation of having a strong community through effective moderation.

#### Guiding principles for this revamped moderation project

- We want Open Collective to be a platform that is trusted.
- We want Open Collective to have high friction for spammers and bad actors.
- We want Open Collective to have low friction for users to moderate their Collectives as much or as little as they want, with a variety of tools available to them.
- We want Open Collective to anticipate and be proactive about moderation needs going forward, rather than reactionary.

## Owner
@sbinlondon 

## Prioritization

- Does this serve our mission?

> We are on a mission to help collaborative groups collect and spend money transparently.

As @Betree mentioned in our original project, yes, moderation is an essential building block to help groups collaborate healthily. Putting these tools in the hands of our users will make their work and our platform more *sustainable* and *open*/welcoming to all.

- Will this help to make us financially sustainable within a year?

The direct impact of moderation on financial sustainability (in the sense of making money) is limited but if we lose our community's trust, then they will go elsewhere for what we are offering.

- Is it feasible to build and maintain with our team and runway?

As Ben mentioned before, we have a lot on our plate, but a lot of issues described here can be tackled incrementally. It's important to keep things well-scoped, drill down to the core of each idea, and implement it quickly but properly, and remember to iterate. This will never be 'done' so make sure we can constantly and consistently deliver and build on each previous block.

- Can this make us move faster?

While spam complaints/requests for support may not be the number one source of tickets in our support inbox anymore, a lot of the moderation work we do is still manual. Not only is it the right thing to do to empower our Collective/Host admins and users with tools themselves, but it will help the team move faster by automating manual moderation jobs, and help Collective admins do their jobs better by being able to focus on running a Collective instead of dealing with spam, etc.

- Does this increase quality and not technical debt?

This project should not create any technical debt and should help us automate some things that are done manually right now (like 'search and destroy' spam profiles). It will definitely increase quality of the platform.

- Will this bring us more Collective and financial contributors?

I believe that it would positively bring more Collectives and financial contributors to the platform. As Ben mentioned previously, not handling spam or offering good moderation tools can frustrate Collectives and drive people away and cause people to leave the platform. However, offering a platform where we allow Collectives and Hosts control over who can donate to their project, who is displayed on their websites in the sponsors section, who can interact with their Collective, etc... can positively raise our profile in the community via word of mouth and bring in people who want a platform they can trust.

- Is this already solved elsewhere or is it our unique contribution?

Not a unique contribution, but every platform has moderation needs - some universal, some unique - and we should work to solve them using a variety of ideas both original or adapted from other sites/platforms who are doing it well.

## Roadmap & Timeframe

Following the intro to this proposal there will be 3 separate sub-issues for our short-, mid-, and long-term goals that comprise this project.

* [New moderation project short-term goals/discussion](https://github.com/opencollective/opencollective/issues/3462): urgent priority, to be completed for our second Q3 sprint and beginning of Q4
* [New moderation project mid-term goals/discussion](https://github.com/opencollective/opencollective/issues/3467): high priority in relation to other issues, to be completed in Q3/Q4 2020
* [New moderation project long-term goals/discussion](https://github.com/opencollective/opencollective/issues/3475): medium/low priority in relation to other issues, to be discussed, scoped, planned, and implemented from the beginning of next year.

## Success metrics

- Fewer support requests regarding removing spam collectives/contributions
- Addressing long-time community feedback on moderation
- Increased trust in OC platform

-----------

# Extra context

## Community feedback and suggestions that influenced this proposal so far

Feedback from users via Twitter, Slack, and on our Github issues (some suggestions are duplicated as multiple people suggested similar things)

- Suggestion to remove the *incentive* for spammers by ‘no-follow’ links and other things. “Otherwise if you try to ban e.g. gambling in particular in the TOS, you'll just play whack-a-mole forever with various shady groups trying to do the same grift.”
- Request to block/reject sponsors: Tell x group “we don’t want your money”
- Suggestion to notify Collectives or OC when the linked website in a profile changes, to prevent spammers from looking legit at first and then changing their info. (Note: this should probably be explicitly against TOS anyways and grounds for banning?)
- Suggestion that OC should be involved in detecting ‘obvious’ spammers and denying any contributions by them. (Note: Ben’s ‘search and destroy’ already kind of does this in deleting obvious spammers but do we also block obvious spam contributions in between these monthly search and destroys?)
- Suggestion that Collectives should be able to toggle on/off whether they want to manually approve every single contribution that comes in, saying that most probably won’t care, but some will.
- Suggestion for feature where admins can reject/refund already-finalised sponsorship: “A way for a Collective to reject an already-finalized sponsorship, which would issue refund(s) and whatever else needs to happen in the database + being able to specify a reason for rejection is also going to be helpful (“offensive”, “spam”, etc), as this might improve the spam-detection heuristics.”
- Suggestion to rethink how we advertise sponsorships and what sponsors get from them, or for us to teach Collectives how to make this more explicit: “Another idea is moving away from automatically placing links and logos anywhere, and in fact discouraging this for Collectives. there wasn’t really any guidance given to Collectives insofar as what the tiers might want to look like and what “rewards” sponsors should get, if any.  {Collective} was one of the first Collectives, so maybe things have changed since. Some Collectives feel that donors should not expect anything “extra” in return, since they already get value from using the open-source product in the first place… I’m starting to lean this way for {Collective}, but other Collectives have contributors that are living on donations (e.g., {Collective 2} ) so they would want to maximize donations.”
- Disagreement that moderation should be down to Collective admins, or at least suggests that we should be considering more automated moderation tools for the future to reduce burden on maintainers: “Forcing Collectives to do this adds maintenance burden to - at least of your most successful and notable Collectives - groups that are already overburdened by maintenance. This ends up setting people up for failure and burnout since there'll inevitably be something that slips through or they'll have to have people actively monitoring it.”
- Second suggestion that in addition to blocking unwanted sponsorships from happening in the first place, there is also a way to renege on/refund previously accepted sponsorships.

## Spam and moderation tools already in place

- [“Search and destroy”](https://docs.opencollective.com/help/internal/jobs/search-and-destroy-spammers) obvious spam profiles
- No-follow links: while it isn’t our intention, it’s clear that some ‘spam’ contributions are likely made with the intent of boosting SEO through links. An easy way to make this an unattractive prospect for these kinds of users is to add ‘no-follow’ tags to profile links that go outside the opencollective.com domain, which is the only place that users can set external links. This has been done in the last few weeks. (opencollective/opencollective-frontend#4920)
- [Limiting accounts (manually)](https://docs.opencollective.com/help/internal/moderation): either all features (no comments, expenses, or contributions) or specific features
- Banning users/collective permanently (manual):  also prevents the same email from being used to sign up (see link above)
- Open Collective is notified if profile websites/etc are updated with suspicious or spammy info 
- Other various things implemented via the [previous moderation project](https://github.com/opencollective/opencollective/issues/2741)

**Comment by bnb** [comment]
I don't have a ton to add here since this issue has laid out literally everything with amazing accuracy, but I just want to say this is incredibly well written. Excited to see this progress ❤️

**Comment by sbinlondon** [comment]
**Small update:** the **"reject contribution"** feature is being released to production today. We will turn the feature flag on for a few Collectives who have told us they have a huge problem with spam contributions or contributions they'd rather be able to reject for any reason. After a bit of testing with these Collectives, we hope to release the feature more widely 🎉

**Comment by nmeyne** [comment]
Hi All!   I just wanted to point out that we at Resonate have a Community Credentials project (with funding from the EU) to help address the problem of proving identity and verifiability of credentials in public or restricted community fora, WITHOUT the unnecessary disclosure of too much information to an intermediary or third party, or the community platform itself.  We think we can do that through the simple metaphor of portable (cross-community) 'badges' and credentials that you keep in (your own) digital wallet. Badges might inform community trust levels.    We have a 'know your co-operator' proposal to enable sharing the effort of on-boarding ceremonies / checks across co-operative communities.  Here's a [draft press release](https://drive.google.com/file/d/1Ecmr-45OGAnRet0SvI-0fxYYgBBlyYlN/view?usp=sharing) that explains a little more.  Sorry if this is a red herring...  let me know if it's of interest?

**Comment by phated** [comment]
I'm not sure if this belongs here, but it's also worth noting that you need to add nofollow attributes to links in their "about" section on their profile. For example https://opencollective.com/casino-topp#section-about is abusing links there to get SEO.

**Comment by Betree** [comment]
> I'm not sure if this belongs here, but it's also worth noting that you need to add nofollow attributes to links in their "about" section on their profile. For example https://opencollective.com/casino-topp#section-about is abusing links there to get SEO.

@phated definitely. There's a work in progress about that in https://github.com/opencollective/opencollective/issues/3536

**Comment by sbinlondon** [comment]
> I'm not sure if this belongs here, but it's also worth noting that you need to add nofollow attributes to links in their "about" section on their profile. For example https://opencollective.com/casino-topp#section-about is abusing links there to get SEO.

Good catch @phated! Thank you for flagging it.
