### ISSUE TITLE
Moderation short-term goals

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3462]
To implement ASAP (second sprint of Q3, first sprint of Q4 2020)

This section is about what we want to implement in the next few weeks. Ideally, we’ll discuss what’s set out in this proposal, come up with a well-scoped MVP we are happy with releasing soon (but can iterate on to refine), and start implementation as soon as possible. For this reason the list is short and scoped.

### 1. Rejecting individual contributions _**(released to everyone)**_

As a first step, we want to allow Collectives to reject/refund a contribution that has been made, whether it’s because they see it as a spam contribution, or they don’t want that particular sponsor giving to their project for ethical reasons, etc. It’s been asked for repeatedly over many issues and by many people. Currently, Hosts can refund transactions but we want to allow this feature for Collective admins as well and also include a way for the admins to let a contributor know why the contribution is being rejected, if they feel like saying it.

Please see the specific issue for discussion on implementation: opencollective/opencollective#3463

### 2. Categorization system to allow Collectives and/or Hosts batch control over types of contributions to receive/not receive **_(limited testing release this week)_**

As mentioned in the recent discussion around moderation, we should work towards implementing a system that reduces the burden of individual Collectives/admins having to reject and filter contributions. We think this is an issue that should be discussed and implemented as soon as possible, so an MVP of this has been made a short-term priority.

Please see the specific issue for discussion on implementation: opencollective/opencollective#3466

### 3. Allow Collectives to ‘filter’ the sponsors they show on their website **_(in progress)_**

Some Collectives pull data from the Open Collective API or use our widget to display sponsors on their website. While we want to remain transparent on the Open Collective platform about the contributions going into a project, we understand that people want finer control over what they display on their own platforms/websites. We want to add a way for Collective admins to easily flag contributors or types of contributors to not display if they use our widget or pull data from our API.

Please see the specific issue for discussion on implementation: opencollective/opencollective#3465

### 4. Update ‘Moderation’ and ‘Community Guidelines’ documents to reflect our evolving approach to moderation **_(in progress)_**

Our [community guidelines](https://docs.openCollective.com/help/about/community-guidelines) are short, succinct, and warm and fuzzy. They might be good for a smaller project but Open Collective has grown a lot larger and evolved. In particular, the line about _“We believe in self-managing systems, so we don’t police or moderate much”_ might be ripe for updating. 

We’ve seen how people use Open Collective, and unfortunately how they abuse it as well, so we should start setting down some more explicit community guidance and [moderation rules](
https://docs.openCollective.com/help/product/moderation) based on what we’ve seen, what feedback we’ve been given (both pertaining specifically to Open Collective and based on what people think works well for other sites), and what we might expect in the future. 

We should make it more clear going forward what kind of behaviour we expect on Open Collective, what kind of behaviour we won’t accept, and what we will base our moderation decisions on. Ideally, we would have something like a conference code of conduct, i.e. [Women of React’s CoC](https://womenofreact.com/code-of-conduct).

Please see the specific issue for discussion on implementation: opencollective/opencollective#3464

**Comment by rickhanlonii** [comment]
What do you think about an even shorter term fix we could put in place to remove all incentives to spammers and inform them that they no longer get the benefits they're after? If there were no SEO benefits to adding links to sites, spammers wouldn't pay money for it:

- **Remove benefit via redirect**: Update the links returned from the OC API to return redirects instead of the raw URLs. Instead of returning `rickhanlon.com`, start returning `opencollective.com/redirect?to=rickhanlon.com` and setup the redirect to remove SEO benefits (this could be configurable per project/contributor longer term). With this, there would be no incentive to spam any Open Collective project.
- **Communicate the change**: Update the donation/checkout pages to provide a callout note says "Note: SEO benefits for Open Collective links have been removed. See here for more information". This tells the spammer that they're wasting their money at the point of purchase. Sometime later, once the change makes it way through the spammer network you could remove the notice.

**Comment by Betree** [comment]
As a simpler one that goes in the direction of @rickhanlonii's [comment](https://github.com/opencollective/opencollective/issues/3462#issuecomment-689147260), adding `rel=sponsored nofollow` on all contributors' websites links as it was proposed in https://github.com/opencollective/opencollective/issues/3465 is something trivial that could be considered for this scope.

**Comment by rickhanlonii** [comment]
@Betree yeah if you added `rel=sponsored` to the top `(n)` projects then you wouldn't need the redirect I mentioned, but if you did the redirect then all projects would get the attribute automatically without needing to update their scripts.

**Comment by sbinlondon** [comment]
I like the redirect idea and had no idea that was a thing we could do - really clever. Have mentioned it on the specific issue here: https://github.com/opencollective/opencollective/issues/3465#issuecomment-690261925

I'd be interest in hearing @piamancini's thoughts on communicating the SEO changes?

Also just to be clear @Betree we have already added `nofollow` on contributor's website links (via the profile page) with the `openInNewTabNoFollow` prop, though we could potentially also add `sponsored`.

**Comment by Betree** [comment]
> Also just to be clear @Betree we have already added nofollow on contributor's website links (via the profile page) with the openInNewTabNoFollow prop, though we could potentially also add sponsored.

All good! I think the `nofollow` is sufficient, I missed that we already added it :slightly_smiling_face:

**Comment by Betree** [comment]
I think everything detailed here is done. @znarf can we close?

**Comment by znarf** [comment]
@Betree Sure.
