### ISSUE TITLE
Ability for Collective admins to cancel/reject financial contributions

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3463]
[Previous issue for Host refund and discussion here.](https://github.com/openCollective/openCollective/issues/2006)

## User story 

As a Collective admin, I want to be able to refuse/cancel financial contributions so that I can have a say in who my project accepts money from and who shows up on my page as a contributor, and to combat backer spam.

## Best solution for this problem/MVP

Implementing the same 'Refund' button that Hosts have but for Collective admins.

On the Collective transactions page, when an admin clicks ‘show details’, we see a button for ‘Reject’. Clicking this button would refund the transaction, remove the member from the Collective, and potentially allow you to send a message to the contributor to let them know why you are rejecting their contribution.

For the MVP we would not also allow the Collective admin to block further attempts at contributions from a user. We plan to address this in some of the mid-term moderation goals, but also we don't think most users would continue to try to contribute again after being rejected. However, we will need to monitor this to see if it is a problem.

## Metrics 

We should receive fewer support requests from Collective admins asking to refund/reject contributions.

## Discussion

As mentioned in the team meeting, we need to discuss the finer points of what we do when Collectives reject long-time contributors, and what time limits there are on refunds.

Potentially related: [Refunding all contributions at once](https://github.com/opencollective/opencollective/issues/3011)

**Comment by sbinlondon** [comment]
MVP scoped proposal suggestion:

* Implement **'Refund'** and **'Reject'** on Collective page transactions section (as buttons here, perhaps add a 'View actions/details' drop down like on Host transactions)
<img width="1229" alt="Screenshot 2020-09-08 at 20 16 01" src="https://user-images.githubusercontent.com/37520401/92518420-3e7d0280-f210-11ea-8533-da84e97589fc.png">

* 'Refund' is exactly like the Host dashboard, it is only for mistaken transactions etc.
* 'Reject' is when you don't want the contribution.
* 'Reject' for new (first time) donors will: refund the transaction, remove the member from the Collective, and let you send a message as to why you are rejecting their contribution.
* 'Reject' for ongoing donors will: refund the transaction and let you send a message as to why you are rejecting their contribution, but it will not remove the member from the Collective. If there are multiple donations from a sponsor within 30 days you want to remove, for the MVP you would have to remove them each individually.
* Contributions older than 30 days can't be refunded/removed.

Potentially as an iteration after implementing these first steps, if a contributor has contributed multiple times in under 30 days, with no previous histoy, we can offer a checkbox to refund all transactions/remove member from the Collective when rejecting one contribution.

Removing ongoing sponsors from a Collective if they've been donating for a long time (longer than 30 days) then that's something we'll need to discuss the right way to implement, but not here in the MVP.

Thoughts? @znarf @Betree @piamancini @kewitz

**Comment by Betree** [comment]
> 'Reject' for ongoing donors will [...] not remove the member from the Collective.

Why not?

**Comment by znarf** [comment]
@sbinlondon missing is the "Cancellation" of the Recurring Contribution when rejecting.

Also, I think it would be generally useful for us to clarify the definition of "Membership", especially the `BACKER` role. What does that mean and  when is it ok to delete the entry?

In this case, I think we want 'Reject' to always delete the `BACKER` membership, whatever the case.

**Comment by sbinlondon** [comment]
> > 'Reject' for ongoing donors will [...] not remove the member from the Collective.
> 
> Why not?

I thought it would be more difficult, esp re: the 30 day thing if they're long-time contributors. Do you think it's ok for the MVP to implement removing the contributor from the Collective if their only contributions have been made within the last 30 days, even multiple ones?

> Also, I think it would be generally useful for us to clarify the definition of "Membership", especially the `BACKER` role. What does that mean and when is it ok to delete the entry?
> 
> In this case, I think we want 'Reject' to always delete the `BACKER` membership, whatever the case.

Yes you're right, sorry. I'll add `BACKER` to clarify!

**Comment by Betree** [comment]
So for sure we can't remove the past transactions, but removing the membership is technically ok. The interface will acknowledge that you contributed in the past (on the `transactions` page) but you'll be removed from the contributors.

One thing though: that also means that you won't be displayed on places like Top Contributors. But let's imagine that a company provides 90% of the budget of my collective, then I reject their last contribution, is that ok to remove them from the top contributors? We need to figure that out.

**Comment by sbinlondon** [comment]
> So for sure we can't remove the past transactions, but removing the membership is technically ok. The interface will acknowledge that you contributed in the past (on the transactions page) but you'll be removed from the contributors.

Ok, good to know the distinction. So if we can't remove transactions from showing, would we want to add a status like 'REJECTED', because I can imagine a case where say, Big Tech Co. makes a first contribution to Project X, Project X says 'we don't want your money' and rejects it, we remove the membership and refund but Big Tech Co. still shows up on their transactions list and they might be unhappy with that. Or would we be able to remove first-time rejected contributions from the transactions list? Or is that something for later on where we look at pre-approving transactions before they show up?

> One thing though: that also means that you won't be displayed on places like Top Contributors. But let's imagine that a company provides 90% of the budget of my collective, then I reject their last contribution, is that ok to remove them from the top contributors? We need to figure that out.

Agreed.

**Comment by Betree** [comment]
By default they will be displayed as "refunded". We can indeed add a "rejected" status on Orders, that's a good idea.

**Comment by sbinlondon** [comment]
Updated proposal:

- Implement 'Refund' and 'Reject' on Collective page transactions section
- 'Refund' is exactly like the Host dashboard, it is only for mistaken transactions etc.
- 'Reject' is when you don't want the contribution
- 'Reject' for a one-time donation will: refund the transaction and set the status to `REJECTED`, remove the membership of `BACKER` from the Collective so they won't show on contributors anymore, and let you send a message as to why you are rejecting their contribution
- Contributions older than 30 days can't be refunded/rejected
- Rejected transactions will be marked as such in the budget due to their status, since we can't remove transactions but people will want to show that they have rejected the contribution for whatever reason

I'm still slightly unclear on recurring contributions/multiple one-time donors. Are we saying that when we 'Reject' their latest contribution, we will refund/reject all their transactions for the past 30 days and then remove their `BACKER` membership from the Collective?

**Comment by znarf** [comment]
> we will refund/reject all their transactions for the past 30 days

Only the one where we pushed the button.

**Comment by sbinlondon** [comment]
And we would still remove their membership?

So what status would we display on their transactions that were not refunded/rejected, when they are no longer a member?

**Comment by Betree** [comment]
> transactions pull all money given to the Collective regardless of membership or not

Correct. Your transactions page will display all your transactions, regardless of the membership of the account who made it.

**Comment by sbinlondon** [comment]
Ok that makes sense. I think this is enough to make a start with 🎉

**Comment by sbinlondon** [comment]
Frontend

- [ ] add 'Refund' button for Collective admins (like for Host admins)
- [ ] create 'Reject' button and add it for Host and Collectives alongside 'Refund'
- [ ] add ability to display `REJECTED` status to transactions on the Collective page

API

- [ ] create Order status `REJECTED`
- [ ] create a `rejectContribution` mutation which refunds the transaction, removes the `BACKER` membership from the Collective, and emails the message to the rejected contributor if there is one

**Comment by Memo-Es** [comment]
Why we removed the `needs design` tag? @sbinlondon

**Comment by sbinlondon** [comment]
Sorry @Memo-Es will add it back. Let's talk when you're here on Tuesday.
