### ISSUE TITLE
Update ‘Moderation’ and ‘Community Guidelines’ documents

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3464]
Open Collective team is currently brainstorming what we would like to see in our updated community guidelines. This includes adding new guidelines, deleting some if necessary, updating ones where more details are needed, etc.

These will then be released with a blog post detailing our new guidelines and also details of our new moderation proposal and project.

@piamancini and I are collaborating on the guidelines but will give updates here for team and community feedback.

**Comment by natehn** [comment]
See https://github.com/opencollective/opencollective/issues/4928
