### ISSUE TITLE
"Create an Organization" Form update

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3468]
We are updating the design of the form to create an organization.

**Main goals:**
* Consistency in every flow where we allow users to create organizations
* Improved experience
* Force the creator to confirm of being a legit representative of that organization.

| **Previous design**  | **New proposal**  |
|---|---|
| <img width="1349" alt="Screen Shot on 2020-09-07 at 15-33-14" src="https://user-images.githubusercontent.com/49539954/92415671-af90bd00-f11f-11ea-98da-459762871e26.png">   | ![Create Organization - Desktop](https://user-images.githubusercontent.com/49539954/92415844-655c0b80-f120-11ea-89a8-551aeb36a86d.png) |

🎨 See the [design file](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=2375%3A2) in figma

Other related issues: #3278 

@Betree @piamancini @alanna

**Comment by sbinlondon** [comment]
This is a good feature to put up as a bounty. Whoever works on it can refer to code in our updated Create Collective Flow form and the onboarding modal (for adding the administrators). Will add additional specs later today.

**Comment by JoyLubega** [comment]
@Betree Is it okay, for this to be a bounty as @sbinlondon suggested. I would love to work on it.

**Comment by sbinlondon** [comment]
@JoyLubega I'm writing a spec for the bounty and then we will decide how much to attach to it, but when we do you are welcome to take it on.

**Comment by sbinlondon** [comment]
# Specs
## API
- [ ] update `CreateCollective` v2 mutation to include the field `website`

## Frontend
- [ ] create new components for `CreateOrganization` and `CreateOrganizationForm` following the [Figma design](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC.com%5D-Production-Ready-%E2%9C%85?node-id=2375%3A2)
- [ ] use the updated GraphQL v2 `CreateCollective` mutation to create the new org with the data from the form (see the current mutation in `components/create-collective/index.js`)
- [ ] use the information from the invited admins in `editCollectiveMembers` mutation found in `components/onboarding-modal/OnboardingModal.js` to add admins to the newly created org
- [ ] Update the current create organization E2E Cypress tests to cover the new components

---
Please follow our [code guidelines](https://docs.opencollective.com/help/developers/best-practices-and-code-guidelines), especially:
* The strings must be internationalized. See [/help/developers/translations](https://docs.opencollective.com/help/developers/translations)
* Whenever it's possible we must use `styled-components` to write styles. See [OC Styleguide](https://styleguide.opencollective.com/)
* We're getting rid of `Bootstrap`. Please don't use it for new developments.
* When adding new dependencies, we use [fixed versions](https://docs.npmjs.com/about-semantic-versioning).
* Icons must be imported from the [styled-icons](http://styled-icons.js.org/) library.
* Tests written with Cypress must follow our [good practices](https://docs.opencollective.com/help/developers/testing-with-cypress) conventions.

### Notes
* look at new create collective form code for inspiration (`/components/create-collective`)
* you can find 'invite co-admin' inspiration in the onboarding modal code (`/components/onboarding-modal`)

**Comment by sbinlondon** [comment]
:gift: :money_with_wings: A **$500** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $500 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by sbinlondon** [comment]
@JoyLubega Did you still want to do this? The specs are listed above - let me know if you have any questions.

**Comment by JoyLubega** [comment]
yes

**Comment by JoyLubega** [comment]
I am on it. thanks @sbinlondon

**Comment by JoyLubega** [comment]
@sbinlondon i need some more explanation about this section.
<img width="367" alt="Screenshot 2020-09-20 at 22 51 56" src="https://user-images.githubusercontent.com/29824008/93720808-1d170180-fb94-11ea-91e8-e43788a1179a.png">
I am thinking the avatar and admin only show after the user has added an email. Is it so>

**Comment by sbinlondon** [comment]
> I am thinking the avatar and admin only show after the user has added an email. Is it so>

You would not be able to create an organization without being logged in, so in the photo 'Francois Hodierne' would be replaced with whoever the logged in user is (i.e. the name and photo in the top righthand corner).

**Comment by JoyLubega** [comment]
Great 👍.  Thanks alot

**Comment by JoyLubega** [comment]
@sbinlondon I need some assistance on how to move forward based on @Betree's review on https://github.com/opencollective/opencollective-api/pull/4597. 
When I create a new mutation in the backend for creating an organization, it means I  also create new mutations in the frontend for both creating an Org and editing which is a little bit different from the scope you defined above. 

I having been trying to create the mutation and I am facing some issues
`Error: Unknown type "OrganizationCreateInput". Did you mean "CollectiveCreateInput", "CommentCreateInput", "CreditCardCreateInput", "ExpenseItemCreateInput", or "OrderCreateInput"?`
Yet I have added the OrganizationCreate input. I need some help.

**Comment by snitin315** [comment]
Hi @JoyLubega , Are you still working on this one?

**Comment by JoyLubega** [comment]
Its okay. You can pick it up

**Comment by Betree** [comment]
After merging the update, we should also update the screenshot (and eventually some text) on this page: https://docs.opencollective.com/help/financial-contributors/organizations#if-you-already-have-an-individual-profile

**Comment by sbinlondon** [comment]
:trophy: This issue has been completed by @snitin315  

To claim the **$500** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Comment by sbinlondon** [comment]
> After merging the update, we should also update the screenshot (and eventually some text) on this page: https://docs.opencollective.com/help/financial-contributors/organizations#if-you-already-have-an-individual-profile

I will add that to my list to do today.

**Comment by snitin315** [comment]
>  This issue has been completed by @snitin315
> 
> To claim the **$500** bounty, you can either:
> 
> * Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
> * Or ask for an Open Collective gift card of the same value (to donate to other collectives)

Thank you @sbinlondon, I have submitted an invoice for the same to https://opencollective.com/engineering/expenses
