### ISSUE TITLE
Remove 'hibernating at the north pole'

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3473]
It's a negative experience for a new user to set up their page, put effort into customizing the logo and color, work on their settings, and then have it look like this:

<img width="1263" alt="Screen Shot 2020-09-09 at 10 02 16 AM" src="https://user-images.githubusercontent.com/5498878/92532046-8f7a0e80-f283-11ea-8886-fdfde08a803c.png">

Can we please just remove this altogether? It's an off putting and negative message and there is no way to hide or delete it currently. Sometimes a new profile needs to be set up and it will take some time before the initial activity will make this go away. We shouldn't force them to deal with this in the meantime.

**Comment by Betree** [comment]
More generally, this should be about hiding the "Contributions" section (both in the page and the menu) if there's nothing to display in there.

**Comment by alanna** [comment]
Bumping this again! This makes pages for new users look *so* bad and really puts them off. Please make it go away!

**Comment by alanna** [comment]
What do I need to do to get this prioritised? I'm setting up a new profile for a customer and I can't show it to them in this state with the north pole thing dominating the page. Can it be removed from here manually or something? https://opencollective.com/giftcollective - it would be far better to just have blank space than the current situation... is it hard to just rip out the text and image?

**Comment by Betree** [comment]
> is it hard to just rip out the text and image?

It's not just that, we must make sure the section is not displayed in your menu neither. Which means we need to have to checks at the top level to see if the data is missing or not. It's not really complex but we must test it properly.

https://github.com/opencollective/opencollective-api/pull/3992 was started a few months ago to help with these kind of issues.

**Comment by Betree** [comment]
Just pushed https://github.com/opencollective/opencollective-frontend/pull/5178, it's not the best solution as it doesn't remove the menu entry but at least the message will be hidden.

**Comment by Betree** [comment]
Note: we also have a similar view in the recurring contributions sections, we'll probably hide it too when resolving this issue.

![image](https://user-images.githubusercontent.com/1556356/94778298-466e3380-03c5-11eb-96fc-d3acf64978b6.png)

**Comment by Memo-Es** [comment]
### Design update
---
Replacing the empty state for Collectives for public view

![Desktop](https://user-images.githubusercontent.com/49539954/97331236-c2319380-183e-11eb-8b19-fcf5d3e88e75.png)

@Betree

**Comment by Memo-Es** [comment]
A small design note: We should block certain color codes to avoid buttons like this one @Betree 

<img width="460" alt="Screen Shot on 2020-10-27 at 19-03-39" src="https://user-images.githubusercontent.com/49539954/97378161-56bfe400-1887-11eb-9295-0905ec94fb9a.png">

**Comment by alanna** [comment]
I really disagree with filling the empty space with anything, and especially with any text that reflects negatively on the profile, like the message suggested above saying they "have nothing to show". If there is nothing to show, just show nothing please. This is just changing the problem with the North Pole thing to the same problem with a different design.

**Comment by Betree** [comment]
Closing, the only thing left is the "Contribute" in the menu, that will be taken care of in https://github.com/opencollective/opencollective/issues/3737. @Memo-Es maybe we can open a new issue for empty state based on https://github.com/opencollective/opencollective/issues/3473#issuecomment-717363289?

@alanna Regarding your feedback @alanna, the question is whether we're ok with displaying an empty profile like that without further message:
![image](https://user-images.githubusercontent.com/1556356/100347839-4c0f8080-2fe6-11eb-97d5-41040d367249.png)

**Comment by sbinlondon** [comment]
Sorry I know this is closed but also wanted to say - the "hibernating" thing was cheesy, yes, and needed to be replaced. But it does need to be replaced with _something_. Placeholders aren't necessarily a negative thing, they're just signaling that a collective/user is new. I think we can update the specific copy if you feel it's not ideal @alanna but as @Betree shows above, a totally empty profile looks weird.
