### ISSUE TITLE
Can't load Sustain 2020 event page

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3474]
Clicking on the first event on this page takes you to https://opencollective.com/sustainoss/events/sustain-2020-5874aeeb which errors out. The other events seems to be working.

![Screen Shot 2020-09-09 at 1 29 23 PM](https://user-images.githubusercontent.com/5498878/92543826-8f3c3c00-f2a0-11ea-88bb-1550fea92ede.png)

**Comment by Betree** [comment]
@alanna I can't reproduce on Chrome/Firefox latest versions. Could you see if you get more details in the browser console?

Also, what kind of error do you get on https://opencollective.com/sustainoss/events/sustain-2020-5874aeeb ?

**Comment by znarf** [comment]
@Betree I get it here, likely some dirty deleted object.

<img width="911" alt="Screenshot 2020-09-09 at 08 45 10" src="https://user-images.githubusercontent.com/806/92564032-d1518780-f278-11ea-952e-719d99e1a439.png">

**Comment by znarf** [comment]
I fixed it today.
