### ISSUE TITLE
Financial contribution pending email should only go to admins

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3476]
User feedback:

An odd thing I have noticed is that when someone makes a donation by bank transfer, they receive three emails:
1.       ACTION REQUIRED email: email with instructions for how to make the transfer. 
This is all good.

2.       New pending financial contribution email: e.g. as shown below. 

<img width="568" alt="Screen Shot 2020-09-10 at 4 29 29 PM" src="https://user-images.githubusercontent.com/5498878/92681827-d69af900-f382-11ea-9327-7d5a82e9d5b5.png">

I don’t think this email should be going to the donor, but only to the admins.

3.       `Thank you email`, once the payment is approved. 
This is all good.

**Comment by Betree** [comment]
Indeed, in https://github.com/opencollective/opencollective-api/blob/2c3a44d8ebcd5339131cfc8332891d54927a61ed/server/lib/payments.js#L490 we send the email to `order.createdByUser` but it should really go to the admins.

**Comment by znarf** [comment]
Yes, we should never rely on `createdByUser` for anything, except activity tracking.

**Comment by znarf** [comment]
@alanna @Betree I have a PR coming but should that be really sent to the Collective Admins? Or is it more for the Host Admins?

PR: https://github.com/opencollective/opencollective-api/pull/4621

**Comment by alanna** [comment]
@znarf 

Host admins should definitely receive the `New pending financial contribution` email. I think it's OK if Collective admins do as well, or maybe they should get a different message? The need to know someone has contributed, but they might be confused if they don't see the contribution in the budget and don't realise it's still pending receipt of funds by the host.

After writing that out, I think both Host and Collective admins should get the notification. I assume our system is smart enough that if `Host admin`=`Collective admin` they won't get it twice?

**Comment by alanna** [comment]
Was this fixed in PR: opencollective/opencollective-api#4621 @znarf ?

**Comment by alanna** [comment]
Was this done @znarf ?

**Comment by znarf** [comment]
It was done and looks I ultimately decided to only send to the Fiscal Host admins. I don't exactly remember, maybe because it was simpler that way.
