### ISSUE TITLE
Feature request: Donation budget

### ISSUE THREAD

**Issue by alex-e-leon** [opencollective/opencollective#348]
I'm not sure what the total implication would be for processing or bank transaction fees, but I'd like to be able to set a monthly donation budget that you could then add multiple organisations to and have my budget split evenly (or maybe unevenly adjustable with sliders - maybe a future feature) between them.

This would make it easier to set a monthly donation budget but give some support to potentially many different open source projects - and would also cut down on at least some of the processing fees (a single monthly payment instead of many small ones)

**Comment by piamancini** [comment]
Hi @alex-e-leon we can work that out in two ways a) you can make a lump sum wire transfer to open collective and we allocate it to the collectives you want to support or b) you make a recurring donation to the [open source collective](https://opencollective.com/opensource) (you just use your credit card once) and again we allocate an amount to the collectives you want to support monthly. 
a) is more efficient for everyone in terms of overhead costs and our time 
b) is more work for us and has more processing fees but is better for the open source collective, since it will keep a % of your donation.

**Comment by alex-e-leon** [comment]
Thanks piamancini - for now b) is closer to what I'd be looking to do as a) wouldn't be a recurring payment would it?

**Comment by piamancini** [comment]
@alex-e-leon yeah a) would be a lump sum for the whole year, or 6mo for example. 
how much would you like to give monthly and spread between which collectives?

**Comment by alex-e-leon** [comment]
Ideally I'd be able to set aside a "donation budget" of for example $50 per month, but then be able to add or adjust the projects that I give that to over time. For example, as more and more projects create collectives, I could add them to my list of projects I'd like to support without having to change my original budget, or without having to manually remove or adjust the donation amounts to existing projects.

Say that I'm currently giving $50 to different collectives and I decide tomorrow that I want to support a new collective. I either have to change my budget (ok I'll give $60 per month instead) or I'll have to remove support for an existing project.

For now I think I'll support the open-source collective as that's the closest to having that feature, but it could be nice to have a feature like this in the future.

@piamancini Thoughts?

**Comment by piamancini** [comment]
hi @alex-e-leon that's definitely an interesting feature for us to develop. I need to think what's the mvp for that. Maybe making your company a collective that you can put money into and then thinking a way for collectives to make contributions to other collective. So you would have a monthly subscription to your collective and allocate it to other collectives. That's probably not so hard to build. 
We are also going to build a way for companies to buy support from the projects with a) a recurring subscription or b) $100 for an hour of support.

**Comment by piamancini** [comment]
@alex-e-leon part of this is coming in the new release. Organizations with members can be created on open collective, a credit card will be stored and members can be allowed to make donations with it (with a limit if required).

**Comment by piamancini** [comment]
@alex-e-leon you can now create an organization when making a contribution an attach a credit card to it! you should try it!!
