### ISSUE TITLE
Billing: Payment Receipts section in "Settings"

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3480]
## Purpose

People have a hard time finding their consolidated invoices, we need to make it more obvious.

## Owner

@znarf 

# Quick wireframe

<img width="1190" alt="Screenshot 2020-09-10 at 11 26 03" src="https://user-images.githubusercontent.com/806/92736212-5ec8d080-f37a-11ea-8af9-13fe9cd244d2.png">

**Comment by Memo-Es** [comment]
### Design update

![Large (Desktop)](https://user-images.githubusercontent.com/49539954/93624307-c5b33e80-f9a5-11ea-8cea-7066bc9e1172.png)


🎨 See the [design file](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=6417%3A0) in figma

**Comment by znarf** [comment]
In the end, the functionality should be similar to "Download Receipts" in the User/Organization page but with a much clearer interface. We can look at the [TransactionDownloadInvoices](https://github.com/opencollective/opencollective-frontend/blob/master/components/transactions/TransactionsDownloadInvoices.js) component and get inspiration from it but we should not copy/paste it.

<img width="1250" alt="Screenshot 2020-09-29 at 10 11 24" src="https://user-images.githubusercontent.com/806/94531073-4abb1500-023c-11eb-914a-a99de8f879e8.png">
