### ISSUE TITLE
Splitting login and long-term token functions in 'update-token' route

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3481]
Adding 2FA to the login process has shown the need for splitting and clarifying the functions of certain routes in the API.

The first 2FA iteration had all the 2FA functionality in the `/users/update-token` route which has always been used for logging in.

The current iteration moved the 2FA functionality to a separate endpoint, `/users/two-factor-auth`, which verifies the 2FA code with the token in the database, and then sends back a long-term token.

For accounts without 2FA, `/users/update-token` verifies the login and also sends back a long-term token.

Ideally, we would move the long-term token functionality into another separate route/function that can be used for both 2FA and non-2FA logins.

**Comment by znarf** [comment]
I think this was at least partially addressed in https://github.com/opencollective/opencollective-api/pull/8628

I don't see the need for this anymore.
