### ISSUE TITLE
Buttons move as page loads

### ISSUE THREAD

**Issue by mixmix** [opencollective/opencollective#3482]
**Describe the bug**
I'm an admin of a group and I want to go to the expenses.
I load the main page for my collective and go to click the `Budget` button, then more page loads and the button moves as I try to click it

**Expected behavior**
I want the page layout not to change as it loads

**Screenshots**

Page loading | Page loaded
---|---
![Selection_510](https://user-images.githubusercontent.com/2665886/92822671-84101a00-f420-11ea-8533-2ead099d8fba.jpg) | ![Selection_509](https://user-images.githubusercontent.com/2665886/92822675-85414700-f420-11ea-8b04-38f7bb3a6b85.jpg)

I think the appearance of the Logo / `settings` button cause the vertical spacing to change

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 79.0

**Comment by mixmix** [comment]
Possible solutions:
- put the settings button next to the Fiscal Host details area ... maybe way out on the right to make it clear and standalone?
- fix the height of the logo (if that's the problem)?

**Comment by Betree** [comment]
The image has a fixed height so you're right that the settings button is what creates the layout difference (the good part being, it *only* impacts admins). Now to solve it, I'd suggest adding an empty box that has the same height than the button when it's not there. We can eventually remove some margin if it looks to distant.

> put the settings button next to the Fiscal Host details area ... maybe way out on the right to make it clear and standalone?

This would be a good solution, but the design team already added more info there so I'm afraid how it could look.

**Comment by mixmix** [comment]
maybe I'll install a custom css extension for my browser and 

```css
a {
  position: absolute;
  right: 24px;
  top: 168px;
}
```

![image](https://user-images.githubusercontent.com/2665886/92908552-725b6080-f47a-11ea-8d13-5310033a408d.png)

except it looks like I'd have to write some horrific css selectors to target that element :( 
Alanna is yelling at me to go to bed

**Comment by Betree** [comment]
This will be fixed once we release the new navbar #3773 and merge the settings with the host dashboard. At this point an `Admin pannel` button will appear in the NavBar, which will prevent the jumping issue described here.

![image](https://user-images.githubusercontent.com/1556356/103076529-38980b00-45ce-11eb-872b-c2509fb12442.png)

**Comment by mixmix** [comment]
Hooray! Thanks for the update

**Comment by Betree** [comment]
New navbar is deployed, but we still need [to merge](https://github.com/opencollective/opencollective/issues/2896) the host dashboard with settings to be able to remove this "Settings" button entirely (it will be replaced by the "Admin panel" button in the new navbar)
