### ISSUE TITLE
"Reject" button for Collective admins on Transactions

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3485]
'Reject' is when you don't want the contribution at all and want to remove the member from the Collective.

## Collective transactions UI and where the 'reject' button might go under a 'view details'/'actions' heading
<img width="1252" alt="Screenshot 2020-09-11 at 13 07 25" src="https://user-images.githubusercontent.com/37520401/92923733-cd1b9a80-f42f-11ea-93cd-c2cd7aeb1575.png">

## Details and specs
- 'Reject' for a one-time contribution will: 
    - refund the transaction
    - set the status to `REJECTED`
    - remove the membership of `BACKER` from the Collective so they won't show on contributors anymore
    - and let you send a message as to why you are rejecting their contribution
- 'Reject' for a recurring contribution will:
    - do all of the above (refunding only the latest contribution though)
    - cancel the recurring contribution
- Contributions older than 30 days can't be refunded/rejected
- Rejected transactions will be marked as such in the budget due to their status, since we can't remove transactions but people will want to show that they have rejected the contribution for whatever reason

**Comment by sbinlondon** [comment]
Still to do:

- [ ] make sure this works with recurring contributions in the expected manner
- [ ] make sure refunds work with all payment methods as expected (gift cards, etc)
- [ ] either implement PayPal refunds or disable refund/reject buttons for PayPal transaction on the frontend

**Comment by Betree** [comment]
On https://staging.opencollective.com/captainfact_io/transactions:

- Layout when `Download receipt` & the other buttons are in there is a bit strange
- Shouldn't be able to reject a refund

![image](https://user-images.githubusercontent.com/1556356/94019442-16fe6c00-fdb2-11ea-930e-22f6661a742a.png)

**Comment by sbinlondon** [comment]
In speaking to @znarf last week he said we should be able to reject a transaction that has already been refunded. Do we want to change that now?

**Comment by Betree** [comment]
@sbinlondon Yes but this is a refund of a transaction I made (the collective is the payer). To give a clearer example, on my personal profile, https://staging.opencollective.com/betree/transactions?type=CREDIT, I can reject one of the donations I made to Babel that has been refunded:

![image](https://user-images.githubusercontent.com/1556356/94020567-54afc480-fdb3-11ea-88e5-93582d614438.png)

**Comment by sbinlondon** [comment]
So maybe a clearer thing would be to not allow the user/collective who made the contribution to `reject`?

**Comment by Betree** [comment]
Ah, I'm not an admin of Babel but I'm an admin of OSC on staging. That makes sense then! Apart from the layout issue, it's fine to display it indeed.

**Comment by sbinlondon** [comment]
Fixes: https://github.com/opencollective/opencollective-frontend/pull/5131

**Comment by sbinlondon** [comment]
Making it work with recurring contributions:

API: https://github.com/opencollective/opencollective-api/pull/4612

Frontend: https://github.com/opencollective/opencollective-frontend/pull/5138

**Comment by sbinlondon** [comment]
Planning to roll this out to selected collectives for testing on prod this week. Will release feature more widely soon in the coming weeks.

**Comment by sbinlondon** [comment]
This is now released to everyone on prod. Will do comms next week with Pia.
