### ISSUE TITLE
Bug in the API

### ISSUE THREAD

**Issue by HeaTTheatR** [opencollective/opencollective#3488]
Hello!
I am writing to you about a bug in the documentation - https://docs.opencollective.com/help/contributing/development/api/users-emails

![Снимок экрана 2020-09-11 в 17 46 20](https://user-images.githubusercontent.com/16930280/92965229-1692d680-f47e-11ea-9ba5-24531da175b3.png)
![Снимок экрана 2020-09-11 в 17 47 21](https://user-images.githubusercontent.com/16930280/92965247-1b578a80-f47e-11ea-8ca6-1eb726566802.png)

I tried to use the this API with my accesssToken of administrator in the KivyMD collective - https://opencollective.com/kivymd
I tried to get information about the backer of the KiviMD team using an API:

`curl -H "Authorization: Andrew myAccesssToken" https://opencollective.com/api/groups/kivymd/users`

This returns "Not Found".
Maybe I'm doing something wrong?
Thank!

**Comment by sbinlondon** [comment]
@znarf The linked documentation seems to be missing now and I can't find a `groups` endpoint on the REST API anymore. Should we close this issue?

**Comment by znarf** [comment]
@sbinlondon I answered in https://github.com/opencollective/opencollective-api/issues/4552 and removed the documentation.
