### ISSUE TITLE
Rename repository to 'Welcome'

### ISSUE THREAD

**Issue by RichardLitt** [opencollective/opencollective#349]
The OrgName/OrgName schema is common on GitHub, but it's a bit unclear for new contributors who do not know the schema. However, renaming this repository as 'Welcome' would be immediately clear to anyone that this is a high-level overview of the GitHub organization. 

Further, this repository should be pinned, so that newcomers can see it easily. :)

**Comment by piamancini** [comment]
This repo is pinned on the organization page. :+1:
