### ISSUE TITLE
Expense Flow: Payee Information as First Step

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#3495]
Adds step concept to the Expense Flow.
Display Payee Information as the first step when creating the expense.
When editing, do not separate it as a first step, display everything normally.

Figma:
https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC.com%5D-Production-Ready-%E2%9C%85?node-id=5800%3A215726

### Previews
**Step 1**
![Invoice 2](https://user-images.githubusercontent.com/2119706/93118809-34875380-f697-11ea-9407-1046597cffd7.jpg)
**Step 2**
![Invoice 3](https://user-images.githubusercontent.com/2119706/93119118-9fd12580-f697-11ea-96a1-a00e763d2976.png)

**Comment by Betree** [comment]
Not sure if is makes sense for this particular use case, but the `Steps` component provides a generic framework to deal with multi-steps processes, though it may not be necessary if we use formik.

**Comment by kewitz** [comment]
@Betree thanks for raising that up!
Since the summary happens after formik is submitted, this form has only two steps, and in my current WIP, I'm reusing the current implementation of steps for it.
Now I think we should really use the Steps component for consistency, even if it is a bit of an overkill for what we need.
I'll refactor and submit for review.

**Comment by kewitz** [comment]
Ignoring `When editing, do not separate it as a first step, display everything normally`, having two different UXs sucks too much.
