### ISSUE TITLE
Let admins pay expenses if tax form hasn't been received

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3496]
- Pay button should be enabled
- Paying these expenses should work
- Expenses with pending tax form should **not** be displayed when the `Ready to pay` filter is selected (already the case today)

**Comment by alanna** [comment]
Why would we want to do this?? Seems really dangerous to me. I don't think people understand how incredibly messy the tax form situation gets if we start making exceptions. Our 2019 taxes are still a mess despite pouring so much time in.

**Comment by Betree** [comment]
@alanna It was a request from @piamancini, who wanted to pay an expense that had its tax form submitted manually.

**Comment by alanna** [comment]
We can just go in Forest and set it as received in that case.

**Comment by Betree** [comment]
In that specific case the `LegalDocument` entry was not yet created in the DB (because the script used to run once a day, we've since updated it to once/hour). I agree with you, but I'll let @piamancini review these comments before taking action.
