### ISSUE TITLE
Github Sponsors transactions not showing as contributions

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3497]
We set up this organization profile to process incoming revenue through Github Sponsors: https://opencollective.com/github-sponsors/

@alinamanko adds these funds manually to Collectives based on the data export we get, with this org as the source. However, the transactions are not showing as contributions, which we want so we can see info like which Collectives are getting funded and how much to each.

There was an issue where Alina added these transactions as being from the main Github org profile, then corrected it. Maybe that's caused it?

Should we instead add the total funds to the org and then use it to actually contribute to the Collectives instead of directly adding funds to the Collective?

**Comment by alinamanko** [comment]
@piamancini I made the fix in Forest - adjusting the organization profile through the transactions listings. I hope this information helps

**Comment by alanna** [comment]
OK... who can fix this @piamancini ?

**Comment by JimBobSquarePants** [comment]
Subscribing to this issue as contributions are not arriving to the [SixLabors](https://opencollective.com/sixlabors) collective.

**Comment by alanna** [comment]
@JimBobSquarePants - sorry for the delay adding your payments. This is due to a technical issue on Github's side, which we're working on getting fixed.
