### ISSUE TITLE
Email preview showing wrong expense receipt image

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3498]
Here's how the email appears:
<img width="932" alt="Screen Shot 2020-09-16 at 10 48 45 AM" src="https://user-images.githubusercontent.com/5498878/93276374-70472800-f813-11ea-8e99-49176f94043c.png">

And here's that actual image:
![Screen Shot 2020-09-16 at 9 55 07 AM](https://user-images.githubusercontent.com/5498878/93276387-7937f980-f813-11ea-826c-58544e3c739e.png)

It's the correct image in the expense itself, but showing differently in the email preview.

**Comment by Betree** [comment]
Supposed reason: because the image is wider than high (landscape), it may be that it's repeating itself to fit the container (square).

**Comment by alanna** [comment]
Looks like the repeating image theory is correct, it's happening vertically too.

<img width="612" alt="Screen Shot 2020-09-23 at 1 43 03 PM" src="https://user-images.githubusercontent.com/5498878/93954969-dba87100-fda2-11ea-9773-d22480082485.png">
