### ISSUE TITLE
Blank button in host fees transaction

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3499]
If you click `show details` on an automated host fee transaction on an integrated host budget, there is a weird blank button, and no transaction details. This seems to be the case for all hosts with integrated budgets.

![Screen Shot 2020-09-16 at 9 36 24 AM](https://user-images.githubusercontent.com/5498878/93276687-67a32180-f814-11ea-9428-3b77a4c190b3.png)

**Comment by znarf** [comment]
The code from https://github.com/opencollective/opencollective-frontend/pull/4809 wrongly assumes that all transactions are Expenses or Orders. Could you look into this @kewitz ?

While you're at it, could you tell me why we're not seeing the "Download" button anymore if the transaction is refundable?

`const showDownloadInvoiceButton = !showRefundButton && permissions?.canDownloadInvoice;`

**Comment by kewitz** [comment]
> While you're at it, could you tell me why we're not seeing the "Download" button anymore if the transaction is refundable?

I think this was a design call, I'm restoring it because it looks OK both on the transactions page and on the collective page.
