### ISSUE TITLE
Deactivate rounding of logo for square logos

### ISSUE THREAD

**Issue by jancborchardt** [opencollective/opencollective#350]
At [Open Source Design](http://opensourcedesign.net) we have a square logo. On our [Open Collective](https://opencollective.com/opensourcedesign) I needed to add margins to the logo I uploaded (which made it smaller) just to circumvent the rounding of the logo.

The problem is especially relevant for us since initially our logo was the round version, but we were asked by the Open Source Initiative to change it cause it looks too much like their logo – which we complied to.

So it would be cool if it’s possible that the border can be disabled case-by-case so we can use the full logo size. :)

(cc @simonv3 @evalica for reference)

**Comment by simonv3** [comment]
I'm not sure I understand the ask.

**Comment by piamancini** [comment]
@jancborchardt hey! not entirely sure what you'd like to see. But, one thing to bare in mind is that when you are logged in then you'll alway be in editing mode and the logo shape is different to how it's seen. To see how it looks, open an incognito window. LMK if this doesn't solve it and we can dig deeper in the issue.

**Comment by jancborchardt** [comment]
> one thing to bare in mind is that when you are logged in then you'll alway be in editing mode and the logo shape is different to how it's seen

Oooooh ok! Didn’t know that. And I find it highly confusing so I opened a pull request to fix it :) https://github.com/opencollective/opencollective-website/pull/725
