### ISSUE TITLE
Title/description missing from Fund transaction

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3500]
This appears in the [transactions list for Foundation](https://opencollective.com/foundation/transactions): 
![Screen Shot 2020-09-16 at 9 58 32 AM](https://user-images.githubusercontent.com/5498878/93276820-c2d51400-f814-11ea-892a-b3e1a2a454a1.png)

I suspect what's going on is: this is the host using `add funds` on a Fund profile (Agora), and it not correctly generating the `Financial contribution to Agora` text.

**Comment by Betree** [comment]
It's not a bug on the transactions page: the transaction itself doesn't have a description. There are many others like that in the DB.

The main reason for this was that the legacy "Add Funds" form didn't require you to enter a description. The new one does.
