### ISSUE TITLE
Improvements for campaign-based fundraising

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3501]
I came across this message at the top of the `about` section of [an event](https://opencollective.com/athensmutualaidnetwork/events/sick-out-fund-a58a3a3b):
<img width="1258" alt="Screen Shot 2020-09-16 at 10 45 22 AM" src="https://user-images.githubusercontent.com/5498878/93276943-1ba4ac80-f815-11ea-9ea1-97b9f33b2c2d.png">

The fact that the users are needing to display this message tells me our platform could be better serving their needs here:
1. Allow incognito contributions to events
2. This isn't actually an event; it's more like a tier and it should be served well by standalone tier pages, but it's not. 

I suspect they aren't using a standalone tier page because they want to create suggested levels of giving, and you can't do tiers-within-tiers on a standalone tier page. Maybe we should allow that. 

It could also be that they want to have a separated budget and expenses tracked separately and therefore are using an event. There's no reason we couldn't adapt events to also be a campaigns feature (literally just copy past it and call it 'campaigns' and make the time/place settings optional).

**Comment by Betree** [comment]
> Allow incognito contributions to events

I agree with that. We may want to think about what it means for tickets, but for simple donations we should definitely allow it.

> you can't do tiers-within-tiers on a standalone tier page. Maybe we should allow that.

I'm not sure to understand this one, could you extend a bit?

> There's no reason we couldn't adapt events to also be a campaigns feature (literally just copy past it and call it 'campaigns' and make the time/place settings optional).

Funds may be a better fit, as events also have some logic that we don't want here (location, timezone, tickets, etc).

**Comment by alanna** [comment]
Would `projects` basically achieve this if we rolled it out for everyone?

**Comment by alanna** [comment]
This is solved by Projects
