### ISSUE TITLE
Wrong validation for github repo in new collective flow

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#3507]
This is a valid repo url: https://github.com/citizenspring/playstreets.brussels

But the onboarding when creating a new collective doesn't let me use that url:
<img width="445" alt="Screen Shot 2020-09-16 at 10 12 32 PM" src="https://user-images.githubusercontent.com/74358/93387653-df4f6b80-f869-11ea-9846-3d2f208fd519.png">

**Comment by Betree** [comment]
The fields ask for a Github profile (Github handle), not a Github repo, so that doesn't seems like a bug to me.

**Comment by Betree** [comment]
However after looking in the database it seems many collectives has this field set to a repo so we should probably be consisten and allow that.

**Comment by Betree** [comment]
For anyone willing to take a look, there was a good progress in https://github.com/opencollective/opencollective-frontend/pull/5247. The only thing left to add is to prevent strings like `xxx/yyy/zzz` to be accepted as valid by the form
