### ISSUE TITLE
Bug: Clicking on approve link sends multiple emails

### ISSUE THREAD

**Issue by ghuntley** [opencollective/opencollective#351]
Problem:

I clicked on the approve link twice, it sent two emails.

![image](https://cloud.githubusercontent.com/assets/127353/26184515/d27778be-3bc8-11e7-8f6c-913efb1fcae3.png)

Expected Behaviour:

The approval link once approved once would expire and not send another email.

**Comment by piamancini** [comment]
Thanks @ghuntley both this and the menu button suggestion are spot on. We'll work on this in the coming weeks. 
cc / @xdamman

**Comment by piamancini** [comment]
@asood123 did we solve this?

**Comment by asood123** [comment]
no :(

**Comment by piamancini** [comment]
this is solved now via updates

**Comment by ghuntley** [comment]
Thx
