### ISSUE TITLE
"Become a sponsor" page update

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3510]
We are updating the design of the "Become a sponsor" page

**Main goals:**
* Expanding the new branding style to the rest of the marketing pages

| **Previous design**  | **New proposal**  |
|---|---|
| <img width="1706" alt="Screen Shot on 2020-09-16 at 23-50-43" src="https://user-images.githubusercontent.com/49539954/93421633-8090ee80-f877-11ea-9e3a-84bf55ac726e.png">  | <img width="1162" alt="Screen Shot on 2020-09-16 at 23-51-58" src="https://user-images.githubusercontent.com/49539954/93421686-a74f2500-f877-11ea-8220-e0a19f0395a7.png"> |

🎨 See the [design file](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=6216%3A1132) in figma

@Betree

**Comment by alanna** [comment]
Let me know if you need help with copywriting.

**Comment by Betree** [comment]
Let's make sure we have a clear team decision on whether this update should be implemented as a React page or if we should stay with a static HTML page before starting the implementation.

**Comment by flickz** [comment]
I'm not sure about the page performance implication of using React vs static html but working with React definitely provides a better development experience and speeds things up. On the other hand, I love the idea of keeping things consistent, since the current version is implemented with static HTML. 

@Betree I'd love your opinion on this.

**Comment by Betree** [comment]
@flickz Your comment pretty well describes the pros/cons of each approach.

My personal opinion is that we should go with React for all these refactors. It will simplify our stack, make the updates easier, and will make sure design system updates are propagated there as well. On the performances I think it's pretty much the same. We could even take advantage of Next's [static generation](https://nextjs.org/docs/basic-features/pages#static-generation-recommended) to make it faster.

The main downside of this is that it increases the complexity of the update now (tho arguably simplifying it for future updates). Pages making intensive use of JQuery or other third party libraries may be tricky to migrate.

Ping @znarf @sbinlondon @kewitz

**Comment by flickz** [comment]
@Betree So we're going with React right?

**Comment by znarf** [comment]
@flickz Yes, this work is similar to the Homepage so let's do it with React and try to re-use components as much as possible.

**Comment by flickz** [comment]
> We could even take advantage of Next's static generation to make it faster.

@Betree I'm not sure how we can take this advantage since pages are served from a custom server, which according to Nexjs docs:

>  A custom server will remove important performance optimizations, like serverless functions and Automatic Static Optimization.

Any idea of how we can take achieve this? I'm thinking of maybe enabling Nextjs `useFileSystemPublicRoutes` could work but my worry is coalition of paths.

**Comment by Betree** [comment]
> Any idea of how we can take achieve this? I'm thinking of maybe enabling Nextjs useFileSystemPublicRoutes could work but my worry is coalition of paths.

It was a general idea for the future, we're indeed not ready to implement that.
