### ISSUE TITLE
Not being prompted to go on paid host plan

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3513]
[OCNZ host](https://opencollective.com/ocnz) has added more than $1000 by bank transfer and has multiple Collectives already, but I was never asked to go on a paid host plan. This isn't right, is it? Like, I'm fine with it because we don't have any money anyway haha... but I want to make sure there's not a bug stopping the system working as intended.

**Comment by alanna** [comment]
It's saying my usage is above the starter plan, but fine for free plan?

![Screen Shot 2020-09-18 at 9 30 18 AM](https://user-images.githubusercontent.com/5498878/93530391-9f83a380-f991-11ea-9fd8-9b18ee20552a.png)

**Comment by znarf** [comment]
> OCNZ host has added more than $1000 by bank transfer

Which transactions?

> It's saying my usage is above the starter plan, but fine for free plan?

More than 1 collective is fine for the Free Plan, but above the Single Host Plan.

**Comment by alanna** [comment]
> Which transactions?

I added over $3000, which you can see on the host's budget.

**Comment by alanna** [comment]
I added funds by bank transfer to a Collective and it tripped the $1000 limit and asked me to go on a host plan. So I think it might have to do with the funds being added to the host budget before?
