### ISSUE TITLE
Add button to remove avatar on the collective page

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3514]
_As requested in https://opencollective.slack.com/archives/C0RMV6F8C/p1600103357039700?thread_ts=1600098692038000&cid=C0RMV6F8C_

We want to add a button when hovering for you to remove your avatar in `HeroAvatar`:

![image](https://user-images.githubusercontent.com/1556356/93571204-67319480-f994-11ea-82de-612c1c503df7.png)

When clicked, it should display a message with a `ConfirmationModal`:

> Do really want to remove your profile picture?

If confirmed, it should set `null` for the `image` parameter of `editAvatar`.

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by darkmtr** [comment]
@Betree can i take this up as well?

**Comment by jeffin143** [comment]
Sorry the page didn't relaod , I jsut clicked assign myself

**Comment by Betree** [comment]
@darkmtr As per https://github.com/opencollective/opencollective/blob/master/BOUNTY.md, bounties are limited to one per person  for [contributors](https://github.com/orgs/opencollective/teams/contributors).

**Comment by darkmtr** [comment]
I completed 3+ issues but ok :slightly_smiling_face:

**Comment by Betree** [comment]
@darkmtr I'd be happy to update your status if that's the case, I just checked before sending this message but found only 2 completed + one pending: https://github.com/opencollective/opencollective/issues?q=is%3Aissue+assignee%3Adarkmtr+

**Comment by darkmtr** [comment]
@Betree i thought it was issues and not bounties, no worries. :+1:
