### ISSUE TITLE
2FA: loading state when submitting the form

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3515]
When submitting the 2FA on login form, there is no feedback and it's unclear the action is currently proceeding.

<img width="864" alt="Screenshot 2020-09-18 at 10 43 59" src="https://user-images.githubusercontent.com/806/93577166-fee6b100-f99b-11ea-8626-077c62f3b5b4.png">

**Comment by znarf** [comment]
Bonus: as discussed in latest review, we should remove the "warning" banner as the form is enough by itself.

**Comment by sbinlondon** [comment]
Fixed in https://github.com/opencollective/opencollective-frontend/pull/5130
