### ISSUE TITLE
2FA: dynamic payment limit for user

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3516]
In 2FA for payments, we're currently operating on a simplistic rule of `if payment.amount > $1,000 then 2FA`

We should change this behavior and move to a session based limit, everything stored in cache/Redis.

- If no session -> always challenge with 2FA
- If 2FA success -> allow payment and allow a follow up budget of $10,0000 
- On next payments -> check if the budget is exceeded
  - if yes, challenge for 2FA
  - if not, allow payment and decrease budget

Because of the volatile storage, the session can be lost at any moment and 2FA challenge will then proceed.

**Comment by sbinlondon** [comment]
Do you want to implement this one @znarf?

**Comment by sbinlondon** [comment]
https://github.com/opencollective/opencollective-api/pull/4713

**Comment by sbinlondon** [comment]
Released to OSC on prod. See https://github.com/opencollective/opencollective/issues/3708 for further discussion.
