### ISSUE TITLE
2FA: setting for the Hosts

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3518]
Hosts should be able to activate 2FA for their operations.

Because 2FA is currently hidden for Individual accounts, we should make sure Host Admins are able to see it and activate it.

Additionally:
- Based on our v1, they should be able to adjust the default threshold of 1000 in their currency
- Based on our upcoming version, they should be able to adjust the rolling limit for individual users

**Comment by sbinlondon** [comment]
Released to Open Source Collective on prod. Next step release to limited number of other hosts.

**Comment by sbinlondon** [comment]
Released to OSC on prod. See https://github.com/opencollective/opencollective/issues/3708 for further discussion.
