### ISSUE TITLE
Host monthly update / dashboard

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#352]
Feedback from Alaina (WWCode)

- How much money is in reserve
- Year to date new donations
- Month new donations / expenses (good to know who are the best performing collectives)
- Easy access to the receipt even after paid (to reconcile)
- One PDF will all receipts for the month
- Email alert when expense unpaid after x days

**Comment by piamancini** [comment]
closing this, no action items, some of the things we've done. Open separate issues for those you want to do.
