### ISSUE TITLE
Changes to profile page sections don't immediately update

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3526]
I think this is a UX bug. When you move and disable sections on the `'profile page' settings, you click `save` and then the other action link there is `view Collective page`. But if you click that, your changes won't actually show up. It's confusing and makes the user think they did something wrong or it's broken. I think it's a caching issue or something because if you refresh a few minutes later it's fine.

**Comment by znarf** [comment]
I just had a try, disabled/enabled some sections and could not reproduce.
