### ISSUE TITLE
Bug: core contributors who back the project do not show up as backers

### ISSUE THREAD

**Issue by ghuntley** [opencollective/opencollective#353]
OpenCollective:

https://opencollective.com/reactiveui

Users Experiencing Problem:

* ghuntley
* kentboogaart

Here's our view:

![image](https://cloud.githubusercontent.com/assets/127353/26274712/b388688a-3d82-11e7-96c6-f600a9982673.png)

Here's the XLS

![image](https://cloud.githubusercontent.com/assets/127353/26274717/d385f92c-3d82-11e7-8a8e-9275ff3ae8ea.png)

See https://reactiveui.net/ for end output

**Comment by piamancini** [comment]
Hi @ghuntley thank you for this! We just pushed a fix. cc / @xdamman
