### ISSUE TITLE
Maximum quantity not being enforced

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3530]
This is regarding this tier: https://opencollective.com/ehf-community/contribute/aroha-koha-for-paula-21141

On the main page you can see it's already reached the max available of 7:

![Screen Shot 2020-09-21 at 3 41 24 PM](https://user-images.githubusercontent.com/5498878/93731422-fa7efa00-fc20-11ea-9399-127d1ca88241.png)

But this isn't being enforced. You can still click `koha` and go through the checkout process. It should not let you do that.

**Comment by Betree** [comment]
We actually have an inconsistency here: the contribution (both legacy and new versions) both assume that only PRODUCTs and TICKETs tiers can have a limited quantity. I'll look at that.
