### ISSUE TITLE
Improve error handling in tier creation

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3531]
In the process of creating a new tier, I was shown this when I tried to save it:

<img width="1238" alt="Screen Shot 2020-09-21 at 1 56 08 PM" src="https://user-images.githubusercontent.com/5498878/93731470-3ca83b80-fc21-11ea-8adc-b35b1932fda2.png">

1. These errors should show inline to indicate which box on the form they relate to.
2. The description length limit is because this is actually the headline. For a standalone tier you can actually put in a much longer rich text description, but there is no way to know that from this page. I spent ages editing my text down to 510 characters and then realised I didn't even need to.
3. It should indicate where you've hit the character limit. I had to go out and use a third party tool to tell me how many characters I was at to know how much I had to cut.
4. Why does the default amount need to be a suggested value? And why does the form even let you put in another value if it's not allowed?
5. Same for minimum amount cannot be less than minimum suggested - don't let me input that in the first place.

**Comment by Betree** [comment]
I strongly resonate with this issue, as I assume 95% of new collectives go through this flow when they discover Open Collective and these errors are not a nice welcome for them (I personally had a bad experience with that when we put CaptainFact on Open Collective more than two years ago). 

However I wouldn't solve it like that: everything described here could be supported naturally if we move to our modern way to build forms, as proposed in https://github.com/opencollective/opencollective/issues/3438. This page uses old patterns and libraries that are now considered as deprecated in our codebase, it would be sad to invest too much energy in it to see it wiped away a short time after.

**Comment by Betree** [comment]
Should be resolved in https://github.com/opencollective/opencollective/issues/3438 by using inline validations and toast messages for server-side errors

**Comment by Betree** [comment]
Resolved by https://github.com/opencollective/opencollective/issues/3438
