### ISSUE TITLE
Incorrect isActive field value

### ISSUE THREAD

**Issue by zachleat** [opencollective/opencollective#3532]
Request to https://opencollective.com/11ty/members/all.json has inaccurate API information for entry with multiple backer tiers.

Silver sponsor (listed as active)
![image](https://user-images.githubusercontent.com/39355/93637477-4d577800-f9bb-11ea-91ed-1af9b25c9b25.png)

Gold sponsor (listed as inactive)
![image](https://user-images.githubusercontent.com/39355/93637697-99a2b800-f9bb-11ea-8a2e-cb99bb2d0a11.png)

Specifically this does not match what’s listed on the web site: https://opencollective.com/piccalilli_#section-recurring-contributions

Active contribution (Gold sponsor)
![image](https://user-images.githubusercontent.com/39355/93637573-6b24dd00-f9bb-11ea-83df-d0a1d077dd8e.png)

Cancelled contribution (Silver sponsor)
![image](https://user-images.githubusercontent.com/39355/93637585-6f50fa80-f9bb-11ea-85c7-ce42ef68cf34.png)

**Comment by znarf** [comment]
Transferring the issue to our top repository.

**Comment by znarf** [comment]
The `isActive` exposed in this endpoint has a weird definition. It's now part of our legacy and we're not gonna update it :-/

For reference, you can check the source code here: 
https://github.com/opencollective/opencollective-rest/blob/master/src/server/controllers/members.js

I recommend to use our GraphQL (or REST) API v2 for all new developments. I've created a PR for this https://github.com/11ty/11ty-website/pull/788

**Comment by zachleat** [comment]
Finally got this deployed—thank you! Wow, I did not expect a PR on this one, awesome!
