### ISSUE TITLE
Host not appearing in search results.

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3535]
This host exists:

![Screen Shot 2020-09-22 at 10 25 57 AM](https://user-images.githubusercontent.com/5498878/93827779-1e444d80-fcbe-11ea-91cc-acdf6dc6b75b.png)

But you can't search it:

![Screen Shot 2020-09-22 at 10 26 14 AM](https://user-images.githubusercontent.com/5498878/93827785-213f3e00-fcbe-11ea-8d79-2c769dbd7eed.png)

**Comment by znarf** [comment]
The indexing script is wrong, it's not indexing Organization with `isActive=false`. 

That might have been broken long time ago in https://github.com/opencollective/opencollective-api/pull/2632

**Comment by znarf** [comment]
It's a bit better now but you have to select "Fiscal Hosts" to see then, they're not in the general results. Maybe a simple fix there @Betree ?

<img width="1205" alt="Screenshot 2020-12-09 at 17 29 57" src="https://user-images.githubusercontent.com/806/101657515-45e8bd80-3a44-11eb-9748-5e18d2c39b46.png">

<img width="1228" alt="Screenshot 2020-12-09 at 17 29 51" src="https://user-images.githubusercontent.com/806/101657518-46815400-3a44-11eb-866c-de8e5a3fb6f0.png">

**Comment by Betree** [comment]
> It's a bit better now but you have to select "Fiscal Hosts" to see then, they're not in the general results. Maybe a simple fix there @Betree ?

Good catch, pushing a fix in https://github.com/opencollective/opencollective-frontend/pull/5546
