### ISSUE TITLE
HTML content: replace all external links by redirects

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3536]
Spammers are putting their website links in collective's long descriptions, comments and conversations to get a SEO boost. A way to increase our security and to cut the grass under their feet would be to replace all these links by redirections.

In https://github.com/opencollective/opencollective-api/blob/42fcf36475c3a6876e59a37d06051b2090766612/server/lib/sanitize-html.ts, we could replace all external links by:

`/redirect?url=${url}`

**Comment by HADES-01** [comment]
Hey @Betree can I take this one? I am new to open-source contributions and would very much like to expand my knowledge on this and can you guide me through this as well.

**Comment by Betree** [comment]
@HADES-01 Sure! A good place to do that would be in the [HTML sanitizer](https://github.com/opencollective/opencollective-api/blob/42fcf36475c3a6876e59a37d06051b2090766612/server/lib/sanitize-html.ts#L57). `sanitize-html` has a `transferTag` function that could do just what we want: https://github.com/apostrophecms/sanitize-html#transformations

Migrating the existing entries might be a bit more complex, we can eventually do it in another PR.

**Comment by HADES-01** [comment]
@Betree To be clear, you want me to replace "href" of all the "a" tags  to ```/redirect?url=${url}```

**Comment by Betree** [comment]
@HADES-01 Yep exactly, we also probably wan to use `encodeURIComponent` so `/redirect?url=${encodeURIComponent(url)}`

**Comment by HADES-01** [comment]
@Betree Will adding this to original ```transformTags``` work ??
```javascript
a: function(tagname, attribs) {
    const url = attribs.href;
     return {
         attribs: {
             href: `/redirect?url=${encodeURIComponent(url)}`,
        }
    }
}
```

**Comment by Betree** [comment]
@HADES-01 I suppose, but it has to be tested to confirm it. The best way to do so is to add a test in https://github.com/opencollective/opencollective-api/blob/c95294afaa70c25bb258e749857e7c4793eada28/test/server/lib/sanitize-html.test.js.
You'll be able to run it with `npm run test -- --watch test/server/lib/sanitize-html.test.js`.

**Comment by HADES-01** [comment]
@Betree I did what you asked and it works but "helloworks" test is failing. Can you please check it out [here](https://github.com/opencollective/opencollective-api/pull/4633/checks?check_run_id=1176430694).

**Comment by Betree** [comment]
Fix was merged in https://github.com/opencollective/opencollective-api/pull/4728.

What we now need to do to complete this issue is to migrate all places that have rich HTML content (`collective.longDescription`, `tier.longDescription`, etc.) to this common `sanitize-html` helper.
