### ISSUE TITLE
Get stuck with no error if you leave custom payout method note blank

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3537]
**Describe the bug**
You can't submit an expense if you leave the custom payout method description field blank.

**To Reproduce**
1. Create an expense
2. Select 'other' payout method
3. Create new custom payout method
4. Don't write anything in the box
5. Process with the expense
6. Get stuck without being able to submit it, with no error or way to tell what's happening.

**Expected behavior**
You should be able to create a payout method with no description if you want to.

**Comment by kewitz** [comment]
@alanna in what case do we want to give the option for a user to submit an expense with no instructions on how the host should pay for it?

**Comment by alanna** [comment]
@kewitz often times this is the case when the host admin and the payee are the same person! Or they've had a conversation elsewhere about paying. Or it's actually already been paid and we're just recording it for the OC budget. It's less common, but it happens.

**Comment by Betree** [comment]
@alanna Even if you're using something else it's easy to just write a quick description in the field no? Like:
> Paid manually in cash

It's clearer for the records, and it ensures that the person will be able to re-use the same payout method in the future (because it has a description). If there's none, we'll have to show a *`No description`* payout method in the list, which is always a bit sad.

I see more drawbacks than advantages in allowing payout methods to be created without a description.

**Comment by alanna** [comment]
OK, require a description, just make sure it's clear in the UI that it's
required, and errors in a useful way if it's not put in.

**Comment by Betree** [comment]
The current design pattern is to show `(Optional)` on optional fields, but no `(Required)` or `(*)` on required fields.

As discussed with design recently, we should make sure we don't disable the "Next" button if some fields are missing/invalid. We should always let you click on it, and show an error next to the fields that are not completed.

**Comment by alanna** [comment]
I hit this again today even thought it wasn't for a custom payout, I just didn't put a note in the optional private notes box on a a bank transfer payment method. The `next` button was disabled with no error and no clue what the problem was. I think we should really fix this.

**Comment by znarf** [comment]
@kewitz can you check if it's still relevant?

**Comment by BenJam** [comment]
> I'm ok with closing the issue

dont have to tell me twice.
