### ISSUE TITLE
Add a dateTo parameter in expenses graphql api v2

### ISSUE THREAD

**Issue by danielsum** [opencollective/opencollective#3539]
## User story 
To make a transparency page widget for any collective, I need to query the graphql expenses with parameters dateFrom and dateTo.

Regarding the documentation, it's only feasible to query expenses with a dateFrom for the moment.  I think it's worth to add a dateTo params. An user story around that will be a collective that needs to make an annual reports with specific date for exemple.

## Best solution for this problem

Add a dateTo in expenses graphql query :-)

**Comment by PeterDavidCarter** [comment]
OData?

**Comment by znarf** [comment]
Looks like a simple change.

**Comment by Betree** [comment]
Done in https://github.com/opencollective/opencollective-api/pull/6017
