### ISSUE TITLE
Sponsors are not shown in the README

### ISSUE THREAD

**Issue by nchanged** [opencollective/opencollective#354]
Hi!
We have an issue, backers are shown, sponsors - not.

https://github.com/fuse-box/fuse-box

Thanks

**Comment by piamancini** [comment]
Hi @nchanged that's happening because the sponsor didn't upload an avatar and so there's no image to serve. Is he a contributor on your software? https://opencollective.com/andrianarivony I can fetch his avatar from there.

**Comment by nchanged** [comment]
thanks, I will ask him to do so.
