### ISSUE TITLE
Expense Flow: Refact Collective Picker

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#3540]
Allows the user to invite someone outside the platform.

Figma:
https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC.com%5D-Production-Ready-%E2%9C%85?node-id=5806%3A53925

Preview:
![image](https://user-images.githubusercontent.com/2119706/94047997-38a72580-fda9-11ea-871a-d09e03ccab3f.png)

![image](https://user-images.githubusercontent.com/2119706/94049173-fda5f180-fdaa-11ea-868d-174e1cb4c370.png)

**Comment by PeterDavidCarter** [comment]
In these troubled times it is important to remember that Radiohead donated to Existinction Rebellion via Open Collective. It's such a small world but we are so appreciative of all these efforts! Thank you for the hard work!
