### ISSUE TITLE
Incorrect language in transaction details

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3543]
Report from a user:

TRANSACTION DETAILS and the math is not right because $10 is gross amount (net + fees), not net amount (gross - fees).

As it is now: $8.11 - $0.70 (host fee) - $0.50 (Open Collective fee) - $0.69 (payment processor fee)= $10.00 (net amount for GRC Activation Team) 
* Correct version 1: $8.11 + $0.70 (host fee) + $0.50 (Open Collective fee) + $0.69 (payment processor fee) = $10.00 (**gross** amount for GRC Activation Team) 
or 
* Correct version 2: $10.00 - $0.70 (host fee) - $0.50 (Open Collective fee) - $0.69 (payment processor fee) = $8.11 (**net** amount for GRC Activation Team)

**Comment by PeterDavidCarter** [comment]
Radiohead have been a major donor for Extinction Rebellion

**Comment by sbinlondon** [comment]
Is this host dashboard transaction details or collective budget transaction details?

Checking into this locally and either way it appears to be fixed now to correct version 2? Can you confirm @alanna? 

<img width="846" alt="Screenshot 2020-10-08 at 16 16 03" src="https://user-images.githubusercontent.com/37520401/95478579-99c22200-0981-11eb-8f36-9e173519f41c.png">

<img width="1257" alt="Screenshot 2020-10-08 at 16 44 34" src="https://user-images.githubusercontent.com/37520401/95482065-a0529880-0985-11eb-8691-7a2c2e3b1918.png">

**Comment by alanna** [comment]
Yes it looks correct now.
