### ISSUE TITLE
Improve the information hierarchy of tier cards

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3547]
This is something that came to us via our support channel in slack: 

" I’ve had to explain to two sponsors that the price to sponsor is above the button - both of them thought that the Goal amount at the top was the price to sponsor and were put off, saying it was too expensive. I think they should be reversed "

![screenshot-opencollective com-2020 09 24-16_13_11](https://user-images.githubusercontent.com/49539954/94591532-d25d4f80-024d-11eb-9c27-50b91c94065f.png)

**Comment by Memo-Es** [comment]
### Design update
---

Redesign of the goal-oriented sponsor tier card.

![Goal](https://user-images.githubusercontent.com/49539954/97517780-79233180-195b-11eb-9d9f-d90d7577c316.png)

@Betree

**Comment by RCheesley** [comment]
This looks much cleaner, and is visually much easier to understand I feel! Great job!

**Comment by Betree** [comment]
@Memo-Es Any link to figma for us to easily check the sizes? Also, while I agree that the card individually looks better, the contribute buttons are not aligned anymore in this new version. Are we ok with that?

![image](https://user-images.githubusercontent.com/1556356/105364656-b36c3a00-5bfd-11eb-8bbb-3157d18b6e0a.png)

**Comment by RCheesley** [comment]
> the contribute buttons are not aligned anymore in this new version. Are we ok with that?

I think they should be aligned if that is possible - it would look much tidier!

**Comment by Memo-Es** [comment]
Resolved in #3888
