### ISSUE TITLE
Overly generous GitHub Permissions

### ISSUE THREAD

**Issue by SimonCropp** [opencollective/opencollective#355]
These permissions would seem to be overly generous

![image](https://cloud.githubusercontent.com/assets/122666/26550694/4ab6d8d6-44c2-11e7-8214-6b621b36917f.png)

Why are they required and can they be limited?

**Comment by xdamman** [comment]
Agreed. We should just be able to read the contributors info, repos info (from user/org) and submit a pull request.

This might be a relevant previous commit on this topic: https://github.com/opencollective/opencollective-api/commit/8fedf5bf52b303f8b8abdc6a9f05efa0c9b49cec

Not sure what needs to be changed to reflect that. If you know, pull request very welcome! :)

/cc @asood123

**Comment by SimonCropp** [comment]
did some research and i dont think this is possible https://github.com/jollygoodcode/jollygoodcode.github.io/issues/6

**Comment by SimonCropp** [comment]
not sure what u actually need from a repo? perhaps `read:org` and `user:email` would be a better combination? or even "only  `user:email` " given u get "Grants read-only access to public information (includes public user profile info, public repository info, and gists)" by default?

**Comment by oliversauter** [comment]
Hey folks, 

I think reading everything will not be problematic for public repos. But reading private repos is not only very intense, but also does not seem to fit to the opencollective-spirit.  Nobody would/could/should be able to attach a private repo to a collective anyhow.
So it seems as access to private repos is kinda unnecessary.

**Comment by xdamman** [comment]
I agree. We don't need to be able to see/read private repos.

**Comment by SimonCropp** [comment]
sounds good to me. i assume u dont need a PR for that :)

**Comment by SimonCropp** [comment]
and i just re-read my initial issue text and realized it was overly blunt. sorry for that

**Comment by asood123** [comment]
I've looked into this a couple of times and I can't find another scope that gives us what we need. Currently, we ask for: `user:email, repo`. We need to be able to list all repos that a user has write permissions to (even if they are part of an org) and then find other users who also have write permission on the repos that a user selects.

Happy to change if anyone has a smaller scope that gives us this info.

**Comment by asood123** [comment]
here's the list: https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-scopes-for-oauth-apps/

**Comment by SimonCropp** [comment]
would the list of org memberships suffice? that seems to be public https://github.com/orgs/opencollective/people

**Comment by asood123** [comment]
I don't think so. Opening that link when I'm logged into GitHub shows a much larger list than when I'm not. It would require each member to have made their membership public...

**Comment by SimonCropp** [comment]
> would require each member to have made their membership public.

Isnt this desired given the open nature opencollective is trying to promote.

But either way i can see here that you have done your due diligence in terms of trying to limit the permissions required. Sorry i forced you all to re-hash it. Happy for this to be closed. And thanks for taking he time to educate me

One note is perhaps it might be worth to capture the above context in a little document for the next person who is concerned?

**Comment by asood123** [comment]
Yes, definitely desirable for everyone's membership to be public. Unfortunately, it's a manual action that each person needs to make per org that they are member of. Not everyone gets around to it and it ends up being unreliable info, which breaks our signup flow at times.

I'll figure out a way to document it. Or maybe we'll refer them to this issue when it comes up again ;-).

**Comment by BachirC** [comment]
Would be glad to have this feature too, don't want to scare off potential users of my app :) I personally only need the list of a user's public and private repos, no write needed.

**Comment by fhunleth** [comment]
I'm running into this issue as well since granting read/write permission to private repos is not something I can do. Not sure if this is a new option since when this issue was created, but couldn't the request for `repo` permissions be changed to `public_repo`?

**Comment by shiftkey** [comment]
> We need to be able to list all repos that a user has write permissions to (even if they are part of an org) and then find other users who also have write permission on the repos that a user selects.

I'm still not sure why the `repo` scope here is necessary over `public_repo` and `org:read` to achieve this. I have a little sample which I can share later that I used to poke at this using the [`github`](npmjs.com/packages/github) package, but here's the rough steps I used:

 - [`GET /users/teams`](https://developer.github.com/v3/orgs/teams/#list-user-teams) to find all the teams a user belongs to. This include organizations. Each team has a `privacy` and `permission` setting here that might be of interest.
 - [`GET /teams/:id/repos`](https://developer.github.com/v3/orgs/teams/#list-team-repos) gives you the details about which repositories the team has access to - this will have the `permissions` hash to indicate whether the team can push to it.
 - [`GET /teams/:id/members`](https://developer.github.com/v3/orgs/teams/#list-team-members) to then enumerate the other members in the team. This can be filtered on `member` or `maintainer` if you want to find specific groups of people.

Putting that aside, I'm also not sure about this comment from the linked commit:

```diff
 -      opts.scope = [ 'user:email', 'public_repo' ];
 +      // 'repo' gives us access to organizational repositories as well
 +      // vs. 'public_repo' which requires the org to give separate access to app
 +      opts.scope = [ 'user:email', 'repo' ]; 
```

Is this referring to [OAuth app restrictions](https://help.github.com/articles/about-oauth-app-access-restrictions/) that can be enforced by organizations to only whitelist certain apps? There's documentation to [request](https://help.github.com/articles/requesting-organization-approval-for-oauth-apps/) and [approve](https://help.github.com/articles/approving-oauth-apps-for-your-organization/) to approve these apps in a given organization, which I think is what might need to happen.

**Comment by piamancini** [comment]
cc/ @asood123

**Comment by asood123** [comment]
Let me dig into this - need to context switch back to see how our flow is working and find test cases that were failing before.

**Comment by asood123** [comment]
@shiftkey Ok I tried your steps. I get different results than what our current setup is:

Using your method, I looked up my own teams: came up with two. OpenCollective & xcodeswift (so far so good). Then, I used the team id to look up all the repos on my OpenCollective project. I get back 12 repos. It's missing lots of repos (and I'm an owner of team OpenCollective).

Currently, we use https://api.github.com/user/repos and when I run that for myself, I get over a 100 repos - most of them in OpenCollective.

To give you broader context, it's a balance between users complaining that their GitHub Repo isn't showing up on our sign up flow, so we broadened permissions. I'm happy to reduce them as long as we aren't confusing/losing users along the way.

**Comment by asood123** [comment]
And here's the original commit when we changed it from `public_repo` after user feedback

**Comment by asood123** [comment]
I went through it one more time just to be safe. When I set permissions to `public_repo`, I get back 149 repos for me. When I set it to `repo`, I get back 166 - it includes public repositories from xcodeswift, where I'm a member but haven't made myself a public member (for no other reason except that it's the default). That's the issue we ran into when we set scope to `public_repo`. Many users were confused why their repo wasn't showing up in our flow.

I tried `/user/orgs` - only returns one org for me. `/users/teams` returns one org with two teams for me. Neither case includes xcodeswift org.

In ideal world, the GitHub permissions would make it simpler for users to choose repos across orgs and their own account. It's a tough trade off for us - either limit to `public_repo` and have many confused users (when they don't see their repos in the list) or lose users who aren't comfortable giving access to private repos (which we ![filter out](https://github.com/opencollective/opencollective-api/blob/74d07d7e91d977757f4665cf7a8adfd7d10a5213/server/controllers/connectedAccounts.js#L119) btw).

I'm open to solutions - we would like to get a list of all repos that are public and that you have push permissions to. Main reason to try to include maximum number of repos is that GitHub projects are fluid in nature. People come and go all the time. So someone who may be the main contributor sometimes doesn't have access to the original org/team controls and can't make themselves an owner or make the org oauth accessible.

Hope this helps. Thanks for understanding.

**Comment by shiftkey** [comment]
@asood123 thanks for the extra information. I tried a few things on my side to recreate the issue on my side, but don't have much to show for it currently.

> I get back 12 repos. It's missing lots of repos (and I'm an owner of team OpenCollective).

This list is small because of how the organization is setup. This [guide](https://help.github.com/articles/managing-team-access-to-an-organization-repository/) shows how you can view these repositories assigned to a team and add/remove them.

But if you're fine with only looking for public repositories, `org:read`, then `/org/{name}/repos` and the `permissions` hash on each repository might be Good Enough™ for this, rather than poking at the teams themselves.

> When I set permissions to `public_repo`, I get back 149 repos for me. When I set it to repo, I get back 166 - it includes public repositories from xcodeswift, where I'm a member but haven't made myself a public member (for no other reason except that it's the default). 

I can only see 12 public repositories on the xcodeswift org, so it's not clear where these other repositories are coming from. Let's assume they're private ones.

> I tried `/user/orgs` - only returns one org for me. `/users/teams` returns one org with two teams for me. Neither case includes xcodeswift org.

This was working fine for me when I was using `/user/orgs` - I have a few orgs that I am hidden on:

 - unauthenticated, `/user/shiftkey/orgs` returns the six orgs you see on my profile
 - personal access token with `org:read` set, `/user/orgs` returns 33 orgs (i might be off by one, but whatever)

Anyway, to make it easier to investigate these differences in implementation I've built a test harness so we can easily diff these approaches for specific situations. Feel free to find specific cases so we can figure out which repositories are being overlooked and why. All you need to do is pass it a token (this should work with application authorizations too, but I haven't had a chance to try it): https://github.com/shiftkey/give-me-all-your-repos

I'm also still not clear on the comment in here about "requires the org to give **separate access** to app". Is there a back story here?

```diff
-      opts.scope = [ 'user:email', 'public_repo' ];
+      // 'repo' gives us access to organizational repositories as well
+      // vs. 'public_repo' which requires the org to give separate access to app
+      opts.scope = [ 'user:email', 'repo' ]; 
```

**Comment by jongalloway** [comment]
This is marked closed, but doesn't look resolved. What's the status?

**Comment by asood123** [comment]
Reopening this - we recently redid the GitHub flow and I think we can reduce permission scope.

**Comment by asood123** [comment]
Changing this back to `public_repo` to see if our new flow will reduce user issues that we hit earlier using `public_repo`. https://github.com/opencollective/opencollective-api/pull/1059. Should go live later today.

**Comment by jongalloway** [comment]
It looks like this is still requesting write access to public repos, which shouldn't be necessary. 

Per [this thread](https://twitter.com/leastprivilege/status/941278688649281538), from the reply by @shiftkey, it looks like you want to request "(no scope)" since public repos are already visible without requesting a scope.

(cc @leastprivilege)

**Comment by shiftkey** [comment]
To clarify, "(no scope)" is the default when you don't specify any other scopes, and is documented [here](https://developer.github.com/apps/building-oauth-apps/scopes-for-oauth-apps/)

**Comment by asood123** [comment]
Updated: https://github.com/opencollective/opencollective-api/pull/1067. Going live later today.

**Comment by asood123** [comment]
We have two complaints in last 24 hours (since we pushed the change) that users aren't able to see their repos. It's likely the scope that's the issue. Reverting change to unblock those users while we figure out why this is happening.

**Comment by asood123** [comment]
Both of those issues were resolved with `public_repo` scope. Seems GitHub API doesn't send all public repos without it. Open to alternatives, for now we'll stick to keeping that scope.

**Comment by shiftkey** [comment]
> We have two complaints in last 24 hours (since we pushed the change) that users aren't able to see their repos. It's likely the scope that's the issue.

Please reach out to [GitHub support](https://github.com/c) if you're encountering specific issues with using the API and would like some troubleshooting to understand these cases better...

**Comment by deamme** [comment]
Can we open this issue?

**Comment by oddstr13** [comment]
I just opened an account and went to link to GitHub, and was greeted with a request for **write** access to all my repositories.
![image](https://user-images.githubusercontent.com/638706/56471894-07aa1f00-6458-11e9-91c7-0e92fdbb2fde.png)

This is completely unacceptable, and this issue should be reopened.

What this means is that if the OpenCollective servers are compromized, **all** repositories for **all** users are at risk.

I don't know what exactly all the above permissions do, but I see webhooks and deploy keys are listed there, along with write access to the code and repository settings.

I can't even begin to imagine what a malicious user could do with access to any of the above, let alone all of them.

This is serious enough that I would urge everyone who has authorized OpenCollective with their GitHub account to revoke access **ASAP**.

**Comment by SimonCropp** [comment]
@piamancini can this issue be re-opened?

**Comment by Betree** [comment]
Hello @oddstr13, as someone who refused to register on services using Github auth for the same reasons I can only agree with it.

However from what I understand our hands are tied here because Github doesn't provide enough granularity in its permission system. I'm not very familiar with these, if anyone knows a way to avoid asking so much permissions we'd definitely love to do it. 

![image](https://user-images.githubusercontent.com/1556356/56557333-e140cc80-659a-11e9-85ed-b653a63e917f.png)

That being said, we have to acknowledge that this is a very legit concern that we must address. I have to check with the team how feasible this is, but would the following proposals work for you:

- Revoke all permissions once the repository's ownership has been verified
- Provide a path to manually verify a repository (eg. by uploading a proof to the repo's master)

**Comment by SimonCropp** [comment]
@Betree did anyone from opencollective reach out to github support as @shiftkey suggested here https://github.com/opencollective/opencollective/issues/355#issuecomment-353527162

**Comment by deamme** [comment]
@Betree I know that Netlify has something built in place where you only give them access to specific repos. Although I don't know the exact implementation. cc @sw-yx might know?

**Comment by sw-yx** [comment]
yes netlify does have it. but i dont know the impl. its so old that i dont even know who knows it at the company cos we barely touch it. but it is totally open source: https://github.com/netlify/git-gateway

feel free to steal.

**Comment by Betree** [comment]
Thanks for sharing @sw-yx! I'm re-opening this.

@znarf has a better understanding of the Github flow than I do. He'll be back next week, we'll check together what are our options here. @flickz welcome to join too if you have ideas on how this can be improved.

**Comment by SimonCropp** [comment]
@Betree thanks for looking into this again

**Comment by piamancini** [comment]
@simoncropp we did talk to Github about this - we absolutely agree with the issue raised - but there is not apparent solution at this stage.
 
We have plans of expanding the open collective bot for onboarding, which is a github app and therefore has (I believe) better granularity. @znarf is the right person to comment here. He's away for the next couple of days.

We'll look into netlify too.

**Comment by SimonCropp** [comment]
@piamancini thanks for the follow up, and the extra context.

**Comment by znarf** [comment]
In this context, Open Collective is a "GitHub oAuth app" and wants access to your public repositories. To do that, we ask for the "public_repo" scope. The "public_repo" scope is unfortunately very wide and includes read and write access to all public (not private) repositories data including "read/write access to code, commit statuses, repository projects, collaborators, and deployment statuses for public repositories and organizations". See: https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/

We would love to ask for narrower permissions but GitHub doesn't let us do that. If that's an issue for you, don't link your GitHub account or don't use the functionality asking for these permissions.

@alannallama Can we add that in the documentation?

**Comment by znarf** [comment]
Related: https://github.com/opencollective/opencollective/issues/1034

**Comment by pombredanne** [comment]
FYI, the latest signup still requires read access to private projects boards. I am admin right on many orgs and I CANNOT grant access to private data that I do not control when granting readonly access to my public user data.
