### ISSUE TITLE
Expense categories tracked against a budget

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3553]
## User story 
As a Collective admin, I want to be able to set budgets for different categories of expenses and use tags to track progress against them, so that I can make a plan about spending the money and see how well we're sticking to it.

## Best solution for this problem
Set a budget amount per tag, then tag expenses with that tag as you go, then be able to see a report showing the planned budget amount, the expenses with that tag, and the total spent of those expenses.

## MVP
Add a `tag` filtering option on the expense view so you can show all expenses with a given tag, and use a spreadsheet to total up the amount spent for that tag and compare it to your budget for that category.

**Comment by elea** [comment]
Added a +1, and to add to the user story: "I need to be able to provide categorized budget reports for grantors / potential grantors" is also something that'd call for the same feature.

**Comment by alanna** [comment]
I think this is solved by Projects
