### ISSUE TITLE
Highlight misfilled fields during contribution flow

### ISSUE THREAD

**Issue by ywwg** [opencollective/opencollective#3559]
## User story 
My friend was trying to donate to my collective, and the "Make Contribution" button was disabled.  It turned out they had not filled in their zipcode.  There was no easy indication in the UI that this was the missing piece to enable the donation.

## Best solution for this problem
Usually, sites allow you to press "submit" and will then do an error check, and highlight mis-filled fields.

## MVP
Better indicate required fields?

## Metrics 
Improved bounce rates

**Comment by Betree** [comment]
Thanks for the report @ywwg!

I can indeed reproduce, if you don't fill your ZIP code on the stripe input and click "Make contribution" the button doesn't do anything and the error is not reported in the interface:

![image](https://user-images.githubusercontent.com/1556356/94891743-2ef58000-0483-11eb-9345-449151436593.png)

We should implement the solution described by @ywwg above.

**Comment by HADES-01** [comment]
@Betree Can I take this one?

**Comment by Betree** [comment]
@HADES-01 sure :slightly_smiling_face:

**Comment by HADES-01** [comment]
@Betree I can't seem to pinpoint the exact location of this particular problem. Can you please help me out.

**Comment by Betree** [comment]
For the code:
- https://github.com/opencollective/opencollective-frontend/blob/c22d11f4b6ab1ba9663b01807efa8ba48f4bac22/components/new-contribution-flow/StepPayment.js
- https://github.com/opencollective/opencollective-frontend/blob/4d4da63bdb918e6046079f49183ada4710feb36b/components/NewCreditCardForm.js
- https://github.com/opencollective/opencollective-frontend/blob/cfeb5edc2e2d32ca1c06bb05cbfa0f4efd6c648d/components/new-contribution-flow/index.js#L438

For the feature itself, you can reproduce from any collective whose host has Stripe enabled, ie. https://staging.opencollective.com/babel/donate. You need to have the new expense flow enabled, to either set `NEW_EXPENSE_FLOW` env variable to true or go to https://localhost:3000/babel/new-donate
