### ISSUE TITLE
allow supporters to change their credit card details

### ISSUE THREAD

**Issue by aaronpk** [opencollective/opencollective#356]
There should be a way for people to update the card info without cancelling and re-creating a subscription.

I just had a supporter who needed to change his credit card used for the subscription. He cancelled his previous subscription near the end of the month, then created a new subscription with the new card. This charged his card immediately, and then again a day later on June 1. This means he paid twice for May.

**Comment by piamancini** [comment]
@aaronpk first step has been made, the new release will store details. Editing is the next one.
