### ISSUE TITLE
Host can request Collective to join

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3562]
## User story 
As a host admin, I want to invite an unhosted Collective to join my host, so that I can run an application process off the platform and select successful Collectives to allow to join without turning on the `apply` button for everyone. This would allow hosts to instruct users to go ahead and create their Collective as part of their application process, and then the host can action inviting them to be hosted if they are successful.

## Best solution for this problem
An action host admins can access on a Collective's page to `request to join [host]` - or a place on the host dashboard where you can search and select an existing unhosted Collective, and click `send invitation` or something like that. In both cases, the action would trigger an email notification to the Collective admin, and if they accept the Collective would join the host.

**Comment by znarf** [comment]
Seems duplicate with https://github.com/opencollective/opencollective/issues/3548

**Comment by alanna** [comment]
closing as dup
