### ISSUE TITLE
Error message when setting custom host fees for a collective

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#3569]
**Issue**

We are currently in process of setting up 0 host fees for a number of mutual aid groups coming under the umbrella of OCF. Out of the groups identified we have been setting up 0 host fees as custom fees through the Hosted Collectives tab on the host dashboard.

On a couple of instances an error message has been received, stating "an unknown error occurred". This was happening when setting up the fees for [Street Forum](https://opencollective.com/street-forum) and [Ward 2 Mutual Aid](https://opencollective.com/ward-2-mutual-aid) 

![Capture](https://user-images.githubusercontent.com/57156267/95159075-9ef46500-07f9-11eb-9089-d7fc6269f509.JPG)

**Comment by Betree** [comment]
@alinamanko is this still happening?

**Comment by alinamanko** [comment]
@Betree just checked and it seems to be working - adjusted the fees and will close this issue now
