### ISSUE TITLE
show actual date/time on transaction list

### ISSUE THREAD

**Issue by aaronpk** [opencollective/opencollective#357]
It's really difficult to tell what dates the items in the transaction list correspond to because they are all relative dates. "2 months ago" could be March or April, depending on how it counts a month. The transaction list should show the actual date and time of the transaction so that it's easier to reconcile with my Stripe account.

**Comment by asood123** [comment]
fixed.

**Comment by alanna** [comment]
Reopening because this has gone back to showing relative dates at some point. In order to do financial accounting we need to be able to see exact dates on transactions and expenses.

**Comment by sudo-kaizen** [comment]
@znarf @alanna 
Could you provide a procedure for anyone replicate this? Thanks

**Comment by znarf** [comment]
@alanna @aaronpk  I just checked and it's working as expected in the transactions page. 

Ie: https://opencollective.com/babel/transactions

![Screenshot_2019-09-16 Babel - Open Collective](https://user-images.githubusercontent.com/806/64982902-9021d400-d8bf-11e9-96ad-cbcfe9e23eae.png)
