### ISSUE TITLE
Currency Mismatch on socialcoop

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3572]
The collective changed Host and moved from USD to GBP.

Recurring Contributions in USD were not cancelled and are still processing in USD. This will lead to problems in accounting.

We should fix the situation.

**Comment by znarf** [comment]
Actions:
- contributions to USD tiers should be accounted in GBP in the ledger (use Collective currency, not Tier currency)
- all transactions inserted in USD (since the Collective switched to GBP) should be converted to GBP

We should have a CLI script to convert transactions to another currency. It will be useful in many situation.

**Comment by Betree** [comment]
> We should have a CLI script to convert transactions to another currency. It will be useful in many situation.

Such code would be helpful to implement https://github.com/opencollective/opencollective/issues/3460 as well

**Comment by znarf** [comment]
Calculation of the balance should only be done against current currency/host.

**Comment by znarf** [comment]
It's being worked on.

**Comment by znarf** [comment]
We now have a better handling of currencies in the balance.
