### ISSUE TITLE
Merge bounty documentation

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3575]
There are two different places where the Bounty process is documented:

https://github.com/opencollective/opencollective/blob/master/BOUNTY.md

and 

https://docs.opencollective.com/help/contributing/development/bounties

There is conflicting information on them and it's hard to keep them synced. Can the dev team please pick one location for these docs and we can link to it from the other location?

**Comment by sbinlondon** [comment]
Happy to pick this up.

I'd propose the home for the bounty documentation being on docs.opencollective.com and linking to it from the Github. Thoughts @Betree @znarf @kewitz?

**Comment by Betree** [comment]
@sbinlondon that sounds like the right move

**Comment by alanna** [comment]
Great, thanks Kate! Go for it.

**Comment by sbinlondon** [comment]
docs.opencollective.com updated with most recent info.

PRs to update Github documentation:

opencollective/opencollective: https://github.com/opencollective/opencollective/pull/3714
opencollective/opencollective-api: https://github.com/opencollective/opencollective-api/pull/4913
opencollective/opencollective-frontend: https://github.com/opencollective/opencollective-frontend/pull/5458
