### ISSUE TITLE
Problems with reactivating collective in order to process addition of funds and a transfer

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#3576]
**Description**
sfglobalshapers, a collective previously hosted under Foundation, and whose account was archived in February this year, contacted us to [enquire about funds from Eventbrite sent to Foundation bank account by accident](https://opencollective.freshdesk.com/a/tickets/10147). These funds arrived in our bank account over August and September and in order to add those and complete the transfer we need to reactivate the account. 

This has been done successfully through Forest. However, when trying to connect the fiscal host account foundation doesn't come up in the search for some reason (see screenshot below).

![image](https://user-images.githubusercontent.com/57156267/95406005-d8ea7600-0975-11eb-8151-dbc330e5b341.png)

**To Reproduce**
1. Go to Forest to the Collectives section.
2. Find sfglobalshapers and select the option of editing 
3. Scroll down to 'Host Collective' field and type to host name 
4. The dropdown menu does not include the required information

**Expected behavior**
I would expect the host details to show up which will then enable to process the incoming funds and get the transfer to be completed through the platform.

**Screenshots**
![image](https://user-images.githubusercontent.com/57156267/95406261-7a71c780-0976-11eb-9369-785e1a4e9322.png)

**Comment by alinamanko** [comment]
@znarf @Betree any idea why this is happening?

**Comment by znarf** [comment]
@alinamanko we should not do such operations in Forest.

If it's still a problem please forward the case to the engineering team on Slack or Freshdesk.
