### ISSUE TITLE
PDF preview generation failed

### ISSUE THREAD

**Issue by aaronpk** [opencollective/opencollective#358]
I'm not sure if this is unique to this particular PDF, but it failed to generate a preview when I uploaded it. I've attached it here for debugging.

[superfeedr-invoice-111958.pdf](https://github.com/opencollective/opencollective/files/1048456/superfeedr-invoice-111958.pdf)

**Comment by piamancini** [comment]
@aaronpk has this happened again?

**Comment by piamancini** [comment]
can't repro, link works. closing issue
