### ISSUE TITLE
Host dashboard: Add Host itself to "Hosted Collectives"

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3584]
We want hosts to be able to add funds to themselves when they have activated their host budget. 

To do that we should:
- List the host itself on `/host/dashboard/hosted-collectives`
- Make sure the add funds form works for this host
- Make sure the button to customize the fees is not displayed

**Comment by alanna** [comment]
+1

**Comment by znarf** [comment]
I added an entry in the Members table so it appears in the list. 

Follow up:
- Test that Added Funds actually works in production
- Do that by default when we activate budget for a given Host (entry in the Members table + approvedAt=NOW)
- Make sure the button to customize the fees is not displayed

**Comment by znarf** [comment]
https://github.com/opencollective/opencollective-api/compare/activate-budget-members-entry

**Comment by alanna** [comment]
The host Collective is now showing up twice:

<img width="506" alt="Screen Shot 2020-10-25 at 11 42 04 AM" src="https://user-images.githubusercontent.com/5498878/97095053-32151200-16b7-11eb-9dad-01a686ec4d26.png">

**Comment by znarf** [comment]
@alanna Seems something unexpected happened when you turned the budget on. Do you remember anything unusual?

**Comment by alanna** [comment]
Nothing unusual @znarf - I think I pressed the button and it seemed fine.

**Comment by znarf** [comment]
@alanna ok, from the db, it's a bit like it was activated 2 times, so I'm wondering how it happened. Anyway, it's now corrected.

**Comment by znarf** [comment]
It's done.
