### ISSUE TITLE
Support email address missing from tax form message.

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3587]
The last line here should be "please contact support@opencollective.com" but it's missing.

<img width="796" alt="Screen Shot 2020-10-10 at 12 50 58 PM" src="https://user-images.githubusercontent.com/5498878/95640050-5c7fa080-0af7-11eb-8423-30ee8617bbf4.png">

**Comment by znarf** [comment]
The link is indeed there in the code but not rendering for some reason:
https://github.com/opencollective/opencollective-frontend/blob/master/components/expenses/ExpenseNeedsTaxFormMessage.js

Maybe the reason is obvious for you @Betree ?

**Comment by Betree** [comment]
@znarf This one is only displayed on the legacy page, the one currently displayed is https://github.com/opencollective/opencollective-frontend/blob/15df3640cbaf03dd397824010603557a21855160/pages/expense.js#L394.

Not sure when this was updated, but it seems react-intl now always passes an array as chunks here. Opened https://github.com/opencollective/opencollective-frontend/pull/5294 to update the existing paths.
