### ISSUE TITLE
"Amount contributed" overly emphasised on non-sponsor profiles

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3589]
This is a design issue. If a Collective has financially contributed to other Collectives, the "amount contributed" becomes the top line emphasised number on their page. This is fine for sponsor profiles, but it's misleading when the purpose of the Collective is receiving money not spending it. It's easily confused for the amount of contributions they've received, which this number is *not*.

Here are some examples... both of these profiles are for mainly raising money not contributing money to others, but because these profiles have made contributions, that number ends up as the most eye-catching one on the page.

<img width="1258" alt="Screen Shot 2020-10-12 at 7 29 47 PM" src="https://user-images.githubusercontent.com/5498878/95712753-d4012b80-0cc1-11eb-94e6-60bf1bfb5ef8.png">

<img width="1260" alt="Screen Shot 2020-10-12 at 7 29 26 PM" src="https://user-images.githubusercontent.com/5498878/95712760-d6fc1c00-0cc1-11eb-8f08-44dff58b08fd.png">

@piamancini @Memo-Es do you have thoughts on this?

**Comment by Betree** [comment]
As per https://opencollective.slack.com/archives/G46PNRCGP/p1603202215007600:

> Let’s remove it for funds, hosts and collectives

Aka, only keep it for users and orgs that are not hosts.

**Comment by Betree** [comment]
The amount was actually not displayed for hosts, so the ones really impacted here are funds and projects. https://github.com/opencollective/opencollective-frontend/pull/5258 should fix that.
