### ISSUE TITLE
Monthly emails broken in Google Inbox

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#359]
![2017-06-05 15 40 56](https://cloud.githubusercontent.com/assets/6106941/26800001/b6888756-4a05-11e7-898a-13d97a50e5bf.png)

**Comment by xdamman** [comment]
From Frederik: "A tool like Litmus will help to debug" https://litmus.com

**Comment by emilerousseau** [comment]
Is there any system to make sure funded projects are actually useful? For example, is this OS *really* more secure?

**Comment by xdamman** [comment]
It's the "wisdom of the crowd"

Same applies to Kickstarter projects or blog posts that people actually end up reading.

It's up to all of us to spread the word about the projects that actually make sense and that we want to see succeeding in the world.

**Comment by emilerousseau** [comment]
I kinda gave up three years ago, but an object in motion remains in motion and all that. Happy your team are doing well. All I can manage is the odd impressive animation.

**Comment by emilerousseau** [comment]
Ironically, three years ago I started learning.

**Comment by emilerousseau** [comment]
I suggest http://www.empowering-communities.org/

**Comment by piamancini** [comment]
fixed.
