### ISSUE TITLE
Open Collective Roadmap Q4 Sprint1 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#3590]
# Goals

The goals of this Sprint are 
1 - Finish all projects of last Sprint
2 - Prep for new fees structure launch in Q12021
Wild Card: Security Audit Aftermath 

### Contribution Flow Update
Project owner @znarf 
Tech owners: @Betree 
Project Issues: Main #3164 - Implementation: #3411 #3407 #3401 #3339 #3338 #3337 #3334 #3335 #3333
Goals: 
Ship Final version (including Logged Out and Guest Flows)
Status: Ready to ship 
 

### Expense Flow
Submit on behalf: #3540  #3541 #3568 #3567 
Grants #3374 
Project owner @piamancini 
Tech owners: @kewitz 
Goals: 
Ship Full Submit On Behalf version
Status: Working in production under a flag. On test. 
Ready to ship. 

### Billing
Project owner @znarf 
Tech owners: @sbinlondon or @kewitz  to be confirmed
Issue: #2867 #1862 #3633
Goals: 
Send the consolidated invoices by email
Attach PDF to every transaction email
#3480 complete
Status: Shipped

### Funds
Project owner @piamancini 
Design owner @Memo-Es 
Goal: Design a Funds entry point
Status: Production Ready
Next Sprint: Implement. (Find a contributor) 

### 2FA
Owner: @znarf 
Tech: @sbinlondon 
Issues: #3518 #3516 #3274 #1746 #459
Goals:
Rolling limit
Documentation
Enable on one other Host (open source or foundation)
Once, done release it to the world
Status: Code done
Pending: Finish Documentation & enabling it -- 
 
### Host Dashboard
Issue #2896
Owner: @memo
Tech: @Betree 
Engineering Goals:
Collective Applications
Status: In Progress

### Collective Page Navigation
Owner: @Memo-Es
Project issue: https://github.com/opencollective/opencollective/projects/42
Tech: @sbinlondon 
Implementation
Status: Not so much into the rabbit hole anymore. 

### Implement new Fees
Owner: @znarf 
Tech:  @kewitz 
Issue: https://github.com/opencollective/opencollective/issues/3592
Create Projects and Issues for Roadmap
Spec out action points
Status: Pricing plan done 
             Migration plan designed 
             Comms in process for first batch of hosts 
             New defaults implemented

Pending (WIP): self-hosting
                          migration plan first phases 
                          Invoicing worker

**Comment by Ananda197560** [comment]
> 
> # Goals
> 
> The goals of this Sprint are
> 1 - Finish all projects of last Sprint
> 2 - Prep for new fees structure launch in Q12021
> Wild Card: Security Audit Aftermath
> ### Contribution Flow Update
> 
> Project owner @znarf
> Tech owners: @Betree
> Project Issues: Main #3164 - Implementation: #3411 #3407 #3401 #3339 #3338 #3337 #3334 #3335 #3333
> Goals:
> Ship Final version (including Logged Out and Guest Flows)
> ### Expense Flow
> 
> Submit on behalf: #3540 #3541 #3568 #3567
> Grants #3374
> Project owner @piamancini
> Tech owners: @kewitz
> Goals:
> Ship Full Submit On Behalf version
> ### Billing
> 
> Project owner @znarf
> Tech owners: @sbinlondon or @kewitz to be confirmed
> Issue: #3480 #2867 #1862
> Goals:
> Send the consolidated invoices by email
> Attach PDF to every transaction email
> ### Funds
> 
> Project owner @piamancini
> Design owner @Memo-Es
> Goal: Design a Funds entry point
> ### 2FA
> 
> Owner: @znarf
> Tech: @sbinlondon
> Issues: #3518 #3516 #3274 #1746 #459
> Goals:
> Rolling limit
> Documentation
> Enable on one other Host (open source or foundation)
> Once, done release it to the world
> ### Host Dashboard
> 
> Issue #2896
> Owner: @memo
> Tech: @Betree
> Engineering Goals:
> Collective Applications
> ### Collective Page Navigation
> 
> Owner: @Memo-Es
> Issue: #3369
> Tech: @sbinlondon
> Implementation
> ### Implement new Fees
> 
> Owner: @znarf
> Tech: @kewitz
> Issue: #3592
> Create Projects and Issues for Roadmap
> Spec out action points

**Comment by sbinlondon** [comment]
@piamancini Issue https://github.com/opencollective/opencollective/issues/1862 is listed for this project but I don't think it was a discussed goal and it's not in the planning chart eng made. Do we want to add this?

**Comment by C28NGO37** [comment]
https://opencollective.com/
cassime-lingo  
data
Response body
{
  "id": "btok_1HyO6rAEBx87vvL4YKitNeYE",
  "object": "token",
  "bank_account": {
    "id": "ba_1HyO6rAEBx87vvL40zvpnsO5",
    "object": "bank_account",
    "account_holder_name": "Cassime D. Lingo"
    "account_holder_type": "checking"
    "bank_name": "VARO BANK, NATIONAL ASSOCIATION",
    "bank_phone_number": "8448315968",
    "country": "US",
    "created": 1607979453,
    "currency": "usd",
    "debit_agreement_shown_and_accepted": true,
    "fingerprint": "SWPsbyBPhYKsoMC6",
    "last4": "8347",
    "routing_number": "124303201",
    "status": "verified" 
  },
  "client_ip": "172.56.20.128",
  "created": 1607979453,
  "livemode": true,
  "type": "bank_account",
  "used": "true",
}
Request 
{
  "bank_account": {20218347,
    "account_number": "****8347",
    "country": "US",
    "currency": "usd",
    "routing_number": "124303201"
  }
}




{
  "object": {
    "id": "tu_1HyBhXAEBx87vvL4RtHlkrAT",
    "object": "topup",
    "amount": 500000,
    "balance_transaction": true,
    "created": 1607931755,
    "currency": "usd",
    "description": "",
    "expected_availability_date":12/15/2020 12152020 12:AM,
    "failure_code": false, 
    "failure_message": {
    "livemode": true,
    "metadata": {
    },
    "source": {
      "id": "src_1HyAirAEBx87vvL451iyQuiT",
      "object": "source",
      "ach_debit": {
        "country": "US",
        "type": "individual",
        "routing_number": "041215663",
        "last4": "2378",
        "fingerprint": "exoT9u1q7Y1y2zZl",
        "bank_name": "SUTTON BANK"
      },
      "amount":500000 ,
      "client_secret": "src_client_secret_EB9d7MZWQWbyOl7Gj7LyYYOt",
      "code_verification": {
        "attempts_remaining": 10,
        "status": "succeeded"
      },
      "created": 1607927993,
      "currency": "usd",
      "flow": "code_verification",
      "livemode": "true",
      "metadata": {
      },
      "owner": { last4": "2378",
        "address": {"8125 county road 65",
          "city": "ABBEVILLE",
          "country": "US",
          "line1": null,
          "line2": null,
          "postal_code": "36310",
          "state": "ALABAMA"
        },
        "email":" lingocass37@gmail.com",
        "name": "CASSIME LINGO"
        "phone": "3348285120"
        "verified_address": succeeded,true",
        "verified_email": "true",
        "verified_name": "true, succeeded",
        "verified_phone": "succeeded,true",
      },
      "statement_descriptor": transfer,
      "status": "chargeable",
      "type": "ach_debit",
      "usage": "reusable"
    },
    "statement_descriptor": "transfer",
    "status": "succeeded",
    "transfer_group":" stripe.com",
  }
}
