### ISSUE TITLE
Host fees being applied to debit transactions of that host

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3595]
These are transactions where OC inc is charging Protozoa for its monthly host plan, on opencollective.com/protozoa/transactions

The system is applying host fees, which doesn't make sense for two reasons. First because this is a charge to the host itself, and host fees shouldn't apply, and second because it's a debit transaction so why would any fees be added?

![Screen Shot 2020-10-13 at 1 07 18 PM](https://user-images.githubusercontent.com/5498878/95801069-ae256680-0d55-11eb-9fc3-31fa9a00d335.png)

**Comment by Betree** [comment]
`opencollective` seems to have `hostFeePercent` to 0 now, but it used to be 5% at the time of these transactions. All new transactions created like that since 2020-09-01 have 0 host fees.

I agree that it's a bit strange to have a host fee there. @znarf should we fix the past transactions?

**Comment by znarf** [comment]
> First because this is a charge to the host itself, and host fees shouldn't apply

It's generally being looked into it. We haven't really thought about this case before.

Note that "opencollective" is just a collective hosted by opencollectiveinc at the moment.

> and second because it's a debit transaction so why would any fees be added?

It's handled like a financial contribution, so host fees are/were handled like any other financial contribution.

> should we fix the past transactions?

Let's not touch it now. We can review it once we merge opencollective and opencollectiveinc.
