### ISSUE TITLE
Display contribution policy in contribution flow

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3596]
We want to display collective's contribution policies in the contribution flow FAQ when they have one.

Design: https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC.com%5D-Production-Ready-%E2%9C%85?node-id=4489%3A3180

![image](https://user-images.githubusercontent.com/1556356/95842601-04d77400-0d47-11eb-96a8-bf7bdef7ee0b.png)

**Comment by vickywane** [comment]
@Betree can i assist you on this?

**Comment by Betree** [comment]
Sorry I missed you message @vickywane, thanks for proposing your help, I already have a resolution for this issue that should be pushed today along with other updates to the contribution flow.

**Comment by vickywane** [comment]
Alright
