### ISSUE TITLE
Paypal error message persists after switching to manual

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3599]
**To Reproduce**
1. Try to pay an expense over $2,000 using automatic paypal payment method
2. See below error
3. Change to manual paypal payment method
4. Error stays on the screen
5. You can pay the expense

**Expected behavior**
The error should disappear when you change payment methods

**Screenshots**
![ppcurrency](https://user-images.githubusercontent.com/5498878/95914827-c0111300-0e02-11eb-998b-05be5a6d9871.png)

**Comment by Betree** [comment]
Was fixed in https://github.com/opencollective/opencollective-frontend/pull/5243:

![Peek 2020-11-26 12-41](https://user-images.githubusercontent.com/1556356/100346839-c8a15f80-2fe4-11eb-9b6e-ed2c1686df03.gif)
