### ISSUE TITLE
Share on Twitter / Facebook after donation

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#36]
After a donation, we should offer the user an easy way to share on Twitter and Facebook (and we should add `?referrerId=$userid` to the URL of the collective). Both for first time donors and returning donors.

![](http://cl.ly/3Z2W2Y0g0C1Y/Screen%20Shot%202016-04-17%20at%2010.35.25%20PM.png)

**Comment by carlosascari** [comment]
@xdamman I'm reusing the ShareIcon component for this. @cuiki hasn't had a chance to work on the design however the code is ready, woulld like me to make the PR now, or wait for the design completed PR?

![So far](https://my.mixtape.moe/axvqye.png "Using ShareIcon component")

**Comment by xdamman** [comment]
Boom, perfect! Ship it! :-)

**Comment by carlosascari** [comment]
Shipped https://github.com/OpenCollective/website/pull/169

**Comment by piamancini** [comment]
great!

P.
piamancini.com
t: @piamancini
s: piamancini
OpenCollective <https://opencollective.com>
