### ISSUE TITLE
add link to /transactions in an empty collective

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#360]
If a host wants to manually add funds and there are no transactions in the collective, there is no direct link to do it. host must type the opencollective.com/:slug/transactions URL
example from https://opencollective.com/suffolkfosterparents#budget
<img width="1141" alt="screen shot 2017-06-07 at 2 37 26 pm" src="https://user-images.githubusercontent.com/3671070/26895216-e3ef00b4-4b8e-11e7-8ae2-0148e9306ee8.png">

**Comment by asood123** [comment]
https://github.com/opencollective/opencollective-website/pull/740
