### ISSUE TITLE
Host dashboard: Error when combining Ready to pay + Open Collective payout type filters

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3602]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1556356/95976441-c9f14100-0e17-11eb-947a-4b932d8b0a6d.png)

> syntax error at or near ")"

**To Reproduce**
1. Go to https://staging.opencollective.com/opensource/dashboard?payout=ACCOUNT_BALANCE&status=READY_TO_PAY

Or go to the dashboard and pick the filters.

**Comment by kewitz** [comment]
Fixed by https://github.com/opencollective/opencollective-api/pull/4717
