### ISSUE TITLE
Expense form: blocked from error on another step

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3603]
**Describe the bug**
On the expense form, the first step can be blocked by an error on another step

**To Reproduce**
1. Go to new expense page (or try to edit an existing expense)
2. Pick Invoice and fill payee info
3. Go to step 2 and fill one item details then click on Next
4. Change expense type to "Reimbursement" 
5. Next button is disabled because item is missing an attachment

**Expected behavior**
Shouldn't be blocked on step1 if the error is on step2

**Screenshots**
![image](https://user-images.githubusercontent.com/1556356/95977588-56503380-0e19-11eb-919e-7b3d2ad40f2f.png)

**Comment by gutofoletto** [comment]
Hello @Betree 
Is this "up for grabs"?

_btw, I couldn't reproduce it locally 🤔_

**Comment by Betree** [comment]
> Hello @Betree
> Is this "up for grabs"?

It is!

I indeed could not reproduce anymore with a new expense, it only happens when editing.

**Comment by gutofoletto** [comment]
> > Hello @Betree
> > Is this "up for grabs"?
> 
> It is!
> 
> I indeed could not reproduce anymore with a new expense, it only happens when editing.

Nice! I can take a look then :)

**Comment by gutofoletto** [comment]
Hey there. Sorry I couldn't tackle this sooner
I just pulled from master and it seems that this problem is gone 🤔 
So it might be good to close this issue

**Comment by Betree** [comment]
Issue seems fixed indeed, @kewitz probably fixed it since then?

Anyway thank you @gutofoletto, feel fee to look at other issues if you want to paticipate :-)
