### ISSUE TITLE
Change the shape of the collective header area to be a rectangle

### ISSUE THREAD

**Issue by jdaviescoates** [opencollective/opencollective#3604]
## User story 
_As as collective admin I can add a rectangular head so that thumbnails on social media don't look rubbish_

## Best solution for this problem
_Just make the collective header area a rectangle (instead of a weird curve) like there are everywhere else_

## MVP
_Edit the CSS of collectives so that the header area is a rectangle_

## Metrics 
_How collective thumbnails appear when links to the collective are posted on social media sites_

## Documentation 
_Upload the header you use for Twitter or Facebook and it'll look great on OC too

To get the text in our header image where I wanted it on OC, i.e. like this:
![Better_Media_Open_Collective](https://user-images.githubusercontent.com/2113743/95987049-ce6d2800-0e1e-11eb-9f64-12f623f0a5b9.png)

I had to create a weird image like this:
![BetterMediaUK_Open_Collective_Header](https://user-images.githubusercontent.com/2113743/95987067-d3ca7280-0e1e-11eb-88ac-4a86f6361075.png)

Which then appears as a thumbnail like this:
![lame_twitter_thumbnail](https://user-images.githubusercontent.com/2113743/95987044-cdd49180-0e1e-11eb-825c-cd97f404baab.png)

_

**Comment by Betree** [comment]
Alternative: https://github.com/opencollective/opencollective/issues/2660

**Comment by Betree** [comment]
I'm closing this in favor of #2660, which I think can provide a good solution that doesn't require involving design.
