### ISSUE TITLE
Host fees being applied to contributions to the host budget

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3605]
I thought I already raised an issue for this but I can't find it. Contributions directly to the host budget are charging host fees. Is this what we want?

![Screen Shot 2020-10-15 at 2 11 14 PM](https://user-images.githubusercontent.com/5498878/96061772-8a4a5800-0ef0-11eb-9cba-0d26273c63f0.png)

@piamancini - do we actually want to charge host fees here in terms of counting contributions direct to the host as part of the 15% charged in the new pricing model? That's the only reason I can think of to apply host fees to these transactions.

**Comment by znarf** [comment]
It was partially fixed but that needs to be double checked. https://github.com/opencollective/opencollective-api/pull/4756/files#diff-f462c25a8e5deddb0246b43ce2aaac42df8fd5980855a69c9835b3d6b493a768R568

**Comment by znarf** [comment]
This should be fixed.
