### ISSUE TITLE
tag OSS collectives automatically

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#361]
Tag collectives with what language they use, what type to project they are so we can then bundle them.
Step 1 
Figure out if this can be done automatically fetching that info from github or we need to add the field for manual tagging when creating a collective. 
Step 2 for existing collectives: see #291

**Comment by asood123** [comment]
Fetches tags directly from Github: https://github.com/opencollective/opencollective-api/pull/889
Adds a box in the flow when signing up to edit/add tags: https://github.com/opencollective/opencollective-website/pull/736
