### ISSUE TITLE
Empty "READY TO PAY" expenses filter will throw an error.

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#3611]
**Describe the bug**
When filtering for READY TO PAY expenses, if the returned list is empty, it will cause a bug in the Sequelize query and reach the frontend.

**To Reproduce**
1. Go to your Dashboard
2. Filter for Ready To Pay
3. Tweak with other filters until you see the errors

**Screenshots**
![deepin-screen-recorder_Select area_20201016205610](https://user-images.githubusercontent.com/2119706/96323179-5fe0c380-0ff2-11eb-8bb3-c98f52860ae6.gif)

**Comment by Betree** [comment]
Probably similar to https://github.com/opencollective/opencollective/issues/3602
