### ISSUE TITLE
Display the total amount of filtered expenses in the Dashboard

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#3613]
## User story 
As a host admin, I want to filter the ready to pay expenses and see the total amount I have to send to my TransferWise or PayPal account in order to pay these expenses.

## Best solution for this problem
Add a header or footer to the expense dashboard list where we can display the total amount of the filtered expenses.

## MVP
![image](https://user-images.githubusercontent.com/2119706/96325843-dfc25a00-1001-11eb-8954-bca9323288fa.png)

**Comment by leonardohofling** [comment]
I'll work on it, okay?

**Comment by kewitz** [comment]
Have fun, @leonardohofling!

**Comment by kewitz** [comment]
:trophy: This issue has been completed by @leonardohofling 

To claim the $100 bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
