### ISSUE TITLE
Add Funds form incorrectly adding fees

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3616]
**Describe the bug**
If you change the source in the `add funds` form, the form resets the platform fee even if you've already set it to zero.

**To Reproduce**
1. Got to host dashboard
2. Go to Financial Contributions
3. Search the Collective name
4. Click `add funds`
5. Fill out the form with 0 for fees
6. Change source
7. Fees get reset but it still says 0%

**Expected behavior**
It should retain the fees settings when you change other parts of the form.

**Screenshots**
![Screen Shot 2020-10-20 at 10 46 49 AM](https://user-images.githubusercontent.com/5498878/96515556-0b736780-12c2-11eb-91be-412b67905cfd.png)

Related: #3584 to deprecate this old form.

**Comment by Betree** [comment]
Let's rather focus on https://github.com/opencollective/opencollective/issues/3584 and let's make sure we hide this one in the `Financial contributions` tab.

**Comment by znarf** [comment]
The old form is gone.
