### ISSUE TITLE
Consistent language in team settings

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3618]
Since this section is now called `team`, these buttons should say `add team member` and `remove team member`.

<img width="897" alt="Screen Shot 2020-10-21 at 9 23 36 PM" src="https://user-images.githubusercontent.com/5498878/96693498-ce9f9180-13e3-11eb-8916-62f8fb85b271.png">

**Comment by saideepesh000** [comment]
@alanna, hey can I work on this

**Comment by saideepesh000** [comment]
@alanna, can you provide me steps to follow to get the issue. I was not able to find it.

**Comment by Betree** [comment]
@saideepesh000 the file that you need to update with the new strings is located in `opencollective-frontend/components/edit-collective/sections/Members.js`. You'll then need to run `npm run build:langs` to update the language files.
