### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by RichardLitt** [opencollective/opencollective#362]
Perhaps related to https://github.com/opencollective/opencollective/issues/45.

When I try and put in my email (or any email), I get an `Unexpected token < at position 0` error bar, and no confirmation email. I tried this on a private session in Chrome, too, and the same result. I have not tried it in another browser. 

Here is a screencap of me going through this process. https://www.screenmailer.com/v/ntpXSYDQF5aaRVM

**Comment by piamancini** [comment]
hi @RichardLitt I wish everyone reported errors with screencaps like this :D 
It was  a temporary issue with the API. I just tried it and the email went through. You should have received it in your email. 
Closing this! Reopen if it's still not working or you are not seeing the email

**Comment by RichardLitt** [comment]
Works now! Thanks.
