### ISSUE TITLE
Expenses can be filed by any account on any project

### ISSUE THREAD

**Issue by dtugend** [opencollective/opencollective#3621]
**Describe the bug**
Expenses can nowadays be filed by any account on any project.
This is being abused already.

**To Reproduce**
Go to any project when logged in and click submit expense.

**Expected behavior**
I tink it used to be that way that they have to be at least a Team member of the project.
There seems to be no option to restore the old behaviour.

**Additional context**
https://opencollective.com/advancedfx/expenses/26740

**Comment by alanna** [comment]
This is not a bug and it's always worked this way.

However, I do understand why allowing just anyone to submit an expense might be problematic. We are aware of spam issues and have been working hard to create ways to combat them (see #2741).

We are also working on new functionality to enabling inviting someone to submit an expense, where you fill out some details and then they are notified to confirm everything and submit it finally. Perhaps we should consider a Collective-level setting where you can switch off the `submit expense` button for the public and only have expenses via being invited by an admin.

This might go against some of Open Collective's ideals about open participation, but it could be worthwhile in some situations.

**Comment by dtugend** [comment]
My team and me thought it was different before the expense interface update, sorry.
Also seems like a duplicate issue then.

**Comment by alanna** [comment]
I raised #3623 about only allowing invited expenses.
