### ISSUE TITLE
Can't sign in to my account on a second machine.

### ISSUE THREAD

**Issue by Upperholme** [opencollective/opencollective#3622]
**Describe the bug**
When logged in to my open collective user account on my main PC, I'm not able to log in via a second machine, because the login mechanism doesn't operate using a password, and although the UI says it will send me a login link, no email is received if I'm already logged in elsewhere.

**To Reproduce**
1. Log in to OC.
2. Move to a separate PC/laptop
3. Click the 'Sign in' button and enter your email address
4. Note that no email arrives.

**Expected behaviour**
I expect that I should be able to access my OC user account on multiple devices.

**Comment by znarf** [comment]
There is no such limitation, you should be able to sign in, receive the email and authenticate with it.

**Comment by Upperholme** [comment]
Thanks. Just tried it again and it is working. Not sure what was wrong last time I tried it - couldn't get an email.
