### ISSUE TITLE
Invited expenses only setting

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3623]
## User story 
As a Collective admin, I want to control who can submit expenses to my Collective, to have more control over the decision-making process and to combat spam.

## Best solution for this problem
Now that we're creating a feature to invite someone to submit an expense, we could create a Collective-level setting that would turn off the `submit expense` button and only allow admins to invite expenses. This would also greatly cut down on expense spam.

Some Collectives have processes they follow for expenses, such as requirements to submit an issue, or get approved by a vote, or have been picked for a grant, etc. For example, the Open Collective bounty program only pays expenses for bounties from the Engineering Collective that have gone through the bounty approval process.

On the other hand, it goes against the fully open ethos of the Open Collective platform, and creates more paperwork for Collective admins to do. I suspect only a minority of Collectives would turn on such a feature, but it would be quite valuable to some of them.

**Comment by Betree** [comment]
That would be helpful for large collectives like Webpack and Babel that get a lot of spam through expenses.

To complete the specs, I'd say that `ADMIN`s and people who already got an expense paid from the collective (`MEMBER`s in our database) should be exempted from this.

**Comment by alanna** [comment]
@Betree how many spam expenses do larger Collectives deal with? I know we get a lot on OSC and OCF budgets. Do you think this would be a good way to deal with that?

**Comment by Betree** [comment]
> @Betree how many spam expenses do larger Collectives deal with? I know we get a lot on OSC and OCF budgets. Do you think this would be a good way to deal with that?

If we look at Webpack, they get something like one per month lately. They did get more in the past, but it was usually the same person submitting multiple expenses so something like https://github.com/opencollective/opencollective/issues/2694 could help improve the situation.

I think this issue requires more discussion, because a setting to limit who can submit expenses could play against openness and adds some complexity to the process. If the goal is to just target SPAM, there are simpler steps that we should consider before doing it.

**Comment by alanna** [comment]
Yes there are some concerns about openness. 

We have a Collective starting up soon who needs this setting (to prevent SPAM and just lots of expenses in error due to the nature of the community involved), and @znarf agreed to do it as a one-off (just hide the submit expense button for them). I would be OK if we could just request this for special cases where we feel the compromise with less openness is needed. In that case, it's up to the engineers whether we need a feature for it that platform admins can access, or whether our devs can just action it when requested.

**Comment by SudharakaP** [comment]
@alanna : My understanding is that this is the same as https://github.com/opencollective/opencollective/issues/4196 and is now merged. Therefore I am marking this closed but if there's anything more to be done or if you see any issues, feel free to let me know. 😄

**Comment by alanna** [comment]
Yes it's the same. Thanks!
