### ISSUE TITLE
Add Accountant's as BCC on "thank you" emails

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3626]
This is the last part to complete the https://github.com/opencollective/opencollective/issues/3112 plan, now that we have https://github.com/opencollective/opencollective/issues/2867 it should be fairly simple: we need to put accountants as `BCC` in thank you emails.

**Comment by Piedone** [comment]
Do you have a plan to tackle this in the near future?

**Comment by Betree** [comment]
@Piedone We haven't found the time to prioritize it yet, but that's definitely something we want to do. I understand that it's annoying for your use case to not have this feature completed, I'll try to take care of it as soon as possible.

**Comment by Piedone** [comment]
Thanks for the update!

**Comment by Piedone** [comment]
Do we have to configure anything for this, or how will this work?

**Comment by Betree** [comment]
Hi @Piedone, I was about to post a comment here since we just deployed the change. People added as "Accountants" in your settings should now receive all the emails with PDF receipts.

**Comment by Piedone** [comment]
Great, thank you!
