### ISSUE TITLE
Include consolidated receipt PDF in monthly User/Organization reports

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3633]
We want to attach the consolidated PDFs (which already exist in the Payment Receipts section of the "edit collective" menu) to the monthly User/Organization Reports (an email that we are already sending).

![Screenshot 2020-10-27 at 13 47 31](https://user-images.githubusercontent.com/37520401/97310369-0d599f80-185b-11eb-9527-6467fadf29e5.png)

**Comment by sbinlondon** [comment]
Which monthly reports does this need to be generated for? 

Users and orgs only? There are 3 monthly reports from what I can tell: user, org, and collective.

@znarf @Betree

**Comment by znarf** [comment]
Users and Organizations in their monthly report.
