### ISSUE TITLE
Collective Navigation v2: create new "Connect" section

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3634]
Figma design shows a new "Connect" section which combines the "Updates" and "Conversations" section of the Collective page.

![Screenshot 2020-10-28 at 11 22 05](https://user-images.githubusercontent.com/37520401/97429867-eb6e2480-190f-11eb-9c6e-62f10b6851e3.png)

Notes:

* Don't display the "Connect" section if both "Updates" and "Conversations" are turned off

Questions:

* If "Connect" section is turned on in edit Collective settings but both "Updates" and "Conversations" are empty, what do we display? A placeholder image? Or do we hide the section til there is content?

**Comment by sbinlondon** [comment]
Trying to figure out when to not display the new **Connect** section.

Right now it seems that the rules for **Conversations** and **Updates** are:

* both turned on by default for COLLECTIVE
* only **Conversations** turned on by default for ORGANIZATION
* if **Conversations** is enabled but empty, we display it both all users with a 'start a new conversation' CTA
* if **Updates** is enabled but empty, we hide it from non-admins and display the empty section to admins with a 'Use this section to promote your actions and keep your community up-to-date' info box

So what do we want for the **Connect** section?

Do we keep the same conditions as above, and if for some reason both **Conversations** and **Updates** wouldn't normally be displayed, we also don't display the **Connect** section?

To me this means the only reasons we wouldn't display **Connect** are:

* both **Conversations** and **Updates** are disabled
* only **Updates** is enabled but the user viewing is a non-admin user

**Comment by Betree** [comment]
The behavior you describe sounds good to me. As mentioned on the other issue, we need to think about what that means for https://github.com/opencollective/opencollective/issues/3396
