### ISSUE TITLE
Null Donations

### ISSUE THREAD

**Issue by skipjack** [opencollective/opencollective#364]
> Originally brought up in webpack/webpack.js.org#1360...

We're seeing one of our backers come in with `null` donations:

``` json
{
        "id": 2711,
        "createdAt": "2017-01-24T16:38:32.862Z",
        "name": "Angular",
        "firstName": "Angular",
        "lastName": null,
        "username": "angular",
        "role": "BACKER",
        "avatar": "https://res.cloudinary.com/opencollective/image/upload/v1485288529/angular_uxllte.png",
        "website": "https://angular.io",
        "twitterHandle": "angularjs",
        "totalDonations": null,
        "firstDonation": null,
        "lastDonation": null,
        "tier": "backer"
},
```

Is this to be expected or am I correct that something is wrong here? I'm not sure how someone can be a backer without having contributed money.

We fetch the data from this URL:

```
https://opencollective.com/webpack/backers.json?requireActive=false
```

**Comment by piamancini** [comment]
@skipjack is this solved then? Seeing the other issue was closed. cc / @xdamman

**Comment by xdamman** [comment]
I can still see the issue. I need to take a proper look. How important is this? Because we will refactor all this tier system very spoon so I'd rather focus on that.

**Comment by piamancini** [comment]
🥄

**Comment by skipjack** [comment]
I closed the other issue in favor of tracking here. @xdamman it's fairly important to us as we show our backers by donation amount and we don't currently know what that backer's donation amount is. I think it was someone from that organization who created the issue.

**Comment by piamancini** [comment]
@skipjack what's causing the bug is that we added Angular manually, since they gave money to webpack before your collective was created. Since they didn't actually make a donation through the platform, it is showing 'null' as the total amount donated. For the moment the solution would be to remove them as backers.

**Comment by piamancini** [comment]
@skipjack heads up: removing angular from the backers table to solve this. Also, we shouldn't allow backers with 0 amount on the platform.

**Comment by skipjack** [comment]
@piamancini great thanks for the follow up, yeah I was a bit confused by the null donation.

> removing angular from the backers table to solve this.

@sokra @TheLarkInn does this mean we need to add angular to our `additional-sponsors.json` file?
