### ISSUE TITLE
Collective Navigation v2: create new Collective page navbar actions menu

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3640]
Part of https://github.com/opencollective/opencollective/issues/3639

![Screenshot 2020-10-28 at 12 15 49](https://user-images.githubusercontent.com/37520401/97435490-64717a00-1918-11eb-908b-1a33f825496c.png)

Actions panel includes:

* Contact Collective
* Submit expense
* Request grant
* Apply to host (if host)

**Comment by sbinlondon** [comment]
@znarf @Memo-Es What's the expected behaviour of 'Apply to this host' in the actions menu?

<img width="669" alt="Screenshot 2020-11-05 at 19 27 54" src="https://user-images.githubusercontent.com/37520401/98287347-2241db80-1f9d-11eb-93fa-d277d0fc94a3.png">

Currently, if we visit a Host page and see the `ApplyToHostBtn`:

* if we're logged out, it says 'Apply' and we click it and it takes us to `opencollective.com/apply` and we create a Collective, which then also applies with it to the Host

* if we're logged in, it says 'Apply to this host with {collective}' where `{collective}` is (I think) the latest Collective you've created that is able to apply to a host. From here we either:
    * open a modal, with info about the Host, and then click 'Apply'
    * or if the button has `showConditions={false}` then it just applies directly with that Collective

So what should happen here?

Should I:

* update the `ApplyToHostBtn` to look like it does in the design, but also display 'Apply to host with {collective}'?
* do we keep the text exactly as it is in the design here and it opens a modal where we choose the Collective we want to apply with?
* it takes us to a standalone page?

The last two options would be more work and out of scope.

**Comment by sbinlondon** [comment]
Following conversation yesterday, the MVP for this project is going to be:

* find every collective that we could apply to a host with and render a menu card for that

![image](https://user-images.githubusercontent.com/37520401/98661640-a352f700-233e-11eb-85d3-9260f209d4b9.png)

There is going to be an additional project following Collective Navigation v2 to address the 'apply to host' button more in depth.

**Comment by sbinlondon** [comment]
More clarifications:

* If there are no calls to action that will be rendered in the ACTIONS menu, then we don't render the ACTIONS menu at all

**Comment by sbinlondon** [comment]
Still to do:

- [ ] make sure we are including all CTAs like in the current navbar
- [ ] [make it accessible](https://github.com/opencollective/opencollective/issues/3696)

**Comment by sbinlondon** [comment]
> Still to do:
> 
>     * [ ]  make sure we are including all CTAs like in the current navbar
> 
>     * [ ]  [make it accessible](https://github.com/opencollective/opencollective/issues/3696)

@Betree

**Comment by sbinlondon** [comment]
@Betree I saw you finished the accessibility but had you also added all the CTAs to make sure there is parity with the old navbar CTAs? If everything's done can we move this to the "Done" column?

**Comment by Betree** [comment]
> I saw you finished the accessibility but had you also added all the CTAs to make sure there is parity with the old navbar CTAs?

I haven't tested nor worked on that part, it's still a todo
