### ISSUE TITLE
Collective Navigation v2: create new Collective page navbar sections menus

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3641]
Part of https://github.com/opencollective/opencollective/issues/3639

### Design 
Individual section drop-down menus:

![Screenshot 2020-10-28 at 12 00 42](https://user-images.githubusercontent.com/37520401/97439147-b5d03800-191d-11eb-8b61-4eb4686ea14e.png)

### Behaviour

* Only visible on desktop and tablet
* Hover to open the category section drop-down menu
* Clicking one of the menu items takes you to the standalone page

**Comment by sbinlondon** [comment]
@Memo-Es @znarf  Another questions, do all these menu items lead to standalone pages, or can they link to parts of the main Collective page?

For example, Transactions and Expenses are both standalone pages that exist (`/collective/expenses` and `/collective/transactions`). But there is no standalone page (that I know of) for Team or About. So would those just link to `/collective/#section-about`?

**Comment by sbinlondon** [comment]
Speaking to Memo on Slack: 

* drop down menus are only visible in sub pages, in the Collective page when you click on a menu element it drags you where that section is in the page

**Comment by Betree** [comment]
Tackling this one with https://github.com/opencollective/opencollective/issues/3640 and https://github.com/opencollective/opencollective/issues/3751 as they're related.
