### ISSUE TITLE
Editing expense form - grant application 

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#3647]
**Describe the bug**
We received a number of expenses submitted as grant applications through ATX Mental Health Fund. As the needed documentation was missing the collective admin was attempting to edit the expense form to include the attachments. However, when they saved the information it seems like it is not being updated. 

**To Reproduce**
1. Go to budget --> expenses and select an expense. 
2. Click on Edit button
3. Update the address (that was missing when initially the individual completed the form) and go through to the expense details to include an attachment
4. Click save and then try to review the form again --> the attachment won't be showing 

**Expected behavior**
Collective admin or host admin should be able to update the form when changes are required, which would include getting an attachment in place. 

**Important to note** right now user is not required to include an attachment when selecting the Grant option and this needs to be changed.

**Comment by Betree** [comment]
@kewitz maybe related to #3645?

**Comment by kewitz** [comment]
This was already fixed.
