### ISSUE TITLE
Transaction missing from data export

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3648]
An admin of [this Collective](https://opencollective.com/openmined) exported their transaction data, but they can't find [this expense](https://opencollective.com/openmined/expenses/24568) listed. We have confirmed that it was definitely paid.

> when i download our entire transaction report, i am not seeing it anywhere. i have searched his name, the dollar amount, and the expense name with no success. i see in the thread that the last update was "Expense error".

Theories:

* It's related to that `expense error` thing
* It's related to the fact that we merged multiple Collectives into one - the old one was openmined-primary
* Something else?

**Comment by znarf** [comment]
I see a transaction entry dated November 11th, seems this was troubleshooted out of GitHub and the issue was not updated.
