### ISSUE TITLE
Radio-button behaviour when you set a custom host fee

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3649]
If you go to host dashboard > hosted Collectives > set custom fee and click into the box and type in a custom fee, the radio button should automatically jump to the custom option, not stick on the global option. Right now even if you set a custom fee it can still be stuck on the global option and it's really easy to miss that. Alternatively, the box to put the fee in should be disabled until you select the custom fee radio button.

<img width="448" alt="Screen Shot 2020-10-30 at 9 14 23 PM" src="https://user-images.githubusercontent.com/5498878/97677038-7f99e080-1af6-11eb-8100-29153c7d24e6.png">

**Comment by terminator0309** [comment]
![image](https://user-images.githubusercontent.com/57085155/97721802-ea93e900-1aef-11eb-8c95-63b84821ca35.png)
@alanna is this correct for this issue. Or this is not the right way to do this?

**Comment by Betree** [comment]
@terminator0309 `document.getElementById` is not a good react practice. Also `onFocus` might not be the right place to handle that, because navigating with the Tab key will then change the option.

I recommend making the switch in the `onChange`.

**Comment by terminator0309** [comment]
![image](https://user-images.githubusercontent.com/57085155/97956761-8747d680-1dcf-11eb-8262-c1ee40b37959.png)
@Betree 
i am getting this error when trying to open "My Collectives" through the drop down menu in nav bar.

**Comment by Betree** [comment]
@terminator0309 Try to `npm install` then restart the server

**Comment by terminator0309** [comment]
@Betree 
![image](https://user-images.githubusercontent.com/57085155/98253152-b2cdeb00-1fa0-11eb-816c-b399b6ec35ed.png)
what do you think about this! Disabling the input box until the radio button is checked.

**Comment by Betree** [comment]
@terminator0309 this won't match the expected behavior described above. What we want is to have the radio button selected whenever you click inside of the input.
