### ISSUE TITLE
Automatically invoice hosts pending platform tips and fees

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#3650]
We need a worker that runs at the beginning of each month and invoice Hosts how much is owed to the platform related to Tips and Fees that may have been collected during the contribution flow.

Right now, we automatically collect these tips and fees for donations if they're processed through Stripe, ~but this will change with the new business model~ but we still can't do it for PayPal, manual transactions, and internal transfers.

What we want:
- [x] Trackability: the invoice should contain one row for each order it is collecting tips from;
- [x] Invoice should be in Host's currency, meaning we need to convert the net amount of the tip transaction back to the host's currency. use `data.hostToPlatformFxRate`;
- [x] Flag this is an invoice is a settlement and track which transactions are being settled in this invoice for accounting. (store in `data`)

**Comment by znarf** [comment]
Per strategic decision, we will continue to take Platform Tips at source for Stripe transactions, and we should try to take them at source whenever possible. It's currently not possible for PayPal and Bank Transfers and this is why we need this strategy.

**Comment by alanna** [comment]
I think we need to zoom out a little on this. It should not just be platform tips but all host fees owed (i.e. soon the 15% of host fees we will charge as platform fees). We're rethinking platform fees and there will be several streams to combine, which should all be on one invoice, and we're moving toward requiring host budgets be activated so we can submit these charges as expenses and use our own system. We should be creating all related features with these changes in mind.

Here's how I think it should work....

The system adds up:

* platform tips contributed not via stripe
* platform fees - 15% of host fees charged not via stripe
* platform tips the host decided when adding funds manually (#3652)

Then it automatically creates an expense on the host budget for the amount owed. We need to figure out the details, e.g. will the payout method be a setting the host can change (paypal, bank transfer), will the expense go in already approved, etc.

We also need to somehow include documentation of the platform fees/tips already collected via stripe, but these amounts never reached the host's account so they shouldn't be charged in the expense total. Maybe they should be listed in the expense details or the attached invoice but not contribute to the expense total amount.
