### ISSUE TITLE
Add platform tips box to add funds form

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3652]
As a host admin, I want to contribute platform fees to OC sometimes when I add funds manually, but my process is not always to charge host fees at this point (for example, I am not charging any host fees on an internal grant, or I have already taken out the fundholder fees from the total I am adding to the Collective), so the system can't take the 15% automatically in those cases. Instead there should be an optional platform tips input (a % or a flat $ amount), which is added to my monthly platform fees invoice/expense.

Related: #3650 

![Screen Shot 2020-10-25 at 11](https://user-images.githubusercontent.com/5498878/97770191-09e55180-1b96-11eb-9bfa-22d255cd0211.jpg)

**Comment by SudharakaP** [comment]
@opencollective/core : As discussed, I will be working on this one starting next week. 😄

**Comment by kewitz** [comment]
@SudharakaP let me know if you need a walkthrough in the platform tip implementation, we can schedule one for Monday.

**Comment by SudharakaP** [comment]
@kewitz : That would be wonderful. Thanks a lot. 🤗

**Comment by SudharakaP** [comment]
@Memo-Es : Just summarizing what we discussed in our meeting today on how the platform tips selection should appear; some of the ideas were,

1) Include the platform tips as a percentage (one input). 

2) Include platform tips as a flat amount (one input).

3) Include platform tips as a percentage and flat amount (two input). 

I think we need to clarify this point a bit further on what exactly should be set in the front end. Especially if we decide to go with the third case in which case we need to clarify how exactly they should behave (setting one should disable the other or auto populate the other amount). I'll post on slack and maybe we could arrange a small meeting to discuss. 😄

**Comment by SudharakaP** [comment]
@Betree @znarf @kewitz : I've done an initial draft of the platform tip selection implementation. A screen-cast can also be found the the PR; https://github.com/opencollective/opencollective-frontend/pull/5922. I think there's a few points to reiterate and left to do. 😄 

1) For now I've made the Platform Tip selection only appear when the Platform Fees are not appearing. I am wondering whether there's any use case to specify both Platform Tip and the Platform Fee at the same time. If so let me know and I could change accordingly. 

2) Adjust the platform tip selection according to the design discussions we will have tomorrow. 

Please take a look at the PRs and feel free to let me know if there's anything else to be added. Finally thanks much for taking the time explaining me about the platform tips and providing me with clarifications today. 👍🏽

**Comment by alanna** [comment]
The Platform Fees box only appears to Platform Admins, IIRC. The main users of this feature are non-platform-admin fiscal host admins. Basically, if it's something only platform admins see, it's OK if it's a bit confusing/ugly/lots of boxes, so no need to worry about it much. The main goal is for those external host admins to be able to add a tip when manually adding funds.

**Comment by SudharakaP** [comment]
An updated design for the platform tip box selection has been provided by design (thanks @Memo-Es 👍🏽).
 
https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC.com%5D-Production-Ready-%E2%9C%85

![image](https://user-images.githubusercontent.com/12435965/109100873-8ae2ce80-76da-11eb-924c-0af4bcda3ac8.png)

I'll work on adding the fixed amount selection box as per the above design tomorrow. In the meantime if there's anything else to be done on this please feel free to let me know. 😄

**Comment by SudharakaP** [comment]
@opencollective/core : I've completed adding the fixed platform tip input box as well and as per design when we enter a value on the fixed amount and focus out of the input it auto calculates the percentage and vice versa. In addition I've made the `Add funds` button disabled when the total amount is negative (in case the platform tips + host fees etc goes above the total funding amount). I think this completes the requirements for this issue, but if there's anything else you see please feel free to let me know. 😄 😯 

Herewith I have added an updated screen-cast. 

![Platform Tips - Final](https://user-images.githubusercontent.com/12435965/109123048-41a47600-76fe-11eb-909f-82e10cdfebf9.gif)

**Comment by SudharakaP** [comment]
@opencollective/core : So just want to write here some of the things we discussed in the demo before I forget it over the weekend; 

1) We have yet to come to a consensus on whether to only include the platform tips fixed amount selection or to include both fixed amount and percentage. 

2) We have to finalize whether to add platform tips as an amount added on top of the fund or an amount that is subtracted from the fund amount (just like we have for fees). 

3) We have to decide on whether to move the platform tips selection inputs below description and source inputs. 

Please feel free to let me know if I missed anything important here. 😄 

cc: @alanna

**Comment by alanna** [comment]
A note based on the screencast above: If a host fee applies, Open Collective already takes its platform fee as 15% of that. So platform tips are only relevant when the host fee is 0%. This might simplify the UI design, since you really only need the `host fee` box or the `platform tips` box to be active, not both—but if this actually complicates the logic more, then it's ok to have both there next to each other for this first iteration.

To answer the questions in the above comment:

1. I think having both options available is great. But if it's blocking the feature moving forward, it's OK to just pick one or the other. Users can work around it manually, i.e. if they know the dollar amount they can calculate the percentage and vice versa. It's just a bit nicer to make it easy for them.
2. This is a tricky one! I can see arguments both ways. We could make it like host fees, where the fees are taken out of the total, or we could make it like platform tips works on contributions, where it is added on top. Either way, we just need to make it super clear to the user so they know how to use it for their desired outcome. If the `platform tips` and `host fee` boxes are going to be visible side by side, then we should probably make them both work the same way, otherwise it could be confusing (i.e. make platform tips work like host fees here, where it's taken out of the total instead of added on top).
3. No opinion—seems fine either way.

**Comment by alanna** [comment]
I just watched the demo video. I agree with @piamancini that this tip is something given by the *Host* not the Collective, so it doesn't make sense for it to come out of the total added, and should be on top. I see what @znarf means about the money actually might not be there if we add it on top, but I think we should assume that the Host intends to pay it from fee revenue or they will add funds and that's OK.

Will the platform tip be associated with this transaction, i.e. if you look at the transaction details will it say $x to Collective, $y Host fee, $z Platform tip? I think that would be quite confusing to the Collective and its funders because they will have no idea about how the Host pays the Platform, and we don't want them to deal with that complexity. I think the tip should just show on the Platform Settlement transaction, not on the transaction where the funds were added to the Collective. This is another argument to make the tip on top, not subtract it from the amount added to the Collective.

**Comment by SudharakaP** [comment]
@alanna : Thanks much for the input. 😄 👍🏽 

> A note based on the screencast above: If a host fee applies, Open Collective already takes its platform fee as 15% of that. So platform tips are only relevant when the host fee is 0%. This might simplify the UI design, since you really only need the `host fee` box or the `platform tips` box to be active, not both—but if this actually complicates the logic more, then it's ok to have both there next to each other for this first iteration.

I'll leave the host fee box for this first iteration of this as removing it can be done in number of ways which we should probably discuss. A few ways I can think of are,

1) Add a radio button to choose between host fees and platform tips. 

2) Add logic to auto disable the host fee box upon adding amounts in the platform fee selection boxes and vice versa. 

I am partial to the first method (adding a radio selection input) as the second one (auto disabling method) complicates the logic on UI side and could I think potentially lead to bugs. 😄 

> To answer the questions in the above comment:
> 1. I think having both options available is great. But if it's blocking the feature moving forward, it's OK to just pick one or the other. Users can work around it manually, i.e. if they know the dollar amount they can calculate the percentage and vice versa. It's just a bit nicer to make it easy for them.

I don't see any thing blocking here so I am leaving it as it is. 

> I just watched the demo video. I agree with @piamancini that this tip is something given by the _Host_ not the Collective, so it doesn't make sense for it to come out of the total added, and should be on top. I see what @znarf means about the money actually might not be there if we add it on top, but I think we should assume that the Host intends to pay it from fee revenue or they will add funds and that's OK.

I've added support for adding the platform tip on top of the amount. Please see screen-cast below. 😄 

> Will the platform tip be associated with this transaction, i.e. if you look at the transaction details will it say $x to Collective, $y Host fee, $z Platform tip? I think that would be quite confusing to the Collective and its funders because they will have no idea about how the Host pays the Platform, and we don't want them to deal with that complexity. I think the tip should just show on the Platform Settlement transaction, not on the transaction where the funds were added to the Collective. This is another argument to make the tip on top, not subtract it from the amount added to the Collective.

As I see it, it will not say `$x to Collective, $y Host fee, $z Platform tip`. If you look at the collective transactions it will say what is being given to the collective (no platform tip). And if you look at the user's transactions it will show both the platform fees and the amount given to the collective as separate transactions. The screen-share below I think will clarify matters. 

What do you mean by the platform settlement transaction; is it the same as the users transaction which I've shown in the screen-share or something different? 😄 

![platform-tips-on-top](https://user-images.githubusercontent.com/12435965/109438957-2f1d8b80-79e1-11eb-8193-9e42db4f4bf9.gif)

**Comment by alanna** [comment]
> if you look at the user's transactions it will show both the platform fees and the amount given to the collective as separate transactions

Who is the "user" in this case? The profile selected as the source of funds? That's not really correct. 

The place the platform tip should come from is not the same as the source of funds being added. The funds are from the financial contributor. The tip is from the Host. So the main funds being added should appear as a debit on the payer profile's transactions and a credit on the Collective profile's transactions, while the platform tip should appear as a debit on the Host's budget and a credit on Open Collective's budget, and not be associated with the Collective or Payer's transactions. Tips are all accounted on the Platform settlement expense, so this kind of tip should be the same.

**Comment by SudharakaP** [comment]
> > if you look at the user's transactions it will show both the platform fees and the amount given to the collective as separate transactions
> 
> Who is the "user" in this case? The profile selected as the source of funds? That's not really correct.
> 
> The place the platform tip should come from is not the same as the source of funds being added. The funds are from the financial contributor. The tip is from the Host. So the main funds being added should appear as a debit on the payer profile's transactions and a credit on the Collective profile's transactions, while the platform tip should appear as a debit on the Host's budget and a credit on Open Collective's budget, and not be associated with the Collective or Payer's transactions. Tips are all accounted on the Platform settlement expense, so this kind of tip should be the same.

Ah, that makes sense. Thanks for the explanation. 👍🏽  Currently the platform tip is taken from the profile selected as the source. So we need to change that. I'll work on it this week and get back. 😄

**Comment by SudharakaP** [comment]
So, I've made the changes so that the platform tip is taken from the host budget as [explained above](https://github.com/opencollective/opencollective/issues/3652#issuecomment-787572929c). Herewith I am attaching a screen-cast. Let me know if this matches the requirement exactly. 😄 

Just to reiterate note that here the source is the user `Sudharaka`, the collective that is being funded is `Agora Collective` and the host corresponding to this collective is `JHipster`. The platform tip is going from the host (`JHipster`) to open collective whereas the source of funds is from `Sudharaka` to `Agora Collective`. 

![platform-tips-refactor](https://user-images.githubusercontent.com/12435965/109734923-afc1c080-7b76-11eb-8386-7096a5be2f28.gif)

**Comment by aminakazi** [comment]
Production Ready file: https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=10518%3A29405

**Comment by SudharakaP** [comment]
@aminakazi : Thanks for the design. 

Will start working on this. 😄

**Comment by SudharakaP** [comment]
@opencollective/core-developers : Just wondering since there had been no further updates for this issue for a while, is everything good with the PRs for this one or is there anything that needs to be changed modified further? 😄 😸
