### ISSUE TITLE
Display total contributed on Funds

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3655]
In #3589 we removed the `total contributed` number at the top because it was misleading for Collectives. However, now it's gone from Sponsor profiles where it's the most important number, e.g. https://opencollective.com/salesforce - you can't see anywhere how much they have contributed, and that's the key thing this profile page exists to show.

I'm not sure what we should do here exactly. Maybe a `sponsor` profile type with a design emphasising this number? Or a user-selectable setting to display or not display it?

There is also now a big blank space where this number used to be that looks odd.

![Screen Shot 2020-11-02 at 11 25 56 AM](https://user-images.githubusercontent.com/5498878/97816966-3c11c300-1cfe-11eb-95bb-633b212c703c.png)

**Comment by Betree** [comment]
It's because `Salesforce` is not an `ORGANIZATION` anymore, it's now a `FUND`. The number is still displayed for organizations and individuals that are not hosts.

We could add a setting to display that, but before adding more complexity we should maybe define the expectations for each account type.

**Comment by alanna** [comment]
We need a solution to this. I'm about to go out with the contributor leaderboard and if someone clicks through they won't be able to see how much that sponsor has contributed.

**Comment by znarf** [comment]
1) We nee to make sure that metrics is exposed in the API and up to date. It was `Collective.stats.totalAmountSpent` in v1. Should this include only Financial Contributions or should this also contain Expenses Paid (FUNDs are often contributing by paying Expenses).

2) Then it can be simply displayed like this:

<img width="472" alt="Screenshot 2020-12-09 at 16 17 25" src="https://user-images.githubusercontent.com/806/101648412-12a13100-3a3a-11eb-85e5-f868f9b31ef2.png">

**Comment by piamancini** [comment]
that's a good first step -

**Comment by Betree** [comment]
> Should this include only Financial Contributions or should this also contain Expenses Paid (FUNDs are often contributing by paying Expenses).

Expenses were removed from the computation of this number last week, based on this feedback: https://github.com/opencollective/opencollective-api/pull/4962. It again surfaces the fact that collectives have different expectations for what should be displayed here, based on how they're operating.

**Comment by znarf** [comment]
It's live ! https://opencollective.com/chrome

<img width="1325" alt="Screenshot 2021-02-09 at 21 50 13" src="https://user-images.githubusercontent.com/806/107426817-01030500-6b21-11eb-9f0a-729b1a1062dd.png">
