### ISSUE TITLE
Monster button in conversation email notification

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3659]
<img width="633" alt="Screen Shot 2020-11-03 at 5 19 15 PM" src="https://user-images.githubusercontent.com/5498878/97949529-c6d6e880-1df8-11eb-865f-d73f818d21ae.png">

**Comment by Betree** [comment]
@alanna could you forward me the email?

**Comment by alanna** [comment]
This is happening on more notifications:

<img width="764" alt="Screen Shot 2020-11-04 at 10 10 47 AM" src="https://user-images.githubusercontent.com/5498878/98040972-13b4d080-1e86-11eb-8e4e-5e2f42d36938.png">

I forwarded the emails to ben.
