### ISSUE TITLE
Should I make a collective for my org? Or for my repo?

### ISSUE THREAD

**Issue by trusktr** [opencollective/opencollective#3661]
OpenCollective.com presents two options:

- [ ] Create a collective for the repository
- [ ] Create a collective for the organization

I couldn't find any recommendations on which to pick. What's the advantage of one over the other? When should we pick one or the other?

Can we switch options, or enable both, later?

**Comment by Betree** [comment]
Hi @trusktr, this choice doesn't make a huge difference. If your project is something that mainly rest in a single repo (ie. a code library) then "repository" should be the right choice. If it's a set of multiple repos (ie. a website with a frontend + an API) then "organization" should be picked. The one you choose will affect:
- What the Github icon on your profile will link to
- What will be used for the stars verification: if you pick "repository", it needs to have 100+ stars. If you pick "organization", one of the repositories under this org needs to have 100+ stars.
