### ISSUE TITLE
User menu: wrap email address

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3662]
Long email addresses are not looking good in the user menu

![image](https://user-images.githubusercontent.com/1556356/98121956-4247a100-1eb0-11eb-87b6-a53ffc9ddffa.png)

**Comment by vickywane** [comment]
@Betree I would like to fix this. 

Would it be better to just truncate the email address after it grows out of the viewport and append "..." to it?

**Comment by Betree** [comment]
I think it would be better to display the full email, only to jump to a new line (`word-break: break-all`).

But truncating (with CSS) is a valid option too.

**Comment by vickywane** [comment]
@Betree I just added the `word-break: break-all` to the default props of the P tag since this issue might occur in other parts of the frontend. Is the right thing to do or should I pass it as a prop to work only in the `TopBarProfileMenu` component?
