### ISSUE TITLE
Misaligned "One-click Login" Button in Login Email

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#3664]
**Describe the bug**

In the login email we send the "One-click Login" button that is used to login is misaligned with too much padding at the bottom. 

**To Reproduce**

1. Go to https://staging.opencollective.com
2. Click on Sign In
3. Go to your email and open the login email from OpenCollective

**Expected behavior**

The "One-click Login" button should not have unnecessary padding at bottom. 😄 

**Screenshots**

![image](https://user-images.githubusercontent.com/12435965/98142329-8325c280-1e7c-11eb-961b-f1f50809cb8e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser: FireFox
 - Version: 82.0 (64-bit)

**Comment by Betree** [comment]
Thanks for the report @SudharakaP, it's actually a duplicate from https://github.com/opencollective/opencollective/issues/3659 but we haven't pushed the fix yet. It's on its way

**Comment by SudharakaP** [comment]
@Betree : Ah, I missed that, sorry for the duplicate. 😄
