### ISSUE TITLE
Increase Width of Fees Column in Comparison Table

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#3665]
**Describe the bug**

The fees column of the comparison table at https://docs.opencollective.com/help/product/comparison is too small in width to accommodate the content. Since a scroll bar is present in the bottom I think we should increase the min width of this column. 

**To Reproduce**

Go to https://docs.opencollective.com/help/product/comparison and take a look at the comparison table at bottom. 

**Screenshots**

![image](https://user-images.githubusercontent.com/12435965/98424584-f2e7a900-2046-11eb-88cf-024c7400ec94.png)

**Comment by SudharakaP** [comment]
If a core member could confirm that this is something that needs to be done, I'll just submit a PR. 😄

**Comment by Betree** [comment]
@SudharakaP That would be welcome. I'm not sure how customizable Gitbook (that we use for these docs) is on this topic.

**Comment by SudharakaP** [comment]
@Betree : I haven't used Gitbook at all, but I'll take a look tomorrow to see what we can do. 😄

**Comment by SudharakaP** [comment]
Doesn't seem this is possible in a straightforward manner. It seems that the line breaks on Gitbook is automatic and given that the content of the row is not a proper sentence it seems to break it at weird places. :thinking:

Therefore I am closing this issue; but if anyone has any ideas on how to make Gitbook customizations on these column widths please feel free to reopen. 😄

**Comment by Betree** [comment]
Maybe something we can try is to use non breaking spaces (https://en.wikipedia.org/wiki/Non-breaking_space)

**Comment by SudharakaP** [comment]
@Betree : If I remember correctly, I tried this but for me it didn't work. It shows up in the preview mode in Gitbook but when I deploy it it doesn't seem to show. 🤔
