### ISSUE TITLE
Approval email is received twice when sending via Open Collective mailing list

### ISSUE THREAD

**Issue by RCheesley** [opencollective/opencollective#3667]
**Describe the bug**
When sending an email via the Open Collective mailing list address on our event, I receive the confirmation email twice for the same email.

**To Reproduce**
1. Send email to collective event
2. Receive two email requests to confirm with identical content

**Expected behavior**
One email should be enough ;) 

**Screenshots**
![screenshot-mail google com-2020 11 09-11_02_00](https://user-images.githubusercontent.com/2930593/98533595-16933500-227b-11eb-9a48-1f13dabd267d.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version Version 86.0.4240.183 (Official Build) (x86_64)

**Comment by SudharakaP** [comment]
@RCheesley : Hi, I was trying to reproduce this but couldn't so maybe I am doing something wrong. 🐼  Here to send emails are you using the updates feature of the event? 🐨

**Comment by Betree** [comment]
@SudharakaP this bug is about a feature we've deprecated and already removed from the frontend: https://github.com/opencollective/opencollective/issues/4131. I have a [PR](https://github.com/opencollective/opencollective-api/pull/5991) open to remove the feature entirely, so this is a `wontfix`.

**Comment by SudharakaP** [comment]
@Betree : Ah, that makes sense now. 😄
