### ISSUE TITLE
Feature request: data visualisations

### ISSUE THREAD

**Issue by emilerousseau** [opencollective/opencollective#367]
I would like to be able to see data visualisations regarding the flow of money too and from Open Collectives. I am fairly new to full stack but it is my understanding that it would be possible to output from your PostgreSQL database via an API (I like Phoenix quite a lot at the moment, and just switched to it from Django, but it could be nearly anything; or perhaps your current API layer could be adapted?) and perform the required manipulations and functions via something like the D3.js library.

My concern with Open Collective at present is that while a good idea in theory it doesn't really seem to be addressing problems with the less well-off and less well connected in the industry, particularly those who might have problems fitting in but nevertheless do have technical skills, or to be addressing problems with industry nepotism and hegemonies which may exist among sections of the technology community (I am considering the recent anti-trust cases against Google, for example).

If it were possible to use the data and work you have already done to produce graphical output which was interesting and readily understandable to those outside the tech bubble it might be possible to show where problems really exist and to develop logical, coherant and effective strategies to raise awareness, but also to directly address these problems wherever they are shown to exist, perhaps even at a post-intersectional level that develops a new meritocracy within coding, without unduly stigmatising people who are new to coding, or who may struggle with certain kinds of conceptual frameworks or specific kinds of learning.

I am no expert but I do have some skills I may be able to use to aid in this if you feel it would be useful.

**Comment by piamancini** [comment]
this is not sth we can tackle now. Closing, we can revisit in the future

**Comment by PeterDavidCarter** [comment]
If this is a technical issue I understand. But there's this thing I can't shake, where no matter the opportunities I'm offered and the cushy jobs I have I always need to stick up for the worst off and recently and previous this has cost me my livelihood. But at the same time when I was close to nothing I kicked into a mode that was all survival. So I understand the closing of this ticket, I guess, though I don't approve.
