### ISSUE TITLE
 Collective Navigation v2: update edit collective 'profile page' sections

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3671]
Since we're updating the sections we have and what goes in them, we'll also need to update the part of the edit collective menu that allows admins to enable/disable features on their collective page.

<img width="1218" alt="Screenshot 2020-11-10 at 10 57 52" src="https://user-images.githubusercontent.com/37520401/98665450-9ab0ef80-2343-11eb-943a-dd7551478791.png">

Details TBA

**Comment by alanna** [comment]
Great! Let's please remove the confusing/conflicting seperate sections for `conversations` and `updates` settings. #3396 

I discussed this with @Betree and I think we concluded there's no need for seperate settings for these two and it can just be managed from the profile page settings like all the other sections.

**Comment by sbinlondon** [comment]
> Great! Let's please remove the confusing/conflicting seperate sections for `conversations` and `updates` settings. #3396
> 
> I discussed this with @Betree and I think we concluded there's no need for seperate settings for these two and it can just be managed from the profile page settings like all the other sections.

Have opened issue for this here: https://github.com/opencollective/opencollective/issues/3755

Closing this issue as @Betree is working on it and has made his own issue https://github.com/opencollective/opencollective/issues/3751
