### ISSUE TITLE
Variable names showing in expense summary

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3674]
![Screen Shot 2020-11-12 at 9 49 03 AM](https://user-images.githubusercontent.com/5498878/98873801-ded7f780-24dd-11eb-9e56-8579e9cf1d48.png)

https://opencollective.com/foundation/expenses/27896

Appearing on the summary screen but goes away once the expense is submitted, it seems.

**Comment by Betree** [comment]
I think that's the same one already reported in https://github.com/opencollective/opencollective/issues/3672
