### ISSUE TITLE
Rename master branch to main in all OpenCollective repos

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#3675]
It would be nice to rename and migrate the default branches of the open-collective repos to `main`. The process of doing so is summarized here; 

https://dev.to/swyx/move-primary-git-branch-from-master-to-main-m7c

GitHub will eventually support [seamless re-targetting of PRs and branch protection policies etc](https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-) at the end of the year and I wonder if we should wait for them or start now itself. 🤔 

In any case I am listing down the main repositories so that we can keep track. Please feel free to add, remove or modify if I've missed anything. 😄 

- [x] opencollective

- [x] opencollective-frontend

- [x] opencollective-api

- [x] opencollective-images 

- [x] opencollective-pdf

- [x] opencollective-rest

- [x] opencollective-changelog

- [x] documentation

- [x] opencollective-taxes

- [x] opencollective-setup

- [x] opencollective-emails

- [x] opencollective-bot

- [ ] ~opencollective-github-helpers~ (Nothing to rename here)

- [ ] ~opencollective-workers~ (Nothing to rename here)

- [ ] ~opencollective-watch~ (Nothing to rename here)

**Comment by Betree** [comment]
Thanks for sharing @SudharakaP! Would be great to wait for Github to implement what's described in the [link you shared](https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-) as it will make the process way easier.

**Comment by SudharakaP** [comment]
@Betree : Yes, for sure. Although it will still probably take some manual effort to change the CI and code and documentation mentions of `master`.

**Comment by SudharakaP** [comment]
@Betree : Just to note that now we can [rename the branches to main through the GitHub UI](https://github.com/github/renaming#renaming-existing-branches). However we need to sync this with the updates to all the CI workflows I believe. If there's no objections I'll create some PRs in the coming days for each repo and we can go forward with hit. However I don't have much insight on other impact of this such as the deployments; they probably need to be updated as on that end. 🤔

**Comment by Betree** [comment]
It's a big change, we need a team consensus and to make sure we properly document the impacts before making the switch.

**Comment by SudharakaP** [comment]
@Betree : Sure, thanks for letting me know. Should I stop here and wait for team consensus or I can continue and do all the PRs in the next few days, so when it's discussed and if agreed upon we have everything ready? 😄

**Comment by SudharakaP** [comment]
@Betree : I've gone ahead and submitted PRs to each repo described above with the changes; so that we are ready if we decide to go forward with this. From the code it seems there's some CircleCI integration which needs to be accounted as well. Anyways, let me know if you need any further help from my end for this. 😄 😄

**Comment by SudharakaP** [comment]
>     * See if  developers need to update anything in their local setup, and publish instructions if needed (a post in https://github.com/orgs/opencollective/teams/developers/discussions would be nice)

For the developer local setup, I think the following GitHub instructions covers what needs to be done; https://docs.github.com/en/github/administering-a-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes. Maybe if we are doing this, we can post these instructions in the discussions some days prior so that most contributors will see what's coming. 😄

**Comment by Betree** [comment]
We now have a team agreement on that one. I propose the following plan to move forward: 
1. Publish the notice for developers
2. Start migrating the side projects (pdf, taxes, etc), properly testing deployments for each of them
3. Publish a notice on Slack, then migrate frontend and API
