### ISSUE TITLE
Default avatar

### ISSUE THREAD

**Issue by pierreneter** [opencollective/opencollective#368]
Hi there,
Should we return a default avatar for non-avatar users?

Let see:
![webpack-backers](https://user-images.githubusercontent.com/12815768/28999603-48255ea0-7a76-11e7-981f-2b8d4d1e5dd9.png)
(https://webpack.js.org)
Although in the json file (https://opencollective.com/webpack/backers.json?requireActive=false) returns the data of backers that contain the URLs of the avatars but they are empty.
Here are URLs:
* https://opencollective-production.s3-us-west-1.amazonaws.com/danawoodmancom_7bada460-bd8b-11e6-9ca1-bb6c7a9a84e0.png - avatar of Dana Woodman https://opencollective.com/danawoodman
* https://d1ts43dypk8bqh.cloudfront.net/v1/avatars/5e2529e2-ca5e-495c-8e2f-facb62961cdc  - avatar of Adam Howard https://opencollective.com/a

In opencollective.com avatars are default image: https://opencollective.com/public/images/users/avatar-01.svg

**Comment by emilerousseau** [comment]
Have you read: https://medium.com/the-mission/silicon-valley-has-a-problem-problem-b34437a57e99 ?

**Comment by piamancini** [comment]
we return avatars. re-open if this happens again
