### ISSUE TITLE
Add link between /hosts and /discover

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3681]
Sometimes users end up at https://opencollective.com/hosts when they are looking for Collectives, and at https://opencollective.com/discover when looking for hosts. It would be helpful to have links between them in case the user isn't finding what they are looking for. We should have a great search function where we can find everything with useful filters, but until we can build that a simple link will help.

**Comment by Betree** [comment]
https://github.com/opencollective/opencollective/issues/2605 is currently being tackled by a contributor

**Comment by Betree** [comment]
> We should have a great search function where we can find everything with useful filters, but until we can build that a simple link will help.

@alanna The search function now allows this. Should we rather focus on #2970?

**Comment by alanna** [comment]
Yes, better to just do #2970 if it's going to be worked on soon. The link idea was more of a stopgap.

**Comment by scenaristeur** [comment]
Shouldn't this issue be closed if https://github.com/opencollective/opencollective/issues/2970 has been merged ?

**Comment by Betree** [comment]
Both pages are indeed merged now, thanks for noticing @scenaristeur :+1:
