### ISSUE TITLE
Custom OCF apply flow

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3683]
We designed the process to onboard a fund from the [apply button](https://tafka.d.pr/vTZhFZ) of the [OCF homepage](https://opencollective.foundation/) 

| 1. Intro  | 2. Fees  | 3. Form  | 4. Success  |
|---|---|---|---|
| ![1](https://user-images.githubusercontent.com/49539954/99208824-3351d000-2787-11eb-83b2-d4f0a2899c81.png)  |    ![2](https://user-images.githubusercontent.com/49539954/99208822-3351d000-2787-11eb-8f69-77ee8aee6f34.png)|  ![3](https://user-images.githubusercontent.com/49539954/99208819-32b93980-2787-11eb-9f37-b3c16dcce276.png) | ![4](https://user-images.githubusercontent.com/49539954/99208816-31880c80-2787-11eb-884a-c761ab4fd01f.png)  | 

Check the [design file](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=8202%3A1) in figma 🎨

@znarf @piamancini @alanna

**Comment by vickywane** [comment]
@Memo-Es if this is not a feature to be worked on internally, I would be excited to implement these designs @Memo-Es @alanna @znarf

**Comment by Betree** [comment]
For the frontend part, Formik should ideally be used to manage the state of the form since there are many fields.

On the API part, the way we store data should be defined by https://github.com/opencollective/opencollective/issues/3715.

**Comment by vickywane** [comment]
@Betree is [this](https://github.com/opencollective/foundation-website) the correct repository for the [OCF](https://opencollective.foundation/) ?

**Comment by Betree** [comment]
@vickywane for OCF website, yes. The implementation for this issue however is to be done in Open Collective's codebase.

We're still not sure about the plan for this, but it's a complex project so more likely to be tackled internally or by an existing contractor (outside of the bounty program).

**Comment by vickywane** [comment]
Alright then.

**Comment by Betree** [comment]
This issue will be resolved by https://github.com/opencollective/opencollective-frontend/pull/5623, but we'll need to iterate with https://github.com/opencollective/opencollective/issues/3844 to make sure we display the form data in the host dashboard.

**Comment by znarf** [comment]
@Memo-Es Why do we have 2 times the checkbox for "I agree with the terms of Fiscal Sponsorship"? Step 1 and Step3.

**Comment by znarf** [comment]
<img width="731" alt="Screenshot 2021-01-14 at 14 17 18" src="https://user-images.githubusercontent.com/806/104596719-a33fe200-5674-11eb-8e82-5c9efa18c7dd.png">

@Memo-Es @piamancini the copy at Step "success" is weird:
- it's implying that the application is gonna be accepted, not that it's gonna be reviewed
- if the user created an account in the process, there is no mention of it, do they need to do something? They're gonna receive an email about their account creation and collective/fund creation, what should they do about it?

Generally, what is the expected next step for the User, an email saying that their application was accepted?

**Comment by Memo-Es** [comment]
> @Memo-Es Why do we have 2 times the checkbox for "I agree with the terms of Fiscal Sponsorship"? Step 1 and Step3.

We wanted to make sure folks take acquaintance of that in those two moments of the process... Seems overkill to you? @znarf 

Agree with the success page copy change. I'm gonna wait for Pia's input to put it in the design.

**Comment by znarf** [comment]
> We wanted to make sure folks take acquaintance of that in those two moments of the process... Seems overkill to you? 

@Memo-Es I don't know any process where I need to check a box 2 times for the same thing. So yeah, overkill. Or, at least check it by default the second time it appears.

**Comment by Memo-Es** [comment]
Yeah. I'm removing it from step 3, so the first thing you do is acknowledge the terms of fiscal sponsorship; it also seems less likely that a user reads both links after filling the form
@znarf @flickz

**Comment by Memo-Es** [comment]
### Design update
---

Included a flow for registered users to apply with an existing collective

| 1. Intro  | 2. Fees  | 3. Form  | 4. Success  |
|---|---|---|---|
| ![1 (Registered)](https://user-images.githubusercontent.com/49539954/106231482-708b0300-61b7-11eb-8e7c-98002c15e241.png)  |    ![2 (Registered)](https://user-images.githubusercontent.com/49539954/106231489-72ed5d00-61b7-11eb-94ab-2097f8844e2c.png)|  ![3 (Registered)](https://user-images.githubusercontent.com/49539954/106231488-7254c680-61b7-11eb-8ce9-e1aa1e0d7497.png) | ![4 (Registered)](https://user-images.githubusercontent.com/49539954/106231486-71bc3000-61b7-11eb-9a62-a9e06b28f3f4.png)  | 

See the [production-ready file](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=8202%3A1) on figma

**Comment by Betree** [comment]
Implemented in https://github.com/opencollective/opencollective-frontend/pull/5833
