### ISSUE TITLE
Fixing Tai Collective setup

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3685]
I need some help fixing up a new host which has encountered some snags in setup.

They have set up this Collective: https://opencollective.com/tai-collective

Here's what's needed:

1. The creator set up the fiscal host as [himself](https://opencollective.com/ian-tairea) but actually this should be a self-hosted Collective. So there should be a fiscal host called Tai Collective with its budget on, and no other Collective (although they might add more later).
2. He manually added $12,000 of funds to see how the system works, but now needs this undone. In that process he created an [organization profile](https://opencollective.com/te-tīhi-o-ruahine-whānau-ora-alliance) for the sponsor but put himself as the admin of it. He wants to undo all that and start over, so both the organization and the transaction should be deleted.
3. He connected Stripe, which is NZD, but the system did not set the currency to NZD and it's still showing USD. (We tried to reconnect Stripe in `receive money` settings, but clicking the button throws an `api error`.) The currency needs to be set to NZD.
4. He gave $10 himself to see how that worked - that can stay or it can be undone (whatever's easier - I'm worried the currency thing might get complicated so if deleting that or refunding it, etc, is easier, that's fine).

**Comment by znarf** [comment]
1. Not possible now, the feature is not released and may take one more month to be fully available.
2. Done
3. Done. Not sure what happened. There are some reported issues when connecting Stripe but we haven't be able to nailed it yet
4. Done

**Comment by alanna** [comment]
THank you!
