### ISSUE TITLE
Search with Algolia: pagination is not working properly

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3688]
**Describe the bug**
When searching with Algolia, the pagination returns inconsistent results. For example, you'll get 37 pages for the `test` keyword, but some pages will contains 20 items and others only 18 or 17. This is probably because we filter the results from Algolia after they are returned to us (see https://github.com/opencollective/opencollective-api/blob/94a5765f03a93fb0a8411517342b66b5f952af63/server/lib/search.js#L175).

**To Reproduce**
1. Go to https://opencollective.com/search?q=test

**Expected behavior**
Page should contain the maximum number of items (20) unless it's the last one.

Maybe now is a good time to switch to SQL search?

**Comment by znarf** [comment]
Yeah, everything will be much easier with SQL search.
