### ISSUE TITLE
Fiscal Host Section in Edit Collective is not Mobile Optimized

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#3695]
**Describe the bug**

I noticed that the Fiscal Host section within the Edit Collective screen isn't behaving well on mobile devices. The description should probably appear below the collective image. 

**To Reproduce**
1. Go to a collective you have admin rights.
2. Click on settings (near the logo).
3. On the left hand side, select Fiscal Host. 

Note: You'll have to do the above in a mobile device or use the browser dev tools. 

**Expected behavior**

I believe the description should appear below the collective image as otherwise it makes it difficult to read. 

**Screenshots**

<details>
<summary>>>Screenshot<<</summary>

![Screen Shot 2020-11-18 at 21 45 24](https://user-images.githubusercontent.com/12435965/99626665-8de96700-29e7-11eb-9813-88c41d3b4dfc.png)
</details>

**Comment by piamancini** [comment]
+ 1 to fixing this

**Comment by alinamanko** [comment]
That looks like something we should fix to maximise user experience
