### ISSUE TITLE
Collective Navigation v2: use features endpoint to selectively fetch collective page GraphQL data

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3699]
Make use of the new features endpoint and navbar categories to only fetch data for features which are:

* supported for the collective
* and are enabled
* and have data

**Comment by Betree** [comment]
This is how we proceed nowadays with the `NavbarFields` fragment introduced in https://github.com/opencollective/opencollective-frontend/pull/5415. We iterated a few times and most pages should now be covered:
- https://github.com/opencollective/opencollective-frontend/pull/5513
- https://github.com/opencollective/opencollective-frontend/pull/5530
- https://github.com/opencollective/opencollective-frontend/pull/5622
- https://github.com/opencollective/opencollective-frontend/pull/6537
