### ISSUE TITLE
Fix CSS for Donation flow for no Stripe connected collectives

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#37]
When a collective is open and host has not connected their stripe account yet, there is an overlap of the box and the text in donation flow. https://cldup.com/YB4ZCux-ip.png

**Comment by asood123** [comment]
We should probably just show the button and grey it out.

**Comment by carlosascari** [comment]
@piamancini  @asood123 Done
https://github.com/OpenCollective/website/pull/174
