### ISSUE TITLE
Add keyboard shortcuts to modals

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3701]
*Initial idea suggested by @znarf*

## User story 
As a power user, I can navigate through modals with keyboard shortcuts.

## Best solution for this problem
For all modals:
- `Esc` should close the modal

If corresponding prop is `true`:
- `Enter` should confirm the modal (only when not dangerous, ie. not for "Delete account")

**Comment by vickywane** [comment]
I would work on this @Betree

**Comment by Betree** [comment]
@vickywane you may want to look at this helper recently introduced in the codebase: https://github.com/opencollective/opencollective-frontend/blob/master/lib/hooks/useEscapeKey.js#L3

**Comment by vickywane** [comment]
@Betree I would modify your helper hook to make it reusable for the `Enter` key also. 

Also, I cant use it for class components so I manually added them to the class components using the component lifecycles
