### ISSUE TITLE
Next.js 404 Page Missing

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#3704]
**Describe the bug**

It seems that Next.js is expecting a 404 page when we customize the `_error.js` page. When a 404 error is thrown the following message is displayed in console; 

```
Warning: You have added a custom /_error page without a custom /404 page. This prevents the 404 page from being auto statically optimized.
See here for info: https://err.sh/next.js/custom-error-no-custom-404
```
I suggest adding a 404 error page specifically for 404 errors to take advantage of [Next.js static optimization](https://nextjs.org/blog/next-9-3#automatic-static-optimization-for-404). If we could come up with the content or design of the 404 page, I am willing to quickly construct it. 😄 

**To Reproduce**

- Just go to some non-existent page and notice the console. 

**Additional context**

Reference: https://github.com/vercel/next.js/blob/master/errors/custom-error-no-custom-404.md

**Comment by Betree** [comment]
To be confirmed, but I think the reason for this is that's because we have a fallback route (`pages.add('collective', '/:slug', 'collective-page');`) that will be called for any unknown path, thus we can't really end up on a 404 template.

**Comment by SudharakaP** [comment]
> To be confirmed, but I think the reason for this is that we have a fallback route (`pages.add('collective', '/:slug', 'collective-page');`) that will be called for any unknown path, thus we can't really end up on a 404 template.

Sure let me know. Yes, that is my understanding too; but I was wondering if we could replace that route with the 404 page so as to leverage static optimization; since for non-existent collective page we just show the `Not Found` and two buttons. 🤔

**Comment by sbinlondon** [comment]
Just to add the info I said to @Betree on Slack:

Ben posted this error stack that we get every so often. The dev server crashes at this point and all that is displayed is a blank page that says "Internal server error" and you have to restart it to see the app again.

```
TypeError: Cannot destructure property 'components' of 'object null' as it is null.
    at DevServer.renderToHTMLWithComponents (/home/user/Workspace/Projects/opencollective/opencollective-frontend/node_modules/next/dist/next-server/server/next-server.js:57:246)
    at DevServer.renderErrorToHTML (/home/user/Workspace/Projects/opencollective/opencollective-frontend/node_modules/next/dist/next-server/server/next-server.js:103:332)
    at async DevServer.renderErrorToHTML (/home/user/Workspace/Projects/opencollective/opencollective-frontend/node_modules/next/dist/server/next-dev-server.js:34:1204)
    at async DevServer.renderToHTML (/home/user/Workspace/Projects/opencollective/opencollective-frontend/node_modules/next/dist/next-server/server/next-server.js:102:1094)
    at async DevServer.renderToHTML (/home/user/Workspace/Projects/opencollective/opencollective-frontend/node_modules/next/dist/server/next-dev-server.js:34:578)
    at async DevServer.render (/home/user/Workspace/Projects/opencollective/opencollective-frontend/node_modules/next/dist/next-server/server/next-server.js:52:236)
```

We thought it was related to the out of memory crashes but I'm pretty sure now it isn't. This error stack is all about what @SudharakaP is describing - us not having a custom 404 page.

https://github.com/vercel/next.js/blob/658810815035e55a7031f27c5a6f3c01baa31ccf/packages/next/next-server/server/next-server.ts#L1409

When we fall into trying to render an error page, and have _/error but not _/404, we get that warning and in the try/catch block below it attempt to call renderToHTMLWithComponents with a null result argument.

https://github.com/vercel/next.js/blob/658810815035e55a7031f27c5a6f3c01baa31ccf/packages/next/next-server/server/next-server.ts#L994

Then in that function you can see they try to destructure the null result arg, which throws the TypeError: Cannot destructure property 'components' of 'object null' as it is null. error.

So they render 'Internal server error' as the HTML and send it, and you have to restart the dev server. https://github.com/vercel/next.js/blob/658810815035e55a7031f27c5a6f3c01baa31ccf/packages/next/next-server/server/next-server.ts#L1434

**Comment by Betree** [comment]
> Ben posted this error stack that we get every so often. The dev server crashes at this point and all that is displayed is a blank page that says "Internal server error" and you have to restart it to see the app again.
> 
> ```
> TypeError: Cannot destructure property 'components' of 'object null' as it is null.
>     at DevServer.renderToHTMLWithComponents (/home/user/Workspace/Projects/opencollective/opencollective-frontend/node_modules/next/dist/next-server/server/next-server.js:57:246)
>     at DevServer.renderErrorToHTML (/home/user/Workspace/Projects/opencollective/opencollective-frontend/node_modules/next/dist/next-server/server/next-server.js:103:332)
>     at async DevServer.renderErrorToHTML (/home/user/Workspace/Projects/opencollective/opencollective-frontend/node_modules/next/dist/server/next-dev-server.js:34:1204)
>     at async DevServer.renderToHTML (/home/user/Workspace/Projects/opencollective/opencollective-frontend/node_modules/next/dist/next-server/server/next-server.js:102:1094)
>     at async DevServer.renderToHTML (/home/user/Workspace/Projects/opencollective/opencollective-frontend/node_modules/next/dist/server/next-dev-server.js:34:578)
>     at async DevServer.render (/home/user/Workspace/Projects/opencollective/opencollective-frontend/node_modules/next/dist/next-server/server/next-server.js:52:236)
> ```

I get this error pretty much each time I checkout a different branch. Would be really great if we can solve it, I'm happy to help or to provide more logs if needed.

**Comment by SudharakaP** [comment]
@Betree @sbinlondon : I've made a pull request with a custom 404 page which I think should handle this. As far as I see the fallback route (`pages.add('collective', '/:slug', 'collective-page');`) isn't effected by this and will take precedence. But if you go to a url such as  `http://localhost:3000/generator-jhipster/sklfjsdkljsdklj` then the `404.js` will page will show up. So I guess adding a 404 page doesn't effect that route; correct me if I am wrong. 🤔

**Comment by Betree** [comment]
Just a note to say that this hasn't solved my "Cannot destructure property 'components'" issue, I'm still getting that whenever I checkout a different branch

**Comment by SudharakaP** [comment]
> Just a note to say that this hasn't solved my "Cannot destructure property 'components'" issue, I'm still getting that whenever I checkout a different branch

@Betree : Yeah, I see that too; guess it's not related to this unfortunately. Will take a look. 🤔

**Comment by SudharakaP** [comment]
@Betree : Just to confirm all those branches you were switching to; do they have the 404 page? I was testing this with some more recent branches (all of which includes the `404.js`) and I couldn't get the `Cannot destructure property components` issue. 🤔

**Comment by Betree** [comment]
@SudharakaP I think so because I was testing with rebased ones, but can't confim with 100% certitude. I'm taking note of this in case it happens again

**Comment by SudharakaP** [comment]
@

> @SudharakaP I think so because I was testing with rebased ones, but can't confim with 100% certitude. I'm taking note of this in case it happens again

Yes, please do post back if you see it again with rebased ones; I'll be happy to investigate some more on this. 🤔
