### ISSUE TITLE
2FA: release 2FA for host payouts to more hosts on prod

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3708]
2FA for payouts with adjustable rolling limit has been released to Open Source Collective on prod.

This issue is for collecting feedback and discussing improvements, and making a plan for releasing it more widely.

**Comment by znarf** [comment]
@sbinlondon I see no reason to not release it for everyone.

**Comment by znarf** [comment]
Maybe correct the following bugs first:
- https://github.com/opencollective/opencollective/issues/3770
- https://github.com/opencollective/opencollective/issues/3769

**Comment by sbinlondon** [comment]
Bugs corrected - should we try rolling it out @znarf? Or do we want to do recovery codes first? https://github.com/opencollective/opencollective/issues/3709

**Comment by znarf** [comment]
We can roll out.
