### ISSUE TITLE
2FA: way to login if 2FA is inaccessible

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3709]
## User story 
_As user with 2FA enabled on my account login, I have the ability to bypass 2FA using a set secure method (i.e. recovery codes) so that I can access my account if I lose my phone, etc._

## Best solution for this problem
Potentially recovery codes. See research section below.

## Metrics 
Fewer users contacting support about losing/switching phones and other problems related to 2FA.

## Documentation 
Add a full 2FA section to the docs, including: adding 2FA to your account, apps you can use, how/where to store recovery codes (if that is the method we use), how to turn it off from your account, etc.

## Research

Recovery codes seem to be the best way to do this. [Github uses them](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/recovering-your-account-if-you-lose-your-2fa-credentials), and so does Netlify (who also have a [great blog post](https://www.netlify.com/blog/2020/07/07/two-factor-authentication-is-live-on-netlify/) all about their 2FA.)

I found some good discussion on the [Python Package](https://github.com/pypa/warehouse/issues/5800) repo about their implementation of 2FA recovery codes.

Alternative methods of account recovery:

* **SMS**: Used by [Google](https://support.google.com/accounts/answer/185834?hl=en) among other places. Add a backup phone number to your account to receive a code to get into your account.
* **Security key**: [Also used by Google](https://support.google.com/accounts/answer/185834?hl=en). Basically like a security question, you have a memorable phrase or something to get into your account. 

Both of these seems far less secure than recovery codes.

**Comment by sbinlondon** [comment]
Discussion welcome - recovery codes seem to be the way to go but interested in other ideas. @znarf @Betree @kewitz

**Comment by znarf** [comment]
@sbinlondon Can you propose an implementation proposal for the recover codes?

**Comment by kewitz** [comment]
Recovery codes seem the way to go, we could generate a set of codes based on the existing key.

I think it is equally important to remember that we already expose the raw key when setting up two-factor authentication, it is the manual entry for the QRCode, and this can be used to set up the same OTP generator on different devices.
Technically this is might not be the best practice, but neither using an app that allows you to back up and restore your OTP gen codes.

**Comment by Betree** [comment]
Recovery codes are good, we must make sure the endpoint to use them is strongly rate limited.

We also need to think about a support procedure in case someone loses their 2FA and doesn't have any recovery code.

**Comment by sbinlondon** [comment]
# Proposal

## Frontend

### Generating recovery codes

I propose keeping the same flow for implementing 2FA, but adding a second step. I think Netlify's way of doing this is really good. We could shamelessly implement this in our design style:

![image](https://user-images.githubusercontent.com/37520401/101673917-b5b07580-3a4f-11eb-9e89-86a06d535f28.png)

![image](https://user-images.githubusercontent.com/37520401/101673935-b943fc80-3a4f-11eb-9fd3-ff79dc138ea4.png)

Gitlab also offers a button that downloads the codes into `gitlab-recovery-codes.txt` so maybe we can offer that as well.

Once the person has their recovery codes, we will display the 2FA settings page with the "good job, you set up 2FA", and instead of what we have now (see below) we could implement an "advanced" section which includes generating new recovery codes and also the ability to remove 2FA from your account. This advanced section could be protected by 2FA (enter code to view the section) or we can just make sure that any action you take in the advanced section requires 2FA to execute.

![Screenshot 2020-12-09 at 18 57 02](https://user-images.githubusercontent.com/37520401/101674540-8bab8300-3a50-11eb-8a5a-8de94a2ce162.png)

### Using recovery codes

During the sign-in flow, when you are prompted to enter your 6-digit 2FA code, we could display a link underneath for "Having trouble?" like Github does. We can do this either always, or after a failed attempt to enter the code.

![image](https://user-images.githubusercontent.com/37520401/101674968-0ffe0600-3a51-11eb-9dcf-6083d7049a06.png)

Then the modal would change to the recovery code modal.

![image](https://user-images.githubusercontent.com/37520401/101675109-489ddf80-3a51-11eb-95d9-327e7bdf1117.png)

If the recovery code goes through, great, we sign them in. If not perhaps we allow them one more try, then we take away the input and replace it with a message asking them to get in touch with support.

## API

### Generating and storing recovery codes

When a user enables 2FA on their account and we store the hashed secret on the `User` table in `addTwoFactorAuthTokenToIndividual`, we could also:

* within the mutation generate 6 recovery codes and store them (hashed) in an array within `user.data` (rather than adding yet another column to the table)
* return from the mutation the list of recovery codes and display them on the frontend for the user to store

They should be [hashed with a random algorithm](https://security.stackexchange.com/questions/62640/generating-backup-codes-for-a-2fa-implementation) like the secret and not use any user data or identifiable seed.

Requesting new recovery codes will remove all current recovery codes, however many are left, and replace them.

### Using recovery codes

As @Betree mentioned, it should have its own endpoint and it should be strongly rate limited. I would suggest 2, maximum 3, attempts per user before we ask them to get in touch with support. I'm not sure if we'd want that limit to be per day or total - input please.

If a recovery code is successful, we remove it from the array. Once the user is down to 1 or 2 recovery codes left, we might return a message from the endpoint as they are logging in to remind them to go to their settings and generate new ones.

If the recovery code is unsuccessful, they run into the rate limiting and we return a message asking them to get in touch with support to gain access to the account.

-----------

Feedback and discussion welcome. I'm not really sure where to start on a proposal for the support process to recover an account if all methods of access are lost.

**Comment by kewitz** [comment]
I think that's a good solution to our problem. Just remember to ask for the 2FA code before generating new codes.

**Comment by znarf** [comment]
> we store the hashed secret

> within the mutation generate 6 recovery codes and store them (hashed) 

> They should be hashed with a random algorithm like the secret and not use any user data or identifiable seed.

Let's not confuse hashing and encrypting, these are not the same things. In all these cases, it's encryption not hashing.

> As @Betree mentioned, it should have its own endpoint

As stated a few weeks ago on Slack, "I’m seeing the term `endpoint` being used in the context of GraphQL to describe what should be normally named `query`, `mutation` or `field`. `endpoint` in GraphQL world has a different meaning. In our case, we have 2 different endpoints, one for each of our schemas, API v1 endpoint https://api.opencollective.com/graphql/v1 and API v2 endpoint https://api.opencollective.com/graphql/v2

- Where precisely are we gonna store the recovery codes in the User table? How are we gonna generate them? 
- Can we avoid creating a new mutation for the recovery path? Can we use the existing one and have a special parameter?
- Rate limiting doesn't have to be part of the first version, I can look into it later.

**Comment by Betree** [comment]
Just want to mention the [RateLimit](https://github.com/opencollective/opencollective-api/blob/feat/rich-host-application/server/lib/rate-limit.ts) helper because we often forget that it exists, yet it makes rate limiting very easy:

```es6
const myCall = () => {
  const rateLimit = new RateLimit(`limit_key_${req.ip}`, myLimit);
  if (!(await rateLimit.registerCall())) {
    throw new Error();
  }

  // Anything below will be rate limited
  // ...
}
```

**Comment by sbinlondon** [comment]
> Let's not confuse hashing and encrypting, these are not the same things. In all these cases, it's encryption not hashing.

Have updated my comment

>     * Where precisely are we gonna store the recovery codes in the User table? How are we gonna generate them?

In the `data` column, I guess in a key called `recoveryCodes`? It feels weird to name them so plainly but they'll be encrypted.

For generation we can use this npm package [`crypto-random-string`](https://www.npmjs.com/package/crypto-random-string) which creates strong random strings, and then further encrypt them using our `crypto-js` package.

>     * Can we avoid creating a new mutation for the recovery path? Can we use the existing one and have a special parameter?

Yes they would be generated and stored during `addTwoFactorAuthTokenToIndividual` and returned from that mutation to display the codes for the first time. Then when using a recovery code during sign in we wouldn't be using a mutation would we, just a request?

>     * Rate limiting doesn't have to be part of the first version, I can look into it later.

Will try using the helper @Betree mentioned unless it's proving to be a blocker

**Comment by znarf** [comment]
> Then when using a recovery code during sign in we wouldn't be using a mutation would we, just a request?

Yes, sorry for the confusion, no mutation there indeed.

**Comment by znarf** [comment]
How do we ensure we'll never expose the recovery codes? Even by mistake. Even encrypted.

Following our discussion from yesterday, maybe they should actually have their own column instead of being in `data`?

**Comment by sbinlondon** [comment]
Sure that makes sense. I think that would be good as well for when we want to get in touch to have current 2FA users generate recovery codes - we can check for users where `twoFactorAuthToken` is not null and `twoFactorAuthRecoveryCodes` is null.

**Comment by SudharakaP** [comment]
@Betree @znarf : Correct me if I am wrong, but it seems to me everything in this issue is done, and thus we can close this. If no objection I will go ahead and close this issue? 🤔

**Comment by Betree** [comment]
Recovery codes are live indeed.

We still need to document a procedure internally for people who have no recovery code and want to reset 2FA (we had a few of them already) to define what criteria we want to use based on the account level (contributor, host admin, etc). But it's handled manually atm, and not overwhelming so there's no rush.

**Comment by znarf** [comment]
Please have https://github.com/opencollective/opencollective/issues/4466 in mind. We kind of failed there.
