### ISSUE TITLE
Broken image and Edit link on Docker Kisumu

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#371]
Edit button in event and header image broken

link: https://opencollective.com/dockerkisumu/events/orchestration-1

**Comment by piamancini** [comment]
@nicobarretoOC Is this still an issue? I see it on my end.

**Comment by nicobarretoOC** [comment]
I send a message to them asking to test, the header and logo are working. I'm wondering if the edit button worked...

I re-sent a message today to check if everything is fine.
