### ISSUE TITLE
2FA: ability to turn off 2FA if you don't want it for login anymore

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3711]
## User story 
_As user with 2FA enabled on my account login, I can turn off 2FA (without contacting OC) if I don't want to use it anymore._

## Best solution for this problem

![Screenshot 2020-11-24 at 17 28 50](https://user-images.githubusercontent.com/37520401/100130392-8f4ce080-2e7a-11eb-85f9-7556c952808c.png)

* A user can go to the "Two-factor authentication" menu section in their profile settings to turn off 2FA
* Below (or instead of) the "Two-factor authentication is enabled on this account. Well done! 🎉" message, we can have a danger button that says "Turn off 2FA for my account"
* It would open a modal or display a form field inline for the user to input their 2FA code one last time, as well as warnings about removing the 2FA
* If they input the code correctly, we remove the two factor auth token from their user info in the database

A button on the 2FA section in the profile settings menu that you click to turn off 2FA. You must use 2FA one more time to turn it off.

## Metrics 
Fewer users contacting support to have 2FA removed from their account.

## Documentation 
Add a full 2FA section to the docs, including: adding 2FA to your account, apps you can use, how/where to store recovery codes (if that is the method we use), how to turn it off from your account, etc.

**Comment by sbinlondon** [comment]
@znarf Does this implementation sound ok to you?

**Comment by znarf** [comment]
@sbinlondon Yes, it sounds good.
