### ISSUE TITLE
Remove "member" from user-facing messages

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3712]
* `"members.pending.details": "This member has not approved the invitation to join the collective yet"`
* `"paymentMethod.monthlyLimitPerMember.label": "Monthly limit per member"`
* `"transaction.refund.info": "This action will reimburse your contributor for the full amount of their contribution and they will still be a member of your Collective."`

**Comment by Betree** [comment]
Seems that all these were addressed by https://github.com/opencollective/opencollective-frontend/pull/5834
