### ISSUE TITLE
Steps component bubbles aliasing

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3716]
The steps component that's mainly used in the contribution flow seems to have some aliasing on the bubbles (the lines are not smooth). For me this only happens on **Chrome**, Firefox is displaying them fine.

There seem to be some conversations about that on the Internet, suggesting to use a hack with `box-shadow`. But if there's no clean way to solve it with CSS, I think we should just render the bubble with SVG.

![image](https://user-images.githubusercontent.com/1556356/100106268-a5ea3c00-2e68-11eb-94f4-89cb76db45e0.png)

![image](https://user-images.githubusercontent.com/1556356/100106442-d7630780-2e68-11eb-90ac-632f837230a4.png)

**Context**
- Browser: Version 87.0.4280.66 (Official Build) (64-bit)
- OS: Linux Mint

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

Either proposed solutions will be accepted as valid (as long as they solve the problem!). The one with the SVG might be the simplest one to implement.

**Comment by leonardohofling** [comment]
@Betree I'll work on it, okay?

**Comment by Betree** [comment]
@leonardohofling Sure! Let me know if you need anything. I think you're already familiar with the component right? If I remember correctly you implemented its mobile version last year :slightly_smiling_face:

**Comment by leonardohofling** [comment]
Yes, I did. I'll start later and if I need something I'll let you know.
Thanks

**Comment by Betree** [comment]
:trophy: This issue has been completed by @leonardohofling  

To claim the **$200** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
