### ISSUE TITLE
Broken donate buttons script on widgets

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#372]
Donate button scripts aren't rendering. They are giving the broken image icon. This is true even on the widgets doc page. 

Yakkee Collective is having that problem.

**Comment by piamancini** [comment]
thanks @nicobarretoOC can you please add the images that Aaron shared on the bug report email and if you are able to repro it, please add console logs. 
cc / @xdamman

**Comment by nicobarretoOC** [comment]
Yes, just give me a couple hours untill I get back to a computer.

**Comment by xdamman** [comment]
Also any URL I can look at? (I.e. Where the button widget has been placed)

**Comment by nicobarretoOC** [comment]
He says he is trying to get the embebed HTML widget working, he mentions that it is also not loading on the widgets page on the blog post html code. I think it might be something about the image link? 

The script option works perfectly, it is the html one that seems to have trouble loading the image.

![widget](https://user-images.githubusercontent.com/30665166/29194159-0491d4c2-7dee-11e7-8a0c-9b71d0e41cb4.jpg)

**Comment by xdamman** [comment]
Fixed. thanks for reporting the issue.
