### ISSUE TITLE
Expense policy showing up twice

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3721]
If you submit an expense to OSC, you see the expense policy repeated in the sidebar. Is this because it's doing it once for the Host and once for the Host's budget Collective?

![Screen Shot 2020-11-25 at 11 24 40 AM](https://user-images.githubusercontent.com/5498878/100158412-01700480-2f11-11eb-8d13-0320569dcf23.png)

Also:  why does it say "FISCAL HOST Open Source Collective 501(c)(6) **(pending)**"?

**Comment by Betree** [comment]
> Is this because it's doing it once for the Host and once for the Host's budget Collective?

Good catch, indeed. We should not display that when host === acccount.

> why does it say "FISCAL HOST Open Source Collective 501(c)(6) (pending)"?

We should investigate that, this is normally displayed when the account has not approved the application yet but OSC seems to have all the flags right in the DB, so it's probably a frontend issue.

**Comment by znarf** [comment]
The "Pending" thing is related to https://github.com/opencollective/opencollective-frontend/pull/5274
