### ISSUE TITLE
Link to 2FA should go straight to 2FA settings in a new tab

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3722]
I tried to pay an expense and saw this:

![Screen Shot 2020-11-25 at 11 28 01 AM](https://user-images.githubusercontent.com/5498878/100158810-a25ebf80-2f11-11eb-9d0a-676b21e188cc.png)

When I clicked `account settings` it jumped me to the main profile settings screen in the same window. Instead, it should link directly to the 2FA section, and it should be in a new tab so I don't lose the expense I was paying.

**Comment by Betree** [comment]
Ping @sbinlondon
