### ISSUE TITLE
Receipt PDFs not being attached to "ticket confirmed" emails

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3726]
_Noticed through https://opencollective.slack.com/archives/C6JTTA4SK/p1606238962131200_

We're not attaching PDF receipts to "ticket confirmed" emails (the one sent when ordering a ticket from an event).

Email template: `templates/emails/ticket.confirmed.hbs`

**Comment by sbinlondon** [comment]
I will have a look at this today! Thanks for flagging.
