### ISSUE TITLE
Apply to a fiscal host behaviour - Implementation

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3728]
Adding to the modal designed for the 'Create Collective Flow' project, That is displayed when the user admin of the new Collective goes for the 'Fiscal host' option when choosing how to receive contributions and click the 'Apply' button on any of the cards from the fiscal hosts' options.

We are adding a dropdown (Collective picker) to choose the Collective you are applying with, adding the option to create a Collective applying to that host in the process.

| Application modal | Mockup w/ modal  | Create a Collective and apply  |
|---|---|---|
| ![Fiscal host application modal](https://user-images.githubusercontent.com/49539954/100257773-ea7ae380-2f0b-11eb-842c-379468a90419.png)  | ![Desktop](https://user-images.githubusercontent.com/49539954/100257075-22355b80-2f0b-11eb-84ba-1e9a869f89c6.png)  |  ![Create Collective](https://user-images.githubusercontent.com/49539954/100257776-eb137a00-2f0b-11eb-8ed7-e88403736589.png) |

See the 🎨 [design file](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=8637%3A0) in figma

I'm closing #2282 to start clean with the implementation with a new issue.

@piamancini @alanna @znarf @Betree

**Comment by Betree** [comment]
This is perfect, thank you @Memo-Es.

Related: #3715

**Comment by Betree** [comment]
Implemented in https://github.com/opencollective/opencollective-frontend/pull/5555
