### ISSUE TITLE
Change React Static Boilerplate collective repository

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#373]
Your message from gitter: 

Change the repository URL on this collective? https://opencollective.com/react-static-boilerplate https://github.com/koistya/react-static-boilerplate => https://github.com/kriasoft/react-static-boilerplate

Original message from gitter [here](http://mailtracking.gitter.im/track/click/30050491/gitter.im?p=eyJzIjoibTVsV0djLUFQVmpNSW42Y01ycEFYTFh4WFJNIiwidiI6MSwicCI6IntcInVcIjozMDA1MDQ5MSxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2dpdHRlci5pbVxcXC9rb2lzdHlhI3V0bV9zb3VyY2U9bm90aWZpY2F0aW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXVucmVhZC1ub3RpZmljYXRpb25zXCIsXCJpZFwiOlwiOWJmNzIyYTQ0NmM3NDk2ZWI3ZTA4Njg4Y2U0OGU4M2VcIixcInVybF9pZHNcIjpbXCI3YjY3ZTA3ZGQ4MzRmZWNiZGNjYjFlNTAxNzc5ZTAzMmVhMDFlYjgzXCJdfSJ9)
--

**Comment by piamancini** [comment]
done, also letting him know on gitter
