### ISSUE TITLE
New collective navigation: empty contributions section

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3737]
For type USER if they don't have any activity on their profile, `CONTRIBUTIONS` section is showing up in the navbar but not being rendered.

This is both with or without the `NEW_COLLECTIVE_NAVBAR` feature flag.

<img width="1300" alt="Screenshot 2020-11-26 at 11 40 31" src="https://user-images.githubusercontent.com/37520401/100346745-41e88480-2fdc-11eb-94be-738801f94dee.png">

**Comment by Betree** [comment]
It's related to the "Hibernating in the north pole" issue. More info here: https://github.com/opencollective/opencollective/issues/3473#issuecomment-701930591

**Comment by sbinlondon** [comment]
Right! I see. There are lots of 'empty section' designs in the Figma. I was having trouble thinking of when to implement those but perhaps now is a good time.
