### ISSUE TITLE
New collective navigation: empty collective page sections/empty collective page

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3738]
We have new designs for empty sections with the navigation v2 project so we need to implement them.

Follow-on issue from https://github.com/opencollective/opencollective/issues/3473

# Empty category sections

If a category section has no data yet, we will display the following designs

<img width="472" alt="Screenshot 2020-11-26 at 12 36 39" src="https://user-images.githubusercontent.com/37520401/100351872-0ce03000-2fe4-11eb-964f-8f9463515e2d.png">

<details>
<summary><h3><strike>Empty collective page (done)</strike></h3></summary>

If a collective is new and there's no data for any section, we would display this

<img width="829" alt="Screenshot 2020-11-26 at 12 33 59" src="https://user-images.githubusercontent.com/37520401/100351672-b96de200-2fe3-11eb-910c-4cc61b64d021.png">
</details>

# Question

@Memo-Es @Betree @znarf it's my understanding we'll display these designs to both admins and non-admins, but with different text/CTAs for each? Or will we display these empty section designs for admins only, and remove the category section from the navbar/rendering if it's empty?

**Comment by Betree** [comment]
Duplicate of https://github.com/opencollective/opencollective/issues/3220

**Comment by Betree** [comment]
> it's my understanding we'll display these designs to both admins and non-admins, but with different text/CTAs for each?

@sbinlondon Depends:
- If conversations is enabled but there's no conversation yet, we must show it to everyone (because everyone could be tempted to create a conversation)
- If updates is enabled but there's no update yet, there's no point in showing that to non admins because only admins can create updates

**Comment by sbinlondon** [comment]
Duplicate of https://github.com/opencollective/opencollective/issues/3220
