### ISSUE TITLE
Whitelist opencollective.com subdomains

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3739]
I clicked a link to the docs from a Conversation on a Collective page and saw this:
![Screen Shot 2020-11-27 at 2 07 40 PM](https://user-images.githubusercontent.com/5498878/100400136-4d11e200-30ba-11eb-863b-5b3fccff0a44.png)

Can we please whitelist all opencollective.com subdomains, as we control them?

**Comment by Betree** [comment]
Definitely a bug, this one should have been allowed

**Comment by Betree** [comment]
Fix deployed, I've manually updated the comments affected by this issue to remove the redirects
