### ISSUE TITLE
Post replies to expense notifications as an expense comments

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3740]
## User story 
As an expense submitter with a problem/question, I want my replies to expense notifications to go to the person who can help fix the problem, so I can get a quick resolution and all info about the expense can be tracked in one place.

Currently, replies to expense notifications go to info@opencollective.com and hit the main helpdesk. The person who can actually help the user is the host admin. OC support has to then forward the inquiry to the right person and it's a waste of time and slows down the solution. Plus, we need to direct first-line support to the host admins, as that's really who should be managing their own user's needs.

## Best solution for this problem
When someone replies to an expense notification, it should post as a comment on that expense.

## MVP
Make the reply-to address for expense notifications the host admin, not the main OC helpdesk.

## Metrics 
Fewer support tickets that are really for the hosts.

**Comment by alanna** [comment]
@piamancini had this idea: Put a big reply button in the email that sends them to the expense thread.

**Comment by alanna** [comment]
From #3767 Support report:

> Questions related to expenses continue to be our biggest ticket item. This month, the majority of tickets raised relate to collective under the Social Change Nest host and those are mostly follow-ups on the status of an expense submitted.

So this is a pretty costly situation. @znarf we talked about a big `REPLY` button in the email that goes to the expense comments as a first step, and/or making the reply to address on the emails the host admin.

**Comment by alanna** [comment]
@Betree OK, can we put a big `reply` button that links to the expense comment thread, and change the `replyto` to a `noreply`? I think users are used to this behaviour from other apps and will figure it out.

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by segfult** [comment]
Hey @Betree, picking this up!

**Comment by bolariin** [comment]
@Betree @alanna by "expense notifications" are you referring to all expense related emails that is received by an expense submitter?

**Comment by alanna** [comment]
Yes anything related to an expense where they might hit reply to an email
notification.

**Comment by bolariin** [comment]
Thanks for clearing that up!

**Comment by Betree** [comment]
@alanna while testing the PR for this issue, I realized we don't send any email when an expense is rejected. Let me know if I should create an issue for that.

**Comment by alanna** [comment]
@Betree - yes please! There should definitely be an email when a expense is rejected.

**Comment by Betree** [comment]
Fixed by https://github.com/opencollective/opencollective-api/pull/5677
Opened an issue about rejected expense notification: https://github.com/opencollective/opencollective/issues/4081

:trophy: This issue has been completed by @bolariin  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
