### ISSUE TITLE
Unable to submit expense with my organization as payee

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3742]
I'm trying to submit an expense with the payee as [my organization](https://opencollective.com/protozoa) but it will not let me select a payout method or proceed. The next button is greyed out.

![Screen Shot 2020-11-30 at 12 00 47 PM](https://user-images.githubusercontent.com/5498878/100556060-58584e00-3304-11eb-87b6-f1f08e66df00.png)

I tried putting some text in the optional notes box since that's been a blocker before, but it still doesn't let me proceed. The payout method selection just doesn't appear. I tried this submitting to a few different budgets and it's the same on all. 

I can submit an expense with the payee as myself as an individual, or with a Collective as the payee, but it doesn't seem to be working for any organizations or hosts.

**Comment by kewitz** [comment]
**Technical bug description:**
When picking a collective from the search result, we're assuming that this expense is being submitted on behalf, that we're inviting the org to submit the expense.

**The fix:**
When picking a collective from the search result and the user is an admin of that collective, proceed with the normal expense flow.
