### ISSUE TITLE
Implement new collective page sections data structure

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3744]
As discussed in https://github.com/opencollective/opencollective/issues/3698, particularly this comment https://github.com/opencollective/opencollective/issues/3698#issuecomment-735729599, we need to:

1. implement the new data structure for the collective page section categories/sections/widgets

```es6
settings: {
  collectivePage: {
    sections: [
      { type: 'SECTION', section: 'GOALS' }, // a.k.a. a 'widget'
      { 
        type: 'SECTION_CATEGORY', 
        category: 'CONNECT',
        sections: [
          { section: CONVERSATIONS, isEnabledSettingKey: 'features.conversations.enabled' },
          { section: UPDATES, isEnabledSettingKey: 'features.updates.enabled' },
        ]
      }
  ]
}
```

2. and migrate the current settings for collectives to this structure. This includes considering that some collectives have differing information about what is enabled/disabled, i.e. Conversations in `settings.features.conversations` vs `settings.collectivePage.sections...`

**Comment by Betree** [comment]
I'm gonna start by introducing a `convertSectionsToNewFormat` helper in the frontend to make sure we can start working with them before everything is migrated.

**Comment by Betree** [comment]
Base implementation done in https://github.com/opencollective/opencollective-frontend/pull/5497. Added support for this new format for editing profile page in https://github.com/opencollective/opencollective-frontend/pull/5505 and implemented for the collective page + navbar in https://github.com/opencollective/opencollective-frontend/pull/5530
