### ISSUE TITLE
Ensuring consistency with color codes for profile pages set-ups

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3745]
Now that we are updating the Collective page, we need to ensure consistency in how we show color setups for profile pages, especially with two cases:

**1. New section headers (Icons)**

We modify some UI details depending on the main profile color: Buttons, tabs, tier cards, and links.
![Annotation on 2020-11-30 at 11-57-39](https://user-images.githubusercontent.com/49539954/100646222-5d68cd80-3303-11eb-93f2-c87badc5e71b.png)

With the new section headers, we add a new UI element that should follow the same color code as the profile page: A small dot of color to go with the icon on each section. 
<img width="450" alt="Screen Shot on 2020-11-30 at 12-04-50" src="https://user-images.githubusercontent.com/49539954/100646998-77ef7680-3304-11eb-990b-b968216a5c1a.png">

This dot's color is inherited from the main color with a 30% opacity.

**2. Buttons for sub-pages or flows inside the Collective's environment**

We have some sets of buttons on 'neutral black' color style that apply for all collectives:

| Inner flows  | 'Create new' buttons  |
|---|---|
| <img width="998" alt="Screen Shot on 2020-11-30 at 12-17-58" src="https://user-images.githubusercontent.com/49539954/100648284-598a7a80-3306-11eb-97e8-08604238e918.png">  | ![Annotation on 2020-11-30 at 12-24-54](https://user-images.githubusercontent.com/49539954/100648821-1ed51200-3307-11eb-92e5-d9270d5cbfc1.png) |

These should also be aligned to the main color of the profile page.

The reason why these buttons were in black neutral on the mockups is that I suggest that when you create a new Collective, the default main color should be neutral black until you change it (If you want)

<img width="1280" alt="Screen Shot on 2020-11-30 at 12-19-03" src="https://user-images.githubusercontent.com/49539954/100648283-58f1e400-3306-11eb-851a-65b67b2fa490.png">

---
 **Note:**
I think we should only allow hues that comply with our accessibility standards for the main color, for the sake of avoiding situations like this: 

<img width="1263" alt="92532046-8f7a0e80-f283-11ea-8886-fdfde08a803c" src="https://user-images.githubusercontent.com/49539954/100650774-09adb280-330a-11eb-8936-2b0e68d1d825.png">

@Betree @sbinlondon

**Comment by Betree** [comment]
This was solved as part of the collective page accessibility update
