### ISSUE TITLE
In expense payee selector, profile types should follow user menu conventions

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3747]
When you are selecting the payee profile for an expense, the dropdown list is divided into only two categories, `Myself` and `My Organizations`. Now that we can select other profile types as payees, I think this menu should follow the same pattern as the user menu, which has more categories like `Collectives` `Funds` `Events` etc. Having non-Organizations listed under `Organizations` is confusing and makes the correct payee profile harder to identify.

**Comment by snitin315** [comment]
Looks like this is resolved.


https://user-images.githubusercontent.com/46647141/145204270-0880bbf3-15f9-4e33-84e6-90dde9160528.mov

**Comment by Betree** [comment]
@snitin315 It is indeed! Resolved in https://github.com/opencollective/opencollective-frontend/pull/7180
