### ISSUE TITLE
[Project] Improve the way we record uploaded files

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3753]
Currently, uploaded images are stored as a simple string to the S3 bucket file. There are a few problems with that:
- We don't have an history, so we can't delete files that have been changed from our storage
- We don't know by who and when a file was uploaded 
- We don't have any metrics on files uploaded to the website
- We're not taking down illicit images when removing spammy profiles (ie. adult websites)
- We don't store the filenames
- We're lacking access-control on files (https://github.com/opencollective/opencollective/issues/1045). Since they're not linked to any accounts/users whatsoever, it has been historically difficult to implement this.

# Implementing

- [x] https://github.com/opencollective/opencollective/issues/6345
- [x] https://github.com/opencollective/opencollective/issues/6346
- [x] https://github.com/opencollective/opencollective/issues/6347
- [x] https://github.com/opencollective/opencollective/issues/6348
- [x] https://github.com/opencollective/opencollective/issues/6349
- [x] https://github.com/opencollective/opencollective/issues/6350
- [x] [Build a Metabase dashboard that will let us track the usage of uploaded files](https://opencollective-metabase.herokuapp.com/dashboard/170-uploaded-files)

# Researching & specs

- [ ] https://github.com/opencollective/opencollective/issues/6351
- [x] https://github.com/opencollective/opencollective/issues/6352

# Follow-ups

- [ ] For this first version, we don't want to have hard relationships between other models and the `UploadedFiles` table as the refactor would add a lot of complexity.

# Context 

Will unlock https://github.com/opencollective/opencollective/issues/2660

**Comment by vickywane** [comment]
@Betree can I please take this up?

**Comment by Betree** [comment]
@vickywane This issue has some complexity, so we prefer to keep for the team at the moment. We'll update the issue if that changes.

**Comment by kewitz** [comment]
@Betree I think we should go with something other than `Images` for the model.
It should be more abstract to support PDFs and CSVs.

**Comment by Betree** [comment]
Definitely. Looking back at it, the proposal here was too tied to https://github.com/opencollective/opencollective/issues/2660, I've updated the specs to accommodate for all file types.

**Comment by kewitz** [comment]
- [ ] Update the Expense form attachments to suggest the original file name when downloading files.

**Comment by Betree** [comment]
# Some initial research to prepare the kickoff call

## What kind of files do we store

- As direct references in models
   - [Expense items](https://github.com/opencollective/opencollective-api/blob/1a328112d30ba79086c886f15e6a0d518e5dadf2/server/models/ExpenseItem.ts#L24): Image, PDF. 86243 files currently in DB.
   - [Expense attached files](https://github.com/opencollective/opencollective-api/blob/1a328112d30ba79086c886f15e6a0d518e5dadf2/server/models/ExpenseAttachedFile.ts#L18): Image, PDF. 14100 files currently in DB.
   - [Account avatar](https://github.com/opencollective/opencollective-api/blob/1a328112d30ba79086c886f15e6a0d518e5dadf2/server/models/Collective.js#L334): Image. 14098 files currently in DB.
   - [Account background image](https://github.com/opencollective/opencollective-api/blob/1a328112d30ba79086c886f15e6a0d518e5dadf2/server/models/Collective.js#L356) (Hero): Image. 5341 files currently in DB.
   - [Legal documents](https://github.com/opencollective/opencollective-api/blob/1a328112d30ba79086c886f15e6a0d518e5dadf2/server/models/LegalDocument.js#L38): PDF. 2124 files currently in DB.
- As part of rich text content (PDFs are never allowed there, only images)
   - Accounts long descriptions: 2377 files currently in DB.
   - Tiers long descriptions: 137 files currently in DB.
   - Updates: 947 files currently in DB.
   - Comments & conversations: 1183 files currently in DB.
   - Custom "Thank you" email: 0 files currently in DB.

We, therefore, have a total of ~130.000 files currently recorded in the DB.

## What's the status on S3?

- Cost is ~$80/month (including tax form, staging, dev and production buckets)
- Production bucket currently has ~230.000 files, for a total of 140GB
- Given the stats above, we can estimate that there's a total of ~100.000 files that should be deleted from S3, so ~45%.

## What's this "Cloudinary" thing?

- A service that we're using to resize and generate thumbnails for PDFs and images
- Cost is $99/month
- There's an open issue about removing it: #4568

--

<details>
<summary>Queries</summary>

```sql
-- Count images from long descriptions
WITH images_counts AS (
  SELECT c.slug, array_length(string_to_array(c."longDescription", '<img'), 1) - 1 as nb_images
  FROM "Collectives" c
  WHERE "deletedAt" IS NOT NULL
  AND "longDescription" IS NOT NULL
  AND "longDescription" ILIKE '%<img%'
) SELECT SUM(nb_images) FROM images_counts

-- Count images in custom email messages
WITH images_counts AS (
  SELECT array_length(string_to_array((c.data -> 'customEmailMessage')::text, '<img'), 1) - 1 as nb_images
  FROM "Collectives" c
  WHERE "deletedAt" IS NOT NULL
  AND c.data -> 'customEmailMessage' IS NOT NULL
) SELECT SUM(nb_images) FROM images_counts
```

</details>


# Questions to answer during the call
- Discuss & update the specs for how to record uploaded files
- Define how to implement access control
- Define how removed files will be deleted from remote
- Define how legacy uploaded files will be removed (with a strategy to restore in case we missed some references)
- Define the metrics for building a Metabase dashboard that will let us track the usage of uploaded files

**Comment by vickywane** [comment]
@Betree When would the call happen and can non-internal contributors join-in?

**Comment by Betree** [comment]
@vickywane This project has been prioritized for implementation by the core team, we will tackle it internally. Thanks for offering your help though! Feel free to look at [this list](https://github.com/opencollective/opencollective/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22complexity+%E2%86%92+minimal%22%2C%22complexity+%E2%86%92+simple%22+-label%3Ateam%2Cdiscussion%2C%22blocked+%E2%86%92+waiting+third+party%22%2C%22blocked+%E2%86%92+waiting+parent%22%2C%22blocked+%E2%86%92+waiting+feedback%22%2C%22needs+design%22%2C%22needs+specs%22+) for interesting issues to contribute to.

**Comment by BenJam** [comment]
- [ ] kickoff conversation_today_ 
- [ ] define appetite (scope) today based on opportunities and eng.
- [ ] GOGOGO!

**Comment by Betree** [comment]
_This comment will be updated as we split the work in smaller issues_

# Kickoff notes

- We've updated the [specs](https://github.com/opencollective/opencollective/issues/3753#issue-755028757) for the model above
- We would like to better organize the files on S3 with subfolders. Suggested: `:imageType/:uuid.:extension`.
- We want to store the filename on S3. We'll either or (both):
  - Store as S3 metadata (see `Content-Disposition: attachment; filename="foo.bar"`)
  - Or use the filename in path (e.g. `:imageType/:uuid/:filename.:extension`)
- Access control: we're going to explore the solutions below to see if there's something simple to implement, otherwise we'll spec in an issue to be resolved in a future sprint. Ownership needs to be clear: if I lose access to the host admins, I shouldn't be able to access the file anymore
  - Have am url like opencollective.com/assets/:fileId. Would require cookies to work best.
  - Or handle the download through JS.
  - Or generate the pre-signed URL from the `url` resolver (only if we don't need a round trip with S3)
- Migrate existing entries
  - Have a script create an entry for everything (cheap)
  - Fetch info from S3? (maybe not if too expensive to implement)
  - Otherwise, make sure most fields are nullable
- Delete files from remote: for files uploaded with the new model
  - We need a strategy for each type where the conditions to delete are different (depends on the content + type). Example: Users shouldn't be allowed to delete paid expenses files.
  - Have a CRON that runs once a day, looks a deletedAt, removes from S3 then permanently deletes things after a grace period based on the type:
    - Avatar: delete immediately
    - Expense attachments: 1 month
- Delete files from remote: for legacy uploaded files
  - Compare `UploadedFiles` table with S3
  - Remove the diff by moving to a backup folder that we will delete one day (gives us the ability to restore if needed)
- Add limits (*we'll create the issue but not necessarily resolve it this sprint*)
The new model allows us to implement limits: e.g. x *Image Type* / user / day.
- Build a Metabase dashboard that will let us track the usage of uploaded files
  - Number of uploaded across time (filesize sum too?)
  - Pie chart of uploaded files / type
  - Average file size
  - Max file size

**Comment by BenJam** [comment]
- [ ] clean up MVP
- [ ] starting to work on GQL helper methods

**Comment by Betree** [comment]
**Week 4**
- [ ] Clean up GraphQL API PR and submit for review
- [ ] Implement script to record all existing uploaded files in the DB

**Comment by Betree** [comment]
**Week 5**
- [ ] Run the script to record all existing uploaded files in the DB for production
- [ ] Start looking into the script to delete files from S3 that are not in the DB

**Comment by Betree** [comment]
All items done, we'll merge the last one (https://github.com/opencollective/opencollective/issues/6350) once reviewed.

Follow-up issues are documented in https://github.com/opencollective/opencollective/projects/86, listing them here as I close this project for reference:
- https://github.com/opencollective/opencollective/issues/6478
- https://github.com/opencollective/opencollective/issues/6470
- https://github.com/opencollective/opencollective/issues/6351
- https://github.com/opencollective/opencollective/issues/6461
- https://github.com/opencollective/opencollective/issues/6352
- https://github.com/opencollective/opencollective/issues/2044
- https://github.com/opencollective/opencollective/issues/2660
- https://github.com/opencollective/opencollective/issues/5105
