### ISSUE TITLE
Contribution flow feedback and updates

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3759]
### Design update
---

After some feedback submitted in our slack channel and through some of the core team members we did some updates to the contri bution flow to improve the clarity of the information along the process.

| Reference images  | List of updates  |
|---|---|
| ![Annotation on 2020-12-03 at 00-00-30](https://user-images.githubusercontent.com/49539954/100970649-f3b31400-34fa-11eb-9d1c-49d60d850be3.png)  |  <ul><li>We are adding a line to include the payment processor fee tied to the contribution</li><li>We are adding an extra line after 'Today's charge' to show the net amount the Collective will receive with that contribution</li></ul>  |
| <img width="317" alt="Screen Shot on 2020-12-03 at 00-08-17" src="https://user-images.githubusercontent.com/49539954/100970991-b733e800-34fb-11eb-90a6-dacff7674a38.png">  | <ul><li>We added an info tooltip to add a small message regarding the payment processor fees. **Note**: Please feel free to change the copy of the tooltip</li></ul>  |
| ![Annotation on 2020-12-03 at 00-13-58](https://user-images.githubusercontent.com/49539954/100971423-7dafac80-34fc-11eb-9494-71544c47fd22.png)  | <ul><li>We added a different message box with recurring contribution that explains that we need the user info to create an account linked to that recurring contribution</li></ul>  |
| <img width="663" alt="Screen Shot on 2020-12-03 at 00-16-49" src="https://user-images.githubusercontent.com/49539954/100971618-e8f97e80-34fc-11eb-8f7d-02efbb1b27fc.png">  | <ul><li>We added an extra step after entering your info and clicking the 'Join and next'button, after you confirm your email you go back to the flow to the same step (2) but as a registered user. This will allow you to contribute in incognito mode and also to create an organization to contribute on its behalf</li></ul>  |

See the [design file](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC.com%5D-Production-Ready-%E2%9C%85?node-id=4558%3A10469) 🎨 in figma

@Betree

**Comment by vickywane** [comment]
@Betree is this open to members of the bug bounty program or it is to be worked on internally?

**Comment by Betree** [comment]
@vickywane This issue has some complexity, so we prefer to keep for the team at the moment. We'll update the issue if that changes.
