### ISSUE TITLE
Tax form not required for transfer to Collective in same host

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3760]
This expense is asking for a tax form: https://opencollective.com/opensource/expenses/29113

But the payee is a Collective within the same host. The tax form requirement is only relevant when money is paid to an external party to the host, so this is wrong.

**Comment by Betree** [comment]
The queries for tax form didn't integrate this constraint, I'll update them today to make sure they do.

**Comment by Betree** [comment]
Fix deployed
