### ISSUE TITLE
Replace react-datetime by a library that doesn't require moment.js

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3761]
**Why**
- We want to get rid of momentjs (see https://github.com/opencollective/opencollective/issues/2446)

**How**
- Find a good calendar library that support standard date and date +  time
- Replace the library, make sure it works everywhere it's used
- Remove `moment` and `react-datetime` from dependencies
- Remove this: https://github.com/opencollective/opencollective-frontend/blob/debt/moment-config/next.config.js#L12
- [Bonus] Add some styles on the picker to make it prettier

**Comment by jeffin143** [comment]
@Betree Could this be a bounty similar to moment migration? I can take a dig at this one

**Comment by RahulBansal123** [comment]
Working on it!

**Comment by SudharakaP** [comment]
@Betree : I was doing some investigation on this one today and found the following library; https://github.com/Hacker0x01/react-datepicker. Note that react-datepicker doesn't use moment.js in the new versions; https://github.com/Hacker0x01/react-datepicker#momentjs. So I think if you have no objections we can migrate to this? 🐼 🐨 🐘

**Comment by Betree** [comment]
@SudharakaP `react-datepicker` is a bit heavy: https://bundlephobia.com/result?p=react-datepicker@4.1.0, in part because it includes `date-fns`. That'd be great if we can find something smaller. Otherwise we can eventually go with something like that, but we should use [dynamic imports](https://nextjs.org/docs/advanced-features/dynamic-import) to keep it out of the main bundle since it's only used in a few places.

**Comment by SudharakaP** [comment]
@Betree : I couldn't find anything smaller and better yet. Let us park this for the moment; it seems that react-datetime might remove moment.js in v4; https://github.com/arqex/react-datetime/issues/723. So for now we'll leave it as it is, but I'll revisit this again later. 😄

**Comment by Betree** [comment]
Done in https://github.com/opencollective/opencollective-frontend/pull/7229. We mostly rely on standard `<input type="date" />` nowadays.
