### ISSUE TITLE
Collective Navigation v2: navbar v2 actions menu vs single CTA button

### ISSUE THREAD

**Issue by sbinlondon** [opencollective/opencollective#3764]
As discussed in demos today, we want to look at making the behaviour of the "Admin panel" + "Actions" section of the navbar act differently depending on who is viewing (admin vs non-admin) and how many CTAs are available.

I made a table based on my understanding of how this would work:

| Who is viewing  | How many CTAs are there | Expected look/behaviour |
|---|---|---|
| Admin | One | Admin panel + single CTA button |
| Admin | More than one | Admin panel + Actions drop-down menu (current design) |
| Non-admin | One | One CTA button |
| Non-admin | Two | Two CTA buttons |
| Non-admin | More than two | One CTA button + actions drop-down menu |

@Memo-Es if you could make some mock-ups of how this might look for each instance that would be great.

cc @piamancini @znarf @Betree @kewitz

**Comment by Memo-Es** [comment]
Thank you for putting it up! @sbinlondon 
I will update this issue with the mockups early next week

**Comment by Memo-Es** [comment]
Mockups to illustrate the Collective Navigation for admins and non-admins:

| Who is viewing  | How many CTAs are there | Expected look/behaviour | Mockup
|---|---|---|---|
| Admin | One | Admin panel + single CTA button | ![1](https://user-images.githubusercontent.com/49539954/101437466-e1a7eb80-38d5-11eb-9d90-f768323e8320.png)
| Admin | More than one | Admin panel + Actions drop-down menu (current design) | ![1 +](https://user-images.githubusercontent.com/49539954/101437493-f1bfcb00-38d5-11eb-86b6-74a989012989.png)
| Non-admin | One | One CTA button | ![1](https://user-images.githubusercontent.com/49539954/101437513-fc7a6000-38d5-11eb-8474-4fdcaa853b3a.png)
| Non-admin | Two | Two CTA buttons | ![2](https://user-images.githubusercontent.com/49539954/101437526-03a16e00-38d6-11eb-8753-60b91ee41dc4.png)
| Non-admin | More than two | One CTA button + actions drop-down menu | ![2 +](https://user-images.githubusercontent.com/49539954/101437547-0d2ad600-38d6-11eb-96a3-757b0d5324ca.png)

@sbinlondon

**Comment by piamancini** [comment]
looks good @sbinlondon @Memo-Es

**Comment by Betree** [comment]
https://github.com/opencollective/opencollective-frontend/pull/5632 implements most of this issue. The only thing still missing is that when there are only two calls to action we should display two buttons rather than a button + actions.

**Comment by sbinlondon** [comment]
> The only thing still missing is that when there are only two calls to action we should display two buttons rather than a button + actions.

@Betree Do we still need this part? Happy to do it.

**Comment by Betree** [comment]
We do but it's not a priority, we can delay for after the release
