### ISSUE TITLE
Address required for expenses with a Collective payee, but Collectives don't have addresses

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3765]
We're forcing expense submitters to put an address when submitting an invoice expense where the payee is a Collective. This doesn't make sense because Collectives are by definition not entities with their own address, but exist within the fiscal host.

<img width="792" alt="Screen Shot 2020-12-05 at 9 09 51 AM" src="https://user-images.githubusercontent.com/5498878/101210177-ed2ec300-36d9-11eb-8335-cbfa47cd6fcb.png">

To make it go through, Henry had to enter `N/A` in the field. For a Collective within the same host, no address is required because it's not a real invoice because the money isn't actually going anywhere.

But since we also have situations where the payee is in a different host, I think the simplest solution is to just automatically use the address of the payee host, which we should already know.

**Comment by vickywane** [comment]
@Betree can I work on this?

**Comment by Betree** [comment]
@vickywane Yes. Since most hosts already have (and are supposed to have) an address, let's go with the simple fix of pre-filling the field with the host address.

**Comment by vickywane** [comment]
@Betree a PR has been opened for this.

**Comment by NikitaKorevo** [comment]
@Betree Is a issue outdated?
No need to enter an address now:

![image](https://github.com/opencollective/opencollective/assets/48645737/a3f00f1d-4ed7-44f8-9ab4-ee4b20bcedc2)

**Comment by Betree** [comment]
Indeed, it looks like it was fixed in https://github.com/opencollective/opencollective-frontend/pull/7169; this issue was duplicated in https://github.com/opencollective/opencollective/issues/4969. Thanks, @NikitaKorevo!
