### ISSUE TITLE
New collective NavBar migration strategy

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3773]
The new navbar has some breaking changes in the way we store sections. To deploy the feature without hassle, we should:
1. Deploy a flexible code that displays the new navbar when using new sections format (`settings.collectivePage.useNewSections`) or the old navbar otherwise, without looking at the `NEW_COLLECTIVE_NAVBAR` feature flag. We may want to entirely remove `NEW_COLLECTIVE_NAVBAR` at this stage.
2. Wait for ~1day to make sure "everyone" is running this new code
2. Migrate all sections to new format from the API
3. Remove all code related to legacy sections format
5. Check spacing between sections in the collective page

**Comment by sbinlondon** [comment]
Sounds good to me 👍

**Comment by sbinlondon** [comment]
Let's chat tomorrow morning and see how close we are to this @Betree

**Comment by Betree** [comment]
1 & 2 are done. We will iterate on 3 + 4 once we're sure that no rollback is needed. We can already start 5.

**Comment by Betree** [comment]
3 is done. 4 & 5 are now tracked in https://github.com/opencollective/opencollective/projects/42
