### ISSUE TITLE
Allow Editing the Tier Long Description From the UI

### ISSUE THREAD

**Issue by zicklag** [opencollective/opencollective#3774]
## User story 
As a collective admin, I can edit my collective tiers' long description so that I have a more aesthetically pleasing display for my tier descriptions, avoiding the need to cut off the short description on the card view

## Best solution for this problem
Adding a WYSIWYG HTML editor for the long description field of tiers.

## MVP
The best solution to the problem is not too complicated to be the MVP

## Metrics 
How many users now use the long description feature after they can edit it from the UI

## Documentation 
The API apparently already has support for the long description, and, in fact, the Webpack collective is actually using it, but I assume that the only way they were able to accomplish this was by directly accessing the API.

**Comment by zicklag** [comment]
OK, I just found the button to edit the long description :facepalm: 

![image](https://user-images.githubusercontent.com/25393315/102028591-a6dc0280-3d70-11eb-9d6b-c6f48f041f2a.png)


And that is after I was literally spending time trying to get a development environment setup to fix this, before just deciding to use the API manually. :upside_down_face: 

So...this may or may not need to be implemented, but my confusion at how to actually edit the description might be cause for thinking about whether or not there is a way we could help people find that feature.

**Comment by Betree** [comment]
@zicklag to better understand how we may improve things here, where did expect to find the editor? What could have helped you to find this button?

**Comment by zicklag** [comment]
So I just realized why I didn't seen the button. I was previewing the changes I made to the tiers in a separate tab as an anonymous user, which, of course, doesn't have the edit button on it! That's why I didn't see it, so I would expect that to be more more rare than I initially thought that you would miss that button.

It was still a little confusing to me in the tier edit admin page. I really felt like there should have been a long description WYSIWYG here:

![image](https://user-images.githubusercontent.com/25393315/102099837-5a370c80-3dee-11eb-9ed6-c8e0f6409815.png)

My intuition would have led me to believe that everything that could be edited about the Tier would have been in that screen right there with the rest of the info.

**Comment by Betree** [comment]
> My intuition would have led me to believe that everything that could be edited about the Tier would have been in that screen right there with the rest of the info.

That makes sense. We need to improve the experience around this "standalone page", it feels unfinished and it has generated some issues like #3718 #3528. The redesign (#3438) should hopefully improve things.

I'm closing now as there is no immediate actionable, but I'll the feedback to @opencollective/design so they can take it into consideration.

Thank you for documenting your experience and sharing your experience @zicklag, this is very valuable for us.

**Comment by zicklag** [comment]
Sounds good, thanks for taking the feedback and for helping to provide Open Collective. I have just started getting into it and I am really blown away with how nice the service is. Keep it up! :+1:
