### ISSUE TITLE
HelloWorks: send tax form request email ourselves

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3779]
## User story 
We currently rely on HelloWorks to send tax form request emails for us. There are a few problems with that:
- It doesn't have Open Collective branding, and we can't customize it so it's sometimes unclear for users why they receive it. We're also unable to attach additional information or instruction.
- For organizations, since HelloWorks only allows for one recipient, we have to pick a single admin while they should all receive it

## Best solution for this problem
*To be confirmed by digging into HelloWork's API doc.*

Rather than asking HelloWorks to send the email, only generate the link and send it with a homemade template.

**Comment by alanna** [comment]
Another reason: if you operate multiple OC profiles it's impossible to tell which one the request is for.

**Comment by Betree** [comment]
Another good reason to prioritize this: people don't know anything about Hello works and have not signed up for it. A phishing attack with this vector would therefore be easier.

**Comment by alanna** [comment]
@Betree now that this is done should we raise separate issues for all the things we've wanted to improve about tax form emails? How do the emails look now?

**Comment by Betree** [comment]
@alanna The email looks like that:

![image](https://user-images.githubusercontent.com/1556356/150757958-e53d0af2-6ebf-4705-8eee-2083850d3c47.png)


Feel free to open new issues if you see things that can be improved in this email.

**Comment by alanna** [comment]
@Betree seems people still get both emails, from OC and HelloWorks. Is this intentional?
![Screen Shot 2022-02-11 at 2 11 33 PM](https://user-images.githubusercontent.com/5498878/153523136-500de7fa-8e1b-4a6c-84e4-c3255c701a8d.png)
![Screen Shot 2022-02-11 at 2 11 20 PM](https://user-images.githubusercontent.com/5498878/153523145-8f26c9dc-075f-4b85-96f7-1a3bb10e3280.png)

**Comment by Betree** [comment]
@alanna did you receive both emails at the same time? The normal flow right now is:
- You get an email from Open Collective and click the link to HelloWorks
- HelloWorks asks you to confirm your email, you click on something like "Send verification"
- Click on the other email and actually start the flow

We could be able to skip the two first steps by generating pre-authenticated links, but what they call "delegated authentication" is part of the "Standard Plan" / "Contact sales for details": https://www.hellosign.com/products/helloworks

**Comment by Betree** [comment]
> Yes as you can see in the screenshots they came at the same moment. 
I wasn't sure because seconds are not displayed in there.

> Should I create a new issue for this @Betree ?
Yes, you can categorize this as a bug. HelloWorks email should only be sent after clicking on the internal email
