### ISSUE TITLE
Users may not be able to tell that you can scroll the financial contribution options

### ISSUE THREAD

**Issue by Poopooracoocoo** [opencollective/opencollective#3783]
## User story 
_As a user, I cannot easily tell that you can scroll the financial contribution options because the arrows are not very prominent, and there's otherwise no other indication._

## Best solution for this problem
_What does the ideal solution look like?_
Showing a bit of the next card and always showing the scrollbar instead of only on hover

## MVP
_What will be built as an MVP? (Please refer to our [wiki](https://github.com/opencollective/opencollective/wiki/Feature-Spec-Template) for what's acceptable as an MVP.)_
dude i have no idea 😰

## Metrics 
_What metrics will be used to measure impact?_
idk??? And apparently https://github.com/opencollective/opencollective/wiki/Feature-Spec-Template is deprecated. You should update the links in the issue templates if that's the case.

## Documentation 
_The goal of the documentation should be to make it easier for others to do this_
this is about the frontend and there's probably a duplicate?

**Comment by Betree** [comment]
There should be another indication, we normally display a scrollbar below the cards:
![image](https://user-images.githubusercontent.com/1556356/102589842-e2c7ec80-410f-11eb-880d-0a114f752fc4.png)

As possible enhancements, I agree that making the buttons larger would be helpful.

Another pretty common pattern for this kind of horizontal lists is to display large buttons on the sides:

![image](https://user-images.githubusercontent.com/1556356/102590110-5833bd00-4110-11eb-9796-dc22f424b8ff.png)

![image](https://user-images.githubusercontent.com/1556356/102590172-74cff500-4110-11eb-8db3-96dbcf804173.png)

A related article that argues that horizontal scrolling should always have strong visual clues on desktop: https://www.nngroup.com/articles/horizontal-scrolling/

I'll let @opencollective/design make a proposal!

**Comment by Poopooracoocoo** [comment]
Here's a recording: 
![e3ujuPGTUy](https://user-images.githubusercontent.com/51363864/102607515-864ee680-417c-11eb-950a-3356792c49b4.gif)

**Comment by Memo-Es** [comment]
Thank you, @Poopooracoocoo, for reporting this issue!

We are adding a new behavior for horizontal scrolling:

![horizontal-scroll](https://user-images.githubusercontent.com/49539954/112049381-279b5f00-8b15-11eb-9080-1731be29b555.gif)

@Betree WDYT?

**Comment by Betree** [comment]
@Memo-Es This is looking great!

**Comment by Betree** [comment]
# Specs

- [ ] Update `HorizontalScroller` to accept `PropType.node` as `children`
- [ ] Render `children` in a `div`, set `this.ref` to this div
- [ ] Render the Prev/Next buttons directly from this component, as seen in https://github.com/opencollective/opencollective/issues/3783#issuecomment-804347821
- [ ] Remove all `ChevronsContainer` as we're not gonna use this pattern anymore
- [ ] Make sure everything works as designed in https://github.com/opencollective/opencollective/issues/3783#issuecomment-804347821

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$150** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $150 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by jass2007** [comment]
@Betree  [scrolling cycling ]()

**Comment by Betree** [comment]
:trophy: This issue has been completed by @snitin315  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Comment by Betree** [comment]
There's an important regression that we did not spot in the review: cards are now left-aligned instead of being centered. I'mrolling back https://github.com/opencollective/opencollective-frontend/pull/6199.

![image](https://user-images.githubusercontent.com/1556356/115853403-6fb9e400-a429-11eb-8060-d02a2a32d970.png)
