### ISSUE TITLE
Download and delete expense buttons not visible on mobile

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3785]
I can't find the action buttons that are down the left side of an expense on desktop when I look on my phone, e.g. download and delete.

**Comment by znarf** [comment]
@Memo-Es Where are the buttons supposed to be on mobile?

**Comment by Memo-Es** [comment]
We have a design for this case. I guess it was not surfaced during the expense polish phase.

![Sheet](https://user-images.githubusercontent.com/49539954/104983711-eda5c380-59d2-11eb-9b7b-0d9d303cbaae.png)

See the [design file](https://www.figma.com/file/9Iq3vBOmZ2EuOacXEYD5yK/DS-03-Global-Components?node-id=5337%3A489) 🎨 for implementation

cc @Betree
