### ISSUE TITLE
Add a button for root to merge accounts

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3787]
## User story 
As a root admin, I often need to merge some profiles. This is currently done by editing the DB entries manually, which is tedious and error prone.

## Best solution for this problem
The `scripts/merge-collectives.js` script was recently introduced as an MVP. With the upcoming navbar, we can re-use this code to implement a proper feature:
- [ ] ~In the `Actions` navbar menu~, add a `Merge account` entry for roots => see https://github.com/opencollective/opencollective/issues/3787#issuecomment-806531913
- [ ] When clicked, open a new modal with the main profile displayed
- [ ] Show a collective picker below to select a profile that will be merged into the first one 
- [ ] Fetch & display the same info that's currently displayed in the script ("following items will (not) be moved")
- [ ] Add a strong confirmation, for example by making user type the name of the account that will be deleted or by showing multiple warnings

**Comment by DhairyaBahl** [comment]
@Betree I would like to work on this issue. Kindly assign it to me !!

Thanks :)

**Comment by Betree** [comment]
@DhairyaBahl Sure! Let me know if you need anything.

**Comment by Betree** [comment]
New navbar is now the default, so we can add the button to `components/collective-navbar/ActionsMenu.js`.

Note: local dev envs may still require setting `NEW_COLLECTIVE_NAVBAR=true` in `.env`

**Comment by DhairyaBahl** [comment]
@Betree  Got it !! Thank you for telling me :smile:

**Comment by DhairyaBahl** [comment]
@Betree I cloned the front-end repository and used command npm install in that repository but it showed many errors that this file is missing or that file is missing !! What should I do ??

**Comment by Betree** [comment]
@DhairyaBahl which files? Are you using the latest version on `master`?

**Comment by DhairyaBahl** [comment]
@Betree Many files are missing !! log is very big !!

**Comment by Betree** [comment]
@DhairyaBahl I can't help much without the logs and more info about your setup. Let's not expand to much the discussion on this issue, you can get more assistance by posting in https://github.com/opencollective/opencollective/discussions/categories/development-q-a or on [Slack](https://slack.opencollective.com) (channel #engineering).

**Comment by DhairyaBahl** [comment]
@Betree got it I am trying to figure it out by myself if I still feel stuck, then I will definitely go to the slack channel for help.

Thanks :)

**Comment by alanna** [comment]
+1 we need this!

**Comment by DhairyaBahl** [comment]
@alanna sorry for delay,  I am working on it.

**Comment by Betree** [comment]
@DhairyaBahl are you still working on this?

**Comment by DhairyaBahl** [comment]
@Betree Sorry, I was not working on this. I can start working on this or I can unassign myself. What should I do ? 

Sorry for inconvenience.

**Comment by Betree** [comment]
@DhairyaBahl If you're willing to work on this feel free to do so, but if you don't have the bandwidth to do it now it's better to unassign yourself so that someone else can work on this issue. You can always pick another one later when you'll have more time :slightly_smiling_face:

**Comment by Betree** [comment]
Note on the specs: @znarf is [currently implementing](https://github.com/opencollective/opencollective-frontend/pull/6101) a "Root actions" page for collectives to group all the root admin actions (eg. ban account). We probably want to implement the "Merge accounts" button on that page.

**Comment by DhairyaBahl** [comment]
@Betree I am sorry but unfortunately I won't be able to give time to this issue for next few days. So its better that I unassign myself from this. Sorry again to keep you guys hanging. I will start with some good-first-issues later . Hope you guys don't mind.

Sorry For Inconvenience
Thanks and regards

**Comment by Betree** [comment]
Implemented in https://github.com/opencollective/opencollective-frontend/pull/6768
