### ISSUE TITLE
Add contributor to reconomycop

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#379]
Please add Wouter Extercatte as Core Contributor to https://opencollective.com/reconomycop

**Comment by piamancini** [comment]
@nicobarretoOC Need the person's email address to do this.

**Comment by nicobarretoOC** [comment]
ah, sorry for that! let me request it.

**Comment by nicobarretoOC** [comment]
His email is wouterxt@gmail.com

**Comment by piamancini** [comment]
done
