### ISSUE TITLE
Unable to locate invited expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3795]
I invited someone to submit an expense. Now I want to check on it to make sure the details were right and to make sure it exists, but I can't see it on the expenses list and I don't see an email notification with a link to it or anything.

**Comment by znarf** [comment]
I agree it needs to be visible for the person who created it at least. How complex is this @kewitz ?

**Comment by kewitz** [comment]
@alanna @znarf I updated it to display the unverified expenses by default and to display drafts (invited expenses) that were created by the user.

The detail here is that we still don't support editing the drafted expense, this would get in the way of the submit on behalf flow and it will require further speccing if necessary.
