### ISSUE TITLE
Invited expense wrongly showing $0 as the total

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3796]
<img width="801" alt="Screen Shot 2020-12-26 at 5 15 39 PM" src="https://user-images.githubusercontent.com/5498878/103145389-9ed38800-479e-11eb-9ffa-ab2e0a71a862.png">

I created this expense and put in the amount, which showed correctly before submitting the form. But after submitting, it shows as $0, which is confusing.

**Comment by znarf** [comment]
Can this be reproduced?
