### ISSUE TITLE
Expense inviter can input payout details

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3798]
## User story 
As an expense inviter, I want to have an easy process in the case where I have received an invoice from a vendor and need to get them to submit an expense (which was a main use case for the invite expense feature in the first place). A big part of this is inputting the payout details from the invoice in the system for them. Currently you can only fill out their name and email, plus the expense description and amount, but not the payout info. 

## Best solution for this problem
Allow the inviter to fill out the payout details, then get the actual payee to confirm these (and edit if needed) along with the rest of the expense when they submit it.

**Comment by znarf** [comment]
@alanna What is the payout info exactly? Which fields are we talking about?

**Comment by alanna** [comment]
These fields

![Screen Shot 2021-01-14 at 9 17 56 AM](https://user-images.githubusercontent.com/5498878/104505849-6ad6de80-5649-11eb-89de-0cc542b49689.png)

**Comment by znarf** [comment]
It seems to me it's a bit tricky. If we start exposing this screen to everyone, how can they understand it's optional and how can they skip it? 

Also, how to figure what is mandatory and what is not? I guess you just want to input the information you have and don't necessarily have all the bank details?

@Memo-Es @kewitz What do you think?

**Comment by kewitz** [comment]
This was briefly discussed in the past and it is related to filling for invoices we receive outside the platform.
I think we can implement this, but we have to keep in mind that the contractor will still need to log in to the platform to actually submit the expense. If we're looking for a solution for tracking invoices that do not belong to the platform, this won't do it.

**Comment by alanna** [comment]
Yes the invitee should definitely still need to log in and confirm everything, and submit the expense. I think the invite expense form should only require an email address at minimum, but allow you to input any other data you have, including payout details. This will serve the full range of use cases, from someone just kicking off an expense process in a minimal way to get the user to click through and set up on the platform, to situations where the admin already received the payable invoice and is trying to save the vendor as much time as possible by doing the data entry for them (but they still need to confirm and submit).

**Comment by kewitz** [comment]
@Memo-Es I think this is simple as not skipping to the expense step when filling in the invitee name and email.
Although this may be a reason to ditch the dropdown invitee form and use the main form to input those details.

**Comment by Memo-Es** [comment]
On it, @kewitz will share a proposal here this week

**Comment by kewitz** [comment]
Designs:
https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC.com%5D-Production-Ready-%E2%9C%85?node-id=10011%3A0

**Comment by alanna** [comment]
@shannondwray this will need updating in docs
