### ISSUE TITLE
support rupees

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#38]
We need to support rupees as a currency for WWCodeDelhi. Changed it in DB currency is INR.
Also, CSS needs to be changed to reflect new currency: https://en.wikipedia.org/wiki/Indian_rupee_sign#/media/File:Indian_Rupee_symbol.svg

**Comment by piamancini** [comment]
We need to move forward with this. Joey from WWCode tried to do a paypal reimbursement and it failed. This not good, Joey is seeing this as approved on the backend but nothing in her paypal dashboard. She will do it manually from her paypal. 
![screenshot_delhi](https://cloud.githubusercontent.com/assets/3671070/14862879/287766ac-0c68-11e6-87b1-18d2eab74ac7.png)

**Comment by xdamman** [comment]
That was actually the same bug than https://github.com/OpenCollective/OpenCollective/issues/52

I've fixed it manually in the DB so she can now approve and pay the expense id 362: 
https://app.opencollective.com/groups/47/transactions/362

That said, we still need to add support for showing rupees properly on the frontend and backend (for the confirmation emails)

**Comment by piamancini** [comment]
great. they did it manually already from their paypal.


P.
piamancini.com
t: @piamancini
s: piamancini
OpenCollective <https://opencollective.com>

**Comment by xdamman** [comment]
Then we need to update it in the DB and set the payoutMethod to manual and status to REIMBURSED

**Comment by piamancini** [comment]
done

P.
piamancini.com
t: @piamancini
s: piamancini
OpenCollective <https://opencollective.com>

**Comment by piamancini** [comment]
I'll close this since it hasn't been an issue for a while.
