### ISSUE TITLE
OpenCollective receipts sent from host...

### ISSUE THREAD

**Issue by dahacouk** [opencollective/opencollective#380]
@xdamman @piamancini Currently the OpenCollective receipts are sent from "info@opencollective.com" but is there a way that this could be sent from a project email address or the host email address? I guess I'm interested to see if other hosts would like this too. Cheers Daniel

**Comment by xdamman** [comment]
Good idea. We could send it from `info@:collective.opencollective.com` so that responses go directly to all core contributors of the collective (they can individually decide to unsubscribe from that email address at any time)

**Comment by xdamman** [comment]
deployed!

**Comment by dahacouk** [comment]
@xdamman Could we have it from `pay @ collective.opencollective.com` instead? Not a big deal though! 😃

**Comment by xdamman** [comment]
Why "pay"? Info, contact, team would make more sense no?
