### ISSUE TITLE
Search: don't show filters if nothing is searched yet 

### ISSUE THREAD

**Issue by snitin315** [opencollective/opencollective#3800]
**Describe the bug**

The presence of search results filters even before searching for anything.

**To Reproduce**

Go to https://opencollective.com/search

**Expected behavior**

Filters should appear only after searching for something.

**Screenshots**

![Screenshot at 2021-01-03 11-18-01](https://user-images.githubusercontent.com/46647141/103472626-6a228a80-4db5-11eb-9e3c-a3bce33252fb.png)

**Desktop (please complete the following information):**
 Any

**Smartphone (please complete the following information):**
Any

**Additional context**
Open to syggestions

**Comment by Betree** [comment]
We should also make sure that the selected filter is preserved when changing the searched terms. If you click on "Events" then type something in the search, it should search only for events. Especially cause the filter is still displayed as selected.
