### ISSUE TITLE
State collective title in Stripe receipt...

### ISSUE THREAD

**Issue by dahacouk** [opencollective/opencollective#381]
@xdamman @piamancini In the Stripe receipt the description wording looks like "OpenCollective: kendraio-daw" which seems like the URL part but I'd prefer if it was the title of the collective, as in "OpenCollective: Kendraio DAW". Could we do that? I guess it just means passing a different variable to Stripe. I guess I'm interested to see if other hosts would like this too. Cheers Daniel

**Comment by xdamman** [comment]
Stripe receipt? Where do you see that? Can you share a screenshot?
You are not supposed to receive the default Stripe receipt but a custom receipt that we send from our backend. We also generate a PDF invoice automatically, e.g. http://opencollective.com/co-labs/transactions/399c3b84-5600-4721-950d-7f33fcd367be/invoice.pdf

Unless you meant as a host?

**Comment by dahacouk** [comment]
Yes, seeing as I run the host, Kendraio, I can set Stripe to send out receipts too. Of course not sure if I need to now but just playing with different configurations. But, at least, it would be nice to send the best variables. 😃 
![window_and_opencollective_ _fastmail__dahacouk___9_messages_](https://user-images.githubusercontent.com/201752/29488644-fdfa7b1c-8506-11e7-9647-adcaf29e16fa.png)

**Comment by dahacouk** [comment]
And while we are talking about the receipt – looking a lot better by the way 😃 – can we fix the dates to be English and also suggest verbose (month as text rather than number) to avoid DD/MM/YYYY and MM/DD/YYYY confusion?

![window_and_https___opencollective_com_co-labs_transactions_399c3b84-5600-4721-950d-7f33fcd367be_invoice_pdf](https://user-images.githubusercontent.com/201752/29488664-95662258-8507-11e7-94c9-b4326c9f84d3.png)

**Comment by xdamman** [comment]
Ah yes, it's annoying that the US can't follow international common sense ¯\_(ツ)_/¯ 
We should fix that at some point.

For the description in Stripe, maybe best is to show the url of the collective?
e.g. https://opencollective.com/:slug
That way people can quickly look up what it is about if needed to be.

**Comment by piamancini** [comment]
@dahacouk Can we close this? We won't fix the dates just now. Is the other issue solved?

**Comment by piamancini** [comment]
lack of activity
