### ISSUE TITLE
Migrate OSC to zero platform fees for Collectives

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3811]
While we're keeping the actual money paid from OSC for platform fees the same, I think we should really migrate it to the new model where end-users and Collectives do not have platform fees, and platform fees are between the host and OC inc.

Right now transactions still look like this:
<img width="765" alt="Screen Shot 2021-01-07 at 12 16 38 PM" src="https://user-images.githubusercontent.com/5498878/103832106-68710380-50e2-11eb-9d2f-1cdd5a469c05.png">

I think it should say 10% platform fee and no host fee, just like with OCF, then OC inc should charge OSC its agreed 50% platform fee the same way all hosts are charged in the new model, through an expense on the host budget.

The simplicity of the new pricing model is having so many benefits and I'd really like it to be consistent across the whole platform, with the only difference being whether the platform fee is 15% or 50%.

**Comment by znarf** [comment]
I'm up for it, this just requires a communication to the Collectives explaining the rationale behind the change. And explaining that this doesn't change anything for them.

I know that @piamancini wanted to explore a way to also turn Platform Tips on for OSC so we have a consistent experience everywhere. But, it's not an easy one and we better separate the 2 things.

**Comment by alanna** [comment]
I don't think Collectives will notice or care at all, since the fee amount will stay the same, just combined into one. We've already announced the new pricing model in our newsletter and blog.

I agree platform tips for OSC is a separate discussion.

**Comment by znarf** [comment]
I still think we need to push this information clearly, pricing is sensitive and if "Host Fee" moves suddenly from 5% to 10% in the transactions list, we better have sent an email. A short blog post with the same content would be great to.

If I read the latest newsletter/[blog post](https://blog.opencollective.com/what-a-year/), the change is not clear at all for OSC collectives, they could even think that the Platform Fee is gonna go away and the Host Fee will stay the same.

**Comment by alanna** [comment]
We've been clear in OSC communications that their pricing is not changing. We're due to send another OSC newsletter out soon, so we can reiterate it. I'm not concerned about it because the actual total fees is not changing, just how they are accounted for.

**Comment by znarf** [comment]
I propose to move forward with the change around February 28th so we can trigger Recurring Contributions in March with the new scheme.

**Comment by alanna** [comment]
I am 100% in favor of moving to 10% host fee and not showing platform fees to OSC end users.

However, the question of whether we can turn on platform tips is another matter. @piamancini should we just decouple these and go ahead with the host/platform fee change, and leave platform tips off, or turn platform tips on for OSC and just see what happens?

**Comment by znarf** [comment]
### Some idea.

As part of our pricing update, we will be changing the fee structure of Collectives hosted by the Open Source Collective. This should absolutely not impact your finances.

This is what we're changing:
- Before: 5% Platform Fee / 5% Host Fee
- After: 0% Platform Fee / 10% Host Fee

**Why are we doing this ?**

We're doing this to reflect better how we see the Open Collective platform. We're primarily a service for Fiscal Hosts which themselves host Collectives on our platform.

- As a Collective, you're customer of the Fiscal Hosts, this is what you're paying for
- As a Platform, our customers are the Fiscal Hosts, they pay us for the service

**When is this happening?**

We will update the fee structure between March 31st and April 1st at midnight UTC. Shortly after, we'll start charging the monthly subscriptions for April with the updated scheme.

**How is the Open Collective platform making money?**

From now on, the Open Source Collective will share part of their Host Fees with the Open Collective platform. The amounts should overall stay the same.

With some other hosts, we're using Platform Tips and we're currently evaluating how this could work for the Open Source Collective.

### Plan

- [ ] Update Host to platformFeePercent=0, hostFeePercent=10
- [ ] Update Host to plan.hostFeeSharePercent=50
- [ ] Update Host to plan.platformTips=false
- [ ] Update all hosted Collectives to platformFeePercent=0
- [ ] Update all hosted Collectives to hostFeePercent=10

**Comment by alanna** [comment]
This was already announced in the last newsletter

![Screen Shot 2021-03-11 at 11 16 28 AM](https://user-images.githubusercontent.com/5498878/110705460-49fec400-825b-11eb-8afd-4151d0170d3e.png)

But I agree we should communicate more. I propose we post an Update on OSC host page based on the content above right at the time we're about to make the switch. @znarf is the date 100% confirmed? If so I will prepare this. If the communication is the only thing we're waiting on, we can move it forward. I can write and post this with 24 hours notice (as long as it's not Saturday here!)

**Comment by znarf** [comment]
@alanna Thank you. I somehow missed the announcement in the February newsletter.

From my side, we will stick to this schedule, It was delayed for too long now.

**Comment by znarf** [comment]
We need to update the following just before April 1st 12AM UTC:

```
UPDATE "Collectives" SET "platformFeePercent" = 0, "hostFeePercent" = 10 WHERE id = 11004;
UPDATE "Collectives" SET "data" = jsonb_set("data"::jsonb, '{plan, hostFeeSharePercent}', to_jsonb(50))  WHERE id = 11004;
UPDATE "Collectives" SET "data" = jsonb_set("data"::jsonb, '{plan, platformTips}', 'false'::jsonb)  WHERE id = 11004;
UPDATE "Collectives" SET "platformFeePercent" = 0, "hostFeePercent" = 10 WHERE "HostCollectiveId" = 11004;
```

**Comment by alanna** [comment]
I'm planning to put out an Update informing everyone of this change once it's happened. Does this sound right?

> **OSC's fees aren't changing, but how we show them is**

> Projects with Open Source Collective have always paid a 10% fee. This amount is not changing—it will still be 10%—we're just changing how we account for and display fees. We're informing everyone to prevent confusion if you notice transaction details look a bit different.

> Previously, on each transaction, you would see fees split 5% for Open Collective, who makes the software platform, and 5% for Open Source Collective, the nonprofit Fiscal Host that holds money for Collectives and takes care of taxes, liability, etc.

> Starting today, you will just see a 10% Host Fee. This change is aligned with Open Collective's recent [pricing model update](https://opencollective.com/pricing) for all users of the platform, and is intended to simplify fees. Now Collectives have just one entity they pay fees to, their Fiscal Host, while Hosts pay for use of the Open Collective platform behind the scenes.

Old:

<img width="610" alt="Screen Shot 2021-03-30 at 9 58 01 PM" src="https://user-images.githubusercontent.com/5498878/112962646-17355500-91a3-11eb-9fa3-dc04910ba135.png">


New:
[will get screenshot once change it in effect]

> As always, [OSC's budget is transparent](https://opencollective.com/opensource#category-BUDGET)—you're welcome to check it out if you're wondering how fee revenue gets spent. As a nonprofit, all revenue is reinvested in our mission of supporting health and sustainability of the Open Source Ecosystem.

> Thank you for being with Open Source Collective, and let us know if you have any comments or questions! You can comment on this update or contact hello@oscollective.org.

**Comment by alanna** [comment]
Change confirmed and update sent

https://opencollective.com/opensource/updates/fees-arent-changing-but-how-we-show-them-is
