### ISSUE TITLE
Design for a different pattern for expense tags when big buttons are not necessary

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3813]
As part of the expense list improvements covered in #3583 and https://github.com/opencollective/opencollective-frontend/pull/5421#issuecomment-756301332, we designed a different pattern for the expense tags 'Rejected' and 'Paid,' because, as reported in slack, since these statuses usually require no further action by the user, they could be distracting while interacting with the expense list.

![Screen Capture on 2021-01-07 at 19-56-41](https://user-images.githubusercontent.com/49539954/103965652-d25dcd00-5123-11eb-8b22-5bd0d859cffd.gif)

So we have a dropdown now for 'Rejected' and 'Paid' expenses if the user wants to change the expense, whereas for pending, approved, and ready to pay stays with the current button set.

Check the design file 🎨 in [Figma](https://www.figma.com/file/2gSaMuWjJIhzyFVC2OijNP/OC.com-06-Budget?node-id=2171%3A11600) 

@Betree

**Comment by alanna** [comment]
Can we please call these `labels` or something else since `tags` is another thing?

**Comment by Betree** [comment]
:trophy: This issue has been completed by @snitin315  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
