### ISSUE TITLE
open collective link not showing banner

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#382]
www.opencollective.com is not showing up a banner when shared on social media.

**Comment by nicobarretoOC** [comment]
Here is a screenshot of what I mean:
![captura de pantalla 2017-09-28 a las 1 31 33 pm](https://user-images.githubusercontent.com/30665166/30983925-7a3742d2-a451-11e7-8d77-f85b6aff5e4b.png)

**Comment by piamancini** [comment]
closing this for the moment. We'll reopen if we want to look into it.
