### ISSUE TITLE
Unable to archive or unhost Collective due to "Validation is on twitterHandle failed"

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3824]
I'm trying to archive [this Collective](https://opencollective.com/openupstate) so I can close down the host finally, but it throws this weird error. The same thing happens when I try to remove the host.

<img width="867" alt="Screen Shot 2021-01-12 at 4 20 39 PM" src="https://user-images.githubusercontent.com/5498878/104265628-e70ade00-54f2-11eb-9200-4306cb597e33.png">

<img width="1232" alt="Screen Shot 2021-01-12 at 4 26 12 PM" src="https://user-images.githubusercontent.com/5498878/104265635-ea05ce80-54f2-11eb-9b6d-ae001195f110.png">

**Comment by Betree** [comment]
Updated this specific profile and all others to clean or remove the invalid twitter handles. Archiving should now work properly.
