### ISSUE TITLE
Navbar > Actions: Menu not closing on outside click

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3826]
**Describe the bug**
On some browsers/OS, the menu is not closing itself when users click outside of it.

**To Reproduce**
1. Go to https://opencollective.com/babel/
2. Click on "Actions"

**Expected behavior**
The menu should close itself when users click outside of it.

**Additional context**
So far the bug only seems to affect Firefox and Safari on Mac.
Testing of the following browsers on Linux did not trigger the issue: Firefox, Chrome, Brave, Opera, Edge

The most likely root cause I can imagine right now is a difference in how browsers implement the `contains`/`activeElement` behavior in https://github.com/opencollective/opencollective-frontend/blob/master/components/StyledDropdown.js#L66

Likely related: https://bugzilla.mozilla.org/show_bug.cgi?id=1547926

**Comment by DhairyaBahl** [comment]
@Betree I would like to work on this issue. Thanks :smile:

**Comment by Betree** [comment]
@DhairyaBahl Let's focus on one issue at a time :wink: Especially cause I think @sbinlondon already started looking at this

**Comment by DhairyaBahl** [comment]
@Betree got it !! I didn't know that someone is already assigned to the issue.

**Comment by Betree** [comment]
It would also be great if the menu could close when pressing `Esc`

**Comment by sbinlondon** [comment]
Tested Edge and Chrome to double check and you're right, the menu works as expected there.

Upsettingly, on Safari, not only does the actions menu not close when you click outside, but it's also doing this 🙄 

![Screenshot 2021-02-02 at 13 24 52](https://user-images.githubusercontent.com/37520401/106606510-1fce2e00-655a-11eb-9a08-147d59b451d4.png)

I'll look into solving that too.

**Comment by Betree** [comment]
@sbinlondon we may want to consider going back to a JS implementation (with `react-popper`). A pure CSS approach sounded better for responsiveness and accessibility, but cross-browser compatibility has been challenging with this one. 

Let's try to see if there's an easy fix, if not we'll discuss the alternatives.
