### ISSUE TITLE
Language selection menu shold be updated

### ISSUE THREAD

**Issue by IhorHordiichuk** [opencollective/opencollective#3828]
Add Ukrainian (українська) language to the drop-down language menu located in the footer. Current translation progress = 48% that should be enough.

It is also worth to update the values of translation progress in other languages, as the current values are outdated in this menu.

**Comment by znarf** [comment]
Thank you for opening the issue @IhorHordiichuk, this can be done by updating the following file:
https://github.com/opencollective/opencollective-frontend/blob/master/lib/constants/locales.js

**Comment by IhorHordiichuk** [comment]
Hardcoded list? I can check translation completion on Crowdin and update it. And where can the exact same flags be found?

**Comment by znarf** [comment]
> Hardcoded list? 

Yes

> And where can the exact same flags be found? 

Emojis

> And what to do with languages, that have translation progress below 20%?

We ignore them but we keep the one that are already in the list.

Someone created a PR for Ukrainian:
https://github.com/opencollective/opencollective-frontend/pull/5733
