### ISSUE TITLE
After deactivating host, deactivate host button still active

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3829]
I deactivated opencollective-host, and afterward this is what the screen looks like:

![Screen Shot 2021-01-13 at 10 53 47 AM](https://user-images.githubusercontent.com/5498878/104379050-c6439680-558d-11eb-9881-80dbaeddc259.png)

The button should now say `activate host` since it is already deactivated.

Is `activate host budget` the same as `activate host`? If so, we can just have one button there with two states `activate` and `deactivate`.

**Comment by znarf** [comment]
Some Events were still hosted by Open Collective Host and that was confusing the system. We should not have let Collective archive themselves without Events already archived. Or we should have Archived automatically all Events when archiving Collectives.
