### ISSUE TITLE
Unable to archive host

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3830]
opencollective-host has been deactivated, but it won't let me archive it.

![Screen Shot 2021-01-13 at 10 56 53 AM](https://user-images.githubusercontent.com/5498878/104379253-17ec2100-558e-11eb-93c1-2235c656efb1.png)

**Comment by znarf** [comment]
The profile was still considered as Host after pressing the button, because it was still hosting some Events.

**Comment by alanna** [comment]
I still can't archive it

<img width="937" alt="Screen Shot 2021-01-14 at 11 55 38 AM" src="https://user-images.githubusercontent.com/5498878/104520128-7a612200-565f-11eb-86f6-4cd2798428bb.png">

**Comment by znarf** [comment]
It seems the Open Collective Host has a balance and that is the blocker.

<img width="446" alt="Screenshot 2021-01-18 at 11 42 16" src="https://user-images.githubusercontent.com/806/104905303-734d5300-5982-11eb-88c6-d02369232bee.png">

_Note that I had to temporarily activate as Fiscal Host again to see the Budget section and take the screenshot._

**Comment by alanna** [comment]
OK, how do I clear the balance? Normally I would use `zero balance` but that won't work for a host. I tried to submit an expense, but it won't let me set a payout method.

![Screen Shot 2021-01-19 at 10 26 28 AM](https://user-images.githubusercontent.com/5498878/104964203-d56c8d80-5a40-11eb-9110-7e6390488164.png)

**Comment by znarf** [comment]
I re-activated Fiscal Hosting, I'm now able to see the options.

<img width="756" alt="Screenshot 2021-01-18 at 22 37 55" src="https://user-images.githubusercontent.com/806/104964981-ec2dc880-59dd-11eb-916a-f6d3d2e545d8.png">

**Comment by alanna** [comment]
Yay it worked!
