### ISSUE TITLE
Standalone pages for displaying projects, events and connected collectives

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3835]
We want to be able to link to standalone page for projects, events and connected collectives from the NavBar.

For the design, we can re-use the layout from [the tiers page](https://opencollective.com/babel/contribute/) and make sure we re-use the contribute cards in there. Filtering can be done in the frontend given that there are not a lot of entries.

We want to have three distinct routes:
- `/slug/events`
- `/slug/projects`
- `/slug/connected-collectives`

**Comment by alanna** [comment]
I really want this feature.... @Betree could it be a bounty?

**Comment by Betree** [comment]
Since this issue is mostly about refactoring properly the existing page, writing specs for a bounty could end up taking more time than doing it directly. I'll look at it

**Comment by alanna** [comment]
Woo! That was super fast. Thanks Ben!
