### ISSUE TITLE
Uploaded invoice on invited expense doesn't show up for invitee

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3839]
I invited an invoice expense to be submitted by a new organization (which I was also the admin of) and I put in the details and uploaded an attached invoice. I then received the notification as the admin of the invited org and clicked through to confirm and submit. But the uploaded invoice attachment was not there and I had to re-upload it again as the new org admin. If the expense inviter uploads any files, they should be there when the invitee goes through the expense submission process.

**Comment by znarf** [comment]
Could you have a look @kewitz and assess the complexity?
