### ISSUE TITLE
Invitee unable to create organization as invited expense payee

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3840]
I went through the invite expense process for [this expense](https://opencollective.com/giftcollective/expenses/31776) and put the contact person of the payee org as the invitee. They got the email and clicked through, but they could only select from their existing profiles for the payee, not create a new org, which is what was required for this expense.

I tested clicking through as a logged out user, and in that flow we allow the invitee to select `organization` and put in the details to create that new org profile. But a logged in user can't do the same thing. 

When inviting an expense that's for a payee not yet created, your choices are `invite someone` (an individual) or `create org` (that you will then be admin of), but there's no path for 'invite org', which is what we need to do if the payee is an org that doesn't yet exist.

If I was meant to click `create org` and then put the org admin's email in or something, that was not clear from the UX. I ended up creating the org myself and adding this person as admin, getting them to accept the invite as org admin, then getting them to click the expense invite again, and finally be able to select the new org as the payee.

**Comment by alanna** [comment]
This just came up when creating help docs... This is what I had to instruct users to do:

>  If you already have a personal Open Collective profile, but you need to create a new Organization account to receive this payment, go to your user menu in the top right corner and click the ‘+’ next to My Organizations to create a new Organization profile. Then go back to the notification email and click the blue button again. You will now see your new Organization in the payee dropdown.

It's a pretty roundabout workaround and people who don't have these instructions are not likely to figure it out.

**Comment by kewitz** [comment]
This is just an inconsistency between conditionals. I'm merging a fix for this and we'll have the exact same dropdown for both cases.
