### ISSUE TITLE
Collective Navigation – Elements and buttons polish

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3841]
We are adding the final input on the UI elements of the navigation component:

**Button states:**
<img width="1228" alt="Screen Shot on 2021-01-13 at 23-13-11" src="https://user-images.githubusercontent.com/49539954/104547798-0722c600-55f5-11eb-9726-7cadc7058738.png">

**Update category name in mobile while scrolling:**
We currently have a specific behavior to indicate users where they are when scrolling the page
<img width="1113" alt="Screen Shot on 2021-01-13 at 23-17-42" src="https://user-images.githubusercontent.com/49539954/104548053-992ace80-55f5-11eb-9e53-d64b40439458.png">

This is the way we do the same on smaller screens
<img width="933" alt="Screen Shot on 2021-01-13 at 23-23-01" src="https://user-images.githubusercontent.com/49539954/104548397-5a494880-55f6-11eb-8d82-fe56f1fa7529.png">

See the 🎨 [design file](https://www.figma.com/file/9Iq3vBOmZ2EuOacXEYD5yK/DS-03-Global-Components?node-id=6193%3A0) in figma

@Betree

**Comment by sbinlondon** [comment]
This has been taken care of in the above PR except for the "Categories menu elements" states. Is this a priority @Betree?
