### ISSUE TITLE
Unable to see Host budget, expenses, or find fees transaction

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3846]
I've added funds for the first time to a Collective under https://opencollective.com/giftcollective host. It has an 8% Host Fee, so that transaction and the host fees charged should be showing up on the Host budget. I cannot see the budget section on the host page, and the transactions page is showing nothing. I have also added an expense (https://opencollective.com/giftcollective/expenses/31776) but the expenses section isn't showing up on the Host page either. I checked and all these are set to visible in the profile page settings.

**Comment by znarf** [comment]
> I've added funds for the first time to a Collective under https://opencollective.com/giftcollective host. It has an 8% Host Fee, so that transaction and the host fees charged should be showing up on the Host budget. 

It doesn't work like this. the way it works today, you will get your Host Fees added to your budget at the end of the month.

>  I cannot see the budget section on the host page, and the transactions page is showing nothing. 

If there is no Transactions then the Budget section is currently not displayed.

> I have also added an expense (https://opencollective.com/giftcollective/expenses/31776) but the expenses section isn't showing up on the Host page either.

There is no Expenses section on the Collective page, just a Budget section. As of today, it's not displayed if there is no Transaction.

**Comment by alanna** [comment]
We have expenses we need to pay with this money now. Why would it wait until the first of the month to charge the host fees when the Collective's funds are available right away?

If there is an expense, there should be an expenses section visible. How else can I find the expense we raised?

**Comment by alanna** [comment]
I'm taking the bug label off since apparently it's working as intended, but the UX feels broken.

**Comment by znarf** [comment]
As this issue is mixing different problems, it will be difficult for someone to tackle it. It should be split in follow up issues and closed.

**Comment by alanna** [comment]
Closing in favor of more specific issues.
