### ISSUE TITLE
Bank reference is too long in default template

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3847]
In the bank transfer instructions, you can include the {reference} variable. This outputs [Collective]/[order#]. However, this producing a text string too long to fit in most bank transfer reference fields, so it's confusing. Also, self-hosted Collectives or hosts with just a few Collectives really don't need the Collective name included. So I suggest we have {reference] just be the order# and create another optional variable {collective} that outputs the Collective name.

**Comment by znarf** [comment]
It's actually not the case, `{reference}` will only output the `order.id` from the database.

If the `collective.slug` appears, it's because it's i the template.

**Comment by alanna** [comment]
Oh, sorry I misunderstood! Well in that case I'd just suggest we update the default template to separate them. I can submit a PR myself for this when I get time, so I'll leave this open for now.
