### ISSUE TITLE
Refresh after adding funds

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3851]
I helped an admin add funds to a Collective. He clicked 'add funds' and the modal popped up, and he completed the form and submitted. But when the modal disappeared, the funds did not show up on his page, which he was now viewing. This was confusing. When he refreshed, it showed up. After adding funds, the budget should be updated immediately because users will want to see that change right away.

Specs
------

**API**

- Flush Cloudflare cache
   - happens in https://github.com/opencollective/opencollective-api/blob/4c3d925118818688be59d6a3d3e264d555c0f4c3/server/graphql/v1/mutations/orders.js#L839 
   - similar to https://github.com/opencollective/opencollective-api/blob/4c3d925118818688be59d6a3d3e264d555c0f4c3/server/graphql/v1/mutations/orders.js#L560

**Frontend**

- Refresh or clear `budgetSectionQuery` for the transactions in the Budget section
  - See where it's used and declared https://github.com/opencollective/opencollective-frontend/blob/ff55c1161ef0fa3fe60b3cc99c5c9e61c198266e/components/collective-page/sections/Budget.js#L31
- Refresh `collectivePageQuery` for the stats 
  - See where it's used https://github.com/opencollective/opencollective-frontend/blob/master/pages/collective-page.js#L243      
  -  See where it's declared https://github.com/opencollective/opencollective-frontend/blob/ff55c1161ef0fa3fe60b3cc99c5c9e61c198266e/components/collective-page/graphql/queries.js#L7

Test
----

- 1. Create a Collective
- 2. "Accept Contributions", then pick "Host it ourselves" and activate Stripe (in Test mode, you can skip Stripe's form )
- 3. In the "Actions" menu, pick "Add Funds"
- 4. Enter $1000 and the Collective itself as source
- 5. Submit

The Transaction should appear in the "Budget" section (no refresh) and the balance should be $1000.

Try a second time:

- 1. In the "Actions" menu, pick "Add Funds"
- 2. Enter $1000 and the Collective itself as source
- 4. Submit

The Transaction should immediately appear in the "Budget" section (no refresh) and the balance should be $2000.

**Comment by saideepesh000** [comment]
Hey @alanna, in that function we can do something like window.location.reload() right?

**Comment by Betree** [comment]
@saideepesh000 we don't want a full page reload, either we can directly update Apollo's cache or we use a `refetchQueries` to reload just the data that needs to be updated

**Comment by znarf** [comment]
We also need to make sure to clear Cloudflare cache also to avoid inconsistencies when hard refreshing.

**Comment by znarf** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by znarf** [comment]
@snitin315 Sorry, according to our [rules](https://docs.opencollective.com/help/contributing/development/bounties), only 2 bounties assigned at the same time for you.

**Comment by JoyLubega** [comment]
@znarf can i pick this up

**Comment by znarf** [comment]
@JoyLubega sure! Given the precise specs, I'm gonna put a 1 week limit for it.

**Comment by znarf** [comment]
🏆 This issue was completed by @JoyLubega 

To claim the bounty, you can either:

- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
