### ISSUE TITLE
Edit recurring contribution: menu to pick amount closes immediatly

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3853]
**Describe the bug**
![Peek 2021-01-15 09-48](https://user-images.githubusercontent.com/1556356/104703143-41848400-5717-11eb-95d1-5236b6fd0ff9.gif)

**To Reproduce**
1. Go to your profile > Recurring Contributions
2. Click on Edit
3. Click on "Change amount"
4. Try to pick another value in the select

**Expected behavior**
Menu should act like other selects

**Context**
Tested on latest Firefox, Linux

**Comment by znarf** [comment]
Not reproducing on Firefox / Mac OS.

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by JoyLubega** [comment]
hey @snitin315  Can I please work on this, as you already have another bounty to work on

**Comment by snitin315** [comment]
Hi @JoyLubega, I have already started working on it.

**Comment by snitin315** [comment]
yeah, you can work on it @JoyLubega.

**Comment by JoyLubega** [comment]
Thank you @snitin315

**Comment by bolariin** [comment]
@JoyLubega are you still working on this?

**Comment by JoyLubega** [comment]
Yes.. I am.. raising the fix tomorrow morning.. I had got some challenges
but now am good

**Comment by znarf** [comment]
@JoyLubega we would love to see this fixed. please have an acceptable fix shared today or we will have to give it to someone else.

**Comment by ersachin3112** [comment]
Hi @znarf can I work on this ?

**Comment by znarf** [comment]
@ersachin3112 Sorry, it seems @bolariin wanted to work on it first.

@bolariin For you, if you wish.

**Comment by Betree** [comment]
:trophy: This issue has been completed by @bolariin  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
