### ISSUE TITLE
Edit recurring contribution: amount input UX issues

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3854]
Root cause for https://sentry.io/organizations/open-collective/issues/2147867863

**Describe the bug**
On your profile > Recurring contributions, when you try to edit the amount, there are two issues:
- Minimum amount from the tier is not enforced in the input (it is set at min=100). If you submit with a value that is too low, you'll get an API error that will scroll you at the top of the page (btw it would be great to use a toast notification instead).
- When the input is blurred, some decimals are added which can mislead you into thinking the amount you set is actually much larger

![Peek 2021-01-15 09-50](https://user-images.githubusercontent.com/1556356/104703951-4ac22080-5718-11eb-9436-b917dcef4ce5.gif)

![image](https://user-images.githubusercontent.com/1556356/104703903-3a11aa80-5718-11eb-9558-aec11021cd00.png)

While we're at it, it would be great to replace all the `amount.value * 100` by `amount.valueInCents`, it's clearer and less error prone.

**Comment by znarf** [comment]
Seems Toast notifications are now used, so that's great.

Other points are still valid, especially the default value of "Other" should definitely not be an invalid one (should not be $1 if minimum is $5).

**Comment by znarf** [comment]
Worked on this in https://github.com/opencollective/opencollective-frontend/pull/6351

@Betree just realizing that I haven't really fixed the issue described. In my implementation, you can still set a below minimum amount and will be rejected by the API. It doesn't look too bad or broken.

The alternative is setting appropriate `min`, but then the value is not valid and can't be even passed to the API. 

<img width="691" alt="Screenshot 2021-05-12 at 14 35 03" src="https://user-images.githubusercontent.com/806/117976070-a059b300-b32f-11eb-8790-79c3e4837e6e.png">

Not sure what should be the proper behavior.

**Comment by znarf** [comment]
Is it OK to close the issue, just rely on API side validation? The user experience is ok I would say.

Should we implement Client side validation? Later as an enhancement perhaps?

**Comment by Betree** [comment]
> Is it OK to close the issue, just rely on API side validation? The user experience is ok I would say.

I think so too, as long as the error message from the API is clear that works
