### ISSUE TITLE
Total contributed amount not adding up

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3861]
https://opencollective.com/namaste-foundation

At the top of the screen it says 

> TOTAL AMOUNT CONTRIBUTED $58,470.50 USD

But if you look at the totals on the cards, it adds up to $81,366.

Why are these numbers not matching?

![Screen Shot 2021-01-19 at 9 58 59 AM](https://user-images.githubusercontent.com/5498878/104962369-2aa6a000-5a3d-11eb-983c-95259e58af1f.png)

**Comment by znarf** [comment]
It seems some values are in USD and others in NZD. Then it seems we calculate the total number in USD.
