### ISSUE TITLE
Way to merge profiles

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3862]
Platform admins and support staff often need to merge erroneous profiles. If it has no associated orders or transactions, we can do this using the script in Forest, but if there are transactions we can't. Currently @piamancini does this in Postico, manually changing the Collective ID on every order and transaction with copy/paste. 

Could we have a script that semi-automates this, so we could put in the Collective IDs and it would merge them? That would save Pia a lot of time because me and the other staff could do it ourselves, and it would be more accurate because human error is a factor when there are a bunch of IDs to update.

Can a dev advise whether this would be an easy thing or is more complex?

**Comment by znarf** [comment]
Maybe I'm misunderstanding but such script was introduced by Ben a few weeks ago https://github.com/opencollective/opencollective-api/pull/4961. Back then you actually said it was [awesome](https://opencollective.slack.com/archives/G46PNRCGP/p1607113876024400?thread_ts=1606350841.037400&cid=G46PNRCGP), so maybe it is different?

**Comment by alanna** [comment]
The missing piece is making it so we can actually use it! I have no idea how to access that and @piamancini hasn't been trained to use it either. Just today she was manually copy-pasting like 30 lines in the database.

**Comment by znarf** [comment]
I was confused by the term "script". This thing is effectively not meant for non technical people, so don't expect any instructions or training. But you can ask people from the engineering team to do it for you.

**Comment by alanna** [comment]
Sorry, updated the title. 

So if there's a situation like today where Pia needs to copy paste update the ID on 25 transactions, we should just ask a dev to do it instead?

**Comment by alanna** [comment]
Aha! I just found #3787 - closing this as a dup.
