### ISSUE TITLE
No scroll to the top when moving from step1 to step of the Expenses Flow

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3864]
When moving from Step 1 (Payee information) to Step 2 (Expense Details), I'm not navigated/scrolled to the top and unable to immediately see the form. I have to manually scroll to the top.

**Comment by 304s** [comment]
> When moving from Step 1 (Payee information) to Step 2 (Expense Details), I'm not navigated/scrolled to the top and unable to immediately see the form. I have to manually scroll to the top.

**Comment by znarf** [comment]
A $50 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged. [More info](https://docs.opencollective.com/help/contributing/development/bounties).

**Comment by ersachin3112** [comment]
I am working on it.

**Comment by ersachin3112** [comment]
/cc @znarf  It seems it is already fixed.

![CPT2108041822-828x840](https://user-images.githubusercontent.com/80162912/128184065-a77c5082-fc53-46b2-9283-589bcedadc67.gif)

**Comment by znarf** [comment]
@ersachin3112 Oh, the issue was likely outdated. Thank you for looking at this and sorry for this.
