### ISSUE TITLE
Remove legacy "lib/constants/colors.js"

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3867]
`lib/constants/colors.js` was there before introducing styled-components with a theme to the codebase. We don't want to use it anymore, and it has an history of confusing contributors. We should:
- [ ] Replace the occurrences with existing colors from the design system (`props.theme.colors`)
- [ ] Remove the file

**Comment by ericyoungson** [comment]
Hey, @Betree. I'm interested in taking this one on; seems like a quick entry into learning something about the codebase.

**Comment by Betree** [comment]
@ericyoungson Absolutely! Feel free to ask if you need anything.

**Comment by ericyoungson** [comment]
Thanks, @Betree. I think I'm on the right track but I do have a question about tests. I eliminated the old colors in *Location.js* and the tests pass with `npm run`. I am attempting to run the [full test suite](https://github.com/opencollective/opencollective-frontend/blob/master/docs/e2e.md) but running into an issue building the api. Do I need to do the full test or are pages and components enough?

**Comment by Betree** [comment]
@ericyoungson running all tests locally is tedious, you can submit your PR directly and let the CI run them for you :wink:

**Comment by ericyoungson** [comment]
Great! Thanks.

**Comment by ericyoungson** [comment]
@Betree Looks like most of the remaining references are for *darkgray*. Seems to pass tests with `color: props.theme.colors.darkgray` but I'm trying to verify whether the color exists as the same value `'#797D7F'` in *colors.js*. 

Line 13 in *CollectiveThemeProvider.js* says the colors are defined in *collective.settings.collectivePage.primaryColor*. I can't seem to find it, though.

**Comment by ericyoungson** [comment]
@Betree Looks like most of the remaining references are for *darkgray*. Seems to pass tests with `color: props.theme.colors.darkgray` but I'm trying to verify whether the color exists as the same value `'#797D7F'` in *colors.js*. 

Line 13 in **CollectiveThemeProvider.js** says the colors are defined in `collective.settings.collectivePage.primaryColor`. I can't seem to find it, though.

**Comment by Betree** [comment]
> @Betree Looks like most of the remaining references are for _darkgray_. Seems to pass tests with `color: props.theme.colors.darkgray` but I'm trying to verify whether the color exists as the same value `'#797D7F'` in _colors.js_.
> 
> Line 13 in **CollectiveThemeProvider.js** says the colors are defined in `collective.settings.collectivePage.primaryColor`. I can't seem to find it, though.

What's defined in `collective.settings.collectivePage.primaryColor` is the primary color of the collective, which serves as a seed to generate the theme (if it's defined). Colors themselves are defined `lib/theme/colors.js`
