### ISSUE TITLE
Replace all "Button" and "SmallButton" by "StyledButton"

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3869]
Part of https://github.com/opencollective/opencollective/issues/3289

We have a few occurrences left for `Button` and `SmallButton` in our codebase. They should be replaced with `StyledButton`, and these two legacy components should be removed.

```
12 results - 12 files
===
components/AddPrepaidBudgetModal.js
components/EditEventForm.js
components/SmallButton.js
components/StyledButton.js
components/StyledInput.js
components/StyledLink.js
components/edit-collective/EditTwitterAccount.js
components/edit-collective/sections/HostPlan.js
lib/theme/index.js
pages/createUpdate.js
pages/search.js
server/pages.js
```

**Comment by SudharakaP** [comment]
@Betree : If there's no objection, I'll take this one as it's part of the styled-jsx removal. 😄
