### ISSUE TITLE
Updates: change cursor to pointer for delete/edit actions buttons

### ISSUE THREAD

**Issue by snitin315** [opencollective/opencollective#3879]
**Describe the bug**

The cursor doesn't change to `pointer` when hovering over `edit`/`delete` action buttons of updates.

**To Reproduce**
1. Create an update.
2. Hover on `edit`/`delete`
3. See the error

**Expected behavior**
The cursor should change to `pointer` letting the user know that it's clickable.

**Screenshots**

![update-cursor](https://user-images.githubusercontent.com/46647141/105354262-529d2b80-5c16-11eb-902f-09a589db4ebd.gif)

**Desktop (please complete the following information):**

Any

**Additional context**

**Comment by saideepesh000** [comment]
@snitin315, can I work on this?

**Comment by Betree** [comment]
@saideepesh000 sure you can. Feel free to ask if you need anything

**Comment by Betree** [comment]
Based on the discussion in https://github.com/opencollective/opencollective/issues/3900, we should resolve this by using `StyledButton` with (size=Tiny) for these actions

**Comment by saideepesh000** [comment]
Hey @Betree, I not sure why, whenever I try to create an Collective or an org I'm getting this error, please could you help me with this. I successfully Signed up with STAGED api w/ confirmation mail.
![Screenshot (1)](https://user-images.githubusercontent.com/43727167/105740647-640c6d80-5f5f-11eb-8cbd-22d00d0d6d7d.png)

**Comment by Betree** [comment]
@saideepesh000 Please ask for support on https://github.com/opencollective/opencollective/discussions/categories/development-q-a or on Slack (http://slack.opencollective.com/) #engineering channel
