### ISSUE TITLE
Avatar design update

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3885]
For newly created collectives, we want the avatar to be randomly picked among the three proposed below. To make sure that we always display the same avatar for each collective while keeping the attribution random, I suggest that we pick the default avatar based on the collective ID.

We should also have a `MIN_ID` from where we start applying this policy, to not impact existing collectives:

```es6
const DEFAULT_COLLECTIVE_LOGOS = ['...', '...', '...'];

const getDefaultAvatar = collective => {
  if (collective.id < MIN_COLLECTIVE_ID_FOR_RANDOM_AVATARS) {
    return legacyAvatar;
  } else {
    return DEFAULT_COLLECTIVE_LOGOS[collective.id % 3];
  }
}
```

This must be implemented in the images service: https://github.com/opencollective/opencollective-images

<img width="160" alt="User type=Collective, Mode=New V3, Size=Scalable" src="https://user-images.githubusercontent.com/1556356/105389503-34d0c600-5c18-11eb-80dc-df0eb51d8392.png"> <img width="160" alt="User type=Collective, Mode=New V2, Size=Scalable" src="https://user-images.githubusercontent.com/1556356/105389508-3601f300-5c18-11eb-8ad4-d6a2760ec1b1.png"> <img width="160" alt="User type=Collective, Mode=New V1, Size=Scalable" src="https://user-images.githubusercontent.com/1556356/105389514-37332000-5c18-11eb-88d2-d00bf676a12a.png">

(exported from https://www.figma.com/file/N4Xbl652BhzOutXmzhcrLGch/%5BDS%5D-02-Atoms?node-id=574%3A2439)

**Comment by piamancini** [comment]
- [ ] Review PR

**Comment by Memo-Es** [comment]
@SudharakaP, can we change the previous generic avatars for the new ones? Aside from those newly created?

**Comment by SudharakaP** [comment]
> @SudharakaP, can we change the previous generic avatars for the new ones? Aside from those newly created?

We could do this; just a simple change to remove the condition we added should do it; 

https://github.com/opencollective/opencollective-images/blob/bc7155d61705eed50ceb6a74b3a183e2e2939d48/src/server/controllers/logo.js#L37-L41

@Betree : Do you see any objection to doing this? 🤔

**Comment by Betree** [comment]
No blocker for me. I [initially](https://github.com/opencollective/opencollective/issues/3885#issue-791366805) proposed to only apply that to new collectives to not impact existing collectives. But it's the default avatar, so I don't think that's a big deal to change it @Memo-Es think that's a better approach.

**Comment by SudharakaP** [comment]
> No blocker for me. I [initially](https://github.com/opencollective/opencollective/issues/3885#issue-791366805) proposed to only apply that to new collectives to not impact existing collectives. But it's the default avatar, so I don't think that's a big deal to change it @Memo-Es think that's a better approach.

Done at, https://github.com/opencollective/opencollective-images/pull/511
