### ISSUE TITLE
Tier card design update

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3888]
### Design update
---

Revamped and simplified the tier cards for profile pages
Related issues: #3547

![Sheet](https://user-images.githubusercontent.com/49539954/105449601-52b12180-5c3e-11eb-91c6-2a625e21ddb3.png)

See the [design file 🎨 ](https://www.figma.com/file/9Iq3vBOmZ2EuOacXEYD5yK/DS-03-Global-Components?node-id=6253%3A84)

 ---
@Betree

**Comment by Betree** [comment]
Nice! @snitin315 please note that we're not ready to implement the "Edit" button yet, nor the parts to customize the images and colors (tracking that in https://github.com/opencollective/opencollective/issues/3438 + https://github.com/opencollective/opencollective/issues/2121). All the other parts can safely be implemented.

**Comment by snitin315** [comment]
The design file says `ATTENDING` for both tickets and past events. I think it should be `ATTENDED BY` for past events. 

![screenshot-www-figma-com-file-9Iq3vBOmZ2EuOacXEYD5yK-5BDS-5D-03-Global-Components-1611637910625](https://user-images.githubusercontent.com/46647141/105803660-f21a3f80-5fc3-11eb-8370-f8444e1142e8.png)
