### ISSUE TITLE
Help with mission statement limitation

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#389]
Update mission statement here: https://opencollective.com/reconomycop 

Current version has exactly 100 characters, new version 99 - still, I get "Mission" length muss be less than or equal to 100 characters long message when I want to save, so I'm not able to change the text. 

Maybe you can do it for me? 😁 Here it is: 

Supporting regenerative entrepreneurs and community organizers worldwide to spread ideas that work.

**Comment by piamancini** [comment]
done
