### ISSUE TITLE
Add Structured Bank Account Information for non TransferWise users

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#3893]
Use the platform token to generate the payout method Bank Information form.
We already have this implemented for storing the Bank Account information in the Host _Receiving Money_ settings, what we need to do is to render the correct modal option to the host, because if they don't use TransferWise, we'll need to just render the normal manual modal with the rendered information.
Also, it would be interesting to add an option to enable only selected currencies in the Host settings.

Desirable to implement #3386 first.

**Comment by piamancini** [comment]
+ 1 to fix this. For users without Wise this is very annoying

**Comment by SudharakaP** [comment]
As discussed at [Q2S2 priorities](https://docs.google.com/document/d/1KQKlImKIHwsCiF_cGbkU7tn8otl6gve0uqbBXXl_kvU/edit) I'll be working on this and therefore I am assigning this myself. 😄
