### ISSUE TITLE
Notification of comment on Update should show what Collective it's for

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3895]
The email notification for comments on Updates only shows the name of the Update, not the name of the Collective. If you have multiple Collectives this isn't very helpful.

<img width="882" alt="Screen Shot 2021-01-23 at 9 46 25 AM" src="https://user-images.githubusercontent.com/5498878/105544693-1fff4a00-5d60-11eb-82af-fd442b64dedb.png">

**Comment by bolariin** [comment]
@alanna @Betree It looks like this might have already been addressed. Looking at the code, it looks like the collective name is used as the email recipient so it's `Hi {collective.name}`. https://github.com/opencollective/opencollective-api/blob/b8641a1facc4ea048bd8410bc5ebd126749e0bfe/templates/emails/collective.comment.created.hbs#L29

**Comment by Betree** [comment]
@alanna @bolariin is right, the name of the collective is mentioned in this email. In the screenshot you shared, `Hi Known`, "Known" is actually the name of your collective (https://opencollective.com/known).
