### ISSUE TITLE
Displaying currency twice

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3898]
<img width="314" alt="Screen Shot 2021-01-23 at 2 43 26 PM" src="https://user-images.githubusercontent.com/5498878/105564973-69b05a80-5d89-11eb-88e4-f7cb575a3912.png">

This should say either "NZ$2500" or "$2500 NZD" but not both. Same for the line below.

**Comment by znarf** [comment]
Might not be beautiful but at least people can't miss it. I've seen people easily confuse USD and NZD on the platform.

It looks generally good for euro, dollar and gbp which are the currencies most used on the platform.

**Comment by sudo-kaizen** [comment]
Hello @Betree is there any resolution on the specs for fixing this? I'll like to take it up

**Comment by Betree** [comment]
@sudo-kaizen I haven't looked into specs yet, but it's something we probably want to fix in `components/FormattedMoneyAmount.js` and / or `components/Currency.js`. Ideally we should also create unit tests to prevent regressions on other currencies and make sure it looks good with all condition (`showCurrencyCode=false`, `abbreviate`, etc.)

**Comment by sudo-kaizen** [comment]
@Betree Great! I'll like to take it up. Could you please update this space with the specs when the tests are ready? Thanks

**Comment by znarf** [comment]
Sharing another example that doesn't looks good:

<img width="1057" alt="Screenshot 2021-01-28 at 14 02 18" src="https://user-images.githubusercontent.com/806/106142227-85dd3e80-6171-11eb-9a77-8f98f3c3a097.png">

**Comment by sudo-kaizen** [comment]
What file is the source of this? I really can wait for the spec for this.
Are there currencies that are supposed to have their abbreviations as prefixes and others as suffixes?

**Comment by Betree** [comment]
Also reported by @Memo-Es in https://opencollective.slack.com/archives/C012T9JR3BR/p1612878946004600 for `MXN`:
![image](https://user-images.githubusercontent.com/1556356/107373663-11968980-6ae7-11eb-9bec-f22f993aa0bf.png)

**Comment by znarf** [comment]
I think we should have a clear definitions of these things, and a single helper for each of them to display.

In the case of mexican dollar:
1) simplified currency sign/symbol: `$` https://en.wikipedia.org/wiki/Currency_symbol
2) full currency sign/symbol: `MX$` What is the reference for this?
3) currency code: `MXN` https://en.wikipedia.org/wiki/ISO_4217

In this case, we should never display 1) and 3) at the same time, so either 2) alone, or 1) together with 3)

**Comment by sudo-kaizen** [comment]
Will having a `country -> currency symbol` map for implementing 2) alone for all currencies be a good solution to this?

**Comment by Betree** [comment]
> In this case, we should never display 1) and 3) at the same time, so either 2) alone, or 1) together with 3)

@znarf I suppose you mean we should never display **2)** and 3) at the same time?

> Will having a `country -> currency symbol` map for implementing 2) alone for all currencies be a good solution to this?

We need to investigate and understand the issue properly before jumping on the implementation. For that we need to dig into the `FormattedMoneyAmount`/`formatCurrency` helpers to understand where we output the different part of the amount/currency (as described in https://github.com/opencollective/opencollective/issues/3898#issuecomment-776055827) and where it's failing.

For `FormattedMoneyAmount`, if `showCurrencyCode` is true, I think the expected behavior is to have 1) + 3): `$42 MXN`, that's how the component was designed. If it's false, the expected behavior would be to have `MX$42`. So we need something to switch between the simplified currency sign and the full one.

Also, we should ideally back all that with unit tests.

**Comment by sudo-kaizen** [comment]
Apart from 'Technovation Girls', are there any other collectives that I can use to replicate this issue? Currencies on my computer are appearing in `USD` and a search  for  'Huddles' doesn't bring back any results

**Comment by alanna** [comment]
Can this be a bounty?

**Comment by SudharakaP** [comment]
@alanna : The specs aren't clear in my opinion and thus this cannot be a bounty for now, but I am pinging @Betree so they can weigh in when they return. 😄

**Comment by znarf** [comment]
https://ux.stackexchange.com/questions/9105/international-currency-formatting-guidelines-currency-codes

I would say we can use 1) alone, if **and only if** it's **100% clear** in the context what the currency is.

In all other cases, we should use 1) followed by 3). We should stop using 2).
