### ISSUE TITLE
Unclear action links in Update admin view

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3900]
If you are the admin of a Collective looking at a published Update, you see this:

<img width="555" alt="Screen Shot 2021-01-23 at 3 32 57 PM" src="https://user-images.githubusercontent.com/5498878/105566318-5f458f00-5d90-11eb-8d03-ea19fabc1347.png">

The `Admin` label looks like a button, while the `edit` and `delete` links do not look like buttons. If you hover over them, the cursor does not change to indicate a link.

**Comment by Betree** [comment]
`Admin` is using the default "Tag" styles from our design system, we could eventually make it clearer by using uppercase text.

Regarding "Edit" and "Delete", I agree these should be buttons.

**Comment by snitin315** [comment]
We alreaady have a separate issue for `Edit`/`Delete` Actions -> https://github.com/opencollective/opencollective/issues/3879
