### ISSUE TITLE
Semi-automation of allocation payments for GitHub Sponsors

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#3903]
Allocating payments to Collectives hosted by Open Source Collective that collect funds on GitHub Sponsors is becoming time consuming enough to consider automation. There are around 100 such Collectives at the moment compared with around 600 in total using GitHub Sponsors. This situation is not going to improve without some intervention.

### Current monthly process

1. Login to GitHub Sponsors accounts on GitHub as the account admin. Go to the OSC account, select Fiscal Host and choose the Payout Export option. The report is then to be emailed to hello@oscollective.org. 

![Capture](https://user-images.githubusercontent.com/57156267/105619055-95981280-5e53-11eb-8610-052b39caf0ce.JPG)

2. Open the report and filter on the recent transactions 
3. Log in to Xero and got to OSC dashboard to reconcile open transactions
4. Go to OSC Host Dashboard - Hosted Collectives tab
5. Identify the payout details in the report by searching the amount in the report and pulling the collective details out of the report. 
6. Look for the collective, and use the process of adding funds manually to allocate the payout amount. We adding 5% for host fees and 5% for platform fees. Description added is "GitHub Sponsors [month] payment" and as an organization ensure to select github-sponsors. 
7. Once funds are allocated, mark the amount as allocated in the report and reconcile the funds in Xero. For this use GitHub Sponsors as the source and description is the same as applied on the platform. 
8. Any remaining unreconciled amounts are to be followed us with GitHub Sponsors project team

### Proposal

Around 80% of the projects that are on GitHub Sponsors and Open Collective use the same handle/slug. A Script that parsed the report from GitHub, matched the slug and added the necessary funds through the GraphQL API would alleviate a lot of the work. the script could output a report with funds allocated and runs left to allocate. From there the team member can allocate manually as above.

**Comment by znarf** [comment]
It seems more complicated to automate than what I thought, all the reconciliation is difficult.

If you could end up with a spreadsheet/CSV with the list of all collectives (with their slug) and the amount of money that needs to be wired, we could create some batching to Add Funds automatically.

**Comment by alanna** [comment]
> If you could end up with a spreadsheet/CSV with the list of all collectives (with their slug) and the amount of money that needs to be wired, we could create some batching to Add Funds automatically

@znarf this is what we already export from Github

**Comment by znarf** [comment]
@alanna Sounds great. I tried to get access to such report today without luck, see on Slack. Please forward me a sample so I can have a look.

**Comment by alanna** [comment]
Creating pending orders would be a great step. @znarf if you'd require any changes to the data export to enable this, let us know the specifics and we can request them to Github. No guarantees about what they can do but we can ask.

**Comment by alanna** [comment]
@znarf - OSC should pay for any significant develop time that gets spent on this, so please check with me or @piamancini before spending too much time, because we have to balance OSC's budget priorities, and while this process is currently painful, it is a functioning MVP we can live with for a little while longer if we have to.

**Comment by BenJam** [comment]
Just found this issues and encouraged @alinamanko to move the docuemtnation to https://app.gitbook.com/o/-LWSZizNMEjL8_DrMNdF/s/-MkoLSqv45-IqGUC_Gy-/c/tOoepGYtd0YVp2doS83p/github-sponsors 

I've updated the title and the desripction above to include some improvements following my experience last month.

**Comment by alanna** [comment]
Bumping this issue. We had an ops deep dive session today and @alinamanko is identifying that this is now scaling beyond what's feasible to handle manually.

To clarify the scope, this is what we would like:

1. We download the CSV from github ([example](https://drive.google.com/file/d/16LDlht1OHJanNXWALA7O-jZhn77XZUW0/view?usp=sharing))
2. We'll check that the total from the data matches the total received in the bank manually
2. We upload the CSV somewhere a script can ingest it
3. The script creates transactions on OC that credit each Collective the amount for them on the spreadsheet

There is no need to do a pending order that needs to be confirmed. It should just automatically credit the money with no further action required, as a contribution to the Collective from the [Github Sponsors org profile](https://opencollective.com/github-sponsors).

The main problem I see is Github uses an organization name on the CSV that does not necessarily match the OC slug. But if we can find a way to handle this we should be good to go.

@znarf @BenJam does this seem achievable?

**Comment by znarf** [comment]
This is prioritized in 2022 Q1 Sprint 1 as a use case for the API Project. We will deliver a command line tool that parse the CSV and create the Added Funds contributions using the API.

This will be manually triggered on a monthly basis by someone with enough technical knowledge (at first the engineering team, later other OSC admins).

**Comment by alinamanko** [comment]
@znarf one comment from me is that the slugs we have are not always a direct match to the names showing on the GitHub export. I am attaching the latest one here for context
[sponsors-Open-Source-Collective-payouts-2022-01-25 (1).csv](https://github.com/opencollective/opencollective/files/7966837/sponsors-Open-Source-Collective-payouts-2022-01-25.1.csv)
.

**Comment by znarf** [comment]
@alinamanko I'm aware of this and the tool will be designed around this.

The tool is almost ready, we should be able to process the next batch with it. Just let me know when you have the CSV available.
