### ISSUE TITLE
Payment receipts dates are incorrect

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3907]
1. January is still ongoing. The dates for available consolidated monthly receipts should only go up to December right now. And definitely not February, which hasn't even begun.

![Screen Shot 2021-01-25 at 11 34 22 AM](https://user-images.githubusercontent.com/5498878/105645877-63dd8500-5f01-11eb-8479-c9779420cf47.png)

2. If I download the one for OSC under December, the actual receipt is for November.

![Screen Shot 2021-01-25 at 11 36 40 AM](https://user-images.githubusercontent.com/5498878/105645920-9edfb880-5f01-11eb-8eae-1371ae09e186.png)

<img width="827" alt="Screen Shot 2021-01-25 at 11 33 27 AM" src="https://user-images.githubusercontent.com/5498878/105645904-866f9e00-5f01-11eb-8d3d-35a3c52d733b.png">

**Comment by znarf** [comment]
Receipts appearing for ongoing months is something that was already mentioned in https://github.com/opencollective/opencollective/issues/3684

I'm not sure why the label is now month+1, it was definitely not the case last time I reviewed the feature. Might be a regression.

**Comment by Betree** [comment]
There was a change in https://github.com/opencollective/opencollective-frontend/pull/5681 to migrate this to `FormattedDate`, it's probably the source of the regression. Looking into it
