### ISSUE TITLE
Multi Level Expense Approvals

### ISSUE THREAD

**Issue by hellopetersmith** [opencollective/opencollective#3911]
## User story 
_As Admin, I can set approval assignments on an expense so that an expense can go through the appropriate approval process (with different people playing a different role in the process, i.e. project lead approves that the right person submitted the right amount, finance lead approves the funds leaving the account based upon our available funds and our budget/forecast). no expense is fully approved all assigned users have approved it_

## Best solution for this problem
_What does the ideal solution look like?_ 1) there is a global setting that can set the default approval assignments, i.e. User1 is assigned, if/when they approve, it moves to User2. 2) this setting can be updated on a per expense basis. Any admin can re-assign the expense approval. 3) a user can view all of the pending approvals assigned to them.

## MVP
_What will be built as an MVP? (Please refer to our [wiki](https://github.com/opencollective/opencollective/wiki/Feature-Spec-Template) for what's acceptable as an MVP.)_ Ability to set an approval waterfall for two users as an account default. 

## Metrics 
_What metrics will be used to measure impact?_ 0 expense approvals overturned.

## Documentation 
_The goal of the documentation should be to make it easier for others to do this_

**Comment by alanna** [comment]
Related: #3328 , #3081

**Comment by BenJam** [comment]
closing in favour of #3081 (consolidation)
