### ISSUE TITLE
Broken route when inputting tha page number directly

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3914]
**Describe the bug**
On multiple pages using pagination, typing the page number + Enter breaks the URL.

Affected:
- Expenses page
- Transactions page
- Host dashboard
- Maybe more

**To Reproduce**
1. Go to https://staging.opencollective.com/babel/expenses/
2. Scroll down to the pagination
3. Type any valid number in the box and press Enter
4. Check URL

**Expected behavior**
URL should be properly formatted, just like if you click on "Prev" / "Next" buttons. Ideally we want to fix this globally, as all places using `components/Pagination.js` could be affected by the issue.

**Screenshots**
![Peek 2021-01-26 16-53](https://user-images.githubusercontent.com/1556356/105869049-1e9b7f00-5ff7-11eb-95af-927feb240d49.gif)

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by Yetizone** [comment]
I'll try to work on this one if that's alright. Any specific deadline for submitting a patch ?

**Comment by Betree** [comment]
> I'll try to work on this one if that's alright. Any specific deadline for submitting a patch ?

Sure! let's say 10 days, we can later extend if there's progress.

**Comment by JoyLubega** [comment]
Hi @Yetizone If you need any help on this am available to help

**Comment by Yetizone** [comment]
Thanks @JoyLubega, but I already have a linked PR which I've updated about a week ago, and I think it's ready for the most part, currently waiting for a review on it :)

**Comment by JoyLubega** [comment]
okay, great

**Comment by Betree** [comment]
Will be fixed by https://github.com/opencollective/opencollective-frontend/pull/5855/commits/04a6384a4bbad9d31fc63e4407f86183e2578a1d

**Comment by Betree** [comment]
Fixed in https://github.com/opencollective/opencollective-frontend/commit/04a6384a4bbad9d31fc63e4407f86183e2578a1d
