### ISSUE TITLE
Top Sponsors in single column

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3915]
https://opencollective.com/open-web-docs

This looks odd... isn't it supposed to be in two columns?

![Screen Shot 2021-01-27 at 9 44 16 AM](https://user-images.githubusercontent.com/5498878/105906800-07a56d00-6089-11eb-99c7-97d6ace2ce4b.png)

**Comment by Betree** [comment]
It seems that the size reduction that happened with the release of the new navbar triggered this. I'll look into it
