### ISSUE TITLE
Include message to communicate expense submitters that money will take some time to arrive

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3916]
We want to change the automated email that people receive when they have submitted expenses claims via bank transfer. They receive a mail to say their expense has been marked as paid but **the money will arrive in their account according to each bank's timeline.**

Can we add that to the paid notification email? @Betree

**Comment by Betree** [comment]
@Memo-Es Sure, the template is https://github.com/opencollective/opencollective-api/blob/master/templates/emails/collective.expense.paid.hbs#L24. What should be the copy? I can suggest:
> The money can take a few days to arrive, depending on each bank's timeline.

Below the main paragraph (`Just a quick note to let you know that your expense ... has just been paid`)

**Comment by Memo-Es** [comment]
Looks good to me @Betree

**Comment by Memo-Es** [comment]
@Betree based on recent feedback, we should also include this **other case:**
 
2) The email after someone donates via bank transfer:
Can the reference number be made clearer/bolder/bigger?
