### ISSUE TITLE
Enable tax forms for OC Inc

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3926]
Tax form should be enabled for expenses submitted to https://opencollective.com/opencollective/expenses/

**Comment by alanna** [comment]
It should be enabled for the whole host, not just that Collective.

**Comment by Betree** [comment]
Yes, https://opencollective.com/opencollective is the host for all the other collectives so enabling it there will automatically enable it on all hosted collectives (engineering, design, etc).

**Comment by znarf** [comment]
@Betree Is this just about creating an entry in the RequiredDocumentsTable?

**Comment by Betree** [comment]
Yes, then monitor the emails sent to make sure there's nothing wrong in there

**Comment by Betree** [comment]
Done, I will monitor the effects in the next few days

**Comment by Betree** [comment]
Looking good, the volume hasn't bumped much. Most of the emails were for Open Collective team members

![image](https://user-images.githubusercontent.com/1556356/119006735-e7c7eb00-b990-11eb-9cf0-fac1e5c1d3fd.png)
