### ISSUE TITLE
Out of Date Note About Fiscal Hosting Plans?

### ISSUE THREAD

**Issue by zicklag** [opencollective/opencollective#3927]
I noticed this note in the docs:

![image](https://user-images.githubusercontent.com/25393315/106181800-a4d4d400-6163-11eb-84fe-30ea95317bf4.png)

But that seems to contradict what is currently in the plans dashboard for the Starter Plan, which indicates unlimited bank transfers:

![image](https://user-images.githubusercontent.com/25393315/106181881-bcac5800-6163-11eb-9614-ca4edec5bc98.png)

**Comment by znarf** [comment]
The documentation is indeed out of date and needs to be updated.

- This page: https://docs.opencollective.com/help/about/pricing
- This notice: https://docs.opencollective.com/help/fiscal-hosts/bank-transfers#bank-transfers
- This notice: https://docs.opencollective.com/help/fiscal-hosts/add-funds-manually

The pricing page is up to date: https://opencollective.com/pricing But we're working on a clearer version https://github.com/opencollective/opencollective/issues/3912

**Comment by shannondwray** [comment]
Hey! Alanna has said to wait for the new pricing page to go live and then we can look through the rest of the documentation to make sure its all accurate. Thank you for this!

**Comment by znarf** [comment]
@shannondwray the new pricing page is live: https://opencollective.com/pricing

**Comment by znarf** [comment]
This page still contains info about deprecated Host Plans https://docs.opencollective.com/help/fiscal-hosts/bank-transfers#bank-transfers @alanna @shannondwray

**Comment by BenJam** [comment]
assigned @shannondwray I'll take a look too

**Comment by shannondwray** [comment]
Sorted :)
