### ISSUE TITLE
Odd line break in expense summary title

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3928]
When I'm editing the expense it looks like this:
![Screen Shot 2021-01-29 at 11 14 33 AM](https://user-images.githubusercontent.com/5498878/106205513-7ae2e680-6223-11eb-815d-57d960cc8818.png)

But on the summary it looks like this:
![Screen Shot 2021-01-29 at 11 14 43 AM](https://user-images.githubusercontent.com/5498878/106205523-7f0f0400-6223-11eb-8718-25dadfcf1559.png)

**Comment by sbinlondon** [comment]
This might be related to my PR from last week - I'll have a look.
