### ISSUE TITLE
Styling issues in "Join The Movement" section at /how-it works

### ISSUE THREAD

**Issue by saideepesh000** [opencollective/opencollective#3929]
**Describe the bug**
Buttons in the "Join The Movement" section at [/how-it-works](https://opencollective.com/how-it-works) has got some padding issues.

**To Reproduce**
1. Go to [/how-it-works](https://opencollective.com/how-it-works) 
2. Scroll down to 'Join The Movement' section
3. See the styling of the buttons

**Expected behavior**
Styling of the buttons can be improved

**Screenshots**
![Screenshot (10)](https://user-images.githubusercontent.com/43727167/106283079-793b1200-6267-11eb-86d9-724fb506a115.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 84(may be)

**Comment by saideepesh000** [comment]
Can I try this?

**Comment by snitin315** [comment]
@saideepesh000 yes.
