### ISSUE TITLE
Contribution flow: guest flow responsiveness issue

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3931]
**Describe the bug**
See screenshot

![IMG_20210130_005536.jpg](https://user-images.githubusercontent.com/1556356/106339101-e4034200-6295-11eb-9169-ffe82c05ce53.jpg)

**Comment by devansh5** [comment]
Hey @Betree , I would like to work on this issue?

**Comment by Betree** [comment]
It's now partially resolved, but each field should ideally take the full width on mobile

![image](https://user-images.githubusercontent.com/1556356/107378851-ae0f5a80-6aec-11eb-9e9d-223dc3043848.png)

**Comment by piamancini** [comment]
+1 to this, looks a bit unprofessional -

**Comment by alinamanko** [comment]
+1
