### ISSUE TITLE
Tax amount wrongly recorded for platform tips

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3934]
**Describe the bug**
The following query returns 4 transactions platform tip transactions that have a tax amount.

```sql
SELECT *
FROM "Transactions" t 
WHERE "taxAmount" < 0
AND "deletedAt" IS NULL
AND currency != 'EUR'
```

There are a few problems there:
- The `platformFee` is just a copy/paste form the parent, so the amounts don't make sense ($0.20 VAT on $0.18 platform tip).
- VAT should not be applied on platform tip, because it's a donation
- The currency conversations that happened in the middle is probably wrong, because https://github.com/opencollective/opencollective-api/blob/5917789e33beab5027416c356e26783e5cd479f7/server/models/Transaction.js#L624 wrongly assumes that the tax amount is expressed in the host currency (while it's using `transaction.currency`). _Edit: this was resolved in https://github.com/opencollective/opencollective-api/pull/5203, but we haven't fixed past entries._

**To Reproduce**
1. Enable VAT and platform tips on an host using euros
2. Make a financial contribution with VAT and give a platform tip
3. See wrong transaction

**Expected behavior**
- [x] https://github.com/opencollective/opencollective-api/blob/5917789e33beab5027416c356e26783e5cd479f7/server/models/Transaction.js#L624 should consider `taxAmount` in `transactions.currency`, not host currency => https://github.com/opencollective/opencollective-api/pull/5203
- [x] In the contribution flow (and `createOrder` mutation), we should ignore the platform tip when calculating the tax amount
- [x] We should update the 4 transactions currently in the DB to match this fixed behavior

**Additional context**
This is a followup on https://github.com/opencollective/opencollective-api/pull/5203#discussion_r567724555

**Comment by znarf** [comment]
I'm currently writing some automated tests against the ledger and this issue was one of the first spotted.

**Comment by alanna** [comment]
Was this fixed @znarf
