### ISSUE TITLE
Link timing of host fees being credited and monthly reports

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3938]
I got the monthly report for a Fiscal Host's budget (i.e. the Collective report for that Host's Collective) and it did not show the monthly host fees applied as expected. We should link the timing of crediting monthly host fees (and debiting platform fees) and the monthly reports, so those transactions show up. For a Host Collective those are the key stats I'm looking for in the report.

**Comment by znarf** [comment]
It should normally be executed the same day, more or less at the same time.
