### ISSUE TITLE
unmatched sponsor logo returned

### ISSUE THREAD

**Issue by outsideris** [opencollective/opencollective#3948]
**Describe the bug**
For [mocha](https://opencollective.com/mochajs), we received the below data for CodePilot.ai sponsor via GraphQL

```
{
  name: 'CodePilot.ai',
  slug: 'codepilotai',
  website: 'https://codepilot.ai',
  imgUrlMed: 'https://images.opencollective.com/codepilotai/732befb/logo/64.png',
  imgUrlSmall: 'https://images.opencollective.com/codepilotai/732befb/logo/32.png',
  firstDonation: '2018-02-09T23:39:30.388Z',
  totalDonations: 25000,
  type: 'ORGANIZATION',
  categories: [],
  avatar: 'https://images.opencollective.com/codepilotai/732befb/logo/64.png',
  tier: 'sponsor'
}
```

But the image <https://images.opencollective.com/codepilotai/732befb/logo/64.png> is Netlify logo, not CodePilot.ai.

Could check it?

**To Reproduce**
visit <https://images.opencollective.com/codepilotai/732befb/logo/64.png>

**Expected behavior**
Return CodePilot.aio logo.

**Comment by znarf** [comment]
Because Codepilot.ai hasn't uploaded a logo, Open Collective is defaulting to a third party API which is sending back the wrong logo https://logo.clearbit.com/codepilot.ai. That is unfortunate.

The simple workaround is to ask Codepilot.ai to upload their logo on their Open Collective profile.

**Comment by outsideris** [comment]
Ok, I understood what happened.
