### ISSUE TITLE
Support Metrics Report - January 2021

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#3949]
### Support Metrics Report - January 2021

This report looks at the trends around support to help us better understand areas we need to improve and highlight key topics for the month. 

**Tickets received** 

![Capture](https://user-images.githubusercontent.com/57156267/107160032-9f477b80-69f8-11eb-9437-bb572de9a5a2.JPG)

The number of tickets received decreased slightly (10%) from 493 in December to 443 in January. By removing blank tickets, tickets raised in January decreased just slightly (~5%) - 317 tickets compared to 335 in December. [You can find the detailed listings here.](https://docs.google.com/spreadsheets/d/1pO6FQzpxUXpBms43J94rxhX4toU2IP3S/edit#gid=1241963015)

![Capture](https://user-images.githubusercontent.com/57156267/107160051-c43bee80-69f8-11eb-9e2d-0ecec411433a.JPG)

**Trends and Recommendations**
After removing irrelevant tickets, we had 317 that required support attention. It is worth noting the following areas:

**Expenses**

Questions related to expenses continue to be our biggest ticket item. This month, the majority of tickets raised relate to collective under the Social Change Nest host and those are mostly follow-ups on the status of an expense submitted. This category has dropped significantly in comparison to the previous month (41%) but still requires our attention to direct those email to the fiscal host.

The expenses related questions are on a moderate rise with OCF as well. This is reflected in the increase of expenses processed to $449k during January, which represents a noticeable 60% jump from December. With the increase of new collectives, it is safe to assume these numbers will keep on going up significantly and this is something we should take into consideration as expenses processed for OSC keep on a much more modest increase and keep rather consistent fluctuations (more invoices around the beginning of the month for contributors). 

From questions received under OCF, there is a rising interest in the pre-paid cards option to simplify the process of paying community members in need. 

Grant matching

The increase in the tickets received showing in the graph above (19 vs 6 in previous months) is quite deceiving. While there is a genuine increase in grant matching coming through Benevity, the majority of tickets this month are from automated updates from Verizon, in most occasions relating to similar contributions. But it is good to see the activity through this organization is on the rise as well. The actual number of questions related to this area is very much in line with previous months. 
 
**Onboarding** 

Onboarding keeps on being one of the leading categories. We approved 21 new applications for hosting compared with 23 in December.

For OSC -  58 new collectives were approved during January compared to 20 in December. 

**Grants**

I would like to address two trends here. First, in relation to external grants allocated to collectives under OCF, there is a genuine increase of enquiries and updates we receive from various groups which is really encouraging. There was a big spike this month in grant application paperwork sent to us to verify as well as incoming funds. This is true for a variety of mutual aid groups and also the allocation of payments for Digital Infrastructure starting to come through. 

On the other hand, there is also an increase in grants being allocated by various groups to their communities and we still revise the process around the administration of requests submitted. [You can find the current documentation on the relevant collectives here.](https://drive.google.com/drive/folders/1MpmYqvivAd8odOYR_W1qkvzbhhXCC-AL)

**Other things to note**
Payments errors showing in the report were mostly due to an issue with Guest contributions which since [we decided to drop due to extra complexities caused
](https://github.com/opencollective/opencollective/issues/3884)

**Comment by piamancini** [comment]
thank you @alinamanko!

**Comment by alanna** [comment]
Again I want to plug #3740 - if not as an expense comment, replies to expense notifications should at least go to the fiscal host. We can't be providing support for every fiscal host's payment issues, and unless it's a host we manage, we cannot resolve the queries anyway sometimes.

**Comment by Betree** [comment]
> Payments errors showing in the report were mostly due to an issue with Guest contributions which since [we decided to drop due to extra complexities caused
](https://github.com/opencollective/opencollective/issues/3884)

We're not dropping guest contributions, https://github.com/opencollective/opencollective/issues/3884 is just about changing the way we handle them on the API side.

**Comment by alinamanko** [comment]
Thank you for the clarification @Betree
