### ISSUE TITLE
Include Funds in Top Financial Contributors

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#3950]
We've been growing Funds as an option for companies to manage their contributions on open collective. When we turn 'organizations' into 'funds' the companies loose their stop in the Top Financial Contributors display. 
We should add them to it.

**Comment by znarf** [comment]
https://github.com/opencollective/opencollective-frontend/pull/5859

**Comment by znarf** [comment]
Fixed and deployed.
