### ISSUE TITLE
Discord Webhooks

### ISSUE THREAD

**Issue by blueridger** [opencollective/opencollective#3951]
## User story 
_As an admin of a collective with a discord server, I can add a discord webhook to my collective so that collective activity is sent to Discord for higher visibility._

## Best solution for this problem
Enter the webhook url into the admin portal and configure options.

## MVP

Use the [discord.js library](https://discord.js.org/#/docs/main/stable/examples/webhook) to add a new [notification type](https://github.com/opencollective/opencollective-api/blob/master/server/lib/notifications.js) to the OC api so that power users can email a webhook url to OC admin, just like the slack and glitter integrations are done currently.
## Metrics 
Number of discord webhooks added. Error rates.

## Documentation 
https://discord.js.org/#/docs/main/stable/examples/webhook
https://github.com/opencollective/opencollective-api/blob/master/server/lib/notifications.js
https://github.com/opencollective/opencollective-api/blob/master/server/lib/slack.js

**Comment by Betree** [comment]
Since Discord webhooks are compatible with Slack webhooks (see https://discord.com/developers/docs/resources/webhook#execute-slackcompatible-webhook), can't we just re-use them?

**Comment by blueridger** [comment]
It's possible. It depends on whether the helper library you use `node-slack` is compatible. At best, `node-slack` can send to discord webhook urls just fine and no code change is required. At worst, you just need to copy the slack notifications code and replace the `node-slack` client with the `discord.js` client. I'd be happy to assist with testing.

**Comment by blueridger** [comment]
Adding the webhook url at https://opencollective.com/sourcecred/edit/webhooks with and without the `/slack` modifier didn't work. I imagine this was because it did not recognize the `channel` as slack, and it might still be worth trying to manually set the webhook channel to `slack` via the DB console. Feel free to make that change to the webhook under the `sourcecred` slug, and I'll retest if you do.

**Comment by Betree** [comment]
> Adding the webhook url at opencollective.com/sourcecred/edit/webhooks with and without the /slack modifier didn't work

@blueridger We also have some related things to improve on that page: #3448. 

I've moved your webhook to the `slack` channel type, could you try and let me know if it works as expected?

**Comment by tangjeff0** [comment]
What information is sent in the Slack/Discord Webhook? Also a big fan of Discord and OpenCollective (and SourceCred).

**Comment by blueridger** [comment]
@Betree the slack-style discord web hook is working now!

**Comment by tangjeff0** [comment]
Just added my discord URL to OpenCollective. Can you change the type to `slack` for me as well @Betree ?

**Comment by Betree** [comment]
@tangjeff0 It's done, I've also updated your webhook URL to add the `/slack` suffix (see https://discord.com/developers/docs/resources/webhook#execute-slackcompatible-webhook).

**Comment by tangjeff0** [comment]
Thank you. I was making test donations each time :sweat_smile: Good for you guys and visa though!

**Comment by tangjeff0** [comment]
@Betree I'm pretty sure the webhooks page doesn't let you have more than one webook, but ended up creating my own webhook for Discord so no worries.

**Comment by Betree** [comment]
@tangjeff0 The webhooks page only displays "normal" webhooks, as soon as I turned yours into a Slack webhook it disappeared from this view (we intend to change that in https://github.com/opencollective/opencollective/issues/3448)
