### ISSUE TITLE
Insufficient funds to pay platform fee

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3955]
Gift Collective received an expense for platform fees, the 15% of host fees to be paid to Open Collective. However, there is insufficient budget to pay the expense. This should not be possible - the expense should go in at the same time as the credit of the platform part of host fees hits the budget. We can't have situations where a host can pay money out that it actually owes Open Collective, so how is this happening? If part of the host fee credit we got last week was meant to be held back for Open Collective, then the system should not have let us pay the big legal expense we had outstanding and clear out the host budget.

![Screen Shot 2021-02-09 at 10 58 02 AM](https://user-images.githubusercontent.com/5498878/107286791-ef404400-6ac5-11eb-8e17-52a0b68ac701.png)

**Comment by znarf** [comment]
>  We can't have situations where a host can pay money out that it actually owes Open Collective, so how is this happening?

Part of the Host Fees added to the budget (the one not paid with Stripe) will need to be returned to Open Collective in the settlement expense, it works like that.

Next month, we can try to send everything the same day.

**Comment by alanna** [comment]
OK... I have no idea when more host fees will be coming into this host, so it could be a while before we can pay the OC expense. We had a bunch of host fees up front due to big grants, and nothing on the immediate horizon.

**Comment by znarf** [comment]
I remember a discussion where team members were explicitly gave the feedback that it should not necessarily be triggered the 1st of the month, that a few day later would be nice.

In light of this issue, we should reconsider and send everything the same day.

Ok for you @kewitz ?

If we do this, I think we can close this issue.
