### ISSUE TITLE
GitHub banner contributors.svg not working

### ISSUE THREAD

**Issue by wdanilo** [opencollective/opencollective#3956]
Hi, we were using GitHub contributors banner already, but recently we changed the organization name on GitHub. I updated the OpenCollective configs, but unfortunately, the banner never (after few days) went back to normal. Could I ask you for a little help with it, please? The current banner link is here: `https://opencollective.com/enso-language/contributors.svg?width=890`

**Comment by mgrachev** [comment]
My banner doesn't work too https://opencollective.com/dotenv-linter/contributors.svg?width=890
It doesn't update. I always see 44 contributors in my project, although their number has already exceeded 70.

**Comment by znarf** [comment]
I just released [contributors.svg](https://github.com/opencollective/contributors-svg) as a separate Open Source repository. Anyone is welcome to participate.

I also deployed a new version which should normally fix this old issue.

Feel free to open issues and PRs in the new repository!

**Comment by mgrachev** [comment]
@znarf Now it works! Thanks a lot 🔥
