### ISSUE TITLE
Guest user cannot pay for event ticket

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3957]
**Describe the bug**
When checking out as a guest, unable to click the "payment" button and proceed. This works fine as a logged in user.

**To Reproduce**

1. Be logged out
2. Go to this event: https://opencollective.com/an-entangling-wellington-13971425
3. Buy a ticket
4. Complete the details and profile steps
5. At the summary step, try to click Payment
6. Nothing happens and you can't proceed

**Comment by Betree** [comment]
Fix deployed
