### ISSUE TITLE
Empty Platform Tips Details in Recurring Contributions

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3958]
**How to reproduce:**

1) On https://opencollective.com/friends-of-the-earth-international/recurring-contributions

2) Check the recurring contribution and look at where platform tips are usually displayed.

<img width="312" alt="Screenshot 2021-02-09 at 09 47 40" src="https://user-images.githubusercontent.com/806/107338513-ea769280-6abb-11eb-9ca8-3bc433a7b13a.png">

**Problem**: Instead of nothing or actual platform tips details, you can see some weird looking empty values.

Order Id: 90045

**Comment by znarf** [comment]
@sbinlondon a small one if you have some time this week

**Comment by saideepesh000** [comment]
Hey @znarf @Betree @SudharakaP , should I remove these (--, --) here on [`FormattedMoneyAmount`](https://github.com/opencollective/opencollective-frontend/blob/2929233f7ce5bc8689fc75b7d416a9de822061fa/components/FormattedMoneyAmount.js#L33) and make it `0` or any text like `No Contribution`. I think this was made purposefully.

**Comment by Betree** [comment]
@saideepesh000 `FormattedMoneyAmount` is not the right component to update, it's doing its job by displaying `--,--`. We rather need to update this specific card:
- To display just the amount if there's no platform tip
- To make sure the platform tip value is properly displayed if there's one
