### ISSUE TITLE
Tax not included in total

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3959]
GST is being applied, but the total on the righthand side doesn't include it. The left side looks correct.

![Screen Shot 2021-02-09 at 2 20 36 PM](https://user-images.githubusercontent.com/5498878/107340138-47a52f00-6b22-11eb-9597-5fd416c7ea74.png)

**Comment by Betree** [comment]
Also fixed by https://github.com/opencollective/opencollective-frontend/pull/5867, root cause was the same
