### ISSUE TITLE
Deprecate TemporaryNotification in favor of toast notification

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3963]
`TemporaryNotification` was used before we added toast notifications to our design system. We should replaced all its occurences by toast notifications, and remove the component.

Usage:

```es6
const { addToast } = useToasts();

if (success) {
  addToast({ type: TOAST_TYPE.SUCCESS, message: intl.formatMessage(messages.SUCCESS) });
} else if (error) {
  addToast({ type: TOAST_TYPE.ERROR, message: i18nGraphqlException(intl, e) });
}
```

**Comment by Betree** [comment]
Partially addressed by https://github.com/opencollective/opencollective-frontend/pull/5875

**Comment by saideepesh000** [comment]
Hey @Betree, at present there's only one page which is using TemporaryNotification component and that's a class-based component, but useToast is a functional hook which can't be used inside a class component, now what should I do, should I just remove the TemporaryNotification from it or any other approach you suggest.

**Comment by Betree** [comment]
> Hey @Betree, at present there's only one page which is using TemporaryNotification component and that's a class-based component, but useToast is a functional hook which can't be used inside a class component, now what should I do, should I just remove the TemporaryNotification from it or any other approach you suggest.
> 
> Edit: I found something called HOC in react, should I use it, [SOF](https://stackoverflow.com/questions/64195655/how-to-call-hook-in-class-component-in-react-native)

Using a HOC sounds like the right way to go :slightly_smiling_face:

**Comment by Betree** [comment]
The latest instance of this `TemporaryNotification` is conflicting with the new navbar, we should iterate on it asap. @saideepesh000 let me know if you need any assistance with this, or if you prefer to pass it to someone else.

![Peek 2021-03-01 16-24](https://user-images.githubusercontent.com/1556356/109519557-a28bcf80-7aab-11eb-9149-1ff4628c5339.gif)

**Comment by saideepesh000** [comment]
> The latest instance of this `TemporaryNotification` is conflicting with the new navbar, we should iterate on it asap. @saideepesh000 let me know if you need any assistance with this, or if you prefer to pass it to someone else.
> 
> ![Peek 2021-03-01 16-24](https://user-images.githubusercontent.com/1556356/109519557-a28bcf80-7aab-11eb-9149-1ff4628c5339.gif)
> 

Oh, sorry for the delay, I may not be working on it now, you could pass it on.
