### ISSUE TITLE
Disable bank transfer

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3966]
## User story 
As a fiscal host admin, I want to be able to disconnect my bank account if we no longer want to accept bank transfer payments.

User request: https://opencollective.freshdesk.com/a/tickets/13118

## Best solution for this problem
A `disconnect` button for bank transfer, similar to the one for Stripe, which disables the bank transfer option for the host and its Collectives.

<img width="866" alt="Screen Shot 2021-02-11 at 2 54 19 PM" src="https://user-images.githubusercontent.com/5498878/107595313-286ce580-6c79-11eb-819d-dbebadf20a22.png">

**Comment by alanna** [comment]
Bump, users still request this

**Comment by SudharakaP** [comment]
If no objections, I'll be working on this one. We'll add a button next to `Edit bank details` to remove the bank details (with text "Remove Bank Details"). Once the user clicks on it there will be a confirmation modal with "Are you sure you want to remove the bank details for this host?"

@znarf: Let me know if this sounds reasonable.

**Comment by SudharakaP** [comment]
I've opened a PR for this one, I've put the button on the `Edit bank details` page initially but it didn't look quite good; maybe I was doing it wrong, but I couldn't find a good place to put this button there. Somehow to me it didn't quite feel right to put the delete button next to the save and cancel buttons of the edit form. 🤔 

Also I was thinking when the user clicks on `Edit bank details` button they might be thinking to edit the bank account not to really delete the existing one. Thus for now I've put the button next to the `Edit bank details` button. However if you have any alternative suggestions let me know and I'll quickly change it. 

cc: @znarf @opencollective/design

**Comment by znarf** [comment]
@SudharakaP thank you, that should do the job.
