### ISSUE TITLE
Read more on tier jumps to top of screen

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3969]
Here's a screencast: https://i.gyazo.com/1ed2e75238391c2a27865b99984cda6f.mp4

If you click `read more` on a tier description, it jumps you to the top of the screen. It should stay in the same place and just reveal the extra text.

**Comment by Betree** [comment]
It's happening with the two links in https://github.com/opencollective/opencollective-frontend/blob/d7fa2611e09c44635f243ba3b437cbd2fb5dc3a0/components/CollapsableText.js#L18. A `preventDefault` / `stopPropagation` on click might solve the issue.
