### ISSUE TITLE
Public message overflows off card in collective "About" section

### ISSUE THREAD

**Issue by patcon** [opencollective/opencollective#3974]
**Describe the bug**
A per-collective personal message from team members/contributors can be added to a card. The character limit for this card is 140. It renders fine in one place, but overflows under edges in another.

**To Reproduce**
1. Create a mock collective.
2. Add yourself as team member
3. On your collective page, clock your card to "add a personal message"
4. View the message in the team "About" section down below.

**Expected behavior**
Would expect that up to 140 character limit would render fine in all places its displayed.

**Screenshots**

#### Overflow in team About section
<img width="735" alt="Screen Shot 2021-02-14 at 5 04 27 PM" src="https://user-images.githubusercontent.com/305339/107890408-f8c31500-6ee6-11eb-80b0-c22501c40913.png">

#### Find in Contributors section
<img width="739" alt="Screen Shot 2021-02-14 at 5 06 08 PM" src="https://user-images.githubusercontent.com/305339/107890409-f95bab80-6ee6-11eb-9bb2-e7a693c3b614.png">

**Desktop (please complete the following information):**
 - OS: OSX Catalina 10.15.7
 - Browser Chrome
 - Version 88.0.4324.150 (Official Build) (x86_64)

**Additional context**
n/a

**Comment by Betree** [comment]
Thanks for reporting this issue @patcon! It should be resolved with the next deployment
