### ISSUE TITLE
Firefox development console flooded by CSS warnings

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3977]
Firefox console is flooded (it even becomes unresponsive at some point) by this CSS warning:

```
Unknown property ‘-moz-letter-spacing’.  Declaration dropped.
```
It looks like styled-components adds `-moz-letter-spacing`  (and matching prefixes for IE/Chrome), yet this property is [supported](https://caniuse.com/css-letter-spacing) since Firefox 2, we don't need a prefix there. This might be a bug in an upstream library (e.g. `styled-components`). 

We need to understand why this happens, and fix the issue (either in our code or in the library that we use).

**Comment by SudharakaP** [comment]
@Betree : Very curious as I use Firefox as my default browser for almost everything I do and I haven't noticed this warning at all. I can try to reproduce this but, which version of Firefox is this happening and is there any extensions present? 🤔

**Comment by Betree** [comment]
@SudharakaP I don't think it's specific to some specific extensions as I can reproduce in private mode. Version is 85.0.

You do need to enable the `CSS` filter in the console to see them though:
![image](https://user-images.githubusercontent.com/1556356/108324983-e12aab80-71c8-11eb-8b3d-6fca0c4ecece.png)

**Comment by SudharakaP** [comment]
@Betree : Thanks, you are right; I haven't enabled the CSS filter. 🤯 

Anyways, this seems to be coming from `styled-components` and the relevant issue is https://github.com/styled-components/styled-components/issues/3157. Not sure if we could fix it on our end as it seems that styled-components hasn't upgraded to stylis.js v4 which is the cause of the issue. 🤔

**Comment by Betree** [comment]
> @Betree : Thanks, you are right; I haven't enabled the CSS filter. exploding_head
> 
> Anyways, this seems to be coming from `styled-components` and the relevant issue is [styled-components/styled-components#3157](https://github.com/styled-components/styled-components/issues/3157). Not sure if we could fix it on our end as it seems that styled-components hasn't upgraded to stylis.js v4 which is the cause of the issue.

Nice finding! I missed this issue when I searched for one. Closing this then, as the issue needs to be resolved on their side.

**Comment by SudharakaP** [comment]
> > @Betree : Thanks, you are right; I haven't enabled the CSS filter. exploding_head
> > Anyways, this seems to be coming from `styled-components` and the relevant issue is [styled-components/styled-components#3157](https://github.com/styled-components/styled-components/issues/3157). Not sure if we could fix it on our end as it seems that styled-components hasn't upgraded to stylis.js v4 which is the cause of the issue.
> 
> Nice finding! I missed this issue when I searched for one. Closing this then, as the issue needs to be resolved on their side.

You are welcome 😸
