### ISSUE TITLE
Host organizations for WWCode

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#398]
Find the best host organization for this cities:

- Accra: Ghana (Ghanaian Cedi)
- Manila: Philippines (Philippine peso)
- Medillin: Colombia (Colombian peso)
- Merida: Mexico (Mexican peso)
- Monterrey: Mexico (Mexican peso)
- Shanghai: China (CNY)
- Singapore: Singapore (Singapore dollar)

**Comment by piamancini** [comment]
wait, that's not what I understood from the email. they want new hosts?

**Comment by nicobarretoOC** [comment]
Hmm true, I think you are correct. I thought she wanted a list of host organizations for each country so they could use them. Maybe we can talk about this in the next team meeting. 

From her last email:

" I was just inquiring about a possible list to use on our end to compare against the list I've made internally to remind myself when adding funds to a network to adjust the currency when appropriate.  "
