### ISSUE TITLE
Add funds to an Event after it's over

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3982]
## User story 
As an Event organizer, I want to be able to still accept contributions to an Event after it's over, so that I can pay outstanding expenses and fix budget issues.

This is coming up because there's an [outstanding expense](https://opencollective.com/sustain-2020-5874aeeb/expenses/30735) on an Event we need to pay, but the Event no longer has funds in it. I can't work out how to send money to the Event from the main Collective. I assumed contributing through the generic donation option would work but it seems to be disabled.

## Best solution for this problem
After the Event end date, still make it possible to enable contributions.

**Comment by Betree** [comment]
We still want to prevent people from contributing after an event is over. My suggestion would be to display the contribution flow **only** to admins, with eventually a message like:
> This event is over and it is no longer possible to contribute to it. As an administrator, you can still access this page to add funds to the collective if necessary.

I would also not display the tiers on the profile page, but rather an action button in the navbar.

As an alternative, "Add funds" also seems like a good way to solve this issue:
- Display a `Add funds from Collective` action in the Navbar
- When clicked, show a modified version of the Add funds modal:
  - Hide `Host fee` / `Platform fee`
  - Force parent Collective to be the `Source`
  - Hide the message `You will set aside $-- in your bank account...`

**Comment by alanna** [comment]
Those solutions sound good @Betree

**Comment by SudharakaP** [comment]
@Betree : If no objections, I will take this up, I am thinking of progressing with the second approach you suggested with the modified version of the `Add Funds` modal. 😃

**Comment by znarf** [comment]
I have some concerns about this feature. Let's not deploy it or put it behind a feature flag, deactivated by default.

**Comment by znarf** [comment]
The concern:
- only Host admins can use "Add Funds" currently, so the feature is generally broken in this state
- it make sense, Collective admins don't have the right to arbitrarily move money like this, we should be extremely cautious
- we should absolutely check the balance before creating Transactions between parent and child

It's not a quick issue and there should be clear specs before continuing the work.

**Comment by SudharakaP** [comment]
@znarf : Thanks for the information. I've added the feature flag `ADD_FUNDS_FROM_COLLECTIVE` in https://github.com/opencollective/opencollective-frontend/pull/6765

**Comment by alanna** [comment]
I didn't think this would be done like `add funds` where it can create new money in the ledger. I thought it would be as a contribution, where one Collective is debited and one is credited. The same way we can current add money from parent to Project.

**Comment by Betree** [comment]
@SudharakaP Without touching the API, a possible solution would be to rather use the `createOrder` mutation. This one will take care of checking the permissions and the balance properly.

**Comment by SudharakaP** [comment]
> @SudharakaP Without touching the API, a possible solution would be to rather use the `createOrder` mutation. This one will take care of checking the permissions and the balance properly.

@Betree : Thanks for the idea. So just to clarify when the `Add funds to Collective` button in the actions menu is clicked the `Add funds` modal will open but when they submit the modal we use the `createOrder` mutation instead? Is my understanding correct? 🙂

**Comment by Betree** [comment]
@SudharakaP Regarding the behavior, yes. Regarding the implementation, I wonder if the `Add funds` modal is the best place for this since the use case is quite different. Maybe you should copy-paste the code needed to a new `MoveBudgetToAccountModal` or `AddFundsFromParentModal`.

**Comment by SudharakaP** [comment]
@Betree : Surely. Thanks for the information. Let me work on that. 🤔

**Comment by SudharakaP** [comment]
@Betree : I've done the refactoring; one thing to note is that I wasn't exactly sure how to handle the payment method field required by the `createOrder` mutation. My thinking was to use the same way that we do in [add funds by using the host payment method](https://github.com/opencollective/opencollective-api/blob/673ef818ebe3cc1d63bb9c976898db13b05b7f86/server/graphql/v1/mutations/orders.js#L907-L908). Let me know if everything looks good. 🤔

**Comment by znarf** [comment]
The host payment method is absolutely not the right one. service:opencollective/type:collective from the contributor is the right one.
