### ISSUE TITLE
[PROJECT] Recurring contributions with PayPal

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3986]
## Purpose
Supporting PayPal is a very frequent user request (https://github.com/opencollective/opencollective/issues/1141 #1362 #3267 #1655), and the numbers show that contributors are looking for that too: we got +350% **one-time** contributions with PayPal in 2020 compared to 2019 VS +200% for Stripe.

## Owner
@Betree (at least for the experimentation phase)

**Secondary Developer on project:** @kewitz 

## Prioritization

<details>
<summary>Details</summary>

- Does this serve our mission?

:heavy_check_mark: It helps collective reach new contributors (who are afraid of putting their CC number on a random website)
:heavy_check_mark: It helps us to get new collectives, for whom supporting PayPal is a requirement

- Will this help to make us financially sustainable within a year?

Yes (more contributors + more collectives = :rocket:)

- Is it feasible to build and maintain with our team and runway?

The complexity is still difficult to estimate (see below) but it definitely sounds feasible to implement. We already need to support the legacy PayPal integration, so it shouldn't add too much maintenance.

- Can this make us move faster?

No

- Does this increase quality and not technical debt?

Revamping the existing PayPal implementation could indeed increase the quality of the code.

- Will this bring us more Collective and financial contributors?

Yes

- Is this already solved elsewhere or is it our unique contribution?

Most crowdfunding platforms already support this, it's actually a feature lacking to Open Collective

</details>

## Roadmap & Timeframe
(Key milestones or phases and estimated delivery dates, including specs, design, feature development, feedback, marketing/comms, and documentation)

**Kick-off meeting**: https://docs.google.com/document/d/1v1ypAd9D9PCUgjBqbjwRgq0tS4tqyt3MlS_9CzrMTcY/edit#heading=h.kfc9ucrditbu
**Github Project**: : https://github.com/opencollective/opencollective/projects/52

There will be two phases for this project:
1. **Experimentation** (2 weeks - ETA 1st March)
We're still not decided about whether we want to use Braintree or PayPal subscriptions. We need to experiment & research more before making a decision.

2.  **Implementation** (ETA to be defined)
The implementation cost will depend on the chosen solution. A rough approximation would be between 1 and 2 months.

## Technical research

PayPal offers two APIs for handling recurring payments:
1. Subscriptions: they manage everything
2. Braintree: their latest recommendation, Stripe-like service
3. Billing agreements: user approves a billing contract, then it’s your responsibility to call PayPal’s API when it’s time to charge.

Though it sounded like the most natural option to match what we do with Stripe, (3) has been rejected because it's deprecated and access to this API is [restricted](https://developer.paypal.com/docs/api/payments.billing-agreements/v1), which would limit the adoption for new hosts in the future.

We're left with the two following options:

**Braintree**
  - (+) Recommended by PayPal
  - (+) Would bring support for Venmo, Apple Pay, and other Payment providers out of the box
  - (-) Need a Braintree token, so we need a place to input that and a migration path for hosts with Paypal activated
  - (?) How are recurring payments managed? (plans?)

**PayPal subscriptions** 
  - (+) Up-to-date PayPal API
  - (+) Can re-use your existing PayPal account
  - (-) It’s unclear if collectives would be able to move their subscriptions when changing host
  - (-) Higher implementation cost (though we can have MVPs to simplify)
  - (?) API requires the use of fixed plans that need to be created before the contribution. That might be tedious to achieve with our model where most tiers have flexible pricing, though there does not seem to be a limit to the number of plans you can create, so we could just create one plan for each order). Creating one plan per collective might be enough. (needs some more investigation)

**⚠️ Known limitations with both of these approaches**
- Can’t move recurring contributions from one host to another (that needs to be documented properly)
- Can’t batch recurring contributions

## Success metrics
- Volume
- How much is moving from Stripe to PayPal?

**Comment by Betree** [comment]
So far the Braintree experiment is going well, no blocker has been identified so far. We now have enough information to confirm that we can implement PayPal recurring either with Braintree or directly with PayPal's API. It's worth having a quick chat about that to decide which one we want to use.

So far the pros and cons are:

<table>
<tr>
	<td>
	<td>Pros
	<td>Cons
<tr>
	<td>PayPal
	<td>
- Slightly simpler to implement <br>
- Simpler to setup & manage (most hosts already have a PayPal account linked)
	<td>
<tr>
	<td>Braintree
	<td> 
- Provides a skeleton to implement other payment method providers (PayPal, Venmo, Google Pay, Apple Pay) more easily. For some of them (Venmo, Google Pay) it's a no-brainer, can be done in 2 clicks. 
	<td>
- More complex to setup <br>
- More complex to manage (have to deal with two accounts: PayPal + Braintree)
</table>

---

Whatever we decide (Braintree or PayPal), here are the next steps on this project (**MVP phase**):
- Clean MVP implementation
  - Store Host's Braintree credentials in a connected account
  - Store contributor's `customerId`
  - Add webhook to record the transaction when subscriptions run
- Improve the UI/UX (but keep using the generic drop-in Braintree component for now because it simplifies the implementation)
- Start a very limited test with two hosts: one in Europe and one in the US (because PayPal APIs availability depends on the country). Only the internal team should be able to test & use the Braintree integration at this stage.

Once all these steps have been validated, we can move to the **Beta phase**:
- Add some documentation (general info, setup guide)
- Add all the other important webhooks (subscription canceled, updated, etc.), consolidate the code & tests
- Add a page to connect your Braintree account
- Test with more hosts/users

Once we're good with this, we can move to the public release for everyone. We'll probably want to follow up with:
- Add metrics
- Improve the UX
- (Braintree bonus) activate other payment method providers (with the ability to toggle them from the host admin)

**Comment by Betree** [comment]
**Project update**

This project is a bit behind schedule because we took the decision to get away from the [Braintree implementation](https://github.com/opencollective/opencollective-api/pull/5392) despite the fact that it was mostly ready. The main reason behind this change was the process to go live that ended up being super-complex; there were a lot of legal documents that hosts needed to submit and manual procedures that required them to contact Braintree and do a large part of the setup manually. While Braintree did appear like a nice solution to support more than just PayPal, we didn't want to force hosts to go through this painful process just to start accepting recurring contributions with PayPal, especially since most of them already have a PayPal account linked.

The latest implementation relies solely on PayPal's latest subscription API and is compatible with existing linked PayPal accounts. The only thing required from hosts is to enable some more webhook events in PayPal's settings (though we may be able to automatize that and deploy the update silently for everyone #4096).

We now have a working MVP in production that is ready to be taken to the next step :tada:

**Timeline**
- Add the missing important webhooks (subscription canceled, updated, etc.), consolidate the code & tests
- Update `/:user/recurring-contributions` to support using PayPal from there
- Clarify the UI regarding subscription dates (or update the charge dates to match what we do with Stripe)
- Improve a bit the UI in the contribution flow (submitting state)
- Deactivate subscriptions when deactivating the collective
- Prevent changing currency if there are active PayPal plans
=> Start beta testing with a few collectives under a host we control

Once we're good with this, we can move to the public release for everyone. We'll want to follow up with:
- Add some documentation (general info, setup guide)
- Add method to refund PayPal transactions from the frontend (https://github.com/opencollective/opencollective/issues/1656)
- Add metrics

**Comment by TLWebdesign** [comment]
Thats good news! Thanks for the update 😄

**Comment by Betree** [comment]
This project is now completed, we have progressively enabled the new PayPal integration (that supports subscriptions) for Open Source Collective and Foundation during the past two weeks and just triggered the change to enable the feature for all hosts that have a PayPal account connected.

The next step for this project is https://github.com/opencollective/opencollective/issues/4210, fiscal hosts currently need to contact support to enable PayPal. We would want to streamline that process, especially since this new integration now enables both PayPal payments and PayPal payouts with the same account.

**Comment by BenJam** [comment]
congrats! Can i help follow up on marketing, pr, docs or feedback?

**Comment by Betree** [comment]
@BenJam related docs have normally been updated in sync with the project release. Since, in practice, it's a small change for hosts (they already supported PayPal for one-time) donations, I don't think we need to really seek feedback for this one (apart from eventual bug reports).

I however see some topics for marketing:
- Announcing to hosts that already support PayPal: should be covered by the next newsletter
- Announcing to hosts that do not support PayPal yet: next newsletter should help, I've reached OC Paris to share it with them. We may want to encourage other large hosts to connect their PayPal too (esp. the ones in Europe where PayPal is widely used).
- Some initiatives may have turned their backs to Open Collective in the past because it did not support PayPal payments fully. I'm not sure where (marketing pages? twitter?), but we may want to surface the fact that we now have full integration. 

https://github.com/opencollective/opencollective/issues/4210 is to consider when making announcements.
