### ISSUE TITLE
Change tax form collection interval to 3 years by the submission month

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3991]
After speaking with the accountants about whether we need to collect a new tax form from each payee each year, it seems we don't, but it's a good idea to touch base regularly in case someone's tax info needs to be updated. We are also seeking ways to reduce the number of forms going out to stay under our quota with helloworks, and to spread it out so they don't all get triggered at once in January.

I propose:
1. we move the interval from 1 year to 3 years before requesting a new form.
2. we request the new form in the same month they originally submitted their old form, e.g. if they submit it in May 2021, we ask again in May 2024.

**Comment by alanna** [comment]
If we do this, I think we should spread people out throughout the year who are now on the january schedule, because we have a big spike of people who've been shifted to that date cycle.

**Comment by Betree** [comment]
Nice! This sounds like a really simple way to improve the situation. Thanks for researching this @alanna!
