### ISSUE TITLE
Accept financial contributions: responsiveness issue on medium screens

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#3995]
With ~950px width:

![Peek 2021-02-18 16-55](https://user-images.githubusercontent.com/1556356/108383616-39ce6880-720a-11eb-91a2-46110bf6ef82.gif)

**Comment by ericyoungson** [comment]
@Betree I'm interested in taking this on.

**Comment by ericyoungson** [comment]
I think I have an old phone that is < 950px. Could you send me a link to that page--I'm still learning the site, just want to make sure I have the right page.

Thx!

**Comment by SudharakaP** [comment]
> I think I have an old phone that is < 950px. Could you send me a link to that page--I'm still learning the site, just want to make sure I have the right page.
> 
> Thx!

@ericyoungson : Here's the link to the page in our staging environment; https://staging.opencollective.com/test/accept-financial-contributions/host

Also you don't need a phone necessarily to see this; you can use dev tools of any major browser (such as Chrome, Firefox, Safari) to mimic a mobile device. For example I use Firefox and here's how you do it. 😄 

![Uploading Peek 2021-03-31 21-14.gif…]()

The behavior is noticeable for screen-size of approximately ~950px width; not necessarily for mobile devices as you can see from the above screen-cast. You can try this out yourself in the browser with different responsive screen sizes and mobile devices to see how it behaves. Let us know if you have any questions. 😄

**Comment by ericyoungson** [comment]
Ah, of course! Thx.

**Comment by ericyoungson** [comment]
Ok @Betree , I believe I've resolved the issue but I'm unable to push my branch to the repo. I decided to take the easy rout this time. I'm calling the branch, `accept_financial_contributions_responsiveness`.

Please advice on how to proceed

Thx

Eric

**Comment by SudharakaP** [comment]
> Ok @Betree , I believe I've resolved the issue but I'm unable to push my branch to the repo. I decided to take the easy rout this time. I'm calling the branch, `accept_financial_contributions_responsiveness`.
> 
> Please advice on how to proceed
> 
> Thx
> 
> Eric

@ericyoungson : Thanks for taking the time for this. Could you let us know what error you are getting when you are trying to push the branch? 😄

**Comment by ericyoungson** [comment]
`remote: Permission to opencollective/opencollective-frontend.git denied to ericyoungson.`
`ERROR: Permission to opencollective/opencollective.git denied to ericyoungson`

with HTTPS and SSH, respectively

**Comment by snitin315** [comment]
It seems you are not a member of @opencollective/contributors yet.

**Comment by ericyoungson** [comment]
How do I become a member?

**Comment by snitin315** [comment]
Someone from @opencollective/core can send you an invite. 
Until then you can use your fork to send a PR.

**Comment by SudharakaP** [comment]
@ericyoungson : Hi, I've added you to the @opencollective/contributors. Now you should be able directly create branches in the repo and push. 😄
