### ISSUE TITLE
Budget page design for Collectives (Transparency)

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#3998]
We designed a page to display the money management's transparency layer, so Collectives and other projects can show their contributors and team the budget overview.

It displays a handful of data visualizations ranging from 2 main concepts: transactions and expenses overview.

In the end, we included a shortlist of the latest transactions and expenses.

| Desktop | Tablet Portrait | Tablet Landscape | Mobile |
|---------|-----------------|------------------|--------|
|  ![Desktop](https://user-images.githubusercontent.com/49539954/108448041-993a7180-7226-11eb-8468-fc0fd8aba0b2.png)   |    ![Tablet Portrait](https://user-images.githubusercontent.com/49539954/108448039-98a1db00-7226-11eb-9dc4-7b0e65411259.png)     |   ![Tablet Landscape](https://user-images.githubusercontent.com/49539954/108448040-993a7180-7226-11eb-8750-c328f090e009.png)    |  ![Mobile](https://user-images.githubusercontent.com/49539954/108448036-9770ae00-7226-11eb-93e4-faacd2fe5f6b.png)   |

Production-ready file in [Figma →](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=10158%3A0)

**Comment by Betree** [comment]
This graph can be rendered without any library (these are just boxes with a width defined as a percentage and background colors):
![image](https://user-images.githubusercontent.com/1556356/108476816-c58bd780-7292-11eb-8e88-efadb5bcefd1.png)

We may however want to use something for these 3 ones:
![image](https://user-images.githubusercontent.com/1556356/108476982-f3711c00-7292-11eb-8c40-536431176298.png)

We discussed this a few months ago with @Memo-Es and identified three candidates that served as a basis for what was possible:
- https://www.chartjs.org
- https://apexcharts.com
- https://visjs.org

**Comment by alanna** [comment]
This looks really good!

One thing I'd love to see that seems to be missing is balance over time.
