### ISSUE TITLE
userLayoutEffect Warning on Dev Console

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#3999]
**Describe the bug**

I've noticed that the following warning is printed over and over again while navigating pages in the developer console in Firefox. It would be nice to remove this warning and fix the underlying issue. 

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
    in l
    in l (at collective-page.js:182)
    in main
    in Body__Main (at Body.js:16)
    in Body (at Page.js:45)
    in Fragment (at Page.js:33)
    in Page (at UserProvider.js:147)
    in Context.Consumer (at UserProvider.js:147)
    in WithUser (at collective-page.js:181)
    in CollectivePage
    in Query
    in Apollo(CollectivePage) (at UserProvider.js:147)
    in Context.Consumer (at UserProvider.js:147)
    in WithUser (at _app.js:136)
    in Context.Provider (at ToastProvider.js:50)
    in ToastProvider (at _app.js:135)
    in Context.Provider (at UserProvider.js:135)
    in UserProvider (at withLoggedInUser.js:169)
    in withLoggedInUser(undefined)
    in Context.Consumer
    in ApolloConsumer
    in withApollo(withLoggedInUser(undefined)) (at
```

**To Reproduce**
1. Run the front-end server in development mode (`npm run dev`)
2. Open the developer console in any browser (I've used Firefox for this). 
3. Navigate between pages and notice the warning.

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version 85.0.1 (64-bit)

**Comment by Betree** [comment]
This one seems to come from `styled-components`'s `createGlobalStyle`: https://github.com/styled-components/styled-components/issues/3369

**Comment by SudharakaP** [comment]
@Betree : Yes, seems we will have to wait until `styled-components` fix it on their side. So I'll be closing this for now. 🤔
