### ISSUE TITLE
#feature Posts / newsletter

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#4]
It's important to communicate to the different members of a collective.
To that end, we should make it easy to send an email update and target specifically certain tiers (e.g. an update for backers, an update for sponsors). 

Since a collective is a collaborative space, any member should be able to submit an update (aka a post). For example to do a summary of the latest meetup, share pictures/videos, etc.

To avoid spam, an admin of the collective should approve the post for it to be sent out by email to the targeted audience.

**Comment by piamancini** [comment]
That's key to create network effect. I remember someone mentioned that
kickstarter did this, backers were contacted through them.
Also, to avoid spam, backers/sponsors should be able to easily opt out

P.
piamancini.com
t: @piamancini
s: piamancini
OpenCollective <https://opencollective.com>

**Comment by xdamman** [comment]
v1:

a new page `/:slug/posts/new` for logged in admins of the collective (core contributors) where they can post a text in markdown and specify which tier they should send it to (with a flag to make it publicly available on the page of their collective).

v2:

a mail server (using Mailgun?), where anyone can send an email to `:tier@:slug.opencollective.com` (e.g. `backers@mochajs.opencollective.com`). The email is first sent to the admins of the collective for review and approval. Once approved, it is sent to all the members of the tier (e.g. all backers).

**Comment by piamancini** [comment]
mail server done to backers set up.
