### ISSUE TITLE
Pay with PayPal bug

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#40]
On a meetup with a host without stripe but with PayPal, when clicking on "Pay With PayPal", it triggers a slack notification before the donation actually went through.

That said, it doesn't seem to record the donation in the DB, so it doesn't look like an urgent bug as I initially thought.

**Comment by piamancini** [comment]
Is this fixed in the new flow @sedubois @asood123 ?

**Comment by sedubois** [comment]
This should be fixed by https://github.com/OpenCollective/opencollective-api/pull/321 which was merged, although hasn't been fully tested yet.
