### ISSUE TITLE
Zero balance not working

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4000]
I am trying to archive https://opencollective.com/cannon-coin

I go to settings > advanced and click `send balance to host`. It says processing, then just nothing happens and I can't zero the balance.

https://user-images.githubusercontent.com/5498878/108642865-91bbe680-750c-11eb-98cf-4fedc68b5dc4.mp4

**Comment by znarf** [comment]
It seems the Collective how has a balance of zero and was archived. Difficult to troubleshoot now that the problem was solved/fixed. Closing.

**Comment by alanna** [comment]
I had to submit an expense to zero the balance as a workaround. When a customer is waiting it's not always possible to leave a broken state for investigation.
