### ISSUE TITLE
Ghost Collective preventing host deactivation

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4001]
I am trying to deactivate https://opencollective.com/the-wellbeing-protocol/ as a host.

I archived its only Collective and the dashboard shows no Collectives.

<img width="1215" alt="Screen Shot 2021-02-22 at 1 09 15 PM" src="https://user-images.githubusercontent.com/5498878/108643422-6e466b00-750f-11eb-8c86-33ce966c9d01.png">

However, it says there is a Collective still, and I can't deactivate.

<img width="1133" alt="Screen Shot 2021-02-22 at 1 09 57 PM" src="https://user-images.githubusercontent.com/5498878/108643437-7a322d00-750f-11eb-9d66-9207dfa9cf42.png">

**Comment by alanna** [comment]
Aha! I found https://opencollective.com/cannon-coin2 and deleted it, and now the host is able to deactivate. This Collectives seems to have been previously hosted by this host, but then was removed. When I deleted it, it had no host. So why would it be blocking host deactivation?

**Comment by znarf** [comment]
Sorry, difficult to investigate now that things are fixed/solved. Closing.
