### ISSUE TITLE
Payment Method: Network Error

### ISSUE THREAD

**Issue by awright** [opencollective/opencollective#4005]
**Describe the bug**
Sent in from the [Salesforce](https://opencollective.com/salesforce/) – when trying to send over $10,000 to [Prettier](https://opencollective.com/prettier) they keep getting a network error on the payment page.

**Screenshots**
![Screen Shot 2021-02-22 at 10 07 11 AM(1)](https://user-images.githubusercontent.com/78410/108794016-d4e07e80-7539-11eb-98e5-91671f554f38.png)

**Comment by znarf** [comment]
This is fixed, they can now contribute with the Fund's balance.
