### ISSUE TITLE
Is the open collective bot member check case sensitive?

### ISSUE THREAD

**Issue by nhirschey** [opencollective/opencollective#4006]
**Describe the bug**
The bot never finds me when I create an issue at a backed GitHub repo (see https://github.com/ionide/ionide-vscode-fsharp/issues/1500) . Is the member check case sensitive? I had Nhirschey as my GitHub name on opencollective, rather than nhirschey. Could this be the reason backer.ts doesn’t fine me? It looks like it’s possible that this is the issue when I look at that code file. I am in the ionide member slug that the bot checks, I’ve checked that. 

FYI I just changed my name on opencollective profile to nhirschey to see if it fixes it next time.

**Comment by znarf** [comment]
I'm sorry, we're not investing much in the bot right now and it's likely gonna be deprecated in the future.

It's possible indeed that it's case sensitive. We would need to double check. Source code is here: https://github.com/opencollective/opencollective-bot

**Comment by znarf** [comment]
Open Collective bot is discontinued.
