### ISSUE TITLE
Blog post pages doesn't have the post title in the <title> element

### ISSUE THREAD

**Issue by robnyman** [opencollective/opencollective#4013]
**Describe the bug**
Blog post pages doesn't have the post title in the <title> element

**To Reproduce**
1. Go to https://opencollective.com/open-web-docs/updates/introducing-open-web-docs
2. Title element is <title>Open Web Docs - Open Collective</title>

**Expected behavior**
Expected title element to be <title>[title of the blog post] - Open Web Docs - Open Collective</title>.
E.g. <title>Introducing Open Web Docs - Open Web Docs - Open Collective</title>.

**Comment by saideepesh000** [comment]
Ya, it's using <h5> tag.
