### ISSUE TITLE
Add a confirmation modal before publishing an update

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4016]
*Feature request from @Relequestual*

**User story**
> I accidentally pressed "publish" on a draft I was still working on yesterday -_-
> Could I raise a feature request of a confirmation dialogue to publish a draft please? =]

That's a simple enhancement. It would be good to show the notification audience in there ("Your Update will be sent to x financial contributors").

**Related code**
- `components/PublishUpdateBtnWithData.js`
- `components/ConfirmationModal.js`

**Comment by Relequestual** [comment]
Super!
Does this also apply if it comes from the action menu? (iirc this issue was because I missed with my mouse intending to pick a different option from the menu)

**Comment by Betree** [comment]
@Relequestual It's only when you click "Publish". We will surface the notification audience in the modal (https://github.com/opencollective/opencollective/issues/4064) to make sure folks have a chance to review it in case they picked the wrong value in the select.

![Peek 2021-03-05 09-34](https://user-images.githubusercontent.com/1556356/110089174-0f49e700-7d96-11eb-99e5-7b9a14731854.gif)
