### ISSUE TITLE
Unable to approve event email

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4017]
The admin of [this event](https://opencollective.com/an-entangling-wellington-13971425) wanted to send an email to participants. She drafted it and got the preview. But when she clicked `approve` in the email, she got this error.

<img width="763" alt="Screenshot 2021-02-24 at 8 51 10 PM" src="https://user-images.githubusercontent.com/5498878/109070913-fae36a00-7757-11eb-9f04-24abc38bcd72.png">

![Screen Shot 2021-02-25 at 10 55 56 AM](https://user-images.githubusercontent.com/5498878/109071078-2a927200-7758-11eb-920e-216d8280e19d.png)

**Comment by Betree** [comment]
@alanna could you forward me the email (or share the "Approve" link by pm)? We can probably have a fix for that one
