### ISSUE TITLE
Incorrect hostCurrencyFxRate and amountInHostCurrency with some PayPal expenses

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4021]
When paying an Expense with PayPal, we're reading the `hostCurrencyFxRate` from PayPal response but it's sometimes inaccurate to do so. It's especially visible for Transactions that have `currency = hostCurrency`.

https://github.com/opencollective/opencollective-api/blob/master/server/lib/transactions.js#L117

```
SELECT * FROM "Transactions"
WHERE "deletedAt" IS NULL
AND "ExpenseId" IS NOT NULL
AND "currency" = "hostCurrency"
AND "hostCurrencyFxRate" != 1;
```

We should review this and fix past entries in the ledger.

**Comment by kewitz** [comment]
@znarf
This bug happened only once in 2021 and twice in 2020.
It affects only Adaptive Payments, which PayPal deprecated and continues to provide support to existing integrations only.

I suggest deprecating adaptive payments on our side as well and enabling PayPal Payouts for everyone:
https://github.com/opencollective/opencollective/issues/4210

**Comment by znarf** [comment]
Ok, I think it might be slightly misleading to look at the data as it is today, because I fixed many impacted transactions.

But if it doesn't happen anymore, that's good to know and we don't have to look at a fix I guess.
