### ISSUE TITLE
Updates have really weird word wrapping

### ISSUE THREAD

**Issue by Relequestual** [opencollective/opencollective#4028]
**Describe the bug**
I posted an update. The word wrapping is wrong, and words are broken to wrap.

**To Reproduce**
See at https://opencollective.com/json-schema/updates/json-schema-2020-12-released

**Expected behavior**
Words should not be broken

**Screenshots**
![Screenshot 2021-02-27 104916](https://user-images.githubusercontent.com/731158/109385135-7e809080-78e9-11eb-9d83-cd406b2790a4.png)

**Desktop (please complete the following information):**
 - OS: Windows, macOS, iOS (at least
 - Browser Seems applicable to all browsers. It's in the CSS.
 - Version FF 86.0 (at least)

**Smartphone (please complete the following information):**
Not sure this is applicable as it's a CSS issue

**Additional context**

I have also noticed this problem with buymeacoffee.com.
I would guess some underlying tooling you both use has been updated and this change has gone unnoticed, or it's just a coincidence.

Please mention me on the OC slack if you need more info. I don't check GitHub notifications.

**Comment by rhklee** [comment]
It also seems strange that only this update post has wrap formatting issues, the other update post seem to be fine.

**Comment by Relequestual** [comment]
> It also seems strange that only this update post has wrap formatting issues, the other update post seems to be fine.

Well, that is really weird...

I can see that it only appears to be on that update and not my previous updates.

I have just copied it into a plain text editor, then pasted it back again, and it seems to have fixed the issue.

It's still concerning though, as I shouldn't be able to effect that sort of behaviour.

I don't know if you keep change logs, hopefully you can have a look for the edits I've made a few moments ago, and see what the change looks like. The editor doesn't give me access to raw HTML sadly =[
