### ISSUE TITLE
Invoice for Creative Code SRL & Contact info from Vue.js

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#403]
**Email from Alex from Creative Tim:**

> "Hi guys,
> 
> We just did our first contribution (https://opencollective.com/vuejs#contributors). Can you please give us an invoice including this details:
> 
> CREATIVE CODE SRL...*
> 
> **Also can you please give us the details of somebody from vue.js so we can see what we need to do in order to get our logo appear on their website?"**

*The invoice details are in the original email

**Comment by piamancini** [comment]
this is done.
