### ISSUE TITLE
Allow admin to add funds to specific tier

### ISSUE THREAD

**Issue by visika** [opencollective/opencollective#4036]
## User story 
_As admin, I can add funds so that the balance of a specific tier increases, useful to track objectives_

At the moment, the route I found is to log out and add a contribution as a guest, but I have to input a new email every time.

## Best solution for this problem
_Add an optional field Destination Tier to select the preferred tier_

## MVP
_Adding funds with the Destination Tier field makes an objective progress in that Tier increase_

**Comment by Betree** [comment]
Hi @visika, I think a proposal already exists for that: https://github.com/opencollective/opencollective/issues/4009

Feel free to re-open the issue (or comment on the other one) if it does not match your use case.

**Comment by visika** [comment]
Yes, it is a duplicate indeed :) I don't know why I couldn't find it before!
