### ISSUE TITLE
[Roadmap] Q1S2

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#4041]
### Virtual Cards 

We would like to prototype how we could give Cards to Collectives to spend their budget. We’re considering using the Privacy API because we’re already using the service internally and it seems possible to automatize. Some challenges are:
issuing credit cards from our API, and our interface retrieve the list of transactions from Privacy to invite collective admins to fill expenses, because we need their paperwork enforcing limits based on the collective budget

**Engineers**: @kewitz + @znarf 
**Kick Off Notes**: [Google Doc](https://docs.google.com/document/d/1StuDqnFVFmJTDfDFdMfOp4pHYsarazb2VHCAS2F4NsU/edit#heading=h.vgm2op90bonx)
**Project board**: [Board] (https://github.com/opencollective/opencollective/projects/49)
Status: 
Implemented features needed for project. 
Ready for internal use
Design: Done
Pending: 
User interface to create, apply for and manage cards. 
External Test

### PayPal Recurring
PayPal is not handled for recurring contributions and that is frustrating people and preventing some to contribute. We anticipate it will be more complex and different from our Stripe setup but we still want it. We would like to see how a basic implementation looks like and identify blockers.

**Engineers**: @Betree + @kewitz 
**Kick Off Notes**: [Doc](https://docs.google.com/document/d/1v1ypAd9D9PCUgjBqbjwRgq0tS4tqyt3MlS_9CzrMTcY/edit)
**Project board**: [Board](https://github.com/opencollective/opencollective/projects/52)
**Project issue**: https://github.com/opencollective/opencollective/issues/3986

Status: 
Feature ready for public release but still want to deploy improvements in the interface (like subscriptions page)
Ready for Beta Test. 
Next Steps: Beta Test & iterate

### Embed Contribution Flow
**Engineers**: @Betree 
Currently in beta-testing 
Bug fixes as needed based on feedback. 
Status: ongoing 
Need to onboard more collectives
Next steps: document, release it and close it. 
Close project. 

### Open Stocks
Engineers: @znarf 
Project Owner @piamancini 
Deliverable: website with a checkout flow for stock donations for OSC
Status: in development

### Expense Spam button
Engineer @znarf 
Project Owner: @piamancini @alanna 
Deliverable: user facing flag to mark an expense as spam
Status: Done 
Pending: documentation 

### Whitelabeling
SCA apply flow project
**Project issue**: https://github.com/opencollective/opencollective/issues/3988
**Design**: done
**Engineer**: @znarf + contributor 
**Deliverable**: Pricing & proposal 
**Project Owner**: @piamancini 
Status: Done
Pending: Follow up on reply. 

### Updates
1 day: fixing issues on Updates 
Engineer @Betree 
Done

### Fiscal Sponsorship Static Page 
**Design:** @Memo-Es 
**Owner**: @piamancini 
**Project issue**: https://github.com/opencollective/opencollective/issues/4118
Status: Design and Content done 
Pending: Illustrations 

### Accessibility issues 
**Design**: @Memo-Es 
**Project issue**: https://github.com/opencollective/opencollective/issues/4045
Status: In implementation
Pending: global navigation + standards documentation

### Changelog page
**Design**: @Memo-Es 
**Dev Support:** @znarf 
Status: scoped, but delayed because of Virtual Cards.  

### Dev Website 
Goal: review good dev websites for proposal
**Design**: @Memo-Es 
**Dev support**: @znarf 
Status: Pending

**Comment by alanna** [comment]
This looks good! Do we also want to carve out some time for the team to squash a bunch of small bugs and issues? Such as a three day sprint or something.

I notice many of these do not have their own project issues. I think the project issue template has been working well for us and we should stick with it, and link the project issues here.

**Comment by piamancini** [comment]
Review Document: https://docs.google.com/document/d/1mFArzqaMeAY68G4dXpgoLScaM7zMfzuid9k8EwFI2eU/edit#
