### ISSUE TITLE
Incorrect currency sign in goals

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4042]
When looking at goals set in a currency different than dollar, there is a wrong $ currency sign displayed.

<img width="1333" alt="Screenshot 2021-03-02 at 17 52 55" src="https://user-images.githubusercontent.com/806/109684152-48a90980-7b80-11eb-9271-a74188030569.png">

https://opencollective.com/piratpartiet

**Comment by Betree** [comment]
It seems that we got rid of currency for `FormattedMoneyAmount` in https://github.com/opencollective/opencollective-frontend/pull/5741/files#diff-17573fe68a5c3799afd3a2ff1583b06309c238b21d70975a5538b0a0bcc2d9acL98, we should add that back
