### ISSUE TITLE
Remove the Host Plan selection settings

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4056]
Right now this is how it looks:

![Our Host Plan](https://user-images.githubusercontent.com/5498878/109874075-82d6f000-7cd3-11eb-88d8-79ac7f9d34fd.png)

This is a lot of unneeded complexity and it is confusing for users.

* If a host that used to be on the old pricing switches, they no longer need to see the deprecated old plan info
* There is no difference between the Start plan and the Grow plan and we don't need separate selections for them. If their host fee is set to 0% it functions as the Start plan, and if it's set to >0% it functions as the Grow plan. We don't need them to actively make a selection here. We just need a tooltip next to the `host fee` setting on the Fiscal Hosting screen that says OC will charge 15% of the fees.
* We don't need an option for Custom host plans. We should watch the data ourselves and personally get in touch with them. It's a tiny number of hosts and we want to be in close contact with them anyway. We should just note the >$150,000 message on the pricing page and that's enough.

I suggest we completely remove the "Host Plan" section. We can keep it there for old hosts who haven't yet switched over, as the place they make the switch, but after that it's not needed.

**Comment by znarf** [comment]
In our [pricing](https://opencollective.com/pricing), we decided to clearly segment in 3 different plans: **start**, **grow** and **scale**.

I personally still see value asking Hosts to switch from **start** to **grow** when they want to charge Host Fees, it's a clear opt-in from them and help us treat them differently. As of today, the Host Fee setting is not even available for Hosts in the **start** plan.

I'm open to discuss this, but if we decide to drop this distinction, we also need to review the pricing page, and stop mentioning the **start** and **grow** plans there.

Overall, I don’t feel good about investing engineering and design resources in an interim solution, especially if it’s just for 1 month. I prefer we focus on what we want from May 1st.

We can handle this as a project to be considered for next sprint.

**Comment by alanna** [comment]
> I personally still see value asking Hosts to switch from start to grow when they want to charge Host Fees... we also need to review the pricing page, and stop mentioning the start and grow plans there.

I disagree. I think simplicity is very important in pricing, and we designed the new plan so it functions the same way whether they charge host fees or not. I think the pricing page design is way too complicated and anything we can do to simplify that is a win.

> I don’t feel good about investing engineering and design resources in an interim solution, especially if it’s just for 1 month. I prefer we focus on what we want from May 1st.

This I agree with.

My position is we should take this on and decide how it should be, to be ready by May 1. I strongly support simplifying, but we can discuss it as a team.

**Comment by alanna** [comment]
Now that we have transitioned everyone to the new plans, the outstanding part of this issue is:

> There is no difference between the Start plan and the Grow plan and we don't need separate selections for them. If their host fee is set to 0% it functions as the Start plan, and if it's set to >0% it functions as the Grow plan. We don't need them to actively make a selection here. We just need a tooltip next to the host fee setting on the Fiscal Hosting screen that says OC will charge 15% of the fees.

We should entirely remove the Host Plan section.

**Comment by BenJam** [comment]
++ this seems like a hanger that we need to tidy up as part of the migration process.

**Comment by znarf** [comment]
> There is no difference between the Start plan and the Grow plan and we don't need separate selections for them. If their host fee is set to 0% it functions as the Start plan, and if it's set to >0% it functions as the Grow plan. We don't need them to actively make a selection here. We just need a tooltip next to the host fee setting on the Fiscal Hosting screen that says OC will charge 15% of the fees.

I disagree about this. We have a really clear Pricing page, segmenting Fiscal Hosts in 3 clear categories (Start, Grow, Scale). As a Fiscal Host admin, I want to clearly know in which category I belong and what is the current pricing applied to me.

<img width="856" alt="Screenshot 2021-08-19 at 14 26 55" src="https://user-images.githubusercontent.com/806/130068524-671ea0cb-4904-4302-ba76-1ab60e115a48.png">

I don't mind dropping the Host Plan settings but:
- there should be a place where to clearly display the current pricing applied to the Fiscal Host account
- or, we redo our Pricing page and remove the categorization

**Comment by alanna** [comment]
Yes, I still think it's needlessly complex to have start and grow in both the setting and pricing page, because they are the same. Better to fix it in both places.

**Comment by alanna** [comment]
I am updating the pricing page to reflect the new clarified terminology in #4929 and removing all reference to plans. It's totally unneeded complexity and the goal here is to make pricing simple. So once that's gone, there's no need to retain the entire `Host Plan` section in settings.

**Comment by alanna** [comment]
@znarf is there any block on just removing this now?

**Comment by kewitz** [comment]
To-Do:
- [ ] Check which plans are being used in our DB.
- [ ] Update start-plan to match grow-plan features.
- [ ] Review special conditionals for "start-plan-2021"

**Comment by piamancini** [comment]
- [ ] Fix some technical debt

**Comment by alanna** [comment]
Is this done?

**Comment by BenJam** [comment]
just tested and i cant see these options any more.
