### ISSUE TITLE
Credit Card input looks broken in Recurring Contributions

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4059]
There is not enough space to display the input.

<img width="299" alt="Screenshot 2021-03-04 at 14 01 37" src="https://user-images.githubusercontent.com/806/109967861-3c44be00-7cf2-11eb-9dd5-f407fd08f90a.png">

**Comment by Betree** [comment]
I'm gonna push a simple fix setting the `min-width` of the card to 275px.
