### ISSUE TITLE
Do not allow hosts with >0% host fee to select Start Plan

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4060]
If a host does not understand the nuances of the `Start Plan` vs the `Grow Plan` they can very easily choose the wrong one. I have raised #4056 to discuss problems with this page overall, but this is a specific and painful issue I think we should tackle ASAP.

We just had a case where a host unknowingly picked the wrong one, and the effect was deactivating their host fee without telling them, and it took months for them to notice. The only difference between Start and Grow is having a host fee or no host fee, but this is only explained in the tiny bullet point text.

To select the `Start Plan` a host should already have a 0% host fee set. Or, at least we should pop up a big warning asking if they are sure, because selecting that plan will deactivate their host fee.

**Comment by alanna** [comment]
I'm trying to scope this in a simple and specific way, so hopefully it can be done soon or maybe be a bounty. I think we're likely to get more messy situations if we don't fix this.

If a host has a >0% host fee and they try to select the Start plan, it does not allow it and an error pops up saying:
> The Start Plan is for Fiscal Hosts who do not charge Collectives a Host Fee. Your Host Fee is currently set to %X. To select the Start plan, first [change your Host Fee](link to host fee settings page) to 0%. If you want to continue to charge a Host Fee, please select the Grow Plan instead.

**Comment by alanna** [comment]
We really just need to remove Host plans entirely. We don't need them (see #4056). But if we're not going to do that soon, then +1 to doing this one now because this is a very bad situation if it goes wrong and it's a simple fix.

**Comment by BenJam** [comment]
:100:

**Comment by alanna** [comment]
We are prioritising #4056 so we don't need this anymore.
