### ISSUE TITLE
Bank transfer payments not activated after inputting bank info

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4062]
**Describe the bug**
If you create a new Collective, click start accepting contributions, click "add bank account" as part of the setup process, and put in the bank details, the "contribute" options will activate but no payment is actually available. Noticed when helping a new Collective get setup, and then I was able to reproduce myself.

**To Reproduce**
1. Create a new Collective
2. Click "start accepting contributions"
3. Select "ourselves" as host
4. Select "bank transfer" for how will you accept money
5. Enter bank details and proceed
6. Land back on Collective page, with contribute options activated
7. Try making a contribution
8. See error: "There is no payment provider available"

I set up this Collective for testing and it's currently in this state: https://opencollective.com/testing-bank-setup

To enable contributions by bank transfer in the Collective I was setting up with the user, she had to go to the "receiving money" settings and add the bank account all over again, then it started working.

**Comment by znarf** [comment]
We did some QA on Wednesday for this and could not reproduce.
