### ISSUE TITLE
Toast notifications: implement dark theme

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4063]
The toast notifications are easy to miss because they have a white background - like most of our pages. An alternative design was initially proposed, and we would like to experiment with it. The toast notification should ideally support both versions (depending on a `variant` prop) to be compliant with the design system (use https://styled-system.com/variants/).

**Preview of the current  toast notification (see bottom-right)**
![image](https://user-images.githubusercontent.com/1556356/110087457-f93b2700-7d93-11eb-88e8-d2df7a0b33d0.png)

**What we need to implement**
Design: https://www.figma.com/file/N4Xbl652BhzOutXmzhcrLGch/%5BDS%5D-02-Atoms?node-id=3480%3A1027

![image](https://user-images.githubusercontent.com/1556356/110087409-e7f21a80-7d93-11eb-9c61-2546da31174a.png)

**Comment by sidverma32** [comment]
I would like to pick this up, can you guide me as it's my first open source task @Betree .

**Comment by Betree** [comment]
> I would like to pick this up, can you guide me as it's my first open source task @Betree .

Hi @sidverma32, the design to implement is linked in the issue. The related component is `components/Toast.js`, the easiest way to test it is to add a `addToast({ message: 'Test' });` on any page. Steps to setup the frontend are documented in [the Readme](https://github.com/opencollective/opencollective-frontend).
