### ISSUE TITLE
Support Metrics Report February 2021

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#4065]
### Support Metrics Report February 2021

This report looks at the trends around support to help us better understand areas we need to improve and highlight key topics for the month. 

**Tickets received** 

![Capture](https://user-images.githubusercontent.com/57156267/110260777-7bd11a00-8012-11eb-9fef-a301a388e52d.JPG)

The number of tickets received increased slightly (5%) from 443 in January to 465 in February. By removing blank tickets, tickets raised in February actually decreased in comparison (~13%) - 277 tickets compared to 317 in January. [You can find the detailed listings here.](https://docs.google.com/spreadsheets/d/1pO6FQzpxUXpBms43J94rxhX4toU2IP3S/edit#gid=659450378)

![Capture](https://user-images.githubusercontent.com/57156267/110260849-c783c380-8012-11eb-9ea8-ead5e6f3a2ed.JPG)

**Trends and Recommendations**
After removing irrelevant tickets, we had 277 that required support attention. It is worth noting the following areas:

**Expenses**

Questions related to expenses continue to be our biggest ticket item. The tickets associated with user responding directly to support rather than in the expense thread related to collectives under The Social Change Nest continue to be the key driver here. [A new issue was created](https://github.com/opencollective/opencollective/issues/3740) to address this common mistake and it looks like it was picked up as a bounty so hoping to update on a change next month. 

There was also an increase in ticket raised in relation to expenses raised in collectives under Foundation. It is worth mentioning that we sought additional advice from our accountants on the topic of reimbursements claimed for cash payments that some groups use as their main method of support and we were interacting with their admins to provide further clarifications on the process to ensure our payments process is going more smoothly and we are avoiding unnecessary delays in the transfer of funds while ensuring we collect all the required information. From questions arising in this space, it seems there is still some confusion in place when it comes to the question of privacy and collectives and users understanding of what information on the expense form is public and which has restricted access. 

**Tax**

The increase in the number of tickets related to tax was mostly driven by two factors this month:

- We reached the limit of 100 free forms we can send and this happened towards the end of January and February which led to users follow-ups on this matter. Given the increase in the requirement of forms to be sent in January and the roll-out of any access forms to February, it would be interesting to observe what happens in March as an indicator of whether or not we should upgrade our Hello Works profile to a paid plan. 
- 
- We received enquiries from users submitting invoices for payment during 2020 but haven’t received their 1099s. These inquiries came through those users choosing to get paid through PayPal and given these forms should be addressed by PayPal directly, the accountants have identified a gap in the income levels between 1099-MiSC ($600) to 1099-K PayPal report on (which can vary from state to state but in general, is around the $2k mark for a financial year).

 
**Onboarding** 

Onboarding related questions are still some of the common ones we receive, however, there seems to be a drop in comparison to both January and December as the volumes of new applications keep on being quite consistent. 

We approved 29 new applications for OCF compared with 21 in January.

For OSC -  35 new collectives were approved during February compared to 58 in January. 

**Financial contributions**

Even though there was an increase in the number of tickets received on the matter, no significant issues identified and those questions were mostly related to incoming bank transfers and on occasion some difficulties with a contribution made by card. 

One thing worth mentioning and something we may consider going forward is the scenario when a user wanted to contribute by a bank transfer and then changed their mind to another payment method. We received a number of requests to cancel pending orders and it would be good if this would be something users could update on their own perhaps if this is possible. 

**Other things to note**

- We received a number of requests to process refunds and cancel subscriptions where users missed the timing and got charged. Even though there is an increase in requests to cancel subscriptions, it is not too significant to flag and given the increase in activity, it seems to be a reasonable trend to see.

**Comment by Betree** [comment]
Hopefully, the HelloWorks limit should not be an issue next month
