### ISSUE TITLE
Redirect to /contribute when /donate is disabled

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4066]
When the default tier is disabled, `/donate` shows a message that is a bit scary and doesn't incentive you to go ahead with your contributions. Users can end up on this link if one was shared publicly in the past (on social networks, website, etc.).

So rather than this message, we should directly redirect to `/contribute`, where they can see all available tiers.

![image](https://user-images.githubusercontent.com/1556356/110290947-a2c82580-7feb-11eb-9326-3c96b1ea1cbf.png)

**Comment by saideepesh000** [comment]
@Betree, So this redirect should only be given when `This collective requires you to select a tier to contribute` condition is met, Am I right?, or for every condition on `contributionBLocker.js`

**Comment by Betree** [comment]
> @Betree, So this redirect should only be given when `This collective requires you to select a tier to contribute` condition is met, Am I right?

Correct. We want to redirect only when no tier is selected and `account.settings.disableCustomContributions` is `true`.
