### ISSUE TITLE
Virtual Credit Cards: Attach Receipt to Expense

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#4067]
## User story
As a collective admin, I can use my virtual credit card to pay for services my collective use.
Due to service provider limitations, as a collective admin, I can easily attach a receipt from a virtual credit card charge so that my fiscal host can legally take ownership of that charge.

## Best solution for this problem
The collective admin can simply use their virtual credit card without worrying about anything else.
Since (1) the host collective legally requires a receipt for credit card charges above $25 and (2) we can't access the receipt through the credit card provider API; the next best thing is to automate as much as we can and ask for the user to just upload that receipt.

## MVP
- Automatically create expenses and transactions for these credit card charges.
- Add a small button to paid charge expenses that allow collective admins to quickly attach the receipt.
- When a new transaction is created, notify the collective admin they need to attach a receipt to that expense.

**Comment by alanna** [comment]
Please be careful generalising that $25 threshold to all Hosts - that's advice we got for OCF and OSC specifically. We have no idea what the limitations may be for other types of US legal entities or Hosts in other countries. It may very well be that some hosts must have receipts for smaller charges too. So either make this feature restricted to OSC and OCF, make the threshold a host-level setting the admin can change, or make the threshold $0.
