### ISSUE TITLE
Add calendar year and/or date range options to expense period picker

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4070]
It would be very useful if I could customise the date range for seeing expenses (and probably other places on the platform if this component is reused). Or if not completely custom, at least to be able to select calendar years.

![Screen Shot 2021-03-10 at 10 37 04 AM](https://user-images.githubusercontent.com/5498878/110541551-c676a180-818c-11eb-959f-0b8c375b2283.png)

Like the date picker we have for transactions downloads (but for viewing expenses on screen):

![Screen Shot 2021-03-10 at 10 39 03 AM](https://user-images.githubusercontent.com/5498878/110541649-ead27e00-818c-11eb-957f-cebc25da699f.png)

**Comment by alinamanko** [comment]
+1
