### ISSUE TITLE
Contribution flow: Hide interval picker if not available

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4072]
When users set up a new collective without Stripe, the contribution flow still offers to pick an interval then shows a "No payment methods available" on the last screen. It's pretty rare to have collectives in this situation because fiscal hosts usually configure a way to receive recurring contributions (Stripe).

Still, getting this message when you test the flow after creating your Collective is not a nice experience. The only case where people are able to create a recurring contribution are:
- If the host has STRIPE
- If the host has BRAINTREE_PAYPAL
- If the contributor is an admin of another collective hosted under the same host

**Todo**
- [x] If none of these conditions are met, we should hide the interval picker.
- [x] If the selected tier has an interval but no option for that is available, we should prevent accessing the flow (with `getContributionBlocker` and show a link to see other ways to contribute)

![image](https://user-images.githubusercontent.com/1556356/110596808-0aaf7500-8180-11eb-902b-9ddd8f7cbd88.png)

**Context**
https://opencollective.slack.com/archives/C01NGE0N9U1/p1614504388000400?thread_ts=1613975942.002000&cid=C01NGE0N9U1

**Comment by SudharakaP** [comment]
@Betree : I can give it a try for this one next if there's no objection? 🤔

**Comment by SudharakaP** [comment]
@Betree : Hi, so I've submitted a pull request, but one thing I am uncertain about is the third point you mentioned. 

> If the contributor is an admin of another collective hosted under the same host

I am wondering does that matter. Even if the contributor is an admin of another collective under the same host if the host hasn't configured Stripe or Paypal then the recurring contribution flow should be blocked right? 😄

**Comment by Betree** [comment]
> @Betree : Hi, so I've submitted a pull request, but one thing I am uncertain about is the third point you mentioned.
> 
> > If the contributor is an admin of another collective hosted under the same host
> 
> I am wondering does that matter. Even if the contributor is an admin of another collective under the same host if the host hasn't configured Stripe or Paypal then the recurring contribution flow should be blocked right? smile

If you're an admin of a collective under the same host, I think you can still make collective to collective recurring contributions. For example, Babel admins can create a recurring contribution to Webpack from their budget.

**Comment by SudharakaP** [comment]
> > @Betree : Hi, so I've submitted a pull request, but one thing I am uncertain about is the third point you mentioned.
> > > If the contributor is an admin of another collective hosted under the same host
> > 
> > 
> > I am wondering does that matter. Even if the contributor is an admin of another collective under the same host if the host hasn't configured Stripe or Paypal then the recurring contribution flow should be blocked right? smile
> 
> If you're an admin of a collective under the same host, I think you can still make collective to collective recurring contributions. For example, Babel admins can create a recurring contribution to Webpack from their budget.

Ah, I understand now. Thanks for the clarification. Let me add that too. 😄

**Comment by SudharakaP** [comment]
> > @Betree : Hi, so I've submitted a pull request, but one thing I am uncertain about is the third point you mentioned.
> > > If the contributor is an admin of another collective hosted under the same host
> > 
> > 
> > I am wondering does that matter. Even if the contributor is an admin of another collective under the same host if the host hasn't configured Stripe or Paypal then the recurring contribution flow should be blocked right? smile
> 
> If you're an admin of a collective under the same host, I think you can still make collective to collective recurring contributions. For example, Babel admins can create a recurring contribution to Webpack from their budget.

@Betree : I've added this as well to the PR. Let me know if you see any further issues. Just to demonstrate here's a typical flow with a user whose the admin of another collective under the same host. As you can see everything (including the interval picker) is shown as usual. 

![user-whose-admin](https://user-images.githubusercontent.com/12435965/119527346-177e4680-bd35-11eb-8f2b-8e09fc58292c.gif)
