### ISSUE TITLE
Enable Projects for Collectives

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4074]
This is part of a bigger conversation about unifying the features for Collectives and Funds, which will involve figuring some stuff out for permissions and ensuring we don't make it all too complex, but I wanted to have an issue for it because I do think we should do it.

The use case I am working on is: I’ve set up different funding goals using tiers in a Collective, and now I need a way to allocate those funds to budgets that I can track expenses against. I thought if I could create projects for each one, that could work well.

@piamancini 
> We should unify I think - But it's not that simple of admin rights atm, also let’s consider if we shouldn’t ditch everything and have collectives being events and projects. Just with opt in settings and being “connected collectives”

@znarf 
> Maybe, Events or Projects should be opt-in, I’m afraid to have a bloated experience for new Collectives if they have Events and Projects on by default. The admin rights is a good thing to improve. I still think it’s a good idea to have Collective admins being Events and Projects admins by default as a basis (can’t be removed!). People could invite extra admins for Events and Projects.

Kayla
> +1 giving Projects access to collectives

**Comment by kaylarep** [comment]
A comment from [a group](https://opencollective.com/solidaridad-inquilina): 

> We really do like the projects feature which allows for separate funds to be easily managed and for fundraising for very specific audiences.

**Comment by kaylarep** [comment]
From the roadmap meeting (Apr. 4, 2021)
Pia:

> -  opportunity to prune the platform a bit, make something more versatile. 
rethink the basic concept of having a unit under a collective
> - opportunity to rethink this

Memo:

> - a way for collectives and proects to allocate specific budgets inside their collectives
> - localized budgets should be different-may have need for some design work
 
Francois

> - it's kind of already done, can be done simply & easily
> - could implement it and then refine it later

P:
> - doesnt have custom admin rights in its current form, may just provide further complication
> - will have the same problems that events have, so should merge this with events

F
> - Projects may be more simple, less edge cases, not ticketing, 

Benjam:
> for those communities who are asking for it, we can ask them if they want to try out the beta, then provide feedback

**Comment by alanna** [comment]
I would be really keen to be in the beta for this for [EHF Community](https://opencollective.com/ehf-community) because we're raising a series of crowdfunding campaigns and I need to keep all their budgets and expenses straight. I am 100% fine if it's a bit rough and there's no different admin permissions, etc.

**Comment by BenJam** [comment]
Tracking this in #4204
