### ISSUE TITLE
Goal progress bar not rendering correctly

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4076]
https://opencollective.com/possibilityproject

This Collective has raised $500 of a $100,000 goal, but it's showing as if it's already been achieved.

![Screen Shot 2021-03-11 at 10 30 42 AM](https://user-images.githubusercontent.com/5498878/110700619-099c4780-8255-11eb-862a-dc2b15237776.png)

**Comment by Betree** [comment]
That does not appear to be a bug, the collective wrote $100,000 in their description but put $0 in the "Amount" field. I've manually updated the value in the DB.

**Comment by alanna** [comment]
@Betree should it be allowed to have a goal amount of $0 like that? I wonder if there are cases where people might want that, but it seems odd.

**Comment by Betree** [comment]
> @Betree should it be allowed to have a goal amount of $0 like that? I wonder if there are cases where people might want that, but it seems odd.

We can eventually enforce some validations, that would prevent similar issues in the future
