### ISSUE TITLE
Collective.getUser should not rely on CreatedByUserId

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4082]
In https://github.com/opencollective/opencollective-api/blob/1679d6b30076d10de1a4635a6f86739ac276d992/server/models/Collective.js#L1124, it should be replaced with:

```es6
return models.User.findOne({ CollectiveId: this.id }, queryParams);
```

We must make sure that doing so doesn't break existing code.

**Comment by ericyoungson** [comment]
@Betree I'd be interested in taking a stab at this one. Seems like a good way to get oriented to the API.

**Comment by Betree** [comment]
@ericyoungson Feel free to get a look if you want to, but it might not be as simple as it sounds. A good understanding of our data model is important and the ability to properly identify the side effects is key to resolve this. There may be numerous places and tests that depend on this legacy behavior. 

I would strongly recommend to rather look at issues tagged with [good first issue](https://github.com/opencollective/opencollective/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22), these are the ones we think are accessible enough to get started with the codebase.

**Comment by ericyoungson** [comment]
@Betree Ok. Thanks for the feedback; I'll keep looking at other issues to take up.
