### ISSUE TITLE
Showing NULL balance in error

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4088]
https://opencollective.com/collective/events/an-entangling-wellington-13971425

When I view expenses for this event on the host dashboard, it shows `Balance --.-- NZD`. But the event has a positive balance. The system did let me pay the expenses so it knows the balance isn't actually $0, but it's displaying it as if it were $0.

<img width="970" alt="Screen Shot 2021-03-16 at 10 16 12 AM" src="https://user-images.githubusercontent.com/5498878/111222544-dab11780-8640-11eb-8b35-b56cb565d7cc.png">

<img width="1228" alt="Screen Shot 2021-03-16 at 10 15 49 AM" src="https://user-images.githubusercontent.com/5498878/111222559-dedd3500-8640-11eb-905b-18aebba3146b.png">

**Comment by znarf** [comment]
As of today, the balance is effectively zero, so we can't troubleshoot this issue.
