### ISSUE TITLE
Enable flexible frequency interval for custom tiers

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4089]
## User story 
As a Collective admin, I want to create a tier for a given purpose/goal and allow contributors to decide whether they want to make a one-time or recurring contribution.

## Best solution for this problem
Do not force a tier to be either one-time or recurring, but allow contributions of either type.

I created a new tier and set it to `flexible` for amount, but there's no `flexible` option for interval. And if I then contribute to the tier and chance the frequency setting, it kicks me out of that tier. Sometimes you want to raise funds for a given purpose and you don't care if the contributions are one-time or recurring.

<img width="927" alt="Screen Shot 2021-03-16 at 11 16 36 AM" src="https://user-images.githubusercontent.com/5498878/111228578-52834000-8649-11eb-831d-feacc965795d.png">

<img width="644" alt="Screen Shot 2021-03-16 at 11 15 55 AM" src="https://user-images.githubusercontent.com/5498878/111228718-88282900-8649-11eb-9846-e53dc7fffcf6.png">

**Comment by snitin315** [comment]
Duplicate of #3720 

Implementation started in https://github.com/opencollective/opencollective-frontend/pull/6047

**Comment by alanna** [comment]
MFW I raise a dup of an issue *I myself previous raised* 🤦‍♀️

**Comment by Betree** [comment]
Before closing duplicates, a good habit is to tag them with `duplicate` or `invalid` to prevent them from being included in https://changelog.opencollective.com.
