### ISSUE TITLE
NZD Host's Wise balance displaying in EUR

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4091]
<img width="788" alt="Screen Shot 2021-03-16 at 9 55 29 PM" src="https://user-images.githubusercontent.com/5498878/111282031-6b6c0f80-86a2-11eb-995c-3c683c268a54.png">

**Comment by kewitz** [comment]
@alanna is this an intermittent bug? I notice the screenshot on the other bug-report displays NZD.

**Comment by alanna** [comment]
Yeah it has disappeared now. Weird.

**Comment by kewitz** [comment]
@alanna the requested behavior is already implemented and this can be caused by issues on Wise's API.
I'll close this for now but I would be curious to know if this ever happens again.
