### ISSUE TITLE
Embed contribution flow: adapt wording for platform tips

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4092]
The wording that we currently use for platform tips doesn't work well for the embed flow, where people have no context about what Open Collective is:

> The Open Collective Platform is free for charitable initiatives. We rely on the generosity of contributors like you to make this possible!

![image](https://user-images.githubusercontent.com/1556356/111313868-2378c880-8661-11eb-9fe2-26922b23eeb3.png)

We should change this wording when running in the embed contribution flow. Something like:
> This fundraising page is powered by [Open Collective](https://opencollective.com), a platform for communities to sustain themselves. Open Collective is free for charitable initiatives, we rely on the generosity of contributors like you to make this possible!

Ping @alanna @piamancini @benjam - would love to hear your suggestions on the copy.

_See https://captainfact.io/support-us_

**Comment by BenJam** [comment]
I've been reminding myself about how we pitch open colletive here and 

> Open Collective lets you manage your finances so everyone can see where money comes from and where it goes. Collect and spend money transparently.

I wonder whether we might tweak this slightly into something that works as a single sentence: 

> This page is powered by Open Collective, a platform that lets you collect and spend money transparently. Open Collective is free for charitable communities, we rely on the generosity of contributors like you make this possible. 

There is a part of me that wonders whether we could tweak the final part to include teh name of the project, if we're passing an ID in the embed? Something like:

> Open Collective is free for charitable communities, we rely on the generosity of contributors like you to support projects like CaptainFact.

**Comment by Betree** [comment]
That looks good! Adding the project name in the string is not a problem from the dev side.

The tricky part may be the word "project" since this flow can be used with many different types of initiatives (collectives, events, fiscal hosts, funds, etc). I prefer your second proposal in this regard, but if we feel that "project" is broad enough (we can also use the word "initiative") we can use that. It's also possible to adapt the wording based on the initiative type if we feel that it's the right thing to do (eg. show `support events like ...` if it's an event).

**Comment by BenJam** [comment]
honestly I think that the second is fine and that the third is just a marginal improvement becuase we're keying into the specific cause and saying 'you can support more projects like this one you obvious care about'. 

If it isn't too tricky and we have a comprehensive enumeration of the different types we support then inserting the type too would get a 👍  from me. Also 💯  happy with the second option though.

**Comment by BenJam** [comment]
FANK STALE BOT
