### ISSUE TITLE
Option to not notify anyone when posting an update

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4093]
For host updates, sometimes we want to post small updates and not notify everyone, so it would be great to have a `no one` option alongside `financial contributors` and `Collective admins`.

**Comment by Betree** [comment]
This could be as simple as adding a `NO_ONE` option to `UpdateAudienceType`, with small checks in `getUsersToNotify` and `countUsersToNotify`

**Comment by snitin315** [comment]
@Betree can this be a bounty?

**Comment by Betree** [comment]
Sure! :gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted, and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

The contribution should include tests for the API part:
- `test/server/models/Update.test.js`
  - `getUsersToNotify returns an empty array when audience is NO_ONE`
  - `countUsersToNotify returns 0 when audience is NO_ONE`
- `test/server/graphql/v2/mutation/UpdateMutations.test.js` > `publishes an update`
  - `No email is sent if the audience type is NO_ONE`
