### ISSUE TITLE
Indexation of user profiles by search engines

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4095]
From user feedback:
> When you google for "*user name*" one of the top results is his list of payments. This is a really weird thing for people looking him up in advance

It's understandable that some users may not want to have their Open Collective profiles popping in their Google results, especially because of the list of transactions where you can see the amounts that a person received through expenses.

I see two ways to resolve this situation:
1. Either we decide that all user profiles should be private and we add `NOINDEX` on all user's pages to ask Google to forget them
2. Or we make that opt-in/opt-out by adding a section in the settings to change the "Profile visibility", with two options: Public (current behavior) or Unlisted (won't appear in search engines)

Making the user profiles private is **not** on the table at the moment, as doing so would go against transparency.

**Context**
*https://opencollective.slack.com/archives/G01E5EWDH40/p1616079967001000*

**Comment by piamancini** [comment]
I think it's ok to have users profiles with noindex -- many users are surprised their info shows up in google. 
unless there's an argument for keeping them public, I would err on the side of protecting them

**Comment by Betree** [comment]
We can start with that, and implement (2) (opt-in) if people ask to have their profiles public

**Comment by alanna** [comment]
I agree - be default `noindex` for personal profiles. But what about corporate sponsors like Airbnb or something, who are using us because they want that recognition and exposure?

**Comment by Betree** [comment]
> I agree - be default `noindex` for personal profiles. But what about corporate sponsors like Airbnb or something, who are using us because they want that recognition and exposure?

If we apply that only to user profiles, sponsors like Airbnb won't be impacted (as long as they're registered as an organization).

**Comment by znarf** [comment]
I don't see any Individual complaining that their profile is not indexed. We could always have a setting for this if needed.

However, I see it as yet another step for less openness/transparency. Next time, people will ask us to have their profile or their transactions private by default, be prepared.
