### ISSUE TITLE
Connect PayPal: automatically create webhook

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4096]
In [PayPal setup docs](https://docs.opencollective.com/help/fiscal-hosts/payouts/payouts-with-paypal#paypal-payouts), we ask admins to manually create a webhook to get the notifications redirected to Open Collective, then to copy-paste the webhook ID in their settings. There are a few reasons why this process can be improved:
- Host admins can make mistakes. They can put the wrong URL in there, or forget to check the proper events.
- If we need additional permissions (which is the case for #3986), we'll need to ask admins to update their webhooks

This process can be simplified thanks to PayPal's [Webhooks API](https://developer.paypal.com/docs/api/webhooks/v1/#webhooks_post) that allows listing/creating/deleting/updating webhooks.

# Specs

- [x] In the frontend, remove `webhookId` from connected account settings
- [x] When connecting a PayPal account, automatically create the associated webhook on PayPal and store its ID
- [ ] Migrate existing accounts to this new system
- [ ] Update docs

*Ping @kewitz*

**Comment by kewitz** [comment]
Definitely an improvement, @Betree!
I thought about doing that for TransferWise, but I didn't implement the creation of webhooks because I refactored to use TransferWise to use OAuth and in the OAuth schema, the Application itself has a single webhook to receive events.

**Comment by Betree** [comment]
Because the `PAYMENT.SALE.COMPLETED` webhook event doesn't contain much info (no subscription ID, no order ID, etc) we have to fetch more data to be able to record the transaction. But we need to know which host the notification is for to fetch this additional data (because we need to use its connected account).

The only solution to achieve this is to have a webhook route like `/webhooks/paypal/:hostId`, so we'll have to prioritize this issue for the public release of PayPal recurring.
