### ISSUE TITLE
Expense attachments icons are not respecting their container size on Firefox mobile

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4099]
On mobile:
![IMG_20210320_121017.jpg](https://user-images.githubusercontent.com/1556356/111867581-4105a500-8975-11eb-9790-8582f2a06551.jpg)

See https://opencollective.com/captainfact_io/expenses/35329

**Comment by snitin315** [comment]
It looks like it's fixed. 

<img width="331" alt="Screenshot 2021-04-29 at 8 16 36 AM" src="https://user-images.githubusercontent.com/46647141/116496684-4256b580-a8c3-11eb-9d79-34d25b5e68c0.png">

**Comment by Betree** [comment]
@snitin315 You're viewing an expense where you don't have permissions over the attachments. The bug only seems to affect the preview icon as seen in the screenshot above. I just tested on Firefox Mobile + Android and it's still there.

**Comment by SudharakaP** [comment]
@Betree : Quick fix for this done by making sure the attachment holder stays the same size. Hope that looks good now. Let me know. 😄

**Comment by kewitz** [comment]
Facing something similar on Safari:
![image](https://user-images.githubusercontent.com/2119706/144045141-8b9c52f0-ce33-40b5-89b1-f4e04c01b007.png)

![image](https://user-images.githubusercontent.com/2119706/144045166-6dc9bfdd-83fa-4882-a70f-17d9af544cfe.png)

**Comment by Betree** [comment]
This is still happening. Context:
- Latest Firefox mobile on Android
- https://opencollective.com/captainfact_io/expenses/64909
- Logged in as a collective admin

![Screenshot_20220223-080117_Firefox](https://user-images.githubusercontent.com/1556356/155287432-55b37799-cd62-4297-ae32-f6e884687514.png)

**Comment by Betree** [comment]
Still seeing this issue, I'm adding a bounty on it

![Screenshot_20220901-225531_Firefox~3.png](https://user-images.githubusercontent.com/1556356/188011553-dd89d932-3ecf-4cb1-bd9a-8c5793213e42.png)

**Comment by Betree** [comment]
:trophy: This issue has been completed by @snitin315  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
