### ISSUE TITLE
fix image in thank you mail 

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#41]
Images in thank you emails are broken now.This is probably due to the new design. cc / @xdamman @carlosascari

**Comment by asood123** [comment]
Cloudinary isn't returning anything for some images: https://github.com/OpenCollective/api/blob/master/templates/emails/thankyou.hbs#L10.

Like this for Angular: https://res.cloudinary.com/opencollective/image/fetch/w_80/https://avatars3.githubusercontent.com/u/12663106?v=3&s=200

@xdamman were you manually adding logos to cloudinary or is it supposed to pick that url up on the fly?

**Comment by xdamman** [comment]
it's supposed to pick those images on the fly.
We are far from reaching the limits of our current free plan:
![](
http://cl.ly/3l3p3v3t0a3m/Screen%20Shot%202016-04-20%20at%205.47.27%20PM.png
)

**Comment by asood123** [comment]
Looks like it can't do https:// requests? 
This works: https://res.cloudinary.com/opencollective/image/fetch/w_80/http://avatars3.githubusercontent.com/u/12663106?v=3&s=200
This doesn't: https://res.cloudinary.com/opencollective/image/fetch/w_80/https://avatars3.githubusercontent.com/u/12663106?v=3&s=200
So, let's make sure that our `logo` column only has `http`. @piamancini. There are a lot of groups with https - must be a sql query to find and replace it.

**Comment by xdamman** [comment]
It's also possible that's a temporary issue on their side. It feels like it
worked before.
That said, yes, it doesn't hurt to load the logo from http since we use
https anyway to load it from cloudinary.

**Comment by asood123** [comment]
Ran this query to fix existing entries: 

```
update "Groups" 
set logo = replace(logo, 'https', 'http')
where logo like 'https%';
```

**Comment by sedubois** [comment]
@asood123 are you sure the issue is fixed? I still get 400 error when entering URL below in browser. 
https://res.cloudinary.com/opencollective/image/fetch/w_80/http://avatars3.githubusercontent.com/u/12663106?v=3&s=200

**Comment by asood123** [comment]
Weird that url works for me.

**Comment by asood123** [comment]
Hmm it loads in my browser but not in terminal:

```
Aseems-MacBook-Air-2:Downloads aseem$ wget https://res.cloudinary.com/opencollective/image/fetch/w_80/http://avatars3.githubusercontent.com/u/12663106?v=3&s=200
[1] 53240
Aseems-MacBook-Air-2:Downloads aseem$ --2016-04-21 11:11:49--  https://res.cloudinary.com/opencollective/image/fetch/w_80/http://avatars3.githubusercontent.com/u/12663106?v=3
Resolving res.cloudinary.com... 23.63.184.61
Connecting to res.cloudinary.com|23.63.184.61|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2016-04-21 11:11:50 ERROR 400: Bad Request.


[1]+  Exit 8                  wget https://res.cloudinary.com/opencollective/image/fetch/w_80/http://avatars3.githubusercontent.com/u/12663106?v=3
Aseems-MacBook-Air-2:Downloads aseem$ 
```

**Comment by sedubois** [comment]
Have you cleared your cache?

**Comment by sedubois** [comment]
For me both `curl` and browser get reply header `X-Cld-Error: Invalid fetch URL - not properly escaped`

**Comment by sedubois** [comment]
Replacing the `?` with %3F works: https://res.cloudinary.com/opencollective/image/fetch/w_80/http://avatars3.githubusercontent.com/u/12663106%3Fv=3

**Comment by asood123** [comment]
That makes sense. 

http://cloudinary.com/documentation/fetch_remote_images#creating_a_fetch_url_containing_special_characters

**Comment by sedubois** [comment]
Can use this Javascript: `https://res.cloudinary.com/opencollective/image/fetch/w_80/${encodeURIComponent("http://avatars3.githubusercontent.com/u/12663106?v=3&s=200")}`

**Comment by piamancini** [comment]
Still happening for Consciousness Hacking
<img width="784" alt="screen shot 2016-05-16 at 10 44 14 am" src="https://cloud.githubusercontent.com/assets/3671070/15292873/4b22b626-1b53-11e6-9512-ae884ba95acc.png">

**Comment by sedubois** [comment]
@piamancini could you give the image URL used in that email?

**Comment by asood123** [comment]
Pia is traveling today. I fwd'd it to you, seb.

**Comment by piamancini** [comment]
Seb, do you have everything you need to fix this?

**Comment by sedubois** [comment]
The URL is https://res.cloudinary.com/opencollective/image/fetch/w_80/https%3A%2F%2Fcldup.com%2FQQIUr-FjY4.svg so it's formatting the logo which is https://cldup.com/QQIUr-FjY4.svg (SVG format). 

There are a number of collectives with SVG logo, here's what I get in Firefox:
- consciousnesshackingsf (https://cldup.com/QQIUr-FjY4.svg): **status 200 but blank page** (however does display title `hacckers`)
- nuitdebout (http://www.nuitdebout.fr/img/logoblack.svg): **404 not found**
- rubytogether (http://rubytogether.org/images/rubies.svg): displays OK
- hoodie (https://cldup.com/2T36ZY2qdl.svg): **status 200 but blank page**
- universal-router (https://www.kriasoft.com/universal-router/img/tour.svg):
- gulpjs (https://opencollective-production.s3-us-west-1.amazonaws.com/gulpwhitetextsvg_290cc900-131a-11e6-bfc8-1bf35a49592f.svg): **status 200 but blank page**
- chimp (https://cldup.com/soE1B0CUL9.svg): displays OK
 
I don't know much about SVG rendering, don't know who generated their code, @asood123 ?

**Comment by sedubois** [comment]
OK blank SVGs are actually because they have `stroke="none"` + `fill="none"`, they're made to be rendered with a background. So that's actually OK.

**Comment by sedubois** [comment]
I think the Cloudinary "fetch" API doesn't support SVG graphics. 

Considering this JPG image: 
http://upload.wikimedia.org/wikipedia/commons/0/0c/Scarlett_Johansson_Césars_2014.jpg
(comes from Cloudinary's doc...)

Cloudinary fetches it properly:
http://res.cloudinary.com/demo/image/fetch/http://upload.wikimedia.org/wikipedia/commons/0/0c/Scarlett_Johansson_C%C3%A9sars_2014.jpg

But considering this SVG image: https://commons.wikimedia.org/wiki/Category:SVG#/media/File:Pin_Map_Vector.svg
(URL encoded: https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FCategory%3ASVG%23%2Fmedia%2FFile%3APin_Map_Vector.svg)

It doesn't rendered when fetched by Cloudinary: 
http://res.cloudinary.com/demo/image/fetch/https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FCategory%3ASVG%23%2Fmedia%2FFile%3APin_Map_Vector.svg

Possible workarounds:
- use Cloudinary "upload" API, but that might require an account?: https://support.cloudinary.com/hc/en-us/articles/202521242-Does-Cloudinary-support-converting-SVG-images-to-other-formats-
- use a JPG or PNG instead
- ?

@asood123

**Comment by sedubois** [comment]
Can the reason simply be that mail clients don't render SVG properly? Need to use JPG or SVG? And even if it rendered, it would probably show a blank graphics as there's no background

**Comment by piamancini** [comment]
Yes, it can very well be so. In that case, we need to find a way to store
jpeg logos because most of our logos are now svg and transparent.

**Comment by piamancini** [comment]
This is still happening: 
<img width="768" alt="screen shot 2016-05-31 at 10 20 34 am" src="https://cloud.githubusercontent.com/assets/3671070/15683969/d856b6b0-2719-11e6-9a5c-64700bc748d9.png"> 

Can we come up with a quick fix? even removing the logo altogether when it's an svg is better than the broken image.

**Comment by sedubois** [comment]
@piamancini workaround: https://github.com/OpenCollective/opencollective-api/pull/389

**Comment by piamancini** [comment]
fixed by removing them https://github.com/OpenCollective/opencollective-api/pull/389

**Comment by sedubois** [comment]
NB: forgot to remove svgs in other `thankyou` templates

**Comment by piamancini** [comment]
This was fixed by @asood123 in all templates.
