### ISSUE TITLE
Make ReplyTo address for bank transfer notification the payer not OC

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4100]
When someone makes a bank transfer contribution, the host admin gets this email. If they hit reply, it goes to info@opencollective.com since that's the address the notification comes from. But if a host admin hits reply on this, they want to reach the payer, so the replyto address should be the contributor.

<img width="768" alt="Screen Shot 2021-03-21 at 1 07 06 PM" src="https://user-images.githubusercontent.com/5498878/111888987-5c8cb080-8a46-11eb-9e65-dcdfab3f7a47.png">

**Comment by alanna** [comment]
Are we sure it's done though? @Betree

**Comment by Betree** [comment]
This wasn't done. I think there's a confusion with https://github.com/opencollective/opencollective/issues/3740, where we've set reply-to to `no-reply` for multiple emails.

To provide some specs for this issue:
- Either the contributor is an individual, and in this case, we can directly set the `email`
- Or it's an org/fund/... and we then need to fetch the admin emails to include them all in the reply-to

**Comment by alanna** [comment]
> We should start seriously considering all our notifications as a whole
@piamancini sounds like a project issue waiting to happen! using @BenJam 's new template.

**Comment by MlkMahmud** [comment]
Hi @Betree, can I work on this?

**Comment by Betree** [comment]
@MlkMahmud sure! You can check the local Maildev server (http://localhost:1080/#/) to get details about sent emails.
