### ISSUE TITLE
User interface for connected collectives

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4101]
## User story 
We've been supporting the "Connected collectives" feature for some time now. The amount of maintenance is pretty low, and it's a quick solution that's pretty handy to solve a variety of problems. The only burden right now is that we have to [create them ourselves](https://docs.opencollective.com/help/collectives/connectedcollectives). While this is not super time consuming (we usually get around 2 requests a month), there are a few reasons why we may want to build an interface for users to do it themselves:
1. Surface the feature. A lot of users are not aware that this exists.
2. Improve the user experience. Having to contact support for this is a tedious process, especially since we're batching the requests to save some time to the core team, which can lead to people waiting up to 1 week to get their collectives connected.
3. Reduce support. This might now be true today, but if we're not expecting this feature to go away the sooner we'll implement an interface for it the more time we'll save. Right now we're somewhere around here:

![image](https://user-images.githubusercontent.com/1556356/111963101-6f10f380-8af3-11eb-843b-ab5ca3ff2be4.png)

## Best solution for this problem
Have a `Connected initiatives` page in settings for collectives (and projects?) that displays:
- A list of all the collectives it's connected to (with a button to remove them)
- A list of all the collectives that are connected to the one you're viewing (with a button to remove them)
- A button to add connections

## MVP
- We may not want to involve design, at least not with this being a full-size project - the low priority of this feature doesn't justify it.
- As a basis, we can probably re-use the patterns proposed in https://github.com/opencollective/opencollective/issues/3438#issuecomment-734693116
- Users should only be able to create a connection between collectives they're an admin of. Not respecting this constraint means building an invitation system, which skyrockets the complexity of this issue.

## Documentation 
- https://docs.opencollective.com/help/collectives/connectedcollectives should be updated accordingly

**Comment by BenJam** [comment]
Out of interest how many collected connectives do we have at the moment? Have we seen this grow over 2020 compared to previous years, do we forsee thsi rate increasing now becuase of the types of collectives we see coming on? 

I fully appreciate that answering these questsions should be my job, but I'm still fresh and am taking a punt that you might have this info avaiaible @Betree 😅

**Comment by Betree** [comment]
We have almost 200 connections. It's pretty stable overall, the big peak at the beginning is because we moved the previous system ("child collectives") to this. See https://opencollective-metabase.herokuapp.com/question/201.

Idk if that's something that will be increasing in 2021, but one of the biggest barriers to adoption is the fact that it's only surfaced in a small section of the docs.

![image](https://user-images.githubusercontent.com/1556356/111977724-5d374c80-8b03-11eb-8d25-8e55ee2f1b99.png)


![image](https://user-images.githubusercontent.com/1556356/111977682-50b2f400-8b03-11eb-994a-7648c084ab3b.png)

**Comment by alanna** [comment]
@BenJam I'm not sure the stats we have are indicative of true user uptake because this feature isn't surfaced anywhere and the vast majority don't even know it exists.

Personally I think Connected Collectives are powerful and people would use them a lot more if we gave them the ability.

**Comment by BenJam** [comment]
okay it sounds like someone (happy for this to be me) needs to dive into documenting (and announcing) this maybe before we make improvements? kinda like a smoke test to determine user need?

**Comment by Betree** [comment]
> okay it sounds like someone (happy for this to be me) needs to dive into documenting (and announcing) this maybe before we make improvements? kinda like a smoke test to determine user need?

@BenJam maybe you saw it already, but just in case we started documenting the feature on https://docs.opencollective.com/help/collectives/connectedcollectives

**Comment by alanna** [comment]
@BenJam those are good ideas, but I'm really wondering if the work of doing those things is much less than just implementing a feature for users to actually connect the Collectives themselves?

One super cheap step is to mention Connected Collectives in the newsletter and see if we get any bites. Another cheap thing to look at would be to scan Collectives' About sections to find links to other Collectives, which would indicate users are working around the lack of this feature to accomplish the same function.

**Comment by BenJam** [comment]
if it's low effort let's gopher it.

**Comment by Betree** [comment]
> We should discuss this in the context of talking about the multiple things / entities we have on the platform now. Maybe we can treat everything (events, projects, other collectives) as connected?

That's a good idea, we should definitely include that in the discussion. The main difference between events/projects and connected is that connected collectives is something purely visual: the two entities don't share a budget and can have difference hosts

**Comment by BenJam** [comment]
_/me leans in_

In the docs I've tried to differentiate collectives and projects by the people involved. If you have different people involved in the governace, start another collective. Otherwise go for a project.

**Comment by Betree** [comment]
As suggested in https://opencollective.slack.com/archives/C020ZQSLM5M/p1629586926011400?thread_ts=1629474523.010200&cid=C020ZQSLM5M, a simpler MVP would be to create a simple interface on the admin actions page for root users, that wouldn't require complex checks and an invitation process.
