### ISSUE TITLE
Tracking of already shared Host Fees

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4105]
### Problem

For Host on the new pricing with Host Fee share activated, we're adding on a monthly basis "Host Fees February 2021". Unfortunately, we're not removing yet the part that is already shared with Open Collective through Stripe.

### Solution 

- [ ] We need to add a new transaction "Host Fees already shared with Open Collective (Stripe) in February 2021".
- [x] We also need to add missing transactions for past months

**Comment by kewitz** [comment]
@znarf I was investigating the worker and notice we were in fact deducting the host fees already collected through Stripe.
I'm refactoring the code to do that in a separate transaction to be explicit.
