### ISSUE TITLE
A way to have the Collective to contribute to itself

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4109]
There are lots of cases where a Collective needs to contribute money from the Collective itself. 

For example I'm helping onboard a new one where they have $3,000 previously raised by the community to transfer in from a bank account. Then they also have $200 in cash from event ticket door sales, so someone will transfer $200 from their bank account and keep the cash. In both cases, it's not really the person setting up the contribution who is the source of the funds, it's the wider community of the Collective. Right now they have to create an Org profile that's the same name as the Collective (or close) to have it appear correctly.

It would be nice if it were possible to select the Collective itself as the contributor profile, without that creating a debit transaction, only a credit. This is how it works when a Host adds funds with the source being the host itself, right? These cases are where we are introducing new money to the system. I don't see much difference between a Host doing it and a Collective doing it.

**Comment by alanna** [comment]
I didn't know what the heck to call this issue, sorry. Hope it's clear.

**Comment by Memo-Es** [comment]
I think this feature should be called 'Self added funds for Collectives' and should not be using the contribution flow, but rather the add funds modal we just updated in #3652 @alanna

**Comment by Memo-Es** [comment]
Yeah, that's right, I just don't think that money should be displayed as a contribution from the Collective itself

**Comment by alanna** [comment]
The difference between this and a host adding funds is that a Collective adding funds still requires the money to be actually moved, while a host adding funds implies it's already there. The Collective admin has to either pay with a credit card or bank transfer, and the host still has to validate the money arrives for a bank transfer. So it is a contribution. 

The purpose is to display the contribution as coming from the Collective itself, because that's the use case here. To display a contribution coming from anything else, we already have that functionality - a normal contribution. What users are doing now is creating a redundant org profile with a slightly different name to achieve this.

**Comment by BenJam** [comment]
It kinda seems like we're talking about the platform mirroring the movement of money rather than maintaining a balance, and that feels like the right focus, but what about the framing? the docs says:

> [You can manually add funds to a Collective directly. This is useful when you receive a donation for a Collective outside the Open Collective system (like a bank transfer) and want to apply it to a Collective's budget](https://docs.opencollective.com/help/fiscal-hosts/add-funds-manually)

and, to me at least, that's also the use case we have here. So maybe we use the same langauge but support and track the movement of money correctly?

**Comment by BenJam** [comment]
I took some liberties with command console 😅

![Screenshot 2021-03-24 at 14 19 53](https://user-images.githubusercontent.com/158833/112325973-091b9c00-8cac-11eb-85e3-445db65f2136.png)

![adeddfunds](https://user-images.githubusercontent.com/158833/112331536-e6d84d00-8cb0-11eb-90b5-e8fcb908024c.png)

**Comment by alanna** [comment]
> to me at least, that's also the use case we have here

@BenJam it's a similar concept but not the same. That link to the docs refers to a feature for *Hosts* to correctly mirror amounts on the platform to match realities in their bank account without actually moving money anywhere. This issue is about *Collectives* adding money to their own budget, and moving the money to back that credit to the Host's bank account. 

Maybe that's what you meant already. The screenshots above are exactly what I had in mind, as long as the "payment" step also occurs in between, *without debiting the Collective's balance only crediting it*. This is a bit complex because the flow would look almost identical if the Collective was contributing to another Collective instead of itself. They would select the payer Collective's profile in the "contribute as" step, and then the system would debit their balance and credit the payee Collective. But in the use case of giving money to themselves, they need to only credit.

**Comment by BenJam** [comment]
> Maybe that's what you meant already

whether I did or not I'm a play on 😅

**Comment by znarf** [comment]
Ok, so we should make sure Collectives can contribute to themselves and in this case, by convention, we should only insert a CREDIT transaction.

**Comment by alanna** [comment]
@piamancini [see my comment where I explain this](https://github.com/opencollective/opencollective/issues/4109#issuecomment-805200541). It's not printing money - the money is actually being paid to the host bank account at the time the contribution is made. 

I see what you're saying about the source of funds should be captured as the actual owner of the bank account or credit card behind the contribution, but we don't enforce that at all for organization profiles, so why is this different? I can make a contribution using my personal credit card and make the source a new Org profile for a company that doesn't even exist. That's essentially what users are doing to route around this right now, creating a dummy Org profile with a variation of the Collective name. If we're going to actually enforce matching the real source of funds to the correct profile of the owner of that bank account, we should implement #3340 for contributions as well as payees.

Anyway, this feature is not a big priority and there is a workaround already (dummy profiles) so I'm not pushing for it to be prioritised, I'm just pointing out that our approach is not consistent.

**Comment by alanna** [comment]
> If users are creating dummy profiles, we then need to look at them and report the source of the funds as the person who used the credit card. This is extremely inconvenient for them and it can result in something quite problematic. I don't think we should encourage this behaviour at all.

Yes this is happening because if a group has a paypal account or a crowdfunding campaign or a cash box where they've been raising money, and are now onboarding to a Collective and transferring in those previously raised funds, they don't want their personal name showing up, because it's really the group's money, not them personally making a contribution (if they used their own profile it would look like they personally are the biggest contributor). So they create a dummy profile representing the group, and that shows as the contributor. 

If this is an issue for compliance, then we really need to implement #3340 and #3689 to ensure we are capturing the correct owner of the source bank account, while also allowing users to attribute the contribution to what they want to show on their page (e.g. XYZ community or ABC event, not the owner of the account's name). This is not just the case for this relatively uncommon situation I started this issue for - it's super common that the profile and bank account owner IDs do not match, for a range of reasons.

**Comment by BenJam** [comment]
> we need to always have a source of the funds for every dollar that is added to the platform

> @BenJam in your example you should add the funds as octobox ltd

Closing in place of https://github.com/opencollective/opencollective/issues/4445
