### ISSUE TITLE
Allow deeplinking to specific transactions

### ISSUE THREAD

**Issue by patcon** [opencollective/opencollective#411]
https://opencollective.com/civicinnovationnetwork/transactions

In sharing how the platform works, I was aspiring to link to a specific funding transaction on the above page. This would have made it a little simpler to share details about the collective. It would be amazing if we could deeplink to items, even those past the first page of results

**Comment by piamancini** [comment]
thanks @patcon! I'll label this enhancement and close it for the moment, since we have a long list of priorities to go through first.
