### ISSUE TITLE
Reveal host fee % even if host is not open to applications

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4110]
Currently if a host is not accepting applications, we don't show their host fee or their terms. Is there a reason for this? For transparency and also to serve the people who are in that community I think we should show it.

![Screen Shot 2021-03-23 at 2 11 19 PM](https://user-images.githubusercontent.com/5498878/112077594-ba093480-8be1-11eb-9b59-9fc22d507676.png)

vs

![Screen Shot 2021-03-23 at 2 12 30 PM](https://user-images.githubusercontent.com/5498878/112077649-d311e580-8be1-11eb-9f15-cea921a806c8.png)

**Comment by Betree** [comment]
It seems that this was implemented like that initially, but I can't find any good reason for this. Will update

**Comment by znarf** [comment]
Make sense to check `isHost` instead of `canApply`.

I think we might have wanted to avoid displaying TOS (terms of fiscal sponsorship) if the host was not open to applications.

Also, we need to make sure that it's not displayed for Self Hosted Collectives.

**Comment by Betree** [comment]
> we don't show their host fee or their terms. Is there a reason for this? For transparency and also to serve the people who are in that community I think we should show it.

According to @alanna's description above, we should display the TOS. I also think that if any hosted collective wants to check them it's a good thing to have them accessible.

**Comment by znarf** [comment]
@Betree ok!
