### ISSUE TITLE
Inconsistency in the Add Funds Modal

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4111]
**Describe the bug**

I think there's an inconsistency in the Add Funds modal in the collective page and in the transaction/expenses pages. For example the collective home page the Add funds modal looks like this, 

![Screenshot_2021-03-23 Agora Collective - New - Open Collective](https://user-images.githubusercontent.com/12435965/112172156-b493f600-8bb1-11eb-83cf-bee82c7d08b4.png)

Whereas in the transaction and expenses pages it looks like this,

![Screenshot_2021-03-23 Agora Collective - New · Expenses - Open Collective](https://user-images.githubusercontent.com/12435965/112172351-e0af7700-8bb1-11eb-9828-3b2aac77d862.png)

Notice that the host fee checkbox is missing in the transactions and expenses pages. 

**To Reproduce**
1. Go to any collective page where you are the collective admin.
2. Click on the action menu and `Add Funds`.
3. Do the same in the transaction page for the collective. 

**Expected behavior**

My understanding is that the modal should show the same design everywhere it is shown within the collective. Let me know otherwise. 🤔

**Comment by SudharakaP** [comment]
@piamancini : Ops, I somehow missed this one. Will work on it tomorrow. 😄

**Comment by znarf** [comment]
Looks like `host.plan.hostFees` might be unavailable, preventing to compute `canAddHostFee` properly.  So might just be a matter of making sure the field is asked in a GraphQL query.
