### ISSUE TITLE
Cannot checkout $0 event ticket

### ISSUE THREAD

**Issue by benhylau** [opencollective/opencollective#4116]
**Describe the bug**
Unable to check out a $0 event ticket.

**To Reproduce**
1. Go to https://opencollective.com/compost/events/compost-issue-01-release-party-ecbefdad/order/26664
2. Click on 'Your info'
3. Click on 'Make contribution'

**Expected behavior**
Should work like other paid tickets.

**Screenshots**
<img width="988" alt="Screen Shot 2021-03-24 at 3 23 15 PM" src="https://user-images.githubusercontent.com/2261308/112332335-f1e3ab00-8cb9-11eb-8c65-924daa7cf5c2.png">

**Desktop (please complete the following information):**
 - Firefox on Mac

**Additional context**
Tried changing a bunch of settings but it seems the $0 is what it comes down to.

**Comment by Betree** [comment]
Hi @benhylau, thanks for reporting this issue - there was indeed a bug. We've merged a fix that will be deployed in the next few hours.
