### ISSUE TITLE
Inconsistency in Pricing Details in Documentation Pages

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4123]
**Describe the Issue**

There was a discussion in slack about a inconsistency in pricing in two of our doc pages. 

>On the New Pricing page, it says that Platform form fees (on incoming contributions) and Payout fees (on outgoing payments) are free, except for credit card payments.BUT, on the more detailed Pricing pages, it says that after $1K in funds received thru other channels or bank transfer payments, then there will be an ongoing $10 monthly charge.We are small organization, but sometimes get one-time donations over $1K.   Our average monthly income is under $1K/month.  What would our pricing be?

The pages in question are,

https://docs.opencollective.com/help/about/pricing

and, 

https://opencollective.com/pricing?tab=organization

The original discussion can be found at,

https://opencollective.slack.com/archives/C0HSLRNVC/p1614554323031400

cc: @piamancini @alanna : Including you both as I see you've altered these page info.

**Comment by alanna** [comment]
OK! That's fine. We can just use the documentation tag to track them in the main repo.

**Comment by SudharakaP** [comment]
@alanna @shannondwray : Thanks much for looking into this. I see now that the [pricing page in the docs](https://docs.opencollective.com/help/about/pricing) is updated to link to the [other page in the website](https://opencollective.com/pricing?tab=organization). Therefore I would consider this issue to be solved and the discrepancy is no longer there. 😄 😄
