### ISSUE TITLE
Can not clone opencollective-pdf on windows

### ISSUE THREAD

**Issue by uchar** [opencollective/opencollective#4126]
**Describe the bug**

Some folders in opencollective-pdf contain windows special character ( : ), which cause errors when trying to clone them on windows

**To Reproduce**
1. In windows use this command : 
``` git clone https://github.com/uchar/opencollective-pdf.git .```
2. This would generate an error : 
```
error: invalid path 'pages/[collectiveSlug]/transactions/[:uuid]/[filename].js'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Expected behavior**
Running code on windows should work fine, this issue can fix by renaming folders with special characters like `:`

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by SudharakaP** [comment]
@uchar: My understanding is that for most development people use Linux based systems and we don't test the build on Windows machines. I've used Windows in the past for development and had numerous problems like this unfortunately. For this issue, if we were to remove this kinda thing just to support Windows, it will be hard as we will probably be giving up on many NextJS features; https://nextjs.org/docs/routing/dynamic-routes#catch-all-routes as there might be other special characters not supported as well (such as the dot(`.`)) 😄 

My suggestion therefore is to use [WSL (Windows Subsystem for Linux)](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux). I had some success with it back in the day. 😄

**Comment by Betree** [comment]
It seems that this was [discussed](https://github.com/vercel/next.js/issues/7607#issuecomment-503485919) at the time, and according to https://nextjs.org/docs/routing/introduction we don't have to use `:` for route parameters. So feel free to update the routes with `[:uuid]` -> `[uuid]` @uchar. @SudharakaP is right that we rarely test projects on Windows so we can only provide limited support. We do recommend using a Unix machine, but PRs to make the dev env compatible with Windows are welcome :slightly_smiling_face:

**Comment by SudharakaP** [comment]
@uchar : I've created a PR for this at https://github.com/opencollective/opencollective-pdf/pull/639. I don't have a windows machine so cannot test this, so if you could verify it would be greatly appreciated. 😄 

cc: @Betree
