### ISSUE TITLE
Change default filtering from 'All Contributions' to 'Hosted Collectives' on Host pages

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4128]
A major function of a Fiscal Host page is to show what kind of groups they host and the Collectives under their umbrella. Right now hosted Collectives show up under "All Contributions" combined with Events and Collectives the Host org has financially contributed to, and it's cluttered and confusing. I think an easy fix for this would just be for the list to default to the "Hosted Collectives" filter for Host pages, and then users can click the other filter buttons if they want.

**Comment by patcon** [comment]
> I think an easy fix for this would just be for the list to default to the "Hosted Collectives" filter for Host pages

This 100% addresses my concern. Thanks @alanna!

**Comment by Betree** [comment]
Related: https://github.com/opencollective/opencollective/issues/3788
