### ISSUE TITLE
[discussion] Should we prioritise improving events?

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4129]
This is a discussion intended to feed into the next quarterly roadmap conversation.

Events is something we only ever implemented a basic version of and haven't had capacity to improve. But it's a feature that's used a lot and appreciated a lot by users. There is basically no one else combining events functionality with any of the stuff we offer: transparent budget, expenses against the event, fiscal hosting, crowdfunding. It's a really unique and valuable thing.

If we decide to work on it, there is so much low hanging fruit. We already surface the events feature prominently in the interface and events are the first impression a lot of people have of the OC platform as event attendees. But there are many things that are not great about the user experience, and many missing features (many pretty simple ones).

So, I'm not sure if now is the right time to take on improving events, but I think it's worth considering. If we go for it, I have lots of ideas and would love to work on it with design and gather user feedback.

**Comment by Betree** [comment]
I agree that we have many low-hanging fruits for events. Dedicating a day or two to work on them could greatly benefit users.

I've updated https://github.com/opencollective/opencollective/projects/29 to add all the event's issues that I found. A good way to prioritize this as a project would be to list what we want to achieve, to have a clear estimate of how long it will take. I suggest that we move all the issues that we want to tackle with this project into the "To do" column.

**Comment by BenJam** [comment]
I would just like to say that I am :100: for issues like this re. roadmapping and planning as much as features and development. Thank you.

**Comment by alanna** [comment]
Adding a comment I made on #2081 

> I think we should take a giant step back and realise that the functionality of Projects and Events is overlapping, and we should properly understand their functions and design a more elegant approach. Related: #4075 #4074

**Comment by alanna** [comment]
@BenJam should I turn this into a Project issue?

**Comment by alanna** [comment]
Closing in favor of #4280
