### ISSUE TITLE
[bug] Clarify that receipt images are mandatory for submitting expenses

### ISSUE THREAD

**Issue by patcon** [opencollective/opencollective#413]
Slack context: https://opencollective.slack.com/archives/C6JTTA4SK/p1505761507000407

When submitted an expense without uploading an image or PDF, the submit button appears to be clickable. But when clicked, nothing happens, and no error is surfaced.

I would expect some error handling or form validation exposure to happen here, or else it feels like the form just broke. The simplest possible solution would just to add some exposure of what the "required fields" are.

Thanks! Y'all are great!

**Comment by piamancini** [comment]
@patcon system should give you an alert when you hit submit without a receipt, definitely. 
@asood123 can you put this on your list for when we see expenses?

**Comment by piamancini** [comment]
closing for the moment, we'll add it to the tasks for next release.
