### ISSUE TITLE
View Events linking to the contribution flow

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4130]
**Describe the bug**
If you go to a Collective page's Events section and click `View All Events` it just dumps you in the generic contribution flow, instead of showing you a page about Events. The same thing happens if you go to https://opencollective.com/slug/events.

**Expected behavior**
Either a dedicated Events page similar to the Updates page, where you can see past Events and create new ones, or jumping to the Events section of the main Collective page. Or else remove the `View All Events` button and make /events a 404 or just default to the main Collective page.

**Comment by Betree** [comment]
The button doesn't exactly redirect to the contribution flow but to the contribute page (ie. https://staging.opencollective.com/captainfact_io/contribute) where we show all tiers and all events. You're right that https://staging.opencollective.com/captainfact_io/events does redirects to the contribution flow (it acts as `/donate`), that's a problem.

Here's a proposal for an easy fix:
- [ ] Link `View all events` button to `/:slug/events`
- [ ] From the `/:slug/events` route, render the contribute page
- [ ] In the contribute page, if URL is `/:slug/events`, filter to display only events (filtering can be done in the frontend)

**Comment by Betree** [comment]
These specs are actually part of https://github.com/opencollective/opencollective/issues/3835

**Comment by Betree** [comment]
Resolved in https://github.com/opencollective/opencollective/issues/3835
