### ISSUE TITLE
Approve button should change after loading

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4132]
When approving an expense, you click the button and it changes to a loading symbol. At the end, it should change to the next state (like turn to the green pay button) but instead it reverts to the previous state for some seconds and only changes once the page reloads. This is confusing UX - I thought the approval had failed.

https://user-images.githubusercontent.com/5498878/112904440-74022280-9145-11eb-9112-208ea8999b6d.mp4

**Comment by Betree** [comment]
It seems like a delay between Apollo's query result and cache refresh. I agree that we should try to make the transition faster and/or keep showing the loading spinner until the refreshed data is there.

**Comment by alanna** [comment]
+1

**Comment by Betree** [comment]
@alinamanko You're right that it seems to be resolved in the expenses list and on the expense page. The expense modal however still seems to be affected:
![Peek 2021-05-11 16-43](https://user-images.githubusercontent.com/1556356/117835315-2c100880-b278-11eb-9b3a-37e7bb49798c.gif)
