### ISSUE TITLE
Transactions missing when jumping to budget section

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4133]
Sometimes when I load a page and click `Budget` in the menu to jump to that section, at first it shows no transactions, even if there are transactions. I have seen this a few times but I can't reproduce reliably. If I refresh the page, the transactions show.

<img width="1134" alt="Screen Shot 2021-03-30 at 9 45 31 PM" src="https://user-images.githubusercontent.com/5498878/112961169-9b86d880-91a1-11eb-815b-9b49171aa198.png">

**Comment by Betree** [comment]
Seen this one too, I'll push a quick fix
