### ISSUE TITLE
Frontend logs poluted by "Module did not self-register"

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4139]
In production, our frontend logs are currently hard to read because of this error.

> Error: Module did not self-register: '/app/.heroku/heroku-nodejs-plugin/heroku-nodejs-plugin.node'.

**Comment by Betree** [comment]
According to https://github.com/heroku/heroku-nodejs-plugin/issues/13#issue-519401318, the "best solution" currently proposed is to disable node metrics: https://github.com/heroku/heroku-nodejs-plugin/issues/13

**Comment by znarf** [comment]
Thank you for finding this, I just did this: `heroku labs:disable nodejs-language-metrics -a oc-prod-frontend`

**Comment by znarf** [comment]
@Betree it didn't work it seems.

**Comment by Betree** [comment]
As recommended in https://github.com/heroku/heroku-buildpack-nodejs/issues/727#issuecomment-550975119, I'm not trying to disable Node language metrics to see if that helps

**Comment by Betree** [comment]
On staging these errors are not showing up and everything is disabled

**Comment by znarf** [comment]
Great, let's do this in production. Node metrics are useful but not critical at all.

**Comment by Betree** [comment]
Logging already stopped on Papertrail so it's hard to tell from there, but I can't see the error with `heroku logs` so it might have worked

**Comment by Betree** [comment]
Adding https://github.com/opencollective/opencollective/issues/4139#issuecomment-816483409 did the job :tada:
