### ISSUE TITLE
Ensure sticky header on collective page doesn't push layout

### ISSUE THREAD

**Issue by patcon** [opencollective/opencollective#414]
Noticed a flicker in the sticky header when the page was scrolled to just the right point. On further investigation, it seems that the jumps in the page layout when the sticky header activated might also be an anti-pattern.

Related: https://github.com/captivationsoftware/react-sticky/issues/151#issuecomment-279160882

The GIF through the link provides a great example of an alternative.

I'd say this might be a candidate for the `easy` label, since there's such a clear sample to work from :)

**Comment by piamancini** [comment]
@patcon where did you see this?

**Comment by patcon** [comment]
Ah, this was on the v1 collective page, so no longer relevant!
