### ISSUE TITLE
Collective background image: responsive cropper

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4140]
# Problem 
Multiple collectives end up with Hero images looking like this. This is because they're updating their background image on small screens, and the results don't look good when expanded.

![image](https://user-images.githubusercontent.com/1556356/113267992-38975d80-92d7-11eb-8d5e-d0b0e1a63a7d.png)

# Proposal

Back in the time, we designed a modal to edit the background image with a miniature preview. While inline editing arguably provides a nicer experience, this modal would resolve our problem. We should implement the design proposed below, with the addition of the background mask (the white curve with bubbles) to make sure users have an accurate preview of how it will look like.

See design: https://www.figma.com/file/9Iq3vBOmZ2EuOacXEYD5yK/DS-03-Global-Components?node-id=6542%3A45608

![image](https://user-images.githubusercontent.com/1556356/113268386-9a57c780-92d7-11eb-81ba-a06dc6dd775b.png)

# Tags

Crop, resize, background image

**Comment by Betree** [comment]
Many collectives still end up with badly cropped/positioned hero images. I would love to consider this issue for prioritization (along with https://github.com/opencollective/opencollective/issues/2709) next sprint or so.

**Comment by BenJam** [comment]
? possible plan for this week

- [ ] reimplement modal in a more responsive way

**Comment by Betree** [comment]
@opencollective/design The design above is lacking a button to upload a new image. I'll improvise, but any quick suggestion would be welcome.

**Comment by Memo-Es** [comment]
@Betree I seized the opportunity and started to update this entry of the `Global Components` file of the DS. I updated the modal with 2 states, empty and edit.

<img width="1168" alt="Screen Shot on 2021-12-08 at 15-26-48" src="https://user-images.githubusercontent.com/49539954/145287084-63de0ed6-300f-4566-b04e-32899a6ff62d.png">

Let me know what you think!

**Comment by Betree** [comment]
Perfect, thank you @Memo-Es!
