### ISSUE TITLE
Unable to approve platform settlement expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4146]
When I try to approve this:
https://opencollective.com/foundation/expenses/37388

I get this:
<img width="783" alt="Screen Shot 2021-04-02 at 4 38 03 PM" src="https://user-images.githubusercontent.com/5498878/113377868-03236a80-93d2-11eb-922b-a0983cd94007.png">

**Comment by kewitz** [comment]
Hi @alanna, I commented on the Expense regarding its temporary negative value. This was already fixed, sorry about the confusion.
