### ISSUE TITLE
Bank details not displaying on screen for some users

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4147]
A user did a bank transfer contribution to https://opencollective.com/ehf-community. At the end, he saw the on screen transfer details, but the {account} variable was not rendering. When he got the email notification, the account info was shown as expected.

<img width="542" alt="Screen Shot 2021-04-02 at 5 08 49 PM" src="https://user-images.githubusercontent.com/5498878/113379694-aa0a0580-93d6-11eb-9abf-860217e30bd2.png">

I just tested this myself and I'm not able to reproduce. I tried in a couple hosts and in all cases it's rendering correctly for me.

**Comment by znarf** [comment]
The issue was addressed in https://github.com/opencollective/opencollective-api/pull/5982
