### ISSUE TITLE
Create `first-timers-only` label

### ISSUE THREAD

**Issue by patcon** [opencollective/opencollective#415]
http://www.firsttimersonly.com/

I particularly love this label, as it communicates not only that something is easy, but that it should be left for new contributors. A clear and easy first win is really great for pulling people in.

As stated on the page linked above:

> If you are an OSS project owner, then consider marking a few open issues with the label first-timers-only. The `first-timers-only` label explicitly announces:
>
> > I’m willing to hold your hand so you can make your first PR. This issue is rather a bit easier than normal. And anyone who’s already contributed to open source isn’t allowed to touch this one!

**Comment by piamancini** [comment]
We now have a `good-first-issue` label for first time contributors.
