### ISSUE TITLE
Replace "Backers" by "Financial contributors" in tweets

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4151]
@alanna is this something we should do?

![image](https://user-images.githubusercontent.com/1556356/113404664-cf801a80-93a8-11eb-8ebf-e0423cc5ec52.png)

**Comment by alanna** [comment]
I thought about changing this myself but I wasn't sure if `backers` still referred to a specific kind of tier in the code based on the old way we used to do things. If it's counting all financial contributors, then yes we should change it.
