### ISSUE TITLE
Long descriptions iframes: allow Anchor.fm

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4152]
Depends on https://github.com/opencollective/opencollective/issues/2043
User-requested feature: https://opencollective.slack.com/archives/C6JTTA4SK/p1617357672033800

This would be especially useful for podcasts.

**Example**
- https://anchor.fm/futurediaries/embed/episodes/A-podcast-from-the-future-eorhrm
```html
<iframe src="https://anchor.fm/futurediaries/embed/episodes/A-podcast-from-the-future-eorhrm" height="102px" width="400px" frameborder="0" scrolling="no"></iframe>
```

**Comment by SudharakaP** [comment]
@Betree : Will take this one if no objections, since I already worked on the previous related PR. 😄

**Comment by SudharakaP** [comment]
I've added the support for this; please merge after, https://github.com/opencollective/opencollective/issues/2043. And let me know if you see any issues. 😄
