### ISSUE TITLE
Resetting search on financial contributions tab on host dashboard breaks it

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4154]
**Describe the bug**
After resetting search filters you end up with a `not found`

The URL ends up with https://opencollective.com/host.dashboard?searchTerm=&hostCollectiveSlug=foundation&view=donations instead of the expected https://opencollective.com/foundation/dashboard/donations

**To Reproduce**
1. Go to host dashboard
2. Go to financial contributions
3. Do a search
4. Click `reset` to clear search
5. See `not found` error

**Expected behavior**
It should take you back to the main view of that tab with no search filters

**Comment by Betree** [comment]
Probably related to https://github.com/opencollective/opencollective-frontend/pull/5855
