### ISSUE TITLE
Receipt showing wrong currency

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4156]
**Describe the bug**
My NZ based organization has a recurring contribution to an OCEU Collective for EUR5/month. However, the receipt uses the $ symbol and doesn't specify currency. This is dangerous in two ways: the amounts I'm using this receipt to document for my tax reporting will not match the conversion rates to the wrong currency, and also my country uses the $ symbol as many do, so it's further ambiguous whether this is wrongly claiming to be NZD or USD.

**To Reproduce**
1. Make a contribution to a Collective in another currency
2. Download the receipt
3. See the $ symbol

**Expected behavior**
It should display both the symbol and the currency ID like USD, EUR, NZD.

**Screenshots**
<img width="854" alt="Screen Shot 2021-04-06 at 1 36 59 PM" src="https://user-images.githubusercontent.com/5498878/113646584-32d9b780-96dd-11eb-9209-525e5a26973b.png">

**Comment by Betree** [comment]
@alanna I've deployed a potential fix for this problem, let me know if you still get this issue when downloading the receipt
