### ISSUE TITLE
Contribution cancellation notification showing wrong amount

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4157]
I cancelled a recurring contribution that was for $25+$2.50 tip, but it came through as $28, which is neither $25 or $27.50, the two totals I could logically see this having.

![Screenshot_20210406-160819](https://user-images.githubusercontent.com/5498878/113663676-8f010380-96fe-11eb-80d6-53a24c8f67f8.png)

**Comment by znarf** [comment]
I think it's because it's rounded. We should definitely never round amounts like this.

**Comment by Betree** [comment]
In https://github.com/opencollective/opencollective-api/pull/6096, I'm making a change to not round amounts by default in emails (except for zero decimals currencies).
