### ISSUE TITLE
Edit recurring contributions: shrinked credit card input

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4158]
**Describe the bug**
This was reported in the past by @znarf.

![image](https://user-images.githubusercontent.com/1556356/113678412-e2536180-96be-11eb-9986-8f977b167e88.png)

**Expected behavior**

Should display the full input. We can eventually achieve that by having a min-width of 275px on the card.

![image](https://user-images.githubusercontent.com/1556356/113678260-bd5eee80-96be-11eb-8a48-891589c699a9.png)

**Comment by znarf** [comment]
The original issue was https://github.com/opencollective/opencollective/issues/4059

**Comment by Betree** [comment]
@znarf thanks for sharing, I thought we only reported this orally
