### ISSUE TITLE
No $0 transactions for platform settlement, and wrong anyway?

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4162]
<img width="1167" alt="Screen Shot 2021-04-07 at 8 46 37 AM" src="https://user-images.githubusercontent.com/5498878/113776275-db3f5880-977d-11eb-8a35-39497bc803e3.png">

Why is this $0 platform fees and tip transaction showing up like this? If it's 0$, just don't have a transaction. It looks like an error.

Also, I'm sure there were in fact platform fees and tips charged to this host, OCNZ, in March.

**Comment by piamancini** [comment]
@kewitz cc
