### ISSUE TITLE
Prevent accidental scrolling changing tier goal amount

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4164]
[This goal](https://opencollective.com/ehf-community/contribute/huddles-23081) was $2500. It's mysteriously changed itself to $2499.97, though no one has intentionally edited it. I can't work out if this is a code bug, or a UI bug (e.g. if someone scrolls down on the tier settings page this could happen).

**Comment by Betree** [comment]
I see the correct value there. 

![image](https://user-images.githubusercontent.com/1556356/113824259-db405800-977f-11eb-90ff-0afc12651863.png)

> if someone scrolls down on the tier settings page this could happen

This is very likely. We've prevented this behavior on most of the amount inputs on the website, but you'll still get it on the "Edit tiers" page. It's easy to unwillingly scroll in that input. Maybe we can make this issue about fixing that?
