### ISSUE TITLE
Make list of webhook actions human readable

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4170]
When setting up a new webhook, you choose from a big list of code-looking options that don't indicate much about when they mean.

<img width="705" alt="Screen Shot 2021-04-08 at 8 31 31 PM" src="https://user-images.githubusercontent.com/5498878/113994547-96b0db80-98a9-11eb-960a-86d9433b9774.png">

We need to either:
* Document what each one of these does on the integrations documentation page
or
* Change the text that appears for each into something human readable that lets people know what each one means in the list

**Comment by Betree** [comment]
All these values should be internationalized, with a helper like `i18nNotificationActivity` to display pretty names. After that, having some optional descriptions to display in the list and below the select could be nice. Example:

Select:
- All
- Expense deleted
- Transaction created - Triggered whenever you receive a new financial contribution or an expense gets paid
- ...

**Comment by Betree** [comment]
I'm pushing an update in https://github.com/opencollective/opencollective-frontend/pull/6324 to use proper labels (with i18n) for event types. After that, we can eventually add descriptions for events that are not obvious.
