### ISSUE TITLE
no-reply notifications should come from Open Collective

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4175]
Here's how an email from no-reply@opencollective.com looks in my inbox:
![Screen Shot 2021-04-09 at 9 28 22 AM](https://user-images.githubusercontent.com/5498878/114099013-4459d400-9916-11eb-8ef9-3443b55af173.png)

It should be from Open Collective not "No-Reply"

**Comment by Betree** [comment]
To be confirmed, but I think we can solve that by replacing all:
```diff es6
- from = 'no-reply@opencollective.com';
+ from = 'Open Collective <no-reply@opencollective.com>';
```

**Comment by Betree** [comment]
I can confirm that the fixed worked: 
![image](https://user-images.githubusercontent.com/1556356/115220095-746c5880-a108-11eb-9162-6d79174c3e06.png)
