### ISSUE TITLE
Support Metrics Report March 2021

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#4178]
### Support Metrics Report March 2021

This report looks at the trends around support to help us better understand areas we need to improve and highlight key topics for the month. 

**Tickets received** 

![Capture](https://user-images.githubusercontent.com/57156267/114323442-54252280-9b79-11eb-9c23-d815e61f06ae.JPG)

The number of tickets received increased by 11% from 465 in February to 517 in March. By removing blank tickets, the rise during March was a little more significant in comparison (~19%) - 330 tickets compared to 277 in February. [You can find the detailed listings here.](https://docs.google.com/spreadsheets/d/1pO6FQzpxUXpBms43J94rxhX4toU2IP3S/edit#gid=255610818)

![Capture](https://user-images.githubusercontent.com/57156267/114323485-8cc4fc00-9b79-11eb-9673-69c1de9c3670.JPG)

**Trends and Recommendations**
After removing irrelevant tickets, we had 330 that required support attention. It is worth noting the following areas:

**Expenses**

Questions related to expenses continue to be our biggest ticket item. The tickets associated with user responding directly to support rather than in the expense thread which is related to collectives under The Social Change Nest continued to be the key driver here. This problem was resolved during March and as of April these no longer arrive at support as users are directed to the expense form. 

Following our update last month on the topic of cash reimbursements for some of the collectives under the Open Collective Foundation umbrella, we wanted to keep you on where it is at. We plan to have a formal update on this next month after consultation with the lawyers, and in the meantime, [you can review the Loomio thread we started on this topic.](https://www.loomio.org/d/KohyP38n/direct-cash-assistance) 

**FUNDOSS**

Given the recent update on the FUNDOSS front, there was a lot of interest received from folks wanting to get involved. 
 
**Grants**

During March there were additional grants received by collectives under Open Collective Foundation. The increase in tickets received has to do with new applications and additional follow-ups to help us in assigning funds received through charitable groups such as ACTBlue. 

**Onboarding**

Onboarding related questions are still some of the common ones we receive, however, there seems to be a drop in new collectives onboarded with OCF, there is a big increase in the number of new groups joining OSC. Here is how it was distributed:

We approved 17 new applications for OCF compared with 29 in February.

For OSC -  75 new collectives were approved during March compared to 35 in February. 

**Other things to note**

- We have a number of corporate giving matching programs with OCF, most noticeably through Benevity. The process is we receive a monthly report with the matching contributions made and a bulk payment to the Foundation bank account. Lately, we note a few instances where the names of the initiatives the money should be allocated to is not given and in instances where original contributions were either made as guest or incognito contributions, it is difficult to find how to assign the funds. It may be something for us to consider when we encounter questions from groups interested in joining in. However, there is also a likelihood that any new contributions matches are not something we get notified on. @kaylarep  - would love to see if you have anything to add in this space. 
- Another important topic worth mentioning in the Foundation space, is that we started noticing a few instances where groups receive contributions through other sources than Open Collective (e.g. Patreon, Venmo) and these sometimes listed as avenues for folks to support them. We included a section on the importance of getting all the funds flowing through our platform [in a recent blog post](https://blog.opencollective.com/open-collective-foundation-update-march-2021/). We are currently seeking legal advice on this area and most likely need to contact such groups directly to address those specific cases.

**Comment by alanna** [comment]
It will be very interesting to see if that SCA expenses stat drops off next month. If not we'll need to figure out what else we can do to make sure inquiries to hosts go to the right place.

**Comment by alinamanko** [comment]
@alanna I can confirm this won't be coming up during April. From the last 10 days or so this has no longer been an issue

**Comment by kaylarep** [comment]
@alinamanko Would you be able to update [this doc](https://docs.google.com/document/d/139KBR64W3XRveg4-ef2YU8lbETOeVgkDgoa_CGg9Kb0/edit?usp=sharing) for how to process ActBlue?

Or if you'd prefer, we can schedule a meeting to go over it/you can record your process and I'll transcribe it in. Let me know!

**Comment by OpenCollectiveTest** [comment]
@kaylarep I updated the process doc for you. There is not so much there so let me know if there is anything else you'd like me to add. 

As for Benevity, I don't think we should remove them as a lot of groups have consistent level of support this way. This is something to be aware of and monitor and see if it keeps being a problem. In the 90+% it works, I think it is a very good solution. It was just something I wanted to bring to the team attention as it may grow to be a bigger problem in the future and I am not sure how the onboarding side of things works and how much we are involved in it

**Comment by kaylarep** [comment]
> @kaylarep I updated the process doc for you. There is not so much there so let me know if there is anything else you'd like me to add.
> 
> As for Benevity, I don't think we should remove them as a lot of groups have consistent level of support this way. This is something to be aware of and monitor and see if it keeps being a problem. In the 90+% it works, I think it is a very good solution. It was just something I wanted to bring to the team attention as it may grow to be a bigger problem in the future and I am not sure how the onboarding side of things works and how much w

**Comment by kaylarep** [comment]
Thanks @alinamanko ! I left you a comment/question in the doc

This is the current onboarding information for these: https://docs.opencollective.foundation/how-it-works/third-party-fundraising-tools-and-benefits#third-party-tools

If you have any comments/suggestions/contributions to streamline/clarify, let me know
