### ISSUE TITLE
Deactivate/Delete old user accounts for Moritz

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#418]
Moritz Dausinger would like to know if we can delete his previous accounts and leave the one where he is contributing $100 to Tabula. 

**More info in his email, Aseem has been talking with him before.**

**Comment by piamancini** [comment]
@asood123 are you following this issue?

**Comment by nicobarretoOC** [comment]
I have not heard from Moritz yet. Let me know how the status is going.
