### ISSUE TITLE
Make Hero's background image unselectable

### ISSUE THREAD

**Issue by snitin315** [opencollective/opencollective#4181]
**Describe the bug**

Primary color changes while enabling primary navbar

**To Reproduce**

https://user-images.githubusercontent.com/46647141/114393033-337bbd80-9bb7-11eb-896e-3aca07d28389.mp4

**Expected behavior**

**Desktop (please complete the following information):**
Any

**Additional context**

It doesn't seem to be happening always.

**Comment by Betree** [comment]
Strange bug! Which OS/Browser is this?

If you're using an image as background, my guess would be that this image gets selected when you double-click on the menu - making it appear with a colored overlay. If that's the case, playing with `user-select` on the image should do the job.

**Comment by snitin315** [comment]
I am using macOS and chrome. 
Works fine on safari.
