### ISSUE TITLE
Organizations used as ADMINs of collectives

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4184]
We have some cases where ORGANIZATIONs are being used as ADMINs of collectives. That sounds like something we should not allow as our permission system is not checking for that. It also looks like we stopped supporting that in 2019.

The following query returns 22 entries:

```sql
SELECT c.slug, mc."type", c."type", m."createdAt" 
FROM "Members" m 
INNER JOIN "Collectives" mc ON m."MemberCollectiveId" = mc.id 
INNER JOIN "Collectives" c ON m."CollectiveId" = c.id
AND m."role" = 'ADMIN'
AND mc."type" != 'USER'
AND c."deletedAt" IS NULL
AND m."deletedAt" IS NULL
ORDER BY m."createdAt" DESC
```

|  collective                                   | member type              |       collective type       |            created at         | 
|-------------------------------------|--------------|--------------|---------------------| 
| google                              | ORGANIZATION | ORGANIZATION |                     | 
| google-open-source                  | ORGANIZATION | ORGANIZATION | 2019-11-30 01:00:00 | 
| incognito-fd2538de                  | ORGANIZATION | USER         | 2019-09-16 11:30:14 | 
| ptzoptics                           | ORGANIZATION | ORGANIZATION | 2019-03-05 01:00:00 | 
| west-norfolk-insurance-services-ltd | ORGANIZATION | ORGANIZATION | 2018-07-31 11:16:57 | 
| openmiami-host                      | COLLECTIVE   | ORGANIZATION | 2018-05-14 02:00:00 | 
| codeformiami1                       | ORGANIZATION | ORGANIZATION | 2017-11-19 23:26:45 | 
| calderbootstrap                     | ORGANIZATION | COLLECTIVE   | 2017-10-23 12:29:29 | 
| gorge-genie                         | ORGANIZATION | COLLECTIVE   | 2017-03-12 08:00:26 | 
| wwcodepune                          | ORGANIZATION | COLLECTIVE   | 2017-02-21 21:16:59 | 
| wwcodevancouver                     | ORGANIZATION | COLLECTIVE   | 2017-02-21 20:45:19 | 
| wwcoderaleigh                       | ORGANIZATION | COLLECTIVE   | 2017-02-21 20:39:46 | 
| wwcodesandiego                      | ORGANIZATION | COLLECTIVE   | 2017-02-21 20:34:47 | 
| wwcodecleveland                     | ORGANIZATION | COLLECTIVE   | 2017-02-21 20:25:28 | 
| wwcodesingapore                     | ORGANIZATION | COLLECTIVE   | 2017-02-21 20:13:03 | 
| wwcodehuntsville                    | ORGANIZATION | COLLECTIVE   | 2017-02-21 20:02:21 | 
| wwcodephiladelphia                  | ORGANIZATION | COLLECTIVE   | 2017-02-21 19:49:14 | 
| wwcodefortcollins                   | ORGANIZATION | COLLECTIVE   | 2017-02-21 19:35:34 | 
| wwcodecincinnati                    | ORGANIZATION | COLLECTIVE   | 2017-02-21 19:11:30 | 
| gdljs                               | ORGANIZATION | COLLECTIVE   | 2016-08-09 02:00:00 | 
| hackshackersbrussels                | ORGANIZATION | COLLECTIVE   | 2016-02-01 01:00:00 | 
| partidodigital                      | ORGANIZATION | COLLECTIVE   | 2013-10-30 01:00:00 | 

**Additional context**
Maybe related to https://github.com/opencollective/opencollective/issues/4176?

**Comment by znarf** [comment]
Doesn't make sense with our current permission model. I think they should just be deleted.

**Comment by Betree** [comment]
I've deleted mentioned member entries. Here are the member IDs in case we need to investigate:

> 8416,63584,53097,34324,19726,18459,9235,8087,3545,3358,3352,3350,3348,3346,3344,3340,3337,3333,3331,1177,139,613
