### ISSUE TITLE
Automate Deployment Process using GitHub CI

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4186]
Talking with @znarf about the deployment process I had the following idea. 💡 

Currently the deployment process involves a number of manual steps as per, https://github.com/opencollective/opencollective-frontend/blob/33535f88e79921d89daa8cf0e6c0d0e3346f076c/docs/deployment.md. And we have to wait until the process runs in the local terminal. I would suggest automating it with a GitHub workflow. So my suggestion is as follows. The person who wants to deploy will just create a [release tag](https://docs.github.com/en/github/administering-a-repository/about-releases) on GitHub and a workflow will run on the release tag and we will configure all secrets for the deployment in [GitHub secrets](https://docs.github.com/en/actions/reference/encrypted-secrets). So for example if the release is `2.0.0-staging` it will deploy to staging, if it's `2.0.0-prod` it will deploy to prod and so on. Let me know what you think or if this is useful to have. 😄 

cc: @opencollective/core-developers

**Comment by znarf** [comment]
The pain is not really to type `npm run deply:staging` and wait. One problem is that the app needs to be built at deploy time.

It could be interesting to see what we could do to have 1-3 minutes deployments, instead of the current 15 minutes or so.

**Comment by SudharakaP** [comment]
> The pain is not really to type `npm run deply:staging` and wait. The problem is more that the app needs to be built at deploy time.
> 
> It could be interesting to see what we could do to have 1-3 minutes deployments, instead of the current 15 minutes or so.

@znarf : Thinking about this; I think we should try caching on Heroku for nextjs build as per recommended here; https://nextjs.org/docs/messages/no-cache#heroku. Have we tried this before; if not I can enable it and we could give it a try. 😄

**Comment by SudharakaP** [comment]
Not sure we could do anything about this at this point; therefore I am closing this. 🤔
