### ISSUE TITLE
Add action workflows to Dependabot Upgrades

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4187]
A small enhancement I thought of when working on a dependabot related issue; suggest adding action workflow updates to dependabot; https://docs.github.com/en/code-security/supply-chain-security/keeping-your-actions-up-to-date-with-dependabot. I think currently we use the dependabot preview app (correct me if I am wrong). So first we need to upgrade dependabot to native version to have a configuration file (i.e: `dependabot.yml`). It was a long time I did this for other repos, but if I remember correctly this could be done through the dependabot portal and it will auto create the `dependabot.yml` file. 

Refer: https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/#moving-forward-from-dependabot-com-and-dependabot-preview

@opencollective/core-developers : If anyone who has admin access dependabot portal could do this step I could carry out the other part of adding action workflow updates. 😄

**Comment by Betree** [comment]
That sounds like a good idea, we can try that. The `dependabot.yml` seems to be the future of Dependabot so we'll need to migrate at some point anyway. I just triggered the update on API to try with a first project, it should appear soon on https://github.com/opencollective/opencollective-api/pulls?q=is%3Aopen+is%3Apr

**Comment by SudharakaP** [comment]
> That sounds like a good idea, we can try that. The `dependabot.yml` file seems to be the future of Dependabot so we'll need to migrate at some point anyway. I just triggered the update on API to try with a first project, it should appear soon on https://github.com/opencollective/opencollective-api/pulls?q=is%3Aopen+is%3Apr

The API one is merged and I don't see any issues with it; it seems to be behaving similar to the `dependabot-preview`. So if you could please trigger on the front-end as well. 😄 

cc: @znarf

**Comment by Betree** [comment]
@SudharakaP done :+1:

**Comment by SudharakaP** [comment]
Thanks @Betree 

@znarf : I've remove the max pull request limit from all of the above linked PRs (so there's no limit to how many update PRs can be opened daily) and also created the corresponding actions workflow update PR. Let me know when we are good to go ahead with the merges. 😄

**Comment by SudharakaP** [comment]
Closing this as it was decided not to do this for now and we would stay with Dependabot v1. 

Reference: https://opencollective.slack.com/archives/C0RMV6F8C/p1619712128205500
