### ISSUE TITLE
Introduce `kind` column in Transaction table

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4190]
Related to: 
- https://github.com/opencollective/opencollective/issues/4124
- https://github.com/opencollective/opencollective/projects/55

We want to introduce a new column to help us understand better the Transactions we record in the ledger.

It would be an ENUM with the following values:
- CONTRIBUTION: then main transaction, when done with the "Contribution Flow"
- EXPENSE: then main transaction, when done with the "Expense Flow"
- ADDED_FUNDS: then main transaction, when done with "Add Funds"
- PLATFORM_TIP: financial contribution to Open Collective added on top of another contribution
- HOST_FEE: the host fee going to the Host
- PLATFORM_FEE: reserved keyword in case we want to use in the future
- PAYMENT_PROCESSOR_FEE: reserved keyword in case we want to use in the future
- HOST_FEE_SHARE: part of the Host fee going from the Host to the Platform

Notes:
- Refunds keep the same "kind" but have `isRefund=true`
- Debts should keep the same "kind" and be tracked with a new boolean column `isDebt=true`
- All transactions would share the 
We want to migrate all possible Transactions in the past and add the "kind" that matches. It's ok if it's `null` for past Transactions we can't categorize.

For the record, we anticipate un-categorized Transactions for the following cases:
- Random manually recorded Transactions
- Pre-Paid budget Payment Method
- BackYourStack dispatch Payment Method
- Host Fees added to the Host Budget on a monthly basis (will be deprecated by the new model)
- Host Fee Share removed from the Host Budget on a monthly basis (will be deprecated by the new model)
- Owed Platform Fees and Tips added to the Host Budget on a monthly basis (will be deprecated by the new model)

Technical debt cleaning:
- We should try deprecate `PlatformTipForTransactionGroup`

**Comment by Betree** [comment]
Implemented in https://github.com/opencollective/opencollective-api/pull/5884.
Iterated on `PlatformTipForTransactionGroup` with https://github.com/opencollective/opencollective/issues/4205.
Added a note in https://github.com/opencollective/opencollective/projects/55 for adding the `isDebt` column
