### ISSUE TITLE
Convert all `img` elements to `next/image` elements

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4191]
Now that https://github.com/opencollective/opencollective/issues/4012 is done, maybe after waiting for some days to see if everything goes smoothly we probably should think about moving all `img` elements to `next/image` elements. We already have a PR open for this (https://github.com/opencollective/opencollective-frontend/pull/6009) and we need to adjust/add to it in order to achieve this I think. 😄 

cc: @Betree

**Comment by Betree** [comment]
While having next images is interesting for static images (mostly illustrations), we must make sure to never add the dynamic image domains (especially the one used for attachments preview) in `next.config.js` https://nextjs.org/docs/api-reference/next/image#src. Failure to do so would create public image previews of private documents.

In this regard, I think it's better if we avoid using next images for everything private at the moment.

**Comment by SudharakaP** [comment]
> While having next images is interesting for static images (mostly illustrations), we must make sure to never add the dynamic image domains (especially the one used for attachments preview) in `next.config.js` https://nextjs.org/docs/api-reference/next/image#src. Failure to do so would create public image previews of private documents.
> 
> In this regard, I think it's better if we avoid using next images for everything private at the moment.

@Betree : Yes, I agree. I've updated the PR by removing the image domains in `next.config.js` and also kept some dynamic images in their original state (using `img` tags). All the other static images I've converted to `next/image`s. Let me know if you see any issues. 😄
