### ISSUE TITLE
Upgrade Cypress to Version 7

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4192]
I think we are using a bit old version of Cypress (`v4.12.1`). There is a PR by dependabot sometime back to update this but I think it had problems; https://github.com/opencollective/opencollective-frontend/pull/5583. Current version of Cypress is v7 and I think it would be nice to upgrade to this so that we can use new features of Cypress such as the [`cy.intercept` function](https://docs.cypress.io/api/commands/intercept). 😄

**Comment by SudharakaP** [comment]
If no objection I'll be upgrading this next week or so. 😄

**Comment by znarf** [comment]
@SudharakaP It's really welcome, we're happy to have all packages up to date.

I don't remember what was the blocker by then.

**Comment by SudharakaP** [comment]
> @SudharakaP It's really welcome, we're happy to have all packages up to date.
> 
> I don't remember what was the blocker by then.

No worries. There's so many breaking changes between major versions so I'll try to do a incremental migration from 4 -> 5 -> 6 -> 7 instead of going straight to v7. 😄

**Comment by Betree** [comment]
I hope this will help with #3347 :crossed_fingers:

**Comment by SudharakaP** [comment]
@opencollective/core-developers : Looking good so far with the Cypress update; I would like to highlight the following aspects before merging these PRs. Maybe when we write tests in the future we can leverage these features. 

- We should start using `cy.intercept()` instead of `cy.route()`. Although `cy.route()` can probably be still used it is deprecated. 

- Supports using Cypress Studio; maybe when developing we can try this out; https://docs.cypress.io/guides/core-concepts/cypress-studio#Overview

- Test retries might be a good option to investigate for flaky tests; https://docs.cypress.io/guides/guides/test-retries#Custom-Configurations.

- Pay attention to the opacity; `opacity: 0` is not considered visible anymore; https://docs.cypress.io/guides/references/migration-guide#Opacity-visibility

- Cypress will start failing on non handled exceptions; https://docs.cypress.io/guides/references/migration-guide#Uncaught-exception-and-unhandled-rejections. We have several which I've added exceptions; https://github.com/opencollective/opencollective-frontend/pull/6310/files#diff-f4ccba99a203f90dfdca7435832cfa68e0ddd4865c0abe3adde145a056a14309R26-R32, but I think we should ideally make sure our tests are written so that we handle the exceptions properly. 😄 

** For the future **

- Maybe we can think about using component testing; https://docs.cypress.io/guides/component-testing/introduction once it's out of alpha. 🤔

**Comment by Betree** [comment]
@SudharakaP Thank you for sharing this! Component testing looks great, I'd love to try that once it's in a stable state.

**Comment by SudharakaP** [comment]
> @SudharakaP Thank you for sharing this! Component testing looks great, I'd love to try that once it's in a stable state.

You are welcome. 😄
