### ISSUE TITLE
Add the FUND tag to all Funds

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4194]
Now that we are being more public about Funds, I think it would be a good idea to automatically add the `FUND` tag on each existing Fund profile and new ones as they are created, as that labels it as a Fund at the top and helps make it more clear. It's also good for us as support because we can see easily whether something is a Fund or an Org profile.

**Comment by Betree** [comment]
It actually looks like the code already returns `FUND` https://github.com/opencollective/opencollective-frontend/blob/master/lib/collective.lib.js#L44 as the main tag, unless there's a more specific one (like `open source`) defined, or if the host is `OSC` (we force "OPEN SOURCE" in this case)

**Comment by alanna** [comment]
I'm not sure I understand what that means @Betree - that the Funds should already have this tag? I can't see it. Is it just not displayed?

<img width="427" alt="Screen Shot 2021-04-20 at 4 35 23 PM" src="https://user-images.githubusercontent.com/5498878/115338232-80cedf00-a1f6-11eb-8493-2a4b303eef46.png">

**Comment by Betree** [comment]
It is. The one you shared, https://opencollective.com/google, is an organization - not a fund.

If you look at https://opencollective.com/parentpreneur-foundation, the tag is there:

![image](https://user-images.githubusercontent.com/1556356/115355927-704d4300-a1bb-11eb-8f3f-ccfc3bce534f.png)

**Comment by alanna** [comment]
Ahhhhhh I see.

@piamancini I thought we made Google into a Fund, but I guess I was wrong.
