### ISSUE TITLE
Create an "Operator" route

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#42]
We want to experiment quickly, so in many cases instead of hacking the backend, we can have someone manually do the work during the experiment. So, let's create the "Operator" route. It takes the payload from the frontend and sends an email to operator@. 

Ex: Allow splitting a donation towards multiple collectives. Instead of building the backend and shuffling tables for something that may not stick around, let the frontend send the split of money for each collective in a payload to the Operator. 

```
const payload = {
    userId: 89,
    donationAmount: 100,
    donationCurrency: USD,
    split: {
        WWCode_HQ: 20, 
        WWCode_Seattle: 70,
        OC: 5,
        fees: 5
    }
}
```

The Operator (one of us) will manually "Add funds" to the right collectives.

Specs
- Takes a payload and sends it to operator@
- The route should only require a valid applicationKey to work

**Comment by piamancini** [comment]
oldie.
