### ISSUE TITLE
Change core contributor

### ISSUE THREAD

**Issue by schettino72** [opencollective/opencollective#420]
It seems there is no way to change the list of core contributors after a project is created.

**Comment by schettino72** [comment]
For `doit` project I would like to remove `Kwpolska` (on his request) and add `vlcinsky`.

**Comment by piamancini** [comment]
Hi @schettino72 I removed @kwpolska already but we need an email address for @vlcinsky to add him. You can email it to support@opencollective.com thank you

**Comment by vlcinsky** [comment]
@piamancini 
The e-mail was sent just now (with cc to @schettino72 ).

(sorry I misspelled your name in e-mail)
