### ISSUE TITLE
User invited to become admin should not be able to create org

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4201]
It's my understanding that Org profiles cannot be admins of Collectives and Hosts (#4184). But when inviting a user as an admin of a Collective, they can go down the path of creating an org profile.

This is how I got there:
1. Team settings of a Collective/Host
2. Add new team member
3. Invite a user not yet on the platform
4. User gets the invitation email and clicks through
5. Selects "don't have an account, join"
6. See both the personal and org profile creation options

I'm not sure what happens if they create an org profile here. Would they still be able to accept the invitation to become an admin?

<img width="1022" alt="Screen Shot 2021-04-20 at 9 06 17 PM" src="https://user-images.githubusercontent.com/5498878/115369495-45470b80-a21c-11eb-83e4-6f99eed22fb3.png">

**Comment by Betree** [comment]
They actually shouldn't have the option to create an account from there at all, since the invitation is tied to the email that has been provided. The only option should be to sign in with the email you've been invited with.

**Comment by alanna** [comment]
Ah, this is very unclear in the process! I was inviting a new user (who was also me but a new account) so I assumed I did not have an account created. As a brand new user, being asked to sign into something I have never registered with did not make sense, so I clicked "create account" instead.

**Comment by Betree** [comment]
Hopefully, this should be resolved by https://github.com/opencollective/opencollective/issues/2571 by allowing you to use a different email if the one you've been invited is not the one you actually want to use.

In the meantime, I'll make sure to remove the "Create account" path from this page.
