### ISSUE TITLE
Invitations should refer to the profile type

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4203]
I accepted an invitation to join as admin of a Host, but the wording I see refers to a Collective. We invite people to Funds, Orgs, etc, so this text should have a variable that refers to that profile type.

<img width="493" alt="Screen Shot 2021-04-20 at 9 11 04 PM" src="https://user-images.githubusercontent.com/5498878/115372106-ae2f8300-a21e-11eb-9e7d-d052cbb4850d.png">

**Comment by Betree** [comment]
It always adds some complexity to have specific wording for each account type. To simplify, I would suggest to do something like
> If you accept, your email address will be visible to other admins.

or

> If you accept, your email address will be visible to other admins of this account.

**Comment by alanna** [comment]
> If you accept, your email address will be visible to other admins.

This is a good solution.
