### ISSUE TITLE
Deprecate `PlatformTipForTransactionGroup` in `Transactions`

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4205]
The `PlatformTipForTransactionGroup` column was introduced in https://github.com/opencollective/opencollective-api/pull/4716 to solve an issue with platform tips refunds. The goal was to be able to easily find the platform tip attached to a transaction.

However, it looks like this field should not be needed anymore as platform tips now seem to have the same `TransactionGroup` as the transactions they're referring to. The query below doesn't return any entry newer than 2020-10-10.

<details>

```sql
SELECT *
FROM "Transactions" t 
WHERE "PlatformTipForTransactionGroup" IS NOT NULL 
AND "TransactionGroup"::varchar != "PlatformTipForTransactionGroup" 
ORDER BY "createdAt" DESC
```

</details>

This is most probably linked to [this change](https://github.com/opencollective/opencollective-api/pull/4716/files#diff-4cffa0c51e597183bea1e391ac7dde45b32da7acdd7a8cfc4d2c42443d704097R416) from the PR shared above.

There are therefore two issues:
1. The definition of `TransactionGroup` for platform tips is not consistent in the ledger
2. `PlatformTipForTransactionGroup` does not seem to be useful for new transactions, since its value is the same than `TransactionGroup`

# Proposal

- [ ] Migrate all existing platform tips to make sure their `TransactionGroup` is the same as the transactions they're referring to
- [ ] Remove the `PlatformTipForTransactionGroup` column
- [ ] Update all queries using `PlatformTipForTransactionGroup`

That might be easier to implement after https://github.com/opencollective/opencollective/issues/4190, as we'll be able to do something like this to get platform tips for a given transaction:
```sql
SELECT *
FROM "Transactions"
WHERE "TransactionGroup" = ${transaction.TransactionGroup}
AND kind = 'PLATFORM_TIP'
```

# Context
Initially proposed in https://github.com/opencollective/opencollective/issues/4190
*@znarf @kewitz*

**Comment by kewitz** [comment]
Correct. Once we have `kind` in place, things will be consistent.

**Comment by Betree** [comment]
We should pay extra attention when migrating this: it seems that https://github.com/opencollective/opencollective-api/blob/5654a97eb4417b80ebb90aca07931f0f8961678d/migrations/20201016085526-add-platform-contribution-transaction-group.js did not migrate all entries (see the query below to find the missing ones, ~1200). The join on the date to be the root cause for this, because we checked for `> interval '0'` while some transactions and their platform tip were created during the same second (see `412582`/`412583`) for example.

I initially spent quite some time working on [another migration](https://github.com/opencollective/opencollective-api/pull/4716#pullrequestreview-512415868) that is instead joining on the payment providers IDs that seems to catch these cases. We can eventually bring back this migration.

Another alternative is to re-run the migration with `>=`.

```sql
SELECT *
FROM "Transactions" t 
INNER JOIN "Orders" o ON t."OrderId" = o.id
WHERE (t."FromCollectiveId" = 8686 OR t."CollectiveId" = 8686)
AND o."CollectiveId" != 8686
AND (t."data" ->> 'isFeesOnTop')::boolean = TRUE
AND t."PlatformTipForTransactionGroup" IS NULL
AND t."isRefund" IS NOT TRUE
ORDER BY t."createdAt" DESC
```
