### ISSUE TITLE
Invitation to join should log you in

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4212]
This is what happens when a new or logged out user is invited as an admin of a Collective:
1. Receive email notification
2. Click `view invitation`
3. Jump to login screen where you must enter your email
4. Go back to your email
5. Click `one-click login` button
6. See the pending invitation
7. Click `accept`

This is the first experience many new users will have on the platform, if they are a new person being invited in. I think we can improve this flow.

Since the magic link login process is based on verifying them via their email, why do they have to trigger another email and jump back to their inbox again? Why can't the first `view invitation` button automatically log them in (if they are not logged in already)?

Is it to prevent accidentally creating duplicate accounts if someone is invited on an alternate email? That's a real case but I think it would be the minority.

Is there any way we can have an option the user can self-select where they see "You are about to create a new Open Collective account associated with the email xyz@example.com. If you already have an account under a different email, click here to log in." Or something like that? And most people will never need to click that.

**Comment by znarf** [comment]
For security reasons, we're not doing long term login tokens and we don't embed them in anything else than login emails.

**Comment by alanna** [comment]
How is the invitation different from the login email in terms of security? Is it because the token has to last longer for an invitation? How long do the normal login link tokens last?

**Comment by znarf** [comment]
> How long do the normal login link tokens last?

Login tokens are one-time use and expire after 75 minutes.

> How is the invitation different from the login email in terms of security? Is it because the token has to last longer for an invitation?

They definitely have to last longer, we don't know when the recipient will be able to use it. That might be a security issue too if the invitation is not used and the email is compromised.

By asking them to log in and go to their email box, we're mitigating this and have a guarantee that they have currently control of the email address.

**Comment by znarf** [comment]
We will not be doing this.

I think it's worth improving the experience around invitations and offer a Sign Up form to first time users. 

But that's another issue. Closing this one.
