### ISSUE TITLE
[PROJECT] Privacy on a transparent platform

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4214]
## Overview
Transparency is a huge part of Open Collective, and a deeply held value. It's what really sets us apart in a lot of ways, and have many important benefits. We have been opinionated about it because part of the impact we seek to have in the world is about transparency.

However, privacy is also important. The right to own your own identity and data is also a core value that's been with Open Collective from the beginning, along with the intention to build software expressly for positive impact in communities.

Critically, often times the people most at risk from mishandling privacy or not giving people the right options for privacy are those already dealing with hardships and marginalization in society, and those who are doing brave and important work. Examples we've dealt with have included trans people and people working to support trans communities, people who have needed to hide or change their name due to violence and abuse, people on the cutting edge of research into white supremacy and other highly dangerous topics who are at risk of being targeting in retribution. 

At the same time, those who seek to evade accountability or scam someone will take advantage of lack of transparency where they can. Transparency has been our most important tool for ensuring trust around the thing where it often goes most wrong: money.

One example we can learn from in this area is the [Gittip/Gratipay Crisis](https://geekfeminism.wikia.org/wiki/Gittip_crisis). TL;DR the founder was a cis white male who was dedicated to "total transparency". The platform began to be used by activists who had very real privacy needs, which he disregarded, and the whole thing kind of imploded. We do not want to make the same mistakes.

We have created some tooling for privacy already, such as incognito and guest contributions. We've also done things like hidden certain budget info on Fund pages upon request, because we made a judgement call that the good done by that initiative would outweigh the compromises on transparency. We regularly use some workarounds like advising users to sign up with pseudonyms, but then this causes other issues like their tax form being in the wrong name. There are many gaps.

In recent discussions have acknowledged that this calls for a proper effort, not a series of patchwork fixes and hasty features, both because the technical design must be sound if we are promising to keep something private and not accidentally leak it, and because the choices should be grounded in a deeper conversation about how we can best navigate the tension between privacy and transparency in terms of our values and impact.

Related issues #3422 #3689 #2871 #3324 #3340 #3276 #3216 #3998

## Owner
Alanna for the discussion phase, but probably Francois when we move to implementation? Not sure.

## Prioritization

- Does this serve our mission

Transparency is probably *the* headline word associated with Open Collective. To responsibly and fully have a transparent platform, it's critical to understand how we balance privacy, and to have guidelines to help us decide where the boundaries are. We need to define our integrity surrounding these questions.

- Will this help to make us financially sustainable within a year?

Some privacy related questions are attached to significant revenue, such as large Funds who would not have come on board if we insisted on complete transparency. We could easily get the data on incognito contributions to see how much $ is coming in that way, indicating privacy is a key factor for those amounts. We already serve communities who have significant privacy concerns, such as mutual aid groups supporting vulnerable communities, and mutual aid has been a huge driver of growth for us this year.

- Can this make us move faster?

Honestly, probably not. It's one of those things we should do because it's right, and will probably requiring slowing down to get it right. But once we have good tooling and policy in place, it will enable is to make calls about privacy and transparency faster, and automate some things we're manually working around now.

- Does this increase quality? 

Yes. This issue is already causing patchy workarounds, bugs, and poor user experiences.

- Does this add technical debt?

Not if we do proper implementation. This issue is already causing sort of operational debt, because it's blocking things like requiring payee names to match bank account owner names for payouts, which we need to manually handle currently.

- Is it feasible to build and maintain with our current team and runway?

Yes. I don't think it would be too onerous. The actual features have some complexity but not crazy.

- What insight or research is this project based on?

Lots of feedback via support, working directly with affected people and groups. We could probably get some more quantitative data about how many profiles are not matching payout names, how much $ is coming in as incognito contributions, etc.

- Is this problem already solved elsewhere?

No.

- How will we measure our success? Do we have a baseline today that we can compare this against?

Reduced support load, increased platform use by people with privacy needs, number of incognito expenses or whatever we end up building.

- How well do we understand the complexity of the problem, feature to be added or user need to be addressed? 

We need to do some more design and scoping, but we already have somewhat of an idea. I think I understand the pain points and needs pretty well, and the limitations in terms of regulations, etc, but Francois brought up a lot of questions about technical architecture we'd need to look into.

- What is the estimated timeframe for delivering this project? 

Not sure... 1 or 2 6-weekly sprints?

## Kick-off meeting

TBD

### Roadmap & Timeframe
(Key milestones or phases and estimated dates. Consider including further scoping, discovery, and prototyping. Include as a minimum: planning, design, development, documentation, feedback, iteration and, marketing)

* Do some interviews with users with enhanced privacy concerns, as well as users who deeply value high transparency
* Team workshops covering the company values questions and the technical architecture for privacy issues (could be together or separate)
* Design and feedback on the designs
* Implementation
* Documentation
* Announcement/comms
* Iteration

### Success metrics
(What we will judge outcomes of the project by)

Reduced support load, increased platform use by people with privacy needs, number of incognito expenses or whatever we end up building.

### Release planning

**Estimated delivery date**

TBD

- Which aspect(s) of the platform does this change impact?
Expenses, payments, profiles, tax form, budgets, Funds, contributions 

- Which group(s) of users will benefit from this change?
People with higher privacy needs, and also people who benefit from when we stick to transparency when appropriate.

- Is this project in response to a user-requested feature? If so who requested it (link to feature request if available)?
Yes, lots of user feedback.

- Is this project related to any similar work we have done, or are planning on doing in the next three months?
We've touched on it in various ways, but not directly taken it on.

### Next steps

- [ ] Open up any appropriate project issues
- [ ] Open a documentation issue, link it to this one
- [ ] Open a release issue, link it to this one
- [ ] Create a project board, add this issue to the description, add any issues created above 

## Project Closure

- Close all relevant project issues
- Open up issues for improvements 
- Post comm's according to comm's plan (most likely in release issue)
- Post project screencast on documentation slack channel 
- Post project closure in newsletter slack channel 
- Celebrate!!

**Comment by BenJam** [comment]
I would like to +1 this as we've been in conversation with a couple of groups who have a requirement to use the platform at risk of retaliation if their real names are exposed. This impacts Open Source Collective less so but certainly I can see Open Collective Foundation supporting causes that might be considered risky to operate at 100% transaprency. 

For me, the transparency requirement is more about _what_ the communitie's funds are being used to do, not _who_ is doing that work. This is literally just my opinion but I hope that, as we grow a platform we would be as able to support groups doing risky work for social justice as we would for open source.

**Comment by BenJam** [comment]
also thanks you @alanna for opening up this issues and running through the template. I've added this issue to the roadmap _project_ which I would like to start using as a short-form answer to three questions

> what are we currently working on?

> What might we work on next?

> What's new that might make us reconsider our priorities? 

I'd like us to begin reviewing just this board as we move between sprints, farming issues tagged `important` and opening up new issues like this one if we deem something worthy of elevating into a project. 

I would also like to encourage _everyone_ to contribute to issues like this, prioritisation is a team sport and if you have something to say about an idea it would be great to collectively build the case for a project prioir to us prioritising it as we move into the next sprint. 

Process for progress! 🚩

**Comment by alanna** [comment]
I just remembered another privacy-related issue we dealt with recently. A large company set up a Fund but they have very strict Personal Information (PI) data restriction policies, meaning their employees are not allowed to access more data about people than they need to. So while the Fund admins needed to approve expenses, they didn't need or want access to see expense submitter's private payout details, such as their bank account numbers. I think we could review exactly what different roles need access to at different parts of the process, including Collective/Fund admins, expense submitters, non-admin team members, Host admins, the public, etc.

**Comment by Betree** [comment]
> I think we could review exactly what different roles need access to at different parts of the process, including Collective/Fund admins, expense submitters, non-admin team members, Host admins, the public, etc.

We can also allow more granularity by adding new roles. For example, we had the case a few months ago of an organization where one of the members (an accountant) needed access to most financial information (receipts, expense details, etc) but without being able to do admin stuff like financially contributing as the organization. They also did not want this person to be surfaced in the "Team" section. We introduced a new `ACCOUNTANT` role to match this use case.

**Comment by alanna** [comment]
I'm considering closing this issue but #3422 remains open. Do we feel that the support we built for display/legal names does enough to solve this issue for expenses?
