### ISSUE TITLE
Review WWCode Portland expense

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#423]
Mail from Brittani:

> Hi Pia - 
We received two emails about this $41.65 expense, however it's not showing up in Portland's Open Collective. 
https://opencollective.com/wwcodeportland

I can see an expense for $46.65 with the same description, I don't know why she received an email from OC asking to approve / reject a $41.65. Any ideas? let me know

**Comment by nicobarretoOC** [comment]
Response from Brittani:

> Thanks. Perhaps she deleted it, I just didn't know if you could see something from your side.

**Comment by piamancini** [comment]
If a core contributor reject an expense then it's removed from the front end.
