### ISSUE TITLE
Add support for Dependabot v2 while keeping complexity Minimal

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4231]
Our upgrade to dependabot v2 has undergone a lot of complexity and also has bugs that needs to be addressed. The most significant problem is that dependabot v2 doesn't have access to GitHub secrets; https://github.com/dependabot/dependabot-core/issues/3253. We need a way to make sure the dependency update PR run the CI workflows correctly whilst keeping dependabot related logic minimal and non cluttering the existing CI setups.

My suggestion is to create separate workflows (that mimic the CI and E2E) tests for dependabot. This way the current CI flow is less dependent on dependabot related logic. Also there's some stuff (like matching branches) that are not needed to be handled for dependabot.

**Comment by Betree** [comment]
That sounds like a good approach, and it will make the transition easier once  https://github.com/dependabot/dependabot-core/issues/3253 is solved.

**Comment by SudharakaP** [comment]
@znarf @Betree : So this was tested on API side and seems to work correctly. See, https://github.com/opencollective/opencollective-api/pull/5915 and https://github.com/opencollective/opencollective-api/pull/5925 for PRs opened by dependabot; and https://github.com/opencollective/opencollective-api/pull/5911 for one with force-pushes. So I think we are ready to have this on front-end as well. 😄

**Comment by SudharakaP** [comment]
Closing this as we decided to move back to dependabot v1. 😄 

Reference: https://opencollective.slack.com/archives/C0RMV6F8C/p1619712128205500
