### ISSUE TITLE
Clarify pricing in FAQ

### ISSUE THREAD

**Issue by darkdragon-001** [opencollective/opencollective#4232]
https://docs.opencollective.com/help/collectives/collectives#how-much-does-it-cost

links to 

https://docs.opencollective.com/help/about/pricing

which links to

https://opencollective.com/pricing

which contradicts the first link. Please update accordingly.

**Comment by znarf** [comment]
For you @alanna @shannondwray

**Comment by shannondwray** [comment]
Sorted! Thank you :)

**Comment by darkdragon-001** [comment]
@shannondwray Are you sure this is fixed? Your FAQ still states costs which always apply, while your pricing page says it's free for collectives... Furthermore, your about/pricing page still lists _Updates to this page coming soon!_

**Comment by znarf** [comment]
@shannondwray Seems to me the "[How much does it cost?](https://docs.opencollective.com/help/collectives/collectives#how-much-does-it-cost)" section is not up to date. The most important point is that Open Collective doesn't take a 5% commission. Instead, we often rely on Platform Tips (except for Open Source Collective).

For Fiscal Host fees should, I think it would be more accurate to say that the range is 0% - 10%, often 5%.

@darkdragon-001 while we're fixing the documentation, the [Pricing](https://opencollective.com/pricing) page is up to date and reflect properly our pricing today.

**Comment by shannondwray** [comment]
fixed 😊
