### ISSUE TITLE
Don't show 'all ways to contribute' if all are already visible

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4234]
<img width="1168" alt="Screen Shot 2021-04-29 at 12 56 45 PM" src="https://user-images.githubusercontent.com/5498878/116489993-6f6a8e80-a8ea-11eb-8e09-e56147db0058.png">

To me it seems odd to have a huge button asking you to go look at a page that shows you what you can already see here. This Collective only has one contribution card. I know this is here because we need some link to /contribute in the design, but it seems very unlikely that a Collective like this with only one donation option will need to use the /contribute link instead of just sending people to their main page, so it's not worth the huge button and screen space it's taking up. It also falsely implies there are more options to see.

**Comment by Betree** [comment]
I agree with the intent. I suggest displaying this button only if the collective has:
- More than 6 tiers (because it's easier to scroll vertically on the contribute page than horizontally there)
- Or at least 1 event
- Or at least 1 project
- Or at least 1 connected collective

**Comment by snitin315** [comment]
Maybe we need something similar with the `View all events` button as well? 

<img width="1225" alt="Screenshot 2021-05-07 at 2 16 47 PM" src="https://user-images.githubusercontent.com/46647141/117424014-f8af4000-af3e-11eb-9911-2c0f80622983.png">

**Comment by Betree** [comment]
> Maybe we need something similar with the `View all events` button as well?
> 
> <img alt="Screenshot 2021-05-07 at 2 16 47 PM" width="1225" src="https://user-images.githubusercontent.com/46647141/117424014-f8af4000-af3e-11eb-9911-2c0f80622983.png">

Indeed, that would be a good addition

**Comment by snitin315** [comment]
I will update 👍🏻

**Comment by SudharakaP** [comment]
> I will update 👍🏻

@snitin315 : Created a new issue for this at, https://github.com/opencollective/opencollective/issues/4289
