### ISSUE TITLE
Footer: Don't show login and signup links for a logged in user

### ISSUE THREAD

**Issue by snitin315** [opencollective/opencollective#4235]
**Describe the bug**

We display log in and signup links in the footer always irrespective of the user being already logged in.

**To Reproduce**
1. Go to opencollective.com
2. log in
3. Scroll down to the footer

**Expected behavior**

I think we should not show these links if the user is already logged in.

**Screenshots**

<img width="236" alt="Screenshot 2021-04-29 at 8 03 52 AM" src="https://user-images.githubusercontent.com/46647141/116495902-7df08000-a8c1-11eb-9f02-24c32da147b9.png">

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Additional context**
No

**Comment by akashgp09** [comment]
I would like to work on this :)
