### ISSUE TITLE
Pricing Migration on May 1st

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4241]
We don't have the bandwidth to be more ambitious, so we agreed on the strict minimum:

-  [x] migrate remaining hosts to the “Grow” plan
-  [x] remove the old plans from the “Host Plan” section, but keep Start/Grow/Scale
-  [x]  can remove mention of the metrics and limitation of the old plans

**Comment by BenJam** [comment]
Should we do some more communication around this? I know we put together the post around how fees will be presented, is it worth following up on that?

**Comment by znarf** [comment]
cc @alanna

**Comment by alanna** [comment]
This sounds good @znarf - did it happen on 1 May?

@BenJam : what is there left to communicate?

**Comment by znarf** [comment]
@alanna It happened on schedule.
