### ISSUE TITLE
Move to Renovate (or other suitable dependency management)

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4243]
Forgive me for bringing this up again (after my failed update to dependabot v2) but I think we need to prepare for transition anyways since it was announced yesterday  (29th April) that dependabot v1 is retiring; https://github.blog/2021-04-29-goodbye-dependabot-preview-hello-dependabot/. On this note, I think we need to prepare for a suitable alternative. Here are some thoughts I summarized from our previous experience. 😄  

1) We cannot easily migrate to dependabot v2 due to https://github.com/dependabot/dependabot-core/issues/3253. Although maybe a workaround might be possible; the complexity makes it less appealing. 

2) Also I note that [dependabot-core is under Prosperity Public License 2.0.0](https://github.com/dependabot/dependabot-core/blob/main/LICENSE). It would be nice (in my humble opinion) to move to a open source licensed dependency management system if possible. 

3) A few alternatives that comes to mind are, 

- Renovate bot (https://github.com/renovatebot/renovate)
- Synk (https://snyk.io/)

Of which I think **Renovate** satisfies all our needs and also have some nice features which dependabot doesn't support yet (such as auto-merge rules). Therefore I suggest we slowly transition all our repos to renovate bot; this should ideally be done before August 03rd since dependabot will stop working at that date. 😄 

**Affected Repos**
- [ ] opencollective-frontend
- [ ] opencollective-api
- [x] opencollective-pdf
- [x] opencollective-images
- [x] opencollective-bot
- [x] opencollective-changelog
- [x] opencollective-rest
- [x] opencollective-setup
- [x] opencollective-emails
- [x]  opencollective-taxes

(Please add to the list if anything is missing).

Let me know your thoughts. 😄 

cc: @opencollective/core-developers

**Comment by SudharakaP** [comment]
@znarf @Betree : Since we are coming to the end of June and I don't think the original issue is going to be addressed to fit our needs anytime soon; https://github.com/dependabot/dependabot-core/issues/3253 I think it's a good time to start migrating one by one repo if there's no objection. So if it's okay I'll start with `opencollective-setup`, `opencollective-emails` and `opencollective-rest` next week and we'll migrate everything slowly. 😄

**Comment by znarf** [comment]
@SudharakaP Cool, have a try with those repositories.

**Comment by Betree** [comment]
I haven't followed all the conversations on this dependabot issue, but I'm curious about why what's proposed in https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544 doesn't work for us?

**Comment by SudharakaP** [comment]
@Betree : We could make it work for sure I think. But the workflow's become complex (have to add this `if: ${{ github.actor == 'dependabot[bot]' }}` at job level and then also make sure the checkout action is broken down to two separate branches) and this is the reason I tried to break all the workflows which needs a write token into two separate workflows (https://github.com/opencollective/opencollective/issues/4231), one for dependabot and the other for all CI runs. This should work I think but it did have some bugs and before finishing up on it we decided to stop this migration. Overall my impression is that making the workflow work for dependabot like this seems a bit hacky (like we are creating lot of separate workflows in each repo for dependabot) and I think migrating to renovate might be easier and more straightforward. But let me know if you think we should stick with dependabot; I don't have any strong opinion on this; my thinking is we should go for simplicity. 😉 😄

**Comment by SudharakaP** [comment]
@znarf : I've configured renovate on `opencollective-setup`, `opencollective-emails` and `opencollective-rest` as planned. This has opened a PR on each of these repos. 🐨 

https://github.com/opencollective/opencollective-emails/pull/239

https://github.com/opencollective/opencollective-rest/pull/299

https://github.com/opencollective/opencollective-setup/pull/117

The PR also includes the default way renovate will function. Let me know if you need any adjustments. I think the default should work for us for now. 🤔 🐨

**Comment by SudharakaP** [comment]
@znarf : So, `opencollective-emails` and `opencollective-setup` works fine it seems with renovate; and I've fixed the CI issues of `opencollective-rest` at https://github.com/opencollective/opencollective-rest/pull/300. If there's no objections, I'll go ahead and add renovate to the rest of the repos. 😄

**Comment by SudharakaP** [comment]
@znarf : I will trigger the renovate PR and merge them for the following repos today if no objection; we will keep api and front-end for the last batch; 

opencollective-pdf
opencollective-images
opencollective-bot
opencollective-changelog

**Comment by SudharakaP** [comment]
@znarf : So as per our discussion on slack; https://opencollective.slack.com/archives/C0RMV6F8C/p1624367861147800, I've moved all the repos, except `opencollective-api` and `open-collective-frontend` to renovate. I re-based and merged some patch updates (especially the security ones) but kept everything other thing from dependabot as is. If no objections, when I have time, I will go through and open new PRs fixing these dependency updates in these repos. There's some small questions I have, 

1) Can we archive `opencollective-emails` and `opencollective-setup` if they are not used anymore? 

2) Are there any other repos that we should configure which I missed in the [list above](https://github.com/opencollective/opencollective/issues/4243#issue-873039139).

3) Can we configure renovate such that, if it's a patch release and if the build passes, then we auto merge? 

@Betree

**Comment by Betree** [comment]
>     2\. Are there any other repos that we should configure which I missed in the [list above](https://github.com/opencollective/opencollective/issues/4243#issue-873039139).

There's https://github.com/opencollective/opencollective-taxes/

**Comment by Betree** [comment]
@SudharakaP Some feedback for https://github.com/opencollective/opencollective-pdf: let's keep the same strategies that we have today, enabling auto-merge for this repo is dangerous because the tests don't cover everything and I personally think that a manual review is still important when updating dependencies (especially since this one has an auto-deploy). I don't mind spending a few minutes each week to review them.

**Comment by SudharakaP** [comment]
> @SudharakaP Some feedback for https://github.com/opencollective/opencollective-pdf: let's keep the same strategies that we have today, enabling auto-merge for this repo is dangerous because the tests don't cover everything and I personally think that a manual review is still important when updating dependencies (especially since this one has an auto-deploy). I don't mind spending a few minutes each week to review them.
> 
> **Edit:** my bad, I saw some commits on `main` from Renovabot and thought they were auto-merge but realized that it was a manual thing (eg. [opencollective/opencollective-pdf#696](https://github.com/opencollective/opencollective-pdf/pull/696)); all good!

Sure it makes perfect sense too. We will do it manually then. 😄

**Comment by SudharakaP** [comment]
@Betree : FYI, I've made sure all the repos above don't have the dev dependencies fixed. Except for opencollective-bot where I had a small doubt; https://github.com/opencollective/opencollective-bot/pull/466. 😄

**Comment by SudharakaP** [comment]
If no objection, I'll be creating a config file within our [`.github` repo](https://github.com/opencollective/.github) for renovatebot so that the configuration is in one central location. We can extend it for individual repos. This is as per the discussion here; https://github.com/renovatebot/renovate/discussions/10609#discussioncomment-921519.

**Comment by SudharakaP** [comment]
@znarf @Betree : So the renovate configuration for all repos except `opencollective-frontend` and `opencollective-api` is complete and seems to be working fine. Also note that I've created a repo; https://github.com/opencollective/renovate-config to store the shareable renovate presets. So all renovate presets that should be globally applied should be defined there. 😄 

@znarf : Can you confirm on the [point 4 above](https://github.com/opencollective/opencollective/issues/4243#issuecomment-867339517); 

 >If no objections, I can go ahead an open PRs for configuring renovate on the front-end and api as well. After we disable dependabot from the repos, we will still have the older PRs but we will need to re-base them manually. The plan is over time when we fix those PRs and merge them (the once with the blocked tags), then we will be left with only renovate PRs. Is this fine?

If so I can proceed with the PRs on front and api as well to finish this off. Also please feel free to take a look and let me know if any other configuration should be added to the renovate configurations; maybe such as a schedule for updates etc. 😄

**Comment by SudharakaP** [comment]
This is done. I just configured the last two remaining repos; `frontend` and `api` to use renovate bot hereon. For the leftover PRs of dependabot, when renovate recreates them I'll add any context/information (if they are blocked) and close. 😄
