### ISSUE TITLE
Platform settlement expense has strange figures

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4248]
https://opencollective.com/ocnz/expenses/39597

<img width="667" alt="Screen Shot 2021-05-04 at 8 31 31 PM" src="https://user-images.githubusercontent.com/5498878/116978493-e2736b00-ad17-11eb-9e52-60ab8527dd2b.png">

1. Why is there a line item for something that's $0? Just don't show it.
2. Why is the total showing as -- instead of $214.96?

<img width="874" alt="Screen Shot 2021-05-04 at 8 33 44 PM" src="https://user-images.githubusercontent.com/5498878/116978597-0afb6500-ad18-11eb-91d5-837854554334.png">

**Comment by alanna** [comment]
There's something weird going on with the attached CSV as well. What are all these $0 transactions that say they are contributions to Open Collective?

<img width="1170" alt="Screen Shot 2021-05-04 at 8 35 57 PM" src="https://user-images.githubusercontent.com/5498878/116978905-6e859280-ad18-11eb-8b1c-1378477ce002.png">

**Comment by znarf** [comment]
@kewitz could you look in the things related "Reimburse: Payment Processor Fee for Platform Tips", you're the most suited for this.
