### ISSUE TITLE
"Interested" dropdown appears behind event info

### ISSUE THREAD

**Issue by aaronpk** [opencollective/opencollective#425]
![screenshot 2017-09-26 09 36 49](https://user-images.githubusercontent.com/113001/30872284-5bdda7e0-a29e-11e7-8ccf-8d8e6b1f9e61.png)

**Comment by piamancini** [comment]
is this still a bug?

**Comment by aaronpk** [comment]
I don't see the "interested" button at all anymore

**Comment by piamancini** [comment]
closing then. thanks @aaronpk
