### ISSUE TITLE
Inviting a user who's already used their email as a guest

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4250]
I added someone as an admin of a Collective, but their email was already associated with a previous guest contribution, so it ended up looking like this. Is there any way we could improve this? Like if a guest profile is then used for more activities on the platform the person could transform it into a normal profile?

<img width="930" alt="Screen Shot 2021-05-06 at 12 47 04 PM" src="https://user-images.githubusercontent.com/5498878/117226696-4ce7f080-ae69-11eb-950b-79f66e593592.png">

**Comment by Betree** [comment]
> Like if a guest profile is then used for more activities on the platform the person could transform it into a normal profile?

They can, by going to https://opencollective.com/create-account/guest - that is linked at the end of the contribution flow. Or by just signing in on the website, which will confirm their account and replace their slug to remove the `guest-` part.

I'm not sure about what we could do to improve this in the screenshot you shared, maybe hide the slug (`@guest-2120d226`) in the collective picker if it's a guest account?

**Comment by znarf** [comment]
Looks ok.

If they receive the invitation email, they can sign in and they're converted to a normal account.

**Comment by alanna** [comment]
OK if it updates their acocunt when they log in, that's fine. i thought they were stuck as a guest.
