### ISSUE TITLE
Don't show contributors section if there are none

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4252]
<img width="694" alt="Screen Shot 2021-05-06 at 6 10 13 PM" src="https://user-images.githubusercontent.com/5498878/117249847-605d8080-ae96-11eb-9183-bba6dcf3e1c3.png">

This isn't a great look. Can we wide this section if there are no contributors? I got here after creating a new project.

**Comment by Betree** [comment]
Root cause: we normally never have profiles without contributors. There's always at least one admin. For projects/events, admins are defined by the parent but the `contributors` query does not return them. We should either:
- Return the parent's admins
- OR hide the section when there's no admin

**Comment by alanna** [comment]
+1
