### ISSUE TITLE
Archive a tier / surface tier end date

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4253]
As a Collective admin, I want to archive a tier, so that I can run a time-limited funding campaign or close tiers that have expired.

@Betree said 
> There is also a little-known feature that is not surfaced in the frontend: tiers can have an "end date". When reached, the tier is marked as expired and cannot receive contributions anymore. That has to be set manually in the DB. The good thing about this solution is that the tier is still displayed.

So it seems the feature is already there and we just need to give people a way to access it. I think an `archive tier` option is a good idea (which just sets the end date to today), and also surfacing end dates in the tier settings (just a date picker, leave blank for no end date). 

I've seen many Collectives run crowdfunding campaigns with and end date and they've had to hack around to make it work.

**Comment by alanna** [comment]
I forgot we already have #3529 with more discussion on this

**Comment by Betree** [comment]
Closed in favor of #3529
