### ISSUE TITLE
Separate out Collective onboarding and Host onboarding

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4256]
We did a lot of work in [this doc](https://docs.google.com/document/d/1VcO_mQDsbPC0foW_WZ7a-L337I3VJVRHCQIPSLYNqrY) to crack the conceptual nut of a problem in our onboarding flow, but I realised we didn't have an issue for it.

The conclusion we came to is that the current setup, where we have one flow trying to accomodate new Collectives that are seeking to join a host, self-hosted Collectives, and new Hosts all at the same time, isn't working. The vast majority of people going through that flow are either destined to self-host or join a host. 

The numbers of users seeking to create a host are very tiny, and having that content in there is really confusing, plus stops us from designing a host onboarding flow that's tailor-made for that specific need. 

This is also important groundwork for point B below, which underpins our strategy to empower hosts to own their onboarding flow and customise it, and have more Collectives seeking hosts to enter via those Hosts and not through the main Open Collective front door, which will enable those users to get a much better guided experience and save OC from trying to tell one story to all these different kinds of people (which isn't really possible). I think it's an important aspect of the whitelabeling strategic focus.

So we should separate onboarding into:

### Create Collective Flow

A)

1. Push the big button on the homepage
2. Create Collective
3. Click “Start accepting contributions”
4. Choose between 
   4a. joining a fiscal host, or 
   4b. holding funds themselves (regardless of if they are an individual, company etc)

OR

B)

1. Start from a Host page and enter the application flow
2. Create Collective as part of that process
3. Host approves and it’s done, no need to select where money is held

### Create Host Flow
	
C)

1. Create a self-hosted Collective via A) above, if they only have a single Collective at first
2. After some time, when they want to start charging host fees or add another Collective, they can transform their profile to a Host with a Collective instead of self-hosted.

OR

D)

1. If they know from the beginning they want to create a Host, start with an Organization profile (without a Collective)
2. Click “activate as fiscal host” in settings
3. Create or accept applications from Collectives as they want

Related #3896 #3758 #3988

**Comment by Memo-Es** [comment]
> have more Collectives seeking hosts to enter via those Hosts and not through the main Open Collective front door

Loved this 💙

**Comment by alanna** [comment]
@Memo-Es when are we going to prioritise this for implementation? We seem to be running ahead with other things but we never implemented these changes. Do the designs need to be refreshed?

**Comment by Memo-Es** [comment]
Closing this issue since it's being tracked [here](https://github.com/opencollective/opencollective/issues/4829#issuecomment-1058829159)
