### ISSUE TITLE
[DOCS] How to get your receipts for a tax return

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#4257]
## Context
Meals of Gratitude put out an [update](https://opencollective.com/mealsofgratitude/updates/how-to-generate-a-donation-tax-receipt-using-open-collective) telling reminding their community how to get receipts for their donations to file their tax return correctly. We should document this for users. 

### Who does this change impact?
Contributors to collectives.

### How do users use it?
Users can get their receipts by 
- Going to 'Settings' > Payment receipts (preferred)
- Viewing their debit transactions on their personal profile
- Accessing their donations from individual collective pages

### Changes to be made
- [ ] Add 'Downloading your tax receipts' to 'financial contribtors' section
- [ ] Add link to the above in FAQ.

**Comment by alanna** [comment]
This should also link out to the OCF and OSC pages about the W9/W8BEN and 1099 process, but as that's US specific the details should live in those individual Hosts' docs.

**Comment by shannondwray** [comment]
@kaylarep @BenJam Just touching base about @alanna's comment above. I'm not too versed in these tax processes. Have these been added to the OCF and OSC docs? If so could we make a plan to action and then I can ensure these are linked out to. 😊

**Comment by shannondwray** [comment]
https://app.gitbook.com/@opencollective/s/help/financial-contributors/receipts 

Currently in progress, aiming to add more screenshots just clarifying what I can do $$ wise to show these receipts  😊

**Comment by shannondwray** [comment]
Sorted! https://docs.opencollective.com/help/financial-contributors/receipts Please let me know if anything else need to be added or changed :)
