### ISSUE TITLE
Automated virtual card receipts if the payment is through Open Collective

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4260]
I just signed Open Collective up for meet.coop, who uses OC to accept payments. But I can't use the OC Collective's balance as the payment source because it's across fiscal hosts. So I created a virtual card and use that. 

So Open Collective will send me a receipt for my payment to meet.coop, then I will need to upload that receipt back to Open Collective to complete the virtual card expense. Seems redundant.

This made me also wonder if virtual cards could be the way to finally enable Collective to Collective transfer across hosts.

#2017

**Comment by znarf** [comment]
Seems an edge case to compensate the lack of financial contributions across hosts. I think it's acceptable to have to upload the receipt. I don't see us tackling this issue.

With the ground work on Ledger, we're preparing to implement properly contributions across hosts. https://github.com/opencollective/opencollective/issues/3190 This will be likely based on settlement/reconciliation mechanisms between Hosts.

Credit Card based contributions across hosts is a hack, we kind of already tried it and we're not moving in this direction.

**Comment by alanna** [comment]
OK, makes sense
