### ISSUE TITLE
Support Metrics Report April 2021

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#4262]
### Support Metrics Report April 2021

This report looks at the trends around support to help us better understand areas we need to improve and highlight key topics for the month. 

**Tickets received**

![Capture](https://user-images.githubusercontent.com/57156267/117588901-993d7400-b17a-11eb-9b18-29013ffd9e04.png)

The number of tickets received increased by 52% from 517 in March to 788 in April. During April we linked all the OC emails to go through FreshDesks. This meant that notifications of new applications received and expenses notifications are now coming through FreshDesk and impacting the number of tickets received. By removing blank tickets, the rise during April was of about 40% -  462 tickets compared to 330 in March, with about the third of this number attributed to the emails notifications of comments coming from expense threads, some of which require our attention and action and some relating to other hosts outside of OSC and OCF.  [You can find the detailed listings here.](https://docs.google.com/spreadsheets/d/1pO6FQzpxUXpBms43J94rxhX4toU2IP3S/edit#gid=1529318989)

![Capture](https://user-images.githubusercontent.com/57156267/117588941-d73a9800-b17a-11eb-9031-7a9023996d95.png)

**Trends and Recommendations**

After removing irrelevant tickets, we had 462 (or 318 if we remove the tickets created from expense threads directly) that required support attention. It is worth noting the following areas:

**Expenses**

As indicated above, all user comments related to expense claims they submit now generate a new ticket in FreshDesks. We filter the information in such a way that only notifications of comments generate a new ticket and get automatically assigned to the relevant agent to look at them and address. The number of such tickets (144 during April) was removed from the graph above as the scale is significantly higher than all the other inquiries. Not all these tickets have a fiscal host admin action associated as they could be related to other hosts, exchanges between the user and the collective admins, or generic comments. I would estimate between 40% to 50% requiring updates in cases where we asked for additional information on claims submitted or where there were other problems (such as an error in input of payout method etc.)

Following the update from last month on cash reimbursements, the new processes have been completed and passed through our new lawyer and they look really good. As we are looking for the auditors’ advice on them, we haven’t yet reached out to the initiatives implementing these practices. However, the OCF team is looking to have a confirmed process in place and we are looking to invite the initiatives’ admins to join us for a webinar to talk them through the changes we are introducing and the impact it will have on their internal processes. [You can find more context here.](https://drive.google.com/drive/u/1/folders/1A7gO0dRJLIrEWW487Z_VWEvoBCL3ly8G)

As you can see above, support tickets received related to expenses where users replying to an email, rather than the expense tread (a problem we had associated mostly with The Social Change Nest) is no longer an issue and we only receive a handful of tickets during the month we need to pass to the host and these are mostly generic questions on expenses submitted and not yet paid. 

Some pain points from ops end keep on being expenses submitted (usually for small amounts) coming from users in China and Bangladesh (in this particular month) where there is a difficulty for them to use PayPal or Bank Transfers and so the option we opted for is Payoneer. The trouble is with some of these users (and in some instances our lesser experience with payments to these regions) it takes a lot of back and forth to determine Payoneer may be the only possible solution. The outcome is having a lot of time spent on the user and support end which significantly delays the time of the payment being processed. The other thing is the need to process payments to India manually to capture the additional questions around reasons for transfer. @kewitz  and I had a conversation around building this into the process but concern remains around the need to vary the response to the questions of why we send money through. Is it something that could be overcome?

 
**Onboarding**

Similar to expenses, any new applications notifications received now are going through FreshDesks. This is the reason for the spike in the number of hosting application tickets. The process has changed in the way tickets are now being automatically filtered to go to the relevant fiscal host admin. From the OSC perspective, I find it makes the process of reviewing the application and tracking them easier, helping to ensure we assess the applications in a timely manner and not having emails getting lost in the inbox. Also, I would like to mention that having the option to message the collective directly from the application page helps a lot in streamlining the process to the way it was a few months back!

Onboarding related questions are still some of the common ones we receive, however, there seems to be a drop in new collectives onboarded with OCF, there is a big increase in the number of new groups joining OSC. Here is how it was distributed:

We approved 19 new applications for OCF compared with 17 in March.

For OSC -  64 new collectives were approved during March compared to 75 in March. 

**Financial contributions**

A common question that is on the rise lately is coming from individuals initially opting for a bank transfer when making a contribution and then (usually upon realizing the associated fees their bank charges) changing their contribution to credit card, is whether we could delete the pending order for the bank transfer for them. Is there a way for the user to be able to cancel an order directly from their end? It seems right now this is only something the host admin can do for them with the option of managing contributions is something that applies to recurring payments only. @znarf please correct me if this option exists already. 

**Other things to note**

- During April, the number of questions related to how to process grants applications and the associated methods of transfer of these funds has significantly dropped and this is something that could be attributed to the fantastic work @kaylarep and Nathan did to update the Foundation support page with the relevant processes. 
- We often receive questions from various casino and similar nature websites that are sponsoring one of the bigger projects (most common would be [socket.io](https://opencollective.com/socketio)) with complaints related to their logo not being displayed. It would be great to figure out a better approach in these scenarios (right now it is referred to the collective mostly) as this is something that seems to take quite a bit of energy on our team end as well as the collective and not sure this is the type of organizations we would like to deal with? Would be great to have feedback on this.

**Comment by alanna** [comment]
Great news about the SCA tickets reducing a lot! That's a great example of support and engineering working together to help users get in contact with who they need to reach, and reducing our support load.

With the issue of payments to countries that don't have Paypal/Transferwise, I think we need to just draw a firmer boundary. We are clear that we can only pay using these services, and people should not expect to be able to get paid if they cannot access them. That said, why is telling them to sign up with Global Payoneer so time consuming? Can't we just put something about it in docs, send people that link, done? What is the back and forth about @alinamanko?

Regarding users being able to cancel a pending bank transfer, the truth is it doesn't matter and they should just leave it and it will expire, but they don't know how the system works. It seems silly to create a feature for a function we don't need (actively cancelling instead of just leaving it to expire), but if it's generating so many support requests it's a sign that they need the confirmation of actively cancelling so maybe we should let them. @alinamanko please raise a separate issue for this as a feature request so it can be considered.

When it comes to casino websites and such, we have given tools to Collectives to decide if they want these types of contributions, and it's up to them. Are these inquiries about displaying their logo on Open Collective or on the project's website? If it's the latter, we can't get involved and should just direct them to the project. If it's the former, I think we made a blanket `nofollow` policy, right @Betree ? What exactly do these casino and spammers want us to do @alinamanko ?

**Comment by alinamanko** [comment]
Thanks for the feedback @alanna! 

With payments to more restricted countries, the time-consuming part is to do more with us trying to navigate the alternatives - there is usually quite a bit of back and forth with the user trying to work out which payout method they could use. This normally happens when we receive requests from users residing in those countries we don't engage with often and so there is less awareness on my end around limitations applicable. 

Thanks for the clarification on the pending orders topic. If this is the case, I don't think it justifies our time in developing that particular feature - won't be an effective use of engineering I think. 

As for the sponsors - the questions received most frequently relate to the logo not showing (this is normally new contributors around $100-200 contributions in the time of their reach to us). There is often a complaint that they reached to the collective and didn't hear back. The usual practice from our end is to circulate these tickets back to the collective admin.

**Comment by BenJam** [comment]
Thanks for compiling this @alinamanko. 

It sounds like there are a couple of Issues to be raised here that we could consider. It also sounds like there would be some benefit to sharing some of the experiences here with other hosts, maybe on a peer-support forum of some sort.

@alanna @piamancini have we considered building a resource like this for hosts to ask questions, get answers and build collaborative docs?

**Comment by kaylarep** [comment]
@piamancini @BenJam there was intention for [this space](https://drive.google.com/drive/folders/12L_Z0v4dGkRNk4FEVho2tlI8TRT55G0m?usp=sharing) to be used for public resource sharing/doc building for fiscal hosts.

**Comment by alanna** [comment]
I want to build a whole fiscal host knowledge base, which people can comment on and contribute to. I hope to take that on very soon. For now, I think the best feedback forum is the #host channel and the monthly host calls.
