### ISSUE TITLE
Platform tips UI design might be seen as a dark pattern

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4268]
I'm getting consistent feedback that the Platform Tips design is confusing/misleading. People just hit the blue button without reading the platform tip text and it's not at all clear to them if the tip is going to the platform or the host, etc. I'm seeing big platform tips come it when I'm sure the user did not really intend that. It's great for the platform to get tips, but I don't want to do it through a dark pattern where people aren't aware or understanding what they are doing.

Possible ideas:
* Make platform tip a separate step from the main contribution step.
* Visually separate it into two separate boxes.
* Default the tip to zero and only accept tips when someone means to give one.
* Make it way more obvious it's a tip - the text just says "thank you for your contribution" with no strong indication of what it's referring to.

![Screen Shot 2021-05-11 at 9 18 40 AM](https://user-images.githubusercontent.com/5498878/117725968-fc421000-b239-11eb-9919-51aad4aa8946.png)

related: #4153

**Comment by SudharakaP** [comment]
My suggestion is to do points 3 and 4 together and mimic the text we have in the platform tip modal; https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=10518%3A29405. 

So we could change the description to something like below and also default the amount to "No thank you". 😄 

![image](https://user-images.githubusercontent.com/12435965/117756982-07faeb80-b1d4-11eb-92a1-f072184f30c3.png)

If this is in agreement I can do this. 😄 

cc: @Betree

**Comment by znarf** [comment]
@SudharakaP Please no rush in changing this, it's a stable UI that is here for more than 1 year. There has to be a wide consensus first.

**Comment by alanna** [comment]
Related: #4153

**Comment by alanna** [comment]
Yes for sure @piamancini - I am not suggesting any change to the underlying function of platform tips. I'm very pro platform tips. I'm only referring to UI/design choices that are confusing or misleading, getting in the way of the user making informed choices. I think the direct ask from the platform to the user makes sense and can be very positive. We should just ask in a clearer way.

**Comment by znarf** [comment]
Changed the title of the issue because it was using too strong language. I'm not accepting that it's a dark pattern and would not work in a company having a dark pattern live in production. Based on 1 year of evidence, I've not seen that many users feeling fooled.

We can and definitely should improve the design based on what we learned.

**Comment by alanna** [comment]
The reason I think it's misleading is that the text at the point of making the tip says:

> Open Collective is free for charitable initiatives. We rely on the generosity of contributors like you to make this possible!

This implies a few things that are not necessarily accurate:
1. The initiative you are contributing to is charitable (this message shows on all contributions, even to non-charitable groups)
2. It's only free for charitable groups (it's free to anyone not charging a host fee, charitable or not, and this is actually a huge offering OC gives the world and we should be recognised for it)
3. We never charge host fees to charitable groups (we do charge fees on charitable groups if their host has a fee)
4. Open Collective is not charging any fee on this transaction (often times there is a platform fee though the 15% revenue share)

So all that is misleading. Plus the UI issues that cause people to just not notice they are giving a tip or reverse the tip and contribution, or not understand who the tip actually goes to.

Maybe 'dark pattern' is too strong because that implies it's intentional (obviously we try to be honest and transparent and these problems are not by design), but the effect is like a dark pattern.

> We are not charging platform fees to the collective, we have a shared revenue model with hosts based on a number (host fee) that is 100% decided by the host.

This is true, and it's the reason I think we can rationalise asking for tips even when there is a host fee. We just need to be clearer about it, both in the text and visual design.

**Comment by znarf** [comment]
In our Pricing, we says that Open Collective is "**Free** – forever" "For Collectives" "Host fees may apply depending on your host". If we're happy with it on the Pricing page, I think it's also ok to say the platform is "free" for Collectives here.

Overall, it seems a big part of the issue is about the copy "The Open Collective Platform is free for charitable initiatives. We rely on the generosity of contributors like you to make this possible!" and "thank you for your contribution" Maybe can we start by changing it if there is any inaccuracy or if it's misleading.

@alanna Could you propose something for the copy?

On the design side, @Memo-Es started to explore ideas for a small redesign of the Contribute Flow.

@Memo-Es If you have anything new regarding Platform Tips, please share it in this issue.

**Comment by alanna** [comment]
> Tips from contributors like you allow us to keep Open Collective free for Collectives. Thanks for any support!

This will not fix the UI issues causing people to not notice the tips at all or reverse tips and contribution. If we change the text to above and either change the default tip to zero or move the tips to another step of the process, I think we can solve the main problems here.

**Comment by znarf** [comment]
@alanna Thank you for the copy. Seems you also had a problem with "thank you for your contribution", any change proposal for this one?

Copy change is easy and there is no blocker to move forward with it. We can ship when it's ready.

Regarding the the other aspects:

> change the default tip to zero

It's financially sensitive and there was negative feedback from @piamancini, I don't see this happening on the short term.

>  move the tips to another step of the process

We're always looking to improve the contribution flow, if we're able to prioritize design and get some team consensus, this could be tackled in coming sprints.

**Comment by Betree** [comment]
Related: we [should adapt the wording](https://github.com/opencollective/opencollective/issues/4092) for platform tips in the embed contribution flow (since people don't have the Open Collective context there).

**Comment by alanna** [comment]
I'm not saying most, or even many, people misunderstand how tips work. I'm saying that some do, and that's a really bad thing, because it leads to situations like giving $2000 to the wrong entity without knowing it.

I think the data to look at isn't how many users give tips overall, it's looking for situations where it's gone wrong, such as cases where the tip is larger than the contribution (including times when that happened and was refunded) and cases where refunds have been processed due to a problem with a tip.

I'm not suggesting we change how tips fundamentally work. I'm saying we should change the UI to make it more clear in a couple ways:
1. Change the text next to the tip request
2. Visually make the tip part of the modal a separated box from the main contribution part (or a separate step of the flow)

**Comment by znarf** [comment]
@alanna Still waiting for your on a proposal for the "thank you for your contribution" copy, as you reported it as problematic

**Comment by alanna** [comment]
@znarf it's in this thread [above](https://github.com/opencollective/opencollective/issues/4268#issuecomment-842638378).

**Comment by znarf** [comment]
@alanna I'm confused, there are 2 different sentences and I assume your proposal is only covering the 1st.

Here is the current status of my PR:

<img width="633" alt="Screenshot 2021-06-05 at 09 20 00" src="https://user-images.githubusercontent.com/806/120883773-5c309a00-c5df-11eb-8906-21e388d572f3.png">

Does that looks right?

**Comment by alanna** [comment]
Sorry @znarf I only just saw this.

Yes that first sentence looks good. 

I still think the second sentence can be confusing because 'contribution' is what we call their payment to the Collective. Can we change it to say "Thank you for your tip:" ?

**Comment by alanna** [comment]
More feedback in this [slack thread](https://opencollective.slack.com/archives/CJ2ERRZQ8/p1624259485085100).

**Comment by Betree** [comment]
Something that can be interesting to answer with A/B testing: What's the best default amount (suggested tip)? Maybe We'd get more tips with a lower default value because fewer people would feel the need to remove it
