### ISSUE TITLE
Force selection when applying to host with existing Collective

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4277]
This has happened a couple times recently: 

Collective already exists and wants to apply to a host, so they click apply on the host page and enter the application flow. The dropdown defaults to `no selection` but they don't notice this and just click the button to proceed. This results in them creating a new duplicate Collective instead of applying with their existing one.

<img width="599" alt="Screen Shot 2021-05-13 at 9 38 33 AM" src="https://user-images.githubusercontent.com/5498878/118048263-22011d80-b3d0-11eb-9f1d-62371a93f14c.png">

Possible solution:

* Make this dropdown a required selection so they have to proactively choose `Create a new Collective` or select an existing one. 
* If they have no other Collectives, they will create a new one now.
* If they select an unhosted Collective, it proceeds to apply with it.
* If their Collective already has a host
  * If it has zero balance, it automatically removes the old host and applies to the new one
  * If it has a balance, show an error saying they need to zero the balance first

**Comment by znarf** [comment]
It seems it's already a Required Selection. Just tested on Open Source and Foundation.

<img width="565" alt="Screenshot 2021-05-17 at 14 57 49" src="https://user-images.githubusercontent.com/806/118492604-784bc480-b720-11eb-96cb-33f6bbdd9b8b.png">

**Comment by alanna** [comment]
So the user would have to actively click `Create new Collective` even though that's what they *didn't* want to do?? OK I underestimated how confused this user was then.
