### ISSUE TITLE
Platform tips on added funds mistakenly saying there was no host fee

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4279]
I added funds for [dat](https://opencollective.com/dat) and put the standard 8% OCF host fee. But then I was shown a tip modal that says "since you didn't charge a host fee".

![Screen Shot 2021-05-13 at 11 39 59 AM](https://user-images.githubusercontent.com/5498878/118057519-4238d880-b3e0-11eb-9aba-5c5dc1c88615.png)

![Screen Shot 2021-05-13 at 11 40 49 AM](https://user-images.githubusercontent.com/5498878/118057527-4533c900-b3e0-11eb-82ca-3fec61df4160.png)

**Comment by SudharakaP** [comment]
@alanna : Ops, yes that sentence should be changed when the user selects a host fee. I am wondering what the best sentence to put there when they select a host fee? Any suggestions? 😄

**Comment by alanna** [comment]
If they have a host fee we should not ask them for a tip because they are already paying via the 15% revenue share. The purpose of platform tips on added funds is for hosts who don't charge fees or manage fees off the platform to have a way to contribute.

**Comment by znarf** [comment]
@alanna Can you look at the screencast and tell us if the behavior is right? https://github.com/opencollective/opencollective-frontend/pull/6362

**Comment by alanna** [comment]
This appears to be opposite. In the screencast, there is **no** host fee, and it **does not** ask for platform tips. If there's no host fee, that's when we **should** ask for tips. So the functionality appears to be reversed.

* Host fee box is 0% --> ask for host fee (because this means they aren't paying anything to the platform through host fee revenue share)
* Host fee is >0% --> do not ask for host fee (because they are already paying us through 15% share of the host fee they have set here)

**Comment by SudharakaP** [comment]
> This appears to be opposite. In the screencast, there is **no** host fee, and it **does not** ask for platform tips. If there's no host fee, that's when we **should** ask for tips. So the functionality appears to be reversed.
> 
>     * Host fee box is 0% --> ask for host fee (because this means they aren't paying anything to the platform through host fee revenue share)
> 
>     * Host fee is >0% --> do not ask for host fee (because they are already paying us through 15% share of the host fee they have set here)

@alanna : Ops, my brain was somehow working on opposite; I've corrected this and the screenshot is updated. Sorry about that. 😄 

https://github.com/opencollective/opencollective-frontend/pull/6362#issue-643952179

**Comment by alanna** [comment]
Woops I meant 
> Host fee box is 0% --> ask for 
> Host fee is >0% --> do not ask for **platform tip**

Sorry my brain...
