### ISSUE TITLE
Add Support for Vimeo Embeds in Rich Text Editor

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4284]
YouTube embeds for the rich text editor was supported at https://github.com/opencollective/opencollective/issues/2043 and the previews for YouTube embeds were supported at https://github.com/opencollective/opencollective/issues/4220. However due to some difficulties with adding Vimeo embeds we have left it out for the moment (https://github.com/opencollective/opencollective-frontend/pull/6042#issuecomment-825508243).

This issue was opened to investigate adding support to Vimeo embeds. I believe that adding Vimeo embed support isn't difficult but adding the support for video previews (as we've done for YouTube at https://github.com/opencollective/opencollective/issues/4220) might be tricky as the Vimeo video IDs and the image preview IDs are totally separate from each other. However I think we can find some workaround for this. 🤔

**Comment by SudharakaP** [comment]
@Betree : Before working on this just want to make sure if this is something we would like to have? Or do you think having YouTube embed support is sufficient? 🤔 😄

**Comment by Betree** [comment]
@SudharakaP We have no user request for Vimeo at the moment, and it's not something that will impact a lot of people. It's also difficult to justify why we would prioritize Vimeo over another platform like Peertube. I don't think it's worth spending time on this atm.

**Comment by SudharakaP** [comment]
> @SudharakaP We probably want this at some point, but we have no user request for Vimeo at the moment and it's not something that will impact a lot of people. It's also difficult to justify why we would prioritize Vimeo over another platform like Peertube. I don't think it's worth spending time on this atm.

@Betree : Okay, thanks for the information. I will close this for now then; and will iterate on it if it comes up in the future. 😄

**Comment by SudharakaP** [comment]
A user has requested Vimeo to be added; https://opencollective.freshdesk.com/a/tickets/387987. I am just mentioning it here as this is the first time this was specifically requested. If more requests are made by other users I'll create a new issue for this or re-open this issue 😸
