### ISSUE TITLE
Increase clickable area link back to Collective after contribution

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4290]
After making a contribution, you see this screen:

<img width="653" alt="Screen Shot 2021-05-15 at 9 26 44 AM" src="https://user-images.githubusercontent.com/5498878/118561588-51909b00-b7bf-11eb-80b9-cb462a037e7c.png">

A few users have been unable to figure out how to get back to the Collective because you have to specifically click the name or logo on the card. I think the whole card should be a link to the Collective, as well as the name in text where it says "You are now supporting..." with clear formatting showing it's a link (i.e. underlined).

**Comment by ersachin3112** [comment]
I will take it.

**Comment by SudharakaP** [comment]
> I will take it.

@ersachin3112 : Sure, feel free to let us know if you have any questions. 😄

**Comment by ersachin3112** [comment]
I think we should do same thing for collective cards on `/discover` page as well.

![CPT2106151521-1293x708](https://user-images.githubusercontent.com/80162912/122032600-6d528580-cded-11eb-9dd7-866a9f2a07d6.gif)
