### ISSUE TITLE
Add Support for Embedding Videos on Updates

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4298]
Since the embedding of videos in the long description is coming to an end, I think we should probably think about supporting videos on Updates as well. For this I see there's two parts; 😄 

- [x] Support videos on updates.
- [x] Make sure the video is replaced with a preview image when sending the email about the update.

**Comment by SudharakaP** [comment]
@Betree : Please feel free to add something if I've missed any. 

1) Also you think we should support this video embeds on update comments as well? 😄 

2) Also should we enable it on conversations as well?

**Comment by Betree** [comment]
> @Betree : Please feel free to add something if I've missed any. smile

I think we're good, thanks for documenting this! The preview in the email should also link to the YouTube video itself.

> 1. Also you think we should support this video embeds on update comments as well?
> 2. Also should we enable it on conversations as well?

It makes sense, why not

**Comment by SudharakaP** [comment]
> > @Betree : Please feel free to add something if I've missed any. smile
> 
> I think we're good, thanks for documenting this! The preview in the email should also link to the YouTube video itself.
> 
> > 1. Also you think we should support this video embeds on update comments as well?
> > 2. Also should we enable it on conversations as well?
> 
> It makes sense, why not

@Betree : Thanks for confirming. 😄

**Comment by Betree** [comment]
Re : enabling this in comments (updates and conversations) - we should probably wait for users requests before enabling that. With updates and collective long descriptions, we only open the feature to "trusted" users (collective admins). We should probably think a bit more before opening that to everyone.

**Comment by SudharakaP** [comment]
> Re : enabling this in comments (updates and conversations) - we should probably wait for users requests before enabling that. With updates and collective long descriptions, we only open the feature to "trusted" users (collective admins). We should probably think a bit more before opening that to everyone.

@Betree : Thanks for the idea. Then for now we'll only enable it for updates and not on conversations and comments. Hope that sounds okay. I'll do a PR soon. 😃

**Comment by alanna** [comment]
@Betree can you advise on @SudharakaP's question? OCF is waiting for this feature to announce a new policy so it would be good to understand the expected timeframe.

**Comment by Betree** [comment]
I've blocked this for too long, I'm going to prioritize a proper security audit between the end of this week and next week.
I'll merge directly if I don't find any blocker.

**Comment by Betree** [comment]
I provided some feedback on the API and added a test. I found no critical issue while investigating, but we're not defensive enough. I want us to be super protective, iframes and content sanitization are very common doors for code injection.

It can be achieved pretty quickly though, what @SudharakaP started is good.

**Comment by SudharakaP** [comment]
> I provided some feedback on the API and added a test. I found no critical issue while investigating, but we're not defensive enough. I want us to be super protective, iframes and content sanitization are very common doors for code injection.
> 
> It can be achieved pretty quickly though, what @SudharakaP started is good.

@Betree : I've refactored the code based on your suggestions. Let me know how it looks now. 😉
