### ISSUE TITLE
Deprecate the single transaction approach when recording expenses where payer=payee

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4301]
When the payer is the same as the payee, we record a single `DEBIT` transaction instead of the usual `CREDIT`/`DEBIT` pair. This breaks an important convention that is at the core of the double-entry ledger concept: debit and credit amounts should always match. According to the definition:

> Double-entry bookkeeping, in accounting, is a system of bookkeeping where every entry to an account requires a corresponding and opposite entry to a different account. (...)
The accounting equation is an error detection tool; if at any point the sum of debits for all accounts does not equal the corresponding sum of credits for all accounts, an error has occurred.

I don't yet have a full grasp on the reasons why this was done this way (probably, it was simpler to do at the time), but we should think about alternative solutions. One approach could be to null `CollectiveId` / `FromCollectiveId` when necessary. We already have some entries in `Transactions` where these columns are null, so the data model shouldn't require too many changes.

@znarf Feel free to add more context about the current solution or to propose something else if you have a better approach in mind.

_Related: https://github.com/opencollective/opencollective/issues/4286_

**Comment by znarf** [comment]
We discussed this here https://github.com/opencollective/opencollective/issues/3961 and generally agree that it's a temporary solution. 

We can and should explore "nullification" of one side of the transaction and re-inserting the missing entries.

**Comment by Betree** [comment]
Closing in favor of #3961
