### ISSUE TITLE
Fees apply when adding pre-paid budget

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#4302]
**Fees apply when adding pre-paid budget**
The functionality of topping up a pre-paid budget should not have fees assigned to it. However, fees are assigned automatically without the option to adjust them. 

**To Reproduce**
1. Go to an organization profile. In this example, looking at BuySellAds
2. Click on 'Add Prepaid Budget'. 
3. Add the amount to allocate - fees would be automatically calculated

**Expected behavior**
We should not see fees in this section at all. It seems like this is something that got triggered recently following other updates we pushed.  

**Screenshots**

<img width="447" alt="screen_shot_2021-05-17_at_9 52 36_pm" src="https://user-images.githubusercontent.com/57156267/118916377-eabbdf00-b982-11eb-8bcb-8b40f242b88b.png">

**Comment by Betree** [comment]
Ping @piamancini, I don't remember why we're taking the fees when creating the prepaid VS when contributing. Maybe that was to make sure organizations contribute the full amount that they intend to give?

Anyway we should probably review this with the new host pricing in mind.

**Comment by alinamanko** [comment]
Thank you @znarf - I was not aware of the alternative method here so this helps. 

We do however need to re-align on the fees aspect as a whole as my understanding was there are no fees applicable and so want to ensure there is clarity on this aspect. And regardless of the direction chosen, the current fees structure showing is one that is not aligned with the new pricing model

**Comment by znarf** [comment]
We deprecated this and now recommend A) the automated path or B) creating a Fund.
