### ISSUE TITLE
This button is CHONK

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4304]
Oh lawd he comin'!

<img width="633" alt="Screen Shot 2021-05-20 at 5 02 03 PM" src="https://user-images.githubusercontent.com/5498878/118921935-2f4c7800-b98d-11eb-8f64-40abcdcbe845.png">

**Comment by alanna** [comment]
I probably broke this when I updated the template.

**Comment by znarf** [comment]
Let's keep a minimal quality in the way we report issues, closing this one as invalid.

**Comment by alanna** [comment]
I would think you'd be more concerned about the quality of the user
experience here, but ok.

**Comment by znarf** [comment]
@alanna It's being fixed and I personally reviewed the change.

**Comment by alanna** [comment]
Ok, good to know.

I do A LOT of boring QA for this app even though it's not really my job,
and it sucks that we're not allowed to have fun even with such a trivial
thing. I think I'll refrain from raising issues for a while. Maybe the dev
team can incorporate more QA into your process, and you guys can raise the
resulting issues any way you want.

**Comment by SudharakaP** [comment]
> Ok, good to know. I do A LOT of boring QA for this app even though it's not really my job, and it sucks that we're not allowed to have fun even with such a trivial thing. I think I'll refrain from raising issues for a while. Maybe the dev team can incorporate more QA into your process, and you guys can raise the resulting issues any way you want.

@alanna : Hi, I just want to tell you how much I appreciate your work and wanna let you know that the work you do is quite valuable; in fact I gather a lot of insight into things from a different perspectives from the issues/discussions you open. It's sad that you are thinking about refraining form raising issues, but I would suggest please let us work towards a better process with more defined and precise actions on when and how to close issues and how the communication should be done. 🤔 🤔

I have a few ideas on this and I've opened a discussion at;  https://github.com/opencollective/opencollective/discussions/4308

**Comment by znarf** [comment]
@alanna Sorry to be boring, it's just not possible to keep issues like this open. It was a simple opportunity for me to say that we expect a minimal quality there. Your contributions are generally valued and I can only encourage you to continue reporting issues as you always do.

@SudharakaP I think you're right, it's generally a bad feeling when someone come and close your issue. It's important to have  guidelines and processes to make it as much neutral as possible.

Working in the open here, I progressively learned to be tolerant, I normally avoid closing issues if I think it does more harm than good. Seriously, this is why we have so many issues opened! In this case, I saw this one first thing in the morning, it was clearly an outlier to me, felt it was a simple call and you would not mind, took quick action, 30 seconds. Seems I was wrong.

**Comment by SudharakaP** [comment]
> @SudharakaP I think you're right, it's generally a bad feeling when someone come and close your issue. It's important to have guidelines and processes to make it as much neutral as possible.
> 
> Working in the open here, I progressively learned to be tolerant, I normally avoid closing issues if I think it does more harm than good. Seriously, this is why we have so many issues opened! In this case, I saw this one first thing in the morning, it was clearly an outlier to me, felt it was a simple call and you would not mind, took quick action, 30 seconds. Seems I was wrong.

@znarf : Surely, but it's definitely something we can incorporate in the future maybe if the team agrees; I just created a quick PR; https://github.com/opencollective/opencollective/pull/4309 with some simple issue templates which I though was useful. Maybe we can add more or modify them as needed in the future. Let me know if additions or modifications are needed and I am quite willing to do so. 😄
