### ISSUE TITLE
Better support for multi-day events in email confirmation

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4306]
User feedback:

>  we have a two day event but the confirmation email after folks get their ticket the text says the event is ‘being held on’ the first day only - might be nice to have that change to ‘between xxx and yyy’ for multi-day events

_Originally posted by @kaylarep in https://github.com/opencollective/opencollective/issues/4280#issuecomment-844275285_
_Reported by @RCheesley_

**Comment by SudharakaP** [comment]
> This is the line: https://github.com/opencollective/opencollective-api/blob/6c7b0ac0f617f7332c355c59e78513447af41b3e/templates/emails/ticket.confirmed.hbs#L16. If there's an `event.endDate`, we want to display `between {startDate} and {endDate}`

@Betree : Done, let me know if all looks good. 🐼
