### ISSUE TITLE
When checking out on contributing to a project, the slug doesn't include my collective path

### ISSUE THREAD

**Issue by RCheesley** [opencollective/opencollective#4311]
**Describe the bug**
On checking out from the project page after creating my project, the URL path does not include the slug for my collective. This (may) be an issue if there were projects that had the same slug in the future, in different projects?

The path I ended up on was:

https://opencollective.com/resource-management-initiative/donate/success?OrderId=<orderID>

**To Reproduce**
1. Go to a project
2. Click on contribute
3. Go through the process of making a contribution
4. Watch the file path - as soon as you click contribute, you lose the project slug.

**Expected behavior**
I think that it should have the project slug throughout the payment process?

**Comment by znarf** [comment]
In some situations, we can effectively loose the parent slug in the URL. It's not desirable but it's not breaking.

Projects slugs are currently unique in the whole Open Collective space, so no conflict possible, you're prevented to create a Project with an existing slug. We may reconsider this, if we manage it like events, we would simply add a unique identifier to the slug so ensure it's unique.

**Comment by znarf** [comment]
Duplicate with https://github.com/opencollective/opencollective/issues/4587

**Comment by znarf** [comment]
Closing as we will be tackling this in the duplicate issue.
