### ISSUE TITLE
Contribution Flow Back Button Missing

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4314]
One of the things that I noticed working on the contribution flow is that we don't have a back button after you enter the contribution flow. That is the user has no way of going out of the contribution flow other than the back button of the browser. My understanding here is that it's best to not solely rely on the browsers back button since normally our flows contain back and forward navigation; this flow should be the same (correct me if I am wrong). 😄 

**Suggestion**: I would suggest adding a back button in the first step of the contribution flow next to the "Your info" button such that the user is taken back to the collective screen. 😄 

![no-back-button](https://user-images.githubusercontent.com/12435965/119530942-56fa6200-bd38-11eb-8f8d-e70c6fedb755.gif)

@Betree @opencollective/design

**Comment by Betree** [comment]
We can add such CTA, but I wouldn't personally re-use the same "Prev" button because its intent in there is to navigate between the steps while going back to the collective page takes you out of the flow (= different context). That would make it easy to leave the flow (and lose everything you've typed) because of an erroneous double click, or you could think that there was a step before the first one just because this button exists.

Related: have a better way to switch between tiers inside the contribution flow.

**Comment by SudharakaP** [comment]
> We can add such CTA, but I wouldn't personally re-use the same "Prev" button because its intent in there is to navigate between the steps while going back to the collective page takes you out of the flow (= different context). That would make it easy to leave the flow (and lose everything you've typed) because of an erroneous double click, or you could think that there was a step before the first one just because this button exists.
> 
> Related: have a better way to switch between tiers inside the contribution flow.

@Betree : What is CTA? sorry I am bad with abbreviations. 😃  

Another idea I have is to include a link at the top left hand upper corner of the page maybe to go back to the collective page. But I'll leave it to design to think about this maybe if this is considered important. For myself I always found it a bit problematic; I would first search; "how do I go back" and then default to the browser back button. 😄

**Comment by znarf** [comment]
@SudharakaP https://en.wikipedia.org/wiki/Call_to_action_(marketing)

In the context of a button, that would simply be the text in the button.

**Comment by SudharakaP** [comment]
> @SudharakaP https://en.wikipedia.org/wiki/Call_to_action_(marketing)
> 
> In the context of a button, that would simply be the text in the button.

Thanks. 🐨

**Comment by SudharakaP** [comment]
@opencollective/design : Any ideas on this one? My initial thinking is to put a small back link at the top left hand corner of the page so that the user is taken back to the collective page; if that's agreed let me know. 😄 

Note that this can get annoying to the user if we are relying only on the back button; for example they can do several back and forth motions and then they'll have to click a lot of times to get back to the collective. 😄 

![Peek 2021-05-28 07-19](https://user-images.githubusercontent.com/12435965/119998281-691d1000-bf85-11eb-87e9-11bea1cf677b.gif)

**Comment by znarf** [comment]
@SudharakaP Generic "Back" link/buttons can be problematic, in some cases we have it and it doesn't work as expected.

What you need here is not a "Back" link, it's a "go to Collective page" link.

**Comment by SudharakaP** [comment]
> @SudharakaP Generic "Back" link/buttons can be problematic, in some cases we have it and it doesn't work as expected.
> 
> What you need here is not a "Back" link, it's a "go to Collective page" link.

Thanks, I just added a small link to bottom of the buttons. Hope that looks good for now. 😄

**Comment by Betree** [comment]
In the past we used to have the collective logo at the top clickable to achieve that
