### ISSUE TITLE
[DOCS] Inconsistencies in the Documentation

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4317]
I am reading the documentation and thought of opening an issue that I will keep updating as and when I find issues/inconsistencies. Here are some things I found for the moment. 🐼 

 ✅ (in progress)- https://docs.opencollective.com/help/about/company#where-are-you-based: This section needs to be updated with current members locations. 
 
✅ (in progress)- https://docs.opencollective.com/help/about/team: This needs to be updated with current members.

✅- https://docs.opencollective.com/help/about/contributing#design: This section seems to link to a [blog post](https://blog.opencollective.com/open-collective-design/) which to my understanding has outdated information. Correct me if I am wrong @Memo-Es. Maybe we need to provide a different link or remove the link altogether. 

✅- https://docs.opencollective.com/help/contributing/development/bounties#contributor-ladder: Are we actively maintaining the contribution ladder?  

✅ - https://docs.opencollective.com/help/collectives/create-collective: The first image of profile drop-down needs to be updated.

✅ - https://docs.opencollective.com/help/collectives/customize-collective: The image needs to be updated.

✅ - https://docs.opencollective.com/help/collectives/customize-collective#page-sections: Has the following line, 
>If you would like to reorder sections or hide one, please contact support and we can action your request. In the future, we will enable Collective admins to hide and reorder sections themselves.Is this needed? Unless we have specific plans to do this and a GitHub issue I suggest removing it. 🐼 

✅ - https://docs.opencollective.com/help/collectives/tiers-goals#goals: Screenshot of going to settings needs to be updated.

✅ - https://docs.opencollective.com/help/collectives/tiers-goals#interval: Needs updating to include flexible intervals.

✅ - https://docs.opencollective.com/help/collectives/tiers-goals#interval: What is meant by merging OpenCollective's PR? @znarf

- https://docs.opencollective.com/help/collectives/tiers-goals#can-i-do-a-purchase-order-po: Is this email address correct? Just asking as it's kinda weird looking email. 🐼 😄 (host+c6@opencollective.org) @znarf 

✅ - https://docs.opencollective.com/help/collectives/add-or-change-fiscal-host#adding-a-fiscal-host: Screenshot needs updating

✅- https://docs.opencollective.com/help/expenses-and-getting-paid/submitting-expenses: Screenshot of submit expense needs updating

✅- https://docs.opencollective.com/help/fiscal-hosts/payouts/two-factor-authentication-for-payouts#enabling-2fa-for-payouts: Two broken links in this section. 

✅ - https://docs.opencollective.com/help/fiscal-hosts/fiscal-host-dashboard#pending-applications: Needs additional documentation. 

✅ - https://docs.opencollective.com/help/fiscal-hosts/virtual-cards#enabling-users-to-request-virtual-cards: The final line in this paragraph isn't complete. We probably need to add an illustration/image as well. @BenJam 

✅- https://docs.opencollective.com/help/contributing/design/contribution-guidelines#teamweek: I don't think we use Teamweek anymore right? (cc: @Memo-Es). Shall we remove this? 

✅- https://docs.opencollective.com/help/contributing/design/contribution-guidelines#getting-familiar-with-the-process-of-oc-design: I think we can remove this section as this section is a duplicate from the previous section under the same heading; https://docs.opencollective.com/help/contributing/design/understanding-the-design-workflow#mapping-our-process. (WDYT @Memo-Es?)

✅ - https://docs.opencollective.com/help/contributing/development/dev-contribution-guide#api: Suggest removing the line, `We're currently working to make it easier on Windows` ? (cc: @Betree) 

✅ - https://docs.opencollective.com/help/contributing/development/best-practice-guidelines#frontend-rules: Over here we say we are getting rid of material-ui. I don't see an issue open for this. Is this still accurate? (cc: @Betree)

✅ - https://docs.opencollective.com/help/contributing/development/api/users-emails: Okay to remove this page? 

✅ (deleted)- https://docs.opencollective.com/help/contributing/development/custom-tweets: Empty page; delete it, or do we have some info in mind for this? 

✅- https://docs.opencollective.com/help/internal/welcome-document#design-collective: This section needs revising. Maybe remove the second point with Culki's email and add Memo's email instead? @Memo-Es 

✅ - https://docs.opencollective.com/help/internal/host-admin-manual#do-not-touch: We need to add a reason for this do not touch section? Otherwise, over time new members might not know why. @znarf

✅ - https://docs.opencollective.com/help/internal/host-admin-manual#european-bank-transfer-payments: Maybe replace Xavier with someone else? @znarf

✅ - https://docs.opencollective.com/help/internal/support#reassigning-tickets: Replace Xavier's name with someone else? @znarf

✅ - https://docs.opencollective.com/help/internal/testing#how-to-debug-an-e-2-e-test-that-failed: Revisit and update information for this section. 

@opencollective/core

**Comment by Betree** [comment]
> https://docs.opencollective.com/help/contributing/development/bounties#contributor-ladder: Are we actively maintaining the contribution ladder?

We try to, it's not moving much lately because we are not creating as many bounties as we used to.

**Comment by BigGuy573** [comment]
@SudharakaP Do you have any continuous Integrations?

**Comment by SudharakaP** [comment]
@opencollective/core : So as a fun exercise I went through the whole documentation this weekend and along the way I've found some other inconsistencies. I've update my [original post](https://github.com/opencollective/opencollective/issues/4317#issue-904761276) with all of them. If there's no objection as time permits I can go ahead and create multiple PRs for updating the old images and sections. Let me know your thoughts on these. It's a bit long so I hope I am not overwhelming you. 😄 🐼 🐨 😄

**Comment by shannondwray** [comment]
Am adding ✅ when I have sorted an issue! 😊

**Comment by SudharakaP** [comment]
> Am adding white_check_mark when I have sorted an issue! blush

Thanks for helping with this one Shannon. 😄

**Comment by SudharakaP** [comment]
> Thank you @SudharakaP for this! Great initiative.

You are welcome. 😄

**Comment by Betree** [comment]
> https://docs.opencollective.com/help/contributing/development/dev-contribution-guide#api: Suggest removing the line, We're currently working to make it easier on Windows ? (cc: @Betree)

:+1: 

> https://docs.opencollective.com/help/contributing/development/best-practice-guidelines#frontend-rules: Over here we say we are getting rid of material-ui. I don't see an issue open for this. Is this still accurate? (cc: @Betree)

We mostly got rid of this library in our codebase. We're still using one component though: `@material-ui/core/Switch`. I don't see any strong argument for moving to another library at the moment, except to have something better integrated with our design system. In short, the current status is: we still rely on this library for some stuff but please don't use it directly.

**Comment by shannondwray** [comment]
@Betree thank you! Have fixed :)

**Comment by shannondwray** [comment]
@Memo-Es Would you be able to have a look through this when you have time? You have been tagged in a few of the points

**Comment by BenJam** [comment]
bump!

**Comment by Memo-Es** [comment]
@shannondwray @SudharakaP 
Update on the points regarding design:

>  * https://docs.opencollective.com/help/about/contributing#design: This section seems to link to a blog post which, to my understanding, has outdated information. Correct me if I am wrong, @Memo-Es. Maybe we need to provide a different link or remove the link altogether.

We would need to replace this paragraph entirely with a new link to another post that better describes the current design practice. Can we replace it with a 'WIP' meanwhile?

> * https://docs.opencollective.com/help/contributing/design/contribution-guidelines#teamweek: I don't think we use Teamweek anymore, right? (cc: @Memo-Es). Shall we remove this?

We will also need to replace this page of the design contribution guidelines; the general content is ok so in the meantime, we can delete this thing about teamweek

> https://docs.opencollective.com/help/contributing/design/contribution-guidelines#getting-familiar-with-the-process-of-oc-design: I think we can remove this section as this section is a duplicate from the previous section under the same heading; https://docs.opencollective.com/help/contributing/design/understanding-the-design-workflow#mapping-our-process. (WDYT @Memo-Es?)

Same as the previous one, we will replace the entire page, but I agree that we can delete this section.

> https://docs.opencollective.com/help/internal/welcome-document#design-collective: This section needs revising. Maybe remove the second point with Culki's email and add Memo's email instead? @Memo-Es

Also, think it should be replaced with WIP

I will be working these next 2 weeks on doing a proper update for the aforementioned points, will be in touch with @shannondwray  when I have something ready to be updated

**Comment by SudharakaP** [comment]
Adding something mentioned by @piamancini on Slack; https://opencollective.slack.com/archives/C9767R4V9/p1627030714018200

>peeps, this page needs updating https://docs.opencollective.com/help/fiscal-hosts/fiscal-host-settings the images are from the old page
>
>It seems like we are also missing a section to show how you can add a host's bank details to receive money via bank
>
>https://docs.opencollective.com/help/fiscal-hosts/bank-transfers

**Comment by shannondwray** [comment]
@Memo-Es  Thank you!! have actioned all of these :)

**Comment by SudharakaP** [comment]
@znarf: I've tagged you on some small questions in the original post; https://github.com/opencollective/opencollective/issues/4317#issue-904761276. If you could answer these it will be really helpful. Thanks. 😃

**Comment by Betree** [comment]
This page is duplicated:
- https://docs.opencollective.com/help/internal/architecture
- https://docs.opencollective.com/help/contributing/development/architecture

IMO, it should live under https://docs.opencollective.com/help/contributing/architecture.

**Comment by BenJam** [comment]
@Betree I removed the dupe, I'm gonna be updating some of the material there.

**Comment by BenJam** [comment]
are we good to close this down and open other issues if needed?

**Comment by Memo-Es** [comment]
We can close this one. I will need to follow up with a design-oriented documentation issue, we will make sure to put it up this sprint and follow-up parallely 
@BenJam

**Comment by SudharakaP** [comment]
> are we good to close this down and open other issues if needed?

Yes, there's couple of issues that we need to follow up, but I think we can close this one and open separate issues for those. Almost all the issues from the original post have been addressed. 😄

**Comment by SudharakaP** [comment]
Only remaining issue from the initial post is, 

>https://docs.opencollective.com/help/collectives/tiers-goals#can-i-do-a-purchase-order-po: Is this email address correct? Just asking as it's kinda weird looking email. 🐼 😄 (host+c6@opencollective.org)

which is discussed at https://opencollective.slack.com/archives/C9767R4V9/p1627370950023900. 

@BenJam : Did you update this email? Can we update this in the documentation?

**Comment by SudharakaP** [comment]
> Only remaining issue from the initial post is,
> 
> > https://docs.opencollective.com/help/collectives/tiers-goals#can-i-do-a-purchase-order-po: Is this email address correct? Just asking as it's kinda weird looking email. panda_face smile ([host+c6@opencollective.org](mailto:host+c6@opencollective.org))
> 
> which is discussed at https://opencollective.slack.com/archives/C9767R4V9/p1627370950023900.
> 
> @BenJam : Did you update this email? Can we update this in the documentation?

This has been addressed as per, https://opencollective.slack.com/archives/C9767R4V9/p1629297230003500 and therefore all the issue in this thread are addressed. Thus I am closing this. Thanks everyone for the help. 😄
