### ISSUE TITLE
Stripe 404 error

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#432]
**AIDLE on slack is having an error when trying to connect stripe:**

>  I am unable to connect my stripe account under setting for our open collective
Seems the stripe api request when I click connect to stripe is returning a 404 error
![screen shot 2017-09-27 at 4 30 52 pm](https://user-images.githubusercontent.com/30665166/30945914-85987424-a3c6-11e7-9194-4f22a515224f.png)

**Comment by piamancini** [comment]
@nicobarretoOC followed up with her on #support in slack
