### ISSUE TITLE
CI: E2E cache steps seem abnormally slow

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4322]
I just saw a CI job timing out on API's `.github/workflows/e2e.yml` > `Restore .next cache (frontend)`:

> 3m 8s
> Error: .github/workflows/e2e.yml (Line: 175, Col: 16):
> Error: The template is not valid. .github/workflows/e2e.yml (Line: 175, Col: 16): hashFiles('opencollective-frontend/**') couldn't finish within 120 seconds.

Looking at successful jobs, it seems that the cache steps are taking quite some time to complete (~5min total):

![image](https://user-images.githubusercontent.com/1556356/120156992-d681a880-c1f2-11eb-814f-058d36c41df1.png)

![image](https://user-images.githubusercontent.com/1556356/120157187-0630b080-c1f3-11eb-8d62-ef6e03638ada.png)

My guess is that using `hashFiles('opencollective-frontend/**')` for the `key` is too broad, and forces GH actions to hash too many files. Ideally, the hash should only be based on:
- `package.json` / `package-lock.json`
- NextJS config
- Source files (`components`, `lib`, `pages`, `server`)

But I wonder if we really need this at all since NextJS is not supposed to be fooled by an old cache?

**Comment by SudharakaP** [comment]
@Betree : My thinking is we could make it even simpler by just using the Git hash of the checked out front-end repo. WDYT? 😄

**Comment by znarf** [comment]
@SudharakaP have a try in a PR?

**Comment by znarf** [comment]
The issue is starting to be an important problem in CI so this should now be a priority.

**Comment by SudharakaP** [comment]
@znarf : Yes, I will try this out today; I saw that too, several PRs seems to have this problem. 😄

**Comment by SudharakaP** [comment]
Okay so I think, https://github.com/opencollective/opencollective-api/pull/6274 seems to fix the issue as we are getting rid of `hashFiles` call for these larger file counts. I restarted the CI several times and it seems to be okay. 🤔
