### ISSUE TITLE
[DOCS] Update GitHub Sponsors onboarding process 

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#4334]
## Context
 
GitHub have updated their process for onboarding if you're using a fiscal host. We need to update the docs to reflect the new process. 

### What's changing?

Projects no longer need to add their own account when registering for GitHub sponsors if they're using a fiscal host. Instead GitHub uses the hosts' account details when paying our sponsors for the month. 

https://user-images.githubusercontent.com/158833/120644269-0ccb5c00-c46f-11eb-9a67-c0d4cebd1d4a.mp4

### Why are we changing it?

GitHub have made this change as there was a problem with projects adding incorrect bank details. 

### Who does this change impact?

All collectives that receive contributions through GItHub sponsors. 

### How do users use it?
 
Users register for GitHub sponsors oin GitHub, adding their fiscal host and the url for their project on registration for the waitlist. 

### Is this change optional or mandatory?

Mandatory.

### Is this change being released incrementally as a beta? What's the schedule?

GA

### When will the project be ready for release/complete?

from today. 
### Overview

Update the github sponsors area of the opencollective docs

### Changes to be made

- [x] Update the registration section
- [ ] Remove the stripe account, open collective and exec detail sections (if appropraite)

**Comment by BenJam** [comment]
Started a draft at https://app.gitbook.com/@opencollective/s/open-source-collective/~/drafts/-MYTpWOyHDHLMIc7p8IM/get/github-sponsors/

**Comment by shannondwray** [comment]
Let me know when you've had a chance to complete those last steps @BenJam and I can ensure the information is carried over into the Open Collective Docs and then when the OSC docs are live we can delete those sections from the open collective docs :)

**Comment by BenJam** [comment]
amended this a couple of days back: https://docs.oscollective.org/getting-started/github-sponsors
