### ISSUE TITLE
User menu: update the mobile version

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4335]
Followup on https://github.com/opencollective/opencollective/issues/4045#issuecomment-817450685
Design: https://www.figma.com/file/9Iq3vBOmZ2EuOacXEYD5yK/%5BDS%5D-03-Global-Components?node-id=6662%3A1914

On mobile, we want to show something more compact for the user menu:
![image](https://user-images.githubusercontent.com/1556356/120780318-4744ff80-c528-11eb-9399-4c4dfaf502e5.png)

(the menu on the last screenshot appears when you click on your profile, at the top of the 2nd screenshot)

**Comment by naman360** [comment]
Can I work on this issue?

**Comment by Betree** [comment]
@naman360 Sure! Feel free to ask if you have any question

**Comment by naman360** [comment]
Yup, I have joined slack channel , do let me know in which channel do I need to ask doubts.

**Comment by snitin315** [comment]
I will take it.
