### ISSUE TITLE
People accidentally creating duplicate Collectives when trying to apply to host

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4338]
This keeps happening and I think we need to figure out why. Somewhere in the flow people are getting tripped up and creating new Collectives instead of applying with their existing one. It might be due to #4278 but I'm not sure.

[Example](https://opencollective.slack.com/archives/C0HSLRNVC/p1622812002090800) - I've seen at least three such cases recently and there are probably more coming to support or not being discovered because they just stick with the duplicate.

**Comment by znarf** [comment]
This issue is difficult to action in this state. We'll however look at https://github.com/opencollective/opencollective/issues/4278.

@alanna maybe you should contact affected people and ask how they ended up in this situation.
