### ISSUE TITLE
Support Metrics Report May 2021

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#4339]
### Support Metrics Report May 2021

This report looks at the trends around support to help us better understand areas we need to improve and highlight key topics for the month. 

**Tickets received** 

![Capture](https://user-images.githubusercontent.com/57156267/120941748-8f5a6100-c778-11eb-8b7f-621120df4dca.png)

The number of tickets received increased by 49% from 788 in April to 1172 in May. During April we linked all the OC emails to go through FreshDesks. This meant that notifications of new applications received and expenses notifications are now coming through FreshDesk and impacting the number of tickets received. By removing blank tickets, expenses notifications where no action was required and the OCF hiring related enquiries, the rise during May was of about the same -  461 tickets compared to 462.  It is worth noting that May would be the first full month since we introduced these changes.[ You can find the detailed listings here.](https://docs.google.com/spreadsheets/d/1pO6FQzpxUXpBms43J94rxhX4toU2IP3S/edit#gid=907850428)

![Capture](https://user-images.githubusercontent.com/57156267/120941852-30e1b280-c779-11eb-820d-c270c6e7880d.png)

**Trends and Recommendations**
After removing irrelevant tickets, we had 461 that required support attention. It is worth noting the following areas:

**Expenses**

As indicated above, all user comments related to expense claims they submit now generate a new ticket in FreshDesks. We filter the information in such a way that only notifications of comments generate a new ticket and get automatically assigned to the relevant agent to look at them and address. It is worth noting that during May we started applying different tagging to expenses, in order to differentiate between general notifications (e.g. conversations between user and collective admin, general expense comments) to those expenses requiring host admin intervention. Practically it was done by tagging the relevant host as well as the nature of the ticket. 

During May OCF announced its new [Cash Assistance Policy](https://docs.opencollective.foundation/how-it-works/processes-and-limitations/cash-assistance-policy) (alongside other [important policy changes](https://opencollective.com/foundation/updates/new-policies-for-cash-assistance-outside-accounts-and-outside-entities)). As expected, that resulted in an increase of the related tickets. We have been working with the impacted initiatives on the transition to the new way of reporting on their cash assistance programs and documentation requirements and happy to report the transition is going better than expected. So far we only have one group deciding this way of operating is not going to work out for them and [they are in the process of closing their collective. ](https://opencollective.com/bull-city-mutual-aid/updates/goodbye-and-thank-you)

The increase in the number of tickets with OSC is mostly related to a number of transfers only, with those associated with transfers made to locations we have some issues with processing payments. Given [an accidental double payment processed to a user ](https://opencollective.com/ankidroid/expenses/39649#new-comment-on-expense) in India contributing to AnkiDroid @kewitz restricted auto payments to be processed to India (these require additional information for the transfer to be accepted by the local bank and normally processed manually anyway) to ensure same type of human error is not repeated. 
 
**Onboarding**

Similar to expenses, any new applications notifications received now are going through FreshDesks. This is the reason for the spike in the number of hosting application tickets. 

Onboarding related questions are still some of the common ones we receive, however there seems to be a little drop in new collectives onboarded with OCF, there is a 35% increase in the number of new groups joining OSC. Here is how it was distributed:

We approved 15 new applications for OCF  compared with 19 in April.

For OSC -  87 new collectives were approved this month compared to 64 in April. 

It seems like the slight dropping in new initiatives joining OCF is to be expected with the drop in COVID response needed and it will be really interesting to see how the nature of groups may change as new team members are joining now with the specific focus of promoting OCF as a fiscal host (and Open Collective in general) to new target groups. It seems like this may be the space to watch over the course of the next few months. 

With the process of onboarding new collectives with OSC, we are currently having a conversation around how to make the process easier and to streamline the application process a bit. Hope to have more updates on this front for the June report. 

**Virtual Cards**

There was a lot of interest in the virtual cards offering and to date we have 7 cards issued to OCF collectives and 36 cards for OSC. There was a bit of an adjustment on our and we had to upgrade to paid plan with Privacy to remove limitations on numbers of cards we issue, but given the low associated cost this seems like a good practice for us going forward and it would be good to examine the impact on the payments processing cycle during June. 

**Other things worth noting:**

Not many questions on host onboarding this month. And [pages like this sure help](https://opencollective.com/fiscal-hosting) - brilliant work on getting it integrated!

**Comment by alanna** [comment]
Thanks @alinamanko ! Any ideas about how we could better link to the new Fiscal Hosting page? I think it's great too and I'm concerned we're not making it very easy to find.

**Comment by alinamanko** [comment]
@alanna this is an option I see as possible (though I feel we can find even an easier way to find the information) - when I go to the OpenCollective page and go through the page, the very buttom of the page is looking like this:

![Capture](https://user-images.githubusercontent.com/57156267/121470681-b03de300-ca12-11eb-84aa-8428ca8e7edb.png)

When I click on Learn More button I am taken to the support section and I can't really see how I can find the new page without specifically looking for it. In my opinin there needs to be a really easy way to find it from the main page. Who should we flag on this one specifically?
