### ISSUE TITLE
Error: Payment cannot be processed... (playworkskerryproject)

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#434]
**Mail from Niall:**
> I am trying to process a €200 payment on the platform at the moment on: https://opencollective.com/playworkskerryproject/expenses#exp1834
> 
> I am getting an error message stating that: _"The payment cannot be processed as no payment source is available"_
> 
> Do you know what is causing this? Our account is linked to our paypal. I wonder is it the person who uploaded the receipt has not given their correct paypal email?

**Comment by xdamman** [comment]
To pay expenses it's not Stripe, it's PayPal.

They need to make sure that they have money on their PayPal account or that they have a payment source set up (a debit/credit card).

**Comment by nicobarretoOC** [comment]
Thanks, Xavier.
