### ISSUE TITLE
Embed contribution flow: expose a public API through channel messaging

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4341]
## User story 
As a collective admin integrating the Open Collective contribution flow on my own website (see https://docs.opencollective.com/help/collectives/embed-contribution-flow), I can hook up to various events happening in the iframe - for example, to render a custom success page when a contribution succeeds, or to redirect users somewhere else.

## Best solution for this problem
A common technique to implement this kind of behavior is to use [channel messaging](https://developer.mozilla.org/en-US/docs/Web/API/Channel_Messaging_API/Using_channel_messaging) to share only the information that you really want to share with the parent. That's how YouTube, for example, allows you to hook for various information and controls for the YouTube player (that is also embedded in an iframe).

## MVP
We could start by implementing a `CONTRIBUTION_SUCCESS` event, with some info like:
- Public contributor info (name, account ID)
- Amount contributed
- Tier

## Metrics 
- How many projects use this API
- How many large projects use this API

## Documentation 
Should be documented on https://docs.opencollective.com/help/collectives/embed-contribution-flow

**Comment by Betree** [comment]
This issue could help in the context of #4595, as a way for the event organizers to hook to the "Success" event to show a custom page on their end or to refresh the data.

**Comment by BenJam** [comment]
This sounds awesome. We should discuss this with the folks from hacktoberfest to see whether their design is too far along to incorporate it.

**Comment by BenJam** [comment]
update from convo earlir today: no need to do this for Hacktoberfest, so _next time..._

**Comment by Betree** [comment]
Requested in https://opencollective.slack.com/archives/C6JTTA4SK/p1680108289337519

**Comment by Betree** [comment]
**Events**
- [ ] `onLayoutChange`: share size (height with parent) => https://github.com/opencollective/opencollective/issues/7640
- [ ] `onContributionSuccess`
