### ISSUE TITLE
Improve leaderboard data

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4350]
We use this data for the monthly newsletter leaderboard: https://opencollective-metabase.herokuapp.com/dashboard/19

But there are a few ways it could be cleaned up. I've been doing this cleaning manually each month but if we could change the queries it would be helpful.

1. Do not include Projects (but do include revenue coming through Projects in the total contributions to the parent Collective)
2. Do not include Events (but do include revenue coming through Events in the total contributions to the parent Collective)
3. Do not include Hosts adding funds to their own Collectives as Contributions
4. Do not include distributions from Collectives to their own Projects or Events as contributions
5. Do not include transfers from Events to their Collective as contributions
6. Do not include Collectives or Hosts contributing to themselves
6. Is there any way to display USD equivalents of other currencies? Don't count 2000 MXN as more than 1000 EUR for ranking
7. Exclude these generic profiles that support uses to process bulk contributions: bitcoin-contributions, github-sponsors, benevity, schwab-charitable, fidelity-charitable
8. Do not include guest and incognito transactions
9. Do not include opencollective (always on top of 'most new backers')
10. Include the full URL not just the slug, e.g. https://opencollective.com/getsolus instead of only 'getsolus' - this helps when copying links

**Comment by piamancini** [comment]
Papercuts candidate for this sprint?
