### ISSUE TITLE
Digital Wallet Payment: Add AliPay single-payment payment method

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#4355]
Implement AliPay as a payment method for one-time donations.
Limit to compatible host currencies listed in the docs.

Docs: https://stripe.com/docs/payments/alipay

**Comment by Rhynodeeds** [comment]
no sé

**Comment by Rhynodeeds** [comment]
Tu no Sabes?

**Comment by Rhynodeeds** [comment]
Pussy
