### ISSUE TITLE
User menu closes when you click in it

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4357]
While we do want this behavior when clicking on the links in the menu, one should be able to select text or tap blank areas without closing the menu.

![Peek 2021-06-11 10-25](https://user-images.githubusercontent.com/1556356/121656067-64854b00-ca9f-11eb-97b6-43d21dff479e.gif)

**Comment by ankitzm** [comment]
I can probably fix this issue.

**Comment by SudharakaP** [comment]
> I can probably fix this issue, but I need some help to get on this page,

@ankitzm : This is the file that is concerned with the top bar profile menu; 

https://github.com/opencollective/opencollective-frontend/blob/ab5ff7aab5408c9a97230fc229bfa3cb59190c2a/components/TopBarProfileMenu.js#L53

I haven't tried this myself but you might need to play with how we handle the clicks outside of the component;

https://github.com/opencollective/opencollective-frontend/blob/ab5ff7aab5408c9a97230fc229bfa3cb59190c2a/components/TopBarProfileMenu.js#L75

Hope that's helpful. 😄

**Comment by Betree** [comment]
Seems resolved, probably by https://github.com/opencollective/opencollective-frontend/pull/8193
