### ISSUE TITLE
Transaction amounts not adding up

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4361]
See https://opencollective.com/ehf-wellington-meet-up-pizza-at-mevo-068b2b5f/transactions

This transaction does not add up.

<img width="1057" alt="Screen Shot 2021-06-12 at 2 24 56 PM" src="https://user-images.githubusercontent.com/5498878/121762449-21ec6d00-cb8a-11eb-9779-8a95c087a02b.png">

> $57.50 - $2.88 (host fee) - $1.97 (payment processor fee)= $45.15 (net amount for EHF Wellington Meet Up: Pizza at Mevo). 

$57.50 - $2.88 - $1.97 does not equal $45.15

**Comment by znarf** [comment]
There is a `taxAmount` of $7.50 reported in the database that is not exposed in the interface.

What is the expectation @Betree?

**Comment by alanna** [comment]
Ahhhh so it's GST. That's should definitely be exposed in the transaction
details.

**Comment by Betree** [comment]
I'm not entirely sure, but I think we used to display that in the breakdown. The easy fix would be to add that back:
> $57.50 - $2.88 (host fee) - $1.97 (payment processor fee) - $7.50 (GST) = $45.15

**Comment by znarf** [comment]
We don't know that it's GST specifically. So it would be something more generic like "Tax"? Or do we want to guess based on currency?

**Comment by Betree** [comment]
We are in fact storing this info in the order (`order.data.tax.id`). We should copy this info into the transaction's data.
