### ISSUE TITLE
Cannot Contribute to Particular Collective through Gift Card

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4362]
**Describe the bug**

It seems that for some reason, I cannot contribute to the [Animal Behaviour Collective](https://opencollective.com/animal-behaviour-collective) through a gift card. It just says, `Your card was declined.`. I think it should be possible to contribute to any collective through a gift card as long as the balance is valid. 🤔 🐨 

**To Reproduce**
1. Go to https://opencollective.com/animal-behaviour-collective
2. Try to do a recurring contribution using a gift card.

**Expected behavior**

The contribution should go through so long as the gift card has a valid balance. 🤔 

**Screenshots**

![Peek 2021-06-12 11-59](https://user-images.githubusercontent.com/12435965/121786650-0e370b80-cb76-11eb-8967-296ac7f995de.gif)

**Comment by SudharakaP** [comment]
Looking further, this is not specific to the above collective, I cannot seem to contribute anymore with the card at all. 

Looking at the logs it doesn't seem like I've hit any server limit so the only thing I could think of is what is suggested in this thread; https://opencollective.slack.com/archives/G46PNRCGP/p1615620270000300. 

@Betree @znarf : It seems looking at the code that when a Stripe decline happens we don't log the decline reason anywhere, we only log the decline message. 

```
 Jun 13 01:10:21 opencollective-prod-api app/web.1 error: GraphQL error: Your card was declined.
Jun 13 01:10:21 opencollective-prod-api app/web.1 error: {"locations":[{"line":2,"column":3}],"path":["createOrder"]}
```

I would suggest in addition to this we also log the decline code; https://stripe.com/docs/declines/codes. This way we could know exactly why it occurred just by looking at the logs. WDYT? 🤔 🤔 🐨

**Comment by Betree** [comment]
@alanna is facing the same error with her gift card. The last time I looked, a limitation of some kind was the best explanation since all the other recurring gift card contributions (that run on the first of the month) using the same CC  are working fine. We however looked at the configuration on Privacy with @znarf and we've set the limit at $1000, which should theoretically work given that we have 6 x $100 gift cards plugged on this credit card.

> I would suggest in addition to this we also log the decline code; https://stripe.com/docs/declines/codes. This way we could know exactly why it occurred just by looking at the logs. WDYT? 

We should definitely do that, the more info we have on the error the better. Also related: https://github.com/opencollective/opencollective/issues/4347

**Comment by znarf** [comment]
"Your card was declined." is likely the generic decline code `generic_decline`.

Have we considered that our backing Credit Card is actually locked to Open Source Collective?

**Comment by Betree** [comment]
I don't know if Privacy cards can be locked to multiple entities, but I have one contribution to OC Paris linked to that Gift Card

![image](https://user-images.githubusercontent.com/1556356/121855698-f1284700-ccf3-11eb-98fa-d0f328608caa.png)

**Comment by znarf** [comment]
@Betree Interesting because I noticed that the failures from Suds were on different Fiscal Hosts.

**Comment by SudharakaP** [comment]
After the above PR is merged we do see the decline code, but it wasn't very helpful in this case; 🤔 

```
 Jun 25 18:14:37 opencollective-prod-api app/web.1 error: Stripe Error (handled): StripeCardError, Message: Your card was declined., Decline Code: generic_decline, Code: card_declined
Jun 25 18:14:37 opencollective-prod-api app/web.1 error: GraphQL error: Your card was declined.
Jun 25 18:14:37 opencollective-prod-api app/web.1 error: {"locations":[{"line":2,"column":3}],"path":["createOrder"]}
```
So in this case as per stripe document; 

```
The customer needs to contact their card issuer for more information.
```

Can we do this? I think maybe we are doing payment which might be hitting some blocks/limits. 🤔

**Comment by SudharakaP** [comment]
@znarf @Betree : So just to clarify this has been discussed at, https://opencollective.slack.com/archives/G46PNRCGP/p1624645315089800 and François provided some screenshots from the Privacy.com side about the transaction that was declined. 

<img width="556" alt="Screenshot 2021-06-25 at 21 44 00" src="https://user-images.githubusercontent.com/12435965/124132460-b2092e00-da35-11eb-8778-ad5996fa20ee.png">

And the documentation for this error could be found here; https://support.privacy.com/hc/en-us/articles/360041447214-Why-was-a-transaction-declined-when-I-tried-to-use-a-Privacy-card-;

>An unauthorized merchant charged your card - This card has already been used with another merchant. You'll need to create another card to transact here.

which seems to indicate that it's merchant locked. I am not sure we could do anything on our side for this because my understanding is that privacy cards are either merchant locked or single-use both cases not suitable for this specific case. 🤔 🤔

**Comment by Betree** [comment]
Indeed. The strange thing is that my contribution to OC Paris is still going through, even though it's using the same card.

Maybe they introduced this single vendor limitation later, and did not enforce it for vendors used by existing cards?

**Comment by SudharakaP** [comment]
> Indeed. The strange thing is that my contribution to OC Paris is still going through, even though it's using the same card.
> 
> Maybe they introduced this single vendor limitation later, and did not enforce it for vendors used by existing cards?

@Betree : It might be the case. But the doc clearly states that it's locked to the first merchant. Thus with this payment method in use I don't think we cannot do anything regarding this. I am closing this issue, but feel free to open it in case if anyone has ideas on a workaround or alternative. 🤔
