### ISSUE TITLE
Transaction linking to wrong URL

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4363]
Looking at https://opencollective.com/pytorch-ignite-org - there is a single transaction, which is the expense paid from Season of Docs.

![Screen Shot 2021-06-14 at 12 14 45 PM](https://user-images.githubusercontent.com/5498878/121826106-2b044800-cd0a-11eb-9d7c-d44535a8767e.png)

However, if you click on that expense title, you get a 404. It's trying to send you to https://opencollective.com/pytorch-ignite-org/expenses/42605 but the correct link is https://opencollective.com/season-of-docs-2021/expenses/42605.

**Comment by Betree** [comment]
This one was reported in https://opencollective.slack.com/archives/G46PNRCGP/p1623409906075300 and fixed in https://github.com/opencollective/opencollective-frontend/pull/6479, but we haven't deployed the fix yet
