### ISSUE TITLE
Fix transaction source for Season of Docs

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4364]
I apologise in advance for not breaking this up into multiple smaller issued but I'm not sure how to sort that out.

See https://opencollective.com/pytorch-ignite

There's a single transaction, the payment of the Season of Docs stipend.

This money came from https://opencollective.com/season-of-docs-2021

But it was not possible to select this Pytorch Collective as the payee, because we can't do expenses between Collectives in different hosts.

So instead, the Host was the payee of the expense (https://opencollective.com/pytorch-ignite-org), and then the host admin added the funds to the Collective. 

The problem is, you must specify a source when adding funds, and they selected Google Open Source, because they were not allowed to select the Season of Docs Fund, because Google Open Source is the ultimate source of the funds.

![Screen Shot 2021-06-14 at 12 22 47 PM](https://user-images.githubusercontent.com/5498878/121826319-3f951000-cd0b-11eb-92c4-b015cc09b518.png)

However, this is a problem because it may have debited the Google Open Source profile when that should not be the case. The money was already paid from that Google profile to the Season of Docs Fund, so this would be like double charging it.

I can think of a couple possible solutions:
* Update the source of funds to be the Host, pytorch-ignite-org
* Update the transaction to somehow directly link Season of Docs as the source of funds instead of Google

What's the best way to go about this? There will be several similar transactions coming because there are about 10 stipends going from Season of Docs to Collectives in other Hosts.

For this Pytorch example, it's ok to show the Pytorch Host as the payee because that's also the name of the project. But there are other situations like NumFOCUS who is the Host for about 5 Season of Docs projects. If it shows just the Host as the payee, then on the Season of Docs page there's not a good list of all the projects they actually paid. I guess it's not the end of the world but it would be much better if these transactions could somehow get linked to the ultimate payee Collective.

This also makes me wonder, is it OK that anyone can create a Fiscal Host and then have access to Add Funds with Google's Fund as the source? Anyone could just set up a Host and then create a transaction of Google paying them $100k. The money would not actually move between bank accounts, but wouldn't this mess up the balance of Google's Fund? It seems like only admins of the Host of the Fund (in this case, OSC) should be able to declare that Fund as the source of added funds. So how did this admin of an unrelated Host do that?

It also makes me wonder, why could they select Google Open Source but not Season of Docs in the first place? They are both Funds under OSC. But if they HAD selected Season of Docs as the source, it would still be a double charge, right? Once for the expense, once for the added funds?

**Comment by znarf** [comment]
> Update the source of funds to be the Host, pytorch-ignite-org

This is the right call in this situation because the money needs to move out of the pytorch-ignite-org budget, which is not the case today. They could also have used the Contribution Flow for this.

>   If it shows just the Host as the payee, then on the Season of Docs page there's not a good list of all the projects they actually paid.. [...] I guess it's not the end of the world but it would be much better if these transactions could somehow get linked to the ultimate payee Collective.

If its not the end of the world, then let's stick to it because as of today this is the proper way. We can happily edit the descriptions of the Transactions for clarity and transparency.

> This also makes me wonder, is it OK that anyone can create a Fiscal Host and then have access to Add Funds with Google's Fund as the source?

Google Open Source is not a Fund but an Organization. We're historically supporting this behavior where anyone can "Add Funds" _from_ this profile. We know this can eventually lead to accounting problems if we end up activating budget for this profile. We're ok with it, it's accepted since forever. I'm not against revisiting but this eventually less flexibility for Host Admins.

This is also why they could pick "Google Open Source" and not "Summer of docs" as source.

**Comment by znarf** [comment]
Done.

**Comment by alanna** [comment]
Thank you @znarf - yes that makes sense. I was misunderstanding what was a Fund vs an Org in the process (@piamancini please note this in case we are moving Google to be a Fund in the future).

I will leave this issue open because there are likely a few more of these coming through where we might need to update the transaction source.

**Comment by znarf** [comment]
@alanna Can we close this?
