### ISSUE TITLE
Error while creating Wise's recipient

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4365]
Trying to pay this expense: https://opencollective.com/season-of-docs-2021/expenses/42601

Get this error:

<img width="806" alt="Screen Shot 2021-06-14 at 4 27 35 PM" src="https://user-images.githubusercontent.com/5498878/121839267-c6f37b00-cd2d-11eb-9311-a24c6b56909e.png">

We thought it might be the special character `#` in the address field, so we took that out, but it's still not working.

**Comment by alanna** [comment]
I'm still unable to pay this. Can someone have a look? @znarf @kewitz

**Comment by kewitz** [comment]
Hi @alanna I found some weird errors on our logs and I think you should reach out to Wise's support.
I also notice that the payee is Open Source Foundation, so this might be related to the issue.

This is the actual error we're receiving from Wise's API:
```
TransferWise validation error: We cannot currently accept payments to this recipient.
```
