### ISSUE TITLE
Implement refunds for "Added Funds"

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#4369]
## User story 
Right now there is no easy option to process a refund in the scenario where funds are added using the host balance. This could result in a scenario [of a mistake made by a host admin](https://opencollective.freshdesk.com/a/tickets/23033) or on some occassions where a host receives contributions which could not be identified with a specific collective and adds them to their balance as an interim solution, with the intention of this action to be reversed once the collective reaches out to enquire of the status of that specific contribution made. 

Right now, the refund button will show for the transaction recorded, but once this option is selected the user will receive the following error message:

![Capture](https://user-images.githubusercontent.com/57156267/122122151-87897380-ce80-11eb-8fe9-154649901bcf.png)
 
## Best solution for this problem
It would be great if a refund process was in place, in the same matter as with standard credit card payment and where the budgets could be adjusted without the need of us making a manual change in the database (which is the current practice).

**Comment by znarf** [comment]
In theory, that should really be the simplest case for a refund. No excuse on our side to delay implementation.

**Comment by BenJam** [comment]
++ I just hit this trying to revert a transaction (added funds) for Salesforce https://opencollective.com/salesforce/transactions?kind=ADDED_FUNDS back into Open Source Collective.
