### ISSUE TITLE
Says no Wise balance but there is

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4371]
I'm trying to pay https://opencollective.com/event-in-tautahi-cd532492/expenses/42965

There is balance but it won't let me do it.

<img width="798" alt="Screen Shot 2021-06-17 at 10 39 48 PM" src="https://user-images.githubusercontent.com/5498878/122381484-19969680-cfbd-11eb-95e1-9b2053b91646.png">

**Comment by alanna** [comment]
@kewitz @znarf is this related to the other Wise issue?

**Comment by kewitz** [comment]
@alanna the issue here is related to the collective balance.
It is saying that the collective doesn't have enough money to cover the expense considering fees.

**Comment by alanna** [comment]
Ah crap.... I wonder how many years #1073 will be open until we fix it 😅

Can the error text be updated to say the Collective/Event/Fund name instead of "you" so it's more clear?

**Comment by alanna** [comment]
@kewitz I revised the expense down by $1 in anticipation of fees, and paid it. It went through. But then there was $1 left in the budget! So why did it block the expense for fees when no fees were charged?

**Comment by kewitz** [comment]
@alanna sure, I'll fix the message to be more precise about what is going on with the balance.

Related to the block, you actually rounded it from $35.76 to $34.
There were $0.76 cents of payment processor fees resulting in $1.00 left.
![Screenshot from 2021-06-24 14-01-30](https://user-images.githubusercontent.com/2119706/123304084-e1c7ab80-d4f4-11eb-819b-fdff7e6a0861.png)
