### ISSUE TITLE
Move to GitHub New Issue Config

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4375]
Minor improvement to move to the [new GitHub issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) with the use of a `config.yml` file. This will ensure we can also specify some links in to our slack channel etc when the user click on creating a new issue. 🐨 

Suggest adding,

- Issue tracker link (https://github.com/opencollective/opencollective/issues)
- Slack channel link (http://slack.opencollective.com/)
- Link to our documentation (https://docs.opencollective.com/help/)
- Link to the security vulnerability policy (https://github.com/opencollective/opencollective/security/policy)
- Disabling issue creation on all the repos other than the opencollective repo. 

We shall do the following main repos. 🐨 

- [x] opencollective
- [x] opencollective-frontend
- [x] opencollective-api
- [x] opencollective-pdf
- [x] opencollective-images
- [x] opencollective-bot
- [x] opencollective-changelog
- [x] opencollective-rest

I thought these are the main repos that people will normally go to; if I am missing anything feel free to let me know. 😄 🐨

**Comment by SudharakaP** [comment]
This is complete. Let me know if you see anything else (such as other links) to be added to the `config.yml` file

**Comment by Betree** [comment]
> Disabling issue creation on all the repos other than the open collective repo.

@SudharakaP This is really cool! I just tried merging the one on the PDF service to see how it looks: https://github.com/opencollective/opencollective-pdf/issues/new/choose - it's pretty neat!

![image](https://user-images.githubusercontent.com/1556356/122719545-9bf9b180-d26e-11eb-977b-303de96aecc2.png)


I'm just a bit concerned that having a Slack link here could incentive people to report issues on Slack rather than Github, but that's no blocker for me.

@znarf @kewitz, any opinion?

**Comment by znarf** [comment]
Looks good. I'm ok people complaining on Slack, it's not always a bad experience.

**Comment by SudharakaP** [comment]
> > Disabling issue creation on all the repos other than the open collective repo.
> 
> @SudharakaP This is really cool! I just tried merging the one on the PDF service to see how it looks: https://github.com/opencollective/opencollective-pdf/issues/new/choose - it's pretty neat!
> 
> ![image](https://user-images.githubusercontent.com/1556356/122719545-9bf9b180-d26e-11eb-977b-303de96aecc2.png)
> 
> I'm just a bit concerned that having a Slack link here could incentive people to report issues on Slack rather than Github, but that's no blocker for me.
> 
> @znarf @kewitz, any opinion?

Thanks. I was wondering about it too, we could remove it; but I thought people might find it useful to be pointed to our Slack channel as well. Maybe we'll see how it goes and if too much activity on slack we can remove it. 🐨  😄

**Comment by SudharakaP** [comment]
All of these are merged and seems to work fine, so I am closing this issue. 😄
