### ISSUE TITLE
Character `>` in project tagline renders as `&gt;` on overview of all projects

### ISSUE THREAD

**Issue by vlcinsky** [opencollective/opencollective#438]
Tried to edit `doit` tagline text to `tasks => { doit + shell + python } => done`.

This renders fine on project page, but when listing all open source projects page, the text renders with `>` replaced by `&gt;`.

**Comment by asood123** [comment]
ah, we are sanitizing strings and it's replacing it. I changed it manually on the backend. Thanks for reporting.

**Comment by vlcinsky** [comment]
Thanks @asood123 

A question: I we ever have to touch the tagline (change a space, a character, a word), would it again require the magic touch in backend?

**Comment by asood123** [comment]
Jan - yes backend will sanitize any changes you make :(. It's on our list
to fix. I know it's still a hassle to ping us to change it but we are here,
whenever and however often you want to change it.
