### ISSUE TITLE
Add Search for Updates (by Collective, Title, Tags, ID, etc)

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4384]
Now that #3918 is completed we can proceed with adding search for updates. The Figma design for this is given at, 

https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=12788%3A154030

![Home](https://user-images.githubusercontent.com/12435965/122873259-655f7d80-d2e6-11eb-9cd8-7fca6272ef58.png)

**Comment by Betree** [comment]
I recommend looking at what was done in https://github.com/opencollective/opencollective-api/blob/99054d9b3121c191c42ec68402a9bc7e231303ff/server/graphql/v2/query/OrdersQuery.ts#L116 for inspiration, we used the same approach in `TransactionsQuery` and `ExpensesQuery`
