### ISSUE TITLE
Addition of Emoji by Two Seperate Users

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4387]
**Describe the bug**

It seems that two users are adding and removing the same emoji we have some issues. 

**To Reproduce**
1. Login and go to conversations or updates for a collective.
2. Create a new update or conversation. If it's an update you can try with a update comment. If it's a conversation this will work with the conversation itself or the conversation comments. 
3. Add an emoji reaction to the comment.
4. Now log in as a second user go the the same comment and add the same emoji you added before. 
5. Log back as the first user and try to remove the same emoji. 

Sometimes this seems to work but sometimes it doesn't even let the second user add the same emoji; or when the screen is refreshed it goes back to count 1. 

To further explain this issue I've created the below screen-cast. I think we need to see carefully how we are doing these emoji count updates. 🤔 😄 

**Expected behavior**

The emoji count should go from 2 to 1. 

**Screenshots**

![Peek 2021-06-22 23-30](https://user-images.githubusercontent.com/12435965/123047417-1f6feb80-d3b2-11eb-9945-cbbb2a1d4680.gif)

**Comment by Betree** [comment]
Good catch, that might be related to the `optimisicResponse`.
