### ISSUE TITLE
Adding funds to Funds should not write a debit to the transaction list

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#4388]
I've done this a few times:

- Create a fund for an organisation
- Send an invoice
- Invoice is paid into OSC's account
- I add the funds to the Fund

This creates both a credit and a debit, because the source and destinations of the funds is the Fund itself. But, like organisations, we don't need the debit. As is we are manually removing the debit to ensure that the balance is non-zero and available for the organisation to use.

**Comment by znarf** [comment]
Fixed in https://github.com/opencollective/opencollective-api/pull/6764
