### ISSUE TITLE
Fake advertising, or not?

### ISSUE THREAD

**Issue by peterennis** [opencollective/opencollective#439]
All contributions are equal but some are more equal that others.

![capture185](https://user-images.githubusercontent.com/140737/31043662-d1554662-a574-11e7-9b7f-4afbb65bcb0a.png)

**Comment by piamancini** [comment]
@peterennis they made a contribution before the collective was created. The point you raise (I guess based on the title) is fair. We don't enable that anymore. 
Thanks for the alert on the avatar!
