### ISSUE TITLE
[PROJECT] integrate with accounting tools and practices via exports and reports

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4396]
## Overview
Open Collective does not desire to become a fully featured accounting platform (like QuickBooks or Xero), but our users, especially larger fiscal hosts with established financial processes, need to integrate Open Collective with their accounting operations. We also do not desire to do a deep technical integration (and want to enable users to choose their own accounting tooling, not only the ones we've integrated with), so we want to focus on data export formats to better match standard accounting formats.

Related issues: #3983 #3340 #3875 #3552 #4039 #3961 #3689 #4366 #4018 #3934 #4382 #4361 #2798 #4300

## Owner
TBD... probably needs @znarf because of the ledger implications, and also someone from the host admin side of the team.

## Prioritization

- Does this serve our mission?

Open Collective is an interface between collaborative Collectives and the outside world, seeking to enable them to retain their essence as circles, while being able to operate in the world of accounting, taxes, and legal entities. Backoffice tooling for this function is essential.

- Will this help to make us financially sustainable within a year?

Our main revenue source now, and the area we see the most future potential, is large scale hosts, all of whom need to do tax reporting and integrate with accounting systems.

- Can this make us move faster?

It will feel slower at first because these are mostly invisible features only host admins care about, but it will definitely help more hosts decide to use Open Collective faster and onboard more smoothly.

- Does this increase quality? 

Yes, this is a key area of ledger-debt and technical-debt in the platform.

- Does this add technical debt?

No, it will reduce technical-debt.

- Is it feasible to build and maintain with our current team and runway?

It would take a decent amount of time and attention from Francois and either Pia or Alanna, to go deep on both the ledger and accounting functionality sides. But if we decide that's worth it, then we can manage it.

- What insight or research is this project based on?

Our own experience operating hosts and customer development discussions with new hosts.

- Is this problem already solved elsewhere?

We currently solve this in our first party hosts with a messy combination of manually cleaning our current data exports and trying to achieve what we need with metabase. This takes a lot of time from developers and accountants (expensive!) and is quite error prone (we have major issues every time with taxes/audit exports). Existing accounting software does solve this but our data has to match up with them.

- How will we measure our success? Do we have a baseline today that we can compare this against?

Less time spent on tax and audit data crunching for our own hosts.
Wider adoption of OC as a system by existing orgs becoming new hosts.
Faster onboarding of new hosts who need to set up their accounting processes.

- How well do we understand the complexity of the problem, feature to be added or user need to be addressed? 

There's still a fair amount of discovery to be done. We're clear about the desired end-state but need to figure out all the details.

- What is the estimated timeframe for delivering this project? 

?

## Kick-off meeting
?

### Roadmap & Timeframe
?

### Success metrics
Less time spent on tax and audit data crunching for our own hosts.
Wider adoption of OC as a system by existing orgs becoming new hosts.
Faster onboarding of new hosts who need to set up their accounting processes.

### Release planning
?

**Estimated delivery date**
?

- Which aspect(s) of the platform does this change impact?
Ledger, host settings, data exports.

- Which group(s) of users will benefit from this change?
Hosts

- Is this project in response to a user-requested feature? If so who requested it (link to feature request if available)?
Yes - all new hosts ask about integration with their accounting systems, plus our own experience with our hosts.

- Is this project related to any similar work we have done, or are planning on doing in the next three months?
Not really?

### Next steps

- [ ] Open up any appropriate project issues
- [ ] Open a documentation issue, link it to this one
- [ ] Open a release issue, link it to this one
- [ ] Create a project board, add this issue to the description, add any issues created above 

## Project Closure

- Close all relevant project issues
- Open up issues for improvements 
- Post comm's according to comm's plan (most likely in release issue)
- Post project screencast on documentation slack channel 
- Post project closure in newsletter slack channel 
- Celebrate!!

**Comment by alanna** [comment]
Adding #4497 to this

**Comment by alanna** [comment]
Adding local tax stuff here as we cannot align with accounting if we don't handle tax correctly #4493 #4532 #4494 #1552 #4366 #vat

**Comment by alanna** [comment]
Related: #6121

**Comment by BenJam** [comment]
closing in favour of #3983
