### ISSUE TITLE
backers / sponsors avatars in READMEs are not retina

### ISSUE THREAD

**Issue by dasilvacontin** [OpenCollective/OpenCollective#44]
> I just noticed that the backers/sponsors are not displayed with a retina image. IMO they should – looks more official / professional / in active care / you-name-it.

> Yes. How can we do that? I guess we will have force the height in the HTML

> Yep, force the height in the HTML. Otherwise, maybe some hacks using svg where the svg includes an img with the forced height. (so that the HTML we have to paste is more compact) Maybe there's other ways to do it

> yeah I want to keep the html compact, but I also wanted to keep flexibility to improve the design without having to change the HTML

> with a card design like on http://opencollective.com/mochajs (but probably more compact than that)

discussion in #mochajs between @xdamman and @dasilvacontin

**Comment by xdamman** [comment]
Is there anyway to do this without having to force the width or the height in the HTML?

Otherwise, if we want to change the way it looks, we will have to change the HTML which would be a bummer.

For example, we were considering showing a small card for each backer/sponsor like on https://opencollective.com/mochajs (but smaller), also with the amount they contributed.

**Comment by dasilvacontin** [comment]
Looks like you _can_ embed images with fixed sizes inside svg:
- https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/SVG_Image_Tag
- http://stackoverflow.com/questions/6249664/does-svg-support-embedding-of-bitmap-images

You might be able to dodge changing the HTML this time. :)

**Comment by xdamman** [comment]
The issue with that method is that we need to know in advance the width and height:

```
* If you do not set the height or width attributes, they will be set to 0.
* Having a height or width attribute of 0 will disable rendering of the image.
```

**Comment by xdamman** [comment]
This will do: https://github.com/image-size/image-size
