### ISSUE TITLE
500 error when attempting auto-tweet on donation

### ISSUE THREAD

**Issue by hollomancer** [opencollective/opencollective#440]
REPRO
1) Access https://opencollective.com/:slug/connect/twitter
2) Provide your Twitter account authorization to connect to OpenCollective

RESULT
 `{"error":{"code":500}}`

NOTES
Following instructions at https://github.com/opencollective/opencollective/wiki/Automatic-Thank-You-Tweets

**Comment by asood123** [comment]
Might be the same issue here. opencollective.com/mochajs/connect/twitter.
