### ISSUE TITLE
2FA on expenses authorization misbehaves

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#4401]
**Describe the bug**
When trying to process an expense for payment (sending money to a user's bank account), the host admin receives a notification of 2FA being required but without the option to input the information. The admin needs to press the Go to Pay button again to be able to access the input window. This is a functionality that has changed as previously, you could input the code bellow the message received directly. 

**To Reproduce**
1. Go to an expense ready to be processed for payment.
2. Click on Go to Pay button.
3. A notification will pop up requiring the user to complete the payment but without the option to add the code. 

![Capture](https://user-images.githubusercontent.com/57156267/123562303-0deb7100-d802-11eb-8e5c-356c412e4d7b.png)

4. Click the Go to Pay button again. This time the input window will appear below the payee account details. 

**Expected behavior**
There shouldn't be multiple tries. I would expect to have the ability to incorporate the code straight away.

**Comment by Betree** [comment]
@alinamanko was this solved? I just tried to reproduce without success

![Peek 2021-07-30 19-37](https://user-images.githubusercontent.com/1556356/127691033-aa891b14-252b-4f04-9ecf-4c2a124d039b.gif)

**Comment by alinamanko** [comment]
@Betree that issue was resolved it seems - I will close it now.
