### ISSUE TITLE
Change Positioning of the Notification Icon in Navbar

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4404]
We have to change the positioning of the notification icon in the navbar to the opposite side of the Avatar and remove the username of the user according to the new design. 

https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=12788%3A152534

![image](https://user-images.githubusercontent.com/12435965/123710525-c675dc80-d823-11eb-91e3-a77a110ca871.png)

I tried to do this as part of https://github.com/opencollective/opencollective/issues/4345 but later reverted the code as it seems to break a lot of E2E tests since we are checking for the username to see if the user has logged in. 

My initial thinking is to check for the logged in user by clicking on the avatar and verifying the name. 

- [x] Change all places where `topbar-login-username` is refered to.

- [x] Adjust the following test to click on the avatar and then verify the username. 

https://github.com/opencollective/opencollective-frontend/blob/875b38878fa2c37321931244f1b0bcd183b4860f/test/cypress/support/commands.js#L305-L311

**Comment by SudharakaP** [comment]
@Betree : Let me know if you agree with the proposed approach for this. Thanks. 🤔 🐨

**Comment by Betree** [comment]
Looks good to me
