### ISSUE TITLE
Default to Updates being on for Events

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4406]
We've had some support requests from people who can't work out how to email event attendees, and the issue is that Updates is set to `disabled` in their settings. I think this should default to being enabled, because emailing attendees is a very common task. If people don't want to use it they can turn it off.

**Comment by Betree** [comment]
Unless I'm missing something, it seems that this is already the case. I just tried creating a new event, and the Updates section was activated by default.

**Comment by alanna** [comment]
Hmmm! That's odd because the user I was just supporting didn't turn it off
that she knew of, but she was stuck because it was turned off.

**Comment by Betree** [comment]
When was the event created? This change only occurred 3 months ago (https://github.com/opencollective/opencollective/issues/4122) around the 15th of April. If the event was created before that, it's possible that it used the old default.

**Comment by alanna** [comment]
It's this one:
https://opencollective.com/the-connectorship-project/events/do-good-jobs-x-the-connectorship-project-7ff21cc4

**Comment by Betree** [comment]
The section looks enabled in their settings; it should therefore be visible for any logged-in admin.

**Comment by alanna** [comment]
OK I guess it was a fluke
