### ISSUE TITLE
Add ToolTip for Changelog Notification Icon

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4407]
This is a small thing that we've missed in https://github.com/opencollective/opencollective/issues/4345. The user should see a tool-tip when hovering over the notification icon; 

![Desktop](https://user-images.githubusercontent.com/12435965/123902520-d7a51300-d921-11eb-8ae2-631bca78f38a.png)

**Comment by snitin315** [comment]
I will take it.

**Comment by SudharakaP** [comment]
> I will take it.

Thanks @snitin315 👍🏽
