### ISSUE TITLE
Clicking through on invited expense again leads to odd state

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4409]
If you are invited to submit an expense, go through that process, and then later want to go check on the expense, users sometimes go back to their email and click the link again. If they do, you end up at this odd state with the expense details and the edit button missing, and part of the form showing.

<img width="780" alt="Screen Shot 2021-06-30 at 11 07 46 PM" src="https://user-images.githubusercontent.com/5498878/123950640-0392c800-d9f8-11eb-82ca-580ce0db94b5.png">

If an invited expense has already been submitted by the invitee, going back to the link should ignore the `?key=123wcbt456oq6bt88er90` part and just load the normal expense page.

**Comment by SudharakaP** [comment]
Related discussion found at; https://opencollective.slack.com/archives/C0RMV6F8C/p1626732411276900. Will investigate more on this issue today. 😄

**Comment by SudharakaP** [comment]
This is fixed by https://github.com/opencollective/opencollective/issues/4409 and therefore closing. 👍🏽
