### ISSUE TITLE
404 error accessing banner.md

### ISSUE THREAD

**Issue by hollomancer** [opencollective/opencollective#441]
REPRO
1) Connect to https://opencollective.com/:yourcollective/banner.md, where `yourcollective` is your... collective.

RESULT
404 error.

**Comment by asood123** [comment]
Hi Conrad - this is working for me.
https://opencollective.com/mochajs/banner.md. Is there a particular
collective where it's failing? (you need to remove the colon)

**Comment by piamancini** [comment]
hey @hollomancer You are probably talking about operation code. it's working for me https://opencollective.com/operationcode/banner.md

**Comment by piamancini** [comment]
@hollomancer this should be solved. Can you please confirm son we can close? thanks!

**Comment by piamancini** [comment]
closing this, @hollomancer let us know if needs to be reopened.
