### ISSUE TITLE
Can't send event update despite being admin

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4410]
I am an admin of the parent Collective, but when I try to send an update on an event it says I can't because I'm not an admin? I am logged in.

<img width="1264" alt="Screen Shot 2021-07-01 at 3 07 16 PM" src="https://user-images.githubusercontent.com/5498878/124058771-210a7500-da7e-11eb-9190-57293b605437.png">

event: https://opencollective.com/ehf-wellington-meet-up-pizza-at-mevo-068b2b5f

**Comment by alanna** [comment]
I thought it might be because the event was past, so I tried creating a new event on staging - same issue. Can't create an Update.

**Comment by Betree** [comment]
Probably introduced in https://github.com/opencollective/opencollective-frontend/pull/6537

**Comment by Betree** [comment]
Fix deployed
