### ISSUE TITLE
Event Update going only to core contributors, not all attendees

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4411]
<img width="465" alt="Screen Shot 2021-07-01 at 3 14 32 PM" src="https://user-images.githubusercontent.com/5498878/124059383-1e5c4f80-da7f-11eb-86ce-60b6ad164b7f.png">

The organizer of [this event](https://opencollective.com/the-connectorship-project/events/do-good-jobs-x-the-connectorship-project-7ff21cc4) is trying to send an update, but it's only giving her the option to send it to core contributors. She needs to send it to all attendees.

**Comment by Betree** [comment]
I tried to reproduce with another collective without success.

Looking at the audience query for this collective, I see:
```
CORE_CONTRIBUTOR	4
USER	29
```

@alanna Do you know when this happened? Having the exact date could help to understand if there's an issue.

**Comment by alanna** [comment]
I am pretty sure it was on the date that I raised this issue. But if it's not happening any more it's going to be hard to track down. Might not be worth it.
