### ISSUE TITLE
Nav bar items sometimes go missing on Event

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4413]
So far I have only seen this on Events and it seems to be working normally on Collectives.

Main Event page nav bar:

<img width="948" alt="Screen Shot 2021-07-01 at 3 25 34 PM" src="https://user-images.githubusercontent.com/5498878/124060184-99723580-da80-11eb-8a20-a916994520f5.png">

Nav bar when on /contribute page (Connect is there):

<img width="817" alt="Screen Shot 2021-07-01 at 3 26 26 PM" src="https://user-images.githubusercontent.com/5498878/124060235-b9a1f480-da80-11eb-9363-ee42c51a8db6.png">

Nav bar on the transactions page (Connect is missing):

<img width="910" alt="Screen Shot 2021-07-01 at 3 28 23 PM" src="https://user-images.githubusercontent.com/5498878/124060377-0980bb80-da81-11eb-9935-5a48694340fc.png">

Nav bar on expenses page (Connect and About are missing):
<img width="860" alt="Screen Shot 2021-07-01 at 3 30 05 PM" src="https://user-images.githubusercontent.com/5498878/124060474-3af98700-da81-11eb-9a6c-23b9cfa2afa3.png">

**Comment by Betree** [comment]
Things got a bit improved in https://github.com/opencollective/opencollective-frontend/pull/6537 regarding consistency, but this bug still exists for the "About" section.

The simplest and most consistent fix I can think of would be to add an entry in `Features` like  `LONG_DESCRIPTION` and add this new field to the `NavBarFields` fragment.
