### ISSUE TITLE
Hide platform tips on Open Collective's budget

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4414]
As per https://github.com/opencollective/opencollective-frontend/pull/6558#discussion_r661785266:
>  In the context of Open Collective budget, that will be noisy to have platform tips there.

Achieving this requires updating the cache for this query on the API.

**Comment by Betree** [comment]
@znarf I don't especially agree with this proposal: I think it's nice for contributors to see their tips if they go to Open Collective's profile. After that, if anyone needs to have a different look at Open Collective's accountability the right place to go is the transactions page.

**Comment by znarf** [comment]
@Betree Ok, I'm good with the current state then!

**Comment by Betree** [comment]
Alright, closing for now. We can re-discuss that later if needed
