### ISSUE TITLE
Error on host refund payment: "The preapproval key can't be used before the start date or after the end date"

### ISSUE THREAD

**Issue by regenhans** [opencollective/opencollective#442]
When we  click to pay expenses uploaded by a collective  we get an error banner "The preapproval key can't be used before the start date or after the end date". 

<img width="1678" alt="screenshoot" src="https://user-images.githubusercontent.com/6634296/31056995-e06182b0-a6a0-11e7-8bd3-8cbfeb0cb5e2.png">

Type of User: Host
Host: HackerGarage
Collective to refund expenses : GDLJS

**Comment by piamancini** [comment]
solved by refreshing paypal's pre-approval key
