### ISSUE TITLE
Estimated Annual Budget isn't calculated correctly

### ISSUE THREAD

**Issue by DataDrake** [opencollective/opencollective#4420]
**Describe the bug**
There seems to be an issue where the Estimated Annual Budget for a Collective isn't being calculated correctly. The "Monthly recurring" total reported in the tooltip for "Estimated Annual Budget" in the Budget section of the Collective page is greater than 1/12th of the total reported in the text for "Estimated Annual Budget". "Monthly recurring" appears to be correct based on the contributions made this month. 

**To Reproduce**
1. Go to https://opencollective.com/getsolus
2. Scroll down to the "Budget" section
3. Hover over "Estimated Annual Budget" in the sidebar
4. View "Monthly recurring" in the tooltip
5. View the total presented beneath "Estimated Annual Budget"
6. Observe that "Estimated Annual Budget" is less than 12 x "Monthly recurring"

**Expected behavior**
The "Estimated Annual Budget" should be calculated as:

```
Estimated Annual Budget = 12 x Monthly + Yearly + One-time
```

If "Monthly recurring" is calculated correctly, "Estimated Annual Budget" should be no less than 12 times that value.

**Screenshots**

![Screenshot from 2021-07-02 16-17-21](https://user-images.githubusercontent.com/4991377/124324476-02c17980-db51-11eb-98d9-df70a2a1a733.png)

**Additional context**

The expected algorithm is documented [here](https://github.com/opencollective/opencollective-api/blob/7190454f9b123f86193bdcf8e5739b417e75ca93/server/lib/budget.js#L298) along-side the query I believe is used to calculate the value.

There is a [similar query](https://github.com/opencollective/opencollective-api/blob/7190454f9b123f86193bdcf8e5739b417e75ca93/server/lib/queries.js#L135) used for other purposes, but you'll note that the first part of the query where the Monthly portion is calculated is quite different between the two queries.

Without digging too deeply, I can say that the [following part](https://github.com/opencollective/opencollective-api/blob/7190454f9b123f86193bdcf8e5739b417e75ca93/server/lib/budget.js#L307) of the first query has a smell to it:

``` SQL
ROUND(AVG(t."netAmountInCollectiveCurrency"))
```

**Comment by Betree** [comment]
@DataDrake Sorry for the delay it took to look into this! On top of some ledgers changes we've made since this issue was opened, I've created https://github.com/opencollective/opencollective-api/pull/7413 which should hopefully simplify the way we compute this number and fix the root causes for this issue.
