### ISSUE TITLE
Link to manage recurring contributions is wrong for guest contributors

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4423]
**Describe the bug**
In the "thank you" emails (and probably others) we send a link to edit your recurring contributions created like this:
> `${config.host.website}/${fromCollective.slug}/recurring-contributions`

It's problematic for guests, because their `slug` changes as soon as they sign in. So they end up on a "Not Found" page, with an URL like `/guest-x5df6df/recurring-contributions`.

**Expected behavior**
I think the simplest fix for guests would be to link directly to `${config.host.website}/recurring-contributions`, since this page automatically redirects to the user profile.

**Comment by znarf** [comment]
That could be solved by having the unified recurring contributions page.

Todo:
 - [ ] https://github.com/opencollective/opencollective/issues/4931
-  [ ] close this issue and favor the one where guest slugs are not updated #4876

**Comment by Betree** [comment]
This was resolved in https://github.com/opencollective/opencollective-api/pull/6468 but we still want to have a consolidated page for recurring contributions: https://github.com/opencollective/opencollective/issues/4876
