### ISSUE TITLE
Transactions period filter: improve behavior for "End Date"

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4424]
In the transactions period filter (but this might be true for expenses/order filter too), if you pick the same day for Start Date / End Date, you will usually end up with no results. This is because the filter translates this query to:
> startDate: 2021-06-01 00:00:00
> endDate: 2021-06-01 00:00:00

While `endDate` should really be `2021-06-01 23:59:59`, to make sure we include the transactions happening during the day.

![image](https://user-images.githubusercontent.com/1556356/124448762-118f7280-dd83-11eb-89b8-7d36cf267fea.png)

**Comment by ersachin3112** [comment]
I will take it.
