### ISSUE TITLE
Delete duplicate accounts for Paul

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#443]
Slack from Paul:

> hello, hope you can help me, not very urgent though. I've ended up with 4 Open Collective accounts and want to merge or delete the others. Only backed 1 project on one of them(...)

> this seems to have happened because I use login email addresses like (...)

Nicolas reply:
> Can you tell us which is the email account you want to keep?

Paul:

> social.coop@(see email on support channel)...

**Comment by piamancini** [comment]
done
