### ISSUE TITLE
Support Metrics Report June 2021

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#4436]
### Support Metrics Report June 2021

This report looks at the trends around support to help us better understand areas we need to improve and highlight key topics for the month. 

**Tickets received** 

![capture](https://user-images.githubusercontent.com/57156267/124844080-78ad6100-dfe7-11eb-804a-17379f72202d.png)

The number of tickets received increased by 24% from 1,172 in May to 1,452 in June. During April we linked all the OC emails to go through FreshDesks. This meant that notifications of new applications received and expenses notifications are now coming through FreshDesk and impacting the number of tickets received. By removing blank tickets, expenses notifications where no action was required, the rise during June was 27% with 590 tickets compared to 461 in May. [You can find the detailed listings here.
](https://docs.google.com/spreadsheets/d/1pO6FQzpxUXpBms43J94rxhX4toU2IP3S/edit#gid=1860825127)

![capture](https://user-images.githubusercontent.com/57156267/124844211-cc1faf00-dfe7-11eb-80f5-d86e0de5ce0f.png)

**Trends and Recommendations**
After removing irrelevant tickets, we had 590 that required support attention. It is worth noting the following areas:

**Expenses**

There is quite a significant increase in expense related enquiries and comments related both to OCF and OSC. 

OSC saw an increase due to the big payouts resulting from Season of Docs and the FundOSS 1st round coming to a close, which resulted in the obvious increase of volumes we processed through the month as well as having a big wave of new submitters coming through who are less familiar with the process of submitting expenses, which naturally resulted in an increase in questions raised. 

The contributors to the increase with OCF vary - the main contributors are follow-ups as part of cash assistance requests (though it looks like these volumes, in general, seem to come down), enquiries related to process around documentation required to support payment and general increase related to new initiatives joining in and getting more familiar with the process of raising and approving claims. 

Given the variety of expenses processed and the different nature of operations we support through OCF, this month it became clear how, in some instances, it can be really useful to have more than one host admin to review expenses before getting them paid out. We identified that one collective was engaging in some lobbying activity (which is in breach of OCF terms) where the expense in question was not flagged in time and so we are now looking into determining internal guidelines to approach the process of authorizing payments. 
 
**Onboarding**

Similar to expenses, any new applications notifications received now are going through FreshDesks. This is the reason for the spike in the number of hosting application tickets. 

Onboarding related questions are still some of the common ones we receive, however, there seems to be a little drop in new collectives onboarded with OCF, there is a 35% increase in the number of new groups joining OSC. Here is how it was distributed:

We approved 27 new applications for OCF  compared with 25 in May.

For OSC -  89 new collectives were approved this month compared to 128 in May. 

[Note - now that we can run queries through Metabase with more ease these numbers are more accurate as we can easily picked the applications we approved during the month rather than those created during the month so the May numbers are updated in comparison with the previous month]_

In the OCF space, we are looking into our onboarding process and moving into a place of building more focus[ on what our strategic direction should be](https://docs.google.com/document/d/1xb1WwqJ8cvaqT768s62ccAYMQPP5E-JihCx7BGoZbFw/edit?amp;usp=embed_facebook) as we are expanding our focus on the communities we serve. We expect the next few months to be an exciting phase as new groups join in with a wider focus on impact. 

There is also more work to be done in the OSC space around how we improve the onboarding of new groups and this is a space to watch. 

**Virtual Cards**

Virtual cards pilot continues to be a strong focus this month and the requests keep coming through. We currently have 63 active cards for collectives hosted under OSC and 11 for collectives under OCF. 

One thing noted through support tickets received for requests made for OSC is that very often there is not sufficient information included in the initial request - missing the vendor name and more frequently the monthly limit of the spend. Would be good if these elements would be more visible on the application form to ensure we gather all the information we need without the need to follow up with the collective admin. It seems we already are incorporating restrictions on new collectives making requests even before they were approved for hosting and it would be good to determine clear specifications on the minimum time the collective is active before they can make a request to receive a new card. It seems like we considered a minimum period of 3 months and if this is the decision we make it should be clearer in the application process. 

**Other things worth noting:**

- This month Ember joined as a lead person on the support function and this has been such a welcomed addition! Super exciting to have the support team growing!
- Nathan and @alanna are leading the research work into getting the option of grants integrated for initiatives looking to issuing those. We paused that offering initially and now ensure we tick all the IRS compliance boxes before moving ahead in that space. If we are able to figure this out, it will help us in making the expenses processing a lot easier on a few of our initiatives and we are hoping to integrate the projects feature to monitor the reporting and associated budgets. Watch this space!

**Comment by BenJam** [comment]
closing this out so we only have the most recent report 'open'
