### ISSUE TITLE
Review: Expense payment for acgn-stock Collective

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#444]
Mail from user:

> https://opencollective.com/acgn-stock/expenses

> I submit and approve 3 expense about 9 days ago, but still not receive until today.
> FAQ say it will be paid every Friday.
> Anything wrong?

Is this collective under Open Collective, or maybe it's under another organization?

**Comment by piamancini** [comment]
@nicobarretoOC please email to them that we've been having some issue sending the payment to that paypal account. We believe is not on their end, so we are talking with paypal so see what's the issue.  We are working on solving and hopefully we can reimburse them this week.

**Comment by nicobarretoOC** [comment]
User says it has no other Paypal account :/

**Comment by piamancini** [comment]
@nicobarretoOC we tried to pay again today and we hit the same error. We are taking with Paypal, trying to see what's going on.

**Comment by nicobarretoOC** [comment]
Hey, do you want me to keep this issue open @piamancini ?

**Comment by piamancini** [comment]
yes, it's still unresolved.

**Comment by piamancini** [comment]
fixed and expense reimbursed. @nicobarretoOC user probably knows from seeing his expense paid but just in case shoot them an email.
