### ISSUE TITLE
Figma Integration to Storybook

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4442]
Currently we use Storybook as our style-guide. However I feel that there's a disconnect between the dev workflow and the design workflow such that there's many times were we have to comb through some Figma designs to see if the component fits the design exactly. And it's easy to miss certain things especially when design is changed slightly after the component/feature has already been developed. 😄 

One way to eliminate or reduce this is to have an workflow which integrates our Storybook and Figma designs. This way we always have a go-to place to check if our designs match the current implementation of the component. 😄 

On this regard I would like to suggest adding an add-on on top of Storybook to integrate to Figma. My quick investigation suggests the following two add-ons meet out needs. 

1) [Designs AddOn](https://github.com/pocka/storybook-addon-designs) - This is a simple add-on and it seems to just view the Figma design and the Storybook design side by side so that we could visually see what's going on. This is free and open source. More info can be found here; https://medium.com/storybookjs/storybook-figma-addon-7a399f094a0a 😄 

2) [Contrast](https://www.contrast.app/) - This is not free but seems to give a diff between the Figma design and the Storybook components. Seems to be more advanced in terms of capabilities than the first. More info and rational behind this is explained at, https://www.contrast.app/posts/how-to-connect-storybook-figma-toppling-the-great-divide

I am okay with integrating either one but let me know your thoughts. Just thought I'd mention both in case if anyone has any preferences on this. 😄 

cc: @Betree @opencollective/core-developers @opencollective/design

**Comment by Betree** [comment]
`Designs AddOn` looks great, and matches what we were talking about last time  - simply to have Figma & implementation displayed in the same place.

I don't think our Styleguide/Design system is mature enough to justify the use of `Contrast`. A lot of our components are far from being pixel-perfect.
