### ISSUE TITLE
[DOCS] Improve guidance for adding funds generated through physical events

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#4445]
This issue replaces https://github.com/opencollective/opencollective/issues/4109 as a feature for collectives to add funds to their collection when they raise money outside of the platform. For example with a physical event with tickets paid on the door.

In this case the individual(s) holding the cash need to donate it using their personal profile so that we are able to account for the cash held on behalf of the collective (for AML etc). 

I'm proposing this as docs issue @shannondwray but I think we should consider looking at where the platform needs to be self-documenting, i.e. docs should also include the app :)

**Comment by shannondwray** [comment]
Have included this in the new docs update. So will close this.
