### ISSUE TITLE
Improve Transfer of Budgets from Events to Collective

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4446]
As per the discussion at https://github.com/opencollective/opencollective/issues/4280#issuecomment-878366659 we need to support transferring of budgets from Events to it's associated collective. 😄 

![image](https://user-images.githubusercontent.com/12435965/125377964-bb05d380-e342-11eb-8385-31369de21bdc.png)

Summarizing the technical specs;

- [ ]  Add the front-end transfer funds button to the budget page
- [ ]  Add a mutation (`TransferBudgetMutations.js`) on the api side to transfer the budget from the event to the collective
- [ ] Add front-end logic to call the mutation and transfer the budget

**Comment by SudharakaP** [comment]
@Betree : Let me know if there's anything to add to this or if my technical specs are in agreement. 😄 

@Memo-Es : I couldn't find the figma design for this; is this already in production? 🤔

**Comment by SudharakaP** [comment]
The attached image above is just a mockup as Memo indicated to me and it seems that as per, https://github.com/opencollective/opencollective/issues/4280#issuecomment-878599185 we will probably need to discuss more and sync with design before moving forward on this. I suggest putting this on hold until @Betree comes as he might have some ideas on this as well. 🤔

**Comment by BenJam** [comment]
errr looks like [we didn't reaslise this already happens](https://github.com/opencollective/opencollective/issues/4280#issuecomment-878599185) so in fact all we need to do is notify these folks with a message?

**Comment by SudharakaP** [comment]
@BenJam @alanna : I am closing this issue as it seems that the initial concern that we were trying to address here is already there as per, https://github.com/opencollective/opencollective/issues/4280#issuecomment-878599185. But if anyone thinks there's something to improve let us know and we can reopen or start a new issue. 👍🏽 

cc: @Betree
