### ISSUE TITLE
Flacky E2E Test on Stripe Input

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4447]
I have noticed that from time to time the following test fails on our E2E suite. 🤔 

```
4 passing (1m)
  1 failing

  1) Contribution Flow: Donate
       works with 3D secure:
     AssertionError: Timed out retrying after 15000ms: Expected to find content: 'We are unable to authenticate your payment method.' but never did.
      at Context.eval (http://localhost:3000/__cypress/tests?p=test/cypress/integration/12-contributionFlow.donate.test.js:300:8)
```
This is similar to what we had before at, https://github.com/opencollective/opencollective-frontend/pull/6365. Since this is related to the Stripe frame not loading at a timely manner I would suggest we add a retry as we did before.

**Comment by Betree** [comment]
Adding a retry is a good idea, because of the multiple Stripe iframes this one will often fail because of things that are out of our control - network requests, timeouts, etc.
