### ISSUE TITLE
Payment source shows up twice

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4448]
<img width="618" alt="Screen Shot 2021-07-13 at 1 22 38 PM" src="https://user-images.githubusercontent.com/5498878/125375717-a88ca800-e3dd-11eb-87fa-90e608c2f853.png">

When setting up a contribution to a Collective under the OC host (Documentation), the OC host org profile shows up twice.

**Comment by Betree** [comment]
It looks like OC Inc has 2 `collective` payment methods. We should understand why the second one was created and merge them

```sql
SELECT * FROM "PaymentMethods" pm
WHERE "CollectiveId" = 8686
AND service = 'opencollective'
AND "type" = 'collective'
```

**Comment by znarf** [comment]
Seems this was fixed for this case. Maybe this was tracked and fixed this in a separate issue.

**Comment by znarf** [comment]
Duplicate with https://github.com/opencollective/opencollective/issues/4964
