### ISSUE TITLE
[PROJECT]

### ISSUE THREAD

**Issue by Andyyguevara225** [opencollective/opencollective#4450]
## Overview
(What is this project and why have we prioritised it?)

## Owner
(Name of core team member responsible for the project)

*Note: Project owner responsibilities include coordinating all the different people that need to contribute to the project, defining specs and goals, communicating project progress, being the point person for decisions, QA, documentation, and a plan for ongoing maintenance. If the project owner can't continue, they need to hand the role over to another person explicitly.*

**Secondary Developer on project:** 

## Prioritization

- Does this serve our mission

- Will this help to make us financially sustainable within a year?

- Can this make us move faster?

- Does this increase quality? 

- Does this add technical debt?

- Is it feasible to build and maintain with our current team and runway?

- What insight or research is this project based on?
- Is this problem already solved elsewhere?

- How will we measure our success? Do we have a baseline today that we can compare this against?

- How well do we understand the complexity of the problem, feature to be added or user need to be addressed? 

- What is the estimated timeframe for delivering this project? 

### Roadmap & Timeframe
(Key milestones or phases and estimated dates. Consider including further scoping, discovery, and prototyping. Include as a minimum: planning, design, development, documentation, feedback, iteration and, marketing)

### Success metrics
(What we will judge outcomes of the project by)

### Release planning

**Estimated delivery date**

- Which aspect(s) of the platform does this change impact?
- Which group(s) of users will benefit from this change?
- Is this project in response to a user-requested feature? If so who requested it (link to feature request if available)?
- Is this project related to any similar work we have done, or are planning on doing in the next three months?

### Next steps

- [ ] Open up any appropriate project issues
- [ ] Open a documentation issue, link it to this one
- [ ] Open a release issue, link it to this one
- [ ] Create a project board, add this issue to the description, add any issues created above 

## Project Closure

- Close all relevant project issues
- Open up issues for improvements 
- Post comm's according to comm's plan (most likely in release issue)
- Post project screencast on documentation slack channel 
- Post project closure in newsletter slack channel 
- Celebrate!! 
#4382

**Comment by Andyyguevara225** [comment]
**
![imgur_com](https://user-images.githubusercontent.com/86837906/125403500-33888680-e37b-11eb-8e08-e912ce9dd8c0.jpeg)
**

**Comment by SudharakaP** [comment]
This ticket is closed due to **guidelines not followed**. 

All tickets should follow the guidelines as mentioned in: 

- The [Code of Conduct](https://github.com/opencollective/opencollective/blob/main/CODE_OF_CONDUCT.md).

- Submission guidelines as mentioned in our [README file](https://github.com/opencollective/opencollective/blob/main/README.md#issues).
