### ISSUE TITLE
Convert API from CommonJS to ESM

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4451]
More and more projects seems to start using [ESM](https://nodejs.org/api/esm.html#) instead of [CommonJS](http://www.commonjs.org/) and I think eventually we will have to do this migration. For example certain dependencies such as, https://github.com/opencollective/opencollective-api/pull/5825 and https://github.com/opencollective/opencollective-api/pull/5835 are currently blocked due to new versions of those only supporting ESM. 😄 

Therefore I suggest migrating our api side to [ESM](https://nodejs.org/api/esm.html#). Some helpful tips to migrate a larger codebase to ESM is given here; https://ar.al/2021/01/27/commonjs-to-esm-in-node.js/. Also there's some tips at, https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c. 

I am willing to give this a try if there's no objections. 😄 

cc: @opencollective/core

**Comment by znarf** [comment]
It seems it's a complex project and should be tackled trough our normal prioritization process. Feel free to do some research on an experimental branch and share with the rest of the team how it could looks like.

**Comment by SudharakaP** [comment]
@znarf : Exactly, let me do some thinking on this in the coming days and get back. It's indeed complex, and I am also not sure if it's worth the hassle, I tried several attempts to update the above two dependencies with different approaches but failed so that's what I thought maybe it's time we need to think about upgrading to esm. 😢 😄

**Comment by SudharakaP** [comment]
I did some investigation on this in the https://github.com/opencollective/opencollective-api/tree/feat/migrate-to-esm branch. 

There's some serious problems that blocks this migration at this point I think; 

- ESM modules [aren't supported by Sequelize I think](https://github.com/sequelize/sequelize/issues?q=is%3Aissue+is%3Aopen+esm); or the support has some issues; such as; https://github.com/sequelize/sequelize/issues/11777

- I didn't find a proper way of doing the `if (require.main === module) {` and `!module.parent` kinda checks (more on this at the comment https://github.com/nodejs/modules/issues/274#issuecomment-517493328). Some discussion about this can be found at; https://github.com/nodejs/modules/issues/274. There's some workarounds such as using, https://github.com/nodejs/modules/issues/274#issuecomment-588528200. But they are workarounds and I don't think we should go with that for now.

Due to these points above and since there is no such need to migrate the codebase to ESM immediately I am planning to close this issue for now. Maybe in the future when things on the above issues are solved we can revisit this again. If you have any opinions or other alternative suggestions on this feel free to let me know. 😄

**Comment by negotiamini** [comment]
It's been one hell of a battle, will require a lot of work. I've been working on it for some time now. @Nest has the best framework for it. Unfortunately, too many packages still haven't ported over, coupled with all the components and it's going to require some heavy lifting. 

Best approach would be modularity in stages, that said even Sequelize proved to be a challenge in migrating. Caveat, I'm not an advanced coder, so learning curve has hindered progress.
