### ISSUE TITLE
Don't display org creation option in apply flow

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4459]
I just supported a user who went down the wrong path and got stuck and I think we should close that specific path.

We often send people directly to opencollective.com/opensource/apply if they are trying to create a new Collective, or they end the flow by clicking the 'apply' button on the Host page. 

If they are a completely new user, they first are asked to create their account, which is fine, but it goes like this:

1. Go to opencollective.com/opensource/apply
2. Get directed to create an account
3. See options for individual or organization registration
4. Think "I'm here representing my group trying to create a Collective, so I'll click organization"
5. Register, creating both their individual profile and their org profile
6. Get magic link login from email and click through back to OC
7. Continue Collective creation flow
8. End up with *both* an Org and a Collective for the project
9. Be confused

OR
6. Get magic link and do not bother to go to email and get logged in
7. End up with an Org profile only and fail to create a Collective or apply to the Host as intended (what happened in this case)
8. Be confused

I think if someone is entering the flow via applying to a Host, we should only show them the individual user registration option, because registering an Org at this point is not the correct step.

**Comment by znarf** [comment]
Alternative, people should be able to "Create a Collective + Apply" and "Sign Up" in the same form. I think that would be the best experience.

**Comment by Memo-Es** [comment]
We updated the collective creation last sprint following the discussion described here #4256 

I agree with @znarf and did the corresponding adequations to the [Figma file](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC-Design-Production-Ready-%E2%9C%85?node-id=8637%3A0) that @Betree and I used to implement https://github.com/opencollective/opencollective-frontend/pull/5555

![Form 1](https://user-images.githubusercontent.com/49539954/129109520-74426eb1-d3a9-4a63-b57e-83f91d12b7d1.png)

**Comment by Betree** [comment]
I've opened a quick fix in https://github.com/opencollective/opencollective-frontend/pull/7129 that hides the `Create Organization Profile` tab in the create collective flow (`/create`) and apply flow (`/:host/create`). If that works for everyone, I'll merge it and will create a separate issue for https://github.com/opencollective/opencollective/issues/4459#issuecomment-897191848: `Combined sign up + apply form`.

**Comment by Memo-Es** [comment]
That works for me @Betree we can follow up later for a long term solution
