### ISSUE TITLE
To fork or not to fork: Banned content by your payment processors but adding Code bouty/freelancing services

### ISSUE THREAD

**Issue by DrAlta** [opencollective/opencollective#4462]
I wanted to use Open collective for my Relationship and Sexuality Education edutainment game but Stripe said they was one of their restricted business and they wouldn't allow their services to be used by it.

I haven't found any good alternative. Librepay on open but they don't allow you to recognize your Patrons so there really dampens the ability to Patreon like tiers.  I wanted to do a code bounty/freelancing site but that was a more long-term goal.  I think I could code up a Patreon/Code Bounty/Freelancing site I just need some too.  I just need someone to review it and make sure it meets FinTech standards and then actually deploy it.  

Would Open Collective be interested in working with me on this project? or should I just fork the Open Collective code base and go off on my own way?

**Comment by znarf** [comment]
It's generally not a good idea to fork our codebase, it's too complicated and overkill to operate.

Feel free to contact support@opencollective.com with your inquiry.
