### ISSUE TITLE
Odd card appearing in search result

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4463]
<img width="1131" alt="Screen Shot 2021-07-17 at 9 16 58 PM" src="https://user-images.githubusercontent.com/5498878/126032398-08cc6e36-cac0-49f7-8e12-707994a85923.png">

If you click the third one it sends you to https://opencollective.com/website and throws an error.

<img width="767" alt="Screen Shot 2021-07-17 at 9 17 45 PM" src="https://user-images.githubusercontent.com/5498878/126032416-5722b4f2-4537-42e8-85cd-a9800df1fe35.png">

**Comment by Betree** [comment]
Looks like our Cloudflare config redirects everything ending with `/website` to the images service: https://github.com/opencollective/opencollective-workers/blob/91b49a5c1c42022f1bcc2dab2f16e2a6ecc18b72/main.js#L105

I'd be in favor of fixing this by:
1. Renaming this collective (eg. to `/website1`)
2. Add `website` to the reserved slugs: https://github.com/opencollective/opencollective-api/blob/8864ca16427fa06d7729b01494d71226771e81eb/server/lib/collectivelib.ts#L157
