### ISSUE TITLE
Add tooltip to 'total disbursed'

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4464]
This is from the budget section of /foundation:

![Screen Shot 2021-07-19 at 9 36 21 AM](https://user-images.githubusercontent.com/5498878/126082825-c4318e86-361e-4eab-9b68-7bb7251a8311.png)

`Total disbursed` is the only one without a tooltip. OCF has disbursed way more than $17k, so I need a tooltip here to explain what I am looking at. Is this stat for the last month or something?

The `Total raised` stat also doesn't make sense, as OCF has brought in a lot more than $130k in host fees.

**Comment by alanna** [comment]
Can someone help me understand what these numbers mean? I can't tell if it's a bug or I just don't get it. @Betree @znarf

**Comment by Betree** [comment]
> Total disbursed is the only one without a tooltip. OCF has disbursed way more than $17k, so I need a tooltip here to explain what I am looking at. Is this stat for the last month or something?

This number is for the entire life of the account, there's no date filtering here. If's defined as `totalRaised - balance`, so for example: if I got $1000 in financial contributions, and my balance today is $700, we'll assume that I disbursed $300.

`totalRaised` itself is calculated by looking at all the credit transactions for this collective. These metrics probably need to be reviewed for hosts, as they're probably missing the host fees collected before the ledger refactor.

**Comment by znarf** [comment]
> as they're probably missing the host fees collected before the ledger refactor.

Hosts used to do Add Funds on a monthly basis to add those Host Fees.

But there are so many other accounting things that could have gone wrong with this account in the past, we need to look closely at it to explain (and fix) the numbers.

Seems we're about to go off track as this ticket is about "Add tooltip to 'total disbursed" and not about Foundation accounting internals. Can we move this discussion elsewhere? Slack might be more convenient.

**Comment by alanna** [comment]
<img width="389" alt="Screen Shot 2021-08-24 at 11 16 40 AM" src="https://user-images.githubusercontent.com/5498878/130531353-66d2545b-bea8-4e8e-8534-514e9ffb04c2.png">

It appears this is fixed. Now that the number matches the total disbursed, we don't need a tooltip explaining.

**Comment by znarf** [comment]
Weird that the total raised was off like this and back to normal now, I haven't touched anything personally.
