### ISSUE TITLE
Recovery code not allowing to change 2FA device

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4466]
When losing access to your 2FA device, users can properly access their account using the recovery codes.

Unfortunately, it's not possible for them to reset the 2FA itself because it's still requiring a 2FA code to proceed.

Maybe when using recovery codes, we should disable 2FA authentication in the process.

**Comment by SudharakaP** [comment]
@znarf : I think we probably need to also state that it's disabled in the docs as well as in the recovery dialog; 

![image](https://user-images.githubusercontent.com/12435965/126382031-7ebf8fb3-b55c-43e5-a328-c92464f6f4b6.png)

Something like; `On successful authentication 2FA will be disabled`

If this is in agreement I'll add this one. 😄

**Comment by kewitz** [comment]
### Spec
- [ ] Rename the button action to "Redefine 2FA"
- [ ] Update `twoFactorAuthAndUpdateToken (server/controllers/users.js#L102)`
  - [ ] When successfully using the recovery, delete `twoFactorAuthToken` and `twoFactorAuthRecoveryCodes`
- [ ] Update `frontend/lib/withLoggedInUser.js#L104`
  - [ ] When successfully calling `refreshTokenWithTwoFactorRecoveryCode`, redirect the user to `/{slug}/edit/two-factor-auth`

**Comment by snitin315** [comment]
Taking this up.

**Comment by kewitz** [comment]
:trophy: This issue was completed by @snitin315 

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
