### ISSUE TITLE
Delete or Merge user accounts for Mike

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#447]
Mail from Mike:

> I just started backing a project via Open Collective, which has created an opencollective user for me. However it seems I already had a user, which means I now have two accounts. But I'm not sure how to access the original account. Is there a way for me to merge these two users into one?
> 
> The existing user is: https://opencollective.com/m-allanson
> The newly created one is: https://opencollective.com/mallanson
> 
> I'd like to just keep the m-allanson user (with the hyphen), as this matches my GitHub account name.

Reply from Nico:

> Hey Mike, thanks for contacting us about this issue. 
> 
> We have a no-password system so you can try to login to your other account with your email.
> 
> Do you have any subscriptions active on the account you want to delete? 
> If you do, it would be best to login and cancel those subscriptions here:
> www.opencollective.com/subscriptions
> 
> I'll wait for your reply, and in parallel I'll create a ticket for your request. (...)

**Comment by piamancini** [comment]
done
