### ISSUE TITLE
Events missing from Host settings

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4470]
OCF wants to host events. But Events is not an option for the profile page apparently? How do we turn Events on?

![Screen Shot 2021-07-20 at 4 57 30 PM](https://user-images.githubusercontent.com/5498878/126265065-343095c3-69d5-40d1-a5b5-731887868271.png)

**Comment by SudharakaP** [comment]
I've investigated the issue and it seems that we are missing a field in our code when we retrieve the GQLV2 fields here; 

https://github.com/opencollective/opencollective-frontend/blob/57f80ac3ebea94bd4e9282e5c0aca63ab6131a98/components/edit-collective/sections/EditCollectivePage.js#L37. 

The PR above suggests a simple fix that corrects this issue. :smile:

**Comment by SudharakaP** [comment]
And thanks much @alanna for reporting the issue. 😸

**Comment by alanna** [comment]
Thank you! Is there any way this could be fixed ASAP @SudharakaP @znarf ? Not being able to create an event is blocking OCF from publishing a post we've been working on for a while.

**Comment by SudharakaP** [comment]
> Thank you! Is there any way this could be fixed ASAP @SudharakaP @znarf ? Not being able to create an event is blocking OCF from publishing a post we've been working on for a while.

@alanna : We need to deploy the fix to production. When @znarf reviews this tomorrow, I'll be sure to push it to prod ASAP. Will let you know once done. 😄
