### ISSUE TITLE
Stop Abbreviating Numbers in Contribution Flow

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4471]
As per the discussion https://github.com/opencollective/opencollective-frontend/pull/6632#issuecomment-883402851, it was suggested that we should stop abbreviating numbers in the contribution flow. Currently the contribution flow looks like this,

![image](https://user-images.githubusercontent.com/12435965/126344547-f10b6a5e-b02d-4ecd-a277-74e82eb1ab6a.png)

Abbreviating number I think has a purpose in the context of currencies such as YEN where the monetary amounts are normally large values (ex: 10000, 20000 so on). But for other currencies doing this might not be worthwhile and thus my suggestion is that we should only abbreviate for these currencies not all. 🤔 

Let me know your thoughts. 

@opencollective/core

**Comment by znarf** [comment]
I think it's fine whatever the currency. We can try it and iterate if it's a problem.

Note that it's still important to format properly the strings for readability, `5,000,000` and not `5000000`.

**Comment by Betree** [comment]
It would be interesting to have some feedback from @opencollective/design (who initially proposed this) and native English speakers (@alanna) on this one.

**Comment by alanna** [comment]
`$1.234k` and $4.321k` are not abbreviations that are used in English and I think they look weird. Even more, it doesn't actually abbreviate it because it's the same number of characters as `$1,234` and `$4,321`. Abbreviations with K are usually approximations or at least perfectly round numbers. Abbreviations with decimals really only start with m for million as in `$4.2m`.

**Comment by BenJam** [comment]
++ if the amount is over 10k then I might expect abbreviations in the USD, GBP or EU for round numbers 10k 10.2k and at a stretch 10.23k but three decimals on abbreviations is weird.

**Comment by znarf** [comment]
Abbreviation with decimals seems a clear no go.

I personally think it's a bit complex to abbreviate in some cases and in some not, this is why I initially proposed to stop abbreviating altogether. Remember that we're talking about the presets of the contribution flow, so it's really uncommon to have really big numbers here.

**Comment by SudharakaP** [comment]
Just to note, the number of valid collectives which has tiers which include amounts greater than, 100,000 is around 1 or 2 according to my rough calculations (and those don't seem to have any contributions for those tiers). So my thinking is abbreviations for amounts larger than this amount isn't probably useful. 🤔

**Comment by SudharakaP** [comment]
I think this discussion is stale unless there's any alternative proposals which you strongly think we should reiterate on. Thus I am closing this issue for now. But please feel free to let me know otherwise. 😄 🤔
