### ISSUE TITLE
Small bug with time selector on event creation page

### ISSUE THREAD

**Issue by RCheesley** [opencollective/opencollective#4474]
**Describe the bug**
There seems to be a bug with the time selector when creating events.

I was trying to select 6pm but it would not allow me to do so:

https://youtu.be/G5JxHLTlatc

**To Reproduce**
1. Create an event
2. Try to set a time for the start or end
3. Note that it is hard to set a specific time - the numbers are jumping up and down and text input of 6 set itself to 7 when I tried to manually set without the time picker.

**Expected behavior**
Should be able to select a time using the picker or manually without any issue.

**Screenshots**
https://youtu.be/G5JxHLTlatc

**Desktop (please complete the following information):**
 - Device: Macbook Pro
 - OS: Catalina
 - Browser Chrome 91.0.4472.114 (Official Build) (x86_64)

**Comment by Betree** [comment]
@RCheesley Thanks for the great documentation on this issue and including a video.

It seems similar to what was reported in https://github.com/opencollective/opencollective-frontend/pull/5108#issuecomment-720475812, so this might not have been solved entirely.

**Comment by RCheesley** [comment]
Ah yes - did not find that in issues! Seems like the same issue!

**Comment by Betree** [comment]
> Ah yes - did not find that in issues! Seems like the same issue!

It was only some feedback in the code review, it's great that you created a dedicated issue for this :+1:

**Comment by SudharakaP** [comment]
Interesting. I tried both Firefox and Chrome and couldn't recreate this. 🤔 

@RCheesley : Can you try updating chrome to latest version by any chance? I am using **92.0.4515.107**. 🙂

**Comment by Betree** [comment]
@SudharakaP It's possible that only MacOS is affected, we should try reproducing with this OS.

**Comment by SudharakaP** [comment]
> @SudharakaP It's possible that only MacOS is affected, we should try reproducing with this OS.

Unfortunately I don't have a Mac. However I tested on Browser-stack (with Catalina OS and Chrome as the bug describes) and still couldn't recreate it. 🤔 

![time-picker](https://user-images.githubusercontent.com/12435965/127163827-25eaf21a-bd7c-4b80-9e31-43e0d7371ab2.gif)

Maybe we need to test it on a real device. 🤔

**Comment by SudharakaP** [comment]
This one should no longer be a problem as we have moved the date-time fields in the settings page to a `datetime-local` as per https://github.com/opencollective/opencollective/issues/4865. And it seems that latest version of Safari supports it; https://caniuse.com/?search=datetime-local. 

@RCheesley : Let us know if you see any further issues. 🙂
