### ISSUE TITLE
Add 'create event' button to empty events page

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4479]
If there are no events, this is what you see:

![Screen Shot 2021-07-22 at 9 01 33 AM](https://user-images.githubusercontent.com/5498878/126559656-c5c0a1b3-72ef-4e08-9b4f-73222be2525d.png)

If you are an admin, there should be a `Create Event` button here.

**Comment by SudharakaP** [comment]
For this I suggest adding a button similar to what we have on the Updates screen; 

![image](https://user-images.githubusercontent.com/12435965/126563099-d366cba5-0e35-4851-956f-462b64bbb21d.png)

I've done a [PR above](https://github.com/opencollective/opencollective-frontend/pull/6666). Let me know if it looks good. 😄
