### ISSUE TITLE
Review Invoice from Ivan from "react-native-image-crop-picker" Collective

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#448]
Email from Ivan:

> Hi Pia,
> 
> Here is the invoice. The amount is now 280$. I used template from this linke https://docs.google.com/document/d/1ROQA11PaYjGtcie-1Ut8cFV5LCISKipSu8sgsY5U7vw/edit?usp=sharing. 
> 
> Does invoice look good to you? If yes, should I create new expense and attach sent invoice?
> 
> Thanks,
> Ivan

**Comment by nicobarretoOC** [comment]
Looks good to me (check attachment on email), let me know @piamancini. 
If you approve then next invoices that keep that format I can help you reviewing them.

**Comment by piamancini** [comment]
good call.

**Comment by nicobarretoOC** [comment]
Ok, he just sent a corrected invoice with his address.

**Comment by piamancini** [comment]
invoice updated. we'll get it paid on friday
