### ISSUE TITLE
Change 'Contribute' section header for Events to 'Tickets' when custom contribution is off, and make it off by default

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4480]
Auggestion: 
> I would be reluctant about removing Contribute from the navbar as it's against the patterns we've set up. We can eventually rename Contribute to Tickets if there are no custom contributions for the event and remove this tooltip in this case.

If you're hosting an event (especially a free one) and you turn off custom contributions, it's really weird to have a contribute banner dominate the space above the ticket registration action card. And it has some misleading hover text about giving money when that's not this page's function at all. 

![Screen Shot 2021-07-22 at 9 23 51 AM](https://user-images.githubusercontent.com/5498878/126562521-f56025df-dd4f-4566-b244-bb7839c1d664.png)

We have also got feedback from many users that not having tickets at the top really confuses users whose main objective on this page is getting an event ticket. This is made worse by the fact that custom contributions is on by default and many users don't know they can turn it off. So they get a lot of people making a donation instead of actually registering for a ticket. I think custom contributions should be off by default on Events.

**Comment by Betree** [comment]
Not sure if that's part of the proposal, but I would be reluctant about removing `Contribute` from the navbar as it's against the patterns we've set up. We can eventually rename `Contribute` to `Tickets` if there are no custom contributions for the event and remove this tooltip in this case.

**Comment by alanna** [comment]
That alternative sounds good. The main point is to remove confusion when the current Contribute setup doesn't match the function of the page.

**Comment by alanna** [comment]
@znarf with the simplified ask contained in the title, could this be a bounty?

**Comment by alanna** [comment]
It was marked medium complexity but I don't think the new idea is complex

**Comment by znarf** [comment]
@alanna It's still a bit touchy and I don't have the bandwidth to manage this issue myself, even through a bounty. Maybe for @SudharakaP as he's working on a few Events improvements or @Betree when he's coming back.

**Comment by SudharakaP** [comment]
Yes, I can take this on when I finish off the current event issues I am working on 👍🏽

**Comment by SudharakaP** [comment]
Will be working on this one soon as per Ben's suggestion above; https://github.com/opencollective/opencollective/issues/4480#issuecomment-884693946

**Comment by Betree** [comment]
A simpler proposal: **rename the `Contribute` category to `Participate` for events.**

The page would then have the following structure:
- Participate
  - Tickets
  - Financial contributions _(if enabled)_

I'm proposing that because the condition implemented in https://github.com/opencollective/opencollective-frontend/pull/6751 to know whether we should display `Tickets` or `Contribute` appears quite complex, difficult to predict, and is not future-proof: if, for example, we later want to show "Connected collectives" for events they would appear under "Tickets".

Of course, we should still update the tooltip and the `Become a financial contributor` subtitle. But to me, the condition to do that should only be whether we are viewing an event or not, having custom contributions enabled shouldn't impact the wording.

**Comment by SudharakaP** [comment]
@alanna : Let us know if you agree with Ben's proposal above. If so, I'll change the implementation to match that. 😄

**Comment by kaylarep** [comment]
Would 'Support' work? or 'Get involved'?

The common language for people looking to donate (in the US) would not be 'Participate' (imo, I would assume that's where I'd go if I wanted to volunteer) and I think we need to give financial donors a really clear, unconfusing pathway to donate.

**Comment by alanna** [comment]
I would support either 1) get involved, or 2) no header at all. If the header is causing so many issues, can we just remove it?
