### ISSUE TITLE
Update editor jumping around while typing

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4481]
Video: https://i.gyazo.com/3aa245ffe0c898d9e0df7208417d8a97.mp4

**Comment by Betree** [comment]
It seems related to the scrollbar appearing and disappearing. Either we make the container grow automatically (so no scrollbar will be needed) or we make sure the scrollbar is displayed at all times, even when not needed (CSS `overflow-y: scroll`).

**Comment by SudharakaP** [comment]
@Betree : Did you manage to recreate it? I couldn't re-create this scenario on Firefox or Chrome. 

@alanna : What browser/version were you using? 🤔

**Comment by alanna** [comment]
Chrome on Mac.

Try it with a big image like I had in this example maybe? I think I noticed
it only started once the image was there.

**Comment by SudharakaP** [comment]
@alanna : Tried some larger images as well, but couldn't see this issue; could you send the image you used. Maybe it has a particular size that triggers this. 🤔

**Comment by alanna** [comment]
![Gift Collective Logo (Main Logo) 1 - Dark_Green](https://user-images.githubusercontent.com/5498878/127237248-f93f5682-5cf0-4e17-aef1-1b9f79c85350.png)

**Comment by SudharakaP** [comment]
@Betree : Although I couldn't reproduce this issue (even with Alanna's image above), I think your suggested solution of adding `overflow: scroll` should solve it; since it will always keep the scrollbar and only disable it when there's no overflow. I've made a PR with that fix, and if you are okay we could give this a try. 😃

**Comment by Betree** [comment]
Just a note to say that the result doesn't look very nice on the comment form. Would be great to find an alternative solution if there's something easy we can do.

![image](https://user-images.githubusercontent.com/1556356/135845916-4b484e4d-868b-4f70-901a-8bb782d8ec3b.png)
