### ISSUE TITLE
Add Special Flow to Contribution Tier for Crypto

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4484]
Depends on https://github.com/opencollective/opencollective/issues/4456.

We need to add some special contribution flow sections for crypto contributions. When the user click on the Crypto tier (as explained in the above referenced issue) then the user should be taken to the crypto flow. The design is given below. 

https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=13104%3A204710

- [x] Add the [Crypto Currency Selection section](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=13426%3A207927).

- ~~[ ] Add the [User Details section](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=13426%3A207917).~~

![Amount Selection](https://user-images.githubusercontent.com/12435965/126709316-36dcb6d1-b197-4572-9e87-74b375e71c4c.png)

![User Details](https://user-images.githubusercontent.com/12435965/126709319-d6834f24-5ce9-4dec-b37a-6f11b814974b.png)

**Comment by Betree** [comment]
>  Add the User Details section.

This section already exists, it's currently only visible for contributions > $5000.

**Comment by znarf** [comment]
Regarding the User Details section, if we don't have extra requirement ourselves, we can just use what exists. And eventually trigger the same  behavior that is currently for contributions > $5000.

In case we wanted to add some fields to accommodate The Giving Block API case, we don't have do it anymore.
