### ISSUE TITLE
Use The Giving Block To Generate the Wallet Address

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4485]
Depends on https://github.com/opencollective/opencollective/issues/4484
 
We need to add connect to [The Giving Block](https://app.gitbook.com/@the-giving-block/s/public-api-documentation/endpoints-documentation) to generate the wallet address and display it on the third step of the contribution tier for crypto contributions. 

Figma Design: https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=13426%3A207907

- [x] Use the Giving Block api to generate a new deposit address; https://app.gitbook.com/@the-giving-block/s/public-api-documentation/endpoints-documentation

- [x] Display this as a QR code int the contribution flow as per the following design.

![Payment Info](https://user-images.githubusercontent.com/12435965/126709766-2c71a3a3-c64a-40b8-89bb-20a2ac257a5e.png)

**Comment by znarf** [comment]
For an MVP, we may create wallet addresses manually and simply add them in the configuration.

**Comment by SudharakaP** [comment]
This was done in https://github.com/opencollective/opencollective-frontend/pull/6725 and mostly a duplicate of https://github.com/opencollective/opencollective/issues/4516 and thus I am closing it.
