### ISSUE TITLE
Improve Design in Empty Balance Button

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4488]
As discussed in our weekly demo the current button for emptying the project/even balance shows 0.00 after the project balance is emptied. We probably needs some design iteration/review for this. 

So currently for projects/events what we have is, 

![image](https://user-images.githubusercontent.com/12435965/126795654-d22c390a-b262-4301-accb-f63bdb3dec8b.png)

@opencollective/design

**Comment by Utkarshn10** [comment]
@SudharakaP For this we can use same format as used in "Start a new conversation" button.

![](https://user-images.githubusercontent.com/5498878/128580706-e9ffb312-86e9-477a-ad5e-889d480ca7c4.png)

**Comment by SudharakaP** [comment]
For this one I am thinking why not hide the section of emptying the event balance completely if the balance is 0 (i.e; it's already emptied) as there's nothing to empty anymore? 

cc: @opencollective/design @Betree

**Comment by Betree** [comment]
> For this one I am thinking why not hide the section of emptying the event balance completely if the balance is 0 (i.e; it's already emptied) as there's nothing to empty anymore?

I'm not a fan of hiding, people end up contacting us asking "Why can't I see X? The docs say it should be there". My preference goes for disabling + having a clear message. 

> As discussed in our weekly demo the current button for emptying the project/even balance shows 0.00 after the project balance is emptied. We probably needs some design iteration/review for this.

Can we clearly describe why we think this is a problem? I'm open to other perspectives but in my opinion this view is pretty clear.

**Comment by SudharakaP** [comment]
> Can we clearly describe why we think this is a problem? I'm open to other perspectives but in my opinion this view is pretty clear.

I also think the current button itself is clear enough. Since it's been a while I don't quite remember why we thought this was a problem in the first place. Thus I am closing this issue, but if others feel this design needs to change please feel free to re-open. My thinking is at least for now no-one has raised this issue and thus maybe we are overthinking? 🤔 

@opencollective/design
