### ISSUE TITLE
Create a new Transaction Kind for Internal Transfers

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4489]
For internal transfers,

- Moving funds from collective to its respective host
- Moving funds from project/event to its parent collective

we need to track these in the ledger using a separate transaction kind. I suggest the transaction kind name to be, `INTERNAL_TRANSFER`. 

We need to,

- [ ] ~~Create migration to search for all transfers form collective to host or project/event to its parent collective and add this new `INTERNAL_TRANSFER` kind to those.~~
- [x] Add support to pass the transaction kind; in `OrderMutations.js`, `createOrder` mutation and use this if it's passed in the created transaction.
- [x] Pass the transaction kind as `INTERNAL_TRANSFER` for places where we move funds from collective to host, or project/event to it's parent collective in front-end.

**Comment by Betree** [comment]
I don't know if we need to expose that in the frontend now, for the current use case it can be guessed by looking at `FromCollective`/`Collective`. But that might be useful for later. @znarf wdyt?

**Comment by znarf** [comment]
To be clear, we need also to make sure the transaction is not treated as a Contribution, the Parent or Host should for example not appear as a "BACKER". And, I think this is already addressed, no "Thank you" email should be sent.

**Comment by SudharakaP** [comment]
Will be working on this one if no objections. 😃

**Comment by znarf** [comment]
I would like:
- this issue to be strictly about the situation where we use the "Empty Balance" button and not extend it to other situations
- to find something else than `INTERNAL_TRANSFER` as a `kind` as I find this one too generic. Proposals: `MOVE_BALANCE`, `EMPTY_BALANCE`, `TRANSFER_BALANCE` or `**BALANCE_TRANSFER**`.

**Comment by SudharakaP** [comment]
So I've opened PRs to support the addition of the new type `BALANCE_TRANSFER` only for the case where we zero the balance of an existing Project/Event. On the front end side I've passed the flag `isBalanceTransfer` within the `customData` field of the order in order to differentiate between a balance transfer and a regular transfer. Anyways, let me know if you have any comments. 😄

**Comment by SudharakaP** [comment]
Keeping this open until we resolve the comment at; https://github.com/opencollective/opencollective-api/pull/6460#pullrequestreview-735913488

**Comment by SudharakaP** [comment]
Closing this as this is done; but if someone has an idea on any further on my comment on https://github.com/opencollective/opencollective-api/pull/6460#issuecomment-903978216 please feel free to reopen a new issue.
