### ISSUE TITLE
Minify JS files

### ISSUE THREAD

**Issue by discoveranirban** [opencollective/opencollective#4490]
Is there anyway the scripts that are being fetched while rendering a page in the website can be minified ? That'd reduce the payload size a bit.

**Comment by SudharakaP** [comment]
@discoveranirban : Hi, the front-end is based on [NextJS](https://nextjs.org/) and NextJS uses [Webpack](https://webpack.js.org) and [Webpack minifies in production mode](https://webpack.js.org). 😃

**Comment by discoveranirban** [comment]
yes, but the scripts which are in the public folder of nextJS project, those aren't getting minified. Is there a way to do that ? Rest are getting minified.

**Comment by SudharakaP** [comment]
> yes, but the scripts which are in the public folder of nextJS project, those aren't getting minified. Is there a way to do that ? Rest are getting minified.

Not sure if I understand correctly. Can you give me an example of a file that isn't getting minified?
