### ISSUE TITLE
Reveal total payout sum per payee to host admin

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4491]
At OCF we have some regulatory/policy thresholds related to the total a given expense submitter has been paid in the current calendar year. It would be very helpful to reveal this figure in the app for the host admin to refer to while paying expenses. I'm thinking of a way which I hope will be easy to implement.

On the expense page, and when viewing the expense on the list on the Host dashboard or Collective's expenses list, add a hover tooltip to the payee's name, which says:

> Total expense payouts this calendar year ($YYYY):
> Invoices: $x; Receipts $y; Grants $z

![Screen Shot 2021-07-24 at 10 57 43 AM](https://user-images.githubusercontent.com/5498878/126849570-25b558de-926d-47b5-b424-cc0642ad77e2.jpg)

**Comment by alanna** [comment]
@alinamanko let us know if this solution would fill the need

**Comment by SudharakaP** [comment]
I would suggest adding a info icon next to the name just like we have for, 

![image](https://user-images.githubusercontent.com/12435965/126859955-583b6ea6-1825-4570-abd1-dbfa58b0f3b0.png)

And when the user hover over the info icon we show the text as @alanna suggested. Without some kinda indication like the info icon I think users will have no way of knowing that they could see this information by hovering over the name. 🤔

**Comment by alinamanko** [comment]
@alanna I think this can be a good solution. Ideally it would be great to have this visibility from the host dashboard directly without the need to open each expense form, but I recognize this may not be the option as the full name of the user is only visible once you hover over their avatar. I would also like to keep this option, ideally, as something visible to the host admin and maybe collective admin and not necessarily make it into a public display.

**Comment by Betree** [comment]
Related: https://github.com/opencollective/opencollective/issues/3258

**Comment by SudharakaP** [comment]
@Betree : Do you think we should add the [proposal above](https://github.com/opencollective/opencollective/issues/4491#issuecomment-886008741) as a quick fix or maybe wait for design for #3258 ? 🤔

**Comment by Betree** [comment]
> @Betree : Do you think we should add the [proposal above](https://github.com/opencollective/opencollective/issues/4491#issuecomment-886008741) as a quick fix or maybe wait for design for #3258 ? 🤔 

I like this proposal, I think it's simple enough to iterate without waiting for design. We should still demo it to them, to get their feedback in case they see something blocking

**Comment by juliekitty** [comment]
2. Display expense total (calendar year)
- "current year" like in the mockup would probably mean the value is zero in January for the payees, so not really reflects wether the payee has some recent activity
- "last 12 months" reflects better the last expenses activity of the payee and is already used for another display in the app (in the budget part) so i would go for it.
