### ISSUE TITLE
Automatically track local tax in a Project

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4494]
I've been learning a lot going through my first round of paying GST for the OCNZ host, and I have an idea to make this much easier by using our existing features.

When any transaction happens in that Host with local tax involved, a Project could be automatically created under the Host called "Local Tax". When a transaction happens with local tax, the tax portion gets credited to this Project. Then when it's time for the Host to pay tax, they can submit an expense to this Project and mark it as paid.

This would require changing how we deal with tax in the ledger. Right now it doesn't get credited anywhere. I think this is not the best approach because it doesn't help transparency, it causes amounts on OC to be out of sync with amounts in the Host's bank account, and it's hard for the Host to get the required data when it's tax time.

If we had such a tax Project, it would automatically track the total tax owed and also all the individual transactions adding up to that amount. This is the dataset I need to give my accountant when it's time to pay tax, so it would be super useful. 

The standard way most companies deal with tax is to have a separate bank account for it, and there are really good reasons why this best practice norm evolved (to keep tax to be paid segregated from the main budget and held safe until it's transferred to the government). Having a Project for tax would be the OC equivalent of this same function, and I think it would be a very good pattern to implement.

**Comment by Betree** [comment]
The spirit of the latest ledger changes is to break down contributions into multiple transactions and this proposal goes in this direction. The same functionality can, IMO, be achieved without a project, just by surfacing the information properly in the frontend and making sure taxes are accounted for properly in all balances.

**Comment by alanna** [comment]
One reason I'm suggesting it be a Project is because right now, even if tax was properly surfaced in both Collective ledgers and CSV exports, there is no function for a host to export all transactions across all its Collectives, which is the dataset I need to work with as a host admin trying to calculate tax.

@Betree can you explain in more detail how a host would get this data if it were surfaced as you're suggesting?

**Comment by Betree** [comment]
@alanna We still need to work on a `/host/dashboard/transactions` page to group all transactions across hosted collectives, we know that's something needed, and it should be fairly easy to re-use existing components to build it. From such page, after implementing taxes as separate transactions, it would be as simple as selecting `Taxes` in the `kind` filter and clicking on "Export CSV".

**Comment by Betree** [comment]
Suggested the alternative approach with separate transactions in https://github.com/opencollective/opencollective/issues/5181

**Comment by alanna** [comment]
closing in favor of #5181
