### ISSUE TITLE
Long Fiscal Host and Connected Collective name

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4495]
<img width="1250" alt="Screen Shot 2021-07-24 at 3 08 47 PM" src="https://user-images.githubusercontent.com/5498878/126855786-14353c67-1f1a-4594-9ef7-083c29ec65ef.png">

https://opencollective.com/enablefund

This doesn't look good.

**Comment by SudharakaP** [comment]
For this I suggest we only show both the `Fiscal Host` and `Part of` with a max of 20 characters. Everything else will be truncated to show, `Re-NABLE OpenCollect...`. And when hovered over it we show the full name in a tool-tip (only if it's truncated). 🤔

**Comment by simonv3** [comment]
I can take this one on

**Comment by SudharakaP** [comment]
@simonv3 : Thanks. Let us give a few days for other team members to comment on this so we can see if there's better alternatives to my suggested solution. After that we'll get back to you so that you can take the issue. 😄 

@opencollective/core : Do you agree with my suggestion; or you have any other ideas on this?

**Comment by Betree** [comment]
20 characters seems a bit small, we often use 30 or 60. With 20 `Open Source Collective` would be truncated while it looks good in most cases. But feel free to play with the values to figure out the best one.

There's also another fix for this one: we don't need to show both `Fiscal host:` and `Part of:` if both are the same. In such cases, only the Fiscal Host part should be displayed.

**Comment by SudharakaP** [comment]
@Betree : Thanks for the ideas. 👍🏽 

@simonv3 : If you'd still like to take this one, it's yours. Let us know if you need any help. So we can do the following two things,

- [ ] Use 30-60 characters (whatever looks the best) for the `Fiscal Host` and `Part of`
- [ ] If both `Fiscal Host` and `Part of` are the same only show the `Fiscal Host`
