### ISSUE TITLE
Use I18nAddressFields component in the Contribution Flow

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#4498]
Deprecate the free-form address field in the contribution flow in favor of I18nAddressFields.

**Comment by kewitz** [comment]
@Betree is this still relevant or was this solved with the new collective picker?

**Comment by Betree** [comment]
@kewitz Thanks for the ping, it's indeed going to be resolved by https://github.com/opencollective/opencollective-frontend/pull/7292. Actually, I wasn't sure who to tag as a reviewer for this one, and since you have some experience with this I'd love to get your feedback when you have the time!
