### ISSUE TITLE
Unable to export transactions in certain date range

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4502]
I'm trying to export transactions from: https://opencollective.com/foundation/transactions

I put in 01/01/2020 to today for the range, but when I opened the CSV the earliest ones were from 03/03/2020. So I went back and tried to export the range 01/01/2020-03/02/020, but the little timer just kept spinning and the export never happened.

**Comment by alanna** [comment]
I queried in metabase and found there were 3 transactions in the range that's missing.

**Comment by Betree** [comment]
May it be related to the date format? Maybe it expects to get it in US format (MM/DD/YYYY)

**Comment by alanna** [comment]
I used the date picker. Also, these particular dates are the same either way! 02/02, 03/03

**Comment by Betree** [comment]
In https://github.com/opencollective/opencollective-api/blob/f20af022c6a396609f1083863d2a1d7d51fee1b2/server/models/Collective.js#L2562 it seems that we're using `Lower than`, and not `Lower than or equal`. So we probably have the same issue there as https://github.com/opencollective/opencollective/issues/4424: when `2021-03-03` is provided as an `endDate`, transactions from `2021-03-03` won't be returned.

**Comment by Betree** [comment]
Solved by @znarf in https://github.com/opencollective/opencollective-frontend/pull/6786/files#diff-12c338b9fe130bf1c1278f6f03f56afeed9dc0f486efedd9a72a7cd80e362b86R105
