### ISSUE TITLE
Add "expense invited" to status updates

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4506]
The goal of the status updates in expense comment threads is to be able to tell the full story of an expense from its history, such as who edited it, approved it, paid it, etc.

Right now one action is missing: who invited the expense. I think "Expense invited" should appear at the top here if it was an invited expense:

![Screen Shot 2021-07-30 at 10 04 26 AM](https://user-images.githubusercontent.com/5498878/127571875-5ff918fd-2324-4bf1-b81f-0c400430e9db.png)

You can find the information at the top of the screen in another section, but we should keep it together (it can still appear like this on the top if we also just add it as as status update below as well).

![Screen Shot 2021-07-30 at 10 04 34 AM](https://user-images.githubusercontent.com/5498878/127571994-1735a7c7-0514-400a-85b2-65acc569b027.png)

**Comment by akashgp09** [comment]
Hi @alanna,  I have resolve two `bounty candidate` issues:  #4506 and #4507. 

Can a bounty be added to these issues ?

**Comment by alanna** [comment]
@znarf can you help?

**Comment by znarf** [comment]
@akashgp09 This is not our current process for Bounties, see https://docs.opencollective.com/help/contributing/development/bounties.

I can check if I can add a bounty and a price for those 2 issues. But to be clear, bounties are only paid when the PR is merged and the issue closed.

**Comment by akashgp09** [comment]
Yeah cool, I have opened PR's for these issues and they are ready for a review :)
