### ISSUE TITLE
[Events] TechUp! Aug 21/22

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#4509]
Techup! is 'The I/O Foundation](https://www.theiofoundation.org/)'s a monthly gathering of technologists who are interested in using their superpowers to fight for digital rights and generally support civil society. 

> The [purpose] of the event is to be a platform to enable the transfer of technologists (especially programmers) into civil society. Our plan is to introduce OC for those FOSS projects looking for financial support. They can then decide if they want us to be their fiscal host or anyone else. I'd like to know if you'd be interested in running an intro session to OC or some other capacity-building sessions.

**Event date(s) & Time(s):** Aug 21 

* Talks: (3-4am/3-4pm/4.30-5.30pm/7-8pm/8.30-9.30pm BST) 
* Drop in Q&A (4-4.30am, 5.30-6am, 10-10.30am, 11.30-12pm, 4-4.30pm, 5.30-6pm, 8-8.30pm, 9.30-10pm BST)

**Event URL:**  https://www.airmeet.com/e/4acc1070-ed56-11eb-87a4-93f25825faa1
**Commitment:** 1-2 OC orientation talks/demos and 'booth' for drop in Q&A
**Participants:** @benjam

### Who is the event for?
Technologists (programmers and adjacent professionals) interested in contributing to digital rights and civic tech projects. 

### Why should we contribute this event?
The I/O Foundation is [an Open Collective host](https://www.theiofoundation.org/#ReachOut) and nonprofit advocating for Data-Centric Digital Rights to establish a more solid approach from a technical standards perspective and to raise awareness on the critical role of programmers as the next generation of Human & Digital Rights defenders.

The I/O Foundation would like someone from the team to run an orientation session for folks to learn more about what Open Collective is, how they can use it in their work and (maybe) to apply to IOF or another Open Collective host organisation to support their work.

I think we should do this to support a shot, build a community that aligns with our views and adopt Open Collective as a platform for communities that emerge.

**Comment by BenJam** [comment]
Update: I'm signed up to do an introductory talk at 4.30 UTC on Saturday 21st Aug. 

## Request 
If folks from @opencollective/americas or @opencollective/apac are up for spending 30 minutes on Saturday 21st Aug for folks who may drop into our 'booth' for support please add your name below (and please take some time off the following week to compensate). All times in UTC:

- 3-3.30am
- 4.30-5am
- 9-9.30am
- 10.30-11am
- 3-3.30pm 
- 4.30-5pm (@benjam)
- 7-7.30pm
- 8.30-9pm

**Comment by natehn** [comment]
I can do 8:30-9pm

**Comment by Memo-Es** [comment]
I can do 3-3:30 am or 7-7:30. pm

**Comment by kaylarep** [comment]
> I can do 3-3:30 am or 7-7:30. pm

@Memo-Es I can do whichever of these two times you dont prefer

**Comment by BenJam** [comment]
thank you all, I'll make sure that we're on and that you'd got some guidance to work from.

**Comment by shannondwray** [comment]
I can do the 4.30-5am :)

**Comment by BenJam** [comment]
I am very thankful that this is coming together. I'm pulling together a talk today/tomorrow which I will post here.

**Comment by kaylarep** [comment]
@Memo-Es mind if I take the 3:30am?

**Comment by Memo-Es** [comment]
@kaylarep All good I can take 7 pm BST

**Comment by piamancini** [comment]
I can do 10:30 -11am

**Comment by piamancini** [comment]
wait UTC is 2hrs behind CET not 1. I'll take the earlier slot

**Comment by BenJam** [comment]
okay folks, closing this out as the event I passed. Thanks everyone for contributing 🙌
