### ISSUE TITLE
Goal description not displayed on amount

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4510]
When you create a goal, you can specify a description:

![Screen Shot 2021-08-03 at 3 48 20 PM](https://user-images.githubusercontent.com/5498878/127954770-03af7cda-5bec-4eb3-87fb-ee725f5cb826.png)

However, this text apparently does not show up anywhere. I assumed it would show up when hovering over that goal on the progress bar, but it does not. We either need to find a place to display the description, or remove it from the input form.

**Comment by SudharakaP** [comment]
> However, this text apparently does not show up anywhere. I assumed it would show up when hovering over that goal on the progress bar, but it does not. We either need to find a place to display the description, or remove it from the input form.

@alanna : That is strange. For me, when I hover over the goal title in the progress bar I do see a tooltip with both the goals title and the description as shown below. 🤔 

![Screenshot from 2021-08-02 22-20-54](https://user-images.githubusercontent.com/12435965/127962140-adbc4748-3497-4a4f-958b-0bba137fa70b.png)

**Comment by alanna** [comment]
The description is not showing up on hover for me, nor for the user who reported this. The screenshot of the description above is in the settings of https://opencollective.com/test-abcd but when I mouse over the goal, nothing happens.

**Comment by akashgp09** [comment]
> https://opencollective.com/test-abcd 

My observation is that the tooltip does show up when you hover over the goal title **`Our Goal`**, but When I try to hover over the amount **`$100`** or the interval **`per year`** area, the tooltip does not show up.

**Comment by alanna** [comment]
Ahhhh yes this was the problem. I was hovering on the amount. Can we make it appear for the amount as well? This was tripping up the user, too.

**Comment by akashgp09** [comment]
Year sure, I will open a PR for it :)
