### ISSUE TITLE
Add QR Code for Crypto Deposit Address

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4516]
Depends on https://github.com/opencollective/opencollective/issues/4484

We need to add the QR code in the last (checkout) section of the contribution flow for crypto contributions. In this issue we will not add any API related logic but rather the support to view the QR code based on a hard-coded url. 

We already use the `qrcode.react` in our 2FA flow. We can use this to show the QR code. 

- [x] Create the order on the api side when the user visits this section.
- [x] Show the QR code based on a hard-coded url. 
- [x]  Add the success page when the user click on the finish button.

The figma design is given below: 

https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=13426%3A207907

![Payment Info](https://user-images.githubusercontent.com/12435965/128089067-706b1f22-83ac-4318-b4da-3ddb1aebf6fb.png)

**Comment by znarf** [comment]
The wallet address is not an URL, it's a string such as `13FBJasPZHeqwKqyGs6ACcLCArMK13MZaG`.

In the design, we can see a logo in the middle of the QR code, how are you planning to handle this? Have you checked that is is technical correct?

**Comment by SudharakaP** [comment]
> The wallet address is not an URL, it's a string such as `13FBJasPZHeqwKqyGs6ACcLCArMK13MZaG`.
> 
> In the design, we can see a logo in the middle of the QR code, how are you planning to handle this? Have you checked that is is technical correct?

@znarf : Sorry, yes, it's indeed a string. That's not a problem as the QR code generator will handle that as well; doesn't need to be a string. 

As for the logo, I was going to post about this after a quick implementation (which is almost done now. 😉). This I think isn't feasible. Since a QR code will not be a QR code anymore if we place a logo in the middle. Simply put I don't think it's technically correct, and thus I think we should not have a logo in the middle of a QR code. The use already see the currency at several places (in the description above the QR code, as well as in the contribution summary on the right hand side), so my suggestion is not to include this kinda logo. 🤔

I am open to suggestions though. 😄 

cc: @opencollective/design

**Comment by SudharakaP** [comment]
So I've added the QR code generation screen in the following PR (still draft). There's some minor things to be done here in terms of making it consistent with the design which I'll do tomorrow, and also add the order creation. In the meantime, let me know if you see any issues. 🙂  

https://github.com/opencollective/opencollective-frontend/pull/6719#issue-702672614

**Comment by znarf** [comment]
>  Since a QR code will not be a QR code anymore if we place a logo in the middle.

What is your research on that topic? How have you came to this conclusion?

**Comment by SudharakaP** [comment]
> > Since a QR code will not be a QR code anymore if we place a logo in the middle.
> 
> What is your research on that topic? How have you came to this conclusion?

Hmm, let me search more. I was reading the about QR codes yesterday (mostly the wiki article; https://en.wikipedia.org/wiki/QR_code) and I thought this is impossible since QR codes are barcodes and by adding images in the middle we are changing the barcode in some way. 🤔

**Comment by znarf** [comment]
I personally googled "can I put a logo in the middle of a QR code" and ended up there. https://scanova.io/blog/how-to-make-a-custom-qr-code/

**Comment by SudharakaP** [comment]
> I personally googled "can I put a logo in the middle of a QR code" and ended up there. https://scanova.io/blog/how-to-make-a-custom-qr-code/
> 
> Anyway, if it's complex, it's a distraction and we should not spend too much time on this at this stage.

Oh, you are right. It seems one can remove the data layers in the middle and add the image. I have an idea on how we can do this. Let me add this one to the above PR as well. 🤔

**Comment by Memo-Es** [comment]
Putting the logo in the middle is definitely not a must, we can move forward without it.

So it will be no QR code? @SudharakaP ?

**Comment by SudharakaP** [comment]
> Putting the logo in the middle is definitely not a must, we can move forward without it.
> 
> So it will be no QR code? @SudharakaP ?

No it was my misunderstanding. I initially thought it will mess up the QR code, but I am wrong and we can add the image. I already added the crypto image, so all good. 👍🏽 

![image](https://user-images.githubusercontent.com/12435965/128194322-7f3b2a88-62fe-4127-8fa5-fb5ca1eef403.png)

**Comment by znarf** [comment]
Is it a Bitcoin image in all cases or do you have an image for each crypto currency?

**Comment by SudharakaP** [comment]
> Is it a Bitcoin image in all cases or do you have an image for each crypto currency?

Nope, I added images for all crypto currencies; depending on what the user chose. 🙂 

![image](https://user-images.githubusercontent.com/12435965/128194891-bb68505c-128b-462f-894c-c94cc60fe02e.png)

**Comment by SudharakaP** [comment]
@znarf @Memo-Es : I am gonna add the success page (when the user click on finish) as part of this issue as well since I think it will be a simple change to slightly change our existing success page. The success page is given in the following design; 

https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=13426%3A207901

I have a few suggestions; 

- We should remove the post message box for at least now; since the user might have not completed the transaction yet. 
- We should change the description `You are now supporting...` to something else to indicate that they will be supporting once the transaction is reconciled. Or some kinda indication that they will receive a notice when the transaction is gone through? 

WDYT? 🤔

**Comment by znarf** [comment]
@SudharakaP Please look at the experience for Manual Bank Transfers, it should be similar (uncompleted transaction).

**Comment by Memo-Es** [comment]
@SudharakaP, I can go ahead and update the success page with the idea we had for the modal 

<img width="621" alt="Screen Shot on 2021-08-04 at 09-35-32" src="https://user-images.githubusercontent.com/49539954/128200359-3afa1cbd-5c57-4672-9669-e772515d5d8d.png">

If this makes sense, I'll need a couple of hours to update, but I can have it ready today

**Comment by SudharakaP** [comment]
My thinking is we can use the @znarf's suggestion and use the same Bank transfer page with some minor tweaking. This way we have consistent design for all success pages within the contribution flow unless of course there's any other specific reason to use a different success page for crypto which I am okay with as well. It looks like this currently. 

![image](https://user-images.githubusercontent.com/12435965/128200892-d44a46f6-bd3d-41a6-b3e7-8c68cb61daad.png)

My suggestion is to remove the `Payment Instructions` part for now and I think we should be good. But I maybe wrong here. 🤔

**Comment by znarf** [comment]
> For now I'll also remove the message posting ability since we are not exactly sure if the user did the transaction or not

I don't see why that's needed, it's the same for Manual Bank Transfers and no one ever complained about this.

**Comment by SudharakaP** [comment]
> > For now I'll also remove the message posting ability since we are not exactly sure if the user did the transaction or not
> 
> I don't see why that's needed, it's the same for Manual Bank Transfers and no one ever complained about this.

ah, interesting. Okay we can leave it for now. I was just thinking this cause to me it didn't make sense to let the user post messages before a transaction is fully reconciled. 

> > Once the transaction is completed you will receive a confirmation email with the details.
> 
> Are we?

What I thought was that when the user donates crypto they should receive an confirmation from their wallet service provider. This is why I added it there. Also after the API side is done and we receive the webhook event for transaction completion we can also sent a confirmation email right? Am I missing something here? Do you think we need to add something else? 🤔
