### ISSUE TITLE
contributors.svg not updating

### ISSUE THREAD

**Issue by watadarkstar** [opencollective/opencollective#4517]
**Describe the bug**
The [contributors.svg](https://opencollective.com/heylinda/contributors.svg?width=890&button=false) is not updating to reflect the repository contributors. 

**To Reproduce**
1. Go to a repository 
2. Contribute
3. See how the svg does not update

**Expected behavior**
Updates contributors.svg in real time (or close to it). It's been 2 days and the image has not updated.

**Screenshots**
Image from contributors.svg:
<img width="475" alt="Screen Shot 2021-08-03 at 6 57 45 PM" src="https://user-images.githubusercontent.com/3059371/128096793-6ed372fe-d1cb-4aad-86b3-f5455693a19a.png">

Repository contributors from Github:
<img width="386" alt="Screen Shot 2021-08-03 at 6 57 57 PM" src="https://user-images.githubusercontent.com/3059371/128096814-0e4a0f68-3666-4fc0-bf44-c25448f81527.png">

**Additional context**
Github repo with the problem: https://github.com/heylinda/heylinda-app
contributors.svg link: https://opencollective.com/heylinda/contributors.svg?width=890&button=false

**Comment by watadarkstar** [comment]
Any idea why this might be happening @znarf ?

**Comment by ylemkimon** [comment]
The daily [`70-update-contributions.js`](https://github.com/opencollective/opencollective-api/blob/main/cron/daily/70-update-contributions.js) cron job doesn't seem to be running.

**Comment by znarf** [comment]
We have for quite some time some capacity problems with our GitHub credentials and are unable to refresh the contributors.

As this widget is not a priority for us at Open Collective anymore, we're gonna officially stop maintaining it. For people relying on it, we're gonna extract it in an independent repository and give it to the community. I'll setup this in the coming days.

**Comment by znarf** [comment]
I just released [contributors.svg](https://github.com/opencollective/contributors-svg) as a separate Open Source repository. Anyone is welcome to participate.

I also deployed a new version which should normally fix the issue.

Feel free to open issues and PRs in the new repository.
