### ISSUE TITLE
Order ready to pay expenses by oldest first

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#4518]
## User story 
When processing expenses, the dashboard view would list all Ready to Pay claims with the newer claims showing on top. When a user submits a number of claims, [like in this example](https://opencollective.com/vuetify/expenses/43516#new-comment-on-expense), the older invoices may get 'lost' further down the page (or on a different page altogether). 

When the collective budget is not sufficient to cover all the claims, what may happen is the older expense may disappear from the Ready to Pay view once the available budget falls below the requested payment amount. This may happen before the host admin realized there is an additional claim awaiting payment. This creates frustration for the user as newer invoices are processed for payment, but older ones are falling behind. 

## Best solution for this problem
Is there a way to include a tag/notification to say the user has a number of claims submitted for payment? There may be easier solutions here, but I am not too familiar with them. 

Another option, which would be easy to implement (and may already be considered as part of the new dashboard view) is to include a filter to sort the expenses (Oldest/Most Recent) in the similar way we have[ under Hosted Collectives tab](https://opencollective.com/opensource/dashboard/hosted-collectives) on the host dashboard.

**Comment by znarf** [comment]
This could be improved if Admins could order Expenses and have oldest first.
