### ISSUE TITLE
Updating recurring contribution should update Members

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4519]
When updating a recurring contribution and changing its Tier, we correctly update the `TierId` in the Orders table but should also update the BACKER entry in the Members table accordingly.

We should also create a script to fix the database with past occurrences. 

- [ ] Update Members when updating Order
- [ ] Write script to fix past occurrences (not a migration, so we can trigger it when we want and look at it closely)

Work will likely be around the `updateOrder` mutation in GraphQL v2 and the `updateSubscriptionDetails` / `updateOrderSubscription` related functions.

**Comment by znarf** [comment]
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](https://docs.opencollective.com/help/contributing/development/bounties).

**Comment by znarf** [comment]
@akashgp09 Thank you for looking at this. We expect to see significant progress within 1 week, after this we'll free the bounty for someone else.

**Comment by akashgp09** [comment]
@znarf I think at the moment I don't have much idea of the codebase. Moreover, I have some other works to do this week. 
I am unassigning myself from the issue so that other interested folks can look into it.

Meanwhile, I will continue working with some simpler tasks to get familiar with the codebase :)

**Comment by leonardohofling** [comment]
@znarf is it available? Can I work on it?

**Comment by znarf** [comment]
🏆 This issue was completed by @leonardohofling 

To claim the bounty please, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new  Please make sure to mention the ticket number in the invoice and in the expense title.
