### ISSUE TITLE
Review creation of super collective for Caroline

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#452]
Mail From Caroline:

> Hello there!
> 
> I'm a new member and I'm so excited for what Open Collective is doing!
> 
> Couple of things:
> 
> 1) I just started [this](https://opencollective.com/metapsychosis) collective. It actually belongs to a broader platform co-op initiative called [Cosmos.coop](Cosmos.coop). Both [Infinite Conversations](https://opencollective.com/infiniteconversations) and Metapsychosis belong to Cosmos.coop. I was wondering how to link these together?

Collective link: https://opencollective.com/metapsychosis

**Comment by piamancini** [comment]
done
