### ISSUE TITLE
Event datetime appears to be incorrect in confirmation emails

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#4522]
As reported by @carolineawoolard https://github.com/opencollective/opencollective/issues/4280#issuecomment-891657724

> this seems like a bug - the time zone in the body of the event email is different than the time for the event. 
![Screen Shot 2021-08-03 at 9 36 41 AM](https://user-images.githubusercontent.com/88373348/127986004-2ece1de5-366a-4370-9797-7210a9186abb.png)

**Comment by znarf** [comment]
The Event is running at 9AM/10AM in UTC-07:00. The value on top looks accurate in CEST.

Unfortunately, we're not storing the user timezone and are not able to customize the email for them right now.

Best shot is too clearly state the timezone when displaying the dates in the email, like we do on the website.

<img width="784" alt="Screenshot 2021-08-04 at 15 31 09" src="https://user-images.githubusercontent.com/806/128189692-96b5eb13-b9c8-4b26-85b0-df1fb7b9c2fa.png">

**Comment by znarf** [comment]
Spec: explicitly state the timezone when displaying dates in event email.

A $50 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged. [More info](https://docs.opencollective.com/help/contributing/development/bounties).

**Comment by carolineawoolard** [comment]
This is becoming a major issue lots of people are reporting this to me -- 5 people in the past 24 hours @alanna @piamancini  perhaps you've experienced this as well.
<img width="1027" alt="Screen Shot 2021-08-19 at 1 11 59 PM" src="https://user-images.githubusercontent.com/88373348/130059147-9f61e705-c9ff-4e1c-b16f-5de9bc341618.png">
<img width="1028" alt="Screen Shot 2021-08-19 at 1 11 45 PM" src="https://user-images.githubusercontent.com/88373348/130059152-a1b5f6b9-d1e4-4db5-a3ec-0484fb1f47a8.png">

**Comment by SudharakaP** [comment]
Just for the information the gcal event problem is fixed here; https://github.com/opencollective/opencollective-api/pull/6462#pullrequestreview-734025263. Once this is merged the issue should be fixed. 😄

**Comment by carolineawoolard** [comment]
Wonderful! Let me know when that is.

**Comment by SudharakaP** [comment]
@carolineawoolard : This is fixed now and it's already in production. Sorry I probably forgot to notify you. Let us know if you see this issue again. 😄 😄
