### ISSUE TITLE
Error When Setting New Bank Transfer Details

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4523]
**Describe the bug**

It seems that there's an error occurring when trying to setup new bank transfer information for receiving funds. This was observed both on staging and on locally. 

**To Reproduce**
1. Go to any host collective that you are the admin. 
2. Go to Settings -> Receiving Money
3. Click on the `Set bank details` button.

**Expected behavior**

There should be no error when clicking this button. 🙂 

**Screenshots**

![transferwise-error](https://user-images.githubusercontent.com/12435965/128199459-65814939-90e3-4478-8772-c810ce396dec.gif)

**Comment by znarf** [comment]
@SudharakaP @kewitz can you collaborate on this? Seems like a priority.

**Comment by SudharakaP** [comment]
@kewitz : I think this is probably due to; 

https://github.com/opencollective/opencollective-frontend/blob/64b442b9fd233fb743442d9ddf1fa5ef5488cd26/components/edit-collective/sections/BankTransfer.js#L207

where we assume that the `opencollective-host` (or whatever pointed to by the above env variable) has transfer-wise configured and then use that token which is not the case I think in staging and in my local. I think we should display a warning or info message below the `Add your bank account information` in the `Setttings -> Receiving Money` section if transfer-wise is not configured. Something like, 

>Please configure Wise on `${data.host.slug}` order to display bank account fields.

This is just for good dev experience I guess; my thinking is as long as we have Wise configured (which is the case in prod) this error will not be shown. 

WDYT? 🤔

**Comment by SudharakaP** [comment]
Done a fix for this by showing a warning message when Wise isn't configured. Let me know if it looks good. I don't think an error is the way to go as the user can still submit the custom bank details in the form below. Correct me if I am wrong. Screenshot provided in the above PR. 😄

**Comment by SudharakaP** [comment]
Reopening this as the previous fix was reverted as it shows the warning on production. https://github.com/opencollective/opencollective-frontend/pull/6742#issuecomment-904454053

**Comment by SudharakaP** [comment]
@znarf : I proposed a quick and simpler fix than before in the above PR, the problem that we see in the staging and dev environments is that, `data.host.transferwise` being `null`. Thus checking for that in that component and showing a warning message should I think handle this case. Let me know. 🙂
