### ISSUE TITLE
Add Support to Automatically Reconcile the Crypto Transactions using the Giving Block Webhook

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4527]
We need to reconcile the Crypto transactions when we receive web-hook events from the giving block. Here are the things that needs to be done on this regard. Feel free to let me know if there's anything I've missed. 😃 

- [x] When the webhook event is received, mark the transaction for that particular order as completed (from pending status). 
- [x]  Send an email to the user that the transaction is completed. 

Since we already have the Giving Block webhook skeleton, I think logic related to both of these can be added at, -https://github.com/opencollective/opencollective-api/blob/0e92794f2b70304c98c4c076ba59ac47c3a97e5c/server/paymentProviders/thegivingblock/webhook.ts

The Giving Block documentation on webhooks: https://app.gitbook.com/@the-giving-block/s/public-api-documentation/endpoints-documentation#server-to-server-notifications

cc: @znarf @kewitz

**Comment by SudharakaP** [comment]
We've done the part of this at https://github.com/opencollective/opencollective/issues/4527. (Thanks @znarf). According to our discussion it seems that we are not receiving the `transaction converted` event; https://app.gitbook.com/@the-giving-block/s/public-api-documentation/endpoints-documentation#event-transaction-converted. Until this is clarified with the Giving Block I think we are stuck on fully completing this issue. 🤔

**Comment by znarf** [comment]
For a prototype, we can rely on the the `DEPOSIT_TRANSACTION` event but that definitely can't be considered as a final version.

**Comment by SudharakaP** [comment]
I've added support for sending email for the `DEPOSIT_TRANSACTION` event. I think the only remaining part here is to add the email confirmation for the `DEPOSIT_CONVERSION` event. This shouldn't be difficult I think and I'll add this as soon as we get the `DEPOSIT_CONVERSION` event figured out. 

In the meantime let me know if the email template looks good or if there's any other changes to be made. 🙂
