### ISSUE TITLE
Review possible solutions for previous backers (Jason)

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#453]
Jason would like to know if there is a way to reflect on OC the amount that his backers have already pledged to their project on another platform. **He wants to fully migrate to OC but he is looking for a way to give credit to his previous backers.**  So basically look for possible solutions or a way to attend this kind of requests. **He has above 90 backers.** 

E-mail from Jason:

> Hi,
> 
> I have a question as our group is interested in migrating to your platform for revenue generation through donations.  We are currently a 501c3 non-profit.  We currently utilize MeetUp as our primary platform.
> 
> Is it possible to migrate our paid members from MeetUp into your system at Open Collective?  Is it possible to do this automatically or manually?
> 
> For further clarification, if we have some paid members can we generate accounts for them (or have them generate accounts themselves) and denote in the system that they have paid a donation.
> 
> Thanks for the assistance.

--------------
Another email reply from Jason:
> It looks like we have about 98ish members to transfer over.
> 
> I guess my primary concern here is that they have pledged a certain amount of money to us annually and I'd like to make sure that amount is reflected into their account if we choose to use your platform.  Is it possible to reflect that they have Subscribed/Donated at a certain dollar amount from the pool of money we would transfer into your system?

**Comment by piamancini** [comment]
closing this. solved via email
