### ISSUE TITLE
Thank You email should be sent to ALL admins and accountants

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4530]
We're surprisingly only sending the Thank You email to the person who setup a recurring contribution (`order.createdByUser`).

Generally, and especially for Organizations, we should send an email to all ADMINs using our standard mechanism.

We should also include ACCOUNTANTs because they're the one usually needing the attached receipt.

**Comment by Betree** [comment]
Related: #3626

**Comment by BenJam** [comment]
Also: https://github.com/opencollective/opencollective/issues/4687

**Comment by Betree** [comment]
Looks like this was done as part of https://github.com/opencollective/opencollective-api/pull/6465/files#diff-e3003d7eec42b2c6736d3f0fcecd26cd90e86fee3199826cd43d2760982ca1cdR442. I'll add tests to consolidate this feature and options to include accountants as targets with https://github.com/opencollective/opencollective/issues/3626
