### ISSUE TITLE
Duplicate buttons on Conversations page

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4535]
<img width="1073" alt="Screen Shot 2021-08-07 at 11 50 33 AM" src="https://user-images.githubusercontent.com/5498878/128580706-e9ffb312-86e9-477a-ad5e-889d480ca7c4.png">

**Comment by SudharakaP** [comment]
Thanks for reporting @alanna . 😄 I think we need to not show the `Create a Conversation` button when there's no conversations rather only the `Start a new conversation` button. I'll do a PR soon.
