### ISSUE TITLE
Support Metrics Report July 2021

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#4540]
### Support Metrics Report July 2021

This report looks at the trends around support to help us better understand areas we need to improve and highlight key topics for the month. 

**Tickets received** 

![Capture](https://user-images.githubusercontent.com/57156267/128799167-11094791-2ef4-47d5-95a6-cb7fdc121fc3.png)

The number of tickets received increased by 11% from 1,452 in June to 1,610 in July. During April we linked all the OC emails to go through FreshDesks. By removing blank tickets and expenses notifications where no action was required, the rise during July was about the same level (9%) with 646 tickets compared to 590 in June. [You can find the detailed listings here.](https://docs.google.com/spreadsheets/d/1pO6FQzpxUXpBms43J94rxhX4toU2IP3S/edit#gid=1314162218)

_Note:_ From a data extract it seems the tags we use when categorizing tickets on FreshDesks require a review and with the overall increase in the number of team members looking at support tickets these days we are looking to make some changes to the way the monthly review is conducted to ensure the metrics presented here to make sense and still relevant. 

![Capture](https://user-images.githubusercontent.com/57156267/128799530-8507c46a-e052-4e07-b045-57c493a8d5e1.png)

**Trends and Recommendations**
After removing irrelevant tickets, we had 646 that required support attention. It is worth noting the following areas:

**Expenses**

While expenses keep on being our biggest area of attention, it seems like the number of tickets requiring actual support attention is on a decline in comparison to a previous couple of months. It may also be a relative decline as during June we processed a number of big payout rounds for Season of Docs and FundOSS.

One area of additional challenge over the course of July was the payouts to India. With the changes in regulations with the local banks, there were further restrictions put in place on international payments coming from non-for-profit organizations from overseas. This change means we no longer can integrate Wise as a payout and need to limit the options available to users to PayPal or Payoneer/Wise generated profiles. As we previously processed bank transfers more easily, the change has caused some confusion to the users invoicing us for a while now. In addition, we need to ensure we pay a lot closer attention to those expenses. The payments may still go through Wise but it puts our account at risk (with the potential for it being suspended). To minimize the likelihood of this scenario from occurring we removed INR from the currencies list. 
 
**Onboarding**

Onboarding related questions are still some of the common ones we receive. There is a 40% increase in the number of new initiatives joining OCF and a slight reduction (9%) in the numbers of collectives onboarded with OSC. Here is how it was distributed:

We approved 38 new applications for OCF in July compared with 27 in June.

For OSC -  80 new collectives were approved this month compared to 89 in June. 

**Other things worth noting:**

- Cash assistance related inquiries are reducing lately, with the volumes of expenses being processed are tracking quite low. Some initiatives are waiting for the introduction of grants which are to be a better fit for processing financial assistance requests. In general, the number of related questions has decreased significantly which is a good indication for us that the policies we worked on are there to provide the guidance and support needed (same is applicable for outside entities).
- We (Alina & Ember) were having a conversation with Amina as she is working on the redesign of the contact page with a better integration with our support page to help users find the answers they are after ahead of contacting us. This is an interesting space to watch - and the initial layout looks like such a big improvement to what we currently have in place!

**Comment by alanna** [comment]
Thank you @alinamanko ! Is there anything that stands out to you in terms of improvements (to the software or our processes) that would save support time or make things easier?

**Comment by alinamanko** [comment]
One thing Ember and I talked about yesterday is consolidating the tags used as right now we have a lot of new ones created lately and it would make the reporting more meaningful once the information is properly grouped. 

I also am thinking about how we could perhaps have an easy process around flagging any critical topics in one spot. With more people looking at tickets it means having the report run by one/two people may become a bit more challenging as we are not on top of everything and as we keep on growing that may become a bigger issue.

**Comment by shannondwray** [comment]
Hey Alina, Are there any common questions surrounding expenses and onboarding that we could add to the docs? Would it be worth aiming to get to a stage where when someone asks your a question that is common there is a docs page that is easily linked out to? Let me know if I'm on the right track and this could help or if I'm not :)

**Comment by alinamanko** [comment]
@shannondwray this is the conversation I had with @aminakazi and I think she has it captured. We were looking at the main areas of supporting splitting [around these areas](https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab?node-id=11592%3A91851). While questions change, the main areas are around setting up a new collective and initial information users are looking for before figuring out if we are the right fit for them, questions around getting funds out of the collective, contribution methods and ways to pay. Questions will also vary when we introduce new features if these are driving users' interest. Happy to have a chat with you to look at the information in more details if you'd like
