### ISSUE TITLE
Create new Project button missing from Projects page

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4543]
https://opencollective.com/ehf-community

<img width="1253" alt="Screen Shot 2021-08-12 at 4 33 14 PM" src="https://user-images.githubusercontent.com/5498878/129139006-6c633f8f-9de6-4ecf-ab5d-f01ab941b9bc.png">

https://opencollective.com/ehf-community/projects
<img width="924" alt="Screen Shot 2021-08-12 at 4 38 05 PM" src="https://user-images.githubusercontent.com/5498878/129139015-2ae17899-0355-48b9-bc0b-2a3167e2cb7e.png">

**Comment by SudharakaP** [comment]
I think here, we need to add a `Create Project` button similar to the `Create Event` button which we have on the events page. I've done that on the above PR. 👍🏽
