### ISSUE TITLE
PAYMENT_PROCESSOR_FEE kind should be renamed

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4544]
It's a bit misleading and should be replaced by something more specific like `PAYMENT_PROCESSOR_FEE_REFUND` or `PAYMENT_PROCESSOR_FEE_COVER`.

We'll later need the `PAYMENT_PROCESSOR_FEE` kind if we decide to split Payment Processor Fees from Transactions.

While we're at it, it should be also ignored from the total money raised. To avoid such situation:

<img width="1255" alt="Screenshot 2021-08-16 at 09 57 38" src="https://user-images.githubusercontent.com/806/129530729-d34827ad-b69e-4d32-a157-e55c2faf42cd.png">

**Comment by Betree** [comment]
`PAYMENT_PROCESSOR_FEE_REFUND` could introduce some confusion with `isRefund` . I prefer `PAYMENT_PROCESSOR_FEE_COVER`.
