### ISSUE TITLE
Move a contribution to a different profile / make it incognito

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4550]
# User story
- Some users make incognito contributions and later want to move them to their "main profile" (like [here](https://opencollective.freshdesk.com/a/tickets/31431))
- Some users want to make their contribution incognito after contributing
- Some users contribute through their personal profile, while they wanted to contribute as an organization

We currently handle these kinds of requests through support, which is time-consuming.

# MVP

We may want to create a path for these users to make the switch themselves. On the contributions, we could add something like "Move this contribution", surfacing all the profiles users can access (their incognito profiles, orgs they're admin of, etc).

<details>

<summary>Keywords</summary>

_Transfer contribution, make / mark contribution as incognito, move contribution to organization profile_

</details>

**Comment by piamancini** [comment]
How often does this happen?

**Comment by Betree** [comment]
I the past few months, I had to switch 2 contributions from the main account to incognito, and one contribution from incognito to the main account.

This issue is far from a priority, but I wanted to document the use case for people to edit the author of a contribution. Technically, it's relatively close to the need for people mistakenly contributing as users to move their contribution to an organization profile.
I'm actually going to edit the issue description to surface this.

**Comment by Betree** [comment]
This could also be implemented as a root action in a first step.

**Comment by Betree** [comment]
I would love to prioritize a root action for this one. Moving contributions is a very frequent support request that takes some engineering time almost every week. I made a [quick draft](https://excalidraw.com/?ck_subscriber_id=796047827#json=E6ofnw63fJPjXQUa017eY,Mz3fQChw8SUm5EQT2AamsQ) of how that could look like. Ideally, the "account" pickers should list user's incognito profiles (but we can skip that part for the MVP):

![Untitled-2021-09-27-0924](https://user-images.githubusercontent.com/1556356/148045169-fded8d2e-391d-442f-8f02-64bc333eb00d.png)

Things we'd need to check on the API:
- When moving a transaction, all the other transactions using the same payment method must be moved as well
- Can't move a transaction if the payment method is an account balance (at least for MVP)
- Balances? (or just add a disclaimer, since this is for root only)

**Comment by Betree** [comment]
Having support for tagging a contribution as "incognito" in the MVP would be really useful as well, it's a very frequent request that is time-consuming because you often need to create the incognito profile manually. And [the need](https://opencollective.freshdesk.com/a/tickets/52983) is not going away any time soon:
> We have some contributions in our collective that we want to make anonymous. It has happened before and it will happen again. How could we anonymize / delete these transactions.

Based on the [mockup above](https://github.com/opencollective/opencollective/issues/4550#issuecomment-1004692664), I would suggest starting with an `@{user}'s incognito profile`  entry in the "Move to" picker.

**Comment by BenJam** [comment]
quick note that I'll update later: it would be good to add an option to mark _all_ contributions for a profile as incognito to service 'right to be forgotten' requests.

**Comment by Betree** [comment]
Demo:

https://user-images.githubusercontent.com/1556356/148803153-7cf2e185-a194-4be5-9c3f-64803dd82986.mp4
