### ISSUE TITLE
Button for root users to invalidate the cache for an account

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4551]
Core team members often have to make direct changes in the database (eg. to change some info about a contribution, create connected accounts, etc). A challenge that comes with this is the cache, we usually need to update Redis and Cloudflare which requires connecting to each service and manually invalidating each entry.

I'd like to be able to do something like this in my shell to clean all caches in one command:

```bash
heroku run scripts/clear-cache.ts COLLECTIVE_SLUG
```

**Comment by Betree** [comment]
Thinking about it more, this should rather be a root action in the frontend as it can be useful for other team members

**Comment by piamancini** [comment]
yes to that last comment

**Comment by Betree** [comment]
Implemented in https://github.com/opencollective/opencollective-frontend/pull/6768
