### ISSUE TITLE
Completely Remove `utm` parameters from URLs

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4555]
This was initially reported at, https://opencollective.slack.com/archives/C6JTTA4SK/p1629294683060700

Our Slack urls in email templates are broken due to having Google analytics tags. These should be removed from all email templates along with all other places we use the utm parameters. 😄

**Comment by znarf** [comment]
It's not just about Slack URLs, utm parameters should be completely removed from the codebase.

**Comment by SudharakaP** [comment]
> It's not just about Slack URLs, utm parameters should be completely removed from the codebase.

Thanks, I've updated the issue with this. 👍🏽
