### ISSUE TITLE
Receipt and payout details missing from expense on mobile

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4560]
https://opencollective.com/openipc/expenses/47728

Payout method and account are not present, and there seems to be no attachments section or way to see the receipt.

This is Firefox focus on a pixel 4a.

![CollageMaker_20210820_153915656~2.jpg](https://user-images.githubusercontent.com/5498878/130175740-38d0a80c-bf5d-43b1-a711-3b472f050187.jpg)

**Comment by alanna** [comment]
Tried on regular Firefox for Android, same.

**Comment by Betree** [comment]
I can easily reproduce on Firefox desktop. One issue is https://github.com/opencollective/opencollective/issues/4099, but there's something else here: the container doesn't seem to grow with its content:

![Peek 2021-08-20 08-59](https://user-images.githubusercontent.com/1556356/130193454-7b4493af-349e-413c-a8aa-e9ba18184605.gif)

**Comment by kewitz** [comment]
Fixed on https://github.com/opencollective/opencollective-frontend/pull/6425.
