### ISSUE TITLE
Mark expense as spam should be moved to the toolbar

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4562]
Too many people use "Mark expense as spam" as a way to delete the Expense because they don't find the delete button.

This is causing problems because they end up being blocked or blocking legit people, I would suggest we move it to the toolbar next to the delete button. Unfortunately, people will be less likely to use it once it's moved.

Also, before proceeding, we should Confirm with the user that they're intent is correct, they understand what it's doing and they want to proceed.

**Comment by Betree** [comment]
This issue might be resolved by https://github.com/opencollective/opencollective/issues/3813, by moving the actions inside the expense status dropdown

**Comment by Betree** [comment]
![image](https://user-images.githubusercontent.com/1556356/130260239-991b1de0-4bf4-430e-a0aa-3a9282927924.png)

**Comment by Betree** [comment]
I feel like https://github.com/opencollective/opencollective/issues/3813 + https://github.com/opencollective/opencollective/issues/4715 completely resolved this issue.

**Comment by Betree** [comment]
My bad, we actually haven't moved the "Mark as spam" button yet

![image](https://user-images.githubusercontent.com/1556356/172549873-6af2eb25-6d0e-4c77-ad64-1e4f5169cc26.png)
