### ISSUE TITLE
Dropping Values from Enum - Recreate Enum Instead

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4563]
Working on another issue, I noticed the following migration block from `20210615074327-platform-tip-debt-kind.js`

```
await queryInterface.sequelize.query(`
      ALTER TYPE "enum_Transactions_kind"
      DROP VALUE IF NOT EXISTS 'PLATFORM_TIP_DEBT' AFTER 'PLATFORM_TIP'
    `);

    await queryInterface.sequelize.query(`
      ALTER TYPE "enum_Transactions_kind"
      DROP VALUE IF NOT EXISTS 'HOST_FEE_SHARE_DEBT' AFTER 'HOST_FEE_SHARE'
    `);
```

https://github.com/opencollective/opencollective-api/blob/ab9f654fd0a8583692a30651f7654f4bbbf6e0ba/migrations/20210615074327-platform-tip-debt-kind.js#L36-L44

I am doubtful this works. As per [the documentation](https://www.postgresql.org/docs/current/datatype-enum.html); 

>Existing values cannot be removed from an enum type, nor can the sort ordering of such values be changed, short of dropping and re-creating the enum type. Something like the following which we've added in a [recent PR](https://github.com/opencollective/opencollective-api/pull/6460);

```
down: async queryInterface => {
    await queryInterface.sequelize.query(`
      UPDATE "Transactions"
      SET "kind" = 'CONTRIBUTION'
      WHERE "kind" = 'BALANCE_TRANSFER'
    `);

    await queryInterface.sequelize.query(`
      ALTER TYPE "enum_Transactions_kind" RENAME TO "enum_Transactions_kind_old";
    `);

    await queryInterface.sequelize.query(`
      CREATE TYPE "enum_Transactions_kind" as enum ('ADDED_FUNDS', 'CONTRIBUTION', 'EXPENSE', 'HOST_FEE', 'HOST_FEE_SHARE', 'HOST_FEE_SHARE_DEBT', 'PAYMENT_PROCESSOR_FEE', 'PLATFORM_FEE', 'PLATFORM_TIP', 'PLATFORM_TIP_DEBT', 'PREPAID_PAYMENT_METHOD')
    `);

    await queryInterface.sequelize.query(`
      ALTER TABLE "Transactions" ALTER COLUMN "kind" TYPE "enum_Transactions_kind" USING "kind"::text::"enum_Transactions_kind"
    `);

    await queryInterface.sequelize.query(`
      ALTER TABLE "TransactionSettlements" ALTER COLUMN "kind" TYPE "enum_Transactions_kind" USING "kind"::text::"enum_Transactions_kind"
    `);

    await queryInterface.sequelize.query(`
      DROP TYPE "enum_Transactions_kind_old"
    `);
  },
```

https://github.com/opencollective/opencollective-api/pull/6460/files#diff-3ac916a99f20c88e62946cfd6ce63ac29f4b479ba8ee3a6f0edf6c7c6c856ceaR11-R38

Suggest changing this dropping of the enum values to this format. 

cc: @Betree

**Comment by Betree** [comment]
@SudharakaP Good catch, but no need to spend time fixing this. You can eventually replace the queries with a simple comment, but we won't rollback this migration now so no need to spend time fixing it.

**Comment by SudharakaP** [comment]
> @SudharakaP Good catch, but no need to spend time fixing this. You can eventually replace the queries with a simple comment, but we won't rollback this migration now so no need to spend time fixing it.

Thanks, I've added a simple comment to warn users who see this. 👍🏽
