### ISSUE TITLE
Create a 'feed' for all Updates posted on OC

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#4564]
having a RSS-type 'feed' where **all** public Updates posted anywhere on OC can be viewed all in one place, maybe even sortable/searchable 

e.g. View all Updates under _ fiscal host, Sort by: Newest; Oldest; Hottest (received the most engagment/comments -we don't have many right now, but perhaps this could help with that), having a 'search bar' within Updates to find specific key words or tags

**Comment by piamancini** [comment]
+1 to this

**Comment by Betree** [comment]
That'd be an effortless feature to implement. My main fear is about spammers; we know they've used updates as a way to post their dubious content in the past, and having such a page would create another incentive for them to do so.

We should maybe surface only updates from "trusted" accounts, for example, only those with > 3 contributors.

**Comment by znarf** [comment]
Good feedback, it would be quite ugly without some moderation or policy.

**Comment by alanna** [comment]
How about we just begin with Updates from known Hosts like OSC, OCF, OC, AfC, SCN, OCEU, etc? Then we can add others if they request, and solve the deeper moderation policy issues later. 

I think the main risk is from self-hosted Collectives. There are some really cool ones we'd like to highlight but I don't think it's the first concern.

**Comment by Betree** [comment]
@alanna This overlaps with a need to have "trusted hosts" that we've talked about in the past. Having an easy way to tag hosts that we know are legit and serious would be helpful to enable sensitive features like this one or cross-host contributions.

**Comment by alanna** [comment]
The number of trusted hosts is small enough that I'm confident we can
manage that manually, for example via the root admin dashboard. If we had
such a designations built into the code.

**Comment by kaylarep** [comment]
also, on a granular level (and in line with reimagining what a 'Fiscal Host' page looks like), having all of a fiscal host's Collective's Updates on that host's page. 

e.g. as a OCF fiscal host admin, I'd love to be able to have [this](https://opencollective-metabase.herokuapp.com/question/563-ocf-updates) displayed in real time. right now its private and off-platform which is a bit of disservice

**Comment by kaylarep** [comment]
related: https://github.com/opencollective/opencollective/issues/3504

**Comment by Betree** [comment]
On the frontend side, we'd need to change a bit the wording compared to the current page. Proposal below.
As mentioned above, we'll need to filter the updates. The easiest solution seems to rely on the `isTrustedHost` field.

We'll also need a query at the root level to fetch all updates.

![image](https://user-images.githubusercontent.com/1556356/180398839-c6927e3a-cc52-4053-b48b-bd3bde92aa2b.png)

**Comment by alanna** [comment]
In an ideal world, this would also be viewable per Host, and be linked from Host pages. But it's fine if that's not considered for MVP.

**Comment by alanna** [comment]
We should probably ensure #5690 is done so the order will be correct on the feed

**Comment by BenJam** [comment]
quite like this idea from the point of view of creating more clarity between the public facing parts of Open Collective (profile pages) and the work-like aspects of Open Collective from a user's perspective. 

I like the idea of coming back to opencollective.com and seeing an activity feed of updates from projects i support alongside some data on the projects and how they doing a la https://github.com/opencollective/opencollective/discussions/5745

**Comment by Memo-Es** [comment]
I've been thinking about redesigning the way we display updates for them to be less financial-looking and more social-looking, if that makes sense. Right now, they are too close to transaction components, with a layout unsuitable for displaying media content, for example. Which, in my opinion, would be an excellent thing for engagement. Having that done, we then need to design the right way to have this on a public page, on a 'global' level (All OC Collectives), 'Host' level (Updates coming from hosted Collectives), and 'Collective' level, that would be basically the redesign of the current 'Updates' section in the Collective page.

If we do grab this one, I would like to tackle it together with #1445 :)

**Comment by BenJam** [comment]
> I like the idea of coming back to opencollective.com and seeing an activity feed of updates from projects i support

just wanted to add that I imagine this working like github.com dashboard (but, y'know... good) 

![Screenshot 2022-08-16 at 15 16 04](https://user-images.githubusercontent.com/158833/184902171-b632ce76-8491-4744-8ccb-b397a3e2c2e0.png)

**Comment by alanna** [comment]
Interesting, I hadn't thought about grouping by Collectives I support. 

Maybe the best implementation would be
* global feed of Updates from Collectives in all trusted hosts on the homepage
* feed of that Host's Collectives on the Host page
* Feed of Collectives you're connected to on your own profile page

**Comment by Betree** [comment]
This is now possible on the API thanks to @gustavlrsn's work in https://github.com/opencollective/opencollective-api/pull/8297

**Comment by kaylarep** [comment]
@gustavlrsn @Betree amazing! Is this something we can present publicly as a Demo or  'how to' guide blog post?  Im not intuitively understanding how this works.

**Comment by Betree** [comment]
@kaylarep For now it is not really interesting for end-users, only for developers. It being available on the API means any developer can easily fetch them, but we still need to build a proper page/interface. I don't think it's worth writing a blog post at this stage.

**Comment by BenJam** [comment]
@kaylarep I'm going to close this based on the work that @gustavlrsn did on https://discover.opencollective.com/ (see updates at the bottom). We also have the personal 'feed' in the new user dashboard. 

If you dont agree that this issue is (mostly) addressed by the above I'm happy to reopen ✌️

**Comment by kaylarep** [comment]
@BenJam my only thought is that https://discover.opencollective.com/  doesn't appear to be showcased anywhere from www.opencollective.com - and it definitely should be! so this 'feed' is pretty buried right now. 

Off the top of my head, i'd add it
- to the header, maybe under the title 'Discover'
- in the footer,
   - I'd edit the 'Discover' link to say "Find a Collective" (more in tune with the other titles under there)
   - then link to the https://discover.opencollective.com under 'Community': "Discover Collectives"
- probably in the middle content somewhere too, its a really great feature that helps users see the work OC supports
