### ISSUE TITLE
Wrong bill to entity on downloaded invoice

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4570]
I went [here](https://opencollective.com/parentpreneur-foundation/expenses/48095) and downloaded the invoice.

<img width="823" alt="Screen Shot 2021-08-24 at 12 59 02 PM" src="https://user-images.githubusercontent.com/5498878/130538685-51540186-bc1d-489f-b85e-53eb6f6f3bd7.png">

This should be billed to the Host, not the Collective. The Collective is not a legal entity who can be billed.

However, I tested it with [another expense](https://opencollective.com/study-into-action/expenses/47483) under the same Host but a different Collective and OCF is appearing correctly as the bill to entity. 

<img width="832" alt="Screen Shot 2021-08-24 at 1 04 07 PM" src="https://user-images.githubusercontent.com/5498878/130538953-12827b0e-119e-4034-a8a8-742b657dc181.png">

So what's going wrong with ParentPreneur? The only ideas I have are maybe because it's a Fund? Or because ParentPreneur set an address in their settings but the other Collective didn't?

**Comment by Betree** [comment]
> So what's going wrong with ParentPreneur? The only ideas I have are maybe because it's a Fund?

Good guess, I need to adapt the PDF service to support this.

**Comment by Betree** [comment]
@alanna This should be fixed now, please let me know if it does not work

**Comment by alanna** [comment]
It's still not working correctly @Betree

**Comment by Betree** [comment]
An outdated dependency caused the fix not to work; I initially didn't test it correctly. I'm updating this dependency in https://github.com/opencollective/opencollective-pdf/pull/761, I've tested it more in-depth this time.

**Comment by Betree** [comment]
@alanna The fix is now in production, could you try again and let me know how it goes?
