### ISSUE TITLE
Expenses missing from navbar budget section dropdown

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4571]
https://opencollective.com/max-hunter - there are expenses but expenses doesn't show up in the menu with transactions.

<img width="767" alt="Screen Shot 2021-08-24 at 1 20 43 PM" src="https://user-images.githubusercontent.com/5498878/130540315-f17f538b-e5e1-4f7a-91db-301500fbf70c.png">

<img width="1230" alt="Screen Shot 2021-08-24 at 1 20 52 PM" src="https://user-images.githubusercontent.com/5498878/130540327-c938af95-c3ca-441b-be76-6f88defdd430.png">

**Comment by snitin315** [comment]
Probably because it is a `user` profile and not a `collective` profile.

**Comment by Betree** [comment]
@snitin315 is correct, we don't yet have an expense section for users.

**Comment by alanna** [comment]
That explains it
