### ISSUE TITLE
E2E Tests Failing at Contribution Flow Intermittently

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4573]
I've noticed recently that the the guest flow e2e tests related to the contribution flow has become unstable. Seems to fail with the following message; 

>1) Contribution Flow: Guest contributions
       Joins after a single contribution:
     AssertionError: Timed out retrying after 15000ms: expected '/user-f89f04a4' to include '/guest-'
      at Context.eval (http://localhost:3000/__cypress/tests?p=test/cypress/integration/18-contribution-flow-guest.test.js:1001:29)
>
>2) Contribution Flow: Guest contributions
       Make multiple contributions in the same session
         Join Open Collective:
     AssertionError: Timed out retrying after 15000ms: expected '/rick-astley' to include '/guest-'
      at Context.eval (http://localhost:3000/__cypress/tests?p=test/cypress/integration/18-contribution-flow-guest.test.js:1117:31)

My investigation suggest this is related to the following commit; https://github.com/opencollective/opencollective-api/commit/1469e9291432023cd9a552737595fc544ce4a8ce. I haven't exactly narrowed down the root cause or the fix yet. 🤔  

cc: @Betree

**Comment by Betree** [comment]
This is the one I reported in https://opencollective.slack.com/archives/C0RMV6F8C/p1629711991110100. A rebate should solve your issue

**Comment by SudharakaP** [comment]
> This is the one I reported in https://opencollective.slack.com/archives/C0RMV6F8C/p1629711991110100. A rebase should solve your issue

Somehow I missed this Slack thread. Thanks for the info. 😄
