### ISSUE TITLE
Project should not be able to submit expense to itself

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4574]
I'm not sure how the user ended up doing this, but they've accidentally created [this expense](https://opencollective.com/common-unity-project-film/expenses/48132) to a project as payable to that same project. I have asked them to correct this by editing the expense, but shouldn't the system not allow it in the first place?

<img width="887" alt="Screen Shot 2021-08-25 at 12 13 22 PM" src="https://user-images.githubusercontent.com/5498878/130706054-1f9fdcaa-54d6-4f23-a082-ce4c4ab81476.png">

**Comment by Betree** [comment]
I'm not aware of any use case for that. It sounds like API should prevent this and the option should also not be displayed in the Frontend. I just reproduced on staging, while the option is not displayed by default in the collective picker it appears if you search the account name.

Ping @znarf @kewitz in case there's a legit use case for this

**Comment by znarf** [comment]
Per current convention, it's a way to remove money from your budget when there is no clear payee.

It's supported for all kind of accounts and I don't see what would be specific to Projects.

**Comment by alanna** [comment]
OK I can see how that could be useful.... I'll just confirm how the user ended up doing this. I suspect that due to people having projects now, a much larger number of users will have the experience of having multiple profiles to choose from, when they aren't used to how that functions. We might need to help the user understand what it means better.
