### ISSUE TITLE
Add Documentation about Crypto Contributions 

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4575]
We need to add some documentation about the Crypto Contributions. Some of the things which I thought might be useful are; 

- How to enable Crypto contributions as a collective: By going to the collective settings and Tiers section. 

- Some screenshots of the flow up-to the deposit address section, explaining the scanning of the QR code. 

- Some information on the approximate time that one has to wait in order to receive the order confirmation.

**Comment by shannondwray** [comment]
https://docs.opencollective.com/help/financial-contributors/crptocurrencies

**Comment by shannondwray** [comment]
https://docs.opencollective.com/help/collectives/collective-settings/tiers-goals

**Comment by SudharakaP** [comment]
Thanks @shannondwray and @BenJam for adding the crypto documentation. This seems to be done and therefore I am closing the issue. 😄
