### ISSUE TITLE
Visual bug Windows 7 by Nenad

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#458]
Mails from Nenad:

> I have an issue to report: when I scroll down black footer stripe moves up and covers the content. Windows 7, Chrome. Screen shot attached.

> I don't use privacy badger or ad blocker (as far as I know). In Chrome incognito window footers stays at the bottom when I scroll. 
> 
> I just checked it in Microsoft Explorer - there the footer stays at the bottom but there is lot of blank space between budget and footer with message "An unexpected error has occurred." See attached screen shot. 

![black_stipe](https://user-images.githubusercontent.com/30665166/31310285-05529906-ab5b-11e7-854c-863fd2183abb.JPG)
![explorer_white](https://user-images.githubusercontent.com/30665166/31310286-0557752a-ab5b-11e7-8e24-1712eda16e57.JPG)

**Comment by piamancini** [comment]
user didn't report this again
