### ISSUE TITLE
Add support for legal name in the expense flow

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4584]
Part of https://github.com/opencollective/opencollective/issues/3689
Require https://github.com/opencollective/opencollective/issues/4581

- [x] Expense summary: if a `legalName` is provided for the payee, show it along with the real name (`Legal name (display name)`)
- [x] Also in the expense pages (create, edit, view) display the legal name of the host
- [x] In the expense form, if a legal name is defined for the payee, make sure it's set by default when adding a bank account and don't allow users to change it (there should be a tooltip to explain why it cannot be edited)

**Comment by Betree** [comment]
Let's tackle the last item from https://github.com/opencollective/opencollective/issues/4581#issue-979936660 at the same time as this one, it will be easier for testing.

**Comment by SudharakaP** [comment]
> Let's tackle the last item from [#4581 (comment)](https://github.com/opencollective/opencollective/issues/4581#issue-979936660) at the same time as this one, it will be easier for testing.

Yes, I'll add this API part tomorrow. For the front-end part I've added support for the tree items mentioned in this issue in the [above PR](https://github.com/opencollective/opencollective-frontend/pull/6818). There's one small doubt though. In the second item you've written, 

>Also in the expense pages (create, edit, view) display the legal name of the host

As you can see in the screenshots in the PR I've added the legal name of the host in the expense view screen. However correct me if I am wrong but it seems that the host name does not appear anywhere on the expense edit or create screens. 🤔

**Comment by SudharakaP** [comment]
> Let's tackle the last item from [#4581 (comment)](https://github.com/opencollective/opencollective/issues/4581#issue-979936660) at the same time as this one, it will be easier for testing.

@Betree : So this part is added at, https://github.com/opencollective/opencollective-api/pull/6545. Screenshot given in PR. 😄
