### ISSUE TITLE
Add a discord link to collective/host's pages

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#4588]
## User story 
User feedback:

> Is there any way to put the discord link on the homepage of our host? Like there is a link to the website?

## Best solution for this problem
Add it either here in the Info section of settings: 
![image](https://user-images.githubusercontent.com/64920686/131032758-f271aebc-922b-4bfc-9a4b-2470edc3b0e3.png)

OR
As a dropdown option in the 'Contact' button

## Goal
More options for people who want to contact a host/initiative

**Comment by kaylarep** [comment]
good points and questions to raise @Betree...
I hadn't heard of Mattermost until now, but I know that Discord is gaining popularity as a tool amongst a lot of different groups right now (in the states at least, also in Europe from All4Climate's feedback.

Would it be possible to have many options available in the settings and then let the page admin select which 3 they want to be displayed? For example, github is popular within the OSS community, but not so relevant to OCF's hosted groups- sometimes group admin's will get confused and create a github so that it can be displayed on their profile page, but it's likely not something they will ever use, so it just sits on their page for no real reason.

**Comment by Betree** [comment]
Closing in favor of a more generic approach: https://github.com/opencollective/opencollective/issues/5097
