### ISSUE TITLE
Contribute incognito as a guest

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4591]
We pretty often face the case on support (see [this one](https://opencollective.freshdesk.com/a/tickets/32835) for example) where people who contributed as guests do not find any option to contribute incognito and are later surprised to see their real name displayed. 

@Memo-Es I remember we had something like a "Contribute incognito" checkbox on the info step at some point. Did we keep that idea? Should we implement it?

As of today, here's what the info screen looks like for them: 
![image](https://user-images.githubusercontent.com/1556356/131100561-9a412f89-bf51-4127-9595-440f9db37a3e.png)

**Comment by Memo-Es** [comment]
With the newest improvements to the contribution form, we solved this not by leaving the incognito checkbox but rather having the 'Display name' as optional; if the user leaves it in blanc, the contribution appears as 'incognito.'

![Annotation on 2021-09-08 at 15-39-43](https://user-images.githubusercontent.com/49539954/132582245-f19b5210-28c9-4068-857e-382f59c0c509.png)

Question: What's the difference (If there is any) of guest/incognito/anonymous? I think I've read the three in different places, and I feel we should unify that concept @Betree

**Comment by Betree** [comment]
> Question: What's the difference (If there is any) of guest/incognito/anonymous? I think I've read the three in different places, and I feel we should unify that concept @Betree

From the technical point of view:
- **Guest**: someone who contributes without signing up. In our system, they're considered guests until they confirm their account (by sign-in).
- **Incognito**: the contribution is not linked to the normal profile, but rather to an "incognito" profile. The advantage here is that you can selectively put some contributions on your incognito profile without affecting others.
- **Anonymous**: this concept is not surfaced anymore. In the past (before the new contribution flow), it was used when people contributed without providing a name (basically, "anonymous" the default name for users).

With these definitions in mind, the main challenge with the proposed design is the following use case:
1. Contribute as a guest to "Collective A", leave the name blank
2. Contribute with the same email address as a guest to "Collective B", put your name in "Display name"
3. Now, since your name is linked to your profile, your contribution to collective A will now appear with the name you've set when contributing to "Collective B"

That was the nice part with the incognito checkbox: regardless of what you put in there, we mark the contribution as "Incognito" and therefore we can guarantee that it will always stay incognito, regardless of how you later edit your profile.

That being said, I like this new design. By having a mandatory (but private) "Legal name", and making a clear distinction with the "Display name", we're introducing a new paradigm that - I think - will be clearer than the "Incognito" concept. I don't think the issue above is something major, and https://github.com/opencollective/opencollective/issues/4550 would be a way to solve the problematic cases.

**Comment by Betree** [comment]
Solved by not requiring a name + having a private legal name. We acknowledge that it is not possible to use the "Incognito" feature for guests at the moment, but they have a workaround to keep their contributions private.
