### ISSUE TITLE
Add a "monthly" goals option for Collective owners

### ISSUE THREAD

**Issue by CaptainStack** [opencollective/opencollective#4596]
## User story 
As a Collective creator/manager, I can set a monthly contribution goal

## Best solution for this problem
In the dropdown on the "goals" section of my Collective dashboard, there should be a "monthly" option alongside "yearly" and "balance"

## MVP
I am not personally at this time committing to building or submitting an MVP, this is a feature request. However, an MVP would likely be very simple, the feature would work very similarly to the "yearly" goal feature, it would just break funds down by month instead. There should be a dropdown in the goal type menu and the rest of the visualizations and widgets should work the same as the existing features. Most Patreon goals are based on monthly donations and I think this should be an option on Open Collective as well.

## Metrics 
Not really a metrics driven feature but you could measure adoption and see how many creators choose to break their goals down by month versus yearly and balance.

## Documentation 
Any docs and tutorials that explain how to create and manage goals should be updated to reflect that "monthly" is an option.

**Comment by Betree** [comment]
Just to make it clear since we also have tier goals, this issue is about **collective goals**:

![image](https://user-images.githubusercontent.com/1556356/131498702-f2e77c3a-9611-4483-9b2f-c2fedec9cc3b.png)

**Comment by ofTheo** [comment]
Huge +1 for this. 

We have monthly costs and would love to show how close we are to reaching the goal for monthly contributors, that cover our monthly overhead. 

It also looks more attainable to show "only $200 more to meet the monthly goal" than only $2400 more to meet the yearly goal.

**Comment by Betree** [comment]
Looks like this issue was duplicated in https://github.com/opencollective/opencollective/issues/4803 and resolved in https://github.com/opencollective/opencollective-frontend/pull/7154

![image](https://user-images.githubusercontent.com/1556356/168531395-4e6e3e26-d64b-4a00-8874-c356a2cf3751.png)
