### ISSUE TITLE
Host page duplication load issue 

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#4598]
**Describe the bug**
When on the host page when you press load more there are duplicate hosts that appear. - https://opencollective.com/hosts

**To Reproduce**
1. Go to https://opencollective.com/hosts
2. Click on load more 

**Expected behavior**
Would expect no duplicates 

**Screenshots**
1 added 

**Desktop (please complete the following information):**
 - MacOS Monterey
 - Brave
 - Version 1.28.106 Chromium: 92.0.4515.159 (Official Build) (x86_64)
<img width="964" alt="Screen Shot 2021-08-30 at 6 12 12 PM" src="https://user-images.githubusercontent.com/79115149/131294113-0c0d87b7-9dd4-49e3-828a-8c50a69c7d9c.png">

**Comment by Betree** [comment]
Good catch, it looks like `orderBy` has no default value for the `allHosts` query. We should make it non-nullable and default to the number of collectives descending.

**Comment by Betree** [comment]
I don't know if it's related or not, but sorting doesn't seem to do its job properly; hosts are supposed to be ordered by the number of collectives hosted descending:

![image](https://user-images.githubusercontent.com/1556356/131297616-17193ffb-881d-4d76-9e43-1acc1c3f2fdc.png)

**Comment by shannondwray** [comment]
This issue is also occurring on the collective page :) https://opencollective.com/discover let me know if I should create another issue :)

**Comment by Betree** [comment]
@shannondwray Thanks! I've opened https://github.com/opencollective/opencollective-api/pull/6520 to solve both issues.
