### ISSUE TITLE
send email with collectives' donations/expenses to their host

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#46]
We should let hosts know on a regular basis when their collectives are receiving donations to make their management easier and more efficient. I suggest hosts can opt-in between every activity/daily digest/weekly digest. I wouldn't offer monthly since they get the monthly email anyway.

**Comment by xdamman** [comment]
It's already happening for a host. But not for the members of the collectives. Is that what you meant?

**Comment by piamancini** [comment]
My mistake. No I don't think we should send that to members unless they specifically opt-in. Spam risk is too big. Closing this.
