### ISSUE TITLE
add goals that help explain the why and how contributions will be used

### ISSUE THREAD

**Issue by ghuntley** [opencollective/opencollective#460]
Example implementation over at:

![image](https://user-images.githubusercontent.com/127353/31312649-88549944-ac14-11e7-9241-050ae817ac81.png)

This screenshot was taken from https://www.patreon.com/godotengine

Right now over at https://opencollective.com/reactiveui I'm inlining this information

![image](https://user-images.githubusercontent.com/127353/31312657-bbfc945e-ac14-11e7-9a22-c457cd49892b.png)

**Comment by xdamman** [comment]
Yes yes and yes.

As a MVP of that I'd just want to add different milestones for the yearly budget.
Eg. at 20k/year: we will have one part time developer, at 50k, we'll have a full time, etc.

/cc @cuiki

**Comment by ghuntley** [comment]
> As a MVP of that I'd just want to add different milestones for the yearly budget.

That works for us!

**Comment by piamancini** [comment]
Closing this and adding it to a post V2 fixes list.
