### ISSUE TITLE
Wise balance showing EUR when currency is NZD

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4604]
https://opencollective.com/protozoa/dashboard

<img width="1025" alt="Screen Shot 2021-08-31 at 2 09 59 PM" src="https://user-images.githubusercontent.com/5498878/131430338-f530fd77-f19c-48f8-8e84-e0a5dd808d3e.png">

**Comment by Betree** [comment]
Looks like this has been fixed

![image](https://github.com/opencollective/opencollective/assets/1556356/1891b95c-cb05-4ca1-a2cb-674baac99d35)
