### ISSUE TITLE
Create email address for automatic invoice submissions

### ISSUE THREAD

**Issue by ninavizz** [opencollective/opencollective#4609]
## User story 
As a paid contributor to an OpenCollective project, I would like a workflow for invoicing that aligns with the rest of my customers, so that invoicing my OC customers can take less time and be less annoying. 

Currently, most of my customers have a specific email address for their billing system's intake, that they send to their vendors plug-in to their invoicing software. Tagged fields in the email body can also map to filled-out form fields on today's form. 

TL;DR, it's a pain for me as a contributor to have to effectively do two separate workflows, to file an invoice for my one client who's an OpenCollective project. First step, on my invoicing software; and second, uploading it to my customer's OpenCollective profile on the website.

Nope, do not need any fancy callback features to tell my invoicing software (Harvest) you've paid me or anything.

## Best solution for this problem
A simple email address that projects can send to contributors, for us to plug-into our invoicing software as a "Send to:" customer email address. Bill.com does this, and its terrific.

## MVP
_What will be built as an MVP? (Please refer to our [wiki](https://github.com/opencollective/opencollective/wiki/Feature-Spec-Template) for what's acceptable as an MVP.)_
I am a freelancer.
My customer sends me an email address.
I plug that email address into my invoicing software so that when I "send" my invoice, it automagically uploads everything to the Open Collective form and I no longer have to endure that step on my own.

## Metrics 
?! I'm a UX contributor. I'm offering my feedback that this would be a beneficial feature that will save me time-on-task in my invoicing. Time on task for other people who submit invoices to OC, I guess.

## Documentation 
I'm not a developer. Look at how bill.com does it?

**Comment by Betree** [comment]
This looks like a duplicate for https://github.com/opencollective/opencollective/issues/1862. Thank you for clearly documenting your use case, this is super valuable.

Ping @alanna @piamancini, since you have some experience with other accounting softwares.
