### ISSUE TITLE
Projects and Events can have their own different admins

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4611]
## User story 
As a Collective admin, I want to empower leaders of Projects and Events without needing to add them as admins over the whole Collective.

As an Event or Project organizer, I want to be able to edit the page settings, send updates, and approve expenses.

## Best solution for this problem
A team section within the settings for each Project or Event where you can add people different to the overall Collective admins. When creating an Event or Project, you should be able to define its admins (select admins of the parent and/or invite other people).

## MVP
To make it simpler, don't add the bit about setting admins during creation and default to inheriting the parent Collective admins, but then still have a team section in settings where you can edit these.

## Notes
People are really responding to the Projects feature (and Events as well) and this is creating demand for more fine-grained control over permissions. I have received multiple requests for this from users, and find myself explaining workarounds a lot in support because we don't have this feature. 

The workaround isn't really a workaround: "The parent Collective admins will be the admins so just have the Project lead email you every time an expense is approved". Messy.

To implement this feature, we will need to ensure new sub-Collective admins also tick a box agreeing to the Host terms. As this is already the case for adding new parent Collective admins, that should be straightforward.

New Projects and Events should only be able to be created by the parent Collective admin, and being invited as a sub-Collective admin should not enable you to create further sub-Collectives or have admin access to the parent.

**Comment by Betree** [comment]
This is how things were initially done, the ability to edit event members was removed to simplify the feature.

Ping @znarf

**Comment by znarf** [comment]
It was a bit messier back then, Collective admins were initially **copied**. And from then were Event admins managed independently and never re-synchronized.

I'm happy to reintegrate **additional** admins for Events/Projects, if we all agree that parent Collective admins will keep full admin rights on Events/Projects all the way.

**Comment by alanna** [comment]
If it's easy to switch back on different *additional* admins, then let's go with that. We can dig into the question about completely different admins later.

**Comment by Betree** [comment]
Let's not forget about https://github.com/opencollective/opencollective-api/pull/7006/files/73d57e943352646636a16a4111cc75edc8289db9#diff-66cf8382a3802288c48c1dd40b91f465d8fee23a9acf3488bb1b319d897f635e when we'll tackle this one

**Comment by simonv3** [comment]
Just going to bump this as something that would be incredibly helpful to a group and project I'm working on. We're organizing an event for which we want to set up a project with specific funding for that event. But the people organizing the event/project shouldn't have access to the parent organization simply because the parent organization has specific processes in place. Right now we're going to be working around this by getting admin from the parent org approving and doing the changes we need, but it's more work on people who are already doing a bunch of the work. This would be incredibly useful.

**Comment by aomuse** [comment]
Also going to bump this issue as I did not realize it had been changed since I started using the feature and it is one of my main selling points to new collectives about the benefits of using the Projects feature to build trust and onboard new people who can manage specific projects with limited budgets within a larger collective. We need this one back to help facilitate those trust relationships within collectives.

**Comment by alanna** [comment]
@aomuse this feature never was in place so it's not about getting it "back". Projects and Events have always inherited the admins of the parent Collective. If you'd like to creating things with different admins now, make them separate Collectives and we can make them Connected Collectives. But we would really like to build a feature for separate sub-Collective admins, which is what this issue is about. I hope we can soon.

**Comment by aomuse** [comment]
Okay. I must have imagined that feature then. I seem to have such a lucid memory of using that it is the only reason I keep talking to everyone about the Projects feature. Strange. Then I would endorse the ability to add additional admins to Projects and Events since this is a distinct need Collectives have expressed.

**Comment by RCheesley** [comment]
+1 for this.

> Use case is we want to empower our LATAM community to manage the funds in a project which will result from a large conference they are organising, but they should only be able to approve expenses in that specific project (and also in the OC event for the conference), not anywhere else

**Comment by alanna** [comment]
Another +1 to this as the Australian host I've been supporting needs it as well

**Comment by aomuse** [comment]
Not at design phase yet, but I am imagining of inheritance as a tickable option on Projects and Events. That way people have the option of deactivating inheritance for specific sub-collectives. Adding that suggestion so I don't forget it when the issue makes its way up the list.

**Comment by RCheesley** [comment]
Yes - what I was expecting to see was some way of saying the team member is:

- Global admin of all the things
- Limited admin with options
    - Can manage all projects
    - Can manage all events
    - Can manage these specific projects (or not manage these specific projects)
    - Can manage these specific events (or not manage these specific events)
- Financial bod (can export transactions and the like but no management access etc)
- Marketing bod (can write draft updates but not publish them)

**Comment by kewitz** [comment]
Implementation Goals:

- [ ] Make sure admin inheritance is purely virtual between parent and children collectives
  - [ ] Write migration to remove ADMIN memberships from children collectives
- [ ] Display the complete TEAM page on Events and Projects
  - [ ] This page allows admins to be created and deleted in this specific project
  - [ ] This page also displays the parent collective admins and does not allow the user to edit.

**Comment by BenJam** [comment]
- [ ] @kewitz tackling this this week ✌️

**Comment by BenJam** [comment]
- [ ] couple of issues with the demo to rectify this week

**Comment by shannondwray** [comment]
Can we add some more information to the Team about about how this works? It currently only shows what the different roles are and nothing about how these admins are just for the project/event?
