### ISSUE TITLE
Stripe Payments Rejected: Indian based Merchants

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4612]
This is with regard to the Freshdesk ticket: https://opencollective.freshdesk.com/a/tickets/32659

It seems that trying to make a payment with an Indian based card gets rejected with the following error on Stripe; 

>It appears that you are creating a token using a Customer object that contains a card payment source to be shared with a IN-based connected account. As part of our continued investment in India and to meet local data storage requirements, we no longer allow cloning card payment source into or out of India, so we had to reject your request. For more information, please visit [https://stripe.com/india-data-storage-faq](https://stripe.com/india-data-storage-faq)

We need to investigate more on this and potentially support these cards. 🤔

**Comment by SudharakaP** [comment]
ping @znarf : Not sure if we should investigate more or prioritize this.

**Comment by znarf** [comment]
It's a complex one. Let's just answer this to Fiscal Hosts and Independent Collectives based in India. 

And send them to other Fiscal Hosts like OSC if they want to accept credit card payments.

**Comment by SudharakaP** [comment]
> > It seems that trying to make a payment with an Indian based card
> 
> @SudharakaP Here you don't seem to get it right, the credit card doesn't matter, it's the Stripe account being based in India.
> 
> Let's just answer this to Fiscal Hosts and Independent Collectives based in India that it's not working for them at the moment due to a Stripe limitation with our setup.
> 
> And send them to other Fiscal Hosts like OSC if they want to accept credit card payments.

Thanks for the explanation. I've updated them about this.
