### ISSUE TITLE
[FIX] Update notification banner design

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#4613]
Can we update the notification banner so we reduce the vertical space?

| Current | Desired |
|---------|---------|
|   ![image](https://user-images.githubusercontent.com/12435965/126227021-f6c9599c-e6e1-4a0c-ad5b-34ce0c39ab44.png)   |   <img width="1438" alt="Screen Shot on 2021-08-31 at 21-14-57" src="https://user-images.githubusercontent.com/49539954/131600722-547437ff-6d81-4a56-b8f8-ba9505d4e8f0.png">      |

[Design in figma
](https://www.figma.com/file/N4Xbl652BhzOutXmzhcrLGch/DS-02-Atoms?node-id=3455%3A3284)
cc @Betree

**Comment by Betree** [comment]
@Memo-Es With the first example, where should the `Send $xx to Collective` button live? Should we just change the vertical margins, or is the button meant to move as well?

**Comment by Memo-Es** [comment]
@Betree Reference:

<img width="1539" alt="Screen Shot on 2021-09-03 at 10-44-55" src="https://user-images.githubusercontent.com/49539954/132032635-cd731482-99b3-49a1-9648-431cf4690c55.png">

**Comment by Betree** [comment]
@Memo-Es Should the banner be fixed like that? It's hiding part of the avatar + the buttons to edit the hero image, yet there doesn't seem to be a way to close it.

**Comment by Memo-Es** [comment]
Closing this since it's been tracked in https://github.com/opencollective/opencollective/issues/4681
