### ISSUE TITLE
Create Collective "close" icon is not properly aligned

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4614]
<img width="693" alt="Screenshot 2021-09-01 at 14 30 45" src="https://user-images.githubusercontent.com/806/131671411-586def9a-6bf6-4e0e-b9aa-4b1ae9814387.png">

**Comment by SudharakaP** [comment]
This is introduced by https://github.com/opencollective/opencollective-frontend/pull/6704 where we changed the style/alignment of the modal close icon. This modal is a special case and I think we missed this one. Anyways, I've made a pull request to correct it. 🙂
