### ISSUE TITLE
Add the Currency Conversion and Payment Processor Fee for Crypto Flow

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4616]
This was taken from the following discussion; https://github.com/opencollective/opencollective-frontend/pull/6787#discussion_r700347283

For the initial design of the Crypto flow we had; 

![image](https://user-images.githubusercontent.com/12435965/131727097-7080e0e2-406e-4e00-bce6-fa5417943e6e.png)

Notice the currency conversion value in the `Contribution Summary` section. This was challenged later as the currency conversion value doesn't quite fit in the contribution summary. And therefore we removed it. However it would be useful to show this currency conversion value in the later sections (the profile and payment sections) in the contribution flow so that the user is informed on how much they are contributing in fiat. 

Although not a priority right now maybe we need to reiterate on the design of this so that we find a way to display this exchange amount. 😄 

We also need to add payment processor fees (an approximate amount) by the Giving Block to the contribution flow so that users know what amount will be used as contribution fees. Maybe we could add this information in the contribution summary. 🤔 

The payment processor fees is around 4.336% on the USD value (as per https://opencollective.slack.com/archives/C028A6H56BG/p1630672772004300) + the OSC 10% fee. 

Related Figma File: https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=13426%3A207907

**Comment by znarf** [comment]
To be fair, the version in the design is already a bit better than what was challenged in our review.

Something we also need is an approximation of the Payment Processor Fees, can you add this to the issue @SudharakaP ?

**Comment by SudharakaP** [comment]
> To be fair, the version in the design is already a bit better than what was challenged in our review.
> 
> Something we also need is an approximation of the Payment Processor Fees, can you add this to the issue @SudharakaP ?

Yes, I've changed the title and added the payment process fees to the description as well. We'll handle both in this issue. 👍🏽 

cc: @Memo-Es
