### ISSUE TITLE
Add Support to Contribute for Past Events - For non-Admin Users

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4617]
This is with regard to the following comment: https://github.com/opencollective/opencollective-frontend/pull/6797#pullrequestreview-744299588

Maybe we could remove the restriction for contributions to past events for non-admin users as well. This needs to be discussed with the team but the main proposal is as follows. 

- [ ] Remove the restriction for show the contribution section for past events for only admin users. So all users will be able to see the contribution section for past events. 
- [x] Make sure all users (admins and non-admins) do not see the tickets section for past events. 

Relate to https://github.com/opencollective/opencollective/issues/3982

cc: @opencollective/core

**Comment by SudharakaP** [comment]
@Betree : Thanks for the feedback. Yes, so we'll wait for a use case. Also note that with the [previous PR](https://github.com/opencollective/opencollective-frontend/pull/6797), admins can buy tickets of past events. If no objections I'll open a new PR correcting this as that doesn't make sense? 🤔

**Comment by Betree** [comment]
Sounds like we don't want this, as there is no use case for it. Feel free to re-open if I'm missing something.
