### ISSUE TITLE
Troubles to setup local dev database

### ISSUE THREAD

**Issue by OpenNtwk** [opencollective/opencollective#4618]
I'm trying to run the `opencollective-api` with `opencollective-frontend`
I've tried `db:setup` and `db:seed` but it seems there is still something missing in DB. Is there any DB dump with latest structure and some seed data?
the db:migrate doesn't seem to run either (but since sequelize sync has worked that shouldn't be big issue)

1.  `db:setup` 
2. `db:seed` 
3.  visit frontend
4.  see error screenshot
5.  signup
6. confirmation link doesn't work `Sign In failed: WHERE parameter "CollectiveId" has invalid "undefined" value.`

**Expected behavior**
working instructions to run the backend without having the db dump or the db dump with a seed

**Screenshots**

![image](https://user-images.githubusercontent.com/89942471/131740294-46cbdd85-0adc-42fb-bcc8-13169ea110c0.png)

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - v92

**Comment by SudharakaP** [comment]
@OpenNtwk : Which instructions did you follow? 

First you need to follow; https://github.com/opencollective/opencollective-frontend#readme for setting up the front-end. Make sure the correct environment variables are set as per, https://github.com/opencollective/opencollective-frontend#environment-variables

Then make sure to setup the API properly as per https://github.com/opencollective/opencollective-api#readme

For the DB setup follow, https://github.com/opencollective/opencollective-api/blob/main/docs/postgres.md. You don't need to run `db:setup` and `db:seed`. 

If you have further questions please feel free to ask them in our Slack channel; https://opencollective.slack.com/archives/C0RMV6F8C

**Comment by SudharakaP** [comment]
I am closing this issue since it seems that the question originally posted was answered. But please feel free to follow up on Slack if there's any further clarifications on this. 😄
