### ISSUE TITLE
markdown support in tier descriptions

### ISSUE THREAD

**Issue by ghuntley** [opencollective/opencollective#462]
Please add support for using markdown in the tier descriptions. Specifically after ability to use bulleted lists.

![image](https://user-images.githubusercontent.com/127353/31312666-23563b1e-ac15-11e7-8504-882e023c3a6f.png)

**Comment by xdamman** [comment]
I'd love to keep the description short and clean (e.g. for sharing on social media).
But we should add a longDescription  with Markdown support. Related: https://github.com/opencollective/opencollective/issues/463#issuecomment-335010275
