### ISSUE TITLE
Button to reset the expense form

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4625]
Some people sometimes get stuck on the expense form. Can be because of a bug, or a misunderstanding. Anyway, it would be great for them to have a "Reset" button that would clear the form and remove the draft saved in `localStorage`. We should make sure to show a confirmation before triggering the reset, to prevent misclicks. 

@Memo-Es Could you suggest a position for such a button?

![image](https://user-images.githubusercontent.com/1556356/131971647-98eb48b9-94e2-447f-9d0a-b4e1bd93ed2e.png)

**Comment by aminakazi** [comment]
Link to the [Production File](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/[OC-Design]-Production-Ready-✅?node-id=14374%3A177551)

<img width="1280" alt="Reset Form Text Link" src="https://user-images.githubusercontent.com/48468919/135079230-8c116b89-b69f-40cc-a663-994cc200b0d9.png">

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $300 when the Pull Request is reviewed, accepted, and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by snitin315** [comment]
@Betree there are two different amounts in the comment above.

**Comment by Betree** [comment]
:trophy: This issue has been completed by @snitin315  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
