### ISSUE TITLE
varying(255) is wrong datatype for tier description. Need to be able to store more text.

### ISSUE THREAD

**Issue by ghuntley** [opencollective/opencollective#463]
![image](https://user-images.githubusercontent.com/127353/31312669-4ddc89b0-ac15-11e7-988b-bb89731c77ba.png)

**Comment by xdamman** [comment]
I'd love to keep the description short but we could add a `longDescription` that would support markdown (and have a dedicated page per tier). Thanks for the feedback!

**Comment by ghuntley** [comment]
The user pain is "how do I express that this tier contains everything of the previous tiers in 255 chars" whilst having enough left over room to express that tiers benefits

**Comment by xdamman** [comment]
Ok ok. Let’s double this :-)

**Comment by ghuntley** [comment]
🚢

**Comment by xdamman** [comment]
This fixes it https://github.com/opencollective/opencollective-api/pull/936
Deploying now.
