### ISSUE TITLE
Support Metrics Report August 2021

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#4637]
### Support Metrics Report August 2021

This report looks at the trends around support to help us better understand areas we need to improve and highlight key topics for the month. Please note that this month we are experimenting with a different view so we may lack some of the comparative figures. Would love to receive some feedback to know if this type of presentation is more useful for making more significant improvements and having a better opportunity to learn as we move forward. 

**Tickets received** 

![capture](https://user-images.githubusercontent.com/57156267/132141487-040fb671-40da-481f-ba79-4a7a7394c8cf.png)

The number of tickets received seems to be quite consistent - 1610 in July to 1659 in August. By removing blank tickets and expenses notifications where no action was required the rise during August was a little lower (by 9%) with 585 tickets compared to 646 in July. [You can find the working files here. ](https://docs.google.com/spreadsheets/d/1pO6FQzpxUXpBms43J94rxhX4toU2IP3S/edit#gid=1455913751)

Following the latest meeting we had on the topic, I was curious to see what the ticket distribution between agents looks like and this is what it comes to:

![capture](https://user-images.githubusercontent.com/57156267/132141524-78e070b0-6461-4119-97b7-4f0c2ee224d6.png)

One thing to note from looking at the tickets is in some instances there are a lacking of tags assigned and so I wonder whether this may be the case where we were missing information and followed up with the users or whether it may be worthwhile flagging the importance of tagging tickets to ensure we capture the types of questions we get. 

[I included a short video here](https://www.loom.com/share/675ab2b9c98f4f838b8966f01ed3033d) to highlight this element and ensure we capture some of the basic functionality available on FreshDesks as well as the changes in this report format

**Trends and Recommendations**
After removing irrelevant tickets, we had 585 that required support attention. Here is the summary of the common areas of questions - please note I took out the Expenses and Onboarding topics as these are addressed separately and would make a large portion of the questions we handle.

![capture](https://user-images.githubusercontent.com/57156267/132141619-4cab370c-05ce-41ee-8b95-db0c4e67f236.png)

Below are some notes on these trends:

**Grants/Contributions**

Requests for support for initiatives through external grants applications keep on being in the lead of tickets we receive (this is with the focus on OCF). I would like to note that over the past few months, and specifically during August, we see an increase in larger amounts flowing in which is fantastic as it both represents an incredible growth in the area of impact our initiatives can create as well as an increase in the host fees we collect on. While in July we received a large grant from Ford Foundation for DI, this month included large contributions received for some of our other initiatives. 

**Virtual cards**

Requests for virtual cards are still received at a stable rate. This month, however, we also had to deal with some issues with restrictions on our accounts (for both OCF and OSC) enforced by Privacy. What began with a questionable transaction passed by one of our group (someone made a payment in a site called PAYSEND which is not allowed apparently) has led to an ongoing conversation with Privacy led by Benjam and Pia. Looks like it still awaits final resolution. 

**Lost/project support**

One type of questions we receive a lot of, on a consistent basis, relates to users reaching out to us directly with a question related specifically to a specific initiative. This is probably something we could improve and help navigate people to the correct contact details with a few tweaks on the platform end. Normally these types of questions will also arrive with very little details (often hardly any information of the initiative is included at all) which means there will be quite back and forth with the user trying to understand which way they should be directed. 

**Expenses and Onboarding**

It seems like it would make sense to aggregate these categories into a separate section to look at some of the trends we can witness. Below is a more detailed description. 

**Expenses**

It seems like the process around expenses works relatively well and we see a reduced number of tickets on the process of submitting expenses, ad, in general, users are able to understand the process fairly easier. As work is currently taking place on the redesign of our contact page with a better link to our documentation section, this visibility of the expenses is something that is likely to reduce the load on support. The common issues we see now include the following:

- Users sometimes struggle with editing their claims and can opt to submit an expense from scratch. This is mostly applicable for instances where users need to adjust their payout details but is also showing when other changes need to be made. So that visibility of the edit functions is something we should look at, specifically from the mobile users' perspective. 
- Instances where expenses are submitted by users as individuals, instead of creating a company profile from the get-go.
- Occasionally, the definitions of Invoices/Reimbursements will cause some confusion with expenses being classified in the incorrect expense type.

In addition to these, areas of struggle will include issues with payout methods. This past month we encountered many instances where users opting for PayPal payment nominate an account before completing the authorization process with PayPal, which creates a delay at the time of payment and an additional need for us to support these changes. 

And then there are these things worth noting:

- Restrictions with payments to _India/Africa_ resulted in some instances where Payoneer accounts were created. This is great but caused some confusion on the support end. What we need to pay attention to is that while the address in the expense form (under Payout Method) will be the local address of the user (e.g. India) the account format would be one for US - ABA rather than IFSC used for local transfers to India
- Payments to _Japan_ - while we don’t have many of those, whenever they occur they are difficult to deal with. One thing identified is that our form doesn’t specify the language used for account holder name, and it seems like it matters and the account holder name should be matching exactly to the account name in their local bank (same thing we have for transfers to Russia, for example). It looks like right now, users can enter the account name in English and that causes some issues. 

**Onboarding**

Onboarding related questions are still some of the common ones we receive. There is a 34% decrease in the number of new initiatives joining OCF and the trend for OSC is pretty steady in comparison to last month. Here is how it was distributed:

We approved 25 new applications for OCF in August compared with 38 in July.

For OSC -  77 new collectives were approved this month compared to 80 in July.

**Comment by alanna** [comment]
Thanks @alinamanko !

> One type of questions we receive a lot of, on a consistent basis, relates to users reaching out to us directly with a question related specifically to a specific initiative. This is probably something we could improve and help navigate people to the correct contact details with a few tweaks on the platform end

Would it be worth asking these people how they ended up contacting us? That would help figure out where they are getting confused.

> there will be quite back and forth with the user trying to understand which way they should be directed

Can we just have a canned response for these and not get involved in back and forth at all? It sounds harsh but I'll support simply not responding if it's taking a lot of time. These support requests aren't our responsibility.

> visibility of the edit functions is something we should look at, specifically from the mobile users' perspective

We've gotten constant feedback since the design was released that having the edit/download/delete buttons on the upper left side is confusing. This doesn't match patterns in most other software and we should rethink it.

> Instances where expenses are submitted by users as individuals, instead of creating a company profile from the get-go.

The real solution to this is #3340 - I hope we can take that on soon. We're working on #3689 which is the precursor.

> This past month we encountered many instances where users opting for PayPal payment nominate an account before completing the authorization process with PayPal, which creates a delay at the time of payment and an additional need for us to support these changes.

Any way to check authorization at the time an expense is submitted or approved @kewitz ?

**Comment by alanna** [comment]
> Restrictions with payments to India/Africa resulted in some instances where Payoneer accounts were created. This is great but caused some confusion on the support end. What we need to pay attention to is that while the address in the expense form (under Payout Method) will be the local address of the user (e.g. India) the account format would be one for US - ABA rather than IFSC used for local transfers to India

@kewitz is there a way to structure the data input to improve this?

**Comment by Betree** [comment]
Thanks @alinamanko :rocket: 

> ![image](https://user-images.githubusercontent.com/1556356/132824180-6fa98544-b747-400c-84be-bc9211df3918.png)

Great to see this graph!

**Comment by kewitz** [comment]
> > This past month we encountered many instances where users opting for PayPal payment nominate an account before completing the authorization process with PayPal, which creates a delay at the time of payment and an additional need for us to support these changes.

> Any way to check authorization at the time an expense is submitted or approved @kewitz ?

@alanna I'm not very familiar with PayPal's API but this may be possible to implement in a way or another.
I don't think PayPal's API will allow us to check if an e-mail is signed up to their platform, that would be a huge privacy issue. We could replace the PayPal email field with a button to sign up with PayPal tho.

> > Restrictions with payments to India/Africa resulted in some instances where Payoneer accounts were created. This is great but caused some confusion on the support end. What we need to pay attention to is that while the address in the expense form (under Payout Method) will be the local address of the user (e.g. India) the account format would be one for US - ABA rather than IFSC used for local transfers to India

> @kewitz is there a way to structure the data input to improve this?

I don't think this is of our concern. To put it simply, users are using Payoneer to bypass a Wise limitation on their side and I'm not sure about the legality of all this.
I think that if users are requesting Payoneer and OSC and OCF have or are interested in accepting Payoneer, we could test adoption by adding a payout method accepting user's Payoneer email (something in the way we do for PayPal). These would have to be paid manually for now but after checking adoption we could move forward and write an integration.

**Comment by piamancini** [comment]
> > visibility of the edit functions is something we should look at, specifically from the mobile users' perspective

> 
> We've gotten constant feedback since the design was released that having the edit/download/delete buttons on the upper left side is confusing. This doesn't match patterns in most other software and we should rethink it.

@Memo-Es Can we have a quick go at how an alternative placement of the editing / deleting buttons would look like?

**Comment by alanna** [comment]
Now that we have a good pattern for an actions drop-down maybe we should
use it for these expense functions too.

**Comment by Betree** [comment]
I'm not sure if whether we're referring to the expenses list or the expense page here, but we recently updated the pattern in expenses list to use dropdowns when the status is `REJECTED` or `PAID`:

![image](https://user-images.githubusercontent.com/1556356/133211315-44aa7f04-903b-4acb-ba00-1a8ea2e0745a.png)

**Comment by znarf** [comment]
Should be straight forward to add Delete there @Betree ? For Edit this is slightly more complicated as we don't have the contextual menu out of `REJECTED` and `PAID`.

**Comment by Betree** [comment]
> Should be straight forward to add Delete there @Betree ? For Edit this is slightly more complicated as we don't have the contextual menu out of `REJECTED` and `PAID`.

Yes, I actually have most of it implemented in https://github.com/opencollective/opencollective-frontend/pull/6813. I paused the work to focus on other priorities, but it's still on my plate.
