### ISSUE TITLE
3rd party use cases for consumption of your API and documentation requests

### ISSUE THREAD

**Issue by ghuntley** [opencollective/opencollective#464]
Howdy folks;

I'll have a few use cases for consuming your API in the immediate future.

a) automatically export backer email addresses into our projects marketing CRM (ActiveCampaign)
b) automatically do things when someone donates for the first time (via Zapier integration please)
c) when viewing a github issue (or pull-request) determine if someone is a financial supporter of the open-source project and display indicators to the maintainers as such. This enables scenarios such as 

![image](https://user-images.githubusercontent.com/127353/31312694-eb574482-ac15-11e7-8364-1fadcc9f24a2.png)

Thoughts? Please leverage something like https://zapier.com/developer/builder/ as writing glue code between opencollective and other services (such as twitter/github) to automate things is not compelling (time setting up and maintaining it would be best spent on maintaining the open-source project)

**Comment by xdamman** [comment]
a) I fixed the API. See the wiki: https://github.com/opencollective/opencollective/wiki/API#get-list-of-collective-users-and-their-emails
b) yes we should totally support that. I'll look into Zapier.
c) would love to see that happening. We should ask people to connect their GitHub account to their backer account on open collective to support that. But imagine we have a simple call to verify the status of a GitHub user, what would you do on Github side?

**Comment by piamancini** [comment]
c) I have an ongoing convo with Nadia @ Github about badges for users. This can be a nice step towards it.

**Comment by ghuntley** [comment]
I was thinking of writing a chrome plugin that queried the OC API when viewing GitHub issues. Would love to have features like this inlined into GitHub.

**Comment by ghuntley** [comment]
https://www.theverge.com/2017/10/25/16525586/patreon-api-app-directory-wordpress-zapier-slack-discourse

> That includes a connection with automation service Zapier, which lets creators do things like instantly add new patrons to mailing lists.

This this this this 🚢

**Comment by xdamman** [comment]
Any #hacktober contributor experienced with Zapier that would love to take on this?

**Comment by patcon** [comment]
> c) when viewing a github issue (or pull-request) determine if someone is a financial supporter of the open-source project and display indicators to the maintainers as such. This enables scenarios such as

Someone could create a probot plugin for this: https://probot.github.io/

(It's an officially-unofficial github project, as far as a I can tell -- no big launch yet, but employees working on it.)

could prob do it by creating a small heroku app that uses [this method to find emails](https://www.sourcecon.com/how-to-find-almost-any-github-users-email-address/) [(sample)](https://api.github.com/users/patcon/events/public), then matching against some opencollective api endpoint that perhaps Boolean checks whether an email represents a backer of a project? (This would require a new endpoint, and I haven't thought through whether that endpoint would be open up new security/privacy concerns...)

**Comment by ghuntley** [comment]
Zapier and probot are the two most compelling use cases at the moment.

Personally I would use both as follows

a) probot used to automatically triage GitHub issues and add labels ("flare") to signify that someone is a financial sponsor.
b) Zapier to automatically add rows to a Google spreadsheet, publish tweets on Twitter, announce in Slack, send a personalized thank-you email.

**Comment by znarf** [comment]
Let's review the use cases and make sure it's covered in upcoming API.

**Comment by znarf** [comment]
I could not figure a clear expectation on how to move that issue forward.

Let's extract clear issues out of this and close it.

**Comment by patcon** [comment]
GitHub Actions beta is on. They're looking for people doing interesting things. Someone with OC could prob submit on behalf of the GitHub org, then tweet to bump up in the queue. Details:

https://blog.github.com/2018-10-17-action-demos/

**Comment by nemchik** [comment]
I wanted to express that I'm still interested in seeing this (since stale bot has tagged it). I unfortunately don't think I'm up to adding this feature myself.

**Comment by znarf** [comment]
@nemchik there are multiple things mentioned here, what are you specifically interested in?

**Comment by nemchik** [comment]
B and C from the original post. For B it'd be nice if it were more than just over event that could trigger some kind of action.

**Comment by znarf** [comment]
b) is being worked on, will be ready in a few days / weeks (let's stay in touch to try it first!)
c) might be solved by the https://github.com/opencollective/opencollective-bot

**Comment by nemchik** [comment]
Thanks!

I've subscribed to the issues related to B. I had the bot setup on GitHub with permissions to my repo but did not make the yml file needed. I'm going to commit that now and see how it goes. If i have any trouble I'll open an issue on that repo for support.

**Comment by znarf** [comment]
The configuration of the Open Collective Bot should be easier in the future with https://github.com/opencollective/opencollective/issues/1876

**Comment by znarf** [comment]
I'm closing this issue. Some of the feature requests are covered by the Open Collective Bot and the Open Collective Zapier integration.

If something is not covered by that or if you want something more specific, please create a new issue!
