### ISSUE TITLE
Add label to archived Projects

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4641]
When a Project has been archived, it should get an `archived` label, similar to how past Events get a `past event` label. This is to make their status more clear.

<img width="1248" alt="Screen Shot 2021-09-07 at 5 12 50 PM" src="https://user-images.githubusercontent.com/5498878/132288102-016b0486-d66b-4197-8209-b3378be77c85.png">

<img width="628" alt="Screen Shot 2021-09-07 at 5 15 22 PM 1" src="https://user-images.githubusercontent.com/5498878/132288114-f972f43c-d111-4ee4-8381-5fea6caa60df.png">

**Comment by saideepesh000** [comment]
Hi @alanna , so the second project on the first pic is archived, am I right ?

**Comment by alanna** [comment]
yes correct, the gray one
