### ISSUE TITLE
provide way for collective to override the seo/socialmedia metadata

### ISSUE THREAD

**Issue by ghuntley** [opencollective/opencollective#465]
![image](https://user-images.githubusercontent.com/127353/31312728-c91daa7c-ac16-11e7-9e64-2b913e0d0b26.png)

The content on the collective (see https://opencollective.com/reactiveui) page for desktop/mobile is not the best content to be displayed in seo/social media situations. For example I'm planning on putting together a image+video embed at the top but am putting this off as the markdown code would in theory flow through into Slack or appear on Google.

**Comment by xdamman** [comment]
The right way to implement this is to allow you to post updates on your collective page (and have a unique page/URL per post that you can share on social media). We'll get there.

**Comment by ghuntley** [comment]
re: posting updates on our collective page

Our project already has a blog and my preference is to concentrate all activities/updates/communication to take place on the website as that provides the maintains insights of who in the community is engaged and where ReactiveUI is being used. 

Have also considered hiding backer updates unless please login with OpenCollective/GitHub account [some form of primary identifier]:

![image](https://user-images.githubusercontent.com/127353/31322351-ee53286e-ace1-11e7-83f5-0850b70ab0e3.png)
