### ISSUE TITLE
Set Projects order

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4650]
@znarf says 

> It’s not exactly random, but it’s undefined, whatever the database send. That can easily be tweaked.

Right now inactive or less important Projects can appear at the front and dominate that section of a Collective page (related: #4640 #4622).

I'm trying to think of the best option for setting Project order that is simple will also enable users to actively affect the order as a workaround.

* Order by most recent activity (transaction or update to settings/description, etc): Live Projects will be on top, but could lead to lots of jumping around of the order which would be confusing.
* Alphabetical: Would enable workarounds like adding `*` to the front so people could actively send one to the front, but that's ugly looking, and also alphabetical could default to less active projects at the top when people don't use a hack.
* By date created: Newest first would enable old projects to fall away, but some might want oldest, most established project first.
* By amount raised: The user asking for this actually wants the biggest budget Project at the end so I don't think it's a good solution.

After typing all that I think ordering by most recent activity is the best option.

**Comment by Betree** [comment]
`By date created` is the easiest to implement (one-line change, no additional data to fetch). It's also the most stable, and consistent with what we do for other parts of the interface (connected collectives, tiers, etc).

I would personally vote for this to be the default behavior, and focus on #4622 to give more options for admins to sort things as they want.

**Comment by znarf** [comment]
+1 for date created as quick fix, descending?

**Comment by alanna** [comment]
ok let's go for date created, with newest first

**Comment by znarf** [comment]
> ok let's go for date created, with newest first

That's done.

**Comment by alanna** [comment]
Ordering by date is an improvement but I still think we should enable custom ordering if possible.

**Comment by alanna** [comment]
Oh that's being tracked in #4622 so I'll close this
