### ISSUE TITLE
Do not ask for legal name when inviting user

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4652]
Legal name should be set by the user themselves, not the inviter.

![Screen Shot 2021-09-09 at 10 33 50 AM](https://user-images.githubusercontent.com/5498878/132595143-c157824f-6ef4-46c3-982b-6d0d0a452e18.png)

**Comment by Betree** [comment]
@alanna We should keep the field for organizations, right?

**Comment by alanna** [comment]
@Betree we can't invite organizations though? Do you mean create organization?

**Comment by Betree** [comment]
Yes, this component is also used when you create an organization inline (eg. In the add funds modal)

**Comment by alanna** [comment]
I think we should keep legal name for creating orgs when adding funds, as
that is not inviting a profile but directly creating it.
