### ISSUE TITLE
Legal name placeholder should match profile type

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4653]
![Screen Shot 2021-09-09 at 10 33 50 AM](https://user-images.githubusercontent.com/5498878/132595183-d6d560ed-c7b9-4b98-819b-a19173484d9a.png)

This is misleading - we're creating an individual profile but the help text says "eg. Open Collective Inc".

If it's an individual the help text should be a person's name, like "Maria Garcia"

If it's an organization, it should be a company name as above, e.g. "Open Collective Inc"

Our individual/organizational profile creating flow confuses users a lot already so let's make sure this is handled carefully.

**Comment by Merian0818** [comment]
Label
