### ISSUE TITLE
Clarify legal name is optional

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4654]
![Screen Shot 2021-09-09 at 10 45 47 AM](https://user-images.githubusercontent.com/5498878/132595609-0b4a0196-c1f6-4d8c-a369-74d32c1a98c2.png)

It's not clear from this that the legal name is optional, and only needed if different than your display name.

**Comment by Merian0818** [comment]
Legal name is Ur family name

**Comment by Betree** [comment]
Ping @opencollective/design

**Comment by alanna** [comment]
I already fixed the help text so I've removed that aspect

**Comment by Memo-Es** [comment]
Updated in the [production-ready file in figma](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/[OC-Design]-Production-Ready-✅?node-id=13838%3A161523)

<img width="367" alt="Screen Shot on 2021-09-22 at 21-47-49" src="https://user-images.githubusercontent.com/49539954/134447989-60a9a1e2-0b23-43ab-8b27-fabe7236ade7.png">

**Comment by SudharakaP** [comment]
> I already fixed the help text so I've removed that aspect

@alanna : I am a bit confused on this. So for the help text currently we have this; 

![image](https://user-images.githubusercontent.com/12435965/135206946-2c45977e-7cb2-4c7a-9c96-1d10329c8812.png)

Do you mean that that is the correct one? The design shows, 

![image](https://user-images.githubusercontent.com/12435965/135207016-232788d8-6740-424b-bc08-a4863224d6d9.png)

**Comment by alanna** [comment]
The help text currently in production is correct.

**Comment by SudharakaP** [comment]
> The help text currently in production is correct.

Thanks for confirming. 👍🏽
