### ISSUE TITLE
Admin Dashboard Reports: Host Fees Section 

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4657]
Part of https://github.com/opencollective/opencollective/issues/4300

Design file: [Figma](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=13711%3A157088)

---

## Collapsed View

![image](https://user-images.githubusercontent.com/12435965/132704719-ecde473f-f794-4a60-9e07-e3595d600557.png)

- [x] Use the `HostMetrics` to display the amounts as shown in the above screenshot. 
- [x] Implement the filters to filter on the dates and the collectives; for the date filter for now we can use the period filter. There's some ongoing discussion on this at https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP?node-id=13711:161925#105081767

## Historical View

![image](https://user-images.githubusercontent.com/12435965/132705783-7813c143-de8b-414b-9bb4-227d26a9c09f.png)

- [x] When we click on the `See Historical` link the section should expand to show the chart.
- [x] Use the [Apex column chart](https://apexcharts.com/javascript-chart-demos/column-charts/) to show the historical view
- [x] On `HostMetrics` add a new `hostFeesCollectedProgress` field. 
  - [x] Args: `year` (required)
  - [x] Response: `[{ date, amount  }]`

**Comment by Betree** [comment]
I'm gonna look at the historical view for this one, the host fees query is a simple case for time series that will be great for experimenting.

**Comment by Betree** [comment]
Feedback from @znarf: maybe showing all host fee shares statuses (pending, invoice, settled) could be clearer.

**Comment by znarf** [comment]
<img width="622" alt="Screenshot 2021-09-10 at 15 16 56" src="https://user-images.githubusercontent.com/806/132859326-1048b6e7-df55-454f-b730-be2ac09f385d.png">

**Comment by Betree** [comment]
Feedback from https://opencollective.slack.com/archives/C020ZQSLM5M/p1631608242032800?thread_ts=1631547165.027900&cid=C020ZQSLM5M:

> 'profit' is also incorrect, it's revenue actually. If we are using host fees to many times we can call it revenue

**Comment by SudharakaP** [comment]
All the tasks for this issue seems to be done and therefore I am closing it.
