### ISSUE TITLE
Admin Dashboard Reports: Transactions View

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4658]
*Part of https://github.com/opencollective/opencollective/issues/4300

Design file: [Figma](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=13711%3A157088)

---

![image](https://user-images.githubusercontent.com/12435965/132716669-4bf708ba-4388-4c47-a023-1728d19a062b.png)

### Front-end

- [x] Add fixed CSS rules to display the contributions and expenses bar (for the MVP we will not use any charts but rather use fixed CSS rules and not add any percentage values; this is under discussion; https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP?node-id=13711:161925#107731426)
- [x] Add filter by date (use `PeriodFilter` for MVP)
- [x] Add filter by collective (use `CollectivePicker.js`)
- [x] Add chart and the ability for it to dynamically update based on the filters. We can use the [Apex line charts](https://apexcharts.com/javascript-chart-demos/line-charts/) for this purpose.

### API

- [x] Add `ContributionsStats` field to `Host` object. 
  - [x] Args: accounts, period
  - [x] Number of one-time
  - [x] Number of recurring
  - [x] Daily average income
  - [x] Data needs to be returned with a customizable granularity (day/month/etc). Granularity should be automatically calculated from the chose period
- [x] Add `ExpensesStats` field to the `Host` object.
  - [x]  Daily average paid
  - [x] Invoice/Reimbursement/Grants repartition
  - [x] Data needs to be returned with a customizable granularity (day/month/etc)

**Comment by SudharakaP** [comment]
@Betree : If no objections I'll take this up and I'll implement the parts without the chart? And after you've done the experimentation with https://github.com/opencollective/opencollective/issues/4657#issuecomment-916204066 we can implement the charts? Does that sound good with you? 😄

**Comment by Betree** [comment]
@SudharakaP Sure, feel free to start :slightly_smiling_face:

**Comment by SudharakaP** [comment]
@Betree : Completed the filters and the stats. I think the PR is getting large so I thought it's best to stop at this. If no objections I go ahead and add try adding the chart as well maybe in a separate PR? 😄

**Comment by Betree** [comment]
> Completed the filters and the stats. I think the PR is getting large so I thought it's best to stop at this. If no objections I go ahead and add try adding the chart as well maybe in a separate PR? smile

Yes, it's a good idea to split these :+1:

**Comment by BenJam** [comment]
plan 

- [ ] close out this issue

**Comment by SudharakaP** [comment]
Closing out this issue as the relevant PRs have been merged.
