### ISSUE TITLE
Admin Dashboard Reports: Platform Tips section

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4659]
Part of https://github.com/opencollective/opencollective/issues/4300

Design file: [Figma](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=13711%3A157088)

---

![image](https://user-images.githubusercontent.com/12435965/132721315-48a1dc87-bda2-4fbd-8e61-96921094495a.png)

### Front-end
- [ ] Use `HostMetrics` to get the platform tips collected and the platform tips owed amounts 
- [ ] Add `PeriodFilter` to make sure we can filter by the date

### API
- ~~[ ] Add API Query to get historical data; Check with legacy data (pre-ledger migration)~~

**Comment by Betree** [comment]
>  Add API Query to get historical data;

@SudharakaP I'm not sure what you mean by that, do we really need that since there's no historical chart in there?

**Comment by SudharakaP** [comment]
> > Add API Query to get historical data;
> 
> @SudharakaP I'm not sure what you mean by that, do we really need that since there's no historical chart in there?

Yes looking back, I don't think we need this since there's no historical chart. I based this off of the document and I think we put it there thinking there's a chart; https://docs.google.com/document/d/1RwC8agICM9CL0IBM9-dtpO2fGPxGKSy5z4hUDdyV-B8/edit. 🤔
