### ISSUE TITLE
provide way for a collective to insert custom javascript in the header or footer

### ISSUE THREAD

**Issue by ghuntley** [opencollective/opencollective#466]
Specifically I'd like to inline some analytic tools (we use clicky.com and google analytics) to get a better idea as to what's happening and where people are coming from. Have also toyed about using something like crazyegg.com to provide usability insights such as heatmaps

**Comment by xdamman** [comment]
Way too dangerous. I'd rather do https://github.com/opencollective/opencollective/issues/467

**Comment by ghuntley** [comment]
Let's do 467

**Comment by ghuntley** [comment]
Actually I'm opening this one up again. Being able to insert our CRM lead-scoring javascript code would be immensely useful. 

```
<script type="text/javascript">
--
  | var trackcmp_email = '';
  | var trackcmp = document.createElement("script");
  | trackcmp.async = true;
  | trackcmp.type = 'text/javascript';
  | trackcmp.src = '//trackcmp.net/visit?actid=475329797&e='+encodeURIComponent(trackcmp_email)+'&r='+encodeURIComponent(document.referrer)+'&u='+encodeURIComponent(window.location.href);
  | var trackcmp_s = document.getElementsByTagName("script");
  | if (trackcmp_s.length) {
  | trackcmp_s[0].parentNode.appendChild(trackcmp);
  | } else {
  | var trackcmp_h = document.getElementsByTagName("head");
  | trackcmp_h.length && trackcmp_h[0].appendChild(trackcmp);
  | }
  | </script>
```

**Comment by znarf** [comment]
After discussion within the team, we don't want to allow that in the near future. Mostly for security reasons.
