### ISSUE TITLE
Add a comma to all `e.g` strings (-> `e.g.,`)

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4664]
Followup on https://github.com/opencollective/opencollective-frontend/pull/6847#discussion_r705445293
According to the feedback from https://opencollective.slack.com/archives/C019YCG6RCY/p1631200631013100

We have 14 places using `e.g.` right now, while the correct format according to https://www.merriam-webster.com/dictionary/e.g. seems to be `e.g.,`.

**Comment by Betree** [comment]
Looking at https://dictionary.cambridge.org/us/dictionary/english/eg, an example without the comma is given:
> One partner in the business cannot act unilaterally e.g. over investments, holidays, contracts to accept, etc.

@alanna could it be that this rule only applies in certain cases, or that both versions are valid?

**Comment by SudharakaP** [comment]
@Betree : The above link is from cambridge dictionary. So in British way of writing this comma isn't used as far as I know. Only in American English. It says that here; https://en.wiktionary.org/wiki/e.g.#Usage_notes (under usage notes). 😉

**Comment by Betree** [comment]
Ok so:
>  In US English, "e.g." is usually followed by a comma.[2] It is not followed by a comma in other English-speaking countries.

And the version without the comma is listed as valid for US English too.

I'm not sure whether we're trying to match en_US in our wording. I'm personally not convinced by the necessity of this change, the fact that everyone in the team (incl. native speakers) wrote it as `e.g.` shows that it feels more natural for us to do so, and thus simpler to enforce. I'll let @alanna take a final decision on this.

**Comment by alanna** [comment]
I don't think this matters much either way and both uses, with comma and
without, are acceptable.

**Comment by znarf** [comment]
Generally, I think we should favor American English over British English as the company and our biggest hosts are based in the USA.

Looks like @alanna has nothing for or against the change.

Personally, no strong opinion but I'm fine with it.

**Comment by SudharakaP** [comment]
@opencollective/design : Just to note this change has been merged and I am pinging design to take note of this for future design iterations. So we will be using `e.g.,` instead of `e.g.`. 🙂
