### ISSUE TITLE
Unable to contribute as guest to Collective whose Host has only bank transfer

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4668]
This was reported by a user:

I have a contributor who would like to make a contribution to our collective.
He was trying to do that without being registered with his email.
Curiously, he can not see frequency flexibility: One Time, Monthly, Yearly
He sees the same as on one of screenshots joint with the email.
Finally, on the 3rd step "Payment Info", he sees "No payment method available".
However, I already entered a bank account info to our fiscal host.
Seems like UI behaviour is different for registered users. For example, if I try to make a contribution from my personal account I see the frequency options and the payment as bank transfer.
I think I understand the issue we are facing. As for registered user we can see the frequency:
1) choosing "one-time", we have "bank transfer" available
2) choosing "monthly", we see "no payment methods available"
For non registered users, as we can not see frequency option, it seems like by default "monthly" option is taken and thus we see "no payment methods available".

-----------------------

I have tested this by setting up [this collective](https://opencollective.com/test-abcd/donate) under a test host with only bank account payment method active. I went through the flow once and hit the same issue as the user -  it did not give me frequency options but then said 'no payment method available'. But then I tried again and now it's working, seeming to default to one-time and showing the bank transfer option. I can't figure out what I did. But this user seems to have tested it thoroughly so I think we should investigate.

**Comment by Betree** [comment]
Related to https://github.com/opencollective/opencollective/issues/4669. We made some improvements in https://github.com/opencollective/opencollective-frontend/pull/7270 and https://github.com/opencollective/opencollective-frontend/pull/7271 that possibly address this, but it needs to be tested.

**Comment by znarf** [comment]
After reviewing this issue today, we were not able to reproduce. We need to invest more time in QA to understand properly.

**Comment by tyntyn1** [comment]
Ty https://github.com/community/community/pull/28585#issue-1330778894

**Comment by znarf** [comment]
Closing as stale.
