### ISSUE TITLE
Parent Collective Update should go to Project & Event contributors too

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4673]
Collectives think of Projects as inside their Collective. They don't want to have to send multiple Updates to reach their community of contributors. Project Updates going only to the Project contributors makes sense, but parent Collective Updates should go to everyone who has contributed to that Collective, its Projects, Events, Tiers, etc.

MVP: Parent Updates go to all contributors

Best solution: Update sender can select which Project/Event/Tiers/etc contributors and Update goes to, with all being the default.

**Comment by Betree** [comment]
Sounds good to me. Let's remember that, by default, the behavior we apply for projects will apply to events as well.

**Comment by alanna** [comment]
> the behavior we apply for projects will apply to events as well.

I think it works. Event Updates should go only to Event attendees/contributors, while parent Updates should go to all Project and Event contributors too.

**Comment by SudharakaP** [comment]
Taking this issue if no objections. 👍🏽

**Comment by alanna** [comment]
@SudharakaP was this completed?

**Comment by SudharakaP** [comment]
> @SudharakaP was this completed?

We are working on this one. I have a pull request for this and we are at the review stage. I'll try to get this done this week. 👍🏽

**Comment by alanna** [comment]
Hi @SudharakaP did this end up getting done? I need to clarify if this is live for a user support ticket.

**Comment by SudharakaP** [comment]
> Hi @SudharakaP did this end up getting done? I need to clarify if this is live for a user support ticket.

Sorry, we have having a small issue and I am having a call with Ben this week about this one. I am pretty confident we can finalize it this week. Sorry about that wait. 😉

**Comment by Memo-Es** [comment]
Making myself available if we need design support for the UI visualization of choosing updates for global, events and projects
@SudharakaP @Betree

**Comment by SudharakaP** [comment]
> Making myself available if we need design support for the UI visualization of choosing updates for global, events and projects @SudharakaP @Betree

Currently we just send Something that we could I think prioritize for the next sprint. Since Alanna also mentioned this as the best solution I am adding this to the next sprint plan to discuss.
