### ISSUE TITLE
[DOCS] Create some documentation clarification between 'Tiers, Goals, Projects (when to use each one)'

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#4679]
If there is still an ongoing issue of users getting confused about which one to use for what type of funding goals, this documentation/FAQ could be helpful to clarify the distinctions. Could be a single comparison chart/infographic; or just a little blurb at the bottom of each respective page (e.g. at the bottom of the goals page: "Trying to set aside funds for a specific goal with separate admins? Try out our Projects feature! [+Link]"

am happy to help put this together/brainstorm if this seems useful.

If this isn't really an issue, can disregard.

**Comment by shannondwray** [comment]
This has been tackled in the new docs rollout! Thank you Kayla <3
