### ISSUE TITLE
[bug] "other contributor" count showing as "-1"

### ISSUE THREAD

**Issue by patcon** [opencollective/opencollective#468]
On the [EDGI test collective page](https://opencollective.com/test-edgi), I'm seeing this:

![screenshot of edgi collective page bug](https://imgur.com/c2Kvnqw.png)

The only other account is "EDGI Admin", which is the shared account used as the host.

PS, love the redesign!!! Yay!

**Comment by piamancini** [comment]
Thanks! we'll have a look.
