### ISSUE TITLE
Do not show archived items in user menu

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4685]
<img width="1161" alt="Screen Shot 2021-09-15 at 8 51 37 PM" src="https://user-images.githubusercontent.com/5498878/133404908-950f6cba-a2d9-478c-90da-58aa6ab211a4.png">

In the example above an archived profile shows up the same as the active ones in my user menu. I think we should remove these.

This leaves the question of how then can someone get to their archived profiles if they want to reactivate it or something. But I think we could put a link to a list of your archived items somewhere, like on your personal profile page or in settings, because this is probably a much less used function than finding your active items in your user menu.

**Comment by scenaristeur** [comment]
@alanna in this case,
A checkbox with "show archived" unchecked by default could do the trick ?

**Comment by Betree** [comment]
Closing as duplicate in favor of https://github.com/opencollective/opencollective/issues/5770
