### ISSUE TITLE
design: Why does the established date get so much screen space?

### ISSUE THREAD

**Issue by ghuntley** [opencollective/opencollective#469]
![image](https://user-images.githubusercontent.com/127353/31322291-b0d93542-ace0-11e7-9b9d-057aea32bd32.png)

That's a lot of screenspace. What design purpose does displaying this date serve etc?

ps; ReactiveUI was established eight years ago; showing that date there that shows 2017 could be a source of confusion.

**Comment by piamancini** [comment]
We refer to when the collective has been established. We will be iterating with the design in the coming months. But the goal is to provide information about when a community became a collective. It has good real estate, because collectives are the center of the platform.

**Comment by piamancini** [comment]
closing this for the moment. We can chat more when new design is out.
