### ISSUE TITLE
[PROJECT] Show details for Expenses in transactions list

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4691]
## User story 
A host admin at OC Paris recently got confused about not seeing the payout fees for the expense, as they're not currently surfaced in the interface.

## Best solution for this problem
In the transaction lists, show a `View details` button on expense entries (similar to what we do for contributions). When clicked, it should display some information about the expense such as the fiscal host and, if available, details about the transaction:
- Payment processor fee
- Host fee

## Context
Ping @znarf since you proposed something related today

**Comment by BenJam** [comment]
@znarf @Betree is there any work that we're doing to show these fees as part of the work @aminakazi is doing on the transaction ledger design? Asking as I have a request about this.

**Comment by aminakazi** [comment]
From a design standpoint, the payment processor fee and host fees, among other things, are clearly being showcased in the new UI. 

However, I'm unsure when we'll be prioritizing the front-end development for this.

**Comment by SudharakaP** [comment]
As an MVP for this one I suggest we implement the following design where we show the payment processor fee and the host fee along with the transaction. 

![All Transactions](https://user-images.githubusercontent.com/12435965/150911406-077f86e6-3441-4207-a912-4bad7b5e9e4a.png)

Figma Design: https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab?node-id=13977%3A208816

@znarf : Does this sound okay? I'll look into the specs more if this is in agreement. 

cc: @aminakazi

**Comment by znarf** [comment]
@SudharakaP What you propose is not a MVP. The MVP is exactly what @Betree is proposing in the issue.

We can look into implementing **parts** of the new design after implementing the first version.

**Comment by SudharakaP** [comment]
> @SudharakaP What you propose is not a MVP. The MVP is exactly what @Betree is proposing in the issue.
> 
> We can look into implementing **parts** of the new design after implementing the first version.

Ops, thanks for clarifying. I somehow got lost in the details here. So if no objections, as a first step I'll use the same design as in the transaction details drop-down; 

![image](https://user-images.githubusercontent.com/12435965/150939748-793de9bd-3cff-40c5-b9ab-766587685625.png)

without the buttons and the `Paid with` parts.

**Comment by aminakazi** [comment]
I agree with the MVP proposed by @Betree. @SudharakaP Like you have mentioned, we will remove the buttons and the 'paid with' section. I'd like to propose different text for the transaction details. Can we do the following...

TRANSACTION DETAILS
This transaction includes:
• $X Payment processor fees
• $X Host fees

**Comment by SudharakaP** [comment]
> I agree with the MVP proposed by @Betree. @SudharakaP Like you have mentioned, we will remove the buttons and the 'paid with' section. I'd like to propose different text for the transaction details. Can we do the following...
> 
> TRANSACTION DETAILS This transaction includes: • $X Payment processor fees • $X Host fees

@aminakazi : Thanks. That makes sense. Let me work on it. 👍🏽

**Comment by SudharakaP** [comment]
Sorry about taking time on this update, but some details that we've discussed in our call and the next steps. 

### How the Expense Amounts are Displayed

Currently in the transactions list (https://opencollective.com/babel/transactions) for expenses we display the total amount payed by the payer including the payment processor fee. For example taking an expense payed by Babel to Henry Zhu, 

![image](https://user-images.githubusercontent.com/12435965/151783236-ea3b457a-28de-4134-99c8-bf4c62299ea6.png)

the total amount 6000.51 includes the expense submitted by Henry (which is 6000) and the 0.51 payment processor fee payed by Babel. 

In the opposite transaction; 

![image](https://user-images.githubusercontent.com/12435965/151785010-fbd8f6be-2be8-40b1-a753-c1fd384b309d.png)

we show the amount received by the payee. 

### Proposed Changes

- We shall show the `amount` for the expense breaking down the payment processor fees. So that in the example above the expense looks like, 

![image](https://user-images.githubusercontent.com/12435965/151788803-ab6a4bd9-fdfd-45ec-8548-fc8b5e49febc.png)

along with a _View Details_ button (similar to what we have in contributions) which expanded shows the payment processor fees as suggested above; https://github.com/opencollective/opencollective/issues/4691#issuecomment-1020947894. 

### Implementation Details

- Change appropriate logic for expenses in `TransactionItem.getDisplayedAmount` method.
- Add a View details button and a drop-down `Container` to display expense details in the `TransactionItem` component (partially done in https://github.com/opencollective/opencollective-frontend/pull/7391). 

### Create testing profiles on staging and double check the following scenarios. 

In addition to the above change we need to create the following test profiles on staging and double check how we are displaying the amounts for each of these cases; 

- 1 contribution
- 1 refunded contribution
- 1 added funds
- 1 expense with fees paid by the collective
- 1 expense with fees paid by the payee (100% of the remaining balance)
- 1 refunded expense
- 1 refunded expense when fees were paid by the payee

cc: @znarf

**Comment by piamancini** [comment]
- [ ] Implement and deploy

**Comment by SudharakaP** [comment]
The testing profile on staging is created at, https://staging.opencollective.com/transactions-project/transactions

### Next steps

- Update the PR (https://github.com/opencollective/opencollective-frontend/pull/7391) with modifications as proposed above. 
- After merging double check all the scenarios with the test profile in staging. 

cc: @znarf

**Comment by Betree** [comment]
We also don't display the contribution tier in there. Would be nice to have it.

**Comment by SudharakaP** [comment]
> We also don't display the contribution tier in there. Would be nice to have it.

I've created a separate issue to track this one; https://github.com/opencollective/opencollective/issues/5193. 🙂

**Comment by SudharakaP** [comment]
As for this issue, some specs that needs to be agreed upon is the labeling of the transaction details depending on the different transactions. Here is my proposal on this; 

### Expense with Payment Processor Fee Payed by the Collective 

Example: Expense of $23, with payment processor fee of $2 dollars submitted to `Transactions Project` by `Suds`. 

#### From the collective perspective
```
Expense Amount: $23.00
Payment Processor Fees (Paid by Transactions Project): $2.00
Net Amount for Transactions Project: $25.00
```

![image](https://user-images.githubusercontent.com/12435965/152409503-c8813de8-57bc-43b0-8509-4e898dc280c5.png)

#### From the payee perspective
```
Expense Amount: $23.00
Payment Processor Fees (Paid by Transactions Project): $2.00
Net Amount for Suds: $23.00
```

![image](https://user-images.githubusercontent.com/12435965/152409578-7f2ce612-266a-42a5-8f74-c3de89abf535.png)

### Expense with Payment Processor Fee payed by the Payee 

Example: Expense of $2.87, with payment processor fee of $0.51 dollars submitted to `Transactions Project` by `Suds`. 

#### From the collective perspective
```
Expense Amount: $2.87
Payment Processor Fees (Paid by Suds): $0.51
Net Amount for Transactions Project: $2.87
```

![image](https://user-images.githubusercontent.com/12435965/152409722-f3109ff2-6e32-4d91-87e6-f3bb3d46f9b3.png)

#### From the payee perspective
```
Expense Amount: $2.87
Payment Processor Fees (Paid by Suds): $0.51
Net Amount for Suds: $2.36
```

![image](https://user-images.githubusercontent.com/12435965/152409784-be705217-1e69-4dbe-a64e-8df05fda7043.png)

Note for a refund of an expense (for both cases where the payment processor fee is payed by collective or the payee) we just show the refund amount as the payment processing fee should always be 0. 

![image](https://user-images.githubusercontent.com/12435965/152409807-3a4c3708-5bb2-40f8-89b1-270138632fe1.png)

![image](https://user-images.githubusercontent.com/12435965/152409847-27e2d19d-ccdd-4075-9696-c2d9d5fbbecc.png)

**Comment by SudharakaP** [comment]
Some corrections to the above spec; when the payee pays the payment processor fees and then the expense is refunded I am using the label; `Refunded Payment Processor Fee` (as pointed out here; https://github.com/opencollective/opencollective/issues/5194#issuecomment-1031207925 we have a refunded payment processor fee in this case and my thinking is that we should show this for added clarity). 

### From the Collective Perspective: 

![Screenshot 2022-02-07 at 16-07-19 Transactions Project - Open Collective](https://user-images.githubusercontent.com/12435965/152773999-96122b40-b999-4ddd-9924-6269a8f9811a.png)

### From the Payee Perspective:   

![Screenshot 2022-02-07 at 16-07-56 Suds - Open Collective](https://user-images.githubusercontent.com/12435965/152773904-1cd5a057-0061-4615-9d46-4de3425380ee.png)

**Comment by SudharakaP** [comment]
The complete screenshots are,

### From the Collective Perspective: 

![Screenshot 2022-02-07 at 16-44-37 Transactions Project - Open Collective](https://user-images.githubusercontent.com/12435965/152778105-3a8d3bfe-f6e7-4964-a025-a188e9b416dc.png)
![Screenshot 2022-02-07 at 16-44-20 Transactions Project - Open Collective](https://user-images.githubusercontent.com/12435965/152778114-9b8ade3f-2b00-4c6b-8548-925d3917251e.png)
![Screenshot 2022-02-07 at 16-44-08 Transactions Project - Open Collective](https://user-images.githubusercontent.com/12435965/152778120-51998181-4a32-45b7-b0b3-c4d76acc3f41.png)

### From the Payee Perspective: 

![Screenshot 2022-02-07 at 16-47-40 Suds - Open Collective](https://user-images.githubusercontent.com/12435965/152778350-7e40d493-35bd-4a8e-a79b-3b9e670d51bf.png)
![Screenshot 2022-02-07 at 16-47-22 Suds - Open Collective](https://user-images.githubusercontent.com/12435965/152778354-ab92d071-c625-4746-8e62-c10f5d0d9144.png)
![Screenshot 2022-02-07 at 16-47-10 Suds - Open Collective](https://user-images.githubusercontent.com/12435965/152778374-457d6f26-c11c-4efa-8acb-6b147aee9bb5.png)

**Comment by znarf** [comment]
Goals for Q1 Sprint 1 Week 3:

- [ ] Continue testing and reviewing edge cases
- [ ] Tackle https://github.com/opencollective/opencollective/issues/5208
- [ ] Deploying first version in production

**Comment by znarf** [comment]
Goals for Q1 Sprint 1 Week 4:

- [ ] Merge
- [ ] Deploying first version in production

**Comment by znarf** [comment]
Goals for Q1 Sprint 1 Week 6:
- [ ] Design / Engineering to discuss follow up and document in an issue @aminakazi @znarf @SudharakaP

**Comment by znarf** [comment]
Feedback issue:  [Feedback] Expense Details on Transactions #5233

**Comment by BenJam** [comment]
@opencollective/design can someone pick up the outstanding item above:

> Design / Engineering to discuss follow up and document in an issue @aminakazi @znarf @SudharakaP

Specifically, whether we should pick up https://github.com/opencollective/opencollective/issues/5193 and implement the cleaned-up design in https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab?node-id=13977%3A208816
