### ISSUE TITLE
Collect legal names and addresses for any user or org contributing over 5k in a tax year 

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#4692]
## User story 
As a non-profit host based in the US I need to collect the names and addresses of any user or organisation that has contributed over $5,000 in the tax year so that I can comply with [tax obligations](https://www.irs.gov/taxtopics/tc506).

## Best solution for this problem
- [x] Collect this information as part of the contribution flow when a user/org tips over 5k for the year. 
- [ ] Make addresses mandatory for any host using 'added funds' as this skips a significant part of the journey for the contributor. 
- [ ] Back-fill address information from sources that are available (stripe, audit lists etc.)

## MVP
 - [x] Add address information to the contribution flow and make this a mandatory requirement if the user/org is tipping over 5k of contributions in the year. 
 - [ ] Add address information from existing audits to the address on organisational profiles (and notify them that we have done this)
 - [ ] Notify anyone with >5k of contributions that we do not already have an address on file for to provide it 

## Metrics
Amount of time that @piamancini et al have to spend gathering address information as part of our annual accounts 🙃

**Comment by BenJam** [comment]
>  Add address information to the contribution flow and make this a mandatory requirement if the user/org is tipping over 5k of contributions in the year.

I think @Memo-Es mentioned he already had something on this?

**Comment by Memo-Es** [comment]
## Design update

| Guest | Logged-in user | Privacy tooltip | Info tooltip | Profile picker |
|-------|----------------|-----------------|--------------|----------------|
| <img width="604" alt="Screen Shot on 2021-09-17 at 12-35-04" src="https://user-images.githubusercontent.com/49539954/133831352-7b42c90f-0bd3-40be-b06a-cf9ab2f03b56.png">  |  <img width="593" alt="Screen Shot on 2021-09-17 at 12-38-39" src="https://user-images.githubusercontent.com/49539954/133831358-19ba329d-54e3-4542-9204-d320bddf252d.png">   | <img width="575" alt="Screen Shot on 2021-09-17 at 12-38-27" src="https://user-images.githubusercontent.com/49539954/133831356-0abf016b-ddc0-44f6-bee9-a5f9dc23ceca.png">           |   <img width="577" alt="Screen Shot on 2021-09-17 at 12-37-53" src="https://user-images.githubusercontent.com/49539954/133831355-f9b3d93b-462b-4a08-9dcb-9169b00a8bab.png">  |  <img width="606" alt="Screen Shot on 2021-09-17 at 12-35-24" src="https://user-images.githubusercontent.com/49539954/133831354-7a490d94-8c91-44a7-a708-4dbec5687c3b.png">   |

[Figma file](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/[OC-Design]-Production-Ready-✅?node-id=13838%3A161523) for reference

Based on this issue #4654 raised by @alanna

**Comment by alanna** [comment]
I made a pull request to change the helptext under the boxes, which has been merged. Please keep that new text.

**Comment by alanna** [comment]
If the profile already exists (as implied by the user selecting it at the top) won't the display and legal names be set? Or is this just a way to get them to update the legal name as part of the flow if they have not already done so? That's probably a good idea as many existing profiles won't have legal/display names set correctly.

**Comment by alanna** [comment]
I think people will likely change the display name to 'incognito' instead of selecting the incognito option as currently designed. Can we think about how to prevent this? If we make the incognito selection the first thing maybe it will ease their mind about putting in their name(s)?

**Comment by Memo-Es** [comment]
> I think people will likely change the display name to 'incognito' instead of selecting the incognito option as currently designed. Can we think about how to prevent this? If we make the incognito selection the first thing maybe it will ease their mind about putting in their name(s)?

@alanna Isn't the help text of the display name field enough for this?  ![Annotation on 2021-09-22 at 21-17-03](https://user-images.githubusercontent.com/49539954/134445770-9150ce29-e4a4-4b66-8cf0-735881cd93bf.png)

**Comment by alanna** [comment]
I hope so but I guess we'll see.

**Comment by Betree** [comment]
We've recently discussed the fact that this issue should be prioritized as soon as possible. The more we wait to implement it, the more work we'll have next year when the time will come to collect contributors' addresses.

The design have been shared in https://github.com/opencollective/opencollective/issues/4692#issuecomment-921973945, so there should be everything needed from the engineering perspective to start the work.

**Comment by Memo-Es** [comment]
@Betree let me know if you need anything on our side as you move forward 👍🏼

**Comment by Betree** [comment]
This is now implemented in production for guest contributions.

We need a similar implementation for existing accounts, ideally checking the cumulative amount contributed (which is something that we want for #3478 as well). We'll want to:
- Pre-fill the location input with the existing location if one exists
- Update the profile with the new location if it changes

**Comment by piamancini** [comment]
- [ ] merge new collective picker 
- [ ] develop private fields, legal name & address

**Comment by Betree** [comment]
For this week:
- [ ] develop private fields, legal name & address
- [ ] cumulative amounts

**Comment by Betree** [comment]
From https://github.com/opencollective/opencollective/issues/3337, it seems that we require a legal name above $250 and an address above $5000. Can we confirm that we want these two separate thresholds?

**Comment by piamancini** [comment]
- [ ] cumulative amounts
 - [ ] close issue

**Comment by Betree** [comment]
I created a [followup issue](https://github.com/opencollective/opencollective/issues/5091) for cumulative amounts as it seems not ideal to implement it without https://github.com/opencollective/opencollective/issues/3479.

Therefore, this issue will be resolved by https://github.com/opencollective/opencollective-frontend/pull/7292
