### ISSUE TITLE
PeriodFilter: Chosen Date is off by Two Days

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4696]
This is something that I've noticed working on another issue. It seems that the [`PeriodFilter`](https://github.com/opencollective/opencollective-frontend/blob/9b33639bfad126a681d5561dfce4127456f25371/components/budget/filters/PeriodFilter.js) behaves weirdly when choosing dates. 

As I've observed it seems that when we choose the dates the date chosen is not the one that's displayed in the Period filter. Rather it seems to be off by two days. Here's a screen-cast which demonstrates that. Note that I choose Sep 01st to Sep 16th in the period filter; however after choosing it the period filter displays August 30th to September 14th. It seems that both the dates are two days off. 🤔

![period-filter-bug](https://user-images.githubusercontent.com/12435965/133722474-8c4e8ceb-ae56-4577-ba0d-efecdd34f135.gif)

**Comment by Betree** [comment]
Good catch! That probably has to do with timezones. Being in CET, I never noticed this one personally but I'll try to look at it since I'm working on the `PeriodFilter` component.
