### ISSUE TITLE
Should we remove explicit IDs from our translation strings?

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4697]
At some point in the past, setting an ID on internationalization strings was mandatory. Consequently, all our strings have an `id` defined that we set manually.

This changed at some point, and today if you omit the id, `formatjs` will [automatically generate a hash](https://formatjs.io/docs/getting-started/message-extraction/). **The docs actually recommend relying on that hash rather than providing explicit IDs**:
> During extraction, we'll preserve explicit declared IDs and insert a hash as an ID for messages without. We recommend against explicit IDs since it can cause collision.

I'm wondering whether we should adapt our practices. So far, here are the arguments I see:

**Pros for removing `ids`**
- Will facilitate developer's lives when writing new strings (one less thing to worry about)
- Solves the duplicates problem, no need to look in `en.json` / copy-pasting any more when re-using strings

**Cons for removing `ids`**
- The id often gives some context to translators about where this string is coming from (eg. when they see `order.expired`, they understand that the string Expired refers to an order). This could be solved by relying on the `description` field that is normally meant for that, but that would require some adaptations to our files format.
- Would completely reset all our translations if we enforce it on existing strings. Though there may be a clever way to notify Crowdin about the move and makes sure it re-uses existing strings.
- We sometimes use keys for grouping (eg. `Expense.Status.Approved`, `Expense.Status.Rejected`, etc). That's nice when reviewing the file.

**Conclusion**
No strong conclusion for me so far. It looks like removing `id`s would bring many benefits, and we probably can find workarounds for most of the cons.

**Comment by SudharakaP** [comment]
Thanks for posting this issue. I vote for the removal of the ids; it makes sense and keep things simple. 😉

**Comment by znarf** [comment]
> Would completely reset all our translations if we enforce it on existing strings. 

Clear blocker to remove ids for past entries for now. On the other end, ok to already skip ids for new strings.

**Comment by Betree** [comment]
Thanks for the feedback! So for now, it seems that the next steps could be:
1. **Relax our policy on IDs today by not requiring them for new strings**
2. **Find out if there's a way to migrate existing strings without losing all the translations.** I suspect something like this may be possible with a process like this:
    1. Merge Crowdin PR to make sure we're in sync, pause all translations and PRs merge
    2. Open a new PR that migrates all the IDs, in `en.json` but also in locale files (`fr.json`, `es.json`, etc.). Achieving so might require a bit of work.
    3. On Crowdin's website, manually upload the updated language files for all locales
    4. Resume normal activity

**Comment by Betree** [comment]
Closing this as it seems we concluded with https://github.com/opencollective/opencollective/issues/4697#issuecomment-921858385
