### ISSUE TITLE
Backer gets placeholder image on opencollective.com, but not GitHub

### ISSUE THREAD

**Issue by Awk34** [OpenCollective/OpenCollective#47]
GitHub:
![screenshot-github com 2016-04-26 12-22-50](https://cloud.githubusercontent.com/assets/5545474/14825997/08107d36-0baa-11e6-826c-0e3a1502d300.jpg)

OpenCollective:
![screenshot-opencollective com 2016-04-26 12-26-27](https://cloud.githubusercontent.com/assets/5545474/14826012/1563e0ae-0baa-11e6-96f6-7c76b28300a8.jpg)

**Comment by piamancini** [comment]
Is this still a problem @Awk34 ?

**Comment by Awk34** [comment]
Appears so: https://github.com/angular-fullstack/generator-angular-fullstack#backers

**Comment by piamancini** [comment]
@asood123 could this be part of the same issue (broken link on readme) just fixed?

**Comment by asood123** [comment]
Here's a fix for that: https://github.com/OpenCollective/opencollective-website/pull/244

**Comment by piamancini** [comment]
do I need to change something in the collective's readme? or does it get fixed from this

**Comment by asood123** [comment]
It'll get fixed once we push

**Comment by Awk34** [comment]
LGTM!

![screenshot-github com 2016-05-20 10-09-21](https://cloud.githubusercontent.com/assets/5545474/15430346/f6ba70e2-1e72-11e6-9f12-6c3722f0b9fd.png)
