### ISSUE TITLE
[bug] error when trying to connect stripe account

### ISSUE THREAD

**Issue by patcon** [opencollective/opencollective#470]
![stripe error screenshot](https://imgur.com/M4dgdHv.png)

Oddly, this happened when logged into the "core contributor" account, rather than one that I knew to be configured as host. As in, I didn't realize a core contributor would be presented the option to attach a stripe account.

**Comment by piamancini** [comment]
@patcon yes, users can be hosts of collectives. May users are. 

cc / @asood123 for stripe issue.

**Comment by asood123** [comment]
@xdamman are we offering anyone to connect with a stripe account? I think previously there was a check for hosts

**Comment by patcon** [comment]
I believe I was host of `test-edgi` (which was set pre-migration), but regular "core contributor" for `hacklabto` where this error happened (which was created just now through self-serve path)

**Comment by xdamman** [comment]
Yes everyone can connect a stripe account to start hosting a collective.

Just updated the redirect uri in Stripe. Thanks for reporting this.
