### ISSUE TITLE
Typos on https://opencollective.com/foundation/edit/virtual-cards

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#4700]
some typos on https://opencollective.com/foundation/edit/virtual-cards

_Originally posted by @kaylarep in https://github.com/opencollective/opencollective/issues/4312#issuecomment-922085944_

should say:
Use a virtual card to spend from your collective's budget. You can request multiple cards (review the host's policy to see how many). Your fiscal host will create the card for you and assign it a limit and a merchant. You will be notified by email once the card is assigned. Learn more (+link to https://docs.opencollective.com/help/expenses-and-getting-paid/virtual-cards)

![image](https://user-images.githubusercontent.com/64920686/133854511-7b6af215-ddef-4c87-a6a9-5dba6cba37cc.png)

**Comment by SudharakaP** [comment]
@kaylarep : Thanks for reporting the issue. I've corrected it; we'll deploy to production next week. 😉
