### ISSUE TITLE
Wrong regex for validating website urls

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#4706]
In the create organization page:
<img width="503" alt="Screen Shot 2021-09-18 at 11 35 47 AM" src="https://user-images.githubusercontent.com/74358/133884362-cda849c9-b7b2-4ce9-aa2a-557968d2324a.png">

**Comment by xdamman** [comment]
Also the checkbox "I verify that I am authorized to represent this organization." should be "I certify" no? Otherwise I'd expect to have to go through a KYC type of process on the next page to prove that I'm indeed a legal representative.

**Comment by Betree** [comment]
In `components/CreateOrganizationForm.js`, we shouldn't use a custom regex but rather rely on the standard `isURL` helper from validator-js. To be tested, but I'm pretty sure this URL will be supported.

**Comment by znarf** [comment]
For the future, I would like us to use html native url input to avoid having to invent our own validation.

**Comment by Betree** [comment]
@znarf One problem with relying on `type="url"` is that it will force users to prepend the URL with `https://`. The `isURL` helper matches what we do in the backend, it might not be the best in terms of accessibility but it's a good solution for a quick fix.
