### ISSUE TITLE
Remove options on Create Collective page

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4709]
On https://opencollective.com/create you see

![Screen Shot 2021-09-20 at 4 14 58 PM](https://user-images.githubusercontent.com/5498878/133956598-05d9444a-1ba6-4b26-8efa-b2a89718c98f.png)

These categories are no longer relevant in the same way and I think we can move past them.

Originally the Open Source path was put in place because at the time the vast majority of Collectives signing up were destined for OSC and we wanted an easy path for them. This is no longer the case.

The COVID19 category was put in place around OCF's COVID fee waiver campaign, which is long over.

I think we should remove this screen entirely and focus all our efforts on improving Collective onboarding and host discovery, which we are already working on.

So essentially put the content of https://opencollective.com/create/community at https://opencollective.com/create and skip a step.

**Comment by Betree** [comment]
I wanted to see some data on this, so I asked [metabase](https://opencollective-metabase.herokuapp.com/question/570-count-new-active-collectives-by-fiscal-host):

![image](https://user-images.githubusercontent.com/1556356/133975196-c03c50b4-6c14-4622-b658-bff71588bb6f.png)

Nowadays, collectives hosted by OSC still represent between 20% and 30% of active collectives created on the platform:

<details>

<summary>SQL Query</summary>

```sql
WITH active_collectives AS (
  SELECT c.*
  FROM "Collectives" c
  INNER JOIN "Transactions" t ON t."CollectiveId" = c.id
  WHERE c."deletedAt" IS NULL
  AND t."RefundTransactionId" IS NULL
  AND t."deletedAt" IS NULL
  AND c."HostCollectiveId" IS NOT NULL
  GROUP BY c.id
) SELECT
  date_trunc('month', c."createdAt"),
  ROUND(((COUNT(c.id) FILTER (WHERE "HostCollectiveId" = 11004) / COUNT(c.id)::numeric) * 100.0), 2) || '%' AS "Percentage of collectives created for OSC"
FROM active_collectives c
WHERE c."createdAt" IS NOT NULL
GROUP BY date_trunc('month', c."createdAt")
ORDER BY date_trunc('month', c."createdAt") DESC
```

</details>

| Date                          | Percentage created under OSC | 
|-------------------------------|------------------------------| 
| 2021-09-01 00:00:00.000 +0200 | 22.22%                       | 
| 2021-08-01 00:00:00.000 +0200 | 19.44%                       | 
| 2021-07-01 00:00:00.000 +0200 | 24.24%                       | 
| 2021-06-01 00:00:00.000 +0200 | 22.81%                       | 
| 2021-05-01 00:00:00.000 +0200 | 32.64%                       | 
| 2021-04-01 00:00:00.000 +0200 | 34.29%                       | 
| 2021-03-01 00:00:00.000 +0100 | 27.13%                       | 
| 2021-02-01 00:00:00.000 +0100 | 31.53%                       | 
| 2021-01-01 00:00:00.000 +0100 | 28.57%                       | 
| 2020-12-01 00:00:00.000 +0100 | 23.76%                       | 
| 2020-11-01 00:00:00.000 +0100 | 32.10%                       | 
| 2020-10-01 00:00:00.000 +0200 | 32.93%                       | 
| 2020-09-01 00:00:00.000 +0200 | 30.00%                       | 
| 2020-08-01 00:00:00.000 +0200 | 38.71%                       | 
| 2020-07-01 00:00:00.000 +0200 | 37.63%                       | 
| 2020-06-01 00:00:00.000 +0200 | 38.20%                       | 
| 2020-05-01 00:00:00.000 +0200 | 34.35%                       | 
| 2020-04-01 00:00:00.000 +0200 | 18.42%                       | 
| 2020-03-01 00:00:00.000 +0100 | 30.71%                       | 
| 2020-02-01 00:00:00.000 +0100 | 44.16%                       | 
| 2020-01-01 00:00:00.000 +0100 | 44.93%                       | 

So a lot of collectives are actually coming for OSC. I'm afraid they can miss the Github apply flow if we skip this step, and it doesn't cost much to keep it. We can probably remove the "Covid-19" CTA though.

**Comment by alanna** [comment]
OK yes please proceed with removing the COVID19 option as a first step.

I really want us to get to the point that our onboarding and host discovery
flows are good enough that we can be confident someone seeking OSC will be
guided to it.
