### ISSUE TITLE
Only Show the Info for Legal Name in Host Section if Legal Name is not set

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4712]
This was initially reported at https://opencollective.slack.com/archives/G46PNRCGP/p1632132442330400?thread_ts=1631881231.305700&cid=G46PNRCGP. 

It seems that the legal name warning message when configuring hosts is displayed even if the legal name is set. We should make sure this info box is only shown if the legal name is not set. 🤔 

![image](https://user-images.githubusercontent.com/12435965/134005494-e2bb8e4c-7c65-4b71-949a-b8ba6ac45eda.png)

**Comment by znarf** [comment]
By the way, the message is wrong in this case (Self Hosted), there is no "Host".
