### ISSUE TITLE
Reset 2FA from root admin dashboard

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4714]
We'll need to consider some security concerns with this, but in cases where support has verified the ID os a user who needs their 2FA reset, could it be on root admin?

**Comment by Betree** [comment]
Yes, but I would like us to clarify https://github.com/opencollective/opencollective/issues/4478 before.

**Comment by sbn2030** [comment]
Follower.. I'm so tired to find a solution
966583332411
