### ISSUE TITLE
New pattern for additional buttons on expense pages

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#4715]
As shared by @alina in https://github.com/opencollective/opencollective/issues/4637#issuecomment-917992873_ and confirmed by other team members experience giving support, we should reposition the edit/download/delete button to a more recognizable pattern

> > visibility of the edit functions is something we should look at, specifically from the mobile users' perspective

> 
> We've gotten constant feedback since the design was released that having the edit/download/delete buttons on the upper left side is confusing. This doesn't match patterns in most other software and we should rethink it.

**Comment by alanna** [comment]
I am thinking something like the gmail send button where it's a button for the main action (in this case approve or pay) but also a dropdown for additional actions.

![Screen Shot 2021-09-22 at 8 56 45 AM](https://user-images.githubusercontent.com/5498878/134246550-3d5bd6bb-7681-4c6d-b06b-9c4c6935b307.png)

**Comment by Memo-Es** [comment]
## Design proposal

| Version 1 | Version 2 | Version 3 |
|-----------|-----------|-----------|
|  ![Desktop-1](https://user-images.githubusercontent.com/49539954/148153775-83249763-5cae-487e-9df8-740db67ebcdc.png)   |  ![Desktop-2](https://user-images.githubusercontent.com/49539954/148153779-fc16bd9c-2017-4ca4-851c-3c01ccbd1835.png)   |   ![Desktop](https://user-images.githubusercontent.com/49539954/148153782-458cd26c-b83f-455b-9af6-20b15f9ddd51.png) |

@alanna @alinamanko @Betree wdyt?

**Comment by Betree** [comment]
@Memo-Es I personally prefer options 2 and 3 because buttons with icons without labels are not explicit enough. In option 3, all actions live in the same place, I think that's a great approach.

**Comment by alinamanko** [comment]
I am thinking option 3 works best from my perspective given it lives in line with other actions (just wonder whether the hidden options may make it a little trickier to see and wonder what others think). That or number one.

**Comment by Memo-Es** [comment]
@alanna Have you seen this one?

**Comment by alanna** [comment]
I agree, option 3

**Comment by Betree** [comment]
**Specs**
- [ ] Remove the existing `ExpenseAdminActions` from `ExpenseSummary` and `pages/expense`
- [ ] Rename `ExpenseAdminActions` to `ExpenseMoreActionsButton`
- [ ] Update this `ExpenseMoreActionsButton` component to match the design proposed on [Figma](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=15758%3A212113) (see the preview below) with the 4 proposed actions (Edit, Download, Copy link, Delete). `components/PopupMenu.js` should be used to build the dropdown. 
- [ ] Some E2E tests will probably be broken with this update, we'll need to update them

We'll be waiting for @Memo-Es's feedback on where to put this button on mobile.

![](https://user-images.githubusercontent.com/49539954/148153782-458cd26c-b83f-455b-9af6-20b15f9ddd51.png)

**Comment by Memo-Es** [comment]
I included the mobile and tablet versions in the same [file](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=15758%3A212113) @Betree

<img width="1444" alt="Screen Shot on 2022-04-26 at 22-19-59" src="https://user-images.githubusercontent.com/49539954/165433320-8d1855c2-a3b0-4ace-9283-b1757727f851.png">
