### ISSUE TITLE
Add Legal Name for Organization SignUp form in the Expense Flow

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4719]
This is with regard to the following conversation, https://github.com/opencollective/opencollective-frontend/pull/6818#discussion_r713235892

It seems that we have missed adding the `Legal Name` to the organizational signup form within the expense flow. So when a user invite another user to submit and expense that user can then create an organization within the expense flow and I think we need to add the legal name to this flow as well. 😄 

![Screenshot 2021-09-21 at 11-47-48 abc expense · Expense #2389 - Open Collective](https://user-images.githubusercontent.com/12435965/134222503-b68510b8-2390-402c-bb93-b12a71f4eb88.png)

cc: @Betree

**Comment by Betree** [comment]
Good catch, feel free to ask @opencollective/design if you also need some feedback from them.

**Comment by Memo-Es** [comment]
| User | Organization |
|------|--------------|
| <img width="394" alt="Screen Shot on 2021-09-22 at 21-20-22" src="https://user-images.githubusercontent.com/49539954/134447533-974bf1a3-cf50-48fe-b44e-a3faa6c5b2d7.png"> |  <img width="380" alt="Screen Shot on 2021-09-22 at 21-21-52" src="https://user-images.githubusercontent.com/49539954/134447534-f1877993-1252-4fcd-a651-9c539ab3ce44.png">     |

We can follow the same logic from the contribution form, the incognito profile will likely exist for expenses as well after https://github.com/opencollective/opencollective/issues/3422

@SudharakaP

**Comment by SudharakaP** [comment]
@Memo-Es : Just to clarify, this is the new design for the contribution flow correct? We do not have this yet if I am not mistaken? 🤔 😄
