### ISSUE TITLE
invoice is showing net amount

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#472]
[Screenshot](https://gm1.ggpht.com/dukxaEXIBz3yB44YokXivW6Fp1uhVY5rdHsQAGr5mXjDY03XkOCwvLufya0HbRAu_CgFfmc0NsiIAEJxKuU293kF6oo1Ifc8VaCCZaMaESLu3l6X7kO-HgV8WpPDuJnj8jXVen9yqHySfIDzWosXmu39ttMV5ThqNFCG3qjuP5WkvNKRaxCqIEYJtAxx3TyHfzuKRa6wN_7iJg-HihKwwO8A6bJyxJtCt1QHtIf11JNLScpC4McRm3zeqzaT9ShL7eLPjU2YZrhXZ60QIY4b7ktEFAvwA6WmPrNftFHDb7JS4_X_Qo9g8PmCfuhimfANSfXnGlkuhiIlzep4wr47mhVrJBTrS9eNL4QUzkHIAr-iEHyeUgwsKKbh_bEu_QBZi1qkFrEzs2Ny1ku91KfBMH0uDtGSrvChTlSXIsmk21lIOkSCv5lzYwD4sNsnGxeMC24Vve-yc6ProV_z9oVWrbwfbskisu0nluGx2WJH3xt_DdqLm0X7BMDjyOmwrGWenlURS421spX8o87jNKgp7JAUJSsR9Gz_N-OQAPx9HdqiwQbrq8FRjTzPvcD7zju9HLtu2QXUpGKERx2ozcj762uRCmlCz61xlufYmBSYA6Li5ITLlnxOSz40WF_kgiYkP_LCyDPE2K6O_31iWbCwxXhL4gVvdHDOc9dd0rJZKhvEnl6jWojqjxtDawhNyQ=s0-l75-ft-l75-ft)

He got to this PDF from the /subscriptions link

**Comment by xdamman** [comment]
Can't open that screenshot

**Comment by xdamman** [comment]
It's ok, I found the bug. PR coming.
