### ISSUE TITLE
Implementation - How it works? marketing page

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#4720]
### We are updating our page to explain how the platform works

| Desktop | Tablet landscape | Tablet portrait | Mobile |
|---------|------------------|-----------------|--------|
| ![HD Desktop](https://user-images.githubusercontent.com/49539954/134245348-9f983921-247b-4f84-aec5-d57b6c59d752.png)   |  ![Tablet Landscape](https://user-images.githubusercontent.com/49539954/134245373-e22b0831-5d69-4c04-9f1a-62350056cc49.png)   |   ![Tablet Landscape-1](https://user-images.githubusercontent.com/49539954/134245366-30922b33-bbeb-42f4-a302-8e0b34b47bea.png)   | ![Mobile](https://user-images.githubusercontent.com/49539954/134245362-b585f009-a57c-4241-8f23-934c0d15427f.png)  |

[Production-ready file in figma](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/[OC-Design]-Production-Ready-✅?node-id=14262%3A165017)

**Comment by znarf** [comment]
This week. Last round of feedback, merge and deploy.
