### ISSUE TITLE
OCF custom email templates

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4721]
We would like to have custom email templates for OCF, like we've done for OSC and SCN, i.e. an OCF version of:

* `collective.approved.hbs`
* `onboarding.day2.hbs`
* `onboarding.day3.hbs`

We already have `thankyou.foundation.hbs` which is great.

If a developer can create the hbs files (just copying the content of the standard ones) and do the code that tells the app to send the OCF ones for OCF Collectives, I can submit a pull request to update the content myself.

**Comment by alanna** [comment]
@znarf can you please confirm: Are 'onboarding.day2.foundation.hbs' and 'onboarding.day3.foundation.hbs' sent on day 2 since the Collective was created, or day 2 since the Collective joined OCF? Ideally it would be on day 2 since they joined OCF for our purposes.

**Comment by znarf** [comment]
Onboarding emails are sent Daily at 5:00 AM UTC.

So for example, this morning we ran:

```
Oct 01 05:03:58 opencollective-prod-api app/scheduler.7513 >>> onboarding.day2 (from 2021-09-29 to 2021-09-30)
```

Reaching all collectives created on the day 2021-09-29 (between 2021-09-29 00:00 and 2021-09-30 00:00)

**Comment by alanna** [comment]
@znarf my question was: is it counting from time of Collective creation or time of host approval?
