### ISSUE TITLE
expense buttons not showing up

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#473]
I log in with my user address (I am logged in with username and avatar showing well) go to /expenses and approve/reject buttons are not showing.
Console shows no error. 
<img width="1172" alt="screen shot 2017-10-09 at 10 37 39 am" src="https://user-images.githubusercontent.com/3671070/31343554-f4256562-acdd-11e7-9173-1dd412a0d361.png">
<img width="518" alt="screen shot 2017-10-09 at 10 38 05 am" src="https://user-images.githubusercontent.com/3671070/31343555-f42acef8-acdd-11e7-910d-2dd9e7c515ce.png">

I approve manually from data base: Approved button not showing. 
Log out, log-in as a host I can see the PAID button. 
Tested again incognito window. Same result. Console log is clean. 
Log in with host: approve/reject buttons appear

Tobias reports: 

> There is no way to approve/reject expenses in the new Frontend. It looks like this feature is not even included in the graphql API (I didn't found a mutation for this feature).
> 
> There is a link to the old frontend expenses page (https://opencollective.com/webpack/expenses) but this neither allows me to approve expenses. I can't even view the expensive pdf via the frontend.
> 
> I was able to view the pdf via direct call to the API: /api/groups/webpack/expenses but calling the approve API via /api/groups/302/expenses/xxxx/approve gave me a permission error:
> {"error":{
> "code":401,
> "type":"unauthorized",
> "message":"User is not authenticated"
> }}
> 
> This is serious because we can no longer pay our contributors!

**Comment by xdamman** [comment]
Fixed. Can you confirm and close the issue?

**Comment by piamancini** [comment]
fixed.
