### ISSUE TITLE
Legal name help text missing

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4730]
<img width="818" alt="Screen Shot 2021-09-23 at 2 33 50 PM" src="https://user-images.githubusercontent.com/5498878/134447093-966eeb8e-6ca3-4481-89ca-508290cf07ba.png">

I recently updated the text in https://github.com/opencollective/opencollective-frontend/pull/6883 but now it's not showing at all?

**Comment by SudharakaP** [comment]
@alanna : Sorry, this was a mistake that I introduced in that PR. Anyways I've corrected it and tomorrow we'll get this to production. 👍🏽
