### ISSUE TITLE
Set amount in destination currency for Wise transfers

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4731]
The Wise interface is set up to enable you to set the amount in either the starting or destination currency, so maybe we could have a similar option?

<img width="479" alt="Screen Shot 2021-09-23 at 4 56 10 PM" src="https://user-images.githubusercontent.com/5498878/134456554-0e487773-934f-41e6-9544-56ba058a4076.png">

This came up because a Collective has an invoice to pay from a supplier in another country. If they don't send the exact amount, the supplier will have to process a debit or credit on their account and it creates an admin headache. Our only solution now is to send the transfer manually in Wise, but that's not scalable as it's a time consuming process.

I wasn't sure if this is the same as #1182

**Comment by Betree** [comment]
@alanna The way to solve this is something we talked about in the past but I could not find an issue for it: letting users pick the currency of their expenses. It's a big project and we should start tracking it (here?). We can already feel the need for it for the core team: all of us get paid in different currencies than USD, and it would be great if we could specify the exact amount that we intend to receive.

**Comment by alanna** [comment]
@Betree should we close this in favor of #5146 ?

**Comment by Betree** [comment]
https://github.com/opencollective/opencollective/issues/5146 will resolve this. I was waiting to have the project documented & enabled for more people before closing its attached issues, but feel free to close now if you think it's the right thing to do.

**Comment by Betree** [comment]
Resolved by https://github.com/opencollective/opencollective/issues/5146
