### ISSUE TITLE
Navigating from a collective page to another should scroll top

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4736]
See the screencast below. To test it simply create a project and click on its "See more" button.

![Peek 2021-09-24 09-13](https://user-images.githubusercontent.com/1556356/134633715-e49ad4b6-2b53-4955-ba4e-13fe82ab2856.gif)

**Comment by Nonna-source** [comment]
I am new to coding, however after some review and research - it would appear that if we add an anchor link that would solve the issue. I am not confident to do it on my own without some guidance. My coding skills are rudimentary and self taught. Here is a link to what I am referring to: ([https://www.w3docs.com/snippets/html/how-to-create-an-anchor-link-to-jump-to-a-specific-part-of-a-page.html])

**Comment by Betree** [comment]
Hi @Nonna-source, it's a good issue to start with! We're using NextJs and React, for us the solution will more probably be to detect the collective change in the page's `componentDidUpdate` and to trigger a `window.scrollTo(0, 0)` when that happens, but feel free to explore other solutions and ideas.

The only repository you'll need to get started is https://github.com/opencollective/opencollective-frontend

**Comment by JoyLubega** [comment]
Hi @Betree  It seems this issue is fixed 
https://www.loom.com/share/7f26a0ffc85644079834a654c8acefa1

**Comment by SudharakaP** [comment]
This should only happy on Firefox and I've made a fix for this at, https://github.com/opencollective/opencollective-frontend/pull/7363
