### ISSUE TITLE
collectives not yet approved able to receive donations

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#474]
See for example: https://opencollective.com/vue-bangalore 
CollectiveID host is 772 (open source, this happens automatically)
IsActive: marked as FALSE 
Collective has $2 in donations

**Comment by piamancini** [comment]
Also, I just changed the host of https://opencollective.com/hacklabto to 254 (hostdemo, no stripe account) and no reference to lack of host when trying to donate: https://opencollective.com/hacklabto/order/1861 IsActive also FALSE

But: 
This one that has the 772 host, also set to IsActive FALSE, has the no host notice: https://opencollective.com/erxes/order/1864

**Comment by xdamman** [comment]
The API will now return an error but we probably want to show something to the user before they place an order. What would you like to see? Maybe disable the contribute button under the tiers with a message below that says that this collective is not active yet?

**Comment by piamancini** [comment]
yep, disable the button would work. I would say: doesn't have a Stripe account connected to receive donations. This will encourage connecting one. what do you think?
