### ISSUE TITLE
Host can toggle grants on or off at Collective and Project level

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4741]
OCF has recently launched its grantmaking policy, which involves holding grants in Projects and paying them out via grant expenses. We need a way to turn on and off the grant expenses option at the Project level.

![Screen Shot 2021-09-15 at 5 42 02 PM](https://user-images.githubusercontent.com/5498878/134822451-c3cc66ec-932f-4ef1-9767-1a2841cbf18c.jpg)

I suggest this setting could be added on the 'hosted collectives' tab on the dashboard, if we're ok adding Projects there, or maybe in the Project's action menu, for hosts only?

![133712070-dac95dd9-1bf6-491b-b1cc-729c28158763](https://user-images.githubusercontent.com/5498878/134822541-c5793da7-4381-407e-952c-8c960ca31f9e.jpeg)

I think this setting should be independent of the parent-child relationship, i..e just because a Collective has grants on doesn't mean its Projects should, and vice versa. For OCF it's important that *only* host-approved Projects have grant expenses active.

**Comment by alanna** [comment]
In an ideal world we'd also be able to turn *off* the other expense types but we can work with it if that's not possible.

**Comment by Betree** [comment]
We know that hosts sometimes want to edit certain settings for their collectives. Having a modal for that here could be nice.

The second button already has a "Settings" icon, so maybe we should just upgrade the "Host fee structure" modal to be a "Account settings" modal and add it there? @opencollective/design wdyt?

![image](https://user-images.githubusercontent.com/1556356/134863945-1cb3b4f6-977c-4661-bf97-15bac664faf0.png)

**Comment by alanna** [comment]
Yeah that sounds fine - any design that allows host admins to change the setting will work. If it's hard to design, put it in root admin dashboard for now.

**Comment by znarf** [comment]
@SudharakaP what is the status for this issue?

**Comment by SudharakaP** [comment]
> @SudharakaP what is the status for this issue?

Was discussing about deploying this issue with Benjamin yesterday and how to make sure we enable it for the two collectives. It's clarified now and will deploy it today. 😃
