### ISSUE TITLE
Add Check in Front End for Minimum Amounts for Each Crypto Currency

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4744]
It caught my attention when working on another issue that the [List Currencies endpoint in TGB](https://app.gitbook.com/@the-giving-block/s/public-api-documentation/endpoints-documentation#list-currencies) also returns the minimum amount for each currency that is supported by the Giving Block. 

I think we should add this check to front end such that if the user enters an amount less than the minimum supported amount for that currency the user should see an error/warning indicating that and we should not them go further in the crypto flow. 

Currently it seems that the deposit address could be generated/viewed for an amount less than the min amount for a currently. For example BAT has min amount 1. But when we enter 0.5 we get,

![image](https://user-images.githubusercontent.com/12435965/134931304-436ad706-91cf-48e2-8559-807d2e23208a.png)

I don't know what happens in The Giving Block side when the transaction tries to be reconciled; it seems that the API allows the creation of the deposit address (thus implying a deposit is possible) even when the amount is less than the minimum as the above screenshot shows. But for good measure, I think we should restrict the user on our side on the front-end at least. 

cc: @znarf @kewitz

**Comment by znarf** [comment]
Why not, we can add a new property in our list of crypto currencies and use this for validation. I would avoid doing anything fancy/dynamic.

**Comment by kewitz** [comment]
If you're using Formik you can add a custom validation function to the `Field` component to check this.
