### ISSUE TITLE
Broken Images in the Transactions Section in Documentation

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4748]
It seems that some of the image links are broken in the Transactions section in our documentation; https://docs.opencollective.com/help/collectives/budget#migrating-your-transactions-to-a-spreadsheet. This is perhaps also related to what is mentioned here; https://opencollective.freshdesk.com/a/tickets/37457. 🤔 🙂 

cc: @shannondwray

**Comment by shannondwray** [comment]
Posted in teams chat in Slack to see if anyone can help: Does anyone know anything about/made this spreadsheet for importing your collectives transactions into? The images to describe what to do, settings to press etc have expired off the docs. So just looking for any guidance if anyone has any background. If not I might have to completely remove this section from the docs. https://docs.google.com/spreadsheets/d/1myLWSwe1ksOL42sENbKEafEfU4c3O1u-Yvz_3dLgRqo/edit?usp=sharing  https://docs.opencollective.com/help/collectives/budget
