### ISSUE TITLE
Add Link to own profile in user menu

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4749]
Currently it seems that users don't have the ability to access their own profile page quickly from our homepage. When the user logs in, one of the obvious places that the user should be able to click on is their own profile picture or the profile name under the drop-down and I think ideally that should link to their own page. 

![image](https://user-images.githubusercontent.com/12435965/135204632-57bd0f3b-3053-488b-bdcf-5a62571b59ae.png)

I feel this is useful since they might want to quickly add the long description (about section) in their profile page. So currently the way they might do it will be to go to settings and then click on the profile picture or maybe directly typing their profile slug on the url bar (if they know it). 🤔 

Suggestion: Simple solution is to add a link from the profile picture under the settings drop-down which links to their profile page.

![image](https://user-images.githubusercontent.com/12435965/135205111-23307d7d-9c98-4a57-8c11-efdf94ad9434.png)

Let me know if you agree with this or if you have any other suggestions. 😄 

@opencollective/design @Betree

**Comment by Betree** [comment]
Good catch, it's not only from the home page, all of them are impacted. Avatar + name should definitely be clickable and link to your personal profile page.

**Comment by aminakazi** [comment]
I agree with @Betree as the quick solution!
> Avatar + name should definitely be clickable and link to your personal profile page.

However it can be a little elusive and if we want to be super clear, we could do something like this. 
<img width="642" alt="Profile Button" src="https://user-images.githubusercontent.com/48468919/135267077-16fc9ca5-7935-4ce5-844e-9b77fbd41db8.png">
