### ISSUE TITLE
Confusing UX leading to expense not being invited

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4751]
## Who is your user?
Expense inviter

## What are they trying to achieve?
Invite an expense so they can make the process easier for payees that are new to OC

## How are they currently doing this?

They go to invite expense and put in the new user's info and click next:

![Screen Shot 2021-09-30 at 9 21 30 AM](https://user-images.githubusercontent.com/5498878/135342969-231d29fa-7847-4d08-8498-0d9783f7c9d6.png)

Then they see this screen:

![Screen Shot 2021-09-30 at 9 21 39 AM](https://user-images.githubusercontent.com/5498878/135343014-4e8978d8-7d9a-4b03-9d5a-53f5fb929aed.png)

This screen has no action buttons. The inviter thinks "OK, I already put the user's info in and pressed the button so they have already been invited".

There is no indication that what they need to do is write a title and then a whole lot more fields will appear. Even if they do reveal these hidden fields, the actual action button `invite expense` is hidden at the bottom of the screen past the fold and they can *still* miss it.

![Screen Shot 2021-09-30 at 9 24 23 AM](https://user-images.githubusercontent.com/5498878/135343701-d25b0faf-aa83-4600-853d-57eeaa7f04ed.png)

The user I spoke to invited many expenses but the payee was never actually invited and it was incredibly frustrating for them.

Why are all the fields hidden until they add a title? We should reveal them all up front. But then we still need to make it clearer that there is another button off the bottom of the screen they need to click to complete the process.

**Comment by Betree** [comment]
I have seen similar feedback in the past. There is no call to action, and the title input doesn't look like a normal input. Altogether, it's easy to miss it and end up wondering what you should do next.

**Comment by alanna** [comment]
Quick thing that could help while we work on a more complex solution: just don't do the odd thing where it hides form fields until you input a title. Show all the fields on the second screen from the start.

**Comment by BenJam** [comment]
plan for this week

- [ ] work on the small modification (not hiding the whole form)  — @Memo-Es to follow up
