### ISSUE TITLE
Separate Independent Collective activation email

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4754]
## User story 
As a newly activated Independent Collective, I need information specific to my use case, so that I can use the platform effectively without needing hands-on support.

## Best solution for this problem
When an Independent Collective activates, send them a different version of an email like `activated.collective.as.host.hbs` but with different content (e.g. link to the Independent Collective section of the docs, no link to book a call with Pia). If the template can be created with the correct triggers coded, I can handle creating the content myself.

## Metrics 
Fewer support requests

## Note
We should still keep an email like `activated.collective.as.host.hbs` for new Fiscal Hosts, but we probably need to clarify the two situations:

1. Independent Collective: Starts as a Collective, selects "ourselves" as the hosting option, sees limited host-related settings in their menu, not possible to have multiple Collectives or charge a Host Fee.
2. Fiscal Host: Has an Organization profile linked, access full Host Dashboard, can charge host fees, can have multiple hosted Collectives.

I want to send separate onboarding emails to each of these types.

**Comment by alanna** [comment]
@znarf @Betree - would this be hard to do? If it's easy and expected to be implemented in the short term, I will create a demo video to link from the email. If not I won't put the time into that now.

**Comment by alanna** [comment]
Great! I'll make a pull request to update the content.

**Comment by Betree** [comment]
@alanna If I merge this we will start sending the email right away. Is this what we want? If we prefer to update the copy first, feel free to post the content here as a comment (formatting is ok) and I'll update the template.

**Comment by alanna** [comment]
OK I will create the content tomorrow and post it here.

**Comment by alanna** [comment]
@Betree here is the content....

---------------

` Subject: Independent Collective Activated — Welcome!`

`{{> header}}`

`<p>Hi {{collective.name}} 👋</p>`

`<p>You've activated your Independent Collective and you're ready to start receiving contributions. That's great! Here are some useful tips to help you get started.</p>`

`<ul>`
`<li><a href="https://docs.opencollective.com/help/independent-collectives/set-up-independent-collective">Get set up:</a> Ensure receipts get correctly generated with your entity info, and connect your Stripe and bank account.</li>`
`<li><a href="https://docs.opencollective.com/help/independent-collectives/manage-independent-collective/money-coming-in-contributions">Manage money coming in:</a> How to confirm pending bank transfers and add funds manually.</li>`
`<li><a href="https://docs.opencollective.com/help/independent-collectives/manage-independent-collective/money-going-out-expenses">Manage money going out:</a> All about expenses and payouts.`
`</ul>`

`<p>If you have questions, you're welcome to <a href="https://slack.opencollective.com">join our Slack</a>, email support@opencollective.com, or check out the <a href="https://docs.opencollective.com">Open Collective documentation</a>.`

`<p>the Open Collective Team</p>`

`{{> footer}}`

**Comment by Betree** [comment]
@alanna Done, here's how the email looks like. Lmk if that's all good for you and I'll ship it:

![image](https://user-images.githubusercontent.com/1556356/140021951-ac180bbc-7860-4cf2-bafd-f25f8cdba6d5.png)

**Comment by alanna** [comment]
Looks good!
