### ISSUE TITLE
Date picker design update

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4757]
The latest design acknowledges the new Timezone picker. The tooltip content has also been updated.
See https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab?node-id=12357%3A180443

![image](https://user-images.githubusercontent.com/1556356/135622381-3a005031-f12e-428d-b8d7-fa3ce98dff82.png)

**Comment by aminakazi** [comment]
The tooltip content is such:

> By default, all dates are filtered according to your local timezone. Switching to UTC will indicate that the dates provided match the coordinated universal time format, also used to generate email reports

Feel free to edit it! :)

**Comment by Betree** [comment]
This has been implemented as the [`PeriodFilter`](https://github.com/opencollective/opencollective-frontend/blob/b14156e76c5d806716266b4cb9241ef12db2ede8/components/budget/filters/PeriodFilter.js) in
