### ISSUE TITLE
Ampersand not rendering in email subject

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4758]
<img width="809" alt="Screen Shot 2021-10-02 at 2 19 02 PM" src="https://user-images.githubusercontent.com/5498878/135699406-cbeabf74-7bfb-4bb2-8567-46a4f89b6a90.png">

**Comment by alanna** [comment]
This is still happening

**Comment by Betree** [comment]
I started a fix in https://github.com/opencollective/opencollective-api/pull/6700 but there's still some work to do on fixing unit tests
