### ISSUE TITLE
Display tags on the search page

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4759]
## User story 
As a user seeking a Collective, Host, or anything on the OC platform, I want to use tags to help narrow down results accurately.

## Best solution for this problem
Add a tags option on the /search page

Subset of #3892

**Comment by Betree** [comment]
Tags are already considered when searching. For example, https://opencollective.com/search?q=hacktoberfest returns multiple collectives that have the `hacktoberfest` tag.

**Comment by kaylarep** [comment]
would love to see the tags appear here on the initiatives' cards whenever that card pops up in searches or in the contributions section

maybe just the top 3 tags or something, so it doesn't get overcrowded?

![image](https://user-images.githubusercontent.com/64920686/137548322-d211e48d-f18c-49cd-b04d-a2b6ac795091.png)

**Comment by Betree** [comment]
@kaylarep That sounds like a simple & useful change. @opencollective/design any concert with that approach?

**Comment by BenJam** [comment]
I am starting to be of the belief that the search redesign is one of the most impactful things we would work on in '22...

**Comment by Betree** [comment]
Edited the issue title to make https://github.com/opencollective/opencollective/issues/4759#issuecomment-933223911 more explicit: searching by tags is already supported but we're not showing them on the collective cards.

**Comment by kaylarep** [comment]
Not sure if this should be a separate issue, but having a 'cloud' displaying the most frequently-used tags on the right side of the search results page would be really useful too.  maybe with a little hyperlink at the bottom of the cloud linking to a page in the docs about 'Tagging Your Collective'

**Comment by alanna** [comment]
Just to clarify, I think we need to not only show tags on the cards in the results, but allow people to actively use tags for filtering. I need to be able to search Collectives in `chicago` that are also `mutual aid`, and to search Hosts in `UK` that are also `charity`.

**Comment by Memo-Es** [comment]
## Add tags to Collective creation form

| Empty | Filled | Adding tag |
|-----------------|----------------|------------------------------|
|   ![Form](https://user-images.githubusercontent.com/49539954/158474968-c9383062-3fae-4b97-b514-b3693d0816bb.png)     |  ![Form-1](https://user-images.githubusercontent.com/49539954/158474962-c6387ead-9edb-4c5e-9ebc-bfbe016e93f6.png)    |  ![Form-2](https://user-images.githubusercontent.com/49539954/158474967-c3741c58-5839-40a5-94db-cb027327b8fd.png)    |

[Figma file reference](https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab?node-id=14425%3A219354)

* Part of https://github.com/opencollective/opencollective/issues/4295

@kaylarep @SudharakaP @alanna

**Comment by alanna** [comment]
Oh great, if adding tags during creation is in scope, I take back what I said before about leaving it out. It would definitely be best to let Collective do this during creation, and give them some suggestions of common tags. If we can capture their location that could be good in creation as well, though we don't want to overload this step.

**Comment by SudharakaP** [comment]
The comments expressed in this issue can be subdivided into three; 

- Adding tags to collective cards; done at, https://github.com/opencollective/opencollective/issues/5316
- Adding tag filters to `/search` page; in progress at, https://github.com/opencollective/opencollective/issues/5333
- Adding tags to the collective creation page; https://github.com/opencollective/opencollective/issues/4764

Thus I am closing this issue as everything here is encompassed by those issues.
