### ISSUE TITLE
Accomodate links that aren't collective-specific

### ISSUE THREAD

**Issue by patcon** [opencollective/opencollective#476]
I noted that this documentation page needs an update: https://forum.opencollective.com/t/how-to-manually-add-funds-to-my-collective/64

Seems that the expenses link now 404's, and is replaced with `https://opencollective.com/<collective-slug>/expenses`. (This is SUPER rad btw, and I'm totally appreciative that the platform now easily accommodates managing multiple collectives!)

But it might still be nice if generic urls still resolve to your collective somehow, when logged in. This would allow documentation to be much more straight-forward and hand-holdy in pointing people to the right places :)

For example, Slack has this nice feature where they redirect my.slack.com to the Slack subdomain that you were most recently active on (presumably that's the resolution strategy, but haven't tested).

Thanks for hearing this out!

**Comment by piamancini** [comment]
@nicobarretoOC The forum is not clear on this. It should be opencollective.com/:slug/expenses and make it clear only the host user has that functionality

**Comment by nicobarretoOC** [comment]
Thanks for the feedback @patcon ! I have edited this on both, the wiki and the forum.

**Comment by patcon** [comment]
Just wanted to bump this for re-openning in light of the links in this post: https://medium.com/open-collective/whats-your-collective-s-expense-policy-c14e288567a7

Still think it would be cool if there was a special reserved namespace (eg. `mycollective` for redirecting people to their own collectives from doc links like this: https://opencollective.com/mycollective/edit#expenses
