### ISSUE TITLE
Suggest (or force) tags during Collective creation

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4764]
Rich tags on Collectives would greatly improve search and discovery. 

When you sign up to Pinterest you're forced to choose categories you're interested in:

<img width="596" alt="Screen Shot 2021-10-02 at 5 08 21 PM" src="https://user-images.githubusercontent.com/5498878/135703172-4f5951c9-2fe2-4434-8814-07c2c5281989.png">

We could do something similar when a Collective is being created.

**Comment by kaylarep** [comment]
should definitely have the options to `Skip tagging` at the bottom of this for groups who don't want any tags

**Comment by SudharakaP** [comment]
Just for reference the figma file for this is given at, https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab?node-id=14425%3A219354

Issue Reference comment: https://github.com/opencollective/opencollective/issues/4759#issuecomment-1068488063

**Comment by Memo-Es** [comment]
### Notes from the kick-off call

**Tags**
 - Should we add a sidebar with additional information? (What is a Collective? Why are tags necessary? About location
 - We should suggest existing tags while the user is typing, adding the opportunity to create new tags
 
 **Location**
 - The location field should work with tags, with the possibility of adding more than one location tag
 - We should reproduce the autocomplete behavior used on [events creation](https://d.pr/i/rf6fm4)
 - There should be 'online' and 'international' options to add as location tags
 
 **Existing Collectives**
 - We agreed to a solution for existing Collectives to use the tags/location feature by adding a banner to all those who are not tagged yet with a message including a link to their settings (Copywriting pending)
 - We should add a 'dismiss' button but make the banner appears again in one week

@SudharakaP @BenJam

**Comment by Betree** [comment]
@Memo-Es Sorry I couldn't be there for the kickoff call; I'm not there on Wednesday afternoons. I'm surprised by:

> The location field should work with tags, with the possibility of adding more than one location tag

It's a significant change to our data model **or** to how we query location (e.g. in search). Could you share some more context about this - why do we need multiple locations? Is this going to live among other tags, or are these special tags that live elsewhere?

**Comment by Memo-Es** [comment]
@Betree No need to apologize :) 
About the context around the location based on tags, it was a suggestion by @kewitz based on the discussion we had of allowing more than one location. For example, a Collective operating in Central Europe but with impact in Ukraine or a Collective like us distributed in different countries, and nevertheless, we appear US-based...

I'm happy to discuss this further; I will bring it up in tomorrow's demo; feel free to let me know your thoughts before then.

**Comment by Memo-Es** [comment]
Goals for Week 2:

- [ ] Start implementation cc @SudharakaP Production files [here](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=16508%3A240862)

**Comment by SudharakaP** [comment]
Some comments from @kaylarep originally posted at, https://github.com/opencollective/opencollective-frontend/pull/7750#issuecomment-1116712618

> hio, sorry to chime in late here, but a couple points of feedback (it's looking great so far!):
> 
>     * Is it possible to give users the option to re-order the tags after selecting them?
>       
>       * this is important because some collectives may be picky about which tags appear on their card that comes up in the general 'Search' page. I would assume it would be the first 3-4 tags will appear on the card- is that accurate?
>         
>         * also is it worth including that information somewhere? (e.g. "The first 3 tags listed will be displayed on your card in the Search") -> i think if reordering is possible, this line isn't necessary.
> 
>     * at the drop-down (~00:57 mark in the video), would it possible to have **all** the tags appear in the scrollable list? (probably sorted by popularity)
>       
>       * i think this is a much more realistic approach than to expect all groups to know exactly how they want to label themselves/what language to use. if they see tags that align, they can just select them + makes it easier to find the community in that same tag; + they might find popular tags they align with they hadn't considered previously
> 
>     * as a side note: (and for the same reasons listed above)
>       
>       * i'd love to see more tags listed on the 'Search' page (00:22), or have the list of tags be scrollable. When I am searching on websites, it's much more natural for me to click and select everything that applies, than to brainstorm and manually enter words

**Comment by kaylarep** [comment]
[from ](https://opencollective.slack.com/archives/C020ZQSLM5M/p1651618679617749?thread_ts=1651613855.566049&cid=C020ZQSLM5M)@alanna 
> This is probably out of scope, but people will definitely miss that the text box is to create a new tag instead of search existing tags. Ideal behavior would be the box searches existing and if none, creates a new one. What happens now if someone types out an already existing tag in that box? does it just add it, or create a dup? I hope it’s case and punctuation insensitive, otherwise we’ll have opensource open source Open Source OpenSource as all different tags.

**Comment by Memo-Es** [comment]
@SudharakaP The comment above talks about the behavior I proposed with the custom component, can we add that searching feature to the tag creation dialog?

**Comment by SudharakaP** [comment]
@kaylarep :

>     * Is it possible to give users the option to re-order the tags after selecting them?
>       
>       * this is important because some collectives may be picky about which tags appear on their card that comes up in the general 'Search' page. I would assume it would be the first 3-4 tags will appear on the card- is that accurate?

Yes it's the first 4 tags that we show. 
        
>         * also is it worth including that information somewhere? (e.g. "The first 3 tags listed will be displayed on your card in the Search") -> i think if reordering is possible, this line isn't necessary.

This one we could iterate in the future; https://github.com/opencollective/opencollective/issues/5522. But I am wondering if users will know automatically that the first three tags will appear in the the search page collective cards, even if re-ordering is possible. So I would suggest adding this line anyways below the tag creation. Something like this? @Memo-Es @kaylarep 

![image](https://user-images.githubusercontent.com/12435965/166721774-75e2ce10-710e-4c56-a9a8-324b08c4901b.png)

>     * at the drop-down (~00:57 mark in the video), would it possible to have **all** the tags appear in the scrollable list? (probably sorted by popularity)
>       
>       * i think this is a much more realistic approach than to expect all groups to know exactly how they want to label themselves/what language to use. if they see tags that align, they can just select them + makes it easier to find the community in that same tag; + they might find popular tags they align with they hadn't considered previously

That's possible, but I would suggest having a upper limit to not show any spam tags. Maybe the first 50 or 100 will be a good limit I think (currently we only show 10). I feel users will not tend to go through the list beyond that anyways if the list is too long so showing all the tags might not be useful. WDYT? 🤔 

>     * as a side note: (and for the same reasons listed above)
>       
>       * i'd love to see more tags listed on the 'Search' page (00:22), or have the list of tags be scrollable. When I am searching on websites, it's much more natural for me to click and select everything that applies, than to brainstorm and manually enter words

For this one I've created an issue; https://github.com/opencollective/opencollective/issues/5521. We'll iterate on this.

**Comment by SudharakaP** [comment]
> @SudharakaP The comment above talks about the behavior I proposed with the custom component, can we add that searching feature to the tag creation dialog?

I think this is possible but I've created a separate issue to discuss and implement this one; https://github.com/opencollective/opencollective/issues/5523.

**Comment by kaylarep** [comment]
@SudharakaP 
>Maybe the first 50 or 100 will be a good limit I think (currently we only show 10). I feel users will not tend to go through the list beyond that anyways if the list is too long so showing all the tags might not be useful. WDYT? thinking

makes sense, could say 75 as a happy medium?  or you could do the same thing as you've proposed in  https://github.com/opencollective/opencollective/issues/5523 and have the 'see more' option + allowing them to click 'see more' as much as they'd like.
---
Is it possible to have the suggested tags live reload once 1 tag has been added to show suggestions that are related to the selected tags? (let me know if this question makes sense)
e.g. if a group selects 'food' as their primary tag, the next suggested tags to appear would be 'fridge' 'mutual aid' or whatever else other groups with similar tagging have used.

**Comment by BenJam** [comment]
Q2S1W3

- [ ] merge PRs 
- [ ] document and follow-on improvements (as issues/papercuts)
