### ISSUE TITLE
🔥 for new users

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4768]
When a new user joins OC for the first time, they already get a 🔥 because they haven't seen any of them yet. Why not add one more that links out to a new users how-to help page introducing the main features? And/or embed a video walkthrough. This could also be good for users who do certain actions, like create their first Collective, make their first Contribution, etc, which would be specifically about what someone in the moment needs to know.

**Comment by SudharakaP** [comment]
My vote is if we decide to add this, we probably need to add a dedicated modal for this. I would love to see something similar to the experience users have after creating a new collective. We show a modal which lets the user to add admins and setup their social accounts etc. 😄 

![image](https://user-images.githubusercontent.com/12435965/135704265-6de0e6e8-1c31-41d0-bdb0-2f5f32504945.png)

In the same way we could show a modal welcoming them and add the links to the docs (how-to) and stuff there. 

The 🔥 notifications could be not seen unless the user clicks on the icon (and I think this warrants something that is a bit more front and center) and also it's a bit problematic as we have to keep track if it's a new user and show this notification at the top of the notification stack and after the user view it probably reset it back to the place it belongs. 🤔 

Anyways I am open to suggestions. 😄 

cc: @Betree @opencollective/design

**Comment by BenJam** [comment]
taking this work over to #4829

**Comment by minhdient49** [comment]
[]() https://truongminhdien833@gmail.com > taking this work over to #4829
