### ISSUE TITLE
Make currency clear when submitting expenses

### ISSUE THREAD

**Issue by kentcb** [opencollective/opencollective#477]
The expenses submission screen does not mention currency. As a result, it's easy to overlook that it's USD. Ideally one would be forced to _choose_ a currency so no mistakes can be made, with the system performing any necessary conversions. At the very least though, it should be clear that USD are being used.

**Comment by piamancini** [comment]
thanks for the feedback Kent! We'll be working on expenses next. 
cc/ @asood123
