### ISSUE TITLE
Add expense submitted status update

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4771]
The expense status updates are meant to tell the story of the life of the expense. It's weird that all of them are in the comment flow, but there's no status update for `expense submitted`. To see that you have to look in a different place. It would be helpful to have an expense submitted update in the flow with the others.

<img width="348" alt="Screen Shot 2021-10-04 at 9 09 20 AM" src="https://user-images.githubusercontent.com/5498878/135769931-f47540bd-5b50-4431-b22c-a40a5363dbb6.png">

<img width="402" alt="Screen Shot 2021-10-04 at 9 09 26 AM" src="https://user-images.githubusercontent.com/5498878/135769934-78a4dfc8-113d-4a41-9d0f-20183a69edc6.png">

**Comment by Betree** [comment]
We had everything we needed in the frontend, so I simply added the activity in https://github.com/opencollective/opencollective-frontend/pull/6961
