### ISSUE TITLE
Don't show the contribute header if contributions are not enabled

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4773]
It looks really odd to have a call to action saying "Become a financial contributor" but there's no way to contribute.

![Screen Shot 2021-10-04 at 3 09 59 PM](https://user-images.githubusercontent.com/5498878/135783673-fc7eed87-8975-4fa3-b108-7c4c0128ea5a.png)

This example is https://opencollective.com/liminal-lab but I think this is the case for all Collectives without hosting set up.

**Comment by Betree** [comment]
Moreover, showing the contributors grid doesn't make sense if there are no financial contributors. We already have the "Team" section to show team members.

**Comment by alanna** [comment]
It would be great to fix this. I keep running into it and it makes the page look confusing.

![Screen Shot 2021-11-03 at 11 42 14 AM](https://user-images.githubusercontent.com/5498878/139961806-54ba5e6e-8280-440c-bc91-32df7251535f.png)
