### ISSUE TITLE
Do not Let User Add Funds from a Collective to the Same Collective

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4778]
This was reported at https://opencollective.slack.com/archives/C0HSLRNVC/p1633366682190600 initially. It seems that in the add funds modal we let the user select the same collective in the source drop-down; thus enabling the user to add funds from a collective to itself; 

![image](https://user-images.githubusercontent.com/12435965/135905633-e132692c-5dda-4241-b1f0-062d6375b652.png)

I think we should not show the same collective in the source selection as doing this doesn't seem to make sense. 🤔

**Comment by znarf** [comment]
It's supported.

**Comment by SudharakaP** [comment]
> It's supported. It's useful to unblock situations where there is no obvious source of the funds.

Ah I see, thanks for the explanation; that makes sense. I'll report that back in the slack. 👍🏽
