### ISSUE TITLE
Open Collective Roadmap FY21Q4S1

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#4783]
Project board: https://github.com/opencollective/opencollective/projects/54

# Engineering Focussed

## Virtual card issuing with Stripe
**Owner:**: @znarf 
**Developer:** TBC
**Design**: TBC
**Tracking issue**: https://github.com/opencollective/opencollective/issues/4807
**Status**: 
**Goals:** Move virtual card transaction synchronisation to Stripe. 
**KPIs**: Reduce support time and impact on other Collectives when cards fail transactions.
**Benefits**: OC/OCF/OSC

## [Dashboard reports](https://github.com/opencollective/opencollective/projects/65#card-69297248)
**Owner:** @Betree 
**Developer**: @SudharakaP 
**Tracking issue(s)**: https://github.com/opencollective/opencollective/issues/4300
**Status:** 
**Goals:** Get to a release-ready version of the host dashbaord
**KPIs:** Provide hosts with a clearer picture of their finances.
**Benefits**: OC/OCF/OSC ↺

## Improve CSV Export
**Owner:**: @znarf 
**Developer**: @znarf 
**Tracking issue**: https://github.com/opencollective/opencollective/issues/4590
**Status**: 
**Goals**: Iterate on feedback from accountants, move process for accountants to use CSV
**KPIS**: Reduce the amount of time/complexity to work with our accountants. 
**Benefits**: OC/OCF/OSC ↺

## Differentiate Legal names
**Owner:**: @BenJam 
**Design**: @Memo-Es 
**Tracking issue(s)**: #4692 #4752 
**Status**: ✅
**Goals**: Implement legal name collection for contribution and registration flows.
**KPIS**: Reduce time spent hunting for details when accounts need to be filed. 
**Benefits**: OC/OCF/OSC 

## Add GDPR consents and notices to contribution flow
**Owner:**: @benjam
**Designer**: @aminakazi 
**Developer**: TBC
**Tracking issue**: https://github.com/opencollective/opencollective/issues/4537
**Status**: 💚
**Goals**: Announce breaking change, implement change, await feedback.
**Benefits**: OC

## Two to sign & multiple expense approvals
**Owner:**: @benjam
**Design**: @Memo-Es 
**Tracking issue(s)**: https://github.com/opencollective/opencollective/issues/3081, https://github.com/opencollective/opencollective/issues/3328
**Status**: 
**Goals**: Implement designs
**KPIs**: Reduce support time required. Reduce legal risks. 
**Benefits**: OC/OCF

## Expenses across hosts
**Owner:**: @znarf 
**Designer**: TBD
**Developer**: TBD
**Tracking issue**: TBC [(ref)](https://github.com/opencollective/opencollective/issues/4497)
**Status**: 
**Goals**: TBD
**Benefits**: OCF/OSC 

# Design Focused

## New Open Collective Homepage 
**Owner:**: @Memo-Es 
**Design**: @Memo-Es 
**Tracking issue(s)**: https://github.com/opencollective/opencollective/issues/4689
**Status**: 💚
**Goals**: Scope a project including the narrative - and how we land that narrative. 
**KPIS**: Increase conversion for host applications, host creation etc. decrease support time spent guiding folks to correct flow. 
**Benfits:** OC

## Improve Collective's ability to tell their story
**Owner:** @Memo-Es 
**Designer:**
**Tracking issue(s)**: #4767, #4763 
**Status**: 💚
**Goals**: Scope, spec and design implemented. 
**KPIs:** Increased activity (contribution, engagement inupdates etc) for collectives utlising.
**Benfits:** OCF/OSC/OC

## Improve user onboarding using 🔥
**Owner:** @Memo-Es 
**Designer:**
**Tracking issue(s)**: https://github.com/opencollective/opencollective/issues/4768
**Status**: 💚
**Goals**: Scope, spec and design implemented. 
**KPIs:** Reduce support enquiries and interventions 

## UX Improvments
**Owner:** @Memo-Es
**Design:** @Memo-Es @aminakazi 
**Tracking Issue(s)** #4751, #4760, #4750

### Status Key
💔  Problem
💛  Needs attention
💚  On track
✅. Completed

**Comment by Memo-Es** [comment]
@BenJam can we include this one?

Design small projects
Add projects and events to host dashboard
Confusing UX leading to expense not being invited #4751 (comment)
Collective page update
Users not finding contact under actions menu #4760
Create photo gallery as page section #4767
Add an embedded video as Collective page section #4763
Improve Truncation in the CollectivePicker.js #4750
🔥 for new users #4768
Transactions page design update

The other two, [visual documentation](https://github.com/opencollective/opencollective/discussions/4746#discussioncomment-1427800) and [DS update](https://github.com/opencollective/opencollective/discussions/4746#discussioncomment-1427806) can remain in the back-office since it only involves design and marketing, what do you think?

**Comment by BenJam** [comment]
@Memo-Es I've included #4726 in the dashboard reports, added top-line items for the storytelling (photos and video sections) and the user onboarding improvements (I think these will be useful efforts to track with proper projects) and left other bits in UX improvements. I hope that's cool.

**Comment by BenJam** [comment]
the adventure continues #4967

**Comment by BenJam** [comment]
reopening for retro...
