### ISSUE TITLE
sponsors/backers links are broken

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#479]
- [x] https://mochajs.org/#sponsors click on a sponsor/backer and leads to https://opencollective.com/undefined?utm_campaign=mochajs&utm_medium=github&utm_source=opencollective
@xdamman is this on mochajs side or a result of v2?

- [x] This problem was also referenced in this bug report: https://github.com/opencollective/opencollective-api/issues/937

- [x] VueJS just reported the same in an email. Links are broken on the readme. Backers not showing.

- [x] Same issue was reported here https://github.com/opencollective/opencollective-api/issues/943

**Comment by piamancini** [comment]
re-opening because it's not fixed.

**Comment by piamancini** [comment]
Same issue was reported here https://github.com/opencollective/opencollective-api/issues/943

**Comment by piamancini** [comment]
@xdamman can we close this an let users know it's fixed?

**Comment by piamancini** [comment]
@asood123 are you still working on the svgs? links in the bug reports are still broken. 
Vue and mochaJS are fixed.

**Comment by asood123** [comment]
I'm not sure what's going on. Looks like in some cases, the image server is never responding in time. Like here: https://github.com/gulpjs/gulp or here https://opencollective.com/gulpjs/backers/badge.svg.

**Comment by xdamman** [comment]
Fixed.
