### ISSUE TITLE
Use OpenCollective for PyPI owned by PSF

### ISSUE THREAD

**Issue by abitrolly** [opencollective/opencollective#4790]
## Who is your user?

https://pypi.org code contributors and sponsors (both individual and company based).

## What are they trying to achieve?

Improve Python package distribution mechanism, merge/review outstanding PRs. In particular, export metadata about PyPI packages without downloading them, document various levels of metadata, improve contributor experience. See aslo https://github.com/psf/fundable-packaging-improvements/blob/master/FUNDABLES.md

When new PR is submitted, I want the review/merge process to take no more than 7 days, so I can quickly iterate submit changes and switch to other things.

When https://pypi.org becomes understaffed, I want to see where current money are flowing, so that I can either submit automated solution (as a contributor) or provide funds to get more people onboard (as a sponsor).

When https://pypyi.org don't have capacity to review PRs, I want to make it visible for my company, so that they can sponsor reviews/merges of specific PRs.

When I want to see how good PyPI is faring, I want to use familiar interface and API of OpenCollective to do my reporting.

## How are they currently doing this?

Writing letters to PSF, asking in discord channels and in GitHub. Following https://twitter.com/pypi twitter.

## Question

It it possible for PSF (as U.S. based non-profit) to own projects, but still manage them using OpenCollective platform?

**Comment by alanna** [comment]
Hi @abitrolly - PSF can absolutely get set up as a fiscal host on the platform, and create Collectives while holding their money under its own umbrella. These Collectives can then use all the features for fundraising and financial tracking and transparency. The platform is also very useful to organizations like PSF for managing expense payouts and gathering documentation needed for accounting and reporting purposes. Please see this page for more info: https://opencollective.com/become-a-fiscal-host

**Comment by abitrolly** [comment]
@alanna thanks. I sent a letter to Phyllis @ PSF pointing to this thread, so hopefully somebody will jump in to discuss the topic directly. Or if I get the reply, I post it here,

**Comment by abitrolly** [comment]
Got this reply from Phyllis 4 days ago.

> Hello, Anatoli,
> 
> As I explained before, OpenCollective is another 501(c) organization in the US.  If the PSF (or PyPI as a project) opened up a Collective, we then become a legal subsidiary of another nonprofit.  Therefore, the PSF and our projects do not have Collectives and will not authorize opening one.  We cannot hold collectives for the PSF or any of our projects without creating a nearly impossible tax and legal situation in the United States. 
>
> --------------------------------------
> Thanks,
> 
> Phyllis A. Dobbs
> Controller
> Python Software Foundation

**Comment by abitrolly** [comment]
@di can you help to resolve this dispute as a @PSF director?

**Comment by pradyunsg** [comment]
Hiya folks! I'm not PSF staff/employee/board member/director, so I am not speaking on their behalf, but I am really familiar with how the PSF operates.

Given that OP got an official response from PSF staff, clearly expressing that there's no interest, is there any reason for this issue to stay open?

The PSF already has fairly robust mechanisms for fundraising, donations and sponsors. OP has literally linked to the PSF's Packaging-WG's fundable projects document, which is a working group in the PSF that has managed funding for multiple six-figure projects now (https://wiki.python.org/psf/PackagingWG).

**Comment by abitrolly** [comment]
@pradyunsg there is no official response from PSF. If you've seen the official response, please share a link. The private letter from Phyllis to me is not the offical public PSF response. Also, the response that just saying that the opponent is wrong and therefore its request should be dismissed, can hardly be acceptable to close the issue.

The PSF mechanism is not robust, because people from projects that PSF own can not raise crypto, can not use platforms like Gitcoin or OpenCollective for transparency, accounting, and fundraising for specific features. Even if people are not based in US, they still can't, because the Twitter is owned by PSF, and PSF doesn't make any moves towards crypto at all. Not everybody can afford to be a volunteer, and crypto is the easiest way to support those people. That's only one argument why PSF donation mechanism is not in any way robust for maintainers.

You're mentioned six-figure project. I wouldn't even start this thread if I could feel that $300000 raised for PyPI are not going into reviews of PR that are aimed to cut the hosting costs of infrastructure and make it more distributed. Asking a person to get more features into a self-sufficient PR up to the point that nobody can review it anymore and then abandoning it is not what I would call an effective sponsored work for a community. That's another counter argument for robustness of PSF proposed schemes to efficiently use targeted donations. The PSF rating is only 80% https://www.charitynavigator.org/ein/043594598 which is not something one would expect from an open source organization. 

OpenCollective features allow to donate specifically to PyPI and its subprojects, at the cost of limiting the freedom of using the donated fund to power marketing and fundraising efforts, and if PSF having a problem about that, I would definitely expect them to be open about that, except just dismissing requests to use crypto and/or platforms like OpenCollective without explanation.

**Comment by pradyunsg** [comment]
> In light of all of these resources, it doesn't really make sense to add the responsibility of managing another platform to the PSF staff's plate, whether or not the legal structures work out.

I'll reiterate that I think this should be closed. If the PSF wants to work with Open Collective, I'm sure someone from PSF staff will reach out directly.

**Comment by abitrolly** [comment]
@pradyunsg why PSF won't state their arguments officially and open in the public just like OpenCollective does? As you see, their private persuasion is quite unprofessional.

**Comment by Betree** [comment]
Closing as this seems to have been answered. Follow-up conversations (if any) should happen with the concerned fiscal hosts or the PSF community directly.

**Comment by abitrolly** [comment]
@Betree there is still no official answer from PSF, so technically the request is not being answered.

**Comment by Betree** [comment]
@abitrolly This repository tracks bugs and improvements to the Open Collective website. At this point, there's nothing we (the Open Collective engineering team) can do to help with your request. I would recommend that you contact the PSF directly.

**Comment by abitrolly** [comment]
@Betree I have contacted PSF directly as you can see above, but their claims are not backed up.

Halas! Let's just bury this and move on. Let PSF rest in peace. If they don't want transparency, its they own shady business. It has nothing to do with the brilliant Python community.
