### ISSUE TITLE
CharityNavigator rating for Open Collective entities

### ISSUE THREAD

**Issue by abitrolly** [opencollective/opencollective#4792]
When I explain people what Open Collective, I want them to find its reviews and ratings themselves, https://www.charitynavigator.org/ein/814004928

When I seek fiscal sponsor for my Open Source project, I want to know if Open Collective is trustworthy.

## How are they currently doing this?

Currently I just trust certain people.

**Comment by SudharakaP** [comment]
@alanna : Not sure if you are the right person to answer this but just pinging you in case. 😄

**Comment by alanna** [comment]
Yes absolutely. We'll make sure the page for OCF is updated as soon as
possible.
