### ISSUE TITLE
Remove 'assign/request a virtual card' options from projects

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#4797]
When we launched virtual cards we accidentally launched it for Projects as well as Collectives. 

There is a lot of value to having virtual cards assigned to projects as well as Collectives but it's not working at the moment and is (likely) untested:    

![image](https://user-images.githubusercontent.com/158833/136373982-f11df33a-6ecf-44be-9a0d-53d0b2845ada.png)

See above, assigning a virtual card only pulls the parent collective through as an admin.

**Comment by znarf** [comment]
We shipped [Virtual Card for projects and events.](https://github.com/opencollective/opencollective/issues/4798)
