### ISSUE TITLE
Virtual cards for Projects and Events

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#4798]
## User story 
As a Collective I want to use virtual cards with projects so I can move recurring expenditure from people working on the project and account for the project's budget more accurately. 

## Best solution for this problem
Implement the same functionality we have for virtual cards on Collectives for projects and events. 

## Current status
We accidentally rolled this out when we rolled out Virtual Cards for Collectives. But it's untested for projects and events...

In practice, this *mostly* works as is, at least projects appear to be able to request a card properly. However when we come to assign the card to a project, the picker to assign the card does not list administrators from the parent Collective:

![image](https://user-images.githubusercontent.com/158833/136375200-675ac263-d1c0-43dd-807e-ac8b33752c9a.png)

We don't know whether transactions are assigned to projects correctly...

## MVP
Add tests for projects, fix the above assignment issue. 

## Metrics 
https://opencollective-metabase.herokuapp.com/dashboard/60-projects 

## Documentation 
Would need to add that this is a feature for projects.

**Comment by natehn** [comment]
In case it helps with prioritization, adding the ability to assign cards to Projects would be really useful for OCF collectives.

**Comment by znarf** [comment]
@kewitz I don't think your API fix alone solve the issue.

- How can Events and Projects request a card? Is the action properly appearing?
- Where can Events and Projects manage their cards? Do they see the section in their settings?

**Comment by kewitz** [comment]
@znarf the actions are properly appearing for both host and collective admins.
I just opened a PR to enable the admin panel for projects and events.

**Comment by znarf** [comment]
Goals for Q1 Sprint 1 Week 6:

- [ ] Look at issue in production
