### ISSUE TITLE
Tests take a long time

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#48]
Talked to Seye (@seyeojumu) about how long our tests take and he thought it shouldn't be this long. 

Hoping he can look at our setup and give us any recs.

Actual runtime of last few test runs: https://www.dropbox.com/s/ym4iv6eyjicdwka/Screenshot%202016-04-26%2012.39.52.png?dl=0.

**Comment by sedubois** [comment]
You can mark this as duplicate if you want: https://github.com/OpenCollective/api/issues/289

**Comment by seyeojumu** [comment]
we should be able to do a few things to speed this up. i'm going to reproduce the test env locally, and try to get baseline numbers for the various test phases.

**Comment by sedubois** [comment]
Before going further we should check why tests often fail e.g during NPM install with `ECONNRESET`

**Comment by xdamman** [comment]
@sedubois I wonder if it's not because we hit the npm servers too often. But I'm not sure.

**Comment by sedubois** [comment]
@xdamman Created issue https://github.com/OpenCollective/api/issues/311 about those ECONNRESET errors.

**Comment by sedubois** [comment]
https://github.com/OpenCollective/api/pull/312 has apparently fixed ECONNRESET and improved the speed.
