### ISSUE TITLE
Edit event button not working

### ISSUE THREAD

**Issue by jancborchardt** [opencollective/opencollective#480]
On https://opencollective.com/opensourcedesign/events/opensourcedesign-summit-371ev, when I click the »Edit« button, nothing happens. I have to manually append `/edit` to the url to go to edit mode.

**Comment by piamancini** [comment]
referenced here https://github.com/opencollective/opencollective/issues/471

**Comment by xdamman** [comment]
Is is still happening? I cannot reproduce it.
Might have been fixed. If not, can you tell me which browser you are using and what's its default language (see accept-language header that it is sending to our server)

**Comment by jancborchardt** [comment]
Button still not working. On Firefox. accept-language `en,en-US;q=0.8,de;q=0.6,fr-FR;q=0.4,fr;q=0.2`

**Comment by xdamman** [comment]
Fixed
