### ISSUE TITLE
Help and support marketing page

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#4800]
We designed a new page for users to get better help, linking the experience with our docs in GitBook, and providing a general form to set a channel for others to reach out to us when is not related to support.

[edit by @benjam]
Tasks
- [x] Implement the frontend components (this issue)
- [ ] #5022
- [ ] #5023

| Desktop | Tablet landscape | Tablet portrait | Mobile | 
|---------|------------------|-----------------|-----------------|
| ![Desktop (2)](https://user-images.githubusercontent.com/49539954/136425473-2ab98301-e122-4e68-acdf-71bff2025c2d.png)   |  ![Tablet L](https://user-images.githubusercontent.com/49539954/140779206-3c20ca40-f2ae-49b7-8c9e-942726f706b9.png)   |  ![Tablet P](https://user-images.githubusercontent.com/49539954/140779349-2fbcc335-ba3d-4ce7-b8da-6d90c1b81518.png)   | ![Mobile](https://user-images.githubusercontent.com/49539954/140779201-d7ef69ea-af2e-41a0-91e9-5199639ea50e.png)
| ![Desktop](https://user-images.githubusercontent.com/49539954/140781578-371bd7c9-8a09-4b23-be6d-50d4bb0d03f6.png)   | ![Tablet L](https://user-images.githubusercontent.com/49539954/140781584-47ea82c6-c124-409e-a127-72f478bdab98.png)  | ![Tablet P](https://user-images.githubusercontent.com/49539954/140781588-44fcef36-0304-4228-bf0a-8a59df31726a.png) | ![Mobile](https://user-images.githubusercontent.com/49539954/140781580-770a38e6-3df3-4a3f-85ce-293558bcc96d.png) | 
| ![Desktop](https://user-images.githubusercontent.com/49539954/140780117-9fa7ce93-2dda-4071-8a2e-fb337fa07132.png)   | ![Tablet Landscape](https://user-images.githubusercontent.com/49539954/140780333-77a84e8a-acda-4e80-9ae0-bfb60d331a42.png)  | ![Tablet Landscape](https://user-images.githubusercontent.com/49539954/140780119-c5ce8f80-cf4b-4ed0-aa02-05c3d3a91010.png) | ![Tablet Portrait](https://user-images.githubusercontent.com/49539954/140780120-ab9b5cdf-32cb-47ab-81ef-4d262802b5c4.png) | ![Tablet](https://user-images.githubusercontent.com/49539954/140780861-89105ea2-6f87-4b0a-897e-a365154c2419.png)

[Production-ready file in figma](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/[OC-Design]-Production-Ready-✅?node-id=14465%3A179840)

**Comment by Betree** [comment]
What happened when you search or when you click on a topic?

**Comment by BenJam** [comment]
Status: 💛 (needs attention)

desgn is ready but @znarf would like to review before committing to implementation.

**Comment by Memo-Es** [comment]
Plan for this week W2S2Q4 - Week 48

- [ ] New styleguide for marketing
  - [ ] Additional typeface presentation and share with the team

**Comment by znarf** [comment]
Implementation of the static page is starting, without the advanced features.

**Comment by BenJam** [comment]
First PR of static pages has been shared, 

- [ ] need to review this week. 
- [ ] 'kick off' this week re. advanced features (gitbook integration etc.) (@aminakazi to share some of the designs)

**Comment by BenJam** [comment]
Following kick off there are a couple of additional things to explore:

- [ ] Gitbook integration
- [ ] Freshdesk integration

**Comment by piamancini** [comment]
- [ ] Review current state 
- [ ] finish mvp 
- [ ] look at advanced features and assess implementation

**Comment by znarf** [comment]
In a first iteration, we should keep the current /support page. Once we have good confidence in the new contact form, we will be able to remove the /support page.

It's possible that we might have to implement the Freshdesk implementation first. See: https://github.com/opencollective/opencollective/issues/5023

**Comment by piamancini** [comment]
- [ ] add links to the new page 
- [ ] review how emails are working before bringing down old page

**Comment by znarf** [comment]
- Implementation of Freshdesk API is currently ruled out because it's not available on the free plan and there is no major benefit. https://github.com/opencollective/opencollective/issues/5023
- Implementation of GitBook API is pending availability to us. They have not considered our application for API key so far.  Even with it, it's unclear that it will work for us. We could also hack into their Algolia account directly but that looks like a poor practice. https://github.com/opencollective/opencollective/issues/5022
- In the coming days, we will be checking if the /contact page works properly in production then deprecate the old /support page.
