### ISSUE TITLE
Root admin action to change the status of a tax form

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4805]
## User story 
As a platform admin, I want to update the status of users' tax forms myself, so we don't have to ask a dev each time we have to process one manually, and to enable faster unblocking for users held up by a tax form status issue.

## Best solution for this problem
Add a 'tax form' section to root admin dashboard, where you can select a user profile and change between statuses (not requested, requested, received - or whatever they are called)

@Betree WDYT?

**Comment by Betree** [comment]
Looking back at this one I think we should add this feature directly into the interface, on the "Tax form required" message. A simple button like "Mark as received" would open a modal with an input for the document link.

**Comment by alanna** [comment]
Ideally this would also include a way to upload the form itself (received manually) to the right place in storage with the other tax forms

**Comment by SudharakaP** [comment]
> Looking back at this one I think we should add this feature directly into the interface, on the "Tax form required" message. A simple button like "Mark as received" would open a modal with an input for the document link.

@Betree : Only issue I have here is the placement of the button. Are we good to add it on the tax form warning message itself? 

![image](https://user-images.githubusercontent.com/12435965/223148264-b72849a8-51e7-4b6f-a47a-763ca30cb19b.png)

- This would only be shown to host admins. 
- Once clicked we open a modal with field to add the link.

**Comment by Betree** [comment]
> Once clicked we open a modal with field to add the link.

Is it the responsibility of the host admin to find this link and set it? We already have it in the database, why not send it directly?

**Comment by Betree** [comment]
@SudharakaP Oh my bad, I thought this was the issue about being able to re-send tax forms request emails (https://github.com/opencollective/opencollective/issues/6126). You proposal sounds good then!
