### ISSUE TITLE
Add consolidated balance in Budget (inlcuding projects and events)

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4806]
As a Collective admin, I want to know how much balance I have across main profile, projects and events.

Today, I only see the balance of the parent.

**Comment by alanna** [comment]
This should also be reflected in the "total raised" stat in the budget section

**Comment by BenJam** [comment]
+1 to this and also I would like to add the project/events budget to the project/event cards in the projects/events list. For example there is currently $580k in the UI project on the web performance fund, but looking at the collective it only appears to have $~250 in it :D 

![Screenshot 2022-02-28 at 09 35 29](https://user-images.githubusercontent.com/158833/155959634-06059523-8cc2-4165-aa26-dca965e6d26e.png)

**Comment by Betree** [comment]
Seems resolved by https://github.com/opencollective/opencollective-frontend/pull/7981?

**Comment by znarf** [comment]
@Betree yes!
