### ISSUE TITLE
Event url changed after editing

### ISSUE THREAD

**Issue by jancborchardt** [opencollective/opencollective#481]
Just earlier I edited our event at https://opencollective.com/opensourcedesign/events/opensourcedesign-summit-371ev (by manually editing, see https://github.com/opencollective/opencollective/issues/480)

Since then, the strange `-371ev` suffix is in the URL and doesn’t seem to be possible to remove. Our current links are broken and the event is this weekend, so it would be great if that can be changed. :)

@asood123 @piamancini

**Comment by piamancini** [comment]
we'll look into it now!

**Comment by piamancini** [comment]
referenced here: https://github.com/opencollective/opencollective/issues/471

**Comment by asood123** [comment]
Fixed. Sorry about that - we moved to a new url scheme for events in our upgrade last week and a few of the active events needed to be changed to be backwards compatible. Original link should work now.

**Comment by jancborchardt** [comment]
Great stuff, thank you so much! :) Just in time for the last announcement I needed to send out to attendees.
