### ISSUE TITLE
Activate Goals for Projects

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4824]
## User story 
As a Project creator, I want to set Goals, so that I can motivate people to contribute and be transparent about intentions.

## Best solution for this problem
Enable the `Goals` profile page section for Projects just like we have it for the main Collective.

## MVP
Currently Project tiers can have goals so some people are trying to achieve it through that but it's not as nice as the regular goals option.

**Comment by alanna** [comment]
Bumping this one as people request it, and I think it's an easy win to create a really powerful toolset for flexible fundraising campaigns.

**Comment by kaylarep** [comment]
had another request for this from a collective admin

**Comment by Betree** [comment]
I missed this issue, it's indeed a very simple one. I'll look into it.

**Comment by kaylarep** [comment]
lets :fire: update this when it's deployed

**Comment by alanna** [comment]
@shannondwray for docs

**Comment by alanna** [comment]
@shannondwray looks like this hasn't been added to docs? We also need to do a 🔥 as this is a powerful user-facing feature for mini-crowdfunding campaigns.
