### ISSUE TITLE
[bug] Donate buttons should be disabled when no Stripe account attached to host

### ISSUE THREAD

**Issue by patcon** [opencollective/opencollective#483]
This concerns the HackLab Toronto collective that I'm experimenting with:
https://opencollective.com/hacklabto

@piamancini has set up our collective so that we own the host user account. We have not yet attached a Stripe account.

I would expect that the donation buttons would be disabled, similar to how they are when a collective "hasn't been approved" by the Open Source Collective.

I am instead seeing the buttons as active. I haven't run through the process to check whether any failure happens, but I expect either 1) it would fail, or 2) it would somehow process, in which case I have no idea where the money might go :)

![screenshot of active donation button](https://imgur.com/386Qaay.png)

**Comment by piamancini** [comment]
@patcon if you hit on the contribute buttons it takes you to a donation page that shows the collective doesn't have a host. 
Agreed that they should be grey to make it clearer. We'll work on that when we work on the design. 
cc / @cuiki @xdamman 
Closing for the moment.
