### ISSUE TITLE
Typo In Collective Card

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#4835]
Should say "Hosted since" not "Host since" wherever these cards appear. (Unless they are a fiscal host, but in these cases, they are all hosted collectives)

![image](https://user-images.githubusercontent.com/64920686/137553333-b8fde5b2-270a-4c06-8776-98c19dbc306c.png)

**Comment by Acroexist69** [comment]
Should be virtual and online only cards? As well as soon to be delivered
