### ISSUE TITLE
Expense "Reset form" button not available at Payee step

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4840]
Followup on https://github.com/opencollective/opencollective/issues/4625

Users should be able to reset the form at any stage

![image](https://user-images.githubusercontent.com/1556356/137727476-09084e6f-8c29-4369-b13c-4e9302aa07a4.png)

**Comment by Betree** [comment]
:trophy: This issue has been completed by @JoyLubega. Thank you!

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Comment by JoyLubega** [comment]
Thanks 🙏
