### ISSUE TITLE
Legacy bank account payout methods stored without addresses

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4842]
It seems that we've enforced bank account addresses at some point (with Transferwise), which makes sense. However, we did not migrate existing entries and ended up with **many** bank accounts stored without addresses.

As a result, users end up with a broken form since we don't support editing payout methods. They, therefore, need to create a new one. 

```sql
SELECT * FROM "PayoutMethods" pm WHERE "type" = 'BANK_ACCOUNT' AND "data" -> 'details' -> 'address' IS NULL
```

We should:
- Try to fix invalid entries in the DB. It's possible that we have everything we need to prefill the info in there
- Maybe add a helpful message to explain what's wrong and what the user can do about it

![image](https://user-images.githubusercontent.com/1556356/137879643-1ea3a191-c2b6-484c-b3bf-56f43e74d714.png)

**Comment by Betree** [comment]
@kewitz This keeps happening to users (see @jfdh's loom: https://www.loom.com/share/379c55cd2ff549759b6c9e17a29ac983). Do you think we could somehow fix the issue on our side by updating the payout methods (if we have everything needed to do so)?

**Comment by kewitz** [comment]
@Betree this was fixed on https://github.com/opencollective/opencollective-frontend/pull/7289#event-5806056353.

**Comment by BenJam** [comment]
closing because ☝️
