### ISSUE TITLE
Giving host admin the option to add money to a fund's balance

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#4844]
I am coming across this situation more and more recently. We get a transfer of funds for funds/organization and as the process of adding funds to their budget has changed, host admin has no option now to allocate this transfer directly to the fund or organization without reliance on the wider team. This leads to some instances where it takes a lot longer for the budget to be updated and delays the timing of the contributions the fund is committed to, leading to frustration and poor user experience. 

As the number of funds is growing, I would like to see a solution that would allow host admin to get the funds allocated with ease or ensure there is a process in place where we can direct folks to follow as right now it doesn't look good for us. 

Recent incidents include the example of [BuySellAds](https://opencollective.com/buysellads) who are making monthly transfers now and any delays from our end negatively impact their ability to contribute. 

![capture](https://user-images.githubusercontent.com/57156267/137980314-8c68e9be-ee59-420c-ad67-a0dc2604d5b3.png)

**Comment by BenJam** [comment]
I see that @znarf set things up a little differently with a [prepaid](https://opencollective.slack.com/archives/GFH4N961L/p1631862767024300?thread_ts=1631849319.024200&cid=GFH4N961L) method. IF we have talked to them about using a Fund then the route above would be the route to go in my opinion.

**Comment by alinamanko** [comment]
Thanks @BenJam - I am getting lost on these instructions though. I am set up as the collective admin for BuySellAds but I can't find that 'prepaid budget' section anywhere - not on the collective settings nor the host settings. What am I missing here? I am feeling so lost here :(

**Comment by BenJam** [comment]
FYI (for anyone following along at home) I have marked the pending transfer as paid, so that should have been added to their balance.

**Comment by alanna** [comment]
Is this done? I'm a bit confused by the comments on this issue.

**Comment by alanna** [comment]
@alinamanko confirms this is done
