### ISSUE TITLE
docs.opencollective.foundation SSL issue

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4846]
Trying to load https://docs.opencollective.foundation 

![Screen Shot 2021-10-20 at 1 41 35 PM](https://user-images.githubusercontent.com/5498878/138010093-29acfb2c-e633-40d6-a5ab-c3ab740490f5.png)

Multiple people having this problem and trying different browsers isn't working.

Can access https://opencollective.foundation website.
Can access the raw gitbook itself.
Can't access via https://docs.opencollective.foundation 

Priority: P1 if this is affecting everyone

**Comment by Betree** [comment]
It's resolvedm @SudharakaP updated the DNS and Gitbook renewed our certificate.
