### ISSUE TITLE
Platform Pop-overs update

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#4847]
We are bringing together the different pop-ups we have in the platform:
* Dropdown menu and non-dialog modal 
   * Collective picker
   * Multiselect
* Date picker

![❖ Pop-overs](https://user-images.githubusercontent.com/49539954/138026821-8b43dbd6-3f76-4697-bd97-a67c94d4324d.png)

[Design reference in figma
](https://www.figma.com/file/9Iq3vBOmZ2EuOacXEYD5yK/[DS]-03-Global-Components?node-id=0%3A1716)
CC @Betree

**Comment by Betree** [comment]
Separated this issue into two smaller ones:
- https://github.com/opencollective/opencollective/issues/4899
- https://github.com/opencollective/opencollective/issues/4900
