### ISSUE TITLE
Fix transactions on WWCode SV

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#485]
Mail from Brittani:

> (...) Can you please change the following transactions in Silicon Valley's OC https://opencollective.com/wwcodesv Inline image 1: 
> $1,000 Donation to Silicon Valley from VMWare to $877.50.
> $2,000 Donation to Silicon Valley from Tableau to $1,755.00.
> $500 Donation to Silicon Valley from Financial Engines to $438.75.

Image on email.

**Comment by piamancini** [comment]
done @nicobarretoOC
