### ISSUE TITLE
Export CSV link for events does not contain a link

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#4854]
**Describe the bug**
The Export CSV button events pages does not appear to contain a URL. 

I am seeing this (as an admin) on https://opencollective.com/opensource/events/open-source-collective-community-call-oct-21-41f9581b 

**To Reproduce**
1. Create an event
2. Register an attenddee
3. View attendees (as an administrator) 
4. Click 'Export CSV' 

**Expected behavior**
I should get a CSV of the registered attendees. 

**Screenshots**

![Screenshot 2021-10-21 at 09 42 57](https://user-images.githubusercontent.com/158833/138243133-470d1ede-d594-45c8-a237-6babcd94cfc7.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome

**Additional context**
The route to export does still appear to work, it's just not linked https://opencollective.com/opensource/events/open-source-collective-community-call-oct-21-41f9581b/admin/export

**Comment by SudharakaP** [comment]
@BenJam : I tried to recreated this in my local and production but seems it's working. For example try at https://opencollective.com/opensource/events/open-source-collective-community-call-nov-21-87598fa3

![export-csv](https://user-images.githubusercontent.com/12435965/139570243-66bc2687-62d7-4fbb-8f77-d79824d1997b.gif)

But let me know if you see this issue again and I'll investigate more. 🤔

**Comment by Betree** [comment]
@BenJam do you see an error message in the console when trying to export?

**Comment by BenJam** [comment]
the problem i was having is that the 'export CSV' button did not actually contain a clickable link. Just tried again and it appears to have resolved.
