### ISSUE TITLE
Show "Export" section in events admin 

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#4855]
**Describe the bug**
Admin panel does not contain link to export page eg. https://opencollective.com/opensource/events/open-source-collective-community-call-oct-21-41f9581b/admin/export 

**To Reproduce**
1. Create an event
2. Click settings on the event's profile page
3. ...

**Expected behavior**
it should be possible to navigate to the export page. 

**Screenshots**
![Screenshot 2021-10-21 at 10 08 39](https://user-images.githubusercontent.com/158833/138247472-74b6f8b8-8d39-4714-ad1f-d9e5bc6a64f7.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome (94.0.4606.81)

**Additional context**
Related #4854

**Comment by alanna** [comment]
Bump for this one. Many event organisers need this feature.

**Comment by Betree** [comment]
I started to work on this in https://github.com/opencollective/opencollective-frontend/pull/7040 but forgot about it. Will finalize this week

**Comment by Betree** [comment]
Actually this was done in https://github.com/opencollective/opencollective-frontend/pull/7545
