### ISSUE TITLE
Submitted HelloWorks Forms Exposed to Email Providers

### ISSUE THREAD

**Issue by U8NWXD** [opencollective/opencollective#4858]
## Who is your user?

Users who need to submit tax forms.

## What are they trying to achieve?

When submitting a tax form, the user wants their social security number (SSN) in the form to be kept private to protect against identity theft. Only the collective's admins should have access to the SSN.

In particular, the SSN should not be transmitted over email since doing so exposes the SSN to the user's email provider and potentially other third parties if the email provider does not require that incoming emails be encrypted in-transit.

The user may not trust their email provider or these other third-parties to protect the SSN. Even though a malicious entity in control of the user's email account could take over the user's OpenCollective account, that account takeover would not by itself give the entity access to the user's SSN, which is not available even from a logged-in account.

## How are they currently doing this?

As far as I can tell, there is currently no way for users to prevent their completed forms from being sent to them over email. This means users have no way to avoid leaking their SSNs to their email providers.

## What is the desired outcome of fixing this problem?

Ideally, users would be able to access their completed forms without leaking the contents of those forms to their email providers. At the very least, users should be warned that their completed forms will be sent over email and visible to email providers.

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by U8NWXD** [comment]
@SudharakaP just to clarify, the email containing the user's SSN comes from HelloWorks. To encrypt an email with OpenPGP, the sender has to encrypt it with the recipient's public key, so to solve this problem with OpenPGP, I think HelloWorks would need to support sending OpenPGP-encrypted emails. Does HelloWorks support this?

From a [HelloWorks support article](https://faq.hellosign.com/hc/en-us/articles/215339268-HelloSign-Security-), it looks like HelloWorks (a.k.a. HelloSign) lets customers remove the PDF of the completed form from the confirmation email, but I didn't see a way to enable OpenPGP encryption. I could easily be missing something though!

**Comment by Betree** [comment]
> For example after the user submits the form HelloSign will send a email to create a password to access the document on HelloWorks; https://faq.hellosign.com/hc/en-us/articles/215343088-Signing-a-HelloSign-document. thinking

@SudharakaP That's true, but arguably doing so would leave some traces (because they'd need to signup) and that's probably not something email providers would ever automatize. On the other hand, we know for a fact that some email providers (e.g. Gmail) parse your attached files (including PDFs). Having them stored on **their** servers, you have no way to know if, when, and how the files were accessed.

According to @alanna's feedback above, we don't see a use case for this at the moment. As part of the upcoming HelloWorks changes, I'll therefore remove the document the from email sent to the participant upon workflow completion.

**Comment by Betree** [comment]
Note that if we want to send the document by email in the future, an alternative is to pass `document_delivery_type="link"` to send the document as a unique URL rather than an email attachment.
