### ISSUE TITLE
Make a clearer distinction between balance and years budget goals

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#4859]
## Problem

Neither the app nor [the docs](https://docs.opencollective.com/help/collectives/collective-settings/tiers-goals) make it clear what the difference between 'balance' and 'yearly budget' goals are:

![Screenshot 2021-10-22 at 10 55 27](https://user-images.githubusercontent.com/158833/138434625-1438c3a7-a479-4b4b-bd1d-ef09a33e596f.png)

> To create a goal, give it a title, categorize it as either a goal balance or yearly budget, specify the amount you need and add a description. Don't forget to save your changes when you're done!

Part of the problem here is that we always show both the balance and yearly budget on the goal tracker #3631. 

## Solution

It would be great to improve the docs and link to them from the 'goal type' form with a info link. It would also be good to only show the balance/estimated yearly budget if there are only goals of that type for this 'Collective' (may be a project, event, fund or something else in the future).

**Comment by RCheesley** [comment]
@shannondwray could you provide a link to how this has been improved?
