### ISSUE TITLE
Expenses should be ordered by incurredAt date

### ISSUE THREAD

**Issue by patcon** [opencollective/opencollective#486]
In preparation for a demo, I manually entered a bunch of incoming funds and expense from the past 3 months in the [`hacklabto` collective](https://opencollective.com/hacklabto).

![screenshot](https://imgur.com/4xfizyK.png)

I would have expected the expense to be arranged by date in which they happened, even though I entered them in an order for my convenience of copy-pasting.

Instead it seems that the expenses are ordered by the date of clicking "paid".

Is this a very intentional choice? :)

**Comment by asood123** [comment]
Also, an issue with transactions: https://opencollective.com/mochajs/transactions. We are ordering by ID and should be using incurredDate or createdDate
