### ISSUE TITLE
Event datetime picker problems

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#4865]
**Describe the bug**
Interactions with the event datetime picker are _incredibly_ weird. So weird that I had to take notes to use it:

https://www.loom.com/share/15fe54ec5ff04d9886a0f3ab3f12a94b

as far as I can tell

- I can select a date okay
- the up arrows for hour are incredibly sensitive (skipping two or more hours)
- If I try to press the down arrow it resets
- if I try to edit the time as a text field the delete key will decrement the time

I think the onclicks are registering additional increments and misbehaving. 

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome 94.0.4606.81

**Comment by SudharakaP** [comment]
@znarf @Betree : While working on this one, I was thinking that the `PeriodFilter` in it's current state do not include a way to specify time; only dates. Do we need to add support for that as part of this issue as well? 🤔 Or shall we do as per the specs above without the time and add it as an separate task?

**Comment by Betree** [comment]
> @znarf @Betree : While working on this one, I was thinking that the `PeriodFilter` in it's current state do not include a way to specify time; only dates. Do we need to add support for that as part of this issue as well? thinking Or shall we do as per the specs above without the time and add it as an separate task?

We would need a design update to include the time in this component, and so far we don't have other use cases for it. I would suggest going for the simpler alternative of having a separate input for the time.

**Comment by Betree** [comment]
@SudharakaP We should keep https://github.com/opencollective/opencollective/issues/4950 in mind while solving this issue

**Comment by Betree** [comment]
Alternative: `PeriodFilter` could accept a `inputsType` prop like:

```jsx
<PeriodFilter inputsType="datetime-local" />
```

See https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/datetime-local

**Comment by SudharakaP** [comment]
@Betree : Working on this I realize we can do a simpler solution with 

> Alternative: `PeriodFilter` could accept a `inputsType` prop like:
> 
> ```js
> <PeriodFilter inputsType="datetime-local" />
> ```
> 
> or
> 
> ```js
> <PeriodFilter hasTime />
> ```
> 
> See https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/datetime-local

@Betree : Thanks for the idea. When I was working on this I realized that we could directly use the `datetime-local` on the input field. I've quickly done a PR to illustrate this. Let me know if there's any issues with this approach. If there is, I'll go back to the PeriodFilter method. I just thought that this way we do not have to customize the period filter a lot and overall it seems much simpler. 🤔
