### ISSUE TITLE
donation fails on a collective hosted by host-other

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#487]
I’m a core contributor of https://opencollective.com/socialcoop and somebody tried to contribute and got the following error:
"An error occured . The order didn't go through. Please try again in a few.: Error: GraphQL error: The host for the social.coop collective has no Stripe account set up (HostCollectiveId: 8674)”

We have received donations for this collective in the past.

**Comment by piamancini** [comment]
cc/ @asood123 in case you can look into this.

**Comment by mayel** [comment]
thanks @piamancini 
I'll post straight to github in the future :)

**Comment by asood123** [comment]
@piamancini I'm not sure what's going on here. 8674 might need be marked as it's own host. Can you try donating on any other collective that's hosted by the same host?

**Comment by mayel** [comment]
@asood123 unless I'm mistaken we are hosted by the main OpenCollective host though (are there others?)

**Comment by piamancini** [comment]
@mayel It should be fixed now. Can you please try again?

**Comment by piamancini** [comment]
closing this as donation came through.
