### ISSUE TITLE
Do not collapse About section

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4872]
This does not look good:

<img width="1234" alt="Screen Shot 2021-10-27 at 11 55 55 AM" src="https://user-images.githubusercontent.com/5498878/138972655-8905f9c0-aae3-447a-a86a-693d4cb0e355.png">

(from https://opencollective.com/happenfilms)

If a Collective puts info in their About section it means they want it displayed on their page. We should not hide it.

**Comment by alanna** [comment]
@SudharakaP content is still weirdly cut off in expense items. Is this the same issue or should I raise a new one?
<img width="741" alt="Screen Shot 2021-11-03 at 1 59 16 PM" src="https://user-images.githubusercontent.com/5498878/139973874-9543f799-c92c-4fb6-b90a-608bb0a9ad88.png">

**Comment by SudharakaP** [comment]
> @SudharakaP content is still weirdly cut off in expense items. Is this the same issue or should I raise a new one? <img alt="Screen Shot 2021-11-03 at 1 59 16 PM" width="741" src="https://user-images.githubusercontent.com/5498878/139973874-9543f799-c92c-4fb6-b90a-608bb0a9ad88.png">

@alanna : Thanks for pointing it out. I've opened an issue at https://github.com/opencollective/opencollective/issues/4903 and suggested a fix there. Will get this one out soon. 👍🏽
