### ISSUE TITLE
Don't show full tax form banner to non-payee

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4873]
Yuri reports:

> Hi, I just sent an invitation to one of MapLibre's contributors, so they can ask for money. They did, and I approved it.  Now it shows a message that requires my tax information, even though it is not me who is receiving the funds -- I'm just authorizing the payment. Should this message be clarified somehow that it pertains to the person being paid, and not the person who is viewing that page?  Or does it need my tax info?

In this example, Yuri is the Collective admin and expense inviter and Hatel is the invited payee. Only Hatel needs to fill out the form, but Yuri sees the banner and gets confused.

![SM77EjDX-ER5nYoxXBlP-ASE7QpxlPg1hw](https://user-images.githubusercontent.com/5498878/138986860-5d356c6d-47e1-41dd-987d-fdbbcc045657.png)

We have got feedback from Collective admins that's it's very useful for them to see when an expense is pending the tax form. Can we display a small banner to the admin/inviter that just says "This expense is pending [payee] to submit their tax form." so it's more clear?

**Comment by znarf** [comment]
We know from experience than Collective admins and Fiscal Host admins are relying on it today. As first step, maybe change the wording so it's not about "you" and everyone understand it's about the Payee.

**Comment by Betree** [comment]
We indeed implemented this on purpose based on feedback from https://github.com/opencollective/opencollective/issues/4729. I agree that changing the wording will make things clearer.

**Comment by alanna** [comment]
Yes this is why I suggested alternate banner wording in the OP.
