### ISSUE TITLE
Unable to invite expense - next disabled with no error

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4877]
I'm trying to invite someone to submit an expense. I've filled out all the info I have, but the `next` button is disabled. There's no error and I can't proceed.

![Screen Shot 2021-10-28 at 1 15 50 PM](https://user-images.githubusercontent.com/5498878/139192776-5d086c1a-988a-4baf-9abe-81dc248ce1e1.png)

**Comment by SudharakaP** [comment]
So just to give an update, I've discussed this with @alanna  and indeed the problem was the email was not valid and my solution above fixes that problem in the sense that below the email input box we show and error when it's not valid so that the user knows. 😉 

cc: @znarf
