### ISSUE TITLE
Provide a domain name service

### ISSUE THREAD

**Issue by mkurz** [opencollective/opencollective#4880]
Hi!

We are thinking about to move an Open Source project to Open Collective.
Right now the domain the project is running at is registered and therefore owned by a company. That company however wants to hand over the OSS project to the community.
I am now looking for a way to transfer the domain to something like a 3rd party trustee which then should own the domain, which is trustworthy and reliable. That's because the project should be run by multiple OSS contributors and should not be owned by an individual and also we don't have any company set up that could own the domain.

Can Open Collective hold the domain name for us?

In the future that might be a service you could offer, like you do with virtual cards, were people can reliable transfer domains to (or register domains) via Open Collective to Open Collective, in a sense that Open Collective (or the Open Source Collective) is owning the domain.

Thank you!

**Comment by BenJam** [comment]
👋 exec director of Open Source Collective here. If a Collective that we host needs us to take ownership of a domain I think we should be able to do that.

**Comment by mkurz** [comment]
@BenJam Thanks! That's great to hear! So even if there is no UI for that yet (of course), would you be able to manage our domain already? Probably we would need to transfer the domain to "Open Source Collective 501(c)(6)" and you need to set the name servers. Also we probably want to have some legal contract that you are not the actual "owner" of the domain (which technical you are), but kind of a trustee. I think it makes sense that if a Collective admin wants to transfer the domain away from the Open Source Collective, he/she is able to do that (btw we are https://opencollective.com/playframework).

We are not planning to transfer the domain to the Open Source Collective within the next few weeks anyway, but I just want to set things up so its ready when we want to start the transfer. Thanks!

**Comment by mkurz** [comment]
@BenJam Can we start with the transfer of the domain? What would be the next steps?

**Comment by mkurz** [comment]
@BenJam The linked page is not available anymore, do you still handle domains?
