### ISSUE TITLE
Search should allow for different punctuation

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4885]
This search failed because of apostrophe placement. Can we make our search a little more forgiving?

<img width="1124" alt="Screen Shot 2021-10-30 at 9 35 47 PM" src="https://user-images.githubusercontent.com/5498878/139526252-23165a49-1807-4946-afbf-4f5d2da33735.png">

<img width="930" alt="Screen Shot 2021-10-30 at 9 36 00 PM" src="https://user-images.githubusercontent.com/5498878/139526254-c91a1314-a14f-487a-af08-6b54b67faf26.png">

**Comment by SudharakaP** [comment]
@Betree : My thinking is that we should compare the search string without punctuation using `localCompare` just like we do here; 

https://github.com/opencollective/opencollective-api/blob/fa6ae5ddafbeef545f407dadd6e6d75cdb1853a6/server/graphql/common/expenses.ts#L741-L763

Let me know if you are okay with this and I'll open a PR.

**Comment by Betree** [comment]
@SudharakaP The search is handled with an SQL query: https://github.com/opencollective/opencollective-api/blob/5bc4696327e14c19821da3dc437e4a27cc1f3a0a/server/lib/search.js#L86, JS functions won't help us here. We normally vectorize the term, but somehow it's not enough to prevent this problem.

There is a larger project to be done on improving the search functionality (by improving the queries, https://github.com/opencollective/opencollective/issues/3825, or by switching to a 3rd party service to do all that for us). @SudharakaP if you see a quick fix that won't impact the performances feel free to implement it (along with a test in `test/server/lib/search.test.js`), but don't spend too much time on this; we want to revamp it.

**Comment by Betree** [comment]
I've pushed an update in https://github.com/opencollective/opencollective-api/pull/6879 that fixes that, along with the plural forms (English only). For example, searching for `democracy` will return entries that include `democracies` in their descriptions
