### ISSUE TITLE
No index on ExpenseId in Transactions table

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4890]
Not sure why we don't have it yet (no useful in current scenarios) but seems needed.

**Comment by Betree** [comment]
Would be great to also add one on `kind` since we use it more and more

**Comment by Betree** [comment]
And while we're at it, [this query](https://github.com/opencollective/opencollective-api/blob/1579c4f9d079007f540681e78f48d89b8fd8ff5e/server/graphql/loaders/index.js#L347) appears to be quite expensive in production. We could easily optimize it by adding an index on `Order.TierId`.

@znarf I think having a single migration to create all these indexes would be great, but LMK if you prefer me to move that to separate issues.

**Comment by Betree** [comment]
Also things that could be interesting to index on Orders:
- `FromCollectiveId`
- `CollectiveId`
- `status`
