### ISSUE TITLE
Paypal donation flow broken

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#49]
Tried it on dockersf and it redirected to paypal fine. After I logged in and clicked approve, it landed me here: https://opencollective-prod-app.herokuapp.com/login?next=/groups/45/transactions/403/callback.

Need to update the callback url at a minimum. There's also a weird delay after you click "Donate with Paypal".

**Comment by piamancini** [comment]
It would be great if we can build a way for other collectives to use this feature easily.

**Comment by asood123** [comment]
Tested with a donation to dockersf. It works!!
