### ISSUE TITLE
Content is Cutoff in Expense Items

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4903]
This is related to the comment https://github.com/opencollective/opencollective/issues/4872#issuecomment-958578164

It seems that after implementing https://github.com/opencollective/opencollective-frontend/pull/7016 for expense items which has only two lines we have our collapse text behavior which is undesirable. Ideally the second line should only be blurred if a third line exists. 🤔 

<img width="741" alt="Screen Shot 2021-11-03 at 1 59 16 PM" src="https://user-images.githubusercontent.com/5498878/139973874-9543f799-c92c-4fb6-b90a-608bb0a9ad88.png">

**Comment by Betree** [comment]
It's not only about blurring, we arguably don't need the "Read full description" in those cases. I would advocate simply changing the min-height to collapse to the double.

**Comment by SudharakaP** [comment]
> It's not only about blurring, we arguably don't need the "Read full description" in those cases. I would advocate simply changing the min-height to collapse to the double.

@Betree : Isn't that what was done in the [above PR](https://github.com/opencollective/opencollective-frontend/pull/7082)? So here we make sure only if there's a third line content is cut off. The content if cut off always at the second line, but previously we were not checking if it goes beyond the second line. So now if there's only two lines we don't show the "Read full description". 🤔
