### ISSUE TITLE
Host admin reports > total money managed: unclear date filters

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4907]
When touching the date filter of the historical view for the "total money managed" section, it reloads everything, including the static data above.

Expected behavior: we should only refresh the historical view.

![image](https://user-images.githubusercontent.com/1556356/140024933-3de10e19-a443-4904-a388-69688df2a713.png)

**Comment by Betree** [comment]
Ping @Memo-Es, this one is an engineering issue but I think it surfaces a possible confusion between the two date pickers. We may want to keep an eye on the feedback for this one.

![image](https://user-images.githubusercontent.com/1556356/140025401-af15042d-1261-4396-9eeb-06e39d261b7b.png)

**Comment by SudharakaP** [comment]
@Betree : I think this is now solved since the filters have been moved to top of the page. Shall we close this one? 🤔

**Comment by Betree** [comment]
@SudharakaP Yep the root issue described has been resolved. There might still be some confusion about the year picker in https://github.com/opencollective/opencollective/issues/4907#issuecomment-958720694, but we'll see if we get feedback in that direction
