### ISSUE TITLE
supercollective shows sum of all funds in available balance.

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#491]
Mail from Brittani:

> It seems like our WWCode Global https://opencollective.com/wwcode Available Funds is a combination of all networks and information has been combined since your last front-end update.  
> 
> We can now no longer see the record for our Global funds as clearly as before, is there another place I should look for this information?

**Comment by piamancini** [comment]
Assigning this to @asood123 to look into instead of @xdamman

**Comment by piamancini** [comment]
this is not longer the case (it's another issue now :) )
