### ISSUE TITLE
🔥 changelog updates for host admins

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4910]
I want to send a 🔥 about the new admin panel, but it's not relevant to 99% of users, but it's highly relevant to host admins and I want to make sure they know about the changes. I wish we could do a 🔥 update that only went to host admins.

**Comment by Betree** [comment]
Updates have a `notificationAudience` attribute. Maybe we can use it with a value like `FISCAL_HOST_ADMINS`, and then filter the changelog entries to display only the ones user would be targetted by?

**Comment by SudharakaP** [comment]
> Updates have a `notificationAudience` attribute. Maybe we can use it with a value like `FISCAL_HOST_ADMINS`, and then filter the changelog entries to display only the ones user would be targetted by?
> 
> Ping @SudharakaP

Thanks for the idea. Yes this works but I think we already have an issue for this at, https://github.com/opencollective/opencollective/issues/4804. 

@alanna : These two issues are the same right? 🤔

**Comment by alanna** [comment]
Yes sorry it's a dup

**Comment by SudharakaP** [comment]
Thanks for confirming, I am closing this issue in favor of the other issue. We'll track that there.
