### ISSUE TITLE
Host reports section: use a tooltip for "Projected" amount

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4915]
We got recurring feedback that it's unclear what "Projected" is. We should add a tooltip to explain what it is and how it's calculated.

![image](https://user-images.githubusercontent.com/1556356/140282596-0fa7dbb6-e852-4cad-97c6-b21e40f6ec1e.png)

**Comment by znarf** [comment]
As discussed this yesterday, I would personally remove this metric that is barely needed and too complicated to explain. Once we figure it's a real problem for Fiscal Hosts, we can re-introduce it.

**Comment by SudharakaP** [comment]
> As discussed this yesterday, I would personally remove this metric that is barely needed and too complicated to explain. Once we figure it's a real problem for Fiscal Hosts, we can re-introduce it.

I am also okay with removing this projected metric and actually, right now we show only the total money managed amount here; not the projected amount so it probably doesn't make sense to show it as we already show this amount just below. 🤔  

![image](https://user-images.githubusercontent.com/12435965/140590430-498e8ac0-45fa-4a14-8341-5776c8b8ec81.png)

**Comment by Betree** [comment]
Removed in https://github.com/opencollective/opencollective-frontend/pull/7100
