### ISSUE TITLE
Receipt not rendering under pending expenses

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#492]
Mail from Brittani:

> When I'm looking at Atlanta's Open Collective and click under pending expenses, I cannot find the receipt for that expense.  https://opencollective.com/wwcodeatl 
It looks like when I click view all expenses, the receipt does show.

**Comment by piamancini** [comment]
closing this, it's referenced in https://github.com/opencollective/opencollective/issues/431
