### ISSUE TITLE
Rename and Refactor all Occurrances of `fundingRequest` in front-end

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4922]
I just noticed that we have occurrences of `fundingRequest` in the front-end. And since we no longer use this field on out DB as per, https://github.com/opencollective/opencollective-frontend/pull/7043, we need to revisit and ideally rename or remove these occurrences. 🤔 

cc: @Betree

**Comment by ManuSquall** [comment]
Hello world, hope you're doing well. May i help on it?

**Comment by SudharakaP** [comment]
> Hello world, hope you're doing well. May i help on it?

Sure, thanks for helping out. Note that we should probably wait until, https://github.com/opencollective/opencollective-frontend/pull/7090 is merged. After that I think what is left is the `fundingRequest` occurrences in this file; 

https://github.com/opencollective/opencollective-frontend/blob/main/stories/mocks/loggedInUser.js

My thinking is we can safely remove the lines `fundingRequest: true` as I don't see them being used anywhere. 

cc: @Betree

**Comment by ManuSquall** [comment]
Oops sorry I completely forgot that this was assigned to me 😓

**Comment by SudharakaP** [comment]
> Oops sorry I completely forgot that this was assigned to me sweat

No worries. 🙂
