### ISSUE TITLE
Problem approving expense for payment after account information was updated

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#4925]
**Describe the bug**
Recently we had a number of incidents where a payment failed (due to various issues with the payout method provided by the user), resulting in an error message. 

Once the user got notified and updated their payout methods and we attempt the payment again, the following error message is received:

![capture](https://user-images.githubusercontent.com/57156267/140663084-c271289f-aaf0-4bdc-bd5e-591d52e8ef5a.png)

**To Reproduce**
1. Go to [this expense](https://opencollective.com/ospic/expenses/53759)
2. Attempt payment as per usual flow
3. See error

![capture](https://user-images.githubusercontent.com/57156267/140663084-c271289f-aaf0-4bdc-bd5e-591d52e8ef5a.png)

**Expected behavior**
Payment should go through as intended - looks like the initial error and update are not registering correctly.

**Comment by Betree** [comment]
Looks like we're not freeing the lock created in https://github.com/opencollective/opencollective-api/blob/main/server/graphql/common/expenses.ts#L1050, we need to investigate why.

**Comment by Betree** [comment]
Should have been resolved with https://github.com/opencollective/opencollective-api/pull/6860
