### ISSUE TITLE
Terminology around fees and pricing model

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4929]
We've got some "terminology debt" building up around the words we use to refer to platform fees and related types of transactions. We need to clarify these terms and update how they appear in the platform, docs, exports, etc.

Here's a rundown of the terms we're using now (I hope I have these correct - some are confusing for me, which is kind of the point of this issue). These terms come from a few different places: platform settlement expenses, CSV exports, the new host reports, the pricing page. One problem is we're using different terms for the same things in different places sometimes.

|   | Current Term  | Meaning   | OK ✅ or problem ⚠️ |  note  |
| --- |--------------|-----------|------------------ | ------ |
| 1 | Platform tip | Optional contribution to OC inc made by contributors when paying a Collective or by Host and IC Admins who don't charge a host fee when adding funds manually |  ✅ | Working well, clear |
| 2 | Host fee | Fee charged by Hosts to their Collectives for the Hosting service, applied to incoming funds (total charged to Collectives without reference to payments to the platform) |   ✅  |  Working well, clear  |
| 3 | Host fee share (used in CSV exports and host reports) | The portion of Host Fees paid to OC inc for using the platform (usually 15%) | ⚠️ | Causing confusion |
| 4 | Shared revenue (used in settlement expenses) | The portion of Host Fees paid to OC inc for using the platform (usually 15%) | ⚠️ | Causing confusion |
| 5 | Host revenue (used in new host reports) | The portion of Host Fees NOT paid to OC inc that the host will retain | ⚠️ | Confusing, not consistent with other terms |
| 6 | Profit (used in new host reports) | The portion of Host Fees NOT paid to OC inc that the host will retain | ⚠️ | Not a good term for us |
| 7 | Host fee share owed (seen on host reports) | Host fee share to be paid to the platform via upcoming settlement expense | ⚠️ | We call this "host fee share debt" in other places - we should pick one term and stick with it |
| 8 | Host fee share debt (seen in CSV exports) | Host fee share to be paid to the platform via upcoming settlement expense | ⚠️ | We call this "host fee share owed/invoiced" in other places - we should pick one term and stick with it |
| 9 | Platform tip debt | Platform tips sitting in the bank account of the host that need to be paid to OC via settlement expense |  ⚠️ | Likely to confuse users |

## Suggested terms going forward
(my own opinion - let's discuss)

### 3 Host fee share --> platform fee

In #4702 @znarf said:

> Consensus is that "Host Fee Share" might not be a great name but naming it "Platform Fee" would have been even more confusing because "Platform Fee" was something different in the past. It would be bit difficult to justify having "Platform Fees" again when we said that we were dropping it in the past. At least we should be really careful with it.

My thoughts....

* We can't be held back by the past forever. The new pricing model has been in place long enough that I don't think users will be confused.
* I acknowledge it could cause issues in the data to use `platform fee` to refer to one thing before and another thing after, but there must be a way to handle this gracefully (can we go back and change all the old transactions to `OLD_PLATFORM_FEE` or something?)
* We only ever promised "no platform fees" to *Collectives* - we always were upfront about charging Hosts a fee to use the platform.

The reason I think `Platform Fee` should be the term is because it's the fee people pay to use the platform. I know we want to emphasize the "shared revenue model" between platform and hosts, and it's fine that we use that phrase casually when describing pricing narratively, but as a technical term it causes lots of confusion. "A shared revenue model" is a conversational phrase that doesn't have an exact technical meaning.

If people don't think `Platform Fee` is right, then what other term could be more clear? I still think it needs the word `platform` in it for sure. We are very committed to using the term `platform` when referring to the software platform made by OC inc, and that clarity is super important in our complex and multi-layered reality with Collectives and Hosts in the mix too. We are also committed to our understanding that the 15% hosts pay is the money that supports development of the *platform*, and what we call that charge should be aligned.

The other term I can imagine working is `Platform Share` because it correctly implies that it's the *platform's share* of the revenue. But I still think the word `share` has so many meanings that it can cause problems. A fee means only one thing, and it's alongside "host fee" as a term we're committed to.

### 5 Host revenue --> I don't know
To me "host revenue" implies the total brought in by the host *before* taking out platform fees (or platform share or whatever) because "revenue" in accounting terms usually refers to total money through the door before expenses. I think it's highly likely "host revenue" will be confused with "host fees". But I don't know what to call it that's better. The technical term would be something like "net host fees".

### 7 Host fee share owed / 8 host fee share debt -->  "to pay" or "owed" (or maybe keep debt?)
We should be consistent and call these the same thing. "Debt" has a negative connotation, but we have committed to the term in the database and I think it's OK. If we want a friendlier term on the front end we can say "Platform fee to pay", but as people will look for this in reports/exports we should probably just stay consistent with the database and stick with "debt".

### 9 Platform tip debt --> Platform tip "to pay" or "owed"

Example of this in action:

![Screen Shot 2021-11-08 at 9 38 06 AM](https://user-images.githubusercontent.com/5498878/140860839-922a2634-0c44-48e1-821c-75ff301a8323.png)

I think it's unlikely someone will intuitively understand what this means. But same question about keeping consistency with the database and what things are called in exports.

---------

Once we clarify the above terms and decide to make changes accordingly in the app, we will also need to make changes to the docs and the pricing page (I think it's a good opportunity to simplify the pricing page anyway).

What do people think?

**Comment by natehn** [comment]
For 5/6, I think it would make sense to use "net host fees." This is like "net profit" - it implicitly references the costs, in this case platform fees.

For "owed/to pay," can we also consider "payable"? As in, accounts payable. This would be easily understandable for folks with any experience in accounting.

**Comment by alanna** [comment]
@znarf what do you think?

**Comment by znarf** [comment]
@alanna I have not changed my mind and I am still reticent about re-introducing the "Platform Fee" term. I could settle with "Platform Share". Or "Platform Fee Share" as a middle ground.

Other terms (especially the one with "debt"), we carefully picked the terms while redesigning the ledger and I personally don't have much regret. I'm happy to not change them and keep them consistent with their internal name.

Regarding the one in the Reports dashboard, we can have those simple definitions.

- `Host Fees = Host Revenue + Shared Revenue`
- `Host Fees -  Shared Revenue = Host Revenue`

1) Platform Tip
2) Host Fee
3) Host Fee Share or **Platform Share** (if the context of Host Fee is clear such as in a Host Fees section)
4) Shared revenue or  **Platform Share**
5) Host Revenue or **Host Net Revenue**
6) Your profit -> **Host Revenue** or **Host Net Revenue**
7) Host Fee Share Debt or **Platform Share Debt**
8) Platform Tip Debt

**Comment by kaylarep** [comment]
I'm pro calling it "Platform fee". This is consistent with what other similar crowdfunding platforms call it.

"share" is a confusing term to me to use at all, because I'm not sure if it means that _that amount_ is being shared, or is it more like "shares" as in stock? "Share" is definitely a nicer word to use, and maybe most people understand that it means the asset, but it isn't clear enough to me.

+1 for using 'Net' whenever it applies
+1 for "Payable" (if that is a globally understood term)

Suggested for 5: Net amount for Host
Suggested for 6: Net amount for the initiative/collective (is that an accurate description?)

I know those suggestions aren't as pretty and concise, but they don't leave much room for confusion.  Am definitely still happy to hear better/other suggestions though.

**Comment by alanna** [comment]
I really agree with @kaylarep about the confusion from the word "share". I has too many meanings that could apply here. We've already experienced the issue of our accountants completely misunderstanding what "host fee share" was about (they assumed it was a portion *for the host*). We fixed that particular misunderstanding but to me that shows that even financial experts are not likely to guess the meaning correctly, much less ordinary users.

@znarf what is your real objection to "platform fee"? Is it something wrong with the phrase itself or only its history because we previously used it to mean something else in the past? If it's only about the history, I really think it's time to move on. If it's some other reason, please explain.

I also agree with @kaylarep that we should align with what other platforms call their fee. We already introduce so many new concepts to our users and there's already complication with host fees in addition - so we should keep things simple and familiar wherever possible.

* Kickstarter calls it 'kickstarter fee'
* GoFundMe calls it 'platform fee'
* IndieGoGo calls it 'platform fee'
* Patreon calls it 'platform fee'

So it really seems like 'platform fee' is standard language.

**Comment by piamancini** [comment]
weighing in: 

I am also reticent to use the platform fee term. It's a revenue share model and I think that the whole point is to emphasize we are in this as partners. The idea of fee has a more extractive connotation and it lucks the nuance that if a host doesn't make money then we don't make money either. That is a KEY aspect of who we are and what we do and it aligns with our values. 

Platform Share is to me the best term, it's the share of the transaction that belongs to the platform. 

I am not a fan of using debt tbh, I think something like payable or ´to be paid´ is friendlier, but I can live with it if we don't want to. mess around too much. Also Owed is an option. I think this one is better. 

Profit is definitely the wrong term here, as it's not really profit. So +1 to Net Host.  I would use Net Host Fee (so it's consistent with 2.)

So: 
1. Platform Tip
2. Host Fee
3. Platform Share 
4. Platform Share
5. Net Host Fee
6. Net Host Fee
7. Platform Share Owed or Debt)
8. Platform Tip Owed (or Debt)

**Comment by znarf** [comment]
@znarf what is your real objection to "platform fee"? Is it something wrong with the phrase itself or only its history because we previously used it to mean something else in the past? If it's only about the history, I really think it's time to move on. If it's some other reason, please explain.

I wrote it many times and still haven't changed my mind, so you can read again in https://github.com/opencollective/opencollective/issues/4702 and perhaps elsewhere. Yes it's because we still had 6 months ago "Platform Fees" (is that a long time?) and also the fact that we're still tracking those "Platform Fees" in the ledger. It's also that we moved precisely to the new model because we're not charging "Platform Fees" anymore, it's something different.

> If it's only about the history, I really think it's time to move on.

I don't think so, as highlighted in https://github.com/opencollective/opencollective/issues/4702#issuecomment-922269155, we have blog posts that are less then 1 year old explaining that we're dropping "Platform Fees". That's not a long time for me.

> So it really seems like 'platform fee' is standard language.

As far as I know, our Host Fee Share mechanism is completely different from GoFundMe, IndieGoGo and Patreon. It's not because some platforms have something named "Platform Fee" that our Host Fee Share mechanism should be named "Platform Fee".

One is visible to the Contributor and the Collective, the other is behind the scenes between the Host and the Platform.

We changed our model and we ended up with this original mechanism, I think it deserves a different name.

**Comment by piamancini** [comment]
Ok - @znarf and I just had a chat about this. 

We agreed on this terminology:
  
Platform Tip
Host Fee
Platform Share
Platform Share
Net Host Fee
Net Host Fee
Platform Share Owed
Platform Tip Owed

**First Step** will be to change this in the report dashboard and keep the data base (therefore the CSV) as it is for the moment. 
**Second Step** we will scope a UI platform broad change in a consistent way
**Third Step**  We will scope a data base update in a consistent way. 

Until we do Step 3 the CSV terminology for these categories will not match the Interface one.

**Comment by alanna** [comment]
I still disagree about not calling it 'platform fee', but I can live with 'platform share' I guess. It's definitely better than what we have now, along with the other changes.

The other place to update is the pricing page - can I go ahead and submit a pull request for that based on the terms @piamancini stated above, or do we want to wait until step 2 of the plan?

Also, when is the right time to make the changes in docs? cc @shannondwray

**Comment by piamancini** [comment]
I think @Betree can edit the terminology in the host dashboard now while he's finishing it. 
You can make a PR to the pricing page @alanna. 

We will need to scope the platform broad change for later implementation

**Comment by kaylarep** [comment]
what about "Platform Allocation"? 

Sorry to press this, but I'm still too confused by the word "Share"- I really don't think it's a clear enough word to be using.

Also, I thought it was 0 platform fees only for charitable initiatives? Or is it that the platform actually doesn't charge any fee at all, and all incoming $ for OC is from Tips only? 

Also, still don't like "Owed". What about "Platform Tip Due"

I understand you want to decide and move on, but think I can't be the only one still confused by this.  At the very least, we might need to bring a Glossary back into the docs

**Comment by alanna** [comment]
Yeah, "no platform fees" was always super clearly *for Collectives* while we always communicated that Hosts would be charged a platform fee through revenue sharing in the current pricing model.

I also still don't agree with the word "share" and think "platform share" is confusing. "Platform fee" is the only term that's general and well understood enough in the market that people will definitely understand it the first time they encounter it.

But... I'm trying to be pragmatic and accept @piamancini and @znarf's decision because we need to move forward and it's much better that "host fee share" which is what we have now. 

Same with using "owed" - it's not perfect but it's better than "debt". @kaylarep I think the issue there is it's not really "due" until we submit the settlement expense for it. This term has to cover the amount that will be charged *or* has already been charged in a platform settlement expense. So "owed" works, and so does "to pay", but "due" could be misleading.

**Comment by alanna** [comment]
@piamancini @znarf does the above feedback change anything or are we still sticking with the plan? I have been holding off on updating the pricing page for confirmation.

**Comment by piamancini** [comment]
@alanna we are sticking to the plan replacing Debt by Owed based on the latest feedback.

**Comment by alanna** [comment]
OK that's fine about using 'owed'. 

What about the feedback around 'platform fee' vs 'platform share'? I just want to be sure that we are sure before moving forward with updating the docs and pricing page.

@piamancini

**Comment by Betree** [comment]
> I just want to be sure that we are sure before moving forward with updating the docs and pricing page.

I would insist on that, making sure we have a consensus is important for moving forward. Updating the terminology has a very significant impact on translations since it invalidates them all, forcing the strings to be translated again.

**Comment by piamancini** [comment]
@alanna I understand the feedback, but in essence the fee is a share of the revenue, think affiliate programs or app store. 

I am not arguing that platform fee as a term per se is incorrect, I am just agreeing with @znarf that we've very recently moved out of having a fee which we called ´platform fee´ and we were very vocal about it. I don't want to roll back on that, it took us a lot of time to get to tips and revenue share model and I think that we should stick with it. 

Going back on it will imho bring more confusion, we will need to to more explaining than simply calling a revenue share, 'share'. Our model is: if you don't charge a fee yourself, we don't charge you because there's nothing to share. That is something people understand and I always, always feel how it makes sense to people when I am explaining it to them.

**Comment by alanna** [comment]
Ok this is resolved. Let's move forward with the changes.

**Comment by alanna** [comment]
Reopening because I realised we might want to track the transition steps on this issue

**Comment by alanna** [comment]
@znarf @piamancini can you confirm what we decided in the team meeting about the transition plan? From what I recall:

Easy-ish, can be done in the short term:

* Pricing page update
* Host dashboard reports
* Docs & marketing materials
* Front-end of the app 

Hard, will take longer:
*

**Comment by alanna** [comment]
I thought of another place to update that's hopefully easy: platform settlement expenses

**Comment by alanna** [comment]
I've updated the pricing docs page with a list of pricing terms and their meanings, as well as a rubric of previous terms people might see as we transition: https://docs.opencollective.com/help/about/pricing

**Comment by Betree** [comment]
Update on the project: I've updated the host reports with this terminology update. It's ready for review: https://github.com/opencollective/opencollective-frontend/pull/7199

**Comment by alanna** [comment]
Is this done?

**Comment by Betree** [comment]
The frontend was done in https://github.com/opencollective/opencollective-frontend/pull/7199. I'm not sure about the API, we may want to have an additional pass there https://github.com/opencollective/opencollective-api/blob/3c4b58ab27277d926916d0b448dbf2aae441d80b/templates/emails/host.report.hbs#L305

**Comment by alanna** [comment]
Can this be closed now?

**Comment by Betree** [comment]
We still show "Platform revenue share" in the [host report](https://github.com/opencollective/opencollective-api/blob/3c4b58ab27277d926916d0b448dbf2aae441d80b/templates/emails/host.report.hbs#L305), not sure if that's something we want to update.

Otherwise, no blocker for me to close.
