### ISSUE TITLE
`totalMoneyManaged` is Not Calculated Correctly

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4936]
The calculation of collective balance has an error and was pointed out at, https://opencollective.slack.com/archives/C02C146LFCP/p1636557626007700. The correct calculation is,

`totalMoneyManged = hostBalance + collectivesBalance`

**Comment by znarf** [comment]
There is still a consistency problem because Timerange filter is applied to totalMoneyManged but not to hostBalance (always the balance of today).

**Comment by SudharakaP** [comment]
> There is still a consistency problem because Timerange filter is applied to totalMoneyManged but not to hostBalance (always the balance of today).

Thanks for pointing it out. I've created PRs to filter the balance by date. 👍🏽
