### ISSUE TITLE
error when submitting an expense

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#494]
I was able to reproduce it
I tried, logged in, logged out, from the front page and directly to /expenses/new
<img width="1274" alt="screen shot 2017-10-12 at 10 57 52 am" src="https://user-images.githubusercontent.com/3671070/31502950-5f0ced04-af3c-11e7-9e11-c453f375a082.png">

It worked when I tried with an image I had but failed with her file. Converted the file to PDF and then I took a screenshot, still not working. Fails on mobile and desktop. 

![reciept1](https://user-images.githubusercontent.com/3671070/31503062-a39ffbb4-af3c-11e7-9141-f6c3056aaad8.JPG)

**Comment by asood123** [comment]
nginx issue. fixed.
