### ISSUE TITLE
Fund transaction list only shows debits

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4941]
I am trying to see when this contributor put the money in their Fund. But the transaction list is only showing debits when they contribute to other Collectives. Why is money coming in missing? Where are the credits?

https://opencollective.com/ford-foundation/transactions

**Comment by znarf** [comment]
It's not a Fund, it's an Organization. We don't compute their balance and their budget.

If we would, it would be negative as they effectively don't have CREDITs.

**Comment by alanna** [comment]
Ah ok I was confused
