### ISSUE TITLE
Showing as contributor but amount is $0

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4942]
This person is showing as a contributor to Open Collective but it's $0. If they haven't contributed anything, they should not appear here.

https://opencollective.com/seyed-abbas-shojaee

![Screen Shot 2021-11-12 at 12 23 10 PM](https://user-images.githubusercontent.com/5498878/141382958-eb1f2e7c-8a00-4c4b-8085-676b10e90eb3.png)

**Comment by znarf** [comment]
I originally deleted some spam transactions from this profile and didn't remove related Members entries. Done.
