### ISSUE TITLE
Edits to OCF's application page

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#4943]
**Describe the bug**
A few edits to make on OCF's hosting application (https://opencollective.com/foundation/apply/form)

1. The 'More info' link in the sidebar is dead. Please direct it instead to https://docs.opencollective.foundation/
![image](https://user-images.githubusercontent.com/64920686/141582472-c762b0b8-2466-4875-8ef7-f500fcabb8e3.png)

2.  This hover (?) doesn't show anything 
![image](https://user-images.githubusercontent.com/64920686/141583734-fefd1c8e-f75c-400f-94fc-6409f10ad532.png)

3. Can we add a hover (?) saying "This can be edited later"
![image](https://user-images.githubusercontent.com/64920686/141584732-0cc93823-0f8f-4c33-8c06-2842414a2ff7.png)

4. Please add to this title: "**What does your initiative do?** Please describe how you plan to use raised funds." -- either as a subheader, or in parenthesis; whichever looks best/is easiest.
![image](https://user-images.githubusercontent.com/64920686/141587500-c4627672-fcc8-4f6f-a1b8-ffc470ea2f72.png)

5. In this highlighted gap, can we add a tip saying:
![image](https://user-images.githubusercontent.com/64920686/141592611-3e4c9f6d-6ddc-499a-9b75-80efaedfe61f.png)
> ⚠️ Once your page is submitted, please be sure to have at least 2 admin (with First, Last Name) on your initiative's Team to ensure timely application processing. Instructions for adding admin [here](https://docs.opencollective.com/help/collectives/collective-settings/core-contributors).

**Comment by natehn** [comment]
Should more info actually just go to our main docs? Seems like that is separate from the mission/vision drop-down.

**Comment by alanna** [comment]
One thing the auditors pointed out is it would be good to explicitly document how the Collective's mission connects to OCF's mission areas (education, social impact, civic engagement). That would also be helpful for the approval process (e.g. an open source project with no specific social impact mission would be caught on that point and could be referred to OSC). Should we add a box for that?

**Comment by natehn** [comment]
@alanna one of the questions in the application, not shown in this issue, is "Please explain how your initiative furthers one or more of our [mission impact areas](https://docs.opencollective.foundation/about/mission-and-values#our-missions-impact-areas). Do you think that is enough?

https://docs.opencollective.foundation/getting-started/how-to-apply/application-questions

**Comment by alanna** [comment]
Ah yeah sorry missed that. If it's already in there that's all good.

**Comment by kaylarep** [comment]
> Should "More info" actually just go to our main docs? Seems like that is separate from the mission/vision drop-down.

Yea sure, works for me

**Comment by SudharakaP** [comment]
I've done some quick changes in the PR above but I think we need to clarify some things. 😄 

>     1. The 'More info' link in the sidebar is dead. Please direct it instead to https://docs.opencollective.foundation/

The more info link seems to be working now and it is directed to the OCF FAQ section; https://docs.opencollective.foundation/faq/basic-faq. Let me know if this is the best place we can redirect our users. 

>     2. This hover (?) doesn't show anything
>        ![image](https://user-images.githubusercontent.com/64920686/141583734-fefd1c8e-f75c-400f-94fc-6409f10ad532.png)

I've added the following to the tool-tip for now; `Tell us more about your collective. This information is private and only used for internal purposes.` Let me know if there's better wording for this one? 🤔 

>     3. Can we add a hover (?) saying "This can be edited later"
>        ![image](https://user-images.githubusercontent.com/64920686/141584732-0cc93823-0f8f-4c33-8c06-2842414a2ff7.png)

Maybe a parenthesis fits better since we are already using parenthesis for the one below and also the user can see it directly? 🤔  
 
>     4. Please add to this title: "**What does your initiative do?** Please describe how you plan to use raised funds." -- either as a subheader, or in parenthesis; whichever looks best/is easiest.
>        ![image](https://user-images.githubusercontent.com/64920686/141587500-c4627672-fcc8-4f6f-a1b8-ffc470ea2f72.png)

Done in parenthesis.

>     5. In this highlighted gap, can we add a tip saying:
>        ![image](https://user-images.githubusercontent.com/64920686/141592611-3e4c9f6d-6ddc-499a-9b75-80efaedfe61f.png)
> 
> 
> > warning Once your page is submitted, please be sure to have at least 2 admin (with First, Last Name) on your initiative's Team to ensure timely application processing. Instructions for adding admin [here](https://docs.opencollective.com/help/collectives/collective-settings/core-contributors).

Done. 👍🏽 

The final result looks like this; 

![ocf-form](https://user-images.githubusercontent.com/12435965/142509658-e00505e8-693c-45ee-93c6-5cfed7552867.gif)
