### ISSUE TITLE
Unable to update expense payee to Collective

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4947]
I invited [this expense](https://opencollective.com/comms-docs/expenses/55256) with the payee being the [Metagov Collective](https://opencollective.com/metagov). However, the invitee changed it to be payable to an outside company. That won't work for this particular expense, so I need to change it back to the Collective as the payee. But when I edit the expense and try to select the Collective, nothing happens. It appears the profile search box isn't doing anything, and no options come up. Normally there would be three dots while searching and then a list of options. It's weird because I was able to search and select it fine when I invited it in the first place.

<img width="456" alt="Screen Shot 2021-11-14 at 3 57 27 PM" src="https://user-images.githubusercontent.com/5498878/141665729-6481f134-d0bd-4a63-832e-f28ac8eb487e.png">

**Comment by alanna** [comment]
I'm having the same problem with [this expense](https://opencollective.com/di-incubator/expenses/55169). The payee needs to be the [CDP Collective](https://opencollective.com/council-data-project), but it won't let me edit it. I search and nothing appears. In this case it's a Collective in the same host so I don't see why it would be blocked.

**Comment by Betree** [comment]
It's a limitation, not a bug: you can only select profiles you're an admin of as payees. The reason why we allow any profile to be selected when inviting is that the profile's admins need to confirm the invitation and review the expense first.

If we just let people select any profile when editing an expense, we'll end up with a security issue where you can create an expense, select any profile as the payee and put your own payout method there. Example: submit an expense to Babel, edit it to select the payee to one of Babel's admins, and set your own PayPal account there.

The normal flow here would be to ask the expense submitter to update it. I'll manually update these two to unblock the situation.

**Comment by Betree** [comment]
@alanna Should I proceed with these changes?
- Update https://opencollective.com/comms-docs/expenses/55256 to have https://opencollective.com/metagov as the payee, set the payout method to "Collective balance"
- Update https://opencollective.com/di-incubator/expenses/55169 to have https://opencollective.com/council-data-project as the payee, set the payout method to "Collective balance"

**Comment by alanna** [comment]
Yes please! Thanks @Betree 

The only part in not sure about is the metagov one being across hosts, will that work? If not it can be a bank transfer.

**Comment by alanna** [comment]
@Betree can you let me know when this has been done?

**Comment by Betree** [comment]
@alanna I've updated https://opencollective.com/di-incubator/expenses/55169.

> The only part in not sure about is the metagov one being across hosts, will that work? If not it can be a bank transfer.

I'm not sure about this one, and I prefer not touching things in the DB until we make sure that's ok. Asking @znarf for feedback.

**Comment by znarf** [comment]
@Betree If we start editing things by hand and put them in a state that is not supported, this can certainly lead to bugs when marking as paid. To be clear, if something is only achievable by editing manually, then it's not supported. In the end, will that work? I can't really answer.

If we reach a point where we have a Transaction inserted in the ledger:
- I can review it to make sure it's properly recorded and consistent
- someone needs to make sure to funds are moving from one Host to the other (offline bank transfer)

**Comment by alanna** [comment]
Thanks for fixing that one @Betree . I talked to @znarf and I'm going to just delete the other one and start over so this is done.
