### ISSUE TITLE
Event time wrong

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4950]
https://opencollective.com/opencollective/events/fiscal-host-call-dec-2021-4863d3c9

I set the time in CET:
![Screen Shot 2021-11-16 at 10 19 27 AM](https://user-images.githubusercontent.com/5498878/141855380-b74b93e3-3555-4fee-99ed-45099eb486e5.png)

But it seems to be saved in my time, which is 12 hours opposite:
![Screen Shot 2021-11-16 at 10 19 07 AM](https://user-images.githubusercontent.com/5498878/141855408-02dee3c1-b068-46b3-874e-ba1e7f16f601.png)

**Comment by znarf** [comment]
@alanna this was tentatively fixed in https://github.com/opencollective/opencollective/issues/4865.

Could you confirm?

**Comment by alanna** [comment]
Yes it looks correct now, thanks.
