### ISSUE TITLE
Unlock Expense on error

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4956]
When paying Expenses through Transferwise, a `isLocked: true` flag is set.

If the payment end up with an error, the `isLocked: true` will not be deleted and it will be impossible to try to pay the Expense again without human intervention.

This is happening regularly (check support).

**Comment by Betree** [comment]
@znarf I think this is another case for `return await`. I've opened a fix in https://github.com/opencollective/opencollective-api/pull/6860
