### ISSUE TITLE
Redirect to Collective page after removing self as admin

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4957]
If you remove yourself as an admin from a Collective, you see a couple error messages that aren't relevant (these things are obvious; you just removed yourself).

![Screen Shot 2021-11-18 at 10 52 04 AM](https://user-images.githubusercontent.com/5498878/142288500-c1396bd3-6868-49bb-a5d2-56bf59b9d3fe.png)

![Screen Shot 2021-11-18 at 10 51 50 AM](https://user-images.githubusercontent.com/5498878/142288486-180ba06e-0d6d-464a-8bcd-d12348e7adb5.png)

Instead of trying to reload the team settings page, it should redirect you to the main Collective page for a better experience.

**Comment by Betree** [comment]
My understanding is that you first clicked `Remove`, then right after `Save`. The second message (`Failed to update member`) is related to the second action. If you just click on remove, we close the modal after a short loading time and only show the `Member removed successfully` toast, not the error one. The `You need to be logged in as an admin` message however pops in all cases.

Steps to fix this UX:
- We shouldn't allow clicking on save after clicking `Remove`. The remove button should be in a loading state, and the save one too (or at least disabled).
- When the remove mutation completes:
  - Either the removed user is someone else => refetch the list of core contributors
  - Or removed user is the logged in one => redirect to the collective page like @alanna suggested

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by Betree** [comment]
:trophy: This issue has been completed by @leonardohofling  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
