### ISSUE TITLE
Integration with Wise working slowly and generating an error message

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#4963]
**Describe the bug**
When trying to process an expense that was initiated as a bank transfer, there is a long processing period at the end of which a message of network error is received. This is happening to a few host admins so it doesn't seem to be a local issue. 

Then when the page is refreshed the expense seems to go through and is reflected on Wise correctly. This situation though, slows the processing of expenses by quite a bit and should be looked into. 

**To Reproduce**
1. Go to Admin dashboard --> Expenses and select an expense that is ready to be processed for payment and has been reviewed as ok to pay. 
2. Click on Go to Pay and go through the standard automatic payment with Wise.
3. See error:

![capture](https://user-images.githubusercontent.com/57156267/142523302-c0be5da0-5802-4d5f-9c0f-1e0020f844b6.png)

**Expected behavior**
There should be no lag or any issue with the processing.

**Comment by znarf** [comment]
Debugging this with https://github.com/opencollective/opencollective-api/pull/6878

**Comment by znarf** [comment]
Just did a test with the Open Collective account and it was fast:

<img width="1430" alt="Screenshot 2021-11-23 at 15 39 37" src="https://user-images.githubusercontent.com/806/143044703-76c002ff-e2d2-4a3a-ab7b-1e742799561a.png">

**Comment by znarf** [comment]
Today, we had one timeout with the following metrics:

<img width="1399" alt="Screenshot 2021-11-29 at 12 24 18" src="https://user-images.githubusercontent.com/806/143859692-61d30152-ea74-4a84-a9aa-c0e3239cb022.png">

**Comment by kewitz** [comment]
@alinamanko this is not related to any specific host but to the time Wise takes to reply to the request. This can vary with Wise API usage and it is out of our control.

I'll spec out a refactor to bring trigger initial quotes when we open the expense payment modal to see if we can reduce this.

**Comment by znarf** [comment]
I would recommend to move to an async process, or a partly async process, instead of trying to do everything synchronously. We have a budget of 25 seconds to answer synchronously.

**Comment by Betree** [comment]
Looks like this is resolved, @alinamanko have you seen this problem since?
