### ISSUE TITLE
OCF profile shows up twice as payment method

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4964]
When contributing from OCF to a Project under the OCF host org:

![Screen Shot 2021-11-19 at 2 11 47 PM](https://user-images.githubusercontent.com/5498878/142525970-e0ec234e-429c-432a-8b70-1d13df5225de.png)

**Comment by znarf** [comment]
List of accounts in such situation:

```
SELECT "CollectiveId", COUNT(*)
FROM "PaymentMethods" WHERE "deletedAt" IS NULL
AND "type" = 'collective'
GROUP BY "CollectiveId"
HAVING COUNT(*) > 1
```
