### ISSUE TITLE
Some Projects not showing on host dashboard

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4971]
[These projects](https://opencollective.com/atx-mental-health-fund/projects) exist:
![Screen Shot 2021-11-22 at 8 45 24 PM](https://user-images.githubusercontent.com/5498878/142822637-e1fd4cd2-79af-4232-8f95-fb3138c76b2d.png)

But many of them do not show up on the hosted collectives tab in the host dashboard (only some do):
![Screen Shot 2021-11-22 at 8 46 08 PM](https://user-images.githubusercontent.com/5498878/142822687-3c051d4a-7abb-42aa-af6c-77d64f03c509.png)

I need to access the IL, LO, and EF Request projects settings to turn on grant expenses.

**Comment by znarf** [comment]
Could be https://github.com/opencollective/opencollective/issues/4938

**Comment by alanna** [comment]
Please manually turn on grant expenses for the Project mentioned in #5032

**Comment by znarf** [comment]
@alanna It should appear in the Host Dashboard now.
