### ISSUE TITLE
Projects showing negative balances

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4972]
![Screen Shot 2021-11-22 at 8 46 18 PM](https://user-images.githubusercontent.com/5498878/142823019-60b148ef-8dda-42cf-a7b7-bc09a497dce7.png)

![Screen Shot 2021-11-22 at 8 51 31 PM](https://user-images.githubusercontent.com/5498878/142823225-4770d55b-a980-4c1d-9a79-6209fe7293fa.png)

There appear to be several like this.

**Comment by znarf** [comment]
Looks like https://github.com/opencollective/opencollective/issues/4953

**Comment by alanna** [comment]
This is still ongoing. Any update? There are a lot of them now.
![Screen Shot 2021-12-13 at 5 07 12 PM](https://user-images.githubusercontent.com/5498878/145750921-20a7b965-dac2-450d-917b-0e61523aaa41.png)

**Comment by znarf** [comment]
@alanna you can follow updates in the issue I shared above https://github.com/opencollective/opencollective/issues/4953

**Comment by znarf** [comment]
Closing, we will be tracking this here https://github.com/opencollective/opencollective/issues/4953
