### ISSUE TITLE
[PROJECT] More Payment Methods using Stripe Elements

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#4974]
## Overview 

With Stripe Elements, it's now possible to collect more Payment Methods. https://stripe.com/payments/elements

We would like to explore and see which new Payment Methods we could support using this strategy.

We generally want to prioritize:
- Payment Methods that are acceptable on a maximum of Fiscal Hosts
- Payment Methods that can be used as recurring using our current recurring contribution strategy

This project is not about delivering a working feature.

**Comment by BenJam** [comment]
might be best to prototype this initially to propose an experience which ties stripes payments methods with our own (collective to collective etc).

**Comment by BenJam** [comment]
as an aside, we could look in the future at how best we support payments in the currency of the contributor (if different from the currency of the collective).

**Comment by BenJam** [comment]
- [ ] schedule kick off for this week
- [ ] prototype two flows
- [ ] get testing on Apple pay sorted 💸

**Comment by hdiniz** [comment]
Enabled payment methods on Stripe connected accounts (host) can be controlled by the Stripe platform account (OC inc). I recommend we only enable payment methods which have gone through the checklist below.

  - [ ] Can it be saved for later use? Required for recurring contributions and easy checkout,  also requires update to frontend contribution flow to reuse the PM.
  - [ ] Can it be refunded? If not, refund flows have to be disabled for orders with this PM.
  - [ ] How dispute works?
  - [ ] What are the processing fees? To display correctly in checkout summary and order.
  - [ ] How to display and format the payment method on orders or when saved and presented during checkout.
 
In general:
- [ ] Update `createPaymentIntent` mutation to use automatic allowed payment methods. Stripe decides based on platform configuration, presentment currency, amount and host country.
- [ ] Update frontend contribution flow to filter saved Stripe payment methods based on methods allow for the payment intent.
- [ ] Update payment intent succeeded webhook as source of truth for the payment method used for the order.
- [ ] Use payment method attached webhook as source of truth for payment methods attached to a customer account.

Apple Pay and Google Pay.

- Are a special case of credit card payments, it is a card payment method with added metadata about which wallet was used.
- Google Pay requires Chrome with a connected Google account and the frontend running on HTTPs to work when developing.
- Apple Pay can be tested using Safari on macOS, requires a domain verification for opencollective.com with Stripe/Apple.

---

Frontend/UX

The changes above would be needed independently of the flow we choose for the frontend.
For UX we have two options.

_Using Stripe Payment Element_

This is a single component that Stripe renders, where the user can pick a payment method option for the list of allowed methods.

![image](https://user-images.githubusercontent.com/5448927/212915107-b9b59d62-5c8c-434e-82d5-f3a434833f53.png)

  Pros
  - Easier to integrate, the Payment Element takes care to render the form for each payment method option.
  - Styling. There are css/style customization options.

  Cons
  - UX. Limitis how we can present each payment method option as they are all bundled inside a single Stripe iframe.
  - UX. Using automatic method seletcion will always include card as an option, duplicating in the iframe the card option that we already have.
 
_Using individual elements_

![image](https://user-images.githubusercontent.com/5448927/212915221-70bcc61b-7cc1-4b3f-9d4a-281228ebb0c4.png)

  Pros
  - UX. We have better control of the UX, we can present options individually and render them as we want.
  
  Cons
  - For each payment method added we need use the either use a Stripe provided element or in case it does no exist (e.g. ACH) we need to build a form to gather the payment details. (e.g. account numbers, billing details, validations, etc).

**Comment by BenJam** [comment]
- [ ] taking a look at some of the feedback form last week (bank option appearing twice, saving payment methods for wallets etc)
- [ ] add BACS payments in the UK

**Comment by Memo-Es** [comment]
### Week 4
 - [ ] Design and UX review

**Comment by hdiniz** [comment]
[ ] UK Bacs Payment Method pull requests in review
[ ] Google and Apple Pay are available, need docs for hosts to enable Apple Pay on Stripe.

**Comment by BenJam** [comment]
- [ ] @BenJam @shannondwray to walk through documentation
- [ ] decide on approach re. direct bank transfer vs. stripe based bank transfer w/ @Memo-Es @BenJam @natehn and @hdiniz

**Comment by hdiniz** [comment]
- [ ] Add E2E tests to cover Stripe Payment Element contribution flow
- [ ] Test bancontact as a payment option

**Comment by hdiniz** [comment]
- [ ] Test iDEAL payment option

**Comment by BenJam** [comment]
@hdiniz did we ever add the notice if someone added a payment method from Apple/Google? seems like a nice lil improvement. I will get the documentation done this week

**Comment by znarf** [comment]
Feedback issue: https://github.com/opencollective/opencollective/issues/6290
