### ISSUE TITLE
[PROJECT] Design work on expenses and transactions

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#4980]
## Overview
We are bundling up some issues regarding expenses+transactions, so we have complete visibility on the changes regarding the budget features and merge/push to implementation all of them.

## List of issues/goals
- [x] #1073 
- [x] #4751 (Continuation)
- [x] #4785 (Production files)
- [x] https://github.com/opencollective/opencollective/issues/4874
- [x] #4984

**Comment by Memo-Es** [comment]
**Plan for this week**

- [ ] #1073 
- [ ] #4751 (Continuation)
- [ ] #4984

**Comment by Memo-Es** [comment]
Plan for this week / W3S2Q4 - Week 49

- [ ] #1073 
- [ ] #4751 (Continuation)
- [ ] #4984

**Comment by piamancini** [comment]
- [ ] Transactions list filters redesign #4984

**Comment by piamancini** [comment]
- [ ] seek feedback

**Comment by Memo-Es** [comment]
Closing this to track transactions updates and expenses updates on separated issues:

https://github.com/opencollective/opencollective/issues/4874
https://github.com/opencollective/opencollective/issues/4785
