### ISSUE TITLE
[PROJECT] Marketing pages - E2C

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#4981]
## Overview
We are putting up a page to explain all the exit to community ideas, a.k.a. e2c

**Note:** Images are not final

| Desktop | Tablet Landscape | Tablet Portrait | Mobile |
|---------|------------------|-----------------|--------|
|  ![Desktop](https://user-images.githubusercontent.com/49539954/144969834-e01eebec-57b0-4760-a8fb-04633fe26747.png)   |  ![Tablet Landscape](https://user-images.githubusercontent.com/49539954/144969847-5bf6af71-095f-4fdf-9899-2f73f82ab06a.png)    |   ![Tablet Portrait](https://user-images.githubusercontent.com/49539954/144969849-4ee53fcd-7077-4dfe-9128-064317f26d1a.png)      | ![Mobile](https://user-images.githubusercontent.com/49539954/144969844-21a2a16d-135c-45c8-b682-036ec93de9eb.png)  |

[Design file in figma](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=15197%3A211981)

**Comment by Memo-Es** [comment]
Plan for this week / W2S2Q4 - Week 48

- [ ] Fill in issue details
- [ ] Wireframes 2nd stage (How to get to e2c)

**Comment by BenJam** [comment]
Plan for this week / W2S3Q4 - Week 49

- [ ] Fill in issue details
- [ ] Wireframes 2nd stage (How to get to e2c)
