### ISSUE TITLE
Deprecate "Host Metrics" admin page

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4989]
The new report seems to cover all the metrics presented there.

1. [x] Show a link in the section like "Go to the new reports", clearly stating that this one will go away soon
2. [x] After a few weeks/months, remove the page

Ping @znarf

**Comment by znarf** [comment]
One metric is not super accessible, the previous "Pending Host Fee Share" is buried in the historic graph as "Host Fee Share (owed)" but that's not a huge issue I guess.
