### ISSUE TITLE
 Add a link to export to CSV on collective

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#499]

**Comment by piamancini** [comment]
@xdamman putting this as high priority to work after emails

**Comment by SunburnedGoose** [comment]
This is important to me as I use it in my workflow to create our thank you content every month for contributors.

**Comment by piamancini** [comment]
thanks @SunburnedGoose we'll get this done soon! do you need the export now? I can manually generate it for you

**Comment by xdamman** [comment]
Deployed to prod. Just head to your collective page and click on "EDIT". There is a new "Export" tab.
