### ISSUE TITLE
Refunding Transaction from Collective to Itself

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4992]
This is initially discussed at, https://github.com/opencollective/opencollective-api/pull/6887#issuecomment-977899304. We don't currently support refunding a transaction made from a collective to itself. For example adding funds to a collective selecting the `Source` as the same collective and then trying to refund this transaction will hit an error (after https://github.com/opencollective/opencollective/issues/4369 is completed it will show a more user friendly error such as; `Cannot refund a transaction from the same collective`).

We need to think about what we should do here. My thoughts are,

1) The word refund doesn't really make sense in the front-end in this case as we are refunding to the same collective. 
2) Even if we do create refund transactions might be confusing when looking at the transactions list. 

I propose that in this case the host admins should be able to remove the transaction and in the UI instead of `refund` it should show `remove` maybe? And when clicked on this a confirmation box appears (similar to the refund case) but after confirming the transaction should be soft deleted and should not appear on the UI. 

Does this sound reasonable? If there's any alternative suggestions let me know. 🤔 

cc: @znarf @Betree

**Comment by znarf** [comment]
It's an edge case and we should not overthink it. As a matter of simplicity, I would not touch anything on the Frontend side.

On the API side, I'm fine with soft-deleting as a first temporary measure if creating a real Refund transaction is complicated.

**Comment by znarf** [comment]
Would be great to tackle this.
