### ISSUE TITLE
Attachment previews not working

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4993]
There are several issues with the attachment previews. I think we should either fix them or just remove this entirely as it's not really working.
![Screen Shot 2021-11-25 at 10 51 39 AM](https://user-images.githubusercontent.com/5498878/143317365-85167334-acc3-48e3-bfbb-4f4b91320dde.png)

If you click "attachment preview"...

1. The system generated invoice automatically downloads. This is not what someone would expect clicking 'preview'.
2. If you click the next arrow, you see the below, which is also not a preview. If you click it, it downloads, which again is not what's expected.

![Screen Shot 2021-11-25 at 10 50 13 AM](https://user-images.githubusercontent.com/5498878/143317487-ab0714a0-8d87-4ee0-81f0-40acc0d1c93a.png)

How it should work:

* The system generated file should not be treated as an attachment or included in this preview function at all (#3865).
* The actual file should be previewed in the modal.
* Nothing should download without further action from the user to intentionally do so.

**Comment by Betree** [comment]
> The system generated file should not be treated as an attachment or included in this preview function at all (Do not treat system-generated expense summary as an attachment #3865).

I agree with this one

> Nothing should download without further action from the user to intentionally do so.

@alanna what browser are you using? On Firefox/Chrome Linux I don't get the auto-download

![image](https://user-images.githubusercontent.com/1556356/143400985-72eb5eff-7ce9-4f84-9b1b-f07f76e5766d.png)

> The actual file should be previewed in the modal.

There indeed seems to be a problem with the PDF preview, we need to investigate that

**Comment by alanna** [comment]
The system generated invoice downloaded as soon as I click "preview
attachments". The other file downloaded when I clicked it (which I did
because the preview wasn't showing and I thought I might need to click to
see it).

**Comment by Betree** [comment]
@alanna What browser do you use?

**Comment by alanna** [comment]
Firefox

**Comment by alanna** [comment]
This is still happening. I think we should remove the "attachment preview" option until we can make it work, because it just seems broken.

<img width="662" alt="Screen Shot 2022-06-27 at 9 17 00 AM" src="https://user-images.githubusercontent.com/5498878/175834189-0776067c-b79a-4aa5-8e70-a12924170e3f.png">

**Comment by gustavlrsn** [comment]
Closing this as this attachment previews was replaced by the files viewer modal in https://github.com/opencollective/opencollective-frontend/pull/8899
