### ISSUE TITLE
Calculation of Host Balance is Incorrect when Filtered on Date

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4994]
This was initially mentioned at, https://opencollective.slack.com/archives/C02C146LFCP/p1637764114003400. It seems that in the total money managed section we calculate the host balance incorrectly when filtered on dates. In fact since `totalMoneyManaged` is always static we should not filter the host balance based on dates.

**Comment by znarf** [comment]
> In fact since totalMoneyManaged is always static

Where is this coming from? I clearly stated.

> totalMoneyManaged is computed **at a given date**, not on an interval

**Comment by SudharakaP** [comment]
> > In fact since totalMoneyManaged is always static
> 
> Where is this coming from?
> 
> In the linked discussion, I clearly stated:
> 
> > totalMoneyManaged is computed **at a given date**, not on an interval

Sorry, I was somehow confused on this one and when I look at this again I realize the above statement is wrong. Yes it doesn't make any sense. 😢
