### ISSUE TITLE
Fix transactions historical view in host report

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#4995]
Followup on https://github.com/opencollective/opencollective/issues/4658

The section introduced in https://github.com/opencollective/opencollective-frontend/pull/6918 (and hidden in https://github.com/opencollective/opencollective-frontend/pull/7189) does not work at all, it displays empty data for all fiscal hosts regardless of the selected period. This is mostly related to the handling of the `timeUnit` that is not consistent between frontend and API. We need to:
- [x] Adopt an automatic `timeUnit` behavior on API for `contributionAmountOverTime` and `expenseAmountOverTime` based on the `dateFrom`/`dateTo`
- [x] In the frontend, fetch this `timeUnit` for both fields and use it in `TransactionsOverviewSection` to build the legend and group the data

**Comment by petervaldaz** [comment]
🪴🪴❤️🪴🪴
