### ISSUE TITLE
Update "Become a Backer" and "Become a Sponsor" buttons

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#50]
They could use some design love ❤️ 

![](http://cl.ly/1r0i1s1T2u1B/Screen%20Shot%202016-04-27%20at%209.58.52%20AM.png)

**Comment by xdamman** [comment]
Thinking more about this, we should also have a section for "Contributors".

**Comment by xdamman** [comment]
Which means that we also need a button "Become a contributor"

**Comment by xdamman** [comment]
Any update on this @cuiki ?

**Comment by erickrico** [comment]
im going to be working on this, let me give does "buttons" a level up!

**Comment by erickrico** [comment]
![sponsor-btn](https://cloud.githubusercontent.com/assets/18429104/14929365/b7525484-0e22-11e6-9bdf-b2cbc4345f23.png)
![backer-btn](https://cloud.githubusercontent.com/assets/18429104/14929367/b760cf8c-0e22-11e6-8aec-a58060182f4c.png)

**Comment by piamancini** [comment]
I'm not a fan of the type colour

P.
piamancini.com
t: @piamancini
s: piamancini
OpenCollective <https://opencollective.com>

**Comment by erickrico** [comment]
ya, you are right.    
![become-backer](https://cloud.githubusercontent.com/assets/18429104/14970088/dad4c836-108b-11e6-8d87-2a2b39e568cd.png)
![become-sponsor](https://cloud.githubusercontent.com/assets/18429104/14970089/daeccfb2-108b-11e6-8c7c-c78f59f25fbd.png)

**Comment by xdamman** [comment]
Can you put that in perspective of a GitHub repo? (See screenshot above). Maybe we should also experiment with rounded avatars? It would be good to have a strong identity there.

**Comment by erickrico** [comment]
in terms of identity it would be a good idea to have rounded avatars like the ones on the collectives ui, it would look something like this 
![context](https://cloud.githubusercontent.com/assets/18429104/14970446/94216efa-108e-11e6-89a5-8548bcadc03f.png)

**Comment by piamancini** [comment]
I would replicate de rounded avatar with the button, so it looks more
coherent. Also, we should use our blue and our dark grey for the colors.


P.
piamancini.com
t: @piamancini
s: piamancini
OpenCollective <https://opencollective.com>

**Comment by xdamman** [comment]
Yeah also not a fan of the shadow. Keep it simple.

**Comment by erickrico** [comment]
buttons with opencollective colors and no shadows 😁 

![backer-btn](https://cloud.githubusercontent.com/assets/18429104/14990824/0b6d76e4-1124-11e6-9868-3d9f6e177dbe.png)
![sponsor-btn](https://cloud.githubusercontent.com/assets/18429104/14990825/0b7e8b46-1124-11e6-8787-7d3a0978a02b.png)

**Comment by piamancini** [comment]
@erickrico do you need this still open?

**Comment by erickrico** [comment]
not really, unless you feel don't feel confortable with the buttons

**Comment by piamancini** [comment]
@erickrico great. Send us the files via slack then. so we can update them thanks
