### ISSUE TITLE
Transactions Page: Exclude Gift Card transactions filter is not working

### ISSUE THREAD

**Issue by snitin315** [opencollective/opencollective#5008]
**Describe the bug**

Exclude Gift Card transactions filter isr not working

**To Reproduce**
1. Go to any collective's transaction page
2. Click on `Exclude Gift Card transactions`
3. See error

**Expected behavior**

Gift card transactions should be filtered.

**Screenshots**

https://user-images.githubusercontent.com/46647141/144159996-41d58804-d60b-4547-b587-4afc61a13294.mov

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser - firefox

**Smartphone (please complete the following information):**
Any

**Additional context**

No

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
The flag gets passed from the frontend, looks like an API issue

![image](https://user-images.githubusercontent.com/1556356/144189993-a31134ca-a52c-4708-bb75-610c1e9e648f.png)

**Comment by znarf** [comment]
Uhm, I think it used to work? :-)

The API param is `includeGiftCardTransactions` and here we're passing `includeGiftCardsTransactions`.

**Comment by znarf** [comment]
Oh, the original point of "Exclude Gift Card transactions" is for cases like Salesforce https://opencollective.com/salesforce/transactions to exclude Transactions coming from Gift Cards issued by Salesforce. It works fine in this context.

In the linked case, it's not the same case and there is no reason to "Exclude Gift Card transactions", at least that's not the spirit of it.

The checkbox should then not appear.
