### ISSUE TITLE
fix invoice preview in front end expenses list

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#501]
receipt preview is not loading on the front end transactions list. They are loading on the front
end expense list.

**Comment by nicobarretoOC** [comment]
@Pia I have this report from WWCode Portland:

> > I'm digging the new OC front end - congrats! 
> 
> One change that I noticed is that you can no longer view receipts from the page, so I'm having to back and forth between email. Not sure if that's intentional or a bug? 
> 
> You can see an example here: https://opencollective.com/wwcodeportland 
> 
> Nothing happens when you click the receipt for the $172 item.

**Comment by piamancini** [comment]
fixed
