### ISSUE TITLE
Ticket Tiers Not Showing

### ISSUE THREAD

**Issue by aomuse** [opencollective/opencollective#5012]
The ticket tiers have disappeared on an [event page](https://opencollective.com/foundation/events/ocf-monthly-forum-dec-2021-151f535e) which I created. Seven people have registered for the event which indicates that the ticket tier was visible at some point. Now when I navigate to that page or my other events, I can see neither the original free ticket tier nor a paid tier which I added to test if there was a bug. A recording of the presentation under both my OCF admin account and a standard user account are included in the recording.

https://www.loom.com/share/596b927fb68c487481df5b05a6e7f112

**Comment by Betree** [comment]
Looking at the settings of the event, it seems that the contribute section was disabled. @aomuse could you check on https://opencollective.com/foundation/events/ocf-monthly-forum-dec-2021-151f535e/admin/collective-page and let me know what you see there?

**Comment by aomuse** [comment]
@Betree Alright. That addressed it, but I did not remember these two functions being tied together like this in previous events. In looking at the old events, I guess I was incorrect. Thanks.
