### ISSUE TITLE
Allow users to update more things directly from the collective page instead of having to go to settings

### ISSUE THREAD

**Issue by snitin315** [opencollective/opencollective#5013]
## User story 

As a user, I want to be able to edit my social links, short description, team members, etc, directly from the home page. So, I don't have to navigate to the settings page.

## Best solution for this problem

Add a button near links that will show a form/modal to update the respective fields.

<img width="228" alt="Screenshot 2021-12-03 at 1 32 19 PM" src="https://user-images.githubusercontent.com/46647141/144568010-81a48c22-afed-4b14-ab02-0fd63e5f8be4.png">

## MVP

Something similar to GitHub.

https://user-images.githubusercontent.com/46647141/144568436-0ffc3b8f-01ae-45fe-afe5-4927ffde0bde.mov

  P1 high frequency, high impact

**Comment by Udit-takkar** [comment]
Can I work on this one? @snitin315

**Comment by snitin315** [comment]
I think we will need some input from the design team on this before starting implementation.

**Comment by Udit-takkar** [comment]
Ok

**Comment by alanna** [comment]
Adding this related comment from @carolineawoolard

> As a collective admin I tried for weeks to double click on the text about my group only to give up and think "I guess I can't change it." I want to be able to edit the text about my group directly, as I can edit the logo and image on my page, in addition to going into the settings panel. See [this Loom about it](https://www.loom.com/share/3f20f2691f97422eabae49d9cff220ad)

**Comment by shannondwray** [comment]
Due to the establishment of the Dashboard it is unlikely that we would enable this functionality. We have been actively moving all functions to the Dashboard. Due to this I will close this issue.
