### ISSUE TITLE
Int cannot represent non 32-bit signed integer value: 2978000000

### ISSUE THREAD

**Issue by Lucifer1590** [opencollective/opencollective#5017]
**Describe the bug**
When going to Open collective Homepage and sorting the "ALL COLLECTIVE" to newest an error occurs
**To Reproduce**
1. Go to 'https://opencollective.com/discover'
2. sort from most popular to newest

**Expected behavior**
All the available projects should be sorted to the newest

**Screenshots**
![ss1](https://user-images.githubusercontent.com/72858502/144755462-af5fef25-3fba-4845-a432-a14ac4e4a0dc.jpg)
**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [94.0.2 (64-bit)]

**Additional context**
Alternatively, you can also go to this URL- [HERE](https://opencollective.com/discover?offset=0&sort=newest)

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritization. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by SudharakaP** [comment]
@Lucifer1590 : Thanks much for reporting this issue. We are aware of this problem and tracking this issue at, https://github.com/opencollective/opencollective/issues/4944.
