### ISSUE TITLE
Improve validations when inviting expense payee

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5020]
On the first step of inviting someone to submit an expense, the validations are not the most intuitive:
- It says `Fields marked with (*) are mandatory` but none of the fields has an asterisk. + that's not a pattern we use elsewhere.
- The "Next" button is disabled, and we don't tell the user why
- The `Add a note for the recipient` field is optional, but we don't show `(Optional)` as we do in other forms

Proposal:
- [x] Always enable "Next", show errors inline if it's not possible to go next
- [x] Add an `(Optional)` to the label for notes to the recipient
- [x] Remove the `Fields marked with (*) are mandatory` sentence

@opencollective/design any blocker with that proposal?

![image](https://user-images.githubusercontent.com/1556356/144981812-22baaa9e-bc9b-47d0-a5cd-bdf77361843b.png)

**Comment by znarf** [comment]
We reviewed this one collectively yesterday and this would be a clear and simple improvement.

**Comment by Memo-Es** [comment]
Thank you for putting this up @Betree, I agree with what you say here:

> Proposal:
-Always enable "Next", show errors inline if it's not possible to go next
-Add an (Optional) to the label for notes to the recipient
-Remove the Fields marked with (*) are mandatory sentence

Looks simple, so we should prioritize it for next sprint
