### ISSUE TITLE
Standardize the way we abbreviate large amounts

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5021]
In the most recent design for host reports, amounts are abbreviated as `7k` in the charts. There was some feedback about the lack of currency being confusing in there (would have expected `$7k`) and some questions about what should we do with really large numbers (e.g. $7,000k, should we use a `,`? should we switch to `m` abbreviation `$7m`?).

The answer to these questions depends on the locale. The goal of this issue is only to define a sensible default for the default locale, English US.

As a starter, I'm proposing the following:
- $4,000 => $4k
- $4,000,000 => $4m
- $4,000,000,000 => $4b

Based on https://www.imperial.ac.uk/brand-style-guide/writing/numbers/money-and-currencies/.

![image](https://user-images.githubusercontent.com/1556356/144991489-73bd324a-0bac-4ee6-a0de-26a3207306ea.png)

**Comment by natehn** [comment]
Because of [differences from country to country](https://abbreviations.yourdictionary.com/different-abbreviations-thousand-million-billion), it might better to use `mil` for million and `bil` for billion. Or if we are using the UK langiage, just changing `b` to `bn` for billion.

**Comment by alanna** [comment]
If we are focusing on the US locale defaults, then yes, that style mentioned is best. Yes use commas, and the currency symbol ($).

    > $4,000 => $4k
    > $4,000,000 => $4m
    > $4,000,000,000 => $4b

You can also use decimals like $4.5k for $4,500 if needed.

**Comment by kaylarep** [comment]
yes to always including the currency symbol.

**Comment by natehn** [comment]
The US convention is actually capitalized for million and billion, to be clear - M, B

**Comment by SudharakaP** [comment]
@Betree : I've suggested a PR above where we use the `Intl.NumberFormat` constructor to make sure we handle these amounts in a more generic way so that the legend amounts are supported for all locales. This uses for example the capitalized million and billion; M, B as @natehn suggested for en-US locale which I think is appropriate. 🤔 Let me know what you think or if you see any issues. 😉
