### ISSUE TITLE
Help and support pages — GitBook Search Integration

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5022]
When a user performs a search on the help and support pages we should search and link to content on GitBook if there's a match. 

- GitBook search API https://developer.gitbook.com/rest-v1/search 
- Design files https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=14465%3A179840

**Comment by znarf** [comment]
On docs.opencollective.com (what we want to replicate), the search is directly powered by Algolia, not GitBook API.

<img width="750" alt="Screenshot 2021-12-13 at 20 33 47" src="https://user-images.githubusercontent.com/806/145876579-aad0b284-4b2e-4c2e-8dc8-9c34d9139f30.png">

**Comment by znarf** [comment]
About the GitBook API itself:

> The GitBook API is currently in beta. This means you should not rely on it's availability, and that it may change without prior warning. If you wish to be one of our testers, please contact our team

**Comment by alanna** [comment]
I would really rather we move off gitbook before investing in further integration with the docs platform.
