### ISSUE TITLE
Improve UX for flexible intervals + tiers with free option

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5028]
While we fixed the blocking part of https://github.com/opencollective/opencollective-api/pull/6948, the UX with free tiers can still be confusing in the Frontend.

# Disable interval for free contributions

It makes no sense to allow picking an interval for free contributions. We should make sure that:
- Disable the interval picker when the selected amount is 0
- API doesn't accept interval if the amount=0

![image](https://user-images.githubusercontent.com/1556356/145582578-57f3dddd-f709-451f-a1ba-9a7fe5e5ce33.png)

# Unexpected tip
  1. Go to https://staging.opencollective.com/captainfact_io/contribute/donateur-4681/checkout
  2. Pick "Other" amount, set 0
  3. Tip gets hidden, and the header doesn't show it, but tip still defaults to $4.50

![image](https://user-images.githubusercontent.com/1556356/145582493-9c4de1f2-bc7b-4bd2-8d56-de7e29537b02.png)

Expected:
- If a tip is set we should keep showing the tip picker (even if the contribution itself is Free)
- Unless a custom tip is set, the tip should default to `0` when the amount is 0.

**Comment by Abekonge** [comment]
@Betree These things seems to be fixed. Should the issue be closed maybe?

**Comment by Betree** [comment]
@Abekonge https://github.com/opencollective/opencollective-frontend/pull/7271 indeed fixed the tip part, and https://github.com/opencollective/opencollective-frontend/pull/9203 made the interval disabled for free tiers. However, while re-testing the flow, I found it confusing that we would disable the interval input while keeping it stuck with a "Monthly" value. I'm pushing https://github.com/opencollective/opencollective-frontend/pull/9618 to force "One Time" to be selected when making a free contribution - which will resolve this issue.

Thanks for the heads up!
