### ISSUE TITLE
Create interface for people to convert to organization

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#503]
We need to create an easy way for past users to convert to organization so they can show up as Sponsors again.

**Comment by piamancini** [comment]
yes we need a way for users to create an organization without forcing them to make a donation

**Comment by cuiki** [comment]
Ah, this is the one that confused me. It's not really converting but just creating a new organization as an explicit action from the user as a standard flow and location.

**Comment by piamancini** [comment]
this is no longer relevant. all users have been converted and new organization flow exists: https://opencollective.com/organizations/new
