### ISSUE TITLE
Project not showing in hosted Collective tab

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5032]
This exists: https://opencollective.com/atx-mental-health-fund/projects/ls-request2

Note, this is `ls-request2` there is also `ls-request` which is another Project in the same Collective.

`ls-request2` doesn't show up here, only `ls-request`. There should be two different Projects called `LS Request` here.

![Screen Shot 2021-12-13 at 5 02 18 PM](https://user-images.githubusercontent.com/5498878/145750647-227745e6-58bc-4c68-a661-d80579d7d400.png)

I need to turn on grant expenses for this Project `ls-request2` - how do I do it?

**Comment by znarf** [comment]
Duplicate https://github.com/opencollective/opencollective/issues/4971
