### ISSUE TITLE
Extend "Pay 100% of expense amount" to PayPal

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5033]
It seems that PayPal supports a `feesPayer` option on some endpoints, which could facilitate the implementation of this.

**Comment by Betree** [comment]
PayPal adaptive (the legacy API) used to support this `feesPayer` param: https://web.archive.org/web/20170428021018/https://developer.paypal.com/docs/classic/api/adaptive-payments/Pay_API_Operation/

However, our newest integration with Payouts (that will soon [become the default](https://github.com/opencollective/opencollective/issues/4210)) does not seem to support such param. We're stuck with having this option enabled only for manual payouts and Transferwise.

See the relevant issue on [PayPal community](https://www.paypal-community.com/t5/REST-APIs/PayPal-payout-fee/td-p/1722298). As usual with PayPal, it's unlikely that this post will receive any update. I'm going to try and contact the support directly, but I don't have much hope

**Comment by Betree** [comment]
Reply from PayPal, sounds like this won't happen anytime soon

![image](https://user-images.githubusercontent.com/1556356/167406299-7a2ba280-70e3-4308-b0f7-61f0366ad8b4.png)

**Comment by BenJam** [comment]
> Paypal might surprise us

At least they're predictable 🥳

**Comment by BenJam** [comment]
little value in keeping this open imo.
