### ISSUE TITLE
[PROJECT] Expenses governance 

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5035]
## Overview 
> Adding a little governance to expenses handling

This issue deprecates https://github.com/opencollective/opencollective/issues/3328 which just got a lil confusing... 

## User story 
As a fiscal host admin, I want to implement financial risk management best practices, so I can meet my governance requirements and avoid misuse of funds.

## Best solution for this problem
In the Open Collective context, there are three roles involved in paying out an expense: submit, approve, pay. I suggest optional fiscal host setting that will not allow a single person to participate in all three roles for a single expense. 

For some small fiscal hosts (like independent Collectives) would not turn this on because there might only be one person involved who needs to do everything, but for larger or stricter organizations, it would be beneficial.

The main governance features would be

- [ ] #5036
- [ ] #5037
- OR Only allowing a single person to play two out of the three (submit, approve, pay) roles
- [ ] [Requiring a minimum number of approvals before passing an expense to payment](https://github.com/opencollective/opencollective/issues/3081)

## MVP
What we're doing for OSC and OCF is just verbally telling all the admins and staff not to approve their own expenses and instead approving each other's. We can codify this.

**Comment by BenJam** [comment]
@kewitz how do you feel about enforcing the weird '2 outta 3' constraint in the submit/approve/pay journey?

@alanna as an alternative how do you feel about the alternative of not allowing a submitter to approve or pay their own expenses? the main impact would be people who pay expenses (Ember, Alina) would need to approve and pay each others'.

**Comment by kewitz** [comment]
@BenJam I think it is an abstract rule that would look a bit weird on code.
I would rather set in stone that you _cannot approve what you submit_ and you _cannot pay what you approve_ if that solves the issue.

**Comment by znarf** [comment]
Well, 2 outta 3 is different, it's technically "you can not pay if you approved and submitted the expense", so it only applies to Host Admins or Independent Collective Admins.

**Comment by alanna** [comment]
I'm having a bit of trouble following all the details, but "you cannot approve what you submit and you cannot pay what you approve" sounds good to me. The underlying purpose of what's called "two to sign" in banking/governance is essentially that you want to prevent a single person acting alone from being able to take money out without other people knowing or approving (to prevent fraud, errors, etc). So if it's easier to think of it like "you cannot approve what you submit and you cannot pay what you approve" then it will achieve that goal.

The use case that is not covered by the above is another thing which is adjacent but not totally the same, which is more creating governance tools that can be used in more flexible ways. If we implemented it as a generic setting of "X approvals needed" people could use it for situations like there are 5 admins and they all have to unanimously approve expenses, so they'd put "5", or a situation where their rule is a majority must approve so they'd put a different number. Governance tools were identified as a priority/interest in the async away day, so perhaps we want to create space for that. But it might be better to achieve this stuff via metagov instead, and I don't want this feature scope blowing out.

**Comment by BenJam** [comment]
> Well, 2 outta 3 is different

correct. 

> "you cannot approve what you submit and you cannot pay what you approve" sounds good to me

this would mean that an admin could not approve and pay an expense in one pass, which might slow things down for hosts. The proposal addresses this by implementing the simpler 'cannot approve or pay your own expense' which I think gets to the core of the issue here (having someone rip through the system without a single check). It ensures that even host admins have to involve another person in the process. 

> If we implemented it as a generic setting of "X approvals needed" ...

that's covered in #3081

**Comment by Betree** [comment]
Pasting some comments from this [Slack thread](https://opencollective.slack.com/archives/C01UJ6SDSHK/p1639135846169600) here as I think they're important for this discussion.

@alanna 
> I’m also really excited about governance tools! Either building them directly or integrating through things like metagov.
>
> I understand your point about security, but in my experience that’s not really as big a problem as you might think. We need to be super careful with fraud prevention since we are a money platform, but I don’t think the two-approvals feature introduces any security holes that are not already present with the single-approver model. I think you’re referring to how such a feature can give people a false sense of security that we should not encourage, if they assume there’s no way for someone to fake a second profile and make some key determination based on that. Thats true, but I think it’s really an edge case.
> 
> The far more common case, and I think the far more interesting case, is where everyone is acting in good faith, because if we assume that then we can confront the truly hard problems based on human interaction and group dynamics when it comes to governance. This is why I think DAOs and blockchain based governance systems are boring - they focus everything on security, identity, smart contracts, anti-fraud, zero-trust. These are not the hard problems, they are just the ones most easily addressed by technology and the easiest ones to see concretely.
> 
> These systems never solve the actually hard problems, which are based in the complexity of human relationships. Think about decision-making in our own team or in your family. Even when everyone knows and trusts each other, and everyone is trying their best to be honest and constructive, there are still a lot of problems to solve! That’s the domain I am interested in, and the domain that’s not solved by existing tools. Technology cannot replace the human dynamics, but we can use technology to enhance groups’ practice and outcomes and make good results more likely.
> 
> Instead of zero-trust systems, what creative tools can we build for high-trust groups to go even further?

Caroline

> I love this! Yes @Alanna too “Technology cannot replace the human dynamics, but we can use technology to enhance groups’ practice and outcomes and make good results more likely.”

@Betree 

> I can understand this approach, and for sure shipping these features will be a lot easier if we don't need to care about security.
> 
> But securing the processes is also about securing the groups. An open-source project with people that never met in real-life might not have the level of trust required to allow these kind of flaws. Not everyone can guarantee that the latest maintainer they onboarded (who's from a different country and not legally suable) will not try to run with the money.
>
> Implementing something secure is more complex, but it's not impossible. We're not dealing with the decentralized aspects of DAOs & blockchains that are the really complex parts. We're centralized, for us the only challenge is to find a good UX that won't feel like a constraint for our users.
> 
> In the meantime, I'll insist to always make it clear for people using these features that we do not guarantee any kind of security. Because the false sense of security you mention can in fact have terrible consequences in a world where people (for very different reasons - personal conflicts, individual bankruptcy, instability) can end up taking decisions that go against the group.
>

**Comment by znarf** [comment]
Closing this as a meta-issue as kind of duplicate with https://github.com/opencollective/opencollective/issues/5143
