### ISSUE TITLE
[PROJECT] Setting to prevent submitters approving their own expenses

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5036]
> Submitters should not be able to approve their own expenses

As part of #5035 we would like to codify a practice that we use in our own host organisations. That users should not approve their own expenses. 

To achieve this we'll need

- [ ] to add a setting to the host expenses policy 'users should not approve their own expenses' 
- [ ] add a notice to collectives' expenses policy when host enables the above setting
- [ ] to enforce the above policy (design TBC)

**Comment by znarf** [comment]
I think this is potentially disruptive as a Host setting for OSC and OCF. Collective admins are used to current practices and some may push back.

Have you considered the pros and cons having this as a Collective setting instead of a Host setting?

**Comment by kewitz** [comment]
**Context:**
1. It's up to a collective admin to approve or not an expense.
2. After the collective admin approves an expense, the rest of the payment process is dealt with by the host admin.
3. Some collectives are managed by a single admin, and they need to submit and approve their own expenses.
    - **Problem**: Collectives that have a single admin won't be able to pay for expenses if the rule is enabled.
4. Other collectives have more than a single admin, and it would be interesting to enforce that more than one admin is aware of the expenses being paid.
    - **Problem**: An admin can temporarily disable this rule to approve their own expense.
    - **Problem**: An admin can add another fake admin to the collective to approve their "own" expense.


**Specifications:**
- Host Admins will be responsible for enabling/disabling this feature for each collective. (Solves Problem 4.1)
    - This will be set on the CollectiveSettingsModal component that can be accessed through: host admin panel -> hosted collectives.
    - _Should we allow collective admins to enable this feature and block only disabling it?_
- When enabled, collective admins will not be able to approve their own expenses.
    - _Should we enforce this rule only on collectives that have more than > 1 admin?_ (Solves Problem 3.1)
    - _Should we enable this by default when the collective onboard a second admin?_
    - _Should we migrate every existing collective that has > 1 admin?_
- This rule is enforced in the backend. In the frontend, we'll disable the approve button and add a tooltip to it explaining why the user can not approve the expense.
- An admin can only approve one expense if they already have approved any expense in the past. (Solves Problem 4.2)
    - Should we allow host admins to enable this flag only on collectives that have two eligible admins available?

cc @Betree @znarf

**Comment by znarf** [comment]
> Host Admins will be responsible for enabling/disabling this feature for each collective.

That works for the MVP but doesn't scale for 1500 Collectives. I see:

1. First step. Feature available for Host admins to set on a Collective basis (default off, opt-in)
2. Second step. Feature available for Host admins to set on a global basis (default on, opt-out)

> Should we enforce this rule only on collectives that have more than > 1 admin.

Yes. Keep current behavior and ignore the feature if only 1 admin.

Maybe there should be a another policy to prevent admins to remove other admins and become the only one.

> An admin can only approve one expense if they already have approved any expense in the past. 

As I see, that doesn't solve the problem, just make it more complicated to circumvent. I would not do this.

**Comment by kewitz** [comment]
Updated https://github.com/opencollective/opencollective/issues/5036#issuecomment-1020477602.

**Comment by znarf** [comment]
@kewitz The release plan is unclear to me at this point. When I read the spec, the points are contradicting each others:

- "Fiscal Hosts will be able to enable and disable this feature on a collective"
- "We'll automatically enable this on collectives of selected hosts"
- "Enable settings in the Host policy menu to automatically turn this setting on"
- "We'll automatically enable this rule on 1st-class hosts."

Maybe you have some different release steps in mind? Can you break "MVP" into clearer milestones?

**Comment by kewitz** [comment]
@znarf they're all describing the initial condition of the MVP when launched:

> Fiscal Hosts will be able to enable and disable this feature on a collective basis through the Hosted Collectives page in their Host Admin Panel.

Refers to the granular access Host will have in order to enable and disable this feature on a collective basis.

> We'll automatically enable this on collectives of selected hosts that have more than one administrator.

We'll automatically enable this feature on every collective hosted by 1st-class fiscal hosts that has more than one admin.

> We'll automatically enable this rule on 1st-class hosts. Hosts can ask for disabling it through a support ticket.

We're also preventing Host admins from approving their own expenses on 1st-class fiscal hosts.

> Enable settings in the Host policy menu to automatically turn this setting on when a collective adds a second administrator.

Refers to how Fiscal Hosts can set the default state of this feature for incoming collectives. I think this one could be moved to the next phase but I also expect this to be simple enough that we could ship it in the MVP.

**Comment by piamancini** [comment]
- [ ] Test MVP with design 
- [ ] Document 
- [ ] Deliver MVP to staging or prod under a flag

**Comment by Betree** [comment]
The specs & the plan from https://github.com/opencollective/opencollective/issues/5036#issuecomment-1020477602 are looking good to me, the MVP sounds realistic. Not much feedback from my side at this point!

**Comment by znarf** [comment]
Goals for Q1 Sprint 1 Week 3:
- [ ] Review and merge PRs from @kewitz 
- [ ] Deployment
- [ ] Get in touch with Collectives (Fiscal Hosts to be in touch with interested Collectives @BenJam for OSC @alanna for OCF)

In our weekly meeting today, we discussed the late change of specification last week, that was not ideal.

Some mentioned concerns making this feature not a "security" one.

It's still an interesting MVP in this state and we can iterate, especially when Leo is back for week 5.

**Comment by znarf** [comment]
Goals for Q1 Sprint 1 Week 4:

- [ ] Get in touch with Collectives
  - [x] Design to be in touch with interested Collectives (@Memo-Es for Accountable)
  - [ ] Fiscal Hosts to be in touch with interested Collectives:
    - [ ] @BenJam for OSC
    - [ ]  @alanna for OCF
    - [ ]  JF for Europe

**Comment by znarf** [comment]
Update posted by @BenJam https://opencollective.com/opencollective/updates/two-to-sign-features-on-open-collective Mixed feedback.

Goals for Q1 Sprint 1 Week 5:
- [ ] Documentation @kewitz

Goals for Q1 Sprint 1 Week 6:
- [ ] @Memo-Es to discuss with Accountable this week

**Comment by znarf** [comment]
This project is considered closed. Feedback issue here: https://github.com/opencollective/opencollective/issues/5279
