### ISSUE TITLE
Refactor: Boolean Expense permissions and duplicated permission logic

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#5038]
I'm starting to spec out the Expense governance issue and one of the current problems I'm facing is how to abstract the permission logic in a way we can avoid duplicating the logic.
Simply put, if expense permissions are booleans and we want to display the reason why permission is `false` in the frontend, how can we convey that without evaluating the permission in the frontend again.

Example:
Users cannot approve their own expenses: API evaluates the rule and returns `expense.permissions.canEdit = false`, how to display "User cannot approve their own expenses" error message in the frontend without needing to reevaluate rules in the browser?

cc @Betree

**Comment by Betree** [comment]
Good topic. Maybe we can have richer types for permissions? Something like:

```ts
permissions: {
  pay: {
    allowed: boolean,
    details: null | 'CANNOT_PAY_OWN_EXPENSES' | 'NOT_ENOUGH_BALANCE',
  }
}
```

**Comment by kewitz** [comment]
**Specifications:**

- Create a new GQL type for structured permissions as recommended by @Betree. `{ allowed: boolean, details: constants }`.
- Update ExpensePermission to include structured permissions based on the existing boolean permissions.
    - `canEdit` becomes `edit` with structured permission type. Do not deprecate `canEdit` just now, so we ensure backward compatibility.
    - Update permission functions to throw encoded errors and write resolvers of the new type to catch these errors and translate to `{ allowed: null, details: errorCode }`
    - Update the existing permission function calls to catch errors and consider them `false`.

CC @Betree, I see this as a blocker for #5036 and #5037 could you review these specs?

**Comment by Betree** [comment]
@kewitz Great, it's clever to keep the `canEdit` / `can*` helpers and remove the `can` prefix from new fields to preserve backward compatibility. Tackling this before #5036 and #5037 will indeed save us from some complex logic and debt in the frontend, I'm supportive of the idea.
