### ISSUE TITLE
Investigate and Add Support for Refunds of Expenses for Same Collective

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5039]
Initially proposed at, https://github.com/opencollective/opencollective-api/pull/6946#pullrequestreview-827362491. We need to investigate the current behavior for refunds of expenses from same collective (expense where `from/to` are same) and add the support for these refunds it that's not currently supported. 🤔

**Comment by znarf** [comment]
@SudharakaP is it duplicate with https://github.com/opencollective/opencollective/issues/4286 ?

**Comment by SudharakaP** [comment]
> @SudharakaP is it duplicate with #4286 ?

Thanks for pointing it out. Yes this is a duplicate. I'm closing this issue and the PR will be linked to the other issue. 👍🏽
