### ISSUE TITLE
Bug on label when adding members

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#504]
Mail from Wil:

> (...)
> Found a bug in the members section.
> 
> Adding one of the core contributors chops off his name.
> 
> His name is "James Carmody" and when adding him in as a contributor, after saving it truncates his name to "James Car"
> 
> Collective: https://opencollective.com/wordpress-sydney/edit#members (...)

**Comment by piamancini** [comment]
can't reproduce from that link @nicobarretoOC

**Comment by nicobarretoOC** [comment]
I believe this is already solved, it was similar to when the tiers where hard to edit... Let me know we might be able to close it now.
