### ISSUE TITLE
Inconsistencies Editing Collectives

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5046]
While working on the https://github.com/opencollective/opencollective-frontend/pull/7229 I realized we have some inconsistencies on our collective settings. Particularly how we handle validations seems inconsistent. Here are some things I've noticed; 

1) Creating an event until the user hits save they are not told that the event name is mandatory. We either need to add validation on this field (preventing the unnecessary call to API and showing the error on the spot below the field) and/or add some indication in the field label that the field is mandatory.

![image](https://user-images.githubusercontent.com/12435965/146255475-6ed8503b-68cd-45b9-9c32-c50ffa93c3ea.png)

2) Adding a new tier seems a bit painful again as the user isn't aware what fields are required. Firstly if the user just tries to create a tier with just the amount; it passes through but the tier isn't actually created. Also if the user only enters the name of the tier then there's an error indicating the amount is needed. So basically the user has the figure out that both fields are required. My suggestion is that we just show some simple validation on the form itself such that if the user do not enter the name or amount an error is shown below the field without the need for the API call in this case. 

![tier-creation](https://user-images.githubusercontent.com/12435965/146257163-2755853e-c6cd-4f06-ac6e-5455121ac41a.gif)

**Comment by Betree** [comment]
> Creating an event until the user hits save they are not told that the event name is mandatory. We either need to add validation on this field (preventing the unnecessary call to API and showing the error on the spot below the field) and/or add some indication in the field label that the field is mandatory.

The default pattern for new developments is:
- Show `(optional)` on optional fields
- Everything else is considered mandatory
- Never disable the submit button
- Validate when clicking on "submit" and show the errors inline, below the concerned field(s)

Overall, it's cool if we can add some frontend validations easily but I would love to see a full rewrite of this form. There's a lof of hacky code in there (things like this https://github.com/opencollective/opencollective-frontend/blob/fix/no-payment-blocker/components/edit-collective/index.js#L87), technical debt (#4830) and it's not using the latest design system & best practices (Formik, validations, etc.).

> Adding a new tier seems a bit painful again as the user isn't aware what fields are required. Firstly if the user just tries to create a tier with just the amount; it passes through but the tier isn't actually created. Also if the user only enters the name of the tier then there's an error indicating the amount is needed. So basically the user has the figure out that both fields are required. My suggestion is that we just show some simple validation on the form itself such that if the user do not enter the name or amount an error is shown below the field without the need for the API call in this case.

I would not invest in this one, we have a great re-design for this page in https://github.com/opencollective/opencollective/issues/3438. I will argue to include it in the upcoming sprints.

**Comment by znarf** [comment]
I would break the 2 problems mentioned there in separate issues, I see the link but they're 2 separate things.

**Comment by SudharakaP** [comment]
> I would not invest in this one, we have a great re-design for this page in #3438. I will argue to include it in the upcoming sprints.

Thanks for the input. I am closing this since the re-design I think should solve these issues. 👍🏽
