### ISSUE TITLE
USD transactions in NZD host

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5047]
On https://opencollective.com/ocnz/admin/orders

![Screen Shot 2021-12-16 at 3 54 02 PM](https://user-images.githubusercontent.com/5498878/146299602-a2698c0c-b72a-4596-9bf2-7e97943c6002.png)

Why is this one transaction in USD?

**Comment by znarf** [comment]
The Collective is currently configured in USD. I'm not sure why.

The transactions are issued in USD but converted to NZD (the host currency). This is a supported case, so no accounting issue.

We can follow up on support if needed.

**Comment by znarf** [comment]
Potential query to check similar cases:

```
SELECT  "Hosts"."currency", "Collectives"."currency", "Collectives".* FROM "Collectives"
LEFT JOIN "Collectives" as "Hosts" ON "Hosts"."id" =  "Collectives"."HostCollectiveId"
WHERE "Hosts"."currency" != "Collectives"."currency"
AND "Collectives"."deletedAt" IS NULL
AND EXISTS (
  SELECT * FROM "Transactions" WHERE "CollectiveId" = "Collectives"."id" AND "Transactions"."deletedAt" IS NULL
)
```

**Comment by alanna** [comment]
Is the currency in USD something the user would have chosen? I was not even aware of it as the host.

**Comment by alanna** [comment]
@znarf is this done?

**Comment by alanna** [comment]
@znarf is this resolved?

**Comment by znarf** [comment]
@alanna according to [my answer from December](https://github.com/opencollective/opencollective/issues/5047#issuecomment-995551109), this was not a bug and there was nothing to do or to resolve.
