### ISSUE TITLE
[DOCS] Remove Github Wiki pages

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5053]
## Context
A long time ago, https://github.com/opencollective/opencollective/wiki/ was used to document some aspects of the platform. This Wiki has long been replaced by https://docs.opencollective.com/help/ and a message there indicates the new documentation URL but we still end up with pages presenting outdated or incomplete information like https://github.com/opencollective/opencollective/wiki/Editing-expenses.

### Changes to be made
- Make sure the information in the wiki can be found in the current documentation
- Remove all pages from this Wiki and only keep the deprecation message
- Make sure the Wiki pages are not linked from anywhere (search google, our own codebase) & update if necessary

**Comment by alceil** [comment]
Can I take up this issue ?@Betree

**Comment by shannondwray** [comment]
ohh I wasn't I can sort this :) Thanks Ben

**Comment by shannondwray** [comment]
Has the wiki been deleted?

**Comment by Betree** [comment]
@shannondwray I took it offline a few months ago after noticing some random edits we had not reviewed. Here's the content, in case you want to take a look: [opencollective.wiki.zip](https://github.com/opencollective/opencollective/files/13381268/opencollective.wiki.zip).

The original git repo for the wiki still exists and can be cloned with:
> git clone git@github.com:opencollective/opencollective.wiki.git
