### ISSUE TITLE
Fix: Amount on receipt for WWCode Atlanta

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#506]
Mail from Brittani:

> Can you change the amount for this receipt in Atlanta's Open Collective https://opencollective.com/wwcodeatl/expenses from $100 to $104.19? 

<img width="934" alt="screen shot 2017-10-16 at 12 43 22 am" src="https://user-images.githubusercontent.com/30665166/31596746-15af9456-b20a-11e7-851c-5ad316f0ae6a.png">

**Comment by piamancini** [comment]
@nicobarretoOC since this expense hasn't been approved, they can reject it and do it again with the correct amount.
