### ISSUE TITLE
Unable to Edit Expense with United Arab Emirates bank account address

### ISSUE THREAD

**Issue by chewitt** [opencollective/opencollective#5061]
**Describe the bug**
I'm forced to provide postcode details for a United Arab Emirates bank account which was correctly created without postcode details, when editing an expense.

**To Reproduce**
I successfully created and submitted my first expense: https://opencollective.com/libreelec/expenses/59077 but then realised the USD value is incorrect as the invoice I am claiming reimbursement for was part-paid using some remaining Paypal credit, so I need to claim a lower USD value. When I edit the expense, I am first asked to reconfirm the payee details for my United Arab Emirates bank account. It is specifically asking for a postcode. However there is no "deliver to home" postal service in the UAE (only PO Boxes for central delivery) so most people have a postbox, but nobody has a postcode. The normal thing to do in this scenario is to use the postbox number to complete the form, e.g. DXB12345, as the UAE banks validate/accept anything in billing details for that field, however I'm not able to edit the account details either, so I can't get to the 'Next' screen to edit the expense. When seeing if I made a mistake when adding bank details I've spotted the logic problem - see screenshots.

**Expected behavior**
Postcode should be an optional detail for any UAE bank account, as nobody has one, and I should be able to edit the expense.

**Screenshots**
Here the bank account address is set to United Kingdom (which has postcodes) and the postcode field is correctly visible:
<img width="818" alt="Screenshot 2021-12-22 at 7 24 35 am" src="https://user-images.githubusercontent.com/251794/147052390-cd1e8667-7065-471f-a40f-bbe4c85ed610.png">

Next I edit the country to United Arab Emirates (which does not have postscodes) and the form correctly adjusts to hide the postcode entry field:
<img width="807" alt="Screenshot 2021-12-22 at 7 26 45 am" src="https://user-images.githubusercontent.com/251794/147052592-223eaa95-0d31-46b2-9676-14ceb2d7e1d1.png">

But when I edit the expense, the logic is wrong and the missing postcode is flagged. I wasn't able to capture the "not editable" cursor icon in the screenshot, but this is what I see:
<img width="838" alt="Screenshot 2021-12-22 at 7 17 31 am" src="https://user-images.githubusercontent.com/251794/147051599-fb22bda9-5c42-404c-a936-cca2e1d6c803.png">

**Desktop (please complete the following information):**
macOS 10.15.7 with Firefox 95.0.1 64-bit

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
Ping @kewitz

**Comment by Betree** [comment]
@kewitz This one looks a bit similar: https://opencollective.slack.com/archives/GDTJY7S48/p1640291980004500

**Comment by chewitt** [comment]
Just to comment, the changed pushed resolved the issue for me. Thanks for the quick response 👍🏻
