### ISSUE TITLE
[Feedback] Expenses Across Hosts

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5064]
This is an issue to collect feedback and potential follow ups for the Expense Across Hosts project. https://github.com/opencollective/opencollective/issues/4966

- [x] Improve Bank Account selection from the payee (not clear which bank account to use) https://github.com/opencollective/opencollective/issues/5179
- [ ] Create documentation
- [ ] https://github.com/opencollective/opencollective/issues/5068
- [x] https://github.com/opencollective/opencollective/issues/5260

**Comment by alanna** [comment]
@znarf how are we handling host fees for this? If Collective A, hosted by Fiscal Host X, submits an expense to Collective B, and Host X has a host fee of 10%, will that be applied when the funds are credited to Collective A? If not, this is an end-run around host fees.

**Comment by znarf** [comment]
@alanna I'm trying to find some previous conversations on the topic, maybe it was discussed for Contributions? Anyway, as a general rule, we have no mechanism for Host Fees on Expenses whatsoever. So, nothing special for Expenses Across Hosts at this stage, the general rule applies.

**Comment by alanna** [comment]
Raised #5260

**Comment by piamancini** [comment]
@znarf to discuss payment method selection issue (it's shown to the user) - has this been fixed?

**Comment by znarf** [comment]
@piamancini are you talking about this issue? https://github.com/opencollective/opencollective/issues/5179

**Comment by piamancini** [comment]
Week 2
- [ ] Improve Bank Account selection from the payee (not clear which bank account to use.

**Comment by alanna** [comment]
Suggest adding #5341 to the current project on this, as it will cause accounting issues and (I hope) is an easy fix.

**Comment by piamancini** [comment]
- [ ] handle of tax form (updating queries)

**Comment by piamancini** [comment]
- [ ] close issue
