### ISSUE TITLE
bug: collectives not showing in supercollective

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#507]
Reads 4 collectives, only shows 2: opencollective.com/europe
![screen shot 2017-10-16 at 11 59 02 am](https://user-images.githubusercontent.com/3671070/31622218-d0148b80-b269-11e7-8530-8338787b3561.png)
Collective opencollective.com/kea is hosted by it, tagged but it's not showing up

**Comment by piamancini** [comment]
added a parent collectiveID it increased the amount to 5 but still not showing up

**Comment by piamancini** [comment]
also see: opencollective.com/uk
![screen shot 2017-10-16 at 1 02 55 pm](https://user-images.githubusercontent.com/3671070/31624961-641051ae-b272-11e7-89c7-742496f7e2bb.png)

**Comment by piamancini** [comment]
Might be related to this, when user created a new collective with the link opencollective.com/gorge-genie/apply the collective was created with no tiers and it had no host.

**Comment by xdamman** [comment]
That's because since we order them by balance, we only show the ones that have at least one transaction. We should fix that but at least now you know why it happens.
