### ISSUE TITLE
Typos/Edits on www.opencollective.foundation

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#5072]
1) 
![image](https://user-images.githubusercontent.com/64920686/147612057-4db78b67-9741-4fa4-be7a-d627055fdc43.png)

'Reach out to us' should have an action. Maybe hyperlink it to mailto: contact@opencollective.foundation would be fine?

2) should say 'and'
![image](https://user-images.githubusercontent.com/64920686/147612184-9e88e79d-22a4-41c3-a538-7356625e6c66.png)

3) 'or if you would like us **to** contact you'
![image](https://user-images.githubusercontent.com/64920686/147612229-8cc58355-0d8a-4845-a5af-d4f22c0fada0.png)

**Comment by znarf** [comment]
@SudharakaP maybe you can have a look?
