### ISSUE TITLE
Remove search bar on discover page

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5074]
On the [discover](https://opencollective.com/discover) page, the search bar can only be used to search by tag. If you type `Webpack` in there, you won't see webpack. This is confusing for users, and not very helpful since the most important tags are supposed to be surfaced with quick filters at the top of the page.

![image](https://user-images.githubusercontent.com/1556356/147642442-ab46f8f6-ee48-403b-910a-36b64c658075.png)

**Proposal**
While we wait for https://github.com/opencollective/opencollective/issues/2970, I propose to remove this search bar. This should:
- Force users to use the top bar search (which full-text search) when needed
- Reduce the confusion between search and discover

**Context**

Based on this [user feedback](https://opencollective.freshdesk.com/a/tickets/52486):

> I believed that the Pytest project was on Open Collective, so I came to your site, went to the Discover page and entered that name. It said nothing was found.
> 
> Eventually on their github site I followed a link and found that they are on Open Collective, and have been for a while. But still the search finds nothing.
> 
> This is very confusing.

**Comment by BenJam** [comment]
will be killed by https://github.com/opencollective/opencollective/issues/4295

**Comment by SudharakaP** [comment]
This issue is no longer relevant as the new `/search` page now handles searching by slug etc. Thus I am closing this issue.
