### ISSUE TITLE
Events and projects not displayed in the user menu for admins

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5077]
**Describe the bug**
In the logged-in user menu, events are currently displayed if you're a financial contributor (which is wrong) but not for admins. This is because the user menu relies on `loggedInUser.memberOf`, which only contains direct memberships - not the parent's memberships.

**To Reproduce**
1. Create an event or project
2. It does not appear in the user menu
3. Make a financial contribution to it, it appears

**Expected behavior**
- The entry should appear for admins in the menu directly after the project/event creation.
- The entry should not appear for attendees and financial contributors.

**Context**
This is closely related to https://github.com/opencollective/opencollective/issues/5066, as both of these places use the same source for the memberships. We should ideally solve both at once with an approach to fetch children.

**Comment by znarf** [comment]
Events and Projects should not appear in the logged-in user menu, at least not with the current design.

Agree that it should not appear for attendees and financial contributors, that's the expected behavior for all accounts.

**Comment by SudharakaP** [comment]
@Betree : If no objections I'll work on this issue this week. 🙂

**Comment by Betree** [comment]
@znarf Adding events to the user menu was a conscious decision from https://github.com/opencollective/opencollective/issues/3416. Why would we want to remove them now?

**Comment by Betree** [comment]
@SudharakaP Let's wait a bit to make sure we have an agreement on how to solve this one. Also, I'd want us to solve https://github.com/opencollective/opencollective/issues/5066 at the same time.

**Comment by znarf** [comment]
@Betree I'm personally not seeing any Events in the menu so I clearly forgot about #3416. Is it really working right now? I think that it's not, given that we are not creating ADMIN entries anymore for Events in the Members table.

**Comment by Betree** [comment]
It's not working right now for events created after the "events admin" change, only the ones created before that appear in the user menu. This issue is an intent to fix it by fetching account's childrens memberships but we'll need to be clever about the query: ideally we should not fetch Babel's children if you're just a BACKER.

**Comment by Betree** [comment]
The new user menu is also impacted by this.

**Comment by Betree** [comment]
Since https://github.com/opencollective/opencollective-frontend/pull/7513/files#diff-65f6cb92316b0fff389f7f2d8b98ab60a978b546ee0fcb5ba2048c4d7bf6aec9 we're fetching the children in the `loggedInUser` query, so the fix should be fairly simple.

**Comment by Betree** [comment]
With the new dashboard's Account Switcher, I don't think we should surface projects and events in the user menu. Thus this issue should aim at removing all events and projects from there (see https://github.com/opencollective/opencollective/issues/5077#issuecomment-1003936658).
