### ISSUE TITLE
Pre-fill end date and time when adding a start date and time on events

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5085]
As above. This is an incredibly annoying little thing when creating events. 

My expectation is that when I add a start date and time that the end date and time will be set to that point (maybe +1 hour) so that I can just adjust the time (which I assume is the expected behaviour in 99% of cases).

**Comment by SudharakaP** [comment]
@BenJam : I am a bit confused on this one. Isn't the end-date filled up by default to `startDate + 3 hours` when we create an event? 🤔 

![image](https://user-images.githubusercontent.com/12435965/148163333-858045a6-c81e-4163-b958-c748ac18a874.png)
