### ISSUE TITLE
[PROJECT] Support & other miscelaneous papercuts

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5087]
This project is about documenting small improvements that we can tackle to reduce support.

Prioritized:
- [x] https://github.com/opencollective/opencollective/issues/5078 @SudharakaP 
- [x] https://github.com/opencollective/opencollective/issues/4550 @betree
- [x] https://github.com/opencollective/opencollective/issues/5000 (for root users) @betree
- [x] https://github.com/opencollective/opencollective/issues/3966 @SudharakaP 

Issue backlog:
- [x] https://github.com/opencollective/opencollective/issues/3330
- [x] https://github.com/opencollective/opencollective/issues/4009 @Betree 
- [ ] better notices about pending bank transfers (view/cancel)
- [ ] better instructions/notices on writing bank payment instructions in correct kanji (maybe linking to wise  guidance directly/through our own docs)
- [ ] introduce a 'suggestions' process for docs
- [x] https://github.com/opencollective/opencollective/issues/3193

**Comment by BenJam** [comment]
am I allowed to add #3330...

**Comment by Betree** [comment]
Looks like there's a common need for a `TierPicker` component between https://github.com/opencollective/opencollective/issues/5000 and https://github.com/opencollective/opencollective/issues/4009. Let's see if we can either extract that from somewhere (edit recurring contributions?) or at least make sure we don't double-implement in in parallel

**Comment by kaylarep** [comment]
Dead link on OCF's homepage
https://github.com/opencollective/opencollective/issues/5211
