### ISSUE TITLE
[DOCS] Fiscal Hosting Info pages should link to each other

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#5089]
These 3 pages should all link to each other (I don't believe they currently do):

- https://opencollective.com/fiscal-hosting
- https://opencollective.com/become-a-host
- https://opencollective.com/hosts (this one already links to 'become a host')

::

Please add on this page https://opencollective.com/become-a-host ?
It can just say "Learn more about fiscal hosting." and the hyperlink can be under `fiscal hosting` going to https://opencollective.com/fiscal-hosting
![image](https://user-images.githubusercontent.com/64920686/148137278-2bd146a2-5ff6-4159-9d0a-6adf4043d6d1.png)

::

I can offer suggestions for where the others should go as well if that's helpful.

EDIT: see this comment for additional edit to this page: https://github.com/opencollective/opencollective/issues/5089#issuecomment-1023655660

**Comment by kaylarep** [comment]
related issue with suggestions: https://github.com/opencollective/opencollective/issues/4701

**Comment by SudharakaP** [comment]
> I can offer suggestions for where the others should go as well if that's helpful.

@kaylarep : Any suggestions on where to place the other links as well? That way I can do the whole thing in one go. 😉

**Comment by kaylarep** [comment]
@SudharakaP on this page: https://opencollective.com/fiscal-hosting

- add here:
- 
![image](https://user-images.githubusercontent.com/64920686/151443201-7e65197c-1bbe-4020-8167-9543bb423be5.png)


(There's a missing period, please add that in.)

- Under 'create your own fiscal host', link to: https://opencollective.com/become-a-host
- Under 'Organizations around the world', link to: https://opencollective.com/hosts

**Comment by kaylarep** [comment]
@SudharakaP on this page: https://opencollective.com/hosts
![image](https://user-images.githubusercontent.com/64920686/151446240-89cac18d-95ca-4c6a-b00b-45e1220e77c9.png)
- Under 'Fiscal Host' (red underline), please link to: https://opencollective.com/fiscal-hosting

**Comment by kaylarep** [comment]
@SudharakaP 

On this page: 
https://opencollective.com/become-a-host

![image](https://user-images.githubusercontent.com/64920686/151446577-5b9593b7-f704-4b45-942b-a6f360b42aba.png)
Please write in there: "Learn more" and have it link to https://docs.opencollective.com/help/fiscal-hosts/become-a-fiscal-host

**Comment by kaylarep** [comment]
@SudharakaP these aren't perfect fixes, but will be good enough for now.

@Memo-Es may want to improve upon this at some point.

**Comment by SudharakaP** [comment]
@kaylarep : Thanks for the information. I've done the fixes, after review we'll merge it possibly beginning of next week. 👍🏽

**Comment by kaylarep** [comment]
@SudharakaP amazing!! thank you so much! :)

**Comment by SudharakaP** [comment]
> @SudharakaP amazing!! thank you so much! :)

You are welcome. 🤗
