### ISSUE TITLE
Add option link an Mastodon account to an collective profile

### ISSUE THREAD

**Issue by 6543** [opencollective/opencollective#5096]
## User story 
On the profile page of an collective you can set your twitter account but not an Fediverse one.
for example as part of "woodpecker-ci" we do have https://mastodon.technology/@WoodpeckerCI but will never have an twitter account.

## Best solution for this problem
Simplest option would be to add a new field for mastodon accounts.
A better option to add lets say up to 5 "custom fields" user can put links into it, specify a category and upload icons for it.

## MVP
_What should be possibly built to demonstrate the solution?_
well just look how at the twitter link option

## Metrics 
_What metrics will be used to measure impact?_
to validate the metrics, create an mastodon account and see how much momentum you can get!
the audience is different sure - but in a better way :+1: 

## Documentation 
_The goal of the documentation should be to make it easier for others to do this_

?

**Comment by 6543** [comment]
I'm not sure If I should open a new issue, but a "open collective - mastodon" account would be a nice idea too!
I think [cross-post from mastodon to twitter](https://masto.donte.com.br/@crossposter) is possible so not much more work should occur.

**Comment by Betree** [comment]
Thanks for documenting this issue @6543! I made a proposal in https://github.com/opencollective/opencollective/issues/4588#issuecomment-906974550 to have a general "Custom links" approach for people to put whatever they want in there. I'm going to consolidate everything in a new issue.

**Comment by Betree** [comment]
Closing in favor of a more generic approach: https://github.com/opencollective/opencollective/issues/5097
