### ISSUE TITLE
Ability to look through older expenses submitted on Host Dashboard 

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#5098]
When host admin is going through processing expenses ready for payment, the default view would have the newest claims first. While this is the right default option, there is no an easy way at the moment to order the view from older claims to newer:
![capture](https://user-images.githubusercontent.com/57156267/148457995-72b4a561-0c07-4c71-ad4f-8e0f411ff353.png)

This filter is useful to ensure the collective budget will cover the older claims first. Currently, there is a risk of collective budget running out before these claims are processed which creates frustration amongst those submitting the claims. 

A current workaround can be processing claims starting from the last page etc, but this is not an easy or intuitive solution.

![capture](https://user-images.githubusercontent.com/57156267/148458624-10ee896a-cf61-4fc4-bcc7-37d05547c58b.png)

**Comment by Betree** [comment]
Ping @opencollective/design
