### ISSUE TITLE
Better strategy for children accounts "hasGrant" setting

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5106]
Originated from [this Slack thread](https://opencollective.slack.com/archives/G46PNRCGP/p1641487650011900)

In https://github.com/opencollective/opencollective/issues/5065, we've disabled the modal that allows for customizing the host fees structure for projects and events (to make sure they always inherit from the parent), but this modal also contains the "has grants" checkbox that shouldn't be hidden.

We have two options:
1. Similarily to host fees structure, make sure children inherit this setting from their parent ~ Medium complexity
2. Restore the modal, with host fees structure disabled/hidden for events/projects ~ Simple complexity

**Comment by znarf** [comment]
@Betree With OCF use case in mind, I think we want 2).

**Comment by Betree** [comment]
@znarf Alright thanks for this feedback, I'll prioritize it this week then. It's the simplest fix and I'm afraid more people may be blocked by this soon.

**Comment by natehn** [comment]
I'm wondering if option 2 is the best option for OCF. I think that option 1 might be better - I'll chat with @alanna about it

**Comment by natehn** [comment]
Okay, touched base with Alanna. "2" is the best option for now.

**Comment by Betree** [comment]
Cool, I think option 2 is safe - we're basically reverting things back to where they were. It's also the simplest. We can can on doing option 1 in the future, but it should have its own specs and prioritization
