### ISSUE TITLE
Currencies displaying on both EUR and USD

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#511]
Mail from Marius:

> Hey, a few more bug reports :)
> 
> First, I see that while the bottom of the page says that the price is in €:
> 
> <img width="934" alt="screen shot 2017-10-16 at 22 01 39" src="https://user-images.githubusercontent.com/30665166/31633706-ddb3e9a8-b286-11e7-9925-0e03e3a539e2.png">
> 
> ... and editing the tiers shows the price in €:
> 
> <img width="218" alt="screen shot 2017-10-16 at 22 02 28" src="https://user-images.githubusercontent.com/30665166/31633725-ea7d16e6-b286-11e7-9daf-b57dc109fd39.png">
> 
> but the text above the actual "collaborate" buttons is still in $:
> 
> <img width="340" alt="screen shot 2017-10-16 at 22 03 00" src="https://user-images.githubusercontent.com/30665166/31633759-009e3b58-b287-11e7-8407-da3a7ecc9dde.png">
> 
> 
> ... and so is the order page:
> <img width="636" alt="screen shot 2017-10-16 at 22 08 33" src="https://user-images.githubusercontent.com/30665166/31633767-06a2acb4-b287-11e7-87bb-737429f805ef.png">

**Comment by xdamman** [comment]
Kea's collective was set to USD. I just changed it to EUR. I'll double check why it wasn't set to EUR in the first place. Normally /apply should take care of that.

**Comment by xdamman** [comment]
I've also updated their tiers to EUR

**Comment by piamancini** [comment]
He prefers his collective in USD because he feels the interface is confusing.

**Comment by piamancini** [comment]
Apply set it en USD, we put in EUR at his request but after seeing the interface and acknowledging most of his users are outside Europe he asked for it to be in USD. I'm reverting your change.

**Comment by xdamman** [comment]
But then shouldn't we move it to the US host?

Just in the Tiers table, update the currency for their CollectiveId

**Comment by piamancini** [comment]
> But then shouldn't we move it to the US host?
good point. I just emailed them saying that we fixed the ui currency, if they still want it in euro. I'll move them to OSC

**Comment by xdamman** [comment]
I think that if it's open source, it's better to have them all on one host. It will make things easier to have collectives to collectives transactions without fees.

**Comment by piamancini** [comment]
@xdamman can we close this?
