### ISSUE TITLE
"See our public company" link leads to a non-public Google Drive link

### ISSUE THREAD

**Issue by eKIK** [opencollective/opencollective#5130]
**Describe the bug**
The link named "See our public company" on https://opencollective.com leads to a non-public Google Drive link.

**To Reproduce**
1. Go to https://opencollective.com, and scroll down close to the bottom of the page, under "Open Company."
2. Click the link saying "See our public company".

**Expected behavior**
I am presented with documentation of some sort about the company, without having to request access.

**Screenshots**
![image](https://user-images.githubusercontent.com/1250308/150292248-f9c9ca45-fba2-4661-b97b-28f068a303f9.png)

**Comment by Betree** [comment]
Hi @eKIK, thanks for reporting this issue. There's indeed something wrong with the permissions on this folder, we'll look at fixing it asap.

**Comment by Betree** [comment]
This is fixed. Sorry about the delay!
