### ISSUE TITLE
New virtual card does not appear until refresh

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5131]
**To Reproduce**
1. Go to admin dashboard > virtual card > create card
2. Create a new card
3. Modal closes but new card is not displayed
4. Refresh and new card appears

**Expected behavior**
If someone is creating a virtual card, they probably want to see it right then, so it should appear without refreshing.

  P4 low frequency, low impact

**Comment by znarf** [comment]
Worked for me when following the steps today.

<img width="1339" alt="Screenshot 2022-05-18 at 22 06 55" src="https://user-images.githubusercontent.com/806/169146798-2c7c3f52-be76-469b-bb66-ab6fc9f7ccd2.png">

<img width="1298" alt="Screenshot 2022-05-18 at 22 07 08" src="https://user-images.githubusercontent.com/806/169146786-7680659c-9525-4354-ac61-41d14b3b7e29.png">
