### ISSUE TITLE
Make expense tags easier to find

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5138]
## User story 
As an expense submitter or admin I want to find the right tag for my expense so I can keep things organized and clear.

Right now, they are seemingly in a random order. You can't search them either.

![75c25477affaa3e989f7ec3b7e1fba40](https://user-images.githubusercontent.com/5498878/150937519-09739e30-e1c9-430e-ac7e-ee91d7d6b057.gif)

## Best solution for this problem
Instead of simply an 'add new tag' option in the text box, allow that to also function as search. As you type it shows a list if matching tags, and if none match it lets you create a new one.

## MVP
Alphabetize the list.

  P4 low frequency, low impact

**Comment by Betree** [comment]
> Right now, they are seemingly in a random order.

They're currently ranked by popularity: most used first.

> Instead of simply an 'add new tag' option in the text box, allow that to also function as search. As you type it shows a list if matching tags, and if none match it lets you create a new one.

Big yes for this

**Comment by kaylarep** [comment]
## [User story ](https://opencollective.freshdesk.com/a/tickets/81304)
> - The tag system seems really great, but currently isn't very useful. We wish there was an option to restrict how people applying for grants could use the tags. We've noticed that people applying will tag with things like "travel" when we already have a "transport" tag. 
>    - Due to this, new tags are made, and now we have 40+ of them on our collective. It'd be good if we could only allow admins to make new tags, and others could only choose from existing tags.
> - Another issue is, as of right now, you can't search through tags when attempting to add one to a transaction. This means it takes a lot longer to find the correct tags, and with all the different versions of one tag makes it hard to keep things organised. 
> - It'd also be great if we could tag donations to the pot. It would make it easier for us to find specific donations, such as money raised through people running campaigns, from sales of goods and more.
> - Something else that would be useful is if you could then archive tags. 
>    - We have tags for projects like our workshops that we no longer use due to the project ending. It would be good if we could archive this, so it's still usable to search but doesn't come up when attempting to scroll through the current tags.

> I really hope you consider these things, as they would make the admin side of running out mutual aid a lot easier! Right now the sheer amount of tags has made it hard to tag anything at all any more as you spend so long scrolling.

**Comment by Betree** [comment]
@alanna Closing in favor of https://github.com/opencollective/opencollective/issues/5523 as it proposes to implement the functionality described here:
> Instead of simply an 'add new tag' option in the text box, allow that to also function as search. As you type it shows a list if matching tags, and if none match it lets you create a new one.

@kaylarep This is interesting feedback, would be great to split it into distinct issues.

**Comment by kaylarep** [comment]
Done!
