### ISSUE TITLE
[DOCS] Documentation unusable on mobile Firefox

### ISSUE THREAD

**Issue by loleg** [opencollective/opencollective#5139]
As a user of OpenCollective, I want to be able to access the documentation on any device. Right now it is not possible for me to use the documentation site in portrait mode on the mobile Mozilla Firefox app, or on desktop Firefox in mobile preview. Toggling Enhanced Tracking Protection has no effect. This is because the menu is stuck in the open state, and all I can do is navigate around without actually seeing any content. The issue can be replicated on the official GitBook site, and I am sending a link to this issue to their support e-mail.

## Appears on

Firefox Daylight 96.2.0 on Android and Firefox 96.0 on Linux. I have also used LambdaTest to fire up a recent mobile and desktop Firefox (92.0) on Android and Windows to make sure this is not just my machine.

## How to reproduce

1. Open a current version of Firefox on a mobile phone, or enable mobile preview on desktop ("Responsive Design Mode" - Ctrl-Shift-M or the icon in the dev tools panel), and make sure you are viewing the page in portrait orientation.
2. Navigate to https://docs.opencollective.com/
3. You will briefly see the content, it is replaced by the menu which obscures the rest of the page. Tapping and sliding and navigating all have no effect.

## Screenshots

![Screenshot from 2022-01-25 09-27-17](https://user-images.githubusercontent.com/31819/150940344-d5135bad-1f1d-454d-8404-d3e7667a23e5.png)
![Screenshot from 2022-01-25 09-27-20](https://user-images.githubusercontent.com/31819/150940349-2c895b43-760b-4252-afad-e4c896f1ff74.png)
![Screenshot from 2022-01-25 09-38-57](https://user-images.githubusercontent.com/31819/150941638-b3e5fef2-180e-4cc4-83ca-e6e09d946f6c.png)

## Related issues

#2595

**Comment by Betree** [comment]
Thank you for documenting this issue. I've been personally facing it for quite some time now but I was hoping that [Gitbook](https://www.gitbook.com/) would fix it given that it must be affecting a lot of users. I'll open a support ticket on their side now.

**Comment by Betree** [comment]
Got an answer from Gitbook today:

> Thanks for reporting this. This is something we are already tracking and I have linked your report to the related topic in our internal product knowledge base. I can't promise a date for the fix, but it should be quite soon!

**Comment by petros** [comment]
Hi folks. Could you double check. This should not be an issue anymore.

**Comment by loleg** [comment]
This is now fixed & looking good - thanks @petros
