### ISSUE TITLE
Recurring expenses

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5144]
## User story 
Many users have recurring expenses that they need to submit at a regular interval. Some examples:
- All Open Collective employees need to submit their invoices each month for the same amount
- Many projects have recurring bills (hosting, domain, rent, etc). For online services, this need is now covered by virtual cards (but they're not available to all fiscal hosts).

## Best solution for this problem
- The interval should be configurable (we could start with week/month/year)
- Some parts of the expense will be fixed:
    - Payee
    - Payout method
- Some parts will eventually need to be updated by the user each time:
    - Attached files / receipts documents
    - Amount
    - Dynamic description (eg. include the month/year?)

## MVP
_TBD_

## Metrics 
_TBD_

## Documentation 
_TBD_

## Context
- Initially requested in https://github.com/opencollective/opencollective/issues/938
- Alternative to https://github.com/opencollective/opencollective/issues/3686
- Alternative / related to https://github.com/opencollective/opencollective/issues/1862

**Comment by kewitz** [comment]
**Features:**
- [ ] Expense requires manual approval (use submit on behalf)
  - [ ] Use a new template than the one used on Submit on Behalf
- [ ] Use abstracted Model to store recurring information
  - [ ] Create the correct associations (One-to-Many)
  - [ ] Update the merge accounts to update RecurringExpenses record
  - [ ] Update the ban collectives to delete RecurringExpenses record
  - [ ] If someone marks any recurring expense as SPAM, we delete the RecurringExpense record
- [ ] User should be able to set the interval (weekly, monthly, quarterly), the start date, and the end date (optional).
- [ ] User should be able to edit recurring expense information.
  - [ ] Shortcut: Always use the information from the last expense, this way the edits made this month will be reproduced next month.
- [ ] User needs to be able to cancel recurring expenses. Probably also a space to list these expenses.
  - [ ] For MVP it could be a button on the Expense draft page to cancel the recurring feature. (https://github.com/opencollective/opencollective/issues/4715)
- [ ] Daily cron work to process RecurringExpenses

**MVP:**
- Checkbox on Step 2 or Summary that display the recurring fields
- The filled expense is submitted at the time and the next expenses are sent as Invites on a selected date and interval.
- Using Submit on Behalf could work

**Design Requirements:**
- MVP: Recurring options fields. (Context: This is set one time per Expense)
- Future: Page to manage Recurring Expenses (Edit, Delete)

**Future Updates:**
- Tax forms: We can predict if any tax form will be required in the future. (e.g. after X months certain amount will be tax liable) We could be proactive about requesting these documents.
- Fully automated recurring expenses could require better invoice generation.
- Template variables in the Expense fields (title, description, additional information). `{month}, year, day, collective name, expense number, recurring expense counter, VAT Number}`
- Automatically cancel and notify a recurring expense after N failed attempts.

**Comment by kewitz** [comment]
From Babel user interview:

- Definitely helpful.
- Have internal repository to track expenses and recurring information.
- Have to input some manual information, would need to include invoice later on.
- Tiny modifications every time, would require editing.
- Even some sort of reminder would already be helpful.

Dreambig:
- Requiring multiple approval. (Currently tracking 3 person approval on spreadsheet before paying on OC)

**Comment by kewitz** [comment]
Projected created at https://github.com/opencollective/opencollective/issues/5144.

**Comment by Betree** [comment]
@kewitz should we close this in favor of https://github.com/opencollective/opencollective/issues/5305? I don't think this one is still relevant
