### ISSUE TITLE
Have a clearer error than `Slug must be unique` for accounts creation

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5154]
Based on https://opencollective.freshdesk.com/a/tickets/56587

> When i get to the page where i put in the grant request details i get " Validation error: slug must be unique ". 

This error is not clear for people who are not tech-savvy as they may not know what a "slug" is and the field is actually displayed as "Set your URL" in the interface. I propose to:
- Change the error message to `An account already exists for this URL, please choose another one`
- If not too complex, on https://staging.opencollective.com/foundation/apply/form, show the error right below the field

![image](https://user-images.githubusercontent.com/1556356/151009823-6156c9d4-ab6e-4c22-b6de-f0036a4afbdd.png)

**Comment by SudharakaP** [comment]
@Betree : Note that the OP mentions that the error they are seeing is `Validation error: slug must be unique`. I've seen this error occurring when calling `models.Collective.create`; such as, https://github.com/opencollective/opencollective-api/blob/9779ee778d31af35dd55a180041b759061dcf554/server/graphql/v2/mutation/CreateCollectiveMutation.js#L132. 

Maybe we need to catch these errors at all the places where `create` is called and change the error message to the one you suggested?

**Comment by Betree** [comment]
> I feel that the problem we are fixing in this issue is slightly different from what was originally mentioned in the issue. 

@SudharakaP I don't understand how your proposal differs from the content of the issue? As the body says, the feedback we're trying to address is:
> When i get to the page where i put in the grant request details i get " Validation error: slug must be unique ".

My proposal was to replace this message with "An account already exists for this URL, please choose another one". It's indeed great if we can do it globally, and also nice if we can show the error inline.

**Comment by SudharakaP** [comment]
> > I feel that the problem we are fixing in this issue is slightly different from what was originally mentioned in the issue.
> 
> @SudharakaP I don't understand how your proposal differs from the content of the issue? As the body says, the feedback we're trying to address is:
> 
> > When i get to the page where i put in the grant request details i get " Validation error: slug must be unique ".
> 
> My proposal was to replace this message with "An account already exists for this URL, please choose another one". It's indeed great if we can do it globally, and also nice if we can show the error inline.

I think my confusion arose from the fact that I saw a freshdesk issue where we didn't free the slug and then when the user tries to create the collective they get `Validation error: slug must be unique`. Anyways, I've added a `try {} catch {}` to handle this case as well; 

https://github.com/opencollective/opencollective-api/pull/7970/files#diff-0faa42b2ee0e59e514c94af8f4aa3e375cd1120e651b9ef18e11671602badc14R132-R143
