### ISSUE TITLE
[Roadmap] Gather Ideas for Q1 Sprint 2 Prioritisation

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#5159]
This is the issues to gather ideas for prioritization of the following sprint. 

Context
--------

You can find here a detailed [FIGMA FILE](https://www.figma.com/file/WJev8P6o4zS7NExfAPVhrg/Product-%26-Sprint-Process?node-id=0%3A1) that explains the Sprint Process

You can find here the [Spring Planning Project Board](https://github.com/orgs/opencollective/projects/5/views/1). You can filter per milestone if you want to see other sprints. The view should normally default to the current sprint. 

Who should use this issue?
--------------------

This issue should be used by the Sprint Lead of the following Sprint (not the current one) to start gathering some ideas for future prioritization.

This issue should be used by anyone who wants to submit an idea for immediate consideration. 

How to use this issue?
--------------

This is to gather ideas for things to be immediately built. This is not a backlog issue to dump every bug, request, etc. 

Please refer to the current Strategic Focus Issues to get a sense of the current Roadmap Priorities. You can find them at the top of the Planning Board. 

For FY22Q1S1 (year 22, 1st quarter, 1st sprint) and FY22Q1S2 these are: 

[API](https://github.com/opencollective/opencollective/issues/5140)
[Automation, Flexibility and Programmability of expenses and contributions](https://github.com/opencollective/opencollective/issues/5141)
[Community Governance](https://github.com/opencollective/opencollective/issues/5143)  
[Community Growth](https://github.com/opencollective/opencollective/issues/5148)

These areas will be further refined and reviewed every 12 weeks during the retreat week. Please refer to the [Sprint Calendar](https://calendar.google.com/calendar/u/0?cid=b3BlbmNvbGxlY3RpdmUuY29tX2ZxbTN0azYwNTRucGp2YTY1czBoajRpdXFrQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20) to see where we are and when the next retreat week is. 

Template
---------

Here's a template you can use to add a comment below with an idea. 

## What are they trying to achieve?

_When <situation>, I want to <motivation>, so I can <outcome>_

## How are they currently doing this?
 

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by alanna** [comment]
## #4024 Host admin can define more manual payment methods

OCF really needs this to create a check option, and I really think it will be used by other hosts in diverse ways as well

**Comment by alanna** [comment]
## #5129 Automate Benevity transactions

OCF is seeing growth through this payment channel and doing it manually is time consuming

MVP would be a script as described in the issue, but we could also use it as a use case for API integrations if it seems like a good option.

**Comment by alanna** [comment]
## #3593 Host can require minimum number of admins

Another one OCF spends a lot of time enforcing manually. This has already been fully specc'd and designed. I think this is a good example of a simple buy powerful governance related feature.

**Comment by alanna** [comment]
## #4824 Activate Goals for Projects

Users continue to create awkward workarounds using tiers with goals in projects, etc, but if goals are already working for Collectives is it really hard to just enable them in Projects?

**Comment by alanna** [comment]
## #4806 Add consolidated balance in Budget (including projects and events)

**Comment by alanna** [comment]
## #3903 Semi-automation of allocation payments for GitHub Sponsors

Doing this manually is getting out of hand... maybe this issue should be closed in favor of a full automation, but if that's going to take a long time, this semi-manual version would still be worthwhile.

**Comment by alanna** [comment]
## #4056 Remove the Host Plan selection settings

I consider this still outstanding from the pricing model project I don't know how many sprints ago, so it would be great to close it off.

**Comment by Memo-Es** [comment]
## https://github.com/opencollective/opencollective/issues/4356 Main nav bar updates
- Displaying all our marketing pages. Easier to navigate and find stuff
- New pattern for notifications (Both platform and user's)

**Comment by Memo-Es** [comment]
## https://github.com/opencollective/opencollective/issues/3438 and https://github.com/opencollective/opencollective/issues/4346 Tiers update
Page to edit tiers
Tier card updates (Accessibility, background, consistency)

**Comment by piamancini** [comment]
RSS FEED https://github.com/opencollective/opencollective/issues/3504

**Comment by SudharakaP** [comment]
## Update the Transaction and Expense Lists

Following up https://github.com/opencollective/opencollective/issues/4691, we could use the already existing designs to update the transaction and expense lists; 

Expense List: https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=15912%3A246112. 

Transaction List: https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=15912%3A246144

**Comment by SudharakaP** [comment]
https://github.com/opencollective/opencollective/issues/5172 Add Support to Remove Attendees from Events

- Don't think we have an existing design for this but this has been brought up multiple times so maybe we could plan this for the future.

**Comment by natehn** [comment]
# #4798 Virtual cards for Projects

It would be really helpful for certain Project expenses to be paid using a Virtual Card. If it is simple, this would help me with a manual process I and Alina take care of on a monthly basis.

**Comment by kaylarep** [comment]
# https://github.com/opencollective/opencollective/issues/2682 Customizeable Thank You Email

As requested by a user: https://opencollective.slack.com/archives/C6JTTA4SK/p1644007590497949

**Comment by alanna** [comment]
## #3593 Host can require minimum number of admins

I think if we're going to build more governance features, this should be the next one up. Both OCF and OSC really need this, and it would help a lot for compliance and best practice. It's a governance thing that's actually a great fit for a tech solution (while many others are a messy mix of tech and human stuff). It can also prevent situations like we're having now with one OCF Collective where they are having an internal dispute and one admin kicked out all the others to take over the project. Hosts should not be dragged into this kind of thing when the tech could help prevent it.

**Comment by alanna** [comment]
## #4694 Host admin can freeze Collective activity

This would be very useful for compliance stuff. Right now it's basically impossible to manually keep track of a special circumstance that means expenses for a certain host shouldn't be paid, as their expenses are just one of hundreds.

**Comment by alanna** [comment]
## #3330 Host admin can unhost Collective

Another compliance one... This is just a disaster waiting to happen if there's some kind of serious breach of policy and a host can't kick a Collective out. We're about to have an ethics policy and we need basic tools like this to implement stuff like that in practice.

**Comment by alanna** [comment]
## #5179 do not require payout method selection for cross host expenses

We'll need to solve this for Season of docs 2022. (And any other lingering issues for cross host expenses, but I'm not sure what's still needed)

**Comment by znarf** [comment]
> https://github.com/opencollective/opencollective/issues/5179 do not require payout method selection for cross host expenses

> And any other lingering issues for cross host expenses, but I'm not sure what's still needed)

@alanna Everything is tracked there https://github.com/opencollective/opencollective/issues/5064 If you have any problem with the feature, send your feedback this way.

**Comment by znarf** [comment]
For next sprint, we’ll normally not be changing our strategic focus. So, if you want to see a project prioritized, it really helps make it fit into one of those 4 topics. And mentioning it. https://github.com/opencollective/opencollective/issues?q=is%3Aissue+is%3Aopen+label%3A%22strategic+focus%22

If you think we should change our strategic focus without waiting for next discussion round (April 18th - April 22th), then start an internal discussion in the team channel before we start the prioritization process (before the end of the month).

Have in mind that we can also prioritize smaller issues through a "papercuts" process. For next sprint, we'll pick one or two "papercuts" topics out of the following one: https://github.com/opencollective/opencollective/labels/papercuts. This sprint we're currently focusing on Projects and Events.

**Comment by alanna** [comment]
I wasn't involved in setting the strategic focus so I'm just going to share
the issues I think are important. I don't have capacity to pre-filter them.
That needs to be owned and facilitated by whoever owns that part of the
process (who is that, by the way?). To me the strategic priorities seem
very broad. I could argue either for or against most of these issues on
that basis. And some things are prior commitments, like expenses between
hosts for season of docs, regardless of current strategy.

**Comment by piamancini** [comment]
> I wasn't involved in setting the strategic focus so I'm just going to share the issues I think are important. I don't have capacity to pre-filter them.

@alanna please try to share issues here that are inside the strategic focus. Otherwise we end up with a backlog of issues here and this is not the intent of this process. I understand you were not present in the strategic focus but they are an application of the long term vision I shared in the loom. 

We also have several Strategic Focus issues that not only explain the global context but they explain each focus individually. I understand you were not present in that discussion, but we had it during the retreat and I believe engineering did a fairly good job at communicating it. 

Adding totally unrelated issues here will not make it easier for anyone, those issues won't get prioritized in this sprint and it only makes it harder to prioritize and frustrating for you. 

If there are any questions regarding the focus, I can do another loom with @znarf to clarify. 

> That needs to be owned and facilitated by whoever owns that part of the process (who is that, by the way?).

As I shared in Slack and multiple calls and as it is stated in the figma file linked above, each sprint has a sprint leader. When I shared this issue in slack I was very clear that I was the next sprint leader while @znarf is this one. 

> This format also doesn't seem to take into consideration the weight that should be given to the priorities of our hosts, so it would be good to understand how that fits in.

This is a good point, but in this particular case it is clear that OCF and OSC priorities are taken into consideration. 
The github script is ready to be implemented this batch and the expense governance is an issue OCF made a priority. 

The idea is that the strategic focus can be debated and updated every 12 weeks during retreat week. 

> if we shut down gathering people's ideas prematurely, we're going to miss out on feedback from outside those who can directly participate in the sprint process.

I would be a bit careful with wording here, words carry weight. People are not and will never be shut down. There are multiple channels for everyone to raise an issue, we have calls every day or every week with most of the team. This is literally the sprint process, it's async and online. This is the first one and priorities were discussed during the live retreats but again I think we are communicating this quite clearly. The next one will happen in April. 

> And some things are prior commitments, like expenses between hosts for season of docs, regardless of current strategy.

The sprint is designed to leave space for papercuts and other issues like these. This is also specified in the figma file above or to @znarf´s comment in this thread.

**Comment by alanna** [comment]
All the issues I suggested are either related to the strategic focus points, or are things we've already committed to do and need to finish (like removing the pricing plans and the cross-host expenses). That is why I suggested them. I stand by my suggestions and want them considered for the sprint. If they don't make the cut, so be it, but they should be considered. I don't think it's constructive to try to exclude suggestions. It's useful data even if ultimately other issues are prioritised.

**Comment by piamancini** [comment]
> All the issues I suggested are either related to the strategic focus points, or are things we've already committed to do and need to finish.

Ok great. If this is the case, then what's the issue with the process? I am missing the source of the conflict withe the sprint design.

**Comment by piamancini** [comment]
For reference here are the Papercut issues that are prioritized and the team has been working on: https://github.com/opencollective/opencollective/issues/5084

**Comment by kaylarep** [comment]
I'm a bit lost about this process to be honest, will post an issue I think is important here, I think it fits in the Strategic Focus too:

**Comment by piamancini** [comment]
> ## #2682 Customizable Thank You Email
> As requested by a user: https://opencollective.slack.com/archives/C6JTTA4SK/p1644007590497949

@kaylarep it is unlikely we are able to undertake this one, since it's quite a big change. Do you have a second priority you can share with us?

**Comment by piamancini** [comment]
For API Strategic Focus: Programmatically authenticate users for metagov integration https://github.com/opencollective/opencollective/issues/5140#issuecomment-1031733333

**Comment by Memo-Es** [comment]
## [Avatar design update](https://github.com/opencollective/opencollective/issues/3885#issuecomment-945016075)

I think is a quick win and it would improve the current onboarding experience

**Comment by BenJam** [comment]
### Event papercuts

> as a event organiser I would like to remove an event attendee 

> as an event attendee I would like to cancel my attendance at an event

**Comment by brainwane** [comment]
### #4521 Add 'add to calendar' buttons for event sign ups.

As an event attendee, I would like to make it more likely that I'll remember to show up for an event I've signed up for.

And: as an [event organiser](https://opencollective.com/workshops), I'd like to make it more likely that the attendees at my event will show up, so I can better plan to work with the participants.

Currently, the user does get a `.ics` attachment as part of the confirmation email, but I suspect that if we add an "add to calendar" button just after the registration flow, people will use it and we'll see a decrease in no-shows.

**Comment by BenJam** [comment]
## Reviewing email contact details 

In some cases we receive support requests that would be more appropriate for the host or Collective to answer. This results in unnecessary load on our support teams. It would be good to review when we notify users of a situation that includes a support@ email address and replace it with the contact details of the host/Collective.

**Comment by znarf** [comment]
### Expense Across Hosts

Follow up: https://github.com/opencollective/opencollective/issues/5064

- https://github.com/opencollective/opencollective/issues/5179
- https://github.com/opencollective/opencollective/issues/5068
- https://github.com/opencollective/opencollective/issues/5260

**Comment by znarf** [comment]
### oAuth

https://github.com/opencollective/opencollective/issues/1660

We can't make it happen in one sprint, but we can work on the foundation and kick start design.

Strategic Focus: https://github.com/opencollective/opencollective/issues/5140

**Comment by kewitz** [comment]
## Recurring Expenses

#5144

**Comment by Betree** [comment]
We'll have to iterate on https://github.com/opencollective/opencollective/issues/5146, the project is not completed yet. More info to come about what's left to do.

**Comment by SudharakaP** [comment]
## Update sender can select which Project/Event/Tiers

Currently we send parent collective updates to child collectives. But it is mentioned that the best case solution is to let the user select which users they want to send the updates; https://github.com/opencollective/opencollective/issues/4673#issue-995325149

**Comment by Memo-Es** [comment]
## Update the page to find a host https://github.com/opencollective/opencollective/issues/4240
I deleted the stuff I proposed about tier cards and left this on instead. Hearing from folks in the last calls I had, I realized that it's super important, and we are not doing a very good job at that.

**Comment by kaylarep** [comment]
## Virtual Card Receipt Upload Reminder and Card Freeze https://github.com/opencollective/opencollective/issues/5269

Right now this process is manual, and that is not ideal/scaleable

**Comment by brainwane** [comment]
## Automated event reminders for signed-up participants #5237 

As an event attendee, I would like to make it more likely that I'll remember to show up for an event I've signed up for, and to do any pre-work the organizer has assigned ahead of time.

And: as an [event organiser](https://opencollective.com/workshops), I'd like to make it more likely that the attendees at my event will show up, so I can better plan to work with the participants. In order to inform the participants of pre-work/homework they should do to make the session more effective, or remind them to attend, I have to manually create an event update that gets emailed to them, and it does not have a `.ics` calendar invitation attachment. If I am busy then that task may not happen in time.

Currently, the user does get a `.ics` attachment as part of the confirmation email, but does not get any automated reminders from OpenCollective about the event. I got requests for these kinds of automated reminders from participants who accidentally did not show up to events I ran recently.

**Comment by brainwane** [comment]
## Increase flexibility for cancelling event registrations #5283 

As a person who has registered for an event, or as an admin/project owner for an event, I can cancel my/the user's existing registration for an event, to reflect that the user is not planning to attend or has been removed from the participant group.

For recent workshops, I had to contact Ben or Nathan to ask them to remove participant registrations (either because the participants emailed to say they couldn't make it, or because I was removing a participant who had not shown up for multiple previous events they'd registered to attend). 

Making this more self-serve, for users and for event organizers/admins, would have helped reduce this work and make it faster, and would have made it easier and faster to recruit more participants to take up those newly-freed slots.

**Comment by brainwane** [comment]
## Event signup waitlist #5284 

As a prospective participant in an event that is currently full, I want to be able to sign up for a waitlist, so that in case a slot opens up, I can get registered and attend. I don't want to have to manually go check the event frequently to see whether a slot has opened up.

As an event organizer for an event that is currently full, I want to have prospective participants on a waitlist and have them automatically notified in case there is space for them, so that if a user cancels, I'll have greater utilization and less waste at the event.

**Comment by Memo-Es** [comment]
##  [New Homepage](https://github.com/opencollective/opencollective/issues/4689)
* Finish design
* Test with users
* Push to implementation

**Comment by kaylarep** [comment]
## Track Balance on Virtual Cards https://github.com/opencollective/opencollective/issues/4556

if not this sprint, roll over to the next. It's difficult for collective admins to track their virtual card balances - they either need to do it manually, or ask a host admin to look- neither option is great.

**Comment by BenJam** [comment]
Closing this issue as we have the board set up over at https://github.com/orgs/opencollective/projects/5/views/19 and the discussion recorded at https://drive.google.com/file/d/1o9ExAZxo-xlYfP4ZeC-Hlr-snEcNnHLw/view?usp=sharing
