### ISSUE TITLE
Autopopulate Expense Info (description/date/amount) based on uploaded receipt/invoice

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#5161]
Related ticket: https://github.com/opencollective/opencollective/issues/1862

As a user: if I upload multiple receipts, it becomes a bit tedious to have to enter the information from the receipts, and would streamline the whole process if those fields could auto-populate the information extracted from the uploaded images.

Some other websites/apps are able to do this type of thing, and its very useful.

**Comment by Betree** [comment]
This was done in https://github.com/opencollective/opencollective/issues/6865
