### ISSUE TITLE
Provide guidance when creating large gift cards campaign

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5164]
Some companies set up huge gift card budgets that are not well optimized. We should add some warnings in the form to help admins who set them up to apply the best security and minimal fees configuration.

1. **Add a warning when using a credit card for gift cards above a certain amount**. Whenever the number of gift cards is > 50 or the total budget > $1000, we can assume that the cards are meant to be widely distributed and therefore want to avoid having too many transactions because banks can flag them as suspicious activity and because of the fixed payment processor fees that can represent a lot of money. Suggested message:
> :warning: Credit card payments are subject to [processor fees](https://stripe.com/pricing), which can become quite expensive on a large campaign like this one. Banks may also flag the numerous transactions as suspicious and start blocking them. We strongly recommend adding a prepaid budget to your account through a bank transfer. [Contact us](mailto://support@opencollective.com) to learn more about that.

2. **Add a warning when generating many gift cards without limiting hosts**. When distributing gift cards publicly (or at least to a broad audience), malicious people may create collectives as a means to withdraw the money for themselves. We can prevent that by forcing (or at least inciting) admins to limit their campaign to specific fiscal hosts. Suggested message:
> :warning: It looks like you're trying to generate many gift cards without limiting the fiscal hosts eligible for contributions. We strongly recommend limiting your campaign to specific fiscal hosts - otherwise, malicious users could end up creating fake open-source initiatives to withdraw the gift card amount.

On top of that, I would also suggest completely blocking the gift cards creation form when a credit card is picked as the payment method above 250 gift cards / $5000 as no bank will ever allow that.

**Comment by kaylarep** [comment]
@Betree 
for the first one, do we have a reply ready for when the 'contact us'?

**Comment by Betree** [comment]
@kaylarep When they contact us, we need to redirect them to the right fiscal host (usually OSC) admin who will send the bank account information to wire the money. I don't think we have a canned response, but if needed, @piamancini has probably done that a few times.

**Comment by alanna** [comment]
@Betree the wording was good but I think it's more likely that people will read it if it's shorter so I rephrased it a bit.

> ⚠️ Credit card payments incur processor fees, which can add up on large campaigns. Banks may also flag the numerous transactions as suspicious. We strongly recommend adding a prepaid budget via bank transfer instead. Contact us to learn more.

> ⚠️ We strongly recommend limiting your gift cards to specific fiscal hosts - otherwise, malicious users could create fake Collectives to withdraw the funds. Collectives under trusted fiscal hosts have all been vetted and confirmed as legitimate.

**Comment by Betree** [comment]
@alanna Thank you :+1:
