### ISSUE TITLE
Expense submitters to cancel their own expenses

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5167]
Requested in https://opencollective.slack.com/archives/C6JTTA4SK/p1643548140076189

Whenever an expense creator submits an expense to the wrong account (which could be resolved by #3981) or for whatever reason realized they did not want to create it (e.g. they were just testing around) it would be nice for them to have a way to reject it without requiring the intervention of a collective admin.

Current workaround: ask in the comments.

**Comment by shannondwray** [comment]
Closing this as @kewitz implemented delete expense as an expense submitter
