### ISSUE TITLE
Update receipt when transaction is refunded

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5171]
## User story 
When I click the download receipt button on this refunded transaction, I get a receipt that does not correctly reference the fact that it was refunded. This can cause confusion, but also a compliance issue, especially for hosts with tax-deductible status. Someone could get a transaction refunded and still download a receipt saying they get the tax deduction for it.

![Screen Shot 2022-02-01 at 4 19 21 PM](https://user-images.githubusercontent.com/5498878/151908602-f0022f26-5089-4c4c-9a14-7cb5bc733f9b.png)

## Best solution for this problem
When a transaction is refunded, update the receipt to show that clearly.

## MVP
Possibly disabling downloading receipts for refunded transactions? But I don't think that's a good solution because sometimes people actually need documentation of what happened.

  P2 low frequency, high impact

**Comment by emberwry** [comment]
Adding that I'd like this to happen automatically on virtual card payments that are refunded as well! Though guessing that ups the complexity and difficulty.

**Comment by BenJam** [comment]
I think marking the receipt as refunded is preferable to removing the receipt itself (in the UK you have to issue a receipt, and I think it's good form to keep it aviaaible). Incidentally, Open Collective Foundation issued more refunds recently, any idea why that is? https://opencollective-metabase.herokuapp.com/question/846-refunded-transactions-ocf

**Comment by Betree** [comment]
This could be a really simple one. How are we supposed to mark the receipt as refunded, will a simple text somewhere in the PDF be enough?

**Comment by alanna** [comment]
Yes a simple text note would be enough - ideally it would show the amount contributed, the amount refunded, and a $0 total. But any simple fix is great compared to nothing.

**Comment by Betree** [comment]
The decision is to simply show "REFUNDED" somewhere on the PDF, maybe next to the title

**Comment by alanna** [comment]
Any chance this could be actioned @iamronen @Betree ? It looks like it was supposed to be done last year at some point. This is causing an issue for OCF because the auditors are reviewing receipts for certain transactions and there's no indication on them if it was refunded. However it does show on the [contribution page like this](https://opencollective.com/brew/orders/532464).

**Comment by iamronen** [comment]
added to next cycle milestone for prioritization

**Comment by Betree** [comment]
Implemented the base solution, but I want to go back to it and change how things are displayed after we unify receipts with https://github.com/opencollective/opencollective-pdf/pull/912.

![image](https://user-images.githubusercontent.com/1556356/236204298-1afb6dc2-396a-45f9-b97c-ce44cfad8bb5.png)
