### ISSUE TITLE
Do not allow Collective admins to refund Added Funds transactions, only Host admins

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5173]
A case we did not consider in #4369

If Collective admins click `refund` on an added funds transaction, nothing actually happens. In this case, the host must manually pay the refund. They they think it’s been refunded, and the budget is debited, but nothing has actually happened and the host as no way to know they clicked that button. This recently happened and the payer was unhappy they didn’t actually get their money back, and we risk losing track of how much money we actually hold for a Collective.

I suggest we disable permission for Collective admins to do this, and allow it for Host admins only. It's OK for Collective admins to refund automated transactions because the system will actually reverse the transaction.

**Comment by Betree** [comment]
@SudharakaP Please look at https://github.com/opencollective/opencollective-api/pull/7110 before working on the fix for this one, the permissions check are going to change a bit for refunds.

**Comment by SudharakaP** [comment]
> @SudharakaP Please look at [opencollective/opencollective-api#7110](https://github.com/opencollective/opencollective-api/pull/7110) before working on the fix for this one, the permissions check are going to change a bit for refunds.

Thanks for mentioning that. I'll take a look. 👍🏽
