### ISSUE TITLE
Surface multi-currency expenses in the interface

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5175]
Part of #5146

@opencollective/design to define a pattern / generic style for this one, but we can already start prototyping based on the proposal below.

- [x] On the `Expense` object, we should expose two fields:
  - `Expense.amount`: amount in expense.currency
  - `Expense.amountInAccountCurrency`: amount in collective.currency
- [x] In the expenses list, expense page, and on the host admin, always show the expense amount with its target currency along with an estimate of the fees
     ![image](https://user-images.githubusercontent.com/1556356/151018545-aa12e6c6-0ab4-4b2e-a010-d33d71d5b92d.png)
- [x] Adapt the "pay expense" modal
    ![image](https://user-images.githubusercontent.com/1556356/151332540-924e6ff9-07d2-412b-991e-f47f17895c56.png)
- [ ] Update the way we compute "Page total" for multi-currencies
- [ ] (Bonus) Adapt the transaction details

**Comment by SudharakaP** [comment]
@Betree : I can help with this one if there's no objections. 🙂

**Comment by Betree** [comment]
@SudharakaP I already started digging into this one, we can have a call to better dispatch the work if your plate is empty and you need more issues to work on.

**Comment by Betree** [comment]
This is done, I've extracted the last bit to https://github.com/opencollective/opencollective/issues/5384
