### ISSUE TITLE
Use expense's currency for PayPal payments

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5177]
Part of #5146

- Set the [batch item currency](https://developer.paypal.com/api/payments.payouts-batch/v1/#definition-payout_item) to expense.currency
- The feature will be limited to automatic payments for the initial release
- It seems that our code already supports cases where the payout currency is not the currency of the host
  - See [PayPal documentation](https://web.archive.org/web/20210421103754/https://developer.paypal.com/docs/payouts/features/currency-conversion/)
  - See [our code](https://github.com/opencollective/opencollective-api/blob/c64a88d085594abe34e26be5d6cea873b99bc798/server/lib/transactions.js#L133)

**Comment by SudharakaP** [comment]
@Betree : I was looking at this and it seems to me that the expense.currency is already set at, 

https://github.com/opencollective/opencollective-api/blob/77f9137b1f7b843d11c566b84ce2a6f597d279ed/server/paymentProviders/paypal/payouts.ts#L39

Am I missing something? 🤔

**Comment by Betree** [comment]
@SudharakaP Is the payment triggered as expected? Is the fx rate recorded properly? There are many places in the code where we already use `expense.currency`. But until now it had no impact since expenses were always submitted with the collective currency. The goal of this issue is to make sure the feature works with Paypal. If everything's working perfectly already, then great!

**Comment by Betree** [comment]
I'm disabling multi-currency expenses for PayPal pre-approval (legacy API). Local tests did not go well, and it's really difficult to configure an account given that the API is now deprecated. We'll only support multi-currency expenses with PayPal for new integrations.

**Comment by SudharakaP** [comment]
> I'm disabling multi-currency expenses for PayPal pre-approval (legacy API). Local tests did not go well, and it's really difficult to configure an account given that the API is now deprecated. We'll only support multi-currency expenses with PayPal for new integrations.

Thanks for taking care of this one.
