### ISSUE TITLE
It would be great to give the option to the backer of having its company shown

### ISSUE THREAD

**Issue by nonnenmacher** [opencollective/opencollective#518]
I don't understand why when an individual is electing to support on its personal behalf and still indicated a company, the latter is shown as 'the sponsor' while it doesn't necessarily endorse this.

It should be a preference of the supporter and not a default choice of some 'data logic' that prefer to display something when it had a choice.

the `  stuff = <something> || <something else> ` isn't always the better option in this case.

note: not happy with my own treatment for that matter.

**Comment by piamancini** [comment]
Hi @nonnenmacher. Yep, we saw that and we are fixing it with this: https://github.com/opencollective/frontend/pull/54 If you add your company you'll show up as a sponsor. 

> note: not happy with my own treatment for that matter
Is there anything we can do to help?

**Comment by nonnenmacher** [comment]
Don't know as I didn't lookup the page listing contributors ;-)

Was just seen the return, that describe me as my company, which I considered 'not cool' at that time.
But its a small matter, don't bother if you corrected it.

**Comment by nonnenmacher** [comment]
In fact this case is exactly the 'inverse' of #54, as you should offer the choice for an individual to indicate a company, and still choose to be displayed as an individual.

Or perhaps have a choice option to choose as 'company' or 'individual' (or even 'anonymous') supporter/backer and have this solve all present and futur cases.

The importance of this, is that we should collectively support such initiatives and not lets 'uberization' of the world, diminishing the responsibility of 'Uberizer' companies to buy of their responsibilities at very low pocket money for them.

This is a matter orthogonal to UI/Code and Politics ;-)

**Comment by piamancini** [comment]
You can choose to support as an organization or as an individiual and your individual profile will show the organizations you are part of. 
we are working on the anonymous version. ftm you can choose not to complete any of the details (except mail which we require but don't display). 
This is all new and so we are still ironing out details, thank you for your feedback!
