### ISSUE TITLE
Track taxes as separate transactions

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5181]
An alternative proposal to https://github.com/opencollective/opencollective/issues/4494
See https://opencollective.slack.com/archives/GFH4N961L/p1643102227024700

# Problem

Taxes are collected by the host and sit on their bank accounts until they're paid. They're not counted in the available balance, so hosts need to add funds or create expenses if they want to materialize the changes. But since we don't link these added funds/expenses to the VAT, the metrics we are showing won't be accurate.

# Solution

In the spirit of the latest ledger design, we should track taxes as separate transactions (`kind=TAX`). Expected benefits:
- Easier accountability
- Ability to track whether the money has been paid to the government or not through `SettlementStatus`
- Would allow adding more than one tax type per transaction (e.g. in Europe, many products have an"Recycling tax" along with their VAT)

**Comment by alanna** [comment]
I think we need this for #4532 as well. I'm doing a lot of manual tax stuff manually for the NZ hosts and it's only manageable because the number of transactions is tiny. It's going to get out of hand soon.

**Comment by jfdh** [comment]
This issue is also related to #5137. The fact that we do not enforce people to provide their tax number in the expense process gives me more to do. I need to open the attachment, check their vat number, check its validity, and record this in a spreadsheet. Will look at how we can prioritize this for next sprint.

**Comment by alanna** [comment]
@jfdh perhaps it's useful for us to share more details about our VAT and GST processes?

For OCNZ, every six months I need to:

* Total up all the GST collected (only applies to products and services, not donations) and pay this amount to the government
* Total up all the GST paid on invoice expenses (not reimbursements, for boring complicated reasons), ensure we've recorded their GST numbers, and claim this amount back from the government
* Pay back the GST reclaimed to the relevant Collectives (this part is fine to do manually)

If local tax was handled separately in the data it would be much easier to calculate the right numbers. But it's important to note that to do the above local tax needs to separated in expenses as well as contributions.

**Comment by Betree** [comment]
Solving this issue would help record taxes correctly, especially now that we support them for both expenses and contributions. We know that taxes usage is going to increase in the future; the earliest we solve it the simplest it will be to migrate. I would love to see it prioritized in the coming year.
