### ISSUE TITLE
Provide Payout Method and Account context when Approving/Paying Expenses

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#5183]
## User story 
> As a Collective host, I want to know if the transaction I'm about to pay out is fraudulent.

## Best solution for this problem
- [ ] https://github.com/opencollective/opencollective/issues/3258#top

In addition to the above, which provides context about the behaviours of this user in isolation we can surface information as a platform provider that might indicate that the user is acting suspiciously:

- the user's payout method is linked to multiple accounts
- the user has a high number of payment or payout methods
- the user has recently had a payout or payment method blocked 

## MVP
On the expense page, a small notification banner can be shown to the admins approving/paying if we detect the account number was used by any other user or with it was used with different account holder names before.

On other pages where we don't display the full expense information, we should add a warning sign notifying that the admin should check the expense page for more details before approving/paying for the expense.

**Comment by BenJam** [comment]
+1 this is a good issue, I wonder whether we should spend a quarter working on 'risk, compliance and security' to prioritise work like this.

**Comment by kewitz** [comment]
@Memo-Es could you provide some sketches on how to best present warning messages for a potential fraudulent expense?
I think the main idea here is to make sure host admins are aware there's something weird with the expense or the payee.

**Comment by kewitz** [comment]
Specifications:
- [ ] Ground Work
  - [ ] Create an abstract "SecurityCheck" GQL object that represents any potential risk factor.
  - [ ] Add "SecurityChecks" resolver to the Expense object.
- [ ] Implement expense checks
  - [ ] How long is the user on the platform?
  - [ ] How long is the collective on the platform?
  - [ ] How long is the payee on the platform?
  - [ ] Number of expenses submitted by the user
  - [ ] Number of expenses with the same payee (can differ from the user submitting the expense)
  - [ ] Is the user submitting the expense to the actual payee?
  - [ ] Does the user has 2FA enabled?
  - [ ] Number of expenses paid to this Payout Method
  - [ ] Number of Payout Methods with this same fingerprint
  - [ ] Expense amount compared to average expense amount to this collective
  - [ ] If the expense was approved by the same user
  - [ ] If the reimbursement is missing a receipt
  - [ ] If the user is likely to be operating multiple accounts (see https://github.com/opencollective/opencollective/issues/5200 or https://github.com/opencollective/opencollective/issues/5183)
  - [ ] How many expenses were paid for this exact Collective and Payout Method 4 expenses paid to this account if it's an existing contributor
  - [ ] Is connected to other platforms? Github account / Twitter account
- [ ] Frontend
  - [ ] To be defined
