### ISSUE TITLE
Event Without Tickets Do not Show `View Event` Button

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5186]
This was initially asked in Slack at, https://opencollective.slack.com/archives/GFH4N961L/p1643878367803659

We currently do not show the `View Event` button on Event Cards both on the collective page (ex: https://opencollective.com/foundation) and on the events page (ex: https://opencollective.com/foundation/events) when the even the event do not have tickets or when the event is passed. 

The relevant code is at, 

https://github.com/opencollective/opencollective-frontend/blob/ab3deb8b84e20203c57e92533d9a92a15626b480/components/contribute-cards/ContributeEvent.js#L32

and,

https://github.com/opencollective/opencollective-frontend/blob/0e19edff2e94d2b7c4603e6e6a639483e36eb89a/lib/events.js#L21-L23

This creates a problem whereby if an event do not have tickets but it is a current event then the `View Event` button isn't shown leading to confusion on the part of the user. I suggest that the `View Event` button should be shown always when the event is not passed irrespective of whether the event has tickets or not. 🤔

**Comment by Betree** [comment]
Hiding the button was part of the initial design for past events (you'd need to click the title to access them). Looking at https://github.com/opencollective/opencollective/issues/3262#issuecomment-1009589502, it seems that we've moved away from this pattern. So we should indeed always display this button, regardless of whether the event is passed or has no tickets.

**Comment by SudharakaP** [comment]
> Hiding the button was part of the initial design for past events (you'd need to click the title to access them). Looking at [#3262 (comment)](https://github.com/opencollective/opencollective/issues/3262#issuecomment-1009589502), it seems that we've moved away from this pattern. So we should indeed always display this button, regardless of whether the event is passed or has no tickets.

Thanks. I've updated the PR, showing the `View Event` button for all events regardless whether they are passed or has no tickets.
