### ISSUE TITLE
Ability to disable GST at the collective level

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5187]
Based on https://opencollective.freshdesk.com/a/tickets/56112

> Gift Collective has de-registered for GST and now needs to not apply it, even on products, services, and event tickets.

This is supported by VAT, so it shouldn't be too complex.

**Comment by alanna** [comment]
What we need is a Host-level setting, not Collective-level. The Host is either GST registered (like OCNZ) or not (like Gift Collective). All Collectives under a Host should follow that global setting, regardless of their mission or tiers etc.

**Comment by Betree** [comment]
@alanna I got confused because "Gift Collective" made it sound like it was a collective, not a host. Anyway, this is already possible; all they have to do to disable the GST feature is to remove the GST number from their settings.

If ever needed, I almost fully implemented the feature to disable GST at the collective level in https://github.com/opencollective/opencollective-frontend/compare/feature/disabled-gst-collective?expand=1 + https://github.com/opencollective/opencollective-taxes/compare/feature/disabled-gst-collective?expand=1.
