### ISSUE TITLE
Intermittent E2E Failure on Add Funds Modal on Host Dashboard

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5191]
It seems that we have a E2E failure on the Add Funds Modal from time to time. 

```
1) host dashboard
       Add funds modal
         Can add funds and platform tip as collective host:
     AssertionError: Timed out retrying after 15000ms: Expected to find element: `[data-cy="funds-added"]`, but never found it.
      at Context.eval (http://localhost:3000/__cypress/tests?p=test/cypress/integration/29-host.dashboard.test.js:1133:10)
```
For example; https://github.com/opencollective/opencollective-frontend/runs/5051784634?check_suite_focus=true

**Comment by alanna** [comment]
Is this still happening?

**Comment by SudharakaP** [comment]
I didn't see this happening recently and hence closing. But will re-open and investigate if I see this again. 🤔
