### ISSUE TITLE
Incorrect Refund Amounts for Expense Refund with Payee Covering Payment Processor Fees

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5194]
**Describe the bug**

Noticed this while working on https://github.com/opencollective/opencollective/issues/4691. It seems that when a user refunds a expense transaction where the payment processor fee has been payed by the payee, the refund expense has incorrect payment processor fees. 

**To Reproduce**
1. Submit an expense with the payee paying the payment processor fees. 
2. Refund the expense. 
3. Notice the refund transactions. 

**Expected behavior**

For expense refunds the payment processor fee should be 0 regardless of whether the payment processor fee is covered by the collective or the payee. 

**Screenshots**

### Expense and Refund Transaction from the Perspective of the Collective

![image](https://user-images.githubusercontent.com/12435965/152410977-df0b2afb-9bda-4f50-b280-996397026bee.png)

### Expense and Refund Transaction from the Perspective of the Payee

![image](https://user-images.githubusercontent.com/12435965/152411105-7e13b2cd-9e9b-4f07-aeb7-27279aae91b1.png)

**Comment by SudharakaP** [comment]
Looking at this further it seems that we intentionally add the paymentProcessorFee fee as a positive value to the refund when the payee is paying the payment processor fee. 

https://github.com/opencollective/opencollective-api/blob/73abef105abd28b47f8d7746ec827c3384f7d451/server/lib/payments.js#L203-L216

This is what led to my confusion as the refund expense object has a `paymentProcessorFee`. Anyways, I think we can mitigate this by adding the payment processor fee directly to the `amount` and for this I've proposed a PR. 

@Betree : Since you've worked on this part recently I've assigned this to you. Let me know if this approach is correct and if I missed anything here. 🤔

**Comment by Betree** [comment]
> For expense refunds the payment processor fee should be 0 regardless of whether the payment processor fee is covered by the collective or the payee.

I don't agree with that, could you elaborate on why we would want the processor fees to always be 0 for expenses?

If I paid `-100` in processor fees and they're fully refunded by the provider, I expect to see `+100` for the processor fees on the refund. That way, the sum of the column will tell me that `$0` was paid in processor fees. If I don't record this `+100`, the sum will inform that `100` were paid in processor fees, which is false.

**Comment by Betree** [comment]
I think the issue you're confronted with is only a problem of labeling. You want to do something like:

```jsx
{!t.isRefund ?
  `Payment processor fees: ${t.paymentProcessorFees}`
  : `Refunded payment processor fees: ${t.paymentProcessorFees}`
}
```

**Comment by SudharakaP** [comment]
> > For expense refunds the payment processor fee should be 0 regardless of whether the payment processor fee is covered by the collective or the payee.
> 
> I don't agree with that, could you elaborate on why we would want the processor fees to always be 0 for expenses?
> 
> If I paid `-100` in processor fees and they're fully refunded by the provider, I expect to see `+100` for the processor fees on the refund. That way, the sum of the column will tell me that `$0` was paid in processor fees. If I don't record this `+100`, the sum will inform that `100` were paid in processor fees, which is false.

Here I think the labeling of the variables is what got me. Since on the API we use the same variable name `paymentProcessorFeeInHostCurrency` for both the transaction and the refund transaction I thought why we have payment processor fee on the refund. I was expecting to see something like, `refundedPaymentProcessorFeeInHostCurrency` but now your explanation solved it for me. Thanks. 👍🏽 

> I think the issue you're confronted with is only a problem of labeling. You want to do something like:
> 
> ```js
> {!t.isRefund ?
>   `Payment processor fees: ${t.paymentProcessorFees}`
>   : `Refunded payment processor fees: ${t.paymentProcessorFees}`
> }
> ```

This makes sense. I wasn't showing this refunded payment processor fee on the refund expenses currently but will look into adding it. Thanks. 👍🏽
