### ISSUE TITLE
Sock puppet detection

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5200]
## User story 

> As a Collective contributor, I want to know if an admin or anyone is trying to obscure identity or game the system using multiple accounts, so that I can trust the transparency of the activity I can see in a Collective to be honest. 

## Best solution for this problem
It seems that this issue is cropping up in different ways for different features, but I think we should solve the underlying problem instead of addressing it different ways in different contexts. I know we already have some fraud detection going on but it's not really visible to users most of the time. I think the OC way of going about this would be to focus on transparency and using tech to give people tools to take action, without necessarily assuming what the action should be (sometimes people have legit reasons to have multiple accounts). At the same time, we need to be very careful of privacy considerations (not 'outting' someone as associated with a profile that they are trying to keep separate for legit reasons).

I honestly have no idea how to go about solving this, but I wanted to raise an issue so we have a place to gather info about it.

## Ideas

- surface any of the measures in #5183
- if multiple accounts on the collective share an IP address 
- if multiple accounts share linked profiles (github, twitter, website etc)

**Comment by Betree** [comment]
Duplicate with https://github.com/opencollective/opencollective/issues/5183?
