### ISSUE TITLE
Update cypress to version 9

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5204]
In our [Frontend](https://github.com/opencollective/opencollective-frontend/) repository, we're using [Cypress](https://www.cypress.io/) version 8.

The latest version is 9 but the update is currently blocked because of breaking changes.
https://github.com/opencollective/opencollective-frontend/pull/7446

We would like to upgrade to the latest version and make sure our E2E test suite pass properly on GitHub actions.

**Comment by zhyd1997** [comment]
I'm glad to work on the issue if possible!

**Comment by znarf** [comment]
:gift: :money_with_wings: A **$100** / **$200** bounty was attached to this issue.

Anyone submitting a Pull Request fixing the E2E test suite will be rewarded with $100 when the Pull Request is reviewed, accepted and merged.

Anyone explaining exactly what the regression is (e.g.: when it was introduced, why it breaks the test suite) will be rewarded $100.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by snitin315** [comment]
@zhyd1997 are you working on this?

**Comment by zhyd1997** [comment]
You can do it if you want, we just want to quickly fix this issue!😁

**Comment by znarf** [comment]
🏆 This issue was completed by @snitin315 

To claim the bounty please, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new  Please make sure to mention the ticket number in the invoice and in the expense title.
