### ISSUE TITLE
Update @apollo/client to 3.7.16

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5205]
In our [Frontend](https://github.com/opencollective/opencollective-frontend/) repository, we're using [Apollo Client](https://github.com/apollographql/apollo-client) version 3.3.21.

The latest version is 3.7.16 but the update is currently blocked because of breaking changes.
https://github.com/opencollective/opencollective-frontend/pull/6703

The breaking change was likely in Apollo Client version 3.4.0 already.

We would like to upgrade to the latest version and make sure our E2E test suite pass properly on GitHub actions.

**Comment by znarf** [comment]
:gift: :money_with_wings: A **$100** / **$200** bounty was attached to this issue.

Anyone submitting a Pull Request fixing the E2E test suite will be rewarded with $100 when the Pull Request is reviewed, accepted and merged.

Anyone explaining exactly what the regression is (e.g.: when it was introduced, why it breaks the test suite) will be rewarded $100 (extra if together with the fix PR).

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by znarf** [comment]
Sorry, let's pause on this issue for a bit as it seems the E2E tests are passing today.

**Comment by znarf** [comment]
Ok, at least one test is still heavily flaky. The goal of the issue is to make sure it's stable again. 

<img width="969" alt="Screenshot 2022-02-08 at 13 58 12" src="https://user-images.githubusercontent.com/806/152991710-4153dd64-53e7-4bd6-ae16-032e7bafc6c5.png">

We should be able to run the test suite 3 times in a row without this failure.

**Comment by alurban** [comment]
@JoyLubega are you already working on this? I thought about looking at it, but don't want to step on your toes. (I'm also very new to this project, so unsure about etiquette with assignees especially on bounties)

**Comment by JoyLubega** [comment]
You can pick it up. I had started but its okay. you can take it

**Comment by alurban** [comment]
> You can pick it up. I had started but its okay. you can take it

ok! I'm glad I asked first, hope you're having a good day 😊

**Comment by alurban** [comment]
@znarf I have this working with @apollo/client 3.4.17, with minimal changes relative to opencollective/opencollective-frontend#6703 (only one new Cypress condition is added). So the breaking changes definitely came in version 3.5.0. I've been trying to triangulate using [their changelog](https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#apollo-client-350-2021-11-08) but it's proving tricky. The biggest change introduced in 3.5.0 is to `useLazyQuery`, which now returns a promise.

The pull request I have open for this is opencollective/opencollective-frontend#7658.

**Comment by Betree** [comment]
This issue is up for grab

**Comment by brymut** [comment]
Sorry to ping again @betree @znarf

**Comment by snitin315** [comment]
@brymut yes. You can pick this.

**Comment by b4s36t4** [comment]
Is this up grab? can I pick this?

**Comment by znarf** [comment]
The issue was solved in https://github.com/opencollective/opencollective-frontend/pull/8866
