### ISSUE TITLE
New Comment on expense notification: Wrong name

### ISSUE THREAD

**Issue by snitin315** [opencollective/opencollective#5207]
**Describe the bug**

Addressed as `Hi ESLint` instead of `Hi Nitin`.

**To Reproduce**

New Comment on expense notification

**Expected behavior**

Should be addressed as the user name instead of the collective name.

**Screenshots**

<img width="596" alt="Screenshot 2022-02-07 at 5 49 16 PM" src="https://user-images.githubusercontent.com/46647141/152786892-45e6358f-affb-451e-b909-3553cce9a3c6.png">

**Desktop (please complete the following information):**

Any

**Smartphone (please complete the following information):**

Any

**Additional context**

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by znarf** [comment]
We're sending this email to different people so "Hi ESLint" is ok for the Collective admins but not for the Expense payee.

As a simple fix, we should remove customization of the "Hi XXXX" here and just say "Hi,".

This is in `collective.comment.created.hbs`

**Comment by alanna** [comment]
For people like me who are admin of many Collectives, it's important to have the Collective name in here as well, so we know which one it's for.

**Comment by scenaristeur** [comment]
@alanna looking in the code, it seems that the collective name is in the subject of the mail.

Couldn't it be 'Hi {admin name} , x posted a comment on an Expense for {collective Name}, {expenseName} '

Or ' x posted a comment for {expenseName}  expense of {collective name}'

And perhaps with a short resume of the comment if possible ?

**Comment by Betree** [comment]
@scenaristeur The situation was well summarized in https://github.com/opencollective/opencollective/issues/5207#issuecomment-1032572774. This email is sent to both the admins and the expense payee, so we can't just say `Hi {admin}`. The proposal above to just say `Hi` sounds like the simplest fix possible.

**Comment by nosro** [comment]
@Betree I'm going to tackle this as my first issue, since it appears to be an easy one.

**Comment by Betree** [comment]
Resolved by https://github.com/opencollective/opencollective-api/pull/7830 by removing the name, I opened https://github.com/opencollective/opencollective/issues/5872 to address this in a more consistent way for the future.
