### ISSUE TITLE
Refunded Expense Transactions have wrong labels

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5208]
Currently when an expense is refunded (marked as unpaid) the expense moves to an approved state whereas the refund transaction also has an approved state. 

![image](https://user-images.githubusercontent.com/12435965/152801889-a0093240-4575-44dc-949d-d4f1da1a857f.png)

Ideally when the expense is refunded, 

1) The expense transaction should be marked `Refunded`.

2) The expense refund transaction should be marked `Completed`.

3) ~~The admins should not be able to pay the refunded expense (currently since it goes to approved state it's possible to pay it back).~~

Related to https://github.com/opencollective/opencollective/issues/4691

@opencollective/core-developers : Let me know if I missed anything here or if there's any objections to this proposal.

**Comment by znarf** [comment]
Item 3 is wrong, I don't see why you would like to change this.

Maybe that’s already clear, but please make sure that your work only impact Transactions, not Expenses themselves.
