### ISSUE TITLE
Collective pages and profile page broken

### ISSUE THREAD

**Issue by jancborchardt** [opencollective/opencollective#521]
I get this on all collective pages and my profile page:
![screenshot from 2017-10-17 17-39-48](https://user-images.githubusercontent.com/925062/31674527-5006ffbe-b362-11e7-8401-a1ec597aa67e.png)
Check https://opencollective.com/opensourcedesign/

cc @piamancini @asood123 cause it seems pretty blocking. (Happens regardless of browser.)

**Comment by asood123** [comment]
Can you try reloading? We pushed a release that caused it and have reverted it. Try cmd+shift+r to make sure it's not cached.

**Comment by jancborchardt** [comment]
Seems to work now, tested on mobile Firefox cause I'm on the road. :+1:
