### ISSUE TITLE
Dead Link on OCF homepage

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#5211]
On this page https://www.opencollective.foundation/ 

Please redirect this link to go to https://docs.opencollective.foundation/how-it-works/fees
![image](https://user-images.githubusercontent.com/64920686/152899712-b4d30fe1-f954-485e-8af5-7095df1e725e.png)

**Comment by kaylarep** [comment]
thanks @SudharakaP ! :)

**Comment by SudharakaP** [comment]
> thanks @SudharakaP ! :)

You are welcome. 🤗
