### ISSUE TITLE
Contact Collective Modal within the Transactions/Expense Page Gives Error on Sending Message

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5212]
It seems that the collective contact form doesn't work correctly when it is accessed within the Expense or Transactions page. It gives the following error on the API: 

```
error: GraphQLError: Variable "$collectiveId" got invalid value "nyvwlnxe-389pojvk-zwd56daq-407rmkgz"; Int cannot represent non-integer value: "nyvwlnxe-389pojvk-zwd56daq-407rmkgz"
```
![image](https://user-images.githubusercontent.com/12435965/152952198-329681c9-e081-4ce1-999e-6da807a24012.png)

**Comment by Betree** [comment]
I was just looking at this one. We need to make sure:
1. Errors are properly displayed
2. The modal should be compatible with data from V1 and v2

**Comment by SudharakaP** [comment]
> I was just looking at this one. We need to make sure:
> 
>     1. Errors are properly displayed
> 
>     2. The modal should be compatible with data from V1 and v2

@Betree : I've proposed a fix where we pass the legacy ID as well and the modal handles both `collective.id` and `collective.legacyID`. One thing I noticed is that in the case of a `Network Error` we do not show the error within the `getErrorFromGraphqlException` function. This seems to be the reason we get a black error in the modal. I've added the `message` of the error to fix this issue. 

https://github.com/opencollective/opencollective-frontend/blob/7db7cbbbc364db190c93330fc6b2432d9cc0c002/lib/errors/index.js#L134

Let me know. Thanks. 🙂

**Comment by Betree** [comment]
@SudharakaP `i18nGraphqlException` is a better fit to display errors. It knows how to translate some of them and has a fallback in case of unknown/network errors.

**Comment by SudharakaP** [comment]
> `i18nGraphqlException`

Thanks for the explanation. My thinking is that we need to move all `getErrorFromGraphqlException` to `i18nGraphqlException`. I'll open a separate issue for that if there's no objection and merge this PR for now. 🤔

**Comment by SudharakaP** [comment]
I've opened a separate issue; https://github.com/opencollective/opencollective/issues/5216 proposing moving from `getErrorFromGraphqlException` to `i18nGraphqlException`. Since this issue is fixed now I am closing this.
