### ISSUE TITLE
Update sequelize to 6.16

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5215]
In our [API](https://github.com/opencollective/opencollective-api/) repository, we're using [Sequelize](https://www.cypress.io/) version 6.13.

The latest version is 6.16 but the update is currently blocked because of breaking changes (typescript).
https://github.com/opencollective/opencollective-api/pull/7072

We would like to upgrade to the latest version and make sure our test suite pass properly on GitHub actions.

**Comment by znarf** [comment]
:gift: :money_with_wings: A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by znarf** [comment]
🏆 This issue was completed by @snitin315 

To claim the bounty, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new  Please make sure to mention the ticket number in the invoice and in the expense title.

**Comment by ephys** [comment]
I'm not speaking for the other maintainers, just for myself, and I know it's too late but I think these funds would have been better donated to the Sequelize development fund as [we're the one that fixed the issue](https://github.com/sequelize/sequelize/pull/14146). 
I won't raise hell over it, after all [we're also the ones that introduced it in the first place](https://github.com/sequelize/sequelize/pull/13909), but I felt the need to speak up as I felt a bit cheated to not have been made aware that there was a bounty related to fixing this issue.

**Comment by znarf** [comment]
@ephys I understand the feeling.

I'm personally convinced that @snitin315 deserves the bounty here. As a trusted contributor, he investigated it, created an issue in your repository and followed up. The bounty here was a generic one, figuring what what's wrong with latest Sequelize update, not precisely asking to fix something specific on Sequelize side.

I'm also convinced that the Sequelize project deserves something for the help here. And also another recent one here: https://github.com/opencollective/opencollective-api/pull/7214 But more generally to sustain your work, which is a critical component of our API project.

We'll immediately donate $100 to match this bounty. Also, I'm happy to tell you that in the next days, we will start a small Fund to give back to OSS projects we use, this is something we planned in our last team meeting in January. Sequelize will definitely be a natural recipient for it.

**Comment by ephys** [comment]
@znarf You're right, it would be unfair to take the bounty away from @snitin315 who has been a great person to collaborate with the whole time. My comment also did not take into account the work that went into https://github.com/opencollective/opencollective-api/pull/7142 before it reached us

I'm really grateful and pleasantly surprised by the bounty match, as well as this great news. Thank you, it means a lot to us!
