### ISSUE TITLE
Replace All Instances of `getErrorFromGraphqlException` to `i18nGraphqlException`

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5216]
We have two different functions which handle GraphQL errors; `getErrorFromGraphqlException` and `i18nGraphqlException`. It seems that `i18nGraphqlException` should be used at all places where we are currently using `getErrorFromGraphqlException` since `i18nGraphqlException` is better at handling errors and has a fallback as well in case there's an exception which isn't handled there. This could also prevent certain cases like https://github.com/opencollective/opencollective/issues/5212#issuecomment-1032448265 from happening due to the `getErrorFromGraphqlException` not having proper fallback. 

I would suggest, 

1) Replacing all instances of `getErrorFromGraphqlException` with `i18nGraphqlException`. 
2) Make the `getErrorFromGraphqlException` private. 

Related issue comment; https://github.com/opencollective/opencollective/issues/5212#issuecomment-1032486983

cc: @Betree

**Comment by Betree** [comment]
There's a reason why we have two separate helpers:

- `getErrorFromGraphqlException`: get an Error object. This is useful to detect the kind of error that happened. For example, one may want to do something like this: 

```jsx
const { error } = useQuery(...);
const parsedError = getErrorFromGraphqlException(error);

return (
  <div>
    <button>Submit</button>
    {error.type === ERROR.NETWORK && <button>Retry</button>}
  </div>
)
```

- `i18nGraphqlException`: syntactic sugar around `getErrorFromGraphqlException` + `formatErrorMessage`

It's great if we can keep that distinction. Most (all?) places are indeed using this helper mostly to get the message. It's fine to replace things as you suggest for cases like:

```es6
const errorMsg = getErrorFromGraphqlException(err).message;
```
