### ISSUE TITLE
Support Metrics Report January 2022

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#5218]
### Support Metrics Report January 2022
This report looks at the trends around support to help us better understand areas we need to improve and highlight key topics for the month. 

**Tickets received** 

![capture](https://user-images.githubusercontent.com/57156267/153323530-35c38097-eae6-4f75-bcef-0c0d3ee3c8f4.png)

The number of tickets received decreased by about 8% from 2,270 in December to 2,080 in January. By removing blank tickets and expenses notifications where no action was required the trend remained roughly the same (14% decrease) with 747 tickets compared to 873 in December. Y[ou can find the working files here. ](https://docs.google.com/spreadsheets/d/1pO6FQzpxUXpBms43J94rxhX4toU2IP3S/edit#gid=439548968)

The tickets contribution across the teams was as shown below:

![capture](https://user-images.githubusercontent.com/57156267/153323724-12bf2554-1e8c-4a89-b92c-bdd92c1f6bcf.png)

**Trends and **Recommendations****
We had 747 tickets that required support attention. Here is the summary of the common areas of questions - please note we take out the Expenses and Onboarding topics as these are addressed separately and would make a large portion of the questions we handle.

![capture](https://user-images.githubusercontent.com/57156267/153323811-5ee6c009-7587-4093-bcff-f524a7877aa8.png)

Below are some notes on these trends:

**Virtual cards**

With the migration of VC from Privacy to Stripe finalized during the month of January, it is not surprising this category is still in the lead with the most common issues raised. This is both related to our communications to the collectives and with new questions received. 

We do still lack a clear policy on the limits. [After reviewing again the limits,](https://opencollective.slack.com/archives/C02PTHM21M3/p1642777280000200) it seems like the decision is to keep these at a similar level as before for security purposes and to allow us better monitoring of the spending we allow for, it looks like we are in a better defined position this month. 

One thing we still need to keep control of is ensuring that the balance available on each of the fiscal hosts Stripe balance is sufficient to cover charges. Currently, @natehn and @alinamanko review the balances periodically and topping these up. 

**Cash Assistance**

Nothing new to report in this space. The option for using cash assistance is still one a few of our mutual aid groups utilize and we still receive new applications to join in, though the number of those is fairly small. 

With each payment run, there are at least a handful of expenses submitted using this policy. 

**Lost**

We still consistently receive a relatively large number of tickets when users are looking to contact a specific initiative/project. There is a drop from 33 tickets to 22 from December to January though which is a good sign, but this is still an ongoing trend. 

**Bank transfers/Contributions**

The notifications coming through on new transfers coming through is a good thing, especially as it is an indication of larger contributions rolling through.

**Tax**

With EOY we did get a few questions coming through after we posted an update on 1099’s for 2021 and additional related questions coming through. 

**Independent Collective**

We do receive quite a few questions from independent collectives. As we do not have a great way to support these folks around the visibility of data from the ops crew, these tickets often end up with @znarf and[ we need to figure out a better way to address these questions. ](https://opencollective.slack.com/archives/GFH4N961L/p1643361526399089)

**GitHub Sponsors**

There are a few things on this front worth mentioning, both related to tickets raised and also general practices that the wider team should be aware of:

- New collectives are claimed without going through the standard route of an application review and approval, with us ending with quite a few collectives with a single admin, which is a situation we try to avoid. [Here is one example.](https://opencollective.freshdesk.com/a/tickets/58667) We have [an ongoing conversation](https://opencollective.slack.com/archives/GRGHEG4GP/p1643080909001000) with GitHub on this.
- Payouts sent to OCF bank account still include money for collectives hosted under OSC. 
- Some questionable projects coming through. [This is one ](https://opencollective.freshdesk.com/a/tickets/51830)where fraud was reported and another recent one which raises a lot of questions as well. 

**Expenses and Onboarding**

It seems like it would make sense to aggregate these categories into a separate section to look at some of the trends we can witness. Below is a more detailed description. 

**Expenses**

Common issues during January and other topics worth noting and weren’t flagged last month:

- In some instances where we have to process a manual payment through PayPal when the expense claimed is equal to the collective balance [there is a restriction in sending money in some instances when dealing with OSC account. ](https://opencollective.slack.com/archives/GDTJY7S48/p1644372385175149)Ember [suggested to get this issue addressed on the platform end](https://opencollective.slack.com/archives/GDTJY7S48/p1643674323119409?thread_ts=1639438189.019100&cid=GDTJY7S48) to reduce this manual handling which will help a lot. 
- On the front of payments to India it seems[ like we need to fix the API issue ](https://opencollective.slack.com/archives/GDTJY7S48/p1643817216237499)on the platform end to ensure users can’t go with the option of selecting a local bank in India when submitting a claim as this is possible to make a mistake when processing payments. 

**Onboarding**

There is a 38%  decrease in the number of new initiatives joining OSC and a 18% decrease for OCF. Here is how it was distributed:

We approved 47 new applications for OCF in January compared with 58 in December.

For OSC -  80 new collectives were approved this month compared to 130 in December. 

**Little celebrations:**

- Really great to have now access to Rooted Actions on the user menu and to be able to address some of the relatively common issues like changing the profile of contribution made from individual to organization and merge of accounts where needed
- The option to edit the pending order amount is super useful when processing incoming contributions
- The option of assigning manual contributions to a specific tiers is very useful!
- Also utilized the option of inviting an organization to submit an expense recently and it is fantastic. 

Yay team - support life seems a little easier now :)

**Comment by alanna** [comment]
@kewitz are you across this one:

> On the front of payments to India it seems[ like we need to fix the API issue ](https://opencollective.slack.com/archives/GDTJY7S48/p1643817216237499)on the platform end to ensure users can’t go with the option of selecting a local bank in India when submitting a claim as this is possible to make a mistake when processing payments.

> Really great to have now access to Rooted Actions on the user menu

So glad this is working. Let's keep our eye out for more repetitive tasks we might want to ask to be added to the root admin menu.

I love having a celebrations section in here! We really have made some progress. Big thanks to @opencollective/developers for all these improvements.
