### ISSUE TITLE
Mandatory fields not marked when inviting organization to submit an expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5222]
When inviting an expense it says mandatory fields are marked * and some are indeed mandatory, but they are not marked.
![Screen Shot 2022-02-11 at 2 45 36 PM](https://user-images.githubusercontent.com/5498878/153525733-2e11e763-2f48-4629-9faf-cd80037e9aa1.png)

**Comment by Betree** [comment]
This is strongly related to https://github.com/opencollective/opencollective/issues/5020. Both issues should be tackled at the same time, rather sooner than later - there's a real impact on the UX and the fix would be super simple.

**Comment by kewitz** [comment]
Since you're creating a draft for someone else to finish, there are no required fields when inviting someone else to submit an expense. The requirement is on the side of the invitee.

**Comment by alanna** [comment]
Oh then we should remove the text about mandatory fields from the invite view

**Comment by alanna** [comment]
But how can you invite an expense without entering the email at least??
