### ISSUE TITLE
collective-page Profile Page ordering "drag&drop" glitches/freezes/breaks

### ISSUE THREAD

**Issue by cybergrunge-ops** [opencollective/opencollective#5228]
OS: linux (debian) 
Browser: firefox 91.5.0esr 
Not a Duplicate Issue: i searched by keyword "drag" to no relevant results

the interface for collective page, to change the order things appear on our page, **freezes up completely** 50% of the time when i drag things. it hangs so that i have to navigate away from the page and reload everything and try again. the other half of the time, **dragging responds in completely inane ways** (not going to the correct place at all, creating an outline of destination but not actually moving there....). this is an essential feature.

This is an issue not just with OC but the implementation of "drag" functionality across the board in browsers.... it is a useless novelty that doesn't actually provide any real functional benefit but more importantly **Drag / Drag&Drop is just NOT RELIABLE.**.. i recommend getting rid of it and use arrow buttons instead.... drag&drop also makes ui's inaccessible to folks who have poor motor skills, cant afford an expensive computer for a flawless browsing experience, etc....

solution: add arrows to move things up and down in order

**Comment by cybergrunge-ops** [comment]
video of this happening repeatedly:
https://youtu.be/9dKsL_Kc5TU

**Comment by Betree** [comment]
Thanks for documenting this issue. I personally can't reproduce, could you share your browser/OS?

Could have been introduced in:
- https://github.com/opencollective/opencollective-frontend/pull/7441
- https://github.com/opencollective/opencollective-frontend/pull/7448
- https://github.com/opencollective/opencollective-frontend/pull/7456

Ping @opencollective/design for the UX feedback.

**Comment by cybergrunge-ops** [comment]
> @cybergrunge-ops Thanks for documenting this issue. I personally can't reproduce, could you share your browser/OS?

i did :)

**Comment by Betree** [comment]
Also reported on https://opencollective.slack.com/archives/C1974QBNK/p1661259814715909 using the latest Firefox. I've tried again with Firefox/Fedora today and couldn't reproduce.

Having arrow buttons to move the sections up/down as suggested in the issue would provide a workaround and a way for people to use this component on mobile, I support the idea.

![failed-drop](https://user-images.githubusercontent.com/1556356/188111521-5f6f637a-db3c-42bb-b3e5-84570ecb3f7a.gif)

![image](https://user-images.githubusercontent.com/1556356/188111746-76e66c9a-e69e-4e9a-ad32-65f9a8f485a5.png)

**Comment by Betree** [comment]
I was actually able to reproduce by drag & dropping very quickly, investigating...

**Comment by Betree** [comment]
Fix incoming in https://github.com/opencollective/opencollective-frontend/pull/8158.
We'll follow up with alternative actions to drag & drop with https://github.com/opencollective/opencollective/issues/5930.
