### ISSUE TITLE
Tips text wrong on embedded contribution flow

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5231]
The tips description looks like this on Open Collective:
![Screen Shot 2022-02-15 at 2 44 30 PM](https://user-images.githubusercontent.com/5498878/153977305-b045a2a7-8cf9-477a-aa93-95b2695d689b.png)

But in an embedded contribution flow, it's showing this:
![Screen Shot 2022-02-15 at 2 44 37 PM](https://user-images.githubusercontent.com/5498878/153977323-e83939c0-c7b0-4df7-9d7f-02463dbdd20c.png)

**Comment by SudharakaP** [comment]
Do we agree that we should change this? If it's embedded, the contributor might not know the context and the line "This page is powered by Open Collective, ...." to me makes it absolutely clear. But let me know. 🤔 🙂

**Comment by Betree** [comment]
That was an intentional change from https://github.com/opencollective/opencollective/issues/4092. People have no clue about what Open Collective is in the embedded version of the contribution flow, we need to be more descriptive.

**Comment by alanna** [comment]
I really don't agree with this because it's bringing back some problems we talked about in #4268 specifically [this comment](https://github.com/opencollective/opencollective/issues/4268#issuecomment-841505481). We worked hard to get to the right messaging and we need to treat it carefully. 

If it needs to be different because of the lack of context on embedded contributions, it should read: 

> Powered by Open Collective, a platform to raise and spend money in full transparency. Tips from contributors like you help keep this service free for Collectives. Thanks for any support!
