### ISSUE TITLE
Clicking "Prev" in the expense form jumps at the start of the process

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5235]
**Describe the bug**
When creating/editing an expense, clicking "Prev" on the 3rd step (summary) brings you back to step 1 (payee info).

**Expected behavior**
When clicking "Prev" on step 3, you should get back to step 2.

**Comment by SudharakaP** [comment]
I was looking at this, but it seems that the summary step button is `Edit Expense`. 

![image](https://user-images.githubusercontent.com/12435965/156107519-5601e6e3-fe2a-4171-ba5d-5cdc69d75caa.png)

So to me it makes sense to go back to start as it lets the user edit the whole expense. Do you think we should rename the button to `Prev` and then let the user go back to previous step? 🤔

**Comment by Betree** [comment]
@SudharakaP We can ask @opencollective/design what the label/expected behavior should be.

From my point of view, the current label is ok but having a prev icon (:arrow_left:) I expect this to go to the previous step, not to go back at the beginning of the flow.

**Comment by aminakazi** [comment]
I agree with @Betree
> I expect this to go to the previous step, not to go back at the beginning of the flow.

We designed the button with this flow in mind where we take the user to the previous step, not the first step. This is to be followed everywhere (expenses, contributions etc) unless specifically mentioned otherwise.
