### ISSUE TITLE
Apply the latest design to the Amount/currency picker

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5236]
Related to #5146 
Design: https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/?node-id=16006%3A280466

We initially created the currency picker with a minimalist approach (try it out [here](https://styleguide.opencollective.com/?path=/story/design-system-styledinputamount--with-currency-picker)). There's now a design for this, we should therefore update the component to match it.

- [x] Add flags
- [x] Add currency full name (should be internationalized)

![image](https://user-images.githubusercontent.com/1556356/154241082-240e05b0-d6e6-4747-a20b-8feea99977f2.png)

**Comment by SudharakaP** [comment]
If no objections, I'll be taking this. 🙂

**Comment by Betree** [comment]
@SudharakaP Sync up with @aminakazi, the design team might have an update for this

**Comment by SudharakaP** [comment]
As [disccused](https://opencollective.slack.com/archives/C0YFZ3MHP/p1645796881702649) with @aminakazi the latest design for this is https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=16008%3A280749.
