### ISSUE TITLE
Review LEM Collective, no host assigned

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#525]
Mail from Noguchi:

> Hi, 
> 
> I'm trying to contribute to the project called lem.
> But I cannot pay any money.
> 
> 
> The webpage says:
> This collective doesn't have a host that can receive money on their behalf
> 
> How could I solve this issue?
> 
> I'd appreciate your help.

This is the Collective's link:
https://opencollective.com/lem

**Comment by asood123** [comment]
done
