### ISSUE TITLE
Hiding transaction data on archived Collectives

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5256]
We've got a situation right now where there's a dispute between people involved in a Collective that's now archived. Someone who was not a Collective admin is reaching out to us as fiscal host wanting the historical transaction data for the Collective, which they can't see because it's archived, but we can as Host admins. 

Why is transaction data hidden for archived Collectives? Isn't this against our value of transparency? It creates a weird power dynamic where the Collective admin can't be held accountable by expense payees retroactively because of lack of access to the data.

**Comment by znarf** [comment]
What is the Collective? I confirm we don't want this, it's against transparency, so it's a bug.

**Comment by Betree** [comment]
That can happen with funds and projects because they're allowed to hide their budgets. But @znarf is right, if it's a collective then we have a bug.

**Comment by znarf** [comment]
After private discussion, It was indeed a Fund.
