### ISSUE TITLE
Update sequelize to 6.17

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5257]
In our [API](https://github.com/opencollective/opencollective-api/) repository, we're using [Sequelize](https://www.cypress.io/) version 6.16.3.

The latest version is 6.17 but the update is currently blocked because of breaking changes (typescript).
https://github.com/opencollective/opencollective-api/pull/7206

We would like to upgrade to the latest version and make sure our test suite pass properly on GitHub actions.

**Comment by WikiRik** [comment]
As mentioned in https://github.com/opencollective/opencollective-api/pull/7206 this is due to the addition of @types/validator in the production dependencies of sequelize. I've made a PR that should solve these issues and allow sequelize to be updated.
