### ISSUE TITLE
API requests failing

### ISSUE THREAD

**Issue by zachleat** [opencollective/opencollective#5259]
Tried a few collectives:

* https://rest.opencollective.com/v2/11ty/orders/incoming?limit=1000&status=paid,active
* https://rest.opencollective.com/v2/astrodotbuild/orders/incoming?limit=1000&status=paid,active

As a side note https://api.opencollective.com/ seems missing too? Linked from https://github.com/opencollective/opencollective-api

**Comment by znarf** [comment]
Thank you for the report!

The REST queries you shared should be fixed now.

As for https://api.opencollective.com/, it's "normal", there is nothing at the root of the domain today. We should definitely put something there.

**Comment by zachleat** [comment]
Thanks!
