### ISSUE TITLE
Review duplicate accounts on Buttercup Collective

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#526]
Mail from Sallar:

>  Hi,
> 
> Im the core contributor of Buttercup.
> Apparently you created an account for me “sallar” but I didnt know and I signed up myself and now I have another account with username “sallar1”.
> 
> I couldnt login with my main “sallar” account. Can you tell me how to delete the extra sallar1 and login using sallar account?
> 
> Thanks a lot
> Sallar.

Also check Perry's account:

> Hi,
> 
> I’m the co creator of buttercup desktop which was just added to your site. There’s been some issues with me logging in as the github profile that was created doesn’t function correctly.
> 
> I have my accounts “perry” and “perry-mitchell”, but would just want to use perry going forward. Buttercup is only attached to the latter account so it would be great if you might:
> 
>  - attach buttercup desktop to “perry”
>  - delete the “Perry-mitchell” account
> 
> Best regards,
> 
> Perry

**Comment by piamancini** [comment]
done
