### ISSUE TITLE
Apply Host fees to cross-Host expenses income

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5260]
## User story 
As a Host admin, I need host fees to be applied to all income to my Collectives, regardless of source. Now that we're enabling expenses across Hosts, we need fees to be built in.

## Best solution for this problem
Normal host fees are applied to income via an expense payable to the Collective from another budget on Open Collective in a different host. Host fees should not apply to expenses between Collectives in the same host.

## MVP
Maybe some kind of list of all such transaction so the Host can manually debit the appropriate fees? I think it will be hard to build a 'cheap' version of this and we should just build the proper one.

  P2 low frequency, high impact

**Comment by alanna** [comment]
@znarf could you scope this? For the hosts I manage, I don't think we can allow cross-host expenses until this is in place because it's an end-run around fees. Someone could just set up an IC, add funds to it, submit an expense to it, and transfer money into a Collective fees-free.

**Comment by znarf** [comment]
We can start scoping this next week (Sprint 2 - Week 1 - Scoping week) if the project is prioritized for next sprint.

**Comment by znarf** [comment]
Done in https://github.com/opencollective/opencollective-api/pull/7290
