### ISSUE TITLE
Parent Collective name missing from child Collective URL

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5263]
I'm seeing URLs like: https://opencollective.com/collective/projects/foss-multilingual-computing

It should be: https://opencollective.com/di-grants/projects/foss-multilingual-computing

Unless this was an intentional change and there's some reason for it? I think it's much better to show the parent Collective name in the string.

**Comment by SudharakaP** [comment]
Thanks for reporting this. I think this is a regression introduced by our recent changes with regard to [adding parent collective slugs to the event and project urls](https://github.com/opencollective/opencollective/issues/4587). I'll take a look this week. 🤔
