### ISSUE TITLE
Send event balance to parent failing due to insufficient funds

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5264]
https://opencollective.com/opencollective/events/regional-retreats-jan-2021-91d34198

<img width="637" alt="Screen Shot 2022-02-27 at 12 56 51 PM" src="https://user-images.githubusercontent.com/5498878/155862782-3453ba84-a07b-4ef9-bff2-9fa05552ed37.png">

As this amount is system-generated and meant to be 100% of the Event balance, this shouldn't happen.

**Comment by znarf** [comment]
There is a $150.51 Expense being processed and the $6,393.97 balance seems ok.

<img width="1244" alt="Screenshot 2022-02-27 at 10 16 23" src="https://user-images.githubusercontent.com/806/155876287-6430914a-792c-4099-a5f0-31808366a7ef.png">

**Comment by alanna** [comment]
OK this was an edge case then
