### ISSUE TITLE
Virtual Card Receipt Upload Reminder and Card Freeze

### ISSUE THREAD

**Issue by emberwry** [opencollective/opencollective#5269]
User is Fiscal Host admin who can provide virtual cards to collectives. 

In OSC and OCF we have a policy that if someone doesn't upload the receipt for a virtual card expense after 30 days, their card will get suspended. That is a royal pain to do manually and would be much more efficiently done by a computer.

What it would need: 
- at least one additional automatic reminder to the admin who submitted the virtual card order to upload the receipt, with the link to the expense/how to do it and a reminder that their card will freeze if they don't do it by x date, say at day 14 and then at day 29
- on day 31, freeze the virtual card/s associated with the collective, with an email sent out to all collective admins about what's happening and why, with 
- unfreeze to be done manually by an ops person once they hear back from the collective and see that the upload is satisfactory (or it could also be automated, but probably good to get a human involved somewhere in here)

Thank you!

**Comment by piamancini** [comment]
we need to check if we have already moved all privacy cards to stripe and shut down privacy

**Comment by kewitz** [comment]
Specs
- [ ] Implement notification cron job for stale missing receipt expenses;
- [ ] Notify expenses about missing receipts after 15 and 29 days;
- [ ] Automatically pause Virtual Card after 31 days

**Comment by piamancini** [comment]
- [ ] Automatically pause Virtual Card after 31 days
- [ ] tweaks over notification emails 
- [ ] change the notification to clarify days remaining.

**Comment by BenJam** [comment]
- [ ] merge PRs
- [ ] update docs (explain pause/resume and how it works under the hood)
