### ISSUE TITLE
"Remind me" feature on events not working

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#527]
Feedback from REconomy members:

> I go to https://opencollective.com/reconomycop/events/community-wealth-building-models-on-both-sides-of-the-atlantic-781ev ... click on INTERESTED button, enter my email and hit REMIND ME button but nothing happens :-/

I tried the same, entered my email and clicked the green button "REMIND ME" and nothing happened.

**Comment by piamancini** [comment]
@asood123 were you looking into this?

**Comment by piamancini** [comment]
I just tried it and it works so closing.
