### ISSUE TITLE
Transparency debt

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5270]
I'm raising an issue about this in general because I see it as a pattern we should be aware of. We may need specific issues for different parts of it.

I have noticed multiple examples of what I'm calling "Transparency Debt" in our system, where through a series of changes or decisions we've strayed away from our commitment to transparency and things are getting hidden on the platform that shouldn't be.

## Hidden Budgets

Here's a [data query](https://opencollective-metabase.herokuapp.com/question/695-accounts-with-hidden-budget) showing profiles with hidden budgets.

When Funds were created, we did not yet have #3689 and decided to allow hiding budgets due to specific valid privacy requirements around expenses from some specific Funds. However, now that we have the ability to use pseudonyms on expenses, this is no longer necessary. I have discussed this with @piamancini and I will get in touch with the Funds who have hidden budgets and help them to transition.

@Betree has already turned off the ability for Funds to switch off their budgets going forward. We can take requests via support to hide budgets, but I think our policy should be not to do so and instead push users to use the pseudonym function if they're concerned about expense payee identities being public.

A side-effect of hiding budgets for Funds was that Projects, a feature originally developed for Funds, inherited this hiding ability, and now we have a bunch of Projects with hidden budgets. I think we should treat this as a bug, inform the users, and show the Project budgets.

## Host hiding Collectives

At the moment, [WWCODE](https://opencollective.com/wwcodeinc) is not displaying their hosted Collectives. This is possible because the "contributions" section can be hidden, and hosted Collectives show up within that section on Host pages. Personally I think that hosted Collectives should be its own section for a variety of reasons, but one way or another we should prevent hosts from hiding this information.

## User hiding expenses

Related to #5261 - while you can see a user's expenses on the Collective's expenses list, the user can hide them on their own profile. This makes it hard to see which Collectives a given user is getting paid from and to transparently understand their activities. We have aspirations to build #3749 to create a proper expenses page per user, and it's odd that this information can be hidden currently.

Are there any other examples of transparency debt we should know about?

**Comment by Betree** [comment]
The "hidden budget" part will be resolved in https://github.com/opencollective/opencollective-frontend/pull/7532 for new accounts (regardless of their types - projects, funds, etc.) as we're not letting them hide their budget sections anymore **unless** they're already hidden (which means the engineering team can still manually hide them if needed).

**Comment by znarf** [comment]
I think closing was a mistake with automation, reopening.

**Comment by Betree** [comment]
> I think closing was a mistake with automation, reopening.

It was, thanks for re-opening. I fixed the description in https://github.com/opencollective/opencollective-frontend/pull/7532

**Comment by alanna** [comment]
After discussing with team members, I sent a message to the admins of all Projects with hidden budgets that are *not* part of Funds, as we consider Collective Projects hiding budgets to be a bug. I've asked them to let me know in the next week if they object to their budgets being displayed.

**Comment by alanna** [comment]
Just thought of another transparency thing... in #4640 we decided to hide archived projects. This means the transactions of past Projects will not be visible, which is not good for transparency. 

Since the main purpose of hiding archived Projects was to prevent confusion by users about what's currently active, I wonder if we could create a little link to "see archived projects" which goes to a separate page, so if people are looking for a transparent history, it's findable, without making people think inactive Projects are still active.

**Comment by Betree** [comment]
> I wonder if we could create a little link to "see archived projects" which goes to a separate page, so if people are looking for a transparent history, it's findable, without making people think inactive Projects are still active.

@alanna That's already more or less the case. On the collective page, you have this:

![image](https://user-images.githubusercontent.com/1556356/156995948-22b8ddbe-0061-442f-b440-7b3ef0a6da16.png)

When clicked, the projects page has everything listed:

![image](https://user-images.githubusercontent.com/1556356/156996013-99676e02-0772-474d-a274-fdaa5ddef533.png)

**Comment by alanna** [comment]
I meant one more click, so on the /projects page there would be a "see archived projects" button. This is because Collectives who use Projects a lot told us having archived projects there was confusing.

**Comment by BenJam** [comment]
just chiming in to say that i am today writing to confirm that we won't mark contributions as incognito unless the request comes from the contributor themselves and that this is a policy decision that needs to be reflected somewhere alongside the decisions we're making in this thread. 

Perhaps this should feed into the ethical standards conversation that @natehn is leading on https://github.com/opencollective/opencollective/issues/4928

**Comment by natehn** [comment]
@BenJam I don't think that those sorts of policies would live in the community guidelines - more of a documentation thing, I think. But in general, yes, this is interconnected with the discussion of Privacy and Transparency we have in the drafted Community Guidelines

**Comment by alanna** [comment]
As mentioned above, we decided to treat hidden Project budgets *not* under Funds as a bug and un-hide them. I informed all the admins of such projects a week ago to let me know if they have any objections, and no one did. So I have raised [this FD ticket](https://opencollective.freshdesk.com/a/tickets/66540) to ask @znarf to do this.

Please note, there are a bunch of Projects with hidden budgets not on this list under the NumFOCUS host. I am in touch with them about that separately (they aren't against transparency they just have many questions about how to set stuff up).

**Comment by alanna** [comment]
Update:
* Projects not under Funds have been un-hidden.
* New Funds and Projects cannot hide budgets themselves (we will decide what to do if someone requests a hidden budget in the future, but at least we will know about it)

**Comment by alanna** [comment]
What's the rationale behind allowing Collectives to hide their admins (by hiding the team section in settings)? I think this is a big issue for transparency.
