### ISSUE TITLE
Multi-currency expenses: show all amounts in emails

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5272]
Part of https://github.com/opencollective/opencollective/issues/5146

In the "Expense paid" email content, and only for multi-currency expenses, we would like to show amounts in both currencies. Something like this:
![image](https://user-images.githubusercontent.com/1556356/156153339-a0c80a92-9dbe-4de5-9d35-4b0defd2c8a7.png)

> {expense.amount} ({transaction.amountInHostCurrency})

**Comment by scenaristeur** [comment]
Hi 
Sorry to ask, but
doesn't this issue be closed if https://github.com/opencollective/opencollective-api/pull/7755 is merged ?

**Comment by SudharakaP** [comment]
@scenaristeur : Indeed. Thanks for pointing it out. 😄
