### ISSUE TITLE
Event image/text not getting pulled through on social media

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5276]
This facebook post links to https://opencollective.com/tauiwi-tautoko/updates/new-10-week-programmes-in-christchurch-welll

<img width="495" alt="Screen Shot 2022-03-02 at 7 33 35 PM" src="https://user-images.githubusercontent.com/5498878/156308200-7ff87e5b-6c70-42bf-9ad7-7f9aeb5c9098.png">

It should be pulling through the Update title and first bit of text, and the Collective's image, not showing default Open Collective text and images.

**Comment by Betree** [comment]
Canonical URL broken in https://github.com/opencollective/opencollective-frontend/pull/7304, I'm pushing a fix in priority as this will be dereferencing all updates from Google.

![image](https://user-images.githubusercontent.com/1556356/156315770-eb5fb5e1-58c7-4f19-9479-496c9c371c08.png)

**Comment by Betree** [comment]
Fixed. Facebook is not pulling the collective image because it's too small (we should probably enforce a minimum size on our end) but the rest is there:

![image](https://user-images.githubusercontent.com/1556356/156326215-5e6bbf60-b275-4420-acc1-c52ee3d09fc3.png)
