### ISSUE TITLE
Delete Expense as an expense submitter

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#5281]
## Who is your user?
Expense submitter 

## What are they trying to achieve?
Delete an expense 

_When an expense is incorrect or not needed anymore, I want to delete the expense, so it disappears. 

## How are they currently doing this?
Making the expense $1

**Comment by Betree** [comment]
Is that not already possible? According to https://github.com/opencollective/opencollective-api/blob/6adfc8c96ecda7e6372d10b84a8ed30db91e561a/server/graphql/common/expenses.ts#L273, expense submitters can delete their expenses once they get rejected.

**Comment by Betree** [comment]
I can confirm that this is already possible from the expense page:
![image](https://user-images.githubusercontent.com/1556356/156525065-302793c0-2abc-44fa-9a67-1e3c78425edf.png)


However not supported in the expenses list, we should fix that:
![image](https://user-images.githubusercontent.com/1556356/156524992-60730b64-6594-4a0f-a60a-63ffc6ef722a.png)

**Comment by shannondwray** [comment]
Why only after it's been rejected?

**Comment by Betree** [comment]
@shannondwray I think the intent from @opencollective/design was to avoid the ["Christmas tree" issue](https://github.com/opencollective/opencollective/issues/2936) - having too many calls to action for an expense. In terms of process, I also think it's interesting to reject before you delete because:
- There's no notification for delete, it really is a SPAM thing. But there is a notification when rejecting. It's good to have the contributors know about the status of their expenses.
- I'd be afraid of admins deleting the expense rather than rejecting it if we had the two calls to action weighted similarly.

**Comment by alanna** [comment]
I think the missing piece here is allowing an expense submitter to delete an expense (which has not yet been approved) that they submitted in error, even if they are not an admin. Is that possible currently  @Betree ?

**Comment by Betree** [comment]
> I think the missing piece here is allowing an expense submitter to delete an expense (which has not yet been approved) that they submitted in error, even if they are not an admin. Is that possible currently @Betree ?

As shared in https://github.com/opencollective/opencollective/issues/5281#issuecomment-1057789777, this is already possible. The only condition is for the expense to be rejected first.

My feedback from https://github.com/opencollective/opencollective/issues/5281#issuecomment-1057792328 is also invalid (or outdated?), it is possible to delete an expense from the expense list:
![image](https://user-images.githubusercontent.com/1556356/160338557-8962aa32-fc65-4f86-9e36-e79bf89f4682.png)

Unless I'm missing something, I think this is either an `invalid` issue or a `design` one meant to review the process of deleting expenses.

**Comment by alanna** [comment]
Is this a dup of #5167 ?

> The only condition is for the expense to be rejected first.

Ah ok, I think there's UX issue here. Someone who is not a Collective admin will not think to click `reject` IMO.

**Comment by Betree** [comment]
@alanna Good find, I did not remember this one. https://github.com/opencollective/opencollective/issues/5167 would resolve this: if you're able to "reject" your own expense then you'll be able to delete it.
