### ISSUE TITLE
Query mismatch when reloading expense page

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5288]
Steps to reproduce:
- Submit an expense
- Click on Approve then Pay
- Wait one minute
- See the form change when data gets reloaded

*More details & screencast to be added*

**Comment by alanna** [comment]
@Betree is this still a problem?

**Comment by Betree** [comment]
Cannot reproduce, I believe this was resolved by https://github.com/opencollective/opencollective-frontend/pull/7875
