### ISSUE TITLE
Change slug for Apprentus

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#529]
From Marius Mail:

> (...)I made the collective "Apprentus" (my company) and donated $50/month to Kea, but the URL of that company is https://opencollective.com/apprentus1 , with "1" in the end. I guess that's because the "/apprentus" that I created before was deleted, but the slug still remained in use. Is it possible to rename the slug to be without the number?

**Comment by piamancini** [comment]
done!
