### ISSUE TITLE
New VAT/GST custom field for expenses

### ISSUE THREAD

**Issue by jfdh** [opencollective/opencollective#5290]
## User story 

As a host Admin, I wanna make sure that people only uses the invoice option to submit services with a legit tax status. In the EU, you need a company/tax number to get paid for a services you gave to a collective. 

As a host Admin, I need my accountant to be able to get these tax numbers in the csv export

## Best solution for this problem

Add a mandatory VAT/GST custom field (that some host can have, other not depending on the needs) after the user chose the invoice option.

  P1 high frequency, high impact

**Comment by Betree** [comment]
Custom fields are indeed an option, but I would advocate for implementing explicit support for VAT directly in the code - like what we do for contributions.

Related: https://github.com/opencollective/opencollective/issues/4532

**Comment by BenJam** [comment]
@jfdh shall we close this in favour of #4532?

**Comment by jfdh** [comment]
Yes! Created this in a hurry but i am going to elaborate on #4532

**Comment by Betree** [comment]
Implemented with https://github.com/opencollective/opencollective/issues/4532
