### ISSUE TITLE
2FA: Add support for Yubikeys

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5294]
Requested in https://opencollective.freshdesk.com/a/tickets/65173

**Comment by Betree** [comment]
Actually Yubikey [seems](https://www.yubico.com/resources/glossary/oath-totp/) to support TOTP, so I believe we should already be compatible

**Comment by Betree** [comment]
Re-opening as native Yubikey support still provides a simpler user experience

**Comment by Betree** [comment]
Interesting lib for handling both the server & client sides: https://github.com/MasterKale/SimpleWebAuthn

**Comment by Betree** [comment]
As we're adopting Yubikeys in the team and trying to enforce 2FA on more hosts, there's a good potential for this issue to smoother the adoption (it's easier to press a button on your key than copy-paste a code). I would love to see this prioritized.

**Comment by Betree** [comment]
Just to note that I've seen multiple demos from the ops team where they lose a significant amount of time filling in 2FA codes since https://github.com/opencollective/opencollective/issues/5289. I'm not sure if they realize it yet, but this has the potential to save them quite some time.

**Comment by znarf** [comment]
> Just to note that I've seen multiple demos from the ops team where they lose a significant amount of time filling in 2FA codes

Similar to 2FA for Expenses, we should not keep asking for multiple actions in a small timeframe.

**Comment by Betree** [comment]
> Similar to 2FA for Expenses, we should not keep asking for multiple actions in a small timeframe.

@znarf We're not, there's currently a default timeframe of one hour for 2FA codes (I actually think we should increase that to 4, will open a PR to discuss it). But even with that, having to enter your 2FA one or two times a day = 30s x 2 x 365 = 6 hours spent / year / agent filling 2FA codes. Taping a Yubikey is much faster comparatively.

**Comment by znarf** [comment]
@Betree Thank you for the additional info, my bad. Maybe it's indeed the 1 hour policy that is too short.

**Comment by znarf** [comment]
Let's try to implement this soon!

**Comment by hdiniz** [comment]
YubiKey support can be implemented in two ways: [YubiKey OTP](https://developers.yubico.com/OTP/OTPs_Explained.html) and [WebAuthn](https://webauthn.io/).

### WebAuthn

- a web standard, supporting multiple device types, not limited YubiKeys
- registration and authentication flow requires initial server request to get a server challenge, challenge is signed by the 2FA device and submitted to the server for validation.
- we store the device clientID, public key and attestation data. Some details here might vary depending on device used, different attestation data?
- the frontend calls the browser web API to trigger the device. 

### YubiKey OTP

- works in a similar way to TOTP, the device generates a unique string which identifies the device and is signed, proving ownership.
- the [OTP is a 44 character string](https://developers.yubico.com/OTP/OTPs_Explained.html), 12 first characters is the fixed device id, the rest is unique signature.
- We store the device id to a User and we validate the token by calling [YubiCloud API](https://upgrade.yubico.com/getapikey/). The API is free to use and contains the factory secret of all YubiKeys.
- Getting the code on the frontend is demonstrated by this [demo](https://demo.yubico.com/otp/verify). The YubiKey works as a keyboard when pressed, we should present the user with instructions to tap their YubiKey and we get the code as keyboard events/as input form value.

Even though WebAuthn is more generic and future proof I suggest we first implement YubiKey OTP. Its flow is very simple and close to the existing TOTP provider that does not require many changes. Larger changes come from supporting an additional method in login/setting routes.

- [ ] Frontend: Extend TwoFactorAuthModal to present YubiKey OTP instructions to press device, capture input and resolve promise with `{ type: 'yubikey_otp', code: 'ccccc...' }`
- [ ] API: Add column `yubikeyDeviceId` to User model.
- [ ] API: Implement yubikey_otp provider, matching the provided device id with the User data and validating token with YubiCloud API.
- [ ] API: Add yubikey_otp to supported methods, refactor `userHasTwoFactorAuthEnabled` and `twoFactorMethodsSupportedByUser` to consider `User.yubikeyDeviceId`
- [ ] API: Refactor 2FA mutations to handle new method, allow two methods to coexist.
- [ ] Frontend: Add new method option under UserSecurity.
- [ ] API/Frontend: Refactor login with 2FA routes to use the 2FA lib.

**Comment by BenJam** [comment]
- [ ] waiting for team to review prs
- [ ] supporting folks to add their keys 
- [ ] looking at extending settings and login flow

**Comment by hdiniz** [comment]
Week 4
- [ ] Extending settings mutation to support multiple methods.
- [ ] Add yubikeys setting to OC team

**Comment by hdiniz** [comment]
Week 5

- [ ] Extending settings mutation to support multiple methods.

**Comment by BenJam** [comment]
- [ ] PR review awaiting
- [ ] release, docs 
- [ ] follow up chat about other types of 2FA and page for managing these settings

**Comment by hdiniz** [comment]
@BenJam this was deprecated in favor of https://github.com/opencollective/opencollective/issues/6796, which is available to all users and covers yubikeys
