### ISSUE TITLE
New profile page

### ISSUE THREAD

**Issue by erickrico** [OpenCollective/OpenCollective#53]

**Comment by xdamman** [comment]
You really put a lot of effort into this description! ;-)

I'd do something simple that we can quickly implement to have something. Then we can improve it over time. 

So for v1, we need to see (in that order)
- user avatar/logo (depending if it's a user or a company)
- collectives he/she is part of
- collectives he/she is supporting

The big question is what are we going to do with the namespace. Let's create a separate issue to discuss this.

**Comment by erickrico** [comment]
lol i typed it but i closed the window without commenting :/

**Comment by erickrico** [comment]
Should we add a way to store the user payment info from here (paypal/stripe) ?

![slack for ios upload-11](https://cloud.githubusercontent.com/assets/18429104/14871385/34f9e9e2-0ca7-11e6-9e14-c2cbe0b1ec4d.jpg)

**Comment by xdamman** [comment]
Not for v1. But yes it would be good to have from there a way to edit avatar, bio, website and connected accounts in v2. We will add payment methods in v3. Step by step.

As a side note, I wonder if we can come up with something creative with the rounded avatar and a network of collectives. A bit like the default background image we have on the collective page. Not important for now but just a thought.

**Comment by carlosascari** [comment]
@xdamman On your side note: First thing that popped into my mind was D3.js, heres is an example of what I mean http://bl.ocks.org/jose187/4733747, of course instead of dots they would be rounded avatars.

Here's a more advance example, it looks a lot like the default background image we have on the collective page. 

http://projects.flowingdata.com/tut/interactive_network_demo/

**Comment by xdamman** [comment]
There might be interesting things to do with that in the future. A collective is a network of people. There is no organizational chart, it's instead an organizational web. Food for thoughts!

**Comment by erickrico** [comment]
this is the public view, working on the editable one 

### Profile page with a lot of data
![profile page full](https://cloud.githubusercontent.com/assets/18429104/14904359/5daa87ae-0d6d-11e6-82f6-dba1c51f081d.png)

### Profile page with a lot of data

**Comment by erickrico** [comment]
This is the public view, working on the editable one

### Profile page with a lot of data ( for a regular user)
![profile page full](https://cloud.githubusercontent.com/assets/18429104/14904388/89a12eb2-0d6d-11e6-84bc-50104fccf5e8.png)


### Profile page with a lot of data (for organizations)
![profile page org](https://cloud.githubusercontent.com/assets/18429104/14904403/a65aeeb2-0d6d-11e6-8a3f-6bd299d32072.png)


### Profile page with little data
![profile page little data](https://cloud.githubusercontent.com/assets/18429104/14904413/b1446f92-0d6d-11e6-9a9a-5464f762fab0.png)

### Profile page with no data
![profile page no data at all](https://cloud.githubusercontent.com/assets/18429104/14904426/bbb92058-0d6d-11e6-9636-5892cc561fe8.png)

**Comment by piamancini** [comment]
i really like this!

P.
piamancini.com
t: @piamancini
s: piamancini
OpenCollective <https://opencollective.com>

**Comment by xdamman** [comment]
Ship it!

**Comment by carlosascari** [comment]
I'm leaving the branch here for quick reference
https://github.com/OpenCollective/opencollective-website/tree/profile

Its not ready the backend is not implemented yet, @asood123 is taking care of this

**Comment by asood123** [comment]
@xdamman picked it up from me
