### ISSUE TITLE
Problems with links to profile & Github

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#530]
in the form to create a new organisation, there was "http://" in front of the field for the website:

<img width="777" alt="screen shot 2017-10-18 at 14 04 38" src="https://user-images.githubusercontent.com/30665166/31729647-3e8ba814-b3f5-11e7-89c3-d4aaaae9b522.png">

However after saving, in the page to edit the collective this "http://" is not there:
<img width="784" alt="screen shot 2017-10-18 at 14 05 22" src="https://user-images.githubusercontent.com/30665166/31729653-44fcf86a-b3f5-11e7-9f91-0019837fcedc.png">

This caused all the links in my Github README and website to redirect to "https://opencollective.com/kea/sponsor/0/www.apprentus.com?utm_campaign=kea&utm_medium=github&utm_source=opencollective", not to "https://www.apprentus.com/". Links like this:
<img width="453" alt="screen shot 2017-10-18 at 14 05 57" src="https://user-images.githubusercontent.com/30665166/31729664-4c05d4f6-b3f5-11e7-843b-60337682acef.png">
After I manuallt added "https://" to the URL, the links still don't work. However the link to the Apprentus website on the Apprentus collective started to work:

<img width="300" alt="screen shot 2017-10-18 at 14 07 38" src="https://user-images.githubusercontent.com/30665166/31729780-a0613c52-b3f5-11e7-9ee4-3d07e0568213.png">

previously it also redirected to that URL.

**Comment by xdamman** [comment]
Thanks for reporting! Deploying a fix right now.

**Comment by xdamman** [comment]
Fix deployed
