### ISSUE TITLE
Character limit on github urls making it impossible to add some repo links 

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5302]
> I'm trying to setup some projects for some of our community GitHub repos and it appears that you have a character limit on GitHub URLs making it impossible to add some repo links: https://opencollective.com/rest-cache-plugin. This project should go to: https://github.com/strapi-community/strapi-plugin-rest-cache

Verified:

![Screenshot 2022-03-09 at 09 56 41](https://user-images.githubusercontent.com/158833/157418030-89be31bd-a2b4-4646-86c4-c780a6a6ab4a.png)

**Comment by znarf** [comment]
@SudharakaP could you have a look at this one today?

**Comment by derrickmehaffy** [comment]
I should have checked that an issue tracker existed before emailing.

Thanks for creating the issue!
