### ISSUE TITLE
Fix Supercollectives Collective cards

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#531]
Reported by Marius: 
> https://opencollective.com/opensource there's something up with I18n:
![screen shot 2017-10-18 at 11 20 03 am](https://user-images.githubusercontent.com/30665166/31730073-66aa601e-b3f6-11e7-85ee-ee2399fe132c.png)

**Comment by piamancini** [comment]
Also happening in opencollective.com/host-other 
https://opencollective.com/wwcode
etc...

**Comment by piamancini** [comment]
![screen shot 2017-10-18 at 2 03 03 pm](https://user-images.githubusercontent.com/3671070/31734568-1a056f26-b40d-11e7-92e2-6364d79587a7.png)
this somehow resolved itself on /opensource but I still see it on wwcode
![screen shot 2017-10-18 at 2 02 41 pm](https://user-images.githubusercontent.com/3671070/31734564-1740ebda-b40d-11e7-935e-f2eb78fa45da.png)
