### ISSUE TITLE
Organizations not appearing in 'our own host' selection

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5311]
This list should show the fiscal hosts the user is an admin of. It's not showing any. Reported by users and reproduced by me.

![Screen Shot 2022-03-11 at 2 07 32 PM](https://user-images.githubusercontent.com/5498878/157782299-1b521aa7-707a-43fc-a88b-d9c077bc6427.png)

Going via the 'start accepting contributions' button appears to be working, but the bug is affecting the same function through the settings workflow.

**Comment by Betree** [comment]
Investigating
