### ISSUE TITLE
Edit recurring contributions: only show profiles list if multiple entries

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5312]
Based on https://opencollective.slack.com/archives/C0140E7A7BN/p1646921864308219

When a user is not administrating anything, showing "Personal profile" is not helpful.

> It’s a bit surprising to see “Personal profile” when it’s alone. As a user, I don’t understand what it is.

![image](https://user-images.githubusercontent.com/1556356/157821240-99a8240e-b7b4-4233-aa9e-9be86729d891.png)

**Comment by Rozgony** [comment]
I can do this one.
