### ISSUE TITLE
drop down menu on profile displays a list of collective

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#532]
![screen shot 2017-10-18 at 12 34 30 pm](https://user-images.githubusercontent.com/3671070/31730716-c3b2f974-b400-11e7-8c06-c8ebc014a572.png)

**Comment by xdamman** [comment]
It's a feature, not a bug. It shows all the collective you are an admin or backer of.
For us it's a bit long but for most it's only 1-5 collectives. When you hover you see the current balance and number of pending expenses.

**Comment by piamancini** [comment]
roger that.
