### ISSUE TITLE
Policies are not inherited by projects

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5326]
Projects do not inherit their expense or contribution policies from their parent Collectives despite them not having their own policies section in `/settings'

## Replicate
Create a Collective
Add a contribution and/or expense policy
Create a project of the collective
Create an expense or contribution

## Expected
The expense or contribution policy should appear in the sidebar

## Seen
Nope

## Example

https://opencollective.com/conferences/projects/foss-backstage/expenses/new vs https://opencollective.com/conferences/expenses/new

**Comment by macovedj** [comment]
I believe I have a fix for the the expense policies in the PR above.  I also locally set up a test collective and a test project and set up a contribution policy.  I probably just missed it, but I couldn't find anywhere in the contribution process where the contribution policy was actually displayed to me.  I'm also including a screenshot of some copy that indicates that there are three contributors to the collective, even though I'm the only contributor that there has ever been, and I just made three contributions total.  Does it make sense to open a separate issue for this?
![Screen Shot 2022-04-16 at 2 50 35 PM](https://user-images.githubusercontent.com/20097860/163689456-20aefc9c-5829-4458-86c3-a635a71df2a7.png)
