### ISSUE TITLE
What to show for an empty (default) search page

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5328]
As part of #4295 we need to decide what should be included in the default (empty) search page. 

The search page is replacing the `/discover` page. As part of 'merging' these two pages we should look at what is missing between the current and proposed designs:

| Current | Proposed | 
| --- | --- |
| ![Screenshot 2022-03-16 at 11 18 42](https://user-images.githubusercontent.com/158833/158578564-c94c5d32-042c-4705-a064-d509cdd5c799.png) | ![](https://user-images.githubusercontent.com/49539954/158094753-a2bc0481-503a-48a2-a8c3-fbe02daf4133.png) |

 - we're missing the opportunity to talk about the kinds of causes that we support on the platform and to support those causes. 
 - we're missing a filter for 'most successful' and 'newest' 
 - we skew massively toward the 'finding Collectives to support' use case rather than the 'find a host for my collective', which I think is still fair (2/3 of the use cases in #4295 are based on this.

I think there are two parts to this problem:

- how do we raise up causes that can be supported
- what kinds of Collectives do we want to promote vs. the kind of Collectives that _need _ promotion

## Proposed solution

- I think we should leave the filters in @Memo-Es' design open if the search query is empty (and that we use a predefined list of tags to be 'featured' in the empty search
- I think we should order results by activity on an ASC basis (that is we show projects that are less active by default, the projects that could do with some help)

My reasoning for this is that as part of this work we will also be filtering out inactive/orphaned Collectives, if we get the balance of these two things right then the search results should be relevant.

**Comment by alanna** [comment]
I think this design is good, and would be greatly enhanced by a tag cloud showing common tags, so people can easily get a sense of what kind of Collectives are here, and narrow down to their interests. #5333 already addresses this.

**Comment by Memo-Es** [comment]
> we're missing a filter for 'most successful' and 'newest'
We don't need another filter for this, we should use the sorting feature @BenJam

**Comment by kaylarep** [comment]
@Memo-Es i like this structuring idea.

> P.D. Regarding the sort by the amount received or amount contributed, how are we accounting for displaying profiles with different currencies?

hm really good question... I'm not really sure. My thought would be that the 'amount received' option would only show up when 1 currency is selected, (and then we need to add another drop-down for 'Currency')

but this sounds not great to me. curious what others think.

**Comment by alanna** [comment]
We really need a way to convert currencies in our data. I always run into
this with the leaderboard data. Maybe the devs have a way to handle it,
like a currency conversion figure list we can reference that's updated
regularly. If it could be in our database somehow it works make all kinds
of queries easier.

**Comment by Betree** [comment]
@alanna We do have something like that in the DB. I don't want to expend too much on this issue, I've shared more in https://opencollective.slack.com/archives/C026UR48V16/p1647854741674219
