### ISSUE TITLE
Add Tag Cloud to Search Page

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5333]
Related discussions; https://github.com/opencollective/opencollective/issues/4295 and https://github.com/opencollective/opencollective/issues/5327

Users need the ability to search collectives by the frequently used tags. The design is given at, https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab?node-id=14316%3A188548

![image](https://user-images.githubusercontent.com/12435965/158698617-48e63539-926f-4408-a6ec-cd8b4c1afe13.png)

Since the frequently used tags are changing with time, I am suggesting that we have a cron job to calculate the tag frequencies daily and store this in db. 

- ~[ ] Add a cron job to update tag frequencies daily and store this in the db.~
- [x] Show the most frequently occurring tags in the search page (suggest showing the first 10 tags). 
- [x] Add support to calculate the tag frequencies in API (create a new GraphQL v2 query to get tag stats; using the `TagStats` object).

**Comment by SudharakaP** [comment]
@znarf: My initial thinking is that we have a daily cron job and we store the values in a new table, `TagFrequencies` (with columns `tag` and `frequency`) but I feel if there's a better way of handling this. Let me know if you have any suggestions. 🤔

**Comment by Betree** [comment]
@SudharakaP Is the computation really that intensive that we'd need to cache the results in a dedicated table? For reference the `Account.expensesTags` field computes something similar dynamically (even though it's just one account).

The following query replies in less than 200ms in prod:

```sql
SELECT UNNEST(tags) AS id, UNNEST(tags) AS tag, COUNT(id)
FROM "Collectives"
WHERE "deletedAt" IS NULL
GROUP BY UNNEST(tags)
ORDER BY count DESC
```

**Comment by Betree** [comment]
Also from that query, it seems that we may want to ignore some tags from this list (at least `user`?)

<details>

| tag                    | count | 
|------------------------|-------| 
| user                   | 7540  | 
| community              | 3822  | 
| open source            | 3460  | 
| opensource             | 1419  | 
| other                  | 978   | 
| association            | 656   | 
| covid-19               | 641   | 
| javascript             | 541   | 
| movement               | 422   | 
| meetup                 | 396   | 
| coop                   | 312   | 
| react                  | 264   | 
| php                    | 234   | 
| python                 | 209   | 
| nodejs                 | 174   | 
| studentclub            | 166   | 
| web                    | 151   | 
| covid                  | 148   | 
| typescript             | 145   | 
| software               | 136   | 
| education              | 134   | 
| C-corp                 | 131   | 
| linux                  | 130   | 
| hacktoberfest          | 127   | 
| pledged                | 117   | 
| css                    | 115   | 
| java                   | 115   | 
| vue                    | 106   | 
| android                | 104   | 
| open-source            | 103   | 
| technology             | 103   | 
| climate                | 100   | 
| mutual aid             | 97    | 
| docker                 | 95    | 
| developer              | 93    | 
| Tech meetups           | 91    | 
| diversity in tech      | 90    | 
| 501c3                  | 90    | 
| neighborhood           | 89    | 
| design                 | 87    | 
| framework              | 86    | 
| angular                | 85    | 
| default                | 84    | 
| api                    | 82    | 
| blockchain             | 81    | 
| nonprofit              | 81    | 
| wwcode                 | 81    | 
| security               | 80    | 
| ruby                   | 77    | 
| golang                 | 76    | 
| music                  | 73    | 
| collective             | 73    | 
| laravel                | 72    | 
| html                   | 70    | 
| art                    | 70    | 
| ios                    | 69    | 
| europe                 | 65    | 
| politicalparty         | 65    | 
| development            | 64    | 
| github                 | 63    | 
|                        | 63    | 
| rust                   | 63    | 
| #brusselstogether      | 63    | 
| pta                    | 62    | 
| go                     | 60    | 
| js                     | 59    | 
| game                   | 59    | 
| web development        | 58    | 
| frontend               | 58    | 
| programming            | 57    | 
| wordpress              | 57    | 
| vuejs                  | 56    | 
| privacy                | 55    | 
| cms                    | 55    | 
| host                   | 54    | 
| crypto                 | 53    | 
| drupal                 | 52    | 
| reactjs                | 52    | 
| devops                 | 51    | 
| graphql                | 51    | 
| node                   | 50    | 
| ai                     | 50    | 
| ui                     | 49    | 
| lobbying               | 49    | 
| event                  | 47    | 
| website                | 47    | 
| asbl                   | 47    | 
| smartcity              | 46    | 
| tech                   | 46    | 
| windows                | 46    | 
| electron               | 45    | 
| swift                  | 45    | 
| node.js                | 44    | 
| science                | 44    | 
| cryptocurrency         | 44    | 
| emccFR                 | 43    | 
| free                   | 43    | 
| brussels               | 43    | 
| react-native           | 43    | 
| machine learning       | 40    | 
| discord                | 40    | 
| cooperative            | 39    | 
| macos                  | 39    | 
| seo                    | 38    | 
| dotnet                 | 38    | 
| cloud                  | 37    | 
| free software          | 37    | 
| diversity              | 37    | 
| software development   | 37    | 
| web-development        | 37    | 
| foss                   | 36    | 
| app                    | 36    | 
| sustainability         | 36    | 
| data                   | 35    | 
| lobby                  | 35    | 
| server                 | 35    | 
| mongodb                | 34    | 
| database               | 34    | 
| computer-programming   | 34    | 
| health                 | 34    | 
| html5                  | 34    | 
| cli                    | 34    | 
| digital                | 33    | 
| library                | 33    | 
| marketing              | 33    | 
| research               | 33    | 
| games                  | 32    | 
| ethereum               | 32    | 
| activism               | 32    | 
| brusselstogether       | 32    | 
| softwaredev            | 32    | 
| webpack                | 32    | 
| testing                | 32    | 
| aws                    | 31    | 
| #fearlesscity          | 31    | 
| fearless city          | 31    | 
| git                    | 31    | 
| jquery                 | 31    | 
| food                   | 31    | 
| mobile                 | 31    | 
| paris                  | 31    | 
| mysql                  | 31    | 
| vzw                    | 31    | 
| environment            | 31    | 
| minecraft              | 31    | 
| non-profit             | 30    | 
| redux                  | 30    | 
| kotlin                 | 30    | 
| coding                 | 29    | 
| Open Source            | 29    | 
| coronavirus            | 29    | 
| bootstrap              | 29    | 
| climate change         | 29    | 
| gaming                 | 28    | 
| bot                    | 28    | 
| backend                | 28    | 
| c                      | 28    | 
| web design             | 28    | 
| opencollectiveeu       | 28    | 
| media                  | 28    | 
| ux                     | 27    | 
| automation             | 27    | 
| p2p                    | 27    | 
| animation              | 27    | 
| hosting                | 27    | 
| oss                    | 27    | 
| serverless             | 27    | 
| solidarity             | 27    | 
| npm                    | 26    | 
| platform               | 26    | 
| django                 | 26    | 
| support                | 26    | 
| kubernetes             | 26    | 
| decentralized          | 26    | 
| charity                | 25    | 
| sql                    | 25    | 
| région                 | 25    | 
| startup                | 25    | 
| casino                 | 25    | 
| code                   | 24    | 
| performance            | 24    | 
| mobile app development | 24    | 
| blog                   | 24    | 
| bitcoin                | 24    | 
| cross-platform         | 24    | 
| JavaScript             | 24    | 
| programmer             | 24    | 
| permaculture           | 23    | 
| flutter                | 23    | 
| finance                | 23    | 
| iot                    | 23    | 
| c#                     | 23    | 
| rails                  | 23    | 
| Climate                | 23    | 
| open data              | 23    | 
| mastodon               | 22    | 
| csharp                 | 22    | 
| social                 | 22    | 
| internet               | 22    | 
| streaming              | 22    | 

</details>

**Comment by SudharakaP** [comment]
> @SudharakaP Is the computation really that intensive that we'd need to cache the results in a dedicated table? For reference the `Account.expensesTags` field computes something similar dynamically (even though it's just one account).

You are right, thinking on this further no need to cache results on dedicated table as the computation isn't intensive as I thought. Thanks for the ideas. 🤗

**Comment by SudharakaP** [comment]
> Also from that query, it seems that we may want to ignore some tags from this list (at least `user`?)

@Betree : I was thinking which tags we should igrnor and I think to start with we should ignore the following tags to start with. 

1) `community` and `user`
2) All one letter tags
3) Empty string tag (there's 63 occurrences of that)

WDYT? Did I miss anything? 🤔
