### ISSUE TITLE
Support Metrics Report February 2022

### ISSUE THREAD

**Issue by emberwry** [opencollective/opencollective#5336]
This report looks at the trends around support to help us better understand areas we need to improve and highlight key topics for the month. 

### Tickets received 

![image2](https://user-images.githubusercontent.com/85583416/158721808-c1e2837d-1d40-4d86-8a9e-bd317016a129.png)

The number of tickets received increased by about 8% from 2080 in January to 2252 in February. By removing blank tickets and expenses notifications where no action was required the trend remained roughly the same (6% increase) with 798 tickets compared to 747 in January. You can find the working files here. 

The tickets contribution across the teams was as shown below:

![image1](https://user-images.githubusercontent.com/85583416/158721799-09ae8808-eb82-40e8-83ad-3fc954d1db7a.png)

### Trends and Recommendations
We had 798 tickets that required support attention. Here is the summary of the common areas of questions - please note we take out the Expenses and Onboarding topics as these are addressed separately and would make a large portion of the questions we handle.

![image3](https://user-images.githubusercontent.com/85583416/158721816-a615fd76-c16e-4517-abf0-646aa6f38070.png)

Below are some notes on these trends:

### Virtual cards

With the switchover from Privacy to Stripe, some follow up with collectives was necessary for collectives with previous cards. We also get many inquiries for virtual cards from OCF and OSC, showing this remains a very popular feature.

### Tax

It being Tax Season in the US, inquiries related to taxes are high.

### Lost

We still consistently receive a relatively large number of tickets when users are looking to contact a specific initiative/project. There is roughly the same amount going from January to February, from 22 to 25. It’s likely this will continue, and an upside is that many of these inquiries do get resolved.

### HR

This task has been changing hands and deepening the offerings, which is an involved task, especially for OCF but also OSC.

### Independent Collective

Alanna has been helping Ember give ICs better direct support, with conversations about improved onboarding to forestall some of the sticky problems and confusion ICs can get into.

### Expenses and Onboarding

It seems like it would make sense to aggregate these categories into a separate section to look at some of the trends we can witness. Below is a more detailed description. 

### Expenses

Common issues during February and other topics worth noting and weren’t flagged last month:

- With the war in Ukraine taking place and the restrictions on payments to Russia we currently not able to process payments to Russia based contributors. The impact for February was still pretty small with PayPal only stopping their support to these payments during early March, but this is something major for us to flag. Mostly impacts OSC. 
- During March OCF started supporting 1k Project for their renewed mission of supporting Ukrainian families and this impacted the expenses process. We anticipate the tickets related to expenses for March to increase due to these changes. As of now we established an automated process (big shout to the engineering team for making it happen!) that allows us sending money to that part of the world. 

### Onboarding

There is a 11% decrease in the number of new initiatives joining OSC and a 23% increase for OCF. Here is how it was distributed:

We approved 58 new applications for OCF in February compared with 47 in January.

For OSC -  71 new collectives were approved this month compared to 80 in January.

**Comment by piamancini** [comment]
This is super helpful @emberwry - It'd be interesting to know for example for Tax or Virtual Cards what are the most common enquiries. This will be useful for finding solutions or showing the info to the users before it reaches support. 

Any specific ideas, please feel free to add them to the https://github.com/opencollective/opencollective/issues/5337

**Comment by alinamanko** [comment]
@piamancini for the question on tax - most of the tickets in February related to our follow up on some info missing for 1099 generation, folks contacting us to enquire why forms were not received (mostly related to the changes in the reporting requirements through PayPal where 1099s are received through them rather being sent by OSC). As for the virtual cards question, I think @emberwry would have a much better context than me

**Comment by emberwry** [comment]
hi, @piamancini ! virtual card tickets are most often virtual card requests for a new card or for an increase in budget, and then earlier this year (feb especially) involved back and forth around receipts needing to be uploaded.

**Comment by emberwry** [comment]
yeah! i'm pretty sure most of the virtual card tagged tickets are virtual
card requests. there was some chatter about the shiftover to Stripe and
uploading receipts as well, but none were recurring issues.
