### ISSUE TITLE
Redirect `/hosts` page to the New Search Page with Host filter Selected

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5339]
After we have, https://github.com/opencollective/opencollective/issues/2970, it makes sense to redirect the `/hosts` page to the new `search` page with the `Fiscal Hosts` filter selected by default. This makes the collective cards that are displayed consistent throughout the platform and also gives users more information, given that we have added more details to the collective cards in the `search` page. 

Reference Slack Comment: https://opencollective.slack.com/archives/C035S573ZD2/p1647575692431289

**Comment by SudharakaP** [comment]
This one was initially proposed by @Memo-Es in the slack thread above, but I am rethinking on this as the `/hosts` page also points the users to [`/become-a-host` page](https://opencollective.com/become-a-host) page and [how to become a fiscal host docs section](https://docs.opencollective.com/help/fiscal-hosts/become-a-fiscal-host). Thus my thinking is that we shouldn't remove this page and just point the users to the search. What I would suggest is rather show all fiscal hosts on this page (`/hosts` page) sorted by "activity" (once https://github.com/opencollective/opencollective/issues/5375 is done).

**Comment by Betree** [comment]
@Memo-Es Based on @SudharakaP's feedback above, do you think https://opencollective.com/search?isHost=true  in its current state is ready to replace https://opencollective.com/hosts?

I would personally advocate for keeping the `/hosts` URL, making it render the new search page but with the "type" filter removed. That way you can still search and filter by country/tags, but you can't get out of the hosts' list by accident.

![image](https://user-images.githubusercontent.com/1556356/164206266-e3e908b7-08e1-4be0-8754-d788b1ee3e08.png)

**Comment by SudharakaP** [comment]
> @Memo-Es Based on @SudharakaP's feedback above, do you think https://opencollective.com/search?isHost=true in its current state is ready to replace https://opencollective.com/hosts?
> 
> I would personally advocate for keeping the `/hosts` URL, making it render the new search page but with the "type" filter removed. That way you can still search and filter by country/tags, but you can't get out of the hosts' list by accident.

This makes perfect sense. What I would suggest is that we remove the `type` filter as Ben suggested and also display the line, 

>[Fiscal Hosts](https://staging.opencollective.com/fiscal-hosting) hold money on behalf of Collectives, taking care of accounting, taxes, invoices, etc. Some also provide extra services. [Find out more](https://docs.opencollective.com/help/fiscal-hosts/become-a-fiscal-host) about [becoming a Fiscal Host](https://staging.opencollective.com/become-a-host).

just like we do at, https://opencollective.com/hosts page in place of the `type` filter. Also we need to make sure that we add an exception to this page (through passing some props) to make sure that we override the behavior of the search bar. Currently when we search for a new term the search filters are reset as per, https://github.com/opencollective/opencollective/issues/5425

**Comment by Memo-Es** [comment]
@SudharakaP @Betree, I'm not a fan of creating a branched version of the search page, It's ok to keep the `/hosts` link, but IMO it should be a redirect of the search page with the hosts' filter active. Why hide the possibility of looking for other profiles using the same interface? So we have fewer pages, and we add to the learning experience of understanding the context of hosts/collectives/orgs/etc

**Comment by SudharakaP** [comment]
> @SudharakaP @Betree, I'm not a fan of creating a branched version of the search page, It's ok to keep the `/hosts` link, but IMO it should be a redirect of the search page with the hosts' filter active. Why hide the possibility of looking for other profiles using the same interface? So we have fewer pages, and we add to the learning experience of understanding the context of hosts/collectives/orgs/etc

@Memo-Es : Thanks for your suggestions. What do you think about the line, 

>[Fiscal Hosts](https://staging.opencollective.com/fiscal-hosting) hold money on behalf of Collectives, taking care of accounting, taxes, invoices, etc. Some also provide extra services. [Find out more](https://docs.opencollective.com/help/fiscal-hosts/become-a-fiscal-host) about [becoming a Fiscal Host](https://staging.opencollective.com/become-a-host).

Do you think we shouldn't bring that as well to this hosts page? Are you suggesting the exact same `search` page but with the `host` filter applied by default?

**Comment by Memo-Es** [comment]
Yes

**Comment by Memo-Es** [comment]
I'm against these type of patterns where there are duplicated components with slightly differences. Like the nav bar, if we follow down this path soon we'll end up having multiple search pages? Not a very good UX

**Comment by Betree** [comment]
> Why hide the possibility of looking for other profiles using the same interface?

@Memo-Es People usually end up on this page after clicking on the `Find a fiscal host` button from their settings. I understand the argument for consistency, but not taking into account the context of how users end up on this page and showing these filters can also create confusion (if I can filter by events after clicking "Find a fiscal host", does that mean I can be hosted by an event?).

But I realize we're taking the problem from the wrong end: we already have a page for collective admins to pick a host for their collective (see screenshot). We should make sure we link there rather than `/hosts` in the admin.

![image](https://user-images.githubusercontent.com/1556356/164440760-63003176-c381-4a88-896d-01a21a00dd32.png)

So @SudharakaP to clarify the specs with what has been mentioned above:
- Remove the existing `/hosts` page
- Redirect `/hosts` to `/search?isHost=true`
- In `components/edit-collective/sections/Host.js`, make sure the button to find a fiscal host redirects to `/:collective/accept-financial-contributions/host`
- Update all other links to `/search?isHost=true`

**Comment by Memo-Es** [comment]
@Betree I agree with the use case you describe, as you say, it should be solved by https://github.com/opencollective/opencollective/issues/4240
