### ISSUE TITLE
Tiers buttons with amount are not active

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#534]
See: https://opencollective.com/internetfreedomfestival The tiers with amounts are in grey the free ones are purple. 
Collective has a host (host-other) I checked and our stripe is connected. 
User wants to launch this week.

**Comment by xdamman** [comment]
It's because the collective hasn't been activated by the host.
Hover with the mouse on the button to get the explanation:
![](https://cl.ly/1D0W09193j2c/Screen%20Shot%202017-10-19%20at%2011.28.11%20AM.png)
