### ISSUE TITLE
OAuth: Manage authorized apps

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5344]
### User Story

As a user, after authorizing an external App to access my Open Collective account using oAuth, I need to be able to edit and revoke access.

### Roadmap

This seems a priority because it's relatively important for testing purpose. 

We could add a "Connected Apps" section  to manage those credentials in user settings.

### Examples with GitHub and Strava:

<img width="1306" alt="Screenshot 2022-03-21 at 13 17 18" src="https://user-images.githubusercontent.com/806/159259414-cf220f4e-c5c6-49e2-ae1b-e4ffbbaa93e8.png">

<img width="927" alt="Screenshot 2022-03-21 at 13 16 02" src="https://user-images.githubusercontent.com/806/159259425-400e57c8-d022-43c3-a8b4-c658a228ee55.png">

**Comment by Memo-Es** [comment]
## Design update

| Authorized apps (Personal)  | Authorized apps (Collective)  | Authorized apps (Mobile)  |
|---|---|---|
| ![oAuth](https://user-images.githubusercontent.com/49539954/169952994-7b2a97a9-23de-46f4-b2b0-8f1527edf8d2.png)  | ![oAuth](https://user-images.githubusercontent.com/49539954/169952953-f3964bb4-5987-469f-8dbb-72726b26f34b.png)  | ![oAuth-1](https://user-images.githubusercontent.com/49539954/169952989-647bcbee-8f2b-49c8-b190-e9689e866808.png)  |

@Betree @znarf 

🎨[ Figma file ready for production
](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=17119%3A214666)

**Comment by Betree** [comment]
@Memo-Es We don't yet have the info about when the authorization was last used. I'm replacing it by the app connection date:

![image](https://user-images.githubusercontent.com/1556356/169966740-b687d602-2c56-4e33-ae00-1db69d2f3f13.png)

**Comment by znarf** [comment]
@Betree good for now, that's a great security feature that we should implement at some point
