### ISSUE TITLE
OAuth: ability for developers to create Apps

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5345]
### User Story

As a developer, I want to be able to create an App and get back client id and client secret for it.

### Roadmap

To start testing early, we could bypass this and give credentials app developers directly.

In a second phase, we will expose GraphQL endpoints to create, update and delete such apps.

In a third phase, we will have the complete user interface, similar to screenshots from GitHub below.

- We could add a "Developer Settings" section in all accounts (Individual, Organization, Collective, Fund). 
- Only Individual would have the extra "Personal access tokens".
- We don't have the equivalent of "GitHub apps" featured below.

### GitHub example

<img width="1184" alt="Screenshot 2022-03-21 at 14 09 50" src="https://user-images.githubusercontent.com/806/159267839-d0c54707-9e68-455c-bac6-09b1466dd4df.png">

<img width="654" alt="Screenshot 2022-03-21 at 14 10 12" src="https://user-images.githubusercontent.com/806/159267837-f27596b1-4166-423d-a704-2ce6c1d461e5.png">

**Comment by Memo-Es** [comment]
## Design update

| For developers | Register app |
|----------------|--------------|
|  ![Register apps](https://user-images.githubusercontent.com/49539954/170181750-03ab8680-5aeb-4069-aa01-b3338ef081b7.png)   |   ![Register apps-1](https://user-images.githubusercontent.com/49539954/170181314-0db761b5-17ec-4f24-9742-e7d2c7493cd2.png)  |
|    ![Register apps-1](https://user-images.githubusercontent.com/49539954/170181746-24a62774-0ff3-4de5-b6a7-983c3cb8b276.png)    |   ![Register apps-3](https://user-images.githubusercontent.com/49539954/170181319-00158e35-a878-4c1f-b8b7-23d801de9e0a.png)    |

Question: Does the 'Edit' button make sense?

[🎨 Figma file reference](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=17150%3A214800)

cc @znarf @Betree

**Comment by Memo-Es** [comment]
## Design update

 - I added an 'App page' to go after registering and app and when you click on settings (Previously edit)

| For developers | Register app | App page |
|----------------|--------------|--------------|
|  ![Register apps](https://user-images.githubusercontent.com/49539954/170604011-a72bb15a-6933-41ef-b83a-580a9ec78f6b.png)  |  ![Register apps-1](https://user-images.githubusercontent.com/49539954/170604009-1ad39d95-0e8a-467d-929b-80dd650d3068.png)  |  ![App page](https://user-images.githubusercontent.com/49539954/170604004-984c87d5-efcb-4376-91f8-07d9ba503582.png)   |
|  ![Register apps](https://user-images.githubusercontent.com/49539954/170604089-7274b555-670c-4505-be48-15a30b63e818.png)     |   ![Register apps-1](https://user-images.githubusercontent.com/49539954/170604087-71a5f20a-b572-4f9f-bedc-bcc715ec1f1c.png)   |   ![App page](https://user-images.githubusercontent.com/49539954/170604084-4f611ab5-2549-4eb5-930b-1e9c4d511329.png)   |


@znarf Let's discuss this feedback in tomorrow's demo

**Comment by Betree** [comment]
@Memo-Es Can we add a design of this page for the empty state?

**Comment by Memo-Es** [comment]
Empty state done [here](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=17677%3A214252) 

@Betree @znarf

**Comment by Betree** [comment]
@Memo-Es On this view:

![image](https://user-images.githubusercontent.com/1556356/174035268-88036b04-33f0-440a-977d-c9f1a4b780a8.png)

- Can we get a view with the client's secret displayed? They have a fixed length, you can use this one as a reference: `269d831a66c8531d8823351e3320742778e3c071`

![image](https://user-images.githubusercontent.com/1556356/174035492-961803e1-648f-40b9-9e81-41704fc07a34.png)

- :ice_cream: It's quite common to have "Copy" icons next to these to quickly copy the value

**Comment by Memo-Es** [comment]
Updating the file today @Betree

**Comment by Betree** [comment]
Implemented in https://github.com/opencollective/opencollective-frontend/pull/7906 (but not public yet)

@Memo-Es any update on the above?

**Comment by znarf** [comment]
Done
