### ISSUE TITLE
OAuth: login screen to connect with Open Collective

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5346]
### User Story

As a user, from another app (i.e. Metagov) I want to connect my Open Collective account to allow the app perform actions on my behalf.

 - If I'm already Signed In on Open Collective, I should be presented the authorization process, review the permissions and allow the app to perform actions on my behalf.
 - If I'm not already Signed In on Open Collective, I should be prompted to Sign In first to complete the authorization.

After a successful authorization, I'm redirected to the external app website, which will complete the authorization process on their side.

### MVP

In a first phase:
- we will not present with granular permissions and give full access to the account

In a second phase:
- apps will be able to ask for specific permissions: EXPENSES_CREATE, EXPENSES_UPDATE

In a third phase:
- users will have to confirm which Collectives and Organizations they want to give access to the app

### Similar flow with GitHub

In this example, Open Collective -> GitHub, Metagov -> Vercel.

Sign In to Open Collective

<img width="440" alt="Screenshot 2022-03-21 at 17 48 29" src="https://user-images.githubusercontent.com/806/159320096-384244f9-723d-4787-842b-b8f0e30a3e9b.png">

Authorize

<img width="587" alt="Screenshot 2022-03-21 at 17 49 37" src="https://user-images.githubusercontent.com/806/159320062-7d81679c-738f-4440-9d88-02fee9c3b822.png">

**Comment by Betree** [comment]
To streamline the login flow, we may want https://github.com/opencollective/opencollective/issues/3842 or https://github.com/opencollective/opencollective/issues/1738

**Comment by Memo-Es** [comment]
## Design update
[Design proposal](https://www.loom.com/share/1f17091b4cdf4fad8b4c905b458376e7) for the flow to connect with a third party app using an Open Collective's account

| Continue with your email  | Email confirmation |  Sign-up form  | Your magic link is on its way  | Authorization step  |
|---|---|---|---|---|
| ![Continue with your email](https://user-images.githubusercontent.com/49539954/167176459-853a4f83-7e15-4de9-a0f2-8b255b368c55.png)  | ![Email confirmation](https://user-images.githubusercontent.com/49539954/167176460-5cc288ce-f0b3-47d8-9703-0ab0cd7b6568.png)  | ![Sign up form](https://user-images.githubusercontent.com/49539954/167176463-e9491db0-f3eb-47d8-a12e-7050c94e469a.png)  | ![Your magic link is on its way](https://user-images.githubusercontent.com/49539954/167176467-995653a3-df1d-4b90-901e-fb8390b23afb.png)  | ![Authorization](https://user-images.githubusercontent.com/49539954/167176458-b741b822-7dc9-4402-833f-7b0afc30cd0f.png)  |
|   |   |   |   | ![Authorization-1](https://user-images.githubusercontent.com/49539954/167176456-eb6333a9-ee7e-442c-bf6f-c91d44916a1a.png)  |


cc @znarf @Betree
