### ISSUE TITLE
Allow funds to see all expenses for all projects

### ISSUE THREAD

**Issue by RichardLitt** [opencollective/opencollective#5347]
[Di-grants](https://opencollective.com/di-grants) is a fund with several different projects in it. As the administrator, I want to be able to see all pending expenses in any of the projects in the fund, without having to click through each of the projects. Right now, as an admin, I can only see expenses to the fund itself, not to its projects. 

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by alanna** [comment]
Related to #4360

**Comment by shannondwray** [comment]
This has been achieved with the new dashboard
