### ISSUE TITLE
Fix Tiers for Preact

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#535]
See on slack 
one sponsor is missing (says 6 and only 5 show up)
I added three to the correct tier in the order table (bronze-sponsor) They show up in the box but the label in the card is still wrong. 
![screen shot 2017-10-18 at 1 25 22 pm](https://user-images.githubusercontent.com/3671070/31732889-00019dde-b408-11e7-8612-b5ca87946cc7.png)

**Comment by xdamman** [comment]
That's because you haven't updated the `TierId` in the `Members` table.

**Comment by piamancini** [comment]
hmm but I added 3 sponsors in one go, how did the number went up to 6 but shows 5? I treated the 3 in the same way.

**Comment by xdamman** [comment]
I haven't deployed the fix yet for the number of sponsors. Waiting for some tests to pass.

I was referring for the tier name not showing on the card. It's based on the `TierId` in the `Members` table.

**Comment by xdamman** [comment]
deployed

**Comment by piamancini** [comment]
members tiers updated.
