### ISSUE TITLE
Search page: wording 

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#5353]
## Best solution for this problem
Is it correct English to say 35 contributions to collectives? rather than 35 contributor to collectives 

<img width="250" alt="Screen Shot 2022-03-23 at 11 35 43 AM" src="https://user-images.githubusercontent.com/79115149/159587740-eb3f1a65-b689-4cc5-bd59-a876aa1cb787.png">

**Comment by SudharakaP** [comment]
These cards are being redesigned as per the Search Experience redesign project and the new design just has 35 Contributors. So I think that should take care of it. 🙂 

![image](https://user-images.githubusercontent.com/12435965/157935160-6257c288-cb85-466f-a98c-d52b59e5aa0f.png)

**Comment by shannondwray** [comment]
Looks beautiful, excited about this :)
