### ISSUE TITLE
Wise: Implement missing length limitation validations for required bank information

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#5358]
Wise added a couple of new properties to their required bank information endpoint and we should implement those on our side.
The fields we are missing are `minLength` and `maxLength`.

- [ ] Update our wise types
- [ ] Update our GraphQL resolvers and objects
- [ ] Query new information in the frontend
- [ ] Implement frontend validation for min and max length `components/expenses/PayoutBankInformationForm.js`

**Comment by Rinalusi44** [comment]
ralamsyah573@gmail.com

**Comment by Rinalusi44** [comment]
Bantau saya ingin kirim uang ke Indonesia

**Comment by kewitz** [comment]
Fixed on https://github.com/opencollective/opencollective-frontend/pull/8796
