### ISSUE TITLE
Wrong payment method on invited expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5359]
https://opencollective.com/foundation/expenses/68595

I invited the expense and added the payout method details, selecting bank account. But after submitting it says "payment method - other" instead of bank account.

![Screen Shot 2022-03-24 at 10 36 24 AM](https://user-images.githubusercontent.com/5498878/159800013-9067d192-4aa6-4b2c-8881-a005d98719c5.png)

**Comment by alanna** [comment]
@SudharakaP has this been confirmed to be a bug?

**Comment by alanna** [comment]
Ah ok, so if they confirm the bank account I put in, it will then change?

**Comment by SudharakaP** [comment]
> Ah ok, so if they confirm the bank account I put in, it will then change?

Yes it does. As soon as the invited user goes through the expense flow and submits the expense (as soon as it the expense changes from draft to pending state) then that information changes. But let us know if this behavior is not desirable. In my view it makes sense as the bank information you entered might be changing (or the payout method itself can change) depending on what he invited user inserts. 🤔

**Comment by alanna** [comment]
OK that makes sense. That's fine. If it could say "unconfirmed" instead of "other" that would be clearer (I raised this issue because at first I thought I actually selected the wrong payout method or it didn't save properly), but I am probably one of very few people who would even notice that.

**Comment by SudharakaP** [comment]
Thinking about this further I think we could show the payout method that the invitee specified in the draft expense. If the user changes it later we should change the payout method in the pending expense accordingly. This way we don't have any ambiguity. 

@Betree : I've made a fix for this such that we show the payout method even for draft expenses.
