### ISSUE TITLE
[DOCS] Multi-currency expenses

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5367]
## Context
We're introducing [multi-currency expenses](https://github.com/opencollective/opencollective/issues/5146), a way for expense submitters to specify their expenses currency and get paid for the exact amount they request, regardless of the exchange rate fluctuations.

## Is this change being released incrementally as a beta? What's the schedule?
It's currently enabled on `opencollective` (host) only, we'll be rolling out this feature incrementaly for other hosts before enabling it for everyone.

## Changes to be made
We need to update the relevant docs page to explain this new feature. The two videos below can safely be used on the public documentation pages if that's helpful.

### Fox expense submitters
Walkaround: https://www.loom.com/share/a6f4f8a0455343f3980002473811cf56

On https://docs.opencollective.com/help/expenses-and-getting-paid/submitting-expenses:
- Should explain which currencies are supported (depending on the payout method)
  - Wise: Collective currency or payout method currency, with the limitation of the currencies that are supported by Wise
  - PayPal: any currency supported by PayPal
  - Other: Any currency accepted by the host. Please contact the host admin if you're unsure about whether it will be accepted
- How do we get/compute our FX rates
  - We rely on the payout provider (Wise, PayPal) whenever possible
  - Otherwise we fallback on internal caching and third-party APIs, mostly https://fixer.io

### For host admins

Walkaround: https://www.loom.com/share/cb61d011072c40c78adeeb481bab5850

We may want to add some basic docs for host admins, but I'm not sure where it should live:

- There's a limitation currently in place to handle fluctuations in the exchange rate: when paying multi-currency expenses, you need to have at least 20% of the requested expense amount in your balance in order to pay it. Example:
  - Collective's currency is USD
  - Payee wants to be paid in EUR and submits an expense for €90 (~= $100)
  - The balance of the collective must be at least $120

**Comment by shannondwray** [comment]
Thank you so much for this ben! The videos are amazing and I have included the first one in the docs :) 

- Submitting Expenses updated - https://app.gitbook.com/o/-LWSZizNMEjL8_DrMNdF/s/-LWSZizTt4ZC1UNDV89f/expenses-and-getting-paid/submitting-expenses

https://wise.com/help/articles/2897238/which-currencies-can-i-add-keep-and-receive-in-my-wise-account - What currencies are accepted? the 21 you can add money with or the 50 that you can hold in your account? 

I'm going to hold fire on putting this in the host admin documentation until it is enabled for groups outside of Open collective. Might wait for the payment processing fees to be sorted :)

**Comment by BenJam** [comment]
draft 🔥 post at https://opencollective.com/opencollective/updates/submit-expenses-using-your-own-currency

**Comment by Betree** [comment]
Now enabled for OSC

**Comment by Betree** [comment]
@shannondwray added the docs to https://docs.opencollective.com/help/expenses-and-getting-paid/submitting-expenses#multi-currency-expenses. Are we ready to close this?

**Comment by shannondwray** [comment]
Would be good to get an answer to my question above about the currencies supported by wise? 

I'll also take out the OCF comment and add some information into the fiscal host section just before it goes live on the 8th of August

**Comment by Betree** [comment]
> Would be good to get an answer to my question above about the currencies supported by wise?
> 
> I'll also take out the OCF comment and add some information into the fiscal host section just before it goes live on the 8th of August

I think the 50 currencies? As long as it's one you can send money with, it should be supported. With the abovementioned limitation: `Wise: Collective currency or payout method currency, with the limitation of the currencies that are supported by Wise`

**Comment by Betree** [comment]
Also, an important thing to be documented: this feature is not available when the host currency differs from the collective currency.

**Comment by Betree** [comment]
Released in production

**Comment by Betree** [comment]
@shannondwray With your latest additions to the docs, I think we're ready to close this one.

**Comment by shannondwray** [comment]
Which fiscal hosts is this turned on for?

**Comment by Betree** [comment]
All fiscal hosts, the only limitation is https://github.com/opencollective/opencollective/issues/5367#issuecomment-1208205066
