### ISSUE TITLE
Define who should be the invoicee on generated invoices (host or collective)

### ISSUE THREAD

**Issue by leena4c** [opencollective/opencollective#5369]
When filing an expense, open collective automatically generates an invoice addressed to the host.
This only works for fiscal hosts that consider the collectives as projects of the host.
All for Climate is considering collectives as independent unincorporated partnerships. As such invoices need to be addressed to one of the members of the collective, not to the host.

Because of that; all those automatically generated invoices are not legal (and put us and the collectives at risk of misclassifying the relationship between a collective and the host). We run into this problem again and again, last one: https://opencollective.com/symbiosis-pdx/expenses/68316 

Maybe this bill to name + address could be defined in the settings of the collective.
E.g. 
Bill to:
Admin 1 legal name
Collective name
Admin 1 legal address

In the meantime, can you at least make this an option that host can opt in or out from?

Thank you.

**Comment by alanna** [comment]
Just to clarify @leena4c - this is in relation to invoice expenses, right? Does it also apply for receipts for contributions in the same way?

**Comment by Betree** [comment]
Most hosts need to have the bill directed to them, so this can only be an opt-in option.

On the PDF service, we could quickly hack that by introducing a `billedAccount` variable that would hold either the collective or the host depending on a new flag that we'd introduce in the host settings.

I assume that for events/projects the parent's info should be used.

We'll need https://github.com/opencollective/opencollective/issues/5369#issuecomment-1080040198 before we can kickoff the implementation.

**Comment by leena4c** [comment]
> Just to clarify @leena4c - this is in relation to invoice expenses, right? Does it also apply for receipts for contributions in the same way?

Yes invoice expenses, reimbursements, contributions. Actually all transactions should be with the collective, not A4C.
I have a template people can use, where I add the relationship, but at this moment asking people to change their invoice/expense with the correct information is a lot of emailing back and forth. (especially the US based collectives tell me, but there is already an invoice :-) - unfortunately not legal for us)

**Comment by Betree** [comment]
Merging this issue into https://github.com/opencollective/opencollective/issues/5369 as it's the same request. We're currently working on this.
