### ISSUE TITLE
Root admin action to convert individuals accounts to organizations

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5373]
## User story 
We have very frequent support [requests](https://opencollective.slack.com/archives/GSNDVCC4F/p1645825882267999) to convert user profiles into organizations. It's error-prone and time-consuming.

## Best solution for this problem
In the long term, probably let users do that themselves?

## MVP
A root action on https://opencollective.com/opencollective/root-actions with an account picker and a confirmation modal.

## Metrics 
- Number of requests treated
- Time saved on support

**Comment by Betree** [comment]
@znarf you have some experience on this topic, any feedback on the things we should be careful about, or the limitations that may prevent an individual account from being turned into an organization?

**Comment by alanna** [comment]
Closing in favor of #5771 as it has more detail
