### ISSUE TITLE
Add Sort Option to Search Page

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5375]
We need to add sorting option to the search page. It was decided that we'll use amounts that collectives/orgs received as the metric for "activity". 

- [x] Add sort by component to the search page as per the design given below
- [x] Change query within [`searchCollectivesInDB`](https://github.com/opencollective/opencollective-api/blob/b8b72e8ed45a02f9d50569308b71a279335b4bf3/server/lib/search.js#L100) to support sorting by creation date and activity (`totalAmountReceived`).

Figma Design: https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab?node-id=14316%3A192586

Related to: https://github.com/opencollective/opencollective/issues/5329

cc: @BenJam @znarf

**Comment by kaylarep** [comment]
sorry to be repetitive, but can we also have 'Sort by' -> Alphabetical?

**Comment by SudharakaP** [comment]
> sorry to be repetitive, but can we also have 'Sort by' -> Alphabetical?

@kaylarep : Sorry, I missed responding to this. Since the designs and prioritization of these issues for the current sprint is done the plan is to only add the "most recent", "least recent" and "activity" sorting. But I think we should discuss and prioritize this for the next sprint. I've added this to the [project board](https://github.com/opencollective/opencollective/projects/71) so that I don't forget this.

**Comment by kaylarep** [comment]
ok, thanks @SudharakaP ! 

is there any sort of user testing/feedback happening for this as well (after its pushed)?  I'm assuming we might be missing some other types things that could be useful, and think public feedback could be insightful.
