### ISSUE TITLE
Do not export `CollectiveType` from `collective-sections`

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5376]
In https://github.com/opencollective/opencollective-frontend/blob/5bab53a12749b6c640aea637510a1ca2b49d866f/lib/collective-sections.js#L407, we're exporting `CollectiveType`. It's wrong because:
- The same variable was already exported from `constants/collectives`
- We don't want most files to depend on `collective-sections`

Todo:
- [ ] Move the imports to use `constants/collectives` instead

**Comment by macovedj** [comment]
https://github.com/opencollective/opencollective-frontend/pull/7649
