### ISSUE TITLE
Use ISO date format everywhere 

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5386]
Would resolve https://github.com/opencollective/opencollective/issues/3646

# Problem

The displays and inputs for dates are confusing because different countries use different formats). When looking at `02/03/2022` you need to know whether your system uses the MM/DD/YYYY or DD/MM/YYYY format to give a correct interpretation.

# Solution

As proposed [on Slack](https://opencollective.slack.com/archives/C6JTTA4SK/p1644942511146929), all our dates should be displayed using ISO time format (`YYYY-MM-DD`). We also want this for all date inputs.

# Specs

- For displaying, we should ideally find a way to fix that at the `IntlProvider` level.
- For inputs, we may want to introduce dedicated `DateInput`/`DateTimeInput` components

**Comment by Relequestual** [comment]
I would pose ISO is not developer centric. ISO date is international.
You can always provide a way for users to change their localised display of dates.

**Comment by Betree** [comment]
We discussed this topic in multiple places and haven't reached a consensus on using ISO everywhere.

We however introduced a new standard way to display dates in https://github.com/opencollective/opencollective-frontend/pull/6939 that shows the full month as text, removing any ambiguity (e.g. `August 22, 2022`). This component also supports a "compact" version, which will display something like `Aug 22, 2022`.

![image](https://user-images.githubusercontent.com/1556356/193518890-a111ceef-f9fb-4b3a-a6ad-2e06079775eb.png)


This doesn't remove the ambiguity for inputs (e.g. in the period filter) even though they're using the browser locale so users input the same date format they do in most places, and the visual calendar helps to select the date. We'll propose more solutions for that in https://github.com/opencollective/opencollective/issues/6017.
