### ISSUE TITLE
Consolidate no-reply email addresses

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5387]
Most emails come from no-reply@opencollective.com, but some emails (e.g. thank you email) come from `no-reply@${collectiveName}.opencollective.com`. There's no clear value in doing so, and it makes it more complex to implement custom filters.

Related: https://github.com/opencollective/opencollective/issues/5351

**Comment by Betree** [comment]
@alanna I know you're a power-user of email filters, would think change impact you in any way?

**Comment by alanna** [comment]
I don't think we should consider email filters in designs. If the filters break we can fix them easily.

**Comment by Betree** [comment]
I'm gonna work on this in priority, most update emails from updates are currently bouncing. I suppose that's because they come from `nore-reply@{collective.slug}.opencollective.com`, which is an unknown domain, and since we introduced DMARC recently that might be blocked.
