### ISSUE TITLE
Expense type options for hosts

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5395]
It seems that Projects under [this Collective](https://opencollective.com/ehf-community) have Grants turned on. I did not turn them on (as the only active host admin for OCNZ) and I can't figure out what's happened. Is there something odd going on where Projects are getting grants turned on mistakenly?

**Comment by Betree** [comment]
The behavior hasn't changed, but the confusion probably comes from the fact that things work differently for OCF.
OCF has `settings.disableGrantsByDefault` turned to true. We introduced this flag in https://github.com/opencollective/opencollective-frontend/pull/7090 (https://github.com/opencollective/opencollective/issues/4741) after some feedback that grants should be turned off by default for them, while we wanted to preserve the existing behavior (grants turned on by default for funds and projects) for everyone else.

This [conversation](https://opencollective.slack.com/archives/G46PNRCGP/p1634282557190000?thread_ts=1634177934.180800&cid=G46PNRCGP) includes most of the context.

**Comment by alanna** [comment]
Oh.... This means I will need to manually go in and disable grants for every Project created in all the hosts I manage besides OCF. Otherwise we'll have to deal with expenses put through as grants that lack the required into to pay as reimbursement or invoices. Can you please disable grants for all Collectives and Projects under Protozoa, OCNZ, and Gift Collective, and set them to `settings.disableGrantsByDefault`?

I strongly think that `settings.disableGrantsByDefault` should be on for all hosts and only turned off by request. Otherwise every third party host and IC is going to have this problem. We have carefully designed the forms for reimbursements and expenses to capture the required info for payouts, and grants circumvent all of that.

@Betree

**Comment by Betree** [comment]
> This means I will need to manually go in and disable grants for every Project created in all the hosts I manage besides OCF

Yes, this is the behavior that has been implemented from the start. If that's not what we want anymore we should indeed change it to be opt-in.

cc @znarf @piamancini does it sounds ok to you?

**Comment by alanna** [comment]
It makes no sense to me why we'd have grants on for Projects by default, but not for Collectives. If that was an intentional design decision, I don't understand the reasoning.

**Comment by Betree** [comment]
Posted specs to resolve this in https://github.com/opencollective/opencollective/issues/5525
