### ISSUE TITLE
Include reference code in transaction details for bank transfer expenses

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5396]
This contribution was made via bank transfer and was assigned a unique reference code:
<img width="641" alt="Screen Shot 2022-04-06 at 7 31 23 PM" src="https://user-images.githubusercontent.com/5498878/161920378-008254b1-9ffd-494d-9207-076e9faf44c0.png">

It would be useful for accounting records to have this code shown in the transaction details, so it can be linked up to bank transaction records more easily, and the order can be searched for more easily on the host dashboard if you start from the transaction:
<img width="1066" alt="Screen Shot 2022-04-06 at 7 32 11 PM" src="https://user-images.githubusercontent.com/5498878/161920462-a27d687a-0bb1-4985-896d-a8f3bcda45fe.png">

**Comment by znarf** [comment]
Duplicate with https://github.com/opencollective/opencollective/issues/5499 ?

**Comment by alanna** [comment]
I'm not sure - are order IDs the same as the bank transfer reference code? If so then yes it's the same. If not, we need both because the reference code is what enables me to link it to bank ledger entries.

**Comment by Betree** [comment]
> I'm not sure - are order IDs the same as the bank transfer reference code? If so then yes it's the same. If not, we need both because the reference code is what enables me to link it to bank ledger entries.

@alanna Yes, they currently are the same thing
