### ISSUE TITLE
Redirect `/discover` page to `/search`

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5397]
Once the "activity" sort is done (https://github.com/opencollective/opencollective/issues/5375) and shown by default on the `/search` page I think we should redirect the `/discover` link in the nav bar to the `/search` page, completely deprecating the `/discover` page. 

- [x] Redirect `/discover` link to `/search` in nav-bar. 
- [x] Remove the `discover.js` and `DiscoverCollectiveCard.js` components.

**Comment by Betree** [comment]
Seems like a sub-item of https://github.com/opencollective/opencollective/issues/2970#issuecomment-1064840074, the last not done yet actually? Let's remember to close both once it's done

**Comment by SudharakaP** [comment]
> Seems like a sub-item of [#2970 (comment)](https://github.com/opencollective/opencollective/issues/2970#issuecomment-1064840074), the last not done yet actually? Let's remember to close both once it's done

Ops, you are right, this is indeed a sub item. The plan is to first merge all the PRs remaining (the country filter, the sort) and then we could re-direct the `/discover` page. Currently we show the discover page as is. 🙂
