### ISSUE TITLE
[Project] Revamp the sign in / join feature

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#5399]
## Overview

During the onboarding flow research calls, 2 out of 3 subjects had a problem with the sign-in step.

| Current  | Proposal  |
|---|---|
| - **Main issue:** Although it says 'Join Open Collective' the form is about signing in. The experience feels broken. | - **Proposal:** Have a single 'Continue with your email' field, so existing users can log-in using the magic link as always, and new users can join from there |
| <img width="684" alt="Screen Shot on 2022-04-06 at 00-02-06" src="https://user-images.githubusercontent.com/49539954/162120932-64739461-3a6f-445f-b252-b6ef5b43330f.png">  |  <img width="864" alt="Screen Shot on 2022-04-07 at 00-07-08" src="https://user-images.githubusercontent.com/49539954/162124293-1677dad3-e0f9-49ff-88ec-70acccbc69e9.png"> |

**Comment by Betree** [comment]
@Memo-Es While it complexifies a bit the process, differentiating sign-in/sign-up reduces the number of duplicated accounts created: if you have an account on Open Collective and get an error ("No account for this email") when trying to sign in, you'll quickly realize that (a) you made a typo in the email address or that (b) it is not the address you used to signup on OC.
If we go with the proposed design, we will end up with many accounts created by errors and duplicate accounts that the support team will then have to merge.

It would be great to find a middle group between the two approaches. For example, if the email doesn't exist yet, have another step after "Continue" saying something like:

 > `toto@email.com` is not registered yet on Open Collective. Would you like to register with this email?
> [Yes, sign me up!] [No, sign-in with a different email]

**Comment by Memo-Es** [comment]
> `toto@email.com` is not registered yet on Open Collective. Would you like to register with this email?
> [Yes, sign me up!] [No, use a different email]

Yes @Betree ! I like this suggestion. There are still a couple of UX fixes to make this work, but those should be solved during the project shaping stage

**Comment by Betree** [comment]
@Memo-Es did you consider https://github.com/opencollective/opencollective/issues/3842 along with this one? This would really help for https://github.com/opencollective/opencollective/issues/5346

**Comment by BenJam** [comment]
@Memo-Es' arranging a kickoff conversation for #4829 tomorrow, let's include a quick discussion on this too.

**Comment by SudharakaP** [comment]
My thinking is that for the MVP; 

- Alter the Join Open Collective page with the new design given above; https://github.com/opencollective/opencollective/issues/5399#issue-1195528181. 
  - When the user clicks on the `Continue` button if they already have an account, redirect them to the `Your Magic link is on its way` page. We keep this magic link page as it is since I believe we have everything we need there. 
  - If they don't have an account we show an interim page as Ben suggested above to ask the user to either register or go back and change their email. 
  - If they do consent to registering we show the `Create Personal Profile` page but remove the `Create Organization Profile` section. Probably we need to revamp the design a bit here to exclude the sections about organizations and also change the "Already have an account" at the bottom to let the user go back and change the email instead. 
![image](https://user-images.githubusercontent.com/12435965/165601961-d9ac442d-f3f5-4edf-8b11-8b9dc8bd33f9.png)

**Comment by Memo-Es** [comment]
Goals for Week 2:

 - Design proposal based on feedback

**Comment by kaylarep** [comment]
@Memo-Es can we add another footer link to those modules that says "What is Open Collective?" And links out to our docs/faq?

What do you think?

**Comment by BenJam** [comment]
W4

- [ ] listing points for sign in (confirm @Memo-Es draft) 
- [ ] wrap up feedback into notes here in this issue
- [ ] identify potential overlaps between this project and the oauth project
- [ ] begin implementing up to the magic link

**Comment by Memo-Es** [comment]
## Production-ready designs

The aim is to focus on creating a personal account first and then displaying the strongest alternatives to continue using the platform.

| Continue with your email  | Email confirmation |  Sign-up form  | Your magic link is on its way  | Authorization step  
|---|---|---|---|---|
| ![Continue with your email](https://user-images.githubusercontent.com/49539954/169434807-862bd4b5-8444-4624-adf4-1749e8641668.png)  | ![Email confirmation](https://user-images.githubusercontent.com/49539954/169434808-e3870622-f484-4d6c-92e0-be4a0182afcc.png)  | ![Sign up form](https://user-images.githubusercontent.com/49539954/169435089-91795a76-39bb-42f8-aa3b-a5f27ac2882f.png)  | ![Your magic link is on its way](https://user-images.githubusercontent.com/49539954/169434814-25e1a4b5-d968-4975-a990-5a7a8bb5b119.png)  | ![Personal account success alternative layout](https://user-images.githubusercontent.com/49539954/169435086-599d3de4-665e-4e5f-bbca-1e13f27d0315.png)  | 

**Implementation notes**
- We are removing the tabs to create a 'personal' vs 'organization' profile because we want users to create a personal account first, end that process with success, and display the difference between creating and an organization more clearly in a separate step.
- In the future, we should invest time in developing an improved profile structure; some of us think we are making a mistake using a synonym to describe two different things (Collective and organization). There was a proposal to switch to 'business profile,' but it's too early to shift that, rewrite documentation, etc. We will wait for a proper workshop to make that final call.

🎨 [Design file in figma](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=17003%3A234359)

@SudharakaP @Betree

**Comment by Betree** [comment]
@Memo-Es I can't find the mobile versions in Figma. Do we have something?

**Comment by BenJam** [comment]
- [ ] review design with @Memo-Es 
- [ ] update status here

**Comment by Memo-Es** [comment]
## Design update

I worked on a polished version of the sign in / sign up flow on the normal state and OAuth version, fixed spacing, margins, and elements sizing on desktop, tablet, and mobile (Please, review the whole thing again, as I made some changes along the way to guarantee consistency across variants.

 - Max width for desktop is fixed on 880 px
 - If the email already exists, we show [this message](https://d.pr/i/ptV8e8), instead of the organization accounttextbox
 - The design update for the OAuth sign in is done, I put both flows together

[🎨 Figma file reference here](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=17003%3A234359)

@SudharakaP @Betree @znarf

**Comment by znarf** [comment]
Still some PRs to finish and merge.

**Comment by BenJam** [comment]
I'm gonna skip doing a release post for this at the moment, can we link the PRs that still need merging here?

**Comment by SudharakaP** [comment]
> I'm gonna skip doing a release post for this at the moment, can we link the PRs that still need merging here?

Yes, we have three main PRs; 

https://github.com/opencollective/opencollective-frontend/pull/7832
https://github.com/opencollective/opencollective-api/pull/7592
https://github.com/opencollective/opencollective-frontend/pull/7834

**Comment by SudharakaP** [comment]
> ## Copywriting update
> 
> After scanning the design again for inconsistencies in our language, specifically in what term we use to 'enter' the platform, i.e., sign-up vs register vs create an account. I asked @natehn for some help bouncing around some ideas to find a better solution for consistency going forward. Here are the conclusions of our working session:
> 
>     * 'Sign-up' sounds generic in the sense that you don't know what exactly are you signing up for
> 
>     * 'Register' sounds bureaucratic and boring in general
> 
>     * 'Create an account' seems like the way to go because it describes precisely what you are doing, and since we are also enforcing the creation of a personal account with this flow before creating a Collective or an organization, it looks consistent with what you experience throughout the whole flow

> Here is the figma file as a reference: https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=17003%3A241253

This is handled at, https://github.com/opencollective/opencollective-frontend/pull/7907

**Comment by kaylarep** [comment]
added comments to the figma file @Memo-Es . looking great thanks!

**Comment by SudharakaP** [comment]
All the PRs related to this is merged and deployed. And thus I am closing this issue.
