### ISSUE TITLE
Change support contact references to help page instead of direct email

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5401]
We have a lovely new support page: https://opencollective.com/help

We want people to use this so they can see some helpful docs that might answer their question, and be guided to provide some more helpful info to support if they contact us.

We should update all the places where we tell people to email support@opencollective.com or info@opencollective.com to link to https://opencollective.com/help instead.

**Comment by Betree** [comment]
It won't cover everything, but I'm pushing a really small update in https://github.com/opencollective/opencollective-frontend/pull/7675 to update the default `I18nSupportLink`. It's a helper we use in most of our messages where we say `please contact <I18nSupportLink>support</I18nSupportLink>`.

With this PR, all these links will now open the `/help` page instead of the email client.

**Comment by Betree** [comment]
@alanna After some testing, I feel like many of these places should actually link to https://opencollective.com/contact. Basically, for all places where we have a message saying `Please contact support`, adding the additional step of `/help` adds one more step that arguably doesn't help.

Take the [pledged collective](https://opencollective.com/codecov) page for example. It seems to me that this email should be replaced by a link to https://opencollective.com/contact, not https://opencollective.com/help.

![image](https://user-images.githubusercontent.com/1556356/162204012-d27b3306-457a-4ceb-9d62-9e3a6fcd9be2.png)

**Comment by alanna** [comment]
OK that makes sense.

**Comment by shannondwray** [comment]
<img width="1361" alt="Screen Shot 2022-04-13 at 10 44 38 AM" src="https://user-images.githubusercontent.com/79115149/163066727-cb190e88-ea71-4e86-b978-1c026f2247db.png">

Heres a image of the footer, the little icon on the right the mail one goes to info@opencollective.com :)

**Comment by Betree** [comment]
https://github.com/opencollective/opencollective-frontend/pull/7675 will replace most references in the frontend. It however won't touch the the content of our emails, where we sometimes use a mailto (e.g https://github.com/opencollective/opencollective-api/blob/511f05ae5e835d37f67a08e846b9ffa52059a3ce/templates/emails/archived.collective.hbs#L15)
