### ISSUE TITLE
Legal name field when creating new user for added funds

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5407]
It would be useful to have the legal and display name fields on this form. I just had a case where I added funds under a desired display name, but the person's legal name is different, and we need to have that on record as part of host compliance around recording the identities of large donors.

<img width="460" alt="Screen Shot 2022-04-08 at 12 31 22 PM" src="https://user-images.githubusercontent.com/5498878/162340558-dedeb56c-3715-4e8b-b3c5-990c7e5b6486.png">

**Comment by BenJam** [comment]
QQ dos Open Collective Foundation need legal name for _every_ donation, or just above a certain amount? And do we not have that information from their W8/9?

**Comment by alanna** [comment]
W8/9s are for expenses, not contributions.

US nonprofits need to collect donor ID info for all donations over $5000. The way we manage this is to save the required info in the OC database. There are many cases where a) we must have the real donor name on file (privately) and b) the donor does not wish their legal name to be the one showing on the platform, and c) we are processing a donation through add funds. This is when having the legal name field here would help a lot.

**Comment by Betree** [comment]
On the project board, the description says "Maybe not a good idea. The popup is small and crowded."

Can we elaborate on this feedback? @znarf maybe?

**Comment by alanna** [comment]
I agree it's not the prettiest design to have lots of fields in a modal, but as this is only seen by Host admins, and Host admins care a lot more about compliance than aesthetics for backoffice tasks like this, I would still advocate for doing it.

**Comment by aminakazi** [comment]
Week 3 Tasks:
- [ ] Design the pop-up to fit 'legal name' field 
- [ ] Share a loom for feedback
- [ ] Share production-ready files to the Dev Team

**Comment by aminakazi** [comment]
The production-ready Figma files can be [found here](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=18528%3A184170)

Please note that this is the MVP solution. The @opencollective/design team will be tackling the ideal version for it in the upcoming sprints.
