### ISSUE TITLE
OC UK - Established date issue

### ISSUE THREAD

**Issue by Kilheure** [opencollective/opencollective#541]
Hi, 

Here is the first bug I notice on OC UK page. Established date is wrong, it is 2017 instead of 2018.
Not sure than an "established" date can be in the future.  Anyway for OC UK it is not correct. 

Thanks for looking at this log. 

***

URL: https://opencollective.com/uk
Logged in as: UC UK
Error message if any:
Expected result: Established in 2017
Browser: Chrome

Bonus point if you can add a screenshot :-)
![screen shot 2017-10-20 at 09 33 01](https://user-images.githubusercontent.com/31570464/31812074-b958aac6-b579-11e7-9716-095e5cdafaf2.png)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by piamancini** [comment]
this is old now
