### ISSUE TITLE
Virtual Cards Edits

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#5410]
## Context
Now that virtual cards have been functioning for a few months, and we've made the transition from using Privacy cards to using Stripe Virtual Cards, there are some things we've noted that need further attention.

I know there's A LOT to unpack here, but virtual cards are such a powerful feature/tool that we're offering, if we can optimize it's useage for host admins and assignees (collective admins), would be amazing <3 (also scaleable)

These are based on feedback from OC staff as fiscal host admins, and from users as collective admins. Issues have been gathered [here ](https://opencollective.slack.com/archives/C02PTHM21M3 )temporarily.

### Virtual Cards Settings (as a fiscal host admin)
- Virtual Card admin options are located in too many different places. As a host admin I am frequently clicking around to find 'Settings/Policy' vs 'Cards'.  This may require another redesign of the admin settings to streamline
    - Here: 
![image](https://user-images.githubusercontent.com/64920686/162343355-aa76a6c9-a0df-4f7c-b188-99a171b213f4.png)

    - There are virtual card options located in the 'Host Dashboard' as well as in 'Fiscal Host' Settings. (I still don't fully understand the difference between an 'Organization' and a 'Fiscal Host' and am often just clicking around till I find what I'm looking for. ) Even though I have edited our 'Virtual card application/policy' within the 'Virtual Card Settings' to ask that card requests are formatted in the correct way, I am still receiving virtual card requests that are not formatted correctly.  This is not intuitive, and as an admin with many other tasks, it is a burden to remember where things are located, instead of being able to find them in a straightforward manner. I know this has already been discussed, but do not have an MVP- would appreciate seeking some external (non-OC/fresh eyes) feedback from other users on the best way to resolve this issue.
    - **Potential MVP Draft?**: Not sure if this is how all groups want to manage VC card requests, but the 'Request a card' popup modul could say something standard like this (with options to request a card/request an increase in the same modul and the requester must select one of those options) -->see below for comments about 'Request card' vs 'Request an increase':
```
Initiative Name:
Assignee: [Drop down w names]
Please detail the card usage below: (include vendor name, purpose (if applicable), monthly amount)

Requesting a new card
Zoom $40/month
Trello  $30/month
Amazon - Cleaning Supplies $200/month
Total: $270/month
or
Requesting an increase on existing card
need an additional $100/month for Amazon for Household Supplies)
[ ] By submitting this request, you agree to adhere to our Virtual Card Policy (edited)  
```

- "the amounts could be drop-down, even, or like a little in-browser tally for each item that totals it for them/us. so it's super obvious."

### Virtual Card Request vs Card Budget Increase 
- now that we use Privacy and cards are not vendor-locked/have max budget at $2500, users should request an increase rather than request a new card. We do not currently have a great way of having our users request an increase other than asking them to emailing us. It's confusing and involves too much back-and-forth. 
    - e.g.: as an admin, a group requested an increase thru our current 'Request a card' button.  I only knew it was an increase (not to assign them a new card) bc of memory (this isnt reliable).  I usually create cards thru the collective's OC page (not thru https://opencollective.com/foundation/admin/host-virtual-cards ) so it is unrealistic to expect host admins to check for duplicates before completing each new card request
    - **Potential mvp?**: When a card is created, if there is already a card for that collective (not including their baby 'Project's' card), a pop-up saying : "This collective already has a card. Would you like to create a new card for them or increase their existing card?"
    - Additional Comments from [Slack](https://opencollective.slack.com/archives/C02PTHM21M3/p1644282261667319):
         - "would even be useful if it says 'request a card' first and then only 'request a limit increase' after that (a bit clunky, but i usually check if they have a card before issuing a new one, under 'virtual cards' in the admin dashboard)"
         - "Down the line something like this would be cool. But I think we want the flexibility of being able to offer multiple cards for certain situations"
         -  "We want flexibility, in case we want to keep things separate for some reason."

### How to handle expenses that aren't monthly (e.g. yearly or one-off)
- There is not currently a 'built-into-the-platform' way to handle expenses that aren't monthly. (e.g. yearly or one-off)
    - This requires more manual oversight/approval/tracking (not scaleable)
    - Yearly/one-off can be done within Stripe, but these are not reflected to host admins on the platform (e.g. I made a 1-off card in Stripe, in OC it appears as monthly)
- Sample Use Cases (Not sure how to handle this complexity and systemize as a fiscal host admin):
    -  ![image](https://user-images.githubusercontent.com/64920686/162348799-096c0ee3-2e6b-4ccd-936e-273fe4d9e529.png)
    - ![image](https://user-images.githubusercontent.com/64920686/162348849-81cdaa44-42aa-4d16-8cac-daad83e1abc7.png)
    - **Possible mvps:**
        - Multiple cards? (e.g. 1 with yearly budget; 1 with monthly budget)
        - Give them a low balance initially and ask them to request an increase when their yearly payments are due (unintuitive, likely that something will slip through the cracks)
        - Trust them and grant them the max budget to the whole request
            - Will likely select 3rd option because: 
                - it requires least complication &
                - since we have the budget tied to the collective -> overspending is not possible
                - we carry a certain level of trust our hosted collective admins
                - **Possible Pain Point here**: "We can assign cards to Projects. But they’ll need to be careful to maintain the budget balance, as if the payment fails due to lack of balance, the individual will be on the hook."

### Refunds
- How do they work?
- Do they sync with the platform? 

## Edits/Needs:
- A stop put in place if a receipt has not been submitted within 30 days (this is vital to vc oversight as we scale up, tracking manually will be too much)
- A blurb in the app saying : by requesting a card, I agree to comply with [host's] virtual card policy (+link)
    - This way if the card is ever misused, host is not liable. 
    - However this would only be accepted by the assignee, so if another admin has access to the card and spends wrongly, host could not be liable--another reason why the assignee matters.
- [As a collective admin](https://opencollective.slack.com/archives/C6JTTA4SK/p1647351116647229): Add the host's address (zip code) to the page where the virtual card is.
   - User feedback: "Every time I use the virtual card, I have to go and find the zip code.
I know for some merchants the zip code doesn't matter. But, for some it does matter, because the card has not worked until I updated the zip code.
This would really help us. Thank you."
    - **Possible MVP**: Display full address/name on card/full contact details on this page https://opencollective.com/foundation/admin/host-virtual-cards?collectiveAccountIds=11049
    - [**Possible MVP**](https://opencollective.slack.com/archives/C02PTHM21M3/p1646689931421579)
        - People realistically don't check the 'Policy' link (where OCF has it's address listed)
        - Probably should be on the card itself in some place - perhaps in a dropdown saying "more details" or somewhere above in the text that isn't hidden
        - Add host's Zip code to the card info that's displayed to the collective admin/assignee - maybe just below the exp date/cvv
- On the 'Create card' and the 'Assign card' moduls, add blurbs saying 'Assignee will be notified of card creation via email.'
    -  ![image](https://user-images.githubusercontent.com/64920686/162354488-a373e890-42f6-47e4-bd16-baa3e80ea1d0.png)

- As a fiscal host admin: It would be amazing if from this page https://opencollective.com/foundation/admin/virtual-cards, I could click on a card and view: 
    - all transactions connected to that card, 
    - if there are any missing receipts for that card,
    - maybe even link directly to that card within Stripe 
- As an assignee, a place on the platform to view all my pending receipt uploads (digging thru emails is inefficient/unreliable)
- How to manage fraudulent charges
    - A button (on the expense itself, or in the list of transactions) to 'report error' or 'report fraud' or something
    - [This slack discussion](https://opencollective.slack.com/archives/C023USJSRGT/p1649270979296229)
        - [To dispute a charge](https://support.stripe.com/questions/fraudulent-transactions-and-disputes-using-stripe-issuing), you need to look at it in “transactions” rather than “authorizations” FYI
 --> Should we add this somewhere? Docs?
        - "Blocking to a merchant might help avoid some of these issues"
        - "We could try to emulate Privacy single merchant behavior. This would need some development as it’s not existing directly on Stripe."
        - "We would need to change policy back to having a bunch of cards for each collective…I think collectives like having just one card, and it lowers the work for the support team" --> Consider scalability too
        - "Lack of vendor lock is a positive, but potentially offering it as a feature/option could work"

## Comments:
- Do we need to store card useage purposes (the answers to application) anywhere - for auditing purposes?  Or is it sufficient to have them available in FD? Or are receipts for transactions sufficient?
    - If not, we'd probably want to have submitted answers auto-stored in a spreadsheet or somewhere.
    
### Re: Assignees:
- Need clearer indication/docs of what being an 'assignee' means
    - Do all collective/Project admins have access to the virtual card #?
        - If 'yes', we need to specify this on the 'Team' page (e.g. all admins added here will gain access to any virtual cards created under this collective. Project admins will only gain access to cards created for that specific Project) 
    - It should only be the assignee who has access to the card that they are responsible for. It feels a bit risky (as a collective admin) to put all the burden on 1 person, but have the access be open. -> Some groups have 10+ admins, that seems a bit risky to give them all access to a single virtual card number.
- The card assignee should be the only one notified of missing receipts (or what is the point of the assignee?)
- [User feedback](https://opencollective.freshdesk.com/a/tickets/65892)
    - "I have not shared virtual card info with anyone - the other admins know the virtual card information though. However, it says that I, [assignee] made these payments to [vendor], which I did not. under my name??? ...so just all virtual card uses are going to be shown as having been made by me.  Thats not ideal."
        - **Potential MVPs**: 
            - Each admin (who wants one) gets their own card, rather than each collective only getting one card. Perhaps this is a bigger conversation of adding another distinction to ['Team Roles'](https://docs.opencollective.com/help/collectives/collective-settings/core-contributors#roles)
            - Rephrased: Cards should be treated like a 'company card', where a collective gets assigned a card to a specific admin, only this admin has access to that card #.[1 card per admin (per collective).. 
                - There may be spaces for exceptions e.g. an admin uses their card for monthly recurring expenses. They request an additional 1-off card to pay for a retreat; that seems fine to me) -OR- an individual is an admin for 2 collectives, they might have multiple card access.
                - If a collective (or another admin) wants an additional card, that admin would get their own card. I think this creates better/clearer accountability + leaves less space for bad actors

## Edits to the auto-email the assignee receives:
- Can someone link to the existing auto-email here?
- Only the assignee should be emailed when the card is created (do you agree?)

~~### Copy edits to make:~~ _addressed in https://github.com/opencollective/opencollective/issues/5722_
 - When the card is **created**: 
    - "Do not share these card details with anyone.  Treat this card number as you would a physical card (being careful about viewing the card details in public spaces). To report fraudulent charges..."
    - The cardholder contact info as described by the host (especially the zip code/address)
        - This is a common question asked in support
    - Auto-email should include budget details (if it doesnt already) 
        - e.g. Your admin (assignee name) has been issued a card with a $___/monthly budget.  You can find card usage, policy, instructions, and contact information here (+link to card policy from host settings).  Your card's details can be found in your Settings (+link).  If you would like to request a budget increase, close or edit the card, please ___"
- an email like this ^^ should also be sent out whenever a card is **edited**: 
    - e.g. Your card's budget ending in ___ has been edited.  If you did not request this change, please reach out to your fiscal host. You find card usage policy instructions here (+link to card policy from host settings) and your card's details can be found in your Settings (+link).  
- or **closed**:
    - e.g. Your card ending in __  assigned to (assignee name) has been closed.  If you think this is an error, please reach out to your fiscal host.~~

THANK YOU FOR READING - IT'S SO MUCH!

**Comment by kaylarep** [comment]
related: https://github.com/opencollective/opencollective/issues/5269#issuecomment-1086416610

**Comment by alanna** [comment]
Thanks for writing this up @kaylarep ! Looking forward to feedback from @kewitz @Betree @znarf

**Comment by emberwry** [comment]
this is awesome work, i'm so glad this is in one place. i know some demos just came up improving some of these issues, and that @znarf has been doing some updates around email notifications, the expense creation automation, and refunds.

adding to the pile-on as a dream big item for this would be letting collective admins and hosts track monthly spending vs the allocated budget from the platform, like on the expenses tab for instance. right now they have no idea when they're getting close to their limit.

**Comment by kaylarep** [comment]
BIG +1 to this
> Letting collective admins and hosts track monthly spending vs the allocated budget from the platform, like on the expenses tab for instance. right now they have no idea when they're getting close to their limit.

It should have been included in this issue, don't know how it was missed.

**Comment by kaylarep** [comment]
more feedback from a user about how they use the virtual card (relates to assignee; receipt upload)

> What is happening with me is that I'm not usually the one who uses the card, I'm just the one left with the task of uploading the receipts when others use it. So, for me it's not an inconvenience with the card necessarily, but that people who use the card don't send/offer me the receipts they get and then I have to nag people. I haven't been able to find anyone in my network who's willing to be an admin for our page.  I guess I could have an expectation that people wanting/needing to use the card become admins so they can upload their own CC receipts?

not sure of an MVP to streamline this, but maybe:
- having 1 card per assignee? instead of 1 card per collective
  - adding granularity in roles for people who don't want to be a collective admin, but will likely be using a virtual card to make purchases
  - a flow for these people to be added as a 'spender' admin (or something-- with very clear details that people added as 'Spenders' will be allowed to request a card from the fiscal host); -> they then have access to 'Request a card', -> they are assigned a card (and informed in the auto-email that they will *need* to upload receipts); they will make purchases, immediately photograph and upload the receipt. done.

**Comment by alanna** [comment]
People who are not admins should not be using the card, unless the admins are 100% sure they can get the receipts from them. It's the admin's responsibility to manage this, or they can't have a card. But we should communicate this more clearly.

**Comment by kaylarep** [comment]
I'm not sure how plausible that is-or if there's a good way we can check on that/accomodate. e.g. a collective's admin is issued a virtual card, but that collective may have a team of volunteers who make purchases for the initiative (like groceries for example). 

its a lot to ask a collective admin to be the sole person responsible for both managing the Open Collective and also to make purchases on behalf of the collective (as stated in that feedback, they have a hard time finding community members willing to be OC admins, but those same volunteers may be more than happy to purchase & distribute groceries).

**Comment by kaylarep** [comment]
also need to consider regarding duplicate card requests: how 'Projects' will be handled (both from the fiscal host admin side & from the requester side) 

- "This Project's parent collective already has a card issued. Would you like to request a new card for this Project only (where funds will be removed from this Project's balance) or would you like to request an increase on the parent Collective's existing card?"

something like that?

**Comment by kaylarep** [comment]
Everyone who has access to the card must be made aware that receipts must be uploaded within 30 days.

e.g. sometimes a group's admins change, they are not aware of rules that the original admin agreed to

I think this is part of the conversation about 'Assignees' & roles

**Comment by alanna** [comment]
For compliance reasons, I wouldn't support assigning a card to non-admins.
We need card users to be covered by agreeing to our terms. However, it
would be very useful to make it more clear who is responsible for receipts
(an individual admin). Right now I get lots of emails saying I need to
upload receipts for transactions I'm not involved in that other admins
created, so it's hard to track my own ones. Also hosts need to know which
individual to hold responsible.

**Comment by kaylarep** [comment]
> For compliance reasons, I wouldn't support assigning a card to non-admins.

+1

as it is right now, I imagine there are many non-admins using the virtual cards

**Comment by alanna** [comment]
We can't stop non-admins from using cards, but the admin assigned is
responsible for collecting and uploading the receipts. And if they can't
manage that, they can't have a card.

**Comment by kaylarep** [comment]
> We can't stop non-admins from using cards, but the admin assigned is responsible for collecting and uploading the receipts. And if they can't manage that, they can't have a card.

have added a line to OCF docs for this

**Comment by znarf** [comment]
Duplicate with https://github.com/opencollective/opencollective/issues/4312 ?

**Comment by kaylarep** [comment]
@znarf This is an issue I created to try to consolidate all the ongoing issues mentioned in Slack (in the now-closed ocf-virtual-card-migration channel), mostly gathered from @emberwry and I as we were using virtual cards.

There are definitely some duplicates from https://github.com/opencollective/opencollective/issues/4312 but not all of them.

I do not think putting all these issues together into this issue like I did here was a good approach. Its too much all together like this, plus yes, there are also duplicates in other places, and not a good way to track.


If we plan to tackle 'Virtual Cards' edits all together, I might like to try and get these all organized into 1 Project/Discussion, with separate issues for each issue. I imagine at this point, there are a few duplicates/resolved issues floating around in different places.

**Comment by znarf** [comment]
@znarf cool, my intent was not to suggest we should close this one, just highlighting that they were both about Virtual Cards feedback/improvements.

**Comment by RichardLitt** [comment]
Related to https://github.com/opencollective/opencollective/issues/5699, which covers only the monthly-only aspect of virtual cards.

**Comment by natehn** [comment]
From @znarf: "For the future, we'll need to make sure that Host Admins have the flexibility to "Mark as unpaid" Virtual Card Expenses."

**Comment by kaylarep** [comment]
[user feedback](https://opencollective.slack.com/archives/C01LTEBDARL/p1658844184943649):
> Feature request: Show virtual card requests pending approvals.
It would be useful to see a pending virtual card request so I can know it was submitted successfully.
There's no email confirmation that the request has been submitted nor any indication as to how long I should expect to wait.

**Comment by kaylarep** [comment]
https://github.com/opencollective/opencollective/issues/5788 Custom label or description for virtual cards

**Comment by kaylarep** [comment]
https://github.com/opencollective/opencollective/issues/5787 Display virtual card Assignee to Admins

**Comment by kaylarep** [comment]
As a fiscal host admin, ideally would be able to click on a Collective's name on their virtual card (from within my dashboard), and a new tab would open to that collective's page. 

![image](https://user-images.githubusercontent.com/64920686/184018240-c73cfc80-dbfe-4536-9c01-ccecd8c8e8e4.png)

**Comment by BenJam** [comment]
I'm going to fold all of this into #5059 and close this out.

**Comment by BenJam** [comment]
...aaaand I'm done https://github.com/opencollective/opencollective/issues/4312

**Comment by emberwry** [comment]
there's probably some overlap, but this project all came from after
bringing in stripe so is more up to date
