### ISSUE TITLE
E2E Intermittent Failures: Contribution Flow - Guest contributions

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5412]
It seems that in the `Contribution Flow: Guest contributions` E2E tests we have intermittent failures. Some failure runs are,

https://github.com/opencollective/opencollective-frontend/runs/5873120352?check_suite_focus=true

https://github.com/opencollective/opencollective-frontend/runs/5873014997?check_suite_focus=true

https://github.com/opencollective/opencollective-frontend/runs/5868773628?check_suite_focus=true

All of these fail with the same error; 

```
AssertionError: Timed out retrying after 15000ms: Expected to find content: 'You are now supporting APEX.' within the selector: '[data-cy="order-success"]' but never did.
```
It seems that this is related to the CAPTCHA where the checkbox isn't somehow checked. 🤔 

![image](https://user-images.githubusercontent.com/12435965/162407594-f500b5d9-fd0f-41a2-ad69-08a81fc68daa.png)

**Comment by alurban** [comment]
@SudharakaP I'm still seeing this error show up after rebasing against `origin/main`, see e.g. this run: https://github.com/opencollective/opencollective-frontend/runs/6079709988?check_suite_focus=true

**Comment by SudharakaP** [comment]
> @SudharakaP I'm still seeing this error show up after rebasing against `origin/main`, see e.g. this run: https://github.com/opencollective/opencollective-frontend/runs/6079709988?check_suite_focus=true

Yes you are right. it seems reduced though as I am not seeing it all the time as I used to. But it does seem to still occur. We need to investigate more on this. 🤔

**Comment by SudharakaP** [comment]
I was looking at recent logs and this issue doesn't seem to appear anymore (for the last 20 days it has appeared only once); at least I couldn't find any recently. I believe the root cause is that it take some time for the captcha to respond once the user click on the checkbox and the PR above fixes this by increasing the waiting time. If it starts appearing often in the future feel free to reopen the issue and we can look further.
