### ISSUE TITLE
Add Funds incognito

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5419]
## User story 
As a host admin, I want to be able to select incognito as an option in the `add funds` screen, so that I can manually process anonymous financial contributions to Collectives.

## MVP
A tick box on the `add funds` modal saying `incognito` which makes the contribution incognito while still capturing the real contributor info privately, just like if the contributor did and incognito contribution themselves.

Currently the workarounds for this are [not good](https://opencollective.slack.com/archives/GFH4N961L/p1649670062048839), causing issues with receipts and recordkeeping.

  P2 low frequency, high impact

**Comment by znarf** [comment]
Duplicate with https://github.com/opencollective/opencollective/issues/5453
