### ISSUE TITLE
OC UK - Collectives not showing

### ISSUE THREAD

**Issue by Kilheure** [opencollective/opencollective#542]
Hi again, 

OC UK is a host and there are 2 collectives underneath. Although the OC page says so, there is no link, nor any details about the collectives (such as a logo etc.). 
It looks like the set up of the page is different than WWC (also a host but where underneath collectives logo and link show up on the page). 
Aligning host page will be beneficial for all. 

Thanks for looking at this issue. 
Dimitri

***

URL: https://opencollective.com/uk
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser: all (chrome, Firefox etc.)

Bonus point if you can add a screenshot :-)
![screen shot 2017-10-20 at 09 41 40](https://user-images.githubusercontent.com/31570464/31812446-e52478c8-b57a-11e7-8e1a-105eff6b3c4d.png)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by piamancini** [comment]
closing this it's duplicated in #507
