### ISSUE TITLE
Show Tags on a collective's page

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#5422]
Groups can tag themselves within their settings. These tags can be used to find them using the search feature, but otherwise do not appear on the collective's page. (They now appear on the cards that appear in the search.)

![image](https://user-images.githubusercontent.com/64920686/162901293-674854c3-969a-4c87-a683-96d4bba25640.png)

### MVP: 
Display the tags on their page, probably at the bottom, but open to suggestions.

**Comment by Betree** [comment]
We currently display what we think is the collective's "main tag" in the hero (guessed through some magic formula) but not the others:

![image](https://user-images.githubusercontent.com/1556356/162905138-4bc1b657-5558-4ff7-b301-8ec34466ab88.png)

That could indeed be a nice addition that would help collectives with their page SEO. Maybe we can display that in the "About" section?
![image](https://user-images.githubusercontent.com/1556356/162905462-1a30de52-0b0a-4bc4-bf8f-18fc1dfce28a.png)

**Comment by BenJam** [comment]
sounds like it would be nice and easy to reappropriate the design used in #4295 here in the collective page.

**Comment by BenJam** [comment]
@opencollective/design not sure we need a full kick-ff on kick off here, would you be able to look at how tags should be presented here?

**Comment by Betree** [comment]
Link to figma design: https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=16687%3A236361

**Comment by kaylarep** [comment]
I like this design!

what happens when you click on a Tag on a collective's page? In my mind, it should open a page of Search results with that tag.

**Comment by kaylarep** [comment]
it already does! disregard above comment.

**Comment by SudharakaP** [comment]
Follow up issue with the design changed we shall iterate later; https://github.com/opencollective/opencollective/issues/5563
