### ISSUE TITLE
Searching Again with New Term should Reset Filters in `/search` page

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5425]
A small regression that was introduced with a recent change to the `/search` page. Suppose we've searched for some term and filter the results and then try to search for a new term. The old filters are not reset. The below screencast shows this;

![reset-filters](https://user-images.githubusercontent.com/12435965/163043179-0bcb4e16-a06d-4502-8d43-c61c5f0e44d8.gif)

**Comment by Betree** [comment]
Do we want to reset the filters? Looking at other websites like https://www.indiegogo.com/explore/tech-innovation?project_type=campaign&project_timing=all&sort=trending&q=potatoe, some of them seem to preserve the filters when the search changes.

@opencollective/design any opinion?

**Comment by SudharakaP** [comment]
> Do we want to reset the filters? Looking at other websites like https://www.indiegogo.com/explore/tech-innovation?project_type=campaign&project_timing=all&sort=trending&q=potatoe, some of them seem to preserve the filters when the search changes.
> 
> @opencollective/design any opinion?

@Betree : But when the search changes, the tag cloud change as well. Thus at the very least the tag cloud should be reset I think. 🤔

**Comment by Memo-Es** [comment]
In our specific context, and supported by the behavior of displaying different tags with each new search, I lean towards restarting filters, sorting, and tags with every new search.

@Betree @SudharakaP 

P.D. I'm still open to tweaking this in the update phase of the next sprint

**Comment by SudharakaP** [comment]
> In our specific context, and supported by the behavior of displaying different tags with each new search, I lean towards restarting filters, sorting, and tags with every new search.
> 
> @Betree @SudharakaP
> 
> P.D. I'm still open to tweaking this in the update phase of the next sprint

Thanks for the input @Memo-Es. 👍🏽
