### ISSUE TITLE
Improvement → Tiers should allow custom button text

### ISSUE THREAD

**Issue by phated** [opencollective/opencollective#543]
Currently, tiers force button text ("Become a Sponsor", "Become a Backer", "contribute") text on their button.  Tiers should allow us to customize the text on the button, especially because we are changing the names of "Backer" and "Sponsor" and "contribute" looks really bad for custom tiers.

![screen shot 2017-10-20 at 10 59 39 am](https://user-images.githubusercontent.com/992373/31835342-0e2a913e-b586-11e7-8079-6fca833451f2.png)
![screen shot 2017-10-20 at 11 01 04 am](https://user-images.githubusercontent.com/992373/31835343-0e432fbe-b586-11e7-8933-8175a188a5ae.png)

**Comment by xdamman** [comment]
What would you like to see?
We could let customize the button but I'm cautious about adding too many settings/features that will boggle down the interface and UX.

**Comment by phated** [comment]
@xdamman the text of the button should be configurable, just like the description and title.

**Comment by phated** [comment]
Any update here?

**Comment by phated** [comment]
Ping @piamancini @xdamman

**Comment by phated** [comment]
Any word when we will see this?

**Comment by xdamman** [comment]
Sorry, this has been low on our priority list. Want to take the opportunity to do a PR for this?

**Comment by phated** [comment]
@xdamman I got lost in the stack, can you point me to where this would happen?

**Comment by xdamman** [comment]
https://github.com/opencollective/frontend/blob/master/src/components/EditTiers.js#L67

Would be good if you could also add a test for it
https://github.com/opencollective/frontend/blob/master/cypress/integration/collective.edit.test.js

Let me know if you have any issue to get your local environment set up.

**Comment by phated** [comment]
@xdamman those look like just the frontend components of this - how does that interact with the API server/database storage?

**Comment by phated** [comment]
I might have a chance to look at this coming up.

**Comment by Betree** [comment]
If anyone's willing to tackle this issue: we already support this feature - we're only missing an input in tiers edit section for users to customize the value themselves. The field is `tier.button`.

**Comment by znarf** [comment]
A $50 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

**Comment by burinious** [comment]
from #osca ph will like to work on this issue

**Comment by burinious** [comment]
please I'm confused how do i go about this

**Comment by znarf** [comment]
@burinious You need to add a new field "Button Text" in the "Tiers" administration interface, in the "Edit Collective" panel.

![Capture d’écran 2019-07-06 à 17 03 58](https://user-images.githubusercontent.com/806/60757842-33c54d00-a010-11e9-9f8c-892364ae16d7.png)

**Comment by Betree** [comment]
I'm thinking that it would be great to provide multiple pre-defined options (donate, contribute, join, participate, register...) that collective admin can pick. Pre defined options can easily be translated, it's much harder for custom strings.

**Comment by alanna** [comment]
I don't think we should assume we know what the pre-defined options should be. Better to let it be customizable then look at the actual data to see what the most common ones are and implement that in a future phase if needed. If a Collective's main community is non-English speaking, then they will make the titles in their ow language anyway.

**Comment by jsamchineme** [comment]
@znarf I am trying my hands on fixing this issue.

After setting up the development environment, I realized I needed to login when I hit the url I could observe in this comment (https://github.com/opencollective/opencollective/issues/543#issuecomment-508932858) above. 

After Login, I get me a message on the page stating `You need to be logged in as the creator of this collective
or as a core contributor of the Blogmarks collective.`

So, is there a way I can get dummy credentials that can give me access to this page, so that I can see the fixes I make as work on this issue?

That will be appreciated.

**Comment by znarf** [comment]
@jsamchineme You don't have to use this precise Collective, I just took a screenshot because I'm an admin of this Collective. To develop this feature, feel free to create a new Collective and you will be admin of it.

**Comment by jsamchineme** [comment]
@znarf Thanks for the hint. I have now created a new collective and added a tier to the account.
However, I see that the API doesn't have a field "buttonText" returned with a Tier.

**Here is the screenshot** 

![image](https://user-images.githubusercontent.com/14825863/60978634-549be400-a329-11e9-80b7-ddc301907be6.png)


Does this mean I would also have to work on the backend project to enable this feature?

**Comment by znarf** [comment]
For reading, the `button`field is already exposed in the GraphQL API. So you don't need to code the support for it, you can just add it in the GraphQL query in the frontend.

For saving, I'm not sure.

**Comment by jsamchineme** [comment]
I just checked the backend code and it appears saving caters for the `button` field.

**Comment by burinious** [comment]
@znarf have updated the description

**Comment by znarf** [comment]
Thank you @burinious ! It's merged. (Deployment to production is still pending).

To claim the bounty, you can:

a) submit an invoice to https://opencollective.com/engineering
b) or ask for an Open Collective gift card of the same value (to donate to other collectives)
