### ISSUE TITLE
Stripe Virtual Cards: Charge Expense gets stuck in Processing

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#5439]
There's potentially an edge case where a charge expense from Stripe that was previously authorized doesn't move out of the "PROCESSING" state.

Apparently, these charges can be reversed before ever getting fulfilled. We currently have 51 stripe charges marked as PROCESSING, the oldest being from February 21st.

We can monitor this with:
```
SELECT * FROM "Expenses"
WHERE
    "type" = 'CHARGE'
    AND "data"->>'authorizationId' IS NOT NULL
    AND "status" = 'PROCESSING'
ORDER BY "id" DESC
```

One proposed solution is to stop creating charge expenses when the transaction is only authorized and wait until it is actually cleared.

**Comment by znarf** [comment]
> One proposed solution is to stop creating charge expenses when the transaction is only authorized and wait until it is actually cleared.

That's not a desirable solution, this is the mechanism that is blocking the balance for the authorized transaction.

We should delete/expire the processing Expenses when we detect that the authorization was not processed (maybe there is a Stripe event for this). Or, we can simply delete/expire them after a few days with a background job.
