### ISSUE TITLE
Error paying expense via Paypal as host

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#544]
Hey I approved an expense yesterday on the foynt collective, www.opencollective.com/foynt when I logged in as a host and head to the expenses list, I clicked on "Pay with Paypal" and got a red message saying " Cannot query field "payExpense" on type "Mutation"."

My web browser is Safari

![screen shot 2017-10-20 at 3 10 26 pm](https://user-images.githubusercontent.com/30665166/31840157-aa60d8e2-b5a9-11e7-9220-798f25959826.png)

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by nicobarretoOC** [comment]
Expanding on this: 

![screen shot 2017-10-23 at 3 49 00 pm](https://user-images.githubusercontent.com/30665166/31912534-d63d7aa8-b809-11e7-812f-b197ad73c0d6.png)

![screen shot 2017-10-23 at 3 49 11 pm](https://user-images.githubusercontent.com/30665166/31912548-e17e2728-b809-11e7-9f40-689f2294eeb3.png)

**Comment by piamancini** [comment]
@nicobarretoOC is this still happening?

**Comment by nicobarretoOC** [comment]
Nope, closing this :)
