### ISSUE TITLE
MemberForm: Can't use `delete` button to remove characters in the description field

### ISSUE THREAD

**Issue by snitin315** [opencollective/opencollective#5441]
**Describe the bug**

Can't use the `delete` button to remove characters in the description field in the `EditMember` or `InviteMember` form.

**To Reproduce**
1. Go to `/collective-slug/admin/members`
2. Try editing a member details
3. use `Delete`/`Backspace` button
4. see error

**Expected behavior**

The `delete` button should work.

**Screenshots**

<img width="678" alt="Screenshot 2022-04-15 at 7 52 24 AM" src="https://user-images.githubusercontent.com/46647141/163507863-419502f9-310e-442e-9f56-212376bbc404.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser firefoxx

**Additional context**

I'm sure this was working before.

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
Might have been introduced in https://github.com/opencollective/opencollective-frontend/pull/7229/files#diff-30b3ec719caea3e77d1153e899b7991654a9df9ca8f69dda3a99556ab7a74cb5 cc @SudharakaP 

The initial reviews on this `MemberForm` missed that it was using an `InputField`. The component has been deprecated for a long time in favor of the `StyledInput` family. That's one more for https://github.com/opencollective/opencollective/issues/4830

**Comment by Betree** [comment]
Great if we can solve both issues at once. I'm adding a bounty for:
- [ ] Solving the reported bug
- [ ] Remove the fields array + `fields.map` + `InputField`, use a more traditional approach (`<form><field1/><field2/></form>`), ideally use `StyledInputFormikField`. See [this one](https://github.com/opencollective/opencollective-frontend/blob/4c5e457dfc9bfd42496b9fca8f309e250d057ff9/components/host-dashboard/AddFundsModal.js#L406) for an example.

---

:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted, and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by JoyLubega** [comment]
H @snitin315  @Betree is this still in development? Can I check it out

**Comment by Betree** [comment]
> H @snitin315 @Betree is this still in development? Can I check it out

@snitin315 is still being iterated on

**Comment by Betree** [comment]
:trophy: This issue has been completed by @snitin315  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
