### ISSUE TITLE
Include expense payees in Updates

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5443]
## User story 
As a Collective admin, I want expense payees to get my Updates, so that they can stay in the loop and be acknowledged as contributors to the mission.

As an expense payee, I want to receive important news from Collectives I do work for and am involved with.

Updates go to all Collective contributors. We include admins and core contributors along with financial contributors already. Expense payees are also contributors to the Collective mission, who have an interest in keeping in the loop with the project.

## Best solution for this problem
More fine grained options for Updates announcements where admins can choose the categories of contributors to receive each update (eg checkboxes for financial contributors, admins, expense submitters, etc).

## MVP
Include expense payees in the category of people who receive both Private and Public Updates. Probably only include payees of *approved* expenses to avoid contacting any spammers or people not actually involved.

  P3 high frequency, low impact

**Comment by Betree** [comment]
@alanna I just double-checked and can confirm that this is already the case: expense payees are added as members with the role `CONTRIBUTOR`, and contributors [do receive updates](https://github.com/opencollective/opencollective-api/blob/5a1a55dace6c7216e9491480b7c412fa92d674f1/server/models/Update.js#L32) (both private and public).

Maybe we can better surface that fact in the interface?

**Comment by alanna** [comment]
Oh great I didn't know that.
