### ISSUE TITLE
Crypto Flow Approximate Fiat Amount is not Shown Anymore

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5448]
I noticed that starting recently the approximate conversion amount in the crypto flow is not shown anymore. We used to have, 

![image](https://user-images.githubusercontent.com/12435965/163842340-7ba3087d-2937-4b97-bf6d-3d863c4f3d97.png)

But currently this approximate fiat amount isn't shown; 

![image](https://user-images.githubusercontent.com/12435965/163842458-a959ab77-0bf6-4c46-8b71-a42b208c6814.png)

This seems to be a CORS issue with the following message being printed on the console; 

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.cryptonator.com/api/ticker/BTC-USD. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 503.
```

**Comment by znarf** [comment]
The fix should be straightforward, anything blocking?

**Comment by SudharakaP** [comment]
@znarf : I couldn't figure it out yet. This was working before just with the content security policy set; 

https://github.com/opencollective/opencollective-frontend/blob/088343430e009746a2e52bb2e12f00ac5456e9cc/server/content-security-policy.js#L49 

There's also an idea that the ad-blocker might be the cause; but I removed the ad-blocker and it still seems not working. Maybe it's cloudflare (as suggested here; https://opencollective.slack.com/archives/G46PNRCGP/p1649062979855229), do we have to add an exception there? I am still trying to understand this and why it was working before. 🤔

**Comment by SudharakaP** [comment]
It seems that Cloudflare is blocking this as per it's Bot fight mode. However it also says in their documentation that that we cannot add an firewall exception to the bot fight mode; https://developers.cloudflare.com/firewall/cf-firewall-rules/actions. 

I think we need to add a query on the API side to get the Cryptonator exchange rates and then call that from the front-end. This should solve this problem. 🤔 

Reference discussion on Slack: https://opencollective.slack.com/archives/G46PNRCGP/p1649062979855229
