### ISSUE TITLE
Spanish correction on string

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#545]
Just a minor correction to change the word "APROVAR" to APROBAR in Spanish :)

![22684805_10214494920386201_518375528_n](https://user-images.githubusercontent.com/30665166/31845753-0cbb6794-b5ca-11e7-90c1-0db826b7f893.png)

***
Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by piamancini** [comment]
good catch nico! fixed https://github.com/opencollective/frontend/pull/68
