### ISSUE TITLE
Load More Button in Update Page Not Positioned Correctly

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5451]
It seems that currently the `load more` button on the updates page is not positioned correctly; 

![image](https://user-images.githubusercontent.com/12435965/163855648-82b6152b-e041-4918-ab72-21fdea2fd2f8.png)

As shown in the above screenshot it seems that the button is within the last update. We need to show the button outside of the update and also capitalize it; `Load more` instead of `load more`. 🤔

**Comment by Betree** [comment]
Example: https://opencollective.com/sequelize/updates

**Comment by Betree** [comment]
Resolved by https://github.com/opencollective/opencollective-frontend/pull/7748
