### ISSUE TITLE
Collective balance > GRAPHQL_MAX_INT

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#5452]
We've been seeing some weird logs related to balances in cents that can not be represented as GraphQL Int.

Most of these logs are related to spammy collectives playing around with "Add Funds", nonetheless we should take into consideration that we deal with multiple currencies and this can quickly become a serious issue.

For context, `GRAPHQL_MAX_INT = 2147483647`.

**Comment by Betree** [comment]
`2147483647` cents => ~`2,1474,836` full. In `GNF`, this value appriximatively equals $2387,67. So it's not crazy to end up with amounts like that in the API, we should make sure they're supported.

We already have the `graphql-scalars` dependency. If it's not a breaking change, I would advocate changing `Amount.valueInCents` (and related legacy amount fields) types to its `BigInt` scalar. We may also want to update some typescript prototypes to the JS [BigInt](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/BigInt) type.

It's difficult to estimate the complexity and side-effects of such change without testing.

**Comment by Betree** [comment]
This issue describes the same problem reported in https://github.com/opencollective/opencollective/issues/4944. I've closed the other as this one is more accurate.

**Comment by Betree** [comment]
We got another crash related to this on the search: https://opencollective.slack.com/archives/C03AWL58JRM/p1657906554753789.

**Comment by Betree** [comment]
Seems like https://github.com/opencollective/opencollective-api/pull/7945 did the job, this issue should not happen anymore with collective balances on our public API.

**Comment by kewitz** [comment]
Looks fine considering JS uses float64. It would be a problem if it was float32.
