### ISSUE TITLE
Cant create collective for fody

### ISSUE THREAD

**Issue by SimonCropp** [opencollective/opencollective#546]
tried to create a collective for fody 

https://github.com/Fody/Fody

but it doesnt show up for me

![image](https://user-images.githubusercontent.com/122666/31862057-7a453514-b783-11e7-8a16-336b9de0170a.png)

but fody would seem to meet the criteria?

**Comment by piamancini** [comment]
Hi Simon, 
It might have to do with your rights on the repo. 
@asood123 should be able to help you through it. 
best!

**Comment by SimonCropp** [comment]
any more info on this one?

**Comment by piamancini** [comment]
Hi Simon, we'll be working on this today. Sorry it's taking so long!

**Comment by piamancini** [comment]
I'm closing this issue since it's duplicated #555

**Comment by SimonCropp** [comment]
Thanks. I will track the other issue

**Comment by asood123** [comment]
Simon - is Fody an org on Github? if so, you may have to reauth through Github and give us org permissions. Let me know if that still doesn't work for you.

**Comment by SimonCropp** [comment]
@asood123 yep re-authing fixed it. thanks
