### ISSUE TITLE
Redirect Open Collective contact button to support page

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5460]
People are submitting support requests using this form: https://opencollective.com/opencollective/contact

It would be much better if this button redirected to https://opencollective.com/help

![Screen Shot 2022-04-21 at 10 41 39 AM](https://user-images.githubusercontent.com/5498878/164336716-9e5b4549-6564-43aa-8618-a40c7817fdcb.png)

**Comment by Betree** [comment]
Resolved by @ktasdf in https://github.com/opencollective/opencollective-frontend/pull/8028
