### ISSUE TITLE
When clicking on discover link  it takes too much time to load (AVG: 10sec)

### ISSUE THREAD

**Issue by jonattfin** [opencollective/opencollective#5462]
**Describe the bug**
Loading the projects (when clicking on discover) takes too much time > 1sec (actually avg was 10sec) for 10 requests. But the problem is not with the frontend, but the graph api endpoint which is too slow.

**To Reproduce**
1. Go to home page
2. Click on Discover projects.
3. Check the time in the network tab.

I've also done a test through the postman test runner, and did 10 requests to "https://opencollective.com/api/graphql/v1" to see if it's an isolated case, or this is "quite the same issue" for all the requests and you can see the results below (attached). 10 Seconds is the avg, but there was also times when it took more than 20 seconds which for a site like OC should never happen.

**Expected behavior**
I would expect that page to load in less than 1sec, considering the fact that that page is one of the most important if not the most important page... and of course it has to be as fast at it can be. Aren't you guys using any distributed cache (EG: redis, or so?)

Additional comments: "The BBC loses an [additional 10% of users](https://www.creativebloq.com/features/how-the-bbc-builds-websites-that-scale) for every extra second it takes for its site to load"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04.1]
 - Browser [Firefox 99.0 / Postman 9.15.2]

**Additional context**

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by jonattfin** [comment]
As i don't know how to attach files here... I've added the postman test run as a code snippet, you can just save it as a json and then import it in postman, or if you'd open it, the important part ar the times ... which are in milliseconds.

"times": [
				10421,
				7639,
				7731,
				9099,
				8276,
				7759,
				12887,
				13263,
				10266,
				22721

**Comment by Betree** [comment]
@jonattfin Thank you for this issue. It's something we're actively working on. It's related to https://github.com/opencollective/opencollective-frontend/pull/7706 / https://github.com/opencollective/opencollective/issues/5454.

> Aren't you guys using any distributed cache (EG: redis, or so?)

We are, feel free to dig into the API's code: https://github.com/opencollective/opencollective-api/

**Comment by jonattfin** [comment]
@Betree Thanks for the quick response. I look forward to see the solution in practice ;-)
I wasn't sure what's the repo, but now... yes, i'll look at the code.

Feel free to make this bug an duplicate.

**Comment by SudharakaP** [comment]
This is already being looked at in https://github.com/opencollective/opencollective/issues/5454. We have restored the old `/discover` page for now until this situation is solved and we find a way to make the default search page (search page with no search term and sorted by "activity") faster. I am closing this issue as this is tracked in the above issue.

**Comment by Betree** [comment]
@SudharakaP The issue that @jonattfin is reporting appears to be on [`/discover`](https://opencollective.com/discover), the legacy / unredirected page

**Comment by znarf** [comment]
@Betree absolutely, reopening cc @SudharakaP

**Comment by znarf** [comment]
Discover is gone !
