### ISSUE TITLE
Contact from incognito

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5467]
I got this message via someone clicking the contact button on OC. But it came through as incognito, meaning I can't easily see who it's from. But if I click reply, their email address is there as reply-to. In this case, that's good, because this person wants us to contact her. But if they thought they were actually incognito, it violates their expectations to reveal their email address to the recipient. I don't think we should allow contact from incognito because we need to know who is contacting us and be able to reply.

<img width="856" alt="Screen Shot 2022-04-23 at 8 34 35 PM" src="https://user-images.githubusercontent.com/5498878/164887378-02aa70a5-1cf6-4007-967e-768a91f5816a.png">

**Comment by Betree** [comment]
Users don't have the ability to pick the profile they're using to contact a collective, we use the default user profiles. This person just happened to have `Incognito` set as their user name.
