### ISSUE TITLE
Private instructions on Events should render as pre

### ISSUE THREAD

**Issue by RichardLitt** [opencollective/opencollective#5468]
Right now, private instructions on events are not rendered as rich text, although they allow rich text in the text field for creators when making an event. Line endings, especially, should be preserved. 

Related to https://github.com/opencollective/opencollective/issues/5461.

**Comment by Betree** [comment]
We must make sure that new lines are preserved in the frontend **and** in the email (ticket confirmed), e.g. using the [pre](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre) tag.

**Comment by snitin315** [comment]
@Betree Can this be a bounty?

**Comment by Betree** [comment]
@snitin315 Sure, feel free to assign yourself or decline as you requested it first. Also, please provide a screenshot on the PR.

**Comment by Betree** [comment]
:trophy: This issue has been completed by @snitin315  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Comment by RichardLitt** [comment]
Thanks, @snitin315!
