### ISSUE TITLE
cannot accept financial contributions via Stripe for a new event in new org

### ISSUE THREAD

**Issue by k-qy** [opencollective/opencollective#5469]
**Describe the bug**

When I make a new event and try to set the way I accept financial contributions, clicking on "Connect Stripe" yields no visible response, and the console logs several errors (which happen for each button click):

```
instrument.js:109 [GraphQL error]: Message: Account must be a collective or a fund, Location: [object Object], Path: applyToHost
...
AcceptContributionsOurselvesOrOrg.js:120 Uncaught (in promise) Error: Account must be a collective or a fund
    at AcceptContributionsOurselvesOrOrg.js:120:13
...
```

My (uninformed) guess is that this is happening because the code doesn't handle cases where the account is an "event." So perhaps the fix is either to not allow financial contributions to be set per-event, or to handle the case.

P.S. With a little guidance about the expected behavior, I'd be happy to try and fix this bug 🙂 

**To Reproduce**
1. Make a new collective with no finances set
2. Make a new event with no finances set
3. Go to the event page and try to set a method to accept financial contributions for it (example URL: `https://opencollective.com/testing-event-855924df/accept-financial-contributions/ourselves`)
4. Click "Connect Stripe"
5. Click does not work

**Expected behavior**
Should be able to accept financial contributions via Stripe for the event

**Screenshots**

<img width="1430" alt="Screen Shot 2022-04-23 at 11 27 27 AM" src="https://user-images.githubusercontent.com/2762356/164912618-a70322f1-4685-45fc-9ad0-52fb4dda3d75.png">

**Desktop (please complete the following information):**
 - OS: macOS Version 12.0.1 (Build 21A559)
 - Browser: chrome
 - Version: 100.0.4896.75 (Official Build) (arm64)

**Smartphone (please complete the following information):**
N/A

**Additional context**

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by k-qy** [comment]
I also get a similar error when I try to add a bank account for the event instead: ("Account must be a collective or fund" error message + console error appears when I try to submit bank details, although they appear to be saved in the org now)

<img width="1432" alt="Screen Shot 2022-04-23 at 11 43 25 AM" src="https://user-images.githubusercontent.com/2762356/164913164-9dc1e983-45d9-4f48-a5c1-68ee779d31ca.png">

**Comment by Betree** [comment]
@k-qy Thanks for documenting this issue.

Stripe/Bank account must be connected from the event's parent. We must make sure that "Accept financial contributions" links to `/:parent/accept-financial-contributions`, not `/:event/accept-financial-contributions` in this case.

@k-qy As a workaround, I recommend going on the parent's profile to set things up.

**Comment by k-qy** [comment]
thanks for the fix/workaround @Betree!
