### ISSUE TITLE
Links in HTML view of e-mail broken but present

### ISSUE THREAD

**Issue by niccokunzmann** [opencollective/opencollective#5471]
**Describe the bug**
I received an e-mail with the title "Getting started with Open Collective".
There are some links in there.
When I want to click certain links, they do not work.
I attach the full source code: [full-email-hello-osc.txt](https://github.com/opencollective/opencollective/files/8552043/full-email-hello-osc.txt).
```
<li style=3D"margin: 5px 0px; line-height: 1=2E4; font-size: 14px; color: =
#494B4D;">Read <a href"https: blog=2Eopencollective=2Ecom ten-steps-to-succ=
essful-open-source-crowdfunding " style=3D"text-decoration: none; color: #2=
97EFF;">Ten Steps to Open Source Crowdfunding</a> and more case studies and=
 how-tos<a href=3D"https://blog=2Eopencollective=2Ecom/" style=3D"text-deco=
ration: none; color: #297EFF;">on our blog</a></li>
<li style=3D"margin: 5px 0px; line-height: 1=2E4; font-size: 14px; color: =
#494B4D;">Here=E2=80=99s our <a href=3D"https://docs=2Eopencollective=2Ecom=
" style=3D"text-decoration: none; color: #297EFF;">documentation</a>, inclu=
ding a <a href=3D"https://docs=2Eopencollective=2Ecom/help/collectives/quic=
k-start-guide" style=3D"text-decoration: none; color: #297EFF;">quick start=
 guide</a></li>
<li style=3D"margin: 5px 0px; line-height: 1=2E4; font-size: 14px; color: =
#494B4D;"><a href"https: docs=2Eopencollective=2Ecom help collectives githu=
b-sponsors" style=3D"text-decoration: none; color: #297EFF;">Connect GitHub=
 Sponsors</a> to your Collective (we also accept contributions in bitcoin a=
nd public stock!)</li>
 </ul>
```

You can find `"https://blog` as welll as `https: blog`. There are spaces where there should be none.#
If you look at the full source, you will find that this contains valid links in the text format but invalid links in HTML.

**To Reproduce**
1. Go to '[...](https://opencollective.com)'
2. create a new account
3. receive an e-mail

**Expected behavior**

I would like the links to be clickable.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
@niccokunzmann Thanks, this email looks broken indeed. We'll look into it
