### ISSUE TITLE
Supercollective showing wrong number of collectives 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#548]
Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: https://opencollective.com/reconomycop
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: seeing 3 collectives not 33 in the number
Browser:

Bonus point if you can add a screenshot :-) The URL shows the bug

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by jfdh** [comment]
Hi all!

On https://opencollective.com/brusselstogether

There are two issues:

1- it is displayed that there are “29 29” collectives hosted by BrusselsTogether (I think there should be less than 20)

2- the events are displayed as collectives (e.g. Meetup - sustainable mobility has its own collectives).

On https://opencollective.com/europe, there are also two issues I noticed:

1- It is displayed that there are “4 4” collectives.

2- Open Collective Europe is shown next to the others collectives below the headings

**Comment by jfdh** [comment]
I also got a 500 internal error on https://opencollective.com/veganizerbxl

Thanks for everything :)

**Comment by piamancini** [comment]
thanks for reporting @jfdh the 500 issue is separate from this issue that refers to the number of collectives. Can you please report it separately? thanks!

**Comment by piamancini** [comment]
This still needs to be solved, events are showing mixed with the collectives https://opencollective.com/europe 
If we don't have all the pieces together don't show events cards, the information is already above and it's confusing for users.
