### ISSUE TITLE
[Strategic Focus] Simplification 

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5486]
_Simplification is about reducing complexity for our users, refining the user experience, honing our core experiences, and reducing the load on our staff._

This means being more selective about where we focus our time. Simplifying is about reducing mental load by reducing the decisions to be made,  communicating process and progress, using plain language and considering the entirety of someone’s experience, whether it’s on our platform or elsewhere. Simplification will most often bring a journey that involves many steps and/or services into one cohesive experience.  Simplification may shift complexity elsewhere, when we do this we will always shift complexity from the many to the few.

Key projects in this area include:

- #4689 
- #4829 
- #4699 

If we're success we should see

- A reduction in the amount of time we spend onboarding individual collectives and organisations
- A reduction in the volume of  requests fielded by support and engineering

**Comment by alanna** [comment]
Metrics ideas:
* Reduction in number of screens/clicks to achieve key workflows
* Fewer complex multi-step process documentation pages/steps required

**Comment by alanna** [comment]
Are we going to have some kind of retro? How successful were we at improving this area?
