### ISSUE TITLE
Can't reset the location of an event

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5490]
**To Reproduce**
1. Create an event with a location
2. Go to Event's admin
3. Remove the location
4. Save & refresh
5. See issue: location's still there

**Expected behavior**
- Location should be removed
- Ideally, there should be a little cross to directly remove the value from the input

**Comment by snitin315** [comment]
@Betree Can this be a bounty?

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by Betree** [comment]
:trophy: This issue has been completed by @snitin315  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
