### ISSUE TITLE
Add Sort by `Relavancy` to `/search` page

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5492]
This is with regard to the discussion at, https://github.com/opencollective/opencollective/issues/4295#issuecomment-1109585001. 

It was decided to add sort by `Relavancy` back to the `/search` page. This could overcome problems such as the one mentioned, https://opencollective.slack.com/archives/C035S573ZD2/p1650703042630149 and https://opencollective.slack.com/archives/C035S573ZD2/p1650842042673579 and https://opencollective.slack.com/archives/C035S573ZD2/p1650849511764859 since the `ACTIVITY` sort do not sometimes get the most relevant results on top.

**Comment by Betree** [comment]
Which one should be the default, relevancy or activity?

**Comment by SudharakaP** [comment]
> Which one should be the default, relevancy or activity?

At the moment we are not changing the default; so we are keeping activity as the default. I had the same question here; https://opencollective.slack.com/archives/D01EA8GBHEZ/p1651000482477979?thread_ts=1650998928.592899&cid=D01EA8GBHEZ.

**Comment by Betree** [comment]
> [om/archives/D01EA8GBHEZ/p1651000482477979?thread_ts=1650998928.592899&cid=D01EA8GBHEZ](https://opencollective.slack.com/archives/D01EA8GBHEZ/p1651000482477979?thread_ts=1650998928.592899&cid=D01EA8GBHEZ).

This link doesn't seem to work for me, maybe a channel I don't have access to?

**Comment by SudharakaP** [comment]
> > [om/archives/D01EA8GBHEZ/p1651000482477979?thread_ts=1650998928.592899&cid=D01EA8GBHEZ](https://opencollective.slack.com/archives/D01EA8GBHEZ/p1651000482477979?thread_ts=1650998928.592899&cid=D01EA8GBHEZ).
> 
> This link doesn't seem to work for me, maybe a channel I don't have access to?

Ops, this was discussed on a private thread with Francois. Anyways, the idea is keeping the default and only add the "relavancy" filter so that issues like this, https://opencollective.slack.com/archives/C035S573ZD2/p1650850178795839. I think in the future we can look into modifying the activity sort to include some frequency measurement as suggested there. But I think for now we are just adding the relevancy filter. 🤔
