### ISSUE TITLE
Problem with searching for organizations under source of funds

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#5493]
**Describe the bug**
There is a problem I am encountering when looking to add funds to a collective and searching for an organization that I know is already been set up. Seems to be related [to this project.](https://github.com/opencollective/opencollective/issues/4295#issuecomment-1110352649)

**To Reproduce**
I recorded [this short video](https://www.loom.com/share/75496465cf4e48ab83a50792305ada34) explaining the flow and the current workaround. 

**Expected behavior**
The name of the organization should come up based on a straightforward input without defaulting the actual slug. In addition, the returned results I see don't really contain the same naming convention so it doesn't look right. 

**Additional context**

  P3 high frequency, low impact

**Comment by Betree** [comment]
@SudharakaP In https://github.com/opencollective/opencollective-api/blob/a040002397238845fcfeff495d2f2b8d3fd47b71/server/lib/search.js#L198, it seems that we're defaulting to sort by `createdAt`. Can we move that back to sort by relevancy by default?
GQLV1's `search` doesn't provide an `orderBy` arg, so we introduced a regression on the collective picker with this default `createdAt` sort by.
