### ISSUE TITLE
Bill to entity should never be hosted Collective

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5495]
In the transaction mentioned in #5494 the receipt was issued with a hosted Collective as the `bill to` entity. This should never happen, as it has no legal status, and this is not a valid receipt. The correct `bill to` entity for a contribution from a Collective is the host (ideally with reference to the payer Collective).

![Screen Shot 2022-04-27 at 5 23 53 PM](https://user-images.githubusercontent.com/5498878/165447147-e479222f-13af-4f19-83ba-82fdccb86904.png)

**Comment by jfdh** [comment]
@alanna I am opening a new issue for this because we actually need the invoice to be "bill to" the collective under OC Europe.
