### ISSUE TITLE
Wrong message for Fiscal Hosts looking into deletion

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5497]
<img width="771" alt="Screenshot 2022-04-28 at 09 16 17" src="https://user-images.githubusercontent.com/806/165698214-cbeded35-255c-47bb-a879-15bc361adf57.png">

The message about "Independent Collective" is false and the directions inappropriate.

Broken in https://github.com/opencollective/opencollective-frontend/pull/7014

**Comment by znarf** [comment]
@SudharakaP Seems you implemented the new wording without considering regression for Fiscal Hosts.

**Comment by SudharakaP** [comment]
@znarf : Sorry, I am a bit lost on why you think the directions are inappropriate? This message only appears if the collective is self hosted and the wording is as suggested here; https://github.com/opencollective/opencollective/issues/4831#issue-1027232106. 🤔

**Comment by znarf** [comment]
@SudharakaP The screenshot features a Fiscal Host, an Organization, not an independent collective. This is not working.
