### ISSUE TITLE
Show order IDs in transactions list

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5499]
**User story**
As a member of the support team, I often get messages from users who screenshot transactions. We then have to look for these transactions using approximate queries, which is tedious and can lead to errors if two of them are very similar.

**Proposed solution**
A small change could really help: show the unique ID of the item (here, the Order ID):
![image](https://user-images.githubusercontent.com/1556356/165717423-cbc959b9-821f-4815-b00d-2a304cd6cd01.png)

We already do that in the expenses list, so that would make things consistent:
![image](https://user-images.githubusercontent.com/1556356/165717539-54697c39-c908-49a7-bdb8-297d1cdf733d.png)

Ping @aminakazi since you recently worked on this
Ping @znarf since you had concerns with exposing numerical IDs in the past

**Comment by znarf** [comment]
Auto-increment ids should generally be avoided. But if we don't have a strong alternative or if this is making things difficult, let's not make it a strict rule and we can continue using them where it make sense.

**Comment by aminakazi** [comment]
I like the approach of showing the numerical ID of the expense. One question though, how many characters is it usually? 4-5 digits?

**Comment by Betree** [comment]
> I like the approach of showing the numerical ID of the expense. One question though, how many characters is it usually? 4-5 digits?

@aminakazi  It's an auto-increment, the current max for orders is `538771` and `76141` for expenses.

**Comment by Betree** [comment]
This would really save me time with support work on a day-to-day basis.

**Comment by Betree** [comment]
Pushed a mini-update for that in https://github.com/opencollective/opencollective-frontend/pull/8064. The expenses/orders lines now look more consistent.

![image](https://user-images.githubusercontent.com/1556356/182588634-b59df2a3-cb19-4c30-b769-fc588590a193.png)
