### ISSUE TITLE
Missing donations

### ISSUE THREAD

**Issue by stevenwadejr** [opencollective/opencollective#550]
In our [latest event](https://opencollective.com/upstatephp/events/level-up-with-pipelines-206ev) (October 19th, 2017), we had a free ticket tier and a donation tier. Registration was plagued by errors during sign-up. We had two members attempt to register and donate.

[Jim Ciallella](https://opencollective.com/jimciallella) tried 3 times to register and donate $5. He continued to get a GraphQL error during registration but has since reported that all 3 $5 charges have hit his account. However, these funds are not showing in the collective's account.

[Nathan Morgan](https://opencollective.com/fuelingtheweb) experienced a similar issue. He's reported to us both of his attempts going through, for a total of $10 - when it was originally meant to be $5. These funds are not showing in the collective's account: ![](https://d1ax1i5f2y3x71.cloudfront.net/items/0W16152k0c0K2z3m0Y2Y/Image%202017-10-23%20at%203.39.04%20PM.png?X-CloudApp-Visitor-Id=1912034)
***

URL: https://opencollective.com/upstatephp/transactions
Logged in as: stevenwadejr
Error message if any: No error message
Expected result: 2 donations should have succeeded totaling $10 and be in the account of UpstatePHP
Browser: Chrome

**Comment by piamancini** [comment]
@xdamman this is probably related to #548

**Comment by asood123** [comment]
Need to add those transactions manually. Bigger question is why is this happening?

**Comment by xdamman** [comment]
@stevenwadejr sorry about this bad experience. But thanks for taking the time to report those issues.

I've looked up those transactions in Stripe and added them manually.
You can see them here: https://opencollective.com/level-up-with-pipelines-206ev/transactions

I still need to investigate why they weren't recorded in the first place. Most likely related to the event type of collective.

Note to ourselves @piamancini @asood123:
Those transactions are recorded in a separate ledger dedicated to the event.
We should add in the interface an option to transfer the balance to the parent collective and / or file expenses against that balance.

**Comment by stevenwadejr** [comment]
@xdamman Thanks for looking into this, but I don't think it's been properly fixed. That event is an event of an existing collective, UpstatePHP, and not its own collective. The event page is here - https://opencollective.com/upstatephp/events/level-up-with-pipelines-206ev - which shows it nested under the "upstatephp" collective.

The funds you added manually as mentioned above are not reflecting in the balance of the collective's main account. 

This seems to be a problem related to a recent upgrade of your system. Our previous event was in August (found here - https://opencollective.com/upstatephp/events/2017-august) and one of our members, Amy Bianco, donated directly to the event and as you can see from the screenshot below, the funds were added to our collective, not a sub-event-collective.

![](https://d1ax1i5f2y3x71.cloudfront.net/items/0a0Q1X0G0c221r3w2v20/%5B45125d004910867cbf666c7ab2073063%5D_Image%25202017-10-24%2520at%25209.40.07%2520AM.png?X-CloudApp-Visitor-Id=1912034)

**Comment by xdamman** [comment]
I know, that's what I was referring to at the bottom of my comment.

There is an argument to be made that an event should have its own budget. It would be nice to be able to look back at any event and see the donations and expenses for it and then bring the balance back to the main collective.

That was the intent with the v2. But we don't have all the pieces yet.
Either we make it easy to bring back the balance to the main collective or we consider all donations to an event to go directly to the main collective.

In the meantime, I can manually move the balance of that event to your main upstatePHP collective.

**Comment by asood123** [comment]
Here's the error that caused missing donations @xdamman. There is now a host. We shouldn't allow people to sell tickets without a host.

```
856684679699542024	2017-10-16T20:46:06	2017-10-16T20:46:06Z	138220813	opencollective-prod-api	50.17.122.119	Local7	Info	app/web.1	>>> createOrder mutation error:  Error: Cannot create a transaction: collective id 8957 doesn't have a host
856684679699542026	2017-10-16T20:46:06	2017-10-16T20:46:06Z	138220813	opencollective-prod-api	50.17.122.119	Local7	Info	app/web.1	    at /app/dist/models/Transaction.js:346:15
856684679699542027	2017-10-16T20:46:06	2017-10-16T20:46:06Z	138220813	opencollective-prod-api	50.17.122.119	Local7	Info	app/web.1	    at tryCatcher (/app/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
856684679699542028	2017-10-16T20:46:06	2017-10-16T20:46:06Z	138220813	opencollective-prod-api	50.17.122.119	Local7	Info	app/web.1	    at Promise._settlePromiseFromHandler (/app/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
856684679699542030	2017-10-16T20:46:06	2017-10-16T20:46:06Z	138220813	opencollective-prod-api	50.17.122.119	Local7	Info	app/web.1	    at Promise._settlePromise (/app/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
856684679703736325	2017-10-16T20:46:06	2017-10-16T20:46:06Z	138220813	opencollective-prod-api	50.17.122.119	Local7	Info	app/web.1	    at Promise._settlePromise0 (/app/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
856684679703736326	2017-10-16T20:46:06	2017-10-16T20:46:06Z	138220813	opencollective-prod-api	50.17.122.119	Local7	Info	app/web.1	    at Promise._settlePromises (/app/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:693:18)
856684679703736327	2017-10-16T20:46:06	2017-10-16T20:46:06Z	138220813	opencollective-prod-api	50.17.122.119	Local7	Info	app/web.1	    at Async._drainQueue (/app/node_modules/sequelize/node_modules/bluebird/js/release/async.js:133:16)
856684679703736328	2017-10-16T20:46:06	2017-10-16T20:46:06Z	138220813	opencollective-prod-api	50.17.122.119	Local7	Info	app/web.1	    at Async._drainQueues (/app/node_modules/sequelize/node_modules/bluebird/js/release/async.js:143:10)
856684679703736332	2017-10-16T20:46:06	2017-10-16T20:46:06Z	138220813	opencollective-prod-api	50.17.122.119	Local7	Info	app/web.1	    at Immediate.Async.drainQueues (/app/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
856684679703736333	2017-10-16T20:46:06	2017-10-16T20:46:06Z	138220813	opencollective-prod-api	50.17.122.119	Local7	Info	app/web.1	    at runCallback (timers.js:781:20)
856684679703736334	2017-10-16T20:46:06	2017-10-16T20:46:06Z	138220813	opencollective-prod-api	50.17.122.119	Local7	Info	app/web.1	    at tryOnImmediate (timers.js:743:5)
856684679821176839	2017-10-16T20:46:06	2017-10-16T20:46:06Z	138220813	opencollective-prod-api	50.17.122.119	Local7	Info	app/web.1	    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by stevenwadejr** [comment]
Will the event funds be moved to our collective at all? How do we get the funds that were donated to the event?

**Comment by asood123** [comment]
Hi @stevenwadejr, sorry for delay in giving you access to the funds. We are working on automating this step. I credited your collective with the funds ($20.25 - after removing fees).

**Comment by asood123** [comment]
Closing this, please let us know if you need anything else.

**Comment by stevenwadejr** [comment]
👏
