### ISSUE TITLE
Confusing error message 'no payment method avialable' when contributing using a Collective balance between hosts

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5504]
**Describe the bug**
When contributing to Collectives I can select my Collective/Fund as the payment method if the Collective receiving my contribution is using the same host.  If the Collective is on a different host I get a confusing error message 

> No payment methods available 

The problem is in fact that the payment method is not available for *this particular transaction* because of the situation described. This is confusing and we can do a better job by providing a more accurate error message:

> The payment methods below are unavailable for this transaction

With the Collective balance greyed out (but present)

**To Reproduce**
Create a collective hosted by host X
Create a collective hosted by host Y
Add a positive balance to collective hosted by X
Contribute to collective hosted by Y from X
Select Collective X as contributor, click next
... Profit.

![Screenshot 2022-04-29 at 10 04 13](https://user-images.githubusercontent.com/158833/165917212-31bced8d-f16f-40e8-8483-edcf8bccf487.png)

**Expected behaviour**
I should be aware that my balance cannot be used for this particular transaction. 
I should be directed to contribute using another payment method (Card, PayPal, bank transfer)

**Triage**
P2 low frequency, high impact

**Comment by SudharakaP** [comment]
This we have worked previously and a bit of a complicated issue to solve completely I believe. For further clarification refer; https://github.com/opencollective/opencollective/issues/4669#issuecomment-920799739. I would close this and track this in the other issue; but if you feel there's anything different between this and that issue feel free to re-open. 🙂
