### ISSUE TITLE
Unable to differentiate receipts in expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5507]
## Who is your user?
Expense submitter

## What are they trying to achieve?
When submitting an expense with multiple receipts, I want to be able to differentiate the files, so that I can add the correct amount and description info to each.

This is what it looks like if you upload multiple files at once. How am I supposed to know which is which?

![Screen Shot 2022-05-02 at 1 04 50 PM](https://user-images.githubusercontent.com/5498878/166172984-d98689ed-1599-40e0-a881-46777fddc46e.png)

## How are they currently doing this?
Either randomly assuming a given line item is a given receipt, or doing them one and a time which defeats the point of milti-file upload. 

  P3 high frequency, low impact

**Comment by Betree** [comment]
The way to achieve that is to click on the attachment itself. It opens a new tab with the file, making it clear what is what.

Maybe we need a second textual call to action, like "View file" to make this explicit.

**Comment by Betree** [comment]
Related: #4993

**Comment by alanna** [comment]
Oh I would never have guessed that from the interface. If it could show a
file preview and the filename in the expense view that would be even better!

**Comment by Betree** [comment]
Ping @opencollective/design

**Comment by aminakazi** [comment]
When we had initially redesigned the 'Submit Expense' pages, we had designed for this use case by showing the thumbnail preview of the receipt with a 'replace' text button. ([View Design](https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/?node-id=15463%3A208879))

<img width="398" alt="Screenshot 2022-05-04 at 6 01 12 PM" src="https://user-images.githubusercontent.com/48468919/166681622-0ae5d3a9-2709-43a4-8c53-5d7f4ec96747.png">


In hindsight:
A. The thumbnail image could be clickable which would show the expanded preview and the replace text button separately clickable to enable replacing the file. OR
B. We could remove the 'replace' text button to something like 'edit' which would then allow the user to preview and replace the file if needed.

I'll create the designs for both these flows IF it is _**technically possibly to show the thumbnail image**_ @Betree

**Comment by alanna** [comment]
related #5964

**Comment by gustavlrsn** [comment]
The attachment preview now shows a thumbnail image like the design above, closing this.
