### ISSUE TITLE
Allow fiscal host to choose where to "Bill To" automatic invoices

### ISSUE THREAD

**Issue by jfdh** [opencollective/opencollective#5516]
## User story 

As a host admin, I wanna be able to choose that all automated invoices are "Bill To" the collective itself and one of its admin, and not to the fiscal host.

This issue is basically the opposite of #5495 raised by Alanna. OCF and OC Europe have different needs on this point.

## Best solution for this problem

Add a host setting to allow the host to have only automated invoices "Bill To" the collective.

- Automated invoices can be "Bill To" the fiscal host (including address, tax number); or
- Automated invoices can be "Bill To" the collective (including address, tax number)

  **P1 high frequency, high impact**

**Comment by BenJam** [comment]
- [ ] @Betree to iterate on feedback and merge this week
