### ISSUE TITLE
Automatically suggest & autocomplete tags in `StyledInputTags` component

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5523]
This was suggested at, https://github.com/opencollective/opencollective/issues/4764#issuecomment-1116770633 

Currently when creating a new tag the user won't be notified if there's similar tags. For example if the user misses that we have a tag called `open source` they might create another tag called `open-source` or `openSource` etc which result in duplicate tags. 

Ideally we should search for existing tags when the user types on the tag creation input and then show similar tags (partial matches, ignoring punctuation and accents) and let the user choose that tag if they wish. 

We already have the `TagStatsCollectionQuery` on the API side so what we need to do is, 

- Whenever the user types something on the tag creation input we query the tags based on that term and show all the tags that is returned in the tag dropdown. 

cc: @Betree

**Comment by gustavlrsn** [comment]
Updating the title for the issue to also include suggested tags (based on popularity) before typing something in and starting to filter down, something like this:

<img width="560" alt="image" src="https://user-images.githubusercontent.com/1552194/212692221-ac73f307-9066-4b21-956b-7d35af8743ea.png">

**Comment by gustavlrsn** [comment]
To make this query performant, I'm thinking we want to use a Materialized view that returns tags sorted by their count. The current `TagStatsCollectionQuery` is looking through all Collective's to unnest tags, a quite expensive query to do in an autocomplete field.

**Comment by Betree** [comment]
Sounds like a very good use case for materialized views, especially since we really don't need fresh data.
