### ISSUE TITLE
Allow Host to turn on or off expense type(s) for Collectives

### ISSUE THREAD

**Issue by natehn** [opencollective/opencollective#5525]
This would be useful for Model C fiscal sponsorship,where the fiscal sponsor makes grants to another entity over and over again - unlike Model A (like the fiscal sponsorship OCF and OSC do) where the Collective becomes legally part of the Host.

## User story 
As a Model C fiscal sponsor (note: I spoke to one today) I would like to be able to turn off certain expense types (i.e., Invoice, Reimbursement, or Grants, or some combination of them).

In the case of the sponsor I spoke with today, it would be useful to be able to turn off both Invoice and Reimbursement expenses, so that only Grant expenses can be submitted to their collectives. From personal experience, I know that other Model C fiscal sponsors would want to only turn off Invoice expenses.

## Best solution for this problem
It would be nice to have a default setting for the Host's Collectives, but see MVP below for something that meets the main need.

## MVP
Checkboxes on the Host's Admin "Hosted Collectives" page for all three expense types, so that all can be turned on or off.

I think the setting should also be passed on to Collectives' Projects, though there is room for discussion on this.

## Metrics 
Increase in number of Model C fiscal sponsors, which are a significant portion of fiscal sponsors in the USA.

**Comment by alanna** [comment]
@natehn I've slightly updated this to make it more general. There are lots of potential applications for a Host turning on and off expense types. What we've learned from #5395 #5093 #4940 #4741 is that Hosts need to be able to turn these settings on and off for many reasons. I think a more general feature is not significantly more complex and will open up more functionality for different Hosts.
