### ISSUE TITLE
Add more tests to `searchCollectivesInDB` function

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5530]
Recently the `searchCollectivesInDB` function was changed since we added new filters in the [Search Experience Redesign](https://github.com/opencollective/opencollective/projects/71) project. We could add more tests for this function particularly around, 

- [x] Make sure the type filtering works correctly as expected.
- [x] Make sure the tag filtering works as expected.
- [x] Make sure the country filter works as expected (done at, https://github.com/opencollective/opencollective-api/pull/7455).

**Comment by Betree** [comment]
Seems all done
