### ISSUE TITLE
Add 'unfreeze' button to banner

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5540]
When a Collective is frozen, it would be nice for the host admin to be able to unfreeze it from the banner
![Screen Shot 2022-05-10 at 8 53 07 AM](https://user-images.githubusercontent.com/5498878/167496940-348a37f4-2fd0-431f-b677-82f6ac962e3d.png)

**Comment by scenaristeur** [comment]
Hi, i could be interested with a bounty for that issue, if someone could tell me what role can freeze/ unfreeze a Collective. Is it a the admin level? The host? 
Thxs

**Comment by alanna** [comment]
It's done only by the host admin

@Betree can this be a bounty?

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted, and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

@scenaristeur As you requested first, feel free to assign yourself the bounty if you're interested in it.

**Comment by Betree** [comment]
To freeze a collective: Go to the [host admin dashboard](https://docs.opencollective.com/help/fiscal-hosts/fiscal-host-dashboard#edit) > Hosted Collectives, then click on More Actions > Freeze

![image](https://user-images.githubusercontent.com/1556356/182782589-86ffb669-10f7-4068-813d-ed9340dfe2c8.png)

**Comment by scenaristeur** [comment]
seems too late, @leonardohofling is on fire !

**Comment by Betree** [comment]
@scenaristeur My bad, I should have assigned you when I created the bounty. Sorry about that.

**Comment by leonardohofling** [comment]
> seems too late, @leonardohofling is on fire !

@scenaristeur it's yours

**Comment by scenaristeur** [comment]
as i understand the issue, a solution could be to get the code of the button in the edit-collective/Form edit-collective/actions/Archive.js
https://github.com/opencollective/opencollective-frontend/blob/ee98f60d0f2599eb041adcad08658583de6b4f70/components/edit-collective/actions/Archive.js#L176

and put it somewhere in Notification at https://github.com/opencollective/opencollective-frontend/blob/ee98f60d0f2599eb041adcad08658583de6b4f70/components/NotificationBar.js#L180 and only if isHostAdmin

What solution do you prefer in general for this kind ? 
should we import Archive.js

```
{status === 'collectiveArchived' && (
  <Archive collective={collective} />
)}
```
and hide the title with specific parameter or create a new component with the button and modal ?

**Comment by scenaristeur** [comment]
A new component "RemoveArchive" or "UndoArchive" used in both location ?

**Comment by Betree** [comment]
@scenaristeur You're confusing "Archiving" (a collective admin action to archive their collectives) and "Freezing" (a host action to temporarily freeze collectives and prevent them from doing any action on the platform, This issue is about having an "Unfreeze" button, we don't want to touch the archive feature.

**Comment by snitin315** [comment]
@scenaristeur are you still working on this? If not, I would like to take this up.

**Comment by scenaristeur** [comment]
@snitin315 I'm on the run for another thing yet, you can take it

**Comment by leonardohofling** [comment]
I was waiting for that also, but ok.

> @scenaristeur are you still working on this? If not, I would like to take this up.
