### ISSUE TITLE
onboarding a repo failure 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#555]
Thank you for taking the time to report an issue 

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: From user: "Here is the [URL](https://opencollective.com/opensource/apply/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6ImNvbm5lY3RlZC1hY2NvdW50IiwiY29ubmVjdGVkQWNjb3VudElkIjoxNTk3LCJ1c2VybmFtZSI6IkRhbmVFdmVyaXR0IiwiaWQiOjg0MTcsImVtYWlsIjoiZGFuZUBkYW5lZXZlcml0dC5jb20iLCJpYXQiOjE1MDg4MTQxOTEsImV4cCI6MTUwODkwMDU5MSwiaXNzIjoiaHR0cHM6Ly9hcGkub3BlbmNvbGxlY3RpdmUuY29tIiwic3ViIjo4NDE3fQ.v6o-4DL8pLIs0u3d9WxgXOburpJVs-rebvcKuStbmbA) I was using when trying to signup. Its the 3/3 page “Why do you want to create a collective."

Error message if any: Create Group from Repo Failure

Created several duplicate collectives: Panel 

Expected result: onboard repo

Browser:

Bonus point if you can add a screenshot :-)

<img width="1548" alt="image 2017-10-23 at 22 05 39" src="https://user-images.githubusercontent.com/3671070/31953184-8a6e7b16-b8b0-11e7-9f13-c6d02770a59f.png">

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by piamancini** [comment]
@asood123 they tried again, still failing. Might be an issue with the slug?
their repo is a slug that already exists. 
<img width="1542" alt="screen shot 2017-10-24 at 23 49" src="https://user-images.githubusercontent.com/3671070/31997494-29a6a8ee-b95a-11e7-90d1-0be1c2000b09.png">

**Comment by piamancini** [comment]
@asood123 same issue reported here https://github.com/opencollective/opencollective-website/issues/772

**Comment by VermontResilienceLab** [comment]
Hi - we got issue on 1st stage for https://github.com/VTResilienceLab/oscurrency
![screenshot-opencollective com-2017-11-01-13-39-02](https://user-images.githubusercontent.com/5089742/32288443-586c23ce-bf0a-11e7-83f0-841c9965b710.png)

Thanks!

**Comment by piamancini** [comment]
@VermontResilienceLab thanks! We are working on fixing this. 
QQ did you try doing it from an account who has merging rights to the repo?

**Comment by piamancini** [comment]
also here: https://github.com/opencollective/opencollective/issues/546

**Comment by piamancini** [comment]
just to keep track of them
https://opencollective.com/react-native-firebase-209
https://opencollective.com/react-native-firebase-823
https://opencollective.com/react-native-firebase-802

**Comment by asood123** [comment]
Fixed. I'm working through already created duplicate collectives to delete all but one of them for each case.

**Comment by asood123** [comment]
Most people who hit this issue shouldn't have to sign up again - we'll be sending out emails and PRs when the collectives are ready to be used.
