### ISSUE TITLE
Collective webhook embed in Discord formats the link incorrectly 

### ISSUE THREAD

**Issue by connorhsm** [opencollective/opencollective#5552]
**Describe the bug**
A Collective's webhook embed link is incorrectly formatted, causing the link to be incorrect.

**To Reproduce**
1. Create a new webhook link in Discord and append `/slack` for compatibility.
2. Add new webhook to a Collective, with the link just created.
3. Trigger an event, such as a new financial contribution being made or a new expense submit.
4. Observe the webhook firing and appearing in Discord with an embed (Screenshot 1)
5. Click link in the message text, observe the link functions correctly. (Screenshot 2)
6. Click link in the embed, observe the error as you are presented with a 404 page. (Screenshot 3)

The expected link is: https://opencollective.com/twohoursonelife
The link that occurs depends on the message in the text, the incorrect link I have observed to appear as:
- https://opencollective.com/twohoursonelife):
- https://opencollective.com/twohoursonelife)!

This depends on the different text for different events.

**Expected behavior**
The Discord embed should link to the Collective home page without the following characters.

**Screenshots**
Screenshot 1
![image](https://user-images.githubusercontent.com/20902771/168200999-01c0bca0-5605-48af-82ab-adaab1ad49d0.png)

Screenshot 2
![image](https://user-images.githubusercontent.com/20902771/168201081-3e60fd92-ebac-4451-8f20-05cbd6973dfc.png)

Screenshot 3
![image](https://user-images.githubusercontent.com/20902771/168201100-d6320169-3497-4514-aa0b-01085da2965d.png)

**Desktop:**
 - OS: Windows
 - Browser: Firefox
 - Version: 100.0

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
Hi @connorhsm, thanks for documenting this issue.

The code that generates the message: https://github.com/opencollective/opencollective-api/blob/main/server/lib/activities.js#L18. It's tested in https://github.com/opencollective/opencollective-api/blob/main/test/server/lib/activities.test.js.

So far the tests seem to be passing and I don't think we changed this code recently. Could be an issue with how we're handling some special characters, or a change in the discord slack webhook adapter.

**Comment by VaclavElias** [comment]
We also have the same problem in our Discord https://opencollective.com/stride3d in the #sponsors channel (contributors section)

<img width="437" alt="image" src="https://github.com/opencollective/opencollective/assets/4528464/b6583fde-17c9-49ed-941c-651e94bbb8dc">

**Comment by Asartea** [comment]
This seems to be a upstream Discord bug; can reproduce it with any link (that will generate an embed) by putting it in the format `[text](link)!`![Screenshot_20231227_014553_Discord.jpg](https://github.com/opencollective/opencollective/assets/76259120/16b4c92c-c482-4764-aa47-888b20efc361)

![Screenshot_20231227_014521_Discord.jpg](https://github.com/opencollective/opencollective/assets/76259120/3c584af5-9fdf-4f26-bea6-d6f98fa21b77)

![Screenshot_20231227_014537_Discord.jpg](https://github.com/opencollective/opencollective/assets/76259120/df824b0d-4f48-49ea-8e27-fd26adef8f91)

**Comment by connorhsm** [comment]
Nice catch, I can confirm the above behaviour. Although, I did find that a link like https://github.com/ that would usually produce an embed, would not produce an embed under the above circumstances.

I'd be happy for this to be closed, unless OC wishes to attempt to avoid the bug or track until Discord resolves.

**Comment by Betree** [comment]
Thanks for sharing, @Asartea! As a quick fix, [I'm removing](https://github.com/opencollective/opencollective-api/pull/9638) the `!` at the end of our Webhook messages - they're not really important anyway.
