### ISSUE TITLE
Rename `useUser` to `useLoggedInUser`

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5571]
- Clearer name
- Consistency with `withLoggedInUser`

**Comment by Betree** [comment]
cc @kewitz since you implemented this initially, there may have been a reason for calling it this way

**Comment by la-costa** [comment]
Hi @Betree 

I analyzed the issue, can you confirm if the requirement is just to rename the method?

In addition to the documents on the site (Contributing / Development ), which ones do you recommend reading for the first contribution?

**Comment by kewitz** [comment]
@Betree no specific reason, I was just keeping it short.

@la-costa, I can confirm this is just renaming the method.
I recommend:
  1. reading our RFCs at https://github.com/opencollective/opencollective/tree/main/rfcs
  2. relevant .md files in the repo you're updating, in this case, it is only `opencollective-frontend`.

**Comment by kewitz** [comment]
@la-costa I would also move this hook to a dedicated file in `lib/hooks` folder.
Let me know if you want to take this on and I'll assign you to this issue.

**Comment by la-costa** [comment]
Hi @kewitz 

If you can assign me the issue, I would appreciate it.

It's a small, but a good starting point to get to know more the project.
