### ISSUE TITLE
Show the User Profile Creation and Organization Creation As Seperate Pages

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5573]
Part of https://github.com/opencollective/opencollective/issues/5399

Currently when the [user joins the platform](https://staging.opencollective.com/create-account) we have two options; 

1) Creates a personal profile.
2) Creates an organizational profile along with the personal profile

In the new design we change these to a two step process. When visiting the `/create-account` page the user is only shown the personal account creation page; 

![image](https://user-images.githubusercontent.com/12435965/169272567-193816bd-58af-4066-a1eb-28b852ae54b1.png)

After creating the personal profile the user can then choose to create a collective or organization using,

![image](https://user-images.githubusercontent.com/12435965/169308030-1848ee77-a92e-4ee1-9017-8a4ead3fa988.png)

Steps to achieve this; 

- [ ] Change the current personal profile creation page to the new design; https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab-%F0%9F%A7%AA?node-id=15427%3A204923
- [ ] Split the organizational profile creation into two pages; https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab-%F0%9F%A7%AA?node-id=15514%3A227583

Migration Steps: 

- [ ] Make sure to keep this under a seperate URL (`/create-accountV2`) until we deprecate the older `create-account` pages.

**Comment by Betree** [comment]
**Additional specs**
- [ ] When switching between org and personal profile, the info already filled in should be carried over

**Questions:**
- What happens when users click "Create an account and continue"?

**Comment by SudharakaP** [comment]
> What happens if the email already exists?

If the email exists we will show the same error as we show now,

![image](https://user-images.githubusercontent.com/12435965/169281882-c6b0bc0f-3180-4c93-91c6-87d22fa2ad43.png)

> What happens when users click "Create an account and continue"?

We will redirect them to the success page just like we do now for both personal and organizational profile creation flows.

**Comment by Betree** [comment]
> If the email exists we will show the same error as we show now,
> 
> ![image](https://user-images.githubusercontent.com/12435965/169281882-c6b0bc0f-3180-4c93-91c6-87d22fa2ad43.png)

But there's no sign-in link on this page, how are we guiding users to the sign-in page?

**Comment by Betree** [comment]
@opencollective/design can you provide some guidance to @SudharakaP regarding https://github.com/opencollective/opencollective/issues/5573#issuecomment-1131602335?

**Comment by SudharakaP** [comment]
> @opencollective/design can you provide some guidance to @SudharakaP regarding [#5573 (comment)](https://github.com/opencollective/opencollective/issues/5573#issuecomment-1131602335)?

Just for the record, this was addressed as now with the new designs there's a back button.
