### ISSUE TITLE
Use new Typescript helpers in sequelize models

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5575]
Since Sequelize 6.14.0 we have [some new helpers](https://sequelize.org/docs/v6/other-topics/typescript/) to define sequelize models that drastically reduce the amount of boilerplate:

```es6
import { Model, InferAttributes, InferCreationAttributes, CreationOptional } from 'sequelize';

// order of InferAttributes & InferCreationAttributes is important.
class User extends Model<InferAttributes<User>, InferCreationAttributes<User>> {
  // 'CreationOptional' is a special type that marks the field as optional
  // when creating an instance of the model (such as using Model.create()).
  declare id: CreationOptional<number>;
  declare string: number;
  // other attributes...
}
```

This should become the default for all new models. We also want to update `docs/adding-new-models.md`.

**This should be tackled after https://github.com/opencollective/opencollective/issues/5099#issuecomment-1131297186.**

**Comment by ephys** [comment]
If you have any comments on our new helpers, we'll be very happy to hear them! We're looking for as much feedback as possible before turning them on by default in a future major release
