### ISSUE TITLE
Move or remove more actions button on submit expense step

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5578]
On mobile i was submitting an expense and got to the summary screen, scrolled down (it's a long page) and saw this

![Screenshot_20220520-182445.png](https://user-images.githubusercontent.com/5498878/169466367-a6bcfc10-e222-4e1f-892d-1a80fc8aeb53.png)

Clicking 'more actions' only shows 'copy link' but the real action button 'submit' is far below. I almost thought I didn't need to click something else to be considered submitting, or that it was broken.

I think it's unlikely someone will really need to copy the link of an expense that hasn't even been submitted yet, and it's confusing to see an actions button that isn't the one you need at this step. So this button should be removed, or at least moved all the way to the bottom of the screen.

**Comment by kewitz** [comment]
Sorry, I missed this detail. The fix is already in production.
