### ISSUE TITLE
Donor can't make a donation: logged in, system prompts her to login again

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#558]
Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***
From user:  

> The donation form beginning is a bit confusing for her: She’s already logged in, but placing her email in the form prompts her to log in again. Is this normal?

URL: https://opencollective.com/buttercup/donate
Logged in as: https://opencollective.com/ida-mitchell
Error message if any:
Expected result: being able to make a donation
Browser:

Bonus point if you can add a screenshot :-)
<img width="1328" alt="pastedgraphic-3" src="https://user-images.githubusercontent.com/3671070/31959680-5bdf7e36-b8c3-11e7-94c3-5194243b1169.png">

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by xdamman** [comment]
Fixed and deployed. 
Note to self: We should add an e2e test for logged in users trying to make a donation to make sure we don't hit such regression again in the future.
