### ISSUE TITLE
[Docs] OAuth beta

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5586]
### Create a OAuth application

There is no web interface yet so use our GraphQL API for this.

You need to be authenticated using an Api Key (personal token). See the following blog post for more information. https://medium.com/open-collective/open-collective-graphql-api-preview-3b42ed1d55ff

```
mutation {
  createApplication(
    application: { name: "My Application", redirectUri: "https//example.com/oauth/callback" }
  ) {
    id
    name
    clientId
    clientSecret
  }
}
```

Note your `clientId` and `clientSecret`.

### Configure OAuth client

- Authorization URL: https://opencollective.com/oauth/authorize
- Token URL: https://opencollective.com/oauth/token
- GraphQL URL:  https://api.opencollective.com/graphql

### Authenticate requests with OAuth Access Token

Use the GraphQL API with an Authorization HTTP header. Replace `{ACCESS_TOKEN}` with the `access_token` retrieved in the OAuth process.

```Authorization: Bearer {ACCESS_TOKEN}```

### Sample  GraphQL query to get information about the authenticated user

```
  {
    me {
      id
      name
      email
      imageUrl
    }
  }
```

**Comment by Betree** [comment]
Docs now published on https://docs.opencollective.com/help/developers/oauth. 

@znarf I think we can now close this issue, especially since the bits about creating an app are now deprecated.

**Comment by znarf** [comment]
Agree!
