### ISSUE TITLE
Tiers should be a "minimum" value

### ISSUE THREAD

**Issue by phated** [opencollective/opencollective#559]
For gulp, we've created a Monthly subscription tier that is $25/month that will result in a donor getting a t-shirt.  We've had someone sign up for that tier so they can receive a t-shirt; however, they had previously said to @piamancini that they wanted to up their donation amount to $100/month.

The current implementation doesn't allow that donor to **both** join the t-shirt tier AND donate $100 per month.  Tiers should allow donors to adjust their amount higher (with the defined amount being the minimum that can be contributed).

**Comment by xdamman** [comment]
Fixed in https://github.com/opencollective/frontend/pull/444
