### ISSUE TITLE
confirm cancellation of expense edit button unclear

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5595]
It's not clear which button to click for your desired outcome here:
<img width="651" alt="Screen Shot 2022-05-27 at 8 06 48 PM" src="https://user-images.githubusercontent.com/5498878/170660378-b218d03f-900f-4f29-988e-808d623c46ea.png">

I suggest:

> Are you sure?
[no, continue editing] [yes, cancel editing]

**Comment by znarf** [comment]
That's indeed confusing, introduced in https://github.com/opencollective/opencollective-frontend/pull/7010
