### ISSUE TITLE
Problems with selecting the contributor profile when adding funds to a collective

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#5599]
When adding funds to a collective (whether through the host admin dashboard or directly from a collective page) and trying to select an existing contributor profile from the list, the first attempt fails, and only upon the second one the selection is successful. [Here is a video to describe the problem](https://www.loom.com/share/574962c1d73c43d7968a43ac491dc93d)

It seems like for some reason the first selection is not recognized and this is a pattern that keeps reoccurring over the last few days.

**Comment by alinamanko** [comment]
After submitting this issue somehow all seems to be working ok, but I wonder if checking what was causing the problem may still be required?

**Comment by Betree** [comment]
We had an update of react-select 6 days ago, so it's very likely related: https://github.com/opencollective/opencollective-frontend/pull/7819

@alinamanko Could you share your browser version? You can get it from there:

![image](https://user-images.githubusercontent.com/1556356/170931223-70fc95ea-5106-41e9-8348-aa3281b46abb.png)

**Comment by znarf** [comment]
I applied the update as tests were passing and it was a minor version. Let's roll back if it's an issue and the fix is complicated.

**Comment by Betree** [comment]
I haven't had the time to look at this yet. I wasn't able to reproduce but we should keep an eye on it.

**Comment by alinamanko** [comment]
@Betree apologies for my late reply - I missed the original notification. This would be through adding funds button [on the admin dashboard](https://opencollective.com/foundation/admin/hosted-collectives) or through a collective page. 

I also noticed that when I use the keyboard to scroll through the results I get, the selection works. However, when I use a mouse it only works upon the second attempt.

**Comment by Betree** [comment]
Could be related with `FocusTrap` as mentioned by @kewitz in https://opencollective.slack.com/archives/C0471HKNW7J/p1675700424281619?thread_ts=1675242218.971939&cid=C0471HKNW7J. 
Maybe we can include react-select's container in containerElements https://github.com/focus-trap/focus-trap-react#containerelements
