### ISSUE TITLE
Show date/name on pending invitation

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5600]
It would be useful to know when I was invited when looking at this view, and while we're at it, who invited me. Could it say "Invited by [person] on [date]"?
![Screen Shot 2022-05-30 at 4 56 33 PM](https://user-images.githubusercontent.com/5498878/170919836-d72d7a80-29ed-4ff0-badd-3db65c487b58.png)

**Comment by Betree** [comment]
- Showing the date is a no-brainer, use the existing `memberInvitation.createdAt`
- We need a new API field for the inviter. I can suggest `memberInvitation.createdByAccount` for consistency with what we do for expenses. Alternative: `memberInvitation.inviter`. cc @znarf if you have a preference on this, I personally have a preference for `inviter` (return type: `Individual`).

**Comment by Appsens** [comment]
I can open a PR _(I used `inviter` for the new field)_ with the following result:
![image](https://user-images.githubusercontent.com/7723240/171750534-ae4ed4b5-ddcb-45b6-9f1b-b5d84eeec84d.png)
Is it what you were expecting ?

**Comment by Betree** [comment]
@Appsens It does, that looks really nice! Could you link the PR here?

**Comment by Appsens** [comment]
I rebased the branch and took into account your remarks (the name of the inviter is now a link to his/her profile).
_Sorry for the delay, I was ill._

**Comment by Appsens** [comment]
I created 2 new PR with the same changes. I probably missed a step when I synced / rebased my fork, sorry.
https://github.com/opencollective/opencollective-api/pull/7640
https://github.com/opencollective/opencollective-frontend/pull/7899
