### ISSUE TITLE
Rename "types" to "CollectiveType" in `constants/collectives`

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5611]
`types` is too generic and we end up importing with an alias in many places:

```es6
import { types as CollectiveType } from '../../constants/collectives';
```

**Comment by kskarthik** [comment]
i guess this is done

**Comment by Betree** [comment]
> i guess this is done

It's not

**Comment by jd-launch-school** [comment]
@Betree Is this what you were thinking? I'll go through the API codebase and replace `types` with `collectiveTypes`. Anything else I should be thinking about?

**Comment by jd-launch-school** [comment]
@kskarthik Are you working on this?

**Comment by kskarthik** [comment]
@jd-launch-school no, you can pick it up
