### ISSUE TITLE
events email feature is broken

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#562]
Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: https://opencollective.com/reconomycop/events/community-wealth-building-models-on-both-sides-of-the-atlantic-781ev

No approved email was received by the ADMIN if the event 
Tried to download csv to send emails manually but  Email column in .cvs is empty (thought this was fixed?)

Logged in as: (just provide your username or the url of your profile)
Error message if any: no
Expected result: 
Browser:

Bonus point if you can add a screenshot :-) I have a screenshot but is has PI, sending it to your slack

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by xdamman** [comment]
Were you logged in?
Emails should only be part of the CSV if you are logged in as an admin of the event.

**Comment by xdamman** [comment]
I just did a test logged in as me on a brusselstogether event and the export CSV worked with the email addresses.

**Comment by piamancini** [comment]
@xdamman do you want to close this then?
I sent you the image without the email addresses to your slack.

**Comment by piamancini** [comment]
happened again: 

This issue is back! 😥 

I just downloaded .cvs from our 3 past events and email column is empty again! I really need this .cvs download to work reliably. Or maybe you could redesign how event participant's email addresses are accessed by OC admins? 

https://opencollective.com/reconomycop/events/impact-781ev 

https://opencollective.com/reconomycop/events/aufruhr-781ev 

https://opencollective.com/reconomycop/events/community-wealth-building-models-on-both-sides-of-the-atlantic-781ev

**Comment by piamancini** [comment]
Made the creator of the collective admin of the event to see if this changes anything.
