### ISSUE TITLE
Don't display previous state after button load

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5627]
This is what it looks like when you click the expense approve button:

![3c1c18b07c13747d8521846e955ebd40](https://user-images.githubusercontent.com/5498878/172480852-713b851e-ca31-44d5-8581-ddd506e1ffe7.gif)

After it loads, it shows `approve` again instead of `paid` and it lags long enough that someone could click again, close the window, or think it failed to work.

Can the loading spinner show until it's ready to display `go to pay` ?

**Comment by Betree** [comment]
This one has been buggering me for some time, somehow our library takes some time to refresh the interface after the cache update. I'm gonna take a first look to try and understand.

**Comment by Betree** [comment]
Interestingly the expenses list doesn't seem to be affected, only the expense page.
