### ISSUE TITLE
Contact form has HTTP 400 error

### ISSUE THREAD

**Issue by JoePfeiffer** [opencollective/opencollective#5633]
**Describe the bug**

**To Reproduce**
1. Go to a collective, for instance https://opencollective.com/asciidoctor/expenses/24010
2. Click on contact button in upper right corner
3. Fill out message form
4. Click on "Contact Collective"
5. Error appears "Response not successful: Received status code 400"

**Expected behavior**
Acknowledgement that message was successfully sent

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/3065196/172680064-a2effcf9-aecc-47ce-af45-87a36e8c3042.png)

**Desktop (please complete the following information):**
 - OS: Debian Linux
 - Browser Firefox
 - Version 91.7.0esr

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
We improved the error message for this form in https://github.com/opencollective/opencollective-frontend/pull/7880, but as far as I'm aware we haven't seen other occurrences of this one. @JoePfeiffer If this is still happening, please share your account with us (support@opencollective.com if you don't want to do it publicly) for a deeper investigation.
