### ISSUE TITLE
Refactor Code for a Better Fix for Profile Menu Dropdown Accessiblity + DOM Nesting

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5637]
Related to the code review comment at, https://github.com/opencollective/opencollective-frontend/pull/7878#discussion_r893111943. 

We need to find a better fix for the accessibility issue of the profile menu drop-down and also fix the DOM nesting issue. 

> Using a `button` as the top container is a bit risky:
>- Cursor is wrong: you get a pointer while not hovering anything
>- DOM nesting: see the console:
>
>```
>next-dev.js?3515:25 Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
>    at button
>    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19811)
>    at _c2 (webpack-internal:///./components/StyledButton.js:57:22)
>    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19811)
>    at div
>    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19811)
>    at Reference (webpack-internal:///./node_modules/react-popper/lib/esm/Reference.js:16:23)
>    at Manager (webpack-internal:///./node_modules/react-popper/lib/esm/Manager.js:13:23)
>    at StyledTooltip (webpack-internal:///./components/StyledTooltip.js:153:183)
>    at div
>    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19811)
>    at ChangelogTrigger (webpack-internal:///./components/changelog/ChangelogTrigger.js:69:22)
>```

**Comment by SudharakaP** [comment]
@Betree : I think we could use a simpler css only approach here by making sure the buttons are not nested within each other; I've opened a PR to demonstrate. Let me know what you think. If you still think we need to use portals let me know and I am willing to change the implementation. 🙂

**Comment by Betree** [comment]
> @Betree : I think we could use a simpler css only approach here by making sure the buttons are not nested within each other

Definitely, whatever we do a button within a button is invalid HTML so we can't stick with that solution.
