### ISSUE TITLE
[Release] Minimum number of admins

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5638]
## Context
Hosts can now request that Collectives signing up have a minimum number of administrators. New Collectives are encouraged to invite admins when joining a host. Hosts can limit the ability for Collectives to accept money until they have the minimum number of admins. 

Project issue: #3593 

### What's being released?

Updated setting for host admins
Updated process for creating and joining hosts
Limits for Collectives not meeting minimum number of admins criteria

### Is this change being released incrementally as a beta? What's the schedule?

Releasing to all hosts who can enable on a case by case basis

### Is this release optional or mandatory?

Optional

### Who does this release impact?

Hosts, collective admins

### When will the project be ready for release?

ASAP

## Product Process
 
- [x] Documentation check
    - [x] host policy https://docs.opencollective.com/help/fiscal-hosts/fiscal-host-settings/policies
    - [x] host application process https://app.gitbook.com/o/-LWSZizNMEjL8_DrMNdF/s/-LWSZizTt4ZC1UNDV89f/~/diff/~/changes/xHPgzRXP5NSalAEwLXmN/collectives/add-fiscal-host
- [x] Release 🔥 post on Open Collective 
- [ ] Announcement (update) for Open Source Collective and Open Collective Foundation when implementing

### Related releases

- two to sign https://opencollective.com/opencollective/updates/two-to-sign-features-on-open-collective

### Release post(s)

https://opencollective.com/opencollective/updates/invite-administrators-when-applying-to-a-host

**Comment by Memo-Es** [comment]
I hope this is the right place to post this update; after undertaking a QA round of the latest design file, some details changed slightly to account for text readability and better spacing/padding. Plus, we can use our updated form components to design consistently going forward. 

These changes don't seem too complex. I really hope someone can do this update soon 😃 At least as a papercut for next sprint

Before (Version in production) | After
-- | --
Settings <img width="1070" alt="Screen Shot on 2022-06-22 at 19-55-24" src="https://user-images.githubusercontent.com/49539954/175184888-a854c367-9fbc-4fd6-9882-ecb6b0e3d3a7.png"> |  <img width="1063" alt="Screen Shot on 2022-06-22 at 19-57-01" src="https://user-images.githubusercontent.com/49539954/175185018-2b980447-02bb-4772-993c-cb5c76890836.png">
  |  Improved spacing. Used updated form fields
Edit member modal <img width="640" alt="Screen Shot on 2022-06-22 at 20-01-57" src="https://user-images.githubusercontent.com/49539954/175185657-7ee482a4-fbf6-4896-a707-c1fae5f45417.png">  |  <img width="524" alt="Screen Shot on 2022-06-22 at 20-02-13" src="https://user-images.githubusercontent.com/49539954/175185698-5ad44456-b9d9-43eb-b49d-6af0e04e5de1.png"> 
  |  Improved vertical spacing. Better text legibility (Help text)
Apply to fiscal host modal ![Annotation on 2022-06-22 at 20-08-11](https://user-images.githubusercontent.com/49539954/175186065-cd86de97-1678-4fe4-98e8-d65d037b24a1.png)  |  <img width="2000" alt="Screen Shot on 2022-06-22 at 20-06-56" src="https://user-images.githubusercontent.com/49539954/175186068-35736c6f-56de-47f6-abfa-ed0798afdf26.png">
  |  Improved text legibility. Improved spacing. Used updated form components

[Figma file in production-ready](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=15981%3A272131)


@kewitz @SudharakaP @aminakazi
