### ISSUE TITLE
Date Filter Auto Reset Dates Incorrectly

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5641]
This is initially reported at, https://opencollective.slack.com/archives/C03AWL58JRM/p1654691282481939 (private channel)

Basically the problem is that when the date filter is used we have some auto reset logic which resets the `from` field if the `to` field is less than that. Here's a demo of that;

https://user-images.githubusercontent.com/12435965/172998653-afb72290-0127-40d7-8e60-c0a843fb9d6d.mp4

Notice that we are trying to set `from: 2022-04-28, to: 2022-04-29`. But as soon as we type, `to: 2022-04-02` before it gets to `to: 2022-04-29` it resets the `from` date. 

Suggested Solution: I am suggesting we remove the auto reset logic and rather handle this simply by showing a small warning message in the dialog beneath the `End date` input; something like `⚠️ End date is less than the Start date`. 

cc: @Betree

**Comment by Betree** [comment]
> Suggested Solution: I am suggesting we remove the auto reset logic and rather handle this simply by showing a small warning message in the dialog beneath the End date input; something like ⚠️ End date is less than the Start date.

Sounds good to me
