### ISSUE TITLE
[Release] OAuth Applications 

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5643]
## Context

We're adding OAuth application support for integrators/developers to create applications that perform actions on behalf of users. 

**Project issue:** https://github.com/opencollective/opencollective/issues/1660

### What's being released?

OAuth application support, authorization management, access token generation, management and usage through the API. 

### Is this change being released incrementally as a beta? What's the schedule?

Incremental, closed beta.

### Is this release optional or mandatory?

Optional

### Who does this release impact?

Integrators/developers and (later) users

### When will the project be ready for release?

End of Q2S2 (mid July)

### Overview

- [x] communicate to integrators who have asked for this (MetaGov, CoBudget)
- [ ] Short post on blog calling for integrator to contact us
- Add access to individual accounts
- Feedback and learn

### Social Media

None

**Comment by Betree** [comment]
Would be great to add some documentation, we currently have none

**Comment by shannondwray** [comment]
Moved here: https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Documentation-Releases_sul57#Project-Releases_turYe/r166&view=modal
