### ISSUE TITLE
[Project] Update OSC Onboarding Process

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5645]
## Overview 

Open Source Collective are updating their eligibility criteria, we need to encapsulate that criteria in the signup flows (GitHub, manual form)

## Ownership

**Owner:** @BenJam 

**Product:** @BenJam 
**Design:** @aminakazi 
**Engineering:** @gustavlrsn 
**Documentation:** @BenJam 

## Resources

- Project board https://github.com/opencollective/opencollective/projects/77w
- Original issue in Open Source Collective repo https://github.com/Open-Source-Collective/osc/pull/4
- Proposed update to eligibility criteria [here](https://app.gitbook.com/o/-LWSZizNMEjL8_DrMNdF/s/-MN_ynR0BjrarSoA9Z-A/~/diff/~/changes/Z4Mvft9N2lqLtEBlxdvK/getting-started/acceptance-criteria)

## Measuring success

reduced risk of accepting inappropriate projects
Reduction in time spent reviewing applications 

**Measure:** time spent verifying applications
**Alignment:** simplify 
**Current baseline:** 6-7 applications a day
**Target:** reduced time per application (manual verification)

## Kick off 

- [x] Create a project board, add this issue to the description
- [x] Open up any issues to de-compartmentalize the project, add them to the project board
- [x] Open [a documentation issue](https://github.com/opencollective/opencollective/issues/new?assignees=&labels=documentation&template=documentation.md&title=%5BDOCS%5D) when kicking off a project, reference this issue, assign an owner
- [ ] Open a release issue when kicking off a project, reference this issue, assign an owner 

## Wrap up

- [ ] Close all relevant project issues
- [ ] Open up issues for improvements 
- [ ] Post documentation and close documentation issue
- [ ] Post release and close release issue
- [ ] Post project closure in #newsletter slack channel 
- [ ] Celebrate!!

**Comment by BenJam** [comment]
## Kickoff 

### Resources

Review issue [https://github.com/Open-Source-Collective/osc/issues/3](http://url100.around.co/ls/click?upn=Ve2f-2FLodSFIkXBMESSfFGk-2Bql0WfTybH5x0RDDQbMzggsBwH06eq-2FQI6RBCp9goeqeKnNeHKkomZlqr9tyduIw-3D-3DBaQe_0pg8-2FkkoUjr3xH-2B4BEW7wgK7LT1hplaxrWkn41Lt64QkdKV3hpQ35jTMtqBfL0-2B2T3mrdh1W9k4e9oJvdgoX6lznvhZgWG2AhYcDUKz56Xv9TDpBPYka5hN9BCow-2BavxbSbhlYz7-2BaEWRSKfOyoZXo6cFuQOQydrIt-2FtXcHXqkL5NRF6K58mPvUkmujw-2B2aEpRpP-2F0gg-2FUWsSbYae55q45rfskEZlRrgLJevnxeWQbTEZrk3mgKDh2EUNFdI7aStpHUwO13shN8malympWn1PGxImXCeLGtnnq6GykRl6BqwlcBVbVXOJWOmMmPzH4Kg-2BNhegJmmiGrrcKB1-2BHxlCVSQDUnY4UJUepK9NcctkIpIUMMdqU6610OlDb45Vx2c)
Update eligibility req (in github) [https://github.com/Open-Source-Collective/osc/pull/4](http://url100.around.co/ls/click?upn=Ve2f-2FLodSFIkXBMESSfFGk-2Bql0WfTybH5x0RDDQbMzggsBwH06eq-2FQI6RBCp9goe5e8yPzoSGSzwV0e4t0BZ5g-3D-3DJpra_0pg8-2FkkoUjr3xH-2B4BEW7wgK7LT1hplaxrWkn41Lt64QkdKV3hpQ35jTMtqBfL0-2B2T3mrdh1W9k4e9oJvdgoX6lznvhZgWG2AhYcDUKz56Xv9TDpBPYka5hN9BCow-2BavxbSbhlYz7-2BaEWRSKfOyoZXo6cFuQOQydrIt-2FtXcHXqkL5NRF6K58mPvUkmujw-2B2aEpRpP-2F0gg-2FUWsSbYae55q4xNAvkaOoMUpA6X8E6KGgV0WG-2BDaE8lyNWC8I0iMXXNzJnxxvBmSzWLHe5AFT0kQgN1m-2BwLj7etBhxQOoiCNUt-2Bl7ZXRIbfC4Mp7meFs3dlRkbjacpksV1cWkf-2Fx2X4HAvOrN2S8j43cS1uXL2WiVn2CQTHX8-2BQoRv0FSL48Sl-2Bh)
Update eligibility in GitBook [https://app.gitbook.com/o/-LWSZizNMEjL8_DrMNdF/s/-MN_ynR0BjrarSoA9Z-A/~/changes/Z4Mvft9N2lqLtEBlxdvK/getting-started/acceptance-criteria](http://url100.around.co/ls/click?upn=Ve2f-2FLodSFIkXBMESSfFGjOaHp04V0Ft78lnUA8jXIlB-2BISnolmoFIG9mfuss463y9GfbkVbQc5vole5xER3Q8hGMTJ4LIZMatK8knWQHKkzPPeZ6tcibflZ7AK-2Boi2-2FKey7l6axnKj4D0TWKUpPS15bv6fJzuNHt-2FHyI-2BZOWG3vWiH8nHccaNDvt2FxBA9y8gOWnOLh2jOjnhfthF4H5A-3D-3DwRk0_0pg8-2FkkoUjr3xH-2B4BEW7wgK7LT1hplaxrWkn41Lt64QkdKV3hpQ35jTMtqBfL0-2B2T3mrdh1W9k4e9oJvdgoX6lznvhZgWG2AhYcDUKz56Xv9TDpBPYka5hN9BCow-2BavxbSbhlYz7-2BaEWRSKfOyoZXo6cFuQOQydrIt-2FtXcHXqkL5NRF6K58mPvUkmujw-2B2aEpRpP-2F0gg-2FUWsSbYae55q4909cKnCuPL4iwh2endw9by7gC5l0CaLAyJzexq7HrOHxqcIuOqySK1FEfKy31LQFyw734ARzGHFczj-2FYHuRS-2BcFCYssziS16OXO-2FXHO6lw-2BO5ApxvptvZTyMW8KuAeU5BPbrwUBR33PEA1vAP12L4w359veYx5y5BTg-2BvJkyVuK)
Working process [https://gist.github.com/BenJam/3e8d9cd852850d14e61a0f1dcebcbe0b]

Recording https://around.co/playback/4b961c4a-81c1-4966-b482-4daa88b4ebfd?s=myMeetingRecordings&sharedKey=c31f9629-56db-4d65-8b26-d89a10544358

## Notes

**Comment by BenJam** [comment]
## Shaping

Given the kickoff conversation above I think there are three parts that we'll need to dive into:

- [ ] updating the GitHub flow to reflect the new eligibility req
- [ ] Updating the form to reflect the new eligibility req

Optionally we could also spend time

- [ ] saving applications in a 'draft' state to return to later
- [ ] developing and publishing guidance for 'mandatory' requirements (licence, CoC, repos owned by individual accounts)

**Comment by piamancini** [comment]
- [ ] Product / Dev discussion of updating GitHub flow @BenJam @znarf 
- [ ] Design elements (@aminakazi)

**Comment by BenJam** [comment]
Quick update after call with @znarf 

- discussed new eligibility criteria and technical approach,
- discussed process of 'follow up' questions if we notice a licence isn't OSI approved or the project is a fork
- Would prefer to have the design for those things done, @aminakazi's design should encompass this

next steps is for Eng. to decided on best approach for doing these checks, @SudharakaP's name was mentioned.

**Comment by BenJam** [comment]
plan for this week

- [ ] @aminakazi working on designs from weds
- [ ] ? to look at engineering approach/make a start on engineering (@znarf to confirm)

**Comment by BenJam** [comment]
re-adding this to prioritisation as we evidently need it to control the number of projects that we're accepting...

**Comment by BenJam** [comment]
@aminakazi can you drop the design that we got to for this?

**Comment by znarf** [comment]
Figma https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO

**Comment by poohlaga** [comment]
a reminder that we want to prevent users from **submitting** their application unless they have 2 admins attached to the application form

**Comment by kewitz** [comment]
Project and issues: https://github.com/opencollective/opencollective/projects/77

**Comment by Memo-Es** [comment]
I did a QA round of the current working file and fixed some inconsistencies and glitches, pushed the design to production here: https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=18824%3A198016

Note: Desktop is finished, tablet and mobile pending.

@gustavlrsn

**Comment by aminakazi** [comment]
Update: The [design file](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=18824%3A198016&viewport=470%2C327%2C0.05) has been updated with the tablet and mobile UI

**Comment by BenJam** [comment]
W3 notes

- finalising data collection
- updating form

**Comment by BenJam** [comment]
- review pr for wrap-up of final mods
- announcement of change to eligibility criteria
