### ISSUE TITLE
Update Cypress to v10

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5648]
We currently use Cypress v9 and it would be nice to migrate to v10 which comes with lot of new features. Especially starting with Cypress v10 we have support for [production ready component testing](https://cypress.io/blog/2022/06/01/cypress-10-release/).

**Comment by Betree** [comment]
I'm personally not convinced by the component testing part. I feel like we can already point cypress to our styleguide to achieve that, which would prevent duplicated code.
