### ISSUE TITLE
Feedback: Send notification to added members of a collective

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#565]
Feedback from Danny from La Conexión Collective:

> I think it would be great at a minimum for people to get notified they’ve been added as members of a collective- if not also given basic onboarding instructions, too!

**Comment by xdamman** [comment]
Duplicate of #566 
Please check if there is no related issue before and if so just +1 it.

**Comment by xdamman** [comment]
Actually, just realized that both our issues were sent the same minute and probably crossed each other ¯\_(ツ)_/¯

**Comment by nicobarretoOC** [comment]
No worries, good coincidence!
