### ISSUE TITLE
OAuth: show last usage date for connected application

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5650]
Followup on https://github.com/opencollective/opencollective/issues/5344#issuecomment-1135478226

In the design proposal for OAuth, we have this bit about the last usage date for connected applications:

![image](https://user-images.githubusercontent.com/1556356/173321562-c920e3b6-792f-44df-9e1d-133c92767e46.png)

This wasn't implemented in the MVP as we don't have this information yet in the database. In the next sprint, we're going to add the app info in activity logging (see https://github.com/opencollective/opencollective/issues/1660#issuecomment-1151326616, to be replaced with issue link) which should make it fairly simple to retrieve this info

**Comment by Betree** [comment]
`Activity.UserTokenId` has been introduced in https://github.com/opencollective/opencollective-api/pull/7652, this issue should now be fairly simple to resolve!

**Comment by la-costa** [comment]
@Betree 

I created the pull request GH-7810, but I'm still working at front end functionality.

**Comment by Betree** [comment]
Linking the abovementioned issue to have it in the right context: https://github.com/opencollective/opencollective-api/pull/7810

**Comment by la-costa** [comment]
This issue also depends on [opencollective/opencollective-frontend#8073](https://github.com/opencollective/opencollective-frontend/pull/8073)
