### ISSUE TITLE
Move added funds

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5651]
For the first release of the `Move authored contributions` tool on https://opencollective.com/opencollective/root-actions we prevented moving added funds, because their `PaymentMethod` is set to a "collective" payment method that belongs to the profile and that we certainly don't want to move from one to another. Instead, the solution when encountering such orders should be:
1. Get or create the payment method for the destination collective
2. Update the transactions, settlements & orders to this payment method, but make sure we don't edit the one previously set on the order/transactions

**Comment by Betree** [comment]
Similar: We should also allow moving transactions that use an `opencollective/host` payment method.

**Comment by Betree** [comment]
We documented the process with @SudharakaP today:

1. Update the order: `CollectiveId`, `PaymentMethodId` , `TierId`
2. Update the transactions:
   - On CONTRIBUTION CREDIT: `CollectiveId`, `PaymentMethodId`, `description`
   - On CONTRIBUTION DEBIT: `FromCollectiveId`, `PaymentMethodId`, `description`
   - On HOST_FEE CREDIT: `FromCollectiveId`
   - On HOST_FEE DEBIT: `CollectiveId`
3. Update Membership: `CollectiveId`, `TierId`

In more complex cases, we'd have to update settlements but we don't want to support moving across hosts for now (when implementing this feature, make sure to throw an exception in this case).

**Comment by znarf** [comment]
Something in the specification is wrong.

For Added Funds, the Payout Method is the one from the receiving Collective and is `service=opencollective` and `type=host`. It should not change when updating the "from" of Added Funds.

If the payment method is `service=opencollective` and `type=collective`, it means "Collective to Collective Contribution" and should be addressed separately.

To avoid the mentioned complex cases, the original `order.fromCollective.HostCollectiveId` is set, we should refuse to move the contribution. If the new `fromAccount.HostCollectiveId` is set, we should also refuse. We can relax this when we'll see clearer.

**Comment by SudharakaP** [comment]
> Something in the specification is wrong.
> 
> For Added Funds, the Payout Method is the one from the receiving Collective and is `service=opencollective` and `type=host`. It should not change when updating the "from" of Added Funds.
> 
> Also, Host Fees should be unaffected.
> 
> If the payment method is `service=opencollective` and `type=collective`, it means "Collective to Collective Contribution" and should be addressed separately.
> 
> To avoid the mentioned complex cases, the original `order.fromCollective.HostCollectiveId` is set, we should refuse to move the contribution. If the new `fromAccount.HostCollectiveId` is set, we should also refuse. We can relax this when we'll see clearer.

Refactored, see comment; https://github.com/opencollective/opencollective-api/pull/8470#issuecomment-1447094361

**Comment by znarf** [comment]
Let's move forward with this please.
