### ISSUE TITLE
Include guidance on supported chains when contributing crypto

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5661]
We had a recent incident involving a (thankfully) user testing sending MATIC through Polygon to a Collective. The wallet address was generated by TGB and the user [sent the transaction](https://polygonscan.com/address/0x77A7b3d18C5E28B701f86ACCDBf4ef00Fd744b5B), but it was never credited to the collective. 

Why?

Because TGB dont support some chains https://docs.thegivingblock.com/faq/frequently-asked-questions/what-happens-if-i-send-unsupported-currencies-to-a-charity-using-the-giving-block-widget This restriction was not mentioned and undocumented at the time.

## To replicate

- Run through the 'contribute crypto' flow on any collective (octobox has it enabled) and select MATIC (other examples exist)
- Send MATIC through Polygon's chain 
- Profi....wait, nope, no profit. 

## Proposed Fix

We should update our guidance on this page, within the flow for donating crypto:
![Screenshot 2022-06-14 at 13 13 55](https://user-images.githubusercontent.com/158833/173575068-396e292c-b5e0-43f6-a758-0d6373b4f477.png)

**Comment by SudharakaP** [comment]
I suggest adding a warning below the info section; 

![image](https://user-images.githubusercontent.com/12435965/177053673-f0e01713-7664-41c2-92ce-ecdedc4ed284.png)

Something along the lines of, "Please do not send unsupported currencies or NFTs to any Ethereum address. Doing will result in the donation being lost and is not recoverable". Let me know if this is in agreement and I'll add it there. 🤔 

cc: @BenJam
