### ISSUE TITLE
Duplicate links created while onboarding repo

### ISSUE THREAD

**Issue by vlasenko** [opencollective/opencollective#567]
Thank you for the great platform!

I have tried to onboard our repo to open collective. 
https://github.com/sysgears/apollo-universal-starter-kit

But due to this issue:
https://github.com/opencollective/opencollective-website/issues/772
all attempts were failing with an error in JavaScript console and I thought nothing created. But after a while I realised that I created 14 collectives for this same project. They all have URLs starting with:
https://opencollective.com/apollo-universal-starter-kit
but 13 of them have suffixes like `-122`, etc. Could you help me and remove all these duplicate collectives with suffixes and leave only main one?
https://opencollective.com/apollo-universal-starter-kit

URL: https://opencollective.com/apollo-universal-starter-kit
Logged in as: vlasenko
Error message if any:
Expected result: 
Browser:

Thank you!

**Comment by vlasenko** [comment]
Or if you could remove them all, it will be fine too, I will start afresh

**Comment by piamancini** [comment]
hi @vlasenko we'll be working on this soon. We'll let you know when you can try again. Sorry you've hit this! 
Closing since it duplicated #555
