### ISSUE TITLE
[Release] Recurring Expenses

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5673]
## Context
 
We're building a process to enable folks to set an automatically recurring expense. 

### What's being released?

Users can set an expense to recur periodically, at the next period the expense will automatically be created based on the first and the user will be notified to complete and submit the expense. 

### Is this change being released incrementally as a beta? What's the schedule?

Releasing incrementally, testing ourselves first, then opening up to collectives on a host by host basis. right now this is enabled on the opencollective host only. 

### Is this release optional or mandatory?

mandatory, collectives will gain access to the feature, they don't have to use it though. 

### Who does this release impact?

All expenses submitters. 

### When will the project be ready for release?

It's pretty close to ready, we're just testing it ourselves. Withinthe next few weeks. 

## Product Process
 
- [x] review docs
- [x] write [release post](https://opencollective.com/opencollective/updates/recurring-expenses)
- [ ] announce to collectives on Open Source Collective and Open Collective Foundation as needed. 

## Resources

**Project issues** https://github.com/opencollective/opencollective/issues/5305

### Documentation

https://docs.opencollective.com/help/expenses-and-getting-paid/submitting-expenses#recurring-expenses

### Release post(s)

https://opencollective.com/opencollective/updates/recurring-expenses

**Comment by alanna** [comment]
Does this need to go back in the sprint priortisation process to get to full global release? Or is it going to be done anyway?

**Comment by Betree** [comment]
I haven't seen any blocking feedback and we've had some good internal testing in the team. I think this can safely be rolled out of everyone. cc @kewitz

**Comment by alanna** [comment]
OK great. @shannondwray please ensure this is documented when it's released to everyone, and let's do a 🔥

**Comment by shannondwray** [comment]
https://opencollective.com/opencollective/updates/recurring-expenses

**Comment by shannondwray** [comment]
Ready to go! Just checking if the updates feature is working as it's suppose to :)
