### ISSUE TITLE
Wise: PROCESSING activity should include ETA

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#5679]
We recently merged a feature that allows us to render detailed messages on thread activities.
Since we've been receiving some support tickets about delayed/slow transactions when paying to certain countries using specific methods, I think we could use the `PROCESSING` expense activity to display some information about the ETA of the transaction.

- [x] Include existing `Expense.data.quote.estimatedDelivery` ETA information when setting the Expense as processing (`Activity.data.message`).

**Comment by znarf** [comment]
I was thinking about this recently, would be awesome.
