### ISSUE TITLE
Improve UX flows and validation in expenses and invited expenses

### ISSUE THREAD

**Issue by iamronen** [opencollective/opencollective#5681]
Due to problems with error validation and the form, users can get stuck in unresolvable states of the flow. 

The resolution is an aggregation of four well understood issues that have been reviewed  by engineers:
 
 - #5020
 - #5306
 - #5429
 - #5222
 - https://github.com/opencollective/opencollective/issues/5697
 - https://github.com/opencollective/opencollective/issues/5820

**Comment by BenJam** [comment]
update - will start looking at this next week.

**Comment by aminakazi** [comment]
Should [this issue](https://github.com/opencollective/opencollective/issues/4667) also fall in the above list? We have entered it as a separate papercut.

**Comment by Betree** [comment]
@aminakazi The new validation strategy should make it easier to implement https://github.com/opencollective/opencollective/issues/4667. Can't guarantee it will be included in the project for this sprint, but great if you have a design for it :+1:

**Comment by BenJam** [comment]
leave on pause until @kewitz is back.

**Comment by BenJam** [comment]
may get some of this done between work on #5704 but priority is there for this week.

**Comment by Betree** [comment]
Related: https://sentry.io/organizations/open-collective/issues/3287154074/

**Comment by Betree** [comment]
Done :rocket:
