### ISSUE TITLE
Goals on Collective page: visual overlap of "Today's Balance" and "Estimated Monthly Budget" labels

### ISSUE THREAD

**Issue by th0rgall** [opencollective/opencollective#5688]
**Describe the bug**

If "Today's Balance" and "Estimated Monthly Budget" are monetarily close to each other, relative to a set goal, then their labels will overlap on the goals progress bar on the Collective page.

This looks unclear and ugly.

The screenshot below explains it best.

This also happens on larger screen sizes (desktop web).

I'm sure time and more donations will eventually fix this for us, but it would be nice to fix for new Collectives.

**To Reproduce**
1. Set a goal in project settings, set it to show on the Collective's home page
2. Simulate following numbers: 
  - goal: 200 usd
  - today's balance: 12.47 usd
  - estimated monthly budget: 16 usd
3. Scroll down to the goal on the project page 

**Expected behavior**

Display the labels in a way that they don't overlap.

I see two options:
1. Place the labels vertically further apart; add some margin/padding.
2. Place the text in each label on one line.

A solution should make sure that the labels don't overlap in any possible position.

**Screenshots**

**Desktop (please complete the following information):**

No access to a desktop at the time of writing.

**Smartphone (please complete the following information):**
 - Device: iPhone11Pro
 - OS: iOS 15
 - Browser: Safari

![image](https://user-images.githubusercontent.com/11543641/175128988-ac13ffb6-3084-455b-9e09-adf0407d4b29.png)

**Additional context**

The issue is seen on my Collective page: https://opencollective.com/readup-collective at the time of posting.

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by SudharakaP** [comment]
My thinking is that we need to change the design here to show these maybe with a legend based graph. Maybe showing the "Todays Balance" and "Estimated Monthly Budget" in two different colors and then having a graph legend below to indicate what they represent. 

cc: @opencollective/design

**Comment by Betree** [comment]
Looks like a duplicate with https://github.com/opencollective/opencollective/issues/4832
