### ISSUE TITLE
Updates should be listed by publication date, not creation date

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5690]
Sometimes we work on a draft update for a while before publishing, and other Updates are published in the meantime. Currently when you then publish the older draft, it shows up on the Updates list down below older posts. Most recent published should be on top.

P4

**Comment by danielsum** [comment]
Hi Alanna, it should be fixed with these 2 pull request. I've also added the possibility to order by updatedAt in case of or for other use case. Have a nice week-end :-).

**Comment by alanna** [comment]
This issue is breaking our  announcements I think.

I published [this changelog post today](https://opencollective.com/opencollective/updates/submit-expenses-using-your-own-currency) but it didn't trigger a new :fire: because it was from a draft a while ago.

**Comment by Betree** [comment]
I'm about to merge a fix for this issue, but there's something I'd like to highlight: not all updates have a publication date, so when viewing https://opencollective.com/opencollective/updates **as an admin** (only them can see drafts) I'll see all draft first, sorted by creation date. Or, with example, a typical list from the admin point of view would be:

```
Update 0: publishedAt: null, createdAt: '2020-07-01' 
Update 1: publishedAt: null, createdAt: '2020-01-01' 
Update 2: publishedAt: '2020-03-01', createdAt: '2020-01-01' 
Update 3: publishedAt: '2020-02-01', createdAt: '2020-05-01' 
Update 4: publishedAt: '2020-01-01', createdAt: '2020-01-01' 
```

I personally think we should address this with a different design, letting the admin select between "Published" and "Draft":

![image](https://user-images.githubusercontent.com/1556356/183590490-d9871eb8-c1f0-4a0e-b22f-d8797cd635ca.png)
