### ISSUE TITLE
Project's Virtual Cards labeled as 'CollectiveName - ProjectName' in dropdown of the Host Dashboard

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#5692]
Can we have Project's card labeled as 'CollectiveName - ProjectName' in dropdown of the Host Dashboard -> Virtual Cards page?  This would lump all of a collective's cards together, would be very helpful to avoid duplicates.

![image](https://user-images.githubusercontent.com/64920686/174895299-9ba866bf-d90d-4540-90bd-81101f442c51.png)

_User case:_ 
As a fiscal host admin, one of our hosted collectives has been issued cards for [~5 different projects](https://opencollective.freshdesk.com/a/tickets/65266).  When they needed assistance, locating all their cards was a bit tedious.  

Adding this fix would help group all of a collective's virtual cards together, also help with avoiding creating duplicate cards for a collective/project.

+ also same for Events (CollectiveName - EventName)

_Originally posted by @kaylarep in https://github.com/opencollective/opencollective/issues/4312#issuecomment-1162345466_

**Comment by kewitz** [comment]
@kaylarep the name/label of a virtual card is defined by the host admin, so it is basically up to the admins to come up with a standard for naming cards.

What we can do to help is being able to fetch all virtual cards that belong to a certain collective and its projects/events. Do you think this would help?
