### ISSUE TITLE
Host admin can set date when confirming or adding contribution

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5693]
## User story 
As a host admin, I want to specify the date funds were received, so that I can better align OC and bank records and accurately record when money came in.

## Best solution for this problem
A date picker on both the `add funds` and `confirm contribution` screens.
<img width="606" alt="Screen Shot 2022-06-27 at 2 10 14 PM" src="https://user-images.githubusercontent.com/5498878/175847261-a82bad0d-e23a-4d16-86da-7d82c1b87d82.png">
<img width="455" alt="Screen Shot 2022-06-27 at 2 09 09 PM" src="https://user-images.githubusercontent.com/5498878/175847266-43a38c4c-d290-4634-8de3-962eb9858a27.png">

**Comment by shannondwray** [comment]
Docs issue - https://github.com/opencollective/opencollective/issues/6163
Release issue - https://github.com/opencollective/opencollective/issues/6164
