### ISSUE TITLE
Allow virtual card assignees to pause/freeze their own card

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#5695]
As a fiscal host, a collective admin [reached out](https://opencollective.freshdesk.com/a/tickets/99154) because they had expenses on their virtual card that they did not recognize.  

They have to first reach out to the fiscal host to ask them to freeze it. In urgent situations (e.g. if the card is being abused repeatedly over a weekend), the assignee should have access to pause their own card.

Would it also be good to consider giving them access to close their own card as well? (Perhaps with double-approval by the host?)

## Proposal

- [ ] Add a 'virtual cards' section to individual user settings
- [x] copy the virtual cards page from host settings (inc. collective filter)
- [x] text at top should say something like _'You are the owner of these virtual cards, purchases made using these cards will be assigned to you and you will be responsible for uploading receipts_ 
- [x] display only cards that are assigned to user
- [x] disable delete/edit functions from actions menu (user can only pause/.unpause)

Optionally we could add a note to receipt emails saying 

> If you do not recognise this purchase click here to pause the virtual card. 

this would send you straight to the new, personal, virtual card page with the filter applied.

**Comment by BenJam** [comment]
> how would it be abused?

I'm pure evil but: if I send someone to an event of some description and I think decide to cut your physical card, which you may be using to get around etc. There's a power dynamic there for sure.

**Comment by kewitz** [comment]
We still don't have a structure to support multiple approvals for any type of action on our platform. Considering this is a papercut, we'll need to find another way to solve this issue.

I suggest allowing the collective to pause the card but not resume it. Resumes would need to be requested straight to host admins, which should be OK considering we aim to cover emergency cases.
Do you think this is acceptable as a solution for this issue?

**Comment by kaylarep** [comment]
> I suggest allowing the collective to pause the card but not resume it. Resumes would need to be requested straight to host admins, which should be OK considering we aim to cover emergency cases.
> Do you think this is acceptable as a solution for this issue?

This sounds fine to me. In this process would definitely need to include:
- Double confirmation: "Are you sure you want to pause this card? You will not be able to resume card usage by yourself. You will need to contact your fiscal host, and ask them to turn the card back on. Please let your fiscal host know why you will be pausing this card."
    - With mandatory Comment field, not too many characters - sample text: _We need to close this card. The number has been stolen and there are fraudulent purchases._
    - Buttons say: (Pause card) (Cancel)
- Then, let me know if you need copy for what the message/notification email to fiscal host will say. I think:
   - would want it to link to the card's page in Admin Settings
   - include steps for what to do next (instructions for turning card back on, for filing a dispute/maybe what things look like in Stripe, anything else?)
   - reply to this message will go to Assignee

**Comment by znarf** [comment]
I would amend the specs with the following:

- Any Collective admin should be able to freeze a card (from the Collective -> Virtual Cards panel). That's especially valid for the permission model on the API.
- Why not keep the extra panel with all the cards assigned to you as User but we could have done without it
- If we we keep the panel, it should not be visible in the menu if you don't have Virtual Cards assigned.

**Comment by Betree** [comment]
I agree with the [specs](https://github.com/opencollective/opencollective/issues/5695#issuecomment-1220511769) from @znarf above. I think the best approach for the 1st version is to just remove the entry in the User's settings, it will simplify many things - including the API query.
