### ISSUE TITLE
Send Notifications to Admins when virtual card used

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#5696]
## Context

As requested by [a collective admin](https://opencollective.freshdesk.com/a/tickets/99154)/virtual card assignee:
>  I would recommend if possible, have there be an alert for as soon as a purchase is made to be sent to our emails. I received no emails about the expenses until the wanted receipts emails came. 

- This notification should be a toggle option
- It could either be via a notifications panel, an email, or both (giving user the option to select how they want to be notified)

- related: 
    - https://github.com/opencollective/opencollective/issues/4556
    - https://github.com/opencollective/opencollective/issues/5501

## Pitch

- Notify all admins of all virtual card payments made, as they are made ([proposed text](https://gist.github.com/BenJam/bca2dd6cfdbe825353d64898761be9d3)). 
- Add pause/unpause action to cards from collective virtual card page. 
- Enable admins to disable notifications for 'virtual card payments' from their notification settings (#3357)
- Add 'manage notifications like this' to all email notifications sent

**Comment by BenJam** [comment]
this is a bit weird but, I get emails (a lot of them) every time a virtual card is used on Open Source Collective and Open Collective Inc. to upload a receipt: https://github.com/opencollective/opencollective-api/blob/main/templates/emails/collective.virtualcard.missing.receipts.hbs

@kaylarep could you check their setup and confirm they're not just sending these emails straight to spam?

**Comment by kaylarep** [comment]
i think (if its possible) a toggle option would definitely be ideal here. 

i definitely don't know if this is possible...but what about an optional text notification. I turned this on for one of my bank cards after it was stolen, and really appreciated getting a text after purchasing. something like this:

![image](https://user-images.githubusercontent.com/64920686/176797100-0dd1c785-3c60-4663-a89a-dfdac17aa947.png)


-- as it is right now, (all admins are emailed when a receipt needs to be uploaded) is a bit confusing

**Comment by BenJam** [comment]
I think we should keep our current, single-channel (email) notification strategy for the moment. But we could email administrators whenever any virtual card is used. 

In the notifications settings panel this might be a 'virtual card payments' notification setting on the 'collectives I administer' section, which would be separate from the 'expenses' notifications that the registered keeper of the card receives (to upload a receipt). 

Just to mention, the other option here would be to add other admins to the list of people responsible for the card, but I think that is not safe from a compliance point of view.

**Comment by BenJam** [comment]
Updated the OP with a pitch and moved to pitching.

**Comment by kaylarep** [comment]
> But we could email administrators whenever any virtual card is used.

if we do this, i really think it needs to have a toggle option. 

I'm worried this will be confusing to users- they are already emailed to upload a receipt, this seems repetitive.  it's just hard for them to maintain oversight over their cards as it stands currently., so this is a proposed solution. i don't want to add another email to their already crowded inboxes. I know I'm the one who created this issue, but I'm really just chasing problems with potential fixes.

> Just to mention, the other option here would be to add other admins to the list of people responsible for the card, but I think that is not safe from a compliance point of view.

+1 to this

I've proposed a lot of pain points in  https://github.com/opencollective/opencollective/issues/5410 (this is one of them); I don't have solutions, but continue facing challenges/confusion surrounding the cards

**Comment by kaylarep** [comment]
i dont think this is issue is well-thought out enough. some of it is too repetitive (admins are already emailed at each transaction when a receipt is requested).

some of it is an issue with admins receiving too many emails already + figuring out the exact role of the 'assignee'.

i'd like to keep it open though, because it still addresses a problem users have.

**Comment by Betree** [comment]
We can adapt the text from the email you receive when your card is being use, but should adapt it

cc @BenJam
