### ISSUE TITLE
Badge "Proud sponsor of Open Source"

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#57]
It would be good to have a small badge that companies can put in the footer of their website that says "Proud sponsor of Open Source", or "We are contributing to Open Source Collectives" (something along those lines), that would link to their company profile page on OpenCollective.

[![](http://cl.ly/2r3S1y0W1S14/Screen%20Shot%202016-04-29%20at%204.40.56%20PM.png)](https://twitter.com/auth0/status/725579084886061056)

**Comment by xdamman** [comment]
The cool thing would be that their profile page on open collective would not only show the open source projects that they sponsor but also the ones they contribute to (which means that we need to find a way to pull the data of who are the people who belong to the organization)

**Comment by erickrico** [comment]
![badges](https://cloud.githubusercontent.com/assets/18429104/15691796/6ece702a-2750-11e6-8a08-87324fc48c7b.png)

**Comment by piamancini** [comment]
Closing this: see opencollective.com/widgets.
