### ISSUE TITLE
Cents not displayed correctly

### ISSUE THREAD

**Issue by stevenwadejr** [opencollective/opencollective#570]
Expenses ending in a "0" are cut off and displayed with a single cent digit.

URL: https://opencollective.com/upstatephp
Logged in as: stevenwadejr
Error message if any: n/a
Expected result: Should display "$48.60" instead of "$48.6"
Browser: Chrome

![](https://d1ax1i5f2y3x71.cloudfront.net/items/132b0a1z0k3L3F3A2R3N/Image%202017-10-26%20at%2010.45.03%20AM.png?X-CloudApp-Visitor-Id=1912034)

**Comment by asood123** [comment]
https://github.com/opencollective/frontend/pull/113
