### ISSUE TITLE
contradictory instructions for bank account name

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5701]
When using a bank account as payout method, this is what you see:
<img width="328" alt="Screen Shot 2022-06-29 at 11 02 51 AM" src="https://user-images.githubusercontent.com/5498878/176333555-b8e6874b-583d-4339-8967-c8b63c51ccb3.png">

New Zealand bank accounts are set up with the *initial* only, not the full name. So we are showing contradictory info.

What's happening now is NZ people are putting in the name shown on the bank account officially (e.g. A S IRVING). Then when we try to pay them, we get this error:
<img width="339" alt="Screen Shot 2022-06-27 at 4 47 47 PM" src="https://user-images.githubusercontent.com/5498878/176333891-cc422bdd-f186-4dea-ac0c-b07c99facdcd.png">

The only way for the user to fix this is to completely delete the payout method and start over, which involves the host doing quite a bit of back and forth with them and delays the payment.

We should give people clear guidance about what to put in the name box - is it what's on the bank account, or their full name?

**Comment by alanna** [comment]
@kewitz this is coming up for almost every NZ bank payment and it's very frustrating. Can you think of a quick way to resolve? is there any way to override the Wise error? I'm concerned that if we have users put their full name instead of their actual bank account name, it will be rejected by the bank.

**Comment by kewitz** [comment]
I just submitted a fix considering Wise's documentation instructions, I think it is extra explicit now.
What we need is the full name attached to the bank account information, note that this does not mean what is written on the user's credit card.
