### ISSUE TITLE
Tags are case sensitive, but case insensitive on de-duplicating adding new tags to a collective

### ISSUE THREAD

**Issue by mlncn** [opencollective/opencollective#5702]
**Describe the bug**

Tags are case sensitive for search/discovery filtering of collectives, leading to unwanted splitting of what should be shared categories.  (At least, the the vast majority of the time)

**To Reproduce**

https://opencollective.com/search?tag=Drupal

https://opencollective.com/search?tag=drupal

When one follows either of those links (as by pressing the tag in a collective) one would expect to see all collectives in the labeled category, when as you can see above there is complete bifurcation depending on the initial letter being capitalized or not.

**Additional context**

This issue is compounded by the fact that it does not seem possible to add "Tag" to a collective when "tag" already exists.

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by SudharakaP** [comment]
My thinking here is that we should make tags case insensitive in the sense that all tags should be stored in lower case. I would suggest the following changes. 

- Create a migration to make all existing tags case insensitive. 
- When searching for a tag, make sure the search is case insensitive. 

@Betree : Let me know if you agree with these changes and/or if there's anything more to add. 🤔

**Comment by Betree** [comment]
I wouldn't enforce lowercase on tags. I think it's a good experience that people are able to use things like `OSS` or `USA` (uppercase) if they want to. But I do agree that the search should be case insensitive, searching for `react` should return collectives tagged with `React`.

cc @znarf

**Comment by SudharakaP** [comment]
@Betree : For the collective tags note that we cannot store something like `OSS` currently. It will be stored as `oss`. So all tags are stored in lowercase. 

https://user-images.githubusercontent.com/12435965/181370753-a406e09a-dd00-4e9d-a311-c8a91a7e65bb.mp4

I think we need to make sure when we search the search should be case insensitive as you mentioned. I've opened two PRs in this regard. 👍🏽
