### ISSUE TITLE
bug: Broken repository link for Sequel Ace project

### ISSUE THREAD

**Issue by vladdancer** [opencollective/opencollective#5706]
**Describe the bug**
The "Code repository" link on https://opencollective.com/sequel-ace is broken (missed "e" char in string)

**To Reproduce**
1. Go to https://opencollective.com/sequel-ace
2. Click on "Code repository"
3. Redirect to 404 page on github.

**Expected behavior**
Correct repository page (https://github.com/sequel-ace/sequel-ace)
**Screenshots**
<img width="1164" alt="Screenshot 2022-07-02 at 19 25 10" src="https://user-images.githubusercontent.com/791060/177008612-90fa8fe5-aef2-42ed-9417-9150a17c29e9.png">

**Comment by SudharakaP** [comment]
This is not a bug in the platform but rather it's upto the collective admins to set the correct repository URL. I've notified the collective admins of this collective about this issue and hopefully they'll correct it soon. 😃

**Comment by Jason-Morcos** [comment]
Thanks for catching this, @vladdancer! This should be fixed now. Thanks, @SudharakaP as well!
