### ISSUE TITLE
Sign in overlay overlaps other parts of the interface

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5709]
The sign-in overlay was updated by mistake in the sign-in flow (see https://github.com/opencollective/opencollective/issues/5700) the quickly adapted as a hotfix in https://github.com/opencollective/opencollective-frontend/pull/7968.

There are two issues with this new approach:
1. It hides other parts of the interface, i.e. links in the footer:
![image](https://user-images.githubusercontent.com/1556356/177119193-2f560bdd-284b-4374-999c-ad39031fc53a.png)

2. It goes above the collective navbar, there again hiding important buttons:
![image](https://user-images.githubusercontent.com/1556356/177119306-d8e91807-b0b1-4357-ba27-1818ed33e831.png)

The previous interface looked better IMO:
![image](https://user-images.githubusercontent.com/1556356/177119475-6fff6a81-06b4-45b2-9c4d-b2d05fd556d4.png)

My suggestion would be to slightly update the existing box to get closer to what we had:
![image](https://user-images.githubusercontent.com/1556356/177120234-62682d27-a37f-4a74-981b-5d858d292706.png)

cc @SudharakaP

**Comment by SudharakaP** [comment]
@Betree : I've opened a PR for this above (see screen-shot in the PR), one thing I didn't change is the positioning of the `Create an account` link. I am okay to change it, but just thought that the way it looks right now underneath the `Don't have one?` looks nice and consistent with the `SignIn` page. But let me know if you disagree and there's a specific reason to change this positioning of the link for the overlay. 🤔

**Comment by SudharakaP** [comment]
> I would personally have kept the previous interface because it was well suited for this space, but there's no turning back now so the next move should be to ask @opencollective/design to propose an official design for this.

I am also okay with going back to the previous interface and we could do that if needed (by creating a separate component for the sign in component for the overlay purpose). The reason I tried this approach initially was that I wanted to reuse our existing new Signin component and thought this gives a consistent approach; for example the logo and stuff, but given your proposal to hide the logo and stuff it basically becomes the same as the previous interface. 🤔

**Comment by Betree** [comment]
> > I would personally have kept the previous interface because it was well suited for this space, but there's no turning back now so the next move should be to ask @opencollective/design to propose an official design for this.
> 
> I am also okay with going back to the previous interface and we could do that if needed (by creating a separate component for the sign in component for the overlay purpose). The reason I tried this approach initially was that I wanted to reuse our existing new Signin component and thought this gives a consistent approach; for example the logo and stuff, but given your proposal to hide the logo and stuff it basically becomes the same as the previous interface. thinking

The interface you've implemented in the other PR looks fine, let's go with it. As discussed in the call, let's just iterate with design to make sure we adopt the best solution for the long-term. The team learning for next time is that we should better study the implications and use cases when updating this kind of global and widely used component.
