### ISSUE TITLE
Reimburse: Francesca 

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#571]
Mail from Francesca:
>Hello support,

>I just added a donation to my collective (https://opencollective.com/djangogirlsmrs), but clicked twice and ended up with 2 donations of 196 euros each. I can't seem to find a way to remove one of them. Would it be possible to get rid of one?

>Thanks a lot, sorry for the hassle.

***
Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by asood123** [comment]
I removed the second transaction.
