### ISSUE TITLE
Experiment with Typescript in the frontend

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5710]
We've added support for Typescript in the API [3 years ago](https://github.com/opencollective/opencollective-api/pull/2183), and, since then, its usage has constantly increased. 26% of the API files are now using Typescript. The migration has been pretty smooth since we decided not to enforce anything and still allow both JS and TS in the project.

![image](https://user-images.githubusercontent.com/1556356/177146327-750d3d2f-722a-4c82-a181-c3609471f022.png)

Having the same approach in the Frontend could have the following benefits:
- Type safety (prevent errors)
- Consistency with the API
- Remove legacy "PropTypes" that are tedious to write and whose errors are difficult to detect (since they're run-time)
- Automatic types from GraphQL queries (see https://github.com/opencollective/opencollective/issues/4054)

Here are the things that I identify as potential barriers to adoption:
- Is the team comfortable with Typescript?
- Would contributors be comfortable with Typescript?
- Are we ok with mixing JS and TS files in the same project? What's the long-term vision?

cc @opencollective/core-developers @opencollective/contributors: I'd love to get feedback on this to see how everyone feels about Typescript and whether we are ready to take our adoption to the next step.

**Comment by SudharakaP** [comment]
For myself I would love this. Although I haven't worked with Typescript, I would love to learn as I go along. 😄

**Comment by JoyLubega** [comment]
I personally love Typescript and I have some good experience with it.
Incorporating it would be great

**Comment by orimdominic** [comment]
I've worked with it. I'm okay with it

**Comment by danielsum** [comment]
I think that the learning curve is smooth enough as if someone is blocked he could ts-ignore and a code reviewer can rewrite it in typescript. I really love typescript as it makes the code more readable and having the type hinting is a huuuge developer friendly approach :-). Here are a link that I found useful so I share it : https://react-typescript-cheatsheet.netlify.app/docs/migration/intro

Another small improvement not related to typescript is to separate the gql files or use the gql-tag library : https://www.npmjs.com/package/graphql-tag. With some helper generator, you will have then a type hinting like in TS for graphql related query in your ide which is really appreciated :-).

**Comment by Betree** [comment]
> Here are a link that I found useful so I share it : https://react-typescript-cheatsheet.netlify.app/docs/migration/intro

@danielsum Thank you for sharing! I guess it kind of answers `Are we ok with mixing JS and TS files in the same project? What's the long-term vision?`, it's about staying in the `Level 1A: Majority JavaScript, increasingly strict TypeScript` until we're comfortable jumping to `Level 1B: Total rename to TypeScript from the start`.

> Another small improvement not related to typescript is to separate the gql files or use the gql-tag library : https://www.npmjs.com/package/graphql-tag

We already have that in place in the frontend, it's currently used by ESLint to detect invalid/deprecated fields in our queries. I didn't think about it, but using that we should indeed be able to get the GQL types integrated with TS very easily!

**Comment by Betree** [comment]
I'd like to complete this one before https://github.com/opencollective/opencollective/issues/6000 to prevent disparities in configurations (ESLint, GraphQL) between the frontend and the template that we want to setup. https://github.com/opencollective/opencollective-frontend/pull/8156 is not far from being completed, so I'll give it another look.

**Comment by RahulBansal123** [comment]
You have taken the right decision. It
