### ISSUE TITLE
Help Host Admin to mark expenses as incomplete faster

### ISSUE THREAD

**Issue by jfdh** [opencollective/opencollective#5713]
As a Host Admin, I want to use the new "Mark as Incomplete" feature from the expenses list. I want to save time by not having to open the particular expense to mark it as incomplete.

As we already have a preview of the attachment accessible from the expenses list, as well as the "Go to Pay" action available, it seems that the "Mark as Incomplete" action is the piece missing here.

Strategic Priorities: Simplification
High frequency - High impact

**Comment by Betree** [comment]
cc @kewitz

**Comment by Betree** [comment]
Should be a menu on the status, like we do when the expense is paid 

![image](https://user-images.githubusercontent.com/1556356/180978482-63e6ef67-1eb0-4d58-8a87-7ffa9c029f39.png)

**Comment by jfdh** [comment]
https://github.com/opencollective/opencollective-frontend/pull/8051#issuecomment-1199316481

**Comment by jfdh** [comment]
Copying my comment here:
