### ISSUE TITLE
Change card layout of the search page to the one that the old discovery page had

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#5714]
I don't know how this happened; we ditched one of the things that worked well on the previous /discovery page, the card layout.
The old layout was aligned with the layout we use in design files; it had smaller margins and reacted better when changing the screen size.

You can compare the experience of the previous [discovery](https://web.archive.org/web/20220414041331/www.opencollective.com/discover) page versus the [current](opencollective.com/search) search page. [Dribble's](https://dribbble.com/) card layout is another example of which layout works great IMO.

Ialso sharinglso a couple of comparison screenshots:

Around 1200 px |  
-- | --
![Annotation on 2022-07-04 at 18-46-27](https://user-images.githubusercontent.com/49539954/177226513-8ec44d30-9933-4d0c-8572-c442370b6f08.png)  |  <img width="3000" alt="Screen Shot on 2022-07-04 at 18-45-34" src="https://user-images.githubusercontent.com/49539954/177226515-5afba3a6-cda8-4c5c-9bff-627a729755cd.png">
Around 890 px| --
<img width="909" alt="Screen Shot on 2022-07-04 at 18-47-18" src="https://user-images.githubusercontent.com/49539954/177226664-44467c78-db45-4792-8bd0-321a466e461f.png"> | <img width="909" alt="Screen Shot on 2022-07-04 at 18-47-38" src="https://user-images.githubusercontent.com/49539954/177226666-caa52991-095b-4a76-a1c3-5e60345bc892.png">
Around 600 px and below | 
<img width="484" alt="Screen Shot on 2022-07-04 at 18-48-06" src="https://user-images.githubusercontent.com/49539954/177226870-837ffe21-3ad5-4e3d-9256-9008bd4c6767.png"> | <img width="484" alt="Screen Shot on 2022-07-04 at 18-47-54" src="https://user-images.githubusercontent.com/49539954/177226876-f0630ac5-71ee-4a71-b00d-6bf2abc4200e.png">

cc @Betree

**Comment by Betree** [comment]
Figma file: https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=16236%3A235796

cc @SudharakaP
