### ISSUE TITLE
Wrong tier being removed 

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#572]
From Danny of Laconexion: a very frustrating bug on our page: clicking to remove a particular tier on https://opencollective.com/laconexion/ (the $50 amount) consistently removes a different tier (the last one, for $1,500).

Separately, what happens when a tier is removed - if we mark it as `deletedAt`, it will cause issues later (when it's related transactions are referenced). We might need an `inActive` state.

**Comment by xdamman** [comment]
We mark it as `deletedAt` for now. Agreed would be good to also have a `disabledAt`.
