### ISSUE TITLE
Expenses inconsistencies in ledger

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#573]
Expense Ids: 280 and 281 were paid out 3x. They are rail girls atlanta's expenses. 

@piamancini Can you please check history on paypal and let me know whether it was recorded multiple times or paid out three times (in which case, we have to copy the expense).

This isn't urgent, can wait till after you get back.

**Comment by piamancini** [comment]
they are old. They've been paid with the Bento (so already reimbursed) but they were still live because they lost the receipts.

**Comment by asood123** [comment]
Issue is that each of those expenses have three different transactions listed. The money is being deducted three times per expense. We can mark two as deleted?

**Comment by piamancini** [comment]
we deleted the duplicates.
