### ISSUE TITLE
Contribution flow amount URL parameters not working with crypto contributions

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5731]
**To Reproduce**
On https://staging.opencollective.com/atomex/donate/crypto?amount=150, the amount input is not pre-filled.

**Expected behavior**
Should pre-fill the amount input

**Context**
- https://github.com/opencollective/opencollective/issues/5631
- https://github.com/opencollective/opencollective/issues/5721

**Comment by Betree** [comment]
Please wait for https://github.com/opencollective/opencollective-frontend/pull/8002 to be merged before working on this one

**Comment by SudharakaP** [comment]
This is already fixed. For example https://staging.opencollective.com/atomex/donate/crypto?cryptoAmount=10&cryptoCurrency=ETH correctly prefills the information.
