### ISSUE TITLE
Developers: revamp "Applications" and create "Personal Tokens"  settings

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5736]
The "Applications" (also named "Api Keys") is getting old and we would like to revamp it in the developer settings under a new name: "Personal Tokens".

If possible, we should also add new features like "scope" and "expiration".

**Comment by znarf** [comment]
I would like to see this project considered for prioritization next sprint (Q4S1).

**Comment by flickz** [comment]
For the Personal Tokens. I'm making the following assumptions:

- Following the same pattern as the "OAuth App",  the personal token should look like 

<img width="1021" alt="Screen Shot 2022-11-21 at 11 01 23 PM" src="https://user-images.githubusercontent.com/15707013/203171795-5bf18397-dd9f-4869-9afa-a7892b643bc8.png">

- On clicking "Create personal token" The modal form pops up with the following inputs.  **Name**, **Scope** (Reusing invoice tag selection component), and **Expiration** selection

<img width="678" alt="Screen Shot 2022-11-21 at 11 05 38 PM" src="https://user-images.githubusercontent.com/15707013/203172377-98d8d377-b416-44c7-a352-6202f059620a.png">
<img width="329" alt="Screen Shot 2022-11-21 at 11 23 15 PM" src="https://user-images.githubusercontent.com/15707013/203172379-73e657de-ab79-46a3-b93e-b8fb3e741634.png">
<img width="161" alt="Screen Shot 2022-11-21 at 11 23 53 PM" src="https://user-images.githubusercontent.com/15707013/203172382-28dc4fa4-e2fb-4c2d-9fa5-338fdae3b3ca.png">

- The API implementation will be reusing existing query/mutation "Application -> API keys" with additional support for `scope` & `expiration`. 
- The existing "Application -> API keys" will be removed from the menu dropdown.

**Comment by Betree** [comment]
Would be great to update https://blog.opencollective.com/open-collective-graphql-api-preview/ when we release this; we've shared it in a couple of places.
