### ISSUE TITLE
Unable to submit expenses due to: ERROR Wise: There was an error while creating Wise's recipient

### ISSUE THREAD

**Issue by chriscroome** [opencollective/opencollective#5738]
On the last page for generating a expense, when clicking the submit form, the following pop-up appears and the form cannot be submitted:

![ERROR Wise: There was an error while creating Wise's recipient](https://docs.webarch.net/w/images/1/1a/Open_Collective_Wise_error.png)

In the past there has not been this problem, is a Wise account now required for bank transfers when receiving money? If that is the case it doesn't seem very clear in [the documentation](https://docs.opencollective.com/help/expenses-and-getting-paid/submitting-expenses#invoices)? Or is there some other issue here?

**Desktop (please complete the following information):**
 - OS: Debian 11.4
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0

**Comment by znarf** [comment]
This should be resolved through support.
