### ISSUE TITLE
:Fire: Notification for pending invitations

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#5739]
As a user/potential collective/host admin, it would be nice to see a :fire: notification when I log in, if i I have a pending invitation to accept.

**Comment by Betree** [comment]
:fire: notifications are for platform updates only at the moment. We already identified that the weight of these notifications was too strong compared to the one of being invited as a member, but I think that's rather a case for https://github.com/opencollective/opencollective/issues/5382 or https://github.com/opencollective/opencollective/issues/5501. It's unclear to me how we could solve this with the fire notifications as they exist today.

**Comment by kaylarep** [comment]
@Betree ah ok, yes i think this fits into #5501 

I was thinking that I would instinctively expect to be notified of a pending invitation on the platform by the :fire: notification, and was surprised to find it a bit buried.
