### ISSUE TITLE
Pre-approved expense submitters 

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#5742]
As a collective host, the anyone can submit an expense model doesn't make a lot of sense would love to see a mode where submitters have to be pre-approved 

[](
https://twitter.com/Rich_Harris/status/1541443633404121088)

**Comment by Betree** [comment]
This model does make sense for most collectives as it makes the process easier. But some (usually large) collectives indeed don't want that, usually to avoid SPAM. We build this feature into the platform a while ago in https://github.com/opencollective/opencollective/issues/4196:

![image](https://user-images.githubusercontent.com/1556356/179464267-18ebb0ee-70c3-4117-8309-567f4e2f5ff0.png)
