### ISSUE TITLE
[URGENT] "There was an error while creating Wise's recipient"

### ISSUE THREAD

**Issue by Sari2DisCO** [opencollective/opencollective#5743]
We came across a new error message we've never seen while trying to upload invoices: "There was an error while creating Wise's recipient". It has to do with Transferwise (now called Wise). The expense blocks us from selecting a currency for the payment. We urgently need to have this payment processed (this has been submitted to a point but is blocked from being accepted by this error message) so we'd really appreciate prompt support! Thank you very much!

**Comment by znarf** [comment]
This is not a technical bug but a more generic problem with the platform or the fiscal host.

Please contact support@opencollective.com or use the contact form https://opencollective.com/contact.
