### ISSUE TITLE
Gift cards

### ISSUE THREAD

**Issue by evenstensberg** [opencollective/opencollective#5748]
## Who is your user?
A potential sponsor

## What are they trying to achieve?
Make sponsoring more fun and inviting to peers.

## How are they currently doing this?
N/A

## How well understood is this problem?
N/A

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [x] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment]
Gift cards are officially supported, you can find some documentation on https://docs.opencollective.com/help/financial-contributors/organizations/gift-cards.
