### ISSUE TITLE
fix dot net foundation setup

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#575]
I need to help dot net connect their stripe account issues: 
the members table has the collective as it's host and admin 
the email is linked to the collective ID of the collective, it doesn't have a separate collectiveid of it's own to make an admin

See:
<img width="920" alt="screen shot 2017-10-27 at 1 09 11 pm" src="https://user-images.githubusercontent.com/3671070/32103569-e285c358-bb18-11e7-80d5-c5688cd9ed3d.png">
 
see user id6478

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by asood123** [comment]
Host migration script already fixes this. Hoping I can get that out today.
