### ISSUE TITLE
Add infos about the Accountant role in the admin team section

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5755]
On `/collective/admin/members`, we show a description of the team member roles but it does not include the "Accountant" role. We could re-use another description provided elsewhere:

> Accountants can access financial information, such as receipts, invoices, and reports. They can't change settings or approve expenses.

Initial text:
> Core Contributors are the people closely associated with your Collective, who will show up on your Collective page as part of the team. Collective Admins are Core Contributors with extra permissions, like editing the Collective settings and approving expenses. Admins get notifications of activity on your Collective.

cc @alanna if you have feedback on how to bundle these in a simple way.

![image](https://user-images.githubusercontent.com/1556356/179696098-4535b0b6-9831-46f5-b756-637f2f410188.png)

**Comment by alanna** [comment]
I suggest making it bullet points, with this wording:

* **Admins** can edit settings and approve expenses, and receive activity notifications (such as when a new expense is submitted). They are the active managers of a Collective.
* **Core Contributors** are shown as part of the team on your page, but do not have admin access or get notifications. They do not play an active role on the platform.
* **Accountants** have read-only access to non-public data, uploaded files, and reports for record-keeping purposes. They cannot make changes and are not shown on your page.

**Comment by alanna** [comment]
Do accountants get notifications?

**Comment by Betree** [comment]
> Do accountants get notifications?

The financial-related ones, yes: host reports, collective reports, thank you emails.
