### ISSUE TITLE
Cannot create an event

### ISSUE THREAD

**Issue by ChrisLefevre** [opencollective/opencollective#577]
Currently, we do not know how to create events. 
At first glance, it is a problem of session or admin rights.
Here's how it behaves:
I am connected with the one-click-login
I can edit my collective
On the other hand, when I click on "create an event", I have a message that says to me "You must identify yourself as administrator of this collective to be able to create an event."

https://opencollective.com/enmarchebe/events/new

I identify myself but it does not change anything

**Comment by xdamman** [comment]
You are logged in as who? What's your profile url?

**Comment by xdamman** [comment]
Nevermind, I found the issue. Your user was actually a simple contributor (member) and not a core contributor (admin). There was a bug in the interface that would show the role as core contributor by mistake in the edit members section of https://opencollective.com/enmarchebe/edit#members

Deploying the fix now
