### ISSUE TITLE
Root action to change profile type between individual / org

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5771]
We often have people who have set up an account for an org as an individual profile type ([example](https://opencollective.com/simply-secure-operations)), or the opposite. This sometimes creates problems for the user, or for a host. For example, OCF has to review payments made to orgs and individuals in certain ways and having them set up as the wrong type makes the data noisy. It would be great if root admins could change an individual profile to an org and vice versa.

**Comment by Betree** [comment]
# Specs

My implementation would be the following one. cc @znarf, I haven't done this in a while, feel free to correct.

**Pre-checks**
- Must not be a host. Would be great to support that in the future, but that adds a lot of complexity to the MVP.

**Action**
- Create a new `USER` entry in the `Collectives` table, re-using most info from the existing profile
- Update the corresponding `CollectiveId` in `Users` to this new profile
- Change the type of the original `USER` account to `Organization`
