### ISSUE TITLE
"Confirm order" loops on the 3D secure request modal

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5773]
**Describe the bug**
Support ticket: https://opencollective.freshdesk.com/a/tickets/101500

We haven't been able to reproduce it, but the user shared a clear screencast where:
1. They receive an email asking to confirm their contribution
2. Click on the link
3. Sign in
4. After a short wait, the user is prompted with a 3D secure stripe modals
5. Complete the 2 steps successfully
6. The page goes back to loading mode
7. The 3D secure modal appears again, there's no success nor error message

Sentry [caught](https://sentry.io/organizations/open-collective/issues/3058463744/events/ef157ae6cbeb4218a7e8e625fa370712/?project=5199682&statsPeriod=14d) an error that seems to be the root cause, but it's unclear why the `payment_intent` would be unknown.

Some more details:
- Using desktop/laptop
- With Firefox and Chrome (tested in classic and private mode both)
- French bank: Société Générale

**Comment by znarf** [comment]
I have a personal Société Générale credit card if needed.

**Comment by Betree** [comment]
@znarf Interesting, it could be worth setting up a recurring contribution with it - though it will still be difficult to reproduce since it depends on the contribution amount, and securities enabled on the actual account. It's hard to tell how to trigger it precisely in production.

**Comment by Betree** [comment]
While digging today I better understood the root cause for this issue and was able to reproduce it locally. It probably happens with the most restrictive banks, the ones asking 3D secure for **each** payment. Here's how we handle that currently:

1. Try to trigger the payment. Stripe asks for 3D secure, so we send a link.
2. User logs in and completes the authentication with their bank.
3. We call `confirmOrder` on the API, which calls Stripe **without** any payment intent.
4. Stripe replies with `requires_source_action` and a paymentIntent that is not stored so we re re-trigger the modal and we loop again with (2).

**How to fix it**: either after the error or after the 3D secure completion, we need to store the payment intent to make sure it's re-used by the 3D secure flow (rather than re-creating a new payment intent each time).


The only unknown for me at this point is why `order.data.paymentIntent` gets nullified in the first place, but it sounds like we can make the code there more resilient.
