### ISSUE TITLE
Allow virtual cards receipts to be uploaded while processing

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5783]
On [Slack](https://opencollective.slack.com/archives/C01LTEBDARL/p1658442414042439):
> Feature request, sorry if this has been made before: What I find super tough right now about keeping up with uploading receipts is that you can’t upload receipts while the charge is “Processing”. So I can’t use the card and then immediately upload the documentation. I have to remember to check back in 2-4 days if its settled yet

On our side, we must make sure that there's no risk of concurrency issues between the admin edit and the update triggered by the payment webhook event.

**Comment by kaylarep** [comment]
the pain point is a bit related to the one in this issue: https://github.com/opencollective/opencollective/issues/5696
of smoothing out the processes for Assignees when they 1) complete a purchase; 2) receive an email notification asking for a receipt upload; 3) upload a receipt

I would like to consider how to improve this very thoughtfully, taking into consideration that the Admins who take the responsibility of being card Assignees often have many other tasks on their plates. So anything we can do to alleviate their burdens would be ideal.

To consider: what a virtual card purchase looks like in practice.
- purchase is made (either by Assignee, or another Admin who can view the same card details)
- email is sent asking for receipt upload
- the Assignee must locate the receipt (either in their own email, or from another Admin who used the card)
- the Assignee needs to wait till the purchase has cleared before they can upload

perhaps having a single page where Assignees can manage all virtual card transactions (view: pending, completed, still needs receipts) would be a good idea?

**Comment by themightychris** [comment]
> perhaps having a single page where Assignees can manage all virtual card transactions (view: pending, completed, still needs receipts) would be a good idea?

As an admin on an org with multiple virtual cards, I can say this would be super helpful! It's a bit discombobulating right now to find and flip through virtual card charges and find things that need action

**Comment by znarf** [comment]
Fyi, I think we're seeing customers uploading receipts while in processing. Or is it just editing the Expense? I had to make this patch for this reason https://github.com/opencollective/opencollective-api/pull/7754

**Comment by BenJam** [comment]
nope https://opencollective.com/octobox/expenses/91729

**Comment by SudharakaP** [comment]
@znarf : With regard to our discussion about uploading the receipt after using the virtual card. I was thinking now that we send an email notification `virtualcard.purchase.hbs` at authorization (after https://github.com/opencollective/opencollective-api/pull/7815) we could add a line in this email notifying the user that they could upload the receipt if they wish to do so (with a link to the appropriate expense) ? 🤔

**Comment by znarf** [comment]
> Allow virtual cards receipts to be uploaded while processing

To come back at the root issue, just wanted to confirm this is already allowed.

@SudharakaP yes, we should change the wording and they something like "you can already attach a receipt if you have one".

But on the other end, we should make sure to not ask for a receipt later on if there is already one attached.

> nope https://opencollective.com/octobox/expenses/91729

@BenJam I just worked with Virtual Cards charges that were processing today and could upload receipts.

https://opencollective.com/opencollective/expenses/92348 https://opencollective.com/opencollective/expenses/92342

**Comment by SudharakaP** [comment]
> @SudharakaP yes, we should change the wording and they something like "you can already attach a receipt if you have one".
> 
> But on the other end, we should make sure to not ask for a receipt later on if there is already one attached.

This is tackled at, https://github.com/opencollective/opencollective/issues/5951

**Comment by znarf** [comment]
Closing. Can be reopened if someone is not able to upload receipts while processing.
