### ISSUE TITLE
[DOCS] Proposition to replace Graphdoc with Magidoc

### ISSUE THREAD

**Issue by pelletier197** [opencollective/opencollective#5785]
## Context
Current [API documentation](https://graphql-docs-v2.opencollective.com/) is built with [Graphdoc](https://github.com/2fd/graphdoc), and some details about how to use the API is also detailed in a separated [Medium article](https://medium.com/open-collective/open-collective-graphql-api-preview-3b42ed1d55ff). 

### What's changing?
Proposition is to replace graphdoc with [Magidoc](https://github.com/magidoc-org/magidoc). 

> Small disclaimer here, I am the maintainer of Magidoc. 

### Why are we changing it?
Two main reasons: 

1. Graphdoc is unmaintained. Last code change was 2 years ago. There are over 60 pending issues and no-one is working on them.
2. With Magidoc, external documentation in a medium article would not be required. Magidoc allows to specify `custom pages` that could contain images, videos, text, and more. All done using markdown.

### Who does this change impact?
Mostly users I suppose? The documentation format and URLs would inevitably change.

### How do users use it?
Same way as right now

### Is this change optional or mandatory?
Optional

### Estimate of effort
Relatively small to begin with. Magidoc's configuration consists of a single javascript file, to which you can provide either a schema file or an endpoint URL. A little more effort may be required if you want custom pages, as you will need to write the markdown for it. 

Magidoc also generates a static html website, exactly like graphdoc, so effort should be small for deployment.

> If you want to discuss more, a thread was open in the `#api` channel in slack. Link [here](https://opencollective.slack.com/archives/C4TC3AYDT/p1658578593940319).

**Comment by Betree** [comment]
cc @znarf

**Comment by znarf** [comment]
I'm up to have a try.

Let's aim to make a more usable website with a nicer landing page.

The repository is here if you want to contribute: https://graphql-docs-v2.opencollective.com/

**Comment by pelletier197** [comment]
Thanks @znarf. I'd be happy to contribute. However you shared a link to the documentation itself, not the repository 😅

**Comment by znarf** [comment]
Sorry https://github.com/opencollective/graphql-docs-v2

**Comment by pelletier197** [comment]
Great, thank you! Quick question, do you wish me to push the static assets like you did here, or are you open to have this be done by pipeline ? I could, for instance, push the built website on a distinct branch, and have the magidoc code in the main branch. (Same flow as GitHub pages if you're familiar with it)

**Comment by znarf** [comment]
We're deploying on Vercel. I guess the assets don't have to be there and we can just build things on Vercel side.

The idea of having a branch with the assets and a branch with the code doesn't looks great to me.

Overall, I think the easiest is to start simple and do 1 step at a time:
1) Keep the assets and provide a new command to update them
2) Present a new approach with assets removed and and create a build script instead

**Comment by pelletier197** [comment]
Okay, seems good. And do the assets need to be at the root of the repository? I could make both solutions live together more easily if I could put each implementation in a separate folder. If that makes sense for you.

**Comment by pelletier197** [comment]
Finally, I did split it into folders. I don't think this is gonna have any impact. And I opened the PR https://github.com/opencollective/graphql-docs-v2/pull/2

**Comment by pelletier197** [comment]
@znarf Hi! This has been pending for a while. Would you mind having a look at it and give me some feedback when you got some time? Thanks a lot!

**Comment by znarf** [comment]
The build is crashing for me here:

```
Error: 
Cannot generate a random value for scalar 'NonEmptyString'. 
The random generator is not able to randomly generate a value for non-standard GraphQL scalars. 
You have to provide a custom factory by providing this in your magidoc config:
{
  website: {
    options: {
      queryGenerationFactories: {
        'NonEmptyString': '<an-example-of-scalar-value>'
      }
    }
  }
}

To learn more about how to generate a custom scalar value, see: https://magidoc.js.org/cli/magidoc-configuration#querygenerationfactories
```

Any idea @pelletier197 ?

**Comment by pelletier197** [comment]
Seems like you added some scalars since i made my first version. You just need to provide a example for this scalar here     https://github.com/opencollective/graphql-docs-v2/blob/5dcbd1ad4b4cd76d522205b98fadce0b70c023be/magidoc/magidoc.mjs#L32

**Comment by pelletier197** [comment]
I added it https://github.com/opencollective/graphql-docs-v2/pull/3

**Comment by znarf** [comment]
@pelletier197 Thank you!

**Comment by pelletier197** [comment]
> @pelletier197 Thank you! I deployed the new version on: https://graphql-docs-v2.opencollective.com/

Awesome! Thanks for trying it out 😊
