### ISSUE TITLE
vue sponsor links are broken

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#579]
From Evan: 
We just noticed the automatic sponsor links (done with links like /xxxsponsor/0/avatar), which were previously working fine, are now broken - gold sponsors are displayed in platinum and duplicated in gold, bronze are displayed in gold... would you mind take a look at it?

<img width="692" alt="screen shot 2017-10-28 at 1 52 35 pm" src="https://user-images.githubusercontent.com/3671070/32135163-61ec8daa-bbf2-11e7-89d3-46d1f3f8102f.png">

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by piamancini** [comment]
more info from Evan: 
vuejs.org (scroll to bottom), also seen on vue's readme on github. I've temporarily removed wrong platinum links now, but even gold links seems wrong.

**Comment by xdamman** [comment]
@aseem I’m AFK for the next 36h or so. Can you take a look at this? Should be in the frontend repo controllers/collectives.js.

**Comment by xdamman** [comment]
Or in the fetchMembers function https://github.com/opencollective/frontend/blob/master/src/server/lib/graphql.js

**Comment by aseem** [comment]
I think you've got the wrong aseem.

**Comment by xdamman** [comment]
Right sorry I meant @asood123

**Comment by asood123** [comment]
Correct url is http://opencollective.com/vuejs/tiers/goldsponsors/xxx/avatar.svg. (their url is missing `tiers` and need plural `goldsponsors`).

For example: 
1st gold sponsor: ![1st gold sponsor](http://opencollective.com/vuejs/tiers/goldsponsors/0/avatar.svg)
2nd gold sponsor: ![2nd gold sponsor](http://opencollective.com/vuejs/tiers/goldsponsors/1/avatar.svg)
3rd gold sponsor: ![3rd gold sponsor](http://opencollective.com/vuejs/tiers/goldsponsors/2/avatar.svg)
