### ISSUE TITLE
Incorrect Github link for fakerjs

### ISSUE THREAD

**Issue by n1c** [opencollective/opencollective#5794]
**Describe the bug**

The "Code repository" link on https://opencollective.com/fakerjs links to "https://github.com/faker-j/faker" instead of "https://github.com/faker-js/faker"

**To Reproduce**
1. Go to 'https://opencollective.com/fakerjs'
2. Click on 'Code Repository'
3. You'll receive a 404 on Github.com

**Expected behavior**
See Github faker-js repository.

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
Thanks, this is now fixed - though the cache might take up to an hour to update
