### ISSUE TITLE
Fixed width buttons do not work well in other languages

### ISSUE THREAD

**Issue by rzelnik** [opencollective/opencollective#5797]
**Describe the bug**
There is a fixed width button on the OC home page. It looks good in English, but in other languages the text has different length, which causes broken centering or overflowing of the text inside the button.

**To Reproduce**
1. Go to [the home page](https://opencollective.com/)
1. Scroll down to 'Start Now' button, check it
1. Change language to Spanish (or any other language that has the phrase translated)
1. Check the button again

**Expected behavior**
All buttons should have flexible width so that it could adapt to the text length.

**Screenshots**

Slovak language:
![oc-home-page-slovak](https://user-images.githubusercontent.com/610651/181876068-c54ef58b-ce34-4ecf-a4d4-c87df179d187.png)

Spanish language:
![oc-home-page-spanish](https://user-images.githubusercontent.com/610651/181876060-732b5cb3-c05c-4be4-937a-4d928b068291.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Firefox
 - Version 102.0

**Comment by Betree** [comment]
Cc @flickz 

I missed that in the review of the home page. Fixed width are evil and should be avoided for the reasons mentioned above.

**Comment by flickz** [comment]
Oops! Not sure how I missed that 😬

**Comment by rzelnik** [comment]
@flickz thank you for quick fix.
