### ISSUE TITLE
[DOCS] roadmap link send to a supposed outdated roadmap

### ISSUE THREAD

**Issue by scenaristeur** [opencollective/opencollective#5802]
The link for the roadmap on this page 
https://docs.opencollective.com/help/product/roadmap
 show a roadmap with the 2021/05/24 date. Is it outdated
? 
No more recent roadmap?

**Comment by Betree** [comment]
@scenaristeur Thanks for documenting this issue. We try to put the meaningful links on https://github.com/opencollective. 

cc @shannondwray, I'm not sure whether we should update the blog or remove this link. Currently:
  <ul>
    <li>Current Sprint: <a href="https://github.com/opencollective/opencollective/issues/5779">2022 Q3 cycle 1</a></li>
    <li>Ideas for Next Cycle: <a href="https://github.com/opencollective/opencollective/discussions/5741">2022 Q3 cycle 2</a></li>
    <li><a href="https://github.com/orgs/opencollective/projects/5">Cycle Planning & Weekly Board</a></li>
  </ul>

**Comment by shannondwray** [comment]
Have linked our docs to Github instead :)

**Comment by Betree** [comment]
That's perfect, looks resolved to me!
