### ISSUE TITLE
#backers and avatars don't match. 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#581]
For a particular tier, collective shows one backer avatar but says in text that there are two backers (there is in fact only one backer so far). See it live here: 
https://opencollective.com/laconexion/

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by xdamman** [comment]
Fixed in https://github.com/opencollective/opencollective-api/pull/981
