### ISSUE TITLE
Improve "Confirm your credit card" email

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5812]
We got a report on support from someone who thought the "Confirm your credit card" email was a phishing attempt:

> this seems like a scam, are you aware of this? has your user database been hijacked? especially the linked image at the start of the mail...

When asked more details about why he thought the email was a phishing attempt, this user said:

> It was just that "confirming your credit card" was ringing alarm bells because it sounds so much like a classical phishing approach:), and maybe it was a bit too few information in the mail why I should do that. I did not know that I have to do such a confirmation. Do I have to do that every year?
> 
> And then I did not find login credentials in my database for opencollective (and from a glance at the login page I did not realize it would send me a one-time-login).
> 
> And then the external link of the image.
> 
> All this together made me wonder.

From this feedback, it seems that we can improve a few things:
1. Make sure we're hosting the images embedded in our emails on our official domain (`images.opencollective.com`)
2. Provide more info about why we require people to do this. It's not the first time I read a support ticket saying they don't understand why we ask for a confirmation.
3. Provide some information on the sign-in screen: Try to open https://opencollective.com/orders/42424242/confirm as incognito, you'll see only a message like "You need to be logged in to continue.". There's not enough context here. We should say something like `Please sign-in to confirm your payment method`

---

_Initially reported in https://opencollective.freshdesk.com/a/tickets/107847_

**Comment by Betree** [comment]
Some more users shared this feedback, doesn't look like an isolated case:
- https://opencollective.freshdesk.com/a/tickets/108206

**Comment by Betree** [comment]
Got another report for this from Accountable by PM

**Comment by Betree** [comment]
I would like to see this project considered for prioritization next sprint (Q4S1).

It seems that many users think it's a phishing email, which means they won't renew their financial contributions. Would be great to back this assumption with a stat: after receiving the email, how many users update their credit card details? That could be used to decide on the prioritization of this project, then on its impact.

**Comment by SudharakaP** [comment]
Another few Fresh-desk tickets related to this; https://opencollective.freshdesk.com/a/tickets/127970 and https://opencollective.freshdesk.com/a/tickets/127476.

**Comment by BenJam** [comment]
- outline why this is happening, pick up documentation that's appropriate (from providers if necessary)
- update email content

**Comment by shannondwray** [comment]
To Do: Set up the documentation issue, ensure that we explain what happens when you change from a fiscal host to independent collective as this action is triggered. - Get more information from the devs

**Comment by Betree** [comment]
Summary of the kickoff meeting that took place today. I will follow-up by converting some of these items to issues.

## Documentation

We need a @opencollective/documentation page to:
- [ ] Explain the process, with screenshots of the email / page
- [ ] Document the most likely reasons for it to fail
  - [ ] Ad blockers
  - [ ] Issue with the bank service
  - [ ] Old browsers

## Email

- [ ] Link to a @opencollective/documentation page to explain this process with screenshots of the email/page
- [ ] Improve the content of the email
  - [ ] The subject is not catchy enough, prefix with "Action Required:"
  - [ ] See if we can improve the wording
  - [ ] Explain what will happen if they don't update
  - [ ] Explain why you should trust this email
  - [ ] Surface data to show it's not a random phishing email
    - Missing card last numbers
    - Card details (VISA, mastercard?)
    - Having the amount is good
    - More info on the contribution (monthly? yearly?)
- [ ] Improve the design of the email
  - [ ] Remove collective logo
  - [ ] Always show Open Collective logo
  - [ ] Add something to show that the email is verified?
  - [ ] Maybe we can have a quick improvement of the global email design?
  - [ ] See if we can improve the fonts


## Frontend

- [ ] Design to work on a template for "System pages" (engineering to produce a list of all these pages)
- [ ] The confirmation page
  - [ ] Should have some details, and a title
  - [ ] Should have the same look & feel as "we sent you your magic link"


**Stretch goals / follow-ups that seem important but are more expensive:**
- [ ] The "Admin > Payment methods" page should surface the same warning and let user update directly from there (would also help if for any reason the link/redirect breaks)
- [ ] Same thing on /recurring-contributions: replace "ACTIVE CONTRIBUTION" by something like "Client confirmation needed" and add a link to confirm

## Better understand the causes and impacts of these confirmations

- It appears that hosts that switched from Hosted to independent see an increase in the number of confirmations
- [ ] Maybe, if we can predict that a recurring contribution will trigger 3D secure after one or two payments, we can force 3D secure during the 1st contribution (needs more research)
- [ ] Have a Metabase report (see `payment.creditcard.confirmation` activity)
  - [ ] How many confirmation emails are we sending
  - [ ] How many confirmation emails are completed

**Comment by Betree** [comment]
**[Metabase dashboard](https://opencollective-metabase.herokuapp.com/dashboard/164-confirm-your-credit-card-sca-3d-secure)**

![image](https://user-images.githubusercontent.com/1556356/202719983-f241d6d7-083c-4516-ab24-2a3d4afb07e6.png)

![image](https://user-images.githubusercontent.com/1556356/202724884-e59dcb39-1fb9-4dc5-8fe9-cdd2cde2603d.png)

**Comment by znarf** [comment]
- [ ] look at the content of the email

**Comment by BenJam** [comment]
- merged and deployed working mods :tada:
- [ ] potentially look at mods to general email content (font family)
- [ ] design pages (verify CC) involved in this journey

**Comment by BenJam** [comment]
for the future

- figure out why fonts are down-grading to generic serif fonts (that look very spammy
- ? merge in change to page route for CC confirmation (to settings page)

**Comment by Betree** [comment]
We solved pretty much everything we wanted for this issue. Let's check the numbers in a couple of months!

**Comment by Betree** [comment]
It seems our changes have been quite successful, we've seen a +15% increase in the completion rate so far!

![image](https://user-images.githubusercontent.com/1556356/217079466-e90f9a8b-40f5-40f2-8576-da7f24f3650f.png)
