### ISSUE TITLE
Select a Collective when using Contact form 

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#5815]
## User story 
_As someone doing support tickets, I spend a lot of time trying to find out the users collective profile or collective they are referring to so that I can get a clearer picture on what is happening in their query_

## Best solution for this problem
It would be great to have another section added to the contact form on our website asking for any links like their profile link, collective, fiscal host link or some sort of auto response email that gets sent from our support inbox asking for this information 

## Metrics 
More queries with more information, save our team time searching 

<details>
  <summary>Triage Template (team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
+1 on this, it could save us some back-and-forth on support. I think this field should be optional though.

**Comment by Betree** [comment]
If the person is signed in, we could display a collective picker pre-filled with all the collectives they're part of

**Comment by BenJam** [comment]
> If the person is signed in, we *should* display a collective picker pre-filled with all the collectives they're part of

+1 to this., it would also be great if there was a way to attach information about the collective and user to the ticket on FD. Maybe there's a question in that statement about moving off email and toward using the FD API for tickets.
