### ISSUE TITLE
I can't see the expense I have created in my account 

### ISSUE THREAD

**Issue by scenaristeur** [opencollective/opencollective#5819]
**Describe the bug**
As a developer, I've created an Expense to a collective (Darcy) and get the mail to see it has been approved https://opencollective.com/darcy-is/expenses/88727 but I can't see it in my account, i think I should be able to see it with a status 'approuved' but I only see my transactions/ contributions 

**To Reproduce**
1. Create an Expense
2 wait for it to be approved
3 search it in your account
4 where is it, I can't see it, should I redo it ? 

**Expected behavior**
Expense i'have created should be visible in my account with their status

**Screenshots**
![Screenshot_20220804-043421_Chrome](https://user-images.githubusercontent.com/4020744/182751700-447ed338-9b12-4c62-b019-bb2b5f0e95b9.jpg)
![Screenshot_20220804-043533_Chrome](https://user-images.githubusercontent.com/4020744/182751702-f24fe641-5cfd-403d-890d-10232eb18109.jpg)

**Additional context**

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
Duplicate with https://github.com/opencollective/opencollective/issues/3749
