### ISSUE TITLE
Recurring expense payee not sticking

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5820]
**Describe the bug**
When the recurring expense draft is created the next time, it defaults back to the user's personal profile as payee, even if it were created with another payee (e.g. and Org or Collective that user is admin of). 

This makes it likely someone will just hit confirm but actually the expense will go to the wrong payee. This is a dangerous outcome because money will go to the wrong place.

**To Reproduce**
1. Create a new recurring expense
2. Make the payee a profile other than your personal user profile (e.g. an org)
3. See the draft expense created for the next recurring instance of the expense
4. The payee will be the creator's personal user profile

**Expected behavior**
Whatever payee is set up on the expense initially should persist when it recurs

  P2 low frequency, high impact

**Comment by Betree** [comment]
Looks similar to the bug we had in https://github.com/opencollective/opencollective/issues/5325. Could be interesting to look at its fix (https://github.com/opencollective/opencollective-frontend/pull/7712/files) while investigating.

**Comment by alanna** [comment]
@kewitz is this a quick fix or something we'll need to prioritise?

**Comment by znarf** [comment]
🎉
