### ISSUE TITLE
Magic links don't arrive

### ISSUE THREAD

**Issue by annapawlicka** [opencollective/opencollective#5825]
**Describe the bug**

I keep waiting for the magic link to arrive, but it doesn't, not even to my spam folder. I use Fastmail with custom domain. Spam protection is currently off. All filters are disabled. Still no magic link.
This is a rather critical issue as I can't access my account at all.

**To Reproduce**

Go to OpenCollective.com
Click on Sign In
Input my email address
I don't receive any email from OpenCollective, not even in the spam folder

**Expected behavior**
My email inbox should show the email from OpenCollective with a magic link, at latest in a few hours.

**Desktop (please complete the following information):**

OS: MacOS 12.4
Browser: Safari Version 15.5 (17613.2.7.1.8)

My account: https://opencollective.com/anna-pawlicka

**Comment by Betree** [comment]
Hi @annapawlicka, it seems that you (or someone on your domain) marked one of Open Collective's messages as spam, which prevented us from sending more emails. I've removed the block from our email service; you should now receive emails. Please let me know if that's not the case.

**Comment by annapawlicka** [comment]
Thank you @Betree! It works now.
