### ISSUE TITLE
Improve 'Tip' wording

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#5831]
The current 'Tip' is explained as 
![image](https://user-images.githubusercontent.com/64920686/183204078-af5e7cef-e8cd-4980-947e-d70198584149.png)

"allow us to keep Open Collective free for Collectives" is sort of misleading to a complete novice who has no context for 'Open Collective' or what a 'Collective' is.  The current language assumes that a donor knows basic information about OC, and they might not.

e.g. A person wants to donate to a collective, follows into the contribution flow, and assumes 100% of their donation arrives into the pocket of the collective - because its 'free for collectives'. They may not know what a fiscal sponsor is (and they may not care), & that additional fees may be charged.
__
Perhaps better (though I still don't love it):
We depend on tips from contributors like you to sustain this platform. [Learn more](https://opencollective.com/pricing)

**Comment by BenJam** [comment]
addressed in #6799
