### ISSUE TITLE
Filter contributions by payment/deposit type

### ISSUE THREAD

**Issue by poohlaga** [opencollective/opencollective#5833]
## Who is your user?
As an admin, I want to go to the Financial Contributions page and filter the list by Payment Type (bank, crypto, paypal...)

## What are they trying to achieve?
I currently filter by status 'pending' but have to check two different places to verify Bank and Crypto. If I could filter by Bank, it would be easier to go through the list and then filter by Crypto and do those transactions separately. 

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ x ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment]
We have this issue about adding a payment method type filter on the [transactions list](https://opencollective.com/babel/transactions): https://github.com/opencollective/opencollective/issues/5517. For the [orders list](https://opencollective.com/opensource/admin/orders), we have: https://github.com/opencollective/opencollective/issues/5307. 

@poohlaga Please let me know if the page you're referring to is not one of these.
