### ISSUE TITLE
OAuth: default scope does not seem to work

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5835]
In https://opencollective.slack.com/archives/C0RMV6F8C/p1659651083858259, a contributor ended up with a `null` scope which triggered a strange-looking error message. We should:
- Make sure `scope` is always initialized with an empty array, as mentioned in the docs (or make it mandatory?)
- Maybe improve the docs, to clearly state that the token will be pretty useless if you don't provide a scope

**Comment by znarf** [comment]
Fixed in https://github.com/opencollective/opencollective-api/pull/7850
