### ISSUE TITLE
Invalid collective navbar layout/spacings

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5837]
Affected devices: Desktop.
Example: https://staging.opencollective.com/usd-eur
Introduced in https://github.com/opencollective/opencollective-frontend/pull/8020

![image](https://user-images.githubusercontent.com/1556356/183450298-16ba0a64-98a8-47c9-9bdc-f15f36866276.png)

**Comment by znarf** [comment]
@Betree Should we close the issue now that it's resolved?

**Comment by Betree** [comment]
Yep, I eneded up reverting the PR that caused this in [NotificationBar.js#L180](https://github.com/opencollective/opencollective-frontend/blob/ee98f60d0f2599eb041adcad08658583de6b4f70/components/NotificationBar.js#L180) and re-opening https://github.com/opencollective/opencollective/issues/4683
