### ISSUE TITLE
uploaded filetype error message confusing

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5839]
I understand what this error means but a lot of people might not.

![Screen Shot 2022-08-09 at 3 46 42 PM](https://user-images.githubusercontent.com/5498878/183559904-4fc2f0f6-42dd-4596-8ece-fb6087b926e3.png)

I suggest:
> Filetype error: only JPG, PNG, or PDF is supported

**Comment by Betree** [comment]
This is probably related to the latest update in https://github.com/opencollective/opencollective-frontend/pull/7844 / https://github.com/opencollective/opencollective-frontend/pull/8017.

**Comment by ShreyaPrasad1209** [comment]
@Betree do you want to format this message or rewrite it in simpler words?

**Comment by Betree** [comment]
> @Betree do you want to format this message or rewrite it in simpler words?

The first part of the message is fine, only the last part about file types should be rewritten to remove the `application/` and such. The result should ideally look like what @alanna suggested in the issue description:

> Filetype error: only JPG, PNG, or PDF is supported
