### ISSUE TITLE
Change expiration date of invited expenses from 30 to 60 days

### ISSUE THREAD

**Issue by poohlaga** [opencollective/opencollective#5844]
## Who is your user?
This update affects collective admins who are sending or receiving invited expenses

## What are they trying to achieve?
Can we change the duration for when invited expenses expire? Currently, it is set to 30 days, can we make it 60? 

## How are they currently doing this?
With Google, they send out a lot of invitations for their Summer of Code grant and there are always a few collectives who lose the invited expense in their emails, and by the time they get to it - it 404s. I think 30 days is too short but 60 days will work. After 30 days collectives do the end of the month reconciling and realize they are missing something so if we make it 60, it gives them another 30 days to clean up the month prior.

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [x] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment]
I just noticed that we already do 2 months, aka 60 days: https://github.com/opencollective/opencollective-api/blob/948e0abf630b6cbe2f323c1f6d9024a3a46d8eef/cron/daily/60-clean-orders.js#L22

**Comment by Betree** [comment]
When we discussed this with @BenJam, we were thinking about something more like 6 months.

**Comment by Betree** [comment]
Oh @poohlaga I actually got confused because we were discussing about orders expiration at the same time! Invited expenses expiration is indeed 1 month! I'll push a fix for that right now.
