### ISSUE TITLE
Notification settings: delay when clicking on a toggle

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5853]
This network delay does not feel great as you're not sure whether your click worked and are tempted to click again.

I suggest looking at Apollo's optimistic mutation results: https://www.apollographql.com/docs/react/performance/optimistic-ui/.

![Peek 2022-08-13 00-18](https://user-images.githubusercontent.com/1556356/184451843-1ee669df-a210-4cfd-9e7d-a3a6eadffbf9.gif)

cc @kewitz

**Comment by kaylarep** [comment]
+1 am experiencing delay as well
