### ISSUE TITLE
Sending Event balance to parent leaves $0.01

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5857]
I clicked the 'send balance to Collective' button on an Event, but then it showed this:
<img width="653" alt="Screen Shot 2022-08-15 at 9 00 14 AM" src="https://user-images.githubusercontent.com/5498878/184554762-8939bc91-7a10-4115-bb6d-1c5d1d744e75.png">

I clicked it again and it properly zeroed out.

**Comment by znarf** [comment]
Could you give more information on the account?

**Comment by alanna** [comment]
It was the January regional retreats event

**Comment by znarf** [comment]
That was a multi currency issue. I created a new ticket to follow up here: https://github.com/opencollective/opencollective/issues/5858
