### ISSUE TITLE
Financial Overview: Budget Section with List expense and contributions view

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#5861]
Implement an alternative Budget section as an opt-in feature following designs in https://github.com/opencollective/opencollective/issues/5704#issuecomment-1214610825.

- [x] Implement horizontal Budget summary
- [x] Implement List view for Expenses and Contributions summary
  - Ignore Expenses per Recipient and Top Financial Contributors for now. 

**Preview:**
![](https://user-images.githubusercontent.com/49539954/184575454-f0e852da-422c-4bb5-97f8-5346a54d28df.png)

**Comment by Memo-Es** [comment]
@kewitz [Figma file reference](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=10158%3A0)
