### ISSUE TITLE
Collectives (and money attached to them) are no more displayed on #BrusselsTogether host

### ISSUE THREAD

**Issue by jfdh** [opencollective/opencollective#587]
Hi all,

I noticed yesterday that the amount of money on [#BrusselsTogether](https://opencollective.com/brusselstogether) has been reduced from +-41,000 euros to 11,000 euros. Moreover, the collectives are nowhere to be seen on this same page.
<img width="1440" alt="screen shot 2017-10-31 at 15 23 40" src="https://user-images.githubusercontent.com/30813303/32228844-a19809de-be4f-11e7-8388-060d0d776a87.png">
<img width="1440" alt="screen shot 2017-10-31 at 15 23 48" src="https://user-images.githubusercontent.com/30813303/32228868-b8d27ab2-be4f-11e7-8030-0052a111be37.png">

***

URL: 
Logged in as: jf
Error message if any:
Expected result: 
Browser: Chrome

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by piamancini** [comment]
@asood123 this might be a consequence of the changes we made yesterday. Let's look at this together. 
Thanks @jfdh

**Comment by asood123** [comment]
@jfdh We had a bug in our budget calculator that was double counting amounts in certain cases (as of Oct 6). We fixed it yesterday, so some of the budgets dropped. This should be roughly the same amount as what Brussels Together had in September. Do you by any chance recall (roughly) what it was last month?

**Comment by jfdh** [comment]
Last month was between 30,000 euros and 40,000 euros. To me, it seems that the 11,650 euros currently displayed on this page only reflect the donations we received for #BrusselsTogether ASBL. Before, it used to reflect these donations combined with those of all the collectives hosted by #BrusselsTogether.

**Comment by asood123** [comment]
Ah yes, I see the issue. Will work on fixing it.

**Comment by piamancini** [comment]
can we close this?
