### ISSUE TITLE
Clicking post before image uploads results in blank expense comment

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5871]
See https://opencollective.com/foundation/expenses/90942

There's a blank comment from me. I think I clicked post before the image had fully uploaded. I did it again on the comment below and waited for it to load, and then it worked.

If the image has not uploaded, the comment should wait until it has to be posted, or the post button should be inactive until it's ready, or it should fail with an error.

**Comment by Betree** [comment]
Your proposed solution to disable the submit button while a file is uploading seems like the simplest and most generic way to solve this. We should ideally do it in `RichTextEditor`, to make sure all places using it (collective long description, update, etc) will be fixed too.
