### ISSUE TITLE
Implement a generic way to do greetings in email templates

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5872]
Followup on https://github.com/opencollective/opencollective/issues/5207
Based on a proposal from @nosro in https://github.com/opencollective/opencollective-api/pull/7830

We don't have a consistent way to do greetings in our emails. We sometimes do `Hi,`, sometime `Hi {collectiveName}`, and sometimes `Hi {userName}`. Apart from the inconsistency issues, this sometimes results in the wrong name being used (see https://github.com/opencollective/opencollective/issues/5207).

We should try and solve this issue in a generic way. I suggest to:
- [ ] Add a special `recipientName` variable in `data`, like what's done in https://github.com/opencollective/opencollective-api/blob/9c33658f4da939e398e35eaa1eb4cf992522dd37/templates/emails/taxform.request.hbs.
- [ ] Try to prefill `recipientName` when appropriate. For example, we can probably do something in `notify.user`
- [ ] Implement a `greeting` partial like:

```hbs
{{#if recipientName}}
<p>Hi {{recipientName}},</p>
{{else}}
<p>Hi,</p>
{{/if}}
```

- [ ] Where appropriate, use this new partial like:

```hbs
{{> greeting}}

My email content

{{> footer}}
```

**Comment by nosro** [comment]
@Betree thanks, you spelled this out clearly. I followed your suggestion to the letter, I think.

I can go through all templates and add the greeting, if this looks like the way to go.

https://github.com/opencollective/opencollective-api/pull/7923
