### ISSUE TITLE
Remove the email forwarding feature

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5874]
Followup on https://github.com/opencollective/opencollective/issues/2847

We used to have an "email forwarding" feature that was deprecated 2 years ago in https://github.com/opencollective/opencollective/issues/2847 / https://github.com/opencollective/opencollective/issues/4131, mostly because of SPAM issues, low security levels and lack of maintenance.

This feature has been replaced by a contact form, and we're planning more improvements in https://github.com/opencollective/opencollective/issues/2263. There's also an open discussion about reviving this feature in a more secure way at some point: https://github.com/opencollective/opencollective/issues/2840.

When we did this change at the time, 3 collectives opted-in to keep it active. Only one of them, https://opencollective.com/peermaps, is still active today. Looking at the email logs, it doesn't seem like they're actively using it.

I'm therefore proposing to remove this feature entirely, following this plan:
- [x] Today: Contact peermaps to let them now we'll remove the feature next month
- [ ] (Unless we get blocking feedback): remove the feature entirely on 1st of October

**Comment by znarf** [comment]
Just replaced the word "kill" with "remove" in the proposal. Less violent language!
