### ISSUE TITLE
[DOCS] Activity log

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5875]
## Context
[[Project] Collective activity log](https://github.com/opencollective/opencollective/issues/5195)

### What's changing?
We're introducing a new feature that will allow people to see a history of what happens on their accounts, making it easier to understand changes and spot suspicious activity.

### Why are we changing it?
Auditability, security.

### Who does this change impact?
- Host admins: history of payments, collective applications, collective activities (like admin changes), etc
- Collective admins: history of everything happening on the collective (new contributions, admin changes, info updates, etc)
- Users: all actions initiated on/by a user account

### How do users use it?
By going to Admin > Activity log

### Is this change optional or mandatory?
The public release will happen for everyone / all profile types.

### Is this change being released incrementally as a beta? What's the schedule?

_Exact dates TBD._

- [x] Enable by default on dev/staging
- [x] Team release: everyone will have access as early as possible to test & improve
- [ ] Public beta: We may enable on a few trusted accounts
- [ ] Public release: we may enable for some profile types (e.g. Users) only at the beginning if we're not satisfied with the results

### When will the project be ready for release/complete?
_Exact dates TBD._

## Docs Process
We can start documenting as early as possible, keeping just a warning at the top of the page while it's in beta.

### Overview
- Document the feature from the user's point of view
- Document the feature from the host admin's point of view
- Document the feature from the collective admin's point of view

### Changes to be made
- [ ] Create the page(s) to document for users/host admins/collective admins
- Document limitations:
  - [ ] Old activities may hold incomplete information (e.g. _missing author_)
  - [ ] Old actions may not be surfaced (e.g. "Updated collective information" did not exist before the release of this feature)

### Estimate of effort
There's some work to be done, many parts will need screenshots. We'll start to synchronize with @opencollective/documentation when the interface will feel ready for a photo shoot!

**Comment by shannondwray** [comment]
Ping me when I can test this/initiate photoshoot time! 🤟🏼

**Comment by mtrackeros** [comment]
Hi all

**Comment by Betree** [comment]
I added some testing instructions at https://github.com/opencollective/opencollective/issues/5912 and recorded a loom to give a walkthrough of the feature here: https://www.loom.com/share/2d6eed14902f4017b1b7cdd0c059903d .

I don't think that we need a lot of text to explain this in the docs. Regarding the overall structure of the docs page, I can suggest the following draft. Please let me know if you need any more content or info from my side!

# Activity log

The Activity Log gives users the ability to track everything happening through their accounts and hosted accounts.

## For user profiles

### 1. Click on the user menu
![Step 1 screenshot](https://images.tango.us/workflows/428fd8e5-2b26-4241-95b2-9b2012f17316/steps/bcc8b341-7153-4bd8-8cd4-b4156f7e9a34/bbd6a299-9cfd-4d8b-800f-024a776e05b6.png?crop=focalpoint&fit=crop&fp-x=0.9654&fp-y=0.0351&fp-z=2.9196&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A941)


### 2. Click on Settings
![Step 2 screenshot](https://images.tango.us/workflows/428fd8e5-2b26-4241-95b2-9b2012f17316/steps/4fbe6c41-507b-4577-866c-467d9c00082c/50f33af3-9a3a-46f7-a440-827063f73111.png?crop=focalpoint&fit=crop&fp-x=0.7156&fp-y=0.3618&fp-z=3.1440&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A941)


### 3. Click on Activity log
![Step 3 screenshot](https://images.tango.us/workflows/428fd8e5-2b26-4241-95b2-9b2012f17316/steps/3989656d-7195-4e15-bf5f-d0e755f29352/810719b0-8294-4780-882e-6b29342e5dab.png?crop=focalpoint&fit=crop&fp-x=0.2255&fp-y=0.5802&fp-z=2.4000&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A941)


### 4. You can filter by period
![Step 4 screenshot](https://images.tango.us/workflows/428fd8e5-2b26-4241-95b2-9b2012f17316/steps/ae42af68-5bdd-4b4e-88c1-343b805f525f/1312e832-4e3b-4367-af74-374a8def4dae.png?crop=focalpoint&fit=crop&fp-x=0.3943&fp-y=0.2147&fp-z=2.1239&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A941)


### 5. Or by activity type
![Step 5 screenshot](https://images.tango.us/workflows/428fd8e5-2b26-4241-95b2-9b2012f17316/steps/0c3b590b-bc1e-4a68-9b7d-fc62a2e29067/d9ce9f75-a47c-4902-9aa3-459517bc8fc3.png?crop=focalpoint&fit=crop&fp-x=0.5883&fp-y=0.3663&fp-z=2.3105&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A941)

## For Fiscal Hosts

### 1. Click on the user menu
![Step 2 screenshot](https://images.tango.us/workflows/2fec86a7-391c-46aa-b0e3-1ad5b7596423/steps/f07d8930-13c3-4459-b414-42a9a0307281/7e9c902d-0e48-4aa8-ad50-a9ee1e35f144.png?crop=focalpoint&fit=crop&fp-x=0.9654&fp-y=0.0351&fp-z=2.9196&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A941)


### 2. Click on the cog icon next to the profile you want to administrate
![Step 3 screenshot](https://images.tango.us/workflows/2fec86a7-391c-46aa-b0e3-1ad5b7596423/steps/d73d2d57-593a-49c3-a1a4-450612ba6a4b/5bc6b19b-c2e8-4f5c-ab9b-1ae899536428.png?crop=focalpoint&fit=crop&fp-x=0.9628&fp-y=0.4702&fp-z=3.1440&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A941)


### 3. Untitled step
![Step 4 screenshot](https://images.tango.us/workflows/2fec86a7-391c-46aa-b0e3-1ad5b7596423/steps/dae82ccf-4f20-4325-829d-b9dcb27d2f5b/127527af-37ff-4f5d-afa0-c994c91efb07.png?crop=focalpoint&fit=crop&fp-x=0.5000&fp-y=0.5000&fp-z=1.0000&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=295%3A535)


### 4. Click on Activity log
![Step 5 screenshot](https://images.tango.us/workflows/2fec86a7-391c-46aa-b0e3-1ad5b7596423/steps/e4e1b99a-db2f-4487-8e28-a6edd0ed9239/e2567c62-7a4d-4756-8064-f928574df3f4.png?crop=focalpoint&fit=crop&fp-x=0.2255&fp-y=0.7046&fp-z=2.4000&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A941)


### 5. Filtering
Using the "Account" filter, you can narrow down the list of results to include only a limited number of hosted collectives, or all of them.
![Step 6 screenshot](https://images.tango.us/workflows/2fec86a7-391c-46aa-b0e3-1ad5b7596423/steps/0986628e-bb23-42de-b57e-ea1957ae74ce/8196251b-3394-4775-8347-a8b8095da385.png?crop=focalpoint&fit=crop&fp-x=0.7326&fp-y=0.2147&fp-z=3.0332&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A941)

## For Collectives

You can access the activity log from Settings > Activity Log. Collectives can also filter by children's accounts (projects & events).

## Caveats

- We're still missing some important activity types (https://github.com/opencollective/opencollective/issues/5909)
- Some entities (updates, conversations, etc) are not yet linked properly from this list
- We did our best to migrate existing activities, but cannot guarantee that everything that happened before November 2022 was properly recorded.

**Comment by shannondwray** [comment]
Moved here: https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Documentation-Releases_sul57#Project-Releases_turYe/r168&view=modal
