### ISSUE TITLE
Remove team member invite

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5878]
> As an admin I want to cancel an invitation to become and admin of my Collective.

Case in point, I invite a user to a Collective and they asked that I invite their other email address (which is used for a profile elsewhere), I sent and invite to the user's profile but I can't delete the previous invitation:

![Screenshot 2022-08-19 at 10 15 56](https://user-images.githubusercontent.com/158833/185587703-ac6b291b-29e9-4eb2-bb19-d20e4f5230db.png)

**Comment by Betree** [comment]
Looks like we need to add a `removeMemberInvitation` mutation in `api/server/graphql/v2/mutation/MemberInvitationMutations.js` to make that possible.

**Comment by snitin315** [comment]
@Betree I believe we already have this ability in API via the removeMember mutation. 

https://github.com/opencollective/opencollective-api/blob/86db7a25f1588028bb355f9f748308c61b645741/server/graphql/v2/mutation/MemberMutations.js#L202

https://github.com/opencollective/opencollective-api/blob/86db7a25f1588028bb355f9f748308c61b645741/server/graphql/v2/mutation/MemberMutations.js#L242


Looks like something changes recently in the frontend, earlier it was possible to remove invitations.

**Comment by Betree** [comment]
@snitin315 Indeed. This API is confusing, we're using dedicated mutation to `sendMemberInvitation` and `editMemberInvitation`, it's unclear why didn't take the same approach for removing invitations. Would be great to improve that at some point, but for now a frontend fix should be enough.

It seems that it was introduced in https://github.com/opencollective/opencollective-frontend/pull/7771 and then iterated on with https://github.com/opencollective/opencollective-frontend/pull/7972. We should make sure we take the "Minimum number of admins" constraint into account while resolving this.
