### ISSUE TITLE
Defining Host and Parent relationships

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#588]
After latest migration, Hosts can now only be USER or ORG. This breaks Super Collectives (like Brussels Together, Open Source, etc) because Host was synonymous with Super Collective previously. It also introduces another depth to our tree.

So, following is going to be a typical setup now: 
Host (OC C6) => Super Collective (Open Source Collective) => Collective (Webpack) => Event (Webinar)

Here's what each depth should see (with icons indicating what's currently happening).

1. Host
    a. ✅ Collectives shown: All collectives
    b. ❌  Budget: it's own (available in the future) and all children 
    c. ❓ Funds Available: it's own (available in the future) and it's children's (cumulative)
    d. ❓ Transactions: it's own and it's children's (cumulative)
2. Super Collective
    a. ✅ Collectives shown: Event (rest of collectives shown at Host level instead)
    b. ❌ Budget: It's own + any of it's events
    c. ❌ Funds available: only it's own + any of it's events
    d. ❌ Transactions: only it's own + any of it's events
3. Collective (Webpack)
    a. ✅ Collectives shown: Event
    b. ❌ Budget: it's own and Events (same as #2)
    c. ❌ Funds Available: it's own and Events (same as #2)
    d. ❌ Txns: it's own and Events (same as #2)
4. Event
    a. ✅ Collectives shown: n/a
    b. ❌ Budget: it's own (though likely not being used this way, can be ignored)
    c. ❌ Funds Available: it's own (again not clear this is a real use case yet but we'd like it to be)
    d. ❌ Txns: it's own (same caveat as above)

If we can make all of the above work , we should be fine for now. (We don't need to worry about greater depth immediately).

Some things we can do to simplify:
- All requirements under Host can be solved by putting "HostCollectiveId" with every child Collective (currently only parent collectives have it). This will make it easy to query everything for the Host.
- Parent relationships are overloaded and we only store one type of it in `Collectives` table. We need to pull it out in Members table to express different type of relationships. Two obvious ones: Collective -> Event ("SubLedger" - meaning parent owns full ledger of child) and Super Collective -> Collective ("Budget" - meaning only budget is rolled up).

- We treat Super Collective as a parent of regular collectives. One other way to simplify is to leave regular collectives at the Host level. So, Host => [Super Collective, (Collective => Event)]. Then, to find out all open source collectives, you visit opencollective.com/opensourceorg. This means we would need to update our Discover page to show you all Open Source collectives, etc.

Let's talk about it live @xdamman and figure out way to store these relationships cleanly. I think it's the last big missing piece to finish the data migration.

**Comment by asood123** [comment]
The other tricky part in all of this is to fetch data two levels deep. For example, how to include Webpack Webinar's transactions and budget in Open Source Collective's budget. One way to deal with is to also define "Budget" parent relationship between Webinar Collective and Open Source Collective. That way a single query from Members table can get us all the data to include.

**Comment by piamancini** [comment]
is this still relevant?

**Comment by piamancini** [comment]
guess not. closing for now.
