### ISSUE TITLE
Activity log: improve activities descriptions

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5881]
Already identified some, but there may be more:
- [ ] COLLECTIVE_EXPENSE_MISSING_RECEIPT
- [ ] COLLECTIVE_EXPENSE_APPROVED
- [ ] COLLECTIVE_EXPENSE_UNAPPROVED
- [ ] COLLECTIVE_EXPENSE_PAID
- [ ] COLLECTIVE_EXPENSE_MOVED
- [ ] VIRTUAL_CARD_CHARGE_DECLINED
- [ ] COLLECTIVE_CORE_MEMBER_REMOVED
- [ ] COLLECTIVE_VIRTUAL_CARD_SUSPENDED
- [ ] COLLECTIVE_CONTACT
- [ ] COLLECTIVE_CORE_MEMBER_ADDED
- [ ] COLLECTIVE_CORE_MEMBER_INVITED
- [ ] COLLECTIVE_CORE_MEMBER_INVITATION_DECLINED
- [ ] COLLECTIVE_CORE_MEMBER_REMOVED
- [ ] COLLECTIVE_CORE_MEMBER_EDITED

**Comment by SudharakaP** [comment]
@Betree : I think we also have to add all the `COLLECTIVE_CORE...` activities as well here. I've edited the original issue and added them.

**Comment by Betree** [comment]
@SudharakaP Good call, feel free to edit again if you spot any other missing activities

**Comment by Betree** [comment]
Related: we should implement these translations as dynamic strings with variables. The one below, for example, should be: `New expense submitted to <Link>Babel</Link> from <Link>Suds</Link>`.

![image](https://user-images.githubusercontent.com/1556356/186110834-d16a4a15-69ce-4719-95d6-70c6b554dc41.png)
