### ISSUE TITLE
GraphQL: Filtering accounts by host

### ISSUE THREAD

**Issue by MattIPv4** [opencollective/opencollective#5882]
## User story 

As a developer wanting to feature open-source projects from OpenCollective on another site (Hacktoberfest), I'd like to be able to fetch projects from a specific OpenCollective host via the GraphQL API.

## Best solution for this problem

Adding a `host` filter to the `accounts` query in GraphQL, likely accepting slugs.

E.g.

```gql
{
    accounts(
        host: ["opensource"] # <-- This
        type: [COLLECTIVE, PROJECT]
        isActive: true
        hasCustomContributionsEnabled: true
        supportedPaymentMethodService: [STRIPE, PAYPAL]
        offset: 0
        limit: 5000
    ) {
        totalCount
        nodes {
            slug
            name
            description
            
            ... on AccountWithHost {
                host {
                    slug
                }
            }
        }
    }
}
```

## MVP

Adding the filter to the accounts query.

## Metrics 

Observing incoming GraphQL requests making use of the new filter.

## Documentation 

https://graphql-docs-v2.opencollective.com/query.doc.html

```
# tag: Only accounts that match these tags
# host: Only accounts that match these hosts
# type: Only accounts that match these account types
```

_Hope I filled this out well enough for y'all 💙_

<details>
  <summary>Triage Template (team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by MattIPv4** [comment]
Ahah! It looks like that does return everything under the OSC, which is great, but I don't then see a way to include the payment filters we're suing at the same time 🤔:

```
isActive: true
hasCustomContributionsEnabled: true
supportedPaymentMethodService: [STRIPE, PAYPAL]
```

**Comment by BenJam** [comment]
@MattIPv4 can you inlude information about the process you used last year, so we can make sure you have what you need this?

**Comment by MattIPv4** [comment]
👀 Sure -- we're listing OC projects on https://hacktoberfest.com/donate/ as we did last year. We're currently listing any OC project that has the `hacktoberfest` tag, and that has custom donations enabled (so we can embed the donate page for the project).

It came up in one of our planning calls with y'all this year that it might be nice to expand this to list all projects under the OSC, rather than just those that have the tag, hence the ask here (both filtering to a host, but also in a way where we can also filter based on custom donations being enabled).

The query we're currently using:

```gql
{
    accounts(
        tag: "hacktoberfest"
        type: [COLLECTIVE, PROJECT]
        isActive: true
        hasCustomContributionsEnabled: true
        supportedPaymentMethodService: [STRIPE, PAYPAL]
        offset: ${offset}
        limit: ${limit}
    ) {
        totalCount
        nodes {
            slug
            name
            description
            imageUrl
        }
    }
}
```

The donate embed URL:

```
https://opencollective.com/embed/${slug}/donate?disabledPaymentMethodTypes=MANUAL&tags=hacktoberfest
```

**Comment by Betree** [comment]
Implemented in https://github.com/opencollective/opencollective-api/pull/8159
