### ISSUE TITLE
Add Activities for Different Collective Type Creation

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5884]
We currently only have activity for collective creation (`COLLECTIVE_CREATED`) but there's no specific activities recorded when creating a project, event, orgnaization. We need add `EVENT_CREATED` and `PROJECT_CREATED` activities to the activity log when these events are triggered. 

- [ ] Add an activity after creating an event in `CreateEventMutation.js`
- [ ] Add an activity after creating an project in `CreateProjectMutation.js`
- [ ] Add an activity after creating an org in `CreateOrganizationMutation.js`

**Comment by Betree** [comment]
Good catch!

Some notes:
- Organizations used to have a proper `ORGANIZATION_COLLECTIVE_CREATED` event on [GraphQL V1](https://github.com/opencollective/opencollective-api/blob/4d21b5ae817b9dbd8601c3f3f99764b641656f67/server/models/Collective.js#L3389). We can re-use this one.
- Funds are created with a `COLLECTIVE_CREATED` activity. We may want to move them to a dedicated `FUND_CREATED` activity.

For all accounts without a "Create" activity, we should, in the migration, insert some with `activity.createdAt = account.createdAt`.

cc @znarf, a design decision we need to make here is whether we want to have one activity type per account (EVENT_CREATED, PROJECT_CREATED, etc) or a generic one like `ACCOUNT_CREATED`. I personally prefer this second approach, but the 1st might be simpler to implement.

**Comment by SudharakaP** [comment]
@Betree : If no objections I am taking this and will go with your suggestion of creating a generic activity `ACCOUNT_CREATED`.
