### ISSUE TITLE
Filter expenses by no tag

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5889]
## User story 
As a Collective admin, I want to be able to surface untagged expenses, so I can ensure all expenses are tagged and fined missed ones (especially now that we're going to have a financial report displaying budgets by tag I think this will become more common)

## Best solution for this problem
Add an `untagged` option here on the expenses page:

![Screen Shot 2022-08-23 at 10 38 18 AM](https://user-images.githubusercontent.com/5498878/186030972-cf8a1400-71b1-4e08-9595-ad38657f7a16.png)

## Metrics 
Fewer untagged expenses

  P3 high frequency, low impact

**Comment by Betree** [comment]
We already support passing `null` as a tag to the API. I suggest that when making such a query:

```gql
{
  expenses(tag: null) {
    totalCount
  }
}
```

We return all expenses without tags.

For the frontend, @alanna's solution above sounds ideal to me.
