### ISSUE TITLE
Convert all models to Typescript

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#5893]
Models have a central role in our code. They're used pretty much everywhere and are usually responsible for binding data inputs to the database. Having them converted to Typescript will therefore improve our coverage in many places, making the code safer.

Today, about half of our models are already using Typescript, and it's the [default documented way](https://github.com/opencollective/opencollective-api/blob/d9a5754bf36b58d6c43f78c14a609b72a49c5334/docs/adding-new-models.md#L1) to create new models. We want to convert the remaining ones.

**For everyone willing to contribute to this:** opening smaller pull requests with only one or a few converted models is very welcome and actually preferred to a giant one that would be more difficult to test & review!

- [x] `server/models/Application.js` => @rxbryan 
- [x] `server/models/Collective.js` => https://github.com/opencollective/opencollective-api/pull/8658
- [x] `server/models/Comment.js` => https://github.com/opencollective/opencollective-api/pull/8255
- [x] `server/models/ConnectedAccount.js` => https://github.com/opencollective/opencollective-api/pull/8248
- [x] `server/models/Conversation.js` => https://github.com/opencollective/opencollective-api/pull/8256
- [x] `server/models/ConversationFollower.js`
- [x] `server/models/DataTypes.js` => https://github.com/opencollective/opencollective-api/pull/8250
- [x] `server/models/EmojiReaction.js` => https://github.com/opencollective/opencollective-api/pull/8239
- [x] `server/models/Expense.js` => https://github.com/opencollective/opencollective-api/pull/8340/files
- [x] `server/models/index.js` => https://github.com/opencollective/opencollective-api/pull/8241
- [x] `server/models/LegalDocument.js`
- [x] `server/models/Member.js`
- [x] `server/models/MemberInvitation.js`
- [x] `server/models/Order.js` => Reserverd to the core team
- [x] `server/models/PaymentMethod.js`
- [x] `server/models/RequiredLegalDocument.js` => https://github.com/opencollective/opencollective-api/pull/8254
- [x] `server/models/Subscription.js` => https://github.com/opencollective/opencollective-api/pull/9194
- [x] `server/models/Tier.js` => https://github.com/opencollective/opencollective-api/pull/8250
- [x] `server/models/Transaction.js` => @Betree 
- [x] `server/models/Update.js` => https://github.com/opencollective/opencollective-api/pull/8596
- [x] `server/models/User.js` => https://github.com/opencollective/opencollective-api/pull/8245

**Comment by jacoobanderson** [comment]
I could work on this one if that's okey.

**Comment by Betree** [comment]
@jacoobanderson Sure! Feel free to open PRs linking to this issue, ideally small ones - one model per PR - to facilitate the review.

**Comment by ShreyaPrasad1209** [comment]
Hi, can I take up this issue if it's still available ? @Betree

**Comment by Betree** [comment]
> Hi, can I take up this issue if it's still available ? @Betree 

Sure! Contributions for this one are welcome, just don't do everything in one go; we recommend making one pull request per converted model to simplify the review & merge process.

**Comment by hjaintech** [comment]
@Betree Can I take up typescript migration for [LegalDocument.js](https://github.com/opencollective/opencollective-api/blob/main/server/models/LegalDocument.js)?

**Comment by Betree** [comment]
@hjaintech Be welcome! I've assigned it to you in the issue description.

**Comment by rxbryan** [comment]
Hi @Betree I can see that Application.js and collective.js has no been worked on. 
Could you assign them to me? I would like to work on them.

**Comment by Betree** [comment]
Hi @rxbryan, we prefer to reserve the `Collective` model for the core team as it's a really large one used in many places.

Feel free to start working on `Application`, I've assigned it to you in the issue description.

**Comment by rxbryan** [comment]
@Betree take a look at the pr https://github.com/opencollective/opencollective-api/pull/8473

**Comment by ashutosh887** [comment]
I would like to work on this issue

**Comment by Betree** [comment]
@ashutosh887 One at a time, please complete your already-assigned PRs and ask again once they're merged
