### ISSUE TITLE
Introduce limits on contributions on the platform

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5895]
We need to put in place limits on all contributions, regardless of whether they're successful or not. 

## Proposal

In my opinion It's not normal to:

- make more than two contributions to a collective in a short period (1 hour)
- make more than five contributions to multiple collectives in a short period (1 hour)
- make contributions from more than five different payment methods over a long period (1 month)

Alternatively, e can leave this to be configured i[n the payment processor's (in our case, Stripe's) anti-fraud product](https://stripe.com/docs/radar/rules/reference#supported-attributes). An example ruleset might be 

- block if number of authorised charges against card is X per hour and/or day
- block if number of authorised charges per 'customer' (or email address) is X per hour and/or day
- block if number of authorised charges per IP address is X per hour and/or day

I'll take a look at what constitutes 'normal' behaviour for us by looking at payment methods in our DB. 

## Exclusions

We may need to implement an exclusion for recurring contributions, which are charged separately:

- [ ] https://github.com/opencollective/opencollective/issues/4206 
- [ ] https://github.com/opencollective/opencollective/issues/1916

**Comment by kewitz** [comment]
Specifications:
- Add a new validation step when creating orders.
- This new step will take into consideration:
  - The error rate of orders
  - The payment method creation rate (take into consideration deleted ones)
- Throws if looks fishy (parameters to be defined and tuned through env variable)
 
Should we take into consideration the rate of successful order creation?

**Comment by BenJam** [comment]
> Should we take into consideration the rate of successful order creation?

Absolutely 100% yes, this was the thing that costs us thousands of dollars last month.
