### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by developit** [opencollective/opencollective#5897]
OpenCollective website is down. It's just returning a CloudFlare error.

**Comment by Betree** [comment]
Hi @developit, our hosting provider (Heroku) is currently down. We're monitoring the situation. https://status.heroku.com/incidents/2453

**Comment by developit** [comment]
Oh! I should have checked that, sorry!

**Comment by Betree** [comment]
@developit Thanks for opening an issue, that could have been helpful!

The situation is resolved now, sorry for th inconvenience it caused.
