### ISSUE TITLE
several users reported unable to get their invoices

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#590]
All donations are going in today, so several users are hitting this. 
Here's an example: https://opencollective.com/24pullrequests/transactions/e1815f9f-5577-462c-ab2b-a2dab0a6c8d4/invoice.pdf

@asood123 assigning to you since @xdamman I think is flying.

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by piamancini** [comment]
@asood123 another from suscriptions https://opencollective.com/opensource/transactions/07e8cab6-c441-4f1c-bf6c-dec77406e4c0/invoice.pdf

**Comment by asood123** [comment]
Hacky fix here: https://github.com/opencollective/opencollective-api/pull/993. We need to find a better place to store a host's address.
