### ISSUE TITLE
Add/remove myself as an admin to perform actions on the collective

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#5907]
There are _many_ additions that are being considered for support ops (root actions) https://github.com/opencollective/opencollective/issues/5906

Some of these merely require you to add yourself as an admin, make some modifications, and then remove myself. I find myself doing this from time to time when it's just easier/faster than handing out some docs and waiting for the user to do it themselves.

**Comment by znarf** [comment]
I think it's more a matter for Root admins to be able to perform actions, without being a Collective admin.
