### ISSUE TITLE
OAuth: Keep getting 403 from /oauth/token on deployment

### ISSUE THREAD

**Issue by izznatsir** [opencollective/opencollective#5910]
**Describe the bug**
I keep receiving 403 response from https://opencollective.com/oauth/token.

It only happened on the deployed version on Cloudflare Pages, it works locally. The error message says error code 1020.

**To Reproduce**

I need to create a minimal repo, but, I cannot do it right now.

**Expected behavior**
Works both on deployment and locally.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 104

**Additional context**
I use Remix for the framework. Deployed on Cloudflare Pages. I have checked that client_id and client_secret is correct on deployment.

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by znarf** [comment]
Can you give us some information on your deployment? Is this something we can test ourselves?

What's the full body of the response looking like?

At what time have you tried for the last time?

We generally don't see 403 errors in the logs for this URL, so we'll need to dig a bit deeper with your help.

**Comment by izznatsir** [comment]
I can create a minimal reproduction that you can deploy yourself, maybe by doing that, I could also reduce the noices.

The last time i tried is around 3 to 4 hours ago.

I'll let you know when the reproduction is ready.

**Comment by znarf** [comment]
I see 404 errors in that timeframe, maybe the parameters are wrong in your Cloudflare Pages setup?

**Comment by izznatsir** [comment]
Thanks for taking a look at the logs!

I'm sure that I already check that the parameters are correct, bu I'll do another check.

**Comment by izznatsir** [comment]
Here is the reproduction:

https://github.com/izznatsir/cfpoc-remix

you still need to clone this repo and create your own oauth app to test it. But, if you want to, you can check what I deployed:
https://cfpoc-remix.pages.dev

**Comment by izznatsir** [comment]
Is there any CORS restriction for OAuth token request?

**Comment by znarf** [comment]
CORS is not relevant for backend requests.

I was able to find the problem, it was in our firewall configuration (at Cloudflare), it should be working now!

**Comment by izznatsir** [comment]
Cool! It's working now. Thank you!
