### ISSUE TITLE
Do not show minimum admins on application for hosts that don't require it

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5915]
**Describe the bug**
Even though OCNZ has no minimum admins setting, it's showing minimum admins in the application form.

This is confusing and would block a single admin Collective form applying even if that's not what the host intends.

**To Reproduce**
1. Have a host without the minimum numbers of admins policy
2. Apply to it
3. See minimum admins section in form

**Expected behavior**
Do not show the minimum admins part of the form for hosts without any minimum admins setting

**Screenshots**
Not set in policies:
<img width="1025" alt="Screen Shot 2022-08-29 at 12 58 52 PM" src="https://user-images.githubusercontent.com/5498878/187104354-9b986298-e5b4-417c-9bb9-f2a4a8fff365.png">

Showing in application form:
<img width="548" alt="Screen Shot 2022-08-29 at 1 14 10 PM" src="https://user-images.githubusercontent.com/5498878/187104374-44c043ef-3cb9-4a77-a1ae-51a1b9c76389.png">

  P2 low frequency, high impact

**Comment by Betree** [comment]
Seems like a very easy one to fix in https://github.com/opencollective/opencollective-frontend/blob/2b548d84a7bdb9836bae9a2ffde080dde3f36a6d/components/ApplyToHostModal.js#L460

cc @kewitz
