### ISSUE TITLE
Macron should default to non-macron character not hyphen

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5916]
<img width="242" alt="Screen Shot 2022-08-29 at 1 11 54 PM" src="https://user-images.githubusercontent.com/5498878/187104836-335e516a-289c-4cb0-8bc1-98bbf874c67d.png">

When a macron isn't possible to have in a string (like a URL slug) it should default to the non-macron version of that letter, not a hyphen, e.g. o instead of ō for 'Pōneke'. This will come up more often now that more NZ Collectives are starting up, as macrons are commonly used in Māori.

**Comment by Betree** [comment]
I've opened an issue with the library we're using to do that: https://github.com/lovell/limax/issues/44. It fits well with their philosophy, as characters like `é` are already replaced with `e`.

**Comment by Betree** [comment]
Found a potential solution and opened a PR for it at https://github.com/lovell/limax/pull/45. If not accepted, we can easily implement the change on our end.

**Comment by Betree** [comment]
The root cause has been fixed in the root library; this should not happen with new collectives in the future (changes not yet deployed).
