### ISSUE TITLE
'Project' Budget Hover info isn't correct

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#5925]
The hover over `Today's Balance` of a **Project** says: `The current balance of the account. Not including Projects and Events.` This is not correct, and confusing.
![image](https://user-images.githubusercontent.com/64920686/187538001-e1204de1-e8d7-46dc-9c48-7813f4ecca80.png)

**Comment by znarf** [comment]
That's right we should not have the tooltip for Projects and Events.
