### ISSUE TITLE
Collective page: wrongfuly displayed tiers pagination

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5928]
**Describe the bug**
On https://opencollective.com/foodandsolidarity this arrow seems random and it doesn't do anything when clicked.

<img width="1451" alt="Screen Shot 2022-09-02 at 9 06 51 AM" src="https://user-images.githubusercontent.com/5498878/188013392-1e887708-29de-4297-a93b-145764840b39.png">

**Expected behavior**
Probably this should only appear when there are many cards to scroll horizontally?

  P4 low frequency, low impact

**Comment by Betree** [comment]
@alanna Can you share more info on screen size / browser? I can't reproduce it on Chrome/Firefox

**Comment by alanna** [comment]
MacBook Pro M1 13" in chrome

**Comment by Betree** [comment]
@kewitz Found how to reproduce this:
1. Go to https://opencollective.com/foodandsolidarity
2. Click on https://opencollective.com/elswicksolidarityfund
3. Resize the window
4. Go back

Basically, `withViewport` or `HorizontalScroller` does not seem to be updated properly when going from one collective page to the other.

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted, and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by JoyLubega** [comment]
hey @ersachin3112 How far with this. Do you need any help

**Comment by Betree** [comment]
The [pull requested](https://github.com/opencollective/opencollective-frontend/pull/8166) that was started on this went stale, the bounty is now open again.

**Comment by JoyLubega** [comment]
I will pick it up

**Comment by Betree** [comment]
:trophy: This issue has been completed by @JoyLubega  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
