### ISSUE TITLE
Changes for WWCode Merida

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#593]
Mail from Brittani:

> It seems as though the amount available in Merida is USD$399.75. Can you change the Q1 Activity Bonus of USD$200 to MXN$3554.06? 
> https://opencollective.com/wwcodemerida/transactions
> ![unnamed-3](https://user-images.githubusercontent.com/30665166/32311688-f6a14bd4-bf67-11e7-8941-77f7a138d533.png)

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by piamancini** [comment]
this is now assigned to @xdamman or @asood123 for change in DB

**Comment by nicobarretoOC** [comment]
Adding to this, mail from Brittani:

> Hey Pia - it looks the OC Is in a mixture of MXN and USD. Those MXN$506.16 MXN$60 Meetup, and MXN$60 global development transactions were all USD.  
> 
> I just need for the available funds to display correctly in MXN or USD so I can reconcile. And also need to be able to mark the outstanding expenses (in MXN) as paid.

**Comment by piamancini** [comment]
assigning a higher priority to this. It's blocking wwcode from reconciling their ledger.

**Comment by asood123** [comment]
done
