### ISSUE TITLE
Wise: Automatically set OTT = true when dealing with European countries

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#5941]
Right now we need to manually set each host account to be compatible with Wise OTT flow and this means that every time a new host joins the platform from Europe or the UK, they'll face some kind of error before they can use Wise for the first time.
We should automate the onboarding process by setting `settings.transferwise.ott = true` when a collective connects to Wise from any European country.

**Comment by Betree** [comment]
We may want to use the `isMemberOfTheEuropeanUnion` helper from lib taxes
