### ISSUE TITLE
Updating virtual card charge expenses does not create activities

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5943]
## Who is your user?
Viewer of an expense

## What are they trying to achieve?
When I view an expense I want to see status updates posted in the comment feed so that I can understand what's happened with it over time.

E.g I just went and added a receipt to [this expense](https://opencollective.com/comms-docs/expenses/93956) but it doesn't show that in any way when viewing it. I expected it to have a date stamped status update saying "Alanna edited this expense" if not more detail like "Alanna uploaded a receipt". I think it does record such actions when editing other aspects of an expense?

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [x] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment]
This seem to happen only with virtual card charges, I'm looking at it
