### ISSUE TITLE
Option to stop all contributions when deleting a tier 

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#5947]
## User story 
As a collective admin, I can choose whether the financial contributions associated with a tier are cancelled when the tier is cancelled so that if the tier is associated with a membership or access to a course when the course is shut down the financial contributions can be stopped as well. 

## Best solution for this problem
A tick box or something within the window when you are deleting a tier asking if you'd like to stop all financial contributions. 

<details>
  <summary>Triage Template (team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by znarf** [comment]
To give some context, we often get people deleting Tiers, then being afraid that recurring contributions would be stopped. They generally don't want it but having the checkbox would make the outcome clearer.
