### ISSUE TITLE
BUG validating collective with GH 

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#595]
Message from David:
> I tried to create a new collective but the form was not able to validate and go to the next page.
> 
![unnamed](https://user-images.githubusercontent.com/30665166/32312049-a993c8c4-bf69-11e7-905e-83132b4ab0dc.jpg)

> When I reloaded the page, I found that few projects were created (I clicked on the button few times).
> 
> Are you able to remove:
> - https://opencollective.com/front-end-checklist-211 
> - https://opencollective.com/front-end-checklist-330 
> - https://opencollective.com/front-end-checklist-417 
> - https://opencollective.com/front-end-checklist-703 
> - https://opencollective.com/front-end-checklist-8

**Comment by piamancini** [comment]
closing this since it duplicates #555
