### ISSUE TITLE
I can't access to my account anymore because signin email is not delivered > how can I change my account email?

### ISSUE THREAD

**Issue by loois33** [opencollective/opencollective#5958]
**Describe the bug**
I cannot access to my account jeanlouis@imajique.be because I can't get the link delivered to my inbox. 

**To Reproduce**
I click on signin link, I enter my email, I don't get the email with the link. 
But if I try with another OC account/email, it works. 
It seems that something's wrong between OC and that specific email because my inbox works fine (I've sent and received other emails). 

**Additional context**
How can we change the account email without accessing it..? :/ 

I'm sorry if Github is not the right place to get support on this but I could'nt find another way.. (don't hesite to lead me to another support channel). 

Thank you ! 

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by znarf** [comment]
There were effectively problems delivering emails to your Inbox, this should be good now.

**Comment by loois33** [comment]
Ho wonderful thanksss!! 

(for my knowledge, could you tell what happened?)

**Comment by znarf** [comment]
On September 12st, your inbox was not working properly (from our provider perspective) and our email provider stopped trying to send emails to you from this point. I just unblocked it.

> 5.1.1 The email account that you tried to reach does not exist. Please try 5.1.1 double-checking the recipient's email address for typos or 5.1.1 unnecessary spaces

**Comment by loois33** [comment]
Ok I see. Indeed it was blocked for a few days.. 

Thank you very much for your lightning support

**Comment by loois33** [comment]
PS: was Gihub the best channel to ask for support for that kind of issue?

**Comment by znarf** [comment]
Good question :-)

No, it's not http://opencollective.com/support or support@opencollective.com are the most reliable.

**Comment by loois33** [comment]
OK thank you, I'll remember it.
