### ISSUE TITLE
DB cleaning

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#596]
There are 97 users that don't have a `CollectiveId` (and therefore no user profile). It's breaking a few things in the code. I want to add a `not null` validation to the model but we first need to clean existing data. We should either remove those rows or create a user collective for them.
There are only 8 of those rows with an email address. So should be quick.

**Comment by xdamman** [comment]
Just need an explanation on those 8 users. You can see them with this filter on the `Users` table:
"CollectiveId" IS NULL and "email" IS NOT NULL

**Comment by piamancini** [comment]
@xdamman fixed the dot net one. We missed that when we created a host org for them the other day. The rest of them I have no idea why they don't have a host. Some of them are probably related to the github flow

**Comment by piamancini** [comment]
this was done already. re-open if you find more cases.
