### ISSUE TITLE
Implement new OSC Signup Form

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#5973]
- [x] Copy existing form from ocf-host-application
- [x] Create additional information fields
- [x] Collect data from repository
    Define abstract data-type to be attached to `collective.data`. Generic interface so we can later connect with GitLab and other different providers.
    - [x] Is Fork
    - [x] Has an SPDX compliante license
    - [x] Recent activity
    - [x] Is owned by org
    - [x] Number of ~~contributors~~ collaborators (contributors not available in from the Github API)
- [x] Pre-fill information that we already fetched from the repository
    **? Should the user be able to edit this data?
    - [x] Repo URL
    - [x] License
    - [ ] ~~Commit Log~~
    - [ ] ~~Usage Link~~
- [x] Style based on Figma designs https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab-%F0%9F%A7%AA?node-id=16097%3A234377
- [ ] Tech-debt: Fetch information from GitLab
- [x] Attach repository data to `application.customData`.

**Comment by kewitz** [comment]
@iamronen @BenJam 
Should the user be able to edit the data we automatically got from their repository? (Repository URL, License, etc...)

Also, what is the Usage Link?

**Comment by iamronen** [comment]
To my understanding the auto-extraction from the repository is an assistive service so editing should be possible. Perhaps, if edited, there could be an indicator for the fiscal host admin? but I will defer this to @BenJam and @poohlaga

**Comment by BenJam** [comment]
> ? Should the user be able to edit this data?

the idea is that we avoid having to review, so if we detect good data then we shouldn't allow the user to edit as that would mean we would need to review. 

> ? What is Usage Link?

Something like this https://github.com/babel/babel/network/dependents though we need to keep it platform independent.

**Comment by kewitz** [comment]
@BenJam I'm considering not allowing the edit and seeing how it goes. @poohlaga also reported people were editing to impersonate different projects and fraud payments.
