### ISSUE TITLE
Collective image missing from contribute page social share

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#5977]
## User story 
As a collective admin, I can edit the social sharing image so that when I post on Social media it can represent our mission rather than being an Open Collective image 

https://opencollective.com/deep-adaptation-forum/contribute/roots-to-reach-appeal-45473

<details>
  <summary>Triage Template (team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by shannondwray** [comment]
![image (2)](https://user-images.githubusercontent.com/79115149/191048823-1a64afd3-a917-4044-b880-9a069485970e.png)

**Comment by Betree** [comment]
There's a larger conversation about letting users customize their social sharing images (https://github.com/opencollective/opencollective/issues/2660), but here we could have picked their image from the collective page. Will push a hotfix.
