### ISSUE TITLE
user can't login to cancel subscription

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#598]
User wants to cancel subscription and can't login 

<img width="1434" alt="screen shot 2017-11-02 at 8 26 18 am" src="https://user-images.githubusercontent.com/3671070/32332541-23d56848-bfbc-11e7-92ac-d452ccc82551.png">

Thank you for taking the time to report an issue 

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by piamancini** [comment]
@xdamman user emailed again, he can't login and asks for his subscriptions to be cancelled. 
(this needs to be done in Stripe and DB). 
Please look into login or cancel subscription manually.

**Comment by asood123** [comment]
We weren't lowercasing emails before checking for them in database. Fix here: https://github.com/opencollective/opencollective-api/pull/1004. Push going out shortly.

**Comment by piamancini** [comment]
good catch
