### ISSUE TITLE
Delete Virtual Card for Collective admins

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5991]
## User story 

As a Collective admin, I would like to delete a Virtual Card assigned to me because it was compromised or became unnecessary.

## Best solution for this problem

A "Delete card" action in the Virtual Card administration interface similar to the one available for Host admins.

## MVP

We already have "pause a card" that does half of the job.

## Metrics 

- How many cards are currently paused by Collective admins since the feature shipped?
- How many Collective admins are asking for a card to be deleted?
- How many deleted cards once the feature is shipped?

## Documentation 

We should update the Virtual Cards documentation from the Collective admins perspective, ensure the "Pause card" and "Delete card" features are covered.

**Comment by aminakazi** [comment]
I have a few questions around this flow.
1. If the admin taps on the 'delete' button and we show a modal pop-up asking them to confirm their decision, what all information do we want to provide the user (e.g., an info box saying that the card will be deleted instantly, etc).
2. Is there any input we want from the admin (e.g., Why do you want to delete this card?), etc?
3. Once deleted, will the card be visible to the user in an 'archived' section or tag?
4. How do we currently display the 'paused' card status? Is there a separate section? 👀

**Comment by hdiniz** [comment]
@aminakazi this is how it looks currently:

1. A confirmation modal is displayed to confirm deletion.
![delete card confirmation modal](https://user-images.githubusercontent.com/5448927/193675987-4b8f0be0-d883-43b5-98f0-5228e308ca02.png)

2. I think we should have some optional message input.
3. Deleted cards do not show up on the host or collective admin dashboard
4. We display paused cards on the same section, the only difference is a tag on the upper right corner.
![active card](https://user-images.githubusercontent.com/5448927/193676910-220521fb-a889-4680-b394-ec1e6beae732.png)
![inactive card](https://user-images.githubusercontent.com/5448927/193677064-709f37cb-21e8-4026-b722-39964dff6475.png)
