### ISSUE TITLE
End-to-end tests regularly fail on app "approve transaction" connect host Paypal account...

### ISSUE THREAD

**Issue by sedubois** [OpenCollective/OpenCollective#60]
...while waiting for `#returnToMerchant` to appear. Relaunching build usually fixes issue. Race condition or overloaded Paypal API? What are possible solutions?

E.g:
- failed: https://circleci.com/gh/OpenCollective/api/1470
- rebuild passed: https://circleci.com/gh/OpenCollective/api/1471

````
[Approve Transaction] Test Suite
================================

...

Running:  connect host Paypal account
 ✔ Element <#loadLogin> was visible after 5072 milliseconds.
 ✔ Element <input#login_email> was visible after 1627 milliseconds.
 ✔ Element <input.button.primary.default> was visible after 50 milliseconds.
 ✖ Timed out while waiting for element <#returnToMerchant> to be present for 60000 milliseconds.  - expected "visible" but got: not found
...
```

Issue appears even when CircleCi parallelization is disabled and even when tests don't seem to be running at same time on different branches.

**Comment by xdamman** [comment]
It's a problem with PayPal which is very slow. Not sure how to address this.

**Comment by asood123** [comment]
I haven't seen this happen in a while. Let's reopen if it happens again.

**Comment by sedubois** [comment]
@asood123 that's because we're not pushing any changes to `opencollective-app` at the moment, but issue still there AFAIK. Low prio I'd say.
