### ISSUE TITLE
Cannot remove fiscal host from collective

### ISSUE THREAD

**Issue by RichardLitt** [opencollective/opencollective#6001]
I am trying to remove OSC as the fiscal host for https://opencollective.com/standard-readme. When I go into settings (presumably as an admin of that collective), I see the "Remove Fiscal Host" button. However, one removal, it continues to show that that collective is hosted by OSC. 

I expect it to be removed and then to no longer have a host. 

This could be a caching issue?

**Comment by znarf** [comment]
> This could be a caching issue?

Maybe, I just tested the flow and it worked flawlessly.

Could you share a video? Or give precise steps to reproduce?

**Comment by RichardLitt** [comment]
Seemed to work on a second run. I'm unsure why - may have been because it automatically was approved earlier. I admit I am confused. 

Thanks for the double-check.

**Comment by znarf** [comment]
I'm definitely convinced that this can be experienced, especially if handling in different browser tabs for example. 

Feel free to reopen if you figure steps that can be reproduced!

**Comment by RichardLitt** [comment]
Will do!
