### ISSUE TITLE
Funds are Not Displayed in Badges

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6002]
Related to the fresh-desk ticket; https://opencollective.freshdesk.com/a/tickets/125063. It seems that when we do, https://opencollective.com/ajv/organization.svg or https://opencollective.com/ajv/sponsor.svg we show the `organizations` and `collectives`, but we miss showing `funds` (for example this collective has Salesforce and Indeed as funds). 

I think we should also include funds here; 

https://github.com/opencollective/opencollective-images/blob/d83fa537dc795b195659faf1125e49a0841a447f/src/server/lib/graphql.js#L207

**Comment by znarf** [comment]
Go for it!
