### ISSUE TITLE
Move "Contact" feature to GraphQL V2

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6004]
Followup on https://github.com/opencollective/opencollective-frontend/pull/8238

Keeping contact on GraphQL V1 is dangerous because there will be a crash if a page using the account navbar (which has a contact button) does not fetch `legacyId`. This can be tackled today as the mutation doesn't affect cached data in any way.

Todo:
- [ ] Introduce a new `sendMessage` mutation on GraphQL V2 (use an `AccountReferenceInput` for the account)
- [ ] Mark `sendMessageToCollective` (GraphQL V1) as deprecated
- [ ] Update the frontend to use this new mutation

**Comment by Betree** [comment]
@znarf I'd like to put a bounty on this one, could you confirm the specs first? I'm wondering whether `sendMessage` is the best name, or if we should be more explicit (e.g. `sendMessageToAccount`). My personal pref goes to the first one.

**Comment by znarf** [comment]
`sendMessage` sounds good !
