### ISSUE TITLE
Create a Metabase dashboard to track 2FA adoption

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6007]
Part of https://github.com/opencollective/opencollective/issues/5289

In order to track the success of https://github.com/opencollective/opencollective/issues/5289 and follow the adoption of 2FA overall (as per https://github.com/opencollective/opencollective/issues/5289#issuecomment-1262481347, we may want to ultimately enforce 2FA for all active hosts admins), we want to introduce a new dashboard on Metabase that would surface:
- [x] How many fiscal hosts enable "Enforce 2FA"
- [x] How many/percentage of host admins who have 2FA enabled

It could also be useful to have more global stats on 2FA:
- [x] How many **organizations** enable "Enforce 2FA"
- [x] How many accounts

**Comment by hdiniz** [comment]
Metabase dashboard created for 2FA adoption: https://opencollective-metabase.herokuapp.com/dashboard/124-two-factor-authentication
