### ISSUE TITLE
Button shouldn't say save changes if no changes were made

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6012]
**To Reproduce**
1. Receive subsequent occurrence of recurring expense email and click through
2. Without making any changes, click next through all the steps
3. Button at the end says 'save changes'

**Expected behavior**
If no changes were made it should say 'submit'

**Screenshots**
![Screenshot_20221002-164410.png](https://user-images.githubusercontent.com/5498878/193437044-23a886bf-7e37-4f5b-95f6-ba4fe26ada30.png)

  P3 high frequency, low impact

**Comment by Betree** [comment]
New condition needs to be added here: https://github.com/opencollective/opencollective-frontend/blob/b14156e76c5d806716266b4cb9241ef12db2ede8/pages/expense.js#L690

**Comment by SudharakaP** [comment]
> New condition needs to be added here: https://github.com/opencollective/opencollective-frontend/blob/b14156e76c5d806716266b4cb9241ef12db2ede8/pages/expense.js#L690

@Betree : I believe the button should always be `Submit Expense` because we don't let the user just "Save" the edits the made without submitting. WDYT? 🤔

**Comment by Betree** [comment]
@SudharakaP Well, "saving" and "submitting" is the same thing, just different words.

The initial proposal was:
> If no changes were made it should say 'submit'

Calling a button just "Submit" is a bad UX practice: https://uxmovement.com/forms/why-your-form-buttons-should-never-say-submit.

The alternative proposal, `Submit Expense`, works but could let you think you're about to submit a *new* expense.

I suggest going with `Save Expense` as a label, regardless if there are changes or not in the form.
