### ISSUE TITLE
Recurring expense should not lead to creating new payee profile if logged out

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6013]
**Describe the bug**
If you click through a recurring expense email notification, but are not logged in, it asks you to start re-creating the profile details that are already saved to the expense.

**Expected behavior**
By definition, a recurring expense has been created by a registered account and the payee details are already known. If not already logged in, it should take the user to the login screen, instead of presenting a form asking for the payee details again.

**Screenshots**
What you see after clicking through if logged out
![Screenshot_20221002-164102.png](https://user-images.githubusercontent.com/5498878/193437258-788fd578-71d5-471c-a5d8-1c9004db3784.png)

**Comment by Betree** [comment]
cc @kewitz

**Comment by alanna** [comment]
@kewitz did you look at this? We really need to reduce dup profiles where possible

**Comment by kewitz** [comment]
@alanna I don't think this would cause duplicated profiles since we enforce unique emails.

**Comment by alanna** [comment]
This is till a poor user experience. Why should we make them fill out all the info again when we know who they are, know it's them, and know all this data already? It should force login and then have it all pre-filled.

**Comment by kewitz** [comment]
The merged solution will redirect the user to the login page if needed (force login) and then send them to review and submit the drafted expense.

Can you explain where our ideas diverge or what else is expected from this issue?

**Comment by alanna** [comment]
Ah sorry @kewitz I didn't realise you were already making those changes, that's great.
