### ISSUE TITLE
Bank account confirmation button should show total amount received

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6014]
**Describe the bug**
When a host admin is matching up incoming pending payments on the financial contributions list, they are comparing the amount received in the bank account to the number on the screen. The big blue button should display the amount we expect they should see in the bank transaction, not the amount going to the Collective after platform tip. The purpose of this moment is for the admin to confirm the amount received matches up, and make any adjustments needed. Right now it's showing the amount without tip on the button.

**To Reproduce**
1. Host dashboard > financial contributions
2. Find a pending transaction with a platform tip included
3. Compare number on button on screen with number in bank transaction
4. They don't match

**Expected behavior**
Blue button should show number expected received to bank account

**Screenshots**

The bank transaction shows $55 received for this transaction (as expected, it's $50 = $5 tip)
<img width="560" alt="Screen Shot 2022-10-03 at 10 48 05 AM" src="https://user-images.githubusercontent.com/5498878/193477875-9bbfe0af-3857-43a9-a2f0-794030496b6e.png">

But the confirmation screen displays $50 on the button
<img width="594" alt="Screen Shot 2022-10-03 at 10 46 28 AM" src="https://user-images.githubusercontent.com/5498878/193477885-8090a42a-bb9d-43ff-b167-6477fd50cb5b.png">

  P2 low frequency, high impact

**Comment by Betree** [comment]
To me, there's some ambiguity on which amount we want to display, and it's not the role of this button to resolve it.

@alanna given that all amounts are displayed above in a clear and properly-labeled summary, can we remove the amount of the button and just say `Confirm contribution`?

**Comment by alanna** [comment]
OK yeah, true people might be paying attention to different numbers. I think your solution of just putting 'confirm contribution' on the button makes sense.
