### ISSUE TITLE
Replace all places still using "Github Handle" by "Repository Url"

### ISSUE THREAD

**Issue by darkdragon-001** [opencollective/opencollective#6024]
## User story 
As an open source software contributor, I can find out where the source code is hosted so that I can contribute.

## Best solution for this problem
Either allow a generic _"source code"_ field or add the second most common one gitlab.com.

## MVP
Button with link displayed on collective's page.

## Metrics 
Number of collectives making use of this feature.

## Documentation 
Self explanatory.

**Comment by Betree** [comment]
Already implemented in https://github.com/opencollective/opencollective/issues/5645, you can put any link in "Repository URL":
![image](https://user-images.githubusercontent.com/1556356/193995026-8ec93a6e-7dad-476d-95f1-9afb2cac5017.png)

We're still surfacing a "Github handle" input in the Open Source apply flow, which is going to be updated with https://github.com/opencollective/opencollective/issues/5645.

Please let me know if I missed another case.

**Comment by darkdragon-001** [comment]
Thanks for the hint! I found the field `repositoryUrl` in the API now :smile:
