### ISSUE TITLE
Emails no longer show "Thank that Person" button

### ISSUE THREAD

**Issue by phated** [opencollective/opencollective#603]
Just noticed that none of our emails have the "Thank that person" button from the donations that came through on the 1st of the month.

**Comment by xdamman** [comment]
It's in the notification for new backers. And you can now also connect your twitter account to automatically tweet a thank you message.

**Comment by phated** [comment]
@xdamman I don't want to thank **every** backer, just ones over a certain threshold.  With the old emails, that was easy to do.
