### ISSUE TITLE
GST settings missing from edit expense options

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6039]
**Describe the bug**
[This expense](https://opencollective.com/ehf-community/projects/cultural-training/expenses/99265) has GST on it (according to the uploaded invoice) but I didn't see anything about GST on the OC expense summary, so I assumed the box had not been ticked and went to edit it myself, but the local tax options are missing. When I try to submit a new expense, the options are there.

**To Reproduce**
1. Edit an expense without GST
2. Try to add GST
3. Box is missing

**Expected behavior**
Tax settings should be editable along with all the other expense options

**Screenshots**
When submitting a new expense, tax options are there:
<img width="698" alt="Screen Shot 2022-10-10 at 11 12 59 AM" src="https://user-images.githubusercontent.com/5498878/194782015-71a969ca-1e05-4505-a055-d08719b8264c.png">

When editing an expense, they are missing:
<img width="739" alt="Screen Shot 2022-10-10 at 11 13 25 AM" src="https://user-images.githubusercontent.com/5498878/194782031-0ddf73ec-f241-4750-a7e8-eca9c9583eb9.png">

  P2 low frequency, high impact

**Comment by Betree** [comment]
I wasn't able to reproduce with the provided steps, but I've fixed some inconsistencies in https://github.com/opencollective/opencollective-frontend/pull/8286 that could have caused this issue. I'll close it when I merge the PR, but feel free to re-open if it happens again.
