### ISSUE TITLE
Paying companies who won't engage with OC

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6040]
## Who is your user?
Collective admin

## What are they trying to achieve?
Pay someone who won't or can't submit an expense on Open Collective, often a big company with their own payment procedures who doesn't care about our processes.

Examples:

* Collective gets product or service from Big Co, who sends a payable invoice but will not submit it on the platform or respond to an expense invitation
* Collective has to pay something by credit card but Host is in a country without Stripe issuing (like NZ) so it's set up on the Host's own card and then we have to represent the expense on OC

## How are they currently doing this?
Got a case like this for OCF right now and we're blocked because even if the Collective admin creates a profile for the company without their involvement (which is already a little sketchy but we do in various cases), the system will trigger the tax form requirement and we'll be blocked again, because weird as it is to operate an OC profile for a company you don't work for, it's even weirder to submit a tax form for them.

Got another case like this for OCNZ where a regular expense can only be paid by credit card and we can't offer VCs here, so it's on the Host's card, but when we go to create the expense we have to operate the company org profile ourselves and it feels wrong. Maybe the proper method would be to select the Collective itself as the payee, but this is not the solution our current UX naturally leads you to. It makes more sense to try to name the payee so it shows up in a way that makes sense in your budget.

## Related issues

This is related to #6021 because if we start requiring verification that someone actually works for a company to operate a profile for it, we'll be even more blocked. People create orgs to be expense payees, but next time another Collective does the same thing we get a proliferation of duplicate profiles.

## How well understood is this problem?

 - [x] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by znarf** [comment]
What's the relationship with https://github.com/opencollective/opencollective/issues/5894 and https://github.com/opencollective/opencollective/issues/5894#issuecomment-1233117915 ?

**Comment by alanna** [comment]
Ahhh yes it's the same issue, thanks I forgot about that
