### ISSUE TITLE
Initial Virtual Card email should encourage receipt upload like subsequent one

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6046]
When a VC is charged, the initial email only tells people to look at the expense, and if you click through, you land in a normal view of the expense in `processing` state. After #5783 we started allowing uploading receipts in this state because there's no reason not to (even if the charge fails it doesn't hurt anything to have the receipt). So I think the initial email should be the same as the subsequent email, encouraging people to upload the receipt and landing them in the expense in an `edit` state, like the subsequent email does currently.

Initial email:
<img width="983" alt="Screen Shot 2022-10-12 at 9 50 04 AM" src="https://user-images.githubusercontent.com/5498878/195195904-1d285ebc-9091-4c84-8430-cb4d6d31c99f.png">

Receipt request email:
<img width="989" alt="Screen Shot 2022-10-12 at 9 48 49 AM" src="https://user-images.githubusercontent.com/5498878/195195925-4a4688d6-b1d8-45ab-b477-ae49f9e22236.png">

Related to #5951 - the system currently still sends the second email even if the receipt was already uploaded. This would need to be fixed for the UX to work well in this flow.

**Comment by SudharakaP** [comment]
@alanna : Here I am thinking we change the initial emails `View Expense` button to `Submit Receipt` which when clicked will open the expense in the edit state. Does this the solution you have in mind? Is there any wording changes we would need here as well? 🤔

**Comment by alanna** [comment]
Correct @SudharakaP - I think we can pretty much make the initial email (first screenshot above) the same as the current receipt request email (second screenshot above). We can keep the current receipt request email the same, as long as it doesn't get sent if the person has already uploaded the receipt (as per #5951 ).

**Comment by SudharakaP** [comment]
> Correct @SudharakaP - I think we can pretty much make the initial email (first screenshot above) the same as the current receipt request email (second screenshot above). We can keep the current receipt request email the same, as long as it doesn't get sent if the person has already uploaded the receipt (as per #5951 ).

Thanks I've made sure the working of the two emails match each other; https://github.com/opencollective/opencollective-api/pull/8086/files
