### ISSUE TITLE
Platform settings styleguide update

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#6047]
I'm documenting our recent design updates for the settings pages inside www.opencollective.com.

## Background

We have never done a proper design to cover all the options we put inside the platform's settings. The developer team initially designed the settings pages in the early versions of Open Collective. We have been building on top of that with isolated updates adding new features or facelifting existing ones. We seized the opportunity provided by #5289 and took the time to set a set of rules of text and spacing that make our settings **accessible**. Now that we have a more complex platform and require users to spend time setting the suitable options to use the platform and deal with sensitive aspects like security.

## Font use and inner spacing

![Component Holder](https://user-images.githubusercontent.com/49539954/195241582-5a08b916-e020-45b5-a5dc-e2fe159eb8c2.png)

## Layout
![Component Holder-1](https://user-images.githubusercontent.com/49539954/195241768-9cad66ce-8d0e-4f1f-a420-42b516a13b69.png)

![Component Holder-2](https://user-images.githubusercontent.com/49539954/195241650-76065af5-44e1-4bb7-8da5-34f0c7eca9ec.png)

![Component Holder-3](https://user-images.githubusercontent.com/49539954/195241649-75b3f422-6e7d-4222-bfea-a23417ddfc21.png)

[🎨 Figma file reference](https://www.figma.com/file/qrTaWmmmKWy2qG2MFC3ggL/%5BDS%5D-01-Foundation?node-id=4138%3A14506)

cc @Betree

**Comment by Betree** [comment]
@Memo-Es With the latest dashboard version, this doesn't seem relevant anymore. Should we close it?
