### ISSUE TITLE
Event has negative balance after clicking 'send balance to host'

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6048]
**Describe the bug**
I clicked 'send balance to host' on the banner on https://opencollective.com/collective/events/marseille-retreat-september-2022-adc4166f - now it has a negative balance.

**Expected behavior**
Clicking that button should result in a zero balance for the event, not negative.

**Screenshots**

<img width="405" alt="Screen Shot 2022-10-12 at 3 02 36 PM" src="https://user-images.githubusercontent.com/5498878/195231884-fcf827db-ed73-47cf-b665-2ce1db3ba493.png">

**Comment by znarf** [comment]
This is https://github.com/opencollective/opencollective/issues/5858

Let's prioritize this issue asap.
