### ISSUE TITLE
Add a button for users to download their recovery codes

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6050]
Updating my 2FA setup for many providers recently, I noticed a common pattern for all of them to offer users to download recovery codes in a standard text format, one code per line. I've been able to do this for Google, Cloudflare, Github, Gitlab, Heroku, Mailgun, Render, and Sentry; with most files named `{service}-recovery-codes` or `{service}-recovery-codes-{accountName}`.

It's handy to have a shared file format for this, as I'm now able to generate a backup document containing all my codes very easily.

According to https://dev.to/thedaviddias/9-best-practices-ux-improvements-for-the-two-factor-authentication-2fa-50m6, offering to download recovery codes is part of 2FA's best practices.

# Proposal

On this screen (Admin > Two-factor authentication > Step 2):
![image](https://user-images.githubusercontent.com/1556356/195269680-2720968f-5242-44b9-bccd-6c3a8ac8966b.png)

Add a "Download codes" button; and optionally a "Print codes" button.

@opencollective/design input welcome regarding the button(s) placement.

**Comment by znarf** [comment]
Happened the same to me. We should 100% do it if it's a best practice.

Also, you might have noticed that recovery codes are always available and not only on setup like on Open Collective. We should also consider this.

**Comment by Betree** [comment]
> Happened the same to me. We should 100% do it if it's a best practice.
> 
> Also, you might have noticed that recovery codes are always available and not only on setup like on Open Collective. We should also consider this.

On Heroku, it actually seems that you can't access your recovery codes - you can only re-generate them. I personally like this approach, as it protects against someone silently stealing a backup code for later use.

Given that our recovery codes are hashed in the database, a simple migration path for us might be to add a "Regenerate recovery codes" button on the 2FA settings page: 

![image](https://user-images.githubusercontent.com/1556356/195298208-eb46d184-7e1d-4add-81d2-3a944b21a26b.png)

**Comment by Memo-Es** [comment]
@Betree, I'll take this as part of the 2FA update, I will update it with a design file asap

**Comment by Betree** [comment]
That would be awesome @Memo-Es! Though there's no rush if you don't have the bandwidth to include it for this sprint.

On the engineering side, it's a small task, we can probably fit it as a stretch goal or a bounty.

**Comment by Memo-Es** [comment]
### Design update

Design for the 'Security' tab for Users.

2FA step 1 | 2FA step 2 | 2FA step 3 
-----------|-----------|-----------|
![Step 1](https://user-images.githubusercontent.com/49539954/196341310-092bc1eb-f640-4bfb-baac-7bfe1e60d59e.png) | ![Step 2](https://user-images.githubusercontent.com/49539954/196341309-6f40c429-0960-47a9-a56a-7ea00f0b27ee.png) | ![Step 3](https://user-images.githubusercontent.com/49539954/196341303-77f852d1-2f7e-40f3-99b3-9ab3783f6ae0.png)

[🎨 Design file reference here
](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=19244%3A160635)

@Betree

**Comment by Betree** [comment]
@Memo-Es Looks great!

**Comment by Betree** [comment]
My only feedback would be about the label of this button; I haven't encountered this in any of the 2FA flows I've tried. I think we can simply say "Verify", the fact that the system will then provide you with recovery codes is a complexity that I think we don't need to expose at this step.

![image](https://user-images.githubusercontent.com/1556356/196611260-4b719a1b-cb49-451c-b153-fd6522cea200.png)

But that's a personal preference, not a blocker.

**Comment by SudharakaP** [comment]
@Betree : If no objection I'll take this one. 😄
