### ISSUE TITLE
user can't access his account - DB change required. 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#606]
> I can’t login to my first account (https://opencollective.com/ndelangen) whichever email i try, I get directed to https://opencollective.com/ndelangen1
> 
> I’m not bothered by the url, but only https://opencollective.com/ndelangen has access to https://opencollective.com/storybook
> 
> Can you help and get me access again to https://opencollective.com/ndelangen ?
> 
> Greatly appreciated :bow:

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by bryphe** [comment]
Hi @piamancini ,

I believe a similiar issue happened to me when I created my collective: https://opencollective.com/oni

It seems that a user `bryphe` was created when I started the collective, but it wasn't linked to an e-mail account, so I was unable to use it. So now I have a user [bryphe](https://opencollective.com/bryphe), that is the core contributor, and a second user, [bryphe1](https://opencollective.com/bryphe1), which is associated with my e-mail, but is not a core contributor. Please let me know if there is any other info I can get for you.

It could potentially be related to the issue I hit during creation of the collective (#555).

Thanks for your help and have a great weekend!

**Comment by piamancini** [comment]
thanks @bryphe! We'll get the emails sorted asap. 
The bug you hit was fixed already by @asood123. If you created the collective, it should have picked up your email. Let us look into it and we'll activate your collective. Thank you for reporting!

**Comment by asood123** [comment]
Fixed bryphe's issue: https://github.com/onivim/oni/pull/869#issuecomment-342302986

**Comment by bryphe** [comment]
I just tried it out and works great-
![image](https://user-images.githubusercontent.com/13532591/32466648-7c9b74a2-c2fc-11e7-8443-78dae864aa0d.png)

Thanks @asood123 !

**Comment by asood123** [comment]
Looks like the first comment is also fixed already. Please reopen if it's still an issue.
