### ISSUE TITLE
Cards for orgs should not refer to money raised

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6062]
<img width="289" alt="Screen Shot 2022-10-19 at 3 01 55 PM" src="https://user-images.githubusercontent.com/5498878/196579883-5ce59fb2-78cc-486d-ac1f-299f5212f4d7.png">

An organization is not a profile type for fundraising. When you click through on it, there's nothing visible about this money being raised. Why is it showing money raised?

**Comment by Betree** [comment]
To be more specific, this is about the card we show in the search: https://github.com/opencollective/opencollective-frontend/blob/3d3a732da606bf6e7b6f3de3659fd29fc4435ebd/components/search-page/SearchCollectiveCard.js. Using `totalAmountReceived` for an organization that can't receive contribution doesn't make much sense; for them, we should try to display the total amount contributed there, but not the amount received.

Profile: https://opencollective.com/center-for-open-science
Search page: https://opencollective.com/search?q=center+open+science&type=ORGANIZATION

**Comment by SudharakaP** [comment]
> To be more specific, this is about the card we show in the search: https://github.com/opencollective/opencollective-frontend/blob/3d3a732da606bf6e7b6f3de3659fd29fc4435ebd/components/search-page/SearchCollectiveCard.js. Using `totalAmountReceived` for an organization that can't receive contribution doesn't make much sense; for them, we should try to display the total amount contributed there, but not the amount received.
> 
> Profile: https://opencollective.com/center-for-open-science Search page: https://opencollective.com/search?q=center+open+science&type=ORGANIZATION

@Betree : When you mention total amount contributed, do you mean the total money spent? I've opened a PR with a potential fix for this let me know how it looks. I used the phrase `Money Spent` since the stat used is in sync with that wording.
