### ISSUE TITLE
Re-use the @opencollective/frontend-components in other projects

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6069]
A bunch of our external projects are copy-pasting components, which is not a future-proof solution as they don't include updates. It also creates disparities in the APIs of this components, which evolve over time.

https://www.npmjs.com/package/@opencollective/frontend-components should be imported & used in:
- [x] PDF service
- [ ] ~~Changelog~~

**Comment by SudharakaP** [comment]
@Betree : I've opened a PR for pdf service. But in the changelog project I don't see any front-end components being used. It seems to use it's own styles. Maybe we should use the front-end components instead of custom styles in changelog? 🤔

**Comment by Betree** [comment]
@SudharakaP We initially wanted to use the design system on the changelog too (e.g. for the tags). But I'm not even sure anyone still uses this page, so let's not invest in it for now. Feel free to close this issue as soon as you merge https://github.com/opencollective/opencollective-pdf/pull/871
