### ISSUE TITLE
update expense attachment in DB

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#607]
User needs to change the attachment in his expense. 
It's the existing Sticker Mule expense in Storybook 
New file: https://www.stickermule.com/orders/R814167577?token=9680b1deee36950d&utm_swu=1826

This expense needs to be updated in order to be paid. 

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by piamancini** [comment]
Also this expense file needs to be updated in the DB: 
opencollective.com/lem/expenses (first expense the one in Japanese)
New invoice is in mail in support, it has PI so can't upload it here, please ask me for it.

**Comment by asood123** [comment]
stickermule link isn't a pdf. Do you normally take a screenshot to upload?

**Comment by piamancini** [comment]
done
