### ISSUE TITLE
Enforce 'submitters cannot approve their own expenses' as a host

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#6075]
As detailed here https://github.com/opencollective/opencollective/issues/5279#issuecomment-1290496589  

> OSC has instigated a policy of reviewing all payments >$10,000. When reviewing these payments we look for a history of similar payments, both for the collective and the individual, we look at the balance and the source of income for the Collective that would pay the expense and finally we look at whether another member of the community approved the expense. In many cases the submitter is STILL the approver and this greatly affects the confidence that we have to make a payment. It slows us down in making genuine payments too. We need this as a setting that we can enforce.

We could enforce this above a certain threshold (as we have in the policy), but right now we are lacking the tools to double-check that an expense is okay with another admin. 

related https://github.com/opencollective/opencollective/issues/5036

**Comment by alanna** [comment]
I thought of a hole in this one: a host admin can add a new virtual card and make a charge using it without any other admins being involved. It's an edge case but it is a version of "user approves own expense".

**Comment by BenJam** [comment]
virtual cards dont have 10k limits.

**Comment by alanna** [comment]
They can, we've done large ones before. Or is that not as a concern because there's another step required for a high limit where another person would be involved?

**Comment by hdiniz** [comment]
wrt to virtual cards, there is a discussion on this [issue](https://github.com/opencollective/opencollective/issues/5994) about making virtual card requests structured in a way that would enabled us to have a policy requiring another admin approval.

For the expense approvals:

- Could we go with a toggle on the collective policy modal under the hosted collectives dashboard?
- Should we disable this toggle if the collective does not have at least two admins?

![image](https://user-images.githubusercontent.com/5448927/206433973-7103382e-2696-4fa1-9f8e-59f8b4002593.png)

**Comment by BenJam** [comment]
@hdiniz We still support single-maintainer projects so it's key that we don't freeze out projects with only one admin. But for those with multiple admins we would like to policy to apply (if necessary, above a certain limit).

Logically we want the setting that we already have as a host admin (under policies) to apply to hosted collectives, which it does not. 

![Screenshot 2022-12-08 at 14 28 35](https://user-images.githubusercontent.com/158833/206472316-045a39e2-3a49-4d1a-a2c8-2822a841ca60.png).

**Comment by BenJam** [comment]
quick chat with @hdiniz plan is:

- [ ] add a checkbox below the existing setting to 'enforce policy for hosted collectives'
- [ ] add a further checkbox to existing setting to 'enforce policy on single-admin collectives'

If we have time we'll also add an option to gate the policy on payout amount:

- further setting (number input) to 'enforce policy for transactions over <host currency>' 
- update tooltip to tell submitter when expense is over limit and policy is being applied
- check (and update) prompts about the same on other expense pages

**Comment by BenJam** [comment]
@alanna I know you care about this setting so, to be clear, the plan is that the host setting will override the collective's setting if applied. 

This will help Open Source Collective a small amount on high-value transactions and encourage multi-admin collectives to work toward a governance framework/policy which will benefit the project in general in my opinion.

**Comment by alanna** [comment]
With the options described above this should give us the flexibility to figure out how to apply this for OCF - we haven't had capacity to fully consider if we'd enforce it for Collectives, so having the option is good.

**Comment by iamronen** [comment]
I am catching up with the demo and wondering if implementing this leaves a loose end in the UX. Wat happens when an admin submits an expense and is unable to approve it? What happens in the UI? Is the approve button disabled? Is there an indicator on why it is disabled and guidance about what needs to happen next (reach out to another admin and ask them to approve)?

**Comment by hdiniz** [comment]
@iamronen the approval button is disabled and it displays a tooltip indicating the reason.

If the policy is applied based on the expense amount it also displays the threshold value.

![image](https://user-images.githubusercontent.com/5448927/208421892-d300b98b-130b-423e-ade2-c2010d646013.png)

**Comment by iamronen** [comment]
Thank you for clarifying that @hdiniz  :) 
It may be useful to add an explanation that clarifies that the expense can be approved by another collective admin.
