### ISSUE TITLE
Apply design update to the frontend template project

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6079]
The template project should include a default design as implemented in the contributor's dashboard:

# Header

Use {projectName} by Open Collective

![image](https://user-images.githubusercontent.com/1556356/198008060-e884bb33-418d-4601-9a10-c4571a046297.png)

# Footer
![image](https://user-images.githubusercontent.com/1556356/198008121-827d347c-0cba-4241-975e-2813e222457c.png)

**Comment by Anuran12** [comment]
@Betree  I would like to work on this.

**Comment by Betree** [comment]
@Anuran12 Sorry, it's simpler for us to take this one internally. But we'll be happy to welcome your contribution to any other issue! Some suggestions: https://github.com/opencollective/opencollective/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
