### ISSUE TITLE
How to deal with 2FA in OAuth?

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6088]
When using the API, developers can now face 2FA errors that require them to use a 2FA code.

- If that's the intended behavior, we should document it and explain how they're supposed to solve it
- If we decide that OAuth apps can bypass 2FA, then we need to properly study the security implications and properly explain it in the interface.

Related: #6085 

cc @hdiniz @znarf

**Comment by Betree** [comment]
Moving the conversation that happened in https://github.com/opencollective/opencollective/issues/6085:

@znarf 

> Currently, we can fail and expect the connected oAuth app to collect the 2FA code and pass it to the API. This is what we're doing in the 1kproject payment script.
> 
> It may however be a clear anti-pattern, third party should not be incentivized or allowed to collect 2FA from users. It means that we should provide a workflow to fail, ask for a 2FA code and collect it on our own https://opencollective.com/ website.
> 
> Easy to prototype I guess but more difficult to get it right.

@Betree 

> Ignoring 2FA for OAuth app is also a valid approach. We force you to input your 2FA code whenever you connect a new application, but after that, the app has full access and doesn't require you to put your 2FA code.
> 
> It looks like both approaches exist in the industry:
> 1. Transferwise use their frontend components to collect 2FA and send it back to the API (if @kewitz can confirm)
> 3. Many sites like Github seem to have this approach where you need to put your 2FA when connecting the app, but after that, it will have full access (within the limits of the scopes you've provided) without the need for further 2FA.

@kewitz 

> I'm fine with requiring 2FA only when connecting.
> 
> Wise pattern is an outlier only when you're funding a transfer, all other endpoints are safe to be requested.
> I think we can try a similar approach if we want to run the extra mile.

**Comment by Betree** [comment]
Mautic is also impacted by this issue

**Comment by BenJam** [comment]
If I'm allowed to have an opinion: I think we can also ignore 2FA when the user has authed the application. At that point they are permitting the app to act on their behalf, they have been made aware of the risks.

**Comment by Betree** [comment]
This week:
- [ ] Organize a kick-off call to layout a plan for this project
- [ ] Eventually iterate on quick actions

**Comment by Betree** [comment]
# Engineering Kickoff

## API 

- [ ] Add a special flag on Applications to allow 2FA bypass. Suggested names:
  - `block2FARequests` default=true
  - `bypass2FA` default=false
  - `ignore2FA` default=false
  - `preAuthorize2FA` default=false
  - `necessaryRequestFor2FA` default=true
- [ ] Add a warning (or error) when using a 2FA code with OAuth (apart from the 1kproject script)
- [ ] Apply the same logic for personal tokens

## Frontend

- [ ] Add a checkbox on Application/Personal tokens creation/edition screens
  ![image](https://github.com/opencollective/opencollective/assets/1556356/f6b939a6-d792-4844-8791-c119148a94ea)
- [ ] Add a warning on the OAuth authorization screen if the app has 2FA bypass enabled
  - `This will give the application the right to trigger critical actions on your behalf without requiring you to input your two-factor authentication codes`

## Other

- [ ] Remove 2FA handling from 1KProject script

## Release

- [ ] Let users know about the flag for the users that requested it (mautic)
- [ ] Let Suds know about the flag (for 1kproject script)

**Comment by Betree** [comment]
This week:
- [ ] Implement the API part
- [ ] Make a proposal for the frontend and request feedback

**Comment by BenJam** [comment]
waiting for @znarf to review next week 👍

**Comment by Betree** [comment]
- [x] Ping users that requested it [on Slack](https://opencollective.slack.com/archives/C4TC3AYDT/p1699430630804789?thread_ts=1690379427.017049&cid=C4TC3AYDT) to let them know that this has been rolled out.
- [x] Update the [docs for OAuth](https://docs.opencollective.com/help/developers/oauth#about-2fa) and create [a page for personal tokens](https://docs.opencollective.com/help/developers/personal-tokens) that includes these changes.

All tasks completed, closing the project!
