### ISSUE TITLE
Cancel Recurring Payments when user Account is Archived

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6094]
Related to freshdesk ticket; https://opencollective.freshdesk.com/a/tickets/137824. 

Currently when a user archives their account the recurring payments they have are not paused or cancelled. My thinking is that once an account is archived we should,

- Ideally pause (or cancel) the recurring payments. 
- Cancel all recurring expenses by the user.

 Let me know what you think on this or if we should do more things when a user archives their account. 🤔 (cc: @opencollective/core-developers)

**Comment by Betree** [comment]
That's an important one, thanks for documenting it. Looking at https://github.com/opencollective/opencollective-api/blob/334749b6b2cae9c0f3e24f798927c2789dd27e7a/server/lib/recurring-contributions.js, it seems that this is affecting both PayPal and Stripe. 

## Frontend

Here we should mention that recurring contributions will be canceled.

![image](https://user-images.githubusercontent.com/1556356/199441564-1a9c071a-24f5-4e45-89f0-61150146e1f7.png)

## API

Have a similar approach than https://github.com/opencollective/opencollective-api/pull/8004, mark all orders as canceled.
