### ISSUE TITLE
Add Support for Date Field in Add Funds Modal

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6095]
Related to the freshdesk ticket; https://opencollective.freshdesk.com/a/tickets/134462. 

There's a user request for being able to retroactively add funds. For example in the above ticket the user added funds using the add funds modal but the funds should be reflect the date as 2021. This makes sense when the fund added reflects something historical such as here; 

![image](https://user-images.githubusercontent.com/12435965/199405528-6374f15a-7a4e-4b77-a934-a0a8d279dc40.png)

It's related to a fund received in 2021.

**Comment by Betree** [comment]
Duplicate of https://github.com/opencollective/opencollective/issues/5693?

**Comment by SudharakaP** [comment]
> Duplicate of #5693?

Thanks. I missed this one. 🥲
