### ISSUE TITLE
Recurring expense "Additional invoice information (optional)" field not saved

### ISSUE THREAD

**Issue by mkurz** [opencollective/opencollective#6098]
I created a recurring expense last month (just got the email notification for it). However it did not have the `Additional invoice information (optional)` field filled out, it's blank. But it was filled in in the original expense:
<kbd><img width="400" src="https://user-images.githubusercontent.com/644927/199681841-3b9613c8-2eaa-4e9a-95b8-16e0a7f8fb7e.png" /></kbd>

Please also save the value of that field, otherwise it does not make much sense for my use case. Thanks!

**Comment by Betree** [comment]
cc @kewitz
