### ISSUE TITLE
#feature add twitter hook to thank donor/sponsor

### ISSUE THREAD

**Issue by pwnela** [OpenCollective/OpenCollective#61]
It would be great if there was a hook to tweet a "thanks" to new sponsors or donors from the OpenCollective organization Twitter account.

**Comment by xdamman** [comment]
+1 
That's a great idea. We did this in the past as a first step but we should go much further https://github.com/OpenCollective/OpenCollective/issues/36

I'd also add the option to automatically, once a month, thank all sponsors (and @mentioning them on Twitter).

**Comment by pwnela** [comment]
Yes! Recurring thanks is something I've thought about doing manually.... but computers do recurring things much better.

**Comment by xdamman** [comment]
This needs to happen first https://github.com/OpenCollective/website/issues/111
Then it will be easier to tackle this.

**Comment by xdamman** [comment]
Let's prioritize this.

We can knock something out quickly. We don't need much UI for this. We can start by communicating the link to connect a twitter account to the collectives that we have.

The only thing that we would need is a page at the end of that flow where they can edit or opt out of the automatic tweets (doesn't need to be designed much for now):

- [ ] Send a tweet every first of the month to thank sponsors and backers 
      `<textarea to edit the default template>Thank you to our 32 backers and sponsors @pubnub @digitalocean @yahoo who are supporting our collective https://opencollective.com/:slug</textarea>`

- [ ] Send a @reply to thank every new backer/sponsor
      `<textarea to edit the default template>@xdamman thanks for becoming the 3rd backer of our collective https://opencollective.com/:slug</textarea>`

@piamancini feel free to suggest edits to those templates. We can also always change them as we go and try different versions.

**Comment by sedubois** [comment]
Connect account: https://github.com/OpenCollective/opencollective-api/pull/450

**Comment by piamancini** [comment]
https://github.com/OpenCollective/OpenCollective/wiki/Twitter
