### ISSUE TITLE
Investigate high AWS bill

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#610]
Our AWS bill reached $250 this month and is increasing rapidly. Quick glance shows it's for data transfers... Since we are on Heroku, need to investigate why we are spending so much on AWS data transfers.

**Comment by xdamman** [comment]
Fixed https://github.com/opencollective/frontend/pull/109

**Comment by asood123** [comment]
Still happening, and it's increasing.

**Comment by xdamman** [comment]
Those two PR should help:
https://github.com/opencollective/opencollective-api/pull/1046
https://github.com/opencollective/opencollective-api/pull/1045

Closing this now. Let's reopen it if bill doesn't go down.
