### ISSUE TITLE
Bank Transfers: Implement a page to display pending order to users.

### ISSUE THREAD

**Issue by hdiniz** [opencollective/opencollective#6119]
When a contribution is made using a bank transfer method within the platform the order will be in a pending state until the transfer is completed, a process that can take days. We should display feedback to contributors so they know their order was received and is processing.

- [x] Check with design about where to display pending orders.
- [x] Add a page to display pending orders.

**Comment by natehn** [comment]
@hdiniz is this related to https://github.com/opencollective/opencollective/issues/5769 ?

**Comment by legeord** [comment]
After you people block all my account you expect me to read your email
never
