### ISSUE TITLE
Make Sure Max Quantity can be Set in Membership Type Tier

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6123]
Related to https://opencollective.slack.com/archives/C6JTTA4SK/p1667735900243569. It seems that currently the max quantity cannot be set for membership type. We need to give the users the ability to set this. Also as pointed out in that thread we need to make sure if the user changes the type after setting a value to a field (such as max quantity) it is cleared out when it's not visible anymore.

**Comment by Betree** [comment]
The PR that explicitly limits the max quantity field visibility is https://github.com/opencollective/opencollective-frontend/pull/216/files#diff-e36f08c8bae542c6f3e1b7df5ba61f49de627584cf29987095650ddb76b7e123R135. There's no  real explanation there,

No blocker for me to show it for memberships.
