### ISSUE TITLE
Ability to resend tax forms 

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6126]
## User story 
If a user didn’t receive or can’t find there tax form it would be great if a fiscal host admin could resend this to them. 

## Best solution for this problem
Some way of resending this form! Either via the expense or root admin? 

<details>
  <summary>Triage Template (team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by BenJam** [comment]
sounds like this is very rare, not super simple as we need to resend the request through FreshWorks.

**Comment by Betree** [comment]
This won't be necessary anymore with https://github.com/opencollective/opencollective/issues/7216; since tax forms are presented directly in the frontend people can just go to their dashboard, we do not need to send them another email if they miss the first one.
