### ISSUE TITLE
Grant expenses enabled even though they are disabled in Host settings

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6133]
**Describe the bug**
Grants are turned off for OCNZ Host but this grant expense just came through https://opencollective.com/nz-federated-services/expenses/107395

**To Reproduce**
1. Go to https://opencollective.com/nz-federated-services
2. Submit an expense
3. See grant option

**Expected behavior**
Grant expenses should be completely disabled if the Host has set up that global policy

**Screenshots**
<img width="217" alt="Screen Shot 2022-11-14 at 4 46 46 PM" src="https://user-images.githubusercontent.com/5498878/201571213-0e3225b9-9889-429f-a9b1-ff081377d04d.png">

<img width="858" alt="Screen Shot 2022-11-14 at 4 49 32 PM" src="https://user-images.githubusercontent.com/5498878/201571339-77b37f76-19f4-47fc-bcc1-4fddb71fa244.png">

**Additional context**

  P2 low frequency, high impact

**Comment by Betree** [comment]
From what I see grants are explicitly enabled for this collective in Hosted Collectives. These collective settings take precedence over global ones.

**Comment by alanna** [comment]
Oh that should not be the case at all. I as a Host need to disallow grant expenses unless I have a process for accepting them. I'll tell the Collective I'm turning it off and not to turn it back on again, but this is a problem. Like can OCF Collectives just turn it on and start submitting them even though we as the Host have not allowed it? That would cause a big compliance headache for us.

**Comment by Betree** [comment]
Sorry, my comment above was not very clear: I'm talking about the setting you enable from `Host admin` > `Hosted collectives`, which is only accessible to host admins. But after double-checking, it seems that we've also enabled this interface in the collective admin > Policies section, I'm going to remove that immediately.

**Comment by alanna** [comment]
Thank you! For other Hosts who might not mind about grant expenses, if the Host level has grants enabled, can Collectives still disable it? I think the ideal behavior would be that Collectives can turn on any expense type the Host has enabled, but aren't required to have them all on. I don't know if other Hosts actually need Collectives to have their own setting for this though - for the ones I manage, it's important the Host is in control of it.
