### ISSUE TITLE
Move from "twitterHandle" to "socialUrl"

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#6134]
Copy pasted and adapted from https://github.com/opencollective/opencollective/issues/4165

# User story

> It would be nice if the text field for entering the social URL was not limited to Twitter. There is now also Mastodon, a decentralized alternative..

# MVP

What we want for this issue, is to allow users to use any kind of social presence for their profile, the one that's linked in the collective page:

<img width="993" alt="Screenshot 2022-11-14 at 14 29 58" src="https://user-images.githubusercontent.com/806/201672822-f6920069-4dae-4b8f-a888-d8a1c6a7968b.png">

We could achieve that by:
- [ ] Introduce a new `socialUrl` field on GraphQL API
- [ ] Deprecate `twitterHandle` on the GraphQL API
- [ ] Migrate `twitterHandle` to `socialUrl` in the model, adapt all existing entries
- [ ] Add legacy compatibility for `twitterHandle` on the GraphQL API if `socialUrl` is a Twitter link
- [ ] Adapt the frontend. We can have a special icon for Twitter, otherwise we can just fallback on something generic.

**Comment by imanshu03** [comment]
@znarf Can you please share the generic icon which we need to show if the `socialUrl` is not a twitter link ?

**Comment by Betree** [comment]
I think we should rather solve this with https://github.com/opencollective/opencollective/issues/5097, most projects usually have multiple social links - Twitter, Facebook, Instagram, etc. The solution proposed here will not resolve this.

**Comment by znarf** [comment]
We'll do https://github.com/opencollective/opencollective/issues/5097 instead.
