### ISSUE TITLE
[DOCS] Create and Edit Tiers

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6139]
## Context
https://github.com/opencollective/opencollective/issues/6092

**Comment by shannondwray** [comment]
We've redesigned the process to create and edit tiers. Tiers can be used to provide perks and rewards to supporters, set membership fees, build funding drives, or simply categorise your contributions. The new experience shows a preview of the tier as it will appear on your Collective's profile:


📘 [Read more about tiers and goals](https://docs.opencollective.com/help/collectives/collective-settings/tiers-goals)
📧 [Contact support if something isn't working](https://opencollective.com/redirect?url=mailto%3Asupport%40opencollective.com)
🙃 Leave feedback below

**Comment by BenJam** [comment]
[I completed this ](https://docs.opencollective.com/help/collectives/collective-settings/tiers-goals#tiers)
