### ISSUE TITLE
[DOCS] Activity log

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6141]
https://github.com/opencollective/opencollective/issues/5912

**Comment by shannondwray** [comment]
https://www.loom.com/share/e4cf23a68a074ade83540a44f6f2ed66

**Comment by shannondwray** [comment]
https://www.loom.com/share/526b9f1a24cb4d138c48063ce602a753

**Comment by Betree** [comment]
I shared the relevant info for docs in https://github.com/opencollective/opencollective/issues/6142

**Comment by shannondwray** [comment]
https://docs.opencollective.com/help/product/activity-log
