### ISSUE TITLE
[Release] Activity Log 

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6142]
## Context
Project: resolve https://github.com/opencollective/opencollective/issues/5195
Feedback: https://github.com/opencollective/opencollective/issues/5912
Slack: https://opencollective.slack.com/archives/C03UD3RV3JQ

### What's being released?
The ability to track activities happening through your account or your hosted accounts.

### Is this change being released incrementally as a beta? What's the schedule?
- Released in beta (see https://github.com/opencollective/opencollective/issues/5912 for testing)
- Release date: 21th of November

### Is this release optional or mandatory?
Will be enabled by default on all profile types in Settings > Activity log.

### Who does this release impact?
Everyone.

**Comment by Betree** [comment]
@shannondwray I've recorded this loom to give a walkthrough of the feature: https://www.loom.com/share/2d6eed14902f4017b1b7cdd0c059903d and updated the `Context` part of this issue.

**Comment by BenJam** [comment]
https://opencollective.com/opencollective/updates/fiscal-host-update
