### ISSUE TITLE
[DOCS] Dedicated page to show all submitted expenses

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6143]
## Context
https://github.com/opencollective/opencollective/issues/3749

### What's changing?
We're introducing new ways to list expenses:
- List all expenses submitted by a given user
- List all expenses where an account was used as the payee 

### Why are we changing it?
- For many users on the platform who needed a way to easily find all the expenses they have submitted, view their pending drafts, etc.
- For Collective/Host/Platform admins who needed a way to investigate the history of a user for many reasons: accountability, fraud protection, data collection, etc.

### Who does this change impact?
- All users: will get a new `Manage Expenses` in their menu
- All users: will be able to view expenses submitted by a given user by going to the profile > Budget > Submitted Expenses
- All users: will be able to view expenses where an account was used as a payee by going to the account expense's page and selecting the "Submitted" filter

#### To view your submitted expenses

1. Open your user menu by clicking on your avatar
2. Click on `Manage Expenses`

![image](https://user-images.githubusercontent.com/1556356/206029715-26205cf2-16a7-44d5-a92a-e3ce00b4808d.png)

#### To view expenses submitted by another user

1. Go to the user profile
2. In the menu, hover `Budget` then click on `Submitted Expenses`

![image](https://user-images.githubusercontent.com/1556356/206029889-017c556b-3efd-4908-904a-11f5907da6ca.png)

#### To view expenses payable to an account

1. Open the account page
2. Go to their **Expenses** page (Budget > Expenses)
3. Click on `Submitted`

![image](https://user-images.githubusercontent.com/1556356/206030099-d371c854-f306-4fa4-8606-7fe5b964d043.png)

### Is this change optional or mandatory?
This is a mandatory change, no settings exposed.

### Is this change being released incrementally as a beta? What's the schedule?
Already been released in production for everyone.

**Comment by Betree** [comment]
I've added context & documentation to the issue body. The change is already released in production & ready to be documented. Note that, based on team feedback, we're likely to update the wording we've used on the expenses page.

**Comment by shannondwray** [comment]
This has been included in the new documentation
