### ISSUE TITLE
[DOCS] Bank transfer (ACH/wire) contributions within the platform.

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6147]
https://github.com/opencollective/opencollective/issues/4927

## Context
 
Receiving contributions via bank payments is a common request, using our integration with Stripe we are able to provide these new payment methods and more in the future.

### What's changing?

We are adding the possibility for users to pay using ACH debit and SEPA debit options in the platform.

### Why are we changing it?

To enable more methods for users to contribute to the platform.

### Who does this change impact?

Fiscal Hosts need to review their Stripe enabled payment methods to enable ACH and SEPA Debit options.

### How do users use it?
 
Users contributing via the existing contribution flow will be presented with the option of paying via ACH or SEPA (depending on the fiscal host currency). The users will complete the payment using the Stripe integration with their bank. 
Payments with ACH and SEPA can take a couple of days to complete, users will receive an email notifying of the contribution.

### Is this change optional or mandatory?

Optional, will only be enabled for some Fiscal Hosts which have this feature and that have enabled ACH and SEPA on their Stripe account.

### Is this change being released incrementally as a beta? What's the schedule?

Released as a beta on the Open Collective account.

**Comment by BenJam** [comment]
generic language in the docs on contributions covers bank transfers, we might be okay without an update here.

**Comment by BenJam** [comment]
removed generic language and merged.
