### ISSUE TITLE
add payment processor fees in DB for expenses paid manually via paypal

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#615]
two webpack expenses needed to be paid via paypal and the fee that paypal charges needs to be updated manually in the transaction table. 
expense id 2182--> payment processor fees $180.1
expense id: 2183--> payment processor fees: $6.01

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by asood123** [comment]
done
