### ISSUE TITLE
[DOCS] Virtual cards

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6151]
https://github.com/opencollective/opencollective/issues/4312 

## Context
Extra mile goals of the sprint were focused on small virtual card enhancements.

### What's changing?

- Added visibility on the card limit, displaying the limit configuration and the remaining limit available on the card.
- Added display of virtual card assignee on the collective dashboard.
- Added labels to identify virtual cards which can be set by collective admins.
- Added more limit options when creating or assigning a virtual card.
- Enable the delete card option for collective admins

### Why are we changing it?

These are small improvements gathered from user feedback that we could tackle as an extra mile on the current sprint.

### Who does this change impact?
Fiscal hosts with the virtual card feature enabled and collective admins that request and manage virtual cards.

### How do users use it?
A virtual card admin page is available for Fiscal Hosts and Collectives with the virtual card feature enabled.

### Is this change optional or mandatory?
This is released to all collectives with the virtual card feature enabled

### Is this change being released incrementally as a beta? What's the schedule?
Immediate release

**Comment by shannondwray** [comment]
https://www.loom.com/share/37f26ba2caf94a319daf65dbb19048fd

**Comment by shannondwray** [comment]
So I'll list out the changes that have been implemented in production and you can take it from there:

Track Remaining limit
Displaying the name of the assignee on the card.
Deleting cards (New feature for collective admins, it already existed for hosts)
Custom label for the cards
Monthly limit and renewal date visible on the card.
Click through to Collective/assignee from name on virtual card

we also solved this issue of granular limits for hosts.- https://github.com/opencollective/opencollective/issues/5992

**Comment by BenJam** [comment]
There was a huge update missing for Virtual Cards from the fiscal host area which I've redrafted:

https://app.gitbook.com/o/-LWSZizNMEjL8_DrMNdF/s/-LWSZizTt4ZC1UNDV89f/~/changes/7PIZ1eJatxwd8dygJT4m/fiscal-hosts/payouts/virtual-cards#assigning-cards

Needs a review.

**Comment by BenJam** [comment]
generic language removed and this is merged.
