### ISSUE TITLE
[DOCS] Fraud Protection

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6153]
https://github.com/opencollective/opencollective/issues/4329

**Comment by shannondwray** [comment]
https://docs.opencollective.com/help/fiscal-hosts/fiscal-host-dashboard/expenses#security-checks

**Comment by shannondwray** [comment]
Security Checks 

We have released a new Security Check feature for Expenses.
This Security Check icon is located by the other expense action buttons and changes colors based on the worst perceived threat. If there's a high-risk threat detected, we'll also make sure you see that before paying for the expense.
With this tool, we provide fiscal host admins with contextual information about the transaction they're about to execute, including risk factors and details for each one of the check routines.

In this first iteration, we check for:
If the user may be trying to impersonate other users in the platform through shared IP addresses or connected accounts
If the user uses 2FA or not
If the user is related to the collective
If the user was already paid by this collective or any other collectives on the platform
If this payout method is also used by other accounts in the platform (only for PayPal and Bank Accounts)
*This is the first batch of security checks we have implemented. They were created based on past cases we had on the platform, and we plan to keep iterating on these checks with the input of fiscal hosts. Your feedback is welcome!

**Comment by kewitz** [comment]
@shannondwray I had to delete that demo from here, make sure you don't share demo's marked with **[INTERNAL]**.

**Comment by shannondwray** [comment]
Can you share the link to slack instead? What is another work around for this? Can we password protect looms? I'm really wanting these issues to become the centre point for where all of this information is stored

**Comment by shannondwray** [comment]
From @BenJam's Release Draft on Open Collective - We're adding warnings about payees to protect Collectives and Hosts from fraudulent expense claims.

As a platform for managing money fraud is, and always has been, a challenge for us and our hosts. In [February this year](https://opencollective.com/opencollective/updates/two-to-sign-features-on-open-collective) we announced our first governance tools to help hosts and Collectives improve how they work together.

Today we're releasing a new feature to help Collectives and hosts identify fraudulent expense claims. Alongside each expense, you'll now see a warning when the user requesting payment meets some conditions:


Warnings include whether this user and/or their payment method is new (to you or the platform in general), whether they are using multiple profiles, whether they've previously had expense claims rejected and whether they're using multi-factor authentication to secure their accounts.

These warnings are designed to inform you as to whether you should approve or pay an expense. They are not a part of an enforcible policy within Open Collective but we encourage hosts and Collectives to consider creating and documenting policies as part of their terms or code of conducts if needed. 

📘 Read more about approving and paying expenses
✉️ Contact Support
📣 Leave feedback below

**Comment by shannondwray** [comment]
@kewitz just flagging my comment above

**Comment by shannondwray** [comment]
https://app.gitbook.com/o/-LWSZizNMEjL8_DrMNdF/s/-LWSZizTt4ZC1UNDV89f/fiscal-hosts/fiscal-host-dashboard/expenses#security-checks - Small updates but looks great!
