### ISSUE TITLE
[DOCS] Enforce 2FA at the Organization level

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6155]
https://github.com/opencollective/opencollective/issues/5289

### What's changing?
Organizations and collectives can now enforce 2FA for all their admins. Any attempt at triggering admin operations or visiting the admin pages will be blocked until the admins enable 2FA on their profiles.

### Why are we changing it?
To help hosts enforce best practices in regard to security.

### Who does this change impact?
All accounts that are administrated by multiple persons: hosts, organizations, collectives, funds. Projects and events inherit the 2FA settings from their parents.

#### 1. Click on the user menu
![Step 1 screenshot](https://images.tango.us/workflows/3eafa474-5eeb-4bdf-a489-8c97bbcced11/steps/14e65e46-07d0-4962-a3b6-762e887363ac/9b7e00f1-594c-499c-ac9f-daad1e8b12d4.png?crop=focalpoint&fit=crop&fp-x=0.9654&fp-y=0.0363&fp-z=2.9069&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A909)

#### 2. Click on the cog icon next to the profile you want to enable "Enforce 2FA" for
![Step 2 screenshot](https://images.tango.us/workflows/3eafa474-5eeb-4bdf-a489-8c97bbcced11/steps/692dbfa6-083a-42c3-b6b8-70d6da2cf01e/6b6ef9f2-a93d-48d7-9b39-7906822ca94c.png?crop=focalpoint&fit=crop&fp-x=0.9628&fp-y=0.2635&fp-z=3.1377&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A909)

#### 3. Click on "Security"
![Step 3 screenshot](https://images.tango.us/workflows/3eafa474-5eeb-4bdf-a489-8c97bbcced11/steps/f981e53b-bad7-431d-bc8d-1f8848f0e00a/196d3e8e-6cab-4efc-b804-f9f8a936b7d8.png?crop=focalpoint&fit=crop&fp-x=0.2255&fp-y=0.8251&fp-z=2.4000&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A909)

#### 4. Check "All admins must have two-factor authentication"
![Step 4 screenshot](https://images.tango.us/workflows/3eafa474-5eeb-4bdf-a489-8c97bbcced11/steps/99d39ad7-7a74-4ec6-a243-f6c14e109302/e8a9df42-94f8-4526-8506-be3273126181.png?crop=focalpoint&fit=crop&fp-x=0.5118&fp-y=0.2840&fp-z=2.2045&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A909)

#### 5. Click on Save
![Step 5 screenshot](https://images.tango.us/workflows/3eafa474-5eeb-4bdf-a489-8c97bbcced11/steps/c197f758-10fb-4899-b6ca-a0cddc87f22a/674288b2-1376-4393-913e-2d23f82bd5ff.png?crop=focalpoint&fit=crop&fp-x=0.3349&fp-y=0.5176&fp-z=2.8402&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A909)

#### When visiting admin pages without 2FA, admins will be prompted to enable it
![image](https://user-images.githubusercontent.com/1556356/202162859-7e9cf92e-cb93-49fe-975d-701e7c0b76e6.png)

### Is this change optional or mandatory?
It's optional (opt-in) and needs to be enabled from the settings.

### Is this change being released incrementally as a beta? What's the schedule?
It's already been released publicly.

**Comment by shannondwray** [comment]
https://www.loom.com/share/ec904cd54b044dbdb4e41808201b2da5

**Comment by Betree** [comment]
Updated context

**Comment by shannondwray** [comment]
Thank you Ben! 

Collective Settings - https://docs.opencollective.com/help/collectives/collective-settings/security
Fiscal Host Settings - https://docs.opencollective.com/help/fiscal-hosts/fiscal-host-settings/security
