### ISSUE TITLE
[Release] Enforce 2FA at the Organization level

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6156]
https://github.com/opencollective/opencollective/issues/5289

### What's being released?
Organizations and collectives can now enforce 2FA for all their admins. Any attempt at triggering admin operations or visiting the admin pages will be blocked until the admins enable 2FA on their profiles.

### Is this change being released incrementally as a beta? What's the schedule?
It's already been released publicly.

### Is this release optional or mandatory?
It's optional (opt-in) and needs to be enabled from the settings.

### Who does this release impact?
All accounts that are administrated by multiple persons: hosts, organizations, collectives, funds. Projects and events inherit the 2FA settings from their parents.

**Comment by Betree** [comment]
Updated context

**Comment by BenJam** [comment]
we'll bundle this with a general update on F2A

**Comment by shannondwray** [comment]
Moved here: https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Documentation-Releases_sul57#Project-Releases_turYe/r167&view=modal
