### ISSUE TITLE
login fails with host+other

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#616]
I log in on opencollective.com: 
![screen shot 2017-11-03 at 4 37 22 pm](https://user-images.githubusercontent.com/3671070/32395023-bf78672e-c0b5-11e7-93d9-f445aed37b60.png)

When I go to the collective (profile not showing up)
![screen shot 2017-11-03 at 4 37 59 pm](https://user-images.githubusercontent.com/3671070/32395033-d07ca094-c0b5-11e7-8a31-4af01b0024d7.png)

When I go to expenses, it logs me out 
![screen shot 2017-11-03 at 4 38 11 pm](https://user-images.githubusercontent.com/3671070/32395039-d7fc3d34-c0b5-11e7-82cb-71a026794847.png)

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by asood123** [comment]
fix: https://github.com/opencollective/opencollective-website/pull/775. Going live in a few mins.
