### ISSUE TITLE
move funds from supercollective to collective

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#617]
By mistake funds where added to the supercollective instead to a collective. They need to me moved manually in the DB

€200 was added by mistake here: https://opencollective.com/vdmcollective 
needs to end up here: https://opencollective.com/reconomycop 

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by piamancini** [comment]
@asood123 maybe you can do it? User emailed me again. 
(It needs to be done manually from db, change the collective ID in the order and transaction tables for the manually added funds)

**Comment by asood123** [comment]
done.
