### ISSUE TITLE
Ability to search/filter for collectives with an OR-operator on tags array

### ISSUE THREAD

**Issue by gustavlrsn** [opencollective/opencollective#6170]
## Description

For the Horizons dashboard it would be great to have the ability to search on multiple tags using an `OR` style operator.

The tags filter on `accounts` accepts an array of tags, but it is currently returning accounts that have all tags, using an `AND` operation.

### 1. Switch current tag filter to OR
Clean and easy but means that we lose some ability on the opencollective.com/search page to narrow down your search by adding more tags, so probably should be avoided
```graphql
accounts(tag: ["climate justice", "climate change"]) 
```
### 2. Add another argument that is specifically for `OR` filtering
A bit ugly(?), but works without messing with current functionality.
```graphql
accounts(tagsOR: ["climate justice", "climate change"]) 
```
### 3. Add more advanced tags filter input type where you can specify operator
```graphql
accounts(tags: { values: ["climate justice", "climate change"], operator: OR ]})
```
### 4. Do nothing
and make sure we tag all collectives manually with what we want to filter on

**Comment by Betree** [comment]
> Switch current tag filter to OR

I agree with you that this should be avoided to prevent breaking changes.

> Add another argument that is specifically for `OR` filtering

That would work, but I agree the argument name is not great.

> Add more advanced tags filter input type where you can specify operator

That would be a breaking GraphQL change that would require us to update all frontend and make an announcement for people relying on this (since our API is public). Taking the same approach, but with a separate parameter, we could introduce the same feature in a non-breaking way:

```graphql
accounts(tags: ["climate justice", "climate change"], tagSearchStrategy: OR)
```

My personal preference goes for this approach.

**Comment by znarf** [comment]
I'm gonna +1 on Ben's proposal with `tagSearchOperator` as a name.

**Comment by gustavlrsn** [comment]
@Betree that was a much cleaner solution, thanks! Opened a PR with it: https://github.com/opencollective/opencollective-api/pull/8214

**Comment by gustavlrsn** [comment]
API support for this fixed in https://github.com/opencollective/opencollective-api/pull/8214. Closing this issue, but feel free to reopen or create a new issue to add support in the UI to do this.
