### ISSUE TITLE
Expense Tags are Not Displayed in Budget Section for Self Hosted Collectives

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6180]
Related to the slack discussion, https://opencollective.slack.com/archives/C6JTTA4SK/p1667597877830129. 

It seems that for self hosted collectives such as, https://opencollective.com/cesakparis, who just use the collective page to keep track of the budget and create expenses where the payer and payee is the collective itself we don't really reflect them in the budget dashboard. 

Note that we have the condition; 

https://github.com/opencollective/opencollective-api/blob/7446bcd67421fe258bf70e5ae41debf58baca4a5/server/models/Expense.js#L523

We need to alter these SQL queries such that these expenses are reflected.

**Comment by SudharakaP** [comment]
@znarf : I am trying to understand how we can alter this SQL query. Does the point behind the condition to check for `t."FromCollectiveId" NOT IN (:collectiveIds)` to eliminate transactions such as `BALANCE_TRANSFER`, `PAYMENT_PROCESSOR_COVER` and `ADDED_FUNDS` etc, in which case I am thinking we could just check for `t."kind" IN 'EXPENSE'` so that we narrow down on `EXPENSE` types but also take into account those for which the `payee` and payer` are the same.

**Comment by BenJam** [comment]
this is a really weird edge case that I don't think we need to address.
