### ISSUE TITLE
Unable to contact a 'Fund'

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6185]
**Describe the bug**
There is no contact button for Funds 

e.g. 

https://opencollective.com/fundoss
https://opencollective.com/di-grants

**To Reproduce**
1. Go to any of the above funds
2. Click on the actions button 
4. See error - there is no contact button 

**Expected behavior**
Unless I'm missing something you should be able to contact a fund via our platform? 

**Desktop (please complete the following information):**
 - OS: MacOS 13.0 Beta 
 - Browser: Brave
 - Version: [Version 1.45.113 Chromium: 107.0.5304.62 (Official Build) (x86_64)]

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
<img width="311" alt="Screenshot 2022-11-23 at 4 39 08 PM" src="https://user-images.githubusercontent.com/79115149/203600874-7abc97a4-fe67-4d5a-a4a4-e52d46597389.png">
<img width="326" alt="Screenshot 2022-11-23 at 4 39 02 PM" src="https://user-images.githubusercontent.com/79115149/203600882-51fd1aed-5199-4d22-801c-604d1750d9f7.png">

  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
Not a bug, we just never activated it. It's a one-line change if we want to do so.

@znarf any blocker?

**Comment by znarf** [comment]
@Betree Fine for me.
