### ISSUE TITLE
Unable to Verify using Github

### ISSUE THREAD

**Issue by dreygur** [opencollective/opencollective#6186]
Unable to Verify using Github

**To Reproduce**
1. Go to 'https://opencollective.com/opensource/apply/intro'
2. Click on 'Verify using GitHub'
3. Click on 'Approve'

**Error response from api**
```
{
    "error": {
        "code": 500
    }
}
```

**Comment by Betree** [comment]
cc @gustavlrsn

**Comment by gustavlrsn** [comment]
@dreygur I'm not able to reproduce this error. Can you confirm if it is still occurring?

**Comment by dreygur** [comment]
It's not occurring anymore

**Comment by gustavlrsn** [comment]
@dreygur thank you for the confirmation. Closing this issue.
