### ISSUE TITLE
Duplicate Payment Methods - Credit Cards

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6189]
This has been brought up in several support tickets, such as this one; https://opencollective.freshdesk.com/a/tickets/137857. 

When users contribute they can keep adding the same credit card which could create duplicate cards which appear exactly the same. Maybe we need to investigate and add a check so that users cannot add the exact same credit card if it already is in their profile. 

![image](https://user-images.githubusercontent.com/12435965/203872380-661049f2-1458-44cb-b045-b21450ffaf1e.png)

**Comment by Betree** [comment]
The support ticket is an edge case, in practice users normally don't end with duplicate credit cards since we suggest the cards that you already have in the different flows (contribution flow, update recurring contribution, etc). 

It's unclear what the solution to resolve this, if any, should be.

**Comment by znarf** [comment]
Stripe support a `fingerprint` property which may help in de-duplication. 

https://stripe.com/docs/api/cards/object#card_object-fingerprint

**Comment by SudharakaP** [comment]
@znarf : Thanks for the idea. I opened a PR with a solution based on this fingerprint. 👍🏽

**Comment by znarf** [comment]
Is throwing an Exception a user friendly solution here?

Can we research what other services would do in this case? E.g. amazon

**Comment by SudharakaP** [comment]
> Is throwing an Exception a user friendly solution here?
> 
> Can we research what other services would do in this case? E.g. amazon

I checked Amazon, Ebay and Google Wallet. It seems that both Amazon and Ebay updates the credit card details when trying to add an existing credit card. Whereas Google Wallet seems to give a error saying the card is already there. But I think editing the card is more user friendly as it do not require anymore user action; therefore I'll alter the implementation to edit the card instead if no objections.

**Comment by SudharakaP** [comment]
@znarf : I've updated the PR to instead update the payment method. So no error thrown to user. 😃
