### ISSUE TITLE
Refund Jason only wants one time contribution

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#619]
Mail from Jason:

> I submitted a one time donation of $50 but somehow it was setup as a monthly subscription and charged my card again on Nov 1st.  Please refund the most recent $50 as it should have only been a one time charge.  
> 
> Account Name:  jjandebug
> Charge:  Monthly donation to Destiny Item Manager (Backers)

**Comment by asood123** [comment]
refunded. Filed a larger tiers issue to track all these related bugs.
