### ISSUE TITLE
Fix fees in txn table 

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#62]
Donation ID 337: $200 to WWC Austin (group id2), platform fees $10 (ok) but host fees is $10 as well (should be $20, 10%) I checked the group and host fees says 10, so I'm not sure what the issue is. 

La Primaire: txn id: 327 host fee 25, id 400 host fee 0 (I'm sure this is because we modified fees in between) I'm manually calculating collective's net. 

Les barbars: txn id359: host fees should be 0, it is calculating 5%. (might be same issue as above, check next month)

Vloupe [bug]: It started calculating 5% for host on 4-18 (txn 364), but host fee was 0 before and it still says 0. 

For paypal flow we need to differentiate fees 'manual' and 'paypal' since 'manual' don't have paypal fees. But we should report them anyway in the monthly email.  Since this is still manual, it's a pain to calculate because I can't aggregate expenses and # of expenses.

If PayoutMethod is empty, I assume it's manual. Please confirm. 

For foreign currencies we need to pull from Stripe the platform fees and host fees in USD at the currency exchange rate of the day. Otherwise we can't calculate revenue properly.

**Comment by piamancini** [comment]
The Query for fees is giving partial results. Please revise: https://github.com/OpenCollective/OpenCollective/wiki/Queries

**Comment by asood123** [comment]
Went over this with Pia in person. Closing.
