### ISSUE TITLE
Refund+Verify meet up charge to UpstatePHP collective

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#620]
Mail from Nathan:

> Hello, I was charged $5 twice for a meetup I was attending, but the organizer never received either one.
> 
> On Oct. 18, I tried to purchase 1 ticket to https://opencollective.com/upstatephp/events/level-up-with-pipelines-206ev for the $5 "Head Count + One Time Donation" and I received an error, so I tried one more time and received the same error. I later discovered that my card was actually charged, but UpstatePHP did not receive either donation.
> 
> The reference numbers for both charges are 5568 and 8797.
> 
> I either need a refund for both of these $5 charges or I need to verify that UpstatePHP received both $5 donations.
> 
> Thank you in advance for your assistance.
> 
> Thanks,
> Nathan Morgan

**Comment by piamancini** [comment]
@xdamman this was from the event that had several issues. 
@asood123 you have allocated funds to the collective from the event, did you add these ones as well?

**Comment by asood123** [comment]
already taken care of: https://github.com/opencollective/opencollective/issues/550
