### ISSUE TITLE
User email <-> User slug 

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6201]
## Who is your user?
Fiscal Host admins, collective admins 

## What are they trying to achieve?
Trying to find users emails or account on OC 

_When I'm communicating with a user and I want to find their user profile or email address

## How are they currently doing this?
There currently isn't a way, you have to ask or if you are on the OC team you can use the meta base query - https://opencollective-metabase.herokuapp.com/question/996-user-email-from-slug

https://opencollective-metabase.herokuapp.com/question/1008-user-slug-from-email

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment]
Alternative: #4699
