### ISSUE TITLE
Ability to open images from Collective page 

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6208]
## Who is your user?
Anyone trying to gather assets 

## What are they trying to achieve?
Trying to obtain logos, graphic for marketing reasons, have to rely on Google having indexed the page in order to obtain the images, would be great if I could open the logos/background images directly from Open Collective 

_When doing marketing activities, I want to gather collective logos so that I can communicate visually  _

## How are they currently doing this?
Trying to find the logos via google, websites etc 

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by shannondwray** [comment]
<img width="387" alt="Screenshot 2022-12-01 at 4 45 06 PM" src="https://user-images.githubusercontent.com/79115149/205020242-44474b41-a24d-40dd-9a3d-3dd25d589040.png">
I can't right click and open image

**Comment by Betree** [comment]
You can right-click > Inspect and get the link from there. I don't think we want to change how we're linking the image here as the technic we're using has a few benefits that we don't really want to lose.

![Peek 2022-12-01 12-20](https://user-images.githubusercontent.com/1556356/205040308-d47e036d-2693-47a1-b79f-31353bc55a51.gif)

**Comment by Betree** [comment]
Closing as it is not an issue with Open Collective itself. I'm happy to provide more assistance if the solution proposed above is not working for you.

**Comment by shannondwray** [comment]
Thank you! Can use this solution :)
