### ISSUE TITLE
merge users and add email

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#621]
Mail from Rick:

> Hi - I can see that I've already got an account here:
> 
> https://opencollective.com/rickhumphries
> 
> But I'm not sure how to log into it? Which email address is associated with it?
> 
> Thanks
> 
> Rick

**Comment by piamancini** [comment]
@xdamman 
the collective in the url: https://opencollective.com/rickhumphries is associated with a user with no email 
please consolidate users: 
ID: 10014
10013
8072
and make the one with email ADMIN of buttercups collective. 
(user is blocked on this, I can do it but requires manual changes)

**Comment by piamancini** [comment]
done
