### ISSUE TITLE
Collectives should be able to see financial contributions 

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6218]
## Who is your user?
Collective admins that are fiscally hosted 

## What are they trying to achieve?
Collective admins should be able to see the financial contributors page. That fiscal host admins and independent collectives can see. (image from an independent collective) 
<img width="1312" alt="Screenshot 2022-12-07 at 12 55 14 PM" src="https://user-images.githubusercontent.com/79115149/206099812-a2e55456-2a80-47d4-a159-aa6791ac498d.png">

_As an admin of a collective, I want to be able to see all of my financial contributors and active recurring contributions, so I can have more insight_

## How are they currently doing this?
There currently isn't any visibility

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by SudharakaP** [comment]
I believe with the new dashboard this need is addressed. The collective admins have a "Contributors" section as well as a "Contributions section".  

![image](https://github.com/opencollective/opencollective/assets/12435965/fb27b42e-c30a-4c6c-91a7-c50028abb8f3)

@shannondwray : Feel free to reopen if you think there's anything missing that needs to be addressed.
