### ISSUE TITLE
[PROJECT] Budget section UX review and update

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#6226]
### Overview

There are a lot of issues with our current display of the budget features. Specifically, the transactions list, the budget overview, the expenses list, and how these features play together provide a clear outline for users of the budget operations inside the platform.

Some of the most important ones:

- We haven't reached a final solution for displaying the budget aspects of events and projects inside a Collective.
- What will be the final solution for the financial overview inside the Collective page? We need a transition from v1 to v2
- Accounting for a large budget and improving the experience of CSV downloads.
-  Solve the expenses vs transactions vs contributions vs debits vs credits issue. Find a way to consolidate all the admin tasks around these aspects and nail it with an improved UI and consolidated terminology.

Related issues:

- https://github.com/opencollective/opencollective/issues/6071
- https://github.com/opencollective/opencollective/issues/5704#issuecomment-1214610825
- https://github.com/opencollective/opencollective/issues/6217

### Goal

Our platform capabilities have grown over the years. This reflects the work we have put in on becoming a powerful financial platform. Now we need to **consolidate all these small moving pieces** in a practical, straightforward, clockwork-like software implementation. 

Main goals:
 - Prioritizing a simple experience
 - Reducing cognitive load as much as possible
 - Aim to have an integrated experience with our different budget features

### Documented comments from slack

> help: where did the budget spreadsheet download button go for collectives? I can no longer download my expense history at Art.coop as xls :sonrisa_con_sudor: which means my accountant who tries to make a basic cash flow for us with projections cannot do her work for EOY — https://opencollective.com/art_coop/expenses — I tried the old and new budget and both seem to have disabled or hidden this feature.

> I figure it out — it is a UX problem — as a user when I go to “view all expenses” it takes me to a page where I cannot download the report. When I go to “view all contributions” it takes me to ALL TRANSACTIONS (not all contributions) and then I can download a report. I think we don’t need both links (expenses and contributions) as that is confusing, and additionally, if contributions takes you to all transactions, it should say all transactions. Both options need to enable me to download the CSV for now.

> just now — as a collective admin, I have a few big pain points as I try to do accounting for a large budget:
I want to be able to download my CSV of transactions but I don’t whether to do V1 or V2 - how can I know which one? (I asked Alanna, we cannot have collectives doing this)
I want to download my CSV but it is not at ALL clear to me that I need to click on multiple areas to make those show up — I never realized that until Alina showed me that right now.
When I download the basic V2 CSV version (the default one) where I see added funds and contributions only, there is no HOST fee. Why is that? This makes my budget look inflated in the transaction log.
Perhaps this is for strong foundations? This has been really challenging as I try to find an accountant that can work with the OC system and I have access to our staff to ask questions if and when needed. Whatever solution we make, I would love to work on Docs about this so all collectives can understand how to us transaction logs and then hire accountants / use Art.coop templates to support their needs.

https://www.loom.com/share/e4821daec5d74bdfbd26eb243ded1588

**Comment by shannondwray** [comment]
@iamronen might be interesting history for the crowdfunding redesign! if not could potentially close this issue as it's being considered in the redesign

**Comment by iamronen** [comment]
We've come a long way addressing these pain points ... and there is still more to do.
Closing this specific issue.
