### ISSUE TITLE
[DOCS] Need some Gift Cards documentation for financial contributors

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6229]
In https://docs.opencollective.com/help/financial-contributors/organizations/gift-cards we have some documentation on gift cards but nothing to explain how to claim them or what the limitations are.

**Comment by Betree** [comment]
In a nutshell: 

> To use a gift card, you first have to activate it on your account from https://opencollective.com/redeem. Then go to make a donation as usual, and select your gift card when asked for payment.
> Note that some gift cards might be limited to specific fiscal hosts or project types (e.g., open source).

**Comment by orimdominic** [comment]
@Betree Can I work on this?
I believe that the quoted text you put up in your last comment under this thread is what is required, with the heading question being _How do I claim the gift cards?_ and _What are the limitations with gift cards?_

**Comment by orimdominic** [comment]
Great!
Is there a copy for this?

**Comment by orimdominic** [comment]
Oh! Okay!
How do I contribute to that? @Betree

**Comment by Betree** [comment]
@orimdominic Feel free to propose some content here or in a PR for the docs repo if you know how to test the feature. We like to record how-tos with https://www.tango.us.
