### ISSUE TITLE
Clarify tiers situation

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#623]
When a user picks backer tier and makes one-time donation, it converts to a monthly. We need to always respect user's wishes at the cost of not assigning the correct tier.

Let's take a step back and come up with Tiers plan that is simple to understand - bar is that we need to explain it externally.

Open Questions
- How to deal with one-time and annual donations in context of monthly tiers?
- What happens if a user doesn't fit into any tier?
- Handle presets and existing tiers pre-migration

Please add other edge cases.

**Comment by asood123** [comment]
Example: https://github.com/opencollective/opencollective/issues/619

**Comment by piamancini** [comment]
- presents and pre-migration tiers is solved
- yearly can be done from one-time
- if user doesn't fit in a tier then it shows up as backer.
