### ISSUE TITLE
Manual paypal processor fee showing wrong currency

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6238]
**Describe the bug**
This box says NZD next to processor fee, but when I add it in, it's calculating it in USD (see how it shows $20.41 in the input box but $31.98 in the output). This view is also mixing currencies without specifying which is which - the expense amount shown ($170) is USD but the processor fee just below it is showing in NZD. This is confusing.

<img width="358" alt="Screen Shot 2022-12-19 at 12 37 21 PM" src="https://user-images.githubusercontent.com/5498878/208325549-d4286a92-162d-4283-bdc4-58ce778c098e.png">

This is the expense: https://opencollective.com/bwt/expenses/112295

**To Reproduce**
1. Pay a Paypal multi-currency expense and select manual
2. Put the payment processor fee in the box in the currency stated
3. See wrong amount

  P2 low frequency, high impact

**Comment by Betree** [comment]
Looking at it

**Comment by znarf** [comment]
@Betree Leo @kewitz started to look at a more generic issue, based on that feedback https://github.com/opencollective/opencollective/issues/5601#issuecomment-1359186212
