### ISSUE TITLE
Missing expenses that have been paid

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6242]
It looks like some expenses that were on the platform and were paid have disappeared. They were payable to https://opencollective.com/happen-films-ltd/

> On 14 April and 30 May this year we were paid by Gift Collective for two invoices, both for NZD $2070, both for the Gravity shoot. However, I can’t see these payments reflected in the Gravity Fishing project on OC: https://opencollective.com/happenfilms/projects/gravity-fishing/

There are two other expenses for the same amount, but the two missing ones are in addition to these:
[https://opencollective.com/happen-films/projects/gravity-fishing/expenses/72390](https://opencollective.com/gravity-fishing/expenses/72390)
https://opencollective.com/happenfilms/projects/food-forest-revisit/expenses/72391

Here are the transactions in Wise, which were paid automatically via the platform:
<img width="880" alt="Screen Shot 2022-12-20 at 10 05 36 AM" src="https://user-images.githubusercontent.com/5498878/208524012-fc982fb1-bff8-44ce-ac70-04c36e43aa80.png">
<img width="850" alt="Screen Shot 2022-12-20 at 10 05 23 AM" src="https://user-images.githubusercontent.com/5498878/208524020-7e0e54e0-84d5-4a87-905d-211bf8c0b0e5.png">

I'm not sure why the second one says $2875.76 but I can't find an expense matching that amount either. 

Can someone please verify if there are expenses paid on the platform that have gone missing somehow?

**Comment by znarf** [comment]
I've looked at it in multiple ways and I could not see any Expense looking like this on this Collective or Host, except the 2 already mentioned.

The $2875.76 Expense is this one https://opencollective.com/happenfilms/projects/food-forest-revisit/expenses/77572

**Comment by alanna** [comment]
Ah ok, the $2875.76 one makes sense.

The thing is, the other two $2070 amounts looks to have been paid, we just can't find an expense for them. Like the recipient sees the incoming payments to their bank account from the Host.

**Comment by znarf** [comment]
If this is money that they were not expecting, maybe duplicate payments for the mentioned expenses (paid offline by someone, or technical glitch, but the expense history looks clean).

It's weird that the dates they mention are exact match for the 2 paid expenses. Have they really received 4 times ~$2070?

**Comment by alanna** [comment]
I'm wondering if they are confused... I'm going back to the user for more info

**Comment by alanna** [comment]
Turns out it was user error, sorry
