### ISSUE TITLE
Headings move on:hover

### ISSUE THREAD

**Issue by mixmix** [opencollective/opencollective#6246]
![image](https://user-images.githubusercontent.com/2665886/208775806-145aafb1-03d1-4e91-8a09-5769c1b65833.png)

These headings change their font-weight when you hover over them. Nice
EXCEPT when this happens the `width` of that heading changes by about a pixel, causing the whole bar to move.

This is a minor gripe but to anyone visually attentive it's incredibly annoying and half-arsed looking. Once you see it you cannot unsee it. You're welcome :japanese_ogre: 

Solution: set a fixed width for each of those tabs
OR have a hidden div with the heavier weight text which holds the right space.

**Comment by mixmix** [comment]
![animation](https://user-images.githubusercontent.com/2665886/208777907-2da9df28-3a79-4ed6-9c73-79b0aaf4bbc4.gif)

**Comment by Betree** [comment]
@mixmix Thank you, there was an attempt at handling this by adapting the `letter-spacing`, but it's not a reliable solution. I pushed a fix in https://github.com/opencollective/opencollective-frontend/pull/8496 that uses the 2nd approach you've suggested (have a hidden div with the heavier weight text which holds the right space.)
