### ISSUE TITLE
Feature: Support gift cards

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#625]
Bloomberg Beta wants to offer Open Collective Gift Cards at their holiday party.

About 400 gift cards to be given out. 

Date of party: Dec 1 in SF, Dec 7 in NYC

- [x] Design landing page flow (opencollective.com/redeem)
- [x] Build landing page flow
- [x] Generate unique codes and send for printing physical cards
- [x] Store unique codes in DB as prepaid payment methods
- [x] Add gift card as a payment method as a link under credit card widget
- [x] Figure out how to link Bloomberg's prepayment of money to moving actual money to the right host (some of it can be manual)
- [x] Basic frontend test
- [ ] Basic backend test

**Comment by cuiki** [comment]
Hi @asood123, 

Which collectives should I feature here?

**Comment by cuiki** [comment]
Hi everyone, 

Here's the landing page design. I included the input filed for the gift-card code inside the collective cards of the featured collectives. This way the step is just one (to choose who to donate to and enter the code).

@asood123, maybe it is faster if you add that field at the bottom of the collective cards after you click the Explore button, at the bottom of the page...

Let me know your thoughts.

![oc-page-gift-card](https://user-images.githubusercontent.com/981188/32969448-d25f1f40-cbaa-11e7-87d5-0ad0cc3bed42.jpg)

Zeplin link: https://zpl.io/Vq16JX7

**Comment by asood123** [comment]
Flow is live at staging.opencollective.com/redeem. Test cases to verify:

1. visit /redeem, select a collective and use a code to redeem with a new email address
2. visit /:collectiveSlug (an open source project hosted by us), select a tier and enter a code instead of credit card (expect: ledger to be updated)
3. visit /:collectiveSlug (something hosted by our open source host), select a tier and enter a code instead of credit card (expect: order to be created but no transactions created)
4. #1 with logged in
5. #2 with logged in
6. #3 with logged in

Separately, I refactored tiers and tickets controller. Need to test following tier scenarios:
1. Presets
- visit /mochajs, 
- select a tier, change presets and intervals and make sure everything updates
- donate and make sure right amount and frequency is recorded

2. Tickets
- Visit an events page with tickets
- add/subtract different tickets (make sure they all update)
- select one and buy it

3. Fixed (like $10/monthly)
- Visit /opensource 
- select a tier with a fixed amount
- make sure everything is displaying properly (and you aren't allowed to change anything)
- donate and check amount and frequency

**Comment by xdamman** [comment]
- [ ] bug: https://staging.opencollective.com/webpack/donate doesn't show the credit card form unless we change the amount manually

**Comment by xdamman** [comment]
- [ ] bug: I just made a donation with the gift card to webpack as a new user and with an organization name and I got redirected to http://staging.opencollective.com/neworg2?status=orderCreated&CollectiveId=302&TierId=undefined&type=COLLECTIVE&totalAmount=5000 but there is no collective there associated to my new organization.

**Comment by piamancini** [comment]
> visit /:collectiveSlug (something hosted by our open source host), select a tier and enter a code instead of credit card (expect: order to be created but no transactions created)

Transaction lines are created. See staging order id6213

**Comment by piamancini** [comment]
> visit /redeem, select a collective and use a code to redeem with a new email address while logged in.
I selected create an organization from the dropdown menu and system didn't give me an option to create one and donation was made from my user.  OrderID6214

**Comment by asood123** [comment]
Took care of two issues that pia mentioned

**Comment by asood123** [comment]
All issues fixed, except the css issue that @xdamman mentioned. I can't find an easy way to do it. If you have ideas, let me know

**Comment by asood123** [comment]
Fixed css issue as well. Pushing to production
