### ISSUE TITLE
Bank transfer instructions reverted

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6251]
**Describe the bug**
On Dec 15 I made an update to OCF's bank transfer instructions, to add EU account details and chance OCF's address, so they looked like this:
<img width="577" alt="Screen Shot 2022-12-15 at 9 45 59 AM" src="https://user-images.githubusercontent.com/5498878/209230855-d9632d7b-f656-427e-8d1e-a6e95790e806.png">

Today, Dec 23, I went back to make another edit, and it seems they have reverted to the previous version, without the EU details:
<img width="474" alt="Screen Shot 2022-12-23 at 10 37 51 AM" src="https://user-images.githubusercontent.com/5498878/209230915-72328555-327f-407c-9204-328227dbc8e0.png">

Can the correct updated version be put back, and can someone please look into why this happened? It's important the correct instructions stick in this setting.

  P1 high frequency, high impact

**Comment by SudharakaP** [comment]
@alanna : This is one me as I've explained at, https://opencollective.slack.com/archives/GFH4N961L/p1671745588840579?thread_ts=1671745380.675799&cid=GFH4N961L.
