### ISSUE TITLE
[DOCS] Consolidate widgets documentation

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6255]
We have two places where widgets are documented:
- In https://docs.opencollective.com/help/collectives/widgets#show-supporters-and-sponsors
- In https://docs.opencollective.com/help/collectives/collective-settings/data-export#widget

Proposal:
- Consolidate everything in https://docs.opencollective.com/help/collectives/widgets#show-supporters-and-sponsors
- In https://docs.opencollective.com/help/collectives/collective-settings/data-export#widget, add a link to the other page (e.g. To see widgets documentation, click here)

**Comment by shannondwray** [comment]
https://docs.opencollective.com/help/collectives/contribution-flow could also be part of the same page, it's just another kind off widget

**Comment by hosilamar** [comment]
@Betree Assign this task to me.

**Comment by shannondwray** [comment]
Moved here: https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Documentation-Releases_sul57#Project-Releases_turYe/r172&view=modal

**Comment by shannondwray** [comment]
Moved here: https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Documentation-Releases_sul57#Project-Releases_turYe/r172&view=modal
