### ISSUE TITLE
Explore alternatives to Dropbox Forms

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6262]
# Why we initially Dropbox Forms (ex-HelloWorks)

The current tax form implementation was built by an external contractor 5 years ago. At the time, he decided to use Dropbox Forms (HelloWorks):
1. To simplify the implementation (no frontend form to build)
2. To automatically generate PDFs
3. To not store sensitive information (SSN) in our systems

# Issues with Dropbox Forms

- Branding issues: not using our email templates, domains, and UI components.
- We're sharing sensitive data with a 3rd party.
- Support and sales teams have historically been super unresponsive.
- Vendor lock-in.
- Dropbox Form pricing is a bit crazy, jumping from a few hundred $ a month to thousands to send a few more tax forms (we are [quite impacted by the limit](https://opencollective-metabase.herokuapp.com/question/192-number-of-tax-forms-sent-over-the-limit) atm). This is not scalable if we want to offer the service to 3rd party hosts.

![image](https://user-images.githubusercontent.com/1556356/210244177-3ba99953-74f1-4884-babd-98651ac164ab.png)

# Benefits of Dropbox Forms

- Ability to send arbitrary tax forms manually

Keywords: HelloWorks, HelloSign, Hello Works, Hello Sign

**Comment by alanna** [comment]
When this is up for prioritisation I would like to help with the project

**Comment by Betree** [comment]
We've been waiting for a simple reply from their support for over a month with @natehn; they haven't even been able to find our account when provided the email and base info 🤕 The news are not looking great either, with Dropbox announcing significant layoffs: https://www.cnbc.com/2023/04/27/dropbox-layoffs-company-to-cut-500-employees.html.

**Comment by Betree** [comment]
OSS alternative with 50x cheaper pricing: https://documenso.com/

**Comment by alanna** [comment]
Looks amazing @Betree ! How can we assess if it would do everything we need?

**Comment by Betree** [comment]
An engineer could test it locally:
- Clone the repo
- Try to re-create the setup for our tax forms
- See if the completion works well
  - => If so, create specs to replace Dropbox Sign in our codebase
  - If not, we can maybe contribute to the repo to make it work?

I'd be interested in doing this if I find some bandwidth during the sprint.

Otherwise, someone outside of the engineering team could contact them to ask questions & eventually request a demo.

**Comment by Betree** [comment]
Just got contacted by yet another OSS alternative: https://www.docuseal.co/

> It's a free alternative to DocuSign that allows to create, fill, and sign digital documents.
> 
> Features:
> 
>  - PDF Form Builder to create complex fillable PDF forms.
>  - All documents are automatically signed with a digital PDF signature.
>  - The UI is optimized for mobile, allowing to review and sign digital documents online from any device.
>  - Developer-friendly and can be integrated with apps via an API, webhooks, or JS widgets.
>

**Comment by ElTimuro** [comment]
@Betree thanks for bringing up Documenso 🙌
We have a lot planned for this year and would love to work with you guys given your background with opencollective.
Happy to answer any questions that come up :)

**Comment by Betree** [comment]
Thanks @ElTimuro, we don't have the bandwidth to iterate on it at the moment, but I'll get in touch whenever we're ready to make a move on this!

**Comment by ElTimuro** [comment]
@Betree sound good. Let me you if you need details, we are ready when you are :)

**Comment by Betree** [comment]
Hi @ElTimuro, I finally had the time to look at Documenso. Our use case: we need people to complete a form like [this one](https://github.com/opencollective/opencollective/files/13752675/fw9.pdf) and sign it. Other tools (Dropbox Forms, Docuseal) offer the option to add custom fields to the document. This allows two things:
1. Make sure that the document gets completed (fields can be marked as "required")
2. Have the data accessible through the API in a standard format (without having to parse the result PDF)

![image](https://github.com/opencollective/opencollective/assets/1556356/fc998c30-06fe-4d74-9152-8810555ce43d)

Is that something you're supporting (or are planning to support)? Is there documentation for Documenso's API?

**Comment by Betree** [comment]
Docuseal [appears to be missing](https://github.com/docusealco/docuseal/issues/168) "Conditional fields" and "Added fields". But since they support embeddings, a workaround could be to review our own flow to request this information directly from our interface, then show the appropriate form embedded into the page.

**Comment by ElTimuro** [comment]
> Hi @ElTimuro, I finally had the time to look at Documenso. Our use case: we need people to complete a form like [this one](https://github.com/opencollective/opencollective/files/13752675/fw9.pdf) and sign it. Other tools (Dropbox Forms, Docuseal) offer the option to add custom fields to the document. This allows two things:
> 
> 1. Make sure that the document gets completed (fields can be marked as "required")
> 2. Have the data accessible through the API in a standard format (without having to parse the result PDF)
> 
> ![image](https://private-user-images.githubusercontent.com/1556356/292494486-fc998c30-06fe-4d74-9152-8810555ce43d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNjQxMzIsIm5iZiI6MTcwMzI2MzgzMiwicGF0aCI6Ii8xNTU2MzU2LzI5MjQ5NDQ4Ni1mYzk5OGMzMC0wNmZlLTRkNzQtOTE1Mi04ODEwNTU1Y2U0M2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMTY1MDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjMwNjg4ZWIyZGIxNzk5ZDBiYzBkNTc4M2EwYmFlMTIxZmUxNDRjNTMyM2ZkYTljYjY5NzFiYjQ3OTJiMzI4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Qyo4mZYbVjhVlZSS2hgT5cM4v85MYzFa1zMp2vKIoiQ)
> 
> Is that something you're supporting (or are planning to support)? Is there documentation for Documenso's API?

@Betree We are close to releasing our API version 1 (target is Q4). Filling and later accessing custom fields will be added soon after that.

**Comment by Betree** [comment]
After some testing and internal discussions, we have decided to go with an in-house solution. While Documenso and Docuseal looked great, we have significant advantages for going with a custom flow (mostly branding, UX, and privacy) at this point.

@ElTimuro thank you for taking the time to comment on this issue; we'll definitely consider using Documenso for other use cases in the future!

**Comment by ElTimuro** [comment]
- @Betree, thanks for the update. We are here, just ping us if sth. comes up

- Happy to discuss internal design choices if you are interested. Having just gone through the same maybe we can share sth. usefull

**Comment by omohokcoj** [comment]
>we have significant advantages for going with a custom flow (mostly branding, UX, and privacy) at this point.

@Betree understand your decision regarding going with an in-house implementation - I just wanted to point out that you probably can get all that with DocuSeal hosted on-premises:
- You can completely customize the embedded signing UI design with CSS to match your website style:
https://www.docuseal.co/guides/embed-document-signing-into-web-app-with-javascript (see Styling form with custom CSS)
- You can host DocuSeal yourself and no-one except you will be able to access the data stored in the self-hosted app:
https://www.docuseal.co/on-premises
