### ISSUE TITLE
Provide a way to set "One Time" as an interval in URL params

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6264]
https://opencollective.com/embed/papertree-bedstuy/contribute/custom-43382?interval=one-time should force the step details to pre-select "One Time" contribution.

**Comment by Betree** [comment]
Resolved by https://github.com/opencollective/opencollective-frontend/pull/8508 + https://github.com/opencollective/documentation/pull/138

**Comment by rudyfraser** [comment]
Did this change also include removing the "platformContribution" parameter?

**Comment by Betree** [comment]
@rudyfraser Not related to this specific issue, but yes https://github.com/opencollective/opencollective-frontend/pull/8508 took care of removing the `platformContribution` parameter that was marked as deprecated and planned for deletion since long ago.
