### ISSUE TITLE
Personal tokens follow-up

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6267]
Followup on https://github.com/opencollective/opencollective/issues/5736 (https://github.com/opencollective/opencollective-frontend/pull/8455 + https://github.com/opencollective/opencollective-api/pull/8315)

- [x] Add a link on `frontend/pages/applications.js` towards the new Developer settings (see https://github.com/opencollective/opencollective-frontend/pull/8455#issuecomment-1362095623)
- [x] Remove corresponding E2E test `frontend/test/cypress/integration/00-applications.test.js`
- [ ] Remove "Applications" link in user menu
- [x] Check `expiryDate` for tokens
- [ ] Deprecate `applications` on GraphQL V1, along with `createApplication` and `deleteApplication` mutations
- [ ] Update docs
  - [x] https://github.com/opencollective/opencollective-pdf/blob/40b2cd8c411d5e3391f7624750479a2fb9285dee/README.md#L82
  - [ ] https://github.com/opencollective/opencollective-rest/blob/b869228461b2628daa2e85d8d94d2b4d96439f53/docs/transactions.md#L39
  - [ ] https://github.com/opencollective/documentation/blob/d0ba160a20eed13dcf6d3b9f6ab61e8ae4421230/contributing/development/api/collectives.md#L169
  - [ ] https://blog.opencollective.com/open-collective-graphql-api-preview/
  - [ ] https://graphql-docs-v2.opencollective.com/access

Bonuses:
- [x] Log last usage date

**Comment by flickz** [comment]
>  Remove frontend/pages/applications.js, redirect it to /:userSlug/admin/for-developers

@Betree Do we want to do this or implement @znarf's idea [here](https://github.com/opencollective/opencollective-frontend/pull/8455#issuecomment-1362095623)?
