### ISSUE TITLE
Root admin action to change a users email adress 

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6268]
## Who is your user?
Any user logging into Open Collective 

## What are they trying to achieve?
Need to change their email address and are unable to access their old email and therefore are unable to access their account

_When a user needs their email updated, I want to be able to do this via root admin, so I don't have to escalate to suds 

## How are they currently doing this?
Currently escalating to suds - unsure how he does this 

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment]
I'm advocating against this unless we can properly educate the entire support team about the security implications.

Contacting support to ask for an email change is a very common way of social engineering, with serious consequences. The attack flow usually goes like that:
1. Alice has an account like `alice@gmail.com`
2. Bob contacts support pretending to be Alice, saying she lost access to her email and needs it to be changed to `alice2@gmail.com`
3. Support changes the email
4. Bob now has full access to Alice's account, including the payment methods and private information

Verifying that someone actually owns an account when they lost access to the email usually requires:
- To ask for some private details; eg. last 4 numbers of the card used for contributing
- Or to verify in another way; eg. if they linked a Github account, ask them to upload a specific file with that account

**Comment by BenJam** [comment]
> I'm advocating against this unless we can properly educate the entire support team about the security implications.

+1

perhaps we could solve this by having users add a secondary 'backup' email address? some services do this and it's a reasonable safety method. Perhaps this goes aw#1738 e have #1738 generally available.

**Comment by shannondwray** [comment]
@SudharakaP and I were discussing this in our meeting the other day. We were thinking adding a backup email would be a good security measure and we were wondering if there was a better way of verifying ownership of an account rather than checking credit card details, posting codes on socials. Can we trigger a 2FA code that goes to someone email? Is there best practise surrounding this?

**Comment by Betree** [comment]
> Can we trigger a 2FA code that goes to someone email? Is there best practise surrounding this?

2FA is not enough to confirm the identity. It's a **second** factor; we'll need to keep verifying the request via other means (credit card, socials, etc). 2FA will still play its role of protecting the account after changing the email, since we're not supposed to reset it in the process.

**Comment by SudharakaP** [comment]
As per the discussion at, https://coda.io/d/_dEguIswyoKq?encodedLocationContext=eyJjb21tZW50VGhyZWFkSWQiOiJyLXd0ckFHY0tQUWUiLCJwYWdlSWQiOiJzZWN0aW9uLVA4cENSRHY1V2wiLCJ0eXBlIjoiZ3JpZCIsIm9iamVjdElkIjoiZ3JpZC1ZLUxJR0lNS1FwIiwicm93SWQiOiJpLWE0MVVqRUZLWEYifQ closing this issue.
