### ISSUE TITLE
Duplicate monthly user limit under organization payment methods

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#627]
Hey just noticed this on my organization profile when editing payment methods, it seems to show the user spending limit twice:

![screen shot 2017-11-06 at 7 06 00 pm](https://user-images.githubusercontent.com/30665166/32471980-c154e726-c325-11e7-8686-ddbef58b3ad7.png)

Its the Foynt organization, I'm using google Chrome.

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by piamancini** [comment]
I can't reproduce on my end, I'm seeing only one.

**Comment by nicobarretoOC** [comment]
mmm maybe it's an isolated case...
