### ISSUE TITLE
Platform Errors notify Engineers 

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6277]
## Who is your user?
All users

## What are they trying to achieve?
An automatic feedback loop when things out of the ordinary happen on the platform 

See image attached from Trade me (New Zealand Marketplace website) 

_When something doesn't behave as expected, I want to automate a notification to the engineers, so our team can have better insight into our platform and bugs_

## How are they currently doing this?
not sure 

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))
![IMG_0945](https://user-images.githubusercontent.com/79115149/210958026-bad2cfa5-2cbf-40e2-8c21-1f79bae23728.PNG)

**Comment by Betree** [comment]
We're already getting errors reported to https://sentry.io, which allows us to detect & fix stuff without user intervention.

**Comment by Betree** [comment]
Closing as, if I understood correctly, we already have that.
