### ISSUE TITLE
Signing Into Account While in Contribution Flow Sends Wrong URL to Email

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6279]
This issue has been noticed many times on Freshdesk, for example, https://opencollective.freshdesk.com/a/tickets/156745. 

It seems that we are sending the wrong url when the user signs in through the contribution flow. And when they click on the email link they get an error. 

[error-logging-in.webm](https://user-images.githubusercontent.com/12435965/211056175-e0088fba-79dc-4b2c-a632-c3fc7a94f6a4.webm)

The problem here is that we are not handling empty and duplicate the query parameters in the url which leads to a malformed URL.

**Comment by Betree** [comment]
This should actually be resolved by https://github.com/opencollective/opencollective-frontend/pull/8508
