### ISSUE TITLE
Typo on Spanish version under EDIT ORGANIZATION

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#628]
I found this under adding members option for organizations:
![screen shot 2017-11-06 at 7 09 22 pm](https://user-images.githubusercontent.com/30665166/32472057-35a59e86-c326-11e7-9e2d-cdf6a356c21d.png)

**It should be replaced with "sumar"**

**Comment by piamancini** [comment]
fixed https://github.com/opencollective/frontend/pull/99
