### ISSUE TITLE
Add location when creating a collective

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#6281]
Similar to #6077 as we've continued to invest in capabilities like #6073, #5745 and #3892 we find it difficult to categorise Collectives by geography. 

Ideally we want collectives to describe the area in which they're working rather than the area in which they're based. For instance, 1k project might be based in the US but is obviously focussing its work in Ukraine.

I'm not sure whether the current location (which needs some work #5999, #3494, #1451) is used for administrative purposes, in which case we may need two locations. I would prefer to use one. 

## Proposed solution

Add 'Location' to the create collective form (https://opencollective.com/create/community) with help text similar to:

> Where does your collective work? This information will be used to help supporters find you.

**Comment by Betree** [comment]
We should make sure that we implement that using the location picker that we want to use in the future: https://github.com/opencollective/opencollective/issues/5999. We have two possible approaches for the location picker:

1. Use our `StyledInputLocation`, our new default for expenses and the contribution flow. It adapts its field depending on the country you pick (e.g., it will suggest states for the US). This component is ideal for collecting exact postal addresses (for legal reasons, or to ship something).
![image](https://user-images.githubusercontent.com/1556356/211259843-dbac91a3-b773-4d9c-be6a-468fb1d9749d.png)

2. **Use Event's location picker**: my personal preference, though the input could benefit some polishing if we're going to expose it on the create collective page (ideally, I would love for the geocoding/locations search not to use Google's APIs)
![Peek 2023-01-09 08-40](https://user-images.githubusercontent.com/1556356/211260160-da055b82-1f3e-4f5d-838a-03a6a126b200.gif)

**Comment by iamronen** [comment]
Yesterday we had a (late in the cycle) kickoff meeting for the locations effort which left the following impressions.
All participants are welcome to add comments if you feel something is missing here..

## Desired Outcomes

### Primary

1. Two kinds of location information are needed for collectives:
     - A "display location" which is a geolocation that where a collective is active (this can be a country, region, city, neighborhood up to a specific address). This serves capabilities such as discover (where are collective active) and in the future to also enable collectives to geographically connect with each other). This information is made PUBLICLY available.
   - A collective can also provide a well structured mailing-address (this requirements seems at the moment to apply more for Europe then for the USA).
2. "Discover" will need to be migrated from the initial (tag-based) implementation to the new "display location" information.

### Secondary

1. Events and Projects can also be assigned a geolocation (which will add a layer of complexity to Discover, one collective can have numerous budgeted projects in different locations).


## Considerations

1. What UI component(s) do we want to use for entering geolocation and specific address information?
2. Changing location input effects: 
   - Collective creation
   - Collective settings
   - Collective profile
   - Notifying existing collectives (this should probably be done by fiscal hosts) they can update their information.
3. What is involved in the trasition process from the tag-based discover solution to geolocation (changing discover, converting tag-based information to geolocation, removing tags).
4. How do location choices effect open-source collectives?
5. If we choose to work with Google does that have any security implications (such as collectives making themselves unconsciously known to Google).
6. There is a potential (though hypothetical at this point) that spam collectives can abuse any potential to input multiple addresses. 
7. Is there a good reason to consider creating a table for storing multiple addresses.

**Comment by iamronen** [comment]
@gustavlrsn and I had a followup conversation to convert the insights this into this sequence of scopes of work:

## Prioritized Scopes
 - [ ] Select geolocation mechanism
 - [ ] Decide if we are storing multiple addresses in current tables or doing "locations table"?
 - [ ] Implement "display location" entry for collectives in service of Discover.
      - [ ] in Collective creation
      - [ ] in Collective settings
      - [ ] in Collective profile
 - [ ] Transitioning existing Discover dataset (currently in tags) to geolocations
      - [ ] Migrating data
      - [ ] Update Discover
      - [ ] Decide if the existing location tags need to be removed (manually, or script)
      - [ ] If necessary, run location tag cleanup
 - [ ] Implement optional mailing-address for collectives (in addition to geolocation for Discover)
      - [ ] in Collective creation
      - [ ] in Collective settings
      - [ ] in Collective profile
 - [ ] Create a fiscal host setting enabling a fiscal host to decide if the mailing address is required. 
 - [ ] Implement "locations table"

The first two scopes are prerequisite research work and will receive immediate attention.
Depending on the outcome of that research and decision we see two potentials paths for work in the time remaining in this cycle:
1. Infrastructure first - implementing the "locations table" to prepare for better location implementation in a future cycle.
2. UI first - implementing the "display location" for collectives and, if time allows, migrating Discover.

**Comment by gustavlrsn** [comment]
We decided after thursday's standup to focus on adding a Locations table in this sprint.

### Week 6
- [ ] Finalize a suggested schema for the Locations table https://github.com/opencollective/opencollective/issues/3494
- [ ] Start implementing that table for existing Locations

**Comment by gustavlrsn** [comment]
A mockup for how we could differentiate between Display Location and Legal address in the Collective settings.

<img width="876" alt="image" src="https://user-images.githubusercontent.com/1552194/219339890-70fff07d-fa9c-47f3-88fa-316952d79f68.png">

Display location could benefit from using the autocompleting input to allow some more freedom in how you would want to define your location, i.e. only specify the city or country I am in and not a full address (but both should save to the same Locations table).

**Comment by gustavlrsn** [comment]
Updated mockup to be able to handle a custom location not found by the autocomplete service:

![Image](https://user-images.githubusercontent.com/1552194/219675359-bcca7e0b-2ef2-4763-9984-e440482da438.png)

**Comment by gustavlrsn** [comment]
Good feedback regarding "legal address" in Slack from @alanna:
> a Collective is likely to have some location (city, neighborhood) but will not have a specific address, because legally it’s not really a thing, it’s part of the host. So it might be confusing to ask for a full address of a Collective like that. This goes for OCF, OSC, Gift Collective, etc, but might be different for OCE Collectives whose address is the admin’s address. I think specific addresses are more likely associated with he individual admin’s profile, not the Collective, and Collectives should inherit their Host’s specific address for legal reasons (e.g. for printing on invoices).

Maybe "legal address" should only be displayed if you're an independent collective (fiscal host for yourself), or if your host has the [Bill to setting](https://github.com/opencollective/opencollective-frontend/pull/8053) set to `Collective`?

Unless there are other use cases of the address I'm overlooking.

**Comment by gustavlrsn** [comment]
Also noting down another feedback from @BenJam in last Friday's demo of the mockup above, the ability to have **multiple display locations**.

While its easy to imagine cases where this might be useful, I'm wondering if it is worth the added complexity in UX, and how strong of a need this is. The most common UX pattern of a profile location field is only having one per profile, stepping outside of this should at least require a good motivation I think.

If I operate in two cities, maybe defining my location as the country or state those are in, is enough. Or if operate in two states, I could use the country or region (e.g. Midwest US, if we end up supporting regions as part of the structured dataset) as my display location.
