### ISSUE TITLE
A User-centric approach to activity on Open Collective AKA 'Workplace'

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#6285]
I wanted to break this out of #4829 because there's a distinct piece of scoping and design work to be done here separate from other work within the onboarding issue:

> Right now our users have to navigate between profiles, and find within them the parts of those profiles that are 'active'. For administrators and people working across a number of Collective, projects, and events this can be quite inefficient and irritating.

> There's not a clear separation between the 'working' parts of Open Collective (filing, approving and paying expenses) and the 'profile' parts of Open Collective (my Collective, organisation, personal profile).

> For example to file an expense for /opensource I have to go to the profile page and find the right button, instead of having a 'file an expense' button on my (logged in) dashboard at [opencollective.com](http://opencollective.com/). This is different from an exploratory experience where I might be searching or browsing for projects to support or events to attend etc.

> The single-entity approach to navigation and UX is providing a very fractured experience for users who interact with a number of Collectives, as a supporter, contributor or administrator. We see ourselves building fixes for specific problems like showing all your submitted expenses in one place https://github.com/opencollective/opencollective/issues/3749.

This issue is nowhere near being ready to work on from an engineering point of view but we could get to a place where the vision for this is clearer and can inform, say, some of the changes that we might propose in #6286 and #5680

**Comment by iamronen** [comment]
had a sync call with @Memo-Es and Tomas and I am currently preparing a pitch for a first phase of work for next cycle.

**Comment by iamronen** [comment]
A long term view of this campaign has been shared with the team:
1. [Slides Presentation](https://docs.google.com/presentation/d/1AfnSTFFpZJqEAuUkzb9qt14tX72RZN1Zocj_-CNr988/edit)
2. It was presented during the last five minutes of [Friday Demos](https://around.co/playback/6b24d390-7f08-4d06-9b33-bfd881d19324?sharedKey=e786109f-35a5-4f48-8b78-eb86ebff9830)

This project already has a team ready to go design - @Memo-Es , engineering - @gustavlrsn 
A pitch for a first phase of work is [ready for next cycle](https://github.com/opencollective/opencollective/issues/6385).

**Comment by BenJam** [comment]
closed in favour of https://github.com/opencollective/opencollective/issues/6385
