### ISSUE TITLE
Improving onboarding of Open Source Collectives

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#629]
Issues I see while enabling Open Source collectives:
- Activating Open Collective PR gets "huh, why did this happen?" or "I don't like this" comment half the time. Means that half the time we are already starting from a weak position and it's harder for a single admin to now advocate for us.
- No follow up after we activate the collective and they merge

Steps that we can take to immediately improve experience:

1. Post-signup: email the core admin with 2 tasks
- ask them to add other admins (no longer happens in the flow)
- announce to the repo (if they think others will be surprised)

2. We need to send an email to each new admin added explaining what we are and who signed them up (this part is important).

3. We review and activate them (manual)

4. We submit a PR on their repo and ideally need to cite who asked this collective to be created (manual)

5. Follow up with the core admins about next steps
- Send a few more things to do: connect slack/gitter, twitter, etc.

6. 1 week followup: How to get most out of Open Collective (merge our PR, share the page with existing companies and users, etc)

7. 2 week followup: Don't forget to file expenses, easiest way for users to see how money is spent. also, we pay them every Friday

8. 1 month followup: How can I help?

**Comment by piamancini** [comment]
@asood123 This is great. 

Also this is the email they get automatically after signup: 

> Thanks for signing up on Open Collective! Your collective has been created: bootstrap-vue.
>  
> While you wait for approval to start receiving donations, check out our helpful how-to guide: Ten Steps to Successful Open Source Crowdfunding.
>  
> Top tips:
>  
> Make your collective your own. Login and hover over elements to edit them.
>  
> Feature your backers & sponsors on your Github & website. We'll submit a PR to your README. Find instructions to add your backers to your website here.
>  
> Submit expenses: https://opencollective.com/bootstrap-vue/expenses, to let potential backers know what they're helping to fund.
>  
> Spread the word. You can connect your Twitter account to your collective and automatically thank your backers. You can also connect your Slack/Gitter for notifications.
>  
> Looking for inspiration? Check out some other collectives to see how they're raising and spending funds.
>  
> If you have questions, join our Slack or email us. We're here to help!
>  
> Cheers,
>  
> – Team Open Collective
>  
> We can do great things together
>  
> For questions or feedback just reply to this email.
>  
> You can also follow us on Twitter or come chat with us on our public Slack channel.
>  
> Made with ❤️ in NYC, San Francisco, Guadalajara and Brussels

We need to update it for sure! 

Adding to this comment: [here's a doc](https://docs.google.com/document/d/1cmuZBfSeIFr2O-zcRC1BNpKJ1sw3YjEqO44JT5jjz_8/edit) I made a while back - before V2 - about the comms steps we take and what I think we need to do.

**Comment by piamancini** [comment]
done with new retention emails and with @monkeywithacupcake's help in submitting PRs
