### ISSUE TITLE
Receiving host onboarding email before being approved

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6293]
**Describe the bug**
I applied to be hosted by OSC and received an onboarding email while I was not yet approved:

![image](https://user-images.githubusercontent.com/1556356/211539882-da0b2c68-4103-4664-9978-a7fb42ad6ab2.png)

**To Reproduce**
1. Go to /opensource/apply/intro
2. Apply with a new collective
3. Check your emails

**Expected behavior**
The email should be submitted only after being approved, otherwise the admin could wrongly think that their application has been approved.

**Comment by alanna** [comment]
Is this affecting OCF?

**Comment by Betree** [comment]
@alanna No only OSC is affected by this. They use a special `templates/emails/collective.created.opensource.hbs` template for collectives created through their apply flow. In https://github.com/opencollective/opencollective-api/pull/5801/files#diff-02c0d9e66916d41cbe7e30ba17d230c0572c39da1fda5e16ae89f0563363b606, the wording of this template was changed with the wrong assumption that the collective was necessarily approved already, but that's only true if they successfully went through the Github apply flow:

![image](https://user-images.githubusercontent.com/1556356/222664308-a7a45889-95c7-4440-a847-6ef2e05f7da2.png)

In the generic template, we do this:

```hbs
<p>
  {{#if hostPending}}
  Your {{accountType}} is pending approval for Fiscal Hosting by (<a href="https://opencollective.com/{{host.slug}}">{{host.name}}</a>).
  Your Host will hold money on behalf of your {{accountType}}.
  Once approved, your {{accountType}} will be able to receive money.
  {{else}}
  Your {{accountType}} is hosted by <a href="https://opencollective.com/{{host.slug}}">{{host.name}}</a>, which will hold money on its behalf.
  {{/if}}
</p>
```

I suggest introducing the same logic in OSC's template.
