### ISSUE TITLE
Event ticket 400 error

### ISSUE THREAD

**Issue by zimbatm** [opencollective/opencollective#6294]
**Describe the bug**

After clicking on "Save" when adding a new ticket, I get a 400 error back and the ticket is not saved to the event.

**To Reproduce**
1. Go to https://opencollective.com/nixcon/events/nixcon-2023-54b64532/admin/tickets
2. Add a ticket
3. See error: "Response not successful: Received status code 400".

**Expected behavior**

No error, or better feedback on why the error is happening.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Brave
 - Version: 1.46.133 Chromium: 108.0.5359.71 (Official Build) (64-bit)

**Additional context**
Inspecting the API response from the browser, it returned this error:

```json
{"errors":[{"message":"Variable \"$collective\" got invalid value { __typename: \"SocialLink\", type: \"WEBSITE\", url: \"https://2023.nixcon.org/\" } at \"collective.socialLinks[0]\"; Field \"__typename\" is not defined by type \"SocialLinkInput\".","locations":[{"line":1,"column":25}],"extensions":{"code":"BAD_USER_INPUT"}}]}
```

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
Thanks for reporting this bug @zimbatm! I can reproduce for other profile types as well.

Note that this does not happen with the new Edit Tiers page (that is not yet deployed to production) as we're facing a typical case of #1451.
