### ISSUE TITLE
Custom settings for collectives

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#63]
It would be great to have a flexible way to add custom settings to a collective.

For example, @phated wanted to change the color of the "Be part of it!" button on the collective page of GulpJS.

Here is what needs to be done to make this happen:

- [ ] In the `api/server/models/Group.js` we should add a new column `settings` like we did for `tiers`
https://github.com/OpenCollective/api/blob/master/server/models/Group.js#L59-L69

- [ ] and write the appropriate migration file, e.g. 
https://github.com/OpenCollective/api/blob/master/migrations/20160211190935-add-group-tiers.js

For now, we would just use it to customize some styling and also to define if fees should be added on the collective side (default) or on the donor side (see https://github.com/OpenCollective/OpenCollective/issues/15#issuecomment-210726727). So I'd recommend something like (open to suggestions):

    group.settings = { 
      feesPaidBy: 'BACKER', // or HOST or COLLECTIVE (default)
      style: { 
        'backgroundImage': 'url', 
        'buttonBackgroundColor': '#cccccc' 
      } 
    }

While right now we can edit a few options of a group in the app, I think it makes more sense to have a settings page or a settings modal on the website (we could add a "settings" menu in the black bar below the big background image).

- [ ] We should create a new container in the website repo like we did for the `DonatePage.js`
https://github.com/OpenCollective/website/blob/master/frontend/src/containers/DonatePage.js
and name it `SettingsPage.js`.

We could probably reuse most of the `GroupSettings.js` from the app:
https://github.com/OpenCollective/app/blob/master/frontend/src/containers/GroupSettings.js
and then add to it the option to edit the custom settings (for now you could hard code the settings that you would want to add).

- [ ] We would also have to add an end-to-end test like we have here:
https://github.com/OpenCollective/website/blob/master/test/e2e/expenses_page.js

**Comment by piamancini** [comment]
I think this issue was partly solved in the last push. @xdamman can we close it?
