### ISSUE TITLE
add new member creates two users at the same time

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#630]
New member is added to this org in this link
https://opencollective.com/renablehost/edit#members
Creates two entries in postico see User ID8843 and ID8841 with the same email address as well as two collectives for them 10072 and 10073

Then the system adds and /null as the new member see https://opencollective.com/renablehost/ the first avatar is a /null and none of the users created are added. 

The same thing happened with dot net finance and it was resolved when I removed the email address from the duplicated user. 

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by piamancini** [comment]
We should probably run a query for duplicated emails in user data base and take it from there.

**Comment by asood123** [comment]
A few things I saw while trying to repro it:

- members table has extra rows added and then marked deletedAt
- adding members from org interface has issues unless you reload the page. Recently added members are editable.

**Comment by asood123** [comment]
Haven't seen this in a while. Please reopen if there is a recent example
