### ISSUE TITLE
Allow collective/host admins to filter by drafts

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6300]
As a collective/host admin, I can filter expenses by draft (e.g. on https://opencollective.com/babel/expenses).

**Comment by iamliamc** [comment]
Hey @Betree this one looks interesting to me. 

Is the scope of this ticket to add an option to the `status` filter for expenses that lets a collective/admin filter expenses by draft? 

Let me know if you think this is an appropriate one to take on now.

**Comment by Betree** [comment]
> Is the scope of this ticket to add an option to the `status` filter for expenses that lets a collective/admin filter expenses by draft? 

Exactly ✅ I've assumed that it's doable with frontend-only changes, but maybe we'll discover we need to make small changes in the API too.

> Let me know if you think this is an appropriate one to take on now. 

It is! I'll assign it to you, feel free to ping me or the engineering team if you need anything.

**Comment by Betree** [comment]
Duplicate of https://github.com/opencollective/opencollective/issues/6224
