### ISSUE TITLE
Platform Error codes

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6301]
## Who is your user?
Any user who is experiencing a bug or error 

## What are they trying to achieve?

_When an error occurs on the platform, I want to provide the user with instructions to contact support and inform them of the error code, so I can have a better understanding of what’s going on rather than just getting an error code_

Even better this would automatically notify the engineering team and we could then let the user know when this error has been resolved

## How are they currently doing this?
An error code just displays 

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by BenJam** [comment]
can i ask: is this the little 'toast' notifications that are sent when processing a transaction (card failure etc)? or more systemic failures like a 'service unavaialble error?

**Comment by shannondwray** [comment]
I think it depends if it's something that the user can fix themselves i.e. they need to change/update their credit card information vs. Something that is broken on the platform and needs development help

**Comment by alanna** [comment]
Same as #5560 ?
