### ISSUE TITLE
Error 400 about  `_typename social media` block the Tier edition

### ISSUE THREAD

**Issue by dsmrs** [opencollective/opencollective#6302]
**Describe the bug**

Try to add or delete a "tier". When a I clic on save, I have a 400 error with no more info. If I look to the network, I see the error in the response:

```
{"errors":[{"message":"Variable \"$collective\" got invalid value { __typename: \"SocialLink\", type: \"WEBSITE\", url: \"https://mosquito-velomobiles.org/\" } at \"collective.socialLinks[0]\"; Field \"__typename\" is not defined by type \"SocialLinkInput\".","locations":[{"line":1,"column":25}],"extensions":{"code":"BAD_USER_INPUT"}},{"message":"Variable \"$collective\" got invalid value { __typename: \"SocialLink\", type: \"GITHUB\", url: \"https://github.com/MoquitoOS\" } at \"collective.socialLinks[1]\"; Field \"__typename\" is not defined by type \"SocialLinkInput\".","locations":[{"line":1,"column":25}],"extensions":{"code":"BAD_USER_INPUT"}},{"message":"Variable \"$collective\" got invalid value { __typename: \"SocialLink\", type: \"DISCORD\", url: \"https://discord.gg/************" } at \"collective.socialLinks[2]\"; Field \"__typename\" is not defined by type \"SocialLinkInput\".","locations":[{"line":1,"column":25}],"extensions":{"code":"BAD_USER_INPUT"}}]}
```

To be able to delete the tier, I add to delete all my social links before, delete de tier then re-add the social media links.

**To Reproduce**
1. Go to your collective settings
2. Click on on tiers and add a new tier
3. fill the form and clic on save
4. See error 400

**Expected behavior**

Should save as normal, or at least have an explicit error

**Screenshots**

![Capture](https://user-images.githubusercontent.com/12203221/211800081-9cf792f9-503e-42fa-a76f-22425a75eb6c.PNG)

**Desktop:**
 - OS: Windows 10
 - Browser Chrome and Edge

**Additional context**

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by dsmrs** [comment]
It seems liked to #6294

**Comment by hdiniz** [comment]
Working on it @dsmrs
