### ISSUE TITLE
[PROJECT] Collective Tag Enhancements

### ISSUE THREAD

**Issue by gustavlrsn** [opencollective/opencollective#6308]
### Suggested tasks 
- updated input for tags editing, more sophisticated
  - ability to order tags
- modal to edit title, description, tags, social links directly from the collective page?
- suggested tags
  - can collectives be searched with their suggested tags?
  - based on already added tags
  - using AI to generate from title, description
  - tags relevant to the host (hand picked or most popular)
    - most popular by default, hand picked in db
- auto-completion
  - based on all collective tags on the platform, or on the given host
- send a communication to collectives 
  - explain why tags are useful or relevant
  - prompt to review and edit based on suggested tags
- clean up database entries
  - lowercase everything
  - deduplicate very close tags
    - opensource => open source

**Comment by kaylarep** [comment]
A few other Tags-related issues (if any of these aren't relevant to this Project, lmk and I'll remove them)
- https://github.com/opencollective/opencollective/issues/5523
- https://github.com/opencollective/opencollective/issues/5537
- https://github.com/opencollective/opencollective/issues/5570
- https://github.com/opencollective/opencollective/issues/5536
- https://github.com/opencollective/opencollective/issues/5534
- https://github.com/opencollective/opencollective/issues/5774
- https://github.com/opencollective/opencollective/issues/3892

**Comment by gustavlrsn** [comment]
@kaylarep thank you for adding these! This project is a focused on Collective tags but I think it's great to surface these here as well, since the work we do now might solve or impact how we can solve other tag issues as well.

I created a board for Tags in general and added them there: https://github.com/orgs/opencollective/projects/10/views/1.

In that board we can also start to refine what we will do in this sprint, focused on Collective tags: https://github.com/orgs/opencollective/projects/10/views/2

**Comment by BenJam** [comment]
- [ ] fixing a few of the more explicit issues listed above 
- [ ] sync and design review of above

**Comment by gustavlrsn** [comment]
## Unedited notes from call with @kaylarep and @Memo-Es 

-  back end up support both cases
   - create a collective before you know the host
   - will show most popular tags across all hosts
- can also show tags that are popular with that host
- should we try to find tag patterns within a host or across all collectives
  - for a donor it makes sense to be platform-wide
  - for collectives, it might be more host-centric. e.g. osc's collectives have common tags for their host's language
    - for this reason 'javascript' should not appear as a suggested tag for groups applying to OCF
  - empo
- middle path
  - suggested tags in the field in the database for the admin to add if the
- design need:
  - why are tags important?
  - improving platform-wide how we think about tags
- how many collectives enter the platform thru OC or thru a fiscal host?

**Comment by gustavlrsn** [comment]
### An edited summary of the above call:
- first step will be to add autocompletion to collective tags input, showing most popular tags across all hosts as the default
  - https://github.com/opencollective/opencollective/issues/5523
- design is still being worked on, but we will start with adding an autocomplete tag input, that can evolve if the design demands it
- a discussion on whether tags should be host-centric or platform-wide

**Comment by BenJam** [comment]
- [ ] complete tag creation on create collective
- [ ] sync on design for suggested tags
- [ ] do we want to update other tags (expenses etc) to new component?

**Comment by kaylarep** [comment]
> do we want to update other tags (expenses etc) to new component?

I vote yes! The more consistency we create for tagging (regardless of where it shows up on the platform), the better.

**Comment by gustavlrsn** [comment]
> > do we want to update other tags (expenses etc) to new component?
> 
> I vote yes! The more consistency we create for tagging (regardless of where it shows up on the platform), the better.

Reviewing this I think what is missing for that is a design for the inline editing of Expense tags. Just popping in the new component doesn't really work. ping @opencollective/design 
<img width="948" alt="Pasted image 20230120110701" src="https://user-images.githubusercontent.com/1552194/215479380-ff34030d-deba-4a0a-ba85-24f9592dd362.png">

**Comment by gustavlrsn** [comment]
### Week 4
- [ ] finalize and merge https://github.com/opencollective/opencollective-api/pull/8462
- [ ] review and merge https://github.com/opencollective/opencollective-frontend/pull/8571
- [ ] add Edit Tags modal on Collective page
- [ ] add Tags helper text, review copy (posted in #wording):
   <img width="585" alt="image" src="https://user-images.githubusercontent.com/1552194/215481468-7130b0c6-43c9-4bfe-bbca-145fc51aa275.png">
- [ ] allow hosts to set their own tags (?)

**Comment by gustavlrsn** [comment]
> > > do we want to update other tags (expenses etc) to new component?
> > 
> > 
> > I vote yes! The more consistency we create for tagging (regardless of where it shows up on the platform), the better.
> 
> Reviewing this I think what is missing for that is a design for the inline editing of Expense tags. Just popping in the new component doesn't really work. ping @opencollective/design

Was notified by @aminakazi that there is a actually a [design for this in Figma](https://www.figma.com/proto/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab-%F0%9F%A7%AA?page-id=18718%3A248309&node-id=18956%3A267423&viewport=-134%2C-777%2C0.22&scaling=min-zoom&starting-point-node-id=18956%3A267423). 

Looks good to me, and would make it consistent with the planned Edit tags modal on the Collective page.

**Comment by gustavlrsn** [comment]
@aminakazi recorded a Loom about an issue I'm seeing with the edit tags modal on expenses (basically, hard to see what expense you are editing tags for), and also an idea for how it could be solved: https://www.loom.com/share/aefd030aa0d24fc2adf3fcfee93cb25e

**Comment by gustavlrsn** [comment]
### Week 5
- [ ] Review/merge PRs:
  - https://github.com/opencollective/opencollective-api/pull/8462
  - https://github.com/opencollective/opencollective-frontend/pull/8571

**Comment by gustavlrsn** [comment]
- [Proposed design for expense tags issue](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=20039%3A138093&t=Jp1cSualToKzhp64-11) from @opencollective/design: , but considering this out of scope for this sprint.

### Week 6
- [ ] Fix issue of materialized view (CollectiveTagStats) not updating
- [ ] Finalize react-dnd replacement: https://github.com/opencollective/opencollective-frontend/pull/8633
- [ ] Merge: https://github.com/opencollective/opencollective-frontend/pull/8571

**Comment by shannondwray** [comment]
No documentation necessary
