### ISSUE TITLE
Missing `ADDED_FUND` translation on orders page

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6311]
See https://opencollective.com/babel/orders?searchTerm=GitHub+Sponsors+payment.

We do have the translation on https://opencollective.com/babel/transactions?searchTerm=GitHub+Sponsors+payment.

![image](https://user-images.githubusercontent.com/1556356/212341449-4c6b4a61-ace2-4a22-9718-f70bbaf71973.png)

**Comment by vickywane** [comment]
I'd like to fix this @Betree.

**Comment by vj-codes** [comment]
Hey @Betree I'm contributing for the first time to this repo and would like to work on it but can't understand the title, can you please explain a lil more in description? thankss!

**Comment by Betree** [comment]
On [this page](https://opencollective.com/babel/orders?searchTerm=GitHub+Sponsors+payment) you can notice that the string `ADDED_FUNDS` is not properly formatted; it should be displayed like "Added funds".

**Comment by ShreyaPrasad1209** [comment]
I'm working on this issue @Betree
