### ISSUE TITLE
Support Spam

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6317]
## Who is your user?
I am getting a lot of spam messages coming through support 

## What are they trying to achieve?
Is there a way to investigate this? Put a captcha on our form? Block the email somewhere? 

_When triaging support, I want to reduce the amount of spam messages, so I can ‘it’s annoying’_

## How are they currently doing this?
Marking them as spam on freshdesk

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by SudharakaP** [comment]
Since most of our support are created from the form; [opencollective.com/contact](https://opencollective.com/contact), we could potentially add a Captcha there. 

@Betree : what do you think?

**Comment by Betree** [comment]
I agree; it's very frequent for contact forms to have a captcha, and there's an open security issue about this endpoint not being rate limited (which Captcha would also solve).

**Comment by shannondwray** [comment]
It would also be great if there was a way of not letting the form be submitted unless it has text in the subject and description, I get a lot of empty emails as well

**Comment by gustavlrsn** [comment]
@shannondwray @SudharakaP A Captcha field has been added to the Contact Support form

**Comment by SudharakaP** [comment]
> @shannondwray @SudharakaP A Captcha field has been added to the Contact Support form

Great. Thanks a lot for doing this. 👍🏽
