### ISSUE TITLE
add platform fee for donation ID 5892

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#632]
This is carbon ads donation to open source collective. 
We need to manually add the platform fee and edit net amount accordingly. 

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by oliviertassinari** [comment]
@piamancini Does the issue closed mean we can easily connect carbon ads revenue with opencollective?

**Comment by piamancini** [comment]
hi @oliviertassinari I followed up by email. Yes, should be super straight forward. Can you please join slack.opencollective.com #carbonadsnetwork channel?
