### ISSUE TITLE
Clean up Collective tags in database

### ISSUE THREAD

**Issue by gustavlrsn** [opencollective/opencollective#6325]
When adding a tag through the interface it will be lowercased automatically. When querying Collectives using tags the string is looking for lowercased versions, however, there are cases of tags that use capital letters in the database, these records won't be returned.

- [ ] Lowercase all Collective tags in db
- [ ] Transform obvious duplicates
  - [ ] `opensource` => `open source`
  - The "problem" of very similar tags should become less of an issue with #5523, that will autocomplete and show most popular tags by default

**Comment by Betree** [comment]
Maybe implement that as a script in the API project to easily re-run it again in the future?

For reference, we had a migration with a similar intent a few years ago: https://github.com/opencollective/opencollective-api/blob/main/migrations/archives/20200425013627-change-tags-to-lowercase.js.

**Comment by gustavlrsn** [comment]
Closing this, script merged in https://github.com/opencollective/opencollective-api/pull/8462 and have been ran in production.
