### ISSUE TITLE
Profile page error

### ISSUE THREAD

**Issue by NikitaKorevo** [opencollective/opencollective#6329]
**Describe the bug**
When I open my profile I get an error

```
./components/collective-page/images/ContributorsGridBackground.svg
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <svg width="1718" height="1450" viewBox="0 0 1718 1450" fill="none" 
|   xmlns="http://www.w3.org/2000/svg">
|   <g opacity="0.64">
```

**To Reproduce**
1. `npm run dev`
2. Go to http://localhost:3000/
3. Click on avatar
4. Click "View Profile" button 
5. See error

**Expected behavior**
I want to see my profile

**Screenshots**
![last-error](https://user-images.githubusercontent.com/48645737/212738190-fa93ff57-02c4-4629-9766-52f64aea2d45.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 19044.2486
 - Browser Google Chrome
 - Version 109.0.5414.74

**Additional context**

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
That's a known issue (https://github.com/opencollective/opencollective/issues/5836), but this one has better documentation. Thanks, @NikitaKorevo!
