### ISSUE TITLE
Hide PayPal Section for Independent Collectives

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6339]
As per discussion, https://opencollective.slack.com/archives/G46PNRCGP/p1673254458152859 we are no longer supporting PayPal for independent collectives. However showing the PayPal payouts section in their settings can be misleading so therefore I am proposing to hide this section for independent collectives. 

![image](https://user-images.githubusercontent.com/12435965/212980689-f5ec1cc0-971b-4668-8304-17ffc1b5d840.png)

**Comment by Betree** [comment]
> hide this section for independent collectives.

Unless it's already connected.

**Comment by SudharakaP** [comment]
Makes sense, and also its later decided that we are enabling PayPal on a case by case basis for independent collectives. So I am closing this.
