### ISSUE TITLE
New Tier Page Ticket Creation Shown Incorrect Fields

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6354]
It seems that in the new Tiers page within settings when the user tries to edit an already created ticket, some fields that should only be shown for a generic tier are also shown. The steps to recreate this is, 

1) Create an event.
2) Create a ticket within the event. 
3) Try to edit the ticket. 

The modal that opens shows type for example. And if you do select a Type the ticket disappears from the page completely. 

[ticket-bug.webm](https://user-images.githubusercontent.com/12435965/213637306-671c68c2-9814-49d5-8936-39bb1f5c14c6.webm)

**Comment by Betree** [comment]
Good catch, we've added the `forcedType` on Create but not Edit
