### ISSUE TITLE
Event attendee count correctness

### ISSUE THREAD

**Issue by clehner** [opencollective/opencollective#6356]
Event https://opencollective.com/decentsocial/events/decentsocial-conference-8c7e0a05 says "96 people going"
However, https://opencollective.com/decentsocial/events/decentsocial-conference-8c7e0a05/attendees.json contains only 15 attendee objects. The full list of attendee info objects was returned up to earlier this month.
The registration (order tickets) page https://opencollective.com/decentsocial/events/decentsocial-conference-8c7e0a05/order/49790 says the smaller amount ("Join 15 other fellow contributors")
Is the request missing some pagination parameters that also may be needed on the frontend?

**Comment by clehner** [comment]
Downstream related issue (`attendees.json` fetched from https://decentsocial.net/): https://codeberg.org/DecentSocial/website/issues/18

**Comment by Betree** [comment]
@clehner We fixed an [issue](https://github.com/opencollective/opencollective/issues/6380) that was potentially the root cause for this, could you try again?

**Comment by ianconsolata** [comment]
Hey @Betree just tried today and it looks fixed. Thanks for the quick turnaround.

**Comment by Betree** [comment]
> Hey @Betree just tried today and it looks fixed. Thanks for the quick turnaround.

Awesome, thanks for the update!
