### ISSUE TITLE
Submit expense form use of screen space

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6358]
Could the form use the full width of the modal? It looks odd using only half.
<img width="830" alt="Screen Shot 2023-01-23 at 4 14 43 PM" src="https://user-images.githubusercontent.com/5498878/213960172-b6cdc817-675c-4a29-aa0b-cb36f763b012.png">

**Comment by Betree** [comment]
I've seen this too but thought it was a local bug, I don't remember any issue mentioning such a design update.
