### ISSUE TITLE
Submit expense modal breaks to show legal name warning

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6359]
**Describe the bug**
See screenshot below

**To Reproduce**
1. Submit new expense
2. Add new payout method
3. Start typing in the name
4. Modal sort of breaks to show warning
5. Goes away once names exactly match

**Expected behavior**
The warning should appear within the modal without breaking it

**Screenshots**
![e1a171b3e75f0499cf5eec1f65e72d71](https://user-images.githubusercontent.com/5498878/213960781-9db3ed0e-eeeb-4109-b320-3a2d769d7cbf.gif)

  P3 high frequency, low impact

**Comment by Betree** [comment]
As shared in https://github.com/opencollective/opencollective/issues/6358, creating a new expense has not been redesigned; this is likely q regression from a different change
