### ISSUE TITLE
Can't pay multi-currency expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6362]
**Describe the bug**
The system will not let me pay this expense:
https://opencollective.com/bwt/expenses/113587

<img width="362" alt="Screen Shot 2023-01-23 at 10 29 49 PM" src="https://user-images.githubusercontent.com/5498878/214006427-14d0cf62-fa6f-4c11-83ff-efbe04087af1.png">

I'm guessing it's because there are 3 currencies involved (AUD, USD, NZD) but I don't understand how this happened or why the system let the user set it up this way. 

There has already been a lot of back and forth on this expense (because of #6333) so I'd really like to just edit it to NZD or USD and get it paid, but I wanted to give the team a chance to have a look in case it's a bug or something that can be improved to prevent this happening again. 

  P2 low frequency, high impact

**Comment by kewitz** [comment]
In the specific case where the user is filling a multi-currency expense to be paid to a bank account, they should be forced to pick the same currency as their bank account.
For some reason, this was not the case here. I'll investigate this.
For now, please convert the currency and amount of this expense to the same currency as the user's bank account.

**Comment by alanna** [comment]
I changed the currency and was able to pay it. It was offering three currency choices.

<img width="314" alt="Screen Shot 2023-01-24 at 8 47 43 AM" src="https://user-images.githubusercontent.com/5498878/214135430-f10095f6-68ea-4bae-9733-faf8a3f80772.png">

Possibly the admin invited the expense in AUD in the first place since they are in Aus?
