### ISSUE TITLE
one-time donations creating subscriptions

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#637]
userID8879  attempted a $100 one time, saw the email with the subscription and cancel it. Wasn't aware that 1st payment goes through and tried another time with the same result. 
This was this morning at  11:33 ATM (CEST)

Let me know when I can go ahead and refund one of the payments on Stripe. 

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by asood123** [comment]
fix: https://github.com/opencollective/opencollective-api/pull/1007
