### ISSUE TITLE
Collective with Canadian fiscal host cannot pay Collective with UK fiscal host

### ISSUE THREAD

**Issue by ianconsolata** [opencollective/opencollective#6372]
**Describe the bug**
The DecentSocial Collective / Event (https://opencollective.com/decentsocial/events/decentsocial-conference-8c7e0a05) is trying to pay meet.coop (https://opencollective.com/meet-coop) for digital event hosting.

Originally, meet.coop sent us a link to contribute directly to their OpenCollective. However, neither the DecentSocial Collective nor the DecentSocial 2023 event show up on the list of possible contributors, despite me being an admin of both. Only my personal account and my organizations show up
<img width="1048" alt="Screen Shot 2023-01-25 at 5 29 48 PM" src="https://user-images.githubusercontent.com/405465/214640215-d9218ea6-dfda-4791-ae50-e43748283bac.png">

So instead, we tried to invite Meet.coop to submit an expense to our Collective, but they encountered the following error:
![Screenshot from 2023-01-24 14-58-32 (1)](https://user-images.githubusercontent.com/405465/214640660-b2cd1bc0-72a1-4449-9fa1-8af59aed95d1.png)

For now, I will go ahead and pay it personally and apply for reimbursement, but it would be nice if we could pay directly. 

Based on the error message, it sounds like it might be something our Fiscal Host needs to enable? If so, it's not clear what steps our collective or our host needs to take to enable it.

**Comment by znarf** [comment]
- A) Contributions are not supported across fiscal hosts. Discussed in: https://github.com/opencollective/opencollective/issues/3190 or https://github.com/opencollective/opencollective/issues/5100
- B) Expenses across fiscal hosts are supported but there a few prerequisites. 1) We need to put the Payer host on a trusted list and 2) They need to have suitable payout method configured.

As it's not a bug, the best is to contact support so we have a ticket to track the request.

**Comment by ianconsolata** [comment]
Oh, great! Thanks for linking those issues. Closing as a duplicate now. 

If it's not expected behavior yet, so I don't feel the need to submit a support ticket unless you think it's useful. I don't mind paying for it myself and getting reimbursed.

**Comment by znarf** [comment]
@ianconsolata I think that could be valuable to put the Payer on the trusted list, that would simplify the process.
