### ISSUE TITLE
Add `platformTip` Parameter to Contribution Flow

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6376]
Motivated by the ticket; https://opencollective.freshdesk.com/a/tickets/162482

We currently seem not to have any contribution flow parameter to specify the platform tip amount. Having one seems useful as this way uses have the ability to share the link along with a predefined platform tip. 

For example; https://opencollective.com/foundation/donate?interval=oneTime&amount=20&platformTip=3 should direct the user to the contribution flow with a platform tip of $3 dollars pre-selected. 

Note: I am not sure if we supported this feature before. In the ticket the user claims that we did, however I couldn't find history on this. Any insight is welcome. 😃

**Comment by znarf** [comment]
As discussed here https://github.com/opencollective/opencollective/issues/6252 and in some Slack threads, this is not something we want to support.

It's unfair to the Open Collective platform to be able to disable tips, this is part of our revenue model and help makes the platform sustainable.

**Comment by Betree** [comment]
This parameter was never officially supported and will not be added back. Platform tips are our only source of revenue for collectives that use it, we're not going to shoot ourselves in the foot by providing a way to silently disable them.
Plus, it would be unfair for tech-savy users (enough to customize the URLs and build an embed version) to have different defaults.

We're currently discussing internally about alternative solutions for the embed flow where the default tip can be perceived as a hidden fee - but it won't be that one.

Closing
