### ISSUE TITLE
Change the way we handle personal profiles in contribution flow URL parameters

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6378]
Today, when sharing URLs from the contribution flow, you get a link like:
https://opencollective.com/captainfact_io/donate?amount=20&interval=oneTime&contributeAs=betree

The `contributeAs=betree` part of this link is not helpful since only I can access my personal profile. In practice, it will force contributors to click on the link to pick a different profile so the experience is not broken.

As a way to improve this, we should use a special string to identify the personal profile (e.g. `contributeAs=personal-profile`, or `contributeAs=me`). This will both reduce the unnecessary data we expose through the link, and let users share links were your personal profile is automatically selected.

**Comment by ShreyaPrasad1209** [comment]
Hi @Betree, can I work on this issue?

**Comment by Betree** [comment]
Sure! Let me know if you need anything.

**Comment by ShreyaPrasad1209** [comment]
@Betree I got this URL on clicking the link you shared above and it automatically changed to `contributeAs=shreya-prasad` 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/43600306/222100381-1848c084-aa34-4550-b322-3f5be1a2251b.png">

**Comment by Betree** [comment]
Yes. As per the issue description:

> The `contributeAs=betree` part of this link is not helpful since only I can access my personal profile. In practice, it will force contributors to click on the link to pick a different profile so the experience is not broken.
>
> As a way to improve this, we should use a special string to identify the personal profile (e.g. `contributeAs=personal-profile`, or `contributeAs=me`). This will both reduce the unnecessary data we expose through the link, and let users share links were your personal profile is automatically selected.

**Comment by ShreyaPrasad1209** [comment]
Okay so do you want to hardcode the value of contributeAs?

**Comment by Betree** [comment]
@ShreyaPrasad1209 I'm not sure what you mean by that. We basically want to use an alias (`me` or `personal-profile`) rather than the user slug for the abovementioned reasons.

**Comment by ShreyaPrasad1209** [comment]
@Betree gotcha, I've raised a PR for the same, feel free to take a look  👀

**Comment by ashutosh887** [comment]
I would like to work on this issue

**Comment by Betree** [comment]
@ashutosh887 It's yours!

**Comment by ashutosh887** [comment]
Thanks for assigning @Betree

**Comment by Betree** [comment]
@ashutosh887 Any progress on that one? Do you need some help?
