### ISSUE TITLE
recurring expense lost currency

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6379]
**Describe the bug**
https://opencollective.com/opencollective/expenses/120331

I've had this recurring expense in NZD for a while, but this month for some reason it lost the currency. It should save the currency selection.

<img width="755" alt="Screen Shot 2023-01-28 at 2 59 57 PM" src="https://user-images.githubusercontent.com/5498878/215236320-e8e65ef4-9e86-4db8-a598-8a33765dd68e.png">

**Comment by Betree** [comment]
I tried to reproduce it but couldn't. As per https://github.com/opencollective/opencollective/issues/5206, this can now happen if you change your payout method to something else where the selected currency is not supported (even if you re-select the right payout method afterwards).

**Comment by mkurz** [comment]
Happened to me just now as well: https://opencollective.com/playframework/expenses/121129
I didn't change anything from the last time the expense was drafted, submitted, approved and paid.
Today I had to choose EUR manually...

**Comment by Betree** [comment]
I got it on my own recurring expense today as well; I should be able to fix it from there

**Comment by Betree** [comment]
@mkurz It's possible that the changes we introduced in https://github.com/opencollective/opencollective-frontend/pull/10343 forced you to re-select the currency. Could you share the expense URL?

**Comment by mkurz** [comment]
https://opencollective.com/playframework/expenses/195829 was drafted on 1st of April btw.

**Comment by mkurz** [comment]
I think this probably can help you to track the problem:
Today following two expenses got drafted which both do not have the currency selected:
- https://opencollective.com/playframework/expenses/204953
- https://opencollective.com/playframework/expenses/204922

(I am not posting the private`?key=...` param)
I can keep this drafts untouched for next week so you can fix it? WDYT? Thanks!

<kbd><img width="200" src="https://github.com/opencollective/opencollective/assets/644927/05e11380-a066-4ccf-be37-7ebf0c148951" /></kbd>

**Comment by Betree** [comment]
@mkurz Thank you! I'm going to try and have a look at it this week.

**Comment by Betree** [comment]
Will close the issue once the fix gets deployed

**Comment by Betree** [comment]
@mkurz The issue should be fixed now, thanks for helping troubleshoot!

**Comment by mkurz** [comment]
@Betree Hmm... Now when I click the "Review and Submit" button from the email with the subject "Your recurring expense for Play Framework was drafted" I end up with a

> Unexpected error
> Something went wrong, please refresh or try something else

message.
This happens when having the `?key=...` param in the url.
Without the key I can see the draft but can not edit it... 
E.g.
- https://opencollective.com/playframework/expenses/204922

**Comment by mkurz** [comment]
What I mean is I can access
- https://opencollective.com/playframework/expenses/204922

but in the email there is an `?key=` param which causes the `Unexpected error` now...

**Comment by Betree** [comment]
@mkurz Sorry about that, we pushed the fix in a rush and did not test the draft key path properly. A fix has been deployed.

**Comment by mkurz** [comment]
Thanks Benjamin, it's working now :+1:
