### ISSUE TITLE
Fix currency symbol for VDM Collective

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#638]
Mail form Jean Paul.

> On the Host : https://opencollective.com/vdmentransition  I see 200$US given  (strange to see $ instead of €) (we could also remove it if it is possible to add directly the money on the specific collectives.

**Comment by piamancini** [comment]
@nicobarretoOC we set the collective in EUR

**Comment by JeanPaulGrange** [comment]
Hi Pia,
You can close the ticket
Thanks

**Comment by piamancini** [comment]
thanks @JeanPaulGrange
