### ISSUE TITLE
Contributors not appearing

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6380]
**Describe the bug**
See https://opencollective.com/happenfilms/projects/food-forest-revisit

The main page shows only one contributor

<img width="671" alt="Screen Shot 2023-01-30 at 2 57 04 PM" src="https://user-images.githubusercontent.com/5498878/215371883-94903a92-74be-4a56-8fb6-b05a26b0b505.png">

But there have been lots more in the past

<img width="1173" alt="Screen Shot 2023-01-30 at 2 56 28 PM" src="https://user-images.githubusercontent.com/5498878/215371909-9269facc-04e8-4561-a143-92668c22113f.png">

This seems to be affecting multiple Projects under this Collective.

**Expected behavior**
The contributors section should show all the contributors

  P2 low frequency, high impact

**Comment by Betree** [comment]
@kewitz It looks like we've deleted all members from events and projects in https://github.com/opencollective/opencollective-api/commit/bcb31277c64e2f5e817a4b68fb648f5ae7645926#diff-7072045407270bdccded264988610f1082de44d630c8ad6cfbb08fb7929c959e, including financial contributors. The `deletedAt` is `2023-01-18 08:40:40.303072 +00:00`.

**Comment by kewitz** [comment]
Done. Sorry about the inconvenience. I had fixed the migration elsewhere but lost the code during rebase/force-pushing.
