### ISSUE TITLE
Change default step for amount arrows in the contribution flow

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6381]
As reported in https://opencollective.slack.com/archives/C0YFZ3MHP/p1674841868530229

> Why are they changing the value in cent steps? I had the impulse to use them quite a few times and expected them to change the price in whole-number-steps or at least fifty-cent. Changing something just a few cents is just rarely necessary, and changing more than that with cent-steps is annoying.

Expected:
- Increase the amount by 0.5 instead of 0.01 when using the arrows
- Make sure it is still possible to manually input any custom amount in the box

![image](https://user-images.githubusercontent.com/1556356/215434351-005c7584-934e-415f-8401-4ad69a1211db.png)

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by kushalnl7** [comment]
Hi @Betree, can I work on this?

**Comment by snitin315** [comment]
Hi @kushalnl7 I have already started working on this one. You can check for other open issues in this repo.

**Comment by Betree** [comment]
As mentioned on Slack:
> Cool, i see somebody has already been working on this. I just want to add that these arrows also are in other places in Open Collective: the page to create new tears fro example^^

It would be great to have a solution that we could easily re-use, maybe a `arrowStep` option on `StyledInputAmount`? The change is not requested to complete the bounty as it comes as a later specification. We can do it as a follow-up.

**Comment by Betree** [comment]
:trophy: This issue has been completed by @snitin315  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
