### ISSUE TITLE
final "ticket.confirmed" webhook no longer being sent for paid orders, "order.processing" sent first instead

### ISSUE THREAD

**Issue by pwolanin** [opencollective/opencollective#6384]
**Describe the bug**

Since about January 20, we have not been receiving the "ticket.confirmed" type webhook for paid ticket orders. We do seem to still receive it for a $0 test ticket.

The last paid one where we received a "ticket.confirmed" was:

```
{"createdAt":"2023-01-19T22:31:24.507Z","id":4899873,"type":"ticket.confirmed","CollectiveId":574860,"data":{"recipient":{"name":"Guest"},"tier":{"id":48608,"name":"General Admission (Early)","amount":3500,"currency":"USD","description":null,"maxQuantity":null,"formattedAmount":"$35.00","formattedAmountWithInterval":"$35.00"},"order":{"id":615291,"totalAmount":3500,"currency":"USD","description":"Registration to DrupalCamp NJ 2023 (General Admission (Early))","interval":null,"createdAt":"2023-01-19T22:31:18.151Z","quantity":1,"formattedAmount":"$35.00","formattedAmountWithInterval":"$35.00"}}}
```

For that ticket we received 3 webhooks:

```
"id":4899871,"type":"collective.transaction.created"
"id":4899872,"type":"collective.member.created"
"id":4899873,"type":"ticket.confirmed"
```

For a more recent ticket we get 3 webhooks payloads but 1 of the 3 are of a different type, and none include the tags from the order:

```
"id":4939380,"type":"order.processing"
"id":4939384,"type":"collective.transaction.created"
"id":4939385,"type":"collective.member.created"
```

**Expected behavior**

When a ticket purchase goes through we expect to receive a "ticket.confirmed" webhook.  This type is still in the drop-down selector for webhooks e.g. on our event settings at: https://opencollective.com/drupalnj/events/drupalcamp-nj-2023-3943c0c2/admin/webhooks

In these recent PRs, the ticket.confirmed webhook type was enhanced to include tags:
https://github.com/opencollective/opencollective-api/pull/8450
https://github.com/opencollective/opencollective-api/pull/8457

**Additional context**

Looking at the commit log, there don't seem to be many related changes in that time frame. A couple possible suspects are:

```
commit f724b4caec8ebab01026f5f171a8a56a9e3222b9
Author: Henrique <hdiniz@users.noreply.github.com>
Date:   Mon Jan 23 15:04:11 2023 -0300

    Handle payment method before creating transactions (#8449)
```

and

```
commit cb0af05e83cff42066096f1ed9efe6a43d5517e4
Author: Henrique <hdiniz@users.noreply.github.com>
Date:   Mon Jan 23 08:35:18 2023 -0300

    Match or create payment method on payment intent success (#8429)
```

Those changes affected Stripe payments webhook, and I think most or all of our paid tickets are coming as credit cards via Stripe.

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
cc @hdiniz, could any of these changes have impacted the type of webhook events we generate?

**Comment by hdiniz** [comment]
Thanks for the bug report @pwolanin! I believe this could be related with the the recent stripe payment element integration which modified the credit card flow, I will check.

**Comment by pwolanin** [comment]
Thanks @hdiniz !
