### ISSUE TITLE
Value "BACS_DEBIT" does not exist in "PaymentMethodType" enum.

### ISSUE THREAD

**Issue by wursterje** [opencollective/opencollective#6386]
I would like to support a project but sadly I get this error:

![image](https://user-images.githubusercontent.com/14123012/216311377-0459f43d-391b-43ca-82d3-8ea34de2d8ec.png)

URL: https://opencollective.com/api/graphql/v2

Request:

`{"operationName":"ContributionFlowPaymentMethods","variables":{"slug":"***********"},"query":"query ContributionFlowPaymentMethods($slug: String) {\n  account(slug: $slug) {\n    id\n    paymentMethods(\n      type: [CREDITCARD, US_BANK_ACCOUNT, SEPA_DEBIT, BACS_DEBIT, GIFTCARD, PREPAID, COLLECTIVE]\n      includeExpired: true\n    ) {\n      id\n      name\n      data\n      service\n      type\n      expiryDate\n      providerType\n      sourcePaymentMethod {\n        id\n        name\n        data\n        service\n        type\n        expiryDate\n        providerType\n        balance {\n          currency\n          __typename\n        }\n        limitedToHosts {\n          id\n          legacyId\n          slug\n          __typename\n        }\n        __typename\n      }\n      balance {\n        valueInCents\n        currency\n        __typename\n      }\n      account {\n        id\n        slug\n        type\n        name\n        imageUrl\n        __typename\n      }\n      limitedToHosts {\n        id\n        legacyId\n        slug\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}"}
`
Response:

```
{
 "errors": [
 {
 "message": "Value \"BACS_DEBIT\" does not exist in \"PaymentMethodType\" enum. Did you mean the enum value \"SEPA_DEBIT\" or \"sepa_debit\"?",
 "locations": [
 {
 "line": 5,
 "column": 55
 }
 ],
 "extensions": {
 "code": "GRAPHQL_VALIDATION_FAILED"
 }
 }
 ]
}
```

**Comment by hdiniz** [comment]
Hi @wursterje thank you for reporting this. We are working on it.

**Comment by hdiniz** [comment]
You should be able to contribute now @wursterje. Sorry for the inconvenience!

**Comment by wursterje** [comment]
@hdiniz Nice, thanks! Yes, I can confirm the error is fixed.
