### ISSUE TITLE
Feedback: confusion when visualizing Host Collectives/ Sub Collectives

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#639]
Mail from Jean Paul:

> There is still a bit of confusion on one of the collective hosted.
> 
> As displayed in the screencopy below : 
> The host collective is : https://opencollective.com/vdmentransition 
> it hosts 3 collectives : 
> REconomy, 
> "Val-de-Marne en Transition"
> and a 3rd one that should not exist called VDM Host Collective with the address :  https://opencollective.com/vdmcollective.
> 
> Why do we have this 3rd Collective ? could we remove it or it is a needed copy of the host collective ?

![2017-11-08 20_45_00-val-de-marne en transition - open collective](https://user-images.githubusercontent.com/30665166/32578239-17b16ac2-c4a2-11e7-92c5-aa39b9884150.png)

**Comment by JeanPaulGrange** [comment]
Hello,
I wanted to know if I could remove the central collective on the screenshot "VDM Host Collective" that seems no a real collective but a wrongly created collective. Can I do it ?
Regards,

**Comment by piamancini** [comment]
@JeanPaulGrange yes, I can do that for you. It's legacy from the previous version. 
done
