### ISSUE TITLE
Support machine generated data/metadata on the API

### ISSUE THREAD

**Issue by iamronen** [opencollective/opencollective#6395]
## User story 

When custom applications are created using the platform API they can (and likely will) rely on additional data that they hold outside the platform. That additional data can create context that is not available on the platform. If they get creative and use encoded data such as hashes to store information on the platform, that information will look like noise, error, garbage or spam on the platform (where the additional context does not exist).

Example1: [Borderlands use of expense tags](https://opencollective.com/borderland/projects/the-borderland-2022/transactions)
![image](https://user-images.githubusercontent.com/8337819/217239831-5b7d3aa0-2c37-434d-a291-d1803410f7a2.png)

Example2: [ongoing custom application exploration going at Art.Coop](https://opencollective.com/testing789/projects)
![image](https://user-images.githubusercontent.com/8337819/217239993-051e6575-52c9-4de3-8305-bddb5a809e22.png)

This can have negative impact:

- On viewers or contributors browsing the platform.
- On fiscal host admins when they need to interact with this information (be it for authorizing/paying expenses or end of year accounting).
- This can be perceived as a security breach by lay users.

## Best solution for this problem
This is a potentially systemic issue (that is already manifesting) that deserves some attention.

P4 low frequency, low impact

**Comment by Betree** [comment]
Doesn't seem like a problem with the API itself but rather an invalid usage of the different fields

**Comment by iamronen** [comment]
Definitely not a problem with the API, on the contrary the API is probably being used creatively in such cases.
The problem is that the outcome as that information appears on the platform directly it can be experienced as confusing and suspicious. The problem I am trying to point to is that it has the potential to reflect negatively on the platform.

Imagine a funder looking at the Discover experience and then arriving at a collective to find projects and expenses that look like that. What does that signal to them?

**Comment by znarf** [comment]
For projects, it's just a bad idea to use the title as an identifier. I'm not even sure this achieve a purpose in the example, maybe the person just wanted to check project creation? They should have done that on the staging API, when in production this could be seen as an abuse of the platform and lead to deletion of the account.

For cryptic tags, I definitely see the use case for it. The proper solution would be "machine tags" (that are not exposed directly in the interface) and I remember Hugi proposed something like this. I unfortunately can not find the issue right now. Flickr had support for this back in the days https://www.flickr.com/groups/api/discuss/72157594497877875/ and I'm not sure what would be a modern version of it.

**Comment by znarf** [comment]
Btw, I find the current title of the issue a bit cryptic itself and misleading. Can we figure something better?

**Comment by iamronen** [comment]
I'm open to suggestions to changing the title :)

I think this goes (potentially) beyond tags. If I remember correctly Hugi raised this on the discussion threads we used for prioritization and I believe he asked for enabling metadata on tags. 
 
If we are truly building this out as a platform then we are inviting people to use it in ways we can't imagine (which is kind of the point). We become a back-end to their front-end. They (and their users) may never interact with the platform directly. They only need to abide by the logic rules that are embedded in the API.

**Comment by znarf** [comment]
This is not something that can be prevented at a technical level. What is a valid title? A valid description? A valid tag?

The only solution I see are:
- Make sure to provide developers a way to embed metadata so they don't have to abuse the system. We can create an issue for this.
- Create community guidelines to prevent people to have profiles that look like junk. Then delete or hide profiles that are not respecting those guidelines.

**Comment by Betree** [comment]
Closing in favor of https://github.com/opencollective/opencollective/issues/6451. Feel free to re-open if it doesn't capture the intent of this issue.
