### ISSUE TITLE
Assist with image change and figure out credentials OpenEMR Collective

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#640]
Matthew has this very cool project (https://opencollective.com/OpenEMR) he created an open collective using Github account and he is trying to figure out what his credentials are. 

Also he requested if we could change the logo of his collective because he just got one of his first backers, so that's **his No. 1 priority: change logo.**

Here it is:
![tys5aqpo_400x400](https://user-images.githubusercontent.com/30665166/32589602-0ea1e536-c4db-11e7-83ee-0868bfca782a.jpg)

**Comment by piamancini** [comment]
done
