### ISSUE TITLE
Error while paying with crypto: value "4586059860" is out of range for type integer 

### ISSUE THREAD

**Issue by tonycorporated** [opencollective/opencollective#6401]
**Describe the bug**
Error while paying with crypto: value "4586059860" is out of range for type integer 

**To Reproduce**
1. Go to https://opencollective.com/monitorcontrol
2. Click on Crypto Contribution
3. Proceed with any amount, either personal or org

**Screenshots**
<img width="793" alt="image" src="https://user-images.githubusercontent.com/73071319/217700125-b65ceb0a-c5c4-45b9-b6b4-5591d6ded3b0.png">

**Comment by Betree** [comment]
@SudharakaP I can reproduce this one. The full error message is:

![image](https://user-images.githubusercontent.com/1556356/217750379-1a2a0066-3ce3-48b7-9ffb-5328bfdb93c2.png)

Corresponding sentry issue: https://open-collective.sentry.io/issues/3301058358/.

I suppose it's happening around [that place](https://github.com/opencollective/opencollective-api/blob/ea111cf2b084df1f1a8f973d05ac008021a6ad11/server/paymentProviders/thegivingblock/index.js#L153), maybe The Giving Block returns a broken fx rate?
