### ISSUE TITLE
Naming conflict between models and GraphQL types

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6403]
When working on GraphQL types, we often end up in a situation where we have naming conflicts between the GraphQL types and the models. An example to illustrate:

`server/graphql/v2/mutation/TierMutations.ts`

```es6
import Tier from '../../../models/Tier';
import Tier from '../object/Tier'; // Error: Tier is already defined

const tierMutations {
  createTier: {
    type: new GraphQLNonNull(Tier),
    resolve: (args) => Tier.create(args);
  }
}
```

The way we usually work around this issue is by aliasing one of the two variables:

```es6
// Aliasing the model
import { Tier as TierModel } from '../../../models/Tier';
import Tier from '../object/Tier';

// Or the GraphQL import
import Tier from '../../../models/Tier';
import { Tier as GraphQLTier } from '../object/Tier';
```

This practice, however:
- Is another thing that you need to think about when working on GraphQL operations
- Is not consistent across files
- Because of the above, is potentially error-prone

# Proposed solution

Standardize all our exported GraphQL objects with the `GraphQL` prefix:
- `GraphQLTier`
- `GraphQLExpense`
- `GraphQLPaymentMethod`
- ...etc

I tend to prefer this approach because it is consistent with all the other GraphQL types that are imported in these files: `GraphQLString`, `GraphQLBoolean`, `GraphQLInt`, etc.

To make it clear: I'm only proposing the rename the exported variable, not the type in GraphQL itself:

```diff
- export const Tier = new GraphQLObjectType({
+ export const GraphQLTier = new GraphQLObjectType({
  name: 'Tier',
  description: 'Tier model',
```

**Comment by znarf** [comment]
A bit verbose but make sense.
