### ISSUE TITLE
Manually Applying for OSC `Bad Credentials` Error

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6408]
Initially reported at https://opencollective.freshdesk.com/a/tickets/163876. 

Sometimes when a user tries to manually enter their information and apply for OSC, they get the "Bad Credentials" error message. As shown below; 

[bad-credentials.webm](https://user-images.githubusercontent.com/12435965/217978475-45e0ece3-49c6-40bd-9974-6ab4282afc3f.webm)

The reason for this is that we seem to be trying to use the GitHub token that we have for the user (if there's one) from the `ConnectedAccounts` table in order to validate the GitHub url for the repository that the user entered. 

https://github.com/opencollective/opencollective-api/blob/9714e39122afbf8111989f5506a256204b56eb47/server/graphql/v2/mutation/CreateCollectiveMutation.js#L108-L125. 

However the `token` in the `ConnectedAccounts` for GitHub could be outdated and here we do not try to "refresh" the token and simply throw the "Bad Credentials" error. 

I am also curious as to why we do this validation during the manual verification phase. After all, manual verification could (or should) be just manually verified by the OSC admins? 

cc: @znarf

**Comment by znarf** [comment]
What tells you the application is manual? Approval is automated, no?

I suggest to fall back to manual approval if there is any error with the automated approval, just catch the error and move forward.

**Comment by znarf** [comment]
Instead of `throw new ValidationFailed(error.message);`

Log the error and `shouldAutomaticallyApprove = false`
