### ISSUE TITLE
Set up an admin interface using Forest

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#641]
First priority is to enable @nicobarretoOC to have access to the database.
We need to hide
- `User`
  - `email`
  - `paypalEmail`
- `PaymentMethods`:
  - `name`
  - `token`
  - `customerId`
  - `data`
- `ConnectedAccounts`:
  - `username`
  - `clientId`
  - `token`
  - `data`
- `Transactions`:
  - `data`
- `Subscriptions`
  - `stripeSubscriptionId`
- `Activities` (entire table)

And we need to be able to give read only access to the rest of the tables and only allow manipulation of the data via "smart actions".

The first one we can start with is merging two users:

input: 
```
MERGE_USER_COLLECTIVEID=23121 (e.g. /xdamman1)
MERGE_WITH_COLLECTIVEID=23120 (e.g. /xdamman)
```
sql:
```sql
MERGE_USERID=SELECT id FROM "Users" WHERE  "CollectiveId"= $MERGE_USER_COLLECTIVEID;
MERGE_WITH_USERID=SELECT id FROM "Users" WHERE  "CollectiveId"= $MERGE_WITH_COLLECTIVEID;
UPDATE "Users" SET "deletedAt" = NOW() WHERE "CollectiveId"= $MERGE_USER_COLLECTIVEID;
UPDATE "Collectives" SET "deletedAt" = NOW() WHERE "id"= $MERGE_USER_COLLECTIVEID;
UPDATE "Members" SET "MemberCollectiveId"=$MERGE_WITH_COLLECTIVEID, "CreatedByUserId"=$MERGE_WITH_USERID WHERE "MemberCollectiveId"=$MERGE_USER_COLLECTIVEID;
UPDATE "Orders" SET "FromCollectiveId"=$MERGE_WITH_COLLECTIVEID, "CreatedByUserId"=$MERGE_WITH_USERID WHERE "FromCollectiveId"=$MERGE_USER_COLLECTIVEID;
UPDATE "Transactions" SET "FromCollectiveId"=$MERGE_WITH_COLLECTIVEID WHERE "FromCollectiveId"=$MERGE_USER_COLLECTIVEID;
UPDATE "Expenses" SET "UserId"=$MERGE_WITH_USERID WHERE "UserId"=$MERGE_USERID
UPDATE "ConnectedAccounts" SET "CollectiveId"=$MERGE_WITH_COLLECTIVEID WHERE "CollectiveId"= $MERGE_USER_COLLECTIVEID
UPDATE "PaymentMethods" SET "CollectiveId"=$MERGE_WITH_COLLECTIVEID WHERE "CollectiveId"= $MERGE_USER_COLLECTIVEID
```
Even better if we could reuse the sequelize models for this instead of raw queries, e.g.
```
models.ConnectedAccounts.update({ CollectiveId: NewCollectiveId}, { where: { CollectiveId: OldUserCollectiveId });
```

The second one is creating an organization which would solve #503:

input:
```
adminUserCollectiveId=2321
adminUserName="Jean Bateau"
organizationName="ACME"
organizationWebsite="https://acme.com"
```

```javascript
const org = await models.Collective.update({
type: "ORGANIZATION",
name: organizationName,
website: organizationWebsite,
data: null
}, { where: { id: adminUserCollectiveId })
const userCollective = await models.Collective.create({
name: adminUserName
});
const user = await models.User.findOne({ where: { CollectiveId: adminUserCollectiveId } });
user.CollectiveId = userCollective.id;
user.save();
org.addUserWithRole(user, 'ADMIN', { CreatedByUserId: $LoggedInUserInAdminInterface });

```

**Comment by xdamman** [comment]
@asood123 please review this when you can

**Comment by xdamman** [comment]
ping @seyz @louisteenbrink

**Comment by SeyZ** [comment]
Thanks @xdamman for the reactivity. Would love to help here.
@asood123 I'll let you review ;)

**Comment by asood123** [comment]
Looks good. We'll need to tweak queries slightly - we can do that after smart actions are setup.

**Comment by PeterDavidCarter** [comment]
What's Forest? Yet another auth library?

**Comment by xdamman** [comment]
@SeyZ let me know if you need any help figuring out how/where to do the PR (https://github.com/opencollective/api)

@PeterDavidCarter https://www.forestadmin.com

**Comment by asood123** [comment]
@SeyZ I'm not sure if this is within your scope. Our ideal admin interface would be a search box - someone can type in a name or an email and it should pull up that User -> Collective -> Orders -> Transactions, etc.

Second to that, we would like to make sure that there is no way to export data out of Forest (especially in bulk). Is that the case currently?

**Comment by SeyZ** [comment]
Hey @asood123 

We work very hard to provide the most efficient UX to run you admin tasks. So yes, you can search for a user by name or email et access to the collective, orders, transactions, etc. You can also create a "Summary View" to aggregate all things in one view, instead of navigating to multiple view.

At the moment, it's not possible to disable the export CSV mode. For my curiosity, is it related to a performance issue or more about security? Would love to know the reasons. Of course, it's a very easy feature for us to implement, let me see with the team an ETA.

Thanks!

**Comment by asood123** [comment]
Disabling CSV is more about security than perf. We don't want anyone to be able to export whole tables including emails for example. 

At some point, we would want to point Forest to a follower database so someone using it doesn't bombard the production db and that should take care of perf issues.

Glad to hear about search. How soon do you think you will have something ready for us to try based on the first post in this thread?

**Comment by SeyZ** [comment]
Hey @asood123 - make sense for the "export csv" option.

I've bootstraped the install on a `forestadmin` branch but I don't have the access to push to this repo. I'd love to make a PR ;-) cc @xdamman @asood123

**Comment by asood123** [comment]
@SeyZ You should be to send a PR to us with that branch and we can merge it

**Comment by SeyZ** [comment]
@asood123 true :-) https://github.com/opencollective/opencollective-api/pull/1019

**Comment by piamancini** [comment]
@znarf fyi closing this since your forest set up is on a separate track.
