### ISSUE TITLE
Order Summary Screen is Shown within Contribution flow on Page Refresh

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6412]
It seems that in the contribution flow, when the page is refreshed the `Summary` screen is always shown even if it doesn't provide any useful information. 

[summary-screen.webm](https://user-images.githubusercontent.com/12435965/218206253-9b142317-7082-4f63-b420-45a192bafc8f.webm)

@Betree : I believe the summary screen should only be shown when there's tax information?

**Comment by Betree** [comment]
That's by design, if you link directly to a step further than "details" in the contribution flow the we show the summary, to make sure contributors have a chance to review the amounts.

**Comment by SudharakaP** [comment]
Ah, that makes sense now. Will close this issue.
