### ISSUE TITLE
Command "npm run build:e2e" doesn't work for Windows

### ISSUE THREAD

**Issue by NikitaKorevo** [opencollective/opencollective#6413]
**Describe the bug**
Command `npm run build:e2e` doesn't work for Windows

**To Reproduce**
1. Go to 'opencollective-frontend' folder
2. run command `npm run build:e2e`
4.  In files `build_next.sh` and `build_server.sh` see error  `Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.`

**Expected behavior**
Expect build in `dist` folder
**Screenshots**

![error](https://user-images.githubusercontent.com/48645737/218315645-996352af-2060-48ff-af21-b5d8343739f0.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 19044.2486
 - Browser Google Chrome
 - Version 110.0.5481.78

**Additional context**

Related https://github.com/opencollective/opencollective/issues/5836

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
That's not really an issue since this command is only used by our CI, which runs on Linux. We can eventually merge if there's an easy fix that doesn't break our current setup.
