### ISSUE TITLE
Establish a unique collective profile experience

### ISSUE THREAD

**Issue by iamronen** [opencollective/opencollective#6415]
## User story 
> I am a potential contributor and I am browsing the platform and all the profile pages look the same to me. They seem to have a similar structure, I recognize repeating parts of the profile which sometimes make sense, sometimes not so much. I would like to be able to effortlessly discern when I am looking at a collective profile.

> I am a contributor and I am discovering that within collectives there are projects and events. It is difficult for me to tell the difference between a collective profile page and project and events profile pages. Also, when I am looking at an event or project profile page, it is not clear to me how it is related to the collective to which it belongs.

> I am discovering a collective by browsing its profile and I have decided I want to contribute to it. How do I contribute?

## Best solution for this problem
This is a proposal to begin development work (investing engineering effort) on a path to redesigning collective profile pages. This effort is:

1. A **sensitive effort** as it involves changing the most established and core platform user experience.
2. It will **span numerous development cycles**.
3. It will be developed alongside the platform to allow for **rapid iteration, exploring design potentials and user testing**.
4. This first iteration is **not intended to be released** but to implement ,test, demonstrate and collect feedback on preliminary designs.

The primary objectives of this pitch are:

1. To  clearly **discern** between the collective profile and other public profiles. This will be achieved by:
    -  Establishing a new UX pattern that is unique to collective profiles.
    - NOT making changes to other profile pages (and when we do get around to changing them, it will be a priority to maintain this differentiation by maintaining clearly distinguishable UX patterns).
2. To clarify the relationship between **a collective and its projects and events**. Project and Events currently have profile pages which also look like any other profile and seem disassociated from their collectives.
3. To create the foundations within the collective profile **to improve the contribution user experience**.

## MVP
A UX pattern that is:

1. Uniquely tailored to house the public face of collectives.
2. Clearly distinguishable from other UX patterns on the platform so that when you see it you know you are looking at a collective (and when you see anything else, you know it isn’t a collective).
3. Manifests the core collective experience on the platform:
    -  Story: a collective is a group of people working towards shared goals.
    -  Budget: the collective budget is fully transparent.
    -  Contribute: ways in which you can contribute to it.
    -  Connect: ways for you to connect to and stay in touch with the collective.

## Traps to Avoid:

The initial research into this redesign is converging on a collective profile page that has an internal navigation menu that divides the profile into numerous sections (this is different from the current single-long-page layout). It is inevitable that this redesign will therefore encounter:

1. Questions about how contents should be divided,
2. Questions about the contents within each part of the collective profile.

The priority for this effort is to focus on high-level choices that shape the overall experience of the collective profile.

## Boundaries

There is much work to do on refining and redesigning the content containers within these pages but this is not within the scope of this effort. The priority here is to lay the foundations to making many more improvements.

P1 high frequency, high impact

**Comment by Memo-Es** [comment]
### Week 2 goals:
 - [ ] Lay down testing steps
 - [ ] Finish design proposal to be tested

**Comment by toomuchinformation** [comment]
Test #1
- [x] Prepare prototype
- [x] Share test
- [x] Iteration

Test #2
- [ ] Prepare prototype
- [ ] Share test
- [ ] Iteration

**Comment by BenJam** [comment]
- [ ] review with eng for performance problems/improvements

**Comment by Memo-Es** [comment]
## Week 6 update

 - [ ] Publish the pitch for the next stage of the project 

cc @toomuchinformation

**Comment by Mayaleeeee** [comment]
Hi @Memo-Es is anyone currently working on this?

**Comment by BenJam** [comment]
- [ ] couple of follow up screen-os for pitch then ready for prioritisation

**Comment by BenJam** [comment]
## 2023 Cycle 3

FYI this project is prioritised for 'extra capacity' this cycle, the goal being to build the interface in [the pitch](https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Currently_suFhs#Pitches-for-next-cycle_turuK/r29&view=modal) in order to test it with some users.

**Comment by BenJam** [comment]
@iamronen do you want this or #5680 to be the canonical issue for this work?

**Comment by BenJam** [comment]
closing in favour os #5680
