### ISSUE TITLE
Delete accounts refinerycms

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#642]
Brice mail:

> Hi! 
> 
> I would like to delete my newly created account on your platform with the email :
> 
> contact@br(...) and the associated open source project : refinerycms
> 
> Thanks

**Comment by piamancini** [comment]
done.

**Comment by bricesanchez** [comment]
Could you please delete all the nominative informations in the issue (email and project)? 

BTW, I have never been warned that my communications could be made public.

**Comment by piamancini** [comment]
hi @bricesanchez! Thank you for brining this up. I've deleted the info. 
We'll be more careful.
