### ISSUE TITLE
Collective Admins can pay invoice without having to involve invoicer/third party

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6426]
## Who is your user?
Collective Admin 

## What are they trying to achieve?
_When paying an external invoice, I want to process this invoice without the need to invite the invoicer/supplier to submit the invoice/interact with Open Collective, so I can pay the invoice with as little barriers_

## How are they currently doing this?
Currently the collective admin has to use the invite a third party to submit an expense feature. Fill in as much information as they hold and then the invoicer/supplier needs to approve and submit this invoice and create an Open Collective account. 

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by alanna** [comment]
#5894

**Comment by shannondwray** [comment]
Duplicate of #5894
