### ISSUE TITLE
Unable to login after clicking email link

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#643]
Message from Etienne:

> Hei Team!
> I tried to log into the host collective but to no avail.
> See what happens on the screenshots below
> <img width="600" alt="capture1" src="https://user-images.githubusercontent.com/30665166/32622072-61d66a76-c547-11e7-9fda-66a724833e4e.PNG">
> 
> <img width="553" alt="capture2" src="https://user-images.githubusercontent.com/30665166/32622096-78adfef8-c547-11e7-951c-a3f3f532eddc.PNG">
> 
> <img width="432" alt="capture3" src="https://user-images.githubusercontent.com/30665166/32622106-7e3ad42c-c547-11e7-822d-18cecc13f0cc.PNG">
> 
> when I click on the One click login, I end up in the same position as initially
> <img width="600" alt="capture1" src="https://user-images.githubusercontent.com/30665166/32622113-833b646e-c547-11e7-9a3a-5f207172aff3.PNG">
> 
> Thanks in advance for your help!
> Etienne
> 

------
Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by PeterDavidCarter** [comment]
What do you want help on? What steps have you taken to isolate the bug thus far?

**Comment by piamancini** [comment]
fixed
