### ISSUE TITLE
Alphabetise filter menu items

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6436]
These seem to be in a random order and it makes it hard to find the one you're looking for.

<img width="234" alt="Screen Shot 2023-02-20 at 3 20 46 PM" src="https://user-images.githubusercontent.com/5498878/219994975-e586bfc3-cb62-42e3-9a87-4637171c4281.png">
<img width="251" alt="Screen Shot 2023-02-20 at 3 20 37 PM" src="https://user-images.githubusercontent.com/5498878/219994986-f0a75617-bd8a-408d-86c2-75a6409b96dd.png">
<img width="243" alt="Screen Shot 2023-02-20 at 3 20 29 PM" src="https://user-images.githubusercontent.com/5498878/219994990-4771f8e7-8c65-4e16-9931-e6bcae26dbeb.png">

**Comment by Betree** [comment]
Adding a bounty to resolve the issue for the following components:
- `components/expenses/filters/ExpensesPayoutTypeFilter.js`
- `components/expenses/filters/ExpensesStatusFilter.js`
- `components/expenses/filters/ExpensesTypeFilter.js`
- `components/transactions/filters/TransactionsPaymentMethodTypeFilter.js`
- `components/orders/OrderStatusFilter.js`

The sorting must be done on the internationalized strings, i.e.:

```es6
const options = values.map(value => ({ value, label: intl.formatMessage(messages[value]) });
const sortedOptions = sortBy(options, 'label');
```

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by Betree** [comment]
:trophy: This issue has been completed by @ersachin3112  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
