### ISSUE TITLE
Improve the onboarding flow for a user creating a collective and selecting a fiscal host

### ISSUE THREAD

**Issue by iamronen** [opencollective/opencollective#6440]
## User story 

> I  would like to create a new collective on the platform, but I am not quite sure what that means and what are the implications of doing this, especially when it comes to handling money. 

## Best solution for this problem
A step-by-step onboarding experience that guides me through decisions I need to make on that path to creating a new collective. The critical path for this user experience:

1. I first join the platform as an individual user.
2. I am presented with the possibility of creating a collective.
3. I create a collective profile that I can flesh out.
4. When I would like to be able to receive funds I am given information about fiscal hosting and how to choose a fiscal host that is suitable for my collective.
5. I can then apply to a fiscal host (or become an independent collective) so that I can start receiving contributions and submitting expenses. 

## MVP
The initial drivers for this effort were:
1. Remove the current junction where a user is prompted to choose between an "open-source" or "community" collective (and address this later on in the critical path).
2. Clearly surface 1st party hosts.
3. Downplay  the option to become an independent collective.

During the shaping of this pitch the scope was expanded to include a low-cost change that would address additional high-value usecases that may be driving a user to join the platform:

1. Create a collective remains the critical path (and priority for this effort).
2. Contribute to a collective (which leads to some kind of search/discover experience).
3. Submit an expense in which it is assumed that the user knows to which collective they wish to submit the expense (and is supported in finding the collective and being directed to the submit-expense capability.
4. Create an organization (which leads to the existing create organization capability).

The following demo from @toomuchinformation captures the scope of work intended for this effort:
https://www.loom.com/share/0ca0a9328b7a4e3c8c7e18ed3329ed37

## Boundaries

The shaping work that went into this pitch clearly indicated that there is a lot of potential for scope-creep in this project. There is a lot more that can be done to improve the onboarding experience. We anticipate that #6385 will create favorable conditions for moving forward with this work.  

The objective for this effort should stay focused on the critical path for creating a collective and the secondary paths which redirect a user to other places on the platform.

The user-interfaces that are instantiated in this effort lack clear placement on the platform. For any of these screens one can ask: "Where I am? How did I get here? How can I get back here if I stop now and resume later?" to which we do not provide clear answers. When the workplace is established, we will be able to direct the user to the individual workplace where these options and potentially other resources can be made available. The personal workplace (instantly available upon creating a personal user account) will be the place to introduce the user to the potentials of the platform and guide them in their first steps.

We therefore, anticipate that the work we do in this effort will be later integrated into the workplace experience. 

Priority: P1 high frequency, high impact

**Comment by iamronen** [comment]
Summary of shared understandings from kickoff meeting:

1. This single issue actually represents two parallel efforts:
      - The first is to implement onboarding improvements based on the critical path of creating a collective as outlined in the pitch above.
      - The second is to continue to iterate in research and design on further potential improvements to the onboarding experience. This effort will also lean into the "workspace" experience #6385 that has also been prioritized for this cycle.
2. We are focusing on the  critical path involved in creating a collective. Any additional improvements (for alternative onboarding scenarios) are contingent on both availability of engineering resources and clarity about desired outcomes we want to achieve.
3. We are starting work with the "find a fiscal host" screen (and wiring it into "apply to fiscal hosts" screens) because:
     - it is currently weak (both in terms of function and performance)
     - it is clearly shaped and understood 
     - it is the most expensive part of this effort
     - it can be easily wired into the existing parts of the collective-path onboarding experience.
4. We will continue (based on time and availability) with rewiring the onboarding experience based on this sequence:
     - Create user account
     - Create a collective (minimal information without having to decide "open-source or community").
     - Add admins (there was a conversation about possibly removing this step).
     - Leading to a new collective profile from which the new "find a fiscal host" screen can be launched.

**Comment by Memo-Es** [comment]
### Week 3 goals:
 - [ ] Design for the page to find a host
 - [ ] Ideal UX review

**Comment by Memo-Es** [comment]
Impressions from the firs implementation round:
https://www.loom.com/share/85acb08295494bd8ad2d0353c81c2496
@hdiniz @aminakazi @Betree @iamronen

**Comment by Memo-Es** [comment]
[Onboarding flow MVP](https://www.loom.com/share/976a6fcb458f4e489923f9afe37c0afd)

@hdiniz @aminakazi @Betree @iamronen

**Comment by iamronen** [comment]
@Memo-Es Yes, I feel that the "narrowing" down is going to be more usable given:
1. The current "menu of fiscal hosts" 
2. and the still unresolved questions around what collective admins know and need in order to approach the question of how to find and select a fiscal host.

I feel this design as an improvement over what we have, but we still have a way to go in understanding user needs and addressing them well.

In the last part of the demo you showed a "fiscal host services" filter and I think this underestimates the challenge in creating a meaningful offering that enables:
1. Fiscal hosts to announce services
2. Collective admins to understand what it possible and what they need 
3. and finally the option to find fiscal hosts that can offer what they need 

[related assessment](https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/All-Assessments_suLr3#Assessments_tuJZG/r82&view=full).

**Comment by Memo-Es** [comment]
## Update week 6

 - [ ] Review the latest version of the "Join a Fiscal Host" page
 - [ ] Connect the latest version with the version in production
 - [ ] Leave a set of next steps based on the latest UX review
 
 cc @hdiniz

**Comment by BenJam** [comment]
## 2023 Cycle 3 

Just a quick not to say that we're moving back to a more design-led project for the next cycle, [from the pitch](https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Currently_suFhs#Pitches-for-next-cycle_turuK/r40&view=modal):

> We want to [research](https://coda.io/d/Design-Comms-Workspace_d7HqSs5Mv-k/Onboarding-Sandbox-Collectives_su9x3) a new experience embedded in the “Collective onboarding” that helps our users learn by doing what they can do with the platform. A "Sandbox experience" i.e., testing the main features of the platform (Manage contributions, paying expenses, setting-up projects and managing a transparent budget with.

**Comment by iamronen** [comment]
- Tomas putting together a test for internal demo's initially followed by outreach to external users.

**Comment by Memo-Es** [comment]
Leaving here the evidence of the design work for the onboarding on top of #6385 
@BenJam @iamronen @tomsusemihl 
https://www.loom.com/share/720019218ffd453292fe59afc1b01934

**Comment by iamronen** [comment]
@Memo-Es some feedback on your demo 

Before getting into the contents of the demo, back in the beginning of the cycle you began a [research initiative](https://arc.net/e/3B8C4F0A-C238-464D-A16A-C958E6F2ADC1) which I thought was a good start and would like to see continued (my reflections on that research are [here](https://coda.io/d/_dUtO8gb4iID/Onboarding-Discussion_supN_)). I feel that while the changes you are proposing here are generally OK, but we still do not have a clear "bigger picture" of how we want to approach onboarding. I would like to see that research move forward.

The feedback on what you presented was a bit too much to put in writing so a short loom:
https://www.loom.com/share/b2e63bae6550479aae068d04143f24fa

**Comment by BenJam** [comment]
@iamronen @Memo-Es I'm going to fold this into the 'parent' issue #4829
