### ISSUE TITLE
Ability to embed crypto donations on external websites.

### ISSUE THREAD

**Issue by codesardine** [opencollective/opencollective#6441]
## User story 
I have 3 collectives to make it easy to donate different currencies, currently we can embed any collective in our own websites, I have implemented a select for each currency that loads the correct  iframe, however crypto is missing and we have to add a extra button for crypto donation.

## Best solution for this problem
Make the following link embed-able so it may be selected as a currency.
https://opencollective.com/embed/collective_name/donate/crypto

**Comment by Betree** [comment]
About the `wontfix`, see https://opencollective.com/opensource/updates/open-source-collective-is-disabling-contributions-in-cryptocurrencies

**Comment by codesardine** [comment]
I already disabled those, we can close this one.
