### ISSUE TITLE
[Project] Enhance Transactions CSV export

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#6443]
- [x] Deprecate "v1" export completely
  - [x] Check if there is activity?
  - [x] Disable it on frontend asap
- [x] Repair asap CSV export (when filtered by collective) in the Host Report panel
- Make sure that truncation is smarter and better communicated to the user:
https://github.com/opencollective/opencollective/issues/6414
  - [x] When clicking export, the Frontend should do an API query to count transactions and estimate a generation time
    - [x] If it's an important number (e.g.: > 10,000 results, warn the users and communicate a rough estimation)
    - [x] If it's a too important number (e.g.: > 100,000 results, decline the request)
  - [ ] When exporting, we should ensure it's a **direct download** without proxy or unnecessary buffer. That's not the case today when clicking the button, see: `fetchCSVFileFromRESTService`
  - [ ] Any low hanging fruit to improve speed and performance?
- Let user pick columns and entries they want exported:
https://github.com/opencollective/opencollective/issues/6243
  - [ ] Can we add email to the list?

**Comment by BenJam** [comment]
- [x] Amina amending designs to clear up the checkbox option hellness
- [ ] Leo to continue, though at the eng meetup this week

**Comment by BenJam** [comment]
- [ ] released 🎉 
- [ ] need a release post and documentation check

**Comment by Betree** [comment]
Feedback issue: https://github.com/opencollective/opencollective/issues/6693
