### ISSUE TITLE
Reimbursement date in UI not matching what was set

### ISSUE THREAD

**Issue by RichardLitt** [opencollective/opencollective#6452]
**Describe the bug**
When submitting a receipt for a reimbursement, you can specify the date. However, the date shown in the UI after setting this date is one day before the date specified. See https://opencollective.com/open-web-docs/expenses/124314, where 2/16 is the date for the invoice, while I had set it at 2/17. 

https://www.loom.com/share/e317d817f9e74c5098e81cd371fd55af

**To Reproduce**
1. Start the process for submitting a reimbursement.
2. Add in a PDF for the receipt.
3. Set the date manually to some date in the past.
4. Submit the reimbursement.
5. Note the date in the UI. 

**Expected behavior**
Same date. 

**Screenshots**
<img width="440" alt="Screenshot 2023-02-21 at 06 36 10" src="https://user-images.githubusercontent.com/910753/220334650-868be67d-1d7f-47ce-94ae-723e60f39c6b.png">

This was set for 2/17. 

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox.
 - Version: 110.0

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
Looking at the database, the date we've stored is `2023-02-17 00:00:00.000000 +00:00`. So the problem is that we've recorded the date as UTC, but we're displaying it as your locale timezone.

**Comment by RichardLitt** [comment]
Thanks, Ben!
