### ISSUE TITLE
Duplication of content in Fiscal-Hosting Info page

### ISSUE THREAD

**Issue by snowtimeglass** [opencollective/opencollective#6473]
Thank you always, depelopers.

**Describe the bug**

  The contents of the two items below are exactly the same. I am wondering if the second item might originally have another content.
![image](https://user-images.githubusercontent.com/10436072/221338106-7eb05f42-20e4-4010-a867-99306fe2a9a1.png)

**To Reproduce**
1. Go to https://opencollective.com/fiscal-hosting
2. Scroll down to '_Who is fiscal hosting for?_' section 
2. Click on the following button<img src="https://user-images.githubusercontent.com/10436072/221334059-2209038a-5c75-4c9b-8b0c-deefdf97193c.png" width="320px">

**Expected behavior**

The item of "Funder coalitions" shows different content from the previous one.

**Screenshots**

Added above

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser: [Chrome]
 - Version: [110.0.5481.104（Official Build）]

**Additional context**

N/A

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
Thanks for the report, we'll update that based on https://www.figma.com/file/bOkmWlsYxP9qA15z85lzgHQ2/%5BOC.com%5D-01-Marketing-Pages?node-id=4671%3A37879&t=OwV7QXr4bh06aVE0-0

![image](https://user-images.githubusercontent.com/1556356/223067757-b4aac4c7-90b7-46b1-9a7a-a743016ac372.png)

**Comment by snowtimeglass** [comment]
Thank you for the fix!
