### ISSUE TITLE
don't force 2fa for VC receipt upload

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6474]
It's making me do 2fa to upload a VC receipt. This seems excessive. There's no security risk involved in uploading a VC receipt. We should only require 2fa when really needed, or people will be less likely to use it and less likely to complete receipt uploads.

<img width="802" alt="Screen Shot 2023-02-27 at 1 45 07 PM" src="https://user-images.githubusercontent.com/5498878/221448265-8e8ef8b6-7ed9-4b01-94ef-cebd107f28b4.png">

**Comment by znarf** [comment]
Agree! cc @hdiniz @Betree

**Comment by Betree** [comment]
Behind the scenes, this uses the same `editExpense` mutation used to edit the expense details - which is why it's strictly protected. I'm ok with adding an exception when editing a paid virtual card charge, since it's strictly limiting the fields you can actually touch.
