### ISSUE TITLE
Old OC address in TOS

### ISSUE THREAD

**Issue by souravcipher** [opencollective/opencollective#6475]
I think the old address needs to be changed in the docs of the Terms of Services! 

1] https://github.com/opencollective/opencollective-frontend/blob/d2f6e7eaf12df915bf817362b584db9391823ec6/components/static-pages/tos.md
2] https://github.com/opencollective/opencollective/blob/0a8eb5dbf268d7543af2e65da98fff3948a05449/TOS.md

**Comment by znarf** [comment]
Thank you for the report @souravcipher!

It should be updated now.
