### ISSUE TITLE
Add Update create/publish Webhooks Events for Slack/Discord Notifications

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6483]
Motivated by https://github.com/opencollective/opencollective/discussions/6437, I was looking at the web-hook events  for Slack/Discord related to the update create/publish activities. It seems that, 

1) These events don't trigger web-hook events currently. 
2) These events somehow is limited to collectives; although we can have updates for organizations and events and projects as well.

**Comment by Betree** [comment]
Could you clarify whether it's only impacting Slack/Discord (in this case, we know these don't support all event types yet) or all webhook events (in this case, it's a bug)?

**Comment by SudharakaP** [comment]
> Could you clarify whether it's only impacting Slack/Discord (in this case, we know these don't support all event types yet) or all webhook events (in this case, it's a bug)?

Yes that's correct. I've updated the title and description. 👍🏽
