### ISSUE TITLE
More Visibility And Feedback on UI: Storybook + Chromatic Integration

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6487]
I encountered https://www.chromatic.com recently and was reminded of an old discussion we had, https://github.com/opencollective/opencollective/discussions/4319#discussioncomment-807076. 

@Betree : Shall we move ahead with integrating https://www.chromatic.com ? Just wanted to document this on an issue since I feel with more team members now this might be even more useful to catch UI regressions. Plus they seem to have a free Open Source offering. If no objection I can try to do this when I have some spare time. 😸

**Comment by Betree** [comment]
It's an interesting service, last time I checked it seemed too expensive but why not if they have an open-source plan; it could help to catch visual regressions.

**Comment by SudharakaP** [comment]
One thing I am not sure though is if the number of snapshots is enough. The OSS plan gives us 35k snapshots. But we have 201 stories which means each build triggers 201 snapshots. That is around 174 builds. 🤔

**Comment by SudharakaP** [comment]
> One thing I am not sure though is if the number of snapshots is enough. The OSS plan gives us 35k snapshots. But we have 201 stories which means each build triggers 201 snapshots. That is around 174 builds. 🤔 

Okay I've enabled TurboSnap (https://www.chromatic.com/docs/turbosnap#turbosnap) so that hopefully reduces the number of builds. Although I am thinking if we can somehow do better, rather than every push do something like when the user triggers it through a PR comment. 🤔

**Comment by Betree** [comment]
> > One thing I am not sure though is if the number of snapshots is enough. The OSS plan gives us 35k snapshots. But we have 201 stories which means each build triggers 201 snapshots. That is around 174 builds. thinking
> 
> Okay I've enabled TurboSnap (https://www.chromatic.com/docs/turbosnap#turbosnap) so that hopefully reduces the number of builds. Although I am thinking if we can somehow do better, rather than every push do something like when the user triggers it through a PR comment. thinking

Good thing. Our frontend CI probably runs around 50 times a day, so we'd quickly exhaust the quota otherwise.
