### ISSUE TITLE
WWCode Backers can't complete order (CollectiveId cannot be null)

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#651]
Message from Jodi from WWCode:

> Hi OC Team, 
> 
> Please see the below error sent from our **Birmingham Director**.  Please advise.

![image](https://user-images.githubusercontent.com/30665166/32757128-7046ae36-c8a3-11e7-88b1-d5f530829630.png)

**Comment by piamancini** [comment]
@nicobarretoOC can you ask them for the email of the backer?

**Comment by piamancini** [comment]
solved.
