### ISSUE TITLE
Orders not properly cancelled on archiving

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#6510]
Follow up from: https://github.com/opencollective/opencollective-api/pull/8141

Updating `status` to `CANCELLED` is not enough to cancel a recurring contribution.

See: https://github.com/opencollective/opencollective-api/blob/main/server/graphql/v2/mutation/OrderMutations.js#L203

- deactivate subscription
- insert activity

**Comment by znarf** [comment]
`OrderId=555456`

**Comment by Betree** [comment]
As per https://github.com/opencollective/opencollective/issues/6509#issuecomment-1453751075, this is actually expected. It's the role of `cron/hourly/70-cancel-subscriptions-for-cancelled-orders.ts` to then entirely deactivate the subscription and insert the activity.

**Comment by SudharakaP** [comment]
As per the above comment, since we are handling this within the cron job, I think we can safely close this issue. Feel free to let me know if you think otherwise. 🤔
