### ISSUE TITLE
Error message for long filename is confusing

### ISSUE THREAD

**Issue by RichardLitt** [opencollective/opencollective#6511]
**Describe the bug**
When uploading a receipt, there is an error message if the name of the file is too long. However, it isn't clear that that is what is going on. 

<img width="706" alt="Screenshot 2023-03-03 at 10 13 16" src="https://user-images.githubusercontent.com/910753/222756421-753acd3d-a0d9-4103-97d1-a0343ac32f75.png">

**To Reproduce**
1. Try and submit a receipt with a filename over 255 characters long. I don't know how to do this - I couldn't figure out how to make a filename that long on OSX. 

**Expected behavior**

I think the warning should be: "The filename for your receipt is too long. Could you shorten it?"

**Additional context**

Noted here: https://opencollective.com/email-markup-consortium/expenses/125848#new-comment-on-expense

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
In https://github.com/opencollective/opencollective-api/pull/8533 we've increased the max URL length but not the max file length. We'll solve the root issue and add a clearer error message.
