### ISSUE TITLE
country list behind add funds modal

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6512]
**Describe the bug**
The list of countries is hiding behind the add funds modal when adding a new organization

**To Reproduce**
1. Add funds
2. Create org
3. Try to select country

**Expected behavior**

**Screenshots**
![](https://i.gyazo.com/b5963ecc57f8ea03a566b2efb7503d85.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 109

  P2 low frequency, high impact

**Comment by Betree** [comment]
cc @kewitz just in case this rings a bell, since we've been playing with portals / trap-focus and such lately

**Comment by Betree** [comment]
Maybe related with https://github.com/opencollective/opencollective/issues/6522?
