### ISSUE TITLE
"Be the first one to contribute" displayed despite no contributors at all

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6526]
In https://github.com/opencollective/opencollective/issues/5766, we defined that there should be no message if none of the cards have contributors. However, looking at https://opencollective.com/drupal-contribution/projects it seems to be displayed all the time:

![Screenshot 2023-03-07 at 22-13-25 Contribute to Drupal Contribution - Open Collective](https://user-images.githubusercontent.com/1556356/223554171-9219a708-af31-4228-9963-8f8761f0b466.png)

**Comment by snitin315** [comment]
I'll check this.
