### ISSUE TITLE
Custom application email template for OCF

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6528]
OCF would like to convey specific information to newly applied Collectives and therefore we would like a custom template component that replaces `collective.apply.hbs` with `collective.apply.ocf.hbs` and only goes out to applicants to OCF.

Here is the content for it

Subject: Thanks for applying to {{{host.name}}}

```
{{> header}}

<div class="hidden">Your application to OCF is pending</div>

<p>Oh hey {{user.collective.name}} 👋 </p>
<p>Thank you for applying for {{> linkCollective collective=collective}} to be hosted by Open Collective Foundation.</p>
<p>We will get in contact with you if we have any questions. Application reviews can take about 2 weeks. 
In the meantime, <a href="https://docs.opencollective.foundation"> our documentation</a> 
has answers to many common questions.</p>

<p>Feel free to respond to this email if you need to ask us anything.</p>

<p>– {{host.name}}</p>

{{> footer}}

```

**Comment by sreenidhithallam** [comment]
Hi, Could you please assign this issue on my name?

**Comment by sreenidhithallam** [comment]
@Betree I don't have permission to create a branch. could you help me with this.

**Comment by sreenidhithallam** [comment]
@Betree  I don't have permission to create a branch. could you help me with this.

Facing below error
`Permission to opencollective/opencollective-api.git denied to sreenidhithallam`

**Comment by Betree** [comment]
> @Betree  I don't have permission to create a branch. could you help me with this.
> 
> Facing below error
> `Permission to opencollective/opencollective-api.git denied to sreenidhithallam`

You need to fork the project and push on your own fork, then you'll be able to open a pull request against the main repository
