### ISSUE TITLE
Assist A.J. Vargas to remove organization and be a direct Boostnote backer

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#653]
Message from A.J. Vargas, he has some feedback when making a contribution:

> Greetings,
> 
> I recently made a donation to a collective, Boostnote, but apparently I
> made it as an organization, A. J. Vargas (then changed to Spoonhoop). I
> believe I entered my name twice in your account creation/donation page
> in the organization section.
> 
> Making things worse, I removed myself accidentally as a core contributor
> from the created organization. Is there a way to add myself again or
> just remove the organization so that I can be a Boostnote backer
> directly?
> 
> Thanks,
> 
> A. J. Vargas

**Comment by piamancini** [comment]
done
