### ISSUE TITLE
Add 'Contact Us' to the website footer

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#6530]
## Context
As an internet user, if I want to contact the org behind the website, my instinct is to scroll to the footer and look for 'Contact Us'. We don't currently have that. We have the small envelope button which links to this page: https://opencollective.com/contact (which is great), but I almost never use this button on websites because it auto-opens the email client on my computer, and I don't use that either. 

## MVP
![image](https://user-images.githubusercontent.com/64920686/223788542-c292aa79-a9e5-4998-91b4-1e79f88707a8.png)

---> which links to https://opencollective.com/contact

(It could go under 'Community' as well)

**Comment by Betree** [comment]
Note that this icon already links to `/contact`:

![image](https://user-images.githubusercontent.com/1556356/223954259-aae74476-ed9f-4ebe-b52b-1328171e91e2.png)

But text links are always clearer, I'm supporting this issue.
