### ISSUE TITLE
tags scroll broken

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6532]
**Describe the bug**
tags scroll looks odd and overlapping

**To Reproduce**
1. add an expense tag
2. scroll

**Screenshots**
![](https://i.gyazo.com/3454bf49dfa47961817f286e78a5c4a1.gif)

**Desktop (please complete the following information):**
 - OS: MacOC
 - Browser: Chrome
 - Version: 109

**Comment by Betree** [comment]
Duplicate of https://github.com/opencollective/opencollective/issues/6522
