### ISSUE TITLE
Contribution flow amount button disappears on mobile

### ISSUE THREAD

**Issue by codesardine** [opencollective/opencollective#6534]
**Describe the bug**
pressing any amount button will make donate 20 disappear

**To Reproduce**
1. Go to Embeded contribution flow iframe
2. Click on donate 5 or donate other
3. button donate 20 is set to display:none

**Expected behavior**
pressing donate buttons should not hide other amount buttons

**Screen
![Screenshot from 2023-03-09 11-51-05](https://user-images.githubusercontent.com/4250006/224015449-fd9decb5-f98b-414a-84bd-b84827f5311d.png)
shots**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
I can reproduce on the non-embed version as well, by going directly to https://opencollective.com/babel/donate?interval=oneTime&amount=10&contributeAs=betree with a smaller window (mobile or tablet).
For these devices we show less contribute options to simplify the interface: https://github.com/opencollective/opencollective-frontend/blob/096e0fb92b89a2384703cdcf2d5da4ac7aa49798/components/StyledAmountPicker.js#L12.
Somehow the styles returned there doesn't seem to apply until there's an update in the interface (either the amount, the interval, the tip, etc).

**Comment by Betree** [comment]
There seems to be a bug in the way we handle it, 1st and last buttons should always be displayed
