### ISSUE TITLE
New Transaction/Expense Webhook Events for Projects

### ISSUE THREAD

**Issue by rudyfraser** [opencollective/opencollective#6539]
Hello, I’m trying to set up webhooks for “New Expenses” and “New Transactions” on a Fiscal Host account and a few Project accounts.

For Projects I only see

- All
- New Member
- Connected Account Added
- Recurring Contribution Cancelled

I would like to have webhooks for New Expense and New Transaction

Slugs for the accounts I’m referencing are pact_collective (fiscal host) and political-education (project under pact_collective)
Is there something I’ve missed or could these options be added?

**Comment by Betree** [comment]
This one is quite straightforward, we can simply enable them in the webhook event types selector in the frontend

**Comment by SudharakaP** [comment]
Reported at, https://opencollective.freshdesk.com/a/tickets/176384
