### ISSUE TITLE
New Transaction/Expense Webhook Events for Fiscal Hosts

### ISSUE THREAD

**Issue by rudyfraser** [opencollective/opencollective#6540]
Hello, I’m trying to set up webhooks for “New Expenses” and “New Transactions” on a Fiscal Host account and a few Project accounts.

For Fiscal Hosts I only see

- All
- New Collective Application
- Collective Application Approved
- Collective Created
- New Member
- Connected Account Added
- Recurring Contribution Cancelled

I would like to have webhooks for New Expense and New Transaction (since both Fiscal Hosts and Projects can have contributions and expenses). For fiscal hosts, an event should fire only if a contribution or expense is made directly to the fiscal host.

Slugs for the accounts I’m referencing are pact_collective (fiscal host) and political-education (project under pact_collective)
Is there something I’ve missed or could these options be added?

**Comment by Betree** [comment]
This one should be quite simple to implement since you don't need the event to be triggered when expenses/transactions are created on hosted accounts, but we need to make that clear in the UI:
> This event will only be triggered when the activity occurs on {host}'s account, not on its hosted initiatives.

Related: https://github.com/opencollective/opencollective/issues/4738

**Comment by SudharakaP** [comment]
Reported at, https://opencollective.freshdesk.com/a/tickets/176384

**Comment by rudyfraser** [comment]
I saw this was delivered but I don't see the changes reflected when I go into the webhook settings.
