### ISSUE TITLE
[DOCS] Export Images → Contributor image cannot change format

### ISSUE THREAD

**Issue by JulianGro** [opencollective/opencollective#6556]
The [export images](https://docs.opencollective.com/help/collectives/collective-settings/data-export#contributor-image) page has some information that is wrong.
Supposedly there is a `format` parameter. This however doesn't work. Replacing `.svg` with `.png` or `.jpg`, doesn't work. An `&format=png` also doesn't seem to do the trick.

**Comment by shannondwray** [comment]
Moved here: https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Documentation-Releases_sul57#Project-Releases_turYe/r171&view=modal
