### ISSUE TITLE
[DOCS] Document individuals and organizations in Export Images → Contributor image

### ISSUE THREAD

**Issue by JulianGro** [opencollective/opencollective#6557]
Currently it isn't documented that you can use `https://opencollective.com/collective/individuals.svg` or `https://opencollective.com/collective/organizations.svg`. I only just learned about it from a [GitHub issue](https://github.com/opencollective/opencollective/issues/2597#issuecomment-552872559).
See the [relevant documentation page](https://docs.opencollective.com/help/collectives/collective-settings/data-export#contributor-image).

**Comment by Betree** [comment]
Thanks for letting us know!

Related: https://github.com/opencollective/opencollective/issues/6255

**Comment by shannondwray** [comment]
Moved here: https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Documentation-Releases_sul57#Project-Releases_turYe/r171&view=modal
