### ISSUE TITLE
Improve the `COLLECTIVE_MEMBER_CREATED` Webhook Message

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6570]
This is related to the comment; https://github.com/opencollective/opencollective/issues/6482#issuecomment-1471551668 by, @josesimoes

> Hi,
> 
> Since my comment on the PR [opencollective/opencollective-api#8608](https://github.com/opencollective/opencollective-api/pull/8608) hasn't had any reply I'm re-posting it here.
> 
> Thank you for the quick fix. However I have a concern: this hook used to generate a more meaningful message which included the contribution amount. This is something that's pertinent to the announcement of a new contributor joining the open collective. If there is no interface to customize the message, I suggest this is added to the default message.
> 
> For reference this is how it used to look like:
> 
> ![image](https://user-images.githubusercontent.com/1881520/221951054-f154cc93-6ae4-4bfa-b73b-5a90b1766880.png)
> 
> Which later evolved to:
> 
> ![image](https://user-images.githubusercontent.com/1881520/221951170-bc0d88f6-8914-412d-91ac-a0c21186076e.png)
> 
> > > > > > > > >
> 
> Just today we've received a new contribution on the collective and this is how it looks on Discord: ![image](https://user-images.githubusercontent.com/1881520/225565800-7a552c50-edfe-4709-b91b-b69ca0fdb516.png)
> 
> Any chance you can improve this please?

I am okay with bringing back the older message if there's no objection to this. However I think we need to do this conditionally as creating a new member on an Event might not involve a contribution (free ticket for example). 

cc: @Betree

**Comment by josesimoes** [comment]
@SudharakaP understood and yes, that makes sense.
Maybe it's simple just adding a new event instead. Which would be triggered when a new contribution/contributor occurs...
