### ISSUE TITLE
Include the Order# on the receipt generated by the platform

### ISSUE THREAD

**Issue by poohlaga** [opencollective/opencollective#6571]
## User story 
As a admin/donor I want to be able to look up my expense in the UI from the receipt more easily. For example, when someone is asking for a refund or checking on the status of a manual payment, they will reference their receipt and give us the 'reference number' which is only searchable in metabase. 

## Best solution for this problem
Instead or in addition to the 'reference number' we should include the order/added funds # which is searchable in the UI. This should be applicable for any type of transaction where an invoice is generated.
Take a look at the attachment for an example of what is currently generated

## MVP
Add the order # to the receipt that the platform generates to make it easier to find an order in the UI. 

## Metrics 
talk to the support folks to confirm if this will save them time.

## Documentation 
 
<details>
  <summary>Triage Template (team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>
[transaction_confstech_2023-03-07_da3dfe42-0df4-46fe-a55e-5d36a2f725da.pdf](https://github.com/opencollective/opencollective/files/10994964/transaction_confstech_2023-03-07_da3dfe42-0df4-46fe-a55e-5d36a2f725da.pdf)

**Comment by Betree** [comment]
No blocker on my side; it's a tiny change

**Comment by jdaviescoates** [comment]
Yes please! This would pretty much solve what #6731 is all about too!
