### ISSUE TITLE
user made a donation but no 'backer' row was created in the members table

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#658]
user collective id: 10190
Made a donation to CHSF (received the email order id 5948)
Donation was made on 11/14
There is no BACKER row on the members table (user doesn't show up on the export csv which is a problem for CHSF

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by asood123** [comment]
That order id is from collective id: 10191

**Comment by piamancini** [comment]
he made a donation as an organization - probably unintentionally - and he's name wasn't showing up on the list, he's organization was.
