### ISSUE TITLE
Remove "Contributor" Collectives from Profile Dropdown

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6583]
Related to the ticket https://opencollective.freshdesk.com/a/tickets/173778

It seems that currently when a user submits and expense and gets paid by a collective we add a entry to the `Members` table with role `CONTRIBUTOR`, and then we show the collective in the profile dropdown menu. 

![image](https://user-images.githubusercontent.com/12435965/226498191-0fc1fd0b-8bbf-4077-aff4-8556c5d0e566.png)

This seems to be a problem if the user has lot of collectives which they have submitted expenses and and do not want these collectives to appear in the dropdown menu. In the aforementioned ticket the user is asking specifically for not show this kind of collectives or a way for them to remove those from the menu. 

My suggestion is to show this kind of collectives within a collapsible menu (same as archived collectives) with the title, "Contributed Collectives" with a tooltip near the title of the collapsible menu to explain what "Contributed" here means; "Collectives for which you have submitted expenses or received reimbursements".

cc: @Betree

**Comment by Betree** [comment]
> Contributed Collectives

Not a fan of this as a title, the word "Contributor" is a bit vague (is it a financial contributor, a code contributor, a docs contributor?), and the concept we have for it in the code (people who got paid by the collective) doesn't really have an equivalent in our glossary.

Adding a tooltip to explain that would be, in my opinion, a hack to work around wording issues.

I would rather challenge the presence of this "contributors" role in the menu altogether; is it really useful, especially now that we have a "Manage my expenses" link in the menu?

**Comment by SudharakaP** [comment]
> > Contributed Collectives
> 
> Not a fan of this as a title, the word "Contributor" is a bit vague (is it a financial contributor, a code contributor, a docs contributor?), and the concept we have for it in the code (people who got paid by the collective) doesn't really have an equivalent in our glossary.
> 
> Adding a tooltip to explain that would be, in my opinion, a hack to work around wording issues.
> 
> I would rather challenge the presence of this "contributors" role in the menu altogether; is it really useful, especially now that we have a "Manage my expenses" link in the menu?

@Betree : Yes I am all for removing it as well. I just thought of keeping it as maybe people are used to going there to submit reimbursements etc if they've already done it previously. Or someone who usually contributes to a collective and submits expenses for bounties and such might find it helpful to quickly find the collective this way. 🤔

**Comment by Betree** [comment]
Could be. I'd love to get @opencollective/design's opinion on this one.

**Comment by SudharakaP** [comment]
This has been brought up again at, https://opencollective.freshdesk.com/a/tickets/185095. 

ping: @opencollective/design

**Comment by SudharakaP** [comment]
Brought up again at, https://opencollective.freshdesk.com/a/tickets/199773.

**Comment by Memo-Es** [comment]
> I would rather challenge the presence of this "contributors" role in the menu altogether; is it really useful, especially now that we have a "Manage my expenses" link in the menu?
I'm with @Betree on this one. TBH I was never a fan of including expense submitters as contributors, less so to display the Collectives you have submitted expenses to as part of "your Collectives" as if you were some admin.
My vote would be to remove this completely since we have now more and better tools to account for the relationship expense submitter - Collective
