### ISSUE TITLE
Edit draft resets the payee to default profile

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6586]
**Describe the bug**
When editing an invited expense right after submission, the payee profile is not set to the person who got invited initially.

Note that this does not affect the flow of invited users clicking on the email link (the one that includes a `key`).

**To Reproduce**
1. Invite someone to submit an expense
2. On the expense page, click "Edit"
3. See issue: default logged in user profiles used in place of invited profile

**Screenshots**
![Peek 2023-03-21 13-38](https://user-images.githubusercontent.com/1556356/226608315-e081d9a2-8b4a-43bf-8193-2c4fa256a845.gif)

cc @kewitz

**Comment by kewitz** [comment]
Hey @Betree, I cannot reproduce this locally. Are you sure you're an admin of "test" in this example? Otherwise, you would be trying to submit an expense on behalf of someone else, and that's not allowed.

**Comment by Betree** [comment]
It's more of a UX issue than a bug; as an expense inviter, I'd like to be able to edit some basic information about the invitation I just submitted. The system lets me "Edit" so you expect this to be possible. Having the payee switched to your personal profile is unexpected in this scenario.

**Comment by Betree** [comment]
We're shutting down the legacy expense flow.
