### ISSUE TITLE
Draft expense errors when no amount is set

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6587]
The expense flow lets you draft an expense without enforcing any amount. But if you try to submit it, you get a cryptic error from the API:

> Validation error: Validation min on amount failed: Validation min on amount failed

![image](https://user-images.githubusercontent.com/1556356/226617611-70d79a98-bf9a-4ac8-9114-057852aa60d3.png)

## Suggested solution

Enforce the amount to be set in the frontend or allow empty amount in the API.

**Comment by la-costa** [comment]
@Betree, it looks like this issue is already fixed in the main branch.

![Screenshot from 2023-10-09 13-54-36](https://github.com/opencollective/opencollective/assets/16106846/20bca582-effc-4908-ad4e-d93b50c2196d)

**Comment by Betree** [comment]
@la-costa You're not trying with the "Invite" flow, where most fields are supposed to be optional. To trigger it, you need to pick a special value in the "Payee step":

![image](https://github.com/opencollective/opencollective/assets/1556356/ccc681f3-3222-477d-9af2-2378c37dbc8c)

**Comment by Betree** [comment]
We get a lot of occurences for this one: https://open-collective.sentry.io/issues/4637984981/?project=5199682&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=13
