### ISSUE TITLE
Add tax info on invite expense email

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6588]
The expense invite email doesn't contain any information about the taxes:

![image](https://user-images.githubusercontent.com/1556356/226619204-fe74af9d-67a6-40d2-98e1-bb6b4b9c01cf.png)

**Comment by sreenidhithallam** [comment]
Hi @Betree, Could you please assign this issue on my name?

**Comment by Betree** [comment]
@sreenidhithallam done. Though this issue should be fairly simple to implement, testing can be a bit complex. Feel free to jump on another issue if you're blocked, or to ask for steps to reproduce

**Comment by Betree** [comment]
Will look at this as part of https://github.com/opencollective/opencollective-api/pull/9529, since we need to edit the email to show the new item currency / FX rate infos.
