### ISSUE TITLE
User being sent to null page when trying to edit profile

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#659]
Joey wants to edit his payment methods, however, when trying to enter to "edit profile" he is sent to a null page :/

Here is his message:

I am getting issues with a redirect to https://opencollective.com/null/edit where I need to login again. I also experience in the Netherlands very slow loading times...it is better than an hour ago. 

So when I logged in, go to profile and edit profile then I get to a page where I am asked to log in again. I think it is a bug because when I click on "Profile" in "Say Yup" (my account) I get redirected to https://opencollective.com/null which is not correct...

Does this help you?

With kind regards,

Joey

PS: released a new version of the site today? perhaps there it broke.

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by xdamman** [comment]
I can’t investigate this issue without the username or user id or email

**Comment by nicobarretoOC** [comment]
I just sent it through slack ;)

**Comment by piamancini** [comment]
@xdamman this happened several times. Is part of the error we saw with @asood123 when two member rows get created when someone adds a member through the platform. The second user still shows up as /null

**Comment by xdamman** [comment]
It's fixed for this user.

I won't have time to look into that underlying issue before Tuesday afternoon. @asood123 if you have time, can you create a new constraint on `Collectives` to make sure that `slug` cannot be null (and also make a migration script to fix the current entries that have a null slug)?
Not sure what the error is for adding new members.

**Comment by asood123** [comment]
Same fix as #672
