### ISSUE TITLE
Remove pledges feature

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6590]
Revival of [this proposal](https://github.com/opencollective/opencollective/issues/3135)

# Acknowledging
- That maintaining code for a feature always takes time (eg. tests need to be updated, bugs...)
- That unmaintained features can contain security issues, or be a vector for privilege escalation
- That the bigger/more complex the code base, the harder it is for newcomers to get on board

# Motivation

- We're currently unable to deprecate and refactor legacy code (e.g. GraphQL V1 `createOrder`) because we need to keep supporting this feature.
- The [plans](https://github.com/opencollective/opencollective/discussions/6027) we have to redux this feature would be very different from the current, so we'll need to get rid of the existing no matter what.
- When https://github.com/opencollective/opencollective/issues/3135 was first open, we didn't have much data on pledges. We now have enough to argue that the feature is barely used.
- The number of projects claimed is very low
- Pledges are a nice communication tool, but you can arguably achieve the same effect by contacting the projects directly and asking them to register on Open Collective.
- It's not a flow that we're testing often; we may miss regressions (tho we added some tests recently to make it stronger)
- It adds some complexity to the code; it's hard to differentiate between pledges and pending orders

# [Data](https://opencollective-metabase.herokuapp.com/dashboard/117-pledges)

![image](https://user-images.githubusercontent.com/1556356/226670374-e2f555ac-de74-4931-b77c-5c7e928615a1.png)

![image](https://user-images.githubusercontent.com/1556356/226670439-d056a2a4-a36b-4aab-8d8c-f533b7cf9820.png)

# Context

Would close the following issues:
- https://github.com/opencollective/opencollective/issues/3586
- https://github.com/opencollective/opencollective/issues/3577
- https://github.com/opencollective/opencollective/issues/3320
- https://github.com/opencollective/opencollective/issues/3319
- https://github.com/opencollective/opencollective/issues/3256

# To do
- [x] [Remove the ability](https://github.com/opencollective/opencollective-api/pull/9204) to create new pledges in the API
- [x] Delete all existing pledges in the database
- [x] Delete all pledged collectives in the database
- [x] Remove the page for pledged collectives in the frontend
- [x] Remove all from documentation

**Comment by BenJam** [comment]
I outlined my views on it over in https://github.com/opencollective/opencollective/discussions/6027 

TLDR: I think there's an opportunity to revive pledges as a kind of 'Funds for individuals' which I think would address some of the issues with the original feature.

**Comment by Betree** [comment]
@BenJam the proposal you made in https://github.com/opencollective/opencollective/discussions/6027 works in a different way, therefore:
> The https://github.com/opencollective/opencollective/discussions/6027 we have to redux this feature would be very different from the current, so we'll need to get rid of the existing no matter what.

According to this, do you see any blocker with the removal of the feature as it is today?
