### ISSUE TITLE
Accountants should have access to draft expenses

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6592]
Permissions to be edited in https://github.com/opencollective/opencollective-api/blob/01df4b57787629e4a05638263a7f3ba01953ef2d/server/graphql/v2/query/ExpenseQuery.js#L29

**Comment by sreenidhithallam** [comment]
Hi @Betree, Could you please assign this issue on my name?

**Comment by Betree** [comment]
Resolved by https://github.com/opencollective/opencollective-api/pull/8782
