### ISSUE TITLE
Regression Caused by Permissions Change - Expenses

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6597]
This is related to several tickets; https://opencollective.freshdesk.com/a/tickets/180260 and https://opencollective.com/ridgewood-mutual-aid-project/expenses/129629

In these cases the collective admins are trying to edit an expense but fails to do so as per the recent expense permissions change, https://github.com/opencollective/opencollective-api/pull/8655. 

My suggestion is that since we have remove the permission from the collective admins to do the majority of expense edit functionality not show the "Edit" button in the actions drop-down for collective admins thus making the collective admins unable to edit expenses.

**Comment by SudharakaP** [comment]
@Betree : Let me know what you think. I've opened a PR with the proposed fix.

**Comment by Betree** [comment]
Interesting, I didn't see this one coming. Your fix makes sense; we should merge it. 

But I see a need for collective admins to upload receipts for any virtual card charge triggered on their collectives, not just the ones they're assigned to. Let's start restrictive and update depending on the feedback we get.

**Comment by SudharakaP** [comment]
> Interesting, I didn't see this one coming. Your fix makes sense; we should merge it.
> 
> But I see a need for collective admins to upload receipts for any virtual card charge triggered on their collectives, not just the ones they're assigned to. Let's start restrictive and update depending on the feedback we get.

Yes definitely, I think this new process will create some issues for collective admins who use to edit expenses themselves now that they cannot do it anymore. So being able for the collective admins to edit some parts of the expense might make sense like the virtual cards as well as expense description and title. 🤔
