### ISSUE TITLE
Can't find Add Funds function to manually add funds to a collective

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#660]
Hey the new interface is looking awesome, I just noticed from Brittani's (WWCode) email that the "add funds" button is no longer showing under the expenses page:

> Hi Pia - 
> 
> I'm attempting to add funds to Twin Cities Open Collective. It looks like the "Add Funds" option is no longer showing up.  Is there a new protocol for adding funds we receive through other payment methods? 
> 
> ​Thanks! ​

**Comment by piamancini** [comment]
answered.
