### ISSUE TITLE
Currency confusion when contributing

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#661]
Feedback from [TechWo](https://opencollective.com/techwo) collective, since they have their collective set to MXN when a backer with an English web browser wants to contribute, they see this:

![screen shot 2017-11-16 at 12 06 56 am](https://user-images.githubusercontent.com/30665166/32876374-292e273e-ca62-11e7-8579-4e3fc4fee013.png)
![screen shot 2017-11-16 at 12 07 07 am](https://user-images.githubusercontent.com/30665166/32876379-2e4263a2-ca62-11e7-89d8-2cd2b36d72bb.png)
So they do not see if they are making a contribution in MXN or USD, however, when they click on the "Donate" button it does show the amounts in MXN.

![screen shot 2017-11-16 at 12 07 18 am](https://user-images.githubusercontent.com/30665166/32876399-4fb59cc0-ca62-11e7-8b4f-97b7c23ed3eb.png)

**Comment by znarf** [comment]
@nicobarretoOC It's working as expected. The Tiers (like "backer") are expressed in USD, while the Collective currency is the MXN. So, it's definitely not a UI issue.

If this is a problem, perhaps the collective should change its Tiers currency from USD to MXN.
