### ISSUE TITLE
Add Funds Button Does Not Appear for New Orgs

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6616]
Working on another issue, I've noticed that for certain hosts, the actions menu do not show the Add Funds button. This is due to some hosts not having the `HostCollectiveId` being not set. To re-create this scenario do the following as an example. 

1) Create a new organization. 

2) Make the organization a new host. 

Then go to the organization page and try to add some funds. There's no way to do it as there's no button to add funds. It seems that in the DB some hosts with `isHostAccount=true` has `HostCollectiveId` set whereas for some it doesn't. 

[added-funds.webm](https://user-images.githubusercontent.com/12435965/228704432-6551fe08-f34c-4810-92ba-7e2c6d3be2a1.webm)

**Comment by alanna** [comment]
I was just on a call with FYA and this was affecting them. When the Host admin looks at the actions menu for one of their Collectives, they don't see add funds. They can add funds via hosted collectives on the host dashboard.

**Comment by SudharakaP** [comment]
My mistake. Closing this issue as per, https://github.com/opencollective/opencollective-api/pull/8753#issuecomment-1490742719

> I was just on a call with FYA and this was affecting them. When the Host admin looks at the actions menu for one of their Collectives, they don't see add funds. They can add funds via hosted collectives on the host dashboard.

I believe this is a different issue which I've also observed; probably due to caching. In the first visit to this collective page the `Add Funds` button is not visible but then when I refresh the page it becomes visible.

**Comment by alanna** [comment]
OK but has that cacheing issue been fixed @SudharakaP ? They need to see the option in the menu even the first time they load the page.
