### ISSUE TITLE
[API] Allow donation in arbitrary currency

### ISSUE THREAD

**Issue by darkdragon-001** [opencollective/opencollective#6629]
## User story 
_As API user, I can easily donate some fixed amount in my currency to any collective so that I don't need to care about currencies._

The current workaroud looks as follows:
- Load list of collective I want to donate to
- Query account's host currency for each collective via
    <details>
    <summary>Example code</summary>

    ```python
    import functools
    import itertools
    from typing import List, Tuple
    
    def chunk(it, size):
        it = iter(it)
        return iter(lambda: tuple(itertools.islice(it, size)), ())
    
    def sanitize_slug(slug: str):
        return slug.replace("-", "_")
    
    async def query_account_host(client: gql.Client, slugs: str|List[str]|Tuple[str]):
        if type(slugs) not in [list, tuple]:
            slugs = [slugs]
    
        async def _query_account_host(slugs: List[str]):
            account_query_template = """
                  {slug_sanitized}: account(slug: "{slug}") {{
                    ... on Individual {{
                      host {{
                        name
                        slug
                        currency
                        hostFeePercent
                      }}
                    }}
                    ... on Collective {{
                      host {{
                        name
                        slug
                        currency
                        hostFeePercent
                      }}
                    }}
                    ... on Organization {{
                      host {{
                        name
                        slug
                        currency
                        hostFeePercent
                      }}
                    }}
                    ... on Fund {{
                      host {{
                        name
                        slug
                        currency
                        hostFeePercent
                      }}
                    }}
                    ... on Project {{
                      host {{
                        name
                        slug
                        currency
                        hostFeePercent
                      }}
                    }}
                  }}
            """
            account_query = "".join([account_query_template.format(slug=slug, slug_sanitized=sanitize_slug(slug)) for slug in slugs])
            query = f"""
                query {{
                  {account_query}
                }}
            """
            data = await graphql_query(client, query)
            if data is None:
                return {}
            
            return data
    
        # NOTE query is too long to yield internal server error when running with whole database
        chunk_size = 10
        data_chunks = [await _query_account_host(slugs_chunk) for slugs_chunk in chunk(slugs, chunk_size)]
        data = functools.reduce(lambda value, element: value | element, data_chunks, {})
        
        return {slug: account["host"] for slug, account in data.items()}
    ```

    </details>
- Query the conversion rate from my credit card company and calculate fees for conversion
- Calculate amount in collective's host's currency I want to donate

This is quite complicated and error prone often ending up in spending a different amount from what I intended to spend. It shouldn't make a big difference for the credit card company or Stripe making the currency exchange. Your platform even seems to support currency exchange information for orders based on [`Amount.CurrencyExchangeRate`](https://graphql-docs-v2.opencollective.com/types/Amount).

## Best solution for this problem
Calling [`createOrder()`](https://graphql-docs-v2.opencollective.com/mutations/createOrder) with [`Amount.Currency`](https://graphql-docs-v2.opencollective.com/types/AmountInput) set to an arbitrary value.

## MVP
API call works without error.

## Metrics 
Number of people making use of this feature.

## Documentation 
_None_ necessary.

<details>
  <summary>Triage Template (team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Mayaleeeee** [comment]
Hi @darkdragon-001 
Is this a design project?

If yes, I would love to work on it.

**Comment by darkdragon-001** [comment]
@Mayaleeeee What do you mean by "design project"? So far it's just scripts interacting with the API to work around various other deficiencies (see my other open issues).

**Comment by darkdragon-001** [comment]
Thanks @Betree, this issue is covered by the combination of both linked issues. Closing as duplicate.
