### ISSUE TITLE
Assist Colan getting his profile slug right

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#664]
Mail form Colan:

> Hi Nicolas,
> 
> I added a new member, and removed the old one.  But I can't get change my user path to "colan-schwartz" (Validation error, as it's taken by the original user).  Would you kindly delete the original user so I can use this path?
> 
> Thanks,

 This is the user email can be found at the original mail message.

**Comment by colans** [comment]
Would you kindly obfuscate my e-mail address in the issue description above so it doesn't get picked up by spam harvesters?  Thanks!  (And thanks for helping me with this issue.)

**Comment by nicobarretoOC** [comment]
@colans Sorry about that!

**Comment by piamancini** [comment]
done @colans you can now log in as an admin with the new email address.

**Comment by colans** [comment]
@piamancini Looks like my account is listed twice in the Aegir collective now?  Did you perhaps add another one, not knowing that I already did this myself?  I tried deleting one of them, but it came back after I logged in again.  (Also, the same collective is showing up twice in my profile, but I think this is a side-effect of the above.)

When deleting one of them, don't delete the one with the path `/colan-schwartz`.  Please delete the other one instead.  Thanks!

**Comment by piamancini** [comment]
@colans good catch. should be fixed now, caching  might still occur. Try appending ?213 to the url to force a refreash

**Comment by colans** [comment]
Nope, still there twice, but it looks like the same account.

**Comment by piamancini** [comment]
@colans I'm sorry this fell off my radar. It's fixed now. 
It seems like your collective is not active yet. Can I help with anything? What's your host status? Do you need one?
