### ISSUE TITLE
Collective balance not matching

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6640]
**Describe the bug**
If you look on [this Collective's expenses page](https://opencollective.com/julian-collective/expenses) it shows this balance

<img width="260" alt="Screen Shot 2023-04-06 at 9 46 43 AM" src="https://user-images.githubusercontent.com/5498878/230219379-f949bb41-8f5c-4c44-b3d4-2baf86311fb4.png">

But if you look at [their budget section](https://opencollective.com/julian-collective#category-BUDGET) it shows this:

<img width="299" alt="Screen Shot 2023-04-06 at 9 46 30 AM" src="https://user-images.githubusercontent.com/5498878/230219470-1485af23-3a57-4ad5-9959-88009f4feab5.png">

I cannot see any events or projects for this Collective where funds could be:
<img width="605" alt="Screen Shot 2023-04-06 at 9 49 03 AM" src="https://user-images.githubusercontent.com/5498878/230219646-4b07353b-d4f6-468d-a898-cde009e86aa7.png">
<img width="575" alt="Screen Shot 2023-04-06 at 9 49 12 AM" src="https://user-images.githubusercontent.com/5498878/230219654-68398c09-f48e-429d-9fd0-b8ac4af81469.png">

So what's going on? We as the host really need to verify the correct balance for this Collective fairly urgently.

**Comment by znarf** [comment]
Seems on the Expenses page we display the balance with blocked funds removed (expenses being processed https://opencollective.com/julian-collective/expenses?status=PROCESSING). This is the balance that's gonna be used before paying any Expense.

It's honestly a bit surprising, we don't expose the balance with blocked funds usually in the interface. I think both should be displayed here in the end, with a tooltip perhaps.

```
query {
  collective(slug: "julian-collective") {
    id
    stats {
      balance {
        value
        currency
      }
      balanceWithBlockedFunds: balance(withBlockedFunds: true) {
        value
        currency
      }
    }
  }
}
```

```
{
  "data": {
    "collective": {
      "id": "dgm9bnk8-0437xqrg-9dkpvzeo-ljdayw5r",
      "stats": {
        "balance": {
          "value": 58148.87,
          "currency": "USD"
        },
        "balanceWithBlockedFunds": {
          "value": 35798.33,
          "currency": "USD"
        }
      }
    }
  }
}
```

**Comment by znarf** [comment]
Closing as duplicate with https://github.com/opencollective/opencollective/issues/6940
