### ISSUE TITLE
Address not printed on receipt

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6658]
If you download the receipt for this transaction: https://opencollective.com/the-archive-project/orders/599934

The address is not shown under the person's name. But when I look at this profile in metabase, the address is there. Addresses should be printed on receipts.

Please note this is an incognito transaction and the user's name or details should not be mentioned publicly in this issue.

**Comment by yhoungdev** [comment]
Can this be assigned to me?

**Comment by yhoungdev** [comment]
Thanks on it

**Comment by Betree** [comment]
This issue will only affect the admins; if the contributor downloads the PDF they'll have the info printed correctly.

The fix must happen in the API, in https://github.com/opencollective/opencollective-api/blob/3fcba43c35025c032a0caffd07348981332bbe82/server/graphql/v2/object/Individual.js#L77 we must allow access in the context of a query that fetches the information form the host. Basically, we need to extend the permission that was implemented with https://github.com/opencollective/opencollective-api/blob/3fcba43c35025c032a0caffd07348981332bbe82/server/graphql/v2/object/Credit.js#L20 to also allow locations.
I'd recommend renaming `SEE_ACCOUNT_LEGAL_NAME` to `SEE_ACCOUNT_LOCATION` in this intent.

@yhoungdev Thanks for jumping on it, but it appears this issue will be complex to solve and test for a first contribution. I'd suggest finding another one if that's ok.
