### ISSUE TITLE
Paypal optional platform tip

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6669]
## Who is your user?
A user contributing with Paypal.

## What are they trying to achieve?
They aren't given the option to contribute a platform tip. 

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment]
I'm not sure I understand this issue, are we talking about platform tips? If so, platform tips appear the same way regardless of the payment method. What makes you think they're not?

**Comment by shannondwray** [comment]
A user was wondering why the platform tip option wasn't coming up when contributing via paypal, I wasn't able to test as I didn't want to make a contribution

**Comment by Betree** [comment]
@shannondwray Can you link the conversation/ticket? [Here](https://opencollective.com/captainfact_io/donate), you can see that the tip info is required at step one before the payment info. Therefore I don't see how the payment method type could impact the tip.

**Comment by shannondwray** [comment]
https://opencollective.com/darkreader/contribute/backer-3762/checkout?interval=month&amount=5&contributeAs=shannondwray - There no platform tip here, did OSC turn it off?

**Comment by Betree** [comment]
@shannondwray Platform tips were never enabled for OSC. It's on our radar, but there are many unknowns, and we would need to test the change on a few collectives first to make sure the community responds well to such a pricing change.

**Comment by shannondwray** [comment]
Okay coolies! thank you for your info! Ill relay to this user :)
