### ISSUE TITLE
Host fees on pending contributions to the host itself

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6670]
In the "Add funds" modal, we don't let admins change the host fee for contributions to the host: https://github.com/opencollective/opencollective-frontend/blob/2fcb8b4d4d3704244a36218a3a884236cccb5887/components/host-dashboard/AddFundsModal.js#L395. This is also the logic used for the "Confirm contribution" modal: https://github.com/opencollective/opencollective-frontend/blob/2fcb8b4d4d3704244a36218a3a884236cccb5887/components/ContributionConfirmationModal.tsx#L89.

However in https://github.com/opencollective/opencollective-frontend/blob/2fcb8b4d4d3704244a36218a3a884236cccb5887/components/host-dashboard/CreatePendingOrderModal.tsx#L259 we let admins set a host fee for contributions to the host.

**Comment by znarf** [comment]
Related: https://github.com/opencollective/opencollective-frontend/pull/8766

**Comment by znarf** [comment]
Let's remove that.
