### ISSUE TITLE
Fiscal Host Admin should be able to edit a transaction created with 'Added Funds'

### ISSUE THREAD

**Issue by poohlaga** [opencollective/opencollective#6681]
## User story 
As a Fiscal Host Admin, I would like the ability to edit ‘added funds’ transactions the same way a fiscal host admin can edit regular transactions. Once it is in a Paid state, I want to mark it as ‘unpaid’ so I can edit the description or date if needed. Then I want to bring it back to a Paid state.
This will help us clean up previously entered manual deposits for accounting purposes.

## Best solution for this problem
_What does the ideal solution look like?_

## MVP
_What should be possibly built to demonstrate the solution?_

## Metrics 
_What metrics will be used to measure impact?_

## Documentation 
_The goal of the documentation should be to make it easier for others to do this_

<details>
  <summary>Triage Template (team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
+1 on this: Support/Engineering regularly have to update added funds manually.

**Comment by souravcipher** [comment]
+1 for this feature!
