### ISSUE TITLE
Platform Tips are Not Shown In Financial Contributions Page

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6683]
**Describe the bug**

It seems that for contributions the platform tips are not shown in the contribution page nor the transactions details. 

**To Reproduce**

1. Go to any contribution page for an contribution that includes platform tips.
2. Notice that they don't include platform tips although looking at the DB they do have platform tips. 

**Expected behavior**
We should show platform tips both in the transactions details as well as in the contribution page. 

**Screenshots**

![image](https://user-images.githubusercontent.com/12435965/233511279-1e01d181-8589-4b8f-a6b5-06cae719a8e8.png)

**Additional context**

Example contributions where this happens; https://opencollective.com/food-not-cops/orders/594950, https://opencollective.com/food-not-cops/orders/594752 and https://opencollective.com/food-not-cops/orders/593470

**Comment by Betree** [comment]
@SudharakaP I'm interested in this one; please ping me on the review or assign me on the issue if you don't have the time.

**Comment by SudharakaP** [comment]
> @SudharakaP I'm interested in this one; please ping me on the review or assign me on the issue if you don't have the time.

I've opened a PR. I've added the platform tip as a small note beneath the transaction amount similar to how we handle payment processor fee. Let me know what you think. The screenshot is given in the PR.

**Comment by Betree** [comment]
Just a note to say that the root cause for this issue was that we're only showing the transactions that affect the currently displayed account (`transaction.account === account`), which is an elegant approach - even though it doesn't necessarily match the user expectations in this case.
