### ISSUE TITLE
Selecting `EU` on the Country Filter in `/search` Page Gives Error

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6689]
**Describe the bug**
Reported at, https://opencollective.freshdesk.com/a/tickets/200026. 

**To Reproduce**
1. Go to https://opencollective.com/search
2. Click on the country filter and select "European Union"
3. See error

**Expected behavior**
This error is also related to the case where a user goes to the collective or profile settings, info section and selects the country as European Union. 

**Screenshots**

![image](https://user-images.githubusercontent.com/12435965/233734024-244de400-4c45-4825-a489-e4223eacad7d.png)

**Comment by SudharakaP** [comment]
API errors out with; 

```
error: GraphQL error: Variable "$country" got invalid value "EU"; Value "EU" does not exist in "CountryISO" enum. Did you mean the enum value "AU", "CU", "EC", "EE", or "EG"?
```

We need to remove `EU` from the list that's shown in the front-end as EU is really not a country but a region.

**Comment by Betree** [comment]
cc @hdiniz, I remember he had a PR for this

**Comment by znarf** [comment]
I'm sorry but we sh

**Comment by Betree** [comment]
@znarf Just to clarify, the [country flag](https://github.com/opencollective/country-currency-emoji-flags) package is an internal one. `EU` had nothing to do in the countries list there, so https://github.com/opencollective/country-currency-emoji-flags/pull/4 was welcome in all cases.

I've moved your comment to https://github.com/opencollective/opencollective/issues/6703 for us to find a more direct source of truth for this countries list, which should be an easy fix if we re-use the `CountryISO` Typescript enum that we get from the API in https://github.com/opencollective/opencollective-frontend/blob/f0e476ee72c5f7565b5d72fe22d3d865e12927f1/lib/graphql/types/v2/graphql.ts#L1988.

**Comment by znarf** [comment]
As EU is a valid country code (according to https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) and has a matching emoji, for me it was not hurting or a mistake to have it in the list, could be useful.

We're simply removing because this had a non-desired side effect.

Thank you for creating [the follow up issue](https://github.com/opencollective/opencollective/issues/6703), I think this is the right call.

**Comment by Betree** [comment]
I'm still seeing the issue in production, even though we've supposedly updated the package

**Comment by SudharakaP** [comment]
> I'm still seeing the issue in production, even though we've supposedly updated the package

It seems that my last update to the package somehow didn't reflect the `EU` removal change. I've created a new package update; https://github.com/opencollective/opencollective-frontend/pull/8862

Also opened a PR for the alternative fix; https://github.com/opencollective/opencollective/issues/6703
