### ISSUE TITLE
Embed contribution flow: using custom parameters enforces "SAMEORIGIN" header

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6691]
Reported in https://opencollective.slack.com/archives/C01NGE0N9U1/p1681662551043349

When embedding the contribution flow with custom parameters, our website sometimes seem to append a "X-FRAME-OPTIONS: SAMEORIGIN" header.

Example URL: https://opencollective.com/embed/test-event-cbc83ea7/contribute/early-bird-55016?email=test%40hello.com
Note that it doesn't seem to impact all parameters/URLs: https://captainfact.io/support-us doesn't seem to be impacted.

It could be an automatic security feature from Cloudflare, adding a default header in some cases. Potentially something we could modify with workers.

**Comment by daggerhart** [comment]
I haven't dealt any with workers, but this seems to be a relavant resource https://developers.cloudflare.com/workers/examples/security-headers.

There is also an option to Transform Response Headers in Cloudflare. I wonder if something like this could work:
![Screenshot 2023-04-24 at 7 55 44 AM](https://user-images.githubusercontent.com/1205329/233989143-556e2f0c-524c-404f-b68c-a7ca452f7a63.png)

**Comment by znarf** [comment]
@Betree Isn't this generated by helmet configured here?
https://github.com/opencollective/opencollective-frontend/blob/main/server/index.js#L54

**Comment by Betree** [comment]
> @Betree Isn't this generated by helmet configured here? https://github.com/opencollective/opencollective-frontend/blob/main/server/index.js#L54

This one is supposed to be removed from https://github.com/opencollective/opencollective-frontend/blob/38eeeec346465433e9f6886d74a654b350085ca8/pages/embed/contribution-flow.js#L35.

What makes me think about Cloudflare is that we've seen it adapt its behavior based on queries, for example, block anything that looks like a SQL injection, and here the issue was reported to happen only when adding URL parameters (e.g. `email=...@`).

But it could also come from a concurrency issue between helmet and the `res.removeHeader`, I haven't digged enough at this point.

**Comment by daggerhart** [comment]
Got the opencollective-frontend running and looked into `EmbedContributionFlowPage.getInitialProps()`

From an untrained eye, it appears to be doing the job.  Here are the `res.getHeaderNames()` before and after the attempt to remove the x-iframe-option.

![Screenshot 2023-04-25 at 9 14 52 PM](https://user-images.githubusercontent.com/1205329/234441248-46269353-974b-496d-ad71-174a461ce788.png)

It exists and is removed.

I'm not really a node guy. Is there somewhere else worth looking? Another place response headers are normally set?

**Comment by Betree** [comment]
@daggerhart Thanks for digging into it!

I tried to reproduce it as well this morning, turns out it's a redirect issue; you got the right intuition when you suggested a sideeffect of the page not being routed correctly :slightly_smiling_face: 

https://opencollective.com/embed/test-event-cbc83ea7/contribute/early-bird-55016?email=test%test.com 
is redirected to https://opencollective.com/embed/daggerhart-testing/events/test-event-cbc83ea7/contribute/early-bird-55016%3Femail=test%test.com

```diff
- /embed/test-event-cbc83ea7/contribute/early-bird-55016?email=test%test.com 
+ /embed/daggerhart-testing/events/test-event-cbc83ea7/contribute/early-bird-55016%3Femail=test%test.com
```

It's a common practice we have to always prepend the parent in the URL.

But then the rewrite doesn't work because it [pattern matches](https://github.com/opencollective/opencollective-frontend/blob/5c6afc3cd67e1d18c4b08a0e27584a580fc4e08e/rewrites.js#L213) on a `:tierSlug?-:tierId([0-9]+)`, but with the broken query params the URL now ends with `55016%3Femail=test%test.com`. We're therefore redirected to a 404, and the 404 doesn't have an `X-Frame-Options` set, thus this error.

I'm looking into a fix for this query parameters issue.

**Comment by Betree** [comment]
@daggerhart As an immediate fix, you can use the full URL in your embed (with the parent already prepended):

https://opencollective.com/embed/daggerhart-testing/events/test-event-cbc83ea7/contribute/early-bird-55016?email=test@opencollective.com
