### ISSUE TITLE
Better default cover for open source projects

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#67]
The current default header doesn't look great for open source projects
https://opencollective.com/react-static-boilerplate

(but it looks terrific when rightly customized https://opencollective.com/mochajs)

Can we have a better default specific to open source projects?

**Comment by piamancini** [comment]
I agree, specially with transparent or white logos


P.
piamancini.com
t: @piamancini
s: piamancini
OpenCollective <https://opencollective.com>

**Comment by GranularDetective** [comment]
It would be better to have a diversity of logos, I feel. Much of the visual and symbolic appeal of the new: Captain America: Civil War file was in its visual diversity and, dare I say, the symbolism from whence it derived. It would be useful to Capitalise on the zeitgeist in this regard I feel. If you're interesting in such things, of course...

**Comment by erickrico** [comment]
to recap the stand up and get this going,   im going to be working on the editable version of a collective page, and give a set of assets for open-source projects so they can look awesome with or without logo/cover ✌️

**Comment by piamancini** [comment]
the order should be
1 - shipping github onboarding
2 - set of assets for OS as default
3 - editable version of collective page

P.
piamancini.com
t: @piamancini
s: piamancini
OpenCollective <https://opencollective.com>

**Comment by erickrico** [comment]
hey, i made some images for collectives without logo, i tried a generic clean approach, also i think that placing the collective logos in circle containers can solve a lot of issues with the collectives, most of them already have this kind of images for facebook or twitter 

## default images for collectives 
![code](https://cloud.githubusercontent.com/assets/18429104/15199931/06fca9c4-17a8-11e6-8083-c43effd41ff5.png)
![mouse](https://cloud.githubusercontent.com/assets/18429104/15199930/06fca816-17a8-11e6-891c-047ca72b43c8.png)
![page](https://cloud.githubusercontent.com/assets/18429104/15199932/06fedec4-17a8-11e6-849b-585f7acf706d.png)
![repo](https://cloud.githubusercontent.com/assets/18429104/15199929/06fc7ecc-17a8-11e6-8e42-ece77c5567e9.png)
![rocket](https://cloud.githubusercontent.com/assets/18429104/15199934/06ff8162-17a8-11e6-8e72-59a79ffe8e19.png)
![open](https://cloud.githubusercontent.com/assets/18429104/15199933/06ff37de-17a8-11e6-9ade-b94e6e39c293.png)
![bessier](https://cloud.githubusercontent.com/assets/18429104/15199935/07086b92-17a8-11e6-84c3-739e09d546d7.png)

## in context
![screenshot 2016-05-11 18 26 01](https://cloud.githubusercontent.com/assets/18429104/15199941/27c8c34a-17a8-11e6-89ee-dca980f0b4c9.png)

## collectives with circle containers 

![screenshot 2016-05-11 18 27 49](https://cloud.githubusercontent.com/assets/18429104/15199948/3cd1023e-17a8-11e6-9344-1ad0a5d0e37c.png)
![screenshot 2016-05-11 18 27 34](https://cloud.githubusercontent.com/assets/18429104/15199953/427e79be-17a8-11e6-8a48-1dcc8f4c3160.png)

**Comment by xdamman** [comment]
At the beginning we had circles everywhere but we realized that it didn't work for most logos. It's great for avatars though. 
That said, the circles you designed as default logo are fine. 

What about background images?

Also I don't think we need that many. 2-3 max should be enough.

**Comment by erickrico** [comment]
background images for open source

## images
![wireframe](https://cloud.githubusercontent.com/assets/18429104/15223623/0bd4c2ea-183b-11e6-8e05-920f2a80bced.png)
![team](https://cloud.githubusercontent.com/assets/18429104/15223624/0bd60aec-183b-11e6-9d1a-0c0f6c3f9c59.png)
![coding](https://cloud.githubusercontent.com/assets/18429104/15223626/0bd63792-183b-11e6-83bf-42617c9da43d.png)
![brainstorm](https://cloud.githubusercontent.com/assets/18429104/15223625/0bd5fd7c-183b-11e6-9cfa-ee3daa192333.png)

## in context 
![screenshot 2016-05-12 12 08 46](https://cloud.githubusercontent.com/assets/18429104/15223636/1b82014e-183b-11e6-8af2-b1e0928310b5.png)
![screenshot 2016-05-12 12 09 01](https://cloud.githubusercontent.com/assets/18429104/15223639/1b8689ee-183b-11e6-8dca-3bad9827de9d.png)
![screenshot 2016-05-12 12 09 10](https://cloud.githubusercontent.com/assets/18429104/15223637/1b85eea8-183b-11e6-9e98-ff40b68e11c8.png)
![screenshot 2016-05-12 12 09 49](https://cloud.githubusercontent.com/assets/18429104/15223638/1b861cc0-183b-11e6-9b79-9a564f88b0f9.png)

**Comment by piamancini** [comment]
hi @erickrico they seem a bit cluttered to me. What would you like to see in the HackFundMx collective for example? What would make you back an os collective?

**Comment by erickrico** [comment]
ideally i would like to see the community itself , personally in projects that ask for support and dont take the attention to brand their site with a cool video or logo ( in sites like kickstarter/indiegogo) i feel like they dont really care that much,   i do know most opensource projects will have a hard time getting their cover photos since there isnt a community to display, let me try something cleaner but between the same concept of people working

**Comment by xdamman** [comment]
For example, for my collective https://opencollective.com/tipbox I'd have wanted to show a map of the world with the avatar of the 5 contributors:
- Mark and myself in San Francisco
- Thomas in Belgium
- montogeek in Colombia
- evil rabbit in Argentina

![](http://cdn0.dailydot.com/cache/4c/d6/4cd6332435e7a8cd5d3851e4b52ea8f3.jpg)

That would have highlighted that we are a distributed community of humans.

**Comment by erickrico** [comment]
hey there, check this one out 

## in context
![screenshot 2016-05-14 13 05 12](https://cloud.githubusercontent.com/assets/18429104/15269958/b7d26c60-19d4-11e6-9cf1-05ae0a16dafb.png)


## background
![nodes](https://cloud.githubusercontent.com/assets/18429104/15269961/cedf8046-19d4-11e6-874c-fb5d0129e86d.png)

**Comment by xdamman** [comment]
I don't think it's there yet but it will do for now. We need to move on. 

I just don't like that particular logo. It looks too much like a horseshoe imo.
