### ISSUE TITLE
Showing Agreements within an expense

### ISSUE THREAD

**Issue by gustavlrsn** [opencollective/opencollective#6705]
Part of https://github.com/opencollective/opencollective/issues/4894

- [x] Showing agreements within an expense
  - [ ] ~~Modal to view agreements associated to a Collective from the expense block~~
    - ~~possibly integrated with the attachments preview?~~
  - [ ] ~~Integrating in the "expense block" in list of expenses (design review - where/how to show this effectively, how does this relate to the "sidebar full expense view")~~
  - [ ] ~~full expense details~~

Edit by @Betree: designed opted-in for a simple hyperlink with a count.

[Design in Figma](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?type=design&node-id=20700-98587&t=dPfNXocq0HvOri6y-0)

![image](https://github.com/opencollective/opencollective/assets/1556356/7dd1e856-63ca-4fe3-9655-b5dbd586a916)

**Comment by shannondwray** [comment]
Duplication? https://github.com/opencollective/opencollective/issues/6831
