### ISSUE TITLE
JWT expired without being logged out

### ISSUE THREAD

**Issue by amfriedman** [opencollective/opencollective#6706]
**Describe the bug**

(Side note, second bug: Most pages I navigate to, there is a "Network Error" and I need to refresh to successfully load the page.)

Worst of all, when trying to create a new account, or even submitting this report over the normal contact form, there is a notice in the bottom-right corner that says "ERROR: jwt expired", and it blocks me from submitting the form.

**To Reproduce**
1. Go to "Create New Account" or "Contact Us"
2. Fill out the form.
3. Click "Submit"
4. Error occurs and I am blocked.

**Expected behavior**
The form should submit without error.

**Screenshots**
![Screenshot 2023-04-26 at 3 22 21 PM](https://user-images.githubusercontent.com/498497/234682136-3dfdf468-1c01-4376-a0ad-b078ec3eca0a.png)

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.3
 - Browser: Chrome 
 - Version: 112

**Additional context**
None.

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
@amfriedman thank you for reporting this bug. We got a few similar reports on Slack, but were not able to reproduce yet.

Tokens are normally renewed when they can be, and if not the system logs you out. It seems that, in some cases, we fail to do the latest.

Can you confirm that refreshing the page doesn't solve the issue for you?

**Comment by Betree** [comment]
I was able to reproduce, working on a fix
