### ISSUE TITLE
Pricing page: broken layout in different languages

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6709]
Fixed width should be avoided.

![image](https://user-images.githubusercontent.com/1556356/235204893-6ba5d658-a19d-41e9-bcd4-8fe90d3ec073.png)

**Comment by d-ivashchuk** [comment]
Just stumbled on this. @Betree if you want to avoid such issues in the future with oss contributions - let me help you to set up lost-pixel.com

would be absolutely free to use for opencollective, you have a great mission!

**Comment by Harish-b-03** [comment]
Helloo Everyone :wave:, Heyyy @Betree :grin: 

I would like to work on this issue, can i?

So, I am new to this project and had this project set up locally in my machine.

I got this two solutions:

1. removing the `WhiteSpace` prop, which will set `white-space` attribute to `normal` thus solving this issue. Like this:

![image](https://user-images.githubusercontent.com/69810789/235417414-2e258852-72a1-400d-be01-efe93b4d94ab.png)

Disadvantages:

- have to remove all the occurence of `WhiteSpace` prop (but possible)
- height of the button increases according to its content, this might be an undesired behaviour
- not a global solution but versatile ( as this change is not attached to the component, everytime we should avoid using `whitespace` prop )

2. truncating the line (using `text-overflow: ellipsis;  overflow: hidden;  white-space: nowrap;` css properties)

![image](https://user-images.githubusercontent.com/69810789/235417663-bc9465fe-5a63-477c-b6d8-229cbbc8f2c7.png)

Disadvantages: 

- this might reduce the readability
- will be affected if any prop alters the three css property

Advantage: This will be a global one

@Betree Please let me know if there is anyother better solution and what can i do now?

Thank you :grinning:

**Comment by Betree** [comment]
@Harish-b-03 Thanks for the research and detailed explanations! I would like to suggest another solution: remove the fixed width, eventually replacing it by `min-width`. Fixed widths on buttons will always cause this kind of issues and should be avoided.

![Peek 2023-05-02 08-11](https://user-images.githubusercontent.com/1556356/235592135-50448acb-62c9-46d9-9bba-ac05a6c26c6a.gif)

**Comment by Betree** [comment]
> Just stumbled on this. @Betree if you want to avoid such issues in the future with oss contributions - let me help you to set up [lost-pixel.com](https://lost-pixel.com)
> 
> would be absolutely free to use for opencollective, you have a great mission!

@d-ivashchuk Thanks for the offer! I'll pass it on to the rest of the team :slightly_smiling_face:

**Comment by d-ivashchuk** [comment]
@Betree absolutely, if you will need any assistance - always happy to help!

**Comment by Harish-b-03** [comment]
Heyyy @Betree ,

I have added `min-width: max-content;` and this fixed the issue

Example 1:

- Before

![image](https://user-images.githubusercontent.com/69810789/236618616-c933b4be-c109-4a2d-bf7d-939d1cc697a0.png)

- After Change

![image](https://user-images.githubusercontent.com/69810789/236618575-950675ff-5b21-46a6-8ba5-56e1c17499e7.png)

Example 2:

- Before

![image](https://user-images.githubusercontent.com/69810789/236618818-6dc02848-fbfb-4fef-8a78-c71df804f15b.png)

- After Change

![image](https://user-images.githubusercontent.com/69810789/236618844-680a01af-b296-4f6f-9538-75ea9d2cc2ec.png)


Please let me know your thoughts and suggestions. Can i submit a PR?

Sorry for the delay :sweat_smile: 

Thank you :grin:

**Comment by Betree** [comment]
@Harish-b-03 Sure! This looks like a good solution; feel free to submit a PR and assign me to the review

**Comment by Harish-b-03** [comment]
Yeah sure :+1: . Thank you very much

**Comment by Harish-b-03** [comment]
Heyyy @Betree 

when I tried to submit a PR, I realized that I was about to submit a PR to `opencollective/opencollective-frontend` repo not `opencollective/opencollective` repo.

Is this what I have to do? can you please confirm it? I am new to this project :sweat_smile:

**Comment by Betree** [comment]
> Heyyy @Betree 
> 
> when I tried to submit a PR, I realized that I was about to submit a PR to `opencollective/opencollective-frontend` repo not `opencollective/opencollective` repo.
> 
> Is this what I have to do? can you please confirm it? I am new to this project :sweat_smile: 

opencollective/opencollective-frontend is the right repo, but you have to fork it and submit the PR from your fork
