### ISSUE TITLE
ux: users think updating cc details in profile updates the subscription

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#671]
Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by xdamman** [comment]
I will remove the "remove" button if there are active subscriptions:
![](https://cl.ly/3l1C0o2n1T1f/Screen%20Shot%202017-11-21%20at%207.13.54%20PM.png)
