### ISSUE TITLE
Cannot add .webp images to event descriptions

### ISSUE THREAD

**Issue by jdaviescoates** [opencollective/opencollective#6716]
**Describe the bug**
Cannot add .webp images to event descriptions.

**To Reproduce**
1. Go to an event
2. Click on edit button in description section
3. Hit the add image button
4. Attempt to add  a .webp image
5. It appears to upload but then no image is displayed.

**Expected behavior**
I expect to be able to add any image file.

**Comment by Aijeyomah** [comment]
@Betree @jdaviescoates  I'm interested in working on this issue. Would it be possible to assign it to me? Thanks!

**Comment by Aijeyomah** [comment]
@Betree Here's the [PR](https://github.com/opencollective/opencollective-api/pull/8897) to resolve this issue in the API. I also added an additional note.
