### ISSUE TITLE
id 8975 host of id8974 is serving a 500

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#673]
There were two host rows. Deleted one. 
Also the host collective id was wrong, fixed it. 
still seeing a 500 

High priority, it's blocking a host from connecting stripe

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by piamancini** [comment]
it has to do with some strings that got moved around in this commit: https://github.com/opencollective/frontend/commit/2e7bbe2e08c786d27d37606fb2a5a629e45710d9

**Comment by xdamman** [comment]
How to reproduce this? Can you add a URL? That makes my life easier.

**Comment by xdamman** [comment]
Got it https://opencollective.com/finance6 (please provide this next time)

**Comment by xdamman** [comment]
That's because `isHost` is false for that Collective because it doesn't have a Stripe Account connected yet. I'll fix the error in a few but before we assign a collective to a Host, we should make sure that the Host Organization or Host User has connected a Stripe Account first.

**Comment by piamancini** [comment]
hmmm is this a new change? because before it produced an error saying that the host didn't have a payment method. 
I wonder what the best path for this is on the self-serve flow.

**Comment by piamancini** [comment]
reopening since the fix broke something else. 
The collective hosted on opencollective.com/finance6 is now broken 
see https://opencollective.com/weco

**Comment by xdamman** [comment]
There is no admin for that collective (weco). Can you add at least one admin?

**Comment by piamancini** [comment]
same problem, now with an admin. hosts should be admins though?

**Comment by xdamman** [comment]
Fixed. The issue was that that collective had a stripe account connected and was therefore considered as a host.
