### ISSUE TITLE
Add a simple ticket number(s) or order number(s) or similar to event tickets emails and PDF receipts

### ISSUE THREAD

**Issue by jdaviescoates** [opencollective/opencollective#6731]
## Who is your user?
People who purchase a ticket for an event
People who sell tickets for events

## What are they trying to achieve?

_When selling tickets for event, I want to have a simple way of checking people in, so I can quickly and efficiently manage the door for the event_

## How are they currently doing this?
 

At present there is no good/ easy way to do this.

The only thing we can realistically do is ask people for their email address. We can't even ask for names as some people just check out as Guest. People often have multiple email addresses they use for different purposes. And people also order multiple tickets for themselves and their friends and their friends may not know which email address the ticket purchaser used to buy their ticket.

## How well understood is this problem?

I've sold over 100 tickets for an event happening on Saturday and I'm quite stressed about how we're going to manage this.

**Comment by jdaviescoates** [comment]
Related: #6695 have basic details about the event included on the PDF receipt would help with this as then we could at least ask people to show their PDF receipt.

**Comment by jdaviescoates** [comment]
It would also be good if the number of tickets purchased was displayed, ideally with a Ticket Number associated with each ticket. That way people who purchase multiple tickets for themselves and their friends could share the PDF receipt with their friends and tell their friends which Ticket Number to quote on the door

**Comment by Betree** [comment]
There is this ID in the receipt that you can check against the API (I can provide a query if you want to explore this, lmk). But there was [a request](https://github.com/opencollective/opencollective/issues/6571) to instead show the numerical ID in there; since it's the one we currently show in the interface I would like us to go in this direction.

![image](https://github.com/opencollective/opencollective/assets/1556356/94430164-1311-433a-97ac-1a910900fc7a)

**Comment by Betree** [comment]
In all cases @jdaviescoates, something you can do is to export the list of transactions before the event, and then check the ID from the exported CSV (it's included in there).

**Comment by jdaviescoates** [comment]
> In all cases @jdaviescoates, something you can do is to export the list of transactions before the event, and then check the ID from the exported CSV (it's included in there).

Yeah, this is what we're planning to do. 

> There is this ID in the receipt that you can check against the API (I can provide a query if you want to explore this, lmk). But there was [a request](https://github.com/opencollective/opencollective/issues/6571) to instead show the numerical ID in there; since it's the one we currently show in the interface, I would like us to go in this direction.
> 
> The alternative is to surface the string ID in the interface.
> 
> ![image](https://user-images.githubusercontent.com/1556356/237093907-94430164-1311-433a-97ac-1a910900fc7a.png)

Yeah, it's just that ID is not very user friendly. It's way too long and complex. No one is going to read that out! The addition of much more simple order number as per that request in #6571 would really help to improve things.

**Comment by Re1da** [comment]
Re1da
