### ISSUE TITLE
Explore a way to store fraud scores for collectives

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6737]
As part of https://github.com/opencollective/opencollective/issues/6674, we want to cache some stats on fraudulent contributions hitting a collective. That information will be used to generate expense security check warnings, but it will also be helpful for us to build a dashboard that we can monitor.

During the call, we discuss having multiple fraud scores like `overallFraudScore`, `monthlyFraudScore`, `weeklyFraudScore` and dailyFraudScore` to provide more granular information.

This issue still needs further research and discussion before we can act on it.

**Comment by kewitz** [comment]
Specifications:
- [ ] Write a query that calculates error rates for different time windows.
- [ ] Create a materialized view based on that query.
- [ ] Refresh the query every hour.
