### ISSUE TITLE
Missing members in members api

### ISSUE THREAD

**Issue by beta-ziliani** [opencollective/opencollective#6742]
As of recent, several members are not listed in the `members/all.json` file.

**To Reproduce**
1. Go to https://opencollective.com/crystal-lang/members/all.json
2. Note that `Concentric` is not listed.
3. Go to https://opencollective.com/concentric and note how it contributed to crystal-lang.

**Expected behavior**
I expect all the contributers of crystal-lang to be listed in `members/all.json`.

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by znarf** [comment]
This was tentatively fixed in https://github.com/opencollective/opencollective-rest/pull/482 but the problems still seems here.

**Comment by Betree** [comment]
@beta-ziliani Fix deployed!

**Comment by beta-ziliani** [comment]
Thank you guys soooo much!
