### ISSUE TITLE
Prevent people to enter payment processor fee >= expense.amount

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#6744]
People are making the mistake to enter the expense amount in the payment processor fee input.

We're seeing it in the ledger and this is causing issues. This should be prevented.

Also, on this screen, it looks weird that the "total amount paid" is pre-populated.

<img width="410" alt="Screenshot 2023-05-11 at 17 32 18" src="https://github.com/opencollective/opencollective/assets/806/3119a483-d8ee-4d8b-90ae-24583fb787b4">

**Comment by znarf** [comment]
According to 

```
SELECT "ExpenseId", "TransactionGroup", MAX("createdAt")
FROM "Transactions"
WHERE "kind" = 'EXPENSE' AND "type" = 'DEBIT' AND "deletedAt" IS NULL GROUP BY "TransactionGroup", "ExpenseId" HAVING COUNT(*) = 2
```

This issue is especially happening in 2023 so it's certainly linked to the second aspect mentioned and a regression.

**Comment by Betree** [comment]
> Also, on this screen, it looks weird that the "total amount paid" is pre-populated.
> <img alt="Screenshot 2023-05-11 at 17 32 18" width="410" src="https://user-images.githubusercontent.com/806/237740199-3119a483-d8ee-4d8b-90ae-24583fb787b4.png">

The `0.00` is a placeholder; the input is not pre-populated. Trying to submit in this state will trigger a validation error:
![image](https://github.com/opencollective/opencollective/assets/1556356/f71d34c9-8871-4c24-8a7b-849fb618c33f)

If this is a typo and the intent was to say that the input is **not** pre-populated (with the expense amount) then I agree we can pre-fill it.
