### ISSUE TITLE
A bug with paying expenses with Wise "you need 925 GBP and you currently have 925 GBP" :thinking: 

### ISSUE THREAD

**Issue by jdaviescoates** [opencollective/opencollective#6748]
**Describe the bug**

As you can see from this screenshot when trying to add this expense I got an error message saying:

"you need 925 GBP and you currently have 925 GBP" :thinking: 

![Screenshot from 2023-05-12 13-40-30](https://github.com/opencollective/opencollective/assets/2113743/0bc4c4fe-e422-4a1c-9fff-a9a07cea1a69)

Something is not right.

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
cc @kewitz

**Comment by jdaviescoates** [comment]
This must be a recently introduced bug because I never had this problem before paying expenses with the exact right amount in Wise. Be great to get it fixed so I can pay expenses again.

**Comment by jdaviescoates** [comment]
@kewitz @Betree  There seems to have been a regression as I just hit this issue again.

![image](https://github.com/opencollective/opencollective/assets/2113743/b336a34b-d4c9-4659-9d46-df55cd587556)

**Comment by Betree** [comment]
@jdaviescoates we've deployed a fix. Could you try that again?

**Comment by jdaviescoates** [comment]
Thanks @Betree - I needed to pay the money out in the interim and so I'd had just transferred another 1p into our Wise account to get around the issue, but yes, next time I pay an expense I shall report back (I generally transfer exactly what is needed into Wise and then try pay them).
