### ISSUE TITLE
Update URL when opening expense in drawer

### ISSUE THREAD

**Issue by gustavlrsn** [opencollective/opencollective#6752]
Update the URL when opening an expense in the drawer, both to enable using browser history to go back/forth and sharing of that page.

### Proposed solution
- Adding a `openExpenseId` query parameter to the current URL
- Add a redirect to the expense page itself if the user is lacking permission to view the page it was linked from

**Comment by iamronen** [comment]
@gustavlrsn a note here to reflect that we would like to end up with one URL that is able to redirect based on logged-in/out & permissions. The same  URL should take:
 - a logged-in fiscal host admin to the expense in the fiscal host workspace 
 - a logged-in collective admin to the expense in the collective workspace
 - a logged-in expense submitter to their individual workspace to the expense.
 - other logged-in users (not belonging to the context of this expense) to the public expense
 - a logged-out user to the public expense

**Comment by Betree** [comment]
Related: https://github.com/opencollective/opencollective/issues/6758

**Comment by alanna** [comment]
I have not fully internalised the vision for the workspace UX so it's hard for me to conceptualise, but personally I feel like linking to the bare expense page in all cases is good enough, and introducing the complexity of all the different drawer states by user context is not worth it if it will significantly degrade loading times. 

However, I'm very used to the old design, and more MVP solutions, so I might not be the best model here. If users become very used to operating within the workspace context and are thrown out of that, maybe it will be disorienting and therefore worth the increased load times. I look at expenses in sooo may contexts it would be impossible for the system to correctly guess what main page I'd want to see it in a drawer from (this expense in the context of all the host's expense, only that Collective's expenses, in a list of expenses submitted by that user, etc etc) — but the vast majority of users have a much more limited context set so it's likely to be correct as described above.
