### ISSUE TITLE
Add logo and link of non financial contributions/support

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6759]
## Who is your user?
Collective admin

## What are they trying to achieve?
Want to pay honour to a contributor who has provided non-financial support in the way of time/code

## How are they currently doing this?
Suggested to add this in the about section 

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by alanna** [comment]
#1895

**Comment by shannondwray** [comment]
Duplicate
