### ISSUE TITLE
Deprecate bluebird in the API

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6764]
As per Bluebird's [GitHub](https://github.com/petkaantonov/bluebird): 

> Please use native promises instead if at all possible. Native Promises have been stable in Node.js and browsers for around 6 years now and they have been fast for around 3. Bluebird still offers some useful utility methods and you can use it - but please consider native promises first.
> 
> This is a good thing, the people working on Bluebird and promises have been able to help incorporate most of the useful things from Bluebird into JavaScript itself and platforms/engines. There are still missing things (.map/.filter are on their way with the iteration helpers proposal and async iterators!).
> 
> If there is a feature that keeps you using bluebird. Please let us know so we can try and upstream it :)
> 
> Currently - it is only recommended to use Bluebird if you need to support old browsers or EoL Node.js or as an intermediate step to use warnings/monitoring to find bugs.

Bluebird also messes with Typescript, since we usually import it as `Promise` (replacing the default).

**Comment by Betree** [comment]
Related: https://github.com/opencollective/opencollective/issues/1432

**Comment by kewitz** [comment]
Started clearing this. There are a few places where map concurrency is not important and is being replaced with `Promise.all(array.map(fn))` but there are places where it is crucial. I'll use a `p-` helper lib in these cases.
