### ISSUE TITLE
No link to main Collective page from workspace/settings

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6767]
## Who is your user?
Admin

## What are they trying to achieve?
Jump from settings/workspace to the main page of the Collective/org. Often you want to see the main page after changing a setting, or see some info or take an action on the main page. The only link is to the main Open Collective homepage, which seems like a less likely place the user would want to go from here.

## How are they currently doing this?
It used to be that the logo/name of the Collective you were in the settings section for was shown on the top left corner. But now that's been changed to a dropdown menu of all your Collectives. This menu is useful, but it means the link back to the page is gone and there doesn't seem to be another option to get there.

<img width="1318" alt="Screen Shot 2023-05-22 at 11 52 56 AM" src="https://github.com/opencollective/opencollective/assets/5498878/53a5d1ad-500b-4c0a-830e-3bac6bb26520">

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [x] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment]
Also shared in https://github.com/opencollective/opencollective/issues/6646#issuecomment-1523312258

Note that this "Workspace" view is not released publicly yet, only for the core team.

**Comment by Betree** [comment]
Resolved in https://github.com/opencollective/opencollective-frontend/pull/9169

![image](https://github.com/opencollective/opencollective/assets/1556356/7653045e-bc7f-45ad-ba11-5ae4cf83db47)
