### ISSUE TITLE
trying to back Open Collective, Inc

### ISSUE THREAD

**Issue by rdela** [opencollective/opencollective#677]
URL: https://opencollective.com/opencollectiveinc

Logged in as: ricky

Error message:
```
An error occured 😳. The order didn't go through. Please try again in a few.: Error: GraphQL error: Must authenticate as a connected account to be able to use customer parameter. See https://stripe.com/docs/api#create_card_token for more details.
```

Expected result: 
Become a backer.

Browser:
Chrome

Screenshots:
![opencollectiveinc-error](https://user-images.githubusercontent.com/74381/33086501-99c4bd9e-ce9c-11e7-8d64-05fc4846bb60.jpg)

`/subscriptions` show each attempt as `(Cancelled)`
<https://user-images.githubusercontent.com/74381/33086598-dd8288e0-ce9c-11e7-9612-371890bcb782.jpg>

Maybe you want everyone to back https://opencollective.com/opencollective ? If so need to disable backers on Open Collective, Inc.

**Comment by asood123** [comment]
I renamed /opencollectiveinc to random slug. Instead, let's redirect them to /opencollective

**Comment by rdela** [comment]
I am seeing
```
Not Found

¯\_(ツ)_/¯
```

problem with redirect?

**Comment by asood123** [comment]
You aren't able to visit https://opencollective.com/opencollective?

**Comment by rdela** [comment]
Sorry unclear meant
https://opencollective.com/opencollectiveinc

Is that supposed to redirect now?

**Comment by asood123** [comment]
No, we aren't using /opencollectiveinc. Please use opencollective.com/opencollective as a way to donate.
