### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by Miragide** [opencollective/opencollective#6773]
Hello,
CSV export not working here:
https://opencollective.com/captainfact_io/admin/export
![image](https://github.com/opencollective/opencollective/assets/15331478/7d04381c-32ff-4f0c-83b8-ff607be1eb2d)
![image](https://github.com/opencollective/opencollective/assets/15331478/c14f5398-285f-489d-8859-876831fc8996)
:( :( :(

**Comment by Betree** [comment]
Hi @Miragide, seems fine on my end. Maybe try to decode with UTF8?

![image](https://github.com/opencollective/opencollective/assets/1556356/0740df21-223e-4607-bca8-48fa48ee7461)

**Comment by Miragide** [comment]
Merci Betree
