### ISSUE TITLE
Remove Chromatic and Introduce Lost Pixel for Visual Testing

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6779]
Related to the thread, https://opencollective.slack.com/archives/C0471HKNW7J/p1683008787902999. 

Although we've introduced Chromatic (https://github.com/opencollective/opencollective/issues/6487) we only have limited credits which makes it difficult to be built for every UI change. Currently we have a workflow trigger that needs to be done manually by the developer in order for the visual testing snapshots to be built. It's rare that we do this an hence we miss out on visual testing completely. 

Lost Pixel (https://lost-pixel.com/) seems to be free for Open Source projects and therefore we should remove Chromatic and integrate Lost Pixel instead.

**Comment by SudharakaP** [comment]
Next Steps: 

- [] Ask Lost Pixel for OSS license
- [] Cleanup GitHub secrets related to Chromatic

**Comment by d-ivashchuk** [comment]
Hey @SudharakaP! I am happy to support you with anything you might need to get successful with lost pixel! If you are up to this I would be happy to create a dedicated channel on discord or open shared slack channel 🙏🏼

**Comment by SudharakaP** [comment]
> Hey @SudharakaP! I am happy to support you with anything you might need to get successful with lost pixel! If you are up to this I would be happy to create a dedicated channel on discord or open shared slack channel 🙏🏼

Thanks much for the offer. For sure if we need any help on this as we move forward I'll be sure to tag you. 😃
