### ISSUE TITLE
Order list of profiles in expense flow

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6780]
When selecting a payee when submitting an expense, the list does not seem to have any particular order, making it harder to use:

<img width="344" alt="Screen Shot 2023-05-29 at 9 00 36 AM" src="https://github.com/opencollective/opencollective/assets/5498878/c4ca510f-fabc-4193-acbf-d2ba69345ebb">

Alternatively, the list within workspace is alphebetized, which is much nicer:
<img width="282" alt="Screen Shot 2023-05-29 at 9 11 21 AM" src="https://github.com/opencollective/opencollective/assets/5498878/9dae2fee-842e-4f22-9b19-e021e4819d3e">

Alphabetized is probably the best way, but we could also consider putting most used or most recently used at the top. For example, I submit 90% of expense with a certain profile, but it's buried in a big list.

**Comment by Betree** [comment]
I thought this was already the case but you're right, it's not. Pushing a quick fix to apply the same logic as the user menu (sort by slug ascending).
