### ISSUE TITLE
Duplicate GraphQL v2 types for update collection

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6785]
- `UpdateCollection` was initially added in https://github.com/opencollective/opencollective-api/pull/4786/files#diff-e77e8373188895f5da60815ac58196255993fa8106658c308ce0b50462078adb
- Two years later, https://github.com/opencollective/opencollective-api/pull/8297/files#diff-bb5e2d8a42b54606434084a5f2e9ff81ba25631c7c48151adedc059d4750dd14 introduced an `UpdatesCollection` type

We should get rid of this second type as it does not match the pattern we have for other collections (`SingularCollection`).

This could be a breaking change depending on how people are using it, so we should announce it on https://opencollective.com/engineering/updates.

**Comment by gustavlrsn** [comment]
Amazed at my ability to miss that existing type.. 

I know https://github.com/opencollective/discover is using the updates root query, but does not reference the type name itself so wouldn't break that at least when switching over.
