### ISSUE TITLE
Update core Frontend dependencies to their latest version

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#6794]
According to our RFCs [001](https://github.com/opencollective/opencollective/blob/main/rfcs/001-cutting-edge.md) and [003](https://github.com/opencollective/opencollective/blob/main/rfcs/003-next-js.md), we aim to use the latest versions of our core dependencies: Next.js, React, Babel and Webpack.

We're currently late applying the [latest Next.js](https://github.com/opencollective/opencollective-frontend/pull/8326) update and [latest React update](https://github.com/opencollective/opencollective-frontend/pull/7631) and it's time to give it proper official attention.

**Comment by Betree** [comment]
This week:
- [ ] Give some attention to https://github.com/opencollective/opencollective-frontend/pull/8326

**Comment by Betree** [comment]
This week:
- [ ] Merge & release https://github.com/opencollective/opencollective-frontend/pull/8326
- [ ] Monitor Sentry & support, be ready to iterate on regressions or rollback

**Comment by Betree** [comment]
We updated everything we wanted to update here, no regression detected still. Closing!
