### ISSUE TITLE
Research and select a headless component library

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6797]
RFC draft: https://github.com/opencollective/opencollective/pull/6750

https://github.com/opencollective/opencollective/blob/rfc/headless-component-library/rfcs/013-introduce-headless-components-library.md

## Affected projects

- [Frontend](https://github.com/opencollective/opencollective-frontend)
- [Frontend template](https://github.com/opencollective/opencollective-frontend-template) (since it depends on Frontend components)

## Motivation

- Reduce the load on the engineering team by re-using components already built with UX/accessibility best practices
- Build new UI more efficiently, through a library of components that are already tested and documented
- Prepare the ground for introducing a [CSS library](https://github.com/opencollective/opencollective/pull/6694)

**Comment by gustavlrsn** [comment]
Added some data in the table. Based on that and some of testing and experimenting with it I'd be ready to advocate for picking Radix UI.

**Comment by Betree** [comment]
This week:
- [ ] Try to complete the libraries comparison table

**Comment by Betree** [comment]
This week:
- [ ] Have a call with the rest of the engineering team to present our conclusions, settle on a decision
- [ ] If adopted, merge RFC
