### ISSUE TITLE
Finalize Tailwind study and RFC

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#6798]
We're currently evaluating Tailwind as an alternative to styled-components for future work. For developer experience, simplicity and flexibility.

The problem is the transition as this can be messy to use the two frameworks at the same time and there is no possible automation. The transition could take many years and may even never be done for some edge cases components that have no attention.

RFC: https://github.com/opencollective/opencollective/pull/6694

https://github.com/opencollective/opencollective/blob/3d09e807748638e8d380fe7edabbf9544d60f1b9/rfcs/013-utility-first-css-framework.md

Until this project is completed, we should not plan on integrating Tailwind in the codebase. For now, all projects should keeps being implemented with our current tooling. This RFC and discussion should not block any ongoing work.

**Comment by Betree** [comment]
For this week:
- [ ] Add the performance analysis to Tailwind RFC (@Betree)

**Comment by Betree** [comment]
Added an [appendix](https://github.com/opencollective/opencollective/blob/utility-first-rfc/rfcs/appendix/013/styled-components-performance.md) to the [Tailwind RFC](https://github.com/opencollective/opencollective/blob/utility-first-rfc/rfcs/013-utility-first-css-framework.md#performance) about styled-components performance.

In short, we can expect that a page transitioning to Tailwind will have 5-10% faster time to first render. For pages with lot of re-renders (contribution flow, expense form, etc), we could expect them to be 10-20% more responsive.

**Comment by Betree** [comment]
For this week:
- [ ] Finilize RFC (see feedback)
- [ ] Seek team feedback & merge if there's an agreement

**Comment by gustavlrsn** [comment]
@BenJam Tailwind is merged, closing this
