### ISSUE TITLE
Clarify  the “platform tip” in the contribution flow and transform it into opt-in.

### ISSUE THREAD

**Issue by iamronen** [opencollective/opencollective#6799]
## User story 
> When users decide to contribute to collectives using the platform, a “tip” is added to support the Open Collective platform. This can be reduced, increased or removed, but the default is currently 15%. Some users say that it is not sufficiently clear that the tip is being added, that it is optional, and that it can be adjusted/removed.

> Furthermore, there may be some confusion about the tip going to the platform, rather than the fiscal host (particularly if the naming is similar).

### Part1

Transform the platform tip from opt-out to opt-in.
 - Requiring the user to select “yes” or “no” (or some other opt-in) to add a platform tip, so they are at least aware it is happening
 - Clarifying the tip as opt-in in the itemised Contribution Summary, even if it’s as simple as adding “(optional)” after the line item

```
Suggested wording:

Support our platform

Groups across the world use our platform every day to raise and manage money. Tips from generous people like you help us make improvements and add new features.

Do you want to add a tip?

No thanks | 10% | 15% | 20% | Other

Thanks for your help.
```

### Part 2 

Clarify (with both copy and UX) that the platform tip is separate from the conversation and is for the maintenance of the Open Collective PLATFORM (remember that our fiscal hosts are also have the word Open and/or Collective in them).

- Ensure that people are not glossing over this tip when they’re rushing to pay
- Separating the Platform Tip into a separate box to the Contribution Details.
- Amending the platform tip drop down box to a similar set-up as the Contribution Frequency and Contribution Amount, with options clearly presented
- Distinguishing between host/collective and platform, by making the wording for the “tips from contributors like you...” copy clearer and sharing more about what it will be used for
- Adding a section to the FAQ clarifying that the tip is optional, variable and going to the platform rather than collective/fiscal host

### Part 3:
When the contribution flow is activated through an embedded URL do NOT include platform tips (since there was not explicit opt-in). This may be refined in the future by changing the changing the sequence of the contribution flow and adding platform tips as a separate and later step, however this is NOT in the scope of this pitch. #6398  

  <summary>Triage Template (team only)</summary>

  P1 high frequency, high impact

**Comment by Betree** [comment]
Related: https://github.com/opencollective/opencollective/issues/6377

**Comment by iamronen** [comment]
@gusaus changes to platform-tips generate substantial ripples.
The opt-in opt-out is also a sensitive conversation (taking place right now).
This issue is a limited scope project to clarify how platform tips (as they currently are) are communicated in the contribution flow.
The scope of this project does not include anything regarding collective admin choices. Such changes may be (re)considered in the future.

**Comment by Memo-Es** [comment]
This week
 - [ ] Set up the prototypes/mockups and a plan to do A/B testing

**Comment by Memo-Es** [comment]
This week

 - [ ] Wording proposal along with @jpjhill 
 - [ ] Push changes to production
 - [ ] Set up a testing path

**Comment by Memo-Es** [comment]
### Week 6 goals

 - [ ] Iterate wording proposal @jpjhill 
 - [ ] Push changes to production
 - [ ] Set up a testing path

**Comment by BenJam** [comment]
@hdiniz will swoop in like Batman later this week to implement the selected changes. @Memo-Es to highlight the selected proposal from above.

**Comment by Memo-Es** [comment]
[Production-ready file](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?type=design&node-id=21058%3A123316&mode=dev)
@hdiniz

**Comment by Betree** [comment]
To make sure, since we're close to releasing this: is someone actively looking at the metrics to analyze the impact of these changes and suggest actions if we notice something unusual?

**Comment by hdiniz** [comment]
This week

- [ ] Considering AB test approach to measure impact
- [ ] Preparing metrics for release

**Comment by hdiniz** [comment]
Last week

- [x] New platform tip component deployed. 
- [x] Contribution funnel added to Plausible.

We have added a contribution funnel to Plausible with properties measuring the use of platform tips, but unfortunately, there is a currently a [limitation in Plausible](https://github.com/plausible/analytics/discussions/846) that prevents breaking down events by property in the dashboard and API data. In order to get AB test results out of this experiment we will need to record this data in our Orders table.

This week

- [ ] Add A/B test data to orders table
