### ISSUE TITLE
Feedback for event email

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#680]
**Feedback from Nenad:**

> Quick feedback about confirmation email below... two possible tweaks: 
> 1) It is probably better not to include location in the first sentence (at least for us), but this is where link to event could be included, for example like this: "We are excited that you'll be joining us at Exploring REconomy Ecosystem #2 on December 7th 2017 at 4:00pm, details here <link to event page>." Also, what could be useful here is some kind of "Add to calendar" function? 
> 
> 2) In third sentence I would expect to see link to open collective page, NOT to event page. 

![screen shot 2017-11-22 at 8 34 57 pm](https://user-images.githubusercontent.com/30665166/33157035-a736c1a6-cfc4-11e7-8b6e-25199151498c.png)

**Comment by piamancini** [comment]
events has a bunch of issues opened. Adding a label for when someone takes the task of working through them.

**Comment by znarf** [comment]
Closed because of low activity.
