### ISSUE TITLE
Banner.js - Refused to load the stylesheet because it violates the following Content Security Policy directive

### ISSUE THREAD

**Issue by VaclavElias** [opencollective/opencollective#6811]
**Describe the bug**
I am getting these errors in chrome

```
banner.html:68 Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Lato:400,700,900' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline' https://hcaptcha.com https://*.hcaptcha.com". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.
```

I am using this

```html
<div class="col-12 text-center">
    <h2>All Stride Sponsors</h2>
    <script src="https://opencollective.com/stride3d/banner.js"></script>
    <h3>Additional Sponsors</h3>
    <p>Thank you to all our additional sponsors who have contributed to the Stride project.</p>
    <p>David Jeske</p>
</div>
```

**To Reproduce**
1. Go to https://stride-web-next2.azurewebsites.net/sponsor/ or directly to https://opencollective.com/stride3d/banner.html
2. Open Chrome Console
3. Refresh the page and see the errors

**Expected behavior**
There shouldn't be error in the console

**Screenshots**
![image](https://github.com/opencollective/opencollective/assets/4528464/06f5f392-5896-4dd9-9bfd-82199e2907f1)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome, Edge
 - Version: Version 114.0.5735.110 (Official Build) (64-bit)

**Additional context**

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
Thanks for the report @VaclavElias! It must have been broken for quite some time now; these CSP rules were added more than 2 years ago.

We don't use Google Fonts in the rest of our code; we self-host them for privacy reasons. It looks like the widget has a fallback to `Inter`, our main font. So I'd suggest we just remove the Google font import.

**Comment by VaclavElias** [comment]
Thank you 🙂

**Comment by VaclavElias** [comment]
@Betree , when is it going to be published?

**Comment by Betree** [comment]
@VaclavElias It's deployed

**Comment by VaclavElias** [comment]
Thank you, I have tested and it is resolved 🙂🙏
