### ISSUE TITLE
Add option to filter virtual card expenses that are missing receipts

### ISSUE THREAD

**Issue by hdiniz** [opencollective/opencollective#6816]
Part of https://github.com/opencollective/opencollective/issues/4312

- [ ] Add API option to filter by expenses missing receipt.
- [ ] Add frontend options to filter for a virtual card expense (type=charge) where receipt is missing

**Comment by Betree** [comment]
@hdiniz I created a follow-up PR on this one: https://github.com/opencollective/opencollective-frontend/pull/9623
