### ISSUE TITLE
Name mismatch between collective name and actual backer

### ISSUE THREAD

**Issue by Kilheure** [opencollective/opencollective#682]
![screen shot 2017-11-23 at 20 14 25](https://user-images.githubusercontent.com/31570464/33213937-a3d7dee2-d121-11e7-92c5-df0a97dc4899.png)

***

URL: https://opencollective.com/agreelist
Logged in as: https://opencollective.com/emilie-esposito
Error message if any:none
Expected result: see another person supporting Agreelist and not the collective itself
Browser:

Bonus point if you can add a screenshot :-)

Seeing the collective backing itself up is a weird usecase. It should maybe not be allowed

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by Kilheure** [comment]
User wanna donate as individual. 
As a use case can organisation donate to itself?

**Comment by piamancini** [comment]
fixed this yesterday
