### ISSUE TITLE
Non-latin characters not displayed in PDFViewer

### ISSUE THREAD

**Issue by gustavlrsn** [opencollective/opencollective#6822]
**Describe the bug**
When opening a PDF with non latin characters, those are not displayed.

To fix this, we need to [configure character maps for `react-pdf`/`pdfjs-dist`](https://github.com/wojtekmaj/react-pdf#support-for-non-latin-characters)

**Comment by Betree** [comment]
Re-opening as we've reverted https://github.com/opencollective/opencollective-frontend/pull/8984 in https://github.com/opencollective/opencollective-frontend/pull/8984

**Comment by kewitz** [comment]
I already had to revert this once: https://github.com/opencollective/opencollective-frontend/pull/9035
We'll need to wait until this is solved: https://github.com/wojtekmaj/react-pdf/issues/1533

**Comment by Betree** [comment]
Reverting the update in https://github.com/opencollective/opencollective-frontend/pull/8984 did the job

**Comment by kewitz** [comment]
@gustavlrsn, can you take this up?

**Comment by gustavlrsn** [comment]
@kewitz will do!
