### ISSUE TITLE
Submitted expenses link broken

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6825]
I clicked this `submitted` button on https://opencollective.com/protozoa/expenses

<img width="440" alt="Screen Shot 2023-06-16 at 9 53 07 AM" src="https://github.com/opencollective/opencollective/assets/5498878/d45a0390-1d6c-4c3b-b512-e3a6596540df">

And I see:
<img width="951" alt="Screen Shot 2023-06-16 at 9 52 53 AM" src="https://github.com/opencollective/opencollective/assets/5498878/83b88a8b-39b6-4181-8643-e89d43ce2411">

Note the URL above.

Looks like the URL looses the profile slug. If I manually update it to https://opencollective.com/protozoa/expenses?direction=SUBMITTED then it works.

**Comment by Betree** [comment]
Fixed in https://github.com/opencollective/opencollective-frontend/pull/8989, which will be deployed today
