### ISSUE TITLE
Reimbursement Multiple Receipts

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6829]
## Who is your user?
Reimbursement submitters 

## What are they trying to achieve?
When uploading receipt images for reimbursements, the receipt is often too long to get a single good-resolution image. 

_When uploading receipt images, I want to upload multiple images to one reimbursement item_

## How are they currently doing this?
So I upload multiple images showing all portions of the receipt. But each receipt image requires a dollar value total of at least $0.01.

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment]
Doing so would complexify a lot our data model. The suggested alternative would be to upload the file as PDF (since PDFs can include multiple pages) or split the receipt into multiple items.

**Comment by SudharakaP** [comment]
Closing as per, https://coda.io/d/_dEguIswyoKq?encodedLocationContext=eyJjb21tZW50VGhyZWFkSWQiOiJyLU9fNThkWU9LVGkiLCJwYWdlSWQiOiJzZWN0aW9uLVA4cENSRHY1V2wiLCJ0eXBlIjoiZ3JpZCIsIm9iamVjdElkIjoiZ3JpZC1ZLUxJR0lNS1FwIiwicm93SWQiOiJpLTRNT2x3dzVmaVYifQ. We can reopen later if this is surfaced again
