### ISSUE TITLE
Webhook Invite expense error

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6830]
## Who is your user?
Collective Admin

## What are they trying to achieve?
I have a web hook set up for new expenses so that we can view expenses in a Slack channel.

It has been working great, but I noticed today that when someone doesn't submit the expense themselves (i.e. the invite payee option is used) it does not make its way to the webhook.

_When any type of expense is submitted, I want to trigger the webhook to post on Slack, so I can complete the expense process_

## How are they currently doing this?
It is working for all expenses except for the invite expense option

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment]
The "Create" webhook event is actually emitted when the invitee verifies the expense; we don't consider the expense as created before that. You can watch the `COLLECTIVE_EXPENSE_INVITE_DRAFTED` event type if you're interested in this specific event.

**Comment by SudharakaP** [comment]
Thanks @Betree. I've responded to the user. In any case I'll watch out for any future requests for this in case we need to come up with some improvement or the need for an additional web-hook support for the COLLECTIVE_EXPENSE_INVITE_DRAFTED event type. My thinking is unless there's multiple requests we probably don't need to support this right now?

**Comment by SudharakaP** [comment]
The support thread relevant is given at, https://opencollective.freshdesk.com/a/tickets/217970

**Comment by Betree** [comment]
> My thinking is unless there's multiple requests we probably don't need to support this right now?

That's my thinking too. The current approach is rational and prevents SPAM: since anyone can invite, I don't want to see expense-created activities unless the payee has approved them.

IMO we should close this issue and defend that things work this way intentionally. I'm not closing it myself in case @shannondwray disagrees.
