### ISSUE TITLE
Show agreements on expenses

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6831]
Part of https://github.com/opencollective/opencollective/issues/4894

[Design in Figma](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?type=design&node-id=20700-98587&t=dPfNXocq0HvOri6y-0)

![image](https://github.com/opencollective/opencollective/assets/1556356/7dd1e856-63ca-4fe3-9655-b5dbd586a916)

**Comment by shannondwray** [comment]
Duplication? https://github.com/opencollective/opencollective/issues/6705

**Comment by Betree** [comment]
Indeed, thanks @shannondwray!
