### ISSUE TITLE
Fiscal Host Application Correspondence

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6837]
## Who is your user?
Fiscal Host admin 

## What are they trying to achieve?
Whenever you reject an application, it prompts you to send a message, and then it disappears. We would love to be able to see rejected applications. View correspondence and help collectives meet the criteria to be approved eventually. 

This could work similarly to how expenses have comments, goes through different stages etc. 

_When processing applications, I want to communicate with the rejected collectives, so I can educate, improve applications and help collectives get approved  _

Being able to filter the applications would also be useful, pending, rejected, and approved. 

## How are they currently doing this?
OSC: We send a rejection message with the open collective platform. We also send a message via Freshdesk. So we can keep track of the conversation. If we communicate with the OC platform, we lose track of all correspondence as it disappears. 

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by shannondwray** [comment]
@BenJam bump for next prioritisation :P

**Comment by shannondwray** [comment]
I asked OCE and SCN to show their application processes in the recent fiscal host call. They both struggle to track conversations and timelines using the OC pending applications process. They utilise external software to process applications, 

Social Change Nest uses Hubspot to track this process and email communication. 

<img width="1218" alt="Screenshot 2023-06-22 at 3 00 24 PM" src="https://github.com/opencollective/opencollective/assets/79115149/dcf2238c-dc7e-48e8-a62b-27ef66b9441f">


OCE uses the application process on their website. They then communicate via email and use Jira to track the stages.

**Comment by Betree** [comment]
Related: https://github.com/opencollective/opencollective/issues/4699

**Comment by shannondwray** [comment]
Will close this with the application comments work that Henrique has been working on
