### ISSUE TITLE
Default Query Parameters on Embed Do not Crash the Contribution Flow

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6838]
**Describe the bug**

Related to the ticket; https://opencollective.freshdesk.com/a/tickets/216040. It seems that adding a default query parameter such as `hideHeader=false` to the embed contribution flow seems to crash the contribution flow with the error; 

```
Uncaught (in promise) DOMException: The operation is insecure.
```

**To Reproduce**
1. Go to https://opencollective.com/embed/hapu-comms/contribute/t-shirt-sales-payments-34722?hideHeader=false
2. Click on `Your Info` button
3. Open the developer console on the browser and see the error. The contribution flow don't work.

**Comment by Betree** [comment]
We're changing how this works in https://github.com/opencollective/opencollective-frontend/pull/8326, I'll test it there to make sure the bug does not appear after the update.

**Comment by Betree** [comment]
In [opencollective/opencollective-frontend@`e473373` (#8326)](https://github.com/opencollective/opencollective-frontend/pull/8326/commits/e473373f8aa9b0c9a201d2a51452c541da3a804b) I'm renaming the step `CHECKOUT` introduced with the crypto flow to `FINALIZE`. The problem with the word `checkout` is that it's already used by another contribution flow route (see the screenshot below), which creates a conflict and eventually redirects to the wrong part of the flow. I was getting a blank page with infinite redirect when trying to visit https://opencollective.com/embed/hapu-comms/contribute/tshirts-34722/checkout?hideHeader=false directly.

Doing so also resolved this issue, as we can observe on https://opencollective-frontend-rgbn6dti2-opencollective.vercel.app/embed/captainfact_io/contribute/tshirt-10355?hideHeader=false

![image](https://github.com/opencollective/opencollective/assets/1556356/c8186863-21d6-4e77-916b-1065d98a4942)

**Comment by Betree** [comment]
Resolved
