### ISSUE TITLE
available balance of collective is not decreasing when expenses marked as paid

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#684]
I just paid an expense manually via paypal marked the expense as method 'Other' hit PAID, the available balance of the collective in the front end did not decrease. It is 224 as it was before paying the expense.
https://opencollective.com/chaijs
expense ID2211
The paid expense did not generate the rows in the the transaction table. 
We should make a search for expenses with no rows in transaction table. I pay expenses +2k manually each time. I paid a 10k one for babel expense ID2224, that did not generate rows in the txn table either. 

This can be very problematic (even if it's just a front end issue, because that number is what we look at to manually pay expenses)

Thank you for taking the time to report an issue 

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by asood123** [comment]
fix to prevent this in the future: https://github.com/opencollective/opencollective-api/pull/1023.

Still need to fix the 10 or so expenses that are marked paid and have no ledger entries. query for it:

`
select * from "Expenses" e

left join "Transactions" t on t."ExpenseId" = e.id

where e.status ilike 'paid' and t.id is null and  e."deletedAt" is null

order by "ExpenseId" DESC, e."updatedAt"
`

**Comment by asood123** [comment]
ran script to fix remaining transactions
