### ISSUE TITLE
Add E2E tests for agreements

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6840]
Part of https://github.com/opencollective/opencollective/issues/4894

```[tasklist]
### To be tested
- [ ] Create an agreement
- [ ] Edit agreement
- [ ] Delete the agreement
- [ ] Agreement appears on expense page for admins
```

**Comment by iamronen** [comment]
@Betree I was unable to add tasks to the list so:
- [ ] Add agreements to different different fiscal hosts, make sure agreements are segregated across fiscal hosts.
- [ ] Add agreements to different collectives in the same fiscal host, add expenses to each collective and make sure that each collective only sees its agreement(s)
