### ISSUE TITLE
Filtering by active contributions still shows inactive contributions

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6843]
**Describe the bug**
I want to see only my active contributions but it's showing me inactive ones too

**To Reproduce**
1. Go to "manage contributions"
2. Filter is set to "active"
3. See inactive contributions

**Expected behavior**
Cancelled contributions should not be considered "active"

**Screenshots**
<img width="959" alt="Screen Shot 2023-06-28 at 3 53 58 PM" src="https://github.com/opencollective/opencollective/assets/5498878/578f4dd5-95d4-4d9c-a7fa-efd79d12f8d5">

  P4 low frequency, low impact

**Comment by Betree** [comment]
I can reproduce. We also have these strange contributions with an empty status. Will look into it to ensure it's not a regression from recent libraries updates.

![image](https://github.com/opencollective/opencollective/assets/1556356/b7e2646b-4305-40ae-b639-be9f5ca0eee4)
