### ISSUE TITLE
Contributions can't be tagged

### ISSUE THREAD

**Issue by poohlaga** [opencollective/opencollective#6856]
**Describe the bug**
A transaction that is a type of 'contribution' can not be tagged. This creates inaccurate reporting for collectives or hosts.

**To Reproduce**
See the behavior here - https://opencollective.com/open-source-festival-2023-e17954c1/contributions/659446
- you can select a tag
- tag is not saved

**Expected behavior**
Selected tags should be saved

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
Related: We're not checking permissions for this button, it's displayed even when unauthenticated

**Comment by Betree** [comment]
@poohlaga are you getting an error message? With the right permissions, the tag gets displayed for me after reloading the page

**Comment by poohlaga** [comment]
Wacky behavior https://www.loom.com/share/e97a3002b64442f694d495191f416ebe

**Comment by Betree** [comment]
Seems to have been resolved by https://github.com/opencollective/opencollective-api/pull/9163 + https://github.com/opencollective/opencollective-frontend/pull/9102
