### ISSUE TITLE
Am I Prohibited

### ISSUE THREAD

**Issue by techtonik** [opencollective/opencollective#6858]
## Who is your user?
Me.

## What are they trying to achieve?
When I am out of money, I want to know if I can use OpenCollective, so I can enable users of my open source projects to support me financially.

## How are they currently doing this?
I don't have PayPal, or whatever, I don't have passport for this online ID. I am merely my contributions and expertise online. In the real world my parents feed me, and my friends were sometimes giving me money or easy jobs to do. But now everybody is moved out, my parents are old, and when I start full time job, I and up in hospital in few months. It is not sustainable.

So I am looking to open OpenCollective account, because that seems legal and transparent to everybody. However, I am not sure I am eligible, because https://opencollective.com/tos says that the platform is only for

> "(ii) you are not a national of, or a company registered in, any Prohibited Jurisdiction."

I do not identify myself with any nationality, but my body has passport. How to check that my body is not marked as Prohibited Jurisdiction?
Can the "Prohibited Jurisdiction" part be directly linked to official list?

## How well understood is this problem?

 - [x] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment]
Hi @techtonik, we're registered as a US company. You can get the list here: https://en.m.wikipedia.org/wiki/United_States_sanctions

**Comment by techtonik** [comment]
I am afraid Wikipedia is not an authoritative source of information, so that doesn't answer the question. Does US has an official API to check if a person is prohibited?
