### ISSUE TITLE
Remove crypto contributions

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6859]
See https://opencollective.com/opensource/updates/open-source-collective-is-disabling-contributions-in-cryptocurrencies

Resolve:
- https://github.com/opencollective/opencollective/issues/4935
- https://github.com/opencollective/opencollective/issues/6441
- https://github.com/opencollective/opencollective/issues/5661
- https://github.com/opencollective/opencollective/issues/5448
- https://github.com/opencollective/opencollective/issues/5432
- https://github.com/opencollective/opencollective/issues/4649
- https://github.com/opencollective/opencollective/issues/4616
- https://github.com/opencollective/opencollective/issues/4576

**Comment by Betree** [comment]
@znarf Crypto contributions code still exists in the API (i.e. [here](https://github.com/opencollective/opencollective-api/blob/ee34c325cee9f1d9d555e6c66a9ef9016c6c0b8b/server/lib/payments.js#L734)), I think that we should keep this open until we have it removed from everywhere.

**Comment by znarf** [comment]
@Betree here we are https://github.com/opencollective/opencollective-api/pull/9495
