### ISSUE TITLE
host (user not org) can't pay expenses 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#686]
I'm trying to pay the expenses on https://opencollective.com/opencollectivehost/collectives/expenses 
the host is a user https://opencollective.com/opencollectivehost
logged in as the host in the URL above, I don't see the pay buttons to pay expenses nor the connect paypal button. 

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by artf** [comment]
Hi @piamancini, I'm facing the same issue and just can't pay the expense I've submitted for a contributor. I was really confused about all the process so tried to check out your FAQ but this not helped,  for example

> **How does it work?**
When you create a collective, the money collected goes to the bank account associated with the collective. When someone wants to use the money, they submit an expense on the public page of your collective (like this one). After the expense is approved by you, the person is automatically reimbursed to their PayPal account. The budget and all the expenses are visible publicly.

`goes to the bank account associated with the collective` 
Not sure if I get it right, but I don't see any option for this kind of operation

`After the expense is approved by you, the person is automatically reimbursed to their PayPal account` 
Well, I've approved the expense but seems like nothing happened. I don't even get if I supposed to see the `pay` button or not

**Comment by piamancini** [comment]
hi @artf! Your collective is hosted (fiscal sponsored) on The Open Source Collective, that means that we receive the funds for you, do bookkeeping, 1099s, and manage your expenses. You don't have a pay button because you are not the host of your collective. We reimburse expenses once a week on Fridays. 

If you would like to host your collective and manage expenses yourself, you need a Stripe account and then the contributions will go directly to the bank account connected to that Stripe. You then are responsible for the financial administration of your collective (and our fee drops to 5%) You can read more on expenses [here](https://github.com/opencollective/opencollective/wiki/Submitting-Expenses) and on hosts [here](https://github.com/opencollective/opencollective/wiki#hosts)

If you want the Open Source Collective to keep being your fiscal sponsor, then you just need to approve the expense and it will get paid on Friday (today!).

**Comment by artf** [comment]
Thanks Pia, didn't know about your wiki 😬  now it's all clear 👍

**Comment by piamancini** [comment]
no worries. it's on us to make it more accessible. Will get expenses reimbursed today. best!

**Comment by piamancini** [comment]
@artf hey! Can you please email us support@opencollective.com the invoice you submitted? for some reason the file is corrupted and it opens a black window. 
Thank you!

**Comment by asood123** [comment]
This is happening because LoggedInUser.memberOf only returns relationships in the Members table. It ignores User.CollectiveId relationship. Ideal solution would be to not allow UserCollectives to be Hosts.

**Comment by asood123** [comment]
Here's a hacky fix for it: https://github.com/opencollective/frontend/pull/137
