### ISSUE TITLE
Search for Expenses based on Merchant (transaction) ID

### ISSUE THREAD

**Issue by iamronen** [opencollective/opencollective#6864]
When we pay an expense with a merchant (Wise/Paypal) we are provided and store a unique merchant ID that uniquely identifies the transaction with the merchant. We’ve been asked (by payment providers) to review expenses based on this ID And need to expand the expense search functionality to include searching based on ‘merchant id’ ONLY within the fiscal host workspace→expenses.

**Comment by aminakazi** [comment]
I assume we'll need to surface and display the merchant id on the individual expense page?

**Comment by kewitz** [comment]
@iamronen An expense usually has several IDs attached to it that refer to different objects within the transaction, for example, the payee id, the transaction id, the quote id, and the business profile id. I need to know exactly which IDs should be indexed.

It would be nice to have an example of one expense from PayPal and another one from Wise with the ID on the platform you want to be able to search for.

**Comment by iamronen** [comment]
@kewitz I will tag @BenJam (the source of this request) to confirm my answer.
 The scenario that drove this is the need to research a transaction that originates from Stripe or Paypal.
>  I am a fiscal host admin looking at(for example) the Stripe dashboard and I am seeing a transaction there that I want to look into on Open Collective. My reference is the Stripe transaction id (which I am assuming is what we mean by merchant id). I'd like to be able to search for that and find the correlating expense/contribution.

**Comment by BenJam** [comment]
- [ ] tell leo which id's are being copying per provider

there are several types of IDs, just need to know which to index and search through the form(s).

**Comment by kewitz** [comment]
Check "Merchand Id" resolver from the CSV export service.
