### ISSUE TITLE
Submit expense without PayPal

### ISSUE THREAD

**Issue by JeanPaulGrange** [opencollective/opencollective#687]
Hello,

HOST : https://opencollective.com/vdmentransition
I want to pay somebody so I go on the Submit expense page but the only solution proposed is to Reimburse Via PayPal. I don't have set up a PayPal because I am in France and it seems complicate to use this. 
How should I proceed ?

Regards,

**Comment by piamancini** [comment]
Hi @JeanPaulGrange You can mark the payout method as 'other'
log in as the host, edit the expense, and select payout method 'other' (see screenshot) and save. 
You can then mark it as PAID and the balance will get deducted from the collective. Make sure you pay that expense somehow else!

**Comment by JeanPaulGrange** [comment]
Hi @piamancini Thanks, I try it.

**Comment by piamancini** [comment]
@JeanPaulGrange great! let me know how it went.

**Comment by JeanPaulGrange** [comment]
Hello Pia, I have not seen where is your screenshot but I succeed in modifying the payout method before approval

**Comment by piamancini** [comment]
thanks @JeanPaulGrange!
