### ISSUE TITLE
Recurring direct debits

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6873]
## Who is your user?
Financial contributors

## What are they trying to achieve?
They want to set up a 

_I want to set up a recurring bank transfer when contributing to a collective. They do this via direct debit and provide the reference number from the first transfer so that they can contribute periodically. 

## How are they currently doing this?
They are currently doing this and are putting the reference number for the first transfer, not knowing that the reference number needs to be unique for each bank transfer. 

I know we don’t allow recurring bank transfers from the platform, but people can set them up from the banking side via direct debit. 

Each manual bank transfer gets given an individual reference number for allocation purposes. Can we give donors wishing to set up direct debit a reference number that will work every month? https://opencollective.freshdesk.com/a/tickets/222083

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by shannondwray** [comment]
This was specifically asked for by the Social Change Nest which is based in the UK

**Comment by Betree** [comment]
@hdiniz can we enable Stripe elements for them?

**Comment by hdiniz** [comment]
I enabled the stripe elements for the `the-social-change-nest`, they now have bacs direct debit as an option for contribution.

**Comment by phlash** [comment]
@hdiniz thank you! This had been annoying me for a year or so - I can finally remove my (unreliable) self from the donation loop :grin:

**Comment by SudharakaP** [comment]
@shannondwray : I suppose we can close this given we support Stripe elements now for the collective in question.
