### ISSUE TITLE
Review loading states for all pages

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6876]
In previous versions of Apollo, when re-fetching (i.e after a route change), `data` contained a reference to fetched items until fresher entries replaced them. In its current version, Apollo unsets previously fetched data while loading, and makes it available through `data.previousData`. As a result, the way our loading page update when refetching/navigating/etc have changed and may not be what we want.

- [x] Collective page => https://github.com/opencollective/opencollective-frontend/pull/9138
- [x] Transactions page
- [x] Expense page
- [x] Expenses page
- [x] Tier page
- [x] Contribute page
- [x] Updates page
- [x] Update page
- _List to be completed_

**Comment by Betree** [comment]
Related: on the transactions page, when authenticated, we seem to trigger the query two times, even though the first one was already authenticated.

**Comment by Betree** [comment]
According to @kewitz:
> for some reason, getDataFromTree is no longer fetching queries from Apollo HOC implementations. I think the correct way to solve this is by refactoring all pages to use Apollo hooks but this needs to be further tested.

We should investigate that as a priority.

**Comment by Betree** [comment]
Analysis with @kewitz:
- SSR is actually crashing with this error: https://nextjs.org/docs/messages/next-router-not-mounted, `withRouter` when used in a component rendered through `getDataFromTree` crashes because it misses the NextJS context.
- It is almost certainly related to the latest NextJS update. We missed it for the past two months because SSR issues are not obvious, and everything still works fine overall. In the past, NextJS was likely returning `null` when the context was not available (which we had to handle manually, see https://github.com/opencollective/opencollective/issues/3558) and seems to have switched to throwing an error in the latest major release.

Discussed solutions:
- ~~**Fix `withData`**~~. After a quick attempt, I haven't been able to figure out an easy solution by just touching `_app.js` and `withData`. We also dislike this solution as it goes against the patterns that are recommended by NextJS nowadays and feel like maintaining this legacy approach is not a good investment of our energy.
- **Use custom `withRouter`/`useRouter`** that checks the context and returns `null` when outside of NextJS: we could do something like that to reduce the number of required changes, but there are a few drawbacks with this solution:
   - It increases the technical debt rather than reducing it
   - Other hooks and HOC that require NextJS context may crash again in the future
- **Move to `getServerSideProps`**: it seems like the cleanest solution but requires some refactoring. We could take advantage of `skipDataFromTree` to progressively migrate, with the ultimate goal to remove `withData` completely.

Whatever we do, we should also make sure we improve the error logging. SSR issues are currently ignored (see https://github.com/opencollective/opencollective-frontend/blob/9c4ea08a86015fa41a34664d6864ef0f5ebf94f4/lib/withData.tsx#L48). They should be logged to Sentry, which would have helped us to notice the issue earlier.

**Comment by kewitz** [comment]
@Betree I just tested out implementing `getServerSideProps` on top of the existing "TransactionsPage" class and it failed. This mostly happens because this component requires other HOC that themselves implement `getInitialProps` (which cannot be used with `getServerSideProps`). I think we'll need to refactor this to function pages so we can replace these HOC with hooks and make it interoperable with `getServerSideProps`.

**Comment by Betree** [comment]
@kewitz Which HOCs in the transactions page use `getInitialProps`? If it's something also used in different places we'll face the problem sooner or later, so we may as well give it a go now

**Comment by Betree** [comment]
To clarify the plan moving forward:
- [ ] Move all pages from `getInitialProps` to `getServerSideProps`
- [ ] Get rid of `withData`

**Comment by Betree** [comment]
Closing as the root issue is resolved, we'll follow up in https://github.com/opencollective/opencollective/issues/7013
