### ISSUE TITLE
Add compliance notices for hosts issuing virtual cards through Stripe

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#6880]
On 26th June we received a notice from Stripe's compliance contractor (Perform line) regarding our non-compliance with one of Stripe's terms, namely:

>Rule: Issuing - General Disclosure - Celtic — issued by Celtic Bank (triggered by: credit card)

The notice was sent to Open Collective Foundation specifically but the compliance requirement exists for any host (and, possibly, Open Collective as a platform) when issuing virtual cards using Stripe. 

Given that we issue a number of virtual cards every month and that the total volume of expenses registered on a monthly basis is in excess of 100k I believe this represents a risk that we should remove entirely as soon as possible. 

More information about Stripe's compliance team can be found at [stripe.com/docs/treasury/compliance](http://stripe.com/docs/treasury/compliance)

**Comment by BenJam** [comment]
- list areas where we would need notices 
- review eng requirements/approach (i.e. how to apply correct notices)

**Comment by hdiniz** [comment]
This week

- [ ] Add compliance notices to virtual card components

**Comment by BenJam** [comment]
@BenJam to check against compliance notices from Stripe.
