### ISSUE TITLE
webmural

### ISSUE THREAD

**Issue by ryanve** [opencollective/opencollective#6883]
### h¡ `=)`

wondering how <b>to</b>~i~<b>let</b> people sponsor @webmural

[<b>open</b>collective](https://github.com/sponsors/webmural) seems igno<b>red</b> @github [sponsors](https://github.com/sponsors/webmural) 

[beeing](https://webmural.com/nature) sponsored [for creative](https://webmural.com) [<b>open</b>source](https://github.com/webmural) sounds [like magic](https://webmural.com/clim8)

### [<b>s9a</b>](https://opencollective.com/s9a)<sup>@s9a</sup> [✸](https://opencollective.com/ryanve) <sub>@p9e</sub>[<b>p9e</b>](https://opencollective.com/p9e)
have [sponges](https://github.com/sponsors/s9a) [pages](https://github.com/sponsors/p9e) <code>wi<s>d</s>th</code> @opencollective as fiscal host 

[<b>web</b>mural](https://opencollective.com.com/webmural) was setup like a user...*my bad?*

what's the best way to handle this scene?

[🦋🦋🦋🦋🦋 <br> thank 🦄 hue <br> 🐠🐠🐠🐠🐠](https://webmural.com/butterfly)

**Comment by ryanve** [comment]
`cc` @jrdnrch

**Comment by Betree** [comment]
@ryanve If you're an open-source project, you can try to apply to opencollective.com/opensource/apply/

**Comment by ryanve** [comment]
Thanks @Betree when I go there it prompts me create a new collective. I already created [@webmural](https://opencollective.com/webmural) on there and would prefer that to be the collective. On Github @webmural is an organism with many repos all opensource. The page to <b>pick a repo</b> in that flow gives a service error perhaps due to the thousands of repos @webmural and anyway would like to pick all of them as a whole open collective. WDYT

**Comment by Betree** [comment]
@ryanve Maybe try and pick "Request manual verification"

![image](https://github.com/opencollective/opencollective/assets/1556356/2435306c-ef31-41fc-8896-21aea670cf17)

**Comment by ryanve** [comment]
@Betree thanks thru community flow as [webmural](https://opencollective.com/webmural) created [collective with capita*L*](https://opencollective.com/webmural_) 💦

Should be cool yea? Going to try connecting @github

**Comment by Betree** [comment]
I recommend joining our [Slack](https://slack.opencollective.com/) > #community-support if you have any more question

**Comment by ryanve** [comment]
huh @github is amour *open*
