### ISSUE TITLE
Can't upload files for processing virtual card charges

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6884]
Reported in https://opencollective.slack.com/archives/C6JTTA4SK/p1688669303322959

> This happens only when the expense has been just processed and you upload it when you first get the email notifying you. Eg when it's i the processing stage. it does not happen at any other stage.

**Comment by RCheesley** [comment]
The issue here is that you can upload the file, and apply tags, update the description etc - but only the tags are saved. The attachment and the title are not saved, and I have to go back and do it again once the transaction is out of the processing state. Thanks!

**Comment by Betree** [comment]
It seems resolved; I couldn't reproduce it with recent processing expenses. @RCheesley, please let us know if you ever reencounter it!
