### ISSUE TITLE
Add a setting to let host turn off collective admins refunds

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6885]
From https://github.com/opencollective/opencollective/issues/6875

> Can Collective admin refunds be turned off for this one Host? Or is there a way for Host admins to have an approval step in the process after Collective admins click refund?

Add a `host.data.policies.COLLECTIVE_ADMINS_CAN_REFUND` policy.

**Comment by alanna** [comment]
Thanks! This would solve Gift Collective's need in the short term.

**Comment by Betree** [comment]
@alanna This is released, you can switch the policy on https://opencollective.com/giftcollective/admin/policies


![image](https://github.com/opencollective/opencollective-frontend/assets/1556356/f81c6c3f-6f98-4588-bd71-057c33ba1418)

**Comment by alanna** [comment]
wow that was fast, thank you so much
