### ISSUE TITLE
Profile page settings are empty

### ISSUE THREAD

**Issue by Xenorio** [opencollective/opencollective#6889]
**Describe the bug**
When going to the admin dashboard of a collective or project and clicking on "Profile Page", the page is empty.

**To Reproduce**
1. Go to admin dashboard of collective/project
2. Click on "Profile Page"
3. Look at screen

**Expected behavior**
There should be a table allowing me to enable or disable sections on the profile page

**Screenshots**
![image](https://github.com/opencollective/opencollective/assets/39472201/f3600abc-b966-40df-93e0-7ed5fe196619)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox, Chromium
 - Version: Firefox 115 | Chromium 114.0.5735.198

**Additional context**
Seems to be related to an error on https://opencollective.com/api/graphql/v2
``Cannot query field "COLLECTIVE_ADMINS_CAN_REFUND" on type "Policies". Did you mean "COLLECTIVE_MINIMUM_ADMINS"?``

![image](https://github.com/opencollective/opencollective/assets/39472201/d7675183-d095-488a-8371-90f643acbe2d)
![image](https://github.com/opencollective/opencollective/assets/39472201/60c1dbe7-2902-4f82-9d3c-98dac9f5e883)

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
@Xenorio Thanks for the detailed report, and sorry for the issue; we missed a deployment of our API services. It should be fixed now.
