### ISSUE TITLE
Improve wording for private updates

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6891]
# Update form 

![image](https://github.com/opencollective/opencollective/assets/1556356/a36231db-04ff-4045-8d79-4b18c17b5809)

Should be:
> Check this to limit access to the content of this update to the target audience only

# Update

![image](https://github.com/opencollective/opencollective/assets/1556356/b1d4a62b-cc1a-48a2-a033-324c2b92c682)

Based on the `notificationAudience`, this should be:
- FINANCIAL_CONTRIBUTORS
   > This update is for contributors only
- COLLECTIVE_ADMINS
   > This update is for hosted collective admins only
- Otherwise:
   > This update is for members only

**Comment by Aditya13s** [comment]
@Betree 
Kindly assign this task to me, allowing me to engage in meaningful work and make valuable contributions to the project.

**Comment by Aditya13s** [comment]
How to check if the update is private or not?
@Betree

**Comment by Betree** [comment]
> How to check if the update is private or not?
> @Betree 

They have a "Private update" tag, as in the 2nd screenshot of the issue's body

**Comment by Aditya13s** [comment]
How to check if the notificationAudience is FINANCIAL_CONTRIBUTER or COLLECTIVE_ADMINS or All
@Betree

**Comment by Betree** [comment]
You select that when you create an update, at the 2nd step, before publishing, in the drop-down next to "Who should be notified"
