### ISSUE TITLE
Filter/Visual Indicator for Virtual Card Expense That Requires a Receipt

### ISSUE THREAD

**Issue by aguywithcode** [opencollective/opencollective#6895]
## User story 
_As collective admin, I can view virtual card expenses missing receipts so that I can easily find and add receipts to those expenses_

## Best solution for this problem
_Add a status or a filter to the expenses view that indicates a receipt is required_
![image](https://github.com/opencollective/opencollective/assets/13209683/5d7df688-1e55-4e68-97c8-7dd2c3edf655)

## MVP
_What should be possibly built to demonstrate the solution?_

## Metrics 
_What metrics will be used to measure impact?_

## Documentation 
_In order to view a list of undocumented virtual card expenses, select the "receipt needed" status from the drop down_

<details>
  <summary>Triage Template (team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
This issue is a duplicate with https://github.com/opencollective/opencollective/issues/6241; feel free to track it to get updates - I believe this has been working on recently.
