### ISSUE TITLE
[DOCS] Attach Agreements to Collectives

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6913]
## Context
Project: https://github.com/opencollective/opencollective/issues/4894

### What's changing?
- We're adding the ability to attach agreements to collectives
- Hosts can manage the collective agreements from their dashboard
- Agreements are surfaced for host admins when viewing an expense

### Who does this change impact?
The release is currently limited to internal fiscal hosts.

### How do users use it?
https://github.com/opencollective/opencollective/assets/1556356/ab27ec1e-3b75-4deb-beee-7151228047ad

### Is this change being released incrementally as a beta? What's the schedule?
We may enable it for all fiscal hosts in the near future.

**Comment by Betree** [comment]
cc @jpjhill

**Comment by Betree** [comment]
@BenJam Could we plan a public release/public com for this one? I'm adding a feature flag to enable it as more hosts are willing to use it. I think it can benefit all fiscal hosts on the platform.

**Comment by shannondwray** [comment]
Moved here: https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Documentation-Releases_sul57#Project-Releases_turYe/r41&view=modal
