### ISSUE TITLE
Incognito Contributions are missing in Transactions List

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6914]
## User story 

This is inspired by the following Freshdesk ticket; https://opencollective.freshdesk.com/a/tickets/230628. Currently if a user contributes in incognito mode that transaction is not viewed under their profile (when logged in) making it hard for them to find what they've actually contributed. 

## Best solution for this problem

It would be nice if users could see their incognito transactions under their profile transactions list when they login.

**Comment by Betree** [comment]
That's supposed to be the case already: https://github.com/opencollective/opencollective-frontend/blob/1e8e4bf36f1940838c0ad3ef2cc8ec1510d63410/pages/transactions.js#L97. If they're not here, it's a regression.

**Comment by Betree** [comment]
I can confirm that incognito transactions are not listed anymore, they may have been broken in https://github.com/opencollective/opencollective-frontend/pull/8751
