### ISSUE TITLE
Attachments Not Uploading for Grants

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6920]
**Describe the bug**

Related to the freshdesk ticket; https://opencollective.freshdesk.com/a/tickets/233693. It seems that for grant requests attachments are not uploaded properly. I could recreate this on staging as shown in the below screen-cast.

**To Reproduce**
1. Go to a collective with grants enabled.
2. Start a grant expense application.
3. Try to attach any attachment.
4. You'll see that while it's uploaded when you click submit the attachment goes away.

**Expected behavior**

Attachments should uploaded for grants. Just like invoice and reimbursements.

**Screenshots**

[grant-attachment.webm](https://github.com/opencollective/opencollective/assets/12435965/ec227e1c-cec0-466f-9788-da3a13fd87d7)

**Comment by Betree** [comment]
I'll prioritize a fix for this one.

**Comment by Betree** [comment]
The issue was actually [introduced](https://github.com/opencollective/opencollective-frontend/pull/8362) a while ago, but we never noticed

**Comment by SudharakaP** [comment]
@Betree : Thanks a lot for fixing this one.
