### ISSUE TITLE
Z-index issue on virtual cards menu list

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6935]
> the z-index is wacky when you click on the ‘…’ view more next to a virtual card

![image](https://github.com/opencollective/opencollective/assets/1556356/22f7581e-20b2-471d-b199-38eb45800a38)

**Comment by Mroczek1992** [comment]
> > the z-index is wacky when you click on the ‘…’ view more next to a virtual card
> 
> ![image](https://user-images.githubusercontent.com/1556356/259643059-22f7581e-20b2-471d-b199-38eb45800a38.png)

**Comment by JatinPhogat** [comment]
Hi i Would like to work on this issue . pls assign it to me .

**Comment by Betree** [comment]
This is resolved

![image](https://github.com/opencollective/opencollective/assets/1556356/58db0812-429e-475c-9379-87c3afc87ea3)
