### ISSUE TITLE
Some users are creating recurring contributions with Bank Transfer (manual)

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#6941]
Discovered while investigating https://github.com/opencollective/opencollective/issues/6934

**Describe the bug**

See the history for https://opencollective.com/letztegenerationat/contributions/611915:

Initially created with interval=month but no payment method (manual bank transfer) - this indeed doesn't make sense, we're not supposed to allow it.

Then updated to PayPal a few months later, payments apparently been running smoothly since then.

```sql
  select *
  from "Orders" o
  INNER JOIN "Collectives" fc ON fc.id = o."FromCollectiveId"
  where o."PaymentMethodId" IS NULL
    AND o."interval" IS NOT NULL
    AND o."deletedAt" IS NULL
    AND o.status != 'PLEDGED'
    AND fc.type = 'USER'
  ORDER BY o.id DESC
```

**To Reproduce**
Steps to reproduce are still unclear. 

**Expected behavior**
We do not support recurring for manual payments. It shouldn't be offered in the frontend, and should be blocked by the API.

**Comment by shannondwray** [comment]
https://github.com/opencollective/opencollective/issues/6873
