### ISSUE TITLE
Changing the number of tickets doesn't compute the right total amount

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#695]
The amount for one ticket is €200, but selecting two shows €400 on the tier component but €800 in the disclaimer (and total amount for the order) 
![](https://cl.ly/1r3X3f420y3W/Screen%20Shot%202017-11-28%20at%202.48.35%20PM.png)

https://opencollective.com/codenplay/order/2678

**Comment by asood123** [comment]
fix here: https://github.com/opencollective/frontend/pull/123/. Should go live later today or earlier tmrw
