### ISSUE TITLE
Error on User Menu when logging out

### ISSUE THREAD

**Issue by NikitaKorevo** [opencollective/opencollective#6960]
**Describe the bug**
Error when logout

**To Reproduce**
1. Go to Explore
2. Click on Avatar
3. Click on Log out button
4. See errors In the console:
>[GraphQL error]: Message: Only collective admins can see pending invitations, Location: [object Object], Path: memberInvitations
>Uncaught (in promise) ApolloError: Only collective admins can see pending invitations

**Expected behavior**
Page without errors

**Screenshots**
![before](https://github.com/opencollective/opencollective/assets/48645737/82ff4d94-24e5-4405-bb3a-3573eb9d3957)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by kewitz** [comment]
This was already fixed.
