### ISSUE TITLE
Can't use Workspace if I changed account

### ISSUE THREAD

**Issue by NikitaKorevo** [opencollective/opencollective#6961]
**Describe the bug**
Can't use Workspace if I changed account

**To Reproduce**
Need 2 accounts
1. Login via first account
2. Go to Workspace
3. Click select element
4. Click "Personal profile"
5. Logout 
6. Login via second account
7. Go to Workspace
8. See message:
>You need to be logged in as an admin

And `DashboardNavigationState` variable from localStorage contains wrong `slug` value.

**Expected behavior**
My second profile instead of the message.

**Screenshots**
![before](https://github.com/opencollective/opencollective/assets/48645737/21d4ff71-9c5b-45f9-9af4-b1066000f15f)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
cc @gustavlrsn

**Comment by Betree** [comment]
Thanks for your detailed reports @NikitaKorevo!

**Comment by iamronen** [comment]
@NikitaKorevo a followup question: 
Given that you use the same account to administer multiple entities on the platform (collectives, organizations, hosts, funds, etc.) and that now, with Workspace, it is easy to switch between them, why do you need multiple platform logins?

**Comment by NikitaKorevo** [comment]
@iamronen  I only used the second account to access the fiscal host settings as admin. I just forgot that I can join the fiscal host as admin from the first account.
