### ISSUE TITLE
Embedded Contribution Flows Broken

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6964]
**Describe the bug**

It seems that starting recently the embedded contribution flows are broken. 

**To Reproduce**
1. Go to any embedded contribution flow. Such as, https://opencollective.com/embed/hapu-comms/contribute/t-shirt-sales-payments-34722
2. See error

**Expected behavior**
The embedded contribution flow should show up the contribution flow without any issue

**Screenshots**

When  going to an embedded contribution flow we get, 

![image](https://github.com/opencollective/opencollective/assets/12435965/190e1e4d-2c9f-4fef-8247-2b2ef5c1ccae)

**Comment by SudharakaP** [comment]
Reported in Fresh-desk at, https://opencollective.freshdesk.com/a/tickets/244808

**Comment by Betree** [comment]
Thanks Suds, fixing that right away
