### ISSUE TITLE
host can't add funds - opencollective payment method failing

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#698]
https://opencollective.com/rochesterenablelimited/collectives/expenses
Is trying to add funds to one of their collectives and it's getting an error: "This host doesn't have an opencollective payment method"
I could reproduce it myself, see screenshot 
![screen shot 2017-11-28 at 3 08 35 pm](https://user-images.githubusercontent.com/3671070/33341913-50fd12de-d44e-11e7-8a4c-7fbf5cf37213.png)

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by xdamman** [comment]
The problem was that their Open Collective Payment Method was archived on 2017-11-28 19:34:40.57+00. I wonder how did that happen... Need to investigate. In the meantime, it should now work for them.

**Comment by xdamman** [comment]
Found the issue, it happened because they edited their payment methods via the interface. I'll deploy the fix shortly.
