### ISSUE TITLE
Submitting an expense with >255 receipt filename results in "Errorvalue too long for type character varying(255)"

### ISSUE THREAD

**Issue by MatthewCroughan** [opencollective/opencollective#6980]
**Describe the bug**
I've tried to submit an expense for https://github.com/NixOS/foundation/issues/83 but was unable to due to the following error appearing when clicking "submit expense"

![image](https://github.com/opencollective/opencollective/assets/26458780/24f90ea3-8f7c-47de-88ea-9a41a278f81e)

I took a screenshot of a GitHub issue to upload as the expense receipt, but the filename was larger than 255 chars, resulting in the error. The solution was to 

`mv "Screenshot 2023-09-05 at 11-09-27 Funding nix.camp 2023-09-24 to 2023-10-01 · Issue #83 · NixOS_foundation.png" funding.png`

**Comment by Betree** [comment]
@MatthewCroughan thanks for documenting this issue :heart:

I suggest fixing this is in the API by truncating the filename if too long and storing the non-truncated version in `data.originalFilename`.

**Comment by Betree** [comment]
This has been resolved in https://github.com/opencollective/opencollective-api/pull/9503
