### ISSUE TITLE
Dashboard: can't get "Recent activity" data when I reloaded "Overview" tab

### ISSUE THREAD

**Issue by NikitaKorevo** [opencollective/opencollective#6995]
**Describe the bug**
I can't reproduce in development mode, only in production mode.

**To Reproduce**
1. Go to https://opencollective.com/dashboard/korevo/overview
2. Await "Recent activity" data (in the console: `[GraphQL error]: Message: Content not ready, Location: [object Object], Path: account,feed`)
4. Reload
5. See the error message:
> Unexpected token E in JSON at position 0

In the console:
> [GraphQL error]: Message: Unexpected token E in JSON at position 0, Location: [object Object], Path: account,feed

**Expected behavior**
The page without errors

**Screenshots**
![before](https://github.com/opencollective/opencollective/assets/48645737/3313508b-3844-44f1-8b85-06896db83386)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by znarf** [comment]
The behavior is normal, the API send "Content not ready" when the feed is not available and proceed with generation in the background. As this error is expected, it would be nice to catch it and not throw it in the console.

Also, this is not this issue, but I acknowledge we need to follow up and make sure people see "Content not ready" / "Generating activity timeline" less often.

**Comment by kewitz** [comment]
@NikitaKorevo the malformed JSON error should be solved by now.
