### ISSUE TITLE
Updates: Logged out user, anchor point on comments

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6996]
## Who is your user?
Logged out users 

## What are they trying to achieve?
Read an update 

_When a logged out user is linked to an update, I want them to land at the beginning of the update, so I can incentivise them to read it_

## How are they currently doing this?
Currently the anchor point is set to the log-in to make a comment section 

<img width="792" alt="Screenshot 2023-09-12 at 10 41 27 AM" src="https://github.com/opencollective/opencollective/assets/79115149/08adfc3b-978b-44d9-9a40-3ae79249d2a7">

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment]
I was able to reproduce, here for example: https://opencollective.com/opencollective/updates/authentication-with-password-now-available. It likely originates from the `autofocus` on the sign-in form, which we should disable on this page since signing in is not its primary intent.
