### ISSUE TITLE
Enter key should submit 2fa form

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#7005]
**Describe the bug**
Pressing enter after typing in 2fa code doesn't do anything. I'm raising this as a bug because I remember it working previously.

**To Reproduce**
1. Trigger 2fa
2. Enter code into modal
3. Press enter on keyboard
4. nothing happens
5. use mouse to click `verify` and it works

**Expected behavior**
Pressing enter should submit the code

**Desktop (please complete the following information):**
- Chrome Version 117.0.5938.62 (Official Build) (arm64)
- MacOS 12.6.8

  P3 high frequency, low impact

**Comment by Betree** [comment]
cc @hdiniz
