### ISSUE TITLE
Personal badges (for backing projects) don't load

### ISSUE THREAD

**Issue by WhiteBlackGoose** [opencollective/opencollective#7006]
**Describe the bug**

Badges, which show the contributions of a user, don't ever load.

**To Reproduce**
1. Insert [badges](https://docs.opencollective.com/help/financial-contributors/website-badge) somewhere in the website.
2. Open it

It doesn't load.

**Expected behavior**
Like in screenshot from the link

**Screenshots**

![image](https://github.com/opencollective/opencollective/assets/31178401/bcae5c4d-4d87-4615-a9d2-74fb16b55bcb)

![image](https://github.com/opencollective/opencollective/assets/31178401/f2bf24ef-aafc-4022-a7dc-6d9c58d077e4)

**Desktop (please complete the following information):**
 - OS: NixOS
 - Browser: tried firefox & chromium

**Additional context**

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
Hi @WhiteBlackGoose, sorry about the delay on this one. We've just deployed a fix (https://github.com/opencollective/opencollective-frontend/pull/9410)
