### ISSUE TITLE
Onboarding 2fa broken 

### ISSUE THREAD

**Issue by Kiloabqq** [opencollective/opencollective#7017]
After creating a New collective and a new organization 2fa is broken "atleast for me it is"  and in order to complete on boarding 2fa code must be verified. I attempted 2fa using Google Authenticator  on android, Authy on android, Authy on Windows 10 X64, Microsoft Authenticator on Android and tried sever different user agents, Firefox, Edge, Google Chrome for some reason none of the User agents will accept any codes from from any of the authenticator apps, not Windows or android versions.   

**To Reproduce**
1. Go to 'settings'
2. Click on 'security'
3. Scroll down to '2FA'
4. clicking on the empty circle does not select authenticator add bubble it simple stays white/transparent
5. click on Authenticator+ button a pop up appears with a QR code and Manual text code.
6. enter the manual code into your authenticator app or scan code via auth app and several attems both qr and manual entry Fails with message invalid code.
**Expected behavior**
after step 5 and 6 above are performed and i have entered the timed 6 digit code from the authenticator app.... my account should sync with code and 2fa should be toggled to active. 

**Screenshots**

![2fafaail](https://github.com/opencollective/opencollective/assets/95199064/a78ef5c6-86ce-4c41-8295-eba98f99826b)
![2fa fail](https://github.com/opencollective/opencollective/assets/95199064/dadca6da-8d1a-4fac-9869-e68b261c03c1)

![2fafaoil3](https://github.com/opencollective/opencollective/assets/95199064/f8566839-cd64-4788-97f2-5bfe23e3558c)

**Desktop (please complete the following information):**
 - OS:  Windows 10 Home 22H2 OS Build:19045.3448- Windows Feature Experience Pack 1000.19044.1000.0
 - Browser: firefox Version 117.0.1 (64-bit) / Microsoft Edge Version 117.0.2045.43 (Official build) (64-bit)

- Version: 22H2

**Smartphone (please complete the following information):**
 - Device: Motorola Edge Plus 5G UW (2022)
 - OS: Android 
 - Browser: firefox / chrome
 - Version: 13

**Additional context**
I even attempted to use the 1password option but could not figure out how to use it in the current configuration

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by coxkevin44** [comment]
#6262

**Comment by Betree** [comment]
@Kiloabqq could it be that the date/time on your machine was not set correctly? If your machine's time is too far away from our server's time, 2FA will fail. Have you tried setting up 2FA on different websites (i.e. Google) to see if that works?

**Comment by Kiloabqq** [comment]
yes time is correct and yes on android and windows 2fa for other apps works
fine

**Comment by Betree** [comment]
@Kiloabqq Which 2FA authenticator app are you using?
