### ISSUE TITLE
Slack invite URL needs to be renewed very often

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7023]
We're using Slack as an open place (anyone can join). It's an edge case they're apparently not very interested about - most people go to Discord or Mattermost to have this - and to make it work we have to use a workaround where we generate public invite links. They've recently reduced the quota for these links: each one is now limited to 400 uses; which means we have to renew the links quite often (this one could maybe be automated).

This has beed [discussed](https://opencollective.slack.com/archives/GSNDVCC4F/p1649893293274459) and manually updated for quite some time now, but recently the number of times a link can be used have significantly decreased which forces us to renew it very often. To make things worse, we don't have any automated alert when the link expires, so we're left with @Betree, which is not a very stable approach.

Two things could help improving this:

1. **Automatically detect when the link is dead.** This might not be straightforward, as the page is rendered with JS it's not obvious how this information is fetched. Here's an expired link to investigate: https://opencollective.slack.com/join/shared_invite/zt-1zffgu7io-v_pFWI3aaONo1HAIAkQLgA?nojsmode=1
2. **Auto-renew the link.** Maybe we can do that through their API? See https://github.com/opencollective/opencollective-tools/tree/main/slack

**Comment by thibaudcolas** [comment]
For what it’s worth, I believe we have this automatic detection set up on a project I work with. We use an expired link and the "production" link and compare the results, from what I could figure out. Then we have an incoming webhook pinging a Slack channel. I can try to locate the code for this if it helps.

I forget where but I think I’ve also heard Slack support was able to generate invite links for thousands of users at a time.

**Comment by Betree** [comment]
> For what it’s worth, I believe we have this automatic detection set up on a project I work with. We use an expired link and the "production" link and compare the results, from what I could recall. Then, we have an incoming webhook pinging a Slack channel. I can try to locate the code for this if it helps.

Interesting! Would love to see the code if you have that. The last time I checked, it didn't seem like a very straightforward path: there's no special HTTP code to catch, and the page's content is generated with JS so it looked like we would have to render it before we can detect anything.

> I forget where but I think I’ve also heard Slack support was able to generate invite links for thousands of users at a time.

Could be, they used to allow that from the interface a while ago, which made this less of a problem - the link was expiring less often.

**Comment by Betree** [comment]
This won't be an issue anymore as we're migrating to [Discord](https://discord.opencollective.com/).
