### ISSUE TITLE
Ledger update for payment processor fees and taxes

### ISSUE THREAD

**Issue by iamronen** [opencollective/opencollective#7025]
## User story 
> As we engage with we need to catch up with some known ledger technical debt. Payment processor fees and taxes are currently stored as values within transactions. This creates frictions for anyone dealing with accounting and makes it difficult to export complete and reliable data that can be transferred to accounting systems.

## Best solution for this problem
Enhance the ledger to create separate transactions to account for payment processor fees and taxes.

[Coda reference](https://coda.io/d/_dnHLKv7oLV0#Projects_tusx8/r112&view=modal)

**Comment by BenJam** [comment]
just having a discussion about this, we might want to talk about a previous design that @aminakazi worked on in which we made processor fees clearer.

**Comment by aminakazi** [comment]
Related transaction updates figma file: https://www.figma.com/file/2gSaMuWjJIhzyFVC2OijNP/%5BOC.com%5D-Platform-features-%E2%9A%A1%EF%B8%8F?type=design&node-id=5925-36153&mode=design&t=IhfEqnddQ2Q5LRGC-11

**Comment by BenJam** [comment]
@znarf and @Betree to start mapping out changes that need to be made to support migration this week.

**Comment by znarf** [comment]
Some links on how we've done this for Payment Processor Fees:
- https://github.com/opencollective/opencollective-api/pull/6114

**Comment by znarf** [comment]
- [ ] Create configuration to separate Payment Processor Fees
- [ ] On Transaction creation (CONTRIBUTION, EXPENSE) handle the ability to separate Payment Processor Fees
- [ ] Modify various "netAmount" computations to incorporate Payment Processor Fees
- [ ] Create migration, 3 options:
  - [ ] No migration, activation on 2024-01-01
  - [ ] Migration until 2023-01-01
  - [ ] Full migration (may be unnecessary if we consider old transactions archived, and not counted in balance computation)
- [ ] Create ledger snapshots that highlight all scenarios (refunds ...)
- [ ] Migrate metabase dashboards (OC Inc. revenue dashboard)
- [ ] Interface work
  - [ ] In the Collective transactions, we recommend to stop displaying fees as main transactions, but display them in the transaction they belong (contribution, expense)
  - [ ] In Host transactions, if displayed as detailed transactions (in a table) always display them separate
  - [ ] Check individual transactions (e.g.: https://opencollective.com/babel/contributions/171905)

**Comment by BenJam** [comment]
@hdiniz sync up on plan and decide whether to pick up any of the work this sprint.

**Comment by znarf** [comment]
Duplicate with: https://github.com/opencollective/opencollective/issues/4623

**Comment by iamronen** [comment]
@znarf in regard to the payment processor fee transactions, what accounts are you going to be crediting?

**Comment by znarf** [comment]
@iamronen some global Vendors (not attached to the host in particular) that we are creating for this feature

https://github.com/opencollective/opencollective-api/pull/9491/files#diff-acab804c558e37795b64beb0b54a50fe5efbe468ea76d2ca9c63d243a6545a73R7

**Comment by iamronen** [comment]
@znarf I think it may be better to have host specific payment processor vendors (that the hosts cannot modify).

This will maintain the integrity of the vendors concept because the payment processor ARE host vendors:
 - They should appear in the vendors list
 - A host can look at a payment processor vendor and see all their transactions.

Alternately, if you choose to go with global, we may need to consider creating UX exceptions to make the global vendors appear like are host vendors in the UI (and only show the transactions related to that host). 

+ I still suspect that there may be a (future - accounting related) case for expanding the scope of exported transactions to include vendor transactions ... which may also be cleaner and easier to extract and export.

**Comment by Betree** [comment]
Seems to be done, should we close?
