### ISSUE TITLE
Add comparison information to expense attachment previews

### ISSUE THREAD

**Issue by iamronen** [opencollective/opencollective#7031]
## User story 
> As a fiscal host admin when previewing an attachment I am comparing the information submitted by the user to the information in the attachment. The attachment overlay hides the information I need to compare to.

## Best solution for this problem
Add to the attachment preview the expense information so that the fiscal host admin can compare what was submitted to what is show in the invoice:

![Image](https://github.com/opencollective/opencollective/assets/8337819/cb5e0350-9ac3-454d-8273-059c857eccd6)

**Comment by aminakazi** [comment]
Figma file can be [found here](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?type=design&node-id=21801-32872&mode=design&t=p0CmW8tXZvMor1yx-11)

**Comment by iamronen** [comment]
@aminakazi I think there may be situations where this design needs to allow for multiple line items to show up:  a single invoice can be related to numerous line items

**Comment by aminakazi** [comment]
Based on feedback from the team, the design proposal was updated. 
[Figma File](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?type=design&node-id=21801-32872&mode=design&t=8N3Qo4wEBmoR4SyD-11) and [Loom Demo](https://www.loom.com/share/517d0b806cb34b8a9a78184b447d885a?sid=bb53c250-bfe0-42a6-bb83-3d7a7982b98c)
