### ISSUE TITLE
Transform “merchant status” area into an expense pipeline overview

### ISSUE THREAD

**Issue by iamronen** [opencollective/opencollective#7032]
## User story 
> I am a fiscal host admin and I need to make sure that at any given time there are enough funds in my merchant accounts to pay the expenses that are ready-to-pay.  Currently I look at the expense total at the bottom of an expenses page and then multiply that by the number of pages of expenses and try to make a rough guess about the available balances. 

## Best solution for this problem

Transform the “merchant header information” on top of the fiscal host expenses screen into a useful overview of the expense pipeline based on the fiscal host primary currency.

![Image](https://github.com/opencollective/opencollective/assets/8337819/0cc01e5e-e8d1-4cec-b058-9924b30d86fe)

**Comment by znarf** [comment]
As a related project should we implement a "Pay scheduled to pay" with PayPal like we have with Wise?

**Comment by aminakazi** [comment]
Week 3:
- [ ] Get feedback from team on current progress
- [ ] Finalise UI and demo it

**Comment by iamronen** [comment]
@znarf I am not aware of a need for PayPal based scheduled to pay. The need came in response to EU 2FA legislation that impeded payment processing for OCE.

**Comment by Memo-Es** [comment]
### Design update

https://www.loom.com/share/57aa24ebb70445b09235f8b03b02c11b?sid=83c5c762-7d17-4a81-a362-c4ad23c2399a

| Option A                    | Option B                                                            |
|-----------------------------|---------------------------------------------------------------------|
| Display all options at once | Use a selector to have the option of hiding payout merchant options |
|             ![Image](https://github.com/opencollective/opencollective/assets/49539954/4bf11910-5a85-4f90-a592-441782bc96ee)            |                  ![Image](https://github.com/opencollective/opencollective/assets/49539954/8002a7fa-82de-4b2d-9ff0-604f7b897ce5)

[Figma file](https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab-%F0%9F%A7%AA?type=design&node-id=23374%3A33279&mode=design&t=KQEp7wagccwVdklG-1)

**Comment by iamronen** [comment]
@Memo-Es 
1. I wonder about the overall spacing and the resulting screen real-estate of the design. I am assuming the spacing is inherited from the platform style guide, however it feels to me that in this case this could be customized ... since this is a kind of "dashboard indicator" with minimal interaction?
2. I like the integration of the message status into the row ... however I think there is a case that needs to be addressed ... I initially thought of it as an edge case however I think it is going to be a regular scenario:
    - OCE regulary uses pay-batch to make payments = the green indicator is going to be called for.
    - However, AT THE SAME TIME, OCE may (regularly) have insufficient funds to cover the expenses = the red indicator is going to be called for.
    - They need to be able to co-exist.
3. Overall I still see this as one solution with two phases of implementation:
    - First we build out the full version - this is the MVP.
    - We add an ability to choose which payment processors are displayed (I think this needs to be saved as a user preference).
    - Note: when we do introduce the customizable version - there may be cases where messages (red/green) are not visible to the user. THIS is an edge-case we may not have to solve for since it is reasonable to expect the user to display the payment processor they work with.

**Comment by znarf** [comment]
> I am not aware of a need for PayPal based scheduled to pay. The need came in response to EU 2FA legislation that impeded payment processing for OCE.

@iamronen PayPal Payouts is actually using that pattern, when you pay an Expense it's in reality "scheduled to pay". Then, every hour, a job is executing the batch of Expenses scheduled to pay in the background.

@kewitz think that it would be great to make it look like Wise for consistency, but that's another project and out of scope here.

**Comment by Memo-Es** [comment]
### Design update

After @iamronen's feedback, I did a second design round with these goals: 
 - Reducing the total screen real state of the component
 - Allow multiple notices to show simultaneously for a merchant
 - Reducing as much as possible the amount of data shown at the same time

https://www.loom.com/share/a08dbfbb3e3246b6961e55bfcd110483?sid=0a191bf8-8304-451a-9c79-fb5a3c6be1de

This round resulted in 2 options:

| Option A                    | Option B                                                            |
|-----------------------------|---------------------------------------------------------------------|
| Tab navigation including an "All" option | All merchant options partially displayed with collapsable details section |
|            ![Image](https://github.com/opencollective/opencollective/assets/49539954/d348b27b-3145-462c-8bb9-b617d89a147e)            |                 ![Image](https://github.com/opencollective/opencollective/assets/49539954/638bc031-aa5f-443e-b43e-f596d2a4d519)

I prefer option A for its simplicity and adaptability.

**Comment by Memo-Es** [comment]
### Design results

| All merchants                    | Merchant selected + Pay Batch                                                          | Merchant selected + Refill Balance                                                          |
|-----------------------------|---------------------------------------------------------------------|------------------------------------|
|  |  |
|            ![Image](https://github.com/opencollective/opencollective/assets/49539954/4e099099-bce6-4951-8b00-d54435c34fea)            |                ![Image](https://github.com/opencollective/opencollective/assets/49539954/35c9df29-f315-48ac-afa7-17a4a87d4d56)    |  ![Image](https://github.com/opencollective/opencollective/assets/49539954/af1c91a3-5f72-4514-a3c9-2c9ae600bcc9)

[Production-ready file
](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?type=design&node-id=21865-14189&mode=dev)

**Comment by iamronen** [comment]
@Memo-Es 
1. Why does the visual layout change between "All Merchants" and one selected merchant?
2. The "Pay Batch" button is needed also on the "All Merchants" option.

**Comment by Memo-Es** [comment]
### Design results

| Default view                    | Notice                                                 | Notice X2                                                      |
|-----------------------------|---------------------------------------------------------------------|------------------------------------|
|  |  |
|            ![Image](https://github.com/opencollective/opencollective/assets/49539954/1555a4bd-5194-494e-8ed2-bbf6dc13d7b4)           |                ![Image](https://github.com/opencollective/opencollective/assets/49539954/e2216e40-2db2-498b-80be-672b780ffbb7)   |    ![Image](https://github.com/opencollective/opencollective/assets/49539954/906f67c5-2c8d-40b2-9eb2-23ccce7608e9) 


[Production-ready file
](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?type=design&node-id=21865-14189&mode=dev)


@aminakazi @hdiniz

**Comment by iamronen** [comment]
In Notice X2 the bottom notice should use the same wording as the top notice.

**Comment by aminakazi** [comment]
Proposed design solution:
[Figma File](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?type=design&node-id=22035-10338&mode=design&t=8N3Qo4wEBmoR4SyD-11) and [Loom Demo](https://www.loom.com/share/53f8629312de4001a89f44dbf93fa2c2?sid=193ea1a3-e750-44ac-8970-0f39b0a84ffa)

**Comment by BenJam** [comment]
hey @hdiniz do you know why Open Source Collective doesn't appear to have a Paypal balance on its dashboard?

**Comment by hdiniz** [comment]
OSC was missing a paypal connected account parameter, I added to it now.
