### ISSUE TITLE
banner.md serving a 404

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#704]
This collective is waiting on this to be fixed so they can add badges and launch 
https://opencollective.com/wireflow/banner.md

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by xdamman** [comment]
Where is that referenced? They shouldn't need it.

**Comment by piamancini** [comment]
@xdamman  https://github.com/opencollective/opencollective/wiki/Github-banner

**Comment by xdamman** [comment]
Should update that. Old doc. @asood123 can you make the PR to their repo using the command line?

**Comment by piamancini** [comment]
ok. @xdamman Is there a way for them to do it themselves?

**Comment by piamancini** [comment]
closing this since it's not longer relevant.

**Comment by piamancini** [comment]
also moved the wiki topic from home to https://github.com/opencollective/opencollective/wiki#deprecated

**Comment by Hypnosphi** [comment]
@xdamman What's the recommended way of showing backers and sponsors in GitHub's `README.md`. One cannot use scripts there
