### ISSUE TITLE
Email expense editors when host admin changes the accounting category

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7053]
Part of https://github.com/opencollective/opencollective/issues/7028

**Only for the hosts with expense categorization policies enabled (https://github.com/opencollective/opencollective/issues/7051)**.

1. When a fiscal host admin edits an expense to select a different category than the one selected by the **expense submitter**, email the expense submitter to inform them about the change (for education purposes).
2. When a fiscal host admin edits an expense to select a different category than the one selected by the **collective admin**, email the collective admin to inform them about the change (for education purposes).

**Comment by Betree** [comment]
# Email template proposal

**Subject:** Your expense to {collective} has been re-categorized

> Hi {name},
> 
> We are writing to let you know that an admin of {host}, {collective}'s fiscal host, has re-categorized one of your expenses:
> * Expense name: [Expense name & link]
> * Original category: {originalCategory}
> * New category: {newCategory}
> 
> The host admin changed the category to better match the purpose of the expense and their accounting system.
> 
> **How to avoid this in the future**
> 
> To avoid having your expenses re-categorized in the future, please try to submit them with the most accurate category possible. 
> 
> We appreciate your cooperation and understanding.
> 
> Sincerely,
> The {host} team

**Comment by iamronen** [comment]
proposal to expense submitter

Subject: Your expense to {collective} has been re-categorized

> Hi {name},
> 
> We are writing to let you know that the expense you submitted to {collective} was reviewed by their fiscal host {host} and in the process the expense category was changed. 
> 
>  - Expense title: [Expense name & link]
>  - The expense category you selected: {originalCategory}
>  - The expense category selected by the fiscal host: {newCategory}
>
> The category selected by the fiscal host administrator better matches the contents of the expense you submitted. 
> 
> **You don't need to do anything**. This message was sent to let you know about the change as a reference for future expenses. 
> 
> Sincerely,
> The {host} team

**Comment by iamronen** [comment]
proposal to collective admin

Subject: An expense you approved on behalf of your collective {collective} has been re-categorized

> Hi {name},
> 
> We are writing to let you know that an expense you approved on behalf of your collective {collective} was reviewed by your fiscal host {host} and in the process the expense category was changed.
> 
>  - Expense title: [Expense name & link]
>  - The expense category you selected: {collectiveCategory}
>  - The expense category selected by the fiscal host: {newCategory}
> 
> The category selected by the fiscal host administrator better matches the contents of the expense you submitted.
> 
> **You don't need to do anything**. This message was sent to let you know about the change as a reference for future expenses. 
> 
> Sincerely,
> The {host} team

**Comment by iamronen** [comment]
flagging a trap:
Ideally these notification should only be sent on first review: when an expense is paid.
However, a fiscal host admin can continue to change expense categories indefinitely - they may do this to make corrections or adjustments. However, such changes should not trigger additional notifications as that would create too much confusion and noise.

**Comment by Betree** [comment]
Some constraints we'd like to enforce:
- Don't send the email if already sent for this expense in the past
- Don't send if the expense was submitted more than 1 month ago
- Could be done in an async job, to be agnostic of the host admin process

**Comment by Betree** [comment]
Let's wait for https://github.com/opencollective/opencollective/issues/7209 to implement this one, as we don't want to send the email if the host admin selects a category that the user can't use.

**Comment by iamronen** [comment]
just to say that while there is a logical dependency between the two, all the expense categories that currently exist are accessible to expense submitters and collective admin.
hosts will be able to add "host only categories" only after we make this available to them.

**Comment by Betree** [comment]
Running a naive query shows that ~20% of users concerned by this check got it wrong on multiple expenses in a short period. As suggested in the kickoff, I'll implement batching in the email as it doesn't add too much complexity.

```sql
SELECT e."UserId", COUNT(e.id)
FROM "Expenses" e
INNER JOIN "AccountingCategories" ac ON e."AccountingCategoryId" = ac.id
WHERE e.status = 'PAID'
  AND e."updatedAt" > NOW() - INTERVAL '7 days'
  -- Make sure submitter/collective admins were allowed to pick this category
  AND ac."hostOnly" IS FALSE
  AND (ac."expensesTypes" IS NULL OR e.type = ANY (ac."expensesTypes"))
  -- Only entries where the submitter/admin picked a different category
  AND (
        e."data" #>> '{valuesByRole,collectiveAdmin,accountingCategory,id}' != ac.id::text
    OR e."data" #>> '{valuesByRole,submitter,accountingCategory,id}' != ac.id::text
  )
GROUP BY e."UserId"
ORDER BY COUNT(e.id) DESC
```

**Comment by Betree** [comment]
Copy-pasting an explanation of the algorithm shared in another thread here for context:

1. Get all recently paid expenses for fiscal hosts that have a chart of accounts defined and a policy that requires people to contribute to the categorization efforts
2. Filter out the ones that have no accounting category set
3. Filter out the ones where the host admins picked a category that the submitter/collective cannot select (i.e., host-only categories)
4. Filter out the ones where the expense category picked by submitter/collective admin are correct
5. Filter out the ones that were submitted more than one month ago
6. Group "mistakes" by user
7. Send a bundled email with all the mistakes made by the user

**Comment by shannondwray** [comment]
Could you send through another screenshot of the multiple expense submitted, the logo at the bottom didn't seem to render

**Comment by Betree** [comment]
@shannondwray Here it is

![307298596-262ed4ff-02c1-423f-b3a5-760857ead1a8](https://github.com/opencollective/opencollective/assets/1556356/e97b63ae-7e5c-48b3-8611-c77c637b5882)
