### ISSUE TITLE
Admin interface to edit chart of accounts

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7059]
Part of https://github.com/opencollective/opencollective/issues/7028

In the Host Workspace, add a new “Accounting” entry in the "Fiscal Host Settings". The only category for now will be “Chart of accounts”, to let host admins edit their chart of accounts.

**Comment by Betree** [comment]
Demo:

https://github.com/opencollective/opencollective/assets/1556356/f0bf18e7-e00b-497e-b04a-a5d234bc2810

cc @Memo-Es

**Comment by Memo-Es** [comment]
@Betree 

https://www.loom.com/share/1f412c31f45b4ee6b19ba25bf50f9f2d?sid=a1204d5f-9f99-489e-85cc-85912e23be95

[Figma file](https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab-%F0%9F%A7%AA?type=design&node-id=23512%3A151027&mode=design&t=UL2nrmndFPRHP0fj-1)

**Comment by Betree** [comment]
@Memo-Es This issue will be resolved with https://github.com/opencollective/opencollective-frontend/pull/9467, we'll track the UI improvements in https://github.com/opencollective/opencollective/issues/7062
