### ISSUE TITLE
logged in user can't edit his expense

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#706]
User is logged in (on mobile) with the email he used and can't see the EDIT button in the expense: 
![screenshot_20171201-004114](https://user-images.githubusercontent.com/3671070/33443008-78e284e2-d5c4-11e7-9072-968568583feb.png)

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by piamancini** [comment]
keeping this opened since now this #713

**Comment by xdamman** [comment]
Fixed

**Comment by xdamman** [comment]
(need to go to /expenses - can't edit from homepage, there is not enough room to show the edit form)

**Comment by piamancini** [comment]
@xdamman can we add a link to 'edit expenses' somewhere? how will users know where to go?
