### ISSUE TITLE
Add funds date defaulting to previous day

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#7069]
When you use `add funds` there is a date field, which should default to the current day. It's defaulting to the previous day for me. 

<img width="738" alt="Screen Shot 2023-10-20 at 10 57 54 AM" src="https://github.com/opencollective/opencollective/assets/5498878/56801af6-7bb3-4d54-b4cc-834f8daadec0">

This could be due to the date line, but this feature should always reference local time.

**Comment by Betree** [comment]
This probably affects the confirm contribution modal as well; we're using a function named `getCurrentDateInUTC` that returns the UTC date rather than the one using the local timezone. Should be a simple fix.
