### ISSUE TITLE
query for new collectives in the past 2 weeks and daily

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#707]
With creators email addresses. So @nicobarretoOC can manually email them a first nudge. 

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by asood123** [comment]
Query to get this data in the future (change the date):

```sql
select 
	c.id as "collectiveId", 
	slug, 
	c."createdAt" as "collectiveCreatedAt", 
	"HostCollectiveId", 
	tags,
	u."firstName" as firstname,
	u."lastName" as lastname,
	u.email as email
from "Collectives" as c
left join "Users" u on c."CreatedByUserId" = u.id
where 
	type ilike 'collective' 
	and c."deletedAt" is null
	and u."deletedAt" is null 
	and c."createdAt" > '2017-11-15';
```

**Comment by piamancini** [comment]
added to wiki [here](https://github.com/opencollective/opencollective/wiki/Queries-for-collectives#new-collectives-for-the-past-xx-and-creator-details)
