### ISSUE TITLE
Bullet Button in Rich Text Editor Broken

### ISSUE THREAD

**Issue by majora2007** [opencollective/opencollective#7071]
**Describe the bug**
When you click the bullet point in the Rich Text Editor, for an announcement, it doesn't insert a bullet point. 

**To Reproduce**
1. Go to your collective
2. Create a new Update
3. On an existing or new line, press the bullet point button
4. See nothing happen

**Expected behavior**
A bullet point is created

**Screenshots**
![image](https://github.com/opencollective/opencollective/assets/735851/140b19ba-ad2e-4330-9200-0ac05c6a82cd)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: FF 
 - Version: 118.0.2

**Additional context**
This has been broken for some time but used to work. Looking back at my Collective's updates, the existing bullet points are no longer present, see https://opencollective.com/kavita/updates/v0-7-7-localization

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
Hi @majora2007, we've just deployed a fix for this issue. Thanks for reporting it!
