### ISSUE TITLE
Cannot Edit Email in Already Sent Expense Invite 

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7080]
**Describe the bug**

This has been reported several times in Fresh-desk, recent report being; https://opencollective.freshdesk.com/a/tickets/279098. It seems that users are unable to change the email of an already sent expense invite. 

**To Reproduce**
1. Send and expense invite to an email
2. Edit the expense and try to change the invitee email
3. While it seems to have changed, when you refresh the page the old email is still there

**Expected behavior**

Editing the email of an expense invite should be possible.

**Screenshots**

[invite-edit-email.webm](https://github.com/opencollective/opencollective/assets/12435965/1bd904d7-4219-4252-bf3c-139d69afacc8)

**Comment by Betree** [comment]
We may want to prevent changing the invitee email for now if that's too complex to fix

cc @kewitz

**Comment by shannondwray** [comment]
A fix for this please!! Very confusing and frustrating, it lets you change the email and even resend the invite to the new email. Then when I refreshed it, it just reverted
