### ISSUE TITLE
Wrong "Last Charge" on Dashboard > recurring contributions

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7084]
**Describe the bug**
When looking at my dashboard > Contributions, all "Last Charge" dates are wrong. Instead of the last charge date, they seem to be set on the first charge date.

![image](https://github.com/opencollective/opencollective/assets/1556356/ad3079a2-78ab-4dc6-b77d-3dc7dfbf401c)

**Expected behavior**
Looking at the code, it seems that we're relying on `order.processedAt` - which contains the date of the **first** successful payment. So:
- Either that's what we want, and we should rename the column to "Start date"
- Or we do want the last charge date, and then we should get the information from somewhere else

cc @gustavlrsn

**Comment by gustavlrsn** [comment]
Good catch! I guess the intention has probably been the last charge date as that seems more relevant. cc @kewitz

Given that we have `nextChargeDate` on orders in the GraphQL API, maybe a `lastChargeDate` could make sense also. Another option to displaying this date could be a better pathway from this contributions list to the actual transactions.

For now, as a quick-fix, I'll open a PR to remove this column.

**Comment by Betree** [comment]
Closing as the root bug is resolved, we'll look into doing things properly if we ever re-introduce the column
