### ISSUE TITLE
Responsiveness/z-index issue on Dashboard (transactions, expenses)

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7085]
Happening on:
- https://opencollective.com/dashboard/betree/submitted-expenses
- https://opencollective.com/dashboard/betree/transactions
- https://opencollective.com/dashboard/betree/payment-receipts

![Kooha-2023-10-27-11-39-54](https://github.com/opencollective/opencollective/assets/1556356/2e356816-092a-4e6f-8e4c-6e5d43271262)

**Comment by ParthMakode** [comment]
do you have any dummy account to work with that i can see the issue with?
i guess even if i setup locally it will ask me to create / some legit account with a 100 star repo

**Comment by Betree** [comment]
> do you have any dummy account to work with that i can see the issue with?
> i guess even if i setup locally it will ask me to create / some legit account with a 100 star repo 
> @Betree 

You don't need an account to test this issue, you can simply go to the transactions page for any active collective (eg. Apex, Babel, etc).

And you can always create collectives without a 100 stars repo, this rule is only meant for applications to the Open Source Collective fiscal host.
