### ISSUE TITLE
Platform Cannot Show Currency Amounts in VND

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7093]
**Describe the bug**

This was inspired from the fresh-desk ticket; https://opencollective.freshdesk.com/a/tickets/282785. It seems that we have integer overflow issues when showing certain currencies which normally translates to very large amounts. Here the example is VND. When a user or collective choose VND as the currency, then several thousands of dollars will translate to a very large number of VND and integer overflows will occur. 

**To Reproduce**
Steps to reproduce the behavior (on staging):

1. Take a user and change the currency of the user to VND
2. Create some contributions from this user so that the total contributed amount is greater than around 8000 USD.

**Screenshots**

[vnd-issue.webm](https://github.com/opencollective/opencollective/assets/12435965/f952c55d-410c-4d9c-be6e-2a25d0c0a1d3)

**Comment by joaoGabriel55** [comment]
I can take a look at

**Comment by Betree** [comment]
This is normally fixed by https://github.com/opencollective/opencollective-api/pull/9581

**Comment by joaoGabriel55** [comment]
> This is normally fixed by [opencollective/opencollective-api#9581](https://github.com/opencollective/opencollective-api/pull/9581)

@Betree, do you think writing a test case for that situation would be good?

**Comment by Betree** [comment]
A GraphQL test would only help a little since we already know the type and its limit. An e2e test could be nice to prevent regressions: add funds with huge amounts (e.g., 2 x $20,000,000,000), then make sure the budget displayed on the collective page is correct.
