### ISSUE TITLE
"Add authenticator" modal closes when you press Enter

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7098]
**To Reproduce**
1. Go to Dashboard > Security
2. Click on "Add Authenticator"
3. Scan the QR code
4. Type your number in your input and press Enter
5. The modal closes without doing anything

**Expected behavior**
It should submit the form, as if clicking on "Verify".

**Screenshots**
![image](https://github.com/opencollective/opencollective/assets/1556356/ad943ec9-c6a2-499e-a6df-b964b39e733b)

cc @hdiniz

**Comment by Betree** [comment]
:gift: :money_with_wings: A **$100** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by Girish4489** [comment]
@Betree Could you please assign this task to me?

**Comment by b4s36t4** [comment]
@Betree I would like to give this a try. I have verified my fix against `opencollective.com` directly, I can raise a PR soon. It's related to accessibility issue.

**Comment by Betree** [comment]
@b4s36t4 Someone's already assigned to the issue. If the PR gets closed and unassigned, you can ask for an assignment. For now, @Girish4489 has the priority.

**Comment by Betree** [comment]
:trophy: This issue has been completed by @Girish4489  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Comment by b4s36t4** [comment]
@Betree I don't think it's a good solution. What if there is a new Input in the modal, do we also need to add the `onKeyDown` handler for that input too?

**Comment by b4s36t4** [comment]
Adding `onKeyDown` doesn't seem like a good solution for me. By default formik will handle the `onSubmit` event when we click `Enter` even though we have `type=submit` button it's not working, because the real issue different. I request you to look at the solution again. I'm not against the attempt, I'm just looking at the possibility of this issue coming again (maybe we have same issue other modals as well).

**Comment by Betree** [comment]
@b4s36t4 The root problem is fixed, and we have no reason to add another input to this modal for now.

If you have a better solution, feel free to propose it; we'd be happy to merge it if it's cleaner or more future-proof. If you detect a similar issue in a different modal, feel free to report it as an issue.
