### ISSUE TITLE
Hosted Collectives improvements

### ISSUE THREAD

**Issue by BenJam** [opencollective/opencollective#7105]
## Overview

This issue originated by a piece of feedback during a call with a user, in which they mentioned that it's confusing to see projects and events as equals as Collectives, especially because they inherit the Collective avatar as a display.

![Image](https://github.com/opencollective/opencollective/assets/49539954/9812737d-81cb-4749-be20-715d79a17f3d)

We can also note that the current card layout is not the ideal display for collectives hosted by fiscal host organizations.

## List of updates

**1. Migrate the card layout to a table**

![Image](https://github.com/opencollective/opencollective/assets/49539954/2e222075-254d-40c8-9bd2-5e2b09f52d7d)

This table features five columns: Collective (Avatar, name, and as a second line, a mention of events and projects, if any), team, fee, hosted since, and balance.

**2. Implement an overview as a drawer**

![Image](https://github.com/opencollective/opencollective/assets/49539954/7b1f330d-94c2-44bf-96d2-65ea637451d7)

   - Hosted since
   - Fee structure
   - Balance
   - Team
   - With a hovercard showing info about the people from the team

![Image](https://github.com/opencollective/opencollective/assets/49539954/9e0a78ca-be7b-45fb-82db-3022e226d0ad)
   

  * Agreements
  * Expense types settings

**Search for projects and events from the list view**

 Searching for a specific project or event shows the main Collective in the results, with an indicator in the events/projects info.

![Image](https://github.com/opencollective/opencollective/assets/49539954/d4ca6824-4281-44fb-93cd-c0fb519ac60f)

  When clicking to open the overview drawer, it directly navigates down and highlights the project or event that triggered the search.
![Image](https://github.com/opencollective/opencollective/assets/49539954/3b733182-551c-4f9a-9acc-603a9787c82b)

**3. Make the projects and events appear inside the overview drawer of the Collective they operate under**

![Image](https://github.com/opencollective/opencollective/assets/49539954/23968e22-dad8-445d-9ba3-81522e39d974)

**4. Add the following actions to the "More actions" dropdown**
- Add funds (Existing)
- Manage Collective (Existing)
- Freeze Collective (Existing)
- Un-host Collective (Existing)
- Add agreement (Existing. Not added)
- Send message (Existing. Not added)
- Submit expense (Not existing. Pending expense submission update)

![Image](https://github.com/opencollective/opencollective/assets/49539954/ce0b0abe-2204-47de-af02-0a4e3085bba0)

https://www.loom.com/share/a05e23f01fb148e2b560a90dc2923d97?sid=16f4a2d2-5529-46b3-9b3d-d0889c91fcfe

Figma file

**Comment by Betree** [comment]
Apart from https://github.com/opencollective/opencollective/issues/7102, it's not clear what's included in this project. https://github.com/opencollective/opencollective/issues/5426 would be a great one to include.

**Comment by BenJam** [comment]
Apologies @Betree , I neglected to port stuff over from Coda. This is a 'nice to have' set of visual updates to the hoted collectives section of the host settings. I agree that, functionally, #5426 would be a better use of a small amount of time

**Comment by iamronen** [comment]
@Betree I think that @Memo-Es included access to the admins in the drawer details ... both seeing the admins and being able to get their emails using hover cards. 

I think that this visual updates creates the conditions to address such issues (revealing admin information) and more. I sense a potential for "Hosted Collectives" to be a much more central tool in fiscal host day-to-day use because of this update (which on the surface seems like "nice to have").

**Comment by Betree** [comment]
@iamronen Yes, @Memo-Es indeed included that in the latest design.

**Comment by kewitz** [comment]
Related to these tabs, what are "Unhosted" collectives in this context? @iamronen @BenJam 
![image](https://github.com/opencollective/opencollective/assets/2119706/eeb85be8-fca5-47d7-8417-195998378545)

**Comment by kewitz** [comment]
Closing this original issue. Feel free to create follow-up issues for iterations in the hosted collectives dashboard.
