### ISSUE TITLE
Add the ability to cancel 2FA modal

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7109]
Followup on https://github.com/opencollective/opencollective/issues/6923

While signing in, if you leave the page when it asks for 2FA, any future visits will ask again for 2FA (because you have a 2FA token stored locally). We can improve this by:
1. Adding a "Cancel" button that instantly clears the 2FA token from local storage
2. Looking at the 2FA token expiry date and ignore it if it's passed (might already be the case)

**Comment by EduardoSCosta** [comment]
Hi, I'd like to take a look at this issue :smiley:

**Comment by Betree** [comment]
@EduardoSCosta It's yours!
