### ISSUE TITLE
Possible wrong pluralisation

### ISSUE THREAD

**Issue by jaysoifer** [opencollective/opencollective#711]
Hi,

I believe there's a pluralisation where none is needed.

URL: https://opencollective.com/vuejs/order/1054
![screen shot 2017-12-01 at 09 47 11](https://user-images.githubusercontent.com/8316698/33473159-fb481c80-d67d-11e7-80e9-6d3ef997dd8f.png)

![screen shot 2017-12-01 at 09 57 33](https://user-images.githubusercontent.com/8316698/33473201-222c54d8-d67e-11e7-99d6-19e48d667b49.png)

**Comment by asood123** [comment]
I have seen this as well. Thanks for reporting.

**Comment by asood123** [comment]
Fix here: https://github.com/opencollective/frontend/pull/129. Live later today.
