### ISSUE TITLE
Search "Reset" icon does not update lists

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7112]
In most places where we search boxes, the reset icon does not update the data presented.

[Kooha-2023-11-15-09-19-33.webm](https://github.com/opencollective/opencollective/assets/1556356/b5764ce2-a925-4250-9b9c-d3a463b8f7d1)

[Kooha-2023-11-15-09-16-09.webm](https://github.com/opencollective/opencollective/assets/1556356/ef041e2b-a0cf-4c29-a406-f76f3826f03a)

**Comment by ArielG1381** [comment]
> In most places where we search boxes, the reset icon does not update the data presented.
> 
> 
> 
> 
> 
> [Kooha-2023-11-15-09-19-33.webm](https://github.com/opencollective/opencollective/assets/1556356/b5764ce2-a925-4250-9b9c-d3a463b8f7d1)
> 
> 
> 
> 
> 
> [Kooha-2023-11-15-09-16-09.webm](https://github.com/opencollective/opencollective/assets/1556356/ef041e2b-a0cf-4c29-a406-f76f3826f03a)
> 
>

**Comment by Betree** [comment]
@Guilherme-NL it's yours!

**Comment by Guilherme-NL** [comment]
thanks @Betree
