### ISSUE TITLE
Inviting an Expense with No Amount Specified Gives Empty Error Bar

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7118]
**Describe the bug**

While trying to invite an expense with the optional amount field left empty seems to give and error. 

**To Reproduce**
1. Go to any collective that you administer
2. Go through the expense flow choosing some other user as the payee
3. Do not specify an amount and leave this input empty

**Expected behavior**

The amount is optional for expense invites and should not pose any error when submitting the expense invite. 

**Screenshots**

![Screenshot from 2023-11-20 14-47-58](https://github.com/opencollective/opencollective/assets/12435965/a6c1551b-e8d3-4d2b-976b-5f3f8b6232ae)

**Comment by SudharakaP** [comment]
This was reported at, https://opencollective.freshdesk.com/a/tickets/283104

**Comment by Betree** [comment]
cc @kewitz, I believe it's the following Sentry issue: https://open-collective.sentry.io/issues/4637984981/?project=5199682&query=is%3Aunresolved+amount&referrer=issue-stream&statsPeriod=90d&stream_index=0.

The missing error message was a simple one, I've pushed a fix for it in https://github.com/opencollective/opencollective-frontend/pull/9637.

**Comment by Betree** [comment]
Related: https://github.com/opencollective/opencollective/issues/6587

**Comment by Betree** [comment]
Adding a hotfix in https://github.com/opencollective/opencollective-frontend/pull/9898 to make the amount required when inviting an expense.
