### ISSUE TITLE
Notifications settings dashboard section not working

### ISSUE THREAD

**Issue by NikitaKorevo** [opencollective/opencollective#7119]
**Describe the bug**

**To Reproduce**

1. Click on the Avatar
2. Click on `Preview Features`, the Dashboard switch must be on
3. Click on Settings / Settings tab / Notification Settings
4. Turn on "Receive the Open Collective newsletter (monthly)" switch 
5. Reload the page
6. The Switch is always off

**Expected behavior**
The Switch can have two states (on or off) after a reloaded page.

**Screenshots**

https://github.com/opencollective/opencollective/assets/48645737/bcbbd493-6111-4f77-8ea1-95a5f0e3b96f

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
@NikitaKorevo Thanks for the report; it appears that the root cause is that the section query is crashing:

![image](https://github.com/opencollective/opencollective/assets/1556356/c1751d0b-da04-4cd4-a856-e8f460adfe64)

Prioritizing a fix since it also means users can't currently manage their notification settings.
