### ISSUE TITLE
Add tests for various tier cases

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#712]
Our Tier setup is pretty complex now and we only have partial test coverage. It's a core part of the flow, so let's add tests for all of them to avoid edge-case bugs.

Here are the cases to cover on the frontend:

- [ ] /donate
- [ ] /donate/:amount
- [ ] /donate/:amount/:frequency
- [ ] /order/:Tierid
- [ ]  - with presets amounts and interval (any amount and interval)
- [ ]  - with fixed amount and interval (ex: $10/monthly)
- [ ]  - with paid tickets (changeable quantity with fixed amount)
- [ ]  - with free tickets (changeable quantity)
- [ ] /:collectiveSlug/events/:eventSlug
- [ ]  - with multiple ticket tier showing on the same page (it's a different route)
- [ ] /redeem
- [ ] Tier Component test cases
- [ ] - Tickets (specific amount with quantity)
- [ ] - Presets (anything goes)
- [ ] - Fixed ($10/monthly)

For each test case,
- verify payment options shows up (if needed)
- tier info (amount, interval, quantity, presets) is displayed correctly
- order amount is displayed correctly (on orderForm)
- if changeable, UI changes appropriately
- order is generated to send to backend appropriately

**Comment by piamancini** [comment]
marking this with a label for when someone takes on tiers refactoring
