### ISSUE TITLE
Button Widget Not Working - Redirecting to Donate Page

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7120]
**Describe the bug**

As per the documentation https://docs.opencollective.com/help/collectives/widgets we used to have the button widgets whereby when the user goes to for example https://opencollective.com/warzone2100/donate/button.js the donate button is displayed. However this doesn't seem to work anymore and the url redirects to the donate contribution flow instead.

**To Reproduce**
1. Go to https://opencollective.com/warzone2100/donate/button.js
2. Note the redirection 

**Expected behavior**

A donate button such as the one shown in the [documentation](https://docs.opencollective.com/help/collectives/widgets) should be displayed.

**Comment by SudharakaP** [comment]
This is reported at, https://opencollective.freshdesk.com/a/tickets/294271

**Comment by past-due** [comment]
This also impacts the image URLs mentioned further down on that documentation page:

> If you want to add a donate button to a blog post, you can load an image version of the logo and then link to the donate page of your collective.
> ```
> <a href="https://opencollective.com/webpack/donate" target="_blank">
>   <img src="https://opencollective.com/webpack/donate/button@2x.png?color=blue" width=300 />
> </a>
> ```

For example,
https://opencollective.com/webpack/donate/button@2x.png?color=blue used to show the image.

**Comment by SudharakaP** [comment]
Also reported at, jon-jeter

**Comment by Betree** [comment]
Could be related to https://github.com/opencollective/opencollective-frontend/pull/9620, maybe the priority order of the routes in `rewrites.js` is causing these troubles

**Comment by iangilman** [comment]
@Betree thank you for the speedy fix!
