### ISSUE TITLE
Preview features window displaying underneath

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#7137]
**Describe the bug**
When clicking preview features it isn't showing above the settings panel 

**To Reproduce**
1. Go to the right side profile settings selector 
2. Click on preview features 

<img width="1240" alt="Screenshot 2023-12-01 at 12 48 32 PM" src="https://github.com/opencollective/opencollective/assets/79115149/d20f3790-6b78-4896-bc74-0cc5dfcfd842">

**Expected behavior**
The module to appear above, so it can be manipulated 

**Screenshots**
Above

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma Version 14.2 Beta 
 - Browser: Chrome
 - Version: 115.0.5790.170

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
I'd say clicking on "Preview Features" should close the user menu

**Comment by Betree** [comment]
cc @gustavlrsn

**Comment by shannondwray** [comment]
It's happening for news and updates as well

**Comment by shannondwray** [comment]
And on Safari

**Comment by gustavlrsn** [comment]
> I'd say clicking on "Preview Features" should close the user menu

Agree, opened issue here: https://github.com/opencollective/opencollective/issues/7143
