### ISSUE TITLE
The language switcher is breaking the display on mobile resolutions, causing responsiveness issues.

### ISSUE THREAD

**Issue by Guilherme-NL** [opencollective/opencollective#7139]
**Describe the bug**

When selecting an option with a large text in the language switcher box, the OpenCollective logo next to it is compressed or even breaks the resolution, as is the case when selecting 'Brazilian Portuguese - Português brasileiro'.

- logo compressed:
![image](https://github.com/opencollective/opencollective/assets/102393263/14817508-6b62-433a-af54-ccf753fe0cd4)

- break of resolution:
![image](https://github.com/opencollective/opencollective/assets/102393263/ff91f1dd-1ded-4d5b-a970-63608f14fca5)

**To Reproduce**
1. Go to '/'
2. Scroll down to footer
2. Click on 'language switcher'
3. Select 'Brazilian Portuguese - Português brasileiro'

**Expected behavior**
![image](https://github.com/opencollective/opencollective/assets/102393263/76f79075-201d-4487-99b0-42c3cefe9579)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Chrome

**Comment by Guilherme-NL** [comment]
If it's okay, I can solve this issue and others related to responsiveness, like:
https://github.com/opencollective/opencollective/issues/7058
https://github.com/opencollective/opencollective/issues/7057

If there's another open issue related to responsiveness, I'd be happy to help.

**Comment by Betree** [comment]
@Guilherme-NL Such a contribution would be greatly appreciated if you have the time. Just make sure you make one PR per issue; it helps with reviews and rollbacks (in case of unspotted regressions).

cc @gustavlrsn

**Comment by Guilherme-NL** [comment]
No problem @Betree, It would be great to help with these issues
