### ISSUE TITLE
Ability to filter TransactionsCollection on Contribution and Expense ID

### ISSUE THREAD

**Issue by gustavlrsn** [opencollective/opencollective#7144]
As part of https://github.com/opencollective/opencollective/issues/7106 we've identified the need to link related transactions from the contribution and expense views:
> An ability to, in the front end, link from contribution and expense views to their related transactions.

In order to achieve that we could add two arguments to the transactions collection resolver:

```
order: OrderReferenceInput
expense: ExpenseReferenceInput
```

**Comment by gustavlrsn** [comment]
@Betree made me aware that filtering on expense and contribution ID's is currently possible through the text filter: https://github.com/opencollective/opencollective-api/blob/24de8578c7c19d34f3249256a85b18f2facb2d01/server/graphql/v2/query/collection/TransactionsCollectionQuery.ts#L250

**Comment by Betree** [comment]
Note that, even though achieving that through the text filter is already possible, a dedicated input will still be welcome as the text filter is a `OR`, which is less precise (it will return both expenses **and** contributions matching the ID).
