### ISSUE TITLE
Add collective cover for open source host

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#715]
I credited bloomberg's $5k to Open Source Host (not open source collective). It shows up at
https://opencollective.com/bloomberg-beta but the OS Host has no collective cover. Is there one we can add @piamancini?

**Comment by piamancini** [comment]
@asood123 not sure I'm following. Is this what you are after? opencollective.com/opensourceorg

**Comment by asood123** [comment]
Could we add a background image to opensourceorg? Otherwise, it looks weird on bloomberg-beta page with just a white background

**Comment by piamancini** [comment]
looking

**Comment by piamancini** [comment]
@asood123 done. looks better now on bloomberg-beta Do you have a logo for them we can use on their page

**Comment by piamancini** [comment]
disregard, found one online
