### ISSUE TITLE
Exemplary deployment for `opencollective-taxes`

### ISSUE THREAD

**Issue by abitrolly** [opencollective/opencollective#7160]
## Who is your user?

Contributors (people and companies) in a specific country, who could use online tax calculator.

## What are they trying to achieve?

Planning their budgets, know how much they can send, how people will receive, and what is the structure of the difference between, including taxes. What kind of taxes apply. how do they relate to other deduction. So that in the end they can provide accurate reporting to their investors and resolve disputes with tax authorities or banks in case of mistakes, and fix those mistakes.

When tax information is incorrect, they want to be able to fix it, so that they stay updated.

When they see https://github.com/opencollective/opencollective-taxes repo, they want to immediately play to see what is all about.

## How are they currently doing this?

Manually. Hiring special people to calculate that stuff. If they have the possibility. Otherwise they just don't know where the money go, and just accept this as is, which is not how they'd like to treat their finances.

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [x] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by abitrolly** [comment]
@Betree documentation how to use the library.

**Comment by Betree** [comment]
As it is today, this library is not meant for public use; it's specialized for the Open Collective's model. Depending on what you're trying to achieve, I can recommend looking into JSVAT or alternative libraries.

**Comment by abitrolly** [comment]
@Betree  so what is required to change that decision?
