### ISSUE TITLE
Changing the Email Address of a Invited Expense

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7163]
**Describe the bug**

This issue was reported at the slack thread; https://opencollective.slack.com/archives/GFH4N961L/p1702663040491629. Trying to change the email address of an already submitted expense invite seems to error out giving; 

![image](https://github.com/opencollective/opencollective/assets/12435965/d3ab8d2b-ffd3-41ab-a3c2-d975efbc99be)

**To Reproduce**
1. Go to a collective and invite an expense (make sure to choose a non existing user on the platform; i.e: set the name and email manually)
2. Go to the draft expense submitted and click on the actions button and edit the expense
3. Change the email address and try to save

**Expected behavior**

A payout method should not be expected from an expense that is invited; since the user is going to set the payout method in the future.

**Comment by Betree** [comment]
cc @kewitz

**Comment by SudharakaP** [comment]
While I could reproduce this issue on production for this specific expense, I cannot reproduce this on staging. I'll keep and lookout if this issue occurs again and re-open this issue if necessary.
