### ISSUE TITLE
Add an easily-filterable collective name/id to an email header

### ISSUE THREAD

**Issue by colindean** [opencollective/opencollective#7173]
I'm trying to improve my email filters and a part of that is ensuring that I don't miss something important. To that end, I'm creating some filters that help me better manage email related to my collectives.

If I just filter on _sender From address_ then I'd mix less actionable personal OC items in with more actionable collective stuff, and esp. very important emails that require action, like attaching receipts. I know virtual cards are going away soon, but I expect many other categories of emails to be filterable. I'd really like to filter on headers related to the collective!

If I filter on _email subject_, I can filter by event type, but not really by collective.

I notice on most emails from OC, there is an `X-Mailgun-Tag` header, e.g. `virtualcard.purchase` on a recent email regarding a virtual card purchase needing a receipt. 

**Could you also include a header that says which collective generated the email?**

For example:

```yaml
X-OpenCollective-Collective: #{collective.name}
```

or, perhaps using the standard:

```yaml
List-ID: #{collective.name}
```

An alternative could be for OC to include the collective name in the From address, e.g. `info+collective@opencollective.com`.

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [X] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by SudharakaP** [comment]
Relevant Fresh-desk ticket can be found at, https://opencollective.freshdesk.com/a/tickets/305715

**Comment by samkevin1** [comment]
Hey! I can take a look at this one.

**Comment by samkevin1** [comment]
@Betree Should maildev work just by running `npm run dev`?

**Comment by Betree** [comment]
> @Betree Should maildev work just by running `npm run dev`? 

Yes, try to open http://localhost:1080/#/ after starting the API, maildev should be there.
