### ISSUE TITLE
Recurring Expense Submission Error With Exchange Rates

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7185]
**Describe the bug**

It seems that with the recent changes to the expense flow to show the exchange rate we've introduced a regression. I've seen this several times with recurring expenses but I think it applies for all types of expenses.

**To Reproduce**
1. Create a expense go in the expense flow until the page where Invoice Details are entered
2. Do not change the currency, and make sure to enter just a value for the amount (and description)
3. Try to save the expense

**Expected behavior**

Should not give any errors

**Screenshots**

![image](https://github.com/opencollective/opencollective/assets/12435965/115ccdd7-6e91-481a-bdd3-2c72c7b5e6df)

As can be seen it gives an error. A workaround for this is to change the currency to a different one and then back to the original one. Initially (if we don't touch the currency drop-down) the page looks like this.

![image](https://github.com/opencollective/opencollective/assets/12435965/3cd5f523-72c6-4c9c-a03c-7b7c7077cc76)

But when the currency is changed and change back to the original it looks,

![image](https://github.com/opencollective/opencollective/assets/12435965/0f17a169-2f4b-4b8d-9f6f-3e2421eb134d)

Then the expense will go through.

**Comment by SudharakaP** [comment]
This was reported at https://opencollective.freshdesk.com/a/tickets/310308.

**Comment by SudharakaP** [comment]
@Betree : Tagging you as you've worked on this I believe.

**Comment by Betree** [comment]
Also reported by Leo on Slack, pushing a fix in https://github.com/opencollective/opencollective-frontend/pull/9840
