### ISSUE TITLE
Added Funds Modal - Icon and Formatting Issues

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7192]
**Describe the bug**

1) It seems that there is a problem in our language translation files for Dutch. In the added fund model when funds are added we show, 

![image](https://github.com/opencollective/opencollective/assets/12435965/ce13ec0e-ac7b-45ec-8960-7c98b8870f98)

Notice that the check-mark is not appearing correctly. In fact in the language files this is what we have, 

https://github.com/opencollective/opencollective-frontend/blob/2ca840c773042c8ed45d8f8f2ba101397d7c3073/lang/nl.json#L280

which seems to be incorrect as other language files shows the check-mark correctly. 

2) In addition, the amount is not appearing in front of the label but always below the label which makes it look ugly. 

![image](https://github.com/opencollective/opencollective/assets/12435965/497199e1-212e-43a4-bdb7-8d9da847100e)

**To Reproduce**
1. Set the language to Dutch
2. Go to a collective whose host you administer
3. Add Funds some funds and got to the success page
4. See issues described above

**Comment by SudharakaP** [comment]
This is reported at, https://opencollective.freshdesk.com/a/tickets/311206

**Comment by Betree** [comment]
Fix deployed

**Comment by SudharakaP** [comment]
> Fix deployed

Thanks 👍🏽
