### ISSUE TITLE
Link to view the company's metrics and financials is not working

### ISSUE THREAD

**Issue by MayaSatishRao** [opencollective/opencollective#7194]
**Describe the bug**
The link to view the company's metrics and financials is a google drive link which cannot be accessed. 

**To Reproduce**
1. Go to Company and Exit to Community in the navbar
2. Scroll down to the section which says "We are open in every way" and then Click on Open Comapny
3. See error

**Expected behavior**
A link that is working

**Screenshots:**
![Screenshot 2024-01-06 200424](https://github.com/opencollective/opencollective/assets/67920373/7bd4fb84-db9b-4b4e-aad0-e3750a4c2e1f)
![Screenshot 2024-01-06 200445](https://github.com/opencollective/opencollective/assets/67920373/aad83703-bb65-4908-a9a5-412c9c99ff58)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by MayaSatishRao** [comment]
@Betree If the link has to be changed, please share the link. I can change it and make a PR

**Comment by Betree** [comment]
Thanks for the report. The Drive folder where this was published is indeed not maintained anymore. Our financial data is still public, we use the platform to pay our expenses. The link can therefore point to  https://opencollective.com/opencollective.

**Comment by MayaSatishRao** [comment]
@Betree ok, I will raise a PR with the updated link.

**Comment by MayaSatishRao** [comment]
@Betree I have raised the PR. Please review it.
