### ISSUE TITLE
Old Twitter logo is in OpenCollective page

### ISSUE THREAD

**Issue by MayaSatishRao** [opencollective/opencollective#7195]
**Describe the bug**
Old Twitter logo is present in https://opencollective.com/opencollective and it needs to be changed to X logo

**To Reproduce**
1. Go to https://opencollective.com/opencollective
2. See error

**Expected behavior**
New Twitter logo or X logo must be used

**Screenshots**
![Screenshot 2024-01-08 182053](https://github.com/opencollective/opencollective/assets/67920373/dde2ac87-8e6d-42dc-a7df-21df858b4b26)

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by MayaSatishRao** [comment]
@Betree I can change the logo an make a PR. Also the open collective page in OpenCollective-frontend and https://opencollective.com/opencollective are not matching.
Localhost:
![Screenshot 2024-01-08 182942](https://github.com/opencollective/opencollective/assets/67920373/d088910d-dc5a-42a6-a11b-e7f0ccef3a2c)
Actual webpage:
![Screenshot 2024-01-08 182952](https://github.com/opencollective/opencollective/assets/67920373/0b8e51dd-2f56-4336-a142-ac10f2428439)
Is there any different repo?

**Comment by Betree** [comment]
Something was started in https://github.com/opencollective/opencollective-frontend/pull/9527, and we provided some instructions on how to solve it in the PR.

> I can change the logo an make a PR. Also the open collective page in OpenCollective-frontend and https://opencollective.com/opencollective are not matching.

The default dev environment points to https://staging.opencollective.com (or your local API if configured), not https://opencollective.com.

**Comment by MayaSatishRao** [comment]
Thanks a lot, Can I make the logo change to the footer as well?

**Comment by Betree** [comment]
@MayaSatishRao Sure

**Comment by MayaSatishRao** [comment]
@Betree I have made the PR. Please review it.
