### ISSUE TITLE
Add Refund / Reject actions to contributions

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#7201]
## Overview
https://www.loom.com/share/3af63e6286fd4f53bc4c167a4cb3280b?sid=0b885774-1c4d-4482-91fd-b9b86083734e

## Solution
 - Add the Refund/Reject buttons (+ download receipt) to the contributions transaction pages.

![Detail Overview](https://github.com/opencollective/opencollective/assets/49539954/859a382e-242f-40e3-907d-677575e799c6)

 - Add the Refund/Reject buttons to the Fiscal Host

![Contribitions list](https://github.com/opencollective/opencollective/assets/49539954/2ffff85d-a349-4287-95a5-0ae2a881813e)

**Comment by SudharakaP** [comment]
Closed as per the discussion at, https://coda.io/d/Support_dEguIswyoKq/Dev-Issue-Tracker_su5Wl#Tracker_tuKQp/r5
