### ISSUE TITLE
Wording: Update "Charge" to "Virtual Card Charge"

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7203]
Surfaced in https://opencollective.slack.com/archives/C05V96RERKL/p1704478810607729

OCF Host admins did not realize that "Charge" (the expense type) was meant for virtual card charges. To provide more clarity, we've decided to rename it globally. While doing so, we should ensure that a longer string does not break the UI.

**Comment by znarf** [comment]
+1 Wanted to rename this for a long time.
