### ISSUE TITLE
Chart of accounts is expanded to allow for contribution related accounting categories

### ISSUE THREAD

**Issue by hdiniz** [opencollective/opencollective#7207]
Part of https://github.com/opencollective/opencollective/issues/7197

The chart-of-accounts MVP was created to support only expense-related accounting categories and now needs to be extended to cover contribution-related accounting-categories.

**Comment by Betree** [comment]
- [ ] Add `AccountingCategoryId` to `Orders`
- [ ] Accept `accountingCategory` on `addFunds` mutation
- [ ] Accept `accountingCategory` on `createPendingOrder` mutation
- [ ] Expose `accountingCategory` on `Order` object

**Comment by shannondwray** [comment]
I see that the 'i don't know' option is still available for the contribution category! Is this needed as it's just fiscal host admins who would be involved in contribution categories?

**Comment by Betree** [comment]
@shannondwray we don't want to force expense submitters and collective admins to pick a category. In some cases, choosing the right one is challenging and it's better to have them pick "I don't know" rather than a random category.

**Comment by shannondwray** [comment]
okay, but when I was trying to submit an expense to OCF the i don't know doesn't show up. (I am probably a fiscal host admin user) and then when I go to add funds to a collective on one of my test accounts the I don't know option shows up. Which I don't think is necessary as contribution categorization is only for fiscal host admins. Does that make sense?

**Comment by Betree** [comment]
> okay, but when I was trying to submit an expense to OCF the i don't know doesn't show up. (I am probably a fiscal host admin user) 

Yes, it's because you're a host admin and host admins are not allowed to pick the "I don't know" option. We're currently reviewing this behavior. cc @iamronen.

> and then when I go to add funds to a collective on one of my test accounts the I don't know option shows up

We're indeed lacking consistency here. I'll wait for @iamronen to pick the best approach.

**Comment by iamronen** [comment]
1. Yes, this is on my plate.
2. @shannondwray these choices came from specific needs in specific contexts and they are indeed not consistent ... and they are evolving.
3. @Betree as I was looking to recreate this I found that, for OSC (both in production and staging), the control for selecting accounting categories does not show up in the pending contributions and added funds flows? Why is that?

**Comment by Betree** [comment]
>     3. @Betree as I was looking to recreate this I found that, for OSC (both in production and staging), the control for selecting accounting categories does not show up in the pending contributions and added funds flows? Why is that?

@iamronen That must have been a feature flag or release issue, the category select does seem to appear:

![image](https://github.com/opencollective/opencollective/assets/1556356/0d7d93e2-99cd-4426-9344-224b0915e09a)
