### ISSUE TITLE
Host-only accounting categories

### ISSUE THREAD

**Issue by hdiniz** [opencollective/opencollective#7209]
Part of https://github.com/opencollective/opencollective/issues/7197

1. The fiscal host chart of accounts lists expense related accounting categories. 
2. When a fiscal host enables participation of expense submitters and/or collective admins in the expense categorization process, they see the list of accounting-categories created by the fiscal host.
3. However, there are some expense related accounting categories which are specialized for accounting purposes and should not be shown to expense submitters and/or collective admins.

Therefore we need to add an indicator for expense-related accounting categories that indicates if it is to be made available to expense-submitters and/or collective admins. 

A clear implementation of this would be to add something like a checkbox “For fiscal host use only.”

**Comment by Betree** [comment]
Waiting for host feedback to update the specs

**Comment by Betree** [comment]
As per @iamronen in https://github.com/opencollective/opencollective/issues/7197#issuecomment-1898116933:

> 
> I have confirmation from OCF that the "Fiscal Host Only" option is something that they still need which means:
> 1. Adding it with default values of false (unselected).
> 2. This may create a ripple with notifications - because if a fiscal host can choose an expense category that is not visible to expense submitters or collective admins then (I think) no notification should be sent.
