### ISSUE TITLE
CSV export: Implement new strategy for transaction effective date

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#7210]
From "Make Open Collective"

> In the past [fiscal hosts presented a request](https://github.com/opencollective/opencollective/issues/5693) around added funds. Added funds are usually entered some time (at least a few days) after the money shows up in the host accounts. Therefore, when added funds are entered into the platform hosts need a way to indicate the date the funds showed up in the bank account so that they can be reconciled in accounting (date matching is one of the basic parameters to matching transactions). 

> In response to this request we added a date in the added funds entry form and fiscal hosts have been using this as they intended to: to indicate the real date the funds showed up in the bank account. 

> However, this has been incorrectly interpreted and implemented as a way to manually set a “date that the contribution was processed.” This is [surfaced in the export interface](https://github.com/opencollective/opencollective/issues/6546):

> This is an incorrect and useless implementation. There is no meaning to “Contribution processed date” - the date the contribution was entered is the date it was processed. Hosts are entering a different date to indicate, as requested and intended, the real date the funds showed up in the bank account, with the intention of being able to reconcile transactions in accounting. 

> This  incorrect implementation is likely related to a tension between:
> 1. The fiscal host request, which from a ledger perspective could mean “back-dating a transaction.”
> 2. The ledger architecture which does not allow for back-dating. 

> The resulting situation is:
> 1. Fiscal hosts ARE entering the real dates that funds showed up in their bank accounts.
> 2. This information is stored but not exported correctly to the fiscal hosts.
> 3. Fiscal hosts are encountering many transactions (potentially ALL added funds) which do not reconcile well in accounting because of the mismatching dates. 

https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Projects_sud_a#Projects_tusx8/r144&view=modal

**Comment by kewitz** [comment]
Specs:
- [ ] Add `receivedAt` column to Transactions.
  - [ ] When creating double transactions, make sure the whole group copies `receivedAt` from the original transaction.
- [ ] Update existing flows to use the new date field:
  - [ ] Stripe contributions.
  - [ ] Stripe issuing (virtual cards).
  - [ ] Wise expenses.
  - [ ] PayPal contributions.
  - [ ] PayPal Payouts and Adaptive expenses.
- [ ] UI/UX:
  - [ ] Update _Add Funds_ modal and make the Date label more explicit about what it represents.
    - [ ] Added funds mutation should set the `transaction.receivedAt` field of the whole group to the informed date.
  - [ ] Update _Contribution Confirmation_ modal and make the Date label more explicit about what it represents.
    - [ ] Manual contributions mutation should set the `transaction.receivedAt` field of the whole group to the informed date.
  - [ ] Update _PayExpenseModal_ to include the transaction date field.
    - [ ] Update mutation to set `transaction.receivedAt`.
