### ISSUE TITLE
CSV Export: implement Payment Method in addition to Payout Method for expenses

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#7212]
There is some confusion for Accountants about the purpose and content of "Payout Methods".

The simple fix is to state that "Payout Method" is information about how the payee wish to receive money, not how the expense was paid.

We can then add a "Payment Method" to expenses in addition to "Payout Method" that will convey information on how the Expense was paid (likely PayPal, Wise or other).

Payment Methods will look similar to what we're using for Contributions.

https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Currently_suFhs#CurrentProjects_tu75U/r143&view=modal

**Comment by kewitz** [comment]
We need to make sure we also ask for the Payment Method used by the user in case they manually settled outside. It would also be nice to ask for a reference like (transaction ID).

**Comment by znarf** [comment]
> We need to make sure we also ask for the Payment Method used by the user in case they manually settled outside. 

On other words, if a user submit an Expense with their bank account details and it's manually marked as paid, we can't assume it will have been paid with Wise, still it may have been.

As we understand, the accountant want to know and this is why we have to ask the fiscal host admin when they "mark as paid".

**Comment by znarf** [comment]
| service | type |
| ------- | -----------  |
| WISE     | TRANSFER |
| WISE     | MANUAL |
| PAYPAL | ADAPTIVE |
| PAYPAL | PAYOUT |
| PAYPAL | MANUAL |
