### ISSUE TITLE
GST Rate Percentage is Disabled for Expense Invites

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7222]
**Describe the bug**

It seems that for a collective that uses GST, when inviting an expense, if the GST Rate is not selected, then the invitee will have no way of specifying the GST rate. The GST percentage input is not editable the user is stuck trying to submit the expense. 

**To Reproduce**
1. Go to a collective that uses GST
2. Create an expense (invoice) invitation and do not tick the "Apply Goods and services tax (GST)" checkbox
3. Login as the invitee and go to the invited expense
4. Edit the invited expense and try to add the GST Rate

**Expected behavior**

Even if when creating the expense invite the GST rate is not specified, the invitee should not get a non editable empty GST rate input box. 

**Screenshots**

Following the steps above to reproduce, we will see the following from the invitee side; 

![image](https://github.com/opencollective/opencollective/assets/12435965/d4495387-3a16-4daf-84de-d2d83397aa32)

**Comment by SudharakaP** [comment]
This was initially reported at, https://opencollective.freshdesk.com/a/tickets/313434

**Comment by Betree** [comment]
I'll look at it

**Comment by SudharakaP** [comment]
> I'll look at it

Thanks a lot for fixing it so quickly 💯
