### ISSUE TITLE
Expense Receipt Recognition Don't Work Correctly With Virtual Cards

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7228]
**Describe the bug**

It seems that if the virtual card is in one currency (say USD) and was used to pay a service in a different currency (EUR) and then when the expense is created there are issues with uploading the receipt (which is in EUR). In fact when the receipt is uploaded the user gets into a stuck state whereby the application thinks there's some currency mismatch. 

**To Reproduce**
1. Create a virtual card charge with a different currency than the virtual card
2. Try to upload the receipt
3. See error

**Expected behavior**

The OCR should recognize and account for this multi currency scenario. 

**Screenshots**

A demonstration of this issue is reported at, https://opencollective.freshdesk.com/a/tickets/314119 along with screenshots.

**Comment by SudharakaP** [comment]
Ping @Betree as you've worked on this recently

**Comment by Betree** [comment]
This is definitely a bug; we don't allow touching the currency for a virtual card charge so the UI shouldn't act like that.
