### ISSUE TITLE
Improve the "Collective picker" component usability

### ISSUE THREAD

**Issue by Memo-Es** [opencollective/opencollective#7246]
## Overview
The "Collective picker" component is a dropdown to select profiles inside Open Collective. We use it in a lot of instances and recent feedback suggests that there is a consolidation opportunity for this component to have better usability and accessibility across different features.

I'm starting to register these opportunities here:

 - Create pending contribution:

> Also, I think this may be a systemic problem with an unexamined UX pattern on the platform.
> I've recently discussed a similar friction in the creating pending contributions flow, when, for selecting who the contributor is, users are shown a list of collectives they administer (which are relatively very few) but they CAN search for all platform accounts ... but they have to know or guess you can search ... there is no visual cue that indicates you can do this ... the initial result set feels finite and confining and insinuates "this is all there is".
By @iamronen

**Comment by Betree** [comment]
Consolidating that into a project: https://github.com/opencollective/opencollective/issues/7629
