### ISSUE TITLE
Welcome page responsiveness issues

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#7250]
On tablet, the column disposition clips part of the welcome message and margins are inconsistent.
![localhost_3000_welcome(iPad Mini)](https://github.com/opencollective/opencollective/assets/2119706/a53c60e9-4a04-40a9-9190-88bd6de6e094)

On mobile, the margins are inconsistent.
![localhost_3000_welcome](https://github.com/opencollective/opencollective/assets/2119706/83f44252-0508-4228-bdd3-7cce2da0402b)

**Comment by samkevin1** [comment]
Hey! Can I work on this one?

**Comment by Betree** [comment]
@samkevin1 It's yours!
