### ISSUE TITLE
CSV export: split accounting category in multiple fields

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7253]
The accounting category should be split into two fields:
1. Accounting Category Name
2. Accounting Category Code

(confirmed also by feedback from OCF)

_Originally posted by @iamronen in https://github.com/opencollective/opencollective/issues/7197#issuecomment-1909482695_

**Comment by Betree** [comment]
We'll take the opportunity to have a dedicated "Accounting" section in the export CSV modal

**Comment by iamronen** [comment]
I had a call today with @znarf and @kewitz about changes to the export CSV modal.
I suggest for now just adding the fields and holding off on adding sections until we engage with the fuller redesign (hopefully next cycle).

**Comment by Betree** [comment]
@iamronen It's already implemented as a new section. We needed to do it that way in all cases because we're going to roll out accounting categories for contributions, and the previous one was under the "Expenses" category.

![image](https://github.com/opencollective/opencollective/assets/1556356/ff84e310-849d-4fbd-9821-cd371060e2dc)
