### ISSUE TITLE
Fix depcheck in CI

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7254]
Fix depcheck

We're disabling depcheck in https://github.com/opencollective/opencollective-frontend/pull/9975 as it gives a seemingly unrelated error:

> > opencollective-frontend@2.2.0 depcheck
> > npx depcheck
> 
> Next.js webpack configuration detection failed with the following error TypeError: Cannot read properties of undefined (reading 'distDir')
>     at getWebpackPluginOptions (/home/runner/work/opencollective-frontend/opencollective-frontend/node_modules/@sentry/nextjs/cjs/config/webpack.js:692:66)
>     at Object.newWebpackFunction [as webpack] (/home/runner/work/opencollective-frontend/opencollective-frontend/node_modules/@sentry/nextjs/cjs/config/webpack.js:381:15)
>     at loadNextWebpackConfig (/home/runner/.npm/_npx/d2bd3cb5801d0b99/node_modules/depcheck/dist/special/webpack.js:129:25)
>     at async parseWebpack (/home/runner/.npm/_npx/d2bd3cb5801d0b99/node_modules/depcheck/dist/special/webpack.js:152:27)
>     at async getDependencies (/home/runner/.npm/_npx/d2bd3cb5801d0b99/node_modules/depcheck/dist/check.js:119:18) Support for this feature is new and experimental, please report issues at https://github.com/depcheck/depcheck/issues
> Unused devDependencies
> * file-loader
> * html-loader
> * markdown-loader
> * raw-loader
> * url-loader

**Comment by znarf** [comment]
https://github.com/depcheck/depcheck/pull/879

**Comment by znarf** [comment]
Fixed with a fork of depcheck in https://github.com/opencollective/opencollective-frontend/pull/10068
