### ISSUE TITLE
Request for Pre-Compiled Windows S3 Plugin for Orthanc Integration

### ISSUE THREAD

**Issue by abhayanand-memorres** [opencollective/opencollective#7260]
I'm interested in integrating AWS S3 bucket storage into our system. Currently, we store data on our Windows server. I've been following the approach of creating the S3 plugin build for Windows (libOrthancS3Build.dll), but I'm encountering difficulties in the process. Despite cloning the repository and following the documentation, I'm only able to generate a libOrthancS3Build.so file, which is not compatible with Windows. Is there a pre-compiled binary available or any other helpful resources that could assist me in completing this integration?

**Comment by abhayanand-memorres** [comment]
I'm interested in integrating AWS S3 bucket storage into our system. Currently, we store data on our Windows server. I've been following the approach of creating the S3 plugin build for Windows (libOrthancS3Build.dll), but I'm encountering difficulties in the process. Despite cloning the repository and following the documentation, I'm only able to generate a libOrthancS3Build.so file, which is not compatible with Windows. Is there a pre-compiled binary available or any other helpful resources that could assist me in completing this integration?

**Comment by Betree** [comment]
Wrong repo.
