### ISSUE TITLE
Confusion in Enabling and Disabling Notifications for Collectives

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7263]
**Describe the bug**

When trying to toggle notifications for a collective the radio buttons are not reflected properly when toggling all the notifications on/off using the "Main collective activity" radio toggle. It does under the hood and a page refresh reflects that, but the user is a bit confused here as we don't show that in real time. The screen-share below explains this in more detail. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to your profile settings
2. Go to Notification Settings
3. Enable and disable "Main collective activity" toggle for a collective that you have subscribed to

**Expected behavior**

When toggling the "Main collective activity" toggle of a collective all the other radio buttons should enable/disable automatically. While it does in the background (hence a page refresh reflects the correct state) it should be reflected in the front-end without a refresh as otherwise the user is confused on what is being enabled/disabled. 

**Screenshots**

[radio-toggle.webm](https://github.com/opencollective/opencollective/assets/12435965/c08d850f-199e-4298-a80b-f6fe154e2ea5)

**Comment by SudharakaP** [comment]
@samkevin1 : Yes that might very well be possible but I will leave that to the engineering team to decide. 

ping @Betree

**Comment by Betree** [comment]
I'll let @kewitz review the specs and https://github.com/opencollective/opencollective-frontend/pull/10027.

Related: https://github.com/opencollective/opencollective/issues/5852
