### ISSUE TITLE
Searching on the help and support page redirects to the global search

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7267]
https://github.com/opencollective/opencollective/assets/1556356/2ab592ab-c113-41d3-a590-d9ef0b1c1ee0

**To Reproduce**
1. Go to https://staging.opencollective.com/help
2. Type something
3. Press enter
4. You're redirected to the search page

**Expected behavior**
If we don't have another way to display the results, pressing Enter should do nothing.

**Comment by samkevin1** [comment]
@Betree Hey! I'll take a look at this one
