### ISSUE TITLE
Help and support page: responsiveness issue

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7268]
See https://staging.opencollective.com/help

Try opening the page on a 800px screen width device.

![image](https://github.com/opencollective/opencollective/assets/1556356/4054d8bf-dcb9-4c26-a3ac-507c3c2167aa)

**Comment by Jibby2k1** [comment]
Hi Betree, I'd like to try and help, let me know if I could contribute!

**Comment by Betree** [comment]
@Jibby2k1 It's open for contributions, feel free to open a PR and comment with the link here :slightly_smiling_face:

**Comment by MarwanBz** [comment]
Hey @Betree,

I saw the open issue about the support page responsivness  and I'd be interested in working on it.  

Please let me know if you'd be willing to assign this issue to me.

Thanks,
@marwanbz

**Comment by Betree** [comment]
@MarwanBz it's yours

**Comment by MarwanBz** [comment]
hey @Betree  I oppend a PR ,so could please check it out 
[https://github.com/opencollective/opencollective-frontend/pull/10266]

**Comment by stilln0thing** [comment]
Hey @Betree,

I saw the open issue and I am interested in working on it.
Let me know if you are still looking

Thanks

**Comment by Betree** [comment]
@stilln0thing sorry, someone already proposed a fix in https://github.com/opencollective/opencollective-frontend/pull/10614
