### ISSUE TITLE
The expense approved and paid is not shown as paid.

### ISSUE THREAD

**Issue by JeanPaulGrange** [opencollective/opencollective#727]
Hello,
On REconomycop collective, I have modified an expense Payout method to Other and validated it (#687).
I see it in Expense All on the left but I don't see it in "Payed" and I don't see it in the right "Latest transactions" as you can see on the screenshot below : 
![2017-12-05 21_26_14-reconomy practitioners - open collective](https://user-images.githubusercontent.com/33667947/33629042-fd0c7754-da02-11e7-83b7-284ce8845c6c.png)
Regards,

**Comment by piamancini** [comment]
hi @JeanPaulGrange try hitting on Fermer les détails

**Comment by JeanPaulGrange** [comment]
hi Pia, I get the same 
![2017-12-06 08_56_08-reconomy practitioners - open collective](https://user-images.githubusercontent.com/33667947/33650716-6dbc4dac-da63-11e7-986c-9ad2f9747bde.png)

**Comment by JeanPaulGrange** [comment]
Hello Pia,

It is not solving the problem. I still don't see the spending.



Amitiés,
Jean-Paul Grange
 www.set94.org - www.val-de-marne-en-transition.org -
www.transitionparisidf.org -  www.transitionfrance.fr


2017-12-05 21:42 GMT+01:00 Pia Mancini <notifications@github.com>:

**Comment by piamancini** [comment]
There's definitely a bug here. @xdamman try clicking on this link https://opencollective.com/reconomycop#budget. If you click on Paid the expense shows up as paid, but if you click again in 'all' and back to 'paid' it disappears from the paid expenses list.

**Comment by xdamman** [comment]
Did you click on "RECORD AS PAID"?
(Only one of the admins of the host can do it)

Btw, it's better to go on the dedicated page to manage expenses https://opencollective.com/reconomycop/expenses

I tried locally and it worked fine: https://d.pr/v/2Mo4ZB

**Comment by JeanPaulGrange** [comment]
Hello

Thanks, it is working now.

Amitiés,
Jean-Paul Grange
 www.set94.org - www.val-de-marne-en-transition.org -
www.transitionparisidf.org -  www.transitionfrance.fr


2018-01-09 16:58 GMT+01:00 Xavier Damman <notifications@github.com>:
