### ISSUE TITLE
comment option when donating or transferring money to/between collectives/projects

### ISSUE THREAD

**Issue by fh948h9** [opencollective/opencollective#7273]
forgive me if this issue has already been created. i'm not saavy at github.

it would be great if there could be an option to comment when donating or transferring money to/between collectives/projects. eg, if there isn't a better structure in place it can allow donors to specify how they'd want the donation to be used--something a collective i'm in really grapples with since we're wanting to lean into developing more consensus with donors as to how the money they donate is SPECIFICALLY used.[*]

it can also help the collective for internal purposes. eg, in one collective we have a project called EARMARKED FUNDS in which we put money in that we do not want to accidentally spend or figure into our available funds bc it's definitely destined for something else already. it would help us if we could quickly identify why that money was put there than to dig through notes of meetings bc unfortunately sometimes we forget! :) and simply being able to attach a comment to the internal fund transfer could really help with that.

so if you were to pursue the feature maybe two comment options--one for public and one for non-public/internal.

thanks!

[*] And in re to this maybe there could be another way to notify them of choices. eg, HEY DID U KNOW WE HAVE DIFFERENT PROJECTS/FUNDS YOU CAN DONATE TO?

**Comment by Betree** [comment]
Adding public comments is already supported from the success page, though this is not yet supported for guest contributions (see https://github.com/opencollective/opencollective/issues/3834):

![image](https://github.com/opencollective/opencollective/assets/1556356/abb19ed8-24ec-47a1-a02c-0c519185889f)

Adding private comments is something that has been requested in https://github.com/opencollective/opencollective/issues/3266; I've added your comment there. Thanks for the feedback!
