### ISSUE TITLE
(nick)names for payout methods

### ISSUE THREAD

**Issue by fh948h9** [opencollective/opencollective#7282]
is there a way to have nicknames for payout methods instead of just account numbers? it's almost a unanimous feature in my life with merchants and utilities websites to have names for payout methods. i find myself double checking every time i do an expense, and i can only have so many stickies... ty.

**Comment by Betree** [comment]
Duplicate with https://github.com/opencollective/opencollective/issues/5323. I would love to see this as well, all we need to implement this is an interface to edit the name.
