### ISSUE TITLE
PayPal Transaction Failure: `Cannot read properties of null (reading 'getFullYear')`

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7296]
**Describe the bug**

Related to the fresh-desk ticket; https://opencollective.freshdesk.com/a/tickets/325901. 

The PayPal transaction for the order,  https://opencollective.com/antennapod/orders/739042 failed with `Cannot read properties of null (reading 'getFullYear')`. Looking at the logs it seems that this is a recurring error while I am not certain of a way to re-create this.

**Comment by Betree** [comment]
Looks like it started ~2 days ago (Feb 21, 16:57). Relevant Sentry issues:
- https://open-collective.sentry.io/issues/5001954776
- https://open-collective.sentry.io/issues/4999655704
- https://open-collective.sentry.io/issues/5001908601

Investigating.

**Comment by Betree** [comment]
Fixing the root cause in https://github.com/opencollective/opencollective-api/pull/9862, but we'll need to see how we're going to synchronize these transactions; I'm not sure if the `cron/daily/51-synchronize-paypal-ledger.ts` will catch them all.

**Comment by Betree** [comment]
Manual bank transfers with tips may have been impacted too

**Comment by Betree** [comment]
Extending the reconciliation job in https://github.com/opencollective/opencollective-api/pull/9869 to include checkout order transactions (previously only subscriptions were synchronized this way).

**Comment by Betree** [comment]
The issue should be fully resolved now.
