### ISSUE TITLE
Improved sign up experience for events

### ISSUE THREAD

**Issue by kadallah** [opencollective/opencollective#7301]
## Who is your user?
Collectives that host events and do ticketing through Open Collective. (Posting this on behalf of a user that sent an email to support)

## What are they trying to achieve?

> We have been using the events feature on the Open Collective platform as a means to check in people to our in-person events as a way to keep track of attendance in the same place where people and organizations can donate to us."
> 
> A frequent complaint that we have is that the Captcha feature is annoying and too complicated. For instance, in the last event, someone failed the Captcha 3 times and ended up not checking in. I understand that this is for security reasons, but would there be a way to make the experience simpler and smoother?
> 
> An idea would be to add types of events when an admin is creating a new event. In our case, we make use of events for attendance purposes only, so it would make sense to allow only attendees to get tickets during the duration of the event. This could potentially eliminate the need for a Captcha. On a related note, we did a test and we were able to get a ticket to a past event.
> 
> Another suggestion to work around this issue would be to allow the possibility to confirm check-in by email, where the person would enter their email and then confirm attendance by clicking on the link sent to their email.
> 
> Lastly, I have noticed that if someone is not logged in to the Open Collective platform, they are not able to see how many people attended each event. This is not ideal for us, because we are trying to collect data in this platform so that potential financial sponsors can see the work we have been doing and the dimension of our community when they come to this page. Would it be possible to have the total number of attendees as part of the event summary? Currently, it says "Attended by" followed by the initials of the first 4 people who signed up. Then, even if you are signed up, you need to click the event to see the count of people who attended. An more helpful alternative would be to show "Attended by" followed by "{initials of the first person who checked in} and {number of remaining check-ins}".

## How are they currently doing this?
 
They are using the events feature normally, but are suggesting some updates that would work better for their use case.

## How well understood is this problem?

 - [x] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment]
Trying to summarize this feedback:
1. Simplify Captcha for Event Check-In (https://github.com/opencollective/opencollective/issues/7302 could help with that)
2. The "Sponsors and Participants" section is only displayed for logged-in users. I'm not sure about the rationale for this, but I tend to agree with this person that we should show it.

> we did a test and we were able to get a ticket to a past event.

This is either because:
- They're admins (admins can contribute to an event even after it's over)
- Or the event ended less than 24hours ago (there's a grace period)

**Comment by Betree** [comment]
Moved to https://github.com/opencollective/opencollective/issues/5355
