### ISSUE TITLE
Error Message When Trying to Submit Expense for Newly Created Collective

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7313]
**Describe the bug**

When we create a new collective and do not assign it to any fiscal host or make it an independent collective, trying to submit a expense will result in an error. While a fiscal host is needed to transfer funds, it would be nice to show a more user friendly error in this case. 

**To Reproduce**
1. Create a new collective
2. Go to the collective page
3. Click on the submit expense link and try to submit an expense

**Expected behavior**

A clear indication of what is wrong and why the expense flow isn't working should be shown to the user. Alternatively we can hide the "Submit Expense" button for a collective who has no fiscal host. 

**Screenshots**

[submit-expense.webm](https://github.com/opencollective/opencollective/assets/12435965/8a6c5513-465c-4a11-b08d-3e09a4665558)

**Comment by SudharakaP** [comment]
This is also reported in https://opencollective.freshdesk.com/a/tickets/331486

**Comment by Betree** [comment]
Another instance https://opencollective.freshdesk.com/a/tickets/334849
