### ISSUE TITLE
New Budget Visualization Not working 

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#7320]
## Who is your user?
All users

## What are they trying to achieve?
New Budget Visualization not working

_When viewing the new budget visualization, I want to see the graphs etc, so I can better understand the budgets of projects on Open Collective_

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment]
Can confirm all profiles are affected; this seems to come from a regression in the API:
> [GraphQL error]: Message: Invalid value Moment<2017-04-01T14:02:10+00:00>, Location: [object Object], Path: account,stats,expensesTagsTimeSeries
