### ISSUE TITLE
Card with invalid CVC code still added to the account

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7333]
On https://staging.opencollective.com/dashboard/betree/payment-methods, entering a card with an invalid CVC code shows an error but still adds it to the account.

**To Reproduce**
1. Go to https://staging.opencollective.com/dashboard/betree/payment-methods
2. Click on "Add payment method"
3. Use Stripe's special code for invalid CVC's: `4000000000000101`
4. See the error saying "Invalid code"
5. Reload the page
6. The card is there

**Expected behavior**
Do not add the card to the account if there was a Stripe error while retrieving its info

**Comment by znarf** [comment]
That "Add payment method" thing should be gone for a long time now.

**Comment by Betree** [comment]
@znarf Do we have a workaround for adding a credit card to be used as a source for gift cards if there's none already?
