### ISSUE TITLE
Mention the collective's twitter account in default twitter message

### ISSUE THREAD

**Issue by Elchi3** [opencollective/opencollective#7337]
## Who is your user?

As an open collective admin, I want to be @-mentioned in case a new sponsor posted a tweet so I can retweet and engage with them on social media.

## How are they currently doing this?

Although I provided my twitter handle on https://opencollective.com/open-web-docs it's not put in the default message, I guess?

https://twitter.com/ken7253_/status/1775865214145368204

"I've just contributed to {collective}. Consider supporting them too — every little helps!" [(code)](https://github.com/opencollective/opencollective-frontend/blob/d8d28d7cec31d843f11738bb50d9e36ad691f9f3/components/contribution-flow/ContributionFlowSuccess.js#L100)

## How well understood is this problem?

There is a paper that researched the impact of social media on obtaining funding to sustain open-source software. https://arxiv.org/pdf/2401.02755v1.pdf

"tweets have the impact of increasing the number of sponsors acquired"

Currently, it seems to be tagging `@opencollect` but you are probably not engaging with the tweets on behalf of the collectives. So @-mention the collectives if you have the handle and let them engage instead.

Aside: Do you have any Mastodon plans? :)

**Comment by Betree** [comment]
Hi @Elchi3,

This will be resolved by https://github.com/opencollective/opencollective-frontend/pull/10309.

> Aside: Do you have any Mastodon plans? :)

See https://github.com/opencollective/opencollective/issues/7138
