### ISSUE TITLE
[Project] Review payout method permissions

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#7347]
Our working assumption is that only fiscal hosts need and should have access to payout method information.

[Coda Entry](https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/All-Projects_sud_a#Projects_tusx8/r205&view=modal) (private link)

**Comment by znarf** [comment]
Waiting on feedback from impacted Fiscal Hosts.

**Comment by iamronen** [comment]
I've gotten no response from the two fiscal hosts who were somehow related to this. My working assumption is therefore that this was related to collective admin being able to edit an expense (which they should still have) and that payment method got bundled into that.

Feedback from OSC is positive on this.

I propose moving forward and if we get relevant feedback we **consider** a implementing fiscal host configuration to override this platform choice.

**Comment by znarf** [comment]
PR: https://github.com/opencollective/opencollective-api/pull/10086
