### ISSUE TITLE
[Project] Integrate Updates into dashboard

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#7348]
### Purpose

Enable the creation and publication of updates from the Collective dashboard

### Friction

As we move forward with developing the different sets of platform features from the dashboard as a launchpad, we are also migrating admin actions originally inside the public profile pages (With admin-only visibility).

For Collectives, our main public profile page, we are undertaking a parallel effort to move the project and event creation and preview to the dashboard, and the effort described here is to have the ability to publish updates from the Collective dashboard.

Doing this will enable the Collective public page simplification, helping us differentiate all the actions and offerings for communities (Contributors, sponsors) from all the admin actions necessary to manage those communities.

### Desired outcomes

- Being able to publish a new update from the Collective dashboard
- Being able to save new updates entries as drafts
- Being able to see previously published updates

### Ownership

**Product:** @iamronen 
**Engineering:** @kewitz @hdiniz  

[Coda Entry ](https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Currently_suFhs#CurrentProjects_tu75U/r151&view=modal) (private link)

**Comment by znarf** [comment]
### Kick Off

Compared to the proposed design, we would like to move forward with a simpler UX without modal, with different **pages**:
- List
- New update
- Editing an update
- Viewing an update (optional)

#### Actions

- @kewitz will start on the skeleton of the project
- @aminakazi will explore an iteration of the design based on the new direction

**Comment by kewitz** [comment]
Same as https://github.com/opencollective/opencollective/issues/7179.

**Comment by kewitz** [comment]
New design here: https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/%5BOC-Design%5D-Lab-%F0%9F%A7%AA?type=design&node-id=26441-3736&mode=design&t=OV6PxBJDTdmAlOlT-0

**Comment by kewitz** [comment]
### This week
- [x] Submit for review.
- [ ] Record and share demo.
- [ ] Merge and deploy.

**Comment by kewitz** [comment]
**Demo:**

https://github.com/opencollective/opencollective/assets/2119706/e3771b83-f8bd-4af3-b8af-c306d9f1e812
