### ISSUE TITLE
Budget Section: Expenses Link Goes to Transactions Page

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7366]
**Describe the bug**

It seems that there's a link in the budget section which says, "View all expenses" but when clicked on it goes to the transactions page instead. 

![image](https://github.com/opencollective/opencollective/assets/12435965/6a1a8148-a867-4a13-9585-14f81a10fec3)

Related discussion: https://opencollective.slack.com/archives/C6JTTA4SK/p1712159496076679

**Comment by Betree** [comment]
It's not a bug; the transaction link you end up at is pre-filtered on expenses (e.g., https://opencollective.com/babel/transactions?kind=EXPENSE). The rationale here was probably that you're looking at the budget section, and only paid expenses play a role in your budget.

It can definitely mislead users, so I would propose renaming the link to "View all paid expenses" to clear out the confusion.
