### ISSUE TITLE
Rounding Errors in Platform Tips

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7386]
**Describe the bug**

It seems that certain contribution flows can introduce rounding errors. Here's an example. 

**To Reproduce**
1. Go to https://staging.opencollective.com/backyourstack
2. Click on the default donation tier; https://staging.opencollective.com/backyourstack/donate
3. Select interval one time, donation amount to be 20.84
4. Click on edit link to edit the platform tip and select 10% and then back to 15%
5. Click next and try to complete the flow

**Expected behavior**
There should not be any rounding errros.

**Screenshots**

[platform-tip-bug.webm](https://github.com/opencollective/opencollective/assets/12435965/ae6d24bd-09cb-401a-a359-6535d7e2ded5)

**Comment by SudharakaP** [comment]
Related fresh-desk thread; https://opencollective.freshdesk.com/a/tickets/343620

**Comment by Betree** [comment]
Thanks for the detailed issue Suds
