### ISSUE TITLE
Add Swish Payment method via Strip, for Sweden

### ISSUE THREAD

**Issue by Kasimirsuterwinter** [opencollective/opencollective#7387]
I represent a new Swedish fiscal host on OC called Massvis. We are hosting a number of collectives, however we have identified a big pain point for contributors to collectives in Sweden. We would like to ask for the Swish payment option to be added. Stripe has recently added Swish as a payment option so it should not be hard to enable it on OC as well. 

## Who is your user?

Contributors in Sweden

## What are they trying to achieve?

_When <situation>, I want to <motivation>, so I can <outcome>_

When making a contribution on Open Collective, I want to be able to pay with Swish, so that it is easier. 

## How are they currently doing this?
 

Massvis (a New Swedish fiscal host) provides a swish number for individual collectives it hosts and one for the whole fiscal host. And then contributions are manually added to collectives which is time consuming and does not sign up new members nor provide platform tips since the payments are made off of OC. 

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [x] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by SudharakaP** [comment]
@hdiniz : Maybe this is done at, https://github.com/opencollective/opencollective-frontend/pull/10459 ?

**Comment by shannondwray** [comment]
Kasmimir did send through a message today on Discord asking how to activate this? - https://discord.com/channels/1241017531318276158/1241700236313890866/1265620352227082351

**Comment by SudharakaP** [comment]
This is answered in discord and has nothing to do with this but rather Stripe disabling Swish.  😉
