### ISSUE TITLE
force height in sponsors logo space 

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#74]
see image, the line that divides logo from text is relative to logo size, should be relative to box. 
<img width="1057" alt="screen shot 2016-05-09 at 1 57 28 pm" src="https://cloud.githubusercontent.com/assets/3671070/15122685/32fbab4e-15ee-11e6-8b17-1c30da5696fb.png">

**Comment by carlosascari** [comment]
PR Sent https://github.com/OpenCollective/website/pull/217
I also removed the gray rectangle in the background, it shouldn't be visible.

**Comment by xdamman** [comment]
Thanks @carlosascari. It's merged, will be soon on production.
