### ISSUE TITLE
Show the host more prominently

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#740]
We need to show who the host is more prominently.
Especially when the host is a 501c3 (like Women Who Code, Operation Code, etc.) because the donor can have a tax deduction.

Can you come up with something quick for that?

I could see 2 states:
- Tax deductible status y/n
- Accepting new collectives y/n

E.g.

This collective is hosted by Women Who Code 501c3
Your donation to this collective is (is not) tax deductible

Apply to create another collective hosted by Women Who Code

(note: not all hosts accept applications)

**Comment by cuiki** [comment]
Hey, quick question: http://tafka.d.pr/6fZUxs

If not, would this work: http://tafka.d.pr/01Vcnr, or are you looking for something more prominent?

**Comment by xdamman** [comment]
That works, thanks that was quick! 👍 
Can you just update the sketch file on dropbox and/or zeplin?

**Comment by cuiki** [comment]
Updated. :)

**Comment by cuiki** [comment]
Should I close this issue, @xdamman?

**Comment by xdamman** [comment]
Closing. Thanks.
