### ISSUE TITLE
Image in Reset Password Screen is Misaligned

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7400]
**Describe the bug**

The image in the password reset screen is misaligned as shown on the screenshot. 

![image](https://github.com/opencollective/opencollective/assets/12435965/18194c95-6ef6-4ae3-a993-7a7be46119f0)

**Comment by SudharakaP** [comment]
Same is true for password update confirmation screen.

![image](https://github.com/opencollective/opencollective/assets/12435965/17370e79-6aa4-4214-b97d-3a762c984118)

**Comment by Pennuaju** [comment]
[](url)

**Comment by SudharakaP** [comment]
Fixed in https://github.com/opencollective/opencollective-frontend/pull/10399

**Comment by SudharakaP** [comment]
Slack thread: https://opencollective.slack.com/archives/C06K5J91675/p1715854302057939
