### ISSUE TITLE
Website join Slack link not working

### ISSUE THREAD

**Issue by kartiks26** [opencollective/opencollective#7402]
**Website Slack Join link not working**
On the website in the help section at [/help](https://opencollective.com/help) 
Not working.

**To Reproduce**
1. Go to [/help](https://opencollective.com/help) 
2. scroll to bottom of page.
3. Click on the slack link

**Screenshots**
![image](https://github.com/opencollective/opencollective/assets/84696578/9ff9fa27-cac8-4160-980c-c05b5951e04a)
![image](https://github.com/opencollective/opencollective/assets/84696578/afc74a44-1243-46f8-9ab1-e3e57064180f)

**Comment by znarf** [comment]
https://github.com/opencollective/opencollective/issues/7023

**Comment by znarf** [comment]
Updated the link, thank you for the feedback.
