### ISSUE TITLE
Embedded Widgets for Different Payment Tiers in external website?

### ISSUE THREAD

**Issue by GeorgeFejer91** [opencollective/opencollective#7410]
Dear community,
I am wondering if there is a feature, or if it would be possible to add a feature, that allows us to generate embed codes for individual payment tiers, similar to what platforms like Ko-fi and Patreon offer. This would let us display specific tiers directly on my website, making it easier for our supporters to choose and contribute without having to leave our site. 
Ideally, I would like to direct all traffic through my association's website, since that is where we create content, thus I think it would be very practical to have the ability to process payments there as well.
Cheers!

**Comment by Betree** [comment]
Hi @GeorgeFejer91, there's limited support for this: https://docs.opencollective.com/help/collectives/contribution-flow#embed-a-specific-tier.
