### ISSUE TITLE
[Project] Batch create transactions

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#7416]
### Friction

You are a host admin. A big part of your job is handling transactions that don’t happen on the platform but that need to be registered on the ledger. Every week you go through your bank transactions to register payments, added funds and pending contributions.

You add transactions one by one in three different interfaces. Would it not be easier if you could register transactions that happened outside the platform all at once?

### Desired outcomes

- Improved accuracy of funds represented on the platform
- Reduce later time and cost reconciling accounts 
- Reduce the time spent by admins representing off platform activity on the platform
- Add funds to collectives in batch
- Match pending contribution to incoming funds in batch
- Review transactions before created
- Save ongoing batch in dashboard 
- Import transactions from CSV to pre-populate batch

### Ownership

Product: @aerugo 
Engineering: @znarf @Betree 

[Coda Entry](https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Currently_suFhs#CurrentProjects_tu75U/r197&view=modal) (private link)

## Project

![image](https://github.com/opencollective/opencollective/assets/1556356/8f0c830a-ec0a-4c41-ad9e-43acfed2d652)

![image](https://github.com/opencollective/opencollective/assets/1556356/5394dbab-484f-475d-996e-669625f07e19)

```[tasklist]
### MVP
- [ ] https://github.com/opencollective/opencollective/issues/7437
- [ ] https://github.com/opencollective/opencollective/issues/7429
- [ ] https://github.com/opencollective/opencollective/issues/7430
- [ ] https://github.com/opencollective/opencollective/issues/7432
- [ ] https://github.com/opencollective/opencollective/issues/7433
- [ ] https://github.com/opencollective/opencollective/issues/7435
- [ ] https://github.com/opencollective/opencollective/issues/7436
- [x] Use standard actions pattern and implement drawer
- [x] Side-quest: enquire about Plaid's pricing (@BenJam)
```

For later:
- Connect bank account (https://plaid.com)
- Revert/Batch revert
- Inline documentation
- Documentation
- Improve validations/error messages for CSV import (missing amount...etc)
- Account already imported rows in new imports
- Batch create transactions: Ability to delete import
- Surface import on linked entity dashboard page (expense, order)

**Comment by iamronen** [comment]
@Betree I don't see the expense creation in the MVP (or is that bundled in "Interface for editing"?)

**Comment by Betree** [comment]
@iamronen That, and "Submit import". I'll make that clearer in the issues specifications.

**Comment by Betree** [comment]
**Last week**
- Project Kickstarted
- Came up with a minimal prototype showing how this could look: 

https://github.com/opencollective/opencollective/assets/1556356/1b734d85-8c31-4845-9974-7e953853d948

**This week**
- [ ] Iterate on prototype, start API implementation
- [ ] Find out where to integrate in the dashboard

**Comment by Betree** [comment]
**This week**
- [ ] Merge the first draft (with a feature flag)
- [ ] Implement "Match contribution" action
- [ ] Implement "Add Funds" action
- [ ] Sync with design for the "Create Expense" action

**Comment by Betree** [comment]
**This week**
- [ ] Finish the "Match contribution" action
- [ ] Propose a 1st draft for "Create Expense"

**Comment by Betree** [comment]
Some last-minute feedback that we'll address before closing the project:
- [ ] Ignored on the right side (next to actions)
- [ ] Ignored tag contrast
- [ ] Invoice upload for expenseType=INVOICE
- [ ] Open expense in dashboard
- [ ] Link to add funds from match modal if no match found
- [ ] Clear filters when closing

**Comment by Betree** [comment]
**Release strategy**
- Make sure there are some limits in place to prevent abuse
- Public beta (needs to be enabled from Preview features)
- Have sync calls with hosts to collect feedback and build up some documentation
