### ISSUE TITLE
Pending Financial Contribution Email Link Broken (after Expected Funds Section)

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7417]
**Describe the bug**

With the recent changes to the dashboard (expected funds section) the link of the pending financial contribution email is broken. Notice the following line, 

https://github.com/opencollective/opencollective-api/blob/bbe2f5cc805b539646a9e5a6253621d90ad16187/server/lib/payments.ts#L997

it seems that it points to the order number, and while the redirect takes effect and takes the use to the contributions section, it doesn't take the user to the expected funds section. 

**To Reproduce**
1. Go to a collective which you are admin of (we'll take OSC as an example)
2. Click on https://opencollective.com/opensource/admin/orders?searchTerm=765521
3. While the pending contribution exists it exists on the expected funds section so the user don't see it

**Expected behavior**

The link or the redirect should be updated to the correct one

**Comment by Betree** [comment]
cc @hdiniz or @gustavlrsn (I'm not sure who worked on this last): it seems that the Host Dashboard > Contributions section does not surface pending contributions, even when explicitly selected in the filters:

![image](https://github.com/opencollective/opencollective/assets/1556356/2d80c296-0516-4448-813c-de08126d46e9)

Is that a bug that we need to solve, or do we want to completely differentiate and update the email link to https://opencollective.com/dashboard/europe/expected-funds?

**Comment by hdiniz** [comment]
@Betree I will update the URL, the expected funds orders now appear on a separate dashboard page.

**Comment by Betree** [comment]
@hdiniz Then we should also remove the option to filter by status > Pending on Host Dashboard > Contributions, it's inaccurate.
