### ISSUE TITLE
optional tax field is required when submitting expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#7427]
<img width="371" alt="Screenshot 2024-06-05 at 3 10 59 PM" src="https://github.com/opencollective/opencollective/assets/5498878/5280d691-295b-4c7c-91bd-c176ccf0e9ba">

I tried not putting the GST ID because it's optional but it says required.

**Comment by Betree** [comment]
@alanna should it be required?

**Comment by alanna** [comment]
Inputting the GST number here should be required on invoice expenses but optional on reimbursements.
