### ISSUE TITLE
Most links are broken in the footer

### ISSUE THREAD

**Issue by mDeram** [opencollective/opencollective#7449]
Hello, visiting the website I found out that most footer's links were not working. All the links that are not pointing to external pages are working but not links that are pointing to opencollective.com

**To Reproduce**
1. Go to https://opencollective.com/
2. Scroll down to the footer
3. Try to click on links

**Desktop (please complete the following information):**
 - OS: linux mint 20.3
 - Browser: firefox (v126.0.1) & chromium (125.0.6422.112 for Linux Mint)

**Comment by Betree** [comment]
Thanks for the report, we're looking at this.
