### ISSUE TITLE
emails for nps

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#745]
100 random collective admins (creators of the collective ideally but not sure we can do that)
100 random backers (backers & sponsors)

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by asood123** [comment]
Data sent over slack. 

Query for collective owners:

```sql

with data as (select distinct(c."CreatedByUserId"), max(u."firstName"), max(u."lastName"), max(u.email) from "Collectives" c

left join "Users" u on u.id = c."CreatedByUserId"

where c.type ilike 'collective' and c."deletedAt" is null and u."deletedAt" is null

and u.id != 8 and u.id != 30 and u.id != 772 and c.id != 1

Group BY c."CreatedByUserId") 

select * from data ORDER BY RANDOM() limit 100
```

query for backers

```sql
with data as (select t."CreatedByUserId", u."firstName", u."lastName", u.email from "Transactions" t

left join "Users" u on u.id = t."CreatedByUserId"

where "PaymentMethodId" is not null and type ilike 'credit' and t."deletedAt" is null)

select * from data order by random() limit 100;
```

**Comment by piamancini** [comment]
thanks. @nicobarretoOC can you please add these two queries to the list of queries in the wiki?
