### ISSUE TITLE
Update all Slack links to Discord

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7451]
We are moving Slack conversations from Slack to [Discord](https://discord.opencollective.com/).

![image](https://github.com/opencollective/opencollective/assets/1556356/0d3994ac-0373-4e23-9e50-72e93e36d59d)

In consequence, some links need to be updated:
- [x] API (https://github.com/opencollective/opencollective-api/pull/10152)
- [x] Frontend (https://github.com/opencollective/opencollective-frontend/pull/10487)
- [x] Side repos (REST, PDF...)
- [x] Documentation
- [x] Old blog posts
- [x] Search for additional places in Google with `link:slack.opencollective.com`

**Comment by shannondwray** [comment]
Have we set up a redirect as well?

**Comment by Betree** [comment]
I've kept the slack link for now, to not confuse people clicking on it. I propose to redirect it to discord when we start removing external users from our slack.

**Comment by shannondwray** [comment]
okay!
