### ISSUE TITLE
Wise: you need to be authenticated to do that error

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#7473]
After connecting our Wise account, I'm getting this error. Not sure to understand what it means since the account is connected (and when I open wise.com in another tab I'm logged in).

<img width="831" alt="Screenshot 2024-07-17 at 7 44 56 PM" src="https://github.com/user-attachments/assets/b3f1176c-f000-4b5e-9797-614f36dfcc38">

<img width="450" alt="Screenshot 2024-07-17 at 7 48 39 PM" src="https://github.com/user-attachments/assets/ea2329a3-5f55-43b3-961a-ec1643cdd646">

Couldn't find anything related to that error in the docs (https://docs.opencollective.com/help/fiscal-hosts/payouts/payouts-with-transferwise).

**Comment by Betree** [comment]
cc @kewitz

**Comment by kewitz** [comment]
@xdamman can you confirm you connected this account as the owner of the account?

You can check that by verifying if you're logged in with the same account as the team member who is marked as (Owner) in the Wise dashboard team settings page.

**Comment by xdamman** [comment]
Yes. The person who connected the account was the owner of it. I'm just an admin though. But once connected it shouldn't matter does it?

Also someone reported to me now that this error also shows up simply when submitting an expense. 
Weird. ![image](https://github.com/user-attachments/assets/a7d67b5e-78da-4c7a-b7e4-1ba7f111e75e)

**Comment by xdamman** [comment]
Update: I also experience the same issue when submitting a new expense. I disconnected the Wise account and now it works.

**Comment by kewitz** [comment]
@xdamman, this is a Wise authentication error and there's something weird with your Wise account.
Could you try reconnecting Wise using the Owner profile?

**Comment by kewitz** [comment]
@xdamman thanks for the info. Definitely something on Wise, the previous token looked fine.
I'll reopen this if this happens again.
