### ISSUE TITLE
[Project] Cookie for authentication

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#7476]
We're historically using localStorage for authentication and want to switch to cookie which make more sense.

Using localStorage was originally thought as a way to bypass "Cookie banners" but it was a misconception and essential cookies are absolutely fine without any user input.

**Comment by Betree** [comment]
- [ ] Core engineers to review
- [ ] Merge & deploy

**Comment by Betree** [comment]
**This week**
- [ ] Try and reproduce @kewitz's issue
- [ ] Add cookie on mutations
- [ ] Merge PRs

**Comment by hdiniz** [comment]
## This week

- [ ] Investigate hydration error when enableAuthSsr flag is used by user

**Comment by hdiniz** [comment]
Cookie based authentication is released with preview feature option for using authenticated SSR, it is to be enabled globally after we validate with the team.
