### ISSUE TITLE
[Project] Revert/Edit Added Funds

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#7482]
It's common for Host admins to ask for edition of Added Funds. While we want to keep the ledger immutable, we want to allow this through a revert/refund then re-creating a new Added Funds.

**Comment by kewitz** [comment]
### Implementation Details
- Can be done only at the Contribution level, not the transaction level.
  - Refunding also should be made at the contribution level.

**Comment by kewitz** [comment]
**This week:**
- [ ] Finish API
- [ ] Sync with Design related to prototyped implementation
  - [ ] Implement any design suggestions
 - [ ] Submit for review

**Comment by Betree** [comment]
**This week**
- [ ] Submit for review
- [ ] Iterate on UI/UX to address feedback

**Comment by Betree** [comment]
**This week**
- [ ] Iterate on Frontend based on design feedback @kewitz 
- [ ] Add tax support @kewitz 
- [ ] Re-review API @Betree 
- [ ] Test full feature with taxes @Betree
