### ISSUE TITLE
Set `Reply-To` Address instead of `From` Address in Contact Form

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7496]
**Describe the bug**
There are cases were people would try to contact us using the support form; https://opencollective.com/contact but the emails ends up in the spam folder of support@opencollective.com inbox. This is due to the fact that we set the `<from>` address of the email to the senders email; 

https://github.com/opencollective/opencollective-api/blob/a4e27e8a696e454a6732cd3aa18a3555bc010f3c/server/controllers/services/email.js#L73

and if that email domain is blacklisted by google it can end up in spam. 

I am wondering how we can mitigate this issue as this means we sometimes miss emails and users are not happy. I suggest setting the `<reply-to>` address instead.

**Comment by Betree** [comment]
No blocker on my side, using reply-to makes more sense than from.
