### ISSUE TITLE
add funds error when doing a number with a decimal 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#751]
<img width="1279" alt="screen shot 2017-12-12 at 4 57 57 pm" src="https://user-images.githubusercontent.com/3671070/33910715-b90316b6-df5d-11e7-9a50-b4dcc8d52352.png">

Solved it by rounding up to 38

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by xdamman** [comment]
Fixed in https://github.com/opencollective/frontend/pull/161
