### ISSUE TITLE
Unable to edit form after error when creating a community

### ISSUE THREAD

**Issue by ThisIsMissEm** [opencollective/opencollective#7520]
**Describe the bug**

<img width="744" alt="Screenshot 2024-08-18 at 16 14 19" src="https://github.com/user-attachments/assets/989c23a5-8fbe-4fde-8f91-2a5b57b260f1">

If a picture doesn't say 1000 words, then: If you get a form submission error on `/create/community` then you can no longer edit the form (since it looks like the fields are disabled during submission).

**To Reproduce**
1. Go to `https://opencollective.com/create/community`
2. Fill in the form, using the collective URL of your username (in my case `thisismissem`)
3. Submit the form
5. Try to correct error

**Expected behavior**
I should be able to correct the error and resubmit the form

**Actual behavior**
I am not able to edit the form and resubmit it.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: MacOS 14.6
 - Browser: Firefox
 - Version: 128, with enhanced tracking protection (the little shield icon in the URL bar)

**Additional context**
n/a

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
@ThisIsMissEm Thanks for the detailed report! We'll fix it with https://github.com/opencollective/opencollective-frontend/pull/10598.
