### ISSUE TITLE
Embedding a video in an event description is completely broken (and breaks being able to edit the description at all)

### ISSUE THREAD

**Issue by jdaviescoates** [opencollective/opencollective#7527]
**Describe the bug**
When trying to embed a YouTube video into an event description it no longer works.

Worse, after trying to embed a video in an event description it become impossible to edit the description again.

**To Reproduce**
1. Create an event
2. Try to embed a video.
3. It doesn't work
4. It's now impossible to edit the event description at all.
5. Pull hair out in frustration and begin all over again.

**Expected behavior**
I expect video embeds to work and to not break basic editing functionality

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 24.04
 - Browser: [e.g. chrome, safari] Firefox or Chrome
 - Version: [e.g. 22] latest

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by SudharakaP** [comment]
This is reported here; https://github.com/opencollective/opencollective/issues/7526

**Comment by Betree** [comment]
@jdaviescoates Sorry for not catching this issue before. I've added more details in https://github.com/opencollective/opencollective/issues/7526, we'll look into merging/deploying this one asap, hopefully today.

**Comment by jdaviescoates** [comment]
Thanks @Betree - I'm surprised more people didn't report it! I originally hit it on 27 Aug (as posted [here](https://discord.com/channels/1241017531318276158/1278085373989224458/1278085373989224458) over on Discord) but hadn't realised it was due to the video embeds

**Comment by Betree** [comment]
@jdaviescoates fix deployed!
