### ISSUE TITLE
Recurring expenses should not automatically include a receipt

### ISSUE THREAD

**Issue by RichardLitt** [opencollective/opencollective#7529]
**Describe the bug**
You can set up recurring expenses on the platform, which will automatically be created. However, this automatically copies over the old receipt, too - which is a problem, as new ones need to be uploaded. I've had one instance where a recurring expense was rejected because I hadn't updated the receipt yet, and it wasn't clear I had to.

**Expected behavior**

Recurring expenses should be drafts and not have a receipt attached.

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
It makes sense not to include the previous attachment, receipts are supposed to represent a single payment and thus should be renewed each time.

Looking at the DB, we do have some cases where receipt files are being re-used. Most cases look like the issue that occurred to you: people mistakingly submitting the same October receipt in November. In a few cases, people submit receipts that don't include dates and could therefore be considered valid to re-use, depending on the fiscal host...
I'd still argue for defaulting to accounting best practices and asking for a new receipt for each expense.

@kewitz Pushed an update for this [here](https://github.com/opencollective/opencollective-api/pull/10302), let me know if you agree with the above.

The query:

```sql
SELECT 'https://opencollective.com/' || submitter.slug || '/submitted-expenses', expense_items.url, expense.*, other_expense.*
FROM "Expenses" expense
INNER JOIN "Expenses" other_expense ON expense."RecurringExpenseId" = other_expense."RecurringExpenseId" AND expense."id" != other_expense."id"
INNER JOIN "ExpenseItems" expense_items ON expense."id" = expense_items."ExpenseId"
INNER JOIN "ExpenseItems" other_expense_items ON other_expense."id" = other_expense_items."ExpenseId"
INNER JOIN "Collectives" submitter ON expense."FromCollectiveId" = submitter."id"
WHERE expense."RecurringExpenseId" IS NOT NULL
AND expense_items.url = other_expense_items.url
```

**Comment by RichardLitt** [comment]
New receipt needed for each expense is what I would expect. I agree with you. 

Thanks for checking on this!

**Comment by RichardLitt** [comment]
Post on iNaturalist more!

**Comment by Betree** [comment]
> Post on iNaturalist more!

I should! I saw you landed a PR in their codebase the other day, good job =)

**Comment by RichardLitt** [comment]
Thanks! :) I miss France very often - several times a week, on average. Hope you're well.
