### ISSUE TITLE
show user paypal email to hosts in front end

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#753]
If hosts need to manually send the money via paypal, they don't see the paypal email as they did before. ATM it needs to be searched in the database or if they user included it, 'edit the expense' to disclose the paypal email. 

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by xdamman** [comment]
Fixed in https://github.com/opencollective/frontend/pull/182
