### ISSUE TITLE
[Project] Reference in invoice Expenses

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#7533]
We want to add an optional reference to invoice Expenses and forward that to the payment provider.

Coda link (private):
https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Currently_suSgoFhs#CurrentProjects_tuTeF75U/r224&view=modal

**Comment by Betree** [comment]
**This week**
- [ ] Review, test & deploy @Betree
