### ISSUE TITLE
[Project] Transfer funds between accounts

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#7536]
We want the ability for Collective admins to easily move money between their difference balances (main account and children).

Coda link (private):
https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Currently_suSgoFhs#CurrentProjects_tuTeF75U/r216&view=modal

**Comment by Betree** [comment]
**This week**
- [ ] Kickoff project

**Comment by gustavlrsn** [comment]
### This week
- [ ] Kickoff project (no kickoff last week)

**Comment by Betree** [comment]
**This week**

- [ ] Kickoff project (no kickoff last week)

**Comment by Betree** [comment]
**This week**
 - [ ] Demo MVP

**Comment by Betree** [comment]
**This week**
- [ ] Put for review

**Comment by kewitz** [comment]
**This week**
- [ ] Merge and deploy
