### ISSUE TITLE
Refund Receipt Download Give Error

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7537]
**Describe the bug**

When trying to download a receipt for a refund transaction it gives the error "An unknown error occurred"

**To Reproduce**
1. Go to any transaction which is refunded; such as, https://staging.opencollective.com/backyourstack/transactions?searchTerm=51413
2. Try to download the receipt for the refund transaction
3. See error

**Expected behavior**

The receipt should be able to download correctly

**Screenshots**

![image](https://github.com/user-attachments/assets/f7903f22-a32b-426b-937b-3d6138632852)

**Comment by Betree** [comment]
Looking at this.
