### ISSUE TITLE
OC Slack bot

### ISSUE THREAD

**Issue by evenstensberg** [opencollective/opencollective#7540]
Hi. Is there a OC bot that could work with Slack to report when an expense is submitted and approved?

**Comment by Betree** [comment]
Hi @evenstensberg, you could try using [Webhooks](https://docs.opencollective.com/help/collectives/collective-settings/integrations#webhooks-generic-slack-discord).

**Comment by Betree** [comment]
Closing as it's not an issue, but feel free to ask if you have any question
