### ISSUE TITLE
Private note not captured in expense detail

### ISSUE THREAD

**Issue by Kilheure** [opencollective/opencollective#755]
Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: https://opencollective.com/agreelist/expenses
Logged in as: host to process expense
Error message if any: none
Expected result: Private note should contain have contain the user input detail such as bank account. User confirmed it was input when filling the expense
Browser: Chrome
![screen shot 2017-12-15 at 15 37 43](https://user-images.githubusercontent.com/31570464/34050239-1fae4dbc-e1b2-11e7-8ee6-05163306c8c3.png)

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by asood123** [comment]
Looks like this got fixed. Please reopen if still an issue.
