### ISSUE TITLE
system allowed a collective to have negative balance

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#757]
just paid an expense, available balance showed ~580 and expense was 560 payment went though and now https://opencollective.com/lem is -1

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by asood123** [comment]
This is because we estimate fees as 2.9% + $.30. In this case, the fees were 3.9% + $0.30. I'll increase the estimate on backend.

**Comment by piamancini** [comment]
But wouldn’t this mean that we won’t be able to pay expenses that would be able to be reimbursed otherwise?

**Comment by asood123** [comment]
yes, in some cases it could mean that extra 1% estimated fee could hold back an expense. We need to decide which situation is worse: negative ledger or expense blocked until slightly more money comes in. I'd vote for avoiding negative ledger.

**Comment by asood123** [comment]
Will fix it on bug-fix friday

**Comment by asood123** [comment]
For now, I'm going to change this to 3.9% + 0.30. There is a way to get the fees from paypal - we can create the payment and then cancel it to get fees. It's clumsy and a couple of days of work to get right. Let's come back to it if this is still a big issue.
