### ISSUE TITLE
Failing API request on Collective Dashboard resulting "This account doesn't exist"

### ISSUE THREAD

**Issue by agung2001** [opencollective/opencollective#7570]
**Describe the bug**
It seems that failing API requests resulting an account error notice
<img width="555" alt="Screenshot 2024-09-20 at 20 58 18" src="https://github.com/user-attachments/assets/f1b61952-fdd5-4044-9c5b-2f0dc2cc5011">

The API output : 
```html
<!DOCTYPE html>
<html>
  <head>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta charset="utf-8">
   <title>Application Error</title>
   <style media="screen">
     html,body,iframe {
      margin: 0;
      padding: 0;
     }
     html,body {
      height: 100%;
      overflow: hidden;
     }
     iframe {
      width: 100%;
      height: 100%;
      border: 0;
     }
   </style>
  </head>
  <body>
   <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
  </body>
</html>
```

**To Reproduce**
1. Go to 'Dashboard'
2. Then it'll show
<img width="252" alt="Screenshot 2024-09-20 at 20 46 52" src="https://github.com/user-attachments/assets/daa16d42-9a36-45ad-8eee-9e9e7f7a19d6">

**Expected behavior**
Collective Dashboard open with no error

**Desktop:**
 - OS: MacOS
 - Browser: Chrome
 - Version: Sonoma 14.5

**Additional context**

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment]
@agung2001 It seems like you faced a temporary issue that's been resolved since, could you try again and share the URL if it still fails?
