### ISSUE TITLE
Can't accept recurring donation for collective community due to Stripe

### ISSUE THREAD

**Issue by agung2001** [opencollective/opencollective#7572]
## Who is your user?

Collective Community who lives in unsupported Stripe country

## What are they trying to achieve?

I want to accept recurring donations for my collective community 
https://opencollective.com/dashboard/kami-kerja-remote

but it seems that OpenCollective only accepts recurring donations through Stripe
you can only create a Stripe account in a supported country
https://stripe.com/global

which makes it currently impossible to do, 
living in an unsupported country such as Indonesia, etc
I'm expecting alternative payment or maybe built-in stripe integration in OpenCollective
so the collective community doesn't have to register with Stripe to accept recurring donation

## How are they currently doing this?
 
Other collectives in supported countries can easily create Stripe accounts
and then accept recurring donation

## How well understood is this problem?

 - [x] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [x] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment]
Hi @agung2001, which payment provider would you recommend to support folks in Indonesia?
I suggest you suggest some in https://github.com/opencollective/opencollective/issues/6290.
