### ISSUE TITLE
Expense Category Selection Blocking Expense Submission

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7577]
**Describe the bug**

There can be a case where if there's no expense category can be selected. To reproduce this scenario follow the steps below. 

**To Reproduce**
1. Go to the host settings, to policies section and enable "Require expense submitters to select a category when submitting an expense
"
2. Go to the "Chart of Accounts" section in settings and make sure there are no categories set there. 
3. Try to submit an expense to a hosted collective

**Expected behavior**

The expense flow should not show the expense categorisation section as there's nothing to select. If it does show then we need to be able to select "I don't know" which is the only option.

**Screenshots**

[expenseblock.webm](https://github.com/user-attachments/assets/c3710041-136a-4e91-91aa-ec1dfe4f79a4)

**Comment by SudharakaP** [comment]
We can also recreate this when all the "Chart of Account" categories are set to be visible to fiscal host admins only and then trying to submit a expense as a regular user will get this block.

**Comment by SudharakaP** [comment]
This is reported initially at, https://opencollective.freshdesk.com/a/tickets/366569

**Comment by Betree** [comment]
We should ideally hide the section entirely if there's nothing there for you to select, but as a quick fix we'll pre-select "I don't know" if there's no other option: https://github.com/opencollective/opencollective-frontend/pull/10659.

**Comment by SudharakaP** [comment]
> We should ideally hide the section entirely if there's nothing there for you to select, but as a quick fix we'll pre-select "I don't know" if there's no other option: [opencollective/opencollective-frontend#10659](https://github.com/opencollective/opencollective-frontend/pull/10659).

Thanks a lot; very useful as otherwise users are blocked from submitting expenses in this case.
