### ISSUE TITLE
Wise: Implement partial refunds of payment processor fee

### ISSUE THREAD

**Issue by kewitz** [opencollective/opencollective#7579]
I also have an update for you about refunds for bounced Swift transfers. This only applies to currencies sent outside their local settlement area, eg USD sent to China or EUR sent to Singapore etc.

When Wise pays out a transfer via Swift we need to use intermediary banks before the funds reach the beneficiary. These banks can take a fee for processing the payment and if that payment is then rejected we might receive less back than was originally sent. The fees are typically 20-50 USD.

Previously we've been refunding the full amount sent, meaning Wise was at a loss. We will need to change this so you'll be seeing some refunds which are less than the amount sent. To be clear, we won't be charging you for these returned payments, the only change is that the fees charged by other banks won't be covered by Wise.

Transfer State Change event won't be changing but you can use that to see that the payment has bounced back and been refunded. 
This refund webhook will show you the amount as well: https://docs.wise.com/api-docs/features/webhooks-notifications/event-types#transfer-refund

**Comment by Betree** [comment]
**This week**
- [ ] Iterate on review
- [ ] Sync with Wise to see if we can deploy next month

**Comment by kewitz** [comment]
This is safe to ship when I get back in early November.

**Comment by kewitz** [comment]
**Previous week**
- [x] Merge and deploy
- [x] Set up new webhooks
- [x] Monitor 

**This week**
- [ ] Contact Wise about why we're not receiving transfers for the transfers#refunded event
- [ ] Review event and code
- [ ] Turn on TRANSFERWISE_USE_TRANSFER_REFUND_HANDLER
