### ISSUE TITLE
[Question] How to retrieve custom donations data via GraphQL API?

### ISSUE THREAD

**Issue by DigitalBrainJS** [opencollective/opencollective#7603]
The platform allows you to create a custom recurring donation for a collective, essentially a membership with a custom tier. However, the API doesn't treat such donations as a membership, so `member.tier` is null. Is there a way to get such sponsor's donations via the API to determine their type (one-time/monthly/annual) so we can treat them as ordinary memberships on the client side?
![Image](https://github.com/user-attachments/assets/406867f9-f6db-4a74-a7f2-e9ec48c0647a)

**Comment by Betree** [comment]
Hi @DigitalBrainJS, you could try to get the matching "order" and get its `frequency` + `amount`.
