### ISSUE TITLE
Problems with expenses showing reject option Universal Viewer Collective

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#761]
Edward from Universal Viewer Collective is having trouble with some expenses that have already been approved are shown as approved with the option to reject them. There is one expense that need to be deleted since it has already been re-submitted. (see in video)

**Edward made a good video where he shows whats going on:**
https://drive.google.com/open?id=1Q4xVIJLr3oi4k0ccn6I9uGDZZOXvSqpL

**So there are two things we need here:**
- Remove the expense that is shown in the video
- Figure out why he is still being presented the reject expense option after having approved most of them.

**Comment by xdamman** [comment]
Another user was complaining that they couldn't reject an expense after having approved it by mistake ¯\_(ツ)_/¯ 

To delete an expense, just reject it

**Comment by asood123** [comment]
Is this resolved @nicobarretoOC or do you need something more?

**Comment by nicobarretoOC** [comment]
Let me check with the user.

**Comment by nicobarretoOC** [comment]
Ok, Pia replied and we have no answer from the user, I will close this now and then if he replies to me we decide if we should re-open this.

**Comment by nicobarretoOC** [comment]
Ok I am re-opening this issue since Brittani from WWCode has a similar problem.

Message:

> I'm having some issues changing the amount of expenses in Manila's Open Collective. https://opencollective.com/wwcodemanila/expenses 
> 
> I've been able to change quite a few but for some reasons cannot with these, any ideas? 

<img width="1130" alt="screen shot 2017-12-20 at 4 26 18 pm" src="https://user-images.githubusercontent.com/30665166/34230420-b00e8180-e59d-11e7-906d-17f2226ed34c.png">

Her intention is to edit those expenses but rejecting them might delete them and approving them will send a green light to be paid, (tha is what confuses her.

**Comment by edsilv** [comment]
Hi, I'm still seeing the same issue where I can approve or reject expenses that have already been paid:

![image](https://user-images.githubusercontent.com/1334393/34249444-a94b069a-e631-11e7-9589-98230f5105a3.png)

**Comment by xdamman** [comment]
So there was a bug with editing expenses with a decimal amount. That was fixed a few days ago in https://github.com/opencollective/frontend/pull/161

The available balance only gets updated when an expense is paid, not when approved.

I'm making a change now to only show the reject button for up to 10mn after the expense has been approved (in case if it was approved by mistake)
