### ISSUE TITLE
Follow up with collective activation (Burgerbeweging)

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#763]
Self hosted collective user has set up a Stripe account and now needs to connect it to the Collective. 

I believe the next step is to send them a link to do so but I need the host-user to complete the opencollective.com/`hostuser`/settings link.

The collective is:
https://opencollective.com/Burgerbeweging

**Comment by nicobarretoOC** [comment]
@xdamman @asood123 I need to send this user a mail to connect their Stripe account. Is this still done through a especial address address as mentioned above?

**Comment by asood123** [comment]
As far as I know, @xdamman will know for sure

**Comment by nicobarretoOC** [comment]
@xdamman @asood123 seems like this collective mission is to support social impact initiatives, primary language is Dutch. I believe it fits more the description of a host so he can manage funds for several collectives in Dutch. How should we proceed?

The user already created a Stripe account and collective and is waiting to get reviewed so he can connect both. 

Here is the description of his collective mission in English:

> Financing your project is often not an easy thing. Certainly not when it comes to initiatives that mainly focus on impact and therefore do not always have a profitable business model.
> With this collective we want to give these initiatives a helping hand.

**Comment by xdamman** [comment]
Just replied. Sorry about the delay here. Closing this issue for now.
