### ISSUE TITLE
Disabled "Mark as paid" button for manual payments

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7630]
**Describe the bug**
The "Mark as paid" button when selecting "Manual" sometimes appear as disabled without any clear reason.

**To Reproduce**

1. Go to https://opencollective.com/dashboard/europe
2. Click "Go to pay" on a bank account expense
3. Quickly switch to "Manual"
4. See disabled button

**Expected behavior**
1. Button should not be disabled. It appears to be related to the quote loading logic for Wise spilling onto manual payments.
2. Bonus: When we disable buttons like that, it's great to add a tooltip to explain why we're doing it (i.e. `Please wait for the quote information to be loaded to trigger the payment`)

**Screenshots**
![Image](https://github.com/user-attachments/assets/0ae0b84b-2b37-4f1b-ad88-46d3fb6f38a3)

cc @kewitz

**Comment by PRATYUSH-MISH** [comment]
I would like to solve this issue please grant me this issue @Betree 
**Disabled "Mark as paid" button for manual payments #7630**

**Comment by Betree** [comment]
@PRATYUSH-MISH Sorry, this issue is too complex for an external contributor.
