### ISSUE TITLE
Creating a profile leads to 404

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7631]
**Steps**
- Create organization
- See error

Looks ok after refreshing the page. Looks like a frontend navigation issue.

![Image](https://github.com/user-attachments/assets/0c96ad4e-416f-44e3-a6ed-9ef5ce6dc379)

**Comment by kewitz** [comment]
@Betree I can't reproduce this error. Is this as generic as it looks or is it a specific context this happens?

**Comment by Betree** [comment]
@kewitz thanks for investigating, I was indeed not able to reproduce anymore - both with Vercel / Authenticated backend and without them.
