### ISSUE TITLE
Double backer has no clickable avatars in OC widget [bounty: 24 XatteR]

### ISSUE THREAD

**Issue by DreadKnight** [opencollective/opencollective#7633]
**Describe the bug**
Double backer missing from OC official widget for over a month now.
I've got messaged yesterday about it and seems he was actually right.
Somehow the widget has skipped the double entries, not showing their avatars.

**To Reproduce**

1. Go to https://opencollective.com/ancientbeast/members/all.json
2. See ids 70 and 71, with https://opencollective.com/buy-tiktok-likes2 and https://opencollective.com/buy-tiktok-followers1 profiles
3. Check https://ancientbeast.com/#backers (the div with more avatars)

**Expected behavior**
There are no clickable avatars for a backer that's supporting the project with 2 accounts.

**Screenshot**
![Image](https://github.com/user-attachments/assets/3acbab3f-7e80-4658-a5a6-f1c35d3fd268)

**Device:**
- OS: Kubuntu 24.04
- Browser: Firefox 131.0.3 (64-bit)

**Additional context**
Are linkedin links banner or something?

I'm offering 24 XatteR as bounty 🪙 for this issue. Token info:
https://github.com/FreezingMoon/AncientBeast/wiki/XatteR

**Comment by Betree** [comment]
The reason is that they cancelled their recurring contribution already. If you want to get them, you'll need to set the `isActive=flag`, but you'll also get everyone else who cancelled in the past: https://opencollective.com/ancientbeast/tiers/backer.svg?avatarHeight=80&width=890&limit=unlimited&button=false&isActive=false.

**Comment by DreadKnight** [comment]
> The reason is that they cancelled their recurring contribution already. If you want to get them, you'll need to set the `isActive=flag`, but you'll also get everyone else who cancelled in the past: https://opencollective.com/ancientbeast/tiers/backer.svg?avatarHeight=80&width=890&limit=unlimited&button=false&isActive=false.

@Betree Argh, thanks for the answer. Had a feeling this might be the case as I recall seeing the avatars before...

**Comment by DreadKnight** [comment]
@Betree The avatars weren't showing around when he was subscribed with both accounts. He just unsubscribed with both 15 hours ago 😢

**Comment by DreadKnight** [comment]
Added his avatars manually on the homepage, will try to get him back as a subscriber and see what happens, though usually low chances for that to happen...

**Comment by Betree** [comment]
> [@Betree](https://github.com/Betree) The avatars weren't showing around when he was subscribed with both accounts. He just unsubscribed with both 15 hours ago 😢 This went exactly as expected...

It's difficult to debug after the fact. Please ping me here if you have other similar examples and I'll investigate.

**Comment by DreadKnight** [comment]
@Betree We got a new backer and bumping into a similar issue. Been doing some tests and it seems that the "&limit=unlimited" parameter tag is causing for the last backer to not be displayed; perhaps this is why the previous double backer didn't get displayed either, as we're using the first code bellow on the homepage https://AncientBeast.com/#backers

https://opencollective.com/ancientbeast/tiers/backer.svg?avatarHeight=80&width=890&limit=unlimited&button=false
![Image](https://github.com/user-attachments/assets/bf098236-434c-483a-a551-c4cb3ff2ed23)

https://opencollective.com/ancientbeast/tiers/backer.svg?avatarHeight=80&width=890&button=false
![Image](https://github.com/user-attachments/assets/b516eff3-8e0e-421a-ba96-3b159309a7e8)

If I change from "unlimited" to a number, it shows the last backer.
I *might* remove the parameter altogether or just have a number for it instead of "unlimited".

**Comment by Betree** [comment]
"unlimited" is not a supported value for the `limit` parameter. You probably got confused by this documentation:

![Image](https://github.com/user-attachments/assets/f8135a22-5ece-4be9-902f-7e6d8d75fc95)
