### ISSUE TITLE
Launch bitcoin support via Stripe

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#764]
Remaining items

- [x] Check that frontend is always setting a type when creating paymentMethods (@xdamman) [for paypal, it's 'adaptive'. For stripe, it's 'creditcard' or 'bitcoin']
- [x] Get frontend tests to pass [@xdamman]
- [x] finish moving stripe webhook over
- [x] create new email template while bitcoin orders are being processed (aseem) 
- [x] populate 'type' on existing paymentMethods (aseem)
- [x] move paypal payment method to new structure (aseem)
- [x] move opencollective payment method to new structure (aseem)
- [x] get all existing tests to pass on API (aseem)
- [x] Write/update test for bitcoin createOrder (aseem)

**Comment by xdamman** [comment]
For PayPal, the frontend simply calls `/api/connected-accounts/paypal/oauthUrl`
https://github.com/opencollective/frontend/blob/master/src/lib/api.js#L47
Having a quick look at your code it doesn't seem that you are taking into account any `type` parameter for the PayPal flow at the moment.

**Comment by asood123** [comment]
launched
