### ISSUE TITLE
Return Dynamic Height for OpenCollective Embed iframe

### ISSUE THREAD

**Issue by Muhammad-Owais-Warsi** [opencollective/opencollective#7640]
## Who is your user?
The Hacktoberfest website displays the `OpenCollective` organizations on their site.

## What are they trying to achieve?
To display the `OpenCollective` organizations, we are using an `iframe`. 

In order to set the dimensions of the `iframe` one has to know about the hight and width, but it seems we have to hardcode these values in our code. It would be great if we get these dimensions from the embed url itself.
## How are they currently doing this?
They are hardcoding the dimensions.

## How well understood is this problem?
I have to make some research on how to implement this feature and maybe need some help

- [x] Surfacing: if you feel this is a seed of an idea that needs to be researched.
- [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
- [ ] Shaping: if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
- [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment]
@Muhammad-Owais-Warsi Could you link to the URL on Hacktoberfest where the iframe is displayed and share screenshots? Thank you!

**Comment by Muhammad-Owais-Warsi** [comment]
Sure, @Betree. On the [donate](https://hacktoberfest.com/donate/) page, the organizations under OpenCollective have iframe embeds. However, part of the embed is not visible due to insufficient height. Currently the height of the iframe container is hardcoded in Hacktoberfest codebase.
![Image](https://github.com/user-attachments/assets/f3bbe0a6-b899-451a-8eb4-31a5ae42249d)

**Comment by Betree** [comment]
@Muhammad-Owais-Warsi Thanks! This could be enabled via [channel messaging](https://developer.mozilla.org/en-US/docs/Web/API/Channel_Messaging_API/Using_channel_messaging), it's something we've been [willing to implement](https://github.com/opencollective/opencollective/issues/4341) for quite some time now.

**Comment by Muhammad-Owais-Warsi** [comment]
Hey @Betree sorry for the late response, can you please provide me with the link of the repo, where `channel messaging` is implemented in `opencollective` codebase.

**Comment by Betree** [comment]
https://github.com/opencollective/opencollective/issues/4341 is still open, channel messaging hasn't been implemented yet. It needs to be implemented in https://github.com/opencollective/opencollective-frontend. The code for the embedded contribution flow lives in `pages/embed/contribution-flow.js`.

**Comment by Muhammad-Owais-Warsi** [comment]
Hey @Betree , I think we can include the `height` param in the `components/EmbeddedPage.js` [link](https://github.com/opencollective/opencollective-frontend/blob/main/components/EmbeddedPage.js) .Up their the height is already set as `100%`. After that we can use up that param in the `pages/embed/contribution-flow.js` [link](https://github.com/opencollective/opencollective-frontend/blob/main/pages/embed/contribution-flow.js).

**Comment by Betree** [comment]
@Muhammad-Owais-Warsi I don't really get your proposal, why not set the height directly in the iframe in this case?

**Comment by Muhammad-Owais-Warsi** [comment]
I understand , but it would be great to have the `height` along with the other params. Thanks :)

**Comment by Muhammad-Owais-Warsi** [comment]
Hey @Betree , so we get the dimensions of the iframe, now as well ?

**Comment by Betree** [comment]
Yep! It's not deployed yet, but everything's documented in https://github.com/opencollective/opencollective-frontend/pull/10880.

**Comment by Muhammad-Owais-Warsi** [comment]
> Yep! It's not deployed yet, but everything's documented in [opencollective/opencollective-frontend#10880](https://github.com/opencollective/opencollective-frontend/pull/10880).

Thanks, by when can we expect it to be deployed.

**Comment by Betree** [comment]
It's live

**Comment by Muhammad-Owais-Warsi** [comment]
Hey @Betree , https://docs.opencollective.com/help/collectives/contribution-flow#url-parameters, I can't find the dimensions in the docs. Thanks.
