### ISSUE TITLE
Ability to disable contributions on a specific project

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7650]
Ecosystems need a way to create projects with contributions disabled, while still allowing added funds.

We can probably achieve that already with `data.features.RECEIVE_FINANCIAL_CONTRIBUTIONS = false` on the project, but there's no easy way to set it easily in the API.

- [x] Ideally, the flag should be part of the `createProject` mutation.
- [x] Make sure `RECEIVE_FINANCIAL_CONTRIBUTIONS` doesn't prevent added funds.
- [x] Make sure it prevents `createOrder`

**Comment by andrew** [comment]
@Betree are there docs for this?

**Comment by Betree** [comment]
@andrew I was waiting on the deployment to ping you with the how-to but we have something blocking and can't deploy to production right now. This should be resolved in a few hours.

In the meantime, it's already available on staging: you simply need to pass `disableContributions: true` to the `createProject` mutation.

**Comment by andrew** [comment]
I tried this out today on staging either I'm not sure if I did it wrong or it's not working as expected:

```
      mutation CreateProject($parent: AccountReferenceInput!, $project: ProjectCreateInput!) {
        createProject(parent: $parent, project: $project, disableContributions: true) {
          id
          legacyId
          name
          description
          slug
          tags
          website
          imageUrl
          createdAt
          updatedAt
        }
      }
```

The resulting project: https://staging.opencollective.com/ecosystems/projects/esf-github-sponsors-foosel

![Image](https://github.com/user-attachments/assets/73744c52-1141-4159-b97d-a60daa986f12)

which still has the submit expense and request grant buttons visible to everyone (screenshot from logged out)

**Comment by Betree** [comment]
@andrew The original issue was only about receiving contributions. I'll document the need to disable expenses as well, we will certainly achieve that through a similar `disableExpenses` flag.
