### ISSUE TITLE
Transactions CSV in Dashboard do not Populate `oppositeAccountEmail`

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#7651]
**Describe the bug**

It seems that in the new transactions csv which can be downloaded from the dashboard transactions section do not populate the `oppositeAccountEmail` for any row. 

**To Reproduce**

1. Go to a collective that you administer
2. Go to the dashboard Transactions section
3. Download the CSV; make sure the preset is set to include the column `oppositeAccountEmail`

**Expected behavior**

For all individual accounts which contributed to the collective the `oppositeAccountEmail` should be populated. 

**Additional context**

Here I am attaching a sample CSV, I generated using the staging environment. 

[backyourstack-transactions (1).csv](https://github.com/user-attachments/files/17675997/backyourstack-transactions.1.csv)

**Comment by relicarious** [comment]
This blocks a workflow for me in which I extract addresses to process memberships externally, causing us problems with an event.

Is there some workaround we can use to get the CSVs while this bug is still live?

**Comment by Betree** [comment]
@relicarious You can try exporting your contributors information from your Dashboard > Contributors > Export CSV.

**Comment by relicarious** [comment]
Forgot to reply to this. Just wanting to say: thank you that did the job! <3
