### ISSUE TITLE
Lock some of the fields in an expense invite

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7661]
From Ecosystems:

> when we send an expense invite it’s possible for the invitee to change the amount without the admins being aware that a change has occurred

## Proposed solution

- In the mutation to create an expense draft invitation, support a `lockedFields` parameter to define fields that can't be edited by the invitee.
- In the frontend, respect the `lockedFields` defined when editing the draft
- In the API, make sure `lockedFields` can't be edited

We're not yet building the frontend capability to lock fields when sending a new expense invite.

**Comment by Betree** [comment]
test

**Comment by Betree** [comment]
test

**Comment by Betree** [comment]
cc @hdiniz make sure we consider this in the new expense flow for editing

**Comment by kewitz** [comment]
@andrew you can lock drafted expense fields using the `lockedFields` parameter when calling `draftExpenseAndInviteUser`:
```gql
draftExpenseAndInviteUser(
  expense: $expense
  account: $account
  skipInvite: $skipInvite
  lockedFields: [AMOUNT, DESCRIPTION, TYPE]
) {
  id
  legacyId
  status
  draft
  lockedFields
}
```
