### ISSUE TITLE
[Project] Improve dashboard contributions display and sorting

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7664]
## Overview

> I am fiscal host admin of a collective that relies mostly on recurring contributions. When I look at my list of incoming contributions I see that the latest contributions took place months ago. When I look at my list transactions I do see that I do have more recent contributions. This discrepancy makes me doubt the trustworthiness of the contributions list I am seeing. 

## Ownership

**Owner:** @kewitz 

_Note: Project owner responsibilities include coordinating all the different people that need to contribute to the project, defining specs and goals, communicating project progress, being the point person for decisions, QA, documentation, and a plan for ongoing maintenance. If the project owner can't continue, they need to hand the role over to another person explicitly._

## Desired Outcomes

![Image](https://github.com/user-attachments/assets/2553b96a-1ed7-4692-826f-7a65123b3da5)

## Context & related issues

- https://coda.io/d/Make-Open-Collective_dnHLKv7oLV0/Currently_suSgoFhs#CurrentProjects_tuTeF75U/r286&view=modal

**Comment by Betree** [comment]
**This week**
- [ ] Submit for review: revisions on the database
- [ ] Iterate on performance

**Comment by Betree** [comment]
**This week**
- [ ] Merge & deploy
- [ ] Tweaks in the frontend
- [ ] Iterate on performance

**Comment by Maliksb11** [comment]
i am happy
