### ISSUE TITLE
Twitter integration deprecaction email notice

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#7666]
Requires https://github.com/opencollective/opencollective/issues/7685

Write an email "Deprecation notice" with links to Discord + Github (for feedback and assistance). Clarify that it's about the integration, NOT linking their Twitter on the profile (they can still do that from the profile settings).

To find the right person to send the email to, we'll need to crunch some data: due to https://github.com/opencollective/opencollective/issues/6870, many accounts are actually not working at the moment. With the recent deployment of https://github.com/opencollective/opencollective-api/pull/10473, we should be able to see how many are still active.

**Query:**

```sql
WITH affected_accounts AS (
  SELECT c.*
  FROM "ConnectedAccounts" ca
  INNER JOIN "Collectives" c ON ca."CollectiveId" = c.id
  WHERE ca.service = 'twitter'
  AND ca."deletedAt" IS NULL
  AND (ca.settings -> 'needsReconnect')::boolean IS NOT TRUE
  AND c."deletedAt" IS NULL
  AND c."isActive" IS TRUE
  AND slug NOT IN ('opencollective', 'captainfact_io')
  GROUP BY c.id
) SELECT c.id, 'https://opencollective.com/' || c.slug, array_agg(DISTINCT admin_users.email) as admins
FROM affected_accounts c
INNER JOIN "Members" admin_members ON admin_members."CollectiveId" = c.id AND admin_members.role = 'ADMIN' AND admin_members."deletedAt" IS NULL
INNER JOIN "Users" admin_users ON admin_users."CollectiveId" = admin_members."MemberCollectiveId" AND admin_users."deletedAt" IS NULL
GROUP BY c.id, c.slug
```

**Comment by Betree** [comment]
Email sent to the admins of 55 collectives:
- https://opencollective.com/ant-design
- https://opencollective.com/flyimg
- https://opencollective.com/socialmarket
- https://opencollective.com/torontojs
- https://opencollective.com/raspap
- https://opencollective.com/animal_rebellion_germany
- https://opencollective.com/denosaurs
- https://opencollective.com/pixieditor
- https://opencollective.com/silicon-valley-robotics
- https://opencollective.com/foodandsolidarity
- https://opencollective.com/pentakly
- https://opencollective.com/nakas
- https://opencollective.com/thexylom
- https://opencollective.com/stroud-district-community-hubs
- https://opencollective.com/frontenddogma
- https://opencollective.com/cncnet
- https://opencollective.com/nuclear-electrical-engineers
- https://opencollective.com/hakky54
- https://opencollective.com/unikraft
- https://opencollective.com/prismane
- https://opencollective.com/bitcoinfinancier
- https://opencollective.com/sokeio
- https://opencollective.com/horizon_sim
- https://opencollective.com/biome
- https://opencollective.com/wiefunkdai
- https://opencollective.com/brtv
- https://opencollective.com/ilihub
- https://opencollective.com/selenium
- https://opencollective.com/cloud-inject
- https://opencollective.com/octocatgithubio
- https://opencollective.com/gac
- https://opencollective.com/lumina
- https://opencollective.com/kinsondigital
- https://opencollective.com/api-platform
- https://opencollective.com/panda-wallet
- https://opencollective.com/tipos-de-coimbra
- https://opencollective.com/teachmastermindpat
- https://opencollective.com/africacryptochainxinnovators
- https://opencollective.com/africacryptochainxinnovatorscom
- https://opencollective.com/africacryptochainx-innovators
- https://opencollective.com/africacryptochainx
- https://opencollective.com/knewkarma
- https://opencollective.com/hearsayhunter
- https://opencollective.com/trust-walletp
- https://opencollective.com/bsidesphilly
- https://opencollective.com/budgetcontrol
- https://opencollective.com/vcs-academy
- https://opencollective.com/brisa_build
- https://opencollective.com/ccmx
- https://opencollective.com/voces-de-esperanza-raramuri
- https://opencollective.com/psake
- https://opencollective.com/africacryptochainx-core-innova
- https://opencollective.com/icanfixthat
- https://opencollective.com/imgnx
- https://opencollective.com/rate

**Comment by farhanali9014** [comment]
“It’s important that TM SIM users can access online registration easily and without delays. The process is designed to help keep mobile connections secure and active, but sometimes the system can be slow or confusing. Hopefully, improvements will make [TM SIM online registration](https://phtmsimregister.com/) faster and more convenient for everyone.”
