### ISSUE TITLE
Review Perkeep Collective

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#767]
New OS collective waiting for approval: https://opencollective.com/perkeep

**Comment by nicobarretoOC** [comment]
Adding to this, a request from the user: 
We want donations in USD but we pay one guy who's in France and wants EUR.

Whats the best way to handle this?

**Comment by asood123** [comment]
Currency depends on the host - if they want donations in USD, then host should be in USD. Their developer can file expenses in USD (using a conversion rate) and we'll pay that out through PayPal.

**Comment by asood123** [comment]
It's an open source project, so currency has to be USD

**Comment by asood123** [comment]
It's already active as well. I'll submit PR soon.
