### ISSUE TITLE
Figure out what to do with expense Id: 1737

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#768]
It got paid out twice. Maybe we can refund from paypal?

**Comment by asood123** [comment]
We can't refund without going through the dispute process. Don't want to have to deal with Paypal. I emailed the user to see if he's willing to refund the money.

**Comment by asood123** [comment]
User says he'll be able to refund the money to us after Jan 13

**Comment by piamancini** [comment]
@asood123 was this a manual error?

**Comment by asood123** [comment]
I doubt it. I think something funky in approve/reject flow.
