### ISSUE TITLE
Bad link in collective page header?

### ISSUE THREAD

**Issue by bradfitz** [opencollective/opencollective#770]
URL: https://opencollective.com/perkeep
Logged in as: bradfitz

The "4 backers" link in the header links to #organizations but should be a link to the '#backers' section.

![screen shot 2017-12-20 at 10 57 48 am](https://user-images.githubusercontent.com/2621/34223620-db92fc06-e574-11e7-9c4c-9049a37cfd3a.png)

That is, this goes nowhere:

https://opencollective.com/perkeep#organizations

But this is where it should link to:

https://opencollective.com/perkeep#backers

**Comment by asood123** [comment]
Thanks for reporting, will fix
