### ISSUE TITLE
right to left languages alignment issue

### ISSUE THREAD

**Issue by epageperron** [opencollective/opencollective#7711]
**Describe the bug**
Right-to-left languages display aligned to left (they should align to right).

**To Reproduce**

paste some arabic text in a project description, you will see the issue in the editor and also after saving, when viewing the project description

**Expected behavior**
Languages should align by defaut to their usual reading direction. 

**Screenshots**

**Device:**
- OS: [e.g. iOS 8, Android 9, Windows 10, Ubuntu 20.04]
- Browser: [e.g. chrome 22, safari 10]

**Additional context**

**Comment by Betree** [comment]
Can confirm the issue, the rich text editor is clever enough to add a `dir="rtl"` on the content but we're then stripping out this information when saving:

https://github.com/user-attachments/assets/888e9699-e64a-4961-af72-d96a725a25a5

We'll try a fix in https://github.com/opencollective/opencollective-api/pull/10552.

**Comment by Betree** [comment]
@epageperron Fix deployed, you should get it to work by editing the description and saving it again. Thanks for reporting the issue!
