### ISSUE TITLE
Cannot apply for collective

### ISSUE THREAD

**Issue by magiconair** [opencollective/opencollective#773]
I am trying to apply for a collective for github.com/fabiolb/fabio with 4300 starts which is a github org which I own and for which I'm the sole maintainer. When I log in as @magiconair it doesn't show up. What am I missing?

URL: github.com/fabiolb/fabio
Logged in as: magiconair
Error message if any: Can't find repository with more than 100 stars
Expected result: find fabiolb/fabio
Browser: any

**Comment by magiconair** [comment]
<img width="1158" alt="screen shot 2017-12-20 at 22 58 19" src="https://user-images.githubusercontent.com/229005/34230757-8e3f0e94-e5d9-11e7-9f9a-7d537438cdde.png">

**Comment by asood123** [comment]
Hi @magiconair, you need to OAuth the organization, since this repo is under the org. It's usually on the bottom left of the GitHub auth screen. If it doesn't show you the screen again, you can go in settings and take remove Open Collective's OAuth token and then screen will show again. 

If it still doesn't work, could you please share a screenshot of the OAuth screen?

**Comment by magiconair** [comment]
How do I do this since I only ever get to see this screen: https://opencollective.com/opensource/apply

and from there I get to the one I've pasted before. There is no page where I could choose the org or my account.

**Comment by asood123** [comment]
Visit: https://github.com/settings/applications and revoke Open Collective app. It should then show you the GitHub OAuth screen again.

**Comment by magiconair** [comment]
Nope. Same issue. I get to authorize the access but it still won't list the fabio repo or org.

<img width="702" alt="screen shot 2017-12-20 at 23 29 46" src="https://user-images.githubusercontent.com/229005/34231862-fc4449be-e5dd-11e7-8808-6e13da5bd4f8.png">

**Comment by magiconair** [comment]
When I setup an OAuth app in the fabiolb org with the details from #209 then I'm at least logged in but didn't get much farther.

**Comment by asood123** [comment]
Hmm can you try visiting https://github.com/organizations/fabiolb/settings/oauth_application_policy and see if it's restricted there?

Otherwise, we just changed github permissions today and I wonder if that's what's causing it: https://github.com/opencollective/opencollective/issues/355

**Comment by magiconair** [comment]
<img width="765" alt="screen shot 2017-12-20 at 23 37 37" src="https://user-images.githubusercontent.com/229005/34232046-d1bf3f90-e5de-11e7-8819-eb0b45a746ed.png">

**Comment by magiconair** [comment]
@asood123 any idea?

**Comment by dstpierre** [comment]
I have the exact same issue - the repository in the org with > 100 stars cannot be seen.

**Comment by asood123** [comment]
Ok I'm going to revert the scope change and see if this fixes it for you.

**Comment by asood123** [comment]
@magiconair and @dstpierre: Would you please try again? You should automatically see the Github oauth screen (since scope is increasing). If you don't, please revoke Open Collective permissions at: https://github.com/settings/applications.

**Comment by magiconair** [comment]
@asood123 yep, that's better.

**Comment by dstpierre** [comment]
same here thanks @asood123
