### ISSUE TITLE
Retry payment for Mateusz 

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#774]
Mateusz says his PayPal Address should be able to receive payments now. More info in his email.

**Comment by asood123** [comment]
I'm not following what has to be done here. Expense is marked as "other", meaning we won't pay it through paypal anyway.

**Comment by nicobarretoOC** [comment]
Hey @asood123 Seems to be a process that Pia was handling, user sent his W-8BEN form.

Last message from Pia to Mateusz was:

> We tried to pay for your expense now, but according to paypal you've reached a limit of money you can receive and you need to contact them to update your info. 
Let's us know once you solve it so we can try again. 

Then Mateusz sent:

> This thing is taking really long with PayPal. They told me that I should be able to receive payments now, although the whole verification process is not yet finished. Could you try again tomorrow?

**Comment by nicobarretoOC** [comment]
@piamancini just following up with this, Mateuzs says Paypal messaged him saying they have lifted restrictions.
