### ISSUE TITLE
Assist Duane changing email & deleting an extra account

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#775]
Duane needs to change the email address associated with his acocunt, he is changing email address. He also needs help deleting an extra account he created when trying to fix this. it is the anonymous40 account on the https://opencollective.com/duaneobrien Collective.

**Comment by asood123** [comment]
I switched his accounts. We can't delete paypal email because it's linked to a one-time donation. His gmail will now allow him to edit his profile listed above.

**Comment by nicobarretoOC** [comment]
Thanks!
