### ISSUE TITLE
Assist with account to edit subscriptions (Edubit)

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#776]
Thomas from https://opencollective.com/edubit organization is unable to see/edit his subscriptions to Collectives like Dokku. 

I believe it is a problem with different accounts so even if he logs in to www.opencollective.com/subscriptions he is unable to see them. 

Do you guys know the email account associated with that organization?

**Comment by asood123** [comment]
This is a bug. /subscriptions is currently only returning subscriptions that were made by that individual, not all subscriptions from an organization that the individual is an admin of.

@nicobarretoOC You can leave this issue open. Separately, can you please ask him what he wants to do with his subscription. We can do it for him manually, while we work on this.

**Comment by nicobarretoOC** [comment]
Yep, just emailed him asking for that.

Let's wait for the reply.

**Comment by nicobarretoOC** [comment]
Ok @asood123 seems like Thomas only needs his invoices for now.
