### ISSUE TITLE
Add onHover:pointer style to SVG

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#778]
From user: 

> I have just one more little request: the SVG is clickable, but when you mouse goes over it, it doesn't show the pointer. I've done some research on StackOverflow, etc, and it looks like the best way to do this would be to add the style into the SVG file - could you have a look at this? That way the image would just be perfect, and most sponsors are paying to have their clickable image, so that's very important for them.

**Comment by xdamman** [comment]
@jdubois will take a stab at it after Xmas :)
This is where to look: https://github.com/opencollective/frontend/blob/master/src/server/lib/image-generator.js#L76

**Comment by jdubois** [comment]
I just did the PR, it was very easy :-)
