### ISSUE TITLE
Text unreadable on some background cover images

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#779]
some cover images don't make it easy to see the text:
https://opencollective.com/mixmax
https://opencollective.com/codenplay

We should allow to change the colors or detect the dominant color of the background, or apply a filter to the background.

**Comment by ryh** [comment]
or you can use javascript to tell the color palette then use invert color like iTunes Album Colors did.

Check these out 
https://github.com/chengyin/albumcolors
https://github.com/lukasklein/itunes-colors

https://github.com/panicinc/ColorArt (Objective-C)

**Comment by piamancini** [comment]
this still needs attention

**Comment by piamancini** [comment]
Closed as covered by https://github.com/opencollective/opencollective/issues/1213
