### ISSUE TITLE
update FAQ's

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#78]
- [ ] How to claim funds for hours worked on project 
- [x] Change/remove 'only in US' answer

**Comment by GranularDetective** [comment]
I'd be interested in the methodology. I don't envy you the task but if you can come up with a fair and equitable system, which either dispenses with the need for self-reporting, or makes self-reporting verifiable then I will be extremely impressed. Best wishes with your self assignment :).

**Comment by piamancini** [comment]
done
