### ISSUE TITLE
Looks like there is a logo cheater

### ISSUE THREAD

**Issue by ryh** [opencollective/opencollective#782]
Sponsors(organizations) in [gatsby](https://github.com/gatsbyjs/gatsby)  
the 4th one `tipe` took extra large margin spaces than anyone,
its logo 192 X 64 (2 times wider with transparent  background)
compare to `fbopensource`'s 64 X 64
<img width="591" alt="sc 2017-12-24 8 49 56" src="https://user-images.githubusercontent.com/121267/34326604-257a29aa-e8ec-11e7-911a-21272e854587.png">
***

URL: https://github.com/gatsbyjs/gatsby
Logged in as: ryh
Error message if any:
Expected result: No extra large margin spaces 
Browser: Chrome  63.0.3239.90 beta

**Comment by piamancini** [comment]
thanks @ryh us this on desktop? I am seeing it on mobile

**Comment by ryh** [comment]
@piamancini yes, desktop,
 macOS 10.13.2, 
tested again  in Chrome 64.0.3282.119 beta, Safari 11.0.2 (13604.4.7.1.6) , and Firefox 58.0b12

**Comment by ryh** [comment]
those are not margins between images, the image is just that wide, 
they (whoever upload the logo) did it on purpose..

**Comment by piamancini** [comment]
thanks, we'll look at this on Friday. (bug fix day)

**Comment by piamancini** [comment]
Closing as this has been fixed.

**Comment by ryh** [comment]
@piamancini  Still wider than any other on https://opencollective.com/gatsby

**Comment by znarf** [comment]
The one that we were targeting with the fix (tldrnewsletter) was actually way wider than that .

It's possible that we are still accepting proportions like this one (tipe), let's check. cc @xdamman
