### ISSUE TITLE
Translation to French of Get a ticket is not correctly translated in french to Deviens

### ISSUE THREAD

**Issue by JeanPaulGrange** [opencollective/opencollective#784]
Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: https://opencollective.com/reconomycop/events/faircoop-earths-cooperative-ecosystem-for-fair-economy-781ev/order/2989
Logged in as:  jeanpaulgrange
Error message if any: None but we see "Deviens un ticket" which means "Become a ticket" !
Expected result: "Obtiens un ticket"
Browser: Chrome

Attached an screenshot
![2017-12-28 20_03_14-faircoop_ earth s cooperative ecosystem for fair economy - open collective](https://user-images.githubusercontent.com/33667947/34421081-77f19122-ec0d-11e7-8159-d455d24e4ed5.png)

Regards,

**Comment by xdamman** [comment]
That's because you need to set your tier type as `TICKET` instead of `TIER`

**Comment by JeanPaulGrange** [comment]
Hello Nenad,

I saw a wrong french sentence name regarding the tickets you created : It
was written "Become a ticket" instead of "Get a ticket".

The hotline tells that this is due to the type selected was TIER instead of
TICKET.

Amitiés,
Jean-Paul Grange
 www.set94.org - www.val-de-marne-en-transition.org -
www.transitionparisidf.org -  www.transitionfrance.fr


2017-12-29 21:05 GMT+01:00 Xavier Damman <notifications@github.com>:
