### ISSUE TITLE
Tiers that had already been created show blank while editing

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#786]
Hey here on my Foynt collective www.opencollective.com/foynt when editing tiers, the ones I had already created show blank. 

Browser: Safari

![screen shot 2017-12-29 at 5 06 40 pm](https://user-images.githubusercontent.com/30665166/34449136-a78bd048-ecba-11e7-89a7-4b5c686b873b.png)

**Comment by asood123** [comment]
@xdamman can you look into this?

**Comment by xdamman** [comment]
Fixed in https://github.com/opencollective/frontend/pull/182
Deploying now
