### ISSUE TITLE
track trivago's donations and figure out migration to c6

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#792]

**Comment by xdamman** [comment]
We just got another wire from them on January 3.
I've cancelled the recurring transfer to secondary bank account (that was scheduled for every 5th of the month).
Waiting for info on new c6 account to start transferring there.

**Comment by piamancini** [comment]
@xdamman routing details in folder.

**Comment by piamancini** [comment]
payment transferred, closing the issue.
