### ISSUE TITLE
enable admins to download their transaction csv

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#794]
Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by jonschull** [comment]
enable admins to download their transaction csv 
and not just at the end of the month.  

I'd suggest in fact that this be made transparent, obvious and public: e.g., a table with columns showing each fee, then the residual delta for the collective, then the updated balance.

To the beginning of time, and up to date to the present.

With a link for downloading as CSV

**Comment by clarete** [comment]
I started working on this feature today. I have most of the API work done and now I just need to finish up the client.

On the design side, that's what I came up with but it will certainly receive some design improvements:

![oc-task](https://user-images.githubusercontent.com/1459190/35250181-51bbfec6-ffa3-11e7-88ac-0ea958443869.jpg)

**Comment by cuiki** [comment]
Hi @clarete, here is the link for InVision. You can extract the assets in the INSPECT MODE tab at the bottom.
› https://invis.io/5JFHA92DMV2

You don't have to do the full UI of the page. @xdamman already is working on the top part and the collective navigation. I guess you will only need to pay attention to the Download CSV button. The way you solved it with a dropdown to pick the date is fine for now.

**Comment by clarete** [comment]
Here are the changes for both API & Frontend!

https://github.com/opencollective/opencollective-api/pull/1108

https://github.com/opencollective/frontend/pull/215

**Comment by clarete** [comment]
The first version of this is up on prod. To check it out just go to a collective's transaction page and click the link `Download CSV` in the right side of the screen.

Here's an example: https://opencollective.com/babel/transactions

**Comment by xdamman** [comment]
I just downloaded that CSV and it looks like the columns shifted because Host Currency is missing:
![](https://d.pr/i/PeXrsx+)

I don't know if it matters but I was logged in.

**Comment by clarete** [comment]
Thanks for the heads up! I fixed that and than I found another lil bug on the reporting of the collective currency. I'll close this ticket when that's deployed.

**Comment by clarete** [comment]
OK, I'm closing this again since I fixed the bug @xdamman pointed out as well as the other lil mistake I found. Now with some test coverage.

**Comment by jonschull** [comment]
Thanks for doing this!
