### ISSUE TITLE
stop telling the creator of the collective that he was added by him/herself as a member

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#795]
<img width="854" alt="screen shot 2018-01-03 at 6 04 51 pm" src="https://user-images.githubusercontent.com/3671070/34539773-b92089a8-f0b0-11e7-9c94-36707979a101.png">

**Comment by clarete** [comment]
Closing for now. This seems to be closed by commit https://github.com/opencollective/opencollective-api/commit/9ad9c11a92d8daa8900d2526a5816944acf97b09#diff-768438be827d00a869e92ca592010413R668
