### ISSUE TITLE
Approve/Reject buttons visible after approving REconomy

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#798]
Nenad from https://opencollective.com/reconomycop/ collective is having trouble again with the approve/reject buttons showing even after approving an expense. 

He also says that the available balance is not updating/reflecting the real amount. They are having problems to make the expenses as paid, that's the end result.

**Comment by xdamman** [comment]
For 15mn you can still reject the expense. It's meant in case people have approved an expense by mistake.

**Comment by xdamman** [comment]
Can someone try to reproduce this on staging?
Don't have the time to look at it now.

**Comment by piamancini** [comment]
you can see it live. he's been waiting on this for a while. It's this same error https://github.com/opencollective/opencollective/issues/727

**Comment by asood123** [comment]
What's the update on this @xdamman ? It's marked high-priority.

**Comment by xdamman** [comment]
I've updated the #727 issue. Cannot reproduce. It's probably not clear for this user that "approved" doesn't mean that it has been paid.

Closing this one to avoid duplicated.
