### ISSUE TITLE
subscription link in mochaJS thankyou email broken

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#80]
there is an error in the link to subscriptions in the thank you email in MochaJS (might be in all thank you emails tho) 

The link received in the email is the wrong token

The email were it happened is in transaction ID542

**Comment by piamancini** [comment]
user tried to log in through the link and it's still not working, it's not a problem in the mail. the token is not working

**Comment by asood123** [comment]
fix here: https://github.com/OpenCollective/website/pull/221. Will be merged and pushed shortly.
