### ISSUE TITLE
Move subscriptions to main platform account

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#801]
Currently, we attach Subscriptions to an individual connected account. This has some downsides:

- Each account has its own rules on how to handle unpaid/cancelled subscriptions (like some accounts can mark subscriptions as "unpaid", while others "cancel" subscription, some can do it immediately and others can take a week)
- Each account dictates it's own fraud rules (like some can require zip code and some can even ignore CVC)
- Future changes to connected accounts (like fees not refunded) will create a lot of edge cases

A more consistent experience would be to attach a subscription to our main account and then transfer funds to appropriate collective accounts. Stripe has a [Transfer API](https://stripe.com/docs/connect/charges-transfers) that lets you charge and then move money afterwards for that Charge. Benefits of this:

- No need for future migrations, simply update stripe account in our database and you are done
- Consistent and reliable (and in our control) refund fees, subscription cancellation policies, etc
- Simpler customer and email management: only one account to manage
- Ability to combine payments across hosts (Joe's payments to all collectives can be charged once and transferred to each collective separately)
- Cheaper stripe fees (since all coming from same accounts vs currently it'll be measured per connected account)

And goes without saying that it would be even better if we didn't create subscriptions on stripe and only stored them on our own servers. On 1st of the month, we can charge all outstanding subscriptions, handle failed payments via email, etc.

**Comment by asood123** [comment]
That's a good point, worth digging into money transmitter issues

**Comment by piamancini** [comment]
what's the status of this in the context of self-serve flow and a growth in the number of hosts?
