### ISSUE TITLE
Inconsistent name: use "Open Collective" instead of "OpenCollective" everywhere

### ISSUE THREAD

**Issue by bradvogel** [opencollective/opencollective#802]
Throughout the site I see inconsistent spacing in the name: "Open Collective" vs "OpenCollective" - which is it?

**Comment by asood123** [comment]
It should be two words everywhere. We went back and forth in the beginning and then maybe haven't changed them all. Thanks for pointing out and feel free to submit PRs to change them.

**Comment by dahacouk** [comment]
At least fix:

- [ ]  Homepage title https://opencollective.com
- [ ]  Twitter name https://twitter.com/opencollect
- [ ]  Cruchbase https://www.crunchbase.com/organization/opencollective
- [ ]  Facebook page name https://www.facebook.com/BeOpenCollective

Cheers!
