### ISSUE TITLE
paypal email shows as missing

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#803]
user enters email address, submits expense, paypal shows missing 
![opencollective-weird](https://user-images.githubusercontent.com/3671070/34611076-c639186e-f202-11e7-884b-114af9a410de.gif)

From user: "once I submit, you have to click to open a new expense, and that one _is_ blank"

![screen shot 2018-01-04 at 10 28 05 am](https://user-images.githubusercontent.com/3671070/34611098-dd1853ec-f202-11e7-8f10-b3d5a0dd0489.png)

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by asood123** [comment]
This will be fixed with: https://github.com/opencollective/frontend/pull/190/files

@xdamman it's an issue of order of evaluation of logical statement: https://github.com/opencollective/frontend/pull/190/files#diff-c8e809519d50f7259f77a09398bc30f7R248 (note the parenthesis)

**Comment by FadySamirSadek** [comment]
This has just happened to me
