### ISSUE TITLE
Unable to pay expenses. Paypal buttons still greyed out. 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#806]
this is blocking me from paying expenses and adding funds 

Paypal buttons are grey
Add funds servers an error 

<img width="1244" alt="screen shot 2018-01-05 at 1 17 48 pm" src="https://user-images.githubusercontent.com/3671070/34617666-f5cb00b6-f21a-11e7-9b2e-a487cb612d1b.png">
<img width="1137" alt="screen shot 2018-01-05 at 12 22 49 pm" src="https://user-images.githubusercontent.com/3671070/34617696-0d7c3342-f21b-11e7-80c7-17e4f5abac58.png">

**Comment by piamancini** [comment]
Paypal buttons are still greyed out. I am changing the subject of this issue because it seems like the problem is not the open collective payment method 

<img width="1276" alt="screen shot 2018-01-08 at 10 40 22 am" src="https://user-images.githubusercontent.com/3671070/34673339-a8ccf6a0-f460-11e7-9c49-b833e9ff2e1e.png">

**Comment by asood123** [comment]
Partial fix here: https://github.com/opencollective/frontend/pull/190
