### ISSUE TITLE
wwcode is not loading the notation matching fund

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#807]
https://opencollective.com/wwcodeportland/donate
https://opencollective.com/wwcodetwincities/donate?referral=undefined

**Comment by pamelawoodbrowne** [comment]
Looks like the same issue is happening with our collective: https://opencollective.com/wwcodegreenville

**Comment by piamancini** [comment]
this is still not loading for me when I do https://opencollective.com/wwcodeportland and click on 'donate'. I am directed here: https://opencollective.com/wwcodeportland/donate and no matching fund. 
<img width="1263" alt="screen shot 2018-01-08 at 11 37 47 am" src="https://user-images.githubusercontent.com/3671070/34675455-74fcddce-f468-11e7-8b27-127bb7ab2ba3.png">

**Comment by xdamman** [comment]
It was indeed missing for portland collective but it's working for me on all the others I could test.

**Comment by piamancini** [comment]
ok closing then
