### ISSUE TITLE
discrepancy in tiered sponsors in cards and on tiers

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#808]
Amp should be a gold sponsor and it is correctly categorized in the cards in https://opencollective.com/babel#organizations However on the tiers on the side bar it is in silver sponsor one.
Webflow has no tier in the #organizations and is a silver sponsor in the side bar

<img width="933" alt="screen shot 2018-01-08 at 11 51 22 am" src="https://user-images.githubusercontent.com/3671070/34676539-ef17ce0e-f46b-11e7-9e8d-3424db5e12d8.png">

Webflow has no tier in the #organizations and is a silver sponsor in the side bar 
![img_0732](https://user-images.githubusercontent.com/3671070/34676532-e7bcc16e-f46b-11e7-80f1-b5bf7db92552.jpg)

**Comment by piamancini** [comment]
Another issue here: Both [mixmax](https://opencollective.com/mixmax) and Kent. C Dodds made a $100 contribution which is a sponsor, but they are both assigned to the wrong tier (the module tier)
https://opencollective.com/rollup

**Comment by piamancini** [comment]
manually put both users on the correct sponsor tier. They show up correctly on the side bar but the name on the Sponsor's card still is the old tier. @xdamman Where in postico I need to update it so the card reads sponsor (already updated the Order table)

<img width="915" alt="screen shot 2018-01-12 at 4 09 48 pm" src="https://user-images.githubusercontent.com/3671070/34891151-34de94dc-f7b3-11e7-986b-57f05d580765.png">

**Comment by xdamman** [comment]
Amp has been fixed a while ago: ![](https://d.pr/free/i/iuLw13+)

Just fixed mixmax card on Rollup.

You need to update the `TierId` both in the `Members` table and in the `Orders` table.
