### ISSUE TITLE
Launch mvp to signup through Github

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#81]
Flow:
- User visits opencollective.com
- Clicks on "Apply" and navigates to github/apply (scaffolding already built by @carlosascari)
- Initiates a 4 step flow (discussion here: https://github.com/OpenCollective/OpenCollective/issues/33)
  1. Connect github account
  2. Select repos (we'll only show repos >100 stars)
  3. Select core contributors (at least 2)
  4. Answer questions
- Show thank you screen
- Send email confirmation to all core contributors

Note this excludes creating a dummy collective with 10 empty slots to fill and gating on 10 donations before launching. We'll get to that once this launches.

Based on this flow, here is what needs to happen:

- [x] Move passport flow to the backend (`api` and `website` to remove passport from `website`) [@sedubois] 
- [x] Add a prominent image and link on opencollective.com to go to github.com/apply (`website-static`) 
- [x] Link up /github/apply to go through oauth flow that @sedubois already built (`website`) [@asood123]
- [x] Pull necessary information from github (repos, number of stars, core contributors, etc) for rest of the apply flow (`website`) [@asood123]
- [x] Link up data fetched from Github to show repos and contributors (`website`)
- [x] Create collectives for selected repo (disable the collective somehow: flag in settings or mark them deletedAt) (`website` and maybe `api`)
- [x] Create users for contributors listed (`website`)
- [x] Add two questions on the "Answer Questions" step and add Thank you step (`website`) [@carlosascari]
- [x] Create new email templates and send to all contributors (`api`)

Pls add if anything is missed. Put your name by whatever you are going to pick up.

**Comment by erickrico** [comment]
here it is, the quick fix for the open-source projects on-boarding flow, im going to be working on a new main cta for the home page
![apply-opensource](https://cloud.githubusercontent.com/assets/18429104/15434699/d3bf3eb4-1e7d-11e6-8815-c1df4340929d.png)

**Comment by asood123** [comment]
I like it. Let's implement it to be taken live on Monday.

**Comment by carlosascari** [comment]
I'll implement it today

**Comment by piamancini** [comment]
me too, good work!

**Comment by erickrico** [comment]
hey, im having trouble coming out with good words for the home page, can you help me out this is what i have so far 
![cta](https://cloud.githubusercontent.com/assets/18429104/15437537/3bac618c-1e8d-11e6-83b4-d133143be71f.png)

**Comment by piamancini** [comment]
How do you feel about: 
Open Collective, Fund your Open Source Project,

**Comment by xdamman** [comment]
This looks terrific! Very very good job!

A few comments:

- [ ] We should skip step 1, the button "let's do this" should be directly "Connect your Github account"
- [ ] 2/4: we should add "only repositories with at least 100 stars and 2 contributors are eligible"
- [ ] 2/4: if there is only one, select it by default
- [ ] 3/4: just the username isn't helping me finding the core contributors, I'd also show the number of commits or something
- [ ] 3/4: even though it says "Add at least 2 contributors", I was able to continue with only one selected
- [ ] 4/4: the collective image should be "logo" and the default shouldn't be the default avatars.

**Comment by carlosascari** [comment]
@xdamman During development, you can continue to the next step by selection zero contributors, here: https://github.com/OpenCollective/opencollective-website/blob/master/frontend/src/constants/github.js#L13

I'll take care of the other fixes

**Comment by erickrico** [comment]
hey, what do you think about this ? 
![apply home onboarding](https://cloud.githubusercontent.com/assets/18429104/15478415/b2b14a6e-20df-11e6-88d1-bf1f9434db51.png)

**Comment by piamancini** [comment]
Hi! I think we don't need the '-' in open source. Otherwise, I think is great, simple and clean.

**Comment by asood123** [comment]
Moar bugz:

- [ ] avatar not added for the owner of the collective (like it is for the contributors)
- [ ] try to get contributor's emails as well (if they are public)
- [ ] bug where removing contributors below the threshold still leaves the `continue` button enabled
- [ ] add messaging underneath `continue` button to say "You need to select at least two contributors" and remove from the subheading

**Comment by piamancini** [comment]
Things that are not bugs but nice to have for the github integration: 
- [ ] add description about their project. 
- [ ] logo
- [ ] image for the Why Join, it looks pretty bad when there is no image

**Comment by carlosascari** [comment]
@piamancini [javierbyte](https://github.com/javierbyte) mentioned a neat idea where github projects can include a JSON like `package.json`, say we call it: `repo.json`. 

There, the metadata that represents the repository, is displayed in the repo's collective page, like logo url and short/long descriptions, etc. I think the coolest part of this, is that they (the developers) can edit the repo.json file, freely and the most up to date logo/metadata will always be displayed, without having to edit it manually everytime there is a change.

Javier is working on a draft for this. What do you think?

**Comment by asood123** [comment]
That's interesting. We can fetch it periodically and update the database to serve the pages.

**Comment by piamancini** [comment]
Yeah it could definitely make our onboarding easier!

**Comment by erickrico** [comment]
@piamancini for the nice to have things
- the long description of the project will have to be added to the pending collective view
- the logo of the collective, we do ask for it in the last step
- image for the why join, this is the placeholder i propose 
![screenshot 2016-05-26 16 24 14](https://cloud.githubusercontent.com/assets/18429104/15590650/61809dee-235e-11e6-87e8-844ca5cb97bf.png)
![place holder](https://cloud.githubusercontent.com/assets/18429104/15590654/63b3bd80-235e-11e6-9057-512627abb973.png)

**Comment by piamancini** [comment]
lgtm!

**Comment by carlosascari** [comment]
@asood123 @piamancini 
I  want to be clear, currently when the user does not have a image or video for the whyjoin section, it collapses and centers the summary information.

Here it is (with Ericks placeholder as a background)
![Collapsed](http://i.imgur.com/MN0N5yy.png?1)

Should I go ahead and remove the collapse logic, and replace it with a default placeholder as shown in Erick's example above?

**Comment by piamancini** [comment]
@carlosascari what do you think?

**Comment by xdamman** [comment]
I like the idea of configuring the collective from a file on the repo. But then I'd take the opportunity to have something branded such as COLLECTIVE.md (if we want something that can be seen on Github) or collective.json if we need more machine readable. But in the latter, I'd rather add some options to the existing package.json instead of cluttering the repo with another file at the root.

**Comment by carlosascari** [comment]
@piamancini I wanted a confirmation, to go ahead since I did not write the collapse code, I didn't want to step on anyones shoe, I think it looks better the way Erick designed it

**Comment by asood123** [comment]
Isn't package.json only for node js projects? COLLECTIVE.MD sounds better to me.

**Comment by ScottFreeCode** [comment]
I think project metadata and branding resources would be helpful stored somewhere that makes it obviously useable not only by Open Collective but by any host (e.g. GitHub itself) or integration that wants it. Maybe a project.json/.project.yml file? Or maybe added to package.json if that's feasible -- I also wish fewer services needed their own files instead of figuring out ways to share them, but I guess that comes down in part to whether the data is actually shareable.

**Comment by carlosascari** [comment]
@asood123 We are fetching 30 repos at a time, that seems to be the default. I've sent a PR https://github.com/OpenCollective/opencollective-website/pull/268

Now 100 repos will be fetched, order from highest star count to least, it should cover most cases

For those who have over 100 repositories with 100 or more stars each (know of anyone?), we'll need to set-up pagination. What do you think?

**Comment by asood123** [comment]
That's fine for now

**Comment by asood123** [comment]
Since this is launched, closing this issue. Please file separate bugs for new issues.
