### ISSUE TITLE
Expense got "paid out" twice in Transactions

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#817]
Expense id 1913 for $597 is listed twice in the Transactions table, similar to the issue we saw a couple of weeks ago. This time it's payment method 'other'.

**Comment by piamancini** [comment]
I did that yesterday.
The expense was showed as RECORD AS PAID on the interface, not PAID...
We should reverse that. don't know why it wasn't properly recorded.

**Comment by asood123** [comment]
It's worth looking at the expense history ... weirdness going on there.

**Comment by asood123** [comment]
I marked the duplicate transaction rows as 'deletedAt'.
