### ISSUE TITLE
floating footer keeps happening on windows

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#818]
![floating_footer](https://user-images.githubusercontent.com/3671070/34782620-129e9b8a-f608-11e7-9394-e5fb0ba27e87.JPG)

it keeps coming back for unknown reason and then works fine for a while and that it's back again...
Right now only on our Open Collective page, on event pages is where footer should be. 

Browser: Chrome, Windows 7, no ad blockers, works ok in incognito window.

**Comment by asood123** [comment]
Can you share a specific url where you are seeing this? Also, a screenshot or listing of your chrome extensions will help.

**Comment by piamancini** [comment]
this extension was breaking it https://chrome.google.com/webstore/detail/stayfocusd/laankejkbhbdhmipfmgcngdelahlfoji?hl=en
