### ISSUE TITLE
Application link for a collective to a host does not seem to work

### ISSUE THREAD

**Issue by tgoorden** [opencollective/opencollective#820]
Following the instruction on the wiki, this URL should allow us to set up new "collectives" under a hosting organisation:
https://opencollective.com/burgerbewegingvzw/apply

See documentation here:
https://github.com/opencollective/opencollective/wiki/Becoming-a-Host#set-up-your-host

Instead, the error "Not Found" is displayed.

<img width="568" alt="opencollective bug" src="https://user-images.githubusercontent.com/2543154/34798029-b4725364-f65a-11e7-9362-2224c147884f.png">

**Comment by xdamman** [comment]
We need to flip a switch on our side. I've just done it.
We should update the documentation. Thanks for pointing that out.

**Comment by xdamman** [comment]
Just updated that wiki page 
https://github.com/opencollective/opencollective/wiki/Becoming-a-Host#set-up-your-host
