### ISSUE TITLE
paypal address missing on a new expenses (filed 1/5)

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#824]
<img width="997" alt="screen shot 2018-01-12 at 10 46 49 am" src="https://user-images.githubusercontent.com/3671070/34877733-03fdbffa-f786-11e7-9402-01226e9a3580.png">

**Comment by asood123** [comment]
This may be an issue of timing. If you see another instance of an expense created after 1/11 (jan 11th), please reopen.
