### ISSUE TITLE
Invoices are serving 404

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#825]
https://opencollective.com/opensource/transactions/e9357af3-1e0e-48a2-80c8-0153bdc75a67/invoice.pdf
probably because we changed the URL?

actually no, I am trying to generate one for a user and it's failing also https://opencollective.com/webpack/transactions/7c609c7d-2195-44f5-bde1-7b5b998b6277/invoice.pdf

**Comment by xdamman** [comment]
Fixed
