### ISSUE TITLE
Submit expense takes too long to load

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#834]
Martin reports having trouble sometimes when submitting an expense to: https://opencollective.com/hybris-integration-intellij-idea-plugin/expenses/new, he says it takes too long to load, and sometimes it works, sometimes it doesn't.

> Paypal email field address disappears and my email field get blank. The submit button gets disabled.

Using chrome and safari on MacOSX High Sierra

![unnamed](https://user-images.githubusercontent.com/30665166/34969487-972efae0-fa34-11e7-8ee9-b69b89081c8c.png)

Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: 
Logged in as: (just provide your username or the url of your profile)
Error message if any:
Expected result: 
Browser:

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by xdamman** [comment]
Please only use the high priority if widespread issue and/or if you could reproduce it.

**Comment by asood123** [comment]
Can't repro, pls reopen if you hear another report
