### ISSUE TITLE
Setup flexible tiers for Oni collective

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#838]
Bryan would like to consolidate the Backers tiers into flexible tiers, with the following amounts: 
$2, $5, $10, $25, $50

**Comment by bryphe** [comment]
Thank you @nicobarretoOC for opening the issue for me! @xdamman actually took care of adding the flexible 'Backer' tier for us already.

There are two minor tweaks I was wondering if we could get for our flexible backer tier:
- Add a $50 tier
- Change the text in the Backer tier to "Become a Backer and help us sustain our activities!"

Thanks again!

**Comment by xdamman** [comment]
Done.

Note: you can edit the description yourself via the interface.

**Comment by bryphe** [comment]
> Note: you can edit the description yourself via the interface.

Ah, apologies - I thought it was special because of the flexible tiers. I see it's all set now. Thank you!
