### ISSUE TITLE
Default image is obscuring our logo

### ISSUE THREAD

**Issue by phated** [opencollective/opencollective#842]
Not sure when this happened.  Screenshot attached.  Happening on latest Chrome for the gulp collective.
<img width="277" alt="screen shot 2018-01-18 at 4 32 15 pm" src="https://user-images.githubusercontent.com/992373/35127052-76c43564-fc6d-11e7-9626-be5b265abe10.png">

cc @piamancini @xdamman

**Comment by xdamman** [comment]
Thanks for the heads up. Looking into this now.
