### ISSUE TITLE
Only one OC shows up under host, despite mention of 3 elsewhere 

### ISSUE THREAD

**Issue by Kilheure** [opencollective/opencollective#845]
Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: www.opencollective.com/uk
Logged in as: none
Error message if any: none
Expected result: Expected to see 3 collectives under the host (opencollective UK), but there is only one
Browser: Chrome

Bonus point if you can add a screenshot :-)
![screen shot 2018-01-21 at 18 52 36](https://user-images.githubusercontent.com/31570464/35197761-61032c46-fedc-11e7-954e-8c6c10f95519.png)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by xdamman** [comment]
Fixed
