### ISSUE TITLE
Become a sponsor link is broken

### ISSUE THREAD

**Issue by koistya** [OpenCollective/OpenCollective#85]
![image](https://cloud.githubusercontent.com/assets/197134/15299508/5ef81ef2-1bad-11e6-8774-fe83de50b662.png)

When you click on this button in a project's `README.md` file, it redirects to `Not found` page.

**Comment by piamancini** [comment]
@xdamman is also happening in the become a backer one. it links to the placeholder but not the collective.

**Comment by asood123** [comment]
This is emabarrassing, so marking high-priority

**Comment by xdamman** [comment]
Ah good catch thanks for reporting.  

I don't have a computer near me but the fix is trivial. We should just change the `>=` into a `>` at the bottom of `website/server/controllers/banner.js` (in the `redirect` method)

    if (position >= users.length) {
      return res.sendStatus(404);
    }

**Comment by sedubois** [comment]
Fixed by https://github.com/OpenCollective/opencollective-website/pull/237

**Comment by sedubois** [comment]
New fix: https://github.com/OpenCollective/opencollective-website/pull/238

**Comment by piamancini** [comment]
we should update the lates fix it in the wiki.

**Comment by asood123** [comment]
finally fixed in https://github.com/OpenCollective/opencollective-website/pull/242. Tricky little bug.
