### ISSUE TITLE
Backer received approve payment email

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#855]
**Slack from Loois:**

> Hello, I'd like to submit an expense to our collective https://opencollective.com/lajacqueline (host is BrusselsTogether) for our monthly workshop rent > should we ask the owner to submit an invoice to 
> Jacqueline Soundsystems
> (...)
> 
> after submitting an expense, a backer received an email to approve it, although this user is not an administrator of the collective... how is that possible? :confused: @xdamman  Thank you

**Comment by xdamman** [comment]
For some reason that user that was a backer was subscribed to the `collective.expense.created` notification (I fixed it). That said, since this user was not an admin, the button wouldn't have let him approve or reject the expense.
