### ISSUE TITLE
Assist Hoverboard Collective with flexible tiers

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#856]
User Ozasadnyy on slack is requesting to have the option of flexible contributors like the ones on Webpack on this collective:
https://opencollective.com/hoverboard/
![image](https://user-images.githubusercontent.com/30665166/35313475-24ec69ce-0086-11e8-9aeb-da9dd6880083.png)

**Comment by xdamman** [comment]
This feature is now live ![](https://d.pr/i/qLa4sk+)
