### ISSUE TITLE
Add input field names on the Login page

### ISSUE THREAD

**Issue by koistya** [OpenCollective/OpenCollective#86]
The input fields on the login page must have names, e.g. `<input name="email" />`. Otherwise, password managers may not work correctly with this login form.

![image](https://cloud.githubusercontent.com/assets/197134/15315573/163a52ba-1c21-11e6-9b37-d83e9bb17a86.png)

**Comment by asood123** [comment]
Fix here: https://github.com/OpenCollective/opencollective-app/pull/180. Thanks for reporting!
