### ISSUE TITLE
Need design for a subscription/Subscription page

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#861]
We are moving /subscriptions to new frontend and adding some additional features to it. Currently looks like this:

![screenshot 2018-01-25 18 17 22](https://user-images.githubusercontent.com/6106941/35417576-067b8c3c-01fc-11e8-8ea7-03cebf115bd4.png)
![screenshot 2018-01-25 18 17 30](https://user-images.githubusercontent.com/6106941/35417577-083505a8-01fc-11e8-820a-feec6f1a5dc2.png)

It would be nice to reuse the collective card that we use on /redeem page for example, so there is some consistency in how we display a collective.

We need to show the following data for each subscription:
- Collective name (like Webpack)
- Collective description (one liner at most)
- Collective logo (and possibly background image)
- Currency + Amount
- Frequency (either monthly or annually)
- Payment method (only when you are logged in). Credit card type, last 4 and expiry. (VISA ****0198 Expires 01/2020)
   - Link to update or change the credit card
      - it should change into a dropdown that lists all of a user's credit cards
      - Last option on the dropdown is to "Add New Card"
      - Adding new card can show the same field that we currently show on order page
- Status
   - Active
   - Past_due (need to highlight this. We'll sending out emails to let them know about this)
   - Cancelled
- Transactions
   - See the expanded view in screenshot above.
   - They should be able to see all the transactions and get the invoice.
- Would be cool to show "Contributed to date". So, a $10/month subscription for 6 months would show $60. (maybe we can get this in the collective card instead)
- Actions:
   - Cancel
   - Update Payment Method
   - (and eventually) Update amount

Likely we'll sort the page to show the Active subs at the top and then a section below for "Cancelled".

@cuiki working on this now, any design input much appreciated.

**Comment by piamancini** [comment]
also https://github.com/opencollective/opencollective/issues/793

**Comment by cuiki** [comment]
Hi Aseem, here is the design for the Subscriptions page. To be able to reuse the collective card, I thought that a grid is a better layout to show the subscriptions.

https://invis.io/UQF0FK26S#/276427449_M_--_User_-_Subscriptions

In order to go and extract the assets and code, you need an InVision account. To which email should I invite you to the project?

**Comment by asood123** [comment]
@cuiki making progress. Few questions/comments

- Putting dot menu on top right is a little tricky (the way components are built). It would be much easier to put the action below the payment method. But, it looks annoying to have those buttons on each card. :/ Thoughts? When we add ability to change amount, we could add a pencil icon next to the amount in the center? So it's only about changing payment methods.
- Need an icon for help - we won't be able to show many payment methods (see screenshot)
- Lastly, we use Stripe elements and while I could split the credit card into multiple fields, it would be *a lot* easier to reuse the current form. See the [credit card form](https://opencollective.com/mochajs/order/965)  (when you are logged out or select 'add card'). Unfortunately, the width is too small to make that form field fit.

![screenshot 2018-02-01 17 30 10](https://user-images.githubusercontent.com/6106941/35707240-fb40d194-0776-11e8-9d85-5a5423fdfde6.png)
![screenshot 2018-02-01 17 30 17](https://user-images.githubusercontent.com/6106941/35707241-fb57efa0-0776-11e8-940e-6e805992c110.png)
![screenshot 2018-02-01 17 38 26](https://user-images.githubusercontent.com/6106941/35707242-fb620ac6-0776-11e8-9d91-bba2b950ce01.png)
![screenshot 2018-02-01 17 38 31](https://user-images.githubusercontent.com/6106941/35707243-fb739a0c-0776-11e8-8dfe-606bbfd10526.png)
![screenshot 2018-02-01 17 39 13](https://user-images.githubusercontent.com/6106941/35707244-fb7cbda8-0776-11e8-885d-b7320ca7a709.png)

**Comment by asood123** [comment]
Ignore the dropdown that pops up for selecting credit cards - that's still work in progress.

**Comment by cuiki** [comment]
Ok, I'll take a stab at the CC entry.

**Comment by asood123** [comment]
Making progress... still have some rough edges, took some liberty on the payment method flow :).

**default state - not logged in**
![screenshot 2018-02-09 16 27 24](https://user-images.githubusercontent.com/6106941/36050865-258ff796-0db6-11e8-9726-3a048627a00a.png)

**default state - logged in**
![screenshot 2018-02-09 16 18 14](https://user-images.githubusercontent.com/6106941/36050727-ab374c56-0db5-11e8-9bd8-63847b6f308c.png)

**actions**
![screenshot 2018-02-09 16 28 22](https://user-images.githubusercontent.com/6106941/36050891-42e307de-0db6-11e8-8bbf-1f2d0a391723.png)

**cancel subscription**
![screenshot 2018-02-09 16 18 27](https://user-images.githubusercontent.com/6106941/36050730-ade15186-0db5-11e8-87fa-461443041d71.png)

**change payment method**
![screenshot 2018-02-09 16 18 42](https://user-images.githubusercontent.com/6106941/36050732-b0efbce6-0db5-11e8-8c35-8c2fd0df2f01.png)
![screenshot 2018-02-09 16 24 47](https://user-images.githubusercontent.com/6106941/36050818-f9652aa6-0db5-11e8-89be-e8613ece5e7d.png)
![screenshot 2018-02-09 16 19 13](https://user-images.githubusercontent.com/6106941/36050828-ff7b349e-0db5-11e8-91d6-c4da1e2fc42e.png)

**Comment by cuiki** [comment]
Hi @asood123 

Here is a state that you can use. I still need to come up with a whole system for this, but meanwhile this can work. I did two views:

1. A user viewing their own page: https://invis.io/TSFWNQD5DWH
2. A user viewing someone else's page: https://invis.io/HKFWNR3P26X

The only change is in the copywrite. Maybe what the text for a visitor says isn't something we can do right now, but it could be cool.

**Comment by asood123** [comment]
@cuiki next up on my list is to allow changing an amount. Do you have any ideas on the UI flow for it? I'll add the action in the dropdown. Should we make the center amount editable somehow?

**Comment by asood123** [comment]
@cuiki any update?

**Comment by cuiki** [comment]
<img width="1593" alt="screen shot 2018-04-07 at 8 33 44 am" src="https://user-images.githubusercontent.com/981188/38454941-702c6474-3a3e-11e8-8518-c6c603e2942e.png">
