### ISSUE TITLE
3 ticket issues when creating event on OC

### ISSUE THREAD

**Issue by Kilheure** [opencollective/opencollective#866]
Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: https://opencollective.com/opencollective/events/a-new-way-of-sustaining-open-source-and-civic-tech-projects-811ev/#tickets
Logged in as: me (dimitri)
Error message if any: None
Expected result: I should be able to create ticket in (1) GBP, currently only in USD. (2) when I create ticket it cannot be free, minimum amount is 0.01 . (3) when I click on ticket, I am redirected to the bottom of the page, but I don't see any option to confirm the registration and buy ticket
![screen shot 2018-01-27 at 21 25 45](https://user-images.githubusercontent.com/31570464/35476496-d1d4e6a0-03a8-11e8-9a34-b14e2e4826d0.png)

Browser: Chrome

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by piamancini** [comment]
@Kilheure is this still happening?

**Comment by Kilheure** [comment]
As of yesterday: yes
Issue can be reduce to: 
Add possibility to enter 0 GBP for free tickets. Not providing any amount is so confusing

**Comment by piamancini** [comment]
closing this @Kilheure let us know if you still have issues.
