### ISSUE TITLE
[bug] Platform prevents saving of tier config data when all tiers are removed

### ISSUE THREAD

**Issue by patcon** [opencollective/opencollective#867]
Thanks for much for all the improvements since I was last testing several months ago! Here's my bug report:

------

As a collective administrator using a "dummy host" with no bank account attached, I am trying to track my organizations expenses manually using the platform. For this reason, I would like to remove all tiers.

When I try to remove all tiers from https://opencollective.com/civictechto/edit#tiers, I get an initial success message, but then when I refresh, all tiers are back, and no data was saved. At first, I still had the default  two tiers. But if I removed one of the two tiers and clicked save, that change "stuck" and I had just one tier. But removing that one tier is again impossible, with same observed behavior.

So it seems that the save action so that no tiers are present, the platform fails to record that.

***

URL: https://opencollective.com/civictechto
Logged in as: patcon
Error message if any:
Expected result: 
Browser: FF Quantum 57.0.4 (Ubuntu)

Bonus point if you can add a screenshot :-)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by patcon** [comment]
fwiw, the POST request without any tiers completely removes the `tiers` array from the graphQL `variables` hash. Seems related. Will check out client

**Comment by patcon** [comment]
Yep, seems that using FF's ability to edit the request and resend -- replacing the tiers array with an empty one -- allowed me to remove all tiers. So it's that the front-end is stripping out empty arrays somewhere in the data

**Comment by piamancini** [comment]
yes, this makes sense since we have default tiers. 
the buttons should be grey though, since you don't have a host (or a stripe connected to a host)
that should achieve the goal of preventing someone to donate.

**Comment by patcon** [comment]
Hm. Cannot speak to whether they were grey when present.

But what if I am using OC to manually track finances, and so expect no contributions through OC page. Then I would want to remove all tiers. That is currently impossible through the UI.

(Restating more concisely: manually crafting a POST request allowed me to remove all tiers. See https://opencollective.com/civictechto)

**Comment by piamancini** [comment]
@patcon this should be fixed now.
