### ISSUE TITLE
Allow anonymous expenses to be disabled

### ISSUE THREAD

**Issue by patcon** [opencollective/opencollective#868]
Seems that people who aren't signed in can file expenses.

It would be rad if we could set a per-collective/host toggle so that when not logged in, the expense page redirects users to the account creation form.

Would this be a feature that would be welcome?

**Comment by piamancini** [comment]
hey @patcon anyone can submit an expense. We create a user for them when they do.

**Comment by patcon** [comment]
Ok, that's nifty! Didn't realize that.

Does it align with your team's thinking that some Collectives might want to encourage account creation process first? That might make public transactions/expenses more meaningful.

I am curious whether a more traditional sign-up process might allow users submitting expenses to recognize that an account has been created for them, and so they're more likely to treat their account like others they create -- populating it with info: avatar, name, etc.

Currently, the group organizer who submitted an expense didn't realize she was creating an account, and so she wouldn't add any details.

Happy to just close this issue and treat our experience as a bit of "hallway testing" though -- doesn't need to be actionable.

**Comment by piamancini** [comment]
Closing as this issue has been fixed.
