### ISSUE TITLE
Notification email to Collective for recurring subscriptions

### ISSUE THREAD

**Issue by phated** [opencollective/opencollective#879]
I just checked the gulpjs collective and noticed that a bunch of recurring donations occurred on Feb 1st but I received no emails about them.  Is this bugged?

**Comment by xdamman** [comment]
Oh, we switched to only sending emails for new backers to not flood your inbox. Are you interested to get individual emails for every single transaction?

**Comment by phated** [comment]
Yes, that way I can decide to thank certain sponsors specifically (say, over $100, etc).

**Comment by phated** [comment]
@xdamman Another reason I need to see the emails is because to keep notified on who is subscribed to our recurring t-shirt tier and needs to be contacted about shipment information.  I have too much to keep track of already to remember to check our collective page each month.
