### ISSUE TITLE
user is getting json error when creating a collective

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#880]
from opencollective.com/apply 
choosing 'movement' 'open source' or 'other' 
browsers 
firefox 58.0.1 (64-bit) 
Chrome
![error_mesg](https://user-images.githubusercontent.com/3671070/35776303-dfbb580a-0991-11e8-9fc9-cb1e1cfdd4ae.png)
![error_mesg2](https://user-images.githubusercontent.com/3671070/35776335-3f051f30-0992-11e8-81a3-cd20b3efdbdb.png)

**Comment by asood123** [comment]
it's fixed, closing
