### ISSUE TITLE
Support importing donations from other platforms

### ISSUE THREAD

**Issue by alexweissman** [opencollective/opencollective#882]
It would make it a lot more appealing for communities to transition to OC from other donation platforms (Patreon, Pledgie, etc), if we could import our donor lists from those platforms.  

As it stands, we are basically making the decision to start over when we move ourselves to Open Collective. It would be better if we could build on our momentum from legacy platforms by importing those donors and transactions (and probably legacy expenses as well).

I realize that this would probably require substantial changes to the data model, such as decoupling donation records from the internal accounting system. So, it's more of thing to keep in mind during a major refactor rather than a quick fix.  However, this would make OC much more flexible and more appealing to those who have been using another platform up until now.

**Comment by xdamman** [comment]
Thanks for writing this. I agree. But yes indeed it's a big refactor :-/ 

The way to do it now is to transfer funds to the host and ask them to allocate them to your collective on behalf of a user/organization. Doesn't scale very well and it implies that you haven't spent the money yet.
