### ISSUE TITLE
Design Bug → Lack of clarity around how much a user is donating to an OC

### ISSUE THREAD

**Issue by devinbalkind** [opencollective/opencollective#883]
Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: https://opencollective.com/oscurrency/donate
Logged in as: https://opencollective.com/devinbalkind
Error message if any: NA
Expected result: Knowing how much I'm donating
Browser: Firefox

Bonus point if you can add a screenshot :-)
![screenshot from 2018-02-04 15-59-03](https://user-images.githubusercontent.com/444311/35823295-0c9279ee-0a7d-11e8-9ad6-f4d82b79acbd.png)

My issue is the lack of clarity around how much I'll be donating to an OC.

If I click on the suggested amounts 10/50/100 then there is a faint highlight. If I then add my own amount, then it isn't clear that the custom amount is actually what I'll be donating unless I read the fine print on the bottom. 

If, for example, I click between suggest and custom amounts a few times, there isn't a strong indicator (design wise) which amount is the selected one. 

I suggest having a strong design cue showing the user which amount they're giving - a brightly colored outline of the current amount or a background or largest "You've Selected $XYZ" would all work.

Thanks.

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by znarf** [comment]
@cuiki good to have that in mind while working on the contribution flow.

**Comment by piamancini** [comment]
This is still an issue.

**Comment by Betree** [comment]
Solved with the new contribution flow, especially now that we've merged https://github.com/opencollective/opencollective-frontend/pull/3026

![Peek 12-12-2019 16-09](https://user-images.githubusercontent.com/1556356/70723861-e0130a00-1cf9-11ea-8721-6d106d5b8638.gif)
