### ISSUE TITLE
Org level collective

### ISSUE THREAD

**Issue by SimonCropp** [opencollective/opencollective#884]
is it possible to create a collective at the github organisation level? and if so where is the doco for that.

thanks :)

**Comment by piamancini** [comment]
hi @SimonCropp yes. Do you want to update an existing collective to an githuborg or a new one?
If it's a new one, just onboard any repo of that org and I can manually change it to the org.

**Comment by SimonCropp** [comment]
@piamancini thanks for getting back to me.

i would like this collective https://opencollective.com/fody/ to point to the org https://github.com/Fody instead of the repo https://github.com/Fody/Fody

**Comment by piamancini** [comment]
done. you should se the changes when cache clears.
