### ISSUE TITLE
new front end & updates fixes

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#885]
- [x] when clicking on submit an expense, page loads first a 404 before loading the new expense form

- [x] no link to /updates from the front page for non core contributors

- [x] submitting a new update (https://staging.opencollective.com/opensource/updates/new#about) and clicking on 'see more' also load a 404 before the page.

- [ ] css to add a video url in editor broken: 

![screen shot 2018-02-07 at 10 53 59 am](https://user-images.githubusercontent.com/3671070/35926048-3fe563be-0bf5-11e8-9e70-1f9a31c03199.png)

- [x] when submitting update, click on the logo to go to the front page again and update takes a long time to load, seems like it's not there.

- [x] Editing an existing update, click on save and it's unclear if it saves it or not. I am still in editing mode with no way of exiting without clicking on the logo. It's unclear if changes will remain if I do this.

**Comment by piamancini** [comment]
- [ ] Still seeing the flashing 404 when I click on new update
-  Nice that you can see the update published when you hit submit

- [ ] After submitting you see a duplicated nav bar in this url  https://staging.opencollective.com/opensource/updates/this-is-an-update
![screen shot 2018-02-09 at 1 48 19 pm](https://user-images.githubusercontent.com/3671070/36044233-f9aca2c0-0d9f-11e8-92da-04de9d3225ce.png)

- [ ] edit could be a bit more visible, it's hard to see: 

![screen shot 2018-02-09 at 1 50 38 pm](https://user-images.githubusercontent.com/3671070/36044336-4a177532-0da0-11e8-8994-e11f2730febe.png)

left a couple of design comments in the design channel

**Comment by xdamman** [comment]
I made a couple of design tweaks. It's better but still need some love from @cuiki 

Just deployed the latest version to staging. Is this good enough to go to prod?
