### ISSUE TITLE
 Feature request: Allow API access to event data

### ISSUE THREAD

**Issue by allella** [opencollective/opencollective#889]
I polked around a bit on the Wiki about API documentation and didn't see anything regarding an events API endpoint and @xdamman sent me here from the Slack API channel.

Code For Greenville (SC) has bots that are reading meetup group events from other popular services and then re-syndicating the event data so people can build various tech calendars without having to source constantly changing data from dozens of meetups.

We have a couple groups using OpenCollective in town so pointing a bot at your API to ping for new events would be handy for our use case.

Thanks

**Comment by xdamman** [comment]
Also, new api docs available on https://developer.opencollective.com
