### ISSUE TITLE
404: this page could not be found - connect to Github

### ISSUE THREAD

**Issue by lwm** [opencollective/opencollective#890]
I'm trying to create a new open collective for my free software project and was connecting my Github account with the open collective login when I saw this. I'm not able to get past this 404 error.

URL: https://opencollective.com/api/connected-accounts/github?utm_source=undefined
Logged in as: account with lukewm@riseup.net as email
Error message if any: 404 this page could not be found
Expected result: That my Github account was connected and I logged in
Browser: Firefox Quantum

Here's what I saw:
![screenshot from 2018-02-08 19-46-53](https://user-images.githubusercontent.com/1991377/35991891-f01019d2-0d08-11e8-85f5-aad43257a1a3.png)

**Comment by piamancini** [comment]
hi @lwm https://opencollective.com/opensource/apply is loading for me. You are using an old link /github/apply 
Where have you landed there from? We should update that. thanks!

**Comment by lwm** [comment]
Hey @piamancini, woops, I meant https://opencollective.com/api/connected-accounts/github?utm_source=undefined (the 'Connect Github' button). I'll amend the report, thanks for checking.

**Comment by piamancini** [comment]
@lwm yes, but the screenshot is what's showing me you are in the wrong URL. 

Can you walk me through it? you go to opencollective.com/opensource/apply and hit on Connect Github button, that should send you to an oauth page (is loading fine for me) https://github.com/login/oauth/authorize.... instead you are on a different URL /github/apply which is serving the 404...

Where are you coming from? are you logged in when you do this?

**Comment by lwm** [comment]
Ah right, I see. OK, I'll go through the steps I have:

1) Go into my email and click on the 'One-click Login' email (after signing up). It looks like:
> https://opencollective.com/signin/{{redacted-key}}?next=/opencollective-host/apply

2) On https://opencollective.com/opencollective-host/apply, I click on 'Open Source Project'
3) On https://opencollective.com/opensource/apply, I click on 'Connect Github', which is pointed at:
> https://opencollective.com/api/connected-accounts/github?utm_source=undefined

I then end up on the following link, after a re-direct:
> https://opencollective.com/github/apply/{{redacted-key}}?utm_source=undefined

And I then see the 404 error.

Hope that makes better sense!

**Comment by piamancini** [comment]
@lwm are you using a new token to log in? If you are using an old one, log out go to opencollective.com to login and generate a new one.

**Comment by xdamman** [comment]
Sorry it was an error at our main traffic router, it was redirecting to the wrong server.

**Comment by lwm** [comment]
Thanks @piamancini @xdamman, all good now 👍  

Looking forward to running [GAFACC](https://github.com/giving-a-fuck-about-climate-change) as an open collective. 

Thanks for all the work!
