### ISSUE TITLE
Automatically donate to the php packages that you depend on

### ISSUE THREAD

**Issue by Flyingmana** [opencollective/opencollective#894]
analog to https://github.com/opencollective/opencollective/issues/178 I would like to see something similar for PHP.

PHP packages have all a composer.json file. https://getcomposer.org/doc/04-schema.md

I hope after the mentioned Issue is finished, doing similar for PHP will only be a small step.

**Comment by xdamman** [comment]
Sadly we don't have many PHP collectives compared to Javascript. Can you help us get more Open Source projects on Open Collective?

**Comment by piamancini** [comment]
Closing as use case is covered through backyourstack.com without the automation.
