### ISSUE TITLE
Widget for backers and sponsors does not work

### ISSUE THREAD

**Issue by clickwork-git** [opencollective/opencollective#896]
The following code for backers and sponsors does not work as expected:

`<script src="https://opencollective.com/:username/collectives.js?role=backer"></script>`

from https://opencollective.com/widgets.

Also the following code:

`<script src="https://opencollective.com/:username/widget.js"></script>`

from https://github.com/opencollective/opencollective/wiki/Show-Backers-and-Sponsors.

Instead of the given examples both codes shows also the number of backers and the yearly budget.

**Comment by znarf** [comment]
They should be working. Please share more details if it's not.
