### ISSUE TITLE
Export "members" sample snippet problem

### ISSUE THREAD

**Issue by schettino72** [opencollective/opencollective#897]
When I use sample snippet like `<object type="image/svg+xml" data="https://opencollective.com/xxx/tiers/backers.svg?avatarHeight=36&width=600" />` all content on my page after this tag is not displayed.

According https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object `object` MUST have an ending tag. Changing the snippet to `<object type="image/svg+xml" data="https://opencollective.com/xxx/tiers/backers.svg?avatarHeight=36&width=600"></object>` fixed the problem.

**Comment by xdamman** [comment]
Ah good to know! Thanks for reporting this. Will fix this asap.
