### ISSUE TITLE
Add a custom one-liner/bio when making a donation

### ISSUE THREAD

**Issue by xdamman** [OpenCollective/OpenCollective#9]
When making a donation, we should allow the donor to say a few words about them. 
E.g. "Developer at Awesome Agency", "Thanks for this awesome open source project!", "In memory of ...", "Go Women Who Code, you rock!", "Proud sponsor", ...

Characters limit should be 100 (so that there is room to add a URL and @mention in a tweet).

Because it is related to the collective, it should be stored in the `UserGroups` table that makes the relationship between a user and a collective.

On the Website Repo, we should add a new input field here https://github.com/OpenCollective/website/blob/master/frontend/src/components/PublicGroupSignup.js#L30

and adapt the `UserGroups` model on API https://github.com/OpenCollective/api/blob/master/app/models/UserGroup.js#L11

How should we call this new column? `description`?

**Comment by cuiki** [comment]
Hi, here's the field after the donation flow...
![screen shot on 2016-04-08 at 12-34-12](https://cloud.githubusercontent.com/assets/981188/14432924/ceb0027a-ffd1-11e5-97d8-26ebbbb12d55.png)

And that one-liner will show up in the backers' cards like this:
![slack-imgs com](https://cloud.githubusercontent.com/assets/981188/14432951/e70f4e0c-ffd1-11e5-97d1-29a160c4d21e.png)

**Comment by piamancini** [comment]
reopen when it becomes a priority.
