### ISSUE TITLE
Create an event validation button does not work

### ISSUE THREAD

**Issue by Nadine21** [opencollective/opencollective#900]
While creating an event on my collective page, I fill in all the fields. However when I press the button "create event" nothing happens.
***

URL:  https://opencollective.com/codenplay/events/new
Logged in as: NadineKhouzam
Error message if any: /
Expected result: event is created
Browser: Chrome

![image](https://user-images.githubusercontent.com/4822284/36146735-e1e863ae-10b5-11e8-8661-30ff3d15f632.png)

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by piamancini** [comment]
@xdamman I can reproduce this for other collectives. No error on the console, but nothing happens.

**Comment by clarete** [comment]
The fix was deployed to staging & production. Please let us know if you face this issue again! Thank you!
