### ISSUE TITLE
new thankyou email for 501c3 with EIN info

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#903]
how can we do this without manually adding every single collective as a 'Case'

**Comment by xdamman** [comment]
Send me the updated thank you email and I'll update it.
Also, see how we did for WWCode with the billing address. That will make sure that the PDF receipts contain the EIN.

**Comment by piamancini** [comment]
@xdamman billing address in the admin of the host? (as in me?) there's no billing address in the collective's table

**Comment by piamancini** [comment]
For than you email for 501c3 (opencollective.com/foundation) 
Under the Collective's name in the signature add:
The Open Collective Foundation is a 501(c3) organization - EIN 81-4004928 - and donations to {{collective name}} may be fully tax deductible.

**Comment by xdamman** [comment]
What about using the same disclaimer than the one for WWCode 501c3?

```
Your contribution is tax-deductible to the extent allowed by law. You may save or print this receipt for your records. This email certifies that you have made this donation as a charitable contribution and you are not receiving any goods or services in return. This receipt may be useful to you when completing your tax return. Women Who Code, registered 501(c)3 Nonprofit TAX ID: XX-XXXXXXX
```

**Comment by piamancini** [comment]
yes. good idea

**Comment by piamancini** [comment]
@xdamman did you see my question above regarding EIN on PDF invoices?
