### ISSUE TITLE
Back button broken

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#910]
Visit opencollective.com/opensourcecollective. Click on "Material UI" collective card. Click back. It won't take you back (though on some of the collectives it takes you back).

**Comment by astorije** [comment]
I can confirm this is still an issue. If that's any useful, a short recording of this happening:

![back-btn](https://user-images.githubusercontent.com/113730/37324514-2dfc7b9e-2660-11e8-84ae-abdc29b4bbd5.gif)

This also happens in the admin settings, and other places.

Thanks! 🙏

**Comment by piamancini** [comment]
I think @znarf fixed this. Can you confirm and close if this is the case?

**Comment by znarf** [comment]
Yes, don't remember exactly the PR, maybe: https://github.com/opencollective/frontend/pull/464

Anyway, I tested and this works.
