### ISSUE TITLE
Onboarding flow for new collectives

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#914]
# Create a collective

Steps to create a new collective with self-onboarding flow.
Related: https://github.com/opencollective/opencollective/issues/679

## Sign up or login

- Email address

*It's not great to ask for an email address from the get go but it highly simplifies the process and it avoids issues with people who already have an account.*

## Pick a category
*(Already implemented today on https://opencollective.com/create)*
- Association
- Coop
- Lobby
- Meetup
- Movement
- Neighborhood Association
- Open Source Project
- Political Party
- PTA
- Student Club
- Other

## Details about your collective
*(already implemented today after picking a category on https://opencollective.com/create or when applying to an existing host: https://opencollective.com/brusselstogetherasbl/apply)*

- Name
- Website
- Twitter handle (if any)
- Description/Mission
- Long description (you can fill this later)

## 🎉 Congrats your collective is now created!

You can already customize your page, show your expenses, create events and post updates.

> If you want to collect money as a collective, you first need to [select a host (or create one)].

*(all of the above is already implemented on https://opencollective.com/create -- the only difference is that we shouldn't automatically attach newly created collectives to a default host)*

## Select a host

Select who will receive the money on behalf of your open collective. The host is responsible to hold the money on behalf of the collective on (one of) their bank account and to reimburse expenses that have been approved by the administrators of the collective. A host can be any legal entity (individual, non profit or for profit entity) and must comply with local financial authorities for bookkeeping and filing financial reports.

- Myself as an individual
- A company
- A non profit
- Apply to be hosted by an existing host: [list of existing hosts that are accepting applications]
  - Their mission is...
  - They are currently hosting # collectives [view]
  - Their host fee is...
  - Their legal status is...
  - Please read and approve their ToS (if any)
  
#### Information about the new host

- Type of entity: individual | company | non-profit (pre-filled based on previous answer)
- Pick an existing organization that you are an admin of (if any), or create one:
  - Legal name:
  - Legal type: 501c3/6, LLC, ASBL, VZW, ...
  - Official address:
  - Country:
  - Registration number: (EIN, Enterprise number, ... this number will appear on all automatically generated receipts and invoices)

#### Connect Stripe Account

Create or connect a Stripe Account to your host.

#### 🎉 All done!

Your collective can now start collecting money!

- [x] allow other collectives to apply to be hosted by you.

Enable people in your community or geography to create open collectives without having to worry about setting up and maintaining a legal entity!

You will receive an email with the details of the new collectives that would love to be hosted by you. It's up to you whether or not you would like to endorse the responsibility to host them.

- Types of collectives that can apply: checkboxes (see list above)
- Host fee:

# Notes

- Users need to be able to become hosts (need to reverse a previous decision that was forcing hosts to be organizations)

**Comment by piamancini** [comment]
- collectives that are self hosted or hosts with one collective should be able to manage that collective from the collective page - at the minimum a link should be provided that sends them to /organization/collectives/expenses.

**Comment by xdamman** [comment]
Agreed, just fixed that in https://github.com/opencollective/frontend/pull/256

**Comment by piamancini** [comment]
@xdamman also please consider this https://github.com/opencollective/opencollective/issues/901 specially if we are going to make applications to hosts for visible

**Comment by asood123** [comment]
Looks great @xdamman. I forget why we required hosts to be Orgs. I think it may have to do with admin check. We were running into bugs checking for users being hosts (which is a special case - not in `members` table)? Anyways, it should be solvable.

**Comment by piamancini** [comment]
since we are tabling this for a while I'm closing this issue.  @xdamman open when you take this again.
