### ISSUE TITLE
Unable to apply for creating a collective (BrusselsTogether)

### ISSUE THREAD

**Issue by jfdh** [opencollective/opencollective#916]
Hello,

A friend of mine in Brussels is trying to create an open collective under BrusselsTogether and using Safari but she keeps receiving the same error message (see screenshot below).

I just asked her to try again using Chrome.

https://opencollective.com/brusselstogetherasbl/apply

![oc issue](https://user-images.githubusercontent.com/30813303/36482936-a99a75ac-170c-11e8-8b03-dd10cd87595e.JPG)

thanks for your help!

Cheers,

JF

**Comment by xdamman** [comment]
It's unrelated to the browser. What is her login (username)?

**Comment by jfdh** [comment]
Je n’arrive pas à la joindre pour l’instant.

Sim adresse email si ça peut aider : Englebert.nastasia@gmail.com

**Comment by xdamman** [comment]
@jfdh I removed your comment for privacy reasons at it contained personal information

**Comment by xdamman** [comment]
Mmmm that's weird, her user doesn't have a profile, that's why it was failing. Let me fix this.

**Comment by xdamman** [comment]
It should be fixed now. Can she try again?
Also, ask her to keep the long description not too long. That may have been the issue. We need to fix that bug.
