### ISSUE TITLE
Create a waitlist for github signups

### ISSUE THREAD

**Issue by asood123** [OpenCollective/OpenCollective#92]
Now that we have a first version of Github signup live, let's figure out next iteration.

Goal: Create an "inactive" collective for anyone who signs up through github flow until they have 10 people committed to support it.

Tasks:

- [ ] `website`: implement designs (https://github.com/OpenCollective/OpenCollective/issues/33#issuecomment-214919994) to show empty cards and populate them as users commit
- [ ] `api`: support new state for Groups like `waiting`. Add in settings.json: `onWaitlist: true`.
- [ ] `api`: modify payments flow to only store payment information for groups in `waiting` stage - don't charge the card but store the amounts, user info, etc to show on the frontend
- [ ] `api`: once 10 users hit, charge all the cards immediately and activate the group (open to suggestions on easiest way to do this: a manual script, a queue, automated script that triggers on 10th commitment, etc) 
- [ ] `api`: send out an email to group owners to let them know that they got activated

Is there anything else needed? @xdamman @sedubois @carlosascari

**Comment by carlosascari** [comment]
Will the inactive collective have its own route `/pending/:slug` or will it be the same as the existing route `/:slug`? I'm assuming the latter

**Comment by xdamman** [comment]
yeah should be the later. 

+1 for `pending` instead of `onWaitList`

For a first implementation, once we hit the 10 backers, we should manually approve it which will trigger the charges to the credit cards on file.

**Comment by carlosascari** [comment]
@asood123  @xdamman 
Design/Scaffolding is done you can find it in the `pending-collective` branch:
https://github.com/OpenCollective/opencollective-website/tree/pending-collective
