### ISSUE TITLE
Link to /transactions page for USER and ORG collectives

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#921]
Otherwise, they have no way of getting to their invoices. 

Needs to be fixed asap or we are going to have a lot of support requests.

- [x] add 'transactions' as a header in profile and show a transactions section below
- [ ] add a link to view all transactions in thank you email

**Comment by piamancini** [comment]
also modify the thank you email with this?

**Comment by asood123** [comment]
what needs to change in thank you email?

**Comment by piamancini** [comment]
We used to add the link to /subscriptions for the invoice I think. Let me check

**Comment by asood123** [comment]
I think you are right, I can update that as well.

**Comment by piamancini** [comment]
just checked we send them the link to the PDF only, but we should add the new link there regardless.  It's a good reminder.

**Comment by xdamman** [comment]
The problem is that the `/transactions` page shows the total amount *before* fees for CREDITS and for DEBITS. That works well for collectives but not for donors, e.g. my transactions page shows my donations as DEBIT and therefore it shows the net amount the collective received https://opencollective.com/xdamman/transactions

The way to fix it would be to show the DEBIT transactions with their total amount including fees. Happy to make that change but needed to give you a heads up since it will impact all collectives.

**Comment by piamancini** [comment]
@xdamman the goal here is for a user to find all previous invoices.  before you could see them in /subscriptions. Now that page only holds subscriptions and credit card details but not previous invoices. What do you think is the easiest way to achieve this?

**Comment by xdamman** [comment]
The easiest way is the way I described. It would mean that debits will show the total amount including fees on the collective/transactions page. I think it’s ok but wanted to give you a heads up since it’s a change that will impact everybody.

**Comment by piamancini** [comment]
but debits for users shouldn't include fees... I'm talking about users accessing their invoices. I'm confused.

**Comment by xdamman** [comment]
It should. Because you paid for example $10. So you need a receipt for that amount even if the collective got less than that because of the fees.

**Comment by asood123** [comment]
Let's talk about this in person today. I think migration that @clarete is planning may fix this because it'll add fees to both transactions in double entry and we can flip `amountinHostCurrency` and `netAmountInCollectiveCurrency`
