### ISSUE TITLE
BrusselsTogether issues (GraphQL error, spelling mistakes in french)

### ISSUE THREAD

**Issue by jfdh** [opencollective/opencollective#922]
Hello,

I noticed some errors on BrusselsTogether host open collective (I am using Chrome and IE).
https://opencollective.com/brusselstogetherasbl

**Graph errors**
On IE
![ie error](https://user-images.githubusercontent.com/30813303/36669153-da6ab056-1aeb-11e8-8ef9-252304210907.PNG)

On Chrome
![member collectives](https://user-images.githubusercontent.com/30813303/36669181-ee4a6846-1aeb-11e8-90b8-643cd21e3d29.PNG)

On Chrome when clicking on huneeds collective from https://opencollective.com/brusselstogetherasbl
![huneeds chrome](https://user-images.githubusercontent.com/30813303/36677021-111511f0-1b05-11e8-95da-bca9dbcc0505.PNG)

**French spelling mistakes**
https://opencollective.com/huneeds
![french spelling](https://user-images.githubusercontent.com/30813303/36669323-5e30f4d6-1aec-11e8-8ed3-6ad2f168fea7.PNG)

Budget
Dernières dépenses
Solde courant

https://opencollective.com/huneeds

Thanks!

**Comment by piamancini** [comment]
thanks @jfdh are you blocked on this?

**Comment by piamancini** [comment]
@xdamman are you still working on this?
