### ISSUE TITLE
I just tried to approve an expenditure via mobile.and the approve and reject buttons are clipped.

### ISSUE THREAD

**Issue by ghuntley** [opencollective/opencollective#924]
![screenshot_20180226-235039](https://user-images.githubusercontent.com/127353/36671533-cd1af976-1af3-11e8-9c7a-d16dfd683ac3.png)

**Comment by piamancini** [comment]
Thanks Geoffrey 
are you blocked on this? Otherwise we'll tackle the css issues on friday (bug fix day)

**Comment by ghuntley** [comment]
Not blocked.

**Comment by piamancini** [comment]
Closing as this issue has been fixed.
