### ISSUE TITLE
user has duplicated avatar

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#925]
he has two roles on the members table (+ a weird fundraiser role which doesn't make sense since he put the money himself)
Both avatars point to the same profile. 
![pastedgraphic-3 2](https://user-images.githubusercontent.com/3671070/36684416-3e32178a-1aee-11e8-88c4-c60c8836f656.png)

**Comment by jfdh** [comment]
Same issue here https://opencollective.com/huneeds
