### ISSUE TITLE
Issues with Backers and Sponsors on GitHub/Widget

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#929]
1. Open Source Collective (the host) is showing up as a sponsor everywhere (see github/mochajs/mocha or github.com/vapor/vapor)

2. On tenancy (github.com/tenancy/tenancy), backer image shows both the backer and the admin (who is not a backer). 

3. Sponsor image (which exists in our database) isn't showing up under Sponsors at github.com/tenancy/tenancy.

**Comment by xdamman** [comment]
1. & 2. I've identified the bug, pull request coming
3. It's because the sponsor https://opencollective.com/gohcltech1 hasn't set a logo but we fall back on the Clearbit API to get us a logo based on the domain: https://logo.clearbit.com/gohcl.com
