### ISSUE TITLE
fetch contributors from open source projects

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#93]
We are reaching out to the core contributors or owners of popular open source projects to see if they are also interested in creating a collective. I've been doing manually by searching them in github/trending and  github-ranking. I'd like to find a quick way of getting this info through the api: 

- projects between 1000 - 5000 stars 
- number of contributors
- the names and contact of core contributors. 

Any ideas?

**Comment by piamancini** [comment]
@boneskull you have been digging into the github api, what do you think?

**Comment by carlosascari** [comment]
@piamancini I wrote a scraper https://github.com/carlosascari/github-people-finder
Let me know what you think

**Comment by piamancini** [comment]
@carlosascari it looks great! what's my cliendID and clientSecret? Do I need fork it to tweak it?  
the _blank detail <3

**Comment by asood123** [comment]
@piamancini I'll DM you separately

**Comment by boneskull** [comment]
@piamancini best to DM me or otherwise on Slack. I get so much email from GitHub you wouldn't believe. 

Concerned we are duplicating some effort here, though what I'm doing is pretty different than @carlosascari's tool

**Comment by boneskull** [comment]
this may be an inappropriate usage of the client ID and secret, as I understand that to be purely for machine-to-machine communication. You can authenticate just as well with a "personal access token" which is easily generated from your account settings.

**Comment by boneskull** [comment]
@piamancini at any rate I'll ensure github messages from open collective show up in my inbox going forward :smile:

**Comment by carlosascari** [comment]
@piamancini, @boneskull is correct a personal access token is the correct key for this, I've updated the repo so it uses an access token instead of client ID & secret.

@boneskull no need to worry about dupe effort here, I wanted a github scraper for myself and will work on it on my spare time, 2 birds 1 stone

**Comment by piamancini** [comment]
Fixed with https://github.com/carlosascari/github-people-finder
