### ISSUE TITLE
Migration circleci.yml files from circleci 1.0 to circleci 2.0

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#930]
They are going to stop supporting it in Aug 2018. See email for more details.

**Comment by xdamman** [comment]
@clarete already migrate the api to circle ci 2.0 https://github.com/opencollective/opencollective-api/pull/1350

@znarf can you migrate the frontend? @clarete had started but never got to the end of it: https://github.com/opencollective/frontend/pull/569

**Comment by clarete** [comment]
Yeah, what held me back was basically the need of loading the binary database dump during the test setup.  On the API side, I rewrote the tests to not use the dumps. That's what I'd recommend for the frontend as well. But that takes more time.

The other option I see is to create a custom docker image with the right version of the postgres client tools (especially `pg_restore` has to match whatever server version used by the server -- that is under control under the docker setup). That image can be used as the base image of the frontend's docker file.

The main downside of this approach is the introduction of another service in the deployment. The docker registry that will host the base image. I don't think circle-ci has a registry for docker images but I'd double check.
