### ISSUE TITLE
Issues on HuNeeds' page (host = Brussels Together)

### ISSUE THREAD

**Issue by Carodem** [opencollective/opencollective#934]
Hello ! 

I found some bugs on our project's page (I am working with Safari).
Link: https://opencollective.com/huneeds#

1) I created a new tier ("Super Jeton logement", 50€) right after the "Jeton logement", therefore I had to copy paste the "Sponsor" tier in order to place it after the new "Super Jeton logement" (I cannot insert a new tier between two existing tiers as each new tier comes at the end) --> first issue ?

2) A friend "Anonymous" (that I know) became sponsor (100€/month) but when I added the tier "Super Jeton logement" (50€), Anonymous is now displayed as "Super Jeton logement" even though he is officially Sponsor (the Sponsor tier is now empty...). I guess the tier moved when I copied pasted it (to insert a new one) but the contributor stayed at the same place ? 

![capture_d ecran_2018-02-28_a_14_45_46](https://user-images.githubusercontent.com/36923849/36791178-5ae378d8-1c97-11e8-893d-e4fb0825e4b0.png)
![capture_d ecran_2018-02-28_a_14_45_24](https://user-images.githubusercontent.com/36923849/36791295-af69cb32-1c97-11e8-9b65-7f9a132625c1.png)

I hope the explanation is clear, it is my first issue here :) 

Thanks for your help !

**Comment by piamancini** [comment]
Hi! 
Yes, when you updated the tier after the payment was made, the sponsor's tier wasn't updated. I just modified it manually, updated it to Super Sponsor (that seems to be the correct category now?)

**Comment by Carodem** [comment]
Yes it is perfect thank you  !

**Comment by Carodem** [comment]
I have 3 other issues... (actually 2 issues + suggestion :) ):

1. There are 2 spelling mistakes in french on the page, and the transactions (+title) are in english, would it be possible to put everything in french as most of the page is in french ?

![capture_d ecran_2018-03-02_a_11_57_19](https://user-images.githubusercontent.com/36923849/36896063-73198dea-1e11-11e8-8c18-e986094b61a5.png)


2. We see on the previous print screen the current balance that is much different from the annual estimated budget (print screen below), this is a bit confusing for a lot of people.. maybe put only the current balance is clearer for everyone ? 

![capture_d ecran_2018-03-02_a_11_57_37](https://user-images.githubusercontent.com/36923849/36896167-d8a08e20-1e11-11e8-96e0-0013eb8dc465.png)


3. Many contributors do not add a picture to their profile which is sad and less "social/human" as this platform is used for transparency, it would be best to encourage backers to add their picture or at least to make it easier. Or add an option to log in through Facebook so that their picture appears automatically ? 


Many thanks for your help !

**Comment by Carodem** [comment]
+ another issue: the donation on a backer's profile appears in € and in $US (both amounts should appear in € as they refer to the same amount)

![capture_d ecran_2018-03-02_a_15_35_16](https://user-images.githubusercontent.com/36923849/36904057-daac936c-1e2f-11e8-9e3c-8ced99136bb0.png)
![capture_d ecran_2018-03-02_a_15_35_21](https://user-images.githubusercontent.com/36923849/36904094-fc0edf4c-1e2f-11e8-8483-ede0ffe355b9.png)

Thanks !
