### ISSUE TITLE
admin profile fails when an event is deleted.

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#936]
opencollective.com/piamancini/subcriptions

**Comment by piamancini** [comment]
user creates event, is made an admin of the event, if event is deleted (event collective also gets deleted) but row is maintained in the members table, so profile fails with an unexpected error. 
Error console log: 
![screen shot 2018-03-01 at 12 25 20 pm](https://user-images.githubusercontent.com/3671070/36861114-fb6e48dc-1d50-11e8-934f-0224d79a2a37.png)

Since profile was failing, subscriptions page also failing. @clarete is proposing a work around below.

**Comment by clarete** [comment]
fixed!
