### ISSUE TITLE
Submit a monthly expense

### ISSUE THREAD

**Issue by Carodem** [opencollective/opencollective#938]
Hello ! 

Would it be possible to add the option of submitting a monthly expense ? 
https://opencollective.com/huneeds

![capture d ecran 2018-03-03 a 12 13 27](https://user-images.githubusercontent.com/36923849/36933652-4714b8ec-1edd-11e8-9ae7-ed1e870ccf3d.png)

Thanks !

**Comment by piamancini** [comment]
hi @Carodem we are not supporting recurring that atm and it's not likely we'll do it in the short term looking a our priority list. We are aware of this and we have it in the to do list so I'm going to close this issue for now.
