### ISSUE TITLE
fix step 2 github onboarding

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#94]
https://github.com/cutestrap/cutestrap couldn't be onboarded. 

Owner is @tylerchilds and nothing happened in step 2: "2/4 Pick a repository" and "Select a project you wish to create an open collective for." with nothing listed there, no errors in the console either.

**Comment by piamancini** [comment]
From @carlosascari: A scope is missing in the url when fetching the repos
https://github.com/OpenCollective/opencollective-website/blob/master/frontend/src/actions/github/fetch_repos.js#L13

**Comment by carlosascari** [comment]
@piamancini Its actually in the api repo, PR sent

**Comment by piamancini** [comment]
what's the PR #?

**Comment by asood123** [comment]
https://github.com/OpenCollective/opencollective-api/pull/362

**Comment by tylerchilds** [comment]
Thanks!

**Comment by asood123** [comment]
Documenting for posterity: That PR isn't going to fix this issue that @tylerchilds hit. That issue is because we look for a repos `owner`, which @tylerchilds isn't according to Github - he's listed as a `contributor`. @piamancini is following up with @tylerchilds.
