### ISSUE TITLE
Include whether a transaction was a recurring autopayment vs new donation in transaction CSV?

### ISSUE THREAD

**Issue by loganfsmyth** [opencollective/opencollective#940]
As mentioned on Slack, up until this month, all of the recurring autopayments were titled "monthly recurring subscription" so it was easy to pick out which transactions in a given month were new vs existing users.

For March, it appears that the title has changed and, at least from what I can tell, no longer includes anything to identify it as a recurring payment.

Would it be possible to include a field in the CSV so it is possible to tell which transactions were automatic payments and which were triggered by user action?

**Comment by piamancini** [comment]
We'll fix this @loganfsmyth in the meantime, can I help you unblock?

**Comment by loganfsmyth** [comment]
I'm fine for now, it isn't critical to have that information in the short term, I just noticed it when I went to dump this month's donation data since I like seeing how many new donations we've gotten.

**Comment by clarete** [comment]
Hi! A new column called "Subscription Interval" was added to the CSV. The possible values for it are:

 * month: Monthly subscriptions
 * year: Yearly subscriptions
 * one time: Either a one time subscription or an expense (we currently don't support subscriptions for expenses, when that time comes I bet we'll differ orders from expenses by the signal of the amount)

**Comment by loganfsmyth** [comment]
This is is a great flag to have. I've been picking that out of the name by looking for `monthly` in the text, so that'll still simplify my logic.

That said, it isn't quite the differentiation I was hoping for. I was more curious, within the recurring transactions, when a transaction is the first one, or I guess more accurately whether it was triggered by a specific user action, vs one triggered as part of your backend autopayment system.

Essentially I was using this as a proxy how many newly-committed users have created recurring payments in a given month.

**Comment by clarete** [comment]
Hi @loganfsmyth thanks for the thorough explanation, now I get the exact problem! I'm reopening the ticket to address your actual need.

I can create another field with in the CSV the date of creation of the order. You will be able to tell how many recurring users started contributing using this new column and the Subscription Interval (if it's not `one time` and `order date` > `firstDayOfMonth()`).

Let me know if that'd be enough to fix this issue! Thank you!

**Comment by clarete** [comment]
The above change will be out in the next roll out!
