### ISSUE TITLE
Deal with the 255-byte limit on expense title

### ISSUE THREAD

**Issue by espadrine** [opencollective/opencollective#941]
Hello wonderful people!

While updating an expense, I was puzzled to notice that clicking the "Save" button did nothing — no warning or error showed up on the screen. So I had a look at the beloved JS console, and lo and behold—

> Uncaught (in promise) Error: GraphQL error: value too long for type character varying(255)

I guessed the following things:

- You are using GraphQL (granted, pretty easy guess right there),
- Your backend store is a PostgreSQL database,
- The [type of the title column in the expenses table](https://github.com/opencollective/opencollective-api/blob/0dd7232dd6d467e5b4de8ee314436d9c279999a1/migrations/20160608001600-add-expenses-table.js#L47) is varchar(255) (probably an unfortunate Sequelize default?).

Could you switch the type of this column to allow arbitrary text lengths? In PostgreSQL, I feel like using `varchar` is usually not as good as using `text`: the latter is [faster](https://www.postgresql.org/docs/10/static/datatype-character.html) and avoids users being unexpectedly constrained. (They usually don’t write novels the size of the Bible anyway.)

Alternatively, could you add an error on the website when this occurs please?

---

URL: https://opencollective.com/shields/expenses
Logged in as: espadrine
Error message if any: Uncaught (in promise) Error: GraphQL error: value too long for type character varying(255)
Expected result: 
Browser: Chrome, but since this error comes from the backend, I must admit I would be pretty shocked if it only happened for Chrome.

![opencollective](https://user-images.githubusercontent.com/100689/36946987-0b4ebda0-1fc6-11e8-8ad8-c717d7873680.png)

[Related tweet](https://mobile.twitter.com/espadrine/status/970061859637350401).

**Comment by piamancini** [comment]
hey! yes, we have the same problem in a description when creating a user. Thanks for reporting this, I'll add it to the bug list for fridays.
