### ISSUE TITLE
user is receiving an invoice for less amount than what he donated

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#949]
https://opencollective.com/finpo/transactions
he made a $250 donation, he's dowloaded invoice is for $215 (this is probably related to fees)
See email subject: "I can't find Receipt anymore ... since 2018/3" to see the invoices (they have PI)

**Comment by piamancini** [comment]
cc/ @clarete

**Comment by asood123** [comment]
I think this is just an issue of using wrong field - when a collective of type USER or ORG, we need to use netAmount, instead of Amount.

**Comment by clarete** [comment]
I also need to test generating the invoice for a collective too, but here's what I've gotten so far:
https://github.com/opencollective/opencollective-website/pull/790

**Comment by xdamman** [comment]
Looks like the bug is elsewhere. This is pulling the invoice for the wrong transaction. The `collective` is the user/org instead of the collective that received the money. I'll look into it more.
