### ISSUE TITLE
allow host to see who submitted an expense

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#95]
host are seeing now expenses without the user that submitted it. It makes it very hard for them to know if they should approve it. This issue is blocking the onboarding of the rest of woman who code network. 
see screenshots of what host sees:  
![austin_view 2](https://cloud.githubusercontent.com/assets/3671070/15519624/2e8be2f2-21b7-11e6-8c66-c2d115fd1749.png)
![austin_view 3](https://cloud.githubusercontent.com/assets/3671070/15519629/31a92cb0-21b7-11e6-9026-c2f82eed5e3f.png)

**Comment by asood123** [comment]
@erickrico can we get a quick design for this? We want to show the name and email of the person on the expense approval page. 

We'll also need to add both of these fields on the expense submission page opencollective.com/yeoman/expenses/new but don't need any designs for those.

**Comment by asood123** [comment]
Marking this high priority as this is blocking onboarding of more WWCode chapters

**Comment by erickrico** [comment]
just a quick sketch to see if i understood
![from skitch](https://cloud.githubusercontent.com/assets/18429104/15551046/bc602698-2279-11e6-9e5f-91f0b8bd6a64.jpg)
im already working on it

**Comment by asood123** [comment]
Looks like the right path.

**Comment by erickrico** [comment]
ok, i figured it was made for mobile, the color coding will refer to the category the expense belongs to, let me know what you think or if a miss any key information 
![expenses](https://cloud.githubusercontent.com/assets/18429104/15552786/a472fe5e-2281-11e6-8603-b6f11f3710f9.png)

**Comment by piamancini** [comment]
lgtm. why do you think the color coding is necessary ?

**Comment by erickrico** [comment]
consistency through the platform and at glance information.

**Comment by asood123** [comment]
I implemented a simple version of this (only name showing - no email because of privacy reasons) to unblock us. Closing this for now.
