### ISSUE TITLE
set up onboarding emails for meetups

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#956]
- [ ] - look at current copy and update (pia)
- [ ] - trigger once a meetup is approved (xavier)
- [ ] - design an initial email for before they are approved (pia)
- [ ] - design an initial email for non meetups and non OS (the one currently sent manually)(pia)
- [ ] - implement initial emails (xavier)

**Comment by piamancini** [comment]
@xdamman can we set up automatically the default tiers for meetups? 
I'd like to get this out tomorrow our monday 
1 month x $250
3 months x $675 (10% discount)
6 months x $1200  (20% discount)

**Comment by piamancini** [comment]
@xdamman this is the current page https://opencollective.com/meetups
There is no specific host the /meetups/apply in this case wouldn't work because /meetups is just way of bundling them with parentCollectiveId. What do you suggest?

**Comment by piamancini** [comment]
@xdamman meetups collective ID is 858 I will add this as Parent Collective ID

**Comment by xdamman** [comment]
@piamancini what should be the default host? I'll use 858 as the `ParentCollectiveId` but I also need the `HostCollectiveId`

For the default tiers, what should be the default description for each and button if different than "contribute"?

**Comment by piamancini** [comment]
@xdamman default host is ID:8674
the tag is "Tech meet-ups" Can you use that instead of parent collective ID?
Button "Sponsor"

**Comment by xdamman** [comment]
Cool, also need a small description for each tier.

**Comment by xdamman** [comment]
btw fwiw it's very weird to read "meet-up" (1.4M results on Google Vs 12M for "meetup")

**Comment by piamancini** [comment]
thanks

**Comment by piamancini** [comment]
I'm editing the tag as well FYI for it to be meetups

**Comment by piamancini** [comment]
tag and title fixed. 
@xdamman Can we change the #parenting that pops up when you scroll down to the meetup list to something less confusing? members maybe or collective-members?

**Comment by xdamman** [comment]
ok

PS: Still need the description for each tier.

**Comment by piamancini** [comment]
"Sponsor our meetup and get: A shout-out on social media, presence in the merch table and your logo on our meetup page"

Each tier has the same description, the difference is the discount.  So maybe add '10% discount' on the 3 months tier and '20% discount' on the 6 months one. 

quick reminder, they are all one time donations.

**Comment by xdamman** [comment]
Collectives created via https://opencollective.com/meetups/apply will now have the "Tech meetups" tag, the `HostCollectiveId` 8674 and the default tiers for tech meetups.

**Comment by piamancini** [comment]
Great!
