### ISSUE TITLE
hyperlink text in event description is white on white

### ISSUE THREAD

**Issue by aaronpk** [opencollective/opencollective#958]
URL: https://opencollective.com/indieweb/events/indiewebcamp-nurnberg-550ev
Logged in as: aaronpk
Error message if any:
Expected result: 
Browser: Chrome on OSX

The hyperlink text in the event description is white on a white background.

![screenshot 2018-03-12 11 32 56](https://user-images.githubusercontent.com/113001/37302579-2417d190-25e9-11e8-9310-3c60038a6e6c.png)

![screenshot 2018-03-12 11 33 00](https://user-images.githubusercontent.com/113001/37302593-2ea68df4-25e9-11e8-9fa8-e81e9e577215.png)

**Comment by piamancini** [comment]
@xdamman is this fixed with the change you merged today?

**Comment by xdamman** [comment]
Yes fixed.
