### ISSUE TITLE
sponsor still showing up in github months after they stop contributing

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#959]
Sponsors used to show up while they are actively contributing. At least that was the consensus?
Digital Ocean is still showing up here https://github.com/buunguyen/octotree even if they stop donating after two months
https://opencollective.com/octotree#contributors

**Comment by xdamman** [comment]
Fixed.

**Comment by buunguyen** [comment]
It still shows here https://opencollective.com/octotree

**Comment by piamancini** [comment]
@xdamman reopening this, it still shows up on gh

**Comment by piamancini** [comment]
closing this since sponsor is not on the readme anymore.
