### ISSUE TITLE
an embeddable widget button for sites

### ISSUE THREAD

**Issue by santisiri** [OpenCollective/OpenCollective#96]
I want a simple widget that works as a button (maybe some customization features like 'amount' options could be nice too), but should be a call-to-action button I can put on my site.

For further reference, check the 'donate bitcoin' button on [democracy.earth](url), that's exactly what i'm thinking of here. Check out how this tool actually is configured on coinbase.

I've checked the existing widget but it's a bit too big and would break my site's design a bit.

Keep up the awesome work!

**Comment by xdamman** [comment]
How many people donated via this bitcoin button? For what total amount?

Also, what label would make the most sense here?
- Support our collective | 30 members
- Join our [open] collective | 30 members
- Donate to our [open] collective | $300 raised
- Donate | 22 backers
- Become our 23rd backer

**Comment by xdamman** [comment]
Ping @erickrico
