### ISSUE TITLE
Project logos are blurry on HiDPI / Retina screens

### ISSUE THREAD

**Issue by astorije** [opencollective/opencollective#960]
Hi Open Collective!

I have noticed that on homepages, project logos are not Retina-ready. Taking https://opencollective.com/thelounge as an example:

<img width="559" alt="100" src="https://user-images.githubusercontent.com/113730/37323854-93c9109e-265c-11e8-830f-9513a8a2c75f.png">

(You might have to be on a HiDPI screen such as a Macbook or mobile to see the logo being blurry)

I have noticed the logo has `height: 10rem`, which is `100px` once applied. I have also noticed that the image URL is `https://opencollective.com/proxy/images/?src=[...]&height=100`.
Due to its max width, I tried to replace that URL to end with `&height=200` (to apply the good practice of using images twice taller/wider than their result), and it looks really good:

<img width="564" alt="200" src="https://user-images.githubusercontent.com/113730/37323964-2c3b554e-265d-11e8-8baa-7b4fa3470150.png">

**Comment by astorije** [comment]
Hey there 👋
If you have any pointers, I'd be happy to help, I'm wondering where that 100px value is coming from.

**Comment by alannallama** [comment]
@cuiki will this be fixed in the new Collective page?

**Comment by Betree** [comment]
Thanks for the pointers @astorije, this is really helpful! I'm currently working on the new version of the collective page and I'll make sure this is included.

Ideally we should use [responsive images (with `srcset`)](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images) to ensure we load the best image based on screen resolution.

**Comment by znarf** [comment]
@Betree on the updated image service, logos are now 128px by default:

https://images.opencollective.com/babel/logo.png
https://images.opencollective.com/babel/logo/128.png

But you can pass the size you need, ie:
https://images.opencollective.com/babel/logo/256.png

**Comment by znarf** [comment]
This will be impacted by https://github.com/opencollective/opencollective-frontend/pull/1686

**Comment by Betree** [comment]
This should now be addressed: on the collective page (ie. https://opencollective.com/babel/) and most new pages developed since, we're using avatars with 2x their displayed size. Feel free to re-open or create new issues if some places are still displaying low-resolution avatars.
