### ISSUE TITLE
Invalid URL is opened when clicking "edit collective" from a contribution form

### ISSUE THREAD

**Issue by astorije** [opencollective/opencollective#961]
Apologies if this is a duplicate, but it's not an easy one to search for 🤷‍♂️

Reproduction steps:

- Go to any project where you have access to the "edit collective" settings. In my case, I will use https://opencollective.com/thelounge
- Click on a "contribute" button of one of the available tiers on the right. In my case, it opens https://opencollective.com/thelounge/order/3739.
- Click on "edit collective, an invalid URL gets loaded. In my case, it opens https://opencollective.com/thelounge/order/undefined/edit

I have seen this happening in a couple places, but I can't remember exactly where so I'll keep an eye out.

**Comment by xdamman** [comment]
Good catch. Fix coming. Thanks for reporting!
