### ISSUE TITLE
Impossible to delete a draft

### ISSUE THREAD

**Issue by astorije** [opencollective/opencollective#962]
I saved an update as a draft a few days ago, then changed my mind and wanted to delete it, but did not find a way to do so.

When I click on the draft, I can only edit it and publish it, not delete it:

<img width="397" alt="screen shot 2018-03-13 at 01 31 37" src="https://user-images.githubusercontent.com/113730/37324213-7db48b06-265e-11e8-8bb8-8fcc9e59118f.png">

Is that currently impossible? If so, would you mind deleting it until it becomes possible to delete drafts ourselves please?
(It's the only draft in https://opencollective.com/thelounge, the other update was published)

**Comment by xdamman** [comment]
deleted. 

Yes we should add a way to delete an update. I will create a separate issue for this.

**Comment by astorije** [comment]
Thanks!
