### ISSUE TITLE
Links in updates suddenly turned white

### ISSUE THREAD

**Issue by astorije** [opencollective/opencollective#963]
I currently have 1 update and 1 draft, and in both cases the links turned white overnight (they were fine a couple days ago).

They currently show up as:

<img width="626" alt="screen shot 2018-03-13 at 01 35 18" src="https://user-images.githubusercontent.com/113730/37324284-064e1ebe-265f-11e8-9a78-bd3e3ecc6ba0.png">

When selecting the paragraph, we can see the link is still there, just... white 😅

<img width="631" alt="screen shot 2018-03-13 at 01 39 34" src="https://user-images.githubusercontent.com/113730/37324352-6a4d9c8c-265f-11e8-9921-1bcfd1dddf60.png">

The CSS property on the link _may_ be a bit too generic 😬

<img width="364" alt="screen shot 2018-03-13 at 01 35 48" src="https://user-images.githubusercontent.com/113730/37324286-06782e84-265f-11e8-9cd8-ebbd8d3bfddc.png">

Thanks and good luck!

**Comment by xdamman** [comment]
Ah, my bad. I introduced that bug. Thanks for reporting, fix coming! :)

**Comment by astorije** [comment]
I do appreciate the color change in the homepage cover however, very nicely done :)

Before | After
--- | ---
<img width="559" alt="100" src="https://user-images.githubusercontent.com/113730/37323854-93c9109e-265c-11e8-830f-9513a8a2c75f.png"> | <img width="544" alt="screen shot 2018-03-13 at 10 30 14" src="https://user-images.githubusercontent.com/113730/37348041-8c7cf16e-26a9-11e8-9f87-a94267b06c6e.png">
