### ISSUE TITLE
Add a way to delete an update

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#965]
See https://github.com/opencollective/opencollective/issues/962

**Comment by piamancini** [comment]
is this still open?

**Comment by astorije** [comment]
As far as I can tell, yes.

**Comment by Betree** [comment]
Would like to take this one!

Adding a **delete** link next to **edit** seems to be the most relevant:

![selection_022](https://user-images.githubusercontent.com/1556356/46736307-02923900-cc99-11e8-8827-a9b77f32541c.png)

We should also add a confirmation to avoid dramas with miss clicks. As of today when we try to delete an event the confirmation is done through a JS confirm:

![selection_023](https://user-images.githubusercontent.com/1556356/46736166-a0393880-cc98-11e8-989c-0d5b3818ba73.png)

I can reproduce the same behavior and use a `confirm` for the first iteration, however a custom modal or a confirm page would probably be nicer.
