### ISSUE TITLE
user is trying to unsubscribe from onboarding emails and is getting a 404

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#966]
https://opencollective.com/api/services/email/unsubscribe/emailbcc%40opencollective.com/materialos/onboarding/98c7230ddddd384063145bff2a8ec88d

**Comment by piamancini** [comment]
also @xdamman I can't find his user (id 10937) in the notifications table. where can I unsubscribe him from?

**Comment by xdamman** [comment]
The notification table doesn't record anymore the subscriptions but only records the unsubscriptions. So add a row there for that UserId and the type of notification ("on boarding")

**Comment by piamancini** [comment]
@xdamman I manually unsubscribed the user. Issue still stands that his unsubscribe buttons is a 404
