### ISSUE TITLE
modify query for total amount donated and invoices after refund

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#968]
profiles still show total amount donated without taking refunds into account
invoices should also ignore refunds

**Comment by clarete** [comment]
yeah, I think this is problem is going to show up everywhere we show the ledger of a collective (of any type). One other place I can think of is the invoices. @xdamman!

I'm thinking about creating a small function to get the ledger for each collective so we'll be able to centralize the logic in one place. The two things this function could initially do is to:

 1. get the balance of a given collective taking into account all transactions including refunds (would be used in the `:collectiveslug/` page to show how much a backer has contributed & how much a collective actually has)
 2. List transactions of that collective (would replace the logic in `:collectiveslug/transactions/`)
