### ISSUE TITLE
Links and markup are filtered out in update listing page

### ISSUE THREAD

**Issue by astorije** [opencollective/opencollective#969]
It seems like all markup gets removed from the update listing page, which means links get removed. For example:

Details page | Listing page
--- | ---
<img width="448" alt="details" src="https://user-images.githubusercontent.com/113730/37573312-e00ca7b0-2aec-11e8-9653-c676e0330ee1.png"> | <img width="437" alt="listing" src="https://user-images.githubusercontent.com/113730/37573313-e01a955a-2aec-11e8-9a9a-cc16e28643d0.png">

It would be great if listing page could display the markup (or a subset of it) from the source post.

**Comment by piamancini** [comment]
hmmm this was a bug that was fixed already. I'll add it to the list.
Does this happen when you edit or you publish?
@xdamman markup is remove on update.

**Comment by astorije** [comment]
@piamancini, you're not talking about #963, correct?

I believe both re: edit vs. publish. For example, if you look at https://opencollective.com/thelounge#updates, the "sheer number of people contributing to The Lounge" text is actually a link, showed at text in the listing.
It is more of an issue on the screenshot above because "See the official release notes" without a link doesn't make a lot of sense.

Does this help?

**Comment by astorije** [comment]
Hey @piamancini and @xdamman, oops, _almost_... 😅

<img width="819" alt="screen shot 2018-03-23 at 09 57 01" src="https://user-images.githubusercontent.com/113730/37833013-9f232b38-2e80-11e8-9ea0-059120ca3b81.png">

**Comment by xdamman** [comment]
Ah yes forgot to deploy the update on the frontend. I’m afk but will deploy this tonight. Hang tight.

**Comment by xdamman** [comment]
Fixed

**Comment by astorije** [comment]
Thanks @xdamman, that's awesome!

I know this is very much on the nitpicky side, but I've noticed one more thing I wanted to mention, unsure if that would get fixed along with the rendering of the links.
The update looks like:

<img width="674" alt="screen shot 2018-03-24 at 00 46 49" src="https://user-images.githubusercontent.com/113730/37860502-d3329374-2efc-11e8-9439-4187646319cf.png">

In the listing page, the paragraph jump is completely removed:

<img width="289" alt="screen shot 2018-03-24 at 00 46 40" src="https://user-images.githubusercontent.com/113730/37860503-d617bd26-2efc-11e8-9c4d-f3b33d9ef1c8.png">

By no means I'm trying to make assumptions or undermine the complexity, but when stripping things out, would it be possible to replace newlines/etc. with a whitespace instead of suppressing it?
