### ISSUE TITLE
traceable url for YC thread

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#97]
I'm going to post a thread in the YC network: 

(along the lines of)

> Give Back: if your company uses open source software you can now support them
> - link to opencollective.com/opensource 
> - if the technology you use is not a collective yet, send them this link (url: opencollective.com/github/apply?ref=referral_id) We have a waiting list but we'll give priority to yc referrals. make sure you share this link. 
> 

Also ideas to make opencollective.com/opensource better looking are welcome.

**Comment by piamancini** [comment]
Something that can be done to improve opencollective.com/opensource is transforming the svg transparent logos into visible logos.

**Comment by carlosascari** [comment]
@piamancini 
> transforming the svg transparent logos into visible logos

I want to be sure, did you mean the white logo background on top of transparency UserCard component?
![UserCards](https://my.mixtape.moe/hpbhuk.png)

**Comment by piamancini** [comment]
@carlosascari Most of the logos are svg in white to contrast with the hero background in public page. The avatar background is white and so you can't see them. See for example: golix, cutestrap and algorithm visualizer. 

<img width="1113" alt="screen shot 2016-06-07 at 3 14 26 pm" src="https://cloud.githubusercontent.com/assets/3671070/15871421/8f353be2-2cc2-11e6-8914-2fdd92790a9d.png">

**Comment by asood123** [comment]
We could add a darker background for all of them. An image can override it
and svg will stand out as well?

**Comment by carlosascari** [comment]
Ok, adding a darker background solves theses particular logos however they contrast against other darker colors like that of APEX that has an all black bg, and also keep in mind logos like KOA, which have a visible white background.

Notice a ~20% darker background, the white svg show, but APEX, Vapor & React-Starter-Kit begin to loose contrast, also for KoaJS and preset logos the white background begins to show

![20% Darker](https://my.mixtape.moe/djwbaa.png)

I don't think changing the bg will be enough in the long run

**Comment by piamancini** [comment]
hmmmm not sure, it works for now. Apex is a screeshot I did for it to show,  the original logo is white, I can revert it to the original if we go down this road.

**Comment by carlosascari** [comment]
Yea your right it should be enough, I've sent the PR with the fix 
https://github.com/OpenCollective/opencollective-website/pull/284

**Comment by asood123** [comment]
PRs here: https://github.com/OpenCollective/opencollective-api/pull/440 https://github.com/OpenCollective/opencollective-website/pull/293
