### ISSUE TITLE
Cancel a subscription does not work

### ISSUE THREAD

**Issue by clickwork-git** [opencollective/opencollective#970]
It’s not possible to cancel subscriptions as described in the FAQ:

> How can I cancel my monthly donation?
> 
> We are sorry to see you go! Go to opencollective.com/subscriptions to manage your subscriptions.

**Comment by piamancini** [comment]
Hi @clickwork-git what's your opencollective profile slug?

**Comment by asood123** [comment]
Hi @clickwork-git. We recently updated our Subscriptions pages to attach to the collective that gave the subscription. That link above will redirect you to your personal collective by default (opencollective.com/edi-goetschel/subscriptions). In this case, looks like you made a donation through an organization. Your subscription can be cancelled at opencollective.com/clickwork/subscriptions. Please let us know if you have any other issues.

**Comment by clickwork-git** [comment]
Thank you, this works!

**Comment by kreativmind** [comment]
@asood123 I am a sponsor for the above project. Since @clickwork-git has canceled, my profile shows no subscritptions and no contributions, however, my bank account is still being drafted $10/month and being emailed a receipt of payment. I need to this to be fixed please.

**Comment by asood123** [comment]
Hi @kreativmind, I see a subscription from you here: https://opencollective.com/kreativmind#. It's attached to your organization, rather than your personal collective.

**Comment by kreativmind** [comment]
Thanks. I have cancelled it. But since Bludit isn't using OpenCollective any longer, how do I get the $10 back credited to my card?

**Comment by asood123** [comment]
@piamancini can help with that

**Comment by piamancini** [comment]
hi @kreativmind I just reimbursed the latest contribution to bludit
