### ISSUE TITLE
change hosts for collective 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#975]
We need to move https://opencollective.com/userfrosting from open source collective to their own org https://opencollective.com/userfrosting-project. They have 2 active subscriptions, all post-migration and one one time donation

- [x] add new host id 12212
- [x] confirm host fee if any
- [x] send available funds to new host

**Comment by piamancini** [comment]
We also need to move social.coop to the Sarapis host

**Comment by asood123** [comment]
Need to paypal them $66.50. That's $62.75 in collective money and $3.75 in host fees.

**Comment by asood123** [comment]
Added a payment method manually as well

**Comment by piamancini** [comment]
available budget sent.

**Comment by clarete** [comment]
Seems like the first payment went to the right account finally! We'll close this one again but please feel free to re-open or create a new issue if you spot anything broken!
