### ISSUE TITLE
Issues on creating profiles on Brussels Together (HuNeeds : host on BT)

### ISSUE THREAD

**Issue by zazengle** [opencollective/opencollective#977]
Hello I am part of the collective HuNeeds on Brussels Together and have 2 request: 
(i am working with safari)

1 . Many contributors do not add a picture to their profile which is sad and less "social/human" as this platform is used for transparency, it would be best to encourage backers to add their picture or at least to make it easier. Or add an option to log in through Facebook so that their picture appears automatically ?

<img width="1216" alt="capture d ecran 2018-03-20 a 09 57 31" src="https://user-images.githubusercontent.com/37575413/37644848-5286db10-2c25-11e8-976a-008535b81beb.png">

2. Would it be possible to make the Tiers appear on the whole page as I represent on the picture, and not one above the other ? 
As people get demotivated and don't really go at the bottom of the page and so, they miss some of the tiers... 

<img width="1413" alt="capture_d ecran_2018-03-20_a_09_59_40" src="https://user-images.githubusercontent.com/37575413/37645269-a3286222-2c26-11e8-96fb-0880db3f391c.png">

Thank you

**Comment by znarf** [comment]
Point 2. Will be addressed by a revamp of the contribute flow. This was also mentioned in https://github.com/opencollective/opencollective-frontend/issues/468
