### ISSUE TITLE
better default logo for specific donation link

### ISSUE THREAD

**Issue by piamancini** [OpenCollective/OpenCollective#98]
We are sending this to a company to give 1500 per month to a collective and it looks so hacked together... 
<img width="1125" alt="screen shot 2016-05-27 at 12 33 35 pm" src="https://cloud.githubusercontent.com/assets/3671070/15619176/6f85f304-2407-11e6-98c9-8d30c9ca6b83.png">

**Comment by erickrico** [comment]
is this a email?

**Comment by piamancini** [comment]
nope, a url for example:
https://opencollective.com/sf-data-science/donate/1500/monthly

**Comment by erickrico** [comment]
ok, on it

**Comment by erickrico** [comment]
![support us no logo](https://cloud.githubusercontent.com/assets/18429104/15833167/282ce472-2beb-11e6-9bff-4c603c1def60.png)
![support us](https://cloud.githubusercontent.com/assets/18429104/15833166/282c5a66-2beb-11e6-9d46-3e00c3766499.png)

**Comment by piamancini** [comment]
great!

**Comment by piamancini** [comment]
@xdamman we should implement this at some point.

**Comment by piamancini** [comment]
reopen when it becomes a priority.
