### ISSUE TITLE
Silver sponsor logo disappeared after editing tiers

### ISSUE THREAD

**Issue by luceos** [opencollective/opencollective#982]
I just edited the description of my tiers. After which the Silver Sponsor disappeared from the right tiers card. This sponsor was previously manually set to the silver tier due to manually selecting an amount instead of clicking a tier. 
![image](https://user-images.githubusercontent.com/504687/38021588-8f762dec-327d-11e8-91ad-28ea4f882f1e.png)
![image](https://user-images.githubusercontent.com/504687/38021639-acc1a9f8-327d-11e8-8ce4-a6f2e62daded.png)

see: https://opencollective.com/tenancy#contributors

**Comment by piamancini** [comment]
@xdamman this is also referenced in #808 The sponsor is marked as silver sponsor in the card but it's not showing up in the side tiers.
Setting this as a priority bug to look at on Friday.

**Comment by xdamman** [comment]
It's because the `TierId` was not referenced in the `Order`. We fixed it in the `Members` table but not in the `Orders` one. Fixed now.
