### ISSUE TITLE
Missing sponsor link shifts remaining sponsor links in SVG

### ISSUE THREAD

**Issue by developit** [opencollective/opencollective#983]
In the SVG OpenCollective generates, when a sponsor has no link, any remaining sponsor links following it are off-by-one.

More details here:
https://github.com/developit/preact/issues/1049

***

URL: https://github.com/developit/preact
Expected result: sponsors after B&B have correct links

**Comment by xdamman** [comment]
Fixed. May take a day for the cache to expire.
