### ISSUE TITLE
New design hides/breaks gulp's banner

### ISSUE THREAD

**Issue by phated** [opencollective/opencollective#985]
Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: https://opencollective.com/gulpjs
Logged in as: (just provide your username or the url of your profile) not logged in
Error message if any: none
Expected result: Don't hide gulp's banner
Browser: Chrome

Bonus point if you can add a screenshot :-)

<img width="1390" alt="screen shot 2018-03-30 at 12 21 02 pm" src="https://user-images.githubusercontent.com/992373/38150651-da8ae8b6-3414-11e8-991e-ce79ee70271b.png">

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by phated** [comment]
Anything happening to fix this?  Our design hinged on the whole banner being displayed.  cc @piamancini @xdamman

**Comment by phated** [comment]
@piamancini is anything going to be done about this?

**Comment by znarf** [comment]
Closing this issue because of the New Collective Page.

However, seems Gulpjs needs to adjust the logo/background, see: https://blog.opencollective.com/new-collective-page/

> all logos are now designed to display on a white background. If you have a white logo, upload an image with a colored background so it shows up.

**Comment by phated** [comment]
Thanks @znarf! The new customization is great! I'm loving how I was able to get adapt our collective page to the gulp brand
