### ISSUE TITLE
expense upload is failing

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#986]
expenses can't be uploaded, this can be reproduced in production.

**Comment by aaronpk** [comment]
This just got me too. Since it's not possible to create an expense without an attachment, I'm completely stuck right now.

**Comment by piamancini** [comment]
Thanks @aaronpk for bumping this up. we'll be fixing it soon.

**Comment by piamancini** [comment]
@aaronpk this is fixed now.
best
