### ISSUE TITLE
contributors badges are broken

### ISSUE THREAD

**Issue by itsjavi** [opencollective/opencollective#989]
Hi, I integrated Open Collective recently in one of my projects but this seems to be happening to every project: the contributors SVG badges are broken as you can see in the screenshot and in the link https://opencollective.com/vuejs/contributors.svg

The SVG seems to be truncated and that produces an error.
<img width="600" alt="screen shot 2018-04-02 at 05 08 54" src="https://user-images.githubusercontent.com/122741/38181628-345c089a-3634-11e8-9de0-51fecd33dc1f.png">

**Comment by piamancini** [comment]
@xdamman can you have a look at this tmr? 

Just heard from electron:

> Our contributors page seems to have JS errors on Chromium and different errors on Safari.
> https://electronjs.org/donors
> On Chrome, the page does not load at all.
> On Safari we see Cannot find route /mycard
>

**Comment by xdamman** [comment]
@piamancini just fixed the error for electron. I'll take a look at the svg issue tomorrow
![](https://d.pr/free/i/Ev4kId+)

**Comment by xdamman** [comment]
The SVG works for me on Firefox, Chrome, Safari.

It was probably related to the issue we had with Nginx over the weekend. I'll close the issue for now but don't hesitate to re-open it if you hit this error again.

**Comment by itsjavi** [comment]
@xdamman to give you an idea of what was happening, when I checked the source code of the SVG, it was like if it was truncated, incomplete, as mentioned, so that was causing a syntax error because the SVG document wasn't complete.

**Comment by xdamman** [comment]
Yes that matches the error we've seen elsewhere in the system were some api calls were also truncated if too long. Nginx was out of disk space and everything that required it to write to disk was causing an issue. Sorry for the inconvenience!
