### ISSUE TITLE
Contribute buttons don't work

### ISSUE THREAD

**Issue by alexanderby** [opencollective/opencollective#990]
Click on `.TierCard .action` and `.CustomDonationTierCard a` don't do anything.

Buttons on `/donate` page also don't work, clicking on "Contribute" button sends all the filled-in fields as query parameters of a GET request.

There is some error with loading `createOrder.js`

**Comment by piamancini** [comment]
Hi @alexanderby I can't repro this, what collective are you trying to donate to?

**Comment by alexanderby** [comment]
This started to work just now.

This happened for all collectives, all the "Become a backer", "Become a sponsor" and "Make one time donation" buttons didn't work due to a network error when loading `createOrder.js`. Was reported by a user 10 hours ago.

**Comment by piamancini** [comment]
Thanks @alexanderby, there was a weird thing happening with nginx. It's fixed now

**Comment by alexanderby** [comment]
Great, thanks.
![](https://cdn-images-1.medium.com/max/1600/1*2kLD3EnaJ-6INo0O-MvjzQ.jpeg)
