### ISSUE TITLE
Overlay shows NaN %

### ISSUE THREAD

**Issue by asood123** [opencollective/opencollective#998]
See screenshot. Would be nice to not show backers who don't have a logo.

![screenshot 2018-04-05 16 14 04](https://user-images.githubusercontent.com/6106941/38389464-842644fc-38ec-11e8-89b9-613e5b61e324.png)

**Comment by xdamman** [comment]
That bug was only on the transactions page.
I have a fix.

Re: not showing people without an avatar, the problem with that is that people wonder and complain why they aren't there. We should allow people to sign up with their twitter/facebook account to make it easy to fetch a default avatar.
