### ISSUE TITLE
Add link to the help wiki on the homepage and dropdown menu

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#999]
Right now the [help wiki](https://github.com/OpenCollective/OpenCollective/wiki) has great info, but it's hard to find if you don't already know about it. There should be links from the home page and probably also from the FAQ page. Could also be worth adding to the dropdown menu for logged in users.

**Comment by xdamman** [comment]
@piamancini is forum.opencollective.com still a thing? Is it maintained? What's the usage?
Should we consolidate the help there or on the wiki?

**Comment by piamancini** [comment]
we should deprecate forum and focus on the wiki
